### ISSUE TITLE
Odd behavior of "Get-Help" and "man"

### ISSUE THREAD

**Issue by MomIsBestFriend** [PowerShell/PowerShell#10001]
Disclamer: this is my first time reporting a bug, so please tell me what to add/change to help :)

I have found out an odd output change within powershell

![odd_powershell](https://user-images.githubusercontent.com/50263213/60113343-3c996180-977a-11e9-94ac-b0d417d86268.png)

as you can see, I ran the firsrt command as "man" and there was no output, and if the second command is "man" than it outputs the content to the screen.

I don't think this is big deal, but just let you developers know + (I wanted to submmit a bug for a while)

**Comment by kvprasoon** [comment]
I believe you  are using Windows PowerShell and not PowerShell 6+. I am not able to repro in both the envs. Can you share the output of `$PSVersionTable`

**Comment by MomIsBestFriend** [comment]
![version table](https://user-images.githubusercontent.com/50263213/60157293-16fe6d80-97f7-11e9-8155-5a77a5762e00.png)

follow up question: just in case this is not the fourm to submmit bugs. where is the fourm to do so?

**Comment by iSazonov** [comment]
@MomIsBestFriend Please install PowerShell Core latest build and try reproduce the issue.

For Windows PowerShell you could report to UserVoice site.

**Comment by kvprasoon** [comment]
Windows PowerShell user voice: https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by MomIsBestFriend** [comment]
Thank you both. I will reopen this issue if I ever install PowerShell Core.
Good Luck in feature development <3
