### ISSUE TITLE
piping to stdin fails on windows using Julia

### ISSUE THREAD

**Issue by musm** [PowerShell/PowerShell#10008]
- cmd.exe -- > works (extra space)
- powershell.exe --> works
- pwsh.exe --> doesn't work (i.e. the latest powershell) (python works here)

`> echo test | julia -E "readline(stdin)"`

**Comment by chuanjiao10** [comment]
Is it work?
```
echo 'test' | foreach-object { julia -E "command" $_ } 
```

**Comment by musm** [comment]
Seems so
```
> echo 'test' | foreach-object { julia -E "println(ARGS[1]);" $_ }
test
nothing
~
 
```

**Comment by musm** [comment]
@chuanjiao10 how do I make it work if `julia` is the function

`function julia { & "C:\tools\Julia\julia-1.x\bin\julia.exe" $args }`

**Comment by chuanjiao10** [comment]
function julia2 
{ 
param
(
$a,
$b
)

& "C:\tools\Julia\julia-1.x\bin\julia.exe" $a $b 
}

julia2  'abc' 123
