### ISSUE TITLE
variable tab completion does not escape curly quotes, potentially others

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10006]
Similar to #9881, while attempting to tab complete a variable reference, at least curly quotes (I've also determined en-dash/em-dash too) do not cause an escape to the `${ }` notation.

# Steps to reproduce

```PowerShell
${test`u{2018}var} = 'Hello World'

$t # press tab for completion until `test‘var` appears
```

# Expected behavior

```PowerShell
${test‘var}

```

# Actual behavior

```PowerShell
$test‘var
```

I believe this is part of the issue:
https://github.com/PowerShell/PowerShell/blob/981c990d747ae97f56a6c7474e5d2ef04bf237c5/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4565-L4566

I think this is inadequate to catch the conditions that require when the `${ }` notation is needed, but the above constant appears to be used for more than just that.  The list of characters that require the `${ }` notation is much larger and more complicated.  If regex could be used, the following might be more accurate for when to require the `${ }` : `^(?:[^$^\w?:]|[$^?].)|.(?:::|[^\w?:])` This would return a MATCH when `${ }` is required.  Examples:

`$`  false
`$$` true
`^` false
`^^` true
`?` false
`??` true
`_?` false
`::` false
`a::` true
`test‘var` true

# Environment data

This particular example was captured with 6.2.0 on Win 10 Pro 18922 (Insiders)

__Edit: improved performance of the regex example.__

**Comment by msftrncs** [comment]
Also, slightly related,

```PowerShell
${test`{`}} = 'Hello World'

$t # press tab for completion until `{test{}}` appears
```

# Expected

```PowerShell
${test`{`}}
```

# Actual
```PowerShell
${test{}}
```
This will cause an error stating that you must use ``` `{ ``` instead of  ``` { ``` in variable names.

**Comment by vexx32** [comment]
This is actually further complicated, because the variables `$$`, `$^`, `$!` etc are all special. They _should_ require braces, but the tokenizer explicitly allows them as special variables.

**Comment by msftrncs** [comment]
Never heard of `$!`.  The regex above was set to handle the fact that the tokenizer accepts those special conditions.

**Comment by msftrncs** [comment]
I think I might have missed `$?` ...

**Comment by msftrncs** [comment]
Also adding that `$??` also fails to be completed correctly as `${??}`, as I noticed `?` was not in the constant list of characters in the code referenced.

**Comment by msftrncs** [comment]
Sample PowerShell filter code for testing:

```PowerShell
filter variablenotate {
    if ($_ -match '^[^$^\w?:]|^[$^?].|.+?[^\w?:]|.+?::') {
        "{$($_ -replace '[{}]', '`$0')}"
    } else {
        $_
    }
}
```

Note that a more complete filter might escape all control characters, such that \<TAB\> (^I) would become ``` `t ``` and so on.

**Comment by msftrncs** [comment]
Also adding that variables with backticks in their name will properly wrap with `${ }` when completed but fail to escape the backtick in that notation.

**Comment by msftrncs** [comment]
I've also found that there are some issues around variables that contain `:` (I know there are some opinions there), but demonstrating a more complete escaper:

```PowerShell
filter variableNotate {
    param(
        [string]$ScopeOrProviderPrefix = '' # specify either scope or provider prefix
    )
    [pscustomobject]@{ 
        ListItemText = $_
        CompletionText = "$($(
            if ($ScopeOrProviderPrefix -eq '') {
                if ($_.Contains([char]':')) {
                    ":$_"
                } else {
                    $_
                }
            } else {
                "${ScopeOrProviderPrefix}:$_"
            }
        ).foreach{
            if ($_ -match '^[^$^\w?:]|^[$^?].|.+?[^\w?:]|.+?::') {
                "{$($_ -replace '[{}`]', '`$0')}"
            } else {
                $_
            }
        })"
    }
}
```

This filter now produces an output similar to the CompletionResult class.

Example usages: (uses aliases)
```PowerShell
(dir env:*).name | variableNotate 'env'

(dir variable:*).name | variableNotate
```
Both above should demonstrate the correct escaped completion to use with the `$` sigil.

(Partial Output from `env:*`)
```None
ListItemText                    CompletionText
------------                    --------------
OS                              env:OS
CommonProgramFiles(x86)         {env:CommonProgramFiles(x86)}
HOMEPATH                        env:HOMEPATH
ProgramFiles(x86)               {env:ProgramFiles(x86)}
ProgramData                     env:ProgramData
TMP                             env:TMP
```
(Partial Output from `variable:*`)
```None
ListItemText                CompletionText
------------                --------------
$                           $
^                           ^
?                           ?
*hello                      {*hello}
hello                       hello
@hello                      {@hello}
a                           a
`                           {``}
::                          {:::}
:                           ::
```

While writing this up, I also found that the `*Hello` variable doesn't complete correctly, `*` is also missing from the list of characters that require escape, but you can see this filter suggests the correct completion.

**Comment by msftrncs** [comment]
I have an intention to post a PR regarding at least parts of this issue, implementing the escapers already found in the `CodeGeneration` class, and we'll see how far I can go from there.

**Comment by msftrncs** [comment]
I was able to implement a C# version of my PowerShell filter,

https://github.com/msftrncs/PowerShell/blob/0af1d06de68391d04f77c3efd3db58a8bd23a036/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4804-L4843

Where does this best belong?
