### ISSUE TITLE
Get-Uptime cmdlet return incorrect value

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#10018]
This is related to MicrosoftDocs/PowerShell-Docs#4487

# Steps to reproduce
1. Restart machine
2. Run `Get-Uptime`

# Expected behavior

Return the timespan since boot.

# Actual behavior

Returns the same value every time.

```none
Days              : 8
Hours             : 23
Minutes           : 46
Seconds           : 18
Milliseconds      : 0
Ticks             : 7767780000000
TotalDays         : 8.99048611111111
TotalHours        : 215.771666666667
TotalMinutes      : 12946.3
TotalSeconds      : 776778
TotalMilliseconds : 776778000
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Note that Win32_OperatingSystem and Get-Time report the same value:

```
get-ciminstance win32_operatingsystem | select LastBootUpTime

LastBootUpTime
--------------
6/18/2019 2:35:08 PM

Get-Uptime -Since

Tuesday, June 18, 2019 2:34:56 PM
```

Neither of these values is accurate.

**Comment by BrucePay** [comment]
@sdwheeler You might want to update the title to say `get-uptime` instead of `get-time`.

**Comment by chuanjiao10** [comment]
guess:
You have enabled a quick boot.
an examination:
Powercfg -h off
Shutdown -r -t 20

rebooting .....

Get-Uptime

**Comment by iSazonov** [comment]
We use .Net Core `Stopwatch.GetTimestamp()` (HPET) so it is a documentation issue.

**Comment by iSazonov** [comment]
@sdwheeler  Can we close the issue?
