### ISSUE TITLE
Backport DSC compilation fixes to PowerShell Core 6.2.

### ISSUE THREAD

**Issue by amitsara** [PowerShell/PowerShell#10014]
# Details
DSC team needs to support DSC compilation on PowerShell core 6.2 for GuestConfiguration Custom Policy Public Preview.
Changes from following PRs has to be backported to enable the DSC compilation on Linux & Windows.
1.	Support DSC compilation on Linux.
https://github.com/PowerShell/PowerShell/pull/9834
2.	Import-DscResource should allow to overwrite DSC built-in resources.
https://github.com/PowerShell/PowerShell/pull/9879
3.	Download latest version (6.2.0) of PSDesiredStateConfiguration nuget package.
 https://github.com/PowerShell/PowerShell/pull/9932

**Comment by TravisEz13** [comment]
@amal-khalaf These are all the PRs?  You aren't expecting any more?

**Comment by amitsara** [comment]
> @amal-khalaf These are all the PRs? You aren't expecting any more?

No, these are only the PRs need to be back ported.

**Comment by ThomasNieto** [comment]
Is 6.2 getting any new releases? If not, should this be closed?
