### ISSUE TITLE
`Start-PSBuild -Clean` will remove untracked files without prompt or warning

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10021]
# Steps to reproduce

1. Add some .cs files with things you are working on that don't happen to be tracked yet.
1. Invoke `Start-PSBuild -Clean` to kick off a clean build process.
1. Your untracked files are deleted without warning or prompt, and they don't even go into your recycle bin.

# Expected behavior

`Start-PSBuild -Clean` should not delete untracked source files without prompt by default (which `git clean` does). That is a really poor decision. I just lost a good chunk of work because of that behaviour, and now I'm losing time trying to get it back. All I wanted was a clean build (i.e. remove any temporary build files, and then rebuild). I did _not_ want to remove files I happen to have in my file system that may be important to me.

# Actual behavior

Any untracked files you have are removed without warning and without even going to the recycle bin.

# Environment data

Irrelevant, but I happen to be invoking `Start-PSBuild` in Windows PowerShell 5.1.

**Comment by vexx32** [comment]
Looking at [the documentation](https://git-scm.com/docs/git-clean) it seems we should be using `git clean` with the `-X` option (capital X) to remove only the files that are in `.gitignore` and not "manually created files" as it calls them. 🙂
