### ISSUE TITLE
Invoke-Command hangs when connecting from Windows 10 to Ubuntu 18.04

### ISSUE THREAD

**Issue by adbertram** [PowerShell/PowerShell#10026]
# Notes
SSH works from Windows to Linux via `adam@<UbuntuIP>`.
I am RDPed into a fresh Windows 10 Azure VM and attempting to connect to a fresh Azure, Ubunto 18.04 VM using it's public IP.

# Steps to reproduce

## On Ubuntu 18.04
1. Install PS with `snap install powershell --classic`
2. Add `Subsystem powershell /usr/bin/pwsh -sshs -NoLogo -NoProfile` to _/etc/ssh/sshd_config_
3. Restart SSHD with `sudo service sshd restart`.

## On Windows 10 17763.557

```powershell
Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
Start-Service sshd
Set-Service -Name sshd -StartupType 'Automatic'
mklink /D c:\pwsh "C:\Program Files\PowerShell\6"
Restart-Service sshd
```

From Windows, run `icm -HostName <IPAddress> -UserName <LinuxUser> -ScriptBlock {1}`

# Expected behavior

To return 1

# Actual behavior

1. Prompts for password
2. Hangs indefinitely after correct password is input

# Environment data

Windows
```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Ubunto 18.04
```none
PS /home/adam> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Linux 4.18.0-1023-azure #24~18.04.1-Ubuntu SMP Tue Jun 25 15:14:42 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chuanjiao10** [comment]
this work?
```
Subsystem powershell /snap/bin/pwsh -sshs -NoLogo -NoProfile
```

**Comment by chuanjiao10** [comment]
if windows as a ssh server ,then need sshd
https://www.cnblogs.com/piapia/p/10763737.html

**Comment by adbertram** [comment]
Yep. That did it. I didn't even think the path needed to be changed since I installed it via Snap. Doh! Thanks.
