### ISSUE TITLE
kill still an alias of Stop-Process on *nix

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#10036]
Just tried `kill` on macOS and it's an alias of `Stop-Process`. I thought all the aliases masking native utils were taken out?

**Comment by chuanjiao10** [comment]
on linux be same,i don't know it is by design,or not.

**Comment by iSazonov** [comment]
Removing this would be a breaking change.
See https://github.com/PowerShell/PowerShell-RFC/pull/129

**Comment by chuanjiao10** [comment]
when vscode-powershell can format  kill to stop-process force. and foreach to foreach-object.
when we can stop that two alias?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee agrees we should remove this alias as it's an oversight and not intentional for this alias to be there
