### ISSUE TITLE
Build test tools in parallel during CI

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#10037]
# Summary of the new feature/enhancement

Currently we compile our test tools in every test job on CIs.
We could do this in parallel with job building pwsh.
It will save about 2 minutes and consumed resources.

/cc @RDIL @TravisEz13

**Comment by RDIL** [comment]
What do you mean by test tools?

**Comment by iSazonov** [comment]
If we run Start-PSPester we compile some test helper tools from test/tools folder before run tests.

**Comment by TravisEz13** [comment]
@iSazonov Do you mean during CI or locally?

**Comment by iSazonov** [comment]
@TravisEz13 During CI.

**Comment by TravisEz13** [comment]
Even doing this in the main build would technically be a compute time savings, but not a clock time savings.  I agree this would be worth doing.  We have done something like this for release build testing.  cc @adityapatwardhan

**Comment by RDIL** [comment]
Or we could just use caching...

**Comment by TravisEz13** [comment]
It's possible.  The artifact system in AzureDevOps is pretty slow.  My intuition is that using the cache will be slower that building, unless that made the caching an order of magnitude faster than other artifacts operations.

I'd like to know either way.

One way to make this work would be to:

1. Restore the cache(s)
1. make the `-SkipTestToolBuild` build if the files are not there and use this in CI
1. save the cache(s)

**Comment by TravisEz13** [comment]
Caching was introduced . https://devblogs.microsoft.com/devops/caching-and-faster-artifacts-in-azure-pipelines/
