### ISSUE TITLE
Invoke-RestMethod with ContentType application/json returns YAML instead of JSON

### ISSUE THREAD

**Issue by NeoXtreem** [PowerShell/PowerShell#10039]
# Steps to reproduce

Call the following where `https://mydomain/foo` is a valid REST method:
```powershell
Invoke-RestMethod -Uri https://mydomain/foo -Method GET -ContentType application/json
```
This issue may be similar to #3131 although that's to do with a POST method.

# Expected behavior

Returns data in JSON format.

# Actual behavior

Returns data in YAML format.

# Environment data

```none
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      0      preview.1
```

**Comment by KalleOlaviNiemitalo** [comment]
The `-ContentType` parameter appears to control the `Content-Type` header field of the HTTP request, which is not relevant in your case because you are not sending any content in the request. Perhaps you want `-Headers @{ Accept = "application/json" }` instead.

**Comment by NeoXtreem** [comment]
> The `-ContentType` parameter appears to control the `Content-Type` header field of the HTTP request, which is not relevant in your case because you are not sending any content in the request. Perhaps you want `-Headers @{ Accept = "application/json" }` instead.

Thanks. I was misusing the method and expecting JSON back which is incorrect.
