### ISSUE TITLE
Extra allocations value types

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#10055]
The test shows

```powershell
$a=[WildcardPattern]::new("a1234567890*")
for ($i=1; $i -lt 5000000; $i++) { $null = $a.IsMatch("a123456789012345678901234567890a123456789012345678901234567890a123456789012345678901234567890" ) }
```
that we (extra) allocate:
1. System.Boolean. 
2. System.In32

![image](https://user-images.githubusercontent.com/22290914/60605197-7f8ab300-9dd2-11e9-9737-0142e8ab8001.png)

For Boolean it is not clear where root of the problem
![image](https://user-images.githubusercontent.com/22290914/60605392-dd1eff80-9dd2-11e9-94fe-16ba417ffa8b.png)

For Int32 it seems it is common problem in NumericOps.cs file due to casting/boxing everything to object
![image](https://user-images.githubusercontent.com/22290914/60605783-94b41180-9dd3-11e9-8051-3b91fb167286.png)

/cc @daxian-dbw

**Comment by iSazonov** [comment]
Also on screenshot above we see huge allocations for:
- System.Management.Automation.VariableScopeItemSearcher
- System.Management.Automation.SessionStateScopeEnumerator

**Comment by iSazonov** [comment]
@daxian-dbw I tried to fix VariableScopeItemSearcher in #10082 without success. There is a race condition related to runspaces. What do you think about VariableScopeItemSearcher? Make sense to fix the allocation? Convert it to regular method?

Also I looked in allocating value types. I did not found where Boolean boxed. It seems in Core runtime. I am not know how we can fix this.
Ints is boxed in IntOps.Add() and it seems we need to generate more smart Linq Expressions to fix this. Could you please share your thoughts?

**Comment by daxian-dbw** [comment]
@iSazonov Are you sure the script you use is a real scenario? When this script snippet is running in a local scope, variable will be optimized to use local tuples instead of looking up the scope chain, and thus `VariableScopeItemSearcher` won't be used at all.
Only when this is dot sourced or running in console directly, the variable will be searched by looking up scopes.

**Comment by iSazonov** [comment]
I run in console. It seems a real scenario too because we often copy code in console.
I tried follow
```powershell
Measure-Command {
$a=[WildcardPattern]::new("a1234567890*")
for ($i=1; $i -lt 5000000; $i++) { $null = $a.IsMatch("a123456789012345678901234567890a123456789012345678901234567890a123456789012345678901234567890" ) }
}
```
and get 
![image](https://user-images.githubusercontent.com/22290914/60939322-a2e0c100-a2f0-11e9-892a-8fe0b3194533.png)

Here we see a lot of SessionStateScopeEnumerator allocations. 

As for the first example it seems variable `$a` could be defined as global in console scenario to be optimized.

**Comment by daxian-dbw** [comment]
`Measure-Command { ... }` will run the script block in the parent scope, not a local scope. So it's the same as running it directly in the console.
I don't think it's a scenario that we should concern too much. It would be very rare for people to run code that has a large number of variable references directly in the console. In normal cases, people will run a `.ps1` or a `function` that will execute in its local scope, where the optimization will be on for variable references.

**Comment by iSazonov** [comment]
There is Jason's comment https://github.com/PowerShell/PowerShell/pull/10082#issuecomment-510146827. It seems he describes the same that you mentioned.

**Comment by daxian-dbw** [comment]
Great, I will close this issue then.
