### ISSUE TITLE
Is changing the name of a parameter set considered breaking?

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10058]
Are parameter set names considered contractual, and therefore changing a parameter set name is considered breaking, or can they be changed as required (i.e. when moving parameters into a new base class as part of a refactoring effort performed while fixing some issues in a set of commands that share those parameters)?

The [breaking change documentation](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md) does not mention parameter sets at all, and therefore I would think parameter set names are not contractual, but thought I should check first to make sure.

cc: @SteveL-MSFT

**Comment by BrucePay** [comment]
@KirkMunro Thanks for bringing this up. We decided way back in V1 that changing the name of a parameter set would officially not be considered a breaking change.  But of course it's a publicly visible property so i'm sure people have taken dependencies on them. At this point, the Committee should probably review this decision/guidance and update it if necessary.

**Comment by iSazonov** [comment]
I would not want it to be a breaking change because we have already discussed that parameter binding should be enhanced to support more features (like PSMore idea and more flexible parameter set description notation)

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We continue to agree that ParameterSet names are not a public api and changing them is not a breaking change.  We should update the breaking change contract doc to make this apparent and explicit.
