### ISSUE TITLE
Need tests for Regex 

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#10051]
We need tests for PowerShell Regex API in WildcardPattern class.

Perhaps MSFT team can port Unit tests
https://github.com/PowerShell/PowerShell/blob/0d55a7249b7a4188b18dab89c004d7be3eae7d7e/src/System.Management.Automation/engine/regex.cs#L722

**Comment by kvprasoon** [comment]
@iSazonov  Hope this can be closed :-)

**Comment by iSazonov** [comment]
@kvprasoon I added tests only for two methods. I think we could add more tests.
