### ISSUE TITLE
Support Fedora 29 and 30

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10060]
# Details of the Distribution

- Name of the Distribution: Fedora
- Version of the Distribution: 29 and 30
- [x] The version of the Distribution is supported for at least one year.
- [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.
- [x] The version of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

## Progress - For PowerShell Team **ONLY**

- [x] Docker image created - https://github.com/PowerShell/PowerShell-Docker/pull/243
- [x] Docker image published
- [x] Distribution tested
- [x] Lifecycle updated
- [x] Documentation Updated

**Comment by thorian93** [comment]
Any update on this?
Kind of waiting for it.

**Comment by TravisEz13** [comment]
@thorian93 status is above.  Only thing left is updating the documentation.

**Comment by thorian93** [comment]
@TravisEz13 Thanks for the quick answer! So if I use this repo (https://packages.microsoft.com/config/rhel/7/prod.repo), following the official docs for Fedora (https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#fedora) it should work already?
And if not that would be a separate issue to troubleshoot and not a general OS support topic, right?

**Comment by TravisEz13** [comment]
I updated the docs yesterday.  There were no changes to the docs, we **have** tested this.

**Comment by TravisEz13** [comment]
https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4903
