### ISSUE TITLE
what verison 6.2.1 or 6.1.4 or 7.0 preview

### ISSUE THREAD

**Issue by stalebhacine** [PowerShell/PowerShell#10068]
I have windows 10 (1903), what is the version to install 6.2.1 or 6.1.4 (same date) or 7.0 preview (last one but what is preview here), I am a beginner, thanks again

**Comment by doctordns** [comment]
It depends on what you are looking for. 7.0 Preview is the latest version.

**Comment by iSazonov** [comment]
Latest released version is 6.2.1.
