### ISSUE TITLE
JEA Versioning PSSessionConfiguration 

### ISSUE THREAD

**Issue by timoline** [PowerShell/PowerShell#10077]
As far as I can see, there is no versioning in the configuration of JEA

It would be nice if we could add some versioning to the configuration
and then Get-PSSessionConfiguration should also output the version.

I'm not sure this is the correct repo for this?

**Comment by PaulHigin** [comment]
WG-Security:
We are not sure about impact since configuration name can implicitly contain version information.  So we are labeling this as an enhancement issue for future consideration.
