### ISSUE TITLE
powershell sometimes doesn't interpret variables within parameters (external commands)

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#10075]
This is more for 3rd party programs like ghostscript.  See https://stackoverflow.com/questions/15489502/powershell-and-ghostscript/56923846#56923846  This will output to a file literally called '$OutputFile'.  The variable isn't interpreted unless it's double quoted.

gswin64c -sOutputFile=$OutputFile

I can demo it with any command.  If it's a pain to change, it would be nice if it was documented.

# Steps to reproduce

```powershell
$a = 'hi'
echo -inputobject$a
```

# Expected behavior

```none
-inputobjecthi
```

# Actual behavior

```none
-inputobject$a
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The issue that summarizes all parameter-parsing oddities is #6467 (your particular finding was originally discussed in #4624, but I've just folded a summary into #6467).

There already is a tracking issue in the docs repo for #6467, https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3038.
