### ISSUE TITLE
How to change the default behavior of powershell -- use port 80 as default to connect client

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#10079]
Microsoft has a great product, that is windows admin center(WAC), it use PS to connect target, but there is one shortage, it instruct PS to use its default behavior (use port 5985) to connect target , do not have an option to instruct PS to use port 80 or 443 (Compatibility mode) to connect target.

In my environment , PS can reach target via port 80 only. For this problem ,I already post a request in WAC user voice -- https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/38030116-connect-client-via-port-80

https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/33981802--configuration-winrm-connect-using-non-default

As only a few users have that demand , so WAC team did nothing for my request.

But if I can change PS's default behavior -- use port 80 as default , then my WAC problem will go way.

Any one can provide me a good solution ?

Thank you in advance!

**Comment by iSazonov** [comment]
See https://blogs.msdn.microsoft.com/wmi/2009/07/22/new-default-ports-for-ws-management-and-powershell-remoting/
