### ISSUE TITLE
The equivalent of "rpm -ql" in powershell

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#10078]
I met a problem when I worked on outlook.
I want to remove all files or settings that associated with a user in outlook. or just uninstall office 2016 ,then install it again.

But I am afraid after I uninstall office 2016 , it is still have some user setting remain in user profile.
If I need to remove office 2016 completely  ,then I need to know all the path to those office installation folders and files and registry key.

In linux , we can use rpm -ql packagename (let's say software package name in windows). to find all files and folders for a specific package.
```
[root@www ~]# rpm -ql openssh-server
/etc/pam.d/sshd
/etc/ssh/sshd_config
/etc/sysconfig/sshd
/usr/lib/systemd/system/sshd-keygen.service
/usr/lib/systemd/system/sshd.service
/usr/lib/systemd/system/sshd.socket
/usr/lib/systemd/system/sshd@.service
/usr/lib64/fipscheck/sshd.hmac
/usr/libexec/openssh/sftp-server
/usr/sbin/sshd
/usr/sbin/sshd-keygen
/usr/share/man/man5/moduli.5.gz
/usr/share/man/man5/sshd_config.5.gz
/usr/share/man/man8/sftp-server.8.gz
/usr/share/man/man8/sshd.8.gz
/var/empty/sshd
```
How about windows , will it possible to this kind of cmdlet ?

Waiting for good news.

**Comment by iSazonov** [comment]
If Office is installed from msi - the Microsoft Window trusted installer subsystem is tracking all files.
If Office is installed by ClickToRun from Cloud - I don't know how the ClickToRun works, it seems it is not public and not documented.
In any case the question is not related to PowerShell.
