### ISSUE TITLE
[QUESTION] How to manipulate File AccessControl?

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShell#10088]
In .NET Core, DirectoryInfo and FileInfo no longer has a SetAccessControl method.  This logic was moved into https://www.nuget.org/packages/System.IO.FileSystem.AccessControl/ . 

While I can access this package easily enough through binary cmdlets, what is the right way to load this dll in PowershellCore / Powershell 6+?

As an example, I want to port Boe Prox's `Set-Owner` function to PowerShell Core: https://github.com/proxb/PowerShell_Scripts/blob/master/Set-Owner.ps1

**Comment by iSazonov** [comment]
You could use Add-Type -AssemblyName

**Comment by jzabroski** [comment]
@iSazonov Thanks, that worked!
