### ISSUE TITLE
Support for Debian 10

### ISSUE THREAD

**Issue by khaffner** [PowerShell/PowerShell#10080]
Now that Debian 10 Stable is released, could we get official support for this version? Thanks! 👍

**Comment by joeyaiello** [comment]
We typically snap to underlying .NET support, and it looks like they're adding support for Debian 10 (listed as "9+") on the [.NET Core 3.0 support page](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md), as opposed to just "9" on the [2.2 support page](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md). 

So yeah, we should probably try and have a Debian 10 package by the time 7.0 GAs.

**Comment by bergmeister** [comment]
Yes, in fact their default SDK docker images tagged with 3.0 are even based on Debian 10

**Comment by TravisEz13** [comment]
The Debian docker image was JUST released.  I went to filed this image based on dependabot opening a PR in the PowerShell docker repo yesterday.

**Comment by TravisEz13** [comment]
The process will be, we will create a docker image, support it experimentally until it is tested, and once tested we can officially support it.  We need to document this process for new Linux distribution releases.

**Comment by TravisEz13** [comment]
Filed an issue using the Distribution Support request template #10255
