### ISSUE TITLE
Feature Request: LastCommand automatic variable

### ISSUE THREAD

**Issue by atruskie** [PowerShell/PowerShell#10089]
# Summary of the new feature/enhancement

I would like more information about the last _ReadLine_ command that was executed. I'm primarily thinking about tooling enhancements for interactive scenarios (in particular for customising `Prompt`), but I can think of a bunch of other uses for this information.

I'm thinking this `$LastCommand` automatic variable should serve a similar role to `$MyInvocation`.  However, unlike `$MyInvocation`, `$LastCommand` information would be available after the command had run, and not be overwritten in a function call. 

`$LastCommand` should basically be supplied every time the `Prompt` function needs to be invoked.

# Proposed technical implementation details (optional)

After every "read line" command is executed, set the `$global:LastCommand` automatic variable is set to an object, with the following fields:

```
@{
  # The command that ReadLine/PSReadLine asked PowerShell to run
  [string]Command = ".."
  # Time spent executing the command (similar to what is stored in Get-History items at the moment
  # but it will also work for commands that are not added to history for some reason
  [TimeSpan]Elapsed = ...
  # A list of the exit codes for any native commands that were run (there could be many)
  [int[]]ExitCodes = @(...)
  # Like $Error but scoped to the last command
  [ErrorRecord[]]$Error
  # Like $? but better
  Status = "OK"
  # Link to history for some useful synergies, or null if not added
  [int]HistoryId = 123
}
```

I think the real drawcard here is `Status`. It would be an Enum/string that could capture all of PowerShell's diverse forms of error:

- "OK"/"Completed" indicated a command/pipeline indicated without any failures
- "CompletedWithErrors" would reflect a pipeline that completed but still populated the `$Error` record (e.g. in cases of `SilentlyContinue`)
- "Failed" where a terminating error (like `throw`) stops execution
- "Cancelled" when `ctrl+c` stops execution
- "Empty" - not sure if this one is necessary but it would reflect cases where `ReadLine` was supplied an empty string and the effective command was a noop
- ... and any I missed

# Alternatives

## Why not `$?`

- `$?` is dismissed as soon as you run any other command. This an issue others have run into:
  - https://github.com/PowerShell/PowerShell/issues/9363
  - https://github.com/dahlbyk/posh-git/blob/a64e5e073f6ce4dcd01394965bf0bbc91a0e3016/src/posh-git.psm1#L32
- `$?` is not always updated. Especially when a ReadLine is cancelled, or is an empty string

## Why not `$Error`

Because it doesn't capture cancelled commands, empty commands, or native commands.

## Why not `$LASTEXITCODE`

`$LASTEXITCODE` is only set when native commands run. But annoyingly, the value is not automatically dismissed. In Bash this is not a big deal (I think) because every command executed has an exit code that updates last exit code (again, mostly speculation). However, in PowerShell, if you run a native command, then run a PowerShell command, which may fail or succeed, then checking the $LASTEXITCODE is misleading. It does represent the last exit code of the last native tool that was run, but this may not be the last user-supplied command or even the last 10 commands.

This is not a big deal in a script, because an author understands this context. But from a tooling perspective, there's no way to understand what just happened unless you start parsing the supplied command. I figure PowerShell could do this for me.

## Why not use Get-History or augment it with new fields

`Get-History` is great but its goal is not well aligned with providing information about the user's last command. Get-History actually supplies information about the last command, that is not a duplicate, and that was not cancelled, or an empty string...

I'm interested in what happens in and around a user typing a command. Get-History I think shouldn't capture all the information in my proposal and just continue recording history.

# Open questions

- The name `$LastCommand` is IMO nice, but probably a poor choice. Other choices:
  - `$LastReadline`
  - `$LastPrompt`
  - `$LastResult`
- The names, types, and variables in the `$LastCommand` could all probably be improved
- I'm only thinking about an interactive scenario. I'm not sure my suggestion has any meaning inside a script...
- If it is only useful in interactive scenarios, it could be supplied to the `Prompt` function as an argument, rather than being set as a global variable
- I'm not wholly familiar with all the types of errors
- There is a security concern with getting access to the commands that were run, but it is no worse than hijacking PSReadLine's  `[Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState` method anyway.

# Related links

- https://github.com/PowerShell/PowerShell/issues/9363
- https://github.com/PowerShell/PowerShell/issues/7853
  - A similar idea, that got derailed with a non-solution
- https://github.com/PowerShell/PowerShell/issues/9140

**Comment by chuanjiao10** [comment]
en ,good idea.
'$^'    and         '$$'   ，i recommend it to you.
I hope it can partially solve your problem.

**Comment by atruskie** [comment]
@chuanjiao10: `$^` and `$$` can be useful but come nowhere near exposing enough useful information.

```
> ls | ? { $_.Name -eq 'blah' } | Select-Object
> "$^;$$"
ls;Select-Object
```

It misses the middle token altogether.

**Comment by chuanjiao10** [comment]
yes,
if no "|", $$ is last command.
2+3 ,$$ is 3
it is partially.

**Comment by heaths** [comment]
I like the overall sentiment here and was going to request something similar, though I would prefer to see this information (perhaps in addition to what was suggested) in the history. I already have a `$prompt` function that makes use of history (along with some types-added script properties) but can't really approximate the behavior suggested in this feature request for the reasons given. How `$LASTEXITCODE` is handled - specifically that it's not reset - and because `$?` is always `$true`  in the `$prompt` function (perhaps this is set after `$prompt` is invoked?) means I need this support in PowerShell itself.
