### ISSUE TITLE
Has this repo still got Cmake/C++ dependencies?

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10094]
Since `powershell-native` has moved into its own repo a while ago, it seems one does not need cmake or C++ tooling any more. Can we remove it, to me it seems to be  not needed any more?
We still recommend vscode extensions for those tools and there are various left-overs in the docs.
https://github.com/PowerShell/PowerShell/blob/master/.vscode/extensions.json

**Comment by iSazonov** [comment]
It can be useful if we work on powershell-native too in a PR.

**Comment by bergmeister** [comment]
Ok, thanks, so the conclusion is that the C++/Cmake vscode extension are still needed for the PowerShell/PowerShell repo if I understand correctly?
Feel free to close the issue then if the answer is yes.

**Comment by iSazonov** [comment]
It is needed for powershell-native repo. If somebody will add/remove a p/invoke for Unix he/she has to work with both repos and C code.
