### ISSUE TITLE
Set-PSBreakpoint allows you to set the same breakpoint again, and again, and again

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10117]
The `Set-PSBreakpoint` command allows you to set a breakpoint multiple times. Most users never encounter this because if they debug and use breakpoints, they do so from Visual Studio Code or PowerShell ISE. For users who use the command line and set breakpoints that way, this behavior leads to additional breakpoints being created that are not necessary and do not add any value to their debugging experience.

# Steps to reproduce

```powershell
Set-PSBreakpoint -Command Get-Process
Set-PSBreakpoint -Command Get-Process
Set-PSBreakpoint -Command Get-Process
```

# Expected behavior

```none
  ID Script                            Line Command                           Variable                          Action
  -- ------                            ---- -------                           --------                          ------
   0                                        Get-Process
```

# Actual behavior

```none
  ID Script                            Line Command                           Variable                          Action
  -- ------                            ---- -------                           --------                          ------
   0                                        Get-Process

  ID Script                            Line Command                           Variable                          Action
  -- ------                            ---- -------                           --------                          ------
   1                                        Get-Process

  ID Script                            Line Command                           Variable                          Action
  -- ------                            ---- -------                           --------                          ------
   2                                        Get-Process
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Desired outcome

I would like to change this behavior such that `Set-PSBreakpoint` does not create duplicates, by having it look at existing breakpoints when a breakpoint is set. If an exact match is found, that breakpoint is returned to the caller. Otherwise, the new breakpoint is set and returned to the caller. There is no value in allowing multiple breakpoints that are 100% identical to be set in a debugger. In fact, graphical debuggers don't allow you to do this, so the command line shouldn't either.

**Comment by bpayette** [comment]
@KirkMunro Don't forget about actions. Each breakpoint object can have it's own action q.e.d multiple breakpoints are necessary.

**Comment by KirkMunro** [comment]
That wasn't my point. My point was that if you're setting a breakpoint that is already set _the exact same way_ (same line/column/command/variable/script/action), then that should just give you back the breakpoint you're setting. When working from the command line using PSReadline's Ctrl+R or just up arrow to set-breakpoint commands between sessions, it's easy to set a single breakpoint twice the exact same way. That's what I want to prevent.

**Comment by rkeithhill** [comment]
Yeah, I'd expect what you're talking about to be a simple idempotent operation. Looks like the impl reflects the *desire* to have multiple breakpoints with different actions/commands/variable but nobody bothered to check if those actions/command/variable are actually different.  BTW, in your example with `Get-Process`, it doesn't actually break three times, does it?

**Comment by KirkMunro** [comment]
In my example it breaks once, but shows three triggering breakpoints that only differ by their ID when it does.

**Comment by iSazonov** [comment]
@TylerLeonhardt @rjmholt Perhaps it could be important for VS Code PowerShell extension.

**Comment by TylerLeonhardt** [comment]
If a fix for this was done at the API layer, then PowerShell Editor Services could be affected.

If a fix for this is done at the cmdlet layer, then PowerShell Editor Services would not need affected.

Thanks for keeping it in mind @iSazonov!
