### ISSUE TITLE
Support Question

### ISSUE THREAD

**Issue by lukepuplett** [PowerShell/PowerShell#10139]
# Support Question

Hey - After installing `PowerShell-6.2.1-win-x64.msi` which I think is PS Core (the filename isn't named or branded clearly IMO) there is no obvious Start Menu shortcut installed.

I have these.

- Windows PowerShell
- Windows PowerShell (x86)

And when I launch either I get

> Try the new cross-platform PowerShell https://aka.ms/pscore6

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack][powershell-slack] and [Discord][powershell-discord] Community Chat - Interactive chat with other PowerShell enthusiasts. Both Slack and Discord are bridged via a bot and can seamlessly talk to each other.
[PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

[powershell-slack]: https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM
[powershell-discord]: https://discordapp.com/invite/AtzXnJM

**Comment by lukepuplett** [comment]
I don't know what's going on, whether its the Windows 10 menu I am clearly unable to use, or what. I reinstalled and checked and I see it now. Sorry!! Closed.

**Comment by vexx32** [comment]
For reference as well -- you'll find the binary name for PS 6.0+ changed as well, as it's meant to run side by side with Windows PowerShell for now, so if you run `powershell` in a console you'll get back to 5.1. 6.0+ can be accessed by calling `pwsh` instead. 🙂
