### ISSUE TITLE
Add sshd configuration to binary installers

### ISSUE THREAD

**Issue by wjk** [PowerShell/PowerShell#10140]
# Summary of the new feature/enhancement

As a user, if I install PowerShell on a Mac or Linux computer, I would want to be able to manage it remotely using the SSH protocol. I must currently manually edit the `sshd_config` file to enable the PowerShell SSH subsystem on each target computer, or otherwise the `New-PSSession` cmdlet will emit a nonintuitive error. (See #9925 for more details.) I would appreciate it if the PowerShell prebuilt installers would add the appropriate code to the `sshd_config` file during installation, so I don't have to remember to do this manually.

# Proposed technical implementation details

I would add the following code to the macOS after-install script:

```sh
grep -E -q "^Subsystem\s*powershell" /etc/ssh/sshd_config || \
echo "Subsystem powershell {0} -sshs -NoLogo -NoProfile" >> /etc/ssh/sshd_config
```

(As with the existing code in the macOS after-install script, `{0}` will be replaced with the full path to the pwsh executable.)

Something similar ought to be done for the Linux installers; however, I am not fluent enough with the PowerShell Linux packaging to offer any specific implementation plans there. Thanks!

**Comment by iSazonov** [comment]
@PaulHigin Make sense to implement this in installer?
