### ISSUE TITLE
Tab completion matches first parts of words in CmdLet names

### ISSUE THREAD

**Issue by lukepuplett** [PowerShell/PowerShell#10142]
# Summary of the new feature/enhancement

As a C# dev and occasional PS user I want the tab completion to recognise and cycle the options for shorthand CmdLet names like `New-AzResGroDep` so that I don't have to type so much before the tab completion suggestions are a usefully short list.

In Visual Studio the suggestions work in this way, so entering `this.LogFac` would suggest `this.LoggerFactory`. This is convenient and now natural to a bunch of developers.

`New-AzResGroDep` would suggest `New-AzResourceGroupDeployment`

Thanks

# Proposed technical implementation details (optional)

I've no clue how to do this. I feel bad now.

**Comment by vexx32** [comment]
Wasn't something like this already implemented, @SteveL-MSFT?

I remember hearing about something that would expand tab completions by looking for acronyms or initialisms, did that ever make it in?

**Comment by SteveL-MSFT** [comment]
@vexx32 yes, PS6.2 has abbreviation expansion which will be non-experimental in PS7 preview2.  Basically, in @lukepuplett's example, `n-argp` would expand to `New-AzResourceGroupDeployment`.  It specifically works against the upper case letters so doesn't fuzzy match additional characters.  What @lukepuplett is suggesting is a bit different and more of an expanded version of the abbreviation expansion

**Comment by lukepuplett** [comment]
Okay thanks folks, good news. My suggested behaviour was proposed simply because I'm used to Visual Studio's.

I must point out that the problems for me - and I'm assuming other people, too - are

# Typing long commands.
# Remembering the name of all the commands. Being able to enter some of the tokens I do remember and cycling them would help.

Matching on the initials would solve 1 but doesn't sound like it would help at all with 2.
