### ISSUE TITLE
Repro .NET CLI content failing with .dotfiles

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1014]
This is a bug on Linux that we need to demonstrate and file against .NET CLI.

**Comment by HemantMahawar** [comment]
@andschwa Still relevant?

**Comment by andschwa** [comment]
I don't think so. This was reported by @JamesWTruher and we intended to provide a repro so it could be fixed... but .NET CLI has undergone so much churn we'd have to see if it's even still a bug.
