### ISSUE TITLE
The output from Export-Clixml includes a dead link

### ISSUE THREAD

**Issue by fatherjack** [PowerShell/PowerShell#10158]
# Documentation Issue

When using Export-Clixml to pass information to a file the first line of the resulting XML file is 

> `<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">`

This xmlns link (http://schemas.microsoft.com/powershell/2004/04) results in a 404 error when clicked

**Comment by iSazonov** [comment]
Close as stale issue.
