### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Panzerbjrn** [PowerShell/PowerShell#10159]
# Summary of the new feature/enhancement

I would love a way to block aliases from being imported when I import a module, or from being loaded when PowerShell loads.
As a user, I find it annoying to have to run 'Remove-Item -Path Alias:* -Force' each time I have imported a module, in order to be sure that other modules will import successfully.
The underlying reasons is that a number of modules use the same aliases, and this prevents scripts from loading them.
For-Example: Get-VM is used by the modules virtualmachinemanager, Hyper-V & PowerCLI.

# Proposed technical implementation details (optional)
A -NoAliases switch could be added to the Import-Module cmdlet, which would prevent aliases from being created. 
Alternatively, the existing -force switch could be enhanced to overwrite existing aliases rather than failing to import the module.

Example:
Import-Module -Name Hyper-V -NoAlias
This would import the Hyper-V module, but without importing any aliases from the module.

**Comment by vexx32** [comment]
Import-Module does have an `-Alias` parameter which could be utilised for this purpose perhaps? It allows you to select from among the provided aliases, but it currently doesn't allow you to select no aliases at all.

**Comment by Panzerbjrn** [comment]
I guess it would be similar functionality if the -alias parameter allowed you to not specify anything...

**Comment by iSazonov** [comment]
We already have https://github.com/PowerShell/PowerShell-RFC/pull/129 to address the issue. Please discuss there.
