### ISSUE TITLE
What is the plan for building binary modules that work on PowerShell 7 and later?

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10169]
Today we have the [PowerShell Standard 5.1](https://github.com/PowerShell/PowerShellStandard) Nuget package for binary modules that work on PowerShell 5.1 and PowerShell Core 6.x and later.

What is the plan for binary modules that only work on PowerShell 7.0 and later, due to their dependencies on new public interfaces available only in that version? As part of the 7.0 preview process, are you going to build/publish a Microsoft.PowerShell.7.ReferenceAssemblies Nuget package? Or will there be a different successor to PowerShell Standard 5.1? And when will we start seeing such a package available as part of the 7.0 preview release process?

**Comment by vexx32** [comment]
I think I noticed this and filed an issue about the lack of reference libraries for recent PS versions. Let me see... Yeah, #10011 is the one. 😄

**Comment by KirkMunro** [comment]
Thanks, missed that in my search. I'll close this since it's a duplicate.
