### ISSUE TITLE
"cd ~" not working at all none FileSystem provider,and all ps version

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#10174]
"cd ~" not working at all none FileSystem provider,and all ps version

get-psdrive can return ps provider.if provider not a FileSystem,then "cd ~" not working

win:
Alias
Cert
Env
Function
HKCU
HKLM
Variable
WSMan

linux:
Alias
Env
Function
Variable

Steps to reproduce
------------------
normal:
```
PS C:\Users\master> cd d:
PS D:\> cd ~
PS C:\Users\master>
```

not work:
```
PS C:\Users\master> cd env:
PS Env:\> cd ~
cd : 未设置此提供程序的主位置。若要设置主位置，请调用“(get-psprovider 'Environment').Home = 'path'”。
所在位置 行:1 字符: 1
+ cd ~
+ ~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-Location]，PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.SetLocationCommand

PS Env:\>
```

Expected behavior
-----------------
can return to user home folder,such as:
cd d:
cd ~

Actual behavior
---------------
```
cd : Home location for this provider is not set. To set the home location, call "(get-psprovider 'Variable').Home = 'path'".
At line:1 char:1
+ cd ~
+ ~~~~
+ CategoryInfo          : InvalidOperation: (:) [Set-Location], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.SetLocationCommand
```

Environment data
----------------
windows 10-18362 + ps v5.1 #has this bug

windows 10-18362 + ps v6.2.2   #has this bug

centos76 + ps v6.2.2  #has this bug

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by BrucePay** [comment]
@chuanjiao10 Is the error message not clear? PowerShell supports the notion of  a "home directory" for all provider types but it's (obviously) not set for all providers. (I think there was some discussion that about having `cd ~` always take you to your home directory in the file system but we didn't go that way.)  Support for `cd ~` was introduced in 6.2(?) so it won't be there in Windows PowerShell (5.1).

**Comment by chuanjiao10** [comment]
from 【env:】-------to------>【~】
you can use one command 
```cd C:\Users\master```

**use two command is unreasonable**

```
cd c:
cd ~
```


> PowerShell supports the notion of a "home directory" for all provider types

This should be a design that lacks thinking.home folder in FileSystem Should be the only ‘~’.fix it for long time i think.

> so it won't be there in Windows PowerShell (5.1).

"cd ~" work well in ps 5.1 in win10.

**Comment by BrucePay** [comment]
@chuanjiao10 
> use two command is unreasonable
> This should be a design that lacks thinking.

I agree 😎 This was an unnecessary generalization. But it sounded good at the time.

**Comment by HumanEquivalentUnit** [comment]
```
PS Env:\> (Get-PSProvider 'Environment').Home = $env:HOMEDRIVE
PS Env:\> cd ~
PS C:\>
```
> fix it for long time i think.

    "(Get-PSProvider).Where{-not $_.Home}.foreach{$_.Home = $env:HOMEDRIVE}"|Add-Content $profile

**Comment by chuanjiao10** [comment]
very well,
Looking forward to the above command, can be built in ps,and let users easy to use.
thanks @HumanEquivalentUnit

**Comment by vexx32** [comment]
Use `$HOME` instead of `$env:HOMEDRIVE` 🙂

**Comment by chuanjiao10** [comment]
@vexx32 yes，good。
who can give a pr ？

**Comment by chuanjiao10** [comment]
This is a deliberate ignorance and closure of the problem.
