### ISSUE TITLE
New-Item cmdlet fails to create folder on PowerShell 7.0.0-preview.2

### ISSUE THREAD

**Issue by amitsara** [PowerShell/PowerShell#10177]
# Steps to reproduce

1.	Create Ubuntu 18.04 VM in Azure
2.	wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.2/powershell-preview_7.0.0-preview.2-1.ubuntu.18.04_amd64.deb
3.	sudo apt install ./powershell-preview_7.0.0-preview.2-1.ubuntu.18.04_amd64.deb
4.	pwsh-preview
5.	new-item -ItemType Directory ./newfolder

In bash run
```bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
pwsh
```

Then, run
```powershell
 New-Item -ItemType Directory ./bas
```

# Expected behavior

new folder is created.

```none

```

# Actual behavior

PS /home/amitsaraf> new-item -ItemType Directory ./newfolder
new-item : The type is not a known type for the file system. Only "file","directory" or "symboliclink" can be specified.
At line:1 char:1
+ new-item -ItemType Directory ./newfolder
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-Item], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.NewItemCommand

```none

```

# Environment data

```none

```

**Comment by chuanjiao10** [comment]
I tested on centos76, and couldn't reproduce the problem.

```
[root@centos76 ~]# pwsh-preview 
PowerShell 7.0.0-preview.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> cd /tmp
PS /tmp> new-item -ItemType Directory ./newfolder3


    Directory: /tmp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2019-7-18  上午11:58                newfolder3

PS /tmp> cd ./newfolder3
PS /tmp/newfolder3> 

```

**Comment by chuanjiao10** [comment]
I guess you didn't follow the manual to install dependencies

ubuntu1804：
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo apt-get update
sudo apt-get remove -y powershell-preview #删除旧版 
sudo apt-get install -y powershell-preview
pwsh -c 'mkdir -p "$env:HOME/.config/powershell" '
pwsh -c 'Add-Content  -Value "Set-PSReadlineOption -EditMode Windows" -LiteralPath $profile '
pwsh -c 'Add-Content  -Value "`nSubsystem powershell /usr/bin/pwsh -sshs -NoLogo -NoProfile" -LiteralPath /etc/ssh/sshd_config '

**Comment by adityapatwardhan** [comment]
The problem reproduces when the LANG is set as `C.UTF-8`. To workaround:

```shell
export LANG=en_US.UTF-8
pwsh-preview
```

**Comment by chuanjiao10** [comment]
yes！
```
[root@centos76 ~]#  export LANG=C.UTF-8
[root@centos76 ~]# pwsh-preview
PowerShell 7.0.0-preview.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> cd /tmp
PS /tmp> new-item -ItemType Directory ./newfolder4
new-item : The type is not a known type for the file system. Only "file","directory" or "symboliclink" can be specified.
At line:1 char:1
+ new-item -ItemType Directory ./newfolder4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [New-Item], PSArgumentException
+ FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.NewItemCommand

```
**it is bug !!!**

export LANG=C.UTF-8 ,and pwsh 6.2.2 not this problem !!!

**Comment by SteveL-MSFT** [comment]
This seems similar to https://github.com/PowerShell/PowerShell/issues/7761 which was resolved.
