### ISSUE TITLE
pwsh hangs on start on Debian 9

### ISSUE THREAD

**Issue by aktzbn** [PowerShell/PowerShell#10173]
We are using **pwsh 6.2.0** (checked on **6.2.2** also) on **Debian 9**. And sometime troubles with start appear - command prompt never appear.

Last line of  calling ` strace pwsh` contains `futex(0xe84b64, FUTEX_WAIT_PRIVATE, 3, NULL` .

**Comment by iSazonov** [comment]
Looks like .Net Core issue. Please open new issue in CoreCLR repo, add more info (maybe trace too) and reference the issue there.

@SteveL-MSFT Who could look the issue?

**Comment by aktzbn** [comment]
> Looks like .Net Core issue. Please open new issue in CoreCLR repo, add more info (maybe trace too) and reference the issue there.
> 
> @SteveL-MSFT Who could look the issue?

@iSazonov, could you suggest what info to add and how to obtain it?

**Comment by iSazonov** [comment]
@aktzbn I hope .Net Core experts help you. Perhaps they request a dump https://superuser.com/questions/401182/how-can-i-create-a-dump-file-of-a-running-process-in-linux

**Comment by aktzbn** [comment]
Close issue because problem currently disappear and no way to gather additional info.

**Comment by aktzbn** [comment]
So, now it is clear that this was due unavailable mount. `pwsh` is touching each mount and is hanging on the first unavailable. Other shells are able to start at least

Out CI cluster (`Azure Devops`) did not work for several day until we realized what problem was in.

**Comment by Aeyk** [comment]
This issue also affects me, an unavailable mount meants pwsh will hang instead of start.

**Comment by scottzach1** [comment]
Why is PowerShell attempting to touch each mount and can this behavior be disabled?

This has been marked as closed but I don't see any solution or fix provided nor do I see a reference to an alternative issue tracking this.

**Comment by scottzach1** [comment]
Issue appears to be now tracked via https://github.com/PowerShell/PowerShell/issues/15061
