### ISSUE TITLE
move-item does not remain file permission (also copy-item)

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#10178]
Using move-item to move files from one folder to another.
The permissions attached to those files doesn't been remained.(Using icacls to get permissions)

before 
??????.lnk APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES:(I)(RX)
           xxx\xxxx.zx:(I)(F)
           NT AUTHORITY\SYSTEM:(I)(F)
           xxx\xxxx.sevic:(I)(F)
           BUILTIN\Administrators:(I)(F)
           xxxx\gxxx.usr:(I)(M)
           BUILTIN\Users:(I)(RX)

after:
??????.lnk NT AUTHORITY\SYSTEM:(F)
           BUILTIN\Administrators:(F)
           xxx\xxxx.zx:(I)(F)

In linux,
cp -p or cp -a can do a good job when copy or move items , I hope move-item or copy-item can do that

**Comment by BrucePay** [comment]
Hi @tlsalex - could you please provide the platform/version information? Also, IIRC, `Copy-Item` and `Move-Item` ultimately call the .Net APIs to do the work:
```PowerShell
[io.file]::Copy("foo.txt", "bar.txt")
[io.file]::Move("foo.txt", "bar.txt")
```
Can you try the APIs and see if the problem is still evident? This might actually be a .Net issue.

**Comment by tlsalex** [comment]
Hello @BrucePay 

`PS C:\ProgramData\chocolatey\bin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`

I will try your suggestion later

**Comment by iSazonov** [comment]
@tlsalex Do you want to add more info?

**Comment by iSazonov** [comment]
We could look this at FileSystem provider V2 time.

**Comment by iSazonov** [comment]
[Common rule (on Windows)](https://docs.microsoft.com/en-us/troubleshoot/windows-client/windows-security/permissions-on-copying-moving-files#more-information)
> By default, an object inherits permissions from its parent object, either at the time of creation or when it is copied or moved to its parent folder. The only exception to this rule occurs when you move an object to a different folder on the **same volume**. In this case, the original permissions are retained.
