### ISSUE TITLE
Reset-PowershellEnvironment

### ISSUE THREAD

**Issue by zbalkan** [PowerShell/PowerShell#10182]
# Summary of the new feature/enhancement

After a few years of PowerShell usage, the environment has been polluted. So many installed & uninstalled modules, console settings, C# included tricks have come and passed. I tried to do a factory reset, removed the config.json files, registry settings, uninstalled some modules. Still, there are some leftovers. A module to reset, backup and restore PowerShell environment in the default modules would be helpful. 

# Proposed technical implementation details (optional)

`Reset-PowershellEnvironment`: Removes all installed modules, cleans profiles, removes Registry settings. By default, it prompts for arguments.
`-Console`: When the switch is defined, only the console settings are removed.

`-Profile`: When the switch is defined, only the profiles are removed.

`-Modules`: When the switch is defined, only the modules installed afterward are uninstalled.

`Backup-PowershellEnvironment`: Backs up the environment settings to an XML or CliXml file.
`Restore-PowershellEnvironment`: Restores the environment  settings from an XML or CliXml file

**Comment by jdhitsolutions** [comment]
This sounds like a project for the community.  Or something that module authors should include. If you install a module that creates a set of registry keys, Microsoft would have no way knowing that or deleting them. The module author should include an uninstall command or provide documentation on what else you might need to do.  Who gets to define at the "PowerShell Environment" consists of? Your environment may be different than mine. Yes, I know there are parameter suggestions, but again, I think these are things the community could provide.

**Comment by iSazonov** [comment]
I agree that this is not something that can be done reliably and predictably. There is a high risk of destroying the system altogether. This should be rejected.

**Comment by zbalkan** [comment]
Closing as not a valuable request.
