### ISSUE TITLE
Feature Request: Function-Level "Using" statements

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#10185]
# Summary of the new feature/enhancement

The "using" statements (using namespace, using assembly, using module, etc.) should be able to be declared as the first line in a function declaration. It would be understood that those imports would still go run-space wide and not end when a function ends, but it would simplify being able to encapsulate functions and functions in modules without having a giant list of using namespaces at the top of a file, especially when "compiling" multiple separate script cmdlets to a single .psm1 file for performance reasons.

Since #requires is allowed at a function level, precedent already exists for this functionality.

**Comment by vexx32** [comment]
Hmm, honestly, if there _is_ a way I'd much prefer any function-scope `using` statements not to affect the wider script or higher scopes. 

Either way though, this would absolutely be a nice thing to have!

**Comment by JustinGrote** [comment]
namespace could maybe be scoped to function, but assembly can't for sure

**Comment by vexx32** [comment]
True... .NET Core 3 is bringing proper assembly unloading. Certainly it can't be completely scoped within the function for probably a majority of use cases, but perhaps we could do something flag the assembly for unload as soon as references to those types are no longer needed in the session or something, after the function that declared the `using assembly` exits.
