### ISSUE TITLE
Post GA of v7 - Update 5.1 pointer to try v6

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#10190]
As per below 

![image](https://user-images.githubusercontent.com/6355225/61582976-d9f17680-ab29-11e9-9459-4511262c1751.png)

should either be replaced to a try v7 or should similarly point to a generic messages similar to  change made https://github.com/PowerShell/PowerShell/pull/9775/

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we agree that this needs to be updated in Windows PowerShell by the time PS7 comes out.  Thanks!
