### ISSUE TITLE
Set-Clipboard and Get-Clipboard do not work in PowerShell 7 Preview 2

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#10196]
# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none

```

**Comment by mklement0** [comment]
See [gallery module `ClipboardText`](https://www.powershellgallery.com/packages/ClipboardText/0.1.8) for a cross-edition (and cross-platform), compatible-down-to-WinPS-v2 implementation of text-only clipboard functionality.

**Comment by iSazonov** [comment]
Also we have #10340
