### ISSUE TITLE
Empty hashtable evaluates $true in boolean context

### ISSUE THREAD

**Issue by MarioSchwalbe** [PowerShell/PowerShell#10201]
Out of curiosity, is there any compelling reason why PowerShell considers empty hashes to be true unlike empty containers (strings, arrays) which are usually false.

# Steps to reproduce
```powershell
PS> [bool]''
False
PS> [bool]@()
False
PS> [bool]@{}
True
```

# Expected behavior

In programming languages supporting implicit conversion to bool, empty containers usually evaluate false:

```powershell
PS> [bool]@{}
False
```

# Environment data

PowerShell 5/6/7 on any supported platform.

**Comment by msftrncs** [comment]
Probably for the same reason as these either work or don't:

```PowerShell
@() | get-member
@{} | get-member
```
Even an empty hashtable isn't empty.  Unlike the array object, it can be added to after it was created (using Add Method), so even though the 'table' is empty, the object itself is not empty.

Now, I am not saying that this is the right behavior, but I suspect it is.

**Comment by vexx32** [comment]
Bit of a different issue, really. The issue there @msftrncs is that by design the pipeline enumerates arrays. That's its entire job. If you pass it an empty array, there's nothing inside for it to enumerate, so it passes nothing along. 

The issue at hand here is the different treatment of <empty array> vs <empty hashtable>, and in a more general sense for those accustomed to C#'s interfaces, probably deals with the difference between an empty `IList` and an empty `ICollection`.

For example, a generic `List<T>` object, which also implements `IList`, and is empty (as it has been newly created):

```ps
PS> [bool][System.Collections.Generic.List[string]]::new()
```

I can definitely see the argument for treating all collection types equally. If I recall correctly, we should be able to modify the logic such that it not only checks `IList` items for their length or count, but it also checks `ICollection` items (which is, from memory, implemented by _both_ dictionary/hashtable and list/array types, so would cover a **vast** majority of the bases) for their `Count` to see if it should return true or false.

What's being displayed here is the "fallback" behaviour in the boolean conversion paths; if an object doesn't have special handling and is a reference-type object, the conversion currently _always_ returns true. `IList` collections are currently specifically targeted as they are one of the most commonly used, if I recall correctly.

/cc @SteveL-MSFT does this seem like a worthwhile change, or at least one that would have code behave in common-sense ways?

It would, of course, be a breaking change in behaviour, but I feel it makes sense, and it seems unlikely to me that people would rely on `[bool]@{}` evaluating to true in any real-world scenarios.

**Comment by BrucePay** [comment]
@vexx32 Changing the behaviour of hashtables in the pipeline would be a _huge_ breaking change. PowerShell has treated hashtables as "structs" from the very beginning. 

@MarioSchwalbe 
As to why an empty hashtable is not treated as false,  I'm sorry - I just don't remember - it was too long ago. But - I can theorize that, because we treated hashtables as structs, we probably don't consider hashtables as false. (@JamesWTruher  or @khansen00  might remember more.)

**Comment by SteveL-MSFT** [comment]
I agree that this is too big a breaking change.

**Comment by vexx32** [comment]
If hashtables were being treated as structs, wouldn't the behaviour be working as @MarioSchwalbe (and myself) would consider logical? Empty hashtable -> false?

I doubt this was a deliberate decision -- all reference types evaluate to true when cast to boolean unless some type conversion has been found or special-cased in the casting logic.

**Comment by MarioSchwalbe** [comment]
To clarify the question: I wrote a script using implicit conversion like that:
```powershell
if ($hash) {
    # use it
}
```
And it executes the code even though I expected it not to.

@vexx32:
I can't really see the special case for enumeration/pipelining. An empty hash is just an object with no elements just like an empty array, so enumeration wouldn't enumerate anything here as well.

> @msftrncs: Even an empty hashtable isn't empty. Unlike the array object, it can be added to after it was created (using Add Method), so even though the 'table' is empty, the object itself is not empty.

I read that multiple times, but have to confess, I don't really understand that statement. Is this the internal Powershell implementation? Normally, an empty collection *is* empty (stores nothing). But it's a non-null reference (*has* members). Are you mixing these two concepts?

Indeed, Powershell seems to be very interesting here:
```powershell
# Empty objects are objects (non-null references):
PS> $l = @()
PS> $l.ToString()
System.Object[]
PS> $l.Count
0

PS> $h = @{}
PS> $h.ToString()
System.Collections.Hashtable
PS> $h.Count
0

# Display members:
PS> $l | Get-Member
Get-Member : You must specify an object for the Get-Member cmdlet.
At line:1 char:6
+ $l | Get-Member
+      ~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
+ FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

PS> $h | Get-Member
   TypeName: System.Collections.Hashtable
Name              MemberType            Definition
----              ----------            ----------
Add               Method                void Add(System.Object key, System.Object value), void IDictionary.Add(System.Object key, System.O…
Clear             Method                void Clear(), void IDictionary.Clear()
Clone             Method                System.Object Clone(), System.Object ICloneable.Clone()
Contains          Method                bool Contains(System.Object key), bool IDictionary.Contains(System.Object key)
ContainsKey       Method                bool ContainsKey(System.Object key)
ContainsValue     Method                bool ContainsValue(System.Object value)
CopyTo            Method                void CopyTo(array array, int arrayIndex), void ICollection.CopyTo(array array, int index)
Equals            Method                bool Equals(System.Object obj)
GetEnumerator     Method                System.Collections.IDictionaryEnumerator GetEnumerator(), System.Collections.IDictionaryEnumerator…
GetHashCode       Method                int GetHashCode()
GetObjectData     Method                void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serializati…
GetType           Method                type GetType()
OnDeserialization Method                void OnDeserialization(System.Object sender), void IDeserializationCallback.OnDeserialization(Syst…
Remove            Method                void Remove(System.Object key), void IDictionary.Remove(System.Object key)
ToString          Method                string ToString()
Item              ParameterizedProperty System.Object Item(System.Object key) {get;set;}
Count             Property              int Count {get;}
IsFixedSize       Property              bool IsFixedSize {get;}
IsReadOnly        Property              bool IsReadOnly {get;}
IsSynchronized    Property              bool IsSynchronized {get;}
Keys              Property              System.Collections.ICollection Keys {get;}
SyncRoot          Property              System.Object SyncRoot {get;}
Values            Property              System.Collections.ICollection Values {get;}

PS> $l = @(1)
PS> $l | Get-Member

   TypeName: System.Int32
Name        MemberType Definition
----        ---------- ----------
CompareTo   Method     int CompareTo(System.Object value), int CompareTo(int value), int IComparable.CompareTo(System.Object obj), int ICo…
Equals      Method     bool Equals(System.Object obj), bool Equals(int obj), bool IEquatable[int].Equals(int other)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
GetTypeCode Method     System.TypeCode GetTypeCode(), System.TypeCode IConvertible.GetTypeCode()
ToBoolean   Method     bool IConvertible.ToBoolean(System.IFormatProvider provider)
ToByte      Method     byte IConvertible.ToByte(System.IFormatProvider provider)
ToChar      Method     char IConvertible.ToChar(System.IFormatProvider provider)
ToDateTime  Method     datetime IConvertible.ToDateTime(System.IFormatProvider provider)
ToDecimal   Method     decimal IConvertible.ToDecimal(System.IFormatProvider provider)
ToDouble    Method     double IConvertible.ToDouble(System.IFormatProvider provider)
ToInt16     Method     short IConvertible.ToInt16(System.IFormatProvider provider)
ToInt32     Method     int IConvertible.ToInt32(System.IFormatProvider provider)
ToInt64     Method     long IConvertible.ToInt64(System.IFormatProvider provider)
ToSByte     Method     sbyte IConvertible.ToSByte(System.IFormatProvider provider)
ToSingle    Method     float IConvertible.ToSingle(System.IFormatProvider provider)
ToString    Method     string ToString(), string ToString(string format), string ToString(System.IFormatProvider provider), string ToStrin…
ToType      Method     System.Object IConvertible.ToType(type conversionType, System.IFormatProvider provider)
ToUInt16    Method     ushort IConvertible.ToUInt16(System.IFormatProvider provider)
ToUInt32    Method     uint IConvertible.ToUInt32(System.IFormatProvider provider)
ToUInt64    Method     ulong IConvertible.ToUInt64(System.IFormatProvider provider)
TryFormat   Method     bool TryFormat(System.Span[char] destination, [ref] int charsWritten, System.ReadOnlySpan[char] format, System.IFor…
```
What is going on here? I cannot enumerate the members of an empty array? But at the same time access properties/call methods? According to the [C# documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/arrays-as-objects), arrays are indeed full objects (unlike C) and can have members.

I come from C++/Python and in those programming languages, empty collections (and strings) are:
1. Non-null references to objects storing the state `empty` and can be treated like regular objects.
2. Can be iterated with no exceptions, but don't enumerate anything, i.e., it is equivalent to a loop whose initial condition was false.
3. Boolean conversion (Python only) is based upon the number of elements, not its reference.
4. `None`/`nullptr` references (pointers in C++) are false.

To my understanding, both of them are (partially) wrongly implemented.

**Comment by vexx32** [comment]
Yeah, this pipeline enumerates the array. If it didn't you'd not be able to write `1, 2, 3 | ForEarh-Object {$_ + 3}` and get the results you currently do. It doesn't currently enumerate dictionary types at all, so Get-Member doesn't "see" flat lists and arrays when piping. You need to use `Geh-Member -InputObject @()` to work around that.

**Comment by MarioSchwalbe** [comment]
Alright:
```powershell
[1] PS> $s = 'text'
[1] PS> $n = 0; $t | foreach { $n++ }; $n
1
[2] PS> $l = @(1, 2, 3)
[2] PS> $n = 0; $l | foreach { $n++ }; $n
3
[3] PS> $h = @{X=1; Y=2; Z=3}
[3] PS> $n = 0; $h | foreach { $n++ }; $n
1
[4] PS> $n = 0; foreach ($e in $h) { $n++ }; $n
1
[5] PS> $n = 0; foreach ($e in $h.GetEnumerator()) { $n++ }; $n
3
```
Got it:
- A pipe plus `foreach` implicitly converts scalar types (non-list-like) to a list with 1 element and iterates it.
- Lists remain lists.
- Other collections such as hashes are considered scalar here.

Maybe case 3 should enumerate the hashes' keys instead. And also case 4. Would be consistent with the majority of programming languages. Finally, `@() | Get-Member` considers the elements' types (not the array) and errors out if there are no elements. Could be the same with hashes. This is still more confusing than necessary.

... And it doesn't explain the semantics of boolean conversions.

**Comment by SeeminglyScience** [comment]
> If hashtables were being treated as structs, wouldn't the behaviour be working as @MarioSchwalbe (and myself) would consider logical? Empty hashtable -> false?

Current behavior makes sense to me with that mindset:

```powershell
Add-Type -TypeDefinition 'public struct Test {}' -IgnoreWarnings
[bool][test]::new()
# returns True
```

**Comment by vexx32** [comment]
Huh, interesting. Didn't know PS treated structs that way.

🤔 

I dunno there tbh. A hashtable in my mind is a collection. A struct is a single instance/glob of data. I'd venture to say I can't really follow where that mindset is coming from. Structs can't change their shape overall, hashtables.... kind of can? At least in as much of the same way as any list-type collection can, anyway.

**Comment by SeeminglyScience** [comment]
> Huh, interesting. Didn't know PS treated structs that way.
> 
> 🤔
> 
> I dunno there tbh. A hashtable in my mind is a collection. A struct is a single instance/glob of data. I'd venture to say I can't really follow where that mindset is coming from. Structs can't change their shape overall, hashtables.... kind of can? At least in as much of the same way as any list-type collection can, anyway.

Think of it less like a struct and more like a `PSObject`, I think that's the general idea.  `Hashtable`s in PS are treated less like a dictionary/map and more like an anonymous object.

To be clear I'm not saying that I agree with treating them that way, especially when we already have `PSObject`.  I would guess that that decision was made very early on, perhaps before `PSObject` was the obvious choice for that type of thing.

**Comment by vexx32** [comment]
Yeah I guess I can see it in that way, perhaps... But as you say, not sure it still makes sense to continue down that road. 🙂

**Comment by SeeminglyScience** [comment]
> Yeah I guess I can see it in that way, perhaps... But as you say, not sure it still makes sense to continue down that road. 🙂

Imo the benefit seems very small compared to the pretty overwhelming cost.  It wouldn't make sense to *just* change truthy behavior, you'd also have to make it enumerate across the pipeline for consistency.  That'd be a hefty breaking change.

**Comment by HumanEquivalentUnit** [comment]
> Maybe case 3 should enumerate the hashes' keys instead.  Would be consistent with the majority of programming languages. 

The majority of programming languages don't have pipelines in the same way PowerShell does. It's really arrays which are the special case, they are easy to take apart *and* easy to put back together, and useful to break apart to help stream things down the pipeline: 

    $x = 1,2,3    # $x is an array
    $y = $x | foreach-object { $_ }    # $y is an array

Pretty much any other collection is easy to get the elements out, but harder or impossible to put back together (trees, etc). If hashtables unrolled into their keys you would risk weird behaviour trying to return a hashtable from a function and keep it in one piece:

    function test {        @{ key1 = 10;  key2 = 20 }       }
    
    test | Another-Cmdlet
    test | foreach-object { $_ } | Another-Cmdlet

I suggest that you want the input to `Another-Cmdlet` to be a single hashtable, and the same in both situations. Receiving an unrolled array of hashtable keys with the values lost would be surprising, receiving an array of DictionaryEntries (keys and values) would mean you'd have to rebuild it into a hashtable again, and receiving different things in each instance depending on whether there was a loop involved somewhere previously would be surprising, annoying and hard work.

PowerShell also does not unroll strings into characters, in the same way Python does.

> Boolean conversion (Python only) is based upon the number of elements, not its reference.

It's first based on the [object.__bool__(self)](https://docs.python.org/3/reference/datamodel.html#object.__bool__) method; you can make a class which is iterable, is a sequence, has no length, but is still Truthy. What you say may hold for the builtin collections, but you can't be sure of it for every class which behaves like a collection.

Back to boolean conversion in PS; I was surprised the first time I found this

```
PS C:\> [bool][int]0
False
PS C:\> [bool][decimal]0
False
PS C:\> [bool][bigint]0
True
```
