### ISSUE TITLE
Feature Request: Show Admin Title for Open here As Admin

### ISSUE THREAD

**Issue by wrolisonaflac** [PowerShell/PowerShell#10211]
Feature Request: Show Admin Title for Open here As Admin

If I run PowerShell 6 or PowerShell 7 as admin directly, "Administrator" is added to the window title as expected.

However, if I right click any folder and use the PowerShell context menu and choose "Open here as Administrator" , the title window does NOT have Administrator. Notice it is there for a split second while the window refreshes.

PowerShell 6 and PowerShell 7 effected.

**Comment by matthew-sutterlin** [comment]
yea this is still happening for me on 7.0.3, unable to open admin powershell window through context menu -> Open here as administrator

**Comment by war59312** [comment]
Seems like such a simple thing to do?

**Comment by war59312** [comment]
Guess not so simple. :(
