### ISSUE TITLE
Comment based help should be loose validating

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1021]
```powershell
function Get-CronJob {
<#
.SYNOPSIS
  Returns the current cron jobs from the cron table
.DESCRIPTION
  Returns the current cron jobs from the cron table
.EXAMPLE
  Get-CronJob -UserName Steve
.RETURNVALUE
  CronJob objects
.PARAMETER UserName
  Optional parameter to specify a specific user's cron table
#>

[CmdletBinding()]
[OutputType([PSObject])]
param (
    [Alias("u")][Parameter(Mandatory=$false)][String] $UserName
)
process {
    $crontab = Get-CronTab -user $UserName
    ForEach ($line in $crontab) {
        if ($line.Trim().Length -gt 0)
        {
            ConvertTo-CronJob -crontab $line
        }
    }
}

}
```

Get-CronJob -?
## Expected behavior

help text
## Actual behavior

syntax only
## Environment data

v0.4.0

**Comment by chunqingchen** [comment]
@SteveL-MSFT 
you will have to use 
get-help Get-CronJob -full 
to show the comment based help.

Are you complaining we need to support this in a more compelling syntax?

**Comment by SteveL-MSFT** [comment]
Requiring `-full` means we have a broken experience between MAML help and comment based help.  cc @joeyaiello

**Comment by lzybkr** [comment]
This is sort of by design. If you change `.RETURNVALUE` to `.OUTPUTS`, it will work correctly.

The design was to stop parsing comments as comment help when we see an unknown directive. This was a design choice meant to avoid breaking any existing scripts.

The intent was to add a script analyzer rule to warning about unknown help comment directives, but I'm not sure if such a rule exists. I do see VS Code colors the unknown directive like ordinary text, so there is a hint at least.

**Comment by joeyaiello** [comment]
Yeah, this looks by-design to me. I'll leave to @SteveL-MSFT to close unless he disagrees.

**Comment by SteveL-MSFT** [comment]
In general, I think we should be loose validating so that future supported extensions don't break existing scripts.  Strict validation should be handled by PSScriptAnalyzer.  In this case, I would agree this isn't needed for 6.0.0 as it's working as previously designed.

**Comment by kilasuit** [comment]
This would be a nice to have but I can't see how much value this would really add as the CBH syntax is already quite presctriptive and I'm not sure that this really will add much more value for the effort to enable it

**Comment by doctordns** [comment]
I would like some better error reporting when the CBH is broken. I'd like to see get-help to actually report the errors vs silently failing.
