### ISSUE TITLE
-TimeoutSeconds of Test-Connection not work when value gt 4,no err

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#10220]
https://docs.microsoft.com/zh-cn/powershell/module/Microsoft.PowerShell.Management/Test-Connection?view=powershell-6

input 1----4  to TimeoutSeconds Parameter,then  work.
input 5----more  to TimeoutSeconds Parameter,does not work.（use 4，No error）

Steps to reproduce
------------------
Test-Connection -TargetName $ip -TCPPort 22 -TimeoutSeconds 20  

Expected behavior
-----------------
Until 20 seconds

Actual behavior
---------------
4---5 seconds ,and return false.

Environment data
----------------
centos76 + ps v6.1.5 + console #has this bug

centos76 + ps v6.2.2 + console #has this bug

centos76 + ps v7.0 preview2 + console #has this bug

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by iSazonov** [comment]
I do not understand what the problem is. If the cmdlet sleeps for more than 20 seconds, it will be a problem.

**Comment by chuanjiao10** [comment]
the point is:
input 1----4  to TimeoutSeconds Parameter,then  work.
input 5----more  to TimeoutSeconds Parameter,does not work.

The current practice is very unprofessional

**If this is a by design, the parameter values should be limited in a friendly way.**
eg：
ValidateRange

**Comment by chuanjiao10** [comment]
@iSazonov  remove Resolution-Answered  label.
put the label,and let bot close this issue is Is not responsible for the practice.

**Comment by iSazonov** [comment]
I re-check that the parameter works as expected on Windows and on WSL.
If there is an issue on centos76 it is not PowerShell Core issue, maybe it is .Net Core issue.

**Comment by chuanjiao10** [comment]
1 I re-check that the parameter works as expected on Windows,by version 6.2.2. it can wait Until 20 seconds.

2 I re-check that the parameter works  4 seconds on linux + docker ,by version 6.2.2.it **can not** wait Until 20 seconds.
```
docker run -it   mcr.microsoft.com/powershell:6.2.2-alpine-3.8 pwsh -c 'Test-Connection -TargetName 192.168.66.66 -TCPPort 22 -TimeoutSeconds 20'                                                                                                                       

```

**Comment by vexx32** [comment]
@chuanjiao10 can you do a simple test to see if the issue is with the type that is used in .NET Core?

```ps
using namespace System.Net.NetworkInformation

$Destination = 'https://github.com'
[byte[]]$Buffer = 1..32
$Options = [PingOptions]::new()

foreach ($timeout in 1..20) {
    $ping = [Ping]::new()
    $ping.Send($Destination, $timeout, $Buffer, $Options)
}
```

I'm curious as to what the errors would be... and why it's having this issue. If it is a .NET Core issue, we should be able to get them to check it out before .NET Core 3 GA release. 🙂

**Comment by chuanjiao10** [comment]
@vexx32  Is your discussion related to the topic? 

```
[root@centos76 ~]# pwsh-preview 
PowerShell 7.0.0-preview.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> /powershell/20190725.ps1
Testing ping to 'https://github.com' with timeout value of 1...
Exception calling "Send" with "4" argument(s): "An exception occurred during a Ping request."
At /powershell/20190725.ps1:11 char:2
+     $ping.Send($Destination, $timeout, $Buffer, $Options)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : PingException
 
Testing ping to 'https://github.com' with timeout value of 2...
Exception calling "Send" with "4" argument(s): "An exception occurred during a Ping request."
At /powershell/20190725.ps1:11 char:2
+     $ping.Send($Destination, $timeout, $Buffer, $Options)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : PingException

```

**Comment by chuanjiao10** [comment]
open this issue @msftbot

**Comment by iSazonov** [comment]
There already is a tracking issue https://github.com/dotnet/corefx/issues/28934. Please discuss there.

**Comment by chuanjiao10** [comment]
@iSazonov  
1In https://github.com/dotnet/corefx/issues/28934 Below short list:，
Which item is related to    “-TimeoutSeconds gt 4 not work”  ? 

2 the “related”， Is this your guess, or has it been investigated?
Anyone willing to help review the Test-Connection code first?

2 If it is related,this issue marked "wait for .net core" as well.
The bug is still, willing to be unidentified, reopen this issue!

**Comment by iSazonov** [comment]
@chuanjiao10 Underlying .Net  Core code is broken for Unix-s. We can not fix this in PowerShell Core repo. Please report such bugs to CoreClr/CoreFX repos and ask them to fix.

**Comment by chuanjiao10** [comment]
This is a deliberate ignorance and closure of the problem.

**Comment by vexx32** [comment]
The issue is not in the scope of our code. We can only do so much with hiding problems exposed by .net Core. In this case, the only way we could bypass the problem would be to implement our own version of the Ping APIs from the native P/invoke calls.

The PowerShell team likely do not have the manpower to build nor maintain such a complex solution, when the bug is being tracked in the provider's repo and will be fixed eventually.

**Comment by chuanjiao10** [comment]
This is a deliberate ignorance,The problem is still, Although the problem is relatively small.
Suggested "wait for .net core" lable.
