### ISSUE TITLE
Feature Request: include language keywords in command completion results

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10221]
# Summary of the new feature/enhancement

Include language keywords, such as 'continue', 'switch', 'foreach', etc... in with the command completions offered by intellisense/tab completion.

# Proposed technical implementation details (optional)

I don't yet know if its possible to restrict the keywords when the insertion point is not the first command in a pipeline, but there is already 1 case in the completion logic that has decided that `foreach` should not have an ampersand `&` (invoke) operator inserted before it (its actually in the completions because its an alias for `ForEach-Object`) because its more likely what the user wanted, but none of the other keywords get this treatment.   Including the keywords would actually eliminate this special case.

I am sure somewhere there is a complete list of keywords in the code, I'm just not sure if there is anything to use as a tooltip text readily available.

I may experiment on this while working the other bugs out of the completion code.

**Comment by vexx32** [comment]
Might want to clarify your issue title; it seems the request is for `language keywords` to show in tab-completion results where appropriate, rather than for commands to show (which they already do).

**Comment by msftrncs** [comment]
Thanks, @vexx32, sometimes I speak better computer than English.  :)

**Comment by HumanEquivalentUnit** [comment]
> I am sure somewhere there is a complete list of keywords in the code

Yes, [here in the tokenizer](https://github.com/PowerShell/PowerShell/blob/026a8f1f41c46f2e79f5cfcb27d49d4cec5cb034/src/System.Management.Automation/engine/parser/tokenizer.cs#L618). Copying it in:

```
private static readonly string[] s_keywordText = new string[] {
    /*1*/    "elseif",                  "if",               "else",             "switch",                     /*1*/
    /*2*/    "foreach",                 "from",             "in",               "for",                        /*2*/
    /*3*/    "while",                   "until",            "do",               "try",                        /*3*/
    /*4*/    "catch",                   "finally",          "trap",             "data",                       /*4*/
    /*5*/    "return",                  "continue",         "break",            "exit",                       /*5*/
    /*6*/    "throw",                   "begin",            "process",          "end",                        /*6*/
    /*7*/    "dynamicparam",            "function",         "filter",           "param",                      /*7*/
    /*8*/    "class",                   "define",           "var",              "using",                      /*8*/
    /*9*/    "workflow",                "parallel",         "sequence",         "inlinescript",               /*9*/
    /*A*/    "configuration",           "public",           "private",          "static",                     /*A*/
    /*B*/    "interface",               "enum",             "namespace",        "module",                     /*B*/
    /*C*/    "type",                    "assembly",         "command",          "hidden",                     /*C*/
    /*D*/    "base",                                                                                          /*D*/
};
```

> I'm just not sure if there is anything to use as a tooltip text readily available.

Would that be beneficial? If you autocomplete `notepad.exe` you don't get very useful tooltip information.

**Comment by msftrncs** [comment]
> Would that be beneficial? If you autocomplete `notepad.exe` you don't get very useful tooltip information.

That's because `notepad.exe` isn't part of PowerShell.  You do on the other hand still get the complete path to `notepad.exe` in the tooltip.  I think something in the tooltip needs to let the user know that this is the keyword, vs the function.  Some functions do not show anything in their tooltip, so if both functions and keywords both showed nothing in the tooltip it might be slightly confusing, however, at least a command with the same name as a keyword requires the `&` and that will show when its selected.

Interestingly I see the operators are already included in completions, and they have tooltips.

Any data kept on whether these keywords are available, or better, available in a given context?  I would think that reserved keywords should probably not have completions offered, so that a user doesn't have as much clutter to sort through, and keywords that are not available in the current context should not be offered.   

I suppose that last part is what has kept keyword completion from being implemented so far.

**Comment by SeeminglyScience** [comment]
Aside from complexity and demand not that I know of. It's not exactly as simple as it first seems since you have to add logic for only returning a keyword completion result when it's actually applicable and that branch of code doesn't exist yet. That's pretty minor, but still
