### ISSUE TITLE
The -InformationAction common parameter alias is inconsistent with other stream common parameter aliases

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10237]
All common parameters that have to do with streams follow a two-letter alias format (first letter of the stream name followed by the first letter of "Action" or "Variable"). In fact, `-InformationVariable` has an alias of `iv`. So why does `-InformationAction` break the mold with an alias of `infa` instead of simply using `ia` as an alias? I couldn't find any competing `ia` alias in common parameters.

This issue should be addressed by adding `ia` as a secondary alias for the `-InformationAction` common parameter.

**Comment by iSazonov** [comment]
There is a bug in completion code for common parameters and maybe the alias name was a workaround.

**Comment by KirkMunro** [comment]
Can you link to that bug? And is the existence of a bug a logical reason for an inconsistent alias?

**Comment by iSazonov** [comment]
I think it is Tab completion confusion with common parameters #1265

**Comment by iSazonov** [comment]
@KirkMunro It seems it is unbelievable that we will change these aliases. Can we close the issue?

**Comment by KirkMunro** [comment]
@iSazonov I want us to at least consider adding `ia` as an alias for `InformationAction`. For that reason, please leave this open a bit longer. I monitor issues I log regularly, so will ensure this doesn't just stay open forever.

**Comment by iSazonov** [comment]
@KirkMunro I suggest reword the issue as "proposal" (or open new issue) - in the case I hope we will get a progress faster. (I don't see reasons why we can not add the new aliases)

**Comment by KirkMunro** [comment]
It turns out that there is an alias conflict, which is why a different alias was chosen.

**Comment by iSazonov** [comment]
Reference to PowerShell Committee conclution https://github.com/PowerShell/PowerShell/pull/10703#issuecomment-540231767
