### ISSUE TITLE
The SSL connection could not be established in pwsh-6.x

### ISSUE THREAD

**Issue by shaarawy18** [PowerShell/PowerShell#10232]
I am trying to develop a PowerShell Module. When I try to set a connection with my local-deploy server using self-signed certificate, pwsh will throw a exception:
 ```
The SSL connection could not be established, see inner exception. 
The remote certificate is invalid according to the validation procedure
```

But this module can be used in windows powershell 5.x as  expected, it can correctly set ssl connection with my certificate to send and receive request.

I use WebHttpHandler to pack a certificate, then new a HttpClient using this handler. 
Simple source code:

 ```
 public async Task<Response> SendRequest( Uri baseAddress, Request request)
 {
...
_handler = new WebRequestHandler();
_handler.ClientCertificates.Add(
                new X509Certificate2(
                    Path.Combine(
                        Path.GetDirectoryName(this.GetType().Assembly.Location),
                        "TestClientCert.pfx"),
                    "password123456"));
             
var client = new HttpClient(_handler) { BaseAddress = baseAddress, Timeout = TimeSpan.FromMinutes(5) };
...
var resp = await client.SendAsync(msg);
return new Response(resp.content...);

}
```
I use `powershell 6.2.1 in windows 10`
I am so confused the same code run different result in different version PowerShell env. Do you have some idea about that, or some solution to that problem ? 

Thanks!

**Comment by djsowa** [comment]
@shaarawy18 Self signet cets are not trusted by default.
You have to write custom ServerCertificateValidationCallback to check certificate details manually.

Also in Your example I can't find any PowerShell code, it's all C#.
