### ISSUE TITLE
Tab completion attempt at `@` returns no result, `@?` crashes PSReadLine, or provides invalid result

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10243]
# Steps to reproduce

Attempt tab completion/intellisense of splats:

```PowerShell
@<CTRL SPACE>
@?<CTRL SPACE> # CRASH PSReadLine
@?<TAB> # results in `@{$}` which is unusable as it tries to make a hashtable
```
`tabexpansion2` also provides no results for ( `'@' 1`).

# Environment data

Believed to occur in all versions, tested in 7.0.0-preview2 and Windows PowerShell on Win 10 Insiders.

# Insights

I believe the example of `@?` crashing PSReadLine is related to the expansion to `@{$}`, and while it probably shows a bug in PSReadLine, PR #10226 would fix the completion (though its likely to be a new problem with the new @@ splats being worked on.

I am not sure yet why `@` alone cannot start a completion, I'm trying to consider what the completion code can do about offering completions that wont work.  I don't think there is currently a syntax that works for splatting variables with complex names, and I didn't see it in the RFC for Enhanced Splatting.

**Comment by msftrncs** [comment]
Weirdly, while I might thnk the PSReadLine crash is related to the result completion `@{$}`, and I can get the list to open on the test build of PR #10226, it still crashes out on certain variables selected for completion, some have braces, and some don't, so I haven't figured out what the deal is yet.

**Comment by daxian-dbw** [comment]
This was fixed by https://github.com/PowerShell/PSReadLine/pull/984
