### ISSUE TITLE
Powershell does not traverse symbolic links on Powershell Core 6

### ISSUE THREAD

**Issue by whitequill** [PowerShell/PowerShell#10242]
# Steps to reproduce

1) download 
[boot_sect.zip](https://github.com/PowerShell/PowerShell/files/3439414/boot_sect.zip)
2) Place the current line into a ps1 file 
```powershell
D:\Applications\qemu\qemu-system-i386.exe -drive format=raw,file='\Documents\Virtual Machines\OS\bin\boot_sect' -m 256
```
3) once the qemu command is in a ps1 file take the **boot_sec.bin** file and then run the following command: 
```powershell
 New-Item -Type SymbolicLink -Name boot_sect -Path <#current location of boot_sect.bin #> \. -Value boot_sect.bin
```
This will create a symbolic link to the **boot_sect.bin** file called **boot_sect.symlink**.
4) There is a good trick to running powershell files. 😄 
make a shortcut to the ps1 file and set the target to: `%pathToPowershell6% -NoExit "Documents\WindowsPowerShell\OS.ps1"`
4.1) Set the **Start in** field to \Documents\WindowsPowerShell
This will quickly run the Powershell script

# Expected behavior
qemu boots and shows "helllo"

>notes: okay this is a little longer then it needs to be and I'm sure you can make a symlink to most executables and it won't run with the following steps in Powershell version 6.1.3

# Actual behavior
Powershell gives the following output.
`D:\Applications\qemu\qemu-system-i386.exe: -drive format=raw,file=D:\Users\brazg\Documents\Virtual Machines\boot_sect: Could not open 'D:\Users\brazg\Documents\Virtual Machines\boot_sect': The system cannot find the file specified.
`
**Powershell does not traverse symbolic links**

If you change the script to be:
```powershell
D:\Applications\qemu\qemu-system-i386.exe -drive format=raw,file='Documents\Virtual Machines\OS\bin\boot_sect.bin' -m 256
```
The qemu will boot

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@whitequill I'm fairly sure this was changed either before or shortly after the release of 6.2 - can you check with a more recent version? Probably best to check it against the recent v7 preview release to be sure. :)

**Comment by whitequill** [comment]
I just checked Powershell 7.0.0-Preview 2 still throws the same error when given a symbolic link

**Comment by whitequill** [comment]
can someone please set this to be Resolution-Answered?
