### ISSUE TITLE
GitHub bot addition

### ISSUE THREAD

**Issue by RDIL** [PowerShell/PowerShell#10241]
Add https://probot.github.io/apps/unfurl-links/ - may be helpful for getting descriptions of links

**Comment by RDIL** [comment]
cc @TravisEz13

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Added, let's try it out on this repo.  Thanks @RDIL

**Comment by RDIL** [comment]
Okay lets try it -
https://example.com

**Comment by RDIL** [comment]
Cool it works!
