### ISSUE TITLE
new-localuser vs net user /add

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#10247]
1. running win10 as client in hyper-v
2. the first account created during the installation of win10 is alex
3. create a new user name with bellow steps(remotely via PS ,not in interactive console)
```
$passwd = Read-Host -AsSecureString
New-LocalUser -Name display -AccountNeverExpires -PasswordNeverExpires -Password $passwd
Get-LocalUser
```
4. I can see the newly created account: display.and it is enabled.
5. logoff alex account in interactive console ,then try to login with display account
6. on the logon screen. There is no way to type the new user name (display) or choose
7. try to add display account to administrators group.
8. restart computer to login again , but still no way to type or choose display account.

########################
9. try to add a new user with net user add with bellow step
`net user selfservice xxxxxx.xxxx /add`
10. try to login again in interactive console , i can see the new account (selfservice) was there , I can click on it ,then type pass word .....

This is my second time met this problem.
Why I can not use the new account created by new-localuser ? 
bug or I make some mistake ?

**Comment by iSazonov** [comment]
The cmdlet is not in the repo. Please discuss on forums.

**Comment by SSJ9899TDylan** [comment]
Ok



Sent from myMail for iOS


Tuesday, 30 July 2019, 3:58 pm +1000 from notifications@github.com  <notifications@github.com>:
