### ISSUE TITLE
Debian 10 Support 

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10255]
# Details of the Distribution

- Name of the Distribution: Debian 
- Version of the Distribution: 10
- [x] The version of the Distribution is supported for at least one year.
- [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.
- [x] The version of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

## Progress - For PowerShell Team **ONLY**

- [x] Docker image created - https://github.com/PowerShell/PowerShell-Docker/pull/250
- [x] Docker image published
- [x] Distribution tested
- [x] Lifecycle updated
- [x] Documentation Updated

**Comment by sirredbeard** [comment]
This would be very useful.

The stretch installer is not installing on buster or higher.

So we are [unable to install PowerShell in Pengwin](https://github.com/WhitewaterFoundry/Pengwin/issues/502), which tracks testing.

But PowerShell is missing from [the repo](https://packages.microsoft.com/debian/10/prod/) for buster.

**Comment by MartinEtcheverry** [comment]
well , it will be nice install powershell in debian 10 just adding the repo . i am just saying.

**Comment by chuanjiao10** [comment]
when you will support?  ps 7 preview 6?
it seems that not in ps 7 preview 4, and ps 7 preview 5.

**Comment by TravisEz13** [comment]
@chuanjiao10 	This works, just hasn't been document.  You can see the status here.

**Comment by chuanjiao10** [comment]
@TravisEz13  ??? 
i not found install package in https://packages.microsoft.com/repos/microsoft-debian-buster-prod/pool/main/p/ .

en,I am not in a hurry.  wait for the ps7 with the official version of .net core 3

**Comment by TravisEz13** [comment]
We are not producing a new package as the existing package works.

**Comment by TravisEz13** [comment]
Docs were updated here:
https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4903
