### ISSUE TITLE
redone powershell icon over purple pink and blue

### ISSUE THREAD

**Issue by whitequill** [PowerShell/PowerShell#10258]
# Summary of the new feature/enhancement

I feel that he icon in Powershell 7 is not balanced and with a very neon pink and a very soft blue. I have a proposed icon that had slightly different colors as I saw in the Powershell 7 assets Powershell_avatar and I thought it still needed to look flashy.

# Proposed technical implementation details (optional)

Here is my proposed icon that I feel has more balanced colors over the purple and pink.
[pwsh_32513.zip](https://github.com/PowerShell/PowerShell/files/3445231/pwsh_32513.zip)

I would love to hear feedback on it and if anyone feels like my proposed colors aren't fitting. 
I did take a color theory class in college.

**Comment by iSazonov** [comment]
@whitequill Please follow issue pattern and add more info in the issue description.

**Comment by whitequill** [comment]
I'm sorry I thought I had typed it.
This issue is simply that the present icon for Powershell looks like it has a magenta transparent color color from gifs that is being shown and I think that the pink clashes with the blue a lot!

I am proposing a different color scheme. I noticed the
[pwsh_32513.zip](https://github.com/PowerShell/PowerShell/files/3449856/pwsh_32513.zip)
I picked the color triad of orange hex(ec7a00), red-orange hex(b01e00), and the current blue hex(00a3c9). the current analogical purple hex(461466), pink hex(ec008c) and the same blue, feel like they are vibrating and uncomfortable to the eyes.

**Comment by msftrncs** [comment]
@whitequill, you can go back and edit your original post.   You probably posted you information over the comment marks, and so your text is commented out.  You can then edit it and make the original post your proposal.

**Comment by whitequill** [comment]
@msftrncs sorry I didn't see notice the comment block at the time.

**Comment by vexx32** [comment]
@whitequill I believe the coloring of the icon is intended to match the coloring of the original character design for the "PowerShell Hero" (some of the art can be found [here](https://docs.microsoft.com/en-us/powershell/digital-art) and the branding you can see in the install process as well.

It's also worth noting that the current colour of the icon is only used for preview versions, and only to help distinguish it from the (usually fairly plain) black icon that is used for GA releases like the ones you can see on 6.0.x, 6.1.x, and 6.2.x. 🙂

**Comment by SteveL-MSFT** [comment]
@vexx32 is exactly right.  The official stable icon is the simple black one.  Only the Preview releases get the avatar themed one.

@whitequill your version actually looks pretty good, but not sure what we'd use it for since we already have branded icons to differentiate stable and preview releases.
