### ISSUE TITLE
Chinese charactor repeat

### ISSUE THREAD

**Issue by hotfics** [PowerShell/PowerShell#10259]
I typed  :ipconfig /all  in powershell 6.2.2  ,Win7  ,and then some messy charactor displayed.
the correct should be :Windows IP 配置
Now：Windows IP 配配置置
And so does other chinese charactors.
配置 means CONFIG

**Comment by hotfics** [comment]
![图片](https://user-images.githubusercontent.com/8078312/62118534-681ae900-b2f0-11e9-9264-fe93e0cf8b7f.png)

**Comment by g-plane** [comment]
This is an issue about the font of terminal, not related to PowerShell.

I'm using Consolas and this works well.
