### ISSUE TITLE
Compress-Archive is slow on 6.2.1 and 6.2.2

### ISSUE THREAD

**Issue by allanoro** [PowerShell/PowerShell#10264]
When I attempt to use 'Compress-Archive' on any folder with lots of items of varying sizes in PS 6.2.0 and the process will be rather quick. Attempt the same process on the same selection of files on PS 6.2.1 or 6.2.2 and the process takes a much longer time.

I've had to roll back to 6.2.0 on my desktop, but on a Win2012R2 server where I have tested 6.2.0, 6.2.1, and 6.2.2, the environment details are below for 6.2.1:

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@allanoro Please first report in https://github.com/PowerShell/Microsoft.PowerShell.Archive repo to investigate the issue and add reference on the issue so we could track a status.
