### ISSUE TITLE
ClearLinux: Distribution Support Request

### ISSUE THREAD

**Issue by robertbaker** [PowerShell/PowerShell#10261]
# Details of the Distribution

- Name of the Distribution: ClearLinux
- Version of the Distribution: 30490 or latest
- [x] The version of the Distribution is supported for at least one year.
- [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.
- [ ] The version of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Lifecycle updated
- [ ] Documentation Updated

**Comment by robertbaker** [comment]
Added issue for netcore team https://github.com/dotnet/core/issues/3124

**Comment by robertbaker** [comment]
Added issue for docker image: https://github.com/PowerShell/PowerShell-Docker/issues/253

**Comment by TravisEz13** [comment]
This distribution is not supported by DotNet.  Please work with DotNet to get the distribution supported first.
