### ISSUE TITLE
PowerShell 7 preview.2 adds @-character to `-character

### ISSUE THREAD

**Issue by Borkason** [PowerShell/PowerShell#10265]
On a german keybord, when pressing SHIFT-\` the @-character is inserted.
If you then press any other key, the \`-character is inserted.

So any combination with the accent key adds the @-character in front of the target character.

For example, this key combination

1. SHIFT-`
2. a
3. SHIFT-`
4. o
5. SHIFT-`
6. u
7. SHIFT-`
8. SPACE

results in 

``@à@ò@ù@` ``

instead of

``àòù` ``

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please remove PSReadline module and check again.

**Comment by Borkason** [comment]
Does not happen when PSReadline module is not loaded. What does this mean for this issue?

**Comment by iSazonov** [comment]
@Borkason Please move the report to PSReadline repo https://github.com/PowerShell/PSReadLine
