### ISSUE TITLE
Aliases are not exported from script module by default

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10268]
Based on the [current description of `Export-ModuleMember`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/export-modulemember?view=powershell-6#description), aliases and functions should be exported by default from any script module that does not explicitly invoke `Export-ModuleMember`. As you can see from the scenario below, that is not the case for script modules that do not have a manifest.

# Steps to reproduce

```powershell
nmo -name A {
function Test-A {
[CmdletBinding()]
[Alias('ta')]
param()
"'$($PSCmdlet.MyInvocation.MyCommand.Name)' was invoked."
}
} | ipmo

nmo -name B {
function Test-B {
[CmdletBinding()]
param()
"'$($PSCmdlet.MyInvocation.MyCommand.Name)' was invoked."
}
New-Alias tb Test-B
} | ipmo

ta

tb
```

# Expected behavior

```none
'Test-A' was invoked.
'Test-B' was invoked.
```

# Actual behavior

```none
ta : The term 'ta' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ta
+ ~~
+ CategoryInfo          : ObjectNotFound: (ta:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

tb : The term 'tb' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ tb
+ ~~
+ CategoryInfo          : ObjectNotFound: (tb:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Note that this issue is not a regression. It exists in Windows PowerShell 5.1 as well.

**Comment by bpayette** [comment]
@KirkMunro This is by design. In the absence of a manifest we decided not to export aliases by default.

**Comment by mklement0** [comment]
@bpayette: That's not true _in general_:

* Aliases do appear to be ignored in _dynamic_ modules (`New-Module`), as @KirkMunro's example demonstrates.

* They are _not_ ignored in _persisted_ script modules:

```
@'
function Test-A {
  [CmdletBinding()]
  [Alias('ta')]
  param()
  "'$($PSCmdlet.MyInvocation.MyCommand.Name)' was invoked."
}
  
function Test-B {
  [CmdletBinding()]
  param()
  "'$($PSCmdlet.MyInvocation.MyCommand.Name)' was invoked." 
}

Set-Alias tb Test-B
'@ > t.psm1

Import-Module ./t.psm1; ta; tb
```

**Comment by doctordns** [comment]
The working group has reviewed this issue and feels this is by design. We agree the documentation on dynamic modules should be updated to clarify this behaviour and would ask that the OP please create an issue in the PowerShell documentation repo.

**Comment by mklement0** [comment]
>  feels this is by design

So that the issue can be properly documented: 

What is the design _rationale_? Specifically, why would _dynamic_ modules behave differently?
