### ISSUE TITLE
Why does this happen?   {doc brown voice} That can't be done... can it?

### ISSUE THREAD

**Issue by ericleigh007** [PowerShell/PowerShell#10270]
# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none

```

**Comment by msftrncs** [comment]
@ericleigh007, I think you inadvertently left your question in the markdown comment blocks, you can edit your question and correct that.

**Comment by ericleigh007** [comment]
Sorry team, didn't intend to actually file this. Please excuse the interruption.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
