### ISSUE TITLE
Cannot enter Polish characters (diacritics) from keyboard

### ISSUE THREAD

**Issue by spajak** [PowerShell/PowerShell#10298]
I can't enter any special character (Polish) with keyboard, using right ALT + letter: `ęółśńćżź`. Just no reaction - nothing is showing.

I **can** enter this characters everywhere else (including cmd.exe) - except PowerShell Console.
I **have no** problem with printing any of the Unicode characters in any console.
I **have** Polish programmers keyboard input set.

Please help.

```
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Remove PSReadline and check the issue again.

**Comment by spajak** [comment]
Yes, It was `PSReadLine`. I've reinstalled it and now everything it is working. Thanks!
