### ISSUE TITLE
No help URI for get-help about_* -online

### ISSUE THREAD

**Issue by darthwalsh** [PowerShell/PowerShell#10306]
[x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
[x] Search the existing issues.
[x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
[x] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6?view=powershell-6).

# Steps to reproduce

```powershell
get-help about_Command_Precedence -online
```

_I ran `get-help about_*` and tried a few other entries, and they don't have online URIs either._

# Expected behavior

Browser opens https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-6

# Actual behavior

```none
PS C:\code> get-help about_Command_Precedence -online
get-help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
At line:1 char:1
+ get-help about_Command_Precedence -online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand
```

# Environment data

```none
PS C:\code> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by sdwheeler** [comment]
About topics don't have online URLs. That is by design because they are TXT files, not MAML like the cmdlet help. Changing that is on the roadmap for improvements to the Help system.
