### ISSUE TITLE
Double check cdxml modules in Safer API

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#10309]
I discovered that for cdxml modules PowerShell calls GetSaferPolicy() method twice:
1. https://github.com/PowerShell/PowerShell/blob/3ca5a1bdb031eeb9453b1481bcfa23eee6d89aec/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L1208
2. https://github.com/PowerShell/PowerShell/blob/3ca5a1bdb031eeb9453b1481bcfa23eee6d89aec/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L1260

Dozens of such modules can be installed on the system and this gives a noticeable delay in the command. 
`Get-Module -Listavailable -All` can consumes a lot of time - up to 25s on my computer at first run and up to 12s in follow runs.
After I remove GetSaferPolicy() - up to 9s at first run and up to 0.9s in follow runs

GetScriptInfoForFile() method has a checkExecutionPolicy parameter which is converted to CommandOrigin  in GetScriptInfoForFile() method but the CommandOrigin is ignored in follow method ShouldRunInternal() - so checkExecutionPolicy parameter doesn't work at all.

I hope we could find a way to remove the extra second check for cdxml modules. I'd expect that we could get 10% perf win at least in the scenario on Windows.
/cc @PaulHigin @SteveL-MSFT 

# Steps to reproduce

```powershell
Get-Module -Listavailable -All
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2-36-g3ca5a1bdb031eeb9453b1481bcfa23eee6d89aec
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@iSazonov Is this a regression caused by the windows update? Or it has always been slow?

**Comment by iSazonov** [comment]
@daxian-dbw I think it is always slow.
I checked on a test VM, install RSAT (to get many modules), run `Measure-Command { Get-Module -Listavailable -All }`
on Windows 10 1709 Enterprise then update OS to Windows 10 1803 Enterprise
(MS Defender)
- Windows 10 1709 Enterprise - 3.8s (1.25s without  GetSaferPolicy() call)
- Windows 10 1803 Enterprise - 3.84s (1.24s without  GetSaferPolicy() call)

Then I checked on HW computer with different antiviruses.
Windows 10 1809 Enterprise
- with KES/KAV and latest updates - 3.7s (0.46s without  GetSaferPolicy() call)
- with MS Defender (KES/KAV was removed) and latest updates - 3.0s (0.33s without  GetSaferPolicy() call)
- with MS Defender (KES/KAV was removed) and only March updates - 3.0s (0.33s without  GetSaferPolicy() call)

Conclusion:
- The Safer API is very slow always.

**Comment by PaulHigin** [comment]
@iSazonov 
I verified that the Safer API is called twice per CDXML module processing, however it would not be easy to change since the code paths are from different parts of module processing.

I also tried reproducing this by disabling Safer API for CDXML modules, but I did not see any significant perf difference when listing modules.  This may be because the Safer APIs can take varying amounts of time depending on whether it needs to refresh cert revocation list.  But in general I would expect the Safer check time to be insignificant compared to the work done in importing a module.

**Comment by iSazonov** [comment]
@PaulHigin Thanks!
>  I did not see any significant perf difference when listing modules.

Do you measure for default installation? I installed RSAT to get over 400 modules (I don't know how many csxml modules is there) - only in the case we will see significant delay in the scenario.

>  But in general I would expect the Safer check time to be insignificant compared to the work done in importing a module.

Yes, it is not significant for module import scenario. Here I consider another scenario - Get-Module -Listavailable -All - in the scenario we pass hundreds of files through Safer API.
Another scenario - run Pester tests for a project like the repo - again hundreds of files is passed through Safer API.
The worst part is also affecting completions in interactive scenario. On my computer where `Get-Module -Listavailable -All` takes sometimes over 20s, if I type `Get-<Tab>` after pwsh start it can takes a lot of time too.
I guess there is many users who install RSAT and many modules and who is prone to this problem.

**Comment by PaulHigin** [comment]
Yes, I tested with `gmo -list -all`.  I am not running RSAT but I do list > 1000 modules.  In any case I was measuring the difference between CDXML SaferAPI calls and no CDXML SaferAPI calls to try and get an idea of the impact of SaferAPIs.

However, I am sure machine/HD speed makes a difference, and as I mentioned I know that the API call time can vary greatly depending on whether cert revocation checks need to be made.

At least in my case the Safer APIs made no noticeable difference in performance.

**Comment by iSazonov** [comment]
>  I am sure machine/HD speed makes a difference

As we can see on screenshots https://github.com/PowerShell/PowerShell/pull/10244#discussion_r308518652  GetSaferPolicy() is on top, and no HD related API is in the trace.

> the API call time can vary greatly depending on whether cert revocation checks need to be made

I tested in closed enterprise environment and I'd guess that in second case (cert revocation) is main. But I turn on CAPI2 log and see only 40 events with Verify Trust category for signed cdxml files - _they takes only 1 second_. (And I see that the events presents twice).
Then I measure
```
Measure-Command { Get-Module -ListAvailable -All }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 10
Milliseconds      : 937
Ticks             : 109376769
TotalDays         : 0,000126593482638889
TotalHours        : 0,00303824358333333
TotalMinutes      : 0,182294615
TotalSeconds      : 10,9376769
TotalMilliseconds : 10937,6769
```
and 
```
Measure-Command {dir C:\windows\system32\WindowsPowerShell\v1.0\Modules\ -Recurse}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 11
Ticks             : 10113956
TotalDays         : 1,17059675925926E-05
TotalHours        : 0,000280943222222222
TotalMinutes      : 0,0168565933333333
TotalSeconds      : 1,0113956
TotalMilliseconds : 1011,3956
```

So I cannot confirm that cert revocation and HD cause the issue.

**Comment by iSazonov** [comment]
I collected a trace with WPR/WPA on HW computer with clean install OS.
The trace shows that 90% time it is GetSaferPolicy() and SRP API. (Below you can see 3.5s delay but there is second way with the same delay - we check cdxml twice, so delay is above 7s from 9s)
![pwsh-ge-module](https://user-images.githubusercontent.com/22290914/62695819-810e5300-b9f0-11e9-8456-b46f5f63314c.png)

I disconnect network cable and expect that the delay go away but I get the same delay. I guess the delay is not a network delay. The API is not documented and I can not confirm that it is CRL check problem.

**Comment by PaulHigin** [comment]
If you disconnect the network cable, then there will be a timeout delay if a cert revocation check is needed.

**Comment by iSazonov** [comment]
Usually all network delays go away if Windows haven't network - network API fast returns if network interface is down. It is my expectation (`ping unknowncomputer` returns without delay in the case).
