### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by GerryOnGithub** [PowerShell/PowerShell#10311]
Select "Properties" to change Colors. Be unhappy with the results. Attempt to restore the default Colors. Uninstall and reinstall in an attempt to get back to the default colors.

It should somehow be possible to find a light color combination that looks okay, and/or restore the default colors.

Can't restore default colors.

Typical Windows 10 professional PC.

**Comment by GerryOnGithub** [comment]
What's with this template?

**Comment by iSazonov** [comment]
@GerryOnGithub The repo is for developers. For support questions please use forums and other support channel.

**Comment by vexx32** [comment]
@GerryOnGithub can't remember the _exact_ key, but the colors are stored in the registry. I think it might be under `HKCU:\Console`.

Removing those values will cause PS to regenerate the defaults and populate the key.

**Comment by GerryOnGithub** [comment]
thanks vexx32

Computer\HKEY_CURRENT_USER\Console\C:_Program Files_PowerShell_6_pwsh.exe
