### ISSUE TITLE
Add read-only option for session

### ISSUE THREAD

**Issue by tmontney** [PowerShell/PowerShell#10312]
# Summary of the new feature/enhancement

An option should be added as a preference variable to set the session to read-only. While this is set, nothing outside local variables can be modified. Examples would be deleting a file off the file system or changing a system setting.

Feature is not meant to be a security feature, but to protect against accidents. Think of it as a "prevent accidental deletion/modification". As mentioned below, it adds another benefit to using official/built-in/proper functions.

# Proposed technical implementation details (optional)

This would target built-in PS functions, but possibly 3rd party. It would utilize approved PS verbs. If you call a function with a verb that means to modify/delete (e.g. `Set-Content` vs `Get-Content`), it will throw an exception.

**Comment by iSazonov** [comment]
@tmontney You could use Language mode https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-6
and JEA https://docs.microsoft.com/en-us/powershell/jea/overview
