### ISSUE TITLE
gcc Wl option error

### ISSUE THREAD

**Issue by ly303550688** [PowerShell/PowerShell#10314]
gcc -Wl,--kill-at
At line:1 char:8
\+ gcc -Wl,--kill-at
\+        ~
Missing argument in parameter list.
\+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
\+ FullyQualifiedErrorId : MissingArgument

**Comment by vexx32** [comment]
PowerShell typically tries to parse command arguments according to its standard semantics when directly calling them. You can either use the invocation operator `&` to run the command and explicitly pass arguments, or you could use the stop-parsing symbol:

```ps
& gcc '-WI,--kill-at'
# or
gcc %-- -WI,--kill-at
```
