### ISSUE TITLE
DE0006: Non-generic collections shouldn't be used (especially in Pester tests)

### ISSUE THREAD

**Issue by ThreeFive-O** [PowerShell/PowerShell#10315]
As per [.NET Platform compatibility rule DE0006](https://github.com/dotnet/platform-compat/blob/master/docs/DE0006.md) and [PowerShell coding guidelines](docs/dev-process/coding-guidelines.md) non-generic collections shouldn't be used.

In particular relevant for PowerShell would be `System.Collections.ArrayList` and `System.Collections.Hashtable`.

Most occurrences of `ArrayList` are in C# code obviously, but some can be found in Pester test files too (due to the lack of an internal dynamic array type in PowerShell).

Those two styles are found in Pester tests:
- `New-Object System.Collections.ArrayList`
- `[System.Collections.ArrayList]::new()`

**C# code**
The replacement of the non-generic collections in C# code by the generic ones might be non-trivial due to the type problems. For new code and code changes the rule should be followed as the replacement is an on-going process.

**Pester tests**
For Pester test files the PowerShell syntax should be favored over the explicitly typed C# equivalents:

- `System.Collections.Hashtable` -> `@{}`
- `System.Collections.ArrayList` -> `@()` (though being of type `Array`; in most cases the performance can be neglected using `+=` operator on `@()` on very small arrays; some instances might be refactored to use a `ForEach` loop which returns an `Array`)

**Comment by iSazonov** [comment]
PowerShell engine uses ArrayList as base type in PSObject and special variables, also it uses ArrayList for serialization and remoting. Changing this is huge breaking change.

Nevertheless, there are places where we use ArrayList unjustifiably and this can be fixed. Code becomes more readable and reliable.

**Comment by KirkMunro** [comment]
Also to be clear, DE0006 recommends avoiding the use of non-generic collections in _new_ code. For existing code we can consider the benefits gained from converting to generic collections where possible (i.e. for PowerShell, where such changes would be non-breaking), but that's it.

**Comment by ThreeFive-O** [comment]
@iSazonov and @KirkMunro I agree that the fundamental architecture of PowerShell should stay as it is.

> DE0006 recommends avoiding the use of non-generic collections in _new_ code.
This is what I meant with on-going replacement. 

@TravisEz13 @adityapatwardhan Not sure who is best informed about this, but do **Codacy** and **CodeFactor** have rules with an error or warning when using non-generic collections?

From @iSazonov's PR #10333 I can't find any hint that would suggest that Codacy or CodeFactor recognized the change from non-generic to generic collections (I would have guessed it should be marked as fixed issue in the logs of Codacy or CodeFactor).

**Comment by iSazonov** [comment]
I have never seen such warnings from Codacy or CodeFactor.

**Comment by ThreeFive-O** [comment]
@iSazonov I guessed so ☹

I'm not familiar with the tools, but maybe there is the possibility to implement custom rules or have some other tool do the check in the CI pipeline.

**Comment by vexx32** [comment]
We have adjusted Codacy and CodeFactor rules before; I think @TravisEz13 has worked with it, or maybe @daxian-dbw?

**Comment by TravisEz13** [comment]
Individual rules are adjusted by configuration files in the repo.  See the services web site for instructions, on how to add a configuration.

**Comment by iSazonov** [comment]
Most of ArrayList  was replaced. I close this because remaining ArrayList is used in engine and remoting.
