### ISSUE TITLE
Make 7.0 be the base version for builds

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10325]
When I'm working on PRs, the version of PowerShell that gets built is 6.0.0-alpha.10. I'd like to change that to 7.0.0-alpha.10 (or whatever...I just want it to be 7.0 since I'm working on 7.0-related functionality). Where is that base version set so that I can change it?

**Comment by SteveL-MSFT** [comment]
I believe you need to just run: git fetch --all --tags

**Comment by KirkMunro** [comment]
Wonderful, that was exactly what I needed. Thanks @SteveL-MSFT!
