### ISSUE TITLE
Get-ChildItem ignores -Depth parameter on DFStargets/shares

### ISSUE THREAD

**Issue by ChinALoiJ** [PowerShell/PowerShell#10332]
When using Powershell Core 6.2 the following command does only return toplevel folders and ignores the -Depth parameter when working with DFS targets/shares.
$Items = Get-ChildItem "\\fqdn\DFS" -Depth 5
$items returns:
Directory: \\fqdn\DFS

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----l         7/15/2019  9:13 PM                Diensten
d----l         7/15/2019  9:14 PM                Projecten

When using powershell 5.1 the following is returned
$Items returns (one example to clear this case):
Directory: \\fqdn\DFS\Projecten\Visual Studio 2017\Templates\ProjectTemplates

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/23/2018   6:08 PM                Extensibility
d-----        2/23/2018   6:08 PM                JavaScript
d-----        2/23/2018   6:08 PM                Service Fabric
d-----        2/23/2018   6:08 PM                TypeScript
d-----        2/23/2018   6:08 PM                Visual Basic
d-----        2/23/2018   6:08 PM                Visual C#
d-----        2/23/2018   6:08 PM                Visual C++ Project
d-----        2/23/2018   6:08 PM                Visual Web Developer

Is this a bug in Powershell Core 6, or am  I missing modules to work with DFS shares?
On a 'normal' file system this is not an issue. (local filesystem)

**Comment by iSazonov** [comment]
I can not repo with latest build.

**Comment by ChinALoiJ** [comment]
I have tested this with version 6.2.0 and 6.2.2. Both have the same issue.
Also tested with version 7.0.0 preview 2 and then this issue is solved. 
thx for your reply!
