### ISSUE TITLE
PSModulePath in powershell.config.json breaks history

### ISSUE THREAD

**Issue by Zerowalker** [PowerShell/PowerShell#10345]
# Steps to reproduce

Set powershell.config.json to something like:

{
"Microsoft.PowerShell:ExecutionPolicy":"RemoteSigned",
"PSModulePath": "C:\\PSModules",
}

# Expected behavior

Powershell should behave like normaly,
but simply have have the added PSModulePath in each new session.

# Actual behavior

Every new launch got it's history cleared.
Meaning Up/Down arrow yields nothing.
Removing the PSModulePath in the powershell.config.json file makes it work like normal again.

# Environment data

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@Zerowalker Please test the issue with #10300 artifacts.

**Comment by Zerowalker** [comment]
Unsure how i am supposed to test it.

**Comment by Zerowalker** [comment]
Okay i tried the latest git, i didn't need, but that one never remembers the history,
not sure if it's cause it's a git build rather than an installation or not though.

So modifying the config doesn't really matter here cause it's broken to begin with,
it does however preserve the $env:PSModulePath from the original powershell so that's good.

**Comment by iSazonov** [comment]
@Zerowalker If I understand you right modifing powershell.config.json does not matter and you should update your report and title.

**Comment by Zerowalker** [comment]
It does on PowerShell Core 6.
On Git when i enabled PSReadLine for history, it just breaks completely if i do the same for the config file.
But it might be me messing up the setup.
