### ISSUE TITLE
BiosSeralNumber should be BiosSerialNumber

### ISSUE THREAD

**Issue by clsmith70** [PowerShell/PowerShell#10349]
When you run the command and attempt to retrieve the *BiosSerialNumber*, it always comes back empty because the property in the returned object is misspelled.  The name it returns is **BiosSeralNumber**.

**Comment by vexx32** [comment]
Which command are you running that exhibits this behaviour, exactly @clsmith70? 🙂

**Comment by clsmith70** [comment]
@vexx32 I am running Get-ComputerInfo

**Comment by RichardSiddaway** [comment]
Windows PowerShell v5.1 reports the property as BiosSeralNumber

PowerShell v6.2.2 and v7.0 preview 2 both report the property as BiosSerialNumber

**Comment by iSazonov** [comment]
The issue was fixed in PowerShell Core.
Windows PowerShell is not in the repo. Please report using Windows Feedback tool or UserVoice site.
