### ISSUE TITLE
Feature Request: Publish DOS package

### ISSUE THREAD

**Issue by mcandre** [PowerShell/PowerShell#10342]
# Summary of the new feature/enhancement

As a power user, I want to be able to automate tasks for my DOS boxes with PowerShell. Ideally, syntax for job control operations enables users to launch multiple concurrent applications, such as FTPSrv and rmenu.

# Proposed technical implementation details (optional)

1. Publish a package for PowerShell to the FreeDOS repository, in the Development group.

https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/group-devel.html

**Comment by iSazonov** [comment]
PowerShell is based on .Net Core so you need to get .Net Core support for FreeDOS first of all.

**Comment by BrucePay** [comment]
@mcandre This isn't going to be possible until .Net Core is available on FreeDOS so I've marked it as resolution external. I'd suggest resolving this issue in favour of a linked issue against the .Net Core repo.
