### ISSUE TITLE
Active Directory Integrated Auth for Invoke-SqlCmd

### ISSUE THREAD

**Issue by Adikota** [PowerShell/PowerShell#10353]
Just wanted to see if there is an option to specify Active Directory Integrated auth when using Invoke-sqlcmd command let when connection Azure SQL Databases. This would alleviate the use of supplying Username and Password in the script

**Comment by iSazonov** [comment]
Review the docs https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication

**Comment by Adikota** [comment]
Yes I did, but was looking for examples where ad integrated auth is used in
invoke-sqlcmd.

**Comment by iSazonov** [comment]
@Adikota The repository is for PowerShell Core development. Invoke-sqlcmd and Azure authentication is out of the repo. Please use other resources like forums to resolve your question.
