### ISSUE TITLE
Set-Content on custom Providers

### ISSUE THREAD

**Issue by romero126** [PowerShell/PowerShell#10358]
When Implimenting a Custom PSProvider I am running into Strange Behavior.
When calling Set-Content to my PSProvider 

GetContentWriterDynamicParameters gets called and returns a custom Class Object
However it appears GetContentWriter's DynamicParameters gets populated with FileSystemContentWriter as casting it with my custom DynamicParameter returns null;

```
            if (DynamicParameters != null)
            {

                // [BUG] Regardless of override DynamicParameters is of type FileSystemContentWriterDynamicParameters
                // StreamContentWriterDynamicParameters dynParams = DynamicParameters as StreamContentWriterDynamicParameters;
                FileSystemContentWriterDynamicParameters dynParams = DynamicParameters as FileSystemContentWriterDynamicParameters;
                                                                 
                if (dynParams != null)
                {

                }
             }
```

**Comment by iSazonov** [comment]
@romero126 You referenced FileSystem provider code. Wh do you call it from your custom provider?  Your custom provider should implement IContentCmdletProvider.GetContentWriter().

**Comment by romero126** [comment]
@iSazonov I believe my focus is more on the Dynamic Parameters portion on this bug, not GetContentWriter.


When I implement my own override for **GetContentWriterDynamicParameters** to push out the class **StreamContentWriterDynamicParameters** it is does not get set in the _DynamicParameters_ object. No matter what I do it _DynamicParameters_ will always be set as type **FileSystemContentWriterDynamicParameters**

https://github.com/romero126/PS1C/blob/master/Source/PS1C/ZipFileProvider/ZipFileProvider.IContentCmdletProvider.cs#L208-L229

https://github.com/romero126/PS1C/blob/master/Source/PS1C/ZipFileProvider/ZipFileProvider.IContentCmdletProvider.cs#L277-L280

**Comment by iSazonov** [comment]
> DynamicParameters will always be set as type FileSystemContentWriterDynamicParameters

Do you see this in debugger? Is root class really a ZipFileProvider at the time?

**Comment by romero126** [comment]
@iSazonov In order to run that block of code, it would have to be a ZipFileProvider object otherwise it cant exist with that override. Dynamic Parameters is still getting set with FileSystemProvider though. So I would assume there's something funky going on with its Iteration through all Registered providers, when determining a name Resolution.

Note: the code uses -root parameter on new-psdrive as base path. So I can assume that it should be factored in, when searching for a bug fix.
