### ISSUE TITLE
Set-PSDebug -Trace 2 does not trace scripts ran with shebang

### ISSUE THREAD

**Issue by eedwards-sk** [PowerShell/PowerShell#10359]
# Steps to reproduce

- given executable script file `foo`:

  ```powershell
  #!/usr/bin/env pwsh
  
  Write-Host 'Hello World'
  ```

- given `Set-PSDebug -Trace 2`

- executing `./foo`:

  ```powershell
  > ./foo
  ```

# Expected behavior

```none
DEBUG:    1+  >>>> ./foo
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:    1+  >>>> Write-Host 'Hello World'

DEBUG:     ! CALL function '<ScriptBlock>'  (defined in file '/path/to/foo')
Hello World
```

# Actual behavior

```none
DEBUG:    1+  >>>> ./foo
DEBUG:     ! CALL function '<ScriptBlock>'
Hello World
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Note: Same behavior on `7.0.0-preview.2`

**Comment by bpayette** [comment]
@eedwards-sk  As implemented, tracing only applies to the current process. Since #! starts a new process, tracing doesn't propagate. This should be easy to fix by adding an environment variable to propagate the trace setting into a child process if that's what we want. I'll change the tag to be "enhancement".

**Comment by eedwards-sk** [comment]
@bpayette ah, that makes sense.

Being able to propagate the debug state into the child would definitely be nice!
