### ISSUE TITLE
File LastWriteTime appears identical between objects but tests as inequal

### ISSUE THREAD

**Issue by eedwards-sk** [PowerShell/PowerShell#10365]
# Steps to reproduce

given two files with the same LastWriteTime
```powershell
>Write-Host $null > ./foo

>Write-Host $null > ./bar

>(Get-Item ./bar).LastWriteTime = (Get-Item ./foo).LastWriteTime

>(Get-Item ./foo).LastWriteTime

Thursday, August 15, 2019 11:59:38 AM

>(Get-Item ./bar).LastWriteTime

Thursday, August 15, 2019 11:59:38 AM
```

# Expected behavior

```powershell
>(Get-Item ./foo).LastWriteTime -eq (Get-Item ./bar).LastWriteTime

True
```

# Actual behavior

```powershell
>(Get-Item ./foo).LastWriteTime -eq (Get-Item ./bar).LastWriteTime

False
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by eedwards-sk** [comment]
It appears that the milliseconds of the DateTime is not being copied. I confirmed the DateTimes actually are different:

```powershell
> (Get-Item ./foo).LastWriteTime.Millisecond
812
> (Get-Item ./bar).LastWriteTime.Millisecond
0
```

So perhaps the bug is with copying DateTime objects, or assigning it through `{file}.LastWriteTime = {file}.LastWriteTime`

**Comment by eedwards-sk** [comment]
Possibly related: https://social.technet.microsoft.com/Forums/ie/en-US/cdae9a4b-b2d2-4e05-8988-9fe9881a1c11/file-lastwrite-times?forum=winserverpowershell

This does not feel like intended behavior.

**Comment by vexx32** [comment]
I think this is a .NET Core issue, not a PowerShell issue. The objects underlying the cmdlets here that you're working with are managed by .NET Core, so if there's a bug in the property that occurs when it is set, there's not much PS can do to resolve it.

You may want to put together a small C# repro and file an issue in https://github.com/dotnet/corefx

**Comment by eedwards-sk** [comment]
@vexx32 thanks for the advice! I'll close this and open a .NET Core issue.
