### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1036]
## Steps to reproduce
- Open terminal in OS X, with "Basic" (default) color schema. 
- Run powershell
- run `throw "foo"`
## Expected behavior

Colors look ok
## Actual behavior

Colors don't look ok

![image](https://cloud.githubusercontent.com/assets/816680/15525256/6d0aa95c-21dd-11e6-81b6-2874cf703472.png)
## Environment data

v0.4.0

cc @nanalakshmanan

**Comment by twblalock** [comment]
I'm able to set some of the colors on Mac OS, but the names of commands as I type them out remain yellow no matter what.

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#472

**Comment by Oxicode** [comment]
+1 Ubuntu

**Comment by jszabo98** [comment]
The default colors aren't great in osx, especially white on white for numbers and members, yellow for commands, and grey for types.

Btw when I tab complete on set-psreadlineoption or get-psreadlineoption, it pops up twice.

**Comment by joeyaiello** [comment]
@jszabo98 agreed on all fronts. The tab-completion bug is known too (I think it's somewhere in the PSReadline repo)

**Comment by milindsaraswala** [comment]
I am late to the party but I found the article which make your mac terminal window same like windows PowerShell. By Setting Profile. Please follow this below article
https://info.sapien.com/index.php/quickguides/setting-up-powershell-on-your-mac

**Comment by casperghst42** [comment]
We are not 4 years down the line, and there has been absolutely no update. It is interesting as Microsoft are now trying the "Run Everywhere" idea, but they are failing to make it a nice experience.

**Comment by jszabo98** [comment]
My current setup.  I just did this on a new mac.

```powershell
set-psreadlineoption -colors @{ 
  command            = 'darkyellow'
  number             = 'black'
  member             = 'black'
  operator           = 'black'
  type               = 'black'
  variable           = 'darkgreen'
  parameter          = 'darkgreen'
  continuationprompt = 'black'
  default            = 'black'
}

$host.PrivateData.VerboseForegroundColor = 'DarkYellow'
$host.PrivateData.WarningForegroundColor = 'DarkYellow'
$host.PrivateData.DebugForegroundColor = 'DarkYellow'
$host.PrivateData.ProgressForegroundColor = 'DarkYellow'
```

**Comment by casperghst42** [comment]
> My current setup. I just did this on a new mac.
> 
> ```powershell
> set-psreadlineoption -colors @{ 
>   command            = 'darkyellow'
>   number             = 'black'
>   member             = 'black'
>   operator           = 'black'
>   type               = 'black'
>   variable           = 'darkgreen'
>   parameter          = 'darkgreen'
>   continuationprompt = 'black'
>   default            = 'black'
> }
> 
> $host.PrivateData.VerboseForegroundColor = 'DarkYellow'
> $host.PrivateData.WarningForegroundColor = 'DarkYellow'
> $host.PrivateData.DebugForegroundColor = 'DarkYellow'
> $host.PrivateData.ProgressForegroundColor = 'DarkYellow'
> ```

Thanks, very helpful.
