### ISSUE TITLE
Feature Request - Cross-Compile Powershell for PowerPC (PPC) architecture

### ISSUE THREAD

**Issue by bwright86** [PowerShell/PowerShell#10373]
Cross-compile Powershell to PowerPC (ppc) architecture.

This would allow Powershell to be utilized on IBM hardware (Power-series) which run RHEL, UNIX, and other *nixes.

As a sys admin with a work environment that is split between VMWare and IBM Power-series frames. Having powershell available on both platforms would allow a unified approach to managing them.

This idea was already mentioned on UserVoice a while ago, but it hasn't gained much reach. So I am not aware of how many users would find this beneficial.

Here is a link:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/33127174-powershell-core-on-ibm-power-series-hardware

**Comment by iSazonov** [comment]
@bwright86 PowerShell Core is based on .Net Core and can only works on OSes which is supported by .Net Core.
You can find supported OS list here https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md
There is no support for PowerPC. 
You should move your feature request to .Net Core repo.
