### ISSUE TITLE
New request -- get-winevent: get all log generated by a specific user

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#10374]
If I try to find when the user abc.cd logon to my computer.
I will do a log query as follow.
`Get-WinEvent -FilterHashtable @{logname='security';data='abc.cd';id=4624}`

If I want to know when a software was install on computer.
I will do a log query as follow.
`Get-WinEvent -FilterHashtable @{logname='application';id=11707}`

but It does not work with a user ID as follow.
`Get-WinEvent -FilterHashtable @{logname='application';id=11707;data='abc.cd'}`

What I do I want is collectting all logs that caused by the user abc.cd by using get-winevent , like he installs a new software , he starts a service ,he starts a scheduled task ..

expected cmdlet: 
`Get-WinEvent -FilterHashtable @{logname=alllog;user='abc.cd'}`

**Comment by iSazonov** [comment]
It is question for a forum. 
[See (Russian only)](https://isazonov.wordpress.com/2013/01/27/%d0%ba%d1%82%d0%be-%d0%b8-%d0%be%d1%82%d0%ba%d1%83%d0%b4%d0%b0-%d0%bf%d0%be%d0%b4%d0%ba%d0%bb%d1%8e%d1%87%d0%b0%d0%bb%d1%81%d1%8f-%d0%bf%d0%be-rdp/) how looks XML request.
