### ISSUE TITLE
Test-Connection -Quiet not working

### ISSUE THREAD

**Issue by clsmith70** [PowerShell/PowerShell#10370]
In PowerShell v5, Test-Connection -Quiet will return True or False, in PowerShell Core 6.2.2, it still returns the entire ping result.  In scripts I have that pipe the result to Out-Null, it works fine in v5, but 6.2.2 still outputs data.

![image](https://user-images.githubusercontent.com/6304269/63178375-e9c08580-c017-11e9-867f-5c64bdb52344.png)

**Comment by vexx32** [comment]
This is a duplicate of #6768 

I also have an in progress draft PR #10044  that will resolve this specific issue as well as add some additional improvements. I plan to finish it before PS7 release, but I have not had a lot of time to work on it recently. I'll see if I can get the kinks ironed out by this weekend, and then start getting the necessary PRs in, one at a time. 🙂

**Comment by clsmith70** [comment]
That makes sense.  I only posted after testing it out when one of the functions in a custom module for work was returning the result from Test-Connection that is piped to Out-Null in the script.  It does not output any results in PS v5.1, but in PS 6.2 it does.  I'll rewrite one of the functions and add something similar to your example above and test it out.  This should suffice until your work is complete.

Thanks @vexx32!

**Comment by tibmeister** [comment]
I don't know if I would close this as resolved because the root issue is still not resolved, being that -Quiet still does absolutely nothing and I don't get a $True/$False return easily.  How about we fix this before closing it, or I don't know, re-introduce the original code from 2 years ago that already had this fixed without needing this stupid workaround.

**Comment by vexx32** [comment]
You will in ps7. I have a PR that addresses this which I think is already merged, and there are further PRs in review that will further improve the output from Test-Connection.
