### ISSUE TITLE
powershell equivalent of lsof

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#10378]
I want to know which process is locking this file by using powershell :
"C:\Windows\System32\LogFiles\Firewall\pfirewall.log"

In Linux if I want to check which process is locking my file ,I will do the following code:

```
sudo lsof /var/lib/dpkg/lock
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
aptitude 4974 root    3uW  REG   8,23        0 815673 /var/lib/dpkg/lock
```
So handy ,right?

How about PS ?

**Comment by tlsalex** [comment]
Maybe handle.exe from sysinternal tool is a good way, but it does not ship with windows

```
PS C:\ProgramData\chocolatey\bin> .\handle.exe C:\Windows\System32\LogFiles\Firewall\pfirewall.log

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

svchost.exe        pid: 3824   type: File           1E8: C:\Windows\System32\LogFiles\Firewall\pfirewall.log
```

**Comment by KalleOlaviNiemitalo** [comment]
The [openfiles](https://docs.microsoft.com/windows-server/administration/windows-commands/openfiles) command ships with Windows, but it requires first enabling the feature and rebooting.

If you suspect a process, you can also use [!handle](https://docs.microsoft.com/windows-hardware/drivers/debugger/-handle) in Debugging Tools for Windows to confirm. I think the NTSD.EXE debugger frontend shipped with Windows XP but not with Windows 7.
