### ISSUE TITLE
If you put a placeholder ExperimentalFeature in test/tools/TestMetadata.json with an empty array of test files, unrelated Pester tests will fail

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10384]
# Steps to reproduce

While working on #10338, I added a placeholder for future tests that I was going to add related to a new Experimental Feature. The reason for the "future" tests were because the initial PR work was to add SDK functionality, and then a follow-up PR was going to add parameters to some cmdlets that could be tested if the Experimental Feature was enabled. It turns out that if you do this, you'll get failures from a test in the `test\powershell\engine\ExperimentalFeature\Get-ExperimentalFeature.Tests.ps1` file on each of the platforms, and you may see a failure on a test in the `test\powershell\Modules\Microsoft.PowerShell.Core\CompatiblePSEditions.Module.Tests.ps1` file on the Windows platform as well.

Here are the contents of my `test/tools/TestMetadata.json` file that resulted in the unexpected CI failures:

```powershell
{
  "ExperimentalFeatures": {
    "ExpTest.FeatureOne": [ "test/powershell/engine/ExperimentalFeature/ExperimentalFeature.Basic.Tests.ps1" ],
    "PSManageBreakpointsInRunspace": [],
    "PSForEachObjectParallel": [ "test/powershell/Modules/Microsoft.PowerShell.Utility/Foreach-Object-Parallel.Tests.ps1", "test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1" ]
  }
}
```

# Expected behavior

The CI tests should pass.

# Actual behavior

You'll see failures like the following:

```none
@KirkMunro, your last commit had 2 failures in PowerShell-CI-windows
PSModulePath changes interacting with other PowerShell processes.System32 module path prepended to PSModulePath.Allows PowerShell subprocesses to call core modules

Expected $null, but got @(Get-ChildItem : The 'Get-ChildItem' command was found in the module 'Microsoft.PowerShell.Management', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Management'., At line:1 char:1, + Get-ChildItem, + ~~~~~~~~~~~~~, + CategoryInfo          : ObjectNotFound: (Get-ChildItem:String) [], CommandNotFoundException, + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule,  ).
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Core\CompatiblePSEditions.Module.Tests.ps1: line 353
353:             $errors | Should -Be $null

Default enablement of Experimental Features.On preview builds, Experimental Features are enabled

Expected: Feature PSCommandNotFoundSuggestion to be Enabled
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\ExperimentalFeature\Get-ExperimentalFeature.Tests.ps1: line 176
176:             $expFeature.Enabled | Should -BeEnabled -Name $expFeature.Name
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2-80-g93fff6de2121ab25144f5921c1c2d1aa71536bce
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
An empty array is not a place holder.
For each key-value pair in `TestMetadata.json`, CI will start a pwsh session with only that feature enabled, and then run the specified tests:
 - if the value is a non-empty array, run the tests defined in the array.
 - if the value is an empty array, run all powershell tests.

So, `"PSManageBreakpointsInRunspace": []` means starting a pwsh session with only the experimental feature `PSManageBreakpointsInRunspace` turned on, and then run all powershell tests in that session.

For the failure in `Get-ExperimentalFeature.Tests.ps1`, the corresponding tests were added recently after enabling all experimental features by default for preview releases. It assumes all experimental features should be enabled, and thus will fail with only `PSManageBreakpointsInRunspace` is turned on. No idea about the `CompatiblePSEditions.Module.Tests.ps1` failure though, it looks to me unrelated to any experimental feature.

Given that now all experimental features are enabled by default except for official release, there is no point to depend on `TestMetadata.json` for testing an experimental feature. The only purpose of it is to test the experimental feature infrastructure itself. However, tests for all experimental features should check if the expected feature is enabled, and skip the tests if not.

**Comment by KirkMunro** [comment]
Thank you for these details @daxian-dbw, they are very helpful.

> An empty array is not a place holder.
> For each key-value pair in `TestMetadata.json`, CI will start a pwsh session with only that feature enabled, and then run the specified tests:
> 
>     * if the value is a non-empty array, run the tests defined in the array.
> 
>     * if the value is an empty array, run all powershell tests.

Can we add to that support for if the value is `$null` don't run any specific PowerShell tests? That could allow for identification that an Experimental Feature requires some manual testing.

> So, "PSManageBreakpointsInRunspace": [] means starting a pwsh session with only the experimental feature PSManageBreakpointsInRunspace turned on, and then run all powershell tests in that session.

I don't think many contributors are aware of that. It would be great if that behavior was documented in the Experimental Feature documentation. 

> No idea about the CompatiblePSEditions.Module.Tests.ps1 failure though, it looks to me unrelated to any experimental feature.

That's what I thought as well, yet that failure went away when I removed my update to `TestMetadata.json`. 🤷‍♂ 

> Given that now all experimental features are enabled by default except for official release, there is no point to depend on TestMetadata.json for testing an experimental feature. The only purpose of it is to test the experimental feature infrastructure itself. However, tests for all experimental features should check if the expected feature is enabled, and skip the tests if not.

There is a minor issue with this: I discovered some tests that should have been skipped if an experimental feature was not enabled were accidentally enabled (and failing) all the time because of how I configured `TestMetadata.json`. Since tests are not just run in CI, but also in dev environments, I think all experimental feature test files (as identified in `TestMetadata.json`) should be run with experimental features disabled.

Now that we're running tests with all experimental features on by default in preview builds, we should still depend on `TestMetadata.json`, but in the opposite way: use it to identify test files related to experimental features, and run those tests explicitly with all experimental features disabled. That will allow CI to catch Pester test issues early so that they don't impact other developers.

**Comment by daxian-dbw** [comment]
> I don't think many contributors are aware of that. It would be great if that behavior was documented in the Experimental Feature documentation.

Absolutely. I will update the [`testing-guidelines`](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md) shortly after.

> Can we add to that support for if the value is `$null` don't run any specific PowerShell tests? That could allow for identification that an Experimental Feature requires some manual testing.

I'm not sure about the the usefulness of this setting because no one will monitor `TestMetadata.json` to track what experimental features requires manual testing.

> we should still depend on TestMetadata.json, but in the opposite way: use it to identify test files related to experimental features, and run those tests explicitly with all experimental features disabled. That will allow CI to catch Pester test issues early so that they don't impact other developers.

I agree that we should have a way to catch the experimental feature tests that do not skip tests appropriately when the corresponding feature is disabled. But `TestMetadata.json` cannot be simply used in the opposite way for this because we still depend on its current behavior to test the experimental feature infrastructure itself -- `ExpTest.FeatureOne` is not a real experimental feature that would be enabled by default, but a fake one only to test the experimental feature code. Having the developers to update the corresponding book-keeping file for the experimental feature tests to be added will also be a problem, as the tests will run by default and there won't be a reason to force them to update a file like `TestMetadata.json`.

**Comment by KirkMunro** [comment]
Ok. I'm going to close this out since you're going to update the `testing-guidelines` doc, and this is really a non-issue based on the additional information you provided (thanks for that).
