### ISSUE TITLE
Could not find WWW-Authenticate header in response

### ISSUE THREAD

**Issue by MrZakos** [PowerShell/PowerShell#10388]
I'm using [Skype for Business Online, Windows PowerShell Module](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell) , on .net core project I get 
"Could not find WWW-Authenticate header in response" , when using .net 4.x project with System.Management.Automation it works fine.

* running the script inside Powershell(ISE/normal/...) works fine as well.
* Windows 10

**Comment by iSazonov** [comment]
@MrZakos Could you please share a simple repo?

**Comment by MrZakos** [comment]
@iSazonov  

![image](https://user-images.githubusercontent.com/999613/63339430-8901b780-c34d-11e9-9a45-7ec4dd6f2354.png)

**Comment by iSazonov** [comment]
@MrZakos Thanks! If you run PowerShell Core interactive session and execute your script there do you get the same error?

**Comment by MrZakos** [comment]
how i run "Powershell Core" ? 
is this "Powershell Core" ?
![image](https://user-images.githubusercontent.com/999613/63351196-7300f080-c367-11e9-87a3-6780e30e6919.png)

**Comment by MrZakos** [comment]
@iSazonov  so is it 
powershell .core bug 
or a
SFB-PowerShell-Module problem ?

**Comment by iSazonov** [comment]
@MrZakos I think you need to move the report to https://github.com/PowerShell/PowerShellModuleCoverage or report directly to SfB team to investigate the compatibility issue.
