### ISSUE TITLE
Distribution Support Request: Ubuntu 19.04

### ISSUE THREAD

**Issue by Pr0methean** [PowerShell/PowerShell#10394]
The version from the Ubuntu 18.04 package repo isn't installable on Ubuntu 19.04.

# Details of the Distribution

- Name of the Distribution: Ubuntu Dingy Disco
- Version of the Distribution: 19.04
- [ ] The version of the Distribution is supported for at least one year.
- [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.
- [x] The version of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker (https://github.com/PowerShell/PowerShell-Docker/issues/265)

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Lifecycle updated
- [ ] Documentation Updated

**Comment by TravisEz13** [comment]
This is an interim release per Ubuntu (https://ubuntu.com/about/release-cycle) .  We don't support interim releases.
