### ISSUE TITLE
Feature Request: Improved [DBNull]::Value comparison

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/PowerShell#10404]
# Summary of the new feature/enhancement

As a PowerShell user, I expect some (many!) conveniences with regards to comparisons and type conversions.  [dbnull]::value has had some improvement recently with #9794 but could use improvements with other comparisons, e.g. `[dbnull]::value -gt 10` should _not_ error out, at least from my perspective.

A practical example.  Let's say I have a CMDB with dbnull in a few spots I want to do comparisons:

```powershell
#Example scenario with a function that uses Invoke-Sqlcmd2 to pull data
    Get-XXXXServer | Where-Object{$_.VCNumCPUs -gt 8}
    #Error for every line where VCNumCPU has DBNull value

    #workaround before recent dbnull handling fix
    Get-XXXXServer | Where-Object{[string]$_.VCNumCPUs -and $_.VCNumCPUs -gt 8}
```

There is precedence for this:  `$null -gt 10` is `$false`, and `10 -gt $null` is `$true`

Cheers!

**Comment by vexx32** [comment]
🤔 interesting... would have to look at the binders for those operators to see if there's a specific provision for `$null` values like there was for `-eq` and `-ne`... Might also just be that there's not an available conversion path for `DBNull`->`int`.

Probably both, unless I miss my guess. What do you think, @SeeminglyScience?

**Comment by vexx32** [comment]
Ha! Called it:

https://github.com/PowerShell/PowerShell/blob/8234fbb04b437748b6782e9c45b0026c374ef12d/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L3213-L3233

Looks like we need to swap these checks for null to `LanguagePrimitives.IsNullLike()` for this to work. 🙂 

The binders for the related operators are similar and not far from these lines.

Fancy a PR, @RamblingCookieMonster? 😉
