### ISSUE TITLE
Dead key detection not working in PowerShell 7.0.0-preview.3

### ISSUE THREAD

**Issue by MovGP0** [PowerShell/PowerShell#10400]
# Steps to reproduce

Install a multi layer keyboard layout like Neo2 and try to enter special caracters.

# Expected behavior

Dead key detection should work properly for non-standard keyboard layouts. 

The problem was already fixed in PSReadLine: 
https://github.com/PowerShell/PSReadLine/issues/914

# Actual behavior

There is an @ entered before the character. Apparently the current preview uses an old version of PSReadLine. 

# Environment data

PowerShell 7.0.0-preview.3

**Comment by uldisv** [comment]
Another way to reproduce - install keyboard, that uses "dead keys" for accented characters (f.e. Latvian).
Pressing on a tilde (~), immediately produces @ sign. 
Expected behaviour: depending on next pressed key - if again ~, then ~. Otherwise accented/diacritical letter.

**Comment by vexx32** [comment]
I think the latest preview is using the most recent PSReadLine release by default? @MovGP0 @uldisv can you check on the latest v7 preview?

**Comment by uldisv** [comment]
> I think the latest preview is using the most recent PSReadLine release by default? @MovGP0 @uldisv can you check on the latest v7 preview?
Works fine on Powershell 7.0 preview v.4 on Windows 10 x64.
Perfect - thank you.

**Comment by iSazonov** [comment]
@uldisv Please share PSReadline version. (Get-Module show this)

**Comment by uldisv** [comment]
> @uldisv Please share PSReadline version. (Get-Module show this)

ModuleType Version    PreRelease Name                                
---------- -------    ---------- ----                                
Script     2.0.0      beta5      PSReadLine

**Comment by MovGP0** [comment]
Can confirm that it works in PowerShell 7.0.0-preview.4
