### ISSUE TITLE
Handle SIGTERM like Windows SHUTDOWN signal

### ISSUE THREAD

**Issue by andyleejordan** [PowerShell/PowerShell#1040]
In other words, port [this](https://github.com/PowerShell/PowerShell/blob/d811fe37ea376fead1f62c2c1de01dc2f0689f7f/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L334) to work on Linux.

This is not an event we'll receive from `System.Console` (all signals received by the event handler are handled in #1039), but we should catch `SIGTERM` and call `SpinUpBreakHandlerThread(true)`.

/cc @lzybkr

**Comment by mwrock** [comment]
Agreed this would be nice. I just ran into this and was surprised to see a `finally` block not invoked in response to a `SIGTERM`.

**Comment by pcgeek86** [comment]
+1 @SteveL-MSFT

**Comment by iSazonov** [comment]
New .Net 6.0 API `PosixSignalRegistration` https://github.com/dotnet/runtime/issues/50527#issuecomment-825858901
