### ISSUE TITLE
"ForEach-Object -Parallel" problem with "6>$null"

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#10419]
Q:"ForEach-Object -Parallel" released, the first thing you think of is?
A:ping test

**Too many people will test "ForEach-Object -Parallel" with Test-Connection**

Q:How to hide the output? use Test-Connection
A:
you must use "6>$null"

eg:
Test-Connection  -Count 1 -TargetName bing.com -Quiet
Pinging bing.com [204.79.197.200] with 32 bytes of data: 
Reply from 204.79.197.200: bytes=32 time=43ms TTL=128
Ping complete.
True

Test-Connection  -Count 1 -TargetName bing.com -Quiet 6>$null
True

Q:Combination "ForEach-Object -Parallel" and "6>$null" problem?
A:
yes!so, "ForEach-Object -Parallel" need update.

hi @PaulHigin  ,this is my feedback,have a look,thanks.

Steps to reproduce
------------------
Get-Content /powershell/71.txt |ForEach-Object -Parallel {if (Test-Connection -Count 1 -TargetName $_ -Quiet  6>$null) {$_} } 

Expected behavior
-----------------

```
Get-Content /powershell/71.txt |ForEach-Object  {if (Test-Connection -Count 1 -TargetName $_ -Quiet  6>$null) {$_} } 


71.1.4.1
71.1.5.1
71.1.6.1
71.1.7.1                                                                                                                                          71.1.8.1                                           71.1.16.1
```

Actual behavior
---------------

```
Pinging 71.1.4.1 [71.1.4.1] with 32 bytes of data:
Pinging 71.1.5.1 [71.1.5.1] with 32 bytes of data:
Pinging 71.1.6.1 [71.1.6.1] with 32 bytes of data:
Pinging 71.1.7.1 [71.1.7.1] with 32 bytes of data:
Pinging 71.1.8.1 [71.1.8.1] with 32 bytes of data:
Reply from 71.1.4.1: bytes=32 time=246ms TTL=128
Ping complete.
71.1.4.1
Reply from 71.1.5.1: bytes=32 time=259ms TTL=128
Ping complete.
71.1.5.1
Reply from 71.1.6.1: bytes=32 time=241ms TTL=128
Ping complete.
71.1.6.1
Reply from 71.1.8.1: bytes=32 time=271ms TTL=128
Ping complete.
71.1.8.1

```

Environment data
----------------
centos76 + ps v7.0 preview3

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

**Comment by awakun** [comment]
You can also accomplish hiding the output of TestConnecction with -InformationAction 'Ignore', but I agree that the stream redirect should probably work.

**Comment by chuanjiao10** [comment]
@awakun it work,thanks. 
Maybe we can't let Test-Connection return that information, at -Quiet

**Comment by vexx32** [comment]
Yeah. I have a WIP PR that accomplishes this. I need to bring it back up and fix whatever's going awry with the failing test so we can get that merged and sorted for 7.0

**Comment by PaulHigin** [comment]
@chuanjiao10   Thanks for report.  To suppress the information data stream try doing this:
```powershell
Get-Content /powershell/71.txt |ForEach-Object -Parallel {if (Test-Connection -Count 1 -TargetName $_ -Quiet) {$_} } 6>$null
```

**Comment by chuanjiao10** [comment]
remove Resolution-Answered  label 
this fixed via  https://github.com/PowerShell/PowerShell/pull/10478
