### ISSUE TITLE
Names from Get-LocalGroupMember are not compatible with Get-LocalUser -Name <string>Feature Request

### ISSUE THREAD

**Issue by HenkPoley** [PowerShell/PowerShell#10415]
# Summary of the new feature/enhancement

Essentially this issue: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4622

> You would expect these two to "speak the same language".
> 
> Get-LocalGroupMember outputs 'COMPUTERNAME\username'
> Get-LocalUser expects the format 'username', and doesn't understand the above.
> 
> It would be nice if this simple incompatibility was resolved.

If you ask for a list of users in a group (Get-LocalGroupMember), and then for data about each user (Get-LocalUser), you would expect Get-LocalUser to understand the usernames you got from the group. But it expects you to strip the computer name first.

# Proposed technical implementation details (optional)

I would recommend to add a little check in Get-LocalUser that looks if names are prepended with the local computer name.

**Comment by iSazonov** [comment]
@HenkPoley The cmdlet is not in the repo. Please use Windows 10 feedback tool for the request.

**Comment by HenkPoley** [comment]
Okay. Just submitted a feedback from Windows 10 1903 🤷‍♂️
