### ISSUE TITLE
ErrorVariable is not set when using Get-InstalledModule cmdlet

### ISSUE THREAD

**Issue by tarikguney** [PowerShell/PowerShell#10424]
Poweshell Version: 6.1.4

`ErrorVariable` is not set when an error happens as seen in the screenshot below. However, if you use `+` append sign in front of the variable, it works.

# Steps to reproduce

Below you will see that I try to run the command without the `+` to set the `ErrorVariable`, which won't work. Later, it works with `+` with a different parameter. In the first case, outputting the `$errorVariable` does not display anything. 

![image](https://user-images.githubusercontent.com/369188/63544666-ec711e00-c4e2-11e9-9fda-d3c42ec064b8.png)

# Expected behavior

`ErrorVariable` should be working without the need of `+` append operator in front.

# Actual behavior

`ErrorVariable` is not set when an error happens.

# Environment data

![image](https://user-images.githubusercontent.com/369188/63544920-728d6480-c4e3-11e9-8304-743643080c42.png)

**Comment by vexx32** [comment]
Can you please test with the latest release and see if this is still an issue? 🙂 

Also, is this occurring with _all_ cmdlets, or just that one cmdlet you're using here?

**Comment by tarikguney** [comment]
@vexx32 Latest release like on the Powershell Core version 7 line or version 6 line? Because I have downloaded it from here https://github.com/PowerShell/PowerShell/releases/tag/v6.2.2 which is latest for the version 6 line.

Also it seems to be happening in other command line environments too. This one, for instance, from ConEmu:

![image](https://user-images.githubusercontent.com/369188/63545443-a321ce00-c4e4-11e9-98e1-3e94cd712c29.png)

**Comment by tarikguney** [comment]
And one last attempt on the Windows CMD, and the issue appears to be happening there too.

![image](https://user-images.githubusercontent.com/369188/63545610-11669080-c4e5-11e9-8c56-2612d911d13d.png)

**Comment by vexx32** [comment]
Latest release, period. If it's already fixed in PS7 it's likely that it won't be backported to 6.1.x branch. Typically only critical / security fixes are backported at the moment.

Console environment shouldn't matter, PowerShell is PowerShell, wherever you're running it. 🙂

**Comment by tarikguney** [comment]
@vexx32 Oh wait, you said `cmdlet`, I thouht you mean `cmd` environments. Let me try with other cmdlets.

**Comment by KirkMunro** [comment]
I was able to reproduce the issue on PowerShell 7 preview 3, and it seems specific to `Get-InstalledModule`. For example, the following works fine:

```
gps -id 123323123 -ev foo
$foo
```

**Comment by vexx32** [comment]
I guess that makes this a PowerShellGet issue?

Genuinely not sure how you'd author a cmdlet that breaks this behaviour, though. I didn't think it could be done.

@SteveL-MSFT are you familiar with this cmdlet at all? Might be worth a look as you guys get towards PSGet 3.0, if this cmdlet is being retained going forward.

**Comment by KirkMunro** [comment]
PowerShellGet has a rather...creative implementation.

**Comment by iSazonov** [comment]
@tarikguney Please move the issue to PowerShellGet repo.
