### ISSUE TITLE
Get-CimInstance is not recognized as the name of a cmdlet -PowerShell 7 SDK

### ISSUE THREAD

**Issue by xGord** [PowerShell/PowerShell#10433]
I'm not able to run the command _Get-CimInstance_ from a net core console application with PowerShell 7 sdk (preview 3). The error I get is 

> System.Management.Automation.CommandNotFoundException: The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

To reproduce create a net core 3.0 preview 8 console application.  Add nuget Microsoft.PowerShell.SDK and System.Management.Automation. 
This is the code running

    using (PowerShell powerShell = PowerShell.Create())
    {
     powerShell.AddCommand("Get-CimInstance").AddArgument("win32_PnPSignedDriver");
     var drivers = powerShell.Invoke().ToList();
     foreach (var driver in drivers)
     {
       Console.WriteLine(driver.Members["Description"].Value);
     }
    }

When adding powershell referenceassemblies for version 5 this runs perfect. 

Anyone one what the problem is?

**Comment by vexx32** [comment]
When running PowerShell from the API for v6+ PowerShell can't realistically make any assumptions about where modules may be installed -- PowerShell can now be installed basically _anywhere_ on a computer, so there's no guarantee that the modules are in any specific location.

You'll need to populate the `$env:PSModulePath` variable before executing most commands. 🙂

**Comment by xGord** [comment]
Thanks for your answer. I have added the path `C:\Program Files\PowerShell\7-preview\Modules` to the PSModulePath environment variable. There is however a difference between the paths in this environment variable in windows and the paths when running `$env:PSModulePath` in powershell. But both of the are having the above path in them. Do I need to somehow load these modules in the code?

**Comment by vexx32** [comment]
You may need to set the variable from the PowerShell session, I'm not entirely sure how that gets populated. @SteveL-MSFT does PowerShell load that variable from the existing environment variables when it starts?

**Comment by xGord** [comment]
I have read some issues around some problems for powershell core on this variable. However this breaks my thoughts around powershell core. I need powershell core to be supplied with the single exe I am publishing and not be dependant on what version is installed on the OS. After fighting a lot of issues I'm not sure that this will be possible yet?

**Comment by xGord** [comment]
I'm using Microsoft.PowerShell.SDK but I got some further about the investigation of this. You are more or less right about the PSModulePath but together with this it seems to me that for Powershell 7 and probably 6 you need to create a runspace. 
For PowerShell 5 this was not necessary and all you had to do was

     using (var powerShell = PowerShell.Create())
     {
           powerShell.AddScript(<yourscript>).Invoke();
     }

But for PowerShell 7 (and probably 6) you need to create a runspace, At least this works for me. 

               using (var runspace = RunspaceFactory.CreateRunspace())
                {
                    runspace.Open();

                    var proxy = runspace.SessionStateProxy;

                    using (var ps = PowerShell.Create())
                    {
                        ps.Runspace = runspace;

                        ps.AddCommand("Get-CimInstance").AddArgument("win32_PnPSignedDriver");
                        
                        var drivers = ps.Invoke().ToList();

                        foreach (var driver in drivers)
                        {
                            Console.WriteLine(driver.Members["Description"].Value);
                        }
                    }
                }

The next thing is to make sure that the modules path is available in the environment variable PSModulePath. But the values in the PSModulePath in windows and when queried in powershell are different. So it wont help to add the path in Windows->Environment Variables->PSModulePath. You need to do it programmatically. 

    var psModulePath = proxy.GetVariable("env:PSModulePath");
    proxy.SetVariable("env:PSModulePath", $@"{psModulePath};C:\Program Files\PowerShell\7-preview\Modules");

It also seems that the PSModulePath is automatically populated with the path your .exe is running from. If you print out 

    Console.WriteLine($"PSModulePath environmentvariable:  {proxy.GetVariable("env:PSModulePath")}");

you will see that this contains (

- C:\Users\username\Documents\PowerShell\Modules;
- C:\Program Files\PowerShell\Modules;
- **c:\users\username\appdata\local\temp\\.net\appname\e2dw1dvd.tkt\Modules;**
- C:\Windows\system32\WindowsPowerShell\v1.0\Modules

So by adding the Modules folder to your application you can make it self-contained without the need for adding a path to the environment variable. Note that this path for me is a temp path cause I'm running it on a remote computer with psexec. 

Probably there is a bug that these variables differ. 

My next issue is that the powershell commands does not work on windows 7.

**Comment by lenoln** [comment]
Hi, I am trying to transcribe this query **"SELECT DeviceId FROM Win32_PnPSignedDriver WHERE DeviceClass = 'DISPLAY'"** to Runspace. I followed the @xGord example and added the parameters. Now I would like to use 'WHERE for DeviceClass', but I can't do it. Can anybody help me?

**Comment by SteveL-MSFT** [comment]
@lenoln not exactly sure what you are asking, but this works:

```powershell
Get-CimInstance -Query "SELECT DeviceId FROM Win32_PnPSignedDriver WHERE DeviceClass = 'DISPLAY'"
```

**Comment by adityapatwardhan** [comment]
Verified with PowerShell SDK version `7.1.1` and it seems to work fine.

*Project file:*
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.1.1" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="7.1.1" />
  </ItemGroup>

</Project>
```

*Code:*
```csharp
class Program
{
    static void Main(string[] args)
    {
        var ps = System.Management.Automation.PowerShell.Create();
        var result = ps.AddCommand("Get-CimInstance").AddArgument("Win32_OperatingSystem").Invoke();

        foreach(dynamic r in result)
        {
            Console.WriteLine($"{r.Name}");
        }
    }
}
```

*Output:*
```
❯ dotnet run
Microsoft Windows 10 Pro|C:\WINDOWS|\Device\Harddisk0\Partition3
```
