### ISSUE TITLE
calling bash -c with powershell incorrectly parses arguments with quotes

### ISSUE THREAD

**Issue by eedwards-sk** [PowerShell/PowerShell#10440]
# Steps to reproduce

```powershell
bash '-c' 'echo "hello world"'
```

# Expected behavior

```none
hello world
```

# Actual behavior

```none
hello
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by eedwards-sk** [comment]
reversing the quotes on the script argument works, by the way:

```
> bash '-c' "echo 'hello world'"
hello world
```

something related to `"` vs `'` parsing?

**Comment by SteveL-MSFT** [comment]
I think https://github.com/PowerShell/PowerShell-RFC/pull/90/files would address this

**Comment by iSazonov** [comment]
Dup? /cc @mklement0

**Comment by mklement0** [comment]
Yes, it's our old friend, #1995, though it may not be obvious:

The broken command line that PowerShell constructs behind the scenes is:

```sh
# Note the lack of escaping of the embedded "
bash -c "echo "Hello World""
```

.NET (correctly) translates that into the following array of verbatim arguments:

`bash`, `-c`, `echo Hello`, `World`

Therefore, `echo`  just sees `Hello` as its argument, and the `World` part is passed as a separate argument that `bash -c` interprets as setting `$0`, which has no visible effect.
