### ISSUE TITLE
Feature Request: Allow writing to output streams from other threads

### ISSUE THREAD

**Issue by replicaJunction** [PowerShell/PowerShell#10452]
# Summary of the new feature/enhancement

As a C# developer, when writing a PowerShell frontend to my .NET Standard or Core libraries, I would like to expose my library's existing logging to PowerShell's output streams - Verbose, Debug, Progress, etc. This is already easy to do with synchronous methods, but any `async` method causes threading problems that PowerShell cannot handle.

Currently, when Cmdlet.Write* is called from a background thread, an error message is thrown:

```
The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread. Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
```

I would like the Cmdlet.Write* methods to allow writing on background threads, and handle marshalling data back to the primary thread as necessary.

# Proposed technical implementation details (optional)

Here is a simple reproduction:

```csharp
public interface ILogger
    {
        void Debug(string message);
        void Info(string message);
        // ...etc
    }

    public class PwshLogger : ILogger
    {
        public Cmdlet Cmdlet { get; }

        public PwshLogger(Cmdlet cmdlet) { this.Cmdlet = cmdlet; }

        // ILogger implementation
        public void Debug(string message) => this.Cmdlet.WriteDebug(message);
        public void Info(string message) => this.Cmdlet.WriteVerbose(message);
    }

    public class Widget
    {
        public ILogger Logger { get; set; }

        public int PerformTest()
        {
            Logger?.Info("Beginning test");
            Thread.Sleep(3000);
            Logger?.Info("Completing test");
            return 0;
        }

        public async Task<int> PerformTestAsync()
        {
            // Contrived example - normally, this would have some awaits in it
            var task = Task.Run(() => {
                Logger?.Info("Beginning async test");
                Thread.Sleep(3000);
                Logger?.Info("Completing async test");
            });
            task.GetAwaiter().GetResult();

            return 0;
        }
    }

    [Cmdlet(VerbsDiagnostic.Test, "Widget")]
    public class TestWidget : PSCmdlet
    {
        private PwshLogger _logger;
        private Widget _widget;

        protected override void BeginProcessing()
        {
            base.BeginProcessing();
            _logger = new PwshLogger(this);
            _widget = new Widget { Logger = _logger };
        }

        protected override void ProcessRecord()
        {
            base.ProcessRecord();

            // Works - run this cmdlet with -Verbose to see output
            _widget.PerformTest();

            // Does not work - throws the error detailed above
            Task.Run(() => _widget.PerformTestAsync()).GetAwaiter().GetResult();
        }
    }
```

Running the command provides this output:

```
PS> ipmo C:\Users\myUser\source\repos\PowerShellTest\PowerShellTest\bin\Debug\PowerShellTest.dll

PS> Test-Widget -Verbose
VERBOSE: Beginning test
VERBOSE: Completing test
Test-Widget : The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread. Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
At line:1 char:1
+ Test-Widget -Verbose
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Test-Widget], PSInvalidOperationException
+ FullyQualifiedErrorId : InvalidOperation,PowerShellTest.TestWidget
```

I have confirmed this behavior on Windows PowerShell 5.1, PowerShell 6.2.2, and PowerShell 7.0.0 preview 3.

I've seen a few [questions](https://stackoverflow.com/questions/38405770/reporting-powershell-progress-from-event-handler) [about](https://stackoverflow.com/questions/12852494/best-way-to-update-cmdlet-progress-from-a-separate-thread) [this](https://stackoverflow.com/questions/40537019/cmdlet-verbose-stream), with various proposed solutions, but they all require the entire structure of the cmdlet class to be built around their solutions.

One could argue that a PowerShell frontend shouldn't be exposing the internal logging from the module, but I'd argue that PowerShell's native output streams are perfect for that sort of thing. The user can see no logging info if they want, or they can pass `-Verbose` and/or `-Debug` if they want detailed logging data displayed.

With the popularity of asynchronous programming, I believe it would be appropriate for PowerShell to handle this case gracefully in order to better integrate with the rest of .NET.

**Comment by BrucePay** [comment]
@replicaJunction I'm not sure I understand the motivation here. It sounds like you want to allow random threads to start writing error/verbose/information messages mixed in with what the user is actually doing. That sound's like a very confusing experience to me. On the other hand, if the goal is to support in-band user notification of asynchronous events, that is more interesting but might lead to a different approach.

**Comment by replicaJunction** [comment]
> On the other hand, if the goal is to support in-band user notification of asynchronous events, that is more interesting but might lead to a different approach.

This is what I'm going for. Basically, I'd like an asynchronous, background thread to be able to call Cmdlet.WriteVerbose() and have the Cmdlet object handle any thread safety concerns transparently.

In my particular use case, I only need one callback at a time, and I block until that background worker is complete anyway. (This is the use case for which I provided a code example in the first post.) These are just implementation details, though.

I understand there would be no guaranteed order if there are multiple callbacks happening on multiple background threads - I see that as a "let the buyer beware" kind of situation. If a user wanted to have multiple background threads going at once, I don't see an issue with the warning that "these are not in a guaranteed order, and they could be confusing."

**Comment by vpopescu** [comment]
The problem with @SeeminglyScience 's solution (if I understand it correctly) is that the events are all queued up until EndProcessing() is called. That is not very useful for something like  a progress bar, no?

Any updates since 2019?

**Comment by vpopescu** [comment]
FWIW, Cmdlet.CommandRuntime.Host.UI.WriteProgress() (and related) are not subject to this cross-thread restriction. I am not sure in which case they would  be counter-indicated.

However these sets of cmdlets don't properly respect switches and preferences (e.g. if you call CommandRuntime.Host.UI.WriteVerboseLine() it will write verbose output even if -Verbose is not specified, and doesn't honor $VerbosePreference.) So no free lunch here either, unless we manually parse the command line switches and env vars for the entire family of functions ourselves.


My use case is that I'd like to register a method to get updates from the library for a long running process, e.g.:

_mydependency.ProgressUpdates +=     ...   {     ...WriteProgress(...) };
_mydependency.DebugMessages +=     ...   {     ...WriteVerbose(...) };

**Comment by vpopescu** [comment]
In my case I need to advance the progress before EndProcessing is called, so I guess I'd need to do it in ProcessRecord, which makes for hard to read boiler plate alongside the cmdlet business logic.


TBH I haven't seen any issues calling CommandRuntime.Host.UI.WriteXXX() directly for my use case, so I could also just call those with proper testing and keeping in mind thread safety. But I don't want to manually add all the command line and env var processing myself.

I am currently trying to derive from Cmdlet and implement your pattern above in a generic way. Will see how clean i can do it.

**Comment by vpopescu** [comment]
Does this look like a good start? Any suggestions?

```cs
      public class MyCmdlet : Cmdlet, IDisposable
    {
        private readonly BlockingCollection<Action> _asyncRequests = new();
        private bool disposedValue;

        protected override void BeginProcessing()
        {
            BeginProcessing(null);
        }

        protected virtual void BeginProcessing(CancellationToken? Token)
        {
            base.BeginProcessing();
            var t = Task.Run(() => Process(Token));
            try
            {
                while (_asyncRequests.TryTake(out Action asyncRequest, -1, Token ?? CancellationToken.None))
                    asyncRequest();
            }
            catch (OperationCanceledException)
            {
            }
        }

        protected virtual void Process(CancellationToken? Token)
        {
            _asyncRequests.CompleteAdding();
        }

        protected override void EndProcessing()
        {
            base.EndProcessing();
        }
      
        public void SendDebug(string text) { _asyncRequests.Add(() => WriteDebug(text)); }
        public void SendVerbose(string text) { _asyncRequests.Add(() => WriteVerbose(text)); }
        public void SendProgress(ProgressRecord record) { _asyncRequests.Add(() => WriteProgress(record)); }
        public void SendError(ErrorRecord record) { _asyncRequests.Add(() => WriteError(record));  }
        public void SendInformation(InformationRecord record)  { _asyncRequests.Add(() => WriteInformation(record)); }
        public void SendInformation(Object messageData, string[] strings) { _asyncRequests.Add(() => WriteInformation(messageData, strings));   }
        public void SendWarning(string text) { _asyncRequests.Add(() => WriteWarning(text));  }
        public void SendObject(Object obj) { _asyncRequests.Add(() => WriteObject(obj));  }
        public void SendObject(Object obj, bool single) { _asyncRequests.Add(() => WriteObject(obj, single)); }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                   _asyncRequests.Dispose();
                }
                disposedValue = true;
            }
        }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
    }

 ```

Usage:
```cs
public class MyCmdltImpl  :  MyCmdlet, ...
{
         protected override void Process(CancellationToken? Token)
        {
            // long running task here...

            base.Process(Token);
         }     
}
  
```
Any additional suggestions? I haven't really tested it thoroughly yet.

**Comment by SeeminglyScience** [comment]
At a glance it looks fine for what is there as far as I can tell.

Part of the problem with trying to tie async into PowerShell generically is that it's a "pit of failure". Meaning that there's a lot of random engine specific knowledge you have to know in order to do it safely. PowerShell is designed from the ground up to store all of it's state in a thread static way. The exception that gets thrown when trying to write from a different thread is actually the *kind* way this manifests.

Even something as simple as calling `this.MyInvocation.MyCommand.Parameters` from a different thread can cause dead locks and/or state corruption. The `AsyncCmdlet` used internally by the `PackageManagement` module [had this issue](https://github.com/PowerShell/PowerShellEditorServices/issues/762) for example.

While a lot of things may end up working fine, a seemingly small change can have huge consequences due to this architecture. Basically, if you're on a different thread, you should just straight up never touch the `PSCmdlet` instance at all unless you have a deep understanding of how the engine works internally.

Personally, I'd like to see a utility class that makes this sort of thread communication easier but I fear tying it into a subclass of `PSCmdlet` may set the wrong expectation. Even if it was it's own standalone class I'd be very hesitant to suggest it be added to SMA.

**Comment by vpopescu** [comment]
I understand your concern, but I think the current behavior is really not flexible enough for certain use cases, and the issue is obscure enough that people will end up shooting themselves in the foot trying to work around it anyway. 

My goal was simple when I started, write a serilog sink that will capture logs from my dependencies and output them to powershell's respective output stream -- since the dependencies were already instrumented with serilog.  Didn't turn out that simple.

Anyway, thanks for your help and insight, hopefully it will be considered for the future.

**Comment by svrooij** [comment]
What a great way to close a 6 year old issue.....

> No body cares about this, so let's make a bot close the issue...

Doing async programming is becoming more and more important! Can someone /reopen this issue?

**Comment by svrooij** [comment]
@replicaJunction here is a solution if you're still looking for it:

1. Create [this](https://github.com/svrooij/ContentPrep/blob/main/src/SvR.ContentPrep.Cmdlet/Internal/ThreadAffinitiveSynchronizationContext.cs) in your project
2. Create a [PowerShellLogger.cs](https://github.com/svrooij/ContentPrep/blob/main/src/SvR.ContentPrep.Cmdlet/Internal/PowerShellLogger.cs)
3. Initialize logger in BeginProcessing `logger = new PowerShellLogger<Packager>(this);`
4. Use your logger in whatever you want logged
5. Run your async code like:

```csharp
ThreadAffinitiveSynchronizationContext.RunSynchronized(async () =>
   await Task.CompletedTask;
);
```
