### ISSUE TITLE
`PSCommandNotFoundSuggestion` generates an error when it fails to find a match.

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10451]
# Steps to reproduce

```powershell
$error.Clear()
gcm Get-InvalidCommand
$error.Count
```

# Expected behavior

```none
1
```

# Actual behavior

```none
2
```

# Root cause

This bug is caused by [this line of code](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/hostifaces/HostUtilities.cs#L72). That was written to assume that matches would be found, but matches are not always found. The script needs to capture the results of the fuzzy search first, and it should only return a string if it found matches.

# Environment data

This was actually done using a build of preview 3. I just haven't updated my tags, but this is using the latest version available at the time of posting.

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2-79-g3943f18c28e9df8369ef17776467c732648747b8
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This is resolved by the new FeedbackProvider  in 7.4
