### ISSUE TITLE
SDK issues on window 7 - can not find a drive with the name 'c'

### ISSUE THREAD

**Issue by xGord** [PowerShell/PowerShell#10456]
I'm running a net core console application with PowerShell SDK version 7.0.0-preview.2. The application is self-contained.
For testing, this application shall start another .exe with the start-process command. 
Running this application on windows 10 works great. The exe opens as expected. 

Running this application on windows 7 does not work. The error (in the streams.error) containes the message "Cannot find drive. A drive with the name 'C' does not exist. 

To reproduce. 
Create a net core 3 console application and add the Microsoft.PowerShell.SDK 7.0.0-preview.3 nuget packages. 
The code running in main: 

                using (var runspace = RunspaceFactory.CreateRunspace())
                {
                    runspace.Open();

                    var proxy = runspace.SessionStateProxy;

                    using (var ps = PowerShell.Create())
                    {
                        ps.Runspace = runspace;

                        ps.AddScript("start-process notepad.exe -wait");
                        
                        ps.Invoke().ToList();

                        foreach(var error in ps.Streams.Error)
                        {
                            Console.WriteLine(error);
                        }
                    }
                }

EDIT: 

I can also see that when using Get-PSDrive from my console application the C drive is not found. Running the same command from both powershell installed with windows 7 and PowerShell 7 the c drive is listed. 
Topwindow is the console application, rest is powershell window in the image below.

![drivenotfound](https://user-images.githubusercontent.com/618919/63930016-c9022200-ca52-11e9-8a0d-9a29be375caf.png)

**Comment by xGord** [comment]
No one knows? 

Are there any requirements for windows framework or anything?  
Any setting for letting powershell access the file system?

**Comment by iSazonov** [comment]
I see FileSystem provider is not initialized. I don't know why. You could share your test project and consult on a dev forum.
