### ISSUE TITLE
Can't install msix

### ISSUE THREAD

**Issue by imba-tjd** [PowerShell/PowerShell#10469]
# Support Question

Hi. I want to try the new `PowerShell-7.0.0-preview.3-win-x64.msix`, but I got a `This app package is not supported for installation by App Installer because it uses certain restricted capabilities.`

How to solve this? I have googled it but get nothing. Thanks.

![图片](https://user-images.githubusercontent.com/24759802/64056400-84e35e80-cbc5-11e9-8ab8-ae340c1cbc47.png)

**Comment by vexx32** [comment]
Yeah, I notified @SteveL-MSFT [on Twitter](https://twitter.com/vexx32/status/1165703138491457541?s=20) when I ran into this.

I had to actually enable Developer Mode in my Security settings on windows 10, and then I also had to install it using `Add-AppxPackage -Path $PathToMsix` before it would let me install it.

**Comment by o-l-a-v** [comment]
It can't be successfully added to Intune either

![image](https://user-images.githubusercontent.com/6450056/65025840-bbe0a080-d937-11e9-9dca-7e3c49793616.png)

![image](https://user-images.githubusercontent.com/6450056/65025887-cd29ad00-d937-11e9-82d5-83a0a98cd6af.png)

Can't find any info in Azure on why it failed.

**Comment by SteveL-MSFT** [comment]
It's not Store signed so you can't just install it.  As @vexx32 noted, you have to be in Developer mode and use the cmdlet to side-load it.  At some point, we will be publishing this to the Store.

**Comment by MicahZoltu** [comment]
I opened an administrative PowerShell (legacy) window and ran `Add-AppxPackage -Path $PathToMsix`.  This resulted in a progress bar that filled up and no visible errors.  However, when I launch PowerShell (via start button and typing PowerShell) I still get the old version.

**Comment by imba-tjd** [comment]
@MicahZoltu it's `pwsh`

**Comment by Nirmal4G** [comment]
> I opened an administrative PowerShell (legacy) window and ran Add-AppxPackage -Path $PathToMsix. This resulted in a progress bar that filled up and no visible errors. However, when I launch PowerShell (via start button and typing PowerShell) I still get the old version.

Same for me.

The solution is to make sure, the `PATH` env variable has priority for `%LocalAppData%\Microsoft\WindowsApps`

**Comment by SteveL-MSFT** [comment]
I think it's best to just have the MSI or MSIX installed, not both.

**Comment by jonasg-gc** [comment]
Hey everyone, just to add to all this:
I got the following error: 
`Cannot find path 'C:\Users\Jonas\downloads\PowerShell-7.1.0-preview.2-win-x64.msixw' because it does not exist.`

Turns out the filename was too long.  I renamed it to **PowerShell-7.msix** and away we go...

**Comment by o-l-a-v** [comment]
> Hey everyone, just to add to all this:
> When running `Add-AppxPackage -Path $PathToMsix` from PowerShell 5,
> I got the following error:
> `Cannot find path 'C:\Users\Jonas\downloads\PowerShell-7.1.0-preview.2-win-x64.msixw' because it does not exist.`
> 
> Turns out the filename was too long. I renamed it to **PowerShell-7.msix** and away we go...

Most likely due to the typo in your $PathToMsix variable (see the 'w' on the end).

**Comment by wx-yz** [comment]
I'm seeing the same issue when trying to install 7.1.3.0 msix (PowerShell-7.1.0-preview.3-win-x64) on Windows 10.

![image](https://user-images.githubusercontent.com/57770159/82373744-dc835d80-99d2-11ea-8471-8731e1a26163.png)

**Comment by rbeesley** [comment]
@wx-yz, that seems to be as expected. The thread above points out that this is not signed from the Store yet and as such it must be sideloaded as a developer tool if you are using the MSIX. When they finally release PowerShell to the store, I suspect in a way similar to how Python is available, then it will install this way. Until then you will have to sideload, use `dotnet.exe tools install powershell -g`, or the MSI. Personally I had been using the global dotnet install method and just uninstalled it to try the MSIX installer... I'm not sure I see the advantage of using MSIX until the Store is managing the updates. I'm debating my options.

**Comment by wx-yz** [comment]
Thanks @rbeesley, I did not know that. I ended up using winget. Starting to like that a lot.

**Comment by rbeesley** [comment]
@wx-yz, oh, you're right. I hadn't considered Chocolatey, Scoop, or WinGet... I went with sideloading the MSIX just to see what complications the additional restrictions being containerized will bring, but this does seem like the perfect opportunity to kick the WinGet tires.
