### ISSUE TITLE
Proxy Authentication using logged on network credentials, works fine in Windows PowerShell

### ISSUE THREAD

**Issue by SwarfegaGit** [PowerShell/PowerShell#10460]
# Steps to reproduce

```powershell
[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials

(Invoke-WebRequest -Uri 'https://google.com').StatusCode
```

# Expected behavior

```powershell
200
```

# Actual behavior

```none
Error message being thrown from network proxy

Authentication Required
You must be authenticated to access this URL.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This works fine on the same machine using Windows PowerShell but doesn't work in PowerShell 6 or above.

**Comment by TomPeters** [comment]
I'm encountering what I think is the same problem on `6.2.2`.

I have a system proxy configured, and I am trying to specify custom credentials for this proxy using the following snippet
```
$systemProxy = [System.Net.WebRequest]::GetSystemWebProxy()
$systemProxy.Credentials = New-Object System.Net.NetworkCredential($proxyUsername, $proxyPassword)
[System.Net.WebRequest]::DefaultWebProxy = $systemProxy
```

On Windows PowerShell, `Invoke-WebRequest` successfully uses this configuration. On PowerShell Core, I receive a `407` response from the proxy server.

Are there any workarounds or alternative ways of configuring an invocation of `Invoke-WebRequest` to use the system proxy with credentials? I can't set the `-Proxy` parameter on `Invoke-WebRequest` because this is a system proxy, so I don't know the literal proxy URL upfront.

**Comment by mikes-gh** [comment]
Happy to report Powershell 7 preview 5 solves this issue for me.
I don't need anything in $PROFILE either it just works 😃

**Comment by garethmorris78** [comment]
I also have the same issue. Powershell Core is not working via a forward proxy with an authentication layer ( any attempt use commandlets that require internet access returns a 407; so Invoke-WebRequest, Find-Module, Install-Module etc ). Windows Powershell works fine using the Cred Cache:

```powershell
(New-Object System.Net.WebClient).Proxy.Credentials = `
  [System.Net.CredentialCache]::DefaultNetworkCredentials
```

Tried on Powershell Core 6.2.3 and 7.0.0 rc2 on Windows 10 Build 1909.

**Comment by ipat8** [comment]
Have there been any updates to this? I can confirm this is still an issue on PS7 and LTSB.

**Comment by michaelelleby** [comment]
This is still an issue with PowerShell 7.1
Have set both [System.Net.WebRequest]::DefaultWebProxy, $env:HTTP_PROXY, and $env:HTTPS_PROXY and I get HTTP status code 407 when using Invoke-RestMethod
```
PS C:\Git> Invoke-RestMethod https://dr.dk
Invoke-RestMethod:
Notification: Proxy Authorization Required
```
The same configuration works perfectly with Windows PowerShell 5.1

This is Windows 10 version 1909

**Comment by michaelelleby** [comment]
> 
> # Steps to reproduce
> 
> ```powershell
> [System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
> 
> (Invoke-WebRequest -Uri 'https://google.com').StatusCode
> ```
> 
> # Expected behavior
> 
> ```powershell
> 200
> ```
> 
> # Actual behavior
> 
> ```
> Error message being thrown from network proxy
> 
> Authentication Required
> You must be authenticated to access this URL.
> ```
> 
> # Environment data
> 
> ```
> Name                           Value
> ----                           -----
> PSVersion                      7.0.0-preview.3
> PSEdition                      Core
> GitCommitId                    7.0.0-preview.3
> OS                             Microsoft Windows 10.0.17763
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
> 
> This works fine on the same machine using Windows PowerShell but doesn't work in PowerShell 6 or above.

This seems to work in PowerShell 7.1

**Comment by iSazonov** [comment]
It comes from .Net.

**Comment by gabrielmccoll** [comment]
What does that mean sorry?

**Comment by mikes-gh** [comment]
I have this issue too closing as it comes from .Net is not very helpful 😦

**Comment by mikes-gh** [comment]
@gabrielmccoll 
I tried with 7.1.1
```
PS C:\Users\mikes> [System.Net.WebRequest]::DefaultWebProxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials
PS C:\Users\mikes>
PS C:\Users\mikes> (Invoke-WebRequest -Uri 'https://google.com').StatusCode
200

```
It now works for me 🎉

**Comment by gabrielmccoll** [comment]
Dang. I have 7.1 and can't get .1.1 until they package it haha. 
Thanks for coming back
