### ISSUE TITLE
How to add records in nisNetgroup Triple using Syntax IA5-String

### ISSUE THREAD

**Issue by bmonteiro** [PowerShell/PowerShell#10472]
How to add records in nisNetgroup Triple using Syntax IA5-String

Set-ADObject -Identity "OU=A,OU=B,OU=netgroup,OU=BLA,DC=BLA,DC=com" -Add @{'nisNetgroupTriple'="(,bla@domain.com,DOMAIN.COM)"} 

This is not working. How to correctly add a record ?

Easy to create :

New-ADObject -Name MYNAME -Type "nisNetgroup" -ProtectedFromAccidentalDeletion $Trueb -Path "OU=A,OU=B,OU=netgroup,OU=BLA,DC=BLA,DC=com" -OtherAttributes @{'nisNetgroupTriple'="(,bla@domain.com,DOMAIN.COM)"}
 
But the update of records is not documented.

**Comment by iSazonov** [comment]
@bmonteiro The repo is only for PowerShell Core developers. Please use forums and other resources for help.
In second command you create MYNAME object with type nisNetgroup but in first command you are trying change OU object not MYNAME.
