### ISSUE TITLE
Invoke-Expression and Invoke-Command: redirecting the error stream to the success stream discards error output

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10476]
Note that the symptom only occurs when redirecting to _another stream_, either via `2>&1` or `*>&1`.

By contrast, redirecting to a _file_ works as expected.

# Steps to reproduce

Run the following Pester test:

```powershell
# Create a string with a command that writes to all streams.
$cmd = '1; write-error 2; write-warning 3; write-verbose -vb 4; write-debug -debug 5; write-information -infa continue 6'
# Make sure that all streams can be directed to the success output stream (1).
(Invoke-Expression $cmd *>&1).Count | Should -Be 6
```

Note: the same applies to (at least local use of) `Invoke-Command`:
`(Invoke-Command ([scriptblock]::create($cmd)) *>&1).Count | Should -Be 6`

The **workaround** is enclosure in `(...)`, but it comes at the expense of losing streaming behavior.
`( (Invoke-Expression $cmd) *>&1).Count | Should -Be 6`

# Expected behavior

The test should pass - all 6 streams should show up in the success output stream.

# Actual behavior

```none
Expected 6, but got 5.
```

That is, the error output was _quietly discarded_, as you 'll see if you run the command inside `(...)` in isolation

# Environment data

```none
PowerShell Core 7.0.0-preview.3
Windows PowerShell v5.1.18362.145 on Microsoft Windows 10 Pro (64-bit; Version 1903, OS Build: 18362.295)
```

**Comment by bad-samaritan** [comment]
@mklement0,  thanks for posting this issue.
I was pulling my hair off wondering what I did wrong.

Another simple repro steps:
```
PS> Invoke-Expression "cmd.exe /c echo 123"
123

PS> Invoke-Expression "cmd.exe /c nonexistingcommand 123"
'nonexistingcommand' is not recognized as an internal or external command,
operable program or batch file.

PS> Invoke-Expression "cmd.exe /c echo 123" *>&1
123

PS> Invoke-Expression "cmd.exe /c nonexistingcommand 123" *>&1

PS>
```
Where did last command's output go?

Workaround I'm currently using:
```
PS > . "cmd.exe" "/c nonexistingcommand 123" *>&1
cmd.exe : 'nonexistingcommand' is not recognized as an internal or external command,
At line:1 char:1
+ . "cmd.exe" "/c nonexistingcommand 123" *>&1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('nonexistingcom...ternal command,:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

operable program or batch file.
```
It's not exactly the same and it makes automation harder (because you have to separate command and arguments) but it's something...

**Comment by PHeonix25** [comment]
Just ran into this myself wondering where `Write-Error` output went!? Thanks for making the issue!

My $PSVersionTable for reference:
```Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0```

**Comment by mklement0** [comment]
Thanks for confirming, @PHeonix25 - the bug is also still in the latest preview, PowerShell Core 7.2.0-preview.2.

@bad-samaritan, a simpler workaround is to embed the redirection in the command string:

```powershell
$cmd  = "cmd.exe /c nonexistingcommand 123"

Invoke-Expression ". { $cmd } 2>&1"
```

(Also, for commands that you construct in memory, for later execution, it's better to use script blocks:
```powershell
$cmd  = { cmd.exe /c nonexistingcommand 123 }

. $cmd 2>&1
```
)

**Comment by onlyann** [comment]
I experience this issue on Powershell 7.1

@mklement0  The workaround you suggest doesn't work for me. As soon as try to redirect the error stream somewhere, nothing happens
```
(& nonexistingcommand 123) 2>&1 >> logs.txt
# logs.txt is empty

$cmd  = { cmd.exe /c nonexistingcommand 123 }

. $cmd 2>&1 >> logs.txt
#  log is still empty
```

How can I capture errors from commands ran by Powershell Core?

There has to be a way, I can't think such a core issue would be open for over a year without workaround.

**Comment by mklement0** [comment]
@onlyann: the workaround doesn't apply to  a _nonexistent_ command, because trying to invoke such a command triggers a statement-_terminating_ error, which requires `try` / `catch` to handle (as opposed to an _existing_ command that is an external program that _can be executed_ but happens to write to stderr during execution):

```
& { try { nonexistingcommand 123 } catch { write-error $_ } } 2>&1 >> logs.txt
```

For an overview of PowerShell's surprisingly complex error handling, see [this GitHub docs issue](https://github.com/PowerShell/PowerShell-Docs/issues/1583).

> such a core issue would be open for over a year without workaround.

To be clear: the issue described in the OP isn't a core issue, given that [`Invoke-Expression` should generally be avoided](https://blogs.msdn.microsoft.com/powershell/2011/06/03/invoke-expression-considered-harmful/), and that [legitimate uses are rare](https://stackoverflow.com/a/51252636/45375).

**Comment by onlyann** [comment]
To give some context of what lead me here is that I was attempting to capture the error stream from running a npm command (`npm run task ...`) from PowerShell Core.

I still haven't found a way to do that and I have been assuming, from this issue, that error redirection from external commands is sort of broken in Powershell Core.

However, from your answer @mklement0 , it sounds like there is a way to do it that doesn't involve Invoke-Expression. 
Would you please share how to do that?

**Comment by mklement0** [comment]
Redirection of stderr from external programs with `2>` in _direct invocation_ works fine, it's only combining `>2` with `Invoke-Expression` that is the problem.

The command in the previous comment, based on your own command, shows how to _merge stdout and stderr_ and append the results to a file; to redirect just stderr, use `2>>logs.txt`

If you're willing to assume that `npm` is present, you don't need the `try` / `catch` statement and the script block, and can use something like `npm run task ... 2>&1 >>logs.txt` or  `npm run task ... 2>>logs.txt` directly.

**Comment by onlyann** [comment]
@mklement0  Somehow, it wasn't working in a PowerShell Core console but was fine on Windows PowerShell. Now that I try to reproduce, it works in both. I must have been doing something stupid... 
Thank you @mklement0 for your help!
