### ISSUE TITLE
Connect-AzureAD Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly

### ISSUE THREAD

**Issue by aollivierre** [PowerShell/PowerShell#10473]
# Steps to reproduce

```powershell

after importing AzureAd module and Calling the Connect-AzureAd Cmdlet
an interactive form opens to supply credentials and provide MFA authentication 

Install-Module -Name "AzureAD" -Verbose -Force -AllowClobber
Import-Module -Name "AzureAD" -Verbose -Force
Get-Module -Name "AzureAD"-ListAvailable | Select-object Name, Version
Connect-AzureAD

```

# Expected behavior

```none

The Connect-AzureAd Cmdlet should continue successfully and establish a connection with Azure AD


```

# Actual behavior

```none

connect-azuread : One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
At line:1 char:1
+ connect-azuread
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AadAuthenticationFailedException
+ FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

connect-azuread : One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
At line:1 char:1
+ connect-azuread
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AggregateException
+ FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

connect-azuread : Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
At line:1 char:1
+ connect-azuread
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], TypeLoadException
+ FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

connect-azuread : One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
At line:1 char:1
+ connect-azuread
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-AzureAD], AadAuthenticationFailedException
+ FullyQualifiedErrorId : Microsoft.Open.Azure.AD.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@aollivierre Please move the issue to Azure feedback site.
Perhaps it is here https://feedback.azure.com/forums/169401-azure-active-directory

**Comment by toddwseattle** [comment]
I don't get why this is moved to the azure feedback site.  I am encountering this exact same error on the 7-Preview.  Here is my version info:
````powershell
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

**Comment by iSazonov** [comment]
@toddwseattle We need a simply repo to discover a root of the issue. Azure site is good place to start.

/cc @SteveL-MSFT

**Comment by toddwseattle** [comment]
@SteveL-MSFT  Same problem; apparently I'm on preview.5 now.  Repro Steps
````powershell
C:\Windows\System32>Update-Module -Name AzureAD
C:\Windows\System32> Import-Module -Name AzureAD
C:\Windows\System32> Get-Module -Name "AzureAD" -ListAvailable | Select-Object Name,Version

Name    Version
----    -------
AzureAD 2.0.2.61
AzureAD 2.0.2.52

C:\Windows\System32> Connect-AzureAD
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
````
Here is my version info right now:
````powershell
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

What else do you need?

**Comment by SteveL-MSFT** [comment]
@toddwseattle please see https://github.com/PowerShell/PowerShell/issues/11070

**Comment by O365scripts** [comment]
I was having issues connecting to the SFB module as well when using the v7 but was unable to connect properly after switching my VS Code's shell to the regular 5.1 and was able to login properly to the service.

**Comment by swinster** [comment]
Exactly the same behaviours as @O365scripts

**Comment by swinster** [comment]
Noted this to when attempting to connect to O365. Posted a question to https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell, and the related GitHub, but as noted in that issue, is looks like PS Core is not support for AzureAD or the Msol name CmdLets.

I guess there is not much that can by done until Azure Az catches up.

**Comment by jianwshen** [comment]
Got error when run command: 
>Connect-AzureAD 
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Screen shot is attached.

**Comment by jianwshen** [comment]
This happens when I use command
$Credential = Get-Credential
Connect-AzureAD -Credential $Credential

**Comment by awgeorge** [comment]
I'm getting this error too - fresh install of PowerShell on osx.

**Comment by fabio770** [comment]
> 
> 
> This happens when I use command
> $Credential = Get-Credential
> Connect-AzureAD -Credential $Credential

I am having the same problem when running this command

**Comment by kzarms** [comment]
Same problem.
Tried with AzureAD and AzureADPreview

```
get-module -ListAvailable Azure*

    Directory: C:\Users\user\OneDrive\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     2.0.2.85              AzureADPreview                      Desk

import-module AzureADPreview
Connect-AzureAD
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PowerShell/issues/10473#issuecomment-554460230

**Comment by ohadschn** [comment]
In short, it's not supported in .NET Core, and therefore not in PowerShell Core (7.X).

**Comment by kzarms** [comment]
Thanks,
New [Microsoft Graph](https://developer.microsoft.com/en-us/microsoft-365/blogs/microsoft-graph-powershell-preview-now-on-powershell-gallery/) PS module is looking very promising.


Hope, documentation will be ready soon and we continue with user creation process. Right now for the New-MgUser we have this :)

```
Get-Help New-MgUser -Examples

NAME
    New-MgUser

SYNOPSIS
    Add new entity to users


    -------------------------- EXAMPLE 1 --------------------------

    PS C:\>{{ Add code here }}

    {{ Add output here }}




    -------------------------- EXAMPLE 2 --------------------------

    PS C:\>{{ Add code here }}

    {{ Add output here }}
```

**Comment by ohadschn** [comment]
Note that partial support is available using the following preview package: https://www.poshtestgallery.com/packages/AzureAD.Standard.Preview/0.1.599.7

```powershell
Register-PackageSource -Name PoshTestGallery -Location https://www.poshtestgallery.com/api/v2/ -ProviderName PowerShellGet
Install-Module -Name AzureAD.Standard.Preview -Repository PoshTestGallery
```

**Comment by hmahajanHM** [comment]
@ohadschn I tried your steps but issue is still not resolved.  My machine is Windows 10. t already had Powershell 5.1. But today I installed Core based 7.x latest release of Powershell. I am using 7.x ISE of PS to run AZ module command and so it asked for Azure login and faced same error.

**Comment by kzarms** [comment]
Hi, @hmahajanHM 

Try this

```
Install-Module Microsoft.Graph
Connect-Graph
Get-MgUser | select -First 5
```
It works in my PS7.0 There is no instruction how to create a new user, but getting existing is fine.

**Comment by ohadschn** [comment]
@hmahajanHM most likely you already had incorrect PS assemblies loaded onto the ISE process. I suggest you start a new regular PowerShell terminal process (Start Menu -> PowerShell) and try again.

**Comment by sirisha-k83** [comment]
> @ohadschn I tried your steps but issue is still not resolved. My machine is Windows 10. t already had Powershell 5.1. But today I installed Core based 7.x latest release of Powershell. I am using 7.x ISE of PS to run AZ module command and so it asked for Azure login and faced same error.

Hi, I am having the same issue and I am installing on 64-bit.Did you find the solution?

**Comment by JeretSB** [comment]
As posted above I have the same thing happening. 7.x power-shell core causes the same error to take place.

Using power-shell 5.1 things seem to work just fine.

**Comment by TimHandy** [comment]
Same as what JeretSB said.     7.0.2. fails.   5.1 works.

**Comment by FGRoy** [comment]
Use: Import-Module  AzureAD -UseWindowsPowerShell 

Until Azure Active Directory product group makes the AzureAD module compatible with PowerShell 7, we need to use the Windows PowerShell Compatibility feature. You can find more details at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7

Thanks to @alexandair 

[about_Windows_PowerShell_Compatibility - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility)

**Comment by JustinGrote** [comment]
@SteveL-MSFT is there a place the AzureAD team has a uservoice or something so we can ask them for the code change described in https://github.com/dotnet/runtime/issues/25044?

**Comment by SteveL-MSFT** [comment]
@JustinGrote couldn't find one I would suggest starting in Azure PowerShell repo and maybe they can help redirect

**Comment by joepaulk** [comment]
Ha ha, i know my comments are not helpful, but this is how i look at it.
**Microsoft wants us to buy windows laptop so we can use managing AzureAD using powershell.**
Their team doesn't even want to support powershell core :(.

**Comment by mpowrie** [comment]
I'm still getting this problem in Powershell 7.1.0 on Windows 10 with a fresh install of AzureAD 2.0.2.128
See screenshot:

![image](https://user-images.githubusercontent.com/323814/100033867-1a17e600-2e4f-11eb-96a6-f93327e12485.png)

**Comment by macbombastic** [comment]
I have the same issue as @mpowrie - please help.

**Comment by MaximoTrinidad** [comment]
@macbombastic and @mpowrie 

Unfortunately, this module is not part of this repository and it's not open source.  It's owned by another team in Microsoft.

At the same time, this module will not work (yet) in PowerShell 7.x as it was built to run in Windows PowerShell: "... _The Azure AD Module is supported on the following Windows operating systems with the default version of Microsoft .NET Framework and Windows PowerShell: Windows 8.1, Windows 8, Windows 7, Windows Server 2012 R2, Windows Server 2012, or Windows Server 2008 R2_... ."

In PowerShell 7.x, if you do a "Get-Module -list AzureAD", the column "PSEdition" = "Desk" (not "Core/Desk"). This means the module runs only in Windows PowerShell.

![WPoshAzureAD_01_2020-11-30_13-39-10](https://user-images.githubusercontent.com/19892435/100650581-264de880-3312-11eb-88f0-32f8ce6e1db9.png)

If you go to the PowerShellGallery, look for the "Contact Owner" option to send an email message.
I know nobody likes this option but... "This is the way!".

**Comment by joepaulk** [comment]
@macbombastic @mpowrie 
> I have the same issue as @mpowrie - please help.

you can try the how i came across the same issue, which i have mentioned in this link,

https://github.com/PowerShell/PowerShell/issues/10473#issuecomment-721442981

**Comment by et01267** [comment]
There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.

**Comment by JustinGrote** [comment]
@et01267 now now don't hold back, tell us how you really feel :)

**Comment by et01267** [comment]
Saint Peter, if it please the court: Exhibit A for the prosecution: $true

**Comment by DEberhardt** [comment]
it persists...

```
❯ Get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.0.2.129             AzureAdPreview                      {Add-AzureADAdministrativeUnitMember, Add-AzureAD…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Binary     1.1.10     preview    MicrosoftTeams                      {Add-TeamChannelUser, Add-TeamsAppInstallation, A…
Script     2.0.496               oh-my-posh                          {Get-BatteryInfo, Get-ComputerName, Get-Formatted…
Script     0.7.3                 posh-git                            {Add-PoshGitToProfile, Add-SshKey, Enable-GitColo…
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Fin…
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
Script     7.0.0.0               SkypeOnlineConnector                {Get-CsOnlinePowerShellAccessInformation, Get-CsO…

❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

❯ Connect-AzureaD -AccountId a98001157_adm@atlascopco.com
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by DEberhardt** [comment]
From this reddit [here](https://www.reddit.com/r/PowerShell/comments/iv7cjy/connectazuread_returns_sha256cng_error_in_ps_703/), I could glean some insight:

> Windows Powershell 5.1 and Powershell Core 7 does not use the same .Net framework.
> 
> Most likely the AD module was written using the full .Net framkork for windows.
> So when you try to run i on PS 7 with the .Net Core framework it's looking for namespaces that no longer are there or named differently.
> 
> If you have 5.1 on the same box you are running PS 7 on, you can load the AD module with import-module -UseWindowsPowerShell. This will load the module in 5.1 but make it usable in 7.


Testing with `Connect-AzureAd` was successful (connection established).
`Connect-MicrosoftTeams` as well as (my) `Connect-SkypeOnline` (which calls `New-CsOnlineSession`) was unsuccessful.

**Comment by JustinGrote** [comment]
For reference, there is an AzureAD.Preview.Standard that exists that works with .NET standard and thus Powershell 7, however it's a few versions behind and doesn't contain the latest features.
https://www.poshtestgallery.com/packages/AzureAD.Standard.Preview/0.1.599.7

**Comment by alexandair** [comment]
AzureAD.Preview.Standard module should not be used in production outside of the Azure Cloud Shell.
Microsoft supports it only in that environment.

**Comment by DEberhardt** [comment]
interesting. What is the planned support path for AzureAd and PowerShell 7 then?
Will PS7 always be a branch or will the Modules be made compatible with the .NET Core used in PS7 (if possible)?

**Comment by JustinGrote** [comment]
@DEberhardt the AzureAD team is a black box, they haven't made any announcements of any kind regarding that as far as I'm aware.

Currently the only supported path is the Microsoft Graph Powershell SDK. Microsoft Graph covers about 90% of what the deprecated AzureAD Graph API covered. These commands are not as "friendly" as AzureAD though, hence the SDK label. A new AzureAD module could theoretically be built using the SDK as a base, but again, nothing's been announced that I'm aware of.

There are also some AD commands in Az.Resources which, while using the deprecated AzureAD API, do work with PS7. It's not a full coverage but is good enough for some use cases.

**Comment by realolap** [comment]
> There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.

Give me slower development and more stabillity any time.

**Comment by mavaddat** [comment]
Install `AzureAD` in PowerShell 5.1.■■■■.■■■■ then, in PowerShell 7.■.■, import the module using `Import-Module AzureAD -UseWindowsPowerShell` 

```pwsh
$ Import-Module AzureAD -UseWindowsPowerShell

WARNING: Module AzureAD is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
```

You may even get an error like this:

```pwsh
Import-Module: Failure from remote command: Import-Module -Name 'Azure': The specified module 'Azure.Storage' with version '4.3.0' was not loaded because no valid module file was found in any module directory.
```

However, it does not prevent the module cmdlets from being used in PowerShell preview.

**Comment by arendkolk** [comment]
Having the same issue. I am using Ubuntu and Powershell from a docker container. What do you suggest?

**Comment by JustinGrote** [comment]
@arendkolk AzureAD is not a supported module outside of Windows currently, period. You can get the AzureAD.Standard.Preview module which does work on linux but that is unsupported outside of cloudshell.

You should be using the Microsoft Graph Powershell SDK for Azure AD operations in Powershell 7. A subset of functionality is also availabile in the Az.Resources module however that still uses the legacy AzAD graph api rather than Microsoft Graph.

There is no roadmap for AzureAD moving to Powershell 7 (yet, the VP for the team has promised a blog article roadmap)

**Comment by peter-bertok** [comment]
@JustinGrote: Am I reading that right? It's 2021, PowerShell Core has now been out for over 3 years, and yet the Azure AD team has no plan to support it?

Which of these two products is unsupported by Microsoft? AzureAD or PowerShell Core?

Because if these two technologies do not work together seamlessly, then at least one of them is _effectively_ unsupported and should not be used by anyone going forward.

Which do you recommend customers should drop?

**Comment by JustinGrote** [comment]
I don't work for Microsoft, but I'd recommend running azureAD in PS7 using the 5.1 compatability import, and look into MS graph powershell sdk or az.resources if you need linux support, and await the new blog article the PM said he would write in regards to the azureAD future roadmap. 

Also it's just PowerShell 7 now, the "core" moniker was dropped.

**Comment by SteveL-MSFT** [comment]
Complaints about AAD PowerShell module needs to go to that team.  Best I can find for a repo is https://github.com/AzureAD/azure-activedirectory-powershell since AAD module itself isn't Open Source.  As @JustinGrote politely noted, Microsoft Graph PowerShell is intended to replace AAD module.  Feedback on that should be to their repo https://github.com/microsoftgraph/msgraph-sdk-powershell.

**Comment by GregWoods** [comment]
> There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.

The fact that in 2022 there are still 2 incompatible branches of Powershell is inexcusable. Powershell had so much promise, but with so many separate teams pulling it in different directions, each blaming the other for incompatibilities is just bad leadership.

**Comment by uhFuzu** [comment]
> > There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.
> 
> The fact that in 2022 there are still 2 incompatible branches of Powershell is inexcusable. Powershell had so much promise, but with so many separate teams pulling it in different directions, each blaming the other for incompatibilities is just bad leadership.

I think more the fact this particular issue has dragged on for over 3 years is more shameful.

**Comment by izkasi** [comment]
> > > There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.
> > 
> > 
> > The fact that in 2022 there are still 2 incompatible branches of Powershell is inexcusable. Powershell had so much promise, but with so many separate teams pulling it in different directions, each blaming the other for incompatibilities is just bad leadership.
> 
> I think more the fact this particular issue has dragged on for over 3 years is more shameful.

So if I want to work with Azure AD PIM (Privileged Access Groups) and do some basic assignments I have to either use some undocumented APIs or run 2 incompatible versions of Powershell and the corresponding modules written for it. 
Can't make this up!

**Comment by JustinGrote** [comment]
> > > > There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.
> > > 
> > > 
> > > The fact that in 2022 there are still 2 incompatible branches of Powershell is inexcusable. Powershell had so much promise, but with so many separate teams pulling it in different directions, each blaming the other for incompatibilities is just bad leadership.
> > 
> > 
> > I think more the fact this particular issue has dragged on for over 3 years is more shameful.
> 
> So if I want to work with Azure AD PIM (Privileged Access Groups) and do some basic assignments I have to either use some undocumented APIs or run 2 incompatible versions of Powershell and the corresponding modules written for it. Can't make this up!

Don't think this is true. The Az module and Mg modules both have supported v3 APIs for PIM, and I use them often.

**Comment by izkasi** [comment]
> > > > > There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.
> > > > 
> > > > 
> > > > The fact that in 2022 there are still 2 incompatible branches of Powershell is inexcusable. Powershell had so much promise, but with so many separate teams pulling it in different directions, each blaming the other for incompatibilities is just bad leadership.
> > > 
> > > 
> > > I think more the fact this particular issue has dragged on for over 3 years is more shameful.
> > 
> > 
> > So if I want to work with Azure AD PIM (Privileged Access Groups) and do some basic assignments I have to either use some undocumented APIs or run 2 incompatible versions of Powershell and the corresponding modules written for it. Can't make this up!
> 
> Don't think this is true. The Az module and Mg modules both have supported v3 APIs for PIM, and I use them often.

[In the current iteration, there is no API support for PIM alerts and privileged access groups.](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-apis#current-iteration--azure-ad-roles-in-microsoft-graph-and-azure-resource-roles-in-azure-resource-**manager**:~:text=In%20the%20current%20iteration%2C%20there%20is%20no%20API%20support%20for%20PIM%20alerts%20and%20privileged%20access%20groups.)
Maybe I am missing something here, could you point me to a working example?

**Comment by DEberhardt** [comment]
AFAIK, Functionality was transported as-is from AzureAD to Graph, meaning Privileged Access Groups cannot be targeted via PowerShell right now. Happy to be proven wrong as I haven't used Graph yet as I am still stuck using AzureAd in my environment

**Comment by JustinGrote** [comment]
I didn't see your need for access groups in parens, I skipped over it and assumed you were defining PIM :).

Privileged Access Groups are a `preview` feature `not for production` (and I hope you aren't using them that way), and there's no API support for that `at all`, so why do you expect these modules (which are just a conduit to the API) to support them? I think you're asking for more than is reasonable.

**Comment by toddalbers** [comment]
> > > > > > There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell.
> > > > > 
> > > > > 
> > > > > The fact that in 2022 there are still 2 incompatible branches of Powershell is inexcusable. Powershell had so much promise, but with so many separate teams pulling it in different directions, each blaming the other for incompatibilities is just bad leadership.
> > > > 
> > > > 
> > > > I think more the fact this particular issue has dragged on for over 3 years is more shameful.
> > > 
> > > 
> > > So if I want to work with Azure AD PIM (Privileged Access Groups) and do some basic assignments I have to either use some undocumented APIs or run 2 incompatible versions of Powershell and the corresponding modules written for it. Can't make this up!
> > 
> > 
> > Don't think this is true. The Az module and Mg modules both have supported v3 APIs for PIM, and I use them often.
> 
> [In the current iteration, there is no API support for PIM alerts and privileged access groups.](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-apis#current-iteration--azure-ad-roles-in-microsoft-graph-and-azure-resource-roles-in-azure-resource-**manager**:~:text=In%20the%20current%20iteration%2C%20there%20is%20no%20API%20support%20for%20PIM%20alerts%20and%20privileged%20access%20groups.) Maybe I am missing something here, could you point me to a working example?

"_There is a special place in hell reserved for everyone associated with this dumpster fire known as PowerShell._"

And it ain't just PowerShell.

I am having this same problem.  I don't know if Microsoft gets it or not.  
The issue isn't that Microsoft needs make changes.  The issue is that Microsoft repeatedly provides new functionality and then quickly turns around and breaks your code by not only making a change but deprecating things your code has relied on.

There is zero consideration for breaking your code on you.  And, newsflash, not all of us are able to keep up with Microsoft's publications about coming changes (not that all breaking changes are even published ahead of time)

Now, I have a bunch of stuff to fix.  Getting tired of having to fix things that Microsoft breaks for us.

AWS and Python are looking more and more attractive.

**Comment by uhFuzu** [comment]
Nice to know Microsoft are so profit driven they're willing to totally
screw long time customers for a critical mass of Azure users. What a joke
of a corporation. My advise. Go with AWS. Azure is years away from being
anything like it and is teeming with incompatibility that I've never had on
AWS as an Architect. Python/java and AWS is indeed the way forward

**Comment by vazome** [comment]
Literally unsuable

**Comment by i-windows** [comment]
still persists...still...since 2019

**Comment by JustinGrote** [comment]
@i-windows Azure AD PowerShell is deprecated, this will not be fixed, you should move to Graph.
https://learn.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-2.0

**Comment by Sumtin** [comment]
@JustinGrote do you know if there's an equivalent function in the Graph module for searching by ObjectId without knowing the type of object?  Looking for equivalent to `Get-AzureADObjectByObjectId`.  `Get-MgUser -ObjectId ***` doesn't work on non-user objects.

**Comment by JustinGrote** [comment]
> @JustinGrote do you know if there's an equivalent function in the Graph module for searching by ObjectId without knowing the type of object? Looking for equivalent to `Get-AzureADObjectByObjectId`. `Get-MgUser -ObjectId ***` doesn't work on non-user objects.

Only for directory objects, not other types of objects.
https://learn.microsoft.com/en-us/graph/api/directoryobject-get?view=graph-rest-1.0&tabs=powershell

For further assistance consider https://aka.ms/PSDiscord, there is a #Powershell-help channel there.

**Comment by Sumtin** [comment]
> Only for directory objects, not other types of objects. https://learn.microsoft.com/en-us/graph/api/directoryobject-get?view=graph-rest-1.0&tabs=powershell

This worked, but I needed to add the `-Debug` flag to the PS cmdlet, otherwise it just returns the `Id` and `DeletedDateTime` columns.. Not super helpful out of the box.

**Comment by ChiefW0mbat505** [comment]
![image](https://user-images.githubusercontent.com/76570872/230499190-423f7fac-9776-4944-bc31-d86d5e4c8b5f.png)
I am fine with been deprecated, I am fine with using Graph but please if that is the case  do not post that as the command in your own portal

**Comment by JustinGrote** [comment]
> ![image](https://user-images.githubusercontent.com/76570872/230499190-423f7fac-9776-4944-bc31-d86d5e4c8b5f.png) I am fine with been deprecated, I am fine with using Graph but please if that is the case do not post that as the command in your own portal

I would recommend you open this as a ticket in the azure portal, posting it here on a closed issue isn't going to get you much progress...

**Comment by damnmso** [comment]
so after 4 years, microsoft was not able to get this compatibility thingen working, thats great :)
so what do i have to do now when -UseWindowsPowerShell does not work?
I get "PS C:\Users\xxx.xxx> Import-Module AzureAD -UseWindowsPowerShell
Import-Module: Failure from remote command: Import-Module -Name 'AzureAD': Das angegebene Modul "AzureAD" wurde nicht geladen, da in keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde."
When i continue, i get the same error with that "Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral..."

So if i understood that correctly, the only way to use this (i want to assign licenses to users via command line to automate processes), is to use the graph api, right?

**Comment by JustinGrote** [comment]
@damnmso so this is not the greatest answer but the AzureAD that runs in Azure Cloud Shell has been patched to solve the issue as I recall, so if you can run your command there then it should work, however these APIs are absolutely deprecated by Azure and you'll need to transition to Graph sooner or later.

All of these are concerns that cannot be addressed in this repo, this is for PowerShell itself and all the Azure stuff is managed by a completely separate team.

**Comment by greigs** [comment]
The commands work on the azure portal "Cloud Shell" for me but not locally.

**Comment by efd7887** [comment]
WTF Microsoft...... Why cant you get this right?  Maybe you need to review your developers and see if they are talented and competent enough to be developing tools that you deploy to millions of your mass user base.  
![image](https://github.com/PowerShell/PowerShell/assets/32522641/4352cb80-604e-4714-a2d7-c28f2ea34d2a)

**Comment by JustinGrote** [comment]
> WTF Microsoft...... Why cant you get this right?  Maybe you need to review your developers and see if they are talented and competent enough to be developing tools that you deploy to millions of your mass user base.  
> ![image](https://github.com/PowerShell/PowerShell/assets/32522641/4352cb80-604e-4714-a2d7-c28f2ea34d2a)
> 
> It would be REALLY nice if we didnt have to constantly fix your issues.  I mean, the time I spend working around these bugs is justifiable of a salary, yet I see no money.  Actually, you should be cutting that check to the company I work for.  They are paying me a fine salary I should not be spending their time trying to fix these issues.  
> 
> Geeze.....  If anyone has a fix for this it would be REALLY nice to use.  Going through the portal to get this information will be roughly 700% less effective.
> 

You're not going to get an answer here, the core PowerShell team is not responsible for modules other people make, including Azure, you have to ask the team that makes that module (which by the way is completely deprecated and you should be using the Microsoft Graph PIM module)
