### ISSUE TITLE
`switch` statement  `default` clause condition keyword should be flagged as keyword token

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10470]
# Summary of the new feature/enhancement

In PowerShell ISE and with PSReadLine, the `default` clause condition keyword of the `switch` statement receives only 'bareword' treatment, making it hard to spot relative to other bareword conditions.

(PowerShell 7 with custom PSReadLine theme)
![image](https://user-images.githubusercontent.com/26179051/64058374-e37ded80-cb6f-11e9-91d8-f4e73f6e80e8.png)

(Example shown here with https://github.com/PowerShell/EditorSyntax/pull/156 (which marks the bareword conditions as unquoted strings) and a custom theme in VS Code, with the keyword highlighted)

![image](https://user-images.githubusercontent.com/26179051/64058337-1b386580-cb6f-11e9-9e7a-a6116ab398b2.png)

# Proposed technical implementation details (optional)

I would propose a change to `Parser.GetCommandArgument()` that would mark the token as a keyword when it meets the criteria for being the `default` clause condition keyword.

I can include a commit to PR https://github.com/PowerShell/PowerShell/pull/10295 that demonstrates this change.

![image](https://user-images.githubusercontent.com/26179051/64058453-e6c5a900-cb70-11e9-973e-41bcab6ca691.png)

**Comment by joeyaiello** [comment]
Conceptually, @PowerShell/powershell-committee agrees that this behavioral part of the change is fine. We defer to the Maintainers and Area Experts to review the technical and implementation aspects of the code. (And we expect that they'll mandate you include some tests in your PR as well :) )

Having looked over #10295, we'd prefer that you add your proposed commit to a separate PR. 

But hey, thanks for the change. I always appreciate seeing improvements to syntax highlighting.
