### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by crshovrd41** [PowerShell/PowerShell#10480]
Hi, I noticed that Invoke-RestMethod has a cap on how many items it can return. This is not listed anywhere in the documentation. Can you please either confirm that this is the case and update the documentation or that this is a bug in the implementation of the command?

**Comment by iSazonov** [comment]
@markekraus Could you please comment?

**Comment by vexx32** [comment]
@crshovrd41 can you provide more details? What version of PowerShell are you running into this with, what OS are you running on, and how exactly did you hit this limitation? 🙂

**Comment by crshovrd41** [comment]
Hi! I apologize. It appeared initially it was a bug but it’s not! The issues ended up being with the way the REST API gets the results. You can definitely close this request, thanks!
