### ISSUE TITLE
New-WebServiceProxy and calling methods with optional parameters 

### ISSUE THREAD

**Issue by Glober777** [PowerShell/PowerShell#10488]
Hi!

I have a module that instantiates a web service proxy object (through `New-WebServiceProxy`) generated based on a fairly large WSDL definition. Within that definition there some methods that contain optional parameters, i.e.:
```
<xsd:element maxOccurs="1" minOccurs="0" name="SomeParameter" nillable="true" type="xsd:string" />
```

The problem is that when I invoke those methods without specifying anything for the optional parameters, they get serialized as:
```
<SomeParameter xsi:nil="true" xmlns="" />
```
…which, in turn is being interpreted by the server as if it was set to Null and acted accordingly. Imagine So in order to call a method that updates some object in a database, I have to know all its property values in advance before and populate them accordingly to avoid them being overwritten by nulls.

What I'd like to have instead is an ability to control whether certain properties should be serialized or not. Is this possible?

While googling around, I came across a suggestion to override EmitDefaultValue attribute, but I can't figure out how that can be done at runtime and not even sure it is applicable to the class generated by New-WebServiceProxy. Another suggestions were to use ShouldSerialize methods and XMLIgnore attributes, but I couldn't figure out how to apply that. Does anyone have any idea?

Thanks!

**Comment by iSazonov** [comment]
@Glober777 The cmdlet is not in the repo. Please use forums and other resources for support.

**Comment by Glober777** [comment]
@iSazonov Actually, it is in the repo:
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/WebServiceProxy.cs

**Comment by iSazonov** [comment]
@Glober777 It is deprecated https://github.com/PowerShell/PowerShell/issues/2240
It will continue to work in Windows PowerShell but not in PowerShell Core.
