### ISSUE TITLE
PowerShell adds "@" when typing accents and quotes

### ISSUE THREAD

**Issue by matheusgrieger** [PowerShell/PowerShell#10481]
# Steps to reproduce

Installed PowerShell Core on a Windows 10 that did not come with it pre-installed.

# Expected behavior

Expected normal typing (had to go back and erase the inserted `@`):
![image](https://user-images.githubusercontent.com/6992464/64210767-7bcee780-ce7a-11e9-9704-4fca087ea346.png)

# Actual behavior

Whenever I try to `Shift + '` to add quotes, it first inserts an `@` and after pressing `Space` it inserts the actual `"` quotemark. Also happens with single quotes, and any kind of accents like `~`, `^` and so on. If I try to type both quotes without pressing space, it'll give me both quotes and a single `@`. If I press space on the fist then try to type another quote, it'll give me another `@`.

![image](https://user-images.githubusercontent.com/6992464/64210786-8be6c700-ce7a-11e9-92ac-c46ceb9868e5.png)
![image](https://user-images.githubusercontent.com/6992464/64210861-bf295600-ce7a-11e9-8790-028e4966868a.png)

I'm brazilian, and I'm on a US keyboard, using "English International" layout, to allow for accents. I also have oh-my-posh and posh-git installed, but I disabled both of them prior to these screenshots.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Could you please check what modules you loaded? Please share `Get-Module` output. 
Also check your profile. You could start pwsh with -NoProfile parameter.

**Comment by matheusgrieger** [comment]
My profile at the moment of testing is exactly this:

```ps1
$DefaultUser = 'Matheus Grieger'

#Import-Module posh-git
#Import-Module oh-my-posh
#Set-Theme Avit

Set-Alias g git
```

All modules are commented. Output of `Get-Module` is the following:

```none
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}
```

Only thing I have that is not native is the PSReadLine. Would that be the cause of the issue? Starting with `-NoProfile` didn't do anything.

**Comment by iSazonov** [comment]
Yes, PSReadLine could be the cause. You could try wit and without it (use Remove-Module) in the same session.

**Comment by matheusgrieger** [comment]
Yes, that solved the issue. Tried updating but to no avail. I'll see what I can do. Thanks!

**Comment by iSazonov** [comment]
If you see a problem with PSReadline and have clear repo steps we could open new issue in PSReadline repo.

**Comment by matheusgrieger** [comment]
I have just installed it, and tried to update it. Only reason I know of its existance is because of oh-my-posh...
