### ISSUE TITLE
Add -Wait parameter to Restart-Service (and other applicable *-Service cmdlets)

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#10486]
# Summary of the new feature/enhancement

Add a `-Wait` parameter to `Restart-Service` so that it blocks until the service has restarted.

**Comment by vexx32** [comment]
Is this not its standard behaviour? At least, it was in Windows PowerShell...

**Comment by kvprasoon** [comment]
yeah, but it's good to add that capability. I've seen people using `SCM` instead of `Stop-Service` to wait for specific time.

**Comment by kvprasoon** [comment]
@rjmholt are we not doing this ?

**Comment by rjmholt** [comment]
> @rjmholt are we not doing this ?

It seems the original issue I opened here is already addressed (where the converse can be done with jobs quite easily).

If you have a different request, please open another issue describing what you're looking for.

**Comment by kvprasoon** [comment]
> It seems the original issue I opened here is already addressed (where the converse can be done with jobs quite easily).

Nothing new, this info was missing here :-)
