### ISSUE TITLE
Feature Request / Get-Command <a cmdlet alias> should return the full info.

### ISSUE THREAD

**Issue by copdips** [PowerShell/PowerShell#10498]
# Summary of the new feature/enhancement

`Get-Command <a cmdlet alias>` should return the same info as to `Get-Command <cmdlet full name>`.

But currently, `Get-Command <a cmdlet alias>` only returns the cmdlet full name.

# Demo on Invoke-WebRequest and its alias iwr

```powershell

# Get-Command without any params

6.2.2> gcm iwr

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           iwr -> Invoke-WebRequest


6.2.2> gcm Invoke-WebRequest

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Invoke-WebRequest                                  6.1.0.0    Microsoft.PowerShell.Utility

# Get-Command with the param -Syntax

6.2.2> gcm iwr -Syntax
Invoke-WebRequest

6.2.2> gcm Invoke-WebRequest -Syntax

Invoke-WebRequest [-Uri] <uri> [-UseBasicParsing] [-WebSession <WebRequestSession>] [-SessionVariable <string>] [-AllowUnencryptedAuthentication] [-Authentication <WebAuthenticationType>] [-Credential <pscredential>] [-UseDefaultCredentials] [-CertificateThumbprint <string>] [-Certificate <X509Certificate>] [-SkipCertificateCheck] [-SslProtocol <WebSslProtocol>] [-Token <securestring>] [-UserAgent <string>] [-DisableKeepAlive] [-TimeoutSec <int>] [-Headers <IDictionary>] [-MaximumRedirection <int>] [-MaximumRetryCount <int>] [-RetryIntervalSec <int>] [-Method <WebRequestMethod>] [-Proxy <uri>] [-ProxyCredential <pscredential>] [-ProxyUseDefaultCredentials] [-Body <Object>] [-Form <IDictionary>] [-ContentType <string>] [-TransferEncoding <string>] [-InFile <string>] [-OutFile <string>] [-PassThru] [-Resume] [-PreserveAuthorizationOnRedirect] [-SkipHeaderValidation] [<CommonParameters>]
```

# Proposed technical implementation details (optional)

We expect to see exactly the same info between `Get-Command iwr` and `Get-Command Invoke-WebRequest`. And the same for all the params.

**Comment by kilasuit** [comment]
This would break user expectations of the command and whilst I can see why you want this, I can't agree that this would be the right way to implement and would counter with adding a switch parameter `ResolveAlias` that would instead check if returning an alias and then return the command that's being aliased instead.

**Comment by vexx32** [comment]
Do people commonly use Get-Command when they just want an alias? I would be surprised if that's common practice. After all, we have Get-Alias for this information already.

**Comment by copdips** [comment]
> Do people commonly use Get-Command when they just want an alias? I would be surprised if that's common practice. After all, we have Get-Alias for this information already.

good point, or at least, Get-Command shold be able to receive Get-Alias from the piepline, something like:

`gal iwr | gcm -Syntax`

otherwise `Get-Command <a cmdlet alias>` is useless.

**Comment by copdips** [comment]
> This would break user expectations of the command and whilst I can see why you want this, I can't agree that this would be the right way to implement and would counter with adding a switch parameter `ResolveAlias` that would instead check if returning an alias and then return the command that's being aliased instead.

OK for `-ResolveAlias` at first.

**Comment by mklement0** [comment]
Good points, @copdips - adding a `-Resolve` switch has been proposed before, in #7387

**Comment by BrucePay** [comment]
One important use of `Get-Command` is to find out what kind of command you have. Hiding the fact that your command is an alias by default is highly undesirable.  However, I think it's reasonable for `Get-Command -Syntax` to "follow the link" and give you the syntax of the aliased command. If this is done, I don't see a particular need for a `-Resolve` parameter.

**Comment by mklement0** [comment]
@BrucePay: I like the idea of `-Syntax` showing the _resolved_ command's syntax, but `-Resolve` should _also_ be supported, for a different reason, because there are _two independent aspects_ to consider:

* what a command's _syntax_ is (your proposal)

* where a command _comes from_ (#7387)

**Comment by mklement0** [comment]
Related: what would be helpful _default_ info for an alias is whether it is _built in_ (as opposed to user-defined), along the lines of:

```none
PS> Get-Command gci

CommandType     Name                                            Version    Source
-----------     ----                                            -------    ------
Alias           gci -> Get-ChildItem                                       (built in)
```
