### ISSUE TITLE
Powershell 7 beta 3 closes after 20 seconds on Ubuntu 18.04

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10497]
# Steps to reproduce

On Ubuntu 18.04.3 VM on Windows 10 Insiders, PowerShell 7 beta 3 only remains open for about 20 seconds before it closes with no indication as to why.   The shell is usable while its open, but when the time runs out, it closes, whether or not any commands have been entered.

I have a console with PowerShell 6.2.2 open at the same time, and it remains open without incident.

I am NOT an avid Linux user, so I don't know much about how it works.

**Comment by iSazonov** [comment]
> Windows 10 Insiders

Please share the version and how you run Ubuntu VM.

**Comment by msftrncs** [comment]
I installed this Ubuntu VM over a year ago.  I downloaded a ISO of the Ubuntu directly from the ubuntu site and installed it from that as a CD in the VM.   Its updated itself many times from the automatic updates from within the operating system.  I use it very little, only to try testing open source cross platform software, once in a while.  I accesses it with the enhanced session and the Xorg Xrdp connector.

**Comment by iSazonov** [comment]
@msftrncs Thanks! Please share Windows 10 Insider version.

**Comment by msftrncs** [comment]
It changes every Thursday/Friday.  😄 I believe its currently build 18975, so it looks like I'm in the 20H1 fast ring at this time.

**Comment by msftrncs** [comment]
preview.5 is no longer doing this.  My guess is something was fixed in .NET Core.
