### ISSUE TITLE
Install on macOS without requiring a password

### ISSUE THREAD

**Issue by RoyTinker** [PowerShell/PowerShell#10495]
Please allow installation on macOS via `brew cask install powershell` without requiring a password during the install.

I just read that PowerShell is available on macOS. How cool! But after typing `brew cask install powershell`, I was greeted with a `Password:` prompt:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/984080/64465063-79110400-d0bf-11e9-8643-eb7662b06c66.png">

I have _never_ had a homebrew package ask me for my password. (I currently have about 60 packages installed.) This makes me feel really uncomfortable... I've decided not to install it after all.

**Comment by iSazonov** [comment]
@TravisEz13 Could you please comment the request?

**Comment by TravisEz13** [comment]
We use a pkg to install a shell.  This will require sudo access.  **As it says two lines above**

Please use the tar.gz instructions.

```
# Download the powershell '.tar.gz' archive
curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/powershell-6.2.0-osx-x64.tar.gz

# Create the target folder where powershell will be placed
mkdir -p <yourPath>

# Expand powershell to the target folder
tar zxf /tmp/powershell.tar.gz -C <yourPath>

# Set execute permissions
chmod +x <yourPath>/pwsh
```

**Comment by RoyTinker** [comment]
> We use a pkg to install a shell. This will require sudo access. __As it says two lines above__

I didn't miss the note two lines above. But saying "I'm going to ask for your password" two lines before a `Password:` prompt doesn't ease the discomfort.

My point in filing this issue is to document--on behalf of many macOS users--what may be keeping them from pursuing a casual interest in `pwsh` on their computers.

**Comment by RoyTinker** [comment]
I disagree with the `Issue-Question` and `Resolution-Answered` tags.

I realize I wasn't clear. I intended this as an enhancement request, not a question. Thanks for clarifying, but `homebrew` packages never ask for passwords, and they install all sorts of things, from `node` and `ruby` to `cowsay` and everything in between -- always without requiring a password.

To fully support `homebrew` as a distribution channel, I believe `pwsh` would do best not to deviate from that expectation.

**Comment by RoyTinker** [comment]
Could you please remove the `Issue-Question` and `Resolution-Answered` tags?

I realize I wasn't clear. I intended this as an enhancement request, not a question. Thanks for providing a workaround, but the issue I wanted to raise is that `homebrew` packages never ask for passwords, and they install all sorts of things, from `node` and `ruby` to `cowsay` and everything in between -- always without requiring a password.

To fully support `homebrew` as a distribution channel, I believe `pwsh` would do best not to deviate from that expectation.

**Comment by TravisEz13** [comment]
This is not possible for this type of package.

**Comment by RoyTinker** [comment]
OK, looks like the issue is really that a MacOS installer .pkg is being used to install PowerShell even from HomeBrew. Installer packages use the macOS installer infrastructure, which requires authentication.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/powershell.rb

I understand that homebrew doesn't disallow asking for a password. But it strongly preaches "don't run `brew` as root!" and 99% of packages (including all shells - `zsh`, `fish`, `bash`, `ksh`, `tcsh`) don't require a password during installation.

**Comment by TravisEz13** [comment]
@RoyTinker 	You don't run homebrew as root.  Homebrew will prompt for a password, as it states in the repro you gave us.
![image](https://user-images.githubusercontent.com/10873629/64658662-171d0b00-d3ed-11e9-819b-3b7d49a169d6.png)

Someone could try to write a Formulae, which would solve your issue, but if it was done, unfortunately, it would not be supported by Microsoft, as it would be a product we did not build.  Our guidance would remain to use the cask, which will prompt for password.

Feel free to contribute a formula to **homebrew** or file an issue in the **homebrew** repo for a formula to be created.

**Comment by TravisEz13** [comment]
Creating a formula like you suggest would require that dotnet produce a formula as well.  If you really, want this you should start there.

**Comment by RoyTinker** [comment]
@TravisEz13 Ah, good to know. Thanks for clarifying!

**Comment by TravisEz13** [comment]
We could build a formula if it was in our own repo.  Would that work?
I have a prototype in my personal repo: https://github.com/TravisEz13/Homebrew-PowerShell
