### ISSUE TITLE
Unable to open PowerShell on new Snap install

### ISSUE THREAD

**Issue by LibraryofV** [PowerShell/PowerShell#10496]
Hello,

Do I need to define where PS should look for the default PATH?

I just followed the instructions provided for installs using Snap on Debian based ElementaryOS.

Please advise

![PS snap install unable to open 2019-09-07 03 52 11](https://user-images.githubusercontent.com/25548438/64469514-f91c8580-d122-11e9-993d-6dc227673f97.png)

**Comment by zigford** [comment]
This is a problem with snapd, not powershell. Snapd will have added a /snap/bin to your path, but your shell is not loading it.
Try running pwsh by specifying it's full path:
`/snap/bin/pwsh`

If that works, you can workaround the issue with the following command assuming you are using bash
`echo 'export PATH=$PATH:/snap/bin' >> ~/.bashrc && source ~/.bashrc`
