### ISSUE TITLE
Shorthand Operator does not work inside function

### ISSUE THREAD

**Issue by SanthoshBonala** [PowerShell/PowerShell#10491]
# Steps to reproduce

```powershell
Param (
[Parameter(Mandatory=$true)]
[string[]] $t
)

Function test {
$empty = @()

$t += $empty

Write-Host $t
}

test
```

# Expected behavior

```none
should append input arguments with empty array
```

# Actual behavior

```none
assigns empty array instead of appending the empty array
```

# Environment data

```none
PSVersion                      5.1.18362.145
```

**Comment by mklement0** [comment]
You're implicitly creating a _function-local_ `$t` variable inside your `test` function, which goes out of scope when the function is exited - the _script-level_ `$t` is never modified.

In an  _assignment_, you'd have to refer to the script-level `$t` variable as `$script:t`, for instance.

(However, on _retrieval_ of the script-level `$t` value, `$t` is sufficient (unless you're shadowing it with a local `$t`. This is a common pitfall - see [this StackOverflow answer](https://stackoverflow.com/a/55403663/45375) for details.)
