### ISSUE TITLE
3 non working keyboard setting commands

### ISSUE THREAD

**Issue by MrLiamMcQ** [PowerShell/PowerShell#10493]
three functions do not work:

Get-WinDefaultInputMethodOverride
Set-WinDefaultInputMethodOverride "0419:00000419"
Set-WinSystemLocale -SystemLocale ru-RU

note i have the languages installed ! an using powershell 5.1 and commands were run using admin powershell.

Get-WinDefaultInputMethodOverride throws an exception
nevermind suddenly Get-WinDefaultInputMethodOverride started working

Set-WinDefaultInputMethodOverride  "0419:00000419"(4019 is russian) correctly sets the registry values located at HKEY_CURRENT_USER\Keyboard Layout\Preload and also it correctly shows the language it was supposed to switch so in "Advanced keyboard settings" but this dose not change the keyboard language as expected:

Set-WinSystemLocale -SystemLocale ru-RU doesn't seem to do anything, i call Get-WinSystemLocale and it just returns and says am english no matter how many times i do the command.

note "Set-WinUserLanguageList ru-RU -Force" successfully changes the keyboard language but is slow and removes all other languages installed.
![bug](https://user-images.githubusercontent.com/28570401/64428665-3a258300-d0ac-11e9-9a68-01a374bc1330.png)

**Comment by iSazonov** [comment]
@MrLiamMcQ The cmdlets are not in the repo. Please move the issue to https://github.com/PowerShell/PowerShellModuleCoverage repository.

**Comment by slycordinator** [comment]
> @MrLiamMcQ The cmdlets are not in the repo. Please move the issue to https://github.com/PowerShell/PowerShellModuleCoverage repository.
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/11524380?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b0a34b9dee59afcd42b8af205ad20025a2d636ac95eebb4d662605e41d7517ac/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[PowerShell/PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage)**Track issues related to using Windows PowerShell modules with PowerShell Core 6 - PowerShell/PowerShellModuleCoverage

Since the module coverage repo has been archived for over 9 months with the issue at https://github.com/PowerShell/PowerShellModuleCoverage/issues/18 having never been resolved, this should be reopened.
