### ISSUE TITLE
Wait-Job behavior with timeout

### ISSUE THREAD

**Issue by kaisxu** [PowerShell/PowerShell#10501]
# Steps to reproduce
The code is aim to set time timeout for back ground jobs. I removed unrelated code here. The behavior is strange for me. Here is the code.
```powershell
function JobWithTimeout {
    param(
        [System.Management.Automation.Job]
        [parameter(
            Mandatory = $true,
            ValueFromPipeline = $true)]
        [ValidateNotNull()]
        $Job,

        [parameter(Mandatory = $true)]
        [ValidateNotNull()]
        [int]
        $TimeoutInSec
    )
    
    Process {
        $Job | Wait-Job -Timeout $TimeoutInSec
        if ($(Get-Job -Id $Job.Id).State -eq "Running") {
            Write-Warning "Job timeout."
        }

        $Job| Stop-Job
        $Job| Receive-Job
        $Job| Remove-Job
    }
}

Start-Job -ScriptBlock {
    Write-Warning "res"
    $aaaa = 1   # <-- remove this line cause timeout
} | JobWithTimeout -Timeout 10


```

# Expected behavior
Always get "WARNING: res"

# Actual behavior

This code works fine and get result “Warning: res”. But if I remove L30, which is meaningless, the job always timeout while `Wait-Job`. Is this a expected behavior? Could you explain the underlying mechanisms to me?
![image](https://user-images.githubusercontent.com/43633998/64499235-d4730a00-d2ea-11e9-8c5c-642d882faf06.png)

# Environment data
Tested on both Windows Powershell and Powershell Core
![image](https://user-images.githubusercontent.com/43633998/64499198-a2fa3e80-d2ea-11e9-8d2b-1ea4ecdf62d8.png)
![image](https://user-images.githubusercontent.com/43633998/64499341-2ae04880-d2eb-11e9-95f3-20f0de895e4b.png)

**Comment by iSazonov** [comment]
Please check on latest PowerShell 7 Preview build.

**Comment by kaisxu** [comment]
Same issue on 7.0.0-preview3
```
PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kaisxu** [comment]
Still repro in PowerShell 7.3.9, same script
