### ISSUE TITLE
Feature Request / enable the creation of alias with cmdlet and its params together

### ISSUE THREAD

**Issue by copdips** [PowerShell/PowerShell#10508]
# Summary of the new feature/enhancement

Currenly, we can only create alias to a cmdlet name only, it would be nice to be able to create alias to the cmdlet and with its params also.

The workaround that I could find till now is to create in advance a new custom cmdlet (via function{}) which calls the target cmdlet with the expected params, and then create an alias that points to this new cmdlet.

```powershell
# The workaround by creating a new cmdlet, 
# ok for complexe functions, 
# but not cool for calling just a cmdlet with params in one line.

function Out-StringWithStream {
    Out-String -Stream
}

Set-Alias oss Out-StringWithStream
```

# Proposed technical implementation details (optional)

```powershell
Set-Alias oss Out-String -Stream

# or with ScriptBlock
Set-Alias oss {Out-String -Stream}
```

**Comment by iSazonov** [comment]
That you want already implemented as proxy functions https://devblogs.microsoft.com/scripting/proxy-functions-spice-up-your-powershell-core-cmdlets/

**Comment by SeeminglyScience** [comment]
Proxy functions came to mind for me as well, but maybe this should be a discussion about improving that experience.  I use proxy functions *a lot* in my profile, but I feel like I'm one of few because of how obtuse they are.  For instance, the above would have to be written as:

```powershell
function Out-StringWithStream {
    [CmdletBinding(DefaultParameterSetName='NoNewLineFormatting', HelpUri='https://go.microsoft.com/fwlink/?LinkID=113368', RemotingCapability='None')]
    param(
        [ValidateRange(2, 2147483647)]
        [int]
        ${Width},

        [Parameter(ParameterSetName='NoNewLineFormatting')]
        [switch]
        ${NoNewline},

        [Parameter(ValueFromPipeline=$true)]
        [psobject]
        ${InputObject})

    begin
    {
        try {
            $outBuffer = $null
            if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer))
            {
                $PSBoundParameters['OutBuffer'] = 1
            }

            $PSBoundParameters.Add('Stream', [System.Management.Automation.SwitchParameter]::Present)

            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand('Microsoft.PowerShell.Utility\Out-String', [System.Management.Automation.CommandTypes]::Cmdlet)
            $scriptCmd = {& $wrappedCmd @PSBoundParameters }

            $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
            $steppablePipeline.Begin($PSCmdlet)
        } catch {
            throw
        }
    }

    process
    {
        try {
            $steppablePipeline.Process($_)
        } catch {
            throw
        }
    }

    end
    {
        try {
            $steppablePipeline.End()
        } catch {
            throw
        }
    }
    <#

    .ForwardHelpTargetName Microsoft.PowerShell.Utility\Out-String
    .ForwardHelpCategory Cmdlet

    #>
}
```

Yeah most of it is generated for you with `ProxyCommand.Create` but for new to intermediate folks, it'll be challenging to even figure out where to put `$PSBoundParameters.Add('Stream', [System.Management.Automation.SwitchParameter]::Present)`.

I don't think `Set-Alias` is the place for something like that, but I'd *love* to see that made a lot easier.

**Comment by vexx32** [comment]
Would be awesome to have a `New-ProxyCommand` cmdlet built in that can generate the needed code and add modifications right from the command line. 🙂

**Comment by copdips** [comment]
@iSazonov 

Thx for sharing the `ProxyCommand`, but sorry, after reading the blog, imho, I dont think it's the answer to this issue. The tag ` Resolution-Answered` should be removed.

First of all, it's too complicated, as a lazy windows admin, I really dont like to write such ProxyCommand just to create an alias to a `cmdlet + params` ? And if I have 10 or more proxy commands to create ?

Then, even for the powershell experts, when they remote connect to a server for a live troubleshooting, and that server only has the default cmdlets set, do they like to or have the time to write such thing ?

BTW, in the Linux world, the alias can be redirected to anything already, it would be nice to port it to powershell.

**Comment by KirkMunro** [comment]
My old [pspx](https://archive.codeplex.com/?p=pspx) module makes this easier. I could refresh that for PowerShell v.Current. It's one of those things where I felt like a rather extreme propeller head and wondered if anyone was actually using the functionality it provided, but it would allow for something like this:

```PowerShell
New-ProxyFunction `
    -CommandName Out-String `
    -ProxyName Out-WithStringStream `
    -RemoveParameter Stream `
    -Begin {
        $PSPassThruParameters.Add('Stream',$true) > $null
    } `
    -DefineNow
```

**Comment by vexx32** [comment]
That sounds like something that would be very very nice indeed. :)

**Comment by iSazonov** [comment]
In general, new proxy cmdlet would has new logic. How would `New-ProxyCommand` help? I believe it is not help. We could address a simple scenario like hiding parameters but it's not worth the effort.
There is a common solution sample - RBAC in Exchange Server.

**Comment by KirkMunro** [comment]
@iSazonov I disagree with the resolution of this issue. Answering a request by saying "just go do this really complicated thing" (proxy commands are not trivial) is not an answer. At a minimum, it should be left open to see if others have similar interest or to continue the discussion. Having it marked as closed and answered signals that there isn't a discussion to be had here.

**Comment by iSazonov** [comment]
@KirkMunro We already have up to 2000 issues without discussion and progress. The issue is not _locked_ and everyone can discuss and share ideas. 
A resolution was to learn Exchange Server RBAC - that tehnology would addresses the feature request. Perhaps it could be implemented as a community module.
