### ISSUE TITLE
Named tuples from C# methods do not retain their names

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#10502]
# Steps to reproduce

```powershell
$namedTuple = [Range]::new(0, 0).GetOffsetAndLength(0)
$namedTuple.Offset
$namedTuple.Length
```

# Expected behavior

`Offset` is translated to `Item1` and `Length` is translated to `Item2`

```none
0
0
```

# Actual behavior

Tuple items must be referred to by their real property names (e.g. `Item1` and `Item2`).

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Notes

Named tuples are implemented in metadata.  The method that returns the tuple is annotated with the `TupleElementNames` attribute.  In the example, the method is annotated with this attribute:

```csharp
[return: TupleElementNames(new string[] { "Offset", "Length" })]
public ValueTuple<int, int> GetOffsetAndLength(int length);
```

The item names cannot be inferred from the value itself, but `PSInvokeMemberBinder` could attach `PSAliasProperty`'s to the tuple after invocation.

Currently this probably isn't all that important. In the version of Core included in7.0.0-preview.3, there are only two public API's in the BCL that return named tuples (the other is `Enumerable.Zip<,>(IEnumerable<>,IEnumerable<>)`).

**Comment by BrucePay** [comment]
I'd be concerned that sticking alias properties on every tuple would be slow. Of course this is a non-issue if tuples aren't used very much. But then if they aren't used, adding the names is unnecessary.  Now what I'd really like is for them to be indexable so I could say `$tuple[0]` instead of `$tuple.Item1`. This would allow you to pass 'arrays' through the pipeline with out having them be shredded. Something like
```powershell
[tuple] (1,2,3,4) | ... shredding goes here ...
```

**Comment by SeeminglyScience** [comment]
> I'd be concerned that sticking alias properties on every tuple would be slow.

Yeah I don't really like it either.  I don't think it would be a big deal for most use cases but at scale it could be pretty nasty. As you said it's not a big deal atm, but it's worth having a conversation about since it seems inevitable that there will eventually be a popular library that uses them heavily.

 > I'd really like is for them to be indexable so I could say `$tuple[0]` instead of `$tuple.Item1`.

Good news! :) I fixed that for tuples (and other cases where an indexer is an explicit interface imlementation) about a year ago with #7633.

> ```powershell
> [tuple] (1,2,3,4) | ... shredding goes here ...
> ```

Not that though.  But you can do `[tuple]::Create(1, 2, 3, 'four')` or if you want an array `[tuple]::Create.Invoke(@(1, 2, 3, 4))`.  A new conversion path that calls `Create` would be pretty cool though, good idea.

I'd also love for the deconstruct syntax to work (#7471).
