### ISSUE TITLE
PowerShell on (Debian) Linux messes up numeric keypad support

### ISSUE THREAD

**Issue by Zastai** [PowerShell/PowerShell#10511]
# Steps to reproduce
1. Open an ssh connection using PuTTY (keypad setting is "Normal", login shell is bash)
2. Ensure the numeric keypad works (`0`-`9`, `/*-+.` and `Enter`)
3. Run pwsh
4. Try the numeric keypad keys again
5. Exit pwsh (whether via `Ctrl-D` or `exit`)
6. Try the numeric keypad keys once more

# Expected behavior

1. Keypad keys work the same in pwsh as in bash (just like they do in ksh, dash, ...)
2. Keypad keys still work when returning to bash from pwsh

# Actual behavior

1. Only the `Enter` key works normally. `/*-` do nothing, `+` inserts `l`, and `0`-`9` insert `p`-`y`.
2. All keypad keys (including `Enter` are non-functional in bash when returning from pwsh.

That PowerShell doesn't handle the keypad is one thing, but that it messes it up for everyone else is Real Bad(tm). It also means that it's not a case of just reading things differently - it seems to be changing the tty's mode without changing it back on exit.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@daxian-dbw Is it PSReadline issue?

**Comment by daxian-dbw** [comment]
This is an issue in .NET Core, as `Console.ReadKey()` generates unexpected `ConsoleKeyInfo` for key pressing from numeric keypad when ssh'ed through PuTTY.
For example, you will the following when pressing `0` on the numeric keypad:
```
PS:1> [System.Console]::ReadKey()
O
KeyChar Key  Modifiers
------- ---  ---------
      O   O Alt, Shift
```
>That PowerShell doesn't handle the keypad is one thing, but that it messes it up for everyone else is Real Bad(tm).

It's messed up by the .NET Core runtime. As soon as you start any dotnet application, you will be left in this "Real Bad" situation.
For example, just run `pwsh -help`, which only prints out the help content and exit. Then you will find all keypad keys are non-functional in bash.
