### ISSUE TITLE
`&` background invocation operator should `-WorkingDirectory` when starting a job

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#10515]
PR #10324 is merged and now we can use `-WorkingDirectory` when starting a job for background invocation operator. 

The following code can be replaced:

https://github.com/PowerShell/PowerShell/blob/f69f30ba49c13ddd601724b35634bf4d1f44e31d/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs#L529-L532

# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-daily.20190906
PSEdition                      Core
GitCommitId                    7.0.0-daily.20190906
OS                             Microsoft Windows 10.0.18978
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by ayousuf23** [comment]
Please assign me to the issue. I submitted a PR for this issue (https://github.com/PowerShell/PowerShell/pull/16180).
