### ISSUE TITLE
Using hyphen/dash parameter produces "Cannot process argument because the value of argument “name” is not valid"

### ISSUE THREAD

**Issue by martinprikryl** [PowerShell/PowerShell#10510]
Using the latest PowerShell 6.2.2:
```
C:\Test>pwsh -File Test.ps1 -
C:\Test\Test.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
+ CategoryInfo          : InvalidArgument: (:) [Test.ps1], PSArgumentException
+ FullyQualifiedErrorId : Argument,Test.ps1
```

The `Test.ps1` is simple

```sh
echo "foo"
```

The error does not make any sense to me. I suspect it's a bug in command-line parsing.

---

PowerShell 5.1 also processes the dash strangely (although it manifests differently):
[What does hyphen/dash parameter mean to PowerShell?](https://stackoverflow.com/q/57199565/850848)

PowerShell 2.0 works as expected.

**Comment by iSazonov** [comment]
> __Cannot process argument__ because the value of argument "name" is not valid

The error message clearly says that you have a typo in argument name. Dash in command line always assumes an argument.

**Comment by martinprikryl** [comment]
@iSazonov  OK, thanks for your answer. But that's a "new" behavior, right? Because in PowerShell 2.0, it is valid to provide a dash as a parameter value. And is there a way in PowerShell 6.0/5.1 to provide a dash as a parameter value?

**Comment by iSazonov** [comment]
@martinprikryl Please use our issue template - add repo steps, expected behavior and used pwsh version.

Perhaps there is inconsistency
```powershell
pwsh -command 'echo $args[0]' -

# Output -

# $args[0] in test.ps1
 pwsh -file C:\temp\test.ps1 -

# Output
C:\temp\test.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.

**Comment by martinprikryl** [comment]
I'm not sure what steps you ask me for.

But let me try.

I have this script:

```
echo $args[0]
```

I want to be able to provide a value `-` to the argument.

In PowerShell 2.0, I can simply do:

```
powershell.exe -File Test.ps1 -
```

And I get:

```
-
```

In PowerShell 6.2.2 (as well as 5.1) I get the above mentioned error message:

> Cannot process argument because the value of argument "name" is not valid.

Is this an intentional change? Or is it a bug?

If it is an intentional change, is there a way to escape the `-` to provide a literal value `-` to the argument?

I have tried a backslash, a backtick, single and double quotes, a double dash, a caret, but neither does that.

```
C:\>pwsh -File Test.ps1 -
C:\Test.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
+ CategoryInfo          : InvalidArgument: (:) [Test.ps1], PSArgumentException
+ FullyQualifiedErrorId : Argument,Test.ps1

C:\>pwsh -File Test.ps1 `-
`-

C:\>pwsh -File Test.ps1 \-
\-

C:\>pwsh -File Test.ps1 '-'
'-'

C:\>pwsh -File Test.ps1 "-"
C:\Test.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
+ CategoryInfo          : InvalidArgument: (:) [Test.ps1], PSArgumentException
+ FullyQualifiedErrorId : Argument,Test.ps1

C:\>pwsh -File Test.ps1 -- -
C:\Test.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
+ CategoryInfo          : InvalidArgument: (:) [Test.ps1], PSArgumentException
+ FullyQualifiedErrorId : Argument,Test.ps1

C:\>pwsh -File Test.ps1 ^-
^-
```

**Comment by martinprikryl** [comment]
OK, so this is not going to get fixed in 6.x?

**Comment by iSazonov** [comment]
I guess we haven't direct commit for the issue, it was a side effect from adding new parameters. So it is not easy backport the change.
