### ISSUE TITLE
Failed to update Help

### ISSUE THREAD

**Issue by jamessingh007** [PowerShell/PowerShell#10520]
# Steps to reproduce
```
1. Install PowerShell 6.2.2 on Windows 10
(Download  URL: **PowerShell-6.2.2-win-x64.msi**
 https://github.com/PowerShell/PowerShell/releases/tag/v6.2.2)
2. Run Update-Help in the PS6 console (Administrator mode)
Alternatively I tried **Update-Help -Force**  also, but i got the same error
```
# Expected behavior
```
Successful Help update
```

# Actual behavior

```
Received the following error
```
![image](https://user-images.githubusercontent.com/29583197/64778711-fcc46800-d579-11e9-872d-e01cbb8881ba.png)

# Environment data

![image](https://user-images.githubusercontent.com/29583197/64778313-83c51080-d579-11e9-85f3-e27922e8037c.png)

**Comment by iSazonov** [comment]
@jamessingh007 Thanks! Please continue discussion in #9981 .
