### ISSUE TITLE
The more and less utilities (pagers) break command-line editing on macOS and Linux

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10524]
Note:

* On macOS 10.14, both `more` and `less` produce the symptom, whereas it is only `less` on Ubuntu 18.04.
* Whether or not the `PSReadLine` module is loaded makes no difference.

<sup>It took considerable discipline to refrain from _more or less_ jokes.</sup>

# Steps to reproduce

On macOS or Ubuntu, run the following and then press <kbd>q</kbd> to exit the pager:

```powershell
# On macOS, `more` is affected too.
1..200 | less
```

# Expected behavior

`less` should exit, the command prompt should return, and command recall with <kbd>arrow up</kbd> should continue to function.

# Actual behavior

`less` exits and the command prompt does return, but command recall is now broken: an `A` is printed instead.

# Environment data

```none
PowerShell Core v7.0.0-preview.3 on macOS 10.14.6
PowerShell Core v7.0.0-preview.3 on Ubuntu 18.04.3 LTS
```

**Comment by mklement0** [comment]
@iSazonov  Yes; to quote from the OP:

> Whether or not the PSReadLine module is loaded makes no difference.

It's natural for people to assume this is PSReadLine-related, even though it isn't, and there's already more information in the linked issue. I suggest we tag this one 'Resolution-External' and keep it open in parallel, for discoverability.

**Comment by iSazonov** [comment]
'Resolution-External' will auto closes the issue.

**Comment by iSazonov** [comment]
If a native command is last in a pipeline will it rise the issue too?

**Comment by mklement0** [comment]
> 'Resolution-External' will auto closes the issue.

I guess a closed issue is better than none for discoverability, but it would more make sense to me to keep such issues open until the issues is actually resolved (externally).

> If a native command is last in a pipeline will it rise the issue too?

`more` and `less` become effective no-ops (buffering changes aside) if you don't use them as the _last_ pipeline segment, so the issue doesn't arise then - but it's  a useless use case.
