### ISSUE TITLE
test-path, -newerthan, -path with wildcards

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#10532]
Test-path seems to fail with the -newerthan option and a -path with wildcards.  I think the wildcard might be incorrectly matching otherfile.txt.  May have to run this twice.

# Steps to reproduce

```powershell
echo hi > otherfile.txt
sleep 1
echo hi > found.txt # newer

$template = 'f*.txt'
$CutoffTime = (Get-Item OtherFile.txt).LastWriteTime
$CutoffTime

$templateTime = (Get-Item found.txt).LastWriteTime
$templateTime

Get-Item $Template|?{$_.LastWriteTime -gt $cutofftime} | ft

Test-Path $Template -NewerThan $cutofftime  # incorrectly false

Test-Path $Template
```

# Expected behavior

```none

Friday, September 13, 2019 11:30:45 AM
Friday, September 13, 2019 11:30:46 AM



    Directory: C:\users\admin\foo

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         9/13/2019 11:30 AM              4 found.txt

True
True
```

# Actual behavior

```none

Friday, September 13, 2019 11:30:45 AM
Friday, September 13, 2019 11:30:46 AM



    Directory: C:\users\cdmin\foo

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         9/13/2019 11:30 AM              4 found.txt

False
True
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by msftrncs** [comment]
I don't seem to be able to reproduce this.  The only difference is I am using a much newer build of Windows 10 (18362).  Anything else particular about your environment?  Can you try this on a newer version of Windows 10?

**Comment by msftrncs** [comment]
I think I figured this out.  The very first time, when both files are 'new', it works.  Subsequent times, it does not work.

I would guess, `Test-Path` uses the 'Creation Time', not the 'Last Modified Time'.  If the script is changed to `CreationTime` then it works as expected, but will not tell you that the path you are testing has files modified later than a specified time.

The documentation does not explain which field is being used.

**Comment by iSazonov** [comment]
Docs says that wildcard is supported https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-path?view=powershell-6

Debug shows it is bug. We check LastWriteTime but for directory, not for resolved paths - we don't enumerate files by wildcard.
Code reference https://github.com/PowerShell/PowerShell/blob/0e975a52ed3896a0d60ddadf424e742db275e063/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3351-L3354
