### ISSUE TITLE
dependency download link

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10531]
When trying to build the latest commit of PowerShell, I get a message about the preview version of the .NET Core SDK not being found, and suggesting to download the SDK from a link.   

The link given is to the documentation, not to the download site.

```
Installing PowerShell build dependencies
A compatible SDK version for global.json version: [3.0.100-preview9-014004] from [C:\Users\Carl\Documents\Git Repositories\PowerShell\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
WARNING: The 'dotnet' in the current path can't find SDK version 3.0.100-preview9-014004, prepending C:\Users\Carl\AppData\Local\Microsoft\dotnet to PATH.
dotnet is already installed.  Skipping installation.
```
I can get to the downloads from this link, but it is not immediately obvious why I landed on a documentation page regarding prerequisites, with no download links on this page.

**Comment by iSazonov** [comment]
There is a link to donload
> For download links and more information, see .NET downloads to download the latest version or .NET downloads archive for older versions.
