### ISSUE TITLE
lastest releases Chinese character Repeat twice.

### ISSUE THREAD

**Issue by obhen233** [PowerShell/PowerShell#10548]
![TIM截图20190916111429](https://user-images.githubusercontent.com/24905302/64932745-9db16c80-d873-11e9-9d32-38613c40e146.png)

**Comment by obhen233** [comment]
windows 8.1 OS

**Comment by iSazonov** [comment]
Please test without PSReadline module:   `Remove-Module PSReadline`

**Comment by obhen233** [comment]
> 
> 
> Please test without PSReadline module: `Remove-Module PSReadline`

it works well

**Comment by iSazonov** [comment]
@obhen233 You could open new issue in PSReadline repository.
