### ISSUE TITLE
Best Practices Module does not work with PowerShell 7 Preview

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#10540]
The BestPractices module does not load in PowerShell 7. It also does not load using WIndows Compatibility module.

# Steps to reproduce

```powershell
Import-Module -Name BestPractices
# or
Import-WinModule -Name BestPractices
```

# Expected behaviour 
I would have expected one or the other to have worked. 

# Actual behavior
Both fail.

# Environment data
PS [C:\foo> ]> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.18980
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0-preview.3}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```powershell

```

**Comment by vexx32** [comment]
Can you be more specific? Does an error occur? What are the details of the error? 🙂

**Comment by kilasuit** [comment]
Where do you get this module from? I can't see it on the PowerShellGallery and therefore am unable to test around this at all, nor can anyone else for that matter

**Comment by iSazonov** [comment]
It is standard module in Windows Server. It is not marked as PowerShell Core compatible.
Please report in https://github.com/PowerShell/WindowsCompatibility repository.

**Comment by doctordns** [comment]
It is a standard module in WIndows server and client- and I understand it may not be importable directly into PowerShell 7.

However, this also fails to be loaded with Windows Compatibility module:

```powershell
PS [C:\foo> ]> import-winmodule bestpractices
Import-Module : Failed to generate proxies for remote module 'BestPractices'. Running the Get-FormatData command in a remote session reported the following error: Unable to cast object of type 'Microsoft.PowerShell.Commands.Internal.Format.ControlReference' to type 'Microsoft.PowerShell.Commands.Internal.Format.ComplexControlBody'..
At C:\Program Files\PowerShell\Modules\WindowsCompatibility\1.0.0\WindowsCompatibility.psm1:531 char:13
+             Import-Module  -Name $ImportNames -NoClobber:$NoClobber @ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
+ FullyQualifiedErrorId : CmdletInvocationException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by doctordns** [comment]
Not sure that the @msftbot answer is actually all that helpful.

The best practises module is not usable wither directly or via WinCompat module. Surely this is not the intended behaviour?

**Comment by iSazonov** [comment]
@doctordns Your report is not in right repo. If you want the module works with WIndows Compatibility module please report in https://github.com/PowerShell/WindowsCompatibility.

Also MSFT team has https://github.com/PowerShell/PowerShellModuleCoverage to track Windows PowerShell module compatibility. 

I wonder you ask again because you already reported there. Sorry if I misled you.
