### ISSUE TITLE
[PowerShell 7 Preview 3] help *provider* breaks the help command for certain provider help topics

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#10553]
Run these commands:
```
help about_FileSystem_Provider
help *provider*
```
After that, repeat the command `help about_FileSystem_Provider`.
The command doesn't return the content of the `about_FIleSystem_Provider` help topic anymore.
Instead the output looks like this:
```
Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
about_FileSystem_Provider         HelpFile
``` 
The same happens for about_Registry_Provider help topic.

Also, the same behavior is noticed for `Get-Help about_FileSystem_Provider -Full`.

**Comment by sdwheeler** [comment]
See related issue https://github.com/PowerShell/PowerShell/issues/9208
