### ISSUE TITLE
List of experimental features in Modules not built in repo needs to be maintained

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10550]
During the official build the modules are restored during packaging so build.psm1 cannot enumerate the experimentalfeatures

List of experimental features in Modules not built in repo needs to be maintained.

Code to get list:

```powershell
Get-Module -ListAvailable | Where-Object {$_.Path -like "${pshome}*"} | Select-Object -ExpandProperty ExperimentalFeatures | Select-Object -ExpandProperty Name
```

**Comment by iSazonov** [comment]
@TravisEz13 Is the issue actual or we can close?

**Comment by TravisEz13** [comment]
Actual issue:
https://github.com/PowerShell/PowerShell/blob/1bf5cc93175840fc22ee708c69a87fe704f77702/build.psm1#L577

**Comment by daxian-dbw** [comment]
For release builds the experimental features are now coming from the pre-generated files:
- `experimental-feature-windows.json`
- `experimental-feature-linux.json`

It's done by https://github.com/PowerShell/PowerShell/pull/16823 and https://github.com/PowerShell/PowerShell/pull/16837.
Given the above, this can be closed now.
