### ISSUE TITLE
Can't Set/ Remove Execution Policy

### ISSUE THREAD

**Issue by grooveasylum** [PowerShell/PowerShell#10565]
Followed the documentation the the letter to remove the execution policy on my LocalMachine.

I am running Powershell as the Administrator; see attachement;
![powershell](https://user-images.githubusercontent.com/35968487/65065225-dd8d5800-d936-11e9-8d7c-01861fc2363a.PNG)

**Comment by vexx32** [comment]
The `Undefined` policy is the same as `Restricted` by default, to my knowledge. Setting the policy to undefined is requesting the same behaviour as default, which is the no-scripts-allowed behaviour.

If you want to run scripts you need to set it to `Unrestricted` or `RemoteSigned` (or `AllSigned` if you only want to allow signed scripts from trusted providers to run).

**Comment by grooveasylum** [comment]
I will give that a try - thank you.
Just to provide some history, these are the instructions I was following; http://prntscr.com/p7eew0

**Comment by grooveasylum** [comment]
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine 

I'm getting the same result; powershell is only allowing me to choose [N] No.

**Comment by SeeminglyScience** [comment]
@grooveasylum You are selecting yes, the color just tells you what the default is.  Check the output of this: `Get-ExecutionPolicy -List`.  If `CurrentUser` is set, that'll take precedence over `LocalMachine`.  If `MachinePolicy` or `UserPolicy` is set, then it's set via GPO and it can't be changed (without getting your org to change the GPO).

**Comment by grooveasylum** [comment]
Thank You!
