### ISSUE TITLE
建议改善颜色体验

### ISSUE THREAD

**Issue by EdwinIZ8** [PowerShell/PowerShell#10564]
我希望PowerShell尽量不要使用黄色的文字，其实保持终端原始的颜色就好。因为黄色、红色都不易辨认，会让人在阅读的时候非常费力。黑色和白色不错。

# 保持终端默认的文字以及背景颜色就好。

**Comment by bergmeister** [comment]
Google translates this into:
>  I hope that PowerShell will try not to use yellow text. In fact, it is better to keep the original color of the terminal. Because yellow and red are not easy to identify, it will make people very hard to read. Black and white are good.
Keep the terminal's default text and background color just fine.

cc @joeyaiello as you were involved in accessibility.
