### ISSUE TITLE
Add option to turn off telemetry as part of install process

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#10578]
During installation the installer should show that telemetry is being collected and that it can be disabled.

The installer should also allows for pwsh to be installed and turn telemetry off via cmdline parameter or via UI install screen

**Comment by vexx32** [comment]
I think this would go a _long_ way towards assuaging the concerns of folks who don't like the telemetry. The ability to opt in or out _on install_ is much more visible and actionable than an environment var is.

**Comment by sba923** [comment]
I presume there is some doc about what telemetry actually collects?

**Comment by iSazonov** [comment]
> I presume there is some doc about what telemetry actually collects?

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_telemetry?view=powershell-7.1

**Comment by kilasuit** [comment]
Thanks for getting this closed @bergmeister & @TravisEz13 !!
