### ISSUE TITLE
Automatically split pipes and ForEach-Object commands to a new line

### ISSUE THREAD

**Issue by thomasrea0113** [PowerShell/PowerShell#10572]
# Summary of the new feature/enhancement

This is really just a continuation of the issue #3020, as it didn't really provide a satisfactory answer. As far as I can understand it, the #9614 PR doesn't really offer a solution for this scenario. I'd like to the ability to take the following line:

```powershell
$Ports | ForEach-Object -Process { NETSTAT.EXE -ano | findstr.exe :8080 | ForEach-Object -Process { ($_ -split '\s+')[-1] } | Sort-Object | Get-Unique | ForEach-Object -Process { taskkill.exe /F /PID $_ } }
```

and convert it to:

```powershell
$Ports |
    ForEach-Object -Process {
        NETSTAT.EXE -ano |
            findstr.exe :8080 |
            ForEach-Object -Process {
                ($_ -split '\s+')[-1]
            } | Sort-Object |
            Get-Unique |
            ForEach-Object -Process {
                taskkill.exe /F /PID $_
            }
    }
```

I think this would go a long way in approving readability. At the very least, with the 

```json
"powershell.codeFormatting.pipelineIndentationStyle": "IncreaseIndentationForFirstPipeline"
```

setting enabled, when I manually add the new line after each `|` and `}`, it will format the indentation correctly which is nice.

**Comment by vexx32** [comment]
This should be in the [vscode-powershell](https://github.com/PowerShell/vscode-powershell/) or [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer/) repositories; PowerShell itself doesn't handle formatting directly. 🙂

**Comment by thomasrea0113** [comment]
Ah... I see that I have posted my comment in the wrong place. Closing and move to the right repo!
