### ISSUE TITLE
Preferences not retained when launched from Explorer Dialogue

### ISSUE THREAD

**Issue by LarnuUK** [PowerShell/PowerShell#10571]
I've changed some of the Properties on PowerShell 7.0.0-preview.3, such as the font, and colouring of the window. When the application is launched via the shortcut then these preferences are retained for each launch.

If, however, I launched the application by right clicking in File Explorer and selecting `Powershell 7-preview > Open here` the preferences from the other window aren't loaded. Interestingly, however, if I change the properties in that window, and then use the dialogue options again, then the settings (of the window i just changed) are loaded. The preferences of the shortcut to the aopplication aren't affected.

It appears that the settings are saved in different locations depending on if the application is launched from a shortcut to `C:\Program Files\PowerShell\7-preview\pwsh` (or running the executable from the directory), or using the Windows Explorer Dialogue.

**Comment by vexx32** [comment]
This is more of a Windows issue in how it handles console defaults and customization, I feel? 🤔

**Comment by SeeminglyScience** [comment]
Yeah, that's how all console apps work.  There's a config in the registry for every exe, and a separate config for any shortcut you make for it.  Nothing PowerShell can do about it 😕 

I've taken to not launching via a shortcut (instead with <kbd>Win</kbd> + <kbd>R</kbd>/an app launcher program/explorer), a bit more consistent that way imo.

**Comment by LarnuUK** [comment]
> Yeah, that's how all console apps work. There's a config in the registry for every exe, and a separate config for any shortcut you make for it. Nothing PowerShell can do about it 😕

You're right; this isn't an issue I have with an application like Putty as it saves it's preferences elsewhere. Does seem to be a Windows "feature". 😞

Will close this then. Thanks.
