### ISSUE TITLE
Exit Broken PSSession

### ISSUE THREAD

**Issue by hattenator** [PowerShell/PowerShell#10573]
Is it possible to exit a disconnected or otherwise broken remote powershell session?  I have one open where every command I enter, I get:

Starting a command on the remote server failed with the following error message : Authorization failed For more information, see the about_Remote_Troubleshooting Help topic.

That includes "Exit-PSSession", "exit", "Get-PSSession", "^C", "^break", "esc-\", "^\", "^D"...

This is from Linux to Windows, without using ssh.  If I open a new pwsh, I can't see the session from this one.

Is there a hotkey or something to terminate an inner remote shell?  I searched around and couldn't find anything.  On ssh from Linux to Linux, if you hit
~.
at any time, it will disconnect the ssh session and return you to your host prompt.  ~& backgrounds the ssh process, but leaves it running.  Is there any equivalent for powershell core?

**Comment by iSazonov** [comment]
See docs about disconnected sessions https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_remote_disconnected_sessions?view=powershell-7
