### ISSUE TITLE
Writing to linux named pipes fails

### ISSUE THREAD

**Issue by Daniel314** [PowerShell/PowerShell#10584]
**# Steps to reproduce**

Start with this:
mknod outputFile p  

Then all of the following commands generate an error:

Get-Process | Out-String | Add-Content ./outputFile
Get-Process | Out-String | Out-File ./outputFile
Get-Process | Out-String | Set-Content ./outputFile
Get-Process | Out-String > ./outputFile

**# Expected behavior**

No error to be returned when writing to a named pipe (as long as a process is reading from the pipe)

**# Actual behavior**

An error is returned when trying to write to the named pipe.  Depending on the command used, the error varies:
Add-Content : Stream does not support seeking.
Out-File : Invalid argument
Set-Content : Invalid argument
out-file : Invalid argument   (using " ... > namedPipe")

The full error content looks like:

```
Set-Content : Invalid argument
At line:1 char:28
+ Get-Process | Out-String | Set-Content ./outputFile
+                            ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Set-Content], IOException
+ FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.SetContentCommand

```
or
```
out-file : Invalid argument
At line:1 char:1
+ Get-Process | Out-String > ./outputFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Out-File], IOException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

```

**# Environment data**

PS /home> $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I guess we need NamedPipeServerStream class. I am not sure that we can implement this transparently, We already have Stream parameter so we could have NamedPipe parameter.

**Comment by Hashbrown777** [comment]
> This issue has not had any activity in 6 months, if this is a bug please try to reproduce on the latest version of PowerShell and reopen a new issue and reference this issue if this is still a blocker for you.

So are we supposed to continually add useless comments to tickets that have all the information already just to keep them alive or what?
