### ISSUE TITLE
Can´t download NuGet Package on NetCore 2.2

### ISSUE THREAD

**Issue by RotterAxel** [PowerShell/PowerShell#10582]
Hello! 
The PowerShell 6.2.2 on Nuget is not Compatible with NetCore 2.2 Apps. I would like to know where I can find information on when this will be supported? 

The Error Messages I get when Trying to Install are:

**Error** Package 'PowerShell 6.2.2' has a package type 'DotnetTool' that is not supported by project 'ProjektL.API.xUnitTest'.				
**Error NU1202** Package PowerShell 6.2.2 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package PowerShell 6.2.2 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any	ProjektL.API.xUnitTest	I:\Portfolio\LeasingApp\Leasing.API.Repo\Leasing.API\ProjektL.API.xUnitTest\ProjektL.API.xUnitTest.csproj	1	
**Error** NU1212	Invalid project-package combination for PowerShell 6.2.2. DotnetToolReference project style can only contain references of the DotnetTool type 	ProjektL.API.xUnitTest	I:\Portfolio\LeasingApp\Leasing.API.Repo\Leasing.API\ProjektL.API.xUnitTest\ProjektL.API.xUnitTest.csproj	1	

Thanks

Axel

**Comment by iSazonov** [comment]
We target the Nuget package to netcoreapp2.1 and I wonder that it is not backward compatible.
@RotterAxel Could you share a reference on your project on GitHub?

**Comment by bergmeister** [comment]
Most people reference the `System.Management.Automation` package only for referencing. In this case I suggest to try using `PowerShell.Standard` instead if possible. Otherwise you'll have to change it to `6.1.1`, which is `netstandard2.0` based and will therefore work for .Net Core 2.2, see #10372 for details

**Comment by masaeedu** [comment]
@bergmeister I'm trying to reference it from .NET Standard 2.0, but it looks like the NuGet package [here](https://www.nuget.org/packages/System.Management.Automation/6.2.3) doesn't supply binaries for any TFMs other than netcoreapp2.1.

I'm not sure whether this is an oversight in terms of how things are packaged, or if the library is just coupled to .NET Core (and won't work on e.g. .NET 4.6.1).

**Comment by iSazonov** [comment]
Please see https://github.com/PowerShell/PowerShell/issues/10379#issuecomment-522783557

**Comment by bergmeister** [comment]
PowerShell 6.2 is coupled to .net core 2.1, 7.0 will be coupled to 3.1, therefore for using .net core 2.2 features at runtime, you will need to go with 7 (currently in preview but will release in a few months). If you use .net standard, then you will need to reference the PowerShell.standard library, which can also be used for Windows PowerShell (aka full .net). If you don't want/can use the standard library, you will need to multitarget net462 or similar and SMA 5.1 for binaries that work for Windows PowerShell
