### ISSUE TITLE
Get-SecureUEFI can't get dbt variable.

### ISSUE THREAD

**Issue by YunSyuan** [PowerShell/PowerShell#10580]
Get-SecureBootUEFI used the wrong GUID (EFI_GLOBAL_VARIABLE_GUID) so cause it can not get dbt.

In UEFI spec 2.8, define the EFI_IMAGE_SECURITY_DATABASE2(dbt) should use the EFI_IMAGE_SECURITY_DATABASE_GUID, so this is the power shell command issue, you can refer to UEFI spec 2.8 - 32.6.1 UEFI Image Variable GUID & Variable Name for detail.

**Comment by iSazonov** [comment]
@YunSyuan Get-SecureBootUEFI is not in the repo. Please report on UserVoice site or use Windows 10 Feedback tool.
