### ISSUE TITLE
New `$PSUserHome` automatic variable for path to root of PowerShell user installation path

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10585]
# Summary of the new feature/enhancement

As a scripter,
I want a `$PSUserHome` automatic variable that contains the path to the folder where a user profile, configuration file, etc. are stored,
so that I can work with that location when appropriate more easily.

# Proposed technical implementation details (optional)

Add a `$PSUserHome` automatic variable, that would be the current user equivalent of the `$PSHome` automatic variable. Store the base folder in which user profiles (`$profile`) are written in that automatic variable, and mark it as read-only.

# Alternate proposals/considerations

I'm not 100% sold on the `$PSUserHome` name. While it is similar to `$PSHome`, I wonder if users might confuse it with `$Home`. I'm not sure what else would be an appropriate name for this folder though. Suggestions for better names than `$PSUserHome` are welcome and appreciated.

**Comment by vexx32** [comment]
🤔 perhaps `$PSConfigRoot`?

**Comment by iSazonov** [comment]
This could be resolved in #6966
