### ISSUE TITLE
Feature Request: keyword statement in hashtable assignments should reset parser for next hash key

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PowerShell#10590]
# Summary of the new feature/enhancement

When a keyword statement is used in regular context, the end of the statement block (usually) marks the end of the statement, and a new statement may start immediately without a new line or a `;` semicolon terminator.  However this doesn't happen when keyword statements are used in hashtable literal assignments.

```PowerShell
# should be acceptable but isn't
@{key1 = if (cond) {statement cond1} elseif (cond2) {statement cond2} key2 = 3} # key2 is an unexpected token

# normal practice
@{
    key1 = if (cond) {statement cond1} elseif (cond2) {statement cond2} 
    key2 = 3 # key2 is accepted
}

# noted special condition
@{
    if = if (cond) {statement cond1} elseif (cond2) {statement cond2} 
    else = 3 # else key not accepted, expected to be remnant of if statement.
}

# required regardless of this request
@{
    if = if ($cond) {statement cond1} elseif (cond2) {statement cond2}; 
    else = 3 # else key is accepted, `;` above ended if statement definitively
}
```

I'm not saying this request is good practice.  I'm just pointing out a discrepancy in behavior.

**Comment by iSazonov** [comment]
> I'm not saying this request is good practice

Looking on the samples I think we get no benefits if we fix this.
