### ISSUE TITLE
[Microsoft.PowerShell.Commands.WebSslProtocol] doesn't expose the Tls13 enum value (Invoke-WebRequest, Invoke-RestMethod)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10597]
Related: #6589

`Microsoft.PowerShell.Commands.WebSslProtocol` is a wrapper for `enum` type `System.Net.SecurityProtocolType`, which means that the wrapped type's enumeration values must be kept in sync with the wrapper's.

Currently, the two diverge:

# Steps to reproduce

```powershell
[System.Net.SecurityProtocolType] 'Tls13' | Should -Be Tls13
[Microsoft.PowerShell.Commands.WebSslProtocol]  'Tls13' | Should -Be Tls13
```

# Expected behavior

The tests should succeed.

# Actual behavior

The 2nd test fails: 

```
Unable to match the identifier name Tls13 to a valid enumerator nam
```

# Environment data

```none
PowerShell Core 7.0.0-preview.3
```

**Comment by iSazonov** [comment]
@markekraus Do we still need the WebSslProtocol?

**Comment by iSazonov** [comment]
https://github.com/PowerShell/PowerShell/blob/461a95cee403f4b608102fe9b721b1941ba2bdbe/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L55-L56

/cc @SteveL-MSFT It is public but do we really need this? It seems we could add new overload with SslProtocols and add Obsolete attribute to old.

**Comment by CarloToso** [comment]
@iSazonov No longer an issue, `WebSslProtocol` includes `Tls13`
