### ISSUE TITLE
Powershell 6.2.3 installation removes Path from $env:PsModulePath

### ISSUE THREAD

**Issue by Stephanevg** [PowerShell/PowerShell#10620]
Hi guys,

I just installed powershell version 6.2.3 on my professional laptop, through a suggestion in vscode telling me that my powershell version was out of date. IT offered me to install, which I did.

Since then, I noticed none of my modules in ```C:\program files\Windowspowershell\modules\``` could be loaded anymore.

Having a closer look at my env path, this is what I see in vscode:

![image](https://user-images.githubusercontent.com/6302961/65568608-cbc13b80-df5a-11e9-9e51-eb43ad54d9b3.png)

We don't have ```C:\program files\Windowspowershell\modules\``` anymore but ```C:\program files\powershell\modules\``` instead.

This is a breaking change for me.

After a second check, I do have now version 6.2.3 of powershell available in vscode (loaded by default).

![image](https://user-images.githubusercontent.com/6302961/65568714-117e0400-df5b-11e9-9acc-fed9ab0735ab.png)

This is of course not what I wanted.

I can imagine that that path is missing only because it is powershell core, and that the folder `WindowsPowershell` can't be present on a mac / linux box.

So far, I am ok with that.
But I work on a Windows machine, and that WindowsPowershell path has been there since modules where introduced. 

Did I do something stupid and removed it my self? or is this really part of pscore? If so, why also on a Windows machines? 

And how can default back to Windows 5.1 on vscode, because clearly broke a lot of working habits (And reduced once more, the user experience I have with VsCode)

**Comment by iSazonov** [comment]
@Stephanevg Thanks for you report! You could download artifact from #10300 and try the build if it fix your issue.
