### ISSUE TITLE
Enable tab completion for variables that are of enum type

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#10631]
# Summary of the new feature/enhancement

When setting preference variables like `$ErrorActionPreference`, it would be great to help users discover allowed values by:

```powershell
$ErrorActionPreference = <tab>
```

instead of trying to set it to something invalid and seeing the allowed values in the error message.

**Comment by mklement0** [comment]
That would be an excellent improvement.

Ideally, this should also work  for flag (bit-field) enumerations, so that something like the following would work:

```powershell
[Flags()] enum Foo { first = 0x1; second = 0x2; third = 0x4 }

[Foo] 'first, th'<tab>  # -> 'first, third', tantamount to [Foo]::first -bor [Foo]::third
```

**Comment by SeeminglyScience** [comment]
> ```powershell
> $ErrorActionPreference = <tab>
> ```

Should it be that or should it be:

> ```powershell
> $ErrorActionPreference = '<tab>
> ```

If the former, would it complete to a string or to a static member expression?

Also would be fantastic if this worked on convert expressions (like in @mklement0's example)

**Comment by mklement0** [comment]
Good question, @SeeminglyScience.

I'm thinking that even `$ErrorActionPreference = <tab>` (no opening quote) should complete to a _string_ (e.g, `$ErrorActionPreference = 'Stop'`), for two reasons:

* Using types and static properties is an advanced technique, and strings are more concise and provide better symmetry with use in _arguments_ (e.g., `-ErrorAction Stop`), where use of the static property expression would be impractical (e.g., `-ErrorAction ([System.Management.Automation.ActionPreference]::Stop`)

* With flag enumerations, a string value is easier to modify later (again with tab-completion support), especially when new flags are added (e.g., `'Compiled'` -> `'Compiled, IgnoreCase'` vs. `[System.Text.RegularExpressions.RegexOptions]::Compiled` -> `[System.Text.RegularExpressions.RegexOptions]::Compiled -bor [System.Text.RegularExpressions.RegexOptions]::IgnoreCase`)

**Comment by SteveL-MSFT** [comment]
I think string is definitely more user friendly.

**Comment by SteveL-MSFT** [comment]
@mklement0 please open a new issue for flags

**Comment by mklement0** [comment]
@SteveL-MSFT: Please see #10647
