### ISSUE TITLE
Distribution Support Request - CentOS 8

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#10632]
# Details of the Distribution

- Name of the Distribution: CentOS 8
- Version of the Distribution:
- [x] The version of the Distribution is supported for at least one year.
- [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.
- [x] The version of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

## Progress - For PowerShell Team **ONLY**

- [x] Docker image created
- [x] Docker image published
- [x] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] Lifecycle updated
- [ ] Documentation Updated

**Comment by adityapatwardhan** [comment]
Closing the issue since .NET does not support RHEL 8 / CentOS 8 yet.

**Comment by TravisEz13** [comment]
Verified with DotNet that CentOs 8 will be supported.

**Comment by adityapatwardhan** [comment]
Docker images and .rpm package are available since 7.0.0-rc.1.

**Comment by TravisEz13** [comment]
@adityapatwardhan Did you update the lifcycle and documentation?

**Comment by adityapatwardhan** [comment]
Missed that.

**Comment by joeyaiello** [comment]
Is `powershell-lts-7.0.1-1.centos.8.x86_64.rpm` the supported RHEL8 distribution as well? I just see we have one named for RHEL 7 and another for CentOS 8, not sure if those are differentiated on purpose.

If yes, given that CentOS / RHEL 8 is out and supported now, and supported by .NET Core, can we update this in the docs / README?

**Comment by TravisEz13** [comment]
the packages should be name rhel8 if it's for redhat and centos imho....

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/commit/57a071e9e626a78c6a49152bf82e1d5cb92fef49#diff-2326fb258876f2fb6efc0b952c932b21

**Comment by asinn826** [comment]
Hey @TravisEz13, do you know what the status of RHEL 8 support is? I notice it's not yet in the readme (https://github.com/PowerShell/PowerShell#get-powershell) so I figured I would ask here.

**Comment by TravisEz13** [comment]
The package is ready to be supported, it just hasn't been documented.   I have other work, before I can update the deployment script for packages.microsoft.com.  I'm not sure what the date is for that.

**Comment by TravisEz13** [comment]
Tracking RHEL in #12984 now, so we stick with one distro, per request
