### ISSUE TITLE
Get-Command should return full cmdletbinding details

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#10643]
PowerShell Functions and Cmdlets can be decorated with the `[CmdletBinding()]` attribute with additional properties being able to be defined including `SupportsShouldProcess`, `ConfirmImpact`, `DefaultParameterSetName`,`HelpURI`, `SupportsPaging`, `PositionalBinding`

Currently we do not output details on this other than it being True if set and we don't return it as false if it is not set and we should return it as either a simple `False` if not set at all or should return an object with the above properties as defined in the command

# Steps to reproduce

```powershell
Get-Command Disable-PNPDevice | Select -ExpandProperty CmdletBinding
```

# Expected behavior
![image](https://user-images.githubusercontent.com/6355225/65814950-c543f580-e1e0-11e9-9531-73a17f649487.png)
![image](https://user-images.githubusercontent.com/6355225/65814952-cd9c3080-e1e0-11e9-830d-34359e409f9b.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/6355225/65815001-68950a80-e1e1-11e9-8cab-1e839471fbe7.png)
![image](https://user-images.githubusercontent.com/6355225/65815007-78145380-e1e1-11e9-9ee3-744201d62db0.png)

# Environment data
Whilst the screenshot's are from ps v5.1 this also affects v7.0.0.preview.4

**Comment by ArmaanMcleod** [comment]
Looks like `System.Management.Automation.Functioninfo.CmdletBinding` is returning `bool`: https://github.com/PowerShell/PowerShell/blob/6a21bcc96766a32888bfc8a1aa24e30e21877b8f/src/System.Management.Automation/engine/FunctionInfo.cs#L270-L276

Thinking we can instead return `Dictionary<string, object>` and populate with above properties. 

I'm not sure if this would be categorized as a breaking change, given some people could be using this `bool` property, but I would agree that it would be very useful to add those CmdletBinding properties instead of just returning `True`. 

What do you think @iSazonov, @kilasuit? I can help PR this if needed.

**Comment by iSazonov** [comment]
> Thinking we can instead return Dictionary<string, object> and populate with above CmdletBinding properties.

It is public API and we can not change it. Also the API wrap internal API so it is not easy to get a new overload.
I think we need another approach to resolve the issue.

**Comment by ArmaanMcleod** [comment]
> > Thinking we can instead return Dictionary<string, object> and populate with above CmdletBinding properties.
> 
> It is public API and we can not change it. Also the API wrap internal API so it is not easy to get a new overload.
> I think we need another approach to resolve the issue.

What about adding a new member to the class? This sounds like an acceptable change to [Bucket 1](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#acceptable-changes):

> Adding new types, **new type members** and new cmdlets

Correct me if I'm misinterpreting something here 🙂

**Comment by iSazonov** [comment]
Yes, we could add new API.

Perhaps you could look PseudoBindingInfo class for start..

**Comment by SeeminglyScience** [comment]
Easiest would be something like this pseudo code:

```csharp
public partial class FunctionInfo
{
    public CmdletBindingAttribute? GetCmdletBinding()
    {
        ReadOnlyCollection<AttributeAst> attributes = ScriptBlock.Ast.Attributes?.Count > 0
            ? ScriptBlock.Ast.Attributes
            : ScriptBlock.Ast.ParamBlock?.Attributes;

        AttributeAst cmdletBindingAst = attributes
            .Where(a => a.GetReflectionAttributeType() == typeof(CmdletBindingAttribute))
            .FirstOrDefault();

        if (cmdletBindingAst is null)
        {
            return null;
        }

        return Compiler.GetAttribute(cmdletBindingAst);
    }
}
```

**Comment by kilasuit** [comment]
I should have been clearer in the issue as this only affects outputs for cmdlets, not functions, which means this only affects the `CmdletInfo` class & not `FunctionInfo`

I'd expect that whilst implied as it is a cmdlet, that this should also return details similarly to the second expected screenshot

**Comment by SeeminglyScience** [comment]
Note that for binary cmdlets it would be `CmdletAttribute` rather than `CmdletBindingAttribute`.  I agree that both should provide this information more readily though.

For binary cmdlets, there is at least a quick workaround with public API's:

```powershell
(gcm Get-Command).ImplementingType.GetCustomAttributes([Management.Automation.CmdletAttribute])
```

**Comment by ArmaanMcleod** [comment]
Thanks @SeeminglyScience. It seems like the `CmdletBindingAttribute` is attached to the scriptblock:

```csharp
public CmdletBindingAttribute GetCmdletBinding
{
    get
    {
        return this.ScriptBlock.CmdletBindingAttribute;
    }
}
```

Which gives:

```pwsh
PS C:\> (Get-Command Update-Disk).GetCmdletBinding

PositionalBinding       : False
DefaultParameterSetName : ByNumber
SupportsShouldProcess   : False
SupportsPaging          : False
SupportsTransactions    : False
ConfirmImpact           : None
HelpUri                 :
RemotingCapability      : PowerShell
TypeId                  : System.Management.Automation.CmdletBindingAttribute

```

**Comment by vexx32** [comment]
You can get that one today as well, although it's rather buried. Would be nice to get at it a bit more easily, but this does work for functions:

```powershell
(Get-Command $functionName).ScriptBlock.Attributes.Where{$_ -is [CmdletBinding]}
```
