### ISSUE TITLE
Support getting canonical filesystem paths with symlinks resolved, similar to the Linux realpath utility

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10640]
# Summary of the new feature/enhancement

Provide the ability to resolve a filesystem path to its canonical path, such as by adding a `-Canonical`  switch to the `Convert-Path` cmdlet.

In short: The idea is to allow you to answer the following question: 

**Given a (possibly relative, possibly PS-drive-based) file or directory path, where does the referenced file truly live, with symlinks, if any, resolved to their underlying target location, expressed as an absolute, native filesystem path?**

For instance, say you want to know the canonical path of file 
`/User Guides And Information/ENERGY STAR.pdf` on a Mac, which is `/Library/Documentation/User Guides and Information.localized/ENERGY STAR.pdf`
because `/User Guides And Information` is a directory symlink that targets
directory `/Library/Documentation/User Guides and Information.localized`

You could then do something like:

```powershell
# WISHFUL THINKING
PS> Convert-Path -Canonical '/User Guides And Information/ENERGY STAR.pdf'

/Library/Documentation/User Guides and Information.localized/ENERGY STAR.pdf
```

On at least some Linux distros, the `realpath` utility provides this functionality, and you can also use `readlink -f` (or `-m` or `-e`).

Note that this new feature would _complement_ the existing ability to inspect a symlink's (reparse point's) target via the `.Target` property of `Get-Item` / `Get-ChildItem` output, and also the proposed `.ResolvedTarget` property (see #13366 ).

The latter only operate on symlinks _themselves_, not on paths _based_ on them (paths with additional components); additionally, the `.Target` property may be a _relative_ path and `$null` if the input path isn't a symlink.
That is, `(Get-Item '/User Guides And Information').Target` works, because `/User Guides And Information` is _itself_ a symlink, but `(Get-Item '/User Guides And Information/ENERGY STAR.pdf').Target` is `$null`, because the file _inside_ the directory-symlink path itself isn't a symlink and therefore has no `.Target` property value.

# Proposed technical implementation details (optional)

* Windows: The [`GetFinalPathNameByHandle`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew) Windows API function provides this functionality.

* macOS, Linux: ~~haven't looked into it, but the GNU `readlink` utility implementation should provide pointers~~. The POSIX-mandated [`realpath()` function](https://pubs.opengroup.org/onlinepubs/9699919799/functions/realpath.html) provides this functionality (implemented as library functions on macOS and Linux; see `man 3 realpath`).

Decisions will also have to be made with respect to how final path components that don't exist yet are handled (i.e., a prefix of the path exists (an ancestral directory), but not the filename part or a relative subdirectory-based path), and how to handle _broken_ symlinks; these cases are reflected in the GNU `readlink` utility's related `-f` / `-e` / `-m` options.

Note that `Convert-Path` in its current form doesn't support (partially) non-existent paths, but it's about time we changed that too - see #2993

_Update_: Implementing this functionality as a .NET API that this feature could build on, in the form of a new `System.IO.Path.GetFullPath()` overload, has now been proposed: https://github.com/dotnet/runtime/issues/24271#issuecomment-670709364

**Comment by iSazonov** [comment]
@mklement0 Please look the old comment https://github.com/dotnet/coreclr/issues/2128#issuecomment-171879087 I think we need Core support. Currently Core team started .Net Core 5.0 design so it is good time to ask them for the feature.

**Comment by mklement0** [comment]
There's a CoreFx symlink API proposal, where I've suggested a new `System.IO.Path.GetFullPath()` overload for canonical path resolution: https://github.com/dotnet/runtime/issues/24271#issuecomment-670709364
