### ISSUE TITLE
Get-WinEvent is very very slow

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#10649]
![Screenshot_20190930-155333~2](https://user-images.githubusercontent.com/26913892/65860937-e7cf3d80-e39d-11e9-8882-95417d44cb0f.png)
![Screenshot_20190930-155325~2](https://user-images.githubusercontent.com/26913892/65860938-e7cf3d80-e39d-11e9-98f1-d80ca737fc98.png)

**Comment by iSazonov** [comment]
@he852100 The cmdlet does not do any heavy work. It use Windows API. In your example you read _all_ events then send _all events_ to pipeline - it is slow. Use filter parameters to get only needed events.

**Comment by he852100** [comment]
Get-eventlog can't find it, I decided to open it.

https://stackoverflow.com/questions/16731635/why-is-get-winevent-slower-than-get-eventlog-when-getting-events-after-a-date

But when querying the Security event log, query time was ~30 times longer.

**Comment by iSazonov** [comment]
@he852100 Get-EventLog cmdlet was deprecated and it is not present in PowerShell Core so we can not make direct comparison. You could make this on latest Windows PowerShell 5.1. I run the test and get that Get-WinEvent cmdlet ~20x faster than Get-EventLog.

If you have real business scenario where performance of Get-WinEvent cmdlet is critical we could measure this particular scenario.
