### ISSUE TITLE
Working directly with certain .NET types, such as Newtonsoft.Json's, is broken: implicit stringification

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10652]
Note: 

* I don't know whether / what other libraries are affected, and whether Newtonsoft.Jsonis an unusual one.

* The bug also exists in Windows PowerShell.

* The error is ultimately the same as in #10650: `Target type System.Collections.IEnumerator is not a value type or a non-abstract class. (Parameter 'targetType')` - note how the type name is an _interface_, not a _class_.

The problem in a nutshell: when `[JValue]` instances are implicitly converted to strings, they stringify to the _empty string_.

By contrast, calling `.ToString()` explicitly works as expected.

# Steps to reproduce

```powershell
# Parse JSON text into a [JObject] instance.
$obj = [Newtonsoft.Json.JsonConvert]::DeserializeObject('{ "foo": "bar"  }')

# Works as expected:
# Call .ToString() explicitly on the `.foo` property, whose value is a [JValue] instance.
$obj.foo.ToString()

# Problem 1: default output formatting yields '' interactively,
#                   and fails with Out-Default
{ $obj.foo | Out-Default } | Should -Not -Throw

# Problem 2: string interpolation yields ''
"$($obj.foo)" | Should -Not -BeNullOrEmpty
```

# Expected behavior

All tests should succeed.

# Actual behavior

Tests 2 and 3 fail.

* Test 2 fails due to an exception, which points to the underlying problem:

```none
Target type System.Collections.IEnumerator is not a value type or a non-abstract class. 
(Parameter 'targetType').
```

* Test 3 fails, because (as with interactive output), `$foo.bar` stringifies to the _empty string_.

# Environment data

```none
PowerShell Core v7.0.0-preview.4 on macOS 10.14.6
Windows PowerShell v5.1.18362.145 on Microsoft Windows 10 Pro (64-bit; Version 1903, OS Build: 18362.295)
```

**Comment by iRon7** [comment]
Just FYI: I came across a similar issue.
(My goal was to build a PowerShell `Test-Yaml` cmdlet, but first needed to be able to simulate the `Test-Json` cmdlet with `[Newtonsoft.Json]` .net classes):

```PowerShell
$Json = @'
{
  "name": "James",
  "hobbies": [".NET", "Blogging", "Reading", "Xbox", "LOLCATS"]
}
'@

$JsonSchema = @'
{
  "description": "A person",
  "type": "object",
  "properties":
  {
    "name": {"type":"string"},
    "hobbies": {
      "type": "array",
      "items": {"type":"string"}
    }
  }
}
'@

# Test-Json -Json $Json -Schema $JsonSchema

$Schema = [Newtonsoft.Json.Schema.JsonSchema]::Parse($JsonSchema)
$JObject = [Newtonsoft.Json.Linq.JObject]::Parse($Json)
$JObject.IsValid($Schema)

OperationStopped: C:\Users\Gebruiker\GDrive\Scripts\PowerShell\_JIO\Yaml\Test-Yaml.ps1:31
Line |
  31 |  $JObject.IsValid($Schema)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Target type System.Collections.IEnumerator is not a value type or a non-abstract class. (Parameter 'targetType')
```

```
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by gregsdennis** [comment]
The JSON Schema implementation has been recently updated to JsonSchema.Net and is available in the latest Powershell snapshot. Please retest this to see if it is still a problem.

@iRon7 you may have a look at another one of my packages [Yaml2JsonNode](https://www.nuget.org/packages/Yaml2JsonNode) which performs YamlDotNet -> JsonNode conversions.  Then you can probably invoke `Test-Json` directly.
