### ISSUE TITLE
Out-GridView on macOS makes it difficult to select objects for the pipeline via -PassThru 

### ISSUE THREAD

**Issue by yobyot** [PowerShell/PowerShell#10663]
Consider the following cmdlet entry:

`Get-AzSubscription | Where-Object -Property State -eq "Enabled" | Out-GridView -PassThru | Select-AzSubscription`

With `Out-GridView`, it's should very easy to graphically select which subscription object from the collection you wish to pass to `Select-AzSubscription`. The code works, but the UI needs to make it clear which row is selected.

For example, it's nearly impossible to tell which row is selected in this image: 
![ogvselection](https://user-images.githubusercontent.com/14332263/65975283-624e9a80-e43c-11e9-9af1-c204a5f90e30.png)
(Sorry, I had to obscure the GUIDs and names.) But the point can still be seen: one of these objects is selected but it's almost impossible to tell.

The colors in the macOS `OGV` UI need adjusting to clearly delineate which object is selected.

**Comment by mklement0** [comment]
`Out-GridView` is not part of this repo; it looks like you're using the https://github.com/PowerShell/GraphicalTools implementation, so I suggest reporting the issue there.

**Comment by yobyot** [comment]
@mklement0  Thanks for the pointer to the correct repo. I've re-posted the issue there.
