### ISSUE TITLE
Tab complete on a command with dash suggests a function that has a dash in the name

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#10677]
# Steps to reproduce

```powershell
function a-b {}
foo -<tab>
```

# Expected behavior

```none
Nothing since `foo` doesn't exist
```

# Actual behavior

```none
foo a-b
```

Regression from WinPS5.1.  Repros in 6.2 and 7 Preview4.

**Comment by kilasuit** [comment]
This doens't repro on my 5;1.18990.1 win ten box

**Comment by SteveL-MSFT** [comment]
@kilasuit correct, this is a regression from WinPS5.1 meaning it worked there and now it doesn't
