### ISSUE TITLE
The current UI culture isn't respected - messages continue to be displayed in English

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10679]
# Steps to reproduce

* Run on Windows.
* Make sure that `Deutsch (Deutschland)` (German (Germany) is installed as a Windows UI (display) language via the Windows 10 Settings application.

```powershell
[cultureinfo]::CurrentUICulture = 'de-DE'; Get-Item nosuch 2>&1 | Should -match 'nicht gefunden'
```

# Expected behavior

The test should succeed.

# Actual behavior

The test fails:

```none
Expected regular expression 'nicht gefunden' to match Cannot find path 'C:\Users\User\nosuch' because it does not exist., but it did not match.
```

That is, the error message was still emitted in English.

This is a regression of sorts from Windows PowerShell, where the above test succeeds.
However, Windows PowerShell's problem is that `[cultureinfo]::CurrentUICulture` is reset after each command line.

# Environment data

```none
PowerShell Core 7.0.0-preview.4
```

**Comment by iSazonov** [comment]
I am not sure that localized help was published. Debug shows internall exception and fallback to en-US.

**Comment by mklement0** [comment]
The test actually tests error messages, not help content.

I naively assumed that since localized DLLs are present in `$PSHOME` (although on Unix platforms there are only 2) that at least startup messages, error messages, ... would already be localized.

Is this being tracked somewhere? Is there a roadmap?

**Comment by mklement0** [comment]
:) Thanks, @iSazonov  - I'm closing this.
