### ISSUE TITLE
$MyInvocation.InvocationName unhelpful with & invocation

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#10676]
Motivated by https://github.com/mikebattista/PowerShell-WSL-Interop/issues/17.

```powershell
function Test-MyFunction
{
    $MyInvocation.InvocationName
}

Set-Alias funky Test-MyFunction
$funkVar = 'funky'

Test-MyFunction                         # 'Test-MyFunction'
& 'Test-MyFunction'                     # '&'
funky                                   # 'funky'
& 'funky'                               # '&'
& $funkVar                              # '&'
& (Get-Item variable:funkVar).Value     # '&'
```

Most of these are very unhelpful.

In the cases where `&` is used, having the actual token representing the command invoked would be much more useful.

In the case where an expression is used, it would be very useful to know what that expression's value has been evaluated to.

It would also be nice in the case of an alias to know what alias was used.

Essentially, more information about the call-time context, like a resolution path/stack, would enable this to be much more helpful.

**Comment by iSazonov** [comment]
Maybe related #10477

**Comment by SeeminglyScience** [comment]
If there are changes being made to that property, there's another piece of functionality that should be kept in mind:

```powershell
$ExecutionContext.InvokeCommand.PreCommandLookupAction = {
    param($source, $e) end {
        if ($e.CommandName -notlike 'Custom*') {
            return
        }

        $e.CommandScriptBlock = { $MyInvocation.InvocationName }
        $e.StopSearch = $true
    }
}

CustomThing
# returns: CustomThing

CustomOtherRandomThing
# returns; CustomOtherRandomThing
```
