### ISSUE TITLE
Only partial help available on Linux

### ISSUE THREAD

**Issue by mike632t** [PowerShell/PowerShell#10671]
After updating help only partial help is available - although no errors are shown during the update process (running these commands as root or with '-Scope CurrentUser' seems to make no difference).

    PS /home/user> $PSVersionTable

    Name                           Value
    ----                           -----
    PSVersion                      6.2.2
    PSEdition                      Core
    GitCommitId                    6.2.2
    OS                             Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13)
    Platform                       Unix
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0

    PS /home/user> Update-Help
    PS /home/user>                                                                                                                    
    PS /home/user> Get-Help Update-Help   
    NAME
    Update-Help
    SYNTAX
        Update-Help [[-Module] <string[]>] [[-SourcePath] <string[]>] [[-UICulture] <cultureinfo[]>] [-FullyQualifiedModule 
        <ModuleSpecification[]>] [-Recurse] [-Credential <pscredential>] [-UseDefaultCredentials] [-Force] [-Scope {CurrentUser | 
        AllUsers}] [-WhatIf] [-Confirm] [<CommonParameters>]
        
        Update-Help [[-Module] <string[]>] [[-UICulture] <cultureinfo[]>] [-FullyQualifiedModule <ModuleSpecification[]>] 
        [-LiteralPath <string[]>] [-Recurse] [-Credential <pscredential>] [-UseDefaultCredentials] [-Force] [-Scope {CurrentUser | 
        AllUsers}] [-WhatIf] [-Confirm] [<CommonParameters>]

    ALIASES
        None

    REMARKS
        Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.
            -- To download and install Help files for the module that includes this cmdlet, use Update-Help.
            -- To view the Help topic for this cmdlet online, type: "Get-Help Update-Help -Online" or
               go to https://go.microsoft.com/fwlink/?LinkID=210614.

    PS /home/user>

**Comment by Neurognostic** [comment]
I am seeing the same behavior on both [powershell-preview-bin [7.0.0-preview.6-1]](https://aur.archlinux.org/packages/powershell-preview-bin) and [powershell-bin [6.2.3-1]](https://aur.archlinux.org/packages/powershell-bin/). 

`Update-Help` exits immediately without any errors no matter what parameter combinations I try. Running `pwsh` with `sudo` produces the same results. There are no Help files in `$env:XDG_DATA_HOME`.

**Comment by jrydval** [comment]
```
PS Variable:/> pwsh -c "Update-Help -Force"
PS Variable:/>
```

Update-Help returns immediately, no error and no detailed help available. I am able to reproduce the same behaviour on 2 MacOS machines - first with PS installed from pkg and second where the PS was installed from a tar file.

**Comment by iSazonov** [comment]
@sdwheeler Could you please comment the issue?

**Comment by sdwheeler** [comment]
Update-Help works in rc2. I haven't tested in rc1.

**Comment by yecril71pl** [comment]
Still [reproducible](https://github.com/yecril71pl/PowerShell-Docs/runs/945716150) as of 7.0.3 on Ubuntu 20,  Please reopen.
