### ISSUE TITLE
"Rouge" filenames that contain a backslash break automatic globbing for native commands on macOS and Linux

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10682]
Note: This case is covered by catch-all issue #9244

The presence of a filename containing a `\` that matches a wildcard pattern causes native globbing to fail quietly (and pass the pattern through  as-is, as if nothing matched).

Note that `\` is a legal filename character on Unix-like platforms.

# Steps to reproduce

On **macOS** and **Linux**:

```powershell
touch 'a\b'
/bin/echo * | Should -Not -Be '*'
rm 'a\b'
```

# Expected behavior

The test should pass.

# Actual behavior

The test fails, because `*` is echoed as-is - no expansion to matching filenames occurs.

 Windows is not affected, because native globbing isn't applied there).

# Environment data

```none
PowerShell Core v7.0.0-preview.4 on macOS 10.14.6
PowerShell Core v7.0.0-preview.4 (7.0.0-preview.4) on Ubuntu 18.04.3 LTS
```

**Comment by iSazonov** [comment]
> Note: This is a regression.

Which version?

Does it work on Linux?

**Comment by mklement0** [comment]
The version is stated in the OP, and I originally thought it affects macOS only - but (a) that isn't true and (b) the problem is much more specific - please see the updated title and OP.

**Comment by mklement0** [comment]
Never mind: I just realized that all backslash-escaped woes are covered in #9244, though I'll add a note there about this specific scenario.
