### ISSUE TITLE
Feature Request - Support AsJob switch in both parameter sets

### ISSUE THREAD

**Issue by pacificpleb** [PowerShell/PowerShell#10685]
# Summary of the new feature/enhancement

Currently you cannot do the following due to the cmdlets parameter sets:
restart-computer -ComputerName Server.contoso.com -wait -for PowerShell -Force -AsJob

BUT you can wrap it in a start-job scriptblock and it works as expected:
start-job -scriptblock { restart-computer -ComputerName satisbrt001 -wait -for PowerShell -Force }

**Comment by mklement0** [comment]
Note that you can now simply append `&` to any command / pipeline in order to run it as a job - it is like an implicit `Start-Job` call, and as such it doesn't rely on individual commands' `-AsJob` parameters.

```powershell
$job = restart-computer -ComputerName Server.contoso.com -wait -for PowerShell -Force &
 ```

**Comment by discombobulater** [comment]
Which version does this apply to?  On v5.1 this does not work, gives error
"the ampersand character is not allowed" even running as admin.

**Comment by mklement0** [comment]
@discombobulater: Yes, it's a PowerShell _Core_-only feature (which is what this repo is about; note that _Windows PowerShell_ will see no new features).
