### ISSUE TITLE
pwsh on debian buster - buffers problem in shell mode

### ISSUE THREAD

**Issue by gvcgael** [PowerShell/PowerShell#10699]
# Steps to reproduce

Run `pwsh` on Debian Buster (Debian 10) and starts to type commands.

# Expected behavior

pwsh is usable, user can type commands and read outputs.

# Actual behavior

There seems to be a problem with the buffers. Typing commands and running them does not work after the first one. Like if the buffers get unsynchronized with the inputs/outputs of the terminal. 

# Environment data

I reproduce this problem with a snap install of pwsh and with the tar.zf archive. 

```
PS /opt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@gvcgael Can you remove PSReadline module ( Remove-Module PSReadline ) and test again?

**Comment by gvcgael** [comment]
Ok, it seems that the problems comes from my setup.

I connect from Git bash via SSH to my Debian buster VM. In this case, I get these buffers problem.

Using directly the console, powershell behaviour is ok.

Any idea what could be the cause ?

**Comment by iSazonov** [comment]
I guess the scenario was never tested.
At first we should check that C# API works right in the scenario. You could create simple C# application and check that Console.ReadKey() and Readline() methods work well.

**Comment by gvcgael** [comment]
Ok, it seems that I was wrong. It comes from the fact that I run git bash on Visual Studio Code.

Outside of studio code, it behaves properly. So it seems to come from the terminal integrated in VSC.

**Comment by iSazonov** [comment]
> So it seems to come from the terminal integrated in VSC.

@TylerLeonhardt In which repository should we track this?

**Comment by TylerLeonhardt** [comment]
@gvcgael are you using the "PowerShell Integrated Console" that is exposed via the PowerShell extension for VSCode?

Or are you using VSCode's integrated terminal which is just running pwsh/powershell?

You can tell by looking at the little drop down at the top right of the terminal pane.

**Comment by gvcgael** [comment]
Hello,

I'm using VSCode Git bash integrated terminal, from which I connect to the VM where I run pwsh.
