### ISSUE TITLE
Updating PowerShell on NuGet

### ISSUE THREAD

**Issue by onovotny** [PowerShell/PowerShell#10690]
PowerShell Core is on NuGet, packaged as a global tool. The current published version there is 6.2.2. Can 6.2.3 be pushed there, along with the PowerShell 7 previews?

Thanks

**Comment by vexx32** [comment]
/cc @SteveL-MSFT @adityapatwardhan 

Do we need to add additional CI build triggers to publish onto NuGet as a global tool when we do a new stable and/or preview release?

**Comment by SteveL-MSFT** [comment]
Looks like this was missed as a (currently) manual step in our release pipeline.  @adityapatwardhan will update it.

**Comment by adityapatwardhan** [comment]
@onovotny thanks for reporting this. `6.2.3` was just released. It should be available shortly. Currently, there are no plans to publish global tool for 7 preview builds.

**Comment by onovotny** [comment]
Thanks. Will the final non-preview build of 7 be published as a tool? (it's a super convenient mechanism that doesn't require admin rights).

**Comment by adityapatwardhan** [comment]
Yes, when the final build of PowerShell 7 is released, it will be released as a global tool.
