### ISSUE TITLE
Get-Help -Online goes to PowerShell 5 version of help

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10705]
# Steps to reproduce

```powershell
get-help get-command -online
```

# Expected behavior

Should open the help for the current version of PowerShell

# Actual behavior

Opens:  https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Get-Command?view=powershell-5.0

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by peetrike** [comment]
just for a reference:
Get-Command Get-Command | Format-List HelpUri
returns same link in PS 5.1, 6.2.3 and 7.0.0-preview 6: https://go.microsoft.com/fwlink/?LinkID=113309, which redirects to correct help location

But link returned by:
Get-Command Test-Connection | Format-List HelpUri
(again same for all versions: https://go.microsoft.com/fwlink/?LinkID=135266) redirects to https://docs.microsoft.com/en-us/previous-versions/powershell/module/Microsoft.PowerShell.Management/Test-Connection?view=powershell-3.0

It seems that some redirect links point to wrong place...

**Comment by vexx32** [comment]
@TravisEz13 shouldn't this be an issue in the PowerShell-Docs repo? 🙂

**Comment by TravisEz13** [comment]
The fwlinks live in this repo and there has already been a PR to fix this...

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/commit/3923ca172854b8f3b00dcd02b0f1829917758f10
