### ISSUE TITLE
Every interactive action, console window will change window size then restore.

### ISSUE THREAD

**Issue by Twilightlee** [PowerShell/PowerShell#10719]
**### And render text twice with different font.**

Windows PowerShell Core v6.2.2.0 running under windows 10 64bit

I set console window font to **Consolas 18**

When I type **help** in powershell console window, it's show text like snapshot below:

![p1](https://user-images.githubusercontent.com/8230703/66264224-ef766280-e833-11e9-94bc-6728c60e3199.png)

Then  I pressed **Ctrl-C** , it's show text like snapshot below, it seemed re-render text with my font setting :

![p2](https://user-images.githubusercontent.com/8230703/66264228-f7ce9d80-e833-11e9-8ae8-7f280a72690f.png)

Is PowerShell Console window have two separate render system?

**Comment by daxian-dbw** [comment]
This is a known issue tracked by https://github.com/PowerShell/PSReadLine/issues/964.
There are a few duplicates such as https://github.com/PowerShell/PSReadLine/issues/1198 and https://github.com/PowerShell/PowerShell/issues/9532

See https://github.com/PowerShell/PSReadLine/issues/964#issuecomment-570744871 for my investigation on this issue.
