### ISSUE TITLE
Unable to use copy/paste in WSL bash.

### ISSUE THREAD

**Issue by ralic** [PowerShell/PowerShell#10711]
I am currently using Windows version 1903. 
After installing the Windows PowerShell v6+, the new PowerShell console window does not support Control-V paste after entering WSL(Linux Subsystem) bash.
The original PowerShell console does support bash and hotkey copy/paste.

# Steps to reproduce

1. Installed Powershell using following command
```
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
```
2. Type bash to enter Ubuntu in windows.
3. Try to **use hotkeys, such as Ctrl-V or Ctrl-P**  OR **right-click in the window.**

# Expected behavior

Paste information copied.

# Actual behavior

No response in the console.
See attached photo for info.
```
https://drive.google.com/file/d/10NJyFhcM-XC4G5FQL4NjzkYeM91SM0sl/view
```
![image](https://user-images.githubusercontent.com/22290914/66306365-e14f4180-e91a-11e9-87eb-f655a20e3f67.png)

# Environment data

```none

```
See the photo link above.
Note: Github's markdown editor's URL does not allow me to use the photo from google drive as a link. Please copy/paste to check to photo.

**Comment by daxian-dbw** [comment]
After `bash` starts up, you are in `bash` and `pwsh` won't handle your key input anymore. The hotkey not working means bash don't support them.

**Comment by ralic** [comment]
> After `bash` starts up, you are in `bash` and `pwsh` won't handle your key input anymore. The hotkey not working means bash don't support them, and this has nothing to do with `pwsh`.

No, hotkeys works in the PowerShell shipped with Windows10.

**Comment by iSazonov** [comment]
@daxian-dbw The question is that pwsh run in WSL but (1) Ctrl-C/P do not work, (2) right click doesn't work.

@ralic Install latest PSReadline version (Beta5) and try Ctrl-C/P.

**Comment by daxian-dbw** [comment]
> The question is that pwsh run in WSL but (1) Ctrl-C/P do not work, (2) right click doesn't work.

@iSazonov The screenshots shows starting bash from pwsh, not running pwsh in WSL.
