### ISSUE TITLE
The ternary operator should support inline comments but not blank lines

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10717]
# Steps to reproduce

```powershell
$true ?




'It is true.'




:





'Nope, it''s false!'
```

# Expected behavior

A parser error should be raised. Comments should be supported, but there is no need to allow blank lines in ternary. That just opens the door for sloppy code.

# Actual behavior

```none
It is true.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
But PowerShell is a "whitespace insignificant" language (unlike Python), well, except for newlines.  Someone could do the following too and like you, I would not recommend that folks use this style:
```
>> if ($true) {
>>                                                                                                                      
>>
>>
>> 'It is true.'
>>                                                                                                                      
>>
>>
>> } else {
>>                                                                                                                      
>>
>>
>> 'Nope, it''s false!'
>> }                                                                                                                    
It is true.
```
But I would not go so far as to want to change the language's whitespace handling.  This is why we have style guidelines and tools like PSScriptAnalyzer to help folks enforce their chosen style.

Also, what exactly do you mean by inline comments?  Comments like this work:

![image](https://user-images.githubusercontent.com/5177512/66273195-f058c580-e82e-11e9-9a83-edc91cbd42d2.png)

As well as: 

![image](https://user-images.githubusercontent.com/5177512/66273206-226a2780-e82f-11e9-982c-9def2750f960.png)

**Comment by vexx32** [comment]
I think @KirkMunro is coming from the perspective of:

1. This is an operator
2. All existing operators do not permit entire blank lines between their output (try `5 + <enter><enter>`; a parsing exception is raised)
3. Therefore, this operator should behave the same way existing operators do.

That said, if this operator _did_ allow comment-only lines in the midst of the arguments, it would also be the only operator to allow it. Try the above example and insert a comment after the first newline, then try to continue writing something else on another newline after that; same deal, instant parsing exception.

**Comment by rkeithhill** [comment]
?? 
![image](https://user-images.githubusercontent.com/5177512/66274845-c956bf80-e83f-11e9-95b7-05ce3e6ddc18.png)

Or put this in a ps1 file and run it:
```
5 +

5 -

10
```
Runs just fine.

**Comment by vexx32** [comment]
_Very_ interesting.

What are you running on in terms of PSReadline version, PS version, and OS?

W10, PSReadLine 2.0.0-beta5, and pwsh7-preview4 that doesn't work in VS Code or the Windows Terminal.... very odd. Though I do see it work from a file and from the default PowerShell terminal.

OK, gonna chalk that up to a PSReadline bug. Objection withdrawn!

**Comment by rkeithhill** [comment]
Well ... this is a trick/workaround that I discovered a while back.  Start your command with `@'` then edit the following lines as desired. Before executing, get rid of the `@'` e.g.:
When you start the multiline command:
```
10-06 13:49:18 14ms 63> @'                                                                                              
>> 5 +
>>
>>
>>
>> 5
```
Then right before executing:
```
10-06 13:49:18 14ms 63> 
>> 5 +
>>
>>
>>
>> 5
```

**Comment by vexx32** [comment]
Interesting. Filed issue on PSRL to see if we can get to the bottom of it one way or another: https://github.com/PowerShell/PSReadLine/issues/1088

Thanks for the workaround!

**Comment by KirkMunro** [comment]
@rkeithhill: By inline comments, I meant regular comments like you showed in your example. I expect those to work when I wrap commands or statements.

For the blank lines though, just because existing keywords and operators allow blank lines (which IMHO they shoud never have in the first place) doesn't mean (to me at least) that new syntax should continue to persist such things when they serve no purpose.
