### ISSUE TITLE
Add a .NET API to add native completers

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#10722]
# Summary of the new feature/enhancement

Currently there are ways to register a scriptblock as a completer with `Register-ArgumentCompleter`, and on cmdlets it's possible to use the `[ArgumentCompleter()]` attribute to specify an `IArgumentCompleter` for a parameter. But there's no way to specify a completer for an ordinary command that I know of that doesn't involve executing a scriptblock.

By this I mean, you can use `Register-ArgumentCompleter` or you can use override `TabCompletion2`, but I'd really like a nicer hook for:

- General completions
- Command completions
- Native command completions, especially

**Comment by SeeminglyScience** [comment]
I'd love to see more ways of extending completion!  One of the biggest things that's always stopped me from working on anything to extend general completion is that it's all or nothing.  If you override `TabExpansion2`, then anyone else trying to do the same will completely override you.  I'd love to see something like an interface that can be registered in the engine to incrementally augment completion. Something like:

```csharp
public interface ICompletionExtension
{
    IEnumerable<CompletionResult> CompleteComment(CompletionContext context);

    IEnumerable<CompletionResult> CompleteMember(CompletionContext context);

    IEnumerable<CompletionResult> CompleteCommandParameter(CompletionContext context);

    IEnumerable<CompletionResult> CompleteCommandArgument(CompletionContext context);

    // Other cherry picked methods from CompletionCompleters/CompletionAnalysis here.
}

public class CompletionEngine
{
    public void RegisterCompletionExtension(ICompletionExtension extension);

    public void UnregisterCompletionExtension(ICompletionExtension extension);

    // Mirroring CommandCompletion.CompleteInput
    public CommandCompletion CompleteInput(
        Ast ast,
        Token[] tokens,
        IScriptPosition positionOfCursor,
        Hashtable options);
}

public partial class EngineIntrinsics
{
    public CompletionEngine Completion { get; }
}
```

**Comment by iSazonov** [comment]
I hope we combine this in one engine with #10741.

**Comment by iSazonov** [comment]
Thinking more about the request I believe it is an edge case. Can you show other use cases (besides UnixCompleters)? 

If we compare PowerShell and Bash design both do the some - register a script for completion of a command. So who else would need a rapper like UnixCompleters?

**Comment by rkeithhill** [comment]
@iSazonov Wouldn't this feature apply to any completions that someone wants to implement in a binary (C#-based) module?

**Comment by iSazonov** [comment]
@rkeithhill I want to see examples. I only see UnixCompleters scenario and it is very specific, edge scenario. PowerShell already implement completions and API for customizations. We need to be sensitive to what exactly we need to add if necessary.

**Comment by SeeminglyScience** [comment]
@iSazonov that's gonna be hard to show.  Any time I've had a similar idea I've thrown it away once I got to the "oh I have to make 100 script block wrappers" step because it felt real dirty.

**Comment by SeeminglyScience** [comment]
Also probably wouldn't be **too** hard to add.  Might be able to get away with switching the internal dictionary to store `Func<string, CommandAst, int, object>` and generating a thin wrapper delegate around registered script blocks.

**Comment by iSazonov** [comment]
On the other hand, small and simple scripts can be more attractive (easy to write, easy to debug) than one huge script or code.

**Comment by SeeminglyScience** [comment]
Yeah for sure it can be.  Sometimes code is complicated though 🤷

**Comment by iSazonov** [comment]
Thanks for confirmation my thoughts.

I also feel that sometimes it is convenient for authors of binary modules to write a completer on C# than a script block.
For them, we could enhance the Register-ArgumentCompleter cmdlet and allow registering code that implements a new interface.

**Comment by rjmholt** [comment]
> enhance the Register-ArgumentCompleter cmdlet 

Still requires running a pipeline though. That's too slow for something executed in a profile or for many commands. We need a lightweight registration mechanism that doesn't require a runspace, the pipeline thread or parameter binding.

**Comment by iSazonov** [comment]
> Still requires running a pipeline though.

If you agreed that the cmdlet could register a binary completer our next step would be to recognize the need to add new public API to do this.

**Comment by rjmholt** [comment]
> If you agreed that the cmdlet could register a binary completer 

Oh, yes, absolutely; `Register-ArgumentCompleter` should support a parameter set that takes a completer object instead of a ScriptBlock

**Comment by iSazonov** [comment]
So we could discuss follow signatures:
```powershell
Register-ArgumentCompleter -Command <string[]>  -CompleterType [Custom type with ICommandCompleter]
Register-ArgumentCompleter -ParameterName <string> [-Command <string[]>]  -CompleterType [Custom type with ICommandCompleter]
```

```c#
public void RegisterArgumentCompleter(string commandName, ICommandCompleter completer);
public void RegisterArgumentCompleter(string[] commandName, ICommandCompleter completer);
public void RegisterArgumentCompleter(IEnumerable<string> commandName, ICommandCompleter completer);

public void RegisterArgumentCompleter(string? commandName, string parameterName, IArgumentCompleter completer);
public void RegisterArgumentCompleter((string? commandName, string parameterName) commandparameterPair, IArgumentCompleter completer);
public void RegisterArgumentCompleter(IEnumerable<string?, string> commandparameterPair, IArgumentCompleter completer);


```
