### ISSUE TITLE
With variable assignment, PowerShell can’t reset color when colored message appears in stderr

### ISSUE THREAD

**Issue by jiasli** [PowerShell/PowerShell#10729]
# Steps to reproduce

Write a Python script color.py using [colorama](https://github.com/tartley/colorama):

```py
import sys
from colorama import Fore, init, deinit
 
init()
sys.stderr.write(Fore.RED + "something" + Fore.RESET)
print("deinit")
deinit()
print("python end")

```
Run in VS Code PowerShell terminal (this also happens with PowerShell's default terminal):
```powershell
python .\color.py 
$a = python .\color.py 
```

# Expected behavior

Color is reset correctly. 

# Actual behavior

Without variable assignment, it works as expected. But with `$a=`, PowerShell can’t reset its color and the color is set to black instead.

![Screenshot_25](https://user-images.githubusercontent.com/4003950/66366994-ebc61580-e9c4-11e9-9764-8ef29a3257b9.png)

# Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}        
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
@jiasli it seems that the behavior is consistent between PowerShell and cmd and that python is setting the console foregroundcolor.  In which case, it seems that the shell should not simply set it back.

```cmd
python color.py > out
```

When redirecting either in PowerShell or cmd, the foreground color (as well as the background color) is changed to black.  A user using a native command that changes the console colors should be respected.  Looks like colorama is calling the win32 api SetConsoleTextAttribute and probably not setting it back correctly.
