### ISSUE TITLE
REGRESSION: Remove-Item Junction no longer works

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#10747]
When creating junction points and removing them, Remove-Item in PowerShell 7 does not work, and produces an incomprehensible error:

> Remove-Item : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

![image](https://user-images.githubusercontent.com/192942/66512538-2bfdc480-eaa7-11e9-8ea5-d699b3fb7228.png)

See Also: [Regression: Get-ChildItem modes are wrong with junctions](https://github.com/PowerShell/PowerShell/issues/10748) #10748 
See Also: [Fix Remove-Item <symbolic link to directory>](https://github.com/PowerShell/PowerShell/issues/621) #621

# Steps to reproduce

```powershell
# Create a junction point
# E.g. Install-Package from the NuGet provider with a `-Destination`
Register-PackageSource -Name NuGet -Trusted -ProviderName NuGet -Location https://api.nuget.org/v3/index.json -Force -ForceBootstrap
Install-Package YamlDotNet -Source NuGet -Destination . -Force -ExcludeVersion

# Review the created junction point 
# PowerShell 7 pre 4 initially displays it as a directory, not a junction
Get-ChildItem YamlDotNet*

# Attempt to remove the directory
# This produces the error:
#    Remove-Item : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Remove-Item YamlDotNet -Recurse
```

# Expected behavior

- `Remove-Item` should remove the junction
- Failing that, it should _at least_ work as well as Windows PowerShell 5
  - It should produce an error message like:
    > Remove-Item : .\YamlDotNet is an NTFS junction point. Use the Force parameter to delete or modify this object.
  - `Remove-Item YamlDotNet -Force -Recurse` should remove the junction

# Actual behavior

It's impossible to remove this with PowerShell Core 7 due to the FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can not repo with latest build. I installed the package to c:\temp and removing works well.

**Comment by iSazonov** [comment]
@SteveL-MSFT Do you see the regression?

**Comment by iSazonov** [comment]
I guess it is again OneDrive related. It is tracked in https://github.com/PowerShell/PowerShell/issues/11721
