### ISSUE TITLE
PowerShell recreates the inaccessible folder immediately after removed it

### ISSUE THREAD

**Issue by mkht** [PowerShell/PowerShell#10743]
After running Get-ChildItem with Select-Object on a folder, I noticed that deleting that folder would recreate the inaccessible folder.

# Steps to reproduce
This is a sample script to reproduce the issue.
```powershell
$ErrorActionPreference = 'Stop'
$null = New-Item C:\j\k\l -ItemType Directory -Force -Verbose
Get-ChildItem C:\j\k | Select-Object -First 1
# Get-ChildItem C:\j\k    #If I don't use the Select-Object, the issue will not occurs.
Remove-Item C:\j\k -Recurse -Force -Verbose
Start-Sleep -Seconds 3
Get-ChildItem C:\j\k -Verbose
```

# Expected behavior
The folder `C:\j\k` is removed. and PS throws `ItemNotFoundException`

# Actual behavior
The PS throws `UnauthorizedAccessException`.
And The folder `C:\j\k` is remained and inaccessible even if I have administrators privilege.
( More precisely, it seems that the folder is recreated immediately after it has been deleted. )
```none
Get-ChildItem : Access to the path 'C:\j\k' is denied.
At C:\Users\Administrator\Desktop\Untitled1.ps1:6 char:1
+ Get-ChildItem C:\j\k -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\j\k:String) [Get-ChildItem], UnauthorizedAccessException
+ FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
```

# Environment data
 I've confirmed that the issue occurs in below environments.
* Windows 7 Professional SP1 x86 with Windows PowerShell 5.1
* Windows 7 Professional SP1 x86 with PowerShell Core 6.2.3
* Windows 10 Pro Version 1809 x64 with Windows PowerShell 5.1
* Windows 10 Pro Version 1809 x64 with PowerShell Core 6.2.3
* Windows 10 Pro Version 1903 x64 with Windows PowerShell 5.1
* Windows 10 Pro Version 1903 x64 with PowerShell Core 6.2.3

# Screen capture
![snippet2](https://user-images.githubusercontent.com/25482642/66486202-14453100-eae5-11e9-8383-b42169703a84.gif)

**Comment by iSazonov** [comment]
I can not repro.
