### ISSUE TITLE
Some of the accented AltGr characters don't work - Polish (Programmers) keyboard layout

### ISSUE THREAD

**Issue by marcinsmialek** [PowerShell/PowerShell#10742]
# Steps to reproduce

- Set keyboard to Polish (Programmers)
- Launch PowerShell (6.2.3 or 5.1) as stand-alone, or in Windows Terminal
- Type:
```none
AltGr+a
Shift+`, a
AltGr+o
Shift+`, o
```

# Expected behavior

```none
ą
ą
ó
ó
```

# Actual behavior

```none
[nothing]
[nothing]
ó
ó
```

# Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
My main machine runs Windows 1909 (with Windows Terminal 0.5.2762.0), but I also tested it on Windows 1903, with both PowerShell 5.1, and Core 6.2.3. The results were the same. This issue started appearing recently for me, maybe at the time the new Windows Terminal was released. Unfortunately, I can't give any time, as I wasn't using accented letters in terminal for some time. A few of my colleagues experience it too, while others don't. My Windows installs are English, with added Polish input and regional settings. For both languages, I use Polish (Programmers) layout.

# Remarks

For some reason, accented o works fine (ó)

List of scenarios I tried, and if accents work or not:
* [x] cmd.exe / conhost.exe (no PowerShell)
* [ ] Launch cmd.exe / conhost.exe window, and inside of it, launch PowerShell / PowerShell Core, type
* [ ] powershell.exe / pwsh.exe
* [ ] Windows Terminal - PowerShell / PowerShell Core
* [x] Launch PowerShell PowerShell Core window, launch cmd, type
* [x] PowerShell ISE
* [x] Visual Studio Code Integrated Terminal
* [ ] Visual Studio Code native PowerShell / PowerShell Core
* [x] Visual Studio 2019 v16.4.0-pre.1.0 Package Manager Console
* [ ] Visual Studio 2019 Developer PowerShell v16.4.0-pre.1.0
* [x] Launch Git Bash and from it, launch PowerShell / PowerShell Core, type
* [x] PowerShell Core 6.2.3 in Azure Cloud Shell
* [x] WSL Ubuntu 18.04.3 LTS (raw bash, both started as Ubuntu, and from Windows Terminal)
* [x] WSL Ubuntu 18.04.3 LTS -> pwsh (both started as Ubuntu, and from Windows Terminal)
Using -NoProfile has no effect, as well as using x86 version of PowerShell (Core)

If you type a text in another editor, and copy-paste it to PowerShell Core 6.2.3 window with either Ctrl+V or Shift+Insert, it works, but with right mouse click, it doesn't (all regular characters, and 'ó' are pasted, while the rest of accented characters are removed). In PowerShell 5.1, the right-click behavior is similar, while with Ctrl+V / Shift+Insert the accents are stripped (letters converted to Latin, except for 'ó'), and '€' is converted to '?'.

The list of special characters on Polish (Programmers) keyboard:

```none
ąćęłńóśźż€
```

They're obtained by either using AltGr (right Alt) combination, or typing ~ (Shift+\`), and then the desired key with the following keys:

```none
acelnosxzu
```

This may be related to Emoji support issue #10016 and this: https://github.com/microsoft/terminal/issues/3019

**Comment by daxian-dbw** [comment]
@marcinsmialek Some issues related to dead keys in keyboard layouts were fixed in the 2.0.0-beta5 version of PSReadLine. Please upgrade from the PowerShellGallery and try it out.

**Comment by marcinsmialek** [comment]
Thank you.
Upgrading PSReadLine from bundled 2.0.0-beta3 to 2.0.0-beta5 on PowerShell Core, and installing it on PowerShell Desktop fixed the issues.

**Comment by bartyzelm** [comment]
@daxian-dbw sorry to bother but where I should raised if for me this is global issue? that means I'm missing ą in all windows apps?

**Comment by daxian-dbw** [comment]
@bartyzelm Sorry to hear that, but I don't have a good answer. Maybe you can report the issue in [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). That's where Windows issues should be reported to.
