### ISSUE TITLE
Running pwsh on macOS Catalina 10.15 terminal results in black screen

### ISSUE THREAD

**Issue by Tandolf** [PowerShell/PowerShell#10758]
# Steps to reproduce

macbook pro with macOS Catalina 10.15
open the terminal, install brew and then install powershell using `brew cask install powershell`

# Expected behavior

When running `pwsh` after finished installation you sheould be greated with some text and be in an interactive shell.

# Actual behavior

command is run and the cursor jumps to the next row. And it is all black, no output, no text, nothing. Its like the program gets stuck. You can only return to the terminal by exiting using ctrl + C.

# Environment data

macOS Catalina 10.15
can't supply more information, running `pwsh --version` gives me no output and the program just freezes.

**Comment by mklement0** [comment]
Do you also see the problem when you install the latest stable version (6.2.3) with the official installers (`.pkg`)?

I just installed both 6.2.3 and the latest preview, 7.0.0-preview.4 via the official installers, and I don't see the problem.

**Comment by Tandolf** [comment]
i just uninstalled the cask powershell and downloaded the latest stable version 6.2.3 from the github page. Installed and i am seeing the exact same behaviour.

i ran the command `pwsh` and all i get is a newline and a black screen. I even tried piping error output but i am getting nothing. Only way for me to exit is to Ctrl + C.

please advice.

**Comment by mklement0** [comment]
@Tandolf: I just tried on another machine that had no previous PowerShell installations, and I don't see a problem.

Try to narrow down your problem by:

* bypassing `$PROFILE` loading (temporarily rename it or launch with `pwsh -noprofile`).
* bypassing user-installed modules (temporarily rename `/Users/jdoe/.local/share/powershell/Modules` and `/usr/local/share/powershell/Modules`)

**Comment by Tandolf** [comment]
tried running with command `pwsh -noprofile` same result, all i get is a new line and then no output and stuck.

renamed `/Users/jdoe/.local/share/powershell/Modules` to `/Users/jdoe/.local/share/powershell/foo` ran `pwsh` still same result.

could not find a `/usr/local/share/powershell/Modules` to rename.

I also installed powershell now on my home macbook pro using `brew cask install powershell` and i get the exakt same result on my home computer as on my work computer.

home mac is running macOS 10.14.5

**Comment by Tandolf** [comment]
but i also figured out that if i install the powershell plugin to Visual studio Code, VSCode starts a powershell terminal and that terminal works. But not if i run pwsh from a regular macOS terminal window.

**Comment by mklement0** [comment]
Are you running with a preferred language / region other than English (US) / United States?

Just to narrow down the problem: If you temporarily change to English (US) / United States, do you still see the problem?

**Comment by iSazonov** [comment]
Close no repo.

**Comment by dinosn** [comment]
Hi, same problem on macOS.  Followed the same steps for possible resolution but the result is the same.  pwsh is frozen with a high cpu time on the system.

**Comment by mklement0** [comment]
@dinosn, see if the problem is related to telemetry and/or the update-notification check, by launching PowerShell as follows, from a POSIX-compatible shell:

```sh
POWERSHELL_TELEMETRY_OPTOUT=1 POWERSHELL_UPDATECHECK=Off pwsh -NoProfile
```

**Comment by krasn1** [comment]
Hello @mklement0 and thank you for your response. 

  I'm afraid the problem is exactly the same. 

<img width="699" alt="Screenshot 2021-04-30 at 6 21 08 PM" src="https://user-images.githubusercontent.com/82439007/116724347-d79b9c00-a9e0-11eb-8db8-c9a62ebacde9.png">

Regards,
Nicolas

**Comment by mklement0** [comment]
Thanks, @krasn1; I personally cannot help you further, but perhaps @iSazonov knows who can.

**Comment by krasn1** [comment]
Hello and thank you for your response. 

 I'm afraid is the same as before:

<img width="1072" alt="Screenshot 2021-04-30 at 7 13 13 PM" src="https://user-images.githubusercontent.com/82439007/116730166-75469980-a9e8-11eb-9c12-2eb710d1fadb.png">

**Comment by iSazonov** [comment]
I have no experience with MacOS. I guess you could collect dotnet traces and analyze them in PerfView.
https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace

Perhaps @SteveL-MSFT has thoughts about the issue.

**Comment by krasn1** [comment]
Hi, thank you for the update.

  I see that dotnet-trace is not working on my macOS I'm starting to think that the problem is on the .net core installation.  I will re-install it and check if there is any change.
