### ISSUE TITLE
System.IO.Path.GetDirectoryName does not throw in PowerShell when passed in null

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#10757]
# Steps to reproduce

In PowerShell 5.1, the following logic produces an error. In PowerShell 6+, it does not.

```powershell
try {[System.IO.Path]::GetDirectoryName($null)} catch {throw}
```

Is this a bug in PowerShell, or .NET?

# Expected behavior

An exception should be thrown.

# Actual behavior

No exception is thrown.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The framework behavior must have changed: .NET Framework throws an error with `''` (which is what the PowerShell argument is converted to - unless you use `[NullString]::Value`) - whereas CoreFX now treats the empty string the same as `null` (don't know if that was an intentional change or not).

```powershell
# $True in .NET Core, exception in .NET Framework.
PS> Add-type -MemberDefinition 'public static bool Test() { return null == System.IO.Path.GetDirectoryName(""); }' -Name Tst -Namespace Tst; [Tst.Tst]::Test()
True
```

**Comment by KirkMunro** [comment]
Thanks for confirming. I've logged the issue in the .NET Core repository, since it seems to be either a documentation problem (docs need to be updated to reflect change) or a regression.

**Comment by mklement0** [comment]
Thanks, @KirkMunro. I see that you've created https://github.com/dotnet/core/issues/3592, but it probably belongs in the CoreFx repo, specifically: https://github.com/dotnet/corefx

**Comment by KirkMunro** [comment]
Thanks @mklement0 I just dug into that repo and found out that the changes are intentional, but the docs haven't been updated to reflect those changes yet (still open issue for that). Nothing more to do here.
