### ISSUE TITLE
Feature Request: Tabbed Interface

### ISSUE THREAD

**Issue by RedactedProfile** [PowerShell/PowerShell#10755]
# Summary of the new feature/enhancement

Simply, a Tabbed interface for multiple powershell sessions, instead of separate floating windows. 

Additionally, I'd like to be able to use a keyboard shortcut like `Ctrl+T` to initiate and focus on a new PowerShell instance. 

Linux Terminals, Mac Terminals, and for Windows we have CMD wrappers like Cmder, Terminator for Windows, and even IntelliJ's console view, have all enabled tabbed interfaces for Command Prompt. 

CMD and the old blue PowerShell could be excused for lacking this feature, but I find it strange and alien feeling to be using a modern iteration and take on PowerShell, but still no tabs. 

An example of Cmder's tab interface 
![image](https://user-images.githubusercontent.com/1039911/66522959-7e3ce680-eaa3-11e9-91b3-c7136162c347.png)

**Comment by rkeithhill** [comment]
This functionality is being implemented in the [Windows Terminal project](https://github.com/microsoft/terminal):

![image](https://user-images.githubusercontent.com/5177512/66523224-9a915100-eaac-11e9-9606-c6dcbc73e921.png)

It even supports horizontal/vertical split panes.

**Comment by RedactedProfile** [comment]
> This functionality is being implemented in the [Windows Terminal project](https://github.com/microsoft/terminal):
> 
> It even supports horizontal/vertical split panes. BTW Windows Terminal requires Windows 10 1903 or higher.

Thank you @rkeithhill ! I was unaware of this project :)
