### ISSUE TITLE
Feature Request: Notification on $PSVersionTable that PowerShell is current/behind and what the latest version is

### ISSUE THREAD

**Issue by mziyabo** [PowerShell/PowerShell#10761]
# Summary of the new feature/enhancement

When running $PSVersionTable it would be a good headsup to the user to know if there is a newer version available or if they are current without them leaving the terminal to check online. 

Benefit is just to keep a user in the shell as opposed to having to start browsing particularly on a GUI-less *Nix/Server Core environment.

**Comment by mklement0** [comment]
Interesting idea - I see that you're already aware of the related proposal in #9141.

One challenge with respect to `$PSVersionTable` is that you don't want to incur the cost of an online lookup every time, particularly when you're using `$PSVersionTable` in scripts, so this information should probably be in a lazily evaluated property.

**Comment by iSazonov** [comment]
Current design is that new version is checked only if session is interactive and the check is delayed up to 3 seconds. With the design we can not use the code in `$PSVersionTable`.

I think a right way is new cmdlet or function (wrapper for Find-Package?).
