### ISSUE TITLE
Long error message in ConciseView

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#10760]
Come from #10746 

![image](https://user-images.githubusercontent.com/22290914/66540526-936a5180-eb45-11e9-9a24-f71ccd3df68b.png)

Make sense to print error message on new line?
```
ParserError:
Line |
   1 | $a=Get-Process -Id $PID | Format-List * | Out-Default | Select-String "Container" | 0/1
     |                                                                                     ^ 
     | Expressions are only allowed as the first element of a pipeline.
```

Screenshot after I decrease windows width
![image](https://user-images.githubusercontent.com/22290914/66540683-1ee3e280-eb46-11e9-8d6e-ae25bb47bf45.png)

**Comment by SteveL-MSFT** [comment]
It may be worth considering also truncating lines longer than console width (adding ellipsis to indicate truncation) so that the relevant section is in the middle

**Comment by iSazonov** [comment]
Truncating error message? It makes it useless.

**Comment by SteveL-MSFT** [comment]
In most of these cases, you would already have the line of code on your screen so not necessary to repeat it.

**Comment by iSazonov** [comment]
My request is only about error message - to place it starting on new line.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can you make a conclusion about my last comment?

Also we have very confusion message for non-existing command:
```powershell
PS> Test-Manifest
Test-Manifest :

PS> dsfsdf
dsfsdf :
```

**Comment by SteveL-MSFT** [comment]
cc @theJasonHelmick 

When the position of the caret in the line is left of middle, I think it's better to have the message following the caret.  However, I agree that when the caret is right of the middle, the wrapping makes it less pleasant.  Perhaps one option is to use the middle to decide if the text should start on the next line?

**Comment by iSazonov** [comment]
> Perhaps one option is to use the middle to decide if the text should start on the next line?

I'd prefer a simple rule that I proposed above. With more complex logic we will catch many bugs - console output is not easy to make reliable for all terminals and all use cases.

**Comment by SteveL-MSFT** [comment]
Would like to get some more feedback before making any change

**Comment by SteveL-MSFT** [comment]
Note that with https://github.com/PowerShell/PowerShell/pull/11398, ConciseView now uses the pre-formatted PositionMessage which does truncation, so long lines will now be truncated.  However, if the error is at the end of the line, then it's still not ideal:

![img](https://i.imgur.com/i540rAM.png)

**Comment by rkeithhill** [comment]
Maybe you add another line here. Have the error position indicator on a line by itself and then on the next line always left justify the error message? 
```
ParserError:
Line |
   1 | $a=get-process -id $pid | format-list * | out-default | select-string "container" | 0/1
     |                                                                                -----^----- 
     | Expressions are only allowed as the first element of a pipeline.
```
Mocked up in notepad so I lost the coloring but you get the idea.

**Comment by iSazonov** [comment]
First better.

**Comment by rkeithhill** [comment]
Also that indicator would need to be adjusted for begining (or near beginning) of the line to something like `^-----`  and at the end maybe `-----^`.  You could complete get rid of the `-----` chars and use just `^` but that might be a bit hard to spot.

**Comment by SteveL-MSFT** [comment]
Since I was using the pre-rendered PositionMessage anyways for a different fix, it sort of made sense to just use it for this one.  So now with the PR, it looks like:

![img](https://i.imgur.com/Jt0EiIc.png)
