### ISSUE TITLE
Please don't display ads in my shell.

### ISSUE THREAD

**Issue by cessor** [PowerShell/PowerShell#10779]
Today, when I started powershell, it displayed an advertisement for powershell core. This is not ok. My suggestion is that you don't do that. I am tired of your behavior. I am filing this as a bug, because it is definitely **unexpected behavior**, just like this category suggests. 

The message shown was this:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6
```

Stop it.

**Comment by iSazonov** [comment]
@cessor Please share $PSVersionTable as issue template requests.

**Comment by iSazonov** [comment]
Windows PowerShell is __frozen__. All new features is added to PowerShell Core only. In near future PowerShell Core will replace Windows PowerShell. MSFT informs customer about the fact.

**Comment by SteveL-MSFT** [comment]
@cessor This is by design for Windows PowerShell.  You can use `-nologo` if it bothers you, but the feedback if that most of the PowerShell community isn't even aware of PowerShell Core and this has already seemed to help improve Windows adoption of PSCore.

**Comment by cessor** [comment]
Thank you for your reply. Yet I still don't understand why arbitrary messages in the shell are justified.

 - I don't know what PSCore is and I don't care. I want to get some work done and could do without the distractions. What gives you the right to decide on what I direct my attention to? 
 - If the adoption of PSCore is low, how is that suddenly my problem?
 - If the adoption of PSCore is low, and it is an 100% equivalent update of my powershell, i.e. it does exactly what PS does without me ever knowing, why do you not just update powershell with the next Windows update, so that I don't even notice?
 - The big thing with PSCore seem to be that it is "platform independent", i.e. it is available for linux and Mac. Why do you push ads to a Windows shell then? Wouldn't it make more sense to ask Canonical to run the add in the Message of the Day (motd) in Ubuntu Terminals? 
 - As a developer, I am interested and excited about software, and I am really happy for the changes that the Core mentality brings, but why do I have to care about that everywhere? If Adobe were to implement Lightroom to run with magic pixies in the background, I still wouldn't care as long as it would help me archive my pictures. 

As for your argument that showing links is justified because it worked: I'd like to see some p-value & effect size on that statement. 

And Finally: I am not part of a PS Community, I am was unaware of PowerShell Core, but I sure am aware of it now. Also, I will make sure to use something else instead. Past behavior is the best predictor for future behavior, so I am pretty certain that PSCore will not respect my desire to be left alone; or even my privacy. Let me guess, big "Telemetry" comming up to help "improve" my "experience?").

**Comment by iSazonov** [comment]
@cessor The repo is for PowerShell Core development. The repo is not right place for Windows PowerShell feedback. Please use other channels for your feedback.

It is impossible replace Windows PowerShell with PowerShell Core transparently - there are breaking changes and MSFT informs users about this in advance so that they have time to study and prepare for migration.

PowerShell Core has a telemetry documented in public RFC. Users have clear understanding that the telemetry is and clear instructions how turn on and turn off the telemetry.

**Comment by cessor** [comment]
Thank you for clarifying.

**Comment by SteveL-MSFT** [comment]
@cessor PSCore isn't just about Linux and macOS, it has substantial improvements for Windows users as well.  Even if you never use PSCore on Windows, by growing the PowerShell community you will have more blogs, modules, scripts that will make you more productive even if you just stay on 5.1 forever.

**Comment by cessor** [comment]
I am not sure what to say at this point or if I should respond at all, as in the posts above I was informed that GH issues are for development issues only and not for general discussions; Yet the fact that you added to the conversation makes it seem like an invitation for me to respond about things like community, blogs, modules and scripts and my productivity. 

Would you like to discuss this some more or would you just like me to be quited about the things you find uncomfortable?

**Comment by SteveL-MSFT** [comment]
I would suggest you join our monthly community call which is this Thursday to discuss this further https://aka.ms/pscommunitycall

**Comment by Kein** [comment]
For the record, PSCore does the same

**Comment by 6a6f6a6f** [comment]
Sorry for reviving this thread, but I don't find anything on the current documentation of PSCore, below the result of `$PSVersionTable`, and how I remove this MOTD from the start of PowerShell core in Windows Terminal?

```
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```  

Windows Terminal profile configuration:

```json
{
      "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
      "hidden": false,
      "name": "PowerShell",
      "source": "Windows.Terminal.PowershellCore"
}
```

**Comment by iSazonov** [comment]
@6a6f6a6f You can set POWERSHELL_UPDATECHECK environment variable. Possible values - Off, LTS, Default.
