### ISSUE TITLE
Use power shell to right a put method for SSRS API deployment for setting shareddataset

### ISSUE THREAD

**Issue by fumiao0525** [PowerShell/PowerShell#10772]
I want to Use power shell to right a put method for SSRS API deployment for setting shareddataset.

I tried the put method in postman and it works fine:
method: put
link: http://fscnbeea2023.fs86.vwf.vwfs-ad/Reports/api/v2.0/Reports(23a6af79-9de3-49cb-b66b-625d3ff3909b)/SharedDataSets
Authorization: Type: NTLM Authentication [Beta]
Headers: Content-Type: application/x-www-form-urlencoded
Body: 
[
  {
      "Id": "935be257-5a65-4c0d-b372-d5a6a188daf6",
      "Name": "P_Calculate_Date_Default_Key",
      "Path": "/Shared_data_sets/P_Calculate_date_Default_key",
      "Type": "DataSet"
  }
]

Then I tried in powershell with get method and it works:

`$Cred = Get-Credential
$Url = "http://localhost/Reports/api/v2.0/DataSets"
$Body = @{

      Path ="/Shared_data_sets/P_Calculate_date_Default_key"
          output_mode = "csv"
    earliest_time = "-2d@d"
    latest_time = "-1d@d"
}
Invoke-RestMethod -Method 'GET' -Uri $url -Credential $Cred -Body $body -OutFile output.csv
`

Then I tried in powershell with put method and it suffers error:
`$Cred = Get-Credential
$Url = "http://localhost/Reports/api/v2.0/Reports(23a6af79-9de3-49cb-b66b-625d3ff3909b)/SharedDataSets"
$Body = @{

       Id = "935be257-5a65-4c0d-b372-d5a6a188daf6"
      Name = "P_Calculate_Date_Default_Key"
      Path = "/Shared_data_sets/P_Calculate_date_Default_key"
      Type = "DataSet"

}| ConvertTo-Json

Write-Output $Body

Invoke-RestMethod -Uri $Url -Credential $Cred  -Body $body -Method Put -ContentType "application/x-www-form-urlencoded"

$error[0]|format-list -force
`

Error is shown as below:

Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At line:16 char:1
+ Invoke-RestMethod -Uri $Url -Credential $Cred  -Body $body -Method Pu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 

Exception             : System.Net.WebException: The remote server returned an error: (400) Bad Request.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 16
PipelineIterationInfo : {}
PSMessageDetails      : 

Could you please kindly help me to check the error and help me to solve the problem?

**Comment by iSazonov** [comment]
@fumiao0525 You could use a sniffer to discover a difference in the requests.

**Comment by fumiao0525** [comment]
> 
> 
> @fumiao0525 You could use a sniffer to discover a difference in the requests.

Hi , could you please kindly provide a short example of this sniffer?  I have not used this before .

**Comment by iSazonov** [comment]
- Microsoft Message Analyzer
- Wireshark

**Comment by iSazonov** [comment]
Close as stale issue.
