### ISSUE TITLE
Please add brew(not cask) formula

### ISSUE THREAD

**Issue by CavalloneChen** [PowerShell/PowerShell#10770]
I would like to install pwsh on our team's centos server where I have no root privilege. But pwsh only comes with brew/cask, which made it impossible for me to install with linux brew.

**Comment by iSazonov** [comment]
@TravisEz13 Is it possible?

@CavalloneChen You can download zip distributive and unpack it in your folder.

**Comment by TravisEz13** [comment]
@CavalloneChen I'm happy for the community to build a formula.  It would not be a Microsoft supported thing as a formula builds the product and we would not have tested those binaries.

**Comment by CavalloneChen** [comment]
> @CavalloneChen You can download zip distributive and unpack it in your folder.

Yeah, definitely. But my server's system isn't officilay supported and installing dependencies can be a pain.

**Comment by iSazonov** [comment]
I guess OpenSSL is single dependency you need and only for remoting.

**Comment by TravisEz13** [comment]
We could build a formula if it was in our own repo.  Would that work?
I have a prototype in my personal repo: https://github.com/TravisEz13/Homebrew-PowerShell
