### ISSUE TITLE
PSCommandNotFoundSuggestion stops working if unknown command is too long

### ISSUE THREAD

**Issue by 0xd4d** [PowerShell/PowerShell#10785]
# Steps to reproduce

```powershell
abcdefg
abcdefgh
abcdefg
```

# Expected behavior

It should show a suggestion after all three commands above

# Actual behavior

The suggestion is only shown after the first unknown command

```
PS C:\> abcdefg
abcdefg : The term 'abcdefg' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ abcdefg
+ ~~~~~~~
+ CategoryInfo          : ObjectNotFound: (abcdefg:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException


Suggestion [4,General]: The most similar commands are: cd, del, ac, clear, diff, cd.., cd\, alg.exe, at.exe, calc.exe.
PS C:\> abcdefgh
abcdefgh : The term 'abcdefgh' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ abcdefgh
+ ~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (abcdefgh:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS C:\> abcdefg
abcdefg : The term 'abcdefg' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ abcdefg
+ ~~~~~~~
+ CategoryInfo          : ObjectNotFound: (abcdefg:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS C:\>
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kvprasoon** [comment]
This happens only if the commands are is copy pasted together to console.

**Comment by 0xd4d** [comment]
> This happens only if the commands are copy pasted together to console.

You don't need to copy and paste the commands to repro this.

**Comment by kvprasoon** [comment]
Can you elaborate on how you executed those invalid expressions. When I execute it one by one or with semicolons in a line, I get suggestions for all.

**Comment by 0xd4d** [comment]
Did you try typing them in? Did you try longer strings?

- 7 chars: `abcdefg` works, `abcdefgh` doesn't
- 6 chars: `aaaaaa` works, `aaaaaaa` doesn't

**Comment by 0xd4d** [comment]
I debugged it and stopped when an ArgumentNullException was thrown and found this script block on the stack. Looks like `Get-Command $lastError...` returns null.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/HostUtilities.cs#L68-L73

**Comment by kvprasoon** [comment]
Interesting, as you mentioned it fails for long strings but not all long strings. I think its not finding a match for those string, hence nothing is printed.

Cc: @SteveL-MSFT

**Comment by 0xd4d** [comment]
Nothing is printed because of the exception, it returns an empty string and gets disabled.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/HostUtilities.cs#L513-L517

**Comment by SteveL-MSFT** [comment]
The current "suggestion framework" is pretty primitive.  We have an open issue to fix this so that suggestions are part of ErrorRecords rather than scrub later.  In this case, it seems that line 72 should check if anything was returned.  Since the current algorithm uses fuzzy matching, repro depends on what is on your system and what results get returned from the fuzzy matching.  It seems reasonable that after a certain length of characters, it wouldn't actually match anything reasonable on your system.

**Comment by vexx32** [comment]
I have a mostly-working WIP implementation of Suggestions-on-ErrorRecord over in #9115

It's largely functional, just stuck on some test failures. If there's interesting in having that available for PS7 I can look at bumping it up my priority list. Might need a hand with some of the odder failures that are cropping up, though. 🙂
