### ISSUE TITLE
Resolve-Path -relative visits parent directory without reason

### ISSUE THREAD

**Issue by an-dr-eas-k** [PowerShell/PowerShell#10792]
When resolving the relative path for the current directory, the parent directory is visited without reason.

The implementation in `PathIntrinsics.NormalizeRelativePath(String, String)` needs fixing. 

The issue is additionally relevant for #8435. See https://github.com/PowerShell/PowerShell/issues/8435#issuecomment-527763563 where I commented a workaround with the usage of `System.IO.Path.GetRelativePath(String, String)`

# Steps to reproduce

```powershell
$ pwd
c:\tmp
$ Resolve-Path -Relative ., (pwd), ../tmp
..\tmp
..\tmp
..\tmp

```

# Expected behavior

```powershell
$ pwd
c:\tmp
$ Resolve-Path -Relative ., (pwd), ../tmp
.
.
.

```

# Environment data
```none
$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
happens also on 5.1.17763.592

**Comment by iSazonov** [comment]
Notice, really there are some NormalizeRelativePath() methods.

**Comment by iSazonov** [comment]
We could look the issue at FileSystem provider V2 time.
