### ISSUE TITLE
Cannot use uppercase if PowerShell is open in Russian keyboard layout

### ISSUE THREAD

**Issue by kvart714** [PowerShell/PowerShell#10794]
# Steps to reproduce

```powershell
1. Switch keyboard layout (I use Russian)
2. open Powershell
3. Switch the layout to English
4. Press shift and enter text
```

# Expected behavior

```none
You can enter "UPPERCASE"
```

# Actual behavior

```none
You cannot enter "UPPERCASE", only "lowercase" without shift
```

# Environment data

```none
Windows 10 Pro 1809
Powershell 5.1.17763.771
```

**Comment by iSazonov** [comment]
@kvart714 Thanks for your report!

It is a known issue with PSReadline module. As workaround you could unload the module. Also the issue was fixed in latest PSReadline preview version (2.0 Beta.5) and you can install it.

**Comment by Suncatcher** [comment]
@iSazonov > Also the issue was fixed in latest PSReadline preview version (2.0 Beta.5) and you can install it.

so maybe it is worth moving from preview to the main version? It is already mid-2021 and it is still in preview. 
Preview is for testing new and experimental features, and this is a fundamental bug.

**Comment by Suncatcher** [comment]
@iSazonov  by the way even on Preview it is not fully fixed. Only SOME of the letter are typable, the others are not working

**Comment by Suncatcher** [comment]
And this problem with typing capital letters exists also on classic PS console, not only in new Terminal. Is there a special bug created for console?

**Comment by iSazonov** [comment]
> Is there a special bug created for console?

If you still say about PSReadline there is an issue about the bug in PSReadline repository.

**Comment by Suncatcher** [comment]
Installed latest 2.2.0 prerelease of PSReadline and the issue seems to be solved. Thanks.

**Comment by Suncatcher** [comment]
@iSazonov and what is the status of that bug? I cannot find it in PSReadline repo?

**Comment by iSazonov** [comment]
@Suncatcher It is not clear what you ask if the issue already fixed in preview and stable version.

**Comment by OZ1** [comment]
@iSazonov Either it does not or my PS is outdated. How can I look up version of the faulty module?

**Comment by iSazonov** [comment]
@OZ1 You can find current versions in https://github.com/PowerShell/PSReadLine. Latest preview one is Beta4, stable 2.1.
Use follow command to discover PSRL version installed:
```powershell
Get-Module PSReadLine | fl
```

**Comment by Suncatcher** [comment]
> It is not clear what you ask if the issue already fixed in preview and stable version.

@iSazonov  I have Powershell like below

Major  Minor  Build  Revision
          ------  -----  -----  --------
5      1      19041  1320

and PSReadLine of version 2.0.0

> Name              : PSReadline
Path              : C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadLine.psm1
Description       : Great command line editing in the PowerShell console host
ModuleType        : Script
Version           : 2.0.0
NestedModules     : {Microsoft.PowerShell.PSReadLine}
ExportedFunctions : PSConsoleHostReadLine
ExportedCmdlets   : {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler,
                    Set-PSReadLineKeyHandler...}
ExportedVariables :
ExportedAliases   :

is it considered stable? I received all dotNet framework updates via Windows update.

**Comment by iSazonov** [comment]
Latest stable version of PSRL is 2.1.0. I think you should update PSRL manually.

**Comment by Suncatcher** [comment]
ok, thanks for clarification. And why the latest stable version is not suggested by the automatic update? Is there any policy to make that happen?

**Comment by iSazonov** [comment]
You can ask MSFT team on next Community Call [(Nov, 18)](https://github.com/PowerShell/PowerShell-RFC/issues/307) :-)

**Comment by Suncatcher** [comment]
ok, I installed latest stable Powershell 7.2.0 and I figured out it loads into PS session several different versions of PSReadLine from different locations

![image](https://user-images.githubusercontent.com/6388034/142223181-762ef3d0-d671-4d91-b37c-7b4574498aea.png)

which will have the highest priority in that case? which one will be in use in this concrete PS session?

**Comment by iSazonov** [comment]
You are searching `available` modules. `Get-Module` show you loaded modules.

**Comment by Suncatcher** [comment]
thanks

**Comment by ognyandim** [comment]
One workaround is to turn-off the per-app keyboard selection: 

"Start menu" -> Settings -> Find "Typing settings" -> Advanced keyboard settings -> check checkbox "Let me use a different input method for each app window" - Uncheck it.

Found here: https://superuser.com/a/1262197
