### ISSUE TITLE
PowerShell Core 6.2.3/7.0.0 failing to install AzureAD module on macOS 10.15

### ISSUE THREAD

**Issue by chrsdrhm** [PowerShell/PowerShell#10801]
# Steps to reproduce

Run command install-module azureadpreview in Terminal after starting PowerShell

# Expected behavior

Module installs...

# Actual behavior

Module fails to install with the following error:

PackageManagement\Install-Package : Unable to load shared library 'api-ms-win-core-sysinfo-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libapi-ms-win-core-sysinfo-l1-1-0.dll, 1): image not found                At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9508 char:21                                                                           
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

# Environment data

PowerShell 6.2.3 or 7.0.0-preview.4 installed via Home-brew on macOS 10.15 Catalina

Attempting to install latest stable and preview versions of AzureAD module

Can confirm this worked on macOS Mojave 10.14.5

**Comment by SteveL-MSFT** [comment]
@chrsdrhm please open this issue in https://github.com/Azure/azure-powershell
