### ISSUE TITLE
how can i do some command after restart?

### ISSUE THREAD

**Issue by khoshroomahdi** [PowerShell/PowerShell#10806]
in the PowerShell 5 I could do that with workflow in PowerShell
but I don't know how to do that in PowerShell core.

**Comment by iSazonov** [comment]
@SteveL-MSFT The scenario is not addressed in docs https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-6 
> In the future, we would like to enable native parallelism/concurrency in the PowerShell language without the need for PowerShell Workflow.

**Comment by kvprasoon** [comment]
@iSazonov I think the question is about checkpoints in PowerShell workflow.
IMO, Its never gonna come in core.

**Comment by SteveL-MSFT** [comment]
@khoshroomahdi there are no plans to bring back PSWorkflow as workflow is not supported in .NET Core.  However, the current suggested workaround is to leverage Task Scheduler to run a PowerShell script after a restart.  I'll submit a PR to update that doc.
