### ISSUE TITLE
Specifying a Set-Alias in your PowerShell profile causes startup time to significantly increase

### ISSUE THREAD

**Issue by antiufo** [PowerShell/PowerShell#10816]
# Steps to reproduce

Add the following line to an otherwise empty `$profile` file, and launch `pwsh`:

```powershell
Set-Alias example dir
```

# Expected behavior

PowerShell still loads reasonably fast.

# Actual behavior
PowerShell loads considerably more slowly:
```none
Loading personal and system profiles took 2026ms.
```

`Get-Module` shows that `Microsoft.PowerShell.Utility` is loaded when `Set-Alias` is used.

Given that aliases are one of the basic features you can expect users might want to customize in their profile, it seems unfortunate that doing so introduces such a significant slowdown.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Linux 4.19.37-5+deb10u2rodete2-amd64 #1 SMP Debian 4.19.37-5+deb10u2rodete2 (2019-08-28 > 2018)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by antiufo** [comment]
My original PowerShell profile was longer, but after investigating what was causing the slowdown, I saw that using that single Set-Alias line was enough to make startup performance much worse.

**Comment by mklement0** [comment]
While startup time is generally a concern for PowerShell, it is most important in _non-interactive_ scenarios: CLI-based execution with `-File` or `-Command`.

For predictability, it is best to use `-NoProfile` in these cases, which bypasses loading of the profiles.
(Sadly, unlike POSIX-like shells, Powershell by default loads its profiles even when `-File` or `-Command` are used - see https://github.com/PowerShell/PowerShell/issues/8072 and https://github.com/PowerShell/PowerShell/issues/992#issuecomment-334965306 for the backstory )

In _interactive_ use, where you do want profiles loaded, the slowdown is noticeable, but doesn't strike me as dramatic; e.g.:

```powershell
PS> { pwsh -nop -c 'get-module' }, { pwsh -nop -c 'set-alias a b; get-module'} | % { (Measure-Command $_).TotalSeconds }

0.472155
0.6102869
```

That is, the implicit loading of the `Microsoft.PowerShell.Utility` module triggered by the `Set-Alias` call (plus the `Set-Alias` call itself) increased the startup time by about 30% on my macOS 10.15 machine.

Given how many basic cmdlets live in said module, it's quite likely that the average profile triggers its import.

**Comment by antiufo** [comment]
I see. I still wonder why the loading of such a common/core module incurs in such a significant time penalty.

```
PS> 1..10 | % { (Measure-Command { pwsh -nop -c 'get-module' }).TotalSeconds }
0.3870604
0.3874905
0.3915055
0.3906345
0.3659332
0.3865723
0.3756553
0.3879174
0.3707061
0.3833163

PS> 1..10 | % { (Measure-Command { pwsh -nop -c 'set-alias a b; get-module' }).TotalSeconds }
3.0328228
0.5088773
1.0092562
1.8483153
0.4995922
0.503561
2.1008697
0.4854821
0.4657199
1.5687297
```

By comparison, a simple
` [Reflection.Assembly]::Load('Microsoft.PowerShell.Commands.Management')` (needed by `Get-Location`), or `::Load('Microsoft.PowerShell.Commands.Utility')` (needed by `Set-Alias`) completes almost immediately.

**Comment by mklement0** [comment]
@antiufo 

Generally, importing a module involves more than just loading an assembly, but hopefully someone more familiar with the module-loading infrastructure can elaborate on what exactly is involved and whether there is potential  for improving the current performance.

As for your 2nd measurement command: These measurements look erratic to me - I don't see the same fluctuations and performance gap, neither on macOS nor on Windows - was your machine just busy at the time, or can you reproduce this? What OS? What PS version?

**Comment by antiufo** [comment]
A simple `strace  -f -tt  -o trace.txt pwsh -noprofile -c '$a = [IO.Directory]::GetFileSystemEntries("/usr/bin")'` shows that even a simple .NET enumeration of that folder, without requesting any additional metadata (only `IEnumerable<string>`), causes each file to be `stat`'d. So I guess the bug belongs to `corefx`?

**Comment by 0xd4d** [comment]
Sounds like this issue: https://github.com/PowerShell/PowerShell/issues/6577

**Comment by darthwalsh** [comment]
I found an easy workaround that took my profile load time from **3000ms** to **_900ms_**. I added the line

```powershell
$ENV:PATH = ($ENV:PATH -split [IO.Path]::PathSeparator | `
    Where-Object { -not $_.StartsWith('/mnt/c') } `
  ) -join [IO.Path]::PathSeparator
```

as the first line to my `$PROFILE`. This removes **every** path from Windows before I use `Set-Alias`, etc.

---

I did a lot of testing with the command `pwsh -nop -c 'Set-Alias a b'` and found that the culprit is the HUGE `PATH` that I was bringing from Windows, taking 800-900ms. I had about 40 PATH entries on my `C:\` SSD. I tried removing dupes like `/mnt/c/Windows` vs. `/mnt/c/WINDOWS` but that didn't make a significant dent. I tried setting `PATH` to any one folder to try to find a culprit, but with only one folder in path `'Set-Alias a b` only ever took 375-450 ms.

But I very rarely use any Windows apps within WSL so removing all entries is probably acceptable for me--but I don't want to suggest this is a good fix!

I might add some PATH entries back for i.e. `/mnt/c/Windows/` for `explorer.exe` -- in my testing add any one folder back didn't slow down `Set-Alias` by more than 50ms.

(This has the added benefit of making a typo produce the error `The term 'fdasfdas' is not recognized as a name of a cmdlet, function, script file, or executable program.` very quickly, instead of waiting for several seconds before failing to find anything.)

----

If it helps anybody reproduce the problem, here was my `PATH` before I started debugging this:
```
~/.pyenv/shims
/opt/microsoft/powershell/7
/home/cwalsh/.local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/usr/lib/wsl/lib
/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe
/mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin
/mnt/c/Windows/system32
/mnt/c/Windows
/mnt/c/Windows/System32/Wbem
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/
/mnt/c/ProgramData/chocolatey/bin
/mnt/c/Program Files/Microsoft/Web Platform Installer/
/mnt/c/WINDOWS/system32
/mnt/c/WINDOWS
/mnt/c/WINDOWS/System32/Wbem
/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/
/mnt/c/WINDOWS/System32/OpenSSH/
/mnt/c/Program Files (x86)/Microsoft VS Code/bin
/mnt/c/Program Files/dotnet/
/mnt/c/Program Files (x86)/dotnet/
/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/
/mnt/c/WINDOWS/system32
/mnt/c/WINDOWS
/mnt/c/WINDOWS/System32/Wbem
/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
/mnt/c/WINDOWS/System32/OpenSSH/
/mnt/c/Program Files (x86)/dotnet-core-uninstall/
/mnt/c/Program Files/Docker/Docker/resources/bin
/mnt/c/ProgramData/DockerDesktop/version-bin
/mnt/c/Program Files/Git/cmd
/mnt/c/Users/cwalsh/scoop/apps/dotnet-sdk/current
/mnt/c/Users/cwalsh/scoop/apps/imagemagick/current
/mnt/c/Users/cwalsh/scoop/apps/oraclejdk/current/bin
/mnt/c/Users/cwalsh/scoop/apps/openjdk/current/bin
/mnt/c/Users/cwalsh/scoop/apps/python/current/Scripts
/mnt/c/Users/cwalsh/scoop/apps/python/current
/mnt/c/Users/cwalsh/scoop/apps/yarn/current/global/node_modules/.bin
/mnt/c/Users/cwalsh/scoop/apps/yarn/current/bin
/mnt/c/Users/cwalsh/scoop/apps/nvm/current/nodejs/nodejs
/mnt/c/Users/cwalsh/scoop/apps/adopt8-upstream/current/bin
/mnt/c/Users/cwalsh/scoop/apps/yarn/current/Yarn/bin
/mnt/c/Users/cwalsh/scoop/apps/android-sdk/current/tools/bin
/mnt/c/Users/cwalsh/scoop/shims
/mnt/c/Users/cwalsh/AppData/Roaming/npm
/mnt/c/bin
/mnt/c/Users/cwalsh/Dropbox/bin
/mnt/c/Users/cwalsh/AppData/Local/Microsoft/WindowsApps
/mnt/c/Program Files (x86)/Google/Chrome/Application
/mnt/c/Users/cwalsh/AppData/Local/Programs/Fiddler
/mnt/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin
/mnt/c/Users/cwalsh/AppData/Local/Microsoft/WindowsApps
/mnt/c/Users/cwalsh/.dotnet/tools
/mnt/c/Users/cwalsh/.dotnet/tools
/mnt/c/Program Files (x86)/Rico Suter/NSwagStudio/
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
```
