### ISSUE TITLE
C# unit test TestAppDomainProcessExitEvenHandlerNotLeaking is flaky

### ISSUE THREAD

**Issue by mdalepiane** [PowerShell/PowerShell#10813]
# Steps to reproduce

- The unit test `TestAppDomainProcessExitEvenHandlerNotLeaking` is flaky.
- Currently is the top 1 faling test in the last 30 days. Failed 20 times out of 87 runs (23% failure rate).
- And all failures have the same error message and stack trace.
- Seems to have been introduced 10/10 in #10768.

### Error Message
```
Assert.DoesNotContain() Failure
Found: (filter expression)
In value: Delegate[] [EventHandler { Method = Void DisposeOnShutdown(System.Object, System.EventArgs), Target = null }, EventHandler { Method = Void CurrentDomain_ProcessExit(System.Object, System.EventArgs), Target = null }]
```

### Stack Trace
```
at PSTests.Sequential.RunspaceTests.TestAppDomainProcessExitEvenHandlerNotLeaking() in D:\a\1\s\test\xUnit\csharp\test_Runspace.cs:line 127
```

[PowerShell-CI-windows - Test failure report](https://powershell.visualstudio.com/PowerShell/_test/analytics?definitionId=19&contextType=build)
![image](https://user-images.githubusercontent.com/1814942/66979822-4296b380-f085-11e9-916a-4cfdc8625781.png)

# Expected behavior

Test results should be consistent.

# Actual behavior

Test is flaky.

# Environment data

Unit tests must be executed in a windows platform.

**Comment by iSazonov** [comment]
@daxian-dbw Can we close the issue?

**Comment by daxian-dbw** [comment]
No, the test is still flaky and is marked as `pending`. Didn't get around to fix it yet.
