### ISSUE TITLE
Serialized PowerShell objects appear to be enumerated

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#10829]
I am not sure whether this qualifies as a bug or designed PowerShell behavior related to unrolling objects (which is to my opinion useless for serialized objects)

# Steps to reproduce

```powershell
$Expression = [ScriptBlock]::Create('[byte[]](1, 2, 3)')
(&$Expression).GetType()
```

# Expected behavior

```none
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Byte[]                                   System.Array
```

I would expect the same behavior as:

- directly invoking the expression  `([byte[]](1, 2, 3)).GetType()`,
- retrieving the type of an embedded valued array, like: `$Expression = [ScriptBlock]::Create('@{x = [byte[]](1, 2, 3)}'); (&$Expression)['x'].GetType()`
- using the [`ConvertFrom-Expression`](https://www.powershellgallery.com/packages/ConvertFrom-Expression) cmdlet : `(ConvertFrom-Expression $Expression -NoEnumerate).GetType()`.

# Actual behavior

```none
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```
<sub>(The **byte[]** array is converted to an **object[]** array)</sub>

This also happens with methods that return a valued array, e.g.: `$Expression = [ScriptBlock]::Create('"abc".ToCharArray()')` and the same happens with other "evaluate" cmdlets along with `Invoke-Expression` and `Invoke-Command`  
This behavior is probably related to: stackoverflow question: [How can I prevent a (serialized) expression to unroll](https://stackoverflow.com/q/56816938/1701026)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
I think your assumption is incorrect.

Your test case is:
```powershell
[scriptblock]::Create('[byte[]](1, 2, 3)')
```

Which is identical to just doing:
```powershell
{ [byte[]](1, 2, 3) }
```

Invoking either of these will cause the collection to be unrolled as it passes through PS's output systems. If you want to prevent this, you would instead need something analogous to:

```powershell
{ Write-Output -NoEnumerate ([byte[]](1, 2, 3)) }
```

Note also that this isn't serialized data, it's just strings being parsed into PowerShell script via the standard parser, no different to any script PS processes normally.

If you want to serialize data, you can use `Export-CliXml`

```powershell
Export-CliXml -Path bytes.xml -InputObject ([byte[]](1, 2, 3))
```

**Comment by iRon7** [comment]
Thanks for the clear answer.

**Comment by iRon7** [comment]
I wonder why the `Write-Output` got the `-NoEnumerate` parameter.  
Wouldn't a `-NoEnumerate` parameter for the `Invoke-Command` make sense for the same reason?

**Comment by vexx32** [comment]
It's not as meaningful, since `Invoke-Command` itself can contain an entire scriptblock with any number of commands; by the time the cmdlet receives any of the output, it's already enumerated. The best it could do is emit the entire `object[]` array as a single item. 🙂

**Comment by iRon7** [comment]
Thanks again for the answer and explanation.
