### ISSUE TITLE
CLI: -File arguments don't recognize [bool] parameter values when passed as separate arguments

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10838]
In response to #4036, passing Booleans to `[switch]` parameters was fixed.

However, the problem persists for `[bool]` parameters _if you pass the value as a separate argument_ (`-param value`), which is the typical syntax; by contrast, `-param:value` (the form that you _must_ use with `[switch]` parameters) works fine (but using `:` _and_ whitespace - `-param: value` - is also broken).

While `[bool]` parameters are rare, there's no reason for them not to be supported.

Additionally, the `-param: value` syntax form (`:` separator _and_ whitespace) also doesn't work with `[switch]` parameters, only `-param:value` does (`:`, but no whitespace).

Also, given that `[bool]` parameters (but not `[switch]` parameters) also accepts _numbers_ inside PowerShell - notably `1` for `$true` and `0` for `$false` (e.g., `& { param([bool] $p) $p } 1` yields `$true`) - passing numbers should be supported too.

# Steps to reproduce

```powershell
Describe "-File with Booleans" {
  BeforeAll {
    Push-Location testdrive:\
    'param([bool] $foo) $foo' > testB.ps1
    'param([switch] $foo) $foo.IsPresent' > testS.ps1
  }

  # [switch] parameter

  It "[switch] param: `$true can be passed with ':' and *no* whitespace" {
    pwsh -noprofile -file ./testS.ps1 -foo:`$true | Should -Be 'True'
  }
  It "[switch] param: `$true can be passed with ':' *with* whitespace" {
    # Note the escaped $, so that '$true' is passed as a string.
    # However, it should work even without escaping, in which case 'True' is passed.
    pwsh -noprofile -file ./testS.ps1 -foo: `$true | Should -Be 'True'
  }


  # [bool] parameter

  It "[bool] param: `$true can be passed with ':' and *no* whitespace" {
    # Note the escaped $, so that '$true' is passed as a string.
    # However, it should work even without escaping, in which case 'True' is passed.
    pwsh -noprofile -file ./testB.ps1 -foo:`$true | Should -Be 'True'
  }

  It "[bool] param: `$true can be passed with ':' *with* whitespace" {
    pwsh -noprofile -file ./testB.ps1 -foo: `$true | Should -Be 'True'
  }

  # A [bool] parameter - unlike [switch] - *requires* an explicit argument, 
  # so you should be able to pass it with the customary value-as-separate
  # argument syntax.
  It "[bool] param: `$true can be passed as a *separate argument*" {
    pwsh -noprofile -file ./testB.ps1 -foo `$true | Should -Be 'True'
  }

  # A [bool] parameter - unlike [switch] - also supports *numbers* as arguments
  # where 0 is coerced to $false and 1 (any nonzero number) to $true
  It "[bool] param: 1 can be passed for $true" {
    pwsh -noprofile -file ./testB.ps1 -foo:1 | Should -Be 'True'
  }
  It "[bool] param: 0 can be passed for $false" {
    pwsh -noprofile -file ./testB.ps1 -foo:0 | Should -Be 'False'
  }

  AfterAll {
    Pop-Location
  }
}
```

# Expected behavior

The test should pass.

# Actual behavior

All tests except the ones with syntax form `-foo:$true` fail:

```none
Expected $true, but got @('.../test.ps1 : Cannot process argument transformation on parameter 'foo'. 
Cannot convert value "System.String" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
```

# Environment data

```none
PowerShell Core 7.0.0-preview.4
```

**Comment by iSazonov** [comment]
Should we escape $ in $true?

**Comment by mklement0** [comment]
@iSazonov 

Good point, but it makes no difference here, because the target `pwsh` instance should recognized both literal strings `$true` and `True`, the latter being what is passed without escaping.
For clarity I've added escaping and a comment to the OP.

Note that the tests do succeed - both with literal `$true` and `True` - if you use the `-param:value` syntax (`:` as separator, no whitespace):

```powershell
# OK: literal '$true'
pwsh -noprofile -file ./test.ps1 -foo:`$true

# OK: literal 'True'
pwsh -noprofile -file ./test.ps1 -foo:$true
```

**Comment by iSazonov** [comment]
It seems the same as:
```powershell
> [bool]'false'
True
```

**Comment by mklement0** [comment]
No, it's not the same: we're talking about the _CLI_ here, where _all arguments are of necessity initially strings_, and you need _some_ way to pass a Boolean when you use `-File`.

The inability to pass a Boolean with `-File` - still a problem in _Windows PowerShell_ - led to the fix in #4036, but that fix was _incomplete_, which is what this issue is about.

**Comment by iSazonov** [comment]
I see two way:
- enhance a binder so that for -File option it tries to convert string arguments to parameter types
- enhance a workaround for switch so that always convert $true and $false literals to boolean.

**Comment by mklement0** [comment]
We don't need _new_ parameter-parsing functionality, we just need to _amend_ (fix) a _previous fix_:

That fix was to allow literal strings `$true`, `true`, `$false`, `false` to be converted to `[bool]` when bound to `[switch]` or - less commonly - `[bool]` parameters when the CLI is used with `-File`.

This now works _in principle_, except in particular _syntax forms_, which should obviously not be treated any different than its _equivalent forms_.

**As stated, `-foo:$false` works, but neither `-foo $false` nor `-foo: $false` do - even though these are just _syntax variations_.**

Note that `-foo $false` - whitespace-only separator - is only applies to `[bool]` parameters, because with `[switch]` parameters you _must_ use `:` (given that switch parameters never treat a _separate_ argument as their value).

@SteveL-MSFT, you implemented the original fix in https://github.com/PowerShell/PowerShell/pull/4178 - does this make sense to you?

**Comment by iSazonov** [comment]
> We don't need new parameter-parsing functionality,

If somebody run ps1 file in pwsh session and then do the same in command line (copy-paster) different behavior may surprise the user.

**Comment by mklement0** [comment]
It may, but it shouldn't:

If you want the same behavior as _inside_ PowerShell, invoke the CLI with `-Command` rather than `-File`.

It was a deliberate design decision to treat all `-File` arguments _as literal string_, at least initially.

This doesn't preclude later conversions _when binding to the script's parameters_, such as from string to `[int]`, but it does preclude passing arguments such as `@{foo=1}` and `(1+2)` and expecting them to be evaluated _up front_, _as expressions_ as they would inside PowerShell.

If you disagree with this design, I suggest you create a new issue.

An _exception_ to the design was deliberately put in place to allow binding _strings_ `$true`, `true`, `$false`, `false` to `[switch]` and `[bool]` parameters when binding calling via `-File`, as it would otherwise be _fundamentally impossible_ to pass a Boolean via `-File`.

The issue at hand is that this exception wasn't implemented comprehensively.

**Comment by mklement0** [comment]
However, there is one problematic aspect about how the exception was implemented, @SteveL-MSFT, though it may not matter much in practice:

The Boolean-like strings are _unconditionally_ converted to `[bool]` - even if the parameter they bind to is _untyped_:

The right behavior is to retain them as strings in that event, just like a "number string" such as `1` remains a string when bound to an untyped parameter via `-File`.

**Comment by iSazonov** [comment]
Conditional conversion means a binder enhancement which is likely unjustified complexity.

**Comment by SteveL-MSFT** [comment]
@mklement0 seems like this is becoming a slippery slope.  At some point, it seems that using `-Command` is a good enough workaround.

**Comment by mklement0** [comment]
I'm personally fine with leaving the _unconditional_ conversion mentioned in my previous comment be, but I don't think there's anything slippery about the issue as original reported:

Supporting a feature in only _one_ syntax form, but not in others that _should always result in the same behavior_ is a baffling inconsistency that is well worth fixing.

**Comment by BrucePay** [comment]
@mklement0  Passing commands to an executable - any executable -  requires that the arguments be passed as literal strings because  that's what the operating systems support. All type information is lost so trying to get the exact semantics of calling a PowerShell function from within PowerShell is tilting at windmills. As @SteveL-MSFT says, after a while you have to accept good enough. If there's something that just doesn't work, then it needs to get fixed (encoding scriptblocks, Steve's fix) but otherwise it just leads to playing wack-a-mole with bugs.

**Comment by mklement0** [comment]
@BrucePay: To succinctly recap my previous comment: 

All that is needed is to fix the incomplete fix that was implemented in https://github.com/PowerShell/PowerShell/pull/4178, as detailed in the OP.

**Comment by adaviding** [comment]
This is still an important issue.  I hit it today.  It still has not been addressed.  I request that it be re-opened.
