### ISSUE TITLE
Weird behavior of .NET class X509Certificate2 in Power Shell Core, Windows Power Shell and Windows Power Shell in elevated mode

### ISSUE THREAD

**Issue by Akreddy123** [PowerShell/PowerShell#10833]
# Steps to reproduce

```powershell
$secPassword = (ConvertTo-SecureString -String "<>" -AsPlainText -Force)
[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]$flags = 4 -bor 16 -bor 2
// 4 -> exportable
//16 ->Persist key
//2->MachinekeySet
$pfxFilePath = 'C:\Users\<>\DESKTOP\Cert.pfx'
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($pfxFilePath, $secPassword, $flags)


```

# Expected behavior

```
Should create a CNG based certificate with an exportable private key.

```

# Actual behavior

```
In Power Shell Core, it is working fine with an exportable private key like below
Key                  : System.Security.Cryptography.CngKey
LegalKeySizes        : {System.Security.Cryptography.KeySizes}
KeyExchangeAlgorithm : RSA
SignatureAlgorithm   : RSA
KeySize              : 2048

In Windows Power Shell, creating a CSP based certificate with an exportable private key like below.
PublicOnly           : False
CspKeyContainerInfo  : System.Security.Cryptography.CspKeyContainerInfo
KeySize              : 2048
KeyExchangeAlgorithm : RSA-PKCS1-KeyEx
SignatureAlgorithm   : http://www.w3.org/2000/09/xmldsig#rsa-sha1
PersistKeyInCsp      : True
LegalKeySizes        : {System.Security.Cryptography.KeySizes}

In Windows Power Shell elevated mode, creating a CSP based certificate with a null private key.

```

# Environment data

Name                           Value                                                                   
----                           -----                                                                   
PSVersion                      5.1.18362.145                                                           
PSEdition                      Desktop                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                 
BuildVersion                   10.0.18362.145                                                          
CLRVersion                     4.0.30319.42000                                                         
WSManStackVersion              3.0                                                                     
PSRemotingProtocolVersion      2.3                                                                     
SerializationVersion           1.1.0.1    
 

PS Core: 
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by iSazonov** [comment]
@Akreddy123 It is not right repo to report an issue about Windows PowerShell. Use other channels like Windows 10 Feedback tool and Microsoft forums.
Also you call .Net method so it is not PowerShell issue, it is .Net issue, for .Net Framework you can use channels I mentioned above, for .Net Core you can report to CoreFX repo https://github.com/dotnet/corefx/.
