### ISSUE TITLE
Stop-parsing symbol on Unix-like platform doesn't support single-quoted arguments

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10831]
Superseded by https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4963

---

The idea behind `--%` is to pass command lines that use the platform-native shell through, with minimal interpretation by PowerShell.

While `--%` with its cmd-style environment-variable expansion is an awkward fit for Unix-like platforms to begin with, it does work in principle, but only with _double_-quoted arguments (`"..."`).

However, the POSIX-like shells (such as Bash) that are native to Unix-like platforms also understand _single_-quoted strings (`...`) - verbatim strings.

`--%` currently doesn't support the latter.

Note that on Unix _someone_ has to break the command line into _individual arguments_ before passing the latter to the target process; unlike on Windows, you cannot start processes with single-string command lines in the native process-creation APIs, so truly passing a command line through isn't an option.

# Steps to reproduce

```powershell
# Note: From Bash itself, running
#        bash -c 'echo "$1 $RANDOM"' - 'I'\''m'
# works correctly and yields something like "I'm 1234"
bash --% -c 'echo "$1 $RANDOM"' - 'I'\''m'
$LASTEXITCODE | Should -Be 0
```

# Expected behavior

The test should succeed.

# Actual behavior

The test fails: The Bash command breaks due to syntax errors, and the exit code is nonzero.

Due to lack of support for single-quoted strings, PowerShell passes the following arguments to `bash` (enclosed in `[...]` here to show their boundaries):

```none
[-c]
['echo]
[$1 $RANDOM']
[-]
['I'\''m']
```
Note how the `'...'` argument was broken in two, and how the embedded double quotes disappeared.

# Environment data

```none
PowerShell Core 7.0.0-preview.4
```

**Comment by chuanjiao10** [comment]
#10219

**Comment by mklement0** [comment]
Thanks, @chuanjiao10.

I've closed this issue, because I remembered that a decision was made in https://github.com/PowerShell/PowerShell/issues/3733#issuecomment-327641533 that `--%` will not be extended to work more sensibly on Unix-like platform.

I've created a documentation issue instead, asking that the near-uselessness of `--%` on Unix be documented: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4963

If you know `--%`'s limitations, you can still use it, however, so in the command that prompted #10219 you can simply use `ssh-keygen --% ""`, i.e. _double_ quotes.
