### ISSUE TITLE
The prompt should be put after the end of the messages of stdout or stderr that an application is writing to

### ISSUE THREAD

**Issue by atiq-cs** [PowerShell/PowerShell#10848]
# Steps to reproduce
Start an application in verbose mode that writes to stdout or stderr; I am not sure where whether it is writing to stdout or err.

After application writes some stuff to the prompt, try to type a command and we will see texts are being typed on top of the output of previous application.

```powershell
Start MyVerboseApp
... verbose messages ....
......... .....
... verbose messages ....
...... my prompt ........
... verbose messages cont ....
... .... ....
... verbose messages ends ....
```

# Expected behavior
prompt should go after the output
```none
... verbose messages ....
... .... ....
... verbose messages ends ....
PS > my prompt
```

# Actual behavior

![image](https://user-images.githubusercontent.com/7858031/67151790-b3a1bb00-f27f-11e9-8cbd-9d9f462adaa2.png)

```powershell
Start MyVerboseApp
... verbose messages ....
......... .....
... verbose messages ....
...... my prompt ........
... verbose messages cont ....
... .... ....
... verbose messages ends ....
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
`Start` is a built-in alias for `Start-Process`, and `Start-Process` launches a process _asynchronously_.

If  you combine that with `-NoNewWindow` (which is implied on Unix-like platforms) and the launched process is a  console application, its output will appear at random times.

To avoid that, use `-Wait` to ensure synchronous invocation, though note that if you simply want synchronous execution of a console application, there's no need to use `Start-Process` at all - just invoke the program _directly_.

If you didn't actually use `start` / `Start-Process`, please clarify your invocation scenario.

Generally, please remember that this repo is for PowerShell _Core_ issues only.
