### ISSUE TITLE
Test failures in release testing in new SSHConnection tests

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#10858]
This PR added new test cases for `New-PSSession -SSHConnection`.
https://github.com/PowerShell/PowerShell/pull/10720/files

In release testing these tests failed on most of OSes with:
```
Expected an exception, with FullyQualifiedErrorId '2100,PSSessionOpenFailed' to be thrown, but the FullyQualifiedErrorId was 'PSSessionOpenFailed'. from /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/engine/Remoting/SSHRemotingCmdlets.Tests.ps1:51 char:30
at <ScriptBlock>, /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/engine/Remoting/SSHRemotingCmdlets.Tests.ps1: line 58
58:         { & $scriptBlock } | Should -Throw -ErrorId '2100,PSSessionOpenFailed'
```

They are only passing on Mac and Ubuntu16.04, that happen to be the systems used in CI, this is why these failures were not noticed in CI in the original PR.

Test, probably, should be updated to check only for `PSSessionOpenFailed` substring.

# Steps to reproduce

run `SSHRemotingCmdlets.Tests.ps1` on Debian 9 /10 

# Expected behavior

test pass

# Actual behavior

`Expected an exception, with FullyQualifiedErrorId '2100,PSSessionOpenFailed' to be thrown, but the FullyQualifiedErrorId was 'PSSessionOpenFailed'.`

**Comment by adityapatwardhan** [comment]
These tests fail on: Alpine, OpenSUSE, Fedora 29 / 30, Debian 9 / 10, centOS 7, Ubuntu 18.

https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=120648&view=ms.vss-test-web.build-test-results-tab&runId=1102520&resultId=101236&paneView=debug
