### ISSUE TITLE
Test failures in release testing related to line endings

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#10855]
Some tests are failing release testing due to comparing strings with different line endings ("/r" vs "/r/n").
The tests should be updated to account for this.
[unelevated-toinvestigate.txt](https://github.com/PowerShell/PowerShell/files/3752899/unelevated-toinvestigate.txt)

# Steps to reproduce

```powershell
run release automation tests on Server 2016
```

# Expected behavior

pass

# Actual behavior

fail

# Environment data

Server 2016

**Comment by anmenaga** [comment]
Similar problem in:
test\powershell\Language\Scripting\Debugging\DebuggerCommand.Tests.ps1 (e.g. line 147) Expected: '...$null\n ...' ; But was: '...$null\r\n ...'
test\powershell\Modules\Microsoft.PowerShell.Utility\Select-String.Tests.ps1 (e.g. line 100) Expected: '\nhello\nHello\n\n' ; But was: '\r\nhello\r\nHello\r\n\r\n'

**Comment by iSazonov** [comment]
@adityapatwardhan @anmenaga  Can we close the issue?

**Comment by adityapatwardhan** [comment]
SCommand API tests.Cloning PSCommands.clones properly when using the setter on the PowerShell type
Expected strings to be the same, but they were different.
Expected length: 5
Actual length:   6
Strings differ at index 4.
Expected: 'test\n'
But was:  'test\r\n'

at <ScriptBlock>, C:\ProgramData\PSPackage\download\Test\test\powershell\engine\Api\PSCommand.Tests.ps1: line 63
63:                 $result | Should -Be "test

**Comment by rjmholt** [comment]
Currently afflicting the Cloning PSCommands tests
