### ISSUE TITLE
Support generic dictionary initializers

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#10862]
# PowerShell should support constructing (and probably casting) generic dictionaries 

```
As a PowerShell user
I need to construct strongly typed dictionaries
So I can pass them to .NET methods

As a PowerShell user with a C# background 
I need to initialize collection types with minimal code
So my code is readable and maintainable
And I don't look like I'm stuck in .net 1.0
```

# Proposed technical implementation details (optional)

What we need is to be able to initialize strongly typed dictionaries. like I can in other languages, e.g.:

```PowerShell
$Spanish = [Dictionary[int,string]]@{
    0 = "zero"
    1 = "uno"
    2 = "dos"
}
```

Since PowerShell's casting is much more powerful than other langauges, and I can already cast this Dictionary to `hashtable`, 

I should also be able to cast to `[Dictionary[string,string]]` etc. as long as the objects in the dictionary can cast to the new types.

Currently I have to resort to behind the scenes tricks with LINQ (and since PowerShell's extensible type system doesn't apply to interfaces, I must apply it to `hashtable` instead of to `IDictionary`):

```PowerShell
using namespace System.Collections
using namespace System.Collections.Generic
using namespace System.Linq

# Add a .ToDictionary(KeyType,ValueType) for all hashtables
Update-TypeData -TypeName Hashtable -MemberType ScriptMethod -MemberName ToDictionary -Value {
param([Type]$KeyType,[Type]$ValueType)
    [Scriptblock]::Create(
        "[Enumerable]::ToDictionary(
            [DictionaryEntry[]]@(`$this.GetEnumerator()),
            [Func[DictionaryEntry,$($KeyType.FullName)]]{ `$args.Key },
            [Func[DictionaryEntry,$($ValueType.FullName)]]{ `$args.Value })"
    ).Invoke()
}

```

So that I can write initializers that are readable and preserve maintainability at some cost of performance (and type safety):

```PowerShell
$Spanish = @{
    0 = "zero"
    1 = "uno"
    2 = "dos"
    3 = "tres"
}.ToDictionary([int],[string])
```

But currently, to cast that to `[Dictionary[string.string]` I have to _cast_ it to hashtable and then convert it `.ToDictionary([string],[string])`:

```PowerShell
([hashtable]$Spanish).ToDictionary([string],[string])
```

**Comment by iSazonov** [comment]
Is it related to https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0002-Generalized-Splatting.md?

**Comment by vexx32** [comment]
Don't think that's related, no. That's more for ways to utilise existing hashtables in commands or method invocation. :slightly_smiling_face:
