### ISSUE TITLE
PowerShell hangs when trying to pass an empty SecureString as a cmdlet parameter

### ISSUE THREAD

**Issue by deniskovalchuk** [PowerShell/PowerShell#10870]
PowerShell hangs when trying to pass an empty `SecureString` as a cmdlet parameter. I wrote a [module](https://gist.github.com/deniskovalchuk/4e9bfab4dc0aac842c7e259cd7a518ff) with `Set-SecureScheduledTask` cmdlet to demonstrate it. The cmdlet based on [Set-ScheduledTask](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/set-scheduledtask?view=win10-ps), but uses `SecureString` for `-Password` parameter.

# Steps to reproduce
1. Set appropriate execution policy to allow loading of modules.
```powershell
Set-ExecutionPolicy Unrestricted -Scope Process -Force
```

2. Import `ScheduledTasks` module.
```powershell
Import-Module ScheduledTasks -SkipEditionCheck
```

3.  Download and import [this](https://gist.github.com/deniskovalchuk/4e9bfab4dc0aac842c7e259cd7a518ff) module with `Set-SecureScheduledTask` cmdlet.
```powershell
Import-Module (Resolve-Path('PS_SecureScheduledTask.cdxml')) -Force
```

4. Create a dummy scheduled task.
```powershell
$task = New-ScheduledTask
```

5. Read a password using `-AsSecureString` and enter an empty string.
```powershell
$password = Read-Host -AsSecureString
```

6. Try to set `-User` and `-Password` for this task using `Set-SecureScheduledTask`.
```powershell
Set-SecureScheduledTask -InputObject $task -User "Username" -Password $password
```

# Expected behavior
```powershell
Set-SecureScheduledTask : Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:66
+ ... cureScheduledTask -InputObject $task -User "Username" -Password $password
+                                                                ~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Set-SecureScheduledTask], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Set-SecureScheduledTask
```

# Actual behavior
PowerShell hangs and doesn’t return control.

```powershell
Set-SecureScheduledTask : Failed to run CIM method SetByObject on the Root/Microsoft/Windows/TaskScheduler/PS_ScheduledTask CIM object.  Specified argument was out of the range of valid values.
Parameter name: offset
At line:1 char:1
+ Set-SecureScheduledTask -InputObject $task -User "Username" -Password ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (PS_ScheduledTask:String) [Set-SecureScheduledTask], CimJobException
    + FullyQualifiedErrorId : CimJob_ArgumentOutOfRangeException,Set-SecureScheduledTask
```
I assume the exception is occurred [here](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs#L55).

Calls with `-Password $null` or a non-empty `SecureString` are handled correctly.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by deniskovalchuk** [comment]
Any comments or suggestions?

**Comment by SteveL-MSFT** [comment]
The [ValidateNotNullOrEmpty] attribute doesn't look inside the SecureString.  For your module, you'll have to convert the securestring to a string and check if it's null/empty.  Seems like it would be ok for the attribute to look inside the contents of the secure string, but will leave it for @PowerShell/powershell-committee to discuss

**Comment by deniskovalchuk** [comment]
@SteveL-MSFT, thanks for your reply. I don't think that there is a problem with the `[ValidateNotNullOrEmpty]` attribute. I used the cmdlet only to demonstrate a general problem. If you don't specify the attribute the behavior will not change: PowerShell will present `ArgumentOutOfRangeException` and hang.

I don't know the internal details of PowerShell, but I can assume that there is a problem with converting `SecureString` to a raw cim string (see [`CimSensitiveValueConverter`](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs#L27)). It looks like the [condition](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs#L53) doesn't allow conversion of empty strings.

**Comment by SteveL-MSFT** [comment]
@deniskovalchuk sorry, misunderstood what you were asking.  I'll see about debugging this.

**Comment by SteveL-MSFT** [comment]
Looks like an error is returned, but [GetConsumingEnumerable](https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs#L1122) is blocked.
