### ISSUE TITLE
Online link for Set-Timezone is incorrect.

### ISSUE THREAD

**Issue by glennsarti** [PowerShell/PowerShell#10879]
When running `Get-Help Set-Timezone -online` I am sent to `https://go.microsoft.com/fwlink/?LinkId=799469` which does not appear to be a valid link as I'm sent to the Microsoft Store to buy a new Surface Laptop.  While this is nice, it is wrong. 😊

https://github.com/PowerShell/PowerShell/blob/ca64bfb3e3e9f85889178206d60bed42e1a3467c/test/powershell/engine/Help/assets/HelpURI/V3Cmdlets.csv#L92

The link in this location should probably be linking to https://docs.microsoft.com/en-au/powershell/module/Microsoft.PowerShell.Management/set-timezone?view=powershell-6 instead. I would normally raise a PR for this myself, however the link shortening service doesn't appear to allow public requests

**Comment by TylerLeonhardt** [comment]
Thanks @glennsarti! 

@sdwheeler how do we typically fix these issues?

**Comment by sdwheeler** [comment]
@TylerLeonhardt @glennsarti We can't fix these because we are not publishing updated cab files for old versions of PowerShell. That is the whole point of the blog post I wrote. https://devblogs.microsoft.com/powershell/updating-help-for-older-versions-of-powershell/

**Comment by yecril71pl** [comment]
Not reproducible, as of PSVersion                      7.0.2.

**Comment by glennsarti** [comment]
Didn't realise this was still open ... Fixed now
