### ISSUE TITLE
Some concerns about error formatting with ErrorView = ConciseView

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#10877]
https://github.com/PowerShell/PowerShell/pull/10641 - The new error formatting is nice but it might have some disadvantages, too.

**Demo script**

```powershell
function Test-Error {
    Write-Error @'
Oops, error! Details:
- Somewhat long details line 1, and more somewhat long details line 1.
- Somewhat long details line 2, and more somewhat long details line 2.
'@
}

Test-Error
```

**NormalView error formatting** (good old but with some "noise"):

```
Test-Error : Oops, error! Details:
- Somewhat long details line 1, and more somewhat long details line 1.
- Somewhat long details line 2, and more somewhat long details line 2.
At C:\ROM\z\_191023_233922_ps_ErrorView\bad-error.ps1:11 char:1
+ Test-Error
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-Error
```

**ConciseView error formatting** (nice and shiny but with issues):

```
Test-Error: C:\ROM\z\_191023_233922_ps_ErrorView\bad-error.ps1
Line |
  11 | Test-Error
     | ^ Oops, error! Details: - Somewhat long details line 1, and more somewhat long details line 1. - Somewhat long details line 2, and more somewhat long
     | details line 2.
```

**Some issues**

1. The file path and line number are in different places. Even for a human it requires
   some effort to connect them together in order to go to the problem location.
   But it is also the challenge for various error parsers in text editors, log
   parsers, etc. VSCode, for example, understands "standard link" patterns as
   `<path>(<line>)`, `<path>:<line> [char:<column>]`. Is it going to work well
   with the new ConciseView formatting?
1. Column number is missing. The caret position is shown in a different way,
   this is somewhat fine for humans but programs (VSCode and others) will
   have difficulties with getting this info.
1. Line formatting of error messages is not respected. Yes, in most cases error
   messages are one liners. But lengthy errors with some detailed multiline
   descriptions are not rare, too. Preserving the original formatting of such
   messages would be useful, they were composed in such a way for reasons.
1. When the error caret position is more to the right, the error message first
   line is more indented and gets even more difficult to read for long messages.
   Copying the error messages is also difficult with such extra indentation.

**Suggestion**

For ConciseView, why not just strip some "noise", i.e. CategoryInfo and
FullyQualifiedErrorId lines and keep the rest just like in NormalView?
Example:

```
Test-Error : Oops, error! Details:
- Somewhat long details line 1, and more somewhat long details line 1.
- Somewhat long details line 2, and more somewhat long details line 2.
At C:\ROM\z\_191023_233922_ps_ErrorView\bad-error.ps1:11 char:1
+ Test-Error
+ ~~~~~~~~~~
```

All the above issues are resolved (or at least negative effects reduced).

**Comment by theJasonHelmick** [comment]
Thank you for the feedback! In regards to line and column - the positional information is still contained in the error object itself so non-humans should still be able to read that.  You should notice it if you use the new cmdlet Get-Error or with $error[0].

**Comment by nightroman** [comment]
I believe in many scenarios tools and apps like VSCode just parse the output *text*, not the actual error instances. To rephrase, did you or somebody else tried this update in VSCode. If a new format error is written to the output, can you click there in order to jump to the source file error line and column?

**Comment by TheIncorrigible1** [comment]
@nightroman If you're referring to the vscode extension, they use powershell's shell as a server to process commands so the error object is still intact.  Next month, they'll be moving to a omnisharp-based server with PS7 GA which should address performance issues seen there.

**Comment by nightroman** [comment]
@TheFlyingCorpse This is good. And yet, have you tried, does it work well? I have not, I just think it might not work.

**Comment by nightroman** [comment]
@TheIncorrigible1 This is good. And yet, have you tried, does it work well? I have not, I just think it might not work.

In other words, can you click in the output where the error is just **printed** so that VSCode jumps to the source code where the error is?

**Comment by SteveL-MSFT** [comment]
@nightroman there's an existing issue to debate what to do with long error messages: https://github.com/PowerShell/PowerShell/issues/10760

For VSCode where the terminal supports linking to the location, the NormalView format doesn't work completely.  `file:line` is understood by the VSCode terminal, but not `file:line char:num`.  Looking at the output of dotnetcli, this format works: `file(line,char)` but is less obvious to a person what it means, but does link correctly.  Here's an example:

```powershell
PS> /Users/steve/test/multierror.ps1
Begin
Get-ChildItem: /Users/steve/test/multierror.ps1(3,1)
Line |
   3 | Get-Childitem -Path .\nothere
     | ^ Cannot find path '/Users/steve/repos/PowerShell/nothere' because it does not exist.

Selct-object: /Users/steve/test/multierror.ps1(5,15)
Line |
   5 | Get-Process | Selct-object -property Nohere
     |               ^ The term 'Selct-object' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Invoke-Command: /Users/steve/test/multierror.ps1(7,1)
Line |
   7 | Invoke-Command -HostName nothere
     | ^ Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

Get-Item: /Users/steve/test/multierror.ps1(9,1)
Line |
   9 | Get-Item -Path .\stuff
     | ^ Cannot find path '/Users/steve/repos/PowerShell/stuff' because it does not exist.

Get-Item: /Users/steve/test/multierror.ps1(11,10)
Line |
  11 | get-item -invalid foo
     |          ^ A parameter cannot be found that matches parameter name 'invalid'.

Done
```

**Comment by nightroman** [comment]
For VSCode the NormalView format works at least partially (file:line), right out of the box. And it may fine tuned via VSCode json settings, as far as I know (some one-liner regex pattern?).

As for the ConciseView, in its current form, VSCode probably does not work at all. And it is very tricky to tune it even using json settings (multi-line regex patterns? is it even supported?).

**Comment by SteveL-MSFT** [comment]
Adding the line as in `file:line` is simple and, I believe, doesn't make the text less human-readable.  I was simply asserting that trying to add the column with parenthesis syntax will probably make it confusing to most users.

**Comment by nightroman** [comment]
@SteveL-MSFT I believe (and have tried), VSCode understands `file:line:column`, too. Will it be confusing if supported?

But if at least the line is added, it's already much better usability.

**Comment by nightroman** [comment]
I think this would be ideal for ConciseView but it's just me :)
```
Test-Error : Oops, error! Details:
- Somewhat long details line 1, and more somewhat long details line 1.
- Somewhat long details line 2, and more somewhat long details line 2.
At C:\ROM\z\_191023_233922_ps_ErrorView\bad-error.ps1:11:1
+ Test-Error
+ ~~~~~~~~~~
```

**Comment by SteveL-MSFT** [comment]
file:line:column does work, but I don't think it's easily understandable by users and most users will see the error in a terminal they can't click

You can always implement a new errorview.

**Comment by nightroman** [comment]
@SteveL-MSFT Thank you for listening and taking actions.
