### ISSUE TITLE
Get-Counter is not in PowerShell Core

### ISSUE THREAD

**Issue by Skybeat** [PowerShell/PowerShell#10872]
Hello,

I was trying a script from PS 5.1 where i use the cmdlet `Get-Counter`.
If I try this script with PS 6.2.3 the follow error message is shown:

> get-counter : The term 'get-counter' is not recognized as the name of a cmdlet, function, script file, or operable program.

# Steps to reproduce

fire a `Get-Counter` in powershell

# Expected behavior

that it works

# Actual behavior

the error message: 

> get-counter : The term 'get-counter' is not recognized as the name of a cmdlet, function, script file, or operable program.

# Environment data

PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```


Thank you,
Nico

**Comment by iSazonov** [comment]
It is dup https://github.com/PowerShell/PowerShell/issues/4306
