### ISSUE TITLE
MSIX pkg starts in system32 instead of user's home directory

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#10884]
# Steps to reproduce

```powershell
Start pwsh from installed msix
```

# Expected behavior

```none
Starts in user's home directory
```

# Actual behavior

```none
Starts in system32 directory
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-Preview.5
PSEdition                      Core
GitCommitId                    7.0.0-Preview.5
OS                             Microsoft Windows 10.0.19010
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Maybe have to leverage https://github.com/Microsoft/MSIX-PackageSupportFramework to have it start in different directory

**Comment by iSazonov** [comment]
We could do this internally. If `[System.Environment]::CurrentDirectory` is `Windows\System32` then force switch to current user home directory.

**Comment by SteveL-MSFT** [comment]
There is a small chance that someone may want current dir to be system32, but seems very rare and they can always have in their $profile to set whatever location they want.  Let's have @PowerShell/powershell-committee discuss.

**Comment by iSazonov** [comment]
> There is a small chance that someone may want current dir to be system32,

We could do this only at startup time for initial runspace.

We use `-WorkingDirectory ~` in shortcut created by MSI.
I guess MSIX does not add the parameter.

So proposal for discussion is to make `-WorkingDirectory ~` being default. 
Follow runspaces will continue to have current default (`[Environment]::CurrentDirectory`).

**Comment by SteveL-MSFT** [comment]
There's no way to add any parameters to the exe in the msix.  MSIX cannot create or modify shortcut.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and believe the proposal to start in $PSHome when in system32 won't be acceptable since if someone explicitly set-location to system32 and starts a new pwsh, it should start in that folder rather than moving to $PSHome.  Will need to leverage https://github.com/Microsoft/MSIX-PackageSupportFramework.

**Comment by iSazonov** [comment]
Using MSIX-PackageSupportFramework would be also problematic. Currently we create regular shortcut and users can customize it (add custom arguments). Is it possible with MSIX-PackageSupportFramework?

**Comment by SteveL-MSFT** [comment]
Users can create their own shortcut to the pwsh.exe installed by MSIX.  But they need to do it manually as MSIX creates the shortcut whereas in the MSI we ship a shortcut we can customize.

**Comment by iSazonov** [comment]
My question is about changing default MSIX behavior. If we implement a fix for the issue can users change the behavior?

**Comment by SteveL-MSFT** [comment]
@iSazonov users can use `set-location` in their $profile and that always work regardless of the initial working directory.
