### ISSUE TITLE
SecureString shouldn't be used warning.

### ISSUE THREAD

**Issue by Kriegel** [PowerShell/PowerShell#10880]
In the [SecureString Class ](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring)  documentation, there is a Warning from the platform-compat team, that Securestring shouldn't be used.
[Direct Link to the Warning on Github](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md)

I like and used SecureString much in the past.

How do we deal with that?

**Comment by Kriegel** [comment]
I am aware of removing SecureString is a breaking change.
So since PowerShell is running on non Windows systems, which perhaps doesn't support SecureString encryption.
I think we have to talk about to implement user warnings, either into the documentation and on screen!?

**Comment by vexx32** [comment]
I believe this will be handled during implementation of @SteveL-MSFT's proposal for secrets handling which is currently in the RFC stage. 🙂 

https://github.com/PowerShell/PowerShell-RFC/pull/208

**Comment by SteveL-MSFT** [comment]
@vexx32 yes and no.  The SecureString type still exists and we need it to tell PowerShell when to prompt masked input.  The Secrets Management module is more about not having plaintext secrets in scripts and also abstracting remote vaults (like Azure KeyVault) making them seamless to use.
