### ISSUE TITLE
Feature Request : Autocomplete in powershell for something that I type the most

### ISSUE THREAD

**Issue by anirugu** [PowerShell/PowerShell#10889]
I write few command every time when I open powershell at global level. For example doing npx create-reacta-app abcd.

It can be anywhere. What I am looking for is when I started typing npx, it show something with grey text and if I press the Tab, the text will be set into the current line.

This could be quite useful. In few case on mac I see this thing, What is helpful here is I don't need to type everything by hand again. Just tab will type everything.

**Comment by iSazonov** [comment]
Some tools have this (Far, browsers in address box). To implement this we need to keep a command history between sessions.

@anirugu Please open a request in PSReadline repository.

**Comment by mklement0** [comment]
The UI aspect of providing a _preview_  of tab-completion values _before_ pressing the tab key has previously been requested in this PSReadLine issue: https://github.com/PowerShell/PSReadLine/issues/741.

Creating _custom_ tab completions is already available to you as part of PowerShell itself, not PSReadLine, via the `Register-ArgumentCompleter` cmdlet; here's a quick example that completes option names only:

```powershell
Register-ArgumentCompleter -Native -CommandName npx  -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorColumn)

    # Simply return the expanded parameter name, if a match is found.
    '-create-react-app',
    '-other-command'  -like "$wordToComplete*"
}
```

Now, typing `npx <tab>` will complete to `-create-react-app`, and `-other-command` if you press tab again.

I suggest you close https://github.com/PowerShell/PSReadLine/issues/1126

**Comment by iSazonov** [comment]
@mklement0 It seems the request is about "command history" like browsers do in address line for us.

**Comment by mklement0** [comment]
Thanks, @iSazonov: there's a PSReadLine request for that as well: https://github.com/PowerShell/PSReadLine/issues/687
