### ISSUE TITLE
Running PowerShell Core under SSH from Windows results in broken UX

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1088]
## Steps to reproduce
- From windows box, open inbox powershell
- ssh to a linux VM. Use ssh that comes with windows version of git from command line

```
C:\Program Files\Git\usr\bin\ssh.exe
```
- Follow [instructions](https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md#toolchain-setup) to install powershell
- Everything works fine up to this point
- Run powershell
- Try to do something
## Expected behavior

You should be able to work
## Actual behavior

Console UX is broken:
half of commands are entered at the top of the screen, overriding the buffer

![image](https://cloud.githubusercontent.com/assets/816680/15945104/96e1e294-2e45-11e6-8f91-a2c59efa13e0.png)
## Environment data

v0.4.0

**Comment by MathiasMagnus** [comment]
Same here. I wanted to try PS on an Ubuntu 16.04 remote cluster node, but the console got really messed up. I tried both ssh.exe that ships with Git for Windows, and also the one from bash.exe (upgraded to Ubuntu 16.04). Neither worked properly. Arrow keys not working properly to move inline and in history, in some places backspace doesn't work... not glitched, but broken.

The few commands that worked got the expected results, so anticipation is not lost, but grew even more. Very eager to try a fixed version, or even start tweaking with a hotfix, but Putty really is not an elegant workaround.

**Comment by Jaykul** [comment]
By the way guys, if you install PowerShell core on your windows box, you can use PowerShell remoting to the Ubuntu box (over SSH). That seems to be working fine (with the exception that _at least with ConEmu in the way_, the Ctrl+C/Ctrl+V don't work in PSReadLine).

**Comment by MathiasMagnus** [comment]
And how does one do that precisely? (Sry, never done that before. Is that Enter-PSSession but instead creating a CIM-Session it's an SSH-Session? I am clueless.)

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#471

**Comment by Jaykul** [comment]
@joeyaiello @lzybkr  is this really "OK"?
I mean -- how can PowerShell close this?

I mean, I'm uncomfortable with taking a mandatory dependency on an _external_ module for the REPL prompt in the first place -- is there **any** functionality more core to the purpose of a **shell** than this?

But if it's broken in a way that impacts docker connections, and PowerShell in WSL, that seems beyond an _unfortunate_ bug in an external module, and into core functionality.

**Comment by SteveL-MSFT** [comment]
This might not be PSReadline.  I can repro with the original steps and after some trial and error was able to remove PSReadline and it still had an issue.  I'll investigate this.

**Comment by SteveL-MSFT** [comment]
I tried this with alpha.18 and had the same problem.  However, trying it with latest master and setting TERM=xterm it appears to work fine with win32 port of ssh.exe from our other GitHub repo (not the one that comes with Git).

At this point, it may just be a documentation issue.

**Comment by SteveL-MSFT** [comment]
Issue from Win32-OpenSSH to on TERM not being set https://github.com/PowerShell/Win32-OpenSSH/issues/252

**Comment by KirkMunro** [comment]
I don't think it's quite as simple as setting TERM=xterm. I'm hitting this issue with an environment that uses Shell in a Box. I've configured my Shell in a Box web server such that the.ip.address/ps will invoke docker run -e TERM=xterm -it microsoft/powershell, and in the docker session I connect to in the browser where TERM is set to xterm the issue still persists. Yet other endpoints I create (such as one for ssh) work just fine.

**Comment by SteveL-MSFT** [comment]
@KirkMunro I'll setup ShellInABox and will investigate this further

**Comment by KirkMunro** [comment]
Great, thanks. @SteveL-MSFT, if you have questions about ShellInABox, let me know.

**Comment by SteveL-MSFT** [comment]
@KirkMunro got a repro.  ShellInABox is pretty cool i have to say, we definitely want powershell working in this environment

**Comment by KirkMunro** [comment]
@SteveL-MSFT Glad you got the repro going. ShellInABox is really cool. I have a modified fork of it (https://github.com/KirkMunro/shellinabox) right now that supports launching PowerShell in a docker container via a POSH endpoint, or for user-defined ssh/mosh targets. I'd like to plug PSRemoting in there as well once I have more time.

**Comment by SteveL-MSFT** [comment]
@KirkMunro can you open a separate issue for ShellInABox?  I believe this original issue is something OpenSSH needs to address.  Thanks

**Comment by joeyaiello** [comment]
@SteveL-MSFT: I don't know which layer of the stack this is broken in...right now, we set TERM=xterm on the SSH side, and my current repro is a complete hang after starting PowerShell. I can't type or do anything here (no Ctrl+C, Ctrl+Break, nothing). 

![image](https://cloud.githubusercontent.com/assets/1255187/26330825/b4edf222-3f02-11e7-8780-ded17ce1477d.png)

**Comment by joeyaiello** [comment]
I'll try to get someone on the SSH side to take a look so we know where to prioritize/resource investigation. 

/cc @bagajjal @manojampalam @bingbing8 @SandeepSutari

**Comment by joeyaiello** [comment]
I lied. Ctrl+Break totally works to get back out to the Windows shell (killing the SSH connection). I was using the wrong mapping on my Pok3r...

**Comment by MaximoTrinidad** [comment]
Hum! In my case, when connected from Windows 10 to Ubuntu 16.04, pressing Ctrl-C doesn't work.  So, its getting hung at the prompt.

c:\> ssh user@linuxSystem

![linuxwnssh_01_2017-05-22_19-08-56](https://cloud.githubusercontent.com/assets/19892435/26332016/2cb66ab8-3f22-11e7-91b7-7b737d368d2f.jpg)

**Comment by KirkMunro** [comment]
@SteveL-MSFT: Done, new issue opened here: #3849.

**Comment by joeyaiello** [comment]
@MaximoTrinidad yeah, Ctrl+C doesn't work for me either. Only Ctrl+Break to leave the session entirely.

That being said, @bagajjal isn't getting a repro on his Win 10 CU box at all, so we're digging in to see what the difference is between our two machines. Given that PuTTY works fine for both of us, we think this is in the OpenSSH layer, so I opened an issue at PowerShell/Win32-OpenSSH#733.
