### ISSUE TITLE
Skip existing files with Copy-Item

### ISSUE THREAD

**Issue by ashmind** [PowerShell/PowerShell#10885]
# Summary of the new feature/enhancement

As a user I want `Copy-Item` to be able to skip existing files, so that I can copy only the non-existent files.

For example, I have a folder that might already contain some configuration overrides, and if they are there, I don't want to touch them, but I do want to copy any non-overriden configuration files.

This proposal does not require time checks, though it would make sense to implement it in a way that would allow time checks later on.

`robocopy` is not a great solution since:
1. It's not cross-platform
2. It has high learning curve

# Proposed technical implementation details (optional)

```powershell
Copy-Item --Skip Existing # allows for extensions like --Skip Newer later on
```

```powershell
Copy-Item --SkipExisting # solves the problem, but not extensible
```

**Comment by BrucePay** [comment]
Note: the file resource in DSC does this.
