### ISSUE TITLE
MSIX Run as Administrator JumpList menu not working

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10895]
cc @SteveL-MSFT 

# Steps to reproduce

Right click on the icon in the taskbar and select 'Run as Administrator'.
It does not elevate, which one can verify with:
```pwsh
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
```

# Expected behavior

Running as Admin

# Actual behavior

Not running as admin

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-Preview.5
PSEdition                      Core
GitCommitId                    7.0.0-Preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by kilasuit** [comment]
OK so I can half repro this

When you click on
![image](https://user-images.githubusercontent.com/6355225/67598578-c9265180-f765-11e9-98a5-797c4028a53a.png)
This comes back with false

Otherwise if you click on 
![image](https://user-images.githubusercontent.com/6355225/67598683-10acdd80-f766-11e9-90e7-635a46dd4c08.png)
it will open the elevated shell by as expected

**Comment by bergmeister** [comment]
The first menu in your screenshots is referred to as a `JumpList`, which is what this issue refers to. I've written the custom code to create that jumplist menu entry. The menu in your 2nd screenshot is something purely native to Windows that applies to any taskbar shortcuts and PowerShell has no knowledge of it.
Given that the JumpList does not give a UAC prompt, I'd say, it's something that we need to explicitly add in order to make it work for MSIX, the following blog post contains a possible solution
https://www.advancedinstaller.com/allow-elevation-msix-packages.html

**Comment by kilasuit** [comment]
In all honesty is there any need to have the jumplist entry if the functionality is there and works by default via the other route?

**Comment by bergmeister** [comment]
The purpose of the Jumplist is to be easier accessible and save 1 extra click and wait time for this slow menu to appear. It was a backport of similar code from Windows PowerShell in C++ to C# in PowerShell Core. Therefore it ensures feature parity with Windows PowerShell and having the same user experience that people are used to.

**Comment by iSazonov** [comment]
(This shortcut fight seems to be endless)

**Comment by kilasuit** [comment]
@bergmeister as per my comment on #10891 on 7.3.0-preview.8 MSIX installed via the Windows Store this seems to have been fixed - do we know if there was a PR that fixed it?
