### ISSUE TITLE
MSIX Wrong Windows and Jumplist icons

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10891]
cc @SteveL-MSFT  as per email

# Steps to reproduce

Open PowerShell from start menu.

# Expected behavior

All Icons the same and should be the preview icons (i..e not the black ones for RTM)

# Actual behavior

Window and Jumplist Icon not the correct preview icon
![image](https://user-images.githubusercontent.com/9250262/67590783-ce7aa080-f753-11e9-8e07-fde633ed6d85.png)

![image](https://user-images.githubusercontent.com/9250262/67590835-de928000-f753-11e9-8d98-c697e6b3bf01.png)

# Environment data

pwsh from MSIX (MSFT store private preview)

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-Preview.5
PSEdition                      Core
GitCommitId                    7.0.0-Preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kilasuit** [comment]
@bergmeister on 7.3.0-preview.8 MSIX installed via the Windows Store this seems to have been fixed - do we know if there was a PR that fixed it?
