### ISSUE TITLE
Feature Request: Cmdlets to add/remove explorer context menu (MSIX does not support custom registry keys)

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10892]
# Summary of the new feature/enhancement

- As a user of the MSIX package I want to have an easy way of adding the explorer context menu that the MSI currently offers. MSIX does not support custom registry keys, therefore cmdlets seem to be a natural way for this, similar to the `Enable-PSRemoting` cmdlet.

- As a user of the MSI, I want to remove/add the context menu post-installation dynamically to my liking or cleanup leftover keys from old previews that might have been left-over due to an upgrade.

I don't have time for this right now but might consider this at some point in the future.

cc @SteveL-MSFT 

# Technical implementation

2 cmdlets:

- `New-PowerShellExplorerContextMenu`
- `Remove-PowerShellExplorerContextMenu`

They probably need to have an optional version and preview/rtm parameter in case someone wants to remove/add the context menu for an older version as there have been some issues with past MSI previews upgrades. The MSI should probably start using them as well (depending on how complex custom actions in upgrade or uninstall is)

**Comment by SteveL-MSFT** [comment]
Would we want to generalize this to allow future extensibility?  Perhaps `Get/Set-ShellExtension` (need a better noun as Shell can be confusing, but don't want it specific to Windows either).

**Comment by bergmeister** [comment]
If we did a generic one (no strong opinion on pros/cons except that it would result in more maintenance and might become more complex in the future), then Id think the proper place would be a module of its own on the `PSGallery`. In this case, would you be happy to ship such a module by default similar to PSReadline?

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we suggest starting this as a separate module to validate the design and get user feedback
