### ISSUE TITLE
Progress bar can significantly impact cmdlet performance

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#10900]
This problem occurs when working remotely,The fault disappears when the progress bar is disabled.   
When I download a file   
Actual: 10x slowdown for Invoke-WebRequest   
```
Name                           Value                            ----                           -----
PSVersion                      6.2.3                            PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT                          PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}            PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5                  PSEdition                      Core                             GitCommitId                    7.0.0-preview.5
OS                             Linux 4.9.112-perf #1 SMP PREEM…
Platform                       Unix                             PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Transmission:openssh
[https://github.com/PowerShell/PowerShell/issues/2138](https://github.com/PowerShell/PowerShell/issues/2138)
![Screenshot_20191026-024220~2](https://user-images.githubusercontent.com/26913892/67612274-d5e18e80-f7d3-11e9-99be-e793990604a7.png)

![qq_pic_merged_1572018489003](https://user-images.githubusercontent.com/26913892/67612301-1c36ed80-f7d4-11e9-864c-88d996a09b29.jpg)

**Comment by he852100** [comment]
To be sure, `pwsh`>`pwsh` performance is very poor.The problem goes away when I use the `bash` connection.

----   
`file Size:5gb`
#### bash>pwsh
linux to win
```
TotalSeconds      : 37.1669552
```
linux to linux
```
TotalSeconds      : 48.4692239
```

----
#### pwsh>pwsh
linux to win
```
TotalSeconds      : 1229.4277205 
```
win to linux
```
TotalSeconds      : 944.0381479
```
![test](https://user-images.githubusercontent.com/26913892/67615001-26b7ae00-f7f9-11e9-872e-8e95df1ef196.gif)

**Comment by SteveL-MSFT** [comment]
We should probably consider `$ProgressView` where we can default to a much simpler progress bar that takes less time/cpu to draw.  The current progress bar has to redraw the entire space include whitespace.

**Comment by iSazonov** [comment]
Previously we did a fix to perform thinning only locally. This means that progress records in a huge number are still transmitted remotely.

**Comment by iSazonov** [comment]
https://github.com/PowerShell/PowerShell/blob/b60381f9228192639adbe6537ffec53bb5c154bb/src/System.Management.Automation/engine/remoting/server/ServerPowerShellDriver.cs#L535-L553

@PaulHigin Is the place right to thin out ProgressRecords?
