### ISSUE TITLE
Assigning to $args looks like it works, but it does not work (should it error?)

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#10902]
Assigning to the automatic variable `$args` doesn't error, and doesn't store the value:

```
PS C:\> $args
PS C:\> $args=1
PS C:\> $args
PS C:\>
```

By comparison, $matches assigns and stores the value (until the `-match` operator overwrites it), and `$host` won't let you assign to it, saying it's constant or read-only.

I only noticed `$args` behaviour because someone was trying to use it and asking me why their code wasn't working - I don't know if it can be read-only / const and still be updated by the engine so it works, but it might be nice if it had some warning or message about not trying to assign to it.

Strict mode doesn't change this behaviour.

(And `$pwd` will let you assign to it and does store the value, but does not change the working directory; might be nice if it either did change the current directory or warned on assignment).

**Comment by vexx32** [comment]
Interesting... seems as though `$args` is behaving more like `$null` in that it'll allow you to write to it, but just discard the value instead of overwriting it.

Is this a deliberate design choice? 🤔

**Comment by mklement0** [comment]
It actually retains the value in the _same scope_, but resets / fills it with arguments on entering a new scope:

```
PS>  & { $args = 'foo'; "[$args]"; & { "[$args]" } }

[foo]
[]
```

I don't think we should ever have allowed assigning to `$args`, but it's conceivable that there is code out there that relies on being able to manipulate it in the same scope.

At least implementing a PSSA rule would make sense, preferably one that warns on assigning to _any_ automatic variable.
