### ISSUE TITLE
Measure-Object ignores $null values in counting and count-based stats

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10905]
Note: The existing behavior can't be changed so as not to break backward compatibility; there are two possible ways forward:

* Live with the limitation and simply document it - it's definitely an edge case.  
However, this means that the count of input collections with `$null` values will be technically incorrect and deviate from manual counting with something like `$count=0; 1, $null, 2 | % { ++$count }; $count`

* Introduce an `-IncludeNull` switch that also counts `$null` values among the inputs, and treats them as `0` in the context of  `-Average` and `-StandardDeviation` and `-Min` / `-Max`.

### Current behavior:

```powershell
PS> 1, $null, 2 | Measure-Object -AllStats

Count             : 2
Average           : 1.5
Sum               : 3
Maximum           : 2
Minimum           : 1
StandardDeviation : 0.707106781186548
```

### Potential new behavior:

```powershell
# Hypothetical new -IncludeNull switch
PS> 1, $null, 2 | Measure-Object -AllStats -IncludeNull


Count             : 3
Average           : 1
Sum               : 3
Maximum           : 2
Minimum           : 0
StandardDeviation : 1
Property          : 
```

That is, the above would behave like `1, 0, 2 | Measure-Object -AllStats`

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please triage the issue?
