### ISSUE TITLE
Investigate TestRunspaceWithPowerShellAndInitialSessionState xUnit failure

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1092]
Follow-up from #1005 

PR #1091 enabled xUnit test run, but it one test was failing and I temporarily disabled it.

**Comment by andschwa** [comment]
@vors I'm moving this assignment back to you, noting that it's still blocked until we have a working xUnit runner or a different assembly loading solution.

**Comment by vors** [comment]
@chunqingchen do you want to take it over, since you are working on xunit runner?

**Comment by chunqingchen** [comment]
I am closing this issue as we are not running many tests through xunit runner. we are still focusing on lite tests.
