### ISSUE TITLE
Get-Member misrepresents some NoteProperty members as type-native properties for deserialized objects

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10924]
`Get-Member -Type Property` (as opposed to the property-type agnostic `-Type Properties`) normally only reports properties native to the object's .NET type.

By contrast, `NoteProperty` members such as those created for `[pscustomobject]` instances are _not_ included (e.g., `[pscustomobject] @{ foo=1 } | Get-Member -Type Property` yields no output).

However, in the context of deserializing objects serialized in the context of remoting / background jobs, those `NoteProperty` members of the deserialized object that correspond to the native properties of the original object are misrepresented as native properties in `Get-Member -Type Property`'s output.

**Note**: 

Perhaps this behavior is by design, to have a "type-unfaithfully" deserialized object better emulate the original input object, but I'm not sure this "white lie" is helpful (if you use .NET reflection methods such as `.GetType().GetProperties()` directly, they tell the truth) and, conversely, it can be confusing.

# Steps to reproduce

```powershell
# Pass a [System.IO.DirectoryInfo] instance to a background job
# and examine the native properties (there should be none) on the *deserialized* object.
Start-Job { $args | Get-Member -Type Property } -Args (Get-Item /) | Receive-Job -Wait -AutoRemoveJob |
  Should -BeNullOrEmpty
```

# Expected behavior

The test should pass.

# Actual behavior

The test fails:

```none
Expected $null or empty, but got @(System.String {get;set;}, System.DateTime {get;set;}, System.DateTime {get;set;}, System.Boolean {get;set;}, System.String {get;set;}, System.String {get;set;}, System.DateTime {get;set;}, System.DateTime {get;set;}, System.DateTime {get;set;}, System.DateTime {get;set;}).
```

That is, the `NoteProperty` members of the deserialized object that correspond to the original input object's native properties were reported as native properties, even though they are not.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by BrucePay** [comment]
@mklement0 
> Perhaps this behavior is by design, to have a "type-unfaithfully" deserialized object better emulate the original input object, but I'm not sure this "white lie" is helpful

Doing this is beyond "helpful". Cmdlets parameters are bound by property name. Preserving the properties on deserialized objects allows them to be used transparently by cmdlets that understand those properties. _This is the core idea behind PowerShell remoting._

**Comment by mklement0** [comment]
@BrucePay:

This by-property-name binding is:

* neither tied to the _actual_ property type - which happens to be `NoteProperty` in the case of non-type-faithfully deserialized objects

* nor to the _incorrect property type reported by `Get-Member`_, which is what this issue is about.

In other words: the de facto `NoteProperty` members on non-type-faithfully deserialized instances bind just fine to by-property pipeline-binding parameters, just like type-native `Property` members do.

---

If you truly believe, as your response suggests, that the gist of this  issue is  to complain about _properties being preserved during remoting_, your response is:

* based on a misreading of the OP

* amounts to an unnecessary distraction.

Unfortunately, this is a recurring pattern.

I've asked this question before:
I do my best to formulate the issues I report here clearly, yet you're repeatedly misinterpreting them.
What can I do to help this situation?
