### ISSUE TITLE
Distribution Support Request for Debian 11

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10923]
# Details of the Distribution

- Name of the Distribution: Debian	
- Version of the Distribution: 11 (Currently Debian Testing)
- Processor Architecture (One per request): AMD64
- [x] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker: https://github.com/PowerShell/PowerShell-Docker/issues/307
- The following is a requirement for supporting a distribution **without exception.**
  - [ ] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and 
  the PowerShell comittee will review the request.
  - [x] The version of the Distribution is supported for at least one year.
  - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [x] Docker image created
- [x] Docker image published
- [x] Distribution tested
- [x] Distribution goes LTS
- [x] Update `packages.microsoft.com` deployment
- [ ] Lifecycle updated
- [ ] Documentation Updated

**Comment by RDIL** [comment]
I'll add Docker image in a few minutes

**Comment by TravisEz13** [comment]
waiting for this to be out officially

**Comment by TravisEz13** [comment]
When we release, packages are pushed.  the mapping file, says which repo's to release to.  It was in a private repo and the code to push still is, but this file says which package to push to which repo and the repo names are usually just the codename for the distribution.  If all the check boxes are checked before `Update packages.microsoft.com deployment` in a distribution request issue.  Feel free to open a PR against the mapping file and link the PR to the distribution request.

**Comment by TravisEz13** [comment]
For reference, this is the only entry that is new in the mapping file:  https://github.com/PowerShell/PowerShell/blob/master/tools/packages.microsoft.com/mapping.json#L38-L41

**Comment by TravisEz13** [comment]
For this to be supported, we still need to test the mapping file 😮‍💨.  So, we will release it in 7.3.0-preview.1 and verify that packages.microsoft.com didn't do anything wrong.  If they did, we will probably fix it during that release.   Then we can backport to 7.2.

**Comment by adityapatwardhan** [comment]
@sdwheeler We have been shipping this distro for some time now. We should add documentation for this in the install docs. We have it supported for PowerShell version 7.2.0+.
