### ISSUE TITLE
Distribution Support Request Fedora 31

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#10936]
# Details of the Distribution

- Name of the Distribution: Fedora 
- Version of the Distribution: 31
- Processor Architecture (One per request): AMD64
- [x] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker
- The following is a requirement for supporting a distribution **without exception.**
  - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and 
  the PowerShell comittee will review the request.
  - [x] The version of the Distribution is supported for at least one year.
  - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] Lifecycle updated
- [ ] Documentation Updated

CC @RDIL

**Comment by RDIL** [comment]
I'm too busy to do it today.  I can maybe do it tomorrow

**Comment by TravisEz13** [comment]
no just... just giving you a heads up since you have wanted to do this work before.

**Comment by TravisEz13** [comment]
Waiting for an image to be created.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell-Docker/issues/449

**Comment by xtqqczze** [comment]
A request for Fedora 35: https://github.com/PowerShell/PowerShell-Docker/issues/686

**Comment by xtqqczze** [comment]
All Fedora distributions were removed in #654.

Last commit of Fedora 34 dependencies before deletion:
https://github.com/PowerShell/PowerShell-Docker/blob/1c3b285c4d3ae6d22dfde83e4964e3a35e6c5627/release/7-3/fedora34/test-deps/docker/Dockerfile
https://github.com/PowerShell/PowerShell-Docker/blob/1c3b285c4d3ae6d22dfde83e4964e3a35e6c5627/release/7-3/fedora34/test-deps/meta.json
