### ISSUE TITLE
MSIX Bad behaviour when running 'install-powershell.ps1 -Daily'

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#10941]
# Steps to reproduce

Install v7-preview5 from private preview in MS store (important, does not repro with MSI installation)
Call the [install-powershell.ps1](https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1) with the `-Daily` switch from PowerShell being installed via MSIX.
cc @SteveL-MSFT 

# Expected behavior

It works, just the same way it works for any version like e.g. the v7-preview5 from MSI

# Actual behavior

The installed daily build of PowerShell gets corrupt (this has happened 2 times in a row and is therefore not a sporadic problem).
`Test-Path` on the `powershell-daily` folder of the daily install reports `true` and `get-childitem` can see items but the using the `pwsh.exe` from inside it does not work (immediate crash with no stack trace). Somehow the `powershell-daily` folder is not visible/accessible via explorer.exe. Running Test-Path from a different (non MSIX) PowerShell returns `false`, therefore it seems to be a problem with folder permissions.

# Environment data

v7-preview5 from MS Store private preview

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-Preview.5
PSEdition                      Core
GitCommitId                    7.0.0-Preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Ok, it seems that there is still some filesystem virtualization happening with AppX even though the package requests `unvirtualizedResources`.  When I run `install-powershell.ps1 -daily` in the MSIX pwsh, it ran but also had issues with the newly installed pwsh at the end of the script.  I can see the folder and its contents.  If I use a regular pwsh window, that folder doesn't exist at all.

**Comment by bergmeister** [comment]
@SteveL-MSFT Just FYI that this issue is still present with version `7.1.0-preview.6` from the MS-Store.

Related to the MS-Store generally: Apparently it forcibly closes the process of the running app during update (which cannot be controlled either), which could be fatal in some cases where a script is mid execution and could leave a system in a corrupt state. Therefore, personally I will not consider using the Microsoft store any more due to that and I think the store description should have a warning about this risk because most people will not be aware. Please evaluate whether the MS-Store is actually suitable for RTM releases of PowerShell or only previews only due to that.
