### ISSUE TITLE
[Feature Request] '<' operator like in cmd or unix

### ISSUE THREAD

**Issue by jmwielandt** [PowerShell/PowerShell#10945]
# Summary of the new feature/enhancement

Add the '<' operator like the CMD's o UNIX's one to pass the content of a file (by lines) as stdin input.

### With this code:

![image](https://user-images.githubusercontent.com/37153467/67882648-56302880-fb21-11e9-9aa5-d89167b78848.png)

### And this file:

![image](https://user-images.githubusercontent.com/37153467/67883208-6b598700-fb22-11e9-8979-0462640c72da.png)

### In CMD ✔️ 

![image](https://user-images.githubusercontent.com/37153467/67882918-dd7d9c00-fb21-11e9-837f-abefbc0bad1d.png)

### In WSL (with ubuntu 18.04) ✔️ 

![image](https://user-images.githubusercontent.com/37153467/67882988-04d46900-fb22-11e9-91cd-87772b47b5f9.png)

### In powershell 6.2.3 ❌ 

![image](https://user-images.githubusercontent.com/37153467/67882792-98596a00-fb21-11e9-9c11-306ffe35c609.png)

### In powershell 5 ❌ 

![image](https://user-images.githubusercontent.com/37153467/67882872-c343be00-fb21-11e9-9f03-0ef5f20c359e.png)

I really need it (university) :sob:
Thanks!
#FutureIsNow (?)

**Comment by alexbuzzbee** [comment]
The equivalent feature in PowerShell is piping from `Get-Content`. So, in your case,

```
PS> Get-Content example.txt | py .\print-twice.py
hola
hola
```

`<` should probably be supported as well.

**Comment by chuanjiao10** [comment]
both '<' and ‘<<’ is a shit ！powershell never should have '<' operator  ！！！
