### ISSUE TITLE
Feature Request: Add back Export-Counter and Import-Counter

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#10946]
# Summary of the new feature/enhancement

These cmdlets were removed due to using undocumented APIs primarily working with blg (binary log) format of perf counters.  This OSS project https://github.com/microsoft/Tx supports blg using a different set of APIs so there's a possibility of bringing back those cmdlets.

**Comment by jdhitsolutions** [comment]
Submitted to the Cmdlet Working Group for discussion.

**Comment by jdhitsolutions** [comment]
This issue has been reviewed by the Cmdlets & Modules Working Group. It is the group's consensus that this is a `won't fix` item. The PowerShell community does not appear to place a high priority on these commands. It is the Working Group's belief that use of these commands is very low and thus doesn't warrant the work effort. Still, a community contribution in the PowerShell Gallery would be welcome.
