### ISSUE TITLE
-replace operator stringifies its LHS operand culture-sensitively

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10948]
In many contexts PowerShell uses the invariant culture for string operations for predictable operation irrespective of the session's current culture.

For instance, `"$(1.2)"` (string interpolation in expandable strings) yields `'1.2'` even in cultures that use `,`, not `.` as the decimal mark, and cast to numeric types (e.g., `[double] '1.2'`) are similarly culture-invariant.

The `-split` and `-replace` operators implicitly convert their LHS operands to strings, if they aren't, but while `-split` commendable uses the culture-invariant conversion (as in expandable strings), 
**`-replace` is unexpectedly culture-sensitive**

# Steps to reproduce

```powershell
Describe "Culture-invariance tests for -split and -replace" {
  BeforeAll {
      $prevCulture = [cultureinfo]::CurrentCulture
      [cultureinfo]::CurrentCulture = 'fr' # The French culture uses "," as the decimal mark.
  }
  It "-skip: LHS stringification is not culture-sensitive" {
    1.2 -split ',' | Should -Be '1.2'
  }
  It "-replace: LHS stringification is not culture-sensitive" {
    1.2 -replace ',' | Should -Be '1.2'
  }
  AfterAll {
      [cultureinfo]::CurrentCulture = $prevCulture
  }
}
```

# Expected behavior

The tests should pass.

# Actual behavior

The `-replace` test fails:

```none
      Expected: '1.2'
      But was:  '12'
```

That is, `1.2` was unexpectedly stringified culture-_sensitively_, as `'1,2'`.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by iSazonov** [comment]
You will laugh but it is "By-Design"
https://github.com/PowerShell/PowerShell/blob/96eb361af8d04d7821343ea2d59f61f0efcdd54c/src/System.Management.Automation/engine/lang/parserutils.cs#L953-L954

The replace operator uses Regex and the C# Regex can use only CurrentCulture.

**Comment by iSazonov** [comment]
Looks like a breaking change.

**Comment by iSazonov** [comment]
A fix was pulled with question what right fix is (there are some options).
