### ISSUE TITLE
Backport PR #9250 into PowerShell 6.x

### ISSUE THREAD

**Issue by glennsarti** [PowerShell/PowerShell#10940]
Currently when using `Set-Location` (or it's cd alias) the FileSystem provider will use the literal text that is entered.  For example:

Given a filesystem with following layout:

``` text
C:\
  |
  + Users
  + Windows
```

Issuing the following PowerShell commands results in:

``` powershell
PS C:\> cd Users
PS C:\Users> cd ..
PS C:\> cd users
PS C:\users>
```

Note - The last command used the path `users` instead of the _actual_ name `Users`

This contrary to:

* Using tab completion
Tab completion resolves to the name on disk

* "magic" paths like tilde (`~`)

``` powershell
PS C:\> cd ~
PS C:\Users\glenn.sarti>
```

* 8.3 Alternate names

``` powershell
PS C:\> cd C:\progra~1
PS C:\Program Files>
```

This can cause issues with child process creation, as the working directory passed to the child process, strictly speaking, does not exist.  This is proved simply by calling cmd.exe:

Given the filesystem layout example above (`C:\Users` is the correct name, not `C:\users`)

``` powershell
C:\users> cmd.exe /c cd
C:\users
```

Note that cmd.exe outputs the "invalid" directory of `C:\users`

Note that, while strictly the fault of PowerShell, I have seen other cross-platform tools behave in strange ways (for example Ruby and NodeJS) where they are performing file path operations and raise errors because the current working directory is not what is on disk.

---

This appears to be "fixed" in PowerShell 7.x via https://github.com/PowerShell/PowerShell/pull/9250.  This issue is to backport these fixes into PowerShell 6.x

**Comment by glennsarti** [comment]
Cross reference - https://github.com/PowerShell/PowerShell-RFC/pull/232

**Comment by iSazonov** [comment]
A rule is to backport only security and critical fixes.

**Comment by glennsarti** [comment]
@rjmholt Suggested I raise this here instead of the RFC I proposed.  Also, I can find no reference to the rule you suggested in the Contributing guide. Are you able to provide a link to this rule for the PowerShell repository?

Perhaps backport is the wrong word, Feature Request then.

**Comment by iSazonov** [comment]
@glennsarti Your request is in right place but MSFT has the policy for backporting commits - backport only security and critical fixes. I think your request does not fall under this rule.

For personal uses you can use current 7.0 preview version. 7.0 GA is planned on January, 2020.

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@iSazonov is correct, we only make security and critical (blocking) fixes in already released versions.  This particular issue would not meet that bar.
