### ISSUE TITLE
ConvertTo-Json doesn't serialize $null

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10942]
<sup>Conceptually related: #9231</sup>

Null values are a legitimate part of JSON, so `ConvertTo-Json` should be able to serialize them.

Currently, `ConvertTo-Json` quietly ignores `$null`s as a distinct input objects (but does serialize them correctly as a _property values_).

# Steps to reproduce

```powershell
# OK
[pscustomobject] @{ prop=$null } | ConvertTo-Json -Compress | Should -Be '{"prop":null}'

# FAIL
$null | ConvertTo-Json -Compress | Should -Be 'null'
ConvertTo-Json -Compress $null | Should -Be 'null'
```

# Expected behavior

All tests should pass.

# Actual behavior

The `$null` tests fail:

```
^ Expected 'null', but got $null
```

That is, instead of returning string `'null'`, there was _no output_.

_Update_: To clarify: `$null` is generally ignored, so the following test fails too, because it returns `'[1,2]'`, not `'[1,null,2]'`:

```powershell
1, $null, 2 | ConvertTo-Json -Compress | Should -Be '[1,null,2]'
```

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by SteveL-MSFT** [comment]
So you expect: '{"":null}' to come out?

**Comment by mklement0** [comment]
@SteveL-MSFT: No, it should be `'null'`, as used in the tests.

**Comment by mklement0** [comment]
Perhaps a _single_ `$null` is rare, but what about something like `1, $null, 2 | ConvertTo-Json`?

Consider what JavaScript does:

`JSON.stringify(null)` -> `'null'`
`JSON.stringify([1, null, 2])` -> `'[1, null, 2]'`
