### ISSUE TITLE
CLI: When launched from VBScript (WSH), well-known assemblies aren't found with Add-Type -AssemblyName

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10949]
Launching `pwsh.exe` via WSH, such as from a VBScript, seemingly causes PowerShell not to find well-known assemblies such as `System.Windows.Forms` that you can normally load with `Add-Type -Assembly`

Note: This is a regression of sorts from Windows PowerShell, though the technological foundation has changed: Windows PowerShell looks in the GAC, whereas PowerShell Core - due to there no longer being a GAC in .NET Core - seemingly looks in `$PSHOME`.

Note that the problem can be reproduced with both WSH executables, `cscript.exe` (console) and `wscript.exe` (GUI).

# Steps to reproduce

Run the following Pester test on Windows:

```powershell
Describe "WSH-launched CLI command should find well-known assemblies" {

  BeforeAll {
    Push-Location testdrive:\
    $outFile = (Convert-Path .) + 'out.txt'
    'powershell', 'pwsh' | ForEach-Object {
      "CreateObject(`"WScript.Shell`").Run(`"$_.exe -noprofile -c Add-Type -AssemblyName System.Windows.Forms; `$Error[0] > $outFile`")" > "test_$_.vbs"
    }
  }

  It "Can locate System.Windows.Forms" {

    'powershell', 'pwsh' | ForEach-Object {

      Remove-Item -ErrorAction Ignore $outFile

      & ./"test_$_.vbs"

      While (-not (Get-Item -EA Ignore $outFile)) {
        Write-Host . -NoNewline
        Start-Sleep -Milliseconds 300
      }
      Write-Host
      Get-Content $outFile | Should -BeNullOrEmpty
    }

  }

  AfterAll {
    Start-Sleep 1 # Sleep a little 
    Pop-Location
  }

}
```

# Expected behavior

The tests should pass.

# Actual behavior

The test with `pwsh.exe` fails.

```none
 Expected $null or empty, but got @('Add-Type : Cannot find path 'C:\Users\jdoe\AppData\Local\Temp\07a8351f-062f-4253-bf76-8994223a491b\System.Windows.Forms.dll' because it does not exist.'
```

That is, the `System.Windows.Forms.dll` assembly wasn't found in PowerShell's own home folder (`$PSHOME`) even though it is present there. (try `Get-Item "$PSHOME\System.Windows.Forms.dll"`)

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by iSazonov** [comment]
What is $pwd in the case?

**Comment by iSazonov** [comment]
> Run(`"$_.exe -noprofile 

If I put full path to the exe I don't see errors. Perhaps vbs script find previous pwsh version without the dll?

**Comment by mklement0** [comment]
> Perhaps vbs script find previous pwsh version without the dll?

Excellent guess, @iSazonov - that's exactly what it was - it never occurred to me to check for that, because the older version (6.2.3) _isn't in my $env:PATH_.

Here's what happened in detail:

* I had both v7.0.0-preview.5 and v6.2.3 installed on my system, with _only_ v7.0.0-preview.5 in the path (in a directory listed in `$env:PATH`)

* Even though v6.2.3 wasn't in the path, it _was_ present in the _registry_, as put there by the installer, namely in the following location:

  * `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\pwsh.exe`

* **The `WScript.Shell` COM Automation component's `.Run()` method apparently _first_ looks in the _registry_ for an executable's path**, and only _then_ in `$env:PATH`, which is why it ended up launching v6.2.3 (where the `System.Windows.Forms.dll` doesn't exist).

---

This behavior contrasts with both cmd.exe and PowerShell itself:

* In _direct execution_ (`pwsh ...`), it is _only_ `$env:PATH` that is consulted.

* In execution via `start` / `Start-Process, `$env:PATH`  is consulted _first_, and only if no match is found is the _registry_ location consulted.

Therefore, the observed behavior is entirely owed to `WScript.Shell` by-(surprising)-design behavior, so I'm closing this.
