### ISSUE TITLE
Make Module Manifest loose validating

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#10958]
# Summary of the new feature/enhancement

Currently, the module manifest is strictly validated with exception of the PrivateData section.  This makes potentially adding new capabilities impossible other than stuffing everything into PrivateData.  Proposal is to make it loose validating and ignore anything it doesn't understand in that version.

**Comment by iSazonov** [comment]
If we don't strictly check PrivateData why should we do strong check for other manifest parts?
We will need to enhance Test-ModuleManifest.

**Comment by SteveL-MSFT** [comment]
The strict validation is something that's always been there to enforce backwards compatibility.  When PrivateData was introduced (as a trapdoor for strict validation), that was special cased for forward compatibility.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and believe that PrivateData is sufficient and given the minimal changes in module manifest in the past, it's unlikely we would accept any changes in the future that necessitate loose validation.

**Comment by KirkMunro** [comment]
I just saw the notification about the original issue posted here, and came in to say that it's about time, but then I read that it's already been discarded as unnecessary. Ugh.

Give me a clean, forward thinking break with `psd2` files already and be done with the duck taped `psd1` file format. Plus, hello, `PowerShellVersion` is checked first in recent versions of PS, so this could be moved forward with `psd1` files.

The current mandate to leave `psd1` files in legacy mode for backward compatibility and discard any possible enhancements to make them better, with the argument that `psm1` files can be used to deal with the extra stuff is really getting old. `psm1` files should only be necessary for scenarios when a manifest can't describe a module in a declarative way, which they should be able to do for binary modules and modules composed of a bunch of `ps1` files most of the time.
