### ISSUE TITLE
Invoke-RestMethod/Invoke-WebRequest should set charset=utf-8 for application/json by default

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#10971]
Recently had an issue trying to use a GitHub API when I put emojis in the POST body:

```powershell
$body = ConvertFrom-Json @{
    tag_name = "tag"
    name = "demo"
    body = "I like 🐛s"
    draft = $true
    prerelease = $true
}

$uri = "https://api.github.com/repos/me/bughunter/releases"
$headers = @{
    GitHubToken = $myToken
    Accept = "application/vnd.github.v3+json"
}

Invoke-RestMethod -Method Post -Uri $uri -Body $body -Headers $headers
```

Sending this published a draft with the description:

```text
I like ??s
```

Took me a while to work out I needed `-ContentType "application/json; charset=utf-8"`, which is fine. Except everything else defaulted (as expected) to UTF-8, so I assumed this would too.

**Comment by rjmholt** [comment]
Worth noting that this is probably classable as a breaking change, but if we're always converting upper ASCII to `?` then I'm not sure what we'd be breaking.

**Comment by SteveL-MSFT** [comment]
Given that our console and output encoding default to utf-8, it seems like the webcmdlets should also follow with utf-8 as default charset unless overridden.  cc @markekraus

**Comment by he852100** [comment]
Xml is not recognized
```powershell
PS /> (irm 'https://storage.live.com/items/A78ACCAEBB24EDD7!420260?.&authkey=!#######')
 ï»¿<?xml version="1.0" encoding="utf-8"?>
```

**Comment by he852100** [comment]
@SteveL-MSFT It's the data of the website.I didn't create it.
