### ISSUE TITLE
Tab completion fails with a specific sequence

### ISSUE THREAD

**Issue by MathiasMagnus** [PowerShell/PowerShell#10976]
I have reported this issue on [PSReadline](https://github.com/PowerShell/PSReadLine/issues/1116), however it turns out it's vanilla PS at fault. I have also created a GIF with keystrokes to show what the actual problem is.

It seems that certain sequences (`ty` to be precise) don't complete as intended. They do so on the Linux 6.2.3 release, but they don't on the Windows 7.0.0-Preview.5

# Steps to reproduce

![tabcomplete](https://user-images.githubusercontent.com/9763499/68071130-ab657780-fd77-11e9-9422-00a917f96b58.gif)

# Expected behavior

Tab complete the unambigous filename even when between `t` and `y`.

# Actual behavior

Completion only happening on Linux.

# Environment data

### Linux
```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Windows
```none
Name                           Value
----                           -----
PSVersion                      7.0.0-Preview.5
PSEdition                      Core
GitCommitId                    7.0.0-Preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MathiasMagnus** [comment]
This is vexing because my nick name (Matty) is in most of my host names and when I prepend host names to benchmark data for instance, I keep hitting this bug. How can I attach a debugger to walk through the code that triggers on tab completion?

**Comment by MathiasMagnus** [comment]
"Give a man a fish, and you feed him for a day. Teach him how to attach a debugger to 3rd party scripts and binaries, and you'll get a constant stream of bug reports for the rest of your life." - Ancient Greek proverb

**Comment by iSazonov** [comment]
> How can I attach a debugger to walk through the code that triggers on tab completion?

We have all needed configs in the repo for VS Code. See our docs how to build.

**Comment by daxian-dbw** [comment]
Hmm, I cannot reproduce the issue on my windows machine.
@MathiasMagnus Please follow instructions [here](https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-core.md) to build PowerShell on windows. Let us know if you run into issues.
