### ISSUE TITLE
Feature Request: add 'Terminal' to $PSVersionTable to make support requests easier.

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#10991]
# Summary of the new feature/enhancement

The powershell team will likely get an increase in bug reports from people running Windows Terminal, or want to see if some behavior is specific to Windows Terminal or the old terminal (which I guess is called 'console'?). You might want to add the `Terminal` as a field to `$PSVersionTable`:

```
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18908
Platform                       Win32NT
Terminal                       Windows Terminal (Preview) 0.6.2951.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Where do we can get a terminal name from?

**Comment by mikemaccana** [comment]
@iSazonov Hrm vscode adds `$env:TERM_PROGRAM` but it looks like Terminal doesn't use that.

@DHowett-MSFT is there a way for shells to detect the Terminal?  Thanks! 🙂

**Comment by DHowett-MSFT** [comment]
Nope: microsoft/terminal#1040. There's no broadly accepted standard for identifying a terminal emulator application. :smile:

**Comment by iSazonov** [comment]
@lzybkr @daxian-dbw Based on your PSReadline experience can you reword the request so that we could understand what useful would we add to $PSTableVersion about current terminal/console?

**Comment by daxian-dbw** [comment]
The bug [report template](https://raw.githubusercontent.com/PowerShell/PSReadLine/master/.github/ISSUE_TEMPLATE.md) in PSReadLine repo provides the following script to help an issue author to collect environment data about whether you are running in terminal:

```powershell
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

   "HostName: $hostName"

```
