### ISSUE TITLE
Powershell 7: half terminated 'cmd' (run from pwsh) makes pwsh ignore every second key stroke

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PowerShell#10990]
# Steps to reproduce

 - Open pwsh (repeatable in both the default powershell 7 terminal and Windows Terminal)
 - Run a `cmd` script
 - Cancel it (using [[Ctrl C]]
 - Don't immediately answer `Terminate batch job (Y/N)?`. Let it repeat. Then cancel it again or press `Y`
 - Type `1234567890`

# Expected behavior

`1234567890` appears in the console

# Actual behavior

`13579` appears in the console.

**This doesn't seem to be a terminal issue - it happens in both Windows Terminal and the default Powershell console**

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18908
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mikemaccana** [comment]
Um I didn't add the `Issue-Question` label. This isn't a question. That wasn't me.

**Comment by mklement0** [comment]
`Issue-Question` is automatically assigned to new bug reports, pending appropriate classification later (not every bug report turns out to be about a bug) - at least that's my inferred understanding of the process.

---

What does _let it repeat mean_?

I just tried with a batch file with the following content, pressing Ctrl+C, then choosing to continue several times, then choosing 'Y' to cancel - I don't see the problem:

```cmd
@echo off
:more
pause
goto more
```

**Comment by iSazonov** [comment]
@mikemaccana Can you repo without PSReadline?

**Comment by mikemaccana** [comment]
@iSazonov Running `remove-module psreadline` then starting my app and pressing Ctrl-C once *works fine* - I just kept being asked to confirm the Termination by `cmd`

**Comment by mklement0** [comment]
It's still unclear (at least to me) how to reproduce your issue - I don't understand the repro steps (_don't immediately answer_, _let it repeat_).

Can you also provide the content of a minimal sample batch file that the issue can be reproduced with? Or perhaps the one I posted above will do?

**Comment by mikemaccana** [comment]
PS, I can't repeat this with your batch file either. The steps from https://arc.codes/quickstart/install will show the error though.

**Comment by mikemaccana** [comment]
Oh @mklement0 I just realised you were quoting me here:

> I don't understand the repro steps (don't immediately answer, let it repeat).

Elaboring:

Press Ctrl C. You will be asked `Terminate batch job (Y/N)`. Do not immediately press `Y` or `N`. Press enter or something instead. The message `Terminate batch job (Y/N)` will appear again. Then press `Ctrl C` or `Y`.

I hope that helps. Does Powershell have either:

 - I `reset` command like Unix shells, to fix corrupted terminals?  
 - A diagnostic command with output I can send you?

**Comment by mikemaccana** [comment]
PS. The command in question `arc sandbox` generates colored output, so maybe that's it.

**Comment by mklement0** [comment]
Have you updated to the latest PSReadLine preview (`Install-Module -Force PSReadLine -AllowPrerelease`) to see if that makes a difference?

**Comment by mikemaccana** [comment]
Thanks @mklement0 . I can confirm the issue still occurs after I run `Install-Module -Force PSReadLine -AllowPrerelease` and restart the shell. 

The usual way I trigger `Terminate batch job (Y/N` is by pressing Ctrl C, twice. Here's some sample output:

![image](https://user-images.githubusercontent.com/172594/69657315-e48cc100-1071-11ea-95ef-98d9de888545.png)

**Comment by mikemaccana** [comment]
@daxian-dbw I'm pretty sure it's PSReadline too - I've started running `remove-module psreadline` before I run my app and the issue has gone from 100% to 0% of the time.

**Comment by daxian-dbw** [comment]
@mikemaccana I cannot reproduce the issue (using a batch file with the content from https://github.com/PowerShell/PowerShell/issues/10990#issuecomment-550133629).
I tried in windows terminal too and also cannot reproduce the issue.

![edit](https://user-images.githubusercontent.com/127450/69756374-418a8480-110f-11ea-9494-19eba014d754.gif)

-------------------------

You mentioned `arc sandbox` in above comment, is that a necessary command in the batch file to reproduce the issue?

**Comment by mikemaccana** [comment]
Heya! Just install arc per the link above. You don't need to edit any other
file.

Since arc outputs colours etc I wonder if that triggers the issue.

**Comment by iSazonov** [comment]
@mikemaccana Is it arc sandbox issue? Can we close the issue?

**Comment by mikemaccana** [comment]
No, a command should not be able to corrupt the terminal. It isn't arc
related.

**Comment by daxian-dbw** [comment]
I still cannot reproduce the issue with the `arc sandbox` command in the `.bat` file.
@mikemaccana Please provide the `.bat` file and the steps that can consistently reproduce the reported issue.

I was using the `7.0.0-rc.2` powershell, see the screen recording below:

![repro](https://user-images.githubusercontent.com/127450/73698484-1cc60680-4696-11ea-940d-1562ee02a688.gif)

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
