### ISSUE TITLE
Start-Process with AppX application URLs cannot be combined with -PassThru or -Wait

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#10996]
Note: Perhaps there's no solution, in which case the error message should improved to provide a specific hint.

UWP / AppX-packaged applications (Microsoft Store applications) are launched by URL scheme (e.g., `calculator:` to start the Calculator app) rather than executable file name.

Combining this style of launching with `-PassThru` in order to obtain a process object identifying the newly launched process fails; ditto with `-Wait` to effect synchronous execution.

# Steps to reproduce

Run the following on Windows:

```powershell
{ Start-Process calculator: -PassThru } | Should -Not -Throw
{ Start-Process calculator: -Wait } | Should -Not -Throw
```

# Expected behavior

The tests should pass.

# Actual behavior

The tests fail (Calculator still launches, but no process object is returned / waiting doesn't occur, and an error is emitted):

```none
Expected no exception to be thrown, but an exception 
"This command cannot be run completely because the system cannot find all the information required."
was thrown
```

# Environment data

```none
PowerShell Core v7.0.0-preview.5 on Microsoft Windows 10 Pro (64-bit; Version 1903, OS Build: 18362.418)
```

**Comment by StewartRyanSony** [comment]
+1. I'm running into this issue as well

**Comment by jborean93** [comment]
This came up in the Discord and it looks like pwsh is expected [Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=net-6.0) to be started but .NET is not doing so. This result bubbles up the stack to this message as there is no process object to passthru or wait on.

You can verify this behaviour with:

```powershell
$psi = [System.Diagnostics.ProcessStartInfo]@{
    FileName = '...'
    UseShellExecute = $true
}
$proc = [System.Diagnostics.Process]::Start($psi)
$null -eq $proc  # $true
```

In my example `FileName` was a jpeg that was associated with a UWP.

It seems like the problem exists in .NET and needs to be fixed there.

**Comment by jborean93** [comment]
Just a further note, it looks like .NET tries its best to get the process handle https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L90-L116.

In some cases `ShellExecuteEx` might have it set to `NULL` and I think this is one of them. Unless there's a better API or mechanism in Windows/explorer to use it might just be a limitation of these types of apps and PowerShell should just generate a better error message on return if `-PassThru` or `-Wait` is being used.

**Comment by guyrleech** [comment]
I get this error with Windows PowerShell 5.1 on Windows 10 when using start-process on the new Microsoft Teams which is an AppX package although the new process does start. Don't get the error with the same code and Teams version on Windows 11

**Comment by TheErstwhile** [comment]
I found a sloppy work around for this issue. Not sure if I am allowed to post those here. I texted it with the XBox App.
`Start-Process xbox:` then sleep for a few seconds `Start-Sleep -Seconds 5`. After the sleep get the running process and pipe that into Wait-Process `Get-Process xboxPcApp | Wait-Process` Script will pause until you close the XBox Window (Note: you need to have XBox App configured to close and not hide in settings).
