### ISSUE TITLE
Restart-Computer -cn -Force -Wait -Timeout is broken in latest build.

### ISSUE THREAD

**Issue by CranePet** [PowerShell/PowerShell#11002]
# Steps to reproduce

```
1. Install Powershell 7 Release 5 x64 on a up-to-date Windows 10 Computer
2. Run Powershell 7
3. Run the following script...

$ComputerNames = "Computer1","Computer2", "Computer3"
$ComputerNames | ForEach-Object -Parallel {
     Restart-Computer -ComputerName $_ -Force -Wait -Timeout 1800
}
4. Wait the allotted Timeout period of 30 minutes.

Where Computer1-3 are test computers on the same network.

Paul Higin Tested this and commented in another tread;

"This appears to be an error in the Restart-Computer cmdlet. When I run it alone in the latest
preview build, it restarts the remote computer as expected, but never returns and eventually 
crashes PowerShell. I get the same behavior when running it within a foreach -parallel 
script block.

This appears to have nothing to do with foreach -parallel, except that foreach -parallel doesn't
currently support progress data (by design) and so there is no indicator of how the computer
restart is proceeding.

I feel this Issue should be closed and two new issues open:
a. Restart-Computer -cn -Force -Wait -Timeout is broken in latest build.
b. ForEach -Parallel to support progress data stream (not sure how this would work and it would 
be a new feature request anyway)."
--




 
```

# Expected behavior

```
The remote computer will reboot and the script will continue without error.
```

# Actual behavior

```
The computers reboot, but PowerShell never reconnects to them.

After 30 Minutes, the following errors are received;

Restart-Computer: Failed to restart the computer Computer1 with the following error
 message: The computer did not finish restarting within the specified time-out period..
Restart-Computer: Failed to restart the computer Computer2 with the following error
 message: The computer did not finish restarting within the specified time-out period..
Restart-Computer: Failed to restart the computer Computer3 with the following error
 message: The computer did not finish restarting within the specified time-out period..

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by karaziox** [comment]
I seem to be hitting this issue with the Powershell 7.0 release. I've tried on a couple computers, with and without credentials (Credssp or Kerberos)
`Restart-Computer -ComputerName computer -Force -Wait`
This seems to never return, the computer reboots but the wait never completes. The progress bar is stuck on "Waiting for powershell connectivity".
From a second powershell command line, I can `Enter-PSSession computer` successfully, so the powershell remoting is correctly back up, but the Restart-Computer doesn't notice it.

**Comment by doctordns** [comment]
is this the first time that you rebooted this system? I have similar errors in the past but only after the first time the server reboots.

**Comment by karaziox** [comment]
I have tried to reboot a couple times the same computer and so far it never completes even though the computer reboots fine. I've seen it on a couple computers. The command works fine when ran from Powershell 5.1.

**Comment by FluffyBeaver** [comment]
As I understand, it's still a issue for PowerShell 7.1, is it?

**Comment by KyleS-ITW** [comment]
> As I understand, it's still a issue for PowerShell 7.1, is it?

Just tested this morning and can confirm this is still an Issue in 7.1

**Comment by mastadook** [comment]
I´m facing the same Problem

`$Servers | foreach-object -parallel {
$broker = "$_.domain.com"
Write-Host "Restarting now $broker" -ForegroundColor Green
try {
restart-computer -computername $broker -Force -ErrorAction Stop -Wait -For WinRM -Delay 2`}

ForEach-Object : Parameter set cannot be resolved using the specified named parameters.

For me it is looking that something is different with the restart-computer cmdlet as in Version 5.1

Will this being fixed?

**Comment by doctordns** [comment]
An update from me - I have several scripts from my books on PowerShell that use the Restart-Computer, and with 7.2 they ALL fail to return to the calling script.

**Comment by sumit84mca** [comment]
Is there any update on this?

**Comment by sumit84mca** [comment]
It works when you pass WinRM for -For parameter 
Restart-Computer -ComputerName <ComputerName> -Wait -For WinRM -Timeout 300 -Delay 2 -Credential $cred -Force
![image](https://user-images.githubusercontent.com/18229166/176890067-8c3f76d3-c104-44de-9bcb-34d7f0299c7a.png)

**Comment by whitTech** [comment]
If someone could manage our expectations even slightly with regard to:

1. Whether or not there is intent to resolve this bug
2. If so, some kind of time frame or indication of where this sits in the list of priorities

, it would be immensely helpful. 

I don't mind if the time frame is something like -Gt 5 years, or if the priority is bottom 5%. Some expectation management allows us to plan accordingly, even that planning is: "Forget it exists. Just plan to use -For "WinRM" indefinitely and free up that brain capacity for something else".

Thanks all.
