### ISSUE TITLE
Function Test-WinRMQuickConfigNeeded needs to be updated

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#11005]
[Function `Test-WinRMQuickConfigNeeded`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs#L4011) is used in `Enable-PSRemoting` to detect if `Set-WSManQuickConfig` needs to be run or not.
Currently on PS Core it always returns `$True` because [`Get-Command Get-NetFirewallRule` check](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs#L4038) fails because `Get-NetFirewallRule` cmdlet, found using command discovery process, is located in Non-PS-Core-Compartible module `NetSecurity`:
```
PS E:\> Import-Module NetSecurity
Import-Module: Module 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1' does not support current PowerShell edition 'Core'. Its supported editions are 'Desktop'. Use 'Import-Module -SkipEditionCheck' to ignore the compatibility of this module.
```
Also, if if the code is changed so that the firewall rule is found as enabled, then  `Test-WinRMQuickConfigNeeded` returns `False` and `Set-WSManQuickConfig` is Not run, then `New-PSSession` fails with `PSRemotingTransportException`, so apparently `Test-WinRMQuickConfigNeeded` does not check all the things that `Set-WSManQuickConfig` is doing.

# Steps to reproduce

1) for `Test-WinRMQuickConfigNeeded` always returns `$True`: run debugging session with a breakpoint on [start of function `Enable-PSSessionConfiguration`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs#L4111).
2) for `Test-WinRMQuickConfigNeeded` out-of-sync with `Set-WSManQuickConfig`:
   * make sure all checks in `Test-WinRMQuickConfigNeeded` are satisfied;
   * change `Test-WinRMQuickConfigNeeded` to return `False`
   * call `Enable-PSRemoting -SkipNetworkProfileCheck`
   * try connecting to the endpoint using `New-PSSession`

# Expected behavior

1) At least in 1 scenario `Test-WinRMQuickConfigNeeded` returns `False`
2) PS Session should be created successfully

# Actual behavior

1) `Test-WinRMQuickConfigNeeded` always returns `True`
2) `New-PSSession` fails with `PSRemotingTransportException`

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Fix:
```powershell
Get-CimInstance -ClassName MSFT_NetFirewallRule -Namespace "root/standardcimv2" -Filter "InstanceID like 'WINRM-HTTP-In-TCP'"
```
