### ISSUE TITLE
Errors are not shown in CI - Windows Test - ElevatedPesterTests

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#11004]
Non-terminating errors, specifically in `BeforeAll` sections, are not displayed in CI `Test` console.
`Verbose` and `Warning` messages are displayed just fine.
Not seeing errors in the output makes it really hard to investigate results, especially for test failures that happen only in CI, but not locally.

PS. looks like in `Windows Test - UnelevatedPesterTests` errors are shown.

# Steps to reproduce

1) add `Write-Error "Test Error for CI output"` to any `BeforeAll` section
2) run this test file in CI `Windows Test - ElevatedPesterTests`

# Expected behavior
error should show up in the output

# Actual behavior
There is no error in the output

**Comment by msftrncs** [comment]
I mentioned this in a PR, https://github.com/PowerShell/PowerShell/pull/10226#issuecomment-545771337.
