### ISSUE TITLE
debian10 libcrypto libssl symlink

### ISSUE THREAD

**Issue by theguly** [PowerShell/PowerShell#11019]
i know that debian10 is not yet ready, i'm opening this issue to have a referral for people using powershell on buster or maybe kali linux.

issue #10080 also affects debian10: on debian buster/kali we have libcrypto.so.1.1 and libssl.so.1.1

the error i had using Invoke-Command against a remote windows host was:
Invoke-Command : This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.

and to me, having libssl1.1 installed, the proposed fix works:
```ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
```
of course if you have libssl1.0.2 you can:
```ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
```

**Comment by theguly** [comment]
just another bit: why don't you use libcrypto.so and libssl.so but rely on .so.1.0.0 ?

**Comment by TravisEz13** [comment]
@theguly libmi.so will not fix a bug wrt this

**Comment by TravisEz13** [comment]
I would suggest moving to SSH based remoting over time as we can fix issues in that code.

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT We cannot fix this in a static tar.gz.  This means we have to produce a package, or add a script to step-up the symbolic links.

**Comment by SteveL-MSFT** [comment]
For the zip and tgz, we should update our installation docs for any final setup the users need to perform.  We should target publishing Deb10, Fedora29, Fedora30 pkgs for PS7 RC.  Leave the existing symlinks in the tgz for now until customers move off Ubuntu 1604 and 1804.

**Comment by TravisEz13** [comment]
I filed https://github.com/PowerShell/PowerShell-Docker/issues/331 to verify this in our docker images.

**Comment by TravisEz13** [comment]
I have a draft PR to address this issue.  https://github.com/PowerShell/PowerShell/pull/11028  
I'll need to run the package build to validate.
