### ISSUE TITLE
Get-Command doesn't properly recognize System.Management.Automation.CommandInfo (its own output type) as pipeline input

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11017]
#10851 reported that feeding `Get-Command` output to itself via the pipeline - useful if you want to force loading of all modules in the context of reflection, for instance - doesn't work as expected.

#10929  tried to fix that, but fell short.

# Steps to reproduce

```powershell
function foo {}; set-alias foo foo

(gcm -all foo | gcm).Count | Should -Be 2

(gcm -all foo | gcm).ComandType | Should -Be Alias, Function
```

# Expected behavior

The tests should succeed.

# Actual behavior

The tests fail:

```none
Expected 2, but got 278                   #  *all* commands are returned
Expected @('Alias', 'Function'), but got $null
```

# Environment data

```none
PowerShell Core 7.0.0-preview.5, with PR #10929 applied
```

**Comment by SteveL-MSFT** [comment]
So what's happening is that the `foo` function doesn't have a Noun or Verb (they are empty strings), but it does have a Noun and Verb property, so when it's piped to `gcm` it binds to `-Noun` and `-Verb`, since they are empty string, `gcm` does a wildcard search thus returning everything.  A simpler repro:

```powershell
function foo{}; gcm foo | gcm
```

Adding a new parameterset to accept CommandInfo won't help as the default parameter set is Noun/Verb which will match any CommandInfo object.

A possible fix would be if Noun and Verb are both empty, inspect the pipeline object further and use whatever is available to match: Name and CommandType

**Comment by vexx32** [comment]
Given there is currently no pipeline parameter accepting this object as input in its complete form, would that information be available to Get-Command?

**Comment by SteveL-MSFT** [comment]
@vexx32 excellent point, it wouldn't as only Noun and Verb would be there.  Hmmm, I guess the only way to fix this I can think of is a breaking change so that CommandInfo parameterset is default.

**Comment by mklement0** [comment]
@SteveL-MSFT: It's fine to leave the default parameter set - a specifically `CommandInfo`-typed parameter would still bind correctly.

**Comment by SteveL-MSFT** [comment]
@mklement0 it would bind correctly if the default parameter set doesn't bind first which it will

**Comment by mklement0** [comment]
@SteveL-MSFT:

I took a quick (incomplete) stab at this, and it seems to be working correctly; here are the relevant pieces:

Declare a new parameter in its own parameter set:

```c#
[Parameter(
    Mandatory = true,
    Position = 0,
    ValueFromPipeline = true,
    ParameterSetName = "CommandInfo")]
[ValidateNotNullOrEmpty]
public new CommandInfo[] CommandInfo { get; set; } // Note: `new` is necessary, because there is an inherited InternalCommand.CommandInfo property.
```

Make `-CommandType` also support the new parameter set (the others do by default or the combination doesn't make sense).

```c#
[Parameter(ValueFromPipelineByPropertyName = true, ParameterSetName = "CommandInfo")]
```


```c#
                case "CommandInfo":
                    _accumulatedResults.AddRange(CommandInfo);
                    break;
```

Note: More work is needed there, to support type filtering and any other filters that can be meaningfully applies.

In `EndProcessing()` tweak the conditional for default exclusions.

```c#
            // We do not show the pithy aliases (not of the format Verb-Noun) and applications by default.
            // We will show them only if the Name, All and totalCount are not specified.
            if ((this.Name == null && this.CommandInfo == null) && (!_all) && TotalCount == -1 && !UseFuzzyMatching)
```

With the above, `CommandInfo` input binds correctly, both via the pipeline and positionally.

**Comment by mklement0** [comment]
@SteveL-MSFT 

It doesn't _necessarily_ bind first, but, as I just realized, it does if you combine it with a parameter _not_ supported in a new `CommandInfo`-typed parameter set.

So the choices are:

* (a) change the default parameter set

* (b) make the new parameter set support _all_ other parameters (except `-Name`), even though some combinations don't make sense (such as `-UseFuzzyMatching`).

I'm unclear on the ramifications of (a)

**Comment by SteveL-MSFT** [comment]
Changing the default parameter set makes the most sense to me, but also unclear how many will be impacted.

**Comment by iSazonov** [comment]
We could add optional parameter -Name in the default parameter set.
