### ISSUE TITLE
Skype Online PowerShell Module: Unable to Create Session

### ISSUE THREAD

**Issue by JeffBrownTech** [PowerShell/PowerShell#11020]
When trying to create a remote PS session using the Skype Online PowerShell module, the following error occurs:

```
PS C:\ps> $skypesession = New-CsOnlineSession
Please enter the user principal name (ex. User@Domain.Com): admin@teamslab.us
Get-CsOnlinePowerShellAccessToken: C:\Program Files\Common Files\Skype for Business Online\Modules\SkypeOnlineConnector\SkypeOnlineConnectorStartup.psm1
Line |
 214 |             $accessToken = Get-CsOnlinePowerShellAccessToken @params
     |                            ^ One or more errors occurred. (Could not load type
     | 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral,
     | PublicKeyToken=b77a5c561934e089'.)
```

This is with the latest version of the Skype Online module and PowerShell 7 Preview 5.

[ps7newcsonlinesession.txt](https://github.com/PowerShell/PowerShell/files/3824871/ps7newcsonlinesession.txt)

![ps7skypeonline](https://user-images.githubusercontent.com/12574689/68482416-8f465800-0207-11ea-9bf5-5fa62ec37951.png)

**Comment by rjmholt** [comment]
Looks like the module isn't .NET Core compatible.

The [Sha256Cng class](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256cng?view=netframework-4.8&viewFallbackFrom=netcore-3.0) isn't available in .NET Core 3.0.

To import this, you might want to look into the [WindowsCompatibility module](https://github.com/PowerShell/WindowsCompatibility).

**Comment by Ashish1662** [comment]
Hi @JeffBrownTech, did you solve your issue? I am facing exactly same issue. It will be great help if you could provide some inputs. I am using sfbOnlineConnector in PS az function app. It uses PS core internally.

**Comment by rjmholt** [comment]
> I am using sfbOnlineConnector in PS az function app. It uses PS core internally.

It's likely that's running PowerShell 6.2.4, which doesn't have the implicit remoting compatibility fallback.

You might want to instead try the WindowsCompatibility module linked above.

**Comment by doctordns** [comment]
The WIndows compatibility module is not being maintained as I understand it. It has been replaced by a more sane approach that integrates the logic into Import-Module. 

I'd recommend updating to 7.0 if at all possible.
