### ISSUE TITLE
Add a -Shuffle switch to Get-Random for convenient collection shuffling

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11022]
# Summary of the new feature/enhancement

`Get-Random` currently requires you to specify a `-Count` argument in order to extract a random subset from an input collection.

Sometimes you want to _shuffle_ an input collection, i.e. to return _all_ input objects, in randomized order, and it would be nice to be able to express that intent directly, without having to provide a `-Count` (which may not even be known; you can work around that with `-Count ([int]::MaxValue)`, but that is awkward).

To that end, a new `-Shuffle` parameter could be introduced:

```powershell
# WISHFUL THINKING - sample output.
PS> 1..5 | Get-Random -Shuffle
4
2
5
3
1

**Comment by eugenesmlv** [comment]
I'm working on this one

**Comment by eugenesmlv** [comment]
What should happen if one had set both `-Count` and `-Shuffle` parameters? Should the command return just <Count> random objects and ignore the `-Shuffle` switch or return the entire collection, in randomized order, despite the `-Count`? Another possible way is to throw an error, but I don't think it is a good solution.

**Comment by vexx32** [comment]
I think the most elegant solution would simply be to put the -Shuffle parameter in a completely different parameter set, so that it can't be used with -Count, via the `Parameter` attribute:

```csharp
[Parameter(Mandatory = true, ParameterSetName = "ShuffleSet")]
public SwitchParameter Shuffle { get; set; }
```

Then when determining your code path you can use `switch (ParameterSetName)` to determine which code path to take. 🙂
