### ISSUE TITLE
[Feature Request] Expose Internal Helper Class SignatureHelper to Reference Outside of PowerShell

### ISSUE THREAD

**Issue by FusionCarcass** [PowerShell/PowerShell#11023]
# Summary of the new feature/enhancement

Request internal helper class SignatureHelper be publicly exposed so that the methods can be referenced outside of PowerShell environments in .NET projects. This will enable easier use and integration when not in a PowerShell context.

Implementing digital signature verification is difficult to do within .NET when it comes to handling both Catalog and Embedded signatures. You all have solved this problem through the use of calling native methods. It would be a lot of work for me to do the same thing. Unfortunately, the helper class is internal which forces me to reference your implementation via Reflection. The goal of this request is to enable me as a developer to directly reference the SignatureHelper class and its methods.

# Proposed technical implementation details (optional)

- The SignatureHelper class and methods inside of the Authenticode.cs file be made public instead of internal.

Currently, I have to use reflection in order to reference this method in a C# project, which makes it difficult to use and wastes processing and memory. Publicly exposed methods would simplify this process.

```csharp
public static class AuthenticodeTools {
        static AuthenticodeTools() {
            try {
                string path = System.IO.Path.Combine(SimpleEndpointManagerCore.Utility.AssemblyDirectory, "System.Management.Automation.dll");
                Assembly assembly = Assembly.LoadFile(path);
                Type asmType = assembly.GetType("System.Management.Automation.SignatureHelper");
                AuthenticodeTools._methodGetSignature = asmType.GetMethod("GetSignature", BindingFlags.NonPublic | BindingFlags.Static);
            } catch(Exception ex) {
                string error = "An exception occurred while looking up the System.Management.Automation.SignatureHelper.GetSignature() method." + ex.Message;
                Log.Error.AddEntry(new ErrorLogEntry(error));
            }
        }

        public static SignatureInfo GetSignature(string path) {
            if(AuthenticodeTools._methodGetSignature == null) {
                return null;
            }

            object signature = AuthenticodeTools._methodGetSignature.Invoke(null, new object[] { path, null });
            Type type = signature.GetType();
            SignatureInfo result = new SignatureInfo();
            result.IsOSBinary = (bool)type.GetProperty("IsOSBinary").GetValue(signature);
            result.SignatureType = (SignatureType)type.GetProperty("SignatureType").GetValue(signature);
            result.SignerCertificate = (X509Certificate)type.GetProperty("SignerCertificate").GetValue(signature);
            result.Status = (SignatureStatus)type.GetProperty("Status").GetValue(signature);
            result.StatusMessage = (string)type.GetProperty("StatusMessage").GetValue(signature);
            result.TimeStamperCertificate = (X509Certificate)type.GetProperty("TimeStamperCertificate").GetValue(signature);

            return result;
        }

        private static MethodInfo _methodGetSignature;
    }
```

Source code:
https://github.com/PowerShell/PowerShell/blob/c679536bb80445134c6b3f03b5127d22aa858816/src/System.Management.Automation/security/Authenticode.cs#L46-L646

**Comment by iSazonov** [comment]
Why do you need to reference PowerShell? 
.Net Core now support on all platforms the old API https://blogs.msdn.microsoft.com/windowsmobile/2006/05/17/programmatically-checking-the-authenticode-signature-on-a-file/

**Comment by FusionCarcass** [comment]
There are two types of digital signatures: (1) Catalog and (2) Embedded or
Authenticode. The code referenced in the link you provided does not support
catalog signatures, but the internal class SignatureHelper in the power
show library supports both catalog and embedded signatures. That is why I
would like that API exposed so I don't have to reimplement all of the ugly
native interrupt that you all already solved with the SignatureHelper class.

I mean, I still reference it now using reflection, but it's kind of an ugly
hack and it's not quite as important.

**Comment by iSazonov** [comment]
If you project is PowerShell-based you could use  GetAuthenticodeSignatureCommand cmdlet.

**Comment by FusionCarcass** [comment]
My project is a .NET Framework library. I thought about loading up the
PowerShell runtime within my library, but that was even more overhead than
the reflection technique I posted.

**Comment by iSazonov** [comment]
I think your request would make sense for PowerShell related project but otherwise no.
The code is under MIT and you could fork and create new library.
