### ISSUE TITLE
Why am I getting "Stream too long" when using AllowWriteStreamBuffering=$false

### ISSUE THREAD

**Issue by frippe75** [PowerShell/PowerShell#11025]
# Support Question

Hitting the "Stream was too long" at 2GB. 
I was hoping using `AllowWriteStreamBuffering=$false`  in HttpWebRequest

```PowerShell
My-Upload : Stream was too long. 
At line:1 char:1
+ My-Upload -File ./file.iso                                                                                                                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo          : NotSpecified: (:) [My-Upload], IOException  
+ FullyQualifiedErrorId : IOException,My-Upload 
``` 

Running under Linux and have seen document pointing out 
gcAllowVeryLargeObjects in the app.config file but can this be set somewhere?

```PowerShell
PS /home/frta/> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@frippe75 Thanks for your report. I think it is dup https://github.com/PowerShell/PowerShell/issues/4129

**Comment by frippe75** [comment]
Well... Opening an issue one day. Then a day later (on a Sunday) it closed.
Also based on a "I think it is a dup".

Not really sure about that. Tried to look into both Invoke-RestMethod as well as Invoke-WebRequest but could not find any support for or against that claim.

**Comment by vexx32** [comment]
@frippe75 see here: https://github.com/PowerShell/PowerShell/issues/4129#issuecomment-491452090

Without seeing the actual code you're using we can provide only limited advice, but it does look like you're either using one of the web cmdlets or the same API that they use.

As @daxian-dbw notes in the linked issue, .NET has limitations on the maximum memory consumed per object. The property you mentioned needs to be set in the project file itself before compiling the project, so you'd need to, build pwsh from source with the property set to workaround it if you want to use the API this way from PowerShell at the moment.

I'm unsure what the possible side effects from setting that flag in a project may be, so I don't know whether it's feasible to have PowerShell set that flag then it is built normally.
