### ISSUE TITLE
Powershell Script in same shell exits with error code 1 on certain commands

### ISSUE THREAD

**Issue by thboop** [PowerShell/PowerShell#11036]
It appears that commands that redirect std-err (such as `npm ping`) called consecutively in a script that does not open in a new window causes powershell to exit with code 1, rather then execute the commands and exit with code 0.

I've linked a quick project showing this [problem](https://github.com/thboop/PowerShell-Repro)

# Steps to reproduce
See
https://github.com/thboop/PowerShell-Repro/blob/master/test/Program.cs#L11

``` C#
            var command = "'" + Directory.GetCurrentDirectory().Replace(@"\\", @"\") + @"\test.ps1'""";
            var _proc = new Process();
            // REPLACE WITH DIRECTORY OF YOUR PWSH
            _proc.StartInfo.FileName = @"C:\Program Files\PowerShell\6\pwsh.EXE";
            var arguement = @"-command "". " + command;
            _proc.StartInfo.Arguments = arguement;
            _proc.StartInfo.UseShellExecute = false;
            _proc.StartInfo.RedirectStandardInput = true;
            _proc.StartInfo.RedirectStandardError = true;
            _proc.StartInfo.RedirectStandardOutput = true;
            
            // ******************************************************************
            // Setting this line to true causes powershell core to exit code 1
            _proc.StartInfo.CreateNoWindow = true; 
            // ******************************************************************

            var response = _proc.Start();
            _proc.WaitForExit();
            Console.WriteLine(_proc.StandardOutput.ReadToEnd());
            Console.WriteLine(_proc.StandardError.ReadToEnd());
            Console.WriteLine($"exited with exit code {_proc.ExitCode}");
```

Shell Script it invokes
```
$ErrorActionPreference = 'stop'

npm ping
npm ping
npm ping
```

# Expected behavior

```none
Powershell Exits with Code 0 and runs the commands
```

# Actual behavior

```none
Powershell exits with code 1
```

# Environment data

```none
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

node -v
v10.16.0
```

**Comment by rjmholt** [comment]
I'm unable to reproduce this on my machine:

```
> .\bin\Debug\netcoreapp3.0\publish\testexe.exe

npm notice PING https://registry.npmjs.org/
npm notice PONG 0.217ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.189ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.302ms

exited with exit code 0
```
> dotnet run

npm notice PING https://registry.npmjs.org/
npm notice PONG 0.188ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.192ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.535ms

exited with exit code 0
```

Tried it with both 6.2.3 and 7.0.0-preview.5.

My platform:

```

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.19013
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Any further details about when PowerShell exits or any other error messages logged or shown?

**Comment by thboop** [comment]
@rjmholt Thanks for looking into this!

I'm able to confirm that 7.0.0-preview 5 is working correctly, but powershell 6 is not.

I recompiled in .net core 3.0 to match your build
Powershell 6
```
PS PowerShell-Exit\bin\Debug\netcoreapp3.0> .\PowerShell-Exit.exe

npm notice PING https://registry.npmjs.org/
npm notice PONG 0.353ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.336ms
npm notice PING https://registry.npmjs.org/

exited with exit code 1
```

Notice how we don't receive output from the last npm ping


Powershell 7.0.0-preview5
`_proc.StartInfo.FileName = @"C:\Program Files\PowerShell\7-preview\pwsh.EXE";`

```
PS C:\Users\thboop\source\repos\PowerShell-Exit\PowerShell-Exit\bin\Debug\netcoreapp3.0> .\PowerShell-Exit.exe

npm notice PING https://registry.npmjs.org/
npm notice PONG 0.518ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.396ms
npm notice PING https://registry.npmjs.org/
npm notice PONG 0.402ms

exited with exit code 0
```

Could their be a conditional environment option causing this on powershell 6? Is there any more information I can provide from my environment? We are seeing this on more then just one machine.

I'm very glad to see Powershell 7 is working!

**Comment by thboop** [comment]
Resolved in powershell 7
