### ISSUE TITLE
Credential Failure on Off-Domain Boxes using New-PSDrive

### ISSUE THREAD

**Issue by jackfalveyiv** [PowerShell/PowerShell#11045]
In my environment, we have created a custom Powershell script that runs on a scheduled interval.  The task does the following:
 - Uses an on-domain service account to run as a scheduled task on the destination server (file server)
 - Uses an off-domain account on a remote DMZ server that has access to a particular custom log repository, with modify rights
 - Copies all files created in the past 14 days to a local folder, and deletes anything in the source directory older than 21 days
 - Logs how many files were moved to what directories in a custom log in the destination directory

When setting up the script, we are consistently able to run it as designed, however we do encounter a strange set of errors on the source server.  First, here is the code:

```
$UserName = 'Service-Account'
$Password = Get-Content 'C:\CredFile' | ConvertTo-SecureString
$ServiceCred = New-Object System.Management.Automation.PSCredential($UserName, $Password)
$SourceIP = 'x.x.x.x'
$SourceShare1 = 'SourceShare1'
$SourceShare2 = 'SourceShare2'
$DestPath1 = 'D:\Path1\'
$DestPath2 = 'D:\Path2\
$Log = 'D:\Log.log'
$LogDate = Get-Date
$DaysBack = "-21"
$DateToDelete = $LogDate.AddDays($Daysback)
    Try
    {
    New-PSDrive -Name "AppLogs" -PSProvider "FileSystem" -Root \\$SourceIP\$SourceShare1 -Credential $ServiceCred
    $Files1 = Get-ChildItem AppLogs:\* | Where-Object {$_.LastWriteTime -gt (Get-Date).AddDays(-14)} -Verbose
    Copy-Item $Files1 -Destination $DestPath1 -ErrorAction Stop -Force -Verbose
    Get-ChildItem -Path \\$SourceIP\$SourceShare1\* | Where-Object {$_.LastWriteTime -lt $DateToDelete } | Remove-Item -Recurse -Verbose
    $Files1Count = $Files1.Count
    "$Files1Count files were written to $DestPath1 on $LogDate." | Out-File -FilePath $Log -Append
    }
    Catch
    {
    "No files were written to $DestPath1 on $LogDate." | Out-File -FilePath $Log -Append
    }
    Try
    {
    New-PSDrive -Name "IISLogs" -PSProvider "FileSystem" -Root \\$SourceIP\$SourceShare2 -Credential $ServiceCred
    $Files2 = Get-ChildItem IISLogs:\* | Where-Object {$_.LastWriteTime -gt (Get-Date).AddDays(-14)}
    Copy-Item $Files2 -Destination $DestPath2 -ErrorAction Stop -Force -Verbose
    Get-ChildItem -Path \\$SourceIP\$SourceShare2\* | Where-Object {$_.LastWriteTime -lt $DateToDelete } | Remove-Item -Recurse -Verbose
    $Files2Count = $Files2.Count
    "$Files2Count files were written to $DestPath2 on $LogDate." | Out-File -FilePath $Log -Append
    }
    Catch
    {
    "No files were written to $DestPath2 on $LogDate." | Out-File -FilePath $Log -Append
    }

    Remove-PSDrive -Name AppLogs -Verbose
    Remove-PSDrive -Name IISLogs -Verbose
```

As you can see, we use New-PSDrive to perform the drive mounting.  For some reason, on the off-domain machine (source) we get two errors consistently in the application logs, 4776 and 4625, indicating a NULL SID.  We have tested this and it only occurs at the New-PSDrive command, indicating to me that despite calling the off-domain credentials specifically to execute this task, Powershell is still passing the credentials of the account running the task first, failing, then using the correct credentials and executing as expected.  The strange thing about this error is that the error logging is returning a "Unknown user name or bad password" for the on-domain account we use to run the scheduled task, yet in the script we run New-PSDrive using the off-domain account only.  We do not understand why, despite the script expressly using separate credentials, that the destination machine still attempts to use credentials it is running the task as.  Despite these errors, the script executes successfully, as intended, despite these errors.

For the time being, we decided to create a mirrored local account on the destination server, which the task now runs as.  This has alleviated these errors completely, however we would rather not have mirrored local accounts.  Has anyone else encountered this situation, and if so is there a better way to approach it?

**Comment by iSazonov** [comment]
@jackfalveyiv Please share $PSVersionTable

**Comment by jackfalveyiv** [comment]
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@jackfalveyiv The repository is for PowerShell Core. You can report Windows PowerShell issues to UserVoice site or use Windows 10 feedback tool.

If you can reproduce the issue with latest PowerShell Core 7 build you can report in the repository.

**Comment by jackfalveyiv** [comment]
OK, after running the same code in Powershell Core 7 I am experiencing the same issue:

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@jackfalveyiv Thanks for repo on PowerShell Core.

Does the script work well in interactive session?

**Comment by jackfalveyiv** [comment]
It does, and still generates the 4776 and 4625 errors.

**Comment by jackfalveyiv** [comment]
I didn't mention this before, but we did manage to narrow this down to the specific New-PSDrive cmdlet since posting this error.  Without any of the copying cmdlets or measurement of directories, executing New-PSDrive is triggering the errors.

**Comment by iSazonov** [comment]
We use P/Invoke https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetaddconnection2a
I guess this is a feature of this function.

**Comment by MSIH** [comment]
@iSazonov How do you use in Powershell. please provide an example. Thanks

**Comment by iSazonov** [comment]
@MSIH I did not understand your question.

**Comment by emixam360** [comment]
Hello

I am facing the same issue with the New-PSDrive command.
The command is executed with success on a Workgroup Computer with a local account but using a Credential parameter from a domain account

`
$Root = '\\SERVER.domain.local\Data\Reports'
New-PSDrive -PSProvider FileSystem -Name 'REPORTS' -Root $Root -Credential (get-credential)
`

Events 4776 and 4625 are generated on the remote server with failed login from the local account.

**Comment by LeFlutiau** [comment]
I have the same problem, using New-PSDrive or net use, the credentials sent to the remote server are as far as i see, random between the current user and the one provided as argument. Sometimes it goes unnoticed, the local credentials is sent 3 or 4 times before the one provided as argument is sent, but if the local one is sent 5 times, the distant account gets locked.

`net use K: [\\name_of_share\](file:///) /USER:userid@otherdomain`

or

`$c = Get-Credential -credential otherdomain\userid
New-PSDrive -name "K" -PSProvider FileSystem -Root [\\name_of_share\](file:///) -Credential $c -Scope Global -persist`

A network capture gives this result :

`
gth	Info
180	14:05:14.799258	<src>	<dst>	SMB2	306	Negotiate Protocol Response
181	14:05:14.799330	<dst>	<src>	SMB2	334	Negotiate Protocol Request
182	14:05:14.800837	<src>	<dst>	SMB2	366	Negotiate Protocol Response
353	14:05:55.236630	<dst>	<src>	SMB2	522	Session Setup Request, INITATOR_NEGO, INITIATOR_META_DATA
354	14:05:55.239793	<src>	<dst>	SMB2	153	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED
355	14:05:55.241443	<dst>	<src>	SMB2	199	Session Setup Request, NTLMSSP_NEGOTIATE
356	14:05:55.244124	<src>	<dst>	SMB2	349	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
**357	14:05:55.248704	<dst>	<src>	SMB2	651	Session Setup Request, NTLMSSP_AUTH, User: \userid@otherdomain**
358	14:05:55.253175	<src>	<dst>	SMB2	130	Session Setup Response, Error: STATUS_LOGON_FAILURE
363	14:05:55.262384	<dst>	<src>	SMB2	334	Negotiate Protocol Request
364	14:05:55.263895	<src>	<dst>	SMB2	366	Negotiate Protocol Response
365	14:05:55.274547	<dst>	<src>	SMB2	516	Session Setup Request, INITATOR_NEGO, INITIATOR_META_DATA
366	14:05:55.276521	<src>	<dst>	SMB2	153	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED
367	14:05:55.277068	<dst>	<src>	SMB2	199	Session Setup Request, NTLMSSP_NEGOTIATE
368	14:05:55.278946	<src>	<dst>	SMB2	349	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
**369	14:05:55.282467	<dst>	<src>	SMB2	655	Session Setup Request, NTLMSSP_AUTH, User: localdomain\userid**
370	14:05:55.285755	<src>	<dst>	SMB2	130	Session Setup Response, Error: STATUS_LOGON_FAILURE
375	14:05:55.292444	<dst>	<src>	SMB2	334	Negotiate Protocol Request
376	14:05:55.293657	<src>	<dst>	SMB2	366	Negotiate Protocol Response
377	14:05:55.294944	<dst>	<src>	SMB2	522	Session Setup Request, INITATOR_NEGO, INITIATOR_META_DATA
378	14:05:55.296582	<src>	<dst>	SMB2	153	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED
379	14:05:55.296993	<dst>	<src>	SMB2	199	Session Setup Request, NTLMSSP_NEGOTIATE
380	14:05:55.298618	<src>	<dst>	SMB2	349	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
**381	14:05:55.300262	<dst>	<src>	SMB2	655	Session Setup Request, NTLMSSP_AUTH, User: localdomain\userid**
382	14:05:55.303674	<src>	<dst>	SMB2	130	Session Setup Response, Error: STATUS_LOGON_FAILURE
387	14:05:55.309378	<dst>	<src>	SMB2	334	Negotiate Protocol Request
388	14:05:55.310786	<src>	<dst>	SMB2	366	Negotiate Protocol Response
389	14:05:55.312379	<dst>	<src>	SMB2	522	Session Setup Request, INITATOR_NEGO, INITIATOR_META_DATA
390	14:05:55.314477	<src>	<dst>	SMB2	153	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED
391	14:05:55.315615	<dst>	<src>	SMB2	199	Session Setup Request, NTLMSSP_NEGOTIATE
392	14:05:55.318076	<src>	<dst>	SMB2	349	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
393	14:05:55.320256	<dst>	<src>	SMB2	655	Session Setup Request, NTLMSSP_AUTH, User: localdomain\userid
394	14:05:55.323627	<src>	<dst>	SMB2	130	Session Setup Response, Error: STATUS_LOGON_FAILURE
404	14:06:01.641667	<dst>	<src>	SMB2	334	Negotiate Protocol Request
405	14:06:01.642842	<src>	<dst>	SMB2	366	Negotiate Protocol Response
406	14:06:01.654997	<dst>	<src>	SMB2	522	Session Setup Request, INITATOR_NEGO, INITIATOR_META_DATA
407	14:06:01.656781	<src>	<dst>	SMB2	153	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED
408	14:06:01.657501	<dst>	<src>	SMB2	199	Session Setup Request, NTLMSSP_NEGOTIATE
409	14:06:01.659605	<src>	<dst>	SMB2	349	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
410	14:06:01.660808	<dst>	<src>	SMB2	651	Session Setup Request, NTLMSSP_AUTH, User: \userid@otherdomain
411	14:06:01.663834	<src>	<dst>	SMB2	159	Session Setup Response
412	14:06:01.664241	<dst>	<src>	SMB2	164	Tree Connect Request Tree: \------\IPC$
413	14:06:01.665596	<src>	<dst>	SMB2	138	Tree Connect Response
414	14:06:01.665756	<dst>	<src>	SMB2	178	Ioctl Request FSCTL_QUERY_NETWORK_INTERFACE_INFO
415	14:06:01.665879	<dst>	<src>	SMB2	210	Ioctl Request FSCTL_DFS_GET_REFERRALS, File: \name_of_share\
416	14:06:01.666952	<src>	<dst>	SMB2	322	Ioctl Response FSCTL_QUERY_NETWORK_INTERFACE_INFO
417	14:06:01.667017	<src>	<dst>	SMB2	398	Ioctl Response FSCTL_DFS_GET_REFERRALS
444	14:06:02.769565	<dst>	<dst>	SMB2	306	Negotiate Protocol Response
445	14:06:02.769732	<dst>	<dst>	SMB2	350	Negotiate Protocol Request
446	14:06:02.771438	<dst>	<dst>	SMB2	366	Negotiate Protocol Response
449	14:06:02.783117	<dst>	<dst>	SMB2	530	Session Setup Request, INITATOR_NEGO, INITIATOR_META_DATA
450	14:06:02.785003	<dst>	<dst>	SMB2	153	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED
451	14:06:02.785354	<dst>	<dst>	SMB2	199	Session Setup Request, NTLMSSP_NEGOTIATE
452	14:06:02.787016	<dst>	<dst>	SMB2	353	Session Setup Response, Error: STATUS_MORE_PROCESSING_REQUIRED, NTLMSSP_CHALLENGE
453	14:06:02.788280	<dst>	<dst>	SMB2	671	Session Setup Request, NTLMSSP_AUTH, User: \userid@otherdomain
454	14:06:02.793988	<dst>	<dst>	SMB2	159	Session Setup Response
455	14:06:02.794441	<dst>	<dst>	SMB2	180	Tree Connect Request Tree: \\AC-3609.------\IPC$
456	14:06:02.796006	<dst>	<dst>	SMB2	138	Tree Connect Response
457	14:06:02.796182	<dst>	<dst>	SMB2	178	Ioctl Request FSCTL_QUERY_NETWORK_INTERFACE_INFO
458	14:06:02.796637	<dst>	<dst>	SMB2	176	Tree Connect Request Tree: \\AC-3609.name_of_share
459	14:06:02.797779	<dst>	<dst>	SMB2	930	Ioctl Response FSCTL_QUERY_NETWORK_INTERFACE_INFO
461	14:06:02.798173	<dst>	<dst>	SMB2	138	Tree Connect Response
463	14:06:02.798500	<dst>	<dst>	SMB2	298	Create Request File: name_of_share;Close Request
464	14:06:02.800073	<dst>	<dst>	SMB2	338	Create Response File: name_of_share;Close Response
465	14:06:02.831692	<dst>	<dst>	SMB2	414	Create Request File: name_of_share\Desktop.ini
466	14:06:02.833449	<dst>	<dst>	SMB2	130	Create Response, Error: STATUS_OBJECT_NAME_NOT_FOUND
467	14:06:02.834264	<dst>	<dst>	SMB2	282	Create Request File: name_of_share\AutoRun.inf
468	14:06:02.835919	<dst>	<dst>	SMB2	130	Create Response, Error: STATUS_OBJECT_NAME_NOT_FOUND
471	14:06:03.348418	<dst>	<dst>	SMB2	258	Create Request File: name_of_share
472	14:06:03.349721	<dst>	<dst>	SMB2	298	Create Response File: name_of_share
473	14:06:03.349919	<dst>	<dst>	SMB2	146	Close Request File: name_of_share
474	14:06:03.351157	<dst>	<dst>	SMB2	182	Close Response
492	14:06:13.363671	<dst>	<src>	SMB2	126	Tree Disconnect Request
493	14:06:13.363993	<dst>	<dst>	SMB2	126	Tree Disconnect Request
494	14:06:13.366915	<src>	<dst>	SMB2	126	Tree Disconnect Response
495	14:06:13.367316	<dst>	<dst>	SMB2	126	Tree Disconnect Response
496	14:06:13.367483	<dst>	<src>	SMB2	126	Session Logoff Request
497	14:06:13.370183	<src>	<dst>	SMB2	126	Session Logoff Response
676	14:07:13.972246	<dst>	<dst>	SMB2	414	Create Request File: name_of_share\Desktop.ini
677	14:07:13.974117	<dst>	<dst>	SMB2	130	Create Response, Error: STATUS_OBJECT_NAME_NOT_FOUND
678	14:07:13.975074	<dst>	<dst>	SMB2	282	Create Request File: name_of_share\AutoRun.inf
679	14:07:13.976655	<dst>	<dst>	SMB2	130	Create Response, Error: STATUS_OBJECT_NAME_NOT_FOUND
681	14:07:14.502731	<dst>	<dst>	SMB2	258	Create Request File: name_of_share
682	14:07:14.505312	<dst>	<dst>	SMB2	298	Create Response File: name_of_share
683	14:07:14.506069	<dst>	<dst>	SMB2	146	Close Request File: name_of_share
684	14:07:14.508336	<dst>	<dst>	SMB2	182	Close Response
`

**Comment by angolo40** [comment]
any news about this?
