### ISSUE TITLE
Powershell 7 Preview 5 system.Data.SqlClient.SqlCommand Error with IAD Auth

### ISSUE THREAD

**Issue by sonnyjrob** [PowerShell/PowerShell#11049]
# Steps to reproduce
**Populate a connection string:**
    $ConnectionString ="Data Source=some.database.Windows.Net; Authentication=Active Directory Integrated; Initial Catalog=tableName"

**Creat a sql client connection:**
    $conn=New-Object System.Data.SqlClient.SQLConnection

**Assign Connection String to object:**
     $conn.ConnectionString=$ConnectionString

Error thrown:
     Keyword not supported: 'authentication'.

# Expected behavior
Connection string is accepted and the data set is populated from the SQL table

# Actual behavior
Setting the connection string causes the script to fail making a SQL connection and populating a data set.

# Environment data

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@sonnyjrob Please share Get-Error output.

**Comment by sonnyjrob** [comment]
Get-Error Output:
Exception             : 
    ErrorRecord    : 
        Exception             : 
            Message : Exception setting "ConnectionString": "Keyword not supported: 'authentication'."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ExceptionWhenSetting
        InvocationInfo        : 
            ScriptLineNumber : 1443
            OffsetInLine     : 3
            HistoryId        : -1
            ScriptName       : E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1
            Line             : $conn.ConnectionString=$ConnectionString
            PositionMessage  : At E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1:1443 char:3
                               +         $conn.ConnectionString=$ConnectionString
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : E:\CPR\Scripts\Monitor-CPRExceptions
            PSCommandPath    : E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Get-SQLData, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 1443
                                at Get-Dictionaries, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 1937
                                at <ScriptBlock>, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 6967
    TargetSite     : 
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Exception setting "ConnectionString": "Keyword not supported: 'authentication'."
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Message    : Keyword not supported: 'authentication'.
        TargetSite : 
            Name          : ParseInternal
            DeclaringType : System.Data.Common.DbConnectionOptions
            MemberType    : Method
            Module        : System.Data.SqlClient.dll
        StackTrace : 
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at CallSite.Target(Closure , CallSite , Object , Object )
        Source     : System.Data.SqlClient
        HResult    : -2147024809
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
FullyQualifiedErrorId : ExceptionWhenSetting
InvocationInfo        : 
    ScriptLineNumber : 1443
[DBG]: PS E:\CPR\Scripts\Monitor-CPRExceptions> Get-Error

Exception             : 
    ErrorRecord    : 
        Exception             : 
            Message : Exception setting "ConnectionString": "Keyword not supported: 'authentication'."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ExceptionWhenSetting
        InvocationInfo        : 
            ScriptLineNumber : 1443
            OffsetInLine     : 3
            HistoryId        : -1
            ScriptName       : E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1
            Line             : $conn.ConnectionString=$ConnectionString
            PositionMessage  : At E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1:1443 char:3
                               +         $conn.ConnectionString=$ConnectionString
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : E:\CPR\Scripts\Monitor-CPRExceptions
            PSCommandPath    : E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Get-SQLData, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 1443
                                at Get-Dictionaries, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 1937
                                at <ScriptBlock>, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 6967
    TargetSite     : 
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Exception setting "ConnectionString": "Keyword not supported: 'authentication'."
    Data           : System.Collections.ListDictionaryInternal
    InnerException : 
        Message    : Keyword not supported: 'authentication'.
        TargetSite : 
            Name          : ParseInternal
            DeclaringType : System.Data.Common.DbConnectionOptions
            MemberType    : Method
            Module        : System.Data.SqlClient.dll
        StackTrace : 
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at CallSite.Target(Closure , CallSite , Object , Object )
        Source     : System.Data.SqlClient
        HResult    : -2147024809
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
FullyQualifiedErrorId : ExceptionWhenSetting
InvocationInfo        : 
    ScriptLineNumber : 1443
    OffsetInLine     : 3
    HistoryId        : -1
    ScriptName       : E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1
    Line             : $conn.ConnectionString=$ConnectionString
    PositionMessage  : At E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1:1443 char:3
                       +         $conn.ConnectionString=$ConnectionString
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : E:\CPR\Scripts\Monitor-CPRExceptions
    PSCommandPath    : E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at Get-SQLData, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 1443
                        at Get-Dictionaries, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 1937
                        at <ScriptBlock>, E:\CPR\Scripts\Monitor-CPRExceptions\_Monitor-CPRExcpetions.03.5.0.ps1: line 6967

**Comment by iSazonov** [comment]
> Message : Exception setting "ConnectionString": "Keyword not supported: 'authentication'."

Perhaps you need to install SQL nuget package to get full features.

**Comment by sonnyjrob** [comment]
I installed the "mssql for Visual Studio Code" package and the error is still present.

**Comment by iSazonov** [comment]
Maybe link to a gist helps you https://github.com/PowerShell/PowerShell/issues/6724#issuecomment-552141268

**Comment by sonnyjrob** [comment]
Thanks iSazonov, I read the link and followed the recommendation ([[Microsoft.Data.SqlClient with PowerShell]](https://gist.github.com/MartinHBA/86c6014175758a07b09fa7bb76ba8e27)) and the DB I'm attempting to read does not support windows logins.  It must be Active Directory Integrated.

**Comment by MartinHBA** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.8

**Comment by sonnyjrob** [comment]
I finally had time to get back to this.  I've started the to move to the ODBC since C# isn't really an option.  

Is there any intention to add support for AAD upon release?

**Comment by MartinHBA** [comment]
@sonnyjrob per this [MS blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/) do not expect any new features to System.Data.SqlClient, all new features will be only with new Microsoft.Data.SqlClient

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
