### ISSUE TITLE
no_proxy variable not respected in sudo pwsh

### ISSUE THREAD

**Issue by cawoodm** [PowerShell/PowerShell#11059]
The `$no_proxy` variable set for `root` in `/etc/bashrc` is not available in `sudo pwsh` with `$env:no_proxy`. This means `curl` or `Invoke-WebRequest` will use the system's `HTTP_PROXY` when they shouldn't and fail to connect.

## Verify $no_proxy is set for root:
```
# sudo su
# echo $no_proxy
localhost,127.0.0.0,0.0.0.0,127.0.1.1,127.0.1.1,local.home,.buhler-ltd.com
```

## Verify it's set in sudo pwsh
```
# sudo pwsh
PowerShell 6.2.3
...
PS /> $env:no_proxy
PS />
```
Not, it's not.

## $PSVersionTable
CentOS 7.7
```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
What is  sudo bash behaviour?

**Comment by cawoodm** [comment]
It's correct:
```
me@lounge# sudo bash
root@lounge# echo $no_proxy
localhost,127.0.0.1
```

**Comment by cawoodm** [comment]
Hmmm... I'm actually on Ubuntu 19.10 now and it's working correctly in pwsh:
```powershell
PS>$env:no_proxy
localhost,127.0.0.1
```

**Comment by iSazonov** [comment]
PowerShell uses .Net Core API to get environment variables. So it could be .Net Core issue on CentOs 7.7 but we need C# repo.

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
