### ISSUE TITLE
Binary modules that worked in PowerShell 6 may not work in 7

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#11053]
@iSazonov and @SteveL-MSFT I think we made a mistake by removing the `WorkflowInfo` type in PR #9638. I know PR #6708 changed the type from public to internal, and that was probably a mistake as well.

I was just testing my FormatPx module in PowerShell 7, since `Out-Printer` is now added back into PowerShell, but the module won't load. It fails with the following error:

> Import-Module: Could not load type 'System.Management.Automation.WorkflowInfo' from assembly 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."

I get the same error if I try to import DebugPx into PowerShell 7, but DebugPx loads just fine in PowerShell 6.2 (FormatPx does not, because there is no `Out-Printer` command, and it derives its `Out-Printer` proxy from that command).

Both DebugPx and FormatPx have binary modules as part of their package.

I am not referencing `WorkflowInfo` directly from either of those projects, so that error must be coming from the PowerShell components that I do reference.

Testing this out locally, I have found that if I put an empty `public WorkflowInfo` class back in PowerShell 7 (not derived from anything, with no constructors or members), suddenly my DebugPx module  loads fine again.

FormatPx loads as well, but doesn't work (null reference exception somewhere), but so I need to figure that one out. That issue aside, it seems we need the `WorkflowInfo` class to persist for backwards compatibility support. Mind if I put it back in a PR?

# Steps to reproduce

```powershell
Install-Module DebugPx
Import-Module DebugPx
```

# Expected behavior

The module should load without error.

# Actual behavior

```none
Import-Module: Could not load type 'System.Management.Automation.WorkflowInfo' from assembly 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5-64-ge185f89591ac5fa5286bef60d087d852873df2be
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Any way we can dig deeper and see what's actually referencing the WorkflowInfo class?

**Comment by iSazonov** [comment]
Is PowerShell SDK used? Perhaps the reference is there.

**Comment by iSazonov** [comment]
@adityapatwardhan @daxian-dbw Could you please look the regression?

@KirkMunro Please add links to your modules in the OP.

**Comment by KirkMunro** [comment]
Here is the source code for the binary modules:

|Module|Source Code|
|--|--|
|DebugPx|https://github.com/KirkMunro/DebugPx/tree/assembly|
|FormatPx|https://github.com/KirkMunro/FormatPx/tree/assembly|

I recommend looking at DebugPx, because I was able to load that module successfully and use it once I re-added an empty WorkflowInfo class.

**Comment by iSazonov** [comment]
I see a problem in SnippetPX
```powershell
ipmo SnippetPx
gcm Invoke-Snippet

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Invoke-Snippet                                     1.0.6.19   SnippetPx

Invoke-Snippet Module.Initialize

Invoke-Snippet: Could not load type 'System.Management.Automation.WorkflowInfo' from assembly 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by iSazonov** [comment]
I found "WorkflowInfo" string in SnippexPX.dll

**Comment by KirkMunro** [comment]
Thanks @iSazonov. I hadn't thought to look at SnippetPx because HistoryPx loads and runs just fine on PowerShell 7, and it also uses SnippetPx as a nested module.

Anyhow, yes, there is source code for the DLL. I just didn't set it up in GitHub in a very standard way back then -- I had crazy ideas at the time, and put the binary module code in an assembly branch. I wouldn't do it that way now, of course, but anyway, here is the reference to `WorkflowInfo` in that module:

https://github.com/KirkMunro/SnippetPx/blob/assembly/SnippetPx/DiscoverableItemSearcher.cs#L424-L427

Given such code exists in my module (and potentially others), we should put an empty public `WorkflowInfo` class back into PowerShell 7, right?

**Comment by daxian-dbw** [comment]
#6708 changed the constructors to internal, but leave the type to be public, see [code here](https://github.com/PowerShell/PowerShell/pull/6708/files#diff-d9036bbae0b5dfd6b852c130a662cb8c).
It's not too late to add back the public type `WorkflowInfo`, but the question is: would that be enough? We removed many other things related to workflow, like `CommandTypes.Workflow`, so potentially they will cause existing modules to fail to load too ... Then it leads to another question, can we maybe keep it as is and force those affected modules to be updated?

**Comment by KirkMunro** [comment]
Speaking for my own modules that are affected by this, I can confirm that adding an empty `WorkflowInfo` class that doesn't derive from anything resolves my issues. Many other areas of workflow that were originally removed were put back and marked as deprecated instead for this reason. I think we may need to backpedal a bit here.

**Comment by iSazonov** [comment]
@KirkMunro Can you check that adding back the class with obsolete attribute works for you?

**Comment by KirkMunro** [comment]
@iSazonov Yes, it works fine for me. I just created PR #11069 in case you guys agree that it should be added back.

**Comment by JamesWTruher** [comment]
based on commentary in https://github.com/PowerShell/PowerShell/pull/11069 the WG is closing this as won't fix
