### ISSUE TITLE
Start-Job -WorkingDirectory only accepts native filesystem paths

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11050]
This has two ramifications:

* A path based on a PS drive isn't supported.

  * A note re a possible fix: The child process running the script block cannot be assumed to have the same PS (filesystem) drives defined, but at least a PS-drive-based input path should be resolved to the underlying native path.

* The interchangeable use of `/` and `\` isn't supported.

# Steps to reproduce

```powershell
New-PSDrive foo filesystem .; Set-Location foo:/

Start-Job { $pwd } -WorkingDirectory $pwd | Receive-Job -Wait -AutoRemove | Should -Match '^foo:[/\\]'

if (-not $IsWindows) {
  Start-Job { $pwd } -WorkingDirectory '\' | Receive-Job -Wait -AutoRemove | Should -Be '/'
}
```

# Expected behavior

Both tests should pass.

# Actual behavior

Both tests fail.

# Environment data

```none
PowerShell Core 7.0.0-preview.5
```

**Comment by iSazonov** [comment]
@mklement0 Will #11041 fix this? Should we add additional tests to #11041 ?

**Comment by mklement0** [comment]
No, @iSazonov, this is a separate issue, and new tests (such as the ones in the OP) should be added to the PR that will fix _this_ issue.
