### ISSUE TITLE
Scriptblock logging set by GPO is not honored by PowershellCore?

### ISSUE THREAD

**Issue by jdotmac** [PowerShell/PowerShell#11063]
# Steps to reproduce
Enable scriptblock logging via GPO or registry:
Computer Configuration/Policies/Administrative Templates/Windows Components/Windows Powershell/Turn on Powershell Script Block Logging = 'Enabled'
Create a scriptblock inside of PowerShellCore 7
{"log this as verbose in PowershellCore/Operational"}

# Expected behavior
All scriptblocks are logged to PowershellCore/Operational

# Actual behavior
Only scriptblocks considered suspicious will produce a 'warning' eventID 4104

Updating the following will enable the required logging
powershell.config.json must be updated with similar settings to below:
	"PowerShellPolicies": {
		"ScriptBlockLogging": {
			"EnableScriptBlockInvocationLogging": false,
			"EnableScriptBlockLogging": true
		},
		"ModuleLogging": {
			"EnableModuleLogging": false
		},
		"ProtectedEventLogging": {
			"EnableProtectedEventLogging": false
		}		
	},
	"LogLevel": "verbose"

# Environment data
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
>  scriptblocks considered suspicious will produce a 'warning' eventID 4104

It is by-design, we do not change the code from 6/0 release - EnableScriptBlockLogging logs only suspicious code.
EnableScriptBlockInvocationLogging = true will log every script block execution.

I see Windows PowerShell behaviour is different. If run "gcm gcm" Windows PowerShell writes to log but Core not. I am not sure that it is a problem.
@daxian-dbw @TravisEz13

**Comment by jdotmac** [comment]
Looks like they're set here for Core:

https://github.com/PowerShell/PowerShell/blob/3f52adb0aeaf58189d85d386ab502e08f92ed41b/src/System.Management.Automation/engine/Utils.cs#L783

**Comment by iSazonov** [comment]
@jdotmac I checked on my system that PowerShell Core gets GPO settings correctly.

**Comment by jdotmac** [comment]
Thanks.  Working for me in PS7 p5 as long as the following is set to 1 
Get-ItemPropertyValue -Path HKLM:\SOFTWARE\Policies\Microsoft\PowershellCore\ScriptblockLogging -Name EnableScriptBlockLogging

**Comment by iSazonov** [comment]
@jdotmac Current logic is that PowerShell Core fallback to Windows PowerShell policy settings if the are not PowerShell Core settings.

**Comment by TravisEz13** [comment]
@iSazonov You have to explicitly say in the core policy to fallback to Window PowerShell Policy.

You should be able to log more that suspicious script blocks.

**Comment by MrMarvel** [comment]
Not working on PowerShell 7.3.8.
```
D:\Users\Sergey> Get-ItemPropertyValue -Path HKLM:\SOFTWARE\Policies\Microsoft\PowershellCore\ScriptblockLogging -Name EnableScriptBlockLogging
1
```
And in config `powershell.config.json`
```
{
   "Microsoft.PowerShell:ExecutionPolicy": "Unrestricted",
   "PowerShellPolicies": {
      "ScriptBlockLogging": {
         "EnableScriptBlockInvocationLogging": true,
         "EnableScriptBlockLogging": true
      },
      "ModuleLogging": {
         "EnableModuleLogging": true
      },
      "ProtectedEventLogging": {
         "EnableProtectedEventLogging": false
      }
   }
}
```
I have no additional folders or files in %userprofile%/Documents on Powershell.
But with Windows Powershell works perfectly
