### ISSUE TITLE
Import-Module ActiveDirectory PS7 RC5

### ISSUE THREAD

**Issue by BinaryCortex** [PowerShell/PowerShell#11064]
# Steps to reproduce

`Import-Module ActiveDirectory`
or
`Import-Module ActiveDirectory -SkipEditionCheck`

# Expected behavior

Loading of the ActiveDirectory module

# Actual behavior

`Import-Module ActiveDirectory`
Import-Module: Module 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\ActiveDirectory\ActiveDirectory.psd1' does not support current PowerShell edition 'Core'. Its supported editions are 'Desktop'. Use 'Import-Module -SkipEditionCheck' to ignore the compatibility of this module.

`Import-Module ActiveDirectory -SkipEditionCheck`
Import-Module: Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

# Environment data

Name | Value
---- | -----
PSVersion  | 7.0.0-preview.5
PSEdition | Core
GitCommitId | 7.0.0-preview.5
OS | Microsoft Windows 10.0.17763
Platform | Win32NT
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1
WSManStackVersion | 3.0

```

**Comment by iSazonov** [comment]
@BinaryCortex Please remove your report to https://github.com/PowerShell/PowerShellModuleCoverage
