### ISSUE TITLE
Unable to install PowerShell 7 Preview at work

### ISSUE THREAD

**Issue by drumforgod82** [PowerShell/PowerShell#11072]
I am unable to install PowerShell 7 Preview at work.  The Microsoft Store and Github are both blocked.  I had to use my personal computer to get into Github, so I can relay this message.

I have even tried the following link: https://mikefrobbins.com/2019/07/11/install-powershell-7-with-jeff-hicks-psreleasetools-module/.  Still got errors and would not copy it.

Please work on another option to install PowerShell 7 (especially when it is fully released), for businesses that have the Microsoft Store and GitHub blocked.

**Comment by SteveL-MSFT** [comment]
@drumforgod82 You can access PowerShellGallery.com and Azure.com?

**Comment by msftrncs** [comment]
@drumforgod82, communication with your IT team would be incredibly valuable.  They may not understand your needs.  If they intend to block you from such resources, it will not matter where PowerShell is released, it will be blocked.

**Comment by drumforgod82** [comment]
@SteveL-MSFT, I can get to both the PowerShellGallery.com and Azure.com.
