### ISSUE TITLE
macos 10.12 not supported by DotNet Core 3.x

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#11089]
macos 10.12 not supported by DotNet Core 3.x

**Comment by TravisEz13** [comment]
cc @adityapatwardhan

**Comment by TravisEz13** [comment]
need to change this
https://github.com/PowerShell/PowerShell/blob/b218e6f6ccfbd784d29258a0cab5820c676c4773/tools/packaging/packaging.psm1#L976

**Comment by adityapatwardhan** [comment]
Fixed by: https://github.com/PowerShell/PowerShell/pull/11163
