### ISSUE TITLE
6.2.3 The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by 9034725985** [PowerShell/PowerShell#11082]
# Steps to reproduce

I can't reproduce this. 
Not sure what we can do with this. 
Just wanted to document it somewhere. 
Please feel free to close. 

```powershell

(press up arrow in new window) 

```

# Expected behavior

```none
shows the last thing
```

# Actual behavior

```none

PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Program Files\PowerShell\6>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
```
 UpArrow
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32 y)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

```

# Environment data

```none
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Tagging https://github.com/PowerShell/PSReadLine/issues/1059

**Comment by msftrncs** [comment]
This is a PSReadLine issue, as indicated in the lines of the error report:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
```

You should give PSReadLine 2.0.0-beta6 a try from PowerShellGallery, and if it doesn't resolve this issue, report further reproduction information there.

**Comment by 9034725985** [comment]
Thank you for looking at this issue. 

I tried to install it but it says 

```
PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Program Files\PowerShell\6> Install-Module -Name PSReadLine -AllowPrerelease

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
WARNING: Version '2.0.0-beta3' of module 'PSReadLine' is already installed at 'C:\program files\powershell\6\Modules\PSReadLine'. To install version '2.0.0-beta6', run Install-Module and add the -Force parameter, this command will install version '2.0.0-beta6' side-by-side with version '2.0.0-beta3'.
``` 

should I install with `-Force`? Is there a way to replace the existing installation of beta3 with beta6?

**Comment by vexx32** [comment]
Yep, use -Force. This comes up because PSReadLine is installed in-the-box with PS Core, so OneGet doesn't consider the in-box version of the module as updatable. It can install side by side without issue. 🙂
