### ISSUE TITLE
Tee-Object should have an -Encoding parameter

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11104]
# Summary of the new feature/enhancement

`Tee-Object` currently _invariably_ uses the _default_ character encoding when teeing to a file (`-Path` aka `-Filepath`, `-LiteralPath`), which in PS Core is BOM-less UTF-8

However, sometimes you need a specific character encoding, and `Tee-Object` currently offers no way to specify a different encoding.

# Proposed technical implementation details (optional)

Introduce an `-Encoding` parameter (to be combined only with the `-Path` / `-FilePath` or `-LiteralPath`, analogous to the parameter of the same name already supported by other write-to-file cmdlets such as `Out-File`.

**Comment by mklement0** [comment]
As an aside: As it turns out,  a  `'Out-File:Encoding'` entry in `$PSDefaultParameterValues` also controls not just `Out-File` / `>`'s output encoding, but also `Tee-Object`'s, which is obscure and probably undesired. However, conceivably someone currently relies on this as a (cumbersome) workaround.

**Comment by vexx32** [comment]
I'm not even sure I _want_ to know how that was jury-rigged. My word... 😂

**Comment by iSazonov** [comment]
Looks as very simple enhancement in Tee-Object.cs

**Comment by peterduniho** [comment]
> I'm not even sure I _want_ to know how that was jury-rigged. My word... 😂

I'm assuming it's just because Tee-Object invokes Out-File to produce the file itself. It'd be better for Tee-Object to have a parameter, but I can see this being an okay work-around in the meantime (ignoring that it applies a global change to a local problem, which is of course always a bad thing to do).

**Comment by rpolley** [comment]
Yeah looking at the code it looks like this just invokes `Out-File`, and since _that_ has an `-Encoding` parameter this might be as simple as adding an encoding parameter that just gets passed through to that command.

**Comment by rpolley** [comment]
Yeah looks like it is as simple as that, going to add some unit tests and turn what I've gotten into a pull request.
