### ISSUE TITLE
ActiveDirectory Module recognized but all Cmdlets fail with same error

### ISSUE THREAD

**Issue by jackfalveyiv** [PowerShell/PowerShell#11103]
ActiveDirectory module is working fine in Powershell 5.1, but in Core 7 I am able to successfully tab-complete the commands but they all retrieve a similar error.

# Steps to reproduce
Get-ADUser, Get-ADDomain

# Expected behavior
Return of user/domain information

# Actual behavior
Error message:
```
Get-ADUser TestUser
Get-ADUser: Type 'generatedProxy_14' from assembly 'ProxyBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.

Get-ADDomain domain.com
Get-ADDomain: Type 'generatedProxy_15' from assembly 'ProxyBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.
```

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@jackfalveyiv The module is not in the repo. Please move your report to https://github.com/PowerShell/PowerShellModuleCoverage

With latest PowerShell Core 7.0 builds you could try:
```powershell
New-PSSession -UseWindowsPowerShell ActiveDirectory
```

**Comment by jackfalveyiv** [comment]
I have reported this in the requested directory, but just for knowing, the following error is returned when running the command you suggested:
```
New-PSSession -usewindowspowershell ActiveDirectory
New-PSSession: A parameter cannot be found that matches parameter name 'usewindowspowershell'.
```

**Comment by vexx32** [comment]
@jackfalveyiv I believe that was added after preview.5 so it'll be available in the daily builds, and in preview.6 and onwards which should be releasing shortly. 🙂

**Comment by jackfalveyiv** [comment]
Understood, thanks for the input.

**Comment by SteveL-MSFT** [comment]
@jackfalveyiv does this repro with today's daily build?  cc @anmenaga

**Comment by iSazonov** [comment]
I don't see the error with latest builds, latest RSAT and Windows Server 2019.
