### ISSUE TITLE
Get-FileHash access denied

### ISSUE THREAD

**Issue by chosebin** [PowerShell/PowerShell#11110]
When using PS 7 preview 5 Get-FileHash it returns access denied to path from pipe

ex. 
```
Get-ChildItem -path "C:\Program Files\" -Recurse | Get-FileHash
Get-FileHash: Access to the path 'C:\Program Files\Common Files' is denied.

From Windows PS
Get-ChildItem -path "C:\Program Files\" -Recurse | Get-FileHash
Algorithm       Hash                                                                   Path
---------       ----
```

**Comment by rjmholt** [comment]
Looks like this happens in `Get-FileHash`:

```
> Get-Error

Exception             :
    TargetSite :
        Name          : ValidateFileHandle
        DeclaringType : System.IO.FileStream
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize,
FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.PowerShell.Commands.GetFileHashCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message    : Access to the path 'C:\Program Files\7-Zip' is denied.
    Source     : System.Private.CoreLib
    HResult    : -2147024891
CategoryInfo          : NotSpecified: (:) [Get-FileHash], UnauthorizedAccessException
FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.GetFileHashCommand
InvocationInfo        :
    MyCommand        : Get-FileHash
    ScriptLineNumber : 1
    OffsetInLine     : 33
    HistoryId        : 3
    Line             : gci -path 'C:\Program Files\' | Get-FileHash
    PositionMessage  : At line:1 char:33
                       + gci -path 'C:\Program Files\' | Get-FileHash
                       +                                 ~~~~~~~~~~~~
    InvocationName   : Get-FileHash
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

```

**Comment by iSazonov** [comment]
I think we need to write non-terminating error for the pipeline scenario.

**Comment by chosebin** [comment]
Is this part of PowerShell 7.0.0-rc.1?
Looks like it is still a problem.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we add the commit to RC branch?

**Comment by kerness** [comment]
Still have the same problem in PowerShell 7.1.3. Here is my code:

`Get-ChildItem -Path C:\Users\kek\Documents\pwsTest -Recurse -Force | Get-FileHash
Get-FileHash: Access to the path 'C:\Users\kek\Documents\pwsTest\filmy' is denied.
Get-FileHash: Access to the path 'C:\Users\kek\Documents\pwsTest\zdjęcia' is denied.
Get-FileHash: Access to the path 'C:\Users\kek\Documents\pwsTest\zdjęcia\wakacje2020' is denied.
Get-FileHash: Access to the path 'C:\Users\kek\Documents\pwsTest\zdjęcia\wakacje2021' is denied.
Get-FileHash: Access to the path 'C:\Users\kek\Documents\pwsTest\zdjęcia\wakacje2020\Tajwan' is denied.

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855       C:\Users\kek\Documents\pwsTest\…`

And here is Get-Error message

`Exception             :
    Type       : System.UnauthorizedAccessException
    TargetSite :
        Name          : ValidateFileHandle
        DeclaringType : System.IO.FileStream
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize,
FileOptions options)
   at Microsoft.PowerShell.Commands.GetFileHashCommand.ComputeFileHash(String path, String& hash)
    Message    : Access to the path 'C:\Users\kek\Documents\pwsTest\zdjęcia\wakacje2020\Tajwan' is denied.
    Source     : System.Private.CoreLib
    HResult    : -2147024891
TargetObject          : C:\Users\kek\Documents\pwsTest\zdjęcia\wakacje2020\Tajwan
CategoryInfo          : InvalidData: (C:\Users\kek\Docume…\wakacje2020\Tajwan:String) [Get-FileHash],
UnauthorizedAccessException
FullyQualifiedErrorId : UnauthorizedAccessError,Microsoft.PowerShell.Commands.GetFileHashCommand
InvocationInfo        :
    MyCommand        : Get-FileHash
    ScriptLineNumber : 1
    OffsetInLine     : 70
    HistoryId        : 26
    Line             : Get-ChildItem -Path C:\Users\kek\Documents\pwsTest -Recurse -Force | Get-FileHash
    PositionMessage  : At line:1 char:70
                       + … m -Path C:\Users\kek\Documents\pwsTest -Recurse -Force | Get-FileHash
                       +                                                            ~~~~~~~~~~~~
    InvocationName   : Get-FileHash
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :`

**Comment by Asshall** [comment]
So... I'm running running PowerShell 7.2.2 on an Ubuntu 20.04 installed though apt and I think I'm still getting the error described here. (I'm know nothing of powershell)

```powershell
Get-ChildItem -recurse | Get-FileHash
Get-FileHash: Access to the path '[redacted]/subdir/subfile' is denied.

Get-Error
Exception             :
    Type           : System.UnauthorizedAccessException
    TargetSite     :
        Name          : Open
        DeclaringType : Microsoft.Win32.SafeHandles.SafeFileHandle
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message        : Access to the path '[redacted]/subdir/subfile' is
denied.
    InnerException :
        Type    : System.IO.IOException
        Message : Permission denied
        HResult : 13
    Source         : System.Private.CoreLib
    HResult        : -2147024891
    StackTrace     :
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode,
FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess
access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String
path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions
options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Microsoft.PowerShell.Commands.GetFileHashCommand.ComputeFileHash(String path, String&
hash)
TargetObject          : [redacted]/subdir/subfile
CategoryInfo          : InvalidData: ([redacted]/subdir/subfile:String)
[Get-FileHash], UnauthorizedAccessException
FullyQualifiedErrorId :
UnauthorizedAccessError,Microsoft.PowerShell.Commands.GetFileHashCommand
InvocationInfo        :
    MyCommand        : Get-FileHash
    ScriptLineNumber : 1
    OffsetInLine     : 26
    HistoryId        : 2
    Line             : Get-ChildItem -recurse | Get-FileHash
    PositionMessage  : At line:1 char:26
                       + Get-ChildItem -recurse | Get-FileHash
                       +                          ~~~~~~~~~~~~
    InvocationName   : Get-FileHash
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```
Seems it does this for every subdirectory.
Same thing happens when I do `Get-FileHash -path **`
