### ISSUE TITLE
Clear-Host has no Source

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#11113]
Currently `Clear-Host` has no source or module associated with it. `mkdir` seems to be the same, although this is more of an alias.

Given `Clear-Host`'s official name, I would expect it to live in `Microsoft.PowerShell.Core`. Without a module, it's harder to namespace it.

**Comment by iSazonov** [comment]
Is it possible for scripts?

**Comment by SteveL-MSFT** [comment]
We should probably turn it into a real cmdlet

**Comment by rjmholt** [comment]
My expectation was that it was just a wrapper for a Host API call, rather than a function
