### ISSUE TITLE
Default FilterScript for Where-Object

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#11116]
By default (where no parameters are supplied except for the `$InputObject`) for the [`Where-Object`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/where-object?view=powershell-6), filter `$Null` "_objects_" from the pipeline.

This request is related to #10704 and its lengthy discussion which concerns matching _properties_ with `$Null` rather than the current _object_with `$Null`.

Some (custom) cmdlets appear to put `$Null` values in the pipeline which might lead to problems as it causes an unexpected iteration. (see e.g. [How to handle $null in the pipeline](https://stackoverflow.com/q/4356758/1701026)):

`1,$Null,2,3 | ForEach-Object {$_}` produces **3** numbers
where
`1,$Null,2,3 | ForEach-Object {'Hi'}` produces **4** `Hi`'s

The current solution to this is to filter the `$Null` objects using the `Where-Object`:

`1,$Null,2,3 | Where-Object {$Null -ne $_} | ForEach-Object {'Hi'}`
<sub>(but as in the example stackoverflow question/answer this is often done incorrectly with `$Null` at wrong side of the  equality operator, and maybe should be even `$_ -isnot $Null`.)<sub>

At the moment (PowerShell version 6.2.3) the `Where-Object` requires at least an extra mandatory parameter besides the `$InputObject`:

**`1,$Null,2,3 | Where-Object | ForEach-Object {'Hi'}`**
Results in:

> ```
> >>
> 
> cmdlet Where-Object at command pipeline position 1
> Supply values for the following parameters:
> FilterScript:
> ```

It would be nice if the default `FilterScript` for the `Where-Object` cmdlet is set to something like `{$Null -ne $_}` (or `{$_ -isnot $Null}`) which should than appropriately filter out anything that is not an object (`$null`'s), so that a syntax like `1,$Null,2,3 | Where-Object | ForEach-Object {'Hi'}` will just produce 3 `Hi`'s.

**Comment by vexx32** [comment]
@iRon7 this request appears to be a duplicate of #8357, which would have the same effect (plus a few extra bits and bobs); can I ask you add your thoughts to that issue instead, please? Thanks! 💖

**Comment by iRon7** [comment]
I have closed this issue as it part of #8357
