### ISSUE TITLE
ConvertFrom-Json allows trailing commas in input JSON

### ISSUE THREAD

**Issue by simonsabin** [PowerShell/PowerShell#11117]
Convertfrom-json and Test-Json both accept invalid json and neither provide ability to force strict parsing. 

It looks like there are two related issues on NJsonSchame and NewtonSoft.Json the latter saying its expected behaviour.

https://github.com/RicoSuter/NJsonSchema/issues/942
https://github.com/JamesNK/Newtonsoft.Json/issues/818

# Steps to reproduce

```powershell
convertfrom-json "{'simon':'sabin',}"
```

# Expected behavior

An error should occur as in Powershell 5.x

# Actual behavior
Parses correctly and returns object matching the json

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The cmdlets is based on Newtonsoft.Json and inherit the behavior.

I see no reason to do something until we migrate to System.Text.Json.

**Comment by simonsabin** [comment]
I realise that, this was more of a put it there so folks can hopefully find the information to understand the behaviour

**Comment by iSazonov** [comment]
I think we need a request to enhance the cmdlets with new parameter or parameters to support "options". This will be more useful for tracking.

**Comment by chriskuech** [comment]
Dup of #10628
