### ISSUE TITLE
Test-NetConnection cmdlet is missing from PowerShell Core 6.2.3 release

### ISSUE THREAD

**Issue by sidsolutions-net** [PowerShell/PowerShell#11111]
Get-Command Test-NetConnection
Get-Command : The term 'Test-NetConnection' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Command Test-NetConnection
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Test-NetConnection:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

**Comment by vexx32** [comment]
@sidsolutions-net the Test-NetConnection command is only available from the Windows PowerShell `NetTCPIP` module. You'll need to have the Windows PowerShell module loaded to be able to use the command. You may need to make sure your Windows PowerShell module locations are present in $env:PSModulePath to be able to load the module by name, otherwise you can always load it directly by the full path.

**Comment by iSazonov** [comment]
In latest builds you can load Core incompatible modules in background Windows PowerShell session (#10973):
```powershell
Import-Module -UseWindowsPowerShell NetTCPIP
```

**Comment by rjmholt** [comment]
I believe NetTCPIP has now been ported as well, but you'll need a recent Windows edition:

![test-netconnection](https://user-images.githubusercontent.com/7009879/69118776-703a9800-0a49-11ea-9305-894c4f89aa0f.PNG)

**Comment by iSazonov** [comment]
Yes, I see
```
    CompatiblePSEditions = @('Desktop', 'Core')
``
in its psd1 file.

**Comment by fakhrulhilal** [comment]
Hi,

Can you recheck again for 7.1.1? I intend to use ps core for linux but there's no entire NetTCPIP module at all
```
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Linux 5.4.0-1031-azure #32-Ubuntu SMP Tue Oct 6 09:47:33 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
The NetTCPIP is a Windows module, it doesn't exist for Linux, and likely will not be able to be ported as it uses Windows-OS-specific APIs for its functionality.

You can use the pwsh-native `Test-Connection` cmdlet on any OS pwsh is available on. However, I will note that .NET Core / .NET 5 support for parts of the functionality it implements is rather lacking in places, so depending on your use case it may be more desirable to use a linux-native ping application.
