### ISSUE TITLE
Get-CimInstance: ignores -Property and WQL query

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShell/PowerShell#11115]
Get-CimInstance documentation states that the parameter **-Property** can be used to limit bandwidth by only retrieving the requested list of properties:
[Help Page](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/get-ciminstance?view=powershell-6)
See example 9.

In reality, Get-CimInstance always seems to return *all* properties, regardless of the use of -Property or -Query. No network bandwidth is saved.

# Steps to reproduce
Run this:
```powershell
Get-CimInstance -Class Win32_Process -Property Name,KernelModeTime
```
The issue is present also in queries:
```powershell
Get-CimInstance -Query "Select Name, KernelModeTime from Win32_Process" 
```
Here, though, there seems to be another oddity: the command outputs data that shows only a few table columns. However, all properties are available:
```powershell
Get-CimInstance -Query "Select Name, KernelModeTime from Win32_Process" | Select-Object *
```

# Expected behavior
Both calls should just retrieve the specified properties. 

# Actual behavior
All properties are returned. No network bandwidth is saved. Results must be sent to `Select-Object` on the client side to get the desired result.

When I use either **-Property** or **-Query**, `Get-CimInstance` returns objects of type *TypeName: Microsoft.Management.Infrastructure.CimInstance#__PartialCIMInstance*, else it is the full instance. So it must be related to the part that "fills" the partial instance IMHO.

**Note:**
I was able to test only on a local system. The same issue is present when I remote against the own system, both with DCOM and WsMan. It might be interesting to see what the results are when data is actually retrieved from a real remote system where network bandwidth plays a role. Possibly, **-Property** is implemented to work only there. However, I would expect it to work always.

The issue is present in **PowerShell Core** and **Windows PowerShell** so seems to be a long standing bug, unless I am overlooking something really stupid and run the wrong command.

# Environment data
```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TobiasPSP** [comment]
This clarified. Apparently, `Get-CimInstance` always returns ALL properties but only populates the requested ones. That was somewhat unexpected but explains it completely.

On a side note, how can I delete an issue that turned out not to be one? :-)

**Comment by iSazonov** [comment]
> On a side note, how can I delete an issue that turned out not to be one? :-)

Close with a comment.

**Comment by tkenvin** [comment]
So can this be closed?

**Comment by doctordns** [comment]
Closing this issue.
