### ISSUE TITLE
New-SMBShare -Temporary seems to do nothing

### ISSUE THREAD

**Issue by guidovbrakel** [PowerShell/PowerShell#11124]
New-SMBShare -Temporary seems to do nothing

# Steps to reproduce

Create a share using New-SMBShare -Temporary, for example:
New-SmbShare -Name Share -Path C:\Temp -Temporary
Then reboot and the share should be gone, but that's not happening

```

# Expected behavior

After a reboot the share should be gone, which is not happening

```

# Actual behavior

Shares stays active when running New-SMBShare with -Temporary
```

# Environment data


Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.19025
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by guidovbrakel** [comment]
<!--

New-SMBShare -Temporary seems to do nothing

# Steps to reproduce

Create a share using New-SMBShare -Temporary, for example:
New-SmbShare -Name Share -Path C:\Temp -Temporary
Then reboot and the share should be gone, but that's not happening

```

# Expected behavior

After a reboot the share should be gone, which is not happening

```

# Actual behavior

Shares stays active when running New-SMBShare with -Temporary
```

# Environment data


Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.19025
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@guidovbrakel New-SmbShare cmdlet is not in the repository. Please use UserVoice site or Windows 10 Feedback tool to report.
