### ISSUE TITLE
Missing some cmdlets from WindowsPS modules that are PS-Core-compatible

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#11127]
One example is `Microsoft.PowerShell.Management` module on Server 2019.
It's manifest `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1` says that the module is PS-Core-compatible:
```
ModuleVersion="3.1.0.0"
CompatiblePSEditions = @('Desktop','Core')
CmdletsToExport=@("Add-Content",
    "Get-EventLog",
    "Clear-EventLog",
...
    "Get-WmiObject",
```
Some of these cmdlets (e.g. `*-EventLog`, `*-WmiObject`) do not exist in `Microsoft.PowerShell.Management` module that comes with PS Core:
```
ModuleVersion="7.0.0.0"
CompatiblePSEditions = @("Core")
```
When `System32`-version of the module imported directly, these cmdlets are missing.

# Steps to reproduce

```powershell
# start a clean PS Core instance
Import-Module C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Management
Get-EventLog
```

# Expected behavior

Cmdlet is executed successfully.

# Actual behavior

```powershell
Get-EventLog
Get-EventLog: The term 'Get-EventLog' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\> (Get-Module Microsoft.PowerShell.Management).ExportedCmdlets.Keys.Contains('Get-EventLog')
False
# other cmdlets from the same imported module point to DLL from PS-Core installation
PS C:\> (Get-Command Get-HotFix).DLL
C:\1\PowerShell-7.0.0-preview.5-win-x64\Microsoft.PowerShell.Commands.Management.dll
```

# Environment data
```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
EventLog cmdlets are deprecated in favor of the WinEvent cmdlets.  Wmi cmdlets are deprecated in favor of the CIM cmdlets.

**Comment by FremontStrom** [comment]
What about Get-HotFix?  That's missing too.

**Comment by SteveL-MSFT** [comment]
@FremontStrom it was added back in preview.5, see https://devblogs.microsoft.com/powershell/powershell-7-preview-5/

**Comment by AaronMargosis** [comment]
AFAICT there is no way to clear an event log's content in PowerShell 7 without invoking Windows PowerShell (Clear-EventLog) which can be problematic. The -WinEvent cmdlets don't offer a "Clear" verb.
