### ISSUE TITLE
Basic Auth over HTTP not allowed on Unix.New-PSSession test failing on Debian 10

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#11129]
Basic Auth over HTTP not allowed on Unix.New-PSSession should throw when specifying Basic Auth over HTTP on Unix

Failed 3h ago on 6dcfecda2e0b
Duration0:00:00.027
Failing buildReleaseAutomationTest-114865
OwnerPaul Higinbotham

Debug
Work items
Attachments
History

Error message
Expected 801, but got 0.

https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=117686&view=ms.vss-test-web.build-test-results-tab&runId=1096282&resultId=101189&paneView=debug

Stack trace
at <ScriptBlock>, /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1: line 32
32:         $err.Exception.ErrorCode | Should -Be 801

# Steps to reproduce

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none

```

**Comment by SteveL-MSFT** [comment]
The problem is that it's looking for libpsrpclient.so in $pshome/linux-x64 folder. Even after copying it there, it has some dependencies and the symlinks are going to the wrong version on the OS.  After manually fixing, the tests pass.
