### ISSUE TITLE
Feature Request: Add ability to alter prompt color

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#11136]
I often find myself lost in a plethora of lines all looking the same. It's hard for me to tell the beginning of the my most recent command's output from previous commands' output.

So, I'd like to suggest to add a property to PowerShell allowing me to change the color of my PowerShell prompt permanently from white text on black background to something else.

Here are two screenshots depicting the current and expected situation (note the red line in the second image, that's the suggested change):

### current situation
![Current state](https://user-images.githubusercontent.com/9283914/69268220-00561a00-0bcf-11ea-97bb-72a81f068faf.png)

### expected situation
![Desired state](https://user-images.githubusercontent.com/9283914/69268224-01874700-0bcf-11ea-99ff-4df3a90ac23a.png)

<hr/>

From my perspective, the prompt consists of two parts:

1. current working directory
1. command

It would be preferable to be able to change the styling of each of these two parts separately.
<hr/>

In addition to the prompt's foreground and background color, the text styling should also be editable: I'd very much like to see the current working directory part underlined. Something like this:

![Underlined](https://user-images.githubusercontent.com/9283914/69269234-de5d9700-0bd0-11ea-8940-e8efc5a093c8.png)

The suggested feature would greatly help in finding previous commands among lines of other output in order to see where the corresponding other output started.

**Comment by rkeithhill** [comment]
You can already do this by writing your own `prompt` function and putting it in your profile so that it is available every time you start PowerShell. For example:
```
function prompt() {
    "`e[41mPS `e[48;2;255;64;64m$($executionContext.SessionState.Path.CurrentLocation)`e[24m$('>' * ($nestedPromptLevel + 1))`e[0m "
}
```
For more info on what VT sequences you can use, see: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

**Comment by SetTrend** [comment]
Oh ... cool! 👍 

Thanks a lot, @rkeithhill, for enlightening me!
