### ISSUE TITLE
Support Question: Unable to extract data from JSON file

### ISSUE THREAD

**Issue by AnthonyPaull** [PowerShell/PowerShell#11140]
# Support Question

I've got a JSON file in this format:
[
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: DELL XPS 13 9380",
    "SensorName": "Virtual Memory Commited",
    "SensorValue": "7286",
    "SensorUnit": "MB",
    "SensorUpdateTime": 1574031681
  },
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: DELL XPS 13 9380",
    "SensorName": "Virtual Memory Available",
    "SensorValue": "1926",
    "SensorUnit": "MB",
    "SensorUpdateTime": 1574031681
  },
  {
    "SensorApp": "HWiNFO",
    "SensorClass": "System: DELL XPS 13 9380",
    "SensorName": "Virtual Memory Load",
    "SensorValue": "79",
    "SensorUnit": "%",
    "SensorUpdateTime": 1574031681
  }
]

Yet every time I convertfrom-JSON and try to get data out (In this case, trying to get temperature info from HWiNFO64), it returns as empty. I can format as a table and see all the data, however nothing I do seems to be able to parse the content of the file and return a value.

So my question here is how do I go about getting information (Say in this case, I want to find anything with sensorname -like tjmax and then return the sensorvalue from that object)

Any suggestions welcome. For reference I'd consider myself competent but not an expert. I'm really hoping there's an easy obvious way to do this that I just missed.

[192.168.66.38.txt](https://github.com/PowerShell/PowerShell/files/3872103/192.168.66.38.txt)

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack][powershell-slack] and [Discord][powershell-discord] Community Chat - Interactive chat with other PowerShell enthusiasts. Both Slack and Discord are bridged via a bot and can seamlessly talk to each other.

[StackOverflow.com](https://stackoverflow.com/questions/tagged/powershell) and [PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

[powershell-slack]: https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM
[powershell-discord]: https://discordapp.com/invite/AtzXnJM

**Comment by mklement0** [comment]
Generally, please note that the issue template is used isn't actually meant to create an issue with - instead, its purpose is to provide _information_ as to _where else_ you can ask for support.

@SteveL-MSFT, can we try to make this clearer in the various information-only templates? Along the lines of a conspicuous preamble along the lines of:

> PLEASE DO NOT CREATE AN ISSUE HERE - just read the information below and take the appropriate action elsewhere. Use the Preview tab for a better reading experience and clickable links.

**Comment by mklement0** [comment]
As for your specific question:

You can use the following to select all objects that have a nonempty `.SensorName` property:

```powershell
((Get-Content -raw file.json) | ConvertFrom-Json) | Where-Object SensorName
```

Note the `(...)` around the `ConvertFrom-Json` call, which is an obscure workaround that is currently required in order to _enumerate_ the objects contained in the JSON array, i.e. to send them _one by one_ through the pipeline, as you would expect.

The need for this workaround is about to go away.

**Comment by SteveL-MSFT** [comment]
@mklement0 I wonder if we should just remove that template and instead put Support higher in the main README.md

**Comment by mklement0** [comment]
@SteveL-MSFT: That would have to been done for all info-only templates, though:

* Documentation Issue
* Security Issue
* Support Question
* Windows PowerShell

Actually, I just noticed the last entry on the new-issue landing page, "Report a security vulnerability", which isn't a template, but simply links to another page (https://github.com/MicrosoftDocs/PowerShell-Docs/security/policy), which looks like the right approach for two reasons:

* It's read-only - no temptation to submit an issue.
* It renders readably and with clickable links by default.

Therefore, can't we use the same approach for all the info-only templates above?

**Comment by SteveL-MSFT** [comment]
@mklement0 yes, that makes the most sense.  I'll submit a PR.

**Comment by SteveL-MSFT** [comment]
PR: https://github.com/PowerShell/PowerShell/pull/11153
