### ISSUE TITLE
Get-Error/ErrorView Concise: Include VSCode Friendly Error URI?

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#11152]
@SteveL-MSFT
# Summary of the new feature/enhancement

Visual Studio Code will render path uris in the console that have a line and character delimiter, such that clicking them goes straight to the line and character in question
`C:\Users\JGrote\Projects\MyProject\MyFile\Public\MyBrokenFile.ps1:130:9`
![ClickLinkDemo](https://user-images.githubusercontent.com/15258962/69389499-0e647300-0c81-11ea-8e33-b444c4d7f455.gif)

# Proposed technical implementation details (optional)

This may not make sense in the core code, but provide some way that ErrorView ConciseView will detect vscode and emit an additional line (or same like with "at:" with the uri, so it can simply be clicked to go right to where the problem is. This would be extremely user friendly. Alternatively a new view like ConciseViewWithPath or something.

Additionally Update Get-Error to have it as a property for this. NOTE that the current normalview does include a URI like this, but the link doesn't use the "correct" column format, it says `At C:\Users\JGrote\desktop\Demo.ps1:5 char:12` instead of `At C:\Users\JGrote\desktop\Demo.ps1:5:12`

**Comment by SteveL-MSFT** [comment]
PowerShell 7 already supports this.  See this [code](https://github.com/PowerShell/PowerShell/blob/b1e998046e12ebe5da9dee479f20d479aa2256d7/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1077)
