### ISSUE TITLE
How to have VSCode show command list for PS7.0 when typing?

### ISSUE THREAD

**Issue by Silver-Fang** [PowerShell/PowerShell#11174]
Under PS5.1 mode, typing "Get-" triggers a list of commands starting with that.
![批注 2019-11-23 105508](https://user-images.githubusercontent.com/33191697/69471956-c14ae300-0ddf-11ea-8a2a-e33ee9a56613.png)
However, with PS7.0, nothing happens:
![image](https://user-images.githubusercontent.com/33191697/69471983-0d962300-0de0-11ea-9562-36749819aff2.png)
What's wrong here?

**Comment by vexx32** [comment]
@Silver-Fang this is probably a better question for the https://github.com/PowerShell/vscode-powershell repo folx to answer for you. 😊
