### ISSUE TITLE
Test-ScriptFileInfo fails when blank line removed from between comments

### ISSUE THREAD

**Issue by S-T-S** [PowerShell/PowerShell#11173]
# Steps to reproduce

Generate new script file info using **New-ScriptFileInfo**
Test this file with **Test-ScriptFileInfo** > test passes!
Open with favorite text editor like VSCode or Notepad;
Delete the blank line between two two comment blocks, save file;
Test this file with **Test-ScriptFileInfo** > test fails!?
Place a blank line between two two comment blocks, save file;
Test this file with **Test-ScriptFileInfo** > test passes!?!

# Expected behavior
White space between comments should not make a test for the validity of the contents of those comments fail.

# Actual behavior
Test for validity of comments fails when there is not a blank line between comments.

# Environment data
```$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@S-T-S Please move your question to right repository https://github.com/PowerShell/PowerShellGet
