### ISSUE TITLE
Why doesn't ThreadJob Module appear in the module explorer?

### ISSUE THREAD

**Issue by Silver-Fang** [PowerShell/PowerShell#11176]
https://docs.microsoft.com/en-us/powershell/module/threadjob
This module is invisible at https://docs.microsoft.com/en-us/powershell/module
Newcomers who don't know its existence won't have a chance to encounter it.

**Comment by mklement0** [comment]
Good point, but the better place to report this is at https://github.com/MicrosoftDocs/PowerShell-Docs/issues

Improvements to the new-issue page to make it clearer that documentation issues shouldn't actually be reported _here_ are [underway](https://github.com/PowerShell/PowerShell/pull/11153).

**Comment by sdwheeler** [comment]
This was fixed a long time ago.
