### ISSUE TITLE
Doc says Out-GridView is in Microsoft.PowerShell.Utility but module doesn't contain the cmdlet

### ISSUE THREAD

**Issue by yobyot** [PowerShell/PowerShell#11179]
The [PowerShell 7 preview 6](https://devblogs.microsoft.com/powershell/powershell-7-preview-6/) announcement mentions improvements in `Out-GridView` and [links to the doc](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/out-gridview?view=powershell-7) which says that `ogv` is in `Microsoft.PowerShell.Utility`.

However, `Out-GridView` is not among the exported commands in `Microsoft.PowerShell.Utility`.

See attached image.

Thanks!

<img width="983" alt="ogvmissing" src="https://user-images.githubusercontent.com/14332263/69482064-b9417200-0de4-11ea-8fa4-6757a6a501ea.png">

**Comment by ili101** [comment]
Are you on windows?

> This cmdlet was reintroduced in PowerShell 7. This cmdlet is only available on Windows systems that support the Windows Desktop.

**Comment by yobyot** [comment]
<headslap>Good question!</headslap>

macOS Catalina.

**Comment by yobyot** [comment]
Sorry, but I don't see a resolution here at all. Neither the doc nor the repo have been updated to resolve this issue.

**Comment by vexx32** [comment]
@yobyot the Out-GridView cmdlet was only reintroduced for Windows as is mentioned in the docs page you linked (see the `Note` in the Description section).

If you would like to work with `Out-GridView` on other platforms, you can use the `GraphicalTools` module from the PSGallery which implements a similar cmdlet on the cross-platform AvaloniaUI framework. 🙂
