### ISSUE TITLE
Can't ignore optional parameters of .Net function?

### ISSUE THREAD

**Issue by Silver-Fang** [PowerShell/PowerShell#11186]
I have a custom .Net DLL named PowerShellExtension:
```VB
Public Module Utility
	Function TaskAssignment(Of T)(TaskList As T(), Optional Threads As Byte = 0) As T()()
	End Function
End Module
```
Calling this in PS will cause error:
```PowerShell
 Add-Type -Path .\PowerShellExtension.dll
$a=1..100
$b=[PowerShellExtension.Utility]::TaskAssignment($a)
```
MethodException: Cannot find an overload for "TaskAssignment" and the argument count: "1".
I have to offer the second parameter, though it's supposed to be optional:
```PowerShell
 $b=[PowerShellExtension.Utility]::TaskAssignment($a,8)
```

**Comment by vexx32** [comment]
If you call `[PowerShellExtension.Utility]::TaskAssignment` on its own, what does the overload definition show?

**Comment by SeeminglyScience** [comment]
Looks like it's an issue with generics specifically:

```powershell
Add-Type -TypeDefinition '
    public static class GenericWithOptional
    {
        public static int TestNonGeneric(int arg, byte optional = 0)
        {
            return default(int);
        }

        public static T TestGeneric<T>(T arg, byte optional = 0)
        {
            return default(T);
        }
    }'

[GenericWithOptional]::TestGeneric(0)
# MethodException: Cannot find an overload for "TestGeneric" and the argument count: "1".

[GenericWithOptional]::TestNonGeneric(0)
# 0
```

**Comment by Silver-Fang** [comment]
> Looks like it's an issue with generics specifically:
> 
> ```powershell
> Add-Type -TypeDefinition '
>     public static class GenericWithOptional
>     {
>         public static int TestNonGeneric(int arg, byte optional = 0)
>         {
>             return default(int);
>         }
> 
>         public static T TestGeneric<T>(T arg, byte optional = 0)
>         {
>             return default(T);
>         }
>     }'
> 
> [GenericWithOptional]::TestGeneric(0)
> # MethodException: Cannot find an overload for "TestGeneric" and the argument count: "1".
> 
> [GenericWithOptional]::TestNonGeneric(0)
> # 0
> ```

That's confusing. What's .Net generics supposed to behave in a PowerShell call?

**Comment by SeeminglyScience** [comment]
@Silver-Fang Sorry, what I'm saying is that PowerShell *does* support optional parameters, there is just a bug in the invoke method binder that only occurs when the method is generic.
