### ISSUE TITLE
Out-GridView displays property names with underscores incorrectly

### ISSUE THREAD

**Issue by ViperTG** [PowerShell/PowerShell#11182]
Since PowerShell 7.0.0-preview.6 now has Out-GridView again I will re-report the bugs i reported on uservoice 4 years ago since the bugs are still present.

When using Out-GridView to display objects that have properties with underscores in the names, like `User_Name`, the resulting column displayed in Out-GridView is `UserName`, missing the underscore. 

Behavior is also inconsistent so if the property is named `Name_Of_User` then it displays `NameOf_User`, so removing the first one only.

Multiple underscores seems to get truncated to one so `__` displays as _ and `___` displays as `_`

It does not affect the actual property names of the output when using `-PassThru` so it is only displaying it wrong.

Common scenario is you are looking at data from a csv file by `Import-Csv | Out-GridView` that you got from someone and you se the column `UserName`. You write some filter for the data based on property `UserName` but it does not work since the property was named `User_Name`

# Steps to reproduce

```powershell
[pscustomobject]@{
    With_underscore = "somedata"
    With_two_underscores = "moredata"
    With__double_andsingle = "even more data"
    whatdoes___tripledo = "can i have data"
} | Out-GridView
```

# Expected behavior

```none
I expected the column names in Out-GridView to have the same names as the properties

With_underscore With_two_underscores With__double_andsingle whatdoes___tripledo
--------------- -------------------- ---------------------- -------------------
somedata        moredata             even more data         can i have data
```

# Actual behavior
![image](https://user-images.githubusercontent.com/26866146/69498401-0fe3a480-0ee8-11ea-87d3-91991a664aac.png)

Instead it is truncating _ char in the column names. Single _ is removed, double __ is reduced to one _ and triple ___ is reduces to a single _.
# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@ViperTG The cmdlet was included in PowerShell 7.0 for backward compatibility only. No plans exist to improve something in the code. All new work will be in https://github.com/PowerShell/GraphicalTools
