### ISSUE TITLE
Add .psh* as a recognised file extension

### ISSUE THREAD

**Issue by Lombra** [PowerShell/PowerShell#11181]
So, I understand that this has been suggested and discussed to great lengths before, and I understand that backwards compatibility is the problem. One thing I don't understand, however, is why additional recognised extensions couldn't be added, while keeping but deprecating the old .ps1 extensions?

I would think the 1 only serves to confuse people into thinking those scripts are for PowerShell 1.0 only. To me it seems like using version based extensions isn't really a thing anyway, looking at other languages and even file types overall. (of course, that doesn't mean PowerShell couldn't set a new trend) PowerShell Core 6 already came without introducing a new extension, while breaking a bunch of things.

My suggestion would be to remove 1 from all relevant extensions, and use .psh as the base extension. (maybe even .posh since .psh seems to be used for some obscure things?) .ps1 becomes .psh, .psm1 becomes .pshm, etc.

**Comment by iSazonov** [comment]
It is dup
https://github.com/PowerShell/PowerShell/issues/2013#issuecomment-247987977
#5904
#6074
