### ISSUE TITLE
Out-GridView displays no data in columns when the property name has a leading or trailing whitespace, . or / in the name

### ISSUE THREAD

**Issue by ViperTG** [PowerShell/PowerShell#11184]
In **PowerShell 7.0.0-preview.6**

Now that Out-GridView is back I am re-reporting the bugs i have reported to user voice several years ago and the bugs are still present.

When displaying objects with Out-GridView and the object has a property name with leading or trailing `whitespace` or a `.` or a `/`, then the data in the column is not displayed at all.

The column for these are just empty leading the user to believe the property data is empty.
Typically I see this when importing CSV files and people give columns in tables weird names.

From my testing I have identified this issue with the following chars as leading or trailing in the property names.
```powershell
[char]9
[char]10
[char]11
[char]12
[char]13
[char]32
'.'
'/'
```

# Steps to reproduce

```powershell
1..10 | ForEach-Object {
    [pscustomobject]@{
        'NormalColumn' = "Normal$_"
        ' ThisDoesNotDispayData' = "Hidden$_"
        'NeitherDoesThis ' = "AlsoHidden$_"
        '.SameForDot' = "NoData$_" 
        '/SameForSlash' = "NoData$_" 
    }
} | Out-GridView
```

# Expected behavior
In the Out-GridView window i would expect the data in the columns 2, 3, 4, 5 to be displayed, instead they are empty as if the properties had no data.
Format-Table ouput show the data as expected.
```none
NormalColumn  ThisDoesNotDispayData NeitherDoesThis  .SameForDot /SameForSlash
------------ ---------------------- ---------------- ----------- -------------
Normal1      Hidden1                AlsoHidden1      NoData1     NoData1
Normal2      Hidden2                AlsoHidden2      NoData2     NoData2
Normal3      Hidden3                AlsoHidden3      NoData3     NoData3
Normal4      Hidden4                AlsoHidden4      NoData4     NoData4
Normal5      Hidden5                AlsoHidden5      NoData5     NoData5
Normal6      Hidden6                AlsoHidden6      NoData6     NoData6
Normal7      Hidden7                AlsoHidden7      NoData7     NoData7
Normal8      Hidden8                AlsoHidden8      NoData8     NoData8
Normal9      Hidden9                AlsoHidden9      NoData9     NoData9
Normal10     Hidden10               AlsoHidden10     NoData10    NoData10
```

# Actual behavior
No data is displayed in the 10 rows for column 2, 3, 4, 5

![image](https://user-images.githubusercontent.com/26866146/69499056-969b8000-0eee-11ea-9f17-c09c41c236b2.png)

```none

```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@ViperTG The cmdlet was included in PowerShell 7.0 for backward compatibility only. No plans exist to improve something in the code. All new work will be in https://github.com/PowerShell/GraphicalTools
