### ISSUE TITLE
Separate module dependency from module preload logic

### ISSUE THREAD

**Issue by dronkoff** [PowerShell/PowerShell#11190]
# Summary of the new feature/enhancement

If one module depends on another module and we want these modules to be installed together using `Install-Module` we use `RequiredModules` attribute in psd1 file.
The issue here is that modules from `RequiredModules` will be also imported during the original module import process. If module has many dependencies, like 30 for example, this behavior will slow down module import a lot.
As an example look at [https://www.powershellgallery.com/packages/AzSK/4.3.0](https://www.powershellgallery.com/packages/AzSK/4.3.0) it has many references to Azure modules, which is expected, but all these references are preloaded during module import. 
`Import-Module AzSK` can take 20-50 seconds depending on machine speed and most of this time is lost on module preloading.
There is no need to preload all these modules. Afaik, only couple of them can be preloaded and the rest can be loaded in a lazy manner.

# Proposed technical implementation details (optional)

With PowerShell module base and code base growing there should be a way to describe module in that way, so module author can specify 2 different lists of references - one list for modules that should be preloaded during module import, and a separate list for modules that just should be installed together but not preloaded.
Let's say the behavior of `RequiredModules` attribute remains the same for backward compatibility purposes, and a new attribute like `ReferencedModules` is introduced that has a list of modules that are installed together but modules from this list are not preloaded during `Import-Module` so module can utilize lazy loading behavior for referenced modules and speed up it's import time.

**Comment by iSazonov** [comment]
I guess most of the slow down comes from AppLocker. See #11074

**Comment by dronkoff** [comment]
Fortunately, the issue with AzSK used as an example is easily reproducible. 
I've used Trace-Command to get the timings.
`Trace-Command -Name ('Modules', 'FileSystemProvider') -Expression {Import-module AzSK} -ListenerOption 'DateTime' -PSHost`
How can I trace to be sure if it's AppLocker or not?

**Comment by iSazonov** [comment]
https://github.com/microsoft/perfview is great tool to discover allocations and performance issues.

**Comment by dronkoff** [comment]
Thanks. It'd be nice to know what particular ETW events from what provider to collect to make observations of PowerShell and AppLocker performance.

**Comment by iSazonov** [comment]
Use default settings. This will works well for your case.

**Comment by dronkoff** [comment]
The defaults are: Kernel Base, .NET, Cpu Samples and TPL providers. How they'll help to understand what's happening inside PowerShell? It doesn't consume memory or CPU during module import.

**Comment by iSazonov** [comment]
See my screenshot https://github.com/PowerShell/PowerShell/issues/11074#issuecomment-559456002

PerfView collects .Net events and with pdb symbols show all .Net callsites to you.

If you want to get more (full system trace, not only your .Net allication) you could use Windows Performance tools (WPR/WPA).

**Comment by dronkoff** [comment]
I know how PerfView works, thanks. The usual question with PerfView is how to analyse the collected data - what particular events to look at and how to aggregate them.
In context of this issue and your advise to use PerfView, taking into account that there are no predefined collector options and views for PowerShell events in PerfView the question rises - what ETW providers do you suggest to subscribe to and how to interpret collected events?
