### ISSUE TITLE
Inconsistent handling of - as a parameter

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#11199]
# Steps to reproduce

```powershell
function test {
[cmdletbinding()]
param ($x) 
7
$x 
}
```

Test -  returns 
7
-

Test ---  returns 
7
---
but test -- returns 
7

-- is not acting as a decrement operator, not as a parameter named "-"  (test -a causes an error) nor as a value.  

# Expected behavior

```none
-- should either be passed as a value, or recognised as a (misplaced) operator, or treated as a parameter name. 
```

# Actual behavior

```none
-- appears to be ignored
```

# Environment data

```none
Applies on 5.1, 6.2 and 7 preview 6. Windows and 6.2 on WSL 
```

**Comment by SeeminglyScience** [comment]
@jhoneill it's not ignored necessarily, it's a modifier.  When used, any parameters after it are treated like string input:

```powershell
Write-Output -- -Testing -These -Are -Strings
# -Testing
# -These
# -Are
# -Strings
```

**Comment by jhoneill** [comment]
@SeeminglyScience  OK. Just when I think there's an area where I can't learn any more :-)  Never seen that anywhere.  Thanks. 

But it's plainly by design, so let's close this and file under "No further action"

**Comment by vexx32** [comment]
@SeeminglyScience do you know if that's documented anywhere? I haven't seen it mentioned in any docs that I recall.

**Comment by SeeminglyScience** [comment]
I looked around briefly, couldn't find anything.  It's come up before in the past six months or so, so I think it's documented somewhere, maybe just as an issue.

@mklement0 was it you I discussed this with last time? I vaguely remember you being involved somehow.
