### ISSUE TITLE
Where is ConvertTo-Json -EscapeHandling EscapeHtml

### ISSUE THREAD

**Issue by diering5** [PowerShell/PowerShell#11195]
# Support Question
I am writing a powershell script which reads in a json file, I manipulate it, and then I write it back to a json file. The problem is that when I write the values to a file the html characters are not escaped. For example, the character ">" is getting written as "\u003e". 

When converting to json I tried using this in my code:
`$jsonOut = $navJson | ConvertTo-Json -Depth 50 -EscapeHandling EscapeHtml`

However, I keep receiving the error:
`A parameter cannot be found that matches parameter name 'EscapeHandling'`

This is very confusing because it is clearly a parameter based on the Microsoft docs:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6

## Official support

[PowerShell Support Lifecycle](https://aka.ms/pslifecycle)

## Community Resources

[Slack][powershell-slack] and [Discord][powershell-discord] Community Chat - Interactive chat with other PowerShell enthusiasts. Both Slack and Discord are bridged via a bot and can seamlessly talk to each other.

[StackOverflow.com](https://stackoverflow.com/questions/tagged/powershell) and [PowerShell.org Forum](https://powershell.org/forums/) - Search or post new general PowerShell usage questions

[powershell-slack]: https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM
[powershell-discord]: https://discordapp.com/invite/AtzXnJM

**Comment by he852100** [comment]
You need to provide json data.

**Comment by diering5** [comment]
Here is a sample of the json data. I'm not sure why that would affect the parameter for the function though:
{
    "shortcuts": [
        {
            "title": "stuff & things",
            "things": [
                {
                    "items": [
                        {
                            "heading": "Home"
                        },
                        {
                            "url": "/home/ethics/",
                            "text": "Ethics"
                        },
                        {
                            "url": "/home/fax/",
                            "text": "Fax"
                        },
                        {
                            "url": "/who/ips.htm",
                            "text": "IPS Menu"
                        },
                        {
                            "url": "/regulator/",
                            "text": "Regulator"
                        },
                        {
                            "url": "/who/",
                            "text": "Who"
                        }
                    ]
                },
                {
                    "items": [
                        {
                            "heading": "Business Supplies"
                        },
                        {
                            "url": "/sc/login.aspx",
                            "text": "TechStor",
                            "helptext": "computer, printers & accessories"
                        },
                        {
                            "url": "/supplies/index.htm",
                            "text": "Office Supplies",
                            "helptext": "office supplies"
                        }
                    ]
                }
            ]
        },
        {
            "title": "Internet Sites",
            "columns": [
                {
                    "items": [
                        {
                            "heading": "Stock Market"
                        },
                        {
                            "url": "http://www.marketwatch.com",
                            "text": "CBS-MarketWatch"
                        },
                        {
                            "url": "http://finance.google.com/finance",
                            "text": "Google Finance"
                        },
                        {
                            "url": "http://www.morningstar.com",
                            "text": "Morningstar"
                        },
                        {
                            "url": "http://finance.yahoo.com",
                            "text": "Yahoo! Finance"
                        },
                        {
                            "heading": "News"
                        },
                        {
                            "url": "http://www.cnn.com",
                            "text": "CNN"
                        },
                        {
                            "url": "http://www.cbsnews.com/",
                            "text": "CBS News"
                        },
                        {
                            "url": "http://www.foxnews.com/ ",
                            "text": "Fox"
                        },
                        {
                            "url": "http://www.npr.org/",
                            "text": "National Public Radio"
                        },
                        {
                            "url": "http://www.msnbc.com",
                            "text": "MSNBC"
                        },
                        {
                            "heading": "Maps"
                        },
                        {
                            "url": "http://maps.google.com/maps",
                            "text": "Google Maps"
                        },
                        {
                            "url": "http://www.mapquest.com",
                            "text": "Mapquest"
                        }
                    ]
                },
                {
                    "items": [
                        {
                            "heading": "Social Media"
                        },
                        {
                            "url": "http://www.facebook.com",
                            "text": "Facebook"
                        },
                        {
                            "url": "http://www.linkedin.com",
                            "text": "LinkedIn"
                        },
                        {
                            "url": "https://twitter.com",
                            "text": "Twitter @nmbradford"
                        },
                        {
                            "url": "https://twitter.com",
                            "text": "Twitter @NM"
                        },
                        {
                            "url": "http://www.youtube.com/",
                            "text": "YouTube"
                        },
                        {
                            "heading": "Web"
                        },
                        {
                            "url": "http://www.bing.com",
                            "text": "Bing"
                        },
                        {
                            "url": "http://www.google.com",
                            "text": "Google"
                        },
                        {
                            "url": "http://www.yahoo.com",
                            "text": "Yahoo!"
                        }
                    ]
                }
            ]
        },
        {
            "title": "Communities",
            "columns": [
                {
                    "items": [
                        {
                            "url": "/ccp/Pages/default.aspx",
                            "text": "CCP <em>Childhood Cancer Program</em>"
                        }
                    ]
                }
            ]
        }
    ],
    "nav": [
        {
            "title": "Client Service",
            "folder": "/client_svc/",
            "option": [
                {
                    "url": "/resources/",
                    "text": "Resources"
                },
                {
                    "url": "/insurance/",
                    "text": "Insurance"
                },
                {
                    "url": "/annuities/",
                    "text": "Annuities"
                },
                {
                    "url": "/crc/",
                    "text": "CRC <em>Client Relations Center</em>"
                }
            ]
        },
        {
            "title": "Running<br>the Business",
            "folder": "/run_bus/",
            "option": [
                {
                    "url": "/mgmnt/",
                    "text": "Management"
                },
                {
                    "url": "/plan/",
                    "text": "Planning"
                },
                {
                    "url": "/compl/",
                    "text": "Compliance"
                },
                {
                    "url": "/technology/",
                    "text": "Technology"
                },
		{
                    "url": "/sbs/",
                    "text": "Services"
                },
                {
                    "url": "/supplies/",
                    "text": "Supplies"
                },
                {
                    "url": "/recruiting/",
                    "text": "Recruiting"
                },
                {
                    "url": "/staffing",
                    "text": "Staffing"
                },
                {
                    "url": "/diversity/",
                    "text": "Diversity"
                }
            ]
        },
        {
            "title": "Financial",
            "folder": "/fin/",
            "option": [
                {
                    "url": "/comp/",
                    "text": "Compensation"
                },
                {
                    "url": "/benefits/",
                    "text": "Benefits"
                },
                {
                    "url": "/sales/",
                    "text": "Sales"
                },
                {
                    "url": "/account/",
                    "text": "Accounting"
                }
            ]
        },
        {
            "title": "News",
            "folder": "/news/",
            "option": [
                {
                    "url": "/news/",
                    "text": "News"
                },
                {
                    "url": "/newsletters/",
                    "text": "Newsletters"
                },
                {
                    "url": "/info/",
                    "text": "Information"
                },
                {
                    "url": "/annual/",
                    "text": "Annual"
                },
                {
                    "url": "/regional/",
                    "text": "Regional"
                },
                {
                    "url": "/other/",
                    "text": "Other"
                },
                {
                    "url": "/stories/",
                    "text": "Stories"
                }
            ]
        },
        {
            "title": "Contacts",
            "folder": "/contacts/",
            "option": [
                {
                    "url": "/home/",
                    "text": "Home"
                },
                {
                    "url": "/field/",
                    "text": "Field"
                },
                {
                    "url": "/associations/",
                    "text": "Associations"
                },
                {
                    "url": "/change/",
                    "text": "Changes"
                }
            ]
        }
    ]
}`

**Comment by he852100** [comment]
```powershell
PS /root> cat ~/3                                                 {"employees":[
  { "first?~~\uFF20\uFF05\u3010\u3011\uFF09Nam":"Anna", "lastName":"S?~~\u2026-@\uFF1B\uFF09mith" }
]}

PS /root> cat ~/3|ConvertFrom-Json                                
employees
---------
{@{first?~~＠％【】）Nam=Anna; lastName=S?~~…-@；）mith}}

PS /root> cat ~/3|ConvertTo-Json
[
  "{\"employees\":[",
  "  { \"first?~~\\uFF20\\uFF05\\u3010\\u3011\\uFF09Nam\":\"Anna\", \"lastName\":\"S?~~\\u2026-@\\uFF1B\\uFF09mith\" }",
  "]}"
]
PS /root> cat ~/3|ConvertFrom-Json|Convertto-Json
{
  "employees": [
    {
      "first?~~＠％【】）Nam": "Anna","lastName": "S?~~…-@；）mith"
    }
  ]  
 }
```

**Comment by mklement0** [comment]
You're probably running _Windows PowerShell_, where `-EscapeHandling` isn't supported.

Please note that this repo is only for PowerShell _Core_ (now just called _PowerShell_), and not for general support questions (the template is meant to be information only, to direct you to the appropriate places for getting support).
