### ISSUE TITLE
Get-PSCallStack's Arguments script property contains no useful information

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11208]
The `.Arguments` property on the `System.Management.Automation.CallStackFrame` instances output by `Get-PSCallStack` is a script property that - I presume - is meant to reflect the arguments passed.

The property isn't documented, but it seems to contain no useful information, seemingly containing `$null` in any non-global scope.

While you con obtain argument information via the type-native `.InvocationInfo` property, I assume there is a purpose to `.Arguments` that it currently doesn't fulfill.

# Steps to reproduce

```powershell
& { (Get-PSCallStack)[0].Arguments } 'foo'  | Should -match 'foo'
```

# Expected behavior

The test should pass.

# Actual behavior

The test fails, because `.Arguments` is `$null`:

```none
Expected regular expression 'foo' to match $null, but it did not match.
```

# Environment data

```none
PowerShell Core 7.0.0-preview.6
```

**Comment by SeeminglyScience** [comment]
Looks like that script property got hit by the script that was replacing `""` with `string.Empty`.

The line was:

```powershell
foreach ($arg in $this.InvocationInfo.UnboundArguments.GetEnumerator())
{
if ($argumentsBuilder.Length -gt 1)
{
$argumentsBuilder.Append(", ")
}
# etc...
```

But is now

```powershell
foreach ($arg in $this.InvocationInfo.UnboundArguments.GetEnumerator())
{
if ($argumentsBuilder.Length -gt 1)
{
$argumentsBuilder.Append(string.Empty, string.Empty)
}
# etc...
```

Which is a syntax error.

**Comment by iSazonov** [comment]
@mklement0 Thanks! I pulled PR with fix.
