### ISSUE TITLE
`using module _` fundamental design issues

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShell#11200]
In every language that I'm aware of, specifying a relative path in an import statement resolves the path relative to the current script.  In PowerShell, the path is resolved relative to the current shell location.

So far, this behavior has made `using module <relative-path>` unusable for me.  This is especially troublesome because `using` statements require constant strings and cannot be dynamically resolved with `$PSScriptRoot`.

**Comment by SeeminglyScience** [comment]
> In every language that I'm aware of, specifying a relative path in an import statement resolves the path relative to the current script. In PowerShell, the path is resolved relative to the current shell location.
> 
> So far, this behavior has made `using module <relative-path>` unusable for me. This is especially troublesome because `using` statements require constant strings and cannot be dynamically resolved with `$PSScriptRoot`.

You using forward slashes or backslashes?  If you use backslashes (<kbd>\\</kbd>) it resolves relative to the script location instead.  I believe there's an issue for fixing it with forward slashes.

Quick test:

```powershell
PS> md ./folder/folder2
'class MyClass { static [string] $MyProp = "testing" }' |
    Out-File -Encoding default ./folder/folder2/ExternalClasses.psm1

'using module .\folder2\ExternalClasses.psm1; [MyClass]::MyProp' |
    Out-File -Encoding default ./folder/MainScript.ps1

& .\folder\MainScript.ps1
# testing
```

Switch it to forward slashes in the using statement and it throws.  Just a bug though.

**Comment by chriskuech** [comment]
@SeeminglyScience , you are correct regarding slashes.  Can you link the issue for me and we can close this as duplicate?

**Comment by SeeminglyScience** [comment]
@chriskuech Found it #7424

**Comment by chriskuech** [comment]
Thanks!
