### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by watkins656** [PowerShell/PowerShell#11206]
# Documentation Issue

In the help for Set-ExecutionPolicy, the help is innacurate.  It appears that either there are no acceptable values for this parameter, or that the first acceptable value is Required? true.  Neither of which is correct.

The actual acceptable values should be listed here.

![image](https://user-images.githubusercontent.com/38428507/69755213-5b32c880-111d-11ea-87dd-f63113d04f51.png)

**Comment by vexx32** [comment]
@watkins656 docs for the cmdlets are maintained in the https://github.com/MicrosoftDocs/PowerShellDocs repo as the issue template mentions; please file this issue there instead, if you could?

Thank you! 😊
