### ISSUE TITLE
pwsh run from dotnet global commands always returns 0

### ISSUE THREAD

**Issue by lamawithonel** [PowerShell/PowerShell#11203]
# Steps to reproduce

```sh
dotnet tool install --global powershell
dotnet tool run pwsh -- 'exit 1'
echo $?
```

### Expected behavior

Output of `echo $?` should equal `1`

### Actual behavior

Output of `echo $?` equals `0`

### Environment data

```
#> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

dotnet SDK: version 3.0.101
Bash: 5.0.11

Also reported at dotnet/sdk#3974

**Comment by jhoneill** [comment]
That looks like  an issue with the command running PowerShell rather than PowerShell itself. 
in cmd you can run 
```
cmd /c "PowerShell ""exit 1"" 
echo %errorlevel%
```
Which returns 1.  even 
`powershell "pwsh -command 'exit 1' "` or `cmd /c "PowerShell ""exit 1"" "`
work. 

Does dotnet tool run return error levels from other tools ?

**Comment by iSazonov** [comment]
@lamawithonel Thanks for your report. It is dup #10362.
