### ISSUE TITLE
Type testing with pattern matching

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#11212]
# Summary of the new feature/enhancement

As a scripter,
I want PowerShell to support type testing with pattern matching with the -is operator
so that I can write much more elegant, compact code.

# Proposed technical implementation details (optional)

C# spoils me with simple syntax that makes code much easier to write and maintain.

One addition that showed up in C# 7 that I'd like to implement in PowerShell is type testing with pattern matching. This is very helpful when you have to deal with .NET types, such as when you are processing AST.

For example, consider this snippet:

```powershell
$ast = {Get-Command Get-Process -Syntax}.Ast
$commandAst = $ast.FindAll({
    param($ast)
    $commandAst = $ast -as [System.Management.Automation.Language.CommandAst]
    if ($commandAst -ne $null) {
        $stringConstantExpressionAst = $commandAst.CommandElements[0] -as [System.Management.Automation.Language.StringConstantExpressionAst]
        return $stringConstantExpressionAst -ne $null -and
               $stringConstantExpressionAst.StringConstantType -eq [System.Management.Automation.Language.StringConstantType]::BareWord -and
               $stringConstantExpressionAst.Value -eq 'Get-Command'
    }
    return $false
}, $true);
```

That's very cumbersome to write, and it's a pretty simple example. It gets worse if you need to go even deeper with nested if blocks.

Instead, if we support type testing with pattern matching like C# 7 supports, we could write the same logic like this:

```powershell
using System.Management.Automation.Language

$ast = {Get-Command Get-Process -Syntax}.Ast
$commandAst = $ast.FindAll({
    $args[0] -is [CommandAst] $commandAst -and
    $commandAst.CommandElements[0] -is [StringConstantExpressionAst] $stringConstantExpressionAst -and
    $stringConstantExpressionAst.StringConstantType -eq [StringConstantType]::BareWord -and
    $stringConstantExpressionAst.Value -eq 'Get-Command'
}, $true);
```

This syntax is much easier to read than the previous syntax that uses `-as` with `-ne $null`, allowing what is meant to be a series of conditional statements to be written as a series of conditional statements.

Any objections to this proposed addition to PowerShell?

**Comment by KirkMunro** [comment]
For full disclosure, such a change would technically be breaking, because:

```powershell
$x = 'A string'
$bool = 'bool'
$x -is [string] $bool # returns False
```

Today, PowerShell parses the right-hand side of the -is operator separately. In the case of the example shown above, `$bool` is a string containing the value `'bool'`, which is then typecast to a string, returning the value `'bool'`, which is then typecast to a type by the `-is` operator, resulting in a comparison checking if `$x` is of type `[bool]`.

I've never seen such code in practice though. I only discovered it by checking to see what would happen if I used code similar to what I'm proposing here. It is unlikely that such code exists in practice, as there is no value in casting something with the `-is` operator.

Also, note that the following examples don't work today, so the possibility of actually breaking something is pretty much non-existent:

```powershell
$x = 'A string'
$string = 'Another string'
$x -is [string] $string # raises an error because 'Another string' is not a type

$x = $true
$string = 'A string'
$x -is [bool] $string # raises an error because you cannot convert boolean true or false to System.Type
```

Last, just to call it out, I would implement this syntax extension for `-is`, but I would not do anything for `-isnot`, because there is no use case for that.

**Comment by vexx32** [comment]
@KirkMunro C#'s pattern matching supports conditionals with negative pattern matching too:
```csharp
if (!(value is Type convertedValue))
{
    // convertedValue does not exist here
}

// convertedValue exists here
```

Perhaps something similar could still be useful with `-isnot`?

**Comment by KirkMunro** [comment]
I worry that might be more challenging than it's worth. Still, good to know it's there. That's a pattern I haven't used in C# yet.

**Comment by iSazonov** [comment]
Maybe we can generalize and propose a syntax to store result for any sub-expression?

**Comment by vexx32** [comment]
There (sort of) is that already, but as Kirk says it's not the greatest syntax:

```powershell
if ($convertedValue = $value -as [type]) {
    # do things with $convertedValue
}
```

**Comment by iSazonov** [comment]
My thoughts is about `bool TryChech(out Type result)` pattern.

**Comment by vexx32** [comment]
The closest analogue for that in PS is much more akin to `Test-Value $value -Out [ref]$var` which is probably a pattern I think we should avoid.

It works well for C#, but if we're doing something like this in PS I think the expression syntax is much more effective here.

**Comment by iSazonov** [comment]
It is not new for PowerShell to store a side result. In pipeline we have PilpelineVariable parameter. Perhaps we could have something like for expressions.

**Comment by KirkMunro** [comment]
Here are some alternate syntax proposals that may be more in line with "the PowerShell way", and that would also be non-breaking:

```powershell
# Explicitly identifying the variable with an additional operator option
if ($x -is [string] -typecastVariable myString) {$myString.Length}

# Or, using shorthand (which could be supported in addition to the above):
if ($x -is [string] -tv myString) {$myString.Length}

# Or, simply using comma (like the -split operator, which has optional additional arguments)
if ($x -is [string],myString) {$myString.Length}
```

I'm not particularly attached to any one of these more than the others. As long as I can assign a value as part of the `-is` comparison, I'll be happy.

I'm not sure where or how something like this could be applied generically to all expressions @iSazonov. Do you have suggestions? It seems to me something that should be done on a case-by-case basis, because the thing you want to capture as a side result depends on what you are doing.

**Comment by vexx32** [comment]
I think I prefer the syntax from the original proposal. `-PipelineVariable` works the way it does because it's probably the least complicated way to manage it from a cmdlet's perspective. I don't think that approach adds value in the expression syntax over what you originally proposed, Kirk. 🤔

**Comment by KirkMunro** [comment]
I think I do as well. It looks more like you're strongly typing something, which is exactly what is being done in that case. I just wanted to share additional options for consideration.
