### ISSUE TITLE
DSC Support for splatting resources

### ISSUE THREAD

**Issue by kewalaka** [PowerShell/PowerShell#11219]
It would be great to be able to splat natively into DSC resources.  An example of a workaround for this is described [here](https://gaelcolas.com/2017/11/05/pseudo-splatting-dsc-resources/).

The desired outcome would be to be able to do something like this:

```
$MyHashes = @(
  @{
    Ensure  = 'Present'
    Name    = 'Putty'
    Version = 'Latest'
    ChocolateyOptions = @{ source = 'https://chocolatey.org/api/v2/' }
  },
  @{
    Ensure  = 'Absent'
    Name    = 'notepadplusplus'
  }
)

Configuration MyDscConfig {
    $Allnodes.nodename {
        foreach($MyHash in $MyHashes) {
            ChocolateyPackage $MyHash['name'] @MyHash
        }
    }
}
```

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this be moved to the PSDSC repository?
