### ISSUE TITLE
PS SDK 6.2.3 does not honor PSModulePath when used via PowerShell.invoke

### ISSUE THREAD

**Issue by mazhar10** [PowerShell/PowerShell#11213]
I am launching a PS script from C# via PowerShell.Create(), ..., Invoke().
Inside the PS script, I am writing the results of Get-Module -ListAvailable to a file.
Nothing gets written to the file.
**However**
If I do the below, then all installed modules (well, at least the ones in the PSModulePath) show up fine.
. 
.
`
SessionStateProxy proxy = runspace.SessionStateProxy;
string psModulePath = proxy.GetVariable("eng:PSModulePath").ToString();
proxy.SetVariable("env:PSMOdulePAth:,$@"{psModulePath}");
`

Above makes no sense to me - why would simply getting and setting PSModulePath make any difference?

**Comment by rjmholt** [comment]
@mazhar10 would you be able to give us a full C# program with a minimal repro in it? I can't work out what's happening in the code you've supplied so far

**Comment by mazhar10** [comment]
See the snippet below. The problem is remediated by adding in the piece between the "shenanigan" comments, and the problem appears if you remove those few lines:
`
public static string RunPS1(string psFile, string sJSONIn)
{
    InitialSessionState initPSState = InitialSessionState.CreateDefault();
    initPSState.AuthorizationManager = new AuthorizationManager("Microsoft.PowerShell");
    Runspace runspace = RunspaceFactory.CreateRunspace(initPSState);
    runspace.Open();
    
    // Below shenanigan is needed otherwise PS core never sees modules in PSModulePath when invoked via runspace.
    SessionStateProxy proxy = runspace.SessionStateProxy;
    string psModulePath = proxy.GetVariable("env:PSModulePath").ToString();
    proxy.SetVariable("env:PSModulePath", $@"{psModulePath}");
    // End shenanigan

    string sJSONOut ="";

    PowerShell ps1 = PowerShell.Create();
    string scrpt1 = File.ReadAllText(psFile);
    ps1.AddScript(scrpt1);
    ps1.AddParameter("sJSONIn", sJSONIn);
    ps1.Runspace = runspace;
    Collection<PSObject> results=ps1.Invoke();

    foreach (PSObject o1 in results)
    {
        sJSONOut += o1.ToString();
    }
    runspace.Close();
    ps1.Dispose();
    return (sJSONOut);
}

`

**Comment by JamesWTruher** [comment]
please see #11211 for additional information. You need to be sure that the PSModulePath is propagated to the new powershell instance. Your code is one approach, but there are many other ways to do this.
