### ISSUE TITLE
PS SDK 6.2.3 ImportPSModule does nothing

### ISSUE THREAD

**Issue by mazhar10** [PowerShell/PowerShell#11211]
I am using PS core SDK 6.2.3.

I have a PS script that has an "import-module psmod1.psm1" statement.

Inside the PS script, I do a get-module and then write the names of all the loaded modules to a text file.

The script runs fine when run from pwsh on the CLI, and I see psmod1.psm1 written to the text file

I am invoking the script from within a .NET CORE C# application. This time the script runs fine but no module names get written to the text file (I am writing some other text to ensure the file itself is being successfully written to etc. and all that works fine).

So, since import-module inside the PS script did not appear to be working, I then added loading of the module to the C# code. This was done by using InitialSessionsState.CreateDefault() and then using ImportPSModule.

I still get the same results, it seems that for PS code invoked from within C# via RunSpaceFactory.CreateRunspace, it is impossible to import modules, either within the PS code file or from within C#. I have tested this on Windows 2008R2 as well as Windows 2012R2.

**Comment by iSazonov** [comment]
@mazhar10 To get a help you could create/share a GitHub project.

**Comment by mazhar10** [comment]
I changed the code in C# to use PowerShell.Create instead of CreatePipeline(), read the PS file into a C# string and fed it to the powershell instance via AddScript, now the import-module statement **inside** the PS code works fine.

**Comment by JamesWTruher** [comment]
Please be sure that that the module is either available via full path or ensure that `$env:PSModulePath` includes the directory to your module. The PSModulePath for hosted app is likely different than that of the console app, which can be the cause of this issue. Also check `PowerShell.Streams` properties to retrieve any errors which may occur in the invocation.
