### ISSUE TITLE
Expose API for profile paths and other common locations for modules and other hosts to use

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#11223]
# Summary of the new feature/enhancement

The PowerShell extension has its own profile paths, but it generates these based on the hosting PowerShell session's profile locations.

This is easy to do in script, but significantly harder from C#. There's some back and forth in the PowerShell codebase between SMA and ConHost when it comes to creating these paths, and it looks like we should generalise the API and expose it for general use in PowerShell-targeting .NET libraries.

**Comment by iSazonov** [comment]
Have you a proposal?
Is it related to "shellid"-s?

**Comment by rjmholt** [comment]
I should add that this is particularly tricky to work around, since `[powershell]::Create().AddScript('$profile').Invoke()` returns nothing and accessing variables from across threads is not all that safe or easy to do.

> Have you a proposal?

`$profile` seems to be an implicit host API (similar to things like the module installation locations). So I'm imagining this to be yet another API to be overridden on `PSHost`. I don't want to get more concrete than that without collecting some more requirements.

**Comment by SeeminglyScience** [comment]
At the very least some static string properties with the defaults that `ConsoleHost` uses would be nice.  Especially useful if the paths ever change again (like the `WindowsPowerShell` folder changing to `PowerShell`).

**Comment by TylerLeonhardt** [comment]
I have a broader issue out here with code snippets so I'm going to close this to that one.

https://github.com/PowerShell/PowerShell/issues/12322
