### ISSUE TITLE
[Feature Request(Write-host)]Add support for color codes

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11231]
The default options currently available are very limited and the display is poor, and when color is matched, the problem is more serious.

Does the powershell provide support for color codes or add brightness options?

example

```
Write-host -BackgroundColor Green -Backgroundbright 50 -ForegroundColor DarkMagenta
Write-host  -ForegroundColor "#60000" -ForegroundColor DarkMagenta
```

**Comment by vexx32** [comment]
VT escape sequences with color codes are supported as long as the terminal actually supports them. You can look over this gist for an example of how they can be used, I use this for my personal `prompt` function to add some nice color, among other things.

https://gist.github.com/vexx32/94ac39486e84a3ea28ef0a9dda6c5a3c

**Comment by he852100** [comment]
Thank you

I have a question:

If the script or module is publicly available, does it still work

**Comment by iSazonov** [comment]
Dup 2381
