### ISSUE TITLE
PowerShell.7 WinRM environment does not allow to use System.Runtime.Loader.AssemblyDependencyResolver

### ISSUE THREAD

**Issue by dmitriyse** [PowerShell/PowerShell#11238]
# Steps to reproduce
1) RemoteMachine:
Enable WinRM, 
Enable PowerShell.7 WinRM configuration.

2) ClientMachine
```powershell
    $psSession = New-PSSession $ipToConnect -Credential $cred -ConfigurationName "PowerShell.7"
    Invoke-Command -Session $psSession {
        $resolver = [System.Runtime.Loader.AssemblyDependencyResolver]::new("$PSHome\pwsh.dll")
        Write-Host $resolver
    }
```

# Expected behavior

```none
System.Runtime.Loader.AssemblyDependencyResolver
```

# Actual behavior

```none
MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Dependency resolution failed for component C:\Program Files\PowerShell\7-preview\pwsh.dll with error code -2147450750. Detailed error: Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.
"
```

# Environment data
RemoteMachine:

```none
Name                           Value
----                           -----
PSEdition                      Core
PSVersion                      7.0.0-preview.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
Platform                       Win32NT
GitCommitId                    7.0.0-preview.6
PSRemotingProtocolVersion      2.3
OS                             Microsoft Windows 10.0.18363
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@dmitriyse Can you reference a real scenario you want address?
I guess it is a protection for remote session and it is by design.
Perhaps @PaulHigin can add more info.

**Comment by daxian-dbw** [comment]
> Hostpolicy must be initialized and corehost_main must have been called

The remoting plugin `pwrshplugin.dll` is a native entry point that hosts CoreCLR, and I'm sure it doesn't deal with anything related to `HostPolicy` (`hostpolicy.dll`).
The [hosting-layer-apis](https://github.com/dotnet/runtime/blob/master/docs/design/features/hosting-layer-apis.md) doc says `hostpolicy` library is for advanced hosting scenarios.

**Comment by dmitriyse** [comment]
One example scenario of usages of AssemblyResolveContext in powershell script is when you are trying to load plugin library into powershell, but this library is in the development stage and not yet published (located usually at ```bin\Debug\netcoreapp3.1\```), and *.deps.json is required to load all dependencies of a plugin.
There are many ways to host .Net Core, but current WinRM plugin implementation uses simple way which don't initialized hostingpolicy. Unfortunately the current .Net Core implementation have strong dependency from AssemblyResolveContext API to" hostingpolicy" and thus you cannot use *.deps.json to load plugins in development.
This case is not frequent, but to achieve my goals I was required to spend 2 more days to setup SSH channel instead WinRM in my development and production environments as a workaround. It was very disappointing.

**Comment by daxian-dbw** [comment]
> One example scenario of usages of AssemblyDependencyResolver in powershell script is when you are trying to load plugin library into powershell, but this library is in the development stage and not yet published (located usually at bin\Debug\netcoreapp3.1\), and *.deps.json is required to load all dependencies of a plugin.

@dmitriyse This sounds interesting. Do you put the plugin library, say `pluginlib.dll` and `pluginlib.deps.json`, in `$PSHOME` in your scenario?
Can you please provide more details of the scenario? For example, how are you using `AssemblyDependencyResolver` in your script for the loading of `pluginlib.dll`?

**Comment by iSazonov** [comment]
@dmitriyse ping.

**Comment by dmitriyse** [comment]
Assume the ```c:\myproject\bin\myplugins``` is an output directory for the Plugin1 project.
When Visual Studio compiles Plugin1 project there are some files in the ```c:\myproject\bin\myplugins```:
```Plugin1.dll```
```Plugin1.dll.deps.json```
```ProjectDep1.dll``` <- some dependencies are copied during the build
```ProjectDep2.dll``` <-
But for example ```Newtonsoft.Json.dll``` is not copied to in the ```c:\myproject\bin\myplugins```
it's referenced through ```Plugin1.dll.deps.json``` and located some where in ```C:\Program Files\dotnet..```

So I need some trick to parse ```Plugin1.dll.deps.json``` and load ```Newtonsoft.json.dll``` from the correct location.
Fortunately in the .Net Core 3.0 we have ```AssemblyDependencyResolver``` class.

To load the non-published plugin in the PowerShell we need to use this code:
```PowerShell
$CSharpModuleRoutinesSrc = @"
using System;
using System.Reflection;
using System.Runtime.Loader;

namespace Utils.PowerShellModule
{
    public class LoadContextForLibrary : AssemblyLoadContext
    {
        private readonly string _depsAssemblyPath;
        private readonly AssemblyDependencyResolver _resolver;

        public LoadContextForLibrary(string depsAssemblyPath)
        {
            _depsAssemblyPath = depsAssemblyPath;
            _resolver = new AssemblyDependencyResolver(depsAssemblyPath);
        }

        public void SubscribeToResolve(AssemblyLoadContext otherContext){
            AssemblyLoadContext.Default.Resolving += (context, asmName) =>
            {
                var asm = this.LoadFromAssemblyName(asmName);
                return asm;
            };
        }
        protected override Assembly Load(AssemblyName assemblyName)
        {
            string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
            if (assemblyPath != null)
            {
                return LoadFromAssemblyPath(assemblyPath);
            }

            return null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (libraryPath != null)
            {
                return LoadUnmanagedDllFromPath(libraryPath);
            }

            return IntPtr.Zero;
        }
    }
}
"@
 Add-Type -TypeDefinition $CSharpModuleRoutinesSrc

$myPluginPath = "c:\myproject\bin\myplugins\Plugin1.dll"

$MyPluginLoadContext = 
    [Utils.PowerShellModule.LoadContextForLibrary]::new($myPluginPath)

# This trick is required to make loaded dependencies visible for the PowerShell
$MyPluginLoadContext = SubscribeToResolve([AssemblyLoadContext]::Default)
        
# Loading library in the default AssemblyLoadContext (which PowerShell also uses)
# But all unresolved assemblies will be resolved with help of $MyPluginLoadContext according to ```Plugin1.dll.deps.json```
Add-Type -Path $myPluginPath

# Happy using of plugin code!
[MyPlugin1.MyType]::new()
```
This example works goon on PowerShell 7.0-RC in the normal startup mode.
But when the powershell were initialized by pwrshplugin.dll (in WinRM remote session) the hostpolicy is not initialized and the AssemblyLoadContext is not available.

**Comment by dmitriyse** [comment]
I am working on very complex docker-based emulator of the real cluster. The cluster management application consist from the combination of .Net Core and PowerShell code and it have no sense about run it in emulation or in a real cluster. Distributed powershell scripts uses PSSessions to manage cluster, it's very beneficial to mount development machine folders (with the visual studio output) in the emulated cluster nodes (docker containers) and run quick testing.

SSH for me was suitable workaround, PowerShell Core started as a normal process when SSH is used.

Later I found the option 
```XML
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
(https://stackoverflow.com/questions/43837638/how-to-get-net-core-projects-to-copy-nuget-references-to-build-output)
But I haven't tried yet this approach.
