### ISSUE TITLE
Ability to disable the startup logo without specifying arguments

### ISSUE THREAD

**Issue by r-darwish** [PowerShell/PowerShell#11233]
# Summary of the new feature/enhancement
When setting Powershell as the default user shell in a unix system using `chsh` it is not allowed to pass any arguments to the shell. Thus, a Unix user which wants Powershell to be its default shell cannot avoid the logo.

# Proposed technical implementation details (optional)
Maybe have Powershell load an additional file before `$profile`. The file could contain settings such as the ability to disable the logo

**Comment by vexx32** [comment]
Perhaps we could have an environment variable that determines whether the logo is displayed?

**Comment by r-darwish** [comment]
I think that environment variables will cause some chicken and the egg problem. Usually, users define environment variables in files such as `~/.profile` which are eventually read by the user shell. There are other ways such as `~/.pam_environment` or `~/.config/environment.d/*.conf` when using systemd, but I don't know if there's a way to do that in macOS.

**Comment by iSazonov** [comment]
We could add an option in powershell.config.json file (and GPO).

**Comment by rashil2000** [comment]
Any updates on this issue? I feel this is much needed.
