### ISSUE TITLE
[My bug report]Typographical confusion with dual-byte characters

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11232]
font:

宋体(simsun.ttf)

```powershell
price  vdat sdm u  h  bws ieps  pd message loaion
-----  ---- --- -  -  --- ----  -- ------- ------
9.62 K    294 4 15 2500    1 175  GIGAT  CHIAO,

哇  dbda llm c噢 hdd   测试 123 pid 消息 位置
-  ---- --- -- ---   -- --- --- -- --
62 KM   294  4  15 2500   1 175 千  哇
```
```powershell
PS > $f;$e
price   : $39.62
vdat    : K
sdm     : 294
u       : 4
h       : 15
bws     : 2500
ieps    : 1
pd      : 175
message :  GIGAT
loaion  : CHIAO,
```
```
plad    : 968
哇    : 62
dbda : KM
llm  : 294
c噢   : 4
hdd  : 15
测试   : 2500
123  : 1
pid  : 175
消息   : 千
位置   : 哇
plad : 96
```
```
PS > Get-Host|select Name,Version,@{N="名称";E={"q"}},@{N="196";E={"间"}}|fl                                                                                          
Name    : ConsoleHost                                             
Version : 6.2.3                                                   
名称      : q                                                     
196     : 间
```
```
PSVersion                      6.2.3/7                              
PSEdition                      Core                               
GitCommitId                    6.2.3/7                              
OS                             Linux 4.9.112-perf #1 SMP 
PREEMPT… Platform                       Unix
```

----
Test string
```json
{
  "哇": "62",
  "dbda": "KM",
  "llm": "294",
  "c噢": 4,
  "hdd": 15,
  "测试": 2500,
  "123": 1,
  "pid": 175,
  "消息": "千",
  "位置": "哇",
  "plad": 96
}
```
```json
{
  "price": "39",
  "vdat": "K",
  "sdm": "294",
  "u": 4,
  "h": 15,
  "bws": 2500,
  "ieps": 1,
  "pd": 175,
  "mesage": " IGAT",
  "loaion": "CHIAO,",
  "plad": 968
}
```

**Comment by iSazonov** [comment]
@he852100 Can you check without PSReadline and with latest PSREadline version?

**Comment by he852100** [comment]
![Screenshot_20191202-151911~2](https://user-images.githubusercontent.com/26913892/69938273-d29a9a80-1517-11ea-953d-308896dbdccf.png)

**Comment by iSazonov** [comment]
@SteveL-MSFT Formatting System issue?

**Comment by he852100** [comment]
Line break issues.
Version:7,6,5.1,5
system:server2019,centos
![Screenshot_20191203-153054~2](https://user-images.githubusercontent.com/26913892/70030161-95034380-15e3-11ea-8695-66896c18a831.png)

**Comment by SteveL-MSFT** [comment]
PSReadLine has some code to determine the screen cell width of characters, it seems that the formatting system needs to adopt this to correctly calculate whitespacing.  I'll take a look at this, but think it won't be a small change (although not complex)

**Comment by kwkam** [comment]
#5739 had been ignored and #11262 was merged within a week, not surprised though.
Anyway, thanks for fixing this, finally.

**Comment by iSazonov** [comment]
@kwkam You are ahead of time! 
(I have no experience in the area - sorry that was no help from me.)

**Comment by SteveL-MSFT** [comment]
@kwkam sorry that your PR was ignored, but it was prefixed as `WIP:` so usually team members don't spend time reviewing those until it is not a work-in-progress.  I wasn't aware you had submitted that PR and didn't mean to take it over.
