### ISSUE TITLE
[Environment]::GetFolderPath() doesn't support all KNOWNFOLDERID's

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#11240]
It should be possible to retrieve the location of all "special folders" instead of hardcoding them (or assuming they are just subfolders of the user's profile folder).

As of today, `[Environment]::GetFolderPath()` (which reportedly relies on [SHGetKnownFolderPath()](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath)) doesn't support all [KNOWNFOLDERID](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid)'s. Here's a few of the ones that are not supported:

````
FOLDERID_Downloads
FOLDERID_DocumentsLibrary
FOLDERID_CameraRoll
````

I understand this might be a .Net Core issue, not a PowerShell Core issue (haven't checked out the code yet).

# Steps to reproduce

````
[Environment]::GetFolderPath('Downloads')
````

# Expected behavior

````
c:\users\joe\Downloads
````

# Actual behavior

````
MethodException: Cannot convert argument "folder", with value: "Downloads", for "GetFolderPath" to type "System.Environment+SpecialFolder": "Cannot convert value "Downloads" to type "System.Environment+SpecialFolder". Error: "Unable to match the identifier name Downloads to a valid enumerator name. Specify one of the following enumerator names and try again:
Desktop, Programs, MyDocuments, Personal, Favorites, Startup, Recent, SendTo, StartMenu, MyMusic, MyVideos, DesktopDirectory, MyComputer, NetworkShortcuts, Fonts, Templates, CommonStartMenu, CommonPrograms, CommonStartup, CommonDesktopDirectory, ApplicationData, PrinterShortcuts, LocalApplicationData, InternetCache, Cookies, History, CommonApplicationData, Windows, System, ProgramFiles, MyPictures, UserProfile, SystemX86, ProgramFilesX86, CommonProgramFiles, CommonProgramFilesX86, CommonTemplates, CommonDocuments, CommonAdminTools, AdminTools, CommonMusic, CommonPictures, CommonVideos, Resources,
LocalizedResources, CommonOemLinks, CDBurning""
````

# Environment data

````
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

````

**Comment by vexx32** [comment]
@sba923 see this document from MS: https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid

While the Downloads folder is listed, you'll note it has no CIDL equivalent. I don't know the history, but looking at the method you're using, it is noted that accepted values are based on CIDL values (which there aren't any for the Downloads folder). See the Remarks section here: https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath

See also this StackOverflow answer for some c# examples which can be adapted for use in Powershell: https://stackoverflow.com/questions/10667012/getting-downloads-folder-in-c/21953690

My guess would be that the GetFolderPath method hasn't been updated in a while; fixing that would definitely be a .net Core issue :slightly_smiling_face:

**Comment by sba923** [comment]
Shall I create a C# repro, open a .Net Core issue and link it from here?

**Comment by vexx32** [comment]
I'd say that's probably the best idea. Might want to check the existing issues on https://github.com/dotnet/corefx to see if there's already an issue you can add to, but otherwise definitely open a new issue for it. 🙂

**Comment by sba923** [comment]
(https://github.com/dotnet/corefx/issues/42733) -> (https://github.com/dotnet/runtime)

**Comment by sba923** [comment]
[.Net Core issue opened](https://github.com/dotnet/runtime/issues/554)
