### ISSUE TITLE
CertificateProvider auto-imports PKI module many times

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#11241]
Attempting to use the PKI Module in Win10 using Preview 6.

I kind of expect a warning when the module is first loaded, with either import-module or via module autoload. But not on every operation:

See this graphic:
![2019-12-03_14-25-53](https://user-images.githubusercontent.com/3630329/70060628-d17e7180-15da-11ea-8c99-298d9d4c51e7.png)

In this session, I Set-Location (getting a warning), then did a get-ChildItem (and got a second warning message) then I did another Get-ChildItem (and got a THIRD warning. All the commands sent to the provider seem to generate a warning and I'd argue this is not a good user experience. 

# Steps to reproduce

```powershell
# 1. Open a PowerShell console window then type:
CD Cert:\
LS
LS .\Currentuser
```

# Expected behaviour
I would not expect the second two (and all subsequent) uses of cmdlets in a compatibility-imported module. I can live with the first warning, but the rest are a poor user experience.

# Actual behaviour
See the graphic above

# Environment data

```none
PS Cert:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
@doctordns In reviewing this I also noticed that any use of tab completion for any cmdlet seems to produce the warning at the moment the tab key is pressed, then completion options are shown after the warning message.  Did you notice that as well?

**Comment by SeeminglyScience** [comment]
Also writes warnings in VSCode's integrated console when intellisense hits the same commands.

**Comment by doctordns** [comment]
@theJasonHelmick  Yes in deed. It does get worse!

If I type:
```
CD Cert:
LS .\Curr<tab|>
```
I see this:

![2019-12-03_18-04-49](https://user-images.githubusercontent.com/3630329/70077080-051bc480-15f8-11ea-848d-6379a143bf57.png)

This can not be acceptable. :-(

**Comment by anmenaga** [comment]
Short version: This looks like a manifestation of a bug in `CertificateProvider` - loading `pki` module on every operation with a certificate path. Wincompat's warning just made this visible.

Long version: When creating new items or getting existing certificate items [CertificateProvider auto-imports `pki` module based on it's internal flag `_hasAttemptedToLoadPkiModule`](https://github.com/PowerShell/PowerShell/blob/2ee9df5a5d007167628db56454bb555b8f9932cd/src/Microsoft.PowerShell.Security/security/CertificateProvider.cs#L1099).
This `_hasAttemptedToLoadPkiModule` flag is set to `false` only once - [in CertificateProvider's constructor](https://github.com/PowerShell/PowerShell/blob/2ee9df5a5d007167628db56454bb555b8f9932cd/src/Microsoft.PowerShell.Security/security/CertificateProvider.cs#L517).
However, `SessionStateInternal.GetProviderInstance` simply creates a new instance of the provider every time, therefore resetting `_hasAttemptedToLoadPkiModule` flag which subsequently causes `pki` module to be re-imported again.

Here is the call stack that resets the `_hasAttemptedToLoadPkiModule` flag during `PS Cert:\> ls` call:
```
Microsoft.PowerShell.Commands.CertificateProvider.CertificateProvider() Line 517
System.RuntimeType.CreateInstanceDefaultCtor(bool publicOnly, bool skipCheckThis, bool fillCache, bool wrapExceptions)
System.Activator.CreateInstance(System.Type type, bool nonPublic, bool wrapExceptions)
System.Management.Automation.ProviderInfo.CreateInstance() Line 571
System.Management.Automation.SessionStateInternal.GetProviderInstance(System.Management.Automation.ProviderInfo provider) Line 284
System.Management.Automation.SessionStateInternal.GetContainerProviderInstance(System.Management.Automation.ProviderInfo provider) Line 604
System.Management.Automation.SessionStateInternal.GetChildItems(string path, bool recurse, uint depth, System.Management.Automation.CmdletProviderContext context) Line 1491
System.Management.Automation.ChildItemCmdletProviderIntrinsics.Get(string path, bool recurse, uint depth, System.Management.Automation.CmdletProviderContext context) Line 278
Microsoft.PowerShell.Commands.GetChildItemCommand.ProcessRecord() Line 318
```

**Comment by anmenaga** [comment]
On a side note, a single `PS Cert:\> Get-ChildItem` call ends up invoking [CertificateProvider constructor](https://github.com/PowerShell/PowerShell/blob/2ee9df5a5d007167628db56454bb555b8f9932cd/src/Microsoft.PowerShell.Security/security/CertificateProvider.cs#L589) 19 (!) times at various stages.

**Comment by doctordns** [comment]
@anmenaga - thanks for this. 

What does this mean for the PKI module? With this P/'R, will these commands work?? 

And will the CERT: provider work properly (as in act the same as in Windows PowerShell).

**Comment by jhoneill** [comment]
> @doctordns In reviewing this I also noticed that any use of tab completion for any cmdlet (not parameters) seems to produce the warning at the moment the tab key is pressed, then completion options are shown after the warning message.

I've been seeing this with particular module I have been working with (or I might say has been working against _me_)  dynamic parameters seem to be expanded as part of get-command and the tab completion seems to cause the dynamicParam code to run.  I found if I set $verbosePrefernce to Continue, tab expanding a command generated hundreds of lines of verbose output because the module in question had 60+ dynamic params, each of which did significant work. 
I suspect something similar is going on here.

**Comment by iSazonov** [comment]
> On a side note, a single PS Cert:\> Get-ChildItem call ends up invoking CertificateProvider constructor 19 (!) times at various stages.

I guess it is in LocationGlobber. It unify entry points to providers but this causes performance problems. It calls helper methods repeatedly many times. We have a tracking issue for FileSystem provider v2 and looking this I think we needs to change design and make entry points in base provider class to preserve unification and get high performance.

**Comment by anmenaga** [comment]
@doctordns #11259 will remove excessive warnings that you're observing. Functionality-wise commands of PKI module will continue to behave like they currently are. If they support serialization - they should work fine.

This issue is good for tracking a multi-import of PKI module bug in `CertificateProvider`/`LocationGlobber` boundary.

**Comment by doctordns** [comment]
This issue appears to have gone away by RC1. IT now works as expected.
