### ISSUE TITLE
Text background color extends to whole line if wrapped

### ISSUE THREAD

**Issue by heaths** [PowerShell/PowerShell#11267]
# Steps to reproduce

The screenshot below is using my `$prompt` function and supporting functions from https://github.com/heaths/profile. The following function should approximate this, though:

```powershell
function global:prompt {
  "`e[0;38;5;15;48;5;5mPS`e[38;5;5;48;5;8m`u{e0b0} `e[38;5;15m$PWD `e[0;38;5;8m`u{e0b0}`e[0m "
}
```

1. Set the global prompt function as above.
2. pushd into deep directories like so:

```powershell
pushd $env:TEMP
mkdir (new-guid) | pushd
```

That said, this approximate function had sporadic results compared with the screenshot below. Sometimes the expected behavior is what I saw, while others it was the actual behavior; however, when I got the expected behavior, resizing the window caused other problems as shown directly below:

![image](https://user-images.githubusercontent.com/1532486/70224521-400a1f00-1702-11ea-9e7e-8d346e49a812.png)

Notice how the beginning of the prompts shifts by increasingly deeper margins.

# Expected behavior

The line background color stops at the end of the text where it should (see cmd.exe example in screenshot below, which uses a similar vterm sequence as my `$prompt`).

This problem also does not occur in the integrated terminal for VSCode:

![image](https://user-images.githubusercontent.com/1532486/70222551-126fa680-16ff-11ea-97e8-d1deb46caff1.png)

# Actual behavior

The line background color extends to the window width. If I resize the window - e.g. shrink by 1 character width then move back to original width - this extra background line is cleared showing what I would otherwise expect (like in the cmd.exe you see in the following screenshot):

![image](https://user-images.githubusercontent.com/1532486/70221580-7abd8880-16fd-11ea-9a5d-52766e39616c.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Font: Cascadia Code PL

**Comment by iSazonov** [comment]
@heaths Please repo on latest PowerShell 7.0 build.

**Comment by rkeithhill** [comment]
It repros on PS 7 Preview.6:

![image](https://user-images.githubusercontent.com/5177512/70258365-59828980-1749-11ea-837f-43afc0536f67.png)

Also this is a duplicate of #11226

**Comment by heaths** [comment]
Hmm, not happening for me on Win10 1903 with PS7p6 - not even the shifting "margins" when I run pwsh.exe 7-preview6 directly (did when I ran it from within pwsh 6, though I assume it's all the same conhost).

![image](https://user-images.githubusercontent.com/1532486/70262940-1ecd2100-174a-11ea-983a-aee92cea1fbf.png)

This appeared right even before I changed the window size.

**Comment by rkeithhill** [comment]
I see the same with conhost  - no issue.  But it does repro in Windows Terminal.

**Comment by heaths** [comment]
I was about ready to post that I wasn't seeing it in Terminal (latest preview) with 6 or 7 until I dumped my conhost version info (to compare with @rkeithhill) and it happened, as shown below. In this case, I hadn't resized the window/buffer before or after prompt rendering:

![image](https://user-images.githubusercontent.com/1532486/70263989-63f25280-174c-11ea-9d30-34bc00bc88fa.png)

**Comment by rkeithhill** [comment]
@heaths Are you using `posh-git`?  If so, what version?

**Comment by rkeithhill** [comment]
@heaths BTW, I updated to Windows Terminal 0.7.3382.0 today and now I'm not seeing this. How about you?

**Comment by heaths** [comment]
Yep, in the same way I did before (though, I admit I forgot to first select the Path then VersionInfo):

![image](https://user-images.githubusercontent.com/1532486/70368729-888d1e00-1863-11ea-8c25-ca25362ea461.png)

No, not using posh-git. I wrote my own: <https://github.com/heaths/profile>. It doesn't run git.exe which time `$prompt` is invoked.

**Comment by iSazonov** [comment]
Can you remove PSReadline and try?

**Comment by heaths** [comment]
It's sporadic, but still repros with PSReadline removed:

![image](https://user-images.githubusercontent.com/1532486/70373018-39fb7600-189b-11ea-82f4-fe1ed09a535d.png)

**Comment by tillig** [comment]
I think I'm running into this using oh-my-posh and seeing line wrapping issues exactly like this: JanDeDobbeleer/oh-my-posh3#65

For me, I primarily see it when the prompt causes the window to scroll. When the window doesn't scroll, it renders correctly. See below screenshot - first prompt did not cause the window to scroll; second prompt after a directory listing caused scrolling and the background fills the line.

<img width="1202" alt="Continued color block at end of screen" src="https://user-images.githubusercontent.com/1156571/96320720-08c5f900-0fc8-11eb-9868-b88773f36a86.png">

**Comment by rkeithhill** [comment]
@DHowett This isn't a Windows Terminal issue but would you happen to know what's going on here?

**Comment by DHowett** [comment]
Oh yeah, this is definitely microsoft/terminal#32. It's been an issue in the console host since at least RS2

**Comment by DHowett** [comment]
It also happens in compliant terminal emulators when a newline is emitted at the bottom of the screen with a background color active.

The new row is given the currently active attributes, by design.

**Comment by heaths** [comment]
Could you clarify "current active attributes"? At least in my prompt - and I suspect others, since the commands seem to use a dark background with light foreground - I'm resetting the attributes, e.g:

```powershell
"`e[0m"
```
