### ISSUE TITLE
PATH is not set correctly after installation of 7.0-Preview.6

### ISSUE THREAD

**Issue by jeroenlandheer** [PowerShell/PowerShell#11269]
# Steps to reproduce

Install PowerShell using the MSI (x64) installer

# Expected behavior

Running `pwsh` should start Powershell.

# Actual behavior

`'pwsh' is not recognized as an internal or external command, operable program or batch file.`

# Environment data

Windows Server 2019 (1809, build 17763)
PowerShell v7.0-preview.6

`PATH` is set to `C:\Program Files\PowerShell\7-preview\preview` while it is installed in `C:\Program Files\PowerShell\7-preview`... that's one `preview` too many.

**Comment by vexx32** [comment]
@jeroenlandheer which operating system are you using, and which version of PowerShell did you try to install? 🙂

**Comment by jeroenlandheer** [comment]
@vexx32 
OS: MS Windows Server 2019 (v1809, build 17763)
Version:  version 7.0-preview.6

**Comment by daxian-dbw** [comment]
@jeroenlandheer For previews of pwsh, you are supposed to use `pwsh-preview` to start the shell, not `pwsh`. There should be a `pwsh-preview.cmd` file in `C:\Program Files\PowerShell\7-preview\preview`.
