### ISSUE TITLE
Get-Help -Online fails for Commands in LocalAccounts module - Preview 6

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#11268]
If you use the command:

```powershell
Get-Help -Online <cmdletname>
```
You get the help text at Docs.Microsoft.com. For example, if I Get-Help for Get-Help, I am redirected to 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-help?view=powershell-7 (i.e. the culture aware help location! for that cmdlet). 

However for the cmdlets in the Microsoft.PowerShell.LocalAccounts module, attempting to Get-Help -online results in being directed to https://www.microsoft.com/en-gb/?ref=go1. 

It appears that the necessary help files are not in Docs.Microsoft.Com's help system. 

# Steps to reproduce

```powershell
Get-Help -Online -Name 'Get-Help'
```

# Expected behaviour
I expected to be sent to a PowerShell 7 related help page.

# Actual behaviour

Sent to https://www.microsoft.com/en-gb/?ref=go

# Environment data

```none
PS C:\foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.19033
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0-preview.6}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
NB.: I tested this in 7.0.0-daily.20191204 and it fails in the same way. FWIW.

**Comment by iSazonov** [comment]
LocalAccounts module was removed from PowerShell 6/7 so it is expected that Get-Help for cmdlets from the module doesn't work.

**Comment by doctordns** [comment]
Yes and no.
I can (and do) import this module and use the commands natively. To the user, it is a module of commands I can access from PowerShell 7. It appears to be being loaded using the new compatibility logic and _acts_ like a native module. 

From a help perspective, this module does not seem to exist (for PWSH7) yet its commands do certainly exist.  I would argue that the user is expecting to be able to Get-Help on a directly available command. Even though you may not ship it, it is a module directly accessible from what you do ship thus at least point to the 5.1 help!

**Comment by iSazonov** [comment]
The compatibility system is intended only to facilitate the transition period to PowerShell 7.
I think it’s not worth the effort, especially since Help System in PowerShell Core will be replaced with new version soon.
/cc @anmenaga

**Comment by doctordns** [comment]
So why can't the relevant cmdlets be coded so as to point to the 5.1 content to give a more consistent user experience?

**Comment by vexx32** [comment]
@doctordns typically the online help link is defined by the module itself; I wouldn't think that PS7 would make a difference here, you should be seeing the same behaviour running the `Get-Help -Online` command from 5.1 for these commands unless there's something I'm missing.

The module itself would need to be updated either way. @iSazonov do you know if that module is in this repo, or if it's managed in a separate repo?

**Comment by iSazonov** [comment]
The cmdlets present only in remote session and Help System see only proxies. If Help System don't see HelpUrl in the proxies I think it’s not worth the effort to enhance it,

> do you know if that module is in this repo, or if it's managed in a separate repo?

The module was removed from the repo for compliance reasons. I started a work on new module #9926 and related RFC but there is still a small progress.

**Comment by troymoore** [comment]
Will listen

**Comment by troymoore** [comment]
Lol deff not system was installed on wrong device. Benefit of doubt I'm
just really catching the system

**Comment by troymoore** [comment]
Module is in another repo

**Comment by troymoore** [comment]
My apologies it took for me to have two modules in my hand and take time
out to study the design of the program

**Comment by troymoore** [comment]
Communicate with power shell through text me commands to start process with
the building of using basics
