### ISSUE TITLE
Mode memeber doesn't show permissions in macOS

### ISSUE THREAD

**Issue by r-darwish** [PowerShell/PowerShell#11263]
# Steps to reproduce
Run `Get-ChildItem` in macOS in a directory containing files and directories

# Expected behavior
I understand that "mode" means something different in Windows then the Unix definition. However, for a Unix user using Powershell the current behavior is somewhat confusing. I'm not sure what's the proper solution here. Maybe add a "permission" column for Unix permissions?

# Actual behavior
The mode column only shows `d` for directories. Here's the output of both `Get-ChildItem` and the system's built-in's `/bin/ls`
```none
PS /tmp/testing> ls -l
total 0
drwxr-xr-x 2 rodarwis wheel 64 Dec  4 13:30 dir
-rw-r--r-- 1 rodarwis wheel  0 Dec  4 13:30 file
PS /tmp/testing> Get-ChildItem


    Directory: /tmp/testing

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        12/04/2019    13:30                dir
------        12/04/2019    13:30              0 file

PS /tmp/testing>
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Funny you should ask! If you grab the latest v7 preview you'll note an experimental feature has been added to retrieve this information (many thanks to @JamesWTruher for that one, it's very handy!)

If for whatever reason it isn't enabled (in most cases it will be enabled by default in preview versions) you can enable it with:
```powershell
Enable-ExperimentalFeature -Name PSUnixFileStat
```

Feedback on experimental features is always welcome, as well. 😊

**Comment by r-darwish** [comment]
Seems like what I was looking for. Thanks!
