### ISSUE TITLE
Start-Process in new window does not work on macOS

### ISSUE THREAD

**Issue by DaRosenberg** [PowerShell/PowerShell#11275]
The [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7) for `Start-Process` mentions that executing the child process in a separate window is the default behavior, and the `-NoNewWindow` parameter exists to prevent it. Indeed, this is how it behaves on Windows.

The same documentation also contains a note that on Linux, the `-UseNewEnvironment` should be used to achieve the same behavior. There is no explicit mention of macOS.

I'm building a cross-platform solution where a requirement is for the new window behavior to be consistent across both Windows and macOS, but based on my testing so far, the child process is always executed within the current terminal window on macOS.

# Steps to reproduce

One of the following:

```powershell
Start-Process pwsh-preview -WorkingDirectory ~/Temp -ArgumentList "-File .\SomeScript.ps1" -Wait
Start-Process pwsh-preview -WorkingDirectory ~/Temp -ArgumentList "-File .\SomeScript.ps1" -UseNewEnvironment -Wait
```

# Expected behavior

```none
The external script SomeScript.ps1 should be executed in a new terminal window.
```

# Actual behavior

```none
The external script SomeScript.ps1 is instead executed in the same terminal window.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I think it is docs issue
From https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=netcore-3.0
> .NET Core does not support creating windows directly on Unix-like platforms, including macOS and Linux. This property is ignored on such platforms.
