### ISSUE TITLE
Cannot load AzureRM module in C#

### ISSUE THREAD

**Issue by xTeKillax** [PowerShell/PowerShell#11277]
Hello, im using PowerShell.SDK and PowerShell.Commands.Diagnostics to call a powershell script which is supposed to reboot a webapp on Azure.
However, I cannot get it to load AzureRM.Websites module to perform the task.

# Steps to reproduce

```
InitialSessionState initialState = InitialSessionState.CreateDefault();
            initialState.ImportPSModule(new string[]
            {
                "PATH_TO_AzureRM.psm1" //tried also AzureRM.Websites or AzureRM.psd1
});
Runspace runspace = RunspaceFactory.CreateRunspace(initialState);
            runspace.Open();
PowerShell powerShellInstance = PowerShell.Create();
            powerShellInstance.Runspace = runspace;

            string initializationScript = "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted";
            powerShellInstance.AddScript(initializationScript);
            powerShellInstance.Invoke();

            //Here I use AddScript/Invoke/AddCommand/Invoke to launch a powershell script which try to call the Restart-AzureRmWebApp method.
```

# Expected behavior

```
The Restart-AzureRmWebApp is recognized and executed
```

# Actual behavior

```
Exception Type: System.Management.Automation.CommandNotFoundException
Exception Message: The term 'Restart-AzureRmWebApp' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

Is there something im missing ?
It seems like the ImportPSModule does nothing

**Comment by iSazonov** [comment]
@xTeKillax You should use Az module https://azure.microsoft.com/en-in/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/

**Comment by xTeKillax** [comment]
Hello @iSazonov, thanks for your reply but migrating to Az module didn't change a thing, now I only get the "The term 'Restart-AzWebApp' is not recognized as the name of a cmdlet" error.

**Comment by iSazonov** [comment]
I don't know why ImportPSModule() does not work but you could use AddCommand or AddScript methods.

**Comment by xTeKillax** [comment]
It seems to work (by the way i used ImportPSModuleFromPath which suits my need better) but the Azure PowerShell seems to struggle.

Im not sure, but it may be due to the PowerShell Version in the library used in C#.
My coworker found out the PS version is 2.0, while Azure PowerShell Module require at least PowerShell 5.1

Is there any work around ?

**Comment by iSazonov** [comment]
> My coworker found out the PS version is 2.0

I wonder how he found this. What is PowerShell SDK version you use?

**Comment by xTeKillax** [comment]
Heard something about the Get-Host cmdlet for the version.

Im running on the latest one, 7.0.0-preview-6 on .NET Core 3.1 but we also tried with preview 3 and the latest stable (6.3.2 if im not mistaken).

For now, Im running a StartProcess powershell.exe -ArgumentLists 'xxxxxxxxxx' as a workaround, but all the benefits of using the SDK are lost

**Comment by iSazonov** [comment]
@xTeKillax I think you get more help and more fast on (MSFT) developer forums. In the repo we can only discuss and fix issues in PowerShell engine.

On top of the page you can see "Used by" button. There you could find over dozen examples of using PowerShell Core SDK.
