### ISSUE TITLE
Package dependency issue for Debian Buster

### ISSUE THREAD

**Issue by mbearup** [PowerShell/PowerShell#11279]
A version of powershell7 for Debian 10 (buster) is available [here](http://packages.microsoft.com/repos/microsoft-debian-buster-prod/pool/main/p/powershell-preview/). However, it depends on the Debian 9 (Stretch) versions of libicu and libssl (57 vs 63, and 1.0.2 vs 1.1 respectively). In its current state, this is not installable without pulling in old versions of the packages from Stretch, which is not recommended. Will you be building a version that depends on the newer versions of these packages?

**Comment by iSazonov** [comment]
It was fixed in #11236
Also we need you feedback here https://github.com/PowerShell/PowerShell/issues/11187#issuecomment-562714872
