### ISSUE TITLE
Error message text background is not black when $Host.PrivateData.ErrorBackgroundColor is set to "Black"

### ISSUE THREAD

**Issue by Yllzarith** [PowerShell/PowerShell#11271]
I can't figure out how to get error message text to have a black background as I enjoy in Windows PowerShell 5.1.  Here is a side-by-side comparison:
![image](https://user-images.githubusercontent.com/21979114/70257528-71add500-1758-11ea-9e7b-4cef0f69086b.png)

# Steps to reproduce

Produce an error in PowerShell 6.2.3.

# Expected behavior

Error message background colour should be black as indicated by $Host.PrivateData.ErrorBackgroundColor value.

# Actual behavior

Error message background colour is not black as expected according to $Host.PrivateData.ErrorBackgroundColor value.

# Environment data

```none
PS C:\Users\\[]> $PSVersionTable

PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\\[]> $Host.PrivateData

ErrorForegroundColor    : Red
ErrorBackgroundColor    : Black
WarningForegroundColor  : Yellow
WarningBackgroundColor  : Black
DebugForegroundColor    : Yellow
DebugBackgroundColor    : Black
VerboseForegroundColor  : Yellow
VerboseBackgroundColor  : Black
ProgressForegroundColor : Yellow
ProgressBackgroundColor : DarkCyan
```

**Comment by vexx32** [comment]
You can use `Set-PSReadLineOption -Colors @{ Error = $Value }` where `$Value` is a string containing an ANSI escape sequence specifying both foreground and background colors.

See [here](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit) for documentation on ANSI escape sequences; you can use `` `e [` to begin an escape sequence (often denoted `ESC[` in ANSI documentation).

**Comment by SeeminglyScience** [comment]
@vexx32 that only applies to PSReadLine errors (and I believe the syntax error indicator you get without a custom prompt function).  The values in `$Host.PrivateData` determine the color of the various streams like `Error`.

**Comment by iSazonov** [comment]
Look also PowerShell 7.0 - this was improved.

**Comment by Yllzarith** [comment]
PowerShell 7 is a preview release.

**Comment by iSazonov** [comment]
It will be GA in next month.
