### ISSUE TITLE
Cannot add Microsoft.Office.Interop assemblies in PowerShell 7 Preview

### ISSUE THREAD

**Issue by wi-fr** [PowerShell/PowerShell#11281]
PowerShell 7 Preview looks for the Interop assembly in the current location
 
# Steps to reproduce

Add-Type -AssemblyName "Microsoft.Office.Interop.Outlook" -PassThru

# Expected behavior

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    _IRecipientControl
True     False    _DRecipientControl
True     False    _DRecipientControlEvents
True     False    _RecipientControlClass                   System.__ComObject
...

# Actual behavior

Add-Type: Cannot find path 'C:\Users\...\Documents\WindowsPowerShell\Scripts\Microsoft.Office.Interop.Outlook.dll' because it does not exist.

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
I guess Microsoft.Office.Interop.Outlook is .Net Framework assembly, not .Net Core.

You could use COM to get Outlook functionality.

**Comment by SeeminglyScience** [comment]
@wi-fr 

That assembly is registered into the GAC, which .NET Core does look at for assembly resolution.

You need to specify the full path to the assembly, either one included with your script/module, or the full path to the one in the GAC:

```powershell
Add-Type -Path $env:WINDIR\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll
Add-Type -Path $env:WINDIR\assembly\GAC_MSIL\Microsoft.Office.Interop.Outlook\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Outlook.dll
```

The safest version is definitely including your own copy from nuget.
