### ISSUE TITLE
ConvertTo-HTML incorrectly converting values when 1st column header has wildcard

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/PowerShell#11287]
# Steps to reproduce

1. Unpack [Test.zip](https://github.com/PowerShell/PowerShell/files/3935105/Test.zip)
2. There's Test.xml in it
3. Content looks like this:

```xml
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Management.Automation.PSCustomObject</T>
      <T>System.Object</T>
    </TN>
    <MS>
      <S N="Products and services">Virtual Machines</S>
      <S N="*Non-Regional">Blank</S>
      <S N="North Europe">Good</S>
      <S N="West Europe">Good</S>
      <S N="France Central">Good</S>
      <S N="France South">Good</S>
      <S N="UK West">Good</S>
      <S N="UK South">Good</S>
      <S N="Switzerland North">Good</S>
      <S N="Switzerland West">Good</S>
      <S N="Norway East">Good</S>
      <S N="Norway West">Good</S>
      <S N="‡Germany North">Good</S>
      <S N="‡Germany West Central">Good</S>
      <S N="*Germany Non-Regional">Blank</S>
      <S N="Germany Central">Good</S>
      <S N="Germany Northeast">Good</S>
    </MS>
  </Obj>
</Objs>
```
4. Execute

```powershell
$Import = Import-Clixml -LiteralPath $PSScriptRoot\Test.xml
$Import | Format-Table -Autosize
$Import | ConvertTo-html -Fragment
```

![image](https://user-images.githubusercontent.com/15063294/70375484-8c21b300-18fe-11ea-8ea7-f44ac7b45aca.png)

# Expected behavior

Proper HTML with wildcard not affecting values in 1st column.

# Environment data

Affected 5.1, 6.2.3 and 7.0.0-preview 6

```none
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

And 

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

and

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PrzemyslawKlys** [comment]
Simpler way to reproduce:

```powershell
$Test = [PSCustomObject] @{
    "Products and services" = "Virtual Machines"
    "*Non-Regional"         = "Blank"
    "North Europe"          = "Good"
    "West Europe"           = "Good"
    "France Central"        = "Good"
    "France South"          = "Good"
    "UK West"               = "Good"
    "UK South"              = "Good"
    "Switzerland North"     = "Good"
    "Switzerland West"      = "Good"
    "Norway East"           = "Good"
    "Norway West"           = "Good"
    "‡Germany North"        = "Good"
    "‡Germany West Central" = "Good"
    "*Germany Non-Regional" = "Blank"
    "Germany Central"       = "Good"
    "Germany Northeast"     = "Good"
}
$Test | ConvertTo-Html -Fragment
```

**Comment by iSazonov** [comment]
Yes, the properties are being processed as Regex.
So it is not surprise that the second "Blank" comes from "*Germany Non-Regional" property.
Root of the issue is that the properties have the same nature as arguments in -Property parameter - it is PSPropertyExpression.
As result property's names can be executable script. In the case I think we should not escape the calculated property name (and delegate this to the script - we cannot know the author’s intentions
). If the property name is not script but simple literal string we could safely escape it (in InitializeResolvedNameMshParameters() method).

/cc @mklement0 What do you think?

**Comment by mklement0** [comment]
My understanding of the internals is superficial, but it definitely sounds like the wrong thing to do to subject the actual property names of the input objects to another round of interpretation as wildcard expression (not regexes) when the property _values_ are retrieved.

To provide an even simpler repro:

```powershell
PS> [pscustomobject] @{ '*b'=1; 'a*b' = 2 } | convertto-html -fragment | sls tr

<tr><th>*b</th><th>a*b</th></tr>
<tr><td>1, 2</td><td>2</td></tr>  # !! Note the `1, 2` in column `*b`
```

If I understand correctly, the property _names_  - `*b`, `a*b` - are initially derived from the first input object, and then mistakenly interpreted as wildcard expressions when it comes to extracting the property _values_, so that wildcard expression `*b` extracts the values from _both_ properties, given that both property names match (whereas `a*b` as a wildcard expression only matches `a*b` itself).

**Comment by iSazonov** [comment]
> If I understand correctly

Correctly.

I referenced a code above where is two paths. My proposal add the fix only in one code path for strings and leave second one as-is (it is script expressions). Do you see any problems with the second one?

**Comment by mklement0** [comment]
I think that should be fine - the script-block case should never be hit if the property names are derived from the input objects. I assume you're aware of it, but just to spell it out: You will have to distinguish between property names derived from the input object (literals) and string `-Property` arguments (wildcards).

The whole approach sounds convoluted and inefficient, though, but I'm not familiar enough with the code to judge if there's a good reason for that.

**Comment by mklement0** [comment]
There is an additional problem, and it presumably affects all cmdlets that use `PSPropertyExpression`:

In the case where you want a `-Property` string argument to be treated as a literal rather than as a wildcard, the usual embedded `` ` ``-escaping doesn't work:

```powershell
# !! The following two commands do NOT select property '*b' correctly:
@{ '*b'=1; 'a*b' = 2 } | ConvertTo-Html '`*b'
@{ '*b'=1; 'a*b' = 2 } | Select-Object '`*b'
```

**Comment by iSazonov** [comment]
Yes. I don't know can we fix this in generic way. Perhaps @bpayette could suggest. 
- can we always escape if PSPropertyExpression is simple string?
- can we always escape if PSPropertyExpression is a script
