### ISSUE TITLE
Please add little bit padding on sides.

### ISSUE THREAD

**Issue by iftkharhussain** [PowerShell/PowerShell#11299]
Hi,
First of All thanks for all of you who contributed to make it Perfect cmd. 
I have a little suggestion for its design perspective, can you please add a little bit padding on sides, currently it is very awkward.
https://www.dropbox.com/s/4bnq0q0hcljrl2d/pwsh_L0yFw0n0ew.png?dl=0

**Comment by SteveL-MSFT** [comment]
The screenshot you link shows the Mode column, are you asking to have more whitespace for that?  Would help if you could say what you want it to look like compared to what it looks like today.

**Comment by rkeithhill** [comment]
If you can use the [Windows Terminal preview](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701), it allows you to adjust the padding. By default, I think the padding is 8 pixels:

![image](https://user-images.githubusercontent.com/5177512/70471774-1e56c200-1a8b-11ea-854b-b7ef31887c4a.png)

Here I have adjusted it up to 15 pixels:

![image](https://user-images.githubusercontent.com/5177512/70471904-5bbb4f80-1a8b-11ea-8bdd-f013fecd2814.png)

**Comment by troymoore** [comment]
Timetomakebetterobsevihaveundercont

**Comment by iftkharhussain** [comment]
Hi @SteveL-MSFT , 
Please check it, this is what i want to say.
https://www.dropbox.com/s/b9w6vfhuy540r3j/explorer_gaKQUQsWTF.png?dl=0

**Comment by SteveL-MSFT** [comment]
@iftkharhussain I see, so you would like some whitespace on the left side of the table?  The downside will be using up one character that could be used for wider tables that already truncate columns.
