### ISSUE TITLE
Debian Buster package not install

### ISSUE THREAD

**Issue by joaoemanuel1981** [PowerShell/PowerShell#11296]
Hi, first sorry for horrible english, i try to install Debian Buster package, but him not install.
Its because the package needs libssl1.0.2 and libicu57, but today in Debian Burster have libicu63 and libssl1.1. Please is possible to recompile Debian Burster package using libicu63 and libssl1.1 instead libssl1.0.2 and libicu57? Thanks you very much.

**Comment by iSazonov** [comment]
@joaoemanuel1981 Thanks for your report!
The issue was fixed in #11236.
