### ISSUE TITLE
Add setting to powershell.config.json to disable WinPS module loading

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#11309]
# Summary of the new feature/enhancement

In PS7 we introduced the equivalent of WindowsCompatibility module in the engine (although using Jobs remoting instead of WinRM remoting).  This is enabled by default.  We should have a way to disable this if it causes problems for users.  Current proposal is to add a setting in powershell.config.json.

cc @anmenaga

**Comment by vexx32** [comment]
Yeah, this should be configurable, but isn't the config.json a machine-wide setting? We should probably allow users to set this on a more granular basis if we can.

Also, do we have a cmdlet that can alter settings other than experimental features in the config.json currently?

**Comment by SteveL-MSFT** [comment]
config.json is both user and machine scoped.  We could add cmdlets for this to make it easier for users.

**Comment by iSazonov** [comment]
It is important feature for early adoption and we also could add a message (link to docs) in startup welcome message.
