### ISSUE TITLE
Update HelpInfoUri for all modules for v7 release

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#11322]
Need to create new FWLinks for `Update-Help` for v7 for the following modules:

- CimCmdlets
- Microsoft.PowerShell.Archive
- Microsoft.PowerShell.Core
- Microsoft.PowerShell.Diagnostics
- Microsoft.PowerShell.Host
- Microsoft.PowerShell.Management
- Microsoft.PowerShell.Security
- Microsoft.PowerShell.Utility
- Microsoft.WSMan.Management
- PackageManagement
- PowerShellGet
- PSDesiredStateConfiguration
- PSDiagnostics
- PSReadLine
- ThreadJob

NOTE: ThreadJob has never had an FWLink. We need this created for both v6 and v7.

Need to know new URLs so we can update the module pages in the docs.

**Comment by adityapatwardhan** [comment]
The current FWLink for PSDesiredStateConfiguration goes to download.microsoft.com. Do we own the content?

**Comment by adityapatwardhan** [comment]
https://github.com/PowerShell/PowerShell/pull/11389

**Comment by iSazonov** [comment]
@sdwheeler #11389 was merged. Please update status of the issue.

**Comment by sdwheeler** [comment]
@adityapatwardhan All HelpInfoURI FWLinks created prior PSv6 point to download.microsoft.com. We don't have access to update the content on the download center. That is why we use Azure blob store now.

#11389 updates the following modules

- CimCmdlets
- Microsoft.PowerShell.Core
- Microsoft.PowerShell.Diagnostics
- Microsoft.PowerShell.Host
- Microsoft.PowerShell.Management
- Microsoft.PowerShell.Security
- Microsoft.PowerShell.Utility
- Microsoft.WSMan.Management
- PSDiagnostics

The remaining modules are in other repos

- Microsoft.PowerShell.Archive
- PackageManagement
- PowerShellGet
- PSDesiredStateConfiguration
- PSReadLine
- ThreadJob

How do you want to track these?

**Comment by iSazonov** [comment]
These are external but somewhere these should be tracked. :-)

**Comment by TravisEz13** [comment]
@iSazonov  Why was this assigned to a release?

**Comment by iSazonov** [comment]
@TravisEz13 There was nothing more suitable, but it should not have been forgotten by accident.

**Comment by adityapatwardhan** [comment]
Microsoft.PowerShell.Archive - https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/83
PackageManagement - https://github.com/OneGet/oneget/pull/482
PSReadLine - https://github.com/PowerShell/PSReadLine/pull/1251
ThreadJob - https://github.com/PaulHigin/PSThreadJob/pull/50

**Comment by unnity** [comment]
After upgrading to PS 7, Update-Help leads to below error

Update-Help: Failed to update Help for the module(s) 'PSDesiredStateConfiguration, ThreadJob' with UI culture(s) {en-GB} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US

On another machine fails for UI culture en-US as well

Is this related to this or requires a separate issue to be raised

**Comment by vexx32** [comment]
That definitely sounds related. Please fix those! 💖

**Comment by jakobnotseth** [comment]
This task seems to be missing some modules:
> Failed to update Help for the module(s) '**PSDesiredStateConfiguration, ThreadJob, WindowsUpdateProvider**' with UI culture(s) {nb-NO} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
> Update-Help: Failed to update Help for the module(s) '**ConfigDefender, Defender, Microsoft.PowerShell.Operation.Validation, UEV, Whea, WindowsDeveloperLicense**' with UI culture(s) {nb-NO} : A Help URI cannot contain more than 10 redirections.
> Failed to update Help for the module(s) '**PSDesiredStateConfiguration, ThreadJob, WindowsUpdateProvider**' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
> Failed to update Help for the module(s) '**ConfigDefender, Defender, Microsoft.PowerShell.Operation.Validation, UEV, Whea, WindowsDeveloperLicense**' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections.

**Comment by TravisEz13** [comment]
cc @PaulHigin

**Comment by sdwheeler** [comment]
We have help but there may be a problem with the file naming that prevents Update-Help from working for ThreadJob. This will be fixed in the new publishing pipeline.

**Comment by sdwheeler** [comment]
The ThreadJob help will be fixed when we publish the new build of the module. This should be fixed in 7.1 GA. PSDesiredStateConfiguration help works in Windows. There is an issue with this on Ubuntu 18.04.

See related:
- https://github.com/PowerShell/PowerShell/issues/12257
- https://github.com/PowerShell/PowerShell/issues/10593

I think this issue can be closed.
