### ISSUE TITLE
Hosted powershell has no "ref" folder

### ISSUE THREAD

**Issue by Hvid** [PowerShell/PowerShell#11320]
I created a hosted PowerShell application in c# with .NET core 3.0
This application executes a PowerShell script using the "powershell-yaml" module. It apparently needs access to the .NET Core assemblies.

I get the files published with this in my project file:

```
<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
```
This property ensures that a "refs" directory is published containing all reference assemblies.

PowerShell though, looks for a "ref" directory:
https://github.com/PowerShell/PowerShell/blob/3923ca172854b8f3b00dcd02b0f1829917758f10/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L614

# Steps to reproduce

Publish a c# application referencing System.Management.Automation.dll and have it execute a PowerShell script using the powershell-yaml module.

# Expected behavior

I would expect it to look for the "refs" folder with is published when enabling the CopyRefAssembliesToPublishDirectory property.

# Actual behavior

It looks for the reference assemblies in "ref", which does not exist.

# Environment data
````json
{
  "PSVersion": {
    "Major": 6,
    "Minor": 2,
    "Patch": 3,
    "PreReleaseLabel": null,
    "BuildLabel": null
  },
  "PSRemotingProtocolVersion": {
    "Major": 2,
    "Minor": 3,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "SerializationVersion": {
    "Major": 1,
    "Minor": 1,
    "Build": 0,
    "Revision": 1,
    "MajorRevision": 0,
    "MinorRevision": 1
  },
  "WSManStackVersion": {
    "Major": 3,
    "Minor": 0,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "Platform": "Win32NT",
  "OS": "Microsoft Windows 10.0.17763",
  "GitCommitId": "6.2.3",
  "PSCompatibleVersions": [
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "5.0",
    "5.1.10032.0",
    "6.2.3"
  ],
  "PSEdition": "Core"
}
````

**Comment by iSazonov** [comment]
@Hvid  I hope it was fixed in https://github.com/PowerShell/PowerShell/pull/10587.

**Comment by vexx32** [comment]
Nope:
https://github.com/PowerShell/PowerShell/pull/10587/files#diff-6259d5c5e88707b8b7cdfb1428af6f6aR614

Still using `ref` and not `refs`.

**Comment by Hvid** [comment]
I just tried updating the project to .NET Core 3.1 and Microsoft.PowerShell.SDK 7.0.0-preview.6 and it actually works, but because the "ref" folder is now published instead of a "refs". This is with "CopyRefAssembliesToPublishDirectory" disabled.

**Comment by iSazonov** [comment]
Switching to refs would huge breaking change.

Maybe @daxian-dbw  add more info.

**Comment by Hvid** [comment]
Seems it was fixed in .NET Core 3.1, as they're now publishing "ref" instead of "refs".
