### ISSUE TITLE
MSIX Installs to different locations on each new version

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#11329]
The install path for the MSIX version from the private preview from the Microsoft store changes between versions, making subsequent use in VSCode & Win Terminal, which require the paths be hardcoded in settings files, another manual user update task.

This ideally should keep the same path on update - however this may a `feature` of the store based installs

**Comment by DHowett-MSFT** [comment]
As a general note, Terminal doesn't require that paths be hardcoded. It will use `%PATH%` for spawning shells, and will launch the store version of powershell if its execution alias shows up earlier in `%PATH%` than any other version.

There is also a version-agnostic alias at `%LOCALAPPDATA%\Microsoft\WindowsApps\pwsh.exe` and a _preview/non-preview_-agnostic alias at `%LOCALAPPDATA%\Microsoft\WindowsApps\Microsoft.PowerShellPreview_8wekyb3d8bbwe\pwsh.exe`.

**Comment by kilasuit** [comment]
The above provides a suitable and easily workable work around
