### ISSUE TITLE
Cannot unregister backup vault container : type "AzureVM"

### ISSUE THREAD

**Issue by bufferwolfa** [PowerShell/PowerShell#11346]
# Steps to reproduce
![prob3](https://user-images.githubusercontent.com/13571179/70859979-35dff000-1f4e-11ea-808c-d26c331c88b3.PNG)
![prob2](https://user-images.githubusercontent.com/13571179/70859920-42177d80-1f4d-11ea-86fa-080c6fd3b3a6.PNG)
![prob1](https://user-images.githubusercontent.com/13571179/70859921-480d5e80-1f4d-11ea-8001-126bb5df50af.PNG)

# Expected behavior
No Error and show success report.

# Environment data
Run these commands in Azure Cloud Shell at  2019-12-15 3:10 pm +07:00 timezone

**Comment by vexx32** [comment]
Thanks for the report! 💖 

The Azure module is not maintained by the PowerShell team; you will want to file this issue in https://github.com/Azure/azure-powershell instead, I think. 🙂
