### ISSUE TITLE
Failed to get buffer

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11345]
I tried to capture the console buffer. An error has occurred

`GetBufferContents` feature is not valid

### Reference:

[Capture console screen](https://devblogs.microsoft.com/powershell/capture-console-screen/)

[Colorized capture of console screen in HTML and RTF.](https://devblogs.microsoft.com/powershell/colorized-capture-of-console-screen-in-html-and-rtf/)

----
<https://github.com/JFLarvoire/SysToolsLib/issues/25>

> Interesting issue: I had never tested any of my PowerShell scripts in PS Core for Linux.
> Juste in case, I first checked the script with PS Core 7.0.0-preview.6 in Windows: It works fine, both in the old Console, and in the new Terminal.
> Then indeed with PS Core for Linux in an LXSS bash window, I get the same exception that you got.
> But I'm afraid this is not a problem in Get-Console.ps1, but rather it's a problem in PS core for Linux, or more likely in .NET Core for Linux: Obviously it's still missing APIs compared to the Windows version.
> I think you should post this instead in [PS Core issues](https://github.com/PowerShell/PowerShell/issues) or in [.NET Core issues](https://github.com/dotnet/core/issues).

**Comment by iSazonov** [comment]
@he852100 Please follow our issue pattern - you skip important parts in the report and it is not clear what is a scenario you mean and what is desired behavior you want to get.
