### ISSUE TITLE
Pipeline variable is updated way too many times

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#11347]
When working with `-PipelineVariable` and variable breakpoints, I discovered that there are far too many updates to PipelineVariable happening.

If you review the reproduction scenario below, you'll see that pipeline variables are written to twice per object emitted from a pipeline, plus once for each additional pipeline statement beyond the first. Pipeline variables should be set once per object emitted, and cleared using a fast, internal method that doesn't result all of the extra work that is associated with setting a variable.

The main culprits seems to be the [`System.Management.Automation.Internal.Pipe.RemovePipelineVariable` method](https://github.com/PowerShell/PowerShell/blob/d80154430d600a52a1d1e3a9f3ecf032b36185d4/src/System.Management.Automation/engine/Pipe.cs#L278-L285). It sets the variable to null before removing it. Clearing the variable before removing it is the right thing to do; however, I believe this should be done with a new, internal `System.Management.Automation.PSVariable.Clear()` method rather than simply using the set accessor, because the set accessor internally invokes `SetValue`, which has a lot more work associated with it, including checking for and triggering write breakpoints if there are any. A new `Clear()` method could simply assign the value to null to allow for garbage collection to come around when appropriate, without all of the extra work that `SetValue` includes.

If you compare this with `Remove-Variable`, that cmdlet does not trigger any write breakpoints set on the variable as the variable is removed. `-PipelineVariable` functionality should not trigger breakpoints either.

I haven't figured out yet if that issue is also the issue for the "leading" initialization of the variable to null, but it could be the cause for both.

# Steps to reproduce

```powershell
Set-PSBreakpoint -Variable foo -Mode write -Action {Write-Host "Write foo: ${foo}!" -ForegroundColor Cyan}
Get-Date -PipelineVariable foo | ForEach-Object {$_} -PipelineVariable foo | ForEach-Object {$_} -PipelineVariable foo
```

# Expected behavior

```none
Write foo: 12/15/2019 11:37:54!
Write foo: 12/15/2019 11:37:54!
Write foo: 12/15/2019 11:37:54!

December 15, 2019 11:37:54 AM
```

# Actual behavior

```none
Write foo: !
Write foo: !
Write foo: 12/15/2019 11:37:54!
Write foo: 12/15/2019 11:37:54!
Write foo: 12/15/2019 11:37:54!

December 15, 2019 11:37:54 AM
Write foo: !
Write foo: !
Write foo: !
```

# Environment data

Custom build of latest PowerShell (but I haven't updated my tags yet since preview 6 dropped).

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5-124-g70828b4a46b384bc756c934d54451a275c0c9ce2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
With:
```powershell
Set-PSBreakpoint -Variable foo1 -Mode write -Action {Write-Host "Write foo1: ${foo1}!" -ForegroundColor Cyan}
Set-PSBreakpoint -Variable foo2 -Mode write -Action {Write-Host "Write foo2: ${foo2}!" -ForegroundColor Cyan}
Set-PSBreakpoint -Variable foo3 -Mode write -Action {Write-Host "Write foo3: ${foo3}!" -ForegroundColor Cyan}
Get-Date -PipelineVariable foo1 | ForEach-Object {$_} -PipelineVariable foo2 | ForEach-Object {$_} -PipelineVariable foo3
```
I don't see any extra assigments:
```
  ID Script                      Line Command                     Variable                   Action
  -- ------                      ---- -------                     --------                   ------
   1                                                              foo1                       Write-Host "Write foo1: $…
   2                                                              foo2                       Write-Host "Write foo2: $…
   3                                                              foo3                       Write-Host "Write foo3: $…
Write foo1: 12/16/2019 00:03:06!
Write foo2: 12/16/2019 00:03:06!
Write foo3: 12/16/2019 00:03:06!

DisplayHint : DateTime
Date        : 16.12.2019 0:00:00
Day         : 16
DayOfWeek   : Monday
DayOfYear   : 350
Hour        : 0
Kind        : Local
Millisecond : 503
Minute      : 3
Month       : 12
Second      : 6
Ticks       : 637120513865035251
TimeOfDay   : 00:03:06.5035251
Year        : 2019
DateTime    : 16 декабря 2019 г. 0:03:06

Write foo1: !
Write foo2: !
Write foo3: !
```

**Comment by KirkMunro** [comment]
There are three extra assignments at the bottom of your output, when PowerShell internally nullifies the value. Nullifying the PV value as the variable is being cleaned up should not result in variable breakpoints being triggered, just as they are not triggered when you invoke `Remove-Variable`.
