### ISSUE TITLE
Pwsh7-Preview 6 - Error message been partially suppressed.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#11349]
In this case, when a cmdlet error-out, the full error message seems to be partially suppressed. 
This is not happening in Windows PowerShell.

And, it's forcing the do extra steps (run $error.exception) to display more information about the error.

# Steps to reproduce
Run the command Get-ChildItem to list files from a non-existing drive.
```powershell
 Get-ChildItem j:\*.txt

```

# Expected behavior
To show the full error message.
```none
PS [19] > ## - Output sample from Windows PowerShell:
PS [20] > Get-ChildItem j:\*.txt
Get-ChildItem : Cannot find drive. A drive with the name 'j' does not exist.
At line:1 char:1
+ Get-ChildItem j:\*.txt
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (j:String) [Get-ChildItem], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

P
```

# Actual behavior
It's forcing me to use additional step, $error.exception to get error message.
```none
PS [22] > Get-ChildItem j:\*.txt
Get-ChildItem :
PS [24] >
PS [25] > $error.exception
Cannot find drive. A drive with the name 'j' does not exist.
```

# Environment data

```none
PS [7] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
![pw7_err_2019-12-15_15-56-24](https://user-images.githubusercontent.com/19892435/70869078-1e583580-1f55-11ea-9002-a4a148b39850.png)

**Comment by iSazonov** [comment]
I don't see the issue in latest build.
@MaximoTrinidad Could you please repo with nightly build?

**Comment by SeeminglyScience** [comment]
I don't see it in the preview 6 build either:

![image](https://user-images.githubusercontent.com/24977523/70907894-007fe480-1fd8-11ea-8613-dde23e0c4e06.png)

@MaximoTrinidad Can you try it with `pwsh-preview -NoProfile`?

**Comment by MaximoTrinidad** [comment]
Hum! I ran it without the -NoProfile and still get it.

This is odd! Let me reinstall preview.6 again.

![pw7_err_2019-12-16_9-57-17](https://user-images.githubusercontent.com/19892435/70917034-a2103180-1fea-11ea-9ade-84e6f12d16a8.png)

**Comment by MaximoTrinidad** [comment]
I just created another Windows 10 Insider VM and it works!
Windows Insider latest build: 
Version 2004 (OS Build 19041.1)

Strange!  It's my physical system and I can't recover from it.
Updated to latest RTM Version 1909 (OS Build 18363.535)

I checked my other VM's and I don't get it. Sorry!

I will close the issue!

Thanks
:)
