### ISSUE TITLE
SxS PSModulePath basic tests fail in release automation on Server 2016/2019

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#11355]
`PSModulePath changes interacting with other PowerShell processes. - Does not duplicate the System32 module path in subprocesses` in `test\powershell\Modules\Microsoft.PowerShell.Core\CompatiblePSEditions.Module.Tests.ps1`
`SxS Module Path Basic Tests. - Ensures $PSHOME\Modules is inserted correctly when launched from a different version of PowerShell` in `test\test\powershell\engine\Module\ModulePath.Tests.ps1`

They failed in the automation test run, but both passed when running them manually on a 2019 VM, so not exactly sure why they were failing.

**Comment by iSazonov** [comment]
If there are two (or more) processes running they can both write to PSModulePath env.

**Comment by daxian-dbw** [comment]
If that's the cause then we should have already observed the intermittent failure in our daily test run and CIs.

**Comment by anmenaga** [comment]
Previously, I've seen failures in `Does not duplicate the System32 module path in subprocesses` in CI.
Could not repro locally, but it definetely failed in CI before. I've added some diagnostics to a branch based off RC1 branch; we'll see if we get more info on what is going on...

**Comment by adityapatwardhan** [comment]
Failing in 7.0.x and 7.1.x 
https://dev.azure.com/powershell-rel/Release-Automation/_build/results?buildId=2109&view=ms.vss-test-web.build-test-results-tab&runId=13430&resultId=100986&paneView=debug

https://dev.azure.com/powershell-rel/Release-Automation/_build/results?buildId=2108&view=ms.vss-test-web.build-test-results-tab
