### ISSUE TITLE
Change in behavior of Out-Gridview when called on launch

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#11351]
I have some code which takes a -grid switch and sends output to Out-gridView rather than sending it back down the pipeline as normal. 
To ensure the grid view closes when the test runs in a CI pipeline with no one watching, the test runs 
`PowerShell -command "blah blah" `
In recent previews of pwsh, out-gridview has returned. Which is **GREAT** My code works as it used to when run normally.  So now my test should be able to run 
`pwsh -command "blah blah"`
But now PowerShell waits for the grid view window to close before continuing. 
This might be by design so that scripts which show a grid don't immediately close , taking the grid with them or it may be a bug

Repro steps compare 
```powershell

powershell -command "ps | ogv ; sleep 5"



pwsh -command "ps | ogv ; sleep 5"

```

# Expected behavior

```none
Expected to match
```

# Actual behavior

```none

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Yeah, I'm seeing the same difference on Windows 10 with preview6.

@SteveL-MSFT did something change in our implementation, or is this a difference in how .NET Core is handling it?

**Comment by SteveL-MSFT** [comment]
The only changes in the Out-GridView code for PS7 was to make it work with .NET Core 3.0.  Will have to investigate.

**Comment by SteveL-MSFT** [comment]
Stepped through the debugger.  The Main() function exits, but the process doesn't quit.  Looks like something in .NET Core.
