### ISSUE TITLE
ArrayList conversion from one element Json throws exception

### ISSUE THREAD

**Issue by haidouks** [PowerShell/PowerShell#11366]
# Steps to reproduce
In 7.0.0-preview.6-ubuntu-bionic, run the following command.

```
$json = @"
["CANSIN"]
"@
$list = [System.Collections.ArrayList]($json | ConvertFrom-Json)

```

# Expected behavior
Command should not throw exception.

```

```

# Actual behavior
Throws conversion exception

```
InvalidArgument: Cannot convert the "CANSIN" value of type "System.String" to type "System.Collections.ArrayList".

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6
OS                             Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
I think it is dup #11077

**Comment by iSazonov** [comment]
@mklement0 Can you confirm my thoughts?

**Comment by mklement0** [comment]
It is indirectly related to #11077, but there's a more immediate issue:

`ConvertFrom-Json`'s default output behavior has changed after the discussion in #3424: it now _enumerates_ an array by default, so as to be consistent with how cmdlets are generally expected to output _multiple_ objects.

You now need `-NoEnumerate`  to prevent this enumeration:

```powershell
PS> ('[ "one "]' | ConvertFrom-Json -NoEnumerate).GetType().Name
Object[]  # array
```

You can then cast the above to `[System.Collections.ArrayList]`.

As an aside: That you cannot cast a _scalar_ as an array list is somewhat unexpected, given that it works with both `System.Array` and  `System.Collections.Generic.List<T>`

**Comment by mklement0** [comment]
I've created #11749 to target the casting-a-single-item-as-an-ArrayList in a focused manner.
