### ISSUE TITLE
PowerShell does not expand `~` for external commands

### ISSUE THREAD

**Issue by vasily-codefresh** [PowerShell/PowerShell#11375]
Hi,

In [discussion with VSCode team](https://github.com/microsoft/vscode/issues/86856) I've found out that somehow PowerShell does not expand `~` paths for external commands (but does it for internal ones). It's a bug that affects usability very much.

# Steps to reproduce

```powershell
ls ~/.gitconfig
code ~/.gitconfig
```

# Expected behavior

* `ls` lists the file in home directory
* `code` opens file in home directory

# Actual behavior

* `ls` lists file in home directory
* `code` opens file at `%HOME%/~` directory instead

# Environment data

```none
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Good point; the problem is already being tracked in #10675

**Comment by bpayette** [comment]
The problem with resolving everything that starts with a `~` as a path is that you can't pass anything starting with a `~` to an external program. Quoting isn't sufficient to suppress this because you may want to do `~`-expansion in a name with a space in it and that requires quoting the path. The PowerShell workaround (from V1 on) has been to use the `Resolve-Path` command (`rvpa`) to do the expansion as in 
```powershell
code  (rvpa ~\Documents\WindowsPowerShell\profile.ps1) 
```
Of course some commands on Windows are smart enough to do their own `~`-expansion like `vim`. For example,
```powershell
gvim  ~\Documents\WindowsPowerShell\profile.ps1
```
just works (one of the reasons `vim` is my favourite text editor :-) ). `code`, however, does not currently do this but it would be nice if it did. In the meantime, you can create you're own wrapper for `code` which calls `rvpa` under the covers.

**Comment by vasily-codefresh** [comment]
thanks for such a workaround, but it doesn't work with newly created files. that is: if I don't have `~/.gitconfig` yet, `rvpa ~/.gitconfig` will fail.

vscode folks are not willing to implement this, they just closed my ticket, blaming PowerShell.

as for passing `~/` or `~\` directly to program as a start of an argument -- do any actual users need it? Unix users has been living with such restrictions for 35 years and I didn't hear anyone suffered from it.

and yes, from my point of view it's reasonable enough not to expand quoted strings (again, the same as on Unix). at least, it's better than current behavior. my reasoning is: users usually need `~` completion for short paths, if that involves a space or many letters, they will use tab completion, thus expanding `~`.

**Comment by mklement0** [comment]
> as for passing ~/ or ~\ directly to program as a start of an argument -- do any actual users need it?
> Unix users had been living with such restrictions for 35 years an

There is no restriction, as POSIX-like shells determine based on whether the initial `~` is _quoted or not_ whether `~` should be expanded to the user's home dir.

```sh
$ echo ~/sub  # ~ (and /) unquoted -> expanded
/home/jdoe/sub

$ echo '~/sub'  # quoted as a whole-> verbatim
~/sub

# POSIX-like shells allow you to compose a string by mixing unquoted and quoted parts:
$ echo ~/'foo bar'/baz  # ~ (and /) unquoted -> expanded
/home/jdoe/foo bar/baz
```

As you can see, quoting the _whole_ argument suppresses `~` expansion, but
it's easy to have `~` expanded even if the remaining path (or parts of it) needs quoting.

**PowerShell currently _partially_ emulates this behavior** when calling native utilities, but **only on _Unix_**:

```powershell
PS> /bin/echo ~/sub # ~ (and /) unquoted -> expanded
/home/jdoe/sub

PS> /bin/echo '~/sub' # whole string quoted -> verbatim
~/sub

# !! This does currently NOT work the way it does in POSIX-like shells:
PS> /bin/echo ~/'foo bar'/baz
~/foo bar/baz  # !! Even though ~/ was unquoted, no expansion took place.
```

**PowerShell should _fully_ emulate this behavior**, and **on _Windows_ too.** 
However, the automatic globbing feature already implemented on Unix (e.g., unquoted `*.txt` expanding to the list of matching files) is _not_ appropriate for Windows, as discussed in the linked issue [here](https://github.com/PowerShell/PowerShell/issues/10675#issuecomment-537547306).

**Comment by mklement0** [comment]
@vasily-codefresh:

* Given that @SteveL-MSFT  opened #10675, you can assume that there's a fundamental willingness to support `~` expansion on Windows too, so I suggest we continue the conversation there.

* As for the incomplete emulation of the current, Unix-only `~` expansion discussed in my previous comment, I've created #11386

Therefore, I suggest closing this issue.

**Comment by vasily-codefresh** [comment]
yeah, I think that's a duplicate, so closing
