### ISSUE TITLE
What is the Target for 7.0.0-rc.1 and final release version number.

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#11376]
@TravisEz13 - when I run the 7.0.0-rc.1 MSI manually on a system that contains both 6.2.3 and 7.0 preview, it targets the 7.0 preview folder for upgrade, not the 6 folder.

This suggests you want it to stay in the preview distribution channel.

Can you please clarify which chocolatey packages sequences should have 7.0.0-rc.1 queued up as the next release?

1. PowerShell-preview (as a visible package since everything in it is of a pre-production nature)
2. PowerShell-Core (as a non-visible, prerelease package - would happen automatically due to "-rc" in version number).  Would require "-pre" switch to see or install from this feed.

My concern about #2 is that it won't actually replace the 6 version, so does not function as a true prerelease.

Also would it please be possible to have the production release be "7.0.1.0" ?  This clears us of all semantic prerelease / chocolatey version weirdness if it can be done - because in both systems it is greater than all other version numbers that predate it on both the preview and production channel.

**Comment by DarwinJS** [comment]
Releasing as 7.0.1.0 on Powershell-preview since it upgrades the preview folder.  Will also be visible this way and not require the -pre switch.

**Comment by TravisEz13** [comment]
Darwin, I've been sick.  Everything with a `-` in the version is in the `preview` channel.
