### ISSUE TITLE
Please add gss-ntlmssp as Recommends to the powershell debian package

### ISSUE THREAD

**Issue by rhertzog** [PowerShell/PowerShell#11374]
Someone reported to us (Kali) that Enter-PSSession is not working (see https://bugs.kali.org/view.php?id=5915) but we are only installing the package that you provide. From a quick search it looks like that the Debian package that you build should be modified to "Depends" (or "Recommends" if you want it optional) on the "gss-ntlmssp" package that provides the required NTLM support (through a plugin) to libgssapi-krb5-2 which you are already depending on.

FWIW, this is related to https://github.com/PowerShell/PowerShell/issues/6647 but I wanted to highlight the fact that the Debian package should be modified, whereas the current solution was to modify the docker image to add the missing package. By adding the dependency on the package itself, it would automatically fix all use cases.

**Comment by TravisEz13** [comment]
I would not recommend installing this.  cc @SteveL-MSFT What are your thoughts?

**Comment by SteveL-MSFT** [comment]
My concern is that we don't have test coverage for this and including it implies we've validated it and support it.

**Comment by iSazonov** [comment]
Maybe add a unsupported note to Linux PowerShell installation docs? It is common for such Linux users to use special configurations.

**Comment by rhertzog** [comment]
You do realize that you ship that package in some of the docker images that you provide?

For example for centos, this got merged: https://github.com/PowerShell/PowerShell-Docker/pull/125

It seems really strange to have different standards for various distributions. Also the lack of test coverage can be tracked in a separate issue/request, it seems weird to require someone to write functional tests to get this one-line patch merged (since adding a dependency is really trivial).

**Comment by TravisEz13** [comment]
Users can manually install the package.  We don't recommend installing NTLM on non-Windows

The package being included in docker is an independent decision.
