### ISSUE TITLE
Emulation of ~ (tilde) expansion for native utilities is incomplete

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11386]
Note: 

* `~` expansion for native utilities currently fundamentally only works on _Unix_ platforms - but Windows would benefit from it too:  see #10675

* Fully emulating the logic of `~` expansion in PowerShell requires recognizing _partial_ quoting of sub-tokens in arguments (e.g., `~/'foo bar'`), which may turn out to be challenge based on how argument parsing currently works.

# Steps to reproduce

On a Unix-like platform:

```powershell
# Quoting the argument as a whole always suppresses ~ expansion.
/bin/echo '~/foo' | Should -Be '~/foo'

# Both commands should expand ~ to the value of $HOME, 
# because the ~/ prefix is unquoted.
/bin/echo ~/foo | Should -Not -BeLike '~/*'
/bin/echo ~/'foo bar' | Should -Not -BeLike '~/*'
```

# Expected behavior

All tests should succeed.

# Actual behavior

The 3rd test fails, because the partially quoted argument prevented `~` expansion - even though `~/` is _unquoted_.

```none
Expected like wildcard '~*' to not match '~/foo bar', but it did match.
```

Note that in POSIX-like shells - whose behavior here is being emulated - `/bin/echo ~/'foo bar'` indeed expands `~`, as expected.

# Environment data

```none
PowerShell Core 7.0.0-rc.1
```

**Comment by Zenexer** [comment]
It's also missing support ~username syntax; for example, if I have a user `foo` with a home directory of `/home/foo`, even if I'm currently running as user `bar`, `~foo/test` should resolve to `/home/foo/test`.  I don't think it's too important to prioritize that feature, since it's not widely known, but I figured I'd mention it.

**Comment by rkitover** [comment]
No, I believe the ~user expansion is widely known, at least among linux developers and power users and is **VERY** useful.

E.g., I'm setting up an account for a friend on my windows server, I may want to do something like:

```powershell
cpi -rec vimfiles, src, .vimrc, .gitconfig ~other_user
```

It should tab complete the expansion too.

**Comment by SteveL-MSFT** [comment]
~username expansion should be a separate issue
