### ISSUE TITLE
Fix the performance of `Get-Module -ListAvailable -All`

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#11387]
# Summary of the new feature/enhancement

As a PowerShell user
I want `Get-Module -ListAvailable -All` to be much more performant than it is right now
so that I don't have to wait an eternity when I'm processing modules on a computer with PowerShell.

# Proposed technical implementation details (optional)

The problem here is simple:

If I run `$env:PSModulePath -split ';' | Get-ChildItem -Recurse`, it returns in 1.121 seconds.

If I run `Get-Module -ListAvailable -All`, it returns in 35.803 seconds.

Something is very wrong with the way `Get-Module` is implemented for it to take over 30x longer than performing a file-system scan of all module folders.

The fix here would be to refactor the `GetModuleCommand` class methods and helper methods that it relies on significantly so that modules can be retrieved much more quickly. Looking at that code, it isn't that surprising that this command takes so long, and there is definitely some room for refactoring.

**Comment by BrucePay** [comment]
> The problem here is simple....
> $env:PSModulePath -split ';' | Get-ChildItem -Recurse,

While I agree this is ridiculously slow, the above is not really representative of what's happening since `Get-Module` reads and deserializes each `.psd1` it encounters and `Get-ChildItem` does not.

**Comment by iSazonov** [comment]
It was reported in #10983 for the first time - security fix consequences.
This would have to be fixed in Windows but we get #11074
Also we have #10309

**Comment by KirkMunro** [comment]
@iSazonov How is this a duplicate of those? One talks specifically about an API for CDXML modules. Do we know that is the single root cause here? The others talk about PowerShell launching and other things, but fail to identify that `Get-Module -ListAvailable -All` is poorly written and could use some refactoring. There may be things we cannot change due to security consequences, but shouldn't there be investigation to see what we can change, and make sure that performance is optimal without compromising security?

**Comment by iSazonov** [comment]
@KirkMunro I believe the single root cause is here.  I measured the scenario. Safer API became slow after mentioned Windows security fix. I guess most of Windows file operations too. I'd prefer Windows security team fixed this issue.

**Comment by KirkMunro** [comment]
@iSazonov Ok. Thanks for the extra information, that helps.
