### ISSUE TITLE
Execution of { dotnet restore $project $RestoreArguments } by build.psm1: line 570 failed with exit code 1

### ISSUE THREAD

**Issue by srthomson** [PowerShell/PowerShell#11408]
![Error](https://user-images.githubusercontent.com/10306855/71215660-470f6080-22b0-11ea-9d8e-2b90e5e22a81.png)
After running Start-PSBuild I get the following:

Run dotnet restore D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\powershell-win-core --runtime win7-x64 /property:SDKToUse=Microsoft.NET.Sdk.WindowsDesktop --verbosity quiet
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.ConsoleHost\Microsoft.PowerShell.ConsoleHost.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.WSMan.Management\Microsoft.WSMan.Management.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.Security\Microsoft.PowerShell.Security.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.Commands.Diagnostics\Microsoft.PowerShell.Commands.Diagnostics.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.Management.Infrastructure.CimCmdlets\Microsoft.Management.Infrastructure.CimCmdlets.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.SDK\Microsoft.PowerShell.SDK.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.Commands.Utility\Microsoft.PowerShell.Commands.Utility.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\System.Management.Automation\System.Management.Automation.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.WSMan.Runtime\Microsoft.WSMan.Runtime.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.MarkdownRender\Microsoft.PowerShell.MarkdownRender.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.Commands.Management\Microsoft.PowerShell.Commands.Management.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\Microsoft.PowerShell.CoreCLR.Eventing\Microsoft.PowerShell.CoreCLR.Eventing.csproj]
D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 128. [D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\src\powershell-win-core\powershell-win-core.csproj]

After a few retries, I just get the error: 

Execution of { dotnet restore $project $RestoreArguments } by build.psm1: line 570 failed with exit code 1
At D:\Downloads\AZSentinel\Pre-Reqs\PowerShell-master\build.psm1:2065 char:17
+                 throw $errorMessage
+                 ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Execution of { ...ith exit code 1:String) [], RuntimeException
    + FullyQualifiedErrorId : Execution of { dotnet restore $project $RestoreArguments } by build.psm1: line 570 failed with exit code 1

I'm not sure what I'm doing wrong.....

**Comment by vexx32** [comment]
Couple things to try. First, make sure your copy of the repo is up to date (`git fetch; git status`) -- you may want to make sure you also have the latest commits from upstream if your main remote is a fork (as it often is) -- `git pull upstream master` can do that if you need that (substitute the name of your upstream remote if needed).

Second, always try with `Start-PSBuild -Clean` _first_. Do a clean build anytime you pull new commits in from upstream, and/or any other time you find yourself running into issues. After a clean build, you can do regular builds as needed, but a -Clean build is always required first, as it generates some necessary files.

Let us know how that goes, and we'll see what more needs to happen here. 🙂

**Comment by stevenebutler** [comment]
FYI, I had the same issue and it was caused by my fork not having any tags.

I used
```bash
git remote add upstream https://github.com/PowerShell/PowerShell.git
git fetch -t upstream
```

to resolve this.
