### ISSUE TITLE
Startup very slowly, about 10 senconds

### ISSUE THREAD

**Issue by chenyj796** [PowerShell/PowerShell#11409]
# Steps to reproduce
Double click the pwsh.exe, need wait about 10 seconds to show the prompt.

If I append the -NonInteractive parameter, it shows the prompt immediately.

When I input $psver and press TAB key, it will block everything for about 10 seconds also. others such as Get-date, [System.Environment]::CurrentDirectory ... works fine.

# Environment data

```none
PS C:\Users\chenyj> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 6.1.7601 Service Pack 1
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
What do you see with -NoProfile parameter?

**Comment by chenyj796** [comment]
With -NoProfile parameter works like without parameter.

**Comment by iSazonov** [comment]
NonInteractive disable PSReadline module importing. If you run with NonInteractive and import PSReadline how long has this been going on?

**Comment by chenyj796** [comment]
Just like without parameter

**Comment by iSazonov** [comment]
Can you try with disconnected network interface?

**Comment by chenyj796** [comment]
The machine has no internet access.

**Comment by iSazonov** [comment]
My request was to detach network cable at all.

I think it is dup https://github.com/PowerShell/PowerShell/issues/10983.

**Comment by Silex** [comment]
I still have this behavior with 7.1.0, whould I create an issue?

**Comment by iSazonov** [comment]
@Silex Please open new issue with repro steps - we need to reproduce the issue to investigate.
