### ISSUE TITLE
Powershell 7: Get-ChildItem in Invoke-Command script block comes back with blank items

### ISSUE THREAD

**Issue by Actionn** [PowerShell/PowerShell#11400]
# Steps to reproduce

```powershell

Invoke-Command -ComputerName localhost -ScriptBlock {get-childitem C:\}

```

# Expected behavior

Comes back with a list of items

# Actual behavior

Comes back with a list of items, but the properties are all blank. I think it's something to do with the default properties not being selected like if you do it locally? For instance PSPath is Microsoft.Powershell.Core\FileSystem::C:\ ... You can actually do something like below and it will come back with data:

```powershell

Invoke-Command -ComputerName localhost -ScriptBlock {get-childitem C:\ | select * | ft}

```

Another thing I noticed - May have some baring on what's going on here:

```powershell
PS C:\Users\xx\Desktop> invoke-Command -ComputerName localhost -ScriptBlock {$PSVersionTable}

Name                           Value
----                           -----
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
WSManStackVersion              3.0
BuildVersion                   10.0.18362.145
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
PSVersion                      5.1.18362.145

```

Another Note - I don't have this issue with Powershell 6.2.3 on the same system.

# Environment data

```powershell

PS C:\Users\xx\Desktop> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by iSazonov** [comment]
I can not repo with latest PowerShell 7.0 builds.

**Comment by mczerniawski** [comment]
Hi
I have the same. First though it's my build, but then checked on few other systems and all are same:
1. Using PowerShell 7 on source host.
2. Invoke-command to windows box with default Windows PowerShell 5.1
3. Run Get-ChildItem or even New-Item results in 'blank' output:

`PS C:\AdminTools> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\AdminTools> Get-ChildItem C:\AdminTools\test\


    Directory: C:\AdminTools\test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          20.03.2020    13:25              0 test1.txt
-a---          20.03.2020    13:25              0 test10.txt
-a---          20.03.2020    13:25              0 test2.txt
-a---          20.03.2020    13:25              0 test3.txt
-a---          20.03.2020    13:25              0 test4.txt
-a---          20.03.2020    13:25              0 test5.txt
-a---          20.03.2020    13:25              0 test6.txt
-a---          20.03.2020    13:25              0 test7.txt
-a---          20.03.2020    13:25              0 test8.txt
-a---          20.03.2020    13:25              0 test9.txt

PS C:\AdminTools> Invoke-Command -ComputerName OBJPLIT-SRV0 -ScriptBlock {$PSVersionTable}

Name                           Value
----                           -----
CLRVersion                     4.0.30319.42000
PSRemotingProtocolVersion      2.3
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
SerializationVersion           1.1.0.1
BuildVersion                   10.0.14393.3471

PS C:\AdminTools> Invoke-Command objplit-srv0 -scriptblock{ 1..10 | % {New-Item -ItemType File -Name ('test{0}.txt' -f $_) -Path c:\admintools\test -force }}


    Directory: C:\admintools\test

Mode                 LastWriteTime         Length Name                               PSComputerName
----                 -------------         ------ ----                               --------------
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0

PS C:\AdminTools> Invoke-Command objplit-srv0 -scriptblock{ Get-ChildItem C:\AdminTools\test\}


    Directory: C:\AdminTools\test

Mode                 LastWriteTime         Length Name                               PSComputerName
----                 -------------         ------ ----                               --------------
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0
                                                                                     objplit-srv0

PS C:\AdminTools>`

**Comment by mczerniawski** [comment]
But if I connect to PowerShell.7 remote endpoint, I get expected results:

```powershell
PS C:\AdminTools> Invoke-Command -ComputerName objplit-srv0 -ConfigurationName 'PowerShell.7' -ScriptBlock {Get-ChildItem C:\AdminTools\test\}


    Directory: C:\AdminTools\test

Mode                 LastWriteTime         Length Name                               PSComputerName
----                 -------------         ------ ----                               --------------
-a---          20.03.2020    13:29              0 test1.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test10.txt                         objplit-srv0
-a---          20.03.2020    13:29              0 test2.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test3.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test4.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test5.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test6.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test7.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test8.txt                          objplit-srv0
-a---          20.03.2020    13:29              0 test9.txt                          objplit-srv0

```

**Comment by iSazonov** [comment]
@mczerniawski Windows PowerShell is frozen and the issue with Windows PowerShell endpoint will be never fixed.

**Comment by mczerniawski** [comment]
Hm. 
So there's nothing that can be done in PS7 that would fix this? 
It can greatly impact with adoption on PS7. 
Because of this not only to fully utilize benefits of PS7 I have to get it on all endpoints, but it becomes very... unpredictable in scanerios ManagementStation-PS7 -> EndpointServers (still PS5.1)

**Comment by iSazonov** [comment]
@vexx32 We changed Formatting system and how we add FileSystem provider properties.

**Comment by PaulHigin** [comment]
Normally, we try to maintain down level compatibility for remoting and it looks like this is broken.  I think this should be looked into but I probably won't get to it until next week.

**Comment by doctordns** [comment]
@iSazonov - can you point to the formatting mechanism now used? In Windows PowerShell this would have been simple - a single line or two of the XML file would have been needed to fix this in the old days. Where is the equivalent of the XML in PowerShell 7?

**Comment by iSazonov** [comment]
@doctordns All Formatting system is the same. Only minor changes was made.
I guess you ask about standard XML files like FileSystem_format.ps1xml. All such files was converted to C# code to speed up startup scenario (see  __*ps1xml.cs__ files).

**Comment by doctordns** [comment]
I must have missed something - but isn't this a bug?

**Comment by illusive-man** [comment]
Just wanted to remind about the issue. And in PowerShell 7.1.0-preview.7 no changes to described behavior (same as in #13412).

**Comment by vexx32** [comment]
Related: #10759

**Comment by Borkason** [comment]
Hope this gets solved soon.

**Comment by dkattan** [comment]
Hey guys, 

I got to the bottom of this.

PowerShell 7 is expecting DirectoryInfo objects to include NameString, LengthString, and LastWriteTimeString properties on the XML. Windows PowerShell does not include those properties when serializing, therefore they come in blank.

![image](https://user-images.githubusercontent.com/1424395/132963489-0e0cf5fc-ec8c-400e-981a-938e50fca0b1.png)

How would you feel about modifying the following code to fall back to using the non-String name of the property?

https://github.com/PowerShell/PowerShell/blob/dad7a34ee743c81dd96e742ed5516ac782388972/src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs#L184-L185

Perhaps something like 
```c#
x = target.Members[_stringValue];
if(x is null && _stringValue.EndsWith("String"))
{
    var nonStringName = _stringValue.Replace("String", String.Empty);
    x = target.Members[nonStringName]?.Value.ToString();
}
```

@rjmholt 

The following code reproduces the problem in PowerShell 7
```powershell
Function ConvertFrom-CliXml
{
    param($InputString)
    [System.Management.Automation.PSSerializer]::Deserialize($InputString)
}


$xml = @'
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.IO.DirectoryInfo</T>
      <T>System.IO.FileSystemInfo</T>
      <T>System.MarshalByRefObject</T>
      <T>System.Object</T>
    </TN>
    <ToString>.Azure</ToString>
    <Props>
      <S N="Name">.Azure</S>
      <S N="FullName">C:\Users\DKattan\.Azure</S>
      <Obj N="Parent" RefId="1">
        <TNRef RefId="0" />
        <ToString>DKattan</ToString>
        <Props>
          <S N="Name">DKattan</S>
          <S N="FullName">C:\Users\DKattan</S>
          <S N="Parent">Users</S>
          <B N="Exists">true</B>
          <S N="Root">C:\</S>
          <S N="Extension"></S>
          <DT N="CreationTime">2021-05-26T10:01:21.9908836-05:00</DT>
          <DT N="CreationTimeUtc">2021-05-26T15:01:21.9908836Z</DT>
          <DT N="LastAccessTime">2021-09-11T17:26:13.4822802-05:00</DT>
          <DT N="LastAccessTimeUtc">2021-09-11T22:26:13.4822802Z</DT>
          <DT N="LastWriteTime">2021-09-11T17:20:37.9533857-05:00</DT>
          <DT N="LastWriteTimeUtc">2021-09-11T22:20:37.9533857Z</DT>
          <S N="Attributes">Directory</S>
        </Props>
        <MS>
          <S N="Mode">d-----</S>
          <S N="BaseName">DKattan</S>
          <Obj N="Target" RefId="2">
            <TN RefId="1">
              <T>System.Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]</T>
              <T>System.Object</T>
            </TN>
            <LST />
          </Obj>
          <Nil N="LinkType" />
        </MS>
      </Obj>
      <B N="Exists">true</B>
      <Obj N="Root" RefId="3">
        <TNRef RefId="0" />
        <ToString>C:\</ToString>
        <Props>
          <S N="Name">C:\</S>
          <S N="FullName">C:\</S>
          <Nil N="Parent" />
          <B N="Exists">true</B>
          <S N="Root">C:\</S>
          <S N="Extension"></S>
          <DT N="CreationTime">2019-12-07T03:03:44.4609777-06:00</DT>
          <DT N="CreationTimeUtc">2019-12-07T09:03:44.4609777Z</DT>
          <DT N="LastAccessTime">2021-09-11T17:26:13.4579316-05:00</DT>
          <DT N="LastAccessTimeUtc">2021-09-11T22:26:13.4579316Z</DT>
          <DT N="LastWriteTime">2021-09-03T20:16:37.4361298-05:00</DT>
          <DT N="LastWriteTimeUtc">2021-09-04T01:16:37.4361298Z</DT>
          <S N="Attributes">Hidden, System, Directory</S>
        </Props>
        <MS>
          <S N="Mode">d--hs-</S>
          <S N="BaseName">C:\</S>
          <Obj N="Target" RefId="4">
            <TNRef RefId="1" />
            <LST />
          </Obj>
          <Nil N="LinkType" />
        </MS>
      </Obj>
      <S N="Extension">.Azure</S>
      <DT N="CreationTime">2021-08-04T07:40:23.6192722-05:00</DT>
      <DT N="CreationTimeUtc">2021-08-04T12:40:23.6192722Z</DT>
      <DT N="LastAccessTime">2021-09-11T15:21:32.0672114-05:00</DT>
      <DT N="LastAccessTimeUtc">2021-09-11T20:21:32.0672114Z</DT>
      <DT N="LastWriteTime">2021-08-04T07:40:23.844276-05:00</DT>
      <DT N="LastWriteTimeUtc">2021-08-04T12:40:23.844276Z</DT>
      <Obj N="Attributes" RefId="5">
        <TN RefId="2">
          <T>System.IO.FileAttributes</T>
          <T>System.Enum</T>
          <T>System.ValueType</T>
          <T>System.Object</T>
        </TN>
        <ToString>Directory</ToString>
        <I32>16</I32>
      </Obj>
    </Props>
    <MS>
      <S N="PSPath">Microsoft.PowerShell.Core\FileSystem::C:\Users\DKattan\.Azure</S>
      <S N="PSParentPath">Microsoft.PowerShell.Core\FileSystem::C:\Users\DKattan</S>
      <S N="PSChildName">.Azure</S>
      <Obj N="PSDrive" RefId="6">
        <TN RefId="3">
          <T>System.Management.Automation.PSDriveInfo</T>
          <T>System.Object</T>
        </TN>
        <ToString>C</ToString>
        <Props>
          <S N="CurrentLocation">Users\DKattan</S>
          <S N="Name">C</S>
          <Obj N="Provider" RefId="7">
            <TN RefId="4">
              <T>System.Management.Automation.ProviderInfo</T>
              <T>System.Object</T>
            </TN>
            <ToString>Microsoft.PowerShell.Core\FileSystem</ToString>
            <Props>
              <S N="ImplementingType">Microsoft.PowerShell.Commands.FileSystemProvider</S>
              <S N="HelpFile">System.Management.Automation.dll-Help.xml</S>
              <S N="Name">FileSystem</S>
              <S N="PSSnapIn">Microsoft.PowerShell.Core</S>
              <S N="ModuleName">Microsoft.PowerShell.Core</S>
              <Nil N="Module" />
              <S N="Description"></S>
              <S N="Capabilities">Filter, ShouldProcess, Credentials</S>
              <S N="Home">C:\Users\DKattan</S>
              <Obj N="Drives" RefId="8">
                <TN RefId="5">
                  <T>System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSDriveInfo, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]</T>
                  <T>System.Object</T>
                </TN>
                <LST>
                  <Ref RefId="6" />
                  <S>D</S>
                  <S>E</S>
                </LST>
              </Obj>
            </Props>
          </Obj>
          <S N="Root">C:\</S>
          <S N="Description"></S>
          <Nil N="MaximumSize" />
          <Obj N="Credential" RefId="9">
            <TN RefId="6">
              <T>System.Management.Automation.PSCredential</T>
              <T>System.Object</T>
            </TN>
            <ToString>System.Management.Automation.PSCredential</ToString>
            <Props>
              <Nil N="UserName" />
              <Nil N="Password" />
            </Props>
          </Obj>
          <Nil N="DisplayRoot" />
        </Props>
        <MS>
          <U64 N="Used">463848312832</U64>
          <U64 N="Free">35528298496</U64>
        </MS>
      </Obj>
      <Ref N="PSProvider" RefId="7" />
      <B N="PSIsContainer">true</B>
      <S N="Mode">d-----</S>
      <S N="BaseName">.Azure</S>
      <Obj N="Target" RefId="10">
        <TNRef RefId="1" />
        <LST />
      </Obj>
      <Nil N="LinkType" />
    </MS>
  </Obj>
</Objs>
'@
ConvertFrom-CliXml $xml

```

**Comment by iSazonov** [comment]
> Perhaps something like
> 
> ```cs
> x = target.Members[_stringValue];
> if(x is null && _stringValue.EndsWith("String"))
> {
>     var nonStringName = _stringValue.Replace("String", String.Empty);
>     x = target.Members[nonStringName]?.Value.ToString();
> }
> ```

We could avoid allocations with switch expression:
```c#
var propertyName =  _stringValue switch
{
    "NameString"               => "Name",
    "LengthString"             => "Length",
    "LastWriteTimeString" => "LastWriteTime",
    _ => string.Empty
}
```

**Comment by PaulHigin** [comment]
@dkattan  Thanks for tracking this down!
It looks like this new property was added sometime in PowerShell 6 and the format view was updated to support it.
And this breaks FileSystemInfo objects formatting from earlier versions of PowerShell over the remoting layer since the new property(s) are not supported.

But I don't think this is the right way to fix the problem.  Instead, I believe the FileSystem_format_ps1xml.cs file should be updated to fall back to the old properties if the new ones don't exist.

**Comment by dkattan** [comment]
> @dkattan Thanks for tracking this down!
> It looks like this new property was added sometime in PowerShell 6 and the format view was updated to support it.
> And this breaks FileSystemInfo objects formatting from earlier versions of PowerShell over the remoting layer since the new property(s) are not supported.
> 
> But I don't think this is the right way to fix the problem. Instead, I believe the FileSystem_format_ps1xml.cs file should be updated to fall back to the old properties if the new ones don't exist.

The best way to get the right answer is to post the wrong one lol. I agree upon further inspect that makes the most sense. Do we know why those new properties were added in the first place? Can we simply remove them?

**Comment by PaulHigin** [comment]
I believe these new properties were added to solve cross platform issues with date/time information.  We don't want to remove them and I don't think we need to.  It is the change in the FileSystem format file that caused the regression over remoting, and we can fix the problem there.

**Comment by dkattan** [comment]
> I believe these new properties were added to solve cross platform issues with date/time information. We don't want to remove them and I don't think we need to. It is the change in the FileSystem format file that caused the regression over remoting, and we can fix the problem there.

I'm not sure if this is for cross platform compatibility. Perhaps that was the original intent but this problem doesn't occur when formatted as a List. If you look in  FileSystem_format_ps1xml.cs you can clearly see that the List format still uses the original non -String names, and it works as expected in both scenarios.

https://github.com/PowerShell/PowerShell/blob/55ccbb6803162965eead3a08aace37f11ea7630b/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs#L95-L118

**Comment by SteveL-MSFT** [comment]
Dupe of https://github.com/PowerShell/PowerShell/issues/10759

**Comment by colinblaise** [comment]
Seems like this issue lost some traction. 

Could this be the offending code that needs updating?

https://github.com/PowerShell/PowerShell/blob/55ccbb6803162965eead3a08aace37f11ea7630b/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs#L45-L92

**Comment by iSazonov** [comment]
@colinblaise You reference Unix code but the issue is only with connecting to Windows PowerShell endpoint from pwsh.

**Comment by dkattan** [comment]
> @colinblaise You reference Unix code but the issue is only with connecting to Windows PowerShell endpoint from pwsh.

Yes, the problem is that at some point the table formatter in pwsh was changed to pull Name from NameString.

pwsh serializes Name into both Name and NameString.

Windows PowerShell serializes Name into Name therefore the table formatter in pwsh doesn’t have NameString.

I truly believe the whole “NameString” concept was never fully baked and we can simply revert the table formatter for this object to read from Name just like the List formatter does.

**Comment by dkattan** [comment]
I guess my point is, if NameString is such a big deal, why doesn’t Format-List use it?
