### ISSUE TITLE
MSIX installer doesn't install PowerShell on Windows 10

### ISSUE THREAD

**Issue by jeroenlandheer** [PowerShell/PowerShell#11403]
# Steps to reproduce
- Install powershell with the MSI***X*** installer.

# Expected behavior
- PowerShell should install

# Actual behavior
- The package does not install. Error message: "This app package is not supported for installation by App Installer because it uses certain restricted capabilities."
![image](https://user-images.githubusercontent.com/3246548/71152954-25729280-2238-11ea-93f2-998437398b96.png)

# Environment data
- Windows 10 Professional version 1903.
- PowerShell Core v7.0 RC1

**Comment by Zenexer** [comment]
Able to reproduce on a relatively fresh install of Windows 10 Pro 1909.

**Comment by vexx32** [comment]
See the notes in the [installation documentation](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#installing-the-msix-package):

> Once downloaded, you cannot simply double-click on the installer as this package requires use of un-virtualized resources. To install, you must use the Add-AppxPackage cmdlet:
> ```
> Add-AppxPackage PowerShell-<version>-win-<os-arch>.msix
> ```

I think I remember that @SteveL-MSFT mentioned that this isn't something they're able to simply "resolve" for a downloaded MSIX, but will be a non-issue for releases that make it to the Windows Store proper.

**Comment by Zenexer** [comment]
@vexx32 Could this be added to the README?  Currently there aren't any instructions for the MSIX.
