### ISSUE TITLE
Formatting for unthrown exception incorrect

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#11413]
# Steps to reproduce

```powershell
$exception = [ComponentModel.Win32Exception]::new(0x8007007a)

# Send to output normally
$exception

# Throw
throw $exception
```

# Expected behavior

Both the output stream exception and the `ErrorRecord` wrapped thrown exception to look similar, or at the very least display the `Exception.Message` text.

```none
# Output stream
The data area passed to a system call is too small.

# Error stream
OperationStopped: The data area passed to a system call is too small.
```

# Actual behavior

```none
# Output stream

Error:

# Error stream
OperationStopped: The data area passed to a system call is too small.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Including screenshot since the "Actual behavior" section looks potentially confusing on this one:

![image](https://user-images.githubusercontent.com/24977523/71278019-6fd13d80-2324-11ea-8705-fa16ce35650e.png)

**Comment by iSazonov** [comment]
It seems it is ConciseView issue.

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Looks like I didn't handle the case where an exception isn't wrapped because it wasn't thrown.  PR coming soon once I fix a different issue with NormalView.
