### ISSUE TITLE
Windows PowerShell modules have a priority if WinCompat feature is enabled

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#11419]
If WinCompat feature is enabled and loaded a Windows PowerShell module ,cmdlets from the module have a priority over PowerShell Core cmdlets.
/cc @anmenaga 

# Steps to reproduce

`Get-Date -UFormat "%s"` was changed in PowerShell Core and we use this in follow demo. 

![image](https://user-images.githubusercontent.com/22290914/71308305-86f35680-241c-11ea-937e-7c7a192c7981.png)

# Expected behavior

Get-Date from PowerShell Core is involved.

I'd expect that PowerShell Core cmdlets have a priority or it is better WinCompat feature exports only requested cmdlet which explicitly presents in a feature list. Perhaps we could do `Enable/Disable-WindowsPowerShellCmdlet -Module <name> -Cmdlet <name>`

# Actual behavior

Get-Date from Windows PowerShell is involved.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.6
PSEdition                      Core
GitCommitId                    7.0.0-preview.6-71-g36d3b3c0e45937d56650b2747effde94c20b42aa
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anmenaga** [comment]
Yup, this is because proxy commands are Functions [which precede Cmdlets during execution](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7):

> If you do not specify a path, PowerShell uses the following precedence order when it runs commands:
> 1. Alias
> 2. Function
> 3. Cmdlet
> 4. Native Windows commands

`Enable/Disable-WindowsPowerShellCmdlet -Module <name> -Cmdlet <name` is an interesting idea.

**Comment by doctordns** [comment]
Not convinced that Enable/Disable is needed. If you want fine-grained delegation, I'd suggest using JEA (once that starts to work properly in PowerShell 7).

**Comment by alexandair** [comment]
@doctordns What is a problem with JEA in PowerShell 7?

**Comment by SteveL-MSFT** [comment]
The user shouldn't have to manage the experience through enable/disable cmdlets.  Ideally, if the cmdlet exists in PS7, that one should be used.  However, we still want to support selective proxy generation so that `ConvertFrom-String` is available.

**Comment by doctordns** [comment]
> @doctordns What is a problem with JEA in PowerShell 7?

In my case, it does not work properly in practice. See  #11538 

It sounds like this is an issue, the team are aware of it, and should be resolved by RTM (and hopefully earlier),

**Comment by anmenaga** [comment]
While the fix is being worked on, here is a temporary workaround that can be used:
Local Core-native cmdlet can be called instead of the proxy function using call operator; e.g.:
`&(Get-Command -Name Import-Csv -CommandType Cmdlet) .\TestColumn.csv`
or
```
$ImportCsv = Get-Command -Name Import-Csv -CommandType Cmdlet
&($ImportCsv) .\TestColumn.csv
```
