### ISSUE TITLE
Add ConvertTo/From Base64

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#11414]
# Summary of the new feature/enhancement

I think powershell needs some analogy of base64 utility 

# Proposed technical implementation details (optional)
"YmxhaGJsYWgNCg==" | ConvertFrom-Base64  | ConvertTo-Base64

**Comment by alexandair** [comment]
@SteveL-MSFT is already working on it.

**Comment by SteveL-MSFT** [comment]
Dupe of https://github.com/PowerShell/PowerShell/issues/8620
