### ISSUE TITLE
A malformed type literal passed to the -is or -as operator is quietly ignored at the prompt

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11428]
Note that the problem only surfaces _at the interactive prompt_, whether or not PSReadLine is loaded.

In a _script_ / script block, an error occurs, as expected.

This is a regression from v6.2.3 / WinPS.

# Steps to reproduce

Submit _at the prompt_:

```powershell
'foo' -is [string 
'foo' -as [string 
```

# Expected behavior

A statement-terminating error with message:

```
Missing ] at end of attribute or type literal.
```

# Actual behavior

Both commands fail quietly, and `$?` even contains `$true`.

# Environment data

```none
PowerShell Core 7.0.0-rc.1
```

**Comment by vexx32** [comment]
Present in preview6 too, so something happened somewhere before that. 🤔

**Comment by iSazonov** [comment]
I can not repo with latest build.

**Comment by BrucePay** [comment]
It works fine in 6.2.3 so it's definitely a regression 7.

**Comment by iSazonov** [comment]
Works well in 7.0 Preview4.

**Comment by SeeminglyScience** [comment]
It's a bug with the concise error view.  The exception is still in `$Error` and if you retrieve it the formatting is blank.  @iSazonov if it doesn't repro with the latest build, it was probably fixed with #11415.

**Comment by iSazonov** [comment]
@mklement0 Can you confirm with nightly build that the issue was fixed?

**Comment by mklement0** [comment]
Thanks for diagnosing, @SeeminglyScience.

Indeed, @iSazonov, the problem has been fixed in the latest daily build.
