### ISSUE TITLE
Gitter outage causing failure on PowerShell-CI-static-analysis

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#11437]
A [Gitter outage](https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8821) on 2019-12-26 is causing a test on the PowerShell-CI-static-analysis pipeline to fail:

> 2019-12-27T00:53:00.2202932Z [-] https://gitter.im/PowerShell/PowerShell?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge should work 269.56s
> 2019-12-27T00:53:00.2787888Z RuntimeException: retry of URL failed with error: Response status code does not indicate success: 504 (GATEWAY_TIMEOUT).
> 2019-12-27T00:53:00.2790901Z at , /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117

**Comment by xtqqczze** [comment]
Opened #11438 to aid diagnosis in future.

**Comment by xtqqczze** [comment]
To fix this, we should add error 504 (Gateway Timeout) to allowedFailures.

**Comment by iSazonov** [comment]
It is common issue with gitter PowerShell room.
