### ISSUE TITLE
Ansi codes are displayed instead of formatting text

### ISSUE THREAD

**Issue by dialex** [PowerShell/PowerShell#11449]
# Steps to reproduce

```powershell
git clone https://github.com/dialex/JcdpConsumer
mvn package
java -jar target/JCDP-Sandbox-0.0.0-jar-with-dependencies
```

# Expected behavior

The output is colored (both font and background)

# Actual behavior

The output is not colored, and shows Ansi codes

# Context

This is how it looks on Windows PS6 vs [Windows Terminal](https://github.com/microsoft/terminal) (maybe you can reach out to your fellow teammates and ask what they're doing differently):
![Capture](https://user-images.githubusercontent.com/2140450/71546839-2753f880-2992-11ea-94d4-cff7a0de8c43.PNG)

I'm the maintainer of JCDP, a java lib to print formatted output on terminals. For that it uses [standard Ansi codes](https://en.wikipedia.org/wiki/ANSI_escape_code). On Linux/Mac it always worked fine. On Windows, I had to depend on Jansi to convert those Ansi codes to something Windows friendly.

I read that Win10 now supports Ansi codes, so I removed the Jansi dependency (https://github.com/dialex/JCDP/issues/25) and tried to run the lib again. Sadly it didn't work on Win PS6... I'm not sure why. Is it because I need to enable the ["Virtual Terminals" feature](https://devblogs.microsoft.com/commandline/new-experimental-console-features/)? Then why does it work out of the box for Win Terminal?

**Comment by iSazonov** [comment]
> This is how it looks on Windows PS6 vs Windows Terminal
> Then why does it work out of the box for Win Terminal?

I don't understand that you compare. 
There are:
- classic Windows console and new Windows Terminal
- PS7 and Windows PowerShell
So we have 4 cases for comparison.
Please clarify that does not work for you.
And please use latest PowerShell 7 build for tests.

**Comment by dialex** [comment]
Sorry if I wasn't clear, that's on me. Windows has 4 diff command lines? 😵 

Here's my problem: my lib claims that a dev can use it to format the text the send to a command line. Right now, it "just works" on Linux and macOS, so I don't need to issue any requirements to devs. So **what are the requirements for it to work on Windows?**

- You must have **Windows 10 Version 1511** or up
- You must use **XXXX cli**
  - what goes here? PS6? PS7? Win Terminal?
  - what is the _defacto_ cli for Windows devs, that also supports Ansi codes? I don't develop on Windows so I wouldn't know -- I trust your advice 🙏 

Regarding PS6 vs PS7, I installed PS6 this month. The only reason I didn't go for PS7 was because at the time it was on "Preview". Is it safe/stable to switch? Again, I'll use whatever you advise me to.

**Comment by iSazonov** [comment]
I don't understand why Windows PowerShell is on right side of your screenshot.

**Comment by dialex** [comment]
> I don't understand why Windows PowerShell is on right side of your screenshot.

What is it that you don't understand? Can you be more precise? On the right I have Windows Terminal, because I read somewhere that it was the "new and best" cli for Win. I don't know why Windows Terminal opens a PowerShell tab, your team mates might.

Did you read any of my previous questions? I'll try to be crystal clear:
- What is the standard/recommended cli for developers on Windows 10? 
- Or, what cli should a Java developer use on Windows (besides IntelliJ's cli)?

**Comment by jhoneill** [comment]
@dialex  It isn't a powershell thing.  
See https://devblogs.microsoft.com/commandline/new-experimental-console-features/ 

If your windows build is before 18298 the terminal doesn't support ansi codes. It doesn't matter if you run CMD, Windows PowerShell (5), PowerShell core (6) or the preview of 7, it's like the 1980s DOS without loading ANSI.SYS. 

If you have a 18298 or later OR if you install the new Windows terminal, again CMD, Windows PowerShell or PowerShell core. will all display as you want. The new terminal will do it better and a lot faster. 

It creates confusion when you say PowerShell core 6 in an old terminal doesn't do X but the older Windows PowerShell 5 in the new terminal does it.

**Comment by iSazonov** [comment]
@dialex For classic Windows console you should continue to use Jansi. New Windows terminal supports escapes and you can remove Jansi.
PowerShell is a shell, not console, and don't implement console features like escapes. PowerShell has a formatting system which would broke your application output - in this case let us know.

**Comment by DHowett-MSFT** [comment]
Hold up, what?

> If your windows build is before 18298 the terminal doesn't support ansi codes.

> For classic Windows Console you should...

This is entirely incorrect: the in-box standard windows console has supported ANSI (really, Xterm and VT100) since _build 10240_, which shipped almost four years ago.

The screenshot seems to show an application (java) not enabling `ENABLE_VIRTUAL_TERMINAL_PROCESSING`, a console mode that has existed since, again, build 10240.

Jansi probably enables that console mode, which is why it makes this work. God, I hope so: if it’s parsing VT sequences on its own it’s going to be terrible.

**Comment by DHowett-MSFT** [comment]
I’d love to learn which piece of documentation told you that 18298 was the build that enabled ANSI, so that my team can go fix it.

**Comment by jhoneill** [comment]
> Hold up, what?
> 
> > If your windows build is before 18298 the terminal doesn't support ansi codes. (@jhoneill)
> 
> This is entirely incorrect: the in-box standard windows console has supported ANSI (really, Xterm and VT100) since _build 10240_, which shipped almost four years ago.

> EDIT: looks like that’s our blog, but somebody has misinterpreted the feature we were releasing. That isn’t “experimental support for ANSI”, that is “experimental support for a split color palette and configurable cursor types”

I'll put my hand up if I misread that... knowing it hasn't _always_ worked but _has_ worked for a decent length of time I went back to check and got the wrong info, if I'd thought a bit harder it should have dawned on me that the post was much too late a date. But I think I reposted an error rather than making a whole new one

**Comment by DHowett-MSFT** [comment]
@jhoneill my bad. Thanks for clarifying :) Yeah, it looks like a classic error-carried-forward.

**Comment by dialex** [comment]
> The screenshot seems to show an application (java) not enabling `ENABLE_VIRTUAL_TERMINAL_PROCESSING`, a console mode that has existed since, again, build 10240.

That's my suspicion too @DHowett-MSFT (also thanks for joining the thread) 🙇 
Since that feature is experimental for 4 years, I _assumed_ that by now it was enabled by default.

**I'll try to enable it and report back the results.**

> It creates confusion when you say PowerShell core 6 in an old terminal doesn't do X but the older Windows PowerShell 5 in the new terminal does it.

Yup, I'm confused as well. I tried PS5, PS6, cmd inside this new Windows Terminal and all showed color ✅However, when I run them individually (outside Win Terminal) they don't show color ❌

If all fails, I can just recommend my devs to use Windows Terminal. 🤷‍♂ Is that fair?

With so many Win clis, **what is the officially recommended cli for developers on Windows 10?**

`<curiosity>`

- Is there something preventing the Windows team from enabling that feature by default, after this experimental time?
- I checked and Jansi is not enabling that feature (https://github.com/fusesource/jansi/issues/63), so they must do it some other way. I get it, they need to support Windows versions prior to 10.

`</curiosity>`

**Comment by dialex** [comment]
UPDATE: [I enabled the feature](https://github.com/dialex/JCDP/pull/44/commits/baa3b95af82db71e2017d967b6ffd08c9e2f74c1#diff-df3dc36270b358a02b972f5066b69a74R332), and now both PowerShell and Command Prompt display colors 😍 

For reference, here's how to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` using Java: https://github.com/dialex/JCDP/pull/44/commits/baa3b95af82db71e2017d967b6ffd08c9e2f74c1#diff-df3dc36270b358a02b972f5066b69a74R332
