### ISSUE TITLE
Get-Job -Name throws exception when name not found

### ISSUE THREAD

**Issue by rayzorben** [PowerShell/PowerShell#11450]
# Steps to reproduce

```powershell
$(Get-Job -Name MadeUpName -State Running -ErrorAction SilentlyContinue).Count

```

# Expected behavior

```none
Get-Job doesn't throw an exception when name is not found or there is a way to ignore it so that the count can be returned directly.
```

# Actual behavior

```powershell

Get-Job : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
At line:1 char:3
+ $(Get-Job -Name MadeUpName -State Running -ErrorAction SilentlyContinue).Cou ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-Job], ParameterBindingException
+ FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.GetJobCommand
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 5.4.4-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 17 Dec…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Currently I know you can workaround it by doing

```powershell
$(Get-Job | Where-Object {$_.Name -eq 'MadeUpName'}).Count
```
but that doesn't seem ideal.

**Comment by iSazonov** [comment]
Can you conform the issue is in latest PowerShell 7.0 bould?

**Comment by jhoneill** [comment]
It looks like the parameter sets for Get-Job don't allow Name and State to specified at the same time  (once you add NAME to the command line tab complete doesn't suggest STATE and Vice versa) that's why you get a parameter binding error.  Get-Job -? shows one syntax for requesting by state and another for requesting by name . 
I'm not saying the current design is good or bad , I can see a valid request to be able to combine the criteria, but that's not what is implemented now. 

"not found" isn't consistent. Get-Job -State running returns nothing on my machine [now]  but get-job -name "foo" gives a non terminating error. Again a case could be made to make all "not found" conditions the same ...

**Comment by rayzorben** [comment]
Sorry I might have pasted the wrong error, and found another issue. It is weird that you can't get 'all running jobs with a specific name' and I think that should be fixed.

But even without adding -State I still think I should be able to do `$(Get-Job -Name Foo).Count`

```powershell
PS /mnt/root> $(Get-Job -Name Foo).Count
Get-Job : The command cannot find the job because the job name Foo was not found. Verify the value of the Name parameter, and then try the command again.
At line:1 char:3
+ $(Get-Job -Name Foo).Count
+   ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Foo:String) [Get-Job], PSArgumentException
+ FullyQualifiedErrorId : JobWithSpecifiedNameNotFound,Microsoft.PowerShell.Commands.GetJobCommand

```

**Comment by rayzorben** [comment]
OK in latest 7.0 it seems consistent

```powershell
PS /opt/microsoft/powershell/7-preview> $(Get-Job -Name Foo).Count
Get-Job: The command cannot find the job because the job name Foo was not found. Verify the value of the Name parameter, and then try the command again.
0
PS /opt/microsoft/powershell/7-preview> $(Get-Job -Status Running).Count
Get-Job: A parameter cannot be found that matches parameter name 'Status'.
0
```

**Comment by iSazonov** [comment]
I guess you mean `Get-Job -State Running`.

**Comment by rayzorben** [comment]
> I guess you mean `Get-Job -State Running`.

Fixed :)

**Comment by SeeminglyScience** [comment]
> But even without adding -State I still think I should be able to do `$(Get-Job -Name Foo).Count`

Most `Name` parameters will write a non-terminating error when a matching item is not found **if** the specified name does not have wild cards.

```powershell
Get-ChildItem \doesnotexist
# Get-ChildItem: Cannot find path 'C:\doesnotexist' because it does not exist.

Get-ChildItem \doesnotexist*
# No error
```

The way most folks handle the case where you just want a count is by specifying `ErrorAction`:

```powershell
$jobCount = (Get-Job -Name MyJobName -ErrorAction Ignore).Count
```

I don't necessarily agree with this behavior, I wish that from the start anything that *could* accept wildcards would not write any errors (basically limiting that behavior to `LiteralName/Path` variants).  It wouldn't make sense to change this for a single cmdlet for consistency, so it would likely have to be a change made across the board.  That said, we've all worked around this behavior for so long that changing it how would break a whole lot of scripts.
