### ISSUE TITLE
Get-CimInstance : FAILED on PS Core 6.2.3. (zip)

### ISSUE THREAD

**Issue by rayden84** [PowerShell/PowerShell#11454]
I'm experiencing the same issue as #4466. I simply unzipped the powershell core 6.2.3 zip, as I did not wanted the additional dependencies installed when using the MSI package. The workaround/fix offered in https://github.com/PowerShell/PowerShell/issues/2777#issuecomment-343571939 doesn't work, the error still persists.

**Steps to reproduce**

```powershell
PS C:\Program Files\Powershell> Get-CimClass win32_process
```
**Expected behavior**

The requested cim object.

**Actual behavior**
```powershell
Get-CimClass : FAILED
At line:1 char:1
+ Get-CimClass win32_process
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-CimClass], CimException
+ FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,Micro
soft.Management.Infrastructure.CimCmdlets.GetCimClassCommand
```

**My environment**
```powershell
PS C:\Program Files\Powershell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Are there additional steps needed? I would very like know how the issue #4466 was resolved/closed, or better: why it does not work in my case!?

**Comment by iSazonov** [comment]
Have you Microsoft.Management.Infrastructure package installed?

**Comment by rayden84** [comment]
Invoking Get-Package results in:

```powershell
PS C:\Program Files\Powershell> Get-Package

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
Microsoft.Management.Infrastr. 1.0.0            C:\Program Files\PackageManagem. NuGet
```

I guess there must be some powershell core prerequisites which I don't meet and which I don't figure out

**Comment by iSazonov** [comment]
Can you repo with latest 7.0 build?

**Comment by rayden84** [comment]
Same behavior for v7.0.0-rc.1. However, according to this [serverfault thread](https://serverfault.com/questions/627386/what-version-of-windows-management-framework-is-installed) it seems that I do not meet the prerequisites (WMF version) for getting a cim instance

**Comment by SteveL-MSFT** [comment]
6.1 is Windows 7 which requires WMF since WMI that is included with WIndows 7 is too old to support the CIM cmdlets.  The install [instructions](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#prerequisites) indicate WMF4 (or newer, 5.1 preferred) is required for Win7.
