### ISSUE TITLE
Feature Request - ConvertTo-Html should auto create hyperlinks

### ISSUE THREAD

**Issue by StingyJack** [PowerShell/PowerShell#11458]
There are many times where I've had to go manually craft an `<a href="....` as a new property where the existing string property already had a valid URL in it, just so ConvertTo-Html would generate a hyperlink. 

Its non-intuitive for something that creates HTML to be unable to recognize url's and emit hyperlinks, It doesnt have to be a default action, but it would save the time and trouble of hand building `<a href` strings

**Comment by jackdcasey** [comment]
I think this would be a nice option as a switch! Something like `-createhyperlinks` but maybe a bit more concise. 

What do you guys think? 

I'd be happy to play around with this!

**Comment by kilasuit** [comment]
I think that this if it is looking for hyperlinks look for any allowable URI (as opposed to URL) 
@JJJcfff is this something that you could add in to your current PR please

**Comment by StingyJack** [comment]
that bot needs to be deprogrammed. I dont appreciate its attempt to derail or shut down this discussion.
