### ISSUE TITLE
Get-PSDrive doesn't display USB drives and other mounted partitions

### ISSUE THREAD

**Issue by jrydval** [PowerShell/PowerShell#11457]
# Steps to reproduce

insert formatted USB flash media into MacOS based machine
+
submit `Get-PSDrive` command

# Expected behavior

It should display also USB drive. At least based on the help text for `Get-PSDrive`:

> Also, beginning in Windows PowerShell 3.0, when an external drive is connected to the computer, PowerShell automatically adds a PSDrive to the file system that
>     represents the new drive. You do not need to restart PowerShell. Similarly, when an external drive is disconnected from the computer, PowerShell automatically
>     deletes the PSDrive that represents the removed drive.

`mount` sees it (see last line):

```
PS /Users/jan> mount
/dev/disk1s5 on / (apfs, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s1 on /System/Volumes/Data (apfs, local, journaled, nobrowse)
/dev/disk1s4 on /private/var/vm (apfs, local, journaled, nobrowse)
map auto_home on /System/Volumes/Data/home (autofs, automounted, nobrowse)
/dev/disk2s1 on /Volumes/Pulec (exfat, local, nodev, nosuid, noowners)

```

# Actual behavior

USB drive is not displayed:

```

PS /Users/jan> Get-PSDrive

Name           Used (GB)     Free (GB) Provider      Root                                                                                                 CurrentLocation
----           ---------     --------- --------      ----                                                                                                 ---------------
/                 155.46         78.01 FileSystem    /                                                                                                          Users/jan
Alias                                  Alias
Env                                    Environment
Function                               Function
Temp              155.46         78.01 FileSystem    /tmp/
Variable                               Variable

```

# Environment data

```
PS /Users/jan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by AdminTurnedDevOps** [comment]
I'm definitely able to get it on Windows with PowerShell 7.0.0-rc.1. Do you have a Windows VM or machine you can try it on? I'm curious so we can narrow down the culprit.

**Comment by jrydval** [comment]
I tested the same USB stick on my Windows 10 machine and there it works as expected (Drive E:):

```
PS C:\Users\jan> Get-PSDrive

Name           Used (GB)     Free (GB) Provider      Root                                                                                                                                                                                                                                                    CurrentLocation
----           ---------     --------- --------      ----                                                                                                                                                                                                                                                    ---------------
Alias                                  Alias
C                 969.89        936.05 FileSystem    C:\                                                                                                                                                                                                                                                           Users\jan
Cert                                   Certificate   \
E                  99.25         20.25 FileSystem    E:\
Env                                    Environment
Function                               Function
HKCU                                   Registry      HKEY_CURRENT_USER
HKLM                                   Registry      HKEY_LOCAL_MACHINE
Temp              969.89        936.05 FileSystem    C:\Users\jan\AppData\Local\Temp\
Variable                               Variable
WSMan                                  WSMan
```

**Comment by AdminTurnedDevOps** [comment]
Gotcha. Yeah, looks like it's something with the underlying OS. Hopefully they can fix the bug :)

**Comment by jhoneill** [comment]
On non windows machines what drive would you expect a USB stick to be. On Windows you have C: D: E:  But (showing my windows-centricity here) you don't get a new drive letter  / filesystem, the usb mounts into the existing / file system . So it is left to you to create and name a drive pointing somewhere in the existing FS.

**Comment by jrydval** [comment]
Hm, I would expect that it shows precisely the same (from conceptual point of view) as on Windows - a path to the drive - in my case on Mac _/Volume/Pulec_ on Windows _E:\_. 
Then I can use it for  `Set-Location` to be there.

**Comment by jhoneill** [comment]
A drive name can't contain   ; ~ / \ . : 
So you couldn't have a drive named /volume/Pulec. 
On Windows you have have multiple file systems which don't (by default) mount into one unifying one (hence they begin with A: B: C:  etc.). PowerShell doesn't _create_ a drive named "E", it recognizes "E" as a system drive.  If you connect Z: to \\localhost\c$  outside PowerShell, it shows up as a PS drive. PS Drives is Aliases + Environment + Functions + Variables + filesystems known to the OS +  Windows' Registry + Certificates + WSMAN
On Unix-derived OSes there is one unified fs in which other file systems mount. Because there isn't a new file system root there is no drive to add. You can make a Windows style drive (so in WSL I can create a PS drive 'C' for /mnt/c ) or one can make a short name for a mounted USB.  But there wouldn't be much point in in creating a psdrive Volume_Pulec in order to allow `set-Location volume_pulec: ` instead of `set-Location /volume/pulec `

**Comment by jrydval** [comment]
You know, I would welcome a parity between Windows and MacOS and Linux behaviour and ability to use a generic way how to recognise that there is a new drive or portable media attached.

What about this:

Now:
```
PS /Users/jan> Get-PSDrive | where -Property Provider -eq (Get-PSProvider -PSProvider FileSystem) | Select-Object -Property Name,Root

Name Root
---- ----
/    /
Temp /var/folders/g0/62pyd9wn0zbg0sqsrjb8_5kr0000gn/T/
```

After:

```
PS /Users/jan> Get-PSDrive | where -Property Provider -eq (Get-PSProvider -PSProvider FileSystem) | Select-Object -Property Name,Root

Name  Root
----  ----
/     /
Pulec /Volume/Pulec
Temp  /var/folders/g0/62pyd9wn0zbg0sqsrjb8_5kr0000gn/T/
```

**Comment by scaleoutsean** [comment]
I have two (external) SCSI disks, /dev/sdb and /dev/sdc, mounted as ext4 filesystems on Ubuntu 20.04. 

```pwsh
PS /home/sean> df | grep sd
/dev/sda1                   523248       4    523244   1% /boot/efi
/dev/sdb                   9546944 3476936   5565332  39% /data
/dev/sdc                   9546944   36888   9005380   1% /mnt/361

PS /home/sean> Get-PSDrive

Name           Used (GB)     Free (GB) Provider      Root                                                                                                     CurrentLocation
----           ---------     --------- --------      ----                                                                                                     ---------------
/                   7.86         14.17 FileSystem    /                                                                                                              home/sean
Alias                                  Alias                                                                                                                                 
Env                                    Environment                                                                                                                           
Function                               Function                                                                                                                              
Temp                7.86         14.17 FileSystem    /tmp/                                                                                                                   
Variable                               Variable

PS /home/sean> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I tried 7.2.0 Preview 5 and also as `root`, no difference.

**Comment by jhoneill** [comment]
@scaleoutsean 

That's expected behaviour.  The Term "Drive" is inherited from  windows as analogous to "root-of-a-[pseudo]-file-system" 
Your filesystems on those disks are mounted into part of the / "drive",  they aren't roots in their own right as they would normally be on Windows.     

You **can** create new drives for places in the /  tree   for example
`New-PSDrive -Name C -PSProvider FileSystem -Root /mnt/c`  
Would present a C: drive on pwsh if that is a more convenient way to work.  But that is in addition to where the OS places them - on Linux system you'd expect to find them mounted somewhere under / wouldn't you ? And native Linux tools would probably demand you use the path from / not a C: style one.

**Comment by scaleoutsean** [comment]
Thanks @jhoneill! I was aware of the term/concept, but thought addition was automatic similar to native `udisks` or other behavior on Linux. 
The command does work as you said, but it ignores the presence of actual filesystem (e.g. `361` isn't mounted) so it seems of limited use that way.

```pwsh
PS > Get-PSDrive -PSProvider FileSystem -Debug

Name           Used (GB)     Free (GB) Provider      Root                                                                                                     CurrentLocation
----           ---------     --------- --------      ----                                                                                                     ---------------
/                   8.09         13.95 FileSystem    /                                                                                                              home/sean
359                 3.80          5.31 FileSystem    /data                                                                                                                   
361                 8.09         13.95 FileSystem    /mnt/361/
```

After actually mounting /dev/sdc to /mnt/361 and recreating this PSDrive, now indirectly (e.g. by looking at `Used (GB)`) we see it's a different situation.

```pwsh
PS > Get-PSDrive

Name           Used (GB)     Free (GB) Provider      Root                                                                                                     CurrentLocation
----           ---------     --------- --------      ----                                                                                                     ---------------
/                   8.09         13.95 FileSystem    /                                                                                                              home/sean
359                 3.80          5.31 FileSystem    /data                                                                                                                   
361                 0.52          8.59 FileSystem    /mnt/361/                                                                                                               
```

Anyway, this appears to be a different topic and off topic for this issue - sorry about that. I wasn't able to find much documentation on how this is supposed to work on Linux so I thought these are related. Please ignore these comments I made.
