### ISSUE TITLE
DnsRefreshTimeout Invalid

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11467]
**Suppose**:  I try to monitor DNS changes for a site,Or, when I change DNS, I need to know when it will take effect.I need to turn off the dns cache for real-time monitoring purposes。

I found the following options with 'bing' but it didn't work，The timeout cannot be set。This option is not valid
```powershell
[System.Net.ServicePointManager]::DnsRefreshTimeout=0
```
I tried to get ip from remote dns, but returned locally
```powershell
[System.Net.Dns]::GetHostAddresses('powershell.com')
```

----
I want to know how to turn off the dns cache, or get it directly from the network。

**Comment by iSazonov** [comment]
It is not PowerShell related. Please ask in .Net Core runtime repo.
