### ISSUE TITLE
Typing "pwsh" in Start doesn't launch PS Core 6

### ISSUE THREAD

**Issue by patrikhuber** [PowerShell/PowerShell#11460]
# Steps to reproduce

I read and followed https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6 and installed PS Core 6 with `dotnet tool install --global PowerShell`. I can confirm that `C:\Users\MyUser\.dotnet\tools` is in my user's PATH. I can also launch it by typing "pwsh" in a `cmd.exe` or in the "old" powershell prompt. `Get-Command pwsh` (from the old PowerShell) returns `C:\Users\MyUser\.dotnet\tools\pwsh.exe`.

However, when typing "pwsh" into Start (the start menu - i.e. pressing the Windows key and then starting to type), it doesn't appear in the start menu - even after waiting. The only thing that appears is the web search and when I press Enter, Edge opens with Bing.

I also rebooted my system, and it didn't help.

# Expected behavior

PS Core should launch, i.e. Start should recognise pwsh, like the documentation says it would.

# Actual behavior

See above.

# Environment data

```
echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Do dotnet tools normally get recognised by the start menu? Typically that kind of install is tailored to CLI use as far as I'm aware.

@adityapatwardhan will probably answer it better than I could, but I do wonder if this is expected behaviour from this type of installation. 🙂

**Comment by patrikhuber** [comment]
@vexx32 I could swear that docs.microsoft.com somewhere said that after PS Core is installed, it can be started by typing "pwsh" in Start.

**Comment by patrikhuber** [comment]
And the old/classical PowerShell is also found by typing "Po" in Start and hitting enter. Same for cmd.

**Comment by vexx32** [comment]
Yep. The `dotnet tool` installation is a specialized install, though, so I'm thinking it might be expected to be a bit different. 

Installing it as a regular application works correctly and it will show up in the Start menu.

**Comment by patrikhuber** [comment]
I see! With "installing it as a regular application", do you mean installing it from the MSI package https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6#installing-the-msi-package?
If so then thank you and that's what I will do next time :-)

**Comment by vexx32** [comment]
Yeah, sorry if that wasn't clear; the MSI or MSIX installers behave more as you'd expect. I'm not sure whether the dotnet tool method is _supposed_ to show in the start menu or not, but I'm sure the PS Team can answer that better than I. 🙂

**Comment by patrikhuber** [comment]
Great :) I just went with the dotnet tool method because it's highlighed in a very visible green at the very top of the documentation page, so I assumed it's the easiest (it is indeed the easiest) and recommended method for all "normal" (i.e. desktop/developer machine) uses.
But it seems like for a desktop/developer machine for someone who is looking to replace the old PowerShell with the new PS Core system-wide, as their main system shell, it's better to use the MSI/MSIX.

I am very happy to close this issue, thank you very much for the advice @vexx32!
I'll leave the closing up to you, in case you/the team further wants to investigate the behaviour or make the docs a bit clearer or something along those lines.

Cheers and happy new year :)

**Comment by vexx32** [comment]
Thanks! :blush:

@adityapatwardhan @sdwheeler you folx may want to clarify in the documentation if there are differences in behaviour with the dotnet tool installation. Easy installation is good, but we need to be mindful that users may have particular expectations that a specialised installation may not conform to entirely. 🙂

**Comment by iSazonov** [comment]
For the application to appear in Start menu you need to create a shortcut in a special folder (user-wide or system-wide). Global tools do not create such shortcut.
