### ISSUE TITLE
new keyword "loop"

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11469]
instead of for dracula for(;;) or while($true) it more lisible to use loop for infinite loop

```
loop {
  
}
```

**Comment by jhoneill** [comment]
Generally loops need a Goto or equivalent (like break) to exit are considered bad.

**Comment by bpayette** [comment]
@p0W3RH311 Also note that adding new keywords is considered a breaking change since someone may already have defined a `loop` command.
