### ISSUE TITLE
User profile isn't created automatically

### ISSUE THREAD

**Issue by EwertonJordao** [PowerShell/PowerShell#11477]
# Install PWSH rc 1 on debian or ubuntu
run pwsh
vim $Profile
edit profile 
exit profile with :wq 
and receive an error about permission, if not exist a subdirectory on /root/.config/... I receive error but I think when an install Powershell made this path need to exist 

```powershell

```

# Expected behavior

```none

```

# Actual behavior

```none

```

# Environment data

```none

```

**Comment by iSazonov** [comment]
Please create more useful issue header.
Can you share the error screenshot?

**Comment by EwertonJordao** [comment]
@iSazonov 

Ok, after install powershell in wsl 1, when i try to edit $profile file i recive this error

![image](https://user-images.githubusercontent.com/12378570/71732869-09b9df80-2e27-11ea-8333-cee30178cb61.png)

********************************************
Invoke pwsh-preview in wsl

run 
New-Item -Path /root -Name .config -ItemType Directory
New-Item -Path /root/.config -Name powershell  -ItemType Directory

Create folder estruture 

Run 
pwsh-preview
cd /root/.config/powershell
vim $profile

Edit content and save.  ESC  :wq

![image](https://user-images.githubusercontent.com/12378570/71734024-b4330200-2e29-11ea-9726-9f52b29b5d22.png)

![image](https://user-images.githubusercontent.com/12378570/71734079-d0cf3a00-2e29-11ea-98a3-4830a59cd33a.png)

**Comment by iSazonov** [comment]
@TylerLeonhardt Could you please comment the issue?

**Comment by EwertonJordao** [comment]
No, I saw the same issue in Windows Terminal with wsl.

**Comment by TylerLeonhardt** [comment]
This is likely because the `~/.config/powershell` doesn't exist because PowerShell doesn't create it. (`$profile`) has always been just a file path whether that file was created or not.

If you create that folder, this should work.

**Comment by TylerLeonhardt** [comment]
Actually you said that you did that... If you open vim with sudo, does it work?

`sudo vim $Profile`

This seems like a permissions issue. I notice you're user account is root...

**Comment by EwertonJordao** [comment]
@TylerLeonhardt 

Yep, I'm root. But I need to create a folder to it works. $profile on windows it`s a path exists if you use this or not, I think this is the default behavior for all user PowerShell. We don`t need to create a folder to customize initialize.

I use "sudo vim $profile" but I saw the same error.

![image](https://user-images.githubusercontent.com/12378570/71771466-fb002500-2f19-11ea-9ced-a34e0c93a965.png)

**Comment by SteveL-MSFT** [comment]
The user $profile is not created by default.  You can do something like:

```powershell
new-item -type file -path $profile -force
```

This will create the path and the file (and clobber any existing one).

**Comment by EwertonJordao** [comment]
Cool, but why not create the path automatically when installed pwsh? 

Tks for help
