### ISSUE TITLE
Show-Markdown -UseBrowser Fails in Snap

### ISSUE THREAD

**Issue by Christopher-St** [PowerShell/PowerShell#11476]
# Steps to reproduce

```powershell
"# This Does Nothing" | Show-Markdown -UseBrowser 
```

# Expected behavior
Open markdown as converted html page inside of default browser, similar to behavior of online help:  `Get-Help Show-Markdown -Online`.  

# Actual behavior
Does not open browser, writes no output, and continues without error. 

# Environment data

Also tested inside snap preview version 7.0.0-rc.1. 
```none
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Issue might be snap confinement interfering with `xdg-open`. corefx `Process.Start()` on Linux relies on `xdg-open`, which isn't working on local files when called from powershell snap. I ran: `xdg-open test.html` from both powershell and bash. Successfully opens the default browser in bash, but does nothing in powershell.

**Comment by iSazonov** [comment]
@adityapatwardhan Could you please comment the issue?

**Comment by Christopher-St** [comment]
Snap looks guilty. With powershell installed as a dotnet global tool  `-UseBrowser` works as expected, as does `xdg-open test.html`.

**Comment by iSazonov** [comment]
I'd expect that this works.

**Comment by iSazonov** [comment]
@SteveL-MSFT Cpild you please triage the issue?
