### ISSUE TITLE
Make "Invoke-Command" return a Hashtable with PSComputerName as the key

### ISSUE THREAD

**Issue by jantari** [PowerShell/PowerShell#11472]
# Summary of the new feature/enhancement

Add an `-AsHashTable` parameter to `Invoke-Command`, so that results are "grouped" (keyed) by PSComputerName.

This would be very helpful to me when querying many computers in parallel,
as indexing into the hashtable like this:

```
$InvokeCommandResults["$ComputerIWant"]
```

is neater and faster than using

```
$InvokeCommandResults.Where{ $_.PSComputerName -eq "$ComputerIWant" }
#and 
if ($InvokeCommandResults.PSComputerName -contains "$ComputerIWant") { <# #> }
```

it also avoids the performance-trap of users accidentally doing:

```
$InvokeCommandResults | Where-Object { $_.PSComputerName -eq "$ComputerIWant" }
```

# Proposed technical implementation details (optional)

**Comment by vexx32** [comment]
Does this add significant value above and beyond what you can already get with Group-Object?
```powershell
$results = Invoke-Command -ComputerName $computerList -Scriptblock $command |
    Group-Object -AsHashtable -Property PSComputerName
```

**Comment by jantari** [comment]
Ah, this is what I get for submitting feature ideas immediately when I get them, so I don't forget, instead of thinking about it for longer.

So, there is not much immediate benefit compared to piping to `Group-Object` - I think.

The only thing to consider is the question of whether it makes sense to default to a hashtable or not.

Personally, I find it a more ergonomic solution and don't see any usability benefit in the `.PSComputerName` implementation.

I am however not too familiar with the implementation details, e.g.:

1. How much CPU time does it cost to add/wrap the PSComputerName property on all returned objects? I imagine sticking them into a Hashtable untouched should be really fast
2. How would memory usage compare between an array of objects with an extra property VS a hashtable?
3. Is the extra property/adding to hashtable done on the client side or the remote computer? Does it matter?
4. Very few PowerShell cmdlets return hashtables - unexpected behavior?

**Comment by SeeminglyScience** [comment]
> Ah, this is what I get for submitting feature ideas immediately when I get them, so I don't forget, instead of thinking about it for longer.

Nothing wrong with that :) much better than never submitting them!

> The only thing to consider is the question of whether it makes sense to default to a hashtable or not.
> 
> Personally, I find it a more ergonomic solution and don't see any usability benefit in the `.PSComputerName` implementation.

The main problem with that is formatting.  With how it is now, you can interactively run a command on several machines and then see the full results for each (and from what computer they came from).

> I am however not too familiar with the implementation details, e.g.:
> 
> 1. How much CPU time does it cost to add/wrap the PSComputerName property on all returned objects? I imagine sticking them into a Hashtable untouched should be really fast
> 2. How would memory usage compare between an array of objects with an extra property VS a hashtable?

The hashtable scenario might actually be worse (though minimally). The collections that store properties for an object will already be allocated.  The internal array for the collection might need to be resized to fit the extra property, but the `hashtable` and the collections it stores as values will need to be resized probably multiple times.

> 3. Is the extra property/adding to hashtable done on the client side or the remote computer? Does it matter?

Both are or would need to be done on the client side.

> 4. Very few PowerShell cmdlets return hashtables - unexpected behavior?

Kinda.  Hashtables are formatted with a key column and a value column.  It doesn't handle arrays of complex objects very well in either column.

**Comment by bpayette** [comment]
@SeeminglyScience 
>  It doesn't handle arrays of complex objects very well in either column.

Hi Patrick, I'm curious. Arrays as keys don't work very well but I'm not aware of any issues with using arrays as values. Can you expand on this?

@jantari 
There's one huge advantage to returning objects with the host name as a property on the object: it allows streaming. In other words, you get objects from remote machines as soon as they are available. Returning something like a hashtable would stall the whole process until the very last record is received from the very last machine. (But if you do want that, you can use `Group-Object` as the others have mentioned.)

Also, remote operations return deserialized objects (PSObject) which are essentially a wrapper around a hashtable so adding the hostname as a property doesn't really add significant overhead.

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience
> 
> > It doesn't handle arrays of complex objects very well in either column.
> 
> Hi Patrick, I'm curious. Arrays as keys don't work very well but I'm not aware of any issues with using arrays as values. Can you expand on this?

Ah thank you, yeah that wasn't clear.  They work just fine, I'm only referring to the formatting differences.  Not that there is anything wrong with hashtable's formatting, it definitely makes sense for what it is.  Just less useful as an output type interactively.

```powershell
$sb = { @([PSCustomObject]@{ Prop = 1; Prop2 = 2 }) * 2 }

Invoke-Command -ComputerName localhost -ScriptBlock $sb |
    Group-Object -AsHashTable -Property PSComputerName

# Name                           Value
# ----                           -----
# localhost                      {@{Prop=1; Prop2=2; PSComputerName=localhost; RunspaceId=e6d63fb4-3f84-4144-a277-ad44692bfcee; PSShowComput…

Invoke-Command -ComputerName localhost -ScriptBlock $sb |
    Format-Table -Property Prop1, Prop2, PSComputerName

# Prop Prop2 PSComputerName
# ---- ----- --------------
#    1     2 localhost
#    1     2 localhost
```

**Comment by bpayette** [comment]
@SeeminglyScience That's what I expected but I wanted to be sure. Thanks.
