### ISSUE TITLE
$ErroractionPreference with scriptblock

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11488]
its possible to have a scriptblock to conditionally break script
```

$ErroractionPreference = {
   # $_ is instance of $error[0]
   if($_.exception -is [ItemNotFoundException] -and $_.Exception.ItemName.Contains('system')) {
      break 
   }
}


# some code here
gi k:\system\foo
```

**Comment by iSazonov** [comment]
You could use ErrorAction Stop and try-catch.

**Comment by p0W3RH311** [comment]
yes i know but $erroractionpreference in top of script reduce the case of use try/catch and the effect is global

**Comment by iSazonov** [comment]
We have RFC https://github.com/PowerShell/PowerShell-RFC/blob/9d0b313c76144e9af7b84294bba470da710810e8/1-Draft/RFCNNNN-ScriptBlock-Action-Preference.md#add--verboseaction--debugaction-and--progressaction-common-parameters
/cc @KirkMunro

**Comment by rkeithhill** [comment]
You can also use the `trap` statement to install a single error handler for a script:
```
& {
    trap {
        if ($_.Exception -is [System.Management.Automation.ItemNotFoundException] -and
            $_.Exception.ItemName.Contains('system')) {
            "Couldn't find item with 'system' in the path"
            break
        }
        else {
            "Could not find $($_.Exception.ItemName) but hey, it's OK. Let's keep going."
            continue
        }
    }

    Get-Item k:\foo -ErrorAction Stop

    Get-Item k:\system\foo -ErrorAction Stop
}
```

**Comment by p0W3RH311** [comment]
> 
> 
> You can also use the `trap` statement to install a single error handler for a script:
> 
> ```
> & {
>     $ErrorActionPreference = 'Stop'
>     trap {
>         if ($_.Exception -is [System.Management.Automation.ItemNotFoundException] -and
>             $_.Exception.ItemName.Contains('system')) {
>             "Couldn't find item with 'system' in the path"
>             break
>         }
>         else {
>             "Could not find $($_.Exception.ItemName) but hey, it's OK. Let's keep going."
>             continue
>         }
>     }
> 
>     Get-Item k:\foo
> 
>     Get-Item k:\system\foo
> }
> ```

but this code not break in specifik error


```
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS > cat .\n.ps1
& {
    $ErrorActionPreference = 'Stop'
    trap {
        if ($_.Exception -is [System.Management.Automation.ItemNotFoundException
] -and
            $_.Exception.ItemName.Contains('system')) {
            "Couldn't find item with 'system' in the path"
            break
        }
        else {
            "Could not find $($_.Exception.ItemName) but hey, it's OK. Let's kee
p going."
            continue
        }
    }

    Get-Item k:\foo

    Get-Item k:\system\foo
}
PS > .\n.ps1
Could not find k but hey, it's OK. Let's keep going.
Could not find k but hey, it's OK. Let's keep going.
PS >
```

**Comment by rkeithhill** [comment]
It is likely you are getting the same error for both:
```
Error is Cannot find drive. A drive with the name 'k' does not exist.
```
Change `Get-Item k:\system\foo` to `Get-Item c:\system\foo` (ditto for k:\foo) and try again.  With that change to the script I get:
```
12> .\n.ps1
Could not find k:\foo but hey, it's OK. Let's keep going.
Couldn't find item with 'system' in the path
Get-Item: C:\Users\Keith\n.ps1
Line |
  17 |     Get-Item c:\system\foo
     |     ^ Cannot find path 'C:\system\foo' because it does not exist.
```
