### ISSUE TITLE
implement Fuzzy Searching in cmdlet

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11487]
Fuzzy Searching  is powerful because often text data is messy. For example, shorthand and abbreviated text are common in various data sets we want to be able to make the most of our data by extrapolating as much information as possible. 

for example:

```
gcm Get-Difference -syntax

Get-Difference [-Algorithm <Levenshtein|Soundex|Trigram>]  [-String1] <string> [-String2] <string>
[-CaseSensitive] [-Similarity <int>]

Get-Difference [-Algorithm <<Levenshtein|Soundex|Trigram>>]  [-String1] <string> [-String2] <string[]>
[-CaseSensitive] [-Similarity <int>]


Get-Difference 'strng' 'string'

cat db.txt | Get-Difference 'bug' -alg soundex -sim 2
```

**Comment by iSazonov** [comment]
What kind of scenarios for which it should have been in the base repository and not in PowerShell Gallery?

**Comment by p0W3RH311** [comment]
> 
> 
> What kind of scenarios for which it should have been in the base repository and not in PowerShell Gallery?


abstraction in powershell is good but sometimes we need specific tool for example Format-Hex..etc. get-difference is good tool and it can be grouped with measure-object/group-object...

**Comment by iSazonov** [comment]
I don't see scenarios where we could use the Get-Difference cmslrt but we could add fuzzy match option in Select-String, Sort-Object, Group-Object.

**Comment by p0W3RH311** [comment]
> 
> 
> I don't see scenarios where we could use the Get-Difference cmslrt but we could add fuzzy match option in Select-String, Sort-Object, Group-Object.

powershell dont have a search engine with fuzzy match cmdlet or option . many algorithm with fuzzy match is used like in PSCommandNotFoundSuggestion feature and probably in other scenario in future. fuzzy match in powershell help user in cases of creation search engine or introduce ps in semantic match...etc

**Comment by lahell** [comment]
There is already a decent module for this in PowerShell Gallery called Communary.PASM.

**Comment by iSazonov** [comment]
For reference https://github.com/gravejester/Communary.PASM

**Comment by SteveL-MSFT** [comment]
`Get-Command` already has a `-UseFuzzyMatching` switch now
