### ISSUE TITLE
Clear-Host outputting space as part of function

### ISSUE THREAD

**Issue by cbattlegear** [PowerShell/PowerShell#11481]
# Steps to reproduce
```
function CameronIsAngry(){
    Clear-Host
    return $false
}

Write-Host "Is Cameron Angry?`r`n"

$response = CameronIsAngry
foreach ($obj in $response){
    Write-Host "'$($obj)' is the value and type of" $obj.GetType()
}

if ($response) {
    Write-Host "Hell Yeah he is!!" -ForegroundColor Red
} else {
    Write-Host "He Happy!!" -ForegroundColor Green
}
```

# Expected behavior

```
'False' is the value and type of System.Boolean
He Happy!!
```

# Actual behavior

```
' is the value and type of System.String
'False' is the value and type of System.Boolean
Hell Yeah he is!!
```

# Environment data
```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.4.0-19025-Microsoft #1052-Microsoft Mon Nov 18 14:41:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mkht** [comment]
I can't reproduce it on Windows. 🤔 

### Output
```
'False' is the value and type of System.Boolean
He Happy!!
```

### PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Screenshot
![image](https://user-images.githubusercontent.com/25482642/71738742-e3ce2280-2e9a-11ea-8812-cbb4e8a1d4b4.png)

**Comment by cbattlegear** [comment]
Strange! This may be linux specific as I initially was running into it on Azure Cloud Shell and then tested locally via Ubuntu (with Linux Subsystem).

**Comment by iSazonov** [comment]
We use follow code:
https://github.com/PowerShell/PowerShell/blob/c4e144b13e1209a6a723160d38be9f11ab45b8da/src/System.Management.Automation/engine/InitialSessionState.cs#L4179-L4181

You could manually run it and investigate where the space comes from..

**Comment by cbattlegear** [comment]
This makes more sense now, since it is running /usr/bin/clear all that is doing is sending ANSI control codes. You can observe exactly what is being output by running:

```
$out = & (Get-Command -CommandType Application clear | Select-Object -First 1).Definition
$out | Format-Hex
```
Which gives an output of
```
                       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
00000000000000000000   1B 5B 33 4A 1B 5B 48 1B 5B 32 4A                 .[3J.[H.[2J
```

Which essentially translates to clear screen, move cursor to home, clear screen. 

If you output that string into a file and output it in PowerShell in Windows you also get extra spaces when the screen is cleared. 

What this seems to land on is when PowerShell encounters an ANSI control character it outputs a blank. Why it does this is beyond me at the moment.

**Comment by cbattlegear** [comment]
Actually I took this a step further, wrote a quick test application in dotnetcore. 

Using Console.Write with the control characters outputs an extra line. Running /usr/bin/clear with Process.Start does not have the extra line.

Assuming we push everything out to console with Console.Write this may be an issue with dotnetcore.

**Comment by iSazonov** [comment]
@cbattlegear Thanks! If you can repo on C# please open new issue in .Net Core Runtime repository.
