### ISSUE TITLE
join operator with startIndex and count

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11490]
static method join have a startIndex and count its possible to have the same in join operator

```
PS C:\> [string]::Join

OverloadDefinitions                                                                                         
-------------------                                                                                         
              
static string Join(string separator, string[] value, int startIndex, int count)      
```                       

example

```
$s = 1..9
$s -join '.',2,5
# 3.4.5.6.7
```

**Comment by bpayette** [comment]
Putting extra stuff on the ends of an operation argument is not very intuitive (For example, I know extra options exist for `-match` and `-replace` by I still have to look them up.) Also be aware that `-join` has a unary form that joins all of the arguments to the right
```powershell
-join "a","b","c"
```
and actually so does the binary form:
```powershell
 $s -join "a","b","c"
1a b c2a b c3a b c4a b c5a b c6a b c7a b c8a b c9
```
so this would be a breaking change all up.

**Comment by vexx32** [comment]
@bpayette the binary form doesn't allow multiple RHS arguments. What you're seeing there is the array `"a", "b", "c"` being joined on `$OFS` (default: space) and used as a string rather than multiple arguments.

**Comment by SeeminglyScience** [comment]
I don't think this makes sense for PowerShell.  The method overload makes sense for optimization, you don't really want create a whole new array just to pass as an argument.  PowerShell generally doesn't care much about that, and if you really need that level of optimization then the method is available to you.

Instead, this currently works and for the majority of cases would be preferable imo:

```powershell
$s[2..7] -join '.'
```

Yeah it gets a lot more obtuse when the length is dynamic, but I think it would make more sense to improve that syntax than to add index/length to the operator.  I believe there is an issue/RFC open somewhere about making slicing with the range operator easier.

**Comment by BrucePay** [comment]
@vexx32 
> array "a", "b", "c" being joined on $OFS (default: space) and used as a string rather than multiple arguments.

That's how "multiple" arguments to a binary operator works.  There is no special syntactic support. The operator just receives left and right operands. It's then up to the operator implementation to interpret those arguments.  For example, the `-replace` operator checks to see if its RHS is a non-string  `IEnumerable` and if it is, parses it as a value + replacement string:
```powershell
{master}PSCore (1:103) >  "abcd" -replace "[ac]","|"
|b|d
{master}PSCore (1:104) >  $a = "[ac]","|"
{master}PSCore (1:105) >   "abcd" -replace $a
|b|d
```
Going back to the issue at hand, `-join` already has defined behaviour if the RHS is an `IEnumerable` so adding any interpretation to those values would be a breaking change.
