### ISSUE TITLE
ConsoleGUI

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#11495]
# Summary of the new feature/enhancement

We could consider https://github.com/TomaszRewak/C-sharp-console-gui-framework as output layer for PowerShell Core to get: 
- Coloring
- Progress bar like Windows PowerShell on Unix-es
- Alternatives graphical cmdlets like Show-Command and Show-GridView
- clickable Help
- and more, more, more

# Proposed technical implementation details (optional)

I was very surprised to see that ConsoleGU size is very small.
Currently we have a console implementation internally in PowerShell Core so integration with ConsoleGU does not have to be complicated.

/cc @SteveL-MSFT @daxian-dbw for information.

**Comment by daxian-dbw** [comment]
I had been looking into https://github.com/migueldeicaza/gui.cs for some time. Will take a look at this project too.

**Comment by SteveL-MSFT** [comment]
Closing as work is happening here https://github.com/PowerShell/GraphicalTools/tree/master/src/Microsoft.PowerShell.ConsoleGuiTools
