### ISSUE TITLE
Active Directory PSDrive Not Created in PS7

### ISSUE THREAD

**Issue by rgroefer** [PowerShell/PowerShell#11498]
# Steps to reproduce

```powershell
Import-Module ActiveDirectory
Set-Location AD:

```

# Expected behavior

```none
PS AD:\>
ActiveDirectory module gets imported and the AD: PSDrive gets created.
Locations sets to AD:
```

# Actual behavior

```none
ActiveDirectory module imports, but the PSDrive AD: is not created.
Set-Location: Cannot find drive. A drive with the name 'AD' does not exist.

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



```

**Comment by MaximoTrinidad** [comment]
There are a few things I just found out.

You're on Windows 10 Build 17763 and, I'm assuming, you are using ActiveDirectory module version 1.0.0.0.  This version seems not to work with PowerShell 7 Rc.1.

Now, if you have a chance to work with Windows Server 2019 then ActiveDirectory module version 1.0.1.0 will work in PowerShell 7 Rc.1.

![AD_Win2K19_01_2020-01-06_17-07-44](https://user-images.githubusercontent.com/19892435/71856136-fb7ef400-30b0-11ea-9e4a-75e93182d689.png)

Unfortunately, I haven't been able to successfully install the latest version of ActiveDirectory, as it's part of the FOD image, and instruction are hard to use. 

So, if you have access to a Windows Server 2019, then I suggest to use implicit remoting to use the module from the server on your desktop system (as a workaround).

**Comment by iSazonov** [comment]
I'd suggest to use latest version of AD module too.

**Comment by doctordns** [comment]
I can confirm that the AD module loads properly in Windows Server 2019 and works well!

Sadly, the ADDS Deployment module a) does NOT work by default and b) has issues with running in the current compatibility solution also does not work to add  DCs to a domain and creating a child domain. But there is a good workaround.

**Comment by MaximoTrinidad** [comment]
Hi @iSazonov 

Where can I find instructions to load the latest AD module version (1.0.1.0)?  I tried using the iso FOD mounted to install the RSAT but instructions and examples are not easy to use. 
:)

**Comment by iSazonov** [comment]
@MaximoTrinidad I did not tried manually install RSAT in last some months but I think it works like before:
- download and mount FoD iso that matches your Windows image version
- temporary disable WSUS in Registry
- use dism /Online /add-capability /LimitAccess
https://social.technet.microsoft.com/Forums/en-US/1509c5e9-e8ad-4f6c-9f2d-5b1f759fe906/windows-10-1809-rsat?forum=win10itprosetup

Also see "FODs with satellite packages:" topic in https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-v2--capabilities

**Comment by doctordns** [comment]
Is there any chance of getting modules like this published to the PS Gallery?

**Comment by iSazonov** [comment]
@doctordns It is unlikely because it is _Windows component_.

**Comment by MaximoTrinidad** [comment]
@iSazonov and @doctordns 

Oh Well!  I tried those instructions and sadly got me nowhere.

So, I did the unforgiven workaround:

 *On my AD Server*
- Created a shared folder on my AD Windows Server 2019.
- Then, copy the server ActiveDirectory Module to the shared folder.

*In Windows 10*
- On my Windows 10 Client, I have mapped the AD Shared folder on my Windows 10.
- Then, renamed ActiveDirectory (v 1.0.0.0) Module folder to ActiveDirectory_old.
- Finally, copy from the AD mapped folder, ActiveDirectory (v 1.0.1.0) into the folder: 
C:\windows\system32\WindowsPowerShell\v1.0\Modules.

I'm sorry but this was quick and less time-consuming. 

And, ... It works for me!

![AD_v10101_01_2020-01-07_16-07-44](https://user-images.githubusercontent.com/19892435/71929863-8e2e9a00-3168-11ea-8403-e6f2e9d2b49d.png)

**Comment by MaximoTrinidad** [comment]
@doctordns 

Great News! I needed to update this issue.

I just notice that in Windows 10 Build 1909 recent has the updated ActiveDirectory module to version 1.0.1.0 which can be used in PowerShell 7 Rc.1.

Look in the "App or remove programs | Optional Features" then look under "Add a feature" for the "RSAT: Active Directory Domain Services and Lightweight Directory Services Tools".

I had version 1.0.0.0 installed and it was replaced with the newer one.

It works!

![ADModule_04_2020-01-15_18-46-55](https://user-images.githubusercontent.com/19892435/72482539-0f6ed800-37cc-11ea-9c7b-49578cd2a1c9.png)

**Comment by doctordns** [comment]
Good news Max!

**Comment by rgroefer** [comment]
I appreciate the quick responses.  I wish I could say that worked for me, but it didn't.  I installed the Windows Optional Feature RSAT which replaced the older 1.0.0.0 version with the newer 1.0.1.0.  So the module is there and I tested it in Windows PowerShell 5.1.

WindowsPowerShell 5.1 imports the ActiveDirectory module just fine, but PowerShell 7.0.0.0-rc.2 does not.

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

![ActiveDirectoryFail](https://user-images.githubusercontent.com/35051290/72819830-f0dd6680-3c3b-11ea-9d40-2793cae65c7a.png)

**Comment by vexx32** [comment]
@rgroefer it looks like the version of the Active Directory module you can get depends on your Windows version -- make sure you're as up to date as possible there; as @MaximoTrinidad mentions, version 1909 seems to come with the fix for the module. 🙂

**Comment by rgroefer** [comment]
Using the -UseWindowsPowerShell switch helps though

![image](https://user-images.githubusercontent.com/35051290/72822247-c4c3e480-3c3f-11ea-84da-9826f72a9c36.png)

**Comment by doctordns** [comment]
The module loads fine with RC2 on Windows Server 2019:

```powershell
PS C:\Foo> gmo active* -list

    Directory: C:\Windows\system32\WindowsPowerShell\v1.0\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.0.1.0               ActiveDirectory                     Core,Desk {Add-ADCentralAccessPolicyMember, Add-ADComputerServiceAccount, Add-ADDomainControllerPasswordReplicationPolicy, Add-ADFineGrainedPasswordPolicySubject, Add…

PS C:\Foo> gmo activedirectory
PS C:\Foo> ipmo activedirectory
PS C:\Foo> dir ad:

Name                 ObjectClass          DistinguishedName
----                 -----------          -----------------
Reskit               domainDNS            DC=Reskit,DC=Org
Configuration        configuration        CN=Configuration,DC=Reskit,DC=Org
Schema               dMD                  CN=Schema,CN=Configuration,DC=Reskit,DC=Org
DomainDnsZones       domainDNS            DC=DomainDnsZones,DC=Reskit,DC=Org
ForestDnsZones       domainDNS            DC=ForestDnsZones,DC=Reskit,DC=Org

PS C:\Foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0-rc.2}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rgroefer** [comment]
Yep, the Windows 10 update... I missed that part.
