### ISSUE TITLE
Introduce a -reverse operator

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11505]
its more elegant  and more concise

```
PS C:\> $a='hello world'
PS C:\> -join $a[$a.length..0]
dlrow olleh
PS C:\> -reverse $a
dlrow olleh
```

**Comment by rkeithhill** [comment]
Just one point of data, I've been using .NET since PDC 2000 and the only time I've ever used `.Reverse` was for an example.  I've never used it in a real app/script.

**Comment by p0W3RH311** [comment]
sometimes we needs manipulating data instead of using loop and index  or maybe other tricks -reverse operator is good alternative

**Comment by bpayette** [comment]
Hi @p0W3RH311 

Why do you think this should be an operator instead of a command? For example, do you feel that it's likely to become so common an operation that we should actually add a language feature rather than a command? (I'll note that in the last decade+, we haven't really even seen a request for a `reverse` command.)

And as you point out, reversing a collection is already fairly easy if a bit obscure:
```powershell
PS[1] (17) > @(1, 3, 4, 5)[3..0]
5
4
3
1
```

**Comment by vexx32** [comment]
Also worth mentioning is that arrays natively have a `Reverse()` method available:

```powershell
$array = 1..10
[array]::Reverse($array)
$array
```

**Comment by iSazonov** [comment]
Implementing the operator for primitive types/scenarios makes no sense. All our operator does PowerShell magic conversions. I can not think a scenario for reverse with magic conversions.

**Comment by lahell** [comment]
In this example `[bigint]::Parse()` returns i negative number and `ToByteArray()` returns bytes in reverse order compared to `$hex`. Before I can use the `$key` I have to reverse it.

```
$hex = '800816b1629bcfa519f57a502a6a841298a9f5c20203d8818fdd18271a3b1682'
$key = [bigint]::Parse($hex, 'HexNumber').ToByteArray()
[array]::Reverse($key)
```

Would be nice if `$key` had an extension method called `Reverse()`. It could take an optional argument of type boolean named `ReturnItems` which defaults to `$false`. In that case I could just do this:

```
$hex = '800816b1629bcfa519f57a502a6a841298a9f5c20203d8818fdd18271a3b1682'
$key = [bigint]::Parse($hex, 'HexNumber').ToByteArray().Reverse($true)
```

**Comment by vexx32** [comment]
@lahell if you use a different type, it can. Arrays simply don't have as many native methods attached to them, they're supposed to be simple, lightweight types with minimal bells and whistles. If you add a type cast to `List[byte]` then you'll get a `.Reverse()` method:
```powershell
$hex = '800816b1629bcfa519f57a502a6a841298a9f5c20203d8818fdd18271a3b1682'
[System.Collections.Generic.List[byte]] $key = [bigint]::Parse($hex, 'HexNumber').ToByteArray()
$key.Reverse()
```
But even then, it's the same amount of code as the array method, so I don't see a lot to be gained here, really.
