### ISSUE TITLE
Introduce a -notis operator

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11504]
operator of type -as and -is that would be Useful to have -notis

```
PS C:\> 'hello' -is [int]
False
PS C:\> !('hello' -is [int])
True
PS C:\> 'hello' -notis [int]
True
```

**Comment by rkeithhill** [comment]
Before suggesting new language features you might want to spend a wee bit more time looking to see if the feature already exists.  In this case, try `-isnot`.  :-)

**Comment by rkeithhill** [comment]
Cool.  BTW **if** you are satisfied with the existing `-isnot` operator you can close this issue.
