### ISSUE TITLE
$error with time of error

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11506]
its possible to add time of error property to $error variable. this value must be important in logging and is useful

**Comment by iSazonov** [comment]
PowerShell logging uses ETW and already has timestamps.

**Comment by BrucePay** [comment]
What @iSazonov  said :-) `$error` is intended to be an short-term _ephemeral_ in-memory logging facility. The event log and ETW are for more durable, time-stamped logging.
