### ISSUE TITLE
Distribution Support Request Ubuntu 19.04

### ISSUE THREAD

**Issue by JesterOrNot** [PowerShell/PowerShell#11507]
# Details of the Distribution
Ubuntu 19.04
![image](https://user-images.githubusercontent.com/50386709/71858157-ccb44e00-30af-11ea-9a14-a7e7223960d3.png)
- Name of the Distribution: Ubuntu
- Version of the Distribution: 19.04
- Processor Architecture (One per request): x86_64
- [X] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker
- The following is a requirement for supporting a distribution **without exception.**
  - [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and 
  the PowerShell comittee will review the request.
  - [X] The version of the Distribution is supported for at least one year.
  - [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Lifecycle updated
- [ ] Documentation Updated

**Comment by TravisEz13** [comment]
This is an interim release of Ubuntu.
