### ISSUE TITLE
font shows ?~?

### ISSUE THREAD

**Issue by 1amirjalai** [PowerShell/PowerShell#11519]
# Steps to reproduce

```powershell 7 rc1

shows this

 

```
****
![image](https://user-images.githubusercontent.com/2786675/71956027-3727d400-31ff-11ea-97ac-fc04a07d373a.png)

**Comment by iSazonov** [comment]
@1amirjalai We need more info to reproduce.
The issue could be with your termonal or PSReadline.

**Comment by 1amirjalai** [comment]
what info do you need? i just installed powershell 7 rc1 core using msi

**Comment by iSazonov** [comment]
Can you repo without PSReadline?
What is a terminal you use?
