### ISSUE TITLE
Microsoft.VisualBasic.Interaction Issue

### ISSUE THREAD

**Issue by ganlbarone** [PowerShell/PowerShell#11513]
# Steps to reproduce
 This results in an error  that there is no method msgbox. You can also run a get-member -static on the actual [Microsoft.VisualBasic.Interaction] object and you will see that in ps7 there is in fact no msgbox method.
```
  [void] [System.Reflection.Assembly]::LoadWithPartialName("Microsoft.VisualBasic") 
    $prompt = [Microsoft.VisualBasic.Interaction]::MsgBox("Test", "OkOnly,SystemModal,Critical", "test")

```
We expect there to be a msgbox method, executing the above in ps 5.1 works perfectly. Below s the msgbox method.

MsgBox          Method     static Microsoft.VisualBasic.MsgBoxResult MsgBox(System.Object Prompt, Microsoft.VisualBasic.MsgBoxStyle Buttons, System.Object Title)

# Environment data

PSVersion 7.0.0-rc.1

**Comment by iSazonov** [comment]
I guess it is limitations of the .Net Core Microsoft.VisualBasic package.
You can use:
```powershell
[System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
$return=[System.Windows.Forms.Messagebox]::Show("This is the Message text")
$return=[System.Windows.Forms.MessageBox]::Show("Message Text","Title",[System.Windows.Forms.MessageBoxButtons]::OKCancel)	
```

**Comment by ganlbarone** [comment]
@iSazonov  thanks for this, I had seen this. 

I actually wrote a function to take advantage of forms. However, I would need to do significant work updating this in all the places the visualbasic class has been used within carying ps scripts.

Would be nice to figure out why it doesnt work in 7. But have already stored this away as a potential work around.

**Comment by iSazonov** [comment]
> Would be nice to figure out why it doesnt work in 7.

.Net Core initially (v1 and v2) doesn't support desktop applications and all GUI API was removed. Currently they ported WinForms to .Net Core and we get it in PowerShell.

**Comment by ganlbarone** [comment]
That makes sense oddly enough, or maybe not too odd, I can use WPF\XAML reader without issue on the GUI side of things.

Ill look to migrate things over to WinForm class for the time being since that seems to be the only real avenue for now. 

Thanks!
