### ISSUE TITLE
add new switch byte to get-random

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11524]
`PS> $bytes=get-random -count 5 -byte`

**Comment by iSazonov** [comment]
@p0W3RH311 Any enhancements make sense only for real business scenarios. What is a scenario you want to address? Why "-byte"? Why not "-kilobyte", "-megabyte"?

**Comment by KalleOlaviNiemitalo** [comment]
This alternative surprisingly outputs floating-point numbers:

```
PS C:\> Get-Random -Count 5 -Maximum ([Byte]::MaxValue)
249.566275419
194.84230476657
97.5254132074888
3.69200218407996
223.495648840207
```
