### ISSUE TITLE
Get-Content -Raw  returns only the last line if it is CR

### ISSUE THREAD

**Issue by al-cheb** [PowerShell/PowerShell#11529]
# Steps to reproduce

```powershell
$bytes = Write-Output 49 13 50 13 51 13 52 13 53
[IO.File]::WriteAllBytes("cr.txt", $bytes)
Get-Content -Raw cr.txt
```

# Expected behavior

```none
1
2
3
4
5
```

# Actual behavior

```none
5
```

# Environment data

```none
Windows 10 / PowerShell 7.0.0-rc.1
```

**Comment by KalleOlaviNiemitalo** [comment]
It is not a bug in Get-Content. Rather, the carriage return characters are output to the console, which then moves the cursor back to the beginning of the line and starts overwriting previous output.

```
PS C:\> "eight`rr"
right
```
