### ISSUE TITLE
Debian Install Script Not Updated To Support Debian 10

### ISSUE THREAD

**Issue by RandomNoun7** [PowerShell/PowerShell#11539]
# Steps to reproduce

From a Debian 10 machine:
1. execute the following command
`wget https://aka.ms/install-powershell.sh; sudo bash install-powershell.sh -preview; rm install-powershell.sh`

2. See that installation will fail on execution of the following script in this project repo:
`tools/installpsh-debian.sh`

[Line 189](https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-debian.sh#L189) has not been updated to reflect the new support for Debian 10.

# Expected behavior

Install script should execute and install PowerShell on Debian 10

# Actual behavior

Script fails with the following error message
```
(23) Failed writing body
ERROR: unsupported Debian version (10).
Supported versions: 8, 9.
For additional versions open an issue or pull request at: https://github.com/powershell/powershell
```
# Environment data

Distro: Debian 10.

I have a fix tested and ready to go. Creating this issue to have something to reference in the Pull Request.

**Comment by he852100** [comment]
yes ，It also does not support all arm
