### ISSUE TITLE
Preserve unmapped security IDs in ConvertFrom-SddlString

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [PowerShell/PowerShell#11537]
# Summary of the new feature/enhancement

When I copy an SDDL string from another computer and use ConvertFrom-SddlString to view it in a form that is easier to understand, ConvertFrom-SddlString discards the security IDs that it is unable to translate to NT account names.  It would be more convenient if ConvertFrom-SddlString displayed them as SID strings in that case.

# Proposed technical implementation details

For example, if S-1-5-82-269044437-150487689-1149708198-3394286750-593715923 (which would be algorithmically generated from `IIS APPPOOL\Sandbox`) is not defined in the local computer:

```
PS C:\> convertfrom-sddlstring -Sddl "D:AI(A;OICI;0x1200a9;;;S-1-5-82-269044437-150487689-1149708198-3394286750-593715923)" -Type FileSystemRights

Owner            :
Group            :
DiscretionaryAcl : {: AccessAllowed (ListDirectory, Read, ReadAndExecute, ReadAttributes, ReadExtendedAttributes, ReadPermissions, Synchronize, Traverse)}
SystemAcl        : {}
RawDescriptor    : System.Security.AccessControl.CommonSecurityDescriptor
```

I would like to see this instead:

```
PS C:\> convertfrom-sddlstring -Sddl "D:AI(A;OICI;0x1200a9;;;S-1-5-82-269044437-150487689-1149708198-3394286750-593715923)" -Type FileSystemRights

Owner            :
Group            :
DiscretionaryAcl : {*S-1-5-82-269044437-150487689-1149708198-3394286750-593715923: AccessAllowed (ListDirectory, Read, ReadAndExecute, ReadAttributes, ReadExtendedAttributes, ReadPermissions, Synchronize, Traverse)}
SystemAcl        : {}
RawDescriptor    : System.Security.AccessControl.CommonSecurityDescriptor
```

(I don't really care whether the asterisk is there or not. `ICACLS` expects the asterisk when given a numerical SID on the command line, but it does not output an asterisk when it displays an unmapped SID in an ACL.)

Perhaps this can be implemented just by changing the exception handler in `ConvertToNTAccount` <https://github.com/PowerShell/PowerShell/blob/40e77b88b59918c82ccbe5234df7ee3ad421bd51/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-SddlString.cs#L48-L58>

**Comment by iSazonov** [comment]
@KalleOlaviNiemitalo  The cmdlet does empirical and low trust conversions. If you are interesting in improving the cmdlet and ready to pull a PR I can reference our old related discussions (or you could use search).

**Comment by KalleOlaviNiemitalo** [comment]
@iSazonov After looking around, I think `ConvertFrom-SddlString` may be better deprecated than fixed.
- Mixing up names from multiple access mask enumeration types (#8365)
- No support for generic access rights (<https://github.com/PowerShell/PowerShell/issues/8365#issuecomment-572679222>)
- No support for `System.Security.AccessControl.ObjectAce` (invalid cast)
- No support for ACE types and [SECURITY_INFORMATION](https://docs.microsoft.com/windows/win32/secauthz/security-information) bits added after Windows Vista; no such support in .NET either (related to <https://github.com/dotnet/corefx/issues/40347>)
- Confusing output "AuditFlags" if both `AceFlags.SuccessfulAccess` and `AceFlags.FailedAccess` are set
- No cmdlet for converting the output back to SDDL or to a security descriptor
- Breaking changes not allowed

**Comment by iSazonov** [comment]
@KalleOlaviNiemitalo This should be a new implementation. It is a breaking change but current implementation is not acceptable.
