### ISSUE TITLE
Console window remains open when VSCode started from PowerShell

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#11542]
Tracked in VSCode as https://github.com/microsoft/vscode/issues/50308.

# Steps to reproduce

(On Windows)

- Open VSCode with `code .`
- `exit` PowerShell

# Expected behavior

- PowerShell console window closes
- VSCode stays open

# Actual behavior

- PowerShell window remains open
- VSCode remains open
- When VSCode window is closed, the PowerShell window is closed
- If PowerShell runs `code` but does not open a new window (because one for the directory is already open) the issue does not occur

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.19535
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by DHowett-MSFT** [comment]
This is microsoft/vscode#66750.

**Comment by iSazonov** [comment]
PowerShell try to detect that application is GUI then run it async. Otherwise it run the application as console application in sync.

**Comment by iSazonov** [comment]
See #9970 for reference on IsWindowsApplication()

**Comment by DHowett-MSFT** [comment]
There's nothing PowerShell can do to prevent this. VSCode (<=1.41? to be confirmed) _re-attaches to the console handle it receives from its parent_. In so doing, it prevents the console from being closed when PowerShell exits because there's still one application attached to it.
