### ISSUE TITLE
CLASSPATH for dll/psm1

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#11543]
# Summary 

In Java/JVM world you can use classpath to add dependencies (jars), instead of packaging it with your own project. e.g.:
```java -cp "myProject.jar:./dependencies/*." MyClass```
Or it could discover jars in CLASSPATH env variable if set

Loading types from dlls and psm1 (powershell classes) using similar approach might be very beneficial for powershell too.
This could be a simple way to decouple dependencies (external dlls) from shared PS scripts/modules and make powershell classes defined in psm1 files reusable (without hacking). Latter is pretty cumbersome at the moment, especially if mixing with imported .net types

# example
 ```
 # this should make types from dll/psm globally available in that session
pwsh [-f ./myscript.ps1] -cp ./dep/*.dll, ./config.psm1

```

```
# this might be nice too
$env:PSCLASSPATH += ":~/dependecies/*"
pwsh -f ./myscript.ps1 
```

**Comment by iSazonov** [comment]
Proposal to put PowerShell classes to special files already was in our discussions.
It is large area for discussion and right way to continue is to create RFC in PowerShell-RFC repository.
