### ISSUE TITLE
Failed CertificateProvider Pester tests

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#11549]
Fixing #6265 exposes failing tests in `test\powershell\Modules\Microsoft.PowerShell.Security\CertificateProvider.Tests.ps1`.

The error message is: "Expected $null to be different from the actual value, but got the same value."

see: https://dev.azure.com/powershell/PowerShell/_build/results?buildId=42916&view=ms.vss-test-web.build-test-results-tab

**Comment by iSazonov** [comment]
@xtqqczze The test should use ` Get-ChildItem -LiteralPath` instead of ` Get-Item -LiteralPath`

**Comment by daxian-dbw** [comment]
@iSazonov Can you please refer to the issue that this one duplicates to?

**Comment by iSazonov** [comment]
@daxian-dbw It is #6265 - all that we need to fix is there.

**Comment by daxian-dbw** [comment]
@iSazonov Thanks! It's always recommended to specify the duplicate issue when closing an issue as `Resolution-Duplicate` 😃

**Comment by xtqqczze** [comment]
The test still fails with `Get-ChildItem` instead of `Get-Item` so this is not duplicate of #11188 .

See commit 30fe43e04a3bda5c3b4c5e8a717b66e1e4895b04 and PowerShell-CI-windows build [43682](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=43682&view=ms.vss-test-web.build-test-results-tab).

@iSazonov can you reopen?

**Comment by iSazonov** [comment]
@xtqqczze You can add comments in #6265. Even if we have some fail tests we can track in one issue. You could summarize there with references to test codes.
