### ISSUE TITLE
Write test to exclude UTF-8 BOM from files in tree

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#11554]
Write a test to exclude regressions from #11546, 0aaf74b

**Comment by xtqqczze** [comment]
We could use the following code to test for BOM:

```powershell
filter hasBom {
    $_.Where{
        $bytes = [byte[]]::new(3)
        $stream = [System.IO.File]::OpenRead($_.FullName)
        $stream.Read($bytes, 0, 3) > $null
        $stream.Close()
        $bytes[0] -eq 0xef -and $bytes[1] -eq 0xbb -and $bytes[2] -eq 0xbf
    }
}
```

**Comment by iSazonov** [comment]
@TravisEz13 Should it be in static tests?

**Comment by TravisEz13** [comment]
@iSazonov  yes, this should be a static test.

**Comment by xtqqczze** [comment]
We should consider setting a code analyzer rule to check for BOM:

![image](https://user-images.githubusercontent.com/45661989/72763681-c6a88c00-3bdc-11ea-8341-0e5e4014c1b3.png)

https://github.com/maroontress/StyleChecker/blob/master/doc/rules/ByteOrderMark.md

**Comment by iSazonov** [comment]
We could use code analyzer(s) on server side although a script would be more simple.

**Comment by xtqqczze** [comment]
@iSazonov If we use a code analyzer rule running on `PowerShell-CI-static-analysis`, we could use the same rule in a local build and for live analysis in the development environment.

**Comment by xtqqczze** [comment]
See #11654

**Comment by xtqqczze** [comment]
When DotNetAnalyzers/StyleCopAnalyzers#2100 is implemented we could add the rule for analysis.

**Comment by iSazonov** [comment]
I believe PowerShell script in our static analysis will be simple, fast and reliable.
