### ISSUE TITLE
Support for multi-line invocations without using parameter splatting or `

### ISSUE THREAD

**Issue by Pxtl** [PowerShell/PowerShell#11551]
# Summary of the new feature/enhancement

Allow invocations that are wrapped in parentheses to span multiple lines, eg:

```ps
(Invoke-MyCommandlet 
 -arg1 "foo" 
 -arg2 "bar" 
 -arg3 "baz" 
)
```

# Problem

Currently there are two dominant ways to do a multi-line invocation in powershell:
## Backtick line-continuations
```ps
Invoke-MyCommandlet `
 -arg1 "foo" `
 -arg2 "bar" `
 -arg3 "baz" `
```

This is problematic because it's whitespace-sensitive and prevents using # for line-comments.

## Splatting
```ps
$HashArguments = @{
 arg1 = "foo"
 arg2 = "bar"
 arg3 = "baz"
}
Invoke-MyCommandlet @HashArguments 
```
this creates the problem that you lose intellisense and validation since you've decoupled the parameters from their corresponding command.

## Summary

There are no good ways to do multiline invocations in Powershell.

# Proposal

Let the humble parenthesis handle it.  Currently, this:

```ps
(Invoke-MyCommandlet -arg1 "foo" -arg2 "bar" -arg3 "baz")
```

is valid powershell, but this:

```ps
(Invoke-MyCommandlet 
 -arg1 "foo" 
 -arg2 "bar" 
 -arg3 "baz" 
)
```

is not valid.  But why not?  The open-parens clearly identifies that we're starting something that should not end until we see a close-parens.  Why not, then, allow it to span multiple lines?

**Comment by vexx32** [comment]
@KirkMunro has some ideas and even an open PR handling something along these lines. Not sure we have consensus on what the solution ought to be here, but this seems to be an interesting idea to add to the possibilities.

**Comment by iSazonov** [comment]
Please discuss in the RFC https://github.com/PowerShell/PowerShell-RFC/pull/179
