### ISSUE TITLE
Compress-Archive should support -DoNotIncludeBaseDirectory parameter

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#11550]
Take the following file tree:

````
❯ Get-ChildItem -Recurse c:/tmp/somedir | Foreach-Object { $_.FullName }
C:\tmp\somedir\somesubdir
C:\tmp\somedir\foo.txt
C:\tmp\somedir\somesubdir\bar.txt
````

It seems / AFAIK there is no way with `Compress-Archive` to produce a zip archive that doesn't include the `somedir` folder at the top.

My current workaround is to use:

````
[System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem")
[System.IO.Compression.ZipFile]::CreateFromDirectory('c:\tmp\somedir', 'c:\tmp\foo.zip', 'Optimal', $false)
```` 

There should be an option to `Compress-Archive` that's the equivalent of the `includeBaseDirectory` parameter of `CreateFromDirectory`.

**Comment by ThomasNieto** [comment]
The GitHub repository for that command is here: https://github.com/PowerShell/Microsoft.PowerShell.Archive Please open the ticket there.

**Comment by sba923** [comment]
Sorry for my mistake.

There's already an issue for this at [https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/43](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/43)
