### ISSUE TITLE
FormatXML not loaded when loading Older Modules (Using the compatibility feature)

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#11556]
In RC1, if you load a module via the compatibility feature (eg ServerManager), then the display XML is not also loaded. That means when objects are returned they are not formatted properly.

For example,, if you load the server manager module to get installed features, the output is like this in RC1:

```powershell
PS C:\Foo> get-windowsfeature powershell
Display Name                                  Name                       Install State
------------                                  ----                       -------------
                                              PowerShell                     Installed
```
In Windows PowerShell the output looks like this:

```powershell
PS C:\Foo> get-windowsfeature powershell
Display Name                                  Name                       Install State
------------                                  ----                       -------------
    [X] Windows PowerShell 5.1                PowerShell                     Installed
```

What should be happening is th at the display XML in the module should be imported into the current session.  If you manually update the format data doign the following then output is as expected:
````powershell
Update-FormatData -PrependPath C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ServerManager\Feature.format.ps1xml
````

# Steps to reproduce

To repo - just load non-compatibile module and observe the objects returned as in the case noted abvove. 

# Expected behavior

I expected output to be consistent with Windows PowerShell 5.1

# Actual behaviour

The objects returned are formatted using default formatting rules not the formatting XML that is included in the module.

# Environment data

```none

```

**Comment by iSazonov** [comment]
@anmenaga Is ServerManager compatible with WinPS Compatible feature?

**Comment by doctordns** [comment]
I use Server Manager extensively to install and remove windows feature. The module works just fine in terms of adding, getting, and removing  WIn features. 

What doe not work is that the display XML is not imported into the parent PS 7 session. I can get around that by manually updating format data and pointing to the display XML file. 

I suggest that if display XML does exist, then when WIncompat loading is done, Import-Module should update the underlying display XML into the PWSH 7 session.
