### ISSUE TITLE
Start-Transcript should have an option to produce color-preserving output

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#11567]
Typical PowerShell script output (especially when debugging, using the various output streams...) is "usefully colorized."

Alas, `Start-Transcript` only captures a non-formatted, "monochrome" version of the output.

It would be great IMVHO to have the option of generating formatted (RTF and/or HTML) output preserving the colors.

As an example, [MobaXterm](https://mobaxterm.mobatek.net/) saves terminal output as RTF, preserving the colors of the emulated terminal's output.

**Comment by SteveL-MSFT** [comment]
I guess the question is whether you actually want to retain color (which would be ANSI escape sequences) or really just want an easier way to view transcripts?  For example, `Get-Content` could have a transcript mode that colorizes strings starting with `DEBUG:`, `VERBOSE:` etc....  Or `ConvertTo-Html` could also have special logic to understand transcripts and output color.

Transcription currently makes an effort to not preserve color and I'm not sure if preserving the ANSI escape sequences really solves your specific problem as they would only be useful viewed in a terminal that understands ANSI.

**Comment by kilasuit** [comment]
@SteveL-MSFT perhaps it's time to spit out a Markdown file for the transcript instead of plaintext?

**Comment by AlexHimself** [comment]
Where did this land?

**Comment by mklement0** [comment]
Note that _Windows PowerShell_'s `Start-Transcript` - invariably - captures ANSI escape sequences as-is.

A simple improvement could be to honor the `$PSStyle.OutputRendering` preference, namely to capture ANSI escape sequences in the transcript (only) when its value is `'Ansi'`.
