### ISSUE TITLE
pwsh fails to load an assembly when Azure.Data.AppConfiguration client is used in a binary module

### ISSUE THREAD

**Issue by eosfor** [PowerShell/PowerShell#11560]
# Steps to reproduce

1. clone the repo from [here](https://github.com/eosfor/appcfgpwsh_test)
2. update the [line](https://github.com/eosfor/appcfgpwsh_test/blob/a61695c84f19a5d4a3bb317840cdf448f3b4b5d7/TestSampleCmdletCommand.cs#L34) with the proper app config service connection string
3. rebuild
4. publish
5. cd to the publish folder
6. load the module dll to the pwsh session
7. run the Test-SampleCmdlet cmdlet, enter any number when prompted

# Expected behavior

keys added to the app config service

# Actual behavior

![image](https://user-images.githubusercontent.com/9363027/72212926-3317e280-349b-11ea-9c3a-baee24c9c6e6.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by eosfor** [comment]
replacing URL is not even necessary. it still fails with the wrong URL anyway

**Comment by iSazonov** [comment]
You could try to load the dll manually by `Add-Type -Path` and look an error with `Get-Error`

**Comment by eosfor** [comment]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/9363027/72224715-5a6dbe80-3532-11ea-8a77-a877bb3a5eb3.png">

I wonder if I can have get-error in ps6.

ps7 is not something we use regularly, I'll try it though

**Comment by eosfor** [comment]
This is what it gives me for just ```add-type```

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/9363027/72226626-12599680-3548-11ea-9c5b-f27fc3b2fbcf.png">

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/9363027/72226636-28675700-3548-11ea-85ae-fdef18b51250.png">
