### ISSUE TITLE
Expand tilde for LD_LIBRARY_PATH and PSModulePath?

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#11570]
# Summary of the new feature/enhancement

This was brought up in the PR https://github.com/PowerShell/PowerShell/pull/11552 to expand `~` for PATH making it consistent with BASH and resolving an issue with dotnet global tools which adds a path starting with `~` to PATH.  `~` expansion is done by the shell and not the OS, so this can lead to unexpected behavior if this isn't understood.  From that perspective, it seems that using `~` as shortcut to refer to `$HOME` is ok for interactive use, but probably not recommended for system config changes as other shells may not support it.

From that perspective, it may not make sense to use it for `LD_LIBRARY_PATH` nor `PSModulePath`, but I can also see an argument that developers may want to use this during development rather than an absolute path.  Thoughts?

**Comment by SeeminglyScience** [comment]
For `PSModulePath` yeah sure why not.

As for `LD_LIBRARY_PATH`, unless `dlopen` expands <kbd>~</kbd> (which I don't think it does) then I don't think it makes sense. Testing a console app from PowerShell and having `LD_LIBRARY_PATH` *appear* to not carry over into the child process would be a pain to debug.

**Comment by SteveL-MSFT** [comment]
Just to be clear what I mean by expand `LD_LIBRARY_PATH` is that when we detect that env var has changed, we would expand `~` and reset the value.  Seems wrong to me just to have consistency across the `PATH` env vars.  In the case of `PATH` and `PSModulePath`, the expansion is internal to pwsh.

**Comment by SeeminglyScience** [comment]
So `$env:PATH = '~/test'; $env:PATH` would return `~/test` but `$env:LD_LIBRARY_PATH = '~/test'; $env:LD_LIBRARY_PATH` would return `/home/user/test`?

**Comment by SteveL-MSFT** [comment]
@SeeminglyScience yes, if we decide LD_LIBRARY_PATH expansion is needed
