### ISSUE TITLE
Start-Process fails on argument-less invocation of 7zip

### ISSUE THREAD

**Issue by Rareitor** [PowerShell/PowerShell#11578]
For likely any version of Powershell beyond 5.1 (6.0.0 and up), if Start-Process is used to execute 7z.exe with the Wait and NoNewWindow flags enabled, the process throws an exception after apparently actually running the executable.

# Steps to reproduce

```
$7zipExec = <path-to-7zip-exec>
Start-Process -FilePath $7zipExec -NoNewWindow -Wait
```

# Expected behavior

```
Prints usage reference like:
Usage: 7z <command> [<switches>...] <archive_name> [<file_names>...] [@listfile]
...
```

# Actual behavior

```
Prints usage reference as it should, but also ends with:
Start-Process : Cannot process request because the process (###) has exited.
At line:1 char:1
+ Start-Process -FilePath $7zipExec -NoNewWindow -Wait;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-Process], InvalidOperationException
+ FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

# Environment data

```
Tested with Powershell:
- 4.0 (Windows Server 2012R2)
- 5.1 (Windows 10 1809)
- 6.0.0 (Windows 10 1809)
- 6.2.3 (Windows 10 1809)
- 7.0.0 RC1 (Windows 10 1809)
```

**Comment by mklement0** [comment]
I just tried with 7-Zip 18.05 on Windows PowerShell, PowerShell 7.0.5, 7.1.2, and the latest preview, 7.2.0-preview.4, and I don't see the symptom - but my Windows 10 version is newer: Version 20H2, OS Build: 19042.867

Are you still on the same Windows 10 version and do you still see the symptom?

As an aside: there's generally no good reason to use `Start-Process` for synchronous invocation of a console application in the same window: direct invocation does that automatically (in your case: `& $7zipExec`), and has the added advantage of integrating with PowerShell's output streams - see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6239
