### ISSUE TITLE
Web cmdlets and proxy

### ISSUE THREAD

**Issue by michaelelleby** [PowerShell/PowerShell#11577]
# Steps to reproduce

```powershell
[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)
Invoke-RestMethod https://www.powershellgallery.com
Invoke-WebRequest https://www.powershellgallery.com
```

# Expected behavior

```none
Both requests should return HTML from https://www.powershellgallery.com as seen when running the same cmdlets in PowerShell 5.1
```

# Actual behavior

```none
Both requests fail:
Invoke-RestMethod: Response status code does not indicate success: 407 (Proxy Authentication Required).
Invoke-WebRequest: Response status code does not indicate success: 407 (Proxy Authentication Required).
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

System proxy settings 
![System proxy settings](https://user-images.githubusercontent.com/6172897/72324539-7a74bd80-36ab-11ea-9135-5624a05ae2b1.png)
```

**Comment by iSazonov** [comment]
Related #9533

**Comment by larssb** [comment]
I also have this issue. On a system with the following characteristics:

1. Proxy PAC script being used for automated system-wide proxy configuration
1. `Find-Module`,`Invoke-WebRequest` and similar cmdlets work fine on PS v5.1
1. The same cmdlets do not work on v7 GA

---

# Errors

The error is: `Invoke-WebRequest: Response status code does not indicate success: 407 (Proxy Authentication Required).` ... this is the err when `[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)` has been executed before executing e.g. `Find-Module`

# Debugging

1.

Without executing `[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)`.

== the error is: `WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.`

2.

Setting:

```
[system.net.webrequest]::defaultwebproxy = new-object system.net.webproxy('http://IP_OF_PROXY:8080')
[system.net.webrequest]::defaultwebproxy.credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
[system.net.webrequest]::defaultwebproxy.BypassProxyOnLocal = $true
```
in $PROFILE

== **does not help**.

3. 

Trying to manually authenticate by setting:

```
$WebProxy = New-Object System.Net.WebProxy(“http://IP_OF_PROXY:8080”,$true)
$WebClient = New-Object net.webclient
$WebClient.proxy.Credentials = New-Object System.Net.NetworkCredential($username,$password)
```

== **does not help**

4.
 
Using the `-Proxy` parameter on the cmdlets

== **does not help**

5.

Tried `Unregister-PSRepository -Name PSGallery` >> `Register-PSRepository -Default` 

== **to no avail**

# Various

I've read the issues referred to in this issue posting as well as:

#10460 
#9495 (where @SteveL-MSFT mentions this to be verified working in v7 preview 3 (I'm on v7 GA))
#7827

**Comment by e1ze** [comment]
Same problem as @larssb here.
I tried all the solutions that are mentioned to register the PSGallery repository or using any webcmdlets in our corporate network behind a proxy but nothing helped so far for PowerShell 7.:

**Important**: The **following workaround**, as mentioned from @SteveL-MSFT [here](https://github.com/PowerShell/PowerShell/issues/9495#issuecomment-515592672), works with the currently logged in user! **BUT** as soon as I start a Powershell with a different user, it doesn't work with this user anymore (no matter which user i am using). The test users are also member of the local administrator group during tests.

Workaround with current user (NOT working when starting powershell as different user):
```pwsh
[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)
Invoke-WebRequest https://www.powershellgallery.com
Register-PSRepository -Default -Verbose
```

**WebRequest with different user:** 

```pwsh
[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)
Invoke-WebRequest https://www.powershellgallery.com

Invoke-WebRequest: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Das Zeitlimit für den Vorgang wurde erreicht.'.
[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)
Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2 -SslProtocol Tls
Invoke-WebRequest: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Das Zeitlimit für den Vorgang wurde erreicht.'.

[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)
Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2 -SslProtocol Tls11
Invoke-WebRequest: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Das Zeitlimit für den Vorgang wurde erreicht.'.

[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)
Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2 -SslProtocol Tls12
Invoke-WebRequest: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Das Zeitlimit für den Vorgang wurde erreicht.'.

Invoke-WebRequest -Uri https://40.87.85.101/api/v2 -SslProtocol Tls12 -SkipCertificateCheck
Invoke-WebRequest: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Das Zeitlimit für den Vorgang wurde erreicht.'.
```

**What have I tested?**

```pwsh
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```pwsh
Resolve-DnsName www.powershellgallery.com

Name                           Type   TTL   Section    NameHost
----                           ----   ---   -------    --------
www.powershellgallery.com      CNAME  30    Answer     powershellgallerytrafficmanager.trafficmanager.net
powershellgallerytrafficmanage CNAME  30    Answer     psg-prod-eastus.cloudapp.net
r.trafficmanager.net

Name       : psg-prod-eastus.cloudapp.net
QueryType  : A
TTL        : 10
Section    : Answer
IP4Address : 40.87.85.101
```

```pwsh
[System.AppContext]::SetSwitch("System.Net.Http.UseSocketsHttpHandler", $false)

$DefaultProxy = "http://proxyserver:8080"
$ProxyUri = New-Object System.Uri($DefaultProxy)
[System.Net.WebRequest]::DefaultWebProxy = New-Object System.Net.WebProxy ($ProxyUri, $true)
[System.Net.WebRequest]::DefaultWebProxy.BypassProxyOnLocal = $true
```

OR

```pwsh
[system.net.webrequest]::defaultwebproxy = new-object system.net.webproxy('http://proxyserver:8080')
```

Tried both - with or without setting the credential properties (we are not using any credentials for our proxy)
```pwsh
[System.Net.WebRequest]::DefaultWebProxy

Address               : http://proxyserver:8080/
BypassProxyOnLocal    : True
BypassList            : {}
BypassArrayList       : {}
Credentials           : System.Net.SystemNetworkCredential
UseDefaultCredentials : True
```

or 

```pwsh
[System.Net.WebRequest]::DefaultWebProxy

Address               : http://proxyserver:8080/
BypassProxyOnLocal    : True
BypassList            : {}
BypassArrayList       : {}
Credentials           :
UseDefaultCredentials : False
```

More Details:

```pwsh
$webclient=New-Object System.Net.WebClient
PS C:\Git> $webclient

Encoding                  : System.Text.UTF8Encoding+UTF8EncodingSealed
BaseAddress               :
Credentials               :
UseDefaultCredentials     : False
Headers                   : {}
QueryString               : {}
ResponseHeaders           :
Proxy                     : System.Net.WebProxy
CachePolicy               :
IsBusy                    : False
AllowReadStreamBuffering  : False
AllowWriteStreamBuffering : False
Site                      :
Container                 :


PS C:\Git> $webclient.Proxy

Address               : http://proxyserver:8080/
BypassProxyOnLocal    : True
BypassList            : {}
BypassArrayList       : {}
Credentials           :
UseDefaultCredentials : False
```

Then:
```pwsh
Register-PSRepository -Default -Verbose
VERBOSE: Performing the operation "Register Module Repository." on target "Module Repository 'PSGallery' () in provider 'PowerShellGet'.".
```

Result:
```pwsh
Get-PSRepository -Verbose
WARNING: Unable to find module repositories.
```

I tried setting the proxy configuration through registry in HKLM/HKCU:

```pwsh
'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings':

ProxyEnable   : 1
ProxyServer   : proxyserver:8080
ProxyOverride : *.local;<local>;test123


'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings':

ProxyEnable   : 1
ProxyServer   : proxyserver:8080
ProxyOverride : *.local;<local>;test123


'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings':

ProxyEnable   : 1
ProxyServer   : proxyserver:8080
ProxyOverride : *.local;<local>;test123
```

I tried setting and using the WinHTTP proxy configuration through netsh

```pwsh
netsh winhttp import proxy source=ie

Aktuelle WinHTTP-Proxyeinstellungen:

    Proxyserver     :  proxyserver:8080
    Umgehungsliste  :  *.local;<local>;test123
```

Also using the `-Proxy` parameter on the cmdlets does not help.

After each change I tried the registration process and the `Invoke-WebRequest` again

EDIT:
After reading this post, i tried his solution and it is **working** for the webcmdlets but NOT for `Register-PSRepository`!

```pwsh
$env:http_proxy = 'http://proxyserver:8080'
$PSDefaultParameterValues["*:proxy"]=$env:http_proxy
Invoke-WebRequest -Uri https://www.powershellgallery.com/api/v2

StatusCode        : 200
StatusDescription : OK
Content           : <?xml version="1.0" encoding="utf-8"?><service xml:base="https://www.powershellgallery.com/api/v2" xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom"><workspace><atom:title ty…
RawContent        : HTTP/1.1 200 OK
                    Cache-Control: no-cache
                    Date: Wed, 15 Apr 2020 10:30:00 GMT
                    Pragma: no-cache
                    Server: Microsoft-IIS/10.0
                    X-CorrelationId: 800034b7-0006-a400-b63f-84710c7967bb
                    DataServiceVersion: …
Headers           : {[Cache-Control, System.String[]], [Date, System.String[]], [Pragma, System.String[]], [Server, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 338
RelationLink      : {}
```

**Comment by iSazonov** [comment]
Please download and check with latest preview version.

**Comment by e1ze** [comment]
@iSazonov 
thanks for the reply.
i installed the Preview 1 of 7.1, deleted my powershell profile and rerun the tests (Powershell started as different user).
Same behavior/problems as before. Here is a screenshot:

![image](https://user-images.githubusercontent.com/6794362/79344678-6ea9c900-7f30-11ea-93ba-2e56dd08ea1c.png)

**Comment by iSazonov** [comment]
Thanks! I also #9533. I guess it is .Net Core issue. If you can create simple repo on C# you could open new issue in .Net Runtime (perhaps it already is there).

**Comment by e1ze** [comment]
For me this is unfortunately a show stopper to switch completely to Powershell 7, because in my daily work I very often start the powershell as a different user and therefore have to and want to work as normal as possible. I can install the modules with my standard user account and now have written a script for it but this is of course more than annoying.

It would be great if someone had a solution or at least an info if it is not directly related to Powershell but to .NET Core, PowershellGet or similar.

**Comment by larssb** [comment]
@eizedev .... maybe [this](https://github.com/PowerShell/PowerShell/issues/9495#issuecomment-627839596) could the solution for you. I can't see you mentioning anything about your environment in regards to a proxy. But, give it a look.

**Comment by drmiru** [comment]
This worked for me:

$proxyUri = 'http://proxy.domain.com:8080'
[System.Net.Http.HttpClient]::DefaultProxy = New-Object System.Net.Webproxy($proxyUri, $true)
[System.Net.Http.HttpClient]::DefaultProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials

**Comment by eizedev** [comment]
> This worked for me:
> 
> $proxyUri = 'http://proxy.domain.com:8080' [System.Net.Http.HttpClient]::DefaultProxy = New-Object System.Net.Webproxy($proxyUri, $true) [System.Net.Http.HttpClient]::DefaultProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials

Setting the proxy for the HttpClient also works for me. You could set the proxy as in  the example above, execute your commands and the unset the proxy for HttpClient this way afterwards:

`[System.Net.Http.HttpClient]::DefaultProxy = New-Object System.Net.WebProxy($null)`

**Comment by CarloToso** [comment]
@iSazonov should we close this? Or should we try to do something about it

**Comment by iSazonov** [comment]
I tried latest build (~7.4 Preview.2) and IWR works with proxy by default.
Since we use HttpClientSocket handler by default (and no plans to support old handler) we can close the issue.
