### ISSUE TITLE
Some command not working on Msix version

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#11588]
Some command not working on [MSIX version](https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.1/PowerShell-7.0.0-rc.1-win-x64.msix). 
But all command working fine on [MSI version](https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.1/PowerShell-7.0.0-rc.1-win-x64.msi).
Please fix MSIX version.
![PowerShell Core](https://user-images.githubusercontent.com/23485114/72437974-23f5a500-37b9-11ea-9cb5-abc585f541f9.png)

**Comment by iSazonov** [comment]
Does this work in Windows PowerShell?

**Comment by amirrammari** [comment]
> Does this work in Windows PowerShell?

this's work on Windows 10 built-in PowerShell and [Msi version of PowerShell Core](https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-rc.1/PowerShell-7.0.0-rc.1-win-x64.msi)

**Comment by SteveL-MSFT** [comment]
Despite requesting un-virtualized resources, it seems that the msix is still running in some sandbox.

**Comment by xmha97** [comment]
After reinstalling Windows 10, this issue resolved.
So I closing this issue.
