### ISSUE TITLE
add new cmdlet to manage errorview

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11580]
in ps7 errorview is awesome but is painful to add custom errorview 

sometimes we need to change errorview for example diplay in dialogbox or change the display 

```
add-errorview -name <string> -scriptblock <scriptblock> 
remove-errorview -name <string>
```

**Comment by iSazonov** [comment]
You could use `Update-FormatData`

**Comment by p0W3RH311** [comment]
> Update-FormatData

i known but it use xml and its pain to use xml 

with add-errorview first it specific to errorview, second it not use xml at all but scriptblock

**Comment by SteveL-MSFT** [comment]
`ErrorView` simply leverages the existing formatting system.  I don't know if it makes sense to have cmdlets specific to errorview.  I would rather make it easier to produce and update formatting.  We have some other issues thinking about moving away from XML to a DSL for formatting, but it's not a priority right now.

**Comment by iSazonov** [comment]
@p0W3RH311  You could prototype the cmdlet in your repository and maybe publish on PowerShellGet. Then we could continue the discussion.
