### ISSUE TITLE
Add Export-TypeData Cmdlet

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#11593]
# Summary of the new feature/enhancement

The format and extended type system have the following cmdlets however, there is not an `Export-TypeData` cmdlet to create `ps1xml` files like the format system.

* Get-TypeData
* Get-FormatData
* Remove-TypeData
* Update-TypeData
* Update-FormatData
* Export-FormatData

# Proposed technical implementation details (optional)

**Comment by jdhitsolutions** [comment]
I have been using this module https://github.com/jdhitsolutions/PSTypeExtensionTools to work with custom type extensions. Although, I'd prefer native commands.
