### ISSUE TITLE
incorrect behaivior variables

### ISSUE THREAD

**Issue by Hansiedown** [PowerShell/PowerShell#11591]
FilesFolder = "C:\temp"
$ColFiles =Get-ChildItem -Path $FilesFolder
ForEach ($TheFile in $ColFiles)
    {
    Write-Host $TheFile
    }
```powershell

```

# Expected behavior

variable $TheFile should only contain the filename (same as poweshell 5.1)

```

# Actual behavior

variable $TheFile contains FilesFolder **and** filename 

```
# Environment data

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by iSazonov** [comment]
Compare `$ColFiles[0].ToString()` output in PowerShell Core and Windows PowerShell: first returns full path, second - file name.

The change was made in .Net Core for DirectoryInfo/FileInfo type. You can find a discussion and PR in CoreFX repo.
