### ISSUE TITLE
We need a story for script signing for non-Windows platforms

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#1159]
`Set-ExecutionPolicy` doesn't complain, but it doesn't do anything either. We should decide whether we're going to support script signing on non-Windows platforms (and I couldn't see an uber-issue for this, so I'm opening this.

I think the initial answer is "no", since we don't have a sip for non-Windows

**Comment by dragon512** [comment]
I would like to have support for signed scripts on non-windows platforms. I think it adds to the security and argument for people to use powershell on non-windows setups. I have been looking around for how todo this, but it seems that it is not supported at the moment

**Comment by ThomasNieto** [comment]
Are there any plans to implement this?

**Comment by ThomasNieto** [comment]
@PaulHigin with Secrets Management module using Cryptography APIs cross-platform in .NET does this now allow PowerShell to check for script signatures on non-Windows?

**Comment by PaulHigin** [comment]
No, there is a lot more involved for signatures.  But .NET Crypto APIs is a step in the right direction.

**Comment by ThomasNieto** [comment]
Can we take a look at this issue again to get signing/validation on non-Windows? I saw this module has been published that validates signatures so it should be possible now to add this feature.

https://www.powershellgallery.com/packages/OpenAuthenticode
