### ISSUE TITLE
Compare-Object should support named calculated properties 

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11607]
# Summary of the new feature/enhancement

`Compare-Object`'s `-Property` parameter already supports calculated properties, but doesn't allow them to be _named_.

This is unfortunate, because the calculated property is currently invariably named for the script _block's literal text_ (key name `e` is short for `Expression`):

```powershell
PS> Compare-Object @{p=1} @{p=2} -property @{ Expression = { $_.p % 2 } }

 $_.p % 2  SideIndicator
---------- -------------
         0 =>
         1 <=
```

Note how `$_.p % 2` became the property name.

As with other commands that support calculated properties - e.g., `Select-Object` - it should be possible to name the property, via a `Name` or `Label` key (or prefix abbreviation thereof):

```powershell
# WISHFUL THINKING
PS> Compare-Object @{p=1}, @{p=2}  @{p=2}, @{p=4} -property @{ n = 'Mod2'; e = { $_.p % 2 } }

Mod2        SideIndicator
---------- -------------
         0 =>
         1 <=
```

Written as of PowerShell Core 7.0.0-rc.1.

**Comment by iSazonov** [comment]
MshParameter -> PSPropertyExpression
I think it is here
https://github.com/PowerShell/PowerShell/blob/70d4a899310f5460700f0be8cba5a2af1d4a0305/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs#L347

Do we lost the same for Sort-Object/Select-Object https://github.com/PowerShell/PowerShell/issues/6855#issuecomment-389684616 ?

**Comment by mklement0** [comment]
Thanks, @iSazonov. I don't think `Sort-Object` needs fixing, it already supports the `expression` and `ascending` / `descending` hashtable keys, which is all that is needed, given that this "property" is used solely to facilitate sorting, and doesn't appear in the output (and therefore needs no name).

https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3383#issuecomment-445467300 summarizes what hashtable keys are supported by what cmdlets.

**Comment by mklement0** [comment]
P.S.: At least _functionally_ `Sort-Object` works fine; don't remember whether there is a good reason to modify the _implementation_.

Come to think of it, the `Measure-Object` implementation actually falls short:

* It currently accepts only a _script block_ and not also a _hashtable_ with the scriptblock stored  in the `Expression` entry.

* Aside from this asymmetry with `Sort-Object`, for instance, `Measure-Object` could also benefit from supporting the `Name` entry, given that the property name is part of the output too.

I'll open a new issue.

**Comment by mklement0** [comment]
I've opened an issue for `Measure-Object`: #11617
