### ISSUE TITLE
Public APIs missing in PowerShell 7.0.0-rc.2 since 6.2.3

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#11619]
I've run an analysis comparing public APIs available in PowerShell 6.2.3 vs 7.0.0-rc.2 and there are some public APIs that are missing.

While this is in many cases intentional, and likely to not be an issue, some may affect programs and tools trying to link against multiple versions of PowerShell (modules and some hosts). Trying to reference such an API would cause a sudden crash in one of these tools (the hard part being that the point at which the crash occurs may be hard to control).

I'm still refining the analysis, but here is a list of classes and members that have been removed:

## Types

- ~~`System.Management.Automation.PSJobProxy`~~ [Workflow]
- ~~`System.Management.Automation.PSChildJobProxy`~~ [Workflow]
- ~~`System.Management.Automation.JobDataAddedEventArgs`~~ [Workflow]
- `System.Management.Automation.PowerShellStreamType` (arguably workflow, but has generic name and namespace. Removed in https://github.com/PowerShell/PowerShell/pull/10083).
- ~~`System.Management.Automation.WorkflowInfo`~~ [Workflow]
- ~~`System.Management.Automation.Runspaces.PSSessionType` (arguably workflow, but possibly worth restoring with single value depending on how it's used)~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is workflow-specific

## Fields

- ~~`System.Management.Automation.CommandTypes::Workflow`~~ [Workflow]
- ~~`System.Management.Automation.PSEngineEvent::WorkflowJobStartEvent`~~ [Workflow]
- ~~`System.Management.Automation.ModuleType::Workflow`~~ [Workflow]
- ~~`System.Management.Automation.Internal.DebuggerUtils::SetVariableFunction`~~ [Internal]
- ~~`System.Management.Automation.Internal.DebuggerUtils::RemoveVariableFunction`~~ [Internal]
- ~~`System.Management.Automation.Internal.DebuggerUtils::GetPSCallStackOverrideFunction`~~ [Internal]
- ~~`System.Management.Automation.Internal.PSMonitorRunspaceType::WorkflowInlineScript`~~ [Internal/Workflow]

## Methods and constructors (captures events and properties)

- ~~``Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache::ImportClasses(System.String,System.Tuple`2[System.String,System.Version],System.Collections.ObjectModel.Collection`1[System.Exception])``~~ [Internal]
- ~~``Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache::GetCachedClasses()``~~ [Internal]
- ~~``Microsoft.PowerShell.Commands.NewModuleManifestCommand::get_ClrVersion()``~~ **Fixed in https://github.com/PowerShell/PowerShell/pull/11623**
- ~~``Microsoft.PowerShell.Commands.NewModuleManifestCommand::set_ClrVersion(System.Version)``~~ **Fixed in https://github.com/PowerShell/PowerShell/pull/11623**
- ~~``Microsoft.PowerShell.Commands.RegisterPSSessionConfigurationCommand::get_SessionType()``~~ [Workflow]
- ~~``Microsoft.PowerShell.Commands.RegisterPSSessionConfigurationCommand::set_SessionType(System.Management.Automation.Runspaces.PSSessionType)``~~ [Workflow]
- ~~``Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods::GetTarget(System.Management.Automation.PSObject)`` (arguably internal, but not internally namespaced. Return type changed in https://github.com/PowerShell/PowerShell/pull/8789)~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is ok to remove
- ~~``System.Management.Automation.Debugger::SetBreakpoints(System.Collections.Generic.IEnumerable`1[System.Management.Automation.Breakpoint])``~~ **Fixed in https://github.com/PowerShell/PowerShell/pull/11622**
- ~~``System.Management.Automation.PowerShell::AsJobProxy()``~~ [Workflow]
- ~~``System.Management.Automation.ScriptBlock::set_IsFilter(System.Boolean)`` **Formerly threw InvalidOperationException. Should assess whether this is considered breaking. Changed in https://github.com/PowerShell/PowerShell/pull/9732**~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is not a real breaking change
- ~~``System.Management.Automation.ScriptBlock::set_IsConfiguration(System.Boolean)`` **Formerly threw InvalidOperationException. Should assess whether this is considered breaking. Changed in https://github.com/PowerShell/PowerShell/pull/9732**~~ Discussed with @daxian-dbw and @adityapatwardhan and decided that this is not a real breaking change
- ~~``System.Management.Automation.PSModuleInfo::get_ExportedWorkflows()``~~ [Workflow]
- ~~``System.Management.Automation.Tracing.Tracer::EndpointRegistered(System.String,System.String,System.String)`` **Removed in https://github.com/PowerShell/PowerShell/pull/9618**~~ Discussed with @daxian-dbw, @adityapatwardhan and @JamesWTruher and decided that being a workflow-oriented, Windows-only API, this break is ok
- ~~``System.Management.Automation.Internal.DebuggerUtils::GetWorkflowDebuggerFunctions()``~~ [Internal/Workflow]

I'll continue this analysis to look into custom attributes

**Comment by SteveL-MSFT** [comment]
The workflow and related ones are deliberate and approved by committee.  Internal ones should not be considered public.

**Comment by rjmholt** [comment]
The only missing custom attributes are of type `System.Management.Automation.Tracing.EtwEvent`. I assume this is by design.

**Comment by rjmholt** [comment]
@iSazonov https://github.com/PowerShell/PowerShell/commit/afa76dec2374df8dadc1629bd7050c5db11c0694#diff-c347101d4edffbab7f8e3874da0d0671 changes the signature of `System.Management.Automation.Tracing.Tracer::EndpointRegistered(System.String,System.String,System.String`. Is that workflow related? Is that an API we should restore? (Easy to add it back as an overload)

**Comment by iSazonov** [comment]
@rjmholt See the comment https://github.com/PowerShell/PowerShell/pull/9618#discussion_r284914035 
It is side effect from PSTypeSession type removing.
It is not long discussed but @PaulHigin and me did not find why we should keep this.

My current thought is the we could replace huge in our code with ILogger. The change will a big break change but it is portable, well documemnted and promisingly.

**Comment by rjmholt** [comment]
@iSazonov I’m viewing on mobile so might not be seeing it, but I can’t find a comment there about this Tracing API. It doesn’t seem to be directly related to Workflow, but I assume that it is in some way.

However, if that API is useful without workflow in some way, I would imagine we should keep it. But I don’t know that Tracing API, how it’s used, whether it’s relevant to SDK users or whether it makes sense without Workflow.

**Comment by iSazonov** [comment]
@rjmholt Thoughts was that if we remove Workflow it makes no sense to keep the parameter too because it is unlikely that anybody uses something from the tracer API - very specific and complex API. That's why I shared the idea of ​​switching to ILogger API - more simple, standard and effective API.
I do not mind strictly reverting the change. Yes, we could add new overload and mark old as obolete.

**Comment by iSazonov** [comment]
PowerShellStreamType was removed as Workflow only related and that was approved.

**Comment by iSazonov** [comment]
Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods::GetTarget - names explicitly says that it is internal.

**Comment by adityapatwardhan** [comment]
I believe that `Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods::GetTarget` was available publicly as it was referenced in the types XML, when we used to have an XML.
