### ISSUE TITLE
Install issues with MSIX

### ISSUE THREAD

**Issue by steskalja** [PowerShell/PowerShell#11615]
When attempting to install Powershell 7.0 RC2 using the MSIX installer. I get this message: "This app package is not supported for installation by App Installer because it uses certain restricted capabilities."

**Comment by vexx32** [comment]
The MSIX currently can only be installed using the `Add-AppXPackage` cmdlet from a PowerShell window, and only if Developer Mode is enabled in the WIndows 10 settings.

I believe the outstanding issue has been sufficiently fixed for the full release, whereupon you can download it directly from the Windows 10 Store. I think directly downloading the MSIX may still have the same restrictions, but the Store version should install automatically. 🙂
