### ISSUE TITLE
Feature Request: Mounting bde drives on Linux

### ISSUE THREAD

**Issue by AndrewL2018** [PowerShell/PowerShell#11612]
# Summary of the new feature/enhancement

As a Linux (Ubuntu mainly) user I want to be able to read/write to BitLocker encrypted drives so that I can interact with my BitLocker encrypted drives while running from Linux.

# Proposed technical implementation details (optional)

Right now, Ubuntu (and few other linux distributions) have a program in the normal repositories that allows for finding BitLocker encrypted drives (gives the location to the volume, such that it may look like /dev/sda3 ), and allows mounting those drives as either read-only or read and write.

The program I speak of is named [Dislocker](https://github.com/Aorimn/dislocker), which uses a [GNU GPL v2 license](https://github.com/Aorimn/dislocker/blob/master/LICENSE.txt) (links lead to github pages). 

Dislocker may be useful in figuring out how to get started on implementing bde drive mounts for Linux.

**Comment by iSazonov** [comment]
We can not use any software licensed as GNU in the repo. Also it seems the applications is developed based on reverse engendering, we should use only MSFT public API for compliance.

**Comment by AndrewL2018** [comment]
> We can not use any software licensed as GNU in the repo. Also it seems the applications is developed based on reverse engendering, we should use only MSFT public API for compliance.

I'm not suggesting using the program I mentioned. I was only saying the functionality of the feature I'm requesting should act similar to it.
