### ISSUE TITLE
Unwanted empty lines in output of errors with $ErrorView=ConciseView

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#11610]
Unwanted empty lines in output of errors with $ErrorView=ConciseView

This issue is similar to "fixed" https://github.com/PowerShell/PowerShell/issues/11377 \
In v7.0.0-rc.2 the result is slightly different but the empty line is still there.

# Steps to reproduce

```powershell
# make sure it's the new default ConciseView
$ErrorView = 'ConciseView'

try {
    throw 'Oops!'
}
catch {
    $_
}
```

# Expected behavior

The error output has no unexpected and unwanted empty lines:

```none
Exception: ...\1.ps1:5
Line |
   5 |      throw 'Oops!'
     |      ~~~~~~~~~~~~~
     | Oops!
```

# Actual behavior

The error output has an unexpected and unwanted empty line:

```none
Exception: ...\1.ps1:5
Line |
   5 |      throw 'Oops!'

     |      ~~~~~~~~~~~~~
     | Oops!
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
I've seen this too in our build logs.

**Comment by iSazonov** [comment]
It is here https://github.com/PowerShell/PowerShell/blob/70d4a899310f5460700f0be8cba5a2af1d4a0305/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L769

**Comment by iSazonov** [comment]
@nightroman Can you add a comment why the issue was closed? Is it resolved?
