### ISSUE TITLE
-FollowRelLink does not work if Link header uses rel=next (no quotes) instead of rel="next"

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShell#11629]
# Steps to reproduce

Make a request to a server that returns `Link: <some url>; rel=next`.
This is valid according to the grammar: https://tools.ietf.org/html/rfc5988#section-5

> relation-types = relation-type
>                | <"> relation-type *( 1*SP relation-type ) <">
> relation-type  = reg-rel-type | ext-rel-type
> reg-rel-type   = LOALPHA *( LOALPHA | DIGIT | "." | "-" )
> ext-rel-type   = URI

The quoting is not required.

# Expected behavior

Should follow

# Actual behavior

Doesn't follow

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is here https://github.com/PowerShell/PowerShell/blob/70d4a899310f5460700f0be8cba5a2af1d4a0305/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1832

**Comment by StevenLiekens** [comment]
This is still broken for me in v7.1.4, see #15972

The PR where the quote marks were made optional did not resolve the issue.
