### ISSUE TITLE
add variable modifier $module:

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11625]
$module:var display variable 'var' in module we can use The ExecutionContext variable to display 'var' variable but modifier $module: is better

**step to reproduce:**
```

$m = new-module {
  $var = 'in module'
} | ipmo -force -PassThru

$var = 'in script'

$sb={
 $var = 'in scriptblock'
 Write-Host $local:var 
 Write-Host $script:var 
 Write-Host $module:var
}

&$sb 

```
**===output===**

```
in scriptblock
in script
in module
```

**Comment by vexx32** [comment]
@p0W3RH311 how will we determine _which_ module to pull a variable from? There could be any number of modules loaded at a given time. Searching through all of them would take quite some time, I'd imagine. Also, how would you handle having multiple modules loaded which each have a variable by the same name?

**Comment by p0W3RH311** [comment]
> 
> 
> @p0W3RH311 how will we determine _which_ module to pull a variable from? There could be any number of modules loaded at a given time. Searching through all of them would take quite some time, I'd imagine. Also, how would you handle having multiple modules loaded which each have a variable by the same name?

we can use this syntax for example

` Write-Host $module:nameofmodule:var`

**Comment by vexx32** [comment]
In that instance, how would you expect `$module:nameofmodule` to behave?

**Comment by mklement0** [comment]
There's generally no reason to access a module's _non-exported_ variables - a module's non-exported module's should be considered private.

If really needed, you can already access such variables, and I think that mechanism is sufficient, given how exceptional the use case is (tip of the hat to @SeeminglyScience's [blog post](https://seeminglyscience.github.io/powershell/2017/09/30/invocation-operators-states-and-scopes)):

```powershell
PS> & $m { $var }
in module
```
