### ISSUE TITLE
CmsCommands - simple fix for linux

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#11630]
At the moment [CmsCommands](https://github.com/PowerShell/PowerShell/blob/3923ca172854b8f3b00dcd02b0f1829917758f10/src/Microsoft.PowerShell.Security/security/CmsCommands.cs) (Encrypting/Decrypting text with X509 cert) are only available on Windows. Those commands can be implemented with standard .net libraries, the only reason it's not working on Linux systems is that Util function that resolves certificate from string is using Cert: provider (which only implemented for Windows). Replacing cert: with X509Store class will make it work on linix systems.

here is the Util:
https://github.com/PowerShell/PowerShell/blob/d58a82ad19fbfad81e85778c8b08cb1b28f58fce/src/System.Management.Automation/security/SecuritySupport.cs#L972

There are few lines referring to Cert:, for example

```
           string certificatePath = sessionState.Path.Combine("Microsoft.PowerShell.Security\\Certificate::CurrentUser\\My", _identifier);
                if (sessionState.InvokeProvider.Item.Exists(certificatePath))
                {
                    foreach (PSObject certificateObject in sessionState.InvokeProvider.Item.Get(certificatePath))
                    {
                        certificates.Add(certificateObject);
                    }
                }
```
Issue can be fixed by replacing it with something like that:
```
X509Store store = new X509Store(StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
 certificatesToProcess = store.Certificates.Find(X509FindType.FindBySubjectName,_identifier,false);
```

This only affect ResolveFromSubjectName and ResolveFromThumbprint methods, so change is relatively small. I played with it on Ubuntu and didn't noticed any extra problems.

**Comment by iSazonov** [comment]
@mikeTWC1984 Welcome to contribute! Pull PR and we will discuss in depth.

**Comment by mikeTWC1984** [comment]
OK, here is the PR
https://github.com/PowerShell/PowerShell/pull/11643

There is another method (bool CertIsGoodForEncryption) in CmsUtils that is using native calls (probably wont work on linux). It basically checks this condition:
```
 Encryption certificates must contain the Data Encipherment or Key Encipherment key usage, and include the Document Encryption Enhanced Key Usage (1.3.6.1.4.1.311.80.1)
```

But that seem to be overkill, all these key usages can be retrieved from  X509Certificate2  cert instance. More over, this check is not really needed to encrypt/decrypt data (I guess it's just following MSFT standards).  AFAIK any RSA key pair can be used for CMS encryption. For example openssl generated keys can be used for PKI encryption (using openssl cms) without setting any extra options . I guess for non-Windows systems this check can always return true (this would also be the easiest fix), since they mainly generate certs using openssl anyway.

**Comment by mrhockeymonkey** [comment]
linking #11656

**Comment by TravisEz13** [comment]
@mikeTWC1984 This is a security standard.  Using a certificate not marked this way to encrypt or decrypt is a threat.  Key Usage ensures that you only use a properly secured cert (what every that standard is for your org) to do that kind of operation.  Allowing any cert, bypasses that assurance.

**Comment by TravisEz13** [comment]
This type of attack was used in the Flame virus against Windows Update Agent/WSUS

**Comment by mikeTWC1984** [comment]
@TravisEz13  Make sense. Since you mentioned this is a security concern - EKU check is implemented in the CMDlet itself, the actual .net class (EnvelopedCMS) is not checking it. So even Unprotect-CmsMessage would skip EKU check if cert is in the CurrentUser\My store. 

I think we can close this, since the PR above  replaced native calls (Windows only)  with pure .net
