### ISSUE TITLE
Support for RemoteSession over SSH with Password 

### ISSUE THREAD

**Issue by Zetanova** [PowerShell/PowerShell#11635]
# Summary of the new feature/enhancement

It is currently possible with pwsh to connect from linux to windows over SSH
with an pubkey or with the help of a regular password.
Both methods are working, but the auth method with a password has some benefits
because the remote shell will run under the users credentials with a valid windows token.

Commands that require a valid windows credentials token will then work
Get-VM -ComputerName @("server1", "server2", "server2")

# Proposed technical implementation details (optional)

Option1:
SSHConnectionInfo does currently not allow to set an user password. 
it could await the output of "ssh" process on "Password:" and write
the password into the input stream

Option2:
Some command to upgrade the pssession with a valid WindowsUserToken
like "Switch-User"

**Comment by Nova-Logic** [comment]
This is really needed feature
