### ISSUE TITLE
Format issues

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#11632]
# Steps to reproduce

```powershell

```

# Expected behavior

![Screenshot_20200120_132849](https://user-images.githubusercontent.com/26913892/72701173-5f152100-3b89-11ea-9b2a-88c4cd9d798c.jpg)

# Actual behavior

![Screenshot_20200120_220208](https://user-images.githubusercontent.com/26913892/72732459-b985a000-3bd0-11ea-8df3-8460d90b4fa1.jpg)

# Environment data

```none
PSVersion                      7.0.0-daily.20200118
PSEdition                      Core
GitCommitId                    7.0.0-daily.20200118
OS                             Linux 4.9.112-perf #1 SMP PREEMPT…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@he852100 We have a template for new issues. Please add all info the template requests.
