### ISSUE TITLE
Powershell is not handling process termination on Linux Agents and is not waiting.

### ISSUE THREAD

**Issue by v-kyljon** [PowerShell/PowerShell#11639]
When dotnet is launched in a powershell terminal on Linux build/release agents there is a disconnect occurring where dotnet is not terminating its own processes on completion and causing the agent job to run on the powershell step until it times out. 

We have determined that the powershell terminal exits upon execution of the last line of code in the script and orphans the dotnet processes which are collected by Init.

Stop-Process works as long as the process is ready to be exited no later than the last line of code in the script.

The following cmdlets will not stop the process and exit the session on Linux agents:
return
break
exit
$host.SetShouldExit()
$host.Exit()
The [-ErrorAction stop] argument will also fail.

**Comment by iSazonov** [comment]
Perhaps the comment helps you https://github.com/dotnet/cli/issues/9458#issuecomment-396324918
