### ISSUE TITLE
Building PS on other distros (Linux Mint 19)

### ISSUE THREAD

**Issue by leoossa** [PowerShell/PowerShell#11655]
The script build.psm1:
[build.psm1](https://github.com/PowerShell/PowerShell/blob/master/build.psm1)
from instruction of building:
[Build PowerShell on Linux](https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md)
checks for supported distros or throws error for not supported ones:

` 
        if( -not(
            $environment.IsDebian -or
            $environment.IsUbuntu -or
            $environment.IsRedHatFamily -or
            $environment.IsSUSEFamily -or
            $environment.IsAlpine)
        ) {
            throw "The current OS : $($LinuxInfo.ID) is not supported for building PowerShell."
        }
    }`

apparently Linux Mint is based on Ubuntu, then if I commented out 'throw' statement I was available to build it on Linux Mint correctly.

**Comment by iSazonov** [comment]
PowerShell support follow .Net Core support. Currently Mint is not supported in .Net Core repo.

**Comment by ThomasNieto** [comment]
@iSazonov correct me if I'm wrong but it looks as though .NET Core 3.0 supports Linux Mint 18+.

https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md

**Comment by iSazonov** [comment]
@ThomasNieto Great! Thanks!

We have special issue template to request adding support for new distribution - please open new issue with the template.

**Comment by ThomasNieto** [comment]
@iSazonov created https://github.com/PowerShell/PowerShell/issues/11673 and https://github.com/PowerShell/PowerShell/issues/11672 for Linux 18+ support. Let me know if you need another for Linux Mint 19.

**Comment by iSazonov** [comment]
@ThomasNieto Great!
