### ISSUE TITLE
decorator in function

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11650]
this decorator are a way of wrapping a function in another one. Decorators are very powerful and useful since it allows programmers to modify the behavior of function . Decorators allow us to wrap another function in order to extend the behavior of wrapped function, without permanently modifying it. this is an example (we can use measure-command but this example demonstrate this new technique):

```
function timeExecution([scriptblock]$fn) {
	
 
	function inner([scriptblock]$fn) {

		$begin = [Diagnostics.Stopwatch]::StartNew() 
		
		&{$fn} 

        $end = $sw.Stop()
  		"Total time taken in : $(&{$fn.functionName }) $($end - $begin)"

	   inner
    }
}

 function mainfunc($n) :timeExecution {
	 sleep $n
	'in main function'
 }


mainfunc 3
```

i know this breaking change but it allow new possibilities to PS7+ ,  scriptblock object must have new members isfunction and functionName to perform this technique

**Comment by vexx32** [comment]
Hmm. I don't think you need to make any changes. You just need to change what you're passing around.

Functions are the upper layer here - a FunctionInfo object contains both a name and a scriptblock. So while scriptblocks can contain function _declarations_, they cannot contain functions directly.

Once a function is declared, you can retrieve the FunctionInfo object using `Get-Item Function:\Function-Name` -- it's a standard PSDrive you can retrieve items from kind of like the filesystem.

If you pass function objects themselves around, I think you'll be able to mimic the kind of behaviour you're looking for. 🙂

**Comment by p0W3RH311** [comment]
> 
> 
> Hmm. I don't think you need to make any changes in PS itself to accomplish this. You just need to change what you're passing around.
> 
> Functions are the upper layer here - a FunctionInfo object contains both a name and a scriptblock. So while scriptblocks can contain function _declarations_, they cannot contain functions directly.
> 
> Once a function is declared, you can retrieve the FunctionInfo object using `Get-Item Function:\Function-Name` -- it's a standard PSDrive you can retrieve items from kind of like the filesystem.
> 
> If you pass function objects themselves around, I think you'll be able to mimic the kind of behaviour you're looking for. slightly_smiling_face

thanks for the information but there are still some problems because i am trying to pass a function as a parameter to another function but my workaround is  scriptblock its not perfect and it will be awesome if there is a magic variable like $func and this variable contains information about the main function for example:

```
function timeExecution {
	
 
	function inner {

		$begin = [Diagnostics.Stopwatch]::StartNew() 
		
		&{$func} 

        $end = $sw.Stop()
  		"Total time taken in : $($func.functionName ) $($end - $begin)"

	   inner
    }
}

 function mainfunc($n) :timeExecution {
	 sleep $n
	'in main function'
 }
```



and the other problem how to mimic this syntax

` function mainfunc($n) :timeExecution`
