### ISSUE TITLE
"Import-Module WebAdministration" fails with unexpected error

### ISSUE THREAD

**Issue by IanKemp** [PowerShell/PowerShell#11657]
# Steps to reproduce

```powershell
> Import-Module WebAdministration
```

# Expected behavior

The module is loaded, or gives an appropriate error message stating why it cannot be loaded.

# Actual behavior

Does not load the module, instead outputs an error message:

```none
Get-PSSession: The remote session with the name WinPSCompatSession  is not available.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please discuss in https://github.com/PowerShell/PowerShellModuleCoverage/issues/14

**Comment by IanKemp** [comment]
@iSazonov my issue was not with the failure to load the module, rather that the error doesn't make much sense. I've updated the title and description to reflect this.
