### ISSUE TITLE
Measure-Command should execute the given script block in a *child* scope, at least by opt-in

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11666]
`Measure-Command` currently unexpectedly executes the given script block (via the unfortunately named `-Expression` parameter, which should probably be given a `-ScriptBlock` alias) directly in the _caller's_ scope rather than in a _child_ scope.

That is, it effectively _dot-sources_ the given script block, which is unexpected and has two undesired consequences:

* It has side effects for the caller, notably variables created inside the script block lingering in the caller's scope.

* It distorts the measurement, because dot-sourced code executes noticeably more slowly - see #8911

I therefore suggest that we make `Measure-Command` run the given script block be run in a _child_ scope. If needed, a `-NoNewScope` switch (analogous to `Invoke-Command`'s) could be added as an opt-in for dot-sourced execution.

If there is concern that there is code out there that _relies_ on the side effects from execution of the given script block, the next best thing is to reverse the logic: keep dot-sourcing by default, offer a `-NewScope` switch.

# Steps to reproduce

```powershell
$($null = Measure-Command { $foo = 'hi' }; $foo) | Should -Not -Be 'hi'
```

# Expected behavior

The  test should pass.

# Actual behavior

The test fails, because the `$foo` variable created inside the script block was effectively created in the caller's scope, due to implicit dot-sourcing.

```none
Expected 'hi' to be different from the actual value, but got the same value.
```

# Environment data

```none
PowerShell Core 7.0.0-rc.2
```

**Comment by iSazonov** [comment]
I think the design comes from the scenario - user has a script and wrap one line in the cmdlet to see the line impact.

**Comment by mklement0** [comment]
That's a good point, @iSazonov  - I hadn't considered that scenario, I was looking at it from the perspective of "measure execution time of a self-contained piece of code", which is how I personally use it.

That said, even dot-sourced use of `Measure-Command` is of limited use, given that it suppresses the script block's output.

That is, you can't just wrap an existing line in `Measure-Command` and _generally_ expect the script to function normally (except for the additional `[timespan]` output with the timing result).

It would be a different story, if `Measure-Command` passed output _through_ and instead used, say, the information stream to report the timing.

The question is what the backward-compatibility impact is, but I can see two distinct modes as being helpful:

* _with_  a hypothetical `-PassThru` switch:
   * dot-source the script block
   * pass the output through
   * output the timing result (`[timespan]`) via the information stream (where it can be retrieved as such via the `System.Management.Automation.InformationRecord`'s instances `.MessageData` property), or, perhaps with an always-on verbose message?

* _without_ that switch:
  * Like the current behavior, except that the script block will run in a _child_ scope.

**Comment by SeeminglyScience** [comment]
The scenarios where it'll actually impact the time aren't super common, and changing this won't exactly make `Measure-Command` particularly reliable.  I don't think the breaking change is worth it personally.

**Comment by mklement0** [comment]
@SeeminglyScience. Based on your clarification in  https://github.com/PowerShell/PowerShell/issues/11663#issuecomment-577799560, I agree that the performance impact shouldn't drive the decision (not least because https://github.com/PowerShell/PowerShell/issues/8911#issuecomment-464954324 outlines a potential remedy).

The - at least to me - potentially unexpected pollution of the caller's scope is more problematic, however.

At the very least, documenting the behavior is certainly called for - see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5345

Assuming a user is aware of the problem, they can always do `Measure-Command { & { $foo = 'hi' } }` to force running in a child scope, but, needless to say, that is awkward.

So at the second least, if you will, a `-NewScope` switch would be helpful.

Note that this would be the _inverse_ of `Invoke-Command`'s behavior, which runs a script block in a child scope by default, and offers `-NoNewScope` as an opt-in for dot-sourcing - and that inversion is another reason why the current behavior is problematic (as are other inconsistencies in scoping behavior - see #7157)

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience. Based on your clarification in [#11663 (comment)](https://github.com/PowerShell/PowerShell/issues/11663#issuecomment-577799560), I agree that the performance impact shouldn't drive the decision (not least because [#8911 (comment)](https://github.com/PowerShell/PowerShell/issues/8911#issuecomment-464954324) outlines a potential remedy).
> 
> The - at least to me - potentially unexpected pollution of the caller's scope is more problematic, however.

Eh, `Invoke-Command` is the only default one I know of that doesn't (assuming the invocation happens immediately and in the current process).
> 
> At the very least, documenting the behavior is certainly called for - see [MicrosoftDocs/PowerShell-Docs#5345](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5345)

Definitely.

> So at the second least, if you will, a `-NewScope` switch would be helpful.
>
> Note that this would be the _inverse_ of `Invoke-Command`'s behavior, which runs a script block in a child scope by default, and offers `-NoNewScope` as an opt-in for dot-sourcing - and that inversion is another reason why the current behavior is problematic (as are other inconsistencies in scoping behavior - see #7157)

I think it's infrequently enough required that the slight awkwardness of wrapping the block isn't that big of a deal.  The `Invoke-Command` parameter makes sense because you can't undo creating a new scope through the language, like you can the inverse.

**Comment by mklement0** [comment]
I think the primary problem - at least to me - is that I do expect child-scoped invocation and no side effects.

I see your point re `Invoke-Command` being the only one (and the technical necessity for it), still I think it's generally more sensible to default to invocation in a child scope, except in cases intimately connected to the caller's scope (`%`, `?`, calculated properties).

Fair enough, though.

I've added the nested-block technique to the docs issue, and I'm closing this.
