### ISSUE TITLE
Linux Mint 19.3 Support

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#11672]
# Details of the Distribution

- Name of the Distribution: Linux Mint
- Version of the Distribution: 19.3
- Processor Architecture (One per request): 64
- [x] **Required** - https://github.com/PowerShell/PowerShell-Docker/issues/369 - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker
- The following is a requirement for supporting a distribution **without exception.**
  - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and 
  the PowerShell comittee will review the request.
  - [x] The version of the Distribution is supported for at least one year.
  - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] Lifecycle updated
- [ ] Documentation Updated

**Comment by iSazonov** [comment]
> Version of the Distribution: 18+

Current release 19.3. @ThomasNieto Please update the request.

List all versions and EOLs https://linuxmint.com/download_all.php

**Comment by ThomasNieto** [comment]
@TravisEz13 when do you think Linux Mint can be added?

**Comment by TravisEz13** [comment]
@PowerShell/powershell-committee Can your review this request to build and support and additional package and docker image?

**Comment by SteveL-MSFT** [comment]
@ThomasNieto what exactly are you requesting?  We expect the Ubuntu docker image, deb pkg, and Snap pkg to work already with Mint.

**Comment by ThomasNieto** [comment]
.NET lists Linux Mint as a separate supported platform. If you think the Ubuntu binaries will work on Linux Mint then I would say this request would be to add Linux Mint to the README as a supported platform.

**Comment by iSazonov** [comment]
> add Linux Mint to the README as a supported platform.

We don't tests on Mint so we can not say it is supported but we could add in README that PowerShell is supported by Mint community.

**Comment by ThomasNieto** [comment]
Any and all requirements for that platform to be officially supported by powershell would need to be done. This request is for Mint to be officially supported by powershell just like it's listed for dot net.

**Comment by JamesWTruher** [comment]
https://github.com/orgs/PowerShell/teams/powershell-committee has reviewed this request, and our current position is that adding any new release to our current list of supported platforms would be cost prohibitive.

**Comment by TravisEz13** [comment]
I think the current `deb` package should work as a community supported package for Mint.
