### ISSUE TITLE
Create a user-modifiable Start Menu shortcut

### ISSUE THREAD

**Issue by darzgood** [PowerShell/PowerShell#11680]
Changing shell properties (color, font, cursor, etc) does not seem to work when running from the windows start menu shortcut. It brings up an error dialog box as shown below. However, if starting the shell from the install location, C:\Program Files\PowerShell\7-preview, does not bring up the error.
Running PowerShell 7.0.0-rc.2

# Steps to reproduce
Open powershell from C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell. Right-click -> properties. Change any option and click ok. 
![Annotation 2020-01-25 200820](https://user-images.githubusercontent.com/44272361/73129873-4064bf00-3fbb-11ea-92f0-1ca6d9135db9.jpg)

``` 

```

# Expected behavior
Changes appropriate property.
```none

```

# Actual behavior
Launches a Windows error dialog, but, in most cases, proceeds to change the property. However, with several elements, particularly the cursor type, the change is not permanent and it reverts to the default after any key is pressed. 
![Annotation 2020-01-25 200819](https://user-images.githubusercontent.com/44272361/73129886-ad785480-3fbb-11ea-8842-870ef411afae.jpg)
 
```none

```

# Environment data
```Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
This is because the shortcut is created for _all users_, rather than in the current user's own program files.  
The console tries to write something back to where the shortcut was found. IIRC, if you go to the EXE file and launch it without using the short cut, you get a set of defaults and changes are saved to the registry. 
If the shortcut is in the users' programs (as with cmd or windowsPowerShell , IIRC) the user has write access by default, but not if it is in _all Users_ . 

The cure for this would be for setup to add PowerShell to the current user's profile and the default for new users.

**Comment by mklement0** [comment]
I think modifying the installer to create user-specific shortcuts is definitely called for.

In the meantime, here's a workaround:

**To create a user-modifiable Start Menu shortcut**:

```powershell
# Create a user-specific Start Menu shortcut
Get-Item "$env:ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\*lnk" |
  Copy-Item -Destination "$env:APPDATA\Microsoft\Windows\Start Menu\Programs"
```

This user-specific copy effectively shadows the all-users one in your Start Menu, and PowerShell windows launched from it do permit persisting console settings via their system menu.

**To pin a user-modifiable shortcut to the task bar** (alternatively or in addition):
 * Start PowerShell via the (effectively read-only) Start Menu shortcut.
 * Right-click on the running task and select `Pin to taskbar`
   * At that point a _user-specific copy_ of the shortcut (`*.lnk` file) is created, as a pinned taskbar item, in the following location:
        * `"$env:APPDATA\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"` 
    * **Important**: 
       * Close the open window and launch a new one via the new pinned shortcut before trying to modify settings.
       * The mere act of _un_-pinning deletes this user-specific shortcut file again.
       * Even if you create a pinned item from a user-specific Start Menu shortcut, an independent shortcut file is created, with independent settings.

**Comment by mklement0** [comment]
@bergmeister, are you aware of this?
