### ISSUE TITLE
support nested expansion for variable

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11695]
to create a variable inside a variable for example:

```
$a = 'a var'
$b = 'a'
```

next if we want to display variable a we use simply $a. but suppose we want display the content of variable a from variable b ? 

### steps to reprduce

```
$a = 'powershell'
$b = 'a'
$c = 'b'
$d = 'c'

"$a" # normal expansion 
Invoke-Expression "`$$($b)"
Invoke-Expression ('$' + (Invoke-Expression "`$$($c)"))
Invoke-Expression ('$' +  (Invoke-Expression ('$' + (Invoke-Expression "`$$($d)"))))
```

### actual behaviour

```
powershell
powershell
powershell
powershell
```

it will be nice if we add for each expansion dollar $ example:

```
$a
$$b
$$$c
$$$$d
```

**Comment by vexx32** [comment]
This already exists. You can use Get-Variable to retrieve a variable by name.

I'm not sure I see how recursively resolving strings to variable names would be especially helpful, but I suppose in theory you could add a -Recurse switch to Get-Variable to do so.

Without a compelling reason to do so, though, and a thorough example, I can't say that I'd want this to be implemented, though. You can already implement your own recursive function to do something like this, so I don't see a great need to add something native to the language.

Looking up all those variable references would almost certainly have a pretty hefty perf impact at scale, too.

**Comment by mklement0** [comment]
Agreed, and let's not forget that [`Invoke-Expression` should generally be avoided](https://blogs.msdn.microsoft.com/powershell/2011/06/03/invoke-expression-considered-harmful/); how to better communicate that to users is currently being discussed in #11662

**Comment by scriptingstudio** [comment]
@p0W3RH311
$a = 'a var'
$b = '$a'
$ExecutionContext.InvokeCommand.ExpandString($b)

**Comment by mklement0** [comment]
Good point, @scriptingstudio, that's a more flexible alternative to `Get-Variable b -ValueOnly` (while neither satisfies the recursive requirement, I, like @vexx32, think that's not worth providing as a built-in feature).

You may be interested in #11693, which suggests providing a (more sophisticated version of) `Expand-String` as an official cmdlet.
