### ISSUE TITLE
What Version of the Nuget Server API is Required by PowerShell 6 and 7

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#11709]
I tried hard to find this information in this repository :(

I know that Get-PackageProvider on PowerShell 6 and 7 show that the *provider* is version 3.x.x.x and I hope, but hate to assume, this also means it can talk to NuGet Server API version 3.

Can someone please clarify if NuGet Server API V3 is fully supported by PowerShell 6 & 7?

/cc @TravisEz13 @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
This is more of a question for https://github.com/OneGet/oneget.  I don't believe the work to support Nuget v3 was complete for the Nuget provider in PackageManagement.  v3 is expected to be supported with PowerShellGetv3.

**Comment by DarwinJS** [comment]
Thanks for the pointer.  Looks like it does indeed support the server api V3: https://github.com/OneGet/NuGetProvider/blob/master/releasenotes.md
