### ISSUE TITLE
Cmdlet "Test-ComputerSecureChannel" not recognized

### ISSUE THREAD

**Issue by CKalis** [PowerShell/PowerShell#11706]
Screenshot from domain-joined Windows 10 Pro 1909 Build 18363.592 desktop PC. Latest Powershell 7.0.0-rc.2 (1/16/2020) from 64-bit MSI installer.

![Capture](https://user-images.githubusercontent.com/5816420/73296762-54d1d300-41d8-11ea-9a30-77729f1424bb.JPG)

As you can see, the v5 PowerShell auto-completes and runs it just fine. Also, Install-Module auto-completes it in v7.

I tried...
- Disabling all 3 experimental features I had enabled.
- Installing and testing with rc2 & rc1 versions (both MSI installer bit versions) on Windows Insider build 18975.1000 laptop.
- Using rc2 32-bit ZIP version on desktop PC.
- Rebooting both PCs & between installations.
- Installing and testing v6.2.4 (01/27/2020) 64-bit.
... with no change.

I've tried to rule out any issues on my end but let me know if I am just plain missing something or if it's working for you all. Willing to do further troubleshooting at any time.

Edit: Added last "I tried" item. Added "... with no change."

**Comment by iSazonov** [comment]
The cmdlet was removed because it is Windows-only and can not be ported on Unix-s.

/cc @SteveL-MSFT Have MSFT team plans to bring the cmdlet back? No compliance issues?

**Comment by SteveL-MSFT** [comment]
The source isn't even in this repo.  Took a look at the Windows code, it seems that it may have used private APIs in the past (and also WMI), but a quick search shows that the API is documented.  The WMI calls could be converted to CIM API calls.  Seems like it may be possible to bring it back.

**Comment by SteveL-MSFT** [comment]
The other option that may be better to explore is to selectively generate proxy functions for cmdlets in Managmeent/Utility that are in 5.1 and not in 7 using the new Windows compatibility path.

**Comment by ThomasNieto** [comment]
For compatibility reasons this cmdlet should come back even if it is Windows only, just like `Get-HotFix`.

**Comment by iSazonov** [comment]
Dup #11732
