### ISSUE TITLE
Install-Module not working on PowerShell Core 6 / PowerShell 7 preview

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#11718]
```powershell
PS C:\Users\Amir> Install-Module -Name PSCalendar

PackageManagement\Install-Package : The module 'PSCalendar' cannot be installed or updated because the authenticode signature of the file 'PSCalendar.psd1' is not valid.
At D:\program files\powershell\7-preview\Modules\PowerShellGet\PSModule.psm1:9683 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Please help me

**Comment by tommeadon** [comment]
It looks to me like you need to get the developer of PSCalendar to check their authenticode signature.

**Comment by xmha97** [comment]
> It looks to me like you need to get the developer of PSCalendar to check their authenticode signature.

I can't install any packages, fir example: `Install-Module -Name SqlServer`

![image](https://user-images.githubusercontent.com/23485114/73372838-123df280-42cd-11ea-9e48-7180647c7baa.png)

**Comment by vexx32** [comment]
Can you install the latest PS7 prerelease and see if you're still experiencing the same issue? 🙂 

If you are, please post the output from `$PSVersionTable` for that installation.

**Comment by xmha97** [comment]
> Can you install the latest PS7 prerelease and see if you're still experiencing the same issue? 🙂
> 
> If you are, please post the output from `$PSVersionTable` for that installation.

Yes
![image](https://user-images.githubusercontent.com/23485114/73373650-364e0380-42ce-11ea-8751-655c9f539c60.png)

**Comment by vexx32** [comment]
The latest version fo PS7 is RC2 -- please grab the latest release candidate of v7 from the https://github.com/PowerShell/PowerShell/releases page 🙂

**Comment by xmha97** [comment]
> The latest version of PS7 is RC2 -- please grab the latest release candidate of v7 from the https://github.com/PowerShell/PowerShell/releases page 🙂
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/49609581/96590180-07d7-11ea-89b1-2f719dc4bb9c"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[PowerShell/PowerShell](https://github.com/PowerShell/PowerShell)**PowerShell for every system! Contribute to PowerShell/PowerShell development by creating an account on GitHub.

Ok, I upgraded the Powershell Core.

![image](https://user-images.githubusercontent.com/23485114/73375909-cc375d80-42d1-11ea-8cf7-7084f4e75fc9.png)

**Comment by vexx32** [comment]
Thanks for checking! 😊

Can you also check `Get-ExecutionPolicy -List`?

**Comment by xmha97** [comment]
> Get-ExecutionPolicy -List

![image](https://user-images.githubusercontent.com/23485114/73377576-80d27e80-42d4-11ea-930f-31b8f34cf4b0.png)

**Comment by xmha97** [comment]
After reinstalling Windows 10, this issue resolved.
So I closing this issue.
