### ISSUE TITLE
Get-ChildItem follows ReparsePoints in PSSessions

### ISSUE THREAD

**Issue by thefirstben** [PowerShell/PowerShell#11717]
# Steps to reproduce

Enter-PsSession $ServerName
Get-ChildItem C:\Users\$env:USERNAME\AppData\  -Attributes !ReparsePoint -recurse -force -ErrorAction SilentlyContinue | Select-Object FullName

# Expected behavior

Shows the list of folders in AppData. 

# Actual behavior

The command works as expected locally, but when launching the same command in a PsSession it will loop on each reparse point.

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
@thefirstben What is remote point version? pwsh or Windows PowerShell?

**Comment by thefirstben** [comment]
PS7 is installed but when i remote the version that appear is use is 5.1. 
I'm pretty sure the issue is with all PS version 5.1+

**Comment by iSazonov** [comment]
@thefirstben Thanks! Could you please check with PowerShell 7.0 remote endpoint?

**Comment by thefirstben** [comment]
PS7 is installed on both source and destination, but i can't seem to be able to force version 7 on remote ps session : 
`Set-PSSessionConfiguration -Name PS7 -PSVersion 7.0`

> Set-PSSessionConfiguration: Cannot bind parameter 'PSVersion' to the target. Exception setting "PSVersion": "The value 7.0 is not valid for the PSVersion parameter. The available values are 2.0, 3.0, 4.0, 5.0, 5.1."

**Comment by iSazonov** [comment]
On remote:
```powershell
Enable-PSRemoting
Get-PSSessionConfiguration
```
Use the configuration name `<name>` on local:
```
Enter-PSSession ipam -ConfigurationName <name>
```

**Comment by thefirstben** [comment]
Thanks for the info, i had everything except i did not understand the configurationName option.
So i can confirm that the bug exists in remote PS 5.1 but not anymore in PS7.

Sorry about this. I will open a ticket with PS 5.1

**Comment by iSazonov** [comment]
>  i did not understand the configurationName option.

If you don't see useful description in docs please open new issue in PowerShell-Docs repo and ask to improve docs.

> Sorry about this. I will open a ticket with PS 5.1

Windows PowerShell is frozen. All new features will be only in PowerShell Core. I'd do not expect that MSFT team will back port such fixes (exception is security fixes).

> So i can confirm that the bug exists in remote PS 5.1 but not anymore in PS7.

I see the same. Thanks for your investigations!
