### ISSUE TITLE
[Linq.Enumerable]::Any() accepts [object[]] arrays only with an explicit cast

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11722]
Note: This is a minor issue in the grand scheme of things (and it's easy to work around it), and there may well be good reasons for the behavior (which would be good to know).

The problem is specific to `[object[]]` arrays (without cast); other types work fine.

# Steps to reproduce

```powershell
[object[]] $arr = 1, 2, 3  # omitting the type constraint has the same effect

# OK: with cast.
[Linq.Enumerable]::Any([object[]] $arr) | Should -BeTrue

# Fails without the cast.
[Linq.Enumerable]::Any($arr) | Should -BeTrue
```

# Expected behavior

Both tests should pass.

# Actual behavior

The method call in the 2nd command fails, because overload resolution fails (the generic type parameter is not inferred):

```
MethodException: Cannot find an overload for "Any" and the argument count: "1"
```

Curiously, in a directory that has _at least two_ items _one of which is a directory_ the following does _not_ fail:

```powershell
PS> [Linq.Enumerable]::Any((Get-ChildItem))
True
```

A type other than `[object]` works:

```powershell
PS> $intArr = [int[]] (1, 2, 3); [Linq.Enumerable]::Any($intArr)
True
```

# Environment data

```none
PowerShell Core 7.0.0-rc.2
```

**Comment by iSazonov** [comment]
Maybe related #10664
