### ISSUE TITLE
Set-MpPreference has no effect

### ISSUE THREAD

**Issue by BSG-75** [PowerShell/PowerShell#11727]
# Steps to reproduce

```powershell
Set-MpPreference -DisableRealtimeMonitoring $True
(Get-MpPreference).DisableRealtimeMonitoring
```

# Expected behavior
shows `True`, or at least report an error (and possibly a reason) of why it cannot be set

# Actual behavior
shows `False`, and in the Windows Defender's GUI Security Control Panel, the Real Time Monitoring option is still "ON"

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Screenshot:
![image](https://user-images.githubusercontent.com/2989995/73407624-0288d300-42fa-11ea-8e05-d41787c6b97f.png)

**Comment by iSazonov** [comment]
The cmdlet is not in the repo. Please use another resources to discuss/report the issue.
