### ISSUE TITLE
Invoke-WebRequest: Unable to Capture 401 Status Code as Variable

### ISSUE THREAD

**Issue by davespatz** [PowerShell/PowerShell#11729]
# Background
Doing error handing test for an RSS feed for FireEye ETP service. Doing check on status code to ensure that I'm getting a 200 back. Sample below is me purposely trying to get something other than a 200 so I can key off of that for error handling later. Below is quick/simple example of issue and very easy to reproduce.

# Steps to reproduce
$foo = (Invoke-WebRequest -Uri "https://fireeye.secure.force.com/cloudstatusFOO/?service_id=a930c000000U278AAC").StatusCode

# Expected behavior
Even though I'm getting a 401 (like I expect - error handling test case), I should just get back the status code string of "401" for variable $foo.

# Actual behavior
Invoke-WebRequest keeps spitting out the entire HTTP response body for the 401 unauthorized and I can't capture the 401 status code as a variable.

# Environment data
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
Perhaps you ask about SkipHttpErrorCheck parameter.

**Comment by davespatz** [comment]
Ahh! Yes that's it - thank you! Closing this.
