### ISSUE TITLE
Consider changing MarkdownOption cmdlets to handle ANSI strings the same way as PSReadLineOptions

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#11734]
# Summary of the new feature/enhancement

The way that ANSI formatting strings are configured is different between the PSReadlineOptions and MarkdownOptions cmdlets.

PSReadline requires that you include the escape character (`` `e ``) in the string. The MarkdownOptions cmdlet omit the escape character and throw an error if you try to include it (exception - see #11733). 

The PSReadline pattern this the way most people think about defining these escape sequences and predate the Markdown cmdlets.

# Proposed technical implementation details (optional)

This would be a breaking change but would be more consistent with existing patterns in PowerShell and decades of historical usage by ANSI artists.

**Comment by mklement0** [comment]
Good idea, and I don't think it would be a breaking change, just an enhancement: if the string starts with ESC, use it as-is; otherwise, prepend the ESC (as before).

**Comment by iSazonov** [comment]
@SteveL-MSFT said that there is a plan in next milestone to add a coloring API in engine. I guess it will be a code moved from PSReadline.
