### ISSUE TITLE
PowerShell 6.2.4 MSIX unable to Install-Module PowerShellGet -Force -AllowClobber

### ISSUE THREAD

**Issue by SebMouren** [PowerShell/PowerShell#11744]
Hello,
If I enter the line `Install-Module PowerShellGet -Force -AllowClobber` on a fresh MSIX Powershell 6.2.4 deployment, it sends me a `WARNING: The version '1.4.6' of module "PackageManagement' is currently in use. Retry after closing the applications` every time I try to install the module and doesn't install the module.
If I enter the line `Install-Module PowerShellGet -Force -AllowClobber -Verbose` **it works**: it deploy a more recent `PowerShellGet` module in the 'C:\Users\%USERNAME%\Documents\Powershell\Modules\PowerShellGet\2.2.3'

**Comment by iSazonov** [comment]
@SebMouren Please move the issue to PowerShellGet repo.

**Comment by SebMouren** [comment]
Yep, I'll do that but I forgot to mention that it doesn't append with a freshly installed MSI Powershell 6.2.4 deployment on another machine. It look like -before I dig in- that it is related to differences between the MSI and MSIX package.

**Comment by iSazonov** [comment]
MSI and MSIX can be very different in behavior.
