### ISSUE TITLE
Can't enter remote Powershell session from Linux to Windows

### ISSUE THREAD

**Issue by kobelobster** [PowerShell/PowerShell#11743]
I searched for this topic and found these issues

https://github.com/PowerShell/PowerShell/issues/2466
https://github.com/PowerShell/Win32-OpenSSH/issues/656

however they didn't fix my problem.
# Steps to reproduce

* Have a Linux VM with Ubuntu 18.04
* Have a Windows VM with Windows 1904
* Follow these steps inside the Windows VM https://docs.microsoft.com/en-gb/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#set-up-on-a-windows-computer
* Find out the IP address of the Windows VM (`192.168.70.23` in my case)
* Try to connect to the Windows VM with `Enter-PSSession -HostName "gitlab-runner-execut@192.168.70.23`
* Error appears.

When I use normal ssh `ssh gitlab-runner-execut@192.168.70.23` I can connect from Linux to Windows, just not when using `Enter-PSSession`.

I also tried at `Enter-PSSession` to also include theworkspace in the user name, so `Enter-PSSession -HostName DESKTOP-{IDENTIFIER}\gitlab-runner-execut@192.168.70.23` OR `Enter-PSSession -HostName 192.168.70.23 -UserName "DESKTOP-{IDENTIFIER}\gitlab-runner-execut"`
# Expected behavior

Successfull connecting to the remote PowerShell config

# Actual behavior

```none
Enter-PSSession : The background process reported an error with the following message: The SSH client session has ended with error message: Permission denied, please try again..
At line:1 char:1
+ Enter-PSSession -HostName "gitlab-runner-execut@192.168.70.23"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
+ FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerShell.Commands.EnterPSSessionCommand
```

# Environment data

In Linux
```none
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

In Windows
```none
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Inside the in `C:\Program Data\ssh\sshd_config` I removed the comment before `PasswordAuthentication` and my Subystem directive looks like this

`Subsystem powershell c:\progra~1\powershell\6\pwsh.exe -sshs -NoLogo -NoProfile` (This path exists, when I copy it into cmd/powershell and execute it, it opens a PS session)

**Comment by iSazonov** [comment]
@tzfrs Please try latest PowerShell 7.0 build on both endpoints.
