### ISSUE TITLE
CLI: when installed as a .NET global tool (dotnet tool), argument parsing is broken

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11747]
Note:

* This problem was discovered  by @gerardog, and this issue is meant to supersede #11569

* It only affects PowerShell _when installed as a .NET global tool_:
  * `dotnet tool install --global PowerShell`
  * Note: You need a .NET Core SDK 3.1 installation first.

# Steps to reproduce

```powershell
# NOTE: 
#  * Problem shows if `pwsh` was installed via `dotnet tool --global`
#  * Run from *cmd.exe* or *bash*
pwsh -noprofile -c "write-output 1 \"2 3\""
```

# Expected behavior

```none
1
2 3
```

That is, the escaped embedded double quotes (`\"`) should be honored, resulting in two outputs, `1`, and `'2 3'`.

This is indeed what happens with a regularly installed version.

# Actual behavior

```none
1
2
3
```

This output suggests that the embedded escaped double quotes (`\"`) were unexpectedly _eaten_.

# Environment data

```none
PowerShell Core 7.0 # as a global .NET tool, all platforms
```

**Comment by gerardog** [comment]
I think I have a clue about this one:

The Global Tool Shim is accepting the `args[]` as provided in the main function by .NET.
https://github.com/PowerShell/PowerShell/blob/42b599dc664a5f588e833f8591282fc4ed861943/src/Microsoft.PowerShell.GlobalTool.Shim/GlobalToolShim.cs#L33

However, to keep the quotes correctly it should be using either `Environment.CommandLine` 
or Win32Api:
        [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
        public static extern System.IntPtr GetCommandLine();

Hope it helps.-

**Comment by mklement0** [comment]
Nice sleuthing, @gerardog.

The simplest and robust solution is to copy the elements of `args` to a `ProcessStartInfo` instance's [`System.Diagnostics.ProcessStartInfo.ArgumentList`](https://docs.microsoft.com/en-US/dotnet/api/System.Diagnostics.ProcessStartInfo.ArgumentList) property (a new, collection-based alternative to the single-string `.Arguments` property), which on Windows performs proper re-quoting as necessary, and on Unix passes the already-parsed arguments through as an array:

```csharp

            // Use ProcessStartInfo.ArgumentList to robustly pass arguments through.
            var psi =  new ProcessStartInfo("dotnet");
            psi.ArgumentList.Add(pwshPath);
            foreach (var arg in args) { psi.ArgumentList.Add(arg); }

            if (File.Exists(pwshPath))
            {
                var process = System.Diagnostics.Process.Start(psi);
                process.WaitForExit();
                
                return process.ExitCode;
            }
```

**Comment by alfredmyers** [comment]
This issue probably can be closed now as argument parsing has been fixed in #10461 which according to [msftbot](https://github.com/apps/msftbot) was incorporated into [v6.2.4](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.4) and [v7.0.0-preview.4](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-preview.4)

I haven't tested v7.0.0-preview.4, but my tests show the issue has been solved in v6.2.4 and [v7.0.0](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0).

**Comment by gerardog** [comment]
> which on Windows performs proper re-quoting and escaping as necessary
Does it?

A few edge cases:
- Arguments without spaces wrapped single or double quotes, will be re-quoted?
- Arguments with spaces wrapped in single quotes, will be re-quoted in double quotes?

Thanks

**Comment by mklement0** [comment]
> Does it?

Yes, assuming the target application uses the command-line parsing rules of C/C++/.NET applications, as described [here](https://stackoverflow.com/a/48491292/45375).
That's the best that can be done - ultimately, any application is free to make up its own parsing rules.

As for the edge cases:

> Arguments without spaces wrapped in single or double quotes, will be re-quoted?

No - if an argument contains no spaces, it is passed _unquoted_, irrespective of whether it was quoted or not on the original command line.

> Arguments with spaces wrapped in single quotes, will be re-quoted in double quotes?

Yes.

**Comment by ForNeVeR** [comment]
Folks, this problem keeps reappearing from time to time in different random places (see the linked issues). Perhaps the bot was too eager to close it? I believe it should be addressed, for PowerShell to be a more robust / reliable tool for all the use cases.

Currently, the argument/quotes parsing changes depending on the way you install PowerShell in your system. This can't be good, can it?

**Comment by gerardog** [comment]
Thanks @ForNeVeR! After so much time... 

And yes, that bot is infuriating. I am very sorry to say this, but sometimes, negative feedback makes a difference, so here it goes: @StevenBucher98, when you activated the bot on Nov 16 2023 and gave just 6 days from warning to closure, you really messed up. This ticket is the proof of it. You should manually review all tickets closed on Nov 22, 2023 and evaluate if they need a second try.
