### ISSUE TITLE
No different color for syntax 

### ISSUE THREAD

**Issue by pmahend1** [PowerShell/PowerShell#11751]
# Steps to reproduce

1. Open PowerShell

```powershell
PowerShell 7.0.0-rc.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'
```
1. Type any PowerShell command

> Note  : I upgraded from Windows 10 Home to Windows 10 Education by the way.

![image](https://user-images.githubusercontent.com/21352870/73600886-34ca4880-4525-11ea-91c0-1111fec8d1c5.png)

# Expected behavior

For PowerShell commands the color should be yellow

# Actual behavior

- Commands Color is not Yellow

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by vexx32** [comment]
@pmahend1 coloring is provided by the PSReadLine module rather than PowerShell itself.

Can you verify that PSReadLine is imported with `Get-Module PSReadLine`?

**Comment by pmahend1** [comment]
By default it's not getting imported. Why?
I imported, it works as expected. I don't have any screen reader on, but still it says I have one.. Not even narrator.

**Comment by SeeminglyScience** [comment]
@pmahend1 Do you have one installed? Just having NVDA installed is enough to trigger it for me.  Might be worth opening an issue in PSReadLine, but I believe that's just how the win32 API they use works.

A workaround is to put `Import-Module PSReadLine` in your `$profile`.

**Comment by pmahend1** [comment]
@SeeminglyScience  I dont know which program is being considered as screenreader.
`Import-Module PSRreadLine` does work , and I `PSReadLine` is another github repository, but I see someone added code to check this and turn off PSReadLine in Powershell Core.

If that cant be reverted as a user how can turn this off , I dont prefer runnijng Import statement every time I open powershell core.

**Comment by neospect** [comment]
Just upgraded to PowerShell 7.0.0 final and I am getting that same unexpected behavior (no color highlighting for syntax) and warning by default. I have neither NVDA nor any other screen reader, that I know of.

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

**Comment by pmahend1** [comment]
@neospect Do this.
```shell
PS>$PROFILE
C:\Users\<BlahBlah>\Documents\Powershell-Core\PowerShell_profile.ps1
```

Open and add this line to 
```shell
Import-Module PSReadline
```

**Comment by galversonNU** [comment]
I have added "Import-Module PSReadLine" to the top of my $PROFILE. I now get colored syntax but I still get the warning every time I start a shell. It appears to come before $PROFILE gets executed. How to stop this junk! I don't even have NVDA.

**Comment by pmahend1** [comment]
@galversonNU same here. I was not able to identify which is that screen reader. Could be any application like Adobe, Firefox Chrome which have accessibility mode.
Wish there was some code to check it

**Comment by SeeminglyScience** [comment]
Here, run this:

```powershell
Add-Type -TypeDefinition '
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;

public static class ScreenReaderFixUtil
{
    public static bool IsScreenReaderActive()
    {
        var ptr = IntPtr.Zero;
        try
        {
            ptr = Marshal.AllocHGlobal(sizeof(int));
            int hr = Interop.SystemParametersInfo(
                Interop.SPI_GETSCREENREADER,
                sizeof(int),
                ptr,
                0);

            if (hr == 0)
            {
                throw new Win32Exception(Marshal.GetLastWin32Error());
            }

            return Marshal.ReadInt32(ptr) != 0;
        }
        finally
        {
            if (ptr != IntPtr.Zero)
            {
                Marshal.FreeHGlobal(ptr);
            }
        }
    }

    public static void SetScreenReaderActiveStatus(bool isActive)
    {
        int hr = Interop.SystemParametersInfo(
            Interop.SPI_SETSCREENREADER,
            isActive ? 1u : 0u,
            IntPtr.Zero,
            Interop.SPIF_SENDCHANGE);

        if (hr == 0)
        {
            throw new Win32Exception(Marshal.GetLastWin32Error());
        }
    }

    private static class Interop
    {
        public const int SPIF_SENDCHANGE = 0x0002;

        public const int SPI_GETSCREENREADER = 0x0046;

        public const int SPI_SETSCREENREADER = 0x0047;

        [DllImport("user32", SetLastError = true, CharSet = CharSet.Unicode)]
        public static extern int SystemParametersInfo(
            uint uiAction,
            uint uiParam,
            IntPtr pvParam,
            uint fWinIni);
    }
}'

if ([ScreenReaderFixUtil]::IsScreenReaderActive()) {
    [ScreenReaderFixUtil]::SetScreenReaderActiveStatus($false)
}
```

The flag for if a screen reader is active is persistent.  So if an application *at some point* set the flag and then crashed before disabling it (or was written poorly), that flag will stay.  This script will turn the flag off.  This won't help if you still have a program that is actively setting the flag, but will help in the scenario I described.

**Comment by galversonNU** [comment]
Dear Patrick,

That does indeed appear to fix the recurring warning.

Thanks very much!

Best regards,
George

**Comment by NotNotWrongUsually** [comment]
Worth mentioning, that for me the culprit was a key in Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access. I set "On" to 0 and the problem disappeared. I have no clue how it got enabled to begin with.

**Comment by alannt777** [comment]
> Here, run this:
> 
> ```powershell
> Add-Type -TypeDefinition '
> using System;
> using System.ComponentModel;
> using System.Runtime.InteropServices;
> 
> public static class ScreenReaderFixUtil
> {
>     public static bool IsScreenReaderActive()
>     {
>         var ptr = IntPtr.Zero;
>         try
>         {
>             ptr = Marshal.AllocHGlobal(sizeof(int));
>             int hr = Interop.SystemParametersInfo(
>                 Interop.SPI_GETSCREENREADER,
>                 sizeof(int),
>                 ptr,
>                 0);
> 
>             if (hr == 0)
>             {
>                 throw new Win32Exception(Marshal.GetLastWin32Error());
>             }
> 
>             return Marshal.ReadInt32(ptr) != 0;
>         }
>         finally
>         {
>             if (ptr != IntPtr.Zero)
>             {
>                 Marshal.FreeHGlobal(ptr);
>             }
>         }
>     }
> 
>     public static void SetScreenReaderActiveStatus(bool isActive)
>     {
>         int hr = Interop.SystemParametersInfo(
>             Interop.SPI_SETSCREENREADER,
>             isActive ? 1u : 0u,
>             IntPtr.Zero,
>             Interop.SPIF_SENDCHANGE);
> 
>         if (hr == 0)
>         {
>             throw new Win32Exception(Marshal.GetLastWin32Error());
>         }
>     }
> 
>     private static class Interop
>     {
>         public const int SPIF_SENDCHANGE = 0x0002;
> 
>         public const int SPI_GETSCREENREADER = 0x0046;
> 
>         public const int SPI_SETSCREENREADER = 0x0047;
> 
>         [DllImport("user32", SetLastError = true, CharSet = CharSet.Unicode)]
>         public static extern int SystemParametersInfo(
>             uint uiAction,
>             uint uiParam,
>             IntPtr pvParam,
>             uint fWinIni);
>     }
> }'
> 
> if ([ScreenReaderFixUtil]::IsScreenReaderActive()) {
>     [ScreenReaderFixUtil]::SetScreenReaderActiveStatus($false)
> }
> ```
> 
> The flag for if a screen reader is active is persistent. So if an application _at some point_ set the flag and then crashed before disabling it (or was written poorly), that flag will stay. This script will turn the flag off. This won't help if you still have a program that is actively setting the flag, but will help in the scenario I described.

I am getting this error:
```
Program.cs(1,1): error CS8652: The feature 'top-level statements' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(1,26): error CS1002: ; expected [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(1,26): error CS1010: Newline in constant [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(1,26): error CS1011: Empty character literal [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(1,27): error CS1002: ; expected [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(2,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(3,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(4,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(65,2): error CS8803: Top-level statements must precede namespace and type declarations. [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(65,2): error CS1010: Newline in constant [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(65,2): error CS1011: Empty character literal [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(65,3): error CS1002: ; expected [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(67,5): error CS1525: Invalid expression term '[' [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(67,26): error CS7000: Unexpected use of an aliased name [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(68,26): error CS1001: Identifier expected [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(68,56): error CS1056: Unexpected character '$' [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
Program.cs(68,63): error CS1002: ; expected [C:\Users\alan\Desktop\Fixer\Fixer.csproj]
```

**Comment by LinearDynamics** [comment]
This issue was affecting us with VSCode's terminal window.
Running @SeeminglyScience's script as a .ps1 file worked for me. 
But I'd like to know what a 'screen reader' is and what are the popular ones.

**Comment by alannt777** [comment]
> Worth mentioning, that for me the culprit was a key in Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access. I set "On" to 0 and the problem disappeared. I have no clue how it got enabled to begin with.

I checked this particular registry key and its value was 1. I changed it to 0 and now I don't have any issues

**Comment by alannt777** [comment]
> Here, run this:
> 
> ```powershell
> Add-Type -TypeDefinition '
> using System;
> using System.ComponentModel;
> using System.Runtime.InteropServices;
> 
> public static class ScreenReaderFixUtil
> {
>     public static bool IsScreenReaderActive()
>     {
>         var ptr = IntPtr.Zero;
>         try
>         {
>             ptr = Marshal.AllocHGlobal(sizeof(int));
>             int hr = Interop.SystemParametersInfo(
>                 Interop.SPI_GETSCREENREADER,
>                 sizeof(int),
>                 ptr,
>                 0);
> 
>             if (hr == 0)
>             {
>                 throw new Win32Exception(Marshal.GetLastWin32Error());
>             }
> 
>             return Marshal.ReadInt32(ptr) != 0;
>         }
>         finally
>         {
>             if (ptr != IntPtr.Zero)
>             {
>                 Marshal.FreeHGlobal(ptr);
>             }
>         }
>     }
> 
>     public static void SetScreenReaderActiveStatus(bool isActive)
>     {
>         int hr = Interop.SystemParametersInfo(
>             Interop.SPI_SETSCREENREADER,
>             isActive ? 1u : 0u,
>             IntPtr.Zero,
>             Interop.SPIF_SENDCHANGE);
> 
>         if (hr == 0)
>         {
>             throw new Win32Exception(Marshal.GetLastWin32Error());
>         }
>     }
> 
>     private static class Interop
>     {
>         public const int SPIF_SENDCHANGE = 0x0002;
> 
>         public const int SPI_GETSCREENREADER = 0x0046;
> 
>         public const int SPI_SETSCREENREADER = 0x0047;
> 
>         [DllImport("user32", SetLastError = true, CharSet = CharSet.Unicode)]
>         public static extern int SystemParametersInfo(
>             uint uiAction,
>             uint uiParam,
>             IntPtr pvParam,
>             uint fWinIni);
>     }
> }'
> 
> if ([ScreenReaderFixUtil]::IsScreenReaderActive()) {
>     [ScreenReaderFixUtil]::SetScreenReaderActiveStatus($false)
> }
> ```
> 
> The flag for if a screen reader is active is persistent. So if an application _at some point_ set the flag and then crashed before disabling it (or was written poorly), that flag will stay. This script will turn the flag off. This won't help if you still have a program that is actively setting the flag, but will help in the scenario I described.

Oh! I was supposed to run this as a PowerShell script.

**Comment by ValZapod** [comment]
Will just mention that this also disables Ctrl-R reverse search, very problematic (part of PSReadLine, I suppose). Computer\HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access helps indeed. But this is bad and happens when you update from 1909 to 2009 as I did.

**Comment by PritKalariya** [comment]
Running the program with .ps1 worked for me as well.
Thank you  @SeeminglyScience

**Comment by PritKalariya** [comment]
Every time I open my terminal it shows the same error that I'm using a screen recorder even though I'm not. 

![Screenshot 2020-12-23 152848](https://user-images.githubusercontent.com/71484962/102984454-9cb9c100-4533-11eb-832f-0274cc32bced.png)


I even changed the settings to "off" but no luck! It happens every time I open a new terminal.

![Screenshot 2020-12-23 150431](https://user-images.githubusercontent.com/71484962/102984124-18ffd480-4533-11eb-8646-ea20557cb439.png)

**Comment by skoobeeb** [comment]
In my case I suspect it was was caused by enabling Voice Dictation. The problem also persisted after editing of $profile - being fixed by the script of @ghost 19.09.2020

**Comment by rohit1205** [comment]
hello guys pls help me as i am stuck in vs code earlier there was only a warning that you might be using a screen reader that has disabled PSReadLine if you want to reenable it run ' Import-Module PSReadLine'. then i get to know the solution of this after runing the above given code in .ps1 file and then the warning was not coming but still vs code is not working like i am not able to get any output in terminal it is just showing that code is running when i reclick on it , it again shows code is already running but it is not asking me for input and not showing any output

**Comment by Himanshvarma** [comment]
we need to add this code in powershell. Good Luck !!!

**Comment by samhernandezc24** [comment]
Well, I modify the current Powershell Script to this, just a few changes:

```shell
Add-Type -TypeDefinition @"
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;

public static class ScreenReaderFixUntil
{
  public static bool IsScreenReaderActive()
  {
    IntPtr ptr = IntPtr.Zero;
    try
    {
      ptr = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(int)));
      int hr = Interop.SystemParametersInfo(
        Interop.SPI_GETSCREENREADER,
        sizeof(int),
        ptr,
        0);

      if (hr == 0)
      {
        throw new Win32Exception(Marshal.GetLastWin32Error());
      }

      return Marshal.ReadInt32(ptr) != 0;
    }
    finally
    {
      if (ptr != IntPtr.Zero)
      {
        Marshal.FreeHGlobal(ptr);
      }
    }
  }

  public static void SetScreenReaderActiveStatus(bool isActive)
  {
    int hr = Interop.SystemParametersInfo(
      Interop.SPI_SETSCREENREADER,
      (uint)(isActive ? 1 : 0),
      IntPtr.Zero,
      Interop.SPI_SENDCHANGE
    );

    if (hr == 0)
    {
      throw new Win32Exception(Marshal.GetLastWin32Error());
    }
  }

  private static class Interop
  {
    public const int SPI_SENDCHANGE       = 0x0002;
    public const int SPI_GETSCREENREADER  = 0x0046;
    public const int SPI_SETSCREENREADER  = 0x0047;

    [DllImport("user32", SetLastError = true, CharSet = CharSet.Unicode)]
    public static extern int SystemParametersInfo(
      uint uiAction,
      uint uiParam,
      IntPtr pvParam,
      uint fWinIni
    );
  }
}
"@
if ([ScreenReaderFixUntil]::IsScreenReaderActive()) {
   [ScreenReaderFixUntil]::SetScreenReaderActiveStatus($false);
}
```

**Comment by ByteJuggler** [comment]
This is so infuriating. I'm still seeing this today on Windows 11.  I do not have a screen reader.  Worse, I had this disabled for some period of time (via some registry hackery) and it automatically returned recently with one of the updates. So annoying.  I DO NOT WANT THIS WARNING EVERY TIME I OPEN A TERMINAL.  -- It's really way more complicated than it needs to be to turn this off and have it STAY OFF.
