### ISSUE TITLE
add Index and LastIndex property to $matches variable

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11755]
### steps to reproduce

```
PS C:\> 'hello' -match 'e'
True
PS C:\> $Matches | fl *

Name      : 0
Key       : 0
Value     : e
Index     : 1
LastIndex : 2
```

**Comment by vexx32** [comment]
I'm not really sure what you're asking here. What purpose would this serve? $matches is just a hashtable; all it really has is key and value for each item.

**Comment by iSazonov** [comment]
It is about first and last position of found substring in source line.

**Comment by vexx32** [comment]
@iSazonov thanks, that makes a bit more sense! It does raise the question of whether we want First/LastIndex of just the `0` entry, though, or whether we'd want to add it for each match group item as well?

**Comment by iSazonov** [comment]
I guess it is based on Regex and we can not add the indexes without performance degradation.

**Comment by mklement0** [comment]
Adding new entries to `$Matches` is also a potentially breaking change.

However, we discussed returning `[System.Text.RegularExpressions.Match]` instances in the context of a future `-allmatches` operator -  #7867 - which would at least enable you to do:

```
PS> ('hello' -allmatches 'e')[0]

Groups   : {0}
Success  : True
Name     : 0
Captures : {0}
Index    : 1
Length   : 1
Value    : e
```

**Comment by iSazonov** [comment]
@mklement0 Can you move this in #7867 explicitly?

**Comment by mklement0** [comment]
Assuming you meant my previous comment, @iSazonov: done.
