### ISSUE TITLE
Support accessing System.Memory

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#11768]
# Summary of the new feature/enhancement

Currently there isn't much you can do with `System.Memory<T>` other than create it, pass it to a method and allocate a new array from it.  Most of the functionality is actually attached to the property `Span` which PowerShell is unable to use.

While this type might not be incredibly applicable to PowerShell users today, it is going to be utilized more and more by the framework itself and third party libs as time goes on. Some basic support for at least enumerating and accessing by index would go a long way.

# Proposed technical implementation details (optional)

Special casing in the binder should be added to enable either direct indexing of `System.Memory` 

```powershell
$memory = [Memory[int]][int[]](0..10)

# Should return 0
$memory[0]

# Should set index 0 to 1
$memory[0] = 1

# Should enumerate
foreach ($i in $memory) {
}
```

<details>

<summary><sub>Alternate, more complicated proposal</sub></summary>

Or specifically for indexing, enable the usage of `System.Span` *when accessed directly from `Memory`*.  This might be the most idea route for understandably (since `Memory` doesn't have an indexer) but might also be impossible with how the binder is set up.

```powershell
$memory = [Memory[int]][int[]](0..10)

# Should return 0
$memory.Span[0]

# Should set index 0 to 1
$memory.Span[0] = 1

# This will still throw
foreach ($i in $memory.Span) {
}

# This will still throw
$i = $memory.Span
$i[0]
```

</details>

---

<details>
<summary>(Click to expand)

## Indexing example implementation
</summary>

Indexing is complicated slightly by the fact that `System.Linq.Expressions.Expression` does not seem to support `ref` returns at all, and `Span.Item` is a ref indexer.  One way to get around this would be a proxy method:

<sub>(Note: example not optimized)</sub>

```csharp
namespace System.Management.Automation
{
    internal static class CompilerOps
    {
        public static T GetSpanIndex<T>(Span<T> span, int index) => span[index];

        public static void SetSpanIndex<T>(Span<T> span, int index, T value)
            => span[index] = value;
    }

    internal partial class Compiler
    {
        private static Expression GetMemoryIndex(
            Expression expression,
            Expression target)
        {
            return Expression.Call(
                instance: null,
                typeof(CompilerOps).GetMethod(nameof(CompilerOps.GetSpanIndex)),
                Expression.Property(expression, nameof(Memory<int>.Span)),
                target);
        }

        private static Expression SetMemoryIndex(
            Expression expression,
            Expression target,
            Expression value)
        {
            return Expression.Call(
                instance: null,
                typeof(CompilerOps).GetMethod(nameof(CompilerOps.SetSpanIndex)),
                Expression.Property(expression, nameof(Memory<int>.Span)),
                target,
                value);
        }
    }
}
```

</details>

<details>
<summary>(Click to expand)

## Enumerable example implementation
</summary>

<sub>(Note: example not optimized)</sub>

```csharp
namespace System.Management.Automation
{
    internal class MemoryEnumerable<T> : IEnumerable<T>
    {
        private readonly ReadOnlyMemory<T> _memory;

        internal MemoryEnumerable(ReadOnlyMemory<T> memory) => _memory = memory;

        public IEnumerator<T> GetEnumerator() => new Enumerator(_memory);

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        private class Enumerator : IEnumerator<T>
        {
            private readonly ReadOnlyMemory<T> _memory;

            private readonly int _length;

            private int _index;

            public Enumerator(ReadOnlyMemory<T> memory)
            {
                _memory = memory;
                _index = -1;
                _length = memory.Length;
            }

            public T Current
            {
                get
                {
                    if (_index < 0) throw new InvalidOperationException("Enumeration has not started. Call MoveNext.");
                    if (_index >= _length) throw new InvalidOperationException("Enumeration already finished.");

                    return _memory.Span[_index];
                }
            }

            object IEnumerator.Current => Current;

            public bool MoveNext() => _index < _length && (++_index) < _length;

            public void Reset() => _index = -1;

            public void Dispose()
            {
            }
        }
    }

    internal partial class PSEnumerableBinder
    {
        public static DynamicMetaObject BindForMemory(DynamicMetaObject target, DynamicMetaObject[] args)
        {
            Type type = target.Value.GetType();
            if (!type.IsGenericTypeDefinition)
            {
                return null;
            }

            Type openGeneric = type.GetGenericTypeDefinition();
            if (!(openGeneric == typeof(ReadOnlyMemory<>) || openGeneric == typeof(Memory<>)))
            {
                return null;
            }

            Type memoryType = type.GetGenericArguments()[0];
            Type enumerableType = typeof(MemoryEnumerable<>).MakeGenericType(memoryType);
            return new DynamicMetaObject(
                Expression.New(
                    enumerableType.GetConstructor(
                        BindingFlags.Instance | BindingFlags.NonPublic,
                        binder: null,
                        new[] { type },
                        modifiers: null)),
                PSEnumerableBinder.GetRestrictions(target));
        }
    }
}
```
</details>

**Comment by mklement0** [comment]
+1; just to tie this to the larger suggestion to support generics (more) comprehensively: #5146

**Comment by SeeminglyScience** [comment]
@daxian-dbw @vexx32 Could the work group discuss this? Specifically whether a PR would be accepted to make the following syntax work:

```powershell
$memory = [Memory[int]][int[]](0..10)

# Should return 0
$memory[0]

# Should set index 0 to 1
$memory[0] = 1
```

Note that you can't do this in C# either, in C# you need to access `memory.Span[0]`. Trying to fit that into PowerShell's binder would be very challenging though.  If it is deemed acceptable to fake this indexer, I can provide a PR.

**Comment by rjmholt** [comment]
We discussed this in the Engine Working Group last week and had the following thoughts:

- The request here is for language-level special casing/support for a very specific type
- We don't really have any motivating scenarios described here and generally it's not clear how useful enhanced support of memory types would be for most PowerShell users, compared to just falling back to C#
- There's some concern about handling stack-based value types safely in a language as heap-oriented as PowerShell
- It would probably require significant effort to implement the proposed changes within PowerShell itself, so we'd want to be able to justify that with significant impact

With those thoughts in mind, we think handling of memory types is better done with a set of cmdlets in a standalone module than baked into PowerShell and that we should decline this PowerShell feature request.

**Comment by SeeminglyScience** [comment]
Fair enough.  One point of clarification:

> There's some concern about handling stack-based value types safely in a language as heap-oriented as PowerShell

`Memory<>` is the heap only version of `Span<>`.  The point of the proposed feature is because the intended way to use `Memory<>` is via the `Span` property which is not usable in PowerShell due to it's possibility of being stack based (when not returned from `Memory`).

---

If anyone else wants this feature they will need to champion it, I will be accepting the WG's decision.
