### ISSUE TITLE
$PROFILE is not updated to default location on Windows 

### ISSUE THREAD

**Issue by tedonmain** [PowerShell/PowerShell#11763]
# Steps to reproduce

Re: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6

Install PowerShell Core according to guidelines: **dotnet tool install --global PowerShell**

# Expected behavior

$PROFILE is updated to C:\Users\me\Documents\PowerShell\Profile.ps1

# Actual behavior

C:\Users\me\Documents\PowerShell\Microsoft.PowerShell_profile.ps1 (location and file does not exist and unable to edit $PROFILE)

# Environment data

PS ~ > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.19035
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS ~ >

**Comment by mklement0** [comment]
`C:\Users\me\Documents\PowerShell\Microsoft.PowerShell_profile.ps1` _is_ the correct path:

* The PowerShell-only name is in the _parent_ folder name (`PowerShell` vs. `WindowsPowerShell`).

* `Microsoft.PowerShell` still applies (note: _Microsoft_, not _Windows_) - it is based on the regular console host's `$ShellId` value, which hasn't changed.

**Comment by iSazonov** [comment]
You should manually create the path and file.
