### ISSUE TITLE
Can't set location to mounted disk image device path

### ISSUE THREAD

**Issue by cobalthex** [PowerShell/PowerShell#11764]
# Steps to reproduce

```powershell
$m = Mount-DiskImage -ImagePath (Resolve-Path '.\test.iso')
Set-Location -LiteralPath $m.DevicePath
```

# Expected behavior
cd into the device path folder

# Actual behavior
```
Set-Location : Cannot find path '\\.\CDROM0' because it does not exist.
````
# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lukeb1961** [comment]
wouldn't you just refer to the drive? It's a volume, not a device.
$drive = ($m | Get-Volume).DriveLetter + ':'
Set-Location $drive

**Comment by cobalthex** [comment]
Seems roundabout, and (in theory) not every mounted disk image has a volume letter

------ Original Message ------

**Comment by jhoneill** [comment]
> wouldn't you just refer to the drive? It's a volume, not a device.
> $drive = ($m | Get-Volume).DriveLetter + ':'
> Set-Location $drive

^^  this.
It's more obvious with a VHD file than an ISO for a CD/DVD, but the letter is associated with the filesystem not with the disk (which may have multiple filesystems or none)
It's the difference between `get-ciminstance win32_diskDrive` and `get-ciminstance win32_volume`

**Comment by cobalthex** [comment]
this will not work on linux

something also to note, the volume path (\\.\Volume{...}) also does not resolve

**Comment by jhoneill** [comment]
> this will not work on linux
> 
The mount-diskimage command is not available on linux - or at least not in 6.2 running on WSL which is what I have here. 
On linux, you mount whatever devices and or filesystems you need to with native commands, and CD into them using the path you'd use in any other shell. 

> something also to note, the volume path (\.\Volume{...}) also does not resolve
That's a windows device path not a filesystem path

**Comment by tommagumma** [comment]
> this will not work on linux

You would still need to supply `Set-Location` with the path the partition you are interested in (as @jhoneill pointed out, there could be multiple partitions on the disk) is mounted in as opposed to the path to the device itself.  It's the difference between `cd /dev/sdb` and `cd /mnt/mydisk`.

**Comment by cobalthex** [comment]
regardless, what works in windows powershell does not work on powershell core. 
remember volumes != partitions, and you can open a volume by its guid (not all volumes have mount points)

e..g `\\?\Volume{00000000-0000-0000-0000-000000000000` (try `Get-Volume | select Path` and open w/ the run dialog)
