### ISSUE TITLE
Powershell with Az CLI module on Linux Certificate issue

### ISSUE THREAD

**Issue by AndreiDita** [PowerShell/PowerShell#11769]
# Steps to reproduce

```
- Install PS on any supported Linux distribution
- Install the AzCli module in the PS on Linux
- Configure the Linux machine to connect through a proxy/firewall that does a SSL check, causing the certificate to be self-signed 
- run "az connect" command.

```

# Expected behavior

```- to allow you to "disable certificate check" or configure a local repository for the self signed certificate.

```

# Actual behavior

```- will refuse the certificate and deny the connection
   - will provide no mean to either disable certificate or use local repository

```

# Environment data

```Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
# Additional notes
- In Windows this works; you can basically disable the certificate check.
- In Linux, you can run separately the AzCli and have either the certificate check disabled or configure a local repo for the certificate.

However, none of the options above seem to be available when running PowerShell on Linux and AzCli module inside this PowerShell.

**Comment by iSazonov** [comment]
Please move the issue to https://github.com/Azure/azure-cli

**Comment by MaximoTrinidad** [comment]
Just an FYI

I tested Azure-CLI from Ubuntu 18.04 in PowerShell 7 RC2 and was able to login to Azure with no issues. Notice the use of "sudo" is not allowed.

```
pwsh-preview
az login  #->browser devicelogin.
## connected successfully inside powershell
az vm list 
```
![AzCli_Pwsh_01_2020-02-05_9-58-33](https://user-images.githubusercontent.com/19892435/73853064-3eda9880-47fe-11ea-83ae-7a6a7aec23a2.png)

![AzCli_Pwsh_02_2020-02-05_9-58-33](https://user-images.githubusercontent.com/19892435/73853191-777a7200-47fe-11ea-8eed-b9ae00f886bc.png)

**Comment by marinnedea** [comment]
@MaximoTrinidad - did you do that after "Configure the Linux machine to connect through a proxy/firewall that does a SSL check, causing the certificate to be self-signed" ?

**Comment by MaximoTrinidad** [comment]
@marinnedea 

Ubuntu 18.04 out-of-the-box! No manual configuration done.

I just follow the Microsoft Doc instructions on "Install Azure CLI with apt":
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

If it helps, this is a virtual machine on Hyper-V in Windows 10 RTM (10.0.18363). This system is not joined to any AD domain. 

:)

**Comment by marinnedea** [comment]
@MaximoTrinidad  

Maybe I wrote this wrong ... 
If you need to pass with your az cli through a proxy/firewall that does SSL inspect, your SSL fingerprint will change and the system will see it as "self signed" instead of CA verified. 

Now, in normal Az Cli , installed directly into Linux, you have the option to disable the SSL check.
Same goes when you install AzCli as a module inside PowerShell on Windows.

However, none of the existing methods work for **AzCli installed as a module inside PowerShell on Linux.**

Since the issue happens with the AzCli module for PowerShell, from my perspective this should be handled by PowerShell team. I'll open a bug report on AzCli page too, just in case.
