### ISSUE TITLE
How to receive email notification of non-AD joined DHCP leases?

### ISSUE THREAD

**Issue by Strakix** [PowerShell/PowerShell#11778]
Hi,
I am actually solving the situation of my DC server when some non-AD clients joins into my production LAN and receives IP address from DHCP server. I want to know about that situation. So I find out nice script on serverfault but it is not working properly for me. 

My plan is: 1. prepare script for comparing clients in DHCP versus clients in AD when someone receive new IP address
2. setup scheduled task if DHCP lease IP address
3. be notificated via email about this situation

Problem is that when DHCP lease the IP address I receive only empty email. Can anybody will help with it please? Thank you very much.
Here is the script.

 ` Get-DhcpServerv4Lease -allleases -ScopeId "192.168.140.0" | Select-Object @{expression= {$_.hostname}; label='name' } | export-CSV -notypeinformation C:\dhcp\LeaseLog.csv

import-module activedirectory

#get input CSV

$leaselogpath = "c:\DHCP\LeaseLog.csv"
Import-csv -path $leaselogpath | 
#query AD for computer name based on csv log
foreach-object `
{ 
   $ComputerName = $_.Name.Replace(".mydomain.cz",$null)
   $NameResult = Get-ADComputer $ComputerName
   $RogueSystem | Out-File C:\DHCP\RogueClients.txt -Append
   $RogueSystem = $null

}
Get-Content C:\DHCP\RogueClients.txt | Select-Object -Unique | Out-File C:\DHCP\RogueClientsFinal.txt
Remove-Item C:\DHCP\RogueClients.txt

#send email to sysadmin
$smtpserver = 192.168.140.40
$from="myemail@mydomain.cz"
$to="myemail@mydomain.cz"
$subject="Non-AD joined DHCP clients"
$body= (Get-Content C:\DHCP\RogueClientsFinal.txt) -join '<BR>&nbsp;<BR>'
$mailer = new-object Net.Mail.SMTPclient($smtpserver)
$msg = new-object Net.Mail.MailMessage($from,$to,$subject,$body)
$msg.IsBodyHTML = $true
$mailer.send($msg)`

**Comment by vexx32** [comment]
@Strakix this repo is mainly for the engine code itself. While you might find a few folx here that can help, you'll likely have a lot better luck asking around the community channels:

- [Slack](https://aka.ms/psslack)
- [Discord](https://aka.ms/psdiscord)
- [Reddit](https://reddit.com/r/PowerShell)
