### ISSUE TITLE
New Tab Feature Request

### ISSUE THREAD

**Issue by emretufekci** [PowerShell/PowerShell#11770]
PowerShell 6 has not multi tab feature like PowerShell ISE. Currently i'm working more than 10+ docker container on the powershell, while using powershell ise got some problem and also docker does not recommend PowerShell ISE, they're recommend PowerShell itself.

**Comment by mklement0** [comment]
Are you looking for a _terminal emulator_ (console) with tab support? 
Most of them in the Unix world do support that; on Windows, the upcoming [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab) will offer that (currently in preview, but usable), and there are also (stable) third-party alternatives, such as [ConEmu](https://conemu.github.io/).

**Comment by doctordns** [comment]
If not MS Terminal, why not VS Code?

**Comment by mklement0** [comment]
VS Code is great for _development_, but I think what @emretufekci  is after is the ability to run multiple _terminal sessions_ in a tabbed interface (which you could also do from the ISE).

**Comment by sburbano** [comment]
@emretufekci As @mklement0 mentioned, give a try to Windows Terminal. Officially is "preview" software, but I've been using it already for months without any issues. You can even setup different environments (PS5.1, PS6, different flavors of each one, ...) to suit your needs.

![image](https://user-images.githubusercontent.com/32914271/73831029-f1622980-4805-11ea-9eb7-ccf76ee3875f.png)

**Comment by emretufekci** [comment]
@mklement0  @sburbano Thank you so much, i've tried "Preview" feature it is exactly what i'm looking for. I am grateful for the help.
