### ISSUE TITLE
Select-Xml with file input unexpectedly treats whitespace as significant

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11771]
When you pass XML text via `-Content`, pretty-printing whitespace is _ignored_ in the resulting `XmlDocument` instance, which is consistent with .NET's default behavior (casting a string to `[xml]`, using [`System.Xml.XmlDocument.Load`](https://docs.microsoft.com/en-US/dotnet/api/System.Xml.XmlDocument.Load))

Unexpectedly, using `-Path` / `-LiteralPath` to load text from a file treats the whitespace as significant.

# Steps to reproduce

```powershell
# Create XML text with whitespace only between the element's
# opening and closing tag.
# Normally, this whitespace should be *ignored* on parsing.
$xmlText = @'
<elem>

</elem>
'@

# Save the text to a file.
$xmlFile =  "temp:/$PID.xml"
$xmlText > $xmlFile

# OK with -Content: whitespace is ignored.
(Select-Xml -Content $xmlText '/elem').Node.InnerText | Should -Be ''

# FAILS with -LiteralPath and -Path - whitespace is treated as significant.
(Select-Xml -LiteralPath $xmlFile '/elem').Node.InnerText | Should -Be ''
```

# Expected behavior

Both tests should pass.

# Actual behavior

The 2nd test fails, because the use of `-LiteralPath caused the text to be parsed with whitespace preserved.

```none
Expected strings to be the same, but they were different. 
Expected length: 0 Actual length:   2 Strings differ at index 0. 
Expected: '' But was:  '\n\n'
```

# Environment data

```none
PowerShell Core 7.0.0-rc.2
```

**Comment by p0W3RH311** [comment]
maybe add switch parameter **-compress** or **-compact** suppress all spaces between tags

**Comment by mklement0** [comment]
By far the most common use case is to _ignore_ whitespace in element content, which is why the [`PreserveWhitespace `](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument.preservewhitespace) property defaults to `$false`.

You sensibly get this default when you cast to `[xml]` and when you use `Select-Xml -Content` (as well as with `XmlDocument.Load()`), so there is no good reason to deviate from that default with `Select-Xml -LiteralPath /  -Path` (this deviation isn't documented either, so I assume it is accidental).

Therefore:

* I would consider making `Select-Xml -LiteralPath /  -Path` exhibit the default behavior too a _bug fix_.

* I don't think the whitespacing-_preserving_ behavior needs to be surfaced as a bona fide PowerShell feature; for this unusual need I think having to use the .NET methods directly is justified.
