### ISSUE TITLE
ListControl/WideControl OutOfBand constructor always set to false

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#11788]
`[ListControl]::Create($true).EndList()` should return `OutOfBand` property to true.

# Steps to reproduce

```powershell
It 'OutOfBand should be true' {
     [System.Management.Automation.ListControl]::Create($true).EndList().OutOfBand | Should -BeTrue
}
```

# Expected behavior

```none
Executing script C:\temp\test.ps1
  [+] OutOfBand should be true 8ms
Tests completed in 28ms
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

# Actual behavior

```none
[-] OutOfBand should be true 51ms
    Expected $true, but got $false.
    2:     [System.Management.Automation.ListControl]::Create($true).EndList().OutOfBand | Should -BeTrue
    at <ScriptBlock>, C:\temp\test.ps1: line 2
```

# Root cause

This is caused by the constructor hard coding the value to false instead of using the parameter.

https://github.com/PowerShell/PowerShell/blob/a5a97a593984a8f4ace4cbc19d11429170859503/src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs#L124-L128

https://github.com/PowerShell/PowerShell/blob/d80154430d600a52a1d1e3a9f3ecf032b36185d4/src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs#L77-L82

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> should return OutOfBand property to true

Could you please add more info why do the return should return true?

**Comment by ThomasNieto** [comment]
Because the constructor should do what it says it does.

**Comment by iSazonov** [comment]
@SteveL-MSFT @daxian-dbw Could you please make a conclusion about the issue?

**Comment by daxian-dbw** [comment]
The hard coded value might be intentional, but I'm not sure.
@JamesWTruher Could you please weigh in?

**Comment by ThomasNieto** [comment]
I don't see why it would be considering the other two Control classes work as expected. Plus the property can be modified after the object is created.

**Comment by iSazonov** [comment]
@ThomasNieto  The code is sensitive  and does not covered by test well. So we have to be careful.
