### ISSUE TITLE
PowerShell 7 Write-Host output hidden in Centos 7 screen session

### ISSUE THREAD

**Issue by HuAaron** [PowerShell/PowerShell#11780]
The powershell output encountered two issues on centos 7 when running in screen session:
Prerequest:
install screen and run powershell in screen session.

Version:
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Linux 4.19.48-001.ali4000.alios7.x86_64 #1 SMP Mon Sep 30 15:50:11 CST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

screen --version
Screen version 4.01.00devel (GNU) 2-May-06
uname -r
4.19.48.x86_64

Issues:
1. when open pwsh-preview and type command like "virsh list", the console just hangs.
2. when run pwsh-preview **.ps1 and some of the output was vanished( some of the output were displayed but some were not).

**Comment by iSazonov** [comment]
Please share PSTableVersion as issue template requests.
Can your repo with latest PowerShell 7.0 RC2 build? Without PSReadline?

**Comment by HuAaron** [comment]
> Please share PSTableVersion as issue template requests.
> Can your repo with latest PowerShell 7.0 RC2 build? Without PSReadline?

Yes. The psversion is rc2. What do you mean about "Without PSReadline”

**Comment by iSazonov** [comment]
@HuAaron unload PSReadline module
```powershell
 remove-module PSReadline
```

**Comment by HuAaron** [comment]
> @HuAaron unload PSReadline module
> 
> ```powershell
>  remove-module PSReadline
> ```

Still the same.

**Comment by iSazonov** [comment]
What is TERM is on your system?
See https://github.com/PowerShell/PowerShell/issues/2364

**Comment by HuAaron** [comment]
> What is TERM is on your system?
> See #2364

MobaXterm. This issue can also reproduce when using Windows Terminal Preview ssh remotely.

**Comment by iSazonov** [comment]
@HuAaron You could play with TERM. Also you could do `remove-module PSReadline` and share results.

**Comment by HuAaron** [comment]
> @HuAaron You could play with TERM. Also you could do `remove-module PSReadline` and share results.
remove-module PSReadline -- still the same.
I use tmux instead of screen and all issues are gone.

**Comment by iSazonov** [comment]
So the issue is related MobaXterm?

**Comment by HuAaron** [comment]
> So the issue is related MobaXterm?

No. It is related to screen. Works fine for tmux.
