### ISSUE TITLE
CLI tool not distributed with icons

### ISSUE THREAD

**Issue by aggieben** [PowerShell/PowerShell#11794]
# Summary of the new feature/enhancement

As a user, I'd like for the CLI tool distribution of powershell to include icons so that I can configure Windows Terminal to display the PowerShell Core icon in tabs.  This would also be applicable to other console tools, like Conemu.

It appears that the latest distributions of the powershell CLI tool do not include icons.

**Comment by DHowett-MSFT** [comment]
Terminal 0.9 is coming out pretty soon and ships with both a powershell icon you might be able to use and a detector that will search for different versions of powershell. Perhaps that’ll work better for you?

**Comment by aggieben** [comment]
@DHowett-MSFT yep, that suits me just fine.
