### ISSUE TITLE
Unable to Load IISAdministration module in Server 2019, pwsh7-rc2

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/PowerShell#11792]
I'm trying to load IISAdmininistration module on Server 2019 (core), but it's failing for me.

I do not understand why. I've tried loading the one installed on the system, I've also tried installing it from PSGallery and importing that one, with the same result.

# Steps to reproduce

```powershell
PS> Import-Module IISAdministration -SkipEditionCheck  -RequiredVersion 1.1.0.0
Import-Module: Could not load file or assembly 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

# Expected behavior

This is what happens in Powershell 5 on the same machine, basically I typed `exit` then `powershell`

```powershell
PS> Import-Module IISAdministration  -RequiredVersion 1.1.0.0
Get-Command -Module IISAdministration

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Clear-IISCentralCertProvider                       1.1.0.0    IISAdministration
Cmdlet          Clear-IISConfigCollection                          1.1.0.0    IISAdministration
Cmdlet          Disable-IISCentralCertProvider                     1.1.0.0    IISAdministration
...

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

It seems to work on my windows 10 machine. Are additional steps required, or is this a bug?

**Comment by doctordns** [comment]
Not that it helps, but this works OK here. Without the edition check.

```powershell
PS C:\Windows\System32> ipmo iisadministration
WARNING: Module iisadministration is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell Core please use 'Import-Module -SkipEditionCheck' syntax.
PS C:\Windows\System32> gmo

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.0                   iisadministration                   {Clear-IISCentralCertProvider, Clear-IISConfigCol…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     2.0.0      rc2        PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
Script     1.0                   ServerManager                       {Disable-ServerManagerStandardUserRemoting, Enabl…
```

The IIS Administration module does sort of load OK (Trying RC2 here). But the IIS: PSDrive is not imported.

**Comment by he852100** [comment]
Because `powershell core`(6,7) does not support `windows powershell`(5,4,3,2) module

**Comment by iSazonov** [comment]
The issue is reported in https://github.com/PowerShell/PowerShellModuleCoverage/issues/14

**Comment by MartinSGill** [comment]
@iSazonov Are you sure? I found that issue before I wrote this one, and the other one is about importing webadministration module. I'm trying to import IISAdministration, which 

> I believe we are favouring the IISAdministration module for porting. 
https://github.com/PowerShell/PowerShellModuleCoverage/issues/14#issuecomment-534405763

I'm also curious as to why it works on Windows 10 for me and appears to work for @doctordns . What's different?

**Comment by iSazonov** [comment]
IISAdministration module is not compatible with PowerShell Core and you can not directly load and use it in 7.0. As @doctordns mentioned you can use WinCompat feature and load the module without edition check.

**Comment by MartinSGill** [comment]
@iSazonov I get the same error when I load it without skipedition check.

````
PS> Import-Module -Name IISAdministration
Import-Module: Could not load file or assembly 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
````

**Comment by iSazonov** [comment]
Have you `Microsoft.Web.Administration` in GAC?

**Comment by MartinSGill** [comment]
Yes to the latter. I'm actually in the process of trying to figure out the minimum set of features/components I need my app.

**Comment by doctordns** [comment]
> IISAdministration module is not compatible with PowerShell Core and you can not directly load and use it in 7.0. As @doctordns mentioned you can use WinCompat feature and load the module without edition check.

I am not sure this is good advice (loading with -SkipEditionCheck).  Mainly because it does not work:

```powershell
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32> Import-Module -Name IISAdministration -SkipEditionCheck
Import-Module: Could not load file or assembly 'Microsoft.Web.Administration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
PS C:\Windows\System32>
```

So not only is the error message rather obtuse, but the module is not loadable within a PWSH 7 session in any event. Loading it in the compatibility session works and the IISAdministration module mainly functional. The OP needs to work out why it's not being loaded in the compat session - is the OP actually running the latest RC?

I think the compatibility solution is helpful but it leaves a lot of work undone. I do not feel this solution is really a) the best the team can do, and b) really ready for prime time. But to ship is to choose - and maybe the team is choosing to ship what arguably, is an incomplete solution with no formal mitigation plans yet advised.

**Comment by iSazonov** [comment]
> I am not sure this is good advice (loading with -SkipEditionCheck). 

:-) Sorry, I meant just "do not use -SkipEditionCheck"

**Comment by doctordns** [comment]
I agree - the advice in that error message is poor. Telling the user to use -SkipEditionCheck is not useful or helpful/ 

We have an issue with compatibility that will never be 100% resolved until product teams 'fix' their modules to accommodate .NET Core - like the AD module.  I know for some this will be hard (eg WSUS UpdateServices module). Having less than 100%, but still high, at RTM is, to me, is find given that so much works. @SteveL-MSFT said he wanted 90% and while I've not added it up, it's in that ballpark.  We want IT Pros to migrate to PowerShell 7 with a great compatibility story.

To me, our issue is two-fold: doing what can be done to move the meter (and being able to publicise the timetable to 100%) AND ensuring the user gets good actionable feedback when they enter into that 10% area.  I'd like to see, at PowerShell 7 release a confirmation as to when/how those incompatible modules are to be moved to .NET Core and PowerShell 7. Let's get a commitment to the roadmap to .NET core.

And when compatibility can be achieved, the user experience has to be good too. The OP;'s error message should not happen. When you try to load UpdateServices or BestPractices, you should get a good failure message (and maybe a URL reference for more info). The latest build nearly does this!   All other modules should load with the warning messages I see in RC2. It would be nice to have that message explicitly state that a provider is NOT being imported - but you can get to it via Invoke-Command.

And finally, when you try to load a compatible or semi-compatible module, like Server Manager and IIS, jit would be great to import the Display XML into the PowerShell 7 session to give the best possible user experience. 

I feel we are nearly there on a good compatibility story. We can/should do that little bit better.

**Comment by PeterHodges15** [comment]
Regarding managing IIS servers via PowerShell (IISAdministration),  MS does not install the required DLL for this to work.  They must be distracted with other priorities.
Does not even work on the latest preview.
