### ISSUE TITLE
MSI hangs trying to close pwsh process in VS Code

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#11796]
# Steps to reproduce

1. Install 7.0.0-rc.**1** and vscode
1. Set the following vscode setting: `"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",`
1. hit `ctrl`+\` (tilda) to open the terminal pane and verify via `$PSVersionTable` that PowerShell Preview is started (rc.1)
1. Run the MSI for 7.0.0-rc.2
1. when prompted, attempt to close the actively running pwsh processes

# Expected behavior

The pwsh process in VS Code closes and the MSI continues to install rc.2 and succeeds.

# Actual behavior

![image](https://user-images.githubusercontent.com/2644648/73989574-1a181b00-48fb-11ea-8f4c-0101f158109c.png)

# Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Also CC'ing @Tyriar in case he has any ideas..,

I want to be clear: *This has nothing to do with the PowerShell extension*. That said, it does affect the Install PowerShell feature in the VS Code which downloads the MSI and runs it. We clean up the PowerShell Integrated Console before executing the MSI but we don't clean up other pwsh processes on the machine and I think that the MSI should be the one to handle that.

**Comment by Tyriar** [comment]
The problem is the MSI can't close the the pwsh processes? By hang do you mean the MSI app crashes?

**Comment by TylerLeonhardt** [comment]
The behavior seems to be different in a couple places...

If I hit "OK" in the dialog above, it takes me to:

![image](https://user-images.githubusercontent.com/2644648/74179180-ca369e00-4bf1-11ea-813e-eee82e31b87f.png)

which I hit "OK" which takes me to the same screen shot above...

After I hit OK on that, the installation seems to give up on trying to close the pwsh process in VS Code and it just completes the installation as if I had selected "Do not close applications".

... I think another time I was doing this, it was taking too long so I hit "Cancel" in the main Installation window and that seemed to have caused the whole MSI app to hang.

**Comment by TylerLeonhardt** [comment]
I think the takeaway for you @Tyriar is that I don't know why the MSI can't close the pwsh inside of VS Code but it probably should be allowed to if possible.

**Comment by Tyriar** [comment]
@TylerLeonhardt that gist is about this right? Can you link it?

**Comment by TylerLeonhardt** [comment]
It's related for sure. Here's the gist: https://gist.github.com/TylerLeonhardt/7deb5f39877a48ebb41a2f9b208cce65
