### ISSUE TITLE
Bad IL Format for cmdlet created with PowerShellStandard.Library

### ISSUE THREAD

**Issue by Bluecakes** [PowerShell/PowerShell#11799]
I'm trying to create a portable library that i can use with PowerShell 5, 6 (Core) and Linux. I'm following the [Building a C# Cmdlet for PowerShell Standard 3.0 with Visual Studio](https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/visual-studio-simple-example.md) example but i'm only able to successfully import the module on PowerShell 5.

Steps to reproduce:
1. Create a new "Class Library (.NET Standard)" project in Visual Studio
2. Add the PowerShellStandard.Library Nuget package
3. Replace the class in Class1.cs with the following code
````
    using System.Management.Automation;

    [Cmdlet(VerbsCommunications.Write, "Greeting")]
    public class WriteGreeting : PSCmdlet
    {
        protected override void EndProcessing()
        {
            this.WriteObject("Greetings!");
        }
    }
````
4. Build the project

Expected Results
- Can import the module in PowerShell 5 and run the Write-Greeting cmdlet
- Can import the module in PowerShell 6 and run the Write-Greeting cmdlet

Outcome
- PowerShell 5 successfully imports the module and i can run the Write-Greeting cmdlet
- PowerShell 6 displays "Bad IL Format" when i import the module
![image](https://user-images.githubusercontent.com/12452056/74000232-0f20c180-49b3-11ea-865b-c55d602bf18f.png)

Visual Studio and .NET Framework Version
![image](https://user-images.githubusercontent.com/12452056/73999830-af75e680-49b1-11ea-9eb2-ef604607f46e.png)

PowerShell 6 and .NET Core Version
![image](https://user-images.githubusercontent.com/12452056/73999881-e21fdf00-49b1-11ea-9517-10c2b8b9e125.png)

PowerShell 5
![image](https://user-images.githubusercontent.com/12452056/73999675-34accb80-49b1-11ea-8b3b-cf4178d5feff.png)

**Comment by iSazonov** [comment]
For reference https://devblogs.microsoft.com/powershell/powershell-standard-library-build-single-module-that-works-across-windows-powershell-and-powershell-core/

**Comment by Bluecakes** [comment]
@iSazonov  I tried following that reference and encountered the same error. After creating a new module using the psmodule template and immediately building the project, i can't import the resulting library into PowerShell Core to run the "Test-SampleCmdlet" cmdlet.

![image](https://user-images.githubusercontent.com/12452056/74119163-0ece3380-4c0a-11ea-895d-056df2a0825b.png)

**Comment by iSazonov** [comment]
If it is native library loading related we have an update in last days and @Bluecakes can test with lates nightly build.

**Comment by iSazonov** [comment]
@Bluecakes Can you share Get-Error output?

**Comment by Bluecakes** [comment]
I downloaded the latest release, PowerShell 7, and tried importing the module created by the .NET Core CLI and got the same error, here is the Get-Error output:

![image](https://user-images.githubusercontent.com/12452056/74123087-2f51ba00-4c19-11ea-9d3e-68d9ee458de4.png)

**Comment by iSazonov** [comment]
I can not confirm the bug. I create, compile and import the module without any error, and run the cmdlet too in both PowerShell versions.

**Comment by Bluecakes** [comment]
I tried the exact same steps to create a brand new psmodule on a different machine and it worked perfectly. The version of Windows (10.0.17763) and Core (3.1.101) are exactly the same, the only difference is that the working machine only has 3.1.101 SDK installed, the machine that isn't working has multiple SDKs as listed in the first post.

**Comment by iSazonov** [comment]
You could use dotnet tracing if you want fix this.

**Comment by vexx32** [comment]
It doesn't seem right that PowerShell would break here just if a different SDK happens to be installed. The install should be standalone from whatever SDK versions are installed side by side :thinking:

**Comment by iSazonov** [comment]
There can be conflict with paths or packages in cache.

**Comment by Bluecakes** [comment]
So i opened up a new PowerShell window and got the ID with `$PID`, opened another window and got dotnet trace to collect data from that process id and...   it worked. Just to make sure i closed down all windows and opened up a new window, module still loaded. Opened up PowerShell 6 and tried it there too, still loaded.

I'm both happy and confused, i'm not sure what caused the problem or what fixed it but thank you for helping me with this issue.
