### ISSUE TITLE
Adding Version details to WinPS Compatibility Module Deny List

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#11805]
The WinPS Compat Deny list works nicely in the daily build. 

But what happens when one of the teams updates their module to at least be imported into a compat session?  Should the module list be versioned?  Should the Best Practices module be specially mentioned as 1.0 as being denied so if/when 1.1 or higher is released it will work as expected? 

And is the compat list only ever looked after the module is found to not loadable in the current session?

**Comment by anmenaga** [comment]
1) there are no guarantees that a higher version of a module will be WinCompat-compatible, in which case user experience will be bad again as before deny-list fix.
2) `is the compat list only ever looked after the module is found to not loadable in the current session?`
Yes, assuming `found to not loadable` means that the module is under System32 and {either has `CompatiblePSEditions` missing from `psd1` or `CompatiblePSEditions` does not contain `Core`}. Such modules used to be called `Core-incompatible` before WinCompat and were generating `PSEditionNotSupported / Module '{0}' does not support current PowerShell edition '{1}'. Its supported editions are '{2}'. Use 'Import-Module -SkipEditionCheck' to ignore the compatibility of this module.` error.
Also the compat list is checked when WinCompat is enforced with `-UseWindowsPowerShell` parameter.

**Comment by doctordns** [comment]
Thanks
