### ISSUE TITLE
add node and leafnode property to split-path

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11806]
### example

```
PS C:\> $a='x:\a\b\c\d\e'
PS C:\> $a | Split-Path
x:\a\b\c\d
PS C:\> $a | Split-Path -Leaf
e
PS C:\> $a | Split-Path -node 0
x:\
PS C:\> $a | Split-Path -node 1
x:\a
PS C:\> $a | Split-Path -node -1
x:\a\b\c\d
PS C:\> $a | Split-Path -node -2
x:\a\b\c
PS C:\> $a | Split-Path -leafnode -1
e
PS C:\> $a | Split-Path -leafnode -3
c
PS C:\> $a | Split-Path -leafnode 0
x:
PS C:\> $a | Split-Path -leafnode 1
a
PS C:\>
```

**Comment by jhoneill** [comment]
Is there a real world use case for 
"Give me the name of this file's grand parent directory".

**Comment by p0W3RH311** [comment]
> 
> 
> Is there a real world use case for
> "Give me the name of this file's grand parent directory".

same as split-path. split the path but give me the name or the path of my choose and not only the root or the last directory name 

for example:

give me the path path 

```
'c:\a\b\c\o','x:\f\g\h\o' | split-path -node -3
c:\a\b
x:\f\g
```
more flexility

**Comment by jhoneill** [comment]
That's what you said originally. 
But I've been working with hierarchical directories for 35 years and I can count on my thumbs the number of times I have wanted a bit of code to take a path which is certain to have a leaf, a parent, and a grand parent  and return the grand parent (or even the grand parent). 

I do wonder how much thought goes into suggestions like this before spamming the issues list with them  "X would offer the ability to do new things"... is true.   
But how many people are suffering under the burden of having to write `(Split-path (Split-path $Path $p) )`  or ` 'x:\f\g\h\o' -replace "^(.*)\\[^\\]*\\[^\\]*$",'$1'` 
Enabling things which no-one feels a need for isn't a good use of resources.
