### ISSUE TITLE
No Icons, can't save changes to properties.

### ISSUE THREAD

**Issue by shogerr** [PowerShell/PowerShell#11810]
PWSH RC2

**How**
1. Uninstall RC1
2. Install RC2

**What**
Application installs without icons.
Cannot save changes to properties:

```
Unable to modify the shortcut
C:\ProgramData\Microsoft\Windows\Start Menu\Powershell 7-preview (x64).lnk
Check to make sure it has not been deleted or renamed.
```

**Comment by mklement0** [comment]
Sounds like a duplicate of #11680

Workaround: https://github.com/PowerShell/PowerShell/issues/11680#issuecomment-578541388

**Comment by shogerr** [comment]
Alright, thanks, I'll take a look. Closing.
