### ISSUE TITLE
add new cmdlet set-module to modify code in module on the fly

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#11814]
### 
### steps to reproduce
```

import-module ./foobar.psm1

get-foobar
# hello

set-module -name foobar -RemoveFunction get-foobar,set-foobar -AddCode {
  $a='hello foobar'
  function show-foobar {
     $a
  }
}

get-foobar
# ERROR

show-foobar
#hello foobar
```

its possible to do this with

```
. $module {
 # code
}
```

but it more powershell way to create cmdlet

**Comment by vexx32** [comment]
I don't think we should encourage users to be modifying modules in-session.

It's useful for debugging on occasion, but I have't seen anywhere near enough compelling use cases to make it a standard cmdlet.

**Comment by iSazonov** [comment]
Updated module a developer can load with Force parameter. In general modules can have complex session state dependencies and changing module code/variables can destroy the session. If we think about binary modules it is absolutely impossible to change anything.
