### ISSUE TITLE
For ForEach-Object -Parallel, detect if the user is using an existing variable

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#11811]
# Summary of the new feature/enhancement

Seems that new users are likely to not understand that they need to use `$using:` to pass in variables to the scriptblock.  Seems like we should be able to detect these cases and create a suggestion to use `$using:`, something like:

```
Suggestion: Did you forget to use `$using:<variable>`
```

Where we can fill in `<variable>` with the actual variable name.

**Comment by doctordns** [comment]
Great idea

And when documenting this feature, ensure that there are examples that show this.

**Comment by vexx32** [comment]
See also: #10876 and #10499

`$using` is always going to be confusing, there are restrictions on its use as well which should also be well-documented.

**Comment by PrzemyslawKlys** [comment]
While you're at improving detection please address this:

Doesn't work

```powershell
$OhMy = 'Test'
(1..100) | ForEach-Object -Parallel {
    $Test = $Using:OhMy
    (1..50) | ForEach-Object -Parallel {
        $Test5 = $Using:Test
    }
}
```

![image](https://user-images.githubusercontent.com/15063294/74090909-8d638d80-4ab1-11ea-8f60-f55be0ae2792.png)


Works:
```powershell
$OhMy = 'Test'
$Test = $null
(1..100) | ForEach-Object -Parallel {
    $Test = $Using:OhMy
    (1..50) | ForEach-Object -Parallel {
        $Test5 = $Using:Test
    }
}
```

**Comment by iSazonov** [comment]
@PrzemyslawKlys Please open new issue for your report.
