### ISSUE TITLE
Invoke-WebRequest test failure: "Denial of service.Image Parsing"

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#11821]
Invoke-WebRequest test "Denial of service.Image Parsing" is failing intermittently:

* `PowerShell-CI-linux` failed in [build 45608](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=45608&view=ms.vss-test-web.build-test-results-tab&runId=1313682&resultId=103071&paneView=debug)
 * `PowerShell-CI-linux` failed in [build 44792](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=44792&view=ms.vss-test-web.build-test-results-tab&runId=1306436&resultId=103064)

Error message: `Expected the actual value to be greater than 5, but got 0.368549962301977.`

Stack trace:
```
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1: line 1932
1932:             $pathologicalRatio | Should -BeGreaterThan 5
```

**Comment by xtqqczze** [comment]
Test has not failed in last 30 days, closing.

**Comment by PaulHigin** [comment]
This seems like it may be a fragile test, as it is randomly failing again on release builds.
