### ISSUE TITLE
Installer does not create directories for $Env:PSModulePath

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#11824]
$Env:PSModulePath

Contains the following paths:

C:\Users\<userName>\Documents\PowerShell\Modules;
C:\Program Files\PowerShell\Modules;
c:\program files\powershell\7-preview\Modules;
C:\Program Files\WindowsPowerShell\Modules;
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

But when the installer in v7 creates:

C:\Users\<userName>\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules

It does not create the Modules directory.

The question is should it? If they are valid paths then perhaps the directory should exist so that a test to see if a requested module resides in that path does not fail because the directory is missing.

All the expected directories in PSV5 are present the user does not have to create them.

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
> All the expected directories in PSV5 are present the user does not have to create them.

Windows PowerShell is _Windows component_ but PowerShell Core is not. And it is by-design that PowerShell Core installer doesn't create these module folders. It makes no sense to create these folders until PowerShell will dominate on Windows systems.

**Comment by RG255** [comment]
> It makes no sense to create these folders until PowerShell will dominate on Windows systems.

I have to ask then, if the directories do not and will not exist why the path statement is incorrect - pointing at places that are invalid?

**Comment by iSazonov** [comment]
The intention is that the user himself will create these folders if necessary. They can also already be created at the time of PowerShell Core installation.

**Comment by RG255** [comment]
I have just uninstalled and re-installed the V7RC2 and I see no option to create the directories. However it seems this is not seen as an issue so closing the bug report.
