### ISSUE TITLE
pwsh 7-rc2 Function with runspaces slow to process, uses large amounts of memory

### ISSUE THREAD

**Issue by zzragnar0kzz** [PowerShell/PowerShell#11826]
I have a function which scans IPv4 addresses for hosts that are listening on a specific port.

[Code](https://github.com/PowerShell/PowerShell/files/4189649/Show-OnlineHosts.txt)

In PowerShell 5.1, running this function against 500+ IP addresses routinely takes less than 10 seconds for the scan to complete, as indicated by the internal stopwatch. However, in PowerShell Core 7.0.0-rc.2, scanning the same 500+ addresses routinely takes nearly 50 seconds to complete. The process's memory usage is also several times higher in the preview version (600+ MB vs ~ 200 MB, as reported by Task Manager). Neither of these seem like desirable behavior.

# Steps to reproduce
1. Save the function above in a script or module file.
2. Open a classic PowerShell window.
3. Import the saved script or module file.
4. Run the function with the -Verbose and -Force flags and note the elapsed time reported.
5. Open a PowerShell Core window.
6. Import the saved script or module file.
7. Run the function with the -Verbose and -Force flags and note the elapsed time reported.
8. Compare the times reported in Steps 4 and 7 above.

# Expected behavior

Memory usage and execution time comparable to PowerShell 5.1:

`
PS 5.1> soh -Verbose -Force
`
```
VERBOSE: Initializing function . . .
VERBOSE: Total networks detected         : 2
VERBOSE: Addresses to scan per network   : 256
VERBOSE: Total addresses to scan         : 512
VERBOSE: Initialization complete. Continuing . . .
VERBOSE: Proceeding with network scanning.
VERBOSE: Scanning network . . .
VERBOSE: Network scanning complete. Scanned 512 address(es) in 5.6210833 seconds.
```

# Actual behavior

Largely inflated memory usage and execution time compared to PowerShell 5.1:

`
PS 7-preview> soh -Verbose -Force
`
```
VERBOSE: Initializing function . . .
VERBOSE: Total networks detected         : 2
VERBOSE: Addresses to scan per network   : 256
VERBOSE: Total addresses to scan         : 512
VERBOSE: Initialization complete. Continuing . . .
VERBOSE: Proceeding with network scanning.
VERBOSE: Scanning network . . .
VERBOSE: Network scanning complete. Scanned 512 address(es) in 49.7831588 seconds.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@zzragnar0kzz Could you please split the script on parts and measure every part to find where performance degradation occurs?

**Comment by zzragnar0kzz** [comment]
@iSazonov I've added code to measure the time elapsed during each of the following tasks:
1. Script startup to user prompt
2. Network scanning
  a. Runspace generation
  b. Runspace execution
3. Cleanup to script exit

Debug messages have also been added at each of these points; these messages display the total elapsed runtime and the current process's PagedMemorySize and PeakPagedMemorySize at each point.

[Modified code](https://github.com/PowerShell/PowerShell/files/4189412/Show-OnlineHosts.txt)

Sample output:

`
PS 7-preview> soh -Force -Verbose -Debug
`
```
VERBOSE: Initializing function . . .
VERBOSE: Total networks detected         : 2
VERBOSE: Addresses to scan per network   : 256
VERBOSE: Total addresses to scan         : 512
VERBOSE: Initialization completed in 0.0280024 seconds.
DEBUG: Total runtime : 0.0299236 seconds.
DEBUG: Memory usage : Current 58.1484375 MB / Peak 58.1484375 MB
VERBOSE: Continuing . . .
VERBOSE: Generating runspaces . . .
VERBOSE: Runspace generation complete : 512 runspace(s) in 4.4426279 seconds.
DEBUG: Total runtime : 4.4815925 seconds.
DEBUG: Memory usage : Current 673.9296875 MB / Peak 676.23046875 MB
VERBOSE: Scanning network . . .
VERBOSE: Network scanning complete : 512 address(es) in 43.7567895 seconds.
VERBOSE: Total detected host servers : 1
DEBUG: Total runtime : 48.246157 seconds.
DEBUG: Memory usage : Current 695.94140625 MB / Peak 696.41796875 MB
VERBOSE: Performing runspace pool cleanup . . .
VERBOSE: Runspace pool cleanup completed in 0.0490162 seconds.
DEBUG: Total runtime : 48.2999362 seconds.
DEBUG: Memory usage : Current 647.59375 MB / Peak 696.41796875 MB
VERBOSE: Exiting gracefully. Total runtime : 48.3038236 seconds.
```
I don't know if this is relevant, but as it currently is, running the function with -Debug in 5.1 causes a Confirm prompt to appear after each call to Write-Debug. These prompts must be responded to individually - Yes to All does not answer Yes to All. It also returns some wildly inconsistent memory values. It otherwise appears to function as expected.

Sample output from 5.1 for comparison:

`
PS 5.1> soh -Force -Verbose -Debug
`
```
VERBOSE: Initializing function . . .
VERBOSE: Total networks detected         : 2
VERBOSE: Addresses to scan per network   : 256
VERBOSE: Total addresses to scan         : 512
VERBOSE: Initialization completed in 0.028382 seconds.
DEBUG: Total runtime : 0.0313089 seconds.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: Memory usage : Current 114.59375 MB / Peak 115.234375 MB

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
VERBOSE: Continuing . . .
VERBOSE: Generating runspaces . . .
VERBOSE: Runspace generation complete : 512 runspace(s) in 1.5926215 seconds.
DEBUG: Total runtime : 3.2710461 seconds.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: Memory usage : Current 439.3203125 MB / Peak 439.3203125 MB

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
VERBOSE: Scanning network . . .
VERBOSE: Network scanning complete : 512 address(es) in 2.3413952 seconds.
VERBOSE: Total detected host servers : 1
DEBUG: Total runtime : 7.2270809 seconds.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: Memory usage : Current 444.3828125 MB / Peak 456.91015625 MB

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
VERBOSE: Performing runspace pool cleanup . . .
VERBOSE: Runspace pool cleanup completed in 0.159363 seconds.
DEBUG: Total runtime : 8.8202681 seconds.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: Memory usage : Current 234.125 MB / Peak 456.91015625 MB

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
VERBOSE: Exiting gracefully. Total runtime : 10.2109238 seconds.
```
Is something like this what you were looking for? Please advise.

Thank you!

**Comment by iSazonov** [comment]
You can replace Write-Debug with Write-Verbose.
Also `$socket = New-Object Net.Sockets.TcpClient($ip,$Port)` does connection and you shouldn't do            `$socket.Connect()` - it is bug in the script.
You could put results in one table to easily review.

**Comment by mikeTWC1984** [comment]
@zzragnar0kzz the pool size of 500 is definitely  overkill and probably causing this issue. Reduce it to the number of cpu threads of your machine. In your case I wouldn't use runspaces at all though. You can just use connectasync, then just check if task has status RanToCompletion
```powershell
$socket = [Net.Sockets.TcpClient]::new()
$task = $socket.ConnectAsync($ip, $port)
```

**Comment by zzragnar0kzz** [comment]
@iSazonov @mikeTWC1984 Code has been modified per your suggestions:

[Modified code](https://github.com/PowerShell/PowerShell/files/4203700/Sample_Show-OnlineHosts.txt)

Observations:
  1. Removing calls to `Write-Debug` has made troubleshooting this issue easier, but does not explain the discrepancy in behavior between versions. Does this discrepancy warrant further investigation?
  2. `$socket.Connect()` was indeed unnecessary, but removing it had no appreciable impact on runtime or monitored resource usage.
  3. The pool size was set to such an admittedly insane number to facilitate speed with the original code. Reducing this value would lower memory usage, but would greatly increase runtime.
  4. Using `$socket = [Net.Sockets.TcpClient]::new()` and `$task = $socket.ConnectAsync($ip, $port)` reduces runtime and virtually eliminates the difference in runtime between versions, in all stages.
  5. In conjunction with (4) above, reducing the pool size to (threads)x1.25 also greatly reduces memory usage, while maintaining an acceptable level of speed.
  6. Eliminating runspaces reduces memory usage even further, but a brief timeout is required between connection attempts before success can be verified, and even a small timeout (0.1s) severely slows down processing when hundreds of addresses are scanned sequentially. Thus, runspaces have been preserved.
  7. Data points have been stored in `$results` for easier retrieval.

Sample output:
`PS 7-preview> soh -Force -Verbose`
```
VERBOSE: Starting function . . .
VERBOSE: [Startup] : Begin
VERBOSE: Initializing . . .                                                                                             VERBOSE: Total network(s) detected       : 2                                                                            VERBOSE: Address(es) to scan per network : 256                                                                          VERBOSE: Generating list of IP address(es) to scan . . .                                                                VERBOSE: List of IP address(es) to scan successfully generated.                                                         VERBOSE: Total address(es) to scan       : 512                                                                          VERBOSE: Creating and opening runspace pool with 20 thread(s) . . .                                                     VERBOSE: Runspace pool successfully created and opened.                                                                 VERBOSE: [Startup] completed in 0.031 seconds.
VERBOSE: Memory usage : Current 52.281 MB / Peak 52.281 MB
VERBOSE: Total runtime : 0.046 seconds.
VERBOSE: Continuing . . .
VERBOSE: [RunspaceSetup] : Begin
VERBOSE: Generating runspace(s) . . .
VERBOSE: [RunspaceSetup] completed : 512 runspace(s) in 0.174 seconds.
VERBOSE: Memory usage : Current 88.734 MB / Peak 88.734 MB
VERBOSE: Total runtime : 0.233 seconds.
VERBOSE: [Scan] : Begin
VERBOSE: Scanning network(s) . . .
VERBOSE: Total detected host(s) : 1
VERBOSE: [Scan] completed : 512 address(es) in 2.525 seconds.
VERBOSE: Memory usage : Current 101.719 MB / Peak 101.719 MB
VERBOSE: Total runtime : 2.767 seconds.
VERBOSE: [Cleanup] : Begin
VERBOSE: Performing post-processing and cleanup . . .
VERBOSE: [Cleanup] completed in 0.005 seconds.
VERBOSE: Memory usage : Current 100.988 MB / Peak 101.832 MB
VERBOSE: Total runtime : 2.779 seconds.
VERBOSE: Exiting gracefully. Total time to execute : 2.783 seconds.
```

Unless I'm missing something, it appears that the original's time and memory discrepancies between versions can be explained by some garbage code on my part. Thank you for the advice! Please let me know if I may be of further assistance.

**Comment by iSazonov** [comment]
If I understand right now your code works well on both versions, yes?

**Comment by mikeTWC1984** [comment]
@zzragnar0kzz  I think powershell core just spins up runspaces faster. Each of them  eats about 1-2MB of memory, so  I guess memory usage increase would be be somewhat proportional to the runspaces handled. Running too many threads probably just bloated your cpu.

**Comment by zzragnar0kzz** [comment]
@iSazonov That is correct. Runtime is now pretty consistent for me across versions, and is faster than ever. Memory usage, both peak and current measured after cleanup, has also been reduced across versions. In fact, peak memory usage in core is now consistently around 1/3 that of v5.1, and core is now using less memory at completion than v5.1. Combined with the reduced runtime, this is a complete reversal of the situation that originally prompted me to submit this issue.

@mikeTWC1984 On my end at least, generating runspaces is still slightly faster in v5.1 than it is in core. However, with the dramatic reduction in threads, the difference is now only fractions of a second, as opposed to the 2-3x longer it initially was. Agreed on memory usage per thread. What I still don't really understand is why executing the runspaces initially took ~ 20x longer in core, or why it was initially using much more memory in core.

**Comment by iSazonov** [comment]
We have some issues for runspaces. Use Area-Performance label filter to discover them.
