### ISSUE TITLE
Get-Content -ReadCount 0  combined with -Last / -Tail seems to read ALL lines internally

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11830]
`Get-Content -ReadCount 0` is a convenient way to request that all lines be read _at once, into an array_ and to have that array be output _as a single_ object to the success stream.

When combined with `-First` aka `-TotalCount` aka `-Head`, this sensibly allocates an array for and outputs _only the requested number of lines_ from the beginning, not for _all_ lines.
Note: Meaningfully combining `-First` with `-ReadCount 0` was only recently implemented, in #10749.

While combining `-Last` aka `-Tail` with `-ReadCount 0` is _functional_,  performance timings suggest that _all_ lines are needlessly being read into an array behind the scenes, before only the sub-array of interest is output.

In other words: while `-Tail <n> -ReadCount 0` _should_ be the same as `-Tail <n> -ReadCount <n>` (explicitly setting the the read count to the same number as the number of trailing lines requested), it currently isn't in terms of _performance and memory use_.

# Steps to reproduce

```powershell
# Create a temporary file with 1 million lines
$f = [IO.Path]::GetTempFileName(); (, 'foo') * 1e6 > $f
# Warm up the cache.
$tmp = gc $f -ReadCount 0

# Read 1000 lines from the end, as a single array
$n = 1000
{ $v = gc $f -Tail $n -ReadCount $n },
{ $v = gc $f -Tail $n -ReadCount 0  }, 
{ $v = gc $f          -ReadCount 0  } <# control: read all lines #> |  % {
  "$_`: " + (Measure-Command $_).TotalSeconds 
}

Remove-Item $f
```

# Expected behavior

`-Tail $n -ReadCount $n` and `-Tail $n -ReadCount 0` should perform virtually the same and should be faster than `-ReadCount 0` by itself.

# Actual behavior

`-Tail $n -ReadCount 0` is not only slower than `-Tail $n -ReadCount $n` , but also slower than `-ReadCount 0`  by itself, suggesting that _all_ lines were read behind the scenes.

```none
 $v = gc $f -Tail $n -ReadCount $n : 0.1515997
 $v = gc $f -Tail $n -ReadCount 0  : 0.2118531
 $v = gc $f          -ReadCount 0  : 0.209674
```

# Environment data

```none
PowerShell Core 7.0.0-rc.2
```

**Comment by NoMoreFood** [comment]
Looked into this a bit.  I think you discovered an interesting issue / circumstance.  In PowerShell Core, the `[IO.Path]::GetTempFileName(); (, 'foo') * 1e6 > $f` command produces a UTF-8 file without a byte-order-marker (BOM).  Side note: This differs from Windows PowerShell which produces a UTF-16 with a BOM.  When processing UTF-8 data with no BOM, the Get-Content cannot detect the file encoding when the file is read in reverse.  As a result, it does a forward search which enumerates the whole file (albeit in different chunk sizes depending on ReadCount -- which might explain your performance differences).  Can you confirm that doing the following changes the behavior for you?

```
$f = [IO.Path]::GetTempFileName()
(, 'foo') * 1e6 | Set-Content -Encoding utf8BOM -LiteralPath $f
```

**Comment by mklement0** [comment]
Intriguing, @NoMoreFood, thanks for the sleuthing - using a file _with a BOM_ indeed makes a big difference in the resulting performance (and even seems to make `-ReadCount 0` marginally faster than `-ReadCount $n`)

I would never expect `Get-Content` to _detect_ encodings, however: if a BOM is present, the encoding is unambiguously specified; in the absence of a BOM, the _default_ encoding should be _assumed_ (UTF-8 in PS Core), so there is no good reason for this variation in behavior.

**Comment by NoMoreFood** [comment]
Yeah, I think you're right and I believe I see the detection bug in the code.  More to come....

**Comment by NoMoreFood** [comment]
@iSazonov It appears Get-Content -Tail already has a decent set of tests to validate the encodings.  The tests of interest passed before and they continue to pass after the change.  However, I saw some new explicit encodings were not in the list to I added them to this pull.

However, this pull addresses a performance bug which obviously can run differently on every system and every execution so it would be nearly impossible to include a reliable pass/fail test for something like this without adding specific debug tracing to the code in order to validate the code path of interest is hit or not hit; I do not see any precedent for that in other tests.  In absence of that, I am providing a code snippet to verify obviously demonstrate the performance before and after the change:

Test Code:
```
$Encodings = @('String','OEM','Unicode','BigEndianUnicode',
    'UTF8','UTF8BOM','UTF8NoBOM','UTF7','UTF32','Ascii')
$TempFile = (New-TemporaryFile).FullName
$Results = @()
ForEach ($Encoding in $Encodings)
{
    (1..2e6) | Set-Content -Encoding $Encoding -LiteralPath $TempFile -Force
    $Time = Measure-Command { $Capture = Get-Content -Tail 1 -LiteralPath $TempFile }
    $Results += New-Object PSObject -Property @{'Encoding'=$Encoding;'Time'=$Time.TotalMilliSeconds}
    Remove-Item -LiteralPath $TempFile -Force
}
$Results | Format-Table -AutoSize 
```

Before Change:
```
Encoding             Time
--------             ----
String            12.3904
OEM              585.5496
Unicode            1.2809
BigEndianUnicode   1.1258
UTF8             555.5736
UTF8BOM            0.9639
UTF8NoBOM        647.7248
UTF7             560.4215
UTF32              1.1847
Ascii            562.1341
```

After Change:
```
Encoding           Time
--------           ----
String           2.8139
OEM              0.8078
Unicode          0.8523
BigEndianUnicode 0.9938
UTF8             0.7483
UTF8BOM          0.7559
UTF8NoBOM        0.7721
UTF7             0.8044
UTF32            1.1415
Ascii            0.9463
```

Notice the performance improvements for UTF-8 / UTF-8 NoBOM / UTF-7 / Ascii / OEM (which are all interpreted as UTF-8 by Get-Content given they are all indistinguishable with the provided test character set) .  This latter performance is consistent to what you'd see from Windows PowerShell.
