### ISSUE TITLE
yum install packages-microsoft-com-prod - out of memory error

### ISSUE THREAD

**Issue by bluebrown** [PowerShell/PowerShell#11849]
I am trying to install powershell on CentoOS 8. I follow the [official Microsoft instructions][1]. 
I had some [previous issue][2]. 

---

I rented a nanode from Linode which is the smallest model. I get memory error:

```shell
[codingsafari@centosbox ~]$ sudo yum update
CentOS-8 - AppStream                                                                140 kB/s | 4.3 kB     00:00
CentOS-8 - Base                                                                     155 kB/s | 3.8 kB     00:00
CentOS-8 - Extras                                                                    43 kB/s | 1.5 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                       33 kB/s |  14 kB     00:00
packages-microsoft-com-prod                                                          28 kB/s | 2.9 kB     00:00
Out of memory allocating 771751936 bytes!
Killed

[codingsafari@centosbox ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:            821          77         648           1          95         633
Swap:           511          75         436
```

---

It is a fairly small node so I resized the node to the next bigger tier and the same error happens

```shell
[codingsafari@centosbox nginx]$ sudo yum install -y powershell
packages-microsoft-com-prod                                                                               25 kB/s | 2.9 kB     00:00
Out of memory allocating 419430400 bytes!

[codingsafari@centosbox nginx]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1829          83        1663           1          82        1631
Swap:           511          85         426

```

At this point, I highly doubt it has something to do with the size of the node. Does anyone know why this could happen?

  [1]: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7
  [2]: https://serverfault.com/questions/1002952/unable-to-run-dnf-update-after-adding-packages-microsoft-com-prod?noredirect=1#comment1303778_1002952

**Comment by mikeTWC1984** [comment]
Well, on your first snapshot you are getting this error during yum update, so I don't see any link to powershell here. Try  install something else, like java, to see if you getting this error. Also, try to reproduce it  installing centos container or VM on your local machine. Probably centos8 is just too heavy for 1GB machine. Keep increasing memory.
