### ISSUE TITLE
Compare-Object: -ExcludeDifferent should imply -IncludeEqual

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#11847]
`Compare-Object` only reports _differences_ by default, requiring explicit opt-in for inclusion of _equal_ objects via `-IncludeEqual`.

Therefore, the only meaningful behavior when you use `-ExcludeDifferent` is to _default_ to `-IncludeEqual`.

Without that, as is currently the case, _nothing_ is ever output, so it is currently effectively pointless to pass `-ExcludeDifferent` _without also passing `-IncludeEqual`_.

# Steps to reproduce

```powershell
Compare-Object 1,2 3, 1 -ExcludeDifferent -PassThru -IncludeEqual  | Should -Be 1
# Currently produces NO output, because -IncludeEqual isn't implied.
Compare-Object 1,2 3, 1 -ExcludeDifferent -PassThru | Should -Be 1
```

# Expected behavior

Both tests should pass.

# Actual behavior

The 2nd test fails, because `-IncludeEqual` is not implied.

# Environment data

```none
PowerShell Core 7.0.0-rc.2
```

**Comment by Jawz84** [comment]
It appears that it is already _supposed_ to do that, but clearly isn't. See [Compare-Object.cs](https://github.com/PowerShell/PowerShell/blob/3ab605aeec1dbd5a9e975f15628b0648b6ee0464/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs#L374)

```csharp
/// <summary>
/// If the parameter 'ExcludeDifferent' is present, then we need to turn on the
/// 'IncludeEqual' switch unless it's turned off by the user specifically.
/// </summary>
protected override void BeginProcessing()
{
    if (ExcludeDifferent)
    {
        if (_isIncludeEqualSpecified == false)
        {
            return;
        }

        if (_isIncludeEqualSpecified && !_includeEqual)
        {
            return;
        }

        _includeEqual = true;
    }
}
```
