### ISSUE TITLE
Module Manifest Import Checks

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#1185]
Some work may be required to more gracefully handle module imports when modules are incompatible with PowerShell Core.

**Comment by SteveL-MSFT** [comment]
Seems like PSGallery should cover most common case of preventing install of incompatible modules.  Seems like an edge case for someone to xcopy an incompatible module.

**Comment by iSazonov** [comment]
@SteveL-MSFT It seems we could close the issue.
