### ISSUE TITLE
else statement does not work on new line

### ISSUE THREAD

**Issue by DanielFrei64** [PowerShell/PowerShell#11854]
# Steps to reproduce
The following script
```powershell
$i = 1
if ($i -eq 1) {
    Write-Output "i equals 1"
}
else {
    Write-Output "i does not equal 1"
}
```
fails with the error:

```none
else: The term 'else' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
however, simply moving "else" up one line along side the } makes the script work

```powershell
$i = 1
if ($i -eq 1) {
    Write-Output "i equals 1"
} else {
    Write-Output "i does not equal 1"
}
```
# Expected behavior

```none
"else" should be allowed to be on a new line and not error
```

# Actual behavior

```none
else: The term 'else' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

# Environment data
Tested out on multiple systems

```none
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This looks like this might be similar to #9499, however, my results are different than his. He specifies it works on Windows, in my case, and a few other Windows systems it does not.

**Comment by jhoneill** [comment]
This is pasting into the PowerShell console? Or in a .PS1 file ?

**Comment by DanielFrei64** [comment]
It works fine when running as a ps1 but if pasting it into the console or opening it up in vscode and running the section manually it will error

**Comment by jhoneill** [comment]
It's a general problem because the parser sees the } belonging to IF as the end of a statement. 
This is something Psreadline is _meant to _ handle , can you double check what version of psreadline you have.

**Comment by mklement0** [comment]
This is a long-standing PSReadLine issue: https://github.com/PowerShell/PSReadLine/issues/579

In short: Unix terminals in general and the Windows console when you right-click (as opposed to using <kbd>Ctrl-V</kbd>) paste the text by _simulated typing_, which PSReadLine is unaware of and therefore stops once a statement is complete.
The plan is to use the timing of the keystrokes received to _guess_ when typing is being simulated.

In VSCode, if you use the PowerShell extension's `Run Selection` command to run a block of lines, you should _not_ experience the problem, however.

 (By contrast, the PowerShell Integrated Console running in VSCode's integrated terminal doesn't use PSReadLine (yet?) at all, and only knows line-by-line pasting).

**Comment by DanFrei64** [comment]
So I’m my case, I am using vscode and the powershell extension “run selection” command and I am experiencing this behavior, you are correct that the integrated terminal is not experiencing this same issue. At least in my couple of test cases.

**Comment by vexx32** [comment]
@DanFrei64 is that in the PowerShell or powershell-preview extensions? The latter I think may have additional handling that improves that scenario...

**Comment by mklement0** [comment]
@DanFrei64, I was trying to say that the integrated terminal behaves even less helpfully by submitting _each line_ pasted as its own command.

I don't think any pasting is involved when you use `>PowerShell: Run Selection` (<kbd>F8</kbd>), so I see no problems, neither on Windows nor on macOS (VSCode 1.42.1, PowerShell extension 2020.1.0)

Note that there's also the non-PowerShell-specific `>Terminal: Run Selected Text in Active Terminal` command, which again behaves like the integrated terminal: each line is submitted as its own command.

**Comment by DanielFrei64** [comment]
To answer another question from above, I was running PSReadline 2.0.0 rc2. I just updated to PSReadline 2.0.0 released a couple of days ago but it is still happening. 

I did try the Powershell Preview extension, as well as the "Terminal: Run Selected Text in Active Terminal" command, but it still resulted in the error. 

We recently went through all of our powershell shell scripts and autoformatted them based on the PSScriptAnalyzer, which defaults it to putting the else on the next line. And now of course I'm looking at going move to pscore and thus my issue, so I appreciate the help. Also worth noting, this happens on pscore6 as well but if I'm understanding correctly, this is more an issue with psreadline than pscore.

**Comment by mklement0** [comment]
To be clear: the `>Terminal: Run Selected Text in Active Terminal` command _shouldn't be expected to work_ - by design, it submits each line one by one.

Are you really seeing the problem when you use `>PowerShell: Run Selection` (<kbd>F8</kbd>)?

>  if I'm understanding correctly, this is more an issue with psreadline than pscore.

Yes, though it would be more accurate to says that the problem stems from how terminal programs perform pasting (simulated typing), and that a nontrivial, yet-to-be-implemented workaround is possible in PSReadLine.

**Comment by DanielFrei64** [comment]
@mklement0 Yes. pwsh terminal, >PowerShell: Run Selection (F8) I receive the error

**Comment by mklement0** [comment]
@DanFrei64, If the integrated terminal just happens to be running `pwsh` _as a shell_, that would explain the problem.

What you _should_ be running is the _PowerShell Integrated Console_, which is a special PowerShell instance that comes with the VSCode PowerShell extension, which integrates with the editor to provide linting, debugging, ...
Only if the integrated terminal shows 
![image](https://user-images.githubusercontent.com/588825/74581383-eed99f80-4f7c-11ea-9b09-c9a79cae2367.png) in the top right corner are you truly running the PowerShell Integrated Console, and only then will `>PowerShell: Run Selection` (<kbd>F8</kbd>) work as expected.

**Comment by jhoneill** [comment]
@mklement0  makes an important point with the non-integrated shell text is just typed not fed as a block.  Just for the record, I took this code 
```
if ($true) {"boo"}
else {"hoo"}
```
and tried copy/paste and F8 in most of the permutations - results below
```
Paste
Windows PowerShell 5.1 ISE (no PsReadLine )                                     line continues
Windows PowerShell 5.1 or PowerShell 7 RC2 / std or terminal with PsReadLine    line continues
Windows PowerShell 5.1 or PowerShell 7 RC2 / std or terminal without PsReadLine line breaks
VSCode with PowerShell 7 RC2 shell OR Integrated console and PSreadline         line breaks
F8 in Edit window
Windows PowerShell 5.1 ISE                                                      line continues
VSCode with Integrated console                                                  line continues 
VSCode with shell                                                               line continues  
```

**Comment by iSazonov** [comment]
We have many discussion about this https://github.com/PowerShell/PowerShell/issues?utf8=%E2%9C%93&q=is%3Aissue+continuation
