### ISSUE TITLE
Simplified calculated property syntax

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#11866]
## Property table
Since I am using calculated properties I am questioning the current its syntax: *Why do I need to assign the name of the concerned property to a new name/label while the property(/column) name is literally *key* by itself? Why can't I just instantly assign the (calculated) values to the property (name) in a hash table similar to what is done in the related constructor of that object?*

<sub>To put this in perspective with the recent requests #11607 and #11617, you might as well consider to update the classic [`New-Object`]([https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-object?view=powershell-7](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-object?view=powershell-7)) cmdlet property parameter to be compliant with calculated properties: <strike> `New-Object -COMObject InternetExplorer.Application -Property @{Name = 'Navigate2'; Value = "www.microsoft.com"}, @{Name = 'Visible'; Value = $True}`</strike></sub>

## Multiple property attributes
For `Select-Object`, which has in fact a single calculated property attribute (if you do not count `Name`/`Label`),  a calculated property syntax like `<name>={<expression>}`is easy to imaging, but there other cmdlets, like `Sort-Object` and `Format-Table`, that support calculated properties. And the property parameter of those cmdlets support more attributes than just the expression, as e.g. `Ascending`, `Descending`, `FormatString`, `Width` and `Alignment`.   
As the value of these property attributes are currently represented as common (`string` and `integer`) datatypes, it hard to recognize them by type but that is not the case if those values are predefined by object classes (and enumerations). Meaning that it would than be possible to explicitly define each property attribute by its type prefix and as the common types (and enumeration values) used by the constructors of those classes are known, it is also possible to implicitly refer to common property attributes.

## Wrappers
Unfortunately I am not experienced enough with C# but to test and show the idea, I have created 3 simple PowerShell wrappers (not caring about the parameter constrains and correctly processing the pipeline):

 1. `Select2` wraps around the `Select-Object` cmdlet 
 2. `FT2` wraps around the `Format-Table` cmdlet
 3. `Sort2` wraps around the `Sort-Object` cmdlet
  
Each of the wrappers is able to process properties as usual and recognize the purposed syntax. Any property in the purposed format is translated to the current format and passed to the related cmdlet.

```PowerShell
class Expression {
    [ValidateNotNullOrEmpty()][ScriptBlock]$Value
    Expression ([scriptblock]$Value) {$this.Value = $Value}
    Expression ([string]$Value) {$this.Value = [ScriptBlock]::Create("`$_.'$Value'")}
}
class FormatString {
    [ValidateNotNullOrEmpty()][string]$Value
    FormatString ([string]$Value) {$this.Value = $Value}
}
class Width {
    [ValidateNotNullOrEmpty()][int]$Value
    Width ([int]$Value) {$this.Value = $Value}
}
enum Alignment {Left; Center; Right}
enum Ascending {Ascending}
enum Descending {Descending}

Function ConvertProperty([HashTable]$Parameters, [Type[]]$ExplicitTypes = @(), [Switch]$Immutable) {
    $EnumItems = @{}; $ImplicitTypes = @{}
    ForEach ($Type in (@([Expression]) + $ExplicitTypes)) { # The later $ExplicitTypes will overrule.
        If ($Type.BaseType.Name -eq 'Enum') {
            ForEach ($EnumName in $Type.GetEnumNames()) {
                $EnumItems[$EnumName] = $Type
            }
        } Else {
            ForEach ($Constructor in ($Type.GetConstructors())) {
                $ImplicitTypes[$Constructor.GetParameters()[0].ParameterType.Name] = $Type
            }
        }
    }
    $ExplicitTypes = @([Expression]) + $ExplicitTypes
    $LegacyKeys = ('Name', 'Label', 'Expression') + $ExplicitTypes.Name
    $LegacyKeys = ForEach ($Key in $LegacyKeys) {
        For ($i = 1; $i -le $Key.Length; $i++) { $Key.SubString(0, $i) }
    }
    If ($Parameters.Property) {
        $Parameters['Property'] = ForEach ($Property in $Parameters.Property) {
            If ($Property -is [System.Collections.IDictionary]) {
                ForEach ($Key in $Property.Get_Keys()) {
                    $Exclusive = $Key -IsNot [String] -or !($LegacyKeys -Contains $Key)
                    If ($Exclusive) { Break }
                }
                If ($Exclusive) {
                    ForEach ($Key in $Property.Get_Keys()) {
                        $HashTable = @{}
                        ForEach ($Value in $Property.$Key) {
                            If ($Null -ne $Value) {
                                $Type = $Value.GetType()
                                If ($ExplicitTypes.Contains($Type)) {
                                    $HashTable[$Type.Name] = If ($Type.BaseType -eq [Enum]) { "$Value" } Else { $Value.Value }
                                } ElseIf ($EnumItems.ContainsKey($Value) -and !$HashTable.ContainsKey($Type.Name)) {
                                    $HashTable[$EnumItems[$Value].Name] = If ($EnumItems[$Value].Name -eq $Value) { $True } Else { $Value }
                                } ElseIf ($ImplicitTypes.ContainsKey($Type.Name) -and !$HashTable.ContainsKey($Type.Name)) {
                                    $HashTable[$ImplicitTypes[$Type.Name].Name] = $Value
                                } Else { Write-Error "Cannot resolve property Value: $Value" }
                            } Else { Write-Error 'Property Value cannot be null' }
                        }
                        If ($Key -is [Expression]) {$HashTable['Expression'] = $Key.Value}
                            ElseIf ($Key -is [ScriptBlock]) {$HashTable['Expression'] = $Key}
                            ElseIf ($HashTable.ContainsKey('Expression')) {$HashTable['Name'] = "$Key"}
                            Else {$HashTable['Expression'] = "$Key"}
                        $HashTable
                    }
                } Else { $Property }
            } Else { $Property }
        }
    }
#   Write-Host ($Parameters | ConvertTo-Expression -Expand 1)    # https://www.powershellgallery.com/packages/ConvertTo-Expression
    Write-Output $Parameters
}

Function Select2 {
    [CmdletBinding()]
    param(
        [object[]]$Property,
        [Parameter(ValueFromPipeline=$true, Mandatory=$true)]$InputObject,
        [String]$ExcludeProperty, [String]$ExpandProperty,
        [Switch]$Unique, [Int]$Last, [Int]$First, [Int]$Skip, [Switch]$Wait

    )
    $Null = $PSBoundParameters.Remove('InputObject')
    $Parameters = ConvertProperty $PSBoundParameters
    $Input | Select-Object @Parameters
}

Function FT2 {
    [CmdletBinding()]
    param(
        [object[]]$Property,
        [switch]$AutoSize, [switch]$RepeatHeader, [switch]$HideTableHeaders, [switch]$Wrap,
        [object]$GroupBy, [string]$View, [switch]$ShowError, [switch]$Force, 
        [ValidateSet('CoreOnly','EnumOnly','Both')]$Expand,
        [Parameter(ValueFromPipeline=$true, Mandatory=$true)]$InputObject
    )
    $Null = $PSBoundParameters.Remove('InputObject')
    $Parameters = ConvertProperty $PSBoundParameters ([FormatString], [Width], [Alignment])
    $Input | Format-Table @Parameters
}

Function Sort2 {
    [CmdletBinding()]
    param(
        [object[]]$Property,
        [switch]$Stable, [switch]$Descending, [switch]$Unique,
        [Parameter(ValueFromPipeline=$true, Mandatory=$true)]$InputObject,
        [string]$Culture, [switch]$CaseSensitive
    )
    $Null = $PSBoundParameters.Remove('InputObject')
    $Parameters = ConvertProperty $PSBoundParameters -Immutable ([Ascending], [Descending])
    $Input | Sort-Object @Parameters
}
```
## Change
To prevent a breaking change, the wrappers test for any known property attribute name (`Name`, `Label`, `Expression,`...) or abbreviation (`n`, `l`, `e,`...) and if found, it will assume the current property syntax layout and exclude it from the conversion. This could be a little stricter by excluding anything that would produce an error like:
 
 > `The <keyname> key is not valid.`
> `A mandatory entry for expression is missing.`
> `The <keyname> key has a type, System.Object[], that is not valid; expected type is System.String.`

<sub>In the unlikely case of an overlap (where e.g. the property names have similar names and value types as the property attributes), the current syntax implementation will simply take priority.</sub>

## Typecasting
Once the a dictionary item is considered to be an new syntax, it will parse the (array of) property attributes in the following order:
 1. **Explicit**, the attribute is a predefined property attribute type (e.g. `[Expression]'<expresson>'`.
 2. **Implicit enumeration value**, the (`[Srting]`) attribute is listed by any predefined attribute (`[enum]`) enumerations.  (e.g. `Left`, `Center` or `Right` for `[Alignment]`).
 3. **Implicit type**,  the common type of the attribute is used by one of the constructors of the predefined attribute classes (e.g. `[Int]` for `[Width]`, `[String]` for `[FormatString]`,  and `[ScriptBlock]` for `[Expression]`). <br>
<sub>In the event the variety of calculated properties crow that much, and an unlikely conflict arise, <strike>the order of the attribute might also be taken in consideration</strike>(requires `[orderer]` attribute table, see #8107). Besides specific attribute can always been forced using explicit property attributes. </sub>

## Disadvantage
The disadvantage of the purposed solution is that all possible property attributes need to be predefined. This could be through some more advanced sub classes contained by a larger "decoration" class and possibly some type accelerators. (Unfortunately, I am not aware of any technique that can be done in the scope of the cmdlet but prior loading the parameters and doubt that exists.) At the other hand predefined property attributes could also be useful to decorate an object and set the default attribute of a property along with the object itself rather than defining the attributes with the `-Property` parameter of the specific cmdlet.

## Examples

**`Select-Object`**

```PowerShell
# Current syntax:
Get-ChildItem | Select2 Name,
    @{label='Size';expression={ $_.length/1KB }},
    @{l='Days';e={ ((Get-Date) - $_.LastAccessTime).Days }}

# Purposed implicit syntax:
Get-ChildItem | Select2 Name,
    @{Size = { $_.length/1KB }},
    @{Days = { ((Get-Date) - $_.LastAccessTime).Days }}
```

You could also put all properties in one hash table:

```PowerShell
Get-ChildItem | Select2 Name, @{
    Size = { $_.length/1KB }
    Days = { ((Get-Date) - $_.LastAccessTime).Days }
}
```

But in this case the order will be lost (I am not sure when this can be be resolve take in account that the order will not be lost in a new/ordered object constructor syntax). Anyways, it is also possible to provide an `[Ordered]` dictionary:

```PowerShell
Get-ChildItem | Select2 Name, ([Ordered]@{
    Size = { $_.length/1KB }
    Days = { ((Get-Date) - $_.LastAccessTime).Days }
})

# Purposed explicit syntax:
Get-ChildItem | Select2 Name, @{
    Size = [Expression]{ $_.length/1KB }
    Days = [Expression]{ ((Get-Date) - $_.LastAccessTime).Days }
}
```

**`Format-Table` example 1**

```PowerShell
# Current syntax:
get-date | ft2 'Date',
    @{Name = 'Time'; Expression = { $_ }; FormatString = 'T'},
    @{Name = 'Min'; Expression = { (60 - $_.Minute)/60 }; FormatString = 'P'; Alignment = 'Left'} -AutoSize

# Purposed implicit syntax:
get-date | ft2 'Date',@{Time = { $_ }, 'T'; Min = { (60-$_.Minute)/60}, 'P', 'Left' } -AutoSize

# Purposed explicit syntax:
get-date | ft2 'Date',@{
    Time = [Expression]{ $_ },'T'
    Min = [Expression]{ (60-$_.Minute)/60 }, [FormatString]'P', [Alignment]'Left'
} -AutoSize
```

**`Format-Table` example 2**

```PowerShell
$Table = ConvertFrom-Csv @'
AAA,BBB,CCC
1,2,3
4,5,6
'@

# Current syntax:
$Table | FT2 @{'Alignment' = 'Left'; 'Expression' = 'AAA'; 'Width' = 10},
    @{'Alignment' = 'Center'; 'Expression' = 'BBB'; 'Width' = 10},
    @{'Alignment' = 'Right'; 'Expression' = 'CCC'; 'Width' = 10}

# Purposed (implicit) syntax:
$Table | FT2 @([Ordered]@{AAA = 'Left', 10; BBB = 'Center', 10; CCC = 'Right', 10})
```

**`Sort-Object` Example 1**
Note that the properties of the objects passed thru the `Sort-Object` do not change and therefore expressions are not added to the properties as with `Select-Object` and `Format-Table`

```PowerShell
# Current syntax:
Get-ChildItem | Sort2 @{Expression = 'Length'; Descending = $True}

# Purposed syntax:
Get-ChildItem | Sort2 @{Length = 'Descending'}
```

**`Sort-Object` Example 2**

```PowerShell
# Current syntax:
Get-ChildItem | Sort2 @{Expression = { $_.CreationTime - $_.LastWriteTime }; Descending = $True}

# Purposed syntax:
Get-ChildItem | Sort2 @{{ $_.CreationTime - $_.LastWriteTime } = 'Descending'}
```

**Comment by HumanEquivalentUnit** [comment]
Looks like it's related to request #8107
