### ISSUE TITLE
File Headers

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#1186]
We need to have a proper and consistant file header message in the source files 
-Some source files have no headers.
-Some has "Copyright (c) Microsoft Corporation.  All rights reserved."
-Some like OneGet has Apache License

**Comment by joeyaiello** [comment]
I don't think that we actually need consistent header messages (as some codefiles have more specific copyrights based on their heritage), but I'll follow up with legal.

**Comment by joeyaiello** [comment]
Case 1 is correct. Case 2 is redundant but harmless because the MIT license applies to everything. Case 3 doesn't apply anymore because OneGet is not in this repository.
