### ISSUE TITLE
Start-ThreadJob holds a large amount of memory

### ISSUE THREAD

**Issue by Life3Code** [PowerShell/PowerShell#11875]
While testing the new Start-ThreadJob in Windows Server 2019, I kicked off 10000 back-end jobs with the command below:
    
    _**1..10000 | % {Start-ThreadJob -Name "Test" -ScriptBlock {sleep 3} -ThrottleLimit 2048}**_

The pwsh.exe process acquired most of the system memory, which is expected. After finished testing, I ran _**Get-Job | Remove-Job**_ to release the system resource, however the memory in pwsh.exe process is not released, it still holds a large amount of memory.

**Comment by anmenaga** [comment]
PowerShell is a .NET app, so it is .NET that manages memory; `Remove-Job` just makes job-related memory available for [.NET garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals).
Used memory should go down if you force .NET garbage collection:
```
PS C:\> Get-Job | Remove-Job -Force
PS C:\> "Memory used before collection: $([System.GC]::GetTotalMemory($false))"
Memory used before collection: 4633516304
PS C:\> [System.GC]::Collect()
PS C:\> "Memory used after full collection: $([System.GC]::GetTotalMemory($true))"
Memory used after full collection: 83220320
```

**Comment by Life3Code** [comment]
Thank you. memory consumption remained low after running garbage collection.This fixed the problem,
