### ISSUE TITLE
$Env:PSModulePath is not correct

### ISSUE THREAD

**Issue by FreZZZeR-I** [PowerShell/PowerShell#11883]
# Steps to reproduce
Clearly installation Windows 10 1909 Ent
Install PowerShell 6.2.4 X64 by msi
```powershell
[Environment]::GetEnvironmentVariable("PSModulePath", "Machine").Split(";")
[Environment]::GetEnvironmentVariable("PSModulePath", "Process").Split(";")
$env:PSModulePath.Split(";")
```

# Expected behavior
$env:PSModulePath.Split(";") returns "Machine", "User"(if exist) and "Process" paths include "C:\Program Files\WindowsPowerShell\Modules"
```
C:\Users\User1\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\6\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\Windows\system32\WindowsPowerShell\v1.0\Modules
```

# Actual behavior
$env:PSModulePath.Split(";") returns only "Process" paths
```
C:\Users\User1\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\6\Modules
C:\Windows\system32\WindowsPowerShell\v1.0\Modules
```

# Environment data

Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```none

```

P.S. Other checks:
- PowerShell 5.1.18362.145 returns $env:PSModulePath with "C:\Program Files\WindowsPowerShell\Modules"
- PowerShell 7.0.0-rc.2 returns $env:PSModulePath with "C:\Program Files\WindowsPowerShell\Modules"

I tried add path "C:\Program Files\WindowsPowerShell\Modules" to User environment but it works on PowerShell  5.1 or 7.0rc2 and doesn't work on PowerShell 6.2.4

**Comment by iSazonov** [comment]
@FreZZZeR-I Since 7.0 version will be released in days you can use it. 6.* versions is servicing versions and  only security updates will be backported to them.

**Comment by FreZZZeR-I** [comment]
Thanks! 
Working Solution for PowerShell 6.*
Needed change user powershell profile adding paths to $env:PSModulePath

More info: 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7
