### ISSUE TITLE
Compress-Archive fails on large file (8 GB) on ARM64

### ISSUE THREAD

**Issue by jcbottorff-marvell** [PowerShell/PowerShell#11893]
I was trying to compress a crashdump on a ARM64 system, and get the following error.

PS C:\Temp\PowerShell-7.0.0-rc.2-win-arm64> Compress-Archive -Path ..\memory.dmp -DestinationPath ..\memoryWithFw.zip
MethodInvocationException: C:\temp\powershell-7.0.0-rc.2-win-arm64\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:845
Line |
 845 |  …                     $destStream.Write($buffer, 0, $numberOfBytesRead)
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Write" with "3" argument(s): "Stream was too long."

The file was:
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           2/19/2020  1:50 AM     8547379611 memory.dmp

File Explorer->SendTo->CompressedFolder works fine on the same file and system.

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19
