### ISSUE TITLE
X509Certificate Extension / AsnEncodedData

### ISSUE THREAD

**Issue by chrisdi89** [PowerShell/PowerShell#11902]
I don't know if the powershell github repo is the right place for this bug.
I choose the powershell Repo, because i have the problem with powershell.

i use powershell.core on debian linux at an lxc container.
The Host for the lxc is proxmox 5.4-13 wich is basend on debian stretch with an customized kernel.
the lxc container is debian 9.12.

the installed powershell version is:
![image](https://user-images.githubusercontent.com/25806780/74921115-961b6400-53cd-11ea-8401-fb07e8270dab.png)

The issue is a difference behavior with the "System.Security.Cryptography.AsnEncodedData" object between windows and linux.

the reference windows client is an windows 10 1909 with powershell 5.
![image](https://user-images.githubusercontent.com/25806780/74920886-2a38fb80-53cd-11ea-95d4-3d10eaa6a0cb.png)
i confirmed the windows behavior on multiple windows server os from windows 2012r2 upwards.

on windows, when i use the format method of an System.Security.Cryptography.X509Certificates.X509Extension with the oid 1.3.6.1.5.5.7.1.1the output is an string with all enumerations of the oid.

![image](https://user-images.githubusercontent.com/25806780/74920794-0aa1d300-53cd-11ea-8ed2-548640ebfca2.png)

when i make the same format on the powershell for linux, i only get the first enumeration of the oid
![image](https://user-images.githubusercontent.com/25806780/74921061-7b48ef80-53cd-11ea-8e18-220c8b94eda4.png)

the powershell commands to reproduce the issue:
```
$Cert = [System.Security.Cryptography.X509Certificates.X509Certificate2][X509Certificate]::new((iwr http://cert.stg-int-x1.letsencrypt.org/).Content)
$Cert.Extensions.Item("1.3.6.1.5.5.7.1.1").format($true)
```

if you need futher information please let me know, or if its the wrong github repo.

Regards

Chris

**Comment by iSazonov** [comment]
It looks like .Net Core issue. Please move the report to .Net Core Runtime repo https://github.com/dotnet/runtime
