### ISSUE TITLE
Extract-Archive should allow encoding as a parameter

### ISSUE THREAD

**Issue by lbruun** [PowerShell/PowerShell#11901]
# Summary of the new feature/enhancement

The `Extract-Archive` cmdlet does not currently allow the define the expected encoding of file names in the archive to the expanded. This means the cmdlet cannot predictably be used to expand ZIP files created with other tools than PowerShell itself (meaning `Compress-Archive`).

For example, the `Extract-Archive` cmdlet cannot predictably unpack an archive created directly from Windows File Explorer, using its build-in feature for ZIPs. This is Windows not being compatible with Windows and should be fixed.

# Proposed technical implementation details (optional)

Solution is to allow encoding as a parameter to the cmdlet and to document what happens if such parameter is _not_ specified, which is the current behavior.

Note: Overall I like what `Compress-Arhive` is doing, consistently using UTF-8 for the file names, but the truth of the matter here is that most PowerShell users will expect to be able to use `Extract-Archive` cmdlet to also expand archives which were not created by PowerShell itself.

**Comment by iSazonov** [comment]
Please move the request in https://github.com/PowerShell/Microsoft.PowerShell.Archive
