### ISSUE TITLE
New PowerShell Profiles for PowerShell

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#1190]
# Overview
PowerShell Core instances shall support their own set of profiles. The profiles shall be placed in  PowerShell Core specific directories and have PowerShell Core specific names. Additional code will be needed to load the profiles from the new locations. Mostly it looks like a task to IFDEF the components of the name and path to be appropriate for PowerShell Core.

# New Profiles
Name = PowerShell Core File and path
AllUsersAllHosts = $PSHome\profile.ps1
AllUsersCurrentHost = $PSHome\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts = ~\Documents\PowerShell\profile.ps1
CurrentUserCurrentHost = ~\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

**Comment by daxian-dbw** [comment]
I'm not sure why we are changing `Microsoft.PowerShell_profile.ps1` to `PowerShell_profile.ps1`. In our terminology, `Windows PowerShell` means powershell for full desktop, so I get that we should change any `WindowsPowerShell` to `PowerShell`. But powershell core is still Microsoft powershell, not? Are we saying that `Microsoft PowerShell` also indicates powershell for full desktop?

**Comment by vors** [comment]
Terminology reference https://blogs.msdn.microsoft.com/powershell/2016/08/18/powershell-on-linux-and-open-source-2/

**Comment by mirichmo** [comment]
This change only applies to (Platform.IsCoreCLR && ! Platform.IsInbox)

@HemantMahawar Please confirm

**Comment by daxian-dbw** [comment]
I think we should keep the same file names as in desktop powershell. The path to the files will be different anyways -- `WindowsPowerShell` in desktop powershell and nano/iot inbox powershell, `PowerShell` in powershell core on windows platform.

**Comment by HemantMahawar** [comment]
@mirichmo Yes, this change only applies to PlatForm.IsCoreCLR && ! Platform.IsInbox
@daxian-dbw You are correct w.r.t the file name. The profile files are tied to the host name (for ISE it is Microsoft.PowerShellISE_profile.ps1), since we are not changing the host name for console host, no need to change the profile file name. I have updated them in the issue description.

**Comment by charub** [comment]
Closing this issue as it's no longer needed.
