### ISSUE TITLE
PowerShell Common Launcher for Windows

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#1192]
# Overview

PowerShell Core for Windows should support a common launcher that can start either a specified version of or a "default" version .
# Changes Required
1. An executable or script that supports a -version <version> parameter and passes cmd line arguments to an instance of PowerShell.exe
2. The executable or script resides is %ProgramFiles%\PowerShell\powershell.exe
3. It determines the "default" instance of PowerShell by reading a value from a configuration file in its same directory. File type and format are flexible and should be driven by the ease of parsing the info.
# Open Issues
1. The exact design has not yet been finalized. This is a place holder issue to note that work is likely required to support the desired behavior.
2. On non-Windows systems, the installer already creates a symlink on the path that points to the latest installed instance of PowerShell. No additional work is likely required in those environments.

**Comment by SteveL-MSFT** [comment]
Last discussion by @PowerShell/powershell-committee is that using file paths is sufficient and user can use symlinks to change default
