### ISSUE TITLE
Portuguese keyboard on Linux does not handle home, end and altgr combinations on Linux

### ISSUE THREAD

**Issue by rjfmachado** [PowerShell/PowerShell#11926]
# Steps to reproduce

Hit Keyboard home, end, @, £ and others does not produce expected results

# Expected behavior

Keyboard works...

# Actual behavior

I get ~ for home, end
and the digit-argument input for altgr+number keys

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Linux 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

tried ssh from cmd and windows terminal as I've seen this in the past in local powershell in WT.

**Comment by iSazonov** [comment]
@rjfmachado Can you try without PSReadline module? (`Remove-Module PSReadline`)

**Comment by rjfmachado** [comment]
That resolves the altgr combos, but home/end still do not work, HOME does go to the start of the line, but prints 1~, END only prints 4~
![2020-02-23_08-49-43](https://user-images.githubusercontent.com/3235846/75105961-b5a6cc80-5619-11ea-96d1-1695749f1ace.gif)

**Comment by rjfmachado** [comment]
also, when using without PSReadline, occasionally the cursor jumps to the start of the line for no reason (changed by cursor to make this easier to see)
![2020-02-23_09-01-50](https://user-images.githubusercontent.com/3235846/75106313-85602d80-561b-11ea-9614-910da626e7fc.gif)

**Comment by iSazonov** [comment]
@daxian-dbw Could you please comment the Issue?

**Comment by daxian-dbw** [comment]
@rjfmachado Does Portuguese keyboard works as expected with pwsh on Windows (win 10)?

**Comment by rjfmachado** [comment]
Yes, all keys work and PSReadline also has no issues. I only see this on Linux, I'm using the inbox ssh on Windows 10 if this helps (Windows 10 18363, OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5)

**Comment by iSazonov** [comment]
@rjfmachado Could you please add more info about your scenario? Do you use Windows terminal, open SSH session to Linux and run pwsh?

**Comment by rjfmachado** [comment]
That's it, Windows Terminal calling ssh to ubuntu 18.04 then from bash, run pwsh-preview

**Comment by rjfmachado** [comment]
the 7.0.0 GA fixed the AltGr combinations, home/end issue remains

**Comment by iSazonov** [comment]
It is dup #8869

**Comment by lzybkr** [comment]
This is most likely a .Net issue - see https://github.com/dotnet/runtime/issues/802
