### ISSUE TITLE
Fix class base-call AST structure

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#11936]
Currently class ASTs don't accurately describe the actual syntax parsed.

One issue is that `base` calls that aren't explicitly invoked are inserted into the AST:

```powershell
class Thing
{
    Thing() # <- the parser inserts a base() call here
    {
    }
}
```

has the same AST as

```powershell
class Thing
{
    Thing() : base()
    {
    }
}
```

```
> { class Thing { Thing() { } } }.Ast.EndBlock.Statements[0].Members[0].Body.EndBlock.Statements[0].Expression.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    BaseCtorInvokeMemberExpressionAst        System.Management.Automation.Language.InvokeMemberExpres…
```

(This expression has an empty extent given to it so it won't appear...)

The second issue is that the actual base call is not transparently recorded in the AST. Instead it's converted into the first statement in the method script block, which is much harder to discover:

```powershell
class Thing : System.Collections.Hashtable
{
    Thing($count) : base($count)
    {
    }
}
```

```
> { class Thing : System.Collections.Hashtable { Thing($count) : base($count) {} } }.Ast.EndBlock.Statements[0].Members[0].Body.EndBlock.Statements

Expression   Redirections Extent       Parent
----------   ------------ ------       ------
base($count) {}           base($count)
```

These idiosyncrasies make it harder to tool class ASTs (e.g. in the pretty printer I'm writing).

**Comment by rjmholt** [comment]
Meant to mention that this occurs here:

https://github.com/PowerShell/PowerShell/blob/697dc5b37149d0dd98c34c33a87c833a23fe467e/src/System.Management.Automation/engine/parser/Parser.cs#L5214-L5231

**Comment by iSazonov** [comment]
I used such workaround while playing with getters/setters :-) So I guess there could be other (many!) such patterns. Huge work to review manually... Maybe we could create a tool to automate this process (parse-recover-compare)?

**Comment by rjmholt** [comment]
> I used such workaround while playing with getters/setters :-)

Absolutely fair enough when prototyping.

My feeling is that the AST's job is to faithfully represent the syntax, and it's up to the compiler (or other AST consumer) to decide how it deals with absent pieces. Basically my feeling is that this is a layering violation. But I'm not sure if others agree with me.

> So I guess there could be other (many!) such patterns. Huge work to review manually... Maybe we could create a tool to automate this process (parse-recover-compare)?

I'm not sure how easy this would be to automate, given that it has to compare user expectation (and the AST is very much the API for it -- we're hitting places where the API is kinda lying). I've hit a couple of things like this before and have a small internal catalogue of them (and suspect others might too), so we could ask for people to dump anything they've been holding on to in issues. Also, I hit this writing [this](https://github.com/rjmholt/MicrosoftPowerShellModules/blob/asttools/Modules/Microsoft.PowerShell.AstTools/src/PrettyPrinter.cs), which has been a nice comparison tool between what the AST literally encodes vs what the coder wrote. So we might pick up some more there. Also just reading through the parser might pick some of these up.
