### ISSUE TITLE
pwsh-preview -command argument

### ISSUE THREAD

**Issue by MaynardMiner** [PowerShell/PowerShell#11933]
# Steps to reproduce

I have tried all powershell 7 versions. This behavior is new to Powershell 7, testing with 6.2.4 everything works as intended.

```
Write-Host "This works fine"
Start-Process "pwsh-preview" -Verb Runas

Write-Host "This works fine as well"
Start-Process "pwsh-preview" -ArgumentList "-command ""Write-Host $PSHOME; Start-Sleep -S 60"""

Write-Host "This fails"
Start-Process "pwsh-preview" -ArgumentList "-command ""Write-Host $PSHOME; Start-Sleep -S 60""" -Verb Runas
```

# Expected behavior
pwsh-preview when used with ``Start-Process`` and ``-Verb Runas`` trigger should start, with or without ``-Command`` in ``-Argumentlist``

# Actual behavior
pwsh-preview will start as administrator, but when it is started with ``-Command`` in ``-argumentlist``, it doesn't run/closes immediately.

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It looks like #8898 dup /cc @mklement0

**Comment by mklement0** [comment]
Indeed looks like a duplicate, @iSazonov, thanks.
