### ISSUE TITLE
Add option to allow preserve event order on  Register-ObjectEvent

### ISSUE THREAD

**Issue by rrg92** [PowerShell/PowerShell#11937]
# Summary of the new feature/enhancement

I guess the way how powershell handles events, can cause events being processed in a different order than it was generated

If possible, include a parameter on Register-Object event to let user choose if order which was generated must be preserved.

# Proposed technical implementation details (optional)

I guess that fact of events being handled in a thread pool is causing the out of order (`ThreadPool.QueueUserWorkItem(new WaitCallback(...`).
https://github.com/PowerShell/PowerShell/blob/d58a82ad19fbfad81e85778c8b08cb1b28f58fce/src/System.Management.Automation/engine/EventManager.cs#L923-L961
For example, using powershell to get events generated by SqlClient.SqlConnection.InfoMessage event , causes messages and errors generated by SQL Server being returned in incorrect order, when consumed with Get-Event cmdlet.

To confirm that, I had implemented a custom event handle using a custom type with Add-Type.
I got the SqlConnection and add my own delegate to InfoMessage event, and inserted it on a Queue collection. On powershell, I could read the queue and all messages was generated in correct order.

**Comment by iSazonov** [comment]
@rrg92 Please use more useful issue title.

> I guess the way how powershell handles events, can cause events being processed in a different order than it was generated

@daxian-dbw @PaulHigin Can you confirm the guess?

**Comment by rrg92** [comment]
@iSazonov , sorry. I forgot to change title when opening. It is more intuitive now.

**Comment by daxian-dbw** [comment]
I think @rrg92 is right. When using `Register-ObjectEvent`, PowerShell will register a delegate to the object event that calls to `ProcessNewEvent` with `processInCurrentThread` being `false`, so the call will go through the thread pool code path. And `ThreadPool.QueueUserWorkItem` doesn't preserve the order of execution for the delegates passed to it.

**Comment by iSazonov** [comment]
> that calls to ProcessNewEvent with processInCurrentThread being false,

If we add an option to use `true` can we fall in a thread lock?
