### ISSUE TITLE
Command colors in 6.2.4 are different from 5.1. How to customize colors in 6.2.4?

### ISSUE THREAD

**Issue by devoftheweb** [PowerShell/PowerShell#11935]
![image](https://user-images.githubusercontent.com/9593201/75122453-a0f32480-566b-11ea-9ec5-bc6dfeb59b2e.png)

Left is PowerShell 5.1, right is PowerShell 6.2.4. I obtained this by running:

`[System.Enum]::GetValues('ConsoleColor') | ForEach-Object { Write-Host $_ -ForegroundColor $_ }`

In particular, "Yellow" in 6.2.4 is very light and subdued.

I'm aware that you can change the colors around, say I want error messages to be "Cyan" instead of Red.

However, how can I go about changing the value of the color itself? In this case, yellow.

**I want the yellow in 6.2.4 to reflect the yellow in 5.1. How do I do this?** Thank you!

**Comment by rkeithhill** [comment]
The value of the colors are determined by the hosting app.  For conhost.exe, the colors are set in the shortcut and can be accessed by the Properties menu:

![image](https://user-images.githubusercontent.com/5177512/75123538-903fb000-5665-11ea-985f-10750e83f244.png)

This is the color in question:

![image](https://user-images.githubusercontent.com/5177512/75123555-b6655000-5665-11ea-860e-a10428f1626e.png)

You can change it. Just make sure you set the `Screen Text` color back to the index just to the right of the dark yellow index (square).  

Windows Terminal handles this in a completely different way, allowing you to specify a named color scheme (including any custom color schemes you define) in the profiles.json file for Windows Terminal:
```
      {
        // Make changes here to the cmd.exe profile
        "colorScheme": "Campbell",
        "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "name": "cmd",
        "commandline": "cmd.exe",
        "hidden": false
      },
```

**Comment by devoftheweb** [comment]
Hi @rkeithhill ,

I understand how to change the Screen Text, that isn't what I was asking.

**I want to change the value of the color "Yellow" itself to reflect 5.1's (brighter), is that possible?**

Reason being that in 6.2.4, "Yellow" is lighter than in 5.1. I prefer 5.1's implementation of "Yellow" (brighter).

Here is a screenshot. 5.1 on the left, 6.2.4 on the right.

![image](https://user-images.githubusercontent.com/9593201/75127202-e32c5e00-568b-11ea-80bc-6f7c02a6b40f.png)

**Comment by devoftheweb** [comment]
@rkeithhill provided the solution. Thanks Keith!
