### ISSUE TITLE
Features that Do Not Require Modification

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#1195]
# Overview

This is a work-in-progress list of features that have been investigated and determined to not require modification for side-by-side scenarios. I am creating this issue to document the list and reasoning behind the decisions.
# Pwrshsip.dll

This is the Crypto Subject Interface Package (SIP) provider for handling Authenticode signature verification for all signed files PowerShell supports (psd1, psm1, etc.). The provider is loaded by the Authenticode verification system and only one instance should exist in Windows. It is installed via manifest on all Windows SKUs where PowerShell ships inbox. If we need to add additional file types for Authenticode signature verification, we can create a new SIP provider and install it side-by-side with the existing one. The new provider will only support the new file types.

**Comment by ferventcoder** [comment]
@mirichmo just discovered what may be a known issue in PowerShell for checking the authenticode signature if the file has Unix line endings (`LF`) - https://github.com/PowerShell/PowerShell/issues/3361

**Comment by joeyaiello** [comment]
@mirichmo is this still needed? If not, I'm assigning to you to close.

**Comment by SteveL-MSFT** [comment]
Closing this.  If there are specific issues with authenticode, please open separate issues.
