### ISSUE TITLE
Not able to resize PowerShell windows size 

### ISSUE THREAD

**Issue by gaurmayank** [PowerShell/PowerShell#11958]
# Steps to reproduce
1. Launch PowerShell application.
2. Resize PowerShell windows size to half on the screen.
3. Connect to some machine using ssh through PowerShell.
4. Resize PowerShell  windows size to full scree.
5. Press enter PowerShell  window automatically size to the windows size, what was it before ssh.

# Expected behavior
1. PowerShell  window size should be fullscreen 

# Actual behavior
1. PowerShell  windows is resizing automatically 

# Environment data

PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
@gaurmayank The repository is only for PowerShell Core, not Windows PowerShell. Do you the issue in PowerShell Core 7.0 latest version?

**Comment by gaurmayank** [comment]
@iSazonov as per "$PSVersionTable" output 
Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
> PSVersion 5.1.17134.858

It is Windows PowerShell. You should download and install PowerShell 7.0 RC3.

**Comment by gaurmayank** [comment]
@iSazonov  Thanks for your response, i will update and check the same
