### ISSUE TITLE
Add -monthly parameter to New-JobTrigger cmdlet

### ISSUE THREAD

**Issue by notverynick** [PowerShell/PowerShell#11967]
New-JobTrigger does not permit creation of monthly schedules, furthermore, when using Get-ScheduledJob on existing jobs create in the GUI, an error is returned when enumerating jobs which have monthly schedules.

Adding -monthly would allow the creation of such schedules and one would assume thus allow Get-ScheduledJob to enumerate jobs with monthly schedules created in the GUI. 

Should it be deemed inappropriate, i.e. monthly schedules should be created using preexisting schedule types and custom script code, or by some other means. This feature request becomes the necessity to enumerate GUI created jobs with monthly schedules from the CLI, at the very least such that the jobs are listed and do not throw an error.

Finally, if this request is inappropriately placed then please if someone could move it accordingly.

Many thanks in anticipation,

Nick

**Comment by iSazonov** [comment]
@notverynick The cmdlet is not in the repo. Please use other channels like UserVoice site, forums and Windows feedback tool.
