### ISSUE TITLE
[System.Security.Cryptography.X509Certificates.CertificateRequest]::new crashes pwsh 7 rc 3 on mac

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PowerShell#11966]
This worked fine on pwsh 6 up until pwsh 7 rc 2 but started failing on rc3. The pwsh process just exits

RC 3
![image](https://user-images.githubusercontent.com/10071039/75450043-6391de00-596e-11ea-8cba-daf1a4f56ddb.png)

PSv6

![image](https://user-images.githubusercontent.com/10071039/75450172-9b008a80-596e-11ea-9961-12e034a74a14.png)

# Steps to reproduce

```powershell
$rsa = [System.Security.Cryptography.RSA]::Create(2048)

$dn = [X500DistinguishedName]::new('CN="bogus"')

[System.Security.Cryptography.X509Certificates.CertificateRequest]::new(
  $dn,
  $rsa,
  [System.Security.Cryptography.HashAlgorithmName]::SHA256,
  [System.Security.Cryptography.RSASignaturePadding]::Pkcs1
)
```

# Expected behavior

works

# Actual behavior

crashes pwsh process

# Environment data

```none
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I think it is external https://github.com/dotnet/runtime/issues/31020

**Comment by bgelens** [comment]
Might be the case but why did it work without issue from 6 until 7 rc2? The link to the external issue has not been commented on after October 2019 so how come I had no issues until rc3 (for me it's regression)?

**Comment by iSazonov** [comment]
@bgelens PowerShell Core 6.0 is based on .Net Core 2. PowerShell 7.0 is based on .Net Core 3. So I expect it is .Net Core regression.
/cc @SteveL-MSFT for information.

**Comment by bgelens** [comment]
It's fixed in GA!
