### ISSUE TITLE
does not recognize python

### ISSUE THREAD

**Issue by talley** [PowerShell/PowerShell#11977]
I  have python compiler on my computer .

When i type python on powershell core i  get this response.

PS C:\Users\ourota> python
PS C:\Users\ourota>

But when i type python on regular command prompt a get this response

Python 3.6.5 (default, Jul 10 2019, 23:58:39) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

FIX IT

**Comment by vexx32** [comment]
Please follow the issue template and provide proper details from your environment. There's not a lot we can do without the necessary information and proper context given that this very feature is working without issue for the majority of us.

Can you also please check `where.exe python`  from both Command Prompt and PowerShell? As well as `Get-Command python` from PowerShell.

Also, how exactly are you starting PowerShell?

**Comment by TBBle** [comment]
Doers it do *actually* nothing, or does it pop up the Microsoft Store? It's possible there's a difference in `PATH` variable seen by cmd and by PowerShell, and in the latter case it's picking up _C:\Users\paulh\AppData\Local\Microsoft\WindowsApps\python.exe_ which is supposed to launch the Microsoft Store to let you install Python from the Store.

**Comment by Whale-fall** [comment]
> Please follow the issue template and provide proper details from your environment. There's not a lot we can do without the necessary information and proper context given that this very feature is working without issue for the majority of us. I would also recommend making your title a little clearer if you can.
> 
> Can you also please check `where.exe python` from both Command Prompt and PowerShell? As well as `Get-Command python` from PowerShell.
> 
> Also, how exactly are you starting PowerShell?

Hi, I meet the same problem on PowerShell 7 , when I type Python it just pops up the Microsoft Store. Here is some information and I hope it helps
![Snipaste_2020-04-08_18-23-31](https://user-images.githubusercontent.com/22662209/78774006-a1027600-79c6-11ea-8520-bf088f57d5e0.png)

**Comment by vexx32** [comment]
This doesn't sound like an issue with PowerShell. You'd experience the same in CMD; your PATH environment variable is listing the path containing Windows Store shortcut before it lists the executable you've installed via another means.

**Comment by Whale-fall** [comment]
So where can I find a solution to fix it?

**Comment by Whale-fall** [comment]
And when I type python in PowerShell 6, it works correctly.I think it is weird.

**Comment by vexx32** [comment]
@Whale-fall I'd recommend inspectin `$env:PATH` in both versions and see if there are any notable differences between the values.

**Comment by MaximoTrinidad** [comment]
@talley 

Nothing to FIX here! It is not PowerShell, but the Python installer. In some cases, in the installer, I've seen an option to include the path to the environment path variable.

I use Anaconda version of Python, and everything works as expected without having to manually add the path to the $env.

![PythonGood_2020-04-09_13-55-05](https://user-images.githubusercontent.com/19892435/78926267-cc3ea100-7a6a-11ea-82d2-a18eb33ef66d.png)

![PythonGood2_2020-04-09_13-55-05](https://user-images.githubusercontent.com/19892435/78926289-d5c80900-7a6a-11ea-848e-1818b9193de5.png)
