### ISSUE TITLE
Powershell with SUSE enterprise 15

### ISSUE THREAD

**Issue by rcoughtrey** [PowerShell/PowerShell#11973]
I'm having a real hard time with the installation powershell on SUSE enterprise 15. 
We are building out our automation to use remote powershell sessions from a windows Jenkins server to a Linux VM. I have got it working with Centos Redhat SUSE 12x but SUSE 15 is just buggy to get running.

My first issue is that your online steps fail to tar the file.

t-suse150:~ # mkdir -p /opt/microsoft/powershell/7
t-suse150:~ # tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

This made it almost impossible to install.

I then used snapcraft to install powershell and this seems to work. 
Next I then installed the following:

wget https://github.com/microsoft/omi/releases/download/v1.6.4-0/omi-1.6.4-0.ssl_110.ulinux.x64.rpm
rpm -ivh omi-1.6.4-0.ssl_110.ulinux.x64.rpm

wget https://github.com/PowerShell/psl-omi-provider/releases/download/v1.4.2-2/psrp-1.4.2-2.universal.x64.rpm
rpm -ihv psrp-1.4.2-2.universal.x64.rpm

After this all my other distros would allow me to create a PS session to the Linux VM

$SessionOptions = New-PSSessionOption -SkipCACheck -SkipRevocationCheck -SkipCNCheck 
$session = New-PSSession -ComputerName $IPaddress -Credential $creds -Authentication Basic -UseSSL -SessionOption $SessionOptions

Sample part of my script.
There error we get is 

error message : The target namespace does not exist

I seem to find why a connection cannot be created

**Comment by iSazonov** [comment]
@rcoughtrey Please use our issue template to request the OS support.
