### ISSUE TITLE
Get-AzureADMSTrustFrameworkPolicy not present in AzureAD.Standard.Preview module

### ISSUE THREAD

**Issue by erikanderson** [PowerShell/PowerShell#11978]
# Steps to reproduce 

On linux (centos7) installed powershell core and the AzureAD.Standard.Preview module (with some help from https://blogs.endjin.com/2019/05/how-to-use-the-azuread-module-in-powershell-core/).
```
Register-PackageSource -Name PoshTestGallery -Location https://www.poshtestgallery.com/api/v2/ -ProviderName PowerShellGet

Install-Module -Name AzureAD.Standard.Preview -RequiredVersion 0.0.0.10

Import-Module -Name /root/.local/share/powershell/Modules/AzureAD.Standard.Preview/0.0.0.10/AzureAD.Standard.Preview.psm1
```
This is working however as mentioned by others it is missing some cmdlets.
```
PS /home/*****> Get-AzureADMS*
Get-AzureADMSDeletedDirectoryObject  
Get-AzureADMSGroup                  
Get-AzureADMSIdentityProvider
Get-AzureADMSDeletedGroup           
Get-AzureADMSGroupLifecyclePolicy    
Get-AzureADMSLifecyclePolicyGroup
```

The Get-AzureADMSTrustFrameworkPolicy (among others) is not present 

This cmdlet is neccesary for Azure B2C management https://docs.microsoft.com/en-us/azure/active-directory-b2c/manage-custom-policies-powershell

# Expected behavior

`Get-AzureADMSTrustFrameworkPolicy` is available for use 

# Actual behavior

`Get-AzureADMSTrustFrameworkPolicy` is not present 

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Linux 3.10.0-957.41.1.el7.x86_64 #1 SMP Fri Nov 15 06:50:10 EST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@erikanderson Please use latest PowerShell 7.0 version. Also the cmdlets is not in the repo - please move the issue to the module repository.

**Comment by erikanderson** [comment]
Thank you @iSazonov, I have created issue in the modules repo and tested with powershell core 7 

https://github.com/PowerShell/Modules/issues/54
