### ISSUE TITLE
Feature Request: allow parameter to ask for pseudo tty allocation for SSH PSSession

### ISSUE THREAD

**Issue by borgdylan** [PowerShell/PowerShell#11970]
# Summary of the new feature/enhancement

I am finding the SSH remoting feature very useful but it is lacking a featrure that the raw ssh command has. Raw SSH allocates a pseudo-TTY automatically for interactive sessions and of given the parameter `-t` it will also do that for a batch session. Can there be a similar option for `New-PSSession` and `Enter-PSSession`? Pseudo-TTYs are a must to run `sudo` in a remote interactive shell. The workaround of using `<password> | sudo -s <command>` violates a commonly held tenet of not typing passwords where command history may save them.  It maybe acceptable to do so in a batch script but not in an interactive setting where the user is there to type teh password when prompted.

# Proposed technical implementation details (optional)
I propose a new parameter `-AllocateTTY` that would force allocate a pseudo-TTY. According to forums I have looked at the commonly used `Renci.SSHNet` library used for SSH in .NET applications surfaces this option in its APIs.

I expect that I can run sudo normally like when I use the normal ssh command whenever I create and enter a remote SSH based PSSession.

**Comment by iSazonov** [comment]
For reference #11343

**Comment by iSazonov** [comment]
Dup #1527
