### ISSUE TITLE
Installing module where commands already exist on system

### ISSUE THREAD

**Issue by codaamok** [PowerShell/PowerShell#11983]
# Steps to reproduce

Take the scenario where you have a module installed and it exports a function named `Get-FunctionA`. You attempt to install another module from the psgallery where one of its exported functions is also named `Get-FunctionA`. No exception is printed to console however two records are in `$error`.

In Windows PowerShell 5.1, the user is given helpful error record immediately printed to console.

![image](https://user-images.githubusercontent.com/6683266/75624606-cde49180-5bad-11ea-8e89-56aa2da7c5b9.png)

The `AutomatedLab.Common` module has functions named the same that `Indented.Net.IP` offers. So for the below I'll use those two modules

```powershell
Install-Module AutomatedLab -Scope CurrentUser
Install-Module Indented.Net.Ip -Scope CurrentUser
```

# Expected behavior

```none
PS C:\> install-module AutomatedLab -Scope CurrentUser
PS C:\> install-module indented.net.ip -Scope CurrentUser

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from     'PSGallery'?
PackageManagement\Install-Package : The following commands are already available on this system:'ConvertTo-BinaryIP,Co nvertTo-DecimalIP,ConvertTo-DottedDecimalIP,ConvertTo-Mask,ConvertTo-MaskLength,Get-BroadcastAddress,Get-NetworkAddres s,Get-NetworkRange,Get-NetworkSummary'. This module 'Indented.Net.IP' may override the existing commands. If you       still want to install this module 'Indented.Net.IP', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pac     kageManagement.Cmdlets.InstallPackage

PS C:\>
```

# Actual behavior

```none
PS C:\> install-module AutomatedLab -Scope CurrentUser
PS C:\> install-module indented.net.ip -Scope CurrentUser
PS C:\>
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by codaamok** [comment]
Looks like PowerShell 7 has PackageManagement version 1.4.6.

**Comment by iSazonov** [comment]
@alerickson Could you please comment?

**Comment by alerickson** [comment]
I think this is an issue with how the error's being captured and read in PowerShell.
PWSH 6.2.4 w/ PowerShellGet 2.2.3 and PackageMangement 1.4.6 outputs the error as expected:
![pwsh6 2 4jpg](https://user-images.githubusercontent.com/25858831/75718801-6cddbc00-5c88-11ea-9f30-9f467ea84b12.jpg)
but PWSH 7.0.0-rc.3 w/ PowerShellGet 2.2.3 and PackageMangement 1.4.6 
![pwsh7 0 0-rc3 repro](https://user-images.githubusercontent.com/25858831/75718864-8aab2100-5c88-11ea-83e7-49e2b89d094c.jpg)


When I try running the command in PowerShellGet that calls into PackageManagement to install, it throws the error and outputs as expected: 
![psget install](https://user-images.githubusercontent.com/25858831/75720960-47eb4800-5c8c-11ea-8584-625fbf87094e.jpg)

**Comment by iSazonov** [comment]
@SteveL-MSFT It could be again in ConciseView.

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me, getting the expected error message.  If you notice the original error, it's about the collection being modified as the output is being created.  I think this is the same as https://github.com/PowerShell/PowerShell/issues/11797
