### ISSUE TITLE
Case sensitive mac file system

### ISSUE THREAD

**Issue by quantrpeter** [PowerShell/PowerShell#11982]
Hi All. Case sensitive mac file system will cause error.

<img width="1385" alt="powershell in case sensitive mac file system" src="https://user-images.githubusercontent.com/50471577/75623685-84b13380-5be7-11ea-9a2a-01fdf09d2e6f.png">

**Comment by iSazonov** [comment]
@quantrpeter Please move the issue to https://github.com/SharePoint/PnP-PowerShell

**Comment by quantrpeter** [comment]
thanks
