### ISSUE TITLE
Pinned shortcut icon disappears on upgrade

### ISSUE THREAD

**Issue by heaths** [PowerShell/PowerShell#11995]
When upgrading from v7 RC to RC, my pinned pwsh.exe shortcut on the taskbar (pinned from the [shortcut you create](https://github.com/PowerShell/PowerShell/blob/00b60c44fa91606a7458c3e9a428f8d05c0639d7/assets/Product.wxs#L247)) disappears. This is because Windows Installer icons via WiX's `<Icon>` element get random GUIDs that change from release to release. As a former WiX dev and looong-time setup dev, we recommended people away from those icons and other advertised features because of various problems like this.

You can still use it if you want to customize your Add/Remove Programs (ARP) entry like you do via `ARPPRODUCTICON`, but don't set the `Shortcut@Icon` property to it. Instead, omit the `@Icon` attribute and it will default to the first icon index in the target EXE instead of a cached path to the Windows Installer cache that will change from release to release as you rebuild your MSI.

**Comment by iSazonov** [comment]
I thought it was fixed in #9305

**Comment by heaths** [comment]
The `<Icon>` is not tied to a component and has no GUID itself. It's stored within the MSI for advertisement purposes originally (i.e. not in the `File` table, which are tied to components) so files weren't installed but the product was registered. As such, it gets a randomly-generated file name in the Windows Installer cache and will change each time.

**Comment by heaths** [comment]
So you could leave it for ARP, but just use the first icon in the pwsh.exe for the shortcut (i.e. don't author the `@Icon` attribute). If you want that to be the colorful preview one, you'll need to embed that in your EXE. If you want to keep the regular one as the first index, add the colorful one as a separate index, use WiX 3.x, and use the `@IconIndex` attribute as documented here: https://documentation.help/WiX-v3.0/wix_xsd_shortcut.htm

**Comment by heaths** [comment]
If you agree with the change, I can make the change, test it, and submit a PR.

**Comment by iSazonov** [comment]
@heaths Yes, it was a great thing!

**Comment by heaths** [comment]
What I'd like to hear from the team - which would make a change easier - is why the colorful icon isn't the EXE icon. If it were for prereleases, it would be consistent everywhere and this change would be very easy.

**Comment by iSazonov** [comment]
We use one icon (black) for release and second icon (color) for pre-release.

**Comment by heaths** [comment]
Not for pwsh.exe. Seems it's sole icon is the blackish one. At least it still was for RC3. Ideally, you'd want the icon the same everywhere - EXE and MSI (as represented in ARP), either of which should affect the shortcut no matter how authored.

**Comment by iSazonov** [comment]
Perhaps @bergmeister remember details. I think it is moderated by an environment variable assigned in PowerShell script.

**Comment by heaths** [comment]
Yes, I found that, but the icon was not present in RC3's pwsh.exe. I haven't yet poked into the rest of the environment, but given that assume that variable was not used to pack resources into the EXE. It probably should be.

**Comment by iSazonov** [comment]
Please look release version too. I don't see the issue in my local dev builds.

**Comment by heaths** [comment]
The release version is fine. The idea is that if the product team wants the colorful preview version as the icon, it should be everywhere: in the MSI, shortcut, and EXE. Fixing the shortcut is simple if the EXE has the right icon at the right index (first, whether preview or release).

**Comment by heaths** [comment]
My proposal to fix this can be found [here](https://github.com/PowerShell/PowerShell/issues/12011#issuecomment-596105112). There's a few problems leading to this, as well as other ill behaviors and complicated upgrades in the future.
