### ISSUE TITLE
Micrsoft Dynamics AX 2012 R2, Modules cannot be loaded on PS7 rx3

### ISSUE THREAD

**Issue by thenecroscope** [PowerShell/PowerShell#11993]
Hi,

This is quiet a specific issue which is really geared to people using Dynamics AX 2012 R2 only. 

When I try to import the Microsoft Dynamics modules for 2012 R2. Some of the modules loaded ok (there are 3 in total) and some do not. The error I'm getting for Powershell 7 rc 3 is:
Could not load file Microsoft.Dynamics.Ax.Framework.Management

I'm blocked from using Powershell 7 until I can get to the bottom of this. Help! :)

thanks,

**Comment by iSazonov** [comment]
@thenecroscope The module is not in the repo. Please use other channels to communicate to Microsoft Dynamics team like UserVoice site

**Comment by thenecroscope** [comment]
Yup I understand that. I'm just flagging this as my understanding is that PS 7 aims to be backwards compatible with older modules. So it might a possible test case to investigate why this is not working. I was really expecting answer to the question to be honest. Also 2012 R2 is out of support as well, so I think I'm stuck with the issue.

**Comment by iSazonov** [comment]
> PS 7 aims to be backwards compatible with older modules.

Not true for _binary_ modules. You could use WinCompat feature `Import-Module -UseWindowsPowerShell`
See also https://devblogs.microsoft.com/powershell/announcing-powershell-7-0/

**Comment by thenecroscope** [comment]
Ah nice, I wasn't aware of that. Thanks
