### ISSUE TITLE
PSModulePath doesn't use $home, but uses [environment]::getfolderpath("mydocuments")

### ISSUE THREAD

**Issue by simonsabin** [PowerShell/PowerShell#12001]
It appears that env:PSModulePath is being prepended with [environment]::getfolderpath("mydocuments")\WindowsPowershell\Modules rather than $Home\Documents\WindowsPowershell\Modules as described in the docs

# Steps to reproduce
Redirect your mydocuments to a different folder

Start powershell and get the $env:psmodulepath

# Documented behavior

```none
$env:PSModulePath.split(";") -contains "$home\WindowsPowershell\Modules"
```

# Actual behavior

```none
 $env:PSModulePath.split(";") -contains "$([environment]::getfolderpath("mydocuments"))\WindowsPowershell\Modules"
```

**Comment by rjmholt** [comment]
What PowerShell version are you seeing this in?

**Comment by simonsabin** [comment]
All versions

Simon Sabin

________________________________

**Comment by rjmholt** [comment]
> All versions

The path you give in your example seems to be a Windows PowerShell path. This repository tracks issues in PowerShell 6+.

The module path is set here:

https://github.com/PowerShell/PowerShell/blob/20a236b228d024ed23bf12c9331bbbb484e3836c/src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs#L968-L972

It seems that `$HOME` variable comes from the `$env:USERPROFILE`:

https://github.com/PowerShell/PowerShell/blob/a34d0f3e808659b0c07b8fdac83aaae1dae43c21/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L182

It's not clear whether the inconsistency is intended, but given that this behaviour is longstanding and likely unable to be changed, we might want to move this issue to the docs repo.

**Comment by iSazonov** [comment]
I think it is Docs issue.

**Comment by simonsabin** [comment]
Its a fairly broad reaching docs problem. I'll raise a docs issue.

**Comment by rjmholt** [comment]
@joeyaiello or @sdwheeler can you transfer this issue to the docs repo?

**Comment by simonsabin** [comment]
I’ve already created an issue on the docs side. You can close this one

Simon Sabin

________________________________

**Comment by mklement0** [comment]
As an aside, regarding ships that have saild: The more appropriate definition of `$HOME` would be `"${env:HOMEDRIVE}${env:HOMEPATH}"` rather `$env:USERPROFILE` - while the two values are _by default_ identical, they can differ, and the former is then the better location for modules.

Therefore, basing the personal module path on `[environment]::getfolderpath("mydocuments")` is actually more appropriate than basing it on `$HOME`.

**Comment by simonsabin** [comment]
I agree that its appropriate use, its just confusing that its not documented. 
Furthermore the rules for how its set if the user environment variable is set isn't clear in the docs
