### ISSUE TITLE
Missing MSIX Packages from Powershell 7.0 Release

### ISSUE THREAD

**Issue by baget** [PowerShell/PowerShell#12009]
The MSIX Packages are missing from Powershell 7.0 Release

# Steps to reproduce

```
goto https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0
search for msix packages
```

# Expected behavior

```none
having the MSIX package in github release page
```

# Actual behavior

```none
No MSIX packages in github release page
```

# Environment data

```none

```

**Comment by SteveL-MSFT** [comment]
In progress.  We found an issue during the regular release which necessitated a specific fix and rebuild.  No ETA.

**Comment by wbpluto** [comment]
Waiting for MSIX package :) as well as release to the Microsoft Store!

**Comment by Nirmal4G** [comment]
Is #11991 the problem?

**Comment by fredskis** [comment]
> Waiting for MSIX package :) as well as release to the Microsoft Store!

Waiting here too. My poor Surface Pro X is still on v7.0.0-rc.3

**Comment by wenqiangxie** [comment]
How about now? I'm wating here.

**Comment by Nirmal4G** [comment]
@SteveL-MSFT Will 7.0 servicing or the 7.1 LTS have an MSIX package published and eventually be available in the Windows Store?

**Comment by o-l-a-v** [comment]
Ref. the PS community call yesterday, I wanted to add some reasons for you to release 7.0 GA as MSIX as well as in the Microsoft Store (which currently was the only target for a MSIX release for 7.0 GA).

* MSIX App Attach with Windows Virtual Desktop
  * https://docs.microsoft.com/en-us/azure/virtual-desktop/app-attach
  * https://microsoftplatform.blogspot.com/2019/10/msix-app-attach-will-fundamentally.html
* MSIX deployment with Intune (not everyone wants to use Microsoft Store)
   * https://docs.microsoft.com/en-us/windows/msix/desktop/managing-your-msix-deployment-intune

**Comment by therealderrickd** [comment]
Hows is this STILL not resolved?

**Comment by SteveL-MSFT** [comment]
We're still waiting on another team to publish the right cert to sign the msix pkg.  No ETA.

**Comment by darrenjrobinson** [comment]
@SteveL-MSFT when you publish it, can you please also include Hololens as a target platform. 

e.g **TargetDeviceFamily Name="Windows.Holographic"**

**Comment by SteveL-MSFT** [comment]
The 7.1 preview.6 release has been published to the Store.  It was made available for Windows.Holographic but it appears it can't actually start and that's likely due to conhost not being on that device.  I'll unmark Windows.Holographic as a supported device for next update.  Working on publishing 7.0.4 to Store once that is available.
