### ISSUE TITLE
The "PS C:\Users\'username'>" command prompt not showing after 7.0.0 install. [SOLVED]

### ISSUE THREAD

**Issue by sibeov** [PowerShell/PowerShell#12003]
Forgive my ignorance. Just started to learn powershell. 

Just installed v7.0 and suddenly the "PS C:\Users\'username'\>", in lack of propper lingo / word for it, is not showing up at all. Trying to type anything results in a little to known "beep". See attached snippet.

Tried reinstalling v6 but all the same there. Worked flawlessly until a couple of hours ago. And also tried running as admin and restart.

What have I done? I'm assuming I'm the idiot here.

P.S. Edit 04.03.2020 20:43 Powershell 5.x not showing same issue.

![pwsh7notresponding](https://user-images.githubusercontent.com/44866861/75910475-36ea3480-5e4e-11ea-8a0d-86d3710587ba.JPG)

# Steps to reproduce

```
Install Powershell core 7...
```

# Expected behavior

```
Excpected the "PS C:\Users\'username'\>" to appear upon running pwsh.
```

# Actual behavior

``` 
"PS C:\Users\'username'\>" does not appear and trying to type anything results in a "beep" and no respons.
```

# Environment data

```
Not able to provide with $PSVersionTable becaus I cannot type anything.
```

**Comment by anmenaga** [comment]
@sibeov what is the OS? is the hardware where you are running this heavily used by other applications? how long did you wait for the prompt to appear? (on some low-performance ARM hardware I've seen cases where it takes up to a minute)

**Comment by sibeov** [comment]
> @sibeov what is the OS? is the hardware where you are running this heavily used by other applications? how long did you wait for the prompt to appear? (on some low-performance ARM hardware I've seen cases where it takes up to a minute)

Sorry for not posting the specs. Forgott! Here.
![SysSpecs](https://user-images.githubusercontent.com/44866861/75913665-9c8cef80-5e53-11ea-82ee-32f84cbf16a9.JPG)

**Comment by iSazonov** [comment]
Please check environment variables - PATH and PSModulePath.

**Comment by rjmholt** [comment]
@sibeov what does your profile look like? Is it doing anything intensive? Can you instrument it with `Write-Host` commands to see if they get shown?

Some other things to try:

- Restart the machine
- Tell us if you have any antivirus or policy installed that might stop programs from starting
- If all else fails, you might want to get a dump of the process and send that through. Let us know if it comes to that and I can help you with it

**Comment by sibeov** [comment]
> Please check environment variables - PATH and PSModulePath.

@iSazonov In PATH The "...\Program Files\Powershell\7" is listed.

for PSModulePath se attachement.

![psmodulepath](https://user-images.githubusercontent.com/44866861/75916110-fdb6c200-5e57-11ea-847f-89dd6af277ed.JPG)

**Comment by sibeov** [comment]
> @sibeov what does your profile look like? Is it doing anything intensive? Can you instrument it with `Write-Host` commands to see if they get shown?
> 
> Some other things to try:
> 
> * Restart the machine
> * Tell us if you have any antivirus or policy installed that might stop programs from starting
> * If all else fails, you might want to get a dump of the process and send that through. Let us know if it comes to that and I can help you with it

@rjmholt 
- Tried restart. Does not do anything. :/
- Only Windows Defender. Have not changed any policies or similar today.
- How can I send a "process dump"?. Thanks for the help!

**Comment by rjmholt** [comment]
What's in your `$profile`?

If you put `Write-Host "profile run begin"` at the top of your `$profile` and `Write-Host "profile run end"` at the end, do you see either of them run?

**Comment by sibeov** [comment]
HAHAHA! I found the problem. 

I had an variable wich I had forgott to put embrace with "". Commented it out and everything is working like a charm. Was supposed to be a quick way to open the emacs in the terminal.

I am so sorry for wasting all of your time. I feel like crap now. Well I did learn something today at least.

**Comment by rjmholt** [comment]
> I had an variable wich I had forgott to put embrace with "". Commented it out and everything is working like a charm. Was supposed to be a quick way to open the emacs in the terminal.

Can you show us the issue and the fix? PowerShell should not hang at startup like that.

**Comment by sibeov** [comment]
> > I had an variable wich I had forgott to put embrace with "". Commented it out and everything is working like a charm. Was supposed to be a quick way to open the emacs in the terminal.
> 
> Can you show us the issue and the fix? PowerShell should not hang at startup like that.

@rjmholt Of course!

Had this in the $profile:
- $emacsTerminal = C:\GNU-EMACS\emacs-26.3\bin\emacs.exe -nw

- Solution: #$emacsTerminal = C:\GNU-EMACS\emacs-26.3\bin\emacs.exe -nw

Commented it out and now pwsh (not running as admin) is working.

Running as admin produces (see attached image).
![Capture](https://user-images.githubusercontent.com/44866861/75918024-43c15500-5e5b-11ea-9865-77a9492210a4.JPG)

**Comment by rjmholt** [comment]
Ohhhh, so it was starting an interactive program in the profile? If so, that's pretty hard to defend against, yeah

**Comment by sibeov** [comment]
> Ohhhh, so it was starting an interactive program in the profile? If so, that's pretty hard to defend against, yeah

@rjmholt Lesson learnt. Well, one has to start off somewhere right? Thanks for the help everyone. Sorry for wasting your time and thanks for directing me to the profile!

Have a nice day/evening.

**Comment by rjmholt** [comment]
> Sorry for wasting your time and thanks for directing me to the profile!

Not at all! What we're here for and also a learning experience for us

**Comment by sopheapsok2023-cpu** [comment]
yes
