### ISSUE TITLE
Provide a means to get the default module path to ensure installed modules can be imported

### ISSUE THREAD

**Issue by simonsabin** [PowerShell/PowerShell#12015]
Currently the `install-module` cmdlet install modules to a path that might not be in the list of paths in $env:PSModulePath and thus can't be imported by `import-module`

# Options

Potential options. 
Have `import-module` have a SourceScope property that matches the Scope property of install-module and therefore looks in the same place. 

Have a cmdlet to return the default install directory and be able to pass that to import-module

This is attempting to solve the issue where $env:psmodulepath doesn't include the default directory for installing modules. Its very hard to 
* understand why import-module doesn't find the module
* What has set psmodulepath such that import-module doesn't work
* Change import-module to make it find the module you've installed.

Related to https://github.com/PowerShell/PowerShell/issues/12001

**Comment by rjmholt** [comment]
Related to https://github.com/PowerShell/PowerShell/issues/11223
