### ISSUE TITLE
Problem having 6 and 7 co-exist

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#12025]
# Steps to reproduce
Install PowerShell 7 Release following defaults on a system where PowerShell 6 is present

# Expected behavior
6 can remain in place for side by side testing OR be removed  depending on what the user requires

# Actual behavior
6 is removed, and attempting to [re]install  6.2.4 gives an error "there is a newer version installed". 

Suggestions. 
1.  Install should ask before removing a prior version (perhaps only there is a change of major version)
2. Install should not refuse to install an older version (again perhaps only allowing a change of major version). 

# Work round (for windows 10)
Install makes a shadow copy. 
`get-ciminstance Win32_ShadowCopy | ft installDate,DeviceObject` 
Will show a list of shadow copies.  My newest one was number 6, so I copied that to from the command below (n.b. I added a trailing \ to the name) 
`cmd /c mklink /d c:\ShadowCopy "\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\"`

Now I can copy from `C:\ShadowCopy\Program Files\PowerShell\6` to restore 6
Delete C:\ShadowCopy when done.

**Alternatively** download the ZIP version of 6.2.4, unblock and expand into the 6 directory.

**Comment by jgardsentry** [comment]
An alternative workaround is to just download the PS 6 zip and extract it back to `$env:ProgramFiles\PowerShell\6\`.

This is a dupe of [12002](https://github.com/PowerShell/PowerShell/issues/12002) where it is discussed thoroughly.

**Comment by jhoneill** [comment]
My error. I saw @KevinMarquette  mention it on twitter but he seems to have opened the item here rather earlier than I thought so I didn't scroll down far enough to spot it.
