### ISSUE TITLE
Update Azure Cloud Shell to have PowerShell 7 GA.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#12029]
# Summary of the new feature/enhancement

Just an observation, the Azure Cloud Shell, PowerShell needs to be upgraded to the latest version PowerShell 7 GA.

Or, is there a way to do the update my self? 

:)

# Proposed technical implementation details (optional)

**Comment by iSazonov** [comment]
Thgis was announced in https://devblogs.microsoft.com/powershell/announcing-powershell-7-0/

**Comment by MaximoTrinidad** [comment]
I'm still getting PowerShell 7 RC 2.

![AZPOSH_2020-03-05_14-13-17](https://user-images.githubusercontent.com/19892435/76016860-98141580-5eeb-11ea-8f04-d7487892cc14.jpg)

**Comment by MaximoTrinidad** [comment]
Thanks! It has been updated.

:)
