### ISSUE TITLE
Powershell window settings issue

### ISSUE THREAD

**Issue by scriptingstudio** [PowerShell/PowerShell#12024]
"Terminal Tab\Cursor Shape\Vertical Bar" option does not save its setting. After typing just one char it resets to "Use legacy style".
![settings](https://user-images.githubusercontent.com/17237559/75964585-7fe6cb00-5ed8-11ea-97e4-6809247c1e2e.png)

**Comment by jhoneill** [comment]
Is this a variation on the  "Short cut on the start menu which you can't write back to." Known problem (I'm guessing so from the menu title). If you run pwsh rather than launching from the start menu, or move the shortcut from all users to your own items, does the problem go away ?

**Comment by scriptingstudio** [comment]
I am aware of "Short cut on the start menu which you can't write back to."
I created a new shortcut right from `C:\Program Files\PowerShell\7\pwsh.exe` on my desktop but the problem still here.

**Comment by scriptingstudio** [comment]
BTW the same problem happens to Windows Powershell window but cmd.exe window is ok.

**Comment by jhoneill** [comment]
It piqued my curiosity. 
PSReadline is doing it. If I  do remove-module psreadline it goes away.  Interestingly they don't have an option to control it, but they (and other things) do over-ride the console color settings.

**Comment by scriptingstudio** [comment]
Confirm. It is PSReadline.

**Comment by iSazonov** [comment]
> Confirm. It is PSReadline.

Please move the issue in PSReadline repo.

**Comment by scriptingstudio** [comment]
@iSazonov I see no any option to move it as this guide teaches. https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by iSazonov** [comment]
@scriptingstudio I mean you close the issue and open new one in PSReadline repo.
