### ISSUE TITLE
Get-PSSessionConfiguration Fails to find WIndows PowerShell endpoint

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#12030]
Using Get-PSSessionConfiguraition does not find older WIndows PowerShell endpoints. But those endpoints DO exist and can be used:

# Steps to reproduce

```powershell
# Enable Remoting to be sure
Enable-PSRemoting -Force
# Get Endpoints
Get-PSSessionConfiguration | Format-Table Name, PSVersion
Invoke-Command -Computer Localhost -Scriptblock {$PSVersionTable}

```

# Expected behavior

```none
PS C:\foo> Get-PSSessionConfiguration | Format name, psversion

Name                            PSVersion
----                            ---------
microsoft.powershell          5.1
microsoft.powershell.workflow 5.1
microsoft.powershell32        5.1
microsoft.windows.serverma... 3.0
PowerShell.7                    7.0
PowerShell.7-preview            7.0
PowerShell.7.0.0                7.0
PowerShell.7.0.0-daily.20200207 7.0
PowerShell.7.0.0-rc.2           7.0

PS C:\foo> Invoke-Command -Computer Localhost -Scriptblock {$PSVersionTable}

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19569
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

# Actual behavior

```none
PS C:\foo> Get-PSSessionConfiguration | Format-Table Name, Psversion

Name                            PSVersion
----                            ---------
PowerShell.7                    7.0
PowerShell.7-preview            7.0
PowerShell.7.0.0                7.0
PowerShell.7.0.0-daily.20200207 7.0
PowerShell.7.0.0-rc.2           7.0

PS C:\foo> Invoke-Command -Computer Localhost -Scriptblock {$PSVersionTable}

Name                           Value
----                           -----
WSManStackVersion              3.0
BuildVersion                   10.0.19569.1000
SerializationVersion           1.1.0.1
PSEdition                      Desktop
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19569.1000}
CLRVersion                     4.0.30319.42000
PSVersion                      5.1.19569.1000
```

# Environment data

```none

```
So you can enter a session that does not exist. I think this is confusing and is not good user experience. Interestingly, I can see ALL the endpoints from Windows PowerShell 5.1.

**Comment by iSazonov** [comment]
It is dup #11616

**Comment by doctordns** [comment]
Sorry - but #11616 is a different issue.
That bug is around the default end point used., THIS Issue is that the default endpoint is not visible with Get-PSSessionConfiguration

**Comment by iSazonov** [comment]
https://github.com/PowerShell/PowerShell/issues/11616#issuecomment-589159319

**Comment by joeyaiello** [comment]
Reopening given the stance we landed on in [my comment here](https://github.com/PowerShell/PowerShell/issues/11616#issuecomment-594119801).

`Get-PSSessionConfiguration` should return all legitimate WinRM endpoints on the machine. I realize that this directly contradicts our original decision to explicitly hide these endpoints, but we understand now that if PS7 is to truly manage the entirety of a Windows box, it needs to be able to enumerate and configure WPS endpoints as well.

**Comment by joeyaiello** [comment]
@doctordns could you also describe here the issue with running the cmdlet remotely? Does it just not work at all when running it an interactive session and/or Invoke-Command against a WinRM-based PSSession?

**Comment by doctordns** [comment]
@joeyaiello the issue here is that from Pwsh 7 you do not see the Windows PowerShell endpoints. You can still use them. And the commands work (albeit is Windows PowerShell). 

I still think the default endpoint should be the same as the version of PowerShell (eg should be a PS7 endpoint, not a windows PowerShell endpoint), but that's a different issue. I like the idea of adding switches to the installation MSI to enable admins to have it their way at install time.

**Comment by joeyaiello** [comment]
Yeah, I got that part here, but there was also reference in the other issue to the fact that the cmdlet doesn't work over remoting. My question is whether it works at all (only enumerating the PS7 endpoints as is the case on a local machine), or if there's an additional problem blocking its remote usage altogether

**Comment by iSazonov** [comment]
If the cmdlet will show all Windows PowerShell endpoints we should filter out __Workflow__:
```powershell
 Get-PSSessionConfiguration


Name          : microsoft.powershell
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\ИНТЕРАКТИВНЫЕ AccessAllowed, BUILTIN\Администраторы AccessAllowed, BUILTIN\Пользователи
                удаленного управления AccessAllowed

Name          : microsoft.powershell.workflow
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : BUILTIN\Администраторы AccessAllowed, BUILTIN\Пользователи удаленного управления AccessAllowed

Name          : microsoft.powershell32
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT AUTHORITY\ИНТЕРАКТИВНЫЕ AccessAllowed, BUILTIN\Администраторы AccessAllowed, BUILTIN\Пользователи
                удаленного управления AccessAllowed

```

**Comment by doctordns** [comment]
Any progress on this issue?

At a minimum, can we get the ability of Get-PSSessionConfiguration to see down-level endpoints into 7.2?
