### ISSUE TITLE
Install fail on Ubuntu

### ISSUE THREAD

**Issue by ohlssrog** [PowerShell/PowerShell#12034]
# Steps to reproduce
sudo apt --fix-broken install
sudo apt-get install -f
sudo apt autoremove

sudo dpkg -i powershell_7.0.0-1.ubuntu.18.04_amd64.deb

```powershell

```

# Expected behavior

```none

```

# Actual behavior
dpkg: error processing package powershell (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.7-3) ...
Errors were encountered while processing:

The following packages have unmet dependencies:
 powershell : Depends: liblttng-ust0 but it is not installed
              Depends: libssl1.0.0 but it is not installable
              Depends: libicu60 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```none

```

# Environment data

       `:+ssssssssssssssssss+:`           --------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 19.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: All Series 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.3.0-42-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 days, 23 hours, 26 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2362 (dpkg), 16 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.3 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1200, 1920x1080, 1080x1920 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 3.34.3 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Paper 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-4770K (8) @ 3.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 760 
      -+sssssssssssssssssyyyssss+-         Memory: 8588MiB / 15951MiB 

```none

```

**Comment by rjmholt** [comment]
@ohlssrog there's not enough information here to identify what problem you're experiencing. Please update the issue with the details described in the issue template.

**Comment by jtrh** [comment]
The PowerShell build for Ubuntu 18.04 depends on some packages that are not present in Ubuntu 19.10. I know that 19.10 is not an LTS release, and that servers mostly use Ubuntu's LTS releases, but I hope that the PowerShell maintainers can do something to help non-LTS users.

**Comment by jozefizso** [comment]
PowerShell instalation fails on Ubuntu 20.04 (LTS):

```
 sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.0 but it is not installable
              Depends: libicu60 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kilasuit** [comment]
The original issue listed here was unclear though seemed to be targeting the 19.10 version of Ubuntu with a dpkg for the older 18.04 variant which I would not expect to work.

The issue @jozefizso raised (& I fell into) is that Ubuntu 20.04 is not yet supported though this has been requested in #12626

**Comment by rjmholt** [comment]
Closing, with outstanding ask deduplicated to #12626
