### ISSUE TITLE
Operations log for Windows Event Logging

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/PowerShell#12044]
# Steps to reproduce
 
Perform any command in PowerShell 7 console on a Windows machine. You will find that the events are being logged to the PowerShellCore operational log:

![image](https://user-images.githubusercontent.com/11204251/76042906-a24e0800-5f1b-11ea-8707-55d5df872503.png)

# Expected behavior

Log called just PowerShell

# Actual behavior

Log is called PowerShellCore

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
I think it is by-design - it makes no sense to have two logs.

**Comment by vexx32** [comment]
Hmm maybe? Seems like the kind of thing that probably just got left out of the rename party, though. Can you confirm @SteveL-MSFT? 🙂

**Comment by iSazonov** [comment]
> the rename party, though

Looking on `PSVersion 5.1.18362.628` I think it is about Windows PowerShell?
