### ISSUE TITLE
$env:PROCESSOR_ARCHITECTURE incorrectly displaying x86 on AMD64 platform?

### ISSUE THREAD

**Issue by sgaglione** [PowerShell/PowerShell#12045]
# Steps to reproduce

```powershell
$env:PROCESSOR_ARCHITECTURE
```

# Expected behavior

```none
AMD64
```

# Actual behavior

[screenshot of both 5.1 and 7.0]
![image](https://user-images.githubusercontent.com/25793670/76045440-0f1cce80-5f2b-11ea-89fa-496b85b5a8db.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
@sgaglione `PROCESSOR_ARCHITECTURE` reflects the architecture of the process you are in.  Looking at the screenshot, you have installed the 32 bit version of PowerShell 7.

If you're looking for whether the operating system is 64 bit you can use `[Environment]::Is64BitOperatingSystem`.

**Comment by sgaglione** [comment]
good lord; i didn't even know there was such a thing...this day and age.  my bad and i've since installed the x64 version.  so sad on my part.

**Comment by SeeminglyScience** [comment]
@sgaglione No worries, happens to us all 🙂
