### ISSUE TITLE
Back button on "Optional Actions" page of MSI installer returns to "Welcome", not to "Destination Folder"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [PowerShell/PowerShell#12055]
# Steps to reproduce

1. Download [PowerShell-7.0.0-win-x64.msi](https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/PowerShell-7.0.0-win-x64.msi).
2. Double click to open.
3. The "Welcome to the PowerShell 7-x64 Setup Wizard" page opens. Click "Next".
4. The "Destination Folder" page opens. Click "Next".
5. The "Optional Actions" page opens. Click "Back".

# Expected behavior

The "Destination Folder" page opens.

# Actual behavior

The "Welcome to the PowerShell 7-x64 Setup Wizard" page opens.

# Environment data

Windows 10 version 1909.

`$PSVersionTable` is not available when PowerShell has not been installed yet.

**Comment by bergmeister** [comment]
Thanks for reporting and investigating in so much details. Your 2 comments on the 2 PRs above were useful and pointed out that my original implementation was correct but regressed in PR #8846 
As you already pin-pointed the problem, can you submit a PR please?

**Comment by KalleOlaviNiemitalo** [comment]
> As you already pin-pointed the problem, can you submit a PR please?

With the CLA requirement, I think not.

**Comment by bergmeister** [comment]
@KalleOlaviNiemitalo Can you please elaborate what the issue with the CLA requirement is?
I can do a PR as well but we'd want to understand first what exactly is preventing you (or anyone else in the community) from contributing.
