### ISSUE TITLE
ActiveDirectory Module: Piping Get-AdUser into Get-AdUser no longer works

### ISSUE THREAD

**Issue by bderagon** [PowerShell/PowerShell#12053]
In PowerShell 5.1 we were able to do something like:
`$me = Get-AdUser me@me.com`
Then realize we needed a property not normally included...say department, and do:
`$me = $me | Get-AdUser -properties Department`

In PowerShell 7.0, attempting the same produces: 
`Get-ADUser: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.`

# Steps to reproduce

```powershell
$me = Get-AdUser me@me.com
$me | Get-AdUser -properties Department
```

# Expected behavior

```
Department        : Testing
DistinguishedName : CN=ME,OU=Users,OU=ME,OU=CODE,DC=test,DC=com
Enabled           : True
GivenName         : Me
Name              : 310269056
ObjectClass       : user
ObjectGUID        : 7e80aa0f-10db-4d3f-91cd-45eb68e05710
SamAccountName    : 310269056
SID               : S-1-5-21-1058362020-116201650-909353088-15157933
Surname           : Me
UserPrincipalName : me@me.com
```

# Actual behavior

```
Get-ADUser: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
```

# Environment data

```$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by NoMoreFood** [comment]
Possible this is due to implicit remoting.  When you start up a fresh copy of PowerShell and do a `Import-Module ActiveDirectory`, does it give you any warning?  I confirmed I do not see this issue under Windows 10 1909, but I believe they updated the Active Directory module to be directly loadable in Core at some point in semi-annual channel.

**Comment by iSazonov** [comment]
Only latest version of ActiveDirectory module (Windows Server 2019) works with PowerShell 7.0.
