### ISSUE TITLE
7.0 LTS dev and support questions

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#12057]
I opened doc issue https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5549 about 7.0 LTS.
We could discuss this here.

For .Net Core it is simple:
- 3.1 is LTS with EOL in 09/2022
- 3.1.x is servicing patches (no minor updates!)
- next LTS every 2 year

Since PowerShell 7.0 is based on .Net Core 3.1 and this cause questions:
- Will we have only patch servicing like 7.0.x next 3 years?
- If so, what will be the next dev version? 7.1? And it will be released as not LTS? and based on .Net Core 5.0?
- .Net Core team will release LTS versions every 2 year. Do we follow this too? Do we really need so many LTS versions? What will be version numbering? .Net Core 6.0 LTS - PowerShell 7.2.0 or 8.0?
- So we release LTS and non-LTS every 2 year? Or non-LTS every half a year as we did for 6.x? But in the case 7.1 should be on 3.1.
- If servicing release support is 3 months after previous release it conflicts with .Net Core servicing release because support for last one will end before PowerShell support.

/cc @joeyaiello @SteveL-MSFT

**Comment by iSazonov** [comment]
If our principle is to follow .Net Core support policy the simplest thing we can do is say that PowerShell support ends when .Net support ends on which this version of the PowerShell is based.

**Comment by SteveL-MSFT** [comment]
Current plan is to align with .NET releases.  There is currently no intention to move to a version 8.  So 7.1 will be based on .NET 5 and not be LTS.  7.2 would be based on .NET 6 and would be LTS.  PS7 LTS releases are supported for as long as .NET LTS support exists.
