### ISSUE TITLE
Add -ShowProgress to Wait-Job

### ISSUE THREAD

**Issue by craiglandis** [PowerShell/PowerShell#12069]
# Summary of the new feature/enhancement

Add **-ShowProgress** to **Wait-Job** like the 3rd-party module PoshRSJob has with Wait-RSJob -ShowProgress.

With **ForEach-Object -Parallel -AsJob** making it simple to create jobs in PS7+, it would help to also have a simple way to show job progress.

**Comment by JamesWTruher** [comment]
can we be more specific about what progress we're showing? Is this the progress of a specific job or all the outstanding jobs? What would happen if you have `wait-job` with a specific job?
