### ISSUE TITLE
Windows Powershell persistent history

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#12061]
# Summary of the new feature/enhancement

Please add Windows Powershell command history by default, like there is with GNU Bash. It's a pain in the ass to have to remember repetitive commands or write them down in another place.

**Comment by vexx32** [comment]
@superbonaci can you please clarify what you mean with your feature request?

Command history has not changed a great deal since the Windows PowerShell days. You can access command history from `Get-History` or by using the PSReadLine features which scroll though history when using up/down arrow keys (unless you've reconfigured these options).

**Comment by doctordns** [comment]
Up-arrow and down-arrow do a great job with history. And you can view it with Get-History.

**Comment by superbonaci** [comment]
@doctordns I've checked and Up/Down arrow works, which is what I wanted. However Get-History is clean after rebooting computer. @vexx32 I want all history to be preserved by Get-History even after a reboot. Is that clear?

**Comment by ToMakeSense** [comment]
Persisting history is indeed needed, just like `pwd\.bash_history`

**Comment by superbonaci** [comment]
Actually I'm not sure it command history on GNU/Linux depends on Bash itselt, what I know is that it remembers all commands even after a reboot. But no idea if that's up to GNU Bash or the terminal emulator itself.

**Comment by mklement0** [comment]
PowerShell's command history already is persistent, via the included `PSReadLine` module, which stores the persisted history in file `(Get-PSReadLineOption).HistorySavePath`.

If that isn't working for you, your setup must be broken, or perhaps you've deactivated `PSReadLine` intentionally.

**Comment by ToMakeSense** [comment]
@mklement0 The persisted history `(Get-PSReadLineOption).HistorySavePath` does work for both Poweshell[Core] and Windows Powershell console. new skill get!

But, I think, the thing is, the actual path below is too much deep and the designed cmdlet `(Get-PSReadLineOption).HistorySavePath` hide itself too much deep. It's not as obvious and easy to use as `bash`.
> C:\Users\UserName\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt

As you saying `Also note that this repo is for PowerShell [Core], not Windows PowerShell (though the above applies to both editions).` , BTW, I tested Window Poweshell ISE, the path blow is not working. 
> C:\Users\UserName\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\Windows PowerShell ISE Host_history.txt

**Comment by mklement0** [comment]
@ToMakeSense, the Windows PowerShell ISE does not support `PSReadLine` - see https://github.com/PowerShell/PSReadLine/issues/401; it doesn't come with persistent history (the linked issue offers a workaround).

Generally, given that [the ISE is no longer being actively developed](https://docs.microsoft.com/en-us/powershell/scripting/components/ise/introducing-the-windows-powershell-ise#support) and doesn't support PowerShell [Core] at all (only Windows PowerShell), consider moving to [Visual Studio Code](https://code.visualstudio.com/), combined with its [PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell), which supports `PSReadLine` in its integrated console.

> the actual path below is too much deep and the designed cmdlet (Get-PSReadLineOption).HistorySavePath hide itself too much deep.

Just like in Bash, you needn't know where the file that records the persistent history is located - PSReadLine manages that for you.
If you do feel you need to use a custom location, you can do so with `Set-PSReadLineOption -HistorySavePath`.

If you want to examine the history programmatically / interactively, 
* use `Get-History` to examine _the current session_'s history, and 
* `Get-Content (Get-PSReadLineOption).HistorySavePath` to examine the current session's _plus_ the persisted one.

True, direct access to the history file is not as simple as targeting a path such as `~/.bash_history.txt`, but once you know about `Get-PSReadLineOption`, tab completion will assist you in finding the right property name.

Remember that PowerShell has very different roots than POSIX-like shells such as Bash, and PSReadLine was written long before PowerShell became cross-platform, and additionally wasn't even an integral part of PowerShell at first.
Changing the file's location now would be a breaking change, and it is generally challenging to find locations that work consistently across all platforms; the Unix `~/.*` convention for initialization / history files, while technically possible, isn't a great fit for Windows, and PowerShell doesn't use it.

Quick tangent: `[Environment]::GetFolderPath()` provides a limited set of platform-abstracted paths, e.g. `[Environment]::GetFolderPath('ApplicationData')`,  but such calls are cumbersome; #6966 proposes surfacing them in a simpler, more PowerShell-like way.

**Comment by superbonaci** [comment]
> PowerShell's command history already is persistent, via the included `PSReadLine` module, which stores the persisted history in file `(Get-PSReadLineOption).HistorySavePath`.
> 
> If that isn't working for you, your setup must be broken, or perhaps you've deactivated `PSReadLine` intentionally?
> 
> Also note that this repo is for _PowerShell [Core]_, not _Windows PowerShell_ (though the above applies to both editions).

This works thank you, is displays where the text file is located, which contains lots of previous commands in a text file:
```
PS C:\Temp> (Get-PSReadLineOption).HistorySavePath
C:\Users\Myuser\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt
```

**Comment by mklement0** [comment]
Note: The following applies to the _current-session_ history only.
I do agree that seamlessly integrating the persisted history would be helpful.

The current-session part of the history can be shown in a more targeted fashion with `Get-History`, whose built-in alias is `h`, and - similar to Bash's history feature - you can use the `Invoke-History` cmdlet to target a command from the history by id; the built-in alias for `Invoke-History` is `r`, so the equivalent of `!25` is:

```powershell
# Re-invoke the command recorded as history entry 25 (a shown by h / Get-History
r 25
```
You can do the following with tab completion: type a `#` followed by a _substring_ of a previous command line of interest, and pressing <kbd>Tab</kbd> will cycle through and expand all matching history entries _without submitting them yet_, giving you a chance to modify the command line.

For instance, the following would cycle through all commands in the history that contain the substring `date`:

```powershell
PS>#date<tab>
```

----


Only the following technique appears to be integrated with the persisted history already: 

Use the keyboard shortcut for the `ReverseSearchHistory` `PSReadLine` function, which by default is bound to <kbd>Ctrl-r</kbd>:

* Press it, and start typing a substring of interest.
* To jump backward to the next earlier history entry containing the same substring, press the shortcut again.
* Once you find the entry of interest:
  * Either press <kbd>Enter</kbd> to submit it instantly.
  * Or press <kbd>Tab</kbd> to leave search mode, allowing you to modify the command before submitting it.

Run [`Get-PSReadLineKeyHandler`](https://docs.microsoft.com/en-us/powershell/module/psreadline/get-psreadlinekeyhandler) and inspect the "History functions" section for the available functions and their current key binding.

**Comment by superbonaci** [comment]
`Invoke-History` for me just re-runs the last command.

**Comment by steppnav** [comment]
Cmon...ksh, the code for "set -o vi" and "set -o emacs" has been built INTO ksh since forever. The GNU stuff has it out their for free. A bajillion of us have nerves welded in for one or the other. Just get on board, please. Bash, ksh, mksh, tcsh, zsh, dash, and whatever other shells some nitwit is spinning up for the *nix world has great history functionality. Did I mention the code is ALREADY OUT THERE FOR FREE!!!
Cygwin makes Windows bearable.
That there is a cross platform powershell is cool. But every time I see the baroque command lines one executes to do things I ask who can remember (or comfortable type) THAT! Esc-k then hjkl for me, thank you.

**Comment by steppnav** [comment]
> `Invoke-History` for me just re-runs the last command.
> Ok got it, `Invoke-History` or `r` without arguments re-run last command. It's like hitting the up arrow and enter.

Very kshish. Good. I did the "h", which numbers the history lines. Then "r 1" and it ran that line of the displayed history. Good.

**Comment by turowicz** [comment]
How can I create a persistent alias to the `gc (Get-PSReadLineOption).HistorySavePath` command

**Comment by vexx32** [comment]
You can define a function for that, but you'll need to put it in your $profile for it to be persisted to new sessions. You can do that by doing something like the following:

```ps
@"
function Get-PSReadLineHistory {
    [CmdletBinding()]
    [Alias('gph')]
    param()
    Get-Content -Path (Get-PSReadLineOption).HistorySavePath
}
"@ | Add-Content -Path $profile
```

After doing that it will be present in any new PS sessions you create for your current user. To immediately load it into the current session you'll need to use `. $profile` to reload your profile into the current session.

**Comment by doctordns** [comment]
In PowerShell, an alias is only a short cut (accelerator as it were) to a command name. There has been some discussion of changing this, but so far, to achieve what you want requires you to build a function. You can, as @vexx32 suggests, just add the function in ti your Profile.

**Comment by turowicz** [comment]
@doctordns thank you for your reply.

When executing your command, I get the followin error on a brand new installation of PS 7.x:

```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\Me> @"
>> function Get-PSReadLineHistory {
>>     [CmdletBinding()]
>>     [Alias('gph')]
>>     param()
>>     Get-Content -Path (Get-PSReadLineOption).HistorySavePath
>> }
>> "@ | Add-Content -Path $profile
Add-Content:
Line |
   8 |  "@ | Add-Content -Path $profile
     |       ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path 'C:\Users\Me\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'.
```

Seems like it should also create the profile file if one doesn't exist?

**Comment by vexx32** [comment]
Usually it won't complain, but that error indicates the folder path it would usually be placed in doesn't exist either. Run this before that command to create the folder:

```ps1
$profile | Split-Path -Parent | New-Item -ItemType Directory
```

**Comment by turowicz** [comment]
thanks @vexx32 

I get an error like this though

```
PS C:\Users\Me> $profile | Split-Path -Parent | New-Item -ItemType Directory
New-Item: The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  Path
```

**Comment by vexx32** [comment]
That's what I get for trying to be clever off-the-cuff. This'll work:

```ps1
$profile | Split-Path -Parent | New-Item -Path { $_ } -ItemType Directory
```

**Comment by turowicz** [comment]
Thanks @vexx32 and @doctordns! It all works!

**Comment by Slion** [comment]
So basically use PowerShell through Visual Studio PowerShell extension and you get persistent command line history for free.

**Comment by doctordns** [comment]
You also get this persistent command line history via the console too. This is a nice feature of PSReadline.

It looks like the history for VS Code is separate to that for the PowerShell 7 Console.

**Comment by Slion** [comment]
> You also get this persistent command line history via the console too.

Indeed, edited my post above.

**Comment by picnicsecurity** [comment]
I am sure there is a better way to do this but for me it works fine. It is also not 100% perfect since I don't have a lot of time I can spend on this. For example, I can't get Format-Table to output multiple lines per column (Out-GridView does a better job). I am just sharing in it hopes that it helps out whomever stumbles across this thread next.

```
function Format-PSReadLineHistory {
    $historyList = [System.Collections.ArrayList]::new()
    $history = $(Get-Content (Get-PSReadLineOption).HistorySavePath)
    $i = 0
    while( $i -lt $($history.Length - 1) ){
        # If it ends in a backtic then the command continues onto the next line
        if( $history[$i] -match "``$" ){
            $commands = [System.Collections.ArrayList]::new()
            $commands.Add($history[$i].Replace('`','')) | Out-Null
            $i++
            while($history[$i] -match "``$"){
                $commands.Add($history[$i].Replace('`','')) | Out-Null 
                $i++       
            }
            $commands.Add($history[$i].Replace('`','')) | Out-Null
            $i++
            # Now we join it all together with newline characters
            $command = $commands -join "`n"
            $historyList.Add([pscustomobject]@{
		        Number = $i + 1
                Command = $command
	        }) | Out-Null
        } else {
            $historyList.Add([pscustomobject]@{
		        Number = $i + 1
                Command = $history[$i]
	        }) | Out-Null
            $i++  
        }                           
    }
    return $historyList
} 

function Get-PSReadLineHistory {
    [CmdletBinding()]
    [Alias('gph')]
    param()
    Format-PSReadLineHistory | Format-Table -HideTableHeaders -AutoSize
}

function Find-PSReadLineHistory {
    [CmdletBinding()]
    [Alias('fph')]
    param([parameter(Position=0)]$keyword)
    Format-PSReadLineHistory | Where-Object { $($_.Command.Replace('`n','; ')) -match $keyword } | Format-Table -HideTableHeaders -AutoSize 
}
```

This will format `(Get-PSReadLineOption).HistorySavePath` so that the multiline commands (like when you paste in a function) appear as a single function. It will then allow you to search across your history. You can do something like `Select -Expand Command` once you find what you are looking for and itll display the whole command.

**Comment by Slion** [comment]
> I am sure there is a better way to do this

The better way is not to use deprecated ISE. Command history is persisted by default in the latest PowerShell.

**Comment by picnicsecurity** [comment]
I am not doing it in ISE. I switched to VSCode awhile ago. Still getting use to it but its nice.
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.1110
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1110
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Windows\system32> history

  Id CommandLine
  -- -----------
   1 $PSVersionTable
```
I was doing it straight from the powershell console. While the up arrow works just fine, when you type in history into the powershell console you will only see the history for the current session. What I wrote above was a way to change that so that it instead shows all of your history
