### ISSUE TITLE
Get-ClipBoard does not always return a value

### ISSUE THREAD

**Issue by 7cc** [PowerShell/PowerShell#12066]
`Get-Clipboard` just after `Set-Clipboard` sometimes fails to return a value

# Steps to reproduce

```powershell
1..200 | % {
  Set-Clipboard $_
  $i = Get-Clipboard
  if ( $i -eq "" ) {
    echo $_
  }
}
```

# Expected behavior

outputs nothing

```none
```

# Actual behavior

```none
42
48
80
104
131
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 7cc** [comment]
works fine with `Start-Sleep` after `Set-Clipboard`

```powershell
1..200 | % {
  Set-Clipboard $_
  Start-Sleep -Milliseconds 1
  $i = Get-Clipboard
  if ( $i -eq "" ) {
    echo $_
  }
}
```

outputs nothing

**Comment by doctordns** [comment]
I tried this here too - ran it 100 times - can not replicate.

**Comment by NoMoreFood** [comment]
I am able to reproduce this under Windows 10 1909 but not nearly as frequently as you.  Also see it under Windows PowerShell 5.1.  I upped your `1..200` to `1..100000` and I see about 25 failures.  Can you try doing the same @doctordns?

**Comment by iSazonov** [comment]
It is by-design. The code is thread-sensitive. I do not think that we want to add waiting another thread and delay the Set-Clipboard cmdlet.

**Comment by iSazonov** [comment]
Doc issue https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5896
