### ISSUE TITLE
Invoke-WebRequest and Invoke-RestMethod should support Unix Domain Sockets

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#12060]
# Summary of the new feature/enhancement

`curl` has the parameter `--unix-socket` which is super useful when dealing with those services which use them (like Docker). for example:
 
`curl --unix-socket /var/run/docker.sock http://v1.40/images/json| convertfrom-json`

It seems that our webrequest and restmethods should support this.

# Proposed technical implementation details (optional)

One possible approach would be to allow the uri property to encode the path to the socket
It seems like the cmdlets have enough parameter sets, but adding parameter sets for this might also be reasonable.

**Comment by CarloToso** [comment]
I tried to implement this in #18995 but I need some testers

**Comment by CarloToso** [comment]
Previously discussed in https://github.com/PowerShell/PowerShell/issues/8314
