### ISSUE TITLE
Release notes wording ("for not" → "for now")

### ISSUE THREAD

**Issue by ForNeVeR** [PowerShell/PowerShell#12068]
Currently, [the release notes for 7.0.0](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0) say (emphasis is mine):
> Note: The snap package is segfault after launching on Ubuntu 16.04. We are investigating with the .NET team. The workaround **for not** is to use the DEB or tar.gz package.

I guess it should say "for now" instead of "for not".

Sorry for creating an issue, but I wasn't able to quickly found a more appropriate channel to report this kind of issue.

**Comment by sdwheeler** [comment]
I don't have rights to edit a release. @TravisEz13
