### ISSUE TITLE
Code completion does not complete when function is defined within the script

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShell/PowerShell#12079]
When a function is defined within a script, code completion for this function won't work for some scenarios. 

This painfully surfaces in editors such as *ISE* and *VSCode*: when working on code in one editor pane, intellisense stops working inside of this editor pane.

It does work on other editor panes. However, when a typical script author works on a solution with more than one function and tries to reference one of these functions from other places *in the same script*, Intellisense is broken.

# Steps to Reproduce

## Example 1: Complete Corruption of Parameter Completion
When a function parameter uses PS-defined enums, all function parameters become invisible:
**Actual Behavior**
```powershell
$script1 = '
enum Cities
  {
    Hannover
    Redmond
    NewYork
  }

  function Test-It
  {
    param
    (
      [Cities]
      $City
    )

    $PSBoundParameters
  }
  
  Test-It -'

TabExpansion2 -inputScript $script1 -cursorColumn $script1.Length | select -ExpandProperty CompletionMatches
```
*Result: none*

### Expected Behavior
To simulate the *expected* behavior, simply remove the enum from the code and place it into a parent scope:

```powershell
enum Cities
  {
    Hannover
    Redmond
    NewYork
  }
  
$script1 = '
  function Test-It
  {
    param
    (
      [Cities]
      $City
    )

    $PSBoundParameters
  }
  
  Test-It -'

TabExpansion2 -inputScript $script1 -cursorColumn $script1.Length | select -ExpandProperty CompletionMatches

```
*Result: Completion Match for parameter **-City***

## Example 2: Corruption of Argument Completion
When a function parameter uses the attribute [ArgumentCompleter()], the argument completion fails if the function is defined in the same script:
**Actual Behavior**
```powershell
$script = '
  function Test-It
  {
    param
    (
      [ArgumentCompleter({"Hannover","Redmond","NewYork"})]
      $City
    )

    $PSBoundParameters
  }

Test-It -City '

TabExpansion2 -inputScript $script -cursorColumn $script.Length | select -ExpandProperty CompletionMatches  
```
*Result: default path completion*

### Expected Behavior
To simulate the *expected* behavior, place the function definition into the parent scope:

```powershell
function Test-It
  {
    param
    (
      [ArgumentCompleter({"Hannover","Redmond","NewYork"})]
      $City
    )

    $PSBoundParameters
  }
  
$script = 'Test-It -City '

TabExpansion2 -inputScript $script -cursorColumn $script.Length | select -ExpandProperty CompletionMatches
```
*Result: Completion Matches for the three cities defined by the attribute*

Note: `Register-ArgumentCompleter` is unaffected by this issue because the associated scriptblocks are defined outside the current scope.
# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SteveL-MSFT** [comment]
I tried example 1 in WinPS 5.1 and it also fails.  I thought this might have been a regression, but it appears that has never worked?

**Comment by TobiasPSP** [comment]
It in fact seems to be a bug carried over from the old code base. It actually surfaced in VSCode where it messes up IntelliSense but is present in ISE as well.

It is surfacing with a delay probably because it is triggered by techniques that only recently became increasingly popular and were newly added in WPS 5.
