### ISSUE TITLE
Feature Request - Support pst1 as a file type explictly for tests

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#12071]
# Summary of the new feature/enhancement

Add engine support for pst1 file types that are explicitly for tests removing the need for `file.tests.ps1` & would make it `file.pst1` which I think would be neater and cleaner overall.

# Proposed technical implementation details (optional)

Engine supports pst1 files as per https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11221107-add-pst1-file-extentsion-to-better-support-pester

& per https://github.com/pester/Pester/issues/444

**Comment by WSLUser** [comment]
I think this should be backported to 5.1 but not earlier versions once implemented. This will allow easier transition to upgrade from Windows Powershell to Powershell Core.
