### ISSUE TITLE
[Feature Request] Check-box selection for `Out-GridView`

### ISSUE THREAD

**Issue by GeeLaw** [PowerShell/PowerShell#12074]
# Summary of the new feature/enhancement

When using `Out-GridView -PassThru`, the user might want to select multiple items. Currently, the user can add a range to selection by holding Shift, and add a particular item to selection by holding Ctrl. It would be much better if the user can do this more easily, without holding a key.

<img width="462" alt="Screen Shot 2020-03-07 at 6 27 35 PM" src="https://user-images.githubusercontent.com/4462444/76155496-7d839d00-60a1-11ea-8121-64d4f256ce42.png">

Windows File Explorer provides check-box selection. `Out-GridView` can implement this, too.

![Capture](https://user-images.githubusercontent.com/4462444/76155548-45308e80-60a2-11ea-9155-36070c728200.PNG)

**Comment by iSazonov** [comment]
The code was added to PowerShell 7 from Windows PowerShell for backward compatibility only and it is frozen. https://github.com/PowerShell/GraphicalTools is for future

**Comment by vexx32** [comment]
Same here @GeeLaw; if this is about the linked GraphicalTools module, please go ahead and open this issue there as well. 😊
