### ISSUE TITLE
Window resize when run any command

### ISSUE THREAD

**Issue by wasphin** [PowerShell/PowerShell#12072]
# Steps to reproduce

1. Set terminal font to `Lucida Console` with size 14;
2. Run any command will cause the terminal window resize.

# Expected behavior

Terminal output normally without window size changing.

# Actual behavior

Window resize narrow and wide.

# Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Do you use Windows Terminal?
Can you repo without PSReadline module?

**Comment by wasphin** [comment]
Hi @iSazonov, I use the default terminal(``pwsh.exe``) installed with PS.
The terminal doesn't resize after ``Remove-Module PSReadLine``, it cannot even change the font.

**Comment by daxian-dbw** [comment]
what's the default font of the console for your operating system?
This is very likely a duplicate of https://github.com/PowerShell/PSReadLine/issues/964 (see the `the codepage` section).

**Comment by wasphin** [comment]
Cannot reproduce this after unchecking the ``Unicode UTF-8`` option in the language settings.

**Comment by daxian-dbw** [comment]
@wasphin Can you please clarify what language setting?

> The terminal doesn't resize after `Remove-Module` PSReadLine, it cannot even change the font.

This observation make it more obvious that this is a duplicate of PowerShell/PSReadLine#964.
For details, see [this comment](https://github.com/PowerShell/PSReadLine/issues/964#issuecomment-570744871)

**Comment by wasphin** [comment]
I unchecked this option:
![image](https://user-images.githubusercontent.com/1237906/77141749-e8c56a00-6ab8-11ea-914b-1e9c3c347f0e.png)

The font is now ``点阵字体``, I haven't use ``pwsh`` for a time, this may not the initial default font.
The ``Lucida Console`` font does not show in the terminal property page. It likely the same as you said in that comment.

And the code page is 936, a Chinese Simplified OS.

**Comment by daxian-dbw** [comment]
Thanks for the clarification on the Language setting part and the additional information.
I will resolve this issue as a duplication.
