### ISSUE TITLE
[Bug] Files with Backslash in name

### ISSUE THREAD

**Issue by cnibbler** [PowerShell/PowerShell#12085]
Mac OS X 10.13.6.
Powershell v7 latest version and just installed.

File name is back\slash.txt
And is the only file stored in /Somewhere/Folder

`dir /Somewhere/Folder` results in:
`    Directory: /Somewhere/Folder/back`
` `
`Mode    LastWriteTime Length Name`
`----    ------------- ------ ----`
`----- 08/03/2020 18:37 123456 back\slash.txt`

I've then found `$_.PsParentPath` is:
`Microsoft.Powershell.Core\FileSystem::/Somewhere/Folder/back`
Although `$_.FullName` and `$_.Name` are correct.

I then found that `$_.FullName | Split-Path -Parent` results in:
`/Somewhere/Folder/back`

Should be quite easy to replicate for anyone else.

**Comment by cnibbler** [comment]
Also found that `Test-Path $_.FullName` returns False and `Rename-Item $_.FullName -NewName 'nobackslash.txt'` fails stating the file doesn't exist when it definitely does and this is proved when running `ls -l $_.FullName`

**Comment by mklement0** [comment]
Yes, the non-support for `\` in file names on Unix is unfortunate, but to quote from

From the PS committee decision at https://github.com/PowerShell/PowerShell/issues/9244:
> Filesystem accepting both / and \ on all systems is an explicit cross platform experience decision for PowerShell.

See #9244

**Comment by cnibbler** [comment]
Ahhh, my bad.

Thanks for the answer and sorry for the dupe.
