### ISSUE TITLE
regex '\P{IsBasicLatin}' (non-ascii) matches the letter 'i'

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#12082]
I was looking for a regex to match non-ascii characters (not within 0-127), and found an expression here:  https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions .  But weirdly capital and small letter 'i' match as non-ascii.  "\P" means "not".

# Steps to reproduce

```powershell
'i' -match '\P{IsBasicLatin}'
'I' -match '\P{IsBasicLatin}'
```

# Expected behavior

```none
False
False
```

# Actual behavior

```none
True
True
```
No other ascii character matches.

```powershell
0..127 | foreach { if ([char]$_ -match '\P{IsBasicLatin}') { [char]$_ } }
I
i
```

A workaround is to use -cmatch:

```powershell
'i' -cmatch '\P{IsBasicLatin}'
False
```
Ah, 'i' matches some some Turkish character (0x130) without case sensitivity.  There's a little dot over the capital I.

```
'i' -match 'İ'
True
```
Also, Kelvin K matches as ascii when case is ignored:

```powershell
[char]0x212a | select-string '\p{IsBasicLatin}'

K
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This will be dependent on system culture settings and whether you use case sensitive or insensitive matching. Also, any perceived or actual discrepancies there are entirely down to how the regex processor in .NET Core is handling it. While we can document such discrepancies, we cannot fix them here; if we need them fixed or there are corrections to be made, we'll need to file issues in the dotnet/runtime repo. 🙂

**Comment by jszabo98** [comment]
The culture is irrelevant.  My culture is en-US, and somehow the Turkish `İ` gets conflated with small i and capital I when case is ignored.  I'm not sure what culture the kelvin sign `K` is.  I posted a little about it on stackoverflow:  https://stackoverflow.com/questions/30805741/match-high-ascii-characters-but-not-the-letter-i/60590324#60590324

**Comment by jszabo98** [comment]
It's funny how this kind of thing happens even outside .net.  Maybe I should make a ticket with the unicode consortium.

```
echo i | findstr /i İ
i
```

**Comment by tenatus** [comment]
It is a bug that \P{IsBasicLatin} != [^\p{IsBasicLatin}] in powershell. E.g., this command will remove all i's [bug]:
`(get-content 'c:\file.txt') -replace '\P{IsBasicLatin}', ''`
while this won't [correct]:
`(get-content 'c:\file.txt') -replace '[^\p{IsBasicLatin}]', ''`
