### ISSUE TITLE
add new member to array

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12084]
```
PS C:\> $a = 5,7,100,44,1,3
PS C:\> $a.min()
1
PS C:\> $a.min(2)
3
PS C:\> $a.max()
100
PS C:\> $a.max(3)
7
```

index in this example begin with 1 and not zero

in case of array string[] min and max return les longest and smallest string

**Comment by mklement0** [comment]
If proper support for LINQ is ever implemented, we should get this for free - see #2226

In the meantime, there's this (somewhat cumbersome):

```powershell
[int[]] $a = 5,7,100,44,1,3 
[Linq.Enumerable]::Min($a) # Note: input array must have specific numeric type

[Linq.Enumerable]::Max($a) 
```
