### ISSUE TITLE
Connect-ExoPSSession Error

### ISSUE THREAD

**Issue by scottclarke1** [PowerShell/PowerShell#12093]
When running the Connect-ExoPSSession cmdlet to connect to Exchange Online with MFA enabled, the following error is returned;

Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=<redacted>'.

**Comment by iSazonov** [comment]
@scottclarke1 The repo is for PowerShell dev only. Please use other channels to report the issue.

I guess EXO is not PowerShell Core compatible.
