### ISSUE TITLE
Get-Help Add-Computer Reveals help for Select-XML

### ISSUE THREAD

**Issue by teskemj** [PowerShell/PowerShell#12097]
# Steps to reproduce

```powershell
get-help add-computer
get-help add-computer -examples
```

# Expected behavior

```none
Help output for add-computer
Examples for add-computer
```

# Actual behavior

```none
Updates help each time and returns select-xml help
Examples for select-xml
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
@teskemj 

Knowing that this cmdlet is a Windows PowerShell cmdlet and not PowerShell 7.

To get the help to work. I need to use the following command to run it in PowerShell 7:

```
Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell
```
Then, when doing the Get-Help Add-Computer there is recurring behavior that running the Update-Help every time the Get-Help Add-Computer runs. (see image)

![UpdateHelp_2020-03-10_17-03-52](https://user-images.githubusercontent.com/19892435/76359361-7a7eeb80-62f1-11ea-89ad-cafb228bf068.png)

I don't think it is the Add-Computer cmdlet causing the problem, but doing the Get-Help on a Windows PowerShell cmdlet.

Definitely! It need to be investigated.

**Comment by MaximoTrinidad** [comment]
It seems there is a conflict between core modules: PS7 vs. Windows PowerShell

```
PS C:\Users\max_t> Get-Module -L Microsoft.PowerShell.Management                                                                                                                                                                                                                                                                                                            Directory: C:\program files\powershell\7\Modules                                                                                                                                                                                            ModuleType Version    PreRelease Name                                PSEdition ExportedCommands                         ---------- -------    ---------- ----                                --------- ----------------                         Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Get-Clipbo…                                                                                                                             Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules                                                                                                                                                                               ModuleType Version    PreRelease Name                                PSEdition ExportedCommands                         ---------- -------    ---------- ----                                --------- ----------------                         Manifest   3.1.0.0               Microsoft.PowerShell.Management     Core,Desk {Add-Content, Clear-Content, Clear-Item…                                                                                                                         PS C:\Users\max_t> 
```

It can't find it the Add-Computer help files and is returning something else. And, it doesn't even work if you use the following command:

```
Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell                                                                                                             
```

![UpdateHelp0_2020-03-10_17-03-52](https://user-images.githubusercontent.com/19892435/76360421-5b815900-62f3-11ea-822e-fe6b9beff778.png)

Something is going on!
:)

**Comment by teskemj** [comment]
Cool...I was just poking around between Windows Powershell and 7 as I'm onboarding systems and wanted to test out 7.

**Comment by doctordns** [comment]
I am using PowerShell 7.0 as released in Windows 10. These work here OK:

![2020-03-11_10-47-28](https://user-images.githubusercontent.com/3630329/76409261-0d696580-6386-11ea-9096-f66e98b27682.png)

**Comment by teskemj** [comment]
The command executes, but look at the help displays the help for _select-XML_ :)

**Comment by MaximoTrinidad** [comment]
@doctordns 

This happens to me in the beginning, then I realized that the help for Add-Computer is not equal to the Select-XML help. Unless I'm missing something.

In my case, I got PowerShell 7 install in of my environments (Physical and VM's) and the Add-Computer cmdlet is not available at first. You said that works! Hum!

![AddComp_01_2020-03-11_10-02-51](https://user-images.githubusercontent.com/19892435/76425506-1b1bec80-6380-11ea-9b8b-9efc1f2924a0.png)

I wonder! How did you install PowerShell 7? I use the "PowerShell-7.0.0-win-x64.msi".
:)

**Comment by doctordns** [comment]
Update-Help??

**Comment by doctordns** [comment]
OK - so I tried this on a newly created DC:

![2020-03-11_17-54-21](https://user-images.githubusercontent.com/3630329/76448177-d618aa00-63c1-11ea-83d0-1f602402b7e7.png)

ANd if I update the help , the examples reutrn

NO Idea why the earlier command worked like that!!!

**Comment by MaximoTrinidad** [comment]
@doctordns 

Yes! It works in Windows PowerShell but not in PowerShell 7.0.

![AddComp_02_2020-03-11_14-04-31](https://user-images.githubusercontent.com/19892435/76449404-6941e780-63a2-11ea-9334-0552ea60ab7c.png)

It's possible there's a conflict of modules that the Get-Help can't resolve.

![AddComp_03_2020-03-11_14-04-31](https://user-images.githubusercontent.com/19892435/76449431-7363e600-63a2-11ea-819a-57dba78bf3b4.png)

:)

**Comment by SteveL-MSFT** [comment]
I believe this is a side effect of https://github.com/PowerShell/PowerShell/issues/11419.  Going through the code, `Get-Help` initiates command discovery and finds this command in the Windows PowerShell Management module, so uses that index into the PS7 Management module help which shows the wrong content.

**Comment by anmenaga** [comment]
Can somebody with the repro please try it on the latest daily build? Thank you.

To install the latest daily build:
`Invoke-Expression "& { $(Invoke-RestMethod 'https://aka.ms/install-powershell.ps1') } -daily"`


```
PS C:\> $psversiontable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      0      daily.20200322

PS C:\> get-help add-computer

NAME
    Add-Computer

SYNTAX
    Add-Computer [-DomainName] <string> -Credential <pscredential> [-ComputerName
    <string[]>] [-LocalCredential <pscredential>] [-UnjoinDomainCredential
```

**Comment by MaximoTrinidad** [comment]
@anmenaga 

At least I'm not getting the Help Select-Xml now.

![Add-Computer_2020-03-23_19-48-58](https://user-images.githubusercontent.com/19892435/77373776-7d40fe00-6d3f-11ea-9bb7-14a06f86d7b8.png)

**Comment by MaximoTrinidad** [comment]
@anmenaga 

Ah! No luck!

I just did an Update-Help -Force and the issue came back.
Sorry!

![Add-Computer2_2020-03-23_19-48-58](https://user-images.githubusercontent.com/19892435/77374182-6b138f80-6d40-11ea-8c99-35a4f7c2ea83.png)

**Comment by joeyaiello** [comment]
Just did a little investigation: it looks like this is a symptom of the fact that you can't run `Add-Computer` from 7.x due to it existing in the `system32`/WinPS instance of `MS.PS.Management`. @anmenaga kinda fixed this where "first one wins" with cmdlets like `ConvertFrom-String` in `MS.PS.Utility`, but I suspect that because `MS.PS.Mgmt` is being loaded at startup time, you can never load the one `system32` one that has Add-Computer. 

@teskemj (or anyone else in the thread): are you able to actually run `Add-Computer` at all from 7.x? I cannot, hence my conclusion above. 

If that's the case, we should rename this to "Add-Computer won't run from WinPS Microsoft.PowerShell.Management"

**Comment by MaximoTrinidad** [comment]
This might answer your question.

![cmdletIssue_01_2020-08-20_14-51-59](https://user-images.githubusercontent.com/19892435/90812969-e9c32780-e2f4-11ea-936c-6f1e37ab10a9.jpg)

Definitely it should be tagged! This cmdlet won't work in PS7.

**Comment by joeyaiello** [comment]
I verified that this is working now in 7.1.0. If it's still failing for you on 7.1 or newer, please file a new issue.
