### ISSUE TITLE
To connect to SharePoint Online with Powershell 7 

### ISSUE THREAD

**Issue by 7Shubhamb** [PowerShell/PowerShell#12108]
I am not able to connect to SharePoint Online Site collection with Powreshell 7.I am getting below error -The remote server returned an error: (400) Bad Request.

Add-Type -Path "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.dll"
Add-Type -Path "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.Runtime.dll"
$userName = "***"
$password = ConvertTo-SecureString "" -AsPlainText -Force
$webURL="https://test.sharepoint.com/sites/test/"
$Context=New-Object Microsoft.SharePoint.Client.ClientContext($webURL)
$Context.Credentials=New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($username,$password)
$Web=$context.Web
$Context.Load($web)
$Context.executeQuery()
Write-host $Web.URL

**Comment by iSazonov** [comment]
I guess the Sharepoint  module is not compatible with PowerShell Core. Please use other channels to report the issue like UserVoice.

**Comment by AspenForester** [comment]
I'm currently able to import the 'Microsoft.Online.SharePoint.PowerShell' on a windows machine in PS7 using the -UseWindowsPowerShell switch.
