### ISSUE TITLE
Progress bar in Copy-Item

### ISSUE THREAD

**Issue by manigandan-jegannathan-developer** [PowerShell/PowerShell#12110]
It would be great to have something in CLI which can indicate the progress of item being copied

**Comment by iSazonov** [comment]
To do this in consistence way we should enumerate all items before coping. A problem is there is a some levels for path expansion. Thus, there is no single point where we could inject this progress code. This will require deep refactoring providers.

**Comment by AspenForester** [comment]
I'd prefer to skip the progress instead of delaying the actual progress of the copy operation with painting stuff on the screen.

**Comment by iSazonov** [comment]
Yes, most of reports say that users are concerned a performance of file operations.
I hope we will have some improvements in the area in next milestone.

Also we use .Net Core API for file operations. The API does not support a progress. See 
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CopyFile.cs#L16
So you could ask .Net Core team to add the support. I believe it is more right way.

**Comment by FallenGameR** [comment]
>Also we use .Net Core API for file operations. The API does not support a progress. 
The most common case of file copy is lots of files. Even if AP doesn't let you see progress on one particular file you can show progress on file batch overall - total number of files and their total byte size.
