### ISSUE TITLE
will you make it "efi" compatible ?

### ISSUE THREAD

**Issue by sixcentgeorge** [PowerShell/PowerShell#12127]
# Summary of the new feature/enhancement
i try to contact you .. but i found no email 

# Proposed technical implementation details (optional)

i first found a tool you made : Half Life Game Level Viewer
https://www.codeproject.com/Articles/32751/Half-Life-Game-Level-Viewer

because i search someone able to create the dlls for my mod .
i want something close to the opposing force one with few changes in monsters and entities .
i have it really hard to find somebody able to do it.. you seem to have all the qualities .. you know well the game and already done some programming .
beside searching somebody like you, i collect source code that i want in the game .
there are few projects here but a majority of them are made by scammers.. 

i am ready to pay a correct amount for this job.. beside i think valve should do these kind of product for less than $10 or at least $100 per demand .

i also find your powershell very interesting.. i mean i dream to make my game playable at the efi prompt with a lan support...
are you feeling able to do that "later" ?
is your powershell able to replace the cmd.exe ?
i liked a lot the dos time and the fact it was showing the use of memory...with NT there is no more memory manages...like qemm386.sys .. 
my gmail is grml4d i wait your answer for the job
have a nice day Paul

**Comment by doctordns** [comment]
PowerShell is, in effect, a great replacement for CMD.EXE in Windows. 

Regarding memory management, Windows does this internally. No need for a 3rd party add-on. You can use PowerShell to retrieve memory counters (either Get-Counter or using WMI)

Finally, the project you refer to is nothing to do with PowerShell.

I suspect this report can be closed.

**Comment by sixcentgeorge** [comment]
i made this issue because i was thinking this project was "not popular" 
i try to contact :  Paul Higinbotham aka : https://github.com/PaulHigin
thank you to send this message for me
