### ISSUE TITLE
Powershell 7.0.0 installer does not add the context menu

### ISSUE THREAD

**Issue by shogerr** [PowerShell/PowerShell#12121]
The newest installer does not properly add the right click context menu entry for powershell core.

It still links back to 5.1

Furthmore, MS has made it potentially impossible to modify this shortcut..
```
 PS > Set-Itemproperty "HKLM:\SOFTWARE\Classes\Directory\shell\powershell" -Name command -Value "powershell.exe -noexit -command Set-Location -literalPath '%V'"
Set-Itemproperty : Requested registry access is not allowed.
Set-ItemProperty : A positional parameter cannot be found that accepts argument 'access'.
At line:1 char:1
+ Set-Itemproperty : Requested registry access is not allowed.
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ItemProperty], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand
```
Ran from an Adminstrator's context. Gee MS, I thought I had control over my machine. Turns out I need to go to Github to ask your permission to modify my machine. 

**Solution**
1. Open registry as an admin
2. Find  HKLM:\SOFTWARE\Classes\Directory\shell\powershell" <- it's actually going to be class root, you'll find it, I believe in you.
3. Right click 'Permissions'
4. Go to advanced
5. Make yourself the owner of the registry key
6. Modify the command property

Don't even bother to try and do this via a command line. MS of course makes it impossible to be efficient here.

Furthermore, when will be able to modify the 'win+x' menu to use core? The core product will never be picked up until the 5.1 desktop is destroyed from being accessible on machines. You'll see all this work go into the garbage over time. Pretty much we're all stuck at 5.1 until MS fixes these accessibility issues. If you think that supporting compatibility like this is a good idea, consider that what MS has done with PS is so absolutely confusing to end users, most senior programmers will use CMD all day every day, and don't even consider PS.

**Comment by AspenForester** [comment]
Are these really PowerShell issues or Windows issues?  Maybe submit this via Windows Feedback Hub, too?

**Comment by shogerr** [comment]
Uh... I would think it's a powershell issue. I would think you would want your installer to actually add the context menu as the user is requesting.

If I click "install context menu" in your team's software product's installer, I would expect you would be concerned that the context menu isn't being put in place.

How long until we get AI chat bots telling us that the issue has been closed as a "non-bug", or that these issues need more votes before a human looks at them? Lazy ass buck passing MS employees.

**Comment by shogerr** [comment]
Nm, I forget what a joke it is to work with MS products. I will forever love the great open source swindle that MS pulled to get a bunch of niave programmers to work for free on their projects, which have the most destructive license I've ever seen.

Closing issue, because ethically, none of use should be helping you for free.

**Comment by AspenForester** [comment]
How astonishingly rude. They may just be nameless, faceless "Microsoft
employees" to you, but the members of the PowerShell team are my friends,
and this sort of behavior is unacceptable.

**Comment by shogerr** [comment]
You act like history doesn't follow a individual, ie Microsoft. No one has forced you or your peers to work for a company that has a reputation like Microsoft. Removing posted issues to these trackers.
