### ISSUE TITLE
macOS Installer doesn't have notarization ticket stapled

### ISSUE THREAD

**Issue by built2order** [PowerShell/PowerShell#12139]
# Steps to reproduce

```
Assumptions:
* user is running macOS Catalina 10.15.3
* user doesn't have full internet connectivity

1. Download macOS based pkg installer
2. Enable firewall or remove network connectivity
3. Execute installer

The issue shown is that the underlying installer doesn't have the notizition ticket stapled to the installer.

```

# Expected behavior

```
The installer should prompt the user through various steps to install the underlying framework.
```

# Actual behavior

```
The user is prompted with a dialog box with the following error: 
"powershell-7.0.0-osx-x64.pkg" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.
```

# Environment data

```none

```

**Comment by built2order** [comment]
![Screen Shot 2020-03-17 at 10 56 33 am](https://user-images.githubusercontent.com/6132811/76811862-39359100-6847-11ea-9dfc-4eebd79aa65b.png)

Attaching screenshot.

**Comment by mklement0** [comment]
For context: You're referring to [_notarizing_](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) / [_notarization_](https://www.merriam-webster.com/dictionary/notarization) software for macOS - please update the issue's title to use one of these terms.

**Comment by built2order** [comment]
My Australian spell checker still doesn't recognise the work!?!

**Comment by mklement0** [comment]
The noun form (_notarization_) isn't common, and not every dictionary (and, seemingly, spell checker) has an entry for it, but it definitely [exists](https://www.merriam-webster.com/dictionary/notarization), and it's the term used by Apple.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/issues/10874
