### ISSUE TITLE
On macOS, PowerShell unexpectedly uses /bin/zsh rather than /bin/sh to re-invoke itself when launched as a login shell.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12134]
Note: 

* There is no _functional_ problem.

* However, the rationale for choosing `/bin/zsh` over `/bin/sh` suggested by a comment in the source code is misleading (see below).

At the very least, getting clarity on this issue would allows to amend the source-code comments to avoid confusion.

----

The source code currently states: 

https://github.com/PowerShell/PowerShell/blob/07962a9749ab50444ebe87101e5bacf5b5f47f88/src/powershell/Program.cs#L324

Additionally, @rjmholt  states in https://github.com/PowerShell/PowerShell/pull/12058/files#r393120683

> No, we tried this. The version of bash it uses is too old to support `-l` in `sh`-compatibility mode and it wasn't starting properly.

`bash` on macOS has been frozen at `v3.2.57` for many versions of macOS, for licensing reasons, and won't get updated.
However, it definitely at least _formally_  supports `-l` (`--login`); from the `man` page:

> If  `bash`  is  invoked  with  the name `sh`, it tries to mimic the startup
       behavior of historical versions of sh as  closely  as  possible,  while
       conforming  to the POSIX standard as well.  When invoked as an interac-
       tive login shell, or a non-interactive shell with the  `--login` [alias `-l`]  option,
       it  first  attempts  to read and execute commands from `/etc/profile` and
       `~/.profile`, in that order.

Indeed, running `/bin/sh -l` loads both `/etc/profile` and `~/.profile`.

Even if `bash` ever gets removed from future macOS versions, `/bin/sh` (the _system_ default shell, as opposed to the _interactive user_ default shell, which is now `zsh`) must and will remain a (mostly) POSIX-compliant shell - whatever concrete shell act as `/bin/sh`.

As such, `/bin/sh` is the more stable long-term choice.

Of course, if there _is_ a functional problem with using `/bin/sh -l` currently, using `/bin/zsh` is a sensible workaround - but then the source-code comment should be amended.

# Environment data

```none
PowerShell Core 7.0.0
```

**Comment by mklement0** [comment]
@rjmholt, here's some background information that hopefully paints the full picture.

FWIW, I compiled a version with `/bin/sh` on macOS 10.15.3, and it worked fine. The system Bash version (`/bin/bash`), 3.2.57, hasn't changed since 10.10 (Yosemite), long before the oldest version supported by PowerShell (10.13, High Sierra)

The `-l` / `--login` option was introduced in Bash 2.0.

The short of it is: I recommend updating the incorrect comment in the source code to avoid confusion and to provide a brief rationale for the choice of `/bin/zsh`.

----

**macOS default user and system shells:**

**Default interactive user shell (configurable by each user)**:
* up to 10.14 (Mojave): `/bin/bash`, version 3.2.57(1) since 10.10 (Yosemite)
* from 10.15 (Catalina): `/bin/zsh`

**System default shell, `/bin/sh`**:
* as of 10.15 (Catalina): a custom build of `/bin/bash`, 3.2.57(1) (and the respective Bash versions on older macOS versions) - _for licensing reasons, Bash on macOS hasn't received updates since 10.10, and won't in the future_.

    * Even though Bash automatically enters POSIX compatibility mode when invoked via a symlink named `sh` or with `$0` set to `/bin/sh`, `sh`, or `-sh` (to request a login shell), (e.g., via `exec -l -a <value-for-$0> /bin/bash`), the custom build provides additional POSIX compliance.

* Will a different shell ever become `/bin/sh` on macOS?

    * `/bin/zsh` too is capable of running in POSIX compatibility mode when invoked as discussed above for Bash (as currently used by PowerShell).

    * Since no automatic startup process processes `/etc/profile` and `~/.profile` on macOS - only the individual user shell instances created on demand do - the capabilities of `/bin/sh` are primarily important for portable shell scripts that use a `#!/bin/sh` shebang line.

        * Therefore, if macOS ever wants to support potential new POSIX shell-language features introduced after Bash 3.2.57, it'll have to replace `/bin/sh` with a more modern shell.

**Comment by rjmholt** [comment]
As I say, I originally tried the /bin/sh invocation and it didn't work for me. But if you've tried it and it works, then perhaps you can open a PR and we can try out your changes?

Is there any observable behavioural difference in using /bin/zsh that you've noted?

**Comment by mklement0** [comment]
My original concern was that use of `/bin/zsh` wasn't necessary, and that the ramifications of using it in lieu of `/bin/sh` weren't clear and that it's always better to avoid special-casing.

> Is there any observable behavioural difference in using /bin/zsh that you've noted?

There are at least two I personally know of (detailed below), but there may be more.
That said, they may not matter in practice.

Therefore, among the **solutions** below, I'd be personally fine with (a), but I hope that at least _that_ will be considered - fixing a misleading comment in the source code is simple and well worth it.

* **Solution (a)**: Stick with `/bin/zsh`, but amend the source-code comment with a proper rationale / background info (and perhaps even a link to this conversation).

* **Solution (b)**: Revert to `/bin/sh` (only if tests show that it works, of course).

  * This means that responsibility for providing a modern-enough POSIX-compliant shell as `/bin/sh` rests on macOS itself. While it still is (a custom build) of `bash` as of macOS 10.15, they've laid the groundwork for easily switching to either `/bin/dash` or `/bin/zsh` in future versions. Also, users can already switch of their own accord in 10.15 (requires `sudo`) - though I think switching the _system_ shell on individual machines is asking for trouble.

* **Solution (c)**: on macOS 10.15 and above, switch to `/bin/dash` for better performance:

  * I haven't done any tests, and my guess is that in practice there's not much of a difference, but the no-frills `/bin/dash` is built for speed, and its binary size is also only about 1 / 5th to 1 / 6th of that of `bash` / `zsh`.

  * Obviously, this amounts to special-casing too (macOS 10.14 and below do not come with `/bin/dash`).

  * Thus, since macOS 10.14 and below can't use `/bin/dash` yet, this solution must be combined with either (a) or (b).

---

**Behavioral differences** between  Bash  (acting as `/bin/sh`) and `/bin/zsh` in POSIX compatibility mode:

* The `echo` built-in _does_ interpret `\` escape sequences in Bash running as `sh` (due to the macOS custom build of it), `zsh` does _not_; e.g, `echo 'a\nb'` prints `a<newline>b` in Bash in compatibility mode (on macOS only), but `a\nb` _verbatim_ in `zsh` in compatibility ode.

   * As stated, macOS goes out of its way for this behavior, with a custom Bash build, presumably for the  official UNIX 03 certification, as such systems that report as XSI-compliant (an optional superset of the standard that macOS implements) are required to exhibit this behavior.

   * `/bin/dash` too exhibits this behavior, always (but not `/bin/zsh` when acting as `sh`).

* As a side effect of Bash acting as `/bin/sh`, the `$BASH` shell variable is set and there's conditional code in `/etc/profile` that sources additional, Terminal.app-specific code if `$BASH` is found to be set.

   * That said, this code - intended for terminal session-specific restoration on restart for Bash via shell functions - doesn't matter to PowerShell and it's arguably better _not_ to waste time executing it, so use of `/bin/zsh` is actually an _advantage_ in this respect; `/bin/dash` would _not_ execute it either.
