### ISSUE TITLE
Tying the letter 'c' results in Ctrl-C

### ISSUE THREAD

**Issue by RichiCoder1** [PowerShell/PowerShell#12130]
# Steps to reproduce

Type the letter C.

# Expected behavior

`c` is written to the terminal

# Actual behavior

`^C` is written to the terminal.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The weird thing is it works fine on one machine, just not the other.

**Comment by mklement0** [comment]
If it happens just on one machine, we'd need to know what's special about that machine.

Also, the problem may be related to the terminal program (console) used - what is it?

**Comment by RichiCoder1** [comment]
@mklement0 That's the weird thing.  It happens in both the standard windows console and Windows Terminal. It doesn't happen with 6.2, only 7. The only other major difference I can think of is this machine is in in insiders, but that's about it.

**Comment by RichiCoder1** [comment]
The only other thing worth noting is doing `Alt+c` outputs a C fine (which is how I'm mostly getting around it)

**Comment by RichiCoder1** [comment]
Figured it out. Some random script had a PSReadLine handler that was suddenly was uncoditionally treating `c` as a signal to cancel.
