### ISSUE TITLE
After modifying Terminal colour's + transparency the terminal gets corrupted

### ISSUE THREAD

**Issue by vurso** [PowerShell/PowerShell#12133]
Installed the latest version of PowerShell 7 on a Windows 10 Professional desktop PC with the latest .NET Core and Framework SDK's already installed.

Starts up fine however when I then go into the settings and modify the background colour for example and then I try installing a module for example the terminal gets itself into a mess with the cursor appearing in a phantom location and terminal updates not appearing in the right place
![image](https://user-images.githubusercontent.com/997532/76764772-5443ca80-678d-11ea-9387-90cf07b4a506.png)

**Comment by iSazonov** [comment]
I can not repo. Please add more info.
Please start `pwsh -NoProfile` and try to repo your issue. 
Also you could do `Remove-Module PSReadline` and try to repo.

**Comment by daxian-dbw** [comment]
> I can not repo.

Same here. I cannot repro. Some additional repro steps would be helpful.

**Comment by iSazonov** [comment]
Also please share your Windows 10 version.
