### ISSUE TITLE
Add Regression Tests for Web Cmdlets' Regex Patterns

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#12138]
# Summary of the new feature/enhancement

The web cmdlets currently are lacking in terms of regression tests. The only tests currently verifying the regex patterns used are here:

https://github.com/PowerShell/PowerShell/blob/920b671fb41bdaa3cfc0ce030a41e81c4860d330/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1#L1904

The cmdlets use a half-dozen different regex patterns for various purposes; we should add tests to ensure they work correctly going forward.

See also #12099 -- both that PR and the new tests should be backported to 7.0 branch as a bugfix.

## Details

This is the tool we are supposed to use:  https://www.microsoft.com/en-us/security-risk-detection/
The description of the requirement are here:
https://docs.microsoft.com/en-us/security-risk-detection/concepts/seed-files

**Comment by TravisEz13** [comment]
> @TravisEz13 If I understand right you will make the tests internally so the site list will be not public. We are not going to change, share or distribute the pages. We are not going to download any artifacts like pictures - we need only html. We are not going to check these sites and distribute any information about it - we are going to test only that our code works correctly on the data.

@iSazonov  The HTML itself is also covered by the site's copyright.  So, until you propose exactly what site to use, I can't say if such usage would require permission from the site owner.

**Comment by iSazonov** [comment]
> The HTML itself is also covered by the site's copyright. 

How do sites like Binq and Google search work? They collect HTMLs, store local in cache, parse, analyze and so on.

> until you propose exactly what site to use

We could start with *.office.com and *.microsoft.com sites

**Comment by TravisEz13** [comment]
@iSazonov tl;dr: Because search engines have a systematic way to opt-out, it's not considered a copyright violation.  See https://www.practicalecommerce.com/Search-Engines-Indexing-and-Copyright-Law

**Comment by TravisEz13** [comment]
The tasks to run these are now in private preview:  https://secdevtools.azurewebsites.net/
