### ISSUE TITLE
Relevant com error message is no longer displayed

### ISSUE THREAD

**Issue by nbkalex** [PowerShell/PowerShell#12143]
https://github.com/PowerShell/PowerShell/blob/320656c8deb21d1c9e5d34bc8f6b67a69c06597d/src/System.Management.Automation/engine/COM/ComMethod.cs#L109

IMO the relevant error message is in the target invocation exception.
I'm not sure what are the scenarios treated there but I think it's not an improvement.
![debug_ps_com_method](https://user-images.githubusercontent.com/29368999/76854935-b74e6380-6858-11ea-8ae2-21d050de3a15.jpg)

![error_message_display](https://user-images.githubusercontent.com/29368999/76855324-8fabcb00-6859-11ea-8813-73fe610f1af3.jpg)

black background is master
blue background is 5.1.18362.628

**Comment by vexx32** [comment]
Seems like it would be more appropriate to put the two together as an `AggregateException`, or just return the surface one, for sure.

**Comment by nbkalex** [comment]
> Seems like it would be more appropriate to put the two together as an `AggregateException`, or just return the surface one, for sure.

I'll give it a try

**Comment by nbkalex** [comment]
Using AggregateException will look like this:
![error_message_display](https://user-images.githubusercontent.com/29368999/76864079-2cc23000-6869-11ea-9c71-e52f74d76f7e.jpg)

Not sure it is more human readable, but I'm pretty sure it's more explicit.
