### ISSUE TITLE
Test-Connection shows unwanted output when DNS not resolved on Powershell 7.0.0

### ISSUE THREAD

**Issue by chvol** [PowerShell/PowerShell#12147]
`Test-Connection -Quiet -Count 1 Hostname` 
gives output

`Test-Connection: Testing connection to computer 'Hostname' failed: Cannot resolve the target name.`

Expected behaviour would be

`False`

In a code block like 
` $comps | ForEach-Object -Process { if (Test-Connection $_.Name -Quiet -Count 1) {Write-Output "$($_.Name) on"} else {Write-Output "$($_.Name) off"} }`
this gives output
`Test-Connection: Testing connection to computer 'Hostname' failed: Cannot resolve the target name.
Hostname off`

Again, the extra output is unwanted, given the Quiet flag.

**Comment by vexx32** [comment]
🤔 This is kinda weird. We shouldn't be surfacing any hostname resolution errors...

This code path handles the hostname resolution:

https://github.com/PowerShell/PowerShell/blob/43e0e1a1c54144ae351e1541dd0965b7792d338b/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs#L640-L733

As you can see, we're catching everything in there. Not sure why you'd be getting hostname resolution errors here, unless you're using a different Test-Connection command. There are only two cases you should be getting errors from this cmdlet -- when you provide a `$null` hostname, or when you provide an IP address that doesn't match the requested switch (i.e., providing an IPv6 address and specifying `-IPv4` or vice versa).

Just to be sure, can you grab the output from `Get-Command Test-Connection` so we can see what it's calling?

**Comment by chvol** [comment]
` Get-Command Test-Connection`

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Test-Connection                                    7.0.0.0    Microsoft.PowerShell.Management
```

**Comment by vexx32** [comment]
Can you post the result from `$PSVersionTable` as well, please, so we have any necessary OS / other info? Thanks! 😊

**Comment by vexx32** [comment]
Oh, I see it.

https://github.com/PowerShell/PowerShell/blob/43e0e1a1c54144ae351e1541dd0965b7792d338b/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs#L680-L704

We should definitely be just returning false here.

**Comment by iSazonov** [comment]
Issue is here
https://github.com/PowerShell/PowerShell/blob/43e0e1a1c54144ae351e1541dd0965b7792d338b/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs#L575-L577

**Comment by vexx32** [comment]
We catch the hostname resolution error in the method and call WriteError() -- there's nothing that can be done outside the method call itself other than writing `false` to output. The issue here is that the error still shows in `-Quiet` mode, so we'd need to handle that in the method.

**Comment by iSazonov** [comment]
Quiet parameter can be used in interactive session too. If user don't want to get error SilentlyContinue exists.

**Comment by vexx32** [comment]
`-Quiet` should do what it says on the tin, in my opinion. 🤷‍♂ 

If it's erroring, it's not quiet.

**Comment by SeeminglyScience** [comment]
@vexx32 btw the get host entry call is part of why the command sometimes doesn't respond to stop processing requests.

**Comment by vexx32** [comment]
That's a very good point... Is there an async/cancellable method for that one you know of?

**Comment by SeeminglyScience** [comment]
@vexx32 Since there's no cancel, all you can really do is something like:

```csharp
private CancellationTokenSource _cancel;

// ...

private IPHostEntry GetHostEntryWithCancel(string hostNameOrAddress)
{
    var task = Dns.GetHostEntryAsync(hostNameOrAddress);
    var waitHandles = new[] { ((IAsyncResult)task).AsyncWaitHandle, _cancel.Token.WaitHandle };
    if (WaitHandle.WaitAny(waitHandles) == 1)
    {
        throw new OperationCanceledException();
    }

    return task.GetAwaiter().GetResult();
}
```
