### ISSUE TITLE
Powershell 7: AD cmdlets don't seem to accept pipeline input

### ISSUE THREAD

**Issue by CamRatliff** [PowerShell/PowerShell#12145]
I'm sure that this has been reported by now but I couldn't find any with a quick search in the issues so here it is.
# Steps to reproduce
```
get-adgroup test_group | get-adgroupmember
```

# Expected behavior
```
Group members get outputted
```

# Actual behavior
```
Get-ADGroupMember: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input
```

# Environment data
```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Can you post the output from `Get-Command Get-ADGroupMember`, please? 🙂

**Comment by doctordns** [comment]
This works here just fine:
![2020-03-18_10-01-58](https://user-images.githubusercontent.com/3630329/76949025-d5bb6a00-68ff-11ea-8cf8-a767cd44944f.png)

What version is the AD Cmdlets module on your system? I am seeing version 1.0.1.0.

**Comment by mklement0** [comment]
@doctordns, you're running Windows PowerShell, not PowerShell 7.

**Comment by doctordns** [comment]
Sory - I forgot to attach the 7.0 version as well:

![2020-03-18_13-48-41](https://user-images.githubusercontent.com/3630329/76969001-b8979300-6921-11ea-88c9-0d23d8ff7cfc.png)

**Comment by iSazonov** [comment]
Only latest ActiveDirectory module (Windows Server 2019) works on PowerShell 7.0.

**Comment by doctordns** [comment]
> Only latest ActiveDirectory module (Windows Server 2019) works on PowerShell 7.0.

What is the recommended way to get this module?  We should perhaps provide better prescriptions advice?

**Comment by iSazonov** [comment]
Official docs https://docs.microsoft.com/en-us/windows-server/remote/remote-server-administration-tools

**Comment by Olivier92800** [comment]
I also encountered the issue with Powershell v7 from a Windows 2016 server or Windows 2019 server.
As explained on the official site of the get-adgroup comandlet in the section -Identy


"...Specifies an Active Directory group object by providing one of the following values. The identifier in parentheses is the LDAP display name for the attribute. The acceptable values for this parameter are:

	- A distinguished name
	- A GUID (objectGUID)
	- A security identifier (objectSid)
	- A security accounts manager account name (sAMAccountName)
..."

 For all version Powershell, the correct usage is :

(get-adgroup test_group).objectGUID |  get-adgroupmember
or
(get-adgroup test_group).objectSid |  get-adgroupmember
or
(get-adgroup test_group).sAMAccountName |  get-adgroupmember
or
(get-adgroup test_group).distinguishedName |  get-adgroupmember

For rename-adobject

"...Specifies an Active Directory group object by providing one of the following values. The identifier in parentheses is the LDAP display name for the attribute. The acceptable values for this parameter are:

	- A distinguished name
	- A GUID (objectGUID)
..."
