### ISSUE TITLE
Connect to Azure cmdlet doesn't work

### ISSUE THREAD

**Issue by vurso** [PowerShell/PowerShell#12142]
Operating system:  Windows 10 Professional (latest updates)

Default PowerShell version 5.x already installed (works fine)
PowerShell 7 latest release (has issues)

When attempting to run the following command in PowerShell 7 terminal (admin mode) the terminal just hangs waiting for a response which I believe is a popup modal to sign into Azure - this works fine with the current PowerShell version (5.x) i.e. the modal appears (see attached screenshot) but the same does not happen with PowerShell 7.

![image](https://user-images.githubusercontent.com/997532/76855447-11dfc380-6849-11ea-9952-82c69bd45462.png)

**Comment by vexx32** [comment]
This is an issue with the module itself and the API it's trying to use, which is simply not available on all platforms. As a result, it's not going to be properly compatible with pwsh. If the API is not available in .NET Core, they'll need to find an alternative way to handle that authentication method.

I'm not entirely sure which command you're using, it's obscured in the screenshot, but you'll need to file this issue on [the module's repo](https://github.com/Azure/azure-powershell); there's nothing PowerShell itself can do about the .NET APIs that a module chooses to use.
