### ISSUE TITLE
$PSUICulture Variable Empty in PS7 on Ubuntu 18.04

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/PowerShell#12149]
# Steps to reproduce

Log into PS 7.0 on an Ubuntu 18.04 machine:

```powershell
$PSUICulture
```

# Expected behavior

```none
en-US
```

# Actual behavior

```none
Returns empty.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Notes

- $PSUICulture returns correct value on PS Core 6 and PS 7 on Ubuntu 16.04.
- Seems like an issue specific to PS 7 on Ubuntu 18.04.

**Comment by mklement0** [comment]
As a data point: In my local Ubuntu 18.04.4 LTS VM, with the latest updates applied, I see a _different kernel_, and I also _don't see the problem you describe_.

Here's the - differing - kernel info from my VM, extracted from `$PSVersionTable`'s outptu:

```none
OS    Linux 4.18.0-041800-generic #201808122131 SMP Sun Aug 12 21:33:20 UTC 
```

**Comment by PlagueHO** [comment]
@mklement0 - interesting.

I was testing using the standard Azure Ubuntu 18.04 marketplace image and had not applied any updates to it.

I first detected the issue occurring in Azure DevOps Pipelines `ubuntu-18.04` pipeline images:
https://dev.azure.com/dscottraynsford/GitHub/_build/results?buildId=1431&view=logs&j=1b4c76ef-e880-5241-0155-88566c4dcdab&t=c3b097e0-8d2d-5cef-f943-5ce972a892ac&l=64

**Comment by iSazonov** [comment]
The variable returns `System.Threading.Thread.CurrentThread.CurrentUICulture.Name`.
[Docs](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.currentuiculture?view=netcore-3.1) says:
> by default is the same as the operating system culture

So I believe the Ubuntu image have probably an invariant culture like "C".

**Comment by mklement0** [comment]
Good catch, @iSazonov.

The invariant culture `CultureInfo` object indeed has the empty string as its `.Name` property, which is what `$PSUICulture` (and `$PSCulture`) reports when the `C` or `POSIX` locale is in effect in the calling POSIX-like shell (run `locale` to check).

```powershell
# From Bash:

$ LC_ALL=en-US pwsh -noprofile -c '$PSUICulture'
en-US # as expected

$ LC_ALL=C pwsh -noprofile -c '$PSUICulture'
 # empty string

$ LC_ALL=POSIX pwsh -noprofile -c '$PSUICulture'
 # empty string
```

**Comment by SeeminglyScience** [comment]
> The invariant culture's `CultureInfo` object (examine its properties with `[cultureinfo] '' | Format-List`) 

Use `[cultureinfo]::InvariantCulture` for that (edit or react to this and I'll mark off topic)

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience , I've made the edit, but I'm also curious (happy to mark this as off-topic later):

Did you  suggest `[cultureinfo]::InvariantCulture` solely for conceptual clarity, given that `[cultureinfo]  ''` works too?

The only difference - which I just now realized - is that `[cultureinfo] ''` creates a _read-write copy_ of the invariant culture. Was that the reason?

**Comment by SeeminglyScience** [comment]
Yeah mainly conceptual clarity.  It does also create an extra object that isn't needed, and also won't have reference equality with the static instance (neither of these are likely to ever matter though).
