### ISSUE TITLE
Feature Request: Get-Help -ShowWindow Option Dark/Inverse Mode - Or follow system theme

### ISSUE THREAD

**Issue by BouwenMA** [PowerShell/PowerShell#12159]
# Summary of the new feature/enhancement
Have the "Get-Help -ShowWindow" option show the resulting window with a dark/inverse mode, where the background is black and the text is white, or follow the system theme option like Windows 10 now has for light/dark.  

# Proposed technical implementation details
Possible options for specifying light/dark:
- If running Windows, then follow the system theme setting
- New PSPreferences variable
- Another switch on Get-Help like -ShowDarkWindow or -Dark

This is by no means a high priority.  With the new Windows Terminal and VScode now being nice with theming capabilities, this would be an eye-friendly enhancement.

**Comment by Zwatotem** [comment]
This already received labels, but I'd have the same request, but for `Out-GridView`. Should I create a new issue, or is editing this sufficient?
