### ISSUE TITLE
On Unix, PowerShell should define the SHELL environment variable on startup

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12150]
POSIX-like shells such as `bash` define the `SHELL` environment variable on startup as the full path of the _current user's default shell_ (e.g., `/bin/bash`). (They do so even if they're not the default shell themselves - unless the variable is already defined.)

This variable is [mandated by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08):

> SHELL
> This variable shall represent a pathname of the user's preferred command language interpreter. 

If PowerShell itself functions as the default shell, `SHELL` is never set, because PowerShell doesn't set it.

Unix utilities may rely on the presence of this environment variable.

Therefore, PowerShell, like POSIX-like shells, should define `SHELL` on startup, unless it is already defined.

# Environment data

Written as of:

```none
PowerShell 7.0
```

**Comment by iSazonov** [comment]
> Unix utilities may rely on the presence of this environment variable.

Interesting, how would we test that defining this variable will have the desired effects and do not break these utilities?

**Comment by mklement0** [comment]
> how would we test 

I don't think you can, but I don't think we have to:

Even non-POSIX shells such as `csh` set the `SHELL` variable, and even the behavioral variations among POSIX-like shells (except if they're in compatibility mode) mean that you can't make blind assumptions about _how, specifically_, to _invoke_ the shell reported by `SHELL` (other than without arguments).

In other words: no existing utility can make _fixed_ assumptions about specific behaviors exhibited by the user's default shell, as reflected in `SHELL`.

However, knowing _what shell_ is the user's default shell is important information, which PowerShell should provide too.

An important use case is that installer utilities may decide what shell-specific initialization files (profiles) they need to modify and how.

**Comment by davidBar-On** [comment]
I have a proposed fix for this issue, but again I am not sure were to add the tests.  My planned main test is to unset the SHELL env. variable, make sure it is not defined, and then run pwsh and verify that SHELL is set (and if possible also verify its value)

**Comment by mklement0** [comment]
I don't know if this has since been fixed or whether I'm missing something, but I just tried with PowerShell Core 7.2.0-preview.4 as the default shell on both macOS and Linux, and `$env:SHELL` _is_ defined accordingly.

@davidBar-On, do you still see it _not_ being set, and if so, in what version (and on what platform)?

**Comment by davidBar-On** [comment]
I am using WSL (Ubuntu 20.4 Linux) and building from PowerShell 7.2.0-preview.3 master branch. `$env:SHELL` is **not** defined by this version.  (Initially it was defined as `/bin/bash` from Linux, but after unset it and running pwsh again it was not defined.)

**Comment by iSazonov** [comment]
> I don't know if this has since been fixed or whether I'm missing something

We don't set the env variable in pwsh.

**Comment by mklement0** [comment]
Thanks, @iSazonov.

I've come to realize that the POSIX-compatible shells also do _not_ set this variable [as an environment variable - see below] - they rely on the _system_ to set it:

* On macOS, it seems that setting `$env:SHELL` happens via the `login` utility that the terminal applications use behind the scenes, given that every shell created in a terminal is launched as a _login_ shell (`-l`)

* On Linux, judging by my Ubuntu 18.04 machine, it seems that `$env:SHELL` is set _once_, when a user's OS session starts.

Therefore, from what I can tell, using PowerShell as a user's default shell should work correctly already - also via `ssh`.

----

Among POSIX-compatible shells, `zsh` and `dash` do not set `$SHELL` at all, whereas `bash` and `ksh` only set it as a _shell-only_ variable, not as an environment variable - all this suggests that shells aren't expected to define this variable _as an environment variable_ themselves.

Due to PowerShell having distinct syntaxes for environment- vs. shell-only variables, the `bash` / `ksh` approach wouldn't work; as a courtesy, we _could_ set the environment variable, but I don't think it's necessary, given that it should be defined by the system, and given that POSIX-compatible shells do not (fully) try to compensate for its absence.

---

@davidBar-On, can you confirm that starting a new shell after `chsh -s /usr/bin/pwsh` indeed has `$env:SHELL` defined accordingly?

**Comment by davidBar-On** [comment]
> can you confirm that starting a new shell after `chsh -s /usr/bin/pwsh` indeed has `$env:SHELL` defined accordingly, after logging out and back in or rebooting?

After setting `pwsh` as the default shell using `chsh` and logging in the `$env:SHELL` is set to the new shell (I used `su` to login).

Also, under Linux `bash` I `unset SHELL` and checked which shell sets it (without login).  `/bin/bash` does set SHELL if it is not set already. `/bin/sh` and `/bin/csh` does not.

**Comment by mklement0** [comment]
Thanks for checking, @davidBar-On (using `su $env:USER` is a great idea to avoid the need for a logout / reboot - hadn't occurred to me).

Note that `/bin/bash` sets a _shell_ variable named `SHELL`, not an _environment_ variable (verify with `declare -p SHELL`); On Ubuntu, `/bin/sh` is `dash` (which, as you state, takes no action at all). As stated, the `bash` approach (ditto for `ksh`) isn't really an option for PowerShell, given that _environment_ variables use a different namespace (`$env:SHELL`) from _shell_ variables (`$SHELL`).

Just to be clear: Are we in agreement that _no_ action is needed?

**Comment by iSazonov** [comment]
If we don't know broken scenarios with SHELL _environment_ variable I suggest to archive the issue.
