### ISSUE TITLE
Un-Pend test after NET 5 Preview 2

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#12155]
Initially removed in https://github.com/PowerShell/PowerShell/pull/12140/commits/1e8e3b4260995e9584080017decd0fa111c374dc
Then added back as pending in : https://github.com/PowerShell/PowerShell/pull/12099

**Comment by TravisEz13** [comment]
Also, create tests for the regex's in .NET. 
https://github.com/dotnet/runtime/blob/f80a5147ef7662c3238275568c9dad7655a9684f/src/libraries/System.Text.RegularExpressions/tests/Regex.KnownPattern.Tests.cs#L886

**Comment by iSazonov** [comment]
Do we ready to un-pend?

**Comment by TravisEz13** [comment]
should be.  .NET said it was in Preview.2 when I filed the issue.
