### ISSUE TITLE
Font changes are not applied.

### ISSUE THREAD

**Issue by wonho21** [PowerShell/PowerShell#12153]
# Symptom

Change the Powershell 7 font to D2Coding. [https://github.com/naver/d2codingfont](url)

In the <Defaults> menu (Console Windows Properties), the D2Coding font is visible.

However, in the <Properties> menu ("Powershell 7 (x64)" Properties), the D2Coding font is not visible, and fonts such as Consolas are visible.

Consolas and Lucida Console do not contain Korean font information, so Korean characters are not displayed as desired.

I think this is a bug. It doesn't happen on Windows 10.

If you compare it to Windows Powershell on the same server, you can clearly see the difference.

# Comparison : Windows Powershell vs Powershell 7

![Image of Defaults Menu](https://s3-ap-northeast-1.amazonaws.com/ftt-img.four33.com-tok/github-PS-Defaults.png)

![Image of Properties Menu](https://s3-ap-northeast-1.amazonaws.com/ftt-img.four33.com-tok/github-PS-Properties.png)

# Environment data

Windows Server 2012 R2 English (current system locale : Korean)

```PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Can you compare first tab - Options?
