### ISSUE TITLE
Null-coalescing operator inconsistent behaviour with types

### ISSUE THREAD

**Issue by nvarscar** [PowerShell/PowerShell#12158]
# Steps to reproduce

```powershell
$null ? "original value" : "substitute value"
[int]$null ? "original value" : "substitute value"
[string]$null ? "original value" : "substitute value"
$null ?? "substitute value"
[int]$null ?? "substitute value"
[string]$null ?? "substitute value"
```

# Expected behavior

```none
substitute value x6
```

# Actual behavior

```none
substitute value
substitute value 
substitute value 
substitute value 
0
<empty string>
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
When you convert `$null` to a `string` or `int`, they are no longer `$null`.  The null coalescing operator doesn't work like an `if` statement (i.e. it's not "truthy") but instead like a `if ($null -eq $val)` statement.

**Comment by vexx32** [comment]
We're also conflating two different operators here.

```ps1
$null ? "original value" : "substitute value"
[int]$null ? "original value" : "substitute value"
[string]$null ? "original value" : "substitute value"
```

This operator has nothing to do with null, it's a ternary operator. It selects a value based on whether it sees the conditional as `$true` or `$false`. Empty string, null, and `0` are all considered "falsey" in PowerShell. You'll get the same exact results if you swap in a regular `if ($condition) { $truevalue } else { $falsevalue }` statement instead.

```ps1
$null ?? "substitute value"
[int]$null ?? "substitute value"
[string]$null ?? "substitute value"
```

This is the null coalescing operator, it only cares whether something is null or not. As @SeeminglyScience mentioned, once you cast null to another type, it can be converted. `[int]` is not nullable, so it gets converted to the closest possible value, but it isn't the same as null.

`[string]` is a bit of a confusing one -- the PowerShell team made a design decision quite a while back to treat strings more like a proper value type. This results in a few differences from how strings behave in C# and the rest of .NET; they can't be enumerated in a `foreach` or over a pipeline without a casting operator to force the conversion to `[char[]]`, and they can't be `$null` in PowerShell; if you cast `$null` to a string, you get the empty string back. The only way to get a string null in PowerShell is to use the static property `[NullString]::Value` if I recall correctly.

Perhaps this could be documented better? Was there documentation that led you to believe the operators should be working the way you expected that we could look to revise? 🙂

**Comment by nvarscar** [comment]
Excellent responses, that does make things clear. I guess the docs never say that this is only valid for pure $null values, but I'm not sure if they need to go to such detail, as, clearly, [string]$null and [int]$null are not nulls indeed. I tried to use it against a function parameter defined as `[string]$Name` and was expecting it to be null, since it wasn't passed upon function call. I should've put 2 and 2 together and realize that assigning type to a variable makes it non-null. I guess, I've become too used to Powershell "truth" and expected this operator to behave in a similar way.
Thank you all for the explanation, I'm going to close this issue.
