### ISSUE TITLE
PowerShell ISE

### ISSUE THREAD

**Issue by soethi** [PowerShell/PowerShell#12152]
I would like to request for keep continue for PowerShell ISE, it's very easy to use not only for beginner but also a lot can run easily to catch error detection. I'm urge please continue support ISE for us.

Thanks and Best Regards,

SOE THI

**Comment by iSazonov** [comment]
ISE is Windows component and is frozen, Windows PowerShell is frozen too - all new features will be in PowerShell Core only. Instead of ISE please use VS Code with PowerShell extension. It supports editing and debugging.

**Comment by soethi** [comment]
I would to say what can I do if ISE is discontinued and frozen? I am simple
user and I love ISE since first release of PowerShell ISE, I have to say
some of object can not use on VS code which is System.Windows.Form. I am
still using ISE due to internal automation deployment and some more I can
edit for Asian font for output display . in this case if I am wrong please
correct me.

I am very sure you can't run this command >>>

[System.Windows.MessageBox]::Show('Would  you like to play a
game?','Game input','YesNoCancel','Error') <<<<

Thanks and Best Regards
ST

**Comment by iSazonov** [comment]
>I am very sure you can't run this command >>>
[System.Windows.MessageBox]::Show

See https://github.com/PowerShell/PowerShell/issues/11513#issuecomment-571727748

> ome of object can not use on VS code which is System.Windows.Form. I am
still using ISE due to internal automation deployment and some more I can
edit for Asian font for output display

You could report to VS Code and VS Code PowerShell extension repositories.

In any case ISE works only with Windows PowerShell. You should consider migrating to PowerShell Core and .Net Core.

**Comment by doctordns** [comment]
First off - VS Code replaces ISE. The $PSISE object is different, but anything you can do in ISE you can do with VS Code.

YOu can target VS Code at Windows PowerShell if you choose to and change versions of PowerShell to use. It's quite easy.

```powershell
# load the assemblies 
 [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")  
[void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms") 
[void] [System.Windows.Forms.Application]::EnableVisualStyles() 
[System.Windows.MessageBox]::Show('Would  you like to play a     
# Put up a message block:
[System.Windows.Forms.MessageBox]::Show('Would  you like to play a game?','Game input','YesNoCancel','Error')

**Comment by soethi** [comment]
Ok, Thanks for your reply,
#11513 << is make sense for me.
Best Regards,

ST

**Comment by soethi** [comment]
I would request where can I edit for Asian language on VS code and how/whre to report VS Code teams? 
I have to say sorry and if I ask too much question, 
Thanks

**Comment by soethi** [comment]
> 
> 
> First off - VS Code replaces ISE. The $PSISE object is different, but anything you can do in ISE you can do with VS Code.
> 
> You can target VS Code at Windows PowerShell if you choose to and change versions of PowerShell to use. It's quite easy.
> 
> ```powershell
> # load the assemblies 
> [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")  
> [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms") 
> [void] [System.Windows.Forms.Application]::EnableVisualStyles() 
> [System.Windows.MessageBox]::Show('Would  you like to play a     
> # Put up a message block:
> [System.Windows.Forms.MessageBox]::Show('Would  you like to play a game?','Game input','YesNoCancel','Error')
> ```
> 
> Works great.

Thank you so much.

**Comment by doctordns** [comment]
> I would request where can I edit for Asian language on VS code and how/whre to report VS Code teams?
> I have to say sorry and if I ask too much question,
> Thanks

Report issues with VS Code to: https://github.com/Microsoft/vscode/issues

**Comment by Shayan-To** [comment]
Take a look at https://ironmansoftware.com/using-powershell-core-6-and-7-in-the-windows-powershell-ise/.

**Comment by soethi** [comment]
> 
> 
> Take a look at https://ironmansoftware.com/using-powershell-core-6-and-7-in-the-windows-powershell-ise/.

Hi Thanks for your reply I had explore your website from google, however I am facing with this issue,

Regards,

>>>>
$Host.PushRunspace($Runspace)
Exception calling "PushRunspace" with "1" argument(s): "Object reference not set to an instance of an object."
At line:13 char:1
+ $Host.PushRunspace($Runspace)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
 
Exception calling "PushRunspace" with "1" argument(s): "Object reference not set to an instance of an object."
At line:13 char:1
+ $Host.PushRunspace($Runspace)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
<<<

**Comment by dpandharkarGIT** [comment]
Try this : 

```powershell
$Process = Start-Process PWSH -ArgumentList @("-NoExit") -PassThru -WindowStyle Hidden

function New-OutOfProcRunspace {
    param($ProcessId)

    $ci = New-Object -TypeName System.Management.Automation.Runspaces.NamedPipeConnectionInfo -ArgumentList @($ProcessId)
    $tt = [System.Management.Automation.Runspaces.TypeTable]::LoadDefaultTypeFiles()

    $Runspace = [System.Management.Automation.Runspaces.RunspaceFactory]::CreateRunspace($ci, $Host, $tt)

    $Runspace.Open()
    $Runspace
}

$Runspace = New-OutOfProcRunspace -ProcessId $Process.Id
$Host.PushRunspace($Runspace)
```

**Comment by noeffort3** [comment]
Hi I have two comments/questions; I will submit separately.

First, to dpandharkarGIT:
I followed the instructions to install 7 alongside 5.1.  I have also used the "Add-on" script to switch the ISE from old, .NET (5.1) to new Core (7).
When I run this however, I recieve the same "runspace" error as you address with your latest reply above, and still recieve the "runspace" error

....
`$Host.PushRunspace($Runspace)  <-- the last directive/end of your script above
MethodInvocationException: 
Line |
  16 |  $Host.PushRunspace($Runspace)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "PushRunspace" with "1" argument(s): "Specified method is not supported."`

It does switch to version 7, yes, but is this an impactful error?

**Comment by noeffort3** [comment]
The second question is from the above statements regarding "ISE is regarding:

> ISE is Windows component and is frozen, Windows PowerShell is frozen too - all new features will be in PowerShell Core only. Instead of ISE please use VS Code with PowerShell extension. It supports editing and debugging.

That is not "OK"... many who use PowerShell are administrators, not developers.  I think this is lost on Microsoft/PowerShell community (but what is new there... "the Devs are the darlings")  but a) we are not developers, hence learning yet another net new tool (Visual Studio) is not somethign that is going to happen and b) has a HUGE licensing impact (ISE was included, previously)... 

Now I have to go get a VS license just to run Powershell in the future?

NOT OK, at all... i.e, someone needs to develop an ISE specifically for PowerShell Core/7

**Comment by vexx32** [comment]
Visual Studio is not required, I'm not even sure it's recommended.

Visual Studio Code is a different (completely free) product entirely, and the PowerShell extension for it is what's maintained directly by the PS team.

But yes, Windows PowerShell / the ISE are frozen. The ISE contains many components not owned by the PS team and from what I recall being said previously there were a multitude of legal issues with open sourcing it, so it had to be dropped as the team is focusing on open sourcing their core products. Both pwsh and the PowerShell extension for VS Code are open source.

**Comment by spacefuntus** [comment]
@dpandharkarGIT Could you please provide your contact details. Wanted to discuss something with you
