### ISSUE TITLE
Common pipeline parameters

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#12164]
Based on request #11754, I think that it should be avoided that there will be different implementations of parameters for each cmdlet that creates a selection of the `$InputObject` collection.
I'm specifically referring to the [`Select-Object`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7) (and purposed in #11754) parameters as: 

- `-Last <Int32>`
- `-First <Int32>`
- `-Skip <Int32>`
- `-SkipLast <Int32>`
- `-Index <Int32[]>`
- `-SkipIndex <Int32[]`

Note that [`Get-Content`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7) has also two of these parameters:

- `-TotalCount alias `-First` (and `-Head`)
- `-Tail` Alias `-Last`

Meaning that either:

* A consistent referral to the  [`Select-Object`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7) cmdlet should be made.

Or:

* These parameters should be added to the [**CommonParameters**](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7).
This would mean that when `CmdletBinding` is active and there is an `InputObject` parameter  that supports `ValueFromPipeLine`, the concerned `Common pipeline parameters` will be put in a parameter set to together with the  `InputObject` parameter
<sub>(where the set `-Last`, `-First`, `-Skip` is mutual exclusive with `-SkipLast` and `-Index` and  `-SkipIndex`)</sub>
The `InputObject` collection should than automatically filtered for processing according to the definition of the concerned parameter.

**Comment by iSazonov** [comment]
I believe Select-Object cmdlet designed for this and adding these parameters to other cmdlets makes sense only in specific scenarios like for performance and  Get-Content addresses such scenario.

I believe most of users prefer _simple cmdlets with few parameters_. This is in keeping with the spirit of PowerShell.

**Comment by iRon7** [comment]
I agree that "_Select-Object cmdlet designed for this_", I just wanted to be certain that if the number _specific scenarios_ increases, these parameters stay consistent and 'common parameters' are considered.
