### ISSUE TITLE
PSHostTraceListener has redundant IDisposable implementation

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1216]
Because this class is internal, the Close method does nothing (calls base, which does nothing), and nobody can derive from PSHostTraceListener to override that behavior.

**Comment by joeyaiello** [comment]
@lzybkr PowerShell Standard implications?

**Comment by lzybkr** [comment]
None.

**Comment by joeyaiello** [comment]
Then this sounds like code cleanup that we don't need for 6.0.0.

**Comment by iSazonov** [comment]
It is not clear that the fix will be - remove PSHostTraceListener.Dispose() method?
