### ISSUE TITLE
On-board and Enable telemetry for windows

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#1217]
As a non-windows component, the onboarding process is different.  We should:
- [ ] Onboard PowerShell Core to Windows Telemetry
- [ ] Re-enable telemetry for windows
- [ ] Find a story for non-windows platform (out of scope of this issue)

**Comment by SteveL-MSFT** [comment]
Current plan is to use AppInsights

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/PowerShell/PowerShell/pull/3620
