### ISSUE TITLE
Fix sorting of hashtables

### ISSUE THREAD

**Issue by Hermholtz** [PowerShell/PowerShell#12175]
# Summary of the new feature/enhancement

In order to sort dictionary (hashtable) an explicit `GetEnumerator` is required. For example:
```powershell
> $a = @{a=1;b=2;c=3;d=4}
> $a|sort Name                                                                                                                                       
Name                           Value
----                           -----
c                              3
d                              4
b                              2
a                              1
```
(doesn't work)

```powershell
> $a.GetEnumerator()|sort Name                                                                                                                       
Name                           Value
----                           -----
a                              1
b                              2
c                              3
d                              4
```
(works fine)

# Proposed technical implementation details (optional)

Make a change so that
```
> $a|sort Name                                                                                                                                       
```
works as expected. Current behavior benefits nobody.

**Comment by mklement0** [comment]
While it may be surprising, `[hashtable]` instances have always been treated as a _single object_ in the pipeline, and changing that now would be a massively breaking change.

Think of `[hashtable]` instances as _single objects_, whose _properties_ (hashtable entries) you wouldn't expect to be enumerated in the pipeline either.

**Comment by Hermholtz** [comment]
At first it's really surprising and confusing. Then it starts to make sense. However maybe there should be friendlier way than using a method which is very rarely used even by .NET developers.

**Comment by mklement0** [comment]
I agree that it's not obvious, but the need for it is too rare to warrant a dedicated operator for it in PowerShell, I think.

Note that your specific scenario is at least explicitly documented in the conceptual [`about_Hash_Tables` topic](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables?view=powershell-7#sorting-keys-and-values).

Also note that, as stated in the linked topic, you're not sorting the hashtable itself (which is impossible); instead, you're outputting a sorted array of key-value pairs.

**Comment by mklement0** [comment]
P.S.: A simple alternative is to cast to [`System.Collections.SortedList`](https://docs.microsoft.com/en-US/dotnet/api/System.Collections.SortedList):

```powershell
PS> $ht = @{ zz = 1; gg = 2; aa = 3 }; [System.Collections.SortedList] $ht

Name                           Value
----                           -----
aa                             3
gg                             2
zz                             1
```
