### ISSUE TITLE
Powershell Core not running in read-only NFS

### ISSUE THREAD

**Issue by Smino97** [PowerShell/PowerShell#12181]
Hi,

I am trying to run powershell core on a live booted CentOS 7. The NFS of the System is running on a dedicated Server and is read-only that multiple clients can access the NFS at the same time.
I tried the newest versions stable, lts and preview. None of them seem to work on read-only filesystems.

Question is: Is there a way to run Powershell Core on read-only FS, e.g. by manually setting up the environment properly?

# Steps to reproduce

```
1. Setup PXE Server using https://github.com/bertvv/ansible-role-pxeserver
2. Setup NFS using https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/diskless-nfs-config
3. Install Powershell on the exported NFS with
`sudo yum install powershell --installroot=_exported-root-directory_ --releasever=/`
4. Connect to Live booted client and run `pwsh`

```

# Expected behavior

```
Powershell starts

```

# Actual behavior

![image](https://user-images.githubusercontent.com/62539851/77311661-d3db1780-6d00-11ea-9d55-a0d5b8731e6a.png)

Extract of `strace -f pwsh-preview`

![image](https://user-images.githubusercontent.com/62539851/77311764-07b63d00-6d01-11ea-8a68-3e190a5590b8.png)

# Environment data

```
Package installed: powershell-preview-7.0.0_rc.3-1.rhel.7.x86_64.rpm
CentOS 7

```

**Comment by daxian-dbw** [comment]
I'm afraid you won't be able to run pwsh on a read-only file system as of today.

**First**, .NET Core runtime creates pipes for managed debugging, when the runtime starts up.
> ... pipes for managed debugging in /tmp. They are named something like “clr-debug-pipe-17206-65823754-out”, “clr-debug-pipe-17206-65823754-in” where 17206 is the process id and 65823754 is the process creation time.

Your screenshot shows the failure of creating the pipes. For details, see https://github.com/dotnet/runtime/issues/7204

![image](https://user-images.githubusercontent.com/127450/77346070-dafb2900-6cf2-11ea-9323-9456538ab9a3.png)

This step can be disabled by executing `export COMPlus_EnableDiagnostics=0` before start the .NET Core program. See https://github.com/dotnet/coreclr/pull/15878 for details.

**Second**, the update notification feature added in pwsh 7 requires writing to the disk. But you can disable it by executing `export POWERSHELL_UPDATECHECK=Off` before starting pwsh.

**Third**, the `PSReadLine` saves command line history to a file. This can be disabled by running `Set-PSReadLineOption -HistorySaveStyle SaveNothing` right after starting pwsh I guess.

**Fourth**, the module analysis in PowerShell saves the analysis results to a cache file. This cannot be disabled, but the failure of writing to the cache file will be tolerated by pwsh.

**Fifth, this one might be a hard blocker.** pwsh also creates a pipe for debugging purpose when starting (attach to a running pwsh process), and obviously, this will fail on a read-only file system. It's very possible this failure will terminate the process.

**Comment by Smino97** [comment]
Hi,

thanks for your fast and detailed answer!

I tried to get this done step by step, but still unfortunately pwsh will prompt me another error.
Nevertheless it seems like the Issue with the .NET Core runtime and it's pipes is solved.
I setup everything again and installed pwsh stable version this time to be sure it has nothing to do with the environment.

Here's the output: 
![image](https://user-images.githubusercontent.com/62539851/77414056-ae154780-6dc0-11ea-9972-bb89a42d4043.png)

The only solution I could find for this is something out of the visual studio context I guess, see here: https://stackoverflow.com/questions/34388394/the-type-initializer-for-system-management-automation-runspaces-initialsessions

Comments/Help highly appreciated!

**Comment by daxian-dbw** [comment]
The exception happens here, when trying to create the data directory.
https://github.com/PowerShell/PowerShell/blob/68442a33e5f775c80526b2f64475c795f6bb085b/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L278-L301

It turns out this method attempts to create directories at multiple code paths ...
There could be code like this elsewhere. It was never a target for pwsh to work on read-only file system.

To work around this particular issue, you will have to pre-create those default directories:
https://github.com/PowerShell/PowerShell/blob/68442a33e5f775c80526b2f64475c795f6bb085b/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L258-L261 
but I doubt if it's worth to try, because you may run into other similar issues after working around this one.
