### ISSUE TITLE
Remove generated types and formats for Microsoft.PowerShell.Diagnostics

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1218]
In Full, the following files are expected in $PSHOME

TypesToProcess="GetEvent.types.ps1xml"
FormatsToProcess="Event.format.ps1xml","Diagnostics.format.ps1xml" 

In Core, ~~they are apparently expected in the module directory (like any other module).~~ they are also expected in $PSHOME, and Nano PS depends on the internal C# `GetEvent_Types_Ps1Xml.generated.cs` and `Event_Format_ps1xml.cs` to handle them.

Normally this isn't a big deal, but the engine currently knows about these files if they are in $PSHOME and uses some internal C#.  That code should probably be removed and we stick with the Core way of doing things, but that requires manifest changes on Full and Core.

**Comment by joeyaiello** [comment]
@daxian-dbw so we need to continue to ship the .ps1xml files on Windows PowerShell, and PowerShell Core is already fine? If yes, you can close. Thanks!

**Comment by daxian-dbw** [comment]
The comments here suggest that the code in `GetEvent_Types_Ps1Xml.generated.cs` and `Event_Format_ps1xml.cs` should be removed from Github powershell core.

**Comment by lzybkr** [comment]
@daxian-dbw - that looks right to me - the ps1xml files for those modules is correctly in the module folder, so I'd just remove the generated C# version.

**Comment by joeyaiello** [comment]
In that case, we should do this in 6.0.0.

**Comment by joeyaiello** [comment]
So just to clarify, this means "remove the generated code for just `Microsoft.PowerShell.Diagnostics`.

**Comment by joeyaiello** [comment]
The question is whether this matters right now. Adding to `Review - Committee` so we can ask @lzybkr and @BrucePay about it Wednesday. I suspect that this is a minor code cleanup that we can punt out.

**Comment by SteveL-MSFT** [comment]
After discussion with @PowerShell/powershell-committee we can defer this to when we actually move the Diagnostics module out

**Comment by iSazonov** [comment]
To load ps1xml.cs files out of engine we need to have a new public API for this.
Could MSFT team implement this? It would help decoupling modules (HelpSystem too).

**Comment by jszabo98** [comment]
So in powershell 5, event.format.ps1xml is completely ignored because it's defined in c#?

**Comment by iSazonov** [comment]
@jszabo98 Yes, for better startup time all xml files was converted to C#.

**Comment by doctordns** [comment]
Is this still an isue??

**Comment by daxian-dbw** [comment]
It is still an issue if we want to eventually ship the `Microsoft.PowerShell.Diagnostics` module separately.
