### ISSUE TITLE
windows and font grow larger and flash

### ISSUE THREAD

**Issue by KagamigawaMeguri** [PowerShell/PowerShell#12180]
# Steps to reproduce
input any code，even ENTER

# Expected behavior
![1](https://user-images.githubusercontent.com/35628460/77296160-2aa51900-6d22-11ea-8869-70bcb133da1b.png)
while I input any code，the window and font will suddenly grow larger and flash, like following img
![2](https://user-images.githubusercontent.com/35628460/77296164-2c6edc80-6d22-11ea-9848-3631c7fe51c6.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Other than the column of times to the right being missing from the second screen shot, there is no obvious difference between the two. Can you describe your problem and under what conditions it occurs in more detail? Are you using a regular console window or a different terminal emulator?

**Comment by KagamigawaMeguri** [comment]
> Other than the column of times to the right being missing from the second screen shot, there is no obvious difference between the two. Can you describe your problem and under what conditions it occurs in more detail? Are you using a regular console window or a different terminal emulator?

thanks for your reply.
i recorded a video, like this.
https://drive.google.com/open?id=1emfWBLjBTKAWhqIHoQIrc5GzLD62qfKY
thanks again

**Comment by KagamigawaMeguri** [comment]
> Other than the column of times to the right being missing from the second screen shot, there is no obvious difference between the two. Can you describe your problem and under what conditions it occurs in more detail? Are you using a regular console window or a different terminal emulator?

thanks for your reply.
i recorded a video, like this:
https://drive.google.com/open?id=1emfWBLjBTKAWhqIHoQIrc5GzLD62qfKY
thanks again.

**Comment by mklement0** [comment]
That looks strange indeed. Does it still happen if you remove PSReadLine first 
(`Remove-Module PSReadLine`)? Does your `prompt` function contain unusual commands (`$function:prompt`)?

**Comment by KagamigawaMeguri** [comment]
> That looks strange indeed. Does it still happen if you remove PSReadLine first
> (`Remove-Module PSReadLine`)? Does your `prompt` function contain unusual commands (`$function:prompt`)?

!!!thanks!
when i try Remove-Module PSReadLine, It works, then i realized that the font is wrong.
i change the font, everything is fine!.
Thanks again!!!!!!!!!!
