### ISSUE TITLE
Get-FileHash add parameter to feed in an HashAlgorithm Object

### ISSUE THREAD

**Issue by Kriegel** [PowerShell/PowerShell#12196]
The .NET build in Hash Algorithms are not the fastest.
In Times where Datasize is rising we need VERY fast Hash Algorithms.

There are many .NET libraries out there which creating Hash Algorithms  Classe which are following the .NET interface Standards.

So it can be easy to feed in a HashAlgorithm Object to the Get-FileHash cmdlet.

For Example I am using the very fast xxHash from this Repository:
https://github.com/brandondahler/Data.HashFunction
Pseudo example code ahead!

```powershell
# adding .NET core type for the xxHash algorithm
Add-Type -Path 'A:\PowerShell-Code\HashFunction\Data.HashFunction\netstandard1.1\OpenSource.Data.HashFunction.xxHash.dll'

# creating xxHash instance
$xxHash = [OpenSource.Data.HashFunction.xxHash.xxHashFactory]::Instance.Create()

# using Get-Filehash wit xxHash algorithm instance
Get-FileHash -Path C:\temp\testfile.txt -InputHash $xxHash
```

**Comment by iSazonov** [comment]
.Net Runtime exposes _cryptography strong implementation_. PowerShell uses the implementation so that users can trust it in any scenario. Any performance issues with the implementation should be discussed and addressed in .Net Runtime repo.

If users have scenarios where they do not need cryptography strong implementation but higher performance they can install and use other libraries.

PowerShell could get benefits from such library including it in engine only if there is _real and important business scenario_.

**Comment by Kriegel** [comment]
To compare backed up files, source and destination, or  to find duplicates there is no need for cryptographic strong algorithms.
Because they are cryptographic strong they are slower than the non cryptographic strong algorithms.

My .NET skills are not so good ...
So I currently write an PowerShell Module to implement these non cryptographic strong algorithms.

I Like the idea to widen the usecase of an cmdlet with objects wich support the standard interface
in addition to extend PowerShell with Modules so we cann extend it with standardized Objects.

**Comment by iSazonov** [comment]
> So I currently write an PowerShell Module to implement these non cryptographic strong algorithms.

Current workflow for extending PowerShell is to publish new module to PowerShellGet site and look uses. If there will be popular scenario the module or cmdlet can be included in the repo.

> I Like the idea to widen the usecase of an cmdlet with objects wich support the standard interface
in addition to extend PowerShell with Modules so we can extend it with standardized Objects.

I have a concern that we can not dynamically load non-trusted third-party library in core cmdlets.

> To compare backed up files, source and destination, or to find duplicates there is no need for cryptographic strong algorithms.

Here is two scenario. (1) We could discuss this in another issue. We have an issue Copy-Item to get robocopy features. In the case we have no need to have many hash algorithms - just one. (2) Compare files. Again another issue. We could discuss Compare-File, as raw byte by byte, as text, as hash. (3) We could discuss in another issue enhancement of Get-Item to add a hash property in FileInfo.

**Comment by Kriegel** [comment]
To use Copy-Item to compare or Hash files, follows not the monadology.
A seperate cmdlet is needed here.

With support of only cryptography strong algorithms I think the use cases of Get-FileHash are intended to only support a 1 main usecase.
Checking against malicious changes.
Data Integrity is only a byproduct. 

With support for non cryptography strong algorithms Get-FileHash can be used for that in a faster manner.

> I have a concern that we can not dynamically load non-trusted third-party library in core cmdlets.
I see that point. But cannot see any security issue, compared to loading and usinf any other .NET dll in PowerShell.  

@iSazonov I appreciate your inputs. Thank you. *hug*
Please let this issue hang around a while to catch other voices.

**Comment by iSazonov** [comment]
> To use Copy-Item to compare or Hash files, follows not the monadology.
A seperate cmdlet is needed here.

We could optimize `Copy-Item -ToSession` scenario to avoid coping files to remote system.
You can open new issue to discuss this.

RoboCopy tracking issue #2581

> With support of only cryptography strong algorithms I think the use cases of Get-FileHash are intended to only support a 1 main usecase.
Checking against malicious changes.
Data Integrity is only a byproduct.

No. It is addressed _all_ scenarios in way which users can trust to.
Specific scenarios could be optimized for performance. Such scenarios need to be clearly identified and tested to avoid functional and security issues.

> Please let this issue hang around a while to catch other voices.

If you want a progress don't think only about Get-FileHash - think about _specific scenarios_ like I mentioned (and others) and open tracking issues to discuss possible solutions in which you are interested.
