### ISSUE TITLE
Microsoft RPM repository for CentOS does not contain Powershell 7 stable

### ISSUE THREAD

**Issue by nielsvbrecht** [PowerShell/PowerShell#12193]
I am creating a RedHat Enterprise Linux and CentOS image on Azure in which I am installing Powershell 7 from the Microsoft RPM repository. 
However Powershell 7 stable is not available for CentOS (7), while it is in the RHEL 7 repository. 

Why is there a difference and can Powershell 7 stable be added to the CentOS repository?

CentOS: https://packages.microsoft.com/centos/7/prod/
RHEL: https://packages.microsoft.com/rhel/7/prod/

**Comment by TravisEz13** [comment]
https://packages.microsoft.com/rhel/7/prod/powershell-7.0.0-1.rhel.7.x86_64.rpm

We don't publish to centos to match the instructions of .NET Core varying would break people.

Please use one of the repo's listed in the install instructions.
