### ISSUE TITLE
Provide Powershell to Ubuntu WITHOUT SNAP

### ISSUE THREAD

**Issue by Grimeton** [PowerShell/PowerShell#12198]
Hello,

when running Powershell in a docker container it becomes really problematic installing it via the snap package. Snapd comes with so many dependencies that it's pointless to even start using it in a container. 

What is the problem of providing an Ubuntu 19.10 dpkg file containing Powershell? Maybe I can help...

Right now, installing Powershell in an Ubuntu 19.10 container is basically impossible without dragging in tons of unnecessary stuff...

Thanks!

KR,

G.

**Comment by mburszley** [comment]
I'm not sure I understand your complaint.  The package is available for Ubuntu as a .deb: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7

Is this incompatible with 19?

**Comment by Grimeton** [comment]
Hello,

the later releases, as visible on the link that you posted, are only available via snap. When using an lts build on 19.10 you have "too tight" dependencies. The package depends on libssl1.0.0 while on 19.10 you have libssl1.1. 

You can force-install the package and then install the necessary dependencies with the versions available on 19.10 and it works, but nevertheless it errors out when you try to go down the usual road.

Also powershell is not part of the microsoft repository for 19.10, so there's not apt-get install powershell.

KR,

G.
