### ISSUE TITLE
Feature Request: Allow to change default variable scope

### ISSUE THREAD

**Issue by Tragen** [PowerShell/PowerShell#12199]
Currently, the default variable scope allows variables to be accessed in child scopes.
I always had a lot of problems with this in bigger scripts.
It would be nice to have an option, e.g. at the beginning of a script, which tells PS
that the default scope should be private for this script.

**Comment by mburszley** [comment]
That is the purpose of declaring your variables with scope, .e.g, `$private:myVar`

**Comment by vexx32** [comment]
Correct. I believe the request is to have a way in the script to set such a scope to be the _default_ for all variables in that scope, so that when creating an unscoped variable it is automatically assigned the `private` scope.

**Comment by Tragen** [comment]
Yes, exactly. When you have very long scripts, it's very ugly to prefix all variables with `private`

**Comment by mklement0** [comment]
PowerShell's dynamic scoping is a problem in other areas too, notably with not wanting `Set-StrictMode` settings to apply to child scopes ((third-party) code is often written with the assumption that no strict mode is in effect, and one going into effect in the caller's scope can break the code - see the (languishing) lexical strict-mode RFC at https://github.com/PowerShell/PowerShell-RFC/issues/7

For more robust code, lexically scoped variables, or their emulation with the `$private:` scope modifier, but _without the latter's ceremony_ would indeed be helpful, but requires an _opt-in_ mechanism so as not to break backward compatibility.

Conceivably, a new `using` statement could using be introduced that makes all local variables private _by default_, along the lines of `using private variables`.

**Comment by vexx32** [comment]
Not a bad suggestion, @mklement0. For myself, I was imagining introducing a preference variable; e.g., `$PSDefaultVariableScope = 'Private'`

**Comment by mklement0** [comment]
The problem with preference variables is again their dynamic scoping - child scopes that weren't written with all-private variables in mind could break.

I suggested `using` under the mistaken assumption was that  they are lexically scoped to the enclosing script / script module, but as it turns out they're _not_, not even in the `using namespace` case.

**Comment by Tragen** [comment]
This isn't answered yet

**Comment by fabienfl-orc** [comment]
@iSazonov What is the answered resolution ?

**Comment by iSazonov** [comment]
@fabienfl-orc PowerShell is well-designed language for scripting. :-) Later classes was introduced in PowerShell to address "programming" scenarios.
