### ISSUE TITLE
Powershell 7 types "@" in console when Fn key pressed

### ISSUE THREAD

**Issue by uldisv** [PowerShell/PowerShell#12195]
# Steps to reproduce
In powershell 7.0.0 on Windows 10 Pro 1909. Hardware: Msi GE72 6QF Notebook.

1) Open powershell 7
2) Press "Fn" key.

# Expected behavior
No echo in powershell - because it's a dead key, next key will determine behaviour.

# Actual behavior
In powershell "@" symbol is printed.
If next key is pressed - Fn functionality works as expected, just every press leaves new "@" in the console.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by vexx32** [comment]
@uldisv I'd recommend seeing if this reproduces without PSReadLine imported. If not, you may want to report it to the https://github.com/PowerShell/PSReadLine repository instead. 🙂

**Comment by uldisv** [comment]
> @uldisv I'd recommend seeing if this reproduces without PSReadLine imported. If not, you may want to report it to the https://github.com/PowerShell/PSReadLine repository instead. 🙂
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/11524380?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[PowerShell/PSReadLine](https://github.com/PowerShell/PSReadLine)**A bash inspired readline implementation for PowerShell - PowerShell/PSReadLine

You're right.
It's a PSreadline module problem. Removed module - everything works like a charm!
