### ISSUE TITLE
PowerShell installed as a .NET global tool cannot invoke its own CLI on macOS

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12205]
When PowerShell is installed as a .NET global tool, it prepends its own `$PSHOME` folder to `$env:PATH`.

However, on macOS `$PSHOME` contains an _incompatible_ `pwsh` binary that is for _Linux_.

Therefore, from within an existing session, invoking `pwsh` (by mere file _name_) unexpectedly fails.

# Steps to reproduce

```powershell
# Install PowerShell as a .NET global tool, to ~/.dotnet/tools
dotnet tool install powershell -g

# Invoke it, and try to re-invoke its own CLI.
~/.dotnet/tools/pwsh -noprofile -c 'pwsh -noprofile -c write-output hi' | Should -Be 'hi'
```

# Expected behavior

The test should succeed.

# Actual behavior

The test fails, due to incompatible binary being invoked:

```none
Expected 'hi', but got @('ResourceUnavailable: Program 'pwsh' failed to run: Exec format errorAt line:1 char:1' ...
```

# Environment data

```none
PowerShell Core v7.0.0 (7.0.0) on macOS 10.15.3
```

**Comment by mklement0** [comment]
Thanks for labeling, @SteveL-MSFT; please note that this problem will likely only affect people who use the .NET global tool version _interactively_.

The likelier use is for CI (automation), and for that #11747 is the much more serious bug (as yet not classified as a bug): something primarily used as a CLI not handling argument parsing properly is highly problematic.

#12176 too is unequivocally a not-yet-classified-as-such bug, though less impactful.

**Comment by TravisEz13** [comment]
I verified this behavior on 7.0.0 on macOS 10.15.4

**Comment by albigi** [comment]
this is still a problem on macOS 11.1 and it can be quite unpleasant when deploying xplat scripts. I would expect that invoking a child pwsh would work under every circumstance

**Comment by kkshinkai** [comment]
Any progress on this?

#11141 puts `$PSHOME` at the front of `$PATH`, so this problem becomes unsolvable under macOS. Perhaps we should put `$PSHOME` at the end of the `$PATH`.

**Comment by ins0mniaque** [comment]
This is still a problem on macOS 12.2.1 (arm64).

I can confirm that having $PSHOME in front of $PATH (#11141) makes it impossible to fix using $Env:Path under macOS.

As a workaround, I added this to my PowerShell profile:
```
Set-Alias pwsh "~/.dotnet/tools/pwsh"
```

**Comment by StevenBucher98** [comment]
Looks like possibly another issue reported around this bug, #18139

**Comment by dlnash18** [comment]
@StevenBucher98: Thanks for connecting the dots. Yep, looks like the same bug to me. Knowing about [#11141](https://github.com/PowerShell/PowerShell/pull/11141) explains why changing $PATH didn't fix the problem for me. The workaround I mentioned in my bug is very simple:

```
cd $PSHOME
mv pwsh pwsh.elf
ln -s ../../../../../../../../../../../.dotnet/tools/pwsh pwsh
```

It fixes this bug as well, unsurprisingly. I've been running in this state since I posted my bug and have yet to notice any adverse effects.

**Comment by lukket** [comment]
It's now 2023, macOS 13.4, PowerShell 7.3.4 and this is still an issue...

Thanks for the workaround @dlnash18.
