### ISSUE TITLE
copy-item with multiple destination 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12200]
the parameter -destination is <string> its better to change to <string[]>

EXAMPLE:
```

# copy 1.txt and 2.txt in d:\foo and e:\bar\lol
copy-item -Path c:\1.txt,C:\Users\2.txt -Destination d:\foo\,e:\bar\lol\
```

**Comment by vexx32** [comment]
I don't see a lot of use for this myself, but I also don't really see a need to disallow this behaviour. Seems like a pretty straightforward addition if we'd like to take it. 

Copying items to multiple locations is certainly something a decent number of folks would have a use for, I'd think.

**Comment by mklement0** [comment]
If we do this, we'd need to make clear that _all_ input items are copied to _each_ destination path (user could have the expectation that copying happens _in pairs_ (`1.txt` only to `foo`, `2.txt` only to `bar`)).

A fairly low-ceremony way to do this with the current features is to use delay-bind script block:

```powershell
'd:\foo\', 'e:\bar\lol\' | copy-item -Path c:\1.txt,C:\Users\2.txt -Destination { $_ }
```
