### ISSUE TITLE
Incorrect command-line parsing when escaping the " character

### ISSUE THREAD

**Issue by TheXDS** [PowerShell/PowerShell#12216]
At the command line, if an application is given a set of arguments while trying to escape a ```"``` character (by doing ```\"```, which should be OK since the ```"``` char is not valid in a file path anyway), powershell will attempt to reparse the command passing out incorrect data to the OS.
# Steps to reproduce
### Case 1
```powershell
.\someapp.exe \"test test\" 
```
### Case 2
```powershell
.\someapp.exe "\"test" "test\""
```
# Expected behavior
- Powershell displaying an error about invalid character in path.
- Passing the command line as-is.
- If using the ```\``` character to escape the ```"``` could be considered legal, then for both cases, application command line should be passed to the OS as:
```
.\someapp.exe "\"test" "test\""
```
powershell should enclose the escaped ```"test``` and ```test"``` in quotes so the app may correctly assume that each escaped ```"``` is part of each literal.

# Actual behavior
Powershell passes to the OS:
### Case 1
```
.\someapp.exe "\test test\\"
```
### Case 2
```
.\comeapp.exe \ "test test\\"
```

# Environment data
```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Thanks for your report! It is dup #1995.
