### ISSUE TITLE
MSI installer should provide option to set PS7 as default WinRM endpoint

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#12212]
# Summary of the new feature/enhancement

As an admin, I want to install PS 7 using the MSI in such a way that it becomes the default WinRM remoting endpoint on that server machine for all incoming WinRM-based PowerShell Remoting clients.

# Proposed technical implementation details (optional)

This does need to be discussed in more detail (possibly as an RFC), based on the relative consensus reached on [my comment](https://github.com/PowerShell/PowerShell/issues/11616#issuecomment-594119801) in #11616, we should offer a sub-option of the "Enable PowerShell remoting" MSI option that also makes PS7 the default remoting endpoint (i.e. `microsoft.powershell`) and does something to preserve the existing Windows PS endpoints if they exist (e.g. migrating them to `microsoft.powershell.5`). 

As a pre-req to this, it might be useful to have scripts in PSHome that do some of this work, and that provide reversability of the configuration, akin to what @jaykul proposes [here](https://github.com/PowerShell/PowerShell/issues/11616#issuecomment-598432849).

**Comment by doctordns** [comment]
Any progress on this?

**Comment by gogbg** [comment]
Any updates on this?
