### ISSUE TITLE
Powershell version relation to .Net Standard, Core and/or framework versions

### ISSUE THREAD

**Issue by viralmodi** [PowerShell/PowerShell#12215]
I have spend quite a lot of time looking for answer to this question but could not find it. While this might not be the correct forum for this type of question but I couldn't find any other forum to ask this. I really need some help here since I couldn't even find an answer on reading Microsoft Powershell docs.
I want to know the relation between Powershell versions (windows powershell and powershell core) and .Net Standard (Core and Framework) versions.
As a concrete example, If I have a powershell cmdlet built for target framework .Net Standard 2.0, how do I find which powershell versions (both windows powershell and powershell core), will it work on?
My understanding was as long as .Net Standard 2.0 or higher based implementation of .Net Core or .Net framework is installed on users machine, it doesn't matter which powershell version the user uses. The cmdlet should work. But then, users don't explicitly install these .NET versions on their machines. They are installed by default on Windows or as part of powershell core(?) on cross platform OSes. Can someone please help understand this relation and answer my question?

**Comment by iSazonov** [comment]
> They are installed by default on Windows or as part of powershell core(?) on cross platform OSes.

First look about "self-contained" and " runtime-dependent" .Net Core applications
https://docs.microsoft.com/en-us/dotnet/core/deploying/

**Comment by SeeminglyScience** [comment]
In addition to what @iSazonov mentioned, Windows PowerShell is always runtime dependent.  For a netstandard2.0 library to work within Windows PowerShell, the user will need at least net framework 4.7.1 installed (or I think 4.6.2 if you ship the netfx version of the netstandard.dll shim with your library)

More simply put, if you target netstandard2.0 it will work:

1. In Windows PowerShell if net framework 4.7.1 is installed on the machine
1. In PowerShell Core/PowerShell 7+.  Core can be runtime dependent too but any version should be compatible with netstandard2.0 iirc

**Comment by iSazonov** [comment]
Also see https://github.com/PowerShell/PowerShell/issues/6475#issuecomment-375798893
https://docs.microsoft.com/en-us/powershell/scripting/learn/writing-portable-modules?view=powershell-7

**Comment by SteveL-MSFT** [comment]
The doc that @iSazonov linked to is expected to answer this question.  If there's anything unclear or missing, please open as a doc bug in https://github.com/MicrosoftDocs/PowerShell-Docs

**Comment by viralmodi** [comment]
Thanks folks. I do have some follow on questions but first will read the docs pointed by you and see if they get answered there. Will respond back after that.

**Comment by iSazonov** [comment]
@viralmodi If you have an interest please document and share you experience.

**Comment by viralmodi** [comment]
@iSazonov @SeeminglyScience @SteveL-MSFT 
I read the links and while they were useful; they couldn't answer all my questions. Here are my follow-on questions. Let's say I have a powershell cmdlet with target framework of .NET Standard 2.0 (run-time dependent and not self-contained)
1) Will it work with Windows powershell 2.0, 3.0, 4.0, 5.0, 5.1?
2) Will it work with Powershell core versions 5.0, 6.0 and 7.0?
3) If I have powershell 3.0 installed which as per this link (https://docs.microsoft.com/en-us/powershell/scripting/install/windows-powershell-system-requirements?view=powershell-7) requires .NET framework 4, will my cmdlet work on it?
4) Same condition as #3 question above but let's say if I externally install .NET framework 4.6.1 (or 4.7.x) from MSFT website on my machine, will it work with powershell 3.0 now?

**Comment by SeeminglyScience** [comment]
> Let's say I have a powershell cmdlet with target framework of .NET Standard 2.0 (run-time dependent and not self-contained)

The choice of run time dependent vs self contained is up to the host application, which in this case is PowerShell. This would only be your decision if you were running outside of PowerShell, or if you were hosting it.  I'm being a little pedantic here admittedly, but it can be an important distinction.

> 1. Will it work with Windows powershell 2.0, 3.0, 4.0, 5.0, 5.1?

Not 2.0, that specifically requires a much older CLR version which is only supported by net framework 3.5 and below.  Everything else, depends on if netfx 4.7.1 (or 4.6.2 if you ship the shim) is installed on the target machine. That said the version of `PowerShellStandard.Library` built for 3.0 hasn't seen a lot of love (or adoption).  YMMV for anything under 5.1.

> 2. Will it work with Powershell core versions 5.0, 6.0 and 7.0?

Definitely 6.0 and 7.0.  If by 5.0 you mean the version of PS core that was in nano I'm not sure, but probably not. iirc that had a really early build of .NET core which almost definitely wasn't netstandard2.0 compliant.  Is that still available through something? cc @SteveL-MSFT 

> 3. If I have powershell 3.0 installed which as per this link (https://docs.microsoft.com/en-us/powershell/scripting/install/windows-powershell-system-requirements?view=powershell-7) requires .NET framework 4, will my cmdlet work on it?
> 4. Same condition as #3 question above but let's say if I externally install .NET framework 4.6.1 (or 4.7.x) from MSFT website on my machine, will it work with powershell 3.0 now?
> 5. #4 question above is to understand that if it even matters what version of powershell I have to run my cmdlet. Does the only thing that matters is if I have a .NET Core or .Net Framework corresponding to .NET standard 2.0 installed on my client machine?

See response to #1 for answers to above.

**Comment by viralmodi** [comment]
Thanks @SeeminglyScience That answers a bunch of my questions. While you have mentioned that answers to my other questions is same as what you mentioned in #1. 
I want an explicit answer to these ones:
1) Powershell cmdlet targetted for .NET Standard 2.0 being run in Windows Powershell 5.0 (or 4.0) - will it work? I read your answer to this as YMMV but why is it YMMV is what I don't understand.
2) Powershell cmdlet targetted for .NET Standard 2.0 being run in Windows Powershell 5.0 (or 4.0) and let's say I have .NET Framework 4.7.1 separately installed (I don't know if this scenario makes sense or is possible) - will it work?
The above questions only reinforce some confusion in my understanding about relation between Powershell version, Cmdlet target framework and .NET version installed on my client machine. Perhaps, a re-take on my 5th question above which I don't see an answer to or may be, I couldn't infer from your answers, might better help my understanding. Repeating again:
5) if it even matters what version of powershell I am running my cmdlet on. Does the only thing that matters is if I have a .NET Core or .Net Framework corresponding to .NET standard 2.0 installed on my client machine? i.e. can I direct my host application for my cmdlet, Powershell in this case, to use any installed .Net Framework on my client machine?
Thanks for patiently answering all my questions and that too pretty fast.

**Comment by iSazonov** [comment]
> will my cmdlet work on it?

"Will" says that you plan new project. Strategic recommendations from .Net Core team is to start new project only on .Net Core.

You can find .Net Standard compatibility table in docs https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by viralmodi** [comment]
@iSazonov  Yes that is correct. It's a new project I am working on.
Based on MSFT and Azure doc reading, I realized that its better to target .NET Standard compared to .NET framework or .NET Core if the product is targeted towards Windows and other OSes. 
I had referred that table earlier as well. It had helped me understand the relation between .NET standard, .NET Core and .NET framework.
I am still looking to get answers to my questions above. This is to get better grasp on relation between Powershell version, .NET version/s installed on the machine and my product's target framework. Can you please answer my questions above?

**Comment by iSazonov** [comment]
MSFT supports only Windows PowerShell 5.1 (maybe still 5.0) and it is only _servicing_ support (critical and security fixes). The same is true for .Net Framework - 4.7 and 4.8 has only servicing support.
If you do not have to support old versions like Windows 7 you have no need to invest in compatibility with .Net Framework.
Also PowerShell Core has not compatibility with Windows PowerShell 2.0 and 3.0 at all.

**Comment by viralmodi** [comment]
In that case, what is the latest version of Powershell that can be used on Windows? Can we use Powershell 6.0/7.0 based on .NET Core implementation on windows as well?

**Comment by iSazonov** [comment]
Current PowerShell version is 7.0. It is LTS (supported as .Net Core 3.1).
(6.2 is still supported some months)

So if your project is targeted to .Net Standard 2.0 and reference PowerShell Standard library your application will works on all supported systems (Windows and Unix-s) and Windows PowerShell 5 too.

**Comment by viralmodi** [comment]
@iSazonov Thanks.
At this point, I do not have information on whether we need to support old versions. But I am going to go with support for Windows Powershell 5.1 (with .NET Framework 4.7.2 installed), Powershell Core 6.0+ which based on this thread will work with target framework .NET Standard 2.0 for my project.

**Comment by iSazonov** [comment]
@viralmodi On top of the GitHub page you can find "Used by" button - this helps you to find sample projects.

**Comment by viralmodi** [comment]
Sure. Thanks. This discussion was very helpful
