### ISSUE TITLE
add auto-suggestions

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12224]
in other shell like zsh (oh-my zsh) and fish it exist one awesome feature auto-suggestions
its great if powershell implement this feature:

![peyTN](https://user-images.githubusercontent.com/36144546/77847136-a0b8de00-716f-11ea-9fed-46dd07807e5e.png)

**Comment by vexx32** [comment]
@daxian-dbw has been looking at making some improvements to [PSReadLine](https://github.com/PowerShell/PSReadLine) which will offer this kind of functionality. 

If you have suggestions on specific details on this (or want to try out the alpha build of the module with this feature in place), I'd highly recommend you comment on the [relevant issue](https://github.com/PowerShell/PSReadLine/issues/687) in that repository. 😊 

For the most part, PowerShell doesn't handle completions on its own; the larger part of that work is done in PSReadLine itself. 🙂

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/687
