### ISSUE TITLE
Feature Request - Out-GridView, define/pass "default" filters through Parameters

### ISSUE THREAD

**Issue by PsychoData** [PowerShell/PowerShell#12228]
# Add parameters to enable you to pass default filters to Out-GridView windows for when they are first shown. 

For example, if I was writing a process to look for processes of some sort, and I wanted to show a simple GUI to say which process to kill. 

I could show them a list of all processes, but it would be a nice feature if I could show them just a list of processes under their username/login session, predefined as a Criteria Filter

# Proposed technical implementation details (optional)

With the current/old way I could filter it before I push it to Out-GridView, but if they wanted to find a process from another user, it wouldn't work or would have to be handled more completely in code. 

The result would let you filter further, but not go backwards. 
![image](https://user-images.githubusercontent.com/3719116/77948778-ebcc1180-7293-11ea-8b4f-43ac566c6c5f.png)

Where, if there was an option to pre-fill the form, we could show it to the user with Quick Search predefined like this
![image](https://user-images.githubusercontent.com/3719116/77948940-2df55300-7294-11ea-82bb-d4afff65ee55.png)

or, even better, pre-define the Criteria directly so that they could still easily use the quick search
![image](https://user-images.githubusercontent.com/3719116/77949078-5c732e00-7294-11ea-8766-ea0d58a40d74.png)

If we could add a -DefaultFilter and/or -Criteria option, that might be sufficient. 
Perhaps it could even support the same FilterScript as Where-Object? 
If there was a way we could just pass `Get-Process -IncludeUsername | Out-GridView -FilterScript {$_.Username -like "*Administrator"} ` and it predefined the Criteria from that, ending up looking like my final screenshot, I think that would be my Ideal implementation

**Comment by iSazonov** [comment]
@PsychoData The cmdlet was added to PowerShell Core only for backward compatibility. The code is frozen in the repo. 
All new work will be in https://github.com/PowerShell/GraphicalTools repo. Please move your proposal and discuss there.

**Comment by PsychoData** [comment]
New issue created there https://github.com/PowerShell/GraphicalTools/issues/78
