### ISSUE TITLE
New-PSDrive works not with WebDav

### ISSUE THREAD

**Issue by icemansven** [PowerShell/PowerShell#12231]
# Steps to reproduce

```
$pass="xxXXxxx"|ConvertTo-SecureString -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PsCredential('p1122334455',$pass)
New-PSDrive -Name WebDavShare -PSProvider FileSystem -Root "\\subd.domain.tld@81\DavWWWRoot" -Credential $Cred


```

# Expected behavior

```
Get-ChildItem WebDavShare:\\ gives me the files from the Webdav folder.

```

# Actual behavior
```
If pwsh.exe runs in user space it mounts to local C: drive, if it runs in Administrator space, I get 

> New-PSDrive: The specified drive root "\\subd.domain.tld@81\DavWWWRoot\" either does not exist, or it is not a folder.

It works in Powershell 5.1
```

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by thunder7553** [comment]
I do have the same problem with PowerShell 7.1 - is there any other way (workaround) to execute files on WebDav in pwsh/linux, without downloading it first? I do want to have the signature check for remote scripts

**Comment by avmaksimov** [comment]
I have the same problem so I have to return to PS 5 for the same situation :(. Windows Server 2019 Standard 64 bit,

**Comment by iSazonov** [comment]
I can mount and access a test WebDav site:
![image](https://user-images.githubusercontent.com/22290914/143734989-f1bd5c2b-2bf3-4834-aede-760145155669.png)

**Comment by avmaksimov** [comment]
> I can mount and access a test WebDav site: ![image](https://user-images.githubusercontent.com/22290914/143734989-f1bd5c2b-2bf3-4834-aede-760145155669.png)

But for me: I have another result:
![Screenshot 2021-11-28 123228](https://user-images.githubusercontent.com/2793938/143762160-aae523c2-3543-4c64-a5bf-dd13f410f0ed.jpg)

Also I tested with wrong folder name and see the error: "New-PSDrive: The specified drive root "\\webdav.yandex.ru@SSL\Archives222" either does not exist, or it is not a folder.".

**Comment by avmaksimov** [comment]
![Screenshot 2021-11-28 123228](https://user-images.githubusercontent.com/2793938/143763108-609e55ce-47b6-40b1-8810-20da3943fdd5.jpg)
The expected behavior.

**Comment by iSazonov** [comment]
I can not connect to yandex neither in pwsh nor in Windows PowerShell.

**Comment by avmaksimov** [comment]
> I can not connect to yandex neither in pwsh nor in Windows PowerShell.

May be you can provide test access to your Webdav site to check this situation. May be it depends on WebDav sites, nor PS version.

But I say again that there is no problem with Yandex in PS 5.

**Comment by avmaksimov** [comment]
I see the same problem with Mail.ru (VK) WebDav. BTW: Path to connect "\\webdav.cloud.mail.ru@SSL\DavWWWRoot".

**Comment by fornax-a** [comment]
I too have the same issue, this time with SharePoint Online.

Likely unrelated, but perhaps still worth mentioning - The alternative `net use` approach maps the drive successfully, but then I get weird "_Illegal characters in path. (Parameter 'path')_" errors when piping files via `Get-ChildItem` to  `Get-Content`.    

Meanwhile file explorer has no problem traversing folders and opening files.

**Comment by fornax-a** [comment]
> Likely unrelated, but perhaps still worth mentioning - The alternative `net use` approach maps the drive successfully, but then I get weird "Illegal characters in path. (Parameter 'path')" errors when piping files via Get-ChildItem to Get-Content.

Just to add a little more about this issue, it seems we are dealing with NUL terminations.

![image](https://user-images.githubusercontent.com/94235837/146226653-15ed65a6-f102-4fd3-8227-8876214919ea.png)

Strip that character and things work.

![image](https://user-images.githubusercontent.com/94235837/146227783-9eae6802-99d0-4565-ba53-2248082b7281.png)

Again this could have nothing to do with the originally reported issue, then again it could be related (even if only a symptom).

**Comment by iSazonov** [comment]
> And PowerShell will convert to string itself which it does in many scenarios 

I guess it comes from .Net. You could report the issue in .Net Runtime repository.
