### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by Alaka-Rathnakar** [PowerShell/PowerShell#12247]
The command---- >  Get-Command -Module HardwareCertification  is not able to list the HLK Automation tool cmdlets in the powershell with latest version which is required for execution of test cases. The command is not working in version of  HCK -2.1 and HLK -1607 . The same command works with HLK-1903 and HLK-1809 version.

Expected results: It should display the following cmdlets: 
Export-HwCertTestCollectionToXml
Import-HwCertTestCollectionFromXml
Merge-HwCertTestCollectionFromPackage
Merge-HwCertTestCollectionFromXml
New-HwCertProjectDefinitionFile
New-HwCertTestCollection
New-HwCertTestCollectionExcelReport
-
Actual results: It is not displaying anything.
-

**Comment by iSazonov** [comment]
If you load the module in PowerShell 7.0 and the module doesn't work please report the issue to the module owner.
