### ISSUE TITLE
MenuComplete does not highlight selected option on WSL 2

### ISSUE THREAD

**Issue by HymanZHAN** [PowerShell/PowerShell#12244]
# Steps to reproduce

On WSL, go to a random directory, type `cd` and hit Tab.

# Expected behavior

![image](https://user-images.githubusercontent.com/26806995/78275146-38575d00-74df-11ea-88e1-debb7d7f6a26.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/26806995/78275264-5cb33980-74df-11ea-93ab-7f95c9827b7a.png)

# Environment data

```shell
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@HymanZHAN this is about a PSReadLine feature; MenuComplete is not handled by PowerShell itself. Could you file this over in the [PSReadLine](/PowerShell/PSReadLine) repository, please? 🙂

**Comment by HymanZHAN** [comment]
Ah OK. Sorry I didn't realize that. Thanks for the redirection.
