### ISSUE TITLE
Enable PsDscRunAsCredential to run without SeInteractiveLogonRight

### ISSUE THREAD

**Issue by craig-martin** [PowerShell/PowerShell#12241]
# Summary of the new feature/enhancement

Requiring the SeInteractiveLogonRight privilege blocks me from using DSC because my service accounts are denied this privilege, which is a good security practice.

When trying to use my service account  I get this error:
[Logon failure: the user has not been granted the requested logon type at this computer](https://github.com/dsccommunity/SqlServerDsc/issues/1416)

The scenario requires network access because the DSC resource needs to do things like validate objects in Active Directory.

# Proposed technical implementation details
It would be great if this could be solved, here are some options:
## Allow DSC to use a Group Managed Service Account
Details here: [Group Managed Service Accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/group-managed-service-accounts-overview)

## Enable PsDscRunAsCredential to run without SeInteractiveLogonRight
Not sure why DSC requires this privilege, but it would be nice to allow DSC to not require it.

**Comment by powertim** [comment]
No news on this ? It  seems essential to change this behaviour! All security recommendations like STIG or CIS say that service account should not have the SeInteractiveLogonRight.
