### ISSUE TITLE
update-help does nothing on WSL

### ISSUE THREAD

**Issue by vim-diesel** [PowerShell/PowerShell#12257]
# Steps to reproduce

```powershell
update-help
```

# Expected behavior

```none
it should update the help
```

# Actual behavior

```none
does nothing, no output
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by M-Kub** [comment]
Update-Help fails for me for days, not only on WSL but also on Windows, I even did a fresh install of Windows. It'S the same in Powershell 5 and Powershell . I tried "Update-Help -Force -Verbose", and it just doesn't display anything. Just the cursor is blinking thats all. I am really running out of ideas what else I could try.

**Comment by vim-diesel** [comment]
Are you in the administrator mode

________________________________

**Comment by M-Kub** [comment]
> Are you in the administrator mode
Yes. 
I'm googling this a few days now and nothing seems to help. I'm not behind a proxy or anything,   and when it didnt work after the clean install I really had no more ideas.

**Comment by vim-diesel** [comment]
Are you on Linux? I’ve heard other people say they resorted to just using google unfortunately

________________________________

**Comment by MaximoTrinidad** [comment]
Yes!  It seems that there's an issue with Update-Help

I notice in the full version of Ubuntu, I'm getting an error I never seen before:

```
Update-Help: Failed to update Help for the module(s) 'PSDesiredStateConfiguration, ThreadJob' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

![pwsh7_help_01_2020-04-06_9-56-15](https://user-images.githubusercontent.com/19892435/78566289-000c9300-77ed-11ea-89ff-65e3a1f3de24.png)

So, I was able to run the following command:

```
update-help -force -UICulture en-US
```

And, I was able to run the update-help and I saw module helps been installed, But it sill need up giving the same errors at the end.

:(

cc: @SteveL-MSFT

**Comment by sdwheeler** [comment]
The problems with PSDSC and ThreadJob should be fixed now.

**Comment by iSazonov** [comment]
@sdwheeler Should we close the issue?

**Comment by sdwheeler** [comment]
@iSazonov Yes, I think this is resolved.

**Comment by MaximoTrinidad** [comment]
@iSazonov,

Confirmed! It's resolved!
![updhelp ok-2021-01-18_10-44-27](https://user-images.githubusercontent.com/19892435/104936311-590f7700-597a-11eb-97da-c51de5583b8b.png)
