### ISSUE TITLE
Xaml and other resources are not embeded into Microsoft.PowerShell.GraphicalHost and Microsoft.PowerShell.Activities.dll

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#1225]
## Steps to reproduce
1. Build full PS in Github.
2. Open the generated Microsoft.PowerShell.Activities.dll and Microsoft.PowerShell.GraphicalHost.dll in ILSpy.exe.
3. Open the Microsoft.PowerShell.Activities.dll and Microsoft.PowerShell.GraphicalHost.dll from the GAC.
4. Compare the items in "Resources" folder that are displayed in ILSpy.exe. 
## Expected behavior

You will see for each of the DLLs from GAC, there is a "*.g.resources" item. Those resources are expected to be embedded in the DLLs produced in Github.
## Actual behavior

Those resources items are missing from the DLLs produced in Github.
## Environment data

PS:122> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003119)

Product Information:
 Version:            1.0.0-preview2-003119
 Commit SHA-1 hash:  0708fe095e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by 1RedOne** [comment]
Been testing my XAML tools in PowerShell on Linux today and finding that I can't instantiate a XML NodeReader Object.

**Comment by iSazonov** [comment]
@vors Graphical host and WorkFlows was removed from the repo.
