### ISSUE TITLE
Support formatting specifiers in string interpolation 

### ISSUE THREAD

**Issue by stinos** [PowerShell/PowerShell#12259]
# Summary of the new feature/enhancement

It would be a great adddition to Powershell to support full-blown string interpolation, i.e. including the ability to specify the format of the expanded tokens. Essentially like C#'s https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated or Python's https://www.python.org/dev/peps/pep-0498.

So right now we can 'traditional' string formatting like
```
>>> $x=10
>>> $y=1/3
>>> "x={0,5} and y={1:F3}" -f $x, $y
x=   10 and y=0.333
```

The more 'modern' way is writing expressions inline
```
>>> "x=$x and y=$y"
x=10 and y=0.333333333333333
```
However this does currently not support specifying the format like in the traditional example.

So what I'm looking for here is a way to write it like for instance C# allows i.e. start a string with the `$` sign then enter expressions and their format specifiers inline, here's some example C# code:
```
> var x = 10;
> var y = 1.0/3.0;
> $"x={x,5} and y = {y:F2}";
"x=   10 and y = 0.33"
```

Why? It is usually shorter and more readable, once I got used to it in other language it is really hard to go back to having to write placeholders and hoping you don't mess up the order. Already brought up shortly by @logicalextreme in https://github.com/PowerShell/PowerShell/issues/11412, orignally I asked on SO https://stackoverflow.com/questions/61026258/does-powershell-string-interpolation-support-format-specifiers.

# Proposed technical implementation details

I assume C# implements this by parsing the $ string and turning it into a concatenation of the parts where the interpolated expression is simply passed to string.Format. Not sure if Powershell also needs a special character. But it's maybe not a bad idea to keep a familiar syntax like C#'s i.e. `{<interpolationExpression>[,<alignment>][:<formatString>]}` So the basic idea is to allow for instance
```
"x=${x,5} and y = ${y:F2}"
```
which could be implemented by transforming that into
```
"x=$('{0, 5}' -f $($x)) and y = $('{0:F2}' -f $($y))"
```

**Comment by iSazonov** [comment]
For reference #11412

**Comment by mklement0** [comment]
It would be nice to have this ability, but the proposed syntax won't work:

* `${x,5}`, because `{...}` serves to delineate variable names, refers to a variable named `x,5`, which - perhaps surprisingly - _is_ supported: `${x,5} = 42; ${x,5}`

* `${y:F2}`, because `:` serves as the separator in [namespace variable notation](https://stackoverflow.com/a/55036515/45375), is referring to path `F2` in PS drive `y`.
