### ISSUE TITLE
Duplicate Filesystem Information

### ISSUE THREAD

**Issue by mhbosch** [PowerShell/PowerShell#12265]
Powershell 7.1.- Preview 1

Hello,

with the Powershell Version i get with USB Drives a duplicate Fileinformation by call 
PSDrive.

I use it in a script for freesize and the script get wrong.
With powershell 5.1.xxxx there is no problem.

With regards,

mhbosch

**Comment by vexx32** [comment]
@mhbosch can you please follow the issue template and provide both environment and reproduction information?

Thanks! 😊

**Comment by mhbosch** [comment]
Oh sorry,

i deinstall the instable Version. Sorry.
With Powershell 7 stable i dont have the problem.

Can i help with some other information?
Maybe, i can make a reinstall to the preview drop.
