### ISSUE TITLE
New-LocalUser is not able to link Microsoft Accounts

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/PowerShell#12261]
# Steps to reproduce

```powershell
New-LocalUser -Name 'MicrosoftAccount\user1@outlook.com'
```

# Expected behavior

The command line should create a local user account and link it to a Microsoft Account

# Actual behavior

```powershell
New-LocalUser: Cannot validate argument on parameter 'Name'.
The character length of the 34 argument is too long.
Shorten the character length of the argument so it is fewer than or equal to "20" characters,
and then try the command again.
```

# Environment data

For information, it doesn't work with PS 5.1 neither...

```powershell
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Can you share more information about the feature? Does it really work? New-LocalUser docs is mentioned this but without example.
Also I wonder if it will work after we move to AccountManagement API. Thoughts?

**Comment by MarcoEnxuto** [comment]
Hi, is this still in progress to be implemented?

**Comment by MarcoEnxuto** [comment]
@andschwa can you or someone from your team follow up this issue? Thanks.

**Comment by andschwa** [comment]
I've marked it as "Needs Triage" so it should get followed up on.

**Comment by EssyK** [comment]
Hi @fullenw1 did you get a solution or workaround to this issue? I am currently experiencing the same problem.

Hi @andschwa has there been any fix made? I would appreciate any pointers you can give.
