### ISSUE TITLE
Windows version of pwsh not compatible with .NET 5.0 preview 3

### ISSUE THREAD

**Issue by mthalman** [PowerShell/PowerShell#12264]
# Steps to reproduce

1. Install current (as of today) .NET 5.0 preview 3 build: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-preview.3.20169.1/dotnet-runtime-5.0.0-preview.3.20169.1-win-x64.exe

2. Install PowerShell
```powershell
$powershell_version = '7.1.0-preview.1'; `
Invoke-WebRequest -OutFile PowerShell.Windows.x64.$powershell_version.nupkg https://pwshtool.blob.core.windows.net/tool/$powershell_version/PowerShell.Windows.x64.$powershell_version.nupkg;
\dotnet\dotnet tool install --add-source . --tool-path \powershell --version $powershell_version PowerShell.Windows.x64;
```

3. Run PowerShell
```powershell
.\powershell\pwsh.exe
```

# Expected behavior

```none

```

# Actual behavior

```none
It was not possible to find any compatible framework version

The framework 'Microsoft.NETCore.App', version '5.0.0-preview.3.20201.7' was not found.
```

# Environment data

```none

```

This behavior doesn't occur for the Linux version of pwsh.

cc @adityapatwardhan

**Comment by iSazonov** [comment]
We will move to .Net 5 Preview3 after it will be public preview.

**Comment by mthalman** [comment]
This should be using the automatic roll forward versioning.  For PowerShell 7.0, there was not an issue when using .NET 5.0 preview 2 before it had been released.  This is blocking us from producing the .NET 5.0 preview Docker images that have PowerShell pre-installed.

**Comment by mthalman** [comment]
Also, the fact that Linux works but Windows does not seems to imply some sort of configuration difference there.

**Comment by iSazonov** [comment]
I don't remember that we add anything to discover .Net. It looks like .Net issue.

/cc @SteveL-MSFT for information.

**Comment by mthalman** [comment]
.NET is doing the discovery, not PowerShell.  But that doesn't mean PowerShell isn't the cause of it.  If PowerShell is configured to not allow roll forward, then .NET will fail if that specific version doesn't exist.

**Comment by iSazonov** [comment]
@mthalman You could look global.json and build.psm1 (search key "fxdependent") and review configuration options we use. 
Last PR in the area https://github.com/PowerShell/PowerShell/pull/12140

**Comment by iSazonov** [comment]
@mthalman If time is critical I could pull new PR to move 5.0 Preview2 and then you could download artifacts from the PR to make your tests.

**Comment by mthalman** [comment]
Found the root cause.  This is an issue with the framework version dependencies packaged within the .NET SDK.  Nothing to do with PowerShell.  Closing.

**Comment by iSazonov** [comment]
@mthalman We moved to 5.0 Preview2. It is not public but you can use actifacts from #12250 if you need.
