### ISSUE TITLE
PowerShell 7.1.0-preview.1 does not install assets folder

### ISSUE THREAD

**Issue by najeebanwer** [PowerShell/PowerShell#12273]
# Steps to reproduce
Right-click in any folder to show context menu.

# Expected behavior
Show icon for PowerShell 7-Preview in context menu.

# Actual behavior

PowerShell right-click context menu does not show correct icon for PowerShell 7-Preview.

![image](https://user-images.githubusercontent.com/34123660/78694395-30723100-78c2-11ea-9ff3-c5349df217e7.png)

The reason is that the assets folder is missing from the install folder.

![image](https://user-images.githubusercontent.com/34123660/78694556-77602680-78c2-11ea-8a87-0ce3576f9bd8.png)

# Environment data

![image](https://user-images.githubusercontent.com/34123660/78694756-bdb58580-78c2-11ea-977f-0c4e9fbf38db.png)

**Comment by heaths** [comment]
I have changes ready to fix this but I need time to test them. This is the same problem as the other related issues: incorrect MSI component authoring.

**Comment by najeebanwer** [comment]
This appears to be fixed in PowerShell 7.1.0-preview.2
