### ISSUE TITLE
New parameters to test-json

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12272]
Hello

```
# File Content Json data
-FilePath  

# : File content scheme 
-SchemeFile or -TempleFile 

 # to validate Only propertie(s) and not all properties
-PropertyNames    
```
```

 # Example  validate  Only properties naame and age within json file json.txt with templateFile scheme.txt  
 test-json -FilePath  json.txt -TemplateFile  scheme.txt -properties name,age
```

**Comment by vexx32** [comment]
@p0W3RH311 please follow and fill out the full feature request issue template.

**Comment by p0W3RH311** [comment]
thanks @vexx32 and sorry for my english :)

as a user a would like use test-json cmdlet with some parameters like -FilePath (File content json data) and  -TemplateFile (File content json schema) and -properties (properties to validate)

**Comment by iSazonov** [comment]
We have #11934

**Comment by p0W3RH311** [comment]
@iSazonov thanks  for your contribution  #11934 is  for include just a json file but my request iss for  -templateFile  or -schemeFile and -propeerties to have granularity to choose  between  proerties and validate same properies and not all propertiies

**Comment by kilasuit** [comment]
As some of this has been added I am closing this as Resolution-Fixed so we can track the ask of the Property Parameter request better in #19890 (and so that it can be better shown up in the changelog when implemented)
