### ISSUE TITLE
Feature Request: Export-Clixml encrypt with own key

### ISSUE THREAD

**Issue by isrbaral** [PowerShell/PowerShell#12276]
# Encrypt Export-Clixml with a custom key similar to SecureString implementation

As a user I would like to be able to encrypt my full `Get-Credential` output with a custom key similar to how I can encrypt the password output with a custom key using ConvertFrom-SecureString. Currently it appears the encryption is tied to the user and the machine.

I think it would make the most sense if the workflow looked something like this:
```powershell
#Create the key and the credentials
$Key = New-Object byte[] 32
[Security.Cryptography.RNGCryptoServiceProvider]::Create().GetBytes($Key)
$Key | Out-File .\keyfile.key
Get-Credentials | Export-Clixml -Path .\path\to\store\creds.xml -Key $Key
```
```powershell
#Import the credentials
$Key = Get-Content .\keyfile.key
$Credentials = Import-Clixml .\creds.xml -Key $Key
```

**Comment by iSazonov** [comment]
@PaulHigin Is the scenario addressed in your new module?

**Comment by PaulHigin** [comment]
No, this is a different ask.

**Comment by iSazonov** [comment]
@PaulHigin Is Microsoft.PowerShell.SecretManagement more right place for the ask?

**Comment by PaulHigin** [comment]
No, this has nothing to do with that module.  I believe this is the right place for the ask.
