### ISSUE TITLE
Feature request: Get-service "pathname" return property

### ISSUE THREAD

**Issue by scriptingstudio** [PowerShell/PowerShell#12283]
Why does `get-service` not return `pathname` but `get-ciminstance win32_service` does? Are the underlying methods different? `Get-service` is much faster than `get-ciminstance win32_service` with filter. 

It relates to #9826 but no resolution yet.

**Comment by iSazonov** [comment]
It is dup #3322.

We need a solution for all supported OS but underlying API from .Net Core does not support this.
