### ISSUE TITLE
Add-LocalGroupMember prefer to add domain account over local

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#12289]
# Steps to reproduce

This issue is copied from https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3555

Be aware if the computer is member of a domain and you try to add a local user with same name as a member of the domain it adds the domain member.

```powershell
$Password = ConvertTo-SecureString -String "Testing@19" -AsPlainText -Force
New-LocalUser -Name "User" -Description "Local bruger" -Password $Password -FullName "NewLocalUserWithTheSameNameAsOneInTheDomain"

Add-LocalGroupMember -Group "TheLocalGroup" -Member "User"
```

**Comment by iSazonov** [comment]
This Windows module implementation uses low level P/Invoke to resolve the member user account by name. So It is Windows API behavior giving priority to domain accounts on a domain computer.

I ported the module to public API in #12242 and I hope we preserve the behavior there too.
