### ISSUE TITLE
Possible Memory Leak When Invoking DSC Configuration (7.1-preview1 on ubuntu)

### ISSUE THREAD

**Issue by mrhockeymonkey** [PowerShell/PowerShell#12282]
I have started using Powershell 7.1.0-preview.1 to compile DSC configurations into mofs on Linux and have noticed a potential memory leak when invoking a configuration block. 

# Steps to reproduce

```powershell
# Uses PsDscResources which isn't builtin because it works on Linux/PsCore
Configuration TestConf {
    Import-DscResource -ModuleName 'PSDscResources'

    Node 'localhost' {
        Environment 'test' {
            Name = 'foo'
            Ensure = 'absent'
        }
    }
}

while ($true) {
    & TestConf
    Start-Sleep -Milliseconds 200
    $ws = (Get-Process -Id $pid).WS
    Write-Warning "$($ws / 1MB)MB in use"
}
```

# Expected behavior

```none
MB in use should stay roughly the same indefinitely. 
```

# Actual behavior

```none
MB rises slowly but steadily until OOM
```

# Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1
OS                             Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

I have tried a few things to stop this such as calling `Remove-Item function:/TestConf` and `[System.GC]::Collect()` but these do not appear to have any effect. I'm happy to try any other steps or reproduce on another version/OS if it helps identify the issue.

**Comment by mrhockeymonkey** [comment]
It is probably also worth mentioning that when running the above I get warning messages that `Embeded resource are not support on PSCode...`. I don't know if that is linked in some way to the issue but it feels like they might be left over from a previous release where DSC wasn't supported on Linux. As far as i can tell the mof does get created correctly.

**Comment by gaelcolas** [comment]
Hey @mrhockeymonkey,

Can you try adding the following between runs to see if that's still an issue:

```PowerShell
[Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache]::ClearCache()
[Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache]::Initialize()
```

**Comment by mrhockeymonkey** [comment]
Hey @gaelcolas,

Thanks for the suggestion. Just gave it a go and it does not appear to solve the issue. The memory usage still creeps up.
