### ISSUE TITLE
Feature Request: Return all of a files extensions.

### ISSUE THREAD

**Issue by jake9wi** [PowerShell/PowerShell#12298]
# Summary of the new feature/enhancement

Powershell currently has a property called extension which returns a files extension. Currently this only returns the value after the final dot character in a files name. However some files have a chain of extensions (eg '.tar.gz'). Therefore I suggest modifying the extension property to return an array of a files extensions [like pythons suffixes property](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffixes).

**Comment by vexx32** [comment]
The `Extensions` property comes from .NET Core's `System.IO.FileInfo` class. While PowerShell could add its own property to supplement this, it would make a lot more sense for something like this to be supported in .NET Core if there's a real need for it.

**Comment by iSazonov** [comment]
Currently I look how our ResGen works and it interpret a file name as visibility.namespace.classname.resx where namespace may contains dots. So extension is not "a chain of extensions" in general.
Common convention is that extension is a part after last dot. .Net follows this and we follow .Net.
