### ISSUE TITLE
Set-Location & Get-Item -LiteralPath Inconsistent On Files/Dirs With ?/* Characters

### ISSUE THREAD

**Issue by NoMoreFood** [PowerShell/PowerShell#12299]
# Steps to reproduce

Using PowerShell 7.0 on Linux or MacOS:
1) Create an empty directory
2) Create two sub directories called ":" and "?"
3) Attempt to change location to '?'; the directory will actually change to the ':' directory.
4) Attempt to Get-Item on the '?' directory; the directory information will be for the ':' directory.
# Expected behavior

```
PS /tmp> New-Item -ItemType Directory '/tmp/dir/:' | Out-Null
PS /tmp> New-Item -ItemType Directory '/tmp/dir/?' | Out-Null
PS /tmp> Set-Location -LiteralPath '/tmp/dir/?'
PS /tmp/dir/?> Get-Item -LiteralPath '/tmp/dir/?'


    Directory: /tmp/dir

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          04/10/2020    19:45                ?
```

# Actual behavior

```
PS /tmp> New-Item -ItemType Directory '/tmp/dir/:' | Out-Null
PS /tmp> New-Item -ItemType Directory '/tmp/dir/?' | Out-Null
PS /tmp> Set-Location -LiteralPath '/tmp/dir/?'
PS /tmp/dir/:> Get-Item -LiteralPath '/tmp/dir/?'


    Directory: /tmp/dir

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          04/10/2020    19:45                :
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by JamesWTruher** [comment]
@NoMoreFood interestingly, I'm not able to repro this on my 7.1 shell (on Mac) are you still seeing this?

**Comment by NoMoreFood** [comment]
@JamesWTruher On the test case I originally presented, you seem to be correct.  The failure was highly dependent on how the underlying file system was enumerated in order to expose the bug.  It's possible a change elsewhere in the codebase is now requiring different preconditions or, alternatively, the bug was addressed in another way.  I will look into it.
