### ISSUE TITLE
Line break appended to file redirected from stdout over SSH

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#12291]
# Steps to reproduce

Create a file with some bytes in Linux/WSL/whatever

```
voltagex@raspberrypi:~ $ echo -ne '\x00\x01\x02\x03\x04\x05\xff' > bytes.bin
voltagex@raspberrypi:~ $ xxd bytes.bin
00000000: 0001 0203 0405 ff                        .......
```

i.e. the file has the bytes `00 01 02 03 04 05 ff`

Transfer that file using OpenSSH for Windows
```
ssh voltagex@raspberrypi.local "cat bytes.bin" > bytes.bin
```

Note that the file now contains `00 01 02 03 04 05 C2 A0 0D 0A`

This is better than PowerShell 5.1 which completely destroys the file by default, but will still make backups created via dd invalid.

# Expected behavior
Binary files to be untouched when redirected in PowerShell

# Actual behavior
C2 A0 0D 0A is appended to files that are redirected from stdout.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by voltagex** [comment]
`Out-File bytes.bin -Encoding ascii -NoNewline` still results in `00 01 02 03 04 05 3F` which is ASCII `?`
