### ISSUE TITLE
New-SelfSignedCertificate fails with ECDSA and Microsoft Smart Card KSP

### ISSUE THREAD

**Issue by cdanger** [PowerShell/PowerShell#12309]
# Steps to reproduce

```powershell
New-SelfSignedCertificate `
              -Subject "CN=John Doe" `
              -KeyAlgorithm "ECDSA_secP256r1" `
              -Provider 'Microsoft Smart Card Key Storage Provider'
```

# Expected behavior
Example of successful output when using `Microsoft Software Key Storage Provider` instead:

```none
PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\MY

Thumbprint                                Subject              EnhancedKeyUsageList
----------                                -------              --------------------
D166947F01BFB28AB9B43C2FB9DD0B33CCBC76CD  CN=John Doe          {Client Authentication, Server Authentication}
```

# Actual behavior
Error message:

```none
New-SelfSignedCertificate: CertEnroll::CX509Enrollment::_CreateRequest: Provider type not defined. 0x80090017 (-2146893801 NTE_PROV_TYPE_NOT_DEF). 
```

# Environment data

```none
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Extra info
This info does not fix it but may help troubleshooting:
1. If I replace `ECDSA_secP256r1` with `RSA`, works as expected. 
1. If I replace `Microsoft Smart Card Key Storage Provider` with `Microsoft Software Key Storage Provider`, works as expected.
1. If I replace `ECDSA_secP256r1` with `ECDSA_badcurve`, I get a different error: `Unknown cryptographic algorithm.` So `ECDSA_secP256r1` is recognized as a known crypto algorithm at least.
1. According to [Microsoft Docs on CNG Key Storage Providers](https://docs.microsoft.com/en-us/windows/win32/seccertenroll/cng-key-storage-providers#microsoft-smart-card-key-storage-provider), Microsoft Smart Card Key Storage Provider supports ECDSA P256, P384, P521.

If it works for other ECDSA P256 curves (which ones then?), it works for me, but I need ECDSA on the smartcard.

**Comment by iSazonov** [comment]
PowerShell does nothing with encryption and follow .Net Core. 
I think you need to open issue in .Net Runtime repo.

**Comment by cdanger** [comment]
Thanks for the tip. Are you refering to [this .net repo](https://github.com/dotnet/runtime) as the one providing the New-SelfSignedCertificate cmdlet ? 
Just asking for confirmation, because I couldn't find this cmdlet in the code over there. So I am not sure that I can ask them the exact same question. Actually I can't find a repo that provides the `pkiclient` module altogether. But maybe it is not open source or I don't know how to loko for it.
