### ISSUE TITLE
Can't connect to Exchange Online O365 via Powershell on MacOS

### ISSUE THREAD

**Issue by beth01** [PowerShell/PowerShell#12310]
Hi guys,

I've already followed the procedures in all the other threads regarding the same question but none worked for me. I hope somebody can help with my issue:

PS /Users/user> $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
New-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
PS /Users/user> $PSVersionTable   

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Darwin 17.7.0 Darwin Kernel Version 17.7.0: Tue…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

MacOS High Sierra 10.13.6
Brew Installed, OpenSSL Installed. Please help, I'm in severe troubles!

**Comment by iSazonov** [comment]
WSMan is not supported on MacOs.
Your feedback should be directed to Exchange server team.
