### ISSUE TITLE
add new operator  :+

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12320]
this operator not convert the result/operand

```

PS C:\> 0b11 + 0b10
5
PS C:\> 0xa +  0x112
284

PS C:\> 0b11 :+ 0b10
0b101
PS C:\> 0xa :+  0x112
0x11C

PS C:\> 'hello' + 7
hello7
PS C:\> 7 + 'hello'
# ERROR

PS C:\> 'hello' :+ '7'
hello7

PS C:\> 'hello' :+ 7
# ERROR
PS C:\> 7 :+ 'hello'
# ERROR
```

**Comment by vexx32** [comment]
The idea in general could be worth pursuing. Worth mentioning though that `0b11 + 0b10` does not _convert_ anything, it's just displaying the value in decimal and not binary. Changing that would be quite a different story than just preventing conversions.

That said... having an operator affix that works _in general_ to prevent implicit conversions could be useful, not just for the `+` operator itself, but as a general affix for all arithmetic operators, at least. There might be _some_ use for the broader range of operators as well, but definitely for arithmetic operators it'd make a lot of sense, I think.

**Comment by iSazonov** [comment]
It is formatting. No new operators needed. With PSCore implementation it is easy to implement this.

**Comment by vexx32** [comment]
Apart from the binary literal example, it's not formatting? It's disabling type coercions.

**Comment by p0W3RH311** [comment]
@iSazonov and @vexx32  thank +1 

yes is formating but also powershell need operator such  ':+' ':*' ':-' ':/'  disabling type coercions.
example
```
"hello" :+ 7 
#error
```

**Comment by bpayette** [comment]
@p0W3RH311  I'll ask the question I always ask: why? What purpose does this serve? What real-world scenarios will this unblock?

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
