### ISSUE TITLE
Invoke-command of 7.0 does not connect to Posh 7.0 but instead to V5.1

### ISSUE THREAD

**Issue by JohnRanger** [PowerShell/PowerShell#12339]
The problem seems to occur because there seems powershell V5.1 and V7.0 installed. When I do a invoke-command -computername xyz -scriptblock {$psversiontable} I get the return that it is version 5.1 instead of 7.0. 

Of course, PosH V7.0 is installed both on the local and the remote system (and the only one listed in add/remove programs)

I have checked Enable remoting during setup of 7.0 on the destination machine.

How to disable PoSH V5.1 remoting so that 7.0 remoting works?

P.S: When checking remoting during setup, the remoting ov V5.1 should automatically be disabled.

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PowerShell/issues/11616#issuecomment-594119801 and below comments and related issues.
