### ISSUE TITLE
Rename build.psm1 and commands some of the commands

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1233]
The module name is too generic, maybe BuildPowerShell.psm1?

And the prefix for commands in the module shouldn't be PS - that prefix belongs to the product, not the tool that builds the product.

Here are some possible names (with almost no real thought here):

Start-PSBootStrap => Start-BootstrapBuildPowerShell
Start-PSBuild => Start-BuildPowerShell
Start-PSPackage => Start-PackagePowerShell
Start-PSPester => Start-TestPowerShell -Pester
Start-PSxUnit => Start-TestPowerShell -xUnit

Assuming the above sounds good, some aliases are desirable too:

Start-BootstrapBuildPowerShell => sbbps
Start-BuildPowerShell => sbps
Start-TestPowerShell => stps

**Comment by nightroman** [comment]
Hello,

Sorry if this is off-topic or it is too late. The discussion was private and I
could not join it. I hope that Invoke-Build still can be useful.

@vors wrote:

> I would expect problems on Linux / CoreCLR, but definitely worth investigation.

[#31]: https://github.com/nightroman/Invoke-Build/issues/31

True, Invoke-Build currently has some known issues (like [#31]) and some
potential (like a few `\` in paths). I am working on resolving them.

**Comment by nightroman** [comment]
Invoke-Build v3.0.1 is cross-platform with PowerShell v6.0.0-alpha.

**Comment by andschwa** [comment]
@nightroman that is awesome! Nice, fast, work. Our build module really should be rewritten in a target driven manner... random scripts are messy.

**Comment by joeyaiello** [comment]
I think we're far enough along here that this isn't going to be (nor does it need to be) changed. Closing unless someone has an issue with it.
