### ISSUE TITLE
deep copy instead of shallow  copy

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12358]
### steps to reproduce
if  i copy or assign variable to other variable the copy is not  complete

```
PS C:\> [validateSet('a','b','c')]$abc  = 'a'
PS C:\> Copy-Item Variable:\abc  variable:\abc2
PS C:\> $abc3 = $abc
```

### expected behavior

```
PS C:\> (Get-Variable abc).Attributes

ErrorMessage IgnoreCase ValidValues TypeId
------------ ---------- ----------- ------
                   True {a, b, c}   System.Management.Automation.ValidateSetAttribute

PS C:\> (Get-Variable abc2).Attributes

ErrorMessage IgnoreCase ValidValues TypeId
------------ ---------- ----------- ------
                   True {a, b, c}   System.Management.Automation.ValidateSetAttribute

PS C:\> (Get-Variable abc3).Attributes

ErrorMessage IgnoreCase ValidValues TypeId
------------ ---------- ----------- ------
                   True {a, b, c}   System.Management.Automation.ValidateSetAttribute

PS C:\>
```

### actual behavior
```

PS C:\> (Get-Variable abc).Attributes

ErrorMessage IgnoreCase ValidValues TypeId
------------ ---------- ----------- ------
                   True {a, b, c}   System.Management.Automation.ValidateSetAttribute

PS C:\> (Get-Variable abc2).Attributes
PS C:\> (Get-Variable abc3).Attributes
PS C:\>
```

### envvironmment

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bpayette** [comment]
Hi @p0W3RH311 You misunderstand. `Copy-Item` copies the _value_ of the variable, not the variable object itself. Since the associated metadata resides on the variable object not on the value it contains, there is no "deeper" to copy. If you really need to manipulate variables, use the `Get-Variable`/`Set-Variable` cmdlets. This is what they were designed for.

**Comment by p0W3RH311** [comment]
@bpayette 

thanks,

i tried this but

```
PS C:\> [validateSet('a','b','c')]$abc  = 'a'
PS C:\> New-Variable -Name b -Value $abc
PS C:\> $b
a
PS C:\> (Get-Variable b).Attributes
PS C:\> $b
a
PS C:\> (Get-Variable b).Attributes
PS C:\> (Get-Variable b).Attributes = (Get-Variable -Name abc).Attributes
```

attributes is read-only.

its possible to clone the object variable easily for example add another switch to **new-variable** and **set-variable** for example  switch **-clone**

example:
`new-variable -name b -clone -value $abc`

**Comment by SeeminglyScience** [comment]
@bpayette The name implies to me that it's copying the *item*.  If it was supposed to be just the value, wouldn't `Copy-Content` have been more appropriate?  Also the FileSystem provider sets some precedent since metadata like last write time, readonly, etc are also copied.

**Comment by bpayette** [comment]
@SeeminglyScience It **is** copying the item, because, by design, "item" means the `Value` stored in the variable.  Should `$x = $y` copy the `PSVariable` object too? Actually, can you provide a example where 'copy' copies the reference to the value as well as the value.

**Comment by SeeminglyScience** [comment]
```powershell
Get-Item Variable:\ExecutionContext
# Name                           Value
# ----                           -----
# ExecutionContext               System.Management.Automation.EngineIntrinsics

Get-Content Variable:\ExecutionContext
# PSPath         : Variable:\ExecutionContext
# PSDrive        : Variable
# PSProvider     : Microsoft.PowerShell.Core\Variable
# ReadCount      : 1
# Host           : System.Management.Automation.Internal.Host.InternalHost
# Events         : System.Management.Automation.PSLocalEventManager
# InvokeProvider : System.Management.Automation.ProviderIntrinsics
# SessionState   : System.Management.Automation.SessionState
# InvokeCommand  : System.Management.Automation.CommandInvocationIntrinsics
```

The item is the `PSVariable`.  The value is the *content*.

> Should `$x = $y` copy the `PSVariable` object too?

Nah, *that's* the value.

> Actually, can you provide a example where 'copy' copies the reference to the value as well as the value.

Not the reference, it should clone the item.  In the same way that copying a file doesn't copy a reference, it just clones the item.

**Comment by p0W3RH311** [comment]
> 
> 
> @bpayette The name implies to me that it's copying the _item_. If it was supposed to be just the value, wouldn't `Copy-Content` have been more appropriate? Also the FileSystem provider sets some precedent since metadata like last write time, readonly, etc are also copied.
> 
> @p0W3RH311 here's a workaround
> 
> ```powershell
> [validateSet('a','b','c')]$abc  = 'a'
> $source = Get-Variable abc
> $newVar = [psvariable]::new(
>     'c',
>     $source.Value,
>     $source.Options,
>     $source.Attributes)
> 
> $ExecutionContext.SessionState.PSVariable.Set($newVar)
> $c = 'd'
> # throws validation error
> ```

@SeeminglyScience +1

thanks for your solution ...but i believe is an anti-pattern.  
its more simpler and clean if  we implement this  behavior as cmdlet or parameter for example:  `clone-variable -name a -source b `

but in this case we add the verb "clone" in get-verb

**Comment by vexx32** [comment]
`Clone-Variable` in that case is literally just duplicating `Copy-Item`. That's what `Copy-Item` is supposed to do, and that's what it does for every other provider.

We don't generally add verbs that cover the same territory -- `Clone` has the same meaning as `Copy`. If we wanted a specific `Copy-Variable` then maybe, but I don't see a reason for `Copy-Item` to not copy the variable's properties as well as the value.

**Comment by iSazonov** [comment]
What a business scenario do you want address to justify the change of this long-term design?

**Comment by scriptingstudio** [comment]
@p0W3RH311 try this

```
function Copy-Object ($inputobject) {
	if (-not $inputobject) {return}
	$ms = New-Object System.IO.MemoryStream
	$bf = New-Object System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
	$bf.Serialize($ms, $inputobject)
	$ms.Position = 0
	$bf.Deserialize($ms)
	$ms.Close()
	$ms.Dispose()
} # END Copy-Object
```

**Comment by SeeminglyScience** [comment]
@scriptingstudio he's referring to properties of the `PSVariable` object itself.  Like type declaration, attribute decorations, readonly, etc.
