### ISSUE TITLE
Read-Host max imput length cap in pwsh 7

### ISSUE THREAD

**Issue by Tyf0x** [PowerShell/PowerShell#12354]
# Steps to reproduce

```powershell
Read-Host
```
then paste:
```powershell
{"testKey":"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}
```

# Expected behavior

The output should display the full input.

# Actual behavior

The input is truncated at 1022 chars.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#NOTE:
This works in powershell 5.1.18362.752

**Comment by iSazonov** [comment]
We changed the buffer size to 1024 to be consistent on all systems.
Before the change Unix-s used 1 Kb buffer, Windows - 16 Kb and we had huge allocations in heap. Now we use 1 Kb buffer in stack.

**Comment by Tyf0x** [comment]
Thanks @iSazonov for the explanation, it makes sense that the behaviour was standardised across OS.

If there a way to go around this restriction?

We have scripts that are expecting a JSON input and doing some work with it.
The JSON contains a lot of sensitive data (creds essentially) so it's encrypted in a vault, only decrypted temporarily and copied into the clipboard to then be pasted into powershell.
We read this input via Read-Host and stitching it using ```$kvp = (@(While($inputStr=(Read-Host).Trim()){$inputStr}) -join("`n")) | ConvertFrom-Json```
One of these JSON properties is a private key that is 1676 characters long - too long for the 1Kb buffer.

Could you please advise of a solution or workaround?

On a side note, should this change in buffer size be documented on the [`Read-Host` page](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/read-host?view=powershell-7)?

Thank you

**Comment by iSazonov** [comment]
> On a side note, should this change in buffer size be documented on the Read-Host page?

I can open new issue in PowerShell-Docs repo if you think it is useful.

> The JSON contains a lot of sensitive data (creds essentially) so it's encrypted in a vault, only decrypted temporarily and copied into the clipboard to then be pasted into PowerShell.

Perhaps you find the new module useful https://devblogs.microsoft.com/powershell/secrets-management-module-vault-extensions/

**Comment by StanleyGoldman** [comment]
Can I override this limit?

**Comment by iSazonov** [comment]
The limit is hard-coded. You can open issue in PowerShell-Docs repo to request the doc update.

**Comment by iSazonov** [comment]
> On Windows v7.1.2 I'm not able to type past the 1022'th character.
> On OSx v7.1.2 I'm able to create a value seemingly well past 1022.

I guess it is `\n` vs `\r\n`.

**Comment by StanleyGoldman** [comment]
Can you point me to this code?

**Comment by iSazonov** [comment]
See
https://github.com/PowerShell/PowerShell/blob/c5955a5c0de50295e509dbc10928147b33d5cbea/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1539

**Comment by StanleyGoldman** [comment]
Thanks for the help
