### ISSUE TITLE
Need higher resolution PowerShell icon in readme

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1236]
I love having an icon, but we need a retina and 4K compatible icon given the increasing prevalence of high-definition monitors. It's looking a bit blurry.

**Comment by andschwa** [comment]
@joeyaiello 256 isn't high res :tongue:

**Comment by andschwa** [comment]
But it's better than 64!

**Comment by joeyaiello** [comment]
I'm going to replace it with the SVG.

**Comment by joeyaiello** [comment]
Never mind, I can't find an SVG....one day...
