### ISSUE TITLE
Failure to build when using Visual Studio 2019 without manual NuGet package restore

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#12373]
Build was attempted using Microsoft Visual Studio Community 2019 Version 16.5.4

```
Error	NU1105	Unable to find project information for 'X:\PowerShell\src\Microsoft.Management.UI.Internal\Microsoft.PowerShell.GraphicalHost.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.	powershell-win-core	X:\PowerShell\src\powershell-win-core\powershell-win-core.csproj	1	
```

**Comment by xtqqczze** [comment]
```
Error	NU1201	Project Microsoft.PowerShell.GraphicalHost is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Project Microsoft.PowerShell.GraphicalHost supports: net50 (.NETFramework,Version=v5.0)	powershell-win-core	X;\PowerShell\src\powershell-win-core\powershell-win-core.csproj	1	
```

**Comment by xtqqczze** [comment]
The following commands ran once via the developer PowerShell allow me to build the solution in Visual Studio.
```
msbuild -t:restore; Import-Module ./build.psm1; Start-PSBuild
```

**Comment by iSazonov** [comment]
We use TFM "netcoreapp5.0" but should "net5.0".

**Comment by iSazonov** [comment]
Docs https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md

**Comment by TravisEz13** [comment]
Honestly, we need a maintainer of the solution.  I don't use the solution because it's only problematic for me.  cc @daxian-dbw

**Comment by iSazonov** [comment]
Usually VS public update is needed to work stable with latest .Net preview.

**Comment by xtqqczze** [comment]
@iSazonov Build was attempted using Microsoft Visual Studio Community 2019 Version 16.5.4

**Comment by xtqqczze** [comment]
@iSazonov Using the latest Visual Studio preview the solution failed to open, see #12505.

**Comment by iSazonov** [comment]
@xtqqczze We moved to TFM "net5.0" today. You could try with latest master.

**Comment by xtqqczze** [comment]
Using 7c1cc868b, the solution fails to build from a clean workspace using "Build Solution" from within Visual Studio. It would therefore appear the move to `net5.0` does not affect this issue.

Additionally invoking `Start-PSBuild` fails too unless a manual [NuGet package restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-msbuild) is performed first with `msbuild -t:restore`.

As I indicated earlier, building from within Visual Studio suceeds as long as a command line build with `msbuild -t:restore; Import-Module ./build.psm1; Start-PSBuild` has suceeded previously.

**Comment by TravisEz13** [comment]
@xtqqczze `Import-Module ./build.psm1; Start-PSBuild` I always do this before trying to build with the solution.  I think this is expected.

**Comment by vexx32** [comment]
I've often found that in a clean workspace or after some commits have been pulled in I'll need to `Start-PSBuild -Clean` which prompts it to take a couple extra steps that seem to be required n certain cases.

**Comment by xtqqczze** [comment]
@TravisEz13 @vexx32 I have found that `msbuild -t:restore` is indeed necessary to resolve the error `NU1105` described in this issue, as `Start-PSBuild` doesn't appear to perform the necessary NuGet package restore, even with the `Clean` parameter.

**Comment by TravisEz13** [comment]
@xtqqczze This sounds like an issue in visual studio not realizing it needs to restore.  I'm not sure what to tell you.  You or someone else could add a `-RestoreAll` switch to `start-psbuild`.

The `sln` is only there as a connivence.  We make no guarantees for it working to actually build.

@iSazonov has been doing good working getting rid of the workarounds we use in `start-psbuild`, but the team at Microsoft, we don't have an immediate goal to build using Visual Studio.  There is still one workaround, `TypeGen` which I haven't seen him attempt to eliminate.  

As far as why we don't restore everything, we know we can't cross compile, so we limit what we have dotnet restore to save time and disk.

**Comment by xtqqczze** [comment]
@vexx32 I have now found that if `Start-PSBuild -Clean` is used as you suggested than `msbuild -t:restore` is unnecessary.

@TravisEz13 It seems that if Visual Studio is opened before running `Start-PSBuild` then the environment becomes polluted somehow (likely from an automatic restore). I'm closing this issue but will open a new one concerning the build documentation as it is badly outdated.

**Comment by xtqqczze** [comment]
To resolve this issue `Import-Module ./build.psm1; Start-PSBuild -Clean` should be ran with Visual Studio closed. After building from the command line once, then "Build Solution" from within Visual Studio seems to work.

**Comment by iSazonov** [comment]
> TypeGen which I haven't seen him attempt to eliminate.

@TravisEz13 I did the attempt years ago but MSFT team said "Oh, no..." :-) If I remember right the team wanted to avoid complex csproj files and prefer PowerShell script. But the TypeGen (like resgen) is stable and we could move it to csproj that helps to build on VS 2019.

If you want I could try to move TypeGen to csproj (It will work like resgen works now)

**Comment by TravisEz13** [comment]
I don't want to move it but it would be required for msbuild or visual studio to work perfectly
