### ISSUE TITLE
adding Named placeholders in format operator

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12374]
Hi,

this is, a prototype:
```

PS C:\> "welcome to {0} {1}" -f 'power','shell'
welcome to power shell

PS C:\> "welcome to {first} {last}" -f 'first=power','last=shell'
welcome to power shell

PS C:\> "welcome to {first} {last}" -f 'last=shell','first=power'
welcome to power shell

PS C:\> "welcome to {first,15} {last}" -f   'first=power','last=shell'
welcome to           power shell


# if we want literal we add baacktick
PS C:\> "welcome to {first} {last}" -f "first`=power",'last=shell'
welcome to first=power shell
```

**Comment by mklement0** [comment]
PowerShell's `-f` operator provides access to the [`System.String.Format`](https://docs.microsoft.com/en-US/dotnet/api/System.String.Format) .NET functionality, which supports only indexed format items (placeholders).

While named placeholders would be nice, I don't think we want to overlay the .NET functionality with a custom layer of additional functionality, not least for the implementation challenges that would ensue.

#11412 has previously asked for named placeholders, which led me to suggest relying on the existing string-interpolation syntax (expandable strings) instead and allowing _on demand_ expansion of string literals acting as _templates_, via a hypothetical new `Expand-String` cmdlet: #11693
Note that, as with the current string interpolation, this requires making the values to be formatted a direct part of the string - not separate arguments.

However, just like current string interpolation that wouldn't directly  support `String.Format()`-style formatting instructions (such as `{first,15}` for left space-padding to 15 characters, in your example).

Making this ability part of regular PowerShell string interpolation is what #12259 proposes.
