### ISSUE TITLE
Please provide localization support

### ISSUE THREAD

**Issue by wbpluto** [PowerShell/PowerShell#12380]
Microsoft is a global company, and Windows Terminal is used by users speaking many languages.
You should support this, just like Windows PowerShell 5:

![image](https://user-images.githubusercontent.com/5191513/79669372-9da09300-81ed-11ea-8b69-1fa700396410.png)

**Comment by he852100** [comment]
你用的是什么字体？这么漂亮。

**Comment by mklement0** [comment]
For reference: #666

**Comment by iSazonov** [comment]
Tracked in #666

**Comment by wbpluto** [comment]
> 你用的是什么字体？这么漂亮。

https://github.com/be5invis/Sarasa-Gothic
