### ISSUE TITLE
Test-Connection returns wrong error message on fractional delay parameter

### ISSUE THREAD

**Issue by schuelermine** [PowerShell/PowerShell#12381]
# Steps to reproduce

```powershell
PS C:\> Test-Connection example.com -Delay 0.1
```

# Expected behavior

Either: Delay is now a tenth of a second  
Or: 
```none
Test-Connection: Cannot validate argument on parameter 'Delay'. The argument "0" cannot be validated because its value is fractional.
```

# Actual behavior

```none
Test-Connection: Cannot validate argument on parameter 'Delay'. The argument "0" cannot be validated because its value is not greater than zero.
```

# Environment data

```none
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
From the help information:

```ps1
PS> Get-Help Test-Connection -Parameter Delay

-Delay <System.Int32>
    Specifies the interval between pings, in seconds.

    Required?                    false
    Position?                    named
    Default value                None
    Accept pipeline input?       False
    Accept wildcard characters?  false
```

In PowerShell at large, fractional values are converted to integers quite frequently, so the fractional portion will be stripped away in a case like this...

My general recommendation for this would be to use a non-integer type for this parameter, though, or at least make it use milliseconds instead of seconds. An integer value for seconds is a bit wonky to work with when we're talking network introspection.

**Comment by fireflycons** [comment]
^^^ Incorrect issue link

**Comment by iSazonov** [comment]
It is by-design - we do not allow short delays to exclude DoS attacks.

**Comment by schuelermine** [comment]
I understand, but the error message is the problem @iSazonov. It says that the value is not greater than zero, which it is. It should say that it's not greater than one.

**Comment by iSazonov** [comment]
:-) The parameter is Int32. But I can pull new PR if you want better error message.

**Comment by schuelermine** [comment]
OK.
