### ISSUE TITLE
System.Managment.Automation.PowerShell throws when accessing properties after Invoke() on Linux

### ISSUE THREAD

**Issue by fireflycons** [PowerShell/PowerShell#12383]
# Steps to reproduce

```csharp
using (var powershell = PowerShell.Create())
{
      // script setup snipped

      // This works and output is returned
      var results = powershell.Invoke();

      // This throws PlatformNotSupportedException on Linux (Ubuntu 18.04), but not on Windows
      if  (powershell.HadErrors)
      {
          // This, if tested in isolation also throws PlatformNotSupportedException 
          //  on Linux (Ubuntu 18.04), but not on Windows
          var errorRecord = powershell.Streams.Error.FirstOrDefault();
      }
}
```

# Expected behavior
No exception is thrown

# Actual behavior
Exception is thrown

# Environment data

Occurs with version 6.1.6 and version 7.0.0 of the System.Management.Automation nuget package
My project is compiled with NET Core 3.1 LTS

Complete implementation of host can be found here: https://github.com/fireflycons/PSDynamicParameters/blob/appveyor/tests/Firefly.PowerShell.DynamicParameters.Tests/TestCmdletHost.cs

**Comment by SeeminglyScience** [comment]
The `Invoke` method is what's throwing, that happens when there is a terminating error. You would use `HadErrors` and/or `Streams.Error` to check for *non-terminating* errors.

**Comment by fireflycons** [comment]
Hi @SeeminglyScience 

I've created a branch to specifically test this and have found that it's not the property accessors that are throwing. It is in fact that the cmdlet has thrown `PlatformNotSupportedException` as a non-terminating error, when the expected exception is `ParameterBindingException`

I am now logging the progress of the host
https://github.com/fireflycons/PSDynamicParameters/blob/issue-12383/tests/Firefly.PowerShell.DynamicParameters.Tests/TestCmdletHost.cs#L128

...testing with this
https://github.com/fireflycons/PSDynamicParameters/blob/issue-12383/tests/Firefly.PowerShell.DynamicParameters.Tests/Issue12383Tests.cs

and the results can be seen here
https://ci.appveyor.com/project/fireflycons/psdynamicparameters/builds/32297830

This happens everywhere I expect `ParameterBindingException`, but only in Linux

Where I skip the tests for exceptions, other tests execute correctly
https://ci.appveyor.com/project/fireflycons/psdynamicparameters/builds/32291659

Unless this helps you to shed some light on what's going on, next job for me will be to build to a local docker container and debug the tests within that.

**Comment by SeeminglyScience** [comment]
@fireflycons Yeah that's correct.  That cmdlet throws `PlatformNotSupportedException` when invoked on non-Windows by design.  That exception is surfaced through the `PowerShell.Invoke` method.

**Comment by fireflycons** [comment]
Er, which cmdlet? `Set-ExecutionPolicy`? That's the only one I'm calling which isn't mine.

If you look at the links I posted above back to my project, the `PlatformNotSupportedException` is being received through the error stream. `PowerShell.Invoke()` is _not_ throwing directly.

**Comment by fireflycons** [comment]
Ha - it was indeed that!

Thanks v much for your assistance in helping me track this down. All good now, so I'll close.
