### ISSUE TITLE
more events with register-EngineEvent

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12392]
hi,

register-EngineEvent support  2 events from the **_PSengineevent_** '**PowerShell.Exiting**' and '**PowerShell.OnIdle**' its possible to add other events for example:
```
 
-  'Powershell.Starting' 
-  'Powershell.Terminating'  # crash or killed by click in the botton
-  'Powershell.StartWithTranscriptionActivated'
```

**Comment by SeeminglyScience** [comment]
> -  'Powershell.Starting' 
> -  'Powershell.StartWithTranscriptionActivated'

You mean like when the PowerShell process starts? I'm not sure how you'd register that before that event would fire.

> -  'Powershell.Terminating'  # crash or killed by click in the botton

If PowerShell crashes, it's not going to be in a state where it's safe to execute more code.  Does `PowerShell.Exiting` not work when the close button is clicked? I thought it did, or was supposed to.  If that doesn't work maybe that should be a separate issue.

**Comment by p0W3RH311** [comment]
Hi @SeeminglyScience 
thanks



> 
> 
> > * 'Powershell.Starting'
> > * 'Powershell.StartWithTranscriptionActivated'
> 
> You mean like when the PowerShell process starts? I'm not sure how you'd register that before that event would fire.
> 
> > * 'Powershell.Terminating'  # crash or killed by click in the botton
> 
> If PowerShell crashes, it's not going to be in a state where it's safe to execute more code. Does `PowerShell.Exiting` not work when the close button is clicked? I thought it did, or was supposed to. If that doesn't work maybe that should be a separate issue.

**Comment by p0W3RH311** [comment]
> 
> 
> > * 'Powershell.Starting'
> > * 'Powershell.StartWithTranscriptionActivated'
> 
> You mean like when the PowerShell process starts? I'm not sure how you'd register that before that event would fire.
> 
> > * 'Powershell.Terminating'  # crash or killed by click in the botton
> 
> If PowerShell crashes, it's not going to be in a state where it's safe to execute more code. Does `PowerShell.Exiting` not work when the close button is clicked? I thought it did, or was supposed to. If that doesn't work maybe that should be a separate issue.

Hi @SeeminglyScience 

i test  **powershell.exited** event and it not work:

```
PS> Register-EngineEvent -SupportEvent powershell.exited -Action { 'exited' > 'C:\Users\Public\exited.txt' }
PS> exit
# Not work
```
```

PS>  Register-EngineEvent -SupportEvent powershell.exited -Action { 'exited' > 'C:\Users\Public\exited.txt' }
# i click in button exit  and also not work
```
no file created ?!

> 
You mean like when the PowerShell process starts? 

yes

**Comment by vexx32** [comment]
I think we have an open issue around the `Exited` event specifically, something to do with it not working in some cases.

The issue with registering events around PowerShell's own start is that there is no PS code you can run in a powershell process _before_ it starts, which you would need to do in order to be able to trigger something on engine start.

**Comment by SeeminglyScience** [comment]
> i test powershell.exited event and it not work:

The event is `PowerShell.Exiting`, works for me on both `exit` and clicking the close button.

> _You mean like when the PowerShell process starts?_
> 
> yes

Where would you register that event handler though? If you're able to run code, the process is already started.  That aside, what benefit would that provide over profiles?
