### ISSUE TITLE
weird  ValidateUserDrive

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12391]
some tests:

```
PS C:\> [ValidateUserDrive()]$c = 'c'
MetadataError: The attribute cannot be added because variable c with value c would no longer be va
lid.

PS C:\> [ValidateUserDrive()]$c = 'c:'
MetadataError: The attribute cannot be added because variable c with value c: would no longer be v
alid.

PS C:\> New-PSDrive -Name mydrive -PSProvider FileSystem -Root C:\Users\Public\

Name           Used (GB)     Free (GB) Provider      Root                                CurrentL
                                                                                          ocation
----           ---------     --------- --------      ----                                --------
mydrive           435.16         30.25 FileSystem    C:\Users\Public\

PS C:\> [ValidateUserDrive()]$c = 'mydrive'
MetadataError: The attribute cannot be added because variable c with value mydrive would no longer be valid.

PS C:\> [ValidateUserDrive()]$c = 'mydrive:'
MetadataError: The attribute cannot be added because variable c with value mydrive: would no longe
r be valid.


PS C:\> New-PSDrive -Name user -PSProvider FileSystem -Root C:\Users\Public\

Name           Used (GB)     Free (GB) Provider      Root                                CurrentL
                                                                                          ocation
----           ---------     --------- --------      ----                                --------
user              435.16         30.25 FileSystem    C:\Users\Public\

PS C:\> [ValidateUserDrive()]$c = 'user:'
PS C:\>  # work ?!

```

it only work with  psdrive user: ?  its more better to generalise this attribute to work with any new psdrive createdd by the user

**Comment by vexx32** [comment]
I'm not really clear on the design intent of `ValidateUserDriveAttribute` as it is to be quite honest. Perhaps @SteveL-MSFT or one of the other team members can speak more accurately to that.

**Comment by mklement0** [comment]
I'm curious too. It almost looks like the current implementation is based on a misconception:

Currently, `[ValidateUserDriveAttribute()]` is effectively the same as  `[ValidateDrive('user')]`, where `'user'` binds to the `ValidRootDrives` property that contains the list of drive names that are allowed  - that is, only paths referencing a drive literally named `user:` are accepted (and that drive must exist).

Since constructors aren't inherited and `ValidateUserDriveAttribute` only has a parameterless one, the above use is the only possible one.

**Comment by p0W3RH311** [comment]
```
PS C:\> New-PSDrive -Name user -PSProvider FileSystem -Root C:\Users\Public

Name           Used (GB)     Free (GB) Provider      Root                                CurrentL
                                                                                          ocation
----           ---------     --------- --------      ----                                --------
user              438.58         26.84 FileSystem    C:\Users\Public

PS C:\> [ValidateUserDrive()]$a = 'user:\foo'
PS C:\> [ValidateDrive('user')]$a = 'user:\foo'
PS C:\>
```

**Comment by p0W3RH311** [comment]
i found this but i m not certain:

```
User drive

If your connecting users need to copy files to or from the JEA endpoint, you can enable the user drive in the session configuration file. The user drive is a PSDrive that is mapped to a unique folder for each connecting user. This folder allows users to copy files to or from the system without giving them access to the full file system or exposing the FileSystem provider. The user drive contents are persistent across sessions to accommodate situations where network connectivity may be interrupted.
```

[its in relation with Jea perhaps](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/jea/session-configurations?view=powershell-7) ?!

**Comment by SteveL-MSFT** [comment]
I think it does have something to do with JEA.  cc @PaulHigin

**Comment by PaulHigin** [comment]
Yes, this is related to a JEA configuration option.  Normally a JEA endpoint does not enable the file system provider so as to prevent information disclosure and unwanted file changes.  But there needs to be a way to legitimately transfer and access files in a JEA session, so an optional 'UserDrive' can be mounted on the endpoint and the user is restricted to that PSDrive.

See `New-PSSessionConfigurationFile -MountUserDrive`

The `ValidateUserDrive` attribute is used internally by JEA helper functions to ensure provided path arguments are valid `UserDrive:` paths.

**Comment by vexx32** [comment]
@PaulHigin @sdwheeler perhaps this should be a doc issue instead, then?

**Comment by PaulHigin** [comment]
Can you please file a doc issue?
