### ISSUE TITLE
Command.CommandText doesn't display parameters

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#12405]
`Command.CommandText` doesn't display parameters... this leaves the extension in an awkward position because we pass around `PSCommand`'s everywhere and there doesn't seem to be a friendly way of printing those out short of iterating over all the parameters ourselves.

I would have expected PowerShell to take care of this by default.

# Steps to reproduce

```powershell
[PowerShell]::Create().AddCommand("Get-Foo").AddParameter("WillThisShowUp", "Nope").Commands.Commands[0].CommandText
```

# Expected behavior

```none
Get-Foo -WillThisShowUp Nope
```

# Actual behavior

```none
Get-Foo
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-daily.20200418
PSEdition                      Core
GitCommitId                    7.1.0-daily.20200418
OS                             Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by bpayette** [comment]
@TylerLeonhardt `PSCommand` is just a property bags of _strings_, parameters etc. So it just contains the _name_ of the command which won't be resolved until the PowerShell object is invoked. If you actually want any information about a command you really, really should be using CommandInfo objects. 

But, it would be nice if the `ToString()` on `PSCommand` returned what you want. It would be even nicer if the PowerShell `ToString()` returned a complete syntactically valid pipeline string to support code generation. This would make it easier for app developers to implement "Show Me" functionality.

**Comment by SeeminglyScience** [comment]
Kinda complicated to do.  For instance, what would it print here:

```csharp
var obj = new object();
ps.AddCommand('Save-Object').AddArgument(obj);
```

**Comment by TylerLeonhardt** [comment]
Yeah that's tricky @SeeminglyScience. I would guess just calling ToString() on each parameter value / argument.

**Comment by SeeminglyScience** [comment]
What's the motivation if it can't accurately represent the command though? Just a visual aid?

**Comment by TylerLeonhardt** [comment]
>  If the aim is instead to just get a "good enough" ToString to make it easy to see what the PSCommand currently holds then 👍 👍 from me

Yeah this is the idea.

**Comment by iSazonov** [comment]
In the case perhaps we need to have more descriptive name instead of `ToString()`.

**Comment by JamesWTruher** [comment]
the CommandText property name is slightly misleading. It really should have been called "CommandName" (this is clear from the comment in the code). Rather than changing this property name, a new property could be created. However, this can also be done with an ETS extension external to the engine.
