### ISSUE TITLE
new type [hex] and [bin]

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12409]
Hi,

its useful to convert to binary and hexa

```
PS C:\> 0xa -is [hex]
True

PS C:\> [hex]'10'
0xA

PS C:\> 0b110011 -is [bin]
True


PS C:\> 6552 -as [bin] -is [bin]
True

PS C:\>  [bin]5
0b101
```

**Comment by vexx32** [comment]
Hex and binary aren't types. They're just a different way of writing a number. I don't think it's feasible or particularly useful to make pseudo-types for this. If you want a hex string of a number, you can do `$number.ToString('X')`, and if you want to get the hexadecimal representation of a string, you can use `$string | Format-Hex`.

There may be improvements to be had in discoverability there, but I don't think type accelerators are the way to go. They communicate the wrong thing here; these aren't separate types... just different ways of expressing the same data.

**Comment by p0W3RH311** [comment]
@vexx32 

thanks 

```
PS C:\> [convert]::ToString('10',16)
a
PS C:\> [convert]::ToString('2',2)
10
```

not perfect but it work
