### ISSUE TITLE
Get-Date returns wrong date/time when using inside Invoke-Command

### ISSUE THREAD

**Issue by remenaker** [PowerShell/PowerShell#12410]
When running the following code the wrong date/time is returned. Instead of returning the remote computers date/time it returns the date/time from the local computer. For instance if the remote computer has a different timezone configured then the local computer it returns the local computers time.

I believe this to be a bug because this is not something I would expect to happen. If this is not a bug can you please explain why this happens? Thanks!

# Steps to reproduce

```powershell
Invoke-Command -ComputerName <remote_computer> -ScriptBlock {Get-Date}
```

# Expected behavior

Returns the remote computers Date/Time

# Actual behavior

Returns the local computers Date/Time

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by p0W3RH311** [comment]
can you try

invoke **get-timezone** in local and remote machine

**Comment by remenaker** [comment]
Also forgot to mention that this happens on Powershell 5.1 as well. But wanted to test it with the current release of PS 7.

**Comment by mklement0** [comment]
When PowerShell serializes `[datetime]` instances (on the remote end), it records them with their UTC offset; e.g.:

```xml
    <DT>2020-04-21T13:25:58.454524-04:00</DT>
```

On deserialization (on the caller's end), the point in time is expressed in _local_ time (as reflected in the `.Kind` property containing `Local`).

That is, you cannot derive remote time-zone / UTC-offset information from the date returned.

If you need this information, use `Get-TimeZone`, as suggested, or use `[datetimeoffset]::Now`.

Note that `[datetimeoffset]` is currently not deserialized type-faithfully; that is, the return value is a custom object with static copies of the original object's property values; there is an open feature request to change that - see #3172

The following command shows how to retrieve the date expressed as the caller-local date, as the remote-relative local date, as well as the UTC offset on the remote machine in hours.

```powershell
Invoke-Command -ComputerName $computer { [datetimeoffset]::Now } |
  Select-Object LocalDateTime, DateTime, @{ n='Offset'; e = { $_.Offset.TotalHours } }
```

**Comment by mklement0** [comment]
P.S.: In case it is not obvious from the above: there is no bug here, everything works as designed. It is an inherent limitation of the `[datetime]` type that it doesn't carry UTC-offset information, and deserializing the remote point in time to the equivalent _caller-local_ point in time makes sense, not least because that's what local `Get-Date` calls return too.
