### ISSUE TITLE
Powershell Crashing after launch. 

### ISSUE THREAD

**Issue by bestaps** [PowerShell/PowerShell#12425]
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

as soon as I open PowerShell, it is throwing this issue and crashing immediately. please suggest a fix

**Comment by iSazonov** [comment]
Please add more info. How can we reproduce the issue?

**Comment by BDS26** [comment]
Just after installation on a Windows2016 server I get the same. First time start, the application hangs with this message. My Windows machine is running Build Version 1607

**Comment by iSazonov** [comment]
Please use issue template to share all requested information.

**Comment by prem48science** [comment]
The problem got resolved when I uninstalled the recent update KB4549951. I think is problem with .NET framework 3.5 or plus. one has to uninstall all .NET framework and install an update and reinstall .NET Framework.

**Comment by BDS26** [comment]
My problem got solved when touching the powershell Culture settings.

Default setting is nl-NL.
When changing it to en-US in Powershell 5.1.. the result is that powershell 7 start.

The strange thing is, when revering back the Culture setting to nl-NL powershell remains working ok... and to me nothing has changed. 

commands:
Get-Culture (to verify the current setting)
Set-Culture nl-NL or en-US  (to change the setting)

Restart the powershell session, then only you see the change.
