### ISSUE TITLE
Unable to load DLL 'api-ms-win-eventing-provider-l1-1-0.dll'

### ISSUE THREAD

**Issue by nu8** [PowerShell/PowerShell#12424]
I downloaded a program from here:

<https://github.com/PowerShell/PowerShell/releases/download/v7.1.0-preview.1/PowerShell-7.1.0-preview.1-win-fxdependent.zip>

I try to run it, and get this:

~~~
A fatal error occurred. The required library hostfxr.dll could not be found. If
this is a framework-dependent application, install the runtime in the global
location [C:\Program Files\dotnet]
The .NET Core runtime can be found at:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win7-x64
~~~

ok fair enough. So I go to that link and I see these options:

1. .NET Core Runtime
2. Desktop Runtime

So I go with number 1. Then I try again:

~~~
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0-preview.1.20120.5' was not
found.
  - The following frameworks were found:
      3.1.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&
framework_version=5.0.0-preview.1.20120.5&arch=x64&rid=win7-x64
~~~

So I uninstall what I installed before, and install this new thing. Then I try
again:

~~~
Unhandled exception. System.TypeInitializationException: The type initializer
for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
 ---> System.TypeInitializationException: The type initializer for
 'System.Management.Automation.Tracing.PSEtwLogProvider' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL
 'api-ms-win-eventing-provider-l1-1-0.dll' or one of its dependencies: The
 specified module could not be found. (0x8007007E)
~~~

**Comment by iSazonov** [comment]
You should install .Net 5.0.0-preview.1 to use fxdependent package.

**Comment by muv1** [comment]
iSazonov I did that. I installed from here:

<https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&
framework_version=5.0.0-preview.1.20120.5&arch=x64&rid=win7-x64>

**Comment by iSazonov** [comment]
I guess you need to use  msi installer or set DOTNET_ROOT environment variable.
Use `dotnet  --list-runtimes` to check.

**Comment by muv1** [comment]
@iSazonov ok I will start fresh, with the instruction you give. Trying from the
beginning I get:

~~~
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a framework-dependent application, install the runtime in the global
location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable
to specify the runtime location or register the runtime location in
[HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
- https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win7-x64
~~~

So I go to that page and get the **.NET Core Runtime** installer. I run the
installer. After that I check. The installer didnt set a registry entry, or
`DOTNET_ROOT`, but that shouldnt matter, as it installed to
`C:\Program Files\dotnet` as shown above. I then try again:

~~~
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0-preview.1.20120.5' was not
found.
  - The following frameworks were found:
      3.1.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
- https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&
framework_version=5.0.0-preview.1.20120.5&arch=x64&rid=win7-x64
~~~

I then install the file linked above. and Try again:

~~~
Unhandled exception. System.TypeInitializationException: The type initializer
for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
 ---> System.TypeInitializationException: The type initializer for
'System.Management.Automation.Tracing.PSEtwLogProvider' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL
'api-ms-win-eventing-provider-l1-1-0.dll' or one of its dependencies: The
specified module could not be found. (0x8007007E)
~~~

Note I didnt uninstall anything like the first time, and the error continues.

> Use `dotnet --list-runtimes` to check.

~~~
Microsoft.NETCore.App 3.1.3 [C:\Program
   Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [C:\Program
   Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.2.20160.6 [C:\Program
   Files\dotnet\shared\Microsoft.WindowsDesktop.App]
~~~

**Comment by iSazonov** [comment]
I see you have 5.0.0-preview.2 installed so perhaps it is expected that 5.0.0-preview.1 ignored.

I don't know why roll-forward does not work for the framework-dependent package.

/cc @adityapatwardhan

**Comment by muv1** [comment]
I think the problem is this. This link is given:

<https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0-preview.1.20120.5&arch=x64&rid=win7-x64>

but then when you go there, it changes to this:

<https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-5.0.0-preview.2-windows-x64-installer>

a link to `5.0.0-preview.1` should not change to `5.0.0-preview.2`. If I go to
this instead, it gives the correct version:

<https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-5.0.0-preview.1-windows-x64-installer>

I think `dotnet.exe` or whatever is the culprit, should not be giving out bogus
links, as it will cause confusion to the user.

**Comment by muv1** [comment]
DLL error continues with new version as well:

https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.2

**Comment by nu8** [comment]
I think this has been fixed

https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.3
