### ISSUE TITLE
`ForEach-Object -Parallel` incorrect path handling

### ISSUE THREAD

**Issue by IISResetMe** [PowerShell/PowerShell#12428]
# Steps to reproduce

 - Create and switch to a directory with wildcards in the name:
```powershell
mkdir '~\[]' |Set-Location -Path { $_ }
```
 - Use `ForEach-Object -Parallel`:
```powershell
1..5 |ForEach-Object -Parallel { $_ }
```

# Expected behavior

`ForEach-Object` should execute and return

```none
PS ~\[]> 1..5 |ForEach-Object -Parallel { $_ }
1
2
3
4
5
```

# Actual behavior

`ForEach-Object` throws an exception indicating the current directory doesn't exist?!

```powershell
PS ~\[]> 1..5 |ForEach-Object -Parallel { $_ }
ForEach-Object: An unexpected error has occurred while processing ForEach-Object -Parallel input. This may mean that some of the piped input did not get processed. Error: System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\IISResetMe\[]' because it does not exist.
   at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context, Boolean literalPath)
   at System.Management.Automation.PSTasks.PSTaskBase.Start()
   at System.Management.Automation.PSTasks.PSTaskPool.Add(PSTaskBase task)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.<InitParallelParameterSet>b__63_2(Object _).
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1-38-g4082d6612997c78be67b39badf0a83ae5238512b
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
# Potential fix

The issue is with this call:

https://github.com/PowerShell/PowerShell/blob/7837a536ebbce02f289f73b421f7b82fdd394874/src/System.Management.Automation/engine/hostifaces/PSTask.cs#L450

Replacing it with:
```
    runspace.ExecutionContext.SessionState.Internal.SetLocation(_currentLocationPath, new CmdletProviderContext(runspace.ExecutionContext), true);
```

... resolves the issue

**Comment by jszabo98** [comment]
This seems to affect start-threadjob too.  I don't know if they use the same code:

```powershell
cd './`[example/'
1..5 | start-threadjob { $input  } | receive-job -wait -auto  # no output
```

**Comment by IISResetMe** [comment]
@jszabo98 They don't, but [the underlying cause](https://github.com/PaulHigin/PSThreadJob/blob/99bfe5adc30ed066973114ea18d7c5091197ee14/PSThreadJob/PSThreadJob.cs#L731) in PSThreadJob is almost identical:

```csharp
    ps.AddCommand("Set-Location").AddParameter("Path", _currentLocationPath).Invoke();
```

Should be using the `LiteralPath` parameter instead.

@PaulHigin should I file a separate issue [here](https://github.com/PaulHigin/PSThreadJob/issues)?

**Comment by PaulHigin** [comment]
@IISResetMe  Yes, or you can just submit a PR.  It would be nice to include tests as well.  Note that PSThreadJob is going to be moved soon to https://github.com/PowerShell/Modules.git.

**Comment by IISResetMe** [comment]
@PaulHigin PR opened against PSThreadJob :) 

I'll write a few tests for wildcard locations and open one for this as well
