### ISSUE TITLE
Improve mutable struct detection

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#12430]
# Summary of the new feature/enhancement

When assigning a struct to a variable, some checks are done to determine if the struct is mutable.  The current code path checks if there are:

1. Any public instance fields
1. Any public instance properties with a set accessor
1. Any public instance methods

This can be simplified by checking if the struct is decorated with the `IsReadOnlyAttribute`.  This would allow PS to assume any struct that wasn't declared explicitly as read only with the C# `readonly` modifier ([SharpLab example](https://sharplab.io/#v2:D4AQzABATgpghgEwPYDsA2BPCBnALlAVwGNcIBZDAZX2NIG8BfIA)) to be mutable.  This would also probably result in *less* false positives because most structs have a public field (even if `initonly`) or a public method, even these explicitly `readonly` structs.

# Proposed technical implementation details (optional)

This method:

https://github.com/PowerShell/PowerShell/blob/947bddfe0474429672745b939d0ec511392e5879/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L2030-L2063

Should be changed like this:

```diff
diff --git a/src/System.Management.Automation/engine/runtime/Binding/Binders.cs b/src/System.Management.Automation/engine/runtime/Binding/Binders.cs
index b54fbdfd5..7a0254ccb 100644
--- a/src/System.Management.Automation/engine/runtime/Binding/Binders.cs
+++ b/src/System.Management.Automation/engine/runtime/Binding/Binders.cs
@@ -2034,32 +2034,7 @@ namespace System.Management.Automation.Language
                 return false;
             }
 
-            // If there are any fields, the type is mutable.
-            if (type.GetFields(BindingFlags.Public | BindingFlags.Instance).Any())
-            {
-                return true;
-            }
-
-            // If there are any properties with setters, the type is mutable.
-            var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);
-            for (int index = 0; index < properties.Length; index++)
-            {
-                var property = properties[index];
-                if (property.CanWrite)
-                {
-                    return true;
-                }
-            }
-
-            // If there are any methods other than the property getters, the type might
-            // be mutable, so assume the type is mutable.
-            var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance);
-            if (methods.Length != properties.Length)
-            {
-                return true;
-            }
-
-            return false;
+            return !type.IsDefined<System.Runtime.CompilerServices.IsReadOnlyAttribute>();
         }
 
         private static readonly ConcurrentDictionary<Type, bool> s_mutableValueTypesWithInstanceMembers =
```

Related issue #12411

/cc @mklement0

**Comment by iSazonov** [comment]
We need to compare performance - IsDefined() method may be too.

**Comment by SeeminglyScience** [comment]
True, though I would be very surprised if it was slower than all of the other reflection calls it would replace.

**Comment by iSazonov** [comment]
I don't see using IsReadOnlyAttribute in .Net Runtime repo https://github.com/dotnet/runtime/search?l=C%23&q=IsReadOnlyAttribute

**Comment by SeeminglyScience** [comment]
Check out the right hand side of [this SharpLab example](https://sharplab.io/#v2:D4AQzABATgpghgEwPYDsA2BPCBnALlAVwGNcIBZDAZX2NIG8BfIA).  When a struct has the `readonly` modifier applied to it, it is decorated with that attribute.

**Comment by SeeminglyScience** [comment]
Eh complicating it a bit is that the attribute isn't in `netstandard2.0`. Libraries that target netstandard2.0 will turn this:

```csharp
public readonly struct MyStruct { }
```

into

```csharp
namespace System.Runtime.CompilerServices
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    [AttributeUsage(AttributeTargets.All, Inherited = false)]
    internal sealed class IsReadOnlyAttribute : Attribute
    {
    }
}

[IsReadOnly]
public struct MyStruct { }
```

That makes it a little bit more tricky, and may need to match based on type full name:

```csharp
foreach (var attribute in type.GetCustomAttributes())
{
    if (attribute.AttributeType.FullName.Equals("System.Runtime.CompilerServices.IsReadOnlyAttribute", StringComparison.Ordinal))
    {
        return true;
    }
}
```

That makes performance more of a concern, but it still replaces a lot of reflection calls so hopefully performance is very similar if not better.  Either way, it's cached statically per type so I believe it's worth it.

**Comment by iSazonov** [comment]
>  the attribute isn't in netstandard2.0

.Net runtime does not address the issue in IsDefine()?

**Comment by SeeminglyScience** [comment]
So because the attribute isn't in netstandard2.0, roslyn adds the code to define it as an internal type within the library declaring a readonly struct.

So if my module declares a readonly struct while targeting netstandard2.0, it'll be decorated with `System.Runtime.CompilerServices.IsReadOnlyAttribute, MyModuleAssembly` not `System.Runtime.CompilerServices.IsReadOnlyAttribute, System.Private.CoreLib`

**Comment by iSazonov** [comment]
I guess IsDefine() knows about this?

**Comment by SeeminglyScience** [comment]
Hmm not sure what you mean.  Can't use that method because it only takes a `Type` object, which has assembly identity built into it.

**Comment by iSazonov** [comment]
I guess IsDefined() understand custom IsReadOnlyAttribute() and I hope we have no need a workaround.

**Comment by iSazonov** [comment]
Docs https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.readonlyattribute?view=net-5.0 suggest use reflection.

**Comment by SeeminglyScience** [comment]
That's a different attribute from `IsReadOnlyAttribute`.

If `IsDefined` accounted for this scenario it would be lying, and would lose a ton of performance for the typical case.  If I pass it a `typeref` of `System.Runtime.CompilerServices.IsReadOnlyAttribute, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e` and it returns true for `System.Runtime.CompilerServices.IsReadOnlyAttribute, MyRandomAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=` then that would be pretty confusing for any attribute outside of these edge cases.  Plus, it would have to just do a full name compare like we're doing here.

**Comment by iSazonov** [comment]
In the case I wonder why the attribute is automatically defined for <netstandard2.0.

**Comment by SeeminglyScience** [comment]
Mainly because the other option is to not support `readonly struct` until netstandard2.1

That said, it has zero runtime effect.  It not working with `IsDefined` is impactful for us because we're working with *runtime* types. Static compilers like roslyn already can't use `IsDefined` because they're dealing with `System.Reflection.Metadata` constructs. So they are already mostly just string matching (I guess runtime type reflection is too, it's just cached internally by the CLR).

**Comment by iSazonov** [comment]
Ah, it is for to allow compilation.

If we think about <netstandard2.0 we need to keep workarounds in IsValueTypeMutable() but enhance it with IsDefined() - if no IsReadOnlyAttribute presents we continue the analysis.

**Comment by SeeminglyScience** [comment]
We can also just check that attribute type full name like roslyn does.  I would predict it's at least comparable in terms of both performance and allocations. Even if it's more though, it's cached per type per session so unlikely to be measurable imo.

**Comment by iSazonov** [comment]
@SeeminglyScience Do you want to pull a PR?

**Comment by SeeminglyScience** [comment]
Nah you can mark it up for grabs.
