### ISSUE TITLE
Wpeutil not available

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#12446]
PS7:
````
PS C:\> Wpeutil
Wpeutil: The term 'Wpeutil' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
````

**Comment by vexx32** [comment]
@superbonaci sounds like it's missing from your PATH. If you have something in your Windows PowerShell profile that's adding PATH entries (or removing any from PS7) you'll need to add it to PowerShell 7's profile(s) as well.

**Comment by jcotton42** [comment]
`wpeutil` is only available in Windows PE, not normal Windows. If that is the case then please indicate the version of Windows PE that you're having this issue in.

**Comment by superbonaci** [comment]
I'm on normal windows, not PE.

**Comment by jcotton42** [comment]
Then PowerShell can't find it because it isn't available on that configuration of Windows.
