### ISSUE TITLE
Issue-Question  what difference between event-driven and logging

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12448]
label:Issue-Question  what difference between event-driven and logging in powershell ?

**Comment by vexx32** [comment]
I think we're going to need a lot more information on what exactly you're asking @p0W3RH311, and I'd recommend filling out the question issue template properly so we can get a better idea of what you're looking for here. 🙂

**Comment by p0W3RH311** [comment]
@vexx32 

Hi,

my question is "in powershell logging  iss the same of event-driven or not ?" because in other languages sometimes is the same and sometimes its not the same

**Comment by vexx32** [comment]
Sure, but PowerShell has more than one kind of logging you can use, not to mention the myriad custom logging solutions you can make use of as well.

Here's a decent write up: https://www.fireeye.com/blog/threat-research/2016/02/greater_visibilityt.html
