### ISSUE TITLE
Configure telephony to Microsoft Teams

### ISSUE THREAD

**Issue by terblas** [PowerShell/PowerShell#12454]
Hello, I want to configure the Teams tenant toassign a phone number to my users but when I run the Set-CsUser i get an error saying the OnPremLineURI cannot be found, The user has the phone system license and the office 365 F3 license, I tested in other tenants and I dont get the same error. Does anybody know why I am getting the error?

PS C:\Users\Administrator> Set-CsUser -Identity user@domain -EnterpriseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:+52XXXXXXXXXX
Set-CsUser : A parameter cannot be found that matches parameter name 'OnPremLineURI'.
At line:1 char:95
+ ... priseVoiceEnabled $true -HostedVoiceMail $true -OnPremLineURI tel:+52 ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-CsUser], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Rtc.Management.AD.Cmdlets.SetOcsUserCmdlet

**Comment by vexx32** [comment]
The Teams module is not in this repository, it's a separate module. I'd advise directing this request either over UserVoice or the MS Teams github (if they have one? Not sure).

Alternatively, some of the folks in the community channels may have seen the behaviour before and could potentially help you with it. You can join the PowerShell community on [Slack](//aka.ms/psslack) or [Discord](//aka.ms/psdiscord) and ask around those channels if you like. 🙂
