### ISSUE TITLE
Windows: use the ConPTY APIs with native commands

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#12453]
# Summary of the new feature/enhancement

This affects interactive PSRemoting.  Currently, when running a native command, PowerShell will create that process and redirect stdin/stdout.  However, for commands that bypass stdin/stdout (like calling getc() in native code such as cmd.exe), this doesn't work at all.

# Proposed technical implementation details (optional)

Added in Windows 10 (RS5+) is the new pseudoconsole APIs (https://docs.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session).  We should be able to leverage that receiving all input and output to send back over PSRemoting.

**Comment by bpayette** [comment]
This should be exciting!

**Comment by iSazonov** [comment]
Fir reference https://github.com/PowerShell/PowerShell/issues/7894

**Comment by iSazonov** [comment]
Can this https://github.com/PowerShell/Win32-OpenSSH/issues/1545 block this?

**Comment by iSazonov** [comment]
Make sense to ask on .Net Runtime repo to enhance Process class to support ConPTY redirections?
