### ISSUE TITLE
Additional key binding for completing command suggestions

### ISSUE THREAD

**Issue by regexhater** [PowerShell/PowerShell#12467]
# Summary of the new feature/enhancement
PS Core suggests recently used commands with arguments and flags when typing (as shown below). This is a great feature but it has one significant problem. In order to accept that suggestion, one must press the right arrow key (default) when the cursor is at the last character. The only key binding for the right arrow key is ForwardChar which is also used when moving the cursor in the terminal. It would be great to have separate binding for complete suggestion action without changing the standard navigation of right-left arrow keys. This new binding should probably allow completing suggestion when the cursor is not at the end of the command.
![pscsuggestions](https://user-images.githubusercontent.com/36335136/80139780-4ad92980-85a7-11ea-9db9-75b90521759f.png)

# Expected behaviour
User is able to bind any key eg. TAB to action responsible for completing command suggestions.  Preferable user can use this action while the cursor is not at the end of the command.

**Comment by SeeminglyScience** [comment]
Workaround:

```powershell
Set-PSReadLineKeyHandler -Chord ctrl+i -ScriptBlock {
    param($key, $arg) end {
        $currentIndex = 0
        $buffer = $null
        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref] $buffer, [ref] $currentIndex)
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($buffer.Length)
        [Microsoft.PowerShell.PSConsoleReadLine]::ForwardChar($key, $arg)

        # Comment this line if you don't want to save your initial cursor position.
        [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($currentIndex)
    }
}
```

Though a public method on `PSConsoleReadLine` would be nice /cc @daxian-dbw

**Comment by iSazonov** [comment]
I believe it is for PSReadline repo.
