### ISSUE TITLE
PowerShell 7 and 7.1 on Windows Server 2016 cannot be opened

### ISSUE THREAD

**Issue by Sascha-69** [PowerShell/PowerShell#12476]
# Comment
Couldn't find any other hint, if there are any prerequisites to run PowerShell 7 and later on Windows Server 2016. Therefore I'm trying it here.

# Steps to reproduce

Open PowerShell 7 at Windows Server 2016
# Expected behavior

Should start without throwing the exception.

# Actual behavior

Messagebox "pwsh has stopped working"

<code>Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLogProvider' threw an exception.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Globalization.CultureData.GetNFIValues(NumberFormatInfo nfi)
   at System.Globalization.NumberFormatInfo..ctor(CultureData cultureData)
   at System.Globalization.CultureInfo.get_NumberFormat()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Guid.TryParseExactD(ReadOnlySpan\`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan\`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at System.Management.Automation.Tracing.PSEtwLogProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSEtwLog..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSEtwLog.LogConsoleStartup()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args)</code>

# Environment data

$PSVersionTable can't be provided here, because PS7 is crashing before, but under PS 5.1 it looks like this:

Name|Value
----|-----
PSVersion|5.1.14393.3471
PSEdition|Desktop
PSCompatibleVersion|{1.0, 2.0, 3.0, 4.0...}
BuildVersion|10.0.14393.3471
CLRVersion|4.0.30319.42000
WSManStackVersion|3.0
PSRemotingProtocolVersion|2.3
SerializationVersion|1.1.0.1

**Comment by iSazonov** [comment]
What install package do you use?

**Comment by Sascha-69** [comment]
I'm using the 2 MSI's
PowerShell-7.0.0-win-x64.msi
PowerShell-7.1.0-preview.2-win-x64.msi

**Comment by iSazonov** [comment]
@Sascha-69 We need repo steps to investigate the error. Can you reproduce this on clean system?

**Comment by Sascha-69** [comment]
I have it on at least 3 different 2016 servers, but I'll try to install a clean system this afternoon.

**Comment by iSazonov** [comment]
What is culture on your server?

**Comment by Sascha-69** [comment]
Get-Culture

LCID             Name             DisplayName
----             ----             -----------
1053             sv-SE            Swedish (Sweden)

**Comment by iSazonov** [comment]
I see the stack trace `System.Globalization.NumberFormatInfo.get_CurrentInfo()` so I guess you change a number format on your system?

**Comment by iSazonov** [comment]
Can you share `[System.Globalization.NumberFormatInfo]::CurrentInfo`? (From Windows PowerShell)

**Comment by Sascha-69** [comment]
was a bit a surprised, thought we were using English, but here are the requested details.
Thanks to spend your time on it.

CurrencyDecimalDigits    : 2
CurrencyDecimalSeparator : ,
IsReadOnly               : False
CurrencyGroupSizes       : {3}
NumberGroupSizes         : {3}
PercentGroupSizes        : {3}
CurrencyGroupSeparator   : .
CurrencySymbol           : kr
NaNSymbol                : ¤¤¤
CurrencyNegativePattern  : 8
NumberNegativePattern    : 1
PercentPositivePattern   : 0
PercentNegativePattern   : 0
NegativeInfinitySymbol   : -∞
NegativeSign             : -
NumberDecimalDigits      : 2
NumberDecimalSeparator   : ,
NumberGroupSeparator     :  
CurrencyPositivePattern  : 3
PositiveInfinitySymbol   : ∞
PositiveSign             : +
PercentDecimalDigits     : 2
PercentDecimalSeparator  : ,
PercentGroupSeparator    :  
PercentSymbol            : %
PerMilleSymbol           : ‰
NativeDigits             : {0, 1, 2, 3...}
DigitSubstitution        : None

0
1
2
3
4
5
6
7
8
9

**Comment by Sascha-69** [comment]
Even if I don't really get it, why this is disturbing PowerShell 7 to load , it is working when it is switched to English.

**Comment by iSazonov** [comment]
@Sascha-69 Thanks! Please share your OS version and confirm that you install latest updates.

I open new issue in .Net Runtime repo and you can monitor it status (perhaps they ask you to share more info)

**Comment by Sascha-69** [comment]
Thanks a lot, will provide the details in the new .Net Runtime rep thread.

**Comment by iSazonov** [comment]
@Sascha-69 .Net team ask to report the issue to Windows team using Windows 10 Feedback Hub. They think it is OS level issue. I think so too. I guess it is a localization bug.
If you have a support contract you could open a case and send Windows team traces and logs.

Thanks for your report!

/cc @SteveL-MSFT for information.
