### ISSUE TITLE
Interrupted Tab Completion Hangs the Shell

### ISSUE THREAD

**Issue by SchrodingerZhu** [PowerShell/PowerShell#12475]
# Steps to reproduce
On linux, type anything that may show the candidates list and then press tab and `Ctrl-C`
```powershell
syst<tab>
🕙[ 10:22:44 ] λ systemctl
systemctl                       systemd-hwdb                    systemd-run
systemd-analyze                 systemd-id128                   systemd-socket-activate
systemd-ask-password            systemd-inhibit                 systemd-stdio-bridge
systemd-cat                     systemd-machine-id-setup        systemd-sysusers
systemd-cgls                    systemd-mount                   systemd-tmpfiles
systemd-cgtop                   systemd-notify                  systemd-tty-ask-password-agent
systemd-delta                   systemd-nspawn                  systemd-umount
systemd-detect-virt             systemd-path                    systemmonitor
systemd-escape                  systemd-repart                  systemsettings5
systemd-firstboot               systemd-resolve                 systool

/usr/bin/systemctl
```
Then the candidates list disappears (which is expected) but the whole shell hangs.

# version
PowerShell 7.1.0-preview.1 and PowerShell 7.1.0-preview.2

# addons
starship 0.38.1 

# profile
```powershell
# Shows navigable menu of all options when hitting Tab 

Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete

 # Autocompletion for arrow keys

Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward 
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward

Invoke-Expression (&/home/schrodinger/.cargo/bin/starship init powershell)   
```

**Comment by fMichaleczek** [comment]
@SchrodingerZhu Why you think the issue is more on PowerShell side than Starship ?
First please upgrade Starship to the latest version v0.40.1, maybe the bug is on this side.

**Comment by vexx32** [comment]
Hi @SchrodingerZhu!

PSReadLine is maintained in a separate repository; can you please file this issue in https://github.com/PowerShell/PSReadLine instead? 😊

**Comment by SchrodingerZhu** [comment]
@fMichaleczek @vexx32 Ok, thanks. Tested without starship, the problem reproduced. As the completion feature belongs to PSReadLine,I will migrate this issue.

**Comment by SchrodingerZhu** [comment]
Moved to https://github.com/PowerShell/PSReadLine/issues/1487.
