### ISSUE TITLE
test based-comment

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12477]
Hi guys :)

pester is awesome framework to testing code but sometimes we need test code ad-hok and quickly...the idea is to provide a _test based-comment_ . for this we need:

**1) new commun parameter <switch> for example -testDoc
2) a comment based help with .EXAMPLE section
3) and of course a code to test**

for example we assume we have a test-me function

```
<#
.SYNOPSIS
 test-me 
.DESCRIPTION
 test-me function
.EXAMPLE
test-me 5 6
11

.EXAMPLE
test-me 5
10

.EXAMPLE
test-me 4
3
#>
function test-me {
  param($a,$b=5)
  $a+$b
} 
```

and then with the new commun switch **-testDoc**

### result

```
PS > test-me -testDoc

Failed Example
    test-me 4
Expected:
    9
Got:
    3

1 item(s) had failures 1 of 3 
```

we can use this technique with functions or scripts that have comments-based-help.

### what benefits

1) he will encourage everyone to write good comments and especially good examples

2) it will help us quickly test our code

3) it's not a substitute for pestering but another toolkit

**Comment by iSazonov** [comment]
It is implemented in Jupyter Notebooks  https://devblogs.microsoft.com/powershell/public-preview-of-powershell-support-in-jupyter-notebooks/

**Comment by p0W3RH311** [comment]
@iSazonov 

thanks its awesome article :) but the idea is to generalise this technique

**Comment by iSazonov** [comment]
I think it can only work in a sandbox for security reasons.

**Comment by vexx32** [comment]
You should also be able to use Pester to do something like this if you want, so I don't see a reason to try to create something that already exists, except also taking up a parameter slot that someone might want to use for something else (or may already be using for some other purpose).

**Comment by p0W3RH311** [comment]
@iSazonov 

hi, thanks :)

I am with you, security is an essential thing...but all executable codes have a security problem, even pester or ETS or even some validation attributes.

**Comment by p0W3RH311** [comment]
@vexx32 

hi thanks,

pester does not have a technique like this ... this technique has many benefits and allows the author to test his code quickly and simply ... also it allows you to validate the examples in the comments ... also it allows to properly write comments by all authors

**Comment by vexx32** [comment]
Pester does not have a built-in way of handling this, but you can retrieve this information with Get-Help and test it yourself. Either way, I think this would be more appropriate as a feature request for Pester than all of PowerShell.
