### ISSUE TITLE
Powershell Snap not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by batocciero** [PowerShell/PowerShell#12481]
# Steps to reproduce
Power shell version 7.0 installed with sudo snap install powershell --classic
# Actual behavior
Failed to load, error: /snap/powershell/104/opt/powershell/../../lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
Failed to bind to CoreCLR at '/snap/powershell/104/opt/powershell/'
Failed to create CoreCLR, HRESULT: 0x80008088

**Comment by fMichaleczek** [comment]
Hi @batocciero !

Can you move your issue to the [powershell-snap](https://github.com/PowerShell/PowerShell-Snap)  repository ?

https://github.com/PowerShell/PowerShell-Snap/issues/65

Thank you
