### ISSUE TITLE
When execute some command, the font will changed.

### ISSUE THREAD

**Issue by onebits** [PowerShell/PowerShell#12490]
Windows 10, Chinese language version.
Powershell 7 Preview 2.

Changed the font to other font. Jetbrains Mono. 
When execute some command, the powershell font will changed to default font.
Explame: 
ping command.
The command was not execute:
![befor](https://user-images.githubusercontent.com/40101424/80286215-ac8ec480-875c-11ea-9d43-8b3ff3d58d6f.png)

The command is running...
![after](https://user-images.githubusercontent.com/40101424/80286222-b0224b80-875c-11ea-8339-a310032b6524.png)

**Comment by iSazonov** [comment]
@onebits Please remove PSReadline and check again.

**Comment by onebits** [comment]
> @onebits Please remove PSReadline and check again.

Thank u, But its not worked.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please comment?

**Comment by iSazonov** [comment]
Maybe @Dhowett has any thoughts.

**Comment by DHowett** [comment]
This is a side effect of https://github.com/PowerShell/PSReadLine/issues/964

When PSReadline changes the codepage, the display font is changed to match.

**Comment by DHowett** [comment]
If PowerShell is doing the same codepage maintenance as PSReadline (it might be), this would happen with the module removed.
