### ISSUE TITLE
Compare-Object doesn't respect IEquatable<T>

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12498]
Input objects that implement `IEquatable<T>` but not also `IComparable<T>` aren't properly compared in terms of equality.

The root cause is that a comparison method is used that requires not just an _equality_ test, but one for _ordering_ values: if the `.Equals()` call in `.TryCompareValue()` indicates `false`, the result _isn't_ used (which is appropriate for `Object.Equals()`, but not for `IEquatable<T>.Equals()`) - instead, the code falls back to `.ToString()` comparison, which for types that don't override this method reports the same value - the full type name - for _all_ instances, causing all instances to compare as equal.

See https://github.com/PowerShell/PowerShell/blob/16ec1cc32f9e60c9d76b074c865c32a5d2acf5a2/src/System.Management.Automation/engine/LanguagePrimitives.cs#L883 and https://github.com/PowerShell/PowerShell/blob/16ec1cc32f9e60c9d76b074c865c32a5d2acf5a2/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs#L222

# Steps to reproduce

```powershell
# Define class Foo that wraps an integer and implements IEquatable<T>
# to return true if two instances wrap the same integer value.
Add-Type 'public class Foo : System.IEquatable<Foo> { public int Bar = 0; public bool Equals(Foo other) { return Bar == other.Bar; } public override bool Equals(object o) { return o is Foo && Equals((Foo) o); } public override int GetHashCode() { return Bar; } }'

$o1 = [Foo]::new(); $o1.Bar = 1
$o2 = [Foo]::new(); $o2.Bar = 2

# OK
$o1.Equals($o2) | Should -BeFalse

# FAILS, because $o1 and $o2 are unexpectedly considered equal.
Compare-Object $o1 $o2 | Should -Not -BeNullOrEmpty
```

# Expected behavior

Both tests should succeed.

# Actual behavior

The 2nd test fails, because `$o1` and `$o2` are unexpectedly considered equal, so `Compare-Object` produces no output. 

```none
Expected a value, but got $null or empty.
```

# Environment data

```none
PowerShell Core 7.1.0-preview.2
```

**Comment by iSazonov** [comment]
"Ordering" is a fundamental nature of the cmdlet. I wonder why you ask about equality for it. 
Also if you implement a class a best practice is to implement ToString() method.

**Comment by mklement0** [comment]
> "Ordering" is a fundamental nature of the cmdlet.

The cmdlet offers you to determine _equal_ and _different_ objects - where do you see _ordering_?

> Also if you implement a class a best practice is to implement ToString() method.

Even if you do override `.ToString()`, signaling equality via instances' string representation is not the appropriate mechanism - that is what `IComparable` and / or `Equatable` are for.

**Comment by iSazonov** [comment]
:-) Sorry, I thoughts was about output with "=>".

**Comment by iSazonov** [comment]
Windows PowerShell has the same behavior. Fixing `TryCompare()` would be a breaking change and not only in the scenario. There is a `Compare()` method too with the same behavior. I believe the design was to implement exactly `compare`, not `equality` in the methods and throw if objects are not comparable. I believe we could create Equals() methods in the call tree and use it in Compare-Object cmdlet.
