### ISSUE TITLE
Move admin\monad\src\Activities\Generated\Update-PowerShellActivitySource.ps1 to Github

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#1249]
Update-PowerShellActivitySource.ps1 is the script to generate activity source code for a given PS cmdlet. This script needs to be refactored to work in Github.

**Comment by vors** [comment]
@mirichmo also found another script to port: 
```
admin\monad\src\cimSupport\cmdletization\xml\generate.ps1
```

It needs to be run when we change cdxml schema

**Comment by lzybkr** [comment]
The code generated by that tool isn't great - I did something similar for the types.ps1xml parser and ended up fixing it to be much faster and use much less memory.

Analyzing cdxml modules does show up as a hotspot, so I hope we find some time to fix this at some point. Also, given that we don't change the cdxml schema much, I think it's reasonable to manually change both on demand.

**Comment by iSazonov** [comment]
@daxian-dbw Seem we can close the Issue.

**Comment by daxian-dbw** [comment]
@iSazonov Yeah! Workflow code is gone for good :)
