### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by icebluey** [PowerShell/PowerShell#12499]
# Expected behavior
$ pwsh
PowerShell 7.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Cannot get required symbol EVP_rc2_cbc from libssl
Aborted (core dumped)

```none
```
# Environment data
// OS and PS version
$ dpkg -l | grep -i powershell
ii  powershell                                 7.0.0-1.ubuntu.16.04                         amd64        PowerShell is an automation and configuration management platform.

// openssl version
$ openssl version
OpenSSL 1.0.2u  20 Dec 2019
```none

**Comment by iSazonov** [comment]
Please follow instructions and install all dependencies
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7

**Comment by icebluey** [comment]
All dependencies (libc6, libgcc1, libgssapi-krb5-2, liblttng-ust0, libstdc++6, zlib1g, libssl1.0.0, libicu55) have already been installed before, and installation of powershell was successful. Everything looks good.
Just don't  know why it aborted.

**Comment by iSazonov** [comment]
I guess you need to fix "OpenSSL 1.0.2u" - it is not libssl1.0.0
