### ISSUE TITLE
Exported commands empty for azuread & azureadpreview on macOS

### ISSUE THREAD

**Issue by mcnahum** [PowerShell/PowerShell#12501]
# Steps to reproduce

Tested on new VM to be sure it's 100% repro.

install Powershell:

download powershell-7.0.0-osx-x64.pkg from https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0

run the below command: 
sudo installer -pkg /Users/marc/Downloads/powershell-7.0.0-osx-x64.pkg  -target /

Start powershell
Install-module AzureADPreview -Verbose

Get-Module azureadpreview -ListAvailable

    Directory: /Users/marc/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     2.0.2.89              AzureADPreview                      Desk      

# Expected behavior

having the list of working command and be able to run command like: "Connect-AzureAD"

# Actual behavior

Connect-AzureAD                         
Connect-AzureAD: The term 'Connect-AzureAD' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by vexx32** [comment]
You'll need to follow up with the Azure module team on that one, their module is not something the PowerShell team have any control over. As far as I'm aware, the AzureAD module hasn't been updated to work with PowerShell 7, and the majority of development has been for the newer `Az` module.

Probably the best bet would be follow up here, unless someone else knows where a better place for feedback for the older module is:

https://github.com/Azure/azure-powershell
