### ISSUE TITLE
Error mode command line argument

### ISSUE THREAD

**Issue by MarkPflug** [PowerShell/PowerShell#12515]
# Summary of the new feature/enhancement

Using powershell in a build script (called from MSBuild) I have run into issues several times where failures in the script aren't propagated out of the Exec task. Powershell returns exit code 0, even when the script encountered problems. This is reasonable behavior in many common use cases. However, in a build script, one typically wants the build to "fail fast" when an issue is encountered.

In my particular case, I "fixed" the issue by adding:

$ErrorActionPreference = 'Stop'

... do the stuff

trap {
	"Build failed: $_"
	exit -1
}

This works, but isn't an ideal solution either, because this script will exit powershell if run interactively and an error is encountered. There is probably a way to make this behave more sanely in an interactive session, but it feels clumsy to have to specially craft any ps1 script that is intended to be used in a build.

My proposal is to add a new command line switch to pwsh.exe, that will cause it to exit with a non-zero exit code on the first failure, rather than the default behavior of continuing and exiting with 0. This would make it *much* easier to use from in a build script scenario where any unhandled failure should be considered critical.

# Proposed technical implementation details (optional)

add a cmdline switch such as:
`pwsh.exe -ExitOnError`

In the presence of this error scripts run as if $ErrorActionPreference = 'stop' is set and will return a non-zero exit code when the first error is encountered.

**Comment by iSazonov** [comment]
There is no standard for exit status.  https://en.wikipedia.org/wiki/Exit_status
You should return codes expected by specific parent process.
So you workaround is right way.
