### ISSUE TITLE
Module PnPDevice has a flaw

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShell/PowerShell#12510]
The CDXML cmdlet `Get-PnPDevice` has a script property *ProblemDescription* which reads problem descriptions from a local resource file using `Import-LocalizedData`. Since no -BaseDirectory is specified, the property is populated only when the user (accidentally) happens to have set the current path to the module base.

A complete problem investigation and suggested fix can be found [here](https://powershell.one/wmi/cdxml-intro#buggy-using-text-resources).

# Steps to reproduce
This fails. *ProblemDescription* is always empty:
```powershell
Get-PnPDevice | Select-Object -Property Name, ProblemDescription
```
This works (workaround, current folder set to module base):
```powershell
# temporarily switch current path to module base
Push-Location -Path (Get-Module -Name PnPDevice).ModuleBase
# now *ProblemDescription* is populated
Get-PnPDevice | Select-Object -Property Name, ProblemDescription
# restore path
Pop-Location
```
# Expected behavior
*ProblemDescription* should always be populated.

# Actual behavior
*ProblemDescription* is always empty except if the user has set the current path to the module base.

The problem is in the file *PnPDevice.Types.ps1xml*:

```powershell
notepad "$PSHome\Modules\PnpDevice\PnPDevice.Types.ps1xml"
```
To fix the problem, simply replace this line:

```powershell
Microsoft.PowerShell.Utility\Import-LocalizedData  LocalizedData -filename PnpDevice.Resource.psd1
```

with this line

```powershell
Microsoft.PowerShell.Utility\Import-LocalizedData  LocalizedData -filename PnpDevice.Resource.psd1 -BaseDirectory (Get-Module -Name PnPDevice).ModuleBase
```

# Environment data
```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anmenaga** [comment]
This is a bug in Windows PS module `PnPDevice`; the fix has to go into Windows code base.

**Comment by TobiasPSP** [comment]
Thanks. Can you hint where these issues can be posted?

**Comment by iSazonov** [comment]
@TobiasPSP You can use Windows 10 feedback tool or UserVoice site.
