### ISSUE TITLE
Please add a "Run with PowerShell 7" context menu

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#12524]
I noticed that right-clicking a `.ps1` file doesn't provide a PowerShell 7 context menu entry like ...
- `PowerShell 7 > Run script`, or
- `PowerShell 7 > Run script as Administrator`.
<br/>

Could you please add such feature to the installer?
<br/>

<img alt="Add 'run with' context menus to Explorer" src="https://user-images.githubusercontent.com/9283914/80622601-4e5a2e00-8a49-11ea-82fa-990a05885aba.png">

**Comment by iSazonov** [comment]
Do anybody know Windows or WiX API for the feature?

**Comment by codingfunwoody** [comment]
I also missed the context menus shortcut by choco installation

**Comment by SetTrend** [comment]
Let's bubble this up ...
