### ISSUE TITLE
Can not find Microsoft.Management.Infrastructure error

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#12522]
I am writing a multi-platform c# command line application using .NET Core 3.1 that will need to work as a single executable. I am using Visual Studio 2019 (16.5.4). My OS is Windows 10.0.18363.778 and I intentionally did NOT install Powershell 7.  Added Microsoft.Powershell.SDK 7.0.0 nuget package to the project. 
# Steps to reproduce
1) Compile the project with a specific rid (Win-x64) : If I do NOT add a RID there is no problem.
2) Inside Code block
```
using (PowerShell PowerShellInst = PowerShell.Create())
{
PowerShellInst.Invoke(); 
}
```
# Expected behavior
Invokes Powershell and runs the script block created.
```none

```

# Actual behavior
Throws FileNotFound Execption for  Microsoft.Management.Infrastructure file.
```none

```

# Environment data

Single I dont have the shell installed, I am copying info from debuging my application.
PSVersion=7.0.0
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3

When I check the directory for non RID specified build output, I fnd the Microsoft.Management.Infrastructure under runtimes whereas, when build with Win-x64 file is not there.

**Comment by iSazonov** [comment]
Try Win7-x64.

**Comment by erenturkm** [comment]
RID Win7-x64 works, however I do not want to use it for long.   Since it creates binaries specific to Win 7/Win Server 2008 and these OS's are unsupported by .net core 3.1.
 
When can we expect this limitation to be lifted?

**Comment by iSazonov** [comment]
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#windows-rids

I think win-x64 is for .Net Core only but MMI is Windows-only.

**Comment by erenturkm** [comment]
iSazanov, I couldnt understand what you intended to say. I have several other packages in my application not just PS. Its quite possible that they will stop supporting Win7-x64 platform for their packages since it is not supported by .net core 3.1. PS team will have to upgrade Microsoft.Management.Infrastructure.dll and related resources for newer/supported OS's. I am asking when we can expect this?

**Comment by iSazonov** [comment]
MMI is deprecated and you shouldn't use it in new projects if possible. MSFT has no plan invest in MMI or port it on Linux or MacOS. Also I believe MMI package is linked to Win7-x64 RID.
We have to accept this as-is for now.

Perhaps @adityapatwardhan could add more info.

**Comment by erenturkm** [comment]
I am not using MMI intentionally, here is what I do:
I have the latest  Microsoft.Powershell.SDK Nuget package (7.0.0) installed as a dependency per advice from [this blog](https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/).
I am using "using System.Management.Automation" at the start of my code.
I am using below 2 lines to call PS:
PowerShell PowerShellInst = PowerShell.Create()
PSOutput = PowerShellInst.Invoke()

Is there anything else I can do to NOT use MMI?

**Comment by iSazonov** [comment]
SMA has dependency on MMI and compile RID is Win7-x64. If you compile a project with another RID and get File not found exception you could manually copy MMI dll to home folder.
Perhaps MMI will be removed in future.

**Comment by erenturkm** [comment]
Currently Powershell SDK is forcing us to create unsupported binaries for our .net Core 3.1 applications. I see this is not fixed in Ver 7.1 Preview2. Can we get an indicative timeline on when we can expect this to happen?

**Comment by iSazonov** [comment]
PowerShell 7.0 is LTS - it will be supported while .Net Core 3.1 is supported.

**Comment by erenturkm** [comment]
It's not support of Powershell or .NET Core itself. Since .net Core 3.1 is not supported on Win7/Win Server 2008R2, Nobody  (.net Core team, all 3rd party library authors such as myself) is testing their code when compiled with Win7-x64. When I am forced to compile MY code under this RID, I will probably be stuck getting support from other nuget package vendor/authors.

**Comment by iSazonov** [comment]
You can see supported OS [here ](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md#windows). Win7 SP1+ is supported.

You can compile your code with another RID (Win81-x64, Win10-x64) and also put MMI dll manually.

**Comment by erenturkm** [comment]
1) You are correct for Win7 SP1+ support, I wasnt clear. I ment Win Server 2008 R2 since this app is for servers. So argument is still valid.
2) I tested with Win-x64 with copying MMI manually it works. I can live with that. The only side effect is for Single exe publishing. Is there a way to tell dotnet.exe to add this dll with publish command?

**Comment by iSazonov** [comment]
> Is there a way to tell dotnet.exe to add this dll with publish command?

I think yes. You could ask in MSBuild repo.

**Comment by drmcclelland** [comment]
My application is a .NET Core 3.1 console application, and for anyone else running into this issue: (System.IO.FileNotFoundException - Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.)

The key takeaway is the CSPROJ has to have the following value:

`<RuntimeIdentifier>win7-x64</RuntimeIdentifier>`

I am using the following nuget package:

`<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.0.3" />`

Here's the sample PowerShell code I was running:

```
                using (var ps = PowerShell.Create())
                {
                    var re = ps.AddScript("Get-Process");
                    var results = re.Invoke();
                }

```
