### ISSUE TITLE
Progress of Get-DscResource remains visible for duration of execution

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#12521]
The progress bar(s) produce by `Get-DscResource` remain visible for the duration of execution well after `Get-DscResource` completes.  Examining the PowerShell.Streams.Progress suggests that PSDesiredStateConfiguration.psm1 does not write a "Completed" record for its activities.  Searching the implementation file by invoking

```PowerShell
Import-Module PSDesiredStateConfiguration -PassThru | 
    % Path | 
    % { Get-Content $_ } | 
    ? {($_ -like '*-Completed*') -or ($_ -like '*Write-Progress*')}
```

outputs

```none
        Write-Progress -Id 1 -Activity $LocalizedData.LoadingDefaultCimKeywords
        Write-Progress -Id 2 -Activity $LocalizedData.GettingModuleList
            Write-Progress -Id 3 -Activity $LocalizedData.CreatingResourceList
```

which suggests that there are no calls to `Write-Progress -Completed` that correspond to the module's activities.

The absence of a "Completed" record differs from other commands like `Invoke-WebRequest` that also write progress.  An example PowerShell.Streams.Progress for an invocation of that command (using the structure of the repro below) includes a "Completed" record as follows:

```none
Name                  Count
----                  -----
0, Processing          1026
0, Completed              1
```

# Steps to reproduce

```powershell
$sb = {Get-DscResource Archive -Module PSDesiredStateConfiguration}
. $sb | Out-Null
sleep 5
$ps = [powershell]::Create().AddScript($sb)
$ps.Invoke() | Out-Null
$ps.Streams.Progress | group ActivityId,RecordType | select Name,Count
```

# Expected behavior

## at sleep

![image](https://user-images.githubusercontent.com/11237922/80611046-f42c7f00-89ee-11ea-9079-8fb81ef2df9d.png)

## at completion

```none
call complete

Name          Count
----          -----
1, Processing     1
2, Processing     1
3, Processing     1
1, Completed      1
2, Completed      1
3, Completed      1
```

# Actual behavior

## at sleep
![image](https://user-images.githubusercontent.com/11237922/80611119-0d353000-89ef-11ea-8001-bc0544a15306.png)

## at completion

```none
call complete

Name          Count
----          -----
1, Processing     1
2, Processing     1
3, Processing     1
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by iSazonov** [comment]
Please move the report to https://github.com/PowerShell/PSDscResources

**Comment by alx9r** [comment]
@iSazonov I'd like to [transfer the issue](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) to that repo, but the [transfer issue button](https://help.github.com/assets/images/help/repository/transfer-issue.png) is not shown for me.  If you have that button, can you transfer it for me?

**Comment by iSazonov** [comment]
I haven't permissions. You could close the issue and open new one there.

**Comment by alx9r** [comment]
@iSazonov I'm planning to leave this issue open and here until I get some clarity on #12536.
