### ISSUE TITLE
Get-StringHash (something like Get-FileHash but not file based)

### ISSUE THREAD

**Issue by Conan1989** [PowerShell/PowerShell#12531]
# Summary of the new feature/enhancement
Hi,
Request a native cmdlet for getting a hash value (MD5, SHA256, etc) of an inputted string.
eg - something like Get-FileHash  ... but not file based

justification. I've seen requirements for such a thing around the place, but with incorrectly implemented (hopefully the below isn't too far off) and sub optimal solutions. eg bad code from SE and write to disk, hash from disk with Get-FileHash

# Proposed technical implementation details (optional)
something like the following maybe

```powershell
function Get-StringHash {
    [CmdletBinding()]
    [OutputType([System.String])]
    param (
        [ValidateScript({ ![System.String]::IsNullOrEmpty($PSItem) })][System.String]$inputString,
        [ValidateSet('MD5', 'SHA1', 'SHA256', 'SHA384', 'SHA512')][System.String]$hashAlgo
    )
    process {
        $ErrorActionPreference = 'stop'
        Set-StrictMode -Version 'latest'

        $inputBytes    = [System.Text.Encoding]::UTF8.GetBytes($inputString)
        $hashAlgorithm = [System.Security.Cryptography.HashAlgorithm]::Create($hashAlgo)
        # [System.Security.Cryptography.HashAlgorithmName]

        return ( [System.BitConverter]::ToString( $hashAlgorithm.ComputeHash($inputBytes) ) -replace '-' )
    }
}

```

**Comment by scriptingstudio** [comment]
Provide a default value or validation for $hashAlgo, otherwise you'll get
```
Get-StringHash : You cannot call a method on a null-valued expression.
At line:1 char:1
+ Get-StringHash $s
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-StringHash], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Get-StringHash
```

**Comment by iSazonov** [comment]
@Conan1989 Our workflow is that you should create RFC in PowerShell-RFC repository for discussion and voting.

**Comment by alx9r** [comment]
I have an implementation of Get-StringHash that is used by many of our internal powershell modules.  For a built-in implementation to be useful in our organization it would need to implement the whole matrix of a significant number of common input (strings, byte arrays, etc), algorithms (CRC, MD5, SHA256, etc) and output formats (hex, base64, ascii, etc).  

For most of our use cases we need the property `($s1 | Get-StringHash) -eq ( $s2 | Get-StringHash)` to hold for all cases where `$s1` and `$s2` are the "same".  I suspect that is the property needed by many users looking to convert a string to a hash.  I have found a significant number of edge cases related to text encoding, EOLs, etc on both the input and output side that prevent that property from holding across PowerShell, .NET, and OS versions and editions.  Our organization tests for that property across the subset of combinations for which we need the property to hold and make changes to our implementation to correct for edge cases.  Doing that for all possible conditions seems like a substantial undertaking.  

I don't think the sort of testing to make that property hold is occurring for other PowerShell commands currently; there are combinations of PowerShell versions where `Set-Content` and `Get-Content` roundtrips aren't isomorphic, for example.  So if you write a string to a file with PowerShell 5 and read it with PowerShell 7 you can end up with significant observable differences some of which break equality.  It's not obvious that there is a conversion that completely corrects for the differences.  `Get-StringHash` would add another layer to that problem.

**Comment by Conan1989** [comment]
> 
> 
> @Conan1989 Our workflow is that you should create RFC in PowerShell-RFC repository for discussion and voting.
> But it is already https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0018-Get-StringHash.md

Thanks. Is there any way to try get some movement on that RFC? Seems it's been idle since 2017

**Comment by iSazonov** [comment]
@Conan1989 You can contribute and implement the RFC.

**Comment by iSazonov** [comment]
I forget about https://github.com/PowerShell/PowerShell/pull/3395

**Comment by lahell** [comment]
What would be the expected result if `Get-FileHash` becomes an alias for `Get-Hash` and someone is already using `'C:\file.txt' | Get-FileHash` or `(Get-ChildItem).FullName | Get-FileHash` in their script? Should they get `FileHashInfo` or `StringHashInfo` as output? I as a user would expect to get `FileHashInfo` but if I'm reading the [RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/Archive/Experimental/RFC0018-Get-StringHash.md) correctly the output would be `StringHashInfo` which could break many existing scripts.

**Comment by lahell** [comment]
It will not be obvious to users that `Get-FileHash` is an alias because it will be the only one with a name like `Verb-Noun`.

Adding a new cmdlet named `Get-StringHash` will not break existing scripts, will probably not be as complicated to implement and it will not cause confusion.

**Comment by lahell** [comment]
I have tested the code from [https://github.com/iSazonov/PowerShell/tree/gethashrfc](https://github.com/iSazonov/PowerShell/tree/gethashrfc) and it looks like it will fail [tests in DefaultCommands.Tests.ps1](https://github.com/PowerShell/PowerShell/blob/6fa7260db9a4574b124661edf438b9939d2faceb/test/powershell/engine/Basic/DefaultCommands.Tests.ps1#L569-L591) unless we change the tests or the [GetScriptBlock for DisplayName in AliasInfo](https://github.com/PowerShell/PowerShell/blob/6fa7260db9a4574b124661edf438b9939d2faceb/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L571-L585).

**Comment by boernsen-development** [comment]
Please reopen this :)

**Comment by boernsen-development** [comment]
Workaround

```powershell
$string = "any string"
Get-FileHash -InputStream ([IO.MemoryStream]::new([Text.Encoding]::Utf8.GetBytes($string)) -Algorithm SHA256 | Select-Object -ExpandProperty Hash
```
