### ISSUE TITLE
Function Definition AST doesn't say where the name of the function actually starts

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#12540]
# Summary of the new feature/enhancement

The Function Definition AST has a few properties:

* `ast.Extent.StartColumnNumber`: tells you where the definition starts (aka where `function`, or `filter` keywords begin)
* `ast.Name`: tells you the name of the function or filter (`Get-Foo`)
* `ast.Extent.Text`: tells you the full text: `function foo { ... }`

There is no property that says "this is where the name begins (or ends for that matter)". This means that document highlighting in PSES (this is the feature that lets you click on a reference and it will highlight the definition in the file) involves computing this... like so:

https://github.com/PowerShell/PowerShellEditorServices/pull/1279

It's silly that we have to do this when we have the AST at our finger tips.

# Proposed technical implementation details (optional)

If the AST has the tokens in it, that would be ideal... but if not, just having something that says "this is the location of the name" would be incredibly helpful.

**Comment by vexx32** [comment]
I don't see any reason _not_ to have the function name itself in that AST member. It's kinda weird that it doesn't tbh. 😁

**Comment by rjmholt** [comment]
Wait, it is an AST member:

```
> { function x {} }.Ast.EndBlock.Statements[0]

IsFilter   : False
IsWorkflow : False
Name       : x
Parameters :
Body       : {}
Extent     : function x {}
Parent     : function x {}

```

The problem I think is a more general one: every time you need to deal with tokens within an AST that aren't themselves ASTs, you're forced to reinvent basic token processing... So `ast.Name` has no extent, meaning you're forced to scan through the tokens looking for it. It would be nice if ASTs came with something like their first token index in the array or something, to allow fast random access.

**Comment by rjmholt** [comment]
Ideally I'd like ASTs to come with their own token list, but I suspect that wouldn't be nice for allocation/garbage collection

**Comment by vexx32** [comment]
A list of tokens is probably overkill for most things, but something like `Name` could store the actual token there instead. If that ship has sailed, we could add a `NameToken` member for it.

**Comment by TylerLeonhardt** [comment]
@rjmholt `{ function x {} }.Ast.EndBlock.Statements[0]` this doesn't seem to give you the startColumnNumber.

**Comment by rjmholt** [comment]
Try

```
{ function x {} }.Ast.EndBlock.Statements[0].Extent
```

**Comment by TylerLeonhardt** [comment]
@rjmholt 

```
{ function x {} }.Ast.EndBlock.Statements[0].Extent.StartColumnNumber
3
```

That's not the value I'm looking for :(

**Comment by rjmholt** [comment]
Oh sorry, I was responding to this:

> I don't see any reason not to have the function name itself in that AST member

**Comment by rjmholt** [comment]
It seems to me that ASTs would ideally have tokens for their properties rather than strings, but that ship has sailed

**Comment by SeeminglyScience** [comment]
Yeah I've been burned by this a few times as well.  It's especially annoying because of how forgiving the parser is here:

```
function


test


{}
```

I always wished the name was a `StringConstantExpressionAst` of some sort.  Though, the name isn't exactly parsed like most bare word strings so that might be misleading. While not impactful in this exact use case, part of the problem is that the extent text doesn't always match up to the function name. Take this example:

```
{ function t'est' {} }.Ast.EndBlock.Statements[0]
# IsFilter   : False
# IsWorkflow : False
# Name       : test
# Parameters :
# Body       : {}
# Extent     : function t'est' {}
# Parent     : function t'est' {}
```

**Comment by rjmholt** [comment]
Yeah I've been worrying about the extent text too for precisely this reason.

An AST seems more appropriate than a token in this case, although it would be nice to have a way to link ASTs and tokens easily...

**Comment by TylerLeonhardt** [comment]
> Yeah I've been burned by this a few times as well.  It's especially annoying because of how forgiving the parser is here:
> 
> ```
> function
> 
> 
> test
> 
> 
> {}
> ```

Dang... Does this means I have to fix my PR in PSES to take into account newlines? 😢

**Comment by SeeminglyScience** [comment]
> An AST seems more appropriate than a token in this case, although it would be nice to have a way to link ASTs and tokens easily...

Yeah if I had a nickle every time that would have come in handy...

In EditorServicesCommandSuite I started *sort of* linking these together.  Everything gets passed an object that has:

1. The AST closest to the cursor
1. A `LinkedList<Token>` node of the token closest to the cursor

Then a bunch of extension methods to make linking them and searching within an extent easier.  It works, but it's super hacky.  I don't know how much extra GC pressure linking them properly would add, but I'm tempted to say it would be worth it.

> Dang... Does this means I have to fix my PR in PSES to take into account newlines? 😢

[Well...](https://media.giphy.com/media/gZGlQX3wWAV1u/giphy.gif)

**Comment by TylerLeonhardt** [comment]
Putting this code here for anyone else who stumbles upon this issue but also wants the start column and line of the _actual_ function name:

```csharp
        private static (int, int) GetStartColumnAndLineNumbersFromAst(FunctionDefinitionAst ast)
        {
            int startColumnNumber = ast.Extent.StartColumnNumber;
            int startLineNumber = ast.Extent.StartLineNumber;
            int astOffset = 0;

            if (ast.IsFilter)
            {
                astOffset = "filter".Length;
            }
            else if (ast.IsWorkflow)
            {
                astOffset = "workflow".Length;
            }
            else
            {
                astOffset = "function".Length;
            }

            string astText = ast.Extent.Text;
            // The line offset represents the offset on the line that we're on where as
            // astOffset is the offset on the entire text of the AST.
            int lineOffset = astOffset;
            for (; astOffset < astText.Length; astOffset++, lineOffset++)
            {
                if (astText[astOffset] == '\n')
                {
                    // reset numbers since we are operating on a different line and increment the line number.
                    startColumnNumber = 0;
                    startLineNumber++;
                    lineOffset = 0;
                }
                else if (astText[astOffset] == '\r')
                {
                    // Do nothing with carriage returns... we only look for line feeds since those
                    // are used on every platform.
                }
                else if (!char.IsWhiteSpace(astText[astOffset]))
                {
                    // This is the start of the function name so we've found our start column and line number.
                    break;
                }
            }

            return (startColumnNumber + lineOffset, startLineNumber);
        }

**Comment by iSazonov** [comment]
If we enhanced AST with the name extent what about backward compatibility? No problems?
