### ISSUE TITLE
Progress bar remains despite Completed record in progress stream (now with portable repro)

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#12541]
I've noticed occasions where PowerShell continues to show a progress bar despite that the activity has completed.  That can be merely confusing on short runs, but it becomes inscrutable for long-running scripts because the progress bars eventually accumulate until they fill most of the console and then jump around (see also #7507).  

In some cases a progress bar remains because the offending command simply does not write a "Completed" record.  That can be determined by examining PowerShell.Streams.Progress.  In this case, however, it looks to me that correctly-formatted "Completed" records are indeed written to the progress stream.

1. In what conditions should I expect PowerShell to stop displaying a progress bar?  Is it simply a "Completed" record with a matching ActivityId?  Or are there other conditions that also have to be met?
2.  Why do the progress bars accumulate when invoking `Backup-SqlDatabase` but do not accumulate when paying back the same records via `Write-Progress`?

# Steps to reproduce

_Note: I had originally posted a repro that wasn't portable.  See the revision history of this post for that repro._

## Prerequisites

* [SqlServer module](https://docs.microsoft.com/en-us/powershell/module/sqlserver/?view=sqlserver-ps)
* A test database instance with an empty database, and permissions to perform a backup.

## Script
```PowerShell
Import-Module SqlServer -PassThru | select Name,Version | Out-String | Write-Host
$sb = {
    1..10 | % {
        Backup-SqlDatabase TEST_DB_0178b0 -ServerInstance .\TEST_INST_ba7dec
        Write-Progress 'Backup complete' -Id 1 -Completed
    }
}
. $sb
$ps = [powershell]::Create().AddScript($sb)
$ps.Invoke() | Out-Null
$ps.Streams.Progress |
    ? {$_.Activity -like '*Back*' } |
    Select-Object ActivityId,RecordType,Activity
$ps.Streams.Progress | Export-Clixml .\progress.xml
```

## Artifacts

* [progress.xml](https://gist.github.com/alx9r/bf91fa0eedde6c0adec80a2ac98ac89b#file-progress-xml) - captured by above script
* [playback.ps1](https://gist.github.com/alx9r/bf91fa0eedde6c0adec80a2ac98ac89b#file-playback-ps1) - used to "playback" the progress captured and demonstrate the "expected" behavior

Output of progress stream (`...` indicates repetition of the same record):

```

ActivityId RecordType Activity
---------- ---------- --------
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
         1 Processing Backing up (Database: 'TEST_DB_0178b0' ; Server: 'DT30\TEST_INST_ba7dec' ; Action = 'Database')
...
         1  Completed Backup complete
```

# Expected behavior

I expect the behavior of the progress bar to be like this in that they do not accumulate:

![expected](https://user-images.githubusercontent.com/11237922/80817035-7fd81400-8b85-11ea-9d13-8afe728b3f6c.gif)

# Actual behavior

The progress bars accumulate:

![actual](https://user-images.githubusercontent.com/11237922/80817430-3fc56100-8b86-11ea-8d10-be5c7c879162.gif)

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by alx9r** [comment]
@iSazonov Do you think this is already explained by any of the issues mentioned in #3366?  

I've done a first read through them but I see now that the progress bar implementation is more complicated than I expected.

**Comment by SeeminglyScience** [comment]
> 1. In what conditions should I expect PowerShell to stop displaying a progress bar?  Is it simply a "Completed" record with a matching ActivityId?  Or are there other conditions that also have to be met?

A completed record is the main way, but it will also be cleared after the current interactive pipeline is finished (when `ConsoleHost` is the current host).

**Comment by iSazonov** [comment]
> Do you think this is already explained by any of the issues mentioned in #3366?

I think it looks like point 4.

**Comment by alx9r** [comment]
@iSazonov 
>I think it looks like point 4.

>4. #5370 - With Write-Progress -Completed in nested scenarios we need a delay Start-Sleep 1 to get screen update in follow Write-Progress.

I added some sleeps as follows:

```PowerShell
1..10 | % {
    Backup-SqlDatabase TEST_DB_0178b0 -ServerInstance .\TEST_INST_ba7dec
    sleep 1
    Write-Progress 'Backup complete' -Id 1 -Completed
    sleep 1
}
```

The progress bars still accumulate, however.  But I'm not sure if that's what you meant.  

Would you be able to explain what is happening that a sleep would make the difference for whether a "Completed" record takes effect?

**Comment by iSazonov** [comment]
1 - it is ms. You could use Start-Sleep 500.

**Comment by SeeminglyScience** [comment]
@iSazonov the positional parameter is `-Seconds`.

**Comment by iSazonov** [comment]
Internally Engine keeps the data by <SourceId, ActivityId>. SourceId is not in ProgressRecord. So we need to know SourceId used by Backup-SqlDatabase and use it in Write-Progress to cleanup Backup-SqlDatabase output.

**Comment by alx9r** [comment]
Hmm...I wonder why SourceId is not included ProgressRecord.  That would mean that any application hosting a PowerShell would not have sufficient access to correctly handle "Completed" by way of PowerShell.Streams.Progress alone.  I wonder if there is some other way that PowerShell is hosted that reveals the SourceId of ProgressRecords to the host.

**Comment by SeeminglyScience** [comment]
> That would mean that any application hosting a PowerShell would not have sufficient access to correctly handle "Completed" by way of PowerShell.Streams.Progress alone.

They typically also provide a `PSHost`, and more specifically implement `abstract PSHostUserInterface.WriteProgress(long sourceId, ProgressRecord record);`.  If they don't, the progress messages aren't going to go anywhere anyway.

**Comment by alx9r** [comment]
> They typically also provide a PSHost, and more specifically implement abstract PSHostUserInterface.WriteProgress(long sourceId, ProgressRecord record);. If they don't, the progress messages aren't going to go anywhere anyway.

I see.  I had been subscribing to PowerShell.Streams and displaying those records to the host.  But that was only for non-interactive sessions.

I don’t have experience using PSHost, etc.  Do you see a way to intercept PSHostUserInterface.WriteProgress() to discover the SourceId written by Backup-SqlDatabase, etc without the work required to implement a full-blown console?

I guess I could build a modified PowerShell console from this repo but I’ve never built PowerShell myself so I’m not sure how much of an undertaking that would be.

**Comment by SeeminglyScience** [comment]
How are you creating the runspace? You should be able to just pass `$Host` to the `runspacefactory.CreateRunspace` overload that takes it.  If not, then no there's no way to intercept it.  Closest you could do is build a proxy `PSHost` that stores the original host and just forwards all calls to that internally.

**Comment by iSazonov** [comment]
Design intention of the cmdlet is to show 100% message to user. If `-Completed` would be used users never saw the message.
It is again an issue in design/implementation of progress bar in PowerShell. I will reference this in meta issue.

**Comment by alx9r** [comment]
@SeeminglyScience 

Thank you for the guidance.  I succeed by making a proxy with `PSHostUserInterface.WriteProgress()` overridden so that it prefixex `Activity` with `sourceId`.  I put a working example in [this gist](https://gist.github.com/alx9r/688730f7c8c01e610e361cfa44eb877b).

Backup-SqlDatabase seems to increment its source ID:

![image](https://user-images.githubusercontent.com/11237922/81018550-95fe0280-8e19-11ea-9fc5-8b7bfc9e8acf.png)

It's not immediately obvious to me how to reliably compensate for that.

**Comment by KalUlin** [comment]
Hello
Has anyone found a fix for this bug?
Two years later, it's still happening...
