### ISSUE TITLE
[Feature Request] Better display of UNC paths

### ISSUE THREAD

**Issue by Stanzilla** [PowerShell/PowerShell#12544]
# Summary of the new feature/enhancement

Currently, when the CWD is a UNC path, it is displayed like so

`PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\stan\projects\personal\yarntest>`

Would it be possible to display it as a normal path instead? like so

`PS \\wsl$\Ubuntu\home\stan\projects\personal\yarntest>`

Or is that something my profile broke?

# Proposed technical implementation details (optional)

**Comment by vexx32** [comment]
Not sure how complex this would be to make behave as you expect, but you can always use the `New-PSDrive` cmdlet to add a simpler address to the path, e.g.:

```ps1
New-PSDrive -Provider FileSystem -Root \\wsl$\Ubuntu\ -Name WSL

Set-Location WSL:
```

**Comment by Stanzilla** [comment]
Well my request was mostly to improve the default since it does look a bit "wrong".

**Comment by SeeminglyScience** [comment]
Something you can add to your profile:

```
function prompt {
    if ($null -eq $PWD.Drive -and $PWD.Provider.Name -eq 'FileSystem') {
        return "PS $($PWD.ProviderPath)> "
    }

    return "PS $($PWD.Path)> "
}
```

Maybe worth adding as a default.

**Comment by Stanzilla** [comment]
No worries, @thlac is working on a fix already.

**Comment by Stanzilla** [comment]
Bad bot

**Comment by Stanzilla** [comment]
bad bot

**Comment by Stanzilla** [comment]
bad bot
