### ISSUE TITLE
Powershell and < character with mysql and mysqldump

### ISSUE THREAD

**Issue by lebartha** [PowerShell/PowerShell#12548]
Hi,

We had this issue since PowerShell v1. The < character is always reserved for future use, but that future never arrives.

< and > are using by many command line utilities, such as mysql and mysqldump for example. But can never use it with powershell.

https://bugs.mysql.com/bug.php?id=73481

**Comment by ThomasNieto** [comment]
Have you try using the stop-parsing symbol `--%`?

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7

```
mysql.exe --% < backup.sql
```

**Comment by lebartha** [comment]
Gives me the error:  Couldn't find table: ">"

**Comment by jcotton42** [comment]
@ThomasNieto the issue here isn't that PowerShell is swallowing `<`, it's that PowerShell doesn't support input redirection (setting the stdin of a native command to be from a file), so the stop parsing symbol won't help.

**Comment by vexx32** [comment]
Given the token has been labeled as reserved for several versions, I'd be inclined to assume that if someone wanted to implement the feature it would probably be largely welcomed. 

The broader question would simply be what is the expected behaviour if you use `<` on a cmdlet, pipeline, or expression. Sensible behaviour for a first implementation might just be to throw an error in those cases, and only allow it to be used when invoking native commands.

**Comment by jcotton42** [comment]
> The broader question would simply be what is the expected behaviour if you use `<` on a cmdlet, pipeline, or expression. Sensible behaviour for a first implementation might just be to throw an error in those cases, and only allow it to be used when invoking native commands.

IMO the intuitive behavior there would be that `cmdlet < file` would be semantically equivalent to `Get-Content file | cmdlet`.

**Comment by lebartha** [comment]
So, what I am hearing (or reading), is that MySQL tools are the issue here and not powershell. I mean there is a workaround to wrap the commands with cmd /c "...", but its sad that it has to be done that way :(

**Comment by jcotton42** [comment]
@lebartha no the issue really is ultimately PowerShell, in that it doesn't support input redirection.

**Comment by Phil-Factor** [comment]
The MySQL commandline tools work perfectly fine with PowerShell. PowerShell does support input redirection (setting the stdin of a native command to be from a file). The syntax is different. The flow always goes from left to right. It is a much better idea than input redirection Here is code for reading SQL from a file
$Result = ([IO.File]::ReadAllText("$MyInputFile") | mysql "--host=$myhost" "--password=$myPassword"  "--user=$MyUser")
or for use with a query as a string ...
 'SHOW VARIABLES LIKE "version"'|mysql "--host=$myhost" "--password=$myPassword"  "--user=$MyUser"
