### ISSUE TITLE
Feature Request : Set-ConsoleTitle

### ISSUE THREAD

**Issue by ramonsmits** [PowerShell/PowerShell#12543]
# Summary of the new feature/enhancement

I'm not entirely sure if this is the right location for a function suggestion to be part of powershell but it surprised me that there is no `Set-ConsoleTitle` function. In a DOS console you can set the the title via `` title 'Your cool tab' &amp; cmd `` and was hoping for a similar function in Powershell but then to find that it does not exist but can be set via `$host.ui.rawui.set_WindowTitle(string)`

There are plenty of website suggesting to make your own Function and Alias but I think it should be part Powershell itself.

It is *VERY* useful to use when you have loads of console instances that you to identify easily. 

# Proposed technical implementation details (optional)

```ps1
Function Set-ConsoleTitle {
  Param ([string]$value)
  $host.ui.rawui.set_WindowTitle($value)
}
Set-Alias title Set-ConsoleTitle # Would make it behave similarly as in a DOS console
```

**Comment by iSazonov** [comment]
It is well-known workaround and everyone can put it in profile if needed.
I would like to see a lot of votes in support of this proposal before adding.

**Comment by jdhitsolutions** [comment]
I don't see how Microsoft adds any value or here nor is the solution something only Microsoft could implement. This is easy enough to implement on your own in whatever way you want. Maybe you want support for ShouldProcess, or a limit on the string length. Maybe you want to save the current title and have a parameter that lets you revert? Microsoft already gives you a way to achieve this goal.

```powershell
$host.ui.RawUI.WindowTitle = "PS 5.1"
```

Anything else around that or beyond that, can be up to the user and/or community.
