### ISSUE TITLE
new feature: start-transcript preserve object 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12552]
Hi

step to repoduce:

```
PS> start-transcript -asxml
# code 1
# code 2
PS> stop-transcript

```
with -asxml switch the transcription is sending to an xml file...the data is object...for example if the user enter in the host: **get-process** this  object is  deserialized and sending in xml file next:
`
PS> import-clixml transcriptfile.xml
`
and return pure object...with that  formating,  filtering, ....etc made easy.

**Comment by iSazonov** [comment]
The main purpose of this cmdlet is user input logging for security - no need to write to the log full information about all object.
