### ISSUE TITLE
ValidateScript attribute throws exception when argument is explicitly set to $null

### ISSUE THREAD

**Issue by mmorak** [PowerShell/PowerShell#12557]
When using a parameter with a ValidateScript attribute, this throws an exception if the parameter is explicitly set to $null, which is unexpected. I didn't find it documented anywhere, so I guess it's a bug. Minimal working example below.

# Steps to reproduce

```powershell
function testfunc {
    param(
        [ValidateScript({ $true })]
        [psobject]
        $Arg
    ) 

    'Arg is null: {0}' -f ($null -eq $Arg)
}
```

# Expected behavior

```powershell
testfunc -Arg $null
```
Output:
```none
Arg is null: True
```

# Actual behavior

```powershell
testfunc -Arg $null
```
Output:
```none
Cannot validate argument on parameter 'Arg'. The argument is null, empty, or 
an element of the argument collection contains a null value. Supply a collection 
that does not contain any null values and then try the command again.

+ CategoryInfo          : InvalidData: (:) [testfunc], ParameterBindingValidationException
```
------

But without parameters:
```powershell
testfunc
```
Output:
```none
Arg is null: True
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by yuqieang19841028** [comment]
App

**Comment by vexx32** [comment]
This is _probably_ due to inherited behaviour for the ValidateScript attribute, but either we should document this or fix it. Not sure which is more appropriate here.

**Comment by iSazonov** [comment]
Since ValidateScript is inherited from ValidateEnumeratedArgumentsAttribute it is by-design.

**Comment by mmorak** [comment]
Ok, thanks for letting me know. I think this by-design behaviour should still be documented somewhere, since it is somewhat unexpected. It implies that, as soon as you use a Validate* attribute (Script, Range, Set, Pattern, etc.), this implies ValidateNotNull, and AllowNull becomes impossible, and the use of these two attributes therefore has no effect.

**Comment by mmorak** [comment]
And, thinking of my usecase now, it means that when null values are allowed, parameter validation has to be done using an if-statement (or similar), and throwing an exception, inside the main function code. Is that correct?

**Comment by iSazonov** [comment]
The cmdlet can have a history for the design. Perhaps somebody could add an information about this.

> Is that correct?

You can implement custom attribute for your needs.
