### ISSUE TITLE
PowerShell fails to launch on Windows ARM64

### ISSUE THREAD

**Issue by richlander** [PowerShell/PowerShell#12550]
I did the following:

* Installed .NET 5.0 Preview 4 on a Windows AM64 device
* Installed the PowerShell global tool
* Updated the pwsh.runtimeconfig.json file to reference the MS.NetCore.App framework instead of the Windows Desktop one.
* "set DOTNET_ROLL_FORWARD=LatestMajor"

I then see the following:

```console
C:\git\testapps\versioninfo>pwsh
PowerShell 7.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

The shell cannot be started. A failure occurred during initialization:
The type initializer for 'System.Management.Automation.LanguagePrimitives' threw an exception.
```

**Comment by iSazonov** [comment]
> Updated the pwsh.runtimeconfig.json file to reference the MS.NetCore.App framework instead of the Windows Desktop one.

Why do you change the default? PowerShell 7.0 depends on Windows Desktop.

**Comment by DHowett-MSFT** [comment]
I’m concerned that this bug report is “I modified powershell’s runtime environment and that made it break.” Isn’t that sorta you-break-it-you-bought-it?

Does the same thing happen if you try to retarget the GA version to .NET 5 on AMD64? Does it work if you _don’t_ retarget it, and use it with .NET Core 3 as it was produced for GA?
