### ISSUE TITLE
Not Implemented Exception for Enter-PSSession

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#12553]
I am writing a c# application to connect to remote Windows Server 2012 R2 server with PS Remoting. I am using Powershell SDK Invoke method to connect.
# Steps to reproduce
I create the following script block with code:
```
$User="WinServer2012r2\Administrator"
$Pass=ConvertTo-SecureString -String "xxxxx" -AsPlainText -Force
$Cred=New-Object PSCredential $User,$Pass
Enter-PSSession -computername WinServer2012R2 -Authentication Negotiate -Credential $Cred
```

# Expected behavior
When I use Windows Powershell on my machine with the exact commands I receive the remote Powershell.
```
[winserver2012R2]: PS C:\Users\Administrator\Documents> whoami
winserver2012r2\administrator
```
# Actual behavior
I receive an Exception with HResult=-2147467263 and Message="The method or operation is not implemented." 

# Environment data
Client is running Windows 10 1909 Build 18363.778
Windows Powershell PSVersion Output:
PSVersion=5.1.18362.752
PSEdition=Desktop
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3

Since I am running inside an application, I am copying from debug window.
PSVersion=7.0.0
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3

**Comment by iSazonov** [comment]
Can you share full stack trace for the exception?

**Comment by erenturkm** [comment]
StackTrace for the execption is:
   at System.Management.Automation.Internal.Host.InternalHost.GetIHostSupportsInteractiveSession()
   at System.Management.Automation.Internal.Host.InternalHost.PushRunspace(Runspace runspace)
   at Microsoft.PowerShell.Commands.EnterPSSessionCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by iSazonov** [comment]
I guess you do not implement interactive host.

**Comment by erenturkm** [comment]
I am just calling Enter-PSSession inside script block. Could you elaborate on what needs to be done,

**Comment by iSazonov** [comment]
The cmdlet checks that your host implement IHostSupportsInteractiveSession.

**Comment by erenturkm** [comment]
So, the correct way to run Powershell on a remote connection is using runspaces through SDK and NOT using Enter-PSSession. However maybe we can improve the developer experience with a more meaningful error message. Thanks.

**Comment by iSazonov** [comment]
It is for developers only - they can see a stack trace and look PowerShell source code.
