### ISSUE TITLE
Join-Path fails on linux with 'drive doesn't exist'

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PowerShell#12564]
This can not be legit behavior:

![image](https://user-images.githubusercontent.com/85767/80920977-917f0e80-8d73-11ea-89d9-e49d8486cd6c.png)

This is hybrid project and I don't actually use this path on linux, but the mere presence of this line fails.

**Comment by fMichaleczek** [comment]
Why do you think it's an error relative to the source code of PowerShell ?

**Comment by majkinetor** [comment]
Because try it
![image](https://user-images.githubusercontent.com/85767/81006678-28b99400-8e50-11ea-9753-fb6442eaffc1.png)

**Comment by fMichaleczek** [comment]
You are on a Linux host, what do you expect ?

The previous error come from a script named "base.ps1".

You should ask the owner of the script.

I don't understand your issue.

**Comment by majkinetor** [comment]
Join-Path, unlike Resolve-Path, can accept any garbage, and join it with path delimiter. Its basically a x-platform method of doing "$path1/$path2/$path3..." 

For example on Windows:
```
PS> join-path :< 1 2
:<\1\2
```

On linux

```
PS /root> join-path :< 1 2
:</1/2
```

But when you put `x:`  as first argument it doesn't work. 

The problem is pretty obvious - its not cross platform, its not correct either.

**Comment by fMichaleczek** [comment]
@majkinetor OK, please submit all informations of the template, I can't reproduce.

```
PS /home/lexpec> Join-Path 'C:' l
C:/l
PS /home/lexpec> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by majkinetor** [comment]
CentOS Linux release 7.7.1908 (Core)

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fMichaleczek** [comment]
@majkinetor It's a duplicate of [4386](https://github.com/PowerShell/PowerShell/issues/4386)

**Comment by majkinetor** [comment]
OK, closing this.
Need to impove on my search. Sorry.

**Comment by majkinetor** [comment]
After reading original issue, I must say, I didn't know this doesn't work on Windows too... Thx for sharing.

**Comment by peetrike** [comment]
> Join-Path, unlike Resolve-Path, can accept any garbage, and join it with path delimiter - It doesn't check physical existence. Its basically a x-platform method of doing string concatenation like "$path1/$path2/$path3..." without haveing to take care of path delimiter yourself.
> 
> For example on Windows:
> 
> ```
> PS> join-path :< 1 2
> :<\1\2
> ```
> 
> On linux
> 
> ```
> PS /root> join-path :< 1 2
> :</1/2
> ```
> 
> But when you put `x:` as first argument it doesn't work on linux.
> 
> The problem is pretty obvious - its not cross platform, its not correct either. Clearly its a bug.

Actually, the same happens on Windows, if the PSDrive doesn't exist.  You can try with any currently nonexisting PSDrive name.  Like for example 
```powershell
Join-Path -Path u: -ChildPath folder
# make sure that ActiveDirectory module is not loaded
remove-module ActiveDirectory -ErrorAction SilentlyContinue
Join-Path -Path ad: -ChildPath folder
```

**Comment by majkinetor** [comment]
Yeah, I didn't know that and relized it after reading all the provided comments in related ticket. Seems like a bad design chocice from the start.
