### ISSUE TITLE
[Feature Request] Press arrow up going through previous commands: show previous *different* command instead of repeating same command

### ISSUE THREAD

**Issue by SirHodlington** [PowerShell/PowerShell#12566]
This is a small but powerful improvement for PowerShell. I regularly use PowerShell to run commands for my programming work like starting builds, deploying cloud functions, running scripts etc.. 

The press arrow up feature to get the previous command is very helpful, but cumbersome to use when repeating the same command often.

When developing, I often have to run the same commands a lot of times in a row. 
Example:
1.) start server command
2.) change code -> run script command
3.) change code -> run script command 
.....
50.)  change code -> run script command
*ends coding session*

Now here is the issue. The next time I start the terminal I would like to select the start server command again by pressing arrow up button. The problem is though, that I have to press is like 50 times before it shows that command. I'm assuming that there is some kind of list that is iterated through 1 row each time the arrow up button is pressed. 

It would be extremely helpful, if the "press arrow up"-function would not repeat the same command, but always show the next different command. (increase i until next command is different then currently show command). (same goes for arrow down)
In my example that would mean: When I start the terminal and press arrow up once it shows the  "run script command" and when pressing it the second time it shows the " start server command"

Maybe you can make that change? I would SO MUCH appreciate it!

**Comment by DHowett-MSFT** [comment]
You can do this with PSReadline (which is the line editor and history management module that ships with powershell, and which you’re already using) today with...

```
Set-PSReadLineOption -HistoryNoDuplicates
```

If you put that into your profile, you won’t see duplicated in your history file or your up-arrow history recall.

**Comment by DHowett-MSFT** [comment]
(As an aside, you can actually search your history interactively with <kbd>Ctrl+R</kbd>! If you press ^R and then part of the command that starts the server, it’ll automatically jump to that command so you can run it again.)

**Comment by SirHodlington** [comment]
You Sir, deserve more than the one upvote I can give.

**Comment by SirHodlington** [comment]
imho this should be the default setting

**Comment by rkeithhill** [comment]
An even more straightforward way to search is to type in the first part of the command e.g. `start` and then press the UpArrow key.   IIRC you need this bit of configuration to make that work:
```
Set-PSReadlineKeyHandler -Chord UpArrow   -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Chord DownArrow -Function HistorySearchForward
```
Finally, give the new PSRL 2.1.0 Beta a try.  It provides completion prediction functionality (I typed in only `dot` below - the rest is the prediction) e.g.:
![image](https://user-images.githubusercontent.com/5177512/80992200-67226500-8df6-11ea-9f8e-5432f23d5d44.png)

See this PSReadLine issue for more details: https://github.com/PowerShell/PSReadLine/issues/687

**Comment by SirHodlington** [comment]
I wish I could preset these somehow. Having to enter them at the beginning each time is really slowing me down :/

**Comment by DHowett-MSFT** [comment]
So that's what I was alluding to when I mentioned [your profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7). You can have a script that runs automatically every time you open PowerShell to set your customizations up exactly as you want them.

**Comment by SirHodlington** [comment]
Ok I will try that. Thanks!
