### ISSUE TITLE
It will not try to find a compatible version

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12560]
# Steps to reproduce
When I try to use [About Requires](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7) in the script, it never tries to find a compatible version and execute it.
```powershell
#Requires -PSEdition Desktop
```

# Expected behavior

```none
Error
```

# Actual behavior

```none
Ok
```

# Environment data

```none
Windows
```

**Comment by vexx32** [comment]
Gonna need more info, like what the actual error was, and what you actually expected to happen. All I can do here is guess.

Best guess I have is that you're expecting this to somehow invoke Windows PowerShell. That's not how #Requires works.

All #Requires statements do is validate whether the constraint can be met in the currently-running session. They do not do anything other than that. If the constraint isn't met, it is supposed to simply fail.
