### ISSUE TITLE
Feature Request: Update-Module without parameters should identify module/repository

### ISSUE THREAD

**Issue by LarsFosdal** [PowerShell/PowerShell#12567]
Moved to
https://github.com/PowerShell/PowerShellGet/issues/136

**Comment by iSazonov** [comment]
@LarsFosdal Please move your request to PowerShellGet repository.

**Comment by LarsFosdal** [comment]
Umm... I apologize for the stupid question: How do I do that?

**Comment by iSazonov** [comment]
You could close the issue and create new there.

**Comment by LarsFosdal** [comment]
Ah, like that.  Well, there appears to be two PowerShellGet repositories.
Which one is the right one?

**Comment by iSazonov** [comment]
I think https://github.com/PowerShell/PowerShellGet. That is new 3.0.

**Comment by LarsFosdal** [comment]
Moved. Feel free to remove this thread if desired.
