### ISSUE TITLE
add  new cmdlet  to  process new eventview

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12575]
PS7+ not support *-eventlog  cmdlet it only support get-winevent and new-winevent.
 
add  new cmdlet  to  process new eventview 
```

Clear-WinEvent
Limit-WinEven
Remove-WinEvent
Show-WinEvent
```

**Comment by vexx32** [comment]
@p0W3RH311 please follow the issue template and provide sufficient information. At best we can guess what you intend, but this would not be a productive discussion if we have to infer all the information you're trying to convey. 

It's very difficult to give credence or thought to an idea that is not explained. This is part of the reason we have issue templates in the repository. Please follow them.

**Comment by p0W3RH311** [comment]
@vexx32 

you're right i will try to explain ... i use... google translate :p 



in windows powershell there is the family * -eventlog cmdlet....powershell 7 missing commands like:

```
Clear-WinEvent
Limit-WinEven
Remove-WinEvent
Show-WinEvent
```

**Comment by iSazonov** [comment]
*-EventLog cmdlets were removed because they were based on old non-public API.

It makes no sense to offer new cmdlets without describing usage scenarios that could be evaluated.

**Comment by jdhitsolutions** [comment]
I agree that there are some PowerShell 7 limits. If I wanted to adjust the size of an event log in PS 7, what command do I have? Or if want to clear it? The Cmdlet Working Group has already discussed a separate issue for creating a new eventlog, deciding not to pursue it, But I can see value in having commands like `Limit-WinEvent` and 'Clear-WinEvent`. Adding this to the Working Group review list.
