### ISSUE TITLE
Content Copied from a Microsoft Teams Code Snippet is Pasted in Reverse in Windows 10

### ISSUE THREAD

**Issue by bmkaiser** [PowerShell/PowerShell#12579]
# Steps to reproduce

1. Create and send a [multi-line code snippet](https://support.microsoft.com/en-us/office/send-code-snippets-in-a-message-in-teams-5406fe2b-2771-4b9a-bd73-656914f6ab3c) in Microsoft Teams
2. Copy the code snippet from Teams (can be from either Teams desktop app or [https://teams.microsoft.com](https://teams.microsoft.com))
3. Paste the code snippet into either Pwsh.exe or PowerShell.exe

```powershell
$date = Get-Date
$date
```

# Expected behavior

* Code is pasted in the same order it was copied

```powershell
$date = Get-Date
$date
```

# Actual behavior

* Code lines are reversed

```powershell
$date
$date = Get-Date
```

# Environment data

I could not replicate this behavior on macOS and was not able to test on Linux. I also tested pasting into many other applications and did not observe the text order being reversed, so I believe this is a PowerShell issue and not a Teams issue (Notepad, Notepad++, Word, Command Prompt, Teams).

* Windows 10 1909 10.0.18363.778
* Microsoft Teams 1.3.00.8663

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rjmholt** [comment]
I just tried this out on my machine:

![paste](https://user-images.githubusercontent.com/7009879/81088708-30a92080-8eb0-11ea-8d63-430ee9888312.PNG)

![paste2](https://user-images.githubusercontent.com/7009879/81088712-343ca780-8eb0-11ea-9c29-c3dc986f25a0.PNG)

I copied the contents of the snippet with <kbd>Ctrl</kbd>+<kbd>V</kbd> and pasted into the ordinary pwsh.exe conhost with <kbd>Ctrl</kbd>+<kbd>C</kbd>. Right-click to paste also got the order right, but omitted the newline (which I believe is a known limitation in that form of paste).

Some followup questions:

- How are you copying?
- How are you pasting?
- Are you running normal pwsh.exe in the conhost (as in my screenshot), or are you running it in another terminal emulator (like Windows terminal or Hyper)?
- Does this also occur with powershell.exe?
- Does this also occur with the current PowerShell preview (7.1.0-preview.2)?
- Does this occur for you on any other machines?
- Does this occur with any other Electron applications, like VSCode or Slack, or possibly Chrome?

**Comment by vexx32** [comment]
I've noticed this seems to be getting a little better as the months pass, so I'm not sure if this is something that the app is doing incorrectly, or if PS needs to handle it better.

I notice it most with apps like [floobits](https://j.mp/floobits) that we use commonly in the PS slack/discord, pasting snippets from those into PS is very odd unless you go via some other text editor.

**Comment by bmkaiser** [comment]
@rjmholt - It looks like you just formatted your text as monospaced as opposed to using a code snippet. Should look something like this:

![image](https://user-images.githubusercontent.com/5446414/81090252-73c4bd00-8ecb-11ea-952b-c89a7a7039e4.png)
![image](https://user-images.githubusercontent.com/5446414/81090370-9eaf1100-8ecb-11ea-9b09-b27f15ea3be7.png)

To answer your questions though:
* I am copying with `Ctrl`+`C`
* I am pasting with right-click (I just discovered that the issue doesn't occur with `Ctrl`+`V`)
* Yes, pwsh.exe is being run in the console host and is not using an emulator
* Yes, issue exists in 7.1.0-preview.2 (see screenshot below)
* I have observed this on other computers as well that have the same version of Windows as me
* I also tested with VSCode and didn't observe the behavior

![image](https://user-images.githubusercontent.com/5446414/81091296-0580fa00-8ecd-11ea-8b55-052ed18aa610.png)

**Comment by rjmholt** [comment]
I can confirm that creating a full code snippet doesn't change the behaviour I see either.

One last question: if you disable PSReadLine with `rmo PSReadLine`, does this issue still occur?

> I have observed this on other computers as well that have the same version of Windows as me

Given that PowerShell's version is independent of Windows, that is more suggestive of this bug living beyond PowerShell's own code.

/cc @SteveL-MSFT and @daxian-dbw in case they have any insights into any manipulation we might do with the clipboard

**Comment by adityapatwardhan** [comment]
It is probably https://github.com/PowerShell/PSReadLine/issues/579
 As @rjmholt said, can you try without PSReadLine?

**Comment by bmkaiser** [comment]
I would agree that this is a PSReadLine issue after looking at those two issues. When I paste after disabling PSReadLine, it's in the correct order, but line returns are not understood:

![image](https://user-images.githubusercontent.com/5446414/81128903-93320900-8f10-11ea-8b21-bb5fafff13ea.png)

I also tried the workaround recommended in PowerShell/PSReadLine#496 and it appeared to offer the same functionality:

![image](https://user-images.githubusercontent.com/5446414/81128799-31719f00-8f10-11ea-913e-b2b87ed2a8c2.png)

I think the best work around until this is fixed is just to use <kbd>Ctrl</kbd>+<kbd>V</kbd> which doesn't have these issues. I also think this can be closed now that I see it has an existing open issue within PSReadLine.
