### ISSUE TITLE
Copy operation should show progress 

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/PowerShell#12586]
# Summary of the new feature/enhancement

On long copy (especially over the network) it is unclear if copying is done at all. Progress bar that shows that operation is really working and progressing (and where it is currently stuck and for how long) would definitely help.

# Proposed technical implementation details (optional)

There should be switch for Copy-Item that would write progress via Write-Progress. Progress should include:
- time spent already
- bytes copied already
- currently copied file
- (optional, this can be tricky to calculate) estimate percent done of the copy operation. This is optional. If it is network copy it can take lots of time to enumerate files and calculate their total size. If that takes more than a second, I'd rather this estimate would be dropped altogether.

**Comment by iSazonov** [comment]
Dup #12110

**Comment by FallenGameR** [comment]
The other issue was closed before the discussion took place. Do I need to recreate the issue anew now that you closed both?

**Comment by iSazonov** [comment]
The issue was closed as a duplication. 
You can continue discussing in #12110 (closing is not locking and anyone can add comments)
