### ISSUE TITLE
Module manifest could not be processed

### ISSUE THREAD

**Issue by ntatschner** [PowerShell/PowerShell#12599]
# Steps to reproduce
[Module files.zip](https://github.com/PowerShell/PowerShell/files/4593515/Module.files.zip)

```powershell
Running Test-ModuleManifest -Path "ATTACHED psd1 FILE"

PS C:\Users\nrtat> Test-ModuleManifest -Path .\Documents\WindowsPowerShell\Modules\Tatux.Utils\Tatux.Utils.psd1

This issue presented itself while trying to use Publish-Module
I then tested the command in both versions of PS

```

# Expected behavior

```none
Manifest file is validated.

The command above works in Powershell Verstion 5.1

```

# Actual behavior

```powershell
Test-ModuleManifest: The module manifest 'Tatux.Utils' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: C:\Users\nrtat\Documents\WindowsPowerShell\Modules\Tatux.Utils\Tatux.Utils.psd1
```

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by iSazonov** [comment]
In "Tatux.Utils" `Utils` is considered as a file extension.
The regression comes from #8687 (#8388) /cc @mklement0 
See HasValidRootModule() method https://github.com/PowerShell/PowerShell/blob/ef187d94f3b503d68a3cab818c255f1adb69c8fa/src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs#L323-L335
