### ISSUE TITLE
Performance Issue with foreach - paralllel

### ISSUE THREAD

**Issue by Schwanowski** [PowerShell/PowerShell#12597]
Hi guys

the attached test runs on my machine (Powershell V7) astonishingly 30 seconds.

Can this be true? It has only 10k records and I dont get the performance issue?

Can you please clarify the issue?

Thanks,

Alex

[tmp.txt](https://github.com/PowerShell/PowerShell/files/4591664/tmp.txt)

# Steps to reproduce

```
   
    $myTest = Get-Content 'tmp.txt' | ConvertFrom-Json | Select-Object 'InputObject'
Measure-Command {
    $myTest | ForEach-Object -parallel {}
}

```

# Expected behavior

```
This shouldnt take 30 seconds imho

```

# Environment data

```
$PSVersionTable.PSVersion


Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      0




```

**Comment by iSazonov** [comment]
@Schwanowski In 7.0 new runspaces is created for every input object. It is really slow.
You can try latest 7.1 preview nightly build where some optimizations was added.

**Comment by vexx32** [comment]
Additionally, if the overall processing required for each runspace is small, you will have better results in both versions if you batch the inputs for processing.

**Comment by Schwanowski** [comment]
Thanks, we can leave this for the moment. I will try this again when 7.1 is out
