### ISSUE TITLE
Improper cursor/backspace handling of surrogate pairs

### ISSUE THREAD

**Issue by Serentty** [PowerShell/PowerShell#12593]
# Steps to reproduce

Try entering a non-BMP character such as 𐀀 into PowerShell. Then, press backspace.

# Expected behavior

It should delete the entire character.

# Actual behavior

It deletes the low UTF-16 surrogate, leaving the high surrogate.

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 5.6.8-1-MANJARO #1 SMP PREEMPT Wed Apr 29 19:05:17 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Additional notes

This affects not just backspace, but cursor movement as well. When the character is pasted in, I see the character itself, but also additional replacement characters surrounding it. These don't seem to be noticed by PowerShell, as the command history just shows the character pasted in when I press the up arrow, although just as usual, it takes up two columns in the terminal instead of one. I have run into this issue both on Windows and on Linux, and the results were similar if not the same on both. My test environment here was Linux, with both my terminal and PowerShell using UTF-8 output (which I understand PowerShell transcodes from UTF-16).

![image](https://user-images.githubusercontent.com/614548/81242825-22582300-8fdc-11ea-9b9f-7396b81c8e00.png)

**Comment by iSazonov** [comment]
@daxian-dbw I think it is already tracked in PSReadline repo?
