### ISSUE TITLE
snap package fails on ubuntu 20.04

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#12594]
Installing powershell on ubuntu 20.04:
````
sudo snap install powershell --classic
powershell 7.0.0 from Microsoft PowerShell✓ installed
````
````
pwsh
Failed to load ���, error: /snap/powershell/104/opt/powershell/../../lib/x86_64-linux-gnu/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
Failed to bind to CoreCLR at '/snap/powershell/104/opt/powershell/'
Failed to create CoreCLR, HRESULT: 0x80008088
````

**Comment by iSazonov** [comment]
Currently Ubuntu 20.04 is not in .Net 3.1 supported OS list. https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md
You should ask .Net team to add the support before PowerShell could works on the OS.

**Comment by nikonthethird** [comment]
@iSazonov the `dotnet` packages are available for Ubuntu 20.04 as of today :tada: 

Does that mean Powershell can be added to the APT repos now as well?

**Comment by iSazonov** [comment]
See #12626

**Comment by superbonaci** [comment]
This @msftbot is really eager to mark issues as fixed. Why the hell has to close the issue WITHIN 24H???????

**Comment by superbonaci** [comment]
Continue here: https://github.com/PowerShell/PowerShell/issues/12648

**Comment by iSazonov** [comment]
This was closed at a time when .Net team had not yet expanded support for this version.
