### ISSUE TITLE
MyInvocation.Line doesn't work for commands split across multiple lines

### ISSUE THREAD

**Issue by weshaggard** [PowerShell/PowerShell#12609]
My team uses powershell scripts a lot as part of our Azure DevOps pipelines and there is a lot of times we don't have enough information to debug when something goes wrong so I'm been trying to find a nice easy way to output the exact command line so we can try and reproduce it locally. I found an old PS blog post https://devblogs.microsoft.com/powershell/getting-all-your-parameters/ which I thought would do the job so I started using [MyInvocation.Line](https://github.com/Azure/azure-sdk-tools/commit/80de19bbcd4226c37c0085036bdf15b1022afd0c#diff-bb4f526089847eee6eb5471ec830d63c) but the first time I needed to use this information to debug I realized it only contained the first line of the command line and since we often split long command lines across multiple lines to make reading easier that didn't end up helping like I wanted. 

# Steps to reproduce

```powershell
> function test { $myinvocation.line.substring($myInvocation.OffSetInLine-1) }
> test 1 2 3 `
>> 4 5 6
```

# Expected behavior

```none
test 1 2 3 4 5 6
```
or perhaps
```none
test 1 2 3 `
4 5 6
```

# Actual behavior

```none
test 1 2 3 `
```

# Environment data

```none
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I'd also be happy with another simple way to echo the exact command line of a script call.

**Comment by iSazonov** [comment]
Code for the Line:
https://github.com/PowerShell/PowerShell/blob/f4382202ae4622bf26795e29a7b39b9d7cdfb3fb/src/System.Management.Automation/engine/InvocationInfo.cs#L259-L270

@TylerLeonhardt Can we return `ScriptPosition.Text`? Or it break PSES?

**Comment by iSazonov** [comment]
> My team uses powershell scripts a lot as part of our Azure DevOps pipelines and there is a lot of times we don't have _enough information to debug_ when something goes wrong

/cc @joeyaiello @SteveL-MSFT for information.

**Comment by SeeminglyScience** [comment]
Ideally `ScriptPosition` would just become public.  I don't think the change you suggested would necessarily break anything because iirc PSES typically directly accesses `ScriptPosition` via reflection. That said, it would be sort of a lie since it isn't necessarily a line.

**Comment by Jaykul** [comment]
I'm fairly certain we'd all be content with a "Statement" property instead ...

**Comment by IISResetMe** [comment]
WG-Engine reviewed this issue yesterday, and we generally agree the full extent of the originating statement should be made part of the public API, but that the `Line` property should retain its current behavior to guard against existing use cases expecting a single-line string. 

I expect to have a PR ready for further discussion later this week.

**Comment by rkeithhill** [comment]
@IISResetMe Any progress on that PR?

**Comment by IISResetMe** [comment]
@rkeithhill yes, thanks for the kind reminder! 😄
