### ISSUE TITLE
Bug report - Powershell 6 to 7 - PowerShell 6 navigation menu isn't removed.

### ISSUE THREAD

**Issue by FellFromTheSky** [PowerShell/PowerShell#12600]
When installing PowerShell 7 and uninstalling PowerShell 6, this the PowerShell 6 navigation menu isn't removed. See it here :
![BUGPS67](https://user-images.githubusercontent.com/47761913/81311977-1019cb80-9054-11ea-95e1-58c9d0581821.png)

**Comment by iSazonov** [comment]
It is known issue. You have to manually cleanup Registry.

**Comment by FellFromTheSky** [comment]
I tried to use one of the tools by NirSoft, but I can't even detect the PS6 navigation menu item.

**Comment by iSazonov** [comment]
Perhaps it was in #12105
