### ISSUE TITLE
new-psSessionOption: A parameter cannot be found that matches parameter name 'IdleTime

### ISSUE THREAD

**Issue by mdlokesh007** [PowerShell/PowerShell#12604]
[-OpenTimeout <Int32>]
   [-CancelTimeout <Int32>]
   [-IdleTimeout <Int32>]

options are mission on RHEL where as on winodows they are available.

[root@lokesh-38 localdisk]# pwsh-preview 
PowerShell 7.1.0-preview.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /opt/localdisk> 
PS /opt/localdisk> New-PSSessionOption -
SkipCACheck          Verbose              ErrorAction          InformationAction    WarningVariable      OutVariable          PipelineVariable     
SkipCNCheck          Debug                WarningAction        ErrorVariable        InformationVariable  OutBuffer

**Comment by iSazonov** [comment]
I guess they present but it is tab completion issue.

**Comment by mdlokesh007** [comment]
Its not tab completion issue . I get the error "new-psSessionOption: A parameter cannot be found that matches parameter name 'IdleTimeOut"  when i try "new-psSessionOption -IdleTimeout"

**Comment by iSazonov** [comment]
It is by design since OMI is not supported. See #8279.
