### ISSUE TITLE
Previous progress remains displayed for successive invocation of Invoke-WebRequest

### ISSUE THREAD

**Issue by hazychill** [PowerShell/PowerShell#12603]
# Steps to reproduce

```powershell
& {
    $uri = 'http://ipv4.download.thinkbroadband.com/5MB.zip'
    Invoke-WebRequest -Uri $uri -OutFile 'data1.dat'
    Invoke-WebRequest -Uri $uri -OutFile 'data2.dat'
    Invoke-WebRequest -Uri $uri -OutFile 'data3.dat'
    Invoke-WebRequest -Uri $uri -OutFile 'data4.dat'
    Invoke-WebRequest -Uri $uri -OutFile 'data5.dat'
}
```

# Expected behavior
Progress of previous Invoke-WebRequest disappears before new one starts and console displays only progress of current Invoke-WebRequest.

![7 0 0](https://user-images.githubusercontent.com/174583/81322649-45173400-90cf-11ea-8967-4d66999a6b6d.png)

# Actual behavior
Progresses of all previous Invoke-WebRequest remain in console.

![7 1 0-preview 2](https://user-images.githubusercontent.com/174583/81322666-48122480-90cf-11ea-975c-a7fbb8070871.png)

Bisecting the git repository tells me that 8ebff6a2a4ea09c5bf4f3c35e227af16f174f157 is the first bad commit.

# Environment data

```none
PS Temp:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is by-design. And it is a compromise - if PowerShell removed this at cmdlet finish you would never saw 100% complete message, as result the message is automatically removed at pipeline end.

**Comment by hazychill** [comment]
@iSazonov OK, understood.
But, is there any trick of scripting that mimic previous behavior?

**Comment by iSazonov** [comment]
At first look you could try to put the `Invoke-WebRequest` in nested pipeline.
