### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#12616]
# Steps to reproduce
Run the attached script.
It uses the disk serial number obtained using Get-Disk or Get-PhysicalDisk and tries to use the output to obtain the disks that match the serial number using Get-Disk or Get-PhysicalDisk

This does not work as the output from Get-Disk contains leading spaces which are not present using Get-PhysicalDisk

E,g.
Disk Number: [1] Serial:[            S1E35PF2] (Using Get-Disk)
Disk Number: [1] Serial:[S1E35PF2] (Using Get-PhysicalDisk

```powershell

```

# Expected behavior
Using the output from either method should be usable in the other to obtain the appropriate disk output.

See the TXT file in the zip and how the output differs and is confusing

I think the documentation may also need addressing as it seems to differ from reality if I am looking at the correct page see the online version link shown using "get-help Get-PhysicalDisk"

```

# Actual behavior
The request to find disks with a particular serial number using the output from either sometimes returns an error and other times the result is empty. 

Using Get-Disk:
`Disk Number: [1] Serial :[            S1E35PF2] (From Get-Disk using Get-Disk)
Disk Number: [1] Serial :[] (From Get-Disk using Get-PhysicalDisk)`

Using Get-PhysicalDisk:
Get-Disk: S:\Test\GetDiskExample.ps1:27
Line |
  27 |  … ng Get-Disk)' -f $item, (Get-Disk -SerialNumber $SerialNumber).Serial …
     |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No MSFT_Disk objects found with property 'SerialNumber' equal to 'S1E35PF2'.  Verify the value of the
     | property and retry.

Disk Number: [1] Serial :[] (From Get-PhysicalDisk using Get-Disk)
Disk Number: [1] Serial :[S1E35PF2] (From Get-PhysicalDisk using Get-PhysicalDisk)

Both methods should work in the same way and the "Number" property should be available using Get-PhysicalDisk
```

# Environment data

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
[GetDiskExample.zip](https://github.com/PowerShell/PowerShell/files/4605988/GetDiskExample.zip)

```none

```

**Comment by iSazonov** [comment]
These cmdlets is not in the repository. Please use Windows 10 Feedback tool or UserVoice site.
