### ISSUE TITLE
mysterious variable

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#12613]
Hi guys

$PSLogUserData and $LogSettingsEvent are two built-in  variable, the uniq information i have is for [logging ](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SpecialVariables.cs) but there is no example of using these variables. what is their purpose? and how to use them? are there any examples of use case

thanks

**Comment by iSazonov** [comment]
If they are not documented, you can only see in the code how they are used. Although maybe it's outdated code.

**Comment by no-identd** [comment]
> Hi guys
> 
> $PSLogUserData and $LogSettingsEvent are two built-in  variable, the uniq information i have is for [logging ](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/SpecialVariables.cs) but there is no example of using these variables. what is their purpose? and how to use them? are there any examples of use case
> 
> 
> thanks

Check https://github.com/PowerShell/PowerShell/blob/master/src%2FSystem.Management.Automation%2Flogging%2FLogProvider.cs#L173 and https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs#L307

(Note: "Crimson"=Longhorn Codename for the modern event system)

Seems ETW & tracing related I guess?

<blockquote><img src="https://repository-images.githubusercontent.com/49609581/aad0ad80-cdec-11ea-8248-a37bc0571bfd" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/logging/LogProvider.cs">PowerShell/src/System.Management.Automation/logging/LogProvider.cs at master · PowerShell/PowerShell</a></strong></div><div>PowerShell for every system! Contribute to PowerShell/PowerShell development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/49609581/aad0ad80-cdec-11ea-8248-a37bc0571bfd" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs">PowerShell/src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs at master · PowerShell/PowerShell</a></strong></div><div>PowerShell for every system! Contribute to PowerShell/PowerShell development by creating an account on GitHub.</div></blockquote>
