### ISSUE TITLE
Use Windows Powershell in Pwsh7

### ISSUE THREAD

**Issue by onriv** [PowerShell/PowerShell#12614]
# Steps to reproduce

```powershell
[void][System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic')
$name = [Microsoft.VisualBasic.Interaction]::InputBox("Enter your name", "Name", "Lastname")
```

or 

```powershell
Get-WmiObject win32_physicalmemory
```

# Expected behavior

working as in windows powershell, basically anything related to com or windows api cant be used in pwsh7

```powershell
# Get-WmiObject win32_physicalmemory
>>


__GENUS              : 2
__CLASS              : Win32_PhysicalMemory
__SUPERCLASS         : CIM_PhysicalMemory
... others
```

```none
[void][System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic')
$name = [Microsoft.VisualBasic.Interaction]::InputBox("Enter your name", "Name", "Lastname")
```

![image](https://user-images.githubusercontent.com/1629055/81488935-4cdb0200-92a2-11ea-97ea-c3aa293e80ba.png)

# Actual behavior

```powershell
# Get-WmiObject win32_physicalmemory
>>
Get-WmiObject: The term 'Get-WmiObject' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

~
# [void][System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic')

~
# $name = [Microsoft.VisualBasic.Interaction]::InputBox("Enter your name", "Name", "Lastname")
InvalidOperation: Method invocation failed because [Microsoft.VisualBasic.Interaction] does not contain a method named 'InputBox'.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Please read and fill out the proper issue template for your question. There is't enough information here to really make any kind of meaningful determination as to what the problem actually is.

I will, however, note that neither of your listed commands will work in Windows PowerShell either.

**Comment by onriv** [comment]
@vexx32 I'm sorry and the question should have been clarified and followed the template now.

And though I used 

```powershell
 Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell
WARNING: Module Microsoft.PowerShell.Management is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell Core please use 'Import-Module -SkipEditionCheck' syntax.


~
# Get-WmiObject win32_physicalmemory
>>
Get-WmiObject: The term 'Get-WmiObject' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

it's still not working

**Comment by vexx32** [comment]
@onriv thanks for updating the issue!

We're conflating a few separate issues here, but ultimately I think you could resolve them all without too much difficulty.

The `*-WmiObject` cmdlets were deprecated in PowerShell version **3**. Please use the `Get-CimInstance` cmdlet as a replacement; for most tasks they are a drop-in replacement, parameters are all very similar or identical in a lot of cases. Some things previously directly referenced as methods on the objects may need to be handled with `Invoke-CimMethod` instead, however.

You will most likely not be able to reliably import a Windows PowerShell core module in pwsh, or if you can I would expect reduced functionality as it is over a remoting connection. I wouldn't count on it, and it's better to use the CIM cmdlets in pwsh instead.

As for the Visual Basic issue, not really sure where to begin on that, but I'd check the documentation for those libraries to see what's changed in the .NET Core versions of those. In a lot of cases, the GUI functionalities of many libraries were removed. That's neither here nor there, it's far beyond what PowerShell has any control over.

**Comment by SeeminglyScience** [comment]
@onriv For more info on `Get-WmiObject`, see [Breaking Changes for PowerShell 6 -  WMI v1 cmdlets](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-7#wmi-v1-cmdlets).

**Comment by onriv** [comment]
@SeeminglyScience thanks, the document would solve my probelm for the wmi api

@vexx32 And I can't use .Net framework in pwsh7? I tried to add the dll of .Net but it didn't work neither:

```powershell
~
# Add-Type -Path C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.VisualBasic.dll


~
# $name = [Microsoft.VisualBasic.Interaction]::InputBox("Enter your name", "Name", "Lastname")
InvalidOperation: Method invocation failed because [Microsoft.VisualBasic.Interaction] does not contain a method named 'InputBox'.
```

mostly this part is for using com-object (like excel/outlook/vb). Sometimes switching from pwsh7 console to powershell and then switching back is not very convenient, especially if having to share some variables.

**Comment by SeeminglyScience** [comment]
You can use the .NET API, it's just subject to it's own breaking changes outside of PowerShell's control.  That library no longer contains the `InputBox` API and it's not controlled by the PowerShell team.  See the discussion in #11513 about `MsgBox` in the same library.

Also note that it doesn't affect COM interop.

**Comment by onriv** [comment]
@SeeminglyScience @vexx32 thanks a lot ! Since the information have been enough for me, I closed the issue.

**Comment by onriv** [comment]
@SeeminglyScience @vexx32 Hello~ I still got a problem:

I got the dll version that windows powershell is using:

```powershell
# [Microsoft.VisualBasic.Interaction].Assembly

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll
```

And try to add the dll to pwsh7:

```powershell
~
# [Microsoft.VisualBasic.Interaction].Assembly

GAC    Version        Location
---    -------        --------
False  v4.0.30319     D:\Users\sha*****\Apps\PowerShell-7.0.0-win-x64\Microsoft.VisualBasic.Core.dll



~
# Add-Type -Path C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll


~
# $name = [Microsoft.VisualBasic.Interaction]::InputBox("Enter your name", "Name", "Lastname")
InvalidOperation: Method invocation failed because [Microsoft.VisualBasic.Interaction] does not contain a method named 'InputBox'.


~
# [Microsoft.VisualBasic.Interaction].Assembly

GAC    Version        Location
---    -------        --------
False  v4.0.30319     D:\Users\sha*****\Apps\PowerShell-7.0.0-win-x64\Microsoft.VisualBasic.Core.dll
```

but anyway it still use the version that pwsh7 port with?

**Comment by rjmholt** [comment]
@onriv in your last example, you've already loaded `D:\Users\sha*****\Apps\PowerShell-7.0.0-win-x64\Microsoft.VisualBasic.Core.dll` when you import the GAC's `C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll`. It's loaded because you've already used the `Microsoft.VisualBasic.Interaction` assembly in your first command.

If you start a fresh PowerShell session, this will work:

```powershell
Add-Type -Path C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll
[Microsoft.VisualBasic.Interaction]::InputBox("Enter your name", "Name", "Lastname")
```'

In this case though, I would recommend using [a WinForms solution](https://docs.microsoft.com/en-us/powershell/scripting/samples/creating-a-custom-input-box?view=powershell-7), since that's supported by the DLLs that come with PowerShell (so no Add-Type from the GAC needed).

**Comment by DenisBalan** [comment]
@onriv there is a hack to get it working in pwsh7 core
load it as a dynamic assembly and invoke static method InputBox

$v = [System.Reflection.Assembly]::LoadFile('C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.VisualBasic.dll')
#instead of directly referencing InputBox
#[Microsoft.VisualBasic.Interaction]::InputBox("Title", "File data", "")
$hh = $v.GetExportedTypes() |? { $_.Name -eq 'Interaction'}
$to = $hh.GetMethod('InputBox')
$to.Invoke($null, @("Title", "File data", "", -1, -1))
