### ISSUE TITLE
Compress-Archive should expose -FollowSymlink parameter

### ISSUE THREAD

**Issue by tnorrisvnc** [PowerShell/PowerShell#12624]
# Summary of the new feature/enhancement

Compress-Archive should be able to compress files in symbolic link directories. Currently, if you have a directory structure like:
```
folder_to_compress
|--regular_subdir
|  |--regular_file
|--symlink_subdir
   |--symlink_file
```

and you run 
`Compress-Archive -Path .\folder_to_compress -DestinationPath compressed.zip`

The output file is missing symlink_subdir and symlink_file, at least on Windows.

# Proposed technical implementation details

Expose -FollowSymlink from Get-ChildItem as a parameter to Compress-Archive, or use -FollowSymlink by default.

**Comment by vexx32** [comment]
@tnorrisvnc The *-Archive cmdlets are maintained in the [Microsoft.PowerShell.Archive](/PowerShell/Microsoft.PowerShell.Archive) repo; can you file this issue there instead, please? 🙂
