### ISSUE TITLE
Please support Ubuntu 20.04

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#12626]
# Details of the Distribution

- Name of the Distribution: Ubuntu 
- Version of the Distribution: 20.04 
- Processor Architecture (One per request): 
- [x] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker
- The following is a requirement for supporting a distribution **without exception.**
  - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and 
  the PowerShell comittee will review the request.
  - [x] The version of the Distribution is supported for at least one year.
  - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [x] Docker image created
- [x] Docker image published
- [x] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] Lifecycle updated
- [ ] Documentation Updated

Further adding to this Ubuntu 20.04 is an LTS so releasing a supported version of this would be a good long term investment for the community

I would love to see a 7.0 release for it (LTS with another LTS) but expect a retro release would not be feasible so if this could fit in for a 7.1 release that would be great

**Comment by kilasuit** [comment]
The corresponding Docker request is https://github.com/PowerShell/PowerShell-Docker/issues/404 - thanks to @TravisEz13 

& doing so would properly fix this issue - https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5906

**Comment by TravisEz13** [comment]
This one is pretty obvious.  I won't send this to the committee.  Let's consider this approved.  We need a tar.gz based container to do the testing.

**Comment by bergmeister** [comment]
With the new .Net Core 3.1.4 (and 2.1.18) runtime release yesterday, .Net has added support for Ubuntu 20.04: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.4/3.1.4.md#net-core-lifecycle-news

**Comment by superbonaci** [comment]
Up so @msftbot doesn't close it. `sudo snap install powershell --classic` still doesn't install required version on .net.

**Comment by TravisEz13** [comment]
@superbonaci Please use https://github.com/powerShell/powershell-snap to discuss issues with the snap package.  Specifically, https://github.com/PowerShell/PowerShell-Snap/issues/65

**Comment by tmknight** [comment]
Interestingly, the [16.04](https://github.com/PowerShell/PowerShell/releases/download/v7.0.1/powershell_7.0.1-1.ubuntu.16.04_amd64.deb) package for 7.0.1 successfully installs on 20.04

**Comment by xdaDaveShaw** [comment]
I've just done `dotnet install -g powershell` on my 20.04 WSL and it has installed 7.0.1

**Comment by superbonaci** [comment]
> 
> 
> I've just done `dotnet tool install -g powershell` on my 20.04 WSL and it has installed 7.0.1

But is that equivalent to `sudo snap install powershell --classic` or what is the difference?

**Comment by TravisEz13** [comment]
@superbonaci 
> But is that equivalent to sudo snap install powershell --classic or what is the difference?

`dotnet tool install` uses the dotnet sdk install to get the dotnet native dependencies, meaning you are actually running on the host os binaries.  

In snap, you are running in a containerized environment, the base layer is current 18.04, the PowerShell snap bring PowerShell and dotnet that work against the 18.04 layer, with access to your host OS.

**Comment by bergmeister** [comment]
@superbonaci Kind of in the sense that it gets the job done of putting pwsh somewhere and setting various environment variables.
Depending on the use case this might be just a workaround though because you need to think about updating that version in the future. The dotnet tool has an update command but not yet a command to update all installed tools. For a local dev environment, it's probably OK as a workaround but I wouldn't use this way of distributing it across machines due to the maintenance overhead. Ideally you only want to use 1-2 package managers and avoid using too many different package managers.

**Comment by superbonaci** [comment]
Tried today on ubuntu 20.04 with `sudo snap install powershell --classic` and install and runs fine PowerShell 7.0.1, so can close issue. Mark as fixed.

**Comment by kilasuit** [comment]
@superbonaci  no we can't - until there is a binary that can be installed on 20.04

**Comment by kilasuit** [comment]
you can however go and update the docs page sayin that it can work via snap, though I can't get this working with Ubuntu 20.04 on WSL via Snap

**Comment by TravisEz13** [comment]
Perhaps we should update the distribution request to say that snap support is off topic and those issues should be discussed in the PowerShell/PowerShell-snap repo.

**Comment by TravisEz13** [comment]
I made the change.  
https://github.com/PowerShell/PowerShell/blob/master/.github/ISSUE_TEMPLATE/Distribution_Request.md

**Comment by mattduguid** [comment]
> I've just done `dotnet tool install -g powershell` on my 20.04 WSL and it has installed 7.0.1

That method wouldn't work for me but after installing the .net core sdk and run times the following command allowed it to install without error on 20.04 -> sudo snap install powershell --classic

**Comment by superbonaci** [comment]
@mattduguid that also worked for me:
````
sudo snap install powershell --classic
sudo snap install dotnet-sdk --classic
````

**Comment by superkid200** [comment]
The instructions on the Docs actually works, but you need to type powershell instead of pwsh.

**Comment by josteink** [comment]
Rather than discussing how to dissuade the community from bringing up Ubuntu 20.04-support, I'd propose you close this issue and mark it as "solved".

If you check, you will see snaps have been published for Ubuntu 20.04:

````
$ snap search powershell
Name                Version          Publisher              Notes    Summary
powershell          7.0.1            microsoft-powershell✓  classic  PowerShell for every system!
powershell-preview  7.1.0-preview.3  microsoft-powershell✓  classic  PowerShell for every system!
...
````

I've installed it, tested and it works *fine*. Cheers!

**Comment by superbonaci** [comment]
Stop marking comments as off-topic.

**Comment by TravisEz13** [comment]
> Stop marking comments as off-topic. 

@superbonaci Please make comments about snap in the snap repo.  This issue is not about the snap or dotnet tool.

**Comment by dmarinere** [comment]
Please support Us

**Comment by johlandabee** [comment]
If you can't use the snap package because missing dependencies for PS remoting: The container image works just fine.

**Comment by dmarinere** [comment]
I have installed it with Dotnet dependency, but now I am having trouble logging in, I get an error of this client.Subscription cannot be found

**Comment by jwhipp** [comment]
`dotnet tool install -g powershell`

This also worked for me on WSL 2 Ubuntu 20.04, and while that's great, I'd rather have the native.    Seems that, just getting the package dependencies sorted for 20.04 is all that is needed since the binary works fine.

**Comment by BristolITDave** [comment]
Just upvoting this... can't believe that 20.04 has been out for two months and isn't supported still? This is the LTS build... this will become standard very soon for anyone installing Ubuntu. Please consider expediting!

**Comment by petersen65** [comment]
Please support Ubuntu 20.04. Thanks.

**Comment by steveoams** [comment]
bump

**Comment by TravisEz13** [comment]
This is approved and in progress.  Locking conversation so we can focus on the work.

**Comment by TravisEz13** [comment]
This is not fixed.  @SteveL-MSFT Please make sure all the work is done before closing

**Comment by anmenaga** [comment]
Just in case, duplicating instructions link from the main page here:
[Installation instructions for Ubuntu 20.04](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#ubuntu-2004)
