### ISSUE TITLE
OS environment variable mappings should be better specified/implemented

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1262]
`System.Management.Automation.Environment.GetEnvironmentVariable(string)` maps some environment variables when they do not exist:

```
OS => "linux"
COMPUTERNAME => HOSTNAME
USERNAME => USER
HOMEPATH => HOME
USERPROFILE => HOME
TMP => TMPDIR
TEMP => TMPDIR
```

There are a couple issues with this.
1. They aren't true environment variables, so child processes won't see $env:HOMEPATH or $env:OS
2. There is no mapping back to Windows
3. Other possibly useful Windows env vars aren't there, like ProgramFiles, AppData, or LocalAppData

If we keep what we have (for portability), I think it's better to define these variables as proper environment variables at startup rather than map them when they are accessed.

Regarding bullet 3, I think these map to XDG directories - do we expose those as an api or env vars?

**Comment by daxian-dbw** [comment]
Those mapping environment variables were removed in PR #1721, at https://github.com/PowerShell/PowerShell/pull/1721/files#diff-5599b99aca945f353fb890ab80b010dbL827

And for XDG directories, we current expose them as an API which is only available in unix platform:
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L229

**Comment by Liturgist** [comment]
PowerShell core should ensure that there is a Env:TEMP variable that developers can count on using all platforms. If you don't want to name it 'TEMP', then pick something else.

**Comment by SteveL-MSFT** [comment]
@Liturgist there's a separate issue specifically around TEMP https://github.com/PowerShell/PowerShell/issues/4216

**Comment by SteveL-MSFT** [comment]
Since the original issue is resolved and we have other issues to capture the interop of env vars, closing this.
