### ISSUE TITLE
PowerShell unexpectedly executes documents located in $env:PATH directories as commands

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12632]
See also: #12625

# Steps to reproduce

```powershell
# Create a text file in the temp dir and prepend 
# the temp dir to $env:PATH for this session.
'hi' > temp:/foo.txt
$env:PATH = (Convert-Path 'temp:/') + [io.path]::PathSeparator + $env:PATH

# Go to a directory *other* than where the file is located (and where no foo.txt file exists either).
Set-Location

# Invoke foo.txt by mere file name.
{ foo.txt } | Should -Throw
```

# Expected behavior

The test should succeed, because the following error should be reported:

```none
foo.txt: The term 'foo.txt' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

# Actual behavior

`foo.txt` opens in the system's default text editor, and the test fails:

```none
Expected an exception, to be thrown, but no exception was thrown.
```

That is, `foo.txt` was  unexpectedly looked for in the directories listed in `$env:PATH`, and then invoked _as a document_, as if it had been passed to `Invoke-Item`.

I don't think users expect to invoke _documents_ by mere file name from `$env:PATH` locations - doing so isn't useful, and, conversely, users may end up operating on different files than they expect.

Note that, by contrast, `Invoke-Item foo.txt` commendably looks only in the _current_ directory.

# Environment data

```none
PowerShell Core 7.1.0-preview.2
```

**Comment by cmkb3** [comment]
This doesn't appear to be specific to PATH handling -- giving PowerShell a literal file path will open the file directly regardless of whether it exists in PATH. PATH just facilitates discovering/passing the exact path:

(7.4.6)
```ps
'hi' > temp:/foo.txt
C:\Users\YourUser\AppData\Local\Temp\foo.txt

# foo.txt opened by default .txt handler
```

re: [about_Command_Precedence](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7.4#command-precedence)
> You can run any executable command using its full path.

**Comment by cmkb3** [comment]
> What isn't expected - and confusing - is that if a document happens to located in one of the directories listed in $env:PATH, you can invoke it without a path; e.g., submitting foo.txt may open a file c:\some\random\dir\in\path\foo.txt, which is unhelpful.

This interaction isn't specific to documents (.txt). It occurs for _any_ file when the console is given a full file path in both CMD and PowerShell. You can test this functionality by intentionally creating a file with a non-registered extension (e.g.: `.noexist`) and repeating the earlier tests upon which you'll get the `Select an app to open this .noexist file` popup.

This is part of the default Windows shell interaction, and attempting to intercept these scenarios to preemptively catch and break them is counter intuitive.

See: [about_Command_Precedence - Running external executables](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7.4#running-external-executables), re:

> On Windows. PowerShell treats the file extensions listed in the $env:PATHEXT environment variable as executable files. Files that aren't Windows executables are handed to Windows to process. Windows looks up the file association and executes the default Windows Shell verb for the extension. For Windows to support the execution by file extension, the association must be registered with the system.

e.g.

1. Command `foo.txt` -- not an alias, function, or cmdlet, so pass to Windows
2. 'foo.txt' resolves via PATH to `C:\Users\USERNAME\AppData\Local\Temp\foo.txt`
3. '.txt' is a registered application in `HKCR` (and/or `HKCR:\CLSID`), call default handler to open %1

**Comment by mklement0** [comment]
My only concern are _name-only_ invocations, which in PowerShell normally work _only_ for files that are discoverable via `$env:PATH`.

E.g., you can _not_ open file `foo.txt` located _in the current directory_ in PowerShell; you must use a _path_, e.g., `.\foo.txt`

That is an intentional deviation from the behavior of `cmd.exe` and the Windows shell (via `ShellExecute`) (which between them behave differently with respect to whether a current-directory or a `PATH`-based file takes precedence), so it is well-established that PowerShell can and does "its own thing".

Locating _executables_ via `$env:PATH` in name-only invocations makes perfect sense; locating _documents_ (i.e. files that _aren't themselves executable_, but require interpretation by an _associated_ executable) does _not_:

* If I invoke `foo.exe` , I'm happy to defer to `$env:PATH` to locate said executable.
* If I invoke `foo.txt`, i.e. a _document_ with _instance-specific content_ rather than a generic _executable_, it makes no sense to defer to `$env:PATH`, given that there can be a multitude of `foo.txt` files around and I won't know which one will open, unless I examine the entries in `$env:PATH` first.
  * More likely than not, invocation `foo.txt` is a mistaken attempt to open a file by that name _in the current directory_.
  * Normally, PowerShell alerts you to that fact with a _suggestion_ (`was not found, but does exist in the current location` - though the wording regrettably uses the term _command_), but if a file with that name happens to be discoverable via `$env:PATH`, it is opened instead; an unaware user can end up accidentally modifying the wrong file.
