### ISSUE TITLE
Exit-PSSession error on Windows 10 to Linux remote session

### ISSUE THREAD

**Issue by travisgan** [PowerShell/PowerShell#12635]
# Steps to reproduce
Windows 10 desktop and Linux redhat both installed with Powershell 7.0
Linux server installed with psl-omi-provider and omi from below urls
https://github.com/PowerShell/psl-omi-provider
https://github.com/Microsoft/omi

On desktop, enter-pssession from windows desktop to remote to linux works by following the similar instruction as shown in the psl-omi-provider link.
$so = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
Enter-PSSession -ComputerName <linux server> -Credential <acct> -UseSSL -SessionOption $so -Authentication Basic

However, exit-pssession returns error and number of omiagent process on linux server kept increasing after multiple remote attempts (possibly due to incomplete exit-pssession)

# Expected behavior
Exit-PSSession should close the ps session successfully (and its omiagent process), but it throws error.

# Actual behavior
Exit-PSSession returns the following error.

Closing the remote server shell instance failed with the following error message : <SOAP-ENV:Fault xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope"><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Receiver</SOAP-ENV:Value><SOAP-ENV:Subcode><SOAP-ENV:Value>wsman:InternalError</SOAP-ENV:Value></SOAP-ENV:Subcode></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en-US"/></SOAP-ENV:Reason></SOAP-ENV:Fault> For more information, see the about_Remote_Troubleshooting Help topic.

On linux server, the number of omiagent process kept increasing with after multiple remote attempts and exit-pssession failures (possibly due to incomplete exit-pssession).

# Environment data
Desktop
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Linux server
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Installed omi and omi-psrp-server packages
Name        : omi
Arch        : x86_64
Version     : 1.6.4
Release     : 1
Size        : 4.4 M
Repo        : installed
Summary     : Open Management Infrastructure
License     : MIT
Description : omi server

Name        : omi-psrp-server
Arch        : x86_64
Version     : 1.4.1
Release     : 28
Size        : 872 k
Repo        : installed
Summary     : PowerShell Remoting Protocol
License     : MIT
Description : PowerShell Remoting Protocol provider

**Comment by iSazonov** [comment]
OMI is deprecated. https://github.com/PowerShell/PowerShell/issues/8233
 You should use SSH for remoting from Unix-s..

**Comment by neugan** [comment]
This issue was PowerShell remote session from Windows 10 to Linux (not Linux to Windows). But thanks for the clarification on OMI deprecation, wasn't aware of that announcement.

**Comment by iSazonov** [comment]
Really WinRM can works on Linux. 
Your issue is that you use `UseSSL` with `New-PSSessionOption` but `New-PSSessionOption` is based on WinRM and is not compatible with SSH.

**Comment by iSazonov** [comment]
@PaulHigin Is the issue the same as https://github.com/PowerShell/PowerShell/issues/12654#issuecomment-628727230 ?
