### ISSUE TITLE
Get-CimInstance requires elevated privileges

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#12643]
I am using Powershell SDK 7.0 from C#
# Steps to reproduce
My C# app is running as a normal user (not elevated)
```powershell
(Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
```

# Expected behavior
Get the number of logical processors (4 in my test environment, validated through Windows Powershell 5.1 running as normal user.)
# Actual behavior
I get the following error from API
{The 'Get-CimInstance' command was found in the module 'CimCmdlets', but the module could not be loaded. For more information, run 'Import-Module CimCmdlets'.}

I tried adding import-module CimCmdlets in front of the command but received "Scripting not enabled" which leads to running executionpolicy command as elevated inside script.

# Environment data
PSVersion=7.0.0
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3

**Comment by mklement0** [comment]
Your command does not require elevation, and neither does changing the execution policy, as long as you use either `-Scope  CurrentUser` or `-Scope Process`.
Also, you don't need an `.AddScript()` call to invoke `Import-Module`; you can use `.AddCommand("Import-Module").AddArgument("CimCmdlets")`. Once you've done that, you can access the `.Error` collection on the PowerShell instance to see what went wrong.

**Comment by erenturkm** [comment]
OK, this worked
