### ISSUE TITLE
Unexpected newline when parsing JSON

### ISSUE THREAD

**Issue by zachChilders** [PowerShell/PowerShell#12649]
I'm trying to parse a json file and then parse it into a string.  It seems that when I'm parsing in the way that I'm used to, an additional newline is being put into my data.  In the examples below, my `ConvertFrom-Json` call does not include any empty members, but it appears as soon as I start processing the object it produces.

# Steps to reproduce

lints.json: 
```json
{
    "lints": [
        "needless_return",
        "module-inception",
        "many_single_char_names",
        "implicit-hasher"
    ]
}
```

```powershell
Get-Content ./lints.json | ConvertFrom-Json | % lints
```

# Expected behavior

```none
needless_return
module-inception
many_single_char_names
implicit-hasher
```

# Actual behavior

```none

needless_return
module-inception
many_single_char_names
implicit-hasher
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
I cannot reproduce this behavior with the sample input string - are you sure it is representative?

Does the following also reproduce your symptom?

```powershell
@'
{
  "lints": [
    "needless_return",
    "module-inception",
    "many_single_char_names",
    "implicit-hasher"
    ]
 }
'@ | ConvertFrom-Json | % lints
```

**Comment by iSazonov** [comment]
@mklement0 Do you try on MacOS too?

**Comment by vexx32** [comment]
The sample code appears to work just fine on MacOS (Catalina) for me. 😕

**Comment by mklement0** [comment]
Thanks for confirming, @vexx32. @iSazonov, yes, I tried on macOS too (it's usually where I try first).

**Comment by iSazonov** [comment]
I guess the file contains broken newlnes.

**Comment by Liturgist** [comment]
More information might come from:

`Format-Hex -Path ./lints.json`
