### ISSUE TITLE
Set-ExecutionPolicy without -Scope gives misleading error message

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#12646]
`-Scope` should default to `LocalMachine`, which means that running `Set-ExecutionPolicy` from a non-elevated session should fail with an error message indicating the need to elevate.

As of PowerShell Core 7.1.0-preview.2, an inapplicable success / error hybrid message is shown (a regression from 7.0).

# Steps to reproduce

On Windows, from a non-elevated session:

```powershell
# Note: Pick a policy OTHER than the one in effect.
Set-ExecutionPolicy Restricted
```

# Expected behavior

The following error should be reported (which is true in 7.0):

```none
Set-ExecutionPolicy: Access to the path 'C:\Program Files\PowerShell\7\powershell.config.json' is denied.
To change the execution policy for the default (LocalMachine) scope, 
start PowerShell with the "Run as administrator" option. 
To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".
```

# Actual behavior

The following error is emitted instead.

```none
Set-ExecutionPolicy: PowerShell updated your execution policy successfully, 
but the setting is overridden by a policy defined at a more specific scope.  
Due to the override, your shell will retain its current effective execution policy of RemoteSigned.
Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
```

Note that not only is the error message inapplicable, it incorrectly suggests that an update was actually performed.

(And, as an aside: Even when that error is reported as designed, it is problematic - see #12032.)

# Environment data

```none
PowerShell Core 7.1.0-preview.2
```

**Comment by kvprasoon** [comment]
@mklement0 I'm not able to repro this in Pv3

**Comment by mklement0** [comment]
Thanks, @kvprasoon - indeed the symptom is gone in PowerShell Core 7.1.0-preview.3.
