### ISSUE TITLE
invoke-restmethod does not support http/2

### ISSUE THREAD

**Issue by TomCJones** [PowerShell/PowerShell#12641]
I cannot tell if this method should support protocol/verson http/2 - or is that a windows problem still?

**Comment by vexx32** [comment]
Please provide the information requested in the issue template. There's really not a lot to go on here.

For reference, the API used by the cmdlets is here: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1

There is reference to support for other versions of HTTP via this API / the SendAsync() method: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=netcore-3.1

I'm not sure on the state of HTTP2 support on the web cmdlets by default.

**Comment by iSazonov** [comment]
It seems we could consider new `HttpVersion` parameter for all web cmdlets.

**Comment by dmex** [comment]
The version would need to be set in two places since the SendAsync method doesn't use the DefaultRequestVersion. For example the Invoke-WebRequest script:

https://github.com/PowerShell/PowerShell/blob/0f16d0ec6ea7524ccdcf61669b84812474d1d25b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1038-L1038

`httpClient.DefaultRequestVersion = new Version(2, 0);`


https://github.com/PowerShell/PowerShell/blob/0f16d0ec6ea7524ccdcf61669b84812474d1d25b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1079-L1080

`request.Version = new Version(2, 0);`

**Comment by hayhay27** [comment]
could we same time replace [HttpClientHandler](https://docs.microsoft.com/ru-ru/dotnet/api/system.net.http.httpclient?view=netcore-3.1#httpclient-and-net-core)  by SocketsHttpHandler?

> 
>     The use of SocketsHttpHandler offers a number of advantages:
>       * A significant performance improvement when compared with the previous implementation.
>       * The elimination of platform dependencies, which simplifies deployment and servicing. For example, libcurl is no longer a dependency on .NET Core for macOS and .NET Core for Linux.
>       * Consistent behavior across all .NET platforms.

**Comment by iSazonov** [comment]
SocketsHttpHandler is an _implementation_ of HttpClientHandler.

**Comment by hayhay27** [comment]
> 
> 
> SocketsHttpHandler is an _implementation_ of HttpClientHandler.

My fault. I miss sentence about HttpClientHandler implementation.

Anyway. I want to add new parameter HttpVersion for `irm` and `iwr`:

```csharp

[Parameter]
public virtual HttpVersion HttpVersion { get; set; } = HttpVersion.Default;

enum HttpVersion
{
  Default,
  Version10,
  Version11,
  Version20,
  Version30,
}
```

And fill `request.Version` according to `HttpVersion`

If it's ok I'll create PR

**Comment by iSazonov** [comment]
`HttpClient` has `DefaultRequestVersion` property of `Version` type. I think we should use `Version` for the new parameter since new HTTP versions may appear in the future. Argument completer would be great addition. Current supported list is in [HttpVersion class](https://source.dot.net/#System.Net.Primitives/System/Net/HttpVersion.cs,6)

> If it's ok I'll create PR

Come on!

**Comment by SteveL-MSFT** [comment]
If we follow `curl`'s lead, we should default to 2.0 and fallback to 1.1 if negotiation fails: https://everything.curl.dev/http/versions#:~:text=Since%20perhaps%20mid%202016%2C%20curl%20will%20default%20to,capable%20curls%20get%201.1%20over%20HTTPS%20by%20default.

But also expose a `HttpVersion` if the user wants to be explicit.

**Comment by hayhay27** [comment]
> If we follow `curl`'s lead, we should default to 2.0 and fallback to 1.1 if negotiation fails: https://everything.curl.dev

should we consider this as breaking change? default version was [changed](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version?view=net-5.0#remarks) in dotnet 2.1 and reverted in 3.0 for reasons unknown to me

If we definitely follow curl's I can set default as 2.0

> But also expose a `HttpVersion` if the user wants to be explicit.

done

**Comment by iSazonov** [comment]
> should we consider this as breaking change? default version was [changed](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version?view=net-5.0#remarks) in dotnet 2.1 and reverted in 3.0 for reasons unknown to me

History https://github.com/dotnet/runtime/issues/28635#issuecomment-462531816

I think it makes no sense to change the default from 1.1.

**Comment by SteveL-MSFT** [comment]
Unfortunately, the specific reasons of the change from HTTP2 back to HTTP1.1 wasn't made clear in the dotnet/runtime thread.  It seems that the least risky change is to keep default as 1.1 and just expose the `-HttpVersion` parameter if the user wants something better and knows the endpoint supports it.

**Comment by iSazonov** [comment]
> Unfortunately, the specific reasons of the change from HTTP2 back to HTTP1.1 wasn't made clear in the dotnet/runtime thread.

From my understanding, they say that 2.0 and 3.0 are de-facto specific enhancements of 1.1 but not new protocols. So users should explicitly point that they want to use.

**Comment by sergeevabc** [comment]
So, with Powershell 5.1 and 7.2.* it is not possible to connect using HTTP/2?

**Comment by dmex** [comment]
@sergeevabc This issue was fixed 5 years ago? You need to add the `-HttpVersion` parameter for HTTP2/3.

The powershell documentation has examples for HTTP/2 and it's the same for HTTP/3:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.5#example-8-send-a-request-using-http-2-0

**Comment by sergeevabc** [comment]
>> @sergeevabc 
>> So, with PowerShell 5.1 and 7.2.* it is not possible to connect using HTTP/2?

> @dmex
> You need to add the -HttpVersion parameter for HTTP2/3.

``` console
$ pwsh
PowerShell 7.2.24

$ pwsh -c "iwr -Uri https://cloudflare.com/cdn-cgi/trace -HttpVersion 2"
Invoke-WebRequest: A parameter cannot be found that matches parameter name 'HttpVersion'.

**Comment by dmex** [comment]
@sergeevabc 

```
PowerShell 7.5.0
PS C:\Users\Admin> iwr -Uri https://cloudflare.com/cdn-cgi/trace -HttpVersion 2

StatusCode        : 200
StatusDescription : OK
Content           : fl=47f237
                    h=cloudflare.com
                    ip=2403:5811:f66e:0:912a:f871:e831:d096
                    ts=1745196153.781
                    visit_scheme=https
                    uag=Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.26100; en-AU) PowerShell/7.5.0
                    colo=MEL…
RawContent        : HTTP/2.0 200 OK
                    Date: Mon, 21 Apr 2025 00:42:33 GMT
                    Access-Control-Allow-Origin: *
                    Server: cloudflare
                    cf-ray: 9338d7991eabf0da-MEL
                    X-Frame-Options: DENY
                    X-Content-Type-Options: nosniff
                    Cache-Co…
Headers           : {[Date, System.String[]], [Access-Control-Allow-Origin, System.String[]], [Server,
                    System.String[]], [cf-ray, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 298
RelationLink      : {}
```

**Comment by sergeevabc** [comment]
@dmex, consider visiting an ophthalmologist to have your eyesight checked. I've indicated twice which versions of Powershell I'm interested in, but you persistently continue to show me what version 7.5.0, which I'm not interested in, is capable of.

**Comment by iSazonov** [comment]
@sergeevabc Please follow CoC.

The commit you ask was merged in 7.3 milestone https://github.com/PowerShell/PowerShell/blob/92c6f7a632cb2922a61632e21008757371ffd54f/CHANGELOG/7.3.md?plain=1#L1120

**Comment by dmex** [comment]
> I've indicated twice which versions of Powershell I'm interested in

Your post contains 3 lines of command output and doesn't include any text or mention anything about version requirements? If you can't update to the latest version, then it would help to mention you have a specific requirement for some old version of powershell because otherwise everyone is going to provide information from the most recent update.

> you persistently continue to show me what version 7.5.0, which I'm not interested in, is capable of.

Yes, because the latest version is the correct answer.

If you need HTTP/2 support with v7.2.24 then your only option is using .NET methods from a custom function. Here's a basic example that is compatible with v7.2.24:

```ps
function Invoke-HttpClient
{   
    param([Parameter(Mandatory = $true, Position = 1)] [string]$RequestUri)

    Add-Type -AssemblyName "System.Net.Http"

    $handler = [System.Net.Http.HttpClientHandler]::new()
    $handler.UseCookies = $false
    $handler.AllowAutoRedirect = $true
    $handler.MaxConnectionsPerServer = 10

    $client = [System.Net.Http.HttpClient]::new($handler)
    $client.DefaultRequestHeaders.Add("User-Agent", "MyCustomKwonol")
    $client.DefaultRequestHeaders.Add("Accept", "application/json")
    $client.DefaultVersionPolicy = [System.Net.Http.HttpVersionPolicy]::RequestVersionOrLower
    $client.DefaultRequestVersion = [System.Version]::new(2, 0)

    return $client.GetAsync($requestUri).GetAwaiter().GetResult()
 }
```
Then call Invoke-HttpClient and print some output:
```ps
$response = Invoke-HttpClient -RequestUri "https://cloudflare.com/cdn-cgi/trace"
$response.StatusCode
$response.Headers
$response.Content.ReadAsStringAsync().Result
```

**Comment by flawrist** [comment]
> @dmex
> Your post contains 3 lines of command output and doesn't include any text or mention anything about version requirements?
 
I mentioned PS <mark>5.1 and 7.2.*</mark> in my [original question][1], then [repeated][2] this requirement.

[1]: https://github.com/PowerShell/PowerShell/issues/12641#issuecomment-2812700045
[2]: https://github.com/PowerShell/PowerShell/issues/12641#issuecomment-2816931284

![Image](https://github.com/user-attachments/assets/1eec0848-d9b9-4044-adaf-2a48c899ab0f)

> If you need HTTP/2 support with v7.2.24 then your only option is using .NET methods

Does not work, alas, still HTTP/1.1.

**Comment by flawrist** [comment]
I got Pwsh 7.5.1, but `-HttpVersion 2` did not work on my end (with Windows 7).

``` console
$ dotnet --list-runtimes
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

$ $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.5.1
PSEdition                      Core
GitCommitId                    7.5.1
OS                             Microsoft Windows 6.1.7601 Service Pack 1
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$ irm https://cloudflare.com/cdn-cgi/trace -HttpVersion 2
...
http=http/1.1
tls=TLSv1.2
...
```

However, Microsoft Edge v109 outputs `http/3, tls=TLSv1.3`, even [older versions](https://caniuse.com/http3) do too.

Explanation:
* https://github.com/dotnet/runtime/issues/61866

Conclusion:
* What a shame: relatively old Edge browser is capable of, fresh NET/Pwsh is not.
