### ISSUE TITLE
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer informationMy bug report

### ISSUE THREAD

**Issue by jonathantopacio** [PowerShell/PowerShell#12640]
Getting below error message intermittently when calling Invoke-WebRequest
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.

Do you have ideas on how to avoid this issue?

**Comment by vexx32** [comment]
Please refer to the issue template and provide more information so we can appropriately address your issue. 🙂

**Comment by jonathantopacio** [comment]
# Steps to reproduce
$response=Invoke-WebRequest -Uri $Uri -Method POST -ContentType 'application/json'-Body $json

# Expected behavior
It will send request and get response from server


# Actual behavior
Sometimes request/response is successful.

Intermittenly gets below error:
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer informationMy bug report

**Comment by vexx32** [comment]
Please see the bug report template and provide at _least_ your PowerShell and OS Version information.

**Comment by jonathantopacio** [comment]
OS version: Windows Server 2012 R2 Standard
Powershell version: 5.1.14409.1018

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
