### ISSUE TITLE
The null-coalescing operator evaluates the left-hand operand twice.

### ISSUE THREAD

**Issue by chtoucas** [PowerShell/PowerShell#12655]
# Steps to reproduce

```powershell
function A {
    Write-Host "In A"
    return "something"
}

# Here, A is called twice
$y = (A) ?? "blabla"
```

# Expected behavior

The function `A` should be called only once.
```none
In A
```

# Actual behavior

The function `A` is called twice.
```none
In A
In A
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
The LHS here needs to be saved to a temporary variable:

https://github.com/PowerShell/PowerShell/blob/42248a072f806586a262eb2821ac81cf8ed62d09/src/System.Management.Automation/engine/parser/Compiler.cs#L991-L997

Also 

https://github.com/PowerShell/PowerShell/blob/42248a072f806586a262eb2821ac81cf8ed62d09/src/System.Management.Automation/engine/parser/Compiler.cs#L985-L988

`AutomationNull` is a static class that stores an instance of `PSObject` in a static field. This check will never be true.
