### ISSUE TITLE
Tab completion confusion with common parameters

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1265]
## Steps to reproduce

`function foo { param($DebugBuild) }`
1. `Receive-Job -wa<TAB>`
2. `foo -D<TAB>`
3. `foo -Debug<TAB>`
## Expected behavior
1. Cycle through -Wait and -WarningAction
2. Cycle through -Debug and -DebugBuild
3. Cycle through -Debug and -DebugBuild
## Actual behavior
1. Only completes -WarningAction
2. Only completes -DebugBuild
3. No additional completion

**Comment by Peter-Schneider** [comment]
The actual behavior of case 2 should be ok unless you are using the cmdletbinding attribute.

**Comment by SteveL-MSFT** [comment]
@louistio Thanks for the investigation details!

In the your first issue, even if an exact match is found, I would expect it to cycle through other possible matches.  For the second, it should also all possible matches including common parameters.
