### ISSUE TITLE
Get-GPO does not return UserVersion, ComputerVersion or WMI Filters

### ISSUE THREAD

**Issue by lgaudreau** [PowerShell/PowerShell#12661]
In PowerShell 7.0.0, Get-GPO does not return the UserVersion, ComputerVersion or WMI Filter values.

Windows PowerShell 5.1 returns these values.

Tested from both Windows 10 1909 and a non-Domain Controller Windows Server 2019 1809.

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please use UserVoice site or Windows 10 Feedback tool to report the issue.
