### ISSUE TITLE
Feature Request: Make PowerShell to be able to print PDF files

### ISSUE THREAD

**Issue by vazome** [PowerShell/PowerShell#12663]
# Summary of the new feature/enhancement

Early I found that ```Get-Content C:\example.pdf | Out-Printer``` and ```Start-Process –FilePath “c:\docstoprint\doc1.pdf” –Verb Print``` are unable to print at least PDF files

It would be great to have the native ability to print PDF files without these workarounds at least on Windows

# Proposed technical implementation details (optional)
For more information about the issue please refer here: https://github.com/PowerShell/PowerShell/issues/12615#issuecomment-628472368

**Comment by vexx32** [comment]
`Get-Content` reads a file as string data, it has no PDF or image handling. I'm not sure what you'd reasonably expect to get as output if you called `Get-Content` on a PDF file, they're decidedly not plain text files.

Also, `Out-Printer` doesn't seem to be cross-platform, so I'm not sure if there is a great deal of interest in maintaining it / rewriting it in future. 

As for `Start-Process -Verb Print`, this will only work if you've assigned a default PDF handling application in your Windows settings. If you have, that print task would be handled by your PDF application, typically.

**Comment by vazome** [comment]
> 
> Also, `Out-Printer` doesn't seem to be cross-platform, so I'm not sure if there is a great deal of interest in maintaining it / rewriting it in future.
> 
Reasonable. I will correct this issue.

**Comment by rjmholt** [comment]
I think the answer to this probably lies in an external module; PowerShell itself shouldn't know about printers.

@vazome you mention workarounds in your issue description. Would you be able to list them here in case others looking for a solution come to this issue?
