### ISSUE TITLE
I am getting $<5> when i open pwsh on RHEL7 VM. I have tried reinstalling powershell 7 but still i a getting this issue. 

### ISSUE THREAD

**Issue by akashagarwal37** [PowerShell/PowerShell#12679]
# Steps to reproduce
I have used command sudo yum install https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/powershell-lts-7.0.0-1.rhel.7.x86_64.rpm to install pwsh. 

# Expected behavior

I am supposed to type commands like "get-help"
```

# Actual behavior
Command is actually being typed as $<5>get-$<5> but it is providing results as expected. 

# Environment data

<!-- provide the output of $PSVersionTable -->

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0â€¦}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Run `remove-module PSReadline` and try again.

**Comment by akashagarwal37** [comment]
Hey, I did remove PSReadline Module and reboot machine as well after it. Issue is still not resolved.

**Comment by iSazonov** [comment]
Thanks! What is terminal you use?

**Comment by akashagarwal37** [comment]
I am using secure CRT. What's the recommended terminal to user for pwsh.

**Comment by iSazonov** [comment]
You could try `TERM=xterm pwsh`.

**Comment by KalleOlaviNiemitalo** [comment]
`$<5>` is [terminfo](https://linux.die.net/man/5/terminfo) syntax for a delay of five milliseconds. Perhaps there is a bug that prevents PowerShell, or a library used by it, from recognizing this syntax.

**Comment by KalleOlaviNiemitalo** [comment]
In the ncurses library, the `tparm` function evaluates a parameterized string; then the caller can pass the resulting string to `tputs`, which outputs it to the terminal and recognizes the delay syntax.

In the .NET runtime, the internal `System.TermInfo.ParameterizedStrings` class corresponds to `tparm`. <https://github.com/dotnet/runtime/blob/47ec733ba79b196e4e09d0c89bad245155002353/src/libraries/System.Console/src/System/TermInfo.cs#L511-L512>

The bug then seems to be in `System.ConsolePal.WriteStdoutAnsiString`, which corresponds to `tputs` but does not recognize the delay syntax. <https://github.com/dotnet/runtime/blob/47ec733ba79b196e4e09d0c89bad245155002353/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L1388-L1391>

**Comment by iSazonov** [comment]
Please report the issue to .Net Runtime repo.

**Comment by KalleOlaviNiemitalo** [comment]
I hope @akashagarwal37 will report it there, as I don't currently have the software for reproducing the issue.

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
