### ISSUE TITLE
`$ErrorView = "ConciseView"` does not print any errors with module autoloading disabled

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#12671]
PowerShell Core version: v7.0.1

# Steps to reproduce
Run the following lines in `pwsh -noprofile`:
```PowerShell
$PSModuleAutoLoadingPreference = "None"
$ErrorView = "ConciseView"
NonExistentCmdlet
$ErrorView = "NormalView"
NonExistentCmdlet
$ErrorView = "ConciseView"
NonExistentCmdlet
```

# Expected behavior
3 error messages are thrown, 1st and 3rd one formatted as concise error messages, 2nd one as normal error message.

# Actual behavior
When `$ErrorView` is set to `"ConciseView"`, the errors are silently ignored and nothing is displayed. `"NormalView"` works correctly.
![image](https://user-images.githubusercontent.com/6414091/82053401-991cac80-96bd-11ea-8ac3-54492c9a8fb3.png)

When running with `Set-PSDebug -Trace 2`, the following output is displayed:
![image](https://user-images.githubusercontent.com/6414091/81999799-89b64880-9656-11ea-9b8b-4a70e62c2c4d.png)

The output indicates that while printing output, the ConciseView error printing code uses `Test-Path`, which is not loaded because of the disabled auto-loading.

Then, I attempted to first run `Import-Module Microsoft.PowerShell.Management`, which contains the `Test-Path` cmdlet. After the import, with auto-loading still disabled, errors now correctly print in ConciseView.

**This leads me to believe that the issue is in `Get-ConciseViewPositionMessage` function attempting to use `Test-Path`, which is unavailable due to disabled auto-loading.**

# Environment data

PowerShell Core:
```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@MatejKafka can you check if there's anything stored in `$error` in this case?

**Comment by MatejKafka** [comment]
@vexx32 I updated the issue description with more info - I believe I found the root cause.

**Comment by vexx32** [comment]
@MatejKafka thanks!

@SteveL-MSFT looks like something you'll want to take a look at. 🙂

**Comment by iSazonov** [comment]
It is not a regression. Please update the issue header.

**Comment by MatejKafka** [comment]
@iSazonov That's debatable, as ConciseView is (as far as I know) the new default, but I agree the root of the issue is not a regression from powershell.exe, but the new ConciseView. I'll update issue title and reproduction steps accordingly.
