### ISSUE TITLE
New-PSSession does not find WSMan client library on RHEL

### ISSUE THREAD

**Issue by nimehta2010** [PowerShell/PowerShell#12674]
# Steps to reproduce

Go to PS7 on RHEL
Install-Module -Name ExchangeOnlineManagement -RequiredVersion 0.4669.0
This works correctly on ubuntu but gives the following error on RHEL

# Expected behavior

Expected it to connect the RPS session

# Actual behavior

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ARMCN94XP to authenticate.
Exception: /root/.local/share/powershell/Modules/ExchangeOnlineManagement/0.4669.0/netCore/ExchangeOnlineManagement.psm1:426
Line |
 426 |  …             $PSSession = New-ExoPSSession -ExchangeEnvironmentName $E …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either
     | not installed or unavailable for this system.

PS /home/nimehta-linux1> $Error.Exception

ErrorCode                   : 0
TransportMessage            :
ErrorRecord                 : This parameter set requires WSMan, and no supported WSMan client library was found.
                              WSMan is either not installed or unavailable for this system.
WasThrownFromThrowStatement : True
TargetSite                  : Void .ctor()
StackTrace                  :    at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.WSM
                              anAPIDataCommon..ctor()
                                 at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager..ct
                              or(Guid runspacePoolInstanceId, WSManConnectionInfo connectionInfo,
                              PSRemotingCryptoHelper cryptoHelper, String sessionName)
                                 at System.Management.Automation.Runspaces.WSManConnectionInfo.CreateClientSessionTrans
                              portManager(Guid instanceId, String sessionName, PSRemotingCryptoHelper cryptoHelper)
                                 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl..ctor(Client
                              RemoteSession session, PSRemotingCryptoHelper cryptoHelper, RunspaceConnectionInfo
                              connectionInfo, URIDirectionReported uriRedirectionHandler)
                                 at System.Management.Automation.Remoting.ClientRemoteSessionImpl..ctor(RemoteRunspaceP
                              oolInternal rsPool, URIDirectionReported uriRedirectionHandler)
                                 at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.Create
                              ClientRemoteSession(RemoteRunspacePoolInternal rsPoolInternal)
                                 at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler..ctor(
                              RemoteRunspacePoolInternal clientRunspacePool, TypeTable typeTable)
                                 at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.CreateDS
                              Handler(TypeTable typeTable)
                                 at
                              System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal..ctor(Int32
                              minRunspaces, Int32 maxRunspaces, TypeTable typeTable, PSHost host,
                              PSPrimitiveDictionary applicationArguments, RunspaceConnectionInfo connectionInfo,
                              String name)
                                 at System.Management.Automation.Runspaces.RunspacePool..ctor(Int32 minRunspaces,
                              Int32 maxRunspaces, TypeTable typeTable, PSHost host, PSPrimitiveDictionary
                              applicationArguments, RunspaceConnectionInfo connectionInfo, String name)
                                 at System.Management.Automation.RemoteRunspace..ctor(TypeTable typeTable,
                              RunspaceConnectionInfo connectionInfo, PSHost host, PSPrimitiveDictionary
                              applicationArguments, String name, Int32 id)
                                 at Microsoft.PowerShell.Commands.NewPSSessionCommand.CreateRunspacesWhenUriParameterSp
                              ecified()
                                 at Microsoft.PowerShell.Commands.NewPSSessionCommand.ProcessRecord()
                                 at System.Management.Automation.Cmdlet.DoProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
Message                     : This parameter set requires WSMan, and no supported WSMan client library was found.
                              WSMan is either not installed or unavailable for this system.
Data                        : {}
InnerException              : System.DllNotFoundException: Unable to load shared library 'libpsrpclient' or one of its
                              dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG
                              environment variable: liblibpsrpclient: cannot open shared object file: No such file or
                              directory
                                 at System.Management.Automation.Remoting.Client.WSManNativeApi.WSManInitialize(Int32
                              flags, IntPtr& wsManAPIHandle)
                                 at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.WSM
                              anAPIDataCommon..ctor()
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087

# Environment data

PS /home/nimehta-linux1> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Linux 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Tue Jan 14 15:50:19 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
You could try workarounds from https://github.com/PowerShell/PowerShell/issues/11216

**Comment by adityapatwardhan** [comment]
This is not supported on RHEL 8. Please have a look at: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6491

**Comment by andybirenzi** [comment]
I'm having the same issue on AWS Lambda, did anyone figure out this WSMAN error on linux
