### ISSUE TITLE
MSIX not working for 7.0.1.0

### ISSUE THREAD

**Issue by eluchsinger** [PowerShell/PowerShell#12676]
I've just tried to install PS Core 7.0.1.0 with the MSIX x64 installer. 

The installer says the installation with App-Installer is not supported, because "some constrained functions are being used".

I'm using Windows 10 Pro Insider Preview (Version 2004, Build 19624.1000).

![image](https://user-images.githubusercontent.com/12324017/82026011-69a47a80-9692-11ea-961d-407381db1405.png)

**Comment by iSazonov** [comment]
@eluchsinger MSFT team announced in their blog that they works on MSIX package internally and will publish new one soon.

**Comment by Restia666Ashdoll** [comment]
yeah I have the same issue.

**Comment by iSazonov** [comment]
Could you please check with latest 7.1.0 Preview?

**Comment by alexgwolff** [comment]
Hi, looks this https://github.com/PowerShell/PowerShell/issues/11403

**Comment by Restia666Ashdoll** [comment]
When will this come to the Store ?

**Comment by iSazonov** [comment]
@SteveL-MSFT expects this on after 7.1 Preview3.

**Comment by eluchsinger** [comment]
Then I'll close this issue. It probably should be documented somewhere tbh.
