### ISSUE TITLE
More function should support pipelining

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1267]
The current definition of more does not pipeline, it collects all output in $input and then pipes to more after the upstream command finishes.

**Comment by joeyaiello** [comment]
@lzybkr per our conversation with the @PowerShell/powershell-maintainers, would this actually be something that goes to `0 - Backlog`? And if so, what's the intended purpose of `2 - Ready`?

**Comment by iSazonov** [comment]
@lzybkr I attached a script file to address the Issue. Could you please look when you'll have free time? If it is right direction I'll push a PR.
[Next-More.txt](https://github.com/PowerShell/PowerShell/files/1643154/Next-More.txt)
