### ISSUE TITLE
Automatic/Pipeline PowerShell Core releases with Chocolatey distribution

### ISSUE THREAD

**Issue by epomatti** [PowerShell/PowerShell#12673]
# Summary of the new feature/enhancement

I have PowerShell Core `7.0.0` installed with Chocolatey and there's a new upgrade to version `7.0.1`:

![image](https://user-images.githubusercontent.com/6530769/82005156-0a674b80-963b-11ea-923c-91912da29ead.png)

However the upgraded package is not available at Chocolatey.

It would be nice to have a trigger that starts a pipeline allowing Chocolatey to be immediately upgraded with the latest PowerShell Core available.

```
PS > choco upgrade powershell-core 
Chocolatey v0.10.15
Upgrading the following packages:
powershell-core
By upgrading you accept licenses for the packages.
powershell-core v7.0.0 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by DarwinJS** [comment]
This has been implemented for quite some time here https://gitlab.com/guided-explorations/microsoft/chocolatey/powershell-core and can be closed as completed.
