### ISSUE TITLE
String parameters are converted to empty string despite being set to [NullString]::Value

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#12680]
# Steps to reproduce

```powershell
function foo { param([string] $bar = [nullstring]::value) $null -eq $bar }; foo
```

# Expected behavior

```powershell
true
```

# Actual behavior

```powershell
false
```

# Environment data
```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Notes
1. This is especially annoying when using the new null-coalescing operator, e.g.:
```powershell
function foo { param([string] $bar = [nullstring]::value) $bar ?? 'default' }; foo
```
this use is relevant in contexts where multiple parameter sets are used and only some of them should have default values for certain string parameters.
2. Found this example and workaround in an existing issue: https://github.com/PowerShell/PowerShell/issues/4616#issuecomment-405113611

**Comment by vexx32** [comment]
If that's the case, then this issue is also tied to #4312 and would be fixed if that was resolved, according to @mklement0's comment there.
