### ISSUE TITLE
MSIX package name still has "Preview" in it

### ISSUE THREAD

**Issue by saschanaz** [PowerShell/PowerShell#12681]
![image](https://user-images.githubusercontent.com/3396686/82049756-30cacc80-96b7-11ea-9e77-eaac4d41869c.png)

It also appears as "PowerShell Preview" after installation. I think we want to remove the word.

**Comment by xtqqczze** [comment]
The PackageFullName is also `Microsoft.PowerShellPreview_7.0.1.0_x64__8wekyb3d8bbwe`

**Comment by viderme** [comment]
Here, the installed version (7.0.1) of msix has not been replaced by this 7.0.2 msix version. To use 7.0.2, i have to open "PowerShell Preview"

**Comment by SteveL-MSFT** [comment]
Need https://github.com/PowerShell/PowerShell/pull/11991 backported to 7.0 servicing branch.  Once this is fixed, we can then publish stable to Store.

**Comment by saschanaz** [comment]
I don't think this is an issue anymore, probably safe to close.
