### ISSUE TITLE
Cannot install PowerShell-7.0.1-win-x86.msix

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#12688]
When installing `PowerShell-7.0.1-win-x86.msix`:

![](https://i.imgur.com/POIycPN.jpg)

Cannot open app package
Publisher: Microsoft Corporation
Version: 7.0.1.0
This app package is not supported for installation by App Installer because it uses certain restricted capabilities.

However `PowerShell-7.0.1-win-x64.msi` installs perfectly.

**Comment by gabrielweyer** [comment]
According to the [documentation](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7#installing-the-msix-package), you must use the `Add-AppxPackage` cmdlet:

```powershell
Add-AppxPackage PowerShell-7.0.1-win-x64.msix
```

**Comment by superbonaci** [comment]
I just double-click on file...
