### ISSUE TITLE
Feature Request: Write-* cmdlets  - add ANSI color codes to stdout

### ISSUE THREAD

**Issue by mikeTWC1984** [PowerShell/PowerShell#12703]
# Summary of the new feature/enhancement

Main idea is to capture colors from console stdout and convert it to HTML, so tools using it for logging (e.g. jenkins) could produce pretty looking logs. 
Actually error printing is already doing this:
![image](https://user-images.githubusercontent.com/31977106/82155376-8089cf00-9842-11ea-85e3-e2cdc877463e.png)
But Write-* cmdlets output does not contain ansi codes though, so there is no straightforward way to get those colors on html log.

# Proposed technical implementation details (optional)

This could be extra option for OutputFormat e.g.
```
pwsh -of ansi -c "Write-Host 123 -fore green"
```

**Comment by iSazonov** [comment]
Perhaps @daxian-dbw have thoughts about this.

Personally, I would prefer PowerShell to initially do HTML formatting and render this for terminals.

**Comment by mikeTWC1984** [comment]
@iSazonov  that would be even better (is this something on radar?)

**Comment by SeeminglyScience** [comment]
As a workaround you could implement a custom `PSHost` whose `PSHostUserInterface.WriteErrorLine`, `WriteDebugLine`, etc use ANSI.

**Comment by iSazonov** [comment]
> that would be even better (is this something on radar?)

No. It looks weird, but when the whole world invests in web, MSFT invests in a dump teletype. :-)
Although I know that there are GiHub projects of similar web->tty rendering.

**Comment by mikeTWC1984** [comment]
Some more thoughts on this.
turns out many cli tools include color codes only if stdout goes to tty (terminal/emulator). The common pattern to include colors everywhere is to use --color flag. Good example is "ls -la --color". I think that could be good option for pwsh too, at least on nix platforms. There are actually some options to emulate tty on linux, but it might work strange.

Another good feature/solution could be adding ansi coloring as string class extension. E.g.
```powershell
Write-Host "red string on green background".Fg("red").Bg("green")
Write-Host "just red string".Red
```

**Comment by mikeTWC1984** [comment]
Actually the script tool  (tty emulator, linux only but seemed to be in the box on major repos) is quite ok.  The snippet below would do about what I want , although some extra trimming is needed because pwsh generates some weird sequences like "`e="  that  may not be parsed. 
```powershell
script -qec 'pwsh -f ./myscript.ps1' | ansi-to-html
```
