### ISSUE TITLE
Powershell version nags are overly aggressive

### ISSUE THREAD

**Issue by anaisbetts** [PowerShell/PowerShell#12701]
![image](https://user-images.githubusercontent.com/1396/82124459-00853b80-9754-11ea-8779-9dfe77ece23d.png)

Please don't nag users *every time* they open a shell for a *0.0.1* release - if you pop this dialog every time you make the smallest release, and you (as you should!) make many small incremental releases, this will effectively mean that the vast majority of your users are being constantly harassed to upgrade, all the time.

A few solutions:

- Lower the user's time / attention "cost" of upgrading, so that the cost of upgrading is a single "do it" click or copy-paste command (`Upgrade-PowerShell` command maybe?)

- Make the nag proportional to the size of the update - 0.0.1 releases shouldn't get the same real-estate as "Check out PowerShell 8.0!"

- Make the nag only show up once per day instead of every single invocation

**Comment by rjmholt** [comment]
> 0.0.1 releases shouldn't get the same real-estate as "Check out PowerShell 8.0!"

This is interesting, since patch releases often have security patches in them (particularly from .NET). In this sense, patch releases are much more important than major version releases to the people seeing them.

**Comment by rkeithhill** [comment]
You can disable the update check by setting a user or system environment variable called `POWERSHELL_UPDATECHECK` to `0`.

**Comment by rkeithhill** [comment]
> pop this dialog every time you make the smallest release

To put this into perspective, if you were on the stable 6.2.0 release (3/28/2019), and these messages popped up for 6.2.x, you would have gotten 5 notifications in the past ~15 months.  That's an average about one upgrade notification every 3 months.

**Comment by rjmholt** [comment]
> Make the nag only show up once per day instead of every single invocation

Yeah I thought we already did this. /cc @daxian-dbw @SteveL-MSFT 

> so that the cost of upgrading is a single "do it" click or copy-paste command (Upgrade-PowerShell command maybe?)

I think we all want that, but it's currently not easy to solve. Unfortunately I don't know enough about the issues at play to conjecture (@joeyaiello might). On macOS and Linux package managers are how we resolve this. On Windows, MSIX installations in the Store also resolve this. But MSI and zip installations have no package management concept. The diversity of installation vectors certainly makes an `Update-PowerShell` command more complex. I believe there is a will for a solution here though.

**Comment by iSazonov** [comment]
> Yeah I thought we already did this

We have a code only for delaying the check in network. (See `CheckForUpdates()` method.)

>  The diversity of installation vectors certainly makes an Update-PowerShell command more complex.

Interesting, how does VS Code implement this?

**Comment by rjmholt** [comment]
> how does VS Code implement this?

Ah that's a good question. It basically presumes you installed with the MSI. On macOS and Linux it just reminds you; it won't try and run a package manager update for you

**Comment by vexx32** [comment]
> On macOS and Linux it just reminds you; it won't try and run a package manager update for you.

On my Mac, it will happily go off and run Homebrew to do the update for me, in my experience. 🙂

**Comment by iSazonov** [comment]
So VS Code knows how it was installed.

> And detecting how you installed after installation is the hard part

We could add a resource per package type. This could be an empty file in home folder.
It would be great UX for personal installations but for Enterprises this should be disabled.

**Comment by rjmholt** [comment]
> > On macOS and Linux it just reminds you; it won't try and run a package manager update for you.
> 
> 
> 
> On my Mac, it will happily go off and run Homebrew to do the update for me, in my experience. 🙂 

Oh! You’re quite right. Not sure about Linux, since root is needed.

**Comment by xtqqczze** [comment]
IMO the version update notification should not appear until at least 24 hours after release.

**Comment by marcusl** [comment]
If it's contains a security fix, the notification should mention that.

Currently it looks like "hey, we fixed a typo! check it out."

**Comment by nzain** [comment]
Imho, simplifying upgrades (regardless of OS and the installation source) is important.

Maybe it would be sufficient to help people create their own upgrade script? I know there is an `Install-Powershell.ps1` at https://aka.ms/install-powershell.ps1 but it did not upgrade my installation, just unzip the latest package into `%appdata%\Microsoft\powershell`. Maybe it is easier to create a dedicated website with upgrade strategies (and scripts) for each type of install.

**Comment by SteveL-MSFT** [comment]
The bar for servicing updates is high.  We don't take trivial fixes to avoid risk of regression.  There should only be fixes that are security, compliance, or customer blocking issues.  This [RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/5-Final/RFC0052-Notification-On-Version-Update.md) describes the intent and design in detail and ways to disable.

Auto-update is something I would love to have, but is very difficult to solve whether because it requires root or due to open file handles (and requiring elevation) on Windows.

**Comment by xtqqczze** [comment]
It would be good if we could ensure a new [Chocolatey package](https://chocolatey.org/packages/powershell-core) is available before the version nag appears. I previously suggested we could delay the notification by 24 hours to allow for this.

Ideally we would have automatic Chocolatey releases from a pipeline (#12673). /cc @DarwinJS

**Comment by anaisbetts** [comment]
> The bar for servicing updates is high. We don't take trivial fixes to avoid risk of regression. There should only be fixes that are security, compliance, or customer blocking issues. This RFC describes the intent and design in detail and ways to disable.

This is useful to know, but users don't understand that because it's very much contrary to how most software treats version numbers - nobody sees an 0.0.1 increase and thinks "Wow, I should definitely get that, it's almost certainly security related!!!"

If this is the case, PowerShell needs to call out security updates differently than "We added new stuff" releases, and do things to educate users about how PowerShell uses version numbers Differently than most projects

**Comment by vexx32** [comment]
PowerShell uses version numbers according to the widely established and commonly recognised [semver](https://semver.org/) aka Semantic Versioning.

It's not uncommon by any stretch of the imagination, though its use in the Windows / Microsoft ecosystem is pretty rare.

**Comment by SidShetye** [comment]
Is there any way to disable the nags? Also, IMHO, the upgrades should be coming through windows update.

**Comment by vexx32** [comment]
Pwsh is not (yet) a Windows component, so will not be updated via Windows update until that changes. The support lifecycle is currently also vastly different to Windows' own.

As for disabling them, one option is to start pwsh with the `-NoLogo` parameter.

**Comment by doctordns** [comment]
> Is there any way to disable the nags? Also, IMHO, the upgrades should be coming through windows update.

Updates via Windows Update would be great, but that is not going to come any time soon. 

In the meantime, what is the problem with having an option in the configuration.json file to tell PWSH NOT to check for new versions?

**Comment by sysopsdev** [comment]
Can someone please demonstrate how to **PERMANENTLY** disable this? 

```
[System.Environment]::SetEnvironmentVariable("POWERSHELL_UPDATECHECK", 0)
```

This did not work. Nor did

`$Env:POWERSHELL_UPDATECHECK = 0`
`$Env:POWERSHELL_UPDATECHECK = 'Off'

It is continuously popping up. With the colorscheme I have set it's most unpleasant to look at. I know devs tend to complain about frivolous garbage, and I'm not even asking you to change it. I just want to know how to disable this permanently. The solutions above are not working.

**Comment by vexx32** [comment]
You need to set it either in the current user or machine scope. By default the SetEnvironmentVariable method only sets the variable in the current process.

```ps1
[Environment]::SetEnvironmentVariableTarget("POWERSHELL_UPDATECHECK", 0, 'User')
```

**Comment by sysopsdev** [comment]
> 
> 
> You need to set it either in the current user or machine scope. By default the SetEnvironmentVariable method only sets the variable in the current process.
> 
> ```powershell
> [Environment]::SetEnvironmentVariableTarget("POWERSHELL_UPDATECHECK", 0, 'User') # or 'Machine' for all users
> ```

Thank you! ✌

**Comment by daxian-dbw** [comment]
> what is the problem with having an option in the configuration.json file to tell PWSH NOT to check for new versions?

You won't want powershell to parse the config file at the startup time, given that we already have perf issue in startup.
As @vexx32 [showed above](https://github.com/PowerShell/PowerShell/issues/12701#issuecomment-659658336), you can set the environment variable `POWERSHELL_UPDATECHECK` to `0` at either the current user or machine scope to disable the update notification.

**Comment by doctordns** [comment]
> > what is the problem with having an option in the configuration.json file to tell PWSH NOT to check for new versions?
> 
> You won't want powershell to parse the config file at the startup time, given that we already have perf issue in startup.
> As @vexx32 [showed above](https://github.com/PowerShell/PowerShell/issues/12701#issuecomment-659658336), you can set the environment variable `POWERSHELL_UPDATECHECK` to `0` at either the current user or machine scope to disable the update notification.

Given that the json file us already loaded and parsed, would there really be that much overhead involved vs reading an Environment variable?  I would prefer to see more in json and less in environments variables.

**Comment by daxian-dbw** [comment]
Today, there is no `powershell.config.json` file ship with PowerShell by default for Linux and macOS. On Windows, it's unfortunate that we have a default config json file that contains `WindowsPowerShellCompatibilityModuleDenyList` and `ExecutionPolicy`, but both defaults potentially can be moved to code to avoid having a default config json file at all.

**Comment by Jack-Works** [comment]
Please at least make the message smaller, for example, 1 line only message
