### ISSUE TITLE
WARNING: Unable to find module repositories.

### ISSUE THREAD

**Issue by ALarBL** [PowerShell/PowerShell#12709]
Good day all,

I´m having an issue while I try to install the Module "MicrosoftPowerBIMgmt", it states t

`
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'MicrosoftPowerBIMgmt'. Try Get-PSRepository to see all 
available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
`

Then i run the command "Get-PSRepository" and i get the below message.

`PS C:\WINDOWS\system32> Get-PSRepository
WARNING: Unable to find module repositories.`

I´ve been troubleshooting the whole morning and am not sure on where to go from here. Any help on where to go from here is greatly appreciated!

I´ve attached the full error message
![PowerBIMgmt Issue](https://user-images.githubusercontent.com/65543787/82210524-2737a380-9907-11ea-9800-331b58efd7ad.JPG)

**Comment by iSazonov** [comment]
@ALarBL The repository is only for PowerShell Core developers. 
You need to discuss your issue on a forum.

**Comment by vexx32** [comment]
@ALarBL drop by the PowerShell [Slack](https://aka.ms/psslack)/[Discord](https://aka.ms/psdiscord) channels and I'm sure some folks can help you troubleshoot. 🙂
