### ISSUE TITLE
Make it possible to create files w/  LF using cmdlets like `Out-File` even in Windows

### ISSUE THREAD

**Issue by tats-u** [PowerShell/PowerShell#12712]
# Summary of the new feature/enhancement

You may want to create files with the newline LF in Windows.  It is inconvenient to create such files by PowerShell in Windows.  You have to run the following to do so:

```pwsh
[IO.File]::WriteAllText("$PWD\foo.txt", $ContentLines -join "`n")
```

This looks ugly.  It would be nice if `Out-File` of PowerShell supports the LF newline as it supported UTF-8 without BOM.

# Proposed technical implementation details (optional)

I'd like the following syntax for creating UTF-8 (w/o BOM) + LF files.

```pwsh
Out-File foo.txt -Encoding utf8NoBOM -Newline LF
```

I wish this proposed option `-Newline` takes one of the values `CRLF`, `LF`, and `Native` (or `Auto`).

P.S. `Tee-Object` may also requires this option.

**Comment by tats-u** [comment]
- `Out-File` is implemented in https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
- An argument named `Newline` should be appended in `PathUtils.MasterStreamOpen` in https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/PathUtils.cs

**Comment by iSazonov** [comment]
Dup #3855. Please continue discussion there.

**Comment by tats-u** [comment]
I see.  We may want to use other characters than LF or CRLF to separate lines.
