### ISSUE TITLE
remove `assets\license.rtf`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#12719]
`assets\license.rtf` is outdated as it refers to 'PowerShell 6'.

Since #8846, we do not show an EULA in the MSI, so we should remove `license.rtf`.

@TravisEz13 appears to be in favour of removing RTF generation: https://github.com/PowerShell/PowerShell/issues/8704#issuecomment-461667561

**Comment by iSazonov** [comment]
I agree.

**Comment by xtqqczze** [comment]
EULA was added by @raghushantha in b6b95c4d634aaaef35ab820093c284484fd04c7b.

I will create PR to remove.
