### ISSUE TITLE
New-PSDrive does not create mapped network drives.

### ISSUE THREAD

**Issue by BusinessDataCoach** [PowerShell/PowerShell#12710]
I am trying to map network drives to local machine drives, and my current code creates the connection in PowerShell but the mapped drive does not show up in File Explorer. As I am able to inspect the content of the mapped drive in PowerShell I am confident that this is not a credentials problem. The code does execute and create the requested drive. It is however not showing up in File Explorer and all the tips I have found to resolve the problem do not solve the problem for me.

# Steps to reproduce

```powershell
$username = "localhost\Steven"
$password = Get-Content 'C:\Users\StevenDeLandtsheer\AQSynol.txt' | ConvertTo-SecureString
$cred = New-Object -typename System.Management.Automation.PSCredential -argumentlist ($username, $password)
. New-PSDrive -Name "Z" -PSProvider FileSystem -Root "\\10.0.0.7\Bedrijf" -Scope global -Persist -Credential $cred
```
I have found similar issues but none have provided me a clue on what might go wrong here or how to pinpoint the root cause of the problem.

# Expected behavior
According to the documentation a persistent locally mapped drive should be created, but that does not happen. The documentation indicates that the Persist will not work if the command is scoped locally. Therefore I used the -Scope global parameter, but this has not solved the issue.

```none

```

# Actual behavior
Executing the commands (administrative mode) results in a confirmation of the mapped drive in PowerShell
```none
Name           Used (GB)     Free (GB) Provider      Root                                                                     CurrentLocation
----           ---------     --------- --------      ----                                                                     ---------------
Z                2451,86       4693,27 FileSystem    \\10.0.0.7\Bedrijf
```

# Environment data
I have also set the ExecutionPolicy for both CurrentUser and LocalMachine to RemoteSigned.

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned
```

**Comment by iSazonov** [comment]
PSDrive is not OS drive. It is created per runspace and lives only in PowerShell.

**Comment by iSazonov** [comment]
I see such drive in Explorer under `Network Locations` below `Devices and Drives`.

**Comment by BusinessDataCoach** [comment]
The problem I have is that I would like to create stable mapped drives on my computer. I can do this in explorer by mapping those drives (to a Synology device) but as this device is not in a domain I use the Synology account to make the mapping. That works, but each time I start my machine I need to provide the (Synology account) password again. To avoid this I wanted to use this script to automate the login process.
The script I wrote does this within the PowerShell environment, but not on the level of the OS, although the documentation clearly states this is possible. So what is wrong in my approach or what could I do to pinpoint the root cause of the failure?

**Comment by BusinessDataCoach** [comment]
I checked and the script did not the drive in the Network Locations. The Synology NAS device is there, but not the intended mapped drive.

**Comment by mklement0** [comment]
You mention "administrative mode"; please note that an elevated process has separate drive mappings from a non-elevated one, even for the same account. To put it differently: a drive mapped in an elevated (run-as-admin) session won't be seen when the same user runs non-elevated - this behavior applies at the system level, and PowerShell has no control over it.

**Comment by BusinessDataCoach** [comment]
Thanks for the last comment!
The root cause of the problem was indeed that I was running this script in PowerShell administrative mode. As soon as I ran the exact same script as  a non-elevated process the drive mappings were visible and functioning perfectly.
