### ISSUE TITLE
DSC Core and on-prem pull server

### ISSUE THREAD

**Issue by steskalja** [PowerShell/PowerShell#12724]
Has there been any official update or plan for DSC Core and on-prem pull servers now that Powershell v7 is out? Many people have on-prem requirements and cannot use Azure DSC.

**Comment by gaelcolas** [comment]
Yes, a few announcements have been made, but nothing that directly translates in a new 'CORE' LCM that would directly replace 5.1.
PS Team 2021 investments Blog post: https://devblogs.microsoft.com/powershell/powershell-team-2021-investments/#dsc-for-powershell-7
About PS investments in DSC (a little old): https://www.youtube.com/watch?v=toTwph350zY&ab_channel=DSCCommunity
Azure Policy Guest Configuration and Azure Arc (on prem with Azure Control Plane): https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration

Azure Policy Guest Configuration (and through Azure Arc) supports PS Core DSC resources cross platform.
That means you can audit your linux vm running on your vmware servers and report it into your Azure Data plane.

Hope that answers the question.

**Comment by steskalja** [comment]
> Yes, a few announcements have been made, but nothing that directly translates in a new 'CORE' LCM that would directly replace 5.1.
> PS Team 2021 investments Blog post: https://devblogs.microsoft.com/powershell/powershell-team-2021-investments/#dsc-for-powershell-7
> About PS investments in DSC (a little old): https://www.youtube.com/watch?v=toTwph350zY&ab_channel=DSCCommunity
> Azure Policy Guest Configuration and Azure Arc (on prem with Azure Control Plane): https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration
> 
> Azure Policy Guest Configuration (and through Azure Arc) supports PS Core DSC resources cross platform.
> That means you can audit your linux vm running on your vmware servers and report it into your Azure Data plane.
> 
> Hope that answers the question.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e68e34fec82df597ef2257f5c1caf66389261e928d626d20543a46464430cf65/68747470733a2f2f646576626c6f67732e6d6963726f736f66742e636f6d2f706f7765727368656c6c2f77702d636f6e74656e742f75706c6f6164732f73697465732f33302f323031382f30392f506f7765727368656c6c5f3235362e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/51145e85e7e07991fb2b235b9306ab50d9e4843dd1c5dc1bed7f3b5821707a53/68747470733a2f2f646576626c6f67732e6d6963726f736f66742e636f6d2f706f7765727368656c6c2f77702d636f6e74656e742f75706c6f6164732f73697465732f33302f323031392f30322f506f7765727368656c6c5f323536312e706e67"> PowerShell Team**[PowerShell Team 2021 Investments | PowerShell Team](https://devblogs.microsoft.com/powershell/powershell-team-2021-investments/)**PowerShell Team 2021 Investments The PowerShell Team plans engineering work per semester (6 months at a time). However, PowerShell itself follows the .NET schedule of release every year. In this blog post, we’ll cover the year long plan for PowerShell 7.2 as well as tooling and modules work we have planned for the next semester.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/0f67595c301739c467733e670e036897181dae5cea0e9d7f7fa2f3f4a79a5fba/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f656e2d75732f6d656469612f6c6f676f732f6c6f676f2d6d732d736f6369616c2e706e67">**[Learn to audit the contents of virtual machines - Azure Policy](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/guest-configuration)**Learn how Azure Policy uses the Guest Configuration client to audit settings inside virtual machines.

This doesn't replace or update On-Prem DSC. There are many times when you cannot connect to the internet to use Azure DSC

**Comment by gaelcolas** [comment]
I'm not saying it replaces what you can do with 5.1, just pointing to the latest _official update and plan_.

If it's not in there, it's not in the plan.
I agree that's a pain as many would like to see one, myself included.

**Comment by ThomasNieto** [comment]
@steskalja you can see the latest plan here: [PowerShell Blog](https://devblogs.microsoft.com/powershell/desired-state-configuration-dsc-planning-update/)

@StevenBucher98 this issue can be closed.
