### ISSUE TITLE
Powershell doesn't list all installed monospace fonts

### ISSUE THREAD

**Issue by JoeUX** [PowerShell/PowerShell#12720]
Powershell 7.0.0 and 7.0.1 don't list all installed monospace fonts. In particular, they don't list [Roboto Mono](https://github.com/google/fonts/tree/master/apache/robotomono), my preferred font. Screenshot and system details below.

The Powershell font settings are in the Defaults and Properties menus. Same issue in both.

The installed Roboto Mono font file is a .ttf, and it's version 2.002 of that font (the latest).

![Powershell 7](https://user-images.githubusercontent.com/8071692/82314320-7b319f00-997e-11ea-81bd-22a8c0d70fe6.JPG)

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
Do you see the same for Windows PowerShell window? For cmd.exe?

**Comment by JoeUX** [comment]
Yes, I see the same problem in Windows Powershell and cmd.exe.

**Comment by iSazonov** [comment]
The problem is not in the applications.

Perhaps @DHowett could add more info.

**Comment by vexx32** [comment]
If anything this would be an OS issue rather than a PowerShell issue. PowerShell has **zero** control over what the OS chooses to show in that menu. From what I recall, fonts shown in that menu may require some changes to the registry.

There's a good walkthrough of how to go about that here: https://www.maketecheasier.com/add-custom-fonts-command-prompt-windows10/

**Comment by JoeUX** [comment]
@vexx32 FYI, there are at least three applications that correctly show all the monospaced fonts, including Roboto Mono:

1. Windows Terminal (from Microsoft; it's a Microsoft Store / UWP app, possibly still a Preview)
2. Sublime Text
3. UltraEdit

So applications seem to have some control over it, though I'm not sure how they interface with the relevant APIs.

With Windows Terminal, I just edited their settings.json file to specify Roboto Mono. For the two editors, Roboto Mono shows up in their font selector UI.

**Comment by vexx32** [comment]
Yep. Applications not using Windows' own conhost can handle fonts however they like... but as far as I'm aware, using conhost means you essentially have to take what you're given when it comes to fonts. Windows Terminal uses conpty (a newer implementation that IIRC is also developed by the Windows Terminal team) rather than the older conhost.

PowerShell operates _within_ a terminal rather than being a terminal in and of itself... so it's beholden to whatever rules the terminal itself sets in terms of fonts etc.

**Comment by DHowett** [comment]
![image](https://user-images.githubusercontent.com/189190/82392649-457dcc00-99f9-11ea-8772-17400ddf285a.png)

**Comment by DHowett** [comment]
Conhost has very specific rules for what fonts it presents, and we are not likely to change those rules. Sorry!

**Comment by SeeminglyScience** [comment]
Note that some of the fonts that don't show up can still be used if manually set.  I use this in my profile to set the font to `FuraCode NF` from nerd fonts:

https://github.com/SeeminglyScience/dotfiles/blob/c4fa75ceddbdb5d9b6d16b90428969cc1c37fbe7/PowerShell/SetConsoleFont.ps1

**Comment by JoeUX** [comment]
@SeeminglyScience Thanks, how do I run that? Do I just invoke that .ps1 file on the command line?

**Comment by SeeminglyScience** [comment]
Yeah, here's where I call it in my profile.ps1

https://github.com/SeeminglyScience/dotfiles/blob/c4fa75ceddbdb5d9b6d16b90428969cc1c37fbe7/PowerShell/profile.ps1#L84

**Comment by JoeUX** [comment]
@SeeminglyScience Oh, okay, I'm not familiar with profile.ps1 files. Are they comprehensive settings for Powershell? I'm glad there's a way to set up any font.

**Comment by vexx32** [comment]
It's essentially just a script that gets run whenever you start PowerShell.

You can call `$profile` in your PowerShell console to see the path it'll be looking for, and create or edit the file at that location to add anything you need available in your typical powershell sessions 🙂

**Comment by athompson-merlin** [comment]
I have to agree - these fonts, as-is, are nearly useless on Windows.  Only those very few applications that have a convenient configuration file AND are willing to use variable-pitch fonts (iow: VS Code and very little else) can use Monaspace; everything else doesn't recognize it as a valid monospace font.

The PANOSE "Proportion" field in all the fonts is currently unset (or set to "Any", same net effect) whereas it needs to be set to "Monospace" to be visible in most editors/terminal emulators.

I'm unsure how to change this in the Monaspace build, but in FontForge at least, the setting can be found at Element->Font Info->OS/2->Panose->Proportion.  I'm just not willing to manually edit 100+ files...
