### ISSUE TITLE
"Get-ChildItem -Filter" is much slower in PowerShell 7 than in Windows PowerShell 5.1

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#12745]
Running

````
Get-ChildItem -LiteralPath <somedir> -Filter 'wontmatchanything*.txt'
````

(especially when the filter excludes all/most files) is **much** slower in PowerShell 7 than in Windows PowerShell 5.1:

![image](https://user-images.githubusercontent.com/12860484/82532925-91885800-9b42-11ea-98b4-e5aac4aefa07.png)

Digging _seems_ to reveal that the .NET Core API (invoked from PowerShell) would be the culprit, but I was unable to repro using raw C#:

![image](https://user-images.githubusercontent.com/12860484/82533031-cac0c800-9b42-11ea-9ffd-1aabefcccde6.png)

# Steps to reproduce

- Extract the test harness from [TestHarness.zip](https://github.com/PowerShell/PowerShell/files/4661326/TestHarness.zip)
- edit the `locations.json` file to define the location of one or more test directories
- populate the directories by running `Populate.ps1`
- optionally, add/remove/change testcases by editing the `testcases.json` file
- run `RunTestCampaign.ps1`

Results are output to `results.csv`.

# Expected behavior

The performance of PowerShell 7 should be higher than Windows PowerShell 5.1, or at least on par with Windows PowerShell 5.1

# Actual behavior

PowerShell 7 is way slower

# Environment data

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Yellow lines on second screenshot shows that it is .Net Core issue.

You could enhance your tests using `enumerationOptions` parameter in `EnumerateFiles(string path, string searchPattern, System.IO.Enume
rationOptions enumerationOptions)`

**Comment by sba923** [comment]
That was also my line of thinking. But I wrote a [C# program](https://github.com/PowerShell/PowerShell/files/4666679/EnumerateFilesPerf.zip) and couldn't show that difference between .NET Framework and .NET Core. Something wrong in that C# repro attempt?

What `enumerationOptions` would you suggest trying?

**Comment by iSazonov** [comment]
You could play with MatchType.

As for C#, you should measure with PerfView to see all call stack. Perhaps PowerShell force antivirus API.

**Comment by sba923** [comment]
`EnumerateFiles(String, String, EnumerationOptions)` is not supported under .NET Framework, so there's not much I can compare there.

I'm not sure I understand what you want me to profile.

The PowerShell test harness clearly reveals a performance difference between 5.1 and 7.0.

I can't repro a similar performance difference when calling `EnumerateFiles(String, String)` in .NET Framework 4.8 and .NET Core 3.1.

Maybe I could try using WPR on the PowerShell tests?

**Comment by sba923** [comment]
If you send me a private message, I can share the WPR capture off my OneDrive.
