### ISSUE TITLE
Can't not import PSScheduledJob module 

### ISSUE THREAD

**Issue by t105362506** [PowerShell/PowerShell#12743]
import this module "Import-Module PSScheduledJob" & get this error message

i don't know how to fix this error

Error message: Import-Module: Module 'PSScheduledJob' is blocked from loading using Windows PowerShell compatibility feature by a 'WindowsPowerShellCompatibilityModuleDenyList' setting in PowerShell configuration file.

**Comment by iSazonov** [comment]
PSScheduledJob module that is not PS-Core compatible and was explicitly blocked.

**Comment by t105362506** [comment]
But i need use ScheduledJob  and this error message told me run "Import-Module PSScheduledJob"


ErrorMessage: Get-ScheduledJob: The 'Get-ScheduledJob' command was found in the module 'PSScheduledJob', but the module could not be loaded. For more information, run 'Import-Module PSScheduledJob'.

**Comment by iSazonov** [comment]
Today we can use ScheduledJob only with Windows PowerShell.

**Comment by t105362506** [comment]
but  before can  run Scheduled in  powershell vscode  , so now we can't use this module in the vs code ?

 
---------------------------------------

This is another vm , i can't start powershell have any idea?

![image](https://user-images.githubusercontent.com/54572002/82531202-72ed8580-9b71-11ea-82a4-ef710bda555d.png)

**Comment by doctordns** [comment]
The cmdlets in that module do not work with Powershell 7 either natively or via the Win32compat mechanism. Your only option is to run them with Windows PowerShell.

**Comment by iSazonov** [comment]
You could ask Windows team using Windows 10 feedback tool or UserVoice site.
