### ISSUE TITLE
Add PWSH to Win+X toolbar

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#12747]
# Summary of the new feature/enhancement
On install of Pwsh it should be possible to add pwsh to the Win+X toolbar via a checkbox

**Comment by doctordns** [comment]
It is already there

![2020-05-21_17-36-42](https://user-images.githubusercontent.com/3630329/82582555-2c585500-9b8a-11ea-8694-82e349369ff5.png)

**Comment by thlac** [comment]
That's not really an issue for the PowerShell team. Correct me if wrong, but it's definitely on "the radar", main obstacle is getting PowerShell to have the same support cadence as .Net 5/Windows which seems to be what's happening with 7.1 right now.

**Comment by china-live** [comment]
Need this

**Comment by iSazonov** [comment]
What is public API to manage the bar?

**Comment by kilasuit** [comment]
@SteveL-MSFT can this be looked at for the 7.1 release

**Comment by iSazonov** [comment]
@heaths Is it possible to customize Win-X menu for "all users" in msi?

**Comment by heaths** [comment]
I have no idea. I always assumed that menu is controlled solely by Windows. For example, the only way I know to switch between powershell.exe and cmd.exe is through a first-party Settings (nee Control Panel) application. There's certainly nothing documented in shell extensibility docs I've ever seen.

**Comment by iSazonov** [comment]
Elements of Win-X menu is in %LocalAppdata%\Microsoft\Windows\WinX user folder. I don't know if there is a computer-wide folder.

**Comment by heaths** [comment]
Finding where that stuff lives != changing it being supported. For a project with the scope of PowerShell, it might be good if @SteveL-MSFT talks with Windows devs first if that's supported. For example, in my 20+ years of Windows Installer, I know a lot about their registry keys (and more), but tweaking them - especially if you're not very careful - causing bad, unsupported behavior.
