### ISSUE TITLE
Powershell 7.0.0 is Super-Glued to My System

### ISSUE THREAD

**Issue by sc0ttwad3** [PowerShell/PowerShell#12753]
I've tried to remove **Powershell 7.0.0** many, many times from my currently running Windows 10 Insider Build 19268 laptop, but it refuses to go. I've tried to upgrade with many of the 7.1.0-previews, or install _any_ other version—with no luck—all the .msi installers fail to uninstall Powershell 7.0.0 at the same point:

It's demanding **obxu42qf.vob.msi** and will not budge. That file is unknown to me and I certainly don't have it. I fully scrubbed my drives and it's nowhere. I suspect it was a transient that slept in the temp folder until it was asked to leave.

The first method was the most direct, I thought, by using **Invoke-Expression** with the install script hosted at Microsoft, but I ran into the couldn't find the *_.vob.msi_ file. Next was to uninstall using _Apps and Features...Uninstall_, and always the same stopping point. Since then it's been trying all the various ways I could come up with, and now I'm out of ideas

**So I'm looking for ways to create a substitute for the missing _.vob.msi_ file, or any method that doesn't involve blindly hacking away in the RegEdit Forest—to make it past an original install temporary _.vob.msi_ file that no longer exists in my universe.**

![image](https://user-images.githubusercontent.com/1682691/82622303-6d149600-9bab-11ea-94f4-1bc463b5b38b.png)

**Comment by thlac** [comment]
In my experience that is typically caused by an issue with the MSI Cache. I believe their [troubleshooter tool](https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) should be able to fix the specific issue you're having.

**Comment by he852100** [comment]
You deleted obxu42qf.vob.msi。
 Find the same version of the installation package and reinstall

**Comment by sc0ttwad3** [comment]
@thlac Can't believe I've never run across that particular official Install/Uninstall troubleshooter. That took care of it. Thx!

@he852100 That was my first course of action, but could never find a preview version that worked. After running the troubleshooter and getting past the corrupted state to something I could work with, I tracked obxu42qf.vob.msi down to 7.0.0.6.
