### ISSUE TITLE
The console in the remote desktop fails

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12751]
Do not receive any input
# Steps to reproduce

```powershell
123456
```

# Expected behavior

```none
123456
```

# Actual behavior

```none
Null 
```

# Environment data

```none
win 7.0.1
system server1909
```

**Comment by vexx32** [comment]
Please provide a more thorough issue description and reproduction steps.

**Comment by he852100** [comment]
![20200522_151356](https://user-images.githubusercontent.com/26913892/82641560-1c4e7d00-9c3f-11ea-8d0f-d957ddc6782c.gif)

**Comment by he852100** [comment]
Not compatible with rdp10

**Comment by brogdonm** [comment]
> Not compatible with rdp10

I am seeing the same thing. I have a Windows 10 box, with `pwsh v7.0.1` installed. If I use `Remote Desktop 10.3.11` on MacOS 10.15.4 to remote into the Windows 10 machine and do:

* WIN+R
* `pwsh` and enter

If I type nothing shows up in the window. I can hit the `<enter>` key and it will do a newline. 

But if I open `cmd.exe` or the older `powershell.exe` then the keyboard works fine.

**Comment by brogdonm** [comment]
> Please provide a more thorough issue description and reproduction steps.

@vexx32 I'm pretty sure I see the same thing @he852100 mentions.

**Comment by jbyway** [comment]
Seems to be reproducible in a Win10 session when connecting via HTML5 client to a remote Windows Virtual Desktop session. 

Using the Windows Virtual Desktop Windows client pwsh v7.0.1 can receive inputs normally but when using the HTML5 client it fails to pass any input outside of CTRL-V or Enter

**Comment by ferdnyc** [comment]
I'm using Remmina (Linux remote-session client) to a Windows 10 Pro 21H2 system via its RDP plugin (HTTP transport), and exactly the same. Input works to any other program without issue. 

Running `pwsh.exe` (version 7.2.1), either in a newly-launched Windows Terminal window, or by executing it from the command prompt of an existing `cmd.exe` session, results in no response to any of the normally-echoed basic ASCII command line characters.

The <kbd>Enter</kbd> key works, <kbd>Ctrl</kbd> combinations seem to work, keyboard paste via <kbd>Shift</kbd>+<kbd>Insert</kbd>works, <kbd>PgUp</kbd>/<kbd>PgDn</kbd> work... it's just the shell prompt itself that seems to be ignoring most attempts to communicate with it.

Pasting in a command line and typing <kbd>Enter</kbd> **DOES** execute the pasted command, if that's any help.

**Comment by ferdnyc** [comment]
> Running `pwsh.exe` (version 7.2.1), either in a newly-launched Windows Terminal window

Sorry, not Windows Terminal. That runs Windows PowerShell, and encourages me to upgrade to PowerShell 6. PowerShell _7_ executes under the Console Window Host.

**Comment by ferdnyc** [comment]
Unfortunately, no changes following the 7.2.2 update. 😞

**Comment by nentibusarchitectura** [comment]
I'm experiencing a similar problem on a brand new install of Windows Server 2022 21H2, I can type anywhere on notepad, cmd.exe, however as soon as I type: "powershell" and powershell is running I can't type on the window, same if I start powershell on its own. In my case I'm accessing the Win2022 instance via another Windows 2019 server acting as a bastion. So The full chain is Linux/Remmina->Windows Server 2019->Windows Server 2022.

Hope this helps.

**Comment by nentibusarchitectura** [comment]
And even more bizarre, if I run an interactive powershell script the powershell console (running powershell via cmd.exe) accepts input normally as soon as the script ends the console stops accepting input.

**Comment by barrybingo** [comment]
I had this issue and fixed it via a Remmina preference change.

Remmina Preferences -> RDP -> untick "use client keyboard mapping"

Also have confirmed that re-ticking the option causes the problem to come back

**Comment by ngcdev** [comment]
I was experiencing the same issue. The fix suggested by @barrybingo above fixed it for me. Thanks!

> I had this issue and fixed it via a Remmina preference change.
> 
> Remmina Preferences -> RDP -> untick "use client keyboard mapping"
> 
> Also have confirmed that re-ticking the option causes the problem to come back

**Comment by ferdnyc** [comment]
@barrybingo @ngcdev 

Huh — holy crap, that _does_ work. Nice find, thanks @barrybingo. Fascinating that should be the issue, especially since it's a _systemwide_ preference and not a per-connection thing.

I looked at the Remmina code to see _why_ it would make a difference.

When that option is enabled in the RDP preferences, the RDP plugin's code translates _certain_ keypresses (ones that aren't modifiers, spaces, function keys, numpad keys, or any key combined with a modifier) into unicode code points, instead of into raw keycodes:

[Remmina/plugins/rdp/rdp_event.c@763:809](https://gitlab.com/Remmina/Remmina/-/blob/master/plugins/rdp/rdp_event.c#L763-809):
```c
		if (!rfi->use_client_keymap) {
			hardware_keycode = event->hardware_keycode;
			if (rfi->keymap) {
				for (ik = 0; ik < rfi->keymap->len; ik++) {
					kep = &g_array_index(rfi->keymap, RemminaPluginRdpKeymapEntry, ik);
					if (hardware_keycode == kep->orig_keycode) {
						hardware_keycode = kep->translated_keycode;
						break;
					}
				}
			}
			scancode = freerdp_keyboard_get_rdp_scancode_from_x11_keycode(hardware_keycode);
			if (scancode) {
				rdp_event.key_event.key_code = scancode & 0xFF;
				rdp_event.key_event.extended = scancode & 0x100;
				remmina_rdp_event_event_push(gp, &rdp_event);
				keypress_list_add(gp, rdp_event);
			}
		} else {
			unicode_keyval = gdk_keyval_to_unicode(event->keyval);
			/* Decide when whe should send a keycode or a Unicode character.
			 * - All non char keys (Shift, Alt, Super) should be sent as keycode
			 * - Space should be sent as keycode (see issue #1364)
			 * - All special keys (F1-F10, numeric pad, Home/End/Arrows/PgUp/PgDn/Insert/Delete) keycode
			 * - All key pressed while Ctrl or Alt or Super is down are not decoded by gdk_keyval_to_unicode(), so send it as keycode
			 * - All keycodes not translatable to unicode chars, as keycode
			 * - The rest as Unicode char
			 */
			if (event->keyval >= 0xfe00 ||                                                  // Arrows, Shift, Alt, Fn, num keypad…
			    event->hardware_keycode == 0x41 ||                                          // Spacebar
			    unicode_keyval == 0 ||                                                      // Impossible to translate
			    (event->state & (GDK_MOD1_MASK | GDK_CONTROL_MASK | GDK_SUPER_MASK)) != 0   // A modifier not recognized by gdk_keyval_to_unicode()
			    ) {
				scancode = freerdp_keyboard_get_rdp_scancode_from_x11_keycode(event->hardware_keycode);
				rdp_event.key_event.key_code = scancode & 0xFF;
				rdp_event.key_event.extended = scancode & 0x100;
				if (rdp_event.key_event.key_code) {
					remmina_rdp_event_event_push(gp, &rdp_event);
					keypress_list_add(gp, rdp_event);
				}
			} else {
				rdp_event.type = REMMINA_RDP_EVENT_TYPE_SCANCODE_UNICODE;
				rdp_event.key_event.unicode_code = unicode_keyval;
				rdp_event.key_event.extended = False;
				remmina_rdp_event_event_push(gp, &rdp_event);
				keypress_list_add(gp, rdp_event);
			}
```

When a keyboard event of type `REMMINA_RDP_EVENT_TYPE_SCANCODE_UNICODE` is processed, it's delivered to the remote server using the RDP message [`TS_UNICODE_KEYBOARD_EVENT`](https://msdn.microsoft.com/en-us/library/cc240585.aspx).

[Remmina/plugins/rdp/rdp_plugin.c@228-234](https://gitlab.com/Remmina/Remmina/-/blob/master/plugins/rdp/rdp_plugin.c#L228-234):
```c
		case REMMINA_RDP_EVENT_TYPE_SCANCODE_UNICODE:
			/*
			 * TS_UNICODE_KEYBOARD_EVENT RDP message, see https://msdn.microsoft.com/en-us/library/cc240585.aspx
			 */
			flags = event->key_event.up ? KBD_FLAGS_RELEASE : KBD_FLAGS_DOWN;
			input->UnicodeKeyboardEvent(input, flags, event->key_event.unicode_code);
			break;
```

Apparently, presumably due to its own fairly low-level keyboard processing, Unicode input events aren't properly handled by PowerShell 7.

**Comment by tovoro** [comment]
For people having this problem with Microsoft Remote Desktop for Mac, switching Keyboard Mode solves it! 
<img width="450" alt="grafik" src="https://user-images.githubusercontent.com/54395768/194088949-2bcd3363-4559-4b88-a9e8-60ca8a998f56.png">

**Comment by vexx32** [comment]
Did you try the fixes folks mentioned above (disabling client keyboard mapping in the RDP settings)?

Beyond that, I have a vague recollection that it might be worth seeing what version of PSReadLine is on the box you're connecting to and whether it might need updating.

**Comment by pr1malc0de** [comment]
As far as i am aware the RD web client is delivered from from RDS services and there is no way to confgiure the settings for the session other than suppressing telemetry. https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin i have raised this at the suggested place in that article too.

**Comment by pr1malc0de** [comment]
@vexx32 well there never used to be any settings but it appears there is an option now to turn on "Input Method Editor" in the RDP Web client. Turning that on and setting keyboard to "other" has fixed the issue for me!

![image](https://user-images.githubusercontent.com/662108/206434577-1363fbd1-1bef-40ec-b90f-b1a20287a9e2.png)

**Comment by vexx32** [comment]
Ah heck yeah, nice find! 💖

**Comment by ferdnyc** [comment]
Indeed. In fact, perhaps someone from the PowerShell team (if anyone's out there listening) — or @he852100, of course, if you're still around — could retitle this issue to something slightly more precise for the benefit of future users searching the open issues, now that we've nailed down the exact pathology? I'm thinking something like,

"Can't type into PowerShell window when connected via Remote Desktop"

or

"Keyboard input ignored by PowerShell running in Remote Desktop session"

**Comment by fd694309** [comment]
Issue still exists. But Microsoft prefers to ignore the issue. since there is a workarround, Please specify 
= WILL NOT INVESTIGATE OR SOLVE

**Comment by ferdnyc** [comment]
@fd694309 I mean, that's pretty heavily implied by the issue being auto-closed. I don't see why they have to be any more explicit than that.

And in fairness, I doubt anyone from Microsoft has **_seen_** this issue since 2020; certainly not since the workaround was discovered.

You could try opening a _new_ issue, specifically reporting that PowerShell only responds to low-level scancode keyboard input, but not Unicode keyboard input, over Remote Desktop. Now that we know precisely what the issue actually **is**.
