### ISSUE TITLE
Get-CimClass -ClassName Accepting Wildcard

### ISSUE THREAD

**Issue by benAugust** [PowerShell/PowerShell#12752]
I see a discrepancy between the help command in powershell and the powershell online help.

If I run help Get-CimClass -full, I see the parameter of -ClassName with Accept wildcard characters? false.

But, if I go to the online help site. https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/get-cimclass?view=powershell-7 I see the parameter of -ClassName with Accept wildcard characters? true.

**Comment by iSazonov** [comment]
Dup #4715. Please discuss there.

**Comment by vexx32** [comment]
@iSazonov sounds more like this is just a discrepancy between what's shown from `Get-Help Get-CimClass -Parameter ClassName` and what's shown in the online help page. I don't think the other issue really covers this (though I'm not sure if this is an issue for this repo or the docs repo).

**Comment by thlac** [comment]
Get-Help shows the correct info for me, maybe they haven't run Update-Help yet?

**Comment by iSazonov** [comment]
I guess there are no help files at all - only generated output.
