### ISSUE TITLE
Use `start-Process` start any process with PID 1 as `exec` do in bash

### ISSUE THREAD

**Issue by lktslionel** [PowerShell/PowerShell#12750]
# Summary of the new feature/enhancement

###### As A
User 

###### I WANT
To use `pwsh` as my default container's shell

###### SO THAT
I could launch any process with `start-Process` and make the process be the `PID 1`

**Comment by SteveL-MSFT** [comment]
I think first we need to discuss how to expose this via `Start-Process`.  For example, maybe we could add a switch `-AsExec`?  cc @JamesWTruher and @rjmholt for suggestions.  The code to actually call `exec` can be borrowed from here: https://github.com/PowerShell/PowerShell/blob/b1e998046e12ebe5da9dee479f20d479aa2256d7/src/powershell/Program.cs#L436

**Comment by lktslionel** [comment]
Does `Program.Exec` act the same way as the linux `exec` ? 
If so `-AsExec` seems great.

**Comment by rjmholt** [comment]
`Exec` doesn't play nicely with .NET's environment variable implementation; they have a native layer to prevent thread issues with things setting environment variables.

I'd like the understand the scenario a bit better if we can. I understand that PID 1 is special and has its own Linux namespace, but what's the constraint on the program?

My thinking here is I'm not sure we can make this behave well enough in general that we can support it nicely.

Also I'm not sure `Start-Process` is the right place to put the logic:

- We're not starting a new process
- We'll be using entirely new logic, so it's not a simple perturbation from the current implementation

**Comment by rjmholt** [comment]
Related issues:

- https://github.com/dotnet/runtime/issues/30525
- https://github.com/dotnet/runtime/issues/4103
- https://github.com/dotnet/runtime/issues/9529

**Comment by rjmholt** [comment]
I have thought about us implementing this though, and I think it deserves its own command like `Invoke-Exec` or some other wording that implies that this will be the last PowerShell command you get to use

**Comment by lktslionel** [comment]
Here is a concrete example. Let's say, I want to create a custom `nginx` that derives from `mcr.microsoft.com/powershell`. Doing this, usure that my default shell will be powershell (`pwsh`). 

My Doker file looks like this : 

```dockerfile
FROM mcr.microsoft.com/powershell

COPY run.sh /run.sh

CMD /run.sh 
```

The `run.sh` script use `exec nginx -g 'daemon off;'`, to make sure the `nginx` command get `PID 1`. But this only works with `bash/sh` shell because they suport `exec`command.

It will be great if I could do something like this and make sure I get the same behavior as below : 


```dockerfile
FROM mcr.microsoft.com/powershell

COPY run.sh /run.sh

CMD Invoke-Exec -Command nginx -g 'daemon off;'
```

I hope is more clear now :-)
Let me know.

**Comment by JamesWTruher** [comment]
So the exec'd process will get whatever PID had spawned it. It's only `1` in your scenario because it's a docker instance where the first process gets the PID you're looking for. The PID itself shouldn't matter much unless the `nginx` process _must_ have PID=1 - is that the case?

**Comment by lktslionel** [comment]
Actually, WHen I say `PID 1` is because — as you said — it's the first process. If instead, any first process forwards all the SIGKILL and SIGTERM to nginx (its child process) it works for my case.

In summary, it will be great if the `Invoke-Exec` make the executing command be the first process inside the container.

**Comment by rjmholt** [comment]
Here's a simple implementation of a cmdlet that I haven't tested it. But it should be as simple as compiling it to a DLL (you can use a new C# project or Add-Type to do that), importing the DLL (you could add a module manifest and put it on the module path to import it implicitly too), and then calling `Exec -Executable nginx -Arguments 'daemon','off;'`

```csharp
[Alias("exec")]
[Cmdlet(VerbsLifecycle.Invoke, "Exec")]
public class InvokeExecCommand : PSCmdlet
{
    [Parameter(Mandatory = true)]
    [ValidateNotNullOrEmpty]
    public string Executable { get; set; }

    [Parameter()]
    public string[] Arguments { get; set; }

    protected override void EndProcessing()
    {
        // Resolve exes passed by path
        string executable = Executable.Contains('/') || Executable.Contains('\\')
            ? GetUnresolvedProviderPathFromPSPath(Executable)
            : Executable;

        // Set up the exec arcs
        var args = new List<string>();
        if (Arguments != null)
        {
            args.AddRange(Arguments);
        }
        args.Add(null); // Needed by exec

        // Flush the env vars
        foreach (DictionaryEntry envEntry in Environment.GetEnvironmentVariables())
        {
            setenv(envEntry.Key.ToString(), envEntry.Value.ToString(), overwrite: true);
        }

        // Invoke the exec syscall
        exec(executable, args.ToArray());
    }

    [DllImport("libc", SetLastError = true)]
    private static extern int exec(string path, string[] args);

    [DllImport("libc", SetLastError = true)]
    private static extern int setenv(string name, string value, bool overwrite);
}
```

**Comment by lktslionel** [comment]
@rjmholt Thanks! Do you think that it should be part of a powershell release ?
I will test it and let you guys know if it works.

I will try with this `Dockerfile`: 

```Dockerfile
FROM mcr.microsoft.com/powershell

SHELL ["/opt/microsoft/powershell/7/pwsh", "-C"]

RUN apt update -y;apt install nginx -y

# Or with this alias 'exec'
CMD  Invoke-Exec -Executable nginx -Arguments '-g','daemon off;'
```

Acutally it does look nice 🙈🤗

**Comment by rjmholt** [comment]
> Do you think that it should be part of a powershell release ?

I think we might look to implementing in a module of unix-specific PowerShell commands. If that proves useful or popular, we can consider whether it should be a part of the standard PowerShell release. But in general, our preference is for new commands to go into modules unless they really make sense at the heart of PowerShell, since the module system and the gallery lower the friction of getting new functionality

**Comment by lktslionel** [comment]
Geat. I will try to implement it in another powershell module.
Should I close the issue or let it open in case I need some help?

**Comment by JamesWTruher** [comment]
@lktslionel I'm working on this now as well - planning on releasing a UnixUtils module which includes umask, ulimit and this.

**Comment by lktslionel** [comment]
Great @JamesWTruher !
Let me know if you need any help from me.
I can write documentation if needed. Where can I see your progress ?

**Comment by r-darwish** [comment]
@JamesWTruher such module would be helpful to me. Would you mind posting it here once it's published?

**Comment by thunder7553** [comment]
I stumbled at the same problem, and I can add some background information to it. 

The main problem is that the container runtime ("docker") will send a SIGTERM to process ID 1. When the program does not quit on time, it will kill the process. 

"exec" in bash will replace the process, so that the same process id is reused, und the SIGTERM will be sent the running program (e.g., dotnet Kestrel server)

Another way would be to catch the signals and forward it to the programs. This is possible in `bash` with `trap` and then calling `kill` with the child process id. I did not find a way to do it that way in PowerShell.

The `exec` approach has the benefit that it uses less memory (since the PowerShell process is gone). The `trap` method has the benefit that you could spawn multiple processes and kill them all at once.

I ended up replacing my PowerShell Script with a bash script again. It was quite a pain because I was trying to set the ASPNETCORE_URLS based on some other env variables. Super easy in PowerShell.

**Comment by thunder7553** [comment]
And I discovered for PowerShell 7.3, there is `switch-process` - https://learn.microsoft.com/en-US/powershell/module/Microsoft.PowerShell.Core/Switch-Process?view=powershell-7.3

**Comment by SteveL-MSFT** [comment]
`Switch-Process` was added that replaces the need for changes to `Start-Process`
