### ISSUE TITLE
PowerShell 7.1 preview 3 - Security Error

### ISSUE THREAD

**Issue by Schwanowski** [PowerShell/PowerShell#12757]
# Steps to reproduce

```
run.ps1 thorows an SecurityError on 7.1 while not in 7.0

Has anything being changed on the security interface?

```

# Expected behavior

```
I dont know if 7.0 or 7.1 behavioris correct

```

# Actual behavior

```
In 7.0 all works fine

In 7.1. it throws an securty exception

cannot be loaded. The file xxx.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.

```

# Environment data

```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      1      0      preview.3

```

**Comment by kilasuit** [comment]
by default you need to set your execution policy in each new version of PowerShell any preview version if you have never installed a prior version of the preview as it doesn't 
The details you need to follow are in the help topic about_Execution_Policies as shown in the message or at https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7

@iSazonov this isn't a Security issue, so the `Area-Security` label is not correct & should be removed
