### ISSUE TITLE
Support passing options to SSH through cmdlets that allow remoting over SSH

### ISSUE THREAD

**Issue by BrannenGH** [PowerShell/PowerShell#12762]
# Summary of the new feature/enhancement

As a user automating with PowerShell, I would like to [pass options to OpenSSH](https://man.openbsd.org/ssh#o) when using PSRP over SSH as a SSH client, like `ssh -o GlobalKnownHostsFile=/Path/To/File`.

Currently, it seems only a [small subset](https://github.com/PowerShell/PowerShell/blob/0e435a51432121f6c71fde081e2d18e0038b0e8a/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2066) of command line arguments for SSH are supported. 

# Proposed technical implementation details

A new parameter could be added to the Invoke-Command and New-PSSession cmdlets that would allow a dictionary of strings or a list of strings for configuration options.

**Comment by vexx32** [comment]
Looks like something you might want to field, @PaulHigin 🙂

**Comment by PaulHigin** [comment]
I think this is a great idea.  We initially kept SSH command options to a minimum to keep things simple.  But if they are useful, we should definitely support them.

**Comment by BrannenGH** [comment]
That's great! It doesn't seem like this would be too hard to implement, I'd have no problem taking a look.
