### ISSUE TITLE
Install from Microsoft Store 

### ISSUE THREAD

**Issue by Samuel12321** [PowerShell/PowerShell#12765]
The msix package is already distributed, it would make it a lot easier to get and keep updated if it was installable from the Microsoft Store.
Additionally as the package would be signed, it would allow msix package to be installable without having to switch to developer mode.

**Comment by iSazonov** [comment]
MSFT team already announces this. They works on this internally.

**Comment by kilasuit** [comment]
This is a dupe of #7730

**Comment by Samuel12321** [comment]
sorry, i didn't see #7730 
Closing now.
