### ISSUE TITLE
Overwrite mode not working

### ISSUE THREAD

**Issue by johnnygerard** [PowerShell/PowerShell#12769]
# Steps to reproduce

```none
Press Insert key or uncheck 'Insert Mode' in Properties > Options > Edit Options
```

# Expected behavior

```none
Toggles between insert and overwrite mode.
```

# Actual behavior

```none
Stays in insert mode.
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by iSazonov** [comment]
You should have an elevated permissions to change system shortcut.
As workaround you could create a custom shortcut.

**Comment by johnnygerard** [comment]
I am able to change the system shortcut.

The issue is that it does not work. Even when 'Insert Mode' is unchecked, the shell behaves as if I was in 'Insert Mode'. My 'Insert' key does not work either.

In cmd.exe, I can overwrite but not in powershell (I have the same issue in Powershell 5).

**Comment by iSazonov** [comment]
It works if you do `Remove-Module PSReadline`.  Please open issue in PSReadline repo.

**Comment by johnnygerard** [comment]
Thank you for your help.
