### ISSUE TITLE
No support of System.Management.Automation for .net framework

### ISSUE THREAD

**Issue by kriti218** [PowerShell/PowerShell#12773]
In my project, we are using .net framework 4.6,2 and want to call powershell from our c# code. When i went to nuget to install the required library (System.Management.Automation), i could see that 6.x.x onward versions are available and all support .net core and not .net framework.

my ask is how should i use or call powershell in my application as i cant upgrade it to .net core. It is a legacy application. I could manage to find one "Install-Package System.Management.Automation.dll -Version 10.0.10586" whicb alteast let me use PS but that is a deprecated one.

Please suggest how can i get old versions of above library from nuget for .net framework as that is blocking my work currently as we are short of time now.

**Comment by powercode** [comment]
You should be able to use https://www.nuget.org/packages/PowerShellStandard.Library

Version 5.1 works with Windows Powershell.

**Comment by alx9r** [comment]
@powercode Is PowerShellStandard.Library 5.1.0 meant to supercede [Microsoft.PowerShell.5.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/)?  Or do those have different purposes?

**Comment by powercode** [comment]
The standard library should work for .net core pwsh also.

**Comment by Nikita-T86** [comment]
As stated in [README](https://github.com/PowerShell/PowerShellStandard/blob/master/README.md) for PowerShellStandard.Library "NOTE: You should not use PowerShell Standard for standalone applications that leverage PowerShell." and indeed it doesn't work, see for example [here](https://github.com/PowerShell/PowerShellStandard/issues/63).

So it is still not clear what is the correct solution.
