### ISSUE TITLE
Intellisense only works for the first parameter of an attribute

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#12771]
# Steps to reproduce
Open up Powershell (with PSReadline), VS code (with Powershell extension) or even just the ISE and type in the following:
```powershell
#2 suggestions pop up for the parameters "Options" and "ErrorMessage".
[ValidatePattern(<CTRL+Space>)]$StringToCheck

#No options show up
[ValidatePattern("\w",<CTRL+Space>)]$StringToCheck

#You can still tab complete the parameters.
[ValidatePattern("\w",O<Tab>)]$StringToCheck
```
This happens with any attribute.

# Expected behavior
Intellisense shows suggestions for attribute parameters, even after adding the first parameter.

# Actual behavior
Intellisense only shows suggestions for the first parameter you add.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
This may be because the () hold a mixture of arguments for the constructor, and properties to be set after the attribute object is created. I can't get ctrl space do display a list of properties in the ISE or in 7 on VSCode unless there is the start of a property name. (e.g. type O in either and "Options" is offered). VSCode offers things the editor thinks might be useful but not the property choices.  The first and subsequent properties behave the same way.

**Comment by vexx32** [comment]
Yeah this might just be a total lack of completion support here. It's probably something that could be added, I'd imagine.

**Comment by MartinGC94** [comment]
Okay maybe the examples were bad at describing how to actually see this properly. The line has to be complete like this: `[ValidatePattern()]$StringToCheck` then you move the cursor inside the parentheses and press CTRL+Space
Here it is inside the ISE:
![image](https://user-images.githubusercontent.com/42123497/82932486-cbb18980-9f88-11ea-8612-b897a32309b6.png)
Here it is inside the latest Powershell preview version, this time with the cmdletbinding attribute:
![image](https://user-images.githubusercontent.com/42123497/82932690-19c68d00-9f89-11ea-9009-20e927cdc176.png)

Writing this comment has made be realize why it doesn't work, adding the comma for the next parameter makes the line invalid and that breaks intellisense, adding a letter makes it valid again but that obviously limits the options offered by intellisense.

**Comment by vexx32** [comment]
Oh, okay, that makes sense to a point.

Plenty of other things are able to generate completions for things like that though, and we should (at least in theory) be able to offer completions for the incomplete input as well (without the trailing `)]`, it's just a matter of figuring out how that gets presented in the parser and updating the completion logic to handle that.
