### ISSUE TITLE
Import-Module memory allocation when using module name tab-completion 

### ISSUE THREAD

**Issue by mziyabo** [PowerShell/PowerShell#12774]
# Steps to reproduce

When calling `Import-Module` and using tab-completion to complete the name of  module, pwsh seem to allocate quite a large chunk of WS/working set memory as compared to a scenario when you just type out the name of your module without tab-completion

E.g. I have a large module here `AWSCompleter` in the PSGallery, the psmi is 2mb and it appears as though this is used to determine the amount of allocated memory when using tab-completion - I could be wrong here.

To illustrate, after starting pwsh with `no-profile` flag  **WS** ~48mb
Here are the comparisons of then attempting Import-Module AWSCompleter with and w/o module name tab-completion:

|After Import-Module| ~WS(mb) |
|-----------------------|-----|
|W/o tab-completion| 90 |
|With tab-completion|136|

A difference of 46mb in the WS- pretty significant (for me). 
> Note, I'm aware the module is large and am working on breaking it down but the question remains about memory allocation with the above scenarios:

- Last but, also important, if you don't actually hit **Enter** after the `Import-Module <Tab-Completed Module Name>`
The WS memory is already allocated and gone up to 136 despite the fact that the module hasn't actually been imported or loaded into the Session.
In other words to reproduce simply tab-complete and don't hit enter and observe the memory, it is quite observable with a large module like `AWSCompleter` or any module I'd think that has a file size in that 2mb range.
# Expected behavior

- I would expect the memory allocated to be the same whether tab-completion was used or otherwise. 
- Also if I don't hit **Enter** I would expect that there not be any WS allocation or spike without the module being actually loaded into the Session.

# Actual behavior

- High WS for tab-completed module-name when using  Import-Module

# Environment data

$PSVersionTable:

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by jhoneill** [comment]
A lot of tab completers do Get-ThingToComplete.  So tab completing a command seems to do get-command which triggers evaluating the dynamic parameters of loaded commands. 
If tab-completing a module name works in the same lots of module metadata may be loaded, and if you have many modules (e.g. the whole Azure set), or very large modules, then that would come with a similar hit.

**Comment by mziyabo** [comment]
Either way tab-completion of Module Names should not use 100Mb of WS memory before the actual Import-Module command itself is executed, in this case before the module is loaded in the session or memory
This isn't a hit, it is memory that is preallocated regardless of the module being in the session- why preallocate in this way? Also if I abort then what? When does this get Garbage Collected because the memory remains as claimed for quite some time after
