### ISSUE TITLE
Import-PowershellDataFile double wraps ScriptBlock

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#12789]
# Steps to reproduce
 1. Create a `test.psd1` file with following content:
```powershell
@{
	Script = {
		echo "test"
	}
}
```
 2. Import the file:
```powershell
$data = Import-PowerShellDataFile .\test.psd1
```
 3. Run the script block:
```powershell
& $data.Script
```

# Expected behavior

Script block runs and `"test"` is printed to output.

# Actual behavior

Script block runs, but returns another script block that must be invoked again to actually run the script block content.

Following script illustrates the issue:
```powershell
$data = Import-PowerShellDataFile .\test.psd1

echo "BARE:"
echo $data.Script

echo "INVOKE 1x:"
echo (& $data.Script)

echo "INVOKE 2x:"
echo (& (& $data.Script))


# same hashtable, defined inside a normal script
$data2 = @{
	Script = {
		echo "test"
	}
}

echo "BARE:"
echo $data2.Script

echo "INVOKE:"
echo (& $data2.Script)
```
Output:
![image](https://user-images.githubusercontent.com/6414091/82843941-0bbc3200-9edf-11ea-8d87-21373d8a4080.png)

# Environment data
```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by General-Fault** [comment]
Looking for a simple way to test for this condition before executing the scriptblock.
All I've got so far is:

```
$result = $data.Script.Invoke()
if ($result -is [System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject]] -and $result[0] -is [ScriptBlock] ) {
  $result = $result.Invoke()
}
```

**Comment by MatejKafka** [comment]
From more exploration around this issue, this might be intentional, although unfortunate. It seems using script blocks in .psd1 is not officially supported, as it is supposed to be a static, data-only format. Still, I think this should be either fixed (prefarably) or explicitly disapproved with a meaningful error message on import.

**Comment by loleebr** [comment]
Ran into this issue myself and I agree.  Should be either fixed or a warning given.

**Comment by kort3x** [comment]
Importing and invoking scriptblocks from psd1 should be supported and this issue should be fixed.

**Comment by kort3x** [comment]
bump

**Comment by MatejKafka** [comment]
I looked around a bit and wrote down a few notes and links.

Looking through unit test files, I don't see any explicit test for this behavior.

Implementation of the cmdlet: https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs#L60

Relevant bits:
```
var ast = Parser.ParseFile(resolved, out tokens, out errors);
var data = ast.Find(static a => a is HashtableAst, false);
return data.SafeGetValue(SkipLimitCheck)
```

Relevant call from `Parser.ParseFile`: https://github.com/PowerShell/PowerShell/blob/102782fbb0bc82310ca8eaba5574fc54e9ca9e6d/src/System.Management.Automation/engine/parser/Parser.cs#L103

I'd suspect that the `.SafeGetValue` call has something to do with the issue, I'll play with it when I find more time.

**Comment by MatejKafka** [comment]
not completed, please reopen

**Comment by MatejKafka** [comment]
I believe the issue is caused by this method: https://github.com/PowerShell/PowerShell/blob/ec3840d6a1fffdbaca7173ededb4a4504b2f5b41/src/System.Management.Automation/engine/parser/SafeValues.cs#L793-L796

The extent includes the opening and closing braces (`{...}`), which causes `ScriptBlock.Create`, which expects the actual content inside the scriptblock, without the braces, to create a nested scriptblock.

**Comment by santisq** [comment]
> I believe the issue is caused by this method:
> 
> https://github.com/PowerShell/PowerShell/blob/ec3840d6a1fffdbaca7173ededb4a4504b2f5b41/src/System.Management.Automation/engine/parser/SafeValues.cs#L793-L796
> 
> The extent includes the opening and closing braces (`{...}`), which causes `ScriptBlock.Create`, which expects the actual content inside the scriptblock, without the braces, to create a nested scriptblock.

And the solution might be:

```cs
public object VisitScriptBlockExpression(ScriptBlockExpressionAst scriptBlockExpressionAst)
    => scriptBlockExpressionAst.ScriptBlock.GetScriptBlock();
```

**Comment by hudsonm62** [comment]
This is the only workaround I've stumbled upon thus far. Putting here for my own future reference too.

```powershell
# test.psd1
@{
    Script = {
        param($Name)
        Write-Output "Hello, $Name!"
    }
}
```
```powershell
function Import-DataFile {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory, ValueFromPipeline)]
        [string]$DataFile
    )
    process {
        return $DataFile | Get-Item -Force | Get-Content -Raw | Invoke-Expression
    }
}

$data = ".\test.psd1" | Import-DataFile
& $data.Script -Name 'World'

# Hello, World!
```
