### ISSUE TITLE
Error when using `Add-Type` with `-ReferencedAssemblies`

### ISSUE THREAD

**Issue by Shayan-To** [PowerShell/PowerShell#12781]
# Steps to reproduce

```powershell
Add-Type -Language CSharp -TypeDefinition @'
public class Test1
{
    public static void f()
    {
        System.Console.WriteLine("abc");
    }
}
'@ -ReferencedAssemblies System.Windows.Forms
```

# Expected behavior

The code compiles and the type `Test1` is added and available.

# Actual behavior

It gives me this error:

```none
Add-Type: (5,9): error CS0234: The type or namespace name 'Console' does not exist in the namespace 'System' (are you missing an assembly reference?)
        System.Console.WriteLine("abc");
        ^

Add-Type: Cannot add type. Compilation errors occurred.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by alx9r** [comment]
@Shayan-To 

I think you'll need to reference the assembly containing System.Console explicitly by passing the right name to `-ReferencedAssemblies`.  The assembly containing `System.Console` for .Net Core seems to be System.Console.dll.  It is usually possible to find the assembly you need to reference for a type in the following ways:

* the "Assembly:" field of the documentation on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/system.console?view=netcore-3.1)
* outputting the assembly location from PowerShell (`[System.Console].Assembly.Location`)

The following outputs `abc` without errors:

```PowerShell
Add-Type -Language CSharp -TypeDefinition @'
public class Test1
{
    public static void f()
    {
        System.Console.WriteLine("abc");
    }
}
'@ -ReferencedAssemblies @(
    'System.Windows.Forms'
    ([System.Console].Assembly.Location)
)
[Test1]::f()
```

FWIW `Add-Type` makes an amount of effort to reference default assemblies and resolve named assemblies.  But in your case, mentioning `System.Windows.Forms` seems to cause `Add-Type` to not reference `System.Console`.  The assembly resolution logic is implemented in [AddType.cs](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs) but it's not obvious to me why that happens.

**Comment by iSazonov** [comment]
Dup #9599. Please discuss there.
