### ISSUE TITLE
mkdir <name> | cd breaks $pwd

### ISSUE THREAD

**Issue by james-world** [PowerShell/PowerShell#12780]
Piping mkdir to cd breaks $pwd to include the provider name.

This is immediately noticeable when the current path is displayed in the prompt using powerline.

# Steps to reproduce

```powershell
cd c:\
mkdir test | cd
$pwd
```

# Expected behavior

```none
C:\test
```

# Actual behavior

```none
Microsoft.Powershell.Core\FileSystem::C:\test
```
# To quickly workaround and reset $pwd
Enter `<current-drive>:`, e.g. `C:` at the prompt. (Note this doesn't change the current directory.)

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This is the same issue as #9293. 🙂
