### ISSUE TITLE
Support a PowerShell repository on a SMB share

### ISSUE THREAD

**Issue by craibuc** [PowerShell/PowerShell#12796]
# Support a PowerShell repository on a SMB share

We are in a mixed environment (Windows, OS X).  

We would like to use a SMB share as a private, PowerShell repository. 

Currently, attempts to register a SMB share:

```powershell
$Uri = 'smb://10.1.3.6/PowerShellRepository'
$Repository = @{
    Name = 'MyRepository'
    SourceLocation = $Uri
    PublishLocation = $Uri
    InstallationPolicy = 'Trusted'
}
Register-PSRepository @Repository
```
produces an error:

```powershell
Register-PSRepository: The specified Uri 'smb://10.1.3.6/PowerShellRepository' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
```

**Comment by ThomasNieto** [comment]
You'll want to open an issue in the PowerShellGet repository for this enhancement.

**Comment by craibuc** [comment]
OK.  Thanks for the clarification.
