### ISSUE TITLE
-Begin scriptblock of additional Foreach-Objects run too early in the pipeline

### ISSUE THREAD

**Issue by Willem-J-an** [PowerShell/PowerShell#12794]
# Steps to reproduce

```powershell
@('a','b','c') |
Foreach-Object `
  -Begin {Write-Host "Begin round 1"} `
  -End {Write-Host "End round 1"} `
  -Process {Write-Host $_; $_} |
Sort-Object -desc |
Foreach-Object `
  -Begin {Write-Host "Begin round 2"} `
  -End {Write-Host "End round 2"} `
  -Process {$_ }
```

# Expected behavior

```
Begin round 1
a
b
c
End round 1
Begin Round 2
c
b
a
End round 2

```

# Actual behavior

```
Begin round 1
Begin Round 2
a
b
c
End round 1
c
b
a
End round 2

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by jhoneill** [comment]
This is correct 
All the begin blocks run 
Then all the items come down the pipeline and the process blocks run
Finally all the end blocks run. 

It is not Command1 runs to completion with its output stored
Command2 takes command1's output and runs to completion storing its output 
Command3 takes command2's output

This has a number of benefits, notably if the last step won't be able to run its begin block can stop the other commands doing anything saving time, and potentially saving preventing losing the output of change which can't [easily] be redone to generate the same output.

**Comment by Willem-J-an** [comment]
I understand this is the case, but sometimes this behavior (Run to completion with output stored) does occur, for example, when using the Sort-Object; all objects will gather there for sorting, and stream into the next Foreach-Object when they are done sorting. That's when I would expect the -Begin block of the second Foreach-Object to start, as that is literally before the objects start streaming into it.

I can imagine some cases where the -Begin block running too early in this case gives problems, for example when you are working from a certain Azure Context, and need one context in the first, and another context in the second process block. The second -Begin block would run too early, causing objects in the first process block to be processed in the wrong context. You also do not want to set the context in the -Process block, as it would keep setting the context over and over again.

**Comment by jhoneill** [comment]
> I understand this is the case, but sometimes this behavior (Run to completion with output stored) does occur, for example, when using the Sort-Object; all objects will gather there for sorting, and stream into the next Foreach-Object when they are done sorting. That's when I would expect the -Begin block of the second Foreach-Object to start, as that is literally before the objects start streaming into it.

Yes, you won't be the only person to expect that, but if the last command writes to a file and the file is locked or must logon and credentials are bad, or ... how does the last command stop the first generating any data if nothing in it can run before the first one has sent at least the first of its output ? 

> 
> I can imagine some cases where the -Begin block running too early in this case gives problems, for example when you are working from a certain Azure Context, and need one context in the first, and another context in the second process block. The second -Begin block would run too early, causing objects in the first process block to be processed in the wrong context. You also do not want to set the context in the -Process block, as it would keep setting the context over and over again.

In that case you can't run as one pipeline and need
```
$temp = Command1 <context1>
command2 -input <$temp> <context2>
```
Or in at least one case I know of, but the "begin" code in the process block with a flag to say it has been run before and should be skipped after the first object. 
The advantages of  the way it is implemented outweigh the disadvantages, but as you've said there are cases where someone might prefer the other way.

**Comment by Willem-J-an** [comment]
There would be workarounds for any of the cases we can come up with.

Is the second Begin block supposed to run when the first object comes through the pipeline(1), or as soon as the pipeline starts at all(2)? Right now it seems the second case is true, based on the output I'm seeing.
1. In the first case, this wouldn't break anything in the way I would consider this to work. As soon as any object hits the Foreach-Object, run the -Begin block, that should work for both the 'streaming' pipeline, and the 'batch' pipeline.
2. In the last case this wouldn't solve the issue of needing data to check if the first script block should keep running, also it seems more intuitive to just place the Begin logic of the second Foreach-Object in the -Begin block of the first Foreach-Object.

With this all said, now that I know this behavior I can take it into account. It is rather simple to make it work the way I need; adding parentheses around the first block is enough.
``` pwsh
(@('a','b','c') |
Foreach-Object `
  -Begin {Write-Host "Begin round 1"} `
  -End {Write-Host "End round 1"} `
  -Process {$_;Write-Host $_} |
Sort-Object -desc) |
Foreach-Object `
  -Begin {Write-Host "Begin round 2"} `
  -End {Write-Host "End round 2"} `
  -Process {$_ }
```

**Comment by vexx32** [comment]
Yeah, this is by design. All cmdlets in the pipeline execute their `begin {}` or `BeginProcessing()` or (in ForEach-Object's case) `-Begin { }` code before any `process {}` block is run. 

Could it be changed? Hm. Maybe? Is it worth doing so? Probably not, unless there's a really good reason to. Keep in mind PS has worked this way pretty much since v1, way back in the Windows XP days. Would need to be a fairly compelling reason to change something fundamental like this since it'd alter the behaviour in pretty subtle but potentially very impactful ways.

**Comment by Willem-J-an** [comment]
Unfortunately I would have to agree with you. Thanks @jhoneill and @vexx32!
