### ISSUE TITLE
Set-Location unexpected behaviour with \\ on network paths

### ISSUE THREAD

**Issue by cpmcgrath** [PowerShell/PowerShell#12809]
When working with local drives I can enter \\\\ in a path and powershell understands that I really just meant 1:
```powershell
set-location c:\windows\\system32
$pwd -eq "c:\windows\system32"
```
This is the same as Powershell 5. However, Powershell 5 also allowed this behaviour with network paths while powershell 7 doesn't.

Why is this useful? well, it just lets us be a bit lazy with string concat - 
```powershell
#easy to write, easy to read
cd "$base\foo\bar"
#hard to write, hard to read
cd (Join-Path $base "foo\bar")
```
Even if you don't agree with this behaviour, I think at the very least the operation should just fail instead of taking you to the path up to where the \\ is.

# Steps to reproduce

```powershell
set-location \\localhost\c$\windows\\system32
```

# Expected behavior

```none
$pwd -eq "\\localhost\c$\windows\system32"
```

# Actual behavior

```none
$pwd -eq "\\localhost\c$\windows"
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
This works well in both PowerShell. You should run with elevated permissions.
