### ISSUE TITLE
Unable to send unicode characters to PowerShell 7 via wincompose

### ISSUE THREAD

**Issue by IarwainBen-adar** [PowerShell/PowerShell#12807]
# Steps to reproduce

1. Install [WinCompose](https://github.com/samhocevar/wincompose) v0.9.4 (default settings: <kbd>right Alt</kbd> key set to <kbd>compose</kbd>)
2. Open PowerShell 7
3. Ensure that `$OutputEncoding`, `[System.Console]::InputEncoding`, and `[System.Console]::OutputEncoding` are all set to UTF-8
4. Type Unicode character composition `å` via compose key sequence <kbd>compose</kbd><kbd>o</kbd><kbd>a</kbd> = `å`
5. Observe that no character is sent to PowerShell 7 (no Unicode error character, no fallback character `a` either)
6. Copy/paste the `å` character to PowerShell and observe that it renders correctly
7. Type <kbd>left Alt</kbd><kbd>0</kbd><kbd>2</kbd><kbd>2</kbd><kbd>9</kbd> in PowerShell 7 and observe that `å` is sent to the shell
8. Repeat the compose key test in cmd.exe and observe that <kbd>compose</kbd><kbd>o</kbd><kbd>a</kbd> properly sends `å` to the cmd.exe shell
9. Repeat the compose key test in a Windows Terminal-hosted PowerShell 7 tab and observe that <kbd>compose</kbd><kbd>o</kbd><kbd>a</kbd> properly sends `å` to the Windows Terminal shell

# Expected behavior

I would expect compose key compositions to work in PowerShell 7 the same as they do in Windows Terminal or cmd.exe

# Actual behavior

PowerShell 7 can output Unicode characters, and PowerShell 7 can receive Unicode characters as input from the clipboard and other sources, but PowerShell 7 does not seem to be able to receive compose key Unicode character compositions

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Does this still occur if you unload PSReadLine? (`Remove-Module PSReadLine`)

**Comment by IarwainBen-adar** [comment]
@vexx32 no, this does not occur if PSReadLine is unloaded! Is this some known conflict? Does PSReadLineKeyHandler's key binding system not distinguish between left and right <kbd>Alt</kbd> keys? If I remove all <kbd>Alt</kbd> key combinations from PSReadLineKeyHandler, would you expect PSReadLine to still conflict with a <kbd>right Alt</kbd> compose key?

**Comment by IarwainBen-adar** [comment]
That definitely solves part of they mystery (thank you @vexx32 ), but it leaves me puzzled as to why a PowerShell 7 tab hosted within Windows Terminal can accept Unicode character compositions even while the PSReadLine module is loaded?

**Comment by vexx32** [comment]
I'm not really sure, but by the sounds of it it's something in how PSReadLine interacts with the default console host vs the Windows Terminal. I'd guess you should file the issue in the [PSReadLine](/PowerShell/PSReadLine) repo so it can be triaged appropriately; that module's not managed in the main PowerShell repo. 🙂

**Comment by IarwainBen-adar** [comment]
OK, I'll close this and re-submit the issue under [PSReadLine](https://github.com/PowerShell/PSReadLine) instead. Thank you.
