### ISSUE TITLE
We have $PSEdition, so shall "$IsWindows ,  $IsLinux ,  $IsOSX , and  $IsCore" be kept in PowerShell Core permanently?

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#1280]
The variables  $IsWindows ,  $IsLinux ,  $IsOSX , and  $IsCore  are now an integral part of PowerShell Core. $PSEdition serves the same purpose in PS Core, so shall the "$is" variables be kept permanently in PowerShell Core?

We should nail down this as early as possible, because existing tests are using the "$is" variables a lot, and new tests would follow the same pattern. It will be more work to clean them up if we decide to remove "$is" variables later.

PS C:> $PSEdition
Core
PS C:>

**Comment by SteveL-MSFT** [comment]
I remember having this discussed, but couldn't find any conclusion posted by the @PowerShell/powershell-committee

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee the discussion occurred and decision is here: https://github.com/powershell/powershell/issues/1635#issuecomment-275279483

**Comment by joeyaiello** [comment]
I still need to write more RFCs....fun....

**Comment by SteveL-MSFT** [comment]
Since it doesn't appear that the RFC is going to make it for 6.0.0, I'd like to revisit one aspect of this which is renaming $IsOSX to $IsMacOS for consistency (which may also mean renaming our Mac release filename).

**Comment by joeyaiello** [comment]
Yeah, we should probably move to macOS. We can leave the old one there as an alias too, right? Just make them resolve to the same thing? As for casing, I'm pretty hardcore about 'macOS', but capital M seems the right thing to do here.

**Comment by SteveL-MSFT** [comment]
Created a separate issue for $IsOSX->$IsmacOS
https://github.com/PowerShell/PowerShell/issues/4700

**Comment by JamesWTruher** [comment]
we don't have a backward compatibility problem _yet_ as this variable doesn't exist in 5x and we haven't released yet. I would rather not carry around state variables where we don't need to and while removing $IsOSX now may be a large PR because of the test changes, better now than after we release.

**Comment by SteveL-MSFT** [comment]
No longer an issue.  What exists will exist forever at this point for these automatic variables.
