### ISSUE TITLE
Get-ChildItem to a file is 2x slower than CMD

### ISSUE THREAD

**Issue by asklar** [PowerShell/PowerShell#12817]
# Steps to reproduce

```powershell
(Measure-Command { dir -Recurse C:\rnw | Out-File C:\temp\1.txt }).TotalSeconds
```
takes 15.222019 seconds
whereas CMD:
```txt
C:\temp\timecmd.cmd "dir /s C:\rnw > C:\temp\1.txt"
```
command took 0:0:8.47 (8.47s total)

# Expected behavior
Same performance as CMD.

# Actual behavior
2x slower than CMD

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.20133
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by p0W3RH311** [comment]
1-  in your ps code you use pipeline
2-  every cmdlet is aa object  in your  case every object passed throw pipeline is passed  is an object  (structured object) and not string ass cmd
3-  in cmd eveery commaand have here owwn parser in PS is one parser for every command  aand  one formater for all cmdlet

**Comment by iSazonov** [comment]
It is tracked in #3575

**Comment by asklar** [comment]
@p0W3RH311 @iSazonov  using redirection instead of pipe, is even worse:
```powershell
PS C:\rnw> (Measure-Command { dir -Recurse C:\rnw > C:\temp\1.txt }).TotalSeconds
18.5898439
```

The fact that everything is an object doesn't matter, that's an implementation detail. If we are pushing people away from CMD and onto PS as a replacement, then its performance must be comparable, and any overhead must be pay-for-play, and not affect the general case where I don't use any of the objects explicitly.

**Comment by vexx32** [comment]
Yeah, redirection to a file in PS is identical to `| Out-File -Path $path` so it incurs the same overhead. If you want to avoid some of the overhead of the formatter, you can just pull off the text properties that you actually need, or use a cmdlet designed to work with text rather than wasting time formatting everything (like `Out-File` does):

```ps1
# Set-Content coerces the input to string instead of sending it through the formatter
(Measure-Command { Get-ChildItem -Recurse C:\rnw | Set-Content -Path C:\temp\1.txt }).TotalSeconds

# Pull off the property you want to store
(Measure-Command { Get-ChildItem -Recurse C:\rnw | Select-Object -Property FullName | Out-File -Path C:\temp\1.txt }).TotalSeconds
```

The formatter exists for convenience and making the shell experience more user-friendly. If you don't want the overhead it brings, there are plenty of avenues available to you to speed things up. 🙂

**Comment by powercode** [comment]
```powershell
function cmddir {cmd /c dir /S}

**Comment by iSazonov** [comment]
@asklar What is a result for:
`(Measure-Command { dir -Name -Recurse C:\rnw > C:\temp\1.txt }).TotalSeconds`

**Comment by lukeb1961** [comment]
PWSH> $PSversiontable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.2
PSEdition                      Core
GitCommitId                    7.1.0-preview.2
OS                             Microsoft Windows 10.0.19631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PWSH> (Measure-Command { CMD /c DIR /S      'C:\Program Files\PowerShell' > C:\temp\1.txt }).TotalSeconds
0.2031207
PWSH> (Measure-Command { GCI -Name -Recurse 'C:\Program Files\PowerShell' > C:\temp\2.txt }).TotalSeconds
0.8576304
PWSH> (Measure-Command { GCI  -Recurse      'C:\Program Files\PowerShell' | Select-Object -Property FullName |  Out-File -Path C:\temp\3.txt  }).TotalSeconds
0.2609885

**Comment by iSazonov** [comment]
For `cmd.exe` more correct test is:
```
cmd /v:on /c "echo !TIME! &  DIR /S "C:\Program Files\PowerShell" > C:\tmp\1.txt & echo !TIME!"
```

**Comment by iSazonov** [comment]
For `Get-ChildItem -Recurce -Name` you can test with artifact from #12834.
