### ISSUE TITLE
Naming convention for `internal static readonly`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#12819]
In #11777, the readonly modifier was added to internal static members which raised an issue of our naming convention.

According to StyleCopAnalyzers on CodeFactor, "readonly variables that are not declared private must start with an upper-case letter" otherwise there are violations of the rule [SA1304NonPrivateReadonlyFieldsMustBeginWithUpperCaseLetter](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1304.md)

Our [naming conventions](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md#naming-conventions) state static fields should start with `s_`, however the existing code overwhelmingly uses PascalCase for `internal static readonly` members.

In my view conventions should be descriptive rather than prescriptive, so we should consider making changes to the written naming convention.

**Comment by vexx32** [comment]
Yeah most of the newer code I see uses `PascalCase` for these. Might be that our naming conventions doc needs an update? /cc @SteveL-MSFT

**Comment by xtqqczze** [comment]
https://github.com/dotnet/codeformatter/issues/281#issuecomment-442733951 makes a case that `readonly` should not change the casing style or prefixes.

I don't have a strong opinion either way, but CodeFactor rules should not conflict with naming conventions – it adds too much friction to pull requests.

**Comment by xtqqczze** [comment]
Currently, the PowerShell naming convention states:
> Use `_camelCase` to name internal and private fields and use `readonly` where possible.
Prefix instance fields with `_`, static fields with `s_` and thread static fields with `t_`.

Unfortunately there is no StyleCop rule available to enforce the use of `_camelCase` for `internal`.

I think the following changes would be reasonably descriptive of the existing codebase:
* Use `_camelCase` to name private fields (and prefix instance fields with `_`, static fields with `s_` and thread static fields with `t_`).
* Use `PascalCase` to name non-private fields.

If we modified the written convention as suggested we could enforce this using the StyleCop rule:
`SA1307: AccessibleFieldsMustBeginWithUpperCaseLetter`.

**Comment by xtqqczze** [comment]
We should also consider: https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md

**Comment by TravisEz13** [comment]
If we want to modify our code style, we should modify our code style doc.  We can discuss it there.  I would suggest one issue at a time and not changing any existing rule without a good reason.  the main reason for them is consistency.   cc @daxian-dbw
