### ISSUE TITLE
meta: Pester v5

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#12816]
Pester version [5.0.0](https://github.com/pester/Pester/releases/tag/5.0.0) has been released, we should start thinking about how to migrate.

***incomplete list***

## Blocking changes

* The `Invoke-Pester` interface is incompatible as some parameters have been removed, we must use the new advanced interface where configuration is passed as a single object via `-Configuration` parameter.

## Possibly blocking changes

* `-Pending` and `-Inconclusive` are currently unimplemented and are converted to `-Skip`. 
* Parametrized scripts are unimplemented

**Comment by iSazonov** [comment]
It would be nice to have a link to Pester 5.0 docs.
We will have to put "global" code to `BeforeAll` blocks.
It would interesting to see perf wins for our tests.

**Comment by vexx32** [comment]
It's gonna be a bit more than just that but yeah we should really see if we can update tests to work with v5 of Pester sooner rather than later. It'll be a good opportunity to resolve any outstanding style issues with the existing tests as well; there's probably going to be a fair bit of refactoring needed, especially in the older tests due to the new split behaviour between test discovery and test runs.

**Comment by xtqqczze** [comment]
@iSazonov the release notes appear to be the only documentation available for v5

**Comment by iSazonov** [comment]
All docs here https://github.com/pester/Pester/tree/v5.0 on main page.

**Comment by iSazonov** [comment]
We could add new CIs for Pester 5.0 and migrate step by step, file by file. 
For that we could change `tags` - "CI" with "CIv5", "Feature" with "FeatureV5" and so on.

**Comment by xtqqczze** [comment]
[Pester v5.1.0 is released](https://github.com/pester/Pester/releases/tag/5.1.0) with numerous improvements:
* NUnit output is fixed.
* Parametrized scripts are implemented.

**Comment by MatejKafka** [comment]
@kilasuit Still relevant, please reopen.

**Comment by kilasuit** [comment]
I think this will be a keep-open but low priority due to the amount of work that would be needed.
