### ISSUE TITLE
Invoke-DscResource not working as shown

### ISSUE THREAD

**Issue by danielniccoli** [PowerShell/PowerShell#12810]
# Steps to reproduce
![image](https://camo.githubusercontent.com/2a6ec02fddc847fb23ddb75495750453504d3e8d/687474703a2f2f646576626c6f67732e6d6963726f736f66742e636f6d2f706f7765727368656c6c2f77702d636f6e74656e742f75706c6f6164732f73697465732f33302f323031392f30392f696e766f6b656473637265736f757263652e676966)

Source: https://devblogs.microsoft.com/powershell/powershell-7-preview-4/

```powershell
Invoke-DscResource -Name PSModule -Method Test -Property @{ Name="Pester" }
```

# Expected behavior

![image](https://camo.githubusercontent.com/2a6ec02fddc847fb23ddb75495750453504d3e8d/687474703a2f2f646576626c6f67732e6d6963726f736f66742e636f6d2f706f7765727368656c6c2f77702d636f6e74656e742f75706c6f6164732f73697465732f33302f323031392f30392f696e766f6b656473637265736f757263652e676966)

# Actual behavior

![image](https://user-images.githubusercontent.com/2971735/82985126-c2113b80-9ff3-11ea-8edd-146ae35aea71.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasNieto** [comment]
@StevenBucher98 this issue can be closed.
