### ISSUE TITLE
Feature Request: Set-AuthenticodeSignature -TimeStampServer support HTTPS

### ISSUE THREAD

**Issue by RStoddart** [PowerShell/PowerShell#12827]
# Summary of the new feature/enhancement

When attempting to sign a Script with Set-AuthenticodeSignature 
using the 
**PS C:\Scripts\SignScript>** Set-AuthenticodeSignature -FilePath C:\Scripts\SignScript\* -Certificate $Cert -IncludeChain "All" -TimeStampServer 'https://ca.signfiles.com/tsa/get.aspx'
**Error:** _Set-AuthenticodeSignature : Cannot sign code. The TimeStamp server URL must be fully qualified, and in the format http://<server 
url>...._

(URL does verify and work in the **http:**// variant)

# Proposed technical implementation details (optional)

The command should accept and use the HTTPS: ssl protocol request as it does with the HTTP: protocol. 
I speculate that the code that validates the input, does not accept https: as valid option. 

Security teams are all SSL(TLS) happy and would demand anything going over network be SSL (TLS) encrypted.

**Comment by zaaj** [comment]
Any chance the fix will ever get back-ported to Windows Powershell 5.1 for shops who share their signed code with stock-windows-10 and Windows server versions that don't come with preview versions of Powershell Core 7.3?

**Comment by mndxt007** [comment]
Hello,

I was wondering if this was ever tested after the fix. In the PR, I see the validation checks are updated to include https scheme, but does the underlying Native API support HTTPs for timestamp URLs - https://learn.microsoft.com/en-us/windows/win32/api/cryptuiapi/nf-cryptuiapi-cryptuiwizdigitalsign ?

I get the error when use the sample provided in docs - https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-authenticodesignature?view=powershell-7.5#example-3-add-a-signature-that-includes-the-root-authority

![Image](https://github.com/user-attachments/assets/a4ef5cfb-c3c9-4ba2-ba42-3c3a2d84b672)

I tried other timestamp servers with similar results. 

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.0
PSEdition                      Core
GitCommitId                    7.5.0
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
