### ISSUE TITLE
Evaluating non-existent property always returns true (with certain test values)

### ISSUE THREAD

**Issue by villesl** [PowerShell/PowerShell#12828]
This seems to reproduce with all tested cmdlets. All that is needed is a non-existent property and evaluation against integer with two or more dots.

# Steps to reproduce

```powershell
(Get-Date).Nanosecond -eq 1.1.1
```

# Expected behavior

```none
False
```

# Actual behavior

```none
True
```

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by vexx32** [comment]
There's no such thing as "an integer with two or more dots". 

`10` is an integer. `10.1` is the `double` value `10.1`. `10.1.1` targets the (nonexistent) property named `1` on the value `10.1`.

The comparison returns true because neither property exists, so both return `$null` values.

**Comment by villesl** [comment]
True, thanks for clarifying!
