### ISSUE TITLE
Third line printed to STDERR causes pwsh to fail

### ISSUE THREAD

**Issue by ericsciple** [PowerShell/PowerShell#12823]
The third time a child process prints to STDERR causes pwsh to fail when using the `windows-latest` runners on GitHub Actions.

The script stops execution and pwsh returns exit code 1.

Note, [the runner prepends `$erroractionpreference='stop'`](https://github.com/actions/runner/blob/11435857e4cd9795fa5ee68c20b674e5f96052ab/src/Runner.Worker/Handlers/ScriptHandlerHelpers.cs#L57) which may help explain why execution halts. Although does not explain why the third line STDERR line causes an issue.

Using pwsh 7.0.1

# Steps to reproduce

[Here is the small repro](https://github.com/ericsciple/testing/blob/179117882d8f9d1a17076a771fdc46ad376ce710/.github/workflows/main.yml) on GitHub Actions

[Here are the logs](https://github.com/ericsciple/testing/actions/runs/117482086) from the failed run

What is strange, is it succeeds for me when using a self hosted runner. Both machines are using pwsh 7.0.1

Is there any way to turn on diagnostic logging for pwsh? Also could try a private build with additional logging. The runner uses pwsh from the PATH, so would just need to download it during the workflow-run, extract, and add it to the PATH using [this runner command](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)

# Expected behavior

```none
hello 
world 
aaaa 
bbbb 
cccc 
```

# Actual behavior

```none
hello 
world 
aaaa 
##[error]Process completed with exit code 1.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ericsciple** [comment]
Also this sounds very similar to issue https://github.com/PowerShell/PowerShell/issues/11036 which also doesn't repro on my self-hosted runner. Didnt try on the hosted runner, but guess would probably repro.

**Comment by ericsciple** [comment]
Related to this [github community issue](https://github.community/t/powershell-steps-fail-nondeterministically/115496)

**Comment by iSazonov** [comment]
I don't know how to investigate this issue as it requires debugging in the GitHub Action environment.
Perhaps it is related to how PowerShell works with native command redirections.
I see you found a workaround so I close the issue. We can reopen if there will be a simple repro.
