### ISSUE TITLE
 CreateFile() Error: 5 after open powershell

### ISSUE THREAD

**Issue by flying1020** [PowerShell/PowerShell#12831]
CreateFile() Error: 5

![图片](https://user-images.githubusercontent.com/14899806/83209010-c8392080-a189-11ea-94dd-b40dc0661079.png)

**Comment by mklement0** [comment]
There's not enough information to diagnose your problem. In general, please fill in the issue template as provided.

**Comment by vexx32** [comment]
Windows PowerShell is not maintained in this repository. Please file a ticket with UserVoice or consult with community forums for assistance. 🙂

**Comment by flying1020** [comment]
updated, see:#12859
