### ISSUE TITLE
'Start-Process powershell.exe' from Powershell 7 produces an error message related to PSReadline

### ISSUE THREAD

**Issue by wsy** [PowerShell/PowerShell#12838]
# Steps to reproduce
Open Powershell 7 and then:
```powershell
Start-Process powershell.exe
```

# Expected behavior
Another window is created with Windows Powershell

# Actual behavior
Another window is created. But Windows Powershell is giving out an error message
```none
Cannot load PSReadline module. Console is running without PSReadline
```
![image](https://user-images.githubusercontent.com/2684991/83279938-75527e00-a208-11ea-88d3-92f66a6c56a7.png)

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by byyxx128** [comment]
Reproduced on my laptop with 7.1.0-preview.3 and Version 2004 of Windows 10.

**Comment by byyxx128** [comment]
Reproduced on my laptop with 7.1.0-preview.3 and Version 2004 (Build 19041) of Windows 10.

**Comment by iSazonov** [comment]
Perhaps it is PSModulePath issue.

**Comment by wsy** [comment]
![image](https://user-images.githubusercontent.com/2684991/84151971-a51a4500-aa96-11ea-8a4d-55994acd98f5.png)
Actually this happens only when I type
```
start powershell
```
Also I checked "PSModulePath", they're indeed different.

**Comment by iSazonov** [comment]
Perhaps the issue is with PSModulePath.
/cc @SteveL-MSFT @daxian-dbw
