### ISSUE TITLE
Ctrl + w can not delete a word, instead of, ^w.

### ISSUE THREAD

**Issue by flying1020** [PowerShell/PowerShell#12837]
# Steps to reproduce

```powershell
1. type a word: hello
2. type ctrl + w
```

# Expected behavior
the world hello should be deleted.
```none

```

# Actual behavior
ctrl + w -> ^w
```none

```
![图片](https://user-images.githubusercontent.com/14899806/83253973-82f40d80-a1e0-11ea-8fca-39cd79072cd1.png)

# Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by vexx32** [comment]
@flying1020 please provide environment data as mentioned in the issue template. 🙂 

Can you also test whether the same occurs if you unload PSReadLine? (`Remove-Module PSReadLine` and re-test).

Thanks! 😊

**Comment by flying1020** [comment]
> 
> 
> Can you also test whether the same occurs if you unload PSReadLine? (`Remove-Module PSReadLine` and re-test).
> 
> Thanks! 😊
Environment data has updated, thinks for your help.

Nothing chenged after run `Remove-Module PSReadLine` (ctrl + w still does not work as expected).

**Comment by vexx32** [comment]
Not sure what's really going on there, but PS 5.1 isn't maintained in this repo; you might be better off asking on one of the community channels ([Slack](//aka.ms/psslack)/[Discord](//aka.ms/psdiscord)).

If I had to guess, I'd say that probably the shortcut you're using isn't supported by the terminal you're running PowerShell in -- the fact that the behaviour is the same with and without PSReadLine indicates that none of PS's usual input handling is affecting it whatsoever and most likely the terminal is intercepting the chord instead.

Are you running in Windows Terminal?

**Comment by flying1020** [comment]
@vexx32 I install Powershell 7.1 again just now, The ctrl + w is work as expectly.
The Powershell which has problem version is “WindowsPowershell”，it is build in win10 system. 
Is 'WindowsPowershell' and 'Powershell' are not the same project? I never known this before.
