### ISSUE TITLE
WindowsIdentity.Impersonate Method missing

### ISSUE THREAD

**Issue by andreasgottwald** [PowerShell/PowerShell#12836]
Hey Guys, 

I just installed both PS 7.0.1 LTS and 7.1.0 RC for testing my scripts against those versions.
First thing I had to notice is the absence of the WindowsIdenity.Impersonate Method. I know you guys are building PS on top of the .net Core - but is it on purpose you left out impersonate?

-->

# Steps to reproduce

```powershell, 
add new-object System.Security.Principal.WindowsIdentity
Try to run .impersonate() 
```

# Expected behavior

```
No error, 7.0 is supposed to be backward compatible.
```

# Actual behavior

```
Unhandled error: Method invocation failed because [System.Security.Principal.WindowsIdentity] does not contain a method named 'Impersonate'.
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by KalleOlaviNiemitalo** [comment]
[WindowsIdentity.RunImpersonated](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=netcore-3.1) seems to be the replacement; see <https://github.com/dotnet/runtime/issues/35389> and <https://github.com/dotnet/runtime/issues/20647#issuecomment-454860914>.

Be careful to get the first argument from the WindowsIdentity.AccessToken property rather than WindowsIdentity.Token, which returns an IntPtr and can cause the token handle to be closed too early if PowerShell helpfully converts the IntPtr to a SafeAccessTokenHandle.

**Comment by andreasgottwald** [comment]
> 
> 
> [WindowsIdentity.RunImpersonated](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=netcore-3.1) seems to be the replacement; see [dotnet/runtime#35389](https://github.com/dotnet/runtime/issues/35389) and [dotnet/runtime#20647 (comment)](https://github.com/dotnet/runtime/issues/20647#issuecomment-454860914).
> 
> Be careful to get the first argument from the WindowsIdentity.AccessToken property rather than WindowsIdentity.Token, which returns an IntPtr and can cause the token handle to be closed too early if PowerShell helpfully converts the IntPtr to a SafeAccessTokenHandle.

The problem with this is, that you can only call SafeAccessTokenHandle in PS7 - but not before. So using this script on several thousand computers at the same time is nearly impossible. OK - making a workaround with a second import shouldn't be that much trouble, but it's inconvenient, that it is not compatible.

Thank you for your fast reply, Kalle :)

**Comment by KalleOlaviNiemitalo** [comment]
> The problem with this is, that you can only call SafeAccessTokenHandle in PS7 - but not before.

WindowsIdentity.RunImpersonated seems to be working OK on Windows PowerShell 5.1 with .NET Framework 4.8:

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\> Set-StrictMode -Version 5.1
PS C:\> $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
PS C:\> [System.Security.Principal.WindowsIdentity]::RunImpersonated($identity.AccessToken, {})
```

According to [Windows PowerShell System Requirements](<https://docs.microsoft.com/powershell/scripting/windows-powershell/install/windows-powershell-system-requirements?view=powershell-5.1#microsoft-net-framework-requirements> "Windows PowerShell System Requirements - PowerShell | Microsoft Docs"), Windows PowerShell 5.1 requires .NET Framework 4.5. The [WindowsIdentity.RunImpersonated](<https://docs.microsoft.com/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=netframework-4.6> "WindowsIdentity.RunImpersonated Method (System.Security.Principal) | Microsoft Docs") methods were added in .NET Framework 4.6, so I suppose you cannot rely on them being available on infrequently-updated computers. .NET Framework 4.5.2 on Windows Server 2012 or 2012 R2 seems to remain supported for few years still.
