### ISSUE TITLE
Feature Request: ConvertTo-HashTableLookup

### ISSUE THREAD

**Issue by NoMoreFood** [PowerShell/PowerShell#12835]
# Summary of the new feature/enhancement

A simple cmdlet to create a hash table (indexed lookup) for an array objects with properties.  While simple to do in code, it is a pattern I often find myself repeating over and over again in code and could probably be further enhanced by being built-in.

The general idea here is I have large array of objects with properties many of which are unique.  For example, all uses from an Active Directory forest.  Now let's say I have some SQL database that provides a user's user principal name and I need to lookup some other property of the user.  So, the lazy mans way of doing this might be find the users by doing:

```
ForEach ($Row in $Rows)
{
   $UserData = $AllUsers | Where-Object { $_.UserPrincipalName -eq $Row.User }
   Write-Host $UserData.SamAccountName
}
```

For these scenarios, I often find myself using a simple pattern of creating a hash-based index for reuse: 

```
$UserHash = @{}
$AllUsers | ForEach-Object { $UserHash[$_.UserPrincipalName] = $_ }
ForEach ($Row in $Rows)
{
   Write-Host $UserHash[$Row.User].SamAccountName
}
```
This change can often result in 100x performance improvement for sufficiently large datasets.  

If somebody is already aware of a better way to do this using current cmdlets, please educate me accordingly.

# Proposed technical implementation details

While it only takes two lines to implement this pattern, it would be more readable (and potentially higher performing) if we could avoid the need for a script block and wrap it into something more readable like:

```
$UserHash = ConvertTo-HashTableLookup -InputObject $Array -Property 'HashKeyProperty'
```
Given my perceived simplicity of this, I would be more than happy to work on it.

**Comment by SeeminglyScience** [comment]
I believe this is what you're looking for:

```powershell
$lookup = $AllUsers | Group-Object UserPrincipalName -AsHashTable -AsString
```

**Comment by NoMoreFood** [comment]
@SeeminglyScience Thanks!  I'll close this and reopen if necessary.
