### ISSUE TITLE
Powershell startup performance just slowed down by 10x?

### ISSUE THREAD

**Issue by rtestardi** [PowerShell/PowerShell#12843]
Hi all, again. :-)

Sorry for the mail out of the blue.

We recently switched our beefy appliances (40 logical processors, NVMe, 128GiB RAM) from COSINE build 5B to 6B -- we are on a private branch, so the issue might be limited to us: RS5_RELEASE_SVC_ASDB_PROD1?

And now running the following command takes over two seconds just to launch an empty powershell:

PS C:\Users\Administrator> (measure-command { powershell.exe -command "&{12}" }).totalseconds
2.2435018
PS C:\Users\Administrator> (measure-command { powershell.exe -command "&{12}" }).totalseconds
2.2792461
PS C:\Users\Administrator> (measure-command { powershell.exe -command "&{12}" }).totalseconds
2.2730729

Older builds were 10x faster:

PS C:\Users\Administrator> (measure-command { powershell.exe -command "&{12}" }).totalseconds
0.1868931
PS C:\Users\Administrator> (measure-command { powershell.exe -command "&{12}" }).totalseconds
0.2052852
PS C:\Users\Administrator> (measure-command { powershell.exe -command "&{12}" }).totalseconds
0.1922806

Our current OS build is:

$Script:Rs5SvcBaseDevBinaryImageBranch = "RS5_RELEASE_SVC_ASDB_PROD1"
$Script:Rs5SvcBaseDevBinaryImageBuild = "17763.10153.200514-1750"

You can remote powershell into this system (e-mail richardt) and try it for yourself.

Would you have any suggestion how to track this?

I've taken precise xperf traces, but nothing has jumped out at me -- trace is here: "\\redmond\wsscfs\Foundata\vpetter\logs\richardt\profile.cswitch2.etl"

The whole system is just idle, waiting.

If it is a clue, setting parent powershell affinity to one core makes the time almost double -- and still, the whole system is idle.

-- Rich

**Comment by iSazonov** [comment]
The repo is only for PowerShell Core developers. To report Windows PowerShell issues you should use other channels like Windows Feedback tool, MSFT forums, UserVoice site.
