### ISSUE TITLE
Refresh and enable the 'ComBinder' code in PowerShell

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#12842]
The support for `dynamic` and `ComBinder` was added by https://github.com/dotnet/runtime/pull/33060 and shipped in .NET 5 preview.2.
We should refresh the code under `src\System.Management.Automation\engine\ComInterop` with the code from [dotnet/runtime](https://github.com/dotnet/runtime/tree/ac219a0b106b380c7946eb2c6c1f4b182b39e43a/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop) and enable `ComBnder` code path in our binders.

`ComBinder` will significantly speed up COM interop in PowerShell. See the reference issue: https://github.com/dotnet/runtime/issues/36944

**Comment by skippernl** [comment]
Added a Config file to the onedrive link
.\Fortigate2Excel.ps1" .\PerfTest_20200526_0942.conf
to run the command
