### ISSUE TITLE
Requires statements are ignored when scripts are downloaded via DownloadString

### ISSUE THREAD

**Issue by lextm** [PowerShell/PowerShell#12854]
# Steps to reproduce
In a non-elevated console (either PowerShell 6 or 7) on Windows, run
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/lextm/windowsterminal-shell/master/install.ps1'))
```

# Expected behavior
The script `install.ps1` has two requires statements. Both of them should be enforced.

# Actual behavior
For PowerShell 6 or 7, the requires statements do not take effect. The script is being executed even if the console is not elevated.

This behavior also occurs in PowerShell 5.1.

If the same script is downloaded to local and executed from there, then the requires statements take effect.

# Environment data

```none
PS C:\Users\lextm> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.5
PSEdition                      Core
GitCommitId                    6.2.5
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Given that we generally want to discourage use of `Invoke-Expression` anyway, the better solution may be to enhance `Invoke-Command` as described [here](https://github.com/PowerShell/PowerShell/issues/5909#issuecomment-461192202).
