### ISSUE TITLE
Start-Job fails when launching an executable on a custom drive

### ISSUE THREAD

**Issue by Serentty** [PowerShell/PowerShell#12851]
I have ``/mnt/d`` on Linux mapped to drive ``D:`` in PowerShell. If I'm within that drive, and I run a command like:

```
sajb { ./program }
```

I get an error like the following:

```
Set-Location: Cannot find drive. A drive with the name 'D' does not exist.
```

It seems that custom drives are not used for path resolution within the block.

**Comment by vexx32** [comment]
/cc @PaulHigin seems like this has a similar issue as https://github.com/PowerShell/PowerShell/issues/12851

Probably needs to be considered in the same fix, if possible?

**Comment by Serentty** [comment]
@vexx32 The number you wrote there is this exact issue. Did you mean to paste another number?

**Comment by vexx32** [comment]
Oh, huh. Sorry, meant #11033
