### ISSUE TITLE
CreateFile() Error: 5 after open powershell

### ISSUE THREAD

**Issue by XuPengfei-1020** [PowerShell/PowerShell#12859]
# Steps to reproduce

```powershell
Open powershell (or WindowsPowersehll) without admin author.
powershell print :
CreateFile() Error: 5
CreateFile() Error: 5

and pending until entry ctrl+c
```
img:
![图片](https://user-images.githubusercontent.com/14899806/83372599-561a4300-a3f8-11ea-9294-23c74749195d.png)

# Expected behavior

```
no “CreateFile() Error: 5” print
```

# Actual behavior
```
print  CreateFile() Error: 5 
```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

ps：Open cmd without admin author is no such issue. 
Is powershell try creating some file in path which the current user has no write perms after every start?

**Comment by vexx32** [comment]
If you start PowerShell with `-NonInteractive` is the message still printed?

**Comment by jhoneill** [comment]
Error 5 means "access denied". 
It would suggest that the account does not have full read/write access to its profile directory, particularly
~\AppData\Roaming\Microsoft\Windows\PowerShell\
where psreadline tries to create its log.

**Comment by iSazonov** [comment]
procmon utility could help to find a root of the issue.

**Comment by flying1020** [comment]
> 
> 
> If you start PowerShell with `-NonInteractive` is the message still printed?

Error msg still here.
![图片](https://user-images.githubusercontent.com/14899806/83592130-3d429680-a58c-11ea-856f-a2b64d609f14.png)

**Comment by flying1020** [comment]
> 
> 
> Error 5 means "access denied".
> It would suggest that the account does not have full read/write access to its profile directory, particularly
> ~\AppData\Roaming\Microsoft\Windows\PowerShell
> where psreadline tries to create its log.

Current user has all access for `~\AppData\Roaming\Microsoft\Windows\PowerShell`.
![图片](https://user-images.githubusercontent.com/14899806/83592263-885ca980-a58c-11ea-84c7-346df60f6355.png)

And PSReadLine can write file for record history command in `AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine` normally. It seems like is not access issue of `AppData\Roaming\Microsoft\Windows\PowerShell\`, I konw `CreateFile() Error 5` means write access issue, but would other path?

![图片](https://user-images.githubusercontent.com/14899806/83592498-0e78f000-a58d-11ea-86b8-1313a26291fd.png)

Think you.

**Comment by flying1020** [comment]
> 
> 
> procmon utility could help to find a root of the issue.
Thinks, I will try it.

**Comment by flying1020** [comment]
> 
> 
> procmon utility could help to find a root of the issue.

300+ 'CreateFile' operator which result is not 'success', nothing valuable found.

PS：Why powershell needs read or write so many files on startup? And those files are distributed everywhere (driver C, D, E，many directory seems like no relationship with powershell).
[Logfile.zip](https://github.com/PowerShell/PowerShell/files/4741296/Logfile.zip)

**Comment by flying1020** [comment]
Can anyone help me?

**Comment by iSazonov** [comment]
Log file you shared is not full.

**Comment by flying1020** [comment]
So, what should I do？
again：
Why powershell needs read or write so many files on startup? And those files are distributed everywhere (driver C, D, E，many directory seems like no relationship with powershell).

**Comment by iSazonov** [comment]
@flying1020 The issue you report is _specific_ for your system. ProcMon is better utility for diagnostic in the case. If PowerShell creates objects it creates its in user temp folder - perhaps you limited a write access to the temp folder. Also it could be a registry key.

> Why powershell needs read or write so many files on startup?

You should be more concrete. By design PowerShell does nothing but the necessary.
You could look your PATH and PSModulePath environment variables - PowerShell uses its to discover modules and others.

**Comment by flying1020** [comment]
The problem still here after re-install operator system. Could it be caused by the current user is offline account?

Thinks.

**Comment by wujiyoung** [comment]
@flying1020 Do you solve this ? I have the same problem.

**Comment by flying1020** [comment]
@wujiyoung Not yet, Is your win10 user is offline also?

**Comment by wujiyoung** [comment]
Yes, it came out yesterday, while before that everything was ok.

**Comment by flying1020** [comment]
Here is bug! no doubt.

**Comment by liyueyi** [comment]
Hi all,
Is this problem resovled ?  I have same issue.

**Comment by iSazonov** [comment]
@lilyfang We need repo steps to find a root of the issue. Or you could investigate the issue locally and report what file PowerShell can not create.

**Comment by liyueyi** [comment]
Looks like each command of Powershell will reprot this error message, but the command execluted successfully.

![图片](https://user-images.githubusercontent.com/16708730/97398775-bae5b500-1926-11eb-9105-bf3d4cfa781c.png)

**Comment by iSazonov** [comment]
@liyueyi You could run procmon to find the file with access denied.

**Comment by liyueyi** [comment]
@iSazonov 
I guess the root cause is below event,  it only occured on user process,  can`t see it when i run powershell as administrator.
```
15:39:33.8227604	pwsh.exe	12632	CreateFile	C:\Users\liyy\:docId	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
15:39:33.8229056	pwsh.exe	12632	CreateFile	C:\Users\liyy\:isDelay	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
15:39:33.8229998	pwsh.exe	12632	CreateFile	C:\Users\liyy\:status	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
15:39:33.8231458	pwsh.exe	12632	CreateFile	C:\Users\liyy\:isDelay	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
```

**Comment by jhoneill** [comment]
Really basic question. 
What are the environment variables homeDrive, homePath, and userprofile set to ? Is there a stray ":" in any of them ?

**Comment by liyueyi** [comment]
> 
> 
> Really basic question.
> What are the environment variables homeDrive, homePath, and userprofile set to ? Is there a stray ":" in any of them ?

No, this issue only happened in user mode powershell,  therer is no error message when run powershell as administrator, i just checked user enviroment variables.

BTW, I`m not farmiliar with Windows programing, but i really thought "isDelay", "docID" looks like a function name or a variable name.

**Comment by iSazonov** [comment]
You could run `pwsh -NoProfile`
If the issue will still present please share `get-module` output.

**Comment by liyueyi** [comment]
```
C:\Users\liyy>pwsh -NoProfile
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

CreateFile() Error: 5
CreateFile() Error: 5
CreateFile() Error: 5
CreateFile() Error: 5
CreateFile() Error: 5
CreateFile() Error: 5
CreateFile() Error: 5
PS C:\Users\liyy> CreateFile() Error: 5
CreateFile() Error: 5

PS C:\Users\liyy> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Script     2.0.4                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

PS C:\Users\liyy>
```

**Comment by iSazonov** [comment]
What is Get-Error returns?

Have you Anaconda3 installed?

**Comment by liyueyi** [comment]
Get-Error return NULL.
I haven't installed Anaconda3.

**Comment by iSazonov** [comment]
Only suggestion is to build pwsh locally and run debugger.

**Comment by liyueyi** [comment]
:sweat:

**Comment by frostnotfall** [comment]
After installed win10 2009 ，I found this issue

**Comment by liyueyi** [comment]
Finally, I disabled UAC to workaround this issue.

**Comment by shamork** [comment]
I encountered this problem after deleted *.log and *.dmp file in C:\
Run any app affected use Administrator will fix it.
I did not figure out which file caused this problem.

**Comment by oearhp** [comment]
Hi @flying1020 , have you fixed it yet?

**Comment by zxyao145** [comment]
I have the same problem. And when the system starts at the beginning, this problem will not occur. But when the system runs for about one minute, it appears. It have only two modules:

```
Manifest   7.0.0.0               Microsoft.PowerShell.Utility    
Script     2.1.0                 PSReadLine
```

I tried PowerShell V5.1 from the system and pwsh v7.1.3 from GitHub. `pwsh -NonInteractive` works normally, but powershell doesn't work.

I think there should be some application conflict, but I don't know how to find it. Can anyone offer any advice?

**Comment by lone-wolf-akela** [comment]
> I have the same problem. And when the system starts at the beginning, this problem will not occur. But when the system runs for about one minute, it appears. It have only two modules:
> 
> ```
> Manifest   7.0.0.0               Microsoft.PowerShell.Utility    
> Script     2.1.0                 PSReadLine
> ```
> 
> I tried PowerShell V5.1 from the system and pwsh v7.1.3 from GitHub. `pwsh -NonInteractive` works normally, but powershell doesn't work.
> 
> I think there should be some application conflict, but I don't know how to find it. Can anyone offer any advice?

I'm not sure but it seems that many of those who have got this bug are Chinese people…… I suspect it has something to do with some software many Chinese people (or Chinese company, if you are using a Computer provided by your company) use...

**Comment by zxyao145** [comment]
> I'm not sure but it seems that many of those who have got this bug are Chinese people…… I suspect it has something to do with some software many Chinese people (or Chinese company, if you are using a computer provided by your company) use...

You are probably right, maybe the company has installed some software. This problem never appears on my personal computer, but it will appear on the company's computer.

**Comment by lone-wolf-akela** [comment]
> > I'm not sure but it seems that many of those who have got this bug are Chinese people…… I suspect it has something to do with some software many Chinese people (or Chinese company, if you are using a computer provided by your company) use...
> 
> You are probably right, maybe the company has installed some software. This problem never appears on my personal computer, but it will appear on the company's computer.

Yeah, I too only got this bug on my company's computer.

**Comment by flying1020** [comment]
> Hi @flying1020 , have you fixed it yet?

No, but used to going with it.
