### ISSUE TITLE
Cannot see/find WSL in system32

### ISSUE THREAD

**Issue by RefusesNames** [PowerShell/PowerShell#12857]
# Steps to reproduce
1. Upgrade Windows 10 to version 2004
2. Install WSL 2

```powershell
cd C:\Windows\System32
ls
```
or
```powershell
wsl
```

# Expected behavior

```none
See the all files (specifically, wsl.exe is missing)
```
or
```none
wsl starts
```

# Actual behavior

```none
wsl is missing
```
or
```none
wsl: The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Additional Info
- WSL is indeed installed
- WSL can be seen in the explorer
- I can call `wsl` from `cmd.exe`
- WSL can be found in PowerShell (the pre-installed one on Windows, `ls` and `wsl` works)

**Comment by vexx32** [comment]
Try calling wsl with `./wsl` -- PowerShell doesn't let you call executables from the current directory without qualifying them, unless they happen to be on the PATH.

**Comment by xtqqczze** [comment]
@RefusesNames Please update to [7.1.0-preview.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.3) and then confirm the output of the following commands:
* `$env:PATH -split ';'`
* `cmd /C dir C:\Windows\System32\wsl.exe /B`

**Comment by lukeb1961** [comment]
just fyi this does work for me, with Preview-2 on 19635. What does your PATH look like?

**Comment by RefusesNames** [comment]
> @RefusesNames Please update to [7.1.0-preview.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.3) and then confirm the output of the following commands:
> 
> * `$env:PATH -split ';'`
> * `cmd /C dir C:\Windows\System32\wsl.exe /B`

I can confirm, that updating solved the problem. 

@lukeb1961 `C:\Windows\System32` was in my `PATH` (as it should always be, otherwise you run into way bigger problems)

**Comment by Fendse** [comment]
I encountered the same issue just recently, as well as a possibly-related issue where some `.lnk` files would fail to open. In my case, the issue was that I had installed the x86 version of Powershell instead of the x64 one (which works fine).
Perhaps running the wrong installer should show the user some kind of warning?
