### ISSUE TITLE
Not compatible with utf8 script

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12867]
# Steps to reproduce

```powershell
icm -sess xx utf8.ps1
```

# Expected behavior

```none
ok
```

# Actual behavior

```none
error
```

# Environment data

```none
linux ps7.1 to win 7.1
```
It recognizes the code as ascii,Errors with non-ascii characters will occur.

**Comment by iSazonov** [comment]
Close as stale issue without clean repro steps.
