### ISSUE TITLE
Add ability to export pushd helpers from modules

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#12868]
# Summary of the new feature/enhancement

Suppose you want to write a handy "goto" helper function, which acts as a helper to set your current working directory. Ideally your helper would use `pushd` (`Push-Location`), but it cannot, because `pushd` in a module will use a separate, module-scoped location stack. There is currently no way (that I know of) to access the user's global location stack from a module. (The only way to have such a helper currently is to have code in your $profile.)

# Proposed technical implementation details

I haven't put a ton of thought into this, but an easy way to do this would be to introduce a new parameter to `Push-Location`: `-GlobalStack`.

**Comment by SeeminglyScience** [comment]
You can use this:

```powershell
# Push/pop
$PSCmdlet.SessionState.Path.PushCurrentLocation('')
$PSCmdlet.SessionState.Path.PopLocation('')

# Examine stack
$PSCmdlet.SessionState.Path.LocationStack('')
```

The `SessionState` property reflects the *caller's* session state.  Also an empty string is the name of the default location stack.

**Comment by jazzdelightsme** [comment]
Thank you @SeeminglyScience! This has been a perennial annoyance for me; I'm so glad to have a way to do it!
