### ISSUE TITLE
Unrecognized encoding

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#12861]
# Steps to reproduce

```powershell
$a=@'
ascii.txt
unicode.txt
utf32.txt
utf8.txt
utf8bom.txt
'@ -split "\s"
$url='https://raw.githubusercontent.com/he852100/111/master/Test/'
$a|%{"$((irm $url$_) -split '\s' -match '.')`t$_"}
```

# Expected behavior

```none
123456你好    ascii.txt
123456你好    unicode.txt
123456你好    utf32.txt
123456你好    utf8.txt
123456你好    utf8bom.txt
```

# Actual behavior

```none
123456??        ascii.txt
��123456`O}Y    unicode.txt
��123456`O}Y    utf32.txt
123456你好      utf8.txt
﻿(bom)123456你好     utf8bom.txt
```

# Environment data

```none
PSVersion                      7.1.0-daily.20200530
PSEdition                      Core
GitCommitId                    7.1.0-daily.20200530
OS                             Linux 4.9.112-perf #1 SMP PREEMPT Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Detecting `charset=xxx` has no purpose

Assuming it is a `ps1`, it will have serious compatibility issues

**Comment by mklement0** [comment]
To clarify the problem: the responses all indicate UTF-8 via the `charset` attribute in the `Content-Type` header field, but the actual payloads (file content) are differently encoded, but indicate their specific encoding with a BOM.

Currently, PowerShell only considers the `charset`-specified encoding (in whose absence it currently assumes ISO-88591-), and ignores the BOM (even reading it _as data_).

Arguably, a BOM in the payload, if present, should take precedence over the `charset` attribute. 
See https://github.com/PowerShell/PowerShell/issues/11547#issuecomment-637034379.
