### ISSUE TITLE
$MaximumErrorCount or equivalent mechanism needed.

### ISSUE THREAD

**Issue by GFoxHub** [PowerShell/PowerShell#12860]
I was load testing some PowerShell code that uses a background runspace to ship all the errors that have been written to $Error. I ran into the 256 item limit. I struggled to figure out why the $MaximumErrorCount variable mentioned in several articles wasn't working until I tried going back to PowerShell 5.1. After realizing it was just broken after Powershell 5.1 I adjusted my web search and found this thread.

Paul clearly calls out the issue of backward compatibility and avoiding an unnecessary limitation. Instead a decision was made based on a faulty argument that removing functionality isn't an issue of backward compatibility and also on not "seeing folks using it".

Regarding this change being made three years ago, I would suggest that people aren't noticing until now because their migration to .Net-Core-Based PowerShell has been delayed potentially due to issues like this.

Please reinstate the ability to increase the MaximumErrorCount because people need it, it had already been implemented practically, and there cases when it is preferable to using -ErrorVariable or clearing the $Error variable as it fills up.

See previous thread:
https://github.com/PowerShell/PowerShell/pull/2363

# Steps to reproduce

```
$MaximumErrorCount = 10000

for ($item = 0; $item -lt 1000; $item++)
{
    1/0
}

$error.count

```

# Expected behavior

```
Output: 1000
```

# Actual behavior

```
Output: 256

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Config variables are hard to find. I believe it is better to add new config option in powershell.config.json.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, it appears that this was originally removed intentionally as a search of scripts using this variable didn't turn up results.  However, we understand this is likely only used for debugging in an interactive session so such a search wouldn't show results.  We agreed that this specific variable should be brought back, but not a priority so leaving it as up-for-grabs.
