### ISSUE TITLE
global.json, dev container dockerfile, and .NET SDK Docker Hub version mismatch

### ISSUE THREAD

**Issue by thomasrayner** [PowerShell/PowerShell#12884]
The version of the .NET Core SDK is mismatched between `global.json`, the `dockerfile` for the dev container, and what's actually available on Docker Hub.

* In [global.json](https://github.com/PowerShell/PowerShell/blob/master/global.json#L3) the version required is `5.0.100-preview.5.20279.10`.
* In [the dockerfile for the dev container](https://github.com/PowerShell/PowerShell/blob/master/.devcontainer/Dockerfile#L6) the tag being pulled is `5.0.100-preview.2` which could be easily changed, except...
* The latest tag available on [Docker Hub](https://hub.docker.com/_/microsoft-dotnet-core-sdk) ([Tag List](https://mcrflowprodcentralus.cdn.mscr.io/mcrprod/dotnet/core/sdk?P1=1592249353&P2=1&P3=1&P4=oSOgrflz6FmOlzPhB7sEcexaF%2BxNrsMwbPKtDSILrnA%3D&se=2020-06-15T19%3A29%3A13Z&sig=eyu4fLu5KHQHGywJV23ySloDtL3Th4nduZiCgKvsGwc%3D&sp=r&sr=b&sv=2015-02-21)) appears to be `5.0.100-preview.3`.

This all makes it pretty hard to use the VS Code dev container 😁

**Comment by thomasrayner** [comment]
Updated the initial issue to point to the correct Docker Hub image. Sorry about that.

**Comment by adityapatwardhan** [comment]
I will have a look at this. Thanks for reporting!
