### ISSUE TITLE
Get-Process return closed(stoped) process

### ISSUE THREAD

**Issue by Sidoran** [PowerShell/PowerShell#12880]
## Steps to reproduce

```powershell
$proc = Start-Process notepad++ -PassThru
Get-Process -Id $proc.Id
Stop-Process $proc
get-process -Id $proc.Id
```

## Expected behavior

```none
 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      3     0,56       1,89       0,02    5996   7 notepad++
Get-Process: untitled:Untitled-1:4:1
Line |
   4 |  get-process -Id $proc.Id
     |  ~~~~~~~~~~~~~~~~~~~~
     | Cannot find a process with the process identifier 1598.

```

## Actual behavior

```none
 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      3     0,57       1,86       0,05    5580   7 notepad++
      0     0,00       0,00       0,08    5580

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by vexx32** [comment]
This might just be a timing issue, retrieving the process before it's finished shutting down. Killing a process isn't always instantaneous.

Does it still reproduce if you have a slight wait before calling the final Get-Process?

**Comment by Sidoran** [comment]
This issue are reproduced after a several minutes wait.
```
$proc = Start-Process notepad++ -PassThru
Get-Process -Id $proc.Id
Stop-Process $proc
Start-Sleep 180
get-process -Id $proc.Id
```
Return the same.
On powershell 5.1 everything works fine

**Comment by vexx32** [comment]
Interesting. I'm not seeing the same on MacOS.

Hard to say if this is a PowerShell or a .NET issue... Can you swap the final step for `[System.Diagnostics.Process]::GetProcessById($proc.Id)` and see if you get the same?

We may need to file an issue in the [dotnet](/dotnet/runtime) repository if it still reproduces with only .NET code.

**Comment by Sidoran** [comment]
```
$proc = Start-Process notepad++ -PassThru
Get-Process -Id $proc.Id
Stop-Process $proc
Start-Sleep 180
[System.Diagnostics.Process]::GetProcessById($proc.Id)
```
return the same:
```
 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      3     0,54       1,66       0,08   15536   7 notepad++  
      0     0,00       0,00       0,09   15536     

```
This issue was first found on Windows Server 2012R2

**Comment by vexx32** [comment]
Interesting... [The documentation for the Process class](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=netcore-3.1) mentions that calling `Process.Kill()` is asynchronous, and if you want to wait for a process to fully exit you can check `Process.HasExited` or use `Process.WaitForExit()`

Looking at the Stop-Process cmdlet code, it looks like it will pretty much always just call `Process.Kill()` and move on.

I'm not entirely sure it makes sense for the cmdlet to always wait for each process to exit. It would cause problems if you were passing an array of processes to stop, and a particular process didn't exit, preventing the cmdlet from terminating subsequent processes.

If anything, I'd suggest we enhance `Stop-Process` to support:

- A `-Wait` switch to wait for the process(es) to exit, and
- A `-WaitTimeout` parameter to specify a number of seconds (maybe 3-5 seconds by default?) to wait for process terminations to complete.

The cmdlet can call `Kill()` on all the processes, and then wait in a loop with small sleeps in `EndProcessing()` until either the timeout has elapsed or all processes have exited. If the timeout elapses and some or all processes have not yet terminated, write non-terminating errors for each process that failed to stop.

**Comment by KalleOlaviNiemitalo** [comment]
This is a .NET Core bug, mentioned in <https://github.com/dotnet/runtime/issues/20725#issuecomment-390391489> and presumably caused by <https://github.com/dotnet/corefx/pull/17476>, i.e. between .NET Core 1.1.13 and 2.0.0. On .NET Framework 4.8, `Process.GetProcessById` does not return a process that has already terminated, even if the process object still exists because of process handles.

`Process.UpdateHasExited` uses a zero-duration wait on the process handle to check whether the process has terminated. `ProcessManager.IsProcessRunning` should be changed to do the same.

**Comment by Sidoran** [comment]
I writed a small console app
```
using System;
using System.Diagnostics;
using System.Threading;

namespace ProcessTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Process testproc = Process.Start(@"C:\\Program Files\\Notepad++\notepad++");
            Console.WriteLine($"Started  a new process with ID {testproc.Id}");
            Console.WriteLine($"Get process by id {Process.GetProcessById(testproc.Id).ProcessName}");
            testproc.Kill();
            Console.WriteLine($"Process with Id {testproc.Id} was killed");
            Thread.Sleep(5000);
            try
            {
                Console.WriteLine($"Get process by id {Process.GetProcessById(testproc.Id).ProcessName}");
            }
            catch (Exception e) {
                Console.WriteLine($"GetProcessById filed with Exception: {e.Message}");
            }
        }
    }
}

```
On .Net Core 2.1 and .net core 3.1 i received a next:

Started  a new process with ID 9896
Get process by id notepad++
Process with Id 9896 was killed
GetProcessById filed with Exception: Process has exited, so the requested information is not available.

GetProcessByID works correctly with killed process in actual .net core version.

**Comment by KalleOlaviNiemitalo** [comment]
> ```
> Started  a new process with ID 9896
> Get process by id notepad++
> Process with Id 9896 was killed
> GetProcessById filed with Exception: Process has exited, so the requested information is not available.
> ```

That exception comes from `Process.ProcessName`, not `Process.GetProcessById`.

**Comment by KalleOlaviNiemitalo** [comment]
> So I think it is Windows behavior.

It is Windows behavior that [OpenProcess](<https://docs.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess> "OpenProcess function (processthreadsapi.h) - Win32 apps | Microsoft Docs") can open a process that has already terminated. [Process.GetProcessById](<https://docs.microsoft.com/dotnet/api/system.diagnostics.process.getprocessbyid?view=netstandard-2.0> "Process.GetProcessById Method (System.Diagnostics) | Microsoft Docs") tries to detect that situation and throw `ArgumentException`, but the detection no longer works in .NET Core.

A PowerShell script that uses [Get-Process](<https://docs.microsoft.com/powershell/module/microsoft.powershell.management/get-process?view=powershell-7> "Get-Process") can work around the bug by checking [Process.HasExited](<https://docs.microsoft.com/dotnet/api/system.diagnostics.process.hasexited?view=netstandard-2.0> "Process.HasExited Property (System.Diagnostics) | Microsoft Docs"), which has the correct value. Alternatively, `Get-Process` could be changed to do that.

**Comment by TishSerg** [comment]
Hi. I just stumbled upon this nasty behavior of PowerShell 7.2.3. 
And like in the case of topicstarter:

> On powershell 5.1 everything works fine

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/runtime/issues/63937> was fixed in .NET v7.0.0-preview.3.22175.4. <https://github.com/PowerShell/PowerShell/pull/17061> updated to .NET SDK 7.0.100-preview.4.22252.9. When PowerShell v7.3.0-preview.4 is released, it should include the fix.
