### ISSUE TITLE
PowerShell keyboard shortcuts

### ISSUE THREAD

**Issue by nu8** [PowerShell/PowerShell#12898]
Currently I am using Bash on Windows via MSYS2. I have this file `.inputrc`:

    "\33[1;3A": "cd ..\n"

Whenever I press Alt Up Arrow, it moves to the parent directory. Does PowerShell
have a similar method to map shortcuts?

**Comment by rkeithhill** [comment]
I couldn't get `Alt+UpArrow` to work but this does work.  Put it in your PowerShell profile script:
```
Set-PSReadLineKeyHandler -Key Shift+UpArrow -ScriptBlock { Set-Location .. -ErrorAction Ignore; [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt() }
```

**Comment by nu8** [comment]
Works great! Thank you!
