### ISSUE TITLE
Feature Request: Force stop/remove-job

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PowerShell#12897]
`Stop-Job` can take a long time or forever depending on what you have started. See for example [this](https://stackoverflow.com/questions/19248149/powershell-stop-job-takes-too-long) or [this](https://github.com/Badgerati/Pode/issues/553).

Adding `-Force` should bring it down imediatelly.

`Remove-Job` has force param but it still hangs.

**Comment by NoMoreFood** [comment]
@majkinetor Can you a standalone, easily reproducible example snippet here?

**Comment by Badgerati** [comment]
Hi @NoMoreFood,

I've come across this recently when using Jobs for Sockets/HttpListener. A simple example is:

```powershell
Start-Job -Name Example -ScriptBlock {
    $listener = [System.Net.HttpListener]::new()
    $listener.Prefixes.Add('http://*:80/')
    $listener.Start()
    $listener.GetContext()
}
```

Calling `Stop-Job -Name Example` will just hang forever, or take 5mins+ to stop on some machines. `Remove-Job -Name Example -Force` exhibits the same issue as well.

**Comment by majkinetor** [comment]
Note that this must be executed in admin shell or it will just complete with 'Access denied'. 

Note also that it doesn't only avoid stopping, but also completelly renders Powershell session unusable.
