### ISSUE TITLE
Install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by octos4murai** [PowerShell/PowerShell#12903]
## Steps to reproduce

Follow instructions at https://docs.microsoft.com/en-ca/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#ubuntu-1804.

## Expected behavior

Successful installation

## Actual behavior

```bash
The following packages have unmet dependencies:
 powershell : Depends: libicu55 but it is not installable
```

## Environment data

Fresh installation of Ubuntu 18.04.3 (LTS) x64 on DigitalOcean droplet

**Comment by iSazonov** [comment]
@octos4murai Please share PowerShell versions as requested in the issue template.

**Comment by iSazonov** [comment]
It is .Net dependency https://github.com/dotnet/core/blob/master/Documentation/linux-prereqs.md

**Comment by octos4murai** [comment]
@iSazonov It's my mistake--I was attempting to install the version for Ubuntu 16.04 rather than 18.04.
