### ISSUE TITLE
Assigning Hidden to a file/folder should throw on Linux

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#12901]
On Windows we can set Hidden flag in file/folder attributes.
Since .Net 5.0 this is supported for BSD-like OS-es (MacOS, FreeBSD)
https://manpages.debian.org/buster/freebsd-manpages/chflags.2freebsd.en.html

But it does not work on Linux. Currently PowerShell silently accepts Hidden flag - that is very amazing behavior: if an user sets the flag without error the user expects that the flag really is on the file/folder but it is not.

.Net tracking issue https://github.com/dotnet/runtime/issues/37301

## Steps to reproduce

```powershell
(Get-Item testfile).Attributes = 'Hidden'
```

## Expected behavior

```none
Throw unsupported exception.
```

## Actual behavior

```none
Silently pass but follow check shows that the file/folder has not the Hidden flag.
```

## Environment data

```none
pwsh 7.1 Preview3
```

**Comment by floh96** [comment]
@iSazonov fyi .net issue is fixed

**Comment by iSazonov** [comment]
@floh96 Unfortunately, the problem has not been completely resolved. We will need to learn this again while working on FileSystem Provider v2.
