### ISSUE TITLE
Escape literal Newline

### ISSUE THREAD

**Issue by nu8** [PowerShell/PowerShell#12918]
I must be crazy, but PowerShell seems to have no method to escape literal
newlines. If I do this:

~~~
"Sunday`
Monday"
~~~

The newline remains:

~~~
Sunday
Monday
~~~

Compare with Bash:

~~~
bash-4.4$ echo "Sunday\
> Monday"
SundayMonday
~~~

**Comment by nu8** [comment]
Here is another approach:

~~~
PS C:\> 'Sunday' +
>> 'Monday'
SundayMonday
~~~

**Comment by mklement0** [comment]
Yes, unlike in POSIX-like shells, `` ` `` before a newline doesn't _strip_ the newline from the resulting string. In effect, your use of of `` ` `` is a no-op - from PowerShell's perspective, _you're escaping a character that doesn't need escaping_, so it is retained as-is.

In addition to your `+` solution, you can do things like:

```powershell
-join ('Sunday', 'Monday')
```

```powershell
@'
Sunday
Monday
'@ -replace '\r?\n'
```
