### ISSUE TITLE
Can I decrypt NonInteractive file?

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#12924]
Hello
Can I decrypt StartupProfileData-NonInteractive file?
```
$env:LOCALAPPDATA\Microsoft\PowerShell
```

File Location:
![image](https://user-images.githubusercontent.com/23485114/84122064-1fbe7280-aa4d-11ea-855e-3bc44002eb62.png)

Contents:
![image](https://user-images.githubusercontent.com/23485114/84122277-7166fd00-aa4d-11ea-9727-95a81bb7bf58.png)

Thanks.

**Comment by NoMoreFood** [comment]
At a quick glance, it's not encrypted; it's some binary configuration file.   Looks like this might be the module that parses it:

https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/multicorejit.cpp

**Comment by xmha97** [comment]
> At a quick glance, it's not encrypted; it's some binary configuration file. Looks like this might be the module that parses it:
> 
> https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/multicorejit.cpp
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/9141961?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[dotnet/runtime](https://github.com/dotnet/runtime)**.NET is a cross-platform runtime for cloud, mobile, desktop, and IoT apps. - dotnet/runtime

Is there a tool that can convert the file to an understandable text format such as JSON or XML?

Implementing these codes is difficult.
https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/multicorejit.cpp

**Comment by SeeminglyScience** [comment]
@xmha97 The format for the file is described [here](https://github.com/dotnet/runtime/blob/b8e1a49266199ccfaeb9cce8c2f5952048a4e3b0/src/coreclr/src/vm/multicorejitimpl.h#L71-L96).  It's very unlikely that there is a converter for it since afaik it doesn't really have any uses except optimizing the CLR JIT compiler.  You could write your own reader with some difficulty, but what are you hoping to get out of these files?

**Comment by xmha97** [comment]
Thank @SeeminglyScience 
I hope to get out list all environment variables ($env:) from these files.

**Comment by vexx32** [comment]
Looking at the linked format, it doesn't appear to contain any environment variables, unless I'm missing something?

If you want to list environment variables, you can do:

```ps1
Get-ChildItem Env:
# or
[Environment]::GetEnvironmentVariables()
```

**Comment by xmha97** [comment]
Thank @vexx32 
I closing this issue.
