### ISSUE TITLE
Issues  label:Issue-Question  Uninstall Windows Powershell

### ISSUE THREAD

**Issue by Bamajon1974** [PowerShell/PowerShell#12929]
Does the Powershell included in Windows 10 as well as Powershell ISE versions need to be uninstalled or removed from Windows prior to installing v7? Or can all versions run simultaneously? 

Thanks!

**Comment by vexx32** [comment]
Versions 6 and above can all be installed side-by side with Windows PowerShell. 🙂

**Comment by Bamajon1974** [comment]
Got it. Is there any reason to keep the old versions of Powershell and Powershell ISE installed? I believe they are removed through the turn on/off optional components, right? If I uninstall the old versions in favor of v7, will anything in windows be broken?

**Comment by vexx32** [comment]
Yeah, many windows components are reliant on v5 of PowerShell I'd guess.

I'm not really sure you actually _can_ uninstall it, tbh.

**Comment by Bamajon1974** [comment]
That is exactly what I wanted to know. I will leave the old PowerShell version. Thank you for your help!

**Comment by Bamajon1974** [comment]
Thank you.
