### ISSUE TITLE
Hardlink create do not support  relative path 

### ISSUE THREAD

**Issue by 1349422030** [PowerShell/PowerShell#12922]
example:
when i am in `~\documents\testpath1`
this command `New-Item -Path testfile1 -Type HardLink -Value ..\testpath2\testfile2` will report with error
file tree is like this
```
+---testpath1
|   +---testfile1
+---testpath2
|   +---testfile2
```

**Comment by m1c0l** [comment]
@1349422030 did you resolve the issue? I experienced this as well on PowerShell 7.0.3, trying to create a hardlink with relative path did not work outside of the directory that PowerShell was installed to.

**Comment by 1349422030** [comment]
No, I didn't.
My temporary resolve is to use resolve-path command to transfer relative path to obsolute path


-------- 原始邮件 --------
发件人： Michael Li <notifications@github.com>
日期： 2020年9月26日周六 清晨6:17
收件人： PowerShell/PowerShell <PowerShell@noreply.github.com>
抄送： 1349422030 <l1349422030@outlook.com>, Mention <mention@noreply.github.com>
主 题： Re: [PowerShell/PowerShell] Hardlink create do not support relative path (#12922)

@1349422030<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F1349422030&data=02%7C01%7C%7C042a87ec20e247e304c508d861a0ba36%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637366690225830769&sdata=CuTjsg7jMuCicl1BIGOwc0tgLj49aOBAM2AWYpFmpGQ%3D&reserved=0> did you resolve the issue? I experienced this as well on PowerShell 7.0.3, trying to create a hardlink with relative path did not work outside of the directory that PowerShell was installed to.

**Comment by m1c0l** [comment]
Right, I tested as well that finding and using the absolute path works.
I think you should still reopen this issue so that the PowerShell team can be made aware of it and make a fix 😃
