### ISSUE TITLE
New-Item -ItemType Junction cloud not be visited via explorer

### ISSUE THREAD

**Issue by 1349422030** [PowerShell/PowerShell#12923]
## Steps to reproduce
I use scoop installed megacmd, then
```powershell
New-Item MEGAcmd -Type Junction -Value C:\Users\l1349\scoop\apps\megacmd\current\
```
## Expected behavior
It should be that i can visit this directory via explorer.exe.
And is i use
```cmd
mklink /J MEGAcmd C:\Users\l1349\scoop\apps\megacmd\current\
```
There seems to be no problems.
![image](https://user-images.githubusercontent.com/35253997/84112997-56e85000-aa5c-11ea-9628-22d17c5e87df.png)

## Actual behavior
I found megacmdserver clould not be started, perhaps because 
![image](https://user-images.githubusercontent.com/35253997/84112680-cf024600-aa5b-11ea-87b3-f13813c7e298.png)
## Environment data

```none
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
What id cmd.exe in the case?

**Comment by 1349422030** [comment]
> What id cmd.exe in the case?

both cmd and pwsh can create junction links.
and in this case, the junction created by `mklink /J ...` works, however created by `New-Item -ItemTye Junction ...` do not works very well, i can not visit the junction from explorer.exe
Let me translate the error reported by explorer when visit the junction created by `New-Item -ItemTye Junction ...'
```
C:\Users\l1349\AppData\Local\MEGAcmd is not available. If this location is on this computer, please make sure that the compute or drives are connected, and retry. If is on the internet, please make sure you have connected to the internet, and retry. If still could not visit it, perhaps it has been removed or deleted.
```
but actually i am at this location in pwsh `Set-Location`

**Comment by 1349422030** [comment]
> What id cmd.exe in the case?

er...
simplify my explantions
1、If i create the junction with cmd.exe command
```cmd
mklink /J ...
```
Everything is OK

2、If i create this junction by powershell command
```
New-Item -ItemType Junction ...
```
I can not visit the junction via explorer.exe.

**Comment by NoMoreFood** [comment]
I can not repro this (tried with 7.0.1).  Can you provide a contiguous set of instructions that demonstrates the " is not available" message being returned from Set-Location immediately after junction creation for you?

**Comment by 1349422030** [comment]
> I can not repro this (tried with 7.0.1). Can you provide a contiguous set of instructions that demonstrates the " is not available" message being returned from Set-Location immediately after junction creation for you?

Sure, I'll show you it.
1, I want to use `scoop` to install `megacmd`, so the first is install scoop
```
iwr -useb get.scoop.sh | iex 
```
2. Install `megacmd`
```
scoop install megacmd
```
3. Try `mega-get`,
```
mega-get
```
you will find this message
```
Server not running. Initiating in the background...
Unable to execute: C:\Users\WDAGUtilityAccount\AppData\Local\MEGAcmd\MEGAcmdServer.exe errno = : 3
```
4. So, i try create a junction
: Because I use windows sandbox, so the username is `WDAGUtilityAccount`
```
cd ~\AppData\Local\
New-Item MEGAcmd -ItemType Junction -Value C:\Users\WDAGUtilityAccount\scoop\apps\megacmd\current\
```
5. Finally
```
cd MEGAcmd
ii .
```
![image](https://user-images.githubusercontent.com/35253997/84140054-924a4500-aa83-11ea-8277-b41d3cf7ac9c.png)


I have tried both `powershell-core 7.0.1` and `powershell-core 7.1.preview3`, they have the same problem.
But `Windows PowerShell 5.1` works fine

**Comment by NoMoreFood** [comment]
When you look at the new junction using cmd.exe and `dir`, how does the junction look with PowerShell 7 versus 5.1?  

```
C:\Users\Admin\AppData\Local>dir MEGA*
 Volume in drive C has no label.
 Volume Serial Number is 9498-E773

 Directory of C:\Users\Admin\AppData\Local

06/09/2020  07:33 AM    <JUNCTION>     MEGAcmd [\??\C:\Users\WDAGUtilityAccount\scoop\apps\megacmd\current\]
               0 File(s)              0 bytes
               1 Dir(s)  280,694,636,544 bytes free
```

**Comment by 1349422030** [comment]
> When you look at the new junction using cmd.exe and `dir`, how does the junction look with PowerShell 7 versus 5.1?
> 
> ```
> C:\Users\Admin\AppData\Local>dir MEGA*
>  Volume in drive C has no label.
>  Volume Serial Number is 9498-E773
> 
>  Directory of C:\Users\Admin\AppData\Local
> 
> 06/09/2020  07:33 AM    <JUNCTION>     MEGAcmd [\??\C:\Users\WDAGUtilityAccount\scoop\apps\megacmd\current\]
>                0 File(s)              0 bytes
>                1 Dir(s)  280,694,636,544 bytes free
> ```

`PowerShell 7`
```
➜  Local $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


➜  Local dir -Filter mega*

    Directory:  C:\Users\l1349\AppData\Local

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
la---          2020/6/9     19:41        1   MEGAcmd -> C:\Users\l1349\scoop\apps\megacmd\current\

➜  Local
```

`PowerShell 5`
```
➜  Local $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



➜  Local dir -Filter mega*

➜  Local
```

`cmd`
```
C:\Users\l1349\AppData\Local>dir mega*
 Volume in drive C is OS
 Volume Serial Number is 3840-ADFF

 Directory of C:\Users\l1349\AppData\Local

File Not Found
```
