### ISSUE TITLE
Test-Connection test setup fails on macOS due to DNS issue

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#12935]
From the test output:

```
  Describing Test-Connection
    [-] Error occurred in Describe block 0ms
      ExtendedSocketException: nodename nor servname provided, or not known
      MethodInvocationException: Exception calling "GetHostEntry" with "1" argument(s): "nodename nor servname provided, or not known"
      at <ScriptBlock>, /Users/runner/runners/2.170.1/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 15
      at Invoke-Blocks, /Users/runner/runners/2.170.1/work/1/a/bins/publish/Modules/Pester/4.10.1/Functions/SetupTeardown.ps1: line 135
      at Invoke-TestGroupSetupBlocks, /Users/runner/runners/2.170.1/work/1/a/bins/publish/Modules/Pester/4.10.1/Functions/SetupTeardown.ps1: line 121
      at DescribeImpl, /Users/runner/runners/2.170.1/work/1/a/bins/publish/Modules/Pester/4.10.1/Functions/Describe.ps1: line 209
```

Based on https://github.com/dotnet/runtime/issues/29780#issuecomment-499084660, this seems to be a DNS resolution issue, and seems to be common on macOS.

I don't know enough about these tests or networking configuration to be a good judge of whether we should try to fix this or how, but want to discuss here if possible.

In particular:

- Is this something we think we could fix or workaround in our code? The `Test-Connection` tests on macOS seem to have been flaky for some time.
- Do we think there's some way we could improve the way the CI instance is configured to mitigate?
- Otherwise, is there some other way we could perform test setup here that wouldn't hit this issue? Or possibly we could identify when we've hit this issue and handle it somehow?

/cc @JamesWTruher @SteveL-MSFT @iSazonov

**Comment by iSazonov** [comment]
We have a tracking issue here and in .Net Runtime repository. Can PowerShell team ping .Net team to fix the API? It is absolutely impossible to use the API on Unix-s _for years_. If they can not fix in .Net 5.0 maybe we switch to an alternative library to get Test-Connection working on Unix-s?

**Comment by rjmholt** [comment]
Looks like this is continuing to occur

**Comment by rjmholt** [comment]
Relevant code:

https://github.com/PowerShell/PowerShell/blob/ec20043a91ebb58e7e208630c5ef38f2af69e7e4/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1#L8-L15

**Comment by iSazonov** [comment]
Maybe MacOS image was updated?

**Comment by vexx32** [comment]
Yeah, this wasn't happening when this code was introduced. Something appears to have changed there, for sure. 🤔

**Comment by rjmholt** [comment]
Two possibilities I see:

- the macOS host configuration has changed
- we've taken a regression in .NET

**Comment by iSazonov** [comment]
We don't update .Net in last days.

**Comment by rjmholt** [comment]
Opened https://github.com/dotnet/runtime/issues/37766, since `ifconfig` is succeeding when .NET fails.

**Comment by rjmholt** [comment]
Looks like we might be able to attribute this to https://github.com/dotnet/runtime/issues/36849

**Comment by rjmholt** [comment]
Testing in my PR indicates that `nslookup` also fails on macOS, meaning this issue is external to macOS

**Comment by rjmholt** [comment]
Opened https://github.com/actions/virtual-environments/issues/1042

**Comment by iSazonov** [comment]
Will we track actions/virtual-environments#1042 here?
