### ISSUE TITLE
Distribution Support Request: Alpine 3.11 arm32

### ISSUE THREAD

**Issue by pedropombeiro** [PowerShell/PowerShell#12938]
## Details of the Distribution

- Name of the Distribution: Alpine
- Version of the Distribution: 3.11
- Package Types
    - [ ] Deb
    - [ ] RPM
    - [x] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request): arm32
- [ ] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker: https://github.com/PowerShell/PowerShell-Docker/issues/444
- The following is a requirement for supporting a distribution **without exception.**
    - [ ] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by iSazonov** [comment]
I don't see Arm32 support in .Net 5.0 https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md

**Comment by TravisEz13** [comment]
As @iSazonov  mentioned, this is not supported by .NET.   
https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md?rgh-link-date=2020-06-11T09%3A08%3A49Z
![image](https://user-images.githubusercontent.com/10873629/84828310-b73a3d00-afda-11ea-944a-fb00d8cbda40.png)
