### ISSUE TITLE
Distribution Support Request: Alpine 3.11 arm64

### ISSUE THREAD

**Issue by pedropombeiro** [PowerShell/PowerShell#12937]
## Details of the Distribution

- Name of the Distribution: Alpine
- Version of the Distribution: 3.11
- Package Types
    - [ ] Deb
    - [ ] RPM
    - [x] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request): arm64
- [x] **Required** - An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker: https://github.com/PowerShell/PowerShell-Docker/issues/443
- The following is a requirement for supporting a distribution **without exception.**
    - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://endoflife.date/alpine) or equivalent.

## Progress - For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by iSazonov** [comment]
You can request for next version based on .Net 5.0 https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md

Also why do you reference Ubuntu for life support cycle?

**Comment by pedropombeiro** [comment]
> Also why do you reference Ubuntu for life support cycle?

Not aware of that, what makes you say that?

**Comment by iSazonov** [comment]
> The version of the Distribution is not an interim release or equivalent.

This contains a link to Ubuntu site.

**Comment by pedropombeiro** [comment]
> This contains a link to Ubuntu site.

That is part of the issue template, I didn't change that.

**Comment by iSazonov** [comment]
Please add a link to Alpine support cycle.

**Comment by TravisEz13** [comment]
https://endoflife.date/alpine

**Comment by TravisEz13** [comment]
@adityapatwardhan Please investigate the work to get the native components working in this scenario.

**Comment by panekj** [comment]
@TravisEz13 can you tell what is currently lacking to progress this and https://github.com/PowerShell/PowerShell/issues/14667?
I've cross-compiled PowerShell to Alpine arm64 and was able to build it natively. Maybe I could help speed up some tasks.
https://github.com/panekj/PowerShell/tree/alpine-arm

**Comment by cjbottaro** [comment]
I need an Alpine arm64 build.

@panekj Can you explain how you built it on Alpine arm64? I'd rather just do it myself while waiting for a release.

**Comment by panekj** [comment]
> Can you explain how you built it on Alpine arm64?

> I've cross-compiled PowerShell to Alpine arm64 and was able to build it natively.
