### ISSUE TITLE
Want a natural sorting order when listing files

### ISSUE THREAD

**Issue by phuclv90** [PowerShell/PowerShell#12931]
## Summary of the new feature/enhancement

As a user I want a [natural sorting order](https://en.wikipedia.org/wiki/Natural_sort_order) when listing files like in Windows Explorer. For example when running Get-ChildItem a normal lexicographic sorting order is used

```
PS C:\Users> ls "D:\ppt\slides\*.xml"

    Directory: D:\ppt\slides\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          1/1/1980  12:00 AM           5504 slide1.xml
-a----          1/1/1980  12:00 AM           9709 slide10.xml
-a----          1/1/1980  12:00 AM          21260 slide11.xml
-a----          1/1/1980  12:00 AM          26662 slide2.xml
-a----          1/1/1980  12:00 AM          17179 slide3.xml
-a----          1/1/1980  12:00 AM           2449 slide4.xml
-a----          1/1/1980  12:00 AM           6996 slide5.xml
```

## Proposed technical implementation details (optional)

There's already [StrCmpLogicalW](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strcmplogicalw) for natural sort. I think some new options to Get-ChildItem or Sort-Object would be greate

**Comment by augustoproiete** [comment]
Please re-open this ticket. This still a desired feature

**Comment by zotabee** [comment]
> Please re-open this ticket. This still a desired feature

https://github.com/dotnet/runtime/issues/13979

**Comment by phuclv90** [comment]
@zotabee that one is for .NET, and this one is for PowerShell which will depend on the .NET implementation first
