### ISSUE TITLE
[Question] Latest version

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#12946]
![image](https://user-images.githubusercontent.com/23485114/84451314-fa598080-ac67-11ea-8143-a70770da088c.png)
What is the difference between PowerShell version 6 and version 7?
Which is newer?

**Comment by NoMoreFood** [comment]
They are both maintenance releases.  Use the 7.x series unless you have a reason to use 6.x (e.g., a behavior that broke between 6.x and 7.x).

**Comment by rjmholt** [comment]
As @NoMoreFood says, version 7 is newer. The reason there is a temporally recent release of PS 6 is because the old version receives critical maintenance updates.

You should rely on the semantic version of PowerShell release to indicate its "newness" (in a feature sense).

**Comment by xmha97** [comment]
> 
> 
> As @NoMoreFood says, version 7 is newer. The reason there is a temporally recent release of PS 6 is because the old version receives critical maintenance updates.
> 
> You should rely on the semantic version of PowerShell release to indicate its "newness" (in a feature sense).

OK, Thanks.
