### ISSUE TITLE
Can not connect to new MS365 tenancies with PowerShell on macOS as New-PSSession does not support Modern Authentication

### ISSUE THREAD

**Issue by kai-h** [PowerShell/PowerShell#12947]
I have created a few new tenancies for my clients recently on Microsoft 365 and MFA has been enabled by default on all user accounts within these tenancies.

This is good, it is a lot more secure... However, I now can not connect to these tenancies using New-PSSession as it does not support modern authentication.

To connect to Exchange Online PowerShell using MFA, for example, you need to use the Exchange Online PowerShell V2 module, which is Windows only.

**Comment by daxian-dbw** [comment]
@kai-h Thanks for reporting the issue. I think this should be a feedback to the Exchange Online PowerShell V2 module to ask for cross-plat support. I guess you can start by logging an issue at https://github.com/MicrosoftDocs/office-docs-powershell/issues
