### ISSUE TITLE
Installer of Release 7.0.2 say it's a Preview release

### ISSUE THREAD

**Issue by augustoproiete** [PowerShell/PowerShell#12950]
The [release 7.0.2](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.2) doesn't mention it's a preview version and the tag/version number also doesn't reflect it's a preview (assuming this follows semver): `v7.0.2`.

Am I missing something, or is this a bug?

## Steps to reproduce

Download and run `PowerShell-7.0.2-win-x64.msix` from the 7.0.2 Release

## Expected behavior

Release v7.0.2 to be a stable version

## Actual behavior

![image](https://user-images.githubusercontent.com/177608/84513531-f184a100-ac9f-11ea-8236-a76bbfbe8feb.png)

## Environment data

N/A

**Comment by vexx32** [comment]
Probably a bug in the MSIX packaging. /cc @SteveL-MSFT 

My understanding is that the MSIX package format itself is still a bit on the experimental side until it gets properly published to the Windows Store, hopefully in the next couple versions if not sooner. Still definitely something we should fix, thanks for reporting it! 😊

**Comment by augustoproiete** [comment]
You're welcome.

FYI, I was not able to install the MSIX package. Happy to help troubleshoot (if desired):

![image](https://user-images.githubusercontent.com/177608/84520964-b89df980-acaa-11ea-8721-73e59380cbd6.png)

**Comment by vexx32** [comment]
Yeah, that's a known issue with it as well. The only workaround currently is to use `Add-AppXPackage -Path $msixPath` from an admin (Windows?) PowerShell session to bypass the msix restrictions.

Once the issues are ironed out you would just be able to get it from the Store without hitting any of these issues. 🙂

**Comment by xtqqczze** [comment]
See also: #12681
