### ISSUE TITLE
power update/install via dotnet tool fails.

### ISSUE THREAD

**Issue by ADNewsom09** [PowerShell/PowerShell#12957]
## Steps to reproduce

have powershell 7.0.1 installed as dotnet global tool

`dotnet tool update powershell --global`

PowerShell Failed to create shell shim for tool 'powershell': Command 'pwsh' conflicts with an existing command from another tool. Tool 'powershell' failed to install. 

`pwsh`

 The application to execute does not exist: 'C:\Users\XXX\.dotnet\tools\.store\powershell\7.0.1\powershell\7.0.1\tools\netcoreapp3.1\any\Microsoft.PowerShell.GlobalTool.Shim.dll'. 

## Expected behavior

Powershell should update or at least fail to update without breaking the existing system. It is now in a un-recoverable state.

## Environment data

can't run pwsh any more

system is a Windows 10 x64 Pro v1909

```

**Comment by adityapatwardhan** [comment]
I will have a look at this. Thanks for reporting.

**Comment by adityapatwardhan** [comment]
If you are trying to update PowerShell from within PowerShell you will get this error as it is trying to update assemblies in use. Please use `cmd` for updating the PowerShell version. I gave that a try and it seemed to work. If that is not the case please report back.

**Comment by ADNewsom09** [comment]
> If you are trying to update PowerShell from within PowerShell you will get this error as it is trying to update assemblies in use. Please use `cmd` for updating the PowerShell version. I gave that a try and it seemed to work. If that is not the case please report back.

This may have been the case that I ran the update command from within PowerShell initially but each command listed here was run from cmd. I'm not sure how to get back into a recoverable state.

**Comment by ADNewsom09** [comment]
This is still an issue, can you unmark as answered and re-open please.

**Comment by Ashbjorn** [comment]
Same issue here, Powershell 7.0.2 installed using MSI from Github, cannot update Global Tool.

![](https://user-images.githubusercontent.com/65817798/85923372-b16e1280-b88a-11ea-9475-76558ed60c22.png)

**Comment by Ashbjorn** [comment]
@[**ADNewsom09**](https://github.com/ADNewsom09) when I was debugging my issue I went to the following directory:

`c:\Users\joskr\.dotnet\tools\` and I deleted the `pwsh.exe` file that was lingering there.

Then I proceeded to execute the install/update command again:

![](https://user-images.githubusercontent.com/65817798/85923649-23475b80-b88d-11ea-8604-ff6f51f898a7.png)

Although I still cannot run PS1 files from within VS Code, but that is unrelated to what you reported. Perhaps you can use a similar approach to solve your local issue.
