### ISSUE TITLE
Pasting path strips leading non-breaking space from file name on Windows

### ISSUE THREAD

**Issue by movomo** [PowerShell/PowerShell#12963]
## Steps to reproduce

```powershell
# Create a temporary pathname that includes a leading non-breaking space.
New-Item "$([char]0xa0)test.txt"

# Try to copy & paste the file path, either by drag & drop from Explorer or just by pressing Ctrl + V.
```

## Expected behavior

```none
D:\ test.txt
```
The path should be pasted like above, preserving the space, because it is a valid pathname character.

## Actual behavior

```powershell
Set-Location D:\test.txt
# Set-Location: Cannot find path 'D:\test.txt' because it does not exist.
```
The leading space is stripped out and becomes an incorrect path.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KalleOlaviNiemitalo** [comment]
This looks like a PSReadLine issue, perhaps related to <https://github.com/PowerShell/PSReadLine/issues/760>. You could test whether `Remove-Module PSReadLine` fixes the problem.

> by pressing Ctrl + V

Is that in Windows Terminal or in conhost? Because Windows Terminal binds Ctrl+V to its own paste function by default, and that prevents PSReadLine from detecting the keypress and running *its* paste function, which might correctly preserve the non-breaking space.

**Comment by movomo** [comment]
I was on Windows Terminal when I noticed this, but it also happens with conhost too. Windows powershell and cmd on Windows Terminal works fine.

I tried ```Remove-Module PSReadline``` and it half-works.
* It pastes the path with 'space' preserved, but apparently not 'non-breaking' space. It becomes a wrong path.
* It will not enclose it with double quotes if no other breaking spaces are found in the path, even though it converted the non-breaking space to a plain space. This differs from Windows PowerShell 5.1.

* Legacy powershell (5.1.19041.1) behavior:
  - Pasted path is not enclosed in double quotes unless it had other ```\x20``` spaces.
  - Unless enclosed, path is incorrect.
  - If enclosed manually, the path becomes recognizable.
* pwsh behavior:
  - Pasted path is not enclosed in double quotes unless it had other ```\x20``` spaces. (same)
  - Manually enclosed or not, path is unrecognizable.

I also noticed another thing. The above tests were done with conhost, but if you do it on Windows Terminal (removing PSReadline), pwsh shows the same legacy powershell behavior. That is, manually enclosing it in quotes works. If you don't remove PSReadline, it just strips the ```\xa0``` character as described earlier.

**Comment by DHowett** [comment]
Windows Terminal will preserve the non-breaking space in paste due to a bug.

The traditional windows console host (conhost) replaces 0xa0 with 0x20, if I recall: https://github.com/microsoft/terminal/blob/master/src/interactivity/win32/Clipboard.cpp#L348

**Comment by movomo** [comment]
Yeah it seems like conhost is replacing 0xa0 with plain space... along with dash and quotes.

But... if Windows Terminal preserves non-breaking space due to a bug, then what is the right behavior? Now I'm confused.  So each of conhost, wt, powershell and pwsh is coming up with their own funny ideas with the clipboard??

---

conhost and wt comparison
Starting from `D:\`, try to cd to `"D:\ temp"`,

Done on the same window of cmd.exe directly executed from Run.
- **cmd**: 0xa0 replaced by 0x20 (quoting doesn't make it valid)
- **powershell**: space is preserved(?) but needs to be quoted
- **pwsh**: space removed

---

Windows Terminal
- **cmd**: 0xa0 is preserved and isn't even needed to be quoted
- **powershell**: space is preserved(?) but needs to be quoted
- **pwsh**: space removed

**Comment by KalleOlaviNiemitalo** [comment]
> The traditional windows console host (conhost) replaces 0xa0 with 0x20, if I recall

That must be "Filter clipboard contents on paste" under "Edit Options".

![Screen shot of the "Windows PowerShell" Properties dialog box, highlighting the option "Filter clipboard contents on paste"](https://user-images.githubusercontent.com/46201428/84737914-901b4580-afb1-11ea-86fc-9323a781b1ab.png)

**Comment by movomo** [comment]
Thanks, I didn't even know it existed. Having that 'Filter clipboard contents on paste' unchecked and also PSReadLine removed, then pwsh finally understands path with 0xa0. Does this mean this is PSReadLine bug?

**Comment by KalleOlaviNiemitalo** [comment]
It may be the same bug as <https://github.com/PowerShell/PSReadLine/issues/760>.

However, I think you can work around it this way:

- Keep PSReadLine imported.
- Paste by pressing Ctrl+V (not by right-clicking, using a menu, pressing Shift+Insert, or pressing Ctrl+Shift+V).
- If you use conhost, then "Filter clipboard contents on paste" does not matter for Ctrl+V.
- If you use Windows Terminal, then remove the [default Ctrl+V binding](https://docs.microsoft.com/windows/terminal/customize-settings/key-bindings#paste), to let PSReadLine handle the Ctrl+V.

See also <https://github.com/PowerShell/PSReadLine/issues/579>, for differences between Ctrl+V and other ways to paste.

**Comment by movomo** [comment]
Ah, those two worked like a charm. Thanks!
Too bad I can't use drag & drop for this though... that would be very nice.

**Comment by daxian-dbw** [comment]
Just saw this issue. FYI, the right-click pasting doesn't work in PSReadLine due to a .NET Core issue: https://github.com/dotnet/runtime/issues/38966

**Comment by nu8** [comment]
https://github.com/PowerShell/PSReadLine/issues/1603
