### ISSUE TITLE
PowerShell-7.0.2.win-arm64.msix Fails to Install

### ISSUE THREAD

**Issue by RichardMeadowsTC** [PowerShell/PowerShell#12966]
The msix for ARM64 (PowerShell-7.0.2.win-arm64.msix) will not install on Windows ARM64 Device. Not sure if anyone else has this issue. I am using OS from fast ring.  Error I see when install is: 'This app package is not supported for installation by App Installer because it uses certain restricted capabilities.'

**Comment by vexx32** [comment]
The MSIX installer must currently be installed via `Add-AppXPackage -Path $msixPath` from an administrative PowerShell session. 🙂

**Comment by RichardMeadowsTC** [comment]
I just need to run Add-AppXPackage -Path PowerShell-7.0.2.win-arm64.msix  Or is there some other installer that I need?

Richard Meadows

**Comment by vexx32** [comment]
If you want to use the MSIX, yeah that should work as far as I'm aware. 🙂 

If you prefer, you can also grab the regular MSI installer which is a little easier to work with. ^^

**Comment by adityapatwardhan** [comment]
I have tested with `Add-AppxPackage` and it seemed to work. If it does not please let me know. Please also include the OS version details.

**Comment by RichardMeadowsTC** [comment]
That worked.   Thank you.

Richard Meadows

**Comment by adityapatwardhan** [comment]
Thanks for confirming. Closing the issue.
