### ISSUE TITLE
Pasted script block is horribly mangled (appears to be reversed)

### ISSUE THREAD

**Issue by IanKemp** [PowerShell/PowerShell#12965]
## Steps to reproduce

Paste the following into a PS 7.0.2 window **(line endings must be `\n` NOT `\r\n`**):

```powershell
    @{
        "Microsoft.Azure.Functions.JavaWorker" = "https://ci.appveyor.com/NuGet/azure-functions-java-worker-fejnnsvmrkqg";
        "Microsoft.Azure.Functions.NodeJsWorker" = "https://ci.appveyor.com/nuget/azure-functions-nodejs-worker-0fcvx371y52p";
        "Microsoft.Azure.Functions.PowerShellWorker" = "https://ci.appveyor.com/nuget/azure-functions-powershell-wor-0842fakagqy6";
        "Microsoft.Azure.WebJobs.Script.WebHost" = "https://ci.appveyor.com/NuGet/azure-webjobs-sdk-script-g6rygw981l9t";
    } |% getEnumerator | %{
        $result = Invoke-Expression -Command ".\NuGet list $($_.key) -Source $($_.value) -PreRelease"
        $latestVersion = $result.Split()[1]
        Write-host "Adding $($_.key) to project" -ForegroundColor Green
        #Invoke-Expression -Command "dotnet add package $($_.key) -v $latestVersion -s $($_.value)"
    }
```

## Expected behavior

Script block is accepted as-is.

## Actual behavior

Script block is horribly mangled:

```powershell
PS C:\Users\iank\source\repos\_GitHub\Azure\azure-functions-core-tools\src\Azure.Functions.Cli>     }                   >>         #Invoke-Expression -Command "dotnet add package $($_.key) -v $latestVersion -s $($_.value)"                  >>         Write-host "Adding $($_.key) to project" -ForegroundColor Green                                              >>         $latestVersion = $result.Split()[1]                                                                          >>         $result = Invoke-Expression -Command ".\NuGet list $($_.key) -Source $($_.value) -PreRelease"                >>     } |% getEnumerator | %{                                                                                          >>         "Microsoft.Azure.WebJobs.Script.WebHost" = "https://ci.appveyor.com/NuGet/azure-webjobs-sdk-script-g6rygw981l9t";                                                                                                                    >>         "Microsoft.Azure.Functions.PowerShellWorker" = "https://ci.appveyor.com/nuget/azure-functions-powershell-wor-0842fakagqy6";                                                                                                          >>         "Microsoft.Azure.Functions.NodeJsWorker" = "https://ci.appveyor.com/nuget/azure-functions-nodejs-worker-0fcvx371y52p";                                                                                                               >>         "Microsoft.Azure.Functions.JavaWorker" = "https://ci.appveyor.com/NuGet/azure-functions-java-worker-fejnnsvmrkqg";                                                                                                                   >>     @{
```

![image](https://user-images.githubusercontent.com/1726434/84669486-d377a480-af1c-11ea-93ea-8eb297f0eea3.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Note

Same behaviour occurs in PS 5.1.
ISE works fine.

**Comment by vexx32** [comment]
This isn't a PowerShell issue; from memory, if you unload PSReadLine it stops appearing. That said, however, it also depends entirely on where you're copying from & how you're pasting. I'm not seeing it currently, having copied the code from the issue body.

Typically I've seen this be an issue with apps like Floobits and a few other Electron apps. It was happening with Teams as well for a while, I think, but Teams managed to fix it on their end.

See https://github.com/PowerShell/PSReadLine/issues/829, https://github.com/PowerShell/PSReadLine/issues/496#issuecomment-338515707 (decent analysis of probable cause), and https://github.com/PowerShell/PSReadLine/issues/579 (proposed as one of the more complete fixes that's been brought up so far).

**Comment by adityapatwardhan** [comment]
As per the suggestions in https://github.com/PowerShell/PSReadLine/issues/829, using `Ctrl+V` to paste works better.

**Comment by IanKemp** [comment]
> This isn't a PowerShell issue; from memory, if you unload PSReadLine it stops appearing.

Saying "this is an issue with PSReadLine, not PowerShell" is technically correct, but not helpful. Since PSReadLine is a default PS module since v3, it is de facto part of PowerShell. The fact this issue was reported over 3 years ago (and re-reported multiple times since) in the PSReadLine repo, but is not yet fixed, rather dents my confidence in PowerShell.

Having sub-repos for different subsystems is fine. Having those sub-repos be places where bug reports go to die, is not.

>  That said, however, it also depends entirely on where you're copying from & how you're pasting. I'm not seeing it currently, having copied the code from the issue body.
>
> Typically I've seen this be an issue with apps like Floobits and a few other Electron apps. It was happening with Teams as well for a while, I think, but Teams managed to fix it on their end.

I'm copying from a .ps1 file in Notepad++, that uses `\n` for line endings.

> See [PowerShell/PSReadLine#829](https://github.com/PowerShell/PSReadLine/issues/829), [PowerShell/PSReadLine#496 (comment)](https://github.com/PowerShell/PSReadLine/issues/496#issuecomment-338515707) (decent analysis of probable cause), and [PowerShell/PSReadLine#579](https://github.com/PowerShell/PSReadLine/issues/579) (proposed as one of the more complete fixes that's been brought up so far).

`Remove-PSReadlineKeyHandler Ctrl+Enter` pastes in the correct order, but eats newlines making the resultant code non-executable anyway, so... not very helpful.

> As per the suggestions in [PowerShell/PSReadLine#829](https://github.com/PowerShell/PSReadLine/issues/829), using `Ctrl+V` to paste works better.

This happens regardless of the method I use to paste (Ctrl+V or mouse right-click).

**Comment by vexx32** [comment]
The reason I say it's from PSReadLine and not PowerShell is because PSReadLine is managed from an entirely separate repository, so there's a limited amount of things folks in this repo can do directly, that's all. 🙂 

I'd recommend you copy that information to one of those other threads I linked, especially if you're still seeing it with Ctrl+V to paste. I'd hazard a guess that it might also be related to which terminal you use, so that info could be helpful too. ^^
