### ISSUE TITLE
Support bash/zsh-like way of passing environment variables down to subprocesses

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#12961]
## Summary of the new feature/enhancement

Take a look at this guide:
https://www.twilio.com/blog/2017/08/working-with-environment-variables-in-node-js.html

The example they used:

```bash
PORT=9999 node server.js
```

which sets `$env:PORT` to `9999` for the subprocess, `node`.

This works in bash, zsh, and fish... and is used _everywhere_. But it doesn't work in PowerShell.

The equivalent in PowerShell would be:

```
PS > $env:PORT = 9999
PS > node server.js
```

but that would set `$env:PORT` for the _current_ process as well which could cause issues.

## Proposed technical implementation details (optional)

If possible, we should try to support this syntax exactly. I couldn't find a specific doc, but this SO sums it up well:
https://unix.stackexchange.com/questions/392050/set-environment-variable-for-subshell

**Comment by vexx32** [comment]
This has been suggested before... Looks like it was #3316? 🙂

**Comment by TylerLeonhardt** [comment]
Thanks! I was searching the wrong things :) @SteveL-MSFT for awareness on a shell improvement.

**Comment by vexx32** [comment]
Knew I'd seen it before, but Github's search does not make that one at all easy to find. 😂
