### ISSUE TITLE
Attribute to add Cmdlet description from Source Code

### ISSUE THREAD

**Issue by arunswarnam** [PowerShell/PowerShell#12973]
Cmdlet description using attribute declarations 

PowerShell by default generates most of the help text in an expected way except for the Cmdlet Description. Just for specifying the description looks like we need to generate the help text in MAML format.  Is there a way to specify Cmdlet description as an Attribute in source code like we specify the output type? 
    [Cmdlet("Get", "Greeting")]
    [**OutputType**(string)]
    public class GetGreeting : PSCmdlet
   {
            [Parameter(Mandatory = false, ValueFromPipelineByPropertyName = true, **HelpMessage** = @"Person's name")]
        public string Name { get; set; }
   }

## Proposed technical implementation details (optional)

If this already exists, please update the documentation or is it possible to get this feature?

**Comment by iSazonov** [comment]
This should support localization at least.
