### ISSUE TITLE
No Taskbar icon with Powershell 7.0.2

### ISSUE THREAD

**Issue by JoeUX** [PowerShell/PowerShell#12977]
After installing Powershell 7.0.2, there is no longer an app icon in the Taskbar. Instead, there is a white rectangle, the standard placeholder icon. This is confirmed on two Windows 10 Pro machines. Screenshot below, followed by environment data.

Screenshot. See the white rectangle next to the VS Code icon in the center. That's Powershell 7.0.2:

![Powershell No Icon](https://user-images.githubusercontent.com/8071692/84898609-666b2880-b05c-11ea-9774-d236dda2fbaf.JPG)

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
It is dup #11995.
It was fixed in #12792 but not backported.
Perhaps @TravisEz13 can add more info.

**Comment by JoeUX** [comment]
Oh dang, I didn't see that one when I searched. 7.0.2 was just released – I wonder why it's not in it.

**Comment by TravisEz13** [comment]
@iSazonov definitely not fixed in #12792
