### ISSUE TITLE
tools/install-powershell.ps1 installs Win32 build on ARM64 Windows PC

### ISSUE THREAD

**Issue by 77** [PowerShell/PowerShell#12979]
```
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
VERBOSE: About to download package from
'https://github.com/PowerShell/PowerShell/releases/download/v7.0.2/PowerShell-7.0.2-win-x86.msi'
^C
```

Expectation is it would install PowerShell-7.0.2-win-arm64.msix instead.

**Comment by adityapatwardhan** [comment]
Unfortunately the script does not support installing `msix` but only `MSI`. The script at https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1 needs to be updated for supporting installing via `msix`

Thanks for reporting! We would appreciate if you could take a crack at it.
