### ISSUE TITLE
Unable to install any packages using PowerShellGet

### ISSUE THREAD

**Issue by ThadHouse** [PowerShell/PowerShell#12974]
I've been attempting to install posh-git on my new system, however installs keep failing with 

```
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/posh-git/0.7.3' is not valid.
```

With some more testing, it appears that any download with PowerShellGet fails. I wonder if this has something to do with NuGet removing TLS 1.1 and prior support as of 6/15/2020. However, setting TLS 1.2 explicitly with `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` doesn't seem to work. Is there something else that needs to get ran to force TLS 1.2? I can download the files using a web browser however.

Steps to reproduce:

1. `PowerShellGet\Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force`
2. Thats it, the above will fail saying the source location is not valid.

**Comment by daxian-dbw** [comment]
@alerickson Can you please take a look?

**Comment by ThadHouse** [comment]
Oh, I forgot I hadn't closed this. It started working the next day. I still think it was TLS related though.

**Comment by daxian-dbw** [comment]
@ThadHouse good to know it worked for you. I will mark this PR as `Question - Answered`.
