### ISSUE TITLE
Make the verb 'Deploy' symmetrical by adding a new verb 'Undeploy'

### ISSUE THREAD

**Issue by RemcoKapinga** [PowerShell/PowerShell#12978]
## Summary of the new feature/enhancement

As a PowerShell CmdLet developer, I would like to be able to use the Verb `Undeploy` for my Cmdlets, so i can write Cmdlets that undo a `Deploy` action (and are using a valid Verb to pass quality standards).

The verb `Deploy` was added in PowerShell 6, but strangely the verb `Undeploy` was not added at the same time.

In many operations the verb `Undeploy` is relevant, meaning to revert or undo a Deployment action. For example, removing software from a device that was added using a `Deploy` command.

Other Verbs that are paired with a 'Un' version:
- `Block` <==> `Unblock`
- `Install` <==> `Uninstall`
- `Lock` <==> `Unlock`
- `Protect` <==> `Unprotect`
- `Publish` <==> `Unpublish`
- `Register` <==> `Unregister`

## Proposed technical implementation details (optional)

- Add the Verb `Undeploy` to the list of approved Verbs (as returned by `Get-Verb`).
- Allow Code Analysis (`PsScriptAnalyzer`) to recognize and validate `Undeploy` as a valid Verb.

I'm not sure what the correct place to submit this issue is, see also : [my uservoice entry](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/40686598-make-the-verb-deploy-symmetrical-by-adding-a-new)

**Comment by ThomasNieto** [comment]
I would also like to see adding a `Unbuild` verb to go along with `Build` which was added in PowerShell 6.

**Comment by Remco-74** [comment]
> I would also like to see adding a `Unbuild` verb to go along with `Build` which was added in PowerShell 6.

I'm not sure if I do understand the reasoning for an `Unbuild` verb (not for or against it), but I'm afraid it may derail this discussion for `Deploy` / `Undeploy`. 

@ThomasNieto Could you create a new enhancement request for the `Unbuild` verb?
