### ISSUE TITLE
ValidateSet with multiple values fails in PowerShell 7.0.2

### ISSUE THREAD

**Issue by EgorEmeliyanov** [PowerShell/PowerShell#12986]
Good afternoon,

If we grab the Validateset example from [Powershell documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7):

```
[cmdletbinding()]

Param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("Low", "Average", "High")]
    [String[]]
    $Detail
)

Write-Host "Hi, I'm $Detail"
```
Since we are casting Detail as an array, we should be able to specify multiple parameters and in fact we can if using old Windows PowerShell 5.1:

![image](https://user-images.githubusercontent.com/17551749/84957912-39edf580-b0ca-11ea-81b0-50996dd36e65.png)

However, if we change powershell to pwsh (7.0.2), validateset throws an error:

![image](https://user-images.githubusercontent.com/17551749/84957957-51c57980-b0ca-11ea-91ae-8d04dd508efb.png)

If we go into interactive pwsh shell and run the file from there, getting rid of the quotes does the trick:

![image](https://user-images.githubusercontent.com/17551749/84958017-6b66c100-b0ca-11ea-8c7e-b1ca157133ed.png)

Therefore I assumed that cmd.exe somehow transforms and breaks arguments, but: (a) it does the same thing in Ubuntu bash and (b) If, instead of $Detail we output $PSBoundParameters (obviously after getting rid of ValidateSet so we reach this point in our code), we can see that the arguments have been correctly passed with or without quotes and cmd.exe is not guilty:

![image](https://user-images.githubusercontent.com/17551749/84958196-d57f6600-b0ca-11ea-953c-f52fb216728e.png)

Am I missing something very obvious? Thank you for looking into this!

**Comment by vexx32** [comment]
I think this _used_ to work only because the default mode of input was different. Try with both an explicit `-File ./test-param.ps1` and an explicit `-Command ./test-param.ps1` rather then supplying the file path positionally and you'll get different results. IIRC the default argument mode was changed sometime in 6.x, so that's why you're seeing a different here I think.

**Comment by EgorEmeliyanov** [comment]
Hi, @vexx32 !

Thank you very much for pointing me in the right direction. I was able to make it work when using -Command with dot-sourcing which is likely work for me:

![image](https://user-images.githubusercontent.com/17551749/84967844-010e4a80-b0e3-11ea-8ea5-401bd36f0170.png)

However, I still think something is not right either with the documentation or the interpreter. The documentation states that "_[...] all characters typed after the File parameter name are interpreted as the script file path followed by the script parameters [...] Parameters passed to the script are passed as literal strings, after interpretation by the current shell. For example [...] pwsh -File .\test.ps1 -TestParam %windir%_" But I wasn't able to find the right syntax to make it work with explicit -File:

![image](https://user-images.githubusercontent.com/17551749/84968026-84c83700-b0e3-11ea-8231-69bd1931645b.png)

Thank you!

~Egor

**Comment by vexx32** [comment]
That last one is definitely one I'd expect to work given your code, absolutely. That's very strange...

**Comment by EgorEmeliyanov** [comment]
I got the same result in Ubuntu (version 7.0.2 as well):

![image](https://user-images.githubusercontent.com/17551749/84969056-e7223700-b0e5-11ea-8808-91eee1233f6e.png)

**Comment by mklement0** [comment]
The `-File` CLI parameter doesn't support _arrays_, so you'll have to use `-Command`.

Your quote from the docs (emphasis added) provides a clue as to why: 

> Parameters passed to the script are passed as _literal strings_, after interpretation _by the current shell_.

That is, PowerShell uses the values _as broken into arguments by the calling shell_ as literals - without then _also_ trying to interpret them as a _PowerShell_ command line (only `-Command` does that).

Traditional shells have no concept of an array, and pass `"Low","High"` as a _single_ argument (received by PowerShell as verbatim string `Low,High`); if you tried to put a space between the elements - `"Low"," High"` - they pass _2_ arguments, received as verbatim `Low,` (note the trailing `,`) and verbatim `High`.

Note that PowerShell itself too passes arguments this way _when calling external programs_.
(By contrast if you use `(...)` around the array to turn it into an _expression_, PowerShell will pass the array elements as _individual arguments_; e.g., `printf [%s] ('Low','High')` yields `[Low][High]`, whereas `printf [%s] 'Low','High'` yields `[Low,High]`)

See also:  https://stackoverflow.com/a/48959328/45375

**Comment by EgorEmeliyanov** [comment]
Thank you, @mklement0 that explains it.
