### ISSUE TITLE
Dynamic parameters are not imported as variables

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#12987]
## Steps to reproduce

```powershell
FUNCTION TEST-PARAM { [CMDLETBINDING()] PARAM([SWITCH] $B)
 DYNAMICPARAM {
NEW-OBJECT Management.Automation.RuntimeDefinedParameterDictionary |
 % { $_.ADD('A', (
NEW-OBJECT Management.Automation.RuntimeDefinedParameter (
'A', [SWITCH], ((
NEW-OBJECT  Management.Automation.PARAMETERATTRIBUTE
))
)
)
)
$_
 }
RETURN
 } PROCESS { '[{0}={1} {2}={3}]' -F $A, $PSBOUNDPARAMETERS.A, $B, $PSBOUNDPARAMETERS.B 
 }
 }

TEST-PARAM -A -B
```

## Expected behavior

```none
[True=True True=True]
```

## Actual behavior

```none
[=True True=True]
```

## Environment data

<DL ><DT >PSVersion                      <DD >7.0.2
<DT >PSEdition                      <DD >Core
<DT >GitCommitId                    <DD >7.0.2
<DT >OS                             <DD >Microsoft Windows 10.0.18363
<DT >Platform                       <DD >Win32NT
<DT >PSCompatibleVersions           <DD >{1.0, 2.0, 3.0, 4.0…}
<DT >PSRemotingProtocolVersion      <DD >2.3
<DT >SerializationVersion           <DD >1.1.0.1
<DT >WSManStackVersion              <DD >3.0PSVersion                      7.0.2
<DT >PSEdition                      <DD >Core
<DT >GitCommitId                    <DD >7.0.2
<DT >OS                             <DD >Microsoft Windows 10.0.18363
<DT >Platform                       <DD >Win32NT
<DT >PSCompatibleVersions           <DD >{1.0, 2.0, 3.0, 4.0…}
<DT >PSRemotingProtocolVersion      <DD >2.3
<DT >SerializationVersion           <DD >1.1.0.1
<DT >WSManStackVersion              <DD >3.0</DL >

**Comment by mklement0** [comment]
Perhaps someone (@SeeminglyScience?) can speak to a potential design rationale and whether there are good reasons for this behavior, which can certainly be a pitfall whose avoidance may be non-obvious; just to provide a historical note: dynamic parameters always needed to be accessed via `$PSBoundParameter`; they were never represented as (what would have to be implicitly defined) local variables.

**Comment by vexx32** [comment]
@rjmholt might be the other person to poke on that, if anyone still knows what the rationale was there... But yep, this has always been the case as far as I'm aware.

It's one of many reasons I tend to recommend against use of `dynamicparam` unless there's no other alternative.

**Comment by SeeminglyScience** [comment]
I don't think it's a *design* decision necessarily (though I could be wrong), just kinda looks like a pain.  Right now dynamic parameters are handled the same way for script commands as they are for binary cmdlets.  The dynamic parameter binder is pretty unaware of what the underlying command type is.  That could almost definitely be changed, just with a bit more complexity than you'd think.
