### ISSUE TITLE
3 existing FileCatalog cmdlet tests fail when running in PowerShell Core on the AppVeyor build VM (Windows Server 2012R2)

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#1299]
Note that all tests pass in PowerShell Core on Windows 10 machine. However, 3 of them fail on the AppVeyor build VM, which is Windows Server 2012R2. These 3 tests are disabled for now.
## Steps to reproduce

```
powershell\test\powershell\Modules\Microsoft.PowerShell.Security> Invoke-Pester .\FileCatalog.Tests.ps1
```
## Expected behavior

All tests pass
## Actual behavior

3 tests fail on the AppVeyor build VM (windows 2012R2)

> NewFileCatalogWithMutipleFoldersAndFiles
> Expected: {AFEB46104F506FC64CAB4B0B2A9C6C50622B487A}
> But was:  {ECEE0E902E1392D02D17B1A0C553925D365048EF}
> 
> NewFileCatalogVersion2WithMutipleFoldersAndFiles
> Expected: {6591FE02528D7FB66F00E09D7F1A025D5D5BAF30A49C5FF1EC562FAE39B38F43}
> But was:  {F699D4CA967D1CC303E6AEE4B213646298D11890DB3241439C4232A5353A76CC}
> 
> NewFileCatalogWithUnicodeCharactersInFileNames
> Expected: {6591FE02528D7FB66F00E09D7F1A025D5D5BAF30A49C5FF1EC562FAE39B38F43}
> But was:  {F699D4CA967D1CC303E6AEE4B213646298D11890DB3241439C4232A5353A76CC}
## Environment data

``` powershell
> $PSVersionTable

Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v0.5.0-271-g32e74b8a6380fc1e95e737ff93244b788f7eac33
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSVersion                      5.1.10032.0
PSEdition                      Core
CLRVersion
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
```

**Comment by ThomasNieto** [comment]
@daxian-dbw is this still an issue? It looks like two of the tests have been removed and the third is not commented out.
