### ISSUE TITLE
Remove extra newline in the output of GCI 

### ISSUE THREAD

**Issue by musm** [PowerShell/PowerShell#12994]
## Summary of the new feature/enhancement

![image](https://user-images.githubusercontent.com/4319522/85101361-3e043b00-b1d0-11ea-8b5f-ad22c9d189e9.png)

See the highlighted line above:  Please remove this extra unnecessary line. 

## Proposed technical implementation details (optional)
@iSazonov  solved a related issue in https://github.com/PowerShell/PowerShell/pull/12163 
This feature requests addresses the extra newline at the start of the command. I suspect a similar implementation is likely.

**Comment by iSazonov** [comment]
@musm Can you check with latest nightly build?

**Comment by musm** [comment]
Are there nightly binaries available somewhere to test?

**Comment by iSazonov** [comment]
Download artifacts from https://github.com/PowerShell/PowerShell#build-status-of-nightly-builds

**Comment by musm** [comment]
Looks like it's fixed on master. So the bugfix looks like it didin't make release https://github.com/PowerShell/PowerShell/releases/tag/v7.0.2 ?

**Comment by iSazonov** [comment]
I think this will be never backported. Users will get this in next 7.1. Preview4.

**Comment by musm** [comment]
thanks
