### ISSUE TITLE
Invoke-RestMethod failing with remote certificate is invalid according to the validation procedure for PowerShell 7.0.2

### ISSUE THREAD

**Issue by munishpalmakhija** [PowerShell/PowerShell#12993]
## Expected behavior

```
Connect-Vmc -ApiToken $APIToken should connect and return the authorization token
It works with Powershell 7.0.0 but doesn't work in 7.0.2

```

## Actual behavior

```
We use Connect-Vmc module which uses Invoke-RestMethod which is failing 

PS /root> Connect-Vmc -ApiToken $APIToken
Connect-Vmc: 6/18/2020 11:04:48 PM	Connect-Vmc		Unable to create security context. Details: The SSL connection could not be established, see inner exception.

When I manually use Invoke-RestMethod with console.cloud.vmware.com I also see The remote certificate is invalid according to the validation procedure. It only works when I do -SkipCertificateCheck

```

## Environment data

```
PS /root> $PSVersionTable                

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Linux 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Please share inner exception.
Also check with latest 7.1 build.

**Comment by munishpalmakhija** [comment]
When I run Invoke-RestMethod manually I am getting following error 

`PS /root> Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body
Invoke-RestMethod: The remote certificate is invalid according to the validation procedure.
PS /root> `

Also, I don't see 7.1 under releases. Latest one still shows 7.0.2 which was on 11th June 

Thanks,
Munish

**Comment by munishpalmakhija** [comment]
Following is the URL which has CA-signed certificate

`$API = "xxx"
  $url = "https://console.cloud.vmware.com/csp/gateway/am/api/auth/api-tokens/authorize?refresh_token="+ $API`

**Comment by munishpalmakhija** [comment]
Any update on the same? This is causing VMware Cloud Services commands to fail

**Comment by iSazonov** [comment]
@munishpalmakhija I guess it is .Net issue. PowerShell doesn't check certificates directly, it utilizes .Net API. 
You could review issues in .Net Runtime repository - perhaps they already has such issue.
Or you could review PowerShell code for the cmdlet and create a simple repro (I guess it is HttpClient class issue.)

**Comment by munishpalmakhija** [comment]
I am not Powershell developer only the consumer so I am not sure I will understand the code here . 
Also not sure if that matters but I am using Powershell Core on Linux not on Windows

**Comment by SteveL-MSFT** [comment]
Might be fixed via https://github.com/dotnet/runtime/pull/40222

**Comment by iSazonov** [comment]
Can we move to .Net 5 RC1 to get the fix?

**Comment by TravisEz13** [comment]
@munishpalmakhija can you validate RC.1 fixed this issue?

**Comment by munishpalmakhija** [comment]
I was able to successfully validate with PowerShell 7.1.0-RC.1. Thank you for fixing the same. 
Thanks,
Munish
