### ISSUE TITLE
Feature Request: Support for JSON Schema Draft 2019-09

### ISSUE THREAD

**Issue by mann-david** [PowerShell/PowerShell#12999]
The underlying library that provides JSON Schema support  (Test-Json)(https://github.com/RicoSuter/NJsonSchema) doesn't support either of the latest 2 drafts of JSON Schema, which is problematic as there were significant changes since v4 (the last it supports).

Can this support be added?

**Comment by vexx32** [comment]
@iSazonov is this covered under the pending move to System.Text.Json or is the .NET implementation also missing that functionality?

**Comment by mann-david** [comment]
I dont see schema support in System.Text.Json, but could have missed it
________________________________

**Comment by iSazonov** [comment]
Tracking issue in .Net Runtime https://github.com/dotnet/runtime/issues/29887
Current status - it is not planned for .Net 5.0.

As for the request, we use NJsonSchema so you should ask the support there.
