### ISSUE TITLE
Azure Pipelines clock issues

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#12996]
In build 55800 the clock keeps jumping back and forth about 16 hours:

2020-06-18T16:46:46.1993748Z
2020-06-19T09:28:05.5534482Z

https://dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_apis/build/builds/55800/logs/35

**Comment by daxian-dbw** [comment]
@TravisEz13 @adityapatwardhan Do you know why the timestamp is acting like this?

**Comment by TravisEz13** [comment]
The lines that are being logged in one time zone are on the service and the other are on the agent.

**Comment by TravisEz13** [comment]
The link to report an issue is here:  https://developercommunity.visualstudio.com/spaces/22/tfs.html?type=problem
