### ISSUE TITLE
Run PS from net core using microsoft.PowerShell.SDK in windows 8.1 failure

### ISSUE THREAD

**Issue by agonzalezm** [PowerShell/PowerShell#13006]
I am using microsoft.PowerShell.SDK from net core 3.1  to run PS command, it works fine in windows 10 but in windows 8.1 I get this error:

Is there any workaround to this and to be able to run PS in same way without updating powershell to 5.1?

Detected Windows PowerShell version 4.0. Windows PowerShell 5.1 is required to load modules using Windows PowerShell compatibility feature. Install Windows Management Framework (WMF) 5.1 from https://aka.ms/WMF5Download to enable this feature. ---    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModulesUsingWinCompat(IEnumerable`1 moduleNames, IEnumerable`1 moduleFullyQualifiedNames, ImportModuleOptions importModuleOptions)   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(ExternalScriptInfo scriptInfo, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options)   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName, String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options,

**Comment by agonzalezm** [comment]
Any workaround at this? is this a bug? is windows 8.1 supported ?

**Comment by vexx32** [comment]
The error is just effectively stating that the WinPS compatibility remoting won't be available, but it shouldn't impact general usage of PowerShell apart from the error being reported. I'm not sure if there's a way to set it to be ignored completely though.

/cc @adityapatwardhan

**Comment by agonzalezm** [comment]
But i am not using powershell remoting, i just want to run a local script in the local machine and it is failing to do so.

**Comment by SeeminglyScience** [comment]
@agonzalezm What's in the script? Does it contain a command only available on Windows PowerShell?

**Comment by agonzalezm** [comment]
@SeeminglyScience  yes it runs powershell command Get-MpThreat from defender, running that on powershell console works fine.

psh.Execute("Set-ExecutionPolicy bypass -force -confirm:$false; Import-Module defender;  Get-MpThreat | select-object -property CategoryID,SeverityID, ThreatID, ThreatName | convertto-json", 60))

**Comment by adityapatwardhan** [comment]
I will have a look at this sometime this week. Thanks for reporting this.

**Comment by agonzalezm** [comment]
@adityapatwardhan any update on this?

**Comment by adityapatwardhan** [comment]
Sorry I was busy last week with Preview.5 release. I will have a look this week.

**Comment by daxian-dbw** [comment]
> Detected Windows PowerShell version 4.0. Windows PowerShell 5.1 is required to load modules using Windows PowerShell compatibility feature. Install Windows Management Framework (WMF) 5.1 from https://aka.ms/WMF5Download to enable this feature.

@agonzalezm This error message indicates that the `Defender` module is not compatible with PS 7.
The `Defender` module on Windows 10 is compatible with PS 7 -- `Depender.psd1` has `CompatiblePSEditions = @('Desktop', 'Core')`, but I don't think the module on Windows 8.1 has this compatibility. Therefore, PS 7 needs to load it using the [Windows PowerShell Compatibility feature](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7), which requires Windows PowerShell 5.1 and won't work with Windows PowerShell 4.0.

One workaround is to run `Import-Module Defender -SkipEditionCheck`. `-SkipEditionCheck` will force to load an incompatible module without going through the Windows PowerShell Compatibility feature. It may not work if the module just simply doesn't work in .NET Core, so you have to try it out.
