### ISSUE TITLE
Feature Request: Quiet the Help and Upgrade banners

### ISSUE THREAD

**Issue by JasonKleban** [PowerShell/PowerShell#13007]
This banner is pretty annoying.  Can you tone it down?  Integrated in VS Code split screen, it consumes most of the space allotted.  I don't need this every time - maybe once a week?  Can you only do it when there's a major version or security fix?  Can we dismiss that silly help message?

```
https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.0.2
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.0.2
```

**Comment by vexx32** [comment]
You can start pwsh with `-NoLogo` to remove all of those, I think?

**Comment by rjmholt** [comment]
Related: https://github.com/PowerShell/PowerShell/issues/12701
