### ISSUE TITLE
RunspaceInvoke is missing from latest release

### ISSUE THREAD

**Issue by Triggs9** [PowerShell/PowerShell#13004]
ILSpy on the latest release: 

https://www.nuget.org/packages/System.Management.Automation/

shows RunspaceInvoke missing

References:

https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaceinvoke?view=powershellsdk-1.1.0

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/RunspaceInvoke.cs

**Comment by daxian-dbw** [comment]
Hmm, the `RunspaceInvoke.cs` was not included in the build, since 6.0 ... See https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/System.Management.Automation.csproj#L102

I don't see an obvious reason to exclude it. Maybe it should be brought back.
/cc @adityapatwardhan @TravisEz13 @rjmholt

**Comment by rjmholt** [comment]
I don't see the harm, beyond confusing the API a bit with an alternative to `PowerShell.Create().AddScript(...).Invoke()`. Does this do anything different?

**Comment by TravisEz13** [comment]
It has some APIs which take a string and and execute them.  That's not the safest thing to do, but I'm pretty sure we have similar APIs

**Comment by daxian-dbw** [comment]
@Triggs9 How did you find it missing? Did you try to migrate old code to PowerShell 7 and found it broken because of this?

**Comment by rjmholt** [comment]
I feel I should mention that this not being in PS 7.0 (and also PSStd) does devalue adding it back in now a bit

**Comment by Triggs9** [comment]
No i was trying to run something from the current powershell runspace instead of in a sub powershell instance. I was able to get it working by using an old library that had it included. So i thought i would bring it up, but then abandoned that approach in favor of using just $ExecutionContext.InvokeCommand.InvokeScript()

**Comment by rjmholt** [comment]
You can also try `PowerShell.Create(RunspaceMode.CurrentRunspace)`

**Comment by Triggs9** [comment]
> You can also try `PowerShell.Create(RunspaceMode.CurrentRunspace)`
Thanks i've actually been using that in all situations now.

**Comment by daxian-dbw** [comment]
@PowerShell/powershell-maintainers maintainers reviewed this issue and decided to not bring this type back given that
1. this type is missing from PS 7.0 LTS
2. the customer has a workaround.

**Comment by henryboy666** [comment]
If I want to output an error message, which method should I use, I don't seem to have found an alternative
’ out IList errors‘
` public Collection<PSObject> Invoke(string script, IEnumerable input, out IList errors)
        {
            if (_disposed == true)
            {
                throw PSTraceSource.NewObjectDisposedException("runspace");
            }

            if (script == null)
            {
                throw PSTraceSource.NewArgumentNullException("script");
            }

            Pipeline p = _runspace.CreatePipeline(script);
            Collection<PSObject> output = p.Invoke(input);
            // 2004/06/30-JonN was ReadAll() which was non-blocking
            errors = p.Error.NonBlockingRead();
            return output;
        }
`

**Comment by henryboy666** [comment]
If I want to output an error message, which method should I use, I don't seem to have found an alternative.
` out IList errors`
` public Collection<PSObject> Invoke(string script, IEnumerable input, out IList errors)
        {
            if (_disposed == true)
            {
                throw PSTraceSource.NewObjectDisposedException("runspace");
            }

            if (script == null)
            {
                throw PSTraceSource.NewArgumentNullException("script");
            }

            Pipeline p = _runspace.CreatePipeline(script);
            Collection<PSObject> output = p.Invoke(input);
            // 2004/06/30-JonN was ReadAll() which was non-blocking
            errors = p.Error.NonBlockingRead();
            return output;
        }
`
