### ISSUE TITLE
( Get-NetTCPConnection -State Listen ) vs (netstat -tlnp in linux)

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#13013]
## Summary of the new feature/enhancement
I want to see the listening port and its program at the same time in windows.
But I only see the port , and the program name is not available in windows.
Bellow is the output from LINUX that implement similar feature.
I hope Get-NetTCPConnection have the same feature.

![image](https://user-images.githubusercontent.com/36788337/85349859-227f9400-b532-11ea-9eb2-78e442d6a11d.png)

**Comment by iSazonov** [comment]
Get-NetTCPConnection is not in the repository. Use UserVoice site to send your request to MSFT owner team.

**Comment by hcoona** [comment]
@iSazonov Where is the command `Get-NetTCPConnection` maintained? Is it available on Linux/macOS? What's the scope of the core functions/core utilities of PowerShell?

**Comment by iSazonov** [comment]
@hcoona The cmdlet is in NetTCPIP module. The module is Windows only.

**Comment by hoodedfoxtailz** [comment]
Arch Linux
