### ISSUE TITLE
PSHostUserInterface.ReadLineMaskedAsString should default to ReadLineAsSecureString

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#13015]
## Summary of the new feature/enhancement

The virtual method for `PSHostUserInterface.ReadLineMaskedAsString` throws `PSNotImplementedException` currently.  Since most hosts will already support `ReadLineAsSecureString`, it should use that as a fallback and just convert to a string.

The current implementation is going to be really painful to support for hosts that still need to run in 5.1 (like PSES)

**Comment by daxian-dbw** [comment]
@SeeminglyScience can you elaborate a bit more on how it is painful to support hosts that run in 5.1?

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience can you elaborate a bit more on how it is painful to support hosts that run in 5.1?

Basically if you target PowerShell Standard 5.1, you can't override the virtual method.

> Are you asking the change to be done in 5.1 as well?

Nah, only asking that it not throw by default in 7.1.  That way hosts that already support `ReadLineAsSecureString` will automatically support `ReadLineMaskedAsString` without having to compile for 7.1
