### ISSUE TITLE
Replace licenseUrl with SPDX license identifier in PowerShell NuGet packages

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [PowerShell/PowerShell#13026]
## Summary of the new feature/enhancement

As a developer consuming NuGet packages, I want the license terms of each package to remain readable and immutable after I have reviewed them. However, PowerShell NuGet packages such as [Microsoft.PowerShell.Security](https://www.nuget.org/packages/Microsoft.PowerShell.Security/7.1.0-preview.3) currently have <https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt> as `licenseUrl` in the package metadata. The license terms referenced by such a URL can be changed, and the URL may stop working if the branch is renamed (as requested in <https://github.com/PowerShell/PowerShell/issues/12951>).

## Proposed technical implementation details (optional)

NuGet has deprecated `licenseUrl` (<https://github.com/NuGet/Announcements/issues/32>). The `license` property should be used instead, presumably here: <https://github.com/PowerShell/PowerShell/blob/ab7460365ffdd40e1c3ae67958a27f210c6b594a/tools/packaging/packaging.strings.psd1#L137>

**Comment by iSazonov** [comment]
We could use `<license type="MIT"/>`.

/cc @TravisEz13

**Comment by iSazonov** [comment]
There are two option in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file
1. Set license type
2. Set license file

Since we have a license file in repo root perhaps second option is better.

**Comment by iSazonov** [comment]
`iconUrl` is also deprecated. We should add `icon` and keep `iconUrl` for backward compatibility.

**Comment by TravisEz13** [comment]
> We could use `<license type="MIT"/>`.
> 
> /cc @TravisEz13 

This should work for the packages in this repo, but @adityapatwardhan is the expert on compliance here.  We may have to get some changes in other places after we create the package.

**Comment by TravisEz13** [comment]
> `iconUrl` is also deprecated. We should add `icon` and keep `iconUrl` for backward compatibility.

If it's like licenseUrl, you cannot have both.

**Comment by TravisEz13** [comment]
> There are two option in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file
> 1. Set license type
> 2. Set license file
> 
> Since we have a license file in repo root perhaps second option is better.
> 
> For backward compatibility we should keep old code too.

1 is the preferred option.  We have systems that try to parse and 1 works more reliably

**Comment by KalleOlaviNiemitalo** [comment]
The documentation says that both `icon` and `iconUrl` can be specified in the same nuspec file. <https://docs.microsoft.com/nuget/reference/nuspec#icon>

**Comment by adityapatwardhan** [comment]
>You can specify both icon and iconUrl to maintain backward compatibility with sources that do not support icon. Visual Studio will support icon for packages coming from a folder-based source in a future release.

We only publish to NuGet.org so we no not need "iconUrl".

**Comment by adityapatwardhan** [comment]
yes we can use <license type="MIT"/>
