### ISSUE TITLE
PowerShell 7.1.0-preview4 x64 executable removes PowerShell 7.0.2 and does not install preview4

### ISSUE THREAD

**Issue by CatTheHacker** [PowerShell/PowerShell#13035]
## Steps to reproduce
- Install PowerShell 7.1.0-preview3 (7.1.0.3) [`PowerShell-7.1.0-preview.3-win-x64.msi`]
- Install PowerShell 7.0.2 [`PowerShell-7.0.2-win-x64.msi`]
- Verify that both appear separately in `C:\Program Files\PowerShell\`
- Install PowerShell 7.1.0-preview4 (7.1.0.4) [`PowerShell-7.1.0-preview.4-win-x64.msi`]
- Verify `C:\Program Files\PowerShell\7\` and `C:\Program Files\PowerShell\7-preview\` again

## Expected behavior

PowerShell Preview is updated to 7.1.0-preview4 and PowerShell 7.0.2 is not deleted.

## Actual behavior

PowerShell 7.0.2 is being deleted from `C:\Program Files\PowerShell\7\`
PowerShell 7.1.0-preview4 is not installed (but its installation is added to registry)
PowerShell 7.1.0-preview3 is installed.
![image](https://user-images.githubusercontent.com/31106839/85796197-0d208a80-b729-11ea-8dcd-64cf8d84f3e0.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Microsoft Windows 10.0.20150
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Additional info
This happened on my main PC (Windows 10 2004, build 19041.329) as well as I was able to reproduce it in VM with Windows 10 Insider Preview (build 20150.1000)
Also latest preview installation executable does not appear to have digital signature attached in comparison to the previous preview.
Something for @TravisEz13 I guess?

**Comment by iSazonov** [comment]
Will be fixed n #13036 I guess.

**Comment by LittleNewton** [comment]
How to install preview-4 without .MSI?

Now I cannot use pwsh in Windows Terminal.

**Comment by atiensivu** [comment]
Might want to pull the notification of the new update that happens inside the preview 3. That's a bit of a big oopsie.

**Comment by TravisEz13** [comment]
> Might want to pull the notification of the new update that happens inside the preview 3. That's a bit of a big oopsie.

We are working to release preview 5 as quickly as possible.  Feel free to file a feature request for the ability for us to disable the update notification functionality for a release, but I don't think it is viable at this time.

**Comment by iSazonov** [comment]
> Feel free to file a feature request for the ability for us to disable the update notification functionality for a release 

We already have such issue.

**Comment by minoseah629** [comment]
i just installed preview5.  it installed properly.  but not 7.0.2 since it thinks preview is a higher version
https://github.com/PowerShell/PowerShell/pull/13036#issuecomment-654875234

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PowerShell/pull/13036#issuecomment-655039948
