### ISSUE TITLE
I cannot find the currect GUID in Windows Terminal for preview-4

### ISSUE THREAD

**Issue by LittleNewton** [PowerShell/PowerShell#13037]
```
在配置文件列表中找不到你的默认配置文件-使用第一个配置文件。请进行检查以确保 "defaultProfile" 与你的某个配置文件的 GUID 相匹配。
```

How to add the config to Windows Terminal

```
{
  // 键标记
  "guid": "{7bc167bf-00e9-4fc6-b51b-a8a5a3b090fd}",
  "name": "pwsh",
  "source": "Windows.Terminal.PowershellCore",
  // 行为
  "closeOnExit": true,
  "commandline": "D:/Users/newton/Documents/Softwares/software_windows/develop/shell/PowerShell-7.1.0-preview.4-win-x64/pwsh.exe -nologo",
  "hidden": false,
  "historySize": 9001,
  "snapOnInput": true,
  "startingDirectory": ".",
  // 外观
  "acrylicOpacity": 0.5,
  "cursorColor": "#FFFFFF",
  "cursorShape": "bar",
  "fontFace": "Fira Code",
  "fontSize": 11,
  "padding": "5, 5, 20, 25",
  "useAcrylic": false,
  
  // 颜色主题
  "colorScheme": "Homebrew"
},
```

Windows Terminal said she cannot find the default configure file and please make sure "defaultProfile" match with some configures GUID.

I just uninstall preview-3 and replace the "commandline" with the new location of the new powershell core preview-4. For the developer didn't provide a MSI package, I cannot find the GUID by mylf.

I need help.

**Comment by LittleNewton** [comment]
What is the usage of GUID?

I think this item is useless.

**Comment by vexx32** [comment]
The GUID itself in Terminal isn't special as far as I'm aware, it's just an identifier for that profile configuration so you can target that profile specifically. The `source` property is what determines where it comes from. 

IIRC you'll need either a powershell preview source (not sure if they have an automatic config for previews, but they might?) or you'll need to use a path-based configuration and target the pwsh.exe from the preview installation specifically.

**Comment by LittleNewton** [comment]
Yes, after canceling/deleting the `source` property, every work safe and sound.

**Comment by DHowett** [comment]
> not sure if they have an automatic config for previews

We do, but it somewhat requires people to install powershell in normal and expected locations, not nested forty directories deep in their home folders 😁
