### ISSUE TITLE
"Loading" of Windows Runtime assemblies fails in 7.1 Preview 4

### ISSUE THREAD

**Issue by wi-fr** [PowerShell/PowerShell#13042]
## Steps to reproduce

[void][Windows.Storage.StorageFile, Windows.Storage, ContentType=WindowsRuntime]

[void][Windows.Graphics.Imaging.BitmapDecoder, Windows.Graphics, ContentType=WindowsRuntime]

## Expected behavior

WinRT assemblies are loaded. 

## Actual behavior

InvalidOperation: Unable to find type [Windows.Storage.StorageFile,Windows.Storage, ContentType=WindowsRuntime].

InvalidOperation: Unable to find type [Windows.Graphics.Imaging.BitmapDecoder,Windows.Graphics, ContentType=WindowsRuntime].

## Environment data

PSVersion                      7.1.0-preview.4
PSEdition                      Core
GitCommitId                    7.1.0-preview.4
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SeeminglyScience** [comment]
This is due to removal of builtin support in dotnet, see dotnet/runtime#37672.

/cc @SteveL-MSFT while this breaking change isn't PowerShell's fault, it will have a decent impact. It may be a good idea to look into adding built in support. [C#/WinRT package](https://github.com/microsoft/CsWinRT) seems to be the recommendation, though at a glance it doesn't look like that can be used as a general solution.

There are some very popular modules that utilize winrt APIs (like [BurntToast](https://github.com/Windos/BurntToast) by @Windos).

**Comment by Windos** [comment]
It may be that my morning coffee is only half drunk atm, but I'm struggling to wrap my head around making use of [C#/WinRT](https://github.com/microsoft/CsWinRT) in (non-C#) PowerShell.

From what I can see on the Gallery, the biggest use case of these WinRT assemblies are Toast Notifications of various flavours (Even [dbatools](https://www.powershellgallery.com/packages/dbatools/0.8.905/Content/functions%5CWatch-DbaUpdate.ps1) uses them).

If we could wrangle built-in support in PowerShell that'd be super 💜. If not, it looks like module authors will need to figure out runtime projection... in BurntToast's case that'll probably mean a version or two that caps its host support at 7.0 until I/someone figure it out.

**Comment by iSazonov** [comment]
PowerShell has never WinRT support. The fact that users could load WinRT assemblies previously does not mean that everything worked out of the box. Moreover, the engine explicitly blocks WinRT event processing (Also it seems the engine consider WinRT types as special case).
To restore previous behavior users have to explicitly install [C#/WinRT package](https://github.com/microsoft/CsWinRT) (it seems it is still not ready for general use).
Since no changes was made in PowerShell engine all modules used WinRT directly (by p/invoke) should continue to work.

**Comment by SeeminglyScience** [comment]
@iSazonov I 100% agree that this break isn't PowerShell's *fault* or even necessarily it's responsibility to fix.  It still might be a good idea though.

> PowerShell has never WinRT support.

In the same way it never supported `System.Text.StringBuilder` I suppose but if that disappeared tomorrow it might be a good idea to add it back.

> Moreover, the engine explicitly blocks WinRT event processing (Also it seems the engine consider WinRT types as special case).

It also blocks processing of event handlers with a return type other than `void`.  I'm guessing there are similar technical and/or design reasons.

**Comment by iSazonov** [comment]
> In the same way it never supported System.Text.StringBuilder I suppose but if that disappeared tomorrow it might be a good idea to add it back.

Technically we would need to reference C # / WinRT package. But now the package is not ready for release. Also I guess MSFT team prefer to reduce PowerShell distributive size.

**Comment by iSazonov** [comment]
@Windos If I understand correctly BurntToast doesn't work on latest PowerShell preview. Do you consider C # / WinRT package for BurntToast?

**Comment by Windos** [comment]
@iSazonov Yeah, BurntToast 100% relies on WinRT assemblies so this change in .NET will break the module in PS preview. I missed Preview 4 before  the MSI got pulled, so will confirm this when Preview 5 is out.

I will be looking into C#/WinRT, but haven't had a chance to sit down and figure that out yet.

**Comment by iSazonov** [comment]
> I missed Preview 4 before the MSI got pulled, so will confirm this when Preview 5 is out.

@Windos You can load a nightly build from main page of the repo.

**Comment by wi-fr** [comment]
Another use case of WinRT assemblies that's worth to be considered are its bitmap decoders that support Apple's HEIF format. I'm not aware of any alternative provided by Microsoft.

**Comment by Windos** [comment]
Can confirm, expected exception when importing the module.

![Exception on module import](https://user-images.githubusercontent.com/6955786/86191147-6447b480-bb9a-11ea-86b6-0039b5a6490a.png)

**Comment by SteveL-MSFT** [comment]
I'll bring this up with the .NET team

**Comment by AdamBraden** [comment]
With the breaking change in .NET5 Preview 6, https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-6/, you will now need to reference a cswinrt generated interop assembly to call winrt apis. For the Windows WinRT apis, we've built a nuget package that provides this support, and will need to be referenced when building the module - https://www.nuget.org/packages/Microsoft.Windows.SDK.NET

**Comment by richlander** [comment]
There are three big questions we need to answer:

- Does referencing the package resolve this issue?
- Does referencing the package / adding a dependency fit into a natural PS workflow?
- What should we do to enable a PS module to support both PS 7.0 and 7.1 (to accommodate this breaking change)?

**Comment by vexx32** [comment]
Modules referencing a nuget dependency is a scenario that still does not work anything close to well and isn't a supported scenario for PowerShellGet as far as I'm aware. Not sure if that's planned to change for v3 of that module but it really should if it hasn't already.

Until that's working _seamlessly_ things like this will need to be included in PowerShell itself to avoid breaking changes.

**Comment by SteveL-MSFT** [comment]
Workaround:

1. include winrt.runtime.dll from microsoft.windows.cswinrt nupkg
2. include Microsoft.Windows.SDK.NET.dll microsoft.windows.sdk.net nupkg

Add-Type -AssemblyName <the two above assemblies>

In BurntToast, remove lines like 2137 that try to load the types using fully qualified names as those types are projected from different assemblies.

Was able to get `New-BurntToastNotification` to work.

I'd like to get PowerShellGetv3 to manage nuget.org dependencies but until that exists you'll have to pkg your module with those assemblies and load them.

**Comment by iSazonov** [comment]
I see a size of latest version of microsoft.windows.cswinrt package is ~977 Kb. We could add it in PowerShell 7.1 distribution until PowerShellGet addresses dependencies.

**Comment by Windos** [comment]
That was unbelievably easy, thanks for spelling out the work around @SteveL-MSFT!

Also, this whole thing also addresses #2181 as the reflection includes event handling and... that works now:

![Working events](https://user-images.githubusercontent.com/6955786/86530082-c3def080-bf09-11ea-819d-fb48139045f5.png)

![happy dance](https://media.giphy.com/media/XxowRoIpcU3te/giphy.gif)

**Comment by SteveL-MSFT** [comment]
Will have PS-Committee review whether we should just include the necessary assemblies with PS7.1

**Comment by Windos** [comment]
Is that a community call review (and does that mean I'll have to wake up for the next call 😂)?

**Comment by SteveL-MSFT** [comment]
@Windos no, the PS-Committee is separate from the Monthly Community Calls.  PS-Committee meets twice a week to weigh in on certain decisions affecting PowerShell

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we agreed that we will not be redistributing the WinRT assemblies with PowerShell 7.1.  We also agreed to have documentation added to help PowerShell users that want to use WinRT.

**Comment by joeyaiello** [comment]
More generally, we also agreed that we should, as a rule, snap to .NET's decision on API surface area except where there is overwhelming evidence that something has additional value to PS users. E.g. WinForms/WPF are used *heavily* in the PS ecosystem, and make sense to continue including on Windows.

**Comment by Windos** [comment]
Thanks for the quick decision on this. Will work on a module update to include the assemblies.

**Comment by xdhmoore** [comment]
Based on this thread I've been able to successfully use some WinRT classes in PowerShell by importing the two dlls in [this BurntToast folder](https://github.com/Windos/BurntToast/tree/main/BurntToast/lib/Microsoft.Windows.SDK.NET), but I can't figure out how to get or build these dlls from the primary source. Are these on NuGet somewhere?

* Microsoft.Windows.SDK.NET.dll
* WinRT.Runtime.dll

**Comment by Windos** [comment]
@xdhmoore: https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref/

**Comment by anonhostpi** [comment]
You can now fix this with the Import-Package module that I just published to PowerShell gallery.

```powershell
Import-Package "microsoft.windows.sdk.net.ref"
```

It automatically installs (if not already installed) the Microsoft.Windows.SDK.NET.Ref package and imports the whole .nupkg into the PowerShell session.

Small warning though:

That Microsoft package does not make use of the NuGet "runtime" directory, so Import-Package will not know that this package is Windows-specific, and will try to import it, even if you are running it from PowerShell on Linux.

**Comment by pronichkin** [comment]
I am sorry, but can someone please explain to non-programmers how to take advantage of this fix (or some other workaround)? I do not know anything about assemblies, namespaces, runtimes, etc. In my heart, I'm a mere sysadmin writing my 10-20 lines scripts that sometimes need to tackle Windows APIs, and historically PowerShell has been exceptionally good in that.

E.g., considering the basic examples in the very first message in this thread (or slighly more complex code samples [like this](https://gist.github.com/pronichkin/9d5caaf86329c3098e2a9f23d0c07bdd)), what exactly needs to be changed so that they work in PS7? (And, preferably, still work in PS5.1).

And I apologize if this has been already documented. Unfortunately, Internet search for "winRT PowerShell" currently gives you this thread as the most relevant link and not some documentation page.

**Comment by iSazonov** [comment]
> @PowerShell/powershell-committee reviewed this, we agreed that we will not be redistributing the WinRT assemblies with PowerShell 7.1. We also agreed to have documentation added to help PowerShell users that want to use WinRT.

@sdwheeler Have we the docs or a doc issue?

**Comment by sdwheeler** [comment]
> @sdwheeler Sean Wheeler FTE Have we the docs or a doc issue?

@iSazonov No we don't have docs or a docs issue. Please open a docs issue and provide the necessary information needed for the docs.

**Comment by iSazonov** [comment]
I created doc issue but don't have specific information for this documentation. I hope the participants in this discussion will post steps for using WinRT there.

**Comment by Xavron** [comment]
@pronichkin

You can actually just run whatever code on the older PowerShell by wrapping stuff with eg `powershell { }` Its that simple to run the script code in another installed powershell version. I have pwsh as newer PS and powershell as older one. One result can be a script stuck running and that just means the code needs adjustment.

If you have an error like in OP, and an older installed PS version where it works, then you can do this as long as there's an old enough installed PS version available. You just need to figure out where to wrap your scripts or code to work best.

To me that is simpler and better than doing anything above and I use it but it depends on your situation.

I can't help you further on this. Just giving a hint of something possible that you can do =)

**Comment by denis-komarov** [comment]
@pronichkin 
@iSazonov 

For the current version 7.5 it works like this.
Install a NuGet package, for example, for a current user (or, if you want, for everyone or even in a separate catalog):
```powershell
Install-PSResource -Repository 'NuGetGallery' -Name 'Microsoft.Windows.SDK.NET.Ref' -Scope 'CurrentUser' -SkipDependencyCheck -TrustRepository
```
Now WinRT can be called like this:
```powershell
#  load assembly/DLL

Get-InstalledPSResource -Name 'Microsoft.Windows.SDK.NET.Ref' -Scope 'CurrentUser' |
Sort-Object -Top 1 -Property @{ Expression = { [version] $_.Version } ; Descending = $true } |
ForEach-Object { "$($_.InstalledLocation)\$($_.Name)\$($_.Version)\lib\*.dll" }    |
Get-ChildItem -Recurse -File -Force                                                |
ForEach-Object { Add-Type -Path $_.FullName }

#  call WinRT

$SystemDiagnosticInfo = [Windows.System.Diagnostics.SystemDiagnosticInfo]::GetForCurrentSystem()

$SystemMemoryUsageReport = $SystemDiagnosticInfo.MemoryUsage.GetReport()

$SystemMemoryUsageReport |
Format-Table -Property @{ n = 'Available (Gb)'; e = { $_.AvailableSizeInBytes     / 1GB } }, 
                       @{ n = 'Total (Gb)'    ; e = { $_.TotalPhysicalSizeInBytes / 1GB } } -AutoSize
```
