### ISSUE TITLE
Date and time calculation ：11-11=12？

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#13040]
## Steps to reproduce

```powershell
PS /root> get-date
2020年6月27日星期六 上午11:43:43

PS /root> (get-date) - [timespan]::FromHours(11)    
2020年6月27日星期六 上午12:44:01

PS /root> (get-date) - [timespan]::FromHours(10)    
2020年6月27日星期六 上午1:44:06
```

## Expected behavior
11-11 return 0

## Actual behavior
11-11 return 12

## Environment data
powershell v7.02 on linux
powershell v7.1.4 on win

**Comment by KalleOlaviNiemitalo** [comment]
The problem must be in how the time is displayed, not in how it is computed. What do these output?

- `[DateTime]::new(2020, 6, 27, 0, 44, 6).ToString("F")`
- `$PSCulture`
- `[CultureInfo]::CurrentCulture.DateTimeFormat.FullDateTimePattern`
- `[CultureInfo]::GetCultureInfo($PSCulture).DateTimeFormat.FullDateTimePattern`

The last two would normally be the same unless there is a user-specific override.

**Comment by mklement0** [comment]
@KalleOlaviNiemitalo is correct: in AM/PM-based date/time formats (_12_-hour-based formats), the hour from midnight to 1 AM is expressed as `12:mm`.

Therefore, what is `00:44:01` in 24-hour format (44 minutes and 1 second past midnight) corresponds to `12:44:01` in AM/PM format.

The default output formatting of [`[datetime]`](https://docs.microsoft.com/en-US/dotnet/api/System.DateTime) instances, as output by `Get-Date` cmdlet is determined as follows (`$this` represent the `[datetime]` instance at hand):

```powershell
"{0} {1}" -f $this.ToLongDateString(), $this.ToLongTimeString()
```

The [`.ToLongDateString()`](https://docs.microsoft.com/en-US/dotnet/api/system.datetime.tolongdatestring) / [`.ToLongTimeString()`](https://docs.microsoft.com/en-US/dotnet/api/system.datetime.tolongtimestring) methods correspond to the `"D"` / `"T"` [standard date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) (e.g., `(Get-Date).ToString("D")`, `(Get-Date).ToString("T")`), as determined by the _current culture_, and as also reflected in `(Get-Culture).DateTimeFormat.LongDatePattern` and `(Get-Culture).DateTimeFormat.LongTimePattern`.

It is formatting data (`Get-FormatData System.DateTime`) associated with type `System.DateTime` (`[datetime]`) that tells PowerShell to use the `DateTime` property of  instances of that type for display output. `DateTime` is a script-block-based property (type `ScriptProperty`)  that  PowerShell attaches to `[datetime]` instances via its ETS (Extended Type System; `Get-TypeData System.DateTime`); the expression above is the relevant part of the script block for the default display, which can be modified by changing an instance's `DisplayHint` ETS property, which, however only `[datetime]` instances directly output by `Get-Date` have.

---

Note that if you _implicitly stringify_ a `[datetime]` instance inside an _expandable string_ (`"..."`; e.g., `"$(Get-Date)"`), you get a _different_ representation, namely the one output by  a call to `.ToString([cultureinfo]::InvariantCulture)`.
In string interpolation contexts and when casting, PowerShell uses the  [_invariant_ culture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture), which means that the resulting format is _always the same_, irrespective of what the culture currently in effect is. 
That is, `"$(Get-Date)"` is _always_ equivalent to `(Get-Date).ToString([cultureinfo]::InvariantCulture)`.

In the absence of an explicit date/time format string passed to the `.ToString()` method, `"G"` is the default, which "represents a combination of the short date (`"d"`) and long time (`"T"`) patterns, separated by a space". In an expandable string in PowerShell, the format string used for `[datetime]` instances is therefore _always_ `[cultureinfo]::InvariantCulture.DateTimeFormat.ShortDatePattern + ' ' + [cultureinfo]::InvariantCulture.DateTimeFormat.LongTimePattern` which results in `MM/dd/yyyy HH:mm:ss`.

Note the use of `HH` to format the hours, which means that you _always_ get _24-hour_ format, unlike with the culture-sensitive direct display output (where it is the current culture that determines whether 24-hour or AM/PM format is used).

(By contrast, if you _explicitly_ call `.ToString()` on a `[datetime]` instance - without arguments - , you get the _current culture_'s `"G"` formatting.
That is, `(Get-Date).ToString()` is the same as `(Get-Date).ToString('G')`, which is the same as `(Get-Date).ToString('G', [cultureinfo]::CurrentCulture)`.)

---

Therefore, placing your command inside an expandable string would have displayed the hours in 24-hour format, where the correct subtraction of the time span is immediately obvious:

```powershell
# Output format is the same, irrespective of what culture is current.
PS> "$(([datetime] '2020-06-27T11:44:01') - [timespan]::FromHours(11))"
06/27/2020 00:44:01
```

**Comment by kasini3000** [comment]
woo，Anti-human design，linux date same.

thanks for answer，KalleOlaviNiemitalo，mklement0 

0hour:
[DateTime]::new(2020, 6, 27, 0, 44, 6).ToString("F")
2020年6月27日星期六 上午12:44:06

12hour:
 [DateTime]::new(2020, 6, 27, 12, 44, 6).ToString("F")
2020年6月27日星期六 下午12:44:06

23hour:
[DateTime]::new(2020, 6, 27, 23, 44, 6).ToString("F")
2020年6月27日星期六 下午11:44:06

**Comment by mklement0** [comment]
Well, it is _human_ design: it reflects a deeply engrained cultural convention that _humans_ are familiar with, despite its inconsistency.

However, this only applies if the convention used is indeed _culture-appropriate_, and it sounds like that is the real problem here (I'm assuming `zh-Hans-CN` (Chinese, Simplified (China mainland)) as the current culture):

```powershell
# PowerShell Core, all platforms: *12-hour time format.
PS> pwsh -noprofile { [cultureinfo]::CurrentCulture = 'zh-Hans-CN'; [DateTime]::new(2020, 6, 27, 0, 44, 6).ToString("F") }
2020年6月27日 星期六 上午12:44:06

# Windows PowerShell: *24*-hour time format.
PS> pwsh -noprofile { [cultureinfo]::CurrentCulture = 'zh-Hans-CN'; [DateTime]::new(2020, 6, 27, 0, 44, 6).ToString("F") }
2020年6月27日 0:44:06
```

.NET Core uses a different source of culture information than the legacy Windows-only .NET framework, it seems, and in .NET Core the Chinese time format is defined as a _12_-hour (AM/PM) format.

**_If_ this is incorrect, I encourage you to file a [.NET Core bug report](https://github.com/dotnet/runtime/issues/new/choose)**, though this _may_ ultimately have to be reported as a [CLDR bug](http://cldr.unicode.org/index/bug-reports) - I am not sure (and, if .NET Core is indeed based on CLDR, there's also a possibility that a CLDR release in which this has been fixed may already exist, but hasn't been integrated into .NET Core yet).
