### ISSUE TITLE
Ensure that newest-release information is current on the repo home page and for the install-powershell.ps1 script

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13047]
Preview 4 was released on 2020-06-25 and the in-session notification of the new version is already being displayed when you create a preview 3 session.

As of this writing, 3 days later:

* The links on the repo home page (https://github.com/PowerShell/PowerShell) still point to preview *3*.
* https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json also still points to preview *3* - this file is what https://aka.ms/install-powershell.ps1 relies on, so running with `-Preview` currently installs an _obsolete_ preview.

Please:

* Correct the problem manually for now.

* In the future, ensure that updating this information becomes an _automated_ part of the release process, so that the information is guaranteed to be current everywhere.

## Steps to reproduce

```powershell
# As of 28 Jun 2020:
(irm https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json).PreviewReleaseTag | Should -Be v7.1.0-preview.4
```

## Expected behavior

The test should succeed.

## Actual behavior

```none
Expected: 'v7.1.0-preview.4'
But was:  'v7.1.0-preview.3'
```

## Environment data

```none
PowerShell Core 7.1.0-preview.4
```

**Comment by iSazonov** [comment]
@mklement0 Preview5 will be released in days due to a bug in Preview4 packaging.

**Comment by mklement0** [comment]
Thanks, @iSazonov - does that mean that the automated process suggested in the OP already _is_ in place, and was overridden manually in this case, due to the issue you mention?

Since preview 4 wasn't removed as a whole, and since the update notification appeared on session startup, I presume https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json could have pointed to preview 4 in the meantime, which would enable installation via https://aka.ms/install-powershell.ps1, given that this installation method isn't affected, right?

**Comment by iSazonov** [comment]
@mklement0 To publish new version we should merge some PRs. And we merged one for Preview4 before the bug was discovered. Since it is only preview MSFT team is in no hurry. I hope they make updates today.
