### ISSUE TITLE
IsReservedDeviceName does not recognize CONIN$, CONOUT$

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [PowerShell/PowerShell#13046]
# Steps to reproduce

```powershell
"hello" > world
Move-Item world CONOUT$
```

## Expected behavior

```none
Move-Item: Cannot process path 'C:\Temp\u\CONOUT$' because the target represents a reserved device name.
```

## Actual behavior

Move-Item outputs `hello` to the console. After that, neither `world` nor `CONOUT$` exists as a file in the directory.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Notes

<https://github.com/PowerShell/PowerShell/blob/ab7460365ffdd40e1c3ae67958a27f210c6b594a/src/System.Management.Automation/engine/Utils.cs#L1254-L1256>

That also lists `CLOCK$`, `COM0`, and `LPT0` even though those names are not reserved in Win32. IIRC, MS-DOS has a `CLOCK$` or `CONFIG$` device.

**Comment by davidreis97** [comment]
Hi, having a go at this one.
