### ISSUE TITLE
Feature Request: "Always-On-Top" 

### ISSUE THREAD

**Issue by pf35301** [PowerShell/PowerShell#13050]
## Summary of the new feature/enhancement
I want to show powershell window always on top.
or if I can do this, let me know.

**Comment by SeeminglyScience** [comment]
PowerShell itself doesn't have any options for this, but it also doesn't really have a way to surface it.  You can use win32 API's (or I think sysinternals might have a tool for it?) to set something up like this yourself, but if you'd like the feature baked into conhost/terminal you'd want to file the issue on [microsoft/terminal](https://github.com/microsoft/terminal) or feedback hub/user voice.

**Comment by HumanEquivalentUnit** [comment]
PowerShell doesn't control how it is displayed on screen, it has to be run inside a terminal program like PowerShell ISE, or Visual Studio Code, or the most basic one is Windows Console Host. It's up to them to be "always on top" or not, and I don't think any of them have that option.

If you are willing to try another terminal program, [ConEmu](https://conemu.github.io/) is a popular one which can run PowerShell and has [Always on top settings](https://conemu.github.io/en/SettingsAppearance.html).

**Comment by pf35301** [comment]
ok. I'll try. thank you.
