### ISSUE TITLE
Create a `touch` equivalent in pwsh

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#13054]
## Summary of the new feature/enhancement
If there is not a definitive way to `touch` a file, there should be. I searched Issues, but did not readily see one. If there is one, please reply with the Issue or PR number.

There are a variety of solutions proposed on the Internet; some more competent than others.
## Proposed technical implementation details (optional)
Perhaps `Set` is not the best verb for this. I would propose:
```
Set-TouchFile
Set-Alias -Name touch -Value Set-TouchFile -Option ReadOnly
```

**Comment by ThomasNieto** [comment]
If you just need to create a blank file you can use: `New-Item -Path abc.txt -Type File`

**Comment by vexx32** [comment]
I'd probably call it something like `Update-FileDateTime` if we were to mirror `touch` as much as possible really.

**Comment by Liturgist** [comment]
> If you just need to create a blank file you can use: `New-Item -Path abc.txt -Type File`

That would only be a partial solution.

**Comment by Liturgist** [comment]
> I'd probably call it something like `Update-FileDateTime` if we were to mirror `touch` as much as possible really.

That name could be used. But, to me the verb Update implies that something exists to be updated. If it does not exist, `touch` creates a new file.

**Comment by Liturgist** [comment]
Would this work on any provider other than FileSystem?

```
function touch {
    Param(
        [Parameter(Mandatory=$true)]
        [string]$Path
    )

    if (Test-Path -LiteralPath $Path) {
        (Get-Item -Path $Path).LastWriteTime = Get-Date
    } else {
        New-Item -Type File -Path $Path
    }
}
```

**Comment by vexx32** [comment]
Not unless that provider also has a LastWriteTime property on its returned objects that is settable.

I'm also not sure if the .NET objects used for the filesystem provider even support setting the last write time / will persist that change to disk.

**Comment by Liturgist** [comment]
@vexx32 , it works on Windows PowerShell 5.1. I have not yet tried it on PowerShell Core.

**Comment by rkeithhill** [comment]
.NET Core supports setting `LastAccesTime` and `LastWriteTime` - https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.lastwritetime?view=netcore-3.1

**Comment by iSazonov** [comment]
A workaround for `touch` so simple in PowerShell as example above shows that no need is to add this as new cmdlet.

**Comment by vexx32** [comment]
@iSazonov that only works when using it to create new items. It doesn't work the same for updating the last write time of existing items.

**Comment by ThomasNieto** [comment]
Related discussion about touch functionality (update LastWriteTime or create file) #11677

**Comment by HumanEquivalentUnit** [comment]
See also: https://github.com/PowerShell/PowerShell/issues/8621

@Liturgist switching between `LiteralPath` and `Path` in your code could be a bug - the file you test, and the file(s) whose datetime you update might be different.
