### ISSUE TITLE
Changelog for v7.1.0-preview.4 is missing from master

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13052]
This has occurred previously, see #12665 (v7.1.0-preview.2)

IMO there should be a "merge branch 'release/v7.1.0-preview.4' into master" step in the release process.

**Comment by iSazonov** [comment]
The Preview4 is broken and obsolete. After a fix new Preview5 will be pulled.

**Comment by xtqqczze** [comment]
In any case, this was fixed by 2f949b7b9
