### ISSUE TITLE
Updating minor versions from Windows Terminal commandline

### ISSUE THREAD

**Issue by markolbert** [PowerShell/PowerShell#13051]
Every time I launch Terminal I get a notice about there being a new version (7.0.2). Terminal starts up running 7.0.1.

I've tried to update powershell from the commandline by running:

```
dotnet tool update --global PowerShell --version 7.0.2
```

but, while that works, the next time I launch Terminal I'm back to the same update message.

How do I update powershell from the command line?

**Comment by mklement0** [comment]
Did you originally install via `dotnet tool`? Perhaps you now have parallel versions installed, and the non-dotnet-tool-installed version takes precedence? (Try `Get-Command -All pwsh`).

**Comment by markolbert** [comment]
That's it, thanx! I've just uninstalled the version I installed with the downloaded installer and the issue is resolved.
