### ISSUE TITLE
7.1.0-preview.4 - 2020-06-25 missing msix package

### ISSUE THREAD

**Issue by wbpluto** [PowerShell/PowerShell#13058]
7.1.0-preview.4 - 2020-06-25 missing msix package

**Comment by iSazonov** [comment]
7.1.0-preview.4 is broken on Windows. 7.1.0-preview.5 will be released soon.

**Comment by rjmholt** [comment]
Also, the MSIX is currently blocked by other factors external to the PS team. We're waiting on a solution before we can ship another MSIX

**Comment by wbpluto** [comment]
Please provide MSIX package as soon as possible. Store App is easy to deploy and manage. If it is not Store App, I will refuse to install it.
