### ISSUE TITLE
Ensure system PATH Environment variable is updated correctly on all *nix platforms for PowerShellGet Scripts

### ISSUE THREAD

**Issue by raghushantha** [PowerShell/PowerShell#1306]
On Windows, the PATH environment variable is updated upon Script installation using PowerShellGet.

We need to ensure this happens consistently on all *nix platforms also

**Comment by Jaykul** [comment]
Why bother updating profiles for other shells? The scripts aren't going to work there anyway (at least, not yet, and probably not at ever, unless PowerShell is registered as a shell interpreter, **and** we convince the whole PowerShell community to put shebang lines in anything that works on Core...

Just (offer to) update PowerShell's profile, let them know about it, and move on?

**Comment by SteveL-MSFT** [comment]
This issue was moved to PowerShell/PowerShellGet#29
