### ISSUE TITLE
.NET MAUI in PowerShell

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#13063]
Does .NET MAUI mean that PowerShell will include a GUI environment? Are there any implications?

https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/

**Comment by iSazonov** [comment]
@Liturgist All PowerShell UI investigations live in https://github.com/PowerShell/GraphicalTools. As I know they are waiting MAUI preview to continue a work on PowerShell GUI cmdlets.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Indeed, @iSazonov: more specifically, @Liturgist, "https://github.com/PowerShell/GraphicalTools/issues/101".
