### ISSUE TITLE
Non-nullable parameter best practices

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13067]
I'm writing my first binary PowerShell module and have C# 8 with non-nullable reference type checking enabled. I have a cmdlet with a string parameter called `Name`. The parameter has the `ValidateNotNull` attribute for PS to check if `Name` is null and error out. The compiler outputs a warning about the uninitialized string. 

What are the best practices for non-nullable parameters where PS does a null check?

## Steps to reproduce

```powershell
[Cmdlet(VerbsCommon.Find, "Thing")]
public sealed class FindThing : PSCmdlet
{
    
    [Parameter()]
    [ValidateNotNull]
    // PS does a null check and errors.
    // Compiler produces this warning:
    // Non-nullable property 'Name' is uninitialized. Consider declaring the property as nullable.
    public string Name { get; set; }

    protected override void ProcessRecord()
    {
        // do thing
    }
}
```

**Comment by vexx32** [comment]
In that case you can do one of two things:

1. Set a default value of `string.Empty` just to satisfy the compiler, or
2. "Assure" the compiler that it should never be null, effectively. I believe the pattern looks something like this:

```cs
public string Name { get; set; } = null!;
```

**Comment by ThomasNieto** [comment]
Thanks @vexx32. I was trying to use the null-forgiving operator but put it in the wrong spot.

**Comment by vexx32** [comment]
I still put it in the wrong place all the time, it's very confusing! 😂
