### ISSUE TITLE
add to Reslove-DnsName cmdlet -mDNS option

### ISSUE THREAD

**Issue by pintomeitar** [PowerShell/PowerShell#13062]
I think that if Resolve-DnsName would have the mDNS option it can be very useful just like the -UseLlmnrOnly. It's seems that dnsapi.dll(which is used by Resolve-DnsName) already implements mDNS . 
mDNS is very common on local network and can help researchers in a lot of situations.

**Comment by iSazonov** [comment]
@pintomeitar The cmdlet is not in the repo. It is in DnsClient module which is a Windows component. You should use other channels for your request (UserVoice site, MSFT forums and so on).
