### ISSUE TITLE
Cryptic error message on new symbolic link missing value

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#13073]
## Steps to reproduce

```powershell
NI -TY S .
```

## Expected behavior

```none
Supply values for the following parameters:
Value:
```

## Actual behavior

```none
New-Item: .
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is ConciseView issue.

On the other hand, we could better check the parameters

**Comment by yecril71pl** [comment]
`$ERROR | SELECT -INDEX 0 | % EXCEPTION | % MESSAGE` is ‘.’.  There is no way for a formatter to display it better.

**Comment by iSazonov** [comment]
The fix should be here https://github.com/PowerShell/PowerShell/blob/d1aa11e367581736ffea570722cee93815c07a41/src/System.Management.Automation/engine/SessionStateContainer.cs#L3501-L3511
