### ISSUE TITLE
Make PowerShell available for npm installation.

### ISSUE THREAD

**Issue by aetos382** [PowerShell/PowerShell#13083]
## Summary of the new feature/enhancement

I want to do the following.

- I can install and run PowerShell in the current user scope with the following commands.

```
npm install -g @microsoft/powershell
pwsh
```

- I can install and run PowerShell in current directory with the following commands.

```
npm install -D @microsoft/powershell
npx pwsh
```

- I can use PowerShell immediately by cloning the repository from Git with the following commands.

```
git clone <repo-url>
cd <repo-dir>
npm install
npx pwsh
```

- And I can write the following in [package.json](https://docs.npmjs.com/files/package.json#scripts).

```json
{
  "script": {
    "clean": "Remove-Item ./output -Recursive"
  }
}
```

By default, the commands in the npm script are executed using the native OS shell (cmd on Windows, bash on Linux).
Therefore, the same commands cannot be used on Windows and Linux.
We can use npm modules to absorb OS differences, but it's more natural to write them in the shell's native language.

So I think it is useful to be able to write the npm scripts in PowerShell.
The shell that runs the npm scripts can be configured in a [.npmrc file](https://docs.npmjs.com/misc/config#script-shell). It can be placed in a project directory.

Similarly, PowerShell can be installed as a dotnet Global Tool.
In this case, the .NET Core SDK must be installed first, and the .NET Core SDK cannot be installed with platform-independent commands (PowerShell is required to use the [dotnet-install.ps1 script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)).

**Comment by kilasuit** [comment]
theres this - https://rannn505.github.io/node-powershell/

does that help at all?

**Comment by aetos382** [comment]
@kilasuit No. It's a module to call PowerShell from NodeJS, PowerShell needs to be installed separately.

My suggestion is on how to install PowerShell itself.

**Comment by ALIENQuake** [comment]
@aetos382 How about using this: https://www.npmjs.com/package/pwsh

**Comment by aetos382** [comment]
@ALIENQuake Thank you! That is exactly what I was looking for.
