### ISSUE TITLE
Add a Invoke-PrivateCommand into PowerShell.Core

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#13087]
Allows the use of Privately Scoped Functions/Cmdlets in a more PowerShell friendly way than doing this

```powershell
$module = Get-Module MyModule
& $module { Get-PrivateFunction }
```

## Proposed technical implementation details (optional)

Using pure PowerShell this can be done like so - https://github.com/kilasuit/Invoke-PrivateCommand/blob/master/InvokePrivateCommand.ps1

But I am not sure how you'd do the same in C# to add this to Microsoft.PowerShell.Core (or Microsoft.PowerShell.Utility)

It is potentially going to be easier adding this as a script function that is shipped alongside and loaded as part of the loading of the module anyway.

**Comment by vexx32** [comment]
Adding on some of @SeeminglyScience's suggestions from the PS discord in case they were missed:

```cs
// moduleInfo should be an instance of PSModuleInfo
var sb = moduleInfo.NewBoundScriptBlock(originalSb);
PowerShell.Create(RunspaceMode.CurrentRunspace).AddScript(". $args[0]", useLocalScope: false).AddArgument(sb)
```

and

```sb
InvokeCommand.InvokeScript(moduleInfo.SessionState, scriptBlock.Ast.GetScriptBlock())
```

**Comment by SeeminglyScience** [comment]
Note that `Ast.GetScriptBlock()` is only required if `scriptBlock` has an existing session state affinity (Due to a bug, see #12883).  If it was created with `ScriptBlock.Create` it can be skipped.

**Comment by SeeminglyScience** [comment]
That said, the original description reads like you're looking to add a `Invoke-PrivateCommand` as a built in command?  If so, maybe a separate issue should be opened discussing the use cases before you put in the effort of drafting a PR.

**Comment by kilasuit** [comment]
> 
> 
> That said, the original description reads like you're looking to add a `Invoke-PrivateCommand` as a built in command? If so, maybe a separate issue should be opened discussing the use cases before you put in the effort of drafting a PR.

I opened this issue to see if there was a desire to have this built in or not (my view it should be). As otherwise I'll release it as a seperate module just making use of the PowerShell implementation due to it's simplicity.

**Comment by iSazonov** [comment]
Adding to the Core only makes sense if commonly used scenarios exist. It also violates an intent of the author of the module. Private functions can be changed by the author at any time. This cannot be used on a regular basis. Similar code could be in an analysis module (like Pester) but not in Core.

**Comment by vexx32** [comment]
Pester provides an `InModuleScope` function for this purpose, yeah. Dunno if I think it should / needs to be a default cmdlet. 🤷

**Comment by JamesWTruher** [comment]
This seems like a great thing for the gallery. However, this is not something that we would like to perpetuate as it breaks the model that the module author has when he doesn't want to export a function, so putting it in PowerShell is not something we would entertain.
