### ISSUE TITLE
Cannot Expand-Archive to a PSDrive destination

### ISSUE THREAD

**Issue by BobPusateri** [PowerShell/PowerShell#13088]
Unable to expand a local .zip archive to a remote location (specified via PSDrive) using `Expand-Archive`.

## Steps to reproduce

```
# Create a PSDrive object mapped to a path on a remote computer
New-PSDrive -Name MappedDrive -PSProvider FileSystem -Root '\\192.x.x.x\Folder'

# Try to use Expand-Archive to expand a .zip file to the PSDrive path
Expand-Archive -Path deploy.zip -DestinationPath 'MappedDrive:\'
```

## Expected behavior

Expecting zip file to be expanded into the `MappedDrive` remote location

## Actual behavior

Throws an error:
`Cannot find drive. A drive with the name 'MappedDrive' does not exist.`

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by KalleOlaviNiemitalo** [comment]
Cannot reproduce with PowerShell 7.0.2 and Microsoft.PowerShell.Archive 1.2.5 on Microsoft Windows 10.0.19041. However, I was using a computer name rather than an IPv4 address in the UNC path.

This was apparently fixed several years ago in <https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/3>.

**Comment by KalleOlaviNiemitalo** [comment]
However, if I first do `Import-Module -Name Microsoft.PowerShell.Archive -UseWindowsPowerShell`, then `Expand-Archive` will not see `MappedDrive:`.

Perhaps @BobPusateri is getting the Windows PowerShell version of Microsoft.PowerShell.Archive imported for some reason.

**Comment by daxian-dbw** [comment]
@BobPusateri Can you install the latest `Microsoft.PowerShell.Archive` module and give it a go?
