### ISSUE TITLE
WSMan client library was not found while using CoreCLRHost

### ISSUE THREAD

**Issue by spKhan00** [PowerShell/PowerShell#13092]
I built CoreCLRHost for communication between Java-c++-Dotnet to establish ExchangeOnline session. Followed steps provided from Microsoft docs for sample coreclr host. i got the below exception
```This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.```

Based on my understanding we need to include dlls while coreclr_initialize 'TRUSTED_PLATFORM_ASSEMBLIES'. is there any way to include Shared libraries(libpsrpclient.so) as well. i guess that's the cause for this exception.

## Steps to reproduce
1. published donet library as self-contained
2. c++ shared library to establish connection with dotnetcore
3. used that shared library in java.

## Environment data
OS: Centos 7
$PSVersionTable 
PSVersion.6.2.4
PSEdition.Core
GitCommitId.6.2.4
OS.Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Thu Sep 19 19:59:54 IST 2019
Platform.Unix
PSCompatibleVersions.System.Version[]
PSRemotingProtocolVersion.2.3
SerializationVersion.1.1.0.1
WSManStackVersion.3.0

**Comment by jborean93** [comment]
I don't have any knowledge on the CoreCLRHost part or even around the Java -> C++ -> .NET interop side but PowerShell itself includes the `libpsrpclient.so` inside it's folder. On Fedora the PowerShell files are at `/opt/microsoft/powershell/7` and I would assume Centos is similar but we can see that the compiled library is there as well as the deps it requires by running this `ldd` command:

```bash
ldd /opt/microsoft/powershell/7/libpsrpclient.so
```

This produces the following output on my host

```text
ldd: warning: you do not have execution permission for `/opt/microsoft/powershell/7/libpsrpclient.so'
        linux-vdso.so.1 (0x00007fffd8851000)
        libmi.so => /opt/microsoft/powershell/7/libmi.so (0x00007f987e546000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f987e504000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f987e33a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f987e333000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f987e321000)
        libssl.so.1.0.0 => /opt/microsoft/powershell/7/libssl.so.1.0.0 (0x00007f987e2af000)
        libcrypto.so.1.0.0 => /opt/microsoft/powershell/7/libcrypto.so.1.0.0 (0x00007f987e042000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f987e96b000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f987e016000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f987dffc000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f987dff4000)
```

We can see that all the dependencies are installed and present so the library should load properly if it's on the correct path. PowerShell will do that work for you when starting up but if you are trying to do something from pure .NET you probably need to set `LD_LIBRARY_PATH` to the PowerShell folder so the process can actually see that binary. Even then I don't even know if that will solve your problem.

**Comment by spKhan00** [comment]
Thanks for your input. The thing is in production environment there wont be powersell installed. thats why i used sellf-containted publish method. Since there is no powershell installed in that machine i may need to include the shared libraries as well while colreclr initialization. i have set java.library.path instead of LD_LIBRARY_PATH .

**Comment by spKhan00** [comment]
Adding another point: I figured everyone told to create symlink for libssl.so and libcrypto.so in /usr/local/lib. 
Is this necessary?

**Comment by iSazonov** [comment]
WSMan lib is deprecated. Recommendation is to use SSH remoting in new projects.
If you still want to use WSMan you could review related issues in the repo. There are workarounds to get WSMan working (specially with SSH versions).

**Comment by spKhan00** [comment]
@iSazonov  thanks for your suggestion. can you please give an example of how to connect to Exchange Online using ssh in powershell. i did the all the steps mentioned in [here](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7#set-up-on-an-ubuntu-1604-linux-computer)

**Comment by iSazonov** [comment]
@spKhan00 It is still under development https://twitter.com/gregtaylor_msft/status/1280657888642392064

**Comment by JamesWTruher** [comment]
You can distribute the libmi and libpsrp assemblies in your app since they are MIT licensed. We agree that you should continue to pursue the SSH solution.
