### ISSUE TITLE
Start-Process adds extra space to command line

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#13094]
## Steps to reproduce

```powershell
Start-Process powershell.exe

# or

Start-Process pwsh.exe
```

In the new window run the following

```powershell
Add-Type -Namespace Kernel32 -Name NativeMethods -MemberDefinition @'
[DllImport("Kernel32.dll", CharSet = CharSet.Unicode)]
public static extern IntPtr GetCommandLineW();
'@

$linePtr = [Kernel32.NativeMethods]::GetCommandLinew()
$cmdLine = [System.Runtime.InteropServices.Marshal]::PtrToStringUni($linePtr)

"'{0}'" -f $cmdLine
```

## Expected behavior

```text
'"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"'

# or

'"C:\Program Files\PowerShell\7\pwsh.exe"'
```

_Note: the path is dependent on where powershell is installed, this also affects v7_

## Actual behavior

```none
'"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" '

# or

'"C:\Program Files\PowerShell\7\pwsh.exe" '
```

The actual command line contains a trailing space. If you were to start the process with arguments the trailing space comes after the arguments. This is not a problem when using `System.Diagnostics.Process` directly or the call operator.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

# or

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
After further testing, pwsh only has an issue when no arguments are supplied. WinPS has an issue even with the arguments but that's not really covered by this repo here.

**Comment by kvprasoon** [comment]
something to do with formatting, this happens only when `"'{0}'" -f $cmdLine` , just `$cmdLine` works as expected.

**Comment by jborean93** [comment]
That’s because you can’t see the space without the single quotes around it. I only did that format string to easily demonstrate what is happening.

**Comment by kvprasoon** [comment]
yep correct.

and it wont be from https://github.com/PowerShell/PowerShell/blob/58c371ca31d9e1b72da5d94821f2d670da5b4dfa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2003

`targetMessage` is displayed only when `-WhatIf` is used.

**Comment by jborean93** [comment]
Ah fair enough.

You may want to close https://github.com/PowerShell/PowerShell/issues/13097 as that’s a duplicate of this.

**Comment by kvprasoon** [comment]
I believe the issue is in `System.Diagnostics.Process` as I see the same behavior that way and happens only if  new windows is spawned.

**Comment by jborean93** [comment]
I don't think so, when looking at the code PowerShell is actually calling [CreateProcess](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) [here](https://github.com/PowerShell/PowerShell/blob/58c371ca31d9e1b72da5d94821f2d670da5b4dfa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2540) or [CreateProcessWithLogon](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) (if credentials were specified) [here](https://github.com/PowerShell/PowerShell/blob/58c371ca31d9e1b72da5d94821f2d670da5b4dfa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2484).

My guess as to what is happening is that [the check for ArgumentList](https://github.com/PowerShell/PowerShell/blob/58c371ca31d9e1b72da5d94821f2d670da5b4dfa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L1877-L1880) is true because while the ArgumentList is empty it is not null and the join operation is pretty much the same as `' ' -eq [string]::Join([String[]]@(), ' ')`. When the actual command line is being built it has a check on the argumentlist [here](https://github.com/PowerShell/PowerShell/blob/58c371ca31d9e1b72da5d94821f2d670da5b4dfa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2313-L2317). At this particular point in time `arguments` is equals to `' '` which is neither null or an empty string so it is appended to the command line to run. What I don't understand is why there's only 1 space, there should be 2 based on the assumption above. I don't have access to my dev environment so I can't step into the code to 100% check this but I don't think the issue lies in .NET but rather in PowerShell.

**Comment by jborean93** [comment]
Sorry for the false alarm, just stepped through the code and I was wrong. By default `Start-Process` will use `System.Diagnostics.Process` unless other parameters are set which in this case it is not.

When running the code

```powershell
$psi = [System.Diagnostics.ProcessStartInfo]@{
    FileName = 'pwsh'
    UseShellExecute = $true
}
[System.Diagnostics.Process]::Start($psi)
```

I see the same behaviour that `Start-Process` shows which indicates the problem is there and not in PowerShell. Even when forcing the code path to use the powershell call to `CreateProcess` by added `-LoadUserProfile` the command line args are fine.

**Comment by kvprasoon** [comment]
> My guess as to what is happening is that [the check for ArgumentList](https://github.com/PowerShell/PowerShell/blob/58c371ca31d9e1b72da5d94821f2d670da5b4dfa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L1877-L1880) is true because while the ArgumentList is empty it is not null and the join operation is pretty much the same as `' ' -eq [string]::Join([String[]]@(), ' ')`.

:-) I was around this for hours with no luck and finally confirmed its in `System.Diagnostics.Process` by testing in that way...

**Comment by jborean93** [comment]
Yea I should have listened to the experts :) thanks for your help.
