### ISSUE TITLE
Can not run Get-NetAdapter from SDK

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#13096]
I need to call Get-NetAdapter from Powershell SDK. When I call directly, I get "The term 'Get-NetAdapter' is not recognized as the name of a cmdlet, function, script file, or operable program". So I tried calling Import-Module NetApdater and receive large number of errors.

## Steps to reproduce

```powershell
Import-Module NetAdapter
Get-NetAdapter
```

## Expected behavior
I expect to receive the list of Network Adapters.

## Actual behavior
File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapter.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterAdvancedProperty.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterBinding.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterChecksumOffload.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterEncapsulatedPacketTaskOffload.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterHardwareInfo.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterIPsecOffload.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterLso.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterPowerManagement.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterQos.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterRdma.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterRsc.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterRss.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterSriov.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterSriovVf.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterStatistics.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterVmq.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterVmqQueue.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterVPort.cmdletDefinition.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterPacketDirect.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,File C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetAdapter\MSFT_NetAdapterUso.cdxml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.-2146233087,The term 'Get-NetAdapter' is not recognized as the name of a cmdlet, function, script file, or operable program.

## Environment data
```
PSVersion=7.0.2
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3
```

**Comment by doctordns** [comment]
Set-ExecutionPolicy RemoteSigned

Then try again.

**Comment by erenturkm** [comment]
Hi,

Sorry I didnt make myself clear. This is not an interactive shell issue, it is a SDK call that I am invoking from c# code. The code that I ran is running on my local machine with Remote Execution already set to remote signed. 
1) When I run this command from Windows Powershell it runs perfectly. 
2) All other powershell commands that I invoke from SDK are running perfectly.

**Comment by vexx32** [comment]
From the errors, it would appear the SDK API is seeing a different execution policy than powershell sees interactively, so you may still need to set it for the SDK by invoking that command before trying to call Get-NetAdapter.

Get-NetAdapter itself is not part of PowerShell 7, the module is a Windows component, so it has to be loaded over Windows Compatibility remoting. @adityapatwardhan may have additional insight into the precise issue you're seeing, as well.

**Comment by erenturkm** [comment]
Setting this solved the issue. I am writing the command I issued in case somebody else needs it:
set-ExecutionPolicy -scope Process remotesigned -Force
Setting this in code was challanging since documentation does not state the argument dictionary has to be <string,dynamic> and Force arguement needs to be of type SwitchParameter. It would be nice to update the page:
[https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addparameters?view=powershellsdk-7.0.0#System_Management_Automation_PowerShell_AddParameters_System_Collections_IDictionary_](url)
