### ISSUE TITLE
Pipelining between ffmpeg and ffplay is broken 

### ISSUE THREAD

**Issue by tats-u** [PowerShell/PowerShell#13105]
## Steps to reproduce

```powershell
cinst -y ffmpeg # with administrator's privilege & Chocolatey
ffmpeg -i foo.mp4 -c:a copy -c:v copy -f matroska - | ffplay -i -
```

## Expected behavior

The video is played in a new playback window.

## Actual behavior

The following message appears:

```none
pipe:: Invalid data found when processing input
```

No window pops up, and the video doesn't start to be played.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This bug is also reproduced in Windows PowerShell 5.1 but not in CMD.

**Comment by vexx32** [comment]
I'm almost certain this is related to #1908 - ffplay is almost certainly expecting bytes to be input in order to play the video, but PowerShell is getting in the way and attempting to interpret the data first.

**Comment by tats-u** [comment]
@vexx32 Agree with you.  I'll watch the issue.
