### ISSUE TITLE
Pipelining a Simple object to Get-Service is broken

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#13103]
## Steps to reproduce

```powershell
$ob1 = @{
    ServiceName = 'BITS'
}

$ob1 | Get-Service
```

## Expected behavior

```none
returns the BITS Service
```

## Actual behavior

```none
Get-Service: Cannot find any service with service name 'System.Collections.Hashtable'.
```

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.20161
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by vexx32** [comment]
Get-Service / the pipeline parameter binder isn't expecting hashtable input; if you cast it to PSCustomObject before piping, it works as expected. 🙂

**Comment by kilasuit** [comment]
That shouldn't matter though (& why I said simple object 😉)

**Comment by vexx32** [comment]
? It's the same for any commands that use ValueFromPipelineByPropertyName, isn't it? 

Is there a case where that does work (and the parameter isn't itself typed as hashtable)?

**Comment by kvprasoon** [comment]
`ValueFromPipelineByPropertyName` means it takes value from property, here `ServiceName` is not a property of that hashtable, but a key and key is the property here...
