### ISSUE TITLE
Invoke-RestMethod does not perform HTTP connection pooling

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13109]
The `Invoke-RestMethod` cmdlet since PowerShell 6 does not perform HTTP connection pooling.

The behaviour in Windows PowerShell 5.1 was to perform connection pooling, so there is a performance regression in PowerShell Core.

*This issue was discovered in #12764.*

## Steps to reproduce

While running a packet capture, compare execution of the following with execution under Windows PowerShell 5.1:

```powershell
(Measure-Command {
    (1..100).ForEach{
        Invoke-RestMethod -Uri "https://postman-echo.com/get?i=$_"
    }
}).TotalSeconds
```

## Expected behavior

A single HTTP connection is used for all requests, as was the case in Windows PowerShell 5.1.

## Actual behavior

A new HTTP connection is opened for every request and a TLS handshake is perfomed for each request, resulting in much worse performance than Windows PowerShell 5.1.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Why duplicate #12764?

**Comment by xtqqczze** [comment]
@iSazonov There was a lot of unrelated discussion and misleading information in #12764 so I thught it would be good to open a new issue with a clear description of the issue, is this not the way?

**Comment by iSazonov** [comment]
@xtqqczze That would be nice, but most of the issues are similarly confusing. Since we have already a conclusion in #12764 we can close current issue.

**Comment by xtqqczze** [comment]
I will close this issue, perhaps you could edit the title of #12764 for clarity?
