### ISSUE TITLE
It takes half an hour to start and open

### ISSUE THREAD

**Issue by shijunti19** [PowerShell/PowerShell#13116]
## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

windows10 

7.0.2

It takes half an hour to start and open

![image](https://user-images.githubusercontent.com/5392211/86548889-a3964c80-bf70-11ea-9de2-5d85c8ade8d8.png)

Only the first start of the day occurs

**Comment by iSazonov** [comment]
I guess there is a delayed request to Internet. Can you inspect network connections in the time?

**Comment by shijunti19** [comment]
@iSazonov Isn't it a local app
I'm in China, it may be delayed

**Comment by iSazonov** [comment]
I think we could add a timeout or async to resolve the issue.

**Comment by daxian-dbw** [comment]
Only the update notification feature requires network, but it's not a hard requirement. It performs the update check on a background thread, which should never block the startup of PowerShell.
@shijunti19 What version are you using? Are you able to find a folder named after the version in `$env:LOCALAPPDATA\Microsoft\PowerShell`, if so, can you share what files are in that folder (e.g. folder named `7.0.1`)?

In your screenshot, nothing is displayed in the pwsh console, which make me suspect Windows Defender being the culprit.
