### ISSUE TITLE
Get-AzStorageContainer Cannot Return "PublicAccess" attribute if using AD-based context

### ISSUE THREAD

**Issue by JoelCBennett** [PowerShell/PowerShell#13118]
Get-AzStorageContainer command utilizes a -context to authenticate and retrieve values for a storage account.  The 'PublicAccess' attribute only returns values if the -context supplied uses a storage account key.  If the context utilizes AD credentials it fails to return any values.  

See below:
![repo](https://user-images.githubusercontent.com/35112555/86613682-cae81c00-bf66-11ea-9f87-de3401dc9f3a.jpg)

**Comment by vexx32** [comment]
The `Az` module isn't maintained by the PowerShell team @JoelCBennett. You'll need to file this issue in the [azure-powershell](https://github.com/Azure/azure-powershell) repo. 🙂

**Comment by JoelCBennett** [comment]
Thanks @vexx32.  Opened new issue there ([link](https://github.com/Azure/azure-powershell/issues/12338)) and closing this one.
