### ISSUE TITLE
Get-NetAdapter returns Null Status value

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#13111]
I am using Powershell SDK through c# code to gather information on Network Adapters. I am getting most of the information corretly. Here correctly means command returns same results for Windows Powershell 5.1. (Most of the properties returned are null/empty which is ok. The only case is Status property. 

## Steps to reproduce

```powershell
Set-ExecutionPolicy with Parameters Force:true,ExecutionPolicy:remotesigned,scope:process
Get-NetAdapter
```
On the returned PSObject collection, I can get all other properties correctly (such as Name). 
However difference is when I ran the code: (string)obj.Properties.Match("Status")[0].Value.
I checked the property value is  string.

## Expected behavior
I expect string values such as Up, Disconnected which is what I get when I ran the command from Powershell Console.

## Actual behavior
I receive null

## Environment data
```none
PSVersion=7.0.2
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3
```

**Comment by iSazonov** [comment]
> (string)obj.Properties.Match("Status")[0].Value.

This looks very strange. I'd expect `obj` is array. Can you share more info about your code?

**Comment by daxian-dbw** [comment]
The `Status` property is a `ScriptProperty`, meaning that `...[0].Value` will trigger the getter script to run in the Runspace where call `Get-NetAdapter`. Is that Runspace still available when you are running `(string)obj.Properties.Match("Status")[0].Value`?

**Comment by erenturkm** [comment]
Sorry it took me longer than anticipated. I realized that returned values are not the same type as Windows Powershell. Windows Powershell returns Strings whereas PowershellSDK returns integer values. Parsing as integer solved the problem. I dont think this change is documented. Can we put it so somebody else does not spend time on this?
