### ISSUE TITLE
Move back to .NET's DirectoryInfo.MoveTo code when .NET bug is fixed

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13126]
From https://github.com/PowerShell/PowerShell/issues/13039.

.NET does not implicitly allow cross-filesystem directory moves: https://github.com/dotnet/runtime/issues/31149.

This was mitigated in https://github.com/PowerShell/PowerShell/pull/13044, but when .NET updates their implementation, we should fall back to using their API as before.

**Comment by doctordns** [comment]
Has the .NET team updated their implementation?
