### ISSUE TITLE
CommandInfo.ResolveParameter throws NullReferenceException sometimes

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13127]
From https://github.com/PowerShell/PSScriptAnalyzer/issues/1538.

PSScriptAnalyzer tries to get the value of `Export-ModuleMember`'s parameters by calling the `CommandInfo.ResolveParameter()` call [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/d04c03907b4a4b675bcc3cec3a32cbf3c4ee2d64/Engine/Helper.cs#L438).

This calls into PowerShell here:

https://github.com/PowerShell/PowerShell/blob/b1e998046e12ebe5da9dee479f20d479aa2256d7/src/System.Management.Automation/engine/CommandInfo.cs#L593-L605

As with various other `CommandInfo` members, this appears not to be threadsafe and the call sometimes throws an NRE.

**Comment by vexx32** [comment]
related: #12865
