### ISSUE TITLE
Markdown static tests should be restricted

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13121]
`Verify Markdown Links` test experiences frequent intermittent failures due to transient issues, e.g.:
* https://github.com/PowerShell/PowerShell/pull/13086/checks?check_run_id=842863871

We could increase CI reliabilty by restricting markdown static tests to PRs where markdown files are modified.

We should also run `markdown-link-check` test on a schedule to detect dead links seperately from normal CI. There are Github actions available that will run the check and automatically open an issue if broken links are found.

**Comment by iSazonov** [comment]
I agree.

/cc @TravisEz13

**Comment by TravisEz13** [comment]
Please ask of the feature from AzDevOps

**Comment by TravisEz13** [comment]
Related existing requests:
https://developercommunity.visualstudio.com/content/idea/366363/support-wildcards-in-trigger-path-filters-1.html

**Comment by iSazonov** [comment]
I think @xtqqczze suggests to replace our static Markdown link test with follow action https://github.com/marketplace/actions/markdown-link-check
1. Check only modified Markdown files on PR pull event
2. Check all Markdown files on daily scheduled tests

**Comment by TravisEz13** [comment]
checking the markdown links needs to remain a CI check.

**Comment by TravisEz13** [comment]
Using github actions is viable, but there is a risk that when release branches get merged back that links will be broken as we do released with AzDevOps

**Comment by xtqqczze** [comment]
@TravisEz13 So we need to ensure we run `markdown-link-check` on merge commits as well, e.g. 8ad954d2853d522a56a9fb80bb3f4e3cbe29c112.

**Comment by TravisEz13** [comment]
> @TravisEz13 So we need to ensure we run markdown-link-check on merge commits as well, e.g. 8ad954d.

Yes, in that case, it should not be restricted to changed files.

**Comment by xtqqczze** [comment]
@iSazonov Please reopen.
