### ISSUE TITLE
Scripts using -Parallel fail when run using Microsoft.PowerShell.SDK and a publish runtime flag

### ISSUE THREAD

**Issue by normj** [PowerShell/PowerShell#13132]
We use the `Microsoft.PowerShell.SDK (7.0.2)` NuGet package in a .NET Core 3.1 application to execute PowerShell 7 scripts in a Linux environment. We have found when the .NET application is published with the runtime **linux-x64** to reduce the package size, scripts that use the `ForEach-Object -Parallel ...` fail with the following error message.
```
[Error] - The term 'Write-Host' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
If the .NET application is packaged without specifying runtime the script runs correctly. Also if the ForEach-Object command does not use the `-Parallel` parameter the script runs correctly.

## Steps to reproduce

Here is the test PowerShell script attempting to run through the .NET Application. 
```powershell
$SharedVariable = "Hello Shared Variable"
@(1..100) | ForEach-Object -Parallel { 
    $i = $_
    Write-Host "Running against: $i for SharedVariable: $($using:SharedVariable)"
}
```

Here is a trimmed down version of the .NET Core 3.1 application that is used for running the PowerShell script.

```csharp
using System;
using System.IO;
using System.Management.Automation;

namespace PowerShellScriptRunner
{
    class Program
    {
        static Exception _lastException;

        static void Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.Error.WriteLine("The first argument should the path to the script to run.");
                System.Environment.Exit(-1);
            }
            else if (!File.Exists(args[0]))
            {
                Console.Error.WriteLine($"Script {args[0]} can not be found.");
                System.Environment.Exit(-2);
            }

            var executingScript = File.ReadAllText(args[0]);
            Console.WriteLine("Executing script:");
            Console.WriteLine(executingScript);
            var ps = PowerShell.Create();
            SetupStreamHandlers(ps);

            ps.AddScript(executingScript);

            var output = new PSDataCollection<PSObject>();
            var asyncResult = ps.BeginInvoke<PSObject, PSObject>(null, output);

            while (!asyncResult.IsCompleted)
            {
                asyncResult.AsyncWaitHandle.WaitOne(500);
            }
        }

        private static void SetupStreamHandlers(PowerShell ps)
        {

            Func<string, EventHandler<DataAddingEventArgs>> _loggerFactory = (prefix) =>
            {
                EventHandler<DataAddingEventArgs> handler = (sender, e) =>
                {
                    var message = e?.ItemAdded?.ToString();

                    LogMessage(prefix, message);

                    var errorRecord = e?.ItemAdded as ErrorRecord;
                    if (errorRecord?.Exception != null)
                    {
                        _lastException = errorRecord.Exception;
                    }
                };
                return handler;
            };

            ps.Streams.Verbose.DataAdding += _loggerFactory("Verbose");
            ps.Streams.Information.DataAdding += _loggerFactory("Information");
            ps.Streams.Warning.DataAdding += _loggerFactory("Warning");
            ps.Streams.Error.DataAdding += _loggerFactory("Error");
        }

        private static void LogMessage(string prefix, string message)
        {
            if (string.IsNullOrEmpty(message))
            {
                return;
            }

            if (!string.IsNullOrEmpty(prefix))
            {
                message = $"[{prefix}] - {message}";
            }

            Console.WriteLine(message);
        }
    }
}
```

On a Linux environment publish the project using the following command
```
dotnet publish --configuration Release --self-contained false --runtime linux-x64
```
then execute the program
```
dotnet exec .\bin\Release\netcoreapp3.1\linux-x64\publish\PowerShellScriptRunner.dll <path-to-psscriptfile>
```

Script fails with the following error messages. 
```
[Error] - The term 'Write-Host' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
If i repeat the steps above but remove the `--runtime linux-x64` switch there is no problem.

One theory I have is with the `--runtime linux-x64` switch the assemblies from the publish\runtimes folder get flatten out at the root of the publish folder. But there is also the Modules in the publish\runtimes\unix\lib\netcoreapp3.1\Modules and maybe something about the modules not being direct children of the assemblies anymore is causing the failure.

On a side note the value `--runtime win-x64` also doesn't seem to work either but for a different error. That error is 
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning)
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
```
Which I can see the `Microsoft.Management.Infrastructure.dll` is missing in the publish folder but `Microsoft.Management.Infrastructure.CimCmdlets.dll` is there. This isn't my use case as I'm on Linux but maybe related somehow. 

## Expected behavior

Scripts using `-Parallel` argument execute successfully.

**Comment by iSazonov** [comment]
@PaulHigin Could you please look the issue?

**Comment by PaulHigin** [comment]
This looks like a build/publishing error where required core module binaries are not available, at runtime.  ForeEach-Object -Parallel code creates runspaces with default initial state that includes all core modules.  But for some reason runtime command discovery cannot find them.

@daxian-dbw  has worked on the SDK.  Dongbo can you comment on why `Write-Host` cannot be found at runtime?

**Comment by normj** [comment]
Sorry I should have put this in the original post but sometimes I get the following error as well which might provide more clues.

```
2020-07-07 15:13:21: [Error] - An unexpected error has occurred while processing ForEach-Object -Parallel input. This may mean that some of the piped input did not get processed. Error: System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/2473a89a-8513-49db-bf23-51d8af91a349/.local/share/powershell/Modules'.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at System.Management.Automation.Platform.SelectProductNameForDirectory(XDG_Type dirpath)
   at System.Management.Automation.ModuleIntrinsics.GetPersonalModulePath()
   at System.Management.Automation.ModuleIntrinsics.GetModulePath(String currentProcessModulePath, String hklmMachineModulePath, String hkcuUserModulePath)
   at System.Management.Automation.ModuleIntrinsics.SetModulePath()
   at System.Management.Automation.ModuleIntrinsics..ctor(ExecutionContext context)
   at System.Management.Automation.ExecutionContext.InitializeCommon(AutomationEngine engine, PSHost hostInterface)
   at System.Management.Automation.ExecutionContext..ctor(AutomationEngine engine, PSHost hostInterface, InitialSessionState initialSessionState)
   at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, InitialSessionState iss)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.LocalRunspace.OpenHelper(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
   at System.Management.Automation.Runspaces.RunspaceBase.Open()
   at System.Management.Automation.PSTasks.PSTaskBase.Start()
   at System.Management.Automation.PSTasks.PSTaskPool.Add(PSTaskBase task)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.<InitParallelParameterSet>b__63_2(Object _).
```

**Comment by daxian-dbw** [comment]
> One theory I have is with the --runtime linux-x64 switch the assemblies from the publish\runtimes folder get flatten out at the root of the publish folder. But there is also the Modules in the publish\runtimes\unix\lib\netcoreapp3.1\Modules and maybe something about the modules not being direct children of the assemblies anymore is causing the failure.

This is exactly the cause. The Runspace created by `ForEach-Object -Parallel` depends on all modules being present in the modules path, which are not.
It's a known limitation in the the `Microsoft.PowerShell.SDK` package that the deployment of built-in modules doesn't work when building with the specific RID. See https://github.com/PowerShell/PowerShell/pull/11832#issuecomment-584882314.

The workaround is to have a post build step, to copy the `Modules` folder right under the publish folder, where `System.Management.Automation.dll` is located. The `Modules` folders are at `<publish-folder>\unix\lib\netcoreapp3.1\Modules` and `<publish-folder>\win\lib\netcoreapp3.1\Modules` for Linux/macOS and Windows respective.

--------------------------------------------

For the issue regarding `Microsoft.Management.Infrastructure`, it looks like a bug in the nuget packaging of `Microsoft.Management.Infrastructure.Runtime.Win` -- it doesn't have a runtime folder named `win-x64`, and hence `dotnet publish -r win-x64` cannot get the corresponding libraries deployed. @adityapatwardhan Can you please take a look?

**Comment by daxian-dbw** [comment]
> Error: System.IO.DirectoryNotFoundException

No idea why `Directory.CreateDirectory` could fail with this exception. It doesn't require any part of the path to be present ... The code is [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L312). The path in use was `/tmp/2473a89a-8513-49db-bf23-51d8af91a349/.local/share/powershell/Modules` and `/tmp/2473a89a-8513-49db-bf23-51d8af91a349` was already successfully created by [this code](https://github.com/PowerShell/PowerShell/blob/5ad8a5916f37835feb0476396ff7c79e748c2577/src/System.Management.Automation/utils/PsUtils.cs#L145-L165).

**Comment by adityapatwardhan** [comment]
Thanks for the detailed bug report! I really appreciate that.

For `Microsoft.Management.Infrastructure` we cannot have `win-x64` folder as the dependencies are OS specific. Hence, we have to use OS specific runtimes. 

Also, can you try with `Microsoft.Management.Infrastructure` version `2.0.0`? That fixed a bunch of issues around runtimes.

**Comment by daxian-dbw** [comment]
@adityapatwardhan FYI, the user was using `Microsoft.PowerShell.SDK` 7.0.2, which reference the 2.0.0 version of `Microsoft.Management.Infrastructure`.

**Comment by normj** [comment]
Thanks for the information. I'm able to put a work around in our publishing tooling that moves around the Modules folder.
