### ISSUE TITLE
No MSIX packages for v7.1.0-preview.5

### ISSUE THREAD

**Issue by TBBle** [PowerShell/PowerShell#13131]
There's no MSIX packages for the [v7.1.0-preview.5 release](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.5).

I could understand if they are being left out due to the various issues noted in this Issue tracker around suprise sandboxing, but I can't see any hint that this was a deliberate decision.

**Comment by TBBle** [comment]
Ah, right after I lodge the ticket, I realise that this was probably deliberate, as noted in https://github.com/PowerShell/PowerShell/issues/13058#issuecomment-652668046:
> Also, the MSIX is currently blocked by other factors external to the PS team. We're waiting on a solution before we can ship another MSIX

I hadn't looked hard at that issue, as I assumed it was due to the misupgrade issue in the v7.1.0-preview.4 release.

Probably better to have mentioned this in the release notes though, so people know to switch from the MSIX to the MSI in the meantime.

**Comment by wbpluto** [comment]
Please provide MSIX package as soon as possible. Store App is easy to deploy and manage. If it is not Store App, I will refuse to install it.

**Comment by adityapatwardhan** [comment]
Update the release page with this information. Thanks for pointing it out.
