### ISSUE TITLE
Cursor is blinking while I am using zsh on WSL

### ISSUE THREAD

**Issue by F-Unction** [PowerShell/PowerShell#13133]
## Steps to reproduce

```powershell
pwsh
wsl
[backspaceKey]
```

## Expected behavior

```
nothing will happen, the cursor will not move any more
```

## Actual behavior

```
the cursor is always blinking, it moves to next line then move back.
```
![GIF 2020-7-8 18-53-03](https://user-images.githubusercontent.com/51352133/86910510-625a9400-c14c-11ea-8ad4-e2e2377bd8ee.gif)
```
I an not sure is it a bug of PowerShell, when I use cmd it will happen.
when I use the terminal directly in VisualStudioCode, it will also happen,
but when I use it in VSCode WSL - remote , it won't happen.
```
![GIF 2020-7-8 18-58-38](https://user-images.githubusercontent.com/51352133/86910971-19570f80-c14d-11ea-900d-b28a3c450554.gif)

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
> I an not sure is it a bug of PowerShell, when I use cmd it will happen.
when I use the terminal directly in VisualStudioCode, it will also happen,
but when I use it in VSCode WSL - remote , it won't happen.

If it happens in cmd too, then it's likely not a powershell issue. When running VSCode WSL remote, the terminal runs directly in the WSL distro, so it's different from running `wsl` from within cmd or powershell.

**Comment by F-Unction** [comment]
> > I an not sure is it a bug of PowerShell, when I use cmd it will happen.
> > when I use the terminal directly in VisualStudioCode, it will also happen,
> > but when I use it in VSCode WSL - remote , it won't happen.
> 
> If it happens in cmd too, then it's likely not a powershell issue. When running VSCode WSL remote, the terminal runs directly in the WSL distro, so it's different from running from within cmd or powershell.`wsl`

So how to solve it. Is it a bug of WSL?

**Comment by daxian-dbw** [comment]
I don't really know where to report the issue. You should definitely try reporting it to WSL, or open an issue in https://github.com/microsoft/terminal asking about this, and maybe they can point you to the right place.

**Comment by F-Unction** [comment]
Thank you
