### ISSUE TITLE
Make SMA.PowerShell.CreateNestedPowerShell() useful or deprecate it

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13135]
From https://github.com/PowerShell/PowerShellEditorServices/issues/1295#issuecomment-655650376.

Rewriting PSES' pipeline implementation currently, and I've hit a number of issues in the nested prompt implementation.

A big one has been in how to get a new PowerShell instance for PowerShell execution.

In my initial implementation I used `pwsh.CreateNestedPowerShell()` but had issues with that:
  - first with the parent pipeline being null (because of `PSThreadOptions.ReuseThread`) and `CreateNestedPowerShell` giving me a PowerShell where `IsNested` is true, but not `IsChild`,
  - then because of apartment state...

So I moved to using `PowerShell.Create(RunspaceMode.CurrentRunspace)`.

So my question is, what's the difference between the two? How are they meant to be used?

**Comment by KirkMunro** [comment]
@rjmholt Thank you for asking this question! I have been troubleshooting problems that I have not been able to explain for a few days using Windows PowerShell from within a custom application, and `CreateNestedPowerShell` ended up being the issue. The moment I switched away from it, the problem went away. Ugh.

One of the symptoms of this that I was seeing was my event handlers for data streams (verbose, warning, information, etc.) working just fine until the moment I would invoke CreateNestedPowerShell, after which the event handlers stopped receiving events. I could see messages being generated (the application also has a custom host, and it was receiving the messages), but the event handlers were just not.

**Comment by JamesWTruher** [comment]
This was originally intended for use when entering a nested prompt (AFAICT - it's still used in the ISE when entering a nested prompt). I'm not sure how much utility it has anymore, but I seem to remember that this how we originally did the EnterNestedPrompt in V1 .

**Comment by rjmholt** [comment]
We should consider either fixing the API or deprecating it

**Comment by rjmholt** [comment]
Reopening since, while we have an explanation of the original intention, the API remains unhelpful

**Comment by MatejKafka** [comment]
@SteveL-MSFT Still relevant, please reopen.
