### ISSUE TITLE
Cannot Change PowerShell 7 Properties With Non-Admin Account

### ISSUE THREAD

**Issue by MrM21632** [PowerShell/PowerShell#13148]
## Steps to reproduce

Sorry if this is a duplicate issue.

1.  Start PowerShell 7 as a regular user (i.e., not an administrator) from the Start Menu (e.g., press Windows key, type "powershell", left-click PowerShell 7).
2.  Right-click top of window, select "Properties."
3.  Change a setting (e.g., Opacity in the "Colors" tab).
4.  Click "OK".

## Expected behavior

The Properties window closes, any changes are saved and persist in future sessions.

## Actual behavior

The following error message window pops up:
```none
Unable to modify the shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\PowerShell 7 (x64).lnk. Check to make sure it has not been deleted or renamed.
```

Changes to properties do not persist in future sessions.

Strangely enough, when opening PowerShell 7 via the context menu, whether or not you choose to run as an administrator, the expected behavior happens.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is how MSI works. The shortcut is protected by OS permissions.
You can create a custom shortcut and modify its properties.

**Comment by dkoehler69** [comment]
I think this issue should be reopened. In Powershell 5 I can change the settings for the local user. Why is it only possible to change the settings as admin for every user in Powershell 7?

**Comment by iSazonov** [comment]
@dkoehler69 If you can reproduce the issue in latest 7.2 Preview please open new issue.

**Comment by jonlandrum** [comment]
This is definitely reproducible in the latest release (7.2.6). No other MSI-installed program has issues saving preferences except for PowerShell.

**Comment by Legend-Master** [comment]
Same problem here (latest release 7.2.6), a work around is to copy the short cut to somewhere else and change the properties then replace the original one...

**Comment by Legend-Master** [comment]
Just run it (the shortcut) as admin, then you can change any thing you want (right click C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\PowerShell 7 (x64).lnk then click Run as administrator)

>In Powershell 5, it is no problem to change the settings, even as a local user.

The windows default PowerShell (5) shorcut is in the user directory so yeah

**Comment by dudung** [comment]
I use it in Windows 11 and the change of properties can only be seen when I run it as Administrator. I use v 1.0.

**Comment by trexneb** [comment]
I think this should be re-opened.  Modifications to properties in PS 7.4.1 are not persistent, whether in Admin mode or not.  It worked in 5.1, and is broke as shit in 7.4.1.  WTFO MS?
