### ISSUE TITLE
Include .NET Core SDK Component options when installing PowerShell

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#13151]
So, since PowerShell 7.0.0 (released 3/4/2020) .NET Core 3.1.2.

PowerShell 7.0.1 (released 5/14/2020) needs "Microsoft Windows Desktop Runtime 3.1.3 (x64)" components for our products to work.

Then, the recent release of PowerShell 7.0.2 (released 6/11/2020), needs "Microsoft Windows Desktop Runtime 3.1.5 (x64)" which breaks out products again.

This is impacting in our effort to keep improving our products as our customers are suffering from these GA updates.

Is there going to be monthly GA updates?

:)

_Originally posted by @MaximoTrinidad in https://github.com/PowerShell/PowerShell/issues/8663#issuecomment-645642429_

**Comment by vexx32** [comment]
The default distributions of PowerShell package their own .NET installations with the application; they have no need to use a machine-wide installation of .NET Core.

If you're installing the framework-dependent packages then that's by design, but otherwise PowerShell is perfectly happy keeping its own .NET Core version separate from any machine-wide .NET installation present.

**Comment by vexx32** [comment]
Are these packages not included in the default distribution on Windows? /cc @adityapatwardhan

**Comment by MaximoTrinidad** [comment]
I think including to "Optionally" install the .NET Core SDK components can alleviate the issue for some third-party products to break.

During the installation, it could detect the previous .NET Core version, then give the option to upgrade.  Or, just give a notification providing the link to download separately the SDK components.

In our case, at SAPIEN Technologies, we only needed the "Microsoft Windows Desktop Runtime 3.1.x (x64)". 

:)

**Comment by MaximoTrinidad** [comment]
@vexx32 

Sorry! I was adding more information.
:)

**Comment by SeeminglyScience** [comment]
@MaximoTrinidad could you clarify if y'all are using the framework dependent install? I was also under the impression this wasn't needed for the standalone.

Also could you clarify why the SDK should be bundled?

**Comment by adityapatwardhan** [comment]
@MaximoTrinidad Thank you for reporting this. Could you please give information about the following:

1. Which package of PowerShell do you use? MSI / Zip / Framework dependent Zip / NuGet packages?
2. PowerShell is a standalone app and ships the .NET runtime within the package. Which would mean the customer machine does not need to have the .NET SDK installed. 

If there are dependencies from the SDK you need to be included in the package, let us know. We can see if those make sense to ship them within the package or in some other form.

**Comment by MaximoTrinidad** [comment]
@SeeminglyScience 

Bundling the SDK can be useful! 

One of our products, we can build Windows Forms application using PowerShell language. In our case, we needed to have the  .NET Core "Desktop" Runtime version matching the one used in the latest PowerShell 7.

Again, **Just A Suggestion** that can provide:

1. Gives a heads up that PowerShell 7 is using a newer .NET Core version. (Sometimes people don't read what's in the update notes).
2. Let the people decided what to install: 
      *  .NET Runtime
      *  ASP.NET Core Runtime
      *  Desktop Runtime

When can we expect the next PowerShell 7 GA with .NET Core 5.0 to be released? Should be soon... Right!

**Comment by MaximoTrinidad** [comment]
@adityapatwardhan 

Greatly Appreciated the response!

Answered:

_1. Which package of PowerShell do you use? MSI / Zip / Framework dependent Zip / NuGet packages?_

* MSI (only).

_2. PowerShell is a standalone app and ships the .NET runtime within the package. Which would mean the customer machine does not need to have the .NET SDK installed._

* Yes! I understand. In our situation has caused headaches to our worldwide customers using our products.

To rectify the issue, we are providing the .NET Core SDK with the product installation. But, there are also, some changes in our product code to support the latest version.  

The fast turn-around of updates to .NET Core has keeping very us busy. 

Don't get me wrong! The way PowerShell is progressing. It's Great!

:)

**Comment by SeeminglyScience** [comment]
> Bundling the SDK can be useful!

The SDK refers to `dotnet build` and the like, pretty exclusively for managing dotnet projects.  Is that what you mean to be requesting?  It is a separate product from the runtime install.

> One of our products, we can build Windows Forms application using PowerShell language. In our case, we needed to have the .NET Core "Desktop" Runtime version matching the one used in the latest PowerShell 7.

Can you elaborate a little on this?  What error message do you get when it's not installed and how specifically are you interacting with PowerShell (e.g. hosting with the PowerShell SDK, running pwsh.exe (if this then what package as @adityapatwardhan asked) , etc)?

**Comment by MaximoTrinidad** [comment]
@SeeminglyScience 

You got to understand... Our products have components that need to be rebuilt each time the framework change to work with PowerShell.  So, our team developers it's working in a solution to reduce this barrier. 

It's not like some time ago Windows Management Frameworks (3.0, 4.0, 5.0) took a couple of years apart to be released. Now, with .NET Core moving at a much faster pace for the last few months, it got us fixing stuff faster.

But, this is our responsibility to keep up with changes in our products.

So, just a suggestion, to have an additional notification during the installation to let people know the framework has been  updated. To at least, in the MSI installation, make the new framework the links available. This way, people may want to install additional components. 

At the same time, I think this will help minimize the impact to our customers when installing PowerShell and using our products.

:)

**Comment by SeeminglyScience** [comment]
> You got to understand... Our products have components that need to be rebuilt each time the framework change in order to work with our PowerShell Host. So, our team developers it's working in a solution to reduce this barrier.

Some additional details would be helpful in determining if this is an application specific problem.  I'm no stranger to how editors and custom hosts work and I don't think I've encountered this.

/cc @TylerLeonhardt @rjmholt if I'm wrong please correct me, have we ever had an issue where the resolution was installing/updating the runtime?

If it is application specific, I think the best action would be to build in the update notification to your application's start up process.

**Comment by TylerLeonhardt** [comment]
I don't recall any such issue, but then again, PowerShell itself is our runtime so maybe we're an exception.

I also work on the [dotnet-interface host](https://dotnet/interactive) which is a global tool and don't recall having this issue either.

**Comment by adityapatwardhan** [comment]
@MaximoTrinidad Almost every time PowerShell releases a revision version update to stable release (non-preview), there will be an update to the .NET framework version. Updating the .NET framework version is the only way PowerShell can consume the security / other fixes that come with the update. It is expected that the application ships the .NET framework binaries with itself. 

We understand that there is a need to potential change code whenever we release an update. So we only release updates when they are high priority fixes.
