### ISSUE TITLE
PowerShell SDK: out-of-process Runspace doesn't allow using proxy.

### ISSUE THREAD

**Issue by tonyoscarad** [PowerShell/PowerShell#13158]
## Steps to reproduce

```powershell
PSSessionOption pSSessionOption = new PSSessionOption
{
pSSessionOption.ProxyAccessType = ProxyAccessType.WinHttpConfig;
}

Runspace runspace = RunspaceFactory.CreateOutOfProcessRunspace(TypeTable.LoadDefaultTypeFiles());
// Runspace runspace = RunspaceFactory.CreateRunspace();
PowerShell powerShell = PowerShell.Create();
powerShell.Runspace = runspace;
powerShell.Commands.AddCommand("Import-Module");
powerShell.Commands.AddParameter("Name", "ExchangeOnlineManagement");
powerShell.Commands.AddCommand("Connect-ExchangeOnline");
PSCredential psCredential = new PSCredential(user, password.ToSecureString());
powerShell.Commands.AddParameter("Credential", psCredential);
powerShell.Commands.AddParameter("PSSessionOption", pSSessionOption);
powerShell.Invoke();
```

## Expected behavior

```none
To connect to Exchange Online
```

## Actual behavior

```none
The module doesn't connect to the internet. If we use RunspaceFactory.CreateRunspace, it works.
```

## Environment data

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```none

```

**Comment by tonyoscarad** [comment]
It doesn't work in other Operating systems too. Tried in different OSes.

**Comment by iSazonov** [comment]
@tonyoscarad The repository is only for PowerShell Core dev process. 
To report Windows PowerShell issue you should use other resources like UserVoice site, MSFT forums and so on.

You could repro on PowerShell Core but Exchange Online module is still not supported on the version.
