### ISSUE TITLE
Feature Request - Code sign Apple pkg

### ISSUE THREAD

**Issue by jshealth** [PowerShell/PowerShell#13159]
## Summary of the new feature/enhancement
As a Mac OSX Powershell user, I want the Powershell pkg for Mac OSX to be code-signed so I do not have to create security exceptions for them

If you try and open the downloaded package
<img width="422" alt="image" src="https://user-images.githubusercontent.com/47585763/87238852-5e2fbe80-c44b-11ea-989b-21efd12fda9f.png">

You need to make a security exception in System Preferences > Security & Privacy
<img width="666" alt="image" src="https://user-images.githubusercontent.com/47585763/87238745-ce3d4500-c449-11ea-8077-536e34285858.png">

## Proposed technical implementation details (optional)
Code-sign packages using Apple's keys and then I will not have to create the exceptions listed above

**Comment by daxian-dbw** [comment]
Loop in @TravisEz13 and @adityapatwardhan

**Comment by adityapatwardhan** [comment]
This is on the backlog with no ETA as of now. There is a workaround by using the `Unblock-File` cmdlet: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7

**Comment by jshealth** [comment]
Unblock-File allows you to run downloaded Powershell
What we're talking about here is if you download the Powershell installer for Mac OS from https://github.com/PowerShell/PowerShell/releases/tag/v7.0.2
e.g.
https://github.com/PowerShell/PowerShell/releases/download/v7.0.2/powershell-7.0.2-osx-x64.pkg

Mac OS Gatekeeper prevents you from running the pkg installer.
The pkg needs to be signed with an Apple Developer certificate so that installing the pkg will not be blocked by Gatekeeper.
See
https://developer.apple.com/developer-id/
https://developer.apple.com/support/code-signing/
https://simplemdm.com/certificate-sign-macos-packages/

**Comment by daxian-dbw** [comment]
Removed the `Resolution-Answered` tag to allow @adityapatwardhan to follow up.

**Comment by TravisEz13** [comment]
@jshealth Our teams that implements signing for us in not prioritizing implementing this type of signing and this issue is already open.
https://github.com/PowerShell/PowerShell/issues/10874

**Comment by jshealth** [comment]
@TravisEz13 Ok
