### ISSUE TITLE
Support for extended-length paths removed in v7

### ISSUE THREAD

**Issue by pjaclark** [PowerShell/PowerShell#13168]
I have several servers that have very long paths. In v5, I was able to use extended-length paths (as detailed in https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) to access files and folders with a path longer than the maximum length. I could access them locally via `\\?\DRIVE:\LONG\PATH` and remotely via `\\?\UNC\SERVER-NAME\SHARE\LONG\PATH`. These no longer work, which has broken nearly every single script I have.

`$PSVersionTable.PSCompatibleVersions` says v7.0.2 should be compatible with 5.1.10032 upwards, but it is not.

## Steps to reproduce

```powershell
Get-ChildItem \\?\C:\Users
```

## Expected behavior
As seen in PSVersion 5.1.17763.1007
```none

    Directory: \\?\C:


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-r---       2019-05-13     01:47                Users
```

## Actual behavior
Returns nothing - no error, no objects
```none

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
PowerShell Core now supports long paths _by default_ - no  opt-in via `\\?\` needed.

Unfortunately, however, using the opt-in in PS Core (which should be a no-op) doesn't work consistently, which is problematic for cross-edition code that must also support Windows PowerShell - see #10805

The workaround in this particular case is to use `-LiteralPath` rather than the (implied) `-Path`.

**Comment by pjaclark** [comment]
The workaround you gave (use `-LiteralPath`) doesn't work with wildcards, so doesn't help me. 

#10805 indicates this is an actual bug, so should be fixed at some point. I think I'll just roll-back to v5 until this bug is solved. Thanks for pointing me at it. This issue isn't in the list of Known Issues with v7, so probably should be added there.

**Comment by daxian-dbw** [comment]
> This issue isn't in the list of Known Issues with v7, so probably should be added there.

@pjaclark Can you please point me to that doc? /cc @sdwheeler.

**Comment by sdwheeler** [comment]
@daxian-dbw https://docs.microsoft.com/powershell/scripting/whats-new/what-s-new-in-powershell-70#breaking-changes-and-improvements

https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-70.md
