### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by mskadu** [PowerShell/PowerShell#13166]
Hello!

I am running pwsh v7.0.2 on RHEL 7.6 (maipo). I have a script that examines and manipulates a large number of XML files. Until recently the same script on a windows 10 machine without issues. But recently we moved to a beefier linux machine for compliance reasons. 

And since then I am seeing the following error message interspersed with normal messages:

_Failed to create CoreCLR, HRESULT: 0x8000405_

I can't seem to find anything useful anywhere else that tells me why this is happening?

## Steps to reproduce

```powershell
nohup find /data/input/lot001/ -name '*.xml' -exec pwsh -File ./MyScript.ps1 {} \; 2>&1 > /data/logs/lot001.log &
```

## Expected behavior

* regular output messages
* script completes execution

## Actual behavior

* regular output messages interspersed with the error message - _Failed to create CoreCLR, HRESULT: 0x8000405_

## Environment data

```powershell
Name                                      Value
-----                                        -------
PSVersion                               7.0.2
PSEdition                                Core
GitCommitId                           7.0.2
OS                                           Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018
Platform                                  Unix
PSCompatibleVersions            {1.0, 2,0, 3.0, 4.0...}
PSRemotingProtocolVersion   2.3
SerializationVersion                1.1.0.1
WSManStackVersion               3.0
```

**Comment by daxian-dbw** [comment]
@mskadu Can you please collect the CoreCLR start-up traces and share with us?
You need to set the environment variables `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=<path>`, see https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-do-i-debug-the-probing-properties-construction.

I suggest to reduce the number of xml files when collecting the traces, so that there won't be a large number of `pwsh` spun up which may result in to much traces.

**Comment by mskadu** [comment]
Am in the process of doing this .. should be back shortly. In the meanwhile, I am seeing the following message in the trace file

> -- Begin breadcrumb write
> Directory core breadcrumbs [] was not specified or found
> Fallback directory core breadcrumbs at [opt/breadcrumbs] was not found
> Breadcrumb store was not obtained... skipping write.

Is this safe to ignore? Or am i doing something wrong?

**Comment by daxian-dbw** [comment]
I'm not very sure about what the breadcrumb thread is supposed to log, but it looks benign. We can ignore this for now.

**Comment by mskadu** [comment]
Hi, i (finally) have the "start-up traces". The file is in MBs and too large to be pasted on here. How are such files generally made available to you?

**Comment by mskadu** [comment]
Here you go [hobsvc-6063_coretrace.log](https://github.com/PowerShell/PowerShell/files/4938281/hobsvc-6063_coretrace.log). Please let me if you need any further details

**Comment by mskadu** [comment]
Here you go:

[13166_coretrace.log](https://github.com/PowerShell/PowerShell/files/4938326/13166_coretrace.log)

Please let me know if you have further questions or need more information

**Comment by daxian-dbw** [comment]
@mskadu At startup, CoreCLR tries to create named pipes for debugging and profiling of the process in `/tmp/`. It could be that the pipe creation fails intermittently when `pwsh` gets started so frequently. Can you please try disabling CoreCLR diagnostics by setting the environment variable `export COMPlus_EnableDiagnostics=0` (as [instructed here](https://github.com/dotnet/coreclr/pull/15878)), and then try running your repro step again to see if that helps?

**Comment by mskadu** [comment]
Thanks. I am checking this and will confirm back shortly.

**Comment by daxian-dbw** [comment]
@mskadu Any luck?

**Comment by mskadu** [comment]
Not yet, I am afraid. Got side-lined by another unrelated issue. 

Please bear with me. I hope to get back to you soon.

**Comment by mskadu** [comment]
I know this is close. But thought I'd let you know this suggestion worked. For people who find this after. Thank you!

**Comment by daxian-dbw** [comment]
@mskadu Good to know that! Thanks for getting back to us.

**Comment by jcoutch** [comment]
I just ran into this with a Alpine container on WSL2.  Adding `COMPlus_EnableDiagnostics=0` worked for me as well.  I happened to search for that environment variable, and ran across this issue:
https://github.com/dotnet/docs/issues/10217

My container is read-only, so it makes sense that disabling diagnostics would fix the issue (if it's writing diagnostics to a read-only folder).

**Comment by alexei-matveev** [comment]
I bet inodes ran out because of many pwsh-invokations, see comments in https://github.com/dotnet/runtime/issues/46462

**Comment by mazhar10** [comment]
> 
> 
> @mskadu At startup, CoreCLR tries to create named pipes for debugging and profiling of the process in `/tmp/`. It could be that the pipe creation fails intermittently when `pwsh` gets started so frequently. Can you please try disabling CoreCLR diagnostics by setting the environment variable `export COMPlus_EnableDiagnostics=0` (as [instructed here](https://github.com/dotnet/coreclr/pull/15878)), and then try running your repro step again to see if that helps?

I tried that with no joy. Here is what  I did:
open a command window.
Execute: set COMPlus_EnableDiagnostics=0
Execute: start pwsh.

pwsh fails with the reported error.
The results are the same if the cmd window is opened as an administrator..

**Comment by daxian-dbw** [comment]
@mazhar10 Please move your comment to the issue that you opened. This issue is already resolved.

**Comment by mazhar10** [comment]
> 
> 
> @mazhar10 Please move your comment to the issue that you opened. This issue is already resolved.

Thanks - I need to pay more attention to the links in notification emails!
