### ISSUE TITLE
Custom classes and thread safe variables 

### ISSUE THREAD

**Issue by montereyharris** [PowerShell/PowerShell#13179]
Issue is I am trying to use parallelization to add a generated object, which is a custom object, to a threadsafe variable. Is this supported? 

My custom class is

class Foo{

[string]$AuditArea
[string]$FooName
[String]$FooId

Foo () {}
}

$Records =  [System.Collections.Concurrent.Concurrentbag[Foo]]::new()
$bar = [Foo]::New()
$Records.tryadd($bar)
MethodException: Cannot convert argument "item", with value: "", for "TryAdd" to type "Foo": "Cannot convert the "Foo" value of type "Foo" to type "Foo"."

**Comment by montereyharris** [comment]
PowerShell Version is is 7.0.2 on Windows 10

**Comment by SeeminglyScience** [comment]
@montereyharris your repro steps work fine as is, but I assume you're redefining the class in each runspace yeah?

If so that won't work, they will have completely different type identities.  That said even if you do copy the `Type` object over, classes are tied to their origin runspace.  Using them in another runspace can cause some major issues (see #12801).

**Comment by ThomasNieto** [comment]
I was able to reproduce your issue by running by redefining the class a second time.

**Comment by montereyharris** [comment]
@SeeminglyScience Yes to make it work I trying to do that. Ok so basically because it is a custom class that doesn't exist across run spaces and I have to redefine it every time it won't work and the practice in of itself is a bad idea. Is this is a limitation of PowerShell classes.

**Comment by SeeminglyScience** [comment]
@montereyharris yeah.  In short, using PowerShell classes in any capacity across runspaces isn't supported at the moment (or for the foreseeable future judging by the lack of momentum in #12801).
