### ISSUE TITLE
Custom Tracing Sources (PSTraceSource)

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13175]
I recently came across the [PSTraceSouce ](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pstracesource?view=powershellsdk-7.0.0) class. Is permitted to add custom tracing sources? The comments for the class seem to indicate tracing is only for the PS team but the remark is commented out and doesn't appear on the class documentation wiki.

https://github.com/PowerShell/PowerShell/blob/9d05561d9c9788546050281a68456775d68fd7ef/src/System.Management.Automation/utils/MshTraceSource.cs#L11-L46

**Comment by vexx32** [comment]
Given it's in the `Internal` namespace, it's definitely not part of the supported API surface. But it's probably possible?

**Comment by ThomasNieto** [comment]
Where did you see that it's in the `Internal` namespace? If I'm not mistaken it looks to be in the `System.Management.Automation` namespace. The methods to actually output data to the tracing system are currently marked as internal. I could see the tracing system being useful for writing custom PSProviders. There are tracing categories for all the built-in providers and associated base code.

**Comment by vexx32** [comment]
Ah you're right, I misread. Never mind, then. 🙂

**Comment by daxian-dbw** [comment]
> Is permitted to add custom tracing sources?

I don't think you are able to to do it today, as `PSTraceSourceAttribute` and `GetTracer` are internal and so is the constructor of `PSTraceSourceAttribute`. Whether it should be made accessible can be discussed here.

**Comment by ThomasNieto** [comment]
@daxian-dbw thanks for the info. I saw #13186 where PowerShell could be broken into different subsystems (assemblies). If that was done wouldn't these classes and methods need to be made public for those subsystems to access it?

**Comment by SeeminglyScience** [comment]
@ThomasNieto Not necessarily. They could just use `InternalsVisibleTo`. Or make it pubternal.
