### ISSUE TITLE
Help -Online test: verify that the retrieved content is relevant

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#13177]
## Summary of the new feature/enhancement

Currently the tests in `HelpSystem.OnlineHelp.Tests.ps1` verify that the help URI is specified for selected commands.  Please add a test that the content behind that URI contains online help for that command (not an error and not any bogus irrelevant stuff).

## Proposed technical implementation details (optional)

1. `Invoke-WebRequest` on the URI.
2. If request failed, skip test.
3. Assert that the request status is OK.
4. Assert that the retrieved content contains the command name.

**Comment by yecril71pl** [comment]
Triggered by https://github.com/PowerShell/PowerShell/issues/7795#issuecomment-658653817 .

**Comment by iSazonov** [comment]
I think the tests should be in another repository because they is not related to PowerShell dev process in the repo.

/cc @sdwheeler

**Comment by yecril71pl** [comment]
Should they be pulled by PowerShell-Docs?
