### ISSUE TITLE
Fix Windows Event-ID 53504 PowerShellCore text description.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#13178]
## Summary of the new feature/enhancement

Currently, in the PowerShellCore, for the event-id 53504, is displaying the following message:
"Windows PowerShell has started an IPC listening thread on process: 10108 in AppDomain: DefaultAppDomain."

Notice that in the event text is displaying "Windows PowerShell" when it should display "PowerShell".

At the same time, I think it's time to get rid of "PowerShellCore" and simply use "PowerShell".

![PSEvent_01_2020-07-15_9-09-51](https://user-images.githubusercontent.com/19892435/87549886-5f93fd80-c67c-11ea-98c5-95ea01fab83c.jpg)

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT - I believe the manifest for the win events come from here: https://github.com/PowerShell/PowerShell-Native/blob/master/src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man

Once I get an ack, I will transfer the issue to  https://github.com/PowerShell/PowerShell-Native

**Comment by MaximoTrinidad** [comment]
@adityapatwardhan 

In today's PowerShell Community Call, @SteveL-MSFT asked me to create a PR for this one.
Let me know what you think.

:)

**Comment by MaximoTrinidad** [comment]
@adityapatwardhan / @SteveL-MSFT 

Hum! Looking at the code in PowerShell.Core.Instrumentation.man...

What you guys want to do with the "ISE" portion of it?  Knowing that there's no ISE for PowerShellCore.
Can it be removed?

:)
