### ISSUE TITLE
Powershell 7 remoting to ubuntu 20.04 doesn't work

### ISSUE THREAD

**Issue by manjeetbhatia** [PowerShell/PowerShell#13185]
## Steps to reproduce
icm to ubuntu 20.04
icm -HostName "hostname" -UserName "username" -ScriptBlock {ip a}

## Expected behavior

It should be able to return results if powershell is configured in client and server

## Actual behavior

It doesn't work

```

## Environment data



```none

```

**Comment by daxian-dbw** [comment]
As far as I know, PowerShell is not supported in Ubuntu 20.04 yet. /cc @adityapatwardhan to confirm.

**Comment by iSazonov** [comment]
See #12626
