### ISSUE TITLE
Remote session and CLI UI hangs

### ISSUE THREAD

**Issue by majkinetor** [PowerShell/PowerShell#13180]
Any CLI tool that has some kind of UI (curses and friends) blocks when used in remote session. I tried vim, less, nano, micro, fzf, basically whatever and the result is the same.

```ps1
icm -Computer remote -Script { ls | less}  #blocks 
icm -Computer remote -Script { ls } | less #works
```

This behavior exists since the early days of PowerShell.

**Comment by daxian-dbw** [comment]
This is by design. PowerShell remoting protocol is not a terminal protocol and it doesn't work with interactive native commands.

**Comment by majkinetor** [comment]
Is there any plan on working on something like that in the future ?

**Comment by daxian-dbw** [comment]
As far as I know, there is no plan to change the PowerShell Remoting Protocol (PSRP). The SSH remoting in PowerShell only uses PSRP (PSRP over ssh), so the behavior will be the same.
