### ISSUE TITLE
compare-object 25x slower without sorting first

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#13208]
Compare-object seems to sort both arrays before comparing them, usually as strings.  But the sort algorithm seems very slow.  Pre-sorting both arrays with sort-object is much faster.  Even without pre-sorting, these two arrays are considered equal by compare-object.

EDIT:
Ok, so maybe compare-object doesn't sort the two files, but by default matches every line in one file with every line in the other file, unless setting the -syncwindow?  If anything, this shows how confusing this command is, and how slow it can be with big files.  I've seen people assume that every object property is compared by default.

## Steps to reproduce

```powershell
$a1 = 1..45kb
$a2 = 45kb..1
measure-command { compare ($a1) ($a2) } | % seconds
```

## Expected behavior

```none
1
```

## Actual behavior

```none
25
```

Workaround, about 25x faster.  I tried larger arrays, 1..700kb, without the sort, but after 8 minutes I gave up.  With sorting, it took about 15 seconds.

```powershell
$a1 = 1..45kb
$a2 = 45kb..1
measure-command { compare ($a1|sort) ($a2|sort) } | % seconds
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> this shows how confusing this command is

You should not rely on your own expectations, you should read the documentation and examples before using the cmdlet (which is over 15 years old).
