### ISSUE TITLE
Feature Request: Get-Volume formatdata shouldn't present the FileSystemLabel property under a misleading name.

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#13207]
I'd like to be able to look at the output of a cmdlet, and then `select` some of the property names I see. The formating data for `Get-Volume` presents the property `FileSystemLabel` as `FriendlyName`, and then `select FriendlyName` doesn't work; it is not clear how to get from the presented name to the real name.

Feature request: Present it as `FileSystemLabel`, it's clear, helpful, and matches terminology elsewhere in Windows (`diskpart` and `gcim Win32_Volume` call it "Label", not Friendly Name, for example).

**Comment by PK-Patomsiri** [comment]
Ok

**Comment by iSazonov** [comment]
Yes, this sometimes happens because the authors of the modules want to make the output more understandable and beautiful. _We cannot prevent them from doing this._

You could get a raw output with:
```powershell
dir | Format-Custom -Depth 1
```
