### ISSUE TITLE
Unable to resolve package source after interrupting Update-Module and re-run

### ISSUE THREAD

**Issue by tigerinus** [PowerShell/PowerShell#13215]
## Steps to reproduce

```powershell
# step 1 - run and cancel after like 3 seconds
Update-Module

# step 2 - because I want to check the module versions first
Get-Module

#step 3 - re-run
Update-Module
```

![image](https://user-images.githubusercontent.com/7172560/87889037-bb081780-c9fd-11ea-908f-a1ee275cc63c.png)

## Expected behavior

Update-Module to run successfully

## Actual behavior

see the screenshot above

## Workaround
Exit `pwsh`, re-enter `pwsh` and re-run `Update-Module`.

(Based on this workaround, it looks like `Update-Module` leaves some states persisted in PS runtime after getting interrupted)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please ask in https://github.com/PowerShell/PowerShellGet
