### ISSUE TITLE
Question about SMTP, SFTP, JWT

### ISSUE THREAD

**Issue by scotthardwick** [PowerShell/PowerShell#13210]
I believe I read an issue or posting about this at some point, but I can't find it, so I wanted to ask.  What is the PowerShell team's stance on adding in additional perhaps out of scope cmdlets?  I know that in some cases, various cmdlets are seen as the property of other Microsoft Teams and left to them to create.  I also believe I read somewhere that there was hope that some of these kind of external cmdlets would be primarily community driven.

I specifically find that I keep needing to use SMTP, SFTP, and JSON Web Tokens (JWT) and there is not an in-built method to do these items. (Well there was for Send-MailMessage but it seems to be deprecated at this time).

I have found myself falling back to using a DLL by a company called Chilkat for SMTP, SFTP, JWT, but my preference would be to use 100% Microsoft code if possible.

Before I write out lengthy feature requests, I wanted to see if this was even potentially something PowerShell team would take on.

**Comment by SeeminglyScience** [comment]
> Before I write out lengthy feature requests, I wanted to see if this was even potentially something PowerShell team would take on.

Unless there is a large undeniable demand, it's not likely.  Generally the route they prefer is for the community to implement a module and publish it to the gallery.  Once the module is published, if it sees widespread usage you can file a request to have the module bundled into PowerShell.  That said, I don't think there are any community modules that have met this bar yet (though I don't recall any that have asked either).

**Comment by iSazonov** [comment]
Since MSFT team is small and has limited resources they prefer to say about community modules.

You are a free to open new feature requests. It seems we already have ones for SMTP and SFTP.
