### ISSUE TITLE
Invoke-Command: calling a program via a UNC path in a remote session results in the wrong error being reported

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13226]
Note that the error only occurs if the executable path passed to `&` is a _UNC_ path.

## Steps to reproduce

Run on Windows, from an _elevated_ console (due to use of "loopback remoting"):

```powershell
{ $ErrorActionPreference='Stop'; Invoke-Command -ComputerName . { & '\\foo\bar' } } |
  Should -Throw -ErrorId CommandNotFoundException
```

## Expected behavior

The test should pass.

## Actual behavior

The test fails:

```none
Expected an exception, with FullyQualifiedErrorId 'CommandNotFoundException' to be thrown, but the FullyQualifiedErrorId was 'RuntimeException'
```

Instead of  the expected `&: The term '\\foo\bar' is not recognized as the name of a cmdlet, function, script file, or operable program.` message, the nondescript `RuntimeException: An error occurred while creating the pipeline.` is reported.

## Environment data

```none
PowerShell Core 7.1.0-preview.5
```

**Comment by daxian-dbw** [comment]
Loop in @PaulHigin for insights.

**Comment by PaulHigin** [comment]
This is by design.  Invoke-Command returns a RemoteException that wraps the original CommandNotFoundException as the serialized remote exception.  The ActionPreferenceStopException wraps it yet again.  You can see the original exception by:

```powershell
$err = Get-Error
$err.ErrorRecord.Exception.SerializedRemoteException
```

**Comment by mklement0** [comment]
@PaulHigin. Yes the original error is wrapped, but it normally - sensibly - still presents _like the original error_.

As stated, the nondescript wrapping only happens _if the executable path happens to be a UNC path_.

Contrast the behavior demonstrated in the OP (UNC path) with a local (non-existent) path:

```powershell
# OK:
PS>  Invoke-Command -ComputerName . { & 'c:\foo\bar' }
ObjectNotFound: The term 'c:\foo\bar' is not recognized as the name of a cmdlet, function, script file, 
or operable program. 
```

**Comment by PaulHigin** [comment]
More equivalently it would be:
```powershell
Invoke-Command -ComputerName . { & 'c:\foo\bar' } -ErrorAction Stop
ObjectNotFound: The term 'c:\foo\bar' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

$err = Get-Error
$err.ErrorRecord.FullyQualifiedErrorId
CommandNotFoundException
```
The problem is that in one case an ErrorRecord is returned and the other a RuntimeException, and seems to be how ErrorAction throws a terminating error.  This appears not be related to Invoke-Command since I can get the same results with this:

```powershell
& { $ErrorActionPreference = "Stop"; & 'c:\foo\bar' }
$err = Get-Error
$err.ErrorRecord.FullyQualifiedErrorId
CommandNotFoundException
```

**Comment by mklement0** [comment]
The only reason I brought `-ErrorAction Stop` into the mix was for the sake of the Pester test, so let's leave it out of the picture.

To recapitulate the original concern:

If a non-UNC path yields the expected error message on the caller's side:

```powershell
# OK
PS>  Invoke-Command -ComputerName . { & 'c:\foo\bar' }
ObjectNotFound: The term 'c:\foo\bar' is not recognized as the name of a cmdlet, function, script file, 
or operable program. 
```

then I see no reason why a UNC path should act differently, given that in local, direct invocation the two scenarios yield the _same_ error message:

```powershell
# !! Unexpectedly yields nondescript error.
PS>  Invoke-Command -ComputerName . { & '\\foo\bar' }
RuntimeException: An error occurred while creating the pipeline.
```

**Comment by PaulHigin** [comment]
Hmm, I don't see that behavior with my latest local build of 7.1.0-preview.5.  I get the same RemoteErrorRecord error object in each case you show above.  I get the RuntimeException object only if I use `-ErrorAction Stop` or set `$ErrorActionPreference = 'Stop'` as shown in by above examples.

**Comment by mklement0** [comment]
I just tried again in a loaded-without-profiles elevated preview-5 session with `$ErrorActionPreference` at its default (`Continue`), and I can reliably reproduce the symptom (on Windows 10 version 1909, but I presume that doesn't matter):

```powershell
PS> icm -cn . { & C:\no\such }; '---'; icm -cn . { & \\no\such }

ObjectNotFound: The term 'C:\no\such' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
---
RuntimeException: An error occurred while creating the pipeline.
```
