### ISSUE TITLE
Start-PSBuild: cryptic error message MSB3073

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#13222]
## Steps to reproduce

```powershell
Start-PSBuild
```

## Expected behavior

```none
git: The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Actual behavior

```none
`PowerShell\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 9009`
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The error comes from MSBuild and we can not improve it.

**Comment by yecril71pl** [comment]
We can refuse to invoke `MSBuild` if `git` is not found.

**Comment by iSazonov** [comment]
We can. But git is main prerequisite for the project. Perhaps we already have this in `Start-PSBootstrap`.

**Comment by yecril71pl** [comment]
The command `Start-PSBootstrap`, which should really be called `Install-Prerequisites`, is documented to call `Install-Dotnet`.  It is also documented that you can call `Install-Dotnet` separately.  `git` is not mentioned.

**Comment by vexx32** [comment]
`git` requirement doesn't necessarily imply it's accessing the internet, merely that metadata from the repository is used as part of the build so that a given build has a version attached to it (typically it's the git commit ID, IIRC).

We can document this, but IMO there's no good reason to remove git from the build.

**Comment by yecril71pl** [comment]
```powershell
Start-PSBootstrap
```
> Installing PowerShell build dependencies
> dotnet is already installed.  Skipping installation.

No `git` whatsoever.
