### ISSUE TITLE
After backgrounding a process with Ctrl+z, powershell is unable to accept input

### ISSUE THREAD

**Issue by iCodeSometime** [PowerShell/PowerShell#13224]
## Steps to reproduce

Open emacs, vim, or any other process that supports being backgrounded via Ctrl+z.
Press Ctrl+z

## Expected behavior

You are returned to PowerShell, the prompt is displayed, and new input is processed.

## Actual behavior

You are returned to PowerShell, the prompt is *not* displayed, and no new input is able to be processed.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iCodeSometime** [comment]
It looks like there are actually two possible behaviors here, depending on the terminal being used.
In the built in Terminal app, pressing Ctrl+z causes the screen to flash to PowerShell, and immediately resume the app.
In iTerm, the behavior is as described above.

**Comment by iSazonov** [comment]
Dup #7854.

**Comment by iCodeSometime** [comment]
Thanks. I'm not sure how I missed that one in my search
