### ISSUE TITLE
Consider using source generators for currently generated code

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13236]
Currently PowerShell uses a fair amount of generated code, for example:

- [The default formatters are all autogenerated](https://github.com/PowerShell/PowerShell/tree/master/src/System.Management.Automation/FormatAndOutput/DefaultFormatters) and there's discussion about refactoring them to improve startup performance already
- [Much of the core interpreter was generated in Python many years ago](https://github.com/PowerShell/PowerShell/tree/master/src/System.Management.Automation/engine/interpreter). There has been discussion in the past about updating our dependency on the LightCompiler

Instead, we could keep generated code out of the checked-in files by defining it as generated at build time using [.NET Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/).

**Comment by SeeminglyScience** [comment]
Related: #12760

**Comment by iSazonov** [comment]
The issue looks like Meta. Could you add more info where you want to use RSG (Roslyn Source Generators)?

I only know we use TypeGen utility at pre-build time.

**Comment by rjmholt** [comment]
Thinking about CDXML more, I think because that's a runtime code emission thing, that might be more a question of `Reflection.Emit`-type usages. AFAIK, Source Generators only occur at compile time, whereas CDXML files we must process when loaded at runtime

**Comment by SeeminglyScience** [comment]
> CDXML files we must process when loaded at runtime

The idea would be instead of generating a PowerShell module based on the cdxml, generate a binary module at compile time and ship that instead.  afaik nothing changes based on the environment it's loaded into, just based on the cdxml.

I know PowerShell doesn't specifically ship any cdxml (right?), but a PS team supported build time cmdletization API would be ideal.

**Comment by iSazonov** [comment]
If it is only for CDXML I think we can close as duplication of #12760.

**Comment by iSazonov** [comment]
> The default formatters are all autogenerated 

In #10898 @daxian-dbw used internal tool to convert type files in optimal format. We could do the same for format files without creating RSGs. Or vice versa, use generators in both cases (and share them for other projects). Although I'm not sure if it will зука win.

> Much of the core interpreter was generated in Python many years ago. There has been discussion in the past about updating our dependency on the LightCompiler.

Do you mean #2230? I believe the code was copy-pasted from old .Net with a little change.
