### ISSUE TITLE
Unreachable code in `typeDataXmlLoader_Table.cs`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13246]
This code is unreachable as `columnEntriesNodeFound` is initialized `false` but then never assigned `true`.

<https://github.com/PowerShell/PowerShell/blob/a6bd47f03155eeca52facd4ae5721bfaa41fe6ac/src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Table.cs#L377-L381>

_See also comment by @iSazonov in https://github.com/PowerShell/PowerShell/pull/13217#discussion_r457822870_

**Comment by iSazonov** [comment]
We should investigate if this is a bug and fix it or otherwise remove the unreachable code.

**Comment by iSazonov** [comment]
/cc @daxian-dbw @PaulHigin 

It seems we should remove the old code.

**Comment by PaulHigin** [comment]
This looks like a bug in the original implementation.  Need to confirm logic and fix if needed.

**Comment by ThomasNieto** [comment]
@PaulHigin were you able to find out if it can be removed?
