### ISSUE TITLE
Install-Module not works

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#13245]
Hello, I can't install any module using `Install-Module`
For example:
```powershell
Install-Module -Name Microsoft.Graph.Users.Calendar
```
![Windows Terminal](https://user-images.githubusercontent.com/23485114/88271128-f8b1bc80-cceb-11ea-9bc6-79ea473f9b76.png)
Please help me.

**Comment by xmha97** [comment]
I can install the modules only using below command:
```
Install-Module -Name PSReadLine -AllowPrerelease -Scope CurrentUser -Force -SkipPublisherCheck
```

**Comment by SeeminglyScience** [comment]
Judging by the error message, it looks like they published a module with a bad autheticode signature and the prerelease version is fixed.

**Comment by SydneyhSmith** [comment]
I can't reproduce this issue, is it still being seen?

**Comment by xmha97** [comment]
> 
> 
> I can't reproduce this issue, is it still being seen?

Thank you
Apparently, this problem has been resolved.
![image](https://user-images.githubusercontent.com/23485114/119379586-ea9a4700-bcd4-11eb-8db6-e2f14ce240cb.png)
