### ISSUE TITLE
Test-Json passes erroneously when data required in schema is missing 

### ISSUE THREAD

**Issue by smitheroons** [PowerShell/PowerShell#13255]
Expected behavior: Test-Json should evaluate the input data against the given schema. If the schema requires certain properties to be present, it should fail without those properties.

Actual behavior: Test-Json returns true even if required properties are missing.

In the following example, the schema requires a billing address if there is a credit card. The sample data contains a credit card, but no billing address. This passes, but it should fail.

Example:
```powershell
$demoschema = @'
{
  "type": "object",
 
  "properties": {
    "name": { "type": "string" },
    "credit_card": { "type": "number" },
    "billing_address": { "type": "string" }
  },
 
  "required": ["name"],
 
  "dependencies": {
    "credit_card": ["billing_address"]
  }
}
'@
 
$demoinput = "{`"name`": `"John Doe`",`"credit_card`": 5555555555555555}"
 
$demoinput | Test-Json -Schema $demoschema
```

**Comment by iSazonov** [comment]
@smitheroons Thanks for your report!

We use [NJsonSchema ](https://github.com/RicoSuter/NJsonSchema) API to validate JSON schema. You could ask in NJsonSchema repository about this behavior.

**Comment by daxian-dbw** [comment]
@iSazonov Can we label this one as `external`?

**Comment by cchildress** [comment]
@daxian-dbw / @iSazonov 
Do either of you have time to write up a test in .NET to try this in the NJsonSchema library directly?

If we don't see this issue in the library directly then it sounds like this is a cmdlet issue.
If we do see this issue in the library then we have a repro ready to file an upstream bug.

**Comment by iSazonov** [comment]
@cchildress All the cmdlet does it is call two NJsonSchema methods
https://github.com/PowerShell/PowerShell/blob/4464d1b4140cc53fa1cf65e95b569e8fd956bba8/src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs#L85-L106

**Comment by Glober777** [comment]
According to RicoSuter/NJsonSchema#1276, support for dependencies is not implemented in NJsonSchema yet

**Comment by Glober777** [comment]
By the way, it is worth mentioning that JsonSchema is now obsolete:
https://github.com/PowerShell/PowerShell/blob/4464d1b4140cc53fa1cf65e95b569e8fd956bba8/src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs#L51

Here are the link to the docs:
https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Schema_JsonSchema.htm

This has been moved to a separate package, which, by the way, does support dependencies:

```posh
Add-Type -Path "C:\Temp\JsonSchema\Bin\netstandard2.0\Newtonsoft.Json.Schema.dll"

$SchemaJSON = @"
{
    "additionalProperties": false,
    "properties": {
    "PropertyOne": {"type": "string"},
    "PropertyTwo": {"type": "string"},
    "PropertyThree": {"type": "string"}
    },
    "dependencies":{
        "PropertyThree": [
            "PropertyOne",
            "PropertyTwo"
        ]
    },
    "type": "object"
}
"@

$TestJSON = @"
{
    "PropertyThree": "qwerty"
}
"@

$ParsedJSON = [Newtonsoft.Json.Linq.JObject]::Parse($TestJSON)
$Schema = [Newtonsoft.Json.Schema.JSchema]::Parse($SchemaJSON)

$ValidationErrors = New-Object System.Collections.Generic.List[string]
$Result = [Newtonsoft.Json.Schema.SchemaExtensions]::IsValid($ParsedJSON, $Schema, [ref] $ValidationErrors)

$Result # is $False

$ValidationErrors # Dependencies for property 'PropertyThree' failed. Missing required keys: PropertyOne, PropertyTwo. Path '', line 1, position 1.

@iSazonov, is there a chance the Test-JSON cmdlet can be updated to use the new package?
```

**Comment by iSazonov** [comment]
@Glober777 We use NJsonSchema. 
Newtonsoft.Json.Schema is a paid package and we can not use it.

**Comment by gregsdennis** [comment]
The JSON Schema implementation has been recently updated to JsonSchema.Net and is available in the latest Powershell snapshot. Please retest this to see if it is still a problem.

This works as expected on https://json-everything.net/json-schema.

One thing to note, however, is that in the latest JSON Schema, `dependencies` has been split into `dependentRequired` (your usage) and `dependentSchemas`.  You can resolve this by either:

- adding `"$schema": "http://json-schema.org/draft-07/schema#"` to your schema to specify that you want draft 7 (where `dependencies` is still a thing)
- changing `dependencies` to `dependentRequired` and letting the validator interpret your schema as the latest version.

<blockquote><div><strong><a href="https://json-everything.net/json-schema">json-everything.net</a></strong></div><div>Extended JSON support in .Net built on top of the System.Text.Json namespace</div></blockquote>
