### ISSUE TITLE
Get-Help/Help doesn’t display contents of about_ file after first success

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/PowerShell#13252]
Get-Help/Help fails to display contents of About_ file after first success

## Steps to reproduce

Using Get-Help or Help, the problem occurs on the second attempt to display the contents of About_If. 

```powershell
Help if
Help about_if
Help if
Help About_If

```
## Expected behavior

```powershell
Help if #Displays list
Help about_if #display contents of About_If
Help if # Displays list
Help About_If #Displays contents of About_If
```

## Actual behavior

Using Get-Help or Help, the second attempt to display the contents of About_If fails by displaying a file list containing About_If, not the contents.

```powershell
Help if #Displays list
Help about_if #display contents of About_If
Help if # Displays list
Help About_If #Displays list containing only the file About_If, not the content.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.3
PSEdition                      Core
GitCommitId                    7.1.0-preview.3
OS                             Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/R…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by vexx32** [comment]
From memory, this can happen if you accidentally load the Windows PowerShell help in some fashion, but there may be other cases it occurs too.

IMO the default behaviour here should be improved; currently it's impossible to target either file even directly by exact name from Get-Help. Should probably do one of:

- Pick the most recent version (if version information is available) of the two and display that, possibly with a warning stating there is another topic by that name.
- Ask the user to select one via a prompt (though this is of dubious value as they have identical names and the user would probably pick at random), we'd need to show more information about it than we typically do, perhaps any available version information + the LastWriteTime of the actual xml file.
- Pick whichever one it finds first and display that.

Regardless of what the default is, we need a way to target the individual items from Get-Help itself; there currently isn't a way that I'm aware of?

**Comment by yecril71pl** [comment]
Another monster:
In a fresh instance:
```powershell
HELP about_Parallel | MEASURE | % COUNT | SHOULD -BE 75
HELP PARALLEL | MEASURE | % COUNT | SHOULD -BE 2
HELP about_Parallel | MEASURE | % COUNT | SHOULD -NOT -BE 1
```

The reason is that the 1st call of `GET-HELP` returns `[STRING[]]`, which is a **BUG**.
