### ISSUE TITLE
Set-Content expects different argument order when -NoNewline is specified

### ISSUE THREAD

**Issue by sasha2048** [PowerShell/PowerShell#13254]
PowerShell 7.0.3.

When I type `Set-Content aaa bbb`, the file `aaa` is created with the content `bbb`.
When I type `Set-Content -NoNewline aaa bbb`, the file `bbb` is created with the content `aaa`.

It's quite unexpected (especially that it seems that [the documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-7.1) doesn't mention that).

(Additionally, when I call `Set-Content -NoNewline aaa $specificLongText`, I get the blue screen of death on my Windows 10 — though I'm not sure whether it's related to PowerShell, it might be that some other software misbehaves when a file with weird name is tried to be created.)

## Steps to reproduce

```powershell
Set-Content -NoNewline aaa bbb
Get-Content aaa,bbb
```

## Expected behavior

```none
bbb
Get-Content: Cannot find path 'C:\Test\bbb' because it does not exist.
```

## Actual behavior

```none
Get-Content: Cannot find path 'C:\Test\aaa' because it does not exist.
aaa
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
This is a parameter binder bug, assign to myself to further investigation/triage.

**Comment by sasha2048** [comment]
(Not a blocker for me personally, but still happens in 7.3.9.)

**Comment by sasha2048** [comment]
(Not a blocker for me personally, but still happens in 7.4.2.)

**Comment by sasha2048** [comment]
Reopen?

**Comment by sasha2048** [comment]
Hello?
