### ISSUE TITLE
Feature Request: Secure Erase | Remove-Item

### ISSUE THREAD

**Issue by tobiaskolkmann** [PowerShell/PowerShell#13267]
## Summary of the new feature/enhancement

As an IT-Administrator I need to delete files according to GDPR. In a lot of cases it is required to make sure that a deleted file cannot be restored, so I need a way to securely erase files in Powershell. 
The cmdlet should be native in powershell, so you don't have to install any additional software

## Proposed technical implementation details (optional)

I think the implementation should be in the original Remove-Item cmdlet. If I add the argument "-Secure", I want the file to be overridden.
Override-Content: The most basic function would be to override all bytes the file uses on the harddisk with zeroes. In other cases it may be required to override the bytes with random values.
Repetitions: It may also be required to enter a number of repetions for the override if one override is not sufficient.
Example: Remove-Item C:\Users\Tobias\Secret -Recurse -Secure random -Rep 3
^--> This cmd should securely erase C:\Users\Tobias\Secret with all subfolders and files by overriding all sectors that contain content of the affected files on the volume three times with a random sequence and of course remove the entry in the MFT as before.

**Comment by vexx32** [comment]
I'm pretty sure this is doable even if there isn't a specific API for this kind of thing.

1. Check file size in bytes
2. Prepare byte array of zeroes or random data
3. Write file X times (possibly recreating byte array each time).

The only difficult part here is that this would probably have to be implemented in the filesystem provider itself if we wanted a core implementation, it's not something you could add to the general-purpose cmdlet directly.

**Comment by KalleOlaviNiemitalo** [comment]
[GNU coreutils documentation of `shred`](https://www.gnu.org/software/coreutils/manual/html_node/shred-invocation.html) warns that just overwriting the file several times does not erase all copies on some types of file systems or devices.

On Windows, [FSCTL_SET_ZERO_ON_DEALLOCATION](<https://docs.microsoft.com/windows/win32/api/winioctl/ni-winioctl-fsctl_set_zero_on_deallocation> "FSCTL_SET_ZERO_ON_DEALLOCATION - Win32 apps | Microsoft Docs") and [FSCTL_FILE_LEVEL_TRIM](<https://docs.microsoft.com/windows/win32/api/winioctl/ni-winioctl-fsctl_file_level_trim> "FSCTL_FILE_LEVEL_TRIM - Win32 apps | Microsoft Docs") look interesting but are not supported by ReFS.

**Comment by vexx32** [comment]
[This StackOverflow thread](https://stackoverflow.com/questions/4147775/securely-deleting-a-file-in-c-net) has some interesting points that seem worth considering.

Unless there's an API available from .NET it might not be worth implementing a tool into PowerShell itself, since it seems like we'd have to maintain syscalls for every supported OS (and figure out the hard way which ones don't support such an API).

**Comment by tobiaskolkmann** [comment]
> [GNU coreutils documentation of `shred`](https://www.gnu.org/software/coreutils/manual/html_node/shred-invocation.html) warns that just overwriting the file several times does not erase all copies on some types of file systems or devices.

That's true. But I suppose that desktop apps got the same problem... we may never find a way to fully delete the whole content of previous versions of a file (without previously encrypting it). And of course there may be VSS copies or backups containing the file as well.
But I think "overwriting" a file should suffice as a feasible way to permanently and "unrecoverably" delete files accourding to GDPR requirements.

"If" there is a feasible way, that is to say. 


A workaround might be: filling ALL empty space with zeroes/random content. But that might confuse the changed block transfer driver for our backup software. May also be very IO-intense, so I'd prefer a "knive" solution over the "sledgehammer".

**Comment by iSazonov** [comment]
It is very sensitive area. We could implement this if all OS-s implemented the function in a standard way. But they haven't. So my conclusion we can not implement this because we will confuse users.
Users should use tools which work reliable in their environment.
