### ISSUE TITLE
It seems that anaconda is not well supported

### ISSUE THREAD

**Issue by Jared-Shen** [PowerShell/PowerShell#13263]
···
PowerShell 7.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Program Files\PowerShell\7> conda activate pytorch
PS C:\Program Files\PowerShell\7> conda activate base
PS C:\Program Files\PowerShell\7> source activate pytorch
source: The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Program Files\PowerShell\7> source activate
source: The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Program Files\PowerShell\7>
···

it seems that when i want to run `conda activate` there are no hint that i succeeded in activating conda

**Comment by devon-ge** [comment]
It seems an issue of Anaconda. You need to load a `ps1` file first and activate the environment.
This is the target of `Anaconda Powershell Prompt (anaconda3).ink` of my windows 10 laptop

> `%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\Name\anaconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\Name\anaconda3' "`

I suggest using [Windows Terminal](https://github.com/microsoft/terminal). You can install it directly from Microsoft Store (recommended) or click the Github Repo link. Then edit the `settings.json` file and add Anaconda

>  {
                "guid": "{Your guid}",
                "commandline": "cmd.exe /K %USERPROFILE%/Anaconda3/Scripts/activate.bat %USERPROFILE%/Anaconda3",
                "icon": "%USERPROFILE%/Anaconda3/Menu/anaconda-navigator.ico",
                "name": "Anaconda3",
                "startingDirectory": "%USERPROFILE%"
     }

For more details, you may refer to [ThirdPartyToolProfiles.md](https://github.com/microsoft/terminal/blob/d2dcdef62019617c178818c96289ae022158f6fc/doc/user-docs/ThirdPartyToolProfiles.md)
