### ISSUE TITLE
Drawing progress bar changes color of original text if full RGB color is used

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#13278]
## Steps to reproduce

```powershell
Import-Module Pansies
$ProgressPreference = "Continue"

cls

for ($i = 0; $i -lt 30; $i++) {
	# Pansies version of Write-Host, with support for full RGB
	Write-Host ("=" * $Host.UI.RawUI.BufferSize.Width) -ForegroundColor "#900000" -BackgroundColor "#400000"
}

for ($i = 0; $i -lt 10; $i++) {
	Write-Progress -Activity "Test" -Status "Test" -PercentComplete ($i * 10)
	sleep 0.2
}
```

## Expected behavior
Text that uses full RGB colors keeps its original color after progress bar is drawn and hidden again.

## Actual behavior
After progress bar is hidden, text at its location has slightly different color (both foreground and background) than it originally had. Seems like it is rounded to the nearest color supported by the built-in Write-Host cmdlet. Resulting color is different in different terminals (pink in Windows Terminal, green in ConHost).

Before progress bar is drawn:
![image](https://user-images.githubusercontent.com/6414091/88464360-55fb6880-ceba-11ea-808c-d5d5e43a5e2d.png)

With active progress bar:
![image](https://user-images.githubusercontent.com/6414091/88464275-b342ea00-ceb9-11ea-9ece-959727e9e34a.png)

After progress bar is finished and hidden again (color at the position of progress bar should be the same as on the other lines, but it isn't):
![image](https://user-images.githubusercontent.com/6414091/88464277-b63dda80-ceb9-11ea-830e-be33cbb2459b.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
Progress bar on windows is drawn by screen buffer scraping. It's likely that the Win32 APIs user to get the buffer cells don't support full RGB color and thus convert the color to a console color that it can recognize.
