### ISSUE TITLE
Compare-Object

### ISSUE THREAD

**Issue by 7-904-001-67-28** [PowerShell/PowerShell#13280]
## Steps to reproduce
$Null -EQ $(Compare-Object @(1,2) @(2,1))
$Null -EQ (Compare-Object @(1,2) @(2,1))
```powershell

```

## Expected behavior
False
```none

```

## Actual behavior
True
```none

```

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```none

```

**Comment by SeeminglyScience** [comment]
@7-904-001-67-28 That's expected, but if you include `-SyncWindow 0` it will have the behavior you want.

**Comment by 7-904-001-67-28** [comment]
Thank you.
