### ISSUE TITLE
MSIX Assets missing for 7.0.3

### ISSUE THREAD

**Issue by pmsjt** [PowerShell/PowerShell#13284]
## Steps to reproduce

Visit https://aka.ms/PowerShell-Release?tag=v7.0.3

## Expected behavior

Under Assets, MSIX packages should be available.

## Actual behavior

No MSIX packages are available.

## Environment data

N/A

**Comment by yecril71pl** [comment]
MSIX are internal, unsupported and provided as a convenience only.

**Comment by pmsjt** [comment]
> MSIX are internal, unsupported and provided as a convenience only.

Well, they were released publicly for many releases without any indication of them being internal and for test only. You might want to consider the implications of that (customers taking a dependency).

Furthermore, there is still no installer being distributed for ARM64 - MSIX was the only one.

**Comment by yecril71pl** [comment]
> > MSIX are internal, unsupported and provided as a convenience only.
> 
> Well, they were released publicly for many releases without any indication of them being internal and for test only. You might want to consider the implications of that (customers taking a dependency).
> 

It was officially documented (probably still is).

> Furthermore, there is still no installer being distributed for ARM64 - MSIX was the only one.

Please change the issue summary accordingly, otherwise it is going to be closed as answered.

**Comment by adityapatwardhan** [comment]
@yecril71pl Since release of https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.5 we have paused releasing MSIX till the issues we are facing a resolved.

**Comment by pmsjt** [comment]
> @pmsjt Since release of https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.5 we have paused releasing MSIX till the issues we are facing a resolved.

Thanks for the pointer @adityapatwardhan . 

I hope this gets resolved soon, as the MSI work-around does not apply to ARM64.

**Comment by yecril71pl** [comment]
MSI is not a work-around, it is the recommended way of getting PowerShell.

**Comment by pmsjt** [comment]
> MSI is not a work-around, it is the recommended way of getting PowerShell.

Then please start building MSI for ARM64.

https://github.com/PowerShell/PowerShell/issues/12116

**Comment by juvtib** [comment]
For the record, I'm also looking for MSIX for 64-bit Intel. I don't intend on upgrading from 7.0.2 until the next MSIX package is available or it is clear that MSIX is abandoned.
