### ISSUE TITLE
iperf3 networking throughput regression in PowerShell Terminal on windows vs CMD Terminal on Windows

### ISSUE THREAD

**Issue by scyto** [PowerShell/PowerShell#13299]
## Steps to reproduce

- [Download latest iperf3 3.8.1 ](https://www.neowin.net/forum/topic/1234695-iperf-381-windows-build/)for windows (happens with older versions too.
- Install PowerShell 7.0.3 (this is only version i have tested so far)
- Open a Terminal PowerShell Terminal OR a PowerShell  terminal.
- run the following command (basically you need a server and client capably of true gig for this.

```
iperf3.exe -c speedtest1-sttlwawb-9.as20055.net -f m -d
```

## Expected behavior
you should get perf like this (this is from a native CMD terminal (not CMD called in psh))
```
[  5]   9.00-10.00  sec   104 MBytes   876 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec   967 MBytes   811 Mbits/sec                  sender
[  5]   0.00-10.00  sec   965 MBytes   810 Mbits/sec                  receiver
```

## Actual behavior
What you actually get is poor throughput measurement.
```
[  5]   9.00-10.00  sec  28.5 MBytes   239 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec   294 MBytes   247 Mbits/sec                  sender
[  5]   0.00-10.00  sec   292 MBytes   245 Mbits/sec                  receiver

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.20175
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me.  Got basically same throughput result in both cases.

**Comment by scyto** [comment]
I wonder if it is related to the build of windows?
Anything else I should check?

```
Caption        : Microsoft Windows 10 Pro Insider Preview
OSArchitecture : 64-bit
Version        : 10.0.20175
BuildNumber    : 20175
```

**Comment by scyto** [comment]
i just ran 5 times in each, seems issue is related to something else as when running multiple times it flips between ~250 and ~900.

So isn't PowerShell.
