### ISSUE TITLE
Installation - unable to install 7.0.3 if 7.1.0-preview5 is installed

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#13294]
## Steps to reproduce

Install 7.1.0-preview5 on a new windows install
Attempt to install 7.0.3

## Expected behavior

```none
7.0.3 installs no issue
```

## Actual behavior

```none
Install fails
```
![image](https://user-images.githubusercontent.com/6355225/88599494-cee9f400-d063-11ea-897b-67fc333b43f7.png)

## Environment data

``` powershell

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.20175
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Additional data

Uninstalling 7.1.0-preview5 allows 7.0.3 to install as expected, though ideally should allow for preview and then stable versions to be installed & no blocker for installing a newer stable when a preview version is installed

**Comment by iSazonov** [comment]
There was a bug in msi. Fixed in Preview5 so that we see a result only after Preview6. Workaround is to uninstall old version and install new.
