### ISSUE TITLE
The 'TraceRoute' test take 44 minutes to fail in macOS CI

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#13309]
The test `TraceRoute works` in the context `TraceRoute` in the file `Test-Connection.Tests.ps1` is causing timeout in [macOS CI builds](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=58605&view=logs&jobId=dd0d77e4-0911-5114-ec89-d447d00ba5e6&j=dd0d77e4-0911-5114-ec89-d447d00ba5e6&t=b551df83-c97f-5a24-b379-7e608cc7f18b).

![image](https://user-images.githubusercontent.com/127450/88866719-5ea4b500-d1c0-11ea-872e-3a5bd82401a6.png)

We will make the test pending for further investigation.

**Comment by iSazonov** [comment]
I had no idea that the Net team could add code that is so unreliable. Maybe the PowerShell team can internally escalate this so that this network-based API is finally fixed?

**Comment by rjmholt** [comment]
I tried that in the last case though, and they insisted the issue is with the native API they call. Looking into it, I think they're right.
