### ISSUE TITLE
ProviderInfo/CmdletInfo list view references non-existent property

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13311]
`ProviderInfo` and `CmdletInfo` both have list formats that reference a non-existant `AssemblyInfo` property. They should be removed if there are no plans to add that property.

This is the code where the properties are added to the view.

https://github.com/PowerShell/PowerShell/blob/ec20043a91ebb58e7e208630c5ef38f2af69e7e4/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L682

https://github.com/PowerShell/PowerShell/blob/ec20043a91ebb58e7e208630c5ef38f2af69e7e4/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L696

## Steps to reproduce

```powershell
Get-PSProvider | Format-List
Get-Command Get-Command | Format-List


It "ProviderInfo should have AssemblyInfo property" {
    Get-PSProvider | Get-Member -Name AssemblyInfo -Type Properties | Should -Not -BeNullOrEmpty
}

It "CmdletInfo should have AssemblyInfo property" {
    Get-Command Get-Command | Get-Member -Name AssemblyInfo -Type Properties | Should -Not -BeNullOrEmpty
}
```

## Expected behavior

No `AssemblyInfo` property shows up.

## Actual behavior

Shows a `AssemblyInfo` property.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3
```

**Comment by iSazonov** [comment]
I guess it is only for backward compatibility.

**Comment by ThomasNieto** [comment]
I opened an instance of PS 2.0 and it doesn't look like the property exists there either. It doesn't look like its for backwards compatibility. Might have been for a planned property that was never added.

I'll open a PR to remove it.
