### ISSUE TITLE
Powershell Core is typing @ before some special characters like ~ or ´  with brazilian keyboard layout

### ISSUE THREAD

**Issue by chiniara** [PowerShell/PowerShell#13327]
**NOTE: It didnt happen before, it worked as expected.**

## Steps to reproduce

Open powershell core
Try to type ~ or ´ with a brazilian keyboard ABNT2

## Expected behavior

Just type ~ or ´

## Actual behavior

![ezgif-6-ed29d6764e61](https://user-images.githubusercontent.com/6012227/89051903-4f8e4600-d32b-11ea-9040-b99ffe4a5d85.gif)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.…
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
@chiniara does the same occur after calling `Remove-Module PSReadline`?

**Comment by chiniara** [comment]
It doesnt!

But i find it weird because it was working fine before.

Maybe an update to PSReadline ?

**Comment by vexx32** [comment]
Yeah, potentially. Check `Get-Module -List PSReadLine` and see what versions you have installed. It's possible there's a newer version available as well; you can try `Update-Module PSReadLine`.

If there is an update, restart your powershell session and try it again to see if it's still an issue.

If not, or it's still happening anyway, please file an issue in the [PSReadLine repo](/PowerShell/PSReadLine) 🙂

**Comment by chiniara** [comment]
@vexx32 
Thank you very much, updating it fixed the problem!
I think this is solved then.

**Comment by rjmholt** [comment]
Will let the bot close it
