### ISSUE TITLE
Red text in PowerShell prompt is not legible

### ISSUE THREAD

**Issue by KarateClubGavere** [PowerShell/PowerShell#13320]
## Red text not legible

When I issued a command that throws an error (for example `dotnet tool update --global dotnet-ef --version 5.0.100-rc.1.20380.2` it throws an error. The error message is printed in red forecolor, without background color.

![image](https://user-images.githubusercontent.com/59490727/88977468-44510100-d2be-11ea-936a-dff5ff3de4a6.png)

(Perhaps the dotnet tools should set the console background color to white => move issue to https://github.com/dotnet)

## Proposed technical implementation details (optional)

Either:
- Set the background color to white
- Transform the foreground color to a more legible one

(0.21 × R) + (0.72 × G) + (0.07 × B) < 128 => Dark text, light background

**Comment by vexx32** [comment]
@KarateClubGavere Windows PowerShell isn't maintained in this repo and is locked at version 5.1.x.

Please submit a UserVoice ticket for Windows PowerShell issues.

The default background color for PowerShell 6+ is black, but you can change the Windows PowerShell background color from the Properties entry in the shortcut or console window menu.
