### ISSUE TITLE
Updatable help for PowerShellGet 3.0.0-x

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PowerShell#13332]
## Expected behavior

 Updatable help for PowerShellGet should now include the new functionality for:

- Find-PSResource
- Get-PSResourceRepository
- Get-PSResource
- Install-PSResource
- Register-PSResourceRepository
- Save-PSResource
- Set-PSResourceRepository
- Publish-PSResource
- Uninstall-PSResource
- Unregister-PSResourceRepository
- Update-PSResource

## Actual behavior

Currently includes updatable help for PowerShellGet 2.x.x functions. 

## Environment data

This applies to all versions of PowerShell.

**Comment by iSazonov** [comment]
@sdwheeler Can we close the issue?

**Comment by sdwheeler** [comment]
@iSazonov @SydneyhSmith @alerickson 
My PR to create the MD stub files was merged but the content is incomplete. That should probably be a new issue, but should that be here or in the PowerShellGet repository?

**Comment by iSazonov** [comment]
If we should fix nothing in the PowerShell repo it is better to track the work in Doc repo.
