### ISSUE TITLE
Get-Command fails with unexpected error when given a blank command-name argument

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13342]
Note: This is definitely a minor bug that won't arise too often in the real world.

Passing an all-whitespace `-Name` argument to `Get-Command` results in unexpected error message `Get-Command: Index was outside the bounds of the array.`

## Steps to reproduce

```powershell
{ Get-Command -ea Stop -Name ' '  } | Should -Throw -ErrorId CommandNotFoundException
```

## Expected behavior

The test should succeed; that is, the usual `CommandNotFoundException` should be reported.

## Actual behavior

The test fails, because the error mentioned above is reported instead.

```none
Expected an exception, with FullyQualifiedErrorId 'CommandNotFoundException' to be thrown, 
but the FullyQualifiedErrorId was 
'System.IndexOutOfRangeException,Microsoft.PowerShell.Commands.GetCommandCommand'
```

## Environment data

```none
PowerShell Core 7.1.0-preview.5
```

**Comment by jackerr3** [comment]
I'll try tackling this one.

**Comment by ThomasNieto** [comment]
This issue could benefit from the proposed enhancement in #10010 to have `[ValidateNotNullOrEmpty()]` have a settable property to check for whitespace in addition to null and empty.

**Comment by jackerr3** [comment]
I'd like to point out that when reproducing this error after doing Start-DevPowershell it gives a different error. This is because src\System.Management.Automation\engine\CommandSearcher.cs has the following `Dbg.Assert(
                !string.IsNullOrEmpty(name),
                "Caller should verify name");`. 

My question is, does this assert belong here? Issue #10165 was closed because it was decided that variable names and alias names with whitespace should be possible. So should Get-Command return the whitespace alias if it exists?

**Comment by vexx32** [comment]
Given the conclusion to that issue, I'd agree that that assertion shouldn't be there, yeah. 👍

**Comment by jackerr3** [comment]
Well I've done some digging and it looks like in CommandSearcher.cs at line 1540 _commandName is trimmed `_commandName = _commandName.TrimEnd(Utils.Separators.PathSearchTrimEnd);`. This is what ultimately causes the index out of range exception to be thrown at line 1102 `                if (_commandName[0] == '.' || _commandName[0] == '~' || _commandName[0] == '\\')
`. If I comment out the `_commandName.TrimEnd(Utils.Separators.PathSearchTrimEnd);` The behavior of `Get-Command ' '` is as expected and everything else _seems_ to work fine. 

My next question is (and I realize this is asking a lot), does anyone have any ideas why the `_commandName = _commandName.TrimEnd(Utils.Separators.PathSearchTrimEnd);` is there?
