### ISSUE TITLE
PSSessions with Containers throw NullReferenceException

### ISSUE THREAD

**Issue by hemisphera** [PowerShell/PowerShell#13347]
Cmdlets that deal with PSSessions created on ContainerId throw a NullReferenceException when creating the session. This is true for `New-PSSession`, `Enter-PSSession` and `Invoke-Command`, among maybe others.

The stack trace is this:
````
Object reference not set to an instance of an object.
   at System.Management.Automation.Runspaces.ContainerProcess.GetContainerProperties()
   at Microsoft.PowerShell.Commands.PSExecutionCmdlet.CreateHelpersForSpecifiedContainerSession()
````

For me the line that fails is inside `GetContainerPropertiesInternal` of the class `System.Management.Automation.Runspaces.ContainerProcess` in `System.Management.Automation.dll`.

`ContainerObRoot = (string) computeSystemPropertiesType.GetProperty("ObRoot").GetValue(obj);`

## Steps to reproduce

To reproduce this a running container is required.

```powershell
New-PSSession -ContainerId <TheContainerId> -RunAsAdministrator
```

## Expected behavior

An instance of `PSSession` should be created.

## Actual behavior

A NullReferenceException is thrown.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
Yes, there have been some cases where container images do not contain the correct Hyper-V binaries needed for a PowerShellDirect connection.  The Hyper-V team who owns these binaries are aware of the issue.  But this problem is outside of PowerShell.

**Comment by hemisphera** [comment]
I am not sure on this @PaulHigin. How is this outside of PowerShell? The same container can be accessed without problems through a `New-PSSession` from PowerShell 5.1. It does look like a PS6/7+ problem to me, no?

**Comment by PaulHigin** [comment]
The original issue description did not mention this.  If WindowsPowerShell can connect to the same container using the same command:

```powershell
New-PSSession -ContainerId <TheContainerId> -RunAsAdministrator
```

Then that would indicate a client error.  But I am not aware of any changes to this code in either WindowsPowerShell or PowerShell core.

**Comment by PaulHigin** [comment]
The only change I see in this code was made two years ago, to fix an incompatibility.

PR #7883

/cc @SteveL-MSFT

**Comment by hemisphera** [comment]
> If WindowsPowerShell can connect to the same container

Sorry, you're right: I did not mention it in the original description. But PS 5.1 is definitely able to access the same identical container. PS 7.0.0 and PS 7.0.3 can not.

**Comment by PaulHigin** [comment]
@SteveL-MSFT  Can you look at this and see if it is related to the fix you made for #7883?

**Comment by SteveL-MSFT** [comment]
Following-up with Hyper-V team to see if they have changed their schema again as the code is trying to get Hyper-V properties, but `ObRoot` property is returning null.

**Comment by SteveL-MSFT** [comment]
The official answer from Hyper-V team is that they also changed this to a field from a property.
