### ISSUE TITLE
PowerShell 7.0.3 prints '@' character on Fn+Left Arrow or Fn+Right Arrow

### ISSUE THREAD

**Issue by Andrll** [PowerShell/PowerShell#13367]
## Steps to reproduce

Run the PowerShell 7.0.3 session. Click Fn+Left Arrow or Fn+Right Arrow, the '@' character will be printed.

## Expected behavior

Fn+Left Arrow and Fn+Right Arrow expect to move the cursor to the beginning or to the end of the line and not print extra characters.

## Actual behavior

Fn+Left Arrow and Fn+Right Arrow prints an extra character ('@').

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Comments

It looks like a regression. The issue has not been observed in at least one of the previous versions.

**Comment by iSazonov** [comment]
It looks like PSReadline issue. Please unload the module in your session and check again. Also please install latest PSReadline version and check too.
