### ISSUE TITLE
Show files icon

### ISSUE THREAD

**Issue by khoshroomahdi** [PowerShell/PowerShell#13363]
## Summary of the new feature/enhancement
Please add show files icon in powershell

**Comment by iSazonov** [comment]
@khoshroomahdi Please add more info. It is not clear that icon you mean. We need to understand your scenario to weight your request.

**Comment by khoshroomahdi** [comment]
Like what terminal-icon module do.

**Comment by iSazonov** [comment]
https://github.com/devblackops/Terminal-Icons
Looks interesting but if terminal-icon module works why do we need to duplicate the module here?

/cc @SteveL-MSFT @joeyaiello for conclusion.

**Comment by khoshroomahdi** [comment]
It just work with nerd fonts and didn't update from last year,by the way i think it's useful to be part of powershell.

**Comment by SeeminglyScience** [comment]
While it is a very cool module, the fact that it needs a specific type of custom font installed and selected is a challenge.  It would be difficult to integrate in PowerShell in a way that makes sense.

**Comment by soredake** [comment]
Still wanted.

**Comment by theJasonHelmick** [comment]
Thank you @khoshroomahdi -- The working group has reviewed this issue and does not believe this should be included in PowerShell. It is better to have this feature provided by a module in the PowerShell Gallery as earlier mentioned.  Thank you for the suggestion.
