### ISSUE TITLE
Dismount removable drive

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#13370]
## Summary of the new feature/enhancement

I would like to have a function to dismount a removable drive to be available in PowerShell.
## Proposed technical implementation details (optional)

```powershell
function Dismount-RemovableDrive ([String] $drive) {
  (New-Object -ComObject:Shell.Application). NameSpace($drive). Self. InvokeVerb('Eject')
}
```

This could theoretically be handled by `Invoke-CimMethod` but that path is more complicated and it requires privilege elevation.

**Comment by iSazonov** [comment]
We need a portable API to implement such cmdlet. .Net has not the API. I think it is impossible to implement the API in near future but you could ask in .Net Runtime repository.
