### ISSUE TITLE
"Aministrator rights are required to install or update." when running PowerShell 7 with Admin rights

### ISSUE THREAD

**Issue by ageevits** [PowerShell/PowerShell#13371]
I get the following error when running PowerShell 7.0.3 with admin rights (Run as Administrator). 

PS C:\Users\agurvits> Install-Module Az -force
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Administrator rights are required to install or update. Log on to the computer with an account that has Administrator rights, and then try again, or install by adding "-Scope
     | CurrentUser" to your command. You can also try running the Windows PowerShell session with elevated rights (Run as Administrator).

I am attaching full output after running the command with -Verbose and -Debug options set.

[output.txt](https://github.com/PowerShell/PowerShell/files/5035808/output.txt)
[output.zip](https://github.com/PowerShell/PowerShell/files/5035812/output.zip)

**Comment by iSazonov** [comment]
@ageevits I think it is not PowerShell issue you get an answer more fast if ask in Az module repository.

/cc @alerickson

**Comment by ageevits** [comment]
OK. Thanks. I’ll open an issue in that repo.

Alex



Alex Gurvits
APX Inc., Chief Information Officer, IT Security Officer
agurvits@apx.com<mailto:agurvits@apx.com>; +1-917-855-6576 (m)

[Description: Description: Description: Description: Logo 1v]
