### ISSUE TITLE
M$ is using Pester to sell it products, therefore M$$ should be in the Sponsor-List of the Maintainers

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#13386]
## Summary of the new feature/enhancement

As we can see here:
[https://github.com/PowerShell/PowerShell/tree/master/test](https://github.com/PowerShell/PowerShell/tree/master/test)
M$ is using Pester. 

Without PowerShell, many Microsoft products would be much less useful.
If PowerShell would have even more bugs, the many Microsoft products would definitely become a nightmare.

Therefore, Microsoft is considered heavily dependent on Pester.

Why can't we find Microsoft in the support list of maintainers who spend their spare time to add the component that is so elementarily important to Microsofts product PowerShell?

I'm not a maintainer, but I am very disappointed about Microsoft's greed and the lack of appreciation.

**Comment by vexx32** [comment]
Not a bad point.

I can't speak to how these things work, but IMO it's worth pursuing an avenue of a set amount of contribution monthly or yearly to Pester (and/or other open source tools that are heavily utilised) per team that uses them.

**Comment by SeeminglyScience** [comment]
> I can't speak to how these things work, but IMO it's worth pursuing an avenue of a set amount of contribution monthly or yearly to Pester (and/or other open source tools that are heavily utilised) per team that uses them.

Yeah, while the tone of the OP is not super helpful, they're not wrong.

@SteveL-MSFT it would be worth discussing a financial contribution for Pester on [OpenCollective](https://opencollective.com/pester) from MS. It's by far the single most important and impactful PowerShell community project.

**Comment by joeyaiello** [comment]
There are many ways that companies contribute to open-source, and this is outside the scope of this repository. 

Please make sure to adhere to our [Code of Conduct](https://github.com/PowerShell/PowerShell#code-of-conduct) as well
