### ISSUE TITLE
IModuleAssemblyInitializer does not run

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13390]
I have a C# module with a module init that uses a static class to maintain a cache. The cache does not get generated when importing the module and can be confirmed by trying to get the items from the cache. I can create the `ModuleInitializer` class manually and call `OnImport()` without issue and verify the cache is generated.

## Steps to reproduce

Create C# module with module initializer class.

```csharp
public sealed class ModuleInitializer : IModuleAssemblyInitializer
    {
        public void OnImport()
        {
            // do stuff
        }
    }
```

Import module using tracing.

```powershell
Trace-Command -Name Modules,PSSnapInLoadUnload -Expression { Import-Module Test } -PSHost
```

You're able to instantiate a `ModuleInitializer` class and run `OnImport` method without issue.

## Expected behavior

Module init OnImport method is ran.

## Actual behavior

Module init OnImport method isn't ran. Tracing does not output message saying `Executing IModuleAssemblyInitializer.Import for {0}`

```none
DEBUG: 2020-08-09 17:22:14.3711 PSSnapInLoadUnload Information: 0 : Analyzing assembly C:\Temp\module.dll for cmdlet and providers
DEBUG: 2020-08-09 17:22:14.3754 PSSnapInLoadUnload Information: 0 : Get-Thing from type Test.GetThingCommand is added as a cmdlet.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
@ThomasNieto can you provide a more specific repo?  I have a module with an initializer that is still working on 7.1.0-preview.5

**Comment by ThomasNieto** [comment]
@SeeminglyScience did some more testing and was able to rule out that its a PowerShell issue.

**Comment by jcasale** [comment]
@ThomasNieto Do you recall what impacted the execution of that interface in your use case?
