### ISSUE TITLE
Quoted [DateTime] objs ignoring culture

### ISSUE THREAD

**Issue by wembleyford** [PowerShell/PowerShell#13397]
## Steps to reproduce

```powershell
(get-culture).displayname
English (United Kingdom)

get-date          
Tuesday, 11 August 2020 08:00:02

get-date -format g 
11/08/2020 07:59
```

So far so good
```
$dt = get-date
"$dt"
11/08/2020 07:59

"$(get-date)"
08/11/2020 07:59:50
```
## Expected behavior
I would have expected that 

```none
"$(get-date)"
```
Would produce a UK formatted date obj.  Especially as 

```
"$(get-culture)" 
en-GB

"$(get-date -format g)" 
11/08/2020 07:59
```

## Actual behavior

The output seems to be producing a US output, despite the culture apparently being en-GB. Clearly given the the difference in output between 
```
$dt =get-date
"$($dt)"
08/11/2020 08:16:21
"$($dt.ToString())"
11/08/2020 08:16:21
```

There is reason why there is a difference between the formatting? I'd expect the out put of "$dt" to be the ToString() output of $dt.  Instead I'm seeing 
```
"$(get-culture; get-date)"
en-GB 08/11/2020 08:30:49
"$(get-culture; (get-date).ToString())"
en-GB 11/08/2020 08:31:08
```
Clearly there is some subtlety I'm musing - or a bug.  Probably the former, I know - I'd appreciate some pointers.
## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Linux 4.9.34-gentoo #1 SMP Sun Aug 13 00:47:40 BST 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
By design, PowerShell uses the _invariant culture_ for string interpolation and in casts.

By contrast, `.ToString()` - for types that implement culture-sensitive representations - uses the _current_ culture.

See [this SO answer](https://stackoverflow.com/a/37603732/45375) for background information.
