### ISSUE TITLE
Support for TLS 1.3

### ISSUE THREAD

**Issue by trudolf-msft** [PowerShell/PowerShell#13398]
## Steps to reproduce
[enum]::GetValues('Net.SecurityProtocolType')
Invoke-WebRequest -SslProtocol tls13 -Uri https://www.google.com

![image](https://user-images.githubusercontent.com/43539433/89870728-97785d00-dbb6-11ea-93ee-a80ba00b69ee.png)

## Expected behavior
Connect with TLS 1.3 without error

## Actual behavior
Error message:
Invoke-WebRequest: Cannot bind parameter 'SslProtocol'. Cannot convert value "tls13" to type "Microsoft.PowerShell.Commands.WebSslProtocol". Error: "Unable to match the identifier name tls13 to a valid enumerator name. Specify one of the following enumerator names and try again:
Default, Tls, Tls11, Tls12"

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by anmenaga** [comment]
[Looks like code was not updated for Tls13](https://github.com/PowerShell/PowerShell/blob/dd85bd11784c8d1dd11ed12b264d2a6e13dfb665/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L61)

**Comment by ThomasNieto** [comment]
There is a comment saying that TLS 1.3 is not supported by `HTTPClientHandler`. Do we know if that has changed?

```csharp
// Also SslProtocols.Default is not the "default" for HttpClientHandler as SslProtocols.Ssl3 is not supported.
```

**Comment by vexx32** [comment]
IIRC SSL3 is not the same thing as TLS1.3; SSL3 is a much older protocol, if my memory of last time I stumbled around something like this is accurate.

**Comment by ThomasNieto** [comment]
@vex you're right, not sure why I read TLS 1.3 when it was SLL13.

**Comment by iSazonov** [comment]
Fix ready.
