### ISSUE TITLE
Get-Item / Get-ChildItem quietly ignore nonexistent parent paths in UNC paths with wildcards

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13417]
Note: This bug goes back to a least v3.

## Steps to reproduce

On Windows:

```powershell
# OK: Nonexistent local path results in error.
{ Get-Item -ea Stop c:\no\such\* } | Should -Throw

# BROKEN: Nonexistent UNC path quietly returns nothing.
{ Get-Item -ea Stop \\no\such\* } | Should -Throw
```

## Expected behavior

Both tests should pass.

## Actual behavior

The second test fails, because `Get-Item` unexpectedly quietly returned nothing instead of reporting an error.

```none
Expected an exception, to be thrown, but no exception was thrown.
```

## Environment data

```none
PowerShell Core 7.1.0-preview.5
```

**Comment by iSazonov** [comment]
It seems we have an related issue.
