### ISSUE TITLE
The output of `$Error[1] | Out-String` contains ANSI escape sequences

### ISSUE THREAD

**Issue by Shayan-To** [PowerShell/PowerShell#13416]
## Steps to reproduce

```powershell
Try
{
    Throw 'Some error.'
}
Catch
{
    $E = $_
}
$E | Out-String
$E | Out-File Test.txt
```

## Expected behavior

```none
Exception: Some error.
```

## Actual behavior

```none
[91mException: [91mSome error.[0m
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
[91m comes from #11891 

It seems @Shayan-To's terminal does not support this.

**Comment by Shayan-To** [comment]
I would never expect the output of `Out-String` to contain ANSI escape sequences. Also, the output file from `Out-File` also contains these characters.

**Comment by joeyaiello** [comment]
@SteveL-MSFT to dupe this one against some other work

**Comment by SteveL-MSFT** [comment]
This is related to the ANSI rendering work I'm already working on which allows for the session whether to remove ANSI escape sequences.  However, it may make sense for `Out-String` and `Out-File` to have `-IncludeANSI` or `-ExcludeANSI` so keeping this issue separate to discuss that.

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/PowerShell/PowerShell/pull/13758

Use `$PSStyle.OutputRendering = 'host'`
