### ISSUE TITLE
Get-Help -Parameter doesn't recognize parameter aliases

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13418]
Getting focused help for a given parameter with `Get-Help -Parameter <name>` is helpful, but you're currently forced to use the actual, full parameter name - using an _alias_ doesn't work.

## Steps to reproduce

```powershell
# OK: Actual parameter name is recognized.
{ Get-Help -ea Stop Get-ChildItem -Parameter LiteralPath } | Should -Not -Throw

# BROKEN: Alias name is not recognized.
{ Get-Help -ea Stop Get-ChildItem -Parameter lp } | Should -Not -Throw
```

## Expected behavior

Both tests should succeed.

## Actual behavior

The 2nd test fails, because the parameter is not recognized via its alias.

```none
Expected no exception to be thrown, but an exception "No parameter matches criteria lp."
```

As an aside: "criteria" should be "criterion" (singular).

## Environment data

```none
PowerShell Core 7.1.0-preview.5
```

**Comment by mattcargile** [comment]
It would be nice to see this fixed because of the below issue.

https://github.com/PowerShell/PSReadLine/issues/3560
