### ISSUE TITLE
Add an -AsAutoNumber switch to Measure-Object for automatic numeric type-widening

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13423]
Follow-up from #12103, closely related to #12141

# Summary of the new feature/enhancement

Currently, numeric input to `Measure-Object` returns a `MeasureGenericInfo` instance whose properties are all (nullably) `[double]`-typed (except `Count`, which is `[int]`-typed).

This can result in loss of accuracy with large integers; e.g.:

```powershell
PS> [long] (9223372036854770000 | Measure-Object -Sum).Sum
9223372036854769664 # !! Number was altered due to lossy conversion to [double].
```

The decision in #12103 was not to alter the current behavior, but we can improve it on an _opt-in_ basis:

Let's introduce an `-AsAutoNumber` switch that modifies the behavior of `Measure-Object` as follows:

* All output properties should retain the input type, if possible (if the inputs aren't of uniform type, base the result on the widest among the input types):

  * `Minimum`, `Maximum` actually should do that _by default_ too - see #13422
  * For `Average` and `StandardDeviation`, `[double]` is an appropriate default in most cases, but `[decimal]` input should result in `[decimal]`  output as well.

* If the input type becomes too small for `Sum` (and possibly for `Count`, if #7244 gets implemented), the type should be _automatically widened_, using the rules described in the related #12141 proposal.

In essence, `-AsAutoNumber` necessitates a new, all-`object`-properties output type.

**Comment by jdhitsolutions** [comment]
If you are going down this path, give me an option to format the results as KB, MB, GB, or TB. Ideally to a user-specified number of decimal points. That saves me from cumbersome expressions like this:

```powershell
dir c:\work -file | measure -Property length -sum | Select Count,@{N="SumMB";E={[math]::round($_.sum/1mb,2)}}
```

That are a pain to type and even harder for PowerShell beginners to understand.

**Comment by kvprasoon** [comment]
IMO, it should be 1024.

**Comment by vexx32** [comment]
1024 would be consistent with the builtin `kb`, `mb` etc suffixes, so would yield predictable results there IMO

**Comment by mklement0** [comment]
* To address the readability of large numbers in general, please see #13590. 

* To address the issue raised by @jdhitsolutions specifically, please see #13601.
