### ISSUE TITLE
Import Get-Process tests

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1343]
The current [Get-Process tests](https://github.com/PowerShell/PowerShell/blob/ca1780255ffeb96b9f82ed3068476d85836922a5/test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1#L2) are no good and need to be replaced by importing existing BVT/DRTs.

/cc @JamesWTruher @TravisEz13

**Comment by raghav710** [comment]
@andschwa has anyone taken this up? This looks like an interesting task for a beginner like me :)

**Comment by TravisEz13** [comment]
@adityapatwardhan  is managing tests.  @adityapatwardhan Can you answer @raghav710 's question?

**Comment by adityapatwardhan** [comment]
@raghav710 We have some tests at: https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1

If you could contribute with more tests, it will be awesome! 

This might be helpful to figure out what tests need to be added: https://codecov.io/gh/powershell/powershell/src/master/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L447

**Comment by TravisEz13** [comment]
Tests needed:

1. get-process -IncludeUserName (requires elevation on windows)
    1. error case, run this as non-admin on windows and verify error
1.  get-process -Module -FileVersionInfo 
1.  get-process -Module
1.  get-process -FileVersionInfo

**Comment by kalgiz** [comment]
Fixed in #6272

**Comment by TravisEz13** [comment]
@adityapatwardhan  Are you okay with this being closed?  If not, can you open a new issue?

**Comment by adityapatwardhan** [comment]
Yes, this can be closed.
