### ISSUE TITLE
make NewProcessConnectionInfo Public 

### ISSUE THREAD

**Issue by Safirion** [PowerShell/PowerShell#13435]
The class NewProcessConnectionInfo (https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L1496 ) must be public (with public creator). Actualy we cannot create out-of-process runspacepool.

-------------------------------------------------------------------------------------------------------------

Workaround : 

```CSHARP
         private static RunspaceConnectionInfo CreateNewProcessConnectionInfo(PSCredential credential, PowerShellProcessInstance process)
        { 
            Assembly automation = Assembly.Load(new AssemblyName("System.Management.Automation"));
            Type t = automation.GetType("System.Management.Automation.Runspaces.NewProcessConnectionInfo");
            RunspaceConnectionInfo obj = (RunspaceConnectionInfo)Activator.CreateInstance(t, BindingFlags.Instance | BindingFlags.NonPublic, null, new object[] { credential }, null);
            foreach (PropertyInfo propertyInfo in obj.GetType().GetProperties(BindingFlags.Instance | BindingFlags.NonPublic))
            {
                if (propertyInfo.Name == "Process")
                    propertyInfo.SetValue(obj, process);
            }

            return obj;
        }
```

And 

```CSHARP
RunspaceFactory.CreateRunspacePool(1, 8, CreateNewProcessConnectionInfo(null, new PowerShellProcessInstance(new Version(5, 1), null, null, false)));
```

**Comment by PaulHigin** [comment]
```
RunspaceFactory.CreateOutOfProcessRunspace()
```

**Comment by SeeminglyScience** [comment]
@PaulHigin They're asking about runspace pools.

**Comment by PaulHigin** [comment]
Thanks for the clarification, I missed that.  I don't see any reason not to make the type public, it probably wasn't done so originally because there was no compelling reason to.  Reflection, per above is a reasonable workaround.

**Comment by SeeminglyScience** [comment]
Seems like `PowerShellProcessInstance` it was excluded from PowerShell Standard (PowerShell/PowerShellStandard#75).

Should it be included in PowerShell Standard?  Honestly I've never figured out the use case for this API.  Was it a workflow thing?

**Comment by PaulHigin** [comment]
/cc @JamesWTruher for PowerShell Standard

Yes, I believe this was exposed for workflows.  Nowadays it is just used for background jobs.

**Comment by JamesWTruher** [comment]
WG-Remoting should decide whether NewProcessConnectionInfo should be public to support this scenario. It's not a PSStandard issue as the NewProcessConnectionInfo is internal in 5 (so it can't be in standard)

**Comment by TravisEz13** [comment]
remoting working group: we agree that it should be public, after appropriate code review and testing.
