### ISSUE TITLE
CredSSP tests fail on Server 2019

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13448]
Test fails at:

https://github.com/PowerShell/PowerShell/blob/d9c2e0e712361bd91f661f6bf6a010c01d2eac0a/test/powershell/Modules/Microsoft.WSMan.Management/CredSSP.Tests.ps1#L46-L63

with error:

```
Expected regular expression 'The machine is configured to allow delegating fresh credentials to the following target(s):wsman/*' to match 'The machine is not configured to allow delegating fresh credentials.', but it did not match.
```

This seems to be an issue in the testing platform.

**Comment by iSazonov** [comment]
Does Enable-WSManCredSSP really work on Windows Server 2019?

**Comment by adityapatwardhan** [comment]
This fails in our release runs all the time. No regression. Not a blocker.
