### ISSUE TITLE
Get-ExperimentalFeatures tests fail on Raspberry Pi because powershell.config.json does not exist

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13444]
Failure occurs in:

https://github.com/PowerShell/PowerShell/blob/d9c2e0e712361bd91f661f6bf6a010c01d2eac0a/test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1#L174

**Comment by iSazonov** [comment]
Have we an issue to exclude powershell.config.json and compile defaults? It was a suggestion from @daxian-dbw

**Comment by daxian-dbw** [comment]
That proposal is only for stable release, not preview releases. Experimental features in preview release are all turned on and they should be turned on the same way as in stable release.

**Comment by adityapatwardhan** [comment]
Not a blocker.
