### ISSUE TITLE
NativeCommandProcessor tests: xdg_open fails to open .txt on Raspberry Pi

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13443]
See:

https://github.com/PowerShell/PowerShell/blob/d9c2e0e712361bd91f661f6bf6a010c01d2eac0a/test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1#L224-L226

**Comment by rjmholt** [comment]
Also failing due to this:

https://github.com/PowerShell/PowerShell/blob/d9c2e0e712361bd91f661f6bf6a010c01d2eac0a/test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1#L237

**Comment by rjmholt** [comment]
Required solution: skip these tests on Raspberry Pi

**Comment by adityapatwardhan** [comment]
Not a blocker.
