### ISSUE TITLE
More human-friendly dependency management?

### ISSUE THREAD

**Issue by IISResetMe** [PowerShell/PowerShell#13457]
## Summary of the new feature/enhancement

Today I spent ~2 hours just to get Visual Studio to load `PowerShell.sln` - updating both the release and preview versions, re-installing latest published release of the .NET 5 Preview SDK etc. etc.

The culprit seems to be [this commit](https://github.com/PowerShell/PowerShell/commit/9c396aa0eae7976c62cfb905cacfdf5cd7390378), pulling in a version of the SDK. Problem is that `dotnet-install.ps1` finds the corresponding artifact online (`https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20366.15/dotnet-sdk-5.0.100-preview.7.20366.15-win-x64.zip`), but it's NOT actually the latest version published on the .NET Core website (`5.0.100-preview.7.20366.6` as of publishing this issue)?!

So now, whenever I set up a new branch from master I have to either
 - Update `global.json` manually every time I checkout a branch I want to work with in VS
 - Run `Start-PSBootStrap` and then manually copy the appropriately versioned SDK folder to `C:\Program Files\dotnet\`

This is perhaps the 4th or 5th time I've run into this or similar issues when picking up the project after not having worked on it for a while, and FWIW it's the No. 1 reason I haven't really contributed anything in the last ~8 months `¯\_(ツ)_/¯`

## Proposed technical implementation details (optional)

Either:
 - Add an option to `Start-PSBootStrap` that allows me to install `dotnet` system-wide instead of in my user profile, or
 - Avoid pulling in new SDK versions before an installer is actually available

**Comment by iSazonov** [comment]
I'm afraid it's inevitable.
MSFT team plans to release PowerShell 7.1 immediately after the release of .Net 5.0. To do this, we need to install the latest available .Net previews as soon as possible. Even with this approach, we receive fixes in .Net with a delay of about 2 months!

We can not install such previews globally because it can break Visual Studio (at least move it in unsupported state).

**Comment by IISResetMe** [comment]
> We can not install such previews globally because it can break Visual Studio (at least move it in unsupported state).

I totally get that, but I'm talking about an _opt-in_ change, not a change to the default behavior. 

Like, `Start-PSBootstrap -Global -Force -YesIKnowWhatIAmDoing`?

**Comment by iSazonov** [comment]
`Install-Dotnet` function already has `InstallDir` parameter.

**Comment by iSazonov** [comment]
I think we could write a comment with description how to install .Net globally.
