### ISSUE TITLE
Hyper V module not available

### ISSUE THREAD

**Issue by rajurh** [PowerShell/PowerShell#13467]
I am trying to run minikube using hyper-v and I am getting below error related to PowerShell module and I verified the same on another machine with a similar OS it works.

Minikue Error
![image](https://user-images.githubusercontent.com/15551296/90467925-75a84880-e169-11ea-95a7-afd710894d09.png)

Powershell output
![image](https://user-images.githubusercontent.com/15551296/90467983-98d2f800-e169-11ea-8e29-7f1b0c10fca8.png)

## Environment data
![image](https://user-images.githubusercontent.com/15551296/90468007-b0aa7c00-e169-11ea-9b86-1fe30ad80791.png)

System: Windows 10 with WSL2 enabled

I even tried running command like `Get-Module -Name Hyper-V -ListAvailable` nothing is listed in output

**Comment by vexx32** [comment]
The Hyper-V module isn't maintained by the PowerShell team themselves; you'll need to submit a UserVoice or Windows Feedback ticket for this one, I think.

**Comment by anmenaga** [comment]
Some thoughts...
1) Looks like [minikube](https://github.com/kubernetes/minikube) is currently using Windows PowerShell. Somebody should advise minikube folks to switch to PowerShell Core / releases of this repo. Windows PowerShell (unlike this repo / PS Core) is basically in maintenance mode at this point and only taking high-impact security fixes.
2) As continuation from the previous point - this issue, being a problem with Windows PowerShell, does Not belong to this repo.
3) As an idea: try comparing `$Env:PSModulePath` on machines where scenario works and where it doesn't.
