### ISSUE TITLE
Parse 'types' when provided as parameter value

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/PowerShell#13469]
## Summary of the new feature/enhancement
 
Example function:
```
function Write-SystemEnvironmentVersion {
    [CmdletBinding()]

    Param ($SystemEnvironmentVersion)
   
    $SystemEnvironmentVersion
}
```

# works:

Write-SystemEnvironmentVersion -SystemEnvironmentVersion ( [System.Environment]::Version )

# console output:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      30319  42000
```
# dosen't work (no brackets):
Write-SystemEnvironmentVersion -SystemEnvironmentVersion [System.Environment]::Version

# console output (string):
`[System.Environment]::Version`

Can you make the `type` to be parsed **without brackets**?

Is this would be a significant amount of work?
Possible breaking change?

**Comment by SeeminglyScience** [comment]
It bothers the hell out of me too, but <kbd>[</kbd> and <kbd>]</kbd> are wildcard pattern characters so the risk it very high.

**Comment by ALIENQuake** [comment]
Well, it's the same for function names, since strings don't need to be 'quoted' when provided as a parameter value. Strings are used much ofter than functions/types/methods so I guess it can't be avoided.
