### ISSUE TITLE
Make path a alias for cd env:

### ISSUE THREAD

**Issue by indiafoxtrot** [PowerShell/PowerShell#13464]
## Summary of the new feature/enhancement
It would be a cool feature to make the command 'path' or 'PATH' redirect you to the 'cd env:' environment because that is pretty much what it represents.

**Comment by vexx32** [comment]
Is this a thing I just have never heard of that's common in Bash or something? I'm a bit lost as to what the intended effect is, to be honest.

Anyway, you can do something like this by defining a short function in your profile:
```ps1
function path {
    Set-Location env:
}
```
