### ISSUE TITLE
Restart-Computer -Force sometimes failed

### ISSUE THREAD

**Issue by yukozh** [PowerShell/PowerShell#13461]
## Steps to reproduce

```powershell
Restart-Computer -Force

```

## Expected behavior

Restart the computer

## Actual behavior

Sometimes, due to some process hang, the reboot will fail.

**Comment by iSazonov** [comment]
Without clear repro steps it is impossible to investigate and fix something.

**Comment by daxian-dbw** [comment]
@yukozh, also, including the environment data as instructed by the bug template would be very helpful for us to triage the issue.
