### ISSUE TITLE
Enable simple detection of [AutomationNull]::Value with -is [AutomationNull]

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13465]
* Follow-up from #9997, which lacked a clear proposal.
* Related to #11921 (`-is [pscustomobject]`) and #10704 (`-is $null`)

## Summary of the new feature/enhancement

Enable the following `-is` test to allow for a PowerShell-idiomatic detection of the `[System.Management.Automation.Internal.AutomationNull]::Value` value that commands that output "nothing" technically output.

```powershell
# `& {}` outputs "nothing", which is technically [System.Management.Automation.Internal.AutomationNull]::Value
PS> & {} -is [AutomationNull]   # WISHFUL THINKING
True
```

In _expression_ contexts `[System.Management.Automation.Internal.AutomationNull]::Value` is treated like `$null`, but there are **contexts where the distinction matters**:

In the **pipeline**:

```powershell
# A true $null is sent through the pipeline. 
PS> $null  | % { 'here' }
here

# [System.Management.Automation.Internal.AutomationNull]::Value is NOT sent through the pipeline
#  - it is an empty enumeration.
PS> & { }  | % { 'here' }
# NO output
```

Also, because the **`switch` statement** treats its operand as an _enumeration_, a `[System.Management.Automation.Internal.AutomationNull]::Value` value causes the statement to be skipped altogether; that is, it is effectively _ignored_:

``` powershell
$val = & {}
# Because $val contains [System.Management.Automation.Internal.AutomationNull]::Value,
# the switch statement is effectively ignored;
switch ($val) {
  default { 'hi' }
}
```

**Operators** behave inconsistently with AutomationNull as the LHS (see #3866):

```powershell
PS> [System.Management.Automation.Internal.AutomationNull]::Value -match 'foo'
# NO OUTPUT - LHS was interpreted as *collection*

PS> [System.Management.Automation.Internal.AutomationNull]::Value -eq 'foo'
False # LHS was interpreted as a *scalar*
```

In short: **Because `[System.Management.Automation.Internal.AutomationNull]::Value` causes observable differences in behavior from `$null`, it must be discoverable.**

## Proposed technical implementation details (optional)

Note: Strictly speaking, `[System.Management.Automation.Internal.AutomationNull]::Value` is of type `[System.Management.Automation.PSObject]`, but treating it as an instance of `AutomationNull` would be a helpful "white lie", similar to the one `-is` already tells when it reports a `[psobject]` wrapper's `.BaseObject`  value's type as the type.

However, @SeeminglyScience's  [proposed implementation here](https://github.com/PowerShell/PowerShell/issues/9997#issuecomment-580743572) would actually resolve this issue, via a new, _public_ `System.Management.Automation.AutomationNull` wrapper, for which an `[AutomationNull]` _type accelerator_ would have to be defined.

**Comment by briantist** [comment]
I really like this proposal. 

The differences between `$null` and "nothing" confound users who inevitably run into it, and the ones who are curious enough to try to understand why and make clear comparisons end up disappointed and with a view of PowerShell as a "weird" language (or at worst one they can't trust). 

True story: I worked at a company where the team who used PowerShell the most had as their team's chat description:
> PowerShell obeys the principle of most surprise

The concept of a `$null` result vs. "no result" is not difficult to understand, but only being able to reason about a result implicitly instead of being able to just _ask the language_ is not a good UX.

`$value -is [AutomationNull]` is clear and concise.

**Comment by CopaceticMeatbag** [comment]
Any chance this is going to be looked at eventually? The current implementation makes zero intuitive sense. This is such a basic and common use case, what's the hold up?
```
$CurrentDevices = Get-AudioDevice -List | ? type -eq 'Playback' #no match so returns an Internal.AutomationNull instead of $null
switch($CurrentDevices){
    default {write-host "this will never run because of some obscure non-public value returned that I can't inspect and the official response 2 years later is still just 'lol'"}
}
```

**Comment by SeeminglyScience** [comment]
@CopaceticMeatbag This issue is about an easier way to detect autonull, not a change in the behavior. That behavior in particular is relied upon heavily so I would not expect it to change.

On an unrelated note, this issue is missing a needs triage tag, adding so the Engine WG can discuss it.

**Comment by CopaceticMeatbag** [comment]
@SeeminglyScience yes I'm sorry I should've been clearer; I think `$value -is [AutomationNull]` is a great halfway solution and would at least give me an option to work with.

I read through issue #9997 and don't understand how @bpayette 's comments make sense to nullify the whole discussion. E.g. "The intent was to make AutomationNull as invisible to script users as possible". Ok sure, but PS is returning an [AutomationNull] result to me, and I'm trying to confirm that, and the response is "you're not meant to use that"? So why return it then if I'm not meant to use it? Feels like the PS team is more than happy shifting the burden onto the end user as a 'fix' for this issue.

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this yesterday and agree to go forward with my proposal laid out in [`#9997 (comment)`](https://github.com/PowerShell/PowerShell/issues/9997#issuecomment-580743572) with the requirement that #18914 is implemented and the currently pubternal type is decorated with `HiddenAttribute`.

**Comment by daxian-dbw** [comment]
Reopen this "up-for-grab" issue.
