### ISSUE TITLE
Existing directories being reported as not found

### ISSUE THREAD

**Issue by andyfore** [PowerShell/PowerShell#13472]
So the issue I am having is that in the latest release of Powershell 7 Preview when I attempt to run executables, like ssh, or to navigate to some subdirectories they are not registering as extant. Obviously, if Powershell feels that the directory doesn't exist then it will not execute any of the binaries inside the directory either, which is how I found this in the first place.  At first, I thought this might some artifact of my custom user profile, so I removed it but I was still able to reproduce the behavior, Here is what I am seeing.

## Steps to reproduce

```none
enter cd and the path that you wish to navigate to
```

## Expected behavior

```powershell
PS C:\Users\andyf> cd C:\WINDOWS\System32\OpenSSH\
PS C:\Windows\System32\OpenSSH>
```

## Actual behavior

```none
PS C:\Users\andyf> cd C:\WINDOWS\System32\OpenSSH\
Set-Location: Cannot find path 'C:\WINDOWS\System32\OpenSSH\' because it does not exist.
```

## Environment data
This is the output from Preview 6, where the action does not work.

```none
PS C:\Users\andyf> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.6
PSEdition                      Core
GitCommitId                    7.1.0-preview.6
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Here is the same data from Preview 5 where the action does work:

```none
PS C:\Windows\System32\OpenSSH> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.5
PSEdition                      Core
GitCommitId                    7.1.0-preview.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rjmholt** [comment]
I've just tried this on my own machine, but am unable to reproduce the issue:

![ssh](https://user-images.githubusercontent.com/7009879/90541080-f6018600-e136-11ea-99df-fc48f2390b7d.gif)

The two possibilities that come to mind are:

- There's a permissions issue with the directory/executable you're trying to execute
- The path that doesn't exist is actually the one that PowerShell is trying to come from rather than go to

**Comment by andyfore** [comment]
I uninstalled PowerShell preview completely from my machine and reinstalled and now everything is working as expected.  This is very odd, since in the past I was able to just update from each release to the next without and uninstall/reinstall loop.

**Comment by vexx32** [comment]
The only thing I can think of is maybe you were running into an issue with an x86 version of pwsh installed and not able to see x64 directories under C:\Windows?

Other than that... not a clue.

**Comment by DHowett** [comment]
> The only thing I can think of is maybe you were running into an issue with an x86 version of pwsh installed and not able to see x64 directories under C:\Windows?

_precisely this_, and no other explanation.
