### ISSUE TITLE
Do we need Enable-RunspaceDebug.Tests.ps1 file?

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#13470]
Do we need `Enable-RunspaceDebug.Tests.ps1` file?

https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.Tests.ps1 was added as part of #8923, then in #10338 the functionality it tests was removed.

When run, its tests are skipped because `Microsoft.PowerShell.Utility.PSDebugRunspaceWithBreakpoints` experimental feature doesn't exist, or else the tests would fail.

https://github.com/PowerShell/PowerShell/blob/904e5511789f0a8375c23c9a1ee59918be0a82a1/test/powershell/Modules/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.Tests.ps1#L9-L14

Should we remove the file?

## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by vexx32** [comment]
Wasn't this recently added back in during the most recent preview cycle? 🤔
