### ISSUE TITLE
WindowsInstaller.Tests.ps1 test WMF link invoke tests failing...

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#13478]
## Steps to reproduce

```powershell
Invoke-Pester WindowsInstaller.Tests.ps1
```

## Expected behavior

```none
Tests pass
```

## Actual behavior

```none
WMF 4.0 link invocation fails.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
This test checks for expected links in Product.wxs file, but then invokes the links to see if they are alive.  Many times they are not and there is a retry loop.  In this case WMF 4.0 link is not working.  Don't know if the link was pulled on purpose.

However, this does not seem like a good test for PowerShell, as PowerShell has nothing to do whether these links work and if they don't should not cause PowerShell build to fail.  I will mark the link invocation test as 'pending'.

**Comment by daxian-dbw** [comment]
@TravisEz13, if the that WMF 4 link is not coming back, then we potentially need to change the link in the installer script.

**Comment by TravisEz13** [comment]
Sounds right, I think anyone can change the link.

**Comment by iSazonov** [comment]
I found short link http://go.microsoft.com/fwlink/?LinkId=293881 - does not work too.

**Comment by daxian-dbw** [comment]
@joeyaiello and @sdwheeler, can you please check with someone from the download center to see if it's intentional to remove the WMF 4 download link?

**Comment by joeyaiello** [comment]
Yeah, we're following up.

**Comment by joeyaiello** [comment]
Still looking into seeing what can be done here, would love to know if this is impacting anyone today out in the real world.

**Comment by iSazonov** [comment]
Is it all about Windows 7 support? If intention is to support Windows 7 in .Net 6.0 I think we still need WMF 4.0 with updates.

**Comment by iSazonov** [comment]
I guess .Net 6.0 will support Windows 7. And question is will we support the next LTS version PowerShell 7.2 on Windows 7? If yes, maybe MSFT approve distributing WMF 4 in PowerShell 7.2 packages as an optional unsupported update?
