### ISSUE TITLE
Parameter parsing/passing: in native executable calls, arguments that look like named PowerShell arguments do not treat the grouping operator as a separate argument

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13488]
Follow-up from https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-676617510.
Related: #13489, #6360, #6291

In short: Using an expression (via `(...)`, the grouping operator) as part of an argument normally causes the output from that expression to be passed as a _separate_ argument (which in itself may be surprising - see #6467).

This is _not_ the case in the following, very specific scenario:

* An external (native) executable is being called.

* The start of the argument looks something like `-foo:`, i.e. _looks like_ a named PowerShell argument, though that concept doesn't apply when calling external programs; note that any other prefix before the `(...)` does _not_ trigger the symptom.

In that event, the (stringified) `(...)` output is directly attached to `-foo:` to form a single argument, though note that if the output is a _collection_, only the _first_ element is attached.

There is no good reason for this anomaly, and the behavior with collections is virtually useless.

## Steps to reproduce

```powershell
# OK: PowerShell command: the output from (...) is passed as a *separate* argument.
Write-Output -foo:('bar', 'baz') | Should -BeExactly '-foo:', ('bar', 'baz')

# On Unix:
# BROKEN: External program: the output from (...) is partially passed as part of `-foo:`, namely 
# (only) the *first* array element.
printf '%s\n' -foo:('bar', 'baz') | Should -Be '-foo:', 'bar', 'baz'
```

## Expected behavior

The tests should pass.

## Actual behavior

The second test fails:

```none
Expected @('-foo:', 'bar', 'baz'), but got @('-foo:bar', 'baz')
```

Note how only _2_ arguments were passed, because the first array element, `bar`, was directly attached to `-foo:`.

## Environment data

```none
PowerShell Core 7.1.0-preview.6
```

**Comment by vexx32** [comment]
/cc @JamesWTruher for visibility.

@mklement0 I half suspect you must spend a lot of time _trying_ to break things around this 😂  (But honestly, thanks; I doubt we'd find half these things if you didn't!)

**Comment by yecril71pl** [comment]
The concept of passing named parameter values *does* apply when the external program is `pwsh` that is called to run an existing script.
