### ISSUE TITLE
Duplicate ExperimentalFeatures entries in powershell.config.json

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#13490]
## Steps to reproduce
Download [powershell-7.1.0-preview.6-linux-x64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.1.0-preview.6/powershell-7.1.0-preview.6-linux-x64.tar.gz)
Open `powershell.config.json` in text editor

## Expected behavior

Each ExperimentalFeature is mentioned once.

## Actual behavior

There are duplicate entries for:
    "Microsoft.PowerShell.Utility.PSManageBreakpointsInRunspace",
and
    "PSDesiredStateConfiguration.InvokeDscResource"

![ExpFeatureDupEntries](https://user-images.githubusercontent.com/11860095/90813778-e754d380-e2dc-11ea-98c0-dafbf930385c.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.6
PSEdition                      Core
GitCommitId                    7.1.0-preview.6
OS                             Linux 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rjmholt** [comment]
Is this a static asset generated by the build, or something PowerShell creates when it first starts?

**Comment by MaximoTrinidad** [comment]
Interesting!

But it doesn't show the duplicates when executing the "**Get-ExperimentalFeatures**" cmdlet.

![expfeaCmdlet_01_2020-08-20_17-20-01](https://user-images.githubusercontent.com/19892435/90827015-7a0b6780-e309-11ea-948b-91ff97c2d1cf.jpg)

**Comment by daxian-dbw** [comment]
@rjmholt It's an artifact generated at build time, at the end of `Start-PSBuild`.

@MaximoTrinidad I guess duplicates are tolerated.

**Comment by TravisEz13** [comment]
If duplicates are tolerated, this seems like a superficial bug.  I've moved to future.
