### ISSUE TITLE
Module Load and Unload Event

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13493]
## Request

The PowerShell engine does not expose events for module authors to subscribe when a module load/unload event occurs. This causes module authors to implement workarounds to identify when a module is loaded/unloaded.

Add module load/unload events.

## Background

I have a module that uses other modules to ship "providers" like the `PSProvider` system. PowerShell is able to inspect modules during load to identify if a module contains a `PSProvider` and add it to the internal cache of providers. PowerShell is also able to remove the `PSProvider` from the cache when the module is unloaded. Modules that leverage a provider model outside of the engine have to use workarounds to discover providers inside other modules.

`PackageManagement` does not import providers when a module is loaded but instead requires the user to call `Import-PackageProvider` to load the provider. If the module containing the provider is removed the provider is not removed and there is no command to remove it.

`SHiPS` requires the provider to use a specific naming convention for the SHiPS provider to load the script module provider.

### PSModuleInfo.OnRemove

This can be used to inject logic into another module unload action but there is no protection against this logic from being wiped out from the module or other user.

### IModuleAssemblyInitializer/IModuleAssemblyCleanup or Script Module

These run in the target module but have to implemented by the other module author.

**Comment by anmenaga** [comment]
There is [PSModuleInfo.OnRemove](https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/Modules/PSModuleInfo.cs#L1417) .
The trick with that is allows only for a single handler. So if setting it to your handler, it is a good idea to check if it is already set by something else, save that original handler and call it in the end of your handler.
