### ISSUE TITLE
Implement the exec command on Unix systems

### ISSUE THREAD

**Issue by r-darwish** [PowerShell/PowerShell#13510]
## Summary of the new feature/enhancement

Unix shell usually have an [exec](https://ss64.com/bash/exec.html) command which calls the [exec](https://linux.die.net/man/3/exec) system call. It would be nice to have that in Powershell as well.

**Comment by vexx32** [comment]
This might be a duplicate of #12750? 🤔

**Comment by r-darwish** [comment]
Seems so. Sorry for the duplicate.
