### ISSUE TITLE
Linux - Powershell 7 - linux commands should not truncate results by default 

### ISSUE THREAD

**Issue by nddipiazza** [PowerShell/PowerShell#13513]
## Steps to reproduce

Run a command that will need to word wrap in your terminal:

```powershell
ps aux
```

## Expected behavior

should not truncate the commands, just like if you ran it in normal linux terminal emulator

```
ndipiaz+ 2473076 22.5  6.2 96664472 4094576 ?    Sl   11:48  52:03 /home/ndipiazza/Downloads/idea-IC-191.8026.42/jre64/bin/java -classpath /home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/bootstrap.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/extensions.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/util.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/jdom.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/log4j.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/trove4j.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/lib/jna.jar:/home/ndipiazza/Downloads/idea-IC-191.8026.42/jre64/lib/tools.jar -Xms128m -Xmx4750m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -XX:CICompilerCount=2 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djdk.http.auth.tunneling.disabledSchemes="" -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Dawt.useSystemAAFontSettings=lcd -Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine -Dsun.tools.attach.tmp.only=true -XX:ErrorFile=/home/ndipiazza/java_error_in_IDEA_%p.log -XX:HeapDumpPath=/home/ndipiazza/java_error_in_IDEA.hprof -Didea.paths.selector=IdeaIC2019.1 -Djb.vmOptionsFile=/home/ndipiazza/.IdeaIC2019.1/config/idea64.vmoptions -Didea.platform.prefix=Idea -Didea.jre.check=true com.intellij.idea.Main
```

## Actual behavior

it truncated things:

```
ndipiaz+ 2473418  0.1  0.3 4113528 217760 ?      Sl   11:50   0:16 /home/ndipiazza/Downloads/idea-IC-191.8026.42/jre64/bin/java -Djava.awt.headless=true -Didea.version==2019.1.4 -Xmx76
```

This is not what a linux terminal user sees by default when using other shells. It should default to the same as any other linux terminal in this respect. This makes it harder to transition to using powershell as your main shell.

## Environment data

Ubuntu + Gnome 20.04.1

Same thing happens on xterm, terminal emulator, and terminator.

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.3}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Weird that this would truncate, it's just outputting a string. 😕 

It's definitely just a display artifact; PS itself receives all the data. You can check this with something like:

```ps1
$string = ps aux
$string
```

The full output will wrap correctly. @SteveL-MSFT probably worth looking into what's up here, something in the formatting systems perhaps?

**Comment by nddipiazza** [comment]
Hi thanks for the fast response! Ran the command you recommended. Same result:

```
/home/ndipiazza> $string = ps aux
/home/ndipiazza> $string         
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          58  0.0  0.0      0     0 ?        I<   Aug18   0:00 [netns]
root          59  0.0  0.0      0     0 ?        S    Aug18   0:00 [rcu_tasks_kt
root          60  0.0  0.0      0     0 ?        S    Aug18   0:00 [kauditd]
...
nx          1144  0.1  0.1 643892 112548 ?       Ssl  Aug18  11:06 /usr/NX/bin/n
root        1154  0.0  0.0 239696  8260 ?        Ssl  Aug18   0:00 /usr/sbin/gdm
root        1268  0.0  0.0 4770792 42820 ?       Ssl  Aug18   3:32 /usr/bin/dock
whoopsie    1272  0.0  0.0 253380 15012 ?        Ssl  Aug18   0:00 /usr/bin/whoo

```

I tried only on Ubuntu 20.x with Linux alienw 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/2238777/91096232-4a1ed580-e623-11ea-9aff-76be3b7d98cd.png)

**Comment by vexx32** [comment]
Even weirder. I get different results if I store the result first. 😕

**Comment by DHowett** [comment]
It was my understanding that `ps` outputs truncated text to the terminal (assuming that it can measure the width. It may not be able to during output redirection.) **unless** you pass `w` or `ww`. This reproduces for me on every shell on every terminal emulator I’ve used.

There may be an environment variable controlling `ps`’s default behavior that you’re not setting in PowerShell?

**Comment by nddipiazza** [comment]
ok `ps auxww` works in powershell without being truncated. 
that's weird.... the environment variables are the exact same.

**Comment by vexx32** [comment]
There may be something in the terminal emulator you're using which prevents `ps` from automatically measuring the console width, so it doesn't surface there.

I'm going to mark this one as external for now, since it seems to be done by `ps` itself and not pwsh. 🙂

**Comment by nddipiazza** [comment]
yep - closing. thanks for the assist!
