### ISSUE TITLE
cant't paste this multiplication sign with powershell "-geometry 1280×1024"

### ISSUE THREAD

**Issue by wswind** [PowerShell/PowerShell#13514]
I use powershell 7.0 on win10 with win32_openssh to manage remote linux servers.
When I try to paste the following line into vnc service config file, the multiplication sign is missing.

```
ExecStart=/sbin/runuser -l pkumar -c "/usr/bin/vncserver %i -geometry 1280×1024"
```
It's very weird, I tried to use utf8 and  Cascadia Code PL as fontFace, but the problem still exists.

Cmd and powershell in conemu doesn't have the same problem. So I cant figure out where is the problem.Please help me.

## Steps to reproduce

1.copy 
```
1280×1024
```
2.past it into powershell window

## Expected behavior

can past multiplication sign

## Actual behavior

 the multiplication sign will be missing
![image](https://user-images.githubusercontent.com/18399096/91129912-5c5d4a00-e6dd-11ea-8425-8f2a152652b8.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Can you try doing the same with PSReadLine unloaded (`Remove-Module PSReadLine`)?

If that works, you may want to have a look through the [PSReadLine issues](/PowerShell/PSReadLine/issues) to see if an existing issue has already been filed for this & file this there if there isn't already one. 🙂

**Comment by kilasuit** [comment]
Can confirm that this doesn't happen when PSReadline is not loaded therefore this has to be a PSReadline issue & depending on which method you use to paste (

With PSReadline (Ctrl+v - Works as expected)
![image](https://user-images.githubusercontent.com/6355225/91176129-bcea8800-e6d9-11ea-9c44-7192fa7cf086.png)

With PSReadline (RightClick - Does not work as expected)
![image](https://user-images.githubusercontent.com/6355225/91176228-dc81b080-e6d9-11ea-850c-7e755956857d.png)


without PSReadline (either method)
![image](https://user-images.githubusercontent.com/6355225/91175982-86ad0880-e6d9-11ea-96c8-5db9996aefcc.png)

**Comment by wswind** [comment]
@vexx32  @kilasuit   Thanks very much for your help. It is PSReadline's issue. 
I will close this issue.

**Comment by wswind** [comment]
<https://github.com/PowerShell/PSReadLine/issues/1771>

**Comment by nu8** [comment]
https://github.com/dotnet/runtime/issues/38966

**Comment by nu8** [comment]
https://github.com/PowerShell/PSReadLine/issues/1603
