### ISSUE TITLE
Feature Request: Support PowerShell Core 

### ISSUE THREAD

**Issue by leandrolerena** [PowerShell/PowerShell#13511]
## Summary of the new feature/enhancement

The CSOM library is available on .NET core, can we have support for powershell core, cross-os? Would like to use it on linux containers :-) 

## Proposed technical implementation details (optional)

Base on the .NET core CSOM package on nuget

https://developer.microsoft.com/en-us/microsoft-365/blogs/net-standard-version-of-sharepoint-online-csom-apis/

**Comment by vexx32** [comment]
This request would probably be best asked of the Sharepoint team themselves. The PowerShell team don't own or manage the Sharepoint modules themselves. 🙂
