### ISSUE TITLE
CLI: Prevent nonsensical interactive invocation with -NonInteractive

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13518]
## Steps to reproduce

```powershell
pwsh -NonInteractive
```

## Expected behavior

An error should be reported indicating that this invocation makes no sense.

## Actual behavior

An interactive session is entered, but any later attempts to use `Read-Host` or confirmation prompts in the session will cause statement-terminating errors.

## Environment data

```none
PowerShell Core 7.1.0-preview.6
```

**Comment by iSazonov** [comment]
I guess a design intention is only to disable interactive commands. 
CLI docs was updated but web docs no https://github.com/PowerShell/PowerShell/pull/13748/files#r559324087
