### ISSUE TITLE
Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

### ISSUE THREAD

**Issue by GuzmanDiaz18** [PowerShell/PowerShell#13526]
## Steps to reproduce

1.- Run PowerShell 7 as administrator.
2.- Write the command: Install-Module -Name Az -AllowClobber -Force

## Expected behavior

Install new version of Az module.

## Actual behavior

![2020-08-26_13-42-43](https://user-images.githubusercontent.com/1861609/91343385-1918df00-e7a2-11ea-8f04-5647212f41c0.jpg)

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by jdhitsolutions** [comment]
I was able to run your command in 7.0.3 in a Windows Sandbox session with no error. Is it just the AZ module that gives you this error when installing?

**Comment by GuzmanDiaz18** [comment]
> I was able to run your command in 7.0.3 in a Windows Sandbox session with no error. Is it just the AZ module that gives you this error when installing?

Yes, Can we do any additional tests? What commands can I run to do more additional tests?

**Comment by jdhitsolutions** [comment]
Can you install any other module from the PowerShell Gallery?  You can try one of mine that is small.

```powershell
Install-Module PSTeachingTools -force
```

**Comment by GuzmanDiaz18** [comment]
> Can you install any other module from the PowerShell Gallery? You can try one of mine that is small.
> 
> ```powershell
> Install-Module PSTeachingTools -force
> ```

I ran it and it didn't show me any error.

![2020-08-26_16-44-25](https://user-images.githubusercontent.com/1861609/91360129-7a00e100-e7bb-11ea-8dd1-2dbc2482ad69.jpg)

**Comment by jdhitsolutions** [comment]
That's good. I'd say try the AZ module again in a new session. If it fails again, then there must be something about that module and your computer. Because I had no problems installing the AZ module on different systems.

**Comment by GuzmanDiaz18** [comment]
> That's good. I'd say try the AZ module again in a new session. If it fails again, then there must be something about that module and your computer. Because I had no problems installing the AZ module on different systems.

I did a test with the PowerShell 5 and it lets me run the command with no problem.

![2020-08-26_17-30-53](https://user-images.githubusercontent.com/1861609/91363319-ff878f80-e7c1-11ea-9eec-3f9af538e607.jpg)

**Comment by vexx32** [comment]
You may need to update the version of your PowerShellGet module as well.

**Comment by jdhitsolutions** [comment]
It looks like he has the most current version of PowerShellGet. Run `Install-Module` with -Verbose and paste the results. You might find it easier to start a transcript, run the install verbosely, stop the transcript then past the verbose messages. Don't post a screen shot. That's too hard to read.

**Comment by GuzmanDiaz18** [comment]
> It looks like he has the most current version of PowerShellGet. Run `Install-Module` with -Verbose and paste the results. You might find it easier to start a transcript, run the install verbosely, stop the transcript then past the verbose messages. Don't post a screen shot. That's too hard to read.

PS C:\Users\Celso J. Guzman Diaz> Install-Module -Name Az -AllowClobber -Force -Verbose
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
VERBOSE: Acquiring providers for assembly: C:\program files\powershell\7\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'Az'.
VERBOSE: Performing the operation "Install-Module" on target "Version '4.6.0' of module 'Az'".
VERBOSE: The installation scope is specified to be 'CurrentUser'.
VERBOSE: The specified module will be installed in 'C:\Users\Celso J. Guzman Diaz\OneDrive\Documentos\PowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'Az' with version '4.6.0' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Advisor'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Aks'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.AnalysisServices'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ApiManagement'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ApplicationInsights'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Automation'' for ''.                                                                                                                       VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Batch'' for ''.                                                                                                                            VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Billing'' for ''.                                                                                                                          VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Cdn'' for ''.                                                                                                                              VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.CognitiveServices'' for ''.                                                                                                                VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Compute'' for ''.                                                                                                                          VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ContainerInstance'' for ''.                                                                                                                VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ContainerRegistry'' for ''.                                                                                                                VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DataBoxEdge'' for ''.                                                                                                                      VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DataFactory'' for ''.                                                                                                                      VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DataLakeAnalytics'' for ''.                                                                                                                VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DataLakeStore'' for ''.                                                                                                                    VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DataShare'' for ''.                                                                                                                        VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DesktopVirtualization'' for ''.                                                                                                            VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DeploymentManager'' for ''.                                                                                                                VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.DevTestLabs'' for ''.                                                                                                                      VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Dns'' for ''.                                                                                                                              VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.EventGrid'' for ''.                                                                                                                        VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.EventHub'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.FrontDoor'' for ''.                                                                                                                        VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Functions'' for ''.                                                                                                                        VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.HDInsight'' for ''.                                                                                                                        VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.HealthcareApis'' for ''.                                                                                                                   VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.IotHub'' for ''.                                                                                                                           VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.KeyVault'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.LogicApp'' for ''.                                                                                                                         VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.MachineLearning'' for ''.                                                                                                                  VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Maintenance'' for ''.                                                                                                                      VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ManagedServices'' for ''.                                                                                                                  VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.MarketplaceOrdering'' for ''.                                                                                                              VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Media'' for ''.                                                                                                                            VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Monitor'' for ''.                                                                                                                          VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Network'' for ''.                                                                                                                          VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.NotificationHubs'' for ''.                                                                                                                 VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.OperationalInsights'' for ''.                                                                                                              VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.PolicyInsights'' for ''.                                                                                                                   VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.PowerBIEmbedded'' for ''.                                                                                                                  VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.PrivateDns'' for ''.                                                                                                                       VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.RecoveryServices'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.RedisCache'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Relay'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Resources'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ServiceBus'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.ServiceFabric'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.SignalR'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Sql'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.SqlVirtualMachine'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Accounts'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Storage'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.StorageSync'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.StreamAnalytics'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Support'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.TrafficManager'' for ''.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Az.Websites'' for ''.
VERBOSE: InstallPackage' - name='Az.Accounts', version='1.9.3',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723'
VERBOSE: DownloadPackage' - name='Az.Accounts', version='1.9.3',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723\Az.Accounts.1.9.3\Az.Accounts.1.9.3.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Az.Accounts/1.9.3'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Az.Accounts/1.9.3'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Az.Accounts/1.9.3'.
VERBOSE: Completed downloading 'Az.Accounts'.
VERBOSE: InstallPackageLocal' - name='Az.Accounts', version='1.9.3',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723'
VERBOSE: InstallPackage' - name='Az.Advisor', version='1.1.1',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723'
VERBOSE: DownloadPackage' - name='Az.Advisor', version='1.1.1',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723\Az.Advisor.1.1.1\Az.Advisor.1.1.1.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Az.Advisor/1.1.1'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Az.Advisor/1.1.1'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Az.Advisor/1.1.1'.
VERBOSE: Completed downloading 'Az.Advisor'.
VERBOSE: InstallPackageLocal' - name='Az.Advisor', version='1.1.1',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723'
VERBOSE: InstallPackage' - name='Az.Aks', version='1.2.0',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723'
VERBOSE: DownloadPackage' - name='Az.Aks', version='1.2.0',destination='C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723\Az.Aks.1.2.0\Az.Aks.1.2.0.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Az.Aks/1.2.0'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Az.Aks/1.2.0'.
VERBOSE: Validating the 'Az.Accounts' module contents under 'C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723\Az.Accounts.1.9.3' path.
VERBOSE: Test-ModuleManifest successfully validated the module manifest file 'C:\Users\Celso J. Guzman Diaz\AppData\Local\Temp\1560227723\Az.Accounts.1.9.3'.
VERBOSE: Validating the authenticode signature and publisher of the catalog file or module manifest file of the module 'Az.Accounts'.
VERBOSE: Catalog file 'Az.Accounts.cat' is not found in the contents of the module 'Az.Accounts' being installed.
VERBOSE: Valid authenticode signature found in the file 'Az.Accounts.psd1' for the module 'Az.Accounts'.
VERBOSE: For publisher validation, current module 'Az.Accounts' with version '1.9.3' with publisher name 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' from root certificate authority 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
VERBOSE: For publisher validation, using the previously-installed module 'Az.Accounts' with version '1.9.3' under 'C:\Users\Celso J. Guzman Diaz\OneDrive\Documentos\PowerShell\Modules\Az.Accounts\1.9.3' with publisher name 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' from root certificate authority 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
VERBOSE: Authenticode issuer 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' of the new module 'Az.Accounts' with version '1.9.3' matches with the authenticode issuer 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' of the previously-installed module 'Az.Accounts' with version '1.9.3'.
VERBOSE: Checking for possible command collisions for the module 'Az.Accounts' commands.
VERBOSE: Installing the dependency module 'Az.Accounts' with version '1.9.3' for the module 'Az'.
Install-Package: C:\Users\Celso J. Guzman Diaz\OneDrive\Documentos\PowerShell\Modules\PowerShellGet\2.2.4.1\PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

**Comment by derekscha** [comment]
> 'C:\Users\Celso J. Guzman Diaz\OneDrive\Documentos\PowerShell\Modules'

I had the same issue. I am also redirecting my Documents folder to my OneDrive folder for replication. I had to remove the Modules folder manually and re-install all of my modules to get the Az module to install on a new machine. I'll be investigating options like [this one found on Stack](https://stackoverflow.com/questions/56786702/how-to-change-powershell-default-module-installation-folder) to move where my profile gets the modules from. It would be a lot nicer if we could redirect the modules and scripts folders away from the Documents folder for reasons like this. Hope this helps others.

**Comment by GuzmanDiaz18** [comment]
> > 'C:\Users\Celso J. Guzman Diaz\OneDrive\Documentos\PowerShell\Modules'
> 
> I had the same issue. I am also redirecting my Documents folder to my OneDrive folder for replication. I had to remove the Modules folder manually and re-install all of my modules to get the Az module to install on a new machine. I'll be investigating options like [this one found on Stack](https://stackoverflow.com/questions/56786702/how-to-change-powershell-default-module-installation-folder) to move where my profile gets the modules from. It would be a lot nicer if we could redirect the modules and scripts folders away from the Documents folder for reasons like this. Hope this helps others.

If I already assumed it, I did everything you indicate at the time and it worked but this is a problem for a common user.

**Comment by sergeevabc** [comment]
Windows 7 x64 user here, with PowerShell 7.2.17.

I'm trying to convert RGB to HEX as follows

``` console
echo 255 0 0 | pwsh -c "'{0:X2}{1:X2}{2:X2}'-f$input"
```
Expected output: FF0000

But I get 'InvalidOperation: Error formatting a string: Index (zero based) must be greater than or equal to zero and less than the size of the argument list..' Why?
