### ISSUE TITLE
Feature Request Class Named and Optional Arguments

### ISSUE THREAD

**Issue by ili101** [PowerShell/PowerShell#13520]
## Summary of the new feature/enhancement

In C# you can call a method omitting the optional parameters and by name, I suggest adding the option to do the same thing in PowerShell.
In addition to being more compatible with C# Classes this is more in line with what PowerShell users expect as it's resembles the PowerShell Functions style where you already use optional and named parameters regularly.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments

## Proposed technical implementation details (optional)

``` powershell
# Apparently defining default values doesn't throw an error so already works?
class ClassName {
    ClassName([string]$sellerName, [int]$orderNum = 5, [string]$productName = 'Default') {
        Write-Host "Seller: $($sellerName), Order #: $($orderNum), Product: $($productName)"
    }
}

# Calling it normally:
[ClassName]::new("Gift Shop", 31, "Red Mug")

# Doesn't Work but should work:
[ClassName]::new("Gift Shop")
# EMethodException: Cannot find an overload for "new" and the argument count: "1".

# Some syntax options for named parameters:
# With name (C# style):
[ClassName]::new(sellerName: "Gift Shop", 31, "Red Mug")
[ClassName]::new(sellerName: "Gift Shop")
# More of a Powershell style?
[ClassName]::new(@{sellerName = "Gift Shop"}, 31, "Red Mug")
# Powershell splat style?
$Param = @{ sellerName = "Gift Shop" ; orderNum = 31 }
[ClassName]::new(@Param)
# Powershell function style?
[ClassName]::new(-sellerName "Gift Shop")
```

I see that optional parameters are already reported in https://github.com/PowerShell/PowerShell/issues/9701 https://github.com/PowerShell/PowerShell/issues/7534
But I didn't find an issue for the Named part.

**Comment by SeeminglyScience** [comment]
> ```powershell
> # Apparently defining default values doesn't throw an error so already works?
> ```

I think it doesn't throw but also doesn't actually change the type metadata any.  Also note that iirc PowerShell doesn't honor the default value of optional parameters unless they happen to be the same as `default(TheType)`.

> But I didn't find an issue for the Named part.

I think there's two but #13307 is the one to track.
