### ISSUE TITLE
A Clean Window

### ISSUE THREAD

**Issue by 1900011604** [PowerShell/PowerShell#13541]
I do not want the:
```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.
```
on the top of the screen, how to delete it?

**Comment by vexx32** [comment]
Start pwsh with the `-NoLogo` switch. 🙂 

(or just use `Clear-Screen` after it starts)

**Comment by 1900011604** [comment]
"Start pwsh with the -NoLogo switch."

Can I fix it in a file so I can start it with double-click?

**Comment by vexx32** [comment]
Yeah, you can create a standard shortcut to pwsh and add the parameter to the Target box of the shortcut.

**Comment by 1900011604** [comment]
Like this: "D:\Apps\PowerShell\7\pwsh.exe -WorkingDirectory -NoLogo ~"?
It does not work

**Comment by 1900011604** [comment]
```D:\Apps\PowerShell\7\pwsh.exe -NoLogo -WorkingDirectory ~```

It solved the problem, thanks!
