### ISSUE TITLE
PropertyNotFoundException for some OLE/COM property getters

### ISSUE THREAD

**Issue by kevinoid** [PowerShell/PowerShell#13544]
## Steps to reproduce

```powershell
Set-StrictMode -Version Latest
$dte = New-Object -ComObject 'VisualStudio.DTE'
$wasVisible = $dte.MainWindow.Visible
Write-Host "Visible: $wasVisible"
```

## Expected behavior

The script would print `Visible: false` or `Visible: 0`, which would match the behavior of a comparable WSH JScript:

```js
var dte = new ActiveXObject('VisualStudio.DTE');
var wasVisible = dte.MainWindow.Visible;
WScript.Echo("Visible: " + wasVisible);
```

## Actual behavior

    PropertyNotFoundException: C:\Users\User\Test-COM.ps1:5
    Line |
       5 |  $wasVisible = $dte.MainWindow.Visible
         |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         | The property 'Visible' cannot be found on this object. Verify that the property exists. 

If `Set-StrictMode -Version Latest` is removed, `$wasVisible` is set `$null`, whether or not the main window is visible.

## Environment data

    Name                           Value
    ----                           -----
    PSVersion                      7.1.0-preview.6
    PSEdition                      Core
    GitCommitId                    7.1.0-preview.6
    OS                             Microsoft Windows 10.0.19041
    Platform                       Win32NT
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0

This occurs with Visual Studio 2019 (Version 16.7.2) on a fresh Windows installation.  Note that [versions of Visual Studio prior to 2017 installed assemblies to the GAC](https://docs.microsoft.com/en-us/visualstudio/extensibility/breaking-changes-2017?view=vs-2019#change-global-assembly-cache-gac) which may affect the behavior on machines which had previously installed such versions.  (I haven't tested.)

See [`EnvDTE.DTEClass.MainWindow`](https://docs.microsoft.com/en-us/dotnet/api/envdte.dteclass.mainwindow) and [`EnvDTE.Window.Visible`](https://docs.microsoft.com/en-us/dotnet/api/envdte.window.visible) for the API used in the example.

Interestingly, setting `$dte.MainWindow.Visible = $true` works correctly.  The issue only appears when getting the property.

I attempted to find a reproduction using OLE/COM classes shipped with Windows, but haven't found one which exhibits the same issue.

Thanks,
Kevin

**Comment by iSazonov** [comment]
Do you see the issue in 7.0 version?

**Comment by kevinoid** [comment]
Yep.  The same issue occurs using 7.0.3 (and 5.1.19041.1).
