### ISSUE TITLE
The Conditional If does not produce error if specific syntax is incorrect

### ISSUE THREAD

**Issue by user8446** [PowerShell/PowerShell#13547]
## Steps to reproduce:
Using the conditional `If`, use the incorrect comparison operator of `=` instead of `-eq`:

```
$Sky = 'blue'

if ($Sky = 'green') {

    Write-Host "The sky is green"
}
```

## Expected behavior

We should get the error `Unexpected token '=' in expression or statement` like this if we used the incorrect comparison operator `equals`:

```
ParserError: 
Line |
   3 |  if ($Sky equals 'green') {
     |           ~~~~~~
     | Unexpected token 'equals' in expression or statement.
```
The variable should also not have been changed to `green` as you don't set variables inside of the condition to be met inside of conditionals.

## Actual behavior

No error is produced, the script continues, and the variable is set to `green`

```

## Environment data

Observed in both PowerShell & Windows PowerShell

**Comment by vexx32** [comment]
This is by design.

What's happening here is that the expression `$sky = 'green'`, which doesn't normally output data, can also be written `($sky = 'green')`, which _does_ produce output (it outputs the value `'green'` to the pipeline as well as storing it in the variable).

Knowing this, the parentheses in an `if` statement (and indeed other conditionals like `switch`) behave the same way, forcing the output and processing it in the conditional statement.

C# works the same way, it's likely a pattern copied from there.

```ps1
$sky = 'green' # no output
($sky = 'blue') # outputs 'blue'
if ($sky = 'blue') {
    # 'blue' is evaluated by the if statement and coerces to a boolean `$true` as it is not an empty or null string.
    Write-Warning "we do indeed get here"
}
```

**Comment by user8446** [comment]
Thank you for the response. 
Even though the syntax of `($Sky = 'green')` with the parenthesis is valid, the parenthesis inside of an `if` statement is *only* the condition that is to be met.
This would really confusing for people coming to PS from other languages that may use `=` as a comparison operator.

**Comment by Northman-de** [comment]
This behavior can be useful:

```powershell
while (($results = $Folder.FindItems($view)).Items.Count -gt 0) {
```
If the folder is empty the while-loop will not be entered. If there are items they are stored in `$results`

btw: $folder.FindItems() is from the Exchange Managed API (EWS)

**Comment by vexx32** [comment]
Indeed. And whether or not it can be confusing is pretty much not very relevant an this point. That's a pretty fundamental language design decision that was decided 15+ years ago.

Different languages have different syntax, that's always going to be the case. Sometimes that syntax will conflict with what folks who already know a different language might expect. 🤷

**Comment by user8446** [comment]
Thank you @vexx32
