### ISSUE TITLE
Online support for about_... help topics

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShell/PowerShell#13550]
Get-Help can display both locally cached help files and online resources.
Since online resources do not require prerequisites like Update-Help and are always up-to-date, and since online resources are much better formatted and include navigation to discover related items, a "Copy" button to copy&paste sample code, and more, many users default to using online help, i.e. by adding this to their profile:

```powershell
$PSDefaultParameterValues.Add("Get-Help:Online",$true)
```

Now, without any prerequisites, users can easily display cmdlet help in an extra window like so:

```powershell
dir -?
Get-Process -?
```

However, Get-Help -Online can only show help topics with a dedicated URI property. That's why all about_... topics fail to display even though there are online versions available.

## Steps to reproduce

```powershell
help Get-process -Online # works
help about_for -Online #fails
```

## Expected behavior
When Get-Help is used with -Online, it should detect whether the requested help starts with about_ and then construct the appropriate URI rather than fail. This could be done with a hard-coded topic list to include only the MSFT about_ topics, or simply done heuristically with the potential of failing for about topics from 3rd party.

If all else fails and there is no match, Get-Help -Online should default to the PowerShell documentation home page: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core  This would enable users to try and search there rather than being left with a red exception.

```PowerShell
Get-Help about_for -Online # should open https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_for
Get-Help about_doesnotexist -Online # should open https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core
```

## Actual behavior
Get-Help -Online fails for any topic that has no distinct URI property

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by Jaykul** [comment]
This has been asked before. It would be nice if it didn't get closed this time (see #10306). Maybe we can just agree on some format for embedding the URLs into about_*.txt files (or about*_.md?) as part of the markdown help stories?

**Comment by iSazonov** [comment]
We add a comment header https://github.com/PowerShell/PowerShell/issues/11205#issuecomment-680594689 with meta information.
If we switched to Markdown it would be more simple.

**Comment by TobiasPSP** [comment]
Adding a comment to the about topics with the URI seems to be a great workaround until eventually there is a switch to md format.

**Comment by yecril71pl** [comment]
> We add a comment header [#11205 (comment)](https://github.com/PowerShell/PowerShell/issues/11205#issuecomment-680594689) with meta information.

What do you mean by that? The comment says *we could add*&hellip;

By the English grammar (*We drink tea every morning*), it looks like we added it every day, only to be undone overnight, hence no progress ☹

**Comment by AndASM** [comment]
```
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

C:\> Get-Help -Name 'Set-ScheduledJob'

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Set-ScheduledJob                  Cmdlet    PSScheduledJob            Set-ScheduledJob…
Set-ScheduledJobOption            Cmdlet    PSScheduledJob            Set-ScheduledJobOption…
```

So... What am I doing wrong? How do you use this help system? How do you tell it you mean literally and exactly what you wrote, not something else that you didn't write?

**Comment by Jaykul** [comment]
@AndASM your problem is you're trying to get help for a module you can't import -- please start a new issue instead of hijacking this one.

**Comment by AndASM** [comment]
> 
> 
> @AndASM your problem is you're trying to get help for a module you can't import -- please start a new issue instead of hijacking this one.

It would appear I posted this in the wrong issue. There are so many things broken. I had intended it in one of the issues related to duplicates and substring matching in the help system, since that seemed relevant. But worry not, I'll just abandon it instead of risking hijacking.

**Comment by mklement0** [comment]
@sdwheeler states in https://github.com/MicrosoftDocs/PowerShell-Docs/issues/2939#issuecomment-926874648 that the `about_*` help _source_ files have now been updated with URL information; alas, the _downloaded_ versions still lack this information.

As a temporary workaround, the following may be of interest:

I've created a `Show-Help` function that is essentially a wrapper for `Get-Help -Online`, but it supports `about_*` topics too, whose URLs it constructs behind the scenes; e.g. `Show-Help about_pwsh` (tab-completion supported).

It's available from an [MIT-licensed Gist](https://gist.github.com/mklement0/880624fd665073bb439dfff5d71da886) - assuming you have looked at the code (which I can personally assure you is safe, but you should always check), you can install it directly:

```
irm https://gist.github.com/mklement0/880624fd665073bb439dfff5d71da886/raw/Show-Help.ps1 | iex
```

See also these related suggestions:

* #11338
* #11339

I've also created helper functions for these; here are all three installation commands:

```powershell
# Show-Help function (wrapper for Get-Help -Online with support for about_* topics); e.g.
#     Show-Help about_pwsh
#     Show-Help about_Automatic_Variables PSItem
irm https://gist.github.com/mklement0/880624fd665073bb439dfff5d71da886/raw/Show-Help.ps1 | iex

# Show-OperatorHelp function (online help for PowerShell's operators; e.g.
#    Show-OperatorHelp replace
irm https://gist.github.com/mklement0/146f3202a810a74cb54a2d353ee4003f/raw/Show-OperatorHelp.ps1 | iex

# Show-TypeHelp function (online documentation for .NET types and instances); e.g.
#    Show-TypeHelp regex
#    Show-TypeHelp datetime tostring
irm https://gist.github.com/mklement0/50a1b101cd53978cd147b4b138fe6ef4/raw/Show-TypeHelp.ps1 | iex
```

**Comment by Jaykul** [comment]
This one really should not be closed -- instead, it should be implemented.
