### ISSUE TITLE
Disable older version of NuGet provider to be installed or loaded on PowerShell Core from repo.

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#1355]
As NuGet provider is a part of PowerShell Core now, it no longer requires to be bootstrapped. However, we need to disable any older version of NuGet provider to be installed or used on Core because they simply won't work on PowerShell Core alpha version..
## Steps to reproduce

find-packageprovider
install-packageprovider -name NuGet -version 2.8.5.205 -force
install-module xjea
## Expected behavior

Error out if people are trying load any older version of NuGet provider
## Actual behavior

not sure yet
## Environment data

PowerShell

**Comment by SteveL-MSFT** [comment]
This issue was moved to PowerShell/PowerShellGet#27

**Comment by SteveL-MSFT** [comment]
Reopening as fix needs to be made in PSCore

**Comment by joeyaiello** [comment]
Looks like this is fixed.
