### ISSUE TITLE
Not all aliases are displayed with Get-Alias

### ISSUE THREAD

**Issue by Joe-Zer0** [PowerShell/PowerShell#13554]
Get-Alias should be able to provide the cmdlet name for all aliases.

## Steps to reproduce

```powershell
alias alias

alias unique
```

## Expected behavior

```none
alias alias
# Output:  alias -> Get-Alias

alias unique
# Output:  unique -> Get-Unique
```

## Actual behavior

```none
Get-Alias alias
Get-Alias: This command cannot find a matching alias because an alias with the name 'alias' does not exist.

Get-Alias unique
Get-Alias: This command cannot find a matching alias because an alias with the name 'unique' does not exist.
```

## Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rjmholt** [comment]
Those aren't real aliases; PowerShell automatically prepends `Get-` when commands don't resolve immediately:

https://github.com/PowerShell/PowerShell/blob/f4382202ae4622bf26795e29a7b39b9d7cdfb3fb/test/powershell/engine/Basic/CommandDiscovery.Tests.ps1#L85-L87

Unlike actual aliases, this logic isn't represented by an object or an entry in a table, it's just something PowerShell does

**Comment by rjmholt** [comment]
Basically if `Get-Alias` returned these aliases, you'd see an alias for every command beginning with `Get-` when you ran `Get-Alias`

**Comment by Joe-Zer0** [comment]
Thank you!  That is actually really cool.  Although I do with either Get-Alias or Get-Command would display some information about what was happening.

**Comment by rjmholt** [comment]
I've opened https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6576
