### ISSUE TITLE
Bug: PowerShell cannot handle a file with long non-ascii file name

### ISSUE THREAD

**Issue by hez2010** [PowerShell/PowerShell#13551]
## Steps to reproduce
Create a directory named "Test"
In the directory, create a file named "测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试.txt"
```powershell
cd Test
ls
```

## Expected behavior
Files listed normally.

## Actual behavior

```none
out-lineoutput: startIndex cannot be larger than length of string. (Parameter 'startIndex')
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.20201
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
I cannot reproduce. I guess it's related to the buffer width/height that was being used. @hez2010 can you share your buffer width/height when seeing the issue?

**Comment by hez2010** [comment]
You can resize and reduce the width of window.

**Comment by xtqqczze** [comment]
I also cannot reproduce using Windows Terminal v1.2.2381.0 on Windows 10.0.19041 (2004).

@hez2010 Does this issue occur when not using Windoes Terminal?

**Comment by hez2010** [comment]
@xtqqczze Yes
Additional information: my language and region is set to ja-jp.

**Comment by iSazonov** [comment]
> And my PSReadLine is 2.1.0-beta2

Do you see the issue without PSReadline?

**Comment by hez2010** [comment]
@iSazonov Yes, the issue still exists

**Comment by iSazonov** [comment]
Perhaps the same as https://github.com/PowerShell/PowerShell/issues/12485#issuecomment-620365761
/cc @Dhowett

**Comment by DHowett** [comment]
We’ll need a backtrace or a repro outside of Terminal to be sure. A repro outside of terminal would require setting the buffer size to be the same as the window size (no scrollback history)

**Comment by plain-dev** [comment]
It should be the problem of setting the **Avit** theme in the module **oh-my-posh**. The problem disappears after changing other themes.

**Comment by hez2010** [comment]
I've hit asset failure while debugging pwsh:
![image](https://user-images.githubusercontent.com/14960345/105272738-ea7a2580-5bd4-11eb-96b7-1e158e46a7a6.png)

Failed for `str.Length < offset` cannot be fullfilled:
![image](https://user-images.githubusercontent.com/14960345/105272822-15647980-5bd5-11eb-80cf-2986c8fc53a2.png)

**Comment by iSazonov** [comment]
@hez2010 I suggest to look previous callsites in the debug, maybe GenerateLinesWithoutWordWrap().

**Comment by hez2010** [comment]
@iSazonov In GenerateLinesWithoutWordWrap:

![image](https://user-images.githubusercontent.com/14960345/105286034-849b9700-5bf0-11eb-80a5-b0b95652490e.png)

![image](https://user-images.githubusercontent.com/14960345/105286056-92511c80-5bf0-11eb-8a52-07db700f1413.png)

**Comment by iSazonov** [comment]
@hez2010 Do you think I can debug by means of screenshots? 😄 If you already run debugger you could review step by step 2-3 method levels and find a root of the issue.

**Comment by iSazonov** [comment]
We split a line to fit in a window width and if on last iteration we did get zero length tail we did next iteration but we should stop.
Proposed fix https://github.com/iSazonov/PowerShell/commit/6a9bf1009f2c1f55c1f5f9273706c49ada5361fa
I added some cleanups to make the code more reliable.

If anyone wants, they can add tests and pull PR.

**Comment by hez2010** [comment]
I can confirm the commit iSazonov@6a9bf10 fixed the issue.

**Comment by kasini3000** [comment]
interesting. 
In win terminal, I cannot reproduce the problem.
In pwsh.exe, I reproduced the problem.
PowerShell 7.2.0-preview.4

**Comment by iSazonov** [comment]
@kasini3000 Please check with v7.2.0-preview.5
