### ISSUE TITLE
Feature Request: More functional and parallel processing functionallity

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#13558]
## Summary of the new feature/enhancement

I currently have this block of assignments within my script:
```
$a = Get-Foo | ConvertTo-Json
$b = Get-Bar
$c = Get-BarFoo
$d = Get-FooBar
$e = Get-FooFoo
$f = Get-BarBar
$g = Get-FooUsing -Parameter $a
Do-SomethingThatChangesGlobalState
```
where none of the lines depend on the former ones. Currently there is no good way to tell powershell to do all these pipes in parallel and just store the result in the variable.

## Proposed technical implementation details (optional)

I think about something like:
```
#pureFunctions
$a = Get-Foo | ConvertTo-Json
$b = Get-Bar
$c = Get-BarFoo
$d = Get-FooBar
$e = Get-FooFoo
$f = Get-BarBar
$g = Get-FooUsing -Parameter $a
barrier
Do-SomethingThatChangesGlobalState
barrier
```
Where `#pureFunctions` tells powershell that the script contains only pure functions and that it is allowed to swap lines as long as lines containing one of the variables as parameter is executed after it is defined.
E.g. $g is always executed after $a, but no other guarantee on the execution order needs to be provided and powershell should automatically parallelize the pipelines.
For commandlets and functions that do have side effects a `barrier`-keyword is required, so that they can be used. Optionally also Monads (like in e.g. Haskell) could be implemented to "warp" these.

Ideally, the `#pureFunctions` declaration should not only work for scripts, but also for scriptblocks, so that a functional entity could easily be integrated into modules and sequential scripts.

Please let me know what you think.

**Comment by iSazonov** [comment]
In any case you need to sync and it makes us think that Jobs is the best alternative.

**Comment by agowa338** [comment]
Using jobs just doesn't improve readability of the code. Maybe I'm just doing something wrong, so here is an example:
![image](https://user-images.githubusercontent.com/2544867/92243123-3b58de00-eec1-11ea-937b-75872b824122.png)

The lines look like this:
```
[System.Management.Automation.Job[]]$xxInventory = Start-ThreadJob -ArgumentList ("$PSScriptRoot/file.yaml") {param([Parameter(Mandatory)][ValidateNotNullOrEmpty()][String]$PSPath);$a = Get-Content -Path $PSPath -Raw | ConvertFrom-Yaml; @{"getContent" = $a} }
$xxInventory += Start-ThreadJob -ArgumentList ($xxToken,$xxAPIUrl) -ScriptBlock {param([Parameter(Mandatory)][ValidateNotNullOrEmpty()][String]$xxToken, [Parameter(Mandatory)][ValidateNotNullOrEmpty][String]$xxAPIUrl); $null = Connect-xxAPI -Token $xxToken -APIurl $xxAPIUrl; $a = Get-xxObjectListOfTypeA; @{"xxInventoryObjectListOfTypeA" = $a} }
$xxInventory += Start-ThreadJob -ArgumentList ($xxToken,$xxAPIUrl) -ScriptBlock {param([Parameter(Mandatory)][ValidateNotNullOrEmpty()][String]$xxToken, [Parameter(Mandatory)][ValidateNotNullOrEmpty][String]$xxAPIUrl); $null = Connect-xxAPI -Token $xxToken -APIurl $xxAPIUrl; $a = Get-xxObjectListOfTypeB; @{"xxInventoryObjectListOfTypeB= $a} }
$xxInventory += Start-ThreadJob -ArgumentList ($xxToken,$xxAPIUrl) -ScriptBlock {param([Parameter(Mandatory)][ValidateNotNullOrEmpty()][String]$xxToken, [Parameter(Mandatory)][ValidateNotNullOrEmpty][String]$xxAPIUrl); $null = Connect-xxAPI -Token $xxToken -APIurl $xxAPIUrl; $a = Get-xxObjectListOfTypeC; @{"xxInventoryObjectListOfTypeC" = $a} }

Wait-Job -Job $xxInventory

$joinedDictInventory = $xxInventory.Output | ForEach-Object -Begin {[Hashtable]$aa = @{}} -Process {foreach($element in ($_.GetEnumerator())) {$aa.Add($element.Key,$element.Value)}} -End {$aa}
```

**Comment by vexx32** [comment]
I would... suggest writing it with less duplication:
```ps1
$yamlJob = {
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]
        $PSPath
    )
    $a = Get-Content -Path $PSPath -Raw | ConvertFrom-Yaml
    @{"getContent" = $a } 
}

$apiJob = {    
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]
        $xxToken, 
        
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty]
        [String]
        $xxAPIUrl,

        [Parameter(Mandatory)]
        [scriptblock]
        $ApiAction
    )
    $null = Connect-xxAPI -Token $xxToken -APIurl $xxAPIUrl
    & $ApiAction
}

$xxInventory = @(
    Start-ThreadJob -ScriptBlock $yamlJob -ArgumentList "$PSScriptRoot/file.yaml"
    Start-ThreadJob -ScriptBlock $apiJob -ArgumentList $xxToken, $xxAPIUrl, {
        @{"xxInventoryObjectListOfTypeA" = Get-xxObjectListOfTypeA }
    }
    Start-ThreadJob -ScriptBlock $apiJob -ArgumentList $xxToken, $xxAPIUrl, {
        @{"xxInventoryObjectListOfTypeB" = Get-xxObjectListOfTypeB }
    }
    Start-ThreadJob -ScriptBlock $apiJob -ArgumentList $xxToken, $xxAPIUrl, {
        @{"xxInventoryObjectListOfTypeC" = Get-xxObjectListOfTypeC }
    }
)

Wait-Job -Job $xxInventory

$joinedDictInventory = $xxInventory.Output | ForEach-Object -Begin {[Hashtable]$aa = @{}} -Process {
    foreach($element in ($_.Keys)) {
        $aa.Add($element,$_[$element])
    }
} -End {$aa}
```

**Comment by agowa338** [comment]
@vexx32 Thanks for your help, even though your solution looks better, sadly it doesn't work in my case. It leads to a powershell engine crash with either `tcache_thread_shutdown(): unaligned tcache chunk detected` or `malloc(): unaligned tcache chunk detected`

**Comment by vexx32** [comment]
Ah, I suppose I should have expected that, nice catch! Yeah, scriptblocks don't behave well at all between runspaces. I think somewhere there's an issue asking for them to be automatically serialized and re-created in the target process/runspace to fix the runspace affinity issue, but at present the string conversion is the way to go. 🙂

**Comment by Bartolomeus-649** [comment]
Why not start by introducing the ability to declare a function/script-block/cmdLet as _pure_. That would then open up for powershell to optimize the execution in any way it sees fit.

A function could even be automatically classified as _pure_ if it could  be determined that it has no side effects ( like only using other pure functions, only refer to the defined by-value-parameters of the function and so on)

The optimal solution would of course be if PowerShell enforced and allowed only "pure stuff" in a function declared as _pure_.

With this in place, stuff declared as _pure_ could be executed in parallel, async execution could be used when IO is involved, and so on....

**Comment by SeeminglyScience** [comment]
> Why not start by introducing the ability to declare a function/script-block/cmdLet as _pure_. That would then open up for powershell to optimize the execution in any way it sees fit.

It's an interesting idea, though a pretty significant work item. Semantic checks would need to ensure that no state is changed, which for PowerShell would mean essentially calling no outside code, not using variables (aside from locals, and even then it would need to block dot sourcing), not inadvertently triggering events, etc.

The compiler would need to change how it handles some things like locals, they'd either need to be actual memory locations like `Expression.Variable` or restricted to `MutableTuple` items.

> A function could even be automatically classified as _pure_ if it could be determined that it has no side effects ( like only using other pure functions, only refer to the defined by-value-parameters of the function and so on)

The difficulty there is that many things in PowerShell are determined not just a runtime, but at runtime of that expression. In order for the engine to automatically mark an item as pure, it would need to resolve it's command invocations recursively. This would be especially problematic with `CommandInvocationIntrincis.PreCommandLookupAction` (and similar) registrations.

You would pretty much only be able to automatically mark commands that just had constants and binary expressions.  Most of which won't actually see any benefit from being parallelized due to the overhead involved in spinning up a thread being greater than the cost of the function.
 
> With this in place, stuff declared as _pure_ could be executed in parallel, async execution could be used when IO is involved, and so on....

Would IO access be considered pure? Would you expect that the handling of the IO be parallelized or are you asking for asynchronous waiting of IO?

**Comment by Bartolomeus-649** [comment]
> > With this in place, stuff declared as _pure_ could be executed in parallel, async execution could be used when IO is involved, and so on....
> 
> Would IO access be considered pure? Would you expect that the handling of the IO be parallelized or are you asking for asynchronous waiting of IO?

It was more based on that you run CPU work in threads and use async for IO. No real thoughts if IO is _pure_ or not.
Perhaps the_pure_ declaration has a few options (like C# attributes), where you op-in for lokal disk file IO to be considered _pure_ (or something like that).

> > Why not start by introducing the ability to declare a function/script-block/cmdLet as _pure_. That would then open up for powershell to optimize the execution in any way it sees fit.
> 
> It's an interesting idea, though a pretty significant work item. Semantic checks would need to ensure that no state is changed, which for PowerShell would mean essentially calling no outside code, not using variables (aside from locals, and even then it would need to block dot sourcing), not inadvertently triggering events, etc.

Well, I guess you would have to start from the bottom up, by marking stuff as _pure_ all the way from `System.Object` and up. Perhaps a joint-venture with the .NET team, the Roslyn team and the C# team to make sure the _pure_ concept get introduced at the correct level. I would guess the Roslyn team are already familiar with the concept... 

> > A function could even be automatically classified as _pure_ if it could be determined that it has no side effects ( like only using other pure functions, only refer to the defined by-value-parameters of the function and so on)
> 
> The difficulty there is that many things in PowerShell are determined not just a runtime, but at runtime of that expression. In order for the engine to automatically mark an item as pure, it would need to resolve it's command invocations recursively. This would be especially problematic with `CommandInvocationIntrincis.PreCommandLookupAction` (and similar) registrations.

I would start with the simple approach by classifying stuff that can be determined for sure, and then perhaps other things can be checked at runtime, and if we are running in a _pure_ scope and try to write to anything outside that scope, then throw an exception.

**Comment by SeeminglyScience** [comment]
> It was more based on that you run CPU work in threads and use async for IO. No real thoughts if IO is _pure_ or not.
> Perhaps the _pure_ declaration has a few options (like C# attributes), where you op-in for lokal disk file IO to be considered _pure_ (or something like that).

Something I've always wanted to see come to PowerShell is a version of C#'s `async/await`.  I've thought a lot about it and even did a few small prototypes. Really cool idea, but to be honest it would either be too restrictive, or require too many architectural changes to PowerShell.  And realistically, it's pretty unlikely more than a handful of people would use it.

> Well, I guess you would have to start from the bottom up, by marking stuff as _pure_ all the way from `System.Object` and up. Perhaps a joint-venture with the .NET team, the Roslyn team and the C# team to make sure the _pure_ concept get introduced at the correct level. I would guess the Roslyn team are already familiar with the concept...

You're welcome to bring it up over on dotnet/runtime. They don't really have the same types of problems that PowerShell does though. The majority of their state management isn't really thread based like PowerShell's is.

> I would start with the simple approach by classifying stuff that can be determined for sure, and then perhaps other things can be checked at runtime, and if we are running in a _pure_ scope and try to write to anything outside that scope, then throw an exception.

Honestly that would be one of the biggest work items in PowerShell's history.  Some more concrete examples of existing scripts or modules that would benefit would probably be needed for someone to take on writing an RFC.

**Comment by agowa338** [comment]
> Would IO access be considered pure? Would you expect that the handling of the IO be parallelized or are you asking for asynchronous waiting of IO?

In general, that's a solved problem. As functional programs have less to no guarantees on sequential execution of instructions, doing io in a functional context is different. Therefore a function/instruction that writes to a file will do everything internally, e.g. open the file, write to it and close the file. If two functions write to the same file, there wouldn't be any guarantee of what gets written first (for some languages not even that they are written one after another). A programmer could solve this by simply either passing a handle to that file through both functions basically creating a dependency chain between them or by putting them inside of a sequential execution block. For the surrounding code that block would then be treated as one whole.
For reference I'm going to cite how haskell approached this problem ([haskell wiki](https://wiki.haskell.org/All_About_Monads#Introduction)):
> A monad is a way to structure computations in terms of values and sequences of computations using those values. Monads allow the programmer to build up computations using sequential building blocks, which can themselves be sequences of computations. The monad determines how combined computations form a new computation and frees the programmer from having to code the combination manually each time it is required. (...)
> Other monads exist for building computations that perform I/O, have state, may return multiple results, etc.

And regarding:
> And realistically, it's pretty unlikely more than a handful of people would use it.

Maybe it's just me being more optimistic than about this than you are, but I see value for this for libraries and to simplify code of complex operations as well as reducing the time it takes to debug issues with side effects.

**Comment by SeeminglyScience** [comment]
> Maybe it's just me being more optimistic than about this than you are, but I see value for this for libraries and to simplify code of complex operations as well as reducing the time it takes to debug issues with side effects.

I should clarify that my concern is more about the amount of community adoption rather than whether it would be useful to those who did adopt.

I've been wrong before though, so if you're passionate about it I'd recommend drafting [an RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/RFC0000-RFC-Process.md). I can't really see a way to make these changes without pretty significant rewrites of PowerShell's architecture, so an implementation proposal would be very helpful to move the conversation forward.

**Comment by agowa** [comment]
No Auto close, Feature Request is still not implemented. Wtf?!? Do I need to write a bot that auto replies to keep my Tickets open now?
