### ISSUE TITLE
Code page seems to be broken

### ISSUE THREAD

**Issue by YF1999** [PowerShell/PowerShell#13568]
I wrote a simple cpp code 'program.cpp', encoding in utf8, for only printing a chinese string:
```cpp
#include<iostream>
int main()
{
    std::cout << "哈哈哈哈哈哈" << std::endl;
    return 0;
}
```

But it actually printed a wrong string:
```shell
> g++ .\program.cpp
>  .\a.exe
鍝堝搱鍝堝搱鍝堝搱
```

## cmd & powershell

The current code page of cmd or powerhsell is 936-gbk. But I can use `chcp 65001` to solve this problem:
```shell
>a.exe
鍝堝搱鍝堝搱鍝堝搱

>type program.cpp
#include<iostream>
int main()
{
    std::cout << "鍝堝搱鍝堝搱鍝堝搱" << std::endl;
    return 0;
}
```
```shell
Active code page: 65001

>a.exe
哈哈哈哈哈哈

>type program.cpp
#include<iostream>
int main()
{
    std::cout << "哈哈哈哈哈哈" << std::endl;
    return 0;
}
```

## pwsh

The current code page is 65001-utf8. I cannot get correct chinese strings printed, and `chcp 65001` doesn't work.
```shell
> .\a.exe
鍝堝搱鍝堝搱鍝堝搱
> cat .\program.cpp
#include<iostream>
int main()
{
    std::cout << "哈哈哈哈哈哈" << std::endl;
    return 0;
}
```
```shell
Active code page: 65001
> .\a.exe
鍝堝搱鍝堝搱鍝堝搱
> cat .\program.cpp
#include<iostream>
int main()
{
    std::cout << "哈哈哈哈哈哈" << std::endl;
    return 0;
}
```

## Environment data

zh-cn win10.

```shell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please test with latest PowerShell 7.1 Preview build.

**Comment by YF1999** [comment]
7.1.0-preview6, this problem still exists. It behaves the same as what 7.0.3 behaves.

**Comment by iSazonov** [comment]
How do you change active code page? If you in the same session you should use `[Console]::OutputEncoding = <nnn>`

**Comment by YF1999** [comment]
`[console]::outputencoding = [system.text.encoding]::utf8` works.

Hmmm, I'm confused.

Before changing code page, `$outputencoding` shows the encoding is utf8 and `[console]::outputencoding` shows the encoding is gb2312. What's the differences between `$outputencoding` and `[console]::outputencoding`?
The 'current code page' in properties shows the encoding is utf8, where does it come from?
If input `chcp`, it prints 'Active code page: 936', where does this result come from?

`chcp 65001` doesn't change the `[console]::outputencoding` or `$outputencoding`, but in powershell it surely changes something to make the output to be decoded correctly. Why it fails in pwsh?

**Comment by DHowett** [comment]
(If your application requires a specific codepage to be active, it should set it itself. It is almost always incorrect to rely on the global state of the console, because it will rarely be what you want.)

**Comment by iSazonov** [comment]
@YF1999 You can see https://stackoverflow.com/questions/40098771/changing-powershells-default-output-encoding-to-utf-8 for additional information.

**Comment by YF1999** [comment]
> (If your application requires a specific codepage to be active, it should set it itself. It is almost always incorrect to rely on the global state of the console, because it will rarely be what you want.)

I don't understand.

If pwsh's encoding is not the same as my program, the output from my program can be decoded correctly?

I wrote a c# program to output '哈哈哈哈哈哈', succeeded if `[console]::outputencoding` is gb2312, utf8 and utf7, but if is ascii it prints '??????'. If this c# program will automatically set the codepage itself, why it fails if global codepage is ascii?

There is not this problem for python and node programs, but electron programs only succeed if global codepage is utf8.

**Comment by iSazonov** [comment]
> If this c# program will automatically set the codepage itself, why it fails if global codepage is ascii?

Your program does not set a code page.
https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows

**Comment by lyj-514328** [comment]
The effect of adding chcp in the PowerShell startup parameters is not the same as executing chcp after startup. When chcp is modified within the startup parameters, it affects PowerShell's OutputEncoding and InputEncoding, so your program can work. chcp is a shorthand for the Windows chcp.com program and is not a built-in command of PowerShell.
When starting PowerShell with powershell -NoExit -Command "chcp 65001", the InputEncoding and OutputEncoding will follow the code page change.

**Comment by lyj-514328** [comment]
If not set, PowerShell 7 defaults to UTF-8, while PowerShell 5 defaults to UTF-16LE with a BOM (Byte Order Mark). The Windows default is PowerShell 5.
