### ISSUE TITLE
Enable context menu additions to Windows Store installation

### ISSUE THREAD

**Issue by csvn** [PowerShell/PowerShell#13560]
## Summary of the new feature/enhancement

When installing powershell from `msi`, there is an option to add context menu additions for opening Powershell in a folder (when right clicking). The same is not true for the Windows Store version (Powershell Preview).

![image](https://user-images.githubusercontent.com/8770194/91845836-2af2fa00-ec5a-11ea-84cf-f65c3479ad1f.png)

![image](https://user-images.githubusercontent.com/8770194/91845897-46f69b80-ec5a-11ea-88cc-20e2930f7306.png)

Maybe it would be possible to allow this option via "App Settings > Add-ons & downloadable content"? It would be great if we can get the auto-updating features of the store version, but still having feature parity with the `msi` installation.

## Proposed technical implementation details (optional)

1. Install Powershell Preview from the store
2. (optional) Enable context menu items
3. Right click inside a folder in File Explorer
4. "Open with Powershell" item should be available

**Comment by iSazonov** [comment]
It is dup #10892.

**Comment by csvn** [comment]
Sorry, I searched for a few keywords, but didn't find any similar issue!
