### ISSUE TITLE
Feature Request: *nix Touch command

### ISSUE THREAD

**Issue by m-ghaoui** [PowerShell/PowerShell#13572]
## Summary of the new feature/enhancement

As a user I want to be about to create a new empty file with `touch myfile.js` so that I can quickly create new source files with the command-line. The `touch` command should be familiar to everybody who uses *nix.

## Proposed technical implementation details (optional)

I would replicate the *nix 'touch' command as closely as possible (updating timestamps, etc.) so as not to throw off the *nix veterans.

**Comment by vexx32** [comment]
Related: https://github.com/PowerShell/PowerShell/issues/8621, https://github.com/PowerShell/PowerShell/issues/13054, and https://github.com/PowerShell/PowerShell/issues/11677

This has been requested before; I'd suggest you add your comments to the last issue, which is still open. 🙂
