### ISSUE TITLE
Bug in Setup: Setup 7 (x86, x64) does not write InstallLocation

### ISSUE THREAD

**Issue by jwallenstein** [PowerShell/PowerShell#13573]
Setup 7 
Setup 7 (x86, x64) does not write InstallLocation property value.
Using msi setup installer, this value would be set automatically.

Uninstall Registry Key you can find here:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{05321FDB-BBA2-497D-99C6-C440E184C043}
Key InstallLocation is empty.
InstallLocation key allows to find target installation folder of "PowerShell 7"

Please correct the setting properties to uninstall key

**Comment by heaths** [comment]
That registry key will change with each new version of the package installed and should not be used for detection. Windows Installer registry keys are undocumented and not supported to be used directly.

Instead, we have a registry key specifically for this purpose - we just need to add the location of the root folder:
https://github.com/PowerShell/PowerShell/blob/88e706f3d7a95b0ea665236c990438e0ff158087/assets/Product.wxs#L179-L185

That registry key will remain the same for the major version, so using it for detection will be more reliable.
