### ISSUE TITLE
Status of pwsh on WSL Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#13583]
What is the status of #12626? It was opened four (4) months ago, but locked two (2) months ago.

```
Please support Ubuntu 20.04
#12626 opened on May 11 

PowerShell locked as off topic and limited conversation to collaborators on Jul 2

```

**Comment by kilasuit** [comment]
I spoke with @SteveL-MSFT about this and it is still in progress & I personally hope we will see a release that targets both 7.0.4 & 7.1.0-preview7 soon

**Comment by Liturgist** [comment]
Thanks, @kilasuit. I would like to leave this issue open until it is delivered. Would that be appropriate?

**Comment by kilasuit** [comment]
Considering it's being tracked in the other issue having 2 open issues for the same thing doesn't really make any sense. Though I did suggest to @SteveL-MSFT to reopen the commenting on #12626 & add a quick comment on current status of a Ubuntu 20.04 build as I did expect others to also ask about it.

**Comment by Liturgist** [comment]
I will close this one.

Would you mention the two (2) open issues tracking this?

**Comment by kilasuit** [comment]
By 2 open issues I meant this one & #12626 - where #12626 is already tracking the status of 20.04 support for PowerShell
