### ISSUE TITLE
Add No Profile options to the Tasks List

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#13582]
On Windows we can add a series of different tasks as per the below Screenshots

Outlook
![image](https://user-images.githubusercontent.com/6355225/92308323-b808bc80-ef94-11ea-87d2-84c300c78cda.png)

Teams
![image](https://user-images.githubusercontent.com/6355225/92308328-bf2fca80-ef94-11ea-9791-c04573c57cc5.png)

Firefox
![image](https://user-images.githubusercontent.com/6355225/92308341-d1116d80-ef94-11ea-8d88-3f07fde76fe6.png)

I propose that we add an option to this menu to allow quick right-click run with no profile, like we can do with Run as Administrator

**Comment by iSazonov** [comment]
Currently we use a workaround to add elements to the list by calling a native code on _every_ pwsh run. As result we have an extra startup delay.
Perhaps @heaths knows better way.

**Comment by heaths** [comment]
You would need a native code custom action (do not use managed custom actions - there are workarounds to all the problems, but they come at significant costs to package size) to basically invoke that same code. Custom actions are tricky to get right. The PowerShell team needs to consider whether they want to prioritize this cost to have this happen at setup time as opposed to (or in addition to) runtime. I'd be happy to help if so.

/cc @SteveL-MSFT

**Comment by kilasuit** [comment]
If this is not reasonably feasible then that's just how it is. 

Though I personally think it needs to be a Setup time action not something that's done as a Runtime action as that makes no sense as you would use the menu option as part of pre-runtime, including potentially as part of the first ever run of PowerShell (unlikely but you get what I mean by this)

**Comment by rkeithhill** [comment]
This is pretty trivial to set up in Windows Terminal.  These days, I don't even pin PowerShell to my taskbar anymore.  I pin Windows Terminal instead.
