### ISSUE TITLE
ThrowTerminatingError error not showing if Object is DataTable or PSCustomObject Array

### ISSUE THREAD

**Issue by ili101** [PowerShell/PowerShell#13593]
If the object in the ErrorRecord is a DataTable or an Array of PSCustomObject and they have at last 2 rows the error will not be displayed. 
## Steps to reproduce
Create a ps1 file with the following code and run it:
```powershell
function Test-Error {
    [CmdletBinding()]
    param ()
    $DataTable = [Data.DataTable]::new()
    $null = $DataTable.Columns.Add('A')
    $null = $DataTable.Rows.Add(1)
    $null = $DataTable.Rows.Add(2)

    $PSCmdlet.ThrowTerminatingError(
        [Management.Automation.ErrorRecord]::new(
            [ArgumentException]::new('Foo'),
            'Bar',
            [Management.Automation.ErrorCategory]::InvalidType,
            $DataTable
        )
    )
}
Test-Error
Pause
```

## Expected behavior
Error shows on PowerShell 5.1
![image](https://user-images.githubusercontent.com/6960531/92399056-567e5480-f132-11ea-8e07-ce69fd6a27df.png)
Error shown if DataTable have less then 2 lines
![image](https://user-images.githubusercontent.com/6960531/92399861-a873aa00-f133-11ea-9ba9-8c03117312fd.png)

## Actual behavior
On PowerShell 7.0/7.1
![image](https://user-images.githubusercontent.com/6960531/92400022-df49c000-f133-11ea-97a0-784fb9820f41.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
/cc @SteveL-MSFT looks like a bug in concise view.

@ili101 in the meantime if this causes you difficulty, you can set `$ErrorView = 'NormalView'` in your profile to revert back to the PS 5.1 default error display view
