### ISSUE TITLE
Enable logging of command line with PowerShell module logging (4103)

### ISSUE THREAD

**Issue by gwsales** [PowerShell/PowerShell#13596]
## Summary of the new feature/enhancement
Enable logging of command issued at the terminal like legacy PowerShell:800 event codes that log both CommandLine and Payload. 

Current module logging for 4103 event codes for both PowerShell 5 and 7 are missing key data points needed for analysis. 

Currently PowerShell v5 still logs both 800 and 4103 event codes when Module Logging is turned on, in v7 this no longer happens so we'll need better logging with existing 4103 event codes. 

## Proposed technical implementation details (optional)

Add param1 from "Windows PowerShell" event_id 800 into the operational 4103 event logs.

**Comment by gwsales** [comment]
Example of why this is needed:
https://twitter.com/GrantWSales/status/1291743466523889666

**Comment by SteveL-MSFT** [comment]
Event id 800 is pipeline execution logging.  That code is still present, need to figure out why it's not logging or how to enable.

**Comment by iSazonov** [comment]
I see 4103 (0x1007) in PowerShell.Core.Instrumentation.man and EventResource.cs but I don't see 800 (0x320) there.

**Comment by PaulHigin** [comment]
It looks like pipeline execution event id, `800`, was replaced with `4103` at some point.  It logs the same information but the details label is slightly different (was 'Context Information:', now is 'Context:').  I assume this was done in the PowerShell 5.x timeframe, since both PowerShell Core and Windows PowerShell 5.1 `4103` event logs have the same format.

Module logging (event Id 4103) does work with PowerShell Core (v6,7), but it does not currently respect 'Module Logging' group policy setting for Windows PowerShell.  PowerShell Core group policy has its own template and reg key:
`Software\Policies\Microsoft\PowerShellCore\ModuleLogging`.

But you can turn on module logging manually:

```powershell
Get-Module | foreach { $_.LogPipelineExecutionDetails }
Get-Module | foreach { $_.LogPipelineExecutionDetails = $true }
Get-Module | foreach { $_.LogPipelineExecutionDetails }
```

Or, I believe you can set it in the PowerShell Core configuration file.

**Comment by gwsales** [comment]
I agree with @PaulHigin that it looks like 4103 was supposed to replace 800, however PowerShell v5 sill logs both with module logging enabled. The big difference between 800 and 4103 is the logging of scriptblock / commandline that went along with the Payload. 

If you'd like a log sample please look at this repo: https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES
https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Other/emotet/exec_emotet_ps_800_get-item.evtx

If time is spent trying to fix these issues, the most useful thing would be to add the comamndline / scriptblock value from 800 to the "User Data" or a new field in the 4103 events. This would likely solve the issue for the long term and future releases of PowerShell.

**Comment by gwsales** [comment]
Created a few samples. 

Legacy 400 (No corresponding 4XXX event code that logs startup with context info):
```xml
<root>
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
      <Provider Name="PowerShell" />
      <EventID Qualifiers="0">400</EventID>
      <Version>0</Version>
      <Level>4</Level>
      <Task>4</Task>
      <Opcode>0</Opcode>
      <Keywords>0x80000000000000</Keywords>
      <TimeCreated SystemTime="2020-09-10T16:49:20.5920770Z" />
      <EventRecordID>19443</EventRecordID>
      <Correlation />
      <Execution ProcessID="0" ThreadID="0" />
      <Channel>Windows PowerShell</Channel>
      <Computer>DESKTOP-RIPCLIP</Computer>
      <Security />
    </System>
    <EventData>
      <Data>Available</Data>
      <Data>None</Data>
      <Data>	NewEngineState=Available
	PreviousEngineState=None

	SequenceNumber=13

	HostName=ConsoleHost
	HostVersion=5.1.19041.1
	HostId=44fd2659-dac3-4be9-a08d-08279a98f78b
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
	EngineVersion=5.1.19041.1
	RunspaceId=9e719284-e101-4523-88f7-e36ca5e9d152
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=</Data>
    </EventData>
  </Event>
</root>
```
Legacy 800 (Similar to 4103 but contains command line / script block. Matching Payload and ContextInfo):
```xml
<root>
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
      <Provider Name="PowerShell" />
      <EventID Qualifiers="0">800</EventID>
      <Version>0</Version>
      <Level>4</Level>
      <Task>8</Task>
      <Opcode>0</Opcode>
      <Keywords>0x80000000000000</Keywords>
      <TimeCreated SystemTime="2020-09-10T22:29:34.5326155Z" />
      <EventRecordID>22812</EventRecordID>
      <Correlation />
      <Execution ProcessID="0" ThreadID="0" />
      <Channel>Windows PowerShell</Channel>
      <Computer>DESKTOP-RIPCLIP</Computer>
      <Security />
    </System>
    <EventData>
      <Data>i`cm {e`ch`o ("Obfu"+"s"+"`c"+"ted")}</Data>
      <Data>	DetailSequence=1
	DetailTotal=1

	SequenceNumber=6749

	UserId=DESKTOP-RIPCLIP\Clippy
	HostName=ConsoleHost
	HostVersion=5.1.19041.1
	HostId=7d5cb8a8-0a62-4f52-ba67-09f94d24e1b7
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
	EngineVersion=5.1.19041.1
	RunspaceId=9e719284-e101-4523-88f7-e36ca5e9d152
	PipelineId=278
	ScriptName=
	CommandLine=i`cm {e`ch`o ("Obfu"+"s"+"`c"+"ted")}</Data>
      <Data>CommandInvocation(Invoke-Command): "Invoke-Command"
ParameterBinding(Invoke-Command): name="ScriptBlock"; value="e`ch`o ("Obfu"+"s"+"`c"+"ted")"
</Data>
    </EventData>
  </Event>
</root>
```
Current 4103 (Similar to 800, matching Payload and ContextInfo with 800's param2 and param3):
```xml
<root>
  <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
      <Provider Name="Microsoft-Windows-PowerShell" Guid="{a0c1853b-5c40-4b15-8766-3cf1c58f985a}" />
      <EventID>4103</EventID>
      <Version>1</Version>
      <Level>4</Level>
      <Task>106</Task>
      <Opcode>20</Opcode>
      <Keywords>0x0</Keywords>
      <TimeCreated SystemTime="2020-09-10T22:29:34.5334620Z" />
      <EventRecordID>21964</EventRecordID>
      <Correlation ActivityID="{1fe2bf64-877d-0003-e93d-e31f7d87d601}" />
      <Execution ProcessID="7996" ThreadID="5596" />
      <Channel>Microsoft-Windows-PowerShell/Operational</Channel>
      <Computer>DESKTOP-RIPCLIP</Computer>
      <Security UserID="S-1-5-21-2895499743-3664716236-3399808827-1001" />
    </System>
    <EventData>
      <Data Name="ContextInfo">        Severity = Informational
        Host Name = ConsoleHost
        Host Version = 5.1.19041.1
        Host ID = 7d5cb8a8-0a62-4f52-ba67-09f94d24e1b7
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        Engine Version = 5.1.19041.1
        Runspace ID = 9e719284-e101-4523-88f7-e36ca5e9d152
        Pipeline ID = 278
        Command Name = Invoke-Command
        Command Type = Cmdlet
        Script Name = 
        Command Path = 
        Sequence Number = 6750
        User = DESKTOP-RIPCLIP\Clippy
        Connected User = 
        Shell ID = Microsoft.PowerShell
</Data>
      <Data Name="UserData">
      </Data>
      <Data Name="Payload">CommandInvocation(Invoke-Command): "Invoke-Command"
ParameterBinding(Invoke-Command): name="ScriptBlock"; value="e`ch`o ("Obfu"+"s"+"`c"+"ted")"
</Data>
    </EventData>
  </Event>
</root>
```

**Comment by PaulHigin** [comment]
Ok, I now see the 800 event data ... I was looking in the wrong place for it before.  I presume this was removed from PowerShell Core because it was thought that 4103 provided the same information.  But that doesn't seem to be the case, and we should look at the differences.

**Comment by gwsales** [comment]
Does adding a milestone mean this could be pulled in for that release?

**Comment by iSazonov** [comment]
@gwsales Yes, this _could_.

**Comment by gwsales** [comment]
Is there any way to add comments here when this is considered and skipped or accepted? There doesn't seem to be any progress on this issue since September and I want to make sure this doesn't get overlooked.

**Comment by gwsales** [comment]
Can this be reopened?

**Comment by gwsales** [comment]
How do we get this issue to be addressed and reopened.
