### ISSUE TITLE
Warnings emitted for UTF-7 cause test failues on Debian 11

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13599]
Release validation tests have failed for Debian 11 due to UTF-7 obsoletion.

Error message:

```
Expected exactly 'Encoding 'UTF-7' is obsolete, please use UTF-8.', but got $null.
```

Stack trace:

```
at <ScriptBlock>, /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/engine/Basic/Encoding.Tests.ps1: line 125
125:             $observed | Should -BeExactly $expectedString
```

**Comment by iSazonov** [comment]
Do you see the issue on all linux-s? I guess it is .Net Core issue.

**Comment by rjmholt** [comment]
> Do you see the issue on all linux-s

Only Debian 11

**Comment by iSazonov** [comment]
Perhaps our workaround with `encoding.CodePage == 65000` does not work.

**Comment by rjmholt** [comment]
That workaround is the one .NET suggested: https://github.com/dotnet/runtime/issues/41459#issuecomment-682106551

**Comment by iSazonov** [comment]
I mean it may be a bug in .Net 5.0 because of Debian 11 specific.

**Comment by adityapatwardhan** [comment]
Seems like a non-blocker.
