### ISSUE TITLE
Add a -DateKind parameter to ConvertFrom-Json to control how System.DateTime / System.DateTimeOffset values are constructed

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13598]
Follow-up from #13592:

## Summary of the new feature/enhancement

Introduce a new `-DateKind` parameter as an enumeration value as follows:

```
ConvertFrom-Json -DateKind { Local | Utc | Unspecified | Offset | None }
```

The goal is to parse timestamps in the input JSON as `[datetime]` /  `[datetimeoffset]` instances of the given kind - irrespective of the specific formatting of those timestamps.

* `Local` / `Utc` / `Unspecified` should create `[datetime]` instances with the given `.Kind` value.

  * A timestamp without time-zone information (UTC offset or `Z` suffix) should be assumed to be `Local` (a pitfall is that on calling `.ToLocalTime()` on something that was parsed as `Unspecified`, it is assumed to be a UTC value - `[datetime]::new(<unspecified-datetime>.Ticks, 'Local')` is the solution).
  * If `Unspecified` is requested, any UTC offset / `Z` suffix should be ignored.
  
* `Offset` should create a `[datetimeoffset]` instance instead, which preserves the exact UTC offset as specified or implied in the input.

  * A timestamp without time-zone information (UTC offset or `Z` suffix) should be assumed to be a caller-local timestamp.

* `None` should not create a date a `[datetime]` /  `[datetimeoffset]` at all and instead pass the _original string values_ through.

Note that on _serializing_, with `ConvertTo-Json`, both `Utc` and `Local` `[datetime]` instances serialize with the appropriate UTC offset (e.g., `"2020-09-08T16:24:21.577822-04:00"`), whereas `Unspecified` serializes without an offset (e.g., "2020-09-08T16:24:21.577822").

**Motivation**:

Since v6, the Json.NET-based `ConvertTo-Json` automatically deserializes _strings_ that contain an `"o"`-formatted (roundtrip format) date/time string (e.g., `"2020-09-07T09:44:13.769Z"`) or a _prefix_ of it that at least includes everything up to the _seconds_ part (e.g., `"2020-09-07T09:44:13:`) as `[datetime]` instances.

However, the resulting `[datetime]` instances' `.Kind` property (`Local`, `Utc`, or `Unspecified`) is determined by the specifics of the string value as follows:

* `Unspecified`, if there is no time-zone information in the input string.
* `Utc`, if the time-zone information is a trailing `Z`
* `Local`, if the time-zone information is given as a trailing UTC _offset_ (e.g., `+02:00`), in which case the offset is properly converted to the caller-local equivalent.

Note that the new `System.Text.Json` API that is being considered as the future underpinning of the `*-Json` cmdlets - see #11198 - exhibits the same behavior.

There are two problems with this behavior:

* A `Utc` instance _gives no indication that it is a UTC timestamp_ in its default output formatting (applies both to PowerShell's formatting and `.ToString()` - verify with  `[datetime]::UtcNow` and `[datetime]::UtcNow.ToString()`).

* Specific UTC offsets in the input are lost, because they are translated to a _caller-local_ `Local` instance.

**Comment by SteveL-MSFT** [comment]
Queued for review within Cmdlets WG

**Comment by iSazonov** [comment]
Important https://learn.microsoft.com/en-US/dotnet/standard/datetime/system-text-json-support

**Comment by sba923** [comment]
Losing the offsets that were in the input data (re: second problem listed above) might be a no-go for me in some scenarios.

**Comment by mklement0** [comment]
@sba923, just to be clear: The proposed `-DateKind Offset` would preserve the offsets, due to using [`[datetimeoffset]`](https://docs.microsoft.com/en-US/dotnet/api/System.DateTimeOffset); `-DateKind None` would return the timestamp strings as-is.

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-cmdlets discussed this and we would like a better understanding of the real world scenarios where this behavior would be used.

**Comment by jborean93** [comment]
Simple

```powershell
ConvertFrom-Json -InputObject '{"Date": "2022-11-02T12:01:44.5801388-04:00"}' | ConvertTo-Json
```

When you use ConvertFrom-Json on this field it gives you a Local Kind DateTime object which has a correct value but you no longer know the original value is `-04:00`. It would only work if your local time zone was also `-04:00`.

If you were able to do `-DateKind Offset` you should be able to get a `DateTimeOffset` value back where the time zone offset is preserved allowing you to round trip the data back but also be able to know what the input value's time zone was. Same with `-DateKind None` as you would just get the raw string back.

**Comment by sba923** [comment]
Please note that whatever improvements are made to `ConvertFrom-Json` must ripple over to other cmdlets that perform the same conversions, such as `Invoke-RestMethod`.

**Comment by iRon7** [comment]
I did some investigation in the newtonsoft json parser and it looks to me that although it is possible use a setting as `DateParseHandling = DateParseHandling.None` for serialization, there no easy way do something like that for deserializing. Besides, the `JValue` is already converted to a `DateTime` object (based on the current localization) which probably means that you have to retrieve the raw string from the parent (which might be either a `JArray` or `JObject` possibly along with other values).
Therefore, I think that would be more feasible to have two additional parameters as:

### `-DateFormat`
Which won't change the `DateTime` type to a `String` but instead add a custom format to the `DateTime` values as in: `Get-Date $JObject.Value -Format $DateFormat` so that it will correctly type cast to the expected string and also roundtrip. It might default to [ISO 8601, which appears to be the default format for NewtonSoft](https://www.newtonsoft.com/json/help/html/datesinjson.htm)

### `-AsLocalTime`
As apposed to `-AsUTC` which would be the default.

For a prototype see: [Powershell 7.2: ConvertFrom-Json - Date Handling](https://stackoverflow.com/a/74352656/1701026),

**Comment by mklement0** [comment]
@iRon7, to recap the key benefit of the `-DateKind` proposal, as also summarized in [@jborean93's comment](https://github.com/PowerShell/PowerShell/issues/13598#issuecomment-1301068480): it is the ability to _avoid loss of information_, by:

* either: suppressing conversion to a date type altogether (`-DateKind None`), leaving interpretation of the original string value up to the caller. 
* or: converting to `[datetimeoffset]`, which preserves the original UTC offset (`-DateKind Offset`)

The secondary benefit, if loss of offset information isn't a concern, is the ability to choose whether the resulting `[datetime]` instances should be expressed in _local_ time or in _UTC_, or even as _unspecified_ in that regard (`-DateKind Local` / `-DateKind Utc`, `-DateKind Unspecified`).

---

By contrast:

* `-AsLocalTime` wouldn't provide the key benefit, and only part of the secondary benefit.

* `-DateFormat` amounts to an unrelated proposal: the ability to control the format of string representations that are used on serialization / recognized on deserialization as timestamp values.
  * I personally don't see the need for such a feature, but if you feel strongly about it, I encourage you to create a separate issue.

Also with respect to discussing potential implementations, we should keep in mind that a move from Newtonsoft's JSON parser to the new, .NET-native parser may be ahead (not sure what the plans are; https://github.com/PowerShell/PowerShell/pull/11198 is now closed).

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets discussed this and would accept adding a new parameter to allow user to opt-in.

**Comment by JJatSTASH** [comment]
Just bumping this, a flag to control date parsing behavior of ConvertFrom-Json would help my own scripting quite a bit; without it, I'm considering downgrading versions

**Comment by jborean93** [comment]
I've opened https://github.com/PowerShell/PowerShell/pull/20925 which adds the `-DateKind` parameter. It implements all the types proposed here except for `Unspecified` which I personally think is just too confusing and not worth the effort.

**Comment by iRon7** [comment]
> It implements all the types proposed here except

Just a thought: maybe also add a `String` option that would than leave the datetime entry as a string. That way, it is up to the scripter to evaluate the datetime and possibly make different decisions for different entries.

> Just bumping this

As somebody is apparently revising the `ConvertFrom-Json` cmdlet, I would like to mention issue #19928 which I am somewhat concerned about. As (afaik) it hasn't had any involvement from the PowerShell team. Maybe somebody from the PowerShell team can review this issue before releasing a new `ConvertFrom-Json` version.
