### ISSUE TITLE
Add a -DisplayHint parameter to Measure-Object for disk-space representations that are easy to grasp

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13601]
Follow-up from https://github.com/PowerShell/PowerShell/issues/13423#issuecomment-681153364:

## Summary of the new feature/enhancement

To easily grasp the size of a directory, it would be helpful if instead of:

```powershell
PS> Get-ChildItem -File |  Measure-Object -Sum  Length
...
Sum: 19241959
...
```

it would be nice to get an auto-scaled value that is expressed as a multiple of KB, MB, GB:

```powershell
PS> Get-ChildItem -File |  Measure-Object -Sum  Length
...
Sum: 18.35MB
....
```

Additionally, such scaling should be available _on demand_.
Therefore:

Introduce a new `-DisplayHint` parameter - analogous to `Get-Date`'s - as an enumeration value that instructs the formatting system to use specific formatting, as follows:

```powershell
... | Measure-Object -DisplayHint { None | KB | MB | GB | AutoBytes }
```

* The parameter would affect the output formatting of the following properties of `GenericMeasureInfo`  / `GenericObjectMeasureInfo` output type (it wouldn't apply to the `TextMeasureInfo` output type selected with any one of the `-Line`, `-Word` or `-Character` parameters):

  * `Average`, `Sum`, `Maximum`, `Minimum`

* `None` would be the default, except if the first input object is of type (derived from) `System.IO.FileSystemInfo` and the
`-Property` value is `Length`, in which case `AutoBytes` is implied.

Meaning of the enumeration values:

* `None` yields the current behavior.

* `KB`, `MB`, `GB` divide the numbers by the implied binary multiplier and represent the result with `2` decimal places, including the multiplier suffix:

  * E.g., with `KB`, value `1234` would be represented as `1.21KB`, the result of `'{0:N2}' -f (1234 / 1kb)`.

* `AutoBytes` auto-select the highest among the binary `KB`, `MB`, `GB` multipliers that makes the scaled value greater than  or equal to `1`, with values below the `KB` threshold getting suffixed with `B`.

  * E.g., `1100200` would be represented as `1.05MB`, the result of `'{0:N2}' -f (1100200 / 1mb)`, because MB is the highest multiplier that still yields a scaled value greater than `1`.

## Proposed technical implementation details (optional)

* Make `Measure-Object` attach an _instance_ `DisplayHint` ETS member to its `GenericMeasureInfo`  / `GenericObjectMeasureInfo` (as needed).

* Add formatting definitions for `GenericMeasureInfo` and `GenericObjectMeasureInfo` that acts on the `DisplayHint` instance member.

**Comment by iSazonov** [comment]
Such things must be entirely in Formatting System, otherwise we are doomed to add such things to every cmdlet. The complete solution is still proposed as PSMore.

**Comment by mklement0** [comment]
@iSazonov, it's in the nature of the `Measure-Object` cmdlet that this information _cannot_ be entirely in the formatting system:

* You cannot generally  know _what_ is being measured, and therefore you cannot know whether it makes sense to express the measurements in multiples of bytes.

* In the one cases listed above where it _is_ known (`[System.IO.FileSystemInfo]` with `-Property Length`) - are there others? - you won't have to use the parameter at all (`-DisplayHint AutoBytes` will be implied).

**Comment by iSazonov** [comment]
> it's in the nature of the Measure-Object cmdlet that this information cannot be entirely in the formatting system

It is true for _current_ Formatting System. 
This encourages us to add hint parameters and properties to a variety of cmdlets and types. This is a dead end road. Using the PSMore idea, we would get a very flexible formatting system for developers and it would be easier for users to indicate what they want to see in the output - local or UTC, digits or Gb - it is unlimited list of formatting options.

**Comment by mklement0** [comment]
@iSazonov, the PSMore (#7857) idea is clearly languishing, and there's no telling if and when it will ever be implemented - though I would definitely welcome a better solution.

Not having looked at PSMore myself: please explain how it would handle this situation: 

* A cmdlet that accepts arbitrary input objects whose *semantics* it cannot know anything about (except  for perhaps a few well-known built-in types).

* That cmdlet's output formatting should vary its formatting based on the unknown semantics of the input objects.

**Comment by iSazonov** [comment]
Input objects know nothing about user preferences. I may want the output in terabytes, you in gigabytes. We either use a default or explicitly specify a preference. It makes no sense to put a preference in the cmdlet itself, since there are an infinite number of options.
In terms of the existing formatting system, we should use `Format-Table -View <CustomView>`. The problem is that it is too time consuming and has many limitations.
As far as PSMore, this could overcome some of these limitations. One key PSMOre feature is that users can modify defaults on the fly and attach formatting to objects.

**Comment by mklement0** [comment]
> We either use a default or explicitly specify a preference.

The proposal suggests a  - what I consider _sensible - default_ (auto-selection of an appropriate  multiplier, depending on the size of the number for `FileSystemInfo` input with property `Length`), supplemented with the ability to _override_ with  a fixed multiplier - or none at all - via `-DisplayHint`.

> It makes no sense to put a preference in the cmdlet itself

It absolutely makes sense, because in the case of `FileSystemInfo` and `Length`  we know that _bytes_ are being  measured and presenting the output in those terms is the most useful to the human observer.

> we should use `Format-Table -View <CustomView>`. The problem is that it is too time consuming and has many limitations.

Indeed: Which do you think is preferable?

`Get-ChildItem -File |  Measure-Object -Sum  Length` (with `-DisplayHint AutoBytes` implied)
vs.
`Get-ChildItem -File |  Measure-Object -Sum  Length | Format-Table -View AutoBytes`

---

As stated, `Measure-Object` is an _unusual_ cmdlet, because of its open-ended input - that, and only that, is the reason why the `-DisplayHint` solution is appropriate.

> As far as PSMore, this could overcome some of these limitations. 

Please spell such a PSMore-based solution out explicitly for the case at hand.
