### ISSUE TITLE
After pwsh+ssh to a windows pc, it changes from pwsh to cmd. How to use remote pwsh on the remote pc?

### ISSUE THREAD

**Issue by physlikenan** [PowerShell/PowerShell#13608]
PC-a (pwsh) ssh to PC-b (pwsh installed), after connected, it defaults to cmd on PC-b.
How to default to pwsh after ssh connected.

**Comment by he852100** [comment]
https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7

**Comment by jborean93** [comment]
This isn't related to PowerShell, look at the wiki for Win32-OpenSSH on how to configure the default shell https://github.com/PowerShell/Win32-OpenSSH/wiki/DefaultShell.
