### ISSUE TITLE
Failed to launch interactive ssh session over Enter-PSSession

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/PowerShell#13617]
Enter-PSSession is doing something wrong with IO redirection.

Here is my setup,
I have 3 machines (2 Ubuntu VMs, 1 Windows VM).
From one of the Ubuntu VM, do Enter-PSSession to Windows VM and then do SSH to another Ubuntu VM.
UbuntuVM_1 ----(Enter-PSSession)----> windows m/c -------(SSH)----->UbuntuVM_2.

SSH connection get's stuck. I tried to print the ssh client logs to console but it fails.

I tried to use SSH instead of Enter-PSSession. It works flawless.
UbuntuVM_1 ----(SSH)----> windows m/c -------(SSH)----->UbuntuVM_2.

Here are the screenshots for both the scenarios,

After Enter-PSSession, tried to ssh with Win32OpensSH Client, Windows GIT SSH Client. 
With win32OpenSSH client, control doesn't return and it's stuck.
With Windows GIT SSH client, control returns but the SSH connection is closed i.e., no interactive SSH session.
![image](https://user-images.githubusercontent.com/23668037/92844026-410b6380-f39a-11ea-8db4-1aadb9513597.png)

With SSH (everywhere) it works fine.
![image](https://user-images.githubusercontent.com/23668037/92841576-5df26780-f397-11ea-9002-05b407abbcba.png)

**Comment by iSazonov** [comment]
@SteveL-MSFT @PaulHigin Maybe MSFT team creates a Design document to define which remote scenarios should be/are supported?

**Comment by PaulHigin** [comment]
This is not supported.  You cannot run an SSH client from within a PowerShell SSH remoting session because the StdIn/StdOut pipes are redirected to pass the remoting protocol messages.

**Comment by bagajjal** [comment]
@PaulHigin - Not sure why it is not doable when nested interactive SSH sessions are possible.

When Enter-PSSession is using SSH as a transport, I expect the traffic should flow through a named pipe (between powershell, ssh client on the same machine) which is not STDIN/STDOUT pipes. If not then changing this will solve the problem?

**Comment by jborean93** [comment]
@PaulHigin can correct me if I'm wrong here but as I understand it the issue with PSRemoting, what `Enter-PSSession` uses, is it uses an SSH subsystem that exchange bytes back and forth between the client and server. This subsystem is started based on the command specified in your `sshd_config`

> Subsystem powershell c:/progra~1/powershell/7/pwsh.exe -sshs -NoLogo

Basically when sshd gets a request to connect to the `powershell` subsystem it will start a new process based on that config entry and use the stdio pipes for that ssh connection as the new process' SSH pipes. That means your ssh session's stdout is the same pipe that is attached to `pwsh.exe -sshd -NoLogo`. From there any data sent from the PowerShell client is sent over the stdin pipe to pwsh and any data received is from the pwsh stdout pipe. This data is encapsulated in a simple XML message like

```xml
<Data Stream='Default' PSGuid='00000000-0000-0000-0000-000000000000'>PSRP fragment(s)</Data>
```

Any messages exchanged between the client and the server are all in these XML messages, that's unlike a normal ssh session where you've simply reading and writing to the stdout/stdin like a normal process. So if you tried to nest an SSH connection that had interactive input then PowerShell would need a way to read and write to those new pipes in a way that didn't affect the PSRP data exchanges.
