### ISSUE TITLE
Microsoft Store not updating to latest version of PowerShell Preview

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#13615]
It's possible I'm missing something.

How do you update your existing Microsoft Store PowerShell Preview version? I thought that at least the app would have an update button, or it was done automatically.

Current Version installed from the Microsoft Store: PowerShell Preview 7.1.0-preview.6

![MSPSPreview_01_2020-09-10_15-02-27](https://user-images.githubusercontent.com/19892435/92787578-39869300-f377-11ea-960e-4c309133c912.jpg)

## Expected behavior
Windows 10 to update PowerShell Preview in Microsoft Store.
```none

```

## Actual behavior
No Update was performed.
```none

```

## Environment data

```none
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-preview.6
PSEdition                      Core
GitCommitId                    7.1.0-preview.6
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```

**Comment by Gnbrkm41** [comment]
The update is currently available on MS Store - I got my P7 update from MS Store just fine. It looks like it went through not so long ago so perhaps you could check again?

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

So, what's the waiting period for updating the PowerShell Preview version? Is it about 3 days after its release?
:)

Thanks

**Comment by kilasuit** [comment]
@MaximoTrinidad as you have the answer, from this comment https://github.com/PowerShell/PowerShell/issues/7730#issuecomment-689732223 I think this can be closed now
