### ISSUE TITLE
Feature Request 'Sudo Alternative'

### ISSUE THREAD

**Issue by cryptic-ai** [PowerShell/PowerShell#13621]
## Summary of the new feature/enhancement
As a user I want to be able to run something like `sudo winget install 7zip` so that I do not have to open a separate powershell prompt as admin. Idea insipired by the `sudo` command on unix.

See this repository for the idea: https://github.com/gerardog/gsudo
## Proposed technical implementation details (optional)

Reference https://github.com/gerardog/gsudo

**Comment by iSazonov** [comment]
Dup #11343

**Comment by cryptic-ai** [comment]
Closing as Duplicate of #11343
