### ISSUE TITLE
Repo website links to a mostly broken page

### ISSUE THREAD

**Issue by svick** [PowerShell/PowerShell#13635]
The repo website link https://microsoft.com/PowerShell for some reason redirects to https://docs.microsoft.com/en-us/previous-versions/msdn10/mt173057(v=msdn.10). That seems to be some kind of horrible, outdated, badly formatted page with no working links:

![](https://user-images.githubusercontent.com/287848/93212699-3a4a6b00-f763-11ea-8ff3-1920eaad32e6.png)
![](https://user-images.githubusercontent.com/287848/93212718-40404c00-f763-11ea-82dd-0f9b53d690ff.png)

Can this be fixed?

**Comment by iSazonov** [comment]
Fixed.
