### ISSUE TITLE
Show-Command enhancement parameters order or group

### ISSUE THREAD

**Issue by jgranduel** [PowerShell/PowerShell#13630]
## Summary of the new feature/enhancement

Say we have a function ` function fn([string]$z, [string] $a){ Write-Host "z = $z, a = $a" }`, could there be a mean to show parameter z at the top with `Show-Command`? So basically, keep order, or change order with [parameter(Position=0)]`?
I thought this was possible a [few years ago ](https://stackoverflow.com/questions/34919540/show-command-cmdlet-layout).

Thanks

**Comment by iSazonov** [comment]
@jgranduel The cmdlet (as all graphical cmdlets in the repo) is frozen and all new work will be in  https://github.com/PowerShell/GraphicalTools repository.

**Comment by ThomasNieto** [comment]
@iSazonov `Show-Command` doesn't exist in that repo. Why are these commands frozen?

**Comment by vexx32** [comment]
They're not compatible with .NET Core and only run on Windows, so they're not being developed further on their original platform as the focus of pwsh is cross-platform. The GraphicalTools module is presently one of the best options to make it work while being cross platform.

**Comment by jgranduel** [comment]
Thanks for your responses. Sorry as I knew it, but I forgot as I'm running pwsh-7 with GraphicalTools! The command was back in 2019 ([Out-gridview returns blog post](https://devblogs.microsoft.com/powershell/out-gridview-returns/)). It seems there are moving yet to another library [GraphicalTools/issue #101](https://github.com/PowerShell/GraphicalTools/issues/101).
