### ISSUE TITLE
Building Binary Module Doc Clarification .NET SDK Version

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#13632]
# Steps to reproduce

The docs for creating a binary module/cmdlet at https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/command-line-simple-example.md have states that

>  file that specifies that the project requires the 2.0.0 version of the .NET Core SDK

I'm unclear as to whether the 2.0.0 version is actually required or if that's just a minimum version. A quick test seems like it's just the latter but honestly I'm just starting to play around with it all so I don't fully understand the landscape.

If it's the former what does that mean when .NET 2.0.0 is EOL?

I'm also curious what happens when .NET 5.0 is released? How does that affect building binary modules that are meant to be compatible with pwsh 5 and newer?

**Comment by SeeminglyScience** [comment]
> I'm unclear as to whether the 2.0.0 version is actually required or if that's just a minimum version. A quick test seems like it's just the latter but honestly I'm just starting to play around with it all so I don't fully understand the landscape.

Just the minimum. SDK version doesn't matter as much anymore as *most* versions you'll see installed these days will work just fine (unless you're using newer C# language features, then you'll need a newer version).  The doc could use some updating for sure.

> I'm also curious what happens when .NET 5.0 is released? How does that affect building binary modules that are meant to be compatible with pwsh 5 and newer?

It doesn't really.  For example, I'm currently building netstandard2.0 libs with the `5.0.100-rc.2` version of the SDK without issue (for C# 9 features).

**Comment by jborean93** [comment]
Thanks for the clarification here (and further questions on the Discord channel).

**Comment by iSazonov** [comment]
You could update the doc to make it more clear.
