### ISSUE TITLE
Powershell generating files in /tmp but does not delete them

### ISSUE THREAD

**Issue by BlacksWise** [PowerShell/PowerShell#13648]
The same error as mentioned in #11599 still persists, which leads to an immense amount of files within the /tmp directory.

pwsh --version
PowerShell 7.0.3

OS:
5.4.0-42-generic #46~18.04.1-Ubuntu

## Steps to reproduce

Just execute any script on linux system

## Expected behavior

Temp files get deleted after script execution

## Actual behavior

Temp files do not get deleted and can cause the system to be unbootable until /tmp gets purged in Single User Mode

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by iSazonov** [comment]
It was fixed in #12187
