### ISSUE TITLE
Regression: Registering a scheduled task no longer works with ScheduledTaskTrigger

### ISSUE THREAD

**Issue by allister-grange** [PowerShell/PowerShell#13645]
## Steps to reproduce

```powershell
$Sta = New-ScheduledTaskAction -Execute "Cmd"
$Stt = New-ScheduledTaskTrigger -Once -At 3am
Register-ScheduledTask Task01 -Action $Sta -Trigger $Stt
```

## Expected behavior

That a scheduled task is set up successfully. This was working in Powershell 5.1 previous to our Powershell 7 migration. 

## Actual behavior

```none
Register-ScheduledTask: Cannot process argument transformation on parameter 'Trigger'. Cannot convert value "Microsoft.PowerShell.ScheduledJob.ScheduledJobTrigger" to type "Microsoft.Management.Infrastructure.CimInstance[]". Error: "Cannot convert the "Microsoft.PowerShell.ScheduledJob.ScheduledJobTrigger" value of type "Deserialized.Microsoft.PowerShell.ScheduledJob.ScheduledJobTrigger" to type "Microsoft.Management.Infrastructure.CimInstance"."
```

## Environment data
`

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by scriptingstudio** [comment]
It works for me (windows 10)

```
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.


C:\Users\adm_motienko\Documents\Documents\sysadmin
PS#> $Sta = New-ScheduledTaskAction -Execute "Cmd"

[635,44ms] C:\Users\adm_motienko\Documents\Documents\sysadmin
PS#> $Stt = New-ScheduledTaskTrigger -Once -At 3am

[84,99ms] C:\Users\adm_motienko\Documents\Documents\sysadmin
PS#> Register-ScheduledTask Task01 -Action $Sta -Trigger $Stt

TaskPath                                       TaskName                          State
--------                                       --------                          -----
\                                              Task01                            Ready
```

**Comment by vexx32** [comment]
Deserialization... ah. @allister-grange you are working with an older version of the ScheduledTasks module. I believe updates for this module are shipped via Windows Update; what version of Windows are you running this on?

The pwsh team probably can't do a great deal, but you might possibly try explicitly importing the scheduled tasks module with `Import-Module -SkipEditionCheck` and see if the version you have happens to work OK directly in pwsh.

**Comment by allister-grange** [comment]
Apologies for the delay in my reply. 

We are using Windows Server 2012 R2 instances, they are receiving windows patching. As you can see above in my ```$PSVersionTable``` Windows is at 6.3.9600. 

I believe that we are using the Task Scheduler 2.0 as the Register-ScheduledTask function was working previously on PowerShell 5.1. So that leads me to think that our Task Scheduler is up to date. 

Sadly, the ```Import-Module -SkipEditionCheck``` workaround doesn't help. 

Is there anything else I can give a shot?

**Comment by mariodeleon** [comment]
Hello, All
I confirm that issue still persists.

I installed "PowerShell-7.0.3-win-x64.msi" in my "Microsoft Windows Server 2012 R2 Standard" Version: 6.3.9600 N/A Build 9600.

---------------------------------------------------------------------

$psversiontable
Name                           Value
'----                           '-----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

-------------------------------------------------------------------------------------

PS > $Sta = New-ScheduledTaskAction -Execute "Cmd"
PS > $Stt = New-ScheduledTaskTrigger -Once -At 3am
PS > Register-ScheduledTask Task01 -Action $Sta -Trigger $Stt

OUTPUT:
Register-ScheduledTask: Cannot process argument transformation on parameter 'Trigger'. Cannot convert value "Microsoft.PowerShell.ScheduledJob.ScheduledJobTrigger" to type "Microsoft.Management.Infrastructure.CimInstance[]". Error: "Cannot convert the "Microsoft.PowerShell.ScheduledJob.ScheduledJobTrigger" value of type "Deserialized.Microsoft.PowerShell.ScheduledJob.ScheduledJobTrigger" to type "Microsoft.Management.Infrastructure.CimInstance"."

**Comment by vexx32** [comment]
I'm not sure there is / will be a patch for Server 2012 that will make the module work in PS7. Those modules are bound entirely to the respective Windows team that handles the patching for the OS functionality as far as I'm aware, so unless they're planning to backport whatever patches they've done to Server 2012 there mightn't be much you can do.

@SteveL-MSFT probably has more insight where that's concerned, though.

**Comment by drchrisking** [comment]
Same issue here, running PoSH v5.1 and server 2016.

**Comment by dave-007** [comment]
Same issue.
