### ISSUE TITLE
New-SelfSignedCertificate command appears to produce SSLv3 certificates instead of TLS 1.x

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#13655]
## Steps to reproduce

```powershell
New-SelfSignedCertificate -Subject blah
```

## Expected behavior

PowerShell generates a TLS 1.3 certificate.

## Actual behavior

PowerShell appears to generate an SSL v3 certificate.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This may depend on your SSL settings in the system/registry and in process.

Try setting `[Net.ServicePointManager]::SecurityProcol = 'Tls12'` and try again perhaps?

**Comment by pcgeek86** [comment]
I just tried setting it to `Tls13` and it still shows a "v3" certificate.

![image](https://user-images.githubusercontent.com/466713/93633814-cac7bc00-f9ac-11ea-8e37-ab6db4975970.png)

**Comment by vexx32** [comment]
No idea there, I'm afraid. Perhaps the Windows documentation somewhere has some information on what that Version refers to. Generally speaking though I'd be surprised if that refers to SSLv3, which hasn't been in common use in quite a long time. My guess would be it has something to do with the version of the hashing algorithms used to generate the keys.

**Comment by pcgeek86** [comment]
Yeah, that's possible. Next question is: how do I verify the certificate type (SSLv3 vs. TLS 1.1, 1.2, 1.3)?

**Comment by jborean93** [comment]
A certificate doesn't state the protocol it is for, that's up to the service/client to manage when creating the TLS pipeline. The Certificate just contains encryption and hashing information to facilitate the functions of TLS. The version is just the version of the X509 structure, V3 doesn't mean SSL v3. The version tells the reader of the cert what fields can be contained and how it is structured.

**Comment by pcgeek86** [comment]
Ah good point. My ignorance is showing. :)

**Comment by jborean93** [comment]
Everyone is ignorant about X509 and certificates, they are too complex for their own good :)

**Comment by vexx32** [comment]
Can confirm, had no dang clue what all that stuff means 😂
