### ISSUE TITLE
Scheduled powershell task ends with '0xC000013A' error code

### ISSUE THREAD

**Issue by Fooughhy** [PowerShell/PowerShell#13659]
I am trying to schedule TNUC to run at login. I do not believe there is an option to do so, and would simply like to try this out. I think I've previously put a shortcut in the Startup folder, but don't see why this shouldn't work. I am also doing this as I want the window to stay open. Therefore I want to run it through powershell, with the '-NoExit' parameter.

## Steps to reproduce

(Download TinyNvidiaUpdateChecker)
Create a new scheduled task. I have set it to use the highest privilege and to configure for "Windows 10". The trigger is "At login" and the actual task is to start a program.

Use "pwsh.exe" as the program. Powershell 7.0.3 is on my path, so this will open that (I have checked manually). You can point to it directly, it doesn't matter.
Then add the `-NoExit` and `-File "path-to-TinyNvidiaUpdateChecker"` arguments as the optional arguments. Click "Ok" and complete the task.

## Expected behavior

TinyNvidiaUpdateChecker is run (in a console window) and the console expects an input when the script is done (As a result of the `NoExit` tag).

## Actual behavior

When this task is run, the following window appears. This seems like a weird error. [Powershell Window][1]

In Task Scheduler, the task has the error 0x40 if I use the full path for powershell, or 0xC000013A if I just use "pwsh.exe" as the application.

What am I doing wrong?

[1]: https://i.stack.imgur.com/s06wN.png

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
The `-File` parameter is for PowerShell scripts, so it's trying to parse the executable you're pointing it to as a plain text PowerShell script (or at least `pwsh` is, `powershell` is just failing immediately because the extension isn't `ps1`).  Try `-Command` instead.

**Comment by Fooughhy** [comment]
Thank you for the fast and short answer! Sorry that I didn't see that solution before. That seems to have fixed the issue.
