### ISSUE TITLE
Add a -Raw switch to Select-Xml to return the matching System.Xml.XmlNodes directly, without a wrapper

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13669]
## Summary of the new feature/enhancement

Typically, a user is only looking for the `[System.Xml.XmlNode]` instances that the XPath query matched rather than the _wrapper_ type instances that `[Microsoft.PowerShell.Commands.SelectXmlInfo]` provide metadata and require access to their `.Node` property to access the wrapped `[System.Xml.XmlNode]` instance, which is both non-obvious and inconvenient.

(Compare this to `Get-Content`'s behavior, which doesn't _wrap_ the lines it returns, but merely _decorates_ them with ETS instance properties.)

**A `-Raw` switch could be implemented that returns the matching `[System.Xml.XmlNode]` instances directly, following the model of `Select-String`'s `-Raw` switch**:

Thus:

```powershell
# Wishful thinking: -Raw returns System.Xml.XmlNode instances directly.
PS> Select-Xml -Raw -Content '<foo><bar>none</bar></foo>' -XPath '//foo'

bar
---
none
```

would be the equivalent of:

```powershell
Select-Xml -Content '<foo><bar>none</bar></foo>' -XPath '//foo' | Select-Object -ExpandProperty Node
```

**Comment by vexx32** [comment]
`-Raw` makes me think it'll return some string value back instead. Is there perhaps a more clear name we could use here?

**Comment by mklement0** [comment]
I never liked `-Raw`, and proposed `-Bare` as the name for a switch that generally omits output-object _decorations_ or _wrappers_ - remember #7855?

As such, `-Bare` would have been appropriate for `Select-String` too, not because it returns _strings_ as such, but because the _unwrapped_ objects are being returned, which just so happen to be strings.

(For `Get-Content`, the current `-Raw` switch should never have been named that, but my proposal to have it renamed was rejected - see #7715.)

It looks like we're stuck with `-Raw` as the name for the not-string-specific pattern described above, so I think it is the right name here.
