### ISSUE TITLE
unable to use install-module

### ISSUE THREAD

**Issue by sudlo** [PowerShell/PowerShell#13661]
Hi, 

for some reasons i am not able to use Install-module / find-module. when i try running the command i get the following error message

C:\WINDOWS\system32> Find-Module -Name PowerShellGet | Install-Module
Find-Module : The term 'Find-Module' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Find-Module -Name PowerShellGet | Install-Module
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Find-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

when i check C:\Program Files\WindowsPowerShell

the scripts folder is empty there is no patch management folder 

my main goal is to reinstall powershell 5.1 i have a windows 10 machine

**Comment by vexx32** [comment]
As far as I know, there's no way to reinstall PS 5.1 without reinstalling Windows.

This repository is only for pwsh (versions 6+); PowerShell 5.1 is not being updated or maintained any longer. You might find better help for this specific issue in community channels. 🙂

**Comment by sudlo** [comment]
@vexx32  i have installed powershell 7 core.
