### ISSUE TITLE
Calling `::new()` on a struct only works if there are no defined constructors

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#13674]
PowerShell doesn't have the `default` keyword, so the only way to create a zeroed instance of a struct is `new()` (which likely just gets translated to `default` in `SLE.Expression` trees) and `[Activator]::CreateInstance([type])`/`New-Object`.  The best way would be `new()` but it is currently inconsistent.  If the struct has defined any constructors, the binder will throw.

## Steps to reproduce

```powershell
# This struct has no defined constructors
[RuntimeMethodHandle]::new()

# This type several
[IntPtr]::new()
```

## Expected behavior

```powershell
# [RuntimeMethodHandle]::new()
Value
-----
    0

# [IntPtr]::new()
0
```

## Actual behavior

```powershell
# [RuntimeMethodHandle]::new()
Value
-----
    0

# [IntPtr]::new()
MethodException: Cannot find an overload for "new" and the argument count: "0".
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.7
PSEdition                      Core
GitCommitId                    7.1.0-preview.7
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Fix

This:

https://github.com/PowerShell/PowerShell/blob/3effa204103460c996a8612aa70718fdf924047d/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L7620-L7624

Needs to be:

```csharp
if (_callInfo.ArgumentCount == 0 && instanceType.IsValueType)
{
    // No ctors, just call the default ctor
    return new DynamicMetaObject(Expression.New(instanceType).Cast(this.ReturnType), restrictions).WriteToDebugLog(this);
}
```

**Comment by dkaszews** [comment]
If the fix has been known for 2 years, why no PR? Are there any breaking changes we need to discuss? Or can I just create the PR myself and get the glory like with `'1' | Test-Json`?

**Comment by SeeminglyScience** [comment]
> Are there any breaking changes we need to discuss? Or can I just create the PR myself and get the glory like with `'1' | Test-Json`?

Good question! I can't think of any but I'll open it up for triage with the engine WG to discuss.

**Comment by dkaszews** [comment]
Why is this closed? It has been waiting on the WG engine. It is ridiculous how maintainers just bot everything closed instead of actually look at the issues in questions.
