### ISSUE TITLE
Installing a module generates a duplicate Documents\PowerShell folder stored in OneDrive but only on one Windows computer

### ISSUE THREAD

**Issue by arcanecode** [PowerShell/PowerShell#13681]
I'm reaching out here as a last resort. I have bingoogleducked my way across the web and found nothing.

I have two Windows computers I use for PowerShell 7 development. The first I call the "beast", it's a ThinkPad P51 with 64 gig of ram, 8 core Xeon processor, lots of disk space. Second machine is a lightweight 13 inch Dell, with Core-i7 and 16 gig of ram.

While the machines are different in hardware, they are almost identical with software. Same Windows 10, same OneDrive, same VSCode, same PowerShell 7.0.3, heck even the same version of Minecraft. I use the same Microsoft login on both machines and OneDrive does a nice job of keeping everything in sync.

Almost.

On the beast, everything works fine. I install a new module, it goes into my Documents\PowerShell\Modules folder, as it should.

On my Dell though, when I install a new module, it complains it had an error writing to the modules folder and has created a new Documents\PowerShell-Dell folder.

The next time I exit PowerShell and come back in, no modules are installed, so I have to reinstall them. Get error, it now has a Documents\PowerShell-Dell-2 folder. Exit, return, install module, PowerShell-Dell-3 gets created. Over and over. Right now I'm on PowerShell-Dell-54. When I first found the issue, I was up to PowerShell-Dell-187. Every so often I go in and delete them all.

The one folder it DOESN'T have on the Dell is Documents\PowerShell. If I remove all my dupes, then manually create the Documents\PowerShell folder, it renames it as PowerShell-Dell and OneDrive throws the error "You now have two copies of a folder. We couldn't merge the changes in "PowerShell" so we created another copy of it. Click to browse to both folders".

This repeats, for example it will say it couldn't merge PowerShell-Dell-53 and created another copy.

I thought, well hey I'll solve the problem by just creating an alternate modules folder outside of OneDrive on this Dell, and point PSModulePath to it. 

But no.

Any attempts to do so and PowerShell Core immediately shoves my Documents\PowerShell back to the beginning of the path, gives me a big middle finger, and from what I read in some other issues not even Satya Nadella could change this behavior.

Every time I open PowerShell I have to reinstall all the modules I need for that session. This is especially irritating with Pester, because if I forget it winds up using the pre-installed Pester 3 instead of the current Pester 5 and all my test scripts start crashing left and right.

I'm at my wits end. I've not found anything, and am tired of having to reinstall modules and clean up my documents folder. I'm not sure if this is a PowerShell Core issue, a OneDrive issue, or something in between. But I'm hoping some here has experienced this and can point me in the right direction.

I should also mention I have two MacBooks and several Linux machines I do PowerShell development on and this issue doesn't occur on any of them, only on this Windows Dell machine. Which is especially irritating as the Dell is the machine I like to use when I do presentations at user groups and the like.

Version info:

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

In addtion:

VSCode is on version 1.49.1, although this has been going on for several versions, at least since June.
OneDrive version is 2020, Build 20.143.0716.0003 (although this has been going on for months, well before the August OneDrive release)

Help! Any assistance would be greatly appreciated.

**Comment by iSazonov** [comment]
For reference https://github.com/PowerShell/PowerShell/issues/9246#issuecomment-638318324
We need to review all operations on surrogate reparse points.
