### ISSUE TITLE
Feature Request: System.Management.Automation.Runspaces.Command.IsEndOfStatement should have a public setter

### ISSUE THREAD

**Issue by leonardder** [PowerShell/PowerShell#13685]
## Summary of the new feature/enhancement
I'm building a PowerShell hosting library for several PowerShell based workflows. Scripts are run by populating an object with the necessary values:

```c#
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

namespace Helper.PS.Model
{
    public sealed class ScriptExecutionDetails
    {
        public Command Command { get; set; }
        public Collection<Command> PreScriptCommands { get; set; } = new Collection<Command>();
        public Collection<Command> PostScriptCommands { get; set; } = new Collection<Command>();
        public Boolean UseStrictMode { get; set; } = true;
        ...

        public ScriptExecutionDetails()
        {
        }

        public ScriptExecutionDetails(Command command)
        {
            this.Command = command ?? throw new ArgumentNullException(nameof(command));
        }

        public ScriptExecutionDetails(String command, Boolean isScript, IDictionary<String, Object> parameters = null)
            : this()
        {
            if (String.IsNullOrEmpty(command))
            {
                throw new ArgumentException($"'{nameof(command)}' cannot be null or empty", nameof(command));
            }
            this.Command = new Command(command, isScript: isScript);
            if (parameters != null)
            {
                foreach (KeyValuePair<String, Object> param in parameters)
                {
                    this.Command.Parameters.Add(param.Key, param.Value);
                }
            }
        }
    }
}

```

This object is then processed when populating the PowerShell object.

One issue I'm facing is that I can't control which commands are piped and which ones are batched, because I can't set the IsEndOfStatement property on the Command objects.
https://github.com/PowerShell/PowerShell/blob/10237bdeb37718595d475bd0014b005a035b34df/src/System.Management.Automation/engine/hostifaces/Command.cs#L187

## Proposed technical implementation details (optional)

Remove the internal keyword

**Comment by vexx32** [comment]
You need to use `.AddStatement()` to end the current pipeline and start a new series of commands. 🙂

**Comment by leonardder** [comment]
Yes, that's what I do now. But I'd like to be able to do this when constructing the ScriptExecutionDetails object and adding commands to it. The PowerShell object is hidden to the internals of the library.

Therefore, while I know there is an alternative, It would help to know why this setter was marked internal in the first place.

**Comment by SeeminglyScience** [comment]
Yeah it'd be nice to be able to control this on the object, even if through a constructor argument.

> Therefore, while I know there is an alternative, It would help to know why this setter was marked internal in the first place.

My guess is thread safety reasons, since most of the `PSCommand` API's change state behind a lock.  I would have guessed `MergeMyResults` would have the same problem, but that is probably easier to check once at the start of an invocation and cache.

/cc @daxian-dbw @PaulHigin, they might know the history.
