### ISSUE TITLE
How to properly resolve dependencies that have runtime identifiers?

### ISSUE THREAD

**Issue by panicoenlaxbox** [PowerShell/PowerShell#13695]
Hello,

I have written a powershell binary module in C#. If I don't add any nuget package reference, everything works fine in PowerShell and PowerShell Core. On the other side If I add some package (like AutoMapper, RestSharp o anything else) I have to add this in .csproj for copying the dependencies in \bin folder and avoid the error *"Test-SampleCmdlet: Could not load file or assembly 'XXXX, Version=10.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'. The system cannot find the file specified."*
```
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```

However, with Microsoft.Data.SqlClient does not work, because it's depends on runtime identifiers (not like AutoMapper or RestSharp that depend only on target framework). Finally, I end with a Microsoft.System.Data.dll in \bin folder that it's not correct (it's a library only with code plenty of PlatformNotSupported exceptions, more info here https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions#11-why-do-i-get-a-platformnotsupported-exception-when-my-application-hits-a-sqlclient-method)

My .csproj is like this:

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard20</TargetFramework>
		<AssemblyName>example</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="10.0.0" />
                <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.1" />
		<PackageReference Include="PowerShellStandard.Library" Version="5.1.0">
			<PrivateAssets>All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="RestSharp" Version="106.11.5" />
	</ItemGroup>

</Project>
```

And a simple example will be this:

```
            // With <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> the following two lines will work
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Foo, Bar>());
            var client = new RestClient();

            // However, this line only works if you copy the right assembly in output folder
            using (var cnn = new Microsoft.Data.SqlClient.SqlConnection())
            {
            }
```

I receive the error when I call to the cmdlet, not when I import the module (Import-Module).

If I manually copy in \bin folder the right assembly of Microsoft.Data.SqlClient (extracting content from .nupkg file and choosing the right one by runtime identifier) does work, but I think PowerShell should do this for me, it's the host.

So, my final thought is that I can develop a powershell binary module if I don't add nuget packages that had been deployed with runtime identifiers... and this is a very big problem :(

I have proved this https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/writing-portable-modules?view=powershell-7#dependency-on-native-libraries but I think I am missing something, because I have tried several folder names and structure, but PowerShell Core does not seem to look for in this folders (I am using Process Monitor to see it https://docs.microsoft.com/en-us/sysinternals/downloads/procmon). I think that my issue is related with this other https://github.com/PowerShell/PowerShell/issues/8861 but I have spent a lot of time in last days and I don't find a solution.

Thank you so much.

**Comment by iSazonov** [comment]
It is dup #2083.
