### ISSUE TITLE
System.Management.Automation.Host not accessible from second class file?

### ISSUE THREAD

**Issue by johnmccrae** [PowerShell/PowerShell#13703]
I am building a PowerShell module in c#. I have 2 class files. The first class looks a bit like this:

```
using System.Management.Automation;
using System.Management.Automation.Host;
.
.
.
namespace foo
{
    class bar
    {
        protected override void ProcessRecord()
        {
            Host.UI.Write("Foo");
        }
    }
}
```

That works fine. Now in the second class file I get this:

```
using System.Management.Automation;
using System.Management.Automation.Host;
.
.
.
namespace foo 
{
    class noob
    {
        public static void DoSomething()
        {
            Host.UI <= The Name 'Host' does not exist in the current context
        }
    }
}
```

What am I doing wrong?

**Comment by vexx32** [comment]
I think the `Host` property you're using in the first file comes from `Cmdlet` or `PSCmdlet`; you're overriding `ProcessRecord`, so I'm guessing you're inheriting one of those in that first file.

**Comment by johnmccrae** [comment]
Crap... that was it. Thank you
