### ISSUE TITLE
Java processes forked from Powershell will die when CTRL+C is used or when Powershell terminal window is closed. 

### ISSUE THREAD

**Issue by nddipiazza** [PowerShell/PowerShell#13701]
## Steps to reproduce

Open a powershell terminal in Linux. You can use any gnome-terminal or terminator, doesn't seem to matter what Terminal program you are using.

Run a program that runs a Jetty service in the background. Example: Lucidworks Fusion 4.2.6

```powershell
/home/ndipiazza/.fusion/4.2.6/bin/fusion start
```

Now close the terminal.

Notice the Java binaries that were opened will killed when the powershell terminal dies. 

Repeating these same steps using a normal terminal will not have this problem. It is only when you start the program from a powershell terminal that this happens.

video capture here: https://www.youtube.com/watch?v=MniUDVmiJGo&feature=youtu.be

This also does not happen on Windows.

## Expected behavior

Should keep running after terminal is closed.

## Actual behavior

Forked java processes die along with powershell. Seem to also die intermittently when you use "CTRL+C".
## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by jhoneill** [comment]
This is standard behaviour - running the command from the prompt launches it as a child process. To allow it continue after the shell terminates use start <<cmdline>>

**Comment by nddipiazza** [comment]
@jhoneill Tried that. Same behavior.

**Comment by iSazonov** [comment]
Interesting, on Windows we have a check whether the application is a console application. Should we do such check on Unix?

/cc @SteveL-MSFT

**Comment by mklement0** [comment]
`Start-Process` is only effective on Windows, where the process is launched in a new window.

On Unix platforms you can use the standard `nohup` utility to disassociate a process from the calling terminal, but note that you won't see its output, which is only collected in file `nohup.out` in the current dir.

In general, I _would_ expect directly launched processes to die along with their calling shell, which applies to PowerShell as well as to POSIX-like shells such as `bash`.

I know nothing about Jetty services and `fusion`, but are you saying that PowerShell overeagerly also terminates processes that _aren't_ its child processes, unlike, say, `bash`?
How are these inappropriately terminated created processes created?

**Comment by nddipiazza** [comment]
OK after shaking the tree a bit, I realize the Fusion code is using a library https://github.com/zeroturnaround/zt-exec to fork java processes. 

This library has "Process destroyers". I bet that one of these "process destroyers" are somehow confused by the combination of Linux + PowerShell and causing the processes to be destroyed when powershell terminal it originated from is destroyed. 

I will do some more digging and close this issue if it turns out this "process destroyer" is doing this.

**Comment by vmiheer** [comment]
This is related: https://stackoverflow.com/questions/64707869/what-is-the-equivalent-of-nohup-in-linux-powershell
I was asking explicitly how to do `Start-Job` which is equivalent to `nohup`.

**Comment by mklement0** [comment]
@vmiheer, I've posted an answer to your SO question, but the same information can be found in #12090.
