### ISSUE TITLE
Installer for v7.1.0-rc.1 doesn't work

### ISSUE THREAD

**Issue by danfloyd111** [PowerShell/PowerShell#13719]
## Steps to reproduce

```
Try to install v7.1.0-rc.1 Release of PowerShell (x64 msi package)
```

## Expected behavior

```
New version get installed
```

## Actual behavior

```
The installer process gets stuck in background and after a long time (like half an hour) crashes with an error.
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by anmenaga** [comment]
There is probably something special about environment. I've just tried on 2 machines and it installs fine there.
Some additional info that might help:
1) how do you run msi - by clicking in Explorer or from other `pwsh`?
2) can you include a screenshot of the moment when installer gets stuck?
3) do you change those selection options in setup dialog or go with defaults?

Thank you.

**Comment by iSazonov** [comment]
Can you run msiexec with logging enabled and attach the log?

**Comment by danfloyd111** [comment]
> 
> 
> There is probably something special about environment. I've just tried on 2 machines and it installs fine there.
> Some additional info that might help:
> 
>     1. how do you run msi - by clicking in Explorer or from other `pwsh`?
> 
>     2. can you include a screenshot of the moment when installer gets stuck?
> 
>     3. do you change those selection options in setup dialog or go with defaults?
> 
> 
> Thank you.

1. I tried both ways with the same result
2. I'll try but the installer starts and the little Windows Installer windows pops up, after that nothing happens, I just can see a background Installer process in the task manager.
3. I'm not able to reach any setup dialog.



> 
> 
> Can you run msiexec with logging enabled and attach the log?

Sure, I'll attach a screenshot and the resulting log:
![image](https://user-images.githubusercontent.com/12446689/94791202-96ee8c80-03d7-11eb-9f5d-4a2b9d99f190.png)

```
=== Verbose logging started: 01/10/2020  11:16:10  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (7C:04) [11:16:10:811]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (7C:04) [11:16:10:811]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (7C:48) [11:16:10:825]: Resetting cached policy values
MSI (c) (7C:48) [11:16:10:825]: Machine policy value 'Debug' is 0
MSI (c) (7C:48) [11:16:10:825]: ******* RunEngine:
           ******* Product: .\PowerShell-7.1.0-preview.6-win-x64.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (7C:48) [11:16:10:826]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (7C:48) [11:16:10:834]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 3: 2 
MSI (c) (7C:48) [11:16:10:834]: Note: 1: 1324 2: . 3: 1 
MSI (c) (7C:48) [11:16:10:834]: MainEngineThread is returning 2
=== Verbose logging stopped: 01/10/2020  11:16:10 ===
```

**Comment by anmenaga** [comment]
@danfloyd111 Maybe the `msi` file is corrupted somehow. If you have another PS installed on the machine, can you please try calculating hash for the downloaded `msi` file and compare it with what is specified on the [PS Releases page / SHA256 Hashes of the release artifacts](https://github.com/PowerShell/PowerShell/releases) (that match what I'm getting for freshly downloaded packages in example below ).
```
PS C:\Temp> Get-FileHash -Path .\PowerShell-7.1.0-rc.1-win-x64.msi

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          A8303C7FA36C03D28E2F35A414FB2F970E446A822139931C18020510AD2D2A92       C:\Temp\PowerShell-7.1.0-rc.1-win-x64.msi

PS C:\Temp> Get-FileHash -Path .\PowerShell-7.1.0-preview.6-win-x64.msi

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          628582C3A7D733E36C1BE35331CD35471011F9A5464FD0192D965E289D968CD9       C:\Temp\PowerShell-7.1.0-preview.6-win-x64.msi

PS C:\Temp>
```

**Comment by VectorBCO** [comment]
@danfloyd111 on which OS and which file you tried install rc1
on my w10 1909 pro x64 i have successfully installed PowerShell-7.1.0-rc.1-win-x64.msi
