### ISSUE TITLE
Replace Pester submodule with import

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1371]
Per #1275 we need to test if we can use the Pester package and remove the submodule. Failing that, we will likely move it to a vendor folder.

**Comment by vors** [comment]
@dlwyatt any updates here?

Also, would you like to be assigned to this issue?

**Comment by dlwyatt** [comment]
When I went through the code differences, they seemed to be lumped into three categories:  slashes, Add-Type, and Start-Job.  I believe the first two are already fixed in PS, but Start-Job may not be working yet on Linux.  (Pester itself doesn't actually need it, but it's used in some of the test suite.)

**Comment by dlwyatt** [comment]
So basically, download the latest Pester on a Linux build, run it and see what happens :)

**Comment by vors** [comment]
OK, will do

Adding #1979 for cross-reference

**Comment by andschwa** [comment]
For #1979, we're going to remove the Pester submodule and rely on importing Pester.

Maintainers are assigning this over to @JamesWTruher for investigation.

**Comment by JamesWTruher** [comment]
@dlwyatt I'm finally looking at this now - is there a specific branch I should be validating against? Running against 3.4.6 is failing about 7% of the tests

**Comment by joeyaiello** [comment]
@JamesWTruher as far as I can tell, we already removed the Pester submodule from the repository. Is this item now implicitly to use the latest version of Pester from the Gallery in our tests? If so, can we change the title to that effect and move this out to 6.1.0 (unless you see a reason for us to be on 3.4.6)?

**Comment by joeyaiello** [comment]
Based on an offline conversation with @JamesWTruher, while we should do this, we should hold this work off until Pester is fully cross-platform (which will likely not happen until after we release a stable 6.0.0).

**Comment by iSazonov** [comment]
@adityapatwardhan Should we close the Issue too after #6064?
