### ISSUE TITLE
Powershell core has issues with background text color when used with Windows terminal

### ISSUE THREAD

**Issue by BSG-75** [PowerShell/PowerShell#13720]
Originally I thought this should be a Windows Terminal's issue, but when I'm using Powershell 5.1 with Windows Terminal, I can't reproduce the issue.
So, this only happens when I'm using Powershell Core, so I decided to report the issue here.

## Steps to reproduce &  Expected behavior & Actual behavior

I think the screenshot below should be self-explanatory, but let me explain more precisely.
Windows Terminal allows us to set a background image, then it will replace the area occupied by the original background color with the background image.
But when I'm using Powershell Core, when typing commands that contain spaces, the background color of text returned to be the original background color, instead of being "transparent" (or more preciesly, instead of displaying the content of background image).
It only occurs when I'm typing commands, looks like this problem won't be triggered when I'm writing a string literal, even if it contains spaces, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/2989995/94719751-da071c00-0353-11eb-9962-14cec928e12b.png)

## Environment data

```none
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This looks like it might be a PSReadLine issue; does this still occur after calling `Remove-Module PSReadLine`?

**Comment by BSG-75** [comment]
@vexx32 Woaw! It doesn't occur anymore after calling `Remove-Module PSReadLine`.
But the syntax highlighting is gone too

And yes, if I call `Import-Module PSReadLine` again, the issue occurred again. So looks like it's a PSReadLine issue.

**Comment by vexx32** [comment]
Yes please! I'd also see if there are any more recent versions of PSReadLine available than you currently have, it may have been fixed somewhat recently, but I don't recall for sure.

**Comment by BSG-75** [comment]
Looks like uninstalling the pre-release version of PSReadLine has fixed the issue, now I'm happy xD
