### ISSUE TITLE
Get-PSDrive will not return free disk space

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#13724]
I have an issue when using Get-PSDrive on an Azure Virtual Machine
If I run this command, usually it should return free disk space. However, when I ran this command,  there's no free disk data returned.
![powershell](https://user-images.githubusercontent.com/57062529/94767761-f355aa00-03df-11eb-824a-26cdbe8e655d.png)

I have done the following steps
1. run powershell as administrator but no change
2. checked Windows OS version: Windows Server 2016 Datacenter-10.0.14393.0
3. checked Powershell version: 5.1.14393.3866

I have another Azure VM which has the same environment but I can run this command to get free disk space successfully.

May I know how this command get free disk space from disk? Is it possible to fix this issue?
Besides, if it’s possible to see the source code of this command? As I checked the module which this command belongs to, I found this command is not listed.
https://github.com/PowerShell/PowerShell/tree/master/src/Microsoft.PowerShell.Commands.Management/commands/management

**Comment by iSazonov** [comment]
@EricZhu0510 The repository is for PowerShell Core. Do you see the issue with latest PowerShell 7.1 RC build?

For Windows PowerShell you should use other resources like UserVoice site, forums and so on. 
Windows PowerShell is frozen (only security fixes is accepted), all new development continues for PowerShell Core only.

**Comment by anmenaga** [comment]
@EricZhu0510 2 commands that will give additional diagnostics info:
```
Get-Command Get-PSDrive                   
$PSVersionTable
```

@iSazonov is correct that if this repros only in Windows PowerShell, but not PowerShell Core, then unfortunately there is not much we can do about it at this point.

PS. [`Get-PSDrive` source code is here](https://github.com/PowerShell/PowerShell/blob/5aca8637ae5c420723f92c3c5b33e8f6163ae269/src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs#L1662).

**Comment by iSazonov** [comment]
Close as stale issue.
