### ISSUE TITLE
When displaying method overloads, show optional parameters as such

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13728]
## Summary of the new feature/enhancement

As a user, when I inspect the overloads of a given .NET method, I want to know which parameters are _optional_, so I only pass arguments to them if actually needed.

Accessing a method without invoking it (via `(...)`) conveniently shows all its overloads (signatures), but currently doesn't indicate which parameters are _optional_:

```powershell
Add-Type -NameSpace demo -Name Foo -MemberDefinition 'public static void Bar(string param, int optParam = -1) { }'
# Show the method signature.
[demo.Foo]::Bar
```

_Current_ output - NO indication that `optParam` is optional):

```
OverloadDefinitions
-------------------
static void Bar(string param, int optParam)
```

_Desired_ output - clear indication that `optParam` is optional, ideally also with its default value, if technically feasible:

```
OverloadDefinitions
-------------------
static void Bar(string param, int optParam = -1)
```

Note: The **same representation should be used for `Get-Member`** output, as originally proposed in #7373.
I suspect that the implementation is shared anyway.

**Comment by eugenesmlv** [comment]
I have code changes ready to submit to a PR that handles optional parameters. Could you please guide me on where I should add tests?

**Comment by iSazonov** [comment]
We haven't test for the area. I suggest to create new file in `test\powershell\engine\Api\` folder.
