### ISSUE TITLE
Windows PowerShell - Unable to import ScheduledTasks module

### ISSUE THREAD

**Issue by Indhukrishna** [PowerShell/PowerShell#1373]
## Steps to reproduce

1) Install latest Windows PowerShell from repo on a Windows machine using the script Update-PSCore.cmd. Alternatively, use the script Validate-OPSFullCLROnWindows.ps1 to get the latest bits and install. 

2) Import-Module ScheduledTasks  
## Expected behavior

Module is imported
## Actual behavior

``` powershell
ipmo : Cannot process Cmdlet Definition XML for the following file:
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\scheduledtasks\MSFT_ScheduledTask_v1.0.cdxml. The type initializer
for 'Microsoft.PowerShell.Cmdletization.ScriptWriter' threw an exception.
At line:1 char:1
+ ipmo scheduledtasks -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportModuleCommand
```
## Environment data

``` powershell
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-82-g34e62401883aaa7d13414cddbdcb29c87b0ebd72
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment]
This is irrelevant now given that the current POR for PS 6.0 is to go Core-only.

**Comment by MaximoTrinidad** [comment]
Hi @Indhukrishna, 

Although this is not a PowerShell Core (6.0.0-beta.1) issue, I may suggest to also post this incident at Windows PowerShell UserVoice site at: https://windowsserver.uservoice.com/forums/301869-powershell/category/148044-powershell-engine

This way the Windows PowerShell team can assist in this issue.

Thanks,
:)

**Comment by joeyaiello** [comment]
@MaximoTrinidad: @Indhukrishna is the Engineering Manager for DSC. 😉 

But yeah, this isn't a 5.1 issue, and we're not doing Core-only. Plus, ScheduledTasks appears to work just fine now with `6.0.0-beta.1` (thanks, CDXML and .NET Standard 2.0!)

![image](https://cloud.githubusercontent.com/assets/1255187/26598233/807865cc-4529-11e7-853e-124af4b36efe.png)

**Comment by MaximoTrinidad** [comment]
Thanks @joeyaiello!
