### ISSUE TITLE
Add modifications to libmi so that linux and mac users can connect to windows server with WinRM

### ISSUE THREAD

**Issue by quej1976** [PowerShell/PowerShell#13733]
## Summary of the new feature/enhancement

With stock libmi i cannot connect to my windows server from linux
However, with this modifications:
https://github.com/jborean93/omi
I can connect to all my windows server

It will be great to merge this code into the main powershell code.

## Proposed technical implementation details (optional)

https://github.com/jborean93/omi

**Comment by iSazonov** [comment]
libmi and WSMan was deprecated. Se latest PowerShell Committee conclusion https://github.com/PowerShell/PowerShell/issues/13577#issuecomment-693705372

**Comment by quej1976** [comment]
Ok, then when will we have an alternative to connect to windows from linux using kerberos to connect to Exchange servers for insistence?
Thanks in advance

**Comment by iSazonov** [comment]
@quej1976 It is a question for Exchange team.
