### ISSUE TITLE
Error: Could not load file or assembly 'System.Net.Connections, Version=5.0.0.0' on invoke-webrequest

### ISSUE THREAD

**Issue by mcDingleHead** [PowerShell/PowerShell#13735]
## Steps to reproduce

PS C:\> enter-pssession -computername localhost -configurationname PowerShell.7.1.0-rc.1

[localhost]: PS C:\> invoke-webrequest http://www.google.com

Error: Could not load file or assembly 'System.Net.Connections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

## Expected behavior

I'd expect invoke-webrequest to return the contents of the web page.

## Actual behavior

Instead, I receive:

Error: Could not load file or assembly 'System.Net.Connections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

## Environment data

The problem only occurs when running in a remote session. That's why I ran enter-pssession localhost prior to executing the invoke-webrequest command.

The issue began when PowerShell.7.1.0-rc.1 was installed. It's not an issue in the prior version (7.1.0-preview.7).

Installing .NET 5.0 RC1 doesn't resolve the issue.

**Comment by anmenaga** [comment]
@mcDingleHead Please provide some additional diagnostics info that may be helpful:
1) `$PSVersionTable` from both: local and remote sessions.
2) how did you deploy `7.1.0-rc.1` - from archive (zip/tar.gz) or using installer package (msi/deb/rpm) ?
3) looks like there were previous PS Core installations, when you installed `7.1.0-rc.1`, correct?

**Comment by TravisEz13** [comment]
May need to update the TPA for WS-MAN in the native repo.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell-Native/issues/55

**Comment by daxian-dbw** [comment]
The TPA list was updated. We can close this issue now.

**Comment by eeskildsen** [comment]
I'm getting a similar error:

```
Invoke-WebRequest: Could not load file or assembly 'System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

This only happens when remoting.

#Remote $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Local $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Installation

I installed PowerShell 7 from the MSI here:

https://github.com/PowerShell/PowerShell/releases/download/v7.3.1/PowerShell-7.3.1-win-x64.msi

I don't know of any previous PS Core versions installed on the server, though it's possible.
