### ISSUE TITLE
Add Hacktober topic to repository

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13749]
Please add the `Hacktober` topic to the repository to opt-in to the event. Here is some additional information for the event.

After working closely with our friends at GitHub, we are happy to introduce measures that are brand new to Hacktoberfest 2020.

* Pull requests can be made in any participating GitHub-hosted repositories/projects.

* Maintainers can opt-in to participate by classifying their projects with the hacktoberfest topic. https://youtu.be/FxBv4FMcDgo

* Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted.

* Additionally, any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.

**Comment by iSazonov** [comment]
We already have `Hacktoberfest` label.

Problem is that now we are in intermediate period - RC1, then RC2 - so all another work excluding release stabilization is frozen.

**Comment by vexx32** [comment]
@iSazonov the `hacktoberfest` label itself is not recognised by DigitalOcean from what I can tell.

If we wanted to allow PRs to count towards hacktoberfest we'd need to add the topic to the repository itself, and also add a `hacktoberfest-accepted` label for PRs.

**Comment by iSazonov** [comment]
I see they changed rules. Now they exclude repositories from the project by default.

We need a confirmation from MSFT team if they want to participate in the project and accept PRs in the time.

/cc @joeyaiello @SteveL-MSFT

**Comment by SeeminglyScience** [comment]
Note that adding the topic isn't really a commitment to reviewing the PR any time soon (or at all really). Unless the PS team was considering disabling PR's all together I don't think there's a reason not to add it.

**Comment by vexx32** [comment]
Aye. I think it might be a good idea for maintainers to go through PRs submitted during the hacktoberfest period and tag the ones that look likely to be accepted as `hacktoberfest-accepted` so that the contribution is recognised, even if it takes longer for the review to be completed and/or the PR to be merged.

**Comment by SeeminglyScience** [comment]
Yeah, hopefully that's something outside collaborators can do as well (just yourself and @iSazonov right?).  Should be pretty quick to determine if something is just spam.

**Comment by vexx32** [comment]
Yeah, I can help make sure we label stuff appropriately as needed, as long as the label is created already (I can't create tags, but I can apply/remove them where appropriate). 🙂  

We should also make sure we have an `invalid` or `spam` label in case we get any spammy PRs.

**Comment by SteveL-MSFT** [comment]
I've already added the `hacktoberfest` topic to this repo.  I'll add the `hacktoberfest-accepted` label to be used with PRs.

**Comment by vexx32** [comment]
Looks like that's all sorted, so I guess we can call this one covered for now. 🙂
