### ISSUE TITLE
When PowerShell runs elevated on Windows, starting *.msc files locks the console

### ISSUE THREAD

**Issue by sethvs** [PowerShell/PowerShell#13744]
When PowerShell `v7.1.0-preview.7` or `v7.1.0-rc.1` is started as Administrator on Windows, and I start some mmc snap-in: `compmgmt`, `diskmgmt`, etc., it locks the console until I close the snapin.

It doesn't lock on `v7.1.0-preview.6` and earlier versions.
It doesn't lock when PowerShell started as standard user (no elevation).
Also, it doesn't lock, when I start the snapin as `mmc compmgmt.msc`

I haven't found (yet?) other file types, that behave like this, maybe there are some.

## Steps to reproduce

```powershell
compmgmt
```

## Expected behavior

```none
Computer management snapin starts, console doesn't lock.
```

## Actual behavior

```none
Computer management snapin starts, console locks until snapin closes.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-rc.1
PSEdition                      Core
GitCommitId                    7.1.0-rc.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This only appears to repro in Windows Terminal and not conhost.  cc @dhowett

**Comment by DHowett** [comment]
> It doesn't lock on `v7.1.0-preview.6` and earlier versions.

That's alarming!

**Comment by DHowett** [comment]
This reproduces in conhost and terminal for me.

![image](https://user-images.githubusercontent.com/189190/95116877-8fdbbd00-06fc-11eb-883e-51569cadd015.png)

![image](https://user-images.githubusercontent.com/189190/95116902-979b6180-06fc-11eb-9129-f9cd64540015.png)

**Comment by vexx32** [comment]
I'm probably not familiar enough to trace exactly where or why this changed, but I have a feeling it's probably a .NET change between the preview versions used for 7.1-p6 and later 7.1 previews/RC.

**Comment by DHowett** [comment]
The change inhttps://github.com/PowerShell/PowerShell/pull/13481 landed in preview7, and it changes a bit about how PowerShell detects what applications to "wait" for. It looks like it subtly shuffles the logic around in a way that may have caused an issue?

**Comment by SteveL-MSFT** [comment]
@dhowett, oops I forgot to run cmd.exe elevated which is why it didn't repro for me...
