### ISSUE TITLE
Get-Module -ListAvailable generates a parameter error

### ISSUE THREAD

**Issue by chscott** [PowerShell/PowerShell#13745]
## Steps to reproduce

```powershell
PS C:\Temp> Get-Module -ListAvailable
Get-Module: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

PS C:\Temp> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Manifest   7.0.0.0               Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP…}
Script     2.0.2                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandle…
```

## Expected behavior

Installed modules are listed.

## Actual behavior

_Get-Module: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided._

Interestingly, the ListAvailable parameter is auto-completed if I type Get-Module, a space, a dash, and then hit Tab. I have to hit Tab multiple times to cycle through the parameters, but that is normal.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can not repro on 7.0.3 and latest 7.1 RC1. What is `gcm Get-Module` output?

**Comment by chscott** [comment]
```none
PS C:\src\transend\tmc-tools> gcm Get-Module

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-Module
```

In subsequent testing, it seems the issue develops some time after a fresh instance is launched. It will work for a time, and then it stops working with the error above. I restart, it works again for awhile, then the same issue happens.

**Comment by iSazonov** [comment]
Expected output is
```powershell
 gcm Get-Module

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-Module                                         7.0.3.0    Microsoft.PowerShell.Core
```
You use _function_, not cmdlet.

**Comment by chscott** [comment]
> Expected output is
> 
> ```powershell
>  gcm Get-Module
> 
> CommandType     Name                                               Version    Source
> -----------     ----                                               -------    ------
> Cmdlet          Get-Module                                         7.0.3.0    Microsoft.PowerShell.Core
> ```
> 
> You use _function_, not cmdlet.

I don't understand. You asked for the output of that command, and that's what I'm getting. If that isn't right, then that seems like a bug or some kind of configuration issue that should be documented. This is a clean install, by the way. That was one of the things I tried after opening this issue.

**Comment by iSazonov** [comment]
In your output Get-Module id __function__ (see CommandType column). This means that you have created this function in your profile.
