### ISSUE TITLE
Member enumeration malfunctions with array that contains 2 or more [pscustomobject] instances, [pscustomobject] contributes `$null` to the result even for non-existent properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13752]
This bug also affects Windows PowerShell.

Normally, trying to access a non-existent property on an array makes member enumeration return `$null`.

However, if the array contains at least two `[pscustomobject]` instances, an _array_ of `$null` values - one for each `[pscustomobject]` array element - is unexpectedly returned.

**Update**:

* The repro steps below show the problem only _indirectly_.

* The **core problem is that `[pscustomobject]` instances - unlike instances of any other type - unexpectedly contribute `$null` to the result even for _non-existent properties_**:
   * `([datetime]::Now, [regex] '.').Year -contains $null` is `$false`, because `[regex]` instances have no `.Year` property, so they don't contribute to the result.
   * By contrast, ` ([datetime]::Now, [pscustomobject] @{}).Year -contains $null` yields `$true`(!); that is, even though the `[pscustomobject]` instance doesn't have a `.Year` property, it unexpectedly contributed `$null` to the result.

---

## Steps to reproduce

```powershell
# OK: $null is returned, so .Count is 0
(1, [pscustomobject] @{ foo = 1 }).NoSuchProperty.Count | Should -Be 0

# !! FAILS: ($null, $null) is returned, whose .Count is 2
(1, [pscustomobject] @{ foo = 1 },  [pscustomobject] @{ foo = 2 }).NoSuchProperty.Count | Should -Be 0
```

## Expected behavior

Both tests should succeeds

## Actual behavior

The second test fails:

```none
 Expected 0, but got 2.
```

## Environment data

```none
PowerShell 7.1.0-rc.1
```

**Comment by vexx32** [comment]
Hmm, interesting... judging from the behaviour with something like `(1, 2, 3, 4).NoSuch.Count` it _seems_ like the difference might be that normal objects return AutomationNull.Value rather than true null for nonexistent properties, unless there's some code specifically handling cases like this somewhere.

**Comment by iSazonov** [comment]
It's even worse:
```
(1, [pscustomobject] @{ foo = 1 }, 12, [pscustomobject] @{ NoSuchProperty = 22 }).foo.Count
2
```

**Comment by iRon7** [comment]
It indeed appear to include `$Null` values for nonexistent properties:
```PowerShell
ConvertTo-Json ((1, [pscustomobject] @{ foo = 1 }, 12, [pscustomobject] @{ NoSuchProperty = 22 }).foo)
[
  1,
  null
]
```

**Comment by nickkimbrough** [comment]
I just ran into this as well. Here is another example to reproduce:

```Powershell
Set-StrictMode -Version 'Latest'

$results = @(1,2) | ForEach-Object {
 [System.Collections.Generic.List[string]]$array = @()
    [PSCustomObject]@{
        Array = [string[]]$array
    }
}

# This will not throw
foreach($result in $results) {
    $result.Array
}

# This will throw
$results.Array
```

This behavior does not throw if StrictMode is not enabled.

**Comment by aolszowka** [comment]
Reproduces for me; as described:

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
> (1, [pscustomobject] @{ foo = 1 },  [pscustomobject] @{ foo = 2 }).NoSuchProperty.Count
2
```

(The above should be 0)

Same deal with the repro from @iSazonov 

```
(1, [pscustomobject] @{ foo = 1 }, 12, [pscustomobject] @{ NoSuchProperty = 22 }).foo.Count
2
```

(The above again should be 0)

**Comment by surfingoldelephant** [comment]
Note that _two_ custom object instances are not required for this member-access enumeration bug to manifest. 

Just _one_ and at least one object of any _other_ type in the enumerated collection is enough.

```powershell
# Name exists on at least one object, so $null values should *not* be returned.
# The single custom object contributes $null to the output.
ConvertTo-Json ((Get-Process -Id $PID), [pscustomobject] @{ Foo = 'Foo'}).Name
# [
#   "pwsh",
#   null
# ]

# Without custom object involvement, behavior is expected:
ConvertTo-Json ((Get-Process -Id $PID), 'foo').Name
# "pwsh"
```

**Comment by surfingoldelephant** [comment]
Here's another manifestation of this issue that doesn't involve a custom object at all.

```powershell
Add-Type -TypeDefinition @'
using System;

public class Class1 {
    public string Foo { get { throw new Exception("Error"); } }
}
'@

ConvertTo-Json ([Class1]::new(), [Class1]::new()).Foo
# [
#   null,
#   null
# ]
```

Each property getter exception contributes a `$null` value to the result. 

It's worth noting that while using getter exceptions is [not recommended](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065#property-get-methods), it's still used in practice, including within the PowerShell source code.

**Comment by x5i4k4** [comment]
Please reopen this issue, it can be really confusing to resolve when dealing with parsed json list for example, it became a penalty for people have the right understanding of group operator

```ps1
(Get-Content ./list.json |  ConvertFrom-Json)."" -is [array] # true
(Get-Content ./list.json |  ConvertFrom-Json)."" | foreach { $_ -eq $null } # all true, array of nulls
```

**Comment by iRon7** [comment]
@x5i4k4 

> it became a penalty for people have the right understanding of group operator

I don't think that your example applies to the actual issue, knowing that `Get-Content` returns a array of lines by default. <strike>Meaning, presuming that the content of `./list.json` is not a list of **Compressed** Json **lines** but a multi-line Json structure, you will need to combine the lines (`- join [Environment]::NewLine`) first or load the whole content in once using the [`-Raw`](https://learn.microsoft.com/powershell/module/microsoft.powershell.management/get-content#-raw) switch, see also: https://stackoverflow.com/q/35863103/1701026</strike>
The only example where the [member-access enumeration](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_member-access_enumeration) of an empty string (`""`) would return something should be an `json` expression like:
```PowerShell
('{"":"Test"}' | ConvertFrom-Json).""
```
But that produces an error as the `PSCustomObject` doesn't support an empty string for a property name.
As apposed to a HashTable:
```PowerShell
 ('{"":"Test"}' | ConvertFrom-Json -AsHashTable)."" | ForEach-Object { $_ -eq $null } # --> $false
```
that does support an empty string for a key name (and return `$false` for your comparison) but doesn't exhibit the concerned issue.

* What exactly do you expect from the command: `(Get-Content ./list.json |  ConvertFrom-Json)."" `?
* Can you give an example of the contents of `./list.json` that should support this expectation?

As an aside: [`$null` should be at the left-hand-side of the operator](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null?view=powershell-7.5#checking-for-null) (which is less of an issue here)

**Comment by surfingoldelephant** [comment]
> you will need to combine the lines (- join [Environment]::NewLine) first or load the whole content in once using the [-Raw](https://learn.microsoft.com/powershell/module/microsoft.powershell.management/get-content#-raw) switch

`-Raw` in this case may be recommended, but isn't mandatory. `ConvertFrom-Json` [accumulates pipeline input](https://github.com/PowerShell/PowerShell/blob/bd33c2d9878a46af65968da42fc4411bcd7bc46d/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs#L67), so piping individual strings that collectively form valid JSON content works just fine.

```powershell
$tmp = [IO.Path]::GetTempFileName()
Set-Content -LiteralPath $tmp -Value @'
[
    {
        "Foo": 1
    },
    {
        "Foo": 2
    }
]
'@

($result = Get-Content -LiteralPath $tmp | ConvertFrom-Json)

# Foo
# ---
#   1
#   2

$result.Count # 2
```

Regarding `""`, I suspect it's being used just as an arbitrary way of provoking the issue. It could be replaced with any other member name in this example.

```powershell
ConvertTo-Json $result.""

# [
#   null,
#   null
# ]

ConvertTo-Json $result.Bar

# [
#   null,
#   null
# ]
```

(`ConvertTo-Json` is used to visually show how each custom object contributes a `$null` value to member-access enumeration output.)
