### ISSUE TITLE
AzureAD module Get-AzureADServiceAppRoleAssignment swapped with Get-AzureADServiceAppRoleAssignedTo

### ISSUE THREAD

**Issue by basburg** [PowerShell/PowerShell#13756]
## Steps to reproduce

Note: I posted this issue in the [Azure Powershell Repo](https://github.com/Azure/azure-powershell/issues/13136) and was redirected to this Repository for AzureAD issues.

When running `Get-AzureADServiceAppRoleAssignment` in `AzureAD` version `2.0.2.116` it behaves exactly like running `Get-AzureADServiceAppRoleAssignedTo` on `AzureAD` version `2.0.2.106`, while `Get-AzureADServiceAppRoleAssignedTo` on `v2.0.2.116` behaved exactly like `Get-AzureADServiceAppRoleAssignment` on `v2.0.2.106`.

I assume that in the latest update the command got swapped somehow.

To reproduce, run 

```powershell
Get-AzureADServiceAppRoleAssignment -ObjectId <object-id>
Get-AzureADServiceAppRoleAssignedTo -ObjectId <object-id>
```

and notice the different output between the two `AzureAD` versions

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.19041.546
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.546
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

tagging @danigian

**Comment by vexx32** [comment]
I'm not really sure why they pointed you here; the PowerShell team have no control over the AzureAD module as far as I'm aware. 😕

**Comment by iSazonov** [comment]
> PSVersion                      5.1.19041.546

The repository is only for PowerShell 7 developers, not Windows PowerShell. 
AzureAD module is seem not open source and it is not in the repo so please use another cannels to report and discuss the issue.
