### ISSUE TITLE
Add provider for Test-Path -Filter

### ISSUE THREAD

**Issue by nikitasa1997** [PowerShell/PowerShell#13764]
## Summary of the new feature/enhancement

Add FileSystem provider to list of supported filters for Test-Path. It must behave like `Get-ChildItem -Filter`

```powershell
Set-Content -Path 'C:\Users\username\Documents\test.txt' -Value 'Hello, World!'
Test-Path -Path 'C:\Users\username\Documents\test.txt' -Filter '*.json'
```

## Expected behavior

```none
False
```

## Actual behavior

```none
True
```

**Comment by vexx32** [comment]
Do any currently implemented providers provide a `-Filter` for `Test-Path`? 🤔 I'm not aware of there being any.

**Comment by SeeminglyScience** [comment]
@vexx32 don't think so but to be fair, no other built-in provider has support for `Filter` in any capacity (at least of those I've tested).

This wouldn't be super easy to add though I don't think. Currently it's just a property on `CmdletProvider` called `Filter`. The provider registers that it supports filters by declaring it as part of their `ProviderCapabilities`.  It's sort of all or nothing, so if this were added to `Test-Path` you'd need a new `ProviderCapabilities` value like `FilterItemExists`.  And/or maybe a new method to test `ItemExists` with a filter, plus new interface and/or base class to implement/inherit from.

**Comment by vexx32** [comment]
Yeah, that's my thought tbh, the file system provider is the only one I've ever seen a filter on, so I was curious if something else had tried to put filters on Test-Path.

It's an unusual use case too; Test-Path is usually used for testing complete paths, whereas -Filter is generally used to qualify searches (Get-ChildItem/Get-Item) and to filter out certain results. I kind of get the intent here, but I'm not really sure what providing -Filter would add here; you already have the path itself, so you can test if the string ends with a specific extension with more direct methods, or use Split-Path to retrieve just the filename if you have more complex patterns to test against. 😕

**Comment by nikitasa1997** [comment]
> Do any currently implemented providers provide a `-Filter` for `Test-Path`? 🤔 I'm not aware of there being any.

@vexx32, no. Not yet. It's not mentioned in [docs](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Test-Path?view=powershell-7) at least

**Comment by nikitasa1997** [comment]
> Yeah, that's my thought tbh, the file system provider is the only one I've ever seen a filter on, so I was curious if something else had tried to put filters on Test-Path.
> 
> It's an unusual use case too; Test-Path is usually used for testing complete paths, whereas -Filter is generally used to qualify searches (Get-ChildItem/Get-Item) and to filter out certain results. I kind of get the intent here, but I'm not really sure what providing -Filter would add here; you already have the path itself, so you can test if the string ends with a specific extension with more direct methods, or use Split-Path to retrieve just the filename if you have more complex patterns to test against. 😕

@vexx32, [Get-ChildItem](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-7) support two way for filtering:
`-Filter`
`-Include`/`-Exclude`

**Comment by iSazonov** [comment]
>  It must behave like Get-ChildItem -Filter

I wonder if it works:
```powershell
dir C:\tmp\test1.txt -Filter "*.json"

    Directory: C:\tmp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          28.04.2020    21:26             14 test1.txt
```

**Comment by nikitasa1997** [comment]
> > It must behave like Get-ChildItem -Filter
> 
> I wonder if it works:
> 
> ```powershell
> dir C:\tmp\test1.txt -Filter "*.json"
> 
>     Directory: C:\tmp
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a---          28.04.2020    21:26             14 test1.txt
> ```

@iSazonov, It's another one bug definitely. Try:
```powershell
 dir C:\tmp\ -Filter "*.json"
```
It will return only .json files. I had tested it.

**Comment by vexx32** [comment]
Yeah I think fundamentally the way the Filter functionality is designed, it tends not to apply when you supply a completely unambiguous single file path; there's nothing for it to filter in the first place, there's only one thing it can be.

Whether that should change now is an open question, I guess.

**Comment by iSazonov** [comment]
I opened #14624 for https://github.com/PowerShell/PowerShell/issues/13764#issuecomment-706584149 bug.
