### ISSUE TITLE
Test-Path ignore -Include and -Exclude when -IsValid is set

### ISSUE THREAD

**Issue by nikita-sakharin** [PowerShell/PowerShell#13763]
## Steps to reproduce

```powershell
Test-Path -Path 'C:\Users\username\Documents\test.json' -Exclude '*.json' -IsValid
Test-Path -Path 'C:\Users\username\Documents\test.txt' -Include '*.json' -IsValid
```

## Expected behavior

```none
False
False
```

## Actual behavior

```none
True
True
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-rc.1
PSEdition                      Core
GitCommitId                    7.1.0-rc.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Shriram0908** [comment]
Hi @nikitasa1997 From Microsoft Documentation IsValid only checks the syntax of the path is valid or not and does not care if the file is present or not.

[Test-Path documentation](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Test-Path?view=powershell-7)

```
-IsValid

Indicates that this cmdlet tests the syntax of the path, regardless of whether the elements of the path exist. This cmdlet returns $True if the path syntax is valid and $False if it is not.

**Comment by kvprasoon** [comment]
@iSazonov with the current expectation of `-IsValid` parameter, isn't this issue invalid, can't this issue be closed ?

**Comment by iSazonov** [comment]
Since now we use WG (work group) workflow I set triage request.

**Comment by nikitasa1997** [comment]
> Hi @nikitasa1997 From Microsoft Documentation IsValid only checks the syntax of the path is valid or not and does not care if the file is present or not.
> 
> [Test-Path documentation](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Test-Path?view=powershell-7)
> 
> ```
> -IsValid
> 
> Indicates that this cmdlet tests the syntax of the path, regardless of whether the elements of the path exist. This cmdlet returns $True if the path syntax is valid and $False if it is not.
> ```

Good day, @Shriram0908!
Let's take as an example the code:
```
Set-Content -Path '~\Documents\test.txt' -Value 'Hello, World!'
Test-Path -Path '~\Documents\test.txt'
Test-Path -Path '~\Documents\test.txt' -Include '*.txt'
```
Output is:
```
True
True
```
After that:
```
Test-Path -Path '~\Documents\test.txt' -Include '*.json'
Test-Path -Path '~\Documents\test.txt' -Exclude '*.txt'
```
Output is:
```
False
False
```
Thus, I expect the `-IsValid` flag to behave in a same way. And what could be the reason for otherwise? Or else `-Include` and `-Exclude` flags are pointless with the `-IsValid` flag and should raise some error.

**Comment by iSazonov** [comment]
I believe a design intention for all Test-* cmdlets to do an _exact_ check. For Test-Path cmdlet this means the Path is a _target_ path and must be interpreted as _a literal path_ and Include/Exclude parameters must be removed. Other cmdlets with target path parameter (New-Item/Copy-Item/Set-Content-Out-File and so on) should consider the target path as literal path, an globbing on the target path rather confuse than benefit.
