### ISSUE TITLE
Select-Object: Add a -NotIndex parameter to complement -Index to select all BUT the objects at the specified positions

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13769]
See also: #11752

## Summary of the new feature/enhancement

`Select-Object -Index` allows me to select a subset of the input objects by an array of indices (`0`-based positions in the input stream):

```powershell
PS> 1..5 | Select-Object -Index 1, 3  # here the same as: (1..5)[1,3]
2
4
```

It would be helpful to be able to select the _complement_, i.e. all elements _other_ than the ones specified, using a new `-NotIndex` parameter:

_Update_: The original proposal suggested a separate `-Not` switch to be combined with `-Index`, but this was changed based on @jhoneill's suggestion.

```powershell
# WISHFUL THINKING: -Not returns everything *but* the objects at the specified positions.
PS> 1..5 | Select-Object -NotIndex 1, 3 
1
3
5
```

For instance, it would allow you to exclude a line with a given number from an array of a file's input lines:

```powershell
# WISHFUL THINKING
PS> 1..3 + 'exclude me' + 4..5 > sample.txt; Get-Content sample.txt | Select-Object -NotIndex 3
1
2
3
4
5
```

Note: While it is hypothetically possible to allow _combining_ `-Index` with `-NotIndex`,  it wouldn't be easy to reason about by the user and is probably of little practical value.
Thus, `-Index` and `-NotIndex` should be made mutually exclusive.

**Comment by jhoneill** [comment]
Probably a single -NotIndex would be better.  Otherwise people would wonder if you can do -not -first (where skip already exists) and similar. 

While looking at this
`1..5 | select  -First 2 -last 1 -Skip 1`   Works on 7..0.3  as I'd expect (i.e. it gives 2,3 and 5)
`1..5 | select  -last 2 -Skip 1 `   skips the last 1 and gives the last 2 before that. Not sure what I'd expect it to do, or that this is "right"  

`1..5 | select  -SkipLast 3` works but -skiplast won't combine with -first or -last.

**Comment by scriptingstudio** [comment]
Maybe -skip <int[]> (range) would be better?

**Comment by jhoneill** [comment]
> Maybe -skip <int[]> (range) would be better?

`-Skip 7,8,9` sounds OK for skipping 3 items by index  and `-skip (7..9)` for the same does as well. The problem is that `-skip 7` is already skipping the first 7 items so a version of `-skip 7...` which _included_ 1..6 would make it easier to confuse people, would `skip 7,10`  suggest 7 _to_ 10, 7 _and_ 10, or starting at 7 _continuing for_ 10

**Comment by mklement0** [comment]
I agree that `-Skip` is not an option due to the existing semantics; it would also lack symmetry with `-Index`.

I do see the appeal of `-NotIndex`, so I've updated the OP accordingly - thanks, @jhoneill.

**Comment by SeeminglyScience** [comment]
`-SkipIndex` does exist already (though appears to be missing in help?), but all of the `-Skip*` parameters feel really awkward to use interactively imo. I personally like the `-Not` switch better, here's how I picture it working:

```powershell
0..2 | select -Not -Index 1
# 0
# 2

0..5 | select -Not -First 2 -Last 1
# 2
# 3
# 4

0..5 | select -Not -Skip 3
# throw
```

Unsure if it's worth it while they already exist in different forms though 🤷

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience - indeed it was the omission of `-SkipIndex` from an outdated local help file that made me miss that parameter. (`Update-Help` fixes the problem, and `Get-Command -Syntax Select-Object` would have shown it either way).

As for a `-Not` as a general switch that negates whatever the other switches select: I think it probably isn't worthwhile, as the coexistence with `-Skip` may create confusion, as you say.

---

`-Skip` is particularly awkward in combination with `-Last`, as @jhoneill's example shows: 
* If `-First` _isn't_ also present, it is interpreted as a _negative_ offset from the end.
* If `-First` is (also) present, it is always interpreted as a positive offset from the start (only).

```powershell
PS> 1, 2, 3, 4, 5 | Select-Object -First 1 -Skip 1 -Last 2
2
4
5   # Due to presence of -First, -Skip had no effect on -Last

PS> 1, 2, 3, 4, 5 | Select-Object -Skip 1 -Last 2
3
4 # Due to absence of -First, -Skip acted as negative offset from the end.

# Edge case, though still worrisome:
PS> 1, 2, 3, 4, 5 | Select-Object -First 0 -Skip 1 -Last 2
3
4   # -First 0 acted like not specifying -First at all
```
