### ISSUE TITLE
Truncated commands in ConsoleHost_history.txt

### ISSUE THREAD

**Issue by jaslawinMs** [PowerShell/PowerShell#13767]
ConsoleHost_history.txt collects commands issued in the console. However, Powershell core truncates commands to 215 characters. 

The classic power shell (not core) saves full command line, so it is a regression. 
I think that the previous version of PS core also saved more (but not sure about that and do not want to downgrade to verify).

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0 ```

**Comment by mklement0** [comment]
I don't see the symptom. Can you provide a reproducible example?

Here's an example of a command that works fine across sessions; it outputs a 501-character string literal and reports its length:

```powershell
(write-output 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy').length
```

**Comment by jaslawinMs** [comment]
I cannot confirm directly this 215 characters truncation now; I just see it is truncated in the history file.
However I could provide this issue that is similar:

```
.\product\src\Run-Test2.ps1 -TargetHost api.redacted.net -TestName ScaleGoals.jmx -DurationInSeconds $(3600*27) -WorkerCount 25 -JMeterProperties "-GOveralGoalPercentage=100 -GSETUP_FILE=100-1k.json" -pfxCertificatePath D:\frome2e_smartspacese2ekeyvault-redacted-20200430.pfx -generateReportJMeterReport $false -collectLog $false
```

This does not show up in the history file at all, however this
```
.\product\src\Run-Test2.ps1 -TargetHost api.redacted.net -TestName ScaleGoals.jmx -DurationInSeconds $(3600*27) -WorkerCount 25 -JMeterProperties "-GOveralGoalPercentage=100 -GSETUP_FILE=100-1k.json" -pfxCertificatePath D:\from.pfx -generateReportJMeterReport $false -collectLog $false
```
is saved in the history file. The only difference is how long is the path to pfx file.

I did a few retries and only this change affects the the history update.

If I have repros of the truncation I will update the thread.

**Comment by jaslawinMs** [comment]
I do not observe the issue anymore after new updates
