### ISSUE TITLE
`Invoke-RestMethod` pipes the whole array as a single object instead of a single object for each each entry in the array, deviating from PowerShell conventions and `ConvertFrom-Json`

### ISSUE THREAD

**Issue by robertwesterlund** [PowerShell/PowerShell#13778]
As was discussed and changed as of #3424, the `ConvertFrom-Json` cmdlet now enumerates arrays and provides a `-NoEnumerate` switch to use the old behavior.

However, the `Invoke-RestMethod` cmdlet, which behaves in the same non-conventional way as the old version of `ConvertFrom-Json` was not changed at the same time, so this cmdlet is still deviating from the expected PowerShell behavior.

Based on the fact that [the PowerShell committee decided to support adding a `-NoEnumerate` switch for the same deviation in `ConvertFrom-Json`](https://github.com/PowerShell/PowerShell/issues/3424#issuecomment-550556633) it seems logical to ensure that the other cmdlet which causes the same issues for people should be changed in the same way.

## Steps to reproduce

```powershell
$port = 41732

$job = Start-Job {
  PARAM(
    $Port
  )
  $listener = [System.Net.HttpListener]::new()

  $prefix = "http://localhost:$Port/"
  $listener.Prefixes.Add($prefix)
  $listener.Start()

  Write-Output "Waiting for requests on $prefix"	
  $httpContext = $listener.GetContext()
  Write-Output "Received Request"
  $responseContent = [Text.Encoding]::Utf8.GetBytes('[1,2,3]')
  $response = $httpContext.Response
  $response.StatusCode = 200
  $response.ContentType = 'application/json'
  $response.ContentLength64 = $responseContent.Length
  $response.OutputStream.Write($responseContent, 0, $responseContent.Length)
  $response.OutputStream.Close()
  $listener.Close()
  $listener.Dispose()	
  Write-Output "Response send, server shut down"
} -ArgumentList $port

# Wait for the job to output that it is waiting for requests
while(-not($job | receive-job))
{
  Start-Sleep -Milliseconds 250
}

invoke-restmethod "http://localhost:$port/" | measure | select -expand count
```

## Expected behavior

The output presented should be:

```none
3
```

## Actual behavior

The output written is:
```none
1
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TheDotSource** [comment]
Can second this, this caught me out when using WHERE and SELECT statements as I assumed each object would appear on the pipeline, not passed as an array.
