### ISSUE TITLE
Expose `Parameters` on ScriptBlock, same as with functions (`[System.Management.Automation.FunctionInfo]`)

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#13774]
## Summary of the new feature/enhancement
Currently, when I want to list what parameters a function has, I can call `(Get-Command fn).Parameters`. When I want to do the same with scriptblock, I have to use `$block.Ast` and manually parse the parameters from the AST, which is quite convoluted. It would be much more convenient if the same `.Parameters` attribute worked for scriptblocks.

## Proposed technical implementation details (optional)
Add `.Parameters` property to `[scriptblock]` that returns same output as on `[System.Management.Automation.FunctionInfo]`

**Comment by vexx32** [comment]
You can do a quick workaround for the same currently:

```ps1
$function:temp = $scriptblock
(Get-Command temp -CommandType function).Parameters
Remove-Item function:temp
```

**Comment by MatejKafka** [comment]
That's an awesome hack, thanks. :)

**Comment by MatejKafka** [comment]
not completed, please reopen

**Comment by oising** [comment]
Ping, @SeeminglyScience

**Comment by MatejKafka** [comment]
As an alternative, which is especially useful from C#, there's an internal property `RuntimeDefinedParameters` on a `ScriptBlock`, which is a different type than the `ParameterMetadata` dictionary returned from `Get-Command`, but contains the same information:
```powershell
$flags = [System.Reflection.BindingFlags]"NonPublic,Public,Instance"
$p = [scriptblock].GetProperty("RuntimeDefinedParameters", $flags)
$p.GetValue({param($a)})
```

I use it in the following helper class to copy parameters from other cmdlets and scriptblocks:
https://github.com/MatejKafka/Pog/blob/main/app/Pog/lib_compiled/Pog/src/Commands/Common/DynamicCommandParameters.cs
