### ISSUE TITLE
Get-UICulture returns wrong result

### ISSUE THREAD

**Issue by merrua** [PowerShell/PowerShell#13770]
## Steps to reproduce

1. On Microsoft Windows 10 Home 10.0.18363 Build 18363
2. Set Settings > Windows region 
County or Region Ireland
Regional Format Recommended English Ireland
Language English (Ireland)
3. On powershell 7.0.3
Run Get-UICulture
Result is
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
Expected
6153            6153               English(Ireland)

This is confusing as I set the region to Ireland (in the EU) during PC initial set up.
I'm a bit worried that its detecting a soon to be non-eu country for the UICulture. 
As I'd expect values like that are looked at for what data processing laws are followed.
The region as Ireland before I installed Powershell 7

## Expected behavior

Run Get-UICulture
Result is
LCID             Name             DisplayName
6153            6153               English(Ireland)

## Actual behavior

Run Get-UICulture
Result is
LCID             Name             DisplayName
2057             en-GB            English (United Kingdom)

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## OS Settings

Settings > Windows region 
County or Region Ireland
Regional Format
Recommended English Ireland

Language
English (Ireland)

Windows
OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363

**Comment by mklement0** [comment]
Note that it isn't the _region_ that determines what `Get-UICulture` returns, but the _Windows display language_ - have you changed that too? (Settings > Time & Language > Language).

Generally, note that `Get-UICulture` essentially just calls `[cultureinfo]::CurrentUICulture`, so if there is an actual problem, you'd have to report it in https://github.com/dotnet/runtime (and it could hypothetically  turn out to be a WinAPI problem in the end).

**Comment by merrua** [comment]
My language settings have not changed recently. If I go to Settings > Time & Language > Language

My windows display language is English (Ireland)

My Preferred languages in order are
English (Ireland)
English ( United Kingdom)
Gaeilge
日本語 (Japanese)

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to follow @mklement0 suggestion.
