### ISSUE TITLE
ConvertFrom-Json tolerates non-standard JSON -- consider a -Strict flag

### ISSUE THREAD

**Issue by AurimasNav** [PowerShell/PowerShell#13788]
## Steps to reproduce

```powershell
>"{'key':'value',}" | ConvertFrom-Json
```

## Expected behavior

expecting pwsh to throw an exception just like powershell 5.1
```powershell
ConvertFrom-Json : Invalid JSON primitive: .
At line:1 char:22
+ "{'key':'value',}" | ConvertFrom-Json
+                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

## Actual behavior

```powershell
>"{'key':'value',}" | ConvertFrom-Json

key
---
value
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
I would expect pwsh 7 to throw in this case just like powershell 5.1 does, in a case where I need to pass this json string down to some other tool I can't validate it using pwsh which I was able to do with powershell 5.1, I've laso tried ```Test-Json``` which behaves consistently:
```powershell
> "{'key':'value',}" | Test-Json
True
```

**Comment by rjmholt** [comment]
This is probably due to Newtonsoft.Json being tolerant and not being configured to reject input like this. If we've been permissive like this, it's possible someone now depends on it, but changing it would strike me as a bucket 3 breaking change

**Comment by iSazonov** [comment]
We will consider this during migration to the new .Net JSON API.

**Comment by rjmholt** [comment]
> We will consider this during migration to the new .Net JSON API.

Yeah this is the kind of change that would occur with that migration. In this case I think it's acceptable. Although perhaps in the case of something like comments in the JSON or trailing commas, we might have compatibility issues that we need to investigate.

**Comment by BrucePay** [comment]
Maybe we should add a '-Strict' flag.

**Comment by Serg046** [comment]
Duplication of https://github.com/PowerShell/PowerShell/issues/11117.
Newtonsoft.Json doesn't support trailing comma validation. If we need this, we will have to write a custom [JsonTextReader](https://github.com/JamesNK/Newtonsoft.Json/issues/818#issuecomment-452131435).

**Comment by iSazonov** [comment]
Dup #10628
