### ISSUE TITLE
Transcription Not Working in C#

### ISSUE THREAD

**Issue by pcarnella** [PowerShell/PowerShell#13785]
Transcription logging in PS7 is not working when hosted in C#/ASP.Net Core app.  I turned on central transcripting via the registry.  Interactive PS sessions work fine, but the hosted app running PS code does not generate any transcription logs.

## Steps to reproduce

Turn on transcripting in registry or group policy.
Set up a .Net core 3.1 app and add PS7 SDK.

## Expected behavior

I'd expect that any PS code running on the system, even in C# hosted app, would get transcription logged.

## Actual behavior

No logs being created for PS code running in .NetCore app

## Environment data
PS 7.03
.NetCore 3.1
Blazor server app
Hosted in IIS on Windows 2019 Core

**Comment by fMichaleczek** [comment]
@pcarnella Can you give output of $host inside your runspace ? transcription need the Console Host.

**Comment by pcarnella** [comment]
Hi, I just figured out it was a config issue.  I was putting the transcription reg keys under HKCU for the IIS app pool service account, but didn't have the app pool set to "load user profile".  Once I set load profile to true the logging started working as expected.
