### ISSUE TITLE
Use Nullable<T>.GetValueOrDefault()

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#13791]
We have over 270 uses where Nullable<T>.HasValue is before Nullable<T>.Value.
Most of these use cases could be replaced with Nullable<T>.GetValueOrDefault() in some way.
(It is not LINQ!)

https://github.com/dotnet/runtime/issues/33792

**Comment by georgettica** [comment]
can I give this a go?

**Comment by iSazonov** [comment]
@georgettica Yes, feel free to pull PR. No need to fix all at one PR - please keep PR as small as possible. I suggest you make only changes of the same type in one PR - there are many different patterns and I suggest to fix only one pattern per PR.

**Comment by georgettica** [comment]
wow! good job yall! I am gonna back off from the other PR's i've made and let you do your thing

**Comment by georgettica** [comment]
thanks for all your support @iSazonov 

and sry if I made you do double work

**Comment by daxian-dbw** [comment]
@iSazonov Please see my questions left in #13804 and #13793. It's not clear why changing in thsoe two places.

**Comment by daxian-dbw** [comment]
Quote my comment from https://github.com/PowerShell/PowerShell/pull/13804#discussion_r524868056:

>I think the comment https://github.com/dotnet/runtime/issues/33792#issuecomment-649665286 in that issue has a point. `.Value` is semantically more correct given that `HasValue` is already checked. There is a duplicate check on the boolean `hasvalue` field, but I don't think that affects the perf in practice.
>
>For places where we can use `GetValueOrDefault` to replace both `.HasValue` and `.Value`, it makes more sense to make the change, like in #13805 and #13808. But if we need to keep the `.HasValue` check, then I think using `.Value` afterwards is better.

**Comment by iSazonov** [comment]
I agree in common. Only there is another side - using different patterns decreases readability. I would prefer to use one pattern even though it looks unusual, especially since there are only a few of them in our code base. There is another reason why I prefer this. Now we often look at a code in .Net Runtime for a better understanding of how an application works and we consider this code as the best practice and high quality. Switching to a different code with a different style immediately causes discomfort. I believe that following .Net in this sense is the right direction - many of those who learn PowerShell code will be grateful to us.

**Comment by vexx32** [comment]
If we're going to use GetValueOrDefault() there, we shouldn't _also_ be checking HasValue. It's fine to use one or the other, but using both is duplicating the same checks unnecessarily.

**Comment by daxian-dbw** [comment]
> Only there is another side - using different patterns decreases readability.

This may be true to some syntax, but to `Nullable<T>.Value` and `Nullable<T>.GetValueOrDefault()`, I don't think readability would be affected given that the property/method names are so readable.

**Comment by iSazonov** [comment]
@vexx32 This could change execution logic - no value and default value can have different semantics in a code path.

**Comment by iSazonov** [comment]
> This may be true to some syntax

Yes, I say about common rule we could/should follow but there are always exceptions to rule. :-)

**Comment by daxian-dbw** [comment]
When the `.HasValue` check is necesary, I think we should keep using `.Value` afterwards. It's semantically more clear that "I want the current value, not the default value". When the `.HasValue` is unnecessary, it makes sense to use `.GetValueOrDefault()`, like in #13805 and #13808.

@iSazonov If you agree, I think we should revert  #13804 and #13793

**Comment by iSazonov** [comment]
I have no objection.

**Comment by xtqqczze** [comment]
In .NET 6.0, `Nullable<T>.Value` following `Nullable<T>.HasValue` has now been optimized in the JIT (dotnet/runtime#13699).

So we can close this issue and revert changes to use `GetValueOrDefault()` to the more natural form.

**Comment by xtqqczze** [comment]
@iSazonov Actually, there may still exist some patterns that could be optimised like in #13808, for example:

```csharp
bool M(bool? b) => b.HasValue && b.Value;
```

.NET 6.0.0 (6.0.21.37719), X64 RyuJIT
```assembly
; Program.M(System.Nullable`1<Boolean>)
       mov       [rsp+10],rdx
       cmp       byte ptr [rsp+10],0
       je        short M01_L00
       movzx     eax,byte ptr [rsp+11]
       ret
M01_L00:
       xor       eax,eax
       ret
; Total bytes of code 21
```

```csharp
bool N(bool? b) => b.GetValueOrDefault();
```

.NET 6.0.0 (6.0.21.37719), X64 RyuJIT
```assembly
; Program.N(System.Nullable`1<Boolean>)
       mov       [rsp+10],rdx
       movzx     eax,byte ptr [rsp+11]
       ret
; Total bytes of code 11
```

**Comment by iSazonov** [comment]
@xtqqczze The issue was more for cleanup and using right pattern than performance. For performance it is better to look and measure specific scenario.

**Comment by xtqqczze** [comment]
@iSazonov Unfortunately, most of @bcwood's PRs linked to this issue seem to have issues with change of logic. Could you please consider closing them and look at reverting #13849 as explained there: https://github.com/PowerShell/PowerShell/pull/13849#issuecomment-903717301.

**Comment by bcwood** [comment]
My apologies. I see what you're getting at with the change of logic. I'll close them for now until I have a chance to re-evaluate.
