### ISSUE TITLE
Add collection of all currently supported preference variables

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#13809]
## Summary of the new feature/enhancement
When running a script as a job using `Start-Job`, I'd like to pass all preference variables (like `$ProgressPreference`, `$ErrorActionPreference`,...) to the job scope. To do that, I need a list of all supported preference variables, as hardcoding this list or using `Get-Variable *Preference` is not a robust solution.

## Proposed technical implementation details (optional)
Expose a class, possibly similar to `[System.Management.Automation.Internal.CommonParameters]`, where the preference variables are listed.

**Comment by mklement0** [comment]
Good idea, but a duplicate of #4394
