### ISSUE TITLE
ForEach-Object -Parallel / Start-ThreadJob don't honor unsilencing of silent-by-default streams via common parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13816]
Inside a `ForEach-Object -Parallel` / `Start-ThreadJob` script block, passing common parameters `-Verbose`, `-Debug`, `-InformationAction Continue` does not make the respective stream output visible to the caller.

Workaround: set the corresponding preference variables in the _caller_'s scope.

## Steps to reproduce

```powershell
# Note: The same applies to Start-ThreadJob
1 | ForEach-Object -Parallel {
  Write-Host "host"
  Write-Output "Output"
  Write-Error "error"       
  Write-Warning "Warning"
  Write-Debug "debug" -Debug
  Write-Verbose "verbose" -Verbose
  Write-Information "information" -InformationAction Continue
}
```

## Expected behavior

All streams should produce output, as would be the case with `ForEach-Object` without `-Parallel` as well as with `Start-Job`:

```none
host
Output
Write-Error: error
WARNING: Warning
DEBUG: debug
VERBOSE: verbose
information
```

## Actual behavior

The verbose, debug, and information streams unexpectedly produce no output:

```none
host
Output
Write-Error: error
WARNING: Warning
```

## Environment data

```none
PowerShell Core 7.1.0-rc.1
```

**Comment by jaslawinMs** [comment]
Same for 7.1.1

**Comment by RandyInMarin** [comment]
This is the same in 7.1.3.  I worked around this by including  the following at the start of the script block.

```
-Parallel {
    $DebugPreference = $using:DebugPreference # bug work around
    $VerbosePreference = $using:VerbosePreference # bug work around
    $InformationPreference = $using:InformationPreference # bug work around
    ...
```

**Comment by mklement0** [comment]
@iSazonov, could you please label this for the appropriate WG? Thanks.

**Comment by iSazonov** [comment]
`Area-Cmdlets-Core` is best I can set. (This says the area is not classified in WG RFC for specific WG.)

**Comment by jaslawinMs** [comment]
I am not sure how relevant it is to this thread, but also -WhatIf does not propagate with -Parallel

**Comment by RandyInMarin** [comment]
@jaslawinMs Whatif being set to false is scary.  Let's see what files would be deleted using WhatIf.  Hum, that's a lot of large audit files.  I guess I better buy some extra backup space so that I can delete them without violating the law.

**Comment by RandyInMarin** [comment]
Simple demo

```$DebugPreference = 'Stop'
$VerbosePreference = 'Stop'
$ProgressPreference = 'Stop'
$InformationPreference = 'Stop'
$WarningPreference = 'Stop'
$ErrorActionPreference = 'Stop'
$WhatIfPreference = $true

$DebugPreference
$VerbosePreference
$ProgressPreference
$InformationPreference
$WarningPreference
$ErrorActionPreference
$WhatIfPreference

1 | ForEach-Object -Parallel {
    $_
    $DebugPreference
    $VerbosePreference
    $ProgressPreference
    $InformationPreference
    $WarningPreference
    $ErrorActionPreference
    $WhatIfPreference
}```

Stop
Stop
Stop
Stop
Stop
Stop
True
1
SilentlyContinue
SilentlyContinue
Continue        
SilentlyContinue
Continue        
Continue        
False

**Comment by Jaykul** [comment]
I'm not sure what's going on here, but it might be worth pointing out that the output _does_ come out:

If you run:

```PowerShell
$InformationPreference = "SilentlyContinue"
"Hello","Goodbye" | foreach -parallel {
    write-host $_
    invoke-command -Cn $Env:COMPUTERNAME -EnableNetworkAccess {
        write-host $args from $Env:ComputerName
    } -ArgumentList $_
} -iv drip

$drip | Format-Table * -force
```

You will actually see the greeting from Computername, like:
```
MessageData         Source     TimeGenerated        Tags
-----------         ------     -------------        ----
Hello               Write-Host 11/4/2022 1:38:25 AM {PSHOST}
Goodbye             Write-Host 11/4/2022 1:38:25 AM {PSHOST}
Hello from Tester   Write-Host 11/4/2022 1:38:29 AM {PSHOST, FORWARDED}
Goodbye from Tester Write-Host 11/4/2022 1:38:29 AM {PSHOST, FORWARDED}
```

So why isn't it being displayed by the host?

**Comment by RandyInMarin** [comment]
Why is this still open?  $WhatIfPreference is still being silently changed from $true to $false.  This is a bug that can potentially cause a lot of damage.  If nothing else is fixed, at least fix this.  

"Whatif correctly listed everything that needs to be done.  Cleanup after the big migration next month will be a really fast with your script.  This parallel stuff is great.  Hey, isn't that the CEO walking into the office?"
