### ISSUE TITLE
Script in StartupScripts

### ISSUE THREAD

**Issue by christophwille** [PowerShell/PowerShell#13812]
I initially opened a SO question at https://stackoverflow.com/questions/64424668/startupscripts-in-initialsessionstate-not-invoked-for-ps-core-runspacepool, but this is getting more and more into the developer realm.

Basically I have an InitialSessionState with an ImportPSModule, various Variables.Add and a StartupScripts.Add call. My expectation was that it being called "scripts", I could pass a script as string that uses the already executed import plus the variables that I set up. However, this continues to balk at me with 

System.Management.Automation.PSInvalidOperationException: 'Running startup script threw an error: The term 'Connect-ExchangeOnline -AppId $exoAppId -Organization $exoOrganization -Certificate $exoCertificate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again..

(Note that the very same script runs fine after PS.Create & assigning the runspace)

Looking at https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/InitialSessionState.cs#L2864 seems to indicate that it is all about commands, not scripts. True? Or am I missing a magical switch to make script run?

**Comment by vexx32** [comment]
Yeah, looks like "startup scripts" should probably be named "startup script _files_", it's really not looking like it's meant for anything other than that.

**Comment by christophwille** [comment]
Having it on-disk with a .ps1 extension works in that it imports the module first, sets the variables and then executes the script from the .ps1. Not having it on disk would be great though (not a huge issue in this specific case but in general I'd prefer to pass it directly via the code as a string).

**Comment by iSazonov** [comment]
This was discussed in #9734. It is "by-design". In the scenario you should use Commands.Add().

**Comment by christophwille** [comment]
But... Commands.Add() on InitialSessionState looks entirely different from AddCommand / Commands.Add in PS (SessionStateCommandEntry instead of Command/string). How would I pass say a Import-Module "ExchangeOnlineManagement"? (or the longer one that failed on me in the initial question: Connect-ExchangeOnline)

**Comment by iSazonov** [comment]
You can create a factory for creating PowerShell objects and initialize there.

**Comment by christophwille** [comment]
Is there some docs / samples that show this? Never heard of those ever, much less tried. Thanks!

**Comment by iSazonov** [comment]
@christophwille I guess you want to create an ISS with pre-defined state. In any case you will create a PowerShell object based on the ISS. If you create such PowerShell object in some code paths you should follow "dry" principle. As result you will create a method where you create ISS and then PowerShell object based on it. You can use the method everywhere. The method could be implemented in a static class - factory.

**Comment by christophwille** [comment]
Ok, misunderstanding then (I was expecting some sort of PS factory thingy). My use case again:

I am creating a RunspacePool with the ISS - and when I assign that pool to a newly created PS, I want each and every Runspace in that pool to be in a certain state (module loaded, ExO connected). That is what I try to achieve - and actually can do with StartupScripts and a script file on disk. 

You alluded to Commands.Add in ISS to be able to achieve the same thing. How?

**Comment by iSazonov** [comment]
@christophwille Thanks for sharing your scenario. I suggest to open new issue, describe your scenario with code example and a problem you ask to resolve.

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
