### ISSUE TITLE
IISAdministration 1.1.0.0 module on Powershell Core 7 missing Microsoft.Web.Administration

### ISSUE THREAD

**Issue by brettpostin** [PowerShell/PowerShell#13818]
I'm trying to deploy and use the IISAdministration module in Powershell Core 7.0.3.

Developing locally on a Windows 10 machine, the module works as expected. However when the same scripts are run on our servers we are seeing errors such as:
```
Line |
12:41:35:472 [ERR] 	  21 |  Import-Module IISAdministration
12:41:35:472 [ERR] 	     |  ~~~~~~~~~~~~~~~~~~~~~~~~~
12:41:35:472 [ERR] 	     | Could not load file or assembly 'Microsoft.Web.Administration,
12:41:35:472 [ERR] 	     | Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The
12:41:35:472 [ERR] 	     | system cannot find the file specified.
```

Much of the information I have read (e.g. [here](https://github.com/PowerShell/WindowsCompatibility/issues/84) and [here](https://github.com/PowerShell/PowerShell/issues/11792)) suggests the IISAdministration module does not work with Powershell Core.

However the following [article ](https://octopus.com/blog/iis-powershell#nano-server-broke-everything) suggests that the IISAdministration module has in fact been ported to Core.

I'm actually seeing both here. Downloading the module from the PSGallery the folder looks like this:

![image](https://user-images.githubusercontent.com/3657993/96597476-ca8d4a00-12e5-11eb-8417-0e52636b5350.png)

Whilst on my Windows 10 machine the module folder looks like this:

![image](https://user-images.githubusercontent.com/3657993/96597711-0d4f2200-12e6-11eb-9bd8-b26b78b59810.png)

Note that the Microsoft.Web.Administration DLL is included with the module. Also the ```IIISAdministration.psd1``` file includes the following:

```
@{
GUID='{07640789-476a-4713-a091-f5b365129c32}'
Author='Microsoft Corporation'
CompanyName='Microsoft Corporation'
Copyright='© Microsoft Corporation. All rights reserved.'
ModuleVersion='1.1.0.0'
PowerShellVersion = '5.1'
CLRVersion='4.0'
TypesToProcess='iiscommands.types.ps1xml'
FormatsToProcess='iiscommands.format.ps1xml'
RootModule='iisadministration.psm1'
NestedModules='Microsoft.IIS.Powershell.Commands.dll'
HelpInfoUri="http://go.microsoft.com/fwlink/?linkid=216321"
Description="IIS Configuration management module"
CompatiblePSEditions = @('Desktop', 'Core')               <--------------- SEE HERE
}
```

Clearly the module has been upgraded for Powershell Core, and it works as expected. My questions are...

1. Why is this version only available on my local Windows 10 machine and not the PSGallery?
2. Why do they share the same 1.1.0.0 version number?

**Comment by iSazonov** [comment]
You can ask about supporting Windows modules in https://github.com/PowerShell/PowerShellModuleCoverage
