### ISSUE TITLE
Dynamic parameter in multiple help files

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#13823]
I'm writing a module that implements a plug-in provider model like the PSProvider system. The core cmdlets can take dynamic parameters defined by the module implementing the provider. How do inform PowerShell that help for a dynamic parameter resides in another help file? I found that `RuntimeDefinedParameterDictionary` has a `HelpFile` property but no code references the property. Even if it did work I would be limited to only a single help file for a single module. I would need to support dynamic parameters from different help files.

The help system supports PSProviders by using the `ICmdletProviderSupportsHelp` interface but, is not generic for other provider like modules to make use of.

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/PseudoParameters.cs#L222-L230

**Comment by iSazonov** [comment]
At first look you need to implement custom HelpProvider.

**Comment by theJasonHelmick** [comment]
@ThomasNieto -- thank you for this issue.  The working group has reviewed this, and while it is possible to do this today, it requires writing your own custom MAML and then linking to the help files. We recommend the practice that we follow today, that you include the dynamic parameters in the standard help and call out that they are dynamically provided by your provider.

**Comment by ThomasNieto** [comment]
@theJasonHelmick that suggestion does not work, lets take PowerShell providers for example. If a third party creates a module lets say `SQLServer`. The PowerShell team would have to embed SQLServer module dynamic parameters into their standard parameter help for all users to see regardless if they have that module imported or not.

I did some research on the help system after creating this issue and it is unable to show dynamic parameters for a PSProvider when looking up parameter help for a command. For example `Set-Item` in the Registry provider. I even tested this example on PowerShell 2.0 before the uplift to updateable help and the migration to PlatyPS which no longer used the dedicated Provider MAML.

```powershell
PS HKLM:\> Get-Command Set-Item -Syntax

Set-Item [-Path] <string[]> [[-Value] <Object>] [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-Type <RegistryValueKind>] [<CommonParameters>]

Set-Item [[-Value] <Object>] -LiteralPath <string[]> [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-Type <RegistryValueKind>] [<CommonParameters>]

PS HKLM:\> Get-Help Set-Item -Path hklm:\ -Parameter Type
Get-Help: No parameter matches criteria Type.
```

I can create a separate issue but the request would be for the help system to show dynamic parameter help with the standard cmdlet parameter view for PSProviders and cmdlets that utilize dynamic parameters. This would also need the capability in this issue for the cmdlet to indicate which module (help file) to pull help from as the dynamic parameter and the help file could be shipped with a different module than the cmdlet help.
