### ISSUE TITLE
Wait-Event does not time out on Raspberry Pi

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13824]
The following test fails on Raspberry Pi in release automation:

https://github.com/PowerShell/PowerShell/blob/5b82b767558f682fef3ec53b5e5955981c2183ec/test/powershell/Modules/Microsoft.PowerShell.Utility/Wait-Event.Tests.ps1#L14

Error message:

```
Expected the actual value to be less than 1500, but got 2105.
```

**Comment by adityapatwardhan** [comment]
Things are sometime slower on RPi. This should be be a blocker.
