### ISSUE TITLE
ConvertTo-Json test for warning failing on Debian 11

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13827]
This test is failing on Debian 11:

https://github.com/PowerShell/PowerShell/blob/5b82b767558f682fef3ec53b5e5955981c2183ec/test/powershell/Modules/Microsoft.PowerShell.Utility/Json.Tests.ps1#L1467-L1472

Error message:

```
Expected a value, but got $null or empty.
```

**Comment by iSazonov** [comment]
What is line with error - 1470 or 1471?

I wonder - is it Newtonsoft Json.NET issue?

**Comment by rjmholt** [comment]
> What is line with error - 1470 or 1471?

1471
