### ISSUE TITLE
Nested Hashtable unexpected behaviour on Add

### ISSUE THREAD

**Issue by Paxilein** [PowerShell/PowerShell#13822]
One of my scripts is using a hashtable for settings for different environments and does a discovery of additional services if the setting is "all" (tried other values for that, no change).
In case of "all" the newly added hashtable will contain the default-values that are stored in the "all"-hashtable of the proper level.
The hashtable could instead of "all" also contain specific names for the environments or services in those. It's not always "all"...
So, when my script adds a new nested hashtable, that's a copy of the nested "all"-hashtble of that level the newly added nested hashtable is added to all hashtables of that level. Which is a weird behaviour imho...

Or I'm doing it wrong...

## Steps to reproduce

```powershell
$hashtable = @{
    "all" = @{
        "all" = @{
            "all" = @{
                value = 4000
            }
        }
    }
}

$hashtable.Add("env1", $hashtable.all)
$hashtable
    
#    Name                           Value
#    ----                           -----
#    env1                           {all}
#    all                            {all}
    
$hashtable.env1.Add("subenv1", $hashtable.env1.all)
$hashtable
    
#    Name                           Value
#    ----                           -----
#    env1                           {subenv1, all}
#    all                            {subenv1, all}
```

## Expected behavior

```none
Only add the new hashtable to the one I run the add-method on
```

## Actual behavior

```none
The new hashtable is added to all hashtables
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Paxilein** [comment]
Looks like I added my comments to the wrong part and it got removed....

One of my scripts is using a hashtable for settings for different environments and does a discovery of additional services if the setting is "all" (tried other values for that, no change).
In case of "all" the newly added hashtable will contain the default-values that are stored in the "all"-hashtable of the proper level. 
The hashtable could instead of "all" also contain specific names for the environments or services in those. It's not always "all"...
So, when my script add a new nested hashtable, that's a copy of the nested "all"-hashtble of that level the newly added nested hashtable is added o all hashtables of that level. Which is a weird behaviour imho...

Or I'm doing it wrong...

**Comment by Paxilein** [comment]
Looks like I have problems with Reference-Types.... The add copies the reference and not the values, so when I change the new env1 I change both as both are pointing to the same memory address...

**Comment by vexx32** [comment]
You can use `.Clone()` to copy the hashtable you're wanting to copy, but it only copies one level deep.
For nested hashtables you want to copy, you'll need to create a recursive cloning function, I think.

**Comment by Paxilein** [comment]
I actually tried the clone and it copies all nested hashtables and not only one level.... So that looks it that'll solve my problem!

Thanks @vexx32
