### ISSUE TITLE
TokenTraits.HasTrait gives unexpected results with Precedence flags

### ISSUE THREAD

**Issue by daviesj** [PowerShell/PowerShell#13820]
The function `TokenTraits.HasTrait(TokenKind, TokenFlags)` gives strange results for the BinaryPrecedence values of `TokenFlags`

For example, 
```powershell
[System.Management.Automation.Language.TokenTraits]::GetTraits([System.Management.Automation.Language.TokenKind]::Band)
```
returns `BinaryPrecedenceBitwise, BinaryOperator, CanConstantFold`. The [documentation ](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.language.tokentraits.hastrait?view=powershellsdk-7.0.0)on `TokenTraits.HasTrait` says: "Return true if the TokenKind has the given trait." Therefore I would expect `HasTrait` to return `true` only for those three values of `TokenFlags`. However:

## Steps to reproduce

```powershell
 [System.Management.Automation.Language.TokenTraits]::HasTrait([System.Management.Automation.Language.TokenKind]::Band,[System.Management.Automation.Language.TokenFlags]::BinaryPrecedenceMultiply)
```

## Expected behavior

```none
False
```

## Actual behavior

```none
True
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Discovered this while trying to work out why the PSScriptAnalyzer rule UseConsistentWhitespace seems to apply to some random set of operators and not to others. After really digging in, it appears the author of the logic for operators in this rule only [intended to implement logic for assignment or arithmetic operators](https://github.com/PowerShell/PSScriptAnalyzer/blob/8c5a6388cc121c8308217039e9d1f9bba4aa4ff2/Rules/Strings.resx#L982). However it appears that person made the same assumption I would that `HasTrait` ought to work on the BinaryPrecedence flags and therefore [used it in attempt to detect all operators with equal precedence to Add or Multiply](https://github.com/PowerShell/PSScriptAnalyzer/blob/8c5a6388cc121c8308217039e9d1f9bba4aa4ff2/Rules/UseConsistentWhitespace.cs#L189).

**Comment by vexx32** [comment]
`BinaryPrecedenceMultiply` is not one of the token flags that `-band` has.

https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.language.tokenflags?view=powershellsdk-7.0.0

It's also not in the list you get back from your initial command?

**Comment by SeeminglyScience** [comment]
Only the later half of the `TokenFlags` enum are actually bit flags. Testing for specific `BinaryPrecedence*` entries should be done like this:

```csharp
(flags & TokenFlags.BinaryPrecedenceMask) is TokenFlags.BinaryPrecedenceMultiply
```

`HasTrait` should probably be updated to account for that.

**Comment by iSazonov** [comment]
The method is public so it would be a breaking change.
It is used 15 times internally so current behavior is" by-design".

**Comment by SeeminglyScience** [comment]
> The method is public so it would be a breaking change.

I can't think of a scenario where someone would depend on this?  Even as a work around? Genuine question as that was my first thought too but I can't come up with even a stretch of a scenario.

> It is used 15 times internally so current behavior is" by-design".

Never with a `BinaryPrecedence*` value though, there's a separate internal method for that because it doesn't work.

**Comment by SeeminglyScience** [comment]
For clarity, here's what the enum looks like:

```python
    Enum: System.Management.Automation.Language.TokenFlags (int) 🚩

   Value Name                      Hex        Bits
   ----- ----                      ---        ----
       0 None                      0x0000000  0000.0000 0000.0000 0000.0000 0000.0000
       1 BinaryPrecedenceLogical   0x0000001  0000.0000 0000.0000 0000.0000 0000.0001
       2 BinaryPrecedenceBitwise   0x0000002  0000.0000 0000.0000 0000.0000 0000.0010
       5 BinaryPrecedenceComparis… 0x0000005  0000.0000 0000.0000 0000.0000 0000.0101
       7 BinaryPrecedenceCoalesce  0x0000007  0000.0000 0000.0000 0000.0000 0000.0111
       9 BinaryPrecedenceAdd       0x0000009  0000.0000 0000.0000 0000.0000 0000.1001
      10 BinaryPrecedenceMultiply  0x000000A  0000.0000 0000.0000 0000.0000 0000.1010
      12 BinaryPrecedenceFormat    0x000000C  0000.0000 0000.0000 0000.0000 0000.1100
      13 BinaryPrecedenceRange     0x000000D  0000.0000 0000.0000 0000.0000 0000.1101
      15 BinaryPrecedenceMask      0x000000F  0000.0000 0000.0000 0000.0000 0000.1111
      16 Keyword                   0x0000010  0000.0000 0000.0000 0000.0000 0001.0000
      32 ScriptBlockBlockName      0x0000020  0000.0000 0000.0000 0000.0000 0010.0000
     256 BinaryOperator            0x0000100  0000.0000 0000.0000 0000.0001 0000.0000
     512 UnaryOperator             0x0000200  0000.0000 0000.0000 0000.0010 0000.0000
    1024 CaseSensitiveOperator     0x0000400  0000.0000 0000.0000 0000.0100 0000.0000
    2048 TernaryOperator           0x0000800  0000.0000 0000.0000 0000.1000 0000.0000
    4096 SpecialOperator           0x0001000  0000.0000 0000.0000 0001.0000 0000.0000
    8192 AssignmentOperator        0x0002000  0000.0000 0000.0000 0010.0000 0000.0000
   32768 ParseModeInvariant        0x0008000  0000.0000 0000.0000 1000.0000 0000.0000
   65536 TokenInError              0x0010000  0000.0000 0000.0001 0000.0000 0000.0000
  131072 DisallowedInRestrictedMo… 0x0020000  0000.0000 0000.0010 0000.0000 0000.0000
  262144 PrefixOrPostfixOperator   0x0040000  0000.0000 0000.0100 0000.0000 0000.0000
  524288 CommandName               0x0080000  0000.0000 0000.1000 0000.0000 0000.0000
 1048576 MemberName                0x0100000  0000.0000 0001.0000 0000.0000 0000.0000
 2097152 TypeName                  0x0200000  0000.0000 0010.0000 0000.0000 0000.0000
 4194304 AttributeName             0x0400000  0000.0000 0100.0000 0000.0000 0000.0000
 8388608 CanConstantFold           0x0800000  0000.0000 1000.0000 0000.0000 0000.0000
16777216 StatementDoesntSupportAt… 0x1000000  0000.0001 0000.0000 0000.0000 0000.0000
```

**Comment by daviesj** [comment]
> 
> 
> > The method is public so it would be a breaking change.
> 
> Can you think of a scenario where someone would depend on this? Even as a work around? Genuine question as that was my first thought too but I can't come up with even a stretch of a scenario.

I hope someone wouldn't be depending on relationships in the bit patterns of `BinaryPrecedence*` values, especially since the numeric values themselves have changed. However, if it is too great of a change then I recommend at least adding to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.language.tokentraits?view=powershellsdk-7.0.0) that `HasTrait` is only valid for `TokenFlags` values which are bit flags.

Given that `token.TokenFlags` cannot be trusted (#10348), at least for operators, it seems one has to rely on `token.Kind` and use `TokenTraits` functions to detect types of operator tokens. When an API user sees there is a `HasTrait` function, and there is no documented reason not to use it, the natural assumption is that you should use it because the API developers know better than you how to determine whether or not a `TokenKind` has a trait.

**Comment by iSazonov** [comment]
> However, if it is too great of a change then I recommend at least adding to the documentation that HasTrait is only valid for TokenFlags values which are bit flags.

@daviesj You could open new issue in PowerShell-Docs repo or pull a PR there.

/cc @msftrncs

/cc @daxian-dbw
