### ISSUE TITLE
Updatable help web validation test fails on Windows Server 2016

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#13828]
The test to validate that `Update-Help` has worked based on a web query is failing on Windows Server 2016 here:

https://github.com/PowerShell/PowerShell/blob/5b82b767558f682fef3ec53b5e5955981c2183ec/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1#L181

Error message:

```
Expected 2, but got 0.
```

**Comment by iSazonov** [comment]
What is moduleName and UserScope in the failed test?

**Comment by rjmholt** [comment]
Also failing on RaspberryPi for 7.1.2

**Comment by anmenaga** [comment]
Also failing on "centos8_LTS - Elevated" config.
```
Error message
Expected 1, but got 0.

Stack trace
at <ScriptBlock>, /home/cloudtest_azpcontainer/PSPackage/download/Test/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1: line 181
181:     $helpFilesInstalled.Count | Should -Be $expectedHelpFiles.Count
```
