### ISSUE TITLE
Make meaningless [pscustomobject] casts report an error

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13836]
## Summary of the new feature/enhancement

As a user, I want to be notified when a cast doesn't work as intended:

```powershell
# OK - a statement-terminating error occurs if the operand cannot be cast to [int]
PS> [int] 'Not a number.'
InvalidArgument: Cannot convert value "Not a number." to type "System.Int32". Error: "Input string was not in a correct format."
```

However, this doesn't currently work as intended with a `[pscustomobject]` cast:

```powershell
# A meaningless cast:
# !! Seemingly quietly ignored - in reality, the operand is simply wrapped in [psobject](!)
PS> [pscustomobject] 42
42
```

Unexpectedly, the above is equivalent to `[psobject] 42` and wraps the operand  in a large largely invisible `[psobject]` instance (except it isn't _always_ invisible - see #5579).
While the utility of such a cast with `[psobject]` is questionably in itself, with `[pscustomobject]` it is downright puzzling (and even though _both_ type accelerators refer to `System.Management.Automation.PSObject`, PowerShell can and does treat them differently with a hashtable operand (see below)).

The only meaningful use of a `[pscustomobject]` cast is (currently) the _syntactic sugar_ supported with a single (ordered) `[hashtable]` operand, to convert a hash table to a custom object; e.g., `[pscustomobject] @{ one = 1; two = 2 }` (Sadly,  it doesn't work with  a generic ``Dictionary`2`` instance, though #13727 may change that; it also doesn't currently work as an _array_ cast - see #13838).

All other uses should report a statement-terminating error.

Note: While this is technically a breaking change, existing instances of such casts amount to already broken code.

**Comment by iSazonov** [comment]
> Unexpectedly, the above is equivalent to [psobject] 42 and wraps the operand in a large largely invisible [psobject] instance (except it isn't always invisible - see #5579).

Oh, I guess it is fundamental PowerShell behavior. It seems there was very old PR for this.
