### ISSUE TITLE
pwsh.exe -command , parameter order and help text. 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#13832]
Looking at #13831  I found something which may have been logged before but I can find it so if this is duplicate, please close 

To test that problem I ran   `pwsh -c "write-host asd"` and got the expected response. 

```
Setting-up Paths, Prompt and History. Redefining CD and h, Defining Whathas, HowLong,  Edit, Elevate, TS, Show-Help.
asd
```
I then called up the previous line and added a switch to get this  ` pwsh -c "write-host asd" -noprofile`

```
Setting-up Paths, Prompt and History. Redefining CD and h, Defining Whathas, HowLong,  Edit, Elevate, TS, Show-Help.
asd -noprofile
```

Everything after `-c` is treated as an argument for the command.  And **this is OK. People probably rely on it** the same probably applies with a `-file` argument as well 

however the help text reads
```
Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
                  [-ConfigurationName <string>] [-CustomPipeName <string>]
                  [-EncodedCommand <Base64EncodedCommand>]
                  [-ExecutionPolicy <ExecutionPolicy>] [-InputFormat {Text | XML}]
                  [-Interactive] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
                  [-OutputFormat {Text | XML}] [-SettingsFile <filePath>] [-STA] [-Version]
                  [-WindowStyle <style>] [-WorkingDirectory <directoryPath>]
```

This bit of BNF (I think it is BNF, but I haven't really worked with that since I finished my degree in the 1980s!)
```
-Command { - | <script-block> [-args <arg-array>]  | <string> [<CommandParameters>] } ]
```
says that if -`command` comes before the others they will morph into command parameters, **but** I read the whole things as saying `-NoExit`, `-NoProfile` etc are optional after -`command <string>`  I'll defer to  anyone with more recent knowledge on the grammar, but most readers will infer that the sequence is valid as shown. 

## Steps to reproduce

```powershell
pwsh -c "write-host Hello" -Noexit
```
or

```powershell
pwsh -c "write-host Hello" -NoProfile
```

## Expected behavior

```none
Hello
```

## Actual behavior

```none
Hello -Noexit
```
or 

```none
xxxx Profile message xxxx
Hello -NoProfile
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
While the description in the help topic is clear about everything after `-c` / `-Command` becoming an argument to that parameter, it definitely makes sense to reflect that in the syntax diagram too, by placing it _last_.

The conceptual challenge here is that users will generally not expect the order of _named_ arguments to matter, but they do here. Making that clear in the help as well as _hinting_ at it in the diagram as described is probably the best we can do.  

(There is nothing in the notation that supports the must-go-last concept, and given that it is an _exception_ I don't think it's worth trying to introduce one.)

**Comment by SeeminglyScience** [comment]
Slightly pedantic but they aren't added as arguments, they're directly appended to `Command`:

```powershell
# This would be a syntax error, but instead we get command not found
pwsh -nop -c 'echo test |' -Something
# -Something: The term '-Something' is not recognized as a name of a cmdlet, function, script file, or executable program.
# Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

(@mklement0 I know you're saying this as well, I just want to stress the difference because it was confusing to me at first)

**Comment by mklement0** [comment]
@SeeminglyScience, yes, thanks for the clarification; specifically, what are technically separate arguments are space-concatenated, and the resulting string is then evaluated as PowerShell code.

In other words: instead of conceiving of the _first_ `-c` argument as a mini-script to which the remaining arguments are passed as arguments _for that mini-script_, _all_ `-c` arguments - however, partitioned - are stitched together and then as a whole interpreted as a script.

Here's another head scratcher:

```powershell
PS> pwsh -nop -c echo "one, two" # evaluated as: `echo one, two`  i.e. a 2-element array
one
two
```

It isn't just confusing, it limits functionality (you can't pass verbatim arguments, because everything is interpreted by PowerShell rules) and it is also at odds with how POSIX-compatible shells do it - see https://github.com/PowerShell/PowerShell/issues/4024#issuecomment-311541803

**Comment by jhoneill** [comment]
> (There is nothing in the notation that supports the must-go-last concept, and given that it is an _exception_ I don't think it's worth trying to introduce one.)

Like I said my knowledge of these notations has 30 years of rust on it but I **think** as it is written it implies.  `Login` (if  it appears) goes before `File `(if it appears), which goes before `command` (if it appears) which goes before `ConfigurationName`   etc.  
I can't remember a wrapper for saying "The _following in any order_" , it's _custom and practice_ in the PowerShell world that applies that to named parameters, it's not always true for .EXEs.

**Comment by mklement0** [comment]
@jhoneill, https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Command_Syntax?view=powershell-7.1 doesn't give the notation a name, and I don't think we need to worry about what _formal_ notation (such as BNF, which it certainly looks like) it derives from:

It's a notation that needs to make sense to the human observer (and, as an aside, with its current formatting it doesn't do a great job at that: see #4135, #4626, #4715, #6856, #7868, #8692)

De facto, with justification, users expect the order of _named_ arguments _not_ to matter, **they are used to reading the diagrams as _not_ being meaningful in terms of the order in which the parameters are listed**, irrespective of what the underlying formal notation may imply, except perhaps for an expectation of a  _meaningful-for-human-comprehension-but-technically-incidental_ ordering .

There are only two exceptional cases where the position of an (ostensible) named argument matters:

* In the CLI, with `-c` / `-Command`, as discussed here.

* If you disable named argument parsing with `--` (e.g., `Write-Output -- -NoEnumerate`)
  * (`--%` isn't really a parameter and only applies to external programs, which don't generally understand PowerShell's notion of named parameters anyway)

Therefore, except for the subtle hint of listing `-Command` last in this particular case, the notation won't help, and the burden falls on the _description_, which currently states:

```none
If the value of Command is a string, Command must be the last parameter for
    pwsh, because all arguments following it are interpreted as part of the
    command to execute.
```

While this is pretty clear, it may make sense:

*  to move it to (near) the _start_ of the parameter description

* to also provide a brief hint _directly underneath the syntax diagram_.

**Comment by mklement0** [comment]
P.S., @SeeminglyScience, the current `-c` behavior is also notable for the asymmetry between the script-block and the string form:

You can do `pwsh -nop -c { $args.Count } -args foo, bar`, but not `pwsh -nop -c '$args.Count' foo bar`. From _within_ PowerShell, that is not a hardship, because the script-block form is superior both syntactically with respect to (limited) rich type support, but from _outside_ PowerShell you're stuck with the string syntax and its limitations.

The current syntax diagram snippet for the _string_ form of `-c` - ` <string> [<CommandParameters>]` - somewhat misleadingly suggests that `<string>` is merely a _command name_, even though you can obviously pass entire statements. 

More importantly, even if you do just pass a single command name, such as in the `pwsh -nop -c echo "one, two"` example above, the arguments won't work as expected.

**Comment by jhoneill** [comment]
@mklement0  yes, agree. 



> De facto, with justification, users expect the order of _named_ arguments _not_ to matter, **they are used to reading the diagrams as _not_ being meaningful in terms of the order in which the parameters are listed, except for _positional_ use** 

Yes . especially as, that



> @jhoneill, https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Command_Syntax?view=powershell-7.1 
> There are only two exceptional cases where the position of an (ostensible) named argument matters:
> 
> * In the CLI, with `-c` / `-Command`, as discussed here.
> * If you disable named argument parsing with `--` (e.g., `Write-Output -- -NoEnumerate`)
>   
>   * (`--%` isn't really a parameter and only applies to external programs, which don't generally understand PowerShell's notion of named parameters anyway)
> 
> Therefore, except for the subtle hint of listing `-Command` last in this particular case, the notation won't help, and the burden falls on the _description_, which currently states:
> 
> ```
> If the value of Command is a string, Command must be the last parameter for
>     pwsh, because all arguments following it are interpreted as part of the
>     command to execute.
> ```
> 
> While this is pretty clear, it may make sense:
> 
> * to move it to (near) the _start_ of the parameter description
> * to also provide a brief hint _directly underneath the syntax diagram_.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/30b871356ed593efa4de9654481182695e3d4aa1/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f6d656469612f6c6f676f732f6c6f676f2d706f7765727368656c6c2d736f6369616c2e706e67">**[about_Command_Syntax - PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_syntax)**Describes the syntax diagrams that are used in PowerShell.

**Comment by mklement0** [comment]
> However exes are on internal to PowerShel

I didn't get that.

> if the user reads about_pwsh instead of running pwsh /? 

These are kept in sync, so there should be no contradiction.
(And I don't think the exception is worth mentioning in  `about_Command_Syntax`.)

**Comment by jhoneill** [comment]
> > However exes are on internal to PowerShel
> 
> I didn't get that.
> 
> > if the user reads about_pwsh instead of running pwsh /?
> 
> These are kept in sync, so there should be no contradiction.
> (And I don't think the exception is worth mentioning in `about_Command_Syntax`.)

Typo sorry.   There's a distinction between functions and cmdlets (named parameters can be in any order) and external programs where it's not guaranteed.  What I meant was  "that only applies to commands internal to PowerShell (which exes are _NOT_)" and the word not got tangled.   

pwsh /? is a subset of what is in the about help. IF someone reads the section on the -command parameter in  about_pwsh  that contradicts what is said in about_command_syntax (because the latter doesn't apply to EXEs and the former is talking about an EXE). 

Sorry, made a pig's ear of saying it the first time.

**Comment by mklement0** [comment]
I see.

> pwsh /? is a subset of what is in the about help.

Formatting differences and section headings aside, the content looks the same to me.

At this point I'm unclear what you're suggesting:

* The suggestions [above](https://github.com/PowerShell/PowerShell/issues/13832#issuecomment-714552773) would improve the `pwsh -?` text / `about_pwsh` topics in isolation.

* Are you saying something is needed in addition, in `about_command_syntax`? I suppose it wouldn't hurt to mention there that these diagrams only apply to PowerShell-native commands, and that for external programs `-?` cannot be expected to work and that `Get-Help <external-program>` never works (except with `pwsh`) and that  `Get-Command -Syntax <external-program>`  prints just the executable's full path (which isn't great, at least an abstract placeholder for the unknown syntax would help), including for `pwsh`.

**Comment by jhoneill** [comment]
> I see.
> 
> > pwsh /? is a subset of what is in the about help.
> 
> Formatting differences and section headings aside, the content looks the same to me.
> 


Now I'm suffering machine specific weirdness. because NOW I get the whole of the About when I run pwsh /? previously I only got the the syntax diagram as I cut and pasted in the first post.
