### ISSUE TITLE
Write-Host not found

### ISSUE THREAD

**Issue by gabyx** [PowerShell/PowerShell#13831]
## Steps to reproduce

```powershell
pwsh -Command "Write-Host asd"
```

## Expected behavior
Writes the following to the console:
```none
asd
```

## Actual behavior
Outputs 
```none
ResourceUnavailable: Program 'Write-Host' failed to run: No application is associated with 
the specified file for this operation.At line:1 char:1    
+ Write-Host asd                                                                                                        
+ ~~~~~~~~~~~~~~.
```

Note: `Write-Output` works! but `Write-Host` not??

## Environment data

`Get-Module -Name Microsoft.Powershell.Utility'` is installed:
```none
ModuleType Version    Name                                ExportedCommands 
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}   
```

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
It works for me. 
```
> pwsh -c "write-host asd"
Setting-up Paths, Prompt and History. Redefining CD and h, Defining Whathas, HowLong,  Edit, Elevate, TS, Show-Help.
asd
```
Which makes me wonder if the is something in your profile causing it . try   `pwsh -NoProfile -c "write-host asd"`

**Comment by gabyx** [comment]
Jeah its a really shitty weird problem:

Starting powershell.exe and executing `pwsh -NoProfile -c "write-host asd"` results in the same error.

**Comment by gabyx** [comment]
It also does not work in "powershell.exe" (not core)

**Comment by vexx32** [comment]
Are you running 32 bit Windows / 32 bit PowerShell/pwsh?

Wondering if perhaps the assemblies we're shipping for the modules are not 32-bit and the 32-bit version of the application doesn't load them correctly.

**Comment by SeeminglyScience** [comment]
What happens if you do `pwsh -c "Get-Command Write-Host"`

**Comment by gabyx** [comment]
its all 64bit:
`pwsh -c "Get-Command Write-Host"`: 

```none
PS C:\Users\gabriel.nuetzi> pwsh -c "Get-Command Write-Host"

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     Write-Host                                         0.0.0.0    C:\Windows\system32\Write-Host
```

**Comment by gabyx** [comment]
Strange its an empty file...

**Comment by gabyx** [comment]
Oh, my god, how could this happen it was an empty file (maybe generated out of an error or something) I deleted the thing. Now it works. Sorry for this!

**Comment by SeeminglyScience** [comment]
No worries, someone at some point probably tried `SomeCommand > Write-Host`.  Happens more often than you'd think 😁

**Comment by gabyx** [comment]
Probably was exactly the case in Admin mode dam....
