### ISSUE TITLE
UNC: Unable to `Set-Location \`

### ISSUE THREAD

**Issue by 9Rune5** [PowerShell/PowerShell#13854]
## Steps to reproduce

```powershell
Set-Location \\stallbacka\home\config
# works okay -- $PWD is now \\stallbacka\home\config
Set-Location \
```

## Expected behavior

```none
$PWD should report \\stallbacka\home (the UNC root)
```

## Actual behavior

```none
Set-Location: Cannot find path 'Microsoft.PowerShell.Core\FileSystem::' because it does not exist.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Interestingly the builtin function `cd\` does seem to work. So clearly this is possible, I'm just unsure why the cmdlet itself is not doing the same expected thing here.

**Comment by vexx32** [comment]
I take it back, `Set-Location \` is working just fine (the builtin function I mentioned just calls that directly).

Can you try to reproduce on the 7.2 RC version?

**Comment by 9Rune5** [comment]
The newest prerelease I could find was 7.1.0-rc.2.

Same issue.

I also tried to not import any packages in my $profile. And I tried this on my laptop.

**Comment by jborean93** [comment]
I can only replicate this once I set the location to a UNC path and then `\`. It sounds like `\` has special logic to mean the root of the current "drive" and you cannot connect to `\\server` or just `\\` as they don't exist/not valid.

**Comment by 9Rune5** [comment]
"I can only replicate this once I set the location to a UNC path and then \"

That was kind of the point?

If you set a UNC path as working directory, you can no longer cd \.

**Comment by vexx32** [comment]
Thanks for clarifying! Looks like an issue with how the filesystem provider determines the root directory from the current location for UNC paths, then.

**Comment by 9Rune5** [comment]
Thank you.

I suspect it affects other operations. While moving a bunch of files, I accidentally did `move something.ext \` and the file wound up in my home directory rather than the root. But I have not been able to reproduce that. Will file a separate issue once I recall the circumstances. (I was probably targetting a folder off root)

**Comment by jborean93** [comment]
> That was kind of the point?

Just merely clarifying that this was key to replicating the issue :) venxx32 was having troubles trying to replicate it and thought it best to mention the UNC part of your example was important.

**Comment by tolgabalci** [comment]
I can replicate the issue after doing the following:
Get-Item c:\Windows | Set-Location
![image](https://user-images.githubusercontent.com/2467618/174707675-4e16b4a2-28b4-4b89-966b-7f8b185b05b2.png)

This was part of a pipeline I have that at the end needs to set to Set-Location to the directory selected.

**Comment by tolgabalci** [comment]
Issue still exists in 7.4.0.  For some reason, Set-Location treats the Path from the pipeline differently.

This works fine:
![image](https://github.com/PowerShell/PowerShell/assets/2467618/ccfa5e32-b36a-4da2-912c-8ac1eca6af6d)


This does not:
![image](https://github.com/PowerShell/PowerShell/assets/2467618/37c557b5-efb4-4b7f-bf03-8049ef3c8121)
