### ISSUE TITLE
Cursor not move to end when press up arrow(last command)

### ISSUE THREAD

**Issue by seanmars** [PowerShell/PowerShell#13851]
## Steps to reproduce

1. input some command(or any thing)
2. press enter
3. press up arrow

## Expected behavior

```none
Get the last input and cursor move to end.
```

## Actual behavior

```none
Get the last input and cursor stay on begin.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Could you check with latest buids PowerShell 7.1 RC and PSReadline 2.1 RC?

**Comment by seanmars** [comment]
> Could you check with latest buids PowerShell 7.1 RC and PSReadline 2.1 RC?

Get the same issue in PowerShell v7.1.0-rc.2

**Comment by seanmars** [comment]
Ok, I found out the problem.
I forgot to check the profile. I setting the `PSReadlineKeyHandler` for some reason.
```ps
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
```
I comment this two line setting and the issue is gone.
