### ISSUE TITLE
How do I uninstall powershell

### ISSUE THREAD

**Issue by Kagreiss** [PowerShell/PowerShell#13864]

**Comment by Kagreiss** [comment]
I believe someone installed this on my device and I don't know how to remove

**Comment by IISResetMe** [comment]
@Kagreiss Is the issue that you have PowerShell installed on your computer? Windows comes with a previous version of PowerShell installed out of the box, so if you're on Windows and find an installation of Windows PowerShell, that's completely expected.

Please share details about which operating system and version you're on and what exactly it is that you believe has been installed :)

**Comment by TravisEz13** [comment]
No security issue reported.

**Comment by TravisEz13** [comment]
I recommend re-filing with the Bug report template.  It tries to gather what is needed to answer this type of question.
https://github.com/PowerShell/PowerShell/issues/new?assignees=&labels=Issue-Question&template=Bug_Report.md&title=My+bug+report
