### ISSUE TITLE
Support hashtable initializers for all IDictionary types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13873]
## Summary of the new feature/enhancement

.NET offers a number of specialized dictionary types that all implement the `IDictionary` interface.
`[hashtable]` (and `[ordered]` (`System.Collections.Specialized.OrderedDictionary`)) conveniently have a literal syntax in PowerShell, but it would be nice if other types of dictionaries could be _initialized_ via such a hashtable literal (`@{ ... }`):

The following, which initializes a non-generic sorted dictionary (a list that also acts as a dictionary) already works:

```powershell
# OK, for this specific type:
PS> [System.Collections.SortedList] @{ one = 1; two = 2 }

Name                           Value
----                           -----
one                            1
two                            2
```

The following are examples of other `IDictionary`-implementing types that do NOT work, but it would be nice if they did:

```powershell
[System.Collections.Generic.SortedList[string, int]] @{ one = 1; two = 2 }
[System.Collections.Generic.SortedDictionary[string, int]] @{ one = 1; two = 2 }
[System.Collections.Generic.Dictionary[string, int]] @{ one = 1; two = 2 }
```

**Comment by iRon7** [comment]
I wonder where this ends...
What about a [`[HashSet]`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=netcore-3.1):
```PowerShell
[System.Collections.Generic.HashSet[string]]@('one', 'two', 'three')
```
Which is lighter then creating a `[Hashtable]` and setting the values to `$True` (which is often done)

**Comment by mklement0** [comment]
@iRon7, as your sample command shows, initialization of a `HashSet` by a literal is already supported, namely via an _array_ - which is good to know. Also, note that `HashSet` doesn't implement `IDictionary`.

**Comment by iRon7** [comment]
I thought that a `[HashSet]` was (binary) indexed and an `[Array]` not...

**Comment by vexx32** [comment]
Don't think you can actually index a hashset directly at all, at least I don't see an obvious way to do so. You can add or remove values and check if things are already inside it, or iterate the entire contents, but I don't see a way to index into it and grab specific items directly.

**Comment by mklement0** [comment]
Indeed, `HashSet<T>` is unordered, so no positional indexing; use `.Contains()` or call `.Add()` and infer from the return value whether the element was already present.

While the related `SortedSet<T>` does maintain (sort) order, it too doesn't support indexing directly; you can work around it with LINQ, but the data structure isn't designed to be accessed by index efficiently (see https://stackoverflow.com/a/20691991/45375):

```powershell
PS> [System.Linq.Enumerable]::ElementAt([System.Collections.Generic.SortedSet[string]] ('one', 'two', 'three'), 1)
three # The 2nd element from the *sorted* set.
```

**Comment by iRon7** [comment]
> Also, note that HashSet doesn't implement IDictionary

**Correct**, I was wrong there.

Anyways, I can't find a use case in StackOverflow, but let's assume I have a bunce of file names and I want to (quickly) check if they exists in my system. (_I don't care where the reside, I just want to no if they whether they exist or not._). For this I could setup a hash table and populate it like `$HashTable[$Filename] = $True` and later check on the file name like `$HashTable.ContainsKey($FileName)` whether it exists but as the value isn't important in this situation, I could also use a `HashSet` (using `$HashSet.Add($Filename) ` and `$HashSet.Contains($Filename)` instead, knowing that a hashset is a lot faster than an array:

```PowerShell
$a = 1..50000 | % { 2 * $_ }
$h = [System.Collections.Generic.HashSet[int]]$a

(Measure-Command {
    Foreach ($i in 1..100000) { $a.Contains($i) }
}).TotalMilliseconds
16951.9234

(Measure-Command {
    Foreach ($i in 1..100000) { $h.Contains($i) }
}).TotalMilliseconds
109.6677
```
See also: [Optimize for extremely large hash tables?](https://stackoverflow.com/a/9550654/1701026)

**Comment by mklement0** [comment]
That's good to know, @iRon7, but it is still unrelated to this proposal, which is about types implementing the `IDictionary` interface.

**Comment by iRon7** [comment]
You're right, I actually thought that you question implied to add the concerned types to the accelerated types which is not the case. I have hidden my comments.
