### ISSUE TITLE
Create an attribute for cmdlets used to enumerate the error types returned

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#13882]
## Summary of the new feature/enhancement

Currently our documentation contains information about the object types returned as output. There is no equivalent feature for the error types and values returned. If an attribute like this existed, error types could be discovered programatically. Platyps could output the error information to the cmdlet documentation.

It would be worthwhile to enumerate all the specific ErrorRecords that a cmdlet returns. We should also add some language that other exceptions may be raised by underlying providers or API interfaces.

The error documentation has been requested by end users. See https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6797.

**Comment by vexx32** [comment]
Clarification point: all ErrorRecords are the same type. Typically they can be differentiated by one or more of:

- Exception type
- ErrorId string
- ErrorCategory

I think both exception type and ErrorId would be a good thing to add in terms of metadata.

**Comment by iSazonov** [comment]
If I remember correctly Jason Shirk once noted that errors/exceptions were never a public contract in PowerShell.

I even assume that we do not cover most of them with tests.

And before documenting, we would have to put them in order, which looks like a lot of work.
