### ISSUE TITLE
Fix CA2208: Instantiate argument exceptions correctly

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13909]
_Tracking issue._

 Various [CA2208: Instantiate argument exceptions correctly](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208) rule violations are suppressed in #13898.

**Comment by iSazonov** [comment]
At first look we use standard .Net exception classes inappropriately. Perhaps we should create our own classes for such cases.

**Comment by xtqqczze** [comment]
@iSazonov Please reopen.
