### ISSUE TITLE
[Microsoft.Powershell.SDK]An error occured while use the result of New-CsOnlineSession to Import-PsSession

### ISSUE THREAD

**Issue by luso0823** [PowerShell/PowerShell#13903]
`
                PSObject psSession = null;
                using (var ps = PowerShell.Create())
                {
                    ps.Runspace = runspace;
                    ps.AddCommand(@"New-CsOnlineSession")
                        .AddParameter("Credential", CreatePSCredential());

                    Console.WriteLine("----------------------    New-CsOnlineSession    -------------------------");
                    psSession = ps.Invoke().FirstOrDefault();
                }
                using (var ps = PowerShell.Create())
                {
                    ps.Runspace = runspace;
                    ps.AddCommand(@"Import-PsSession").AddParameter("Session",psSession);
                    Console.WriteLine("----------------------    Import-PSSession   -------------------------");
                    var results = ps.Invoke();
                    results.ToList().ForEach(x =>
                    {
                        Console.WriteLine(JsonConvert.SerializeObject(x));
                    });
                }
`

I want to use Power shell with C# Code to manager Teams policies Settings,so i choose Microsoft.PowerShell.SDK 7.0.3 + .net core 3.1 to fix it.But when i user PowerShell in .net core 3.1 Console Application with Nuget package:(Microsoft.PowerShell.SDK 7.0.3),it was occured an error while trigger the method "powershell.Invoke(" Import-PSSession ")".

Error Message:
![image](https://user-images.githubusercontent.com/34200616/97254655-cdd68780-1849-11eb-9f71-085d5b366fd6.png)

The error is alter that the result type of cmdlet "New-CsOnlineSession" is Deserialized.System.Management.Automation.Runspaces.PSSession,can`t parse to System.Management.Automation.Runspaces.PSSession.

The result by the cmdlet "New-CsOnlineSession"：
![image](https://user-images.githubusercontent.com/34200616/97254670-d6c75900-1849-11eb-9678-ff1e03b6d13b.png)

You can see the BaseObject and ImmediateBaseObject is Empty, it`s abnormality.Because when i use the same cmdlet in .net formework project,it`s not empty and "Import-PsSession" cmdlet is also work success.

Please help me to find why alter this error and is there some other way to Avoid or repair this problem？  

I would really appreciate your help。

Best regards.

**Comment by iSazonov** [comment]
The module is not PowerShell Core compatible.

Close as stale issue.
