### ISSUE TITLE
Send-MailMessage in PS7

### ISSUE THREAD

**Issue by reuvygroovy** [PowerShell/PowerShell#13904]
## Steps to reproduce

When running the command Send-MailMessage in PS7 you get the following warning:
WARNING: The command 'Send-MailMessage' is obsolete. This cmdlet does not guarantee secure connections to SMTP servers. While there is no immediate replacement available in PowerShell, we recommend you do not use Send-MailMessage at this time. See https://aka.ms/SendMailMessage for more information.

But the link takes you to a page regarding DotNet, not PowerShell, and it's not clear what command should be used instead as an alternative. And of course the command works.

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by doctordns** [comment]
The message is a poor one, at best. It offers no actual help, and as the OP points out, the command works despite the unhelpful message.

Unless and until we have a cmdlet that can send mail 'properly', let's get rid of this warning. It serves no useful purpose as is.

**Comment by jborean93** [comment]
I don't know if PowerShell can offer an alternative. The underlying .NET library (`SmtpClient`) is deprecated and there is no builtin replacement that I know of. The recommended replacement is [MailKit](https://github.com/jstedfast/MailKit) which isn't included in PowerShell. Unless PowerShell wants to ship this library so a new `Send-MailMessage` can utilise it then it can't really do anything.

**Comment by reuvygroovy** [comment]
BTW - this is a PS7 issue, unrelated to VSCode per se, and it can be reprod in PS7 shell.
![97395637-09c32880-18ee-11eb-8621-96727c3d4914](https://user-images.githubusercontent.com/1325158/97528900-6fc7b280-19b7-11eb-8f1f-65f695ec9613.png)

The warning is purposeless, unless you offer an alternative. Sending mail is 101 in coding, and to tell me it's not sure, without providing me an alternative is silly. Also, most mail clients are sending mail unencrypted unless the client/server both support the protocols necessary.

**Comment by iSazonov** [comment]
Dup #11975
