### ISSUE TITLE
CI is broken due to unavailability of Powershell Gallery

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13946]
> The PowerShell Gallery is currently: Experiencing a continued outage as of 10/30 at 18:15 UTC
> __Status: Under investigation
> 
> Summary of Impact: PowerShellGallery.com is experiencing an outage. Users will be unable to access the gallery or download packages.
> 
> Root Cause: Under investigation

https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md#powershell-gallery-status

See also: https://github.com/PowerShell/PowerShellGallery/issues/135

**Comment by xtqqczze** [comment]
> 10/30/2020 18:15 UTC The PowerShell Gallery is currently: __Experiencing a continued outage
> Status: Resolved
> 
> Summary of Impact: PowerShellGallery.com is experiencing an outage. Users will be unable to access the gallery or download packages.
> 
> Root Cause: Work was happening to migrate data lost from the last outage to get the statistics up-to-date. However, an update to the database caused extremely high CPU/DTU utilization which tied up cloud service resources. In an effort to mitigate this issue the production database was restored to a point in time where the database was in a stable state, however this restore caused an error in the configuration of the SQL cluster that resulted in the gallery front end not able to authenticate with the SQL backend. Unfortunately, it took awhile to figure this out. Once that was identified, the SQL configuration was fixed and validated that basic operations are working again. This means for now the statistics are not complete and we'll look at fixing that later after reviewing how this mistake occurred. We are actively monitoring the gallery to ensure it maintains proper operation across all regions.

**Comment by iSazonov** [comment]
Now works.
