### ISSUE TITLE
Unavailability of Powershell Gallery should not break CI

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13956]
Follow-up: #13946

Perhaps we should consider hosting a private nuget repository for modules such Pester, PowerShellGet, etc that we rely on for the build process.

**Comment by iSazonov** [comment]
I think it makes no sense. We had the modules in the repository and removed. I don’t think that rare outages are worth the effort to maintain additional nuget repositories.

**Comment by adityapatwardhan** [comment]
I agree with @iSazonov. If we expect others to take a dependency on PowerShell Gallery for their CI, we should be no different.
