### ISSUE TITLE
Clear-Host results in screen flickering

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#13972]
## Steps to reproduce

Output some lines of text in the PowerShell terminal window (more than three screen height's worth). Then hit `Clear-Host` or `cls`

### Screencast depicting the issue
![PowerShell - Screenbuffer not correctly cleared](https://user-images.githubusercontent.com/9283914/97901315-4b176600-1d3c-11eb-9f77-cb910aae55db.gif)

This flickering regularly gives me the creeps when I suddenly and unexpectedly see errors appearing and vanishing again when I enter `cls`.

## Actual behavior

Apparently, the screen buffer is scrolled to the top before it's getting cleared.

## Expected behavior

The screen should be cleared without recalling some obsolete output.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
To provide some pointers: it doesn't seem to be PSReadline-related, and the problem goes away after the first `Clear-Host` call in a session. Windows Terminal doesn't exhibit the problem to begin with.
