### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gregzakh** [PowerShell/PowerShell#13979]
.

**Comment by vexx32** [comment]
`&` as a suffix is an operator that places the previous pipeline in a new job for execution. It also acts as a statement separator much like `;` does.

So in each of those examples the `[type]` is run in a background job and the following statement is sent to the current session as regular output.

The first example is precisely equivalent to running `[char] &` and `{!{}}` as two completely separate commands.

If your intention is to use `&` as the normal invocation operator it needs to be the _first_ thing in the statement, and given the reproduction examples given here I'd imagine you want to cast the result of some operation to a specific type after it completes. In that case you'd use parentheses like so: `[char](& {!{}})`

**Comment by gregzakh** [comment]
All written by you is familiar for me. Seems you misunderstood my words. I mean that this shouldn't be in the wild. Of course you will say that such shit is entirely on the developer's conscience, nevertheless there should be a job validator.

**Comment by vexx32** [comment]
Not really sure what you're after here. It's how the operator works. 

PowerShell is a tool, and you can use it wisely or unwisely as you please. We don't take hammers off the shelves over a couple of bent nails. 🙂

**Comment by gregzakh** [comment]
In other words, "use this issue like a feature". Right?
