### ISSUE TITLE
Remove workaround for use pre-release of .NET 5 RTM build

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#13974]
To use the pre-release version of .NET 5 RTM builds a workaround had to be added to build.psm1

https://github.com/PowerShell/PowerShell/blob/201f4a6b78f9480589bc29cac91b140d1a5583cf/build.psm1#L1775-L1778

Please remove this when .NET 5 is released.

Also,

remove the RTM feed from the nuget.config:

https://github.com/PowerShell/PowerShell/blob/f03952fc3c6e56aad4ebf5636178b1a5c7481fa8/nuget.config#L5

## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by xtqqczze** [comment]
.NET 5.0 RTM has been released ([5.0.0-rtm.20519.4](https://github.com/dotnet/runtime/releases/tag/v5.0.0-rtm.20519.4))
