### ISSUE TITLE
"Invoke-WebRequest -Resume" fail when local size = remote

### ISSUE THREAD

**Issue by GongT** [PowerShell/PowerShell#13982]
## Steps to reproduce

```powershell
$DownloadFrom = 'https://github.com/PowerShell/PowerShell/releases/download/v7.1.0-rc.2/PowerShell-7.1.0-rc.2-win-x64.msi'
Invoke-WebRequest -Resume -OutFile: 'D:/Test/pwsh.msi' -MaximumRetryCount 10 -RetryIntervalSec 5 -UserAgent gongt/test -Uri $DownloadFrom
```

## Expected behavior

work as [document](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7):

*If the local file size is the same as the remote file size, then no action is taken and the cmdlet assumes the download already complete.*

## Actual behavior

If the local file size is the same as the remote file size, got an error:
```diff
- Invoke-WebRequest: Object reference not set to an instance of an object.
```

Value of `$_.Exception`:
```text
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

## Environment data

<details>
  <summary>Host 1 - Linux + 7.0.3</summary>
<pre>
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 5.8.13-200.fc32.x86_64 #1 SMP Thu Oct 1 21:49:42 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
</pre>
</details>

<details>
  <summary>Host 2 - Windows + 7.0.3</summary>
<pre>
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
</pre>
</details>

<details>
  <summary>Host 2 - Windows + 7.1.0-rc2</summary>
<pre>
Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
</pre>
</details>

**Comment by rmunn** [comment]
Just experienced this with PowerShell 7.4.2 (latest stable release) and 7.5.0-preview.3 (latest preview release) on Windows 11. If you run `Invoke-WebRequest -Resume`, the OutFile already exists, and it's the same file size as the file the server would send, then the result is "Invoke-WebRequest: Object reference not set to an instance of an object."

Also tested using PowerShell 7.4.2 installed on Ubuntu Linux: same "Object reference not set to an instance of an object" error.

Looks like this issue needs to be reopened.

**Comment by rmunn** [comment]
I suspect that [this line of code](https://github.com/PowerShell/PowerShell/blob/bd8b0bd42163a9a6f3fc32001662d845b7f7fff0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L609) may be at the root of the issue: something is later using OutFile, or perhaps QualifiedOutFile (which will throw NullReferenceException if OutFile is null), without checking ShouldSaveToOutFile first (which will be false if OutFile is null).

**Comment by rmunn** [comment]
If I add `-Verbose` I get the following two lines of output, and that's it:

```
VERBOSE: Requested HTTP/1.1 GET with 0-byte payload
Invoke-WebRequest: Object reference not set to an instance of an object.
```

**Comment by rmunn** [comment]
If I delete the downloaded file and try again, I get:

```
VERBOSE: GET with 0-byte payload
VERBOSE: received 6540024-byte response of content type application/octet-stream
```

It might be relevant to note that I'm downloading a file from Google Drive, so the first HTTP response is a redirect with a Location header. Once the second HTTP request is made following the redirect, the second response contains the file.

**Comment by rmunn** [comment]
Discovered that this only occurs when there's been an HTTP redirect first before the file data is sent, so I opened https://github.com/PowerShell/PowerShell/issues/23948 since it's turning out that this is a *different* bug. This issue does not need to be reopened after all.
