### ISSUE TITLE
Allow ValueFromPipelineByPropertyName to work with Hashtables

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#13981]
## Summary of the new feature/enhancement

Didn't find an existing issue... basically:

```pwsh
@{ Name = 'hi'} | .\Invoke-Test.ps1
```

fails, but

```pwsh
[pscustomobject]@{ Name = 'hi'} | .\Invoke-Test.ps1
```

works.

Where `Invoke-Test.ps1` has a parameter, `Name`, with `ValueFromPipelineByPropertyName=$true`.

For newer users of PowerShell, it's hard to grasp what a `PSCustomObject` is and why it differs from a `Hashtable`. This is a scenario that confuses folks a lot.

If one could simply pass in a hashtable and have it work the same as a `pscustomobject` users would be less confused.

**Comment by mklement0** [comment]
Conceptually related: #13727 and #10999.
