### ISSUE TITLE
The capitalization format for the 'systemd' init system is incorrect in the demos folder

### ISSUE THREAD

**Issue by n3rdopolis** [PowerShell/PowerShell#13990]
Hi

Looking at the source, I found that there are some demos for systemd, where the path is capitalized incorrectly

It is spelled as 'SystemD' in the given locations, where to the systemd documentations, this is incorrect https://www.freedesktop.org/wiki/Software/systemd/ . furthermore, the capitalization format 'SystemD', is in fact used by many folks who tend to mock the init system.

```
demos/DSC/dsc-demo.ps1:    $ServiceCtl = "SystemD"
demos/SystemD/journalctl-demo.ps1:Import-Module $PSScriptRoot/SystemD/SystemD.psm1
demos/SystemD/journalctl-demo.ps1:Write-Host -Foreground Blue "Get recent SystemD journal messages"
demos/SystemD/journalctl-demo.ps1:#Drill into SystemD unit messages
demos/SystemD/journalctl-demo.ps1:Write-Host -Foreground Blue "Get recent SystemD journal messages for services and return Unit, Message"
demos/SystemD/readme.md:## SystemD: journalctl demo
demos/SystemD/readme.md:- Requires a SystemD-based operating system (Red Hat or CentOS 7, Ubuntu 16.04)
demos/SystemD/readme.md:Note: Accessing the SystemD journal requires privileges. The user must have authorization to elevate with sudo. You will be prompted for a sudo
```

Thanks

**Comment by iSazonov** [comment]
@sdwheeler Could you please look the Demos folder in the repo? It seems very deprecated and needs to be removed (or updated and moved to Docs repo).

**Comment by sdwheeler** [comment]
@iSazonov These demos are over 4 years old. They don't belong in docs. @SteveL-MSFT do these demos belong in this repo?
