### ISSUE TITLE
Register-ObjectEvent examples not working

### ISSUE THREAD

**Issue by pfmoore** [PowerShell/PowerShell#13999]
## Steps to reproduce

Use the example code from the `Register-ObjectEvent` documentation, with one change to add an action when the event fires to write a file

```powershell
$queryParameters = '__InstanceCreationEvent', (New-Object TimeSpan 0,0,1),
    "TargetInstance isa 'Win32_Process'"
$Query = New-Object System.Management.WqlEventQuery -ArgumentList $queryParameters
$ProcessWatcher = New-Object System.Management.ManagementEventWatcher $Query
Register-ObjectEvent -InputObject $ProcessWatcher -EventName "EventArrived" -Action { echo "Hi" >test.txt }
```

Start a process (e.g. Notepad).

## Expected behavior

The event fires and the file is written.

## Actual behavior

Nothing happens. Testing the same set of commands in Windows Powershell works as expected. I have been unable to find any indication that PowerShell Core doesn't support this (and if that were the case, I'd expect the Register-ObjectEvent documentation to note this).

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by pfmoore** [comment]
(Updated, I accidentally posted the wrong `$PSVersionTable` value the first time).

**Comment by iSazonov** [comment]
@pfmoore Please add a reference to the docs.

**Comment by pfmoore** [comment]
Well, basically `help Register-ObjectEvent`... But it looks like there's an online version here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-objectevent?view=powershell-7

**Comment by iSazonov** [comment]
@sdwheeler Could you please move the issue in Docs repo?

**Comment by sdwheeler** [comment]
This sounds like a bug that needs deeper investigation. I tested this in 7.1.0 and 6.2.7. The cmdlet creates the subscription but it seems that the event is never fired. Before we document anything we need to understand the bug.

**Comment by Joachim-Otahal** [comment]
We need to reopen this, 'cause I just stumbled on exactly the same issue. Purpose: Read Growatt 600 MIC modbus data via RS485, the current power delivered. Powershell is Version 5.1, and I won't change since it is available from Windows 7 up to the newest Windows Canary Insider build.

This version works in Powershell ISE, and when the content of the script is copy-pasted into a shell, but NOT when it is used the normal way in a script:

```
[string]$COM = "COM3"
[int]$Timeout = 4

# Modbus command for "give me your data"
[byte[]]$GetGrowattStatus=(0x01,0x04,0x0b,0xb8,0x00,0x7d,0xb2,0x2a)

$port = New-Object System.IO.Ports.SerialPort $COM,9600,None,8,one
$port.Open()
# Event for receiving data
$eventJob = Register-ObjectEvent -InputObject $port -EventName "DataReceived" -SourceIdentifier StatusCOM3 -Action {
    while ($port.BytesToRead -gt 0) {
       $port.ReadByte()
    }
}
$port.Write($GetGrowattStatus,0,$GetGrowattStatus.Count)
# Response is not fast, but wait no more than $Timeout seconds
for ($i=0;$i -lt $Timeout*4;$i++) {
    Start-Sleep -Milliseconds 250
    if ($eventJob.Output[8]) {
        $GrowattWatt = ($eventJob.Output[7] * 256 + $eventJob.Output[8])/10
        $i=[int]::MaxValue
    }
}
$port.Close()
Unregister-Event -SourceIdentifier StatusCOM3
Remove-Job -Name StatusCOM3
$GrowattWatt

```

Whereas this version, which does NOT rely on Register-ObjectEvent works in ALL cases.
Side effect: Simpler solution beats "complex" solution again :D.

```
[string]$COM = "COM3"
[int]$Timeout = 4

# Modbus command for "give me your data"
[byte[]]$GetGrowattStatus=(0x01,0x04,0x0b,0xb8,0x00,0x7d,0xb2,0x2a)

$port = New-Object System.IO.Ports.SerialPort $COM,9600,None,8,one
$port.Open()
$port.Write($GetGrowattStatus,0,$GetGrowattStatus.Count)
# Response is not fast, but wait no more than $Timeout seconds
for ($i=0;$i -lt $Timeout*4;$i++) {
    Start-Sleep -Milliseconds 250
    if ($port.BytesToRead -gt 0) {
        $Data=@()
        while ($port.BytesToRead -gt 0) {
           $Data += [byte]$port.ReadByte()
        }
        $GrowattWatt = ($Data[7] * 256 + $Data[8])/10
        $i=[int]::MaxValue
    }
}
$port.Close()
$GrowattWatt
```

Another one to the "known powershell buglist". Man, this is weird, and easy to reproduce with any serial device (if you have one).
