### ISSUE TITLE
ConvertTo-Json ignores ETS instance properties that shadow type-native properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#13998]
Force-adding an ETS instance property to a .NET type that already has a property with the given name normally _overrides_ the type-native property. That is, the ETS member then shadows the native property.

Unexpectedly - and this bug also exists in Windows PowerShell - `ConvertTo-Json` does not respect this during serialization and ignores the overriding ETS property.

## Steps to reproduce

```powershell
# Override the type-native 'Height' property.
$size = [System.Drawing.Size]::new(1,1) | Add-member -force -PassThru Height OVERRIDDEN

# Make sure the overridden property is in effect.
$size.Height, ($size | ConvertTo-Json | ConvertFrom-Json).Height | Should -Be OVERRIDDEN, OVERRIDDEN
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because `ConvertTo-Json` unexpectedly ignores the overriding ETS property and reports the type-native property value; note how direct property access _did_ respect the ETS property:

```none
Expected @('OVERRIDDEN', 'OVERRIDDEN'), but got @('OVERRIDDEN', 1).
```

## Environment data

```none
PowerShell Core 7.1.0-rc.2
```

**Comment by iSazonov** [comment]
I'd said it is a bug otherwise it would be a breaking change.

**Comment by michaeltlombardi** [comment]
I just ran up against this again today. It's _extremely_ surprising behavior.

I'm working on some tooling to support generating class documentation from a definition, so I was hoping to be able to declare properties on the class and then overwrite them with ScriptProperties in the constructor, like:

```powershell
class ValeMetricsAutomatedReadability {
    # The numerical representation of a document's complexity.
    [int]    $Score
    # The maximum value for readability to maintain compliance.
    [int]    $Threshold
    # The measurement of a document's complexity as an approximate age range.
    [string] $AgeRange
    # The measurement of a document's complexity as an approximate grade level.
    [string] $GradeLevel

    hidden static $ScoreMapping = @{
        1  = @{
            AgeRange   = '5-6'
            GradeLevel = 'Kindergarten'
        }
        # Truncated for brevity
        14 = @{
            AgeRange   = '18-22'
            GradeLevel = 'College student'
        }
    }

    # The default constructor.
    ValeMetricsAutomatedReadability() {
        $this.AddDynamicMembers()
    }

    # Defines a document's complexity from a known score.
    ValeMetricsAutomatedReadability([int]$Score) {
        $this.Score = $Score
        $this.AddDynamicMembers()
    }

    # Defines a document's complexity from its metrics, as returned by `Get-ProseMetric`.
    ValeMetricsAutomatedReadability([ValeMetricsInfo]$Metrics) {
        $this.Score = [ValeMetricsAutomatedReadability]::GetScore($Metrics)
        $this.AddDynamicMembers()
    }

    hidden [void] AddDynamicMembers() {
        $this | Add-Member -Force -MemberType ScriptProperty -Name AgeRange -Value {
            [ValeMetricsAutomatedReadability]::ScoreMapping[$this.Score].AgeRange
        }
        $this | Add-Member -Force -MemberType ScriptProperty -Name GradeLevel -Value {
            [ValeMetricsAutomatedReadability]::ScoreMapping[$this.Score].GradeLevel
        }
        $this | Add-Member -Force -MemberType ScriptProperty -Name Message -Value {
            if ($this.TestThreshold()) {
                $TargetGradeLevel = [ValeMetricsAutomatedReadability]::GetGradeLevel($this.Threshold)
                $this.Message = @(
                    "Grade level is $($this.GradeLevel)"
                    "try to target $TargetGradeLevel"
                ) -join ' - '
            }
        }
    }

    # Returns a weighted score of a document's complexity using the character count,
    # word count, and sentence count.
    static [int] GetScore([ValeMetricsInfo]$Metrics) {
        $Result = 4.71 * ($Metrics.CharacterCount / $Metrics.WordCount)
        $Result += 0.5 * ($Metrics.WordCount / $Metrics.SentenceCount)
        $Result -= 21.43
        $Result = [Math]::Ceiling($Result)
        $Result = [Math]::Clamp($Result, 1, 14)

        return $Result
    }
}
```

However, with **AgeRange** and **GradeLevel** defined, converting the object to JSON leaves a user with null values for those properties. Leaving them undefined as normal properties and only adding them as ScriptProperties allows them to serialize correctly, but makes the class harder to document automatically.

**Comment by michaeltlombardi** [comment]
I _think_ this is related to the following lines - the conversion process only _adds_ properties from `psextended` and `psadapted`, it **does not** overwrite the values for the base object:

https://github.com/PowerShell/PowerShell/blob/48c9d683565ed9402430a27e09410d56d52d4bfd/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs#L685-L688

This seems tractable to me, but I don't have a good handle on effort/impact.
