### ISSUE TITLE
Property setter assigning to field in HyperVSocketEndPoint

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#13995]
https://github.com/PowerShell/PowerShell/blob/a16f3eb20462b49423a77b37207ec15743e23f9b/src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs#L45-L57

Why is the setter for `ServiceId` assigning to `_vmId`? It is unclear whether this is intended behaviour or not.

**Comment by iSazonov** [comment]
It comes from Windows PowerShell. If it is not bug we need to add a comment in the code.

It seems was @SteveL-MSFT who communicated with Hyper-V team in last time.

**Comment by xtqqczze** [comment]
@PaulHigin @SteveL-MSFT Can someone look at this please.

**Comment by PaulHigin** [comment]
This looks like a typo bug to me.  The only effect appears to be that VmId and ServiceId values are not unique.  Since this class can be serialized I have to assume the information may be persisted, and fixing the typo may cause a breaking change.

**Comment by vexx32** [comment]
Given how this property setter works, I don't think it's possible for `ServiceId` to be deserialised correctly currently... Currently the effect would appear to be that the underlying data for `ServiceId` will always and only ever be the default value, unless you manually set the backing field. Any attempt to set the value by the property will simply set the VM ID instead.

**Comment by rkeithhill** [comment]
The `Equals()` method on this class is only comparing `ServiceId` values via the `VmId` field which is overwritten with the `ServiceId` value.  The `ServiceId` field appears to always contain `Guid.Empty`.  So if if two `HyperVSocketEndPoint` objects have the same `ServiceId` but different `VmId` values they will compare the same.  Probably not a good situation.

**Comment by PaulHigin** [comment]
This is obviously wrong, and I feel we should take the fix.  There may be a small possibility of regression but I feel it is minimal and worth taking the fix.  I ran this by the committee and they felt the same.

**Comment by vexx32** [comment]
Putting it up for grabs for now, as it seems a simple enough change for community folks to take on if they would like.
