### ISSUE TITLE
dotnet apphost.exe detected as Trojan

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#14008]
## Steps to reproduce

I cloned the repo, and executed:
```powershell
Import-Module .\build.psm1
Start-PSBootstrap
```

## Expected behavior
Everything works great.

## Actual behavior
Popup from Windows Defender, claiming that this file:

    C:\Users\<me>\AppData\Local\Microsoft\dotnet\packs\Microsoft.NETCore.App.Host.win-x86\5.0.0\runtimes\win-x86\native\apphost.exe

Is a virus: Trojan:Win32/Fuery.C!cl

**Comment by iSazonov** [comment]
I wonder to see the report in the repository. It is better to report the false positive to Windows Defender team.

**Comment by iSazonov** [comment]
If you think it is not false positives please use out security template as guidance to create a security report.

**Comment by jazzdelightsme** [comment]
Submitted to Defender people following instructions here: https://www.microsoft.com/en-us/wdsi/filesubmission/.

**Comment by jazzdelightsme** [comment]
This has been addressed. Steps to fix locally:

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by davework26** [comment]
Just had malware report of Win32:Tojan-gen in same file by Avast.

**Comment by TravisEz13** [comment]
@davework26 You'll have to work with Avast or .NET on that.
