### ISSUE TITLE
New-PSSession from linux to linux doesn't respect -Port

### ISSUE THREAD

**Issue by rNianios** [PowerShell/PowerShell#14016]
## Steps to reproduce
Setup powershell remoting as explained on https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7 for linux 

My server excepts the ssh connection on different port than 22

```powershell
New-PSSEssion -Hostname username@host:22 -SSHTransport
```
returns 
```
[host] The background process reported an error with the following
     | message: The SSH client session has ended with error message: ssh: connect to host
     | host port 22: Connection refused.
```
This means that the ssh client is connecting to the server and is getting refused because this is not the port of the service.
Now if I try 

```powershell
New-PSSEssion -Hostname username@host:2222 -SSHTransport
```
returns 
```
[host] The background process reported an error with the following
     | message: The SSH client session has ended with error message: subsystem request failed on
     | channel 0.
```
## Expected behavior

```none
Connect to ssh host and the -Port parameter
```

## Actual behavior

```none
Doesn't respect -Port parameter
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Your examples didn't have the `-Port` parameter, can you confirm if you did `New-PSSession -HostName host -UserName username -Port 22` that it works? The error about the subsystem request failing would indicate the server does not have the `powershell` subsystem line in the `sshd_config` file, or it's not pointing to the correct path.

**Comment by rNianios** [comment]
> Your examples didn't have the `-Port` parameter, can you confirm if you did `New-PSSession -HostName host -UserName username -Port 22` that it works (or at least doesn't complain about the port being refused)? The error about the subsystem request failing would indicate the server does not have the `powershell` subsystem line in the `sshd_config` file, or it's not pointing to the correct path.

Thank you. Resolved when added to the subsystem on the destination server. Not sure how I missed that.
