### ISSUE TITLE
Auto-completion doesn't work for non build-in commands and path with []

### ISSUE THREAD

**Issue by Nino-kun** [PowerShell/PowerShell#14015]
Path auto-completion doesn't work for non build-in commands if path contain square brackets symbols.

## Steps to reproduce

```
New-Item -Type File -Name '[test].txt'
Copy-Item '``[ + <TAB> work and became Copy-Item '.\`[test`].txt'
notepad  '``[ + <TAB> doesn't work
```

## Expected behavior

```
TAB-key auto-complete path for any command.
```

## Actual behavior

```
Path auto-completion doesn't work if command not pwsh build-in.
```

## Environment data

```
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by hv0905** [comment]
The issue still exists after nearly 2 years... I hope it can be fixed.
Even worse, the built-in command also can't work with the autocomplete in this case.

# Repro

![image](https://user-images.githubusercontent.com/29349119/181788450-83ecf8a0-a6bf-4dae-8252-fac3ac0a419c.png)
In this case, I can't perform an autocomplete.

![image](https://user-images.githubusercontent.com/29349119/181788604-74ac8166-4d3f-42ec-b346-e2be3a9d76d2.png)
Neither this.

**Comment by Nino-kun** [comment]
Powershell is really non-intitive in that part.
Autocompletion work most of the time, but some time it request adding special characters, and some time it doesn't work at all.
Your examples won't work because of one backtick character <`>. If you write two backticks, it will.

**cat '.\\\`[ + \<TAB\>** - don't work
**cat '.\\\`\`[ + \<TAB\>** - work
**cat .\\\`\`[ + \<TAB\>** - don't work again, because  single quote symbol missing.

**Comment by Nino-kun** [comment]
I really like your suggestion, it's intuitive and simple.

Will it always work as intended? Can't say, i'm not a programmer. The maximum I can say is that some cmdlets have -Path and -LiteralPath keys, which interpret characters in names differently. Path require escaping some "special" characters, LiteralPath treat all characters literally.
