### ISSUE TITLE
ExecutionPolicy ignored when running PowerShell from a mapped network share

### ISSUE THREAD

**Issue by vaporup** [PowerShell/PowerShell#14029]
## Steps to reproduce

```
- Start pwsh.exe directly from share via UNC
- Start pwsh.exe directly from share via mapped drive
- Run some ps1 file
```

## Expected behavior

```
ExecutionPolicy should prevent running ps1 file
```

## Actual behavior

```
Get-ExecutionPolicy returns "RemoteSigned" in both cases
but only when running ps1 file directly from UNC it prevents
the script from running.
```

## Environment data
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

PS: Is running Powershell directly from a share actually supported? It seems to work though...

**Comment by vaporup** [comment]
Hm sorry, I think this is not an issue. Running it from a mapped drive, PowerShell seems to consider it as a local script.

Leaves the question if running Powershell directly from a share is actually supported?

**Comment by mklement0** [comment]
Yes, a mapped drive is implicitly trusted; with UNC paths, it depends on whether the server name contains `.` - perhaps [this summary](https://github.com/PowerShell/PowerShell/issues/13869#issuecomment-717390248) helps.

**Comment by vaporup** [comment]
Yes, very helpful. Thank you
