### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by asdf8dfafjk** [PowerShell/PowerShell#14022]
##pwsh:

>echo "a 1`nb 2`nc 3`nd 4`n" | perl -lane 'printf "%s%s", @F[0], @F[1]'
Substitution replacement not terminated at -e line 1.

##zsh: 

➤ echo "a 1\nb 2\nc 3\nd 4\n" | perl -lane 'printf "%s%s", @F[0], @F[1]'                                           
a1b2c3d4%

**Comment by iSazonov** [comment]
@asdf8dfafjk Please a template to create new issue.
