### ISSUE TITLE
Do not require { ... } (curly braces) around variable names for null-conditional member access

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14025]
Note: This issue is just a reminder to reopen #11379 in order to have it revisited by the PowerShell committee; the willingness to do so was signaled in the Sept. '20 community call (see details below), but there was no follow-up, and leaving an issue in a closed state usually means that it falls through the cracks. There is clearly community interest in having this revisited, and the analysis that led to closing the issue is disputed.

Once #11379 is reopened, this issue can be closed.

------

@SteveL-MSFT 

Thanks for discussing issue #11379 in the September community call (https://aka.ms/PSCommunityCall; as of this writing, the September call's recording has not been posted there, but is accessible at https://aka.ms/JoinPSCall, until the next call), starting at 46:00, based on @ThomasNieto's suggestion in the prior solicitation for discussion topics at   https://github.com/PowerShell/PowerShell-RFC/issues/260:

(I was hoping to provide a direct link to the relevant portion of the recording, but that will have to wait until it is posted to YouTube and linked to at https://aka.ms/PSCommunityCall.)

Based on your remarks in the recording:

* Given that you indicated willingness to revisit this, please reopen the linked issue and re-tag it as `Review - Committee`.

* As for your remarks that enclosing variable names in curly braces is a preexisting feature and that people object to having to use them in this case on _aesthetic_ grounds:

  * I don't think anyone here _isn't_ aware that `{...}` _can_ and sometimes _must_ be used to disambiguate variable names.
  * It is also not about _aesthetics_, it is primarily about _not getting the expected behavior_  in  manner that potentially _fails quietly_ (depending on what strict mode is in effect), due to _not expecting to have to use `{...}` in this case_; a secondary concern is typing inconvenience.

**Comment by ALIENQuake** [comment]
FWIW, if you use PowerShell script with ${var} syntax (not necessary with `?` char) in combination with Terragrunt, it will fail. A workaround is to escape `${` with `$$${` which is very misleading and looks ugly.

**Comment by SeeminglyScience** [comment]
@ALIENQuake A (subjectively) better workaround is using `($var)?.Member` instead.  Personally I prefer that syntax over `${var}?.Member` anyway, assuming the only intention is to make `?.` work.

**Comment by mklement0** [comment]
@joeyaello, thanks for [showing awareness of the problem in the Nov 19 community call](https://youtu.be/IHMgWobHzrI?t=2446): 

> To be honest, this kind of did sway me on this issue a little bit, we still want to have a conversation and **we can make it a priority in our next committee meeting**. Someone did do the analysis on our behalf in the corpus and determined that there was 2 uses of the question mark in a variable name. **I think it's something that we could possibly do as an experimental feature early in 7.2 [...] it's tricky [...] it's not a zero-cost thing [...] not a huge priority right now, so I don't want to guarantee that that's happening.**

Priority is a separate issue, but I do hope this issue won't fall through the cracks, which seems to be a real possibility, given how the debate has unfolded (see timeline below).

To frame the issue in the context of the breaking-change debate:

* The _benefit_ of the change is: Without it, the utility of the new null-conditional access operators will be severely hampered, because _users won't expect to have to enclose the variable name in `{... }` in order to use it_; with `Set-StrictMode -Version 1` or higher, you'll at least get an error (because `$foo?.bar` then requires the existence of `${foo?}`), but with strict mode off the code will simply not do what users expect, [as pointed out by @rkeithhill and acknowledged as a problem by you](https://youtu.be/IHMgWobHzrI?t=2779).

* As for whose code will break due to the change: if the corpus is representative, virtually _nobody's_ - see below.

* As for @rjmholt's syntax-change concerns: this is _not_ a syntax change, but a _semantic_ one: old code won't _break_, it'll simply _behave differently_ - and since there is virtually no code like that in existence, this is a moot point.

----

Timeline:

* The original request, #11379, is opened on Dec 17, 2019.

* It is [closed on Aug 26, 2019](https://github.com/PowerShell/PowerShell/issues/11379#issuecomment-681155223) after the committee decides it would be too much of a breaking change, following analysis of the corpus. "there was quite a bit of usage of variable names ending with the question mark"

* A [request to show the original analysis](https://github.com/PowerShell/PowerShell/issues/11379#issuecomment-682014513) that the committee decision was based on is ignored.

* The community does their own analysis, with the heavy lifting performed by @ThomasNieto; [further analysis](https://github.com/PowerShell/PowerShell/issues/11379#issuecomment-689858916) finds virtually _no_ usage of variable names ending in `?`:  _one_(!) bona fide instance in the corpus, with the majority of the occurrences - limited to 8 files in total - showing _mistaken_ usage of `?` inside _expandable strings_ (e.g., `"Are you sure you want to kill $vParam?"`), which implicitly makes the case for the requested change: _users do not and should not expect `?` to be usable in a variable name without `{...}`_.


* A [request to reopen the original issue](https://github.com/PowerShell/PowerShell/issues/11379#issuecomment-698478048) on 24 Sep, after a discussion in the Sep 17 community call, is ignored.

* This issue is opened on Nov 10, as a reminder to reopen the original one, along with [addressing](https://github.com/PowerShell/PowerShell/issues/14025#issue-740119106) the [arguments made by @SteveLee in the Sep 17 community call](https://youtu.be/nW4OxHNSng0?t=2609).

* The issue is discussed again in the Nov 19 community call, where [@SteveLee in essence repeats his arguments from the Sept. call](https://youtu.be/IHMgWobHzrI?t=2050), showing no awareness of the counterarguments that have been made, and notably repeating the claim "I think we did some research and there are people who use this, so we don't want to break them" and saying "I don't think this really that much of a pain point that we want to keep revisiting". Later in the call this is tempered by [@joeyaiello's acknowledgement of the problem](https://youtu.be/IHMgWobHzrI?t=2446).

Needless to say, the above is liable to erode the community's confidence that it its concerns and feedback are taken seriously.

**Comment by plastikfan** [comment]
When I first discovered the Null-coalescing operators introduce in v7 I was initially pleased. That is until I started reading the ugly details and starting experimenting with this.

In my opinion, this is another example of being held back by prior bad design choices that just goes on to haunt us for evermore, instead of making a corrective breaking change. What value is there for being able to use a '?' in a variable name? It has next to no value but high restraining and detrimental impact. Why can't we have a breaking change that removes this? Having to use those {} just to appease variables names with a question mark is a case of the tail wagging the dog. Sure, there will be some code will be impacted. But if you document it well and SHOUT about it, make it easy for users to upgrade their code, possibly via a new new PSSA warning, then I think that would be better for all of us. The use of the {} really is aweful and should be fixed.

I'm experimenting with test code at the moment and have a test that refers to a PSCustomObject $_options, which contains nested members. I need to access $_options.Tags.From in a safe way.

Tags is known to never be null, but From is optional. So when you use coalescing, do you apply that to the whole path at once, or do you use the ?. on each sub member. When I try the latter (this scenario is missing from the help doc),  it doesnt work because the sub member access is referenced independently, not as a member.

assuming:
```powershell
        $_options.Tags = [PSCustomObject]@{
          From = '3.0.0';
        }
```

---
```powershell
# no coalescing, this is ok, but potentially unsafe, if From doesnt exist (I think)

if ($_options.Tags.From) {
```
---
```powershell
# this doesnt work
# => RuntimeException: The variable '$Tags' cannot be retrieved because it has not been set.
#
if (${_options}?.${Tags}.From) {
```
---

```powershell
# this doesnt work
# => The variable '$_options.Tags' cannot be retrieved because it has not been set.
if (${_options.Tags}?.From) {
```

so what is the correct and safe way to coalesc the entire path from _options right down to From? And also, do the rules apply the same inside of a class method as opposed to a function or script?

**Comment by ExE-Boss** [comment]
@plastikfan You need to use parentheses:
```pwsh
# This works:
if (($_options.Tags)?.From) {
```

**Comment by plastikfan** [comment]
Well if that works, why are we being bogged down and harrased into using ${}? What is the value of that, if we can just use ()?

**Comment by ALIENQuake** [comment]
@plastikfan The point is to be able to use `$variable?` syntax, without braces.

**Comment by plastikfan** [comment]
@ALIENQuake, I know, I'm adding my 2 pence worth to get rid of the braces.

**Comment by mklement0** [comment]
Perhaps needless to say, @plastikfan, I fully agree with your assessment.

While using parentheses is always an option, no workaround is actually required in this case, because `Tags` is a _property_ rather than a _variable_ name, and the former, unlike the latter, aren't permitted to contain `?`:

```powershell
Set-StrictMode -Version 2
$_options = [pscustomobject] @{ Tags = [PSCustomObject]@{ From = '3.0.0' }; Tags2 = $null }

# *No* {...} needed around *property* names.
$_options.Tags?.From # ->3.0.0
$_options.Tags2?.From # -> $null
```

But to me this distinction between variable names and property names is yet another reason to _never_ require `{...}` in combination with null-conditional access (`?.` / `?[]`).

---

As an aside: what null-conditional access currently _doesn't_ protect against is _non-existence_, as opposed to `$null`, even though these conditions are otherwise often interchangeable:

```powershell
$_options.Tags3?.From # !! ERROR, because property doesn't *exist* - as opposed to *existing and being $null*.
```

**Comment by plastikfan** [comment]
thanks @mklement0

**Comment by Halkcyon** [comment]
> ```powershell
> $_options.Tags3?.From # !! ERROR, because property doesn't *exist* - as opposed to *existing and being $null*.
> ```

@mklement0 yikes.. what a footgun of a decision

**Comment by daxian-dbw** [comment]
>```powershell
>$_options.Tags3?.From # !! ERROR, because property doesn't *exist* - as opposed to *existing and being $null*.
>```

I have a different opinion on this. By enabling `StrictMode`, you mean to catch the the cases where a non-existing member gets accidentally dereferenced at runtime, and that's what it does even with the null-conditional operator, isn't it?

The null-conditional operator is essentially a syntactic sugar of `if ($null -eq target) { $null } else { target.member }`, so I don't think it should suppress the "non-existing property" check enforced by the strict mode.

You may ask _"why `$_options.Tags2?.From` doesn't error out given that `From` is a non-existing member?"_. That's because the `From` property doesn't get dereferenced at runtime.

**Comment by daxian-dbw** [comment]
As for the unfortunate fact that curly braces is needed for a variable to use null-conditional operator, I agree we should revisit it.

**Comment by vexx32** [comment]
> >```powershell
> >$_options.Tags3?.From # !! ERROR, because property doesn't *exist* - as opposed to *existing and being $null*.
> >```
> 
> I have a different opinion on this. By enabling `StrictMode`, you mean to catch the the cases where a non-existing member gets accidentally dereferenced at runtime, and that's what it does even with the null-conditional operator, isn't it?
> 
> The null-conditional operator is essentially a syntactic sugar of `if ($null -eq target) { $null } else { target.member }`, so I don't think it should suppress the "non-existing property" check enforced by the strict mode.
> 
> You may ask _"why `$_options.Tags2?.From` doesn't error out given that `From` is a non-existing member?"_. That's because the `From` property doesn't get dereferenced at runtime -- the `else` block won't be evaluated.

IMO this stance is completely useless and borderline invalid until there is a reasonably straightforward way to check this ahead of time without throwing an error.

I think quite a few folks expected the ?. operator to pull double duty as doing that as well. Now we still have no way to actually work in strict mode with any confidence that our code will actually run.

**Comment by daxian-dbw** [comment]
> ... until there is a reasonably straightforward way to check this ahead of time without throwing an error.

I don't think you can have an accurate check on this until at run time. Imagine the script will receive a JSON payload, then convert it to a `PSObject` and access its members -- you don't know what actual payload you will receive, so there is no way to guarantee the ahead-of-time checking on the member accessing.

> I think quite a few folks expected the ?. operator to pull double duty as doing that as well.

If there is such an ask, then we can discuss/debate on whether that's reasonable and worth to have. But for its current behavior regarding strict mode, I don't think it's fair to say it's broken. It's just a syntactic sugar today, and it does what it's supposed to do as a syntactic sugar, nothing more.

**Comment by vexx32** [comment]
I mean, you _can_ check `$object.PSObject.Properties.Name -contains $value` so I don't see a reason that can't be made more accessible for folks that want to work in Strict Mode.

Without some way of making that less of a painful and obscure way to code, strict mode is functionally pretty useless in most circumstances.

**Comment by daxian-dbw** [comment]
> ... you can check $object.PSObject.Properties.Name -contains $name so I don't see a reason that can't be made more accessible via some operator ...

This is a fair ask which we can absolutely discuss about. I assume there is already an issue for this? If so, please share with me the link. My comments were purely about why `?.` does what it does today regarding strict mode, but nothing against making it easy to dereference non-existing member when needed in strict mode.

**Comment by vexx32** [comment]
If there is, I'm not seeing it at the moment. Thought there would have been though. #2798 is somewhat related, I suppose. Opened #15338 for that, ty.

**Comment by ThomasNieto** [comment]
This issue is waiting for the WG to reevaluate with update information.

**Comment by jantari** [comment]
@ThomasNieto commented on this, I don't feel like it should have been closed given that that was "activity"?

**Comment by vaind** [comment]
Can someone reopen this issue? The bot has obviously bugged out. Or should we create another issue to reopen an issue to reopen an issue? 😬

**Comment by vaind** [comment]
> I believe the intent with the great issue purging of 2023 was for us to re-open new issues where needed.
> 
> I did that with #20705 so now that issue is in limbo again just like the original #8751 before it 😄👍

that seems to be a different issue?

**Comment by jantari** [comment]
Yes, but it is an example of an issue that was also closed by the bot and we've had to create a new one.
