### ISSUE TITLE
Get-Content -Tail parameter is broken in v7.1.0-rc.2 and v7.1.0

### ISSUE THREAD

**Issue by FatalBulletHit** [PowerShell/PowerShell#14028]
## Steps to reproduce
Run the following with the latest preview version ([`7.1.0-rc.2`](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-rc.2)) or the latest release version ([`7.1.0`](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0)) of PowerShell 7:
```powershell
(Get-ChildItem $PSHOME -File).Count
(Get-ChildItem $PSHOME -File | ForEach-Object { Get-Content $_.FullName -Tail 1 }).Count
```

## Expected behavior
Output
```none
449
449
```
Works as intended in the previous release version ([`7.0.3`](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3)).

## Actual behavior
Output
```none
449
26
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please create more simple repro steps with one file.

**Comment by FatalBulletHit** [comment]
Made it even simpler I guess and if you need a reference file, just use the `Accessibility.dll` from the PowerShell 7 installation directory or download it: [`Accessibility.dll.txt`](https://github.com/PowerShell/PowerShell/files/5524668/Accessibility.dll.txt)

I'm fairly sure the issue has something to do with special characters, shouldn't be down to my system either as I was able to reproduce it in a VM.

**Comment by vexx32** [comment]
@FatalBulletHit what version have you seen this working correctly in?

**Comment by FatalBulletHit** [comment]
I used the latest release, `7.0.3` that'd be.
Looking at the history of [`GetContentCommand.cs`](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs) I'd assume it might be [this](https://github.com/PowerShell/PowerShell/commit/03a58c4186a0fc8ed2d052054da84d97eb46d8fb#diff-0cf19feadd29d19fb01dcfe57f5fd9bd24be0d5fed7c1241f0cfa05da14c2fc1) or [this](https://github.com/PowerShell/PowerShell/commit/eaad6c22350fd88bbdaaf9db5f325f0ea3608d87#diff-0cf19feadd29d19fb01dcfe57f5fd9bd24be0d5fed7c1241f0cfa05da14c2fc1) commit.

**Comment by vexx32** [comment]
Hm... doesn't look like it's either of those.

I think it's here: https://github.com/PowerShell/PowerShell/commit/d528bf5d3df65655a027cdb46d6734f91518bc7b#diff-0cf19feadd29d19fb01dcfe57f5fd9bd24be0d5fed7c1241f0cfa05da14c2fc1

**Comment by FatalBulletHit** [comment]
The bug is also present in the latest [`7.1.0`](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0) release.

**Comment by kvprasoon** [comment]
for a better picture

```
$count=0;(Get-ChildItem $PSHOME -File | ForEach-Object {$count++;[pscustomobject]@{name=$_.FullName;count=$count;content=(Get-Content $_.FullName -Tail 1 )}})
```

**Comment by iSazonov** [comment]
> Hm... doesn't look like it's either of those.
> 
> I think it's here: [d528bf5#diff-0cf19feadd29d19fb01dcfe57f5fd9bd24be0d5fed7c1241f0cfa05da14c2fc1](https://github.com/PowerShell/PowerShell/commit/d528bf5d3df65655a027cdb46d6734f91518bc7b#diff-0cf19feadd29d19fb01dcfe57f5fd9bd24be0d5fed7c1241f0cfa05da14c2fc1)

But TotalCount default is -1.

**Comment by iSazonov** [comment]
I see the issue in PowerShell 7.1.0-preview.1

**Comment by Liturgist** [comment]
Still the same result.

```
PS C:\> $psversionTable.psversion.ToString()
7.3.9
PS C:\> (Get-ChildItem $PSHOME -File).Count
>> (Get-ChildItem $PSHOME -File | ForEach-Object { Get-Content $_.FullName -Tail 1 }).Count
323
29
```

**Comment by Liturgist** [comment]
Still the same result.

```
PS C:\> $PSVersionTable.PSVersion.ToString()
7.4.0
PS C:\> (Get-ChildItem $PSHOME -File).Count
323
PS C:\> (Get-ChildItem $PSHOME -File | ForEach-Object { Get-Content $_.FullName -Tail 1 }).Count
29
```
