### ISSUE TITLE
Clarify the update strategy for the PowerShell global tool

### ISSUE THREAD

**Issue by kapsiR** [PowerShell/PowerShell#14037]
Since PowerShell `v7.1.0` had a few release candidates and now released as stable, it would be cool to have the [global tool](https://www.nuget.org/packages/PowerShell/) updated accordingly.

Additionally, is there any documentation on how and when the global tool gets updated?  

I just want to ask because 
 - the last release [took some time too until it got published](https://github.com/PowerShell/PowerShell/issues/12964)
 - no preview or rc release got published recently

Thanks for your efforts and the great work!

/cc @iSazonov, @adityapatwardhan

**Comment by adityapatwardhan** [comment]
Just released the global tool. It might take a couple of minutes to be available.

We only release the GA versions, hence no RC and preview builds.

**Comment by kapsiR** [comment]
Thanks for the amazing fast response, I really appreciate that! 🙏👍
