### ISSUE TITLE
By default, PowerShell Remoting isn't working in Asp.Net Core SDK 5.0 projects due to use of BinaryFormatter serialization

### ISSUE THREAD

**Issue by leonardder** [PowerShell/PowerShell#14032]
I have an asp.net core application that uses out of process PowerShell.

## Steps to reproduce
Create a project with the following code:

```c#
using System;
using System.Management.Automation.Runspaces;

PowerShellProcessInstance instance = new PowerShellProcessInstance(
                powerShellVersion: new Version(5, 1),
                credential: null,
                initializationScript: null,
                useWow64: false
);
var runspace = RunspaceFactory.CreateOutOfProcessRunspace(null, instance);
runspace.Open();
```

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="system.management.automation" Version="7.0.3" />
  </ItemGroup>

</Project>
```

Note, also happens w ith System.Management.Automation 7.1.0 (most recent rc)

## Expected behavior
Runspace opens properly.

## Actual behavior
An exception is raised:

> An error has occurred which PowerShell cannot handle. A remote session might have ended.

Inner exception:

> BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.

## Additional details
1. The issue does not occur when using the default project sdk (not the web one)
2. BinaryFormatter should probably not be used, see https://github.com/dotnet/designs/pull/141

**Comment by fMichaleczek** [comment]
### Summary : 
- **The issue occurs only with asp.net core SDK**, not with the dot.net core SDK
- **The issue is only related to RunspaceFactory.CreateOutOfProcessRunspace** , CreateOutOfProcessRunspace(null) had the same error
- The main message error is **BinaryFormatter serialization and deserialization are disabled within this application**

### Solution : 
Add a property **EnableUnsafeBinaryFormatterSerialization** set to **true** in your project
```
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="system.management.automation" Version="7.0.3" />
	</ItemGroup>
</Project>
```

@PaulHigin I think PS Team should add the property EnableUnsafeBinaryFormatterSerialization to every project in this repo which depends on Binary Formatter Serialization.  I don't know if PowerShell depends on EnableUnsafeUTF7Encoding too. See this post, if you want to see all new properties in net5.0
https://github.com/PowerShell/PowerShell/issues/13755#issuecomment-704948203

**Comment by leonardder** [comment]
@fMichaleczek fMichaleczek Thanks a lot for providing these directions, it works like a charm here.

> @PaulHigin I think PS Team should add the property EnableUnsafeBinaryFormatterSerialization to every project in this repo which depends on Binary Formatter Serialization. I don't know if PowerShell depends on EnableUnsafeUTF7Encoding too. See this post, if you want to see all new properties in net5.0
> [#13755 (comment)](https://github.com/PowerShell/PowerShell/issues/13755#issuecomment-704948203)

Given the security vulnerabilities noted, wouldn't it be better not to use the Binary Formatter serialization at all? Or is this simply not possible? If not, I guess the .NET team should be aware of PowerShell being impacted by this.

**Comment by fMichaleczek** [comment]
@leonardder Good news ! Nothing is deprecrated, it's only to force people to know what they do. I think it's better to separate this issue from the BinaryFormatter security discussion, could you : 
- change the title to something more precise like "PowerShell Remoting isn't working in the Asp.Net Core SDK 5.0 " and close it.
- open a new one to ask PSTeam about PowerShell and BinaryFormatter security guide
https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide

@PaulHigin I confirm it will break too in dotnet sdk in the future
see https://github.com/dotnet/sdk/pull/12434#issuecomment-657867794

**Comment by leonardder** [comment]
> @leonardder Good news ! Nothing is deprecrated, it's only to force people to know what they do. 


From https://github.com/dotnet/designs/pull/141#issue-448990656

> Eventually all code within the dotnet repo is to be migrated fully off of BinaryFormatter, at which point the implementation is to be removed from the runtime.

I hear your request to close the current issue, but I think there are still two outstanding points:

1. Your idea in https://github.com/PowerShell/PowerShell/issues/14032#issuecomment-725800387 to add this to all projects.
2. The fact that this is currently not documented on PowerSHell's end. Or do you think that falls in scope of another issue to be created?

**Comment by fMichaleczek** [comment]
@leonardder 
> 1. Your idea in [#14032 (comment)](https://github.com/PowerShell/PowerShell/issues/14032#issuecomment-725800387) to add this to all projects.

After reading the document [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), it's wrong. BinaryFormatter will be disabled by default across all project types for .NET 7  (Nov 2022).

> 2. The fact that this is currently not documented on PowerSHell's end. Or do you think that falls in scope of another issue to be created?

I created issues to ask : 
- to define a PowerShell BinaryFormatter Obsoletion Strategy https://github.com/PowerShell/PowerShell/issues/14054
- to document this issue https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6879

**Comment by leonardder** [comment]
Thanks for this. Closing as requested.
