### ISSUE TITLE
Tab completion now shows files in different order

### ISSUE THREAD

**Issue by jiasli** [PowerShell/PowerShell#14048]
## Steps to reproduce

Create a folder with 3 files:

- a1.ps1
- a2.ps1
- a-b.ps1

![image](https://user-images.githubusercontent.com/4003950/98905809-025b6c00-24f7-11eb-8b9f-f81d07585ad9.png)

Press <kbd>a</kbd>, then <kbd>TAB</kbd>.

## Expected behavior

The tab completion should show file candidates in the same order as previous versions (up to 7.0.3) of PowerShell, File Explorer and Command Prompt, in the order of 

- a1.ps1
- a2.ps1
- a-b.ps1

## Actual behavior

The latest PowerShell shows file candidates in different order compared to previous versions (up to 7.0.3) of PowerShell, File Explorer and Command Prompt.

Actual order in PowerShell 7.1.0:

- a-b.ps1
- a1.ps1
- a2.ps1

## Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It was in v7.1.0-preview.3 and .Net 5.0 Preview4
It came from .Net and it is by design. 
Before:
```powershell
"a-b.ps1","a1.ps1","a2.ps1" | sort
a1.ps1
a2.ps1
a-b.ps1
```
After:
```powershell
"a-b.ps1","a1.ps1","a2.ps1" | sort
a-b.ps1
a1.ps1
a2.ps1
```

**Comment by jiasli** [comment]
Thank you for the rapid response. Is this documented? Why is this change introduced which is inconsistent with Windows File Explorer.

**Comment by iSazonov** [comment]
PowerShell team documents only changes in the repository. Since it is not change in PowerShell you could look .Net documentation https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0. If you do not find this information there, then you can create a request in .Net Runtime repository.

**Comment by tgmayfield** [comment]
Can the sorting be changed to use StringComparison.OrdinalIgnoreCase, which has [consistent behavior across runtimes and operating systems](https://blog.jetbrains.com/dotnet/2020/05/13/sorting-order-depends-runtime-operating-system/)?
