### ISSUE TITLE
LTS version number in the README for Windows is wrong

### ISSUE THREAD

**Issue by aetos382** [PowerShell/PowerShell#14045]
The [README](https://github.com/PowerShell/PowerShell/blob/f4ac0935c530be5b33c3fc043b574b95d41a1ca5/README.md#get-powershell), updated for the release of PowerShell 7.1, links the Windows version of LTS download to 7.1.0.
PowerShell 7.1 depends on .NET 5, and .NET 5 is not an LTS release.
Looking at the [documentation](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/bba4088cf63b89957edacc43551f0abb5bab4e4e/reference/docs-conceptual/PowerShell-Support-Lifecycle.md#powershell-releases-end-of-life), the EOL in 7.1 is earlier than 7.0.

**Comment by fMichaleczek** [comment]
The blog is clear : 7.1 isn't LTS.
https://devblogs.microsoft.com/powershell/announcing-powershell-7-1/

@aetos382 can you rename your issue to something like "LTS version number in the README is wrong"

**Comment by SteveL-MSFT** [comment]
Looks like a "search and replace" mistake.  Will get this fixed.
