### ISSUE TITLE
Can't install from Store

### ISSUE THREAD

**Issue by leotsarev** [PowerShell/PowerShell#14049]
# Steps to reproduce
Go to https://www.microsoft.com/store/apps/9MZ1SNWT0N5D URL marketed both in docs https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1 and blogpost here https://devblogs.microsoft.com/powershell/announcing-powershell-7-1/

## Expected behavior
Store page for powershell

## Actual behavior

We are sorry, the page you requested cannot be found.

The URL may be misspelled or the page you're looking for is no longer available.

Also, I can't found Powershell in store using search

**Comment by fMichaleczek** [comment]
@leotsarev You can close your issue, the page is now available.

**Comment by musm** [comment]
Is the Windows Store version the recommended installation route for Windows users over the msi/zip's provided in the release page? Perhaps it would be a good idea to make some comment in the README to this point.

**Comment by user8446** [comment]
I just installed from the Microsoft Store and found a few bugs: https://github.com/PowerShell/PowerShell/issues/14059

**Comment by fMichaleczek** [comment]
@musm @user8446 You understand that Store means sandboxed or at least packaged in a old school metro app in a special folder ? Windows Store has evolved but I'm not sure you can do everything you want. Also remember how store apps update in background. If you are an admin, you dont want. This version is not for people who open issues on github 😅 It's for casual gamer !
