### ISSUE TITLE
v7.1.0 MSIX

### ISSUE THREAD

**Issue by juvtib** [PowerShell/PowerShell#14053]
What is the status of the MSIX release?

**Comment by iSazonov** [comment]
You can install 7.1 from Store.

**Comment by juvtib** [comment]
I'm not interested in the Microsoft Store. I'm asking specifically about a follow-up to the 7.0.2 MSIX builds which were discontinued with no public explanation.

**Comment by iSazonov** [comment]
From https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.5
> Note: The MSIX is currently blocked by other factors external to the PS team. We're waiting on a solution before we can ship another MSIX. In the meantime, please use the MSI packages.

**Comment by juvtib** [comment]
Will I see a `PowerShell-7.1.0-win-x64.msix` from GitHub?
Is Microsoft supporting MSIX packages from GitHub? 
What has happened in the last four months?
