### ISSUE TITLE
[Ubuntu 20.04] PowerShell v7.1.0 is not available in the packages.microsoft.com repository

### ISSUE THREAD

**Issue by al-cheb** [PowerShell/PowerShell#14056]
What is the status of updating powershell packages in the https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/p/ repository for Ubuntu 20.04?

**Comment by kilasuit** [comment]
Likely as it was with the Microsoft store it is going through an additional cycle of internal review testing first but perhaps @SteveL-MSFT or @TravisEz13 can comment further

**Comment by TravisEz13** [comment]
Duplicate of #12626

**Comment by kilasuit** [comment]
FYI @al-cheb  it is now available to install via that method as shown in the docs https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#installation-via-direct-download---ubuntu-2004
