### ISSUE TITLE
Default Powershell Terminal color choices on macOS are nigh-unreadable

### ISSUE THREAD

**Issue by johncwelch** [PowerShell/PowerShell#14069]
Please take a closer look at the default colors used for the powershell terminal on macOS. It's an unreadable mess, particularly in dark mode.

Ideally, the powershell terminal window should use as many of the user's terminal defaults as possible, and where that's not feasible/practical, look at the current default mode, dark mode or not, and make sure the default colors are as high contrast with the background color as possible.

**Comment by iSazonov** [comment]
@johncwelch Please share more info about your scenario(s) and maybe screenshots.

**Comment by iSazonov** [comment]
Or maybe you say about PSReadline? You can configure PSRL.

**Comment by johncwelch** [comment]
*   I’m kind of pleased to say that it looks like the 7.1 release fixed this. It’s legible sans customizations, so feel free to close. And thank you!

--
"The Mac OS X kernel should never panic because, when it does, it seriously inconveniences the user."

**Comment by iSazonov** [comment]
It seems now you use new PSRL 2.1.
