### ISSUE TITLE
Ubuntu 20.04 - No Installation candidate

### ISSUE THREAD

**Issue by dsolodow** [PowerShell/PowerShell#14062]
Followed steps here:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#ubuntu-2004

Received:
user@localhost ~> sudo apt-get install powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package powershell is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'powershell' has no installation candidate

**Comment by Izzmo** [comment]
Same issue here, except mine says

> E: Unable to locate package powershell

**Comment by anmenaga** [comment]
I believe team members are currently working on this.

**Comment by dsolodow** [comment]
Package is now available in the repo.
