### ISSUE TITLE
In RestrictedLanguage mode, an instance of a given type cannot be created with a cast, but can be created with New-Object

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14071]
Note: I may have a misconception here, but the difference in behavior strikes me as unusual.

## Steps to reproduce

```powershell
try {

  $ps = [powershell]::Create()
  $ps.Runspace.SessionStateProxy.LanguageMode = 'Restricted'

  try {
    $ps.AddScript('[regex] "."').Invoke()
    $ps.Streams.Error | Write-Warning
  }
  catch { Write-Warning $_ }

  $ps.Commands.Clear(); $ps.Streams.ClearStreams()

  try {
    $ps.AddScript('New-Object regex "."').Invoke()
    $ps.Streams.Error | Write-Warning
  }
  catch { Write-Warning $_ }

}
finally { $ps.Dispose() }
```

## Expected behavior

Both attempts to create a `[regex]` instance should fail,  because it appears that `[regex]` is not on an apparent, but undocumented whitelist of permitted types (the whitelist is only documented for `ConstrainedLanguage`); by contrast, a type such as `[int]` can be constructed successfully with either method (`[int] 0` and `New-Object int`).

## Actual behavior

The cast method fails, whereas the `New-Object` method succeeds:

```none
WARNING: Exception calling "Invoke" with "0" argument(s): "At line:1 char:1
+ [regex] "."
+ ~~~~~~
+ The type regex is not allowed in restricted language mode or a Data section."

Options RightToLeft MatchTimeout
------- ----------- ------------
   None       False -00:00:00.0010000
```

## Environment data

```none
PowerShell Core 7.1.0
```

**Comment by fMichaleczek** [comment]
@mklement0 It affects all accelerators ? I try PSModuleInfo, same

```
try {

  $ps = [powershell]::Create()
  $ps.Runspace.SessionStateProxy.LanguageMode = 'Restricted'

  try {
    $ps.AddScript('[psmoduleinfo]::new($true)').Invoke()
  }
  catch { Write-Warning $_ }

  $ps.Commands.Clear(); $ps.Streams.ClearStreams()

  try {
    $ps.AddScript('New-Object psmoduleinfo $true').Invoke()
  }
  catch { Write-Warning $_ }

}
finally { $ps.Dispose() }
```

Same behavior on PS5.1

**Comment by mklement0** [comment]
No, there are types that do work, such as `[int]`.

[`about_Language_Modes`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Language_Modes) only talks about a whitelist of permitted types for `ConstrainedLanguage`, but it looks like there is also one - a more restrictive one - for `RestrictedLanguage`, which seems to surface only with the casts (note that you cannot call `::new()` in `RestrictedLanguage` mode, because no member access is allowed).

(Also, it's not about type _accelerators_ per se; you get the sam behavior if you use `[System.Text.RegularExpressions.Regex]`).

**Comment by fMichaleczek** [comment]
Import-LocalizedData use it.

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Import-LocalizedData.cs#L173

After reading the 'about language modes', everything is working as described. You are only allowed to use command.

**Comment by mklement0** [comment]
Look at the error message:

> The type regex is not allowed in restricted language mode or a Data section.

Yet you can create an instance with `New-Object`.

So at the very least there is an inconsistency - and I don't know what the true intent is.

**Comment by mklement0** [comment]
Also: `[int] 42` works, for instance. Also note in addition to commands _expressions_ are allowed, and a cast is an expression.

Furthermore: `ConstrainedLanguage`, which is generally _less_ restrictive, does not exhibit the same discrepancy; e.g., both `[System.IO.FileInfo] "/"` and `New-Object System.IO.FileInfo "/"` trigger the same error: `Only core types are supported in this language mode`

**Comment by iRon7** [comment]
I was about to raise a similar issue based on the Docs issue [Incomplete Allowed Types list #6884](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6884) I created yesterday:

```PowerShell
$ExecutionContext.SessionState.LanguageMode = 'ConstrainedLanguage'
$test = [System.Collections.Specialized.OrderedDictionary]@{ a = 1 }
```

>  InvalidArgument: Cannot convert value to type "System.Collections.Specialized.OrderedDictionary".
>  Only core types are supported in this language mode.

But I am allowed to do this:
```PowerShell
$test = [ordered]@{ a = 1 }
$Test.PSTypeNames
System.Collections.Specialized.OrderedDictionary
System.Object
```

**Comment by mklement0** [comment]
@iRon7, it sounds like the _syntactic sugar_ is bypassing the permitted-type check (`[ordered] @{ ...}` isn't a regular cast).

**Comment by briantist** [comment]
IIRC (I ran into this years ago), this is also true for `New-Object PSObject` vs `[pscustomobject]@{}`

**Comment by iSazonov** [comment]
I set Issue-Bug and WG-Security until team triages this.

**Comment by vexx32** [comment]
This sounds like a case where `New-Object` itself should have the same type restrictions applied for restricted language mode -- or else it's just an accepted security hole, which seems... well, odd.

**Comment by fMichaleczek** [comment]
@vexx32 there is precheck? and runtime check, i dont think runtime check in restricted mean no object, it only allows a list of cmdlet, some typecode 
type and refuse scriptblock. The default is configured for Data first, so the default whitelist is not the default case, we should have in mind (like class for DSC, etc ...😏). RestrictedLanguage means  NoLanguage configured for Data and Constrained is another area in the runspace linked to security mode.

**Comment by TravisEz13** [comment]
Security group looked at this but we need more time.

**Comment by iRon7** [comment]
Before making any decision in any direction, also consider this...

In constrained mode I am obviously able to create a specific object collection as a result from e.g. a `where` method:

```PowerShell
$ExecutionContext.SessionState.LanguageMode = 'Constrained'
$Where = (1..5).Where({ $_ % 2 })
$Where.PSTypeNames
System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Management.Automation, Version=7.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
System.Object
```

But I am not allowed to build the same type in constrained mode using an initializer, like:
```PowerShell
$ExecutionContext.SessionState.LanguageMode = 'Constrained'
[Collections.ObjectModel.Collection[psobject]](1, 3, 5)
```

> InvalidArgument: Cannot convert value to type "System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject]". Only core types are supported in this language mode.

**Comment by TravisEz13** [comment]
@iRon7 
Security Working Group:  `.Where` is allowed and the type being return is safe, but we still aren't going to allow you to create it yourself.  This is consistent with how Constrained language (CL) works.

In CL you can't run constructors, unless we have done a security evaluation of the type, but other cmdlets or operator can return types that you are not allowed to create yourself, because they don't allow you to run arbitrary constructor.  Instead, they run a constructor that has been evaluated.

**Comment by TravisEz13** [comment]
Security Working Group
This is not a security issue because restricted language mode does not make a security promise.

This is a bug because `new-object` will allow you to create a type but a cast will not allow the same time.

Why are you using restricted language mode?  Be aware of the differences in language modes:  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.1

**Comment by mklement0** [comment]
@TravisEz13 

> This is not a security issue because restricted language mode does not make a security promise

Aren't language modes _all_ about security? If not, what purpose do they serve? Are only _some_ modes security-relevant? If so, which?
The linked [`about_Language_Modes`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Language_Modes) conceptual help topic doesn't provide any clues.


> This is a bug because new-object will allow you to create a type but a cast will not allow the same time.

So what is the resolution here? 

* if you cannot _cast_ to a type, don't allow `New-Object` to instantiate it either?
* if `New-Object` allows you to in instantiate a type, casts should allow it too?
* What is the list of approved types in `RestrictedLanguage` mode, given that the error message `The type regex is not allowed in restricted language mode or a Data section.` implies that there is one?

**Comment by TravisEz13** [comment]
> Aren't language modes all about security? If not, what purpose do they serve? Are only some modes security-relevant? If so, which?
The linked about_Language_Modes conceptual help topic doesn't provide any clues.

Constrained language mode running under WDAC is a security boundary.
Constrained language mode running under AppLocker is a defense in depth feature.

These aren't documented in the language mode because the language mode by in self does not make a security feature.  Only when paired with another security feature.

> if `New-Object` allows you to in instantiate a type, casts should allow it too?

I believe this is the correct fix.

**Comment by mklement0** [comment]
Thanks, @TravisEz13 

So in terms of _documentation_ it sounds like the `about_Language_Modes` topic needs updating to mention which security features the various language modes can / need to be paired with in order to provide actual security.
The only thing currently mentioned there is "User Mode Code Integrity (UMCI)" for Windows RT-based  ARM devices (isn't Windows RT defunct?)

> > if `New-Object` allows you to in instantiate a type, casts should allow it too?

> I believe this is the correct fix.

However, given that `New-Object regex '.'` succeeds in `RestrictedLanguage` mode, allowing `[regex] '.'` directly contradicts the error message, `The type regex is not allowed in restricted language mode or a Data section.`:

* Is the error message incorrect?

* Or is there indeed a whitelist of permitted types that should be enforced?

**Comment by TravisEz13** [comment]
> The only thing currently mentioned there is "User Mode Code Integrity (UMCI)" for Windows RT-based ARM devices (isn't Windows RT defunct?)

UMCI became [Windows Defender Application Control (WDAC)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create) which is a Windows 10 feature (you can see UMCI on that WDAC page.)

**Comment by TravisEz13** [comment]
> However, given that New-Object regex '.' succeeds in RestrictedLanguage mode, allowing [regex] '.' would directly contradict the error message The type regex is not allowed in restricted language mode or a Data section.:

I'd recommend someone investigate creating a fix and recommend.  There may be variation type by type and I'm not prepared to answer until I see proposed code changes.

**Comment by PaulHigin** [comment]
Security Working Group: The difference of behavior between RestrictedLanguage and ConstrainedLanguage is expected because RestrictedLanguage is used for a different purpose, which no longer exists in PowerShell.  There is no issue with ConstrainedLanguage mode which we rely on for application control, so the decision here is 'Won't Fix'.
