### ISSUE TITLE
Feature Request: Strict import scope and function signature semantics

### ISSUE THREAD

**Issue by cveld** [PowerShell/PowerShell#14084]
## Summary of the new feature/enhancement

The current version of PowerShell is actually a very runtime driven framework. Function calls are only checked runtime whether the function is present and the parameters are met.
Import-Module instructions only execute runtime and there is no guidance design time which functions will be pulled into the current scope.

What we like to see is a more design time driven experience such as frameworks as TypeScript Nodejs.
The benefit of the EcmaScript module system is that you know design time which functions you are pulling into scope. Additionally, the import process of Nodejs is much faster than PowerShell.
The benefit of TypeScript is that function calls are validated design time. When a parameter or return type is not met, the file simply does not get compiled.
PowerShell should block any function use that is not coming from an import statement. TypeScript nodejs files simply don't compile when unknown functions are being called.

E.g.
```PowerShell
# Import specific functions / cmdlets
Import Get-AzResourceGroup, Get-AzKeyVault from Az
Get-AzResourceGroup -Name xyz

# Import the whole set of exported functions / cmdlets to a variable
Import * as $Az from Az
$Az.Get-AzResourceGroup -Name xyz

# This should not compile / execute and should throw a parameter mismatch error
Get-AzResourceGroup -RandomParameter
```

**Comment by SteveL-MSFT** [comment]
Can't you get what you want already by using [$PSModuleAutoLodingPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.1#psmoduleautoloadingpreference)?

**Comment by cveld** [comment]
Yes we already always import explicitly. This still does not guarantee if the function signature is called correctly.

Interesting to learn the `ModuleQualified` setting though, have not seen it before, I will discuss this with my team.

**Comment by SteveL-MSFT** [comment]
I think if you want strict validation of function signatures, that might be better suited as a PSScriptAnalyzer rule cc @rjmholt @JamesWTruher 

PowerShellGet v2 depends on PackageManagement module.  Since the call to PackageManagement cmdlet is fully qualified, I would have expected that to work...

`Az` module is just a meta-module that loads all the other actual Az modules, so that behavior is currently expected.  I believe individual Az modules end up importing `Az` due to cross dependencies across Az modules.  If you're goal is to restrict the cmdlets/functions that can be called within a script, you should look at [constrained runspaces](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/creating-a-constrained-runspace?view=powershell-7.1).  The easiest way to do this via script is [Just Enough Administration](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/jea/overview?view=powershell-7.1).

**Comment by cveld** [comment]
> I think if you want strict validation of function signatures, that might be better suited as a PSScriptAnalyzer rule cc @rjmholt @JamesWTruher

Makes sense! I would like to learn how I could establish this.

> If you're goal is to restrict the cmdlets/functions that can be called within a script, you should look at constrained runspaces. The easiest way to do this via script is Just Enough Administration.

No this is too much for us. We just want to have proper "compile-time" support. Additionally, as as nice to have we would like to see better semantics on the `Import-Module` side, not cluttering the current scope so much, and much faster processing. Maybe we are spoiled too much by the EcmaScript module way of working 😉

**Comment by SeeminglyScience** [comment]
I've been interested in the idea of a more strict, more maintainable style of import for awhile as well.

I'm not sure it can be within PowerShell itself though. Languages with multiple dialects are pretty difficult to maintain.  Some good evidence of this within PowerShell itself is how neglected `Set-StrictMode` has become over time. I think for something like this to happen, it would really to be a transpiler (like typescript) and probably would need to be developed and maintained by a different org.

There's definitely some potential there, but it's really difficult to recommend anyone take on that work when you could just as easily make a C# binary module instead.

**Comment by powercode** [comment]
Classes provide you with a more structured, early checked model. Have you tried using these? Also quite a bit faster if you don't require all the features of the parameter binder.

**Comment by cveld** [comment]
We are using the Az modules heavily. So we really would like to see the strictness applied to the Az modules as well.

@powercode It seems PowerShell is lacking named parameters with class methods. So readability is impacted if we move away from regular functions.

@SeeminglyScience I guess c# would be an option if we were able to just ship the c# as a script.  There was already csx, and now with c# there is this top-level program feature.

We are also considering moving to nodejs which gives a perfect solution for all of this. Unfortunately the Az modules nodejs equivalent last time we checked (August 2020) were not very mature and incomplete (https://azure.github.io/azure-sdk-for-js/). Nodejs brings us:
1. Compatibility with Azure Pipelines; it is providing a nodejs task runner;
2. Perfect module import semantics;
3. Strict function signature checking.
I guess we need to revisit this area. It looks like the past few months they didn't stand still!

If we would be able to mix our PowerShell with dotnet code, I guess that we then would hit the dotnet Azure sdk also lagging behind the az cli and az PowerShell modules surfaces.

**Comment by powercode** [comment]
Much of the readability issues can be countered with good naming of variables. But in general, there is a tension between being a good shell and a good language. There are areas where the late binding and type conversion of PowerShell is more of a bug than a feature.
When I find myself in that situation, I write the code in C# and use PowerShell where it really shines, to glue different pieces together.

**Comment by cveld** [comment]
Would there be an opportunity for me to connect with a developer of the PowerShell vscode extension? I am eager to explore the changes required myself.

It would make perfect sense to me at least to have an optional switch in the PowerShell strictness mode to enable both of the features mentioned in the original post, being:
1. Strict import semantics
2. Strict function signature linting

Ad 2. Currently you already get very nice intellisense when writing a cmdlet invocation, i.e. vscode knows perfectly which parameters are allowed. Would be a small adjustment to falsify unexpected parameters.

Ad 1. Maybe there is some intermediary easy solution? For example, we could first go for some comment driven metadata to steer the linting engine to the right file or module for the specific cmdlet and block the linting process to freely peek in every file available in the workspace and psmodule path.

@powercode do you have an example repo where you lay out your way of working where you mix and match PowerShell and c#? And what is your assessment of the maturity of the Azure .NET SDK? To what extent is it lagging behind the latest REST APIs.

**Comment by SeeminglyScience** [comment]
> Would there be an opportunity for me to connect with a developer of the PowerShell vscode extension? I am eager to explore the changes required myself.

You'd want to check out PSScriptAnalyzer.  There isn't much related logic in the VSCode extension nor even the language server (PowerShellEditorServices).

> Ad 2. Currently you already get very nice intellisense when writing a cmdlet invocation, i.e. vscode knows perfectly which parameters are allowed. Would be a small adjustment to falsify unexpected parameters.

VSCode only knows because the PowerShell itself tells it though (through the `SMA.CommandCompletion` API), and only on demand based on cursor location.  That kind of analysis for an entire document would be very expensive, especially once you get into type inference (assuming you want to check input signature). That's not to say that that type of analysis can't be done incrementally, but there is currently no tooling for that.

> Ad 1. Maybe there is some intermediary easy solution? For example, we could first go for some comment driven metadata to steer the linting engine to the right file or module for the specific cmdlet and block the linting process to freely peek in every file available in the workspace and psmodule path.

VSCode uses the same runspace that the PowerShell Integrated Console uses. So you can somewhat control state by changing module autoloading preference and/or manually importing modules. There is no static analysis way to do that though with the exception of fully module qualified commands.

**Comment by cveld** [comment]
@SeeminglyScience albeit unrelated to my OP, if the runspace is shared, then there are two things not clear to me:
1. Why is the completion support on the cmdlets so different in the editor and on the prompt? On the prompt is so much better, so much faster.
2. Where is the pesky delay coming from when I press F8 from the editor? Sometimes it takes many seconds before the selected text get passed to the prompt.

**Comment by SeeminglyScience** [comment]
> 1. Why is the completion support on the cmdlets so different in the editor and on the prompt? On the prompt is so much better, so much faster.
> 2. Where is the pesky delay coming from when I press F8 from the editor? Sometimes it takes many seconds before the selected text get passed to the prompt.

Bugs.  PowerShell/PowerShellEditorServices#1295 is probably the thread to follow.

**Comment by rjmholt** [comment]
> I think if you want strict validation of function signatures, that might be better suited as a PSScriptAnalyzer rule cc @rjmholt @JamesWTruher

I've done some work toward this. Requires investment in a static parameter binding approximation algorithm. Which PSScriptAnalyzer has general need of. But this plus more performant profiles would be the silver bullet for static analysis.

**Comment by cveld** [comment]
@rjmholt Has there been any recent development? Many of our bugs are caused by insufficient static analysis. Would it be easy to start with some manual decoration language so that you can help the language service? If we were able to adopt something like the TypeScript module import semantics, then the language service can limit its analysis to the particular file.

**Comment by rjmholt** [comment]
No new developments here.

> Would it be easy to start with some manual decoration language so that you can help the language service? If we were able to adopt something like the TypeScript module import semantics, then the language service can limit its analysis to the particular file.

Unfortunately adopting new syntax or semantics is hard, and writing the analysis around it is also hard.

> Many of our bugs are caused by insufficient static analysis

Traditionally, static analysis will find bugs, but lack of it won't cause them.

**Comment by cveld** [comment]
@rjmholt you were mentioning in the August 2021 community call that some internal projects that have been building extra analysis rules for static analysis? Not suitable for general purpose, but maybe the various bits can be shared to build upon further? We are not using the dynamic nature of PowerShell to great extent. For us it is just a dotnet dialect and I guess the suggested `Use-StrictMode -Ultra` would be helpful to us 🙂

In the meanwhile if I find further time I will try to continue working on a simple custom analyzer that takes import statements inside comment conventions, combined with scraping the abstract syntax tree for function definitions. I started this exploration during past summer break.

**Comment by rjmholt** [comment]
>  that some internal projects that have been building extra analysis rules for static analysis? Not suitable for general purpose, but maybe the various bits can be shared to build upon further?

Yeah, I don't control that code but I've seen it and it's very very old and different. There's interest from the owning team to perform a gradual migration, at least of the easier parts. As a first example, see https://github.com/PowerShell/PSScriptAnalyzer/pull/1705.

> In the meanwhile if I find further time I will try to continue working on a simple custom analyzer that takes import statements inside comment conventions, combined with scraping the abstract syntax tree for function definitions. I started this exploration during past summer break.

So on this front, I've seen other examples of custom `#include` pragmas in scripts. `using module` and `using assembly` were meant to be the actual versions of this. But for the most part, my intuition is that analyzers should simply forbid things like:

- Using variables with `Import-Module` or `Export-ModuleMember`
- Using `*-Variable` cmdlets
- `*-*Item` cmdlets with variable/function providers
- Anything involving dynamic scope (variables not defined in the immediate scope)
- Probably a few other things I haven't thought of that allow you to dynamically create variables/functions

Once those become errors, you can statically reason about a lot more things.

At that point, you want constant folding (to propagate variable values, splatting, etc) and type inference:

https://github.com/PowerShell/PowerShell/blob/176303d172bcb0726e097ac5139de9f724ecec6b/src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs#L42-L50

You also need some concept of the modules available at runtime and the whole [command metadata](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.commandmetadata) for each exported command. That's needed to work out types and parameter binding. That essentially requires a manifest of well-known commands on each platform. I've done a fair amount of the work required for that as part of PSSA's [UseCompatibleCommands rule](https://github.com/PowerShell/PSScriptAnalyzer/blob/6222e409059664fa02097af5a79d332c4a26fecd/Rules/CompatibilityRules/UseCompatibleCommands.cs#L101-L152).

I've also seen things that try to follow through a script's dependencies and dot-sources as well, and those basically require static inference of the filesystem layout in a script/module's deployment environment.

Anyway, I don't see a huge reason to build a fresh analyzer from scratch here. PSSA is perfectly capable of providing the platform for a lot of this. But if you are interested, I [started some work to reform PSSA as a platform some time ago](https://github.com/PowerShell/PSScriptAnalyzer/tree/pssa2) but had to drop it to work on other things.

**Comment by cveld** [comment]
Are `InferTypeOf` and `StaticParameterBinder` readily available from the context of a PSSA rule?

Chris Dent provides the following PSSA rule in PowerShell which can be used as an example: https://github.com/indented-automation/Indented.ScriptAnalyzerRules/blob/main/Indented.ScriptAnalyzerRules/public/rules/UseSyntacticallyCorrectExamples.ps1

I have been put on two tracks here because I find it easier to explore this all within Visual Studio where everything is c#. The core PSSA rules are written with c# whereas PSSA provides custom rules through PowerShell. At least I am more familiar with the debugging experience inside Visual Studio compared to Visual Studio Code. I guess I should explore the debugging experience for PSSA rules in PowerShell a bit more.
