### ISSUE TITLE
Manifest RequiredModules does not honor provider-qualified path

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#14083]
I've run into trouble in the past with loading modules from a network share ("`\\server\share\...`"), when the current working directory is not a filesystem path (e.g. "`HKCU:\Software`"), and the module I'm trying to load references `$PSScriptRoot` (because the "`\\`" from the `$PSScriptRoot` gets interpreted by the registry provider or whatever is the provider for the current dir).

"Aha!" I said, "I'll just use a provider-qualified path!" (like "`filesystem::$PSScriptRoot\whatever`")

But it doesn't work. :'(

## Steps to reproduce

```powershell
mkdir BugRepro

@'
@{
RootModule = 'Repro.psm1'
ModuleVersion = '1.0'
RequiredModules = @( "filesystem::$PSScriptRoot\other.psm1" )
FunctionsToExport = '*'
}
'@ > .\BugRepro\Repro.psd1


@'
function hi { 'hi!' }
'@ > .\BugRepro\Repro.psm1


@'
function Hi2 { 'hi again!' }
'@ > .\BugRepro\other.psm1

ipmo -force -verbose .\BugRepro\Repro.psd1
```

## Expected behavior

It all works.

## Actual behavior

```none
VERBOSE: Loading module from path 'C:\temp\BugRepro\Repro.psd1'.
Import-Module: The specified module 'C:\temp\BugRepro\filesystem::C:\temp\BugRepro\other.psm1' was not loaded because no valid module file was found in any module directory.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.21257
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> when the current working directory is not a filesystem path (e.g. "HKCU:\Software")

I'd say it is a bug in Import-Module cmdlet.

**Comment by jazzdelightsme** [comment]
@iSazonov perhaps a second bug, then (because as shown in the repro steps, no non-filesystem provider use is required to hit *this* bug).

But I think it's actually an unfortunate "By Design" of the provider system: a path that starts with two whacks ("\\") does not mean "SMB share"; it means "something" relative to the current provider (only for the filesystem provider it means "SMB share").
