### ISSUE TITLE
Redirection Operators

### ISSUE THREAD

**Issue by pf35301** [PowerShell/PowerShell#14081]
## Steps to reproduce

For example:
```powershell
git --version 2> $null
```

## Expected behavior

I want to use Redirection Operators.

## Actual behavior

Sorry it's not English.
It's Japanese.
```powershell
D:\> git --version 2> $null
OperationStopped: ファンクションが間違っています。
```

"ファンクションが間違っています。" means "Wrong function"

## Environment data

```None
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by kvprasoon** [comment]
If you are redirecting stream 2 to a file, then AFAIK, you have to redirect it to output stream (1), then use `>`

```
D:\> git --version 2>&1 > $null
D:\> $null = git --version 2>&1
```

**Comment by pf35301** [comment]
When I use `>`, I am said the same thing.

**Comment by kvprasoon** [comment]
Didn't get you. Are you getting error when using `>` ?
This is not a bug and better if you can start a discussion at https://powershell.org/forums/forum/windows-powershell-qa/
