### ISSUE TITLE
[environment] can't update environment variables

### ISSUE THREAD

**Issue by Vixb1122** [PowerShell/PowerShell#14093]
## Steps to reproduce
 Install powershell from [microsoft store](https://www.microsoft.com/store/productId/9MZ1SNWT0N5D)
```powershell

[environment]::setEnvironmentVariable('TEST_URL','http:url','User')
```

## Expected behavior
reopen shell
```
$env:TEST_URL 
```
output: http:url

## Actual behavior
reopen shell
```none
$env:TEST_URL
```
output is empty

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I believe it is MSIX sandbox limitation.

**Comment by Vixb1122** [comment]
@iSazonov 
Right，Please provide the necessary description in the [instructions](https://docs.microsoft.com//powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1#installing-the-msix-package).

**Comment by vexx32** [comment]
This behaviour is normal. `$env:VAR` only retrieves values from the current process environment.

Updating a user-scope environment variable never updates the current process environment; you have to do that explicitly, in either of the following ways:

```ps1
$env:TEST_URL = [Environment]::GetEnvironmentVariable('TEST_URL', 'User')
# or
[Environment]::SetEnvironmentVariable('TEST_URL', [Environment]::GetEnvironmentVariable('TEST_URL', 'User')
```

You can also opt to simply set it in the current process environment first, or do both at once:

```ps1
# current environment first
$env:TEST_URL = 'http:url'
[Environment]::SetEnvironmentVariable('TEST_URL', $env:TEST_URL, 'User')

# both at once
[Environment]::SetEnvironmentVariable('TEST_URL', ($env:TEST_URL = 'http:url'), 'User')
```

**Comment by Vixb1122** [comment]
@vexx32 
> There _may_ still be an MSIX specific limitation in play here, but the steps in the issue description will not work as expected in any version of PowerShell.

The ‘reopen shell’ operation that I missed in the issue description

Now, i can understand MSIX specific limitation.

run command in powershell installed from msix, and reopen shell and see `$env:TEST_URL`
![Snipaste_2020-11-15_11-06-56](https://user-images.githubusercontent.com/17810492/99162038-a5002e80-2733-11eb-9aec-80a2a45b64cc.jpg)

run command in windows powershell, and reopen shell and see `$env:TEST_URL`
![Snipaste_2020-11-15_11-08-50](https://user-images.githubusercontent.com/17810492/99162027-7da96180-2733-11eb-8be7-49b817899129.jpg)

**Comment by iSazonov** [comment]
If you open new session it is as any process works and as @vexx32 said it is not MSIX specific.

**Comment by sdwheeler** [comment]
@iSazonov This is MSIX specific. The MSIX sandbox virtualizes some registry access. `[Environment]::SetEnvironmentVariable('TEST_URL', 'http:url', 'User')` writes the value to the User registry, which is virtualized. So the change is not persistent across sessions.
