### ISSUE TITLE
New-PSDrive with a UNC path cannot be created.

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#1409]
## Steps to reproduce

New-PSDrive with a UNC path and credential. 
## Expected behavior

PSDrive is created.
## Actual behavior

Microsoft.VS.TTest.TestFailureException: There were error records output from the script. Id: DriveRootError,Microsoft.PowerShell.Commands.NewPSDriveCommand, Id: Microsoft.PowerShell.Commands.WriteErrorException,Assert, Id: DriveNotFound,Microsoft.PowerShell.Commands.RemovePSDriveCommand
 ---> System.IO.IOException: The specified drive root "\DEV-14390-219\TestNetworkPSDrive" either does not exist, or it is not a folder.
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-112-g3276846c401e0c2132cc260f89752b121c81abde
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by kort3x** [comment]
I have this issue occur randomly, as in sometimes the mapping works other times it just fails.

**Comment by alpeshvaghela123** [comment]
Is this issue resolved?

**Comment by joeyaiello** [comment]
Yeah, this works now. I just mounted a UNC path with a domain credential in `6.0.0-beta.1`.

**Comment by AdminValida** [comment]
I am not able to mount a cifs share. Could anyone please post a working example?

Regards
Richard

**Comment by joeyaiello** [comment]
Per [this blog post](https://blog.varonis.com/the-difference-between-cifs-and-smb/) or [this blog post](http://blog.fosketts.net/2012/02/16/cifs-smb/), do you really mean CIFS? I'm testing against what I believe is an SMBv3 share, and it works fine...

**Comment by MaximoTrinidad** [comment]
Yes @joeyaiello!

Trying to accomplishing the following CIFS example in PowerShell:

```
sudo mount.cifs //win10ent01/CrossPlatScripts /home/maxt/CrossPlatScripts -o user=maxt password=passwd01
```

In the above scenario you are mapping a Windows Shared folder to an empty existing folder. I tend to name the folder the same.
 
I can see some challenges integrating to PowerShell but it could be a nice one to have.
:)

**Comment by AdminValida** [comment]
Well, i have the following scenario:

Ubuntu 16.04 with powershell 6 installed, and i want to "mount" a share located at a Windows Server 2012. I want this to be done with New-PSDrive.

Is this possible?

I am able to mount the share with the bash mount command.

Regards
Richard
