### ISSUE TITLE
Circular dependency at runtime between System.Management.Automation and Microsoft.PowerShell.Security

### ISSUE THREAD

**Issue by Fs00** [PowerShell/PowerShell#14095]
While using only System.Management.Automation as a dependency for an application of mine (**without the entire SDK** because I didn't need it), I was getting sometimes a `NullReferenceException` that was thrown in this line of code:

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L51

because `type` was null.

Digging in the stack trace, I found out that the null reference was originated by the following instruction:

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L4072

The `securityDescriptorCommandsBaseType` variable gets passed to the method `GetMethodInfo`, which contains the return statement with the variable `type` shown above.

Once you know that the referenced type (`Microsoft.PowerShell.Commands.SecurityDescriptorCommandsBase`) belongs to the Microsoft.PowerShell.Security package, and that the latter depends on System.Management.Automation, it becomes apparent that [TypeResolver.ResolveType](https://github.com/PowerShell/PowerShell/blob/76cef3b299911ba264fef7a2f510dd633f36497d/src/System.Management.Automation/engine/parser/TypeResolver.cs#L489) was being used in place of `typeof` to avoid a circular dependency at compile time between the two assemblies.
The problem is that the circular dependency still exists and causes the NRE mentioned above when System.Management.Automation is used alone.

Therefore, since I think that probably that dependency can't be broken, I would propose to "loosen" it by adding a null-check that prevents all the code related to the `securityDescriptorCommandsBaseType` from being executed when Microsoft.PowerShell.Security assembly is not available (which should be lines [4074-4128](https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L4074L4128) or even 4074-4210, I'm not sure).

I'm willing to open a PR to mitigate this problem after receiving your feedback on it, since - unlike me - you know the context and the motivation of the code I mentioned throughout this issue.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please comment?

**Comment by Fs00** [comment]
@daxian-dbw A gentle reminder to prevent this issue from being forgotten in the mists of time :)

**Comment by Fs00** [comment]
Hello @daxian-dbw, could you please take a look at this and see if my proposed solution could be enough to solve it?
I don't want to bother you, but this issue is getting stale and I would like to see it fixed (if it's possible to).

**Comment by TravisEz13** [comment]
Currently, the security assembly is required.  We are looking at this type of feature in the future.

**Comment by Fs00** [comment]
Ok, so - if I understood correctly - the proper fix would consist in fully decoupling those two assemblies.

**Comment by Fs00** [comment]
Ok, so - if I understood correctly - the proper fix would consist in fully decoupling those two assemblies.

**Comment by TravisEz13** [comment]
I'll let @daxian-dbw  talk to what the correct fix is.
