### ISSUE TITLE
Get-WinUserLanguageList cmdlet fails

### ISSUE THREAD

**Issue by anthony-geoghegan** [PowerShell/PowerShell#14102]
Now that I’m using a Windows 10 laptop for working from home, I decided to try using PowerShell Core and discovered the following error when attempting to run the `Get-WinUserLanguageList` cmdlet. I’m not a programmer (mostly a GNU/Linux sysadmin) and I was never particularly proficient at PowerShell but this looks like C#/.NET error.

The `Get-WinUserLanguageList` cmdlet is provided by the `International` module which is listed as being compatible with `Core, Desktop`. The cmdlet works in Windows PowerShell 5.1 and not in PowerShell Core 7.1 so I hope I’m reporting this bug to the right place. If not, let me know where I should report this and if so, I hope I've provided enough relevant information.

## Steps to reproduce

Invoke the following cmdlet:

```powershell
Get-WinUserLanguageList
```

## Expected behaviour

Windows PowerShell 5.1 on the same machine returns details of the language list for the current user account:

```none
> Get-WinUserLanguageList -Verbose

LanguageTag     : en-IE
Autonym         : English (Ireland)
EnglishName     : English
LocalizedName   : English (Ireland)
ScriptName      : Latin
InputMethodTips : {1809:00000809, 1809:00001809}
Spellchecking   : True
Handwriting     : False
```

## Actual behaviour

```none
> Get-WinUserLanguageList -Debug
Get-WinUserLanguageList: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
```

## Environment data

```none
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


> Get-Command Get-WinUserLanguageList

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-WinUserLanguageList                            2.0.0.0    International


> (Get-Command Get-WinUserLanguageList).Source | Get-Module | Format-List -Property *

LogPipelineExecutionDetails : False
Name                        : International
Path                        : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\International\International.psd1
ImplementingAssembly        :
Definition                  :
Description                 :
Guid                        : 561544e6-3a83-4d24-b140-78ad771eaf10
HelpInfoUri                 : https://go.microsoft.com/fwlink/?linkid=285548
ModuleBase                  : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\International
PrivateData                 :
ExperimentalFeatures        : {}
Tags                        : {}
ProjectUri                  :
IconUri                     :
LicenseUri                  :
ReleaseNotes                :
RepositorySourceLocation    :
Version                     : 2.0.0.0
ModuleType                  : Manifest
Author                      : Microsoft Corporation
AccessMode                  : ReadWrite
ClrVersion                  : 4.0
CompanyName                 : Microsoft Corporation
Copyright                   : © Microsoft Corporation. All rights reserved.
DotNetFrameworkVersion      :
ExportedFunctions           : {}
Prefix                      :
ExportedCmdlets             : {[Get-WinAcceptLanguageFromLanguageListOptOut, Get-WinAcceptLanguageFromLanguageListOptOut], [Get-WinCultureFromLanguageListOptOut, Get-WinCultureFromLanguageListOptOut],
                              [Get-WinDefaultInputMethodOverride, Get-WinDefaultInputMethodOverride], [Get-WinHomeLocation, Get-WinHomeLocation]…}
ExportedCommands            : {[Get-WinAcceptLanguageFromLanguageListOptOut, Get-WinAcceptLanguageFromLanguageListOptOut], [Get-WinCultureFromLanguageListOptOut, Get-WinCultureFromLanguageListOptOut],
                              [Get-WinDefaultInputMethodOverride, Get-WinDefaultInputMethodOverride], [Get-WinHomeLocation, Get-WinHomeLocation]…}
FileList                    : {}
CompatiblePSEditions        : {Core, Desktop}
ModuleList                  : {}
NestedModules               : {Microsoft.InternationalSettings.Commands}
PowerShellHostName          :
PowerShellHostVersion       :
PowerShellVersion           : 5.1
ProcessorArchitecture       : None
Scripts                     : {}
RequiredAssemblies          : {}
RequiredModules             : {}
RootModule                  :
ExportedVariables           : {}
ExportedAliases             : {}
ExportedDscResources        : {}
SessionState                : System.Management.Automation.SessionState
OnRemove                    :
ExportedFormatFiles         : {}
ExportedTypeFiles           : {}

```

**Comment by kvprasoon** [comment]
You can import Windows PowerShell module in `WindowsPowerShell` mode which is available as a parameter for `Import-Module` cmdlet.

```
Import-Module -Name International -UseWindowsPowerShell -Verbose
```

**Comment by iSazonov** [comment]
@anthony-geoghegan The module is not in the repository. We could use Windows Feedback tool to report the issue.

/cc @anmenaga for information.

**Comment by doctordns** [comment]
WHY doesn't PowerShell 7.1 recognise this module as not working natively?  While I get that the team behind the module hasn't bothered to port to 7.x, shouldn't PowerShell force this module to use the compatibility solution.

It feels like compatibility is not a top issue going forward.

**Comment by Samuli3682** [comment]
I really don't understand....sorry...i just would like to get twrp to my mate 10 pro (bla-l29). I don't know how this TomTom get here

**Comment by anthony-geoghegan** [comment]
Thanks, @kvprasoon I wasn't aware of the `-UseWindowsPowerShell` option or [Windows PowerShell Compatibility](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.1)

@iSazonov I’ve used the Feedback Hub (that comes with Windows 10) to report this problem, under the *Input and Language* category, including a link to this GitHub issue.

**Comment by anmenaga** [comment]
> WHY doesn't PowerShell 7.1 recognise this module as not working natively? While I get that the team behind the module hasn't bothered to port to 7.x, shouldn't PowerShell force this module to use the compatibility solution.

PowerShell 7.1 has no way of knowing that the error is because of incompatibility. It very well may be a valid error coming out of business logic of cmdlet/module that is (mistakenly) marked as compatible with `Core`.
Module owners should fix compatibility declaration on the module.

**Comment by doctordns** [comment]
Maybe I was unclear. The cmdlet in question is in the International module, which is in System32. As such, I would have expected this to be loaded into PSWInCompat session like so many other modules.  If you manually import the module using ```-UseWindowsPowerShell```, the cmdlet works fine, via the implicit remoting.  In this case, Pwsh 7.1 is seeing this as Core compatible so loads it natively where it, of course, does not work and gives the observed error message. 

I do not know why Pwsh 7.1 is not recognizing this as a module that needs to be loaded using the compatibility solution.

**Comment by anmenaga** [comment]
Pwsh 7 is seeing this as Core compatible (i.e. it is Not using compatibility solution to load it) because the module is **incorrectly** declares itself as Core-compatible.
It has `CompatiblePSEditions=@("Core","Desktop")` in `psd1` file. It is wrong. It should be `CompatiblePSEditions=@("Desktop")` if the module is known to be Not working in PS Core.
Please note `Unless the module manifest indicates that module is compatible with PowerShell Core...` in this quote from [About Windows PowerShell compatibility](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.1):
```
LONG DESCRIPTION
Unless the module manifest indicates that module is compatible with PowerShell Core,
modules in the %windir%\system32\WindowsPowerShell\v1.0\Modules folder
are loaded in a background Windows PowerShell 5.1 process
by Windows PowerShell Compatibility feature.
```

So at high level the process is:
When `-UseWindowsPowerShell` parameter is used - user's intent is perfectly clear, so compatibility solution is used immediately to load the module (regardless of what module manifest says about module compatibility).
When `-UseWindowsPowerShell` parameter is Not specified, PS will first check module manifest. If it finds `Core` value in `CompatiblePSEditions` then PS will load the module directly, if the value is not there - it will use compatibility solution to load it.

**Comment by fgimian** [comment]
Still broken on the very latest beta:

```powershell
PowerShell 7.2.0-preview.8
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Program Files\PowerShell\7-preview> Get-WinUserLanguageList
Get-WinUserLanguageList: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
```

@iSazonov While this is external, it is affecting PowerShell and has resulted in broken functionality that was working on the 7.0.x releases.  Can we reopen this to track the fix?

We're at almost a year since the issue was opened and I suspect it has gone off the radar because it is closed.

Issues like this really should be considered the highest priority should they not?  Because anyone upgrading to 7.1.x+ will literally have scripts stop working.

Thanks heaps
Fotis

**Comment by doctordns** [comment]
It works here, both in Preview.8, and the build of the day (from last wed).

**Comment by iSazonov** [comment]
> @iSazonov While this is external, it is affecting PowerShell and has resulted in broken functionality that was working on the 7.0.x releases. Can we reopen this to track the fix?

The module (International) is not in the repository and we can do nothing here.
The module is not compatible with PowerShell Core (see International.psd1).
The module is a component of Windows.

Please use Windows feedback tool to report the issue.
