### ISSUE TITLE
Port FileSystem tests for NTFS alternate streams

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#1410]
## Steps to reproduce

Providers/Providers tests. 
.\runlite -suite Providers.FileSystemProvider.AlternateDataStreams -pri  -test ClearContent
## Expected behavior

NTFS alternate streams work as expected on Windows PowerShell.
## Actual behavior

Cannot find path 'C:\Users\DUser1\AppData\Local\Temp\tmp635C.tmp:Stream2' because it does not exist.
System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\DUser1\AppData\Local\Temp\tmp635C.tmp:Stream2' because it does not exist.
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-112-g3276846c401e0c2132cc260f89752b121c81abde
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment]
@adityapatwardhan same as the other one: is this still relevant? Do we have a repro that we can run without Lite?

**Comment by adityapatwardhan** [comment]
The test needs to be ported.
