### ISSUE TITLE
PowerShell 7.1.0 is not searching the current path directory (.) in the environmental path. 

### ISSUE THREAD

**Issue by timkgithub** [PowerShell/PowerShell#14106]
### 1. Add the current directory ('.') to your the PATH variable
```powershell
   PS> $env:PATH = $env:PATH + ';.'
```
View the search directories

```powershell
   PS> $env:Path -split ';'
```
### 2. Create a script in a test directory

Example script:

```powershell
    PS> Write-Output "'Hello!'" | Set-Content Show-Hello.ps1
```

### 3. Run the script from the cmd host.

```powershell
   PS> Show-Hello
```

## Expected behavior

```none
Hello!
```

## Actual behavior

```none
Show-Hello: The term 'Show-Hello' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [3,General]: The command Show-Hello was not found, but does exist in the current location. PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\Show-Hello". See "get-help about_Command_Precedence" for more details.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
I assume that this was the desired behaviour, if you want to run something in the current directory you need to prefix it with `./` (`.\` on Windows).

**Comment by vexx32** [comment]
Yep, the error message emits that suggestion as well:
```
Suggestion [3,General]: The command Show-Hello was not found, but does exist in the current location. PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\Show-Hello". See "get-help about_Command_Precedence" for more details.
```

(from the OP)

**Comment by timkgithub** [comment]
I question whether this should be the desired behavior for security reasons.

To be clear, all other directory nodes will be searched under PowerShell 7.1.0, *EXCEPT* the current directory ('.' or '.\').

	$env:Path = <DIR1>;<DIR2>;...<DIRN>

Why not allow '.' paths in the search path ($env:PATH) variable?

If you read the 'About Command  Preferences' document:

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_precedence?view=powershell-7.1

Here it states:

_As a security feature, PowerShell does not run executable (native) commands, including PowerShell scripts, **unless the command is located in a path that is listed in the Path environment variable $env:path** or unless you specify the path to the script file._

I need some clarification why PowerShell v7.1.0 will no longer execute paths using the current directory (or any path using a '.').

Thank you.

**Comment by vexx32** [comment]
"no longer"? Was there a version of PowerShell this worked?

In my experience, it's always been this way for PowerShell.

**Comment by timkgithub** [comment]
It sounds like you are not aware or have never set up your environment path to search for PowerShell scripts. This is a very useful feature to customize your PowerShell environment.

The environmental search path for '.' works under 5.x, 6.x, and 7.0.x, but does not search '.' under 7.1.1.

|  PowerShell Version | $env:Path - Search current directory allowed? |
| :--- | :---- |
|  5.x | YES |
|  6.x | YES |
|  7.0.x | YES |
|  7.1.0 | NO |

**Comment by vexx32** [comment]
Yeah, personally I've never felt the need. Thanks for clarifying that!

I'm unsure if this was a regression or an intentional change, though. @iSazonov, do you know of any PRs that went in during the 7.1 release cycle that may have altered this behaviour?

**Comment by iSazonov** [comment]
> $env:PATH = $env:PATH + ';.'

@timkgithub Could you please make this _before_ you start pwsh and then check again?

**Comment by timkgithub** [comment]
I did some more testing, and have resolved the issue.

## Investigation
1. I was setting the $env:Path in my startup profile file 'Microsoft.PowerShell_profile.ps1', but using a **script module** to do set the search path other shell configurations.

2. Setting the $env:Path directly in my 'Microsoft.PowerShell_profile.ps1' file directly did work as expected.

## Conclusion

PowerShell **script modules** will set security information on the PATH environment variable to prevent any '.' paths from the search. This security check must have been added in the v7.1.0 release. 

To fix this, I will do the PATH setup operations directly in 'Microsoft.PowerShell_profile.ps1' .

I will consider this issue resolved/closed.

Thanks all.

**Comment by szalapski** [comment]
So therefore the workaround to always allow this is to add `$env:Path = $env:Path + ';.'` to the end of my powershell $profile, right?

**Comment by vexx32** [comment]
Looks like you're running into https://github.com/PowerShell/PowerShell/issues/12662

In general, relative paths are not well-supported in $env:PATH from what I can see. https://github.com/PowerShell/PowerShell/issues/12662#issuecomment-1145903240 has one suggestion that seems to be able to workaround your issue, though.

**Comment by Anthony-Breneliere** [comment]
"Resolution by design" for this issue means Powershell is designed for system administrators uncompromising on security, but developers that use Visual Studio Code, that need to run  project relative commands, are stuck with Powershell 7.0.

**Comment by Anthony-Breneliere** [comment]
It does not concerns the '.' path but all paths relatives to the current directory: './**'

**Comment by mklement0** [comment]
@Anthony-Breneliere, I'd say it is a bug; see

* #15795

In short: it seems that the relative path is unexpectedly resolved to a full one, on assignment.

**Comment by rsoyxihnark** [comment]
is it possible to disable this so important "Security" feature? in 99.99999999999% cases it only prevents developers to work/slows them down.

![Image](https://github.com/user-attachments/assets/be2445b9-9d26-4a34-ad6a-3dbd81d7d35e)
