### ISSUE TITLE
Export-CSV UTF8 Encoding doesn't work properly.

### ISSUE THREAD

**Issue by gingeryet1** [PowerShell/PowerShell#14108]
## Steps to reproduce

```powershell 7.1.0

$StringToExport = " పిల్లలికి కథలంటే मुक्त ज्ञानकोश 文字材料"
$myObject = [pscustomobject]@{ StringToTest = $StringToExport }
$myObject | Export-Csv -Path "test.csv" -Encoding utf8 

```

## Expected behavior

```
The string should be exported with the correct encoding and display correctly in the CSV.

పిల్లలికి కథలంటే मुक्त ज्ञानकोश 文字材料

```

## Actual behavior

```
The string appears in the CSV (Viewed in MS Excel) as: 
à°ªà°¿à°²à±à°²à°²à°¿à°•à°¿ à°•à°¥à°²à°‚à°Ÿà±‡ à¤®à¥à¤•à¥à¤¤ à¤œà¥à¤žà¤¾à¤¨à¤•à¥‹à¤¶ æ–‡å­—ææ–™

Now if I use utf-8 instead of utf8 the string is exported correctly. This unfortunately does not match documentation and will cause the script to break if run on Windows Powershell 5.1

```

## Environment data

```
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can not reproduce. Could you please share more clear repro steps?

**Comment by jborean93** [comment]
Also try using `Format-Hex -Path test.csv` to read the raw bytes of the file directly instead of trying to read the file in a text editor that might mangle the text if it's trying to read it in a different encoding.

**Comment by gingeryet1** [comment]
@iSazonov Apologies I had made an assumption, a terrible no good assumption. I've updated the ticket with the additional steps.

**Comment by gingeryet1** [comment]
@jborean93 Thanks for the tip.

Here's the outputs:
Powershell 7.1 utf8
          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 22 53 74 72 69 6E 67 54 6F 54 65 73 74 22 0D 0A "StringToTest"��
0000000000000010 22 E0 B0 AA E0 B0 BF E0 B0 B2 E0 B1 8D E0 B0 B2 "à°ªà°¿à°²à±�à°²
0000000000000020 E0 B0 B2 E0 B0 BF E0 B0 95 E0 B0 BF 20 E0 B0 95 à°²à°¿à°�à°¿ à°�
0000000000000030 E0 B0 A5 E0 B0 B2 E0 B0 82 E0 B0 9F E0 B1 87 20 à°¥à°²à°�à°�à±�
0000000000000040 E0 A4 AE E0 A5 81 E0 A4 95 E0 A5 8D E0 A4 A4 20 à¤®à¥�à¤�à¥�à¤¤
0000000000000050 E0 A4 9C E0 A5 8D E0 A4 9E E0 A4 BE E0 A4 A8 E0 à¤�à¥�à¤�à¤¾à¤¨à
0000000000000060 A4 95 E0 A5 8B E0 A4 B6 20 E6 96 87 E5 AD 97 E6 ¤�à¥�à¤¶ æ��å­�æ
0000000000000070 9D 90 E6 96 99 22 0D 0A                         ��æ��"��

Powershell 7.1 utf-8
          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 EF BB BF 22 53 74 72 69 6E 67 54 6F 54 65 73 74 ï»¿"StringToTest
0000000000000010 22 0D 0A 22 E0 B0 AA E0 B0 BF E0 B0 B2 E0 B1 8D "��"à°ªà°¿à°²à±�
0000000000000020 E0 B0 B2 E0 B0 B2 E0 B0 BF E0 B0 95 E0 B0 BF 20 à°²à°²à°¿à°�à°¿
0000000000000030 E0 B0 95 E0 B0 A5 E0 B0 B2 E0 B0 82 E0 B0 9F E0 à°�à°¥à°²à°�à°�à
0000000000000040 B1 87 20 E0 A4 AE E0 A5 81 E0 A4 95 E0 A5 8D E0 ±� à¤®à¥�à¤�à¥�à
0000000000000050 A4 A4 20 E0 A4 9C E0 A5 8D E0 A4 9E E0 A4 BE E0 ¤¤ à¤�à¥�à¤�à¤¾à
0000000000000060 A4 A8 E0 A4 95 E0 A5 8B E0 A4 B6 20 E6 96 87 E5 ¤¨à¤�à¥�à¤¶ æ��å
0000000000000070 AD 97 E6 9D 90 E6 96 99 22 0D 0A                ­�æ��æ��"��

Windows Powershell 5.1 utf8
           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   EF BB BF 23 54 59 50 45 20 53 79 73 74 65 6D 2E  ï»¿#TYPE System.
00000010   4D 61 6E 61 67 65 6D 65 6E 74 2E 41 75 74 6F 6D  Management.Autom
00000020   61 74 69 6F 6E 2E 50 53 43 75 73 74 6F 6D 4F 62  ation.PSCustomOb
00000030   6A 65 63 74 0D 0A 22 53 74 72 69 6E 67 54 6F 54  ject.."StringToT
00000040   65 73 74 22 0D 0A 22 E0 B0 AA E0 B0 BF E0 B0 B2  esà°²à°²à°¿à°à°²
00000060   B0 BF 20 E0 B0 95 E0 B0 A5 E0 B0 B2 E0 B0 82 E0  °¿ à°à°¥àà¤à¥à¤¶ æ
000000A0   96 87 E5 AD 97 E6 9D 90 E6 96 99 22 0D 0A        å­æ"..  ¥à
00000080   A5 8D E0 A4 A4 20 E0 A4 9C E0 A5 8D E0 A4 9E E0  ¥

**Comment by iSazonov** [comment]
@gingeryet1 Thanks for sharing more info.

Windows PowerShell always uses encodings with BOM everywhere. In PowerShell 7 we was moved the default to NoBOM and in your test you get a file in Uft8 NoBOM encoding.
