### ISSUE TITLE
[PowerShell 7.1.0] regression in using module statement with relative paths

### ISSUE THREAD

**Issue by al-cheb** [PowerShell/PowerShell#14109]
## Steps to reproduce

```powershell
md builders
"using module ./builders/foo.psm1`nfoo" > ./builders/foo.ps1
'function foo {"Hello"}' > ./builders/foo.psm1
./builders/foo.ps1
```

## Expected behavior
![image](https://user-images.githubusercontent.com/47745270/99388498-be95a780-28e6-11eb-9d6e-35c6eb42fb7f.png)

```none
PS /home/alex> ./builders/foo.ps1
Hello
```

## Actual behavior
![image](https://user-images.githubusercontent.com/47745270/99388670-ff8dbc00-28e6-11eb-9920-ba81fe531fd6.png)

The module path '/home/alex/builders/builders/foo.psm1' contains duplicate `builders` entry.
```none
PS /home/alex> ./builders/foo.ps1
./builders/foo.ps1: The specified module '/home/alex/builders/builders/foo.psm1' was not loaded because no valid module file was found in any module directory.
```

## Environment data

```none
PS /home/alex> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

PS /home/alex> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Linux 4.4.0-17763-Microsoft #1432-Microsoft Mon Aug 18 18:18:00 PST 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

PS. https://github.com/PowerShell/PowerShell/issues/7424

**Comment by iSazonov** [comment]
@al-cheb Thanks for reporting the regression! Want to pull a fix?

**Comment by al-cheb** [comment]
@iSazonov, Looks like it's a breaking change and not the bug - [#7424](https://github.com/PowerShell/PowerShell/issues/7424)
Before PowerShell Core 7.1,  the path is resolved relative to the current shell location. Now, the path resolves  relative to the current script. 

I think  the documentation should be update to describe new behavior.

**Comment by iSazonov** [comment]
Ah, I see you run a root folder.

@al-cheb Please open new issue in https://github.com/MicrosoftDocs/PowerShell-Docs
