### ISSUE TITLE
Update tags on master repository

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#14116]
Last tag on *master* is set to `v7.1.0-preview.7` that causes the local builds of up-to-date PowerShell repository to show wrong build number:

![image](https://user-images.githubusercontent.com/16168755/99502197-06670e00-297d-11eb-8cd3-ae2c03e45188.png)

![image](https://user-images.githubusercontent.com/16168755/99502079-e2a3c800-297c-11eb-8941-6861ab3ce32a.png)

## Steps to reproduce

```git
git fetch --all --tags
git describe
```

## Expected behavior

```none
v7.2.0-preview.1
```

## Actual behavior

```none
v7.1.0-preview.7-141-g9ca6be1d6
```

**Comment by daxian-dbw** [comment]
This is fixed by #14138. After sync your local master branch, you will get
```
PS:112> git describe
v7.2.0-preview.1-19-g6dcc50701
```
