### ISSUE TITLE
Export-CSV with Encoding utf8 not working for Chinese 

### ISSUE THREAD

**Issue by cssjun** [PowerShell/PowerShell#14115]
Code:
Export-Csv -Path $outPut -NoTypeInformation -Encoding utf8

The code is working with PowerShell 5.1.14393.3866 but not working with PowerShell 7.1.0, which can't out Chinese character correctly

**Comment by mklement0** [comment]
Note that `-Encoding utf8` in PowerShell Core now means _BOM-less_ UTF-8, whereas in Windows PowerShell it means _with_ BOM.

For instance, using `Get-Content` in _Windows PowerShell_ will misinterpret the resulting file (you'd have to use `-Encoding utf8`).

Use `-Encoding utf8BOM` to create a UTF-8 file _with BOM_ in PowerShell Core.

If that doesn't solve your problem, please provide more details about what doesn't work as expected.

**Comment by cssjun** [comment]
Thank you so much for your support. I didn't aware of the change. With
utf8BOM, my code is working in Powershell Core now. Thanks again!!!
