### ISSUE TITLE
Secrets Management should work with the local keychain in macOS

### ISSUE THREAD

**Issue by johncwelch** [PowerShell/PowerShell#14114]
So looking at the secrets management features, it looks nice, but on macOS, it's a bit...not there. (I know it is very early, and if this is on the list, apologies)

There's no option for Add-Secret
Get-SecretVault doesn't seem to know anything about the keychain. This needs to be a default on macOS. Keep in mind, the keychain APIs allow for an arbitrary number of keychains, so if say, one wanted to create just a powershell keychain, that's absolutely possible (along with many other keychain functions): https://developer.apple.com/documentation/security/keychain_services/keychains

this keeps the powershell team from having to write code for their own vaults, and if the user's main keychain is used, then the iCloud sync works as well. This would be a boon to a wide range of powershell users, especially sysadmins.

Enabling the full range of commands for this on macOS is absolutely possible, and is something I've been looking forward to for quite a while (Since talking to Joey Aiello about it at ignite 2019 to be precise.)

**Comment by rkeithhill** [comment]
Have a look at https://www.powershellgallery.com/packages/SecretManagement.KeyChain/0.1.1

**Comment by johncwelch** [comment]
That's a great addon, but, it's still an addon for a feature that exists in every copy of the macOS. I think it's awesome that Steve did that work, but the OS-provided credentials storage shouldn't require an extension here.
