### ISSUE TITLE
System.MethodAccessException and TypeLoadException in Remoting/Infrastructure and Scripting/Debugging tests

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#1411]
## Steps to reproduce

Run BVT/DRT Remoting/Infrastructure and Scripting/Debugging tests. WSManPluginShellSessionUnitTests fail with MethodAccessException and TypeLoadException.
## Expected behavior

Tests pass.
## Actual behavior

**System.TypeLoadException**: Method 'WSManPluginRegisterShutdownCallback' in type 'System.Management.Automation.Remoting.UnitTests.SavesErrorCodeWSManPluginFacade' from assembly 'TAEF.WSManPlugin.UnitTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.Management.Automation.Remoting.UnitTests.WSManPluginEntryDelegatesUnitTests.NullInputIsNoOp()
[HRESULT: 0x80131604]. Test operation failed: 'NullInputIsNoOp'.

**System.MethodAccessException**: Attempt by method 'System.Management.Automation.Remoting.UnitTests.WSManPluginEntryDelegatesUnitTests.InitPluginAssignsWorkerPtrs()' to access method 'System.Management.Automation.Remoting.WSManPluginEntryDelegates+WSManPluginEntryDelegatesInternal..ctor()' failed.
   at System.Management.Automation.Remoting.UnitTests.WSManPluginEntryDelegatesUnitTests.InitPluginAssignsWorkerPtrs()
[HRESULT: 0x80131604]. Test operation failed: 'InitPluginAssignsWorkerPtrs'.
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-112-g3276846c401e0c2132cc260f89752b121c81abde
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment]
@adityapatwardhan same ping.

**Comment by adityapatwardhan** [comment]
@joeyaiello This can be closed.
