### ISSUE TITLE
-split With \G Stops After First Split

### ISSUE THREAD

**Issue by sharpjs** [PowerShell/PowerShell#14112]
## Steps to reproduce

```powershell
"ABCDEFGH" -split '(?<=\G..)(?=..)'
```

## Expected behavior

In PS 7.0.3 and earlier, this is the output:
```none
AB
CD
EF
GH
```

## Actual behavior

In PS 7.1.0, this is the output:
```none
AB
CDEFGH
```

## Workaround

This works in PS 7.1.0:
```powershell
[regex]::Matches("ABCDEFGH", "..") | % Value
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sharpjs** [comment]
Removing `\G` from the pattern restores multiple splits, which suggests that the `\G` anchor indeed is the source of the unexpected behaviour.

```powershell
"ABCDEFGH" -split '(?<=..)(?=..)'
#                      ^
#                    No \G
```

NOTE: Below is not the desired output; it is shown here only to illustrate the behaviour without `\G`.

```none
AB
C
D
E
F
GH
```

**Comment by iSazonov** [comment]
@sharpjs Thanks for your report!

This broke in PowerShell 7.1 Preview1 after we moved to .Net 5.0. PowerShell uses .Net Regex so it is .Net issue.

I see you have an experience in .Net - please create a simple C# demo, open new issue in .Net Runtime repository and reference the issue for tracking.

**Comment by mklement0** [comment]
Just to offer a pragmatic workaround in the meantime: `"ABCDEFGH" -split '(..)' -ne ''`

**Comment by sharpjs** [comment]
Fixes in .NET runtime repo:
`6.0.0`: https://github.com/dotnet/runtime/pull/44975 (merged)
`5.0.x`: https://github.com/dotnet/runtime/pull/44985 (WIP as of this writing)

**Comment by iSazonov** [comment]
@sharpjs Thanks!

**Comment by sharpjs** [comment]
The fix is [not documented to be in .NET 5.0.1](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aclosed+milestone%3A5.0.1+is%3Aclosed+) as of this writing, but my [repro test](https://github.com/sharpjs/Net50RegexSplitBug) went from red to green with the installation of .NET 5.0.1.  So, looks like upstream is fixed.

![image](https://user-images.githubusercontent.com/708461/101538467-ff1a9b00-3951-11eb-9479-0fd018575e0c.png)
