### ISSUE TITLE
Zombie/orphan processes with piped shim executables from pip entry points, when using editable flag under PowerShell Core

### ISSUE THREAD

**Issue by int3l** [PowerShell/PowerShell#14126]
Additional details here: pypa/setuptools/issues/2453

PSVersionTable:
```console
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Can you please confirm that this is or is not related to PowerShell Core itself?
My main concern is that this behavior is not present under CMD, only under the default Windows PowerShell and PowerShell Core.

**Comment by iSazonov** [comment]
If it works in cmd.exe this can be PowerShell issue.
 How does `--editable` work? Redirect IO? Wait input?
You could look in Process Explorer where threads sleep on (see Threads tab).

**Comment by int3l** [comment]
@iSazonov thank you for replying. The strange thing is that I can reproduce this behavior, when I use `Ctrl-C` under PowerShell, but If I use `Ctrl-Break` - it properly propagates the signal to both processes. So I guess that this is some kind of brutal "workaround".

Here is the additional information that I managed to gather:
![Untitled](https://user-images.githubusercontent.com/1278836/99656007-0e01e200-2a65-11eb-8186-74774b892b09.png)
![Untitled2](https://user-images.githubusercontent.com/1278836/99656009-0f330f00-2a65-11eb-922c-ecc792c89914.png)

About the question how editable work - I am not exactly sure, I think that the python entry point scripts are generated somewhere in this codebase: [easy_install](https://github.com/pypa/setuptools/blob/f991fbb3c9d0e10a0a78ae2b508b3fd99f9cdef2/setuptools/command/easy_install.py) with additional tests here: [test_windows_wrappers](https://github.com/pypa/setuptools/blob/f991fbb3c9d0e10a0a78ae2b508b3fd99f9cdef2/setuptools/tests/test_windows_wrappers.py)

**Comment by iSazonov** [comment]
Why are you forced to press Ctrl-C or Ctrl-Break?

**Comment by int3l** [comment]
In order to interrupt/stop the command. I posted examples in the other GitHub issue linked here.

**Comment by iSazonov** [comment]
PowerShell processes Ctrl-C to stop current pipeline and if it can not kill these py processes it is a bug.

**Comment by int3l** [comment]
This bug must be related to some special case while using pipes, because individual processes seems to be interrupted properly.
