### ISSUE TITLE
Empty string is equal to non-empty string

### ISSUE THREAD

**Issue by gurutech-thomasr** [PowerShell/PowerShell#14127]
I am encountering unexpected behavior either in the latest release of powershell or .net; I'm not sure which. 

Demonstration of unexpected behavior:

    PS > "`u{00001A}" -eq ""
    True

I rely on user entering EOF to terminate between batches of input in a script.

I tried reproducing the problem under different versions of .NET and powershell, shown below.  The best I can tell according to [System.Globalization.CompareOptions](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.compareoptions?view=net-5.0), is that "the default option settings for string comparisons [when CompareOptions.None is used]" changed. However, I can't find any documentation on what "the default option settings" are.

## Steps to reproduce

- Open `pwsh.exe` and `powershell.exe`
- Evaluate the expression ``"`u{00001A}" -eq "";`` in each
- Note `pwsh` result of `True` and `powershell` result of `False`

## Expected behavior

```powershell
# the following expressions all evaluate to false
"`u{00001A}" -eq "";
-not [String]::Compare("", "`u{00001A}");
-not [String]::Compare("", "`u{00001A}", [CultureInfo]::CurrentCulture, "None");
```
Aforementioned expressions should evaluate to false.

## Actual behavior

.NET:

    using System;
    using System.Globalization;

    public class Test {
    public static void Main() {
        Console.WriteLine("" == "\x1A");
        Console.WriteLine(String.Compare("", "\x1A"));
        Console.WriteLine(String.Compare("", "\x1A", CultureInfo.CurrentCulture, CompareOptions.None));
        Console.WriteLine(String.Compare("", "\x1A", CultureInfo.CurrentCulture, CompareOptions.Ordinal));
    }
    }

    /* output:
    False
    -1
    -1
    -1
    */

`pwsh.exe -NoProfile`:

    PS ~> "$($PSVersionTable['PSVersion'])"; `
    $windows_eof = "`u{00001A}"; `
    "" -eq $windows_eof; `
    [String]::Compare("", $windows_eof); `
    [String]::Compare("", $windows_eof, [CultureInfo]::CurrentCulture, "None"); `
    [String]::Compare("", $windows_eof, [CultureInfo]::CurrentCulture, "Ordinal");

    <# output:
    7.1.0
    True
    0
    0
    -1
    #>

`powershell.exe -NoProfile` output:

    5.1.18362.1171
    False
    -1
    -1
    -9

.NET Core under `pwsh.exe -NoProfile`:

    Add-Type -TypeDefinition @"
    using System.Globalization;

    public class Test {
    public static System.String Main() {

    System.String result = "";
    result += "" == "\x1A";
    result += "\n";
    result += System.String.Compare("", "\x1A");
    result += "\n";
    result += System.String.Compare("", "\x1A", CultureInfo.CurrentCulture, CompareOptions.None);
    result += "\n";
    result += System.String.Compare("", "\x1A", CultureInfo.CurrentCulture, CompareOptions.Ordinal);
    result += "\n";

    return result;

    }
    }
    "@ `
    -ReferencedAssemblies System.Globalization `
    -Language CSharp; `
    [Test]::Main()

    <# output:
    False
    0
    0
    -1
    #>

## Environment data

    Name                           Value
    ----                           -----
    PSVersion                      7.1.0
    PSEdition                      Core
    GitCommitId                    7.1.0
    OS                             Microsoft Windows 10.0.18363
    Platform                       Win32NT
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0

**Comment by vexx32** [comment]
Looking at the symptoms you're seeing, it sounds like this issue should be filed on the [dotnet/runtime](/dotnet/runtime) repository instead?

**Comment by iSazonov** [comment]
I see this in PowerShell 7.1 Preview3 - it is .Net 5.0 Preview.4.

Please open new issue in .Net Runtime repo and reference the issue for tracking.

**Comment by gurutech-thomasr** [comment]
Following up.  This is an intended breaking change in .NET 5.0, according to:

[Behavior changes when comparing strings on .NET 5+](https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus)
[.NET globalization and ICU](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu)
