### ISSUE TITLE
Discuss about building framework dependent releases with PublishReadyToRun enabled

### ISSUE THREAD

**Issue by imba-tjd** [PowerShell/PowerShell#14121]
## Summary of the new feature/enhancement

Framework Dependent builds support ReadyToRun. Just specify both rid and `--self-contained=false`.

Personally I always have the latest .net SDK installed, so I don't want to use the self contained release. It would be better in my case to use a `win-x64-fxdependent` with ReadyToRun enabled comparing to `win-fxdependent`.

Don't know `win-fxdependentWinDesktop`.

See also https://github.com/PowerShell/PowerShell/pull/12450

**Comment by adityapatwardhan** [comment]
This is something we can definitely look at. thanks for the suggestion.

**Comment by hoodedfoxtailz** [comment]
Terminal
Shelll
Rom
To
Terminal run program
As frame
To a terminal computer fame
