### ISSUE TITLE
Problem with Powershell and https proxy under Linux

### ISSUE THREAD

**Issue by frankpau** [PowerShell/PowerShell#14120]
Hi,

i'm using powershell (7.1.0) under Centos 7.
I'm having a problem getting the for my company required https proxy to work with powershell.
i have set the proxy in the Environment using
export http_proxy=http://<proxyname>:<proxyport> and
export https_proxy=https://<proxyname>:<proxyport>

if i then start pwsh and execute 
Invoke-WebRequest http://woshub.com -Verbose -Debug
i get a StatusCode 200 back and the connect seems fine.

if i try this with https://woshub.com i can't get a working connection.

PS /root> Invoke-WebRequest https://woshub.com -Verbose -Debug           
VERBOSE: GET https://woshub.com/ with 0-byte payload
Invoke-WebRequest: Connection timed out

i also tried setting the proxy inside powershell using:

[system.net.webrequest]::defaultwebproxy = new-object system.net.webproxy('https://<proxyname>:<proxyport>')
which resulted in the same behaviour

## Steps to reproduce

install powershell on linux system behind https proxy, set the proxy in enviroment and try to open a https connection

## Expected behavior

use the configured https proxy

## Actual behavior

Connection timed out

## Environment data

PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Linux 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by frankpau** [comment]
hi,

looks like all my text before $PSVersionTable got lost.

I'm having a problem getting a https connection working inside using our proxy.
after setting the proxy in os:

export http_proxy=http://<proxyname>:<proxyport>
export https_proxy=https://<proxyname>:<proxyport>

i get a working connection using http:
PS /root> Invoke-WebRequest http://woshub.com -Verbose -Debug
VERBOSE: GET http://woshub.com/ with 0-byte payload
VERBOSE: received -byte response of content type text/html
                                                                                                                                                                           StatusCode        : 200                                                                                                                                                    StatusDescription : OK                                                                                                                                                     Content           : <!DOCTYPE html>                                                                                                                                    

but not using https:

PS /root> Invoke-WebRequest https://woshub.com -Verbose -Debug           
VERBOSE: GET https://woshub.com/ with 0-byte payload
Invoke-WebRequest: Connection timed out

**Comment by iSazonov** [comment]
If http request works over proxy then https works too (you could look the proxy logs) but I guess the issue with https itself - see https://www.ssllabs.com/ssltest/analyze.html?d=woshub.com - "Certificate name mismatch".

**Comment by frankpau** [comment]
No matter which https URL is use i get the same output.
i also have problems adding powershellgallery as a repository, since the url is HTTPS

**Comment by iSazonov** [comment]
@faheel Can you investigate in depth on your side? Is your proxy anonymous? Can you look the proxy log? Can you open the url from other applications? Can you check the scenario with different proxy?

**Comment by frankpau** [comment]
I'm currently trying to verify, which setting could be working, but i'm getting strange results.
Which is the best way for Powershell under linux to get it to use a https proxy ?
- export HTTPS_PROXY on OS Level
- export https_proxy on OS Level
- set [system.net.webrequest]::defaultwebproxy inside pwsh 
- something else 
?

**Comment by iSazonov** [comment]
@frankpau PowerShell does not implement this - it uses that .Net implements. So all these options should work. 
I can only guess you have an issue in your configuration. "Connection timed out" usually says about an issue with firewall.
