### ISSUE TITLE
Test-ComputerSecureChannel not working in 7.1.0

### ISSUE THREAD

**Issue by NinjaRMMTheming** [PowerShell/PowerShell#14123]
## Steps to reproduce

```
PWSH 7.1.0  ---  PS C:\Program Files\PowerShell\7> Test-ComputerSecureChannel

Testing in 5.1 comes back True
```

## Expected behavior

```
Result: True or False
```

## Actual behavior

```
Test-ComputerSecureChannel: The term 'Test-ComputerSecureChannel' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment]
This command is loaded here just fine in 7.1. 

This command is in the Microsoft.PowerShell.Management module, V1, and is NOT in the V 7.0.0.0 version (the version shipped with PowerShell 7. So by default you won't see the cmdlet or get tab completion. However, if you spell it out fully, PowerShell loads the V1.0 module (via compatibility), so you get a proxy function of that same name. 

Here is what I see (in 7.1):

```powershell
PS C:\Foo> gmo

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…

PS C:\Foo> gcm -mod Microsoft.PowerShell.Management | where name -match secure
PS C:\Foo> test-computersecurechannel
True
PS C:\Foo> gmo

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Script     1.0                   Microsoft.PowerShell.Management     {Add-Computer, Checkpoint-Computer, Clear-EventLo…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…

PS C:\Foo> gcm -mod Microsoft.PowerShell.Management | where name -match secure

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Test-ComputerSecureChannel                         1.0        Microsoft.PowerShell.Management

```

**Comment by NinjaRMMTheming** [comment]
so in order to use it, we have to use:


import-module Microsoft.PowerShell.Management -UseWindowsPowerShell

?







Thanks,

Dennis Fair  |  I.T Systems Admin
Four Peaks Landscape Management
p: 480-967-0376<tel:480-967-0376>  |  f: 480-967-0406
m: 480-319-5345<tel:480-319-5345>
e: it@fourpeakslandscape.com<mailto:it@fourpeakslandscape.com>
[http://fourpeakslandscape.com/images/four-peaks-landscape-management.png]


________________________________

**Comment by anmenaga** [comment]
> import-module Microsoft.PowerShell.Management -UseWindowsPowerShell

Yes, That is the recommended way for built-in modules that exist in both: WinPS and PS Core.

Error in repro steps comes from CommandDiscovery/ModuleAutoload that rely on module manifest (`C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1`), that is known to have a bug in it on some Windows systems - it mistakenly declares compatibility with PS Core (`CompatiblePSEditions = @('Desktop','Core')`) so it does Not go through WinCompat code.
