### ISSUE TITLE
Add test for verifying the default language mode

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#1413]
## Steps to reproduce

Potentially a test issue. 
.\runlite -suite Scripting.CoreLanguage.CoreLanguageTest -pri  -test DefaultExecutionContextSessionStateLanguageModeInRemoteSession
## Expected behavior

The language mode is FullLanguage.
## Actual behavior

LanguageMode is 3. 

Exception calling "Invoke" with "0" argument(s): "Default $host.Runspace.InitialSessionState.LanguageMode should be FullLanguage when UMCI is not enabled.: '3' does not equal 'FullLanguage'
CallStack: Asserts.ps1: line 87 <- Asserts.ps1: line 219 <- Lite.Scripting.CoreLanguage.CoreLanguageTest.ps1: line 842"
System.Management.Automation.MethodInvocationException: Exception calling "Invoke" with "0" argument(s): "Default $host.Runspace.InitialSessionState.LanguageMode should be FullLanguage when UMCI is not enabled.: '3' does not equal 'FullLanguage'
CallStack: Asserts.ps1: line 87 <- Asserts.ps1: line 219 <- Lite.Scripting.CoreLanguage.CoreLanguageTest.ps1: line 842" ---> System.Management.Automation.RuntimeException: Default $host.Runspace.InitialSessionState.LanguageMode should be FullLanguage when UMCI is not enabled.: '3' does not equal 'FullLanguage'
CallStack: Asserts.ps1: line 87 <- Asserts.ps1: line 219 <- Lite.Scripting.CoreLanguage.CoreLanguageTest.ps1: line 842
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at ExecuteInRunspace(Closure , FunctionContext )
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-112-g3276846c401e0c2132cc260f89752b121c81abde
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment]
@adityapatwardhan same ping

**Comment by adityapatwardhan** [comment]
@joeyaiello  This test verifies the default language mode. This test is missing from GitHub repo. This should be added. The test code is like: 

(Invoke-Command -ComputerName . {$ExecutionContext.SessionState.LanguageMode}) | Should Be ([Management.Automation.PSLanguageMode]::FullLanguage)
