### ISSUE TITLE
PowerShell 7.1.0 'Open Here' context menu miss (x86) next to "Run with PowerShell 7" for PowerShell x86

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#14144]
Steps to reproduce :
1- Install or update to last version both PowerShell 7 x64 and x86 on any supported version of Windows.
2- Right click on **any folder** and see **there's** (x86) written next to "PowerShell 7" for PowerShell x86.
3- Right click on **any ps1** file and see **there's no** (x86) written next to "Run with PowerShell 7" for PowerShell x86. There would normally be (x86) like in the step 2 (those two steps aren't related, those are just teo different ways to open powershell).

**Comment by iSazonov** [comment]
@heaths Could you please look the issue?

**Comment by FellFromTheSky** [comment]
Do you need a screenshot?
It's pretty hard to take a screenshot of Windows context menus. Just ask and I'll do my best.

**Comment by heaths** [comment]
I've not had time to look at this, but these are different registry keys. For folders, it's easy enough to put whatever value you want in the registry key for Directory types. But for files, PowerShell is using resource strings and MUI to extract them, so the executable resources have to be changed and differ between x86 and x64: https://github.com/PowerShell/PowerShell/blob/master/assets/Product.wxs#L259

**Comment by FellFromTheSky** [comment]
> and differ between x86 and x64
what does it means?

Just freshly installed PowerShell 7.1.0 on Windows. 
I know it's Windows 7x64 but there's the same exact result on Windows 10 :

https://user-images.githubusercontent.com/66923825/103711793-321e7180-4f86-11eb-856e-c77c379b6f91.mp4

(Sorry for the bad video quality, I wanted to make it lightwieght.)

**Comment by FellFromTheSky** [comment]
See the video for an example :

https://user-images.githubusercontent.com/66923825/103712122-fa63f980-4f86-11eb-9e71-b96c32e21c38.mp4

It's on Windows 7 but there's the same result on Windows 8 or Windows 10.
