### ISSUE TITLE
Tab completion: do not tab-complete filenames when binding to non-string parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14147]
The default tab-completion (command-completion) behavior for command arguments is to complete based on the names of _items_ in the current location (typically, _files and directories_ present in the current file-system directory).

However, this completion is currently also performed for arguments that will bind to parameters _other_ than _untyped_ or `[string]`-typed  (or perhaps also `System.IO.FileInfo` / `System.IO.DirectoryInfo`) parameters, e.g. `[int]`, in which case such completions make no sense.

(By contrast, custom completions, validation attributes, and `enum`-derived types are handled correctly.)

## Steps to reproduce

```powershell
$line = 'function foo { param([int] $bar) $bar }; foo '

(TabExpansion2 $line $line.Length).CompletionMatches.Count | Should -Be 0
```

## Expected behavior

The test should succeed.
That is, no completion should occur, because tab-completing an `[int]` value (without validation attributes / custom completions) makes no sense.

## Actual behavior

The test fails, because completion based on the item names (files and directories) in the current directory was performed:

```none
Expected 0, but got 526.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.1
```

**Comment by iSazonov** [comment]
The last resort was always in PowerShell for non-implemented branches of the IntelliSense. So a request should be specific and positive - "to add support for IntelliSense for ... case". I suspect there are many such cases out there.

**Comment by mklement0** [comment]
@iSazonov: This request is properly framed negatively: it is about _generically excluding_ tab-completion behavior that is self-evidently _never helpful_.

**Comment by iSazonov** [comment]
> This proposal _is_ properly framed negatively:

I believe all current branches in implementation is positive and this is more _positive_ :-) than adding negative conditions.

**Comment by mklement0** [comment]
The proposal is about adding an _exclusion_ (negative) to the _fallback branch_ (positive).
