### ISSUE TITLE
BuildVersion should be removed from $PSVersionTable

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#1415]
## Steps to reproduce

$PSVersionTable. The major version should be 10 on Windows PowerShell build from PowerShell repo.
## Expected behavior

Version is 10?
## Actual behavior

BuildVersion                   3.0.0.0
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.10032.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v0.6.0-112-g3276846c401e0c2132cc260f89752b121c81abde
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by joeyaiello** [comment]
@adityapatwardhan @SteveL-MSFT @HemantMahawar  is this something we need in PSCore for Win10? What is BuildVersion supposed to denote?

**Comment by SteveL-MSFT** [comment]
Looking at the code, it's the fileversion of sma.dll.  I don't think this property is actually useful particularly since we have the GitCommitId now.  Perhaps we should remove it even though it's a breaking change. @joeyaiello

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT I agree, it is better to introduce the breaking change now.

**Comment by ebekker** [comment]
Not sure if this has already been discussed, but should `GitCommitId` actually refer to `Git`?  I know it's a great DVCS and all, but should the Property refer to something more generic?

**Comment by SteveL-MSFT** [comment]
@ebekker good question.  We don't have any reason or plans to move from GitHub and git now that we are Open Source, the GitCommitId literally allows someone to build the same version that was used to report an issue (if needed).  It's really only intended to be useful for developers of PSCore6.  End users should rely on PSVersion.
