### ISSUE TITLE
Throw expressions

### ISSUE THREAD

**Issue by mladedav** [PowerShell/PowerShell#14203]
## Summary of the new feature/enhancement

As a user I want throw expressions so that I can chain them with operators such as && and ||. This enables me to have more concise throw statements when a command fails.

Right now we can do (taken from [Powershell documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipeline_chain_operators?view=powershell-7.1)):
```
$result = Write-Output 'Value' && $(throw 'Bad')
```
I propose only to simplify it to
```
$result = Write-Output 'Value' && throw 'Bad'
```
For reference, right now it throws (different) error stating:
```
throw: The term 'throw' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

My idea is based on what C# has https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/throw-expression.

## Proposed technical implementation details (optional)

I believe just allowing the syntax parser to parse this would make this work as expected as the throw statement would be executed at that point and nothing else would be including any potential usage or assignment of the value that is expected to be returned from the expression.

If this is seriously considered I think it would be best to reach out to a C# team member to ask if there were any issues with this.

**Comment by jhoneill** [comment]
First  `$result = Write-Output 'Value' && $(throw 'Bad')` 
Is a dreadful example for the help.  
1.  Nothing should ever use   `$variable = write-output <<some_constant>>`
2.  `$result = 'Value' && <<anything which doesn't throw>>` puts "value" into $result and the puts a second value in if there is one,   throw leaves$ result empty. 
 

There's a much wider constrain to do with language keywords.  You can't , for example, do 
`foreach ($x in $Y) {$x +1 } | some-command `   

for / foreach / while / if / throw / break / continue  are not pipelines and as the help says  under "Operator syntax and precedence" 
>   Unlike other operators, && and || operate on pipelines, rather than on expressions like + or -and, for example.

`$result =  'Value' && while ($x -lt 3) {$x ++}` won't work either. nor will.
`$result =  'Value' && if ($true) {"boo"}`

**Comment by mklement0** [comment]
@mladedav, I empathize and certainly wish the `$(...)` wasn't needed, but this has been discussed at length in #10967; specifically, @rjmholt explains [here](https://github.com/PowerShell/PowerShell/issues/10967#issuecomment-549167463) and [here](https://github.com/PowerShell/PowerShell/issues/10967#issuecomment-561843650) why the fundamentals of PowerShell's current grammar prevent a solution.

**Comment by mklement0** [comment]
The short of it: `throw` is a _statement_, as are constructs such as `if` and `foreach`, and the only way to nest statements inside a statement is via `$(...)`.

@jhoneill's examples, such as `foreach ($x in $Y) {$x +1 } | some-command`, therefore do not work for the same reason - even though I wish they did (#6817).

**Comment by mklement0** [comment]
As an aside: The curious thing is that statements _are_ allowed without `$(...)` if they are the standalone RHS of an _assignment_; e.g.:

```powershell
$var = foreach ($i in 1..3) { $i }  # $(...) NOT required in this case.
```

**Comment by mklement0** [comment]
P.S.: [Here](https://github.com/PowerShell/PowerShell/issues/10967#issuecomment-569285154) I've made a proposal to modify the grammar _slightly_, in order to at least allow using `exit` , `return`, `throw` as-is in pipeline chains (with `&&` and `||`), but my knowledge isn't deep enough to know whether (a) that is technically feasible and (b) without breaking backward compatibility.
