### ISSUE TITLE
New-SelfSignedCertificate removes zero-length Name Constraints

### ISSUE THREAD

**Issue by 13thirteen** [PowerShell/PowerShell#14206]
I'm trying to create a root CA certificate with a `Name Constraints` extension (`2.5.29.30`) containing zero-length token values. Adding `DirectoryName=`, `Email=` and `URL=` in the `Excluded` subtree ensures that the certificate may not be used to sign certificates for any names of these types (i.e. wildcard blacklisting).

Unfortunately, `New-SelfSignedCertificate` removes these zero-length token values and only keeps tokens with a non-zero-length value. Removal of `DirectoryName=`, `Email=` and `URL=` in the `Excluded` subtree loosens the constraints and allows signing of certificates for arbitrary names of these types.

## Steps to reproduce

```powershell
 $rootCACert = New-SelfSignedCertificate -Subject "My CA" -KeyUsage CertSign, CRLSign -TextExtension @("2.5.29.19={critical}{text}ca=true&pathlength=0", "2.5.29.30={critical}{text}subtree=Include&DNS=example.com&subtree=Exclude&DirectoryName=&Email=&IPAddress=0.0.0.0,0.0.0.0&IPAddress=0:0:0:0:0:0:0:0,0:0:0:0:0:0:0:0&URL=")
 Export-Certificate -Cert $rootCACert -FilePath "ca.crt" -Type CERT
```

## Expected behavior
Creates a certificate with the following `Name Constraints` value:

![image](https://user-images.githubusercontent.com/20041328/99806539-7375d180-2b3e-11eb-8be7-d4bbf1d03609.png)

```none
Permitted
     [1]Subtrees (0..Max):
          DNS Name=example.com
Excluded
     [1]Subtrees (0..Max):
          Directory Address
     [2]Subtrees (0..Max):
          RFC822 Name=
     [3]Subtrees (0..Max):
          IP Address=0.0.0.0
          Mask=0.0.0.0
     [4]Subtrees (0..Max):
          IP Address=0000:0000:0000:0000:0000:0000:0000:0000
          Mask=0000:0000:0000:0000:0000:0000:0000:0000
     [5]Subtrees (0..Max):
          URL=
```

## Actual behavior
Creates a certificate with the following `Name Constraints` value:

![image](https://user-images.githubusercontent.com/20041328/99806591-85f00b00-2b3e-11eb-8950-703b2e1cd6d1.png)

```none
Permitted
     [1]Subtrees (0..Max):
          DNS Name=example.com
Excluded
     [1]Subtrees (0..Max):
          IP Address=0.0.0.0
          Mask=0.0.0.0
     [2]Subtrees (0..Max):
          IP Address=0000:0000:0000:0000:0000:0000:0000:0000
          Mask=0000:0000:0000:0000:0000:0000:0000:0000
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Further Information
* [New-SelfSignedCertificate docs about Name Constraints](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/New-SelfSignedCertificate.md#user-content--textextension)
* [RFC 5280 - Section 4.2.1.10 Name Constraints](https://tools.ietf.org/html/rfc5280#section-4.2.1.10)
* [CA/Browser Forum - Baseline Requirements - Section 7.1.5 Name constraints](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.3.pdf#page=78)

To use `openssl` to produce an equivalent root CA certificate with `Name Constraints` containing zero-length token values (as shown here in Expected behavior):
Create the following openssl config file `ca.cnf`:
```none
[req]
default_bits = 2048
default_md = sha256
prompt = no
distinguished_name = req_distinguished_name
x509_extensions = v3_ca

[req_distinguished_name]
CN = My CA

[v3_ca]
extendedKeyUsage = clientAuth, serverAuth
subjectKeyIdentifier = hash
keyUsage = critical, cRLSign, keyCertSign
basicConstraints = critical, CA:true, pathlen:0
nameConstraints = critical,@name_constraints

[name_constraints]
permitted;DNS.0=example.com
excluded;dirName.0=exclude_dirname
excluded;email.0=
excluded;IP.0=0.0.0.0/0.0.0.0
excluded;IP.1=0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0
excluded;URI.0=

[exclude_dirname]
```
and then run
```none
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -sha256 -days 365 -out ca.crt -config localhost.cnf -extensions v3_ca -subj "/CN=My CA"
```

**Comment by 13thirteen** [comment]
Also created a Windows Server / Powershell / UserVoice bug report:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/42009115-bug-new-selfsignedcertificate-removes-zero-length

**Comment by iSazonov** [comment]
The cmdlet is not in the repo so close.
