### ISSUE TITLE
Feature Request: 'pwshup' cross-platform self-contained installer CLI tool inspired by 'rustup'

### ISSUE THREAD

**Issue by awakecoding** [PowerShell/PowerShell#14217]
## Summary of the new feature request

'pwshup' (pronounced "push-up") is a proposed self-contained CLI tool meant to facilitate installing, updating, and configuring PowerShell on all platforms without relying on the presence of PowerShell. The goal is to provide a self-contained executable that can be dropped in a fresh environment (Windows, macOS, Linux) and use it to bootstrap a usable PowerShell environment.

Once PowerShell is installed, the tool would be called to update PowerShell and ensure proper baseline on all platforms, making it easier to the latest and greatest rather than deal with older versions for too long. Since the tool needs to install and update PowerShell, it cannot itself be written in PowerShell, which is why a "traditional" CLI tool is required.

This idea is a follow-up [to this discussion on twitter](https://twitter.com/awakecoding/status/1330285843114840065).

## Proposed technical implementation details

The 'pwshup' CLI tool would be written in Rust, just like the tool it takes inspiration from, ['rustup'](https://github.com/rust-lang/rustup). Without going into details as to why Rust is a good choice or not, it is a very common choice nowadays for making CLI tools, especially when they need to be fast, secure and cross-platform. Long story short, [rustup is Rust toolchain installer](https://rustup.rs/) that consists of a single executable. All you need is to copy it in the right place and call it to bootstrap the installation of everything needed for Rust development. It creates a local directory structure in the current user directory, and allows you to easily switch between versions of the Rust tooling.

The local user directory approach taken by rustup avoids the problem of elevating privileges, which has its advantages that could be transferred to PowerShell. One can "install" PowerShell relatively easily without admin rights, as it doesn't really need to be installed globally, as long as you can call it. However, I suggest that we support both install options in "Global" and "CurrentUser" scopes, leaving it up to the user to decide what works best depending on the use case.

For the "Global" install option, I suggest that 'pwshup' adds support for downloading platform-specific packages and simplify its installation or update. For instance, it could fetch and install the msi on Windows by default. It could also be made to support the MSIX installation, and the package type could be passed as an option to override the default. On macOS, it could detect the 'brew' command and default to install/update it through homebrew, etc. Alternatively, it could also handle doing a global installation without a platform-specific package, by doing the same type of installation done in a user local directory, but inside a global directory that is not writable with regular permissions.

For updating, 'pwshup' should help with the detection of PowerShell installation(s) and their versions, such that the update could be conditional on not having a recent enough version of PowerShell. For instance, an application could request pwsh 7.0.0, which would be fine if the system already has 7.1.0 installed. Various third-party applications could do version checks to detect if they have a suitable PowerShell environment available. If those applications are not given elevated permissions, they could call pwshup to download and "install" a recent version of PowerShell in a user-writable directory, and work around the problem this way. This may sound a bit extreme, but this alone would make it possible for a lot of third-party applications to add PowerShell 7 as a *hard dependency*, since there would be a reasonable way to always make it work without bundling a full copy of PowerShell.

I suggest we start small and just get the cross-platform "global" install to work, detecting and downloading the latest PowerShell releases directly from github.com/PowerShell/PowerShell GitHub releases. Once we have a usable prototype, it should be easier to look into getting the "CurrentUser" scope installations to work as well, unless someone wants to give it a short right away, probably importing bits and pieces from the original rustup.

For Windows specifically, I hope that a tool like 'pwshup' would really ease the transition away from Windows PowerShell 5.1. Since it comes with Windows and most PowerShell modules are compatible with it, it is hard to require PowerShell 7 as a baseline without running into issues where the system doesn't have it installed. Rather than use chocolatey, winget, or all sorts of different package managers on all platforms, I'd like to simply point to a single "download and run this" tool that can executed manually or automatically in a script.

PowerShell deserves a special treatment in this case, because PowerShell *becomes* the platform for many other tools. What if all you really need is to bootstrap PowerShell, then use purely PowerShell tools afterwards? In many cases, PowerShell is really all you're going to need, you just need PowerShell to get started.

I would like to hear your thoughts and comments on this!

**Comment by SteveL-MSFT** [comment]
`-Scope [CurrentUser|AllUsers]` makes sense (with it defaulting to `CurrentUser` so admin is not needed).

Should probably have `-Channel [LTS|Stable|Preview]` with default to `LTS`.  Do we need a `-Version` type parameter?  I think initially we can skip it as the channels is more important.

Instead of downloading from GitHub, the PowerShell team should publish the latest versions to an Azure blob.  Then we can have a aka.ms link that redirects to the correct address to do a HTTP GET download of the package.  `pwshup` would then perform whatever the local operation is to install it (run the interactive installer or use dpkg on Linux, for example).

I think once we agree on the scope of the tool, user experience, and name, I can create a repo in PowerShell org to host it.

**Comment by awakecoding** [comment]
I wasn't sure if we'd use PowerShell-style command-line parameters over "traditional CLI" formatting (--parameter some-lowercase-value), but why not? It is meant for PowerShell after all, so I suggest we borrow the PowerShell command structure for parameters. The cool thing is that it would be relatively simple to produce a "pwshup.ps1" prototype in PowerShell to use as a reference specification for the final tool in Rust that would not depend on PowerShell.

I suggest we borrow a lot of the parameter names and structure from the ["Install-Module"](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-7.1) command family, starting with -Scope [CurrentUser|AllUsers], and expand from there to add what we need.

-Channel [LTS|Stable|Preview] sounds good to me. I suggest that the default is set to 'Stable', most people probably want to use the latest, but not the preview builds. Choosing the LTS should be something explicit in my mind.

As for -Version, it would be an important one, but we may need multiple version-related parameters. Install-Module has -RequiredVersion, -MinimumVersion and -MaximumVersion, which I think we should borrow as well. This way, you can both specify a very specific version of PowerShell, and you can also give an acceptable version range. Most users won't bother and only install the latest, but this allows very powerful control for compatible versions of PowerShell if you ever encounter issues that demand it.

Aside from parameters, what should the initial command verbs and nouns be? I have made [a very similar tool in PowerShell for Remote Desktop Manager recently called RdmHelper](https://github.com/devolutions/RdmHelper-ps), but I wasn't sure about the noun choice for many of my commands. Nevertheless, this is where I am coming from when thinking about the naming for the commands in 'pwshup'. Here is a list that comes to mind for the obvious ones:

- Install-PowerShell
- Update-PowerShell
- Uninstall-PowerShell

But we also need commands for operations like:
- Detecting the latest upstream version, versus the currently installed version
- Finding and returning CDN package download information (no installation)
- Detecting and returning the list of local PowerShell installations (path, version, etc).
- Detecting the full path to 'pwsh.exe' based on set of parameters when not in the PATH

Most of this can probably be handled with a Get-PowerShell command that returns "PowerShell objects" as a JSON array of objects that can easily be processed with a ConvertFrom-Json command, with a few ways to simplify the output like just returning a single version number as a "naked string", making it easier to process without PowerShell.

Last but not least, @SteveL-MSFT you said that it would be better to upload the releases in Azure blob storage instead of using GitHub releases. Is this something that is done today, or planned for the future? We also use Azure blob storage at Devolutions and it works great, but regardless of how the releases are published, we need a way to detect the following:

- list of package versions by channel and platform
- detect the CDN download URL for each package

I originally thought that using GitHub releases may simplify things, because the assets are well structured, [and one can query the GitHub releases API rather easily](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#releases). Here is the [JSON output for what can be found in the PowerShell releases](https://api.github.com/repos/powershell/powershell/releases).

At Devolutions we have [a custom productinfo.htm page](https://devolutions.net/productinfo.htm) we use to expose such information in our own format. I don't necessarily recommend using it as a reference, but we would need something similar for 'pwshup' to detect the latest version and find the release artifact CDN download URLs. JSON-formatted data should be rather easy to process. Is there something like that already in place other than GitHub releases?

**Comment by awakecoding** [comment]
To expand on the whole "is this a package manager specific to PowerShell" questions from twitter, I suggest adding two parameters to improve control over package type and package manager usage:

-PackageType: [msi|pkg|deb|rpm|zip|tar]
-PackageManager: [chocolatey|winget|homebrew|aptitude|snapcraft]

However, it really dumbs down to two things:
1. Should we simply call an existing package manager or not? For instance, don't download the msi, call chocolatey or winget. On Linux, it uses the distro-provided package manager, but we could also wrap snapcraft, etc.
2. Should we install a package or not? If calling a package manager, we don't. 'AllUsers' would default to a system package. 'CurrentUser' would download the archive and extract it.

In both cases, even if we provide the whole list of options, there really isn't much that you can't detect by default. For instance, if you detect that you already have pwsh installed through aptitude, it just makes sense to update it through an "apt-get command", same thing if you detect that it was installed through snapcraft with a snap command, etc.

When not wrapping an existing package manager, I agree 'pwshup' becomes a package manager just for PowerShell. However, it doesn't need to be more than that. What's the alternative anyway? Go on the website, download the zip, extract it manually, fiddle with PATH, etc? There's definitely no harm in providing a tool like 'pwshup' to do it all without trying to replace any of the existing package managers, especially when no "installable package" is involved.

I could see a tool like pwshup being extremely useful in cases like new platforms that don't yet have packages available, like PowerShell for Windows ARM64. It's possible to extract the zip and do it all yourself, but it is annoying, and having a tool like pwshup would have made it a breeze. I haven't checked the status for macOS on ARM64, but I bet it's going to be the same.

**Comment by SteveL-MSFT** [comment]
I think the CLI syntax can be flexible as it's not a cmdlet.  I would suggest starting with cmdlet syntax consistency (with aliases for `-c` (Channel) and `-s` (Scope) and based on user feedback, we can decide if `--channel` and `--scope` is needed (not hard to add, but want to avoid confusion).

The purpose of having it in Azure blob storage instead of GitHub is that some customers have reported their enterprise doesn't allow access to GitHub, but I assume Azure is ok.  Also, to make it simple for `pwshup`, we can have a simple redirection Azure Function taking the parameters I noted above and redirect to the actual Azure blob download URL (we already have something similar today for getting latest pwsh version).

A way to list available pkgs can also be supported via same or different Azure Functions HTTP endpoint returning the content as a JSON payload.

Yeah, defaulting to `Stable` instead of `LTS` might be better.  Again, I'm open to user feedback on this.  The default should be correct for majority of users and everyone else just needs to be specific.

I don't think we need to support enumerating all the installed local versions of pwsh.  I think that might be better as part of some cmdlets.  I'd like `pwshup` to be simple and specific for initial pwsh install.

I don't think `pwshup` should expose the different pkg types directly.  For `CurrentUser` it'll be a zip or tgz.  But for `AllUsers`, it should be the recommended one for the platform.  The only open question for me is on Linux, should `pwshup` register `packages.microsoft.com` and use literal `apt` or `yum` to install or download the deb/rpm and install it directly.  The benefit of the former is automatic dependency install while the latter requires more complexity in `pwshup`.

**Comment by awakecoding** [comment]
That sounds good to me, I am just concerned about the best way to get it started: it doesn't matter if it's in GitHub releases of the Azure CDN, what matters is that we have an HTTP endpoint to query and find the release packages available today.

Windows and macOS both have relatively stable ABIs, such that it is easy to make a single binary that works well on multiple versions starting from a baseline. Linux is more difficult, but not impossible, the biggest issue is usually dependencies like OpenSSL and the libc version. However, you already have a fairly good system in place for Linux PowerShell builds, I suggest we simply provide prebuilt rustup binaries for the same targets supported by PowerShell. From there, a "curl-able shell script" can definitely do the distro-specific handling.

The other issue with Linux is that while you can download and install the package directly, updates should normally come from the package manager. Installation instructions always begin with "add this new repository, update, then install" and then with a bunch of distro-specific things to modify for each and very edition of Ubuntu or whatever else you are using. This could be automated for known-supported distributions. In the product I am working on, we borrowed a trick from the Google Chrome Linux package that automatically registers the Google Debian repository when installing the package.

I say we can definitely support both and control it with parameters: install the package directly, or register + install through the distro-specific package repository. That alone would take a lot of the "so, you need PowerShell, on Windows, do this, if you use chocolatey or winget, do this, on macOS, install the pkg or use homebrew, on Linux, well if you're on Ubuntu go for this, on RedHat go for that, if you'd rather use snapcraft then do this" pain away.

Pretty much all of the manual installation steps that are documented over multiple pages can be dumbed down to one 'pwshup' command. If we can do that for all officially supported platforms, it'll be a huge win.

Also, one of the reasons why I'd like 'pwshup' is because it makes me scream internally that all I have on a brand new Windows Server 2019 Server Core Azure VM is Windows PowerShell 5.1, with no installable system feature. I usually install chocolatey and then install PowerShell with it, but there really has to be a better way. With pwshup it would be a one-liner everywhere I need the latest and greatest PowerShell 7. And I'm not even talking about the fact that *most* third-party package managers lag behind in terms of package distribution, you never get the very latest as it is released.

**Comment by SteveL-MSFT** [comment]
Agree that `pwshup` should handle updates, but I would suggest it currently only handle updates for installs it itself made (and not for any arbitrary installs the user may have made).

I'll get more details on what we currently publish in Az Blob, but that's an easy problem to solve.

I think registering `packages.microsoft.com` for Linux would be acceptable and keeps things simple particularly if there's prior art like Chrome doing the equivalent and users not bringing out pitch forks.

If the user agent provided by curl/wget is not sufficient to differentiate the Linux distro, I would agree a simple Bash script would be needed to download the right `pwshup` for the specific distro/version.

We can always add additional capability to `pwshup` in the future based on user feedback, but I don't want to turn this into "yet another package manager" and all the complexity, up keep, etc... that would go along with that.

I can prototype the Azure Function endpoints this week to enable some prototyping in a script before converting to Rust.

**Comment by awakecoding** [comment]
Regarding what Google does for [Linux packaging](https://www.google.com/linuxrepositories/):

Google’s Linux packages are signed with GNU Privacy Guard (GPG) keys. **Google’s packages will automatically configure your package manager to verify product updates with the public signing key, but you may also install it separately** if, for instance, you want to verify the integrity of an initial package download. Follow the instructions below to manually configure your package manager to use the keys.

The installer package basically runs a post-install cron job to configure the key trust and add the package repository automatically. There is a way to disable this behaviour that is [described in the chromium FAQ](https://www.chromium.org/developers/linux-technical-faq).

I think we've got enough material to get started at this point, I do suggest you prototype things entirely in PowerShell and leave the Rust code to us (at least initially). What we'd need the most on our side would be to have the structure in place to query package information and CDN download URLs when it becomes ready.

Let's focus on the obvious functionality with the biggest value that won't cause a lot of stir, then expand from there. Thanks a lot for your time!

**Comment by iSazonov** [comment]
Related #13534 #11222 #12701

**Comment by sharpninja** [comment]
This is really exciting!  Has work begun?

Looking for volunteers?

**Comment by awakecoding** [comment]
@sharpninja we haven't begun the work on this, but it could get started without having to wait on the upcoming CDN download URLs just by using the GitHub release API. We expect to get started on this at the end of 2020 / beginning of 2021 at Devolutions, but if you know Rust and would like to contribute, we could get something going quite fast.

**Comment by SteveL-MSFT** [comment]
I expect to have some time later this week or next week to look into this and prototype it in PS Script

**Comment by sharpninja** [comment]
Rust?

**Comment by TylerLeonhardt** [comment]
How would we ship a `pwshup` executable on all platforms? It would need to be available in all the package managers that `pwsh` ships in.

**Comment by awakecoding** [comment]
@TylerLeonhardt it would essentially be package-less, and distributed directly as a self-contained executable which is copied to a local directory from where it will be launched. If you want to get an idea of the intended look and feel, I suggest you try installing the Rust toolchain using [rustup](https://rustup.rs/) even if you don't intend to start doing Rust development. 'pwshup' would borrow most of the principles from rustup but adapt them to PowerShell instead.

**Comment by TylerLeonhardt** [comment]
@awakecoding I've installed rustup before. It curl's to sh. The thing is, we have that for PowerShell already:

https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.sh-README.md#usage

And I'm curious what this pwshup would really give us beyond what this script already does...

And if you say "it also supports updates" I feel like an `Update-PowerShell` cmdlet could do this - something that has been asked for already https://github.com/PowerShell/PowerShell/issues/8663 https://github.com/PowerShell/PowerShell/issues/12678 https://github.com/PowerShell/PowerShell/issues/11222

**Comment by TylerLeonhardt** [comment]
I have concerns with what `pwshup` brings to the table but all that aside, I question whether `pwshup` provides more value right now than say, shipping in Microsoft Update [like our friends did in .NET](https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/).

Linux users are used to installing packages using *insert package manager* but Windows users on the other hand continue to say "we need PowerShell in box or at the very very least in Microsoft Update".

The Windows customers that want to use PowerShell but can't because they don't want to download it via the existing ways themselves will still likely not use a `pwshup` executable so those customers are still not accounted for.

**Comment by awakecoding** [comment]
@TylerLeonhardt regarding Microsoft Update distribution, I think you should definitely do it regardless of what happens with a tool like 'pwshup'. Otherwise this is like saying there is no platform-provided package distribution in place, like a Linux distribution without an official distribution channel for packages. This being said, there will never be a one-size-fits-all solution, only multiple solutions to the same problem, and it will probably always remain so.

To really understand why a tool like 'pwshup' makes sense, consider customers that find such a solution acceptable (obviously) and that want a uniform way to get the latest PowerShell installed and up-to-date on all platforms, insisting on the pain of doing that in a consistent manner on Windows, macOS and Linux. Windows-only customers will probably choose Microsoft Update but many would still just use chocolatey or winget, but I suspect many just download the .msi directly, many macOS users will choose homebrew if they have it, or download and install the macOS package directory, and Linux users will either follow the distro-specific instructions to add the package repository and install the package or use a snap package. Long story short, if you care more about PowerShell 7 than package managers, you realize it does stand in the way in a big way.

It is specifically for those users that 'pwshup' is meant to: you care vastly more about getting the latest and greatest PowerShell 7 installed and updated in a consistent manner across *all platforms*. This pattern works well for Rust because well, I guess Rust developers care a lot more about getting the latest and greatest Rust toolchains than their platform-specific distribution channel. My dream is that regardless of the platform (Windows, macOS, Linux) my very first step is to bootstrap the latest PowerShell and keep it up to date, such that I can use at a hard dependency.

I don't think we need to go very far in what the tool does: there exists a suitable package for all platforms already, all pwshup really needs to do for a basic system installation is automate the downloading of the platform-specific package and install it, just as if you were following the docs on how to install it for your platform. This would probably mean downloading the .msi and installing it automatically on WIndows, downloading and installing the .pkg on macOS, and for Linux, I suppose we could detect the distribution and perform the same operations as in the docs, with an option to possibly add the repository to get the updates through the official package manager afterwards.

In the spirit of full disclosure, the *real* reason why we are looking into getting this tool built, it is because we need it into [Wayk Bastion](https://wayk.devolutions.net/), the commercial product I am working on. We just released [an initial version of Wayk PowerShell Remoting](https://docs.devolutions.net/wayk/client/psremoting.html) that replaces the PowerShell SSH transport with a rendezvous WebSocket transport, and out-of-band authentication. Our Wayk Agent comes with a built-in remote desktop capabilities (not RDP, but our own protocol), and we want to use PowerShell 7 as the ultimate cross-platform unattended management protocol.

We write a lot of Rust code for Wayk, which is why it is a natural fit for us to look into making 'pwshup' in Rust, heavily inspired or even partially based on the original 'rustup'. However, a major issue we face is how to get PowerShell installed and kept up to date on all machines managed by our Wayk Agent. Of course, we could make a custom solution inside our agent, leaving others to implement a similar tool for themselves, but we would rather do it cleanly as 'pwshup' and take feedback from the community, because we think we're definitely not the only ones facing this very problem.

I should also insist on the fact that pwshup should be a fully standalone executable, something which we know can be particularly difficult especially on Linux, but we used to such difficulties because our Wayk Agent needs to be fully self-contained and require pretty much no hard dependencies to operate properly. We do a lot of static linking and lot of custom builds for external dependencies, but hopefully it should be much simpler to get this done for a simpler tool like pwshup.

In the end, what would happen is our Wayk Agent would use the pwshup executable to install and update PowerShell 7 on hundreds if not thousands of machines running Windows, macOS and Linux. These would all be machines for which we cannot rely on external dependencies and tools to be present in the first place, except our Wayk Agent, and no direct connectivity is possible outside of what the Wayk Agent provides.

If we can get there, then it means we can start building on top of PowerShell 7 as a true cross-platform solution, because all of sudden PowerShell 7 *became the platform*. Install-Module + private/enterprise nuget repositories can easily be used to install and deploy anything that is required on top of this stable, uniform PowerShell baseline. Remote installation and updates can then be controlled easily through our Wayk Agent, but for anybody else this is just a tool they can integrate or call directly to achieve exactly the same result.

Sorry for the wall of text, I just wished to bring more background into the reasons why we're doing this :) I hope I made it a bit clearer as to what our goals are: we are going to build such a tool anyway for our needs, but we really feel like there is a need for it in the community. I think the worst that can happen is nobody likes and it dies on its own, but it wouldn't change the fact that we'd be using it ourselves. If this happens, we'd just ship it ourselves, and it wouldn't be official, but Steve appeared to like the original idea and suggested we could make it an official thing.

**Comment by TylerLeonhardt** [comment]
But you still need a separate install script for `pwshup` on Windows vs non-Windows no? This is exactly what we already provide with the [`install-powershell.ps1`](https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1-README.md#install-powershell-core-using-the-msi-installer) vs [`install-powershell.sh`](https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.sh-README.md#usage).

But it just gets you PowerShell instead of something that will get you PowerShell.

To me, `pwshup` just pushes the problem up... and then you also have to figure out how to update `pwshup` itself if it ever needs an update...

**Comment by awakecoding** [comment]
@TylerLeonhardt oh for the "curl-able" install, I get your point, but I consider that gravy on top, separate from 'pwshup'. This technique is probably only really usable on macOS and Linux with the built-in shell to detect the right executable to download, for Windows of course there can be a PowerShell one-liner similar to how chocolatey is installed.

As for updating the updating tool itself, rustup has a way of doing it which you can trigger using "rustup self update", otherwise it does it regularly on its own just by using the tool: https://rust-lang.github.io/rustup/basics.html#keeping-rustup-up-to-date

This part can be a bit tricky to implement (an executable replacing itself) but there are ways to do it, I would look at how rustup does it first and implement the same technique.

By the way, there is no curl-able wrapper shell-script for rustup on Windows, you just download rustup-init.exe and launch it. However, this could definitely be modified to become a chocolatey-style PowerShell one-liner. This is only required for the initial installation, after that rustup can self update either manually or when you call the tool to run updates, it uses it as an opportunity to update itself as well.

I get your point that it may look like it defeats the purpose, but not if you consider that all you have to do is download and launch the right executable for your platform only once. After that, you only need to call the 'pwshup' tool to install PowerShell, update PowerShell, and update pwshup itself (we could do like rustup and self-update when the tool is called). Even if you skip the curl-able URL part, it just becomes a matter of downloading and launching the right executable for your platform, and regular browser user agent detection can help with presenting the detected platform first to the user.

**Comment by iSazonov** [comment]
I am with @TylerLeonhardt here. 
There is no single standard, and there are many package managers and distribution channels. `pushup` will be another among many, but will not replace them.

.Net and PowerShell itself are officially supported on limited set of systems and any updater must follow this. Also it is security sensitive area - files should be signed and distribution channel should be explicitly trusted. So if this project is implemented, then it will require careful support and monitoring.

@awakecoding If you need just-another-updater why do you not implement it and share with community?

**Comment by awakecoding** [comment]
@iSazonov we are volunteering to implement pwshup ourselves, we'll probably get it done by the beginning of 2021. As I said earlier, we need it for our product, but Steve has shown interest in maybe making it an official tool. It is also my opinion that this is something worth sharing with the community.

The actual work is pending changes to get PowerShell Azure CDN download URLs instead of using GitHub releases as I originally suggested. I don't want to pressure Steve into getting those changes done faster, as we are not in a rush to get the work done this month.

My ideal timeline would be to put some of our developers from Devolutions to work on it in January of 2021, but if the Azure CDN changes are done earlier than that, we can always plan otherwise.
