### ISSUE TITLE
Feature Request - Get-Date inunixtime

### ISSUE THREAD

**Issue by darksidemilk** [PowerShell/PowerShell#14211]
## Summary of the new feature/enhancement

Maybe this is already implemented and I just can't find it, but it would be nice to be able to create a unix time instead of just converting from them. I know about the `-unixTimeSeconds` param. But I need to be able to convert a date to that time format.
i.e. `Get-date -ToUnixTime` would get the date in seconds since the epoch.
Or `Get-Date 11:00 -ToUnixTime` would get 11 am today in an integer that is the seconds since the epoch at 11 am today.

Could also be a method of the datetime object.
i.e. `(Get-Date 11:00).ToUnixTime()` if that's an easier thing to implement.

I would gladly do a pull request myself, I just would need a little help finding where the code for Get-Date is (I found the get-date tests but not the actual code).

## Proposed technical implementation details (optional)

Add something like this to a switch param in `Get-Date` or to a method of the datetime object

```
function Get-SecsSinceEpoch {
param (
    $scheduleDate = (Get-Date)
)
    process {
        $EpochDiff = New-TimeSpan "01 January 1970 00:00:00" $($scheduleDate)
        $EpochSecs = [INT] $EpochDiff.TotalSeconds - [timezone]::CurrentTimeZone.GetUtcOffset($(get-date)).totalseconds
        return $EpochSecs
    }
}
```
I did nab this code from https://jamgotre.blogspot.com/2011/02/powershell-seconds-since-1970.html and just put it in a function

Thanks!
-JJ

**Comment by iSazonov** [comment]
We have `AsUTC` so I'd expect  `AsUnix`.
