### ISSUE TITLE
PowerShell 7.1 (Microsoft Store Version) is Blocked by Windows Firewall

### ISSUE THREAD

**Issue by DesertBear** [PowerShell/PowerShell#14215]
## Steps to reproduce

PowerShell 7.1.0 (Microsoft Store Version) is blocked by Windows Firewall, despite having a valid firewall rule.

Below is an example of a blocked connection Event ID, which in this case is blocking a _Resolve-DnsName_ query to a Quad9 DNS server (UDP Port 53).

```
TimeCreated : 20/11/2020 21:12:08
Message     : The Windows Filtering Platform has blocked a connection.

              Application Information:
                Process ID:             8564
                Application Name:       \device\harddiskvolume3\program files\windowsapps\microsoft.powershell_7.1.0.0_x64__8wekyb3d8bbwe\pwsh.exe

              Network Information:
                Direction:              Outbound
                Source Address:         192.168.1.13
                Source Port:            51596
                Destination Address:    9.9.9.9
                Destination Port:               53
                Protocol:               17

              Filter Information:
                Filter Run-Time ID:     76293
                Layer Name:             Connect
                Layer Run-Time ID:      48
Id          : 5157
```

There are three ways to add a firewall rule to Windows Firewall:

**1)** By using the program exe path.  For example, by applying the firewall rule to the below program path.

`%ProgramFiles%\WindowsApps\Microsoft.PowerShell_7.1.0.0_x64__8wekyb3d8bbwe\pwsh.exe`

Although this method _can_ be used for Microsoft Store apps, it's very rarely used because many store apps put a version number in the file path.  Having a version number in the file path is problematic because every time the store app is updated, the path changes and therefore the firewall rule becomes invalid and requires manual configuration.  If Windows Firewall is set to block outbound connections that do not match a rule using Group Policy firewall rules (which have priority over local (PersistentStore) firewall rules), then the application will be automatically blocked every time it updates.  Therefore, instead if using this method, the below two methods are used instead.

**Screenshot A:**
![Screenshot A](https://user-images.githubusercontent.com/27423064/99883284-6cbe8b80-2c1e-11eb-807c-4b6f8ecda1ab.png)

**2)** By using the app package name.  For example, by applying the firewall rule to the below app package name.

`microsoft.powershell_8wekyb3d8bbwe`

This is the usual method for Microsoft Store apps when using the Windows Firewall UI.

**Screenshot B:**
![Screenshot B](https://user-images.githubusercontent.com/27423064/99883287-75af5d00-2c1e-11eb-98c8-a3a1dd930a0c.png)

**3)** By using the app package SID.  For example, by applying the firewall rule to the below app package SID.

`S-1-15-2-3474344596-1361774275-169937050-1715369765-655753896-4292765343-1302149271`

This method can also be used for Microsoft Store apps when using the Windows Firewall UI, however the app package name would normally be used instead of this.  This method however, would be used when using PowerShell to add Windows Firewall rules (I.E. When using the _-Package_ parameter with _New-NetFirewallRule/Set-NetFirewallRule_).

**Screenshot C:**
![Screenshot C](https://user-images.githubusercontent.com/27423064/99883297-8d86e100-2c1e-11eb-87af-ebba96b90236.png)

Below is an example of the PowerShell firewall rule that Microsoft adds to Windows Firewall during the Microsoft Store Version installation, which uses an app package SID to apply the rule to the app package name.

**Screenshot D:**
![Screenshot D](https://user-images.githubusercontent.com/27423064/99883300-92e42b80-2c1e-11eb-9601-1328df36af90.png)

However, despite using a valid firewall rule in Windows Firewall, PowerShell 7.1 (Microsoft Store Version) is blocked if Windows Firewall is set to block outbound connections that do not match a rule.  It makes no difference whether the firewall rule used is the one that Microsoft adds to Windows Firewall during installation, or whether it's a manually created firewall rule.  When manually creating a rule, it also makes no difference whether applying the rule to the app package name or to the app package SID.  Only using a direct path to the exe allows connections.

Therefore, it appears as though the _microsoft.powershell_8wekyb3d8bbwe_ app package name doesn't correctly point to the pwsh.exe and is preventing the firewall rule from being applied to the application.

## Expected behavior

When using either the default Microsoft firewall rule, or creating a Group Policy firewall rule based on app package name or app package SID, the firewall rule should work as intended.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by tonyg00** [comment]
If you also add the File Path and executable name the rule will work as that is what the firewall uses.

**Comment by DesertBear** [comment]
See item "**1**" in the original post.  

> _"…many store apps put a version number in the file path. Having a version number in the file path is problematic because every time the store app is updated, the path changes and therefore the firewall rule becomes invalid and requires manual configuration."_


Powershell 7 is one of those apps that has a version number in the file path.  I.E.

`%ProgramFiles%\WindowsApps\Microsoft.PowerShell_7.1.0.0_x64__8wekyb3d8bbwe\pwsh.exe`

This is why it's necessary to use an app package name instead (see item "**2**" in the original post), so that every time the app is updated, the firewall rule still continues to work.  However, "app package name" or "app package SID" do not work as expected – hence the post.
