### ISSUE TITLE
Benefit from SupportedOSPlatform/UnsupportedOSPlatform

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#14238]
.Net 5.0 introduced a code analyzer which utilize [SupportedOSPlatform attribute](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.supportedosplatformattribute)/[UnsupportedOSPlatform](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute)

We use many P/Invokes and other OS specific APIs and we could annotate such API-s with SupportedOSPlatform/UnsupportedOSPlatform attributes.

.Net user story https://github.com/dotnet/runtime/issues/43616

Samples https://source.dot.net/#System.Private.CoreLib/PlatformAttributes.cs,c486a73ae41fb2df,references

**Comment by danmosemsft** [comment]
Reach out to @terrajobst or @jeffhandley if you have questions.

**Comment by danmoseley** [comment]
did you end up using it @iSazonov ?
cc @buyaa-n
