### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by nmishr** [PowerShell/PowerShell#14240]
## Steps to reproduce
1. go this URL"
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#ubuntu-2004
2. follow the cut and paste
sudo apt-get update
sudo apt-get install -y wget apt-transport-https
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo add-apt-repository universe
sudo apt-get install -y powershell
pwsh

```powershell

```

## Expected behavior

powershell gets installed

```none

```

## Actual behavior

WSL ubuntu indicates that libssl1.0.0 is not installable

:~$ # Install pre-requisite packages.
:~$ sudo apt-get install -y wget apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.20.3-1ubuntu1).
apt-transport-https is already the newest version (2.0.2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
:~$ # Download the Microsoft repository GPG keys
:~$ wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
:~$ # Register the Microsoft repository GPG keys
:~$ sudo dpkg -i packages-microsoft-prod.deb
dpkg: warning: downgrading packages-microsoft-prod from 1.0-3 to 1.0-2
(Reading database ... 32084 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-2) over (1.0-3) ...
Setting up packages-microsoft-prod (1.0-2) ...
:~$ # Update the list of products
:~$ sudo apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
:~$ # Enable the "universe" repositories
:~$ sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.
:~$ # Install PowerShell
:~$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.0 but it is not installable
              Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.

```none

```

## Environment data

```none

```

**Comment by iSazonov** [comment]
@nmishr Please open new issue in PowerShell-Docs repository.
