### ISSUE TITLE
SSL Handshake failed in 7.1.0 on Ubuntu 18.04 with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by rmbolger** [PowerShell/PowerShell#14253]
After upgrading from PowerShell 7.0.3 to 7.1.0 on a fully patched Ubuntu 18.04 server with OpenSSL 1.1.1, web cmdlets (Invoke-RestMethod and Invoke-WebRequest) throw a `Authentication failed, see inner exception.` when connecting to our Infoblox API (which is running the latest available version of its NIOS OS, 8.5.1). Expanding the inner exception reveals the underlying problem is an SSL handshake failure. Downgrading PowerShell back to 7.0.3 fixes the problem.

*NOTE: Requests to other internal TLS sites using PS 7.1.0 work just fine. This only seems to be a problem specifically with Infoblox (that I've found so far).*

## Steps to reproduce

```powershell
# a simple call to the grid master's documentation endpoint which requires no authentication
Invoke-RestMethod https://gridmaster.test/wapidoc/
```

## Expected behavior

The web request succeeds return normal responses.

## Actual behavior

```none
Invoke-RestMethod: Authentication failed, see inner exception.
```

Serializing the exception using `$Error[0].Exception.ToString()` produces the following output:

```none
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(HttpClient client, HttpRequestMessage request, Boolean keepAuthorization) in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs:line 1361
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord() in /PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs:line 1518
```

## Environment data

`$PSVersionTable` ouput

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Linux 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

`apt-cache policy openssl` output

```none
openssl:
  Installed: 1.1.1-1ubuntu2.1~18.04.6
  Candidate: 1.1.1-1ubuntu2.1~18.04.6
  Version table:
 *** 1.1.1-1ubuntu2.1~18.04.6 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0g-2ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

Unfortunately, Infoblox doesn't allow root access to the appliance's operating system or webserver to give exact versions on things there. But the managed CLI does allow some ability to tweak TLS protocol versions and ciphers. These are the current values. TLSv1.3 is not an option and the ciphers in the list are all that is available.

```none
> show ssl_tls_protocols
TLSv1.2
> show ssl_tls_ciphers
  1. TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 enabled
  2. TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 enabled
  3. TLS_DHE_RSA_WITH_AES_128_CBC_SHA    enabled
  4. TLS_DHE_RSA_WITH_AES_256_CBC_SHA    enabled
  5. TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 enabled
  6. TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 enabled
  7. TLS_RSA_WITH_AES_128_GCM_SHA256     enabled
  8. TLS_RSA_WITH_AES_128_CBC_SHA        enabled
  9. TLS_RSA_WITH_AES_128_CBC_SHA256     enabled
 10. TLS_RSA_WITH_3DES_EDE_CBC_SHA       enabled
 11. TLS_RSA_WITH_AES_256_GCM_SHA384     enabled
 12. TLS_RSA_WITH_AES_256_CBC_SHA        enabled
 13. TLS_RSA_WITH_AES_256_CBC_SHA256     enabled
     TLS_DHE_DSS_WITH_AES_256_CBC_SHA    disabled
     TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA    disabled
     TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA    disabled
     TLS_DHE_DSS_WITH_AES_128_CBC_SHA    disabled
     TLS_RSA_WITH_RC4_128_SHA            disabled
     TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 disabled
     TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 disabled
     TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 disabled
     TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 disabled
```

**Comment by iSazonov** [comment]
@rmbolger Thanks for your investigations!

PowerShell does directly nothing with SSL - it utilize .Net. HttpClient class. Please open issue in .Net Runtime repository. (If you could make simple C# demo app it helped them.)

Notice, PowerShell 7.0 is on .Net 3.1, PowerShell 7.1 is on .Net 5.0.

**Comment by rmbolger** [comment]
Just to follow up here so answers are easier to find. Here's are the details on what is needed to fix the issue.

The crux of the issue deals with a change in the default behavior for TLS in .NET 5.0 that is described in this doc.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux

In summary, .NET 5.0 will respect `CipherString` settings (among others) in the OS's `/etc/ssl/openssl.cnf` file. But if the settings aren't specified (which is the default in Ubuntu 18.04), .NET 5.0 defaults to a very restrictive/secure/modern default set of ciphers whereas .NET 3.1 defaults to a very loose/compatible set of ciphers. So if you are connecting to services that aren't capable of modern ciphers, you need to configure the OS's config to allow one or more of the ciphers your service *does* support. The other option is a code level change in your app that deals with `CipherSuitePolicy` and `SslStream` objects. But since my issue is with PowerShell, I don't have control of the code. So my only option is the OS config change.

In my particular case, I decided to use the [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org/) on the "Intermediate" configuration setting as a guide for what ciphers to allow while remaining compatible, but still as secure as possible. And I added the following to my `/etc/ssl/openssl.cnf` file right before the `[ new_oids ]` section.

```none
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
```

The last two in the list match ciphers that are available from the Infoblox appliance. When re-testing both my .NET sample app and PowerShell's web cmdlets, neither throw an error anymore.
