### ISSUE TITLE
foreach -Parallel does not show up the progress bar

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#14254]
## Steps to reproduce
I try to copy file to multiple computers with:
```
PS C:\Work> $anps | foreach -Parallel {Copy-Item -Path C:\Install\AN\alila20200117.exe -ToSession $_ -Destination c:\software -Verbose} -Verbose

```

## Expected behavior
I hope it will show up the progress bar, just like what it will do in PSVersion 5.1.18362.1171
![image](https://user-images.githubusercontent.com/36788337/100190050-713db980-2f28-11eb-978d-cc160be95731.png)

## Actual behavior

It just show me it's copying to which computer, without progress bar.
```
PS C:\Work> $anps | foreach -Parallel {Copy-Item -Path C:\Install\AN\alilang20200117.exe -ToSession $_ -Destination c:\software -Verbose} -Verbose
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Install\AN\alila20200117.exe Destination: c:\software".
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Install\AN\alila20200117.exe Destination: c:\software".
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Install\AN\alila20200117.exe Destination: c:\software".
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Install\AN\alila20200117.exe Destination: c:\software".
```

## Environment data

```PS C:\Work> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Do you see a progress bar without `-Parallel` switch?

**Comment by tlsalex** [comment]
@iSazonov I can see the progress bar when I using foreach without -Parallel 

![image](https://user-images.githubusercontent.com/36788337/100324881-ccdc7580-3002-11eb-9175-4e0a0778671f.png)

**Comment by tlsalex** [comment]
And copy-item is much slower than SMB
I copy file from one computer to another by using copy-item , the speed is around 10-20Mbps, but if I copy file by using SMB,
the speed is around 60-90Mbps. I am not sure this issue belongs to Powershell or "Powershell Core".

**Comment by powercode** [comment]
Progress is hard. A lot of almost impossible decisions on what to display when different threads simultaneously report progress.
You could show separate progress bars, but when the number of tasks becomes larger this takes up all screen estate.

But maybe nice to have any way in some form.

**Comment by tlsalex** [comment]
but, in Invoke-Command -Session $xx it, has the ability to show the progress bar when I install software on multiple computer parallelly, but in my case , I don't know how to use invoke-command to copy file.

**Comment by iSazonov** [comment]
> And copy-item is much slower than SMB
> I copy file from one computer to another by using copy-item , the speed is around 10-20Mbps, but if I copy file by using SMB,
> the speed is around 60-90Mbps. I am not sure this issue belongs to Powershell or "Powershell Core".

I can open new issue if the scenario is important for your business process.

**Comment by iSazonov** [comment]
I think it is impossible to have one common progress bar for whole `foreach -Parallel` but one per runspace it should work.

@tlsalex Can you investigate more? Replace Copy-Item with Write-Progress to manually create a progress bar.

**Comment by powercode** [comment]
That doesn't work. The progress stream is not forwarded.

**Comment by powercode** [comment]
This seems like a bug. I'm investigating it.

**Comment by tlsalex** [comment]
@iSazonov Could I know , have you open a new issue for the slowness of copy-item?

**Comment by iSazonov** [comment]
> Could I know , have you open a new issue for the slowness of copy-item?

Sorry, my typo, it was for you.

**Comment by tlsalex** [comment]
from #14271 ,seems the fix still on its way, how to speed up it ?

**Comment by iSazonov** [comment]
> from #14271 ,seems the fix still on its way, how to speed up it ?

Collect more votes :-)
