### ISSUE TITLE
Random Crahs in Powershell 7+ (also in 7.2)

### ISSUE THREAD

**Issue by Schwanowski** [PowerShell/PowerShell#14252]
## Steps to reproduce

```
Not possible to reproduce

```

## Expected behavior

No Crash

## Actual behavior

Random Crashs

## Environment data

```
Powershell 7.2 with VS Code. Im using an portable installation of powershell 7.2 (not the msi packages).

Windows Server x64

```

![Unbenannt](https://user-images.githubusercontent.com/34173158/100162773-ac060a00-2eb4-11eb-8a3d-26330a4e1536.PNG)

Hi There,

im experiencing random crashs in Powershell V7.2. They became very rare in 7.2 while they have been more frequent in 7.0 and 7.1.

I have experienced one crash in 7.2. and attached the error message. Do you have any idea, what might cause the crash?

Thanks,

Alex

**Comment by Schwanowski** [comment]
Ok thank you. As I have no control over the envrionment I will close the issue

**Comment by doctordns** [comment]
This is a VS Code problem - I have seen it happen albeit rarely.
