### ISSUE TITLE
Feature Request - improve speed of Get-ComputerInfo

### ISSUE THREAD

**Issue by fatherjack** [PowerShell/PowerShell#14277]
## Summary of the new feature/enhancement

Improving the speed of this function will encourage people to use it over the CIM / WMI alternates. Currently this takes 3 seconds to run on my laptop, regardless of how I filter it to restrict results to smaller pieces of info (eg just total memory) whereas if I use Get-CIMInstance CIM_PhysicalMemory it takes 83ms

**Comment by iSazonov** [comment]
It is dup #9234
