### ISSUE TITLE
Set-Location -Path + fails because it mishandles the history

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell#14279]
## Steps to reproduce

Open a PowerShell 7.1 window, navigate to a safe folder for experimentation, and issue the following commands:

```powershell
# Create a folder called '[Meta]'. Careful! '-Type Folder' doesn't work!
New-Item -Name '[Meta]' -Type Directory

# Output:
# 
#    Directory: C:\Users\FrankAbignaleXIII\Desktop
#
# Mode                 LastWriteTime         Length Name
# ----                 -------------         ------ ----
# d----          2020-11-27    23:37                [Meta]
#

# Change the current folder to '[Meta]'
Set-Location -Path '.\`[Meta`]\'

# Navigate back to "Desktop"
Set-Location -Path '-'

# Navigate forward to '[Meta]'
Set-Location -Path '+'
```

## Expected behavior

After following the reproduction steps, the user expects the current folder to be the '[Meta]' folder.

## Actual behavior

In PowerShell 7.1, I received the following error:

```none
Set-Location: Cannot find path 'C:\Users\FrankAbignaleXIII\Desktop\[Meta]' because it does not exist.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Jaykul** [comment]
Can we reopen this? 

I believe it's a simple fix. The code in [SessionStateLocationAPIs.cs#L250-L265](https://github.com/PowerShell/PowerShell/blob/2502cc848066a6498297ea72bf643be9f831e406/src/System.Management.Automation/engine/SessionStateLocationAPIs.cs#L250-L265) should set `literalPath` to `true` when it successfully retrieves a path from the history.
