### ISSUE TITLE
Can't Enter-PSSession with $PSSessionConfigurationName="Powershell.7"

### ISSUE THREAD

**Issue by vlj** [PowerShell/PowerShell#14274]
Hi,
I didn't find any info on this issue at all, I have no result when looking for the error code (2689860592).

## Steps to reproduce

Install Powershell 7.1 on a local and remote computer (I tried both with msi installer and windows store), enable WinRM on both computer (via Enable-PSRemoting)
Then set $PSSessionConfigurationName to the value "Powershell.7" (or "Powershell.7.1.0", or anything that get returned by Get-PSSessionConfiguration).
Then try to login via 
```
$cred=Get-Credential;
Enter-PSSession -ComputerName XXX -Credential ${cred}
```

Note that it also happens with Powershell 5.1 on the client side. It looks like an issue on the server side.
I also reproduce it on several machine (all with Windows 10 Pro, 20H1 and 20H2)

## Expected behavior

EnterPSSession gives a prompt for Pwsh 7

## Actual behavior

```
Enter-PSSession: Connecting to remote server PC-VINCENT failed with the following error message : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2689860592" Machine="PC-VINCENT"><f:Message><f:ProviderFault provider="PowerShell.7" path="C:\WINDOWS\system32\PowerShell\7.1.0\pwrshplugin.dll"></f:ProviderFault></f:Message></f:WSManFault> For more information, see the about_Remote_Troubleshooting Help topic.
```

There is no info on about_Remote_Troubleshooting. 

## Environment data

On the client :
```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

On the server (I get them by connecting via ssh) :

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by ThePoShWolf** [comment]
Hey, I ran into this issue as well on Server 2019 and PowerShell 7.1.3 when attempting to connect with non-admin users, but fortunately found a workaround.

I found [this post](https://stackoverflow.com/questions/65131931/cant-enter-remote-powershell-7-1-session) on StackOverflow and followed his directions:

1. Delete the PowerShell 7 plugins (replace the version at the end with your version):
```powershell
Remove-Item 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WSMAN\Plugin\PowerShell.7','HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WSMAN\Plugin\PowerShell.7.1.3'
```

2. Run Install-PowerShellRemoting.ps1 again.
3. Since my non-admin user is a member of the Remote Management Users group I also added that group with permissions to the session config (I had to use the ```-ShowSecurityDescriptorUI``` parameter to figure out the syntax):
```powershell
Set-PSSessionConfiguration PowerShell.7 -SecurityDescriptorSddl 'O:NSG:BAD:P(A;;GA;;;BA)(A;;GXGWGR;;;RM)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)'
```

After that I was able to connect with my non-admin user.

**Comment by leoniDEV** [comment]
I have same issue here, but with the fx-dependent package
After enabling PSRemoting the file ```C:\Windows\System32\PowerShell\7-preview\RemotePowerShellConfig.txt``` is created and populated with two directives all of which pointi the $PSHOME folder

```
PSHOMEDIR=C:\Program Files\Powershell\7-preview
CORECLRDIR=C:\Program Files\Powershell\7-preview
```
I tried to change the last one, setting it to the folder where the runtime is installed (```C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.4.22229.4```), this way the error changes from ```Code="2689860592"``` to ```Code="2689860587"```:

```
New-PSSession: [10.30.60.5] Connecting to remote server 10.30.60.5 failed with the following error message : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2689860587" Machine="10.30.60.5"><f:Message><f:ProviderFault provider="PowerShell.7-preview" path="C:\Windows\system32\PowerShell\7-preview\pwrshplugin.dll"></f:ProviderFault></f:Message></f:WSManFault> For more information, see the about_Remote_Troubleshooting Help topic.
```

This example is with PS7.3.0-preview.4 but I get the same error also with the fx-dependent pacakge of the versions ```7.2.4```, ```7.0.11``` and ```6.2.4``` (at least, these are the versions I tested)

**Note** that if on a machine with a working PSRemoting (e.g. with a PS7 installed from the ```.msi``` package) I change the ```CORECLRDIR``` to a random value PS return the same error as the fx-dependent version (with ```Code="2689860592"``)

**Comment by vomaufgang** [comment]
We have the same problem on pwsh 7.2.4, but only if we limit the permissions of the user we use to make the connection to "Remote Management Users" on the target machine. If we put it into the "Administrators" group instead the connection works.

This is not ideal, since we are required by company guidelines to limit each users permissions as much as possible and "Administrators" is the exact opposite of that.

**Comment by sevi-kun** [comment]
Having the exact same problem as @vomaufgang. User in Active Directory Administrator group works just fine. User in local "Remote Management" group gets the above error message.

Using PowerShell 7.2.4

**Comment by DanielWilliamsMSC** [comment]
Still an issue in 7.4.2 don't think this hsould have been closed...?
