### ISSUE TITLE
Java -cp Command doesn't properly fire

### ISSUE THREAD

**Issue by jredfox** [PowerShell/PowerShell#14275]
## Steps to reproduce

```powershell
java -Dfile.encoding=Cp1252 -cp C:\Users\jredfox\Documents\MDK\md5-spreadsheet\filededuper\bin;C:\Users\jredfox\Documents\MDK\md5-spreadsheet\filededuper\libs\apache-codecs.jar jredfox.selfcmd.SelfCommandPrompt true jredfox.filededuper.Main
```

also tried this command but it resulted in error class not found `Error: Could not find or load main class .encoding=Cp1252`. yet this exact command works just fine in command prompt
```
java -Dfile.encoding=Cp1252 -cp "C:\Users\jredfox\Documents\MDK\md5-spreadsheet\filededuper\bin;C:\Users\jredfox\Documents\MDK\md5-spreadsheet\filededuper\libs\apache-codecs.jar" jredfox.selfcmd.SelfCommandPrompt true jredfox.filededuper.Main
```

on command prompt the same command works. See java -cp command on how it's parsed.  Yes I tried removing the jvm flag for file encoding same result.
```
java -Dfile.encoding=Cp1252 -cp C:\Users\jredfox\Documents\MDK\md5-spreadsheet\filededuper\bin;C:\Users\jredfox\Documents\MDK\md5-spreadsheet\filededuper\libs\apache-codecs.jar jredfox.selfcmd.SelfCommandPrompt true jredfox.filededuper.Main
```

## Expected behavior

```none
it run the command
```

## Actual behavior

```none
it prints the java command as if -cp wasn't even executed
it says unable to find file apache codecs.jar completely when the file exists on that same path and the command works with command prompt. I tried inserting quotes around the paths and everywhere can't seem to get it working.
```

## Environment data

```none
windows 10 updated last week
powershell
```

**Comment by mklement0** [comment]
`;` is a metacharacter in PowerShell (unlike in `cmd.exe`), it sequences multiple statements.
(Having additional metacharacters is the unavoidable price to pay for PowerShell's vastly superior capabilities.)

Therefore, you must use _quote_ it; either individually, as `` `; `` or, preferably, by quoting the entire argument via enclosing it in `'...'` (verbatim string) or `"..."` (expandable (interpolating)) string.

----

List of metacharacters that, when used in _unquoted_ tokens in a PowerShell argument-mode parsing context, must be `` ` ``-escaped (backtick-escaped) to be interpreted literally (only a subset applies to `cmd.exe`):

```
<space> ' " ` , ; ( ) { } | & < > @ #
```

**Comment by jredfox** [comment]
is there an escape sequence for them? You can clearly name a file with the ",`' characters so I need to tell my program to wrap them to something powershell can parse

**Comment by mklement0** [comment]
In `'...'` strings, the only thing you ever need to escape is `'` itself, as `''`, everything else is used _verbatim_ (nothing else needs escaping).

In `"..."` strings, which interpolate, you can escape `"` as `""` or `` `" ``  (though note that filenames on Windows cannot contain `"`), `$` as `` `$ `` (to suppress interpolation),  and `` ` `` itself as ``` `` ```.

You can read more about PowerShell string literals in [`about_Quoting_Rules`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Quoting_Rules) and also in [this SO answer](https://stackoverflow.com/a/55614306/45375).

Generally, please note that this repo is only for reporting actual defects and suggesting improvements.

For general support, please use the following resources:

* [Slack](https://join.slack.com/t/powershell/shared_invite/enQtMzA3MDcxNTM5MTkxLTBmMWIyNzhkYzVjNGRiOTgxZmFlN2E0ZmVmOWU5NDczNTY2NDFhZjFlZTM1MTZiMWIzZDcwMGYzNjQ3YTRkNWM) and [Discord](https://discordapp.com/invite/AtzXnJM) Community Chat - interactive chat with other PowerShell enthusiasts. Both Slack and Discord are bridged via a bot and can seamlessly talk to each other.

* [StackOverflow.com](https://stackoverflow.com/questions/tagged/powershell) and [PowerShell.org Forum](https://powershell.org/forums/) - search or post new general PowerShell usage questions.

**Comment by jredfox** [comment]
@mklement0 O I see "." is a parsing character to. that is making more sense on why it broke.

**Comment by jredfox** [comment]
solved by adding "" to each parameter which parsing characters

**Comment by mklement0** [comment]
I didn't notice the additional problem stemming from `-Dfile.encoding=Cp1252`:

Yes, `'-Dfile.encoding=Cp1252'`  or `"-Dfile.encoding=Cp1252"` works, but the quoting is only necessary due to a _bug_  - see #6291.

**Comment by jredfox** [comment]
@mklement0 I noticed the reason why my java code is now not working is the start command seems to error alot in powershell itself should I open up a new issue? I wrapped all my arguments in ""? Or should I re-open this one

**Comment by mklement0** [comment]
`start` is the built-in alias for [`Start-Process`](https://docs.microsoft.com/powershell/module/microsoft.powershell.management/start-process), which on Windows by default opens the target application in a _new window_  (and it is unrelated to `cmd.exe`'s internal `start` command) - do not use `Start-Process` to run a console application synchronously - just invoke it directly - see [this SO answer](https://stackoverflow.com/a/51334633/45375).

(There is a known problem with `Start-Process` with respect to quoting - see #5576.)

PowerShell has been around for a long time; there are a number of known bugs - reported here - and, as with any software, there are undoubtedly more that aren't yet known.

* If you find an _actual bug, based on understanding the expected behavior_ and that bug hasn't already been reported, you should report it here.

* If you need to familiarize yourself with PowerShell's fundamentals and questions arise in the process, please use the resources I've previously mentioned.
