### ISSUE TITLE
$ErrorActionPreference='Stop' and native output to stderr

### ISSUE THREAD

**Issue by aktzbn** [PowerShell/PowerShell#14273]
Release notes for powershell 7.1 contain:

* Make $ErrorActionPreference not affect stderr output of native commands
* Fix $? to not be $false when native command writes to stderr

Is it expected that the following code does not print "Hello"?

```powershell
$ErrorActionPreference='Stop'; & cmd /C 'echo Fail 1>&2' 2>fail.txt ; Write-Host "Hello"
```
## Environment data

PSVersion  7.1.0

**Comment by DHowett** [comment]
I believe you need to enable the `PSNotApplyErrorActionToStderr` experimental feature.

```
Name        : PSNotApplyErrorActionToStderr
Enabled     : False
Source      : PSEngine
Description : Don't have $ErrorActionPreference affect stderr output
```

**Comment by aktzbn** [comment]
Thank you for response.  But what is 'Make $ErrorActionPreference not affect stderr output of native commands' from release notes about in reality?
