### ISSUE TITLE
Invoke-Command returns unexpected result.

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#14272]
## Steps to reproduce

`Invoke-Command -Session $imps -ScriptBlock {get-item c:\software}`

## Expected behavior

Return correct result.

## Actual behavior
It returns empty result. But the result from PSVersion  5.1.18362.1171 is correct.
bellow screenshot, at the left side is from PSv7.1 , at the right side is from PSv5.1
![image](https://user-images.githubusercontent.com/36788337/100419481-99abec00-30bf-11eb-8862-c99c0118c747.png)

## Environment data

PS C:\Users\alex.lu> $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
PS C:\Work> $PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
It seems we already have such issue.

**Comment by mklement0** [comment]
#11400 and #10759
