### ISSUE TITLE
Invoke-Command unable to start remote session in .net 5 Blazor app

### ISSUE THREAD

**Issue by tylerforaie** [PowerShell/PowerShell#14276]
## Steps to reproduce

Updating my Blazor App to .net 5 broke PowerShell's ability to start remote sessions. I have included a vanilla Blazor app that reproduces the error. I was able to reproduce this error using any version of the PowerShell.SDK nuget package. I was unable to reproduce the error if I created a console app.

[Sample App](https://github.com/tylerforaie/powerShellBlazor)

In the sample app there are 3 variables that need to be updated in the PowerShellService.cs file

```none
computerName - remote computer to connect to
userName - username to access remote computer
password - password of user
```
The sample app calls Invoke-Command and runs Get-Process on the remote computer.

## Expected behavior

```none
PowerShell command to be run on remote computer
```

## Actual behavior

```none
PowerShell.Streams.Error logs "An error has occurred which PowerShell cannot handle. A remote session might have ended." 
```

## Environment data

```none
Using PowerShell.SDK 7.1.0 nuget package

$PSVersionTable Output:
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fMichaleczek** [comment]
@tylerforaie could you check this issue ?
https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6879

**Comment by tylerforaie** [comment]
That was exactly my issue. Guess my combination of words was just a little off, thanks!

**Comment by fMichaleczek** [comment]
@tylerforaie If you have issues with PowerShell + Asp.Net Core, tag me, I'm interested to collect them to make a RFC.
