### ISSUE TITLE
How do I show all deployment activities in Powershell?

### ISSUE THREAD

**Issue by adwissler** [PowerShell/PowerShell#14285]
To Whom it May Concern:

How do I show all deployment activities in Powershell?

**Comment by doctordns** [comment]
What deployment activities?

What is the context of this query?

**Comment by adwissler** [comment]
Dear Mr. Lee:


When I reinstall and re-register Windows Store apps via PowerShell, it shows the deployment operation progress of some activities, and then it says something.like "20 activities not shown."  How do I get PowerShell to show those activities?


Any help on this would be greatly appreciated.  Thank you very much.


Sincerely,


Andrew Wissler

**Comment by iSazonov** [comment]
@adwissler Please share repro steps and screenshots.

**Comment by adwissler** [comment]
Dear Ilya:
I can't show you the reproductive steps and screenshots because it's
working fine now, but when I open an elevated PowerShell and run
Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage
-DisableDevelopmentMode -Register
"$($_.InstallLocation)AppXManifest.xml"}, it gives deployment
operation progress for some activities, but then it says something
like "20 activities not shown." I was wondering how I can get it to
show those 20 activities.
Any help on this would be greatly appreciated. Thank you very much.
Sincerely,
Andrew Wissler

	-----------------------------------------From: "Ilya" 
To: "PowerShell/PowerShell"
Cc: "adwissler", "Mention"
Sent: Monday November 30 2020 12:43:17PM
Subject: Re: [PowerShell/PowerShell] How do I show all deployment
activities in Powershell? (#14285)

	@adwissler [1] Please share repro steps and screenshots. 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3]. 

Links:
------
[1] https://github.com/adwissler
[2]
https://github.com/PowerShell/PowerShell/issues/14285#issuecomment-735936815
[3]

**Comment by adwissler** [comment]
How can I show those 20 activities?Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: "msftbot[bot]" <notifications@github.com> Date: 12/3/20  7:00 AM  (GMT-05:00) To: PowerShell/PowerShell <PowerShell@noreply.github.com> Cc: adwissler <adwissler@roadrunner.com>, Mention <mention@noreply.github.com> Subject: Re: [PowerShell/PowerShell] How do I show all deployment activities in Powershell? (#14285) 
This issue has been marked as answered and has not had any activity for 1 day. It has been closed for housekeeping purposes.
