### ISSUE TITLE
SupportsShouldProcess does not create $Confirm in a way recognized by Strict Mode

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#14294]
## Steps to reproduce

```powershell
Set-StrictMode -Version:Latest

function Test-ShouldProcess {
    [CmdletBinding(
        SupportsShouldProcess,
        ConfirmImpact = 'High'
    )]
    param(
        [Switch]$Force
    )

    if ($Force -and -not $Confirm){
        $ConfirmPreference = 'None'
    }

    if ($PSCmdlet.ShouldProcess('TARGET')){
        Write-Output "Some Action"
    }
}

Test-ShouldProcess -Force
```

## Actual behavior

```none
InvalidOperation: C:\temp\testsp.ps1:12
Line |
  12 |      if ($Force -and -not $Confirm){
     |                           ~~~~~~~~
     | The variable '$Confirm' cannot be retrieved because it has not been set.
```

This error does not occur when Strict Mode is off. If you try to add `$Confirm` as a switch parameter you get the following error:

```none
Test-ShouldProcess: C:\temp\testsp.ps1:22
Line |
  22 |  Test-ShouldProcess -Force -confirm:$true
     |  ~~~~~~~~~~~~~~~~~~
     | A parameter with the name 'Confirm' was defined multiple times for the command.
```

So Strict Mode does not see that `$Confirm` has been defined, but **SupportsShouldProcess** does not allow you to define it.

## Environment data

This was tested in PowerShell 5.1 and 7.1.

**Comment by SeeminglyScience** [comment]
@sdwheeler A parameter is defined, but it is not translated into a variable.  Same way other common parameters work like `-Verbose`, there's no `$Verbose` variable created.

The example should be more like this:

```powershell
if ($Force -or $PSCmdlet.ShouldProcess('Target')) {
  # do thing
}
```

**Comment by sdwheeler** [comment]
So you are saying this is by design? We should probably document that there are no variables created for those parameters and you are not allowed to create variables .

**Comment by SeeminglyScience** [comment]
Yeah.  Creating a variable for the actual switch parameter wouldn't make sense because a parameter isn't the only way these things are scoped.  Verbose, warning, whatif, debug, confirm, etc are all propagated via the preference variables and also to child scopes and cmdlet calls.

`Force` is different because it's purely convention.

**Comment by mklement0** [comment]
Just to spell it out:

> all propagated via the preference variables

* In other words: For common switch parameters a local variable _is_ created, but it is a local copy of the corresponding _preference_ variable, not named for the switch itself; in the case at hand: `$ConfirmPreference`, which `-Confirm` sets to `'Low'`, and `-Confirm:$false` to `'None'`.

* This local copy is only created when the common parameter is actually specified. However, thanks to dynamic scoping `$ConfirmPreference` can usually relied on to have a value via the copy in the _global_ scope, but note that it's - surprisingly - possible to _remove_ the variable there: `Remove-Variable -Scope Global ConfirmPreference`.

Given the above (and assuming that no one has removed the global `$ConfirmPreference` copy), you could write your conditional as follows (I'm not sure what the exact intent is):

```powershell
if ($Force -and $ConfirmPreference -ne 'Low') {
  $ConfirmPreference = 'None'
}
```

**Comment by SeeminglyScience** [comment]
> you could write your conditional as follows (I'm not sure what the exact intent is):

I'd probably leave that out of the documentation though.  I believe the intended usage is letting the command runtime determine what to do (e.g. via `ShouldProcess`, `WriteVerbose`, etc)

**Comment by sdwheeler** [comment]
I have updated the doc that prompted this issue. See the original issue at https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6948

I think this can be closed. If there are more suggestions for doc updates, open a new issue in the docs repo or submit a PR with appropriate changes to the docs.
