### ISSUE TITLE
powershell does not compile with openssl 3.0 (currently at alpha) - unable to detect openssl version

### ISSUE THREAD

**Issue by satya-rajesh** [PowerShell/PowerShell#14299]
+ cd /usr/src/BUILD
+ cd powershell-linux-7.0.0
+ cd /usr/src/BUILD/PowerShell-7.0.0
+ cp /usr/src/SOURCES/build.sh .
+ cp /usr/src/SOURCES/Microsoft.PowerShell.SDK.csproj.TypeCatalog.targets src
+ chmod +x ./build.sh
+ ./build.sh
+ for f in src/powershell-unix src/ResGen src/TypeCatalogGen
+ dotnet restore src/powershell-unix

Welcome to .NET Core 3.1!^M
---------------------^M
SDK Version: 3.1.201

Telemetry^M
---------^M
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.^M
^M
Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------^M
Explore documentation: https://aka.ms/dotnet-docs^M
Report issues and find source on GitHub: https://github.com/dotnet/core^M
Find out what's new: https://aka.ms/dotnet-whats-new^M
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https^M
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs^M
Write your first app: https://aka.ms/first-net-core-app^M
--------------------------------------------------------------------------------------
No usable version of libssl was found
./build.sh: line 6: 118072 Aborted                 (core dumped) dotnet restore $f
error: Bad exit status from /var/tmp/rpm-tmp.eQwRvn (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.eQwRvn (%build)

**Comment by iSazonov** [comment]
What is `./build.sh` you use?

**Comment by satya-rajesh** [comment]
build.sh has the following:

#!/bin/bash
#See https://github.com/PowerShell/PowerShell/blob/master/docs/building/internals.md

set -ex

for f in src/powershell-unix src/ResGen src/TypeCatalogGen; do
  dotnet restore $f
done

pushd src/ResGen
dotnet run
popd

pushd src
cp Microsoft.PowerShell.SDK.csproj.TypeCatalog.targets Microsoft.PowerShell.SDK/obj
dotnet msbuild Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj /t:_GetDependencies "/property:DesignTimeBuild=true;_DependencyFile=$(pwd)/TypeCatalogGen/powershell.inc" /nologo
popd

pushd src/TypeCatalogGen
dotnet run ../System.Management.Automation/CoreCLR/CorePsTypeCatalog.cs powershell.inc
popd

#
touch DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
dotnet publish /property:GenerateFullPaths=true --configuration Linux --framework netcoreapp3.1 --runtime linux-x64 src/powershell-unix --output bin

# Even after powershell rpm built, dotnet processes are alive, following to kill them:
killall -15 dotnet

**Comment by satya-rajesh** [comment]
linux version is photon: https://github.com/vmware/photon/
I think powershell needs a compatibility with openssl 3.0 going forward - https://github.com/openssl/openssl/releases

**Comment by iSazonov** [comment]
> I think powershell needs a compatibility with openssl 3.0 going forward

It is not PowerShell dependency - it is .Net dependency.

**Comment by satya-rajesh** [comment]
> > I think powershell needs a compatibility with openssl 3.0 going forward
> 
> It is not PowerShell dependency - it is .Net dependency.

any suggestion how to get it working ? With previous openssl versions, there was no issue.

**Comment by iSazonov** [comment]
You could discuss in .Net Runtime repo https://github.com/dotnet/runtime/search?q=openssl+3.0&type=issues
