### ISSUE TITLE
Resolve-DnsName prefers a failed IPv4 query to a successful IPv6 query

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [PowerShell/PowerShell#14290]
## Steps to reproduce

Query DNS for the name `myip.opendns.com` against the OpenDNS server `resolver1.opendns.com`, it should echo your connection's public IP address.

NB. it will only retun an A record on an IPv4 connection, an AAAA record on an IPv6 connection; mixing them and querying for an A record using an IPv6 connection returns a "name not found" lookup fail. On my connection which supports both IPv4 and IPv6, this happens:

```powershell
PS C:\> Resolve-DnsName -Name myip.opendns.com -Server resolver1.opendns.com
resolve-dnsname : myip.opendns.com : DNS name does not exist
```

A WireShark packet capture shows that this goes out over IPv6 and queries both A and AAAA records. The A record lookup gets a "DNS name does not exist" response - lookup fail. The AAAA record gets an IPv6 address back. PowerShell is showing me the fail, rather than the success.

![image](https://user-images.githubusercontent.com/187787/100550512-5a71cc80-3272-11eb-8a1e-87200fcb3f58.png)

NB. that I can specify `-Type AAAA` and get a valid result, but I can't see a way to choose whether Resolve-DnsName uses IPv4 or IPv6 for its connection, so I have no way of knowing whether I should specify `-Type A` or `-Type AAAA`. One will match the connection it uses and one will not, so I would have to try both. Which is annoying, given that it defaults to trying both for me already - the only problem is it throws away the more useful result in favour of the less useful result.

## Expected result

The data from the successful query, because it's more useful.

## Actual result

The IPv4 lookup fail takes precedence, I see an exception, and the successful query data is lost to the void. 

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@HumanEquivalentUnit The cmdlet is not in the repo. It is in DnsClient module. Please use other channels to communicate with the module owners (Windows 10 feedback tool, UserVoice site, forums and so on).
