### ISSUE TITLE
Compress-Archive without duplicating the root folder

### ISSUE THREAD

**Issue by fullenw1** [PowerShell/PowerShell#14312]
## Summary of the new feature/enhancement

Currently when we compress a folder with subfolders and files,
inside the ZIP file the root folder is duplicated.

Here is an example of folder and files structure.

```powershell
+-- PackageName
      +-- Subfolder1
            -- File1
            -- File2
      +-- Subfolder2
            -- File3
            -- File4
```

The "normal" command line would be:
```powershell
Compress-Archive -Path .\PackageName -DestinationPath .\PackageName.zip
```

The problem is that inside the ZIP file named PackageName.zip the root folder PackageName is present.

```powershell
+ PackageName.zip
   +-- PackageName
         +-- Subfolder1
               -- File1
               -- File2
         +-- Subfolder2
               -- File3
               -- File4
```

This is NOT compatible with the .NUPKG format.

## Proposed technical implementation details (optional)

Can you please implement a parameter like **-NoRootFolderDuplication**?

```powershell
Compress-Archive -Path .\PackageName -DestinationPath .\PackageName.zip -NoRootFolderDuplication
```

The expected result would be:

```powershell
+ PackageName.zip
   +-- Subfolder1
         -- File1
         -- File2
   +-- Subfolder2
         -- File3
         -- File4
```

This is compatible with the .NUPKG format.

**Comment by iSazonov** [comment]
Please open issue in https://github.com/PowerShell/Microsoft.PowerShell.Archive repository.

**Comment by fullenw1** [comment]
A matching issue already exists in this repository.

[https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/43](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/43)

**Comment by w5l** [comment]
For future reference, this is possible using the following wildcard notation:
```ps
Compress-Archive -Path .\PackageName\* -DestinationPath .\PackageName.zip
```
