### ISSUE TITLE
Support hyperlinks in Show-Markdown

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/PowerShell#14315]
## Summary of the new feature/enhancement
As a user I want Show-Markdown to support hyperlinks so that I'm able to open links.

## Proposed technical implementation details
Many terminal emulators, including Windows Terminal, support clickable hyperlinks via escape sequences.

So I'd like `Show-Markdown` to render hyperlinks with the appropriate escape sequences, i.e. this:
```powershell
Write-Output 'The [PowerShell](https://github.com/PowerShell/PowerShell/) repo' | Show-Markdown
```
should include escape sequences like this:
```powershell
Write-Output "The `e]8;;https://github.com/PowerShell/PowerShell/`e\PowerShell`e]8;;`e\ repo"
```

**Comment by iSazonov** [comment]
> Write-Output "The `e]8;;https://github.com/PowerShell/PowerShell/`e\PowerShell`e]8;;`e\ repo"

This does not work in PowerShell console on Windows.

**Comment by anthonyvdotbe** [comment]
True, but it does in a PowerShell console within Windows Terminal.

**Comment by mklement0** [comment]
Good idea, @anthonyvdotbe.

@iSazonov, the good thing is that those terminals that do _not_ support this feature degrade gracefully and simply ignore the link.

Here's an overview of the support across terminal applications:

* Windows:
    * conhost.exe (legacy console windows): NO  - quietly ignores the link and prints just the link label
    * Windows Terminal, as of at least v1.4.3243.0: YES - must Control-click to open the link. 
* Unix:
    * macOS:
        * Terminal.app: NO - quietly ignores the link and prints just the link label.
        * iTerm2.app: YES - must Command-click to open the link.
    * Linux:
        * Gnome Terminal: YES - must Control-click to open the link.

**Comment by DHowett** [comment]
> > Write-Output "The `e]8;;https://github.com/PowerShell/PowerShell/`e\PowerShell`e]8;;`e\ repo"
> 
> This does not work in PowerShell console on Windows.

That doesn’t mean it won’t ever work 😉 

Graceful degradation to static non-clickable text is the _best possible outcome_, especially as it matches what already happens today.
