### ISSUE TITLE
Write-Progress doesn't always update (seems rate limited)

### ISSUE THREAD

**Issue by EmeraldFlame** [PowerShell/PowerShell#14322]
## Steps to reproduce

```
Write-Progress -id 1 -Activity 'something' -CurrentOperation 'stuff'
Write-Progress -id 1 -Activity 'something' -CurrentOperation 'more stuff'
Start-Sleep 5
```

## Expected behavior

The 'stuff' current operation would display (possibly too quick to see), but then update to 'more stuff'. 'more stuff' should be visible during the 5 second sleep.

## Actual behavior

'stuff' is written and visible during the 5 second sleep. The 'more stuff' update does not come through.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Yes, there is a rate limit. The operation is very expensive and significantly slow down script. With the rate limit the script runs as fast as possible but but it brings some side effects.
