### ISSUE TITLE
Enable DocumentationAnalyzers

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#14321]
Enable DocumentationAnalyzers for build and live analysis.

* Add package reference to [DotNetAnalyzers/DocumentationAnalyzers](https://github.com/DotNetAnalyzers/DocumentationAnalyzers).
* Disable all rules

Rule documentation:
https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/StyleRules.md
https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/PortabilityRules.md
https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/Refactorings.md

For example, #14220 fixed [DOC104: UseSeeLangword](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/DOC104.md) rule violations.

**Comment by iSazonov** [comment]
It would be nice to have I believe. Only analyzers slow down the build process. We should think how run analyzers in a more benign way.

**Comment by xtqqczze** [comment]
@iSazonov From the command-line, `dotnet build -p:RunAnalyzers=false` is supported.
