### ISSUE TITLE
Feature Request: An option to enable case-sensitive tab completion.

### ISSUE THREAD

**Issue by aniketbiprojit** [PowerShell/PowerShell#14337]
## Summary of the new feature/enhancement
I think title pretty much explains itself, but here is the idea: Have an config option in profile which allows the user to enable or disable case-sensitive tab completion. A simple filter should do.

Use Case: 
I just want to open explorer.exe and I do this `PS> exp[-> Tab]` and this happens. 
![image](https://user-images.githubusercontent.com/24915107/101291721-ecf50b80-3830-11eb-956d-0f1fe1177521.png)

And, I know adding an l should solve the problem but after years of using case-sensitive bash, it gets annoying while switching from bash to powershell. And, this has become more of a pain point since I have been using WSL regularly nowadays.

## Proposed technical implementation details (optional)

I am hoping a simple filter should do the job but I don't have the technical know-how of powershell to do it myself. If this is not released as a feature, the nudge in right direction would be great.

**Comment by iSazonov** [comment]
@aniketbiprojit Have you tried the latest PSReadline features (including experimental ones)? There are a history using and predictions. Perhaps they resolve your request or raise more feedback.

**Comment by aniketbiprojit** [comment]
They do have the interactive history search but that doesn't help me much. If I have a README.md and run.py, if I do `r[Tab->]` I should get run.py instead of README.md. The issue is for same codebase I have different completions in WSL and Powershell.

**Comment by SeeminglyScience** [comment]
> Is it for the repo or PSReadline?

Most likely would need to be in the `CommandCompletion` API.  PSRL (and PSES for that matter) does not receive what the engine determined to be the "word to complete" so it can't filter by case without duplicating a decent amount of work.

**Comment by aniketbiprojit** [comment]
Is there some easy way to implement this on my end? Something that can be used to filter results once PowerShell prints the output?

**Comment by iSazonov** [comment]
Look #1273 and #8128 for history. We need to expose the option to address the request. Also probably we need to enhance PSReadline. 
@daxian-dbw could you please triage?

**Comment by SeeminglyScience** [comment]
> Is there some easy way to implement this on my end? Something that can be used to filter results once PowerShell prints the output?

No easy way.  You could write a custom `TabExpansion2` but you'd need to find the "word to complete" on your own.  You could probably get a sorta-good-enough version by looking at the token closest to the cursor.
