### ISSUE TITLE
Can we make tab completion cycle through completions before re-using them?

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#14346]
Tab completion is great! But there is something that annoys me: it re-uses the same completion value over and over.

For example, if you type "dir <kbd>tab</kbd>, <kbd>tab</kbd>, <kbd>tab</kbd>", you'll end up with something like "dir .\foo, .\foo, .\foo".

Ideally, when you tab-complete a parameter value, it won't re-use a value that has already been used, at least not by previous tab completion. (In other words, I want to see "dir .\foo, .\bar, .\qux".)

## Repro steps:
Prep: load up the following:
```powershell
function repro
{
    [CmdletBinding()]
    param( [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
           [SupportsWildcards()]
           [string[]] $Keyword,

           [string[]] $MoreThings,

           [switch]$Force
         )
    try
    {
    }
    finally { }
}

Register-ArgumentCompleter -CommandName 'repro' `
                           -ParameterName 'Keyword' `
                           -ScriptBlock {
    param($commandName, $parameterName, $stringMatch, $commandAst, $fakeBoundParameter)

    $global:fbp = $fakeBoundParameter

    return @( 'a1', 'a2', 'b1', 'b2' )
}

```

Then type "repro <kbd>tab</kbd>, <kbd>tab</kbd>, <kbd>tab</kbd>".

**Expected result:**
The command line should now show "`repro a1, a2, b1`".

**Actual result:**
The command line shows "`repro a1, a1, a1`".

## Related:
It would be handy to use `$fakeBoundParameter` to help manually work around the problem in the completer... but due to PowerShell/PowerShell#14345 I may not have the necessary info in `$fakeBoundParameter`.

## Environment

```none
PS version: 7.1.0
PropertyNotFoundException:
Line |
  17 |      $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'PSData' cannot be found on this object. Verify that the property exists.
PSReadline version: 2.1.0
os: 10.0.20274.1001 (WinBuild.160101.0800)
PS file version: 7.1.0.0
HostName: ConsoleHost
BufferWidth: 237
BufferHeight: 9999
```

**Comment by daxian-dbw** [comment]
Transfer to the PowerShell repo.

**Comment by lzybkr** [comment]
I could see implementing this without any engine changes.

I recall a feature in 4NT (now TCC) where you would press <kbd>F10</kbd>  to accept the current completion, insert a space, and continue completing via <kbd>Tab</kbd> for the next completion. I used this a lot. It is documented [here](https://jpsoft.com/help/editing.htm) - see `AddFile`.
