### ISSUE TITLE
'Alt' prints '@' when it's remapped to an unassigned key code (vkE8 or vkFF)

### ISSUE THREAD

**Issue by eugenesvk** [PowerShell/PowerShell#14357]
I'm using **Autohotkey** to suppress the annoying menukey functionality of the <kbd>Alt</kbd> key (selecting menu items on a single press of <kbd>Alt</kbd>). However, in PowerShell it prints `@` symbols instead of printing nothing

## Steps to reproduce

Assign the following Autohotkey (this is for v2, in v1 omit the `'` symbols) mapping to the <kbd>Alt</kbd> key:
```
~Alt::Send '{Blind}{vkE8}'
```
This sends an unassigned key signal that should do nothing, but has the benefit of masking the menukey functionality (`vkFF` has no mapping, but still bugs Powershell).

Press the <kbd>Alt</kbd> key

## Expected behavior

Nothing should be printed, just like nothing is printed in all the other apps (cmd.exe console, old system powershell.exe console or any other GUI app)
```none

```

## Actual behavior
I get an `@` symbol printed instead
```none
@
```

## Environment data

Tried in both 7.1 and 7.2beta

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.1
PSEdition                      Core
GitCommitId                    7.2.0-preview.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please upload PSReadline module and check again.

**Comment by eugenesvk** [comment]
@iSazonov yes, running with `pwsh -c { rmo psreadline} -noexit` fixed the issue, no more `@` symbols; so I guess I'll create an issue with this PSReadline module instead
