### ISSUE TITLE
Select-String with both -Context  and -Raw should follow grep behavior, or be an invalid parameter set.

### ISSUE THREAD

**Issue by darthwalsh** [PowerShell/PowerShell#14350]
For [`Select-String`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string) combining `-Context` and `-Raw` is a painful gotcha. If I want to replicate `"ABCDEF" -split "" | /usr/bin/grep "B" -C 1` it seems intuitive that I could just combine these params. If I comb over the documentation, it seems like an unfortunate implementation details that `-Raw` only outputs the Line property, and doesn't consider the Context property?

The intention of using `-Raw` is to be more like `grep`, but if I was using `Select-String "B" -Context 1` then adding `-Raw` makes the output **less** like grep. I think the best option would be to match the `grep` behavior and print the Context lines, but otherwise it would help to at least error indicating there is never a reason to use `-Context` if you are using `-Raw`.

## Steps to reproduce

```powershell
"ABCDEF" -split "" | Select-String "B" -Context 1 -Raw
```

## Expected behavior

Ideally:
```none
A
B
C
```

Otherwise:
```none
Select-String: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

and then document that [`-Raw`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.1#parameters:~:text=False-,%2DRaw,Causes,-the%20cmdlet%20to%20output%20only%20the%20matching%20strings%2C%20rather%20than) can't be combined with `-Context`.

## Actual behavior

```none
B
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Good catch - it definitely makes sense to support the combination of `-Raw` and `-Context`.

Here's what I would expect that to do, expressed in PowerShell code:

```powershell
# This is what `"ABCDEF" -split "" | Select-String "B"-Raw  -Context 1` should do:
PS> "ABCDEF" -split "" | Select-String "B" -Context 1 | 
       % { $_.Context.PreContext + $_.Line +  $_.Context.PostContext  }

A
B
C
```

Note that the `$_.Context.Pre/PostContext` values are always _arrays_, so the above performs array concatenation and therefore outputs the resulting lines _individually_  - my sense is that this is more PowerShell-like (the alternative would be to output a _single, multiline_ string).

**Comment by darthwalsh** [comment]
Right, returning individual lines as individual pipeline entries instead of multiline strings is expected.

The other difficulty is ensuring that overlapping lines are only returned once, the way that `-Context 2` correctly handles:

```powershell
➜ ~ "ABCDEFGHIJKL".ToCharArray() | Select-String "B|D" -Context 2

  A
> B
  C
> D
  E
  F

➜ ~
```

**Comment by darthwalsh** [comment]
This issue should still be open
