### ISSUE TITLE
Tab Completion for powershell scripts is case sensitive when scripts found in PATH (linux)

### ISSUE THREAD

**Issue by lenihan** [PowerShell/PowerShell#14361]
I created a script "Get-Foo.ps1" that is in directory that is in my PATH.

From a directory that does not contain Get-Foo.ps1...
**If I type "get-fo" then tab, it is not found.**
If I type "Get-Fo" then tab, it is found.

From the directory that does contain Get-Foo.ps1...
If I type "get-fo" then tab, it is found.
If I type "Get-Fo" then tab, it is found.

**Comment by daxian-dbw** [comment]
The `Get-Command` behavior is:
```
PS:19> Get-Command get-foo*
PS:20> Get-Command Get-Foo*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  Get-Foo.ps1                                                   /home/user/tmp/Get-Foo.ps1
```
This needs to be addressed in PowerShell, not PSReadLine.

**Comment by mklement0** [comment]
It would certainly be nice to have consistency here, namely consistently case-_insensitive_ tab-completion and wildcard matching, even on platforms with case-sensitive file-systems.

However, something we will probably have to live with is that for actual _invocation_ of a `*.ps1` script the name has to be case-_exact_ on Linux; while that won't be a problem if that name is tab-completed, a manually typed `get-foo` command fails to call `Get-Foo.ps1`, which is a pitfall for cross-platform scripters.

**Comment by Liturgist** [comment]
Adding  `#Requires -CaseSensitive` would be helpful to cross-platform development. It would at least eliminate that problem when moving to a different platform.

**Comment by mklement0** [comment]
Technically, we have two different aspects to consider with respect to case-sensitivity:

* Globbing (wildcard-based file-name matching)
* Command lookup

Tab-completion merely uses the _results_ of the above.

* If `Get-Foo.ps1` is located in the current directory, _globbing_ applies, which in PowerShell is always case-INsensitive.

* If `Get-Foo.ps1` is (only) present in a directory listed in `$env:PATH`, _command lookup_ applies:
  * While command lookup is _generally_ case-INsensitive, with respect to commands that are _files on disk_, it is the host platform's file-system's case-sensitivity that matters in this case, so on Linux only a case-_exact_ file name / name prefix works for invocation / tab completion.

That is, on Linux (by default, but other platforms can have case-sensitive volumes too) PowerShell's case-INsensitive nature is at odds with the native file-system.

Our options are:

* Leave everything as-is and merely _document_ the problem.
  * This means that on case-sensitive file-system `*.ps1` scripts must always be invoked case-exactly: `Get-Foo` works, but `get-foo` doesn't.

* Make an exception _for `*.ps1` files_ (don't know about how feasible that is without performance concerns):
  * This is defensible in that direct, in-process invocation of plain-text `*.ps1` files (not marked as executable on Unix platforms) is clearly a PowerShell-only feature - no other shell can support that.

* Make lookup of disk-based commands  _generally_ case-INSensitive, irrespective of the case-sensitivity of the host platform's file-system (again, performance may be a concern).

(In the latter two cases there can be ambiguity if _both_ `Get-Foo.ps1` and `get-foo.ps1` exist in the same dir., for instance, but I think even saying that which one is picked is _undefined_ is acceptable in this edge case.)

---

As an aside: globbing exhibits potentially unexpected case-INsensitivity when calling native programs on case-sensitive file-systems (Linux):

For instance, the following two commands work differently on Linux:

```powershell
# PowerShell does the globbing: case-INsensitive, even on Linux:
# Matches both t.txt and T.TXT, for instance.
printf '%s\n' t*.txt

# Globbing is delegated to the native shell: case-SENSITIVE, at least by default:
# Matches only t.txt and *not* also T.TXT, for instance.
sh -c 'printf ''%s\n'' t*.txt'
```

This may just be a matter of needing to _document_ the behavior.

**Comment by JoeSalmeri** [comment]
This too is something that drives me nuts with pwsh on Linux because I want to name ps1 files Get-Foo.ps1 not get-foo.ps1 to follow general pwsh conventions.

In bash, we have the 'set completion-ignore-case on' setting in ~/.inputrc.

We need a similar type configuration for pwsh or for PSReadLine ( I don't care where it is just that it exists ).

I have the 'set completion-ignore-case on' in my .inputrc and if we go back to the original issue reported but use BASH instead of pwsh as our shell then typing 'get-fo' then tab will find Get-Foo.ps1 (since it is on the path) as would be expected.  Clearly bash does not have a problem doing the case-insensitive command searches on a case sensitive file system.

This was tested and is TRUE for both EXT4 and BTRFS file systems which are case sensitive.

I find it quite ironic that BASH can do a case-INsentive match of a powershell mixed case named script on a case sensitive filesystem and find and the script but powershell cannot!

**Comment by JoeSalmeri** [comment]
On Linux why don't they use the fnmatch function?

    https://man7.org/linux/man-pages/man3/fnmatch.3.html

The FNM_CASEFOLD allows case-insenstive matching

**Comment by kmccl922** [comment]
You'll have forced my hand about these messages i don't ever want to receive I'm contacting the FBI now let them them know you'll harassment my emails account stud it down now stop the damn messages please !

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 24, 2021 at 12:20 AM, ***@***.***> wrote:   


/cc @MartinGC94 if you have an interest.

**Comment by Liturgist** [comment]
@mklement0, this is still marked with `Issue-Bug`. Does code need to change or just documentation?

**Comment by mklement0** [comment]
@Liturgist, I was hoping that there'd be a ruling by the WG on whether one of the options I laid out in [this comment](https://github.com/PowerShell/PowerShell/issues/14361#issuecomment-782406315) is worth implementing.
After that we'll know how to amend the docs (which may then be the only action).

@iSazonov, I see that this is labeled "Up-for-grabs", which I don't think is appropriate at this point.
