### ISSUE TITLE
[BUG] InformationVariable not behaving as described

### ISSUE THREAD

**Issue by peppekerstens** [PowerShell/PowerShell#14371]
## Steps to reproduce

[Documentation states](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-5.1#informationvariable):

"The information variable contains all information messages generated by the command, including information messages from calls to nested functions or scripts."

Which (to me) implies that the assigned variable by parameter informationvariable is somehow 'automagically' global and should not have to be explicitly defined as such. 

However, even when explicitly defining the assigned variable as 'global', the information is lost when called within a nested function. 

```powershell
>>New-Variable 'Log' -Scope 'global'
>>function logtest {
    Get-Variable 'Log'
    Write-Information -MessageData "This is a test" -InformationAction 'SilentlyContinue' -InformationVariable 'Log' -Tag 'Test'
    Get-Variable 'Log'
}
```

## Expected behavior

```powershell
>>Get-Variable 'Log'
Name                           Value
----                           -----
Log
>>logtest
Name                           Value
----                           -----
Log
Log                            {This is a test}
>>Get-Variable 'Log'
Name                           Value
----                           -----
Log                            {This is a test}
```

## Actual behavior

```powershell
>>Get-Variable 'Log'
Name                           Value
----                           -----
Log
>>logtest
Name                           Value
----                           -----
Log
Log                            {This is a test}
>>Get-Variable 'Log'
Name                           Value
----                           -----
Log
```

## Environment data

Issue is not Powershell version specific as I can reproduce this in both PS5.1 and PS7.1. Did not test preview releases.

```powershell
 $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
Just like  direct variable assignments (e.g, `$Log = ...`), common `-*Variable` parameters create a _local_ variable by that name, irrespective of wether a variable by that name exists in an ancestral scope.

To explicitly  target the _global_ `$Log` variable in your example, use a _scope modifier_ (`global:Log` as an `-*Variable` argument, `$global:Log` in direct assignment):

```powershell
Write-Information -MessageData "This is a test" -InformationVariable global:Log -Tag Test -InformationAction 'SilentlyContinue' 
```

**Comment by SeeminglyScience** [comment]
> However, even when explicitly defining the assigned variable as 'global', the information is lost when called within a nested function.

It's referring to nested as in other calls to `Write-Information` within the function you're tagging, not nested as in "any scope that isn't global".

e.g.

```powershell
function Test {
    [CmdletBinding()]
    param()

    Test2
    Test3
}

function Test2 {
    [CmdletBinding()]
    param()

    Write-Information 'test2'
}

function Test3 {
    [CmdletBinding()]
    param()

    Write-Information 'test3'
}

Test -InformationVariable infos
$infos
```

**Comment by peppekerstens** [comment]
@mklement0, omfg should have known that...done it before...man... 
@SeeminglyScience very clear on usage!
Thank you both very much! Was lost in a thinking loophole (apparently)
