### ISSUE TITLE
Rounding of numbers is rounding down for even (before decimal place) numbers and up for odd (before decimal place) numbers

### ISSUE THREAD

**Issue by 5uhnjyiwat0ae8ns** [PowerShell/PowerShell#14375]
Rounding of numbers is rounding down for even (before decimal place) numbers and up for odd (before decimal place) numbers

## Steps to reproduce

Write-Host ([math]::round(([decimal]12.5),0))             ; # SHOULD BE 13; IS 12
Write-Host ([math]::round(([decimal]12.50000000000001),0)); # SHOULD BE 13; IS 12
Write-Host ([math]::round(([decimal]12.5000000000001),0)) ; # SHOULD BE 13; IS 13
Write-Host ([math]::round(([decimal]13.5),0))             ; # SHOULD BE 14; IS 14
Write-Host ([math]::round(([decimal]14.5),0))             ; # SHOULD BE 15; IS 14

## Expected behavior

Write-Host ([math]::round(([decimal]12.5),0))             ; # SHOULD BE 13; IS 12
Write-Host ([math]::round(([decimal]12.50000000000001),0)); # SHOULD BE 13; IS 12
Write-Host ([math]::round(([decimal]12.5000000000001),0)) ; # SHOULD BE 13; IS 13
Write-Host ([math]::round(([decimal]13.5),0))             ; # SHOULD BE 14; IS 14
Write-Host ([math]::round(([decimal]14.5),0))             ; # SHOULD BE 15; IS 14

## Actual behavior

Write-Host ([math]::round(([decimal]12.5),0))             ; # SHOULD BE 13; IS 12
Write-Host ([math]::round(([decimal]12.50000000000001),0)); # SHOULD BE 13; IS 12
Write-Host ([math]::round(([decimal]12.5000000000001),0)) ; # SHOULD BE 13; IS 13
Write-Host ([math]::round(([decimal]13.5),0))             ; # SHOULD BE 14; IS 14
Write-Host ([math]::round(([decimal]14.5),0))             ; # SHOULD BE 15; IS 14

## Environment data

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.1
PSEdition                      Core
GitCommitId                    7.2.0-preview.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by 5uhnjyiwat0ae8ns** [comment]
Set-StrictMode -Version Latest;

Describe 'Internal Rounding Consistency' {

Context 'Internal Rounding Consistency' {

It 'Internal Default: Number: <Number>: Digits: <Digits>: Expected: <Expected>' `
	-TestCases @(
		@{  Number = ([decimal]12.5)             ; Digits = 0; Expected = ([int]13); } # FAIL
		,@{ Number = ([decimal]12.50000000000001); Digits = 0; Expected = ([int]13); } # FAIL
		,@{ Number = ([decimal]12.5000000000001) ; Digits = 0; Expected = ([int]13); } # PASS
		,@{ Number = ([decimal]13.5)             ; Digits = 0; Expected = ([int]14); } # PASS
		,@{ Number = ([decimal]14.5)             ; Digits = 0; Expected = ([int]15); } # FAIL
	) {
	[math]::round($Number,$Digits) | Should -BeExactly $Expected;
	}

It 'Internal ToEven: Number: <Number>: Digits: <Digits>: Expected: <Expected>' `
	-TestCases @(
		@{  Number = ([decimal]12.5)             ; Digits = 0; Expected = ([int]13); } # FAIL
		,@{ Number = ([decimal]12.50000000000001); Digits = 0; Expected = ([int]13); } # FAIL
		,@{ Number = ([decimal]12.5000000000001) ; Digits = 0; Expected = ([int]13); } # PASS
		,@{ Number = ([decimal]13.5)             ; Digits = 0; Expected = ([int]14); } # PASS
		,@{ Number = ([decimal]14.5)             ; Digits = 0; Expected = ([int]15); } # FAIL
	) {
	[math]::round($Number,$Digits,[System.MidpointRounding]::ToEven) | Should -BeExactly $Expected;
	}

It 'Internal AwayFromZero: Number: <Number>: Digits: <Digits>: Expected: <Expected>' `
	-TestCases @(
		@{  Number = ([decimal]12.5)             ; Digits = 0; Expected = ([int]13); } # PASS
		,@{ Number = ([decimal]12.50000000000001); Digits = 0; Expected = ([int]13); } # PASS
		,@{ Number = ([decimal]12.5000000000001) ; Digits = 0; Expected = ([int]13); } # PASS
		,@{ Number = ([decimal]13.5)             ; Digits = 0; Expected = ([int]14); } # PASS
		,@{ Number = ([decimal]14.5)             ; Digits = 0; Expected = ([int]15); } # PASS
	) {
	[math]::round($Number,$Digits,[System.MidpointRounding]::AwayFromZero) | Should -BeExactly $Expected;
	}
}

}

**Comment by mklement0** [comment]
Re `It 'Internal Default: Number: : Digits: : Expected:` tests.

.NET uses round-half-to-even rounding by default, which in PowerShell manifests via _casts_ as well.

Thus, `[int] 12.5` getting rounded _down_ to `12` (the closest _even_ number) and `[int] 13.5` getting _up_ to `14` (again, the closest _even_ number)  is expected.

---

Re `It 'Internal ToEven: Number: : Digits: : Expected:` tests:

With `[System.MidpointRounding]::ToEven` rounding, the closest _even_ number is _always_ chosen for `.5` values; your tests seem to confuse an _even_ number with a _whole_ (integer) number.

---

_Separately_, there is a precision-loss issue relating to `12.50000000000001`. If you take that into account, the rounding again works as designed:

If you examine the result of `[decimal] 12.50000000000001`, you'll see that it resulted in _exactly_ `12.5`, which is then again subject to the implied / requested midpoint rounding.

PowerShell parses number literal `12.50000000000001` as a `[double]`, which cannot _exactly_ represent this value.
Even though `[decimal]` can, the accuracy is already lost by the time the `[decimal]` instance is constructed.

The solution is to not use a cast and instead to us suffix `d` to directly construct a `[decimal]` instance: `12.50000000000001d`

This results in a number that is _above_ `.5` and therefor correctly rounds _up_ by default:

```powershell
PS> [int] 12.50000000000001d  
13   # compare to: [int] 12.5
```

**Comment by mklement0** [comment]
As an aside, @5uhnjyiwat0ae8ns: Please use fenced code blocks in the future (` ```powershell<newline>...<newline>``` `), which make code much more readable.

**Comment by 5uhnjyiwat0ae8ns** [comment]
Understood. Thanks.
