### ISSUE TITLE
Loading personal and system profiles took so very long

### ISSUE THREAD

**Issue by rickyrsyah** [PowerShell/PowerShell#14374]
## Steps to reproduce

```none
After I login, I open pwsh
```

## Expected behavior

```none
Loading personal and system profiles took under 10000ms
```

## Actual behavior

```none
Loading personal and system profiles took so very long (~139104ms)
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.20262
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
If you run `pwsh -NoProfile` what is result?

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.

**Comment by Vedant188** [comment]
Hi guys. I know its kinda late now for this ticket, but I am facing profile loading issues. 

![image](https://user-images.githubusercontent.com/57211209/150069359-69258161-fafc-4ab9-b939-e7cf3b2d4117.png)
![image](https://user-images.githubusercontent.com/57211209/150069393-f275512b-f847-4ddf-b1f7-f1805b6febd1.png)

**Comment by KieranDevvs** [comment]
@iSazonov Can we have this re-opened, im also experiencing this issue when using `gitposh`.

**Comment by Freed-Wu** [comment]
I met this problem. It seems due to oh-my-posh, which increases about 6 seconds.

**Comment by rkeithhill** [comment]
I believe that in general, you're going to need to submit issues to the respective module repos that are causing your profile to load slowly.  I work on `posh-git` and we've done some work to improve module load times but there is still more work that could be done.  The acid test is to run `pwsh -noprofile` and see how the perf is. If that is fast, the perf issue likely something you're doing in your profile.

**Comment by tbjers** [comment]
I'm seeing similar issues with Starship where first-time start of pwsh takes anywhere between 4 seconds and 40 seconds before I get a prompt. Subsequent starts of pwsh (separately or in Windows Terminal) are pretty much instant.

**Comment by kong62** [comment]
> Hi guys. I know its kinda late now for this ticket, but I am facing profile loading issues when I use oh-my-posh v3.
> 
> ![image](https://user-images.githubusercontent.com/57211209/150069359-69258161-fafc-4ab9-b939-e7cf3b2d4117.png) ![image](https://user-images.githubusercontent.com/57211209/150069393-f275512b-f847-4ddf-b1f7-f1805b6febd1.png)
> 
> I dont have much in my profile. ![image](https://user-images.githubusercontent.com/57211209/150069504-840a8205-cb3d-45d1-a55f-e84853552a4c.png)
> 
> My profile loading time right now is: ![image](https://user-images.githubusercontent.com/57211209/150069586-fe2e248f-040a-4698-b453-7c9bb4e99412.png)
> 
> When I run pwsh -NoProfile, it loads instantly.
> 
> Time distribution of my $profile. ![image](https://user-images.githubusercontent.com/57211209/150069799-f475e7e0-e929-4bb3-a840-447e5ce61f92.png)

remove Import-Module posh-git  and Import-Module oh-my-posh

only need Set-Theme Agnoster

![snap_screen_20220925095515](https://user-images.githubusercontent.com/10241723/192124947-2a0e0966-68c1-47eb-8907-db262a734050.png)

![snap_screen_20220925095558](https://user-images.githubusercontent.com/10241723/192124967-fcc26692-628f-4c34-b77f-e54981a6827c.png)

**Comment by ScottMichaud** [comment]
_**If you trust everything in your PowerShell profile(s)**_ try excluding it (ex: Documents\PowerShell\Microsoft.PowerShell_profile.ps1) from your antivirus (and preferably remove write permissions on it except for admin/system). It was frequently >10s for me. Since that change, it has stayed around 1s.

**Comment by SteffenSchwaiger** [comment]
> _**If you trust everything in your PowerShell profile(s)**_ try excluding it (ex: Documents\PowerShell\Microsoft.PowerShell_profile.ps1) from your antivirus (and preferably remove write permissions on it except for admin/system). It was frequently >10s for me. Since that change, it has stayed around 1s. (I am running Bitdefender, although it might be wide-spread.)

This change reduced the loading time of my profile from over 4000ms to less than 1000ms. The antivirus software used is "G DATA ANTIVIRUS".

**Comment by immortalt** [comment]
I also encountered this problem.
I have to wait 2-3 seconds every time I open powershell, which is too slow.

**Comment by soban09** [comment]
> _**If you trust everything in your PowerShell profile(s)**_ try excluding it (ex: Documents\PowerShell\Microsoft.PowerShell_profile.ps1) from your antivirus (and preferably remove write permissions on it except for admin/system). It was frequently >10s for me. Since that change, it has stayed around 1s. (I am running Bitdefender, although it might be wide-spread.)

Added this profile and oh-my-posh.exe in exclusions in Windows Defender. Still doesn't work for me.

**Comment by DavidDeSloovere** [comment]
Can also be slow for me. OMP is fast though (`oh-my-posh debug`).
Not the case for me, but one might have multiple profiles loading?
Check them via `$PROFILE | Get-Member -Type NoteProperty`
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3

**Comment by yangpeng0607** [comment]
[https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url)
update of the .NET framework
Run this as Administrator
`$env:PATH = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
[AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
    $path = $_.Location
    if ($path) { 
        $name = Split-Path $path -Leaf
        Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
        ngen.exe install $path /nologo
    }
}`

**Comment by atticusrussell** [comment]
> [https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url) update of the .NET framework Run this as Administrator
> 
> ```
> $env:PATH = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
> [AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
>     $path = $_.Location
>     if ($path) { 
>         $name = Split-Path $path -Leaf
>         Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
>         ngen.exe install $path /nologo
>     }
> }
> ```

this took 500ms off my start time. Thank you!

**Comment by sheldonleung** [comment]
> 

我安装了Anaconda，并使用`conda init powershell`对PowerShell进行配置，每当我启动PowerShell，启动时间都很长。请问您的这个方案可以解决我这个问题吗？

I installed Anaconda and used `conda init powershell` to configure PowerShell, whenever I start PowerShell, it takes a long time to start. Can your solution solve this problem for me?

**Comment by sheldonleung** [comment]
> [https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url) update of the .NET framework Run this as Administrator
> 
> ```
> $env:PATH = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
> [AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
>     $path = $_.Location
>     if ($path) { 
>         $name = Split-Path $path -Leaf
>         Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
>         ngen.exe install $path /nologo
>     }
> }
> ```

我安装了Anaconda，并使用conda init powershell对PowerShell进行配置，每当我启动PowerShell，启动时间都很长。请问您的这个方案可以解决我这个问题吗？

I installed Anaconda and used conda init powershell to configure PowerShell, whenever I start PowerShell, it takes a long time to start. Can your solution solve this problem for me?

**Comment by GooDeeJAY** [comment]
> [https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url) update of the .NET framework Run this as Administrator
> 
> ```
> $env:PATH = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
> [AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
>     $path = $_.Location
>     if ($path) { 
>         $name = Split-Path $path -Leaf
>         Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
>         ngen.exe install $path /nologo
>     }
> }
> ```

For me `ngen.exe` wasn't found, so I changed it to `C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe` and it ran with many warning and exceptions.
Still my load time is  915ms

**Comment by Cheizr** [comment]
PowerShell 7.4.5
Loading personal and system profiles took 527ms.

My drive is Nvme predator GM7000

**Comment by RobThree** [comment]
> I also encountered this problem. I have to wait 2-3 seconds every time I open powershell, which is too slow.

Lucky you...

![Image](https://github.com/user-attachments/assets/81b25332-b522-4f31-b090-3d5b31cf3c29)

This is first startup. This is subsequent starts:

![Image](https://github.com/user-attachments/assets/54834d78-3a37-4b98-890c-a936a08da15a)

It varies from 1200ms to 4000ms. I have tried adding exclusions to Windows Defender, I've tried the ngen thing, I've ruled out oh-my-posh (it only gets loaded in the very end, after the delay - from wherever it comes...).

I've been messing with [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) but I haven't been able to figure it out - yet. It just... seems to freeze for some time and then resume...

**Comment by bryjen** [comment]
Some apps might modify or add profiles that get loaded before your personal profile. For example, `Conda` added the following to my `$PROFILE.CurrentUserAllHosts` which made loading take 3300ms compared to the otherwise instant without it:

```pwsh
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
If (Test-Path "C:\Users\USERNAME\miniconda3\Scripts\conda.exe") {
    (& "C:\Users\USERNAME\miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
}
#endregion
```

Try commenting out everything in your personal profile; If you notice that there was a significant speedup, then try optimizing your personal profile. If it still remains slow, it's worth checking what modules are being loaded via `Get-Module`. If you see a 3rd party application/module, check the following to see if it's being loaded there:

```pwsh
$PROFILE.AllUsersCurrentHost
$PROFILE.AllUsersAllHosts
$PROFILE.CurrentUserAllHosts
```

**Comment by cdock1029** [comment]
> [https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url) update of the .NET framework Run this as Administrator
> 
> ```
> $env:PATH = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
> [AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
>     $path = $_.Location
>     if ($path) { 
>         $name = Split-Path $path -Leaf
>         Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
>         ngen.exe install $path /nologo
>     }
> }
> ```

@yangpeng0607 ngen optimization is for Windows Powershell (`powershell.exe`) on .NET Framework, and should not have any effect on this version of PowerShell (`pwsh.exe`) on .NET Core/.NET right?

**Comment by Marerc** [comment]
> > [https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url) update of the .NET framework Run this as Administrator
> > ```
> > $env:PATH = [Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory()
> > [AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
> >     $path = $_.Location
> >     if ($path) { 
> >         $name = Split-Path $path -Leaf
> >         Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
> >         ngen.exe install $path /nologo
> >     }
> > }
> > ```
> 
> 我安装了Anaconda，并使用`conda init powershell`对PowerShell进行配置，每当我启动PowerShell，启动时间都很长。请问您的这个方案可以解决我这个问题吗？
> 
> I installed Anaconda and used `conda init powershell` to configure PowerShell, whenever I start PowerShell, it takes a long time to start. Can your solution solve this problem for me?

Another reason is that conda init script lagging the startup. the files located in `%UserProfile%\Documents\PowerShell\profile.ps1` for powershell 7.X and `%UserProfile%\Documents\WindowsPowerShell\profile.ps1` for powershell 5.X which was defalut installed in windows. These two file content shows 

```powershell
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
If (Test-Path "D:\Apps\miniconda\Scripts\conda.exe") {
    (& "D:\Apps\miniconda\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
}
#endregion
```

comment those line or just delete these files, no side effects, but startup time shortened.

**Comment by maisonsmd** [comment]
@Marerc 

> comment those line or just delete these files, no side effects, but startup time shortened.

This alone shortened my startup time form ~10 seconds to ~0.5s, thank you!

**Comment by YanniAlshoufi** [comment]
> Some apps might modify or add profiles that get loaded before your personal profile. For example, `Conda` added the following to my `$PROFILE.CurrentUserAllHosts` which made loading take 3300ms compared to the otherwise instant without it:
> 
> #region conda initialize
> # !! Contents within this block are managed by 'conda init' !!
> If (Test-Path "C:\Users\USERNAME\miniconda3\Scripts\conda.exe") {
>     (& "C:\Users\USERNAME\miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
> }
> #endregion
> Try commenting out everything in your personal profile; If you notice that there was a significant speedup, then try optimizing your personal profile. If it still remains slow, it's worth checking what modules are being loaded via `Get-Module`. If you see a 3rd party application/module, check the following to see if it's being loaded there
> 
> $PROFILE.AllUsersCurrentHost
> $PROFILE.AllUsersAllHosts
> $PROFILE.CurrentUserAllHosts

That was it for me! Thx for your comment! :)
