### ISSUE TITLE
Pass parameter by reference to a cmdlet written in C# 

### ISSUE THREAD

**Issue by AlexKichkailo** [PowerShell/PowerShell#14384]
I am trying to write a simple PowerShell cmdlet in C# that accepts an instance of ArrayList and adds an item to it. The issue I've encountered is that cmdlet receives a copy of the collection so modifying it inside the cmdlet does not work. I assume that  this is an intended behavior, but cannot find any proof for that in the documentation. I looked specifically here: https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-overview?view=powershell-7.1, but also read other sections. Below is a program to reproduce the issue. Can anyone point to the documentation or explain why cmdlet parameter binding works this way please?

## Steps to reproduce

```
using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

namespace CustomPowerShellCmdlet
{
    class Program
    {
        static void Main(string[] args)
        {
            string powerShellScript = @"
Write-Output ('PowerShell Version is ' + $PSVersionTable.PSVersion)

$A  = New-Object System.Collections.ArrayList
$A.Add('3') | Out-Null
Write-Output  ('Count is ' + $A.Count)

$B  = New-Object System.Collections.ArrayList
Add-CollectionItem -Collection $B -Item '1'
Add-CollectionItem -Collection $B -Item '2'
foreach ($Item in $B) {
    Write-Output $Item
}
Write-Output  ('Count is ' + $B.Count)
";

            var output = RunPowerShellScript(powerShellScript);

            foreach (PSObject psObject in output)
            {
                Console.WriteLine(psObject.BaseObject.ToString());
            }
        }

        private static Collection<PSObject> RunPowerShellScript(string powerShellScript)
        {
            InitialSessionState initialSessionState = InitialSessionState.CreateDefault();
            initialSessionState.Commands.Add(new SessionStateCmdletEntry("Add-CollectionItem", typeof(AddCollectionItemCmdlet), null));

            using (var runspace = RunspaceFactory.CreateRunspace(initialSessionState))
            {
                runspace.Open();

                using (var ps = PowerShell.Create())
                {
                    ps.Runspace = runspace;

                    ps.AddScript(powerShellScript);


                    return ps.Invoke();
                }
            }
        }

        [Cmdlet(VerbsCommon.Add, "CollectionItem")]
        public class AddCollectionItemCmdlet : Cmdlet
        {
            [Parameter(Mandatory = true)]
            [AllowEmptyCollection]
            public ArrayList Collection { get; set; }

            [Parameter(Mandatory = true)]
            public object Item { get; set; }

            protected override void BeginProcessing()
            {
                Collection.Add(Item);
            }
        }
    }
}

```

## Expected behavior

```Collection parameter is passed by reference
```

## Actual behavior

```a copy of ArrayList is passed to cmdlet.

```

## Environment data

PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by mklement0** [comment]
PowerShell, as C#, performs by-(variable)-value argument passing; if that value happens to be an object _reference_, (an instance of a _reference-type_), the object can potentially be modified by the callee.

I didn't run your code as such, but this simplified _PowerShell_ code demonstrates that your cmdlet works as expected:

```powershell
Add-Type @'
using System;
using System.Collections;
using System.Management.Automation;

[Cmdlet(VerbsCommon.Add, "CollectionItem")]
public class AddCollectionItemCmdlet : Cmdlet
{
    [Parameter(Mandatory = true)]
    [AllowEmptyCollection]
    public ArrayList Collection { get; set; }

    [Parameter(Mandatory = true)]
    public object Item { get; set; }

    protected override void BeginProcessing()
    {
        Collection.Add(Item);
    }
}
'@ -PassThru | % Assembly | Import-Module

$al = [System.Collections.ArrayList] @()

Add-CollectionItem -Collection $al -Item new

$al
```

This outputs `'new'`, as expected.

**Comment by AlexKichkailo** [comment]
@mklement0 thanks. This blows my mind actually. What is interesting is that if you change $al = [System.Collections.ArrayList] @() to New-Object System.Collections.ArrayList then it will output 0. Is this a bug in PowerShell?

**Comment by mklement0** [comment]
Good point, @AlexKichkailo - I hadn't considered the `New-Object` angle, and it looks like you've hit a bug:

I've opened #14394; if you agree that it is a summary of your problem, I suggest closing _this_ issue.

**Comment by AlexKichkailo** [comment]
Thank you very much, @mklement0 ! I am closing this issue then.

**Comment by mklement0** [comment]
My pleasure, @AlexKichkailo, thanks for finding and reporting the issue. Note that up-votes on issues matter when it comes to deciding what gets implemented / prioritized, so I suggest giving the linked issue a thumbs-up.
