### ISSUE TITLE
Update-Help has issues? Seems general issue?

### ISSUE THREAD

**Issue by dennisvanderpool** [PowerShell/PowerShell#14396]
PS C:\Projects\git\BuildAndReleaseFunctions\PowershellScripts> Update-Help -UICulture en-US
Update-Help: Failed to update Help for the module(s) 'PSReadline' with UI culture(s) {en-US} : One or more errors o
ccurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

**Comment by dennisvanderpool** [comment]
I've now forced it with

Update-Help -Verbose -Force -ErrorAction SilentlyContinue

Source: https://stackoverflow.com/questions/39834452/powershell-fails-with-update

**Comment by mklement0** [comment]
I'm not positive, but I think that's a known problem that, as a one-time migration step, requires renaming the local folder from `PSReadline` to `PSReadLine` - note the uppercase `L`.

**Comment by doctordns** [comment]
Yes - this is a 'well known' problem. For certain definitions of well know. I hit it this week in a book chapter I am writing.

It is awful that the help URIs are case sensitive.  But given that. What brain-child thought that up?

But in the mean time, is there ANY chance of some remediation possible? Could the MSI, for example, so a silent rename of this folder?
