### ISSUE TITLE
The background-job operator does not require the $using: scope to reference the caller's variable values, which creates ambiguity

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14400]
Note: This may come down to simply _documenting_ the ambiguity, but I'd like to get clarity on the design intent  first.

In explicit `Start-Job` calls, the only way to embed values from the _caller's_ scope is via the `$using:` scope.

By contrast, if you use the postpositional ` &` operator, this is _not_ required (but also supported).

This creates ambiguity around whether a variable reference refers to the caller's scope or the background job's.

## Steps to reproduce

```powershell
# Makes sure that $Error contains exactly 1 error.
$Error.Clear(); try { 1 / 0 } catch {}

# OK: in a Start-Job script block, "unscoped" variable references refer to 
#        variables *in the background job*. Since no errors have occurred there, the result should be 0.
Start-Job { $Errors.Count } | Receive-Job -Wait -AutoRemoveJob | Should -Be 0

# !! With the background-job *operator*, an "unscoped" variable reference
# !! refers to a variable *in the caller's scope*, if such a variable exists there.
($Error.Count &) | Receive-Job -Wait -AutoRemoveJob | Should -Be 0
```

## Expected behavior

Both tests should succeed.

## Actual behavior

The 2nd test fails, because `$Error` is interpreted as referring to the _caller's_ variable.

```none
 Expected 0, but got 1.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.1
```

**Comment by bpayette** [comment]
It might be a bit surprising but it's not ambiguous. `$using:` can only be used in a _scriptblock_ and there is no scriptblock here. As far as the user experience goes, when we were designing the feature we felt that having this work:
```powershell
$foo = "Hello"
# doesn't require `$using:`  because it's just parameter passing
write-output $foo &
```
but this
```powershell
$foo = "hello"
$foo &
```
fail was a bad experience. So we made it just work.

**Comment by mklement0** [comment]
Thanks for clarifying the design intent, @bpayette.

> `$using:` can only be used in a _scriptblock_

Of course, hypothetically, that doesn't prevent treating `$foo` in statement `$foo &` _as if it were a script block_ - which is a reasonable assumption to make if you conceive of `Start-Job { ... }` and `... &` as mere _syntax variations_, especially given how ` &`, the background operator,  is [currently documented](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators?view=powershell-7.2#background-operator-):

> This operator is functionally equivalent to `Start-Job`.

---

I do get that the user experience is better if the background operator does _not_ require `$using:`, but - at least hypothetically - it does prevents certain scenarios.

The ambiguity exists relative to `Start-Job`, but if we focus on the background operator alone, it's more a case of _invariably shadowing_ variables local to the background job and therefore not being able to refer to them:

The OP already demonstrates it with respect to `$Error`, but let me show another example:

```powershell
PS> $FormatEnumerationLimit = 42; ($FormatEnumerationLimit &) | Receive-Job -wait -AutoRemoveJob
42  # $FormatEnumerationLimit referred to the CALLER'S copy
```

vs.

```powershell
PS> $FormatEnumerationLimit = 42; sajb { $FormatEnumerationLimit } | rcjba
4  # The JOB's default vlue.
```

It may be mostly hypothetical, but with the background operator there is no straightforward way that I'm aware of that would allow you to unambiguously reference the _background job_'s `$FormatEnumerationLimit` copy - to that end, an _inverse_ `$using:` construct would be needed.

(Yes, you could do `$FormatEnumerationLimit='@'; (& ([scriptblock]::create('$FormatEnumerationLimit')) &) | Receive-Job -wait -AutoRemoveJob`, but, needless to say, that is both highly obscure and cumbersome.)

**Comment by mklement0** [comment]
To offer an example that is perhaps closer to real life:

```powershell
# !! This prints the CALLER's $PWD, as explicit use of $using:PWD would.
# !! There is no way to refer to the JOB's $PWD when using the background operator.
(& { Set-Location /; $PWD } &) | Receive-Job -Wait -AutoRemoveJob
```

Incidentally, by contrast, with `$PID` it is the _caller's_ copy that is visible by default:

```powershell
PS> $PID; ($PID &) | Receive-Job -Wait -AutoRemoveJob
21873
31086
```

Because of that, `$using` actually helps in _this_ case:

```powershell
PS> $PID; ($using:PID &) | Receive-Job -Wait -AutoRemoveJob
21875
21875
```

Also note the use of `$using:` _without_ an explicit script block (`{ ... }`), contradicting your earlier claim that `$using:` can only be used inside one.

Generally, though, for full feature parity with `Start-Job` a hypothetical `$callee:` pseudo scope would be needed, to bypass shadowing of the job's variables by the caller's.

I understand that this isn't really called for in practice, but it highlights the limitations of the background operator.

I will open a docs issue to request clarifying the difference between the background operator and `Start-Job` and will close this issue then.
