### ISSUE TITLE
Get-ADUser returns PSObject instead of  Microsoft.ActiveDirectory.Management.ADAccount

### ISSUE THREAD

**Issue by madserg** [PowerShell/PowerShell#14408]
Hi,

Command Get-ADUser (ActiveDirectory module) returns PSObject in PowerShell 7.1.
But in 5.1 it returns Microsoft.ActiveDirectory.Management.ADAccount.
So all my scripts does not work in PS7.1 :(

Powershell 5.1:
![image](https://user-images.githubusercontent.com/16781134/102009089-6dd26c80-3d35-11eb-9f7a-2ebf607dd586.png)

Powershell 7.1
![image](https://user-images.githubusercontent.com/16781134/102009082-64e19b00-3d35-11eb-9d5d-c17d199056bb.png)

**Comment by mklement0** [comment]
I'm wondering if the Windows PowerShell compatibility feature is involved - see [`about_Windows_PowerShell_Compatibility`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility).

If so, the _deserialized_ objects that are output via the implicitly employed remoting are invariably `[psobject]`s that are method-less _emulations_ of the original objects. The only way around that would be a PowerShell Core-native version of the AD module.

**Comment by jborean93** [comment]
There is a PowerShell Core compatible version shipped with newer Windows 10 builds. Can you share what Windows version you are on?
