### ISSUE TITLE
Will it be an issue in foreach -Parallel under my scenario.

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#14412]
## Steps to reproduce

```powershell

$sip= 25..135 | foreach {"10.10.10.$_"}
$ship | foreach -Parallel {if (Test-Connection -ComputerName $_ -Quiet -Count 2) {Add-Content -Path .\online.txt -Value $_} } -ThrottleLimit 10  -Verbose
```

## Expected behavior

```none
Every IP address that response to ICMP request will be added to online.txt

```

## Actual behavior

```none
The whole script runs without any error. But just wonder:
```
Script will test 10 computers at the same time. If the 10 testing finish at the same time, and try to add the IP address to online.txt at the same time,  seems it will be a conflict, as 10 sessions try to access the same file, will it causes some sessions give up the addition of IP address.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Yes, you'll have to do your own cross-thread synchronization - `ForEach-Object -Parallel` doesn't do that for you.

Unfortunately, `Add-Content` can seemingly fail quietly in this scenario.

In your case I would bypass the problem by simply collecting all outputs in memory and writing them to a file later (note that the order of outputs will generally not match the inputs either way).

**Comment by tlsalex** [comment]
thanks ,now I do that in bellow way, hope PS team improve it more.
`$ship | foreach -Parallel {if (Test-Connection -ComputerName $_ -Quiet -Count 2 -Delay 1) {$_}} -ThrottleLimit 10 | tee -Path .\2online.txt`

**Comment by mklement0** [comment]
That's a good solution; as for improvements: I think the only improvement possible here is to make `Add-Content` fail _loudly_, i.e. to have it emit an error.

**Comment by iSazonov** [comment]
Let's continue in #14416.
