### ISSUE TITLE
powershell-linux binaries support for openssl 3.0

### ISSUE THREAD

**Issue by satya-rajesh** [PowerShell/PowerShell#14410]
Package used: powershell-linux-7.0.0

powershell-linux$ grep -r "ERR_put_error" .
Binary file ./System.Security.Cryptography.Native.OpenSsl.so matches
Binary file ./System.Security.Cryptography.Native.OpenSsl.a matches

ERR_put_error which has references in powershell-linux binaries is deprecated in openssl 3.0
Reference: https://www.openssl.org/news/changelog.html

**Comment by jborean93** [comment]
I believe this should be logged with .Net itself (it probably already is). I’m not aware of any direct OpenSSL deps that PowerShell has so there’s not much they can do here.

**Comment by satya-rajesh** [comment]
> I believe this should be logged with .Net itself (it probably already is). I’m not aware of any direct OpenSSL deps that PowerShell has so there’s not much they can do here.

This has and i was thinking this is a powershell release, please confirm:
https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/powershell-7.0.0-linux-x64.tar.gz

**Comment by iSazonov** [comment]
Please re-check with latest **7.0.3** version.
If the issue persists - we can do nothing in the repo - open issue in .Net Runtime repository.
PowerShell 7.0 is based on .Net 3.1.
