### ISSUE TITLE
Unexpected behaviour of -contains

### ISSUE THREAD

**Issue by norrisgc** [PowerShell/PowerShell#14427]
This isn't new: it also occurs with PS 5.1.

## Steps to reproduce

PowerShell 7.2.0-preview.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Program Files\PowerShell\7-preview> $x = 'abcd', $true
PS C:\Program Files\PowerShell\7-preview> $x
abcd
True
PS C:\Program Files\PowerShell\7-preview> $x -contains 'pqrst'
True
PS C:\Program Files\PowerShell\7-preview>

## Expected behavior

False

## Actual behavior

True

## Environment data

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.1
PSEdition                      Core
GitCommitId                    7.2.0-preview.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by scriptingstudio** [comment]
the same here
```
'sdfg' -in 'dgh',$true
True
```
