### ISSUE TITLE
Colorize table and list headers

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#14429]
## Summary of the new feature/enhancement

When `Get-Error` was implemented, there was a deliberate decision to introduce a new `FormatAccent` color to help differentiate the metadata from the data visually.  We can use this same color to separate table headers and list metadata.  This PR implements this https://github.com/PowerShell/PowerShell/pull/14406

Example:

![image](https://user-images.githubusercontent.com/11859881/102249659-718dfc80-3eb7-11eb-972e-e12176c77db0.png)

@powercode asked a good question whether we want separate user configurations for tables vs lists.  My preference is to keep it simple and just have one setting.

Another consideration is that if ANSI is available, the table header can be rendered with an underline instead of using up a row of dashes.

**Comment by jhoneill** [comment]
Using the accentColor for labels works as well or as badly as the choice of different accents - the change to a green font is fine, everything _flows_ , the change to background means that blue block for the table header makes it too separate. This is a lot less controversial than some of the others, if one dislikes it, change the accent colour, if one wants to go mad with it, change the accent colour :-)  
 
Underline for headers is worth considering (but green does it quite nicely. )   I'd also suggest looking at whether ----- should be as wide as the label, or run the full width of the column. Underline probably only goes as far as the text..

**Comment by iSazonov** [comment]
It would be preferable to be able to, but not impose.

**Comment by SteveL-MSFT** [comment]
To be clear, don't focus on the blue background example, that was ONLY intended to show what a user can customize for themselves and would not be considered as a default option.

**Comment by jhoneill** [comment]
> To be clear, don't focus on the blue background example, that was ONLY intended to show what a user can customize for themselves and would not be considered as a default option. Users can decide they don't want color, but just want to have labels in italics or bold.

And I think that is the best thing about the proposal. We can see how it is changed in your video so it's reasonably clear that the white on blue was a user choice - and users can pick what works for them (even if others hate it). Personally I'd have bold labels and one colour.  Provided it redirects without escape codes of course :-)

**Comment by SteveL-MSFT** [comment]
Here's an example with emphasis on the data instead of the metadata:

![image](https://user-images.githubusercontent.com/11859881/102284635-563be500-3ee9-11eb-831d-bd212a8ddbfd.png)

As for redirection, `$PSStyle.OutputRendering = 'host'` already covers that in that redirected output will always be plaintext with this set.  Note that default is `automatic` which mimics Linux behavior whereas `host` mimics macOS behavior.  I'm open to switching the two and make `host` default if that is what most folks prefer.

**Comment by iSazonov** [comment]
> I'm open to switching the two and make `host` default if that is what most folks prefer.

I think [my comment](https://github.com/PowerShell/PowerShell/issues/9270#issuecomment-745775526) is applicable here too.

**Comment by powercode** [comment]
@SteveL-MSFT My suggestion was to separate AccentFormat from HeaderFormat.
AccentFormat may be used to highlight things, which is not the same thing as separate headers from content.

**Comment by powercode** [comment]
There may be a better name than Header, but the main point was to not use `FormatAccent` since that should be used to draw attention to something in the text. This is not conceptually the same.

**Comment by SteveL-MSFT** [comment]
@powercode I see.  `FormatAccent` currently is only used with `Get-Error` to provide visual distinction between property names and values, so using the same color for `Format-List` makes sense to me.  For tables, I'm ok with a separate member that can be customized, but perhaps have it the same color by default.  Since this is now under `$PSStyle.Formatting`, I think just calling it `TableHeader` would be concise and don't need the word `Format` in it at all.

**Comment by powercode** [comment]
When thinking about this, I think we should separate "What color is used" from "What it logically is".

Get-Error should probably use the logical color as Format-List, but I don't think it should be `FormatAccent`, which I would use for accentuating text in a flow, like select-string or so.
`ListHeader` would be more appropriate. They could default to the same color but should be different concepts.

**Comment by SteveL-MSFT** [comment]
Revisiting this now that I have some time.  I like the separation of table and list colors.  However, we've already shipped FormatAccent and would be a breaking change to rename it now.  I think I'll just add a `TableHeader`.

**Comment by ThomasNieto** [comment]
@SteveL-MSFT it wouldn't be an official breaking change since this feature has only shipped in preview correct? I just upgraded to preview 8 and didn't find `FormatAccent` for list headers to be user friendly and didn't make the connection until finding this issue.
