### ISSUE TITLE
Copy-Item -WhatIf should not fail

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#14432]
Per [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.1#whatif), `-WhatIf` should describe the effect of the command instead of executing.  So in the case that the file doesn't exist, it shouldn't matter.

## Steps to reproduce

```powershell
Copy-Item ./foo.bar -Destination test -WhatIf
```

## Expected behavior

```none
What If: Performing operation 'Copy File' on
Target './foo.bar'
```

## Actual behavior

```none
Copy-Item: Cannot find path 'foo.bar' because it does not exist.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.1
PSEdition                      Core
GitCommitId                    7.2.0-preview.1-143-gb8f3acda010c34fe2659658e7330373055b26431
OS                             Darwin 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
`-WhatIf` isn't an _abstract_ hypothetical; its purpose is to test-drive a _specific_ command, so I think it is appropriate to perform as much (side effect-free) up-front validation as possible.

**Comment by iSazonov** [comment]
What is behavior other cmdlets like Remove-Item, Rename-Item, ...?
