### ISSUE TITLE
Add a quiet parameter to Test-WSMan in order to returns a Boolean value

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#14436]
## Summary of the new feature/enhancement
Just like Test-Connection , add a quiet parameter to Test-WSMan in order to returns a Boolean value
In some computer, WSMan is not enable by default. And sometimes I need to collect a list of computer with WSMan enabled via an if statement as bellow:

```powershell
$ship | foreach -Parallel {if (Test-Connection -ComputerName $_ -Quiet -Count 2 -Delay 1) {$_}} -ThrottleLimit 10 | tee -Path .\2online.txt
```

## Proposed technical implementation details (optional)

```powershell
$ship | foreach -Parallel {if (Test-WSMan -ComputerName $_ -Quiet) {$_}} -ThrottleLimit 10 | tee -Path .\2online.txt
```

**Comment by iSazonov** [comment]
Since MSFT team plans to move Remoting to new Engine Subsystem and we will be able to create alternative Remoting (transport) implementations and I think the cmdlet should be transformed to new cmdlet like `Test-Remoting`. In this case, the new parameter can be useful too.

**Comment by jdhitsolutions** [comment]
Absolutely agree we need a `-Quiet` parameter to stay in line with other test commands.

**Comment by tlsalex** [comment]
any update ?

**Comment by jdhitsolutions** [comment]
Added to the Cmdlet Working Group review list.

**Comment by JamesWTruher** [comment]
i'm a little concerned about the name of the parameter. `quiet` usually indicates _no_ output (test-connection not withstanding). how about a different name?

**Comment by jdhitsolutions** [comment]
The Working Group has reviewed this and agrees there is a need for a `-Quiet` parameter to return a boolean value. While there is some debate about whether `Quiet` is the appropriate parameter name, there is precedent with `Test-Connection` and `Select-String`. This issue will be marked as `Up for Grabs`.

**Comment by kort3x** [comment]
bump

**Comment by tlsalex** [comment]
any update?
