### ISSUE TITLE
Update tags on master repository

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#14439]
*Reoccurring issue:  tags on master are not up-to-date*

Last tag on *master* is set to `v7.2.0-preview.1` that causes the local builds of up-to-date PowerShell repository to show wrong build number:

![image](https://user-images.githubusercontent.com/16168755/102313298-a90caf80-3f70-11eb-9e07-aafb9b2e5458.png)

![image](https://user-images.githubusercontent.com/16168755/102313780-8af37f00-3f71-11eb-98ab-2a4a30030f25.png)

## Steps to reproduce

```git
git fetch --all --tags
git describe
```

## Expected behavior

```none
v7.2.0-preview.2
```

## Actual behavior

```none
v7.2.0-preview.1-144-g3f95fc491
```

**Comment by rjmholt** [comment]
Yeah this is because the release isn't quite finished yet

**Comment by kborowinski** [comment]
@rjmholt It seems that I jumped the gun, should I stop reporting tagging issues in the future?

**Comment by iSazonov** [comment]
@kborowinski Current workflow is - MSFT team creates a release branch internally, prepares new release, after the release they merge the release branch to master one. If after the merge you see any issues (tags, docs, links and so on) please report.

**Comment by rjmholt** [comment]
So I think `git fetch --tags` would solve the problem, but I've now merged the PR above so `git fetch` might also solve it now. I'm slightly concerned though since I omitted a bugfix commit that the release used (rather than add a reversion commit) and that might be an issue for this

**Comment by kborowinski** [comment]
Could you update the tags on master again? The *v7.2.0-preview.5* is going to be released soon but the tag on *master* is still set to *v7.2.0-preview.3* which causes my daily builds to end with following string:
![image](https://user-images.githubusercontent.com/16168755/114988818-0bca7500-9e97-11eb-8662-d0b6f2f2f993.png)
