### ISSUE TITLE
Empty folder size value should be set to zero

### ISSUE THREAD

**Issue by petrasteri** [PowerShell/PowerShell#14449]
## Steps to reproduce

We use the following instruction to calculate a folder size

gci c:\my_folder | measure Length -sum

However, if the folder is empty, this instruction returns an error.  This happens in PowerShell 5 to PowerShell 7 (Win 10 to Windows Server 2016 to 2019).  The error message is:

**Measure-Object: Cannot process argument because the value of argument “Property” is not valid. Change the value of the “Property” argument and run the operation again.**

## Expected behavior
Returns 0.  No error.  Especially, no red error message on the screen.

## Actual behavior
Big RED error message on the screen.  Even though 0 is returned, but the error message is annoying.

## Environment data
c:\my_folder is an empty folder

## My opinion
Measure-Object’s behaviour is correct.  So the culprit is the folder object returned by PowerShell.  The size property of the folder object should be set to zero by default.

Of course, if other changes in PowerShell's internal working could lead to the disappearance of the error message, I'm happy with that too.

**Comment by powercode** [comment]
How about using `gci -file` if your intention is to only measure files?

**Comment by petrasteri** [comment]
I have tried your command but I don't get what you mean.

But my intention is to get the folder size, meaning that the sum of all files inside it, no matter the number of files inside it.  If the folder is empty, I of course expect the size to be zero.

It's like counting the number of people living in a house in real life.  If a house has nobody living inside it, I expect the answer to be zero, not "something is not a property of the house".

**Comment by FrankDetzer** [comment]
Hey petrasteri,

is that "my_folder" an actual folder or is a symlink?

**Comment by petrasteri** [comment]
Not symlink

Look, here is an example with my C:\temp\p folder

![image](https://user-images.githubusercontent.com/12992229/102482835-206f3b80-4064-11eb-919f-d63fe17c6812.png)

**Comment by petrasteri** [comment]
Maybe it's better that an official cmdlet called **get-folder-size** is given so we don't have to fiddle with **gci** and **measure**

**Comment by FrankDetzer** [comment]
I am actually working on a module that could solve your problem. it is about folder sizes aswell, if your interessted i could finish it in a few days.

**Comment by petrasteri** [comment]
That's nice.
Will your module be available only in the new PowerShell 7?  Or will it be reintegrated into PowerShell 5 (in Windows 10 and Windows Server 2019)?

**Comment by FrankDetzer** [comment]
its developed in pwsh7 but i see no reason yet it wouldn work on pwsh5 or even 3.

**Comment by petrasteri** [comment]
That sounds great.

**Comment by bpayette** [comment]
The problem only occurs when the folder isn't empty but only contains folders. In this situation, @powercode's suggestion does workaround the issue:
```powershell
gci -file c:\my_folder | measure Length -sum
```
since it doesn't return the `DirectoryInfo` objects.  That said, this does seem inconsistent. Unless you're in strict mode, PowerShell simply ignores missing properties so, unless otherwise specified, `Measure-Object` should do the same.

**Comment by iSazonov** [comment]
The code is here:
https://github.com/PowerShell/PowerShell/blob/7f3364f5dd5c3095d1b177c682960f3bb3ca4ca0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs#L818-L827

**Comment by FrankDetzer** [comment]
@petrasteri 
Hey i just released my ncdu clone

https://github.com/FrankDetzer/HumanFriendlyOutput

**Comment by KiwiThePoodle** [comment]
@bpayette

Hey, I just wanted to clarify on your comment. Are you saying that Measure-Object should just ignore the missing property and not print the error when gci -file is not used?

**Comment by plastikfan** [comment]
It would be nice for this to get fixed properly for Directories (which don't contain files) without resorting to measuring files instead of directories as the workaround suggested above. For directory structures with large numbers of files, measuring individual files is dog slow compared to measuring directories and is very noticable for large directory trees, so its not a practical solution. Looking forward to seeing this get fixed, thanks.

**Comment by petrasteri** [comment]
> @bpayette
> 
> Hey, I just wanted to clarify on your comment. Are you saying that Measure-Object should just ignore the missing property and not print the error when gci -file is not used?

Yes, that is logically consistent with what we expect.

**Comment by petrasteri** [comment]
I have just tried this command in PowerShell 7.3.9.

Now, the command does not produce error, but it does not return 0 either 😅

Further more, dir "some_folder" does not show the same info like before.  Here's a screen shot.  If you compare it with my previous one, you can see the behaviours are very different!


![image](https://github.com/PowerShell/PowerShell/assets/12992229/59818dd2-5eec-48ae-be9d-66ffd7132f5d)

**Comment by cgraf-spiria** [comment]
Can't believe how hard it is to get the folder size (in a reliable way!!) in PowerShell/Windows 🤯🤬
If it helps someone, here's a manipulation that is able to handle empty subfolders without throwing an error:
```powershell
$FolderPath="...folder you wish to print size..."
((Get-ChildItem -Force -Recurse $FolderPath | ForEach-Object { if($_.PSObject.Properties['Length']) { $_.Length } else { 0 }} | Measure-Object -Sum).sum  / 1MB)
```
