### ISSUE TITLE
Make *-PSSessionConfiguration cmdlet context aware with PowerShell Core

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell#1445]
1. Register-PSSessionConfiguration cmdlets should use the PowerShell Core version of pwrshplugin.dll to create new remoting endpoints
2. Looks like Set-PSSessionConfiguration shouldn't need any more changes (cross-check)
3. Get/Enable/Disable/Unregister-PSSessionConfiguration shouldn't need any change (cross-check)

**Comment by joeyaiello** [comment]
@HemantMahawar do you have a simple repro we can try and validate here?

**Comment by mirichmo** [comment]
Resolved via #2671
