### ISSUE TITLE
ERROR_WSMAN_INVALID_SELECTORS to Office 365/Exchange Online

### ISSUE THREAD

**Issue by zhiweiv** [PowerShell/PowerShell#14450]
## Steps to reproduce
Create a PowerShell container(mcr.microsoft.com/powershell:7.1.0-debian-buster-slim) in AKS

Run following command in container

```
Install-Module -Name PSWSMan -Force
Install-WSMan

$username = 'admin@test.onmicrosoft.com'
$password = '***********'
$secure = ConvertTo-SecureString $password -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($username, $secure)
$session = New-PSSession -Credential $credential -ConfigurationName "Microsoft.Exchange" -ConnectionUri "https://ps.compliance.protection.outlook.com/powershell-liveid/" -Authentication Basic -AllowRedirection
Import-PSSession $session -CommandName Get-Label
Get-Label
```

We get following error
`OperationStopped: Starting a command on the remote server failed with the following error message : ERROR_WSMAN_INVALID_SELECTORS: The WS-Management service cannot process the request because the request contained invalid selectors for the resource.  For more information, see the about_Remote_Troubleshooting Help topic.`

1 The error only occurs in an AKS which behinds Azure Firewall, it works in other AKS, works in container of Azure VM.
2 If we execute Get-Label multiple times, it doesn't always error, it may work too.

The powershell is 7.1, any way we can take to troubleshooting this?

**Comment by jborean93** [comment]
Looks like you are using the fork of OMI, you should raise that issue at https://github.com/jborean93/omi as that's where the code lies and not in PowerShell. I can't guarantee I will be able to get to this anytime soon, I would have a look at the logging information https://github.com/jborean93/omi#troubleshooting to try and get some more info and share that in the request.

**Comment by zhiweiv** [comment]
Thanks for the information, I have enabled debug log of libmi to check the issue.

I will open new issue in jborean93/omi if necessary.
