### ISSUE TITLE
Cross field parameter validation fails when invoked by splatted parameters

### ISSUE THREAD

**Issue by plastikfan** [PowerShell/PowerShell#14457]
## Steps to reproduce

Just define a function with cross field parameter validation on 1 or more of its parameters eg:

```powershell
function Get-InverseSubString {
  param(
    [Parameter(Position = 0, Mandatory)]
    [string]$Source,

    [Parameter()]
    [ValidateScript( { $_ -lt $Source.Length })]
    [int]$StartIndex = 0,

    [Parameter()]
    [ValidateScript( { $_ -le ($Source.Length - $StartIndex ) })]
    [int]$Length = 0,

    [Parameter()]
    [switch]$Split,

    [Parameter()]
    [char]$Marker
  )

  ... implementation omitted, because it's irrelevant
}
```

now invoke via splatted parameters:

```powershell
      [System.Collections.Hashtable]$parameters = @{
        'Source' = $Source;
        'StartIndex' = $m.Index;
        'Length'     = $m.Length;
      }
      [string]$remainder = Get-InverseSubString @parameters;
```

## Expected behavior

no error should be reported. If we invoke **Get-InverseSubString** directly, then the execution proceeds without error:

```powershell
      [string]$remainder = $PSBoundParameters.ContainsKey('Marker') `
        ? $(Get-InverseSubString -Source $Source -StartIndex $m.Index -Length $m.Length -Marker $Marker) `
        : $(Get-InverseSubString -Source $Source -StartIndex $m.Index -Length $m.Length);
```

But the above is just a work-around for a scenario in which splatting should be ok.

## Actual behavior

```none
[-] Split-Match.given: Pattern does match.and: multiple matches.and: NOT CapturedOnly.and: First.should: Get first Occurrence 4ms (3ms|1ms)
 RuntimeException: The variable '$StartIndex' cannot be retrieved because it has not been set.
 ParameterBindingValidationException: Cannot validate argument on parameter 'Length'. The variable '$StartIndex' cannot be retrieved because it has not been set.
 at Split-Match, C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Output\Elizium.Loopz\Elizium.Loopz.psm1:3148
 at <ScriptBlock>, C:\Users\Plastikfan\dev\github\PoSh\Loopz\Elizium.Loopz\Tests\Public\Split-Match.tests.ps1:26
```

## Environment data

λ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```none

```

**Comment by mklement0** [comment]
Your approach is conceptually flawed, because **you cannot - and should not - rely on the _order_ in which parameters are bound**.

That is, while the following _happens to_ work:

```powershell
Get-InverseSubString -Source 'foo' -StartIndex 0 
```

the following does _not_ (note the reversal of the argument order):

```powershell
Get-InverseSubString -StartIndex 0 -Source 'foo'
```

When _named_ arguments (values preceded by the target parameter name) are used, users are and should be free to choose the order in which those values are passed.

**Comment by mklement0** [comment]
To summarize:

* For your function to work _robustly_, it mustn't make assumptions about the order in which parameters are bound.
* You can therefore not solve your problem in your parameter declarations and must perform the desired validation in your function _body_.

_If_ you nonetheless wanted to rely on the order in which parameters are bound, your splatting hashtable must be an _ordered_ hash table to guarantee the the ordering of entries (`[hashtable]` does _not_ guarantee entry order):

```powershell
$parameters = [ordered] @{
  'Source' =  'src'
  'StartIndex' = 0
  'Length'     = 1
}
```

**Comment by plastikfan** [comment]
Ok thanks for your insight and your point duely noted. The only thing I would ask to counter your argument is, is there a chance that the validation process is being activated too soon? There should not be an issue of parameter order. The validation of individual parameters should only be taking place once all parameters have been bound in. I suspect the way this is working is some kind of iteration which immediately invokes the parameter validator, rather than bind all the parameters first then invoke the validators. In my opinion, the order of parameters should not matter and the only reason they do is because of an internal implementation detail.

Please take this as constructive criticism,

Thanks


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mklement0** [comment]
Yes, the current design is that validation is performed at the moment a given parameter is bound.

I can see how supporting cross-parameter validation as part of the parameter declaration can be beneficial, but changing to what you propose - collect all values first and _then_ validate - would be a substantial change that would require careful design and evaluation for potential backward-compatibility issues.

For instance - and I'm not saying that that's necessarily a reason _not_ to do it - say you have multiple mandatory parameters that the user doesn't bind on invocation, alongside a bound argument that is invalid. The user will go through a series of interactive prompts to supply the mandatory arguments only to be told about the invalid argument _afterwards_.

If you would like to see this change, I encourage you to open a _new_ issue, of type Feature Request/Idea, and make a focused case there. You can then close this issue.

**Comment by plastikfan** [comment]
Ok thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mklement0** [comment]
@plastikfan, in case you want to pursue this further with a proposal:

One conceivable solution that wouldn't change the existing behavior is to introduce a `PostValidateScript` property whose script-block value is only evaluated after _all_ parameters have been bound.

**Comment by plastikfan** [comment]
Ok thanks for that, sounds useful, cheers
