### ISSUE TITLE
PowerShell 7.0.x shows warning about new non LTS versions

### ISSUE THREAD

**Issue by joshcorr** [PowerShell/PowerShell#14452]
## Steps to reproduce

Launch PowerShell 7.0.x version.

## Expected behavior

Launching LTS version of PowerShell should not notify of a new version _until_ there is a new subversion of the current LTS, or a new Major version of LTS for those that are opting to stay on LTS for its supported lifecycle. 

## Actual behavior

![image](https://user-images.githubusercontent.com/13426972/102527146-b27a4280-406a-11eb-80a6-cd71eb03d20b.png)

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
Note: I realize this might not be a bug, but rather a feature request, so please feel free to recategorize.

**Comment by iSazonov** [comment]
@joshcorr Please look a description of the feature https://github.com/PowerShell/PowerShell/pull/11132
Dies POWERSHELL_UPDATECHECK=LTS resolve your issue?

**Comment by joshcorr** [comment]
Didn't realize that this was an option. Read up on it here a bit. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.1

Going to test it out and report back. Should that environment variable be created on install of 7.0.3?

**Comment by iSazonov** [comment]
> Should that environment variable be created on install of 7.0.3?

It is an option. You need to create this manually.

**Comment by joshcorr** [comment]
Thanks for pointing this out @iSazonov. This works for me. I was able to set it as a system wide environment variable (which is what I was hoping for), but imagine one could also set it as a user specific environment variable.
