### ISSUE TITLE
CommandLine property is empty when user has insufficient privileges

### ISSUE THREAD

**Issue by mardukbp** [PowerShell/PowerShell#14456]
## Steps to reproduce

Install [Oracle XE 11g](https://www.oracle.com/database/technologies/xe-prior-releases.html)

```powershell
 (ps -Name TNSLSNR).CommandLine
```

## Expected behavior

```none
C:\oraclexe\app\oracle\product\11.2.0\server\bin\tnslsnr.exe
```

## Actual behavior

```none
No output
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mardukbp** [comment]
It works with PowerShell running as Administrator.

**Comment by powercode** [comment]
Isn't this just an issue of access rights?
None of the windows management tools I know of displays a command line for admin processes when executing under a non-privileged account.
You have to read the memory of the other process to determine the command line, and you don't have the required rights to do that.

**Comment by powercode** [comment]
What was your expectation?

**Comment by mardukbp** [comment]
When I run the Task Manager using `Ctrl-Alt-Del` it shows the command line of the process. Is it running using Admin privileges?

> You have to read the memory of the other process to determine the command line, and you don't have the required rights to do that.

Fair enough. I think this is what PowerShell should tell the user. Then you know what to do. It is not obvious that you are allowed to read the rest of the information about the process, but not the command line.

**Comment by SeeminglyScience** [comment]
> Fair enough. I think this is what PowerShell should tell the user. Then you know what to do. It is not obvious that you are allowed to read the rest of the information about the process, but not the command line.

Hard to do for a property.  PowerShell by design swallows any exceptions that a property getter throws and instead just displays nothing.

**Comment by mardukbp** [comment]
IMHO that is not how exceptions are supposed to be used. An exception should be thrown when something unexpected happens and of course the user should know about it.

PowerShell happily throws up lots of red text due to a syntax error, but it remains silent when an exception occurs?

**Comment by SeeminglyScience** [comment]
Only when thrown by the method that obtains a value from a property.  Note that I'm not necessarily saying it was or wasn't a good idea, but changing it now would break a lot of folks.

**Comment by jborean93** [comment]
Task manager is a special process where it's run as elevated by default without having to prompt through UAC. It's signed by a specific Microsoft cert which allows it to do so and that's why it can see the command line. So you need to be running as admin and the only action I can reliably see here is for the docs to be updated to state that is the case. As @SeeminglyScience says, changing the behaviour now could break existing scripts so not really something that could be done.

**Comment by mardukbp** [comment]
Thank you for the detailed explanation. I wanted to know how the Task Manager does it. 

Yes, I also wanted to suggest updating the docs.

Am 18. Dezember 2020 23:39:38 MEZ schrieb Jordan Borean <notifications@github.com>:
>Task manager is a special process where it's run as elevated by default
>without having to prompt through UAC. It's signed by a specific
>Microsoft cert which allows it to do so and that's why it can see the
>command line. So you need to be running as admin and the only action I
>can reliably see here is for the docs to be updated to state that is
>the case. As @SeeminglyScience says, changing the behaviour now could
>break existing scripts so not really something that could be done.
