### ISSUE TITLE
Support ANSI links in $PSStyle

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#14460]
## Summary of the new feature/enhancement

Here's what I have to do now:

```pwsh
"`e]8;;http://example.com`e`\This is a link`e]8;;`e`\"
```

Gives me:

![image](https://user-images.githubusercontent.com/2644648/102649310-c7fc7480-411d-11eb-9822-eb527b6daac4.png)

## Proposed technical implementation details (optional)

```pwsh
$PSStyle.FormatHyperlink("This is a link", "http://example.com")
```

Returns:

```pwsh
"`e]8;;http://example.com`e`\This is a link`e]8;;`e`\"
```

Keep in mind that this should still work in `ConstrainedLanguage` mode.

**Comment by SteveL-MSFT** [comment]
Should it be `ToHyperlink()`?

**Comment by TylerLeonhardt** [comment]
Maybe... although the `To` implies that the `$PSStyle` object can be turned into a hyperlink (like `DateTime.ToWhateverString()`)... so I don't quite like `To` over `Format`. Maybe even:

```
$PSStyle.Hyperlink(...)
```

is fine. I just added the Format to differenciate between a method and prop.
