### ISSUE TITLE
Success stream not consistent with other streams

### ISSUE THREAD

**Issue by metablaster** [PowerShell/PowerShell#14464]
## Steps to reproduce

```powershell
function Test-Stream
{
	foreach ($i in 1..3)
	{
		Write-Information -MessageData "Performing operation $i" -INFA "Continue"

		[PSCustomObject]@{
			Key1 = "A$i"
			Key2 = "B$i"
		}
	}
}

Test-Stream
```

## Expected behavior

```none
Performing operation 1

Key1 Key2
---- ----
A1   B1
Performing operation 2
A2   B2
Performing operation 3
A3   B3
```

## Actual behavior

```none
Performing operation 1

Performing operation 2
Performing operation 3
Key1 Key2
---- ----
A1   B1
A2   B2
A3   B3
```

## Workaround

One workaround is to use success stream instead of information stream, ex `Write-Output`:

```powershell
function Test-Stream2
{
	foreach ($i in 1..3)
	{
                # Using success stream instead, not good idea!
		Write-Output "Performing operation $i" -INFA "Continue"

		[PSCustomObject]@{
			Key1 = "A$i"
			Key2 = "B$i"
		}
	}
}

Test-Stream2
```

Which results in output shown in `Expected behavior`, but problem is when we need to select property, ex:

```powershell
Test-Stream2 | Select-Object -Property Key1
```

This is even worse because now we not only lost those informational messages, but the output doesn't look right either.

```none
Key1
----

A1

A2

A3
```

This is relatively simple example, since all of the output will still be on same screen, but often enough output can span 20 or more lines or consist of multiple unrelated outputs, and in that case how do you figure out which informational message is referring to which line or output?

You see a bunch on informational message in one place and a bunch of output in another place which looks like there is no connections between them and it kinds of defeats the purpose of non success streams. (at least when it comes to showing them in the console)

Expected behavior would be to print output sequentially instead of separating data and other streams into chunks.

Off course, same behavior happens with other streams: `Write-Warning`, `Write-Error`, `Write-Debug` etc.. but at least error stream will tell us on which line something happened, but that's not the case with other streams.

I'm sure there must be some rationale behind current design, and if so, a switch parameter that would let us have expected behavior would be great, ex:

```powershell
# Wait until success stream is done processing
Write-Information -Message "Sample Operation" -Wait
```

## Additional related unexpected behavior

Please run both functions in same time as follows:

```powershell
Test-Stream
Test-Stream2
```

There is no way this should be expected behavior?

```
Performing operation 1

Performing operation 2
Performing operation 3
Performing operation 1
Performing operation 2
Performing operation 3
Key1 Key2
---- ----
A1   B1
A2   B2
A3   B3
A1   B1
A2   B2
A3   B3
```

At least those 2 function outputs (including streams) should have been separated, because now it looks like there is one output while there are 2.
And if you go ahead and modify my second function `Test-Stream2` then it's going to be even worse because there will be no output at all:

```powershell
# Modification of Test-Stream2, Test-Stream stays the same
function Test-Stream2
{
	foreach ($i in 1..3)
	{
		Write-Information -MessageData "Performing operation $i" -INFA "Continue"

		[PSCustomObject]@{
			UNRELATED_KEY1 = "A$i"
			UNRELATED_KEY2 = "B$i"
		}
	}
}

Test-Stream
Test-Stream2
```

```none
Performing operation 1

Performing operation 2
Performing operation 3
Performing operation 1
Performing operation 2
Performing operation 3
Key1 Key2
---- ----
A1   B1
A2   B2
A3   B3

<output is missing>

```

As you can see, the info messages are telling us both functions run, but second one didn't print anything, in fact it's not clear from this output which one failed and why.

If those informational messages would have been printed then we could tell at which point the output stopped working.

If after all these samples I'm still wrong, please let me know how to achieve what I'm trying to do.

**EDIT:**
Btw, I know we should use hash tables for key/value pairs, but this is just an example, and is reproducable with "non key/value pair" objects, create any `PSCustomObject` you like and the result will be the same.
And `Format-Table` doesn't work for me, it only separates 2 functions, but streams are still unrelated to output.

I should have titled this issue with `PSCustomObject` but I guess it's too late now...

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Please see #4594

**Comment by metablaster** [comment]
Thank you, I searched for this problem for some time but couldn't find this issue.
I'll ask my additional question in the link you posted.
