### ISSUE TITLE
Please don't put msi/binaries on Github

### ISSUE THREAD

**Issue by mikeprior12345** [PowerShell/PowerShell#14466]

**Comment by mikeprior12345** [comment]
it takes hours to download azure-cli/powershell binaries/installers from github pages. Can these downloads be put on proper infrastructure/mirrored sites, without having end users messing about with vpns, to get decent downloads from github to work.

**Comment by iSazonov** [comment]
If you have an issue with GitHub it is better to open a ticket in GitHub support.
