### ISSUE TITLE
Breaking changes made that impacted the International module cmdlets

### ISSUE THREAD

**Issue by luisaranda** [PowerShell/PowerShell#14473]
## Steps to reproduce

Just run some of the cmdlets on the international module

```powershell
Get-WinUserLanguageList
```

```powershell
New-WinUserLanguageList -Language "en-US"

```
## Expected behavior

This command is working on PowerShell 5.1 and on PowerShell 7.0.0

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
> Get-WinUserLanguageList

LanguageTag     : en-US
Autonym         : English (United States)
EnglishName     : English
LocalizedName   : English (United States)
ScriptName      : Latin
InputMethodTips : {0409:00020409}
Spellchecking   : True
Handwriting     : False
```
```powershell
> New-WinUserLanguageList -Language "en-US"

LanguageTag     : en-US
Autonym         : English (United States)
EnglishName     : English
LocalizedName   : English (United States)
ScriptName      : Latin
InputMethodTips : {0409:00000409}
Spellchecking   : True
Handwriting     : False

```

## Actual behavior

```powershell
> Get-WinUserLanguageList
Get-WinUserLanguageList: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
```
```powershell
> New-WinUserLanguageList -Language "en-US"
New-WinUserLanguageList: Cannot marshal 'parameter #1': Invalid managed/unmanaged type combination.
```

## Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Looks like the module uses a p/invoke signature including a `MarshalAs(UnmanagedType.HString)` decoration.  `HString` is the string type for Windows Runtime API's and is no longer supported by the marshaller.

The module would need to be changed to include it's own marshalling logic. This issue should probably be moved to [PowerShell/PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage).

**Comment by danstur** [comment]
@SeeminglyScience  Why is changing the marshalling behavior in a minor release that breaks public APIs (and one that is shipped with every single Windows installation so can't get any more widespread) not a violation of the breaking changes contract? 

Given the speed with which Windows components get updated and the.. great interest in the PowerShellModuleCoverage repository this probably means the International module will be broken from 7.1 onwards.

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience Why is changing the marshalling behavior in a minor release that breaks public APIs (and one that is shipped with every single Windows installation so can't get any more widespread) not a violation of the breaking changes contract?

The breaking change was in .NET itself, which the PS team does not typically consider to be part of their change contract.  That said, breaking changes are sometimes accepted in any release.  The [change contract](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md) does not specify what release types can or cannot have breaking changes, though the PS team is pretty adverse to widely impacting breaking changes in general.

**Comment by slycordinator** [comment]
> Looks like the module uses a p/invoke signature including a `MarshalAs(UnmanagedType.HString)` decoration. `HString` is the string type for Windows Runtime API's and is no longer supported by the marshaller.
> 
> The module would need to be changed to include it's own marshalling logic. This issue should probably be moved to [PowerShell/PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage).

Given that the PowerShellModuleCoverage repository has been archived for several months and the issue raised there was never resolved, it seems like this issue should be reopened.

The International module is still marked as supporting the Core edition, yet in fact is incompatible with it.

**Comment by MartinGC94** [comment]
The module works fine in Windows 11 but not in Windows 10. Considering the solution for a similar issue with the Appx module was to update to Windows 11 I wouldn't expect the PS team to fix this.
