### ISSUE TITLE
powershell core installations are creating desktop symlinks that breaks PSReadLine w. garbage chars

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#14482]
I just installed the latest `PowerShell 7.2.0-preview.2` and yet again the pwsh link that appear on desktop has the classic broken command line garbage, as reported in several places (see #11685 and issues repos within) . 

So I copied the old link I had, from and for pwsh `6.1.1`, and modified it to be exactly the same (as above) as far as its adjustable in the file `properties`. The result is that the **old** link with new paths is working perfectly! Going through some link forensics from [here](https://github.com/libyal/liblnk/issues/47) I noticed that the two symlinks are different by ~40 bytes and by structure. This is only visible by hexedit/hexdump and not even the `lnkinfo.exe` forensic tool. 

So unlike what was previously believed, **this does not seem to be a PSReadLine issue.**

The real question now, is why symlinks are created differently for the installers in the last 1.5 years? 

## Steps to reproduce

* Install latest powershell
* Open desktop terminal shell
* type anything

## Expected behavior

No pwsh terminal cmd line garbage

## Actual behavior

shows broken ctrl characters  
```text
$ s [104m
```

## Environment data

```powershell
$  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
and

```powershell

-----------------------------------------------------------------------
  PowerShell Version    : 7.2.0-preview.2
  OS Name               : Microsoft Windows 8.1 (64-bit)
  OS Version            : 6.3.9600  [2014-08-16 00:50:01]
  OS BuildLabEx         : 9600.19880
  OS HAL                : 6.3.9600.18969
  OS Kernel             : 6.3.9600.18217
  OS UBR                : 19893
  -------------------------------------------------------
  on Host               : xxxx
  as User               : xxxx
  with Privilege        : Normal
  -------------------------------------------------------
  ExecutionPolicy:
      MachinePolicy     : Undefined
      UserPolicy        : Undefined
      Process           : Undefined
      CurrentUser       : Bypass
      LocalMachine      : RemoteSigned

  Firewall:
      Status            : OK

  Console Settings:
      Type              : ConsoleHost
      OutputEncoding    : Unicode (UTF-8)
      Color Capability  : 151
      Registry VT Level : 1
      CodePage (input)  : 437
      CodePage (output) : 437
      Mode (input)      : N/A
      Mode (output)     : N/A
      Buffer Size (W H) : 150 9009
      PSReadLine version: 2.1.0-beta2

```

---

#### Alternatively

Create a new symlink with Powershell using:
```powershell
$ New-Item -ItemType SymbolicLink -Path C:\Users\xxxx\Desktop\pwss -Target "C:\Program Files\PowerShell\7-preview\pwsh.exe"

$ Get-ChildItem C:\Users\xxxx\Desktop\pwss | fl

    Directory: C:\Users\xxxx\Desktop

Name           : pwss
Length         : 0
CreationTime   : 2020-12-22 19:54:21
LastWriteTime  : 2020-12-22 19:54:21
LastAccessTime : 2020-12-22 19:54:21
Mode           : -a---l
LinkType       : SymbolicLink
Target         : {C:\Program Files\PowerShell\7-preview\pwsh.exe}
VersionInfo    : File:             C:\Users\xxxx\Desktop\pwss
                 InternalName:     pwsh.dll
                 OriginalFilename: pwsh.dll
                 FileVersion:      7.2.0.0
                 FileDescription:  pwsh
                 Product:          PowerShell
                 ProductVersion:   7.2.0-preview.2 SHA: 47ef533b2edd5f4cfae5adb9533613f142dc4315
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:         Language Neutral
```
That is also broken. 

The same info for the *old* (modified symlink for pwsh preview ) that is working, is: 

```powershell
 $ Get-ChildItem C:\Users\xxxx\Desktop\pwsh7b.lnk | fl

    Directory: C:\Users\xxxx\Desktop

Name           : pwsh7b.lnk
Length         : 1716
CreationTime   : 2020-12-22 05:33:18
LastWriteTime  : 2020-12-22 05:36:06
LastAccessTime : 2020-12-22 05:33:18
Mode           : -a----
LinkType       :
Target         : {}
VersionInfo    : File:             C:\Users\xxxx\Desktop\pwsh7b.lnk
                 InternalName:
                 OriginalFilename:
                 FileVersion:
                 FileDescription:
                 Product:
                 ProductVersion:
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:
```

Unfortunately, this seem to be a more general problem, as it is not clear why these *symlinks* are looking so different. 

1. Are they even *symlinks*? 
2. Why doesn't the working links show the *type* as a `symlink`? 
3. Why are the link target not reported?

The lnkinfo.exe tool is not able to read the `New-Item` created `SymbolicLink`s... While looking at them in Cygwin, the seem more like a cygwin softlink, reporting: 
```bash
# \ls -lh pwss
lrwxrwxrwx 1 Administrators None 55 Dec 22 19:54 pwss -> /cygdrive/c/Program Files/PowerShell/7-preview/pwsh.exe
```

The same issue occurs, for any new "terminal" type of links. For example the Anaconda created one's have the same issue.

**Comment by jborean93** [comment]
> Are they even symlinks?

I have no idea what the issue is but a `.lnk` file is a shortcut file and not a symbolic link.

**Comment by eabase** [comment]
@jborean93 

Yep, that certainly helps to know. I was sure Win shortcuts was the same as symbolic links. So then I suppose I need to change the title from "`symlink`" to "`shortcut`". Either way, how and where is the shortcut file structure defined?

**Comment by eabase** [comment]
I was [informed](https://github.com/libyal/liblnk/issues/47#issuecomment-749729041) that there is a *metadata* field in the shortcut. 
1. Any idea what this is used for? 
2. Where is it processed and used?

**Comment by eabase** [comment]
I have found a solution to this issue. It has something to do with the parsing of the console color properties within the terminal shortcut, and contained in the *metadata* property store data block. I managed to fix the broken shortcut, by editing the color definitions, resulting in about 4 different byte location changes. The byte [structure of a windows shortcut](https://github.com/libyal/liblnk/blob/main/documentation/Windows%20Shortcut%20File%20(LNK)%20format.asciidoc#6-extra-data) seem to be mostly unknown apart from that researched by some reverse engineering specialists. 

Why editing the colors individually is breaking terminal ANSI character behavior, is still unknown. This is after all a powershell constructed `SymbolicLink`. 

--- 

### The manual solution

1. open the properties of the shortcut that is causing the problem
2. open the properties of a shortcut that is **not** having the problem
3. select the color tab and compare the color boxes **`[]`** of both. 
4. Then try to edit the colors of the broken shortcut. (You'll need to edit first the color codes for the box that is broken, then click on the color box that should be activated. These steps are shown in the pictures below. 

![pwsh_terminal_shortcut_issue1](https://user-images.githubusercontent.com/52289379/102938751-971d9600-44b5-11eb-9f2f-ea8720b5de5b.png)


![pwsh_terminal_shortcut_issue_fix1](https://user-images.githubusercontent.com/52289379/102938692-79e8c780-44b5-11eb-8b50-7169937a5a87.png)

![pwsh_terminal_shortcut_issue_fix2](https://user-images.githubusercontent.com/52289379/102938694-7b19f480-44b5-11eb-99c8-72894043310e.png)

---

The resulting binary diff can be shown to change 4 bytes at these locations of the shortcut. 

![pwsh_terminal_shortcut_issue_fix3](https://user-images.githubusercontent.com/52289379/102937878-ca5f2580-44b3-11eb-82b4-8a1c6dff6b50.png)

The console colors are probably part of this structure:

* https://github.com/libyal/liblnk/blob/main/documentation/Windows%20Shortcut%20File%20(LNK)%20format.asciidoc#621-console-color-flags

This bring up several questions. 
* Where exactly are these colors specified for default created windows *shortcuts* and *SymbolicLinks*?
* How can we access and edit the console color fields when making links and shortcuts.
* Is there a way to automatically fix all terminal shortcuts in one go?
* Are there any registry items controlling these?
* What are, and where are the official MS data structures for shortcuts and symbolic links?  
(So we don't have to spend years and countless hours of hacking and reverse engineering to be able to figure out and solve these problems.)

--- 

This will hopefully resolve a large number of issues related to command line garbage. Such as:

* https://github.com/PowerShell/PowerShell/issues/11685
* https://github.com/PowerShell/PowerShell/issues/13057
* https://github.com/PowerShell/PSReadLine/issues/1110
* https://github.com/PowerShell/PSReadLine/issues/1508
* https://github.com/PowerShell/PSReadLine/issues/1888

**Comment by jborean93** [comment]
> Where exactly are these colors specified for default created windows shortcuts and SymbolicLinks?

The conhost settings are stored in a shortcut as you've seen. The format as you've seen is a binary file but it is definitely documented. You can see the structure of the conhost settings in a shortcut/.lnk at [MS-SHLINK 2.5.1 ConsoleDataBlock](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-shllink/e6b432b4-5a49-4826-9c25-e28695e8dd0c). When it comes to conhost settings there are 4 locations Windows uses:

1. The defaults in conhost itself - you cannot touch these
2. Your user account's specific settings in `HKCU:\Console`
3. A binary specific setting in `HKCU:\Console\<exe path>`
4. Shortcut (.lnk) specific settings

The priority goes from lowest to highest, i.e conhost settings in a shortcut will trump anything else. When changing the settings the `Defaults` option sets option 2, and `Properties` sets option 4 if you opened it through a shortcut (.lnk) or 3 if it's just a normal path/symbolic link.

![image](https://user-images.githubusercontent.com/8462645/102942101-28b1f580-4500-11eb-9a78-c869eab2fff3.png)

Symbolic links have no special meaning here, they would just act like a different path so option 4 does not apply here. When testing that behaviour that's exactly what I see, any changes to the conhost properties are set under `HKCU:\Console\<symlink path>`.

> How can we access and edit the console color fields when making links and shortcuts.

The official way is to open up the application using the shortcut and make the changes through the normal conhost properties. Any changes you make there will be set on the shortcut itself. There's probably third party tools out there that can do this for you and you could even create your own parser yourself if you really wanted to but dealing with binary data in PowerShell isn't the easiest thing to do.

As mentioned above symbolic links are treated the same as a normal path, that is any settings are stored in the registry (option 3) and not in the symbolic link itself.

> Is there a way to automatically fix all terminal shortcuts in one go?

You can clear out any settings under `HKCU:\Console\` so it always uses your default profile's settings. You would still need to deal with shortcut files yourself in another way. Changing the binary data would be quite cumbersome to my recommendation would be to delete and recreate the shortcut yourself (or just not use them at all).

> Are there any registry items controlling these?

Yes, as mentioned above `HKCU:\Console` controls your user's default settings, and `HKCU:\Console\<path>` controls a path specific one.

> What are, and where are the official MS data structures for shortcuts and symbolic links?

Shortcut files are documented under the [MS-SHLLINK](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-shllink/e6b432b4-5a49-4826-9c25-e28695e8dd0c) protocol. They are a shell implementation and sit at a higher layer than where PowerShell sits. There's probably boundless documentation on this format ranging from basic end user setup details all the way to the format of the file.

Symbolic links don't matter at all in this case. They are treated as just another path to the executable and based on the conhost settings they can have their own custom configuration if you so desire. In this case you should not treat symbolic links are any different from a normal path.

Now going forward conhost is considered a legacy product. The replacement from Microsoft is Windows Terminal which has been massively improved from conhost and handles things like Unicode characters and colours whereas conhost is quite limited. When using Windows Terminal then these conhost settings do not apply at all as it has it's own configuration settings.

If you wanted to learn more about conhost settings https://devblogs.microsoft.com/commandline/understanding-windows-console-host-settings/ is a great guide which goes further in depth to what I've mentioned here.

**Comment by eabase** [comment]
Great super good answer. Thank you, that clarifies a lot. 

Since you mention it's legacy and this use case is for W81, I suppose this will never be fixed? (Or is/will windows terminal be available also for W81?)

**Comment by jborean93** [comment]
I doubt it would ever be fixed as it's a fundamental problem with how conhost deals with console output. I don't believe it's anything that PowerShell can really deal with as the problem exists outside of it. Windows Terminal also cannot be backported to Windows 8.1 as it uses APIs only added in a particular Windows 10 build.

**Comment by iSazonov** [comment]
What is exact repro steps? 
1. Install PS 6
2. Run PS with desktop shortcut and check colors - work as expected
3. Save the shortcut
4. Uninstall PS 6 and install PS 7
5. Run PS with desktop shortcut and check colors - one color is broken
6. Replace PS7 shortcut with PS 6 shortcut and replace path to point to PS 7 - colors work as expected.

@eabase Can you confirm?

**Comment by DHowett** [comment]
Speaking as the owner of both conhost and the Windows Terminal (both of which are [open-source](https://github.com/microsoft/terminal)), I'd like to clear up a few misconceptions.

> conhost ... [legacy] ... [not supported]

We're avoiding the term "legacy" for the console host. It is an important and foundational part of Windows, and it is not becoming unsupported. It underpins all console applications, _even inside Windows Terminal._

The product here that is unsupported is Windows 8.1. It predates almost all of our conhost changes, from VT support to word wrap to all of the allocation and memory and performance improvements. _That_ version of Windows will not be receiving any further conhost _or Terminal_ updates¹.

> Symbolic links don't matter at all in this case.

There is a bug in Windows that results in an application launched from a symbolic link being _told_ that it was launched from a shell link (!) whose path _is the symbolic link (!)_ ². This may confuse some applications. This [confuses conhost](https://github.com/microsoft/terminal/issues/7650) in a way that causes it to treat "L" or "F" as a hotkey (globally!) that will give the launched console window focus.

> [some stuff about colors]

PowerShell made a [what should arguably be considered significant] mistake when it shipped and permanently redefined colors 5 and 6, as well as the default foreground/background colors, using its in-box lnk file. This is not normal, and should not be relied on. The color indices are fairly unyielding, and using the "powershell default" colors will cause you trouble literally everywhere else.

> ConsoleDataBlock ... undocumented

[Here's the source](https://github.com/microsoft/terminal/blob/main/src/propslib/ShortcutSerialization.cpp) for the part of conhost that reads the shell link and pulls properties out of it. Our source is our documentation in many regards.

> Escape character garbage ... [hex editing my shortcut file]
> I doubt it would ever be fixed as it's a fundamental problem with how conhost deals with console output.

**Nothing stored in the shortcut file will ever change the VT parsing behavior on Windows 8.1.** That functionality _does not exist_ in conhost.exe as of Windows 8.1. An application such as powershell emitting VT sequences to a console host that doesn't support it is an application bug.

(@jborean93) This is not a "fundamental problem," it is a feature that was implemented in the _seven years_ since Windows 8.1 shipped.

¹ Rumor has it that a build of conhost from our open-source repository (OpenConsole, "Host.EXE") _will run on Windows 8.1._ YMMV. NO WARRANTY, EXPRESS OR IMPLIED. If it runs, it will support all modern console features from Windows 10.

² This will result in the application opening an executable _as a lnk file_ and attempting to parse it. Not awesome.

**Comment by jborean93** [comment]
Thanks for clarifying @DHowett!

**Comment by eabase** [comment]
@iSazonov  Yes, exactly. (But don't need to uninstall PS6.)

**Comment by eabase** [comment]
@DHowett 
Thank you Dustin for such a detailed and interesting answer.

> Rumor has it that a build of conhost from our open-source repository (OpenConsole, "Host.EXE") will run on Windows 8.1.

I love rumor's and would be happy to test, but how is that done? Just replacing `conhost.exe` with `Host.EXE`?

**Comment by DHowett** [comment]
@eabase yes. Make sure you use a Release build, otherwise the performance will be quite unpleasant.

**Comment by eabase** [comment]
<details>

<summary>This is really OT</summary>

I couldn't find any statically pre-built exe's. Extracted Windows Terminal appx and ran terminals, only to get hit with a missing DLL
**`api-ms-win-core-wow-64-l1-1-1.dll`**

What is special about that one?
Can I throw in one found on a different system?

</details>
