### ISSUE TITLE
Checkpoint computer command not recognised

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [PowerShell/PowerShell#14487]
## Steps to reproduce

Input the code below into the PowerShell window
`Checkpoint-Computer -Description "TWC-RestorePoint" -RestorePointType MODIFY_SETTINGS`

## Expected behavior

Create a System Restore point

## Actual behavior

![image](https://user-images.githubusercontent.com/51249734/102988313-dd333200-4567-11eb-8b0c-f052a6c2ebca.png)

## Environment data

PowerShell 7.2.0-preview.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Program Files\PowerShell\7-preview> Checkpoint-Computer -Description "TWC-RestorePoint" -RestorePointType MODIFY_SETTINGS
Checkpoint-Computer: The term 'Checkpoint-Computer' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Program Files\PowerShell\7-preview>

**Comment by jdhitsolutions** [comment]
This command works in PowerShell 7.2.1 for me.

**Comment by iSazonov** [comment]
> This command works in PowerShell 7.2.1 for me.

I guess in WinCompat :-)

We could try to restore the cmdlet https://github.com/PowerShell/PowerShell/issues/11732#issuecomment-580877408

**Comment by gpion** [comment]
still not found in PWSH 7.4.3
```
PS7  [Admin] ${USERPROFILE}\ > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS7  [Admin] ${USERPROFILE}\ > Checkpoint-Computer -Description "Snapshot" -Verbose -RestorePointType MODIFY_SETTINGS
Checkpoint-Computer: The term 'Checkpoint-Computer' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
