### ISSUE TITLE
Attributes implemented as PS custom classes are only recognized with the "Attributes" suffix

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14499]
Note that regular .NET attribute types such as `[System.ComponentModel.ReadOnlyAttribute]` are _not_ affected (that is,  `[System.ComponentModel.ReadOnly($true)]` works as shorthand for `    [System.ComponentModel.ReadOnlyAttribute($true)]`)

## Steps to reproduce

```powershell
class MarkedAttribute : System.Attribute { }

# Note: iex (Invoke-Expression) is required, because [MarkedAttribute] must already be defined
#           by the time [Person1] and [Person2] are parsed.
@'
  class Person1 {
    [MarkedAttribute()]
    [string]$Name
  }
'@, @'
  class Person2 {
    [Marked()]  # This should be equivalent to [MarkedAttribute()], but currently isn't.
    [string]$Name
  }
'@ | % { { iex $_ } | Should -Not -Throw }
```

## Expected behavior

Both tests should succeed.

## Actual behavior

The second test fails, because `[Marked]` is unexpectedly not recognized as shorthand for `[MarkedAttribute]`:

```none
... Cannot find the type for custom attribute 'Marked' ...
```

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by MatejKafka** [comment]
@kilasuit Please reopen, this is still an issue in the latest preview.

This also happens with function parameter attributes, but depends on the scope of the caller:

```pwsh
class TestCompleterAttribute : System.Management.Automation.ArgumentCompletionsAttribute {
    TestCompleterAttribute() : base(1, 2, 3) {}
}

function Test-Fn([TestCompleter()]$X) {
    $X
}

function Test-Fn2($X) {
    Test-Fn $X
}
```

If you put this snippet into a .psm1 module, import it, and call `Test-Fn`, you will get the following exception: `InvalidOperation: Cannot find the type for custom attribute 'TestCompleter'. Make sure that the assembly that contains this type is loaded.` However, if you first call `Test-Fn2`, the call magically works, and from that point on, directly calling `Test-Fn` will work as well:

```pwsh
Import-Module .\Test.psm1

Test-Fn # InvalidOperation: Cannot find the type ...
Test-Fn # InvalidOperation: Cannot find the type ...

Test-Fn2 # OK
Test-Fn # now also OK
```

With the full attribute name, everything works as expected.
