### ISSUE TITLE
Tracking FileSystem provider performance issues

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#14497]
1. The IsPathRoot() method does double check for UNC
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L5026-L5047
and could be replaced with more short and fast code. Proposal from @mklement0 https://github.com/PowerShell/PowerShell/issues/14497#issuecomment-751356734

Also we need to review GetFileSystemItem(string path, ref bool isContainer, bool showHidden) - there is a root check and maybe a bug (no UNC share check)
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1426-L1430

2. PR #14469 Reduce aggressive correcting casing of file system paths
On Windows we do case normalizations even if results are not used.

3. No need to allocate FileInfo and extra strings in IsSameWindowsVolume():
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L6141-L6147
We can use `GetDirectoryName(ReadOnlySpan<char> path)`. Also we should use Ordinal comparison.

4. EnsureDriveIsRooted() method does extra path.IndexOf(':') - we can simply check last char
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L5709-L5727

5. We need to review semantic of IsValidPath() method. If it is exactly about path validity the method could be simplified but we need to measure a performance. In common case it is impossible to validate path by parsing but only by opening.
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1192-L1246

6. Statistic shows:
```powershell
dir -Recurse 'C:\Program Files (x86)\' | Select -ExpandProperty Mode | Sort-Object  | Group-Object -NoElement

Count Name
----- ----
    1 -----
    3 --r--
44263 -a---
    6 -ar--
 8136 d----
    3 d---s
    2 d-r--
 1044 la---
```
and we could add "la---" as a static element in
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L2024-L2040
```c#
                if (!isLink)
                {
                    // special casing for the common cases - no allocations
                    switch (fileAttributes)
                    {
                        case FileAttributes.Archive:
                            return "-a---";
                        case FileAttributes.Directory:
                            return "d----";
                        case FileAttributes.Normal:
                            return "-----";
                        case FileAttributes.Directory | FileAttributes.ReadOnly:
                            return "d-r--";
                        case FileAttributes.Archive | FileAttributes.ReadOnly:
                            return "-ar--";
                    }
                }
                else if (fileAttributes == FileAttributes.ReadOnly)
                {
                    return "la---";
                }

           ...
```

7. Remove double check ItemExists();
https://github.com/PowerShell/PowerShell/blob/281b437a65360ae869d40f3766a1f2bbba786e5e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L6105-L6112

**Comment by mklement0** [comment]
Thanks for tackling this, @iSazonov.

Note that `[io.path]::IsPathRooted()` also returns true for paths of any depth, as long as they are rooted; e.g., `[io.path]::IsPathRooted("\Windows")` returns `$true` too.

Since `[io.path]::GetPathRoot()`  also works with UNC paths, the one existing check should be enough in principle:

```csharp
bool isDriveOrUncRoot = string.Equals(path, Path.GetPathRoot(path), StringComparison.OrdinalIgnoreCase)
```

The only edge case is that while paths such as `C:\`, `\`, and `C:` are all returned as-is by `[io.path]::GetPathRoot()` (and therefore make the test return `$true`), `\\foo\bar\` - note the trailing `\` - is returned as `\\foo\bar` (no trailing `\`), so it wouldn't be recognized as a (UNC) root path.

**Comment by iSazonov** [comment]
@mklement0 Thanks for help!

> `\\foo\bar\` - note the trailing `\` - is returned as `\\foo\bar`

We need this and the fact complicate our check. Also [io.path]::GetPathRoot("\\q\") returns `\\q\`.
It seems it is a question for .Net team how can we check if a path is a root.

**Comment by mklement0** [comment]
Interesting, @iSazonov: For me, both in 7.1 and v7.2.0-preview.2 (on Windows), `[io.path]::GetPathRoot("\\q")` returns `\\q`, not `\\q\` - but `[io.path]::GetPathRoot("\\q\")` does return `\\q\` - did you mean the latter?

Note that `[io.path]::GetPathRoot()` performs no syntax check on its input path, and `\\q` is formally not a valid path - not sure if our `IsPathRoot()` needs to detect or where else such a check may be performed.

Leaving paths with invalid syntax aside, I think the following would work (assuming only paths with _native_ drive letters are use on Windows):

```csharp
string rootPath = Path.GetPathRoot(path);
bool isDriveOrUncRoot = 
  ! path.EndsWith(':')
  &&
  string.Equals(path, rootPath, StringComparison.OrdinalIgnoreCase) 
  ||
  string.Equals(path.Substring(0, path.Length-1), rootPath, StringComparison.OrdinalIgnoreCase) && 
    path.Length == 1 + rootPath.Length && (path.EndsWith('\\') || path.EndsWith('/'));
```

Note, that the above handles another edge case: a path such as `c:` is returned as-is by `[io.path]::GetPathRoot()`, but it does _not_ refer to the drive's root directory, but to _whatever the current directory is_ on that drive.

**Comment by iSazonov** [comment]
> does return `\\q\` - did you mean the latter?

Yes, GitHub hide the slash.

>  string.Equals(path, rootPath, StringComparison.OrdinalIgnoreCase) 

Why should we compare if GetPathRoot() returns a substring?

**Comment by mklement0** [comment]
> Why should we compare if GetPathRoot() returns a substring?

Because the intent of the PS method, judging by the doc comments and the implementation is to see if the input path refers to a _root directory_, not to see if the path _starts_ from a root directly.

Thus, the idea is to extract just the root-directory portion of the path and to then see if that is the _entire_ path.

**Comment by iSazonov** [comment]
I mean it is enough to check lengths of original path and Path.GetPathRoot(path) (have a workaround for UNC share paths - really remove last slash at the first step).

**Comment by mklement0** [comment]
Good point, @iSazonov - no explicit comparison needed; the following could work:

```csharp
int rootPathLength;
bool isDriveOrUncRoot  = (rootPathLength = Path.GetPathRoot(path)?.Length ?? 0) > 0 && (
  path.Length == rootPathLength && path[^1] != ':'  // rule out, e.g., "C:"
  ||
  path.Length == 1 + rootPathLength && (path[^1] == '\\' || path[^1] == '/') // ignore trailing sep. in UNC root path
);
```

**Comment by iSazonov** [comment]
@mklement0 Thanks! Have you an interest to pull PR?

**Comment by mklement0** [comment]
Thanks, @iSazonov, but my hope is that someone else will pick this up.
