### ISSUE TITLE
Write-Verbose / Write-Warning / Write-Debug colors linger after execution

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14506]
Note: This is a regression from 7.1. It affects all terminals on all platforms.

Executing a `Write-Verbose` / `Write-Warning` / `Write-Debug` command that produces visible - and therefore colored - output makes the colors linger and affects subsequent output (that doesn't explicitly control coloring)

**Update**: The problem is connected to the `PSAnsiRendering` experimental feature and does _not_ occur while it is disabled.

## Steps to reproduce

```powershell
Write-Warning foo; 'bar'
```

## Expected behavior

`foo` should print in yellow, `bar` in the default colors.

## Actual behavior

Both `foo` and `bar` print in yellow, and the subsequent prompt string prints in yellow too.

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by ThomasNieto** [comment]
Strange, I'm not able to reproduce with 7.1 or 7.2 preview 2.

![image](https://user-images.githubusercontent.com/38873752/103230613-7d3be300-48fb-11eb-9156-81289f4e4731.png)

**Comment by reaching-for-libra** [comment]
I have seen the same behavior - OS: Microsoft Windows 10.0.16299

**Comment by reaching-for-libra** [comment]
Note that executing "$PSStyle.Reset" does reset back to the expected coloring.

**Comment by mklement0** [comment]
Thanks for checking, @ThomasNieto and @reaching-for-libra  - strange indeed.
I double-checked without profile and loading after unloading `PSReadLine`, and I still see the problem.

![image](https://user-images.githubusercontent.com/588825/103231124-102d4b00-4905-11eb-9df0-d6ee3a967d26.png)

I wouldn't expect the specific Windows 10 version to make a difference, and, as stated, I do see it in all terminal applications on all platforms.

@ThomasNieto, could there be something in your `$PROFILE` that happens to hide the problem?

**Comment by SeeminglyScience** [comment]
> Strange, I'm not able to reproduce with 7.1 or 7.2 preview 2.

Make sure you have the experimental feature enabled.  I did the same thing the other day

**Comment by mklement0** [comment]
That's it, @SeeminglyScience, thanks: the symptom only surfaces with experimental feature `PSAnsiRendering` enabled.
After executing `Disable-ExperimentalFeature PSAnsiRendering` and starting a new session, the problem goes away.

**Comment by ThomasNieto** [comment]
> > Strange, I'm not able to reproduce with 7.1 or 7.2 preview 2.
> 
> Make sure you have the experimental feature enabled. I did the same thing the other day. (Speaking of which, FYI @rjmholt. I forget what thread I said that in.)

Enabling `PSAnsiRendering` caused to issue to occur.

**Comment by ImportTaste** [comment]
It seems PSAnsiRendering is changing $host.UI.RawUI.ForegroundColor instead of using colors defined in $host.PrivateData.

The colors also seem to be hard-coded, so if you use `$host.PrivateData.VerboseForegroundColor = 'Cyan'` ahead of time, the output is still going to be yellow.

**Comment by SteveL-MSFT** [comment]
This was fixed already in `PSAnsiRendering` experimental feature.  By design, it doesn't use `$host.PrivateData` settings as `[ConsoleColor]` is much more limited than ANSI.  The styles are defined in `$PSStyle.Formatting`
