### ISSUE TITLE
Make Get-Content recognize XML file encodings

### ISSUE THREAD

**Issue by Tomalak** [PowerShell/PowerShell#14508]
## Issue

The commonly-used pattern for reading XML files goes like this:

```ps
$doc = [xml](Get-Content xyz.xml)
```

It's fast, convenient, ubiquitous and ... wrong.

It does not pay attention to XML file encodings and happily (and silently) mangles data from XML files that do not happen to be in the expected encoding (i.e. UTF-8), or in an encoding that mandates a BOM (i.e. UTF-16 and friends). See #14505 and #14404 for more in-depth discussion.

Sadly this usage pattern is not going anywhere. Far too many examples all over the Internet show wrong usage, far too few people are aware of - or care about - how XML implements encodings.

The ideal solution would be to teach people how to do it correctly, the pragmatic solution is to make the pattern above do the right thing.

## Proposal

Make `Get-Content` recognize XML files and switch file encodings on-the-fly. This is what XML parsers do as well.

It's easy, since the first line of the file will contain the XML declaration `<?xml version="..." encoding="..."?>` which has the necessary encoding information.

In the absence of an XML declaration, assuming UTF-8, i.e. exactly what `Get-Content` normally does, is correct. 

## Proposed technical implementation details

An implementation for `Get-Content` encoding sniffing should go like this

- if there's a BOM, use that (that's already happening)
- otherwise, if there is an `-Encoding` parameter, use that
- otherwise, look at the first couple of bytes of the file as ASCII
  - if it starts with an XML declaration `<?xml`, parse out the `encoding="..."` value
    - if it's a recognized encoding name, switch the file stream to a new encoding for the rest of the file
    - otherwise, default to UTF-8
  - otherwise, assume plain text in UTF-8 (that's already happening)
  - not sure if viable, but nice to have: In the "UTF-8 assumed" case, if there are decode errors, rewind stream & fall back to the system's default ANSI encoding (might already happen, I haven't checked)

Actual implementation details can be derived from the way `System.Xml.XmlDocument` implements it in its `.Load()` method, I'm sure there are some corner cases.

## Benefits

- It would make things transparently correct for existing scripts without breaking any of them.
- It would make things transparently correct for anyone copying code off of the Internet/who's not deep enough into the details of how XML implements file encodings.
- All the thousands of bad examples from the Internet would be fine on one sweep.
- It would help people who naively (or for performance reasons) process XML data line-wise as plain text.

**Comment by mklement0** [comment]
Thanks for writing this up; a couple of suggestions:

> if there is an `-Encoding` parameter, use that

To be consistent with current behavior, `-Encoding` should only be respected _if there's no BOM_. 
For instance, currently, if you have a UTF-8-with-BOM file and try to read it with `Get-Content -Encoding utf32`, the `-Encoding` argument is ignored.

> not sure if viable, but nice to have: if there are decode errors, rewind stream & assume system default ANSI encoding as fallback (might already happen, I haven't checked)

Given that we don't do that currently, I don't think we need to worry about this case (and if we did, ANSI would be an awkward, platform-specific fallback; that PowerShell Core still doesn't support `-Encoding Ansi` (which in _Windows PowerShell_ is `-Encoding Default`, and the default for `Get-Content` / `Set-Content` as well as source code) is a separate story - see #6562).

`Get-Content` simply uses `�` (REPLACEMENT CHARACTER, [`U+FFFD`](http://www.fileformat.info/info/unicode/char/fffd)) to replace invalid-as-UTF-8 byte sequences (which would happen with a by-definition BOM-less ANSI-encoded file with non-ASCII chars.), and I don't think doing something special for XML files is called for (as you point out, the proposed accommodation is motivated by pragmatism, not conceptual purity).

Separately, however, we may want to think about generically introducing a switch such as `-Strict` on `Get-Content` and `Set-Content` (possibly others, but for comprehensive coverage you'd either need a for-file-processing-cmdlets-only common parameter or a preference variable, which comes with dynamic-scoping challenges) that _errors out_ on decoding/encoding errors.

**Comment by Tomalak** [comment]
@mklement0 Amended the checklist accordingly.

The "ANSI fallback" is certainly up for debate. I've had my share of situations where trying UTF-8 and falling back to Windows-1252 was a successful strategy, but I admit this can hardly be generalized.

When `�` appears in the output, it pretty much means that the file is a single-byte encoding wrongly interpreted as UTF-8, and optimistically falling back to the system default encoding has a good chance of producing the right result, pragmatically speaking.

The bigger question is if baking such a hidden assumption into the standard behavior of `Get-Content`, or if leaving errors in the output (or throwing exceptions) and letting the user explicitly nail it down is better.

Personally, if `Get-Content` silently fixes it for me, I'm happier than when it silently breaks it for me.

**Comment by mklement0** [comment]
Interesting questions, @Tomalak, but if we wanted to make changes in this area, they wouldn't be specific to the XML accommodation, so it would again call for a _new_ proposal - assuming you feel strongly enough about this.

A few more thoughts, but we should probably continue any discussion in a new proposal, should one be created:

* A simple test for the presence of `�` when using the default encoding is ``Select-String -Quiet "`u{fffd}"  file.txt``

* As stated, having an opt-in to explicitly _fail_ on encountering decoding errors might be helpful - not least because a properly decoded file could contain `�` as an actual character, in which case the `Select-String` test would yield a false positive.

* While falling back to ANSI on Windows is probably helpful more often than not, such magic can also lead to subtle failures, such as when a Windows-1251-encoded file is read on a system where Windows-1252 is the active ANSI code page. By contrast, `�` has the advantage of being a single, visually conspicuous indicator that something went wrong.

**Comment by Tomalak** [comment]
@mklement0 Yeah, I don't feel strongly enough about this to make yet another proposal out of it. It's a messy topic and there is no way my assumptions aren't biased. The more complex this gets, the higher the chance to introduce unpredictable behavior or new bugs.

**Comment by jdhitsolutions** [comment]
The Cmdlet Working Group recognizes the challenge in this issue. However, after deliberation and testing, feel that the best course of action is a change to the `[xml]` type accelerator to introduce a new `Load()` method, which could be used to handle the XML document type. No changes would be made to `Get-Content` and this would not affect `[xml.document]`, only the `[xml]` type accelerator.

**Comment by iSazonov** [comment]
@jdhitsolutions Should we open new issue for `[xml]` type accelerator with more clear specifications what we should add?

**Comment by mklement0** [comment]
A type accelerator is merely a short type-name alias for convenience; `[xml]` is short for `[System.Xml.XmlDocument]` - in other words: the two are - and should remain - equivalent.

Said type already has a `.Load()` method, and _avoiding its awkwardness in PowerShell_:
* `$x = [xml]::new(); $x.Load((Convert-Path 'file.xml'))` (note the need to resolve to a _full path_) 
*  vs. making the existing (PowerShell-idiomatic and convenient) widespread practice, `[xml] (Get-Content file.xml)`, _robust_ 

is the motivation for this feature request.

**Comment by iSazonov** [comment]
From the WG conclusion it is not clear what is new suggestion to resolve the issue.
