### ISSUE TITLE
AllowPrerelease parameter error

### ISSUE THREAD

**Issue by VictorPro007** [PowerShell/PowerShell#14502]
Hello. I was installing Git for PowerShell (https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-PowerShell), and when I put `Install-Module posh-git -Scope CurrentUser -AllowPrerelease -Force` in the console, it log me that the paramater `AllowPrerelease ` doesn't exist. My PowerShell version is:  _5.1.18362.1171_ and I have the Desktop version. Can someone help me, please?

**Comment by iSazonov** [comment]
> My PowerShell version is: _5.1.18362.1171_

You should use latest PowerShell 7.1.

Notice, Windows PowerShell is frozen - all new feature appear only in PowerShell 7+.

**Comment by mklement0** [comment]
Apropos of a [recent discussion](https://github.com/PowerShell/PowerShell/issues/14474#issuecomment-749145682): /cc @SeeminglyScience, @alexandair, @SteveL-MSFT.
