### ISSUE TITLE
create easily new operators 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14512]
in pwsh we can expand the language with several form:

we can create cmdlet/function ( binary - script )
we can create module (binary-script-dynamic...)
we can create new keyword ( ast )
we can create dynamic parameter ( class - DYNAMICKEYWORD keyword)

but we can't create operator easily and only contaiement operator is allowed to create, 
what if we can create operators in runtime easily ? it's possible ? maybe with a schema 'json' or 'xml' or 'hash' and then compile this schema...for example:

```
PS > cat code.ps1

#Requires -configuration MyNewOperator

$a,$b = (ls) -all ($_.PSISContainer)
$a # 10 all directory 
$b # $true 
```

**Comment by iSazonov** [comment]
Operators make no sense without a model/abstraction. @rjmholt did an initial work to support DSLs but without a progress. Perhaps he could share thoughts about this.

**Comment by daxian-dbw** [comment]
This proposal did not raise enough interests, so it will be closed for housekeeping purpose.
