### ISSUE TITLE
Assigning property values with the .ForEach() array method fails if the input object is a scalar

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14527]
## Steps to reproduce

```powershell
$o = [pscustomobject] @{ one = 1 }

# OK: If the input object is forced to be an array, assigning works as expected.
@($o).ForEach('one', 2); $o.one | Should -Be 2

# !! BROKEN: If the input object happens to be a *scalar*, the assignment doesn't work, and behaves 
# !! like *retrieval* instead:
$o.ForEach('one', 3); $o.one | Should -Be 3
```

## Expected behavior

Both tests should pass.
## Actual behavior

The 2nd test fails, because the scalar input object unexpectedly simply _gets_ the existing `.one` value instead of _settings_ the new value, `3`:

```powershell
2  # existing value is unexpectedly output
Expected 3, but got 2.    # Pester error message
```

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by scriptingstudio** [comment]
@mklement0 because .foreach as well as .where apply to arrays by design

**Comment by mklement0** [comment]
@scriptingstudio: No, both `.ForEach()` and `.Where()` are designed to work on scalars too, in the interest of unified treatment of scalars and collections - just like `(42).Count` reports `1` and  `(42)[0]` reports `42`,  for instance. 

This is evidenced by the _equivalent_ operation working just fine:

```powershell
PS> $o = [pscustomobject] @{ one = 1 }; $o.ForEach({ $_.one = 2 }); $o

one
---
  2
```

**Comment by scriptingstudio** [comment]
But there is incompatibility between PS5 and PS7.
### PS5
```
$a=12
$a.foreach{$_}
12
#
$a = [pscustomobject]@{v=12}
$a.foreach{$_}
Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'ForEach
'.
At line:1 char:1
+ $a.foreach{$_}
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ForEach:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

### PS7 
```
$a = [pscustomobject]@{v=12}
$a.foreach{$_}

 v
 -
12
```

I drives me crasy because I always should remember about that and use everywhere `@(var).foreach{}`

**Comment by mklement0** [comment]
Interesting, @scriptingstudio - I didn't know about the v5.1 behavior.

As you demonstrate, it makes much more sense to make the methods also work on scalars, given that you don't always know  _situationally_ whether you're dealing with a scalar or a collection, and having to remember to use `@()` is cumbersome - and, with preexisting arrays, inefficient.

_Mostly_, the two methods already do work on scalars in PS Core (another example: `$o = [pscustomobject] @{ one = 1 }; $o.Where({ $_.one -eq 1 })`), except for the one case in the OP, which should be considered a bug and therefore fixed (the symptom alone - behaving like a _get_ when _set_ is requested - indicates that something's wrong).

**Comment by scriptingstudio** [comment]
It is not simply cumbersome and inefficient, it is crazy. Because `$var.count` and `@($var).count` sometimes give different results and I don't know in advance what type of object I'll get to work with.

**Comment by mklement0** [comment]
Good point, @scriptingstudio: It only seems to affect scalars of _certain_ types, making it clear that even in Windows PowerShell the behavior is a _bug_ (in the case of `.Count`, `$null` is returned for the affected types, though, curiously, _indexing_ (e.g. `$o = [pscustomobject] @{ one = 1 }; $o[0]`) does work.

I haven't tried to find them all, but notable types that are affected in Windows PowerShell are `[pscustomobject]` and `[xml]`; most others - including custom PowerShell classes - seem to be fine; e.g., `$itm = Get-Item /; $itm.ForEach('Name')` works just fine.

(As an aside: with respect to _indexing_ the problem may be different, depending on type: if a _type-native_ indexer is present, it preempts the intrinsic indexing, even if it isn't `[int]`-typed, which notably happens with `[xml]` - see #11189.)

I hope it is clear by now that:

* the symptom described in the OP is a bug that should be fixed.
* that Windows PowerShell is plagued by more serious manifestations of this bug.
