### ISSUE TITLE
Feature Request: adopt `/` not `\\` to path expression syntax

### ISSUE THREAD

**Issue by Banyc** [PowerShell/PowerShell#14523]
## Summary of the new feature/enhancement

It will be preferred that the suggesting path for `cd` by tapping `tab` could be `/`-style rather than `\\`-style. 

## Proposed technical implementation details (optional)

`/` is considered as non-ambiguous when it comes to path expression. Even [the syntax](https://www.w3schools.com/xml/xpath_syntax.asp) for `XPath` is also `/`-based, not to mention Linux.

Every time I copy the path to the C# as a `const string`, I have to manually replace all `\\`. If it is Linux that `PowerShell` hates, I will be cool with that. But when `C#` also considers `\\` as an escape sign, then it is inconsistent that `PowerShell`, a C# based cross-platform APP, still sticks to `\\`.

**Comment by p0W3RH311** [comment]
i think this feature is preferded to add as option configuration in psreadline

**Comment by mklement0** [comment]
Please see #10509 for an ongoing discussion.
