### ISSUE TITLE
Unexpected file

### ISSUE THREAD

**Issue by VictorPro007** [PowerShell/PowerShell#14529]
Hello. I was installing Powershell 7.1(https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1#installing-the-msi-package), and when I put this command: `msiexec.exe /package PowerShell-7.1.0-win-x64.msi /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1`, it only created a new file named Windows.old, but there's nothing in it. What I should I do?

**Comment by iSazonov** [comment]
It looks like a local issue on your system. We can track nothing in the repository. It is better to use other resources to get help like forums.
