### ISSUE TITLE
Feature Request: cp -Force on MacOS results in /bin/cp: illegal option -- F

### ISSUE THREAD

**Issue by codingyourlife** [PowerShell/PowerShell#14520]
## Summary of the new feature/enhancement

'As a user of macOS Big Sur with latest Powershell 7.1. I want to run the cp command with force override of target file in the same syntax as on windows so that I can use the script cross platform

## Proposed technical implementation details (optional)

`pwsh -c "cp -Force ./source.txt ./targetThatExists.txt"`
results in
`/bin/cp: illegal option -- F`

Notice that the command does not contain F but -Force.
The -Force option is available on Windows but not on macOS and my identical script failed.

Workaround:
Remove-Item ./targetThatExists.txt -ErrorAction Ignore
-> then use cp command without -Force option

<img width="593" alt="image" src="https://user-images.githubusercontent.com/10122382/103385921-c7d87d80-4afc-11eb-9f7c-0869d2b2838b.png">

**Comment by jborean93** [comment]
`cp` on Windows is an alias for Copy-Item which is why `-Force` works. On non-Windows hosts it's calling the native binary `cp` at `/bin/cp` which isn't related to PowerShell. If you want something that works on both Windows and other platforms don't use `cp` and instead use `Copy-Item` so you are calling the PowerShell cmdlet directly.

**Comment by codingyourlife** [comment]
Thanks @jborean93 
But why can't it call the native /bin/cp and rewrite the -Force option the way it should work? Can't powershell be considered a wrapper for native commands?

**Comment by jborean93** [comment]
> But why can't it call the native /bin/cp and rewrite the -Force option the way it should work

You now have to maintain a static list of all binaries and options to map to which would be ungodly difficult to maintain. Even then you can't guarantee that `cp` will always accept `-f`.

> Can't powershell be considered a wrapper for native commands?

Depends on how you define a wrapper. PowerShell is a shell which can be used to call native commands. It's not always wrapping those commands, i.e. `Copy-Item` does not call `cp` internally but uses a bunch of syscalls through .NET.

So if you want something that is platform agnostic, use the PowerShell cmdlets (`Copy-Item`) to copy the file.
