### ISSUE TITLE
Feature Request: Add a Set-Cursor command to reposition the terminal cursor

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#14521]
## Summary of the new feature/enhancement

Setting the terminal cursor position in PowerShell is easy, but results in a significant amount of duplicate code. Hence, I propose that we add a helper function to PowerShell that will reposition the cursor in two-dimensional space.

## Proposed technical implementation details (optional)

1. The function name would be `Set-Cursor`.
2. This function accepts two integer parameters, corresponding to the `[int] x, [int] y` constructor of the `[System.Management.Automation.Host.Coordinates]` class
3. The function constructs an instance of the `[Coordinates]` class
4. The function sets the `CursorPosition` property of the `$Host.UI.RawUI` interface to the `[Coordinates]` instance

```
function Set-Cursor {
    [CmdletBinding()]
    param (
        [int] $x = 0,
        [int] $y = 0
    )
    $Host.UI.RawUI.CursorPosition = [System.Management.Automation.Host.Coordinates]::new($x, $y)
}
```

### Example

```
# Set cursor coordinates to 5,5
Set-Cursor -x 5 -y 5
```

**Comment by SeeminglyScience** [comment]
FYI you can also do this:

```powershell
$Host.UI.RawUI.CursorPosition = @{ X = 0; Y = 0 }
```

**Comment by DHowett** [comment]
It doesn't seem like this would warrant _an entire fully-supported cmdlet that will be required, for compatibility reasons, to ship with all future versions of PowerShell._
