### ISSUE TITLE
My bug report: output color of Receive-job loses

### ISSUE THREAD

**Issue by Banyc** [PowerShell/PowerShell#14524]
## Steps to reproduce

1. Build a dotnet project with template blazorserver or anything that has colored output.

1. Run the following:

```powershell
start-job {dotnet run}
receive-job -wait 1
```

## Expected behavior

The output should be colorful.

## Actual behavior

The output is all of the white chars.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Note that many utilities, notably those with a Unix heritage, _conditionally_ apply coloring (via VT / ANSI escape sequences) to their output, namely based on whether their stdout stream is connected to a _terminal_ (DO color) or not (do NOT color).

Background jobs aren't directly connected to a terminal, which probably explains why you're not seeing colored output.

At least some GNU utilities (preinstalled on Linux platforms) allow you to _unconditionally_ request colored output, 
using `--color=always`, such as  `ls` and `grep`.
