### ISSUE TITLE
Feature Request: Create a quick and easy way to restart the current powershell session preserving cwd.

### ISSUE THREAD

**Issue by plastikfan** [PowerShell/PowerShell#14536]
## Summary of the new feature/enhancement

This is to help aleviate the problems of working with classes, particularly when developing modules. Currently, the problem we face is that once a class has been defined and is present in a session, it can't be modified. Obviously, the real underlying problem that should be fixed is this write once only nature of class definitions, but I guess if it was easy to fix, then you'd have done that already. Whilst this is not fixed, can we please have a mechanism for working around this issue.

We need a quick and easy way to restart the current session without closing down the host window (the console app, or visual studio code etc). And to make things easier for the user, the current working directory should be preserved so they should not have to manually navigate to the directory they were in, in the old session.

## Proposed technical implementation details (optional)

perhaps a new function restart-session (argh, restart is not an approved verb, so perhaps redo-session, although that sounds like a misnomer), possibly with an alias of 'res' or 'ress'.

- redo-session should capture the current directory, kill the current session, then invoke set-location with the previously cached directory
- 
- The key requirement though is that no new window should appear, that would be too brutual. Just restart the session.

I have found another way to partially achieve what I'm looking for and that would be to use this command:

> Invoke-Command { & "pwsh" } -NoNewScope

There are a couple of problems with this approach
1) it does not preserve the current working directory
2) it does not close down the previous session, so as a developer repeated running that command to update a class definition would end up with a lot of stacked up powershell sessions

**Comment by doctordns** [comment]
Another related scenario is when I am at the console, have run many commands  to confugurebl an environment, only to find that I needed an elevated console.  I know that SUDO would be a solution, but that won't happen. Can we have a Restart-PSSession -AsAdminstrator ??

**Comment by SeeminglyScience** [comment]
The workflow I usually have is:

1. `pwsh`
2. `cd ./Project`
3. `pwsh`
4. `# do my debugging/testing until I need to reload`
5. `exit`
6. Go to step 3

> > Invoke-Command { & "pwsh" } -NoNewScope

FYI that's the same as just `pwsh` by itself

> 1. it does not preserve the current working directory

Do you have something in your profile that sets location? I can't repro that

**Comment by plastikfan** [comment]
Hi @SeeminglyScience, yeah, you've git a point about that Invoke-Command, there's little to no point in that. Its just that I saw it in a stackoverflow post, tried it and seemed ok apart from teh caveats I already stated, but it slipped my notice that it's just the same as invoking pwsh.

And your workflow is something I already thought of but its long winded, hence me raising this feature request.

**Comment by SeeminglyScience** [comment]
> And your workflow is something I already thought of but its long winded, hence me raising this feature request.

The actual loop is just `exit` and `pwsh`, but if that's too long winded for you you could throw this in your profile:

```powershell
function Enter-PwshLoop {
    while ($true) {
        pwsh
        if ($LASTEXITCODE) {
            break
        }
    }
}
```

Then you just do that once, and send `exit` whenever you want a new session.

**Comment by plastikfan** [comment]
Hey @SeeminglyScience, thats a great suggestion. Actually, I made a tweek to your function that preserves the old file location:

```powershell
function restart-session {
  [Alias('ress')]
  param()

  [System.Management.Automation.PathInfo]$pathInfo = Get-Location;
  while ($true) {
    pwsh -WorkingDirectory $($pathInfo.Path)
    if ($LASTEXITCODE) {
      break
    }
  }
}
``

This works a charm, thanks.

**Comment by iSazonov** [comment]
I don't think it is worth doing anything special in the Engine to deal with this particular scenario as there are many workarounds.
Ex.: create a function to save cwd to a file and exiting, then you could have a code in profile to restore cwd.

**Comment by Mdarshan84** [comment]
This works for powershell, but powershell-ise goes on executing it infinitely.

**Comment by doctordns** [comment]
The Windows Powershell ISE is outside the scope of this repo. You can use the Windows feedback tool to report the ISE issue.
