### ISSUE TITLE
Get-Help should have the same content as online for Import-PowerShellDataFile 

### ISSUE THREAD

**Issue by fatherjack** [PowerShell/PowerShell#14530]
From a PowerShell session it should be possible to access the Docs content for Import-PowerShellDataFile [here](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/import-powershelldatafile) via the command

## Steps to reproduce
execute the Get-Help command
```powershell
Get-Help Import-PowerShellDataFile
```

## Expected behavior

It is expected to see the help content for this function as seen online at [https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/import-powershelldatafile](https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/import-powershelldatafile)

## Actual behavior
The actual output is not only different from the online content but it contains no useful guidance on how to use the Import-PowerShellDataFile functon as follows:

> Synopsis
> 
> Description
> 
> Parameters
> 
> -LiteralPath <String[]>
>     
> 
>     Required?                    false
>     Position?                    named
>     Default value                None
>     Accept pipeline input?       True (ByPropertyName)
>     Accept wildcard characters?  false
> 
> -Path <String[]>
>     
> 
>     Required?                    false
>     Position?                    0
>     Default value                None
>     Accept pipeline input?       False
>     Accept wildcard characters?  false
> Syntax
> Import-PowerShellDataFile [-LiteralPath <String[]>] []
> 
> Import-PowerShellDataFile [[-Path] <String[]>] [<CommonParameters>]
> Notes
> 
> Examples
> 1:
> PS C:>

## Environment data

````powershell
$PSVersionTable
````
|Name|                           Value|
|----|----|
|----                          | -----|
|PSVersion                     | 7.1.0|
|PSEdition                     | Core|
|GitCommitId               |     7.1.0|
|OS                             |Microsoft Windows 10.0.19042|
|Platform                     |  Win32NT|
|PSCompatibleVersions          | {1.0, 2.0, 3.0, 4.0…}|
|PSRemotingProtocolVersion |     2.3|
|SerializationVersion          | 1.1.0.1|
|WSManStackVersion            |  3.0|

**Comment by mklement0** [comment]
Help content is stored locally and can therefore get out of sync with the online versions.

Use [`Update-Help`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/update-help) to download the latest content.

[`Get-Help`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/get-help) shows only concise help _by default_, but you can opt-in to see more details. To get the full per-parameter information you mention, use `-Full`.

In fact, even the default, concise help view contains relevant pointers in the last section, notably also the ability to navigate to the online version with `-Online` and to show examples only with `-Examples`:

```none
REMARKS
    To see the examples, type: "Get-Help Get-Help -Examples"
    For more information, type: "Get-Help Get-Help -Detailed"
    For technical information, type: "Get-Help Get-Help -Full"
    For online help, type: "Get-Help Get-Help -Online"
```

Additionally, you can use the `-Parameter` parameter to get help for a given parameter only; e.g.,
`Get-Help Import-PowerShellDataFile -Parameter LiteralPath`
