### ISSUE TITLE
New-Item -Target parameter mishandles paths that look like wildcard patterns when creating symbolic links / reparse points

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14534]
Note: I'm writing this bug report from the perspective of the green-lit proposal to interpret `-Target` arguments as _literal_ (verbatim) paths - see #13136. Perhaps these two issues can be tackled together.

By contrast, in _Windows PowerShell_ you must _escape_ paths that _look like_ wildcard patterns, i.e. paths that contain `[` and `]`.
Using this escaping as of PowerShell _Core_ in 7.2.0-preview.2 doesn't work either, however, because the _escaped_ path, while recognized as an existing item, is them mistakenly used _verbatim_ as the link's target, resulting in a broken link.

## Steps to reproduce

```powershell
Push-Location ($tempDir = New-Item -Type Directory -Force "temp:/$PID")

try
{

  # Use a file name with '[' and ']' - without that, the test would succeed.
  $target = Join-Path $pwd.ProviderPath '[1] file.txt'

  # Create the file.
  $null = New-Item -Path $target -Value hi -Force

  # Try to create a symlink named 'lnk' in subdir. 'sub' (to be created on demand
  # with -Force) pointing to the newly created file.
  # Note:
  #  If ([WildcardPattern]::Escape($target)) is used to escape the path,
  #  the command *seemingly* succeeds, but the *escaped* path is mistakenly
  #  used *verbatim* as the target, quietly resulting in a *broken link*.
  { New-Item -ErrorAction Stop -Path sub/lnk -Type SymbolicLink -Force -Target $target } |
    Should -Not -Throw

} finally {

  Pop-Location
  Remove-Item -ErrorAction Ignore -LiteralPath $tempDir -Recurse -Force

}
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because (by design _unescaped_) `$target` isn't recognized as an existing item, even though the error message correctly lists the path:

```none
...
Cannot find path '.../[1] file.txt' because it does not exist.
...
```

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by abaumgaertner** [comment]
workaround: New-Item -Type Directory -Target [WildcardPattern]::Escape('abcd [bla]')
similar issues: #6232

**Comment by mklement0** [comment]
Thanks, @abaumgaertner, you probably meant
`New-Item -Type SymbolicLink foo -Target ([WildcardPattern]::Escape('abcd [bla]'))` (wrong type, missing (`(...)`), but, as stated in the initial post, this doesn't actually work:

* The command _seemingly_ succeeds,
* but the resulting symlink is _broken_, because the _escaped_ name is used _verbatim_  as the target path.

**Comment by mklement0** [comment]
@OctaneTwisted found that escaping twice(!) is an effective workaround: https://github.com/PowerShell/PowerShell/issues/6232#issuecomment-813860059

**Comment by Hashbrown777** [comment]
> This issue has not had any activity in 6 months, if this is a bug please try to reproduce on the latest version of PowerShell and reopen a new issue and reference this issue if this is still a blocker for you.

I feel like biannually creating duplicate issues is not a productive way to see if issues still exist.
