### ISSUE TITLE
Feature Request: Add .slice() method for strings and arrays

### ISSUE THREAD

**Issue by lesterw1** [PowerShell/PowerShell#14533]
## Summary of the new feature/enhancement
Add a **.slice()** method for strings and arrays similar to that of JavaScript.
See: https://www.w3schools.com/jsref/jsref_slice_array.asp

For strings, this would provide a method to return the *rightmost* N characters of a string
by using negative value. For example:
```
# Rightmost N existing solution
PS C:\ps1> $text = "ABCDEFG"
PS C:\ps1> $text.Substring($text.Length - 2)
FG

# Rightmost N characters with slice()
PS C:\ps1> "ABCDEFG".slice(-2)
FG

# Padding a month number with slice():
PS C:\ps1> ('0' + (get-Date).Month).slice(-2)
07
```

Below are a few additional examples of how **slice()** might work:
```
PS C:\ps1> "007".slice(-2)
07

PS C:\ps1> "ABCDEFG".slice(3)
DEFG

PS C:\ps1>  $fruits = @("Banana", "Orange", "Lemon", "Apple", "Mango")

PS C:\ps1> $fruits.slice(2)
Lemon

PS C:\ps1> $fruits.slice(2..4)
Lemon
Apple
Mango

PS C:\ps1> $fruits.slice(-2)
Apple

PS C:\ps1> $fruits.slice(-2..-1)
Apple
Mango
```

## Proposed technical implementation details (optional)
Virtually all of the slice() functionality can be leveraged from the existing array code.
The PowerShell code below serves as a simple example of how to define **slice()**:
```
# String slice()
$stringMethod = @{
  MemberName = 'slice';
  MemberType = 'ScriptMethod';
  Value      = { param([int32] $t) $( if ($t -ge 0) {$this.substring($t)} else {$this.substring(($this.Length + $t))}) }	
  Force      = $true
}
Update-TypeData -TypeName 'string' @stringMethod

# System.Array slice()
$arrayMethod = @{
  MemberName = 'slice';
  MemberType = 'ScriptMethod';
  Value      = { param($t) $this[$t] }	
  Force      = $true
}
Update-TypeData -TypeName 'System.Array' @arrayMethod
```
This method is a convenience feature for those familiar with JavaScript and
to provide a way to easily extract the rightmost characters of a string
(the substring() method does not permit negative values).

**Comment by doctordns** [comment]
This is probably something that should not be done in PowerShell. Instead, file this issue against .Net itself.

**Comment by lesterw1** [comment]
The point is to provide the method in PowerShell.  Whether or not .NET provides it is a different matter.

**Comment by iSazonov** [comment]
Have we already a discussion about "range"-s?

**Comment by bpayette** [comment]
PowerShell already supports slices through indexing. On arrays:
```powershell
PS[1] (172) > @(0, 1, 2, 3, 4, 5)[1..3]
1
2
3
```
And strings, (but not very well):
```powershell
PS[1] (182) > "hello world"[2..4] -join ''
llo
```
If you want an actual method on the string class which is owned by the .Net team, you would need to petition them as @doctordns  points out.
