### ISSUE TITLE
Get-Content does not support -encoding 'byte'

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PowerShell#14537]
This can be observed by testing the GPRegistryPolicyParser module using PowerShell 7.1. When Get-Content is called to read files exported from Group Policy using Backup-GPO, a warning is written that 'byte' is not a valid input for -encoding parameter. However, it does not seem that the module is functionally impacted. It still does what it is intended to do, other than returning the error.

Could someone from PowerShell advise the best approach for the issue in the other repo? If 'byte' is no longer available, should we remove the -encoding parameter, or use some other value?

https://github.com/PowerShell/GPRegistryPolicyParser/issues/6

**Comment by SeeminglyScience** [comment]
> Could someone from PowerShell advise the best approach for the issue in the other repo? If 'byte' is no longer available, should we remove the -encoding parameter, or use some other value?

Use the `-AsByteStream` switch parameter.

**Comment by mklement0** [comment]
@mgreenegit, here's the story behind this breaking change, which was made in v6: #7986

The [conclusion](https://github.com/PowerShell/PowerShell/issues/7986#issuecomment-436816082) by @SteveL-MSFT  was: 

 > At this time, without additional customer feedback, it seems that the number of hits in the corpus based on the size of the corpus doesn't justify spending effort to add this back.

It certainly was an unfortunate change that people keep running into.

If you feel strongly enough about revisiting this, I encourage you to create a _new_ issue of type "Feature Request/Idea" and to make the case that `-Encoding Byte` should be brought back (alongside `-AsByteStream`, as an effective alias).

**Comment by mgreenegit** [comment]
It looks like -asbytestream is going to work for parsing .pol files

**Comment by mklement0** [comment]
@mgreenegit, yes, `-AsByteStream` in PowerShell Core is the equivalent of `-Encoding Byte` in Windows PowerShell.

Leaving aside that this change isn't obvious, the bigger concern is that if you write code that targets _both_ editions, you must explicitly account for this difference, which is a nuisance.

**Comment by RandyDotCom** [comment]
A parameter cannot be found that matches parameter name 'AsByteStream'.
A parameter cannot be found that matches parameter name 'Encoding'. 
Neither Parameter is available in the VS Code Terminal 
This is a breaking change for me 
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core 
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by mklement0** [comment]
@RandyDotCom: `-Encoding` is a _dynamic_ parameter of `Get-Content`, applicable only to the _file-system_ (the `FileSystem` [provider](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Providers)).

If neither `-Encoding` nor `-AsByteStream` are recognized (in your case - 7.3.2 - it would be the latter), the implication is that the _current location_ (as reported in `$PWD` / with `Get-Location`) is _not_ a file-system location.

If you find this _not_ to be true, create a new issue.
