### ISSUE TITLE
Join-Path doesn't handle provider prefixes correctly on Unix-like platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14538]
## Steps to reproduce

On macOS or Linux:

```powershell
Join-Path (Get-Item .).PSParentPath foo | Should -Be "$((Get-Item .).PSParentPath)/foo"
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because the existing provider prefix isn't recognized as such, causing its `\` separator to be normalized to `/` and _another_ provider prefix to be prepended.

```none
Expected strings to be the same, but they were different. Expected length: 65 Actual length:   103 Strings differ at index 38. Expected: '...tem::/User...' But was:  '...tem::Micro...'
```

That is, `Join-Path`'s output was something like (note the doubled provider prefix, with the 2nd one using `/`):

```none
Microsoft.PowerShell.Core\FileSystem::Microsoft.PowerShell.Core/FileSystem::/Users/jdoe/Desktop/foo
```

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by iSazonov** [comment]
Is this for Linux and MacOs only?

**Comment by mklement0** [comment]
@iSazonov, yes, because the problem is related to normalizing `\` to `/`.

**Comment by octos4murai** [comment]
Hi folks. Is this up for grabs? If so, I'd like to take it on.

**Comment by octos4murai** [comment]
@iSazonov, resurfacing my question above. This issue is not tagged as up for grabs but I'm wondering whether it could still be a good one for me to look into.

**Comment by vexx32** [comment]
@octos4murai I haven't seen anyone else wanting to take it up, and it seems a fairly clear case of the behaviour being bugged, so yeah, we may as well consider it up for grabs. 🙂

**Comment by iSazonov** [comment]
FileSystem Provider always normalizes paths. See https://github.com/PowerShell/PowerShell/blob/3733a0bb3749b448002b034d0d09055367adac27/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L103-L106.

**Comment by octos4murai** [comment]
Thanks for your response @iSazonov -- but allow me to switch gears for a bit... Is `Join-Path` even meant to have support for paths prepended with the `FileSystemProvider` prefix? This page does not give any hints that it is supported behaviour: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.1.

A supported way to accomplish @mklement0's example above is to do this instead:
```pwsh
Join-Path (Get-Item .).Parent.FullName foo
# Returns something like: /home/octos4murai/foo
```

Unless I'm missing something, this should be classified as an enhancement (if it's decided it should be supported at all).

**Comment by iSazonov** [comment]
> Is `Join-Path` even meant to have support for paths prepended with the `FileSystemProvider` prefix?

Yes, it is. All paths on top level is PowerShell paths (provider qualified paths). Then on level below they are resolved to provider specific paths.

Root of the issue is in broken normalization `\` to `/` .

**Comment by octos4murai** [comment]
Thanks! For the following command in Unix-like systems:
```pwsh
Join-Path (Get-Item .).PSParentPath foo
```
Which of the following is the expected result:
```pwsh
Microsoft.PowerShell.Core/FileSystem::/home/octos4murai/foo
```
or
```pwsh
Microsoft.PowerShell.Core\FileSystem::/home/octos4murai/foo
```
I assume it's the first one with consistent path separators?

**Comment by iSazonov** [comment]
Provider names are never normalized. You can find them in SingleShellProviderNames class.
In your example this is `Microsoft.PowerShell.Core\FileSystem::/home/octos4murai/foo`.
