### ISSUE TITLE
Feature Request - Implement default/implicit "help" parameter set based on -?

### ISSUE THREAD

**Issue by dbaileyut** [PowerShell/PowerShell#14547]
## Summary of the new feature/enhancement

As I user, I would like a quicker way to get to the full help and examples for cmdlets. I'll often append "-?" as a first step and then decide I would like to see more of the help content. I would be nice if I could arrow up in my command history and just append -Full, -Examples, etc. This would be a bit faster than the tab complete from Get-Help (at least in my imagination).

## Proposed technical implementation details (optional)

I can see this being implemented as a parameter set keying off of "-?" where you could add additional Get-Help parameters. Ideally this would apply to all cmdlets automatically.

For example:

To see the full help:
`Get-Item -? -Full # The same as 'Get-Help Get-Item -Full'`
To see examples:
`Get-Process -? -Examples # The same as 'Get-Help Get-Process -Examples'`

**Comment by mklement0** [comment]
I like the idea, but it has been proposed before: #4137

**Comment by dbaileyut** [comment]
Ah, I searched but missed it. My bad.
