### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#14559]
## Steps to reproduce

```powershell
$Global:Error.Clear()
# This line will produce an error which is expected for this example:
Get-Service -Name 'Unknown'
$Global:Error | Select-Object -Property *
# This Try Catch construct will try to process that error but the Type cannot be found!
Try
{Get-Service -Name 'Unknown' -ErrorAction Stop}
# This line tries to handle the service unknown error but cannot find the type
Catch [NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand]
{'Service cannot be found'}
Catch
{'Some other error occurred'}
```

## Expected behavior

```
The catch statement to work as intended

```

## Actual behavior

```
It fails to find the type and a separate error is produced
Get-Service: S:\pny-processed\PowerShellScripts\Test\GetServiceTryCatchTypeError.ps1:3
Line |
   3 |  Get-Service -Name 'Unknown'
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find any service with service name 'Unknown'.


PSMessageDetails      :
Exception             : Microsoft.PowerShell.Commands.ServiceCommandException: Cannot find any service with service
                        name 'Unknown'.
TargetObject          : Unknown
CategoryInfo          : ObjectNotFound: (Unknown:String) [Get-Service], ServiceCommandException
FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, S:\pny-processed\PowerShellScripts\Test\GetServiceTryCatchTypeError.ps1:
                        line 3
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

InvalidOperation: S:\pny-processed\PowerShellScripts\Test\GetServiceTryCatchTypeError.ps1:9
Line |
   9 |  Catch [NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetSe …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand].


```

## Environment data

```Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
The operand for `catch` clauses must be a _type_ (class), more specifically one that derives from `System.Exception`.

In your case you must use `[Microsoft.PowerShell.Commands.ServiceCommandException]`.

You can find that name as follows:

```powershell
Get-Service -ErrorAction SilentlyContinue nosuch; $Error[0].Exception.GetType().FullName
```

You can also easily verify whether a type literal (`[...]`) refers to an existing (loaded). NET type simply by executing it by itself; this tells you that your type literal isn't valid:

```powershell
PS> [NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand]
```

**Comment by mklement0** [comment]
P.S.: It's unfortunate that the issue-template offers "My Bug Report" as the default title, but it's always better to create a custom title that summarizes the issue being reported.

**Comment by RG255** [comment]
Thanks for your reply apologies regarding the title - my bad

The answer you supplied obviously worked - Thanks

The question remains how do I get from the reported error:

FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand

to your solution:

[Microsoft.PowerShell.Commands.ServiceCommandException]

Is taking the last part of the category info:
CategoryInfo          : ObjectNotFound: (Unknown:String) [Get-Service], ServiceCommandException
and replacing the last item in the exception message along with removing the bit from the start to the comma going to work every time.

Each time I have used the construct in the past I have found the FullyQualifiedErrorId  works. I am guessing that that is not a reliable source of such information, it would be helpful if there was a standard - I have not found that so far. Any pointers?

**Comment by mklement0** [comment]
You're welcome; no worries re title; I'm hoping the default title will be removed from the templates soon, so that it'll be more obvious that a custom title should be specified.

As stated, `catch` expects an _exception type_ as the operand, and the specific type can be determined via the `.Exception` property of the [`System.Management.Automation.ErrorRecord`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.ErrorRecord) instances that represent PowerShell errors:

```powershell
# Provoke the error of interest.
Get-Service -ErrorAction SilentlyContinue nosuch; 
# Examine the .Exception property of the most recent error record  to get the exception's full type name.
$Error[0].Exception.GetType().FullName
```

The above outputs `Microsoft.PowerShell.Commands.ServiceCommandException`.

**Comment by RG255** [comment]
@mklement0 Thanks for that - All resolved now.
