### ISSUE TITLE
Start-Process -ArgumentList doesn't accept String[] that is not literal

### ISSUE THREAD

**Issue by M-Pixel** [PowerShell/PowerShell#14551]
PowerShell documentation on `Start-Process` states that the type for parameter `-ArgumentList` is `String[]`.

This appears to hold true when running

```ps1
$x = '/k','echo foobar'
Start-Process CMD -ArgumentList $x
```

The result is that I see a CMD window appear with "foobar" as the first line.  `$x.GetType()` returns `Object[]`.  It also works when $x is manually coerced with `[String[]]`.

However, as soon as I append an addition item to the array...

```ps1
$x = ,'/k'
$y = $x,'echo foobar'
Start-Process CMD -ArgumentList $y
```

this error is produced:

```
Cannot convert 'System.String[]' to the type 'System.String' required by parameter 'ArgumentList'.  Specified method is not supported.
```

Given that both $x and $y in both scenarios are `[String[]]`, the error seems uncalled for.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
I believe the issue here is that `$y = $x,'echo foobar'` produces an array of 2 elements, the first being your `$x` array and the second being `echo foobar`.

```powershell
$x = ,'/k'
$y = $x,'echo foobar'

$y.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array

$y.Count

2

$y[0].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array

$y[1].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object
```

If you are wanting to add to an array you can use `+=`  but that can be problematic when you start dealing with large arrays. You are better off using a Generic List like so

```powershell
$list = [Collections.Generic.List[String]]@('/k')
$list.Add('echo foobar')
```

You can add and remove any element you want and it's also typed so adding non strings will cast to a string automatically for you.
