### ISSUE TITLE
Introduce new preference variable '$ForcePreference' similar to '$ConfirmPreference'

### ISSUE THREAD

**Issue by fawohlsc** [PowerShell/PowerShell#14557]
## Summary of the new feature/enhancement

In a nutshell, there is no way to generally `-Force` all cmdlets to suppress prompts.

![image](https://user-images.githubusercontent.com/41372128/103656943-8404ce80-4f69-11eb-8782-f24042827c87.png)

This requires to add `-Force` to every cmdlet:
```powershell
My-CmdletWithConfirmation –Force
```

While for `-Confirm` someone could set the `$ConfirmPreference`, there is no such variable for `-Force`. See also
[use -confirm instead of "-force"](https://github.com/Azure/azure-powershell/issues/475) and [Everything you wanted to know about ShouldProcess](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-7.1).

## Proposed technical implementation details (optional)

Introduce a preference variable `$ForcePreference` similar to [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.1).

**Comment by fawohlsc** [comment]
See also https://github.com/Azure/azure-powershell/issues/13878

**Comment by mklement0** [comment]
I can't speak to the original design intent, so I don't know if this was an intentional omission due to resulting in potentially inadvertent destructive behavior. (While `$ConfirmImpact = 'None'` can be used to deactivate the regular confirmation prompts, the separate need for `-Force` in some cases can be conceived of as a confirmation of intent that should always be expressed _explicitly_.)

That said, It is already possible to implement this behavior, namely as follows (see [about_Parameters_Default_Values](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameters_default_values)):

```powershell
# !! Implicitly passes -Force to all cmdlets / advanced functions or scripts that have a -Force switch.
$PSDefaultParameterValues['*:Force'] = $true
```

Note that, due to PowerShell's dynamic scoping, this will affect also all descendant scopes; if set in the _global_ scope, it will also affect code in modules, i.e. the entire (local) session.

**Comment by jhoneill** [comment]
-Force is not a common parameter like -verbose, -errorAction, -confirm so it would require existing things with a -Force parameter to be updated . 

As @mklement0  says , things which require -Force usually (but not always) have a confirm impact level so many can be controlled that way, and those which can't can be set singly or with wildcards. 
The "I know what I'm doing" argument applies to single commands,  you typically don't want to confirm that you meant to change "X" but would like to be told you're about to destroy "Y", so globally setting it is _brave._

**Comment by fawohlsc** [comment]
@mklement0 and @jhoneill: First of all, many thanks for your insightful response. Agree that this is _brave_. The use case is rerunning Pester tests on transient errors which internally use Azure PowerShell (See [fawohlsc/azure-policy-testing](https://github.com/fawohlsc/azure-policy-testing)). If you rerun the tests, it would obviously overwrite Azure resources created by the previous test run and unfortunately prompt the user. You can add `-Force` to every cmdlet invocation (e.g. [New-AzRouteTable](https://docs.microsoft.com/en-us/powershell/module/az.network/new-azroutetable?view=azps-5.3.0)), but this can easily be forgotten. Setting `$PSDefaultParameterValues['*:Force']` scoped to the Pester test seems to be a great option. So no need to introduce `$ForcePreference`. Hence closing the issue. Again many thanks.

**Comment by mklement0** [comment]
Glad to hear it, @fawohlsc.
Don't know if it's required in your case, but I forgot to mention that you should run
`$PSDefaultParameterValues = $PSDefaultParameterValues.Clone()` first, to create a local copy of the dictionary; without that, `$PSDefaultParameterValues['*:Force']` - even when run  in a _non-global_ scope - takes effect _globally_.
I've updated my previous comment accordingly.

**Comment by fawohlsc** [comment]
Thank you @mklement0 - very helpful! 🥇
