### ISSUE TITLE
ETS ToString() script methods aren't honored in expandable strings and casts

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14561]
The only type where a custom `.ToString()` is consistently honored appears to be `[pscustomobject]`.

With all others - irrespective of whether the script method is added at the _type_ level (`Update-TypeData`) or the _instance_ level (`Add-Member`) - only _explicit_ `.ToString()` calls honor the override; string interpolation and casts do not.

## Steps to reproduce

```powershell
# Override the .ToString() method for [hashtable]
# to output a compressed JSON representation.
Update-TypeData -Force -TypeName System.Collections.Hashtable -MemberName ToString -MemberType ScriptMethod -Value { $this | ConvertTo-Json -Compress }

$ht = @{ one = 1 }
$htAsJson = $ht | ConvertTo-Json -Compress

# Explicit .ToString() call: OK
$ht.ToString() | Should -Be $htAsJson

# !! BROKEN: [string] cast
[string] $ht | Should -Be $htAsJson

# !! BROKEN: string interpolation
"$ht" | Should -Be $htAsJson
```

## Expected behavior

All tests should pass.

## Actual behavior

Tests 2 and 3 fail, because the `.ToString()` override wasn't honored.

```none
Strings differ at index 0. Expected: '{"one":1}' But was:  'System.Collections.Hashtable'
```

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by iSazonov** [comment]
> [string] $ht | Should -Be $htAsJson

Interesting, what is expectations for:
1. [string] $ht | Should -Be $htAsJson
2. $ht -as [string]
3. $ht.ToString()

I wouldn't be surprised if all three options worked differently by design.

**Comment by mklement0** [comment]
`.ToString()` is the official stringification source for any .NET type, so there is no reason for these to function differently - and indeed they don't for _type-native_ `.ToString()` methods (and also not for ETS methods attached to `[pscustomobject]`).

(That casts and string interpolation look for a `.ToString()` overload that takes a `System.IFormatProvider`  argument so that culture-invariant formatting can be requested is unrelated to this discussion. Also, the `-as` bug discussed in #8129 doesn't seem to affect `-as [string]`).

**Comment by mklement0** [comment]
@iSazonov, to me this is clearly bug.

Please either argue your point as to why these scenarios should behave differently or invite a subject-matter expert to weigh in.

If the issue is labeled just "Issue-Question", I fear it will wither and die.

**Comment by iSazonov** [comment]
> If the issue is labeled just "Issue-Question", I fear it will wither and die.

Labels are nothing, human resources are all 😄

**Comment by mklement0** [comment]
Well, let's go with _both_, just to be safe.

**Comment by JamesWTruher** [comment]
I'm not sure if this helps with your scenario, but `[pscustomobject]` works as you expect:
```
PS> $a = [pscustomobject]@{ one = 1 }
PS> [string]$a
@{one=1}
PS> $a.ToString()

PS> add-member -input $a -MemberType ScriptMethod -Value { return ("hey! {0}" -f $this.one) } -Name ToString -Force
PS> $a.ToString()
hey! 1
PS> [string]$a
hey! 1
PS> $a -as [string]
hey! 1
PS> $a | ft {"$_"}

"$_"
----
hey! 1
```

I haven't checked the code, but I expect this is in our method dispatch code and to support the expected behavior we would need to call an ETS defined method first.

**Comment by mklement0** [comment]
Thanks, @JamesWTruher, but this wasn't about a specific scenario, and the fact that it does work for `[pscustomobject]` - only - is noted in the initial post.

Instead, this is about _consistently_ honoring an ETS-overridden `.ToString()` method, across _all_ types, so, yes, consistently preferring an ETS method by the given name seems like the way to go.

**Comment by vexx32** [comment]
Engine WG discussed this issue today. Our opinion is that the requested change is not likely to be trivial, as these different methods of casting happen at different points in the engine.

We agree it would make sense for these three casting methods to be consistently calling the ETS ToString() method, but it would be a breaking change to the existing behaviour at this point. 

We would need to see a compelling use case where this is necessary to consider changing the existing behaviour and risk breaking existing scripts that may unintentionally be relying on the behaviour.

**Comment by mklement0** [comment]
> We would need to see a compelling use case this is necessary to consider changing the existing behaviour

Can I suggest a shift in perspective? We would need to see existing use cases that may break in order to justify keeping the existing, blatantly inconsistent behavior that is likely to trip up (future) users.

And, if the answer _then_ turns out to be: We won't fix this:

> We agree it would make sense

Acknowledging that something is broken in the deep recesses of issues in this repo is insufficient.
As with all warts that are being retained for the sake of backward compatibility, _they need to be documented_.

**Comment by iSazonov** [comment]
We have an issue with a request to support _extension methods_. Many find that offer very desirable. But if we want extension methods we will fall in the issue as result.
