### ISSUE TITLE
Using module doesn't export classes from nested modules

### ISSUE THREAD

**Issue by Colyn1337** [PowerShell/PowerShell#14580]
## Steps to reproduce

Create module file ./bin/class.psm1 with any class
```powershell
Class HelloWorld{
  HelloWorld{
    'Hello World'
  }
}
````
Create higher level module file ./helloworld.psm1 with:
````powershell
using module ./bin/class.psm1

function Test-Please {
  [HelloWorld]::new()
}
````
From terminal import high level module:
````powershell
using module ./helloworld.psm1
````
invoke the test-please cmdlet:
````powershell
Test-Please
````
Observe the returned 'Hello World' statement

Call class from terminal:
````powershell
[HelloWorld]::new()
````
Error is returned stating:
````powershell
InvalidOperation: Unable to find type [HelloWorld].
````

## Expected behavior

The classes from the nested module should be exported

## Actual behavior

Classes from the nested module aren't exported.  What's worse, is that calling the higher level module will remove the classes and enums if they were previously added manually by calling ````using module ./bin/class.psm1````.  Once removed they cannot be added again unless the session is terminated and a new session created.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X8…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It seems we already have such issue.

**Comment by Colyn1337** [comment]
I did search to see if it had been reported before, I doubted I'd be the first to notice.  But I didn't find a duplicate.  Apologies if this is noise.

**Comment by mklement0** [comment]
#4114 sounds like it could be a duplicate.

Also note the meta issue that has a list of many class-related issues: #6652
