### ISSUE TITLE
Invoke-WebRequest with digest

### ISSUE THREAD

**Issue by damianon** [PowerShell/PowerShell#14599]
We have a script that runs just fine on Powershell 5, but when executing on devops agenst running ubuntu and powershell core 7.1 it always fails with a 401 Error.

```
$Password = ConvertTo-SecureString $MongoAtlasApiKeyPrivate -AsPlainText -Force
$Credentials = New-Object System.Management.Automation.PSCredential ($MongoAtlasApiKeyPublic, $Password)

Invoke-WebRequest -Uri $MongoAtlasApiUrl -Method POST -ContentType "application/json" -Credential $Credentials -Body $json
```

It's trying to callt he mongo atlas api, which according to mongo's documentation requires digest authentictaion. However I couldn't find anything mentioning digest with Invoke-WebRequest. Onlny Oauth and other auth methods, but nothing about digest. Is it just no possible anymore since PWSH 6/7?

This is the corresponding mongo documentation: https://docs.atlas.mongodb.com/reference/api/whitelist-add-one

**Comment by iSazonov** [comment]
I believe it is not PowerShell issue but underlying .Net. See https://github.com/dotnet/runtime/issues/42301
You can discuss this there.

As workaround you always add an authentication header manually - you can find examples in Internet.

**Comment by damianon** [comment]
I can find many examples for basic or bearer authentication, but almost nothing about digest with powershell.

**Comment by iSazonov** [comment]
@damianon The repo is only for PowerShell developers. You can get help faster on forums and other resources.

**Comment by CarloToso** [comment]
@iSazonov I think we can close, the issue underlying with dotnet was fixed, It works correctly in PS7.3.2
Test:
```ps1
$password = ConvertTo-SecureString 'password' -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ('user', $password)
Invoke-WebRequest "https://httpbin.org/digest-auth/auth/user/password" -Credential $credential
```
