### ISSUE TITLE
Unable to load the service index for source https://powershell.myget.org/F/powershell-core/api/v3/index.json - Feed does not exist. 

### ISSUE THREAD

**Issue by satya-rajesh** [PowerShell/PowerShell#14598]
With reference to: https://github.com/dotnet/sdk/issues/15276

/usr/lib/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Unable to load the service index for source https://powershell.myget.org/F/powershell-core/api/v3/index.json. [/usr/src/photon/BUILD/PowerShell-7.0.3/src/powershell-unix/powershell-unix.csproj]
/usr/lib/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Response status code does not indicate success: 404 (Feed does not exist.). [/usr/src/photon/BUILD/PowerShell-7.0.3/src/powershell-unix/powershell-unix.csproj]
error: Bad exit status from /var/tmp/rpm-tmp.x28ccJ (%build)

While accessing the url: https://powershell.myget.org/F/powershell-core/api/v3/index.json, it throws "Feed does not exist."

Please suggest

**Comment by satya-rajesh** [comment]
Powershell team,

Any suggestions please..

.net team suggested to check with powershell team:
https://github.com/dotnet/sdk/issues/15276#issuecomment-760489422

**Comment by iSazonov** [comment]
Publishing to myget was removed in #14613. I guess the feed was removed too.

/cc @rjmholt @JamesWTruher Please comment the issue.

**Comment by iSazonov** [comment]
@satya-rajesh Could please add more info why do need this?

**Comment by satya-rajesh** [comment]
> @satya-rajesh Could please add more info why do need this?

We were building powershell 7.0.3, till last week it was building. It was failing after that and the root cause is, powershell is having this url "https://powershell.myget.org/F/powershell-core/api/v3/index.json" in it's source which is no longer working - Feed does not exist.

**Comment by satya-rajesh** [comment]
> > @satya-rajesh Could please add more info why do need this?
> 
> We were building powershell 7.0.3, till last week it was building. It was failing after that and the root cause is, powershell is having this url "https://powershell.myget.org/F/powershell-core/api/v3/index.json" in it's source which is no longer working - Feed does not exist.

Is there any patch we can try to fix this issue ?

**Comment by iSazonov** [comment]
I think you need to build 7.0.4. 
It seems it's not finished yet though. Perhaps we need to wait a day.

**Comment by amdslancelot** [comment]
I can now build with 7.0.4 . But i saw in nuget.config there's only one source "https://api.nuget.org/v3/index.json" left. Is everything moved under here?

**Comment by iSazonov** [comment]
myget was used only for publishing preview versions. Now the site is not used.
