### ISSUE TITLE
Update PowerShell Linux dependencies.

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/PowerShell#14597]
Downloading PowerShell as tar.gz payload requires users to have some dependencies on the machine.
The dependencies are inherited by .NET. 
Existing PowerShell dependencies are outdated.

List of .NET dependencies can be found [here](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies)
List of Powershell dependencies can be found [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#dependencies)

PowerShell lists additional dependencies “liblttng-ust0, libcurl3, libunwind8, libuuid1”.
We can remove all of them.
Libcurl - .NET 5 removed libcurl dependency.
Libunwind - .NET 2.1 remove the libunwind dependency. [Link to .NET commit](https://github.com/dotnet/coreclr/commit/d104270f8412381b5eb7715a775c3999f28b740c)
libuuid1, liblttng-ust0 – PowerShell is not using.

**Comment by iSazonov** [comment]
@bagajjal Please report the issue in https://github.com/PowerShell/PowerShell-Docs

**Comment by anamnavi** [comment]
libcurl, libuuid1, libunwind8 seems to be removed. Remove from https://github.com/PowerShell/PowerShell/blob/master/tools/packaging/packaging.psm1 and then remove from preview docker images.

**Comment by anamnavi** [comment]
I plan to tackle this issue and left a note on there for that reason :)

**Comment by sdwheeler** [comment]
@iSazonov what am I supposed to do with this? If there is a docs need, please file a [docs issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/new/choose).
