### ISSUE TITLE
Avoid using escape sequences tricks when TERM=dumb

### ISSUE THREAD

**Issue by Link1J** [PowerShell/PowerShell#14594]
## Summary of the new feature/enhancement

When the environment variable `TERM` is set to `dumb`, avoid using escape sequences tricks as they make using the prompt impossible.
I know this is an unlikely situation, as most terminal emulators have support for escape sequences.

The pictures are to help show how a few different ways PowerShell currently handles `TERM=dumb`.
Linux appears to attempt to follow along with the request (Picture 2), but doesn't go all the way.
Windows (Picture 1) does nothing. Not really surprising, as Windows didn't really need to tell terminal emulators apart.

#### SSHed into a Windows Machine
![Powershell does not like playing dumb](https://user-images.githubusercontent.com/22891267/104235407-eefb4d00-5422-11eb-94e2-fbcddfa037c8.PNG)
#### Arch Linux Machine
![Powershell does not like playing dumb 3](https://user-images.githubusercontent.com/22891267/104239859-2ff66000-5429-11eb-9cfe-91725f82ad97.PNG)

> And here is PowerShell descends into madness. It is likely caused by the fact the PowerShell is still expecting escape sequences to work correctly.
> ![Powershell does not like playing dumb 2](https://user-images.githubusercontent.com/22891267/104235529-1baf6480-5423-11eb-89ee-924b87c11aea.PNG)

## Proposed technical implementation details (optional)

When the environment variable `TERM` is set to `dumb`, avoid using escape sequences tricks. Only escape sequences tricks used internally by PowerShell should be effected. If a user profile or external script uses them, PowerShell should not remove the escape sequences.

**Comment by iSazonov** [comment]
> I know this is an unlikely situation, as most terminal emulators have support for escape sequences.

Root of the issue that PowerShell directly injecting  EscS-s (escape sequences) in strings.

I would call it a bad design, but in fact, it's just _the lack of design at all_.

---
#### PowerShell does a lot of magical things and I'm pretty sure we can do such magic things to format the output and support coloring.
---
The design should has two directions:
1. Getting effective internal abstraction(s) for EscS-s
2. Introducing power and magic _language_ support.

For 1. It should be done today. Simplest EscS internal abstraction could be a struct like:
```c#
struct EscapedString
{
    string Prefix;
    string Value;
    string Suffix;
}
```
It is not too difficult rewrite PowerShell internals to utilize this.

User experience:
```powershell
$str = [EscapedString]"`e[31mRed string`e[0m"
Write-Host $str
```

For 2. Direct using EsqS-s is not user friendly. It is better to have any language sugars to control _rendering_. And we could think about supporting (as PowerShell magic) **generic** rendering support.
**_With the approach we will can able to work transparently with any consoles - dumb terminal, VT terminal, graphical console, web browser and so on._**
Ex.: with `<magically formatter string> | ConvertTo-HTML` users will get rich HTML formatted output. Symmetrically, we could have  `<magically formatter string> | ConvertTo-EscString` users will get rich EscS formatted output.
Finally, for generic support, we could think about `<magically formatter string> | ConvertTo-RenderingString -RenderingPlugin [HTML | VirtualTerminal | OtherRenderingPlugins]`.
It is only demo of the idea - really we have no need to work with _raw_ formatting, we should support _generic_.
Obviously, we shouldn't invent our own markup language. There are two main ones - HTML and EscS/VT. Currently MSFT team prefer to have EscS/VT as main one. Uses experience looks like `"$($PSStyle.FileInfo.Executable + $exe.Name + $PSStyle.Reset)"`.  
It looks very cumbersome and difficult for beginners. It looks very cumbersome and difficult for beginners. I would no doubt prefer a subset of HTML as it is more readable, more widely known, and more user-friendly.
But in fact it doesn't matter which rendering method we use by _default_ - our abstractions must support the generic path.
It can be done like this (this is a topic for discussion to find the best syntax super):
`[RenderingString]"a string formatter with default rendering method"`. `RenderingString` is an abstraction which call a parser for default rendering method (EscS for VT console) and internally convert the string to `EscapedString` struct.

User experience:
```powershell
$str = [RenderingString]"$($PSStyle.Foreground.Red)Red string$($PSStyle.Reset)"
Write-Host $str
```

#### Such two level abstraction is very simple and very power - this allows us to work magically in any consoles, implement flexible formatting and develop step by step in any direction.
