### ISSUE TITLE
New-JobTrigger support in powershell core

### ISSUE THREAD

**Issue by amitoverflow-ui** [PowerShell/PowerShell#14609]
## Summary of the new feature/enhancement
Are there any plans to support - New-JobTrigger cmdlet in powershell core?

**Comment by iSazonov** [comment]
@amitoverflow-ui The cmdlet is in PSScheduledJob module which is Windows component. The module is still not PowerShell Core compatible. You can ask about this in https://github.com/PowerShell/PowerShellModuleCoverage repository.
