### ISSUE TITLE
SemanticVersion does not correctly handle build metadata when no pre-release label present

### ISSUE THREAD

**Issue by majaeger** [PowerShell/PowerShell#14605]
## Steps to reproduce

```powershell

[semver]::Parse("1.0.0+asdf")
MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."

[semver]::Parse("1.0.0-beta+asdf")

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----        --------------- ----------
1      0      0                   beta            asdf

```

## Expected behavior

See semver.org:

Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

https://semver.org/#spec-item-11

```powershell

[semver]::Parse("1.0.0+asdf")
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----        --------------- ----------
1      0      0                                       asdf

```

## Actual behavior

```powershell

[semver]::Parse("1.0.0+asdf")
MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."

```

## Environment data

```powershell

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.20279
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
We use Regex to parse. So the fix would be to enhance the Regex. Also we need to add more tests.

**Comment by p0W3RH311** [comment]
[the are an official Regex for this:](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string)

**Comment by anmenaga** [comment]
Restarted Linux CIs that failed in unrelated PSGallery cert issue.

**Comment by JustinGrote** [comment]
@SteveL-MSFT is this possibly up for grabs again since the other PR was closed? I just got bit by this and had to implement my own overriding class.

**Comment by hanshardmeier** [comment]
Looks like this has been fixed meanwhile:
![pwsh](https://github.com/PowerShell/PowerShell/assets/1502977/6c2d36fb-5fc2-48a0-95f5-a937533561c0)

I think this can be closed.
