### ISSUE TITLE
Passing Active Directory Objects into a Runspace Stripts All Non-Default Properties

### ISSUE THREAD

**Issue by MaxAnderson95** [PowerShell/PowerShell#14604]
For those of you who frequently work with the ActiveDirectory module, you'll know using `Get-ADUser` or `Get-ADComputer` will only return a few of the many properties of the object from the database (10 and 9 respectively). If you wish to retrieve additional properties of an AD object, you must specify the `-Properties` parameter and provide one or more property names.

When passing an ADObject that contains one or more non-default properties to a runspace as an argument, the property values are not accessible. They can not be accessed with dot-notation, nor used in a Where-Object filter (among other things).

Interestingly enough, if you just pass the object through the runspace script and output it again in the current context, it will now have the missing properties again, as if they were never lost.

I can reproduce the exact same behavior with `Start-ThreadJob`, `ForEach-Object -Parallel` (which of which uses runspaces) as well as the popular 3rd party module `PoshRSJob`. When using either of these method, it makes no difference to which method I use to pass the object into the job. The problem occurs if I use the `-ArgumentList` or the `$using:` syntax.

This problem however does **NOT** occur with the standard `Start-Job` which spawns an entire new process rather than a new thread/runspace. The downside to using standard background jobs is that the objects are serialized upon passing to the job.

## Steps to reproduce
In the example below the `Name` property of an ADUser object is "default", but the `City` property must be requested specifically. I output the two properties three times each. Once before, once from within the runspace, and once using the object that was passed through the runspace and back into the current context.
```powershell
$ADUser = Get-ADUser -identity mander -Properties City

Write-Output "Before Runspace - The value of name is: $($ADUser.Name)"
Write-Output "Before Runspace - The value of city is: $($ADUser.City)"

$Runspace = [runspacefactory]::CreateRunspace()
$PowerShell = [powershell]::Create()
$PowerShell.runspace = $Runspace
$Runspace.Open()

[void]$PowerShell.AddScript({
    Param ($ADUser)
    $a = "Inside Runspace - The value of name is: $($ADUser.Name)"
    $b = "Inside Runspace - The value of city is: $($ADUser.City)"
    $c = $ADUser

    return @($a,$b,$c)
})
[void]$PowerShell.AddArgument($ADUser)

$a, $b, $c = $PowerShell.Invoke()

$a
$b

Write-Output "After Runspace  - The value of name is: $($c.Name)"
Write-Output "After Runspace  - The value of city is: $($c.City)"
```

## Expected behavior

```none
Before Runspace - The value of name is: Max Anderson
Before Runspace - The value of city is: Atlanta
Inside Runspace - The value of name is: Max Anderson
Inside Runspace - The value of city is: Atlanta
After Runspace  - The value of name is: Max Anderson
After Runspace  - The value of city is: Atlanta
```

## Actual behavior

```none
Before Runspace - The value of name is: Max Anderson
Before Runspace - The value of city is: Atlanta
Inside Runspace - The value of name is: Max Anderson
Inside Runspace - The value of city is:
After Runspace  - The value of name is: Max Anderson
After Runspace  - The value of city is: Atlanta
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaxAnderson95** [comment]
I also would like to note that this issue is not only occuring in PowerShell core. I've also observed the same behavior in Windows PowerShell 5.1. This would tell me that it's not an issue with any abstraction layer (such as [WindowsCompatibility](https://github.com/PowerShell/WindowsCompatibility) making the ActiveDirectory module work within PowerShell Core.

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.546
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.546
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Since AD module is not source open only MSFT team can investigate the issue. I guess the problem can be related with how PowerShell clones variables. If so we could try to fix this in the repo. Otherwise the issue should be reported by Windows support channels, UserVoice site and MSFT forums.

/cc @PaulHigin Could you please make an conclusion?

**Comment by jborean93** [comment]
This is definitely a weird one. When testing against a remote Runspace I can see the CLIXML returned contains the property and accessing `$obj.City` works just fine

```xml
<Obj RefId="0">
  <TN RefId="0">
    <T>Microsoft.ActiveDirectory.Management.ADUser</T>
    <T>Microsoft.ActiveDirectory.Management.ADAccount</T>
    <T>Microsoft.ActiveDirectory.Management.ADPrincipal</T>
    <T>Microsoft.ActiveDirectory.Management.ADObject</T>
    <T>Microsoft.ActiveDirectory.Management.ADEntity</T>
    <T>Microsoft.ActiveDirectory.Management.ADPropertyCollection</T>
    <T>System.Object</T>
  </TN>
  <ToString>CN=vagrant-domain,CN=Users,DC=domain,DC=test</ToString>
  <Props>
    <S N="City">My City</S>
    <S N="DistinguishedName">CN=vagrant-domain,CN=Users,DC=domain,DC=test</S>
    <B N="Enabled">true</B>
    <Nil N="GivenName" />
    <S N="Name">vagrant-domain</S>
    <S N="ObjectClass">user</S>
    <G N="ObjectGUID">bdfa699e-dfb9-41ba-864d-6a2f162f579d</G>
    <S N="SamAccountName">vagrant-domain</S>
    <S N="SID">S-1-5-21-3849754078-2265128455-4044759769-1104</S>
    <Nil N="Surname" />
    <S N="UserPrincipalName">vagrant-domain@domain.test</S>
  </Props>
</Obj>
```

When using a PowerShell pipeline that is targeted against the current runspace (no serialization occurs) I can replicate this problem. What's even more interesting is that the property itself still exists when checking `$obj.PSObject.Properties` and it has the value

```powershell
$ps = [PowerShell]::Create()

$null = $ps.AddScript(@'
Get-ADUser -Identity vagrant-domain -Property City
'@)

$user = $ps.Invoke()

"Direct: '$($user[0].City)'"
"By Prop: '$(($user[0].PSObject.Properties | Where-Object Name -eq City).Value)'"
```

```
Direct: ''
By Prop: 'My City'
```

The same thing applies when running it other ways like through `Invoke-Command` but interestingly not `ForEach-Object -Parallel` even though no serialization occurs through that method. I believe remote runspaces are fine because when the ADUser object is serialized the type isn't preserved so the object that is returned is just a generic property bag.

I'm honestly not sure why this is happening so interested to hear what others may have to say.

**Comment by almhfysl284** [comment]
- [ ] 4580260105593420[_********_]()

**Comment by PaulHigin** [comment]
Does this only occur for an AD object?  I cannot run the repro, and it would be interesting to know if there is a general type of object/property that causes this problem.  For example a script property on an object may not run correctly when passed to a different runspace, due to script block runspace affinity.

**Comment by MaxAnderson95** [comment]
@PaulHigin I have not run into another type of object that this issue occurs on. I've tested your theory using a file object and it does NOT occur. 

```powershell
$File = Get-Item C:\windows\system32\drivers\etc\hosts | Select-Object Mode, LastWriteTime, Length, Name, @{N="LengthInKB";E={$_.Length/1KB}}

Write-Output "Before Runspace - The value of name is: $($File.Name)"
Write-Output "Before Runspace - The value of lengthInKB is: $($File.LengthInKB)"

$Runspace = [runspacefactory]::CreateRunspace()
$PowerShell = [powershell]::Create()
$PowerShell.runspace = $Runspace
$Runspace.Open()

[void]$PowerShell.AddScript({
    Param ($File)
    $a = "Inside Runspace - The value of name is: $($File.Name)"
    $b = "Inside Runspace - The value of lengthInKB is: $($File.LengthInKB)"
    $c = $File

    return @($a,$b,$c)
})
[void]$PowerShell.AddArgument($File)

$a, $b, $c = $PowerShell.Invoke()

$a
$b

Write-Output "After Runspace  - The value of name is: $($c.Name)"
Write-Output "After Runspace  - The value of lengthInKB is: $($c.LengthInKB)"
```

**Comment by jborean93** [comment]
I can't speak for @MaxAnderson95 but I've only just tested this with `Get-ADUser` and the `ADUser` type. Here are the details:

```powershell
> $user.PSObject.Properties | Where-Object Name -eq City


BaseObject      : CN=vagrant-domain,CN=Users,DC=domain,DC=test
Tag             :
MemberType      : Property
Value           : My City
IsSettable      : True
IsGettable      : True
TypeNameOfValue : System.String
Name            : City
IsInstance      : True


> $user.GetType()


IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    ADUser                                   Microsoft.ActiveDirectory.Management.ADAccount
```

I haven't really checked other types but in this case it's definitely the ADUser type. What's interesting is that the `City` property is an actual Property and not a `NoteProperty` or any other PowerShell ETS one AFAIK. Maybe PowerShell sees the type as [ADUser](https://docs.microsoft.com/en-us/dotnet/api/microsoft.activedirectory.management.aduser?view=activedirectory-management-10.0) and only accesses the properties on the type itself which `City` is not usually present?

```powershell
> [Microsoft.ActiveDirectory.Management.ADUser].GetProperties().Name

GivenName
Surname
UserPrincipalName
Enabled
SamAccountName
SID
DistinguishedName
Name
ObjectClass
ObjectGuid
PropertyNames
AddedProperties
RemovedProperties
ModifiedProperties
PropertyCount
Item
```

It's hard to replicate this as `Add-Member` only allows you to add a `NoteProperty` which works just fine and trying to add a [PSAdaptedProperty](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psadaptedproperty?view=powershellsdk-7.0.0) manually through `$user.PSObject.Properties.Add($adaptedProp)` fails.

**Comment by jborean93** [comment]
Just as an FYI you can workaround this issue by adding `| Select-Object *` to your cmdlet calls as that will convert the AD object to a PSObject with NoteProperties instead.

**Comment by PaulHigin** [comment]
A script property was just an example of something that **may** not run on different runspaces.  Simple scripts may run but others may not because of affinity issues (such as accessing a variable only defined in the original runspace).

There may be other reasons why an object property might not evaluate correctly in a different runspace.

Or, it may have nothing to do with the property at all.  But the fact that it seems to only repro on AD objects makes it suspect.

**Comment by jborean93** [comment]
Definitely something up with the AD cmdlets, I cannot seem to replicate it when adding a custom adapted property to an object

```powershell
$ps = [PowerShell]::Create()

$null = $ps.AddScript(@'
$obj = Get-Service -Name WinRM
$obj.PSObject.Properties.Add(($pwd.PSObject.Properties | Where Name -eq Path), $true)

$obj
'@)

$obj = $ps.Invoke()[0]

"Direct: '$($obj.Path)'"
"By Prop: '$(($obj.PSObject.Properties | Where-Object Name -eq Path).Value)'"

# Direct: 'C:\temp'
# By Prop: 'C:\temp'
```

I tried building my own adapted property but to get/set a value I need to supply an adapter which is hidden behind internal classes so I didn't bother to go any deeper.

**Comment by RipTornMist** [comment]
Ronald Leslie Ritchie  75 jasper ave smiths falls Ontario Canada k7a 4c8 613 206 7320
-------- Original message --------From: Jordan Borean <notifications@github.com> Date: 2021-01-13  2:44 p.m.  (GMT-05:00) To: PowerShell/PowerShell <PowerShell@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [PowerShell/PowerShell] Passing Active Directory Objects into a
  Runspace Stripts All Non-Default Properties (#14604) 
I can't speak for @MaxAnderson95 but I've only just tested this with Get-ADUser and the ADUser type. Here are the details:
> $user.PSObject.Properties | Where-Object Name -eq City


BaseObject      : CN=vagrant-domain,CN=Users,DC=domain,DC=test
Tag             :
MemberType      : Property
Value           : My City
IsSettable      : True
IsGettable      : True
TypeNameOfValue : System.String
Name            : City
IsInstance      : True


> $user.GetType()


IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    ADUser                                   Microsoft.ActiveDirectory.Management.ADAccount
I haven't really checked other types but in this case it's definitely the ADUser type. What's interesting is that the City property is an actual Property and not a NoteProperty or any other PowerShell ETS one AFAIK. Maybe PowerShell sees the type as ADUser and only accesses the properties on the type itself which City is not usually present?
> [Microsoft.ActiveDirectory.Management.ADUser].GetProperties().Name

GivenName
Surname
UserPrincipalName
Enabled
SamAccountName
SID
DistinguishedName
Name
ObjectClass
ObjectGuid
PropertyNames
AddedProperties
RemovedProperties
ModifiedProperties
PropertyCount
Item
It's hard to replicate this as Add-Member only allows you to add a NoteProperty which works just fine and trying to add a PSAdaptedProperty manually through $user.PSObject.Properties.Add($adaptedProp) fails.

**Comment by iSazonov** [comment]
Is Microsoft.ActiveDirectory.Management.ADAccount an COM object? I see:
```
Item                   ParameterizedProperty Microsoft.ActiveDirectory.Management.ADPropertyValueCollection Item(str...
```
Maybe it is COM interaction issue? /cc @SeeminglyScience 

Is an object cloned when passed to runspace? Maybe the issue related the cloning (in Engine or in the object)?

**Comment by SeeminglyScience** [comment]
> Is Microsoft.ActiveDirectory.Management.ADAccount an COM object? I see:
> 
> ```
> Item                   ParameterizedProperty Microsoft.ActiveDirectory.Management.ADPropertyValueCollection Item(str...
> ```
> 
> Maybe it is COM interaction issue? /cc @SeeminglyScience
> 
> Is an object cloned when passed to runspace? Maybe the issue related the cloning (in Engine or in the object)?

The AD module uses a custom adapter that just isn't registered in the new runspace.  Issue is fixed if you add `Import-Module ActiveDirectory` in the `AddScript` block.

**Comment by SeeminglyScience** [comment]
> One thing to note is the adapter used in AD is a ThirdPartyAdapter compared to my test which is a DotNetAdapter, might be another thing to look into.

@jborean93 FYI `ThirdPartyAdapter` is sort of a bridge to the public `PSPropertyAdapter` class.  You can pass the `Type` of an implementation of that class to `Update-TypeData`'s `TypeAdapter` property.

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience thanks for the explanation, it still seems weird that the property is present through `$obj.PSObject.Properties` yet you can't access it through the dot notation.

It's just sorta how it's stored. The binder looks in `PSObject._instanceMembers` which only contains explicitly added members.  You can see the adapted property in `_members` if it's already been retrieved due to caching, but that's just not where the binder is looking.
