### ISSUE TITLE
Enable Import-Module to also load Display XML in Compatibility mode

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#14600]
## Summary of the new feature/enhancement

When PowerShell 7 imports a module, it invokes compatibility mode when it finds a module not fully supported in PowerShell Core/7. This allows the cmdlets to be used and in most cases works well.

If, however, the module has display XML that helps format the output nicely, such XML is not imported. This results in less nice output. An easy workaround is to manually import the XML into the current session and then all works well.

Here is an example:

```Console
PS C:\Foo> # Import Server Manager 
PS C:\Foo> Import-Module -Name ServerManager     
WARNING: Module ServerManager is loaded in Windows PowerShell using WinPSCompatSession remoting session; please 
note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.                                                      
PS C:\Foo> # Get features and view sub-optimal output                                                                                                                            PS C:\Foo> Get-WindowsFeature -Name "*PowerShell*"

Display Name                                            Name                       Install State
------------                                            ----                       -------------
                                                        RSAT-Clustering-PowerS…        Available
                                                        RSAT-AD-PowerShell             Available
                                                        Hyper-V-PowerShell             Available
                                                        RSAT-RemoteAccess-Powe…        Available
                                                        PowerShellRoot                 Installed
                                                        PowerShell                     Installed
                                                        PowerShell-V2                    Removed
                                                        WindowsPowerShellWebAc…        Available

PS C:\Foo> # Import the XML
PS C:\Foo> $SMFolder = "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\ServerManager"
PS C:\Foo> Update-FormatData -Prepend $SMFolder\*.Format.PS1XML
PS C:\Foo> # Retest
PS C:\Foo> Get-WindowsFeature -Name "*PowerShell*"

Display Name                                            Name                       Install State
------------                                            ----                       -------------
            [ ] Failover Cluster Module for Windows Po… RSAT-Clustering-PowerS…        Available
            [ ] Active Directory module for Windows Po… RSAT-AD-PowerShell             Available
            [ ] Hyper-V Module for Windows PowerShell   Hyper-V-PowerShell             Available
            [ ] Remote Access module for Windows Power… RSAT-RemoteAccess-Powe…        Available
[X] Windows PowerShell                                  PowerShellRoot                 Installed
    [X] Windows PowerShell 5.1                          PowerShell                     Installed
    [ ] Windows PowerShell 2.0 Engine                   PowerShell-V2                    Removed
    [ ] Windows PowerShell Web Access                   WindowsPowerShellWebAc…        Available
```

## Proposed technical implementation details (optional)

Have Import module look inside the module and automatically import any Type or FormatXML.

If necessary, have a ``-ImportFormatXML`` and ``-ImportTypeXML`` switches to force the import (or deny it explicitly).

Another example of this issue is #14595

**Comment by bpayette** [comment]
A small note: IIRC compatibility mode uses implicit remoting and when we remote, we don't bring the formatting XML across because it can contain scriptblocks which opens up the possibility of code injection attacks. In this case, since we trust both ends, we could special case the scenario but we'd have to be careful not to break security for the general case. Another potential issue is that any code that is brought across could fail since it may depend on types that aren't present.

**Comment by doctordns** [comment]
I would have thought we could bring in any xml that is in System32 as an exception. It would have been nice had they all been signed. 

Having worked with many of the modules, I've seen no issues with importing the XML with respect to non-existent types. Of 
course that is not to say there isn't any.

And to mitigate the risk, what about a ``-ImportFormatXML`` switch to ``Import-Module``? By default, no xml gets imported, but if the switch is set, then it would be. That would let the user decide.

**Comment by doctordns** [comment]
BUMP:

Any chance of getting this as an experimental feature for 7.3?

I suck at C# and can't quite work out where to add the code to ImportModuleCommand.cs.

And would it be a good idea to add to the telemetry to see how many type and format XML files get imported too??
