### ISSUE TITLE
add a  -yes-like parameter to start-process 

### ISSUE THREAD

**Issue by tlsalex** [PowerShell/PowerShell#14601]
## Summary of the new feature/enhancement
Sometimes I need to make installations that based on EXE files.  usually , I just need to issue 
`Start-Process -FilePath C:\path\to\file.exe -ArgumentList  "/S" `
Then everything is on its way. Occasionally, some package does not support silent installation.
It just pop up a dialog box and let me choose yes or no.
So annoying and that's why I hope developer to add a -yes-like parameter to start-process , that then help me answer all "yes/no" to yes.

## Proposed technical implementation details (optional)
No idea, I am just a user.

**Comment by SeeminglyScience** [comment]
As someone who spends an unreasonable amount of their days fighting with bad installers, I definitely empathize with this.

There isn't a good way to implement this though.  At best it would be very inconsistent, and at worst quite dangerous.

**Comment by iSazonov** [comment]
You could experiment wit RedirectStandardInput parameter.

**Comment by SeeminglyScience** [comment]
> You could experiment wit RedirectStandardInput parameter.

OP is referring to actual dialog windows rather than console prompts.

**Comment by iSazonov** [comment]
> > You could experiment wit RedirectStandardInput parameter.
> 
> OP is referring to actual dialog windows rather than console prompts.

Who can understand them these bizarre installers? :-) Sometimes I even have to repack them.

**Comment by Knele83** [comment]
https://github.com/PowerShell/PowerShell/issues/14601#issuecomment-760152242
