### ISSUE TITLE
install-powershell.ps1 script still installs version 7.1.0, even though 7.1.1 has been released

### ISSUE THREAD

**Issue by lauxjpn** [PowerShell/PowerShell#14618]
I am getting the following message in PowerShell:

```
A new PowerShell stable release is available: v7.1.1
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.1.1
```

However, executing `iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"` still tries to install `7.1.0`:

```
VERBOSE: About to download package from 'https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x64.msi'
```

A simple `Update-PowerShell` command that reliably works is long overdue.

_Originally posted by @lauxjpn in https://github.com/PowerShell/PowerShell/issues/8663#issuecomment-760773912_

**Comment by FelixBorst** [comment]
I think the issue is, that the metadata.json under https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json

has not been updated accordingly.

**Comment by Knele83** [comment]
onedrive-api-docs@noreply.github.com

MartinGC94:Improve-completion-for-attributeshttps://github.com/PowerShell/PowerShell/issues/14601#issuecomment-760152242
Poslato sa mog uređaja Galaxy



-------- Originalna poruka --------
Od: Felix Borst <notifications@github.com>
Datum: 15.1.21. 16:02 (GMT+01:00)
U: PowerShell/PowerShell <PowerShell@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Naslov: Re: [PowerShell/PowerShell] install-powershell.ps1 script still installs version 7.1.0, even though 7.1.1 has been released (#14618)


I think the issue is, that the metadata.json under https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json has not been updated accordingly.

**Comment by Knele83** [comment]
{
  "StableReleaseTag": "v7.1.0",
  "PreviewReleaseTag": "v7.2.0-preview.2",
  "ServicingReleaseTag": "v7.0.3",
  "ReleaseTag": "v7.1.0",
  "LTSReleaseTag" : ["v7.0.3"],
  "NextReleaseTag": "v7.2.0-preview.3",
  "LTSRelease": false
}

**Comment by RubberChickenParadise** [comment]
@FelixBorst Yep, since the metadata.json was not updated, the install script still tries to install 7.1.0.  I haven't looked much further to see which tags need to be updated, just Release or the Stable Release tag.

**Comment by chenxizhang** [comment]
> I am getting the following message in PowerShell:
> 
> ```
> A new PowerShell stable release is available: v7.1.1
>    Upgrade now, or check out the release page at:
>      https://aka.ms/PowerShell-Release?tag=v7.1.1
> ```
> 
> However, executing `iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"` still tries to install `7.1.0`:
> 
> ```
> VERBOSE: About to download package from 'https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x64.msi'
> ```
> 
> A simple `Update-PowerShell` command that reliably works is long overdue.
> 
> _Originally posted by @lauxjpn in [#8663 (comment)](https://github.com/PowerShell/PowerShell/issues/8663#issuecomment-760773912)_

echo this, we need a simple way to upgrade

**Comment by doctordns** [comment]
This is a classic problem. The metadata was not updated fast enough. 
This specific issue is resolved for this release, but will probably reoccur. 
You can always check the metadata before trying to update PWSH to check that the new version and the updated meta data is in place.
 
Look at: https://gist.github.com/doctordns/b1a06f7002675ec2bf8f710d3c066182

**Comment by mklement0** [comment]
@doctordns: Once updating the metadata is made _an automated part of the release process_, the problem will go away, and that is what we should strive for, right?

**Comment by doctordns** [comment]
@mklement0 - agreed.

In the meantime, the gist noted above helps me to work out when updating the RTW, Preview, or the daily build makes sense.
