### ISSUE TITLE
VERSIONINFO for pwsh.exe reports OriginalFileName as pwsh.dll

### ISSUE THREAD

**Issue by davemcincork** [PowerShell/PowerShell#14614]
## Steps to reproduce

1. Install PowerShell 7.x on Windows.
2. Navigate to location of pwsh.exe main module (C:\Program Files\PowerShell\7\).
3. Right click on pwsh.exe and go to the Details tab.

## Expected behavior

OriginalFilename property is 'pwsh.exe'.

## Actual behavior

OriginalFilename property is 'pwsh.dll'.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
## Why this is a problem?

Some security products will flag PE files where OriginalFilename does not match the current filename.

**Comment by iSazonov** [comment]
@davemcincork It is .Net Runtime specific. Please report the issue in https://github.com/dotnet/runtime repository

**Comment by davemcincork** [comment]
@iSazonov - Thanks for getting back. I dug into this some more based on your comment above. I cloned this repo and built it locally. If I understand correctly, the issue is that 'dotnet build' generates an apphost.exe program not from the source code but from some sort of template program, and this generated program is then renamed to pwsh.exe. Is your contention that the issue causing apphost.exe to have pwsh.dll as its OriginalFileName has nothing to do with the way the PowerShell build is configured?

**Comment by iSazonov** [comment]
@davemcincork Currently .Net does not allow us configure this. I see some related issues in .Net Runtime repository. You could discuss the issue there and maybe contribute there.
