### ISSUE TITLE
powershell offline install on Centos 7.1

### ISSUE THREAD

**Issue by DevOps-zhuang** [PowerShell/PowerShell#14617]
## Steps to reproduce

1, download powershell 7.1 page, powershell-7.1.0-1.rhel.7.x86_64.rpm, from https://github.com/PowerShell/PowerShell/releases/latest

2, copy the rpm to one machine without connection to github. like offline machine.

3, try to install the powershell with command 'sudo yum install powershell-7.1.0-1.rhel.7.x86_64.rpm', it failed with module error.

the simlar steps works for windows powershell installation. so any suggestion? we doubt the owershell-7.1.0-1.rhel.7.x86_64.rpm doesn't include all modules. thanks.

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by iSazonov** [comment]
Do you read and follow install docs?

**Comment by tingting-sun** [comment]
We followed the install doc here https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#centos-7
