### ISSUE TITLE
Update Microsoft Store version of PowerShell

### ISSUE THREAD

**Issue by pratikpc** [PowerShell/PowerShell#14615]
Currently [Microsoft Store has PowerShell 7.1.0](https://www.microsoft.com/en-in/p/powershell/9mz1snwt0n5d)

Today, PowerShell 7.1.1 was released.

Would it be possible to update the Microsoft Store version?

Would it be possible to automate the Microsoft Store releases?

**Comment by kilasuit** [comment]
@pratikpc there is a potential 3 day lead time for the release on here to be pushed through the windows store publishing checks as per previous issues raised on this 
like https://github.com/PowerShell/PowerShell/issues/13615 & https://github.com/PowerShell/PowerShell/issues/7730 particularly the comment https://github.com/PowerShell/PowerShell/issues/7730#issuecomment-689732223 

Can you please close this as there's nothing we can do to change this and you will just need to wait it out (like I am) I'm afriad

**Comment by pratikpc** [comment]
@kilasuit thank you

>   A new PowerShell stable release is available: v7.1.1
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.1.1

I just received this message and thought something was wrong

I had no idea!!
