### ISSUE TITLE
Invoke-WebRequest to show expected download size and more human readable format (MB/GB instead of Bytes)

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#14610]
## Summary of the new feature/enhancement

Currently, users of `Invoke-WebRequest` do not know how much they have downloaded because a big Byte number gets displayed and due to the digits not being mono-spaced, I cannot even attempt to count digits whilst the number changes every second. Also, I have no progress bar to tell me how much it needs to download.

## Proposed technical implementation details (optional)

[ByteSize](https://www.nuget.org/packages/Bytesize) is a small (14KB) library to better display human readable file sizes but as the problem is quite simple, it was decided to not introduce a dependency but rather just hand-code it instead. Because PowerShell treats `1 KB` as 1024, it should probably use 1024 as the base for KB, MB, etc.

I suggest to have one significant digit after after the comma starting with KB and increase the number of significant digits by 1 for MB, GB, etc.

PR here: https://github.com/PowerShell/PowerShell/pull/14611

**Comment by ktechmidas** [comment]
This would be *really* nice to have

**Comment by bege10** [comment]
A true progress bar with this information would be very helpful:

- Download size as in (Invoke-WebRequest $url -Method Head).Headers.'Content-Length'
- Already downloaded as described in OP
- Percentage downloaded.

**Comment by DWAK-ATTK** [comment]
Some of my server setup and automation tasks rely on Invoke-Webrequest.  A progress bar would be nice, but I would be content with some human-readable "bytes downloaded" display.  "bytes" is just not a human-readable unit of measure when you are talking about MB-GB file sizes.  At least not for this human.

So this is me piling on.  Yes, please implement this request.
