### ISSUE TITLE
Feature Request: add `which` command to show where the path is of a command

### ISSUE THREAD

**Issue by Banyc** [PowerShell/PowerShell#14622]
## Summary of the new feature/enhancement

`Where` is the alias of `Where-Object`. Thus, adding `which` to act as the alias of `where.exe` is a better choice.

## Proposed technical implementation details (optional)

References:

- <https://stackoverflow.com/a/65148/9920172>
- <https://superuser.com/a/1397265>

**Comment by DHowett** [comment]
As an alternative, you can `Get-Command blah | Select Path`.

**Comment by jborean93** [comment]
Using which wouldn’t be a good idea as it’s a  native binary on most Unix systems. I feel like get-command is the way to do this in PowerShell and there shouldn’t be an alias. You are more than free to our one in your own profile though.

**Comment by Banyc** [comment]
## This is my solution

Add the following lines in `profile.ps1` under `document/PowerShell` folder:

```powershell
New-Alias which Get-Path
function Get-Path ($command)
{
    Get-Command $command | Select Path
}
```
