### ISSUE TITLE
Can't install PS7 on Windows 7

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#14631]
I'm trying to install PowerShell-7.1.1-win-x86.msi on my notebook. Has Intel Atom CPU and Windows 7 Starter Version 6.1 build 7600. I get this error:

![](https://i.imgur.com/V9nd885.png)

PowerShell requires the Universal C Runtime to be installed to enable remoting over WinRM. You can find a download link to it here: https://aka.ms/pscore6-prereq

Any idea how to fix that?

**Comment by superbonaci** [comment]
I can't install Windows 7 SP1 due to lack of drivers.

**Comment by jborean93** [comment]
So did you install the universal C runtime? In your link there is the text that tells you where to get it

> Install the [Universal C Runtime](https://www.microsoft.com/download/details.aspx?id=50410) on Windows versions predating Windows 10. It's available via direct download or Windows Update. Fully patched systems already have this package installed.

**Comment by superbonaci** [comment]
@jborean93 which specific file do you recommend?

**Comment by jborean93** [comment]
In the URL you shared (and my quoted response) it says Install the Universal C Runtime. The Universal C Runtime is a link to the Universal C Runtime that you need to install.

**Comment by superbonaci** [comment]
Downloaded the file `WindowsUCRT.zip`, size `8.237.933 bytes`. Contents are these:

````
    Directory: C:\Users\pp\Desktop\WindowsUCRT


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-----        23/10/2015     17:46     250148 sdk_license.rtf
-----        20/11/2015     13:52      86038 Windows UCRT ReadMe.rtf
-----        11/12/2015     17:50    1136143 Windows6.0-KB3118401-x64.msu
-----        11/12/2015     17:50     700047 Windows6.0-KB3118401-x86.msu
-----        12/12/2015     18:29    1047061 Windows6.1-KB3118401-x64.msu
-----        12/12/2015     18:29     639386 Windows6.1-KB3118401-x86.msu
-----        15/12/2015      8:40     546756 Windows8-RT-KB3118401-arm.msu
-----        15/12/2015      8:50    1380813 Windows8-RT-KB3118401-x64.msu
-----        15/12/2015      8:45     631624 Windows8-RT-KB3118401-x86.msu
-----        20/11/2015      9:47     544771 Windows8.1-KB3118401-arm.msu
-----        20/11/2015     10:00    1015961 Windows8.1-KB3118401-x64.msu
-----        20/11/2015      9:54     607985 Windows8.1-KB3118401-x86.msu
````

I get for all of them this error:

![](https://i.imgur.com/laT1mZn.png)

Windows Update Standalone Installer
The update is not applicable to your computer.

**Comment by superbonaci** [comment]
@iSazonov why do you mark as properly answered when was not. Obviously there are compatibility issues.

**Comment by jborean93** [comment]
If you can't install the update as it's not applicable then there's nothing PowerShell can do. Update your OS to a newer version, you can't keep using end of life products and still expect new software to work on them.

**Comment by superbonaci** [comment]
@jborean93 Ideally Service Pack 1 should work, but can't due to lack of a certain driver. PowerShell installer should know better and not recommend me an update that doesn't work.

**Comment by iSazonov** [comment]
> @iSazonov why do you mark as properly answered when was not. Obviously there are compatibility issues.

The repository is for PowerShell developers and only bugs can be addressed here. To get a support please use other resources from MSFT or community.

**Comment by superbonaci** [comment]
> You could skip the installer step and enable remoting later manually.

What is that and how do I do it?

**Comment by iSazonov** [comment]
See docs https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/enable-psremoting?view=powershell-7.1
