### ISSUE TITLE
Ubuntu 16.04 will reach EOL on April 30, 2021

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#14654]
This is to notify and discuss what happens when Ubuntu 16.04 will reach EOL on April 30, 2021. Technically speaking, Canonical also provides extended security maintenance after that, but that is a special enterprise agreement, therefore I assume that PowerShell will stop support for Ubuntu 16.04 on April 30, 2021 as per support policy: https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7.1#unsupported-platforms
Can you please confirm my understanding is correct? Personally I do not see an issue with that but just wanted it to be confirmed.

Here is an (incomplete) list of docs that definitely need updating after that:
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md
- https://github.com/PowerShell/PowerShell/blob/master/README.md
- https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md

**Comment by iSazonov** [comment]
> Can you please confirm my understanding is correct? Personally I do not see an issue with that but just wanted it to be confirmed.

I can confirm. 
A rule is we supports only version which .Net supports.

**Comment by daxian-dbw** [comment]
DSC has a dependency on 16.04 and that won't change in the foreseeable future. The DSC team even talked with .NET team to have  them support .NET 5 on Ubuntu 16.04, see https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux. So I believe we will keep supporting 16.04 until that changes. /cc @bagajjal to chime in.

**Comment by xtqqczze** [comment]
> DSC has a dependency on 16.04 and that won't change in the foreseeable future. The DSC team even talked with .NET team to have them support .NET 5 on Ubuntu 16.04, see https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux. So I believe we will keep supporting 16.04 until that changes. /cc @bagajjal to chime in.

Update: Support for Ubuntu 16.04 was removed in .NET [v5.0.6](https://github.com/dotnet/core/releases/tag/v5.0.6), released 2021-05-11.

See: https://github.com/dotnet/core/blob/06bc572c921014dc77c0d1217861ce10d1cd382b/release-notes/5.0/5.0-supported-os.md

**Comment by xtqqczze** [comment]
Opened #15628 for CI.

**Comment by bagajjal** [comment]
DSC uses latest powershell 7.2.0.preview3 which uses dotnet 6. dotnet 6 support ubuntu 16.04
https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux

**Comment by xtqqczze** [comment]
> > DSC has a dependency on 16.04 and that won't change in the foreseeable future. The DSC team even talked with .NET team to have them support .NET 5 on Ubuntu 16.04, see https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux. So I believe we will keep supporting 16.04 until that changes. /cc @bagajjal to chime in.
> 
> Update: Support for Ubuntu 16.04 was removed in .NET [v5.0.6](https://github.com/dotnet/core/releases/tag/v5.0.6), released 2021-05-11.
> 
> See: https://github.com/dotnet/core/blob/06bc572c921014dc77c0d1217861ce10d1cd382b/release-notes/5.0/5.0-supported-os.md

In response to dotnet/core#6400, it has been clarified that Ubuntu 16.04 is still supported for .NET 5, see https://github.com/dotnet/core/commit/adf939dae4f3b76327dc2314a53f276a86a6fd25, but that a decision is still yet to be made for .NET 6.

**Comment by xtqqczze** [comment]
`dotnet/core` maintainers have confirmed that Ubuntu 16.04 is still supported in .NET [2.1](https://github.com/dotnet/core/commit/a9083195d42a6cebb2746b0fa963024affac73a0), [3.1](https://github.com/dotnet/core/commit/a9083195d42a6cebb2746b0fa963024affac73a0) and [5.0](https://github.com/dotnet/core/commit/f78bf1f80cb5a3124b0dc2b6fefe2855a99f1677) despite being end-of-life, as it still sees significant usage,
