### ISSUE TITLE
Running command through alias does not display colors

### ISSUE THREAD

**Issue by dancojocaru2000** [PowerShell/PowerShell#14659]
For example, I prefer using [`exa`](https://the.exa.website/) instead of `ls` or `Get-ChildItem`. I therefore wrote the following line in my PowerShell profile:

```powershell
New-Alias -Name ls -Value exa
```

However, when I run `ls` after that, the output doesn't contain colors. The output does contain colors when running `exa` directly.

Does alias affect isatty detection (which I suspect might be the culprit)?

**Comment by daxian-dbw** [comment]
I cannot reproduce the issue on Ubuntu 18.04 with the 7.1.0 version of PowerShell:

![image](https://user-images.githubusercontent.com/127450/106063797-a3e16b00-60ad-11eb-8ee0-a255c07768fc.png)

@dancojocaru2000 Am I missing anything in my repro? Can you provide more information about the environment?

**Comment by dancojocaru2000** [comment]
...apparently it fixed itself. On one hand, great, not a problem anymore. On the other hand, sorry for disturbing.
