### ISSUE TITLE
Feature Request: Consider including System.Collections.Generic namespace by default

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#14651]
## Summary of the new feature/enhancement

Almost every one of my scripts/modules starts with `using namespace system.collections.generic` for the use of the List and Dictionary types in order to have strongly typed and performant versions of these to help avoid type and casting mistakes.

Since `System` is already implicitly included in the namespace, there is precedence for this.

I understand this may open the floodgates of "well what about this generic namespace too?" but I think this is a reasonable "base" to include to allow for the very common collection and dictionary formats we are "supposed" to use instead of arraylist and hashtable since .NET 2.0, even though powershell still natively uses those for compatibility reasons.

The only potential breaking change I could see here is a collision with a custom defined name type, but even then powershell class names like `List` would take precedence and override the implicit definition.

## Proposed technical implementation details (optional)

Have System.Collections.Generic added as a `using namespace` by default.

Alternatively register [list] and [dictionary] as new type accelerators, however the "easy" way of doing this in userspace was made private a while ago.

Related to but not a dupe of #10862, it is simpler in scope.

**Comment by JustinGrote** [comment]
Related to but not a dupe of https://github.com/PowerShell/PowerShell/issues/10862, it is simpler in scope.

**Comment by rkeithhill** [comment]
WG-Engine discussed this today.

While this issue with adding `using namespace System.Collections.Generic` is a sore point for you, for others the sore point may be with the `System.Diagnostics` or `System.Management.Automation.*` or `System.Linq` namespaces.  Any additional types we add automatically, increase the odds of a type name collision.  So, adding the requested namespace automatically would likely require a way to disable (not add) the namespace (automatically).  And there are also runtime costs associated with adding more types from more namespaces.  

The team feels that the current mechanism i.e., `using namespace <some.namespace>` is sufficient - providing a way to access the types that each individual scripter is interested in using without having to supply fully qualified type names.

**Comment by JustinGrote** [comment]
@rkeithhill understood, I added my justification to assuage these concerns but I respect the team's decision.
