### ISSUE TITLE
Distribution Support Request: Alpine 3.13 arm32

### ISSUE THREAD

**Issue by mthalman** [PowerShell/PowerShell#14667]
## Details of the Distribution

- Name of the Distribution: Alpine
- Version of the Distribution: 3.13
- Package Types
    - [ ] Deb
    - [ ] RPM
    - [x] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request): arm32
- The following is a requirement for supporting a distribution **without exception.**
    - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by mthalman** [comment]
This is related to https://github.com/PowerShell/PowerShell/issues/12937.

The .NET team plans on producing Alpine arm32 and arm64 Docker images for the .NET 6.0 SDK (https://github.com/dotnet/dotnet-docker/issues/2504).  Being able to include PowerShell in that image would be good in order to make it consistent with the other architectures and distros.

**Comment by mthalman** [comment]
cc @adityapatwardhan

**Comment by TravisEz13** [comment]
cc @adityapatwardhan, we need alpine ARM support before we can do this.

**Comment by tigerinus** [comment]
https://github.com/dotnet/runtime/issues/45343

Can we do this now?

**Comment by mthalman** [comment]
Pinging this to appease the bot.

**Comment by rhubarb-geek-nz** [comment]
Is this still required? Alpine 3.18 provides PowerShell 7.3.4 for arm32, arm64 and x64 in its main repository.

```
$ sudo apk add powershell
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/armv7/APKINDEX.tar.gz
fetch https://svn.rhubarb.geek.nz/pkg/alpine/3.18/armv7/APKINDEX.tar.gz
fetch https://packages.rhubarb.geek.nz/alpine/3.18/armv7/APKINDEX.tar.gz
(1/8) Installing icu-data-full (73.2-r2)
(2/8) Installing dotnet-host (7.0.14-r0)
(3/8) Installing dotnet7-hostfxr (7.0.14-r0)
(4/8) Installing lttng-ust (2.13.5-r2)
(5/8) Installing dotnet7-runtime (7.0.14-r0)
(6/8) Installing libpsl-native (7.3.1-r0)
(7/8) Installing powershell (7.3.4-r1)
(8/8) Purging icu-data-en (73.2-r2)
Executing busybox-1.36.1-r5.trigger
OK: 334 MiB in 97 packages
```

**Comment by mthalman** [comment]
> Is this still required? Alpine 3.18 provides PowerShell 7.3.4 for arm32, arm64 and x64 in its main repository.

The latest release at https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0 only lists a `linux-musl-x64` artifact for musl. In order for this issue to be resolved, I would expect an `linux-musl-arm32` artifact to be listed there.

**Comment by theJasonHelmick** [comment]
Alpine 3.13 is no longer supported by Alpine.

**Comment by theJasonHelmick** [comment]
Closed as unplanned.
