### ISSUE TITLE
add reduce operator

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14661]
hello Guys !

the idea to add  another structure to simplify code execution for example:

```
# is the same  1+2+3+4+5+6+7+8+9+10
PS  > :[+] 1..10
55

# use all arithmetic operator and possibility to store in variable
PS > $result = :[-] 10,32,54
PS > $result

# possibility to add personal reduce filter
PS > filter MyPersonalFilterToListAllWordBeginningByLetterh {
          if($_.tostring().StartsWith('h')) {
                $_
        }
    } 
PS> :[:MyPersonalFilterToListAllWordBeginningByLetterh] @( 'hello','lol','test','fooooo' )
hello 
```

**Comment by doctordns** [comment]
What real-world problem does this proposed operator solve?

**Comment by iSazonov** [comment]
We already have questions to add support for LINQ and extension methods which is more promising.

**Comment by daxian-dbw** [comment]
It's hard to see the usefulness of the proposed syntax. I agree that it's more desired to make static extension methods easy to use in PowerShell.

**Comment by rjmholt** [comment]
I think this has already been discussed in https://github.com/PowerShell/PowerShell/issues/8098 too. See that issue for some definitions of functions that work like the proposed operator.
