### ISSUE TITLE
GCI of extended-length path "\\?\" returns incorrect items

### ISSUE THREAD

**Issue by mccarrm** [PowerShell/PowerShell#14668]
## Steps to reproduce

```powershell

Get-ChildItem -LiteralPath '\\?\D:\'
Get-ChildItem -LiteralPath '\\?\UNC\server\share'

```

## Expected behavior

```none
Gets the items in the specified location.
```

## Actual behavior

```none
Gets the items in the root of the current drive (e.g. C:\).  Same cmdlet in PSVersion 5.1 gets the items in the specified location.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
Related: #10805

The short of it:

* In PowerShell Core, long paths are supported _by default_, so the `\\?` opt-in prefixes are never needed.

* However, they should still be _supported_, not least for the sake of cross-edition code - and currently, they're mostly not.

**Comment by daxian-dbw** [comment]
Definitely a bug that needs to be fixed.

**Comment by AlphaR3C0N** [comment]
Another use case for this old syntax is working with volumes that don't have drive letters (I know it's easy enough to assign letters but in some cases, you don't want to).
![Screenshot 2021-06-09 170018](https://user-images.githubusercontent.com/58408155/121303444-309b1000-c94f-11eb-858d-e1a6108582d7.png)

**Comment by MartinGC94** [comment]
This seems to be working now so I guess this issue can be closed.
