### ISSUE TITLE
Get-Process shows truncated result on macOS

### ISSUE THREAD

**Issue by skyline75489** [PowerShell/PowerShell#14666]
## Steps to reproduce

```powershell
Get-Process
```

## Expected behavior

Not truncated, obviously.

## Actual behavior

Some of the output:

```none
      0     0.00       1.15      14.39   74801   1 com.apple.hiser
      0     0.00       9.59       0.09   46341   1 com.apple.iClou
      0     0.00       5.77      50.40   27529   1 com.apple.quick
      0     0.00      20.66     566.22   75150   1 com.apple.Safar
      0     0.00       0.01       0.21   88922 …22 com.apple.Safar
      0     0.00       7.35      17.64   66373   1 com.apple.sbd
      0     0.00       5.14       2.07    1721   1 com.apple.speec
      0     0.00       0.86       1.98   18265 …65 com.apple.WebKi
      0     0.00       0.86       1.86   40112 …12 com.apple.WebKi
      0     0.00       0.89       1.74   40191 …91 com.apple.WebKi
      0     0.00       0.91       1.80   40661 …61 com.apple.WebKi
      0     0.00       0.90       2.26   45405 …05 com.apple.WebKi
      0     0.00       0.87       0.29   92133 …33 com.apple.WebKi
      0     0.00       2.69      11.06     486   1 com.paragon-sof
```

## Environment data

```none
PowerShell 7.1.0
macOS 10.15.5
tested on both Terminal.app & iTerm2
```

The size of the terminal window does not seem to matter. Even if I use fullscreen window, the issue is still there.

**Comment by mklement0** [comment]
My understanding is superficial, but here's a few pointers:

* There appears to be a macOS system API that limits process (executable) names to 15 characters (which affects calls such as `pgrep -l com.apple.CharacterPicker`). However, this limitation _can_ be overcome, as evidenced by the output from the `ps` utility.

* It is [`System.Diagnostics.Process`](https://docs.microsoft.com/en-US/dotnet/api/System.Diagnostics.Process) that reports the truncated name, so PowerShell is only the messenger here, so I suggest closing this issue and opening one at https://github.com/dotnet/runtime/issues

Separately, an improvement worth considering is to show the whole _command line_ as part of the default output formatting, not just the process name - the way the native `ps` utility already does - this would require opening a separate issue of type "Feature Request / Idea"; also, the `.CommandLine` property doesn't currently work on macOS: see #13943.

**Comment by JamesWTruher** [comment]
@mklement0 has it correct, this is an issue with the underlying `dotnet` API. Which can be seen here:
```
[System.Diagnostics.Process]::GetProcesses().foreach({$_.Name.Length})|measure -max

Count             : 600
Average           : 
Sum               : 
Maximum           : 15
Minimum           : 
StandardDeviation : 
Property          : 
```
Further, there are a number of other issues specifically with `get-process` on mac. A number of process names _cannot_ be reported because the caller does not have privilege. FWIW, on Mac `ps` is `setuid root` which why you can see them from `/bin/ps`

From my perspective, this is an external issue which should be addressed in the dotnet layer
