### ISSUE TITLE
Feature Request: Reset PowerShell to its default color settings

### ISSUE THREAD

**Issue by shridpant** [PowerShell/PowerShell#14664]
## An option in "Windows Powershell" properties to revert to the default color settings

Windows Powershell is an amazing tool. It's highly customizable, especially in terms of its visuals. However, once the users have opted to customize Powershell, it becomes really difficult to revert to the default color settings. Unless the users remember those default settings, **there isn't an easy way to go back**.

This led me (and, probably, other users as well) to some **shady solutions on the web** that require downloading and replacing some original files with those on their websites.

Would really love to see an option that says "Reset to default"/"Reset Settings" on Windows Powershell properties.

**Comment by DHowett** [comment]
You could use ColorTool from the official console and terminal repository at [microsoft/terminal](https://github.com/microsoft/terminal). We support that tool (as it was created by and bears a code signature from Microsoft).

**Comment by iSazonov** [comment]
The repository is for PowerShell Core. We can do nothing for Windows PowerShell here.
