### ISSUE TITLE
Static library (.a) files in the Linux Powershell payload

### ISSUE THREAD

**Issue by bagajjal** [PowerShell/PowerShell#14674]
Linux Powershell payload has static library files (.a files) which are used for compilation.
These files are not required at runtime. Removing them will save 7 MB .

-rwxr--r-- 1 balu balu 1M Oct 19 11:31 libSystem.Security.Cryptography.Native.OpenSsl.a
-rwxr--r-- 1 balu balu 1M Oct 19 11:31 libSystem.Net.Security.Native.a
-rwxr--r-- 1 balu balu 1M Oct 19 11:31 libSystem.Native.a
-rwxr--r-- 1 balu balu 4M Oct 19 11:31 libSystem.IO.Compression.Native.a

**Comment by daxian-dbw** [comment]
See https://github.com/dotnet/runtime/issues/47564.
The `.a` files are needed by mobile versions of .NET 5, like for iOS/tvOS/watchOS, see https://github.com/dotnet/runtime/issues/43949 and https://github.com/dotnet/runtime/issues/43943.

They are not needed by self-contained applications.
