### ISSUE TITLE
Wait-Job fails quietly with -Timeout 0 instead of exhibiting polling behavior

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14675]
`Wait-Job` waits synchronously and, by default, indefinitely until the given job(s) terminate.

The `-Timeout` parameter can be used to stop waiting after a given number of seconds.
If the job(s) haven't terminated by then, the command quietly returns and outputs nothing; if they have, their job-information objects are output.

However, even though `-Timeout 0` is accepted, it doesn't work as expected: Even if the given job(s) have already terminated, the job-information object(s) are _not_ output.

If `Wait-Job -Timeout 0` worked as intended, it could be used in loops for momentary periodic _polling_ of job states, leaving the loop free to perform other tasks between polling attempts (while `Wait-Job -Timeout 1` does work, it introduces an unnecessary 1-second blocking period; the manual alternative is quite cumbersome: 
`$job.State -in 'Completed', 'Failed', 'Stopped', 'Disconnected', 'Suspended'`).

Note that, by contrast, `Wait-Process -Timeout 0` _does_ work as intended. 

## Steps to reproduce

```powershell
# Start a background job.
$jb = Get-Date &
# Synchronously wait for it to finish.
Wait-Job $jb

# !! This fails unexpectedly, even though the job by definition has terminated and should be returned.
# !! If you used -Timeout 1 instead, the test would succeed.
Wait-Job $jb -Timeout 0 | Should -Be $jb
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because `-Timeout 0` always results in _no_ output, even when the job has terminated already.

```none
Expected System.Management.Automation.PSRemotingJob, but got $null.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by SteveL-MSFT** [comment]
The [code](https://github.com/PowerShell/PowerShell/blob/20401c95836ba94bb0302e1be66371a93fb44a19/src/System.Management.Automation/engine/remoting/commands/WaitJob.cs#L262) does specifically handle a timeout of 0 by explicitly doing nothing.  [Wait-Process -Timeout 0](https://github.com/PowerShell/PowerShell/blob/9aede0558a4c26a4f0769a51d8f0bb3e5fcfa744/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L1023) uses a different way to manage the timeout where `WaitOne(0)` has well defined behavior which explains the difference in behavior.

**Comment by TravisEz13** [comment]
remoting working group: The current behavior is unexpected.  If the parameter value is basically invalid, we should emit an error or warning, if that is the design. 

The idea of returning the object if it's ready seem better?

**Comment by mklement0** [comment]
Let me restate what the initial post proposes:

Making `-Timeout 0` perform  _momentary polling_ is useful behavior that enables _periodic polling in a loop_ (that does other things), and would mirror the existing, useful behavior of `Wait-Process -Timeout 0`.

**Comment by reduckted** [comment]
This is still a problem in 7.4.0
