### ISSUE TITLE
Format-Table unexpectedly distributes remaining line width evenly among columns without a custom width

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14677]
Note: This bug affects Windows PowerShell too.

If columns with custom column widths are specified - which due to a related bug currently only takes effect if the _first_ column has one; see #14676 - the remaining columns without a custom-width specifications are unexpectedly auto-assigned a width based on _evenly dividing the remaining line length_ rather than on the width of the values (received within the first 300 msecs.), as usual.

Note: While this could be conceived of as a _feature_, it certainly shouldn't be the _default_ behavior and would require _opt-in_ via a switch yet to be introduced.

## Steps to reproduce

```powershell
$obj = [pscustomobject]@{ a='12345'; b='B'; c='C' }

# Get the formatting with the default column widths
$a = $obj | Format-Table -Property a, b, c | Out-String

# Get the formatting with the first column explicitly set to its actual width, which should result in the same formatting.
# !! However, this causes the remaining columns to each be set to half the width of the remaining line.
$b = $obj | Format-Table -Property @{ e='a'; width=5 }, b, c | Out-String

$a | Should -Be $b
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails due the behavior described above; print `$a, $b` to see the difference.

```none
Expected strings to be the same, but they were different. Expected length: 350 Actual length:   32 Strings differ at index 9. Expected: '...   b      ...' But was:  '\na     b c\n-     - -\n12345 B
     | C\n\n'
```

With a (simulated) console-window width of `50` (via `Out-String -Width 50`), printing `$a, $b` yields:

```none
a     b c
-     - -
12345 B C

a     b                      c
-     -                      -
12345 B                      C
```

Note that specifying `-AutoSize` avoids the problem.

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by ericleigh007** [comment]
HI guys,
Are users not expected to use Format-table?  I'm respectfully asking if there is a timeframe in which we can expect this to get fixed?
Wish I had the time to look myself, but I'm swamped here.
Thanks!
