### ISSUE TITLE
Format-Table ignores custom columns widths except in the first column

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14676]
Related: #14677

Note: This bug affects Windows PowerShell too.

## Steps to reproduce

```powershell
$obj = [pscustomobject] @{ a='A'; b='1234567890'; c='C' }

# OK - custom width is in the *first* column.
$obj | Format-Table -Property @{ e='b'; width = 5 }, c | Out-String | Should -Match '1234…'

# !! BROKEN: custom width is (only) in a column *other* than the first:
$obj | Format-Table -Property a, @{ e='b'; width = 5 }, c | Out-String | Should -Match '1234…'
```

## Expected behavior

Both tests should succeed.

## Actual behavior

The 2nd test fails, because the custom column width was unexpectedly not applied.

```none
Expected regular expression '1234…' to match ' a b          c - -          - A 1234567890 C  ', but it did not match.
```

Note that, similarly, custom widths in _later_ columns only take effect if one was specified for and successfully applied to the first column.

## Environment data

```none
PowerShell Core 7.2.0-preview.2
```

**Comment by zett42** [comment]
> Note that, similarly, custom widths in later columns only take effect if one was specified for and successfully applied to the first column - except, seemingly, for the last column, for which a custom width is seemingly always ignored.

I can't repro the bug for the last column, e. g. this test succeeds (PS 7.1 and 7.2.0-preview.2):

    $obj = [pscustomobject]@{ a = '123456'; b = '123456'; c = '123456' } 
    $table = $obj | Format-Table -Property @{ e='a'; width=5 }, @{ e='b'; width=5 }, @{ e='c'; width=5 }
    $table | Out-String | Should -Match '1234… 1234… 1234…'

**Comment by mklement0** [comment]
I appreciate the corrections, @zett42 - I've updated the title and removed the claim about the last column (I must have gotten myself confused while testing).

**Comment by mklement0** [comment]
On a meta note, @zett42: I've started _hiding_ comments that are no longer relevant, such as my feedback to you that your suggested corrections have been implemented. Can I ask you to do the same for your original comment?. Especially in threads that become long over time I think it's important to keep the noise down. (Of course I'll hide this comment eventually too.)
