### ISSUE TITLE
Using Group Policy to Set Console Session Configuration Crashes PowerShell 7.1.1

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#14679]
I have set the Console Session Configuration GPO settings and logon to a server with a user id. The policy is delivered successfully.

However, when I run a non-elevated console it starts up and then disappears. This results in an Event Log error.

## Steps to reproduce

1. Create a new GPO, and set the Console Session Configuration policy. The end point specified is PowerShell.7
 Here is a pic

![2021-01-28_21-28-43](https://user-images.githubusercontent.com/3630329/106201211-09b61b80-61b0-11eb-9f8a-1d78d9dbbf0e.png)

2. Login and run an ordinary PowerShell console. The console starts up and dissapears.
3. View the event log error:
![2021-01-28_21-32-43](https://user-images.githubusercontent.com/3630329/106201631-a24c9b80-61b0-11eb-92f1-abe3e81396f1.png)

I have tried using both the session configuration name and the full URI. Both fail with the same error code.

## Expected behavior

I expected console to finish starting up and allowing me to use the console with the defined endpoint.

## Actual behavior

Running a console - starts up then disappears. On one occasion I actually got the console started, but the next time I tried it fails.

## Environment data

PS C:\Windows\System32> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.20285
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```none

```

**Comment by jborean93** [comment]
Based on the error it looks like it's actually using WSMan to connect to localhost and connect to the PS configuration you desire. The Windows WinRS client effectively stops you from doing that from an unelevated instance because it is a way to bypass UAC (even though UAC isn't a security boundary).

**Comment by doctordns** [comment]
That may be why the error occurs as it does - but it begs the question: how do you use this GPO setting to require a specific end-point? 

If what you say is true, then there should be an error message generated at failure - a window just disappears seems incorrect. And can we have the error in the event log be more actionable? Just popping an error message seems less than desirable. 

if this POLICY can not actually be used to configure a console endpoint for a given user, then the documentation should say so. It currently does not, and it does not say which endpoint should be in the policy - the name or the URI.

A particular use case here is for JEA sessions. If user JerryG logs into a DC, his PowerShell session should be a JEA-based session, or possibly a session that has had a start up script defined. I want to set, by policy, that the user does not use the normal endpoint. 

If this policy can not be used to configure a default console for non-elevated cases, I am not entirely sure what the purpose of this GPO policy is?

**Comment by jborean93** [comment]
Honestly I'm not sure, I wouldn't have thought using WSMan would be necessary at all but the whole configuration endpoint/JEA is highly tied into the WSMan stack so I'm also not surprised it is using it. When you look at the default options you can see the following groups have been allowed to access the endpoint

![image](https://user-images.githubusercontent.com/8462645/106346639-3aa76500-6304-11eb-8699-00b3183beb61.png)

* Administrators
* Remote Management Users
* INTERACTIVE

Obviously your account does not have the `Administrators` group as it isn't an admin. Typically a WSMan logon will result in a `NETWORK` logon but after testing it does look like PowerShell is passing down the [WSMAN_OPTION_USE_INTERACTIVE_TOKEN ](https://github.com/PowerShell/PowerShell/blob/2784add414393b0ecab798055cfbac0d363c1c1e/src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs#L521) that tells WSMan to use the current interactive token when it spawns the shell.

![image](https://user-images.githubusercontent.com/8462645/106346764-0b452800-6305-11eb-9b89-2c554e598078.png)

So going by this logic than a non-admin should have access to that endpoint as it will be spawned by an interactive logon but this is where I think WSMan has changed recently. It seems like it no longer allows a loopback logon if the caller is not an admin. You can even see it in action when you try and connect back to localhost with `Invoke-Command`

![image](https://user-images.githubusercontent.com/8462645/106347424-0c2c8880-630a-11eb-89c3-01122e928f9b.png)

It does seem like `-EnableNetworkAccess` can get past this so I don't now why `WSMAN_OPTION_USE_INTERACTIVE_TOKEN ` isn't also applied for this use case, someone more knowledable in the setup will probably have to answer that.

As for why the policy exists I think it may be a historical policy and recent changes make it less useful. The actual change occurred only in 2019 https://devblogs.microsoft.com/powershell/windows-security-change-affecting-powershell/.

**Comment by SteveL-MSFT** [comment]
@jborean93 is correct that currently endpoint session configuration is tied to WinRM (hopefully we'll have opportunity to support it via SSH in the future).  It also seems that the tightened security in Windows makes this capability much less useful for non-admins.  I don't think there's anything we can do for this in the meantime.

**Comment by SteveL-MSFT** [comment]
Sorry, didn't mean to just close.
