### ISSUE TITLE
Feature Request: Get-Command -syntax should display the parameter set name for each parameter set

### ISSUE THREAD

**Issue by plastikfan** [PowerShell/PowerShell#14685]
## Summary of the new feature/enhancement

Trying to solve parameter binding issues for a command's parameters is difficult, because generally the error message that is returned generally has nothing in it to help you resolve the problem.

Typically, you'll see something like this:

>  ParameterBindingException: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

This is not helpful. As an alternative, the user can try to use get-command -syntax. The problem with this however is that it returns a bunch of parameter set info for all sets defined for a command, except that for each set, the parameter set name is not shown. Eg:

```powershell
λ get-command Rename-Many -syntax

Rename-Many -underscore <FileSystemInfo> -Pattern <array> [-Drop <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Pattern <array> -Anchor <array> -End [-Drop <string>] [-Relation <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Pattern <array> -Anchor <array> -Start [-Drop <string>] [-Relation <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Pattern <array> -Anchor <array> [-Drop <string>] [-Relation <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Pattern <array> -End [-Drop <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Pattern <array> -Start [-Drop <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Prepend <string> [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]

Rename-Many -underscore <FileSystemInfo> -Append <string> [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]
```

And the corresponding faulty definition:

```powershell
  param
  (
    [Parameter(Mandatory, ValueFromPipeline = $true)]
    [System.IO.FileSystemInfo]$underscore,

    [ValidateScript( { { $(test-ValidPatternArrayParam -Arg $_ -AllowWildCard ) } })]
    [Parameter(ParameterSetName = 'MoveToStart', Mandatory)]
    [Parameter(ParameterSetName = 'MoveToEnd', Mandatory)]
    [Parameter(ParameterSetName = 'MoveToAnchor', Mandatory)]
    [Parameter(ParameterSetName = 'HybridStart', Mandatory)]
    [Parameter(ParameterSetName = 'HybridEnd', Mandatory)]
    [Parameter(ParameterSetName = 'NoMoveUpdate', Mandatory)]
    [array]$Pattern,

    [Parameter(ParameterSetName = 'MoveToStart')]
    [Parameter(ParameterSetName = 'MoveToEnd')]
    [Parameter(ParameterSetName = 'MoveToAnchor')]
    [Parameter(ParameterSetName = 'HybridStart')]
    [Parameter(ParameterSetName = 'HybridEnd')]
    [Parameter(ParameterSetName = 'NoMoveUpdate')]
    [string]$Drop,

    [ValidateScript( { $(test-ValidPatternArrayParam -Arg $_) })]
    [Parameter(ParameterSetName = 'MoveToAnchor', Mandatory)]
    [Parameter(ParameterSetName = 'HybridStart', Mandatory)]
    [Parameter(ParameterSetName = 'HybridEnd', Mandatory)]
    [array]$Anchor,

    [ValidateSet('before', 'after')]
    [Parameter(ParameterSetName = 'MoveToAnchor')]
    [Parameter(ParameterSetName = 'HybridStart')]
    [Parameter(ParameterSetName = 'HybridEnd')]
    [string]$Relation = 'after',

    [Parameter(ParameterSetName = 'MoveToStart', Mandatory)]
    [Parameter(ParameterSetName = 'HybridStart', Mandatory)]
    [switch]$Start,

    [Parameter(ParameterSetName = 'MoveToEnd', Mandatory)]
    [Parameter(ParameterSetName = 'HybridEnd', Mandatory)]
    [switch]$End,

    [ValidateScript( { { $(test-ValidPatternArrayParam -Arg $_) } })]
    [Parameter(ParameterSetName = 'MoveToStart')]
    [Parameter(ParameterSetName = 'MoveToEnd')]
    [Parameter(ParameterSetName = 'MoveToAnchor')]
    [Parameter(ParameterSetName = 'HybridStart')]
    [Parameter(ParameterSetName = 'HybridEnd')]
    [Parameter(ParameterSetName = 'NoMoveUpdate')]
    [array]$Copy,

    [Parameter(ParameterSetName = 'MoveToStart')]
    [Parameter(ParameterSetName = 'MoveToEnd')]
    [Parameter(ParameterSetName = 'MoveToAnchor')]
    [Parameter(ParameterSetName = 'HybridStart')]
    [Parameter(ParameterSetName = 'HybridEnd')]
    [Parameter(ParameterSetName = 'NoMoveUpdate')]
    [string]$With,

    [Parameter(ParameterSetName = 'MoveToStart')]
    [Parameter(ParameterSetName = 'MoveToEnd')]
    [Parameter(ParameterSetName = 'MoveToAnchor')]
    [Parameter(ParameterSetName = 'HybridStart')]
    [Parameter(ParameterSetName = 'HybridEnd')]
    [Parameter(ParameterSetName = 'NoMoveUpdate')]
    [string]$Paste,

    [Parameter(ParameterSetName = 'Prepend', Mandatory)]
    [string]$Prepend,

    [Parameter(ParameterSetName = 'Append', Mandatory)]
    [string]$Append,

    [Parameter()]
    [ValidateScript( { -not($PSBoundParameters.ContainsKey('Directory')); })]
    [switch]$File,

    [Parameter()]
    [ValidateScript( { -not($PSBoundParameters.ContainsKey('File')); })]
    [switch]$Directory,
  )
```
(which for some reason fails when invoked as:  gci \<params\> | Rename-Many -Pattern 'foo' -Start -WhatIf
All I know is that Anchor is the problem, *Anchor* should not be required, but PowerShell disagrees, but why?)

This is for a command (Rename-Many) that I'm currently building. I have defined 8 parameter sets, (currently not working as expected) and I'm trying to fix the definition. I can estimate which of those entries is for which parameter set, but when you're trying to resolve an issue, you really want powershell to tell you how it's determining the parameter set, rather than you yourself trying to guess what's happening (well I mean applying the rules of parameter sets as documented). 

For each entry in that result set, using the -synax option, can we also have the parameter set name dislayed. This would help out in resolving issues in parameter binding.

For example, the first entry returned:

```powershell
Rename-Many -underscore <FileSystemInfo> -Pattern <array> [-Drop <string>] [-Copy <array>] [-With <string>] [-Paste <string>] [-File] [-Directory] [-Except <string>] [-Include <string>] [-Whole <string>] [-Condition <scriptblock>] [-Top <int>] [-Transform <scriptblock>] [-Context <psobject>] [-Diagnose] [-WhatIf] [-Confirm] [<CommonParameters>]
```

This result does not tell me which parameter set it refers to. We need the parameter set name to be displayed somewhere in the result.

By the way, if you could let me know if there are some other techniques/tools (I've tried Trace-Command to no avail) that can help with parameter binding issues, I would be grateful.

**Comment by mklement0** [comment]
I agree that showing the parameter-set names would be helpful, which has previously been suggested in #6856

**Comment by plastikfan** [comment]
Ah ok. That issue talks about that info not being helpful to the end user, which is fair enough, but we as developers need another way of finding this out even if the end user does not. Jsut because the user maybe not interested in the parameter set name, its presence would not be deterimental to them, so in a way I don't understand the reticence. That issue has been opened a while now but not addressed or closed, so what' s gonna happen to it?

Parameter set resolution is difficult as it is and we need some way to help debug these issues.

**Comment by mklement0** [comment]
As for the meta problem: It's always a good question as to what happens to old, seemingly abandoned proposals. Renewed interest, even via an accidental duplicate or near-duplicate may revive the discussion, but it's important to (a) link to old proposals and (b) agree on where the discussion should continue.

My guess is that the reticence is around two aspects:

* Parameter-set names are considered an implementation detail, not public information - though I don't think it would be a problem to expose them, because they do carry useful information even for the end user, even though the need to show them may be more pressing for developers.

   * As long as no one expects these names to be part of a public contract, I don't think showing them is problematic.

* Syntax-diagram output would get longer by 1-2 lines _per parameter set_, which with `-?` could make them (partially) scroll off screen in smaller windows and even with `Get-Command -Syntax` may no longer fit on a single screen.

Even if the parameter-set names were _not_ to be shown with `-?`, `Get-Help`, and only shown with `Get-Command -Syntax` and possibly also `Get-Help -Full`, what is unequivocally helpful to both end users and developers is to highlight the _unique_ parameters in each parameter set, as suggested @bpayette [here](https://github.com/PowerShell/PowerShell/issues/6856#issuecomment-388473915) (a comment that also makes the two points above).

**Comment by plastikfan** [comment]
Actually, I just reviwed the chat on that other issue (#8692) and somebody has written a function that implements this as I need, as this is a duplcate, I'll close.
