### ISSUE TITLE
more request than an issue

### ISSUE THREAD

**Issue by Zak-Ghani** [PowerShell/PowerShell#14683]
can i request a feature please ?
when I open up Powershell core, if an update exists then i am advised by the "A new Powershell stable..." message. can you possibly add a Follow link option that does the update in the same vain as the https://aka.ms/PowerShell-... or make the "Upgrade now" in the second line of the banner text into a hot link to run the upgrade

I'm thinking something along the line's of a Thomas Maurer style one liner

e.g. iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"

Thanks Thomas for that one but having to search for "Thomas Maurer oneliner update powershell" is becoming tedious now

**Comment by mklement0** [comment]
That's a good idea, but I think the better solution would be to implement an `Update-PowerShell` cmdlet, as proposed in #12678, which could then be mentioned in the notification message.

**Comment by iSazonov** [comment]
Current intention is #14217
