### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by AdamBrezik** [PowerShell/PowerShell#14680]
Hi.
I'm using ps7.1.1 and one thing just struck me:
Why do you have color settings, when most of the colors are not there?
Either put them there or remove the color settings tab to make a simple statement...
Sorry, but things should make at least some sense.

**Comment by 237dmitry** [comment]
What do you mean? It's not entirely clear where these settings are. If in PSReadline module, then you can set any RGB color there using esc sequences. If Write-Host cmdlet, then you can do the same there.
```
Write-Host "`e[38;2;23;123;223mLight Blue`e[0m"
```

**Comment by AdamBrezik** [comment]
I'll have to get me someone explain your answer to me first. See you then.

**Comment by iSazonov** [comment]
@AdamBrezik Please use our issue template and add more info as requested in the template.

**Comment by AdamBrezik** [comment]
> @AdamBrezik Please use our issue template and add more info as requested in the template.

So now there's a template somewhere? See - that's the thing I'm trying to tell you. This is not an easy setup. There are three or four places to set the colors which the person has to find themselves because nobody cares to elaborate enough for a mere mortal to understand and then you can start an issue that's not based on a template that is mentioned somewhere somewhere.

This may be an open source, but it sure does seem as a closed community.
