### ISSUE TITLE
new loop structure

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14695]
Hi guys !

this feature is powerfull and this is an example:

![Capture](https://user-images.githubusercontent.com/36144546/106648915-c3611380-6545-11eb-875d-5bafcc4c0855.PNG)

**Comment by daxian-dbw** [comment]
@p0W3RH311 Thanks for the proposal, but we don't see a need to introduce a new loop syntax to PowerShell.
