### ISSUE TITLE
2012-12-31 in Powershell 7.1.1 still gives week 53 should be 1 When using: Calendar.GetWeekOfYear

### ISSUE THREAD

**Issue by B-Art** [PowerShell/PowerShell#14703]
2012-12-31 in Powershell 7.1.1 still gives week 53 should be 1 When using:
`
(Get-Culture).Calendar.GetWeekOfYear('2012-12-31', (Get-Culture).DateTimeFormat.CalendarWeekRule, (Get-Culture).DateTimeFormat.FirstDayOfWeek)
`
The formula should be based on the number of Thursdays in THIS year and must be starting with a Thursday or a Wendsday( When this is a Leapyear.)
'2012-01-01' is a Sunday.....?

Probably the issue exist because Sunday = 0 instead of Monday.

http://week-number.net/calendar-with-week-numbers-2012.html

<blockquote><div><strong><a href="http://week-number.net/calendar-with-week-numbers-2012.html">2012 calendar with Week Numbers - What week is it?</a></strong></div></blockquote>

_Originally posted by @B-Art in https://github.com/PowerShell/PowerShell/issues/11534#issuecomment-772867962_

**Comment by KalleOlaviNiemitalo** [comment]
Which culture is that, anyway?

Possible fixes, starting from the most feasible:

* Change the expression to use the [ISOWeek](https://docs.microsoft.com/dotnet/api/system.globalization.isoweek?view=net-5.0) class. The expression would then not work in Windows PowerShell.
* Change .NET Runtime to use the ISO week numbering for that culture, perhaps by defining a new subclass of Calendar that overrides GetWeekOfYear. This would make some sense if people living in that culture use ISO week numbers in speech and in printed calendars.
* Change PowerShell to detect that your expression tries to call Calendar.GetWeekOfYear, and sneakily call ISOWeek.GetWeekOfYear instead. Would surprise users.
* Change Calendar.GetWeekOfYear in .NET Runtime to use ISO week numbers if CalendarWeekRule.FirstFourDayWeek is specified with DayOfWeek.Monday. Was previously rejected because of the risk that it would break applications.

**Comment by B-Art** [comment]
It is Dutch Culture.
I solved it by skipping Sunday (because it is [int]0) and add/substract the other days to Thursday:

`
function Get-WeekNumber([datetime]$DT = (Get-Date)) {
	(Get-Culture).Calendar.GetWeekOfYear((Get-Date($DT)).AddDays(
	[int](([int](Get-Date($DT)).DayOfWeek) -gt 0)*(4 - ([int](Get-Date($DT)).DayOfWeek) )
	), ((Get-Culture).DateTimeFormat.CalendarWeekRule), ((Get-Culture).DateTimeFormat.FirstDayOfWeek))
}

Get-WeekNumber('2013-01-01')
Get-WeekNumber('2012-12-31')
Get-WeekNumber('2012-12-30')
Get-WeekNumber('2012-12-29')
`
This works as a bugfix.

**Comment by B-Art** [comment]
UICulture has a different bug than Culture:

`
(28..31).foreach({(Get-UICulture).Calendar.GetWeekOfYear("2012-12-$($_)", ((Get-UICulture).DateTimeFormat.CalendarWeekRule), ((Get-UICulture).DateTimeFormat.FirstDayOfWeek))})
`
52
52
53
53

`
(28..31).foreach({(Get-Culture).Calendar.GetWeekOfYear("2012-12-$($_)", ((Get-Culture).DateTimeFormat.CalendarWeekRule), ((Get-Culture).DateTimeFormat.FirstDayOfWeek))})
`
52
52
52
53

**Comment by KalleOlaviNiemitalo** [comment]
What is the UICulture, then?  If it is U.S. English, then perhaps non-ISO week numbers are correct there.

**Comment by B-Art** [comment]
`
(Get-Culture).DateTimeFormat
`
AMDesignator                     :
Calendar                         : System.Globalization.GregorianCalendar
DateSeparator                    : -
FirstDayOfWeek                   : Monday
CalendarWeekRule                 : FirstFourDayWeek
FullDateTimePattern              : dddd d MMMM yyyy HH:mm:ss
LongDatePattern                  : dddd d MMMM yyyy
LongTimePattern                  : HH:mm:ss
MonthDayPattern                  : d MMMM
PMDesignator                     :
RFC1123Pattern                   : ddd, dd MMM yyyy HH':'mm':'ss 'GMT'
ShortDatePattern                 : yyyy-MM-dd
ShortTimePattern                 : HH:mm
SortableDateTimePattern          : yyyy'-'MM'-'dd'T'HH':'mm':'ss
TimeSeparator                    : :
UniversalSortableDateTimePattern : yyyy'-'MM'-'dd HH':'mm':'ss'Z'
YearMonthPattern                 : MMMM yyyy
AbbreviatedDayNames              : {zo, ma, di, wo…}
ShortestDayNames                 : {Z, M, D, W…}
DayNames                         : {zondag, maandag, dinsdag, woensdag…}
AbbreviatedMonthNames            : {jan., feb., mrt., apr.…}
MonthNames                       : {januari, februari, maart, april…}
IsReadOnly                       : True
NativeCalendarName               : Gregoriaanse kalender
AbbreviatedMonthGenitiveNames    : {jan., feb., mrt., apr.…}
MonthGenitiveNames               : {januari, februari, maart, april…}
`
(22..31).foreach({(Get-Culture).Calendar.GetWeekOfYear("2012-12-$($_)", ((Get-Culture).DateTimeFormat.CalendarWeekRule), ((Get-Culture).DateTimeFormat.FirstDayOfWeek))})
`
51
51
52
52
52
52
52
52
52
53

`
(1..7).foreach({(Get-Culture).Calendar.GetWeekOfYear("2013-1-$($_)", ((Get-Culture).DateTimeFormat.CalendarWeekRule), ((Get-Culture).DateTimeFormat.FirstDayOfWeek))})
`
1
1
1
1
1
1
2

**Comment by daxian-dbw** [comment]
@B-Art You are calling a .NET API [`Calendar.GetWeekOfYear(DateTime, CalendarWeekRule, DayOfWeek)`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar.getweekofyear?view=net-5.0). If you have question about the behavior of that API, please open an issue in https://github.com/dotnet/runtime or post a question in their [Discussions](https://github.com/dotnet/runtime/discussions).
