### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by Activate256** [PowerShell/PowerShell#14704]
## Steps to reproduce

```powershell

```suggestion​

## Expected behavior

```none of the GNU General Public Module Program​
Public​Sub​Main​page for a number of reasons for the use my referral code 
```

## Actual behavior of a child which has been the most popular 

```nonetheless and the compiler hasn't implemented the error​message​in the past 

```

## Environment data can be found in this article and the compiler hasn't implemented the error messages in the past 

 https://t.me/TronLink/255141

```none of this has to do with your main file but I will try and get back to it later in the day 

```
Imports​System.Collections.Generic​  :GNU​ is
Public Sub Main :
Imports​ Module​ Compiler​  version 0.0.0.5943, 
Public Module ERC20Basic interface without the use of software for all offers to be able. 
Namespace "Hello, Dcoder! "​Floating_Number(args​(), string()), 
Imports System.Linq :
LogSystemNetworkElementStorage
Name (29)
Method
Status
Time
https://www.google-analytics.com/j/collect
POST
200
95ms
Query String Parameters
v
1
_v
j87
a
529295131
t
pageview
_s
1
dl
https%3A%2F%2Fm.poloniex.org%2F
ul
en
de
UTF-8
dt
Poloni%20DEX%20%7C%20Exchange%20the%20TRON%20world%20with%200%20trading%20fee
sd
24-bit
sr
360x760
vp
360x638
je
0
_u
AACAAUABAAAAAC~
jid
1124885137
gjid
1348128281
cid
1605143543.1610972638
tid
UA-117929022-5
_gid
1100793008.1612341330
_r
1
gtm
2ou1k0
z
690505392
Form Data
Response
1d
https://stats.g.doubleclick.net/j/collect
POST
200
286ms
Query String Parameters
t
dc
aip
1
_r
3
v
1
_v
j87
tid
UA-117929022-5
cid
1605143543.1610972638
jid
1124885137
gjid
1348128281
_gid
1100793008.1612341330
_u
AACAAUAAAAAAAC~
z
1688703215
Form Data
Response
1gco.th
https://api.trongrid.io/wallet/getaccount
POST
200
114ms
Form Data
{"address":"41a2726afbecbd8e936000ed684cef5e2f5cf43008"}
Response
{
 "account_name": "437265617465644279436f6e7472616374",
 "type": "Contract",
 "address": "41a2726afbecbd8e936000ed684cef5e2f5cf43008",
 "balance": 672029119907297,
 "account_resource": {},
 "assetV2": [
  {
   "key": "1003218",
   "value": 20000
  },
  {
   "key": "1003282",
   "value": 1000888
  },
  {
   "key": "1002963",
   "value": 5000000
  },
  {
   "key": "1003134",
   "value": 335000000
  },
  {
   "key": "1003362",
   "value": 10000000
  },
  {
   "key": "1003406",
   "value": 1
  },
  {
   "key": "1003495",
   "value": 200000000
  },
  {
   "key": "1003506",
   "value": 3000000000000
  },
  {
   "key": "1003452",
   "value": 12
  },
  {
   "key": "1003475",
   "value": 1665
  },
  {
   "key": "1003604",
   "value": 69612000000
  },
  {
   "key": "1003621",
   "value": 34806000000
  },
  {
   "key": "1003638",
   "value": 426000000
  },
  {
   "key": "1003650",
   "value": 1675482
  },
  {
   "key": "1003641",
   "value": 3300000000
  },
  {
   "key": "1003659",
   "value": 2000000
  },
  {
   "key": "1003665",
   "value": 10000000
  },
  {
   "key": "1003623",
   "value": 34200000000
  },
  {
   "key": "1003670",
   "value": 1145553
  },
  {
   "key": "1003657",
   "value": 111000000
  },
  {
   "key": "1003678",
   "value": 62640000
  },
  {
   "key": "1003685",
   "value": 84750000000
  },
  {
   "key": "1003695",
   "value": 700000000
  }
 ],
 "free_asset_net_usageV2": [
  {
   "key": "1003218",
   "value": 0
  },
  {
   "key": "1003282",
   "value": 0
  },
  {
   "key": "1002963",
   "value": 0
  },
  {
   "key": "1003134",
   "value": 0
  },
  {
   "key": "1003362",
   "value": 0
  },
  {
   "key": "1003406",
   "value": 0
  },
  {
   "key": "1003495",
   "value": 0
  },
  {
   "key": "1003506",
   "value": 0
  },
  {
   "key": "1003452",
   "value": 0
  },
  {
   "key": "1003475",
   "value": 0
  },
  {
   "key": "1003604",
   "value": 0
  },
  {
   "key": "1003621",
   "value": 0
  },
  {
   "key": "1003638",
   "value": 0
  },
  {
   "key": "1003650",
   "value": 0
  },
  {
   "key": "1003641",
   "value": 0
  },
  {
   "key": "1003659",
   "value": 0
  },
  {
   "key": "1003665",
   "value": 0
  },
  {
   "key": "1003623",
   "value": 0
  },
  {
   "key": "1003670",
   "value": 0
  },
  {
   "key": "1003657",
   "value": 0
  },
  {
   "key": "1003678",
   "value": 0
  },
  {
   "key": "1003685",
   "value": 0
  },
  {
   "key": "1003695",
   "value": 0
  }
 ]
}
https://api.poloniex.org/api/exchange/user/order
GET
200
374ms
https://apilist.tronscan.org/api/system/proxy
GET
200
370ms
https://apilist.tronscan.org/api/token
GET
200
331ms
https://apilist.tronscan.org/api/token
GET
200
340ms
https://apilist.tronscan.org/api/token
GET
200
363ms
https://apilist.tronscan.org/api/token
GET
200
359ms
https://apilist.tronscan.org/api/token
GET
200
328ms
https://apilist.tronscan.org/api/token
GET
200
595ms
https://apilist.tronscan.org/api/token
GET
200
367ms
https://apilist.tronscan.org/api/token
GET
200
377ms
https://apilist.tronscan.org/api/token
GET
200
316ms
https://apilist.tronscan.org/api/token
GET
200
530ms
https://apilist.tronscan.org/api/token
GET
200
356ms
https://apilist.tronscan.org/api/token
GET
200
309ms
https://apilist.tronscan.org/api/token
GET
200
309ms
https://apilist.tronscan.org/api/token
GET
200
501ms
Query String Parameters
id
1003641
Response
{
 "total": 1,
 "data": [
  {
   "country": "",
   "tokenID": 1003641,
   "participated": 0,
   "precision": 6,
   "num": 1000000,
   "available": 0,
   "reputation": "Pending",
   "description": "Balancer is a n-dimensional automated market-maker that allows anyone to create or add liquidity to customizable pools and earn trading fees.\nInvestors of our other projects receive part of our tokens",
   "issuedPercentage": 99.98896063281825,
   "nrOfTokenHolders": 16505,
   "voteScore": 0,
   "dateCreated": 1610713392000,
   "price": 549,
   "percentage": 0,
   "startTime": 1610726400000,
   "id": 1003641,
   "issued": 54353999000000,
   "trxNum": 549000000,
   "abbr": "BAL",
   "email": "info@balancer.finance",
   "website": "https://balancer-exchange.com/",
   "github": "https://github.com/balancer-labs/",
   "level": "0",
   "availableSupply": 0,
   "totalSupply": 54360000000000,
   "frozenTotal": 0,
   "frozen": [],
   "frozen_supply": [],
   "canShow": "1",
   "remaining": 6002049000,
   "url": "https://balancer-exchange.com/",
   "frozenPercentage": 0,
   "imgUrl": "https://coin.top/production/upload/logo/1003641.png",
   "isBlack": false,
   "new_social_media": "",
   "remainingPercentage": 0,
   "name": "Balancer",
   "ownerAddress": "TVddDhyFbFnq75S93Jydn4ueVD1B2zKoei",
   "endTime": 1610812800000,
   "white_paper": "",
   "social_media": [
    {
     "name": "Weibo",
     "url": ""
    },
    {
     "name": "Telegram",
     "url": ""
    },
    {
     "name": "Reddit",
     "url": ""
    },
    {
     "name": "Medium",
     "url": ""
    },
    {
     "name": "Steam",
     "url": ""
    },
    {
     "name": "Webchat",
     "url": ""
    },
    {
     "name": "Twitter",
     "url": ""
    },
    {
     "name": "Facebook",
     "url": ""
    }
   ],
   "rank_order": 1000000,
   "vip": false,
   "totalTransactions": 16512,
   "index": 1
  }
 ],
 "contractMap": {
  "TVddDhyFbFnq75S93Jydn4ueVD1B2zKoei": false
 },
 "totalAll": 1
}
https://apilist.tronscan.org/api/token
GET
200
430ms
https://apilist.tronscan.org/api/token
GET
200
356ms
Query String Parameters
id
1003665
Response
{
 "total": 1,
 "data": [
  {
   "country": "",
   "tokenID": 1003665,
   "participated": 0,
   "precision": 6,
   "num": 100000000,
   "available": 0,
   "reputation": "Pending",
   "description": "The token of Hodler project",
   "issuedPercentage": 99.99995,
   "nrOfTokenHolders": 433187,
   "voteScore": 0,
   "dateCreated": 1611061206000,
   "price": 0,
   "percentage": 0,
   "startTime": 1611090000000,
   "id": 1003665,
   "issued": 99999950000000,
   "trxNum": 1000000,
   "abbr": "HDLR",
   "email": "nygtokens@yandex.ru",
   "website": "https://tron-hodler.com",
   "github": "",
   "level": "0",
   "availableSupply": 0,
   "totalSupply": 100000000000000,
   "frozenTotal": 0,
   "frozen": [],
   "frozen_supply": [],
   "canShow": "1",
   "remaining": 50331648,
   "url": "https://tron-hodler.com",
   "frozenPercentage": 0,
   "imgUrl": "https://coin.top/production/upload/logo/1003665.png",
   "isBlack": false,
   "new_social_media": "",
   "remainingPercentage": 0,
   "name": "Hodler",
   "ownerAddress": "TTaueok8UKrJoPY1DBD28SwxAsMGbpfq78",
   "endTime": 1611176400000,
   "white_paper": "",
   "social_media": [
    {
     "name": "Weibo",
     "url": ""
    },
    {
     "name": "Telegram",
     "url": "https://t.me/tronhodler"
    },
    {
     "name": "Reddit",
     "url": ""
    },
    {
     "name": "Medium",
     "url": ""
    },
    {
     "name": "Steam",
     "url": ""
    },
    {
     "name": "Webchat",
     "url": ""
    },
    {
     "name": "Twitter",
     "url": ""
    },
    {
     "name": "Facebook",
     "url": ""
    }
   ],
   "rank_order": 1000000,
   "totalTransactions": 1200212,
   "vip": false,
   "index": 1
  }
 ],
 "contractMap": {
  "TTaueok8UKrJoPY1DBD28SwxAsMGbpfq78": false
 },
 "totalAll": 1
}
https://apilist.tronscan.org/api/token
GET
200
361ms
Query String Parameters
id
1003623
Response
{
 "total": 1,
 "data": [
  {
   "country": "",
   "tokenID": 1003623,
   "participated": 0,
   "precision": 6,
   "num": 1000000,
   "available": 0,
   "reputation": "Pending",
   "description": "governance token of MBOX swap project",
   "issuedPercentage": 76.775380114,
   "nrOfTokenHolders": 399400,
   "voteScore": 0,
   "dateCreated": 1610178471000,
   "price": 1,
   "percentage": 0,
   "startTime": 1610208000000,
   "id": 1003623,
   "issued": 7677538011400000,
   "trxNum": 1000000,
   "abbr": "MBOX",
   "email": "trxdefi@163.com",
   "website": "www.mbox.ink",
   "github": "",
   "level": "0",
   "availableSupply": 0,
   "totalSupply": 10000000000000000,
   "frozenTotal": 0,
   "frozen": [],
   "frozen_supply": [],
   "canShow": "1",
   "remaining": 2322462230000000,
   "url": "www.mbox.ink",
   "frozenPercentage": 0,
   "imgUrl": "https://coin.top/production/upload/logo/1003623.png?t=1611990592302",
   "isBlack": false,
   "new_social_media": "",
   "remainingPercentage": 0,
   "name": "MBOXSwap",
   "ownerAddress": "TMWEf9XMSTPrVbBPgGKGEbSQGpxnjc917p",
   "endTime": 1610294400000,
   "white_paper": "",
   "social_media": [
    {
     "name": "Weibo",
     "url": ""
    },
    {
     "name": "Telegram",
     "url": ""
    },
    {
     "name": "Reddit",
     "url": ""
    },
    {
     "name": "Medium",
     "url": ""
    },
    {
     "name": "Steam",
     "url": ""
    },
    {
     "name": "Webchat",
     "url": ""
    },
    {
     "name": "Twitter",
     "url": ""
    },
    {
     "name": "Facebook",
     "url": ""
    }
   ],
   "rank_order": 1000000,
   "totalTransactions": 691718,
   "vip": false,
   "index": 1
  }
 ],
 "contractMap": {
  "TMWEf9XMSTPrVbBPgGKGEbSQGpxnjc917p": false
 },
 "totalAll": 1
}
https://apilist.tronsca ​> DeployContract [ownerAddress] contractName ABI byteCode constructor params isHex fee_limit consume_user_resource_percent origin_energy_limit value token_value token_id(e.g: TRXTOKEN, use # if don't provided) <library:address,library:address,...> <lib_compiler_version(e.g:v5)> library:address,...>

**Comment by Activate256** [comment]
LogSystemNetworkElementStorage
All
Log
Information on the right side of your 
System: Android 8.1.0
Protocol: HTTPS
UA: Mozilla/5.0 (Linux; Android 8.1.0; DUB-LX2 Build/HUAWEIDUB-LX2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36
navigationStart: 1612421143720
navigation: 14ms
dns: 0ms
tcp: 0ms
request: 270ms
response: 4ms
domComplete (domLoaded): 1912ms (758ms)
loadEvent: 79ms
total (DOM): 2318ms (2239ms)

**Comment by Activate256** [comment]
> 
> 
> ## Steps to reproduce
> 
> ```powershell
> 
> ```suggestion​
> 
> ## Expected behavior
> 
> ```none of the GNU General Public Module Program​
> Public​Sub​Main​page for a number of reasons for the use my referral code 
> ```
> 
> ## Actual behavior of a child which has been the most popular 
> 
> ```nonetheless and the compiler hasn't implemented the error​message​in the past 
> 
> ```
> 
> ## Environment data can be found in this article and the compiler hasn't implemented the error messages in the past 
> 
>  https://t.me/TronLink/255141
> 
> ```none of this has to do with your main file but I will try and get back to it later in the day 
> 
> ```
> 

Namespace​ Dcoder​

**Comment by Activate256** [comment]
​> DeployContract [ownerAddress] contractName ABI byteCode constructor params isHex fee_limit consume_user_resource_percent origin_energy_limit value token_value token_id(e.g: TRXTOKEN, use # if don't provided) <library:address,library:address,...> <lib_compiler_version(e.g:v5)> library:address,...>

**Comment by doctordns** [comment]
I am not at all clear what the issue is. But it sounds like the OP wants to run PowerShell in Android and that his not supported. 

For the OP - do not put obfuscated links to the environment details, please add them here.  And consider removing this issue and adding one with all the necessary information in a single post.

**Comment by daxian-dbw** [comment]
@Activate256 Please follow the issue template and describe the problem or your ask clearly.
