### ISSUE TITLE
PowerShell starts in $env:windir\system32 instead of $env:userprofile

### ISSUE THREAD

**Issue by mvaneerde** [PowerShell/PowerShell#14706]
## Steps to reproduce

Launch the PowerShell app non-elevated
Launch the PowerShell app elevated

## Expected behavior

Non-elevated case should start in the $env:userprofile directory
Elevated case should start in the $env:windir\system32 directory

## Actual behavior

Non-elevated case incorrectly starts in $env:windir\system32 directory
Elevated case correctly starts in $env:windir\system32 directory

## Environment data

```
> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.21307
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by daxian-dbw** [comment]
@mvaneerde Are you using an installation from the Windows App Store?

**Comment by mvaneerde** [comment]
Yes

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Is it by design that the App Store version of pwsh always starts in the `system32` folder due to limitations of the store apps?
