### ISSUE TITLE
A couple issues in the new progress bar

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#14717]
A couple issues were noticed after https://github.com/PowerShell/PowerShell/pull/14414 was merged. Open this issue to track them.

1. Progress message truncation when `MaxWidth` is not big enough. See https://github.com/PowerShell/PowerShell/pull/14414#issuecomment-774223880
2. New progress rendering fails when `MaxWidth` is too small to have enough space for the `[...]` part. See https://github.com/PowerShell/PowerShell/pull/14414#issuecomment-774225695

**Comment by SteveL-MSFT** [comment]
On Windows systems that don't support VT, should fallback to legacy rendering

**Comment by SteveL-MSFT** [comment]
I believe both of these have been addressed
