### ISSUE TITLE
Provide a keystroke that will clear the screen completely, even when something is running

### ISSUE THREAD

**Issue by intervalia** [PowerShell/PowerShell#14715]
I often run something long term, especially a node server, but other things as well.

On the Mac I can press ⌘+K and it will clear the screen and all visual history.
**This works even if an application is running.**

I do this when I am debugging or whenever I want a clear slate so I can see JUST the new output.

Powershell needs something similar. Clear the entire screen and do a full reset so that there is no more scroll history.

**Comment by daxian-dbw** [comment]
PowerShell provides the keystroke `Ctrl+L` to clear screen. But of course it doesn't work when application is running in PowerShell -- I think that would require the terminal level support, not in the PowerShell layer. /cc @theJasonHelmick

**Comment by DHowett** [comment]
Yes, this requires support in the terminal emulator. Powershell isn’t doing any meaningful keyboard processing while another application is running. Many terminal emulators have this feature already.

**Comment by doctordns** [comment]
PsReadLine does this. Ctrl+L.

Works in the Console,  VS Code, and Terminal.

**Comment by intervalia** [comment]
> PsReadLine does this. Ctrl+L.
> 
> Works in the Console, VS Code, and Terminal.

Only when NOT running a program.

On the Mac Terminal I can press Cmd+K, even when an app is running, and it will clear the display.

Are there other terminal emulators for Powershell? How would I change it?
