### ISSUE TITLE
Regression: Multiple Invoke-WebRequest to raw.githubusercontent.com throws exception

### ISSUE THREAD

**Issue by diddledani** [PowerShell/PowerShell#14729]
This is a regression affecting PowerShell Core, when comparing with Windows PowerShell from Windows Insider Build 21301.

When using multiple `Invoke-WebRequest` calls to download content from `raw.githubusercontent.com`, only the first request succeeds with subsequent requests throwing a `System.Net.InternalException`.

I can reproduce this reliably with `raw.githubusercontent.com` URLs, but I have _not_ succeeded in reproducing against other URLs.

## Steps to reproduce

Both requests should be executed sequentially and without delay. It's easiest to reproduce the issue by putting both requests into a `.ps1` script and execute that.

```powershell
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledan/one-script-wsl2-systemd/master/install.ps1"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledan/one-script-wsl2-systemd/master/services.ps1"
```

## Expected behavior

Both requests are expected to complete successfully, and not throw an exception.

## Actual behavior

The second request throws an exception: `System.Net.InternalException`

```none
StatusCode        : 200
StatusDescription : OK
Content           : param($Distro, $User, [switch]$NoGPG)

                    $repoUrl = 'https://github.com/diddlesnaps/one-script-wsl2-systemd/raw/master/'

                    # The main files to install.
                    $files = @{
                        'systemd' = @{
                            'source' = '…
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Cache-Control: max-age=300
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    ETag: "850161c65667f2bb9ae21e50e21bd807764ff6b8c05…
Headers           : {[Connection, System.String[]], [Cache-Control, System.String[]], [Content-Security-Policy,
                    System.String[]], [ETag, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 9149
RelationLink      : {}

Invoke-WebRequest: C:\Users\yabea\source\one-script-wsl2-systemd\test.ps1:2
Line |
   2 |  Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledan/o …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception of type 'System.Net.InternalException' was thrown. -2146892963
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.21301
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by diddledan** [comment]
For completeness, attempting to reproduce on Ubuntu using the Snap Packaged PowerShell Core does not exhibit the issue. That suggests it's either a conflict with the Windows Insider build I'm running or is otherwise Windows-specific.

My Ubuntu box, that does not fail, shows the following `$PSVersionTable`:

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Linux 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 1…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by CarloToso** [comment]
Can't reproduce in windows 10, Powershell 7.3.1

**Comment by diddledani** [comment]
I can confirm that this appears fixed in Powershell 7.3.1 - I'm not sure when the fix appeared, but it is fixed now.

I am not directly closing this issue, however, as I would like for it to be seen and disseminated among those that have access to label issues here that simply labelling with "waiting on author" without making clear why you're labelling it as such (i.e. in this case I presume @iSazonov  wanted me to re-check whether I'm impacted following @CarloToso's inability to reproduce) makes the life of a bug reporter very difficult because such activity often confuses us and leads to ambiguities. I get that you are expecting your audience here to be technically minded and be able to figure it out given the label alone, but it is much friendlier to state what you require.

In my case here in this issue I had to make a cognitive leap to assume that the label being added by someone after a comment from a different someone were related and that I needed to figure out why. From there I had to make another cognitive leap to assume that the label was added because I was being requested, without any wording to state so, to re-test and verify that the issue is still valid and report back my findings.

Please make sure that within the Powershell team it is understood that you need to be explicit about what you require from another person when labelling with such a label that indicates input from someone other than the person adding the label is being requested.

(This isn't meant as an attack, but might be read as such because I'm bad at phrasing. Please take it as a suggestion to improve interaction with the community you are fostering :-) )

**Comment by iSazonov** [comment]
@diddledani Thanks for your feedback. Labels help us to track issue states and close stale ones. Note this is an open source project and no one has any obligations.

As for the issue, you can download latest daily build 7.4 from main page and check if your issue presents.

**Comment by CarloToso** [comment]
@iSazonov Can't reproduce in windows 10, 7.4 preview1
Test:
```ps1
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/master/install.ps1"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/master/uninstall.ps1"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/master/install.ps1"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/master/uninstall.ps1"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/master/install.ps1"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/master/uninstall.ps1"
```
no errors
