### ISSUE TITLE
ui.RawUI on result of 'Get-Host' contains ForegroundColor/BackgroundColor set to -1 on macOS

### ISSUE THREAD

**Issue by plastikfan** [PowerShell/PowerShell#14727]
This is a platform specific issue and has been tested on mac. To reproduce run the said commands inside terminal app, or Iterm2

```powershell
$host.ui.RawUI.ForegroundColor
```

or 

```powershell
(Get-Host).ui.RawUI.ForegroundColor
```

## Expected behavior

Should behave like windows and return valid colours for ForegroundColor and BackgroundColor

## Actual behavior

On mac:
```
λ $host.ui.RawUI.ForegroundColor
-1


λ (get-host).ui.rawui | Format-List -Property *

ForegroundColor       : -1
BackgroundColor       : -1
CursorPosition        : 0,52
WindowPosition        : 0,0
CursorSize            : 100
BufferSize            : 214,53
WindowSize            : 214,53
MaxWindowSize         : 214,53
MaxPhysicalWindowSize : 214,53
KeyAvailable          : False
WindowTitle           :

```

On windows:

```
λ (get-host).ui.rawui | Format-List -Property *

ForegroundColor       : Gray
BackgroundColor       : Black
CursorPosition        : 0,59
WindowPosition        : 0,0
CursorSize            : 25
BufferSize            : 213,60
WindowSize            : 213,60
MaxWindowSize         : 213,60
MaxPhysicalWindowSize : 1904,70
KeyAvailable          : True
WindowTitle           : Elizium.Krayola
```

I haven't tested this on Linux, but the same applies there also.

## Environment data

```none
λ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

See also: [PSHostRawUserInterface Class](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostrawuserinterface?view=powershellsdk-7.0.0)

I've raised this issue here because that host raw ui interface is part of the PowerShell SDK 7.0.

**Comment by plastikfan** [comment]
Another point of ponderance to me is, if these values are set to -1 and not valid colours, how does general text display in a PowerShell session work without having those properties properly set? It implies there is another place that that colours are being set from, but where? As a workl around, I am manually going to set these values to 'gray' and 'black' in my module initialisation code and inform the user (via documntation) they can override these default values.

**Comment by Jibun-no-Kage** [comment]
This also happens is the psISE environment as well, which makes NO SENSE to me.  The psISE console panel colors are ONLY found as html hex values?  That is even MORE confusing!  So there really is NO WAY?  To get the console panel colors that are compatible with write-host?

**Comment by plastikfan** [comment]
I'm a bit surprised this hasnt been addressed yet, seems like its a trivial issue to resolve

**Comment by adityapatwardhan** [comment]
As far as the Working Group knows, there is no consistent way to get the foreground and background colors on non-windows terminals. This is something that should be done in .NET. I would recommend filing an issue at: https://github.com/dotnet/runtime

We would add documentation which would say that the values are always -1 on non-windows terminals.
