### ISSUE TITLE
improve classes

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14722]
hi guys !

classes in powershell are awesome but it still not powerfull like other languages OOP...it missing a lot of improvement...for example 

1) keyword **private** (method/attribute)
2) import classes or "subclass" more easily...with the keyword "**from**" ?
3) ..etc

**Comment by daxian-dbw** [comment]
The suggestion here is very vague, and PowerShell class already has the [`hidden` keyword](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hidden?view=powershell-7.1) for the 'private' purpose. `hidden` is not the same as `private` in C#, but for similar purpose -- it hides a property/method from the default results of the Get-Member cmdlet, and from IntelliSense and tab completion results.
