### ISSUE TITLE
implement lucene

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14723]
Hi guys !

please implement lucene to improve performance in the search (in filesystem/history/....etc)....powershell compared to other language is slow in "search"

**Comment by BrucePay** [comment]
What do you mean by "implement lucene". The lucene library already exists (including Lucene.Net). It can be loaded  and used from PowerShell as is.

**Comment by jhoneill** [comment]
On windows you can query the Windows Index. https://www.powershellgallery.com/packages/Get-IndexedItem/3.0.3

**Comment by jdhitsolutions** [comment]
I agree that this is already handled via a community contribution. There's no compelling reason for Microsoft to offer commands, especially as based on download numbers for @jhoneill's module (sorry James), there doesn't appear to be clamoring deman.
