### ISSUE TITLE
PowershellDirect on Windows Server 2016: Invoke-Command -VMName 'blah' fails with Unable to cast object of type 'System.String' to type 'VMState'.

### ISSUE THREAD

**Issue by ayeltsov** [PowerShell/PowerShell#14738]
## Steps to reproduce

```powershell
$vmUserPassword = 'password'; #reproes even without correct password
$vmUser = '.\Administrator'; 
$vmMachineName = 'MyLocalVMName';  #this VM needs to exist
$password = ConvertTo-SecureString $vmUserPassword -AsPlainText -Force; 
$cred = New-Object System.Management.Automation.PSCredential ($vmUser, $password); 
Invoke-Command -VMName $vmMachineName -Credential $cred { Write-Output ('Connection'+'Succeeded') }

```

## Expected behavior

```none
ConnectionSucceeded
```

## Actual behavior

```none
Invoke-Command: Unable to cast object of type 'System.String' to type 'VMState'.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Notes:
- this is about the host, rather than guest guest:
  - Win10 or Windows Server 2019 host + Windows Server 2019 guest => works
  - Windows Server *2016* host + Windows Server 2019 guest => breaks
- this is specific to powershell core
  - the same command works from Powershell ISE 5.1.14393.3866 from either host
- In my actual environment I use powershell SDK from c# app, but thankfully it reproes from regular powershell
- Similar unanswered question on [stackoverflow ](https://stackoverflow.com/questions/64661812/enter-pssession-unable-to-cast-object-of-type-system-string-to-type-vmstate).

**Comment by jborean93** [comment]
Looking at the code there are 2 places where this could occur https://github.com/PowerShell/PowerShell/blob/3c7f4b573e96684781b8e1935eeb0b981bcd93bc/src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs#L942 and https://github.com/PowerShell/PowerShell/blob/c7bdb24ff3160b69285202f30a079e4c589f26f4/src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs#L1007.

They are both trying to cast the `State` property from the first output of `Get-VM`. It seems like the code could be a bit more defensive and try to cast the string to the enum type as that isn't implicitly done leading to the error you get back.

**Comment by ayeltsov** [comment]
Just to clarify impact and what I'm looking for.

Impact: blocking ability to ship new version of internal tool. We've update the tool's codebase from .NET 4.7 to .NET 5, which necessitated switching to PowerShell Core SDK from older Powershell SDK. Since we have to support Win 2016, Win 2019 and Win 10 OS, we cannot ship the new version of the tool

What I'm looking for: some sort of work around to get past the issue.


Please let me know if I can do anything to help root cause it and look for workaround. Would love to unblock my project as soon as possible.

**Comment by jborean93** [comment]
I'm not sure you can fix this without changing the PowerShell code. Maybe to start off could you share the output of the following (in both Windows PowerShell and PowerShell):

```powershell
$vm = @(Get-VM -VMName MyLocalVMName)[0]

$vm.State
$vm.State.GetType().FullName
```

Comparing that between 2016 and 2019 guests would also help to potentially track down what is happening.

**Comment by ayeltsov** [comment]
>Comparing that between 2016 and 2019 guests 
Just to be on the same page - difference is about hosts. Guest is Server 2019 in both cases.

$vm.State is 'Running' in all the cases. Datatype is like this:

Powershell | Server 2019/Windows 10 | Server 2016
------------ | ------------- | ----
Powershell ISE | Microsoft.HyperV.PowerShell.VMState | Microsoft.HyperV.PowerShell.VMState
Powershell Core | Microsoft.HyperV.PowerShell.VMState | System.String

**Comment by jborean93** [comment]
Cool so that code is definitely problematic, I just don't understand why Server 2016 on PowerShell is a string but not for Windows PowerShell. I would have to look at the code to see what it is doing to give you a better answer. In short I think the PowerShell code needs to be a bit more defensive here but it's still an interesting problem.

**Comment by ayeltsov** [comment]
I'd be happy to try a private fix of Powershell SDK. 
Repro-wise I understand it's annoying to try and source Windows 2016 server, especially Hyper-V enabled. 

I personally used nested virtualization: Win 10 host -> Win 2016 server [for repro] -> Win 2019 guest, but I guess any VM will do
Not 100% sure, but it may be possible to get nested virtualization enabled Win 2016 sever from Azure.

**Comment by SeeminglyScience** [comment]
I'm guessing the 2016 version is using implicit remoting due to the HyperV module not getting the `Core` tag via Windows Updates.  As a workaround try `Import-Module HyperV -SkipEditionCheck` before running the command.

**Comment by jborean93** [comment]
Ahh I was assuming `guest` was the guest OS being targeted and the OS that is running the `Invoke-Command` was always Windows 10 but that would make more sense.

**Comment by ayeltsov** [comment]
This workaround worked, thank you!

````powershell
PS C:\Users\ayeltsov> Import-Module Hyper-V -SkipEditionCheck
PS C:\Users\ayeltsov> (@(Get-VM)[0]).State.GetType().FullName
Microsoft.HyperV.PowerShell.VMState
````

Let's see if this onion has more layers...

**Comment by ayeltsov** [comment]
Definitely more layers in this onion.

Same workaround needed for this:

````powershell
(Get-VM ayeltsov-336442) | Get-VMNetworkAdapter
Get-VMNetworkAdapter: The specified wildcard character pattern is not valid: VirtualMachine (Name = 'ayeltsov-336442') [Id = '69d6d3ef-09d1-4682-8b2a-b6e2cf44c593']
````

Question: is there a way to hint "-SkipEditionCheck" globally so that I don't change all the scripts that app is using?

**Comment by SeeminglyScience** [comment]
> Question: is there a way to hint "-SkipEditionCheck" globally so that I don't change all the scripts that app is using?

You could try `$PSDefaultParameterValues['Import-Module:SkipEditionCheck'] = $true` but I doubt autoloading actually calls `Import-Module`.  Even if it does, don't be surprised if some built in modules break in core without the wincompat layer (though tbh about as likely to break in my experience).

If you control the environment you could edit the manifests yourself to add `Core` under `CompatiblePSEditions`.  Again, ymmv and unlikely to be considered supported.

Last resort if you're desperate would be hooking into command lookup via `$ExecutionContext.InvokeCommand.PreCommandLookupAction`.

**Comment by ayeltsov** [comment]
@SeeminglyScience , FYI, the workaround with Import-Module:SkipEditionCheck did actually work (please don't break it in the next SDK :-))
I understand that it's affecting more modules than Hyper-V, but it works for this app.

Just for reference:

````csharp
                if (IsWindows2016.Value)
                {
                    System.Collections.Hashtable psDefaultParameterValues =
                        (System.Collections.Hashtable)powerShell.Runspace.SessionStateProxy.GetVariable("PSDefaultParameterValues");
                    psDefaultParameterValues["Import-Module:SkipEditionCheck"] = true;
                }

        private static readonly Lazy<bool> IsWindows2016 = new (
            () =>
            {
                // Weirdly, ProductName reg key is easiest way to distinguish Server 2016 and Server 2019.
                // It's not exposed via things like System.Environment.OSVersion
                // Example values: "Windows 10 Enterprise"  "Windows Server 2016 Datacenter"
                string productName = (string)Registry.GetValue(
                    @"HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion",
                    valueName: "ProductName",
                    defaultValue: null);
                return productName?.Contains("Server 2016", StringComparison.OrdinalIgnoreCase) ?? false;
            });

````

**Comment by SeeminglyScience** [comment]
@ayeltsov honestly with a C# application, you're probably better off always including that parameter in Core.  Unless you're incredibly careful in your usage of returned objects (i.e. never statically typing them), wincompat mode is going to break you regardless.

**Comment by SteveL-MSFT** [comment]
Unfortunately, it seems that the original issue is "by-design".  If a Windows inbox module manifest does not include `Core` in `CompatiblePSEditions`, then PowerShell 7 will use implicit remoting with Windows PowerShell to load the module.  When this happens, all output is deserialized and the enum becomes a string.  We've worked with Windows teams to update their module manifests to include `Core` where we know it works, but those changes do not get backported to older versions of Windows.  `-SkipEditionCheck` forces `Import-Module` to load the module directly into the pwsh process.  I think the current workaround may be the best solution for now.

**Comment by ayeltsov** [comment]
Ack. We're ok with workaround, and will probably speed up deprecation of Server 2016 as a supported for the app host. 
Not sure what is the protocol for closing the bugs, but I'm Ok with closing
