### ISSUE TITLE
Error result when passing second argument to a cmd script

### ISSUE THREAD

**Issue by v3470** [PowerShell/PowerShell#14739]
To reproduce this case, first, write a cmd script called `echotest.cmd` with the following code:

```cmd
echo %1 %2 %3
```

Second, open PowerShell at its place, then call the script with three arguments:

```powershell
.\echotest.cmd a b c
```

Finally, it will get a result: `a %2 c`. However, what I expected is `a b c` as the result.

----
Environment:
OS: Windows 10 x64, version 10.0.19042
Powershell version: 7.0.3, also tested with 5.1.19041.610
Code page: 65001(Unicode), by default I first tested this under 936(GBK) but get an error encoding text with `%2`.

**Comment by jborean93** [comment]
I cannot seem to replicate this with v5.1 and v7.1, they both output the arguments passed into the script. Do the same thing happen when you run `cmd.exe /c echotest.cmd a b c`?

Could you also try the following?

In Windows PowerShell run this to generate an executable that prints out the raw argv passed to a process. Note this only works in Windows PowerShell so you need to generate the .exe there first.

```powershell
$exePath = Join-Path -Path $pwd.Path -ChildPath 'PrintArgv.exe'

$addParams = @{
    TypeDefinition = @'
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace PrintArgv
{
class Program
{
    [DllImport("Kernel32.dll")]
    public static extern IntPtr GetCommandLineW();

    static void Main(string[] args)
    {
        IntPtr cmdLinePtr = GetCommandLineW();
        string cmdLine = Marshal.PtrToStringUni(cmdLinePtr);

        Console.WriteLine(cmdLine);

        for (int i = 0; i < args.Length; i++)
            Console.WriteLine(String.Format("[{0}] {1}", i + 1, args[i]));
    }
}
}
'@
    OutputType = 'ConsoleApplication'
    OutputAssembly = $exePath
}
Add-Type @addParams
```

Then in both Windows PowerShell and PowerShell run the following (you need to be in the same dir as when you ran the script above)

```powershell
.\PrintArgv.exe a b c
```

In my case I get the output which indicates the arguments are correctly being passed through:

```
"C:\temp\PrintArgv.exe" a b c
[1] a
[2] b
[3] c
```

**Comment by v3470** [comment]
@jborean93 Thanks. I tried it inside two virtual machines, one is Windows 10 en-us, another is Windows 10 zh-cn, both of them can get correct result with the command line. Now I almost confirmed it was my system trouble, maybe I need to reinstall it later.
