### ISSUE TITLE
Introduce a PowerShell-aware path-information class for convenient .NET interoperability

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#14745]
Best practice answers and documentation often refer to .Net methods for file streaming where it concerns performance, e.g. [Processing Large Files](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations?view=powershell-7.2#processing-large-files). But the .Net implementation differs from native PowerShell behavior were it concerns casting expectations and the current directory:

```PowerShell
([io.fileinfo]'.\Test.txt').DirectoryName
C:\WINDOWS\system32
(Get-Item '.\Test.txt').DirectoryName
C:\Users\User\MyScripts
```

Btw. There is currently no accelerator or initiator for files:
```PowerShell
[fileinfo]'.\Test.txt'
```
> InvalidOperation: Unable to find type [fileinfo].

<sub>Note that `[io.fileinfo]'.\Test.txt'` strips the `.\` from every member of the object which means if it is used for a parameter type, you can't discover anymore that the path was relative (using a condition as e.g. `if ($FilePath.Name.StartsWith('.\')) {...`), which means that you can only use a general `string` type for this instead.</sub>

Using .net (streaming) methods generally require more coding therefore it often ends up in a separate function.
As a (spoiled) _PowerShell_ engineer, I would expect to be able to do just this (wishful thinking):

```PowerShell
Function Stream-File([FileInfo]$FilePath) {
    $Stream = [System.IO.StreamReader]$FilePath
    # ...
    $Stream.Dispose()
}

Stream-File .\Test.txt
```
This implies at least two things:
1) The (PowerShell) `FileInfo` constructor needs to accept a relative path that is than joined to the current path (`Join-Path (Get-Location) '.\Test.txt'`) to prevent it expects the file in the `C:\WINDOWS\system32` folder and to be  accelerated to resolve the following error:

> InvalidOperation: Unable to find type [FileInfo].

2) The `[FileInfo]` class should automatically cast to other file classes along with `System.IO.StreamReader` which current results in the following error:

> Cannot convert the "C:\Users\User\MyScripts\Test.txt" value of type "System.IO.FileInfo" to type "System.IO.StreamReader".
InvalidOperation:

**Comment by jborean93** [comment]
This is really a known issue as the .NET methods use the process working directory whereas the PowerShell cmdlets rely on the Runspace location. You can't really keep them in sync because there's only 1 process working dir but multiple Runspaces can exist inside a process. Maybe we just need to add some documentation (if there isn't already) on the best ways to write cmdlets to handle this properly. In my case I usually do the following to handle both `-Path` and `-LiteralPath` when calling .NET methods


```powershell
Function Get-ItemLikeFunction {
    [CmdletBinding(DefaultParameterSetName='Path')]
    param (
        [Parameter(
            Mandatory = $true,
            Position = 0,
            ValueFromPipeline = $true,
            ValueFromPipelineByPropertyName = $true,
            ParameterSetName = 'Path'
        )]
        [SupportsWildcards()]
        [ValidateNotNullOrEmpty()]
        [String[]]
        $Path,

        [Parameter(
            Mandatory = $true,
            Position = 0,
            ValueFromPipelineByPropertyName = $true,
            ParameterSetName = 'LiteralPath'
        )]
        [Alias('PSPath')]
        [ValidateNotNullOrEmpty()]
        [String[]]
        $LiteralPath
    )
    
    begin {
        # Some code here
    }

    process {
        if ($PSCmdlet.ParameterSetName -eq 'Path') {
            $allPaths = $Path | ForEach-Object -Process {
                $provider = $null
                $PSCmdlet.SessionState.Path.GetResolvedProviderPathFromPSPath($_, [ref]$provider)
            }
        }
        elseif ($PSCmdlet.ParameterSetName -eq 'LiteralPath') {
            $allPaths = $LiteralPath | ForEach-Object -Process {
                $PSCmdlet.SessionState.Path.GetUnresolvedProviderPathFromPSPath($_)
            }
        }

        foreach ($filePath in $allPaths) {
            # Each $filePath contains the absolute path resolved from the current PowerShell location
        }
    }

    end {
        # Some code here
    }
}
```

I'm not sure I agree with having a type accelerator for `FileInfo` specifically, this class is not really something I think we should encourage general use off in PowerShell. Usually the same operations that `FileInfo` (and `DirInfo`) are behind the FIleSystem provider included cmdlets like `Get-Item`, `Set-Item`, etc. Anyone wishing for these more advanced methods are probably ok with writing the full type name just like any other .NET class without an accelerator.

**Comment by mklement0** [comment]
Good points, @jborean93: the discrepancy between the working directories makes a solution based on general-purpose (PowerShell-unaware) .NET types impossible.

An additional complication is the lack of support for paths based on _PowerShell_ drives; in the context of the provider cmdlets, this is _on output_ compensated for with _instance_ ETS members such as `.PSPath`, which you don't get when you directly work with these types.

* For improving the function / script-authoring experience with file-system paths, @rkeithhill  has previously suggested introducing a `PathParameter` attribute that `string` parameters can be decorated with - see https://github.com/PowerShell/PowerShell/issues/8819#issuecomment-460102241.

* When passing paths to .NET methods, you have to ensure that you always pass _full, native_ paths, to account for the differing working directories.

  * For an _existing_ file-system item this is easily done with `Convert-Path`.
  * Unfortunately, that currently doesn't work with not-yet-extant items, such as when passing an _output_ file path, which is a real pain point - see #2993.

For general usage, what I do think would make sense is to implement _PowerShell-aware analogs_ to `FileInfo` and `DirectoryInfo`:

In fact, a _single_ new class, `PSPathInfo` that derives from the existing [`System.Management.Automation.PathInfo`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.PathInfo) class  (it is currently sealed, but changing that shouldn't break anyone), may be sufficient:

`PathInfo` is currently used in `Resolve-Path`, and has no public constructor - and it has no type accelerator, which `PSPathInfo` would need, however.

`PSPathInfo` could build on `PathInfo` as a provider-agnostic path-information class, with a public constructor that accepts a path string.

It could add generally useful properties, such as `.BaseName`, `.Extension` and `.ParentPath` and `.ParentProviderPath`, as well as `.Exists` and `.ParentExists` (which would be helpful for output items yet to be created), and an `.ItemType` property that indicates the type of item the path refers to _if it exists_ - along the lines of `Unknown` (path doesn't exist), `File`, `Directory`, `Symlink`, ... (including subtypes of other providers, which most don't have, however).

(With the class' focus on _paths_, it wouldn't have to duplicate additional _item_-specific properties such as `.LastWriteTime`, ...)

As an alternative to `Convert-Path`, you could then do the following when calling .NET methods, which is more efficient:

```powershell
# WISHFUL THINKING
# Equivalent to:
#    [System.IO.File]::ReadAllLines((Convert-Path foo.txt))
[System.IO.File]::ReadAllLines(([PSPathInfo] 'foo.txt').ProviderPath)
```

If `PSPathInfo` is made to stringify to its `.ProviderPath` property (the full, _native_ path, which would be a departure from `PathInfo`, but to me a defensible one; use `.Path` for the PowerShell-drive-based path) we could simplify to:

```powershell
# WISHFUL THINKING
[System.IO.File]::ReadAllLines([PSPathInfo] 'foo.txt')
```

Additionally, `Split-Path` could be enhanced to return such instances with the previously proposed `-All` switch - see #6606.

This would make the following two sample commands equivalent:

```powershell
# WISHFUL THINKING
([PSPathInfo] 'foo.txt').Extension
(Split-Path -All foo.txt).Extension
```

Also allowing `Resolve-Path` to take advantage of the enhanced class would require a _new switch_ (e.g., `-ExtendedInfo`), so as not to break backward compatibility.

**Comment by iRon7** [comment]
@jborean93, @mklement0, thanks for your comments.

@jborean93
Your technically argument/limitation about multiple Runspaces is a little above my head, but to your argument:

> Anyone wishing for these more advanced methods ...

The issue is not just an accelerator but everything that comes alone (I think I have chosen a bad title for this issue).
Meaning the general argument for this purpose is:

 > Anyone wishing to improve the performance (where memory usage / the PowerShell pipeline doesn't matter) and therefore pushed* for .Net methods, wishes the same PowerShell experience as it comes to loosely typed variables and defaults.

(*As recommended in [PowerShell scripting performance considerations](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/powershell/script-authoring-considerations) and a lot of StackOverflow answers.)

@mklement0
> `PSPathInfo` could build on `PathInfo` as a provider-agnostic path-information class, with a public constructor that accepts a path string.

Is indeed something I had in mind (again, I think I have chosen a bad title for this issue, any suggestion for a better one?).

**Comment by mklement0** [comment]
@iRon7, regarding the working directory-discrepancy problem, #3428 has more information, but the problem is easy to visualize as follows:

```powershell
PS> [Environment]::CurrentDirectory = '/'; Push-Location $PSHOME; ([System.IO.FileInfo] 'pwsh.dll').FullName; Pop-Location
/pwsh.dll  # !! .NET's current dir. was used, not PowerShell's.
```

**Comment by mklement0** [comment]
As for a title: perhaps something along the lines of "Introduce a PowerShell-aware path-information class for convenient .NET interoperability"?

**Comment by iRon7** [comment]
@mklement0, thanks, for the runspaces referral, I actually think we are one the same page as I wasn't imaging modifying `system.io.fileinfo` by itself but actually placing a PowerShell object/class (as e.g. `[PSFileInfo]`) on top of it where I guess that your suggestion for `[PSPathInfo]` on top of `System.Management.Automation.PathInfo` is actually better.

**Comment by rkeithhill** [comment]
The Engine WG reviewed this issue today.  Calling .NET methods with relative paths is a pain point we recognize but we don't believe there is enough value in adding another type e.g. `[PSPathInfo]` just for this scenario when you can use `"$pwd\Test.txt"`.  We do suggest submitting an enhancement request to PSSA for a rule that warns about sending relative paths to .NET members.

**Comment by mklement0** [comment]
@rkeithhill, to be clear: `"$pwd\..."` will _typically_ work, but _not_ in the following cases:

* The current PowerShell location is based on a _PowerShell-only_ file-system drive.
* The current PowerShell location is _not a file-system location_.

The rationale for suggesting `[PSPathInfo]` was that users _wouldn't have to worry about these edge cases_...

**Comment by iSazonov** [comment]
>  as you cannot know which .NET method parameters represent file-system paths

I saw in C# design repository a _rejected_ proposal to define new types based on strings. Another option could be to ask in .Net Runtime repository to introduce new attribute to annotate "paths". (For third-party API-s we could do annotations with out ETS.)

---

I bit wonder why the issue is under WG-Engine, I'd expect WG-Providers :-)

---

Despite the absolute freeze on this project (only the occasional functional PRs) I haven't given up hope for innovation and have been devoting a lot of time to Providers lately. I tend to think that we will need not even one, but several types for paths to make Providers faster and more reliable.
I don't see the need for them to have public constructors yet. If such a need was objective, it would have been done long ago in the .Net Runtime. At the same time right now PowerShell Providers do a lot of unnecessary internal work without well-done types for paths.

**Comment by iRon7** [comment]
> it wonder why the issue is under WG-Engine, I'd expect WG-Providers :-)

Maybe this should indeed be more general and even go deeper... (needless to say that I am missing some in-depth knowledge here to oversee the whole implication), but a common `[Item]` type (interface?) might do the trick (including for all other providers). Meaning instead of:

```PowerShell
[System.IO.File]::ReadAllLines((Get-Item  .\foo.txt))
```
I might do things along with:
```PowerShell
[System.IO.File]::ReadAllLines([Item] '.\foo.txt')

Function Stream-File([Item]$FilePath) {
    $Stream = [System.IO.StreamReader]$FilePath
    # ...
    $Stream.Dispose()
}
```

This will mean that the result of the `[Item]` casting depends on the current provider if the drive is not provided (as with `*-Item` cmdlets) but it shows how basal this request is.

**Comment by iSazonov** [comment]
@iRon7 What is `.\foo.txt` in follow contexts?
- `Get-Item  .\foo.txt`
- `[System.IO.File]::ReadAllLines(".\foo.txt")`

Obviously we all can say it is `Path`.
Next question if we know it is `path` can PowerShell know this too?
Yes, only if PowerShell has a meta data. For Get-Item it has. For .Net method it hasn't.
We could add the meta data with ETS. Or get from .Net if there would be an specific attribute.

Also notice, PowerShell path it is not only file system path. PowerShell path is used for other Providers too. So we should say about generic means.

With the meta data PowerShell has no needs to have specific types with public constructor like `[Item]` - PowerShell can recognize context and does things _magically_.

**Comment by iRon7** [comment]
@[iSazonov](https://github.com/iSazonov),

> We could add the meta data with ETS. Or get from .Net if there would be an specific attribute.

Sounds like a Catch22 (we can't get it into ETS because there is no specific .Net attribute and we can't convert it to a .Net class be cause there is no ETS), the point that I was trying to make is that there is actually a common attribute *in a PowerShell* for the concerned **Item** (as from `Get-Item` independent of its provider) which is: `PSPath` (and also `PSProvider`).

Your referral to ETS, let me read the [ETS documentation](https://docs.microsoft.com/en-us/powershell/scripting/developer/ets/overview) again:

> Therefore a script developer must have the ability to state the type of one of their variables and build up their own set of dynamically typed "objects" that contain properties and methods and can participate in the type-driven system. ETS solves this problem by providing a common object for the scripting language that has the ability to state its type dynamically and to add members dynamically.
> Fundamentally, ETS resolves the issue mentioned previously by providing the **PSObject** object, which acts as the basis of all object access from the scripting language and provides a standard abstraction for the cmdlet developer.

(Somehow, it feels like **ETS** literally misses a fundamental **item** for this specific issue.)

Anyways,

> With the meta data PowerShell has no needs to have specific types with public constructor like [Item] - PowerShell can recognize context and does things *magically*.

? ... not for this issue.
Unless I would be able to tell PowerShell it concerns an `item` (as in `get-item`).

For this, I have created a very simple PowerShell class:

<details>
  <summary>Item class (prototype)</summary>
  
```PowerShell
class Item {
    [object]$Object
    Item([object]$Path) {
        if ($Path -is [string]) {
            $this.Object = Get-Item -LiteralPath $Path
        }
        elseif ($Path.PSObject.Properties.Name -Contains 'PSPath') {
            $this.Object = $Path
        }
        else {
            Throw "Cannot convert value ""$Path"" to type ""$($Path.GetType())"" to type ""Item""."
        }
    }
    [string]ToString() {
        return $This.Object.ToString()
    }
}
```
</details>

Note that the class returns a `string` (`$This.Object.ToString()`) rather than the object itself (`$This`). I was not able to do this in PowerShell (or it might not even be possible at all). Nevertheless, it shows that I would be able to convert the path string to a PowerShell `item` object which contains an ETS with an absolute path:

```PowerShell
$Item = [Item]'.\Test.txt'
[string]$Item
C:\Users\user\Scripts\Test\PowerShell\Item\Test.txt
```

or:

```PowerShell
[System.IO.File]::ReadAllLines([Item]'.\Test.txt')
```

> Also notice, PowerShell path it is not only file system path. PowerShell path is used for other Providers too. So we should say about generic means.

Yes, I do notice that. As with the `Get-Item` cmdlet it assumes the current provider (usual the `FileSystem`) but in the idea, you might also do something specific like:

```PowerShell
[Item]'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion'
```

**Comment by iSazonov** [comment]
> ```powershell
> [System.IO.File]::ReadAllLines([Item]'.\Test.txt')
> ```

If you want manually annotate in such way you have no need `Item` - you already can make this with `Convert-Path`
```powershell
PS C:\Windows\System32> Convert-Path .\1040\
C:\Windows\System32\1040\
PS C:\Windows\System32> Convert-Path Temp:\.ses
C:\Users\1\AppData\Local\Temp\.ses
PS C:\Windows\System32>
```
If you want to get thing magic and transparent you are forced to have a _meta data_. Now you can have meta data for source (that Get-Item returns - PSPath) but you haven't meta data for target - .Net method _path_ parameter itself.

**Comment by mklement0** [comment]
I know this thread is getting long, but [we've been through both before](https://github.com/PowerShell/PowerShell/issues/14745#issuecomment-776282779):

* If `Convert-Path` were to finally be made to work with _nonexistent_ paths, such as when you're _creating_ a file - see https://github.com/PowerShell/PowerShell/issues/2993. -  then yes, `[System.IO.File]::ReadAllLines((Convert-Path '.\Test.txt'))` would be a robust idiom - and one that isn't even dependent on the provider underlying the current location, given that explicit mandate of `ConvertTo-Path` is to return a native _file-system_ path.

  * That said, it's far from obvious, syntactically verbose, and somewhat heavy-handed, given the need for a cmdlet call - and for full robustness you'd need to use `[System.IO.File]::ReadAllLines((Convert-Path -LiteralPath '.\Test.txt'))` with literal paths.

* `[PSPathInfo] '.\Test.txt'` is syntactically simpler and doesn't require a cmdlet call. Also, as the linked comment proposes, this use of `[PSPathInfo]` (implicit stringification to its `.ProvderPath` property) would just be a side benefit of the parsing capabilities this type would provide, both in direct use and via parameters declared with this type.

If we could do away with the need for _either_ workaround, then all the better - but, @iSazonov, from what I can tell this isn't really an option in this case: 
.NET won't accommodate us by adding metadata identifying file-system path parameters in APIs, since the problem is specific to PowerShell - and I don't think adding this metadata on the PowerShell side is feasible (leaving aside that third-party APIs would have to add metadata too).

**Comment by iSazonov** [comment]
> If Convert-Path were to finally be made to work with nonexistent paths

Why not implement? :-) This could be useful in other scenarios too.

> NET won't accommodate us by adding metadata identifying file-system path parameters in APIs, since the problem is specific to PowerShell

We never asked them. :-)

>  I don't think adding this metadata on the PowerShell side is feasible

We already do this for type extensions and formatting. If it's a _really useful_ feature, we could do it for path annotation too (in community module for example).
