### ISSUE TITLE
Display category & module in the output of Get-Help command

### ISSUE THREAD

**Issue by yihuajack** [PowerShell/PowerShell#14774]
## Summary of the new feature/enhancement

As a user I want to acquire "Category" and "Module" information while I precisely ask "Get-Help" command for documentation so that I can easily find where the command belongs to.

For example, if I want to get help of the command "Write-Prompt" and run `Get-Help Write-Prompt` (even with parameter `-Full`) I only know its NAME, SYNOPSIS, SYNTAX, DESCRIPTION... If I want to know its "Category" or "Module", I have to do weird things like running `Get-Help Write-P` (I have not found any other simple ways to do that).

## Proposed technical implementation details (optional)

`Get-Help` command could list the command's "Category" and "Module" (it's not lengthy, if so, they could be put in `-Full` or `-Detailed` output).

**Comment by sdwheeler** [comment]
You can use `Select-Object`.

```
PS> get-help Write-Prompt | Select-Object Category, ModuleName

Category ModuleName
-------- ----------
Function posh-git
```

**Comment by yihuajack** [comment]
Thanks for telling me this
