### ISSUE TITLE
Get-PhysicalDisk runs in memory leak

### ISSUE THREAD

**Issue by godofglow** [PowerShell/PowerShell#14779]
If you run Get-PhysicalDisk (in a powershell-loop or called from a C# application) you will see after after hundreds/thousands of runs a memory-leak.

// Test-Script
![image](https://user-images.githubusercontent.com/39702056/107786499-49533a80-6d4e-11eb-891f-2146aa29b294.png)

// System-Enviroment
![image](https://user-images.githubusercontent.com/39702056/107786490-448e8680-6d4e-11eb-8288-7c7aac9f3a2b.png)

**Comment by ThomasNieto** [comment]
This repository is for PowerShell 6.0+. The version you used is Windows PowerShell. 

As for your question does the memory get reclaimed by running `[System.GC]::Collect()`

**Comment by godofglow** [comment]
> This repository is for PowerShell 6.0+. The version you used is Windows PowerShell.

Did the same test with PS 6.0 - same behavior.
Also with addition garbage collector (see below)


> 
> As for your question does the memory get reclaimed by running `[System.GC]::Collect()`

No other behavior - still see an increasing memoy

**Comment by daxian-dbw** [comment]
@godofglow At what magnitude did you see the possible memory leak when running `Get-PhysicalDisk` in a loop?

I run the following script from PowerShell 5.1 for 4 hours. I did see the private working set went up and down, but it's not very convincing to say there is a leak.

```powershell
while($true) {
    $null = Get-PhysicalDisk
    sleep -Seconds 1
}
```

I took 5 snapshots of the memory using `VMMap` at 48 minutes, 85 minutes, 91 minutes, 117 minutes, and 240 minutes. 
The snapshots are attached in the end, and here is a table to summarize the private working set changes:

| Timestamp         | Private WS (PWS)    | Managed heap in PWS  | Native heap in PWS  |
| ------------------| ----------------------| ---------------------------| -----------------------|
| 48 minute          | 285 MB                    | 115 MB                           | 158 MB                     |
| 85 minute          | 400 MB                    | 114 MB                           | 274 MB                     |
| 91 minute          | 190 MB                    | 15 MB                             | 169 MB                     |
| 117 minute        | 272 MB                    | 17 MB                             | 249 MB                     |
| 240 minute        | 354 MB                    | 62 MB                             | 285 MB                     |

Throughout the 4 hours of execution, the managed memory was pretty stable.
Native memory appeared to be increasing, but at the 91 minute, the private working set suddenly dropped, and you can see both the managed and native memory reduced in great deal.
Afterwards, the managed memory slightly increased, and native memory increased by 120 MB over the next 2+ hours.

I didn't continue the measurement, but considering the sudden memory drop at 91 minute, it could happen again if the execution continues. By looking at the memory changes during the 4 hours, it's not convincing to say there is a memory leak.



#### 48-minute snapshot
![48min-capture](https://user-images.githubusercontent.com/127450/108578693-39040800-72d8-11eb-95ed-ce432bdf2be4.PNG)

#### 85-minute snapshot
![85min-capture](https://user-images.githubusercontent.com/127450/108578688-37d2db00-72d8-11eb-90a3-5080db0dd690.PNG)

#### 91-minute snapshot
![91min-capture](https://user-images.githubusercontent.com/127450/108578689-386b7180-72d8-11eb-996e-7bc3c827bea1.PNG)

#### 117-minute snapshot
![117min-capture](https://user-images.githubusercontent.com/127450/108578690-386b7180-72d8-11eb-930b-af254b40da96.PNG)

#### 240-minute snapshot
![240min-capture](https://user-images.githubusercontent.com/127450/108578691-39040800-72d8-11eb-9254-a11196642547.PNG)

**Comment by daxian-dbw** [comment]
Thanks to @StevenBucher98 for getting in contact with the owner team of the `Storage` module, we got response from the owner team that they can reproduce the leak with `Get-PhysicalDisk`, and they are working on a fix.

**Comment by iSazonov** [comment]
Close as external.
