### ISSUE TITLE
Add SuppressAnalyzer type alias

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#14784]
## Summary of the new feature/enhancement

As a script author, I want to _shorten_ the repetitive line required to suppress ScriptAnalyzer rules.

Currently, every time I need to suppress a rule I end up with lines that over 120 characters long even without a justification, and shortening the type name from `System.Diagnostics.CodeAnalysis.SuppressMessageAttribute` would make a big difference.  You wouldn't think it happens that often, but since so many of the rules are very broad (e.g. flagging "CredentialName" as a "PSAvoidUsingPlainTextForPassword") I have to suppress things all the time, and it's a mite ridiculous:

```PowerShell
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', '', Target='GitCredentialName', Justification='This is not a password')]
param(
[Parameter(Mandatory)]
$GitCredentialName
)

$Credential = Get-Secret $GitCredentialName
```

## Proposed technical implementation details (optional)

Add a built-in type alias for [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute]

Ideally `[SuppressAnalyzer]` but I'll settle for `[SuppressMessage]` which is what I type now after adding a `using namespace System.Diagnostics.CodeAnalysis` at the top.

Of courser, I'd be happy to settle for anything shorter, like "BeQuiet" or "YeahIKnowBut" ...

### I don't think this can be handled in the PSScriptAnalyzer module

In order to avoid type not found errors, the type alias would need to be _built in_, since this attribute ends up applied to scripts and functions in every context.

**Comment by iSazonov** [comment]
SuppressMessageAttribute name is unique in .Net do I think it makes no sense to use another name.

**Comment by Steg17** [comment]
👌

**Comment by bergmeister** [comment]
I'd propose to call this new alias `SuppressMessageAttribute` to keep it as close as possible to the actual thing.
I tested such a change and can confirm it works. I observed though that when using this aliases for PowerShell versions without this this alias, PSScriptAnalyzer does not throw but just ignored the attribute, I initially expected it to throw an error, not sure it this is what the behaviour should be and if this should be improved

**Comment by Jaykul** [comment]
Hypothetically, @bergmeister in the PSScriptAnalyzer module you can _also_ create the accelerator, so that the accelerator would work **whenever the module is loaded** regardless of the PowerShell version:

```PowerShell
$xlr8r = [psobject].assembly.gettype("System.Management.Automation.TypeAccelerators")

if ($xlr8r::AddReplace) {
    $xlr8r::AddReplace("SuppressMessageAttribute", [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute])
} else {
    $null = $xlr8r::Remove("SuppressMessageAttribute")
    $xlr8r::Add("SuppressMessageAttribute", [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute])
}
```

**Comment by JamesWTruher** [comment]
the WG-Engine agrees this would be a welcome change and improve the interaction of analyzer, we've added the WG-Security label to get their opinion as to any security implications of this change (since it would become a new "well-known" type).

**Comment by Jaykul** [comment]
We still need this, and it should be trivial to add.
