### ISSUE TITLE
Calculated properties return null when passed into pwsh via -Command argument

### ISSUE THREAD

**Issue by fatherofinvention** [PowerShell/PowerShell#14789]
## Description
Calculated properties do not return values when passed into `pwsh` via the `-Command` argument.

## Steps to reproduce

- Open terminal and run the following command:

`pwsh -c "@{ items = @( Get-Process | Select -Last 5 @{n='title';e={$_.ProcessName}},@{n='subtitle';e={$_.ID}} | ? 'title' -ne '' )} | ConvertTo-Json"`

- To prove that the calculated columns are the issue, remove them and select default property names which returns values as expected.

`pwsh -c "@{ items = @( Get-Process | Select ProcessName, ID -Last 5 )} | ConvertTo-Json"`

## Expected behavior

- If you launch `pwsh` first and run the following command instead of passing it in via the -Command argument, you will get the expected results:

```powershell
@{ items = @( Get-Process | Select -Last 5 @{n='title';e={$_.ProcessName}},@{n='subtitle';e={$_.ID}} | ? 'title' -ne '' )} | ConvertTo-Json
```

```json
{
  "items": [
    {
      "title": "webinspectord",
      "subtitle": 10489
    },
    {
      "title": "WiFiAgent",
      "subtitle": 541
    },
    {
      "title": "WiFiVelocityAge",
      "subtitle": 610
    },
    {
      "title": "XprotectService",
      "subtitle": 9203
    },
    {
      "title": "zsh",
      "subtitle": 11330
    }
  ]
}
```

## Actual behavior

```json
{
  "items": [
    {
      "title": null,
      "subtitle": null
    },
    {
      "title": null,
      "subtitle": null
    },
    {
      "title": null,
      "subtitle": null
    },
    {
      "title": null,
      "subtitle": null
    },
    {
      "title": null,
      "subtitle": null
    }
  ]
}
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
* If you're calling this _from a POSIX-compatible shell_ such as `bash` or `zsh`, you must `\`-escape the `$` characters inside the `"..."` argument in order for them to be passed through to PowerShell (otherwise, the calling shell interprets them):


```
# From bash or zsh, for instance
$ pwsh -c "@{ items = @( Get-Process | Select -Last 5 @{n='title';e={\$_.ProcessName}},@{n='subtitle';e={\$_.ID}} | ? 'title' -ne '' )} | ConvertTo-Json"

```

* If you're calling _from PowerShell itself_, the best approach is to pass the `-Command` argument _as a script block_, which also prevents up-front expansion by the caller and additionally supports getting rich types in the output and preserving PowerShell's output streams (with the same type-fidelity limitations as in background jobs / remoting).

**Comment by fatherofinvention** [comment]
@mklement0 **thank you!** In that case I will close this out since it isn't actually a bug.
