### ISSUE TITLE
Change the "New version of PowerShell" message"

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#14797]
We regularly see Issues like #14772 being raised

We could stop this with an update to the message that is displayed when a new version is available to download

I am happy to get a PR raised for this

**Comment by 237dmitry** [comment]
The message depends on `-NoLogo` parameter and user `$profile`. For example, I did not receive it. Can you send message as a system notification?

**Comment by SpiritualBoss** [comment]
> The message depends on `-NoLogo` parameter and user `$profile`. For example, I did not receive it. Can you send message as a system notification?

**Comment by MyTime1969** [comment]
PowerShell ver.7.1.2 is not relesed on Microsoft Store.

**Comment by eitsupi** [comment]
Similar request #14780

**Comment by daxian-dbw** [comment]
We would want to fix the release pipeline, to hold on publishing the release until all packages are available.
