### ISSUE TITLE
metamorphism++

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14795]
```
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      1      0
```

Hi Guys !!

here an example to demonstrate the new feature

first create base class
```

PS C:\> class foo {
>>        $say = 'hello'
>>       [string] sayhello($name) {
>>          return '{0} {1}' -f $this.say, $name
>>        }
>> }

```

work well
```

PS C:\> [foo]::new().sayhello('world')
hello world

```

create a child class with the same  method 'sayhello' to overid the base method class
```

PS C:\> class bar : foo {
>>         [string] sayhello($name) {
>>             return "power${name}"
>>         }
>>    }
PS C:\>

```
work well

```


PS C:\> [bar]::new().sayhello('shell')
powershell
```

but sometimes we need to append the result to method "sayhello" in base class and the method "sayhello" in our child class.... like in ruby with "super" keyword 

this example demonstate the  behaviour missing in powershell. in this example i use "super" keyword
```

PS C:\> class bar : foo {
>>         super [string] sayhello($name) {
>>             return "power${name}"
>>         }
>>    }

PS C:\> [bar]::new().sayhello('shell')
hello shell
powershell
```

**Comment by zett42** [comment]
Currently you can call a method of the base class like this, but it requires an ugly type cast (see [about_Classes](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes?view=powershell-7.1#invoke-base-class-methods)):

```powershell
class bar : foo {
    [string] sayhello($name) {
        return ([foo] $this).sayhello($name) + "`npower${name}"
    }
}
```
Output:
<pre>
hello shell
powershell
</pre>

I would prefer to call the base class without having to repeat its name and without casting, similar to C#'s `base` keyword:
```powershell
class bar : foo {
    [string] sayhello($name) {
        # Currently not possible!
        return $base.sayhello($name) + "`npower${name}"
    }
}
```

**Comment by p0W3RH311** [comment]
@zett42  thanks,

the problem with your ideas

1)         return ([foo] $this).sayhello($name) + "`npower${name}"

is uggly

2)         return $base.sayhello($name) + "`npower${name}"

its better but it need to write explicitly the code (sometimes is good) but not all the times...imagine you have a child class inherit to a base class and the base class inherit to a super class ? OR imagine your call to method is repeated in other methods...its preferable to use a new keyword to do this...but still your idea a good idea and maybe the 2 ideas is good to implement.

example of problems:

```
 class b  {
    funct() {}
}

class c : b {
    super funct() {}
}

class d : b {
    super funct() {}
}

class c : b {
    super funct() {}
}
```

it less typing

**Comment by SeeminglyScience** [comment]
> the problem with your ideas

Just to be clear, that's not an idea, that's how the PowerShell team decided to implement that functionality.  Like that works already.

`$base` would have been nice, but implementing it today may not be feasible without breaking changes.

**Comment by p0W3RH311** [comment]
@SeeminglyScience 

thanks...the idea come from [Ruby](https://stackoverflow.com/questions/4632224/super-keyword-in-ruby) .

**Comment by SeeminglyScience** [comment]
> thanks...the idea come from [Ruby](https://stackoverflow.com/questions/4632224/super-keyword-in-ruby) .

Looks like (from that SO at least) it's called in a similar way as `$base` would be (e.g. it's a method body keyword, not a method signature keyword).  And it makes a little bit more sense there since they're doing the equivalent of `Write-Host` rather than actually trying to join return values.

---

It **would** be nice to have a better way to call a method on the base class, even if it doesn't come up all that often.
