### ISSUE TITLE
Feature Request: Auto update/upgrade from a server

### ISSUE THREAD

**Issue by hasanparasteh** [PowerShell/PowerShell#14790]
Hi
When I open PowerShell I get a message that there's a new version of PowerShell available to install and gives me a link to this GitHub page.
```
  A new PowerShell stable release is available: v7.1.2
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.1.2
```
 If it can understand that there's a new version why there's no command like `shell-upgrade` to auto-download and install the newer version itself? it would be great and easier to update/upgrade the shell and don't need extra stuff.

**Comment by mklement0** [comment]
Please see #12678 and #14217

**Comment by hasanparasteh** [comment]
Thanks
