### ISSUE TITLE
How to get credentials from task scheduler in powershell

### ISSUE THREAD

**Issue by bhuvaneswari01** [PowerShell/PowerShell#14813]
How to get credentials from task scheduler in powershell?

The main requirement we should not keep the credentials in scripting . whenever script is running credentials are automatically taken from task scheduler. Like that i need the scipt.

Is there any possibility in task scheduler or powershell?

**Comment by daxian-dbw** [comment]
@bhuvaneswari01 It's better to post your question to stackoverflow, or use the [Discussion](https://github.com/PowerShell/PowerShell/discussions) tab instead.
