### ISSUE TITLE
Set-Clipboard Linux

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#14811]
## Summary of the new feature/enhancement
PowerShell's `[SG]et-Clipboard` functional independence.

How to work with the clipboard in Linux using PowerShell? If the cmdlet `Get-Clipboard` requires installing `xclip` (gcb is a stub?), then what about `Set-Clipboard`? You can certainly use native utilities, but why then useless cmdlets?

#### My Environment
OS: KDE neon User Edition 5.20 x64
PowerShell v7.1.2 (manual install: download, unpack, symlink to /usr/bin)
xclip v0.13-1

**Comment by mklement0** [comment]
`xclip` is used by _both_ commands, as it supports both copying to and retrieving from the clipboard.

The problem with Linux platforms is that they can have a variety of GUI shells (if any), so there's no single utility or API that provides clipboard access on all of them.

The X11-based [`xclip` utility](https://github.com/astrand/xclip) works on all GUI shells (desktops) that are [X11](https://en.wikipedia.org/wiki/X_Window_System)-based, such as on Ubuntu, a popular Linux distro.

While `xclip` may not be _preinstalled_, PowerShell does take advantage of it _if present_.

> but why then useless cmdlets?

As a _multi-platform_ shell, PowerShell aims to provide commands that work the same on _all_ supported platforms.

With `xclip` present on a Linux distro, that aim is met (with respect to _text_ - see #14758).

In its absence, the aim is met to a _limited_ degree, via a _PowerShell-specific_ clipboard scoped to the _current session_. That is, you can _pair_ `Set-Clipboard`  and `Get-Clipboard` calls - and `Get-Clipboard` then only sees content copied by `Set-Clipboard`, not by other commands - though you won't have access to the platform's true, cross-process clipboard.

**Comment by 237dmitry** [comment]
> xclip is used by both commands

Only one of them does not work correctly. Set-Clipboard does add text to the clipboard, but it has to be interrupted by ^C or it will occupy the console. Look at the screenshot and note the duration of the Set-Clipboard execution (stopped by hand)
![ss-20210216060405](https://user-images.githubusercontent.com/78153320/108013828-8acd3980-701d-11eb-9c99-9dee7d4dbb2a.png)

**Comment by mklement0** [comment]
Good point - I also see the problem in 7.1.2 and 7.2.0-preview.3, on Ubuntu 18.04, and this is clearly a bug.

The problem must be related to how PowerShell waits for `xclip` to exit.

Please update your original post with the details of your environment, as requested in the issue template, and please change the issue title to reflect that `Set-Clipboard` on Linux with `xclip` present  _hangs_.

The workaround for now is to use `xclip` explicitly; e.g., `'foo' | xclip -selection clipboard`

**Comment by mklement0** [comment]
@iSazonov, can you please re-tag as a _bug_ (`'foo' | Set-Clipboard` copies, but then _hangs_, in both 7.1.2 and Core 7.2.0-preview.3)?

It looks like one that is both serious and easy to fix.

**Comment by iSazonov** [comment]
> can you please re-tag as a bug

Now it is in Work Groups competence :-) so I stopped all review work on issues.

**Comment by ehmiiz** [comment]
Works great with xclip (fedora 36) - however I had to dig into the docs to even realize it was dependent on xclip, would be great with a if a warning / error msg that would say this if xclip is not present
