### ISSUE TITLE
Reinstate New-EventLog and similar cmdlets

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#14812]
.NET Core again supports the APIs that New-EventLog and similar used to use, so we can bring back some of the cmdlets. While the *-WinEvent cmdlets are the replacement for the EventLog cmdlets in general, there is no equivalent functionality to create your own eventlog and write events to it.

```
[D:\Lee\Cookbook4\windows-powershell-cookbook-4e]
PS:52 > [system.diagnostics.eventlog] | gm -static

   TypeName: System.Diagnostics.EventLog

Name                  MemberType Definition
CreateEventSource     Method     static void CreateEventSource(string source,
Delete                Method     static void Delete(string logName), static v
DeleteEventSource     Method     static void DeleteEventSource(string source)
Equals                Method     static bool Equals(System.Object objA, Syste
Exists                Method     static bool Exists(string logName), static b
GetEventLogs          Method     static System.Diagnostics.EventLog[] GetEven
LogNameFromSourceName Method     static string LogNameFromSourceName(string s
new                   Method     System.Diagnostics.EventLog new(), System.Di
ReferenceEquals       Method     static bool ReferenceEquals(System.Object ob
SourceExists          Method     static bool SourceExists(string source), sta
WriteEntry            Method     static void WriteEntry(string source, string
WriteEvent            Method     static void WriteEvent(string source, System
```

**Comment by tmmuessig** [comment]
+1, please bring this back

**Comment by rjmholt** [comment]
> +1, please bring this back

If you add a 👍 to the issue description, that is queryable through GitHub's UI and APIs.

**Comment by JamesWTruher** [comment]
Since the current compilation simply omits the `EventLog.cs` file during compilation it's hypothetically possible to delete the omission, however, we are still missing validation for these cmdlets which would need to be created. This does not seem like an overriding priority, so it would be useful if folks could help us understand the importance of this in the real world.

**Comment by iSazonov** [comment]
Now there are much more relevant extensions for logging that work in cross-platforms, but which PowerShell does not support in any way - this direction looks preferable.
