### ISSUE TITLE
Array.Sort method call situationally ignores string-comparer argument

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14829]
Note: 

* The problem occurs if the the array elements are invisibly `[psobject]`-wrapped, as happens when you create an array via a `Write-Output` call, for instance.

* As such, it is another manifestation of #5579.

`Array.Sort()` is just _one_ manifestation: any .NET method call with an `array` / `object[]`-typed array argument that relies on seeing the true array element types rather than their incidental `[psobject]` wrappers will behave unexpectedly from the user's perspective.

## Steps to reproduce

```powershell
# OK, with array constructed *by an expression*.
$a = "b", "ä", "a"; [Array]::Sort($a, [StringComparer]::Ordinal)
$a -join ' ' | Should -Be "a b ä"  # OK - non-ASCII character ä comes LAST in ordinal sorting.

# !! BROKEN, with array constructed via Write-Output, resulting in
# !! individually [psobject]-wrapped strings.
$a = Write-Output "b", "ä", "a"; [Array]::Sort($a, [StringComparer]::Ordinal)
$a -join ' ' | Should -Be "a b ä"  # !! BROKEN - outputs "a ä b" instead
```

## Expected behavior

Both tests should succeed, as it shouldn't matter how the array is constructed.

## Actual behavior

The 2nd test fails:

```none
Expected strings to be the same, but they were different. String lengths are both 5. Strings differ at index 2. 
Expected: 'a b ä' But was:  'a ä b'
```

That is, the string-comparer argument was effectively ignored, because the `.Sort()` method saw `psobject` instances, not _strings_.

## Environment data

```none
PowerShell Core 7.2.0-preview.3
```

**Comment by SeeminglyScience** [comment]
This may just need to be documented.  I'm not sure what the binder can really do here other than iterate `object[]` arrays looking for `PSObject`'s to replace with the underlying object. Plus nested arrays, other complex objects like hashtable, etc.

This is also one of the few situations where autonull can leak into a dotnet method.

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience. I agree that trying to fix the problem in the binder is not the right place (and that documentation is called for, for old PowerShell versions alone).

The larger question is if we can eliminate the `[psobject]` wrapping that automatically happens when _compiled_ cmdlets (only) call `.WriteObject()` - I don't know if these wrappers are ever _needed_, but as this example and the other ones in  #5579 show, they certainly cause subtle bugs - and no one should be _relying_ on them, given that they're implementation details.

Compiled cmdlet:

```powershell
Add-Type @'
using System.Management.Automation;
[Cmdlet("Get", "Foo")]
public class GetFooCmdlet : PSCmdlet {
  protected override void ProcessRecord() {
    WriteObject(42);
  }
}
'@ -PassThru | % Assembly | Import-Module

(Get-Foo) -is [psobject] # -> $true - the [int] instance was [psobject] wrapped
```

PowerShell code:

```
# ---
function Get-Foo { 42 }

(Get-Foo) -is [psobject] # -> $false - NO [psobject] wrapper
```
