### ISSUE TITLE
"File name too long" when running borgbackup on OSX via pwsh

### ISSUE THREAD

**Issue by futuralogic** [PowerShell/PowerShell#14833]
## Steps to reproduce

```powershell
# Set my repo access key as an env variable which is used by borg to decrypt the archives. String is 1,368 characters
$Env:BORG_PASSCOMMAND=$(security find-generic-password -a $Env:USER -s borg-passphrase -w)
# Repo path
$REPO="/Volumes/Backups/nas"
# List archives in the repo
borg list $REPO
```

## Expected behavior

A list of repos

```none
# Borg output when it lists repos:
archive1-2018-02-26-19-57            Mon, 2018-02-26 19:57:53 [5c2b...]
archive1-2018-03-27-18-06            Tue, 2018-03-27 18:06:12 [cbda...]
archive1-2018-10-07-22-57            Sun, 2018-10-07 23:08:16 [7871...]
...
```

`borg` works reliably under `bash` shell on same machine.

## Actual behavior

```none
> borg list $REPO
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4529, in main
  File "borg/archiver.py", line 4461, in run
  File "borg/archiver.py", line 153, in wrapper
  File "borg/helpers.py", line 375, in load
  File "borg/crypto/key.py", line 134, in key_factory
  File "borg/crypto/key.py", line 594, in detect
  File "borg/crypto/key.py", line 435, in env_passphrase
  File "borg/crypto/key.py", line 449, in env_passcommand
  File "subprocess.py", line 316, in check_output
  File "subprocess.py", line 383, in run
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1289, in _execute_child
OSError: [Errno 63] File name too long

Platform: Darwin nameless.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
Borg: 1.1.11  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 55531  CWD: /Users/nameless
sys.argv: ['/usr/local/bin/borg', 'list', '/Volumes/Backups/nas']
SSH_ORIGINAL_COMMAND: None
```

#### Console (OSX log app - Errors & Faults) shows:

`error	16:51:37.793204 -0600	pwsh	nw_path_close_fd Failed to close guarded necp fd 117 [9: Bad file descriptor]`

(Consequently, I notice this same error being logged from Visual Studio Code - perhaps because I use pwsh as my embedded terminal shell?) 

I am running these commands from pwsh inside vs code.  However, running pwsh via iterm2 results in the same issues.

For reference:
`error	16:58:45.133980 -0600	Code Helper (Renderer)	nw_path_close_fd Failed to close guarded necp fd 41 [9: Bad file descriptor]`

I considered reporting this over on borgbackup but this only occurs under pwsh.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@TravisEz13 Can you please take a look at this issue and label it accordingly?

**Comment by TravisEz13** [comment]
@futuralogic  did you `chsh` your shell to `pwsh`?

**Comment by futuralogic** [comment]
I did not, I am primarily launching pwsh from iterm2 or vscode.

My profile in iterm2 launches: `/usr/local/microsoft/powershell/7/pwsh`

Based on the error message, I was kind of wondering if the filename too long may be the environment variable holding my repo key?  Is there potentially an issue handing off the env variable to python where it seems to truncate it?  I was just going that direction because the stack trace shows it breaking right after borg seems to be getting the environment variables.  Since Env: is mounted as a filesystem provider in Powershell, I didn't know if that may be a thought.

> @futuralogic did you `chsh` your shell to `pwsh`?
> 
> Because I cannot reproduce this issue.

**Comment by TravisEz13** [comment]
> Is there potentially an issue handing off the env variable to python where it seems to truncate it? I was just going that direction because the stack trace shows it breaking right after borg seems to be getting the environment variables. Since Env: is mounted as a filesystem provider in PowerShell, I didn't know if that may be a thought.


1. ENV: is mounted as a provider.  We don't have any other filesystem providers other than filesystem on macOS.  Unless borgbackup integrates with PowerShell, this is highly unlikely.
2. the failure is happening pretty deep inside borgbackup.  The encryption key could be wrong.
3. I verified I can echo a variable in bash of length 1368

**Comment by TravisEz13** [comment]
I think you would need borgbackup to investigate and figure out what is happening and then possibly come back to us.
