### ISSUE TITLE
PowerShell MSI installer crashes when other pwsh processes are closed

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#14831]
The PowerShell (stable and preview) MSI installers have an issue where they get stuck trying to close existing PowerShell processes and then crash when those processes are killed manually.

This issue is most prominent from the PowerShell extension for VSCode (see https://github.com/PowerShell/vscode-powershell/issues/3133) but can be reproduced independently.

## Steps to reproduce

- Have PowerShell process open
- Run MSI installer that will need to pave over existing open process
- Tell MSI to close open processes (and watch it stall)
- Close open PowerShell process

![msi_crash](https://user-images.githubusercontent.com/7009879/108252118-1f629500-710d-11eb-84cf-0eed123f88c5.gif)

## Expected behavior

The MSI successfully ends the processes it targets, or at least can continue when those processes are closed manually.

## Actual behavior

The MSI installer process crashes and the PowerShell installation is left in a dubious state.

## Environment data

```
> systeminfo | select -first 2 -skip 2
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
```

The example given is upgrading from PS 7.2.0-preview.2 to PS 7.2.0-preview.3.

**Comment by rjmholt** [comment]
Here are logs from a different instance of this bug

[MSI crash.zip](https://github.com/PowerShell/PowerShell/files/5997922/MSI.crash.zip)

**Comment by andschwa** [comment]
Thanks for filing this Rob. (That MSI crash zip is from me 😅)
