### ISSUE TITLE
Test file in the wrong place

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#14832]
There's a test file at https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/ImportProvider.Tests.ps1.

It should be under the `tests/` directory.

**Comment by MarianoAlipi** [comment]
Hi! I'm having a bit of a hard time trying to identify the correct path for the test file.
I can create a pull request if you give me a little push in the right direction.
I think it should be under `test/` (in singular), and then under `test/powershell/` but then I'm not sure where it should be, as there is no matching directory for `System.Management.Automation`.
Thank you in advance for your time!

**Comment by iSazonov** [comment]
I think it should be in `test\powershell\Modules\Microsoft.PowerShell.Core\`.
