### ISSUE TITLE
Unexpected behavior: Installing pwsh is a lot easier than upgrading. This is a security issue!

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#14846]
## Steps to reproduce

1. Start pwsh
2. We get the note: `A new PowerShell stable release is available: v7.1.0 - Upgrade now, or check out the release page at: …`

## Expected behavior
3. Why does PowerShell nut just tell how the upgrade can be done?
4. I expect a Message like **Just call `pwsh install-upgrade`**

## Actual behavior
It's **very** annoying and therefore a really dangerous security issue: user's don't spend 15 minutes until they get the answer.
1. Users probably start reading the release note. There is no answer how the upgrade must be installed :-(
2. Users must start asking google :-(
3. We find the M$ Docs: **[Installing PowerShell on Windows](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1)** - **the proposal is a shame and a nightmare:** _"For best results when upgrading, you should use the same install method you used when you first installed PowerShell."_ Does anyone remember how he initially installed PowerShell?? I don't because it should _never_ be important.
4. Users are forced to spend additional time to ask google for a useful solution. Of course, it should be professional, e.g. state of the PowerShell scripting art.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
The message assumes the user knows how to upgrade to a new version of PowerShell depending on the channel you got it previously. There is also a discussion about a cross-platform self-contained installer CLI for powershell in #14217.
