### ISSUE TITLE
Import/Export-BinaryMiLog cmdlets

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1484]
In #1474 we removed 2 cmdlets:
- Import-BinaryMiLog
- Export-BinaryMiLog

We should revisit this after post-public release

**Comment by iSazonov** [comment]
For what they were created? If this is useful, then we should resume this project. RFC?

/cc @daxian-dbw @SteveL-MSFT

**Comment by RichardSiddaway** [comment]
The cmdlets are for exporting/importing CIM instances as binary encoded data. I've not seen them used much but would be nice to have for consistency.

**Comment by iSazonov** [comment]
As I understood from MSFT comments the project was stopped. But what was an idea? Perhaps it is actual and we could implement this in more generic way.

**Comment by RichardSiddaway** [comment]
They are currently available in Windows PowerShell 5.1

**Comment by SteveL-MSFT** [comment]
Those cmdlets are using undocumented APIs and those APIs are owned by a different team w/o plans to document them and there is no public equivalent.  As such, we cannot enable them in PSCore6.
