### ISSUE TITLE
Can't upgrage via homebrew on Mac OS

### ISSUE THREAD

**Issue by tiagoh** [PowerShell/PowerShell#14840]
I am trying to upgrade using homebrew the powershell tap, but it always requires a password.

![image](https://user-images.githubusercontent.com/162854/108347128-77b69700-71e0-11eb-853f-a9d7ecb05388.png)

Trying to uninstall presents the same behavior... 

![image](https://user-images.githubusercontent.com/162854/108347234-93ba3880-71e0-11eb-857e-33b09c05fe67.png)

**Comment by jborean93** [comment]
The password it is asking for is for the `sudo` call so it can remove and add some files your normal user cannot access. This is your password and not something specifically for PowerShell.
