### ISSUE TITLE
Consolidate Linux packages

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#14848]
## Summary of the new feature/enhancement

Have a script that creates the symlinks and have one package, which you would run as root.

* could be run manually (for tar packages)
* or as a post script on the package (in deb and RPM)

## Alternative proposal

Consolidate deb packages into 3 packages by the libSSL libmi expects in the package:

1. powershell_7.1.2-1.libssl.1.0.0_amd64.deb 
   * All others (link to libssl may be broken to prevent worse problems in libmi)
2. powershell_7.1.2-1.libssl.1.0.2_amd64.deb
   * Debian 9 
3. powershell_7.1.2-1.libssl.1.1.0_amd64.deb
   * Debian 10 and 11

**Comment by jborean93** [comment]
Curious what components are dynamically linked to libssl except for `libmi`. I assumed you still distributed the OpenSSL 1.0.0 version in all packages so if it was only `libmi` why differentiate between them?

**Comment by TravisEz13** [comment]
libmi requires a symlink, it doesn't dynamically load.

**Comment by jborean93** [comment]
It’s still dynamically linked at load time to a particular OpenSSL version the link is just the relative path. The question still remains, if it’s just libmi that needs the OpenSSL link then why do you have it for different versions. The last time I checked you still package the OpenSSL 1.0.x library linked version.

**Comment by TravisEz13** [comment]
I created a PR for this based on the alternative proposal.
https://github.com/PowerShell/PowerShell/pull/15109
