### ISSUE TITLE
Format-Hex does not properly filter non-printable characters

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#14868]
Format-Hex does not properly filtering non-printable characters:

````
Format-Hex $pshome\pwsh.exe -Count 120
````

![image](https://user-images.githubusercontent.com/11475352/108606800-2b4e9100-7371-11eb-9e63-4d68152eeaa7.png)

The industry standard is that dots represent everything that is non-printable, including null-bytes. The use of the Unicode non-printable character is a neat idea, but diverging from the industry standard just makes it look like a bug. Also, using spaces for null bytes (rather than a dot) makes it very difficult to visually match up which character corresponds to which hex offset, where in a traditional hex format you can count characters.

If the goal was to make it more clear which were the "real" character vs. artifacts we add because the character is non-printable, using a dark grey dot (w/ ANSI) might be cool:

![image](https://user-images.githubusercontent.com/11475352/108607227-fabc2680-7373-11eb-9092-220b4a0234d6.png)

**Comment by rkeithhill** [comment]
+100  Using dot for non-printable makes it so much easier to "scan" the right column for ASCII chars.
