### ISSUE TITLE
Tests on windows should not fail, when they run in non-elevated (non admin) env 

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1486]
There is a number of tests (mostly in PackageManager) that are failing, when they run without admin priviledges. Our CI doesn't catch it, because it's run elevated. But we should have a good experience for developers: they should be able to run it locally without elevation and see clean results on the build from master.

**Comment by vors** [comment]
My current proposition about it:

1. Introduce a new tag for Pester tests (i.e. "RequireAdmin").
  Mark tests that absolutely has to be admin with this label.
  Change the rest of the tests to avoid requiring admin privileges.

1. In the AppVeyor CI split CoreCLR test run into two parts:
   - `-ExcludeTag 'RequireAdmin'` (this should be executed with down-graded elevation, [for example](http://stackoverflow.com/questions/29569292/how-to-run-a-process-as-non-admin-from-an-elevated-powershell-console) )
   - `-Tag 'RequireAdmin'` with normal admin priviledges

Thoughts? cc @SteveL-MSFT @JamesWTruher @andschwa @lzybkr

**Comment by SteveL-MSFT** [comment]
Seems reasonable.  Generally speaking, we shouldn't require admin for anything that doesn't require admin including running tests.
