### ISSUE TITLE
PowerShell policies (UseWindowsPowerShellPolicySetting) should support a single root configuration entry

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#14863]
It took me forever to figure out how to get Powershell to obey the WindowsPowerShell Group Policy settings. It turns out you need to set ‘UseWindowsPowerShellPolicySetting’ on every key to be configured. This seems redundant - if somebody is going through that difficulty to edit every single Powershell Core group policy, they might as well set them to the values they want.

I think it would make sense to look at the WindowsPowerShell keys by default (especially the security ones), but in the worst case – just one root ‘UseWindowsPowerShellPolicySetting’ that PowerShell will look at to determine whether to adopt all settings.

**Comment by TravisEz13** [comment]
Adding the one root would not break any existing scenario, but during the RFC process there was a scenario where people did not want Windows PowerShell Policy to manage PowerShell Core.  This was the solution.

**Comment by TravisEz13** [comment]
Security working group: we could add a single GP that allows redirecting all group policies to use the windows PowerShell group policies without a breaking change.
