### ISSUE TITLE
Engine Logging is not enabled

### ISSUE THREAD

**Issue by LeeHolmes** [PowerShell/PowerShell#14864]
Engine logging is not enabled – this is a security issue for some (detecting PowerShell being hosted in other processes), although the primary industry use is detecting somebody loading Powershell v2 (which isn't really pertinent in PowerShell).

Here is where it's disabled: https://github.com/PowerShell/PowerShell/blob/0d1ea73e599021c9ead87542646f7975bc04e5b9/src/System.Management.Automation/logging/MshLog.cs#L137

This isn’t a critical security issue, but a loss of visibility for some.

**Comment by daxian-dbw** [comment]
The ETW engine logging has been enabled for quite some time. It's the Event Log provider that is not enabled yet, but I wonder if the event log provider is still needed.

PowerShell Core registers the event provider manifest for its ETW logging, which is available in Event Viewer. Also, according to the comments in `EventLogLogProvider.cs`, it's only for the scenarios where PowerShell is running in early windows releases from 2000 to 2003.

https://github.com/PowerShell/PowerShell/blob/4711eb570e45ffd161ff50fc7d474816875abc99/src/System.Management.Automation/logging/eventlog/EventLogLogProvider.cs#L16-L19

Mark this issue to be reviewed by committee, to see if the event log provider should just be deleted.

**Comment by daxian-dbw** [comment]
In case someone wonder what this event log provider is, here is some information about it in Windows PowerShell:

It's the "Windows PowerShell" channel that can be found right under _"Applications and Services Logs"_ in Event Viewer

![image](https://user-images.githubusercontent.com/127450/156853261-28accf10-7cb9-4ead-bc04-e9bd0bf6cfcd.png)


As a comparison, the Windows PowerShell ETW logging provider can be found at _"Applications and Services Logs/Microsoft/Windows/PowerShell"_, and the PowerShell Core ETW logging provider can be found at _"Applications and Services Logs/PowerShellCore"_

**Comment by SteveL-MSFT** [comment]
Let's have WG-Security review this first to see if there's any security implication.  If this is just legacy logging particularly on legacy Windows, the Committee would rely on WG-Engine's evaluation if this code should just be removed as Windows Server 2003 is out of support.

**Comment by LeeHolmes** [comment]
This is the security context: https://www.leeholmes.com/detecting-and-preventing-powershell-downgrade-attacks as well as folks trying to detect WinWord / Excel spawning PowerShell.

This log channel itself doesn't matter, but today those engine events only get generated when this code is not commented out. We could move these events to the ETW log if we wanted.

**Comment by daxian-dbw** [comment]
@LeeHolmes Thanks for sharing the context!
`pwsh` cannot start a downgrade version of PowerShell, so I guess the "downgrade attacks" is no longer a concern to `pwsh`.
Can you share more details about the "detecting WinWord / Excel spawning PowerShell" scenario?

**Comment by PaulHigin** [comment]
@WG-Security  We agree that PowerShell Core no longer supports running down level PowerShell (v2.0) directly or via remoting, and so this is not a security issue.

**Comment by daxian-dbw** [comment]
Thanks for the review @PaulHigin.
Mark for committee to review again, to see if the event log provider should just be deleted.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this, we agree this is legacy and should be removed and should not create any compat issue.
