### ISSUE TITLE
Feature Request - LTS version update notifications

### ISSUE THREAD

**Issue by sassdawe** [PowerShell/PowerShell#14872]
## Summary of the new feature/enhancement

As a user of the LTS version, I'd like to see the version update notifications for the LTS version only.
When I'm using the latest LTS version, I don't want to be reminded about the latest non-LTS version.
But if there is a newer LTS version, I do want to be reminded.

```
PowerShell 7.0.5
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.1.2
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.1.2
```

## Proposed technical implementation details (optional)

The LTS version should check if it is running the latest LTS version or not, and ignore the non-LTS versions.

**Comment by daxian-dbw** [comment]
You can achieve that by setting the environment variable `POWERSHELL_UPDATECHECK`. See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.1#long-description for details.

**Comment by sassdawe** [comment]
Hi @daxian-dbw, I don't want to say that the link you provided doesn't work, because it does. However, having a single - shared - environment variable is a limitation when people are using multiple PowerShell releases at the same time.

Should I update the original issue and say the different releases should check for updates to their release? 
I didn't consider preview releases before, but now I realize that those who are using three different releases, might want to get notified about the matching release.

**Comment by mklement0** [comment]
This just came up again:

* #20210
