### ISSUE TITLE
Add support for specifying external tools in #requires statements (-Executable "external_tool" )

### ISSUE THREAD

**Issue by pakrym** [PowerShell/PowerShell#14879]
Often PowerShell scripts use external executables to accomplish their tasks.

Even more often authors of these scripts do not check or log a readable message when the executable is not available. 

Being able to declare which external tool the script expects on the PATH and have good error messages provided when the script starts would improve customer experience in these cases.

Example:

```powershell
#requires -Executable "npx" -Description "npx is required to do something, please install nodejs"
```

Would replace:

![image](https://user-images.githubusercontent.com/1697911/108751447-13a11500-74f7-11eb-8d1e-2e698281704b.png)

and similar variations

**Comment by jborean93** [comment]
Just an FYI you can "simplify" you check with

```powershell
if (-not (Get-Command -Name npx -ErrorAction SilentlyContinue)) {
    Write-Error -Message "blah"
    exit 1
}
```

**Comment by p0W3RH311** [comment]
@jborean93 

for checking more faster
```

if (-not (Get-Command -Name npx -CommandType Application -ErrorAction SilentlyContinue)) {
    Write-Error -Message "blah"
    exit 1
}
```

**Comment by daxian-dbw** [comment]
Language working group:
The existing solution (@p0W3RH311's answer above) looks sufficient and simple enough for checking whether an executable is available at run time. It seems what you really need is a command `Test-Command -Name <string> [-Type <CommandTypes>] [-Message <string>]`. You can easily wrap the solution code above into such a command.
