### ISSUE TITLE
named parameter in classes

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14878]
hi guys !!

its possible to add named parameter in classes...example:
```

class foo {
   # code
} 
```

instead of positional parameter
`[foo]::new($a,$b)`

_named parameter_

`[foo]::new(a=$a,b=$b)`

with this behaviour we can change the position of parameters
`[foo]::new(b=$b,a=$a)`

and its more ligible

**Comment by daxian-dbw** [comment]
Close as a duplicate of https://github.com/PowerShell/PowerShell/issues/13307
