### ISSUE TITLE
Class broken when containing file is updated (Cannot convert the "ReproType" value of type "ReproType" to type "ReproType")

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#14884]
Just like re-executing `Add-Type` for a snippet of C# code that has not changed, reloading a module that uses classes should also continue to work--even if a script file that contains the [unmodified] class has changed.

(I felt this problem was covered by #14250, but the owner closed it, and this problem is still irritating us, to the point we might just rip out all usage of PowerShell classes.)

This does not only come up during development scenarios. For example, I have a module that auto-updates itself, and then instructs the end user to run "`Import-Module [...] -Force`" to pick up the changes. (And then I get complaints from users when the module breaks in a really nonsensical-looking way.)

The key to the repro below is touching the file where the class is defined (before re-importing the module). You don't have to change the class definition; just add some whitespace somewhere else in the file. Which makes me think that the logic out there for deciding whether to generate a new runtime type for the class is making its decision based on whether the containing file has changed or not, but could do better by looking at just the extent where the class is defined.

## Steps to reproduce

```powershell
mkdir Repro_gh_14250 | Out-Null
pushd Repro_gh_14250
New-ModuleManifest -Path .\Repro.psd1 -RootModule Repro.psm1

@'
$script:data = [ordered] @{
    First = @("Primo", 123)
    Second = @("Secundo", 456)
}

class ReproType
{
    [string] $Name
    [int] $Number
}

$TheList = @()
foreach( $key in $script:data.Keys )
{
    $newThing = [ReproType]::new()
    $newThing.Name = $script:data[ $key ][ 0 ]
    $newThing.Number = $script:data[ $key ][ 1 ]

    $TheList += $newThing
}

function Get-TheList
{
    [CmdletBinding()]
    param()

    process { return $TheList }
}
'@ > Stuff1.ps1

@'
function Show-TheList
{
    [CmdletBinding()]
    param( [ReproType[]] $TheItems )

    process
    {
        foreach( $item in $TheItems )
        {
            Write-Host $item.Name -Fore Cyan -NoNewline
            Write-Host ": " -NoNewline
            Write-Host $item.Number -Fore Yellow
        }
    }
}

function Repro
{
    [CmdletBinding()]
    param()

    $stuff = @( Get-TheList )
    Show-TheList $stuff
}
'@ > Stuff2.ps1

@'

. "$PSScriptRoot\Stuff1.ps1"
. "$PSScriptRoot\Stuff2.ps1"

'@ > Repro.psm1

ipmo .\Repro.psd1 -Force
Repro
'# nothing' >> .\Stuff1.ps1
ipmo .\Repro.psd1 -Force
Repro    # EXPECTED: it works. ACTUAL: Cannot process argument transformation on parameter 'TheItems'. Cannot convert the "ReproType" value of type "ReproType" to type "ReproType".

```

## Expected behavior

No problems after reloading the module.

## Actual behavior

After reloading the module, I get errors when using the [unmodified] class:

```none
Cannot process argument transformation on parameter 'TheItems'. Cannot convert the "ReproType" value of type "ReproType" to type "ReproType"
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.3
PSEdition                      Core
GitCommitId                    7.2.0-preview.3
OS                             Microsoft Windows 10.0.20293
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
> Just like re-executing `Add-Type` for a snippet of C# code that has not changed reloading a module that uses classes should also continue to work--even if a script file that contains the [unmodified] class has changed.

A couple of questions on the expectations of the change:

- Which `SessionState` (module) would you expect it to be bound to?
- Would you expect all static properties to remain unchanged or would you expect them reinitialized to default and for static constructors to be reinvoked?
- If you have a static constructor that changes module state, would you expect the new module instance to reflect those changes?

**Comment by jazzdelightsme** [comment]
> Which SessionState (module) would you expect it to be bound to?

The new one. (The old version of the module is effectively gone, replaced by force-importing the updated version.)

> Would you expect all static properties to remain unchanged or would you expect them reinitialized to default and for static constructors to be reinvoked?

Reinitialized to default; static constructors re-invoked.

> If you have a static constructor that changes module state, would you expect the new module instance to reflect those changes?

Yes.

In other words, I expect force-importing the module to be [nearly*] equivalent to just importing that version of the module in a session where no previous version had been loaded. (*of course that does not apply to global session state)

**Comment by jazzdelightsme** [comment]
> > Just like re-executing Add-Type for a snippet of C# code

I should add that yes, I understand my expectations for C# code are not quite the same as for PowerShell classes. I think this is simply fallout from the fact that C# classes added via `Add-Type` are not tied to session state, but are necessarily global. This is due to limitations of .NET (can't unload the type when a module is unloaded, for example).

Because C# classes are effectively global state, that means they continue to work just fine when the module is reloaded. It is true that static constructors are not re-run when the module is re-imported, so if I were storing state in C# static members, I would have to understand that these would be tied to global session state, not module (and therefore state from before the reload could be around afterward). But for PowerShell classes (a first-class, built-in thing), if they are going to be tied to the module, then they should be tied to the module, and continue to work, even when the module is reloaded.

**Comment by SeeminglyScience** [comment]
> But for PowerShell classes (a first-class, built-in thing), if they are going to be tied to the module, then they should be tied to the module, and continue to work, even when the module is reloaded.

I should clarify that they *do* work when reloaded, the difference is largely in design.  `using module` is a parse time concept where `Import-Module` is a runtime concept.  It's possible that this could be made to work in *very* specific situations by reusing the type definition and manually reinitializing everything *only* when `Import-Module -Force` is used.

That's a pretty big work item with a lot of risk but I can't quickly see why it'd be impossible.  Though the situations where that is feasible would be pretty limited, so for a user outside of this thread it would be challenging to figure out why it's working sometimes and failing others.

**Comment by jazzdelightsme** [comment]
> I should clarify that they do work when reloaded

Sorry, I don't mean to be obtuse, but: the point of this Issue is that they demonstrably do NOT work when reloaded (see the repro steps). I am not sure where our miscommunication is... can you please clarify?

**Comment by SeeminglyScience** [comment]
> Sorry, I don't mean to be obtuse, but: the point of this Issue is that they demonstrably do NOT work when reloaded (see the repro steps). I am not sure where our miscommunication is... can you please clarify?

Ahh I see, this is different form the issue you linked as none of it is exposed outside the module.  Type is probably cached on the `CommandInfo` and isn't correctly invalidated. Outside of function signatures (parameter types, attributes, etc) it'll work with forced reloads though.

I went ahead and hid my other comments as outdated, thanks for the correction.
