### ISSUE TITLE
#requires -ExecutionPolicy ....

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14880]
Hi Guys !!

add new _pragma Executionpolicy_ to enable control execution of script  
```

#requires -Executionpolicy bypass 
echo hello
```

this pragma support enum `[Microsoft.PowerShell.ExecutionPolicy]`

**Comment by SeeminglyScience** [comment]
More details are needed, please specify what you expect this would do.

**Comment by p0W3RH311** [comment]
@SeeminglyScience 

thanks,

this feature make coder to control the script execution policy in this script file for exemple instead of execute her script


`PS> powershell -file ./script.ps1 -executionpolicy bypass `

it can use simply
` PS> ./script.ps1 `

and include in her script pragma` #requires -Executionpolicy bypass `

the values of -Executionpolicy is [Microsoft.PowerShell.ExecutionPolicy]

**Comment by SeeminglyScience** [comment]
But if the file controls the execution policy, what's the point of execution policy? Granted I often ask the latter half of that question anyway, but that's a separate issue.

**Comment by p0W3RH311** [comment]
@SeeminglyScience  but this _is the same_ of:

`PS> powershell -file ./script.ps1 -executionpolicy bypass `

with this we can be bypass the execution policy and put the script in schedule task for example

**Comment by jborean93** [comment]
It's still up to the caller to specify `-ExecutionPolicy Bypass` and not the script. Granted this could be made as a lower priority than the process level so that it doesn't override any other defined policies but I just don't see why.

**Comment by SeeminglyScience** [comment]
Yeah if this were added every script would just add that. After all, why would a script want to disable it's own execution? It would be almost the same as just removing the concept of execution policy entirely.

> with this we can be bypass the execution policy and put the script in schedule task for example

FYI you can add use a PowerShell script as a scheduled task just fine, you just need to define it like this:

|Field|Value|
|---|---|
|Target|`powershell.exe`|
|Arguments|`-ExecutionPolicy Bypass -NoProfile -NonInteractive -File path`|

**Comment by Maamue** [comment]
I also fail to see the improvements this should bring. ExecutionPolicy is defined by the caller, not the script author. It defeats the entire reason ExecutionPolicy exists in the first place. If you need to circumvent it, let the caller circumvent it, not the script author.

**Comment by daxian-dbw** [comment]
I agree that the execution policy should be defined by the caller, not the script. Thanks all for the discussion!
