### ISSUE TITLE
Maintain user-level experimental-feature configuration separately for preview and stable versions

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14891]
Related: #14862

## Summary of the new feature/enhancement

Currently, selective enabling or disabling experimental features at the user level (`-Scope CurrentUser`, which is the default) takes effect for _all_ side-by-side PowerShell (Core) installations, irrespective of whether they're stable versions or preview versions.

This can unwittingly result in the following scenario:

* **By selectively disabling an experimental _feature_ in a _preview_ version, you're implicitly _enabling_ experimental features for side-by-side _stable_ versions**, because the same `powershell.config.json` file is used by all side-by-side version, and because disabling is based on _excluding_ the disabled feature from the list of explicitly enumerated _enabled_ features in that file (based on the all-enabled starting point in preview versions).

The state of experimental features for preview versions should be managed separately from stable versions.

---

An **additional question** is how to handle **_cross-preview-version_ configuration**:

* Say you disable an experimental feature in a preview version (where all features are _enabled_ by default).

* You later install a new preview version that comes with _new_ experimental features.

* With a version-agnostic configuration, **it isn't just the previously explicitly disabled feature that ends up disabled, but _all newly added ones_ as well.**

## Proposed implementation:

Introduce a new property in the user-level `powershell.config.json` file:

* named something like `DisabledPreviewExperimentalFeatures`, which is only read by _preview_ versions, _instead_ of the `ExperimentalFeatures` property.

* whose logic is the _inverse_ of  `ExperimentalFeatures`: all features _except_ the ones listed should then be enabled.

Written as of `PowerShell Core 7.2.0-preview.3`

**Comment by rkeithhill** [comment]
The Engine WG discussed this yesterday and agree that it's a reasonable ask. There needs to be discussion on a better implementation. We cc'd Jason for his input on this.

**Comment by theJasonHelmick** [comment]
I would agree that this seems like a responsible request. I'm not convinced that this problem needs to be addressed, although cumbersome. I do think it's certainly worth discussing and investigating further - along with other customization options that have been discussed and how to handle `powershell.config.json`.  

So, help me clarify the suggestion. The suggestion is to add `DisabledPreviewExperimentalFeatures` that requires a user to individually list the features that are to be disabled.  If they don't list them, then all experimental features are enabled for this and all previews. Is that correct?

**Comment by doctordns** [comment]
i would have expected the JSON to list ALL the experimental features and whether enabled or disabled.

**Comment by daxian-dbw** [comment]
@theJasonHelmick I would like you to also consider having preview versions use a different path for the current-user scope `powershell.config.json` file.

Take windows as an example. Today, the current-user scope file is always located in `C:\Users\<user-name>\Documents\PowerShell\powershell.config.json`. So, maybe for preview versions, the current-user scope file path should be `C:\Users\<user-name>\Documents\PowerShell\preview\powershell.config.json`.

**Comment by daxian-dbw** [comment]
@doctordns Consider there may be non-PowerShell-built-in modules in the module path that define experimental features, it's not possible to list all experimental features until at PowerShell run time.

**Comment by theJasonHelmick** [comment]
@daxian-dbw Certainly makes sense to separate the previews from stable with different paths to the json.  I'm wondering if this impacts MU @TravisEz13?

**Comment by daxian-dbw** [comment]
@theJasonHelmick Do we support MU for preview releases?

**Comment by theJasonHelmick** [comment]
@daxian-dbw @TravisEz13 - Yes, we have been.

**Comment by daxian-dbw** [comment]
The current-user scope configuration file doesn't come with PowerShell package. It's created by user (explicitly, or via `Enable-ExperimentalFeature` command), so I don't think this will affect MU.
