### ISSUE TITLE
error NETSDK1005: Assets file 'project.assets.json' doesn't have a target for 'netcoreapp3.1'.

### ISSUE THREAD

**Issue by shreyasbe** [PowerShell/PowerShell#14890]
Hi MS Team,
We are building PowerShell RPMs from https://github.com/PowerShell/PowerShell/releases/ for Linux distro(i.e. Photon from VMWare). Recently we are trying to upgrade PowerShell to the latest release v7.1.2, but its got failed with the following errors

============Logs(S)============
/usr/lib/dotnet/sdk/5.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1005: Assets file '/usr/src/photon/BUILD/PowerShell-7.1.2/src/powershell-unix/obj/project.assets.json' doesn't have a target for 'netcoreapp3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project. [/usr/src/photon/BUILD/PowerShell-7.1.2/src/powershell-unix/powershell-unix.csproj]
error: Bad exit status from /var/tmp/rpm-tmp.xvxSuE (%build)
============Logs(E)============

Prior to the upgrade of PowerShell to v7.1.2, I have upgraded dotnet-sdk to v5.0.103 as per global.json and upgraded dotnet-runtime to v5.0.3, which are working fine & added as dependencies to build PowerShell v7.1.2.

Is there any way to resolve the above issue?

**Comment by daxian-dbw** [comment]
Was the `build.psm1` file updated to use the `net5.0` as the runtime? Did you try checking out the `v7.1.2` tag and build from that branch?

**Comment by shreyasbe** [comment]
> Was the `build.psm1` file updated to use the `net5.0` as the runtime? Did you try checking out the `v7.1.2` tag and build from that branch?

As I checked the file "powershell-7.1.2/usr/src/photon/BUILD/PowerShell-7.1.2/build.psm1" got updated to the following to use the `net5.0`:
-------------------------------------------------------------------------------------------------------------
 745 function New-PSOptions {                                                        
 746     [CmdletBinding()]                                                           
 747     param(                                                                      
 748         [ValidateSet("Debug", "Release", "CodeCoverage", '')]                   
 749         [string]$Configuration,                                                 
 750                                                                                 
 751         [ValidateSet("net5.0")]                                                 
 752         [string]$Framework = "net5.0",                                          
 753                                                                                 
 754         # These are duplicated from Start-PSBuild                               
 755         # We do not use ValidateScript since we want tab completion 
-------------------------------------------------------------------------------------------------------------

I pulled the code from "https://github.com/PowerShell/PowerShell.git", using tag v7.1.2, building the same.

**Comment by shreyasbe** [comment]
I observe the following difference on the latest(v7.1.2) against v7.0.3:

https://github.com/PowerShell/PowerShell/blob/v7.1.2/build.psm1#L751
```
function New-PSOptions {
    [CmdletBinding()]
    param(
        [ValidateSet("Debug", "Release", "CodeCoverage", '')]
        [string]$Configuration,

        [ValidateSet("net5.0")]
        [string]$Framework = "net5.0",

        # These are duplicated from Start-PSBuild
        # We do not use ValidateScript since we want tab completion
```

https://github.com/PowerShell/PowerShell/blob/v7.0.3/build.psm1#L711

```
function New-PSOptions {
    [CmdletBinding()]
    param(
        [ValidateSet("Debug", "Release", "CodeCoverage", '')]
        [string]$Configuration,

        [ValidateSet("netcoreapp3.1")]
        [string]$Framework = "netcoreapp3.1",

        # These are duplicated from Start-PSBuild
        # We do not use ValidateScript since we want tab completion
```

**Comment by iSazonov** [comment]
I'd suggest to clean up local nuget cache.

**Comment by shreyasbe** [comment]
> I'd suggest to clean up local nuget cache.

I am doing the clean build. Even after that, is it require to cleanup cache?

**Comment by iSazonov** [comment]
If you have already built on this machine, then I would advise you to clear this cache (remove the cache folder) and try a clean the build again.

**Comment by shreyasbe** [comment]
> If you have already built on this machine, then I would advise you to clear this cache (remove the cache folder) and try a clean the build again.

As per recommendation, I did a clean build, but the observing same issue. Please suggest if I need to do anything else?

**Comment by iSazonov** [comment]
Maybe this helps https://developercommunity.visualstudio.com/t/error-netsdk1005-assets-file-projectassetsjson-doe/1248649

**Comment by shreyasbe** [comment]
> Maybe this helps https://developercommunity.visualstudio.com/t/error-netsdk1005-assets-file-projectassetsjson-doe/1248649
> 
> > **[Devcom2](https://developercommunity.visualstudio.com/t/error-netsdk1005-assets-file-projectassetsjson-doe/1248649)**Developer community 2

Thanks for sharing the link. I went through the same, which is for the Windows platform. Whereas we are building Powershell on a Linux platform, where we neither use MSBuild nor NuGet. 

Such an issue we have never encounter with powershell v7.0.3 but in the latest v7.1.1 & v7.1.2 release.

**Comment by shreyasbe** [comment]
Closing this. As I figured out the issue.
