### ISSUE TITLE
Multiple Output types do not work for tab expansion as the help suggests

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#14909]
## Steps to reproduce

The help [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_outputtypeattribute?view=powershell-7.1) has an example which I have modified for clarity below
```powershell
function Get-User {
  [CmdletBinding()]
  [OutputType([System.Collections.Hashtable], ParameterSetName="Name")]
  [OutputType("System.io.file", ParameterSetName="ID")]
  Param (
    [parameter(Mandatory=$true, ParameterSetName="ID")]
    [Int[]] $UserID,

    [parameter(Mandatory=$true, ParameterSetName="Name")]
    [String[]]    $UserName
  )
}
```
if `-userid `is specified it returns a file , if `-username` is specified it returns a hash table, So one would expect       
`get-user  -id 1234 | select <tab>`    
to cycle through the properties of file objects, but in fact it cycles through hash table properties. This happens in 7.1.2 and in the Windows PowerShell 5 ISE so I think it is a longstanding thing - and not a psreadline issue. 

I can't speak for other people's use but my main reason for setting output is for tab completion, but it appears that if multiple output types are given one is always selected  whatever parameter sets  say - changing the order they are declared, setting a default parameter set , putting all parameters in the ID set did not change the selection from hash table (nor does it appear to be alphabetical from the place where I first hit it) .  

## Expected behavior
Tab expansion evaluates the parameter set and selects the correct object. If this isn't practical the help should spell out that multiple output types have limited use. 

## Actual behavior
See above

## Environment data
```none

Name                           Value
----                           -----
PSVersion                      7.1.2                       
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
That would make for a nice enhancement.

Note that the current behavior isn't to pick _one_ type, but to use them _all_ and show the _union_ of their properties.
You didn't see that, because [`System.IO.File`](https://docs.microsoft.com/en-US/dotnet/api/System.IO.File) is a static class _without properties_ (also, just to avoid confusion: the parameter name in your example should be `-UserId`, not `-Id`).

To demonstrate:

```powershell
PS> & {
    function foo { 
      [OutputType([regex], ParameterSetName='A')]
      [OutputType([hashtable], ParameterSetName='B')]
      [CmdletBinding(DefaultParameterSetName='A')] 
      param(
       [Parameter(ParameterSetName='A')] $A, 
       [Parameter(ParameterSetName='B')] $B
      )
      "..." 
    } 
    $cmd = 'foo -A a | Select-Object '; (TabExpansion2 $cmd -cursorColumn $cmd.Length).CompletionMatches.CompletionText
}
# Sorted list of the *union* of [regex] and [hashtable] properties.
Count
IsFixedSize
IsReadOnly
IsSynchronized
Keys
MatchTimeout
Options
RightToLeft
SyncRoot
Values
```

**Comment by jhoneill** [comment]
> That would make for a nice enhancement.
> 
> Note that the current behavior isn't to pick _one_ type, but to use them _all_ and show the _union_ of their properties.
> You didn't see that, because [`System.IO.File`](https://docs.microsoft.com/en-US/dotnet/api/System.IO.File) is a static class _without properties_ 

The example on docs used a string and an Int and I thought "That's no good, no properties on an int" so I went for two random types and picked file instead of file info.  And  just a moment ago I was talking about the phrase "hoist by his own petard" :-)  

My real world example is a function which might return something with a ton of properties or something with 3 and 3 will get lost in the others.  So the substantive "Return [only] the right properties" stands, but  thanks for fixing my confusion  - I had a dim memory of it being the union but I couldn't get that, Doh!

> (also, just to avoid confusion: the parameter name in your example should be `-UserId`, not `-Id`).
I've fixed that :-)

**Comment by SeeminglyScience** [comment]
This was a big disappointment for me when I found out it just always assumed all output types.  It'd be nice if type inference used the pseudo parameter binder to narrow down the results, though it's probably not a small work item.
