### ISSUE TITLE
connect-microsoftteams from powershell with secret. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [PowerShell/PowerShell#14900]
with below script I can authenticate on AzureAd with a secret but not on teams. 
Can you please point me in the right direction how to do this for MicrosoftTeams ? 

import-module Az 
Import-Module MicrosoftTeams 
$azureAplicationId ="xxxx"
$azureTenantId= "yyyyy"
$azurePassword = ConvertTo-SecureString "secret" -AsPlainText -Force
$psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
Connect-AzAccount -Credential $psCred -TenantId $azureTenantId -ServicePrincipal
$context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
$aadToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.windows.net").AccessToken

Connect-AzureAD -AadAccessToken $aadToken -AccountId $context.Account.Id -TenantId $context.tenant.id

Connect-MicrosoftTeams -Credential $psCred

output: 

WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user profile ( C:\Users\jdeclerc\.Azure ). Please ensure th
at this directory has appropriate protections.

Account                              SubscriptionName TenantId                             Environment
-------                              ---------------- --------                             -----------
xxxxx                                yyyyyy                               AzureCloud 

Account      : xxxxx
Environment  : AzureCloud
Tenant       : yyyyy
TenantId     : yyyyy
TenantDomain : yyyyy

Connect-MicrosoftTeams : One or more errors occurred.: unknown_user_type: Unknown User Type
At line:13 char:1
+ Connect-MicrosoftTeams -Credential $psCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : One or more errors occurred.
At line:13 char:1
+ Connect-MicrosoftTeams -Credential $psCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AggregateException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : unknown_user_type: Unknown User Type
At line:13 char:1
+ Connect-MicrosoftTeams -Credential $psCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-MicrosoftTeams], AdalException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams
 
Connect-MicrosoftTeams : One or more errors occurred.: unknown_user_type: Unknown User Type
At line:13 char:1
+ Connect-MicrosoftTeams -Credential $psCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams

**Comment by daxian-dbw** [comment]
@johandeclercqdemocon Please post your question to StackOverflow or the [discussion](https://github.com/PowerShell/PowerShell/discussions) forum. You may be able to get an answer there.
