### ISSUE TITLE
Sum expression in array element becomes array concatenation

### ISSUE THREAD

**Issue by ironyman** [PowerShell/PowerShell#14907]
## Steps to reproduce

```powershell
PS C:\windows\system32> @(1,2+3).length
3
```

## Expected behavior

```none
PS C:\windows\system32> @(1,2+3).length
2
```

## Actual behavior

```none
PS C:\windows\system32> @(1,2+3).length
3
```

## Environment data

```none

```

**Comment by 237dmitry** [comment]
This is because of concatenation of arrays
```
@(1,2+3,4,5).length
@(1,(2+3)).length
```

**Comment by jhoneill** [comment]
For clarity: the + operator is lower precedence than the , operator   
so `1 , 2 + 3 , 4 , 5`   reads as `(1 , 2) + (3 , 4 , 5)`  not  as `1 , (2 + 3) , 4 , 5`

**Comment by mklement0** [comment]
@ironyman, see also: [`about_Operator_Precedence`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operator_Precedence)

**Comment by ironyman** [comment]
Is this not an issue in function calls?

f(1,2+3,4) 

would that be 3 arguments or a single argument?

**Comment by mklement0** [comment]
It's a _single_ argument that happens to be an _array_:

```powershell
PS> & { "args count: $($args.Count)"; "1st arg element count: $($args[0].Count)"; "1st arg stringified value: [$($args[0])]" } (1,2+3,4)

args count: 1
1st arg element count: 4
1st arg stringified value: [1 2 3 4]
```

**Comment by ironyman** [comment]
Oh I suppose that makes sense. Thank you.
