### ISSUE TITLE
We shouldn't add explicit newlines when writing errors

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#1491]
## Steps to reproduce

On Windows

```
PS> throw ("1234567890"*([Console]::BufferWidth/10 + 10))
```

then with the mouse, select the text of the error message, paste on something like notepad
## Expected behavior

no unnecessary line breaks
## Actual behavior

line breaks at the buffer width
## Environment data

Win10 any version

**Comment by iSazonov** [comment]
If I insert clipboard in Notepad after `$error[0].Exception.Message | clip` I don't see any extra newlines.
@lzybkr Please clarify that we should fix.

**Comment by lzybkr** [comment]
You're trying something other than what the repro steps say - and in this case, you will see different behavior.

Do follow my repro steps exactly (including running on Win10).

**Comment by SteveL-MSFT** [comment]
Dupe of https://github.com/PowerShell/PowerShell/issues/3813

I know this is older, but that one has more info.
