### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by yuusakuri** [PowerShell/PowerShell#14916]
## Summary of the new feature/enhancement
I want non-double quoted symbols not to behave like double quotes.

If that's difficult, consider adding it to your pwsh.exe startup options.

#### Command
```powershell
Test-Path "“OK!“"
```
#### Result
```
Test-Path: A positional parameter cannot be found that accepts argument 'OK!'.
```
![pwsh_eJiKoeyoZc](https://user-images.githubusercontent.com/58417213/109396029-ef1fbf80-7972-11eb-93ac-1ca306f3b3b7.png)

**Comment by mklement0** [comment]
https://stackoverflow.com/a/55053609/45375 details what Unicode characters PowerShell considers _equivalent_ in terms of double quotes, single quotes, dashes (hyphens) and whitespace.

To work around the `“` (LEFT DOUBLE QUOTATION MARK, [`U+201C`](http://www.fileformat.info/info/unicode/char/201c)) characters in your example getting interpreted as double quotation marks (which in effect makes your command equal to `Test-Path OK!`), use _escape sequences_:

```powershell
PS> Write-Output "`u{201c}OK!`u{201c}"
“OK!“
```

**Comment by mklement0** [comment]
I forgot the more obvious solutions:

Single-quoting:

```powershell
PS> '“OK!“'
“OK!“
```

`` ` ``-escaping:

```powershell
PS> "`“OK!`“"
“OK!“
```

**Comment by yuusakuri** [comment]
The method of manually escaping those characters doesn't make sense to me.
I have a sophisticated filer called Directory Opus that tries to pass the path of the selected item to the script, but it doesn't work if the script contains `'` and these characters.
I contacted the developers of Directory Opus and he said it was a Powershell issue and he doesn't seem to take any action.
I agree with him in that there is a problem with PowerShell.
So I would like to change this strange implementation of PowerShell.

**Comment by mklement0** [comment]
I understand that PowerShell's permissiveness with respect to quoting/whitespace equivalence can be surprising.

I can't speak to the original design intent, but I assume it was to accommodate text created with or copied and pasted from editors that use non-ASCII-range quotation marks and whitespace.

If you have _verbatim_ file names that are passed _via macro expansion_, _before_ PowerShell sees the resulting source code, use a verbatim here-string:

```powershell
# Assume the content of the here-string is provided via up-front macro expansion, use a verbatim here-string:
Write-Output @'
“OK!“
'@
```

Note that if your file name is stored _in a PowerShell variable_, no extra effort is needed:

```powershell
$fname = '“OK!“'
Write-Output $fname
```

**Comment by yuusakuri** [comment]
Single quotes can be used in filenames. That method does not work if the file name contains single quotes.
