### ISSUE TITLE
Pipeline stops enumerating on encountering a second AutomationNull value in the input

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#14920]
## Steps to reproduce

Note: `(& {})` is used to produce AutomationNull, i.e. the `[System.Management.Automation.Internal.AutomationNull]::Value` singleton representing "no output" in PowerShell.

```powershell
$automationNull = & {}
1, $automationNull, 2, $automationNull, 3, 4, 5 | ForEach-Object { $_ }  | Should -Be (1..5)
```

## Expected behavior

The test should pass: all non-AutomationNull values should be passed through (while the AutomationNull values in the input are apparently themselves _not_ sent through the pipeline).

## Actual behavior

The test fails, because enumeration unexpectedly _stops_ on encountering the _second_  non-AutomationNull value.

```none
Expected @(1, 2, 3, 4, 5), but got @(1, 2).
```

Note that using true `$null` values does _not_ exhibit the problem: the following test succeeds:

```powershell
1, $null, 2, $null, 3, 4, 5 | ForEach-Object { $_ }  | Should -Be 1, $null, 2, $null, 3, 4, 5 # OK
```

## Environment data

```none
PowerShell Core 7.2.0-preview.3
```

**Comment by JamesWTruher** [comment]
it seems to be an artifact of the pipeline:
```powershell
PS> $automationNull = &{}
PS> $c=1, $automationNull, 2, $automationNull, 3, 4, 5                              
PS> $c.length
7
PS> foreach($v in $c) { ":: $v ::" }
:: 1 ::
::  ::
:: 2 ::
::  ::
:: 3 ::
:: 4 ::
:: 5 ::
```

**Comment by rkeithhill** [comment]
The Engine WG reviewed this today. We agree this is a bug that needs investigation. There is some concern that fixing this bug may introduce a breaking change.
