### ISSUE TITLE
New-FileCatalog is improperly parsing/sanitizing filenames of files to be cataloged

### ISSUE THREAD

**Issue by TheManii** [PowerShell/PowerShell#14929]
## Steps to reproduce

When using New-FileCatalog, powershell fails on specific file name combinations and returns an error.

Reproduction steps:
1. Create file: `--a=b.ext`
2. Run `New-FileCatalog -File "--a=b.ext" -CatalogFilePath "test.cat" -CatalogVersion 2.0`
3. Optionally: put text/content into `--a=b.ext`

## Expected behavior

```none
Catalog entry is created for file
```

## Actual behavior

```none
'New-FileCatalog: Unable to find file b.ext=C:\<path>\--a=b.ext to hash.'
```

The cmdlet seems to be attempting to parse the '--<a>=<b>' part as if it was part of the command and not the filename.
The <a> and <b> parts are optional, it can be boiled down to "C:\<path>\--=" and still fail.

If <b> has contents, that will be what is shown in 'Unable to find file <b>`

If you put something/text into the '--a=b.ext' file and run 'Get-Content --a=b.ext' the command returns to contents of the file, so it is specific to New-FileCatalog and not to the underlying powershell engine

Affects both 7.1 and 5.1

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0



Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rbalaz** [comment]
I have also experienced issue with this when using PackageInspector to scan a self-extracting .NET single file executable, which extracted itself to a folder containing `=` symbol at the end of it's name (atPZmeTTBhU8NkmdVdC3cD3GzHDhoSM=). It seems that having `=` is enough to reproduce this.
