### ISSUE TITLE
[FR] Disable telemetry in custom builds (VScode approach)

### ISSUE THREAD

**Issue by Kein** [PowerShell/PowerShell#14936]
## Summary of the new feature/enhancement
See this comment from microsoft/vscode repo: https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

> When we build Visual Studio Code, we do exactly this. We clone the vscode repository, we lay down a customized product.json that has Microsoft specific functionality (telemetry, gallery, logo, etc.), and then produce a build that we release under our license.

>When you clone and build from the vscode repo, none of these endpoints are configured in the default product.json. Therefore, you generate a "clean" build, without the Microsoft customizations, which is by default licensed under the MIT license (note, i made this commit to help make this more clear).

## Proposed technical implementation details (optional)
As above, export telemetry and endpoints as a build configuration (that does not mean you should remove the env variables setup for people who use official builds)

**Comment by SteveL-MSFT** [comment]
Is the scenario that you are doing a build for development purposes and don't want to send the telemetry or that you want to redistribute a fork that doesn't have telemetry enabled?
