### ISSUE TITLE
Can't copy correctly when a folder or a file that contains Japanese dot (。) dragged to PowerShell or the path is copied from Windows Explorer to PowerShell

### ISSUE THREAD

**Issue by AlifianK** [PowerShell/PowerShell#14949]
PowerShell can't copy correctly when a folder or a file that contains a Japanese dot or full stop (。) dragged or the path copied from Windows Explorer. I've tried the same folder with Windows PowerShell but it seems it only affects PowerShell.
I've tried using ```Get-ChildItem``` to check whether PowerShell can detect the folder or not, and it displays the folder correctly
```
PS D:\> Get-ChildItem

    Directory: D:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          26/02/2021    16:32                Data
d----          05/01/2021    19:13                Games
d----          29/01/2021     6:39                Master
d----          23/02/2021    22:32                Multimedia
d----          07/11/2020    12:10                SUPERVISI MUTU LPMP
d----          03/03/2021    15:03                Tools
d----          05/03/2021    19:16                君の名は。 (Deluxe Edition)
-a---          17/08/2020    22:22         193632 JADWAL PELAJARAN DAN LAPORAN MATERI AJAR BDR SMP 5.docx
-a---          30/12/2019     8:55         403928 TIME TABLE GANIJIL TATAPMUKA.roz
```
when I tried to change the directory to ```君の名は。 (Deluxe Edition)``` via dragging the folder or copying the folder path from Windows Explorer, PowerShell can't do it.
```
PS D:\> Set-Location "D:\君の名は (Deluxe Edition)"
Set-Location: Cannot find path 'D:\君の名は (Deluxe Edition)' because it does not exist.
```
**notice that PowerShell didn't display (。) at all.**

Then I typed (。) manually or copied (。) separately to PowerShell and it worked
```
PS D:\> Set-Location "D:\君の名は (Deluxe Edition)"
Set-Location: Cannot find path 'D:\君の名は (Deluxe Edition)' because it does not exist.
PS D:\> Set-Location "D:\君の名は。 (Deluxe Edition)"
PS D:\君の名は。 (Deluxe Edition)>
```

## Steps to reproduce
Name a folder with Japanese full stop
```powershell
a。
```
then drag the folder or copy the folder path from Windows Explorer or to PowerShell then run ```Set-Location``` command to go to the folder

## Expected behavior
PowerShell should read the folder path correctly
```
PS D:\> Set-Location "D:\君の名は。 (Deluxe Edition)"
PS D:\君の名は。 (Deluxe Edition)>
```

## Actual behavior
PoweShell doesn't display (。) at all when the folder is dragged or when the directory path is copied or when the folder name is copied
```
PS D:\> Set-Location "D:\君の名は。 (Deluxe Edition)"
```
becomes
```
PS D:\> Set-Location "D:\君の名は (Deluxe Edition)"
```
## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by mklement0** [comment]
With `PSReadLine` version 2.1.0, I don't see the symptom, neither in a console window nor in Windows Terminal.

Don't know whether the `PSReadLine` version matters, but can you try upgrading to the latest stable version or can you run `Remove-Module PSReadLine` to unload the module before dragging & dropping, to see if that makes a difference.

**Comment by AlifianK** [comment]
Hmm weird, I've tried this again directly on Powershell console, and it worked. Apparently, it's a Windows Terminal problem, not Powershell. Thank you for answering.
