### ISSUE TITLE
Cannot set output codepage

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#14941]
## Steps to reproduce

Running `chcp <codepage>`, setting `[Console]::OutputEncoding`, or using PInvoke to call [SetConsoleOutputCP](https://docs.microsoft.com/en-us/windows/console/setconsoleoutputcp) should be setting the console output codepage. In Windows PowerShell this works but in PowerShell nothing is changed.

```powershell
Add-Type -TypeDefinition @'
using Microsoft.Win32.SafeHandles;
using System;
using System.Runtime.InteropServices;

namespace RawConsole
{
    public class NativeMethods
    {
        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleCP();

        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleOutputCP();
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleCP(
            uint wCodePageID);
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleOutputCP(
            uint wCodePageID);
    }
}
'@

# Take note of the original value
[RawConsole.Nativemethods]::GetConsoleOutputCP()

# Set using one of these 3 options, the value can be anything just something that isn't currently set
[RawConsole.Nativemethods]::SetConsoleOutputCP(1257)
chcp 1257

# On 2nd testing this does actually work
# [Console]::OutputEncoding = [Text.Encoding]::GetEncoding(1257)

# This should be updated with our new value
[RawConsole.Nativemethods]::GetConsoleOutputCP()
```

_Note: You cannot use `[Console]::OutputEncoding` to get the value for this test as it caches the value on the first call. This is why I'm using the PInvoke call to ensure there isn't any caching shenanigans going on in the .NET layer._

## Expected behavior

`GetConsoleOutputCP()` should output 1257.

## Actual behavior

`GetConsoleOutputCP()` outputs the original value. This value is whatever the console output codepage was set to when `pwsh.exe` was started.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Using conhost and not Windows Terminal here. This also only affects PowerShell and not Windows PowerShell.

## Other notes

Calling `SetConsoleCP()` and `GetConsoleCP()` works just fine it's just the output codepage that doesn't seem to have any affect. The Win32 function returns `$true` which indicates nothing went wrong. I'm honestly unsure whether this is a conhost problem, .NET issue, or PowerShell problem. Just trying here first.

I've had a brief look at the OpenConsole code in the terminal repo. Ultimately `SetConsoleOutputCP` calls [DoSrvSetConsoleOutputCodePage](https://github.com/microsoft/terminal/blob/4c53c595e79d2989ed6d126f8495b2a79edc98d2/src/host/getset.cpp#L964-L981) and there's nothing in there that jumps out to me to explain this behaviour. Of course I'm not actually using the OpenConsole.exe conhost but the one builtin to Windows and I'm 100% assuming the code is the same or at least not dramatically different. In any case it also doesn't explain why Windows PowerShell works but PowerShell does not.

**Comment by jborean93** [comment]
Just to give a trivial example of when this can be a problem, my default code page is 437 and running this in pwsh will output `?` because the character `Ǿ` isn't in that codepage.

```powershell
$cmd = '[Console]::WriteLine([string][char]0x01FE)'  # Ǿ

$encCmd = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($cmd))
pwsh.exe -EncodedCommand $encCmd
```

Note: This is highly dependent on the child process and how it's outputting the data. In this case this replicates the behaviour when the child process would open the STDOUT stream as a file and write raw bytes based on the console cp, or even `WriteConsoleA`.

Adding more confusion to the mix running `[Console]::OutputEncoding = [Text.Encoding]::UTF8` seems to actually affect the child process' .NET Console OutputEncoding but the native methods (`chcp`/PInvoke) do not.

```powershell
$cmd = '[Console]::WriteLine([string][char]0x01FE)'  # Ǿ

# chcp 65001  # Does not work as well as the PInvoke SetConsoleOutputCP(65001) method above
[Console]::OutputEncoding = [Text.UTF8Encoding]::new($false)

$encCmd = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($cmd))
pwsh.exe -EncodedCommand $encCmd
```

It seems like there's some inheritance going on with .NET that I just don't understand yet. The raw console output CP that Win32 reports is still the original value but setting `[Console]::OutputEncoding` does affect child .NET processes.

**Comment by SteveL-MSFT** [comment]
@jborean93 I don't believe PowerShell is doing anything here.  Can you write a simple C# app w/o PowerShell and see if it repros?  At least we can determine if it's .NET doing something.

**Comment by mklement0** [comment]
@jborean93, I haven't looked at the details yet, but I wonder if https://stackoverflow.com/a/65986012/45375 helps; in short running `chcp`  from _inside_ PowerShell is ineffective, due to .NET's caching of encodings in the `[Console]` class.

With respect to what `chcp` reports, it is, perhaps surprisingly, `[Console]::InputEncoding` that matters.

**Comment by SteveL-MSFT** [comment]
Although perhaps a bit counter-intuitive, it does seem that [InputEncoding](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L107) does call `SetConsoleCP`.

**Comment by jborean93** [comment]
@SteveL-MSFT I thought it was something up with .NET but if I was to compile this code (with the 5.0.1 sdk) and run it works without any problems:

```csharp
using System;
using System.Runtime.InteropServices;

namespace myApp
{
    public class NativeMethods
    {
        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleCP();

        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleOutputCP();
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleCP(
            uint wCodePageID);
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleOutputCP(
            uint wCodePageID);
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(NativeMethods.GetConsoleOutputCP().ToString());
            NativeMethods.SetConsoleOutputCP(65001);
            Console.WriteLine(NativeMethods.GetConsoleOutputCP().ToString());
        }
    }
}
```

If I was to run the equivalent (below) of that in PowerShell I get the same encoding (437) in my output instead of the one I set.

```powershell
Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

namespace RawConsole
{
    public class NativeMethods
    {
        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleCP();

        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleOutputCP();
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleCP(
            uint wCodePageID);
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleOutputCP(
            uint wCodePageID);
    }
}
'@

[RawConsole.NativeMethods]::GetConsoleOutputCP()
[RawConsole.NativeMethods]::SetConsoleOutputCP(65001)
[RawConsole.NativeMethods]::GetConsoleOutputCP()
```

> @jborean93, I haven't looked at the details yet, but I wonder if https://stackoverflow.com/a/65986012/45375 helps; in short, running chcp from inside PowerShell is ineffective, due to .NET's caching of encodings in the [Console] class.

It would be the case if I was using `[Console]::OutputEncoding` to check the value I set. In this case I'm going straight to the source with PInvoke to call `GetConsoleOutputCP()` and it's not being changed.

> Although perhaps a bit counter-intuitive, it does seem that InputEncoding does call SetConsoleCP.

There are 2 cp APIs, `SetConsoleCP` which corresponds with the input code page and `SetConsoleOutputCP` which is the output codepage.

**Comment by SteveL-MSFT** [comment]
PowerShell does have the `$OutputEncoding` automatic variable which is set on initial state and can be set by assigning it a value.  However, calling the Win32 API directly won't update this variable.  The PowerShell native command processor relies on this variable value.

**Comment by jborean93** [comment]
`$OutputEncoding` AFAIK just controls the encoding PowerShell uses when it's piping data into a native command like `"test" | something.exe`. It seems like the .NET code has changed quite a lot from the Framework days so it could explain the difference between Windows PowerShell and PowerShell. I'll have to look into it a bit more and see if it explains what is happening.

**Comment by jborean93** [comment]
Trying to clear out any confusion there are 2 codepages associated with the console, the input and output codepage. For those 2 cp's I know of 3 "native" ways of setting them

|Method|Input|Output|Notes|
|-|-|-|-|
|PInvoke|SetConsoleCP|SetConsoleOutputCP|I would consider this the absolute truth, it sources the data from the console itself and is how the other methods ultimately get/set the cp|
|chcp|chcp <num>|chcp <num>|This sets both the input/output in 1 command. Running `chcp` by itself only reports the input value though|
|.NET|`[Console]::InputEncoding`|`[Console]::OutputEncoding`|The value of these are cached, once it is retrieved once it will stay that way unless they were set in .NET itself||

I could be wrong here but from observation the output code page is important here. If something is writing bytes directly to the conhost STDOUT pipe (like `[Console]::WriteLine` does) then it's the value of the output cp that decodes the bytes back to text. If the bytes sent don't match up with what encoded it then we will get back garbage text.

To illustrate this a bite more let's say we run `[Console]::WriteLine('café'). here is what happens in the .NET land

* `Console.WriteLine` calls `Console.Out.WriteLine`
* `Console.Out` is a `SyncTextWriter` stream
* This stream will encode any strings using the `Console.OutputEncoding` value set
  * `Console.OutputEncoding` is cached so on the first call it will source the cp from `GetConsoleOutputCP()` which happens when pwsh first starts up
* The bytes are then written to a ConsoleStream which is based on a file handle for the STDOUT pipe
* This "pipe" sends the bytes to conhost
* Conhost will use the value of `GetConsoleOutputCP()` to decode those bytes back to text
* Conhost will then print that text to the screen buffer

In Windows PowerShell, all 3 methods work to change the console input/output codepage. I can use all 3 to set the console output cp to UTF-8 so that my example in https://github.com/PowerShell/PowerShell/issues/14941#issuecomment-790225777 outputs the proper character.

In PowerShell the 3 methods work for getting/setting the input console codepage but the output one is complex. Setting the output cp does not work with the PInvoke or chcp way. I can do `[Console]::OutputEncoding = [Text.Encoding]::UTF8` and it does actually work. Looking at the code setting `[Console]::OutputEncoding` is just flushing the existing out/err pipes and then calling `SetConsoleCP()` so I'm confused as to why I cannot just do that in PowerShell itself.

Taking out the `Console` class althogether and I can show another example that fails on PowerShell but works on Windows PowerShell.

```powershell
Add-Type -TypeDefinition @'
using Microsoft.Win32.SafeHandles;
using System;
using System.Runtime.InteropServices;

namespace RawConsole
{
    public class NativeMethods
    {
        [DllImport("Kernel32.dll")]
        public static extern SafeFileHandle GetStdHandle(
            int nStdHandle);
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleOutputCP(
            uint wCodePageID);
    }
}
'@

$stdoutHandle = [RawConsole.NativeMethods]::GetStdHandle(-11)
$fs = [IO.FileStream]::New($stdoutHandle, 'Write')

[RawConsole.NativeMethods]::SetConsoleOutputCP(65001)
$data = [Text.Encoding]::UTF8.GetBytes('café')
$fs.Write($data, 0, $data.Length)
$fs.Flush()

# This outputs 'caf├⌐' which is the UTF-8 bytes of my input decoded using cp 437
```

Doing the exact same with with PowerShell out of the picture and it works just fine

```csharp
using Microsoft.Win32.SafeHandles;
using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

namespace myApp
{
    public class NativeMethods
    {
        [DllImport("Kernel32.dll")]
        public static extern uint GetConsoleOutputCP();
    
        [DllImport("Kernel32.dll")]
        public static extern SafeFileHandle GetStdHandle(
            int nStdHandle);
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleOutputCP(
            uint wCodePageID);
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(NativeMethods.GetConsoleOutputCP());  // Just verifies the original was 437 in my case

            using (SafeFileHandle stdoutHandle = NativeMethods.GetStdHandle(-11))
            using (FileStream fs = new FileStream(stdoutHandle, FileAccess.Write))
            {
                NativeMethods.SetConsoleOutputCP(65001);
                
                byte[] data = Encoding.UTF8.GetBytes("café");
                fs.Write(data, 0, data.Length);
                fs.Flush();
            }
        }
    }
}
```

So ultimately I have 2 questions:

* Why does PInvoke `SetConsoleOutputCP()` not work when calling from PowerShell (Windows PowerShell is fine)
* Why does `[Console]::OutputEncoding = ...` work in PowerShell but the PInvoke method does not
  * It essentially does the same thing

Granted these are edge cases and it looks like doing `[Console]::OutputEncoding = ...` works for the majority of scenarios. What I really want to understand is why that's the case.

**Comment by jborean93** [comment]
Final thing to add it seems like this is only a problem if I'm calling `SetConsoleOutputCP()` directly from PowerShell.

The following does work and replicates the behaviour I'm seeing when running my pure .NET binary.

```powershell
Add-Type -TypeDefinition @'
using Microsoft.Win32.SafeHandles;
using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

namespace RawConsole
{
    public class NativeMethods
    {
        [DllImport("Kernel32.dll")]
        public static extern int GetConsoleOutputCP();

        [DllImport("Kernel32.dll")]
        public static extern SafeFileHandle GetStdHandle(
            int nStdHandle);
            
        [DllImport("Kernel32.dll")]
        public static extern bool SetConsoleOutputCP(
            int wCodePageID);
    }
    
    public class Program
    {
        public static void Main(string value, Encoding encoding)
        {
            Console.WriteLine(NativeMethods.GetConsoleOutputCP().ToString());
            NativeMethods.SetConsoleOutputCP(encoding.CodePage);
            Console.WriteLine(NativeMethods.GetConsoleOutputCP().ToString());  // It actually updates here!

            using (SafeFileHandle stdoutHandle = NativeMethods.GetStdHandle(-11))
            using (FileStream fs = new FileStream(stdoutHandle, FileAccess.Write))
            {                
                byte[] data = encoding.GetBytes(value);
                fs.Write(data, 0, data.Length);
                fs.Flush();
            }
        }
    }
}
'@

[RawConsole.Program]::Main('café', [Text.Encoding]::UTF8)
```

Is my PInvoke definition wrong, am I calling it incorrectly in Powershell?

**Comment by jborean93** [comment]
Thanks to @SeeminglyScience (once again!) the issue balls down to `PSReadLine` resetting the console codepage after every statement (maybe command I'm not 100% sure). So by setting it through `chcp` or PInvoke it is actually being sent to conhost PSReadLine is just setting it back afterwards before I go to check the value.

@SteveL-MSFT I can raise this issue in the PSReadLine repository but I assume it's expected behaviour and you are just expected to use `[Console]::OutputEncoding` to set this value going forward so will hold off unless you want me to open it.

**Comment by SeeminglyScience** [comment]
> `PSReadLine` resetting the console codepage after every statement (maybe command I'm not 100% sure).

It would be between interactive evals, if it's happening between statements then I can't explain why disabling PSRL fixes it tbh. Make sure your paste isn't being translated into multiple `ReadLine` loops (e.g. right clicking or ctrl v in some terminal apps).  Easiest way is to try it all on one line with semi colons or wrap in `& { }`.

**Comment by jborean93** [comment]
Yea I am just copy and pasting my examples so that would explain it even more.

**Comment by mklement0** [comment]
Great sleuthing, but do we know _why_ PSReadLine does that? Just to guard against external programs changing the code page?

**Comment by SeeminglyScience** [comment]
It saves the [initial output encoding on first `ReadLine`](https://github.com/PowerShell/PSReadLine/blob/f8fb650774a0c0e9421d9389f4a6dee5b8718b07/PSReadLine/ReadLine.cs#L710) call, and then resets it back to that [after every `ReadLine` finishes](https://github.com/PowerShell/PSReadLine/blob/f8fb650774a0c0e9421d9389f4a6dee5b8718b07/PSReadLine/ReadLine.cs#L441).

It can probably be updated to allow for mid-process encoding customizations.

**Comment by SteveL-MSFT** [comment]
Looking at git blame, it seems https://github.com/PowerShell/PSReadLine/commit/c3868e125069d87adbc5ee8f0274762a99510957 to address an issue with CJK chars coming from native commands
