### ISSUE TITLE
7.0.x on Ubuntu 20.04 - amd64

### ISSUE THREAD

**Issue by dsbenghe** [PowerShell/PowerShell#14952]
## Details of the Distribution

- Name of the Distribution: Ubuntu
- Version of the Distribution: 20.04
- Package Types
    - [x] Deb
    - [ ] RPM
    - [x] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request):  amd64
- The following is a requirement for supporting a distribution **without exception.**
    - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [x] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

### For PowerShell Team **ONLY**

- [ ] Docker image created - https://github.com/PowerShell/PowerShell-Docker/issues/558
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

There is already an issue open for Ubuntu 20.04 - https://github.com/PowerShell/PowerShell/issues/12626 - but that one seems to target just 7.1.x and also close for comments.

Considering that net core 3.1 is the LTS and supported on Ubuntu 20.04, and PSCore 7.0.x is the LTS and based on the same .net core 3.1, I would expect that PSCore 7.0.x is supported also on Ubuntu 20.04 but there is no package available.

To add to the confusion, the information about supporting 7.0.x on Ubuntu 20.04 is conflictual in the documentation:
- Here is mentioned as NOT supported: https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7
- Here is mentioned as supported: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7

**Comment by anmenaga** [comment]
@TravisEz13 is it something that can be done?

**Comment by TravisEz13** [comment]
@anamnavi Can you create the docker image from the LTS channel?

**Comment by TravisEz13** [comment]
This is already supported:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2#ubuntu
