### ISSUE TITLE
Windows Store version can't modify PATH

### ISSUE THREAD

**Issue by brunovieira97** [PowerShell/PowerShell#14957]
## Steps to reproduce

```powershell
PS> $path = [Environment]::GetEnvironmentVariable('Path', 'User)
PS> $newPath = "<add new entry here>;$path"
PS> [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
```

## Expected behavior

User's PATH content is altered and verifiable through System Properties > Environment Variables

## Actual behavior

PowerShell 7 reports the new value for the User's PATH.

User's PATH remains the same on every software (Windows PowerShell, for example) and System Properties > Environment Variables.

Example, showing `C:\Users\bruno\foo` is on my PATH (I've added it using steps documented above) according to PowerShell 7 downloaded from Microsoft Store:
 
```powershell
PS> [Environment]::GetEnvironmentVariable('Path', 'User')

C:\Users\bruno\foo;C:\Users\bruno\scoop\apps\gpg\current\bin;C:\Users\bruno\scoop\apps\nodejs\current\bin;C:\Users\bruno\scoop\apps\nodejs\current;C:\Users\bruno\scoop\shims;C:\Users\bruno\AppData\Local\Microsoft\WindowsApps;C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\bruno\AppData\Local\Programs\Azure Data Studio\bin
```

If I go to System Properties, PATH is different, not showing the path I added through PS7:
![image](https://user-images.githubusercontent.com/19749621/110250680-52a18280-7f5b-11eb-853a-2e0d86244ef6.png)

Some important notes:

 - New value is always shown in PowerShell 7 only
 - This does not occur with PS 7 installed through MSI, only MS Store version
 - This happens independently of Terminal used (ConHost and Windows Terminal tested)
 - Occurs even after launching a new instance (of Windows Terminal AND PS 7, tested that)
 - New PATH is never shown in System Properties or Windows PowerShell, even after launching new instances, logging out or rebooting the PC
 - Only way to revert the PATH on PS 7 (so it has the same value as the System Properties one) is editing it through PS 7, as no other way contains the bugged content

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by I-Cat** [comment]
'''
Get path would be a path that is already set

Set path is to set a path 

'''

**Comment by brunovieira97** [comment]
@I-Cat I don't think you understood the issue I reported.

**Comment by SteveL-MSFT** [comment]
Windows Store apps are sandboxed, by design.  PowerShell 7 store app explicitly requests [unvirtualized resources](https://github.com/PowerShell/PowerShell/blob/master/assets/AppxManifest.xml#L47) which should include registry (that's where `PATH` is persisted), but seems like this isn't being honored.  Will have to follow-up with the AppX folks.

**Comment by I-Cat** [comment]
The answer is odd but here it is type in the following
''cmd.exe 
cmd.exe
cd \
PATH=ADD
PATH
PATH=%YOUR PATH VALUE%
PATH=PATH=C:\Java\jdk1.8.0_131\bin;C:\Python39\Scripts;C:\Python39;C:\Program Files\Intel\iCLS Client;C:\Program Files (x86)\Intel\iCLS Client;C:\Windows;C:\win\system32;C:\Windows\System32;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Yarn\bin;C:\Huawei\bin;C:\Windows;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\ProgramData\chocolatey\bin;C:\Users\@I-CAT\nodejs;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\@I-CAT\Git\cmd;C:\Users\@I-CAT\Huawei\bin;C:\Users\@I-CAT\Huawei\resources\app\extensions\deveco-debug\lib\toolkit;C:\Users\@I-CAT\go\bin;C:\Users\@I-CAT\node\;C:\Program Files (x86)\Git LFS;C:\Program Files\TortoiseSVN\bin;C:\Users\@I-CAT\AppData\Local\Microsoft\WindowsApps;C:\Users\@I-CAT\python\;C:\Users\@I-CAT\python\Scripts\;C:\Program Files (x86)\GitHub CLI;C:\Git\mingw64\bin\git.exe;C:\Users\@I-CAT\go\bin;C:\Users\@I-CAT\AppData\Local\atom-nightly\bin;C:\Users\@I-CAT\AppData\Local\GitHubDesktop\bin;C:\Users\@I-CAT\Microsoft_Code\bin;C:\Users\@I-CAT\AppData\Roaming\npm;
''

**Comment by vexx32** [comment]
@I-Cat this issue is about PowerShell and not cmd.exe.

**Comment by I-Cat** [comment]
> @I-Cat this issue is about PowerShell and not cmd.exe.

Yes thank you. Powershell calls cmd.exe and others think of it as a shortcut command and the code should be


PS> [Environment]::GetEnvironmentVariable('Path', 'System')
To set system paths.

**Comment by vexx32** [comment]
Yes. 

This issue is about how specifically in the version of PowerShell from the Windows store, the PATH variable cannot be modified in a persistent way (in user / machine scope) due to msix sandboxing behaviour.

**Comment by kilasuit** [comment]
This works fine for machine scope & actually seems to work fine at returning the edited User scope on new PowerShell processes

what seems not to be updating is the System Properties User Path UI which I don't think updates anyway until you log off and on again as PowerShell reads it from Registry anyway (on windows)

Code to repro
process 1
```powershell
$path = [Environment]::GetEnvironmentVariable('Path', 'User)
$newPath = "C:\Tmp\";$path"
[Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
```
process 2 (started after this)
```powershell
 [Environment]::GetEnvironmentVariable('Path', 'User').split(';') -contains "C:\Tmp\"
```

**Comment by vexx32** [comment]
From the issue post:

> Some important notes:
>
> - New value is always shown in PowerShell 7 only
> - This does not occur with PS 7 installed through MSI, only MS Store version
> - This happens independently of Terminal used (ConHost and Windows Terminal tested)
> - Occurs even after launching a new instance (of Windows Terminal AND PS 7, tested that)
> - New PATH is never shown in System Properties or Windows PowerShell, even after launching new instances, logging out or rebooting the PC
> - Only way to revert the PATH on PS 7 (so it has the same value as the System Properties one) is editing it through PS 7, as no other way contains the bugged content

@brunovieira97 can you double check to make sure you're on the latest version? I know there were some issues around this sort of thing in the first handful of versions on the Windows Store, but from what I've heard and from other folks' mentions on this thread, it _should_ be more or less sorted by now.

**Comment by I-Cat** [comment]
> This works fine for machine scope & actually seems to work fine at returning the edited User scope on new PowerShell processes
> 
> what seems not to be updating is the System Properties User Path UI which I don't think updates anyway until you log off and on again as PowerShell reads it from Registry anyway (on windows)
> 
> Code to repro
> process 1
> 
> ```powershell
> $path = [Environment]::GetEnvironmentVariable('Path', 'User)
> $newPath = "C:\Tmp\";$path"
> [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
> ```
> 
> process 2 (started after running above)
> 
> ```powershell
>  [Environment]::GetEnvironmentVariable('Path', 'User').split(';') -contains "C:\Tmp\"
> ```

Then you need a simple script that will do this in power shell.

cmd.exe shutdown/l

**Comment by brunovieira97** [comment]
> This works fine for machine scope & actually seems to work fine at returning the edited User scope on new PowerShell processes
> 
> what seems not to be updating is the System Properties User Path UI which I don't think updates anyway until you log off and on again as PowerShell reads it from Registry anyway (on windows)
> 
> Code to repro
> process 1
> 
> ```powershell
> $path = [Environment]::GetEnvironmentVariable('Path', 'User)
> $newPath = "C:\Tmp\";$path"
> [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
> ```
> 
> process 2 (started after running above)
> 
> ```powershell
>  [Environment]::GetEnvironmentVariable('Path', 'User').split(';') -contains "C:\Tmp\"
> ```

For me, the new value is only returned on new PowerShell 7 instances. A new Windows PowerShell instance won't return "C:\Tmp\" in User's Path.
