### ISSUE TITLE
be fast

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14959]
Hi Guys !!

Powershell is great but in certain case is very very slow compared to other scripting languages...its possible to re-write some code source with rust in future ?

**Comment by vexx32** [comment]
Possible? Sure, anything's possible.

I doubt it's very likely, though. Part of PowerShell's versatility stems from .NET, and I think at least at the moment it would be hazardous at best, if not entirely detrimental, to replace core functionalities with Rust code instead.

It would probably be simpler to write a scripting language shell in Rust from the beginning, to be honest.

**Comment by doctordns** [comment]
I suspect the integration of Rust and .NET may not be adequate for most things. There would need to be a bit of work, I suspect, to create Rust.NET. 

Besides, why do you think that RUST is going to somehow magically speed up PowerShell?

**Comment by SeeminglyScience** [comment]
PowerShell is slow mostly because of the amount it does for you at runtime.  There are a lot of areas for improvement in the code base, but if it were rewritten in rust (assuming that was feasible in the first place) to the exact same level of quality then performance probably wouldn't be that different.

**Comment by SteveL-MSFT** [comment]
Targeted perf improvements have been made in PowerShell and we automatically get perf improvements from .NET.  It would be more useful to know specific scenarios where speed is required and expected to be able to do something with this issue.
