### ISSUE TITLE
Manipulating strings of size greater than ~1.5 Gb consumes all available resources

### ISSUE THREAD

**Issue by L00pZBreak3r** [PowerShell/PowerShell#14951]
I don’t know if it's a bug or not, but I was able to write a PowerShell script that consumed all available CPU time and memory.

When I ran the script my mouse pointer got slower and slower and eventually completely stopped. Both mouse and keyboard became unresponsive and the only thing a could do was pressing the reset button.

I suspect that it happened when the script’s internal string (one of its variables) got about 1.5 Gb in size.

**Comment by doctordns** [comment]
How much RAM do you have?

**Comment by powercode** [comment]
What are you doing, and what do you expect to happen?

**Comment by L00pZBreak3r** [comment]
I didn’t expect that a PowerShell script that doesn’t have instructions increasing the priority of its process is able to make a computer freeze.

**Comment by vexx32** [comment]
The key thing with strings is that they are, fundamentally, immutable. .NET does not allow you to modify a string. All string operations involve copying portions of or the entire original string, and then saving the new string to a new memory address.

So if you're doing repeated operations on very large strings, it's certainly possible to end up consuming all available resources. Strings aren't designed for that kind of operation to happen repeatedly with enormous strings.

This isn't really a PowerShell problem, it stems from .NET itself. But really, it's probably moreso that you're trying to use tools that weren't designed for the kinds of operations you're trying to do.

If you need to manipulate that much data in detail you're probably better off managing the strings as `[char[]]` arrays, being careful to allocate enough space to do what you need from the beginning. There is also the option of [StringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=net-5.0) which is much more efficient for building strings without excessive allocation.

The tool you should use depends on exactly what you're needing to do, though.

**Comment by L00pZBreak3r** [comment]
What surprised me the most is that a script was able to make **entire Windows completely unresponsive**. If it was only the PowerShell terminal got unresponsive, I’d never consider that situation worth reporting. So, the question is:
_Can a trivial PowerShell script make Windows completely unresponsive?_

`$bigString = ""
$aFiles = Get-ChildItem -Path "a folder with a lot of files" -File
foreach ($aFile0 in $aFiles)
{
    $afc0 = Get-Content -Path $aFile0 -Raw
    $bigString = -Join($bigString, $afc0)
  }
}
Set-Content -Path "OutputFile.txt" -Value $bigString -Encoding Unicode`

**Comment by SeeminglyScience** [comment]
> Can a trivial PowerShell script make Windows completely unresponsive?

Yeah for sure it's possible.

**Comment by powercode** [comment]
You can try to wrap the script with
```powershell
$currentProcess = Get-Process -id $pid 
$originalPriority = $currentProcess.PriorityClass
$currentProcess.PriorityClass = 'Idle' 
try {
  # your code goes here
}
finally{
   $currentProcess.PriorityClass = $originalPriority 
}
```

But your real problem is that you have a fundamentally inefficient way of solving your original problem.

A red flag should always go up when you see code like
```powershell
$bigString = -Join($bigString, $afc0)
or
$bigString += "some more text"
```
because, as @SeeminglyScience explained, strings are not designed to be mutated. Other data structures should be used.

**Comment by powercode** [comment]
For example:

```powershell
Clear-Content OutputFile.txt
$aFiles = Get-ChildItem -Path "a folder with a lot of files" -File
foreach ($file in $aFiles)
{
    $fileContent = Get-Content -Path $file -Raw
    Add-Content -LiteralPath OutputFile.txt -value $fileContent -NoNewLine
}
```
Should do the same thing. If any single file is larger that available memory, you could review stream-based solutions.

**Comment by SeeminglyScience** [comment]
> because, as @SeeminglyScience explained, strings are not designed to be mutated. Other data structures should be used.

(that was @vexx32 btw)
