### ISSUE TITLE
Cause Win10 Dev 21322 green screen(Attach dump log)

### ISSUE THREAD

**Issue by DustinWin** [PowerShell/PowerShell#14967]
Environment:
PowerShell Preview: 7.2.0-preview.3
Oh my Posh version: V3（V2 normal）
Theme: PowerLine
Operating System: Windows 10 Dev 21322(and above)

Steps to Reproduce：
1. Install Windows 10 Dev 21322;
2. Install Git(v2.30.1);
3. Run PowerShell Preview as an administrator, and run the following commands in sequence:
```
Set-ExecutionPolicy RemoteSigned
Install-Module posh-git
Install-Module oh-my-posh
```
4. Run the following commands again in sequence
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
```
5. Create a new "WindowsPowerShell" folder in the "C:\Users\ [Your name] \Documents" directory, and create a new text document. Edit the following content:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
```
Save as "Microsoft.PowerShell_profile.ps1".
6. Restart the computer, run PowerShell again as an administrator.

Expected behavior: Oh-my-posh can be loaded normally, the computer will not have a green screen.

Actual behavior: The computer will have a green screen.

Attach dump log:
[dump.log.zip](https://github.com/PowerShell/PowerShell/files/6100432/dump.log.zip)

**Comment by SteveL-MSFT** [comment]
PowerShell runs in user space and thus itself cannot cause a green screen (which is a kernel mode crash).  I would suggest updating drivers (perhaps video driver) which are likely causes of green screens.

**Comment by DustinWin** [comment]
> PowerShell runs in user space and thus itself cannot cause a green screen (which is a kernel mode crash). I would suggest updating drivers (perhaps video driver) which are likely causes of green screens.

I am using "Windows Update" to update the graphics card driver, the version is 27.20.11028.10001. 
The graphics driver pushed by Microsoft √
Install the graphics driver by myself ×
😂
