### ISSUE TITLE
Containers: PSSTYLE is a royal pain. Can we use environment variables for configuration?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#14964]
We really need a way to control PowerShell's **configuration** from **outside** a container.

Really, PowerShell should obviously respect _ENVIRONMENT_ variables like `TERM=dumb` or [`NO_COLOR`](https://no-color.org/) that we can set globally, and which we can pass into a docker container.

It needs to be something I can set when I'm not calling PowerShell directly, and ideally which works with _existing_ containers, so I don't have to try to mount a system `profile.ps1` into **every different container** we use...

Right now I have a docker container where PowerShell is being run with `-NonInteractive` but whenever there's an error it spews a bunch of `[96m` and `[91m` and so on... 

![image](https://user-images.githubusercontent.com/192942/110272565-818a1980-7f98-11eb-8fa3-fd3b1950151a.png)

While we're talking about it, I also want to turn off Progress output with an environment variable too, because the output in that screenshot is really weird.

Having to reach into a docker container and create a global profile to disable color isn't really a good solution.

**Comment by SteveL-MSFT** [comment]
ANSI is currently controlled based on whether `SupportsVirtualTerminal` is `true`.  Unfortunately, on UNIX, we always [return true](https://github.com/PowerShell/PowerShell/blob/6d7fbed02bcd8d5a2997626a4bf6e2c0302c2fd4/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L65).  We should probably at least respect `TERM=dumb` to output plaintext.

**Comment by mklement0** [comment]
@SteveL-MSFT, perhaps we can also revisit the idea of a new CLI parameter that controls the behavior:

To quote you from https://github.com/PowerShell/PowerShell/issues/10811#issuecomment-546126662:

> @lzybkr had a good suggestion to have a param on `pwsh` like `-color` with `always`, `auto`, `never` values.

**Comment by SteveL-MSFT** [comment]
@mklement0 I had forgotten about that.  Certainly, a new pwsh param that maps to `OutputRendering` would make sense and would override the env var
