### ISSUE TITLE
why i hate the dot

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14963]
hi guys !!

```
PS> 1.000.000.000
PS> # NOT RETURN ANYTHGING

PS> perl6 -e 'say 1_000_000_000'
1000000000


PS> @'
>> fn main() {
>>  let s = 1_000_000_000;
>>  println!("{}",s);
>> }
>> '@ > ./num.rs

PS> rustc .\num.rs

PS> ./num.exe
1000000000
```

in this example i compared between rust, raku and PS....like you see rust and raku use "_" underscore to separate betwwen number and its much clean...but in PS with "." dot it not return anything.

**Comment by vexx32** [comment]
PowerShell doesn't have a number separator like that. I have previously proposed to add an underscore numeral separator, but it was vetoed during review of the PR a year or two back, I think.

When you do `1.000` PowerShell sees that as a floating point number with the value `1.000`. If you then attempt to use another dot, PowerShell assumes you want to access a property, but `1.000` as a numeric value has no property named `.000` and so it will return $null, and further property access from that point will continue to return $null.

`1.000.000.000` tells PowerShell:

1. make a number, `1.000` (floating point, double)
2. access the property of that number called `000` (null)
3. access the property of that value called `000` (null again)

**Comment by p0W3RH311** [comment]
its crazy thing:

```
PS C:\> [string]::IsNullOrWhiteSpace(1.000.000.000)
True
PS C:\>
```

but this is considered a bug

**Comment by p0W3RH311** [comment]
its crazy
```

PS C:\> [string]::IsNullOrWhiteSpace(1.000.000.000)
True
PS C:\>
```

the code its writtin to human not to machine...the parser is not intelligent

**Comment by mklement0** [comment]
@p0W3RH311, no that's just a consequence of the behavior that @vexx32 explained: your command is in effect equivalent to:

```powershell
[string]::IsNullOrWhiteSpace($null)
```

Clearly, `.` is unsuitable as a culture-invariant _thousands-grouping_ separator, given that `.` is the culture-invariant _decimal mark_.

By contrast, `_` as the thousands-grouping separator in _number literals_ indeed would make sense - but has apparently been rejected.

**Comment by vexx32** [comment]
For reference: https://github.com/PowerShell/PowerShell/pull/7993#issuecomment-442651543

You might still find the implementation code in the older commits there, if there is interest in revisiting it.

**Comment by ShrykeWindgrace** [comment]
@mklement0 FYI, `.` is most definitely **not** a culture-invariant decimal mark. Judging by the number of countries in different sections in https://en.wikipedia.org/wiki/Decimal_separator#Hindu-Arabic_numerals, comma and dot are both in widespread use.

**Comment by ShrykeWindgrace** [comment]
@mklement0 Indeed, I forgot about the context here, and my comment was harsh - and uncalled for; please accept my apologies.
