### ISSUE TITLE
"Unable to modify the shortcut"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [PowerShell/PowerShell#14978]
## Steps to reproduce

Right-click title bar of PowerShell 7.1.2 (or any 7.x.x version) and choose **Properties**.  Make any number of changes in any of the tabs, then click OK.

## Expected behavior

The expectation is that these settings would be saved.

## Actual behavior

An error occurs:

```none
---------------------------
Error Updating Shortcut
---------------------------
Unable to modify the shortcut:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\PowerShell 7 (x64).lnk.
Check to make sure it has not been deleted or renamed.
---------------------------
OK   
---------------------------
```

I have seen solutions around the internet which involve steps like creating a new shortcut to the existing shortcut, yada yada (stuff that shouldn't be necessary).

## Environment data

```powershell
>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
I agree that this should be fixed; it has come up twice before: #13148 and #7825, but both issues were closed.

https://github.com/PowerShell/PowerShell/issues/7825#issuecomment-423024388 explains why this currently happens, and I also suggested the following there:

> As for **what needs fixing**:

> * The PowerShell installer could create a _per-user_ Start Menu shortcut for PS Core instead of a single, shared one that requires elevation to modify (as an aside, if multiple users try to customize the shortcut, the customizations could collide).

>   * This is how `cmd.exe` already does it for its `Command Prompt` shortcut, which is placed in `"$env:APPDATA\Microsoft\Windows\Start Menu\Programs\System Tools"` - for every user.

**Comment by ZeldrexK0DE** [comment]
Still exists in latest release.

**Comment by iSazonov** [comment]
PowerShell msi is installed on _system_, not user. It is how MSI works. The shortcut is protected by OS permissions.
You can create a custom shortcut and modify its properties.

**Comment by JeremyTBradshaw** [comment]
It is hideous, regardless of if it is MSI's fault.  Someday, this will be realized and the issue will be addressed somehow.  Maybe I'm wrong, certainly seems like this issue is pretty specific to PowerShell, just can't think of another program to compare with because, nothing else needs to modify the shortcut to save these kinds of basic preferences.

So sick of that answer.  It's a garbage feature, period.  Windows terminal addresses this by taking over for it in this area.  That alone is enough to point out it could be addressed some other way, rather than blaming MSI.

**Comment by iSazonov** [comment]
If you use personal device you can change manually permissions on the shortcut file.

**Comment by ZeldrexK0DE** [comment]
> If you use personal device you can change manually permissions on the shortcut file.

It is an personal pc and it still doesn't let me create a shortcut that it recognize to be edited

**Comment by JeremyTBradshaw** [comment]
Didn't realize @iSazonov teed this up for closure.  Great.  Oh well, moving on again.  Someday... It maybe Microsoft will just revive Windows PowerShell again and fix things there.

**Comment by anton-x-t** [comment]
> PowerShell msi is installed on _system_, not user. It is how MSI works. The shortcut is protected by OS permissions. You can create a custom shortcut and modify its properties.

I had this general problem too.

Thank you for the tip @iSazonov, it can be used as a temporary workaround.

**Comment by o-l-a-v** [comment]
Another workaround:

1. Drag and drop (copy) the shortcut from `%ProgramData%\Microsoft\Windows\Start Menu\Programs\PowerShell` to some place that does not require admin to edit stuff.
  * I chose target `%USERPROFILE%\Desktop`.
1. Edit the shortcut, I wanted to change font and did it from right click -> properties -> font.
1. Drag and drop while holding SHIFT (overwrite) your modified shortcut from  `%USERPROFILE%\Desktop` back to `%ProgramData%\Microsoft\Windows\Start Menu\Programs\PowerShell`.
  * Will ask for admin permissions.
