### ISSUE TITLE
Powershell on AWS Lambda running failing with following error: Unable to load shared library 'libpsrpclient' or one of its dependencies

### ISSUE THREAD

**Issue by andybirenzi** [PowerShell/PowerShell#14972]
## Steps to reproduce

```
Import-Module ExchangeOnlineManagement; 
$creds = New-Object System.Management.Automation.PSCredential -ArgumentList $username, $secureStringPwd

Connect-ExchangeOnline -Credential $creds

```

## Expected behavior

```
I'm running Powershell on MacOS and it works fine there. But when I deploy it on AWS Lambda, I'm getting below error:

```

## Actual behavior
ERROR:

```"errorType": "PSRemotingTransportException",
  "errorMessage": "This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.",
  "stackTrace": [
    "at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost.ExecuteFunction(Stream inputStream, ILambdaContext context)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ],
  "cause": {
    "errorType": "DllNotFoundException",
    "errorMessage": "Unable to load shared library 'libpsrpclient' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibpsrpclient: cannot open shared object file: No such file or directory",
    "stackTrace": [
      "at System.Management.Automation.Remoting.Client.WSManNativeApi.WSManInitialize(Int32 flags, IntPtr& wsManAPIHandle)",
      "at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.WSManAPIDataCommon..ctor()"
    ]
  }
```

## Environment data

```Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by jborean93** [comment]
Based on the `$PSVersionTable` this is running on a macOS host which is surprising to me as I didn't know you could do that with AWS Lambda (I know very little about it really). The `mi` library shipped with PowerShell on macOS has it's own unique problems compared to the Linux distributions. It is dynamically linked to OpenSSL 1.0.x at `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib` and `/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib`. To get the builtin version running on macOS you need to install a copy of OpenSSL 1.0.x (1.1.x won't work) and make sure those dylibs are in those locations. If you can run this on a Linux host it will be easier to set up as some distros still package that OpenSSL version and it should just work out of the box.

The alternative is to use a fork of `mi` and `psrpclient` that I maintain https://github.com/jborean93/omi. This fixes a few problems with the builtin copy of `mi` in particular for this use case

* Links to OpenSSL 1.1.x
  * Uses newer and stronger cryptographic features not available in 1.0.0x
  * Easier to install on hosts like macOS where OpenSSL 1.0.x is no longer available in the default repositories
  * Still supported and continues to have security fixes released by OpenSSL
* Enables HTTPS certificate verification
  * Version included by PowerShell does not validate the CA or CN of the HTTPS endpoint
* Increases the password length to support larger JWT tokens
  * This is important for modern auth as I've encountered tokens that exceed the arbitrary password limit set in the builtin `mi` library shipped by PowerShell

I am in no way affiliated with Microsoft or the PowerShell team so there is no support guaranteed if things go wrong. I try my best to help people who post issues on my forked repo but I can't gurantee a turnaround time or that I will fix the problem. If you wish to use this fork you will have to install it like this (run as root)

```powershell
Install-Module -Name PSWSMan -Scope AllUsers
Install-WSMan
```

Once installed you can close and reopen PowerShell for the new library to be in place and picked up by PowerShell.
