### ISSUE TITLE
new parameter -Generator and -Length to Get-Random

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14989]
hi guys !!

here an example
```

PS C:\> get-random -generator char -count 5
a
B
Z
i
m

PS C:\> get-random -generator int -count 5
5
120
3
7898
9

PS C:\> get-random -generator float -count 5
1.232
9.21
1.32
4.3
5.4

PS C:\> get-random -generator chars -count 5 -length 3
foo
prt
vgt
cAl
Noi
```

**Comment by mklement0** [comment]
Just so we get a sense of what we would gain, let's look at how the same results can be achieved with the current features:

```powershell
# (Near-)equivalent of:
#    get-random -generator char -count 5
get-random ('a'..'z') -count 5

# (Near-)equivalent of:
#    get-random -generator int -count 5
get-random -count 5 -Maximum 1000.0  # [int] is default, in the range 0..([int]::MaxValue-1)

# (Near-)equivalent of:
#    get-random -generator float -count 5
get-random -Minimum 0.0  -Maximum 1000 -count 5  
```

Note that it usually makes sense to limit the range of values, as shown above, which requires explicit `-Minimum` and/or `-Maximum` arguments anyway, and you can use the _type_ of these arguments to imply the output type.

Unfortunately, however, that works for `[int]`, `[double]` and `[long]` only; for others, such as `[byte]` or `[decimal]`, the fallback is `[double]` - see #3598; it was decided not to fix that, however, and the behavior is now documented in the [`Get-Random` help topic](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-random#notes).

Only your last example, `get-random -generator chars -count 5 -length 3`,  currently requires nontrivial extra work:

```powershell
(1..5).ForEach({ -join ('a'..'z')[(Get-Random -Maximum 25 -Count 3)] })
```

However, I wonder whether a syntax like `Get-Random -StringOfLength 3 -Count 5` would be sufficient.

**Comment by joeyaiello** [comment]
Given that most of these can be achieved with existing syntax, and our push to drive new cmdlet functionality via Gallery/community modules, I'd encourage any experimentation for additional `Get-Random` helpers to be done in some sort of community-driven `Get-Random2`
