### ISSUE TITLE
LocalRunspace.ResetRunspaceState() add back default built-in variables instead of reset to exact variables the Runspace initially had

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#14987]
## Steps to reproduce

```powershell
## Remove all removable built-in variables from the InitialSessionState, and create Runspace with it
$iis = [initialsessionstate]::CreateDefault2()
$iis.Variables.Clear()
$ps = [powershell]::Create($iis)

Write-Host "View the available built-in variables:"
$ps.AddCommand("Get-Variable").Invoke()

## Reset the Runspace state
$ps.Runspace.ResetRunspaceState()

Write-Host "View the available built-in variables after RunspaceReset:"
$ps.Invoke()
```

## Expected behavior

The available variables before and after `RunspaceReset` are the same.

## Actual behavior

After `RunspaceReset`, the built-in variables that were intentionally removed when creating the Runspace were added back.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
I think ResetRunspaceState was originally intended to set the state to a 'beginning' state, that included built-in variables.  So as not to break existing behavior, maybe we can add a parameter to skip restoring built-in variables.

**Comment by daxian-dbw** [comment]
> I think ResetRunspaceState was originally intended to set the state to a 'beginning' state

The current behavior of `ResetRunspaceState` is that it adds back all built-in variables plus the variables that user added to `$iis.Variables`. So it only honors the `$iis` partially -- the variables added but not those removed.

**Comment by daxian-dbw** [comment]
The Engine-WG reviewed this issue. The current behavior has been there since at least PowerShell v3, and it's risky to break the current behavior. It would be nice to have `CheckPoint` and `Restore` capabilities for `Runspace`, so it can be restored to a previous state, but that would be complicated if not infeasible. So, for now, we decided to close this issue as won't fix.
