### ISSUE TITLE
ctrl+l dont clear all screen

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#14988]
Hi guys !!

if i try to clear screen with 'ctrl+l' it not clear all screen until i use x time this shortcut

![1](https://user-images.githubusercontent.com/36144546/110701769-73114d00-81a6-11eb-9ff3-78f39d132141.PNG)
![2](https://user-images.githubusercontent.com/36144546/110701788-77d60100-81a6-11eb-94f1-ea4b00264cf9.PNG)
![3](https://user-images.githubusercontent.com/36144546/110701805-7c9ab500-81a6-11eb-9a53-9da76bf1f77c.PNG)
![4](https://user-images.githubusercontent.com/36144546/110701816-80c6d280-81a6-11eb-80da-488ff6983253.PNG)

```
PS C:\> $Host.UI.RawUI

ForegroundColor       : Gray
BackgroundColor       : Black
CursorPosition        : 0,1
WindowPosition        : 0,0
CursorSize            : 25
BufferSize            : 98,3000
WindowSize            : 98,25
MaxWindowSize         : 98,25
MaxPhysicalWindowSize : 105,25
KeyAvailable          : False
WindowTitle           : PowerShell 7 (x64)


PS C:\> 
```

**Comment by joeyaiello** [comment]
I'm not seeing this reproduce on my Win10 box with 7.1. Can you launch with `pwsh -noprofile` to make sure you don't have some sort of modifications mucking things up?
