### ISSUE TITLE
No WhatIf output in Foreach-Object -Parallel

### ISSUE THREAD

**Issue by tleepa** [PowerShell/PowerShell#14984]
When I run a command with `-WhatIf` switch within a `Foreach-Object` loop, it shows the "What if: ..." output.
When doing the same with `-Parallel`, this output is not shown.

If there is `Write-Host` statement in loop body, it is visible in both cases.

Is there anything I can do about it? Is it a bug, or by design?

## Steps to reproduce

Prepare some directories:
```powershell
("test1", "test2", "test3") | ForEach-Object { New-Item -Path .\$_ }
```

Then remove them with -WhatIf switch using -Parallel
```powershell
("test1", "test2", "test3") | ForEach-Object -Parallel { Remove-Item -Path .\$_ -WhatIf }
```

## Expected behavior

Should be the same as running:
```powershell
("test1", "test2", "test3") | ForEach-Object { Remove-Item -Path .\$_ -WhatIf }
```

```none
What if: Performing the operation "Remove File" on target "<current dir>\test1".
What if: Performing the operation "Remove File" on target "<current dir>\test2".
What if: Performing the operation "Remove File" on target "<current dir>\test3".
```

## Actual behavior

```none
<No ouput>
```

## Environment data

```none
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
Remoting working group:  We still need to figure out why this is not coming through and possibly add a feature.  

Do you have a real-life scenario that you need to run whatif in parallel?

**Comment by tleepa** [comment]
Well, I am using parallel to loop over actions in Azure, that can be time-consuming.
I am using a -Noop switch in my scripts and run some commands using `-WhatIf:$Noop`. This way I don't have to test for the switch value and run different commands.
But it is not a deal breaker :)

**Comment by TravisEz13** [comment]
```powershell
❯ Copy-Item ./test.ps1 ./test2.ps1 -WhatIf *> test.txt
What if: Performing the operation "Copy File" on target "Item: /Users/travisplunk/git/powershell/test.ps1 Destination: /Users/travisplunk/git/powershell/test2.ps1".
```

I did a little investigation.  It appears that `-whatif` writes directly to the host and is not redirectable.

I'll let @PaulHigin  speak for what this means for `foreach-object -parallel` but I don't think it is good.

**Comment by JustinGrote** [comment]
@TravisEz13 this would be solved by: https://github.com/PowerShell/PowerShell/issues/9870
