### ISSUE TITLE
PS Core command line parsing of arrays -- Linux vs. Windows...

### ISSUE THREAD

**Issue by rtestardi** [PowerShell/PowerShell#14981]
Any idea why these would be different?  PS Core on Linux seems wrong printing "a,b,c" as the value for $nodes[0]; whereas, PS Core on Windows (as well as Windows powershell) properly (in my opinion :-) prints "a" as the value for $nodes[0].  Note that removing the "powershell " from the respective command line causes it to work properly even on Linux, but I want the script to run in a different process.

PS Core on Windows:

    PS C:\Users\richardt> echo 'param ([array]$nodes = $null); echo $nodes[0]' >array.ps1; powershell .\array.ps1 -nodes a,b,c

    a

    PS C:\Users\richardt> $psversiontable

    Name                           Value
    ----                           -----
    PSVersion                      7.1.2
    PSEdition                      Core
    GitCommitId                    7.1.2
    OS                             Microsoft Windows 10.0.19042
    Platform                       Win32NT
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0 

    PS C:\Users\richardt>

PS Core on Linux:

    PS /home/storsimple> echo 'param ([array]$nodes = $null); echo $nodes[0]' >array.ps1; powershell .\array.ps1 -nodes a,b,c

    a,b,c

    PS /home/storsimple> $psversiontable

    Name                           Value
    ----                           -----
    PSVersion                      7.1.2
    PSEdition                      Core
    GitCommitId                    7.1.2
    OS                             Linux 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021
    Platform                       Unix
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0

    PS /home/storsimple>

Windows powershell:

    PS C:\temp> echo 'param ([array]$nodes = $null); echo $nodes[0]' >array.ps1; powershell .\array.ps1 -nodes a,b,c

    a

    PS C:\temp> $psversiontable

    Name                           Value
    ----                           -----
    PSVersion                      5.1.19041.610
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.19041.610
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1 

    PS C:\temp>

**Comment by mklement0** [comment]
`powershell.exe` defaults to the `-Command` / `-c` parameter, which interprets the string resulting from space-joining the remaining arguments _as PowerShell code_, and therefore correctly recognizes arrays.

For cross-platform compatibility (support for use in Unix shebang lines), `pwsh` now defaults to the `-File` parameter, which uses the arguments following the script-file path _verbatim_, and therefore doesn't support arrays.

Use `pwsh -c ...` to get equivalent behavior to `powershell ...`

**Comment by rtestardi** [comment]
Thank you, thank you for the explanation **and** workaround!  That's great for me!

**Comment by mklement0** [comment]
Glad to hear it was helpful, @rtestardi.
