### ISSUE TITLE
'Run With PowerShell 7' Right-Click Context Menu Disappears On Windows 10 Updates?

### ISSUE THREAD

**Issue by jpr89** [PowerShell/PowerShell#14980]
## Steps to reproduce

```powershell
Install powershell 7 core, ask for Right-Click Context Menu

Experience a Windows update

The context menu is gone.
```

## Expected behavior

```none
The context menu shouldn't disappear.
```

## Actual behavior

```none
The context menu disappears.
```

![image](https://user-images.githubusercontent.com/31327577/110485592-d1143680-80b9-11eb-9502-75a92743e241.png)

For some reason this only happens with some Windows Apps? My Radeon settings and Visual Studio code are fine. But everything else got wiped?

**Comment by joeyaiello** [comment]
How are you installing PowerShell? MSI? Store? Global tool?

What version of PowerShell are you using? What version of Windows? Which update specifically were you installing when this happened?

**Comment by hristijan5** [comment]
Any info on why was this issue closed since this is reproducible? It also happened to me on win 11. Enabled right click menu and aftrer PowerShell updates (via the windows update) the right click menu is gone.
