### ISSUE TITLE
Couldn't load the Windows Runtime assemblies in 7.1.2

### ISSUE THREAD

**Issue by farag2** [PowerShell/PowerShell#14991]
## Steps to reproduce
I downloaded `WinRT.Runtime.dll` 1.1.3 from the CsWinRT [page](https://github.com/microsoft/CsWinRT/releases/latest) and `Microsoft.Windows.SDK.NET.dll` from the Microsoft.Windows.SDK.NET.Ref [page](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref) like it was [described](https://github.com/PowerShell/PowerShell/issues/13042#issuecomment-653357546) but cannot figure out why it still doesn't work.

```powershell
Add-Type -AssemblyName "D:\Desktop\WinRT.Runtime.dll"
Add-Type -AssemblyName "D:\Desktop\Microsoft.Windows.SDK.NET.dll"

[Windows.Management.Deployment.PackageManager,Windows.Web,ContentType=WindowsRuntime]::new().FindPackages() | Select-Object -ExpandProperty Id -Property DisplayName | Format-Table -Property Name
```

## Expected behavior

```none
Name
----
1527c705-839a-4832-9118-54d4Bd6a0c89
c5e2524a-ea46-4f67-841f-6a9465d9d515
E2A4F912-2574-4A75-9BB0-0D023378592B
F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE
Microsoft.AAD.BrokerPlugin
Microsoft.AccountsControl
Microsoft.AsyncTextService
Microsoft.BioEnrollment
Microsoft.CredDialogHost
Microsoft.ECApp

and so on...
```

## Actual behavior

```none
InvalidOperation: Unable to find type [Windows.Management.Deployment.PackageManager,Windows.Web, ContentType=WindowsRuntime].
```

## Environment data

Name                                        Value
----                                          -----
PSVersion                                 7.1.2
PSEdition                                  Core
GitCommitId                            7.1.2
OS                                           Microsoft Windows 10.0.19042
Platform                                   Win32NT
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion                   1.1.0.1
WSManStackVersion                 3.0

**Comment by SeeminglyScience** [comment]
They are loaded as normal types, the fully qualified type name syntax requesting content type winrt is no longer supported.  Remove everything after and including the first comma and it should  work.

**Comment by farag2** [comment]
> 
> 
> They are loaded as normal types, the fully qualified type name syntax requesting content type winrt is no longer supported. Remove everything after and including the first comma and it should work.

```
PS C:\Users\test> [Windows.Management.Deployment.PackageManager]::new().FindPackages() | fl *

ThisPtr                    : 1848228481584
ObjRef                     : WinRT.ObjectReference`1[WinRT.IInspectable+Vftbl]
NativeObject               : WinRT.ObjectReference`1[WinRT.IInspectable+Vftbl]
HasUnwrappableNativeObject : True
AdditionalTypeData         : {[System.RuntimeTypeHandle, ABI.System.Collections.IEnumerable+AdaptiveFromAbiHelper]}
```

It still doesnt output what PS 5.1 does. Or what am I doing wrong again?

**Comment by SeeminglyScience** [comment]
> It still doesnt output what PS 5.1 does. Or what am I doing wrong again?

Well look at that...

You're not doing anything wrong, they just seem to have changed up the design quite a bit.  As a work around you can do:

```powershell
$all = [Windows.Management.Deployment.PackageManager]::new().FindPackages()
$all.AdditionalTypeData[[Collections.IEnumerable].TypeHandle]
```

/cc @daxian-dbw for awareness. It seems like they've made non-concrete types a lot more complicated to work with.

**Comment by farag2** [comment]
Wow. It really works! I'm not familiar with PowerShell (as you can mymain repo), but this .NET classes are like a rocket science for me. Thanks a lot!

**Comment by SeeminglyScience** [comment]
> Wow. It really works! I'm not familiar with PowerShell (as you can mymain repo), but this .NET classes are like a rocket science for me. Thanks a lot!

FYI try not to get discouraged from experimenting with .NET because of these, they are particularly complicated since it's all basically native interop. The normal base class library is a lot easier to work with 🙂

**Comment by SeeminglyScience** [comment]
> Wow. It really works! I'm not familiar with PowerShell (as you can mymain repo), but this .NET classes are like a rocket science for me. Thanks a lot!

FYI try not to get discouraged from experimenting with .NET because of these, they are particularly complicated since it's all basically native interop. The normal base class library is a lot easier to work with 🙂

**Comment by farag2** [comment]
LOL. I meant "familiar" with PS. ))
