### ISSUE TITLE
Add ‘Regional and language constraints’ to both parameter and aliases,then psreadline use it.

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#14992]
## Proposed technical implementation details (optional)

eg:
`[Alias("bee",UICulture='en-us')][UICulture='zh-cn'][String]$蜜蜂`

Then psreadline can use it. In other words,
If the user environment is Chinese, after the user presses tab, the Chinese parameters will be automatically completed.
If the user environment is in English. After the user presses tab, the English parameters will be completed.

**Comment by joeyaiello** [comment]
This is actually a really interesting idea, but I'm not necessarily sure how popular this would be in practice.

Are you authoring modules today where you think that this would be useful for your userbase?

**Comment by vexx32** [comment]
This would work best coupled with language-specific function aliases as well, I would think. I like the idea, not sure how much adoption it would get, but it's probably the best bet for localizing PowerShell modules in a neat way.

**Comment by kasini3000** [comment]
Yes, please pay attention to it. I need such a 【parameter-alias local plan】,or another better plan.
Since the release of powershell v7 2020-03, I have used psv7 to make the two largest projects in the world. Although in these two projects, there is still a lot of shit mountain code.


1 kasini3000. https://gitee.com/chuanjiao10/kasini3000
It is mature and claims to be able to replace 【ansible's】 powershell automatic operation and maintenance tool project.

2 k4t. https://gitee.com/chuanjiao10/k4t
Not open source for the time being. Claimed to be a better container automatic operation and maintenance platform than 【kubernetes】. Known as the atomic bomb project in the container world.

**Comment by theJasonHelmick** [comment]
Thank you @kasini3000 for this issue.  The interactive WG has reviewed this issue and agrees with the desire to achieve a higher level of localization.  At this time, as we investigate better localization, we do not want to proceed with this single issue in isolation. We need to take a more holistic approach to localization.
