### ISSUE TITLE
Way to invoke a scriptblock with named parameters from C#

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15004]
## Summary of the new feature/enhancement

Say I have a scriptblock like this:

```powershell
{
    param(
        $a,
        $b
    )

    "a: $a"
    "b: $b"
}
```

And I want to invoke it from C#:

```csharp
var sb = ScriptBlock.Create("...");
var parameters = new Hashtable
{
    { "a", "A" },
    { "b", "B" },
};

sb.Invoke(?);
InvokeCommand.InvokeScript(sb, ?);

using (var pwsh = PowerShell.Create())
{
    pwsh.<?>.AddParameters(parameters).Invoke();
}
```

Is there a way to do this currently in PowerShell, and if not can we have one?

The best way I've found to do this so far is to use reflection to create a `FunctionInfo` object around the scriptblock for invocation:

```csharp
var sb = ScriptBlock.Create("param($a, $b) \"a: $a\",\"b: $b\"");
var runspace = RunspaceFactory.CreateRunspace();
runspace.Open();

PropertyInfo runspaceExecutionContextProperty = typeof(Runspace).GetProperty("ExecutionContext", BindingFlags.Instance | BindingFlags.NonPublic);
Type ecType = runspaceExecutionContextProperty.PropertyType;

ConstructorInfo funcInfoCtor = typeof(FunctionInfo).GetConstructor(
    BindingFlags.NonPublic | BindingFlags.Instance,
    binder: null,
    new[] { typeof(string), typeof(ScriptBlock), ecType },
    modifiers: null);

object executionContext = runspaceExecutionContextProperty.GetValue(runspace);
var sbFuncInfo = (FunctionInfo)funcInfoCtor.Invoke(new object[] { string.Empty, sb, executionContext });

using (var pwsh = PowerShell.Create())
{
    pwsh.AddCommand(sbFuncInfo).AddParameters(new Dictionary<string, object>{ {"a", "A"}, {"b", "B"} });

    foreach (PSObject result in pwsh.Invoke())
    {
        Console.WriteLine(result);
    }
}
```

But this is very involved, messy, requires overhead and isn't public/officially supported.

## Proposed technical implementation details (optional)

Some considerations:

- While the `PowerShell` API is a good place for this, it doesn't currently have good support for scriptblocks (something which could be improved)
- Other APIs do support scriptblocks well, such as `CommandInvocationIntrinsics.InvokeScript` and `ScriptBlock.Invoke[WithContext]` and it would be nice to extend those to enable named parameter passing since they allow simpler control of the execution context than the `PowerShell` API

**Comment by mklement0** [comment]
Let me know if I'm telling you that you already know, but just to clarify:

* The `.AddScript()` method of the `PowerShell` class accepts a _string_ that becomes a _script block_, which, as usual, can declare parameters and/or receive arguments. Note that since the script block's _content_ is being passed, there must _not_ be enclosing `{ ... }`

* While there is currently no support for passing a _dictionary_ of arguments - i.e. no support for _splatting_ via the `PowerShell` class - a chain of `.AddParameter()` calls is akin to that, if more verbose.

A simple example written in PowerShell:

```powershell
# Note the absence of enclosing { ... }
[powershell]::Create().AddScript(
@'
  param(
    $a,
    $b
    )
    
    "a: $a"
    "b: $b"

'@
).
  AddParameter('a', 'A').
  AddParameter('b', 'B').
  Invoke()
```

This yields:

```
a: A
b: B
```

**Comment by SeeminglyScience** [comment]
I've found myself wanting this a lot as well, but every time I go to request it I have a hard time justifying it.  The only real reason you'd want to do this is to invoke a scriptblock in the current runspace while retaining original AST information for debugging.

If you don't need the AST information, you can just `ToString()` it.  If you aren't invoking in the current runspace, then runspace affinity is going to be a bit confusing for a public API.

Side note, `ScriptInfo` is the command info equivalent for an anonymous script. Maybe just a public constructor that pulled execution context from TLS would be enough.  Or from the scriptblock's affinity.

**Comment by rjmholt** [comment]
> While there is currently no support for passing a dictionary of arguments - i.e. no support for splatting via the PowerShell class - a chain of .AddParameter() calls is akin to that, if more verbose.

I believe [`AddParameters()`](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addparameters?view=powershellsdk-7.0.0) does that.

> The only real reason you'd want to do this is to invoke a scriptblock in the current runspace while retaining original AST information for debugging.

My primary reason is not wanting to rebuild a scriptblock. In my scenario, I'm taking in a user-provided scriptblock in a cmdlet and I want to execute it providing a set of parameters to choose from. I'd like that scriptblock to keep all of its context and metadata and not have the overhead of stringifying it just for PowerShell to construct a new one. That way, if something goes wrong in the execution, the error message makes sense to users.

**Comment by mklement0** [comment]
Thanks, @rjmholt, now I understand, and thanks for the `.AddParameters()` hint; TIL.

> I'm taking in a user-provided scriptblock in a cmdlet and I want to execute it providing a set of parameters to choose from. 

Even in the case where a _string_ is passed to `.AddScript()` (potentially incurring the cost of compilation again), as is currently the only option, it would indeed be nice to be able to pass (named) _arguments_ to the script block, in a _repeatable_ manner, so that a compiled-once script block in a cached `PowerShell` instance can be invoked repeatedly, with different arguments each time (this is somewhat related to your proposal #15008).

So a potential API surface I see is:

* Add an `.AddScript(ScriptBlock sb)` overload (don't know if there be dragons).

* Add new `.InvokeWithParameters()` and `.InvokeWithArguments()` methods that supports passing named arguments / positional arguments to the script block in a given invocation.

Currently, the only way to provide _per-invocation_ input is to use the `.Invoke()` overloads that accept objects that act _as pipeline input_ - there's no _argument_ counterpart (only the "baking in" of arguments with `.AddParameter()`, ... that cannot later be replaced).

To illustrate this based on your example:

Instead of the following _emulation_ of the described behavior:

```powershell
$ps = [powershell]::Create()

$sb = { param($a, $b)  "a: $a", "b: $b" }

# As a workaround, wrap the script block in another one that 
# passes pipeline input to the original one via splatting.
$sbWrapped = '$dictArgs=$($input); . {{ {0} }} @dictArgs' -f $sb.ToString()

# Currently invariably stringifies the script block and rebuilds it.
# As a workaround, pass the arguments dictionary via the *pipeline* to
# enable repeated invocations.
$ps.AddScript($sbWrapped).
    Invoke([array] @{ a = 'A'; b = 'B' })  # -> "a: A", "b: B"

# Repeat invocation with different arguments:
$ps.Invoke([array] @{ a = 'C'; b = 'D' })  # -> "a: C", "b: D"
```

we would then be able to simplify to:

```powershell
$ps = [powershell]::Create()

$sb = { param($a, $b)  "a: $a", "b: $b" }

# [scriptblock] instance $sb is now passed as-is
$ps.AddScript($sb).
    InvokeWithParameters(@{ a = 'A'; b = 'B' })

# Repeat invocation with different arguments:
$ps.InvokeWithParameters(@{ a = 'C'; b = 'D' })
```

**Comment by bpayette** [comment]
@rjmholt  `ScriptBlock.Invoke()` doesn't go through the parameter binder which is where named parameter binding is handled.   It would be best/easiest/most consistent to allow you to add a scriptblock using the `PowerShell` API which would look like: 
```powershell
[powershell]::Create().AddScript({param ($x, $y) "x is $x y is $y"}, $true).AddParameter("x", 10).AddParameter("y", 20).Invoke()
```
Note that this actually works today from PowerShell because the ScriptBlock gets turned into a string and then back into a ScriptBlock. Given that the scriptblocks are cached there might not even be much of a performance penalty for the double-conversion.

**Comment by SeeminglyScience** [comment]
> It would be best/easiest/most consistent to allow you to add a scriptblock using the `PowerShell` API which would look like:

I worry that adding a `ScriptBlock` overload would result in a lot of confusion. Supporting `ScriptBlock` directly would imply to me that `SessionState`, extent data, runspace affinity, etc would be honored. In out of process runspaces, this overload would probably just `ToString`, for in-process-but-not-current-thread runspaces, affinity would likely result in dead locks or state corruption.

Also as you mentioned, it's common in PowerShell to rely on argument coercion here.  So if a new overload were added it would most likely need to be the same as `ToString()` to avoid changing behavior of existing scripts (which doesn't solve the use case in the OP).

Personally I'd like to see either:

1. A public constructor on `ScriptInfo`. This is round about enough that you will likely already understand the caveats if you reach for this
2. A static class following a similar pattern as the BCL's `Unsafe` and `MemoryMarshal` classes. This would make it abundantly clear that safety is the consumer's responsibility.  Something like: 

	  ```csharp
	  namespace System.Management.Automation
	  {
	      public static class PSUnsafe // or CommandMarshal
	      {
	          public static ScriptInfo AsScriptInfo(ScriptBlock scriptBlock);
	          public static ScriptInfo AsScriptInfo(ScriptBlock scriptBlock, Runspace affinity);
	      }
	  }
	  ```

**Comment by mklement0** [comment]
Returning to something @rjmholt said in the OP:

> Other APIs do support scriptblocks well, such as `CommandInvocationIntrinsics.InvokeScript` and `ScriptBlock.Invoke[WithContext]`

@rjmholt, wouldn't introducing the following new  `ScriptBlock.InvokeWithContext()` overload address your use case?

```csharp
public Collection<PSObject> InvokeWithContext (
  Dictionary<string, ScriptBlock> functionsToDefine, 
  List<System.Management.Automation.PSVariable> variablesToDefine, 
  IDictionary parameters // analogous to PowerShell.AddParameters()
);
```

That is, it would be the (extended) analog of `PowerShell.AddParameters()`, just like the existing overloads with their `params object[] args` parameter are the analog of multiple `PowerShell.AddArgument()` calls.

Then perhaps there is no need to pass `ScriptBlock` instances as-is to a `PowerShell` instance, which would avoid the headaches that @SeeminglyScience describes.

---

However, _independently_ - for the case where it's fine to pass a _string_ to `PowerShell.AddScript()` and have that build the script block with the proper runspace affinity internally - there is still also an as-yet-unmet need to allow _repeatable_ invocations to such a behind-the-scenes script block with _new parameters_ on every invocation.

Therefore, _also_ introducing `PowerShell.InvokeWithParameters(IDictionary parameters)` and `PowerShell.InvokeWithArguments(params object[] args)` overloads makes sense to me.

**Comment by SeeminglyScience** [comment]
Side note, there is sort of a way to do this without reflection.  This is the pattern I usually end up with:

```csharp
// From cmdlet parameters or similar
ScriptBlock userScript;
IDictionary parameters;

using var pwsh = PowerShell.Create(RunspaceMode.CurrentRunspace);
const string proxyScript = @"
      # I don't remember which of these are actually respected
	  [System.Diagnostics.DebuggerHidden()]
	  [System.Diagnostics.DebuggerStepThrough()]
	  [System.Diagnostics.DebuggerNonUserCode()]
	  param()
	  end {
	      $private:__p = $args[1]
	      & $args[0] @__p
	  }"@;

pwsh.AddScript(proxyScript)
	.AddArgument(userScript)
	.AddArgument(parameters)
	.Invoke();
```

Not always applicable, but useful to have as a possible work around.

**Comment by mklement0** [comment]
Good to know, @SeeminglyScience - still, it seems like it would make sense to have such an overload.

So it looks like we have the following problems and potential solutions:

* Inability to use _named_ arguments with `ScriptBlock.InvokeWithContext()` and `CommandInvocationIntrinsics.InvokeScript()` (only _positional_ ones are currently supported):

  * New overloads with a `IDictionary parameters` parameter could solve that problem.

* Inability to pass a script block _as-is_ to `PowerShell.AddScript()`

  * However, perhaps your [workaround](https://github.com/PowerShell/PowerShell/issues/15004#issuecomment-799622394) (which improves on my wrapper script-block technique by not stringifying the wrapped block but passing it as an _argument_ instead) is sufficient for this particular use case - and its non-obviousness can implicitly serve as a signal that there be dragons.

* Inability to pass _per-invocation_ arguments via `PowerShell.Invoke()` - that currently only works for _pipeline_ input.

  * For instance, two consecutive calls to `ScriptBlock.Invoke()` on a given, reusable script block with different parameters works just fine -  `$sb = { "[$args]" }; $sb.Invoke(1, 2); $sb.Invoke(3, 4)` - but there's no way to do that via `PowerShell.Invoke()`, from what I understand (the`.AddArgument/Parameter(s)()` irrevocably bake the given arguments into the command).

   * Adding `PowerShell.Invoke()` overloads that accept _per-invocation_ arguments via `IDictionary parameters` and `params object[] args` parameters could solve that problem.

**Comment by Keerthi-anusha** [comment]
Hi...
I'm trying to invoke powershell script which was asking input parameters in powershell in c# how can pass input parameters from c#
