### ISSUE TITLE
MSI installer "Enable PowerShell remoting" could use some hints

### ISSUE THREAD

**Issue by MHHenriksen** [PowerShell/PowerShell#15006]
## Summary of the new feature/enhancement

As a user, I want to understand the consequences of enabling remoting when installing PowerShell, so that I know that I am not exposing any potential security holes or attack vectors.

### Context
I just updated to 7.1.3, and had to pause on the page with optional features. The "Enable PowerShell remoting" option stuck out to me, wedged in the middle of all the others almost as an afterthought, and while it sounds like an attractive feature I don't know exactly what it does or changes with my system, and I did not have time to look more into it. 

Here's all the thoughts that ran through my head and ultimately made me decide to not enable it and also not plan to follow it up since it seems like it would consume too much time.

The term "remoting" is a bit overloaded and therefore ambiguous to me. I work with containers and it sounds like remoting could involve ssh and remote shells, which I tried and failed to use from Windows to Linux once long ago in one of the first previews of PS Core. But I also know it could be related to things like DSC and WinRM, or even new stuff I haven't heard about yet.

I also worried if this would set up a listening port to remote into this machine, which I would need to think through if is acceptable on my work laptop and maybe involve my IT department.

And I was skeptical if this could interfere with other "stuff" I already use for remoting.

## Proposed technical implementation details

Together with the checkbox to enable this feature, provide a summary of the concrete consequences of enabling it. There's more than one way this could be done:

Most straightforward: Just add text slightly indented and styled below the option.

I expect there could be quite a bit to cover, and that all that text wouldn't fit directly on the page it currently lives in, even as just concise keywords. Maybe an (i) icon with a tooltip would work. And a link to the doc page for the feature would also be useful, to remove the friction of having to search for it. Not in the tooltip though, that would be tricky to click ;)

I want to ask you to consider going one step further though, and move this particular option to its own page, so that there's room to write and explain without having to sidestep into a browser. This should be weighed by someone with more knowledge of the actual feature, because it definitely depends on how impactful enabling remoting actually is, especially about security vulnerabilities. If it's totally safe, a separate page might give the wrong impression and also possibly promote it more than it should be. But if there are indeed such implications or other important considerations, this would be a great way to highlight and warn about it.

**Comment by joeyaiello** [comment]
I think it would be reasonable for us to add a hyperlink there to our [remoting docs](https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/running-remote-commands?view=powershell-7.1). Would that be helpful to you?

**Comment by MHHenriksen** [comment]
Yep! That will do.
