### ISSUE TITLE
7.1.3 global tool is not on NuGet

### ISSUE THREAD

**Issue by adamralph** [PowerShell/PowerShell#15011]
7.1.3 was released on 11th March 2021, but the latest version on NuGet is still 7.1.2

![image](https://user-images.githubusercontent.com/677704/111026435-87458c00-83ea-11eb-9857-db22ddbcdd76.png)

**Comment by mikenunan** [comment]
Somehow it's made it onto Chocolatey but still not NuGet, which is a pain for those of us who like to use it as a dotnet global tool - presumably this is a one-click fix for somebody with suitable project privileges?

**Comment by pedrolamas** [comment]
I have noticed before that when there is a new release of PowerShell, it takes a couple of days to appear on NuGet, but this time it sure is taking a bit longer than usually....

I do wonder if there is a specific reason for this type of delay in releasing on NuGet...

**Comment by kapsiR** [comment]
Maybe @adityapatwardhan can help out here? 😉

**Comment by adityapatwardhan** [comment]
Let me check.

**Comment by adityapatwardhan** [comment]
Just released 7.1.3 and 7.0.6 to NuGet. It will be available shortly.

**Comment by adityapatwardhan** [comment]
Both versions are available now. Thank you for your patience.

**Comment by mikenunan** [comment]
Thanks very much for that @adityapatwardhan - for the next time is this something that could be automated in the build pipeline?

**Comment by adityapatwardhan** [comment]
It is automated but there was a bug which caused the upload to not happen. It has been fixed and for the next release, it should be available with on the same day.

**Comment by mikenunan** [comment]
Awesome, thanks for attending to that 👍🏻
