### ISSUE TITLE
`Remove-Item -Recurse` against folders should use a .NET method on Windows instead of recursive list-and-delete

### ISSUE THREAD

**Issue by Sidneys1** [PowerShell/PowerShell#15028]
# Problem

Possibly a non-issue, but this became apparent when trying to excise a poorly-name directory on Windows (`'..`). The folder was non-empty, and could not be entered with PowerShell, CMD, or Explorer to empty.

```ps1
$files = Get-ChildItem;
$dir = $files[0]; # This is the badly-named directory

Remove-Item -Recursive -Force $dir; # Fails
# I assume because it tries to walk the contents and remove them individually,
# but the oddly-named directory "'.." cannot have its contents enumerated

$dir.Delete($true); # Succeeds, is System.IO.DirectoryInfo.Delete(bool recurse)
```

# Solution

It would possibly speed up and increase the resilience of `Remove-Item -Recursive` operations against filesystem providers if PowerShell shortcutted directory removals to call the .NET `System.IO.DirectoryInfo.Delete(bool recurse)` method instead of recursively listing-and-deleting contents.

# Testing

For testing purposes, the folder `'..` was generated in an Angular project with the typo'd command `ng generate component "'..\foo"`.

**Comment by jborean93** [comment]
AFAIK `Delete(true)` does the same thing, it calls `Dir.EnumerateFileSystemEntries` and it itself will traverse down and delete the files before it deletes the actual parent dir The difference is that PowerShell adds a few more checks in there to handle things like like OneDrive reparse points, or broken symlinks, that I believe .NET struggled with in the past. Maybe that's no longer an issue and it could be simplified as you are suggesting. Even if it can't be simplified and there is another reason for PowerShell to enumerate and delete the contents itself then the fact that `$dir.Delete($true)` works means there's a bug in the logic here which should be fixed.
