### ISSUE TITLE
wrong symlink in CentOS8 Powershell 7.1.3 package

### ISSUE THREAD

**Issue by c-0815** [PowerShell/PowerShell#15029]
**Environment:**

 CentOS 8 Powershell 7.1.3
powershell installed by Microsoft repo

**Scenario**

  * ldd for libmi.so shows:

ldd /opt/microsoft/powershell/7/libmi.so
ldd: warning: you do not have execution permission for `/opt/microsoft/powershell/7/libmi.so'
linux-vdso.so.1 (0x00007ffc3ea41000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff105ed7000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007ff105cd3000)
libpam.so.0 => /lib64/libpam.so.0 (0x00007ff105ac3000)
libssl.so.1.0.0 => /opt/microsoft/powershell/7/libssl.so.1.0.0 (0x00007ff10582f000)

**libcrypto.so.1.0.0 => not found**

libc.so.6 => /lib64/libc.so.6 (0x00007ff10546c000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff1060f7000)
libaudit.so.1 => /lib64/libaudit.so.1 (0x00007ff105242000)
libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007ff104d5c000)
libz.so.1 => /lib64/libz.so.1 (0x00007ff104b45000)
libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007ff10493f000)

  * following the missing reference
ls -l libcrypto.so.1.0.0
lrwxrwxrwx  1 root root       25 Mar 10 02:14 libcrypto.so.1.0.0 -> /lib64/libcrypto.so.1.1.1

but /lib64/libcrypto.so.1.1.1 is not found on a CentOS 8 system

**Resolution**
cd /lib64
ln -s libcrypto.so.1.1 libcrypto.so.1.1.1

**Solution**
The link must reference to /lib64/libcrypto.so.1.1

Please fix this in the rpm Package.

regards

Ralph

**Comment by jborean93** [comment]
You cannot just change the link for OpenSSL 1.0.x to point to the 1.1.x libraries. While it will get libmi to load you will be unable to use any TLS features due to the API and ABI difference on OpenSSL 1.0.x and the 1.1.x versions. This is the reason why the symlink is pointing to 1.0.x still.

**Comment by c-0815** [comment]
Hi Jordan,

please look at the output of the ls command. In the current 7.1.3 package libcrypto.1.0.0 is **already linked to** libcrypto.so.1.1.1. But version 1.1.1 is not found in /lib64 directory. 
In /lib64 you find:
  * libcrypto.so.1.1  - that links to libcrypto.so.1.1.1g
 * libcrypto.so.1.1.1g -  the original library

uncorrected I get following error:
```
#>$session = New-PSSession -ComputerName server-05 -Credential $cred -Authentication Negotiate

New-PSSession: This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system.
```
After I corrected the link the WSMAN communication works fine.

best regards

Ralph

**Comment by jborean93** [comment]
So the symlink is pointing to an invalid location and adjusting it to the OpenSSL 1.1.x location gets the library to load. But the issue here is that libmi is compiled against OpenSSL 1.0.x not 1.1.x. These versions are not API and ABI compatible so even if you point the link to the a valid location on your host you will run across issues when it first tries to use something in that library. In your example it’s running over HTTP which doesn’t use OpenSSL, as soon as you target a https endpoint it will fail, maybe even segfault the entire process.

In reality the symlinks shouldn’t be pointing to OpenSSL 1.1.x in this package but rather where the OpenSSL 1.0.x ones. This is complicated by the fact that this OpenSSL version may not be available on more modern distros so you have to compile it yourself.

**Comment by c-0815** [comment]
I understand. But why libmi isn't compiled against OpenSSL 1.1.x in the CentOS8 rpm package?

**Comment by c-0815** [comment]
I've seen PSWSMan 2.1.0 Package in the Powershell Gallery. Is the OpenSSL Bug fixed, if I install this nuget Package, an exchange the libs. I checked the libmi.so and it is correctly linked against OpenSSL 1.1

**Comment by jborean93** [comment]
> But why libmi isn't compiled against OpenSSL 1.1.x in the CentOS8 rpm package?

Another team in Microsoft maintain the package and they no longer support PowerShell's use case so PowerShell is stuck with what was given to them at the time. Technically they could build it themselves and include it in the distribution but so far they haven’t gone that route.

> I've seen PSWSMan 2.1.0 Package in the Powershell Gallery

Thats a fork of the libmi package that has been recompiled against OpenSSL 1.1.x on more modern systems. I’m actually the maintainer of that but there is no connection between myself and Microsoft so it isn’t supported here. I do recommend you use it because it fixes more problems than just OpenSSL, you can find more about it here https://github.com/jborean93/omi.

**Comment by joeyaiello** [comment]
Thanks for providing all that context, @jborean93, and for your work on maintaining that fork of OMI. It's still not something we're feel comfortable taking into our package (largely due to lack of time on our side to review all of your changes), but I'm really glad it's out there for the folks that need it.

Given the symlink to an appropriately installed OpenSSL 1.0.x package, I'm going to close this one.

**Comment by jborean93** [comment]
> It's still not something we're feel comfortable taking into our package 

Totally understandable, I had trouble myself trying to understand the existing codebase due to how complex it all is :) Looking forward to the pluggable transports slated for 7.2 which will hopefully make this even easier to distribute and install.

**Comment by jborean93** [comment]
@joeyaiello i think there is still an issue with the package here. The symlinks are pointing to the 1.1.x locations and even one of them does not exist. In reality they should either:

* Point to the expected 1.0.x locations
* Point to the correct 1.1.x locations

The first is what strictly should happen but it means OpenSSL 1.0.x must be installed for libmi to load at all. The latter will work for the http situation but will fail if a https endpoint is used, I.e. Exchange Online.

**Comment by joeyaiello** [comment]
Thanks for the clarification. I was reading it as "we're linking to 1.0 and I have 1.1, and so 1.0 doesn't exist", but it looks like we're in a strange mixed state. 

I think we should do the first of the two options you're presenting as HTTP endpoints probably shouldn't be used (and I think in the HTTPS we're very ungraceful in our error).

**Comment by jborean93** [comment]
Hmm I might be wrong here, I just installed PowerShell from the Microsoft repo and it has the symlinks pointing to 1.0.x

```bash
[root@5ebb04b287e1 /]# ls -al /opt/microsoft/powershell/7/lib*
-rw-r--r--. 1 root root 3671090 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.IO.Compression.Native.a
-rw-r--r--. 1 root root  907640 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.IO.Compression.Native.so
-rw-r--r--. 1 root root   18568 Oct 19 18:19 /opt/microsoft/powershell/7/libSystem.IO.Ports.Native.so
-rw-r--r--. 1 root root  425486 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.Native.a
-rw-r--r--. 1 root root   75960 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.Native.so
-rw-r--r--. 1 root root   36752 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.Net.Security.Native.a
-rw-r--r--. 1 root root   14536 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.Net.Security.Native.so
-rw-r--r--. 1 root root  997210 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.Security.Cryptography.Native.OpenSsl.a
-rw-r--r--. 1 root root  129224 Feb 16 21:55 /opt/microsoft/powershell/7/libSystem.Security.Cryptography.Native.OpenSsl.so
-rw-r--r--. 1 root root 3175376 Feb 16 21:54 /opt/microsoft/powershell/7/libclrjit.so
-rw-r--r--. 1 root root 7109080 Feb 16 21:53 /opt/microsoft/powershell/7/libcoreclr.so
-rw-r--r--. 1 root root  628520 Feb 16 21:46 /opt/microsoft/powershell/7/libcoreclrtraceptprovider.so
lrwxrwxrwx. 1 root root      22 Mar 10 01:13 /opt/microsoft/powershell/7/libcrypto.so.1.0.0 -> /lib64/libcrypto.so.10
-rw-r--r--. 1 root root  635568 Feb 16 21:51 /opt/microsoft/powershell/7/libdbgshim.so
-rw-r--r--. 1 root root  403872 Feb 16 22:19 /opt/microsoft/powershell/7/libhostfxr.so
-rw-r--r--. 1 root root  371112 Feb 16 22:19 /opt/microsoft/powershell/7/libhostpolicy.so
-rw-r--r--. 1 root root  730728 Jul 23  2018 /opt/microsoft/powershell/7/libmi.so
-rw-r--r--. 1 root root 2576624 Feb 16 21:53 /opt/microsoft/powershell/7/libmscordaccore.so
-rw-r--r--. 1 root root 1840448 Feb 16 21:54 /opt/microsoft/powershell/7/libmscordbi.so
-rw-r--r--. 1 root root   30312 Nov  2 23:15 /opt/microsoft/powershell/7/libpsl-native.so
-rw-r--r--. 1 root root  843744 Jul 23  2018 /opt/microsoft/powershell/7/libpsrpclient.so
lrwxrwxrwx. 1 root root      19 Mar 10 01:13 /opt/microsoft/powershell/7/libssl.so.1.0.0 -> /lib64/libssl.so.10
```

I'm not sure why OP's setup is pointing to the 1.1.x paths but based on this evidence it looks like the PowerShell package is correct.

**Comment by c-0815** [comment]
Is this CentOS8?

**Comment by jborean93** [comment]
Oh I'm really sorry I must have added the repo for rhel/7 so it was installing the EL7 rpm hence why the links were still pointing to 1.0. Please ignore that post and my comments in https://github.com/PowerShell/PowerShell/issues/15029#issuecomment-800690344 still stand.

**Comment by c-0815** [comment]
But than the powershell devs should change die linking behavior I showed at my last post for CentOS8

**Comment by jborean93** [comment]
Yep so that’s the 2nd option I mentioned. I don’t think it’s the right move though as it brings the whole PowerShell process down as soon as you target HTTPS endpoints. The symlinks should still be pointing to the OpenSSL 1.0.x libraries like it does on CentOS 7 and the docs updated to indicate `compat-openssl10` is required for WSMan.

**Comment by mmcnutt** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1879707

Fedora is not packaging compat-openssl10 in Fedora 34. At the moment installing to Fedora 34 leaves WSMan broken

**Comment by megamorf** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1879707
> 
> Fedora is not packaging compat-openssl10 in Fedora 34. At the moment installing to Fedora 34 leaves WSMan broken
> 
> > <img alt="" width="48" src="extensions/RedHat/web/css/favicons/production.ico?v=0">**[1879707 – FTBFS: Remove compat-openssl10 requirement](https://bugzilla.redhat.com/show_bug.cgi?id=1879707)**

I'm also affected by this issue - pwsh as snap on Fedora 34:

```plaintext
➜  pwsh                       
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

No usable version of libssl was found
[1]    14902 IOT instruction (core dumped)  pwsh
```

## snap info

```plaintext
➜  snap list powershell 
Name        Version  Rev  Tracking       Publisher              Notes
powershell  7.1.3    160  latest/stable  microsoft-powershell✓  classic
➜  snap info powershell 
name:      powershell
summary:   PowerShell for every system!
publisher: Microsoft PowerShell✓
store-url: https://snapcraft.io/powershell
contact:   https://github.com/powershell/powershell
license:   unset
description: |
  PowerShell is an automation and configuration management platform.
  It consists of a cross-platform (Windows, Linux, and macOS)
  command-line shell and associated scripting language.
  
  See https://docs.microsoft.com/powershell/scripting/powershell-support-lifecycle for support
  details.
commands:
  - powershell
snap-id:      JSNnoJl3EqkMuWoy5Dgq8PMqZ0uNcpie
tracking:     latest/stable
refresh-date: 2021-04-04
channels:
  latest/stable:    7.1.3 2021-03-12 (160) 68MB classic
  latest/candidate: 7.1.3 2021-03-12 (160) 68MB classic
  latest/beta:      7.1.3 2021-03-12 (160) 68MB classic
  latest/edge:      7.1.3 2021-03-12 (160) 68MB classic
  lts/stable:       7.0.6 2021-03-12 (161) 60MB classic
  lts/candidate:    7.0.6 2021-03-12 (161) 60MB classic
  lts/beta:         7.0.6 2021-03-12 (161) 60MB classic
  lts/edge:         7.0.6 2021-03-12 (161) 60MB classic
installed:          7.1.3            (160) 68MB classic
```
