### ISSUE TITLE
Powershell version-agnostic cmdlets

### ISSUE THREAD

**Issue by Dennis-Petrov** [PowerShell/PowerShell#15027]
## Summary of the new feature/enhancement

We have a small cmdlet, which is mostly independent from Powershell features, so technically it can run using PS from 6.x to 7.x.
In fact, PS just loads it and parses arguments to run cmdlet commands.

This cmdlet depends on `System.Management.Automation` package, which, in turn. differs from PS version to PS version.
Cmdlet is a part of large product,. Its lifecycle contains package update procedure, and ultimately we have V1, where cmdlet depends on `S.M.A` v 6, then V2, where cmdlet depends on `S.M.A` v 7, and so on.

This means, that when end-user updates our product, he must update PS as well, otherwise attempt to run cmdlet will end with this error:
```
Could not load file or assembly 'System.Management.Automation, Version=7.1.2.0, Culture=neutral,
     | PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
I understand *why* this happens.  
I don't understand, *how to* ignore this error and use `S.M.A` which already has been loaded by PS.

## Proposed technical implementation details (optional)

Let cmdlets use already loaded ``System.Management.Automation`` version.  Probably, this should be turned on via `Import-Module` flag.

**Comment by iSazonov** [comment]
Please read the blog post https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/ to select right reference package.

**Comment by Dennis-Petrov** [comment]
Thanks. As far as I understand, we must not refer `System.Management.Automation`.
Will read more attentively, closing for now.

**Comment by jborean93** [comment]
You can definitely refer to `S.M.A`, you are just mean to use the PowerShellStandard.Library as referenced by that blog post.

**Comment by Dennis-Petrov** [comment]
@jborean93 , I meant nuget package, not an assembly itself. Changing `PackageReference` for project from `System.Management.Automation` to `PowerShellStandard.Library` solves the task.
