### ISSUE TITLE
Powershell 7 is unable to use virtualmachinemanager cmdlets

### ISSUE THREAD

**Issue by Immakon** [PowerShell/PowerShell#15026]
On Server 2019 I'm unable to use the virtualmachinemanager module with PowerShell 7.

> Name                           Value
> ----                           -----
> PSVersion                      7.1.2
> PSEdition                      Core
> GitCommitId                    7.1.2
> OS                             Microsoft Windows 10.0.17763
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0

Result trying to get the VM's:
`Get-SCVirtualMachine
Get-SCVirtualMachine: The type initializer for 'Microsoft.VirtualManager.Utils.TraceProviders.ImageLibrary' threw an exception.`

Exception details:

> $error[0].exception
> 
> TypeName       : Microsoft.VirtualManager.Utils.TraceProviders.ImageLibrary
> TargetSite     : System.Management.Automation.Cmdlet lambda_method107(System.Runtime.CompilerServices.Closure)
> StackTrace     :    at lambda_method107(Closure )
>                     at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
> Message        : The type initializer for 'Microsoft.VirtualManager.Utils.TraceProviders.ImageLibrary' threw an excepti
>                  on.
> Data           : {}
> InnerException : System.TypeLoadException: Could not load type 'System.Diagnostics.Eventing.EventProvider' from assembl
>                  y 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
>                     at Microsoft.VirtualManager.Trace.TraceProvider..ctor(ComponentCode component, Boolean etwEnabled)
>                     at Microsoft.VirtualManager.Trace.TraceProvider..ctor(ComponentCode component)
>                     at Microsoft.VirtualManager.Utils.TraceProviders.ImageLibrary..cctor()
> HelpLink       :
> Source         : Anonymously Hosted DynamicMethods Assembly
> HResult        : -2146233036

Using the virtualmachinemanger cmdlets on PS 5.1 does work.

**Comment by iSazonov** [comment]
Please report in https://github.com/PowerShell/PowerShellModuleCoverage
