### ISSUE TITLE
Start-Process: Provide the ability to append when redirecting stdout/stderr streams to file

### ISSUE THREAD

**Issue by csurf** [PowerShell/PowerShell#15031]
Include an option/directive for the 'Start-Process' cmdlet that allows the user to specify that stream output should be *appended to an existing output file when redirecting the stdout/stderr streams to file.

Currently, when using either the '-RedirectStandardOutput' or '-RedirectStandardError' parameters to specify output file paths for redirection of the standard streams to file, the behavior of 'Start-Process' is to create/overwrite if a specified file exists. There is no means to have the output appended to an existing file. This forces the user to come up with additional and, IMHO, seemingly unnecessary work-arounds in order to implement the append logic. This seems like something that could be relatively easily implemented at a lower level, and, quite frankly, seems like basic functionality that the cmdlet should already support.

This could be as simple as adding some kind of append specifier to each parameter:
```
# stdout files gets overwritten (default behavior), stderr file gets appended to ('>>' specifier)
Start-Process -RedirectStandardOutput='logfile.txt' -RedirectStandardError='>>errlog.txt'
```
Of course, this could be setup in a variety of ways and/or as the powershell devs see fit.

Justification:
There are a variety of cases where it would be useful to be able to have a complete output history of a child process' output, even when the same child process is created multiple times, or across multiple executions of the parent script/command. Having the ability to append output files directly from 'Start-Process' would increase its usefulness in this respect.

**Comment by iSazonov** [comment]
PowerShell utilizes Process class which has not such feature. You could discuss this in .Net runtime repository to enhance the class.

**Comment by jborean93** [comment]
This is definitely something that is implemented in PowerShell. .NET gives you the ability to redirect stdout/stderr and exposes that redirection through a [StreamReader](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-5.0#System_Diagnostics_Process_StandardOutput). To achieve this functionality we would have to change how the FileStream is opened here https://github.com/PowerShell/PowerShell/blob/4c40ab11401ff2ca19ee1206b7654ed299f373e6/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L2263.

All that needs to be done to implement this functionality is to either change the mode to `FileMode.Append` or set to `FileMode.Open` and seek the FileStream to the end.

**Comment by iSazonov** [comment]
@jborean93 You referenced temporary code for Unix. PowerShell does many workarounds which is now in .Net and could be removed. 
I'd say the redirection is OS feature and .Net utilizes this.

**Comment by mklement0** [comment]
It looks like as if, to the _caller_, [`System.Diagnostics.Process.StandardOutput`](https://docs.microsoft.com/en-US/dotnet/api/System.Diagnostics.Process.StandardOutput) and `StandardError` are simply _read-only_ properties through which automatically created `Stream` instances reflecting the redirected output  (that on Unix these streams are apparently backed by a _file_ looks like an implementation detail that isn't visible to the caller); alternatively, the output can be read via events.

To put it differently: sending that captured output to a user-chosen _file_  must already be functionality overlaid by PowerShell, so offering an opt-in way to _append_ to such a file should be possible.

---

As for how pressing the need for this feature is (I'm not saying it wouldn't be useful):

Note that there's generally little reason to combine [`Start-Process`](https://docs.microsoft.com/powershell/module/microsoft.powershell.management/start-process) with _console_ applications (terminal applications that use stdout and stderr).

* For synchronous invocation, invoke such applications directly, in which case  you can use `>>`

```powershell
someutil >> out.log 2>> err.log
```

* For asynchronous invocation, you can use a background job, which also allows you to use `>>` - 

```powershell
$job = someutil >> out.log 2>> err.log & 
```

As an aside: Unfortunately, the job-info object currently doesn't reflect `$LASTEXITCODE` after termination - see  #5422


Unnecessary - and often limiting - use of `Start-Process` is a common problem; I've added for guidance to be added to the documentation https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6239, which has further details.

**Comment by iSazonov** [comment]
I don't like an cryptic things in PowerShell language - it is hard for users to discover them. It is more preferable to have an additional switch or two self described name(s) like -AppendToOutput/-AppendToError.

**Comment by jborean93** [comment]
Or maybe even a mode like `-RedirectOutputMode Create/Append` (same for Error). This could have the benefit of adding `Store/Var` support where `-RedirectStandardOutput` is the name of a variable to redirect the value to.

**Comment by mklement0** [comment]
Targeting variables could be achieved via paths that use namespace variable notation, such as `-RedirectStandardOutput variable:out`, which has been suggested before in #5184; the same idea had come up earlier in the context of `>`: #4332, which would make for a nice generalization.

That leaves the aspect of how to ask for _appending_, and in the case at hand `-Append` would then be enough.

Note that you may also want to append to _variables_ (add to an existing collection stored there), which we already support in the context of common parameters such as `-OutVariable` - and there we _do_ already have the kind of non-obvious "mini-DSL" that @iSazonov  is trying to avoid: prefixing the variable name with `+` requests append functionality:

```powershell
$null = Get-Date -ov out
$null = Get-Date 1970-01-01 -ov +out  # appends to existing $out variable
$out # outputs both dates
```

In the case of something like `2>variable:errs`, where adding parameters isn't an option, we'd have no other choice than to use a similar approach: `2>+variable:errs`

**Comment by iSazonov** [comment]
> Or maybe even a mode like `-RedirectOutputMode Create/Append` (same for Error). This could have the benefit of adding `Store/Var` support where `-RedirectStandardOutput` is the name of a variable to redirect the value to.

The mode would be useful if we knew there would be more modes. 

As for output to variables, since we already have this with OutVariable parameter in some cmdlets we should follow this here too for consistency.

**Comment by mklement0** [comment]
>  we already have this with `OutVariable` parameter in some cmdlets

The [common `-OutVariable` parameter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_CommonParameters#outvariable) as well as `-ErrorVariable`, as a common parameters, are present on _all_ cmdlets and designed to display uniform behavior across all cmdlets.

They are implemented in the engine itself, and we cannot overlay that with cmdlet-specific functionality.

As in all cmdlets, these parameters capture what the cmdlet _itself_ outputs to _PowerShell_'s success / error streams, which in the case of `Start-Process` does not apply to  the _native_ output streams (stdout, stderr) of the external process being launched, because - of necessity, given the asynchronous-by-default `Start-Process` behavior - these native streams aren't mapped onto their PowerShell equivalents, unlike in _direct_ invocation. This lack of stream integration is the primary reason not to use `Start-Process` with console applications.

These two common parameters therefore aren't terribly useful with `Start-Process`, but they do work as advertised:

* `-OutVariable out` captures whatever `Start-Process` itself emits to the pipeline in variable `$foo`, which only applies when `-PassThru` is also specified in order to pass out the process-info object describing the newly launched process.

* `ErrorVariable err` captures the errors that `Start-Process` itself emits in variable `$err`, which is in effect limited to the inability to even _create_ the process (e.g., `Start-Process nosuch -ErrorVariable err`) - though I've just realized that appears to be broken on Unix-like platforms.
