### ISSUE TITLE
xml better with Validate-Xml / Generate-Xsd / Transform-Xml (2)

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15033]
hi Guys !!

with powershell and .NET we can validate xml  with xsd /dtd and transform xml with xslt but its lot of typing its better if we simplify this process with cmdlet like 

Validate-Xml -Shema (enum DTD|XSD) -Path (Xml File) -XsdFile (Xsd file) -Passthru
Validate-Xml -Shema (enum DTD|XSD) -Content (Xml String) -XsdContent (Xsd|DTD content)
 -Passthru
Generate-XSD -Path (Xml file) -OutputPath (file)
Generate-XSD -Content (Xml Content) -OutputPath (file)
 
Transform-Xml -Path (xml file) -PathXslt (xslt file) -OutputPath (file) -version (version xslt)
Transform-Xml -Content (xml content) -XsltContent (xslt content) -OutputPath (file) -version (version xslt)

**Comment by vexx32** [comment]
This feels like the kind of thing that would probably be well suited to a standalone module. At some point it would be cool to have that module as part of the standard set for pwsh, but it seems like it'd be pretty useful to have as a standalone module as well.

**Comment by joeyaiello** [comment]
We're currently recommending that any new cmdlet functionality be started and validated by shipping on the PS Gallery before proposing whether or not it should be included in the official PowerShell package. If there is immense need for a `Validate-XML` cmdlet after it's been delivered on the Gallery, we can have the conversation at that point.
