### ISSUE TITLE
Invoke-WebRequest: Cannot convert 'System.String[]' to the type 'System.Uri'

### ISSUE THREAD

**Issue by robinmalik** [PowerShell/PowerShell#15039]
When querying the Office 365 Management API with PowerShell Core (7.1.3), it fails to correctly parse/process certain hyperlinks. PowerShell 5.1 works.

I believe this is due to the presence of `$` in the URL.

A quick in-line fix for my script to work under PS v7 is simply `$URL = ($URL -replace "\$","``$")`

## Steps to reproduce

```
$headerParams = @{'Authorization'="Bearer TOKENVALUE"}
$URL = "https://manage.office.com/api/v1.0/TENANCYGUID/activity/feed/subscriptions/content?contenttype=Audit.General&endtime=2021-03-16T13:21:48.1859513Z&starttime=2021-03-15T13:21:48.1859513Z&nextpage=20210315183117827000466$20210315132148185000000$emea0010"
Invoke-WebRequest -Method Get -Headers $headerParams -Uri $URL
```

## Expected behavior

```
It works.
```

## Actual behavior

```
Cannot convert 'System.String[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not supported.
```

## Environment data

```
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This is expected. `$emea0010` is a valid variable name, and in a double-quoted string PowerShell will attempt to interpolate its value. If the variable doesn't exist, it will be replaced by an empty string (effectively removing the variable name from the string).

The most straightforward solution is to use single quotes when defining the URL, this disables the interpolation and tells PowerShell to treat the string as literal:

```powershell
$headerParams = @{ Authorization = "Bearer TOKENVALUE" }
$URL = 'https://manage.office.com/api/v1.0/TENANCYGUID/activity/feed/subscriptions/content?contenttype=Audit.General&endtime=2021-03-16T13:21:48.1859513Z&starttime=2021-03-15T13:21:48.1859513Z&nextpage=20210315183117827000466$20210315132148185000000$emea0010'
Invoke-WebRequest -Method Get -Headers $headerParams -Uri $URL
``

As you mentioned, you can also escape the `$` with a backtick to indicate that symbol is literal and does not constitute the start of a variable name.

**Comment by robinmalik** [comment]
@vexx32 Hi Joel, thanks for the reply. In providing example code to replicate I expanded the URL (at which point it becomes obvious why that'd happen - doh!). Actually, `$URL` isn't within single/double quotes but direct to variable from an object property. The complete code would be:

```
$AggregateListArray = [System.Collections.ArrayList]@()
$URL = "https://manage.office.com/api/v1.0/$tenantGuid/activity/feed/subscriptions/content?contentType=Audit.General&PublisherIdentifier=$Publisher"
$Count = 1
do {
	Write-Verbose -Message "Request $Count"
	$Data = Invoke-WebRequest -Method Get -Headers $headerParams -Uri $URL
	$Aggregates = $Data.content | convertfrom-json
	foreach($Aggregate in $Aggregates)
	{
		$AggregateListArray.Add($Aggregate) | out-null
	}	
	$Count++
	$URL = $Data.Headers.NextPageUri
}
until($Null -eq $URL)
```

**Comment by iSazonov** [comment]
The conversion `[uri]$uri` works well for URI from your repro steps. Are you sure you create the URI correctly? I mean perhaps the issue is not in Invoke-WebRequest but in script code which creates the URI.

**Comment by robinmalik** [comment]
I think I've discovered the cause and it wasn't what I originally thought. The issue is header data. Using `$Data` when it first becomes populated: `($Data.Headers.NextPageUri).gettype()`

PowerShell 7:
```

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String[]                                 System.Array
```

PowerShell 5:
```
IsPublic IsSerial Name                                     BaseType                                                                                                                                                                                                
-------- -------- ----                                     --------                                                                                                                                                                                                
True     True     String                                   System.Object                                                                                                                                                                                           
```

Apologies for the initial mislead. I suspect this is expected/known behaviour with all the changes to the web cmdlets in PS7.

**Comment by joeyaiello** [comment]
@robinmalik it's unclear to me if you've fixed your problem. Do you still see a bug here?

**Comment by robinmalik** [comment]
@joeyaiello Hi Joey. Sorry for that. The problem is worked around but I wouldn't expect a singular string in the headers (in this case, NextPageUri) to become an array object. I don't know what has changed as part of the web cmdlets in PS7, only that I recall seeing many mentions of such in the release notes. Is there anything I can do to help?
