### ISSUE TITLE
PowerShell SDK 7.1.3 memory issues

### ISSUE THREAD

**Issue by MikeYeager** [PowerShell/PowerShell#15043]
I have a small .NET 5 application that runs on Windows, macOS and Linux (Ubuntu 18.04 and 20.04). 

## Steps to reproduce

```powershell
                    using (var psCommands = PowerShell.Create())
                    {
                        psCommands.AddCommand("Get-Printer");

                        var printers = psCommands.Invoke();

                        if (psCommands.HadErrors)
                        {
                            foreach (var error in psCommands.Streams.Error)
                                _names.Add(error.ErrorDetails.Message);

                            return _names;
                        }

                        foreach (var printer in printers)
                            _names.Add(printer.Members["Name"].Value.ToString());
                    }
```

## Expected behavior
I expect memory use to go up the first time I run this. Then maybe a little more on the next couple of runs and then level off. Perhaps eventually fall again.

## Actual behavior
Memory goes from 72MB before running this code to 158MB after. On the second run, it goes up to 169MB, on the third run, 180MB. Next run, 194MB, then 213MB, then 233MB, then 252MB, 271MB, 290MB, etc... Here's a diff of the memory snapshot between the first run and after several runs. 
![image](https://user-images.githubusercontent.com/7063813/111339314-48f3db00-863d-11eb-9f9f-515e5b7b087e.png)

**Comment by adityapatwardhan** [comment]
Is a similar memory behavior observed if the repro is run as a script on console instead of the SDK? Equivalent script would be something like:

```powershell
$names = [System.Collections.ArrayList]::new()
Get-Printer | ForEach-Object { $null = $names.Add($_.Name) }
```

**Comment by adityapatwardhan** [comment]
Also does the issue repro only for that cmdlet, or with some that come with PowerShell like `Get-Date` or `Get-Process`

**Comment by daxian-dbw** [comment]
@MikeYeager Can you please collect some traces with [PerfView](https://github.com/microsoft/perfview/releases/tag/P2.0.69) and share with us so we can take a look?
Below are the easy steps:
1. download [PerfView](https://github.com/microsoft/perfview/releases/tag/P2.0.69)
2. run you scenario
3. run `perfview /GCCollectOnly /AcceptEULA /nogui /MaxCollectSec:300 /Zip collect`
4. share the generated *.etl.zip file.
