### ISSUE TITLE
Progress rendering is mangled in non-VT terminals

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15047]
## Steps to reproduce

```powershell
Expand-Archive ./big.zip
```

## Expected behavior

Writes a standard progress bar.

## Actual behavior

![image](https://user-images.githubusercontent.com/7009879/111382031-b155b300-8663-11eb-8cba-13d5b63ac3d6.png)

## Environment data

![image](https://user-images.githubusercontent.com/7009879/111382158-da764380-8663-11eb-8b31-9a1c1ee72d2a.png)

**Comment by SteveL-MSFT** [comment]
On systems that don't support VT, should fallback to legacy rendering

**Comment by adityapatwardhan** [comment]
Also happens on Windows 8.1. Same reason, VT is not supported.
