### ISSUE TITLE
PowerShell SDK 7.2.0-preview.3 appears to be broken.

### ISSUE THREAD

**Issue by MikeYeager** [PowerShell/PowerShell#15042]
I have a small .NET 5 app using 7.1.3 that runs on Windows, macOS and Linux. Upgrading to 7.2.0-preview.3 breaks everything. The Microsoft.Management namespace doesn't even exist. 7.2.0-preview.2 works. Attempting to look at the preview.3 package with FuGet package manager from the Nuget.org web page results in an error.

**Comment by adityapatwardhan** [comment]
@MikeYeager Version `7.2.0-preview.3` and above needs .NET 6 as `7.2.0` version is based on .NET 6. Hopefully this helps!

![image](https://user-images.githubusercontent.com/12820925/118563661-d332eb00-b723-11eb-9bee-13b40ba4f9c8.png)
