### ISSUE TITLE
Autocomplete issues on linux

### ISSUE THREAD

**Issue by gsevla** [PowerShell/PowerShell#15041]
## Steps to reproduce

```
1. Open terminal
2. Enter _pwsh_ to execute powershell
3. Now try to autocomplete some command like _dnf upg_... (I'm using fedora 33) or _flatpak ins_...
```

## Expected behavior

```
I'm using powershell on mac os too and there autocomplete works like a charm.
So I was expecting the exact same behavior on linux.
```

## Actual behavior

```
Autocomplete linux commands are not working. But autocomplete for powershell commands works.
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.10.22-200.fc33.x86_64 #1 SMP Tue Mar 9 …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I have installed pwsh using [official docs](https://docs.microsoft.com/pt-br/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation-via-package-repository-preferred---fedora-28-29-and-30)

And yes, I know it says fedora 28, 29 and 30 but there's any reason to?

**Comment by joeyaiello** [comment]
You can get tab completion for non-PS commands via @rjmholt's module here: https://www.powershellgallery.com/packages/Microsoft.PowerShell.UnixCompleters/0.1.1

We're looking to put this functionality straight into PowerShell at some point, but if you pick that up, you'll get whatever completions are available to bash on that same machine.

**Comment by gsevla** [comment]
> You can get tab completion for non-PS commands via @rjmholt's module here: https://www.powershellgallery.com/packages/Microsoft.PowerShell.UnixCompleters/0.1.1
> 
> We're looking to put this functionality straight into PowerShell at some point, but if you pick that up, you'll get whatever completions are available to bash on that same machine.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ca767ff8f0625dd18823c74a8a69da3d93d9df23f87b6703e040b55ba100e9f4/68747470733a2f2f706f7765727368656c6c67616c6c6572792e636f6d2f436f6e74656e742f496d616765732f4272616e64696e672f5061636b61676544656661756c7449636f6e2e706e67">**[Microsoft.PowerShell.UnixCompleters 0.1.1](https://powershellgallery.com/packages/Microsoft.PowerShell.UnixCompleters/)**Get parameter completion for native Unix utilities. Requires zsh or bash.

Many thanks to you man!

But it shouldn't be available on the docs?

Btw I searched for a pwsh module that could do completions but couldn't find. So I guess some other people will not find it either.
