### ISSUE TITLE
New-Variable and Set-Variable: The -Option parameter should be array-valued to better suggest that *combinations* of variable options are possible

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15057]
## Summary of the new feature/enhancement

* The `-Option` parameter of `New-Variable` and `Set-Variable` is of type [`System.Management.Automation.ScopedItemOptions`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.ScopedItemOptions), which is an `enum` with the `Flags` attribute: that is, *multiple* values (bit-ORed flags) can be assigned.

* Because the parameter type is a _scalar_, however, it isn't  obvious how to pass _multiple_ options at the same time - even _though it is directly supported_ (thanks, @SeeminglyScience).

```powershell
# Works, but isn't obvious from looking at the syntax diagram.
New-Variable foo bar -Option ReadOnly, AllScope
```

---

Written as of PowerShell Core 7.2.0-preview.4.

**Comment by SeeminglyScience** [comment]
> A better way to support this - which shouldn't break existing code - would be to use accept an _array_ of such values:
> 
> ```powershell
> # WISHFUL THINKING
> New-Variable foo bar -Option ReadOnly, AllScope
> ```

Did you try that? Seems to work for me:

```powershell
New-Variable foo bar -Option ReadOnly, AllScope
(Get-Variable foo).Options
# ReadOnly, AllScope
```

**Comment by mklement0** [comment]
@SeeminglyScience, well I'll be...

Thanks, trying that hadn't even _occurred_ to me, given the type of the parameter.

But now I see that casting an array of strings directly to an `enum` in PowerShell is directly supported:

```powershell
PS> [System.Management.Automation.ScopedItemOptions] ('ReadOnly', 'AllScope')
ReadOnly, AllScope
```

That is, `[System.Management.Automation.ScopedItemOptions] ('ReadOnly', 'AllScope')` is equivalent to `[System.Management.Automation.ScopedItemOptions] 'ReadOnly, AllScope'` and `[System.Management.Automation.ScopedItemOptions]::ReadOnly -bor  [System.Management.Automation.ScopedItemOptions]::AllScope`

So many ways to herd enums. TIL.

Still, given how non-obvious this us from looking at the syntax diagram and without knowing the intricacies of these conversions, we should still consider making the parameter array-valued.

**Comment by mklement0** [comment]
@SeeminglyScience, I'm closing this for now, because I think the issue here is a more fundamental UI / help-system issue that I have to get a better handle on first:

* Currently, nothing in the syntax diagrams indicates when a parameter happens to be a `Flags` enum and that _combinations_ are therefore automatically accepted.

* `Get-ChildItem`, by using a _plural_ in its `-Attributes` parameter name, helps this a little.

A simple solution would be to establish a convention to consistently use _plurals_ in parameter names that are `Flags`-enum-typed.

In the case at hand, an `-Option` could be renamed to `-Options` without breaking anyone.

Separately/additionally, syntax diagrams, when they show the individual enumeration values with `Get-Help`, could indicate `Flag` enums, along the lines of the following (borrowing metachar. `+` from regexes):

```
... [-Options {None | ReadOnly | Constant | Private | AllScope | Unspecified}+]
```
