### ISSUE TITLE
Start-Process on Unix: trying to launch / open a nonexistent file doesn't trigger an error

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15054]
Note: Windows is _not_ affected.

## Steps to reproduce

```powershell
# Fails on macOS and Linux - no statement-terminating error occurs.
{ Start-Process nosuch } | Should -Throw
```

If you run `Start-Process nosuch` directly, a system error message that cannot be captured prints directly to stderr:

* Ubuntu:

```
"gio: file:///.../nosuch: Error when getting information for file “/.../nosuch”: No such file or directory"
```

* macOS:

```
The file /.../nosuch does not exist.
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because no statement-terminating error is triggered, even though no such file in the current directory / no such executable in the path exists.

```none
Expected an exception, to be thrown, but no exception was thrown.
```

## Environment data

```none
PowerShell Core v7.2.0-preview.4 on macOS 10.15.7
PowerShell Core v7.2.0-preview.4 on Ubuntu 18.04.5 LTS
```

**Comment by 237dmitry** [comment]
```
{ Start-Process nosuch } | Should -Throw
Should: The term 'Should' is not recognized as a name of.....
```
Is this a some module?

```
Start-Process nosuch
xdg-open: file 'nosuch' does not exist
```

**Comment by mklement0** [comment]
Thanks, @joeyaiello, it shouldn't be hard to implement, given that the underlying .NET API reports an exception:

```powershell
PS> [System.Diagnostics.Process]::Start([System.Diagnostics.ProcessStartInfo] @{ FileName = 'nosuch' }).WaitForExit()
MethodInvocationException: Exception calling "Start" with "1" argument(s): "No such file or directory"
```

@237dmitry, you can install Pester with `Install-Module Pester`.
Providing repro steps in the form of Pester tests (via `Should`) makes it easy for others to verify the problem and helps implementers verify when the problem is fixed.

**Comment by mklement0** [comment]
The problem is related to setting `UseShellExecute` to `true`:

```powershell
PS> [System.Diagnostics.Process]::Start([System.Diagnostics.ProcessStartInfo] @{ FileName = 'nosuch'; UseShellExecute = $true }).WaitForExit()
The file /Users/mklement/Desktop/pg/nosuch does not exist.
```

**Comment by SteveL-MSFT** [comment]
The way `Start-Process` works is it tries to find the target first.  If it's not found, and no arguments were provided, then it tries `UseShellExecute = true`.  At this point, it's all handled by the dotnet runtime.  Dotnet relies on `xdg-open` on Linux and `open` on macOS.  You can try this by running `open foo` on macOS and you'll see the stderr message.  It appears that dotnet runtime writes this directly to the console and thus you can't actually redirect.  Created https://github.com/dotnet/runtime/issues/49788
