### ISSUE TITLE
FR: Auto update PowerShell 

### ISSUE THREAD

**Issue by vajahath** [PowerShell/PowerShell#15064]
## Summary of the new feature/enhancement
As a user, I wish if powershell was able automatically update to latest stable version along with windows update or some sort of other mechanism.

## Proposed technical implementation details
* Along with Windows updates.
* Or, like how Chrome updates behind the scenes.

**Comment by iSazonov** [comment]
Thanks for your contribution! You can find some issues about this and you could read MSFT PowerShell team latest blog post about roadmap.
