### ISSUE TITLE
Get-Date cmdlet outputs wrong year from "FileTime" value.

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#15062]
## Steps to reproduce

```powershell

    $filetime = (Get-Date).ToFileTime()
    'Get-Date: {0:dd.MM.yyyy}' -f (Get-Date $filetime)
    'DateTime: {0:dd.MM.yyyy}' -f [datetime]::FromFileTime($fileTime)

```
Output:
```
Get-Date: 18.03.0421
DateTime: 18.03.2021
```

## Expected behavior

Outputting the correct date

## Actual behavior

Incorrect year value

## Environment data

```none
$PSVersionTable                                         
                                                           
Name                           Value                       
----                           -----                       
PSVersion                      7.1.3                       
PSEdition                      Core                        
GitCommitId                    7.1.3                       
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3                         
SerializationVersion           1.1.0.1                     
WSManStackVersion              3.0                         
```

**Comment by mklement0** [comment]
`.ToFileTime()` returns a FILETIME value as a `System.Int64` (`[long]`) value, i.e. a mere _number_.
This number represents (a) a _UTC_ timestamp in 100-nanosecond units (`1e7` units per second), and (b) has UTC  time `1601-01-01T00:00:00Z` as its staring point.

If you pass a mere _number_ to `Get-Date`, the cast to `[datetime]` ([`System.DateTime`](https://docs.microsoft.com/en-US/dotnet/api/System.DateTime)) interprets the number as the `.Ticks` property value of that type, which represents the 100-nanosecond units *since `0001-01-01T00:00:00`*, i.e. a difference of `1600` years, which explains your result.

Additionally, if you construct a `[datetime]` instance this way, its `.Kind` property value is `Unspecified`, i.e.  it is _undefined_ whether the timestamp is a UTC timestamp or a local one.

**Comment by 237dmitry** [comment]
> In other words: Everything works as expected.

Why is this value interpreted at all?

```                                        
$filetime = (Get-Date).ToFileTimeUtc()      
Get-Date $filetime -f 'yyyy.dd.MM HH:mm:ss'
                                         
0421.18.03 14:05:52                   
```

**Comment by mklement0** [comment]
`$filetime` isn't a _date_, it's just a _number_ (a `[long]` instance that happens to contain a FILETIME value).

So when you pass it to `Get-Date`('s positionally implied, `[datetime]`-typed `-Date` parameter), that number must be _interpreted_.

Behind the scenes, `[datetime]::new($filetime)` is called, using [this constructor](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.-ctor?view=net-5.0#System_DateTime__ctor_System_Int64_).

**Comment by 237dmitry** [comment]
> So when you pass it to Get-Date('s positionally implied, [datetime]-typed -Date parameter), that number must be interpreted.

This does not be wrong interpreted:
```
 $a = (Get-Date -Date '01.01.1900 00:00:01').ToFileTimeUtc()
Get-Date -Date $a -format 'yyyy.MM.dd HH:mm:ss'                 

0300.01.01 00:00:01                                           
```
Why YEAR? Not date, not time....  Either the correct date or an exception, I think have to be. Do you agree?

**Comment by mklement0** [comment]
This exhibits the same `1600` years difference I've previously explained.

Your misconception is that you're expecting `.ToFileTime()` to return an _object_ that represents a _timestamp_ (a point in time), but it isn't: it's just a number.

**Comment by 237dmitry** [comment]
I really don't understand why in this case Get-Date returns the result and not an error. Why it returns timespan `$Year - 1600` as datetime type? 
```
(Get-Date $filetime).GetType().fullname
System.DateTime 
```

**Comment by mklement0** [comment]
`Get-Date` is being passed a _number_, which it interprets as the `.Ticks` value of a `[datetime]` instance, for the reasons explained.

If I define `$filetime` as in in the initial post, as of this moment, I get a value of `132605822910578720`, so let's try to pass this to `Get-Date` (results from my computer, in the Eastern US time zone):

```powershell
PS> Get-Date 132605822910578720

Thursday, March 18, 0421 11:04:51 PM

```

**Comment by 237dmitry** [comment]
Ticks from what date?
```
 > (Get-Date '01.01.1601 00:00:01').ToFileTimeUtc()
10000000                                          

 > Get-Date 10000000 -f 'yyyy.dd.MM HH:mm:ss'      
0001.01.01 00:00:01      # Monday ;)                          
```

**Comment by mklement0** [comment]
As implied by my previous comments, `Get-Date 10000000` is the same as `[datetime]::new(10000000)`, and therefore relates to a starting date of `0001-01-01T00:00:00`.

**Comment by 237dmitry** [comment]
All is clear but why `Get-Date` trying interpret these values is not. `New-Timespan` or `(Get-Date) - (Get-Date)` returns a more obvious result.  If `Get-Date` returns a datetime object, then why not give it the same capability as `System.Datetime` class? For example:
```
Get-Date -FromFiletime_Uts_ $filetime
```
This would be logical to get the FileTime value and return the DateTime object from a single cmdlet. Without resorting to .net methods explicitly.  It's more a matter of style, not convenience. These are small things, but every little thing is important. I had never even thought of putting FileTime in Get-Date before. That's why I was surprised. Good Night, my _filetime_ is already near the morning.

**Comment by mklement0** [comment]
> why Get-Date trying interpret these values is not.

It _is_ clear, as explained - and without an explicit (hypothetical) parameter such as `-FromFileTime`, what you're asking for cannot be implemented (see below).

> why not give it the same capability as `System.Datetime` class?

Generally speaking, it is - and cannot - be PowerShell's goal to replicate _all_ .NET APIs.
Instead, PowerShell's focus is on what matters from a perspective of a _shell_ and _automation_ - though there is substantial overlap, which is what makes PowerShell unique among shells.

Using .NET APIs, the solution is:

```powershell
[datetime]::FromFileTime($filetime)
```

This complements your use of a .NET API to obtain the `$filetime` value to begin with  - the `.ToFileTime()` method.

---

If you feel strongly enough that this functionality should be surfaced via the `Get-Date` cmdlet as well, I suggest you create a _new_ issue of type "Feature Request/Idea" and ask for:

* `-AsFileTime` to convert (from `[datetime]`) TO a FILETIME value
* `-FromFileTime` to convert FROM a FILETIME value (to a `[datetime]` instance)

Note: no need for `_UTC`, as FILETIME values are by definition UTC timestamps.
