### ISSUE TITLE
static type checking 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15069]
hi guys !!

we can use **dynamic type checking** in PS with classes _tags_ ex: `[int]$a = 1`
its awesome but PS missing **static type checking**  to  checks the input/output program against the type rules defined in **a type language** after the program parses successfully  (that is there are no syntax errors in it).  many languages implement this static type checker for example in ruby 3 we can use now[ _RBS_](https://github.com/ruby/rbs)  this is usefull we can defined the type input/output to our program

**Comment by JustinGrote** [comment]
THis is more likely to be implemented in https://github.com/PowerShell/PSScriptAnalyzer than the core repo here, I would recreate your issue there. I started a similar discussion already:

https://github.com/PowerShell/PSScriptAnalyzer/discussions/1658
