### ISSUE TITLE
Add a -Tree or -Recurse parameter to Stop-Process

### ISSUE THREAD

**Issue by GitClickOk** [PowerShell/PowerShell#15075]
When using `Stop-Process` to terminate a process, a (very) common task is stop the entire tree of this process. To be more precise, ALL times when I need stop some process I need terminate the entire tree.

Currently the easiest way to do it is using taskkill:
`taskkill /IM "notepad.exe" /T /F`
obviously it is not a built in PowerShell Core feature. The PSCore command is `Stop-Process`, but it has not a built in way to kill the tree, then we need some pipeline-fu like [here](https://stackoverflow.com/a/55942155/48729).

Then, by the same reason TaskKill has a /T flag, I propose `Stop-Process` get a ~~`-Tree`~~ `-Recurse` (as suggested by @GeeLaw) parameter. It is a natural addition, and surely it will avoid a lot of errors and extra boilerplate scripting for a so common task.

**Comment by p0W3RH311** [comment]
use the `-Force` switch ?

**Comment by mklement0** [comment]
@p0W3RH311, all that the `-Force` switch does is it suppresses the confirmation prompt that is shown by default when you attempt to kill a different user's process(es).

`-Tree` would be new functionality that maps onto  [`.Kill(true)`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-5.0#System_Diagnostics_Process_Kill_System_Boolean_)

**Comment by GeeLaw** [comment]
I think `-Recurse` aligns better with current terminology (cf. file system provider).

**Comment by SteveL-MSFT** [comment]
My preference would be `-IncludeChildProcesses` as it's descriptive for non-technical folks, but we can alias it to `-Recurse`

**Comment by iSazonov** [comment]
Since we say about "Stop" it makes sense to _get_ a list of the child processes. I mean the parameter could be in Get-Process cmdlet too.

**Comment by SteveL-MSFT** [comment]
@iSazonov I think `Get-Process` should definitely have the same parameters and the output should be formatted to look like a tree.  I think that should probably be a different issue linked to this one as you could implement one without the other.

**Comment by iSazonov** [comment]
> maybe we really need a Format-Tree cmdlet which would also work with other objects?

Good idea but I can not thing how we could inject/involve the Format-Tree cmdlet in smart way. Perhaps we could enhance Format-Table cmdlet `Get-Process -IncludeChildProcesses  | ft -TreeDisplayProperty Name -TreeBuildPropertyPair ProcessId, ParentProcessId` (we could automatically pick up right format view based on IncludeChildProcesses  custom type).

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this and think it's reasonable to add a `-IncludeChildProcess` parameter to `Stop-Process` that terminates all child processes in addition to the parent process. There should also be a `-Tree` alias to `-IncludeChildProcess`. 

Marking this as Up-for-Grabs as it's not a high priority for us at this time.

**Comment by SteveL-MSFT** [comment]
@iSazonov we should have the `Format-Table` tree view probably as a GitHub discussion?

**Comment by iSazonov** [comment]
> @iSazonov we should have the `Format-Table` tree view probably as a GitHub discussion?

> > maybe we really need a Format-Tree cmdlet which would also work with other objects?
> 
> Good idea but I can not thing how we could inject/involve the Format-Tree cmdlet in smart way. Perhaps we could enhance Format-Table cmdlet `Get-Process -IncludeChildProcesses | ft -TreeDisplayProperty Name -TreeBuildPropertyPair ProcessId, ParentProcessId` (we could automatically pick up right format view based on IncludeChildProcesses custom type).

My current proposal would be to benefit from `View` - `Get-Process -IncludeChildProcesses | ft -View Tree`. Since we added tab completion for View parameter (also there could be automatic Tree view selection) we can _hide all in Formatting system_ and get great user experience. Although the implementation can be non-trivial. This brings us back to the idea of Format-Tree which is not trivial for injection too.

Another thoughts. Modern process and directory/file names are so long that I don't see how we could display such wide tree in a window. _It is a feature rather for Out-GridView_ where we could implement expand-collapse feature for nested data.

So I am very skeptical today about further Github Discussion. :-)

**Comment by SteveL-MSFT** [comment]
Starting with just a `Tree` view for `ProcessInfo` seems like a good idea.  Maybe I'll work on that this weekend...

**Comment by nickkimbrough** [comment]
> @PowerShell/wg-powershell-cmdlets discussed this and think it's reasonable to add a `-IncludeChildProcess` parameter to `Stop-Process` that terminates all child processes in addition to the parent process. There should also be a `-Tree` alias to `-IncludeChildProcess`.

@SteveL-MSFT , as @mklement0 stated, this could simply be mapped to `.Kill(true)`, but that method returns `void` and wouldn't allow us to passthru the child processes that were stopped. Should the `-PassThru` functionality remain as it is today and only return the matching parent processes, or should we add additional logic to also return the child processes that were stopped as well?

**Comment by iSazonov** [comment]
I am ok with "only return the matching parent processes".

**Comment by GeeLaw** [comment]
I think returning the matching parent process(es) is the desired behavior.

Consider `Get-Proces ... | Stop-Process -Recurse -PassThru`. I expect `-PassThru` to mean "do not eat the objects piped into this cmdlet". Since only parent processes are piped in, only those should be piped out. And it's intuitive for `Stop-Process A -AnyOtherArguments` to behave the same way as `Get-Process A | Stop-Process -AnyOtherArguments`.

**Comment by GitClickOk** [comment]
bad bot, no AI food for you
