### ISSUE TITLE
some command can run in powershell5.1,but cant run in powershell7 ,like  ssh ;

### ISSUE THREAD

**Issue by frinck** [PowerShell/PowerShell#15070]
- the powershell version is ：
$PSVersionTable 
Name                           Value
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0 

when i use the command  `ssh、get-localuser` will occur error:
`ssh: The term 'ssh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**Comment by DHowett** [comment]
I suspect you installed x86 PowerShell 7 on an x64 machine.

**Comment by frinck** [comment]
> I suspect you installed x86 PowerShell 7 on an x64 machine.

thanks a lot！！！
