### ISSUE TITLE
Use System.Diagnostics.Eventing.Reader from .NET Core

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#15083]
## Summary of the new feature/enhancement

Comes from https://github.com/dotnet/corefx/issues/31358 and dotnet/corefx#33662 - we could cleanup PowerShell Core code and use System.Diagnostics.Eventing.Reader from .NET Core. This will reduce PoweShell distributive size.

**Comment by xtqqczze** [comment]
@iSazonov This is not completed, please reopen.

**Comment by xtqqczze** [comment]
We should really be using this, bugs have been fixed, for example https://github.com/dotnet/runtime/issues/100198.
