### ISSUE TITLE
[issue-question] PrintManagement module

### ISSUE THREAD

**Issue by scriptingstudio** [PowerShell/PowerShell#15082]
Although PrintManagement module and get-CimInstance cmdlet use the same WMI class, the behavior is different.

## Steps to reproduce
Membership of user account is just `Domain Users`.
```powershell
> gcim MSFT_printer -Namespace ROOT/StandardCimv2 -comp ps1
Get-CimInstance : Access denied.


> get-printer -comp ps1

Name                           ComputerName    Type         DriverName                PortName        Shared
----                           ------------    ----         ----------                --------        ------
PF508-Konica454                ps1             Local        KONICA MINOLTA Univers... IP_192.168.1... True
PF505-Konica458-2              ps1             Local        KONICA MINOLTA Univers... IP_192.168.1... True
PF418-Konica300                ps1             Local        KONICA MINOLTA Univers... IP_192.168.1... True
```

## Environment data
```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
What's the "secret" of the PrintManagement module?

**Comment by jborean93** [comment]
When you do `Get-CimInstance ... -ComputerName ps1` you are connecting over WSMan to `ps1` and running the CIM query on that host in question. It's very similar to doing

```powershell
Invoke-Command -ComputerName ps1 -ScriptBlock {
    Get-CimInstance -ClassName MSFT_Printer -Namespace Root/StandardCimV2
}
```

Looking at the [MSFT_Printer](https://wutils.com/wmi/root/standardcimv2/msft_printer/) class I can see that [ComputerName](https://wutils.com/wmi/root/standardcimv2/msft_printer/#computername_properties) is an actual property of this class which states:

> The name of the server which this printer resides on.

So my guess is that `Get-Printer -ComputerName ps1` isn't actually using WSMan to connect to `ps1` but is instead doing something like the following:

```powershell
Get-CimInstance -ClassName MSFT_Printer -Namespace ROOT/StandardCimV2 -Filter "ComputerName='ps1'"
```

And this essentially is getting all the printers on the localhost that are shared through `ps1` rather than connecting to `ps1` and getting the printers on that host.

**Comment by scriptingstudio** [comment]
> So my guess is that Get-Printer -ComputerName ps1 isn't actually using WSMan to connect to ps1 but is instead doing something like the following:

It is a technical nonsense, because expression `Get-CimInstance -ClassName MSFT_Printer -Namespace ROOT/StandardCimV2 -Filter "ComputerName='ps1'"` makes a local query and filter looks strange, and output is useless.

> If it's a standard (non-admin) account then it might not have access to get the WMI info

Agree. 
```powershell
> gwmi MSFT_printer -Namespace ROOT/StandardCimv2 -comp ps1
gwmi : Access denied.
```

**Comment by jborean93** [comment]
> It is a technical nonsense, because expression Get-CimInstance -ClassName MSFT_Printer -Namespace ROOT/StandardCimV2 -Filter "ComputerName='ps1'" makes a local query and filter looks strange, and output is useless.

It might be technical nonsense but it is what is happening. The `ComputerName` parameter exposed by `Get-Printer` just relates to the `ComputerName` property on the CIM class. It's not like the `ComputerName` parameter on things like `Get-Process`, `Get-Service`, `Invoke-Command` which is designed to run on the remote host specified. The CDXML cmdlets are basically a cmdlet definition in XML that maps the CIM class specified in the XML to a cmdlet automatically.
