### ISSUE TITLE
Give useful syntax errors in Import-PowerShellDataFile

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#15094]
## Summary of the new feature/enhancement
Currently, when .psd1 is malformed and I use `Import-PowerShellDataFile`, I get a generic error:
```
Import-PowerShellDataFile: The file '<file>.psd1' could not be parsed as a PowerShell Data File.
```
This doesn't really help with finding the syntax error. I'd prefer if a normal syntax error would be returned, as with `.`, `&`, `Import-Module` and any other PowerShell file, which clearly shows location of the error.

**Comment by p0W3RH311** [comment]
+1

i suggest for this error (and for all error with structured constrained data) an error like in [ELM Language](https://github.com/PowerShell/PowerShell/issues/15081)

**Comment by p0W3RH311** [comment]
@MatejKafka why downvote ?

**Comment by MatejKafka** [comment]
not completed, please reopen

**Comment by MatejKafka** [comment]
As a temporary solution until this is hopefully improved, I'm using the following C# class in one of my projects to load data files with better error messages, while also fixing #12789 (apologies about the lack of comments): https://github.com/MatejKafka/Pog/blob/main/app/Pog/lib_compiled/Pog/src/Pog.PackageManifestParser.cs#L16
