### ISSUE TITLE
`$PSScriptRoot` and `$PSCommandPath` are not populated with `Start-Job -FilePath <filepath>`

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#15096]
## Steps to reproduce

script.ps1:
```powershell
echo $PSCommandPath
echo $PSScriptRoot
```

Run this in terminal:
```powershell
Start-Job -FilePath .\script.ps1 | Receive-Job -Wait
```

## Expected behavior

```none
<path-to-script.ps1>
<path-to-scrpt.ps1-dir>
```

## Actual behavior

```none


```
(2 empty lines)
## Environment data

```none
PSVersion                      7.2.0-preview.3
PSEdition                      Core
GitCommitId                    7.2.0-preview.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The explanation for the current behavior (which is definitely debatable) is implied by this line [from the docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/start-job):

> When you use this parameter, PowerShell converts the contents of the specified script file to a script block and runs the script block as a background job.

That is, the background job doesn't execute the script _file_ given, but _its contents_, as a script block - and such a script block has no information about where it ultimately came from.

While this behavior makes perfect sense in the context of _remoting_ (with `Invoke-Command -ComputerName $someComputer -FilePath ...`), it arguably makes better sense to let the background job - which by definition runs on  the _same machine_ and can therefore access the specified _file_  - execute the script _file_ directly, so as not to lose invocation context.

**Comment by MatejKafka** [comment]
Don't think this should be closed, as the issue is not really resolved. @iSazonov

**Comment by iSazonov** [comment]
The issue is not blocked and anyone can continue to discuss. 
This is a behavior "by-design" and it needs huge reason to change it. This kind of anonymity can be beneficial or even security-related.

**Comment by mklement0** [comment]
I don't think security concerns are in the picture here, and my _guess_ is that this was done more for the convenience of sharing an implementation with / behavioral symmetry with `Invoke-Command -FilePath`

That said, @MatejKafka, the problem is easily worked around by using a script block instead:

```powershell
Start-Job { .\script.ps1 } | Receive-Job -Wait
```

Note that in Windows PowerShell this won't necessarily work, because background jobs there don't inherit the caller's location, but in PowerShell Core that isn't a problem anymore.
