### ISSUE TITLE
PipelineVariable not available when using Foreach-Object -Parallel

### ISSUE THREAD

**Issue by trir262** [PowerShell/PowerShell#15102]
## Steps to reproduce

```powershell
$MyDict = [System.Collections.Concurrent.ConcurrentDictionary[string,object]]::new()
Get-Process -PipelineVariable Processinfo | ForEach-Object -Parallel {
    $dict = $using:MyDict
    $dict.TryAdd($Processinfo.id, $Processinfo) | Out-Null
}

$MyDict.Keys.Count
1

$MyDict.Keys

```

## Expected behavior

```none
$MyDict.Keys.Count
200
$MyDict.Keys
0
2
3
9
1480
...
```

## Actual behavior

```none
$MyDict.Keys.Count
1

$MyDict.Keys

```

## Environment data

```none
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

The variable defined as the pipeline variable is not available in the foreach-object script when the option -Parallel is used, However then -Parallel is not used, the variable can be used correctly

**Comment by vexx32** [comment]
`ForEach-Object -Parallel` executes scriptblocks concurrently in separate runspaces, so the only data they have access to is the direct input data. Additional defined variables are generally not accessible.

Use `$_` or `$PSItem` to access the input data, rather than a custom pipeline variable name.

**Comment by trir262** [comment]
Thank you for the fast feedback! I tried `$using:Processinfo` but unfortunately it returns with an error:

```PowerShell
InvalidOperation:
Line |
   3 |  $dict.TryAdd($using:Processinfo.id, $using:Processinfo) | Out-Null
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A Using variable cannot be retrieved. A Using variable can be used only with Invoke-Command, Start-Job, or InlineScript in the script workflow. When it is used with Invoke-Command, the Using variable is valid only if the script block is invoked on a remote computer.
```

**Comment by mklement0** [comment]
While @vexx32 is correct in that using `$_` aka `$PSItem` is the best solution here, you're definitely either seeing a bug or a design limitation that is surfaced via a misleading error message:

* It is reasonable to expect `-PipelineVariable` to also work with `ForEach-Object -Parallel` - but, as with reference to any variable value from the caller's scope, you would then have to refer to it via the `$using:` scope.

* This is what you've tried in your previous comment, but it fails _with an inapplicable error message_ - clearly, `$using:` references _can_ be used in `ForEach-Object -Parallel`; it is only the reference to a _pipeline variable_ that causes the error.

* If this is a by-design limitation (I don't know the answer - perhaps @PaulHigin or @SeeminglyScience can clarify), we at least need an appropriate error message.

**Comment by PaulHigin** [comment]
Pipeline variables are not supported for Foreach-Object -Parallel.  The RFC and blog specify that variables can be passed in only via pipeline input `$_` and with the `$using:` keyword.

```
...
The only variable that automatically appears in the parallel script block is the piped in object. Other variables are passed in using the $using: keyword.
...
```

But we may need to update the documentation to make this more clear.  This may be something that can be considered for future releases.

**Comment by mklement0** [comment]
Thanks for clarifying, @PaulHigin; documenting this will certainly help, but providing an appropriate error message is important too.

If we don't want to introduce a _specific_ error message for this scenario, the existing, catch-all message should be amended, along the lines of:

```
A Using variable can be used only with Start-Job, Start-ThreadJob, 
ForEach-Object -Parallel, except with pipeline variables,
and Invoke-Command when targeting remote computers.
```

Note that I've cut out the _workflow_ reference, as it doesn't apply to PS Core anymore, and that I've also added `Start-ThreadJob`.

**Comment by mklement0** [comment]
I've created a docs issue at https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7380, and in the course of writing it up noticed that there's another enhancement worth making:

The `$using:<pipelineVar>` reference _quietly defaults to `$null`_ instead of complaining _unless property access directly on the `$using` reference is attempted_; e.g.:

```powershell
PS> Write-Output a, ab, abc -PipelineVariable word | ForEach-Object -Parallel { $null -eq $using:word }
True
True
True
```

vs.

```powershell
PS> Write-Output a, ab, abc -PipelineVariable word | ForEach-Object -Parallel { $using:word.Length }
InvalidOperation: A Using variable cannot be retrieved...
InvalidOperation: A Using variable cannot be retrieved...
InvalidOperation: A Using variable cannot be retrieved...
```

vs. _indirect_ property access (`$using:` reference again evaluates to `$null`):

```powershell
PS> Write-Output a, ab, abc -PipelineVariable word | ForEach-Object -Parallel { $w = $using:word; $w.Length }
0
0
0
```

**Comment by PaulHigin** [comment]
Actually, @mklement0 has identified a new bug.  The steps shown above should result in an error message.  We should understand why it doesn't.  However, this feels low impact.

**Comment by PaulHigin** [comment]
I looked into this some more and this is not a problem specific to ForEach-Object -Parallel, but is a general $using: variable issue, as I can repro it with Start-Job as well.  The utility method to retrieve the pipeline variable 'word' does not retrieve the value correctly.

So this is a general '$using:' variable problem.

**Comment by vexx32** [comment]
Pipeline variables are an oddity. I'm not sure at what scope they're actually present. Naturally they're present for the lifetime of the pipeline, but are they present as part of that pipeline's parent scope? Or is a new child scope created for pipeline variables?

**Comment by PaulHigin** [comment]
Don't know, but good questions.  The 'word' pipeline variable exists in scope but doesn't have any special designation that I could see, and has a value of 'null'.  This is outside my area of knowledge.  @daxian-dbw may be able to help.
