### ISSUE TITLE
Parity between PowerShell.Invoke() and ScriptBlock.Invoke() APIs

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15105]
## Summary of the new feature/enhancement

Follows on somewhat from https://github.com/PowerShell/PowerShell/issues/15004.

Both the `PowerShell` and `ScriptBlock` APIs have some really useful invocation methods, but there's no one true API to rule them all.

`ScriptBlock` has:

- `InvokeWithContext()`, which allows passing in custom function and variable contexts, but it's not straightforward (possible?) to choose which runspace it's run on and it doesn't interact well with a `PowerShell` object
- Cmdlets also have various APIs for taking in `ScriptBlock`-typed variables, but no direct support for `PowerShell`
- However scriptblocks don't have good support for configuration around dot-sourcing, history, or named parameters

Conversely, with `PowerShell`:

- It's really easy to structurally compose commands, including named parameters
- Invoking `PowerShell` objects safely across threads is easier/possible
- More configuration can be given around things like history and whether to dot-source
- However, there's no way to add custom contextual definitions (and the `Invoke()` overloads do strange things with `input` when it's used the wrong way because it's an `IEnumerable`)
- There's also no good interaction between `PowerShell` and a `ScriptBlock` object. It would be great if it had an `AddScript` overload that took a `ScriptBlock` instead of a string.

My primary ask here would be to augment the `PowerShell` API -- it should be the core API through which we do everything and it's a pretty well designed API so far I think. There are just some scenarios today where I'm forced to use `ScriptBlock`, even though `PowerShell` is clearly the intended way to do what I'm doing.

**Comment by SeeminglyScience** [comment]
> * `InvokeWithContext()`, which allows passing in custom function and variable contexts, but it's not straightforward (possible?) to choose which runspace it's run on and it doesn't interact well with a `PowerShell` object

I think part of what makes it feasible for one and not the other is that these API's represent fundamentally different things. `PowerShell` is more or less just a friendly wrapper around `PipelineProcessor` and `CommandProcessor` where the `ScriptBlock` API represents a single anonymous command.

For example, if you were able to include context, where would it be defined? With `InvokeWithContext` you create a new scope, dump the state, and then it's automatically cleaned up when no longer in scope.  With `PowerShell`, would you define it in whatever the current scope is? Or would you attach it to `Add(Script|Command)`?

From an implementation standpoint, the code path would probably need to change drastically.  Right now it's pretty close to a normal invocation, but afaik it would not have a way to pass state to the underlying `CommandProcessor`.  It may need to take a similar route that the `ScriptBlock.InvokeWithPipeImpl` API does which has a lot of performance issues and limitations.

---

Part of me wishes there was some ability to control scopes.  Something like this:

```csharp
using var pwsh = PowerShell.Create(RunspaceMode.CurrentRunspace);
pwsh.PushScope()
    .AddFunction(name, body)
    .AddVariable(name, value)
    .AddCommand("Invoke-MyThing")
    .PopScope();
```

I've wanted that for a while (probably a different design) but I'm unsure if it's worth it.

- Scopes have mainly been an almost completely private implementation detail, with the exception of a few "do or don't make a scope" parameters
- Modules greatly complicate that.  You'd potentially need to add a `PSModuleInfo` or `SessionState` parameter to `(Push|Pop)Scope`

**Comment by rjmholt** [comment]
Yeah you have a very good point around what does context mean here.

I'd love to do something like take a scriptblock and a `PowerShell` instance and execute that scriptblock in that `PowerShell` context with some added private context of my own.
