### ISSUE TITLE
Improve performance by using sealed classes 

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#15110]
Inspired by https://github.com/dotnet/runtime/issues/49944

- We could think about getting rid of InternalsVisibleTo attributes (specially in SMA).
- We could make (all) private classes sealed.
- We could make (all) internal classes sealed.

This can be especially important if we use PGO for optimizing startup scenarios.

**Comment by daxian-dbw** [comment]
> We could think about getting rid of InternalsVisibleTo attributes (specially in SMA).

This is not possible given that `management.dll`, `utility.dll`, and `security.dll` depending on this flag. Not only that, subsystems will depend on that flag as well in future.

But yeah, it would be nice to follow this best practice in our code base to mark types sealed properly.

> This can be especially important if we use PGO for optimizing startup scenarios

@iSazonov why PGO would require this? can you please clarify this statement? Also, can you be more specific how PGO can be used in PowerShell?

**Comment by iSazonov** [comment]
My main concern is that using of InternalsVisibleTo will absolutely block PGO for us. There is still no documentation for PGO. You may want to talk to the authors of PGO. 

I can only guess that InternalsVisibleTo and sealed both truncate any inheritance/virtualization and as a consequence allow bolder optimizations.

> Also, can you be more specific how PGO can be used in PowerShell?

From my understanding it is the main purpose of the PGO to improve startup scenario(s). We could create specific PowerShell PGO profile and distribute it with PowerShell.

**Comment by xtqqczze** [comment]
> It seems we lost this in #11773 /cc @xtqqczze

So perhaps we want a new PR similar to those changes (2069d92b3e2760ab631efbf12bbde9ca46e661e2), but only `private`, `internal`?

**Comment by iSazonov** [comment]
> From my understanding it is the main purpose of the PGO to improve startup scenario(s). We could create specific PowerShell PGO profile and distribute it with PowerShell.

Also I think we could accelerate other typical scenarios too like runspace/scriptblock creation.

**Comment by xtqqczze** [comment]
We could look into: https://github.com/geeknoid/UnsealedAnalyzer

**Comment by xtqqczze** [comment]
@iSazonov I wonder whether #15675 has improved performance and whether we could measure this?

**Comment by iSazonov** [comment]
It is best practice. .Net Runtime can do more optimizations if a class cannot have derived classes and cannot be used outside.

**Comment by xtqqczze** [comment]
> It is best practice. .Net Runtime can do more optimizations if a class cannot have derived classes and cannot be used outside.

It would be good to quantify the improvement, to see whether further optimizations of the type would be fruitful.

**Comment by xtqqczze** [comment]
We now have `CA1852` in .NET 7, so we should try to enable it.

**Comment by xtqqczze** [comment]
@iSazonov Could you please reopen?

**Comment by xtqqczze** [comment]
#21164 contributes to this issue.
