### ISSUE TITLE
Get-Process -Module fails to stop when piped to Select-Object -First

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15117]
It seems that when `Select-Object -First` tries to stop upstream pipeline input, `Get-Process -Module` doesn't handle this request properly and emits many spurious error messages.

## Steps to reproduce

```powershell
Get-Process -Module  -Id $PID -ev errs | Select-Object -First 1 
$errs.Count | Should -Be 0
```

## Expected behavior

No errors should occur, and the test should succeed.

## Actual behavior

Error message `Get-Process: Cannot enumerate the modules of the "pwsh" process.` is (wrongly) emitted (without `Select-Object -First`, the command succeeds), and the test fails:

```none
InvalidResult: Expected 0, but got 1.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.4
```

**Comment by SeeminglyScience** [comment]
Problem is here:

https://github.com/PowerShell/PowerShell/blob/be7d36603d1cc60abd4e8e738ead8f437b7869fa/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L591-L630

Either the scope of the `try` needs to not include `WriteObject`, or another clause for `FlowControlException` should be added that rethrows.
