### ISSUE TITLE
Improve the error messages resulting from attempting to modify read-only .NET types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15118]
## Summary of the new feature/enhancement

Attempting to modify an instance of a _read-only_ .NET data type should indicate in the error message resulting from the failed attempt that the data type is indeed read-only.

From the current error messages (as of PowerShell Core 7.2.0-preview.4) this is hard to infer:

Given the following dictionary:

```powershell
$readOnlyDict =
    [System.Collections.ObjectModel.ReadOnlyDictionary[string, string]]::new(
      [System.Collections.Generic.Dictionary[string, string]]::new()
    )
```

Here are the - unhelpful - error message currently being emitted:

```powershell
# Note that *getting* a value works fine.
PS> $readOnlyDict['foo'] = 'bar'
InvalidOperation: Unable to index into an object of type "System.Collections.ObjectModel.ReadOnlyDictionary`2[System.String,System.String]".

# Note that the .method *does* exist, due to interface implementations.
PS> $readOnlyDict.Add('foo', 'bar')
MethodException: Cannot find an overload for "Add" and the argument count: "2".

# Note that the .method *does* exist, due to interface implementations.
PS> $readOnlyDict.Clear()
MethodException: Cannot find an overload for "Add" and the argument count: "2".
```

Only using _dot notation_, which uses a different code path, currently provides a helpful error message: 

```powershell
PS> $readOnlyDict.foo = 'bar'
OperationStopped: Collection is read-only.
```

**Comment by daxian-dbw** [comment]
For `$readOnlyDict['foo'] = 'bar'`, I agree the error message could be improved. The C# compilation error for the same statement is 
> Property or indexer 'ReadOnlyDictionary<string, string>.this[string]' cannot be assigned to -- it is read only

But for the other 2 examples `$readOnlyDict.Add('foo', 'bar')` and `$readOnlyDict.Clear()`, they are explicit interface implementation and thus are not directly available on the class. Therefore, powershell cannot find them and the error message is appropriate. The C# complication error is also essentially "cannot find it":
> 'ReadOnlyDictionary<string, string>' does not contain a definition for 'Add' and no accessible extension method 'Add' accepting a first argument of type 'ReadOnlyDictionary<string, string>' could be found (press F4 to add an assembly reference or import a namespace)

**Comment by mklement0** [comment]
Glad to hear you agree on the first message, but let me revisit your argument regarding the other two:

PowerShell surfaces the methods of even explicit interface implementations _implicitly_, and note that the error message doesn't indicate that it cannot _find_ the method(s) (it can, as `$readOnlyDict.Add` reveals), but (falsely) suggests that there's a problem with either the count or the type of the _arguments_, which is _not_ true.

This is analogous to calling the `IList.Add()` method implicitly available on arrays, where a meaningful error message _is_ provided:

```powershell
# OK (meaningful error message "Collection was of a fixed size.")
@(1, 2).Add(3)
```
