### ISSUE TITLE
Alias for COMPARE => compare-object is not set

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#1511]
Steps to reproduce
------------------
gal compare

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by andschwa** [comment]
This was removed because it conflicts with `/usr/bin/compare`.

**Comment by andschwa** [comment]
Particularly took place in https://github.com/PowerShell/PowerShell/commit/7d9f43966690aa69fea1735af24106858ee4199a.
