### ISSUE TITLE
Not update Environment variable list, after add new environment item

### ISSUE THREAD

**Issue by LutAle** [PowerShell/PowerShell#15112]
## Steps to reproduce

```powershell
# add new environment in Environment stack 
[System.Environment]::SetEnvironmentVariable("e1",'ss',[System.EnvironmentVariableTarget]::user)

```

## Expected behavior

```none
#new environment present in environment stack
#get Environment list
[System.Environment]::GetEnvironmentVariables()

```

## Actual behavior

```none
# New environment missing in listing, but present in
Get-CimInstance Win32_Environment
```

## Environment data

```none
PSVersion                      7.2.0-preview.4
PSEdition                      Core
GitCommitId                    7.2.0-preview.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Steg17** [comment]
Test

**Comment by vexx32** [comment]
This is just how the .NET methods and the OS in general work, PowerShell has no control over this. If you set an environment variable in the User scope, it will not affect the current process's local environment variables, but it will usually affect new process's environment variables.

If you set a environment variable to the Machine scope, you may even need to restart the machine or log off and back on before it will be applied.

If you want to set the environment variable in the current process's environment scope as well, you'll need to set it at the `Process` scope, and/or use PowerShell's `$env:` provider to set the value for the local process, e.g., `$env:e1 = 'ss'`
