### ISSUE TITLE
Add `-configurationfile` parameter to `pwsh`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#15120]
## Summary of the new feature/enhancement

`pwsh -configurationname` will take a session configuration name to restrict a PowerShell session, but depends on remoting (specifically WinRM).  It would be useful to have a `-configurationfile` to take a pssc and create a restricted session for that process.  This is not a security boundary, but could make it useful for testing configuration files and allow using them on Linux if `pwsh` is instantiated by something other than directly by the user.

**Comment by TravisEz13** [comment]
Security working group: This seems reasonable.  Session configuration is per end point.  This should not override existing session configuration.

**Comment by PaulHigin** [comment]
WG-Security:
We feel this is potentially useful, but that it is not important for 7.2, and should be moved to 7.3 consider.
