### ISSUE TITLE
Bash Style Tab Completion

### ISSUE THREAD

**Issue by jake9wi** [PowerShell/PowerShell#15126]
### Current Behavior.
When I begin to type a file name and hit tab powershell autocompletes to the entire name of the first matching file.

### Desired Behavior.
In Bash if I have the file list:

- init-py38-emwin.ps1
- init-py39-emwin.ps1

And I type `.\i [tab]` then bash would complete to `.\init-py3` and wait for more input.

### Why is this Behavior Better?

With the current powershell style tab completion if I have lots of files with similar names then I have tab through many files to get the one I want. Bash style tab completion would result in time saved.

**Comment by kilasuit** [comment]
This is provided in [PSReadline](https://github.com/PowerShell/PSReadline) which enhances the out of the box experiences.

If you instead of `Tab` use `Ctrl` +` Shift` instead then you'd get the experience you are actually looking for.

You can also add additional key bindings via PSReadline too.

**Comment by vexx32** [comment]
There's probably a setting for it, afaik that's the default tab completion mode on non-Windows OSes. I usually just change the keybind to MenuComplete, but it seems there is that tab complete mode available.

**Comment by 237dmitry** [comment]
> If you instead of Tab use Ctrl + Shift instead then you'd get the experience you are actually looking for.

Still would find this combination

```
 > (Get-PSReadLineKeyHandler).key | sls '(Ctrl\+Shift)|(Shift\+Ctrl)' -raw

Shift+Ctrl+Enter
Shift+Ctrl+LeftArrow
Shift+Ctrl+RightArrow

 > (Get-Module PSReadLine).Version.ToString()
2.1.0                                        
```

**Comment by SeeminglyScience** [comment]
Try this:

```powershell
Set-PSReadLineKeyHandler -Chord Tab -Function Complete
```

> Why is this Behavior Better?

It's all preference based on what you're used to. That's why the default is different per platform.

**Comment by jake9wi** [comment]
> 
> 
> Try this:
> 
> ```powershell
> Set-PSReadLineKeyHandler -Chord Tab -Function Complete
> ```

Doing this worked.
