### ISSUE TITLE
Tab expansion works unexpectedly for files containing [square brackets] in the name

### ISSUE THREAD

**Issue by agr** [PowerShell/PowerShell#15129]
## Steps to reproduce

```powershell
"Hello, World" | Out-File -LiteralPath "[foo]bar.txt"
Get-Item [foo<tab>
Get-Item `[foo<tab>
Get-Item ``[foo<tab>
```

`<tab>` above denotes user pressing the Tab key trying to invoke tab expansion.

## Expected behavior

After pressing the Tab key entered string expands to a `[foo]bar.txt` filename, potentially properly escaped.

## Actual behavior

Nothing happens

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Additional details

If I type `Get-Item *.txt` and press tab, the command expands to 
```
Get-Item '.\`[foo`]bar.txt'
```
however, if I immediately delete some characters in the expanded filename with escaping and press Tab (which, I imagine, would restore deleted characters), again, nothing happens.

If I type `Get-Item "*.txt"` and press Tab, it expands to `Get-Item ".\``[foo``]bar.txt"`, but if I delete some characters and press Tab, nothing happens.

If I type `Get-Item '``[` and press Tab, it expands to 
```
Get-Item '.\`[foo`]bar.txt'
```
i.e. it seems to work, but that's totally unexpected and unintuitive: why do I have to type two backticks and have the expansion immediately remove one, yet when there is one, expansion does not work?

Similar, with double quotes: `Get-Item "````[` gets expanded to `Get-Item ".\``[foo``]bar.txt"`. Same concern as above. I would expect some consistency.

`Get-Item ````[` also works.

**Comment by agr** [comment]
Looks like it is fixed in 7.4.0 at least in Windows. Will verify later in other OSes.

**Comment by agr** [comment]
Verified on Linux and MacOS. 

However, it works inconsistently depending on what command we are trying to run:

```
Get-Item [foo<tab>
```
expands to
```
Get-Item '.\`[foo`]bar.txt'
```
but
```
notpad [foo<tab>
```
expands to
```
notepad .\[foo]bar.txt
```
Note no apostrophes and escaping, but if I run that command, notepad opens requested file just fine, so it might not have a functional impact (or can even be by design). If that's the case, I think this issue can be closed.
This seems to be related to https://github.com/PowerShell/PowerShell/issues/14015.

**Comment by agr** [comment]
Actually, it doesn't fully work. Try this:

```powershell
mkdir '[foo]bar'
cd '.\`[foo`]bar\'
New-Item -Type File '[foo]bar.txt'
cd ..
```

Now, typing `dir [foo<tab><tab>` (tab twice, yes!) would properly expand to
```powershell
dir '.\`[foo`]bar\`[foo`]bar.txt'
```
and we're good, but typing `notepad.exe [foo<tab><tab>` expands to `notepad.exe .\[foo]bar\` on the first tab press and does nothing on the second.

**Comment by sdwheeler** [comment]
Command line parsing changes after the occurrence of a native (non-PowerShell) command. Arguments to the native command are treated as literal strings.

**Comment by theJasonHelmick** [comment]
Thank you @agr -- This is an interesting issue and it is by design -- working as expected.  The issue is that PowerShell commands are treated a little different than a native command.  The tab completion completes  PowerShell commands by escaping wildcard input, for native commands, it responds with the path as is.
