### ISSUE TITLE
Support hex values for console colors

### ISSUE THREAD

**Issue by brunovieira97** [PowerShell/PowerShell#15133]
## Summary of the new feature/enhancement

Support hex color strings as values for console colors, such as `Write-Host`'s `-ForegroundColor` and `-BackgroundColor`.

Specially since PowerShell is now multi-platform, I consider it'd benefit from using a more standardized way of passing colors, not being limited to the default 16-color table from legacy code. Windows now offers Windows Terminal, which also doesn't interact with the old Console Colors functionality from Conhost.

Maybe backwards compatibility could be maintained by using the old school strings from Conhost as aliases for the actual hex values? Something like `White -> #FFFFFF`.

Is this even possible to implement?

**Comment by 237dmitry** [comment]
> using a more standardized way of passing colors

RGB Escape Sequences maybe? 
```
Write-Host "`e[38;2;255;255;255;48;2;255;0;0mWhite on Red`e[0m"
```

**Comment by brunovieira97** [comment]
Sure, I know that's possible, but adding this directly to the parameters would be much better for the user (dev, etc).

That's the reason I proposed the implementation of a more ubiquous way of using colors lol

**Comment by SeeminglyScience** [comment]
This was added recently in the form of the `$PSStyle` variable:

```powershell
"$($PSStyle.Background.FromRgb(255, 0, 0))$($PSStyle.Foreground.FromRgb(0xFFFFFF))Testing$($PSStyle.Reset)"
```

**Comment by bpayette** [comment]
The way to specify hex values in PowerShell is with the `0x` prefix i.e. 0xf3d and specifying a hex value  as a color for `Write-Host` already works:
```powershell
Write-Host -ForegroundColor 0x6 "Hi there"
```
BUT the type of `-ForegroundColor` itself is a problem. It's an enum `System.ConsoleColor` that already defines a (small) set of  numeric values for colors. The reason you can use color names as arguments is that the parameter binder type converter looks up the  member name on the enum then substitutes the corresponding integer value. For example `White` has the numeric value 0x0f not the RGB value 0xffff. So supporting RGB colors with the existing parameters would be a breaking change. I suppose a new parameter `-ForegroundColorRGB` could be added if you want more colors but the advantage of the current setup is that it's broadly portable.

**Comment by brunovieira97** [comment]
I ended up writing a custom function on my PowerShell module that will work with either hex and `System.ConsoleColor` names as a value for `-ForegroundColor`.

I then check if it's one of the standard colors, or if it matches a hexadecimal color regex, and then transform it to RGB escape sequences to add to the text I want to write. 

It's a workaround, of course, as native support for `#ffffff` as a color would be much appreciated. Anyway, my needs are met for the time being.

Please, keep looking into this as a future improvement, it'd be awesome to just pass a hex string to Write-Host!

**Comment by terryaney** [comment]
@brunovieira97 Have a sample of your custom function? :)

**Comment by brunovieira97** [comment]
@terryaney sure, here it is: https://github.com/brunovieira97/ps-color/blob/main/src/util/Color.ps1

What I did was map the default hex values for each System.ConsoleColor, and just use everything as a hexadecimal value.

It's not the most fancy solution, but it gets the job done 😆

**Comment by SteveL-MSFT** [comment]
$PSStyle.Foreground.FromRgb() and $PSStyle.Background.FromRgb() resolves this
