### ISSUE TITLE
The `-UseSSL` flag is not supported on Linux

### ISSUE THREAD

**Issue by blochl** [PowerShell/PowerShell#15137]
## Steps to reproduce

```powershell
$ip = "X.X.X.X"
Enter-PSSession -ComputerName $ip -Authentication Negotiate -ConfigurationName Minishell -Credential ~\EdgeUser -UseSSL
```

## Expected behavior

Connection established to a remote PSSession.

## Actual behavior

```none
Enter-PSSession: HTTPS on Unix does not currently support CA or CN checks. Use the PSSessionOption -SkipCACheck and -SkipCNCheck if you are certain you trust the server you are connecting to and the network in between.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
We could follow the message recommendations - Use the PSSessionOption -SkipCACheck and -SkipCNCheck if you are certain you trust the server you are connecting to and the network in between.

**Comment by blochl** [comment]
> We could follow the message recommendations - Use the PSSessionOption -SkipCACheck and -SkipCNCheck if you are certain you trust the server you are connecting to and the network in between.

And what if I don't trust the server I am connecting to or the network in between? I guess the issue here is "HTTPS on Unix does not currently support CA or CN checks".

**Comment by jborean93** [comment]
> And what if I don't trust the server I am connecting to or the network in between?

You cannot use the built in version included with PowerShell as the verification functionality was never implemented. You can look at using [PSWSMan](https://www.powershellgallery.com/packages/PSWSMan/) which is a fork of the WSMan library and included TLS verification that is missing from the built in version. Note that you still need to specify `-SessionOption (New-PSSessionOption -SkipCACeck -SkipCNCheck)` in PowerShell but rest assured cert validation still happens. When PowerShell 7.2 is out those session options aren’t mandatory when you use this fork but older versions still require them to be set.
