### ISSUE TITLE
Native support for Mac m1

### ISSUE THREAD

**Issue by rstolpe** [PowerShell/PowerShell#15146]
Is it on the roadmap?

**Comment by iSazonov** [comment]
It was started in #14923. Now need add steps in release process.

/cc @anmenaga @SteveL-MSFT

**Comment by dustinmoris** [comment]
OMG how is this issue not closed yet? The M1 chip has been out for so many months now. How come there is not even a preview yet with native support like there is at least one for .NET 6, which by the way is also super freaking slow in supporting this new architecture. Quite disappointing and frustrating that Microsoft operates so rigid and inflexible to industry changes. Honestly, in case this was not totally fucking obvious to Microsoft, but Arm chips like the M1 are the future of computer chips so it's really mind blogging that Microsoft is yet again so blind and late in recognising that and lagging behind with the innovation that is happening around them.

**Comment by rstolpe** [comment]
> OMG how is this issue not closed yet? The M1 chip has been out for so many months now. How come there is not even a preview yet with native support like there is at least one for .NET 6, which by the way is also super freaking slow in supporting this new architecture. Quite disappointing and frustrating that Microsoft operates so rigid and inflexible to industry changes. Honestly, in case this was not totally fucking obvious to Microsoft, but Arm chips like the M1 are the future of computer chips so it's really mind blogging that Microsoft is yet again so blind and late in recognising that trend and lagging behind with the innovation that is happening around them.

I agree, they should have solved this / migrated this to universal binary long time ago. VsCode etc. are already there.
