### ISSUE TITLE
Power Distribution Support Request

### ISSUE THREAD

**Issue by iga1976** [PowerShell/PowerShell#15144]
## Details of the Distribution

- Name of the Distribution:   Linux PowerPC
- Version of the Distribution:  Debian 8 ("jessie"), ppc64el   Little Endian
- Package Types
    - [ X ] Deb
    - [ ] RPM
    - [ ] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request):   power
- The following is a requirement for supporting a distribution **without exception.**
    - [ ] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
We have an automation framework that allows us to chose the type of language to code (Java, Python, Perl, PowerShell).
However, when one of this is chosen we have to care for portability, and Powershell is not running on other architectures like AIX and Linux on power pc or z systems, Linux PPC, HP ia64, os390, etc. In general any other than x64, Arm32, Arm64. Do you really support all of these architectures x64, Arm32, Arm64 ?
    - [ ] The version of the Distribution is supported for at least one year.
    - [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [ ] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by rjmholt** [comment]
>  The version and architecture of the Distribution is supported by .NET Core.

Unfortunately, it doesn't look like .NET supports the PowerPC architecture. See https://github.com/dotnet/runtime/issues/13277.

**Comment by rjmholt** [comment]
Closing this request for official support, as .NET does not yet support this architecture. Please note that PowerShell has a number of community-supported distributions as well.
