### ISSUE TITLE
Get-Counter shows wrong CPU usage

### ISSUE THREAD

**Issue by francesco1119** [PowerShell/PowerShell#15155]
## Steps to reproduce

1. Open Task Manager
2. Run `Get-Counter -Counter "\Processor(_Total)\% Processor Time" -Continuous`
3. `Get-Counter` shows a 5-10% discrepancy with Task Manager

## Expected behavior

`Get-Counter` should show the right CPU usage

## Actual behavior

`Get-Counter` is showing a good 5-10% discrepancy with Task Manager CPU consumption. 

![Test2](https://user-images.githubusercontent.com/3397477/113520787-e172e080-9595-11eb-991d-8d41e52e0fea.gif)

This is particularly bad because  `Get-Counter`  is the official command that [Microsoft suggest for DTU calculation](http://dtucalculator.azurewebsites.net/) before migrating to Azure SQL DB. 
Check the PowerShell script on the same page.
This means that DTU calculation is possibly suggested with a good 5-10% of error. 

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19035.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19035.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by fMichaleczek** [comment]
@francesco1119  I don't understand your issue. 
![image](https://user-images.githubusercontent.com/6187529/113825576-6ff78580-9781-11eb-9365-d5178e81d79d.png)

**Comment by francesco1119** [comment]
Thank you @fMichaleczek , with a higher update rate the results are much closer. 

I think it works as intended.
