### ISSUE TITLE
On Windows, a directory symlink doesn't behave a like a directory with Get-ChildItem if its target path is a relative path that starts directly with a name

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15161]
Note: This is ultimately a duplicate of #15235

---

PR #8783 brought the ability to use _relative_ paths as symlink targets _on Windows_.

However, if the target is a _directory_ and the relative path starts with / is just a _name_ (rather than starting with `.\`), the resulting symlink doesn't behave like a directory with `Get-ChildItem`.

Note that on _Unix_, as of PowerShell Core 7.2.0-preview.4, use of relative target paths is still fundamentally unsupported - see #15233

## Steps to reproduce

Run on Windows:

```powershell
# Switch to a temporary directory.
Push-Location -ea Stop ($tmpDir = (New-Item -Type Directory -Force (Join-Path Temp:/ $PID)).FullName)

# Create a dir. to serve as the target, with a single text file in it.
$null = New-Item -Type Directory target -Force
'hi' > target/t.txt

# Define two links: 
#  * one that targets 'target' - by name only.
#  * one that targets '.\target' - explicit reference to the current dir.
$null = New-Item -Type SymbolicLink link1 -Target target -Force
$null = New-Item -Type SymbolicLink link2 -Target .\target -Force

# Now compare the Get-ChildItem behavior of these two links, which
# *should* be the same.
Get-ChildItem link1
Get-ChildItem link2

Pop-Location; Remove-Item -lp $tmpDir -Recurse
```

## Expected behavior

With the exception of the directory path in the grouping header, the commands should produce the same output and show the _content_ of the target dir:

```none
    Directory: C:\Users\jdoe\AppData\Local\Temp\8748\link1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            4/5/2021  3:30 PM              4 t.txt

    Directory: C:\Users\jdoe\AppData\Local\Temp\8748\link2

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            4/5/2021  3:30 PM              4 t.txt
```

## Actual behavior

```none
    Directory: C:\Users\jdoe\AppData\Local\Temp\8748

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---            4/5/2021  3:30 PM              0 link1 -> target

    Directory: C:\Users\jdoe\AppData\Local\Temp\8748\link2

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            4/5/2021  3:30 PM              4 t.txt
```

Note how `link1` present as if it were a _flle_, as if you had called `Get-Item` rather than `Get-ChildItem` on it.

Interestingly, `cmd.exe`'s `dir` shows analogous behavior, and additionally fails with `dir link1\t.txt`, which PowerShell handles correctly.

## Environment data

```none
PowerShell Core v7.2.0-preview.4 (.NET 6.0.0-preview.2.21154.6) on Microsoft Windows 10 Pro (64-bit; Version 20H2, OS Build: 19042.867)
```

**Comment by MatejKafka** [comment]
I'm not sure if this is the same underlying issue, but I found a related one.

```
mkdir ./test
mkdir ./test/dir
ni -Type SymbolicLink ./test/dir_link -Target ./dir
```
The created symlink doesn't work, as it thinks it's a file symlink.

**Underlying issue:**
1) It seems that implementation of `New-Item` checks whether target is a file or a directory and changes the type of symlink based on what it finds. When a symlink is marked as a file, and it points to a directory, it's not usable (cannot be traversed).

2) .NET often has different working directory from PowerShell (usually the original working directory when the pwsh process started, which is typically `C:\Windows\System32`).

3) The target type checking code from 1) uses .NET APIs, and it does not resolve the path, so it ends up checking the target path relative to something like `C:\Windows\System32`, where it usually fails and then falls back to creating a file symlink. When the actualy target is a directory, this results into an unusable symlink.

**Comment by 237dmitry** [comment]
I did not understand what the problem is.

![11](https://user-images.githubusercontent.com/78153320/114907610-ed776180-9e23-11eb-8048-7bf734a1510b.png)

**Comment by mklement0** [comment]
@237dmitry, if you run the code in the initial post, you'll see the problem.

It doesn't _always_ happen, but I've just realized that the underlying cause is the same as what @MatejKafka reported in #15235, so I'm closing this.

In short: if there's a mismatch between the _process_' current directory (as reported by `[Environment]::CurrentDir`) and _PowerShell's_ (which is typically the case), the symlink target's _type_ (file vs. directory) may be mis-identified.

In the case at hand, `target` - but not `.\target` - is mistakenly looked for in `[Environment]::CurrentDir` and, if there's no such item there, it is assumed to be a _file_, so that the `link1` symlink is created _with the wrong type_ (it behaves like a _file_, even though its true target is a _directory).
