### ISSUE TITLE
Remove-CalendarEvents cmdlet on Exchange Online throws exception: "String was not recognized as a valid DateTime"

### ISSUE THREAD

**Issue by FunkEinstein** [PowerShell/PowerShell#15169]
Seems that problem appears only for Remove-CalendarEvents cmdlet when we set its QueryStartDate parameter.
We have tested Set-Mailbox with StartDateForRetentionHold and EndDateForRetentionHold parameters and Set-MailboxAutoReplyConfiguration with -StartTime and -EndTime and these cmdlets worked just fine. For all cmdlets we have specified dates as object of DateTime type but error appears only for Remove-CalendarEvents.
Problem happens on different time formats, we have tested United Kingdom(dd/MM/yyyy) and Unkrainian(dd.MM.yyyy) formats and it seems that problem appears when day part is in the first place. Everything is ok when we using United Sates(M/d/yyyy) format.

We tried creating dates in different ways:
$date = Get-Date -Date "27.08.2020"
$date = [System.DateTime]::Parse("27.08.2020")
We even tried to specify the kind of days created, but that didn't change anything.

**Full error:**
Error on proxy command 'Remove-CalendarEvents -Identity:'<identity>' -CancelOrganizedMeetings:$True 
-Confirm:$False -QueryStartDate:'27/08/2020 00:00:00' -QueryWindowInDays:'1825'' to server 
VI1PR06MB5152.eurprd06.prod.outlook.com: Server version 15.20.3999.0000, Proxy method PSWS: 
Cmdlet error with following error message:
System.Management.Automation.ParentContainsErrorRecordException: Cannot process argument transformation on parameter 
'QueryStartDate'. Cannot convert value "27/08/2020 00:00:00" to type "Microsoft.Exchange.ExchangeSystem.ExDateTime". Error: 
"String was not recognized as a valid DateTime.".

**Environment :**
**PSVersion:** 5.1.17763.1490
**PSEdition:** Desktop
**PSCompatibleVersions:** {1.0, 2.0, 3.0, 4.0...}
**BuildVersion:** 10.0.17763.1490
**CLRVersion:** 4.0.30319.42000
**WSManStackVersion:** 3.0
**PSRemotingProtocolVersion:** 2.3
**SerializationVersion:** 1.1.0.1

**Comment by vexx32** [comment]
The type it's trying to convert to indicates this is an issue specifically with the MS Exchange Online module and the types it provides. Not sure why they don't use the .NET standard datetime / datetimeoffset, but there's nothing PowerShell itself can really do here.

Judging by the call stack, the conversion it's trying to do is a custom implementation.

**Comment by FunkEinstein** [comment]
Thank you for answer.

> The type it's trying to convert to indicates this is an issue specifically with the MS Exchange Online module and the types it provides. Not sure why they don't use the .NET standard datetime / datetimeoffset, but there's nothing PowerShell itself can really do here.

Yes, something strange is happening here but I don't see any problems on my side. 

> Judging by the call stack, the conversion it's trying to do is a custom implementation as well using ArgumentTransformationAttribute. Not sure where best to chase this one up. 🤔 @SteveL-MSFT is there a good channel to use for Exchange Online issues?

I've just tested this case on another computer and it wasn't reproduced. I don't fully sure that problem is only in version of powershell but I have performed the same actions as on the first computer.
Environment:
**PSVersion:** 5.1.17134.407
**PSEdition:** Desktop
**PSCompatibleVersions:** {1.0, 2.0, 3.0, 4.0...}
**BuildVersion:** 10.0.17134.407
**CLRVersion:** 4.0.30319.42000
**WSManStackVersion:** 3.0
**PSRemotingProtocolVersion:** 2.3
**SerializationVersion:** 1.1.0.1

**Comment by iSazonov** [comment]
The repository is for PowerShell Core only. Please use other channels to report issues for Windows PowerShell and Exchange Online - UserVoice site, forums, support service and so on.
