### ISSUE TITLE
PowerShell.Stop() behaviour causes very different results between PowerShell.Invoke() and PowerShell.InvokeAsync()

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15173]
## Steps to reproduce

```csharp
[Cmdlet(VerbsLifecycle.Invoke, "Example")]
public class InvokeScriptCommand : PSCmdlet
{
    [Parameter]
    public SwitchParameter Async { get; set; }

    protected override void EndProcessing()
    {
        using (var powershell = PowerShell.Create())
        {
            powershell.AddScript("1;2;3;sleep 10;4;5;6");

            Task<IList<PSObject>> task = null;
            if (Async)
            {
                task = RunAsync(powershell);
            }
            else
            {
                task = Run(powershell);
            }

            Thread.Sleep(2000);

            powershell.Stop();

            foreach (PSObject result in task.GetAwaiter().GetResult())
            {
                Console.WriteLine(result);
            }
        }
    }

    private Task<IList<PSObject>> RunAsync(PowerShell powershell)
    {
            return powershell.InvokeAsync()
                .ContinueWith(psTask =>
                {
                    return (IList<PSObject>)psTask.Result;
                });
    }

    private Task<IList<PSObject>> Run(PowerShell powershell) => Task.Run(() => (IList<PSObject>)powershell.Invoke());
}
```

```powershell
> Invoke-Example -Async
Invoke-Example: One or more errors occurred. (The pipeline has been stopped.)

> Invoke-Example
1
2
3
```

## Expected behavior

Both the async and sync executions should do the same thing.

## Actual behavior

The sync execution returns a partial result and the async execution throws a `PipelineStoppedException`.

~~What's more, when a `PSDataCollection<PSObject>` is passed into the `InvokeAsync()` call, no results are ever inserted and the `DataAdding` and `DataAdded` events are never fired.~~ I passed my collection to the `input` parameter; passing it to the `output` parameter works...

## Environment data

This is with the PowerShell 7.2.0-preview.4 (both as a standalone app with the SDK and as a cmdlet with the exe).

**Comment by daxian-dbw** [comment]
> when a `PSDataCollection<PSObject>` is passed into the `InvokeAsync()` call, no results are ever inserted and the `DataAdding` and `DataAdded` events are never fired.

The `System.Management.Automation.PSDataCollection[TOutput] output` parameter seems to work as expected from the below snippet. This is with `7.2.0-preview.4`.

```
PS:1> $ps = [powershell]::Create()
PS:2> $out = [System.Management.Automation.PSDataCollection[psobject]]::new()
PS:3> $ps.AddScript("1;2;3;sleep 90;4;5;6") > $null
PS:4> $a = $ps.InvokeAsync([System.Management.Automation.PSDataCollection[psobject]]$null, $out); sleep 2; $ps.Stop()
PS:5> $out
1
2
3
PS:6>
```

As for the

**Comment by daxian-dbw** [comment]
`PowerShell.Invoke` handles `PowerShell.Stop` in the same way as how <kbd>Ctrl+c</kbd> is handled in PowerShell console: the `PipelineStoppedException` is ignored [when the pipeline was stopped](https://github.com/PowerShell/PowerShell/blob/49288e4289dc46a28bac79ff89257e744ff55a25/src/System.Management.Automation/engine/hostifaces/pipelinebase.cs#L398-L401).

The api `PowerShell.Invoke` is used as the _primary pipeline_ for many interactive hosts that are built on top of PowerShell packages (e.g. powershell sub-kernel in .NET interactive). For such a host, it's important to act similarly to the PowerShell console, including how <kbd>Ctrl+c</kbd> is handled (the implementation of which would be very likely just calling `PowerShell.Stop`). From this perspective, it seems reasonable for `PowerShell.Invoke` to behave exactly the same as a `LocalPipeline` in PowerShell console.

`PowerShell.InvokeAsync` ( wrapper over `PowerShell.BeginInvoke/EndInvoke`) is for advanced asynchronous scenarios. I think throwing `PipelineStoppedException` makes perfect sense for this API, as I need to know whether my task succeeded or failed, and for what reason if it failed.

We probably cannot afford any breaking changes in either of these 2 APIs. I think what we can do is to add a `<remark>` section to the XML document for those 2 APIs, to describe their behaviors when dealing with `Stop`.

--------------------------------------------

> when a `PSDataCollection<PSObject>` is passed into the `InvokeAsync()` call, no results are ever inserted and the `DataAdding` and `DataAdded` events are never fired. Am I missing something?

The `System.Management.Automation.PSDataCollection[TOutput] output` parameter seems to work as expected from the below snippet. This is with `7.2.0-preview.4`.

```
PS:1> $ps = [powershell]::Create()
PS:2> $out = [System.Management.Automation.PSDataCollection[psobject]]::new()
PS:3> $ps.AddScript("1;2;3;sleep 90;4;5;6") > $null
PS:4> $a = $ps.InvokeAsync([System.Management.Automation.PSDataCollection[psobject]]$null, $out); sleep 2; $ps.Stop()
PS:5> $out
1
2
3
PS:6>
```

**Comment by rjmholt** [comment]
Thanks @daxian-dbw this is exactly the information I was looking for.

I've realised my original issue statement has a flaw in it where I didn't use the `PSDataCollection` properly (used as the wrong argument), so will update that.

But I think the `remarks` addition would be useful

**Comment by daxian-dbw** [comment]
@rjmholt Since you are going to submit the XML doc PR, I will assign this issue to you :)
Note that, you may need to update the XML document for `PowerShell.EndInvoke` as well, it's essentially what `PowerShell.InvokeAsync` does.
