### ISSUE TITLE
Array filtering with -like vs. match: -match passes the matching objects through, -like stringifies them

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15172]
Note:
* Fixing this inconsistency is likely too much of a breaking change; if so, we should document it.

With an array (collection) as the LHS, both `-like` and `-match` (among others) act as _filters_, i.e. they return a sub-array of those elements that match.

Both operators accept _non-string_ elements in the array, in which case the same stringification as in expandable strings (string interpolation) is performed (essentially, simple `.ToString()` stringification) for the purpose of _matching_.

The inconsistency is that:

* `-match` returns the _original objects_ whose string representations matched in the sub-array
* whereas `-like` returns the _string representations_

## Steps to reproduce

```powershell
# Input array (single-element, for simplicity
$a = , [pscustomobject] @{ one = 1; two = 2; three = 3 }

# Note: The  stringified representation of this object is:
#     '@{one=1; two=2; three=3}'
# and this is what is matched against.

' -- -match'
$a -match 'one=' | select { $_ }, { $_.GetType().Name }

' -- -like'
$a -like '*one=*' | select { $_ }, { $_.GetType().Name }
```

## Expected behavior

```none
# -match

 $_                       $_.GetType().Name 
----                     -------------------
@{one=1; two=2; three=3} PSCustomObject

# -like
@{one=1; two=2; three=3} PSCustomObject
```

That is, in both cases the matching input object should be passed through as-is.

## Actual behavior

```none
# -match

 $_                       $_.GetType().Name 
----                     -------------------
@{one=1; two=2; three=3} PSCustomObject

# -like
@{one=1; two=2; three=3} String
```

That is, `-like` returned the _string representation_ of the matching input object rather than the object itself.

## Environment data

```none
PowerShell Core 7.2.0-preview.4
```

**Comment by rkeithhill** [comment]
WG-Engine discussed this today.  This is unfortunate but we believe this bug doesn't meet the bar for introducing a breaking change.  We do believe this behavior should be documented. A PowerShell-Docs issue has been submitted: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9987.
