### ISSUE TITLE
Distribution Support Request for CentOS7

### ISSUE THREAD

**Issue by osakanataro** [PowerShell/PowerShell#15179]
## Details of the Distribution

- Name of the Distribution:CentOS
- Version of the Distribution:7
- Package Types
    - [ ] Deb
    - [X] RPM
    - [ ] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request):x86_64
- The following is a requirement for supporting a distribution **without exception.**
    - [ ] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [ ] The version of the Distribution is supported for at least one year.
    - [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [ ] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

I want to use "Microsoft Build of OpenJDK" and PowerShell on CentOS7.
OpenJDK is used https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
Powershell is used https://packages.microsoft.com/config/rhel/7/prod.repo
But CentOS7's repositry is not include powershell.
CentOS7's repositry have powershell-preview 7.0.0_preview.3 only.
Please update CentOS7 repository

**Comment by iSazonov** [comment]
> CentOS7's repositry have powershell-preview 7.0.0_preview.3 only.

There is all supported versions
https://packages.microsoft.com/rhel/7/prod/

**Comment by osakanataro** [comment]
"[Install Microsoft Build of OpenJDK on RPM-Based Linux](https://www.microsoft.com/openjdk/linux-installer)" said follows
```
for CentOS 7
sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
```
```
$ cat /etc/yum.repos.d/microsoft-prod.repo
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/centos/7/prod
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
sslverify=1
$
```

But PowerShell Document "[Installing PowerShell on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1)" said 
```
for CentOS
# Register the Microsoft RedHat repository
curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
```
```
$ cat /etc/yum.repos.d/microsoft.repo
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/rhel/7/prod/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

Repository name are same.
Both product are managed by Microsoft
rhel7's repository have "powershell", no "msopenjdk"
centos7's repository have "msopenjdk", no "powershell"
I want to use both product.

**Comment by iSazonov** [comment]
> But PowerShell Document "[Installing PowerShell on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1)" said

I believe you should follow the document to install PowerShell.
Then you could request to update OpenJDK documentation.

**Comment by rioriost** [comment]
You can install both of them after editing the repo file for rhel7, 'Microsoft.repo',

[packages-microsoft-com-prod-rhel7]
name=packages-microsoft-com-prod-rhel7
...

$ yum -y install powershell msopenjdk-11

**Comment by osakanataro** [comment]
Why don't powershell provide by centos repository?

**Comment by iSazonov** [comment]
I think the intention is to reduce the number of distributions. Over time, I believe the major vendors will include this in their repositories.
