### ISSUE TITLE
$switch variable inconsistent behavior

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#15185]
The `$switch` variable does not work in combination with `-file` or when the input is pipeline output.

## Steps to reproduce

`$switch` enumerator works as expected for an array input:

```powershell
    $testData = 1, 2, 3, 4
    $switchIsNull = $true

    $output = switch ($testData) {
        (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
              $switch.Current
            }
        }
    }
    
    PS> $switchIsNull
    False   ## $switch was set
    PS> $output
    2
    3
```

`$switch` enumerator is unset for a file input:

```powershell
    $testData = 1, 2, 3, 4
    $switchIsNull = $true

    Set-Content -LiteralPath 'InputData.txt' -Value $testData
    $output = switch -File InputData.txt {
        (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
                $switch.Current
            }
        }
    }
    Remove-Item InputData.txt

    PS> $switchIsNull
    True  ## $switch was not set
    PS> $output
    2
```

`$switch` enumerator is not retrieved for a list input:

```powershell
    $testData = 1, 2, 3, 4
    $switchIsNull = $true

    $list = [System.Collections.Generic.List[object]]::new()
    $list.AddRange($testData)
    $output = switch ($list) {
        (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
                $switch.Current
            }
        }
    }

    PS> $switchIsNull
    False  ## $switch was set
    PS> $output
    2
    1
```

<details>
  <summary>Click to see the old repro steps</summary>

## Steps to reproduce (OLD)

```powershell


Describe '$switch variable' {
  It 'Handles <Kind>' -TestCases @(
    @{Kind = 'array' }
    @{Kind = 'file' }
    @{Kind = 'pipeline' }
  ) {
    param($kind)
    $testData = 1, 2, 3, 4

    $switchIsNull = $false

    $output = switch ($Kind) {
      'file' {
        Set-Content -LiteralPath 'InputData.txt' -Value $testData
        switch -File InputData.txt {
          (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
              $switch.Current
            }
            continue
          }
        }
        Remove-Item InputData.txt
      }
      'array' {
        switch ($testData) {
          (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
              $switch.Current
            }
            continue
          }
        }
      }
      'pipeline' {
        switch ($testData | ForEach-Object { $_ }) {
          (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
              $switch.Current
            }
            continue
          }
        }
      }
    }

    $switchIsNull | Should -BeFalse
    $output | Should -be 2, 3
  }
}
```

## Expected behavior (OLD)

```none
Describing $switch variable
  [+] Handles array 42ms (13ms|29ms)
  [+] Handles file 32ms (13ms|19ms)
  [+] Handles pipeline 43ms (13ms|30ms)
Tests completed in 328ms
Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 0
```

## Actual behavior (OLD)

```none
Describing $switch variable
  [+] Handles array 42ms (13ms|29ms)
  [-] Handles file 13ms (13ms|1ms)
   Expected @(2, 3), but got '2'.
   at $output | Should -be 2,3, testswitch.ps1:56
  [-] Handles pipeline 5ms (4ms|1ms)
   Expected @(2, 3), but got @(2, 1).
   at $output | Should -be 2,3, testswitch.ps1:56
Tests completed in 328ms
Tests Passed: 1, Failed: 2, Skipped: 0 NotRun: 0
```

</details>

## Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.3
PSEdition                      Core
GitCommitId                    7.2.0-preview.3-64-gbe7d36603d1cc60abd4e8e738ead8f437b7869fa
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SeeminglyScience** [comment]
Yeah struct enumerators are going to be real inconsistent.  The engine is probably copying the struct to the variable and not retrieving it.

Even though the engine is almost definitely referencing the boxed version (via `IEnumerator` or similar), `PSVariable` has some special logic to copy mutable structs.

**Comment by daxian-dbw** [comment]
I don't know why, but the Pester test from the repro step gives me a different results, on both 7.1.3 and 7.2.0-preview.6:
```
Describing $switch variable
  [+] Handles array 68ms
  [-] Handles file 54ms
    Expected @(2, 3), but got '2'.
    54:     $output | Should -be 2, 3
  [+] Handles pipeline 6ms
```
But when I run the 'pipeline' part separately, I do get `2,1`, which means the Pester test should have failed :/

Besides, for `switch (file)`, `$switch` is actually unset (`$null`), but the test doesn't reflect that correctly because there is an outer `switch` statement and `$switch` was set for the outer switch.

Given the above issues with the repro steps, I will update the repro steps to split it into 3, for array, file, and pipeline respectively.

**Comment by daxian-dbw** [comment]
For `switch -file`, I think it's by design to not set `$switch`. The file content is read line by line, and each line is fed to the test clause after read it from the file. We should update the help doc to capture this.

For `switch ($list)`, like @SeeminglyScience said, it's because the enumerator is a value type, but I observed different behaviors between when the `switch` statement is in a local scope and when it's in the global scope. See below code snippets:

```
### Running in global scope, and thus $switch is unoptimized -- will store in PSVariable ###

$testData = 1, 2, 3, 4
$switchIsNull = $true

$list = [System.Collections.Generic.List[object]]::new()
$list.AddRange($testData)
$output = switch ($list) {
    (2) {
        $_
        $switchIsNull = $null -eq $switch
        if ($switch -and $switch.MoveNext()) {
            $switch.Current
        }
    }
}
$output
> 2
> 1

### ====== Versus ====== ###

### Running in local scope, and thus $switch is optimized -- will store in local tuples ###

& {
    $testData = 1, 2, 3, 4
    $switchIsNull = $true

    $list = [System.Collections.Generic.List[object]]::new()
    $list.AddRange($testData)
    $output = switch ($list) {
        (2) {
            $_
            $switchIsNull = $null -eq $switch
            if ($switch -and $switch.MoveNext()) {
                $switch.Current
            }
        }
    }
    
    $output
}
> 2
> 3
```
As is called out in the code snippets, the difference is [how `$switch` is stored](https://github.com/PowerShell/PowerShell/blob/170a226689f8d1d095d74be8d1f40907b3961d75/src/System.Management.Automation/engine/parser/Compiler.cs#L5196-L5203):
- when it's stored in `PSVariable`, we got a copy of the value type enumerator, and thus see `2, 1` as the output
- when it's stored in local tuples, it looks it's referencing the same boxed value of the enumerator, and thus we see `2, 3` as the output.

**Comment by daxian-dbw** [comment]
> For `switch -file`, I think it's by design to not set `$switch`. The file content is read line by line, and each line is fed to the test clause after read it from the file. We should update the help doc to capture this.

@bpayette Can you please take a look and see if you agree? Thanks

**Comment by SeeminglyScience** [comment]
> `### Running in global scope, and thus $switch is unoptimized -- will store in PSVariable ###`

Small point of clarification, it's unoptimized due to dot sourcing rather than the specific scope. e.g. you can probably see similar behavior with `& { . { <# repro code #> } }`

**Comment by daxian-dbw** [comment]
PowerShell uses optimized compilation if
1. it's not in debugging, AND
2. it's running in a new local scope (a new local scope is created for the invocation)

Running something directly in the global scope is an easy way to make it unoptimized.

**Comment by vexx32** [comment]
Yeah, I think @SeeminglyScience was just clarifying that the global scope is not the only way to have this problem, so any fix needs to be aware that non-global scopes can also end up unoptimized via dot sourcing, which is fairly common for (for example) importing scripts into another file to reuse functions/variables, etc.

**Comment by powercode** [comment]
From a user's perspective, it is just as useful to be able to skip some input when it is a file, so I think we should strive to fix this for `-file` as well.

**Comment by SeeminglyScience** [comment]
The engine could do it's own sort of boxing for every enumerable.  Maybe a class like this:

```csharp
public class PSEnumerator : IEnumerator
{
    private IEnumerator _base;

    public object Current => _base.Current;

    public bool MoveNext() => _base.MoveNext();

    // etc
}
```

There would be a performance hit for sure.  But the only way I can think of to solve this is to make sure all references are of the same boxed copy which will be very difficult without something like this.  `PSVariable` will always force a copy for mutable structs.

**Comment by bpayette** [comment]
> > For `switch -file`, I think it's by design to not set `$switch`. The file content is read line by line, and each line is fed to the test clause after read it from the file. We should update the help doc to capture this.
> 
> @bpayette Can you please take a look and see if you agree? Thanks

@daxian-dbw  Actually `$switch` with `-file` doesn't work because I never got around to implementing it in V1 and it never showed up on the radar again.  Implementing it would be a good thing.

@powercode WRT skipping lines, while `$switch` doesn't currently work with `-file`,  as a workaround, you can just not match a line and continue iterating:
```powershell
# Return all the lines containing  "^ *function"
switch -file $profile -regex { "^ *function" { $_ } }
```
If you want to skip (or keep) multiple lines, you can do something like:
```powershell
# Return the function line followed by some context lines (doesn't work for short functions)
switch -file $profile -regex { {$num} {$num--; ">> $_"}  "^ *function" { $num = 3; $_ } }
```
You could also use the `continue` keyword to skip to the next line. (I'm sure you know all this but others might not).

**Comment by JamesWTruher** [comment]
We discussed this in the working group meeting (7/22/21) and decided that there are two issues here:
- we agree that using `$switch` with `-file` should be supported. I have opened  https://github.com/PowerShell/PowerShell/issues/15821 and it's marked `UpForGrabs`
- this issue (out of sync struct enumerators in `$switch`) is a bug - also marked `UpForGrabs`
