### ISSUE TITLE
Concatenating files with >> Get-Content | Add-Content << fails?

### ISSUE THREAD

**Issue by User843212** [PowerShell/PowerShell#15188]
## Steps to reproduce

```
I have downloaded video files "segment_1.ts ... segment_n.ts" and want to concatenate these files to one single "Video.ts"

I use this code::
        $Segments | ForEach-Object { Get-Content $_ -Raw | Add-Content "Video.ts" }
         with filenames stored in array "$Segments"
```

## Expected behavior

```
All video files "segment_1...n.ts" should be concatenated to one single video file "Video.ts". 
```

## Actual behavior

```
The file "Video.ts" is created but it is much to big and e.g. VLC can't play it.
The absolutely identical code works perfectly in PowerShell 5.
It seems that the file "Video.ts" is some twice as big when created in PS 7 as opposed to PS 5.

As work around this code works but is much slower:
      $Segments | ForEach-Object { Get-Content $_ -AsByteStream -ReadCount 0 | Add-Content "Video.ts" -AsByteStream }

Is it possible that "PS7 x64" has a problem with "int32" to "int64" conversion in "get/add-content"?
```

## Environment data

```
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Get-Content by default reads files as text, not bytes, so will likely mangle non-text data. Use `-AsByteStream` for both the Get- and Set- commands there to retrieve and store back just the raw bytes.

**Comment by User843212** [comment]
@ vexx32 - how  can I edit the title?

**Comment by User843212** [comment]
> .... Use `-AsByteStream` for both the Get- and Set- commands there to retrieve and store back just the raw bytes.

I have already done this as mentioned in section "Actual behavior" from bug report.
But this is not the point. Why e.g. is the output file "Video.ts" some twice as big as should be?
E.g. with PS5 it is 4.321kB opposed to 7.798kB with PS7

**Comment by mklement0** [comment]
@User843212, you can speed the command up considerably as follows:

```
Add-Content "Video.ts" -AsByteStream -Value (Get-Content $_ -AsByteStream -Raw)
```

For best performance:

* Use `-Raw` rather than `-ReadCount 0` in combination with `Get-Content -AsByteStream`.
* Don't _pipe_ the resulting `[byte[]]` array to `Add-Content`, pass it via `-Value`.

**Comment by User843212** [comment]
@mklement0 
Allready done in all possible ways!
I have listed execution times below - timings from PS7

$Segments | ForEach-Object { Get-Content $_ -Raw | Add-Content "Video.ts" }
TotalSeconds      : 1,7     **<<< this works fine in PS5 but PS7 outputs corrupted video file "Video.ts"**

$Segments | ForEach-Object { Get-Content $_ -AsByteStream -Raw | Add-Content "Video.ts" -AsByteStream }
TotalSeconds      : 25

$Segments | ForEach-Object { Get-Content $_ -AsByteStream -ReadCount 0 | Add-Content "Video.ts" -AsByteStream }
TotalSeconds      : 12

$Segments | ForEach-Object { Add-Content "Video.ts" -AsByteStream -Value (Get-Content $_ -AsByteStream -Raw) }
TotalSeconds      : 37

$Segments | ForEach-Object { Add-Content "Video.ts" -AsByteStream -Value (Get-Content $_ -AsByteStream -ReadCount 0) }
TotalSeconds      : 29

**Comment by mklement0** [comment]
> may be I should have mentioned that I am professional software developer

 It's sufficient to make convincing arguments, irrespective of your background.

> <<< this works fine in PS5 but PS7 outputs corrupted video file "Video.ts"

As @vexx32 has explained, using `Get-Content` without `-AsByteStream` is only suitable for _text_ files.

(That it works in Windows PowerShell (PowerShell versions up to v5.1) is a happy accident (the active ANSI code page being a single-byte encoding such as Windows-1252, where all byte values are by definition valid characters as-is; however, it would fail even in Windows PowerShell if you used the Windows 10 feature of setting the system locale to UTF-8).

As for the remaining benchmarks:

* I misspoke about the influence of the pipeline _in this case_: given that both `-ReadCount 0` and `-Raw` output a _single_ object to the pipeline (a single array with `-AsByteStream` in both cases, a single array / single string without `-AsByteStream`), the overhead introduced by the pipeline vs. argument-passing should be _negligible_.

  * By contrast, with commands that output multiple objects in the - usual - _streaming_ fashion, pipeline vs. argument input can make a big difference - assuming the command is even prepared to handle _array_-valued input by argument, which only some cmdlets do.

* Combining `-AsByteStream` with `-ReadCount -0` vs. `-Raw` _in isolation_ exhibits a huge performance difference in favor of the latter.
  * You could argue that it shouldn't, given that both construct a _single_ array comprising _all_ bytes; in practice `-ReadCount 0` outputs an`[object[]]` array, whereas the - much faster - `-Raw` outputs a `[byte[]]` array.
  * Note that with _text_ input (i.e. in the absence of `-AsByteStream`), `-Raw` is only slightly faster than `-ReadCount 0`, which makes sense: it's the difference between reading a file as a single string and reading it into an array of lines.

**You've clearly hit on a performance problem with _byte_ in- and output**, as the following benchmarks show, and for which I have no explanation at this point:

---

You can run the following benchmarks yourself, using the `Time-Command` function that you can download from [this Gist]((https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27):

  * Assuming you have looked at the linked code to ensure that it is safe (which I can personally assure you of, but you should always check), you can install it directly as follows:
  
        irm https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27/raw/Time-Command.ps1 | iex

Benchmark code that averages the timings of 3 runs, using 32Mb files:

```powershell
Write-Verbose -vb 'Setting up...'

# Create files to serve as the target and the file to add to it.
$bytes = [byte[]]::new(32mb)
Set-Content -AsByteStream target.bin -value $bytes
Set-Content -AsByteStream add.bin -value $bytes

# Create a copy of the original target to restore it betwen runs
Set-Content -AsByteStream original.bin -value $bytes

# Warm up the file cache to level the playing field.
$null, $null, $null = (Get-Content -Raw -AsByteStream original.bin), (Get-Content -Raw -AsByteStream target.bin), (Get-Content -Raw -AsByteStream add.bin)

Write-Verbose -vb 'Running benchmarks...'
# Run the benchmarks.

Write-Verbose -vb '---- BINARY'

Write-Verbose -vb 'Binary: Get-Content alone...'
Time-Command -Count 3 `
  { # -ReadCount 0
    $bytes = Get-Content original.bin -AsByteStream -ReadCount 0
  },
  { # -Raw
    $bytes = Get-Content original.bin -AsByteStream -Raw
  } | Out-Host


Write-Verbose -vb 'Binary: Get-Content + Set-Content...'

Time-Command -Count 3 `
  { # -ReadCount 0, pipeline
    Get-Content original.bin -AsByteStream -ReadCount 0 | Set-Content target.bin -AsByteStream 
  },
  { # -Raw, pipeline
    Get-Content original.bin -AsByteStream -Raw | Set-Content target.bin -AsByteStream 
  },
  { # -ReadCount 0, argument
    Set-Content target.bin -AsByteStream -Value (Get-Content original.bin -AsByteStream -ReadCount 0)
  },
  { # -Raw, argument
    Set-Content target.bin -AsByteStream -Value (Get-Content original.bin -AsByteStream -Raw)
  } | Out-Host

Write-Verbose -vb 'Binary: Get-Content + Add-Content...'

Time-Command -Count 3 `
  { # -ReadCount 0, pipeline
    Copy-Item original.bin target.bin
    Get-Content original.bin -AsByteStream -ReadCount 0 | Add-Content target.bin -AsByteStream 
  },
  { # -Raw, pipeline
    Copy-Item original.bin target.bin
    Get-Content original.bin -AsByteStream -Raw | Add-Content target.bin -AsByteStream 
  },
  { # -ReadCount 0, argument 
    Copy-Item original.bin target.bin
    Add-Content target.bin -AsByteStream -Value (Get-Content original.bin -AsByteStream -ReadCount 0)
  },
  { # -Raw, argument 
    Copy-Item original.bin target.bin
    Add-Content target.bin -AsByteStream -Value (Get-Content original.bin -AsByteStream -Raw)
  } | Out-Host

  Write-Verbose -vb '---- TEXT'

  Write-Verbose -vb 'Text: Get-Content alone...'
  Time-Command -Count 3 `
    { # -ReadCount 0
      $lines = Get-Content original.bin -ReadCount 0
    },
    { # -Raw
      $wholeFileString = Get-Content original.bin -Raw
    } | Out-Host
  
  Write-Verbose -vb 'Text: Get-Content + Set-Content...'

  Time-Command -Count 3 `
    { # -ReadCount 0, pipeline
      Get-Content original.bin -ReadCount 0 | Set-Content target.bin
    },
    { # -Raw, pipeline
      Get-Content original.bin -Raw | Set-Content target.bin
    },
    { # -ReadCount 0, argument
      Set-Content target.bin -Value (Get-Content original.bin -ReadCount 0)
    },
    { # -Raw, argument
      Set-Content target.bin -Value (Get-Content original.bin -Raw)
    } | Out-Host
 ```

On my Window 10 VM running PowerShell Core 7.2.0-preview.4 I see the following results - the absolute times aren't important, but the `Factor` column should give a sense of relative performance:

![image](https://user-images.githubusercontent.com/588825/114123278-fb773080-98bf-11eb-9a76-c260d0a3c717.png)

* The huge performance discrepancy between `Get-Content -AsByteStream -Raw` and `Get-Content -AsByteStream -ReadCount 0` in isolation is strange.

* That input by pipeline would be _faster_ than input by argument for binary data doesn't make sense to me. (By contrast, the ratios are expected for _text_ data).

* That text processing, which involves decoding and encoding, is so much faster than byte processing doesn't make sense to me.

**Comment by powercode** [comment]
Every byte is converted to an object. 

```powershell
trace-command -Expression {add-content -AsByteStream -LiteralPath target.bin -Value (Get-Content -raw -AsByteStream add.bin)} -PSHost -Name ParameterBinding 
```
```text
BIND NAMED cmd line args [Get-Content]
BIND POSITIONAL cmd line args [Get-Content]
BIND cmd line args to DYNAMIC parameters.
    DYNAMIC parameter object: [Microsoft.PowerShell.Commands.FileSystemContentReaderDynamicParameters]
    BIND NAMED args to DYNAMIC parameters
        BIND arg [True] to parameter [Raw]
            COERCE arg to [System.Management.Automation.SwitchParameter]
                Parameter and arg types the same, no coercion is needed.
            BIND arg [True] to param [Raw] SUCCESSFUL
        BIND arg [True] to parameter [AsByteStream]
            COERCE arg to [System.Management.Automation.SwitchParameter]
                Parameter and arg types the same, no coercion is needed.
            BIND arg [True] to param [AsByteStream] SUCCESSFUL
    BIND POSITIONAL args to DYNAMIC parameters
        BIND arg [add.bin] to parameter [Path]
            Binding collection parameter Path: argument type [String], parameter type [System.String[]], collection type Array, element type [System.String], no coerceElementType
            Creating array with element type [System.String] and 1 elements
            Argument type String is not IList, treating this as scalar
            Adding scalar element of type String to array position 0
            BIND arg [System.String[]] to param [Path] SUCCESSFUL
MANDATORY PARAMETER CHECK on cmdlet [Get-Content]
CALLING BeginProcessing
CALLING EndProcessing
BIND NAMED cmd line args [Add-Content]
    BIND arg [target.bin] to parameter [LiteralPath]
        COERCE arg to [System.String[]]
            Trying to convert argument value from System.String to System.String[]
            ENCODING arg into collection
            Binding collection parameter LiteralPath: argument type [String], parameter type [System.String[]], collection type Array, element type [System.String], coerceElementType
            Creating array with element type [System.String] and 1 elements
            Argument type String is not IList, treating this as scalar
            Coercing scalar arg value to type System.String
            COERCE arg to [System.String]
                Parameter and arg types the same, no coercion is needed.
            Adding scalar element of type String to array position 0
        BIND arg [System.String[]] to param [LiteralPath] SUCCESSFUL
    BIND arg [0 0 0 0 0 0 0 0 0 0] to parameter [Value]
        COERCE arg to [System.Object[]]
            Trying to convert argument value from System.Management.Automation.PSObject to System.Object[]
            ENCODING arg into collection
            Binding collection parameter Value: argument type [PSObject], parameter type [System.Object[]], collection type Array, element type [System.Object], coerceElementType
            Arg is IList with 10 elements
            Creating array with element type [System.Object] and 10 elements
            Argument type System.Management.Automation.PSObject is IList
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 0
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 1
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 2
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 3
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 4
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 5
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 6
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 7
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 8
            COERCE collection element from type Byte to type System.Object
            COERCE arg to [System.Object]
                Parameter and arg types the same, no coercion is needed.
            Adding element of type Byte to array position 9
        BIND arg [System.Object[]] to param [Value] SUCCESSFUL
BIND POSITIONAL cmd line args [Add-Content]
BIND cmd line args to DYNAMIC parameters.
    DYNAMIC parameter object: [Microsoft.PowerShell.Commands.FileSystemContentWriterDynamicParameters]
    BIND NAMED args to DYNAMIC parameters
        BIND arg [True] to parameter [AsByteStream]
            COERCE arg to [System.Management.Automation.SwitchParameter]
                Parameter and arg types the same, no coercion is needed.
            BIND arg [True] to param [AsByteStream] SUCCESSFUL
    BIND POSITIONAL args to DYNAMIC parameters
MANDATORY PARAMETER CHECK on cmdlet [Add-Content]
CALLING BeginProcessing
CALLING EndProcessing
```

**Comment by 237dmitry** [comment]
Is this correct or not I don't know . For example we have two binary files 1.bin and 2.bin, we want to concatenate them to 3.bin:
```powershell
New-PSDrive -Name test -PSProvider filesystem -Root .
New-Item 3.bin
${test:3.bin} = ${test:1.bin} + ${test:2.bin}
Remove-PSDrive test
```
I was trying with two 32Mb empty files. It took ~600 milliseconds, the result file was exactly 64Mb.

**Comment by vexx32** [comment]
You can do a similar thing with any named drives, so I think that should work? `${c:\test\file.bin}` is also a valid query in that syntax.

Not exactly the most well known workaround, but if it works, that's pretty good!

**Comment by 237dmitry** [comment]
> You can do a similar thing with any named drives

Yes, but only in Windows. The most interesting thing about this approach is that you can work as with typed variables:
```
> Get-Content 1.txt
1

> [int] ${c:1.txt} += 1
> Get-Content 1.txt
2

> ${c:1.txt} += 1
> Get-Content 1.txt
21

> [array] ${c:1.txt} += 1
> Get-Content 1.txt
21
1
```

**Comment by mklement0** [comment]
Great sleuthing, @powercode.

@237dmitry, as [discussed only recently](https://github.com/PowerShell/PowerShell/issues/15135#issuecomment-813073197) namespace variable notation with the file-system provider has many limitations, and this case is no exception: `${test:1.bin}` is effectively the same as `Get-Content test:1.bin`, i.e it reads _text_ with the default encoding (UTF-8 in PowerShell Core). In other words, this will corrupt your binary files:

```powershell
New-PSDrive -Name test -PSProvider filesystem -Root .
# Create 2-byte files containing 0xFF values.
[byte[]] (, 0xff * 2) | Set-Content -AsByteStream 1.bin, 2.bin
${test:3.bin} = ${test:1.bin} + ${test:2.bin}
Remove-PSDrive test
Format-Hex 3.bin
```

The above yields:

```
          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 EF BF BD EF BF BD EF BF BD EF BF BD 0A          ï¿½ï¿½ï¿½ï¿½�
```

* The invalid-as-UTF-8 `0xFF` bytes became (UTF-8-encoded) `�` characters (the Unicode replacement character, `U+FFFD`)
* A newline was invariably added.

**Comment by vexx32** [comment]
What I'm gathering from this issue is that there currently is no good (read: unnecessarily slow/intensive) way to join binary files in PowerShell at all without reaching for .NET methods and manually doing it.

I would suggest this is probably best resolved by adding a `Join-File` cmdlet with `[string[]] -Path`, `[string] -Destination`, and an optional `-Append` switch. .NET can do this; PowerShell's pipeline semantics get in the way of doing this neatly. We can work around this by adding a cmdlet to bypass the pipeline shenanigans that currently cause issues here.

**Comment by mklement0** [comment]
@vexx32, while nothing will beat the speed of native utility with raw byte handling (`type >>` on Windows, `cat >>` on Unix), the primary problem here is the implementation of `Set-Content` / `Add-Content` with an `[object[]]`-typed `-Value` parameter.

@powercode, correct me if I'm wrong, but I think that if we made `-Value` just `[object]`, with the cmdlets performing array / enumerable detection internally, the performance benefits of the `[byte[]]` array that `-AsByteStream -Raw` brings could be preserved.

**Comment by mklement0** [comment]
Of course, that doesn't preclude _also_ introducing a `Join-File` utility, which sounds like a good idea.

**Comment by User843212** [comment]
mklement0" brought me to this idea:
$Segments | ForEach-Object { Get-Content $_ -Encoding 1252 | Add-Content "Video.ts" -Encoding 1252

This works only almost correctly because every '"CR" 0xD' is translated to "CR/LF" '0xD/'0xA'.
Using "Add-Content" with "-NoNewline" removes every '0xD'.
Is there a convenient way to not translate a CR into Windows style?

**Comment by mklement0** [comment]
Good point, @User843212, that should work, though I recommend `-Encoding 28591`, i.e. ISO-8859-1, given that it it is a true subset of Unicode (unlike Windows-1252). You can avoid the newline problem with `Get-Content -Raw` , which reads the file content as a _single, multiline string_, and `Add-Content -NoNewLine`, which prevents the addition of a trailing newline.

**Comment by User843212** [comment]
@mklement0: your suggestion seems to work in principle!

But every unknown character by this encoding seems to be translated to '0x3F'. I have tried some encodings but haven't found one that supports full 8 bit.

----- **should**  ----------------------------------------------- 
00000 - 47 40 00 10 00 00 B0 0D 00 01 C1 00 00 00 01 EF 
00010 - FF 36 90 E2 3D FF FF FF FF FF FF FF FF FF FF FF 
------ **is** -----------------------------------------------------
00000 - 47 40 00 10 00 00 **3F** 0D 00 01 **3F** 00 00 00 01 **3F**       ----- '0x3F' for "unknown" characters
00010 - 3F 36 3F 3F 3D 3F 3F 3F 3F 3F 3F 3F 3F 3F 3F 3F

**Comment by User843212** [comment]
@mklement0 - it (seems to) works fine.  Very well done!
In a first attempt I had forgotten the "-Raw" argument and I wonder that "-Raw" works together with "-Encoding".
I thought "-Raw" forbids "-Encoding" or at least makes it being ignored

**Comment by mklement0** [comment]
Glad to hear it, @User843212. It should work robustly, becaus all byte values are valid code points in ISO-8859-1 (`-Encoding 28591`).

It is certainly a pragmatic solution, but it's important to note:

* The file size will _double_ in memory, as the `[byte]` values become `[char]` instances, which are in effect `[uint16]` values representing UTF-16 code units. In effect, a NUL byte is inserted after every byte in the input array.

* The character decoding and encoding that is involved in textual operations slows things down - although given the current suboptimal `Add-Content` implementation, it is still much faster than with `-AsByteStream`.

However, with only a bit of .NET-fu you can avoid both problems above:

```powershell
$fs = [IO.File]::OpenWrite((Convert-Path target.bin))
$null = $fs.Seek(0, 'End')

$Segments | Get-Content -AsByteStream -Raw | ForEach-Object { $fs.Write($_) }

$fs.Close()
```

Of course, that shouldn't be necessary, and we should look into improving `Set-Content` / `Add-Content -AsByteStream`.

**Comment by mklement0** [comment]
And, yes, the name of the `-Raw` switch is unfortunate, because it suggests raw byte handling, whereas all it does is read the file _as a whole_ (as a single _string_ by default, as a single `[byte[]]` array with `-AsByteStream`). Renaming it to something like `-Whole` has been suggested, but was turned down (see #7715).

**Comment by mklement0** [comment]
I've refined the benchmarks to more clearly show the impact of the `Add-Content` / `Set-Content -AsByteStream` implementation and the massive performance penalty it occurs.

.NET solutions - both pure and in combination with `Get-Content -AsByteStream -Raw` - are also included, which perform best overall, and about the same between them.

The benchmarks  also include a call to `cmd /c 'type >>'` on Windows, and to `sh -c 'cat >>'` on Unix;
Calling the native shell executable is necessary for the raw byte handling of `>>`:
  * On Unix, at least with the 32MB files, a `cat >>` solution is actually slower than a .NET solution, though not by much, which I presume is in part due to the additional startup cost of the `sh` child process.
  * On Windows, `type >>` is suprisingly slow and not worth considering.

While the `-Encoding 28591` workaround performs acceptably (and certainly far outperforms the `Add-Content -AsByteStream` solutions), the .NET-based/-assisted real byte solutions perform noticeably better (although the factor differs by platform), and have the added advantage of not doubling the size of the file content in memory.

`Get-Content -AsByteStream -ReadCount 0` is remarkably slow, much slower than `Get-Content -ReadCount 0`, i.e. getting all _lines_ as single array.

---

Results, based on 32MB test files (absolute numbers aren't important, but the `Factor` column is):

* On Windows 10 20H2, PowerShell Core 7.2.0-preview.4

![image](https://user-images.githubusercontent.com/588825/114234894-61f66000-994d-11eb-96d6-deb7deabe168.png)

* On macOS 10.15.7 with PowerShell Core 7.2.0-preview.4:

![image](https://user-images.githubusercontent.com/588825/114234870-5dca4280-994d-11eb-9171-6983130266a9.png)

<details>
<summary>Benchmark source code:</summary>

* **Note**: The script downloads and defines benchmark function `Time-Command` from [this Gist](https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27), after prompting for confirmation.

```powershell
Write-Verbose -vb 'Setting up...'

# Download and define function `Time-Command` on demand (will prompt).
if (-not (Get-Command -ea Ignore Time-Command)) {
  $gistUrl = 'https://gist.github.com/mklement0/9e1f13978620b09ab2d15da5535d1b27/raw/Time-Command.ps1'
  if ((Read-Host "`n====`n  OK to download and define benchmark function ``Time-Command`` from Gist ${gistUrl}?`n=====`n(y/n)?").Trim() -notin 'y', 'yes') { Write-Warning 'Aborted.'; exit 2 }
  Invoke-RestMethod $gistUrl | Invoke-Expression 3>$null
  if (-not ${function:Time-Command}) { exit 2 }
}

Push-Location ('temp:/', "$env:TEMP")[$env:OS -eq 'Windows_NT'] -ea Stop

# Create files to serve as the target and the file to add to it.
$fileSize = 32mb
$bytes = [byte[]]::new($fileSize)
$dir = $PWD.ProviderPath
[IO.File]::WriteAllBytes("$dir/add.bin", $bytes)
[IO.File]::WriteAllBytes("$dir/target.bin", $bytes)
# Create a copy of the original target to restore it betwen runs.
[IO.File]::WriteAllBytes("$dir/original.bin", $bytes)

# Warm up the file cache to level the playing field.
$null, $null, $null = (Get-Content -Raw -AsByteStream original.bin), (Get-Content -Raw -AsByteStream target.bin), (Get-Content -Raw -AsByteStream add.bin)

# Use the following inside blocks to output the resulting file size for verification, if needed:
#    (Get-Item target.bin).Length / 1mb | Write-Verbose -vb

# Script block for use with ForEach-Object for appending bytes via .NET
$sbAppend = {
  $fs = [IO.File]::OpenWrite((Convert-Path target.bin))
  $null = $fs.Seek(0, 'End')
  $fs.Write([byte[]] $_)
  $fs.Close()
}

# Script block for restoring the original target file to prevent it from growing too large,
# executed between commands - these timings will be filtered out.
$sbRestoreTargetFile = { if ((Get-Item target.bin).Length -gt $fileSize) { Copy-Item original.bin target.bin } }

Write-Verbose -vb 'Running benchmarks (2 groups; will take minutes)...'

Write-Verbose -vb '--- 1 of 2: READING ONLY'

Time-Command -Count 3 `
{ # TEXT: Get-Content ONLY: -ReadCount 0 -Encoding 28591 (not truly byte-preserving)
  $null = Get-Content add.bin -ReadCount 0 -Encoding 28591
},
{ # TEXT: Get-Content ONLY: -Raw -Encoding 28591
  $null = Get-Content add.bin -Raw -Encoding 28591
},
{ # BINARY: Get-Content ONLY: -AsByteStream -ReadCount 0
  $null = Get-Content add.bin -AsByteStream -ReadCount 0
},
{ # BINARY: Get-Content ONLY: -AsByteStream -Raw
  $null = Get-Content add.bin -AsByteStream -Raw
} | Select-Object Factor, Secs*, Command | Out-Host
# !! Byte-by-byte streaming is PROHIBITIVELY SLOW, so not worth including in the test.
# { # BINARY: Get-Content ONLY: -AsByteStream only (streaming bytes)
#   $null = Get-Content add.bin -AsByteStream
# } 


Write-Verbose -vb '--- 2 of 2: READING & APPENDING'

$timings = Time-Command -Count 3 `
{ # TEXT: Get-Content+Add-Content: -ReadCount 0, pipeline (not truly byte-preserving)
  Get-Content add.bin -ReadCount 0 -Encoding 28591 | Add-Content target.bin -Encoding 28591 
},
$sbRestoreTargetFile, 
{ # TEXT: Get-Content+Add-Content: -Raw, pipeline
  Get-Content add.bin -Raw -Encoding 28591 | Add-Content target.bin -NoNewLine -Encoding 28591 
},
$sbRestoreTargetFile,
{ # TEXT: Get-Content+Add-Content: -ReadCount 0, argument (not truly byte-preserving)
  Add-Content target.bin -NoNewLine -Encoding 28591 -Value (Get-Content add.bin -ReadCount 0 -Encoding 28591)
},
$sbRestoreTargetFile,
{ # TEXT: Get-Content+Add-Content: -Raw, argument
  Add-Content target.bin -Encoding 28591 -NoNewLine -Value (Get-Content add.bin -Raw -Encoding 28591)
},
$sbRestoreTargetFile,
{ # BINARY: Native utility: cmd /c 'type >>' or sh -c 'cat >>'
  if ($env:OS -eq 'Windows_NT') {
    cmd /c 'type add.bin >> target.bin'
  } else {
    sh -c 'cat add.bin >> target.bin'
  }
},
$sbRestoreTargetFile,
{ # BINARY: pure .NET:
  $fs = [IO.File]::OpenWrite((Convert-Path target.bin))
  $null = $fs.Seek(0, 'End')
  $fs.Write(
    [IO.File]::ReadAllBytes((Convert-Path add.bin))
  )
  $fs.Close()
},
$sbRestoreTargetFile,
{ # BINARY: Get-Content+.NET: -AsByteStream -ReadCount 0
  Get-Content add.bin -AsByteStream -ReadCount 0 | ForEach-Object $sbAppend
},
$sbRestoreTargetFile,
{ # BINARY: Get-Content+.NET: -Raw
  Get-Content add.bin -AsByteStream -Raw | ForEach-Object $sbAppend
},
$sbRestoreTargetFile,
{ # BINARY: Get-Content+Add-Content: -AsByteStream -ReadCount 0, pipeline
  Get-Content add.bin -AsByteStream -ReadCount 0 | Add-Content target.bin -AsByteStream
},
$sbRestoreTargetFile,
{ # BINARY: Get-Content+Add-Content: -AsByteStream -Raw, pipeline
  Get-Content add.bin -AsByteStream -Raw | Add-Content target.bin -AsByteStream
},
$sbRestoreTargetFile,
{ # BINARY: Get-Content+Add-Content: -AsByteStream -ReadCount 0, argument
  Add-Content target.bin -AsByteStream -Value (Get-Content add.bin -AsByteStream -ReadCount 0)
},
$sbRestoreTargetFile,
{ # BINARY: Get-Content+Add-Content: -AsByteStream -Raw, argument
  Add-Content target.bin -AsByteStream -Value (Get-Content add.bin -AsByteStream -Raw)
} | Where-Object Command -notmatch 'Copy-Item'

# Because the $sbRestoreTargetFile were included in the timings, the .Factor column values
# are off, which we must correct now.
$minTiming = ($timings.Factor | Measure-Object -Minimum).Minimum

# Output with the corrected factors.
$timings | Select-Object @{ n='Factor'; e={ '{0:N2}' -f ($_.Factor / $minTiming) } }, Secs*, Command

# Clean up.
Remove-Item original.bin, add.bin, target.bin

Pop-Location
```
</details>

**Comment by mklement0** [comment]
After emerging from this remarkably deep rabbit hole, my conclusions are:

* `Set-Content` / `Add-Content` with `-AsByteStream` should be able to use `[byte[]]` arrays as input as-is, for vastly improved performance. Making the `-Value` parameter `[object]` rather than its current type, `[object[]]`, may be the key.


* `Get-Content -AsByteStream -ReadCount <n>` could use optimization too.

**Comment by powercode** [comment]
@mklement0 I agree that it could be solved by changing the parameter type.

Then logic within get-content could be used to determine the most efficient way to handle the content passed to the cmdlet. The main issue would be to ensure compatibility with the current implementation.

**Comment by mklement0** [comment]
Thanks, @powercode  - please #15208

**Comment by mklement0** [comment]
As for improving the performance of `-ReadCount <n>` with `Get-Content -AsByteStream`, see #15209
