### ISSUE TITLE
For the DataTable type, the call to GetType() on a non-existent property returns a value

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#15196]
## Steps to reproduce

```powershell
[void][Reflection.Assembly]::LoadWithPartialName("System.Data.DataSetExtensions");
$Dt = New-Object System.Data.DataTable
[void]$Dt.Columns.Add( 'C1')
[void]$Dt.Columns.Add( 'C2')
[void]$Dt.Rows.Add( '1','2')
[void]$Dt.Rows.Add( 'Y','Z')
$Dt.xyz.GetType()
# IsPublic IsSerial Name                                     BaseType
# -------- -------- ----                                     --------
# True     True     Object[]                                 System.Array
$null -eq $Dt.xyz
#$False
Set-StrictMode -Version latest
$Dt.xyz
#PropertyNotFoundException: The property 'xyz' cannot be found on this object. Verify that the property exists.
Set-StrictMode -Off
```

## Expected behavior
same behaviour as the following cases :
```powershell
$i=10
$i.xyz
#$null
$i.xyz.gettype()
#InvalidOperation: You cannot call a method on a null-valued expression.
$null -eq $i.xyz
#True

$T=1..3
$T.xyz
#$null
$T.xyz.gettype()
#InvalidOperation: You cannot call a method on a null-valued expression.
$null -eq $T.xyz
#True
```

## Actual behavior
The call to GetType() on a non-existent property returns one or more values :
```powershell
$null -eq $Dt.xyz
#$False
```

## Environment data
Windows 10

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
This issue may be related to #6466

**Comment by mklement0** [comment]
Even though the type itself doesn't implement `IEnumerable`, PowerShell treats instances of `System.Data.DataTable` as enumerable rather than requiring you to use their (enumerable) `.Rows` property (which to me is both surprising and consistently implemented - see bottom section).

Therefore, `$dt.xyz` - in the absence of `.xyz` property on the `System.Data.DataTable` instance _itself_ -  performs _member enumeration_, i.e. it behaves like `$dt.Rows.xyz` == `$dt.Rows | % { $_.xyz }`.

In the absence of a `.xyz` property on the individual rows too, `$null` is returned for each, so with 2 rows you get a `($null, $null)` array.
With strict mode in effect, you get an error, as expected.

---

Another manifestation of this behavior is that `$dt.Count` returns `(1, 1)`, because - in given that `System.Data.DataTable` itself has no `.Count` property - `.Rows.Count` is returned, and each row - as a _scalar_ -has a count of 1.

Also, indexing doesn't work as expected: `$dt[0]` is _not_ the same as `$dt.Rows[0]`; instead, with indexing `System.Data.DataTable` is unexpectedly treated as a _scalar_, and `[0]` therefore returns the instance itself, i.e.. the _whole table_.

**Comment by LaurentDardenne** [comment]
I understood that there could be a different behavior, which is not documented, so we have to find out to know.
This has been achieved :-)

In the following case (a bit twisted), the result is different:
```powershell
 #Crée une fonction à partir d'une closure
${Function:Test-GenericIEnumerable}=.{
    #On recherche le type ouvert de l'interface générique IEnumerable
    $GenericIEnumerable=[Type]'System.Collections.Generic.IEnumerable`1'

    Return { 
     #La variable $InputObject implémente-t-elle l'interface générique IEnumerable ?
      param( $InputObject )
        foreach ($Interface in $InputObject.GetType().GetInterfaces())
        {
            #On suppose une seule implémentation de l'interface générique IEnumerable (https://stackoverflow.com/a/7852650)
           if ($Interface.IsGenericType)
           { 
               if ($Interface.GetGenericTypeDefinition() -eq $GenericIEnumerable) 
               {return $true}
           }
        }
        return $false
    }.GetNewClosure()
}

$Dt.Rows -is [System.Collections.IEnumerable]
# True

Test-GenericIEnumerable $Dt.Rows
# False
Test-GenericIEnumerable $Dt.xyz
# True
```
So is this the only type that behaves like this or how else can we identify them?

**Comment by mklement0** [comment]
> the result is different:

That is to be expected: `$Dt.Rows`, with `.Rows` being a type-native property of a `[System.Data.DataTable]` instance, is of type `[System.Data.DataRowCollection]` is an `IEnumerable`, but not a _generic_ enumerable.

By contrast, `$Dt.xyz`, the result of _member enumeration_  is an `[object[]]` array (which it always is with two or more elements) , which _is_ a generic enumerable.

> So is this the only type that behaves like this or how else can we identify them?

Which types PowerShell considers enumerable is based on hard-coded rules:

* Any **type that implements** the **[`IEnumerable`](https://docs.microsoft.com/en-US/dotnet/api/System.Collections.IEnumerable) / [``IEnumerable`1``](https://docs.microsoft.com/en-US/dotnet/api/System.Collections.Generic.IEnumerable-1)** .NET interface(s)
  * **_Except_** the following, which are _not_ automatically enumerated:

    * [`IDictionary`](https://docs.microsoft.com/en-US/dotnet/api/System.Collections.IDictionary) / [``IDictionary`2``](https://docs.microsoft.com/en-US/dotnet/api/System.Collections.Generic.IDictionary-2), which notably includes `[hashtable]` (`@{ ... }`, as a literal) and its ordered cousin, [`OrderedDictionary`](https://docs.microsoft.com/en-US/dotnet/api/System.Collections.Specialized.OrderedDictionary) (`[ordered] @{ ... }`, as a literal)

    * [`XmlNode`](https://docs.microsoft.com/en-US/dotnet/api/System.Xml.XmlNode), the base type for `[xml]` ([`XmlDocument`](https://docs.microsoft.com/en-US/dotnet/api/System.Xml.XmlDocument))

    * _Strings_ ([`String`](https://docs.microsoft.com/en-US/dotnet/api/System.String)); note that `'foo'.Count` is `1` (the intrinsic property reflecting that a string is considered a _scalar_ (single thing)), whereas `'foo'.Length` is `3` (the type-native property that returns the character count).

* **_Additionally_, [`System.Data.DataTable`](https://docs.microsoft.com/en-US/dotnet/api/System.Data.DataTable)** (which *itself* doesn't implement `IEnumerable`, only its `.Rows` property does).

See https://github.com/PowerShell/PowerShell/blob/48c7e112db8f0506a74555c83ecb8bec509b6597/src/System.Management.Automation/engine/LanguagePrimitives.cs#L523

**Comment by LaurentDardenne** [comment]
Thanks for these explanations, however accessing a non-existent property should generate an error.

**Comment by mklement0** [comment]
It does, if you use `Set-StrictMode -Version 2` or higher, just with any other property access:

```powershell
@{ Off = $true }, @{ Version = 2 }  | % {
  Write-Verbose -vb "-- With strict mode -$($_.Keys[0]):$($_.Values[0]):"
  Set-StrictMode @_
  ([pscustomobject] @{}).NoSuchProp
  [Data.DataTable]::new().NoSuchProp
}
```
