### ISSUE TITLE
add -LineNumber switch to select-string and get-content

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15192]
Hi Guys !!

with a large file ex log file its usefull to display the line number.

example: if we serach the term 'Error' within a large log file with select-string its useful to return the match string and the line number...

`PS > cat /var/myverybiglog.log | sls 'Error' -LineNumber`

**Comment by mklement0** [comment]
If you let `Select-String` read the file, you already get line-number information - and the command will perform much better as well:

```powershell
PS> 'a'..'z' > in.txt; Select-String q in.txt | Select Line, LineNumber

Line LineNumber
---- ----------
q            17
```

**Comment by p0W3RH311** [comment]
@mklement0 

thanks for this info. but the pipeline slow the operation + linenumber is much better if it present as switch parameter. also cmdlet like `get-content` and `format-table`  (index property in display)  need indexing the line number

**Comment by mklement0** [comment]
@p0W3RH311, yes, allowing `Get-Content` to directly allow selecting lines based on indices / line numbers would be helpful, similar to `Select-Object -Index` - see #3237

I don't understand how `Format-Table` would benefit from such a feature, however.
