### ISSUE TITLE
Using an open generic type with the -is operator causes a script-terminating error with a bad message

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15197]
## Steps to reproduce

```powershell
(1, 2) -is [System.Collections.Generic.IEnumerable`1]
```

Note: Only a _closed_ generic type works (`(1, 2) -is [System.Collections.Generic.IEnumerable[object]]`)

## Expected behavior

Either a meaningful statement-terminating error, or, preferably, `$true`, i.e., it would be nice if a test like this actually worked.

## Actual behavior

The following error occurs:

From a script:

```none
OperationStopped: Late bound operations cannot be performed on fields with types for which Type.ContainsGenericParameters is true.
```

From an interactive prompt, the error is unspecific:

```
ParentContainsErrorRecordException: An error occurred while creating the pipeline.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.4
```

**Comment by vexx32** [comment]
This likely won't be possible.

Even in C# this generates a compiler error, see [this SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5nJQDMmM6AwugN7Lp2YkBGA9swDboCyAFM4wFYBTAMYAXdMwCU6ALwA+CegCWAZ0xwiAHjn4kAXyA===).

**Comment by mklement0** [comment]
Thanks, @vexx32. Yes, for `IEnumerable1` use of the non-generic  `IEnumerable`  is a workaround, but it's not a general solution.

The problem is definitely solvable, albeit not with direct use of C# `is` / IL `isinst`:

```powershell
PS> [System.Collections.Generic.List[string]]::new().GetType().GetGenericTypeDefinition() -eq [System.Collections.Generic.List`1]
True
```

The question is whether it's worth it.

If not, we should emit a clear, specific error message.

**Comment by SeeminglyScience** [comment]
I think a clear error message is probably the way to go here.  A simple `Type.HasGenericParameters` check with a custom fail message.

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience, that would definitely be an improvement.

I don't feel strongly either way, but is your preference not to support this scenario more about how exotic it is, or are the performance concerns?

**Comment by LaurentDardenne** [comment]
no error with these syntaxes :
```powershell
$Type=[System.Collections.Generic.IEnumerable`1]
@(1, 2) -is $Type
#False
@(1, 2) -is 'System.Collections.Generic.IEnumerable`1'
#False

[System.Collections.Generic.List[Int]]$List=@(1..2)
$List -is 'System.Collections.Generic.IEnumerable[int]'
#True
$List -is 'System.Collections.Generic.IEnumerable`1'
#False
```

**Comment by mklement0** [comment]
Good point, @LaurentDardenne: via an intermediate variable assignment the error goes away - but the resulting behavior is arguably even more problematic than the outright error.

So we can either: 

* report an error in _both_ scenarios.
* or support them both.

And in order to make the right call, we need to understand (a) if this is a common enough use case and (b) if so, if there are implementation / performance concerns.

**Comment by SeeminglyScience** [comment]
> I don't feel strongly either way, but is your preference not to support this scenario more about how exotic it is, or are the performance concerns?

I don't think it's useful in enough situations to justify the custom - not really true - behavior (i.e. `object[]` isn't actually `IEnumerable<T>` even though it is `IEnumerable<object>`).

**Comment by mklement0** [comment]
Well, it _is_ true, just at a higher level of abstraction: if something is an (interface) implementation of a closed (concrete, with generic type parameters bound) type, it is by definition also an implementation of the more abstract open type (with unbound generic type parameters), and that's indeed how interfaces are reported via a type-info object's `.GetInterface(s)()` methods:

```powershell
PS> ([object[]] (1..2)).GetType().GetInterface('IEnumerable`1').Name
IEnumerable`1
```


And at least in the abstract (no pun intended) I can see it being useful.

Case in point: it would be useful for allowing PowerShell to determine whether an instance is a generic dictionary, irrespective of its specific key and value types (though, obviously, PowerShell would solve that problem in C#), to decide whether it should be enumerated in the pipeline - see #15204.
In that issue, @iSazonov links to a [blog post](https://tmont.com/blargh/2011/3/determining-if-an-open-generic-type-isassignablefrom-a-type) that states, "If you're asking why you might need to ever do something like this, you clearly haven't worked with enough Inversion of Control frameworks."

Granted, those scenarios may be less interesting in a PowerShell context.

---

If we decide not to support it, it sounds like @LaurentDardenne's findings imply that a _runtime_ check is also called for, so that _all_ of the following calls result in the same error message:

```powershell
(1, 2) -is [System.Collections.Generic.IEnumerable`1]                # already fails, but obscurely 
(1, 2) -is 'System.Collections.Generic.IEnumerable`1'                # misleadingly reports $false
(1, 2) -is ($var = [System.Collections.Generic.IEnumerable`1])       # misleadingly reports $false
```

**Comment by SeeminglyScience** [comment]
> that's indeed how interfaces are reported via a type-info object's `.GetInterface(s)()` methods:

The property `Type.Name` doesn't include generic parameters or arguments.  If you look at `FullName` you'll see it returns the constructed type.

> Granted, those scenarios may be less interesting in PowerShell code.

Yeah, I know you were mainly replying to @iSazonov here, but I've definitely had use for it.  Never in PowerShell though, and exceedingly rarely outside of it as well.

**Comment by mklement0** [comment]
> If you look at `FullName` you'll see it returns the constructed type.

Good point, thanks for clearing that up. However, the point about it being true in an abstract, meaningful sense stands, as evidenced by the fact that you can _query_ by the abstract name (which you don't disagree with in principle, it sounds).

So, going with the report-an-error scenario:

* Do you agree that _all_ of the command forms (type literal, string literal, variable) should result in the same error?
* Given that the type-literal scenario is a _parsing_ error, whereas the other two would have to be _runtime_ errors, if I understand correctly, how would we handle this?

**Comment by SeeminglyScience** [comment]
> Good point, thanks for clearing that up. However, the point about it being true in an abstract, meaningful sense stands, as evidenced by the fact that you can _query_ by the abstract name (which you don't disagree with in principle, it sounds).

You can query by the type name which is the same no matter what generic args are or are not specified.

For the record I'm definitely not saying it's impossible to determine, or that an API can't be written to query it. I'm not really sure what exactly is implied to be proven if that API did happen to work that way.

> * Do you agree that _all_ of the command forms (type literal, string literal, variable) should result in the same error?

Yeah, though it would be a breaking change. I don't have a strong opinion on if it's worth it.

> * Given that the type-literal scenario is a _parsing_ error, whereas the other two would have to be _runtime_ errors, if I understand correctly, how would we handle this?

It looks like compile time to me, e.g. ```$sb = { $list -is [Collections.Generic.IEnumerable`1] }``` doesn't throw, but first invoke before any execution will.

Ideally all of the errors would be runtime, maybe with classes as an exception.

**Comment by mklement0** [comment]
> You can query by the type name which is the same no matter what generic args are or are not specified.

Indeed. Just to clarify the [terminology](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generics-and-attributes), you can query for an interface by the name of its _open_ generic type, i.e. a generic type whose type parameters haven't been bound yet, as opposed to one whose have, making it a _closed_ (constructed) generic type.

> not saying it's impossible to determine, or that an API can't be written to query it.

We already know that it's possible:

For interfaces:

```powershell
$null -ne ([object[]] (1..2)).GetType().GetInterface('IEnumerable`1')
```

For concrete types:

```powershell
([System.Collections.Generic.List[int]]::new()).GetType().GetGenericTypeDefinition() -eq [System.Collections.Generic.List`1]
```

---

But leaving that aside, I'd personally be happy with a consistently reported _error_.

You're right, it is technically a breaking change, although it sounds like a classic [bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) case to me:
Currently a string literal or variable as the RHS _always results in `$false`_ with an open generic type, making the current behavior useless.

As for when the error occurs: my understanding is superficial in this area, but there is definitely a difference:

```powershell
' $list -is   [Collections.Generic.IEnumerable`1]; ''after'' ' > t1.ps1
' $list -is ''Collections.Generic.IEnumerable`1''; ''after'' ' > t2.ps1
```

```powershell
PS> ./t1.ps1
OperationStopped: Late bound operations cannot be performed on fields with types for which Type.ContainsGenericParameters is true.
```

vs.

```powershell
PS> ./t2.ps1
False
after
```

**Comment by mklement0** [comment]
As for when the error occurs:

It seems that I incorrectly inferred from the fact that a _script_-terminating error occurs that it happens at parse time, but the real problem is apparently just that: it should be a _statement_-terminating error, right?

```powershell
' $list -is   [Collections.Generic.IEnumerable`1]; ''after'' ' > t1.ps1
' 1/0; ''after'' ' > t2.ps1
```

```powershell
PS> ./t1.ps1
OperationStopped: Late bound operations cannot be performed on fields with types for which Type.ContainsGenericParameters is true.
```

vs.

```powershell
PS> ./t2.ps1
RuntimeException: /Users/mklement/Desktop/pg/t2.ps1:1
Line |
   1 |   1/0; 'after'
     |   ~~~
     | Attempted to divide by zero.

after
```

**Comment by SeeminglyScience** [comment]
> Indeed. Just to clarify the [terminology](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generics-and-attributes), you can query for an interface by the name of its _open_ generic type, i.e. a generic type whose type parameters haven't been bound yet, as opposed to one whose have, making it a _closed_ (constructed) generic type.

The type name is the same whether it's an open or closed generic.

I think the confusing part here is that in PowerShell, you need to include the airty specification to reference the open generic, but that's just a PowerShell thing.  The airty is pure compiler convention, both in the type definition and the omission of it when referencing the type, but it's always there in the metadata and surfaced in reflection.

> > not saying it's impossible to determine, or that an API can't be written to query it.
> 
> We already know that it's possible:

I wasn't clear, but yeah that's what I was saying.

> it should be a statement-terminating error, right?

I'd follow whatever `'' -is [notarealtype]` does outside of classes.

**Comment by mklement0** [comment]
> that's just a PowerShell thing. 

The arity notation (e.g., ``IEnumerable`1``) is a language-agnostic _.NET API_ thing that PowerShell also (sensibly) happens to use - if it were PowerShell-specific, something like ``.GetInterface('IEnumerable`1`)`` wouldn't work.

> I'd follow whatever '' -is [notarealtype] does outside of classes.

Makes sense, and your example indeed produces a _statement_-terminating error (unlike the current `` $foo -is [System.Collections.Generic.IEnumerable`1]`` behavior).

(And, to recap: I wish that _statement_-terminating errors had never existed - see https://github.com/PowerShell/PowerShell/issues/14819#issuecomment-790637199)

**Comment by SeeminglyScience** [comment]
> > that's just a PowerShell thing.
> 
> The arity notation (e.g., `` IEnumerable`1 ``) is a language-agnostic _.NET API_ thing that PowerShell also (sensibly) happens to use - if it were PowerShell-specific, something like `` .GetInterface('IEnumerable`1') `` wouldn't work.

Yeah I'm aware. I was referring to it being required to reference an open generic.  Point being, it's always part of the type name

**Comment by mklement0** [comment]
I'm glad you're aware, @SeeminglyScience, but how you expressed that awareness ("that's just a PowerShell thing") was potentially misleading. My comment tried to clarify, so as to avoid any potential confusion.

**Comment by mklement0** [comment]
Let me try to close that tangent by clarifying the relationship between [the .NET API's language-agnostic type-name notation](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names) and the functionality that PowerShell _overlays_ on it:

* PowerShell allows enclosing a verbatim type name in .NET notation in `[...]` to form a _type literal_ (a [`System.Reflection.TypeInfo`](https://docs.microsoft.com/en-US/dotnet/api/System.Reflection.TypeInfo) instance), such as ``[System.Collections.Generic.IEnumerable`1]``

* In a verbatim type name, PowerShell additionally allows referring to a _closed_ generic type by directly enclosing the type-parameter arguments as _nested_ type literals:
  * That is, while the .NET type-name notation only allows referring to _open_ generic types (e.g.. `` System.Collections.Generic.IDictionary`2 ``), PowerShell also allows you to refer to _closed_ (constructed) ones.
  * When doing so, also specifying the _arity_ is _optional_; e.g., the following two type literals both refer to the same  closed (constructed) type that in C# would be expressed as `` IDictionary<string, int> ``:
    * `` [System.Collections.Generic.IDictionary`2[string, int]] `` - arity explicitly specified
    * `` [System.Collections.Generic.IDictionary[string, int]] ``  - arity _implied_ by the number of nested type literals

**Comment by mklement0** [comment]
(I just learned a lesson I should have learned before: don't trust the docs to tell the fully story. In short: the .NET API type-name notation _does_ support specifying _closed_ generic types (which, of course, I should have expected); seemingly, the only PowerShell overlay in this respect is that it makes specifying the arity _explicitly_ optional - I've updated the previous comment.)

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this and agree that a better error message should be emitted.
