### ISSUE TITLE
Add auto path completion for Read-Host

### ISSUE THREAD

**Issue by Andy-AO** [PowerShell/PowerShell#15199]
The PowerShell function being written to generate folders based on templates.

It has a "target path" parameter that is expected to be a subdirectory of a specific directory, so it wants to provide the user with a path completion basis, but there is no such completion mechanism in the `Read-Host` state.

Although there is a completion mechanism when entering the parameters, the working directory does not change at that time, so the user has to switch the working directory manually, which makes the experience very bad.

CMD has this feature, but PowerShell does not, so this is a problem.

Looking at [StackOverFlow](https://stackoverflow.com/questions/22509719/how-to-enable-autocompletion-while-entering-paths), a temporary solution was found to use the GUI, but this has a lot of problems and doesn't work in many cases.

A similar [issue](https://github.com/PowerShell/PowerShell/issues/6571) has been found, but this issue already has an alternative method, and the path completion seems to have not.

**Comment by Andy-AO** [comment]
The code  ↓

```PowerShell

function New-FolderBaseTemplate {
    param (
        [Parameter()]
        [ValidateSet("PyCharm")]
        [String]
        $ActionName,
        [Parameter()]
        [String]
        $InstanceName
    )
    if($ActionName -eq "PyCharm"){
        $TargetRootLocation  = 'D:\MyDocs\pycharm_pro'
        Set-Location $TargetRootLocation
        $TargetLocation = Read-Host 'Please select directory.'
        $params = @{
            NewInstanceName = $InstanceName
            TargetLocation  = $TargetLocation
            TemplatePath    = "$TargetLocation\.template"
        }
        NewFolderFromTemplate @params
    }
}
```

**Comment by mklement0** [comment]
While not specifically about tab-completion, https://github.com/PowerShell/PSReadLine/issues/881 proposes making `Read-Host` use an enhanced `PSConsoleHostReadLine` function by default; the latter is highly customizable (adding syntactic sugar for tab-completion functionality is conceivable).
