### ISSUE TITLE
^C stop whole PowerShell

### ISSUE THREAD

**Issue by Suyun514** [PowerShell/PowerShell#15195]
## Steps to reproduce

```powershell
python3 -c 'input()'
^C
```

## Expected behavior

```none
The `python3.exe` should quit, and I should see the shell prompt.
```

## Actual behavior

```none
While using `conhost.exe`, it works normally.
But while using Windows Terminal (Preview 1.7.572.0) or Alacritty (0.7.2), The whole PowerShell stopped.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by powercode** [comment]
What version of Windows Terminal and Python are you using? 

I could not reproduce with Windows Terminal Version: 1.6.10571.0 and Python 3.9.

**Comment by Suyun514** [comment]
> What version of Windows Terminal and Python are you using?
> 
> I could not reproduce with Windows Terminal Version: 1.6.10571.0 and Python 3.9.

Windows Terminal 1.7.572.0
Python 3.9.4

And I am sorry that the previous command was wrong, and the correct command is `python3 -c 'input()'`.

**Comment by Suyun514** [comment]
I created a GIF to show the problem:
![](https://user-images.githubusercontent.com/52325399/115106506-d0639f80-9f97-11eb-9c50-e11daeba2867.gif)

**Comment by powercode** [comment]
This is not happening on any of my machines. Can you run it under a debugger?

**Comment by daxian-dbw** [comment]
I cannot reproduce either, and I'm using Windows Terminal Preview 1.9.1523.0

![image](https://user-images.githubusercontent.com/127450/121435667-26b7e380-c934-11eb-8de1-eaea9d1ce2ed.png)

**Comment by JamesWTruher** [comment]
I'm sorry, but we can't reproduce this. Please re-open it if you have a repro with a recent terminal.
