### ISSUE TITLE
xpath 3.1

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15198]
hello guys !!

PS as C# dont support xpath > 1.0 because it use old library and MS seem not upgrade here library. many Microsoft XML adopt LINQ to XML, which doesn't address the same problem-space.

now with xpath 3.1 we can query xml and also json easily and with powerfull mini-language. 
 its possible to adopt another library like saxon.net or others third party instead to old library ?

**Comment by iSazonov** [comment]
PowerShell usually follows .Net. So right quest is whether .Net support XPath 3.1?

**Comment by p0W3RH311** [comment]
@iSazonov 

thanks 

yes PS follows .NET but if .NET does not offer an _official_ technology, it is not a reason not to implement it, especially if this technology is efficient. there are third party implementations of XPATH 3.1 like saxon.net and others.

**Comment by iSazonov** [comment]
I guess that the community is moving towards Json and no one wants to invest in XML.
