### ISSUE TITLE
Question -  change ThreadOptions property to UseCurrentThread

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/PowerShell#15194]
Hi,

It's possible to change ThreadOptions property to UseCurrentThread for the currently launched pwsh process **from the ps1 script itself?**

Things I've tried:

`CreateRunspace(  [NamedPipeConnectionInfo]::new($PID), $host, [TypeTable]::LoadDefaultTypeFiles())`

and

`CreateOutOfProcessRunspace([TypeTable]::LoadDefaultTypeFiles(), [PowerShellProcessInstance]::new())`
but none of those was sucesfull.

@iSazonov @daxian-dbw

**Comment by iSazonov** [comment]
I don't understand why you need this for.
PowerShell sets already this. See how `PSThreadOptions.UseCurrentThread` is used.

**Comment by ALIENQuake** [comment]
@iSazonov 
Changing ThreadOptions is required for PS-driven Avalonia/NET MAUI GUI apps in order to be successfully launched on Mac OS since it requires the GUI thread to be the main one.

Background: https://github.com/ironmansoftware/psavalonia/issues/1

Code line: https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1732

I was able to change ThreadOptions property by combining c# app + `$Runspace.ThreadOptions 
 = [PSThreadOptions]::UseCurrentThread` + loading script from the file.

The question is, can I still do it via some trick for the currently launched pwsh process from the launched ps1 script itself? Like pwsh > launch script > change current pwsh process ThreadOptions > continue to execute script?

**Comment by iSazonov** [comment]
@ALIENQuake I quickly looked at the issue you referred and I can hardly say more than @TylerLeonhardt and @SteveL-MSFT.

I see https://github.com/PowerShell/GraphicalTools has a plan to migrate from Avalonia to MAUI and MAUI is moving to release so I'd expect we will have to do something in PowerShell repo to enable MAUI. Thus for WPF, we changed pwsh build process. Maybe it makes sense to ask in the MAUI repo.

Regarding the fix in consolehost, I fear it will backfire. I'd rather expect to see an generic graphical host instead.

**Comment by ALIENQuake** [comment]
@iSazonov I was fear that bringing the 'reason' might cloud the view over the question itself. It's not about 'fix' inside PowerShell code thus changing the default ThreadOptions. It's about 'an ability to change ThreadOptions on the current(or spawned) pwsh process from the ps1 script itself:

c# app > Runspace > change ThreadOptions on runspace : works
pwsh > launching ps1 script> Runspace > change ThreadOptions on pwsh process itself : possible?

If this is a chicken-egg problem, I just need confirmation that I cannot be done.

**Comment by SeeminglyScience** [comment]
> If this is a chicken-egg problem, I just need confirmation that I cannot be done.

It can't be done, the thread options can only be changed before the runspace is opened.  `ReuseThread` is hard coded into `ConsoleHost` (or `Executor`? one of those classes).

**Comment by iSazonov** [comment]
@ALIENQuake As @SeeminglyScience said, you cannot do it. You can only make a custom build for your experiments.

**Comment by ALIENQuake** [comment]
@iSazonov @SeeminglyScience Thanks both of you, much appreciated.
