### ISSUE TITLE
A dictionary type that only implements the generic IDictionary interface is unexpectedly enumerated in the pipeline

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15204]
PowerShell makes a hard-coded exception for types that implement the _non-generic_ `System.Collections.IDictionary` interface with respect to behavior in the pipeline: even though such types are _enumerable_, PowerShell sends them _as a whole_ through the pipeline.

Source code here: https://github.com/PowerShell/PowerShell/blob/48c7e112db8f0506a74555c83ecb8bec509b6597/src/System.Management.Automation/engine/LanguagePrimitives.cs#L523-L543

However, some types _only_ implement the _generic_ equivalent of this interface, `System.Collections.Generic.IDictionary<TKey, TValue>`.
Such type are therefore unexpectedly _enumerated_ in the pipeline, i.e their _key-value_ pairs are sent rather than the dictionary itself.

Note that while with the `IEnumerable` / `IEnumerable<Type>` interface pair implementing the generic version _implicitly_ also implements the non-generic one, this does _not_ apply to the `IDictionary` / `IDictionary<TKey, TValue>` pair.

I don't know what the official recommendations are in this case, but at least one notable example of a type that _only_ implements the generic interface is [`System.Dynamic.ExpandoObject`](https://docs.microsoft.com/en-US/dotnet/api/System.Dynamic.ExpandoObject), used in the repro below.

## Steps to reproduce

```powershell
$o = [System.Dynamic.ExpandoObject]::new(); $o.one = 1; $o.two = 2

($o | Measure-Object).Count | Should -Be 1
```

## Expected behavior

The test should succeed: the `IDictionary`2`-implementing type's instance should be sent _as a whole_ through the pipeline.

## Actual behavior

The test fails, because the instance is enumerated and its key-value pairs are sent through the pipeline.

```none
InvalidResult: Expected 1, but got 2.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.4
```

**Comment by iSazonov** [comment]
This could be too expensive to implement https://tmont.com/blargh/2011/3/determining-if-an-open-generic-type-isassignablefrom-a-type

Without an critical scenario I'd freeze the fix.

**Comment by mklement0** [comment]
A streamlined test is possible:

```csharp
! (objectType.GetInterface("System.Collections.Generic.IDictionary`2", false) is null)
```

And, even though it is an _additional_ test that must be performed, the performance impact is surprisingly small:

Here is sample output from running the benchmarks below on my macOS 10.15.7 system with .NET 6.0.100-preview.3.21202.5

```none
Cumulative timings from 1000 runs:
  non-generic, .IsAssignableFrom()   : 00:00:00.0031652
  generic, .GetInterface()           : 00:00:00.0033636
  combined                           : 00:00:00.0035919
Ratio of generic vs. non-generic test : 1.06
Ratio of combined vs. non-generic test: 1.13
```

In repeated runs the ranking of ratios on occasion even reverses (the _combined_ test is reported as faster) or the two ratios are the same. (The input type was chosen so that _both_ tests are indeed performed so that no short-circuiting occurs).

It is possible that my benchmarks (see below) are flawed; I have little experience with profiling C# code.


<details>
<summary>Benchmark code:</summary>

```csharp
using System;
using System.Collections.Generic;
using System.Collections;
using System.Diagnostics;
using System.Dynamic;

namespace demo
{

  class Program
  {
    static TimeSpan timeAction(Action action, int runs)
    {
      var thisProcess = Process.GetCurrentProcess();
      TimeSpan tsBefore, tsAfter, tsTotal = new TimeSpan(0);
      for (var i = 0; i < runs; ++i)
      {
        tsBefore = thisProcess.TotalProcessorTime;
        action.Invoke();
        tsAfter = thisProcess.TotalProcessorTime;
        tsTotal += tsAfter - tsBefore;
      }
      return tsTotal;
    }

    static void Main(string[] args)
    {

      var obj = new ExpandoObject();
      var objectType = obj.GetType();

      string[] descriptions =
      {
        "non-generic, .IsAssignableFrom()",
        "generic, .GetInterface()",
        "combined"
      };

      Action[] actions =
      {
        () => { var isNonGenericDict  = typeof(IDictionary).IsAssignableFrom(objectType); },
        () => { var isGenericDict     = ! (objectType.GetInterface("System.Collections.Generic.IDictionary`2", false) is null); },
        () => { var isEither          = typeof(IDictionary).IsAssignableFrom(objectType) || ! (objectType.GetInterface("System.Collections.Generic.IDictionary`2", false) is null); }
      };

      // Run the commands in isolation first, to level the playing field with
      // respect to one-time initializations, such as loading types on demand.
      foreach (var action in actions) { action.Invoke(); }

      // Run the benchmarks:
      int runs = 1000; 
      List<TimeSpan> timings = new();
      foreach (var action in actions)
      {
        timings.Add(timeAction(action, runs));
      }

      Console.WriteLine($"Cumulative timings from {runs} runs:");
      var i = 0;
      foreach (var ts in timings)
      {
        Console.WriteLine($"  {descriptions[i++].PadRight(35)}: {ts}");
      }
      Console.WriteLine($"Ratio of generic vs. non-generic test : {timings[1] / timings[0]:N2}");
      Console.WriteLine($"Ratio of combined vs. non-generic test: {timings[2] / timings[0]:N2}");

    } // Main()

  } // class

} // namespace
```
</details>

**Comment by SeeminglyScience** [comment]
> It is possible that my benchmarks (see below) are flawed; I have little experience with profiling C# code.

[BenchmarkDotNet](https://benchmarkdotnet.org/) is the standard. Really difficult to get reliable results outside of it.

**Comment by mklement0** [comment]
I appreciate the pointer, @SeeminglyScience.

Using BenchmarkDotNet indeed paints a different picture:

```none
|            Method |      Mean |    Error |   StdDev |
|------------------ |----------:|---------:|---------:|
|    TestForGeneric | 167.66 ns | 1.836 ns | 1.627 ns |
| TestForNonGeneric |  11.82 ns | 0.075 ns | 0.071 ns |
|     TestForEither | 183.13 ns | 1.491 ns | 1.322 ns |
```

That is, the combined test takes around 16 times as long as the current, non-generic-interface-only test, on my macOS 10.15.7 machine with .NET 6.0.100-preview.3.21202.5

What that would mean in terms of real-world impact I don't know.

<details>
<summary>Benchmark code based on BenchmarkDotNet</summary>
```csharp
using System;
using System.Collections;
using System.Dynamic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace csbm
{
  public class InterfaceTestBenchmarks
  {

    // A type that implements IDictionary`2, but not also the non-generic IDictionary interface.
    static readonly Type s_typeToInspect = new ExpandoObject().GetType();

    [Benchmark]
    public bool TestForGeneric()
    {
        return ! (s_typeToInspect.GetInterface("System.Collections.Generic.IDictionary`2") is null);
    }
    
    [Benchmark]
    public bool TestForNonGeneric()
    {
        return typeof(IDictionary).IsAssignableFrom(s_typeToInspect);
    }

    [Benchmark]
    public bool TestForEither()
    {
        return typeof(IDictionary).IsAssignableFrom(s_typeToInspect) || ! (s_typeToInspect.GetInterface("System.Collections.Generic.IDictionary`2") is null);
    }

  }
  class Program
  {
    static void Main(string[] args)
    {
        // For verifying that the tests are correct: Should be False, True, True
        Console.WriteLine(new InterfaceTestBenchmarks().TestForNonGeneric());
        Console.WriteLine(new InterfaceTestBenchmarks().TestForGeneric());
        Console.WriteLine(new InterfaceTestBenchmarks().TestForEither());

        BenchmarkRunner.Run<InterfaceTestBenchmarks>();
    }
  }

}
```
</details>

**Comment by iSazonov** [comment]
> What that would mean in terms of real-world impact I don't know.

I see over 40 code path use the method so it is a high risk to catch a performance regression.

Since we are in C#, not in script, I guess there is more fast way for the check. https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-examine-and-instantiate-generic-types-with-reflection

**Comment by mklement0** [comment]
Thanks, @iSazonov, but I don't see a faster way to do it based on the linked article. Did you have a specific approach in mind?

**Comment by iSazonov** [comment]
I believe we could fix the issue in `private static IEnumerable GetEnumerableFromIEnumerableT(object obj)` method. We fallback to the method for generics.
https://github.com/PowerShell/PowerShell/blob/2f3f39906f6f58e1028672ae3aeffb83934c5153/src/System.Management.Automation/engine/LanguagePrimitives.cs#L402-L413

**Comment by mklement0** [comment]
That actually performs worse than the `.GetInterface("...")` approach (but it outperforms the delegate-based `.FindInterfaces()` approach):

```none
|                                  Method |     Mean |   Error |  StdDev |
|---------------------------------------- |---------:|--------:|--------:|
|          TestForGeneric_GetByNameString | 169.7 ns | 2.37 ns | 2.22 ns |
| TestForGeneric_EnumerateAndCompareTypes | 225.2 ns | 1.53 ns | 1.35 ns |
|           TestForGeneric_FindInterfaces | 283.5 ns | 2.53 ns | 2.37 ns |
```

<details>
<summary>Benchmark code:</summary>

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Dynamic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace csbm
{
  public class InterfaceTestBenchmarks
  {

    // A type that implements IDictionary`2, but not also the non-generic IDictionary interface.
    static readonly Type s_typeToInspect = typeof(ExpandoObject);

    [Benchmark]
    public bool TestForGeneric_GetByNameString()
    {
        return s_typeToInspect.GetInterface("System.Collections.Generic.IDictionary`2") != null;
    }

    [Benchmark]
    public bool TestForGeneric_EnumerateAndCompareTypes()
    {
     foreach (Type i in s_typeToInspect.GetInterfaces()) 
     { 
         if (i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>)) return true;
     }
     return false;
    }
    
    [Benchmark]
    public bool TestForGeneric_FindInterfaces()
    {
     return 0 != s_typeToInspect.FindInterfaces((t, o) => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>), null).Length;
    }
    
  }
  class Program
  {
    static void Main(string[] args)
    {
        // For verifying that the tests are correct: Should be True, True, True
        Console.WriteLine(new InterfaceTestBenchmarks().TestForGeneric_GetByNameString());
        Console.WriteLine(new InterfaceTestBenchmarks().TestForGeneric_EnumerateAndCompareTypes());
        Console.WriteLine(new InterfaceTestBenchmarks().TestForGeneric_FindInterfaces());
 
        BenchmarkRunner.Run<InterfaceTestBenchmarks>();
    }
  }

}
```

</detals>

**Comment by iSazonov** [comment]
GetEnumerableFromIEnumerableT should return null for IDictionary`2 too so we need to enumerate `obj.GetType().GetInterfaces()` in any case.

**Comment by mklement0** [comment]
Oops! I missed that you had used ``IEnumerable`1`` in your example rather than `` IDictionary`2 `` - if I fix the code above to use the latter, the enumerate-and-compare approach outperforms `.GetInterface("...")` - but that tells us that the speed is dependent on the order in which the interfaces happen to be enumerated (`` IDictionary`2 `` comes 2nd, ``IEnumerable`1`` 4th with type `ExpandoObject`).

Good point about needing to enumerate all interfaces anyway.

**Comment by iSazonov** [comment]
Performance will not be affected since if this fallback happens then we enumerate the interfaces anyway and one more check does not add noticeable delay.

**Comment by mklement0** [comment]
However, assuming I'm reading the code correctly, this interface enumeration currently only happens in _exceptional_ circumstances, namely when calling `.GetEnumerator()` on the non-generic `IEnumerable` unexpectedly returns `null` or throws an exception. 

There also seems to be an inconsistency in the code: in the `null` case, the absence of the generic ``IEnumerable`1`` results in `null` getting returned, whereas if an exception occurred a (different) exception is thrown:

https://github.com/PowerShell/PowerShell/blob/2f3f39906f6f58e1028672ae3aeffb83934c5153/src/System.Management.Automation/engine/LanguagePrimitives.cs#L493-L523

**Comment by iSazonov** [comment]
I played with debugger and it seems we consider wrong code path for the issue. The methods are only called from formatting subsystem.
Also `internal static IEnumerable GetEnumerable(object obj)` has specific code path for IDictionary to consider it as IEnumerable. why should generic IEnumerable behave else?

**Comment by mklement0** [comment]
The difference in enumeration behavior between _processing in the pipeline_ and _output formatting_ is by design:

* In the pipeline, dictionaries should  _not_ be enumerated, irrespective of whether they're non-generic(-only) or generic(-only) dictionaries. That its, it makes sense to think of them more like an _object with properties_ (entries), analogous to a `[pscustomobject]` instance.

* In output formatting, you _do_ want enumeration, so as to present a tabular display of the entries (key-value pairs).

This distinction has always existed, and makes sense.

There is no reason for a given dictionary to behave differently, just because of an _implementation detail_ (implementing _only_ the generic interface, not also the non-generic one).

That is the _conceptual_ view. I do get the _pragmatic_ perspective:

* Such generic-interface-only types _may_ be rare in practice (I don't know).

* Fixing the problem may worsen performance.

My general preference is always to fix inconsistencies, especially such obscure ones, but I understand that pragmatic considerations may prevail.

Looking at the code, there definitely seems to be potential for optimization, though that may be outweighed by introducing _unconditional_ enumeration of all interfaces. Personally, I think it's worth a closer look, but it's certainly a tricky area of the code, and we should understand the real-world performance implications.

**Comment by iSazonov** [comment]
So we have two issue - (1) in pipeline, (2) in formatting.

For (1) we need to find the place to fix and investigate performance risk.
For (2) we already found the fix place. I haven't  a concern about performance since we already enumerate all interfaces. We need explicit examples which we could use as tests.

**Comment by mklement0** [comment]
Well, for (2) we don't need a fix, because we _do_ want such generic-interface-only dictionaries to be enumerated for _formatting_ purposes, and that's already happening (though maybe cleanup / adding comments is called for):

```powershell
# System.Dynamic.ExpandoObject implements only IDictionary`2, not also IDictionary.
PS> $o = [System.Dynamic.ExpandoObject]::new(); $o.foo = 1; $o.bar = 2; $o

Key Value
--- -----
foo     1
bar     2
```

**Comment by vexx32** [comment]
We discussed this today in the Engine Working Group.

We all generally agree that the current behaviour is unintuitive and arguably bugged. Concerns were raised about the potential performance implications, although we all agree that we don't have sufficient data at this point to rule one way or another.

@mklement0's benchmarks are a great starting point, and we'd like to see a combination of isolated tests and testing done after making the change in PowerShell itself to determine in context how much of a difference it would cause.

At minimum, we think we'd need to have the following test cases for comparison's sake:

- Processing objects that implement neither `IDictionary` nor `IDictionary<,>`
- Processing objects that implement `IDictionary`
- Processing objects that implement `IDictionary<,>`

For each of these, we'd need to compare the current and proposed new behaviour in an isolated benchmark, as well as tests done within PowerShell before and after making the change to compare performance differences in-context.

If anyone has additional suggestions on ways to implement the check that may have a lesser performance impact than the already given suggestions, those are also worth discussing as well. 🙂
