### ISSUE TITLE
Skip CI runs for PRs that do not result in code change

### ISSUE THREAD

**Issue by raghushantha** [PowerShell/PowerShell#1520]
Changes to documentation do not need CI runs.

However changes to tools/test/assets/src needs CI.

This will speed up our doc related checkins

**Comment by andschwa** [comment]
This was already attempted in https://github.com/PowerShell/PowerShell/pull/1478 but proved not to be possible to do reliably.

**Comment by SteveL-MSFT** [comment]
Since CI runs the spell checker, I don't think this is relevant anymore.
