### ISSUE TITLE
-Recurse option in Get-ChildItem suppresses the non-existent path error

### ISSUE THREAD

**Issue by amfogor** [PowerShell/PowerShell#15201]
## Steps to reproduce

```powershell
Get-ChildItem nonexistentfolder -Recurse
```

## Expected behavior

Behave the same as without the option

```powershell
Get-ChildItem nonexistentfolder
```

Get the error

```none
Get-ChildItem: Cannot find path 'nonexistentfolder' because it does not exist
```

## Actual behavior

Nothing happens

## Environment data

```none
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
This is the result of the very unfortunate behavior discussed in #5699.

It was decided not to fix this treacherous behavior in the interest of backward compatibility, and the PowerSell committee's recommendation was to make ["the behavior change in a FileSystemProvider v2 implementation"](https://github.com/PowerShell/PowerShell/issues/5699#issuecomment-428755272), though I'm unclear on what that means in concrete terms.
