### ISSUE TITLE
Improve the performance of Set-Content / Add-Content -AsByteStream

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15208]
## Summary of the new feature/enhancement

Passing a `[byte[]]` array to `Set-Content` / `Add-Content -AsByteStream` should result in efficiently writing the given bytes.

Currently, this is excessively slow, because _each byte is converted to `[object]`_ on parameter binding, as @powercode has discovered in https://github.com/PowerShell/PowerShell/issues/15188#issuecomment-816581316.

In effect, PowerShell currently lacks an efficient way to write a byte array to a file, making direct use of .NET APIs necessary.

To demonstrate the problem:

```powershell
# !! This is excessively slow.
Set-Content tmp.bin -AsByteStream -Value ([byte[]]::new(32mb))
```

The above takes about 30 seconds(!) on my machine, even though only 32 MB is written.

By contrast, the equivalent .NET solution completes almost instantaneously:

```powershell
[IO.File]::WriteAllBytes("$pwd/tmp.bin", [byte[]]::new(32mb))
```

## Proposed technical implementation details (optional)

Change the type of the `-Value`  parameter from `object[]` to `object`, and perform cmdlet-_internal_ detection of `byte[]` input.

As @powercode notes, we need to ensure that this causes no backward-compatibility issues.

**Comment by AndersZH** [comment]
Is there any updates on this. I can confirm that this is still an issue in PS 7.2.7. Using the Set-Content is approximately 300 (three hundred!) times SLOWER than using the native [io.file]::WriteAllBytes().

**Comment by powercode** [comment]
Live!
