### ISSUE TITLE
enter-pssession is not Case sensitive with -Hostname. but .SSH is in its config

### ISSUE THREAD

**Issue by matsmcp** [PowerShell/PowerShell#15219]
## Steps to reproduce

I found this one while working with a personal config file (.ssh/config)
in my config I have an entry:

Host DC
  Hostname dc.example.org

if I run SSH DC it will work. 
if I try to do enter-pssession -hostname DC it will fail and complain that it cant resolve dc (observe the lower case). 
It seems like SSH preserves the case but enter-pssession doesn't. 

Powershell 7.1.2
openssh 8.1
server 2022

**Comment by PaulHigin** [comment]
WG-Remoting:
PowerShell itself is case insensitive, but PowerShell should preserve case.
