### ISSUE TITLE
NewLine is added to output when told to explicitly drop NewLine

### ISSUE THREAD

**Issue by johnjelinek** [PowerShell/PowerShell#15222]
A newline is getting added to the output when running `echo` even if I tell it not to (with `-n` flag). It also looks like `Write-Out` doesn't support `-NoNewLine`.

## Steps to reproduce

```powershell
echo 'hello' | base64
```

## Expected behavior

```none
> echo 'hello' | base64
aGVsbG8K
> echo -n 'hello' | base64
aGVsbG8=
```

## Actual behavior

```none
> echo 'hello' | base64
aGVsbG8K
> echo -n 'hello' | base64
aGVsbG8K
```

## Environment data

```none
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
`echo` is an alias for Write-Output. Your `-n` is treated as `-NoEnumerate`, not `-NoNewLine`.

Not sure why echo / write-output is needed here? `"hello" | base64` should do what you want

**Comment by mklement0** [comment]
Yes, unfortunately the trailing newline can currently not be prevented - please see #5974

**Comment by jborean93** [comment]
As a workaround you can use the .NET method instead of relying on platform specific binaries being place.

```powershell
[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('hello'))
```

It's more verbose but the benefit is that it it's portable, unlike calling `base64` which won't work on hosts without that binary. You also have fine control over the encoding used on the string.

**Comment by mklement0** [comment]
@jborean93, on a quick meta note: I know that my user name _looks_ like it has the word "element" in it, but it actually doesn't (the unexciting truth is that it is simply a contraction of my name).

**Comment by SeeminglyScience** [comment]
> @jborean93, on a quick meta note: I know that my user name _looks_ like it has the word "element" in it, but it actually doesn't (the unexciting truth is that it is simply a contraction of my name).

I 100% still read it in my head as "MK Element" even after noticing that's not what it is 😁

**Comment by jborean93** [comment]
My apologies, I'm totally with SeeminglyScience where that's how I say it in my head but I'll have to try harder next time :)

**Comment by mklement0** [comment]
@SeeminglyScience and @jborean93: 😁 .
No worries, @jborean93 - it's an understandable mistake to make, but I figured since we'll likely have more conversations in the future, I'd clarify.

**Comment by johnjelinek** [comment]
@jborean93: so, I'm the only one on the team using `pwsh` for mac right now. The rest are on zsh/fish -- I wanted to write docs that are portable to the rest of my team. The `.NET` way won't work for my use-case. 'Tis a shame, I will have to switch shells to be pragmatic for now.

**Comment by mklement0** [comment]
@johnjelinek, calling the platform-native shell is always an option:

```powershell
PS> sh -c "echo 'hello' | base64"
aGVsbG8K
```

**Comment by mklement0** [comment]
To generalize the approach:

```powershell
PS> sh -c 'echo "$1" | base64' - 'hello'
aGVsbG8K
```

**Comment by mklement0** [comment]
P.S., @johnjelinek: passing a string such as `'printf %s "$1" | base64'` to _external programs_ (such as `sh`) currently results in the  embedded `"` characters effectively getting _stripped_, which is a long-standing problem - see https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-562334606. PR #14692 is aiming to fix on an opt-in basis, initially as an experimental feature. ##15143 additionally proposes important accommodations on Windows.

**Comment by johnjelinek** [comment]
Ok, thanks for the help! Do we want to leave this open or close the issue?

**Comment by mklement0** [comment]
@johnjelinek:

* Your original (legitimate) complaint is covered by #5974, so, yes, I suggest closing this issue.

* Independently, if something is unclear about the comments above - as your use of the 😕 emoji suggests -  feel free to ask for clarification.
  * By contrast, if your use of 😕 is meant to express _disapproval of the status quo_, I suggest expressing that verbally, to avoid confusion.

**Comment by mklement0** [comment]
PowerShell Core 7.2.0-preview.5 has just been released, which includes the `PSNativeCommandArgumentPassing` [experimental feature](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Experimental_Features) that fixes the embedded-double-quotes problem _fully_ on Unix, and _partially_ on Windows. (Preview releases have experimental features turned _on by default_, but not release candidates and regular releases).

Thus, in PowerShell Core 7.2.0-preview.5 the following now works correctly on Unix-like platforms (assuming the experimental feature is on and the `$PSNativeCommandArgumentPassing` preference variable is at its default, `'Standard'`):

```powershell
# Malfunctions in PowerShell Core 7.2.0-preview.4 and below, because `"$1"` turns into `$1`, which
# makes `sh` perform word-splitting, resulting in *two* arguments.
PS> sh -c 'printf %s "$1" | base64' - 'hello more'
aGVsbG8gbW9yZQ==
```
