### ISSUE TITLE
Console Output on SSH Remoting Session Breaks Session

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#15229]
When an SSH remoting session is created the server doesn't seem to redirect the stdout pipe to nothing so anything that writes to stdout is picked up and treated as a PSRP fragment from the server. Because these fragments are designed in a particular way and should come in sequence it's pretty much going to crash the process because the client cannot treat the message as a PSRP response.

Funnily enough the server mode setup with `-s` sets the Stdout/Stderr/Stdin streams to `TextWriter.Null` alleviating this problem https://github.com/PowerShell/PowerShell/blob/99a49e0eab9b137449b690ab4607d7932c6f9956/src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs#L459-L482.

The SSH server mode `-sshs` only gets the handles to write to without setting the existing console handles to `Null` causing this problem https://github.com/PowerShell/PowerShell/blob/99a49e0eab9b137449b690ab4607d7932c6f9956/src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs#L526-L549.

## Steps to reproduce

```powershell
Enter-PSSession -HostName windows

[Console]::WriteLine('boom')
```

## Expected behavior

No output as the raw stdout console should not be attached to anything just like a WSMan remoting session.

This at least aligns with WSMan based sessions and I assume `pwsh -s` ones as there is no console attached for WSMan and `-s` sets the stdio streams in .NET to `TextWriter.Null`. In reality it would be nice if anything written to raw stdout would translate to `$host.UI.Write()` but that would be a future enhance IMO.

## Actual behavior

Errors with the following and the session is closed

> There is an error processing data from the background process. Error reported: boom.

![image](https://user-images.githubusercontent.com/8462645/114641795-16a9cc00-9d16-11eb-950e-dac952a43020.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
For reference. #15128 suggest to allocate a console in WinRM process.

**Comment by jborean93** [comment]
See https://github.com/PowerShell/PowerShell/issues/15128#issuecomment-819772400 these 2 issues are not related.

**Comment by PaulHigin** [comment]
Thanks for finding this!

**Comment by PaulHigin** [comment]
Remoting working group:  Fix has been merged.
