### ISSUE TITLE
Evaluate removal of pragma warning for SYSLIB0015

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15223]
Since 6.0.0-preview.3 `DisablePrivateReflectionAttribute` is removed. Please evaluate its removal from CoreAdapter.cs

Reference: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.disableprivatereflectionattribute?view=net-6.0

PR which disabled the warning: https://github.com/PowerShell/PowerShell/pull/15221

**Comment by iSazonov** [comment]
If I understand correctly whole `nternal static bool DisallowPrivateReflection(Type type)` method should be removed.

**Comment by daxian-dbw** [comment]
@adityapatwardhan Is it removed or just obsoleted?
