### ISSUE TITLE
Receive-Job discards remaining data if enumeration is cut short with Select-Object -First

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15234]
## Steps to reproduce

```powershell
# Create a background job that outputs the numbers from 1 to 10.
$jb = (1..10) &

# Wait for the job to finish.
$null = Wait-Job $jb 

# Receive the job's output, but stop after the first object.
Receive-Job $jb | Select-Object -First 1 | Should -Be 1

# I would now expect calling Receive-Job again to output the remaining objects:
Receive-Job $jb | Should -Be (2..10)
```

## Expected behavior

Both tests should succeed.

## Actual behavior

The second test fails, because the first `Receive-Job` unexpectedly discarded all remaining data after

```none
InvalidResult: Expected @(2, 3, 4, 5, 6, 7, 8, 9, 10), but got $null.
```

## Environment data

```none
PowerShell Core 7.2.0-preview.4
```

**Comment by anmenaga** [comment]
I can see how from one point of view the expected behavior described above would be logical.
However from another point of view (current behavior) also makes sense - [`The Receive-Job cmdlet gets the results that have been generated by the time that the Receive-Job command is submitted.`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/receive-job?view=powershell-7.1#description), so the first `Receive-Job $jb` is pulling all data and then Select-Object shows just the the first.

**Comment by mklement0** [comment]
The linked passage doesn't address what happens when the received data is only _partially consumed_.

With the current behavior, you get an all-or-nothing choice:

* Get _and consume_ ALL output objects currently collected in the job (by default)

* Get _and keep_ ALL objects currently collected, with `-Keep`

My original thought was that `Receive-Job` - without `-Keep` - should only consume those objects that are _actually enumerated (sent through the pipeline)_ - as opposed to removing the entire batch instantly from the job.

(Someone who then truly wanted the consume-it-all behavior could simply add the `-Wait` switch to the `Select-Object -First` call.)

That said, the current behavior is easier to reason about, and questions about how `Select -Last` or `Select -Index` would behave in the partial-consumption scenario do not arise.

---

Therefore, perhaps the better solution is to introduce a `-Count <int>` parameter to `Receive-Object` that allows retrieving a batch of a given size in a consuming manner.

What do you think?

This dovetails with a _time_-based mechanism of limiting what `Receive-Object` returns, as suggested in #5433.

**Comment by mklement0** [comment]
I'm closing this, but would like to continue the discussion, so that a feature request for a `-First` parameter or similar may result from it.
