### ISSUE TITLE
Add Write-Host ability to Prompt {}

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#15231]
## Summary of the new feature/enhancement

Add ability of `Write-Host` cmdlet to `Prompt` function. What is for? For example to support `/usr/bin/scp`. If default shell is pwsh it returns "echoed" output of prompt string that suppress scp. This could be like:

```
Prompt
{
    Write-Host "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) " -NoNewLine
}
```
As Write-Host supports esc-sequences it will be painless for end users who uses customized prompt.

Nowadays the Write-Host not working as expected. If to set it to prompt, prompt will be rewritten or extended with `PS>`

**Comment by powercode** [comment]
What does file copying have to do with the prompt? 
Can you elaborate on what you are trying to achieve, and exactly what it is that does not work?

**Comment by 237dmitry** [comment]
It's strange, just tried one more time and all is Ok. I don't know what it was.
