### ISSUE TITLE
[System.Text.Encoding]::Default give the wrong encoding

### ISSUE THREAD

**Issue by chucklu** [PowerShell/PowerShell#15230]
## Steps to reproduce

```powershell
[System.Text.Encoding]::Default

```

## Expected behavior

```none
BodyName          : gb2312
EncodingName      : Chinese Simplified (GB2312)
HeaderName        : gb2312
WebName           : gb2312
WindowsCodePage   : 936
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 936

```

## Actual behavior

```none
Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chucklu** [comment]
```C#
    Console.WriteLine(Encoding.Default.EncodingName);
            Console.WriteLine(Encoding.Default.CodePage);
```
I get the Chinese Simplified (GB2312), 936 from C# console application for test.

And the powershell(PSVersion  5.1.18362.1171 ) within win10 can provide the correct encoding for default
```powershell
[System.Text.Encoding]::Default
```
```none
BodyName          : gb2312
EncodingName      : Chinese Simplified (GB2312)
HeaderName        : gb2312
WebName           : gb2312
WindowsCodePage   : 936
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 936
```

**Comment by chucklu** [comment]
And the result of chcp command in command prompt is
```none
C:\WINDOWS\system32>chcp
Active code page: 936
```

**Comment by jborean93** [comment]
On .NET Core this is expected https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=net-5.0

> On .NET Core, the Default property always returns the UTF8Encoding. UTF-8 is supported on all the operating systems (Windows, Linux, and macOS) on which .NET Core applications run.

It will no longer use the active codepage like Windows PowerShell (.NET Framework) did.

**Comment by jborean93** [comment]
If you wish to get the same value as `[Text.Encoding]::Default` did in Windows PowerShell then you can use the following:

```powershell
Add-Type -Namespace Kernel32 -Name NativeMethods -MemberDefinition @'
[DllImport("Kernel32.dll")]
public static extern int GetACP();
'@

[Text.Encoding]::GetEncoding([Kernel32.NativeMethods]::GetACP())
```

What you use really depends on what you are using this encoding value for.

**Comment by chucklu** [comment]
@jborean93  Thanks for your information.

**Comment by chucklu** [comment]
@jborean93  By the way, I am investigating the ANSI problem.
https://stackoverflow.com/questions/16083916/the-encoding-that-notepad-just-calls-ansi-does-anyone-know-what-to-call-it
https://stackoverflow.com/questions/700187/unicode-utf-ascii-ansi-format-differences
ANSI: There's no one fixed ANSI encoding - there are lots of them. Usually when people say "ANSI" they mean "the default locale/codepage for my system" which is obtained via Encoding.Default, and is often Windows-1252 but can be other locales.

Do you know what's the ANSI supposed to be? As we can save file by the notepad(C:\Windows\notepad.exe) with an encoding. 
![image](https://user-images.githubusercontent.com/3004057/114659168-af941380-9d25-11eb-8324-2bcc128491a4.png)

**Comment by chucklu** [comment]
I also find something here https://en.wikipedia.org/wiki/Windows-1252
The term ANSI as used to signify Windows code pages is a historical reference, but is nowadays a misnomer that continues to persist in the Windows community.

**Comment by jborean93** [comment]
As far as I know "ANSI" in notepad refers to the system codepage which as you said `[Text.Encoding]::Default` used to refer to. It's a bit of a loaded term unfortunately but that ship sailed years ago.

See my other comment https://github.com/PowerShell/PowerShell/issues/15230#issuecomment-819202122 on how to get that value in a way that would work with both Windows PowerShell and PowerShell.

Ultimately if you are saving files it is recommended to use UTF-8, potentially UTF-8 with BOM if you need compatibility with some older hosts. UTF-8 is more universal and well known on modern systems so it's really the way forward. It's also the same on any host, i.e. utf-8 on 1 host is the same on the other, compared to ANSI where it can refer to different encoding schemes.

**Comment by chucklu** [comment]
@jborean93  Thanks, that's what I want. I prefer to save file with encoding utf-8 with BOM. As the csv file without BOM can not be recognized by Excel correctly.
https://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically

**Comment by chucklu** [comment]
@jborean93  Still a little confused by https://stackoverflow.com/a/2223926/13338936
According to the Unicode standard, the BOM for UTF-8 files is not recommended:

And in comments :(This is the problem I met)

> Also note that Windows seem to default to using a BOM for UTF-8, and a lot of Microsoft programs to not attempt heuristic detection, so if the BOM is missing it won't decode the file properly.

**Comment by jborean93** [comment]
Yea it’s not recommended because a lot of tools on Linux don’t support the BOM for UTF-8. It’s really a mixed bag and you can probably safely use just utf-8 without a BOM but it’s highly dependent on your environment and what is consuming the files.
