### ISSUE TITLE
Question: Assembly Probing? (SDK assemblies)

### ISSUE THREAD

**Issue by Ergamon** [PowerShell/PowerShell#15232]
## Summary 

I want use a net5.0 assembly as module.

How can I tell PowerShell to use the deps.json file?

## details

We have developed a very small AspNetCore application in .NET 5.0.

To make some administration tasks easier I added a few Cmdlets to this assembly, which can be used in PowerShell by Import-Module.

Everything works fine until a Cmdlet uses functionality provided in an SDK assembly, e.g. Microsoft.Extensions.Configuration.Abstractions. PowerShell throws an excpetion of not finding this assembly.

If I manually copy these files in the folder, everything works. (Another solution is to publish as Framework independent)

The AspNetCore application has no problems finding everything needed due to the deps.json file.

So my question is how to I tell PowerShell where to look for these references? Or probably the best solution, how to use the same mechanism the .NET Core application uses.

**Comment by MatejKafka** [comment]
Still relevant; I'd love to see support for `.deps.json` files. Not that useful for released modules, but during development, if the module uses a library from Nuget, the loading currently fails.

**Comment by MatejKafka** [comment]
@kilasuit ^ Please reopen.
