### ISSUE TITLE
Request for guidance: guarding pervasive experimental features + tests

### ISSUE THREAD

**Issue by IISResetMe** [PowerShell/PowerShell#15246]
## Problem description

I've been working on a re-write of the [interface keyword feature](https://github.com/PowerShell/PowerShell-RFC/pull/152) for PS7/.NET5+, and have been [instructed to open a PR introducing it as an experimental feature](https://github.com/PowerShell/PowerShell-RFC/pull/152#issuecomment-794425131) to allow community members to test the proposed implementation.

Adding a new Experimental Feature entry was straightforward, and guarding the parsing routine is easy: https://github.com/IISResetMe/PowerShell/blob/fb98b8fb4b01c54c1fc9f5fa6275cb0bf8d52e4b/src/System.Management.Automation/engine/parser/Parser.cs#L2092-L2095

... but it touches _many_ different parts of the language engine (parser, AST, compiler, PSType etc.), and I'm struggling to figure out how to guard some of these changes:

 - ~~How do I require the feature enabled for related pester tests?~~ (solved with `$PSDefaultParameterValues.Add('It:Skip', (-not $EnabledExperimentalFeatures.Contains('FeatureName')))`)
 - How do I ensure the tests that require the feature enabled are _actually tested_ in build pipelines and elsewhere?
 - How should I handle changes [introduced in `ast.cs`](https://github.com/IISResetMe/PowerShell/commit/fb98b8fb4b01c54c1fc9f5fa6275cb0bf8d52e4b#diff-321bb81b7c5696aca6910d014c4e3165cf030ce7c27ebe037c5b3e8e7b651821)?
 

Please advice

**Comment by powercode** [comment]
I'm not sure all things can be guarded like this. You would need to make massive changes to have a facade, and two different underlying implementations, where the old implementation would be one of them. This would require a dependency-injection-like rewrite of core parts of the engine, which does not seem reasonable.

Tricky, for sure!

**Comment by IISResetMe** [comment]
That's more or less what I've done with PSType (sans a well-defined facade, entrypoint is just a single method call). 

The additions to the ast's might be okay without guardrails (I'm not removing anything), but I'm still a bit perplexed as to how to tag and handle the test suite?

**Comment by IISResetMe** [comment]
@vexx32 kindly suggested scouring existing test fixtures for experimental feature names, and I can see this being used in some:

    $PSDefaultParameterValues.Add('It:Skip', (-not $EnabledExperimentalFeatures.Contains('PSAnsiRendering')))

That answers my first question :)

**Comment by vexx32** [comment]
That code pattern might actually break depending on scoping... If there happens to already be an `It:Skip` entry in that table, it'll fail, I think?

Might be safer to do it like this:
```powershell
$PSDefaultParameterValues['It:Skip'] = -not $EnabledExperimentalFeatures.Contains($FeatureName)
```
