### ISSUE TITLE
Bug in error output caused by closing ScriptAnalysis progress pane

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#1524]
AppVeyor builds fail due to reporting the progress of script analysis, specifically [this piece of code](https://github.com/PowerShell/PowerShell/commit/b400ba368811ac0221632457669dff5203940616#diff-8db7ab7b17a956849fe85734af72f5bbR1327). Removing the `CORECLR` guard results in this error:

> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot process the XML from the 'Error' stream of 'C:\projects\powershell\src\powershell-windows\bin\Debug\netcoreapp1.0\win81-x64\publish\powershell.exe': Data at the root level is invalid. Line 1, position 382.

As can be seen in [this build](https://ci.appveyor.com/project/PowerShell/powershell/build/0.6.0.3806).

@lzybkr notes that disabling the code is not enough:

> By not calling WriteProgress with a Completed message, we'll leave screen artifacts. See the corresponding call in SriptAnalysis.cs, line 43 - that code is not guarded at all by #if !CORECLR
> 
> I don't have a strong preference on this specific progress message, but if progress messages are causing problems in CI, turning them off this way is not the right fix.

**Comment by joeyaiello** [comment]
This looks like progress issues that we fixed. @andschwa or @JamesWTruher, feel free to reopen if this still relevant.
