### ISSUE TITLE
On Windows, Remove-Item unexpectedly fails if the target directory path happens to end in a backslash

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15248]
## Steps to reproduce

```powershell
# Switch to a temporary directory.
Push-Location -ea Stop ($tmpDir = (New-Item -Type Directory -Force (Join-Path Temp:/ $PID)).FullName)

try {

  # Create two directories with one file each in them.
  $null = New-Item -Type Directory -force foo1, foo2
  $null = New-Item -force foo1\t.txt, foo2\t.txt

  # Remove the first one with WITHOUT a trailing "\"
  { Remove-Item .\foo1 -Recurse -ErrorAction Stop } | Should -Not -Throw

  # Remove the second one with WITH a trailing "\"
  # This is also what you'd get with tab-completion.
  { Remove-Item .\foo2\ -Recurse -ErrorAction Stop } | Should -Not -Throw

} finally {
  # Clean up.
  Pop-Location; Remove-Item $tmpDir -Recurse
}
```

## Expected behavior

Both tests should succeed: whether the target directory is specified with a trailing path separator or not should not make a difference.

## Actual behavior

On Windows, removal fails when the target path ends in `\`:

```none
Cannot remove item C:\Users\jdoe\AppData\Local\Temp\8656\foo2\: The directory is not empty.
```

Note:
* The problem only occurs if the target dir. is _non-empty_.
* It seems to have been introduced in v7.2.0-preview.5

## Environment data

```none
PowerShell Core v7.2.0-preview.5 on Microsoft Windows 10 Pro (64-bit; Version 20H2, OS Build: 19042.928)
```

**Comment by iSazonov** [comment]
> Remove-Item .\foo\

I'd expect follow should works - `Remove-Item .\foo\ -Recursive`.

**Comment by mklement0** [comment]
Sorry, @iSazonov: `-Recurse` is indeed required, I just mistakenly omitted it from the test, which I've no updated. As you'll see, the test still fails.

**Comment by iSazonov** [comment]
I manually create the tree in `c:\tmp` and Remove-Item works as expected without an error.

**Comment by mklement0** [comment]
Interesting - what happens when you run my test?
For me, `Remove-Item .\foo -Recurse` works just fine, whereas `Remove-Item .\foo\ -Recurse`  - note the trailing backlash - fails - actually also if the directory is empty and `-Recurse` is omitted.

**Comment by iSazonov** [comment]
No error too.

**Comment by iSazonov** [comment]
Maybe you already have a locked file in C:\Users\jdoe\AppData\Local\Temp\8656\foo\ ?

**Comment by mklement0** [comment]
Are you using preview **5** yet? It only seems to happen there.

I've refined the test in the initial post, and the problem is connected to _non-empty_ directories (which therefore requires `-Recurse`), after all.

If locking were the problem, the test code wouldn't be able to remove the enclosing temp. directory - but it is.

**Comment by iSazonov** [comment]
I wonder how our CI tests are passed.

**Comment by mklement0** [comment]
So you're now seeing the problem too?

> I wonder how our CI tests are passed.

Without having looked at them: Perhaps the particular combination at hand - non-empty target dir., trailing `\`, `-Recurse` -isn't being tested.

**Comment by mklement0** [comment]
If you're seeing the problem too, I suggest we hide all of our comments here, as the initial post has been updated to (hopefully) tell the full story.

**Comment by iSazonov** [comment]
It is a regression after #14902 (again symlinks 😄).

**Comment by mklement0** [comment]
Thanks for digging. 
I've hidden most of my previous comments.
