### ISSUE TITLE
Update tag on master to 7.2.0-preview.4

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#15244]
Could you update the tags on master again? The *v7.2.0-preview.5* is going to be released soon but the tag on *master* is still set to *v7.2.0-preview.3* which causes my daily builds to end with following string:

![image](https://user-images.githubusercontent.com/16168755/114988818-0bca7500-9e97-11eb-8662-d0b6f2f2f993.png)

It's follow up to #14439

**Comment by iSazonov** [comment]
I don't know what was wrong in v7.2.0-preview.3 release but I caught the same and @rjmholt suggested me `git fetch -tags -all` - this helped.

**Comment by kborowinski** [comment]
> I don't know what was wrong in v7.2.0-preview.4 release but I caught the same and @rjmholt suggested me git fetch -tags -all - this helped.

It does not work for me:
![image](https://user-images.githubusercontent.com/16168755/115017915-82776a80-9eb7-11eb-861c-dfc81eef9e59.png)

This is strange since the `git tag -n` shows that they are present:
![image](https://user-images.githubusercontent.com/16168755/115017646-1f85d380-9eb7-11eb-9c76-79da1d27edfd.png)

> But today I rebased to latest and last tag is v7.2.0-preview.4 - not v7.2.0-preview.5.

I guess it's because the *preview.5* is not released yet. I was just referencing it because I saw new commits that are preparing for the *preview.5* release and the last tag is set to *preview.3*.

**Comment by iSazonov** [comment]
` git describe` shows `v7.2.0-preview.3-99-g658837323` for me too.

**Comment by adityapatwardhan** [comment]
Having a look.
/cc @TravisEz13

**Comment by adityapatwardhan** [comment]
I am not seeing them after git fetch either, but seem on the github.com. Trying to root cause.

![image](https://user-images.githubusercontent.com/12820925/115034135-2a317000-9e99-11eb-97bc-0bc0d1544757.png)

**Comment by adityapatwardhan** [comment]
Fixed for preview.5 now. Please pull again and try. Thanks for reporting. We are going to give up fixing preview 4 though as a more recent tag is pushed now.

**Comment by TravisEz13** [comment]
I merged the tag into master.  This step is our instructions for finalizing the release.  I'll emphasize the importance of it to the other maintainers.  Otherwise, you must sync tags.  `Build.psm1` has `Sync-PSTags` to resolve this issue (although it requires a remote to powershell/powershell over https).

**Comment by iSazonov** [comment]
Thanks! I see new tag.

**Comment by kborowinski** [comment]
Yep, it works. Thanks gents!
