### ISSUE TITLE
Improve discoverability of delay-bind scriptblock parameters

### ISSUE THREAD

**Issue by zett42** [PowerShell/PowerShell#15241]
### Existing feature ###

There is a really useful implicit PowerShell feature that many cmdlets that accept pipeline input, already benefit from:
~~~powershell
# Delay-bind script-block argument:
# The code inside { ... } is executed for each input object ($_) and
# the output is passed to the -NewName parameter.
... | Rename-Item -NewName { $_.Name -replace '\.txt$','.log' }
~~~
<sup>Code sample blatantly stolen from [this StackOverflow post](https://stackoverflow.com/a/52807680/7571258), which also gives a good in-depth analysis on how this feature works.</sup>

As in this example, this feature often removes the neccessity of a `ForEach-Object` construct, letting users write more concise code. This is all good, but...

### Problem ###

Code like above is often showcased in PowerShell "recipes" provided on StackOverflow and tutorial websites, but rarely explained. Users have a hard time to look up documentation for this feature. They would expect to find documentation in the context of the cmdlet that is used by a code sample, but if we look up [`Rename-Item` parameter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-7.1#parameters) `-NewName` for instance, there is nothing that hints at its ability to accept a `ScriptBlock` argument. Its type is just listed as `String`. Neither in the examples section is anything to be found that showcases this useful feature.

The only official documentation I know of is "hidden" in the [about_Script_Blocks](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks?view=powershell-7.1#using-delay-bind-script-blocks-with-parameters) page. It took me a while to find and I don't expect many PowerShell beginners to stumble upon it.

### Suggested Solution ###

Update the documentation of all applicable cmdlets, to hint at the possibility to pass delay-bind scriptblock arguments. 

This seems like a big effort but it could possibly be automated. When generating the documentation for each parameter, check the [condition that enables a parameter to accept a delay-bind scriptblock argument](https://stackoverflow.com/a/52807680/7571258). If true, add a line to the details table of the parameter, e. g.

`-NewName`

Type: String
Position: 1
Default value: None
Accept pipeline input: True
Accept [delay-bind scriptblock argument](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks?view=powershell-7.1#using-delay-bind-script-blocks-with-parameters): True
Accept wildcard characters: False

This would make it easy for users to discover and look up this useful feature in the context where it actually can be used instead of having to learn about it "by accident" and keep the exact rules in mind afterwards.

Adding usage examples to some of the most commonly used cmdlets would also help discoverability. In my opinion it is not necessary to add such examples to all applicable cmdlets, because once learned, users will be able to transfer their knowledge to other cmdlets as well, provided they can easily recognize applicable parameters (which an update of the auto-documentation as suggested above would do).

**Comment by jborean93** [comment]
> but if we look up Rename-Item parameter -NewName for instance, there is nothing that hints at its ability to accept a ScriptBlock argument

This just goes to prove your point about it being rarely explained and misunderstood but I assumed that this could only be done on parameters that accepted pipeline input which the docs do state `Accept pipeline input: True`.

**Comment by zett42** [comment]
> I assumed that this could only be done on parameters that accepted pipeline input which the docs do state Accept pipeline input: True.

Yes, but there are some exceptions as explained by the linked [StackOverflow post](https://stackoverflow.com/a/52807680/7571258), which is why I think a separate row in the details table of the documentation of each applicable parameter would be necessary, apart from making the feature more explicit:

>_only_ works with parameters that are _designed to take pipeline input_,
>
>- of any type _except_ the following, in which case _regular_ parameter binding happens[1]:
>   - `[scriptblock]`
>   - `[object]` (`[psobject]`, however, does work, and therefore `[pscustomobject]` too)
>   - (no type specified), which is effectively the same as `[object]`

**Comment by SeeminglyScience** [comment]
It's pretty hard to think of other commands where this syntax is *possible* and much harder still to think of a scenario where it would have real world application.

Maybe the some of the other `Rename-*` commands, but how even they are sort of a stretch (and very few of them are included with PowerShell).  I agree it should be presented where it makes sense but... that might already be done.  Can anyone else think of a different built in command where they've actually used this syntax?

**Comment by jborean93** [comment]
Thanks for the line @zett42 that definitely help. This is my personal opinion but I always found this syntax too magical for me. I don't think I've ever written something like this and always just did something like `| ForEach-Object { $_ | My-Cmdlet -Param $_.Param }`. IMO that more aligns with how most people expect pipelines to work and there's less "huh I've never seen that before, does it even work".

**Comment by rkeithhill** [comment]
I think it would be adequate to just ensure there is an example that shows this kind of usage where it would actually be useful.  `Rename-Item` is one of those command where this is useful and yes, I've used this capability over the past decade and a half.  BTW `Rename-Item` does have an example that shows this:

```poweshell
    --------------- Example 4: Rename multiple files ---------------

    Get-ChildItem *.txt

    Directory: C:\temp\files

    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    -a----        10/3/2019   7:47 AM           2918 Friday.TXT
    -a----        10/3/2019   7:46 AM           2918 Monday.Txt
    -a----        10/3/2019   7:47 AM           2918 Wednesday.txt

    Get-ChildItem *.txt | Rename-Item -NewName { $_.Name -replace '.txt','.log' }
```

**Comment by vexx32** [comment]
TBH I think there's also room to cover this as part of the Advanced Functions and/or Pipelines topics in the help, as part of how `ValueFromPipelineByPropertyName` functions, and that'd probably be the most easily accessible/discoverable place to put it, at least from what I can see.

**Comment by SeeminglyScience** [comment]
Can anyone think of an instance aside from `Rename-Item` that they've used this?

**Comment by vexx32** [comment]
I don't have specific examples, but I do use it from time to time, though granted probably not a large amount of that is in core cmdlets; I've found it pretty versatile and useful when building custom functions and working with functions others have put together. 

It could use more utilisation in core cmdlets IMO, but currently lacks it. ForEach-Object is a nice catch-all, but IMO would be cool if more core cmdlets supported this kinda thing natively where it makes sense.

**Comment by SeeminglyScience** [comment]
Here's an example from @IISResetMe on discord:

```powershell
mkdir $dirName |cd -Path {$_.FullName}
```

Which tells me I had a pretty big misunderstanding of the limitations, and it's applicable in a lot more places than I thought.

**Comment by IISResetMe** [comment]
> @zett42: Update the documentation of all applicable cmdlets, to hint at the possibility to pass delay-bind scriptblock arguments.

While I agree we can do a better job of educating users in general, I don't think that the proposed solution is feasible (nor helpful) - as it applies to ~60% of all cmdlets in the built-in modules:

```
$applicable,$other = (Get-Command -Module Microsoft.PowerShell.*).Where({
  $params = $_.Parameters
  $params.Keys.Where({$params[$_].Attributes.Where({$_ -is [Parameter]}).ValueFromPipelineByPropertyName})
}, 'Split')

Write-Host "Delay-script binding possible for $((100 * $applicable.Count / @($applicable;$other).Count)-as[int])% of built-in commands ($($applicable.Count)/$(@($applicable;$other).Count))"
```
(Gives me 58% (162/279) in 7.1.3 on Win10 2004)
 
 As hinted in the original answer you linked it also applies to any custom function with a parameter meeting the requirements:
 
 ```
function Greet-People {
  param(
    [Parameter(ValueFromPipelineByPropertyName)]
    [string]$Name
  )

  process {
    Write-Host "Hello, $Name"
  }
} 
 
$people = @'
Username,FirstName,LastName
sscience,Seemingly,Science
irme,IISReset,Me
'@ |ConvertFrom-Csv

$data |Greet-People -Name {$_.FirstName,$_.LastName-join''}
```

Result:

```
Hello, SeeminglyScience
Hello, IISResetMe
```

The way I see it, PowerShell's feature set is an iceberg the tip of which most users barely scrape - and while I wish more people would "dive beneath the surface" (and I feel that we can and should do our part as "super practitioners" to educate other users), I don't think it's helpful to try and push every facet of the language in the face of learners at every level - not because it's "too advanced", but because 90% of users will never actually _need_ them beyond a few edge cases (like `Rename-Item`).

**Comment by nashiooka** [comment]
I participated in the [SO question](https://stackoverflow.com/a/67092308/4749264) that lead @zett42 to post the issue. If my opinion means anything. I do agree it's extremely useful, but mostly limited to the *-Item cmdlets. Though I've used with both `Group-Object` & `Sort-Object` often enough, especially in interactive use to quickly get a result without having to formally add a property.  Although those are indeed documented under the about_Calculated_Properties the syntax is quite similar:

`Get-ChildItem c:\temp | Group-Object -Property { $_.Extension }`

I like @rkeithhill approach to focus on examples where reasonably applicable.  I also like @vexx32 idea of additional coverage in advanced function documentation.  There is would be nice to know.  Not to sound cliché but in "tool making" we're taught to think about usage scenarios which leads to thought about what and how you can input to the function.

**Comment by IISResetMe** [comment]
@nashiooka FWIW those are _not_ delay-bind scriptblocks - the `-Property` parameter of both `Group-Object` and `Select-Object` are constrained to `[object[]]`, for which pipeline binding doesn't work - these cmdlets instead work by accepting *property expressions* which look like and have similar semantics to pipeline-bound blocks, but they're resolved by the cmdlets themselves, not the parameter binder

**Comment by nashiooka** [comment]
@IISResetMe thanks, I knew there was some difference, but this clarifies it for me.
