### ISSUE TITLE
Write-Progress -Completed requires an -Activity argument, even though it is pointless

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15252]
To hide a progress bar explicitly, you call `Write-Progress -Completed`

Doing so currently requires that an `-Activity` argument be passed as well, even though that shouldn't be necessary, given that such an argument is only relevant for _displaying_ the progress bar, not when _hiding_ it.

Therefore, `Write-Progress -Completed` by itself should be sufficient to hide a progress bar (potentially combined with `-Id` to disambiguate, should multiple ones have been created).

## Steps to reproduce

```powershell
foreach ($i in 1..10) { Write-Progress $i -Activity foo; start-sleep -ms 100 }
Write-Progress -Completed
'Done'
```

## Expected behavior

The progress bar should display, then disappear, followed by output `'Done'`.

## Actual behavior

`Write-Progress -Completed` unexpectedly prompts for an `-Activity` parameter value.

## Environment data

```none
PowerShell Core 7.2.0-preview.5
```

**Comment by vexx32** [comment]
Somewhat relevant is that (at least to my memory) you have to pass a ProgressRecord with the `IsCompleted` property set to `true` when using the internal `Cmdlet.WriteProgress()` api, and you can't currently instantiate a ProgressRecord with a null or empty string as the Activity value.

I may be misremembering, but that's probably where this comes from -- and it should be fixed in some way that makes it much easier to use for both PowerShell and in C# cmdlets.

**Comment by mklement0** [comment]
Thanks, @vexx32. Sounds like a simple fix would be to simply pass a dummy value behind the scenes.

**Comment by SteveL-MSFT** [comment]
It seems that `Completed` should be a separate parameterset from `Activity` (which is mandatory).  And I think this should just work as `Activity` should just be an empty string if not defined and `Id` will default to 0.

**Comment by vexx32** [comment]
```powershell
PS> [System.Management.Automation.ProgressRecord]::new(0, '', '')
Exception calling ".ctor" with "3" argument(s): "Cannot process the argument because the value of activity cannot be
null or empty."
At line:1 char:1
+ [System.Management.Automation.ProgressRecord]::new(0, '', '')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PSArgumentException
```

This will require additional changes to the ProgressRecord API to allow the cmdlet to construct a ProgressRecord in this way.

Also, if I'm not mistaken, `Completed` and `Id` will still need to share a set, otherwise it will become impossible to mark other progress messages as completed if they have been given a custom ID.

**Comment by iSazonov** [comment]
Activity is an unique identifier. How this can be changed if there can be many progress bars at the same time.

**Comment by mklement0** [comment]
It is the `-Id` parameter that provides the unique identifier; `-Activity` is just display text.

Though, come to think of it: it's unclear how `-SourceId` relates to `-Id`; the [help topic](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress) doesn't make that clear:

> You can use this in place of Id but cannot be used with other parameters like ParentId.

**Comment by iSazonov** [comment]
> It is the `-Id` parameter that provides the unique identifier; `-Activity` is just display text.

No 😄 These names are deceiving. Please see the cmdlet sources. Only `-Activity` is mandatory. `-Id` is for subordinate activities.

**Comment by mklement0** [comment]
😁 Well, you know how much I love looking at the source code.
Let's try it my way for a second (on Windows):

With different `-Activity` arguments and with an _implied_ `-Id`:

```powershell
Write-Progress -Activity 'Bar 1'; Start-Sleep 1
Write-Progress -Activity 'Bar Harbor' -Completed
choice  # The bar is gone, implying that the -Completed call successfully hid it - the differing -Activity values did not matter
```

With different `-Id` arguments but identical `-Activity` arguments:

```powershell
Write-Progress -Id 1 -Activity 'Bar 1'; Start-Sleep 1
Write-Progress -Id 2 -Activity 'Bar 1' -Completed
choice  # The bar is still there, because the -Completed call didn't hide the original bar, due to using a different ID.
```

Let's mix and match: different `-Activity` values, but same `-Id` value:

```powershell
Write-Progress -Id 1 -Activity 'Bar 1'; Start-Sleep 1
Write-Progress -Id 1 -Activity 'Bar Harbor' -Completed
choice  # The bar is gone, implying that the -Completed call successfully hid it, due to targeting the same -ID
```

**Comment by vexx32** [comment]
Yep. `Id` is the identifier for the progress bar. The only reason it's not mandatory is because the cmdlet explicitly chose to default it to zero. All that means is that using `Write-Progress` without specifying an ID will simply overrule other usages of Write-Progress that also don't specify the ID.

Activity is mandatory because you can't construct an instance of ProgressRecord without it, and there isn't much of a sensible default you can provide.

**Comment by mklement0** [comment]
Good points, @vexx32.

To summarize:

* In terms of the user-facing cmdlet syntax, `-Completed`, with `-Id` optional (and possibly `-SourceId`?) must become a new parameter set that permits no other parameters - except _optionally_ `-Activity` _for backward compatibility only_.

* With respect to the underlying API, (`System.Management.Automation.ProgressRecord`)[https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.ProgressRecord]:
  * A quick and dirty fix would be to let the `Write-Progress` implementation pass non-empty _dummy values_ to the current constructor, in case `-Completed` was specified.
  * Preferably, we should extend this API to allow constructing a record of type [`Completed `](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.progressrecordtype) without needing to specify additional, unnecessary values, along the lines of a static `CompletedProcessRecord` property on the class.

**Comment by iSazonov** [comment]
It's strange that we haven't discussed _Clear-Progress_. This is most in the spirit of PowerShell and solves the root of the problem.
