### ISSUE TITLE
Experimental feature PSNativeCommandArgumentPassing doesn't support arguments with embedded double quotes when calling batch files

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15250]
Similar to #15239, this issue would be resolved by the proposal in #15143. See also: #15261 and #15276

Note that high-profile CLIs such as `az` and `npm` (Node.js's package manager), for script-based utilities that come with packages, use batch files as their entry points.

## Steps to reproduce

Run the following on Windows:

```powershell
# Switch to a temporary directory.
Push-Location -ea Stop ($tmpDir = (New-Item -Type Directory -Force (Join-Path Temp:/ $PID)).FullName)

# Create a batch file that strips enclosing double quotes from the first argument and deduplicates the 
# embedded ones.
@'
@echo off & setlocal
set Arg1=%~1
echo [%Arg1:""="%] [%2]
'@ > foo.cmd

./foo.cmd 'Andre "The Hawk" Dawson' | Should -Be '[Andre "The Hawk" Dawson] []'

# Clean up.
Pop-Location; Remove-Item $tmpDir -Recurse
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because the argument with embedded `"` isn't passed batch-file-appropriately - batch files (`cmd.exe`) do not recognize `\"` as an escaped `"` and require `""` instead:

```none
InvalidResult: Expected strings to be the same, but they were different. 
Expected length: 28 Actual length:   30 Strings differ at index 7. 
Expected: '[Andre "The Hawk" Dawson] []' 
But was:  '[Andre \"The] [Hawk\" Dawson"]'
```

Note the literally retained `\` and the unexpected breakup into _two_ arguments.

For this invocation to succeed it would have to pass verbatim `Andre "The Hawk" Dawson` as `"Andre ""The Hawk"" Dawson"` - i.e. escaping the embedded `"` as `""` rather than `\"` - on the command line used behind the scenes.

## Environment data

```none
PowerShell Core 7.2.0-preview.5 on Windows
```

**Comment by SteveL-MSFT** [comment]
The proposed fix would be to special case `cmd.exe` and files ending with `.bat` or `.cmd` to pass enclosed double quotes as `""`?

**Comment by mklement0** [comment]
Indeed, @SteveL-MSFT.

It is part of what I've been proposing for months, repeatedly, in conversations you were a part of: [here](https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-738073284) and [here](https://github.com/PowerShell/PowerShell/pull/14692#issuecomment-772816850) and [here](https://github.com/PowerShell/PowerShell/issues/14747#issuecomment-782892238), which finally evolved into a - hopefully comprehensive and final - proposal in **#15143**, which **summarizes _all_ accommodations that I think are vital to make on Windows, the need to escape `"` as `""` for batch files being just _one_ of them**.

**Excuse me for shouting, but it's out of desperation over these issues seemingly never being paid proper attention to**; this isn't a _personal_ concern; rather, I think **these issues are of vital importance, and we should finally get them right**.

**Therefore, I ask you to please take the time to fully understand and discuss**:
*  the **proposed accommodations**, presented in detail in #15143, and **exemplified for convenience below**.
* **required fixes**, summarized from their separates issues below.

---

### `PSNativeCommandArgumentPassing`: WHAT IS MISSING, WHAT NEEDS FIXING:

Setup:

```powershell
Install-Module Native
```

**Note**:

* The diagnostic output below, via argument-/command-line diagnosing function `dbea` (which uses `-ie` to use the `ie` function behind the scenes, which ensures the desired behavior); these functions are from the [`Native`](https://github.com/mklement0/Native) module. _It is my hope that the need for `ie` will go away_ with proper implementation of `PSNativeCommandArgumentPassing` (though it will still be useful in _older_ PS versions).

  * First shows the _verbatim_ arguments that the target batch file / conventional executable _ends up seeing after parsing its own command line_, i.e. the _effective_ values.
  
  * **Then shows the _raw command line_ (sans executable) that was passed** (which by definition only applies _on Windows_): **this is what PowerShell must construct from the given arguments and assign to [`System.Diagnostics.ProcessStartInfo.Arguments`](https://docs.microsoft.com/en-US/dotnet/api/System.Diagnostics.ProcessStartInfo.Arguments).**

---

**Accommodation A:** Calling a batch file: Must escape embedded `"` as `""`:

```powershell
PS> dbea -ie -UseBatchFile -- 'Andre "The Hawk" Dawson' 'another argument'
2 argument(s) received (enclosed in «...» for delineation):

  «"Andre ""The Hawk"" Dawson"»
  «"another argument"»

Command line (without executable; the value of %*):

  "Andre ""The Hawk"" Dawson" "another argument"
```

Note how the verbatim embedded `"The Hawk"` was escaped as `""The Hawk""`, to ensure that the batch file properly recognized the entire token as a _single argument_.

---

**Accommodation B:** Calling a batch file: _Space-less_ arguments (ones that normally do _not_ trigger enclosure in `"..."`) must still be double-quoted if any of the following `cmd.exe` metacharacters is present: `& | < > ^ , ;`

```powershell
PS> dbea -ie -UseBatchFile -- 'http://example.org?foo=1&bar=2' 'another argument'
2 argument(s) received (enclosed in «...» for delineation):

  «"http://example.org?foo=1&bar=2"»
  «"another argument"»

Command line (without executable; the value of %*):

  "http://example.org?foo=1&bar=2" "another argument"

```

Note how the URL was double-quoted, despite not containing spaces.
Currently, this fails,  both with and without `PSNativeCommandArgumentPassing` in effect, because in the absence of double-quoting `cmd.exe` (which parses the batch file's command line) interprets the unquoted `&` as a _statement separator_.

---

**Accommodation C:** Passing a `PROPERTY=VALUE`-style argument (and variations thereof, prefixed with `/` or `-` optionally combined with `:` instead of `=`)  to _any_ executable: Must _selectively_ `"..."`-enclose _only the `VALUE` part_, if it contains spaces so as to satisfy the particular, nonstandard quoting requirements of executables such as `msiexec` (to _conventional_ executables, this quoting variation makes no difference, so it is safe to use):

```powershell
PS> dbea -ie -- INSTALLDIR=$PSHOME  'another argument'
2 argument(s) received (enclosed in «...» for delineation):

  «INSTALLDIR=C:\Program Files\PowerShell\7»
  «another argument»

Command line (without executable):

  INSTALLDIR="C:\Program Files\PowerShell\7" "another argument"
```

Note how `INSTALLDIR=$PSHOME` turned into _selectively double-quoted_ `INSTALLDIR="C:\Program Files\PowerShell\7"`

**Note**: 
 * Accommodation B and C must situationally be _combined_.
 * Accommodation B, due to the need for Accommodation C, must actually be performed in the context of a `cmd /c "<batch-file> ... & exit"` call -  see below.

---

**Accommodation D:** Support _reliable_ exit-code reporting from batch files:

```powershell
PS> '@echo off & whoami -nosuch 2>NUL || exit /b' | Set-Content test.cmd; ie ./test.cmd; $LASTEXITCODE
1
```

Without `ie`, this currently reports `0` (both with and without `PSNativeCommandArgumentPassing` in effect), i.e. `whoami`'s failure exit code was _not_ reported.

For this to work as intended, PowerShell must translate `./test.cmd ...` into `cmd /c "c:\path\to\test.cmd ... & exit`, as explained in detail [here](https://github.com/PowerShell/PowerShell/issues/15143#issuecomment-816105557). Due to `cmd.exe` _not_ expecting escaping inside the overall `"..."` string, the encoding of the arguments is the same as would be needed for Accommodation B in isolation.

---

**Accommodation E:** Transform multi-argument direct `cmd /c` / `cmd /k` executable calls into single-argument, overall `"..."`-enclosed ones behind the scenes.

This accommodation is arguably the least important, but I think it would be beneficial, because it's one less thing for users to worry about; plus, the important Accommodation D would give us the implementation for free:

```powershell
PS> ie cmd /c "C:\Program Files\PowerShell\7\pwsh" -noprofile -c " 'hi there' "
hi there
```

Without `ie`, this command _breaks_, both with and without `PSNativeCommandArgumentPassing` in effect, due to `cmd.exe`'s _own_ limitations.

If PowerShell transformed the above command line into the following, verbatim _single_-argument `cmd /c` form in `.Arguments` (which is what `ie` does), the command would work:

```
" "C:\Program Files\PowerShell\7\pwsh" -noprofile -c " 'hi there' " "
```

To simulate this with `--%`:

```powershell
PS> & { $PSNativeCommandArgumentPassing='Legacy'
      cmd --% /c " "C:\Program Files\PowerShell\7\pwsh" -noprofile -c " 'hi there' " "
    }
```

For details, see https://github.com/PowerShell/PowerShell/issues/14747#issuecomment-800376364

---

**Fix 1**: Calling `cmd.exe /c` / `cmd.exe /k` _directly_ with a command line (as a single argument) must continue to work properly, as it (by lucky accident) always has, even with `PSNativeCommandArgumentPassing` in effect:

```powershell
# Legacy behavior is actually *ok* in this case:
PS> & { $PSNativeCommandArgumentPassing='Legacy'; cmd /c ' echo "Andre ""The Hawk"" Dawson" ' }
"Andre ""The Hawk"" Dawson" 
```

With `PSNativeCommandArgumentPassing` in effect (`$PSNativeCommandArgumentPassing='Standard'`), you'll now get (broken)
`\"Andre \"\"The Hawk\"\" Dawson\" `. 

Such `cmd /c` calls have historically been valuable for workaround quoting headaches in PowerShell. 
They will continue to be useful:
 * For - hopefully very rare - quoting edge cases that the accommodations do not cover, as a _superior alternative to `--%`_, given that embedding PowerShell variable values and expressions is then easily possible via string interpolation.
 * Probably more frequently, to work around the PowerShell limitation of not providing _raw byte handling_ in the pipeline, and therefore needing to resort to `cmd.exe`'s `|`.

See #15239.

---

**Fix 2**: `--%` must continue to work even with `PSNativeCommandArgumentPassing` in effect:

`--%` is a per-call syntax override, and its functioning should not be affected by whether or not `PSNativeCommandArgumentPassing` in effect. While `--%` is virtually useless on Unix, on Windows there will still be - hopefully very rare - edge cases that require it, and there's also no need to break existing calls using it.

```powershell
# --% use: OK only in legacy mode:
PS> & { $PSNativeCommandArgumentPassing='Legacy'
             cmd /c --% echo "Andre ""The Hawk"" Dawson"
    }
"Andre ""The Hawk"" Dawson" 
```
With `PSNativeCommandArgumentPassing` in effect (`$PSNativeCommandArgumentPassing='Standard'`), you'll now get
(broken) `"\"Andre" "\"\"The" "Hawk\"\"" "Dawson\""`

See #15261.

**Comment by mklement0** [comment]
@SteveL-MSFT, I've moved the gist of my previous comment to https://github.com/PowerShell/PowerShell/issues/15143#issuecomment-822805995, to have all the relevant information in one place.

Note that a new bug has since joined the ranks: #15276

**Comment by seanbudd** [comment]
Any updates on this bug?

**Comment by seanbudd** [comment]
Bump to keep open

**Comment by seanbudd** [comment]
Bump to keep open

**Comment by brian6932** [comment]
This is still an issue
