### ISSUE TITLE
Hyphen before parameter gets stripped on paste

### ISSUE THREAD

**Issue by rockerinthelocker** [PowerShell/PowerShell#15268]
Maybe someone from the A-team can have a look?
@TravisEz13 @SteveL-MSFT @iSazonov @daxian-dbw 

## Steps to reproduce
Copy and paste the following line into a Powershell Core console.
```
Optimize-Volume -DriveLetter C -Analyze –Verbose
```
## Expected behavior
The hyphen before the Verbose parameter should be preserved.
```
Optimize-Volume -DriveLetter C -Analyze –Verbose
```
## Actual behavior
The hyphen before the Verbose parameter has been stripped.
```
Optimize-Volume -DriveLetter C -Analyze Verbose
```
## Environment data

Note: This bug might affect all previous versions of Powershell Core as well.

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can repro with PSReadline 2.1. Please check with latest PSReadline preview 2.2 and if issue will still present open new issue in PSReadline repo.
