### ISSUE TITLE
Experimental feature PSNativeCommandArgumentPassing breaks the stop-parsing symbol

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15261]
Related: #15239, #15250, #15276 - see overview in #15143.

Seemingly, with experimental feature `PSNativeCommandArgumentPassing` in effect (and preference variable `$PSNativeCommandArgumentPassing` set to `'Standard'`), `--%`, the [stop-parsing symbol](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing) is broken in that it is seemingly _ignored_: escaping of `"` chars. that follow is now unexpectedly being performed:

## Steps to reproduce

On Windows (Unix is affected too, but `--%` doesn't make much sense there anyway):

```powershell
# This worked up to preview 4.
'foo' | find --% /v "" | Should -Be 'foo'
```

## Expected behavior

The test should succeed.

## Actual behavior

The test fails, because the `"` chars. are `\`-escaped:

```none
Access denied - \\
InvalidResult: Expected 'foo', but got $null.
```

In effect, command line `find /v "\"\""` is passed behind the scenes - instead of `find /v ""`

Note that with _without_ `--%` the command now works (`'foo' | find /v ""`, which previously failed).

While that is great, `--%` must not be broken.

## Environment data

```none
PowerShell Core 7.2.0-preview.5
```

**Comment by daxian-dbw** [comment]
@JamesWTruher Can you please take a look and see if this is by design? If not, please replace the `Needs-Triage` label with `Issue-Bug`.

**Comment by rmccampbell** [comment]
With some experimentation it looks to me like what is happening is the --% is not really being ignored, but it's being considered as one string literal and then passed as the first argument (which is then escaped), the same as if you wrote `find '/v ""'`.

**Comment by JamesWTruher** [comment]
the new behavior enables this scenario directly:
`'foo' | find /v ""` and the additional `--%` is not needed.
The addition of the `--%` creates the second argument as a literal `""` which is why the misbehavior occurs.
Because the previous behavior was constructing a string to be handed off, the quotes needed to be part of that string. The empty string is (and should be) present in the argument list without the quotes.

**Comment by rmccampbell** [comment]
Ignoring the oddities of find.exe, I think the --% syntax is still broken. By my understanding it should bypass both powershell parsing and any escaping, and pass the rest of the command line directly to the app, the same as it did in Legacy mode. This isn't the case though:

```
> $PSNativeCommandArgumentPassing = "Legacy"
> cmd --% /c echo "hi"
"hi"
> $PSNativeCommandArgumentPassing = "Standard"
> cmd --% /c echo "hi"
"\"hi\""
```
The Standard mode should match the Legacy mode here IMO.
(I'm not sure what the behavior should be if there are arguments before the --%, preferably those arguments would be properly escaped but I think that's probably irrelevant in most cases)

**Comment by rmccampbell** [comment]
Is this actually by design, given my previous comment? It doesn't seem to be usefully designed if so. That means that probably many cases would have to use `cmd /c` to get exact control over the command line

**Comment by mklement0** [comment]
@rmccampbell , please see
* #18664
