### ISSUE TITLE
GPtrustee object not returning currectly when run through SDK  

### ISSUE THREAD

**Issue by erenturkm** [PowerShell/PowerShell#15269]
I have been using Powershell SDK to run a script that gets Group Policy Permissions on a GPO.  When I run the script below over Remote Powershell on a Windows 2016 Host, it returns GPPermission Objects and when I walk through it the Trustee property is correctly returned as GPTrustee object. When I run this script from Powershell SDK 7.1.3, the trustee property returns a string for type of the object instead of the value. Note that rest of the permission object is populated fine. 

## Steps to reproduce

```powershell
$Dic=@{}
$List= New-Object Collections.Generic.List[string]
$GPOs=Get-GPO -All
foreach($G in $GPOs) 
{
	$Perms=Get-GPPermission -Name $G.DisplayName -all -TargetType Group -ErrorAction SilentlyContinue
	$Dic[$G.DisplayName]=$Perms
}
$Dic
```

## Expected behavior

```none
$Dic[<Any GPO>][0].Trustee.getType() returns GPTrustee object.
```

## Actual behavior
Visiual Studio c# code 
```none
Perm.Properties.Match("Trustee")[0].Value returns "Microsoft.GroupPolicy.GPTrustee"
```

## Environment data

```

Remote Powershell output
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

SDK Version.
PSVersion=7.1.3
PSEdition=Core
WSManStackVersion=3.0
PSRemotingProtocolVersion=2.3
```

**Comment by iSazonov** [comment]
Do you connect to Windows PowerShell or PowerShell Core?

**Comment by erenturkm** [comment]
Powershell running on the remote server is Windows Powershell 5.1.

**Comment by iSazonov** [comment]
Please try `$Dic.Values | % { $_ } | Select Trustee`.

**Comment by erenturkm** [comment]
iSazonov, this solution does not work or me. It only returns Trustee property of the permission into the SDK. I need to get the whole Permission object as PSObject and work on it in C#.

**Comment by PaulHigin** [comment]
WG-Remoting
You are running into the default remoting serialization depth, which is set to '2' by default.  Unfortunately, it can only be done in a round about way via a TypeTable.

https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.typedata.serializationdepth?view=powershellsdk-7.0.0

An easier work around would be to try and return an array of flat objects where depth is no larger than '2'.
