### ISSUE TITLE
PowerShell SDK Nuget Package does not work well with Self-Contained Deployment apps

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#15274]
I’m trying to consume the [Microsoft.PowerShell.SDK package](https://www.nuget.org/packages/Microsoft.PowerShell.SDK/), because I want to host the PowerShell runtime in my app. But the resulting file layout does not quite work in my situation.

Importantly (for this Issue), my app is built as a "Self-Contained Deployment" (SCD) (as opposed to a "Framework-Dependent Deployment" (FDD)). And targeting Windows only (RID of `win10-x64`).

When I build my VS solution, I end up with these files in my output directory:

```none
C:\SRC\TMP_DBGSHELL2\BIN\DEBUG\X64\RUNTIMES
├───unix
│   └───lib
│       └───net5.0
│           └───Modules
│               ├───Microsoft.PowerShell.Host
│               ├───Microsoft.PowerShell.Management
│               ├───Microsoft.PowerShell.Security
│               └───Microsoft.PowerShell.Utility
└───win
    └───lib
        └───net5.0
            └───Modules
                ├───CimCmdlets
                ├───Microsoft.PowerShell.Diagnostics
                ├───Microsoft.PowerShell.Host
                ├───Microsoft.PowerShell.Management
                ├───Microsoft.PowerShell.Security
                ├───Microsoft.PowerShell.Utility
                ├───Microsoft.WSMan.Management
                └───PSDiagnostics
```

The “unix” directory is definitely not needed at all—my sole TFM is “net5.0-windows” and my `<TargetPlatformIdentifier>` is Windows; my RID is win10-x64… so I don’t want anything n*x-related in my output.

But worse: the win “Modules” directory IS actually needed, but it is in the wrong place to be found at runtime--it should be in the root output directory (next to S.M.A.dll, else S.M.A.dll can’t find it).

# Repro steps

1. Create a default .NET “Hello world” console app. (Using VS 2019; .NET 5.0)
a. Fixed up the Platform to be x64 if you like
2. Make the app an SCD by adding the following lines to the .csproj:
```xml
  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
```

3. Add a reference to the PowerShell SDK by adding these lines to the .csproj:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.1.3" />
  </ItemGroup>
```
4. Add some code to the Main function to run “`ipmo PSDiagnostics -PassThru | fl`” to load the PSDiagnostics module, and then (crucially) show where the module is being loaded from. Something like:

```csharp
using System;
using System.Management.Automation;

namespace ReproPowerShellSdkPackageProblem
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            PowerShell shell = PowerShell.Create();

            shell.AddCommand("Set-ExecutionPolicy")
                 .AddParameter("ExecutionPolicy", "Bypass")
                 .AddParameter("Force", true)
                 .AddStatement();

            shell.AddCommand("Import-Module")
                 .AddParameter("Name", @"PSDiagnostics")
                 .AddParameter("PassThru", true)
                 .AddCommand("Format-List")
                 .AddCommand("Out-String");

            var results = shell.Invoke();
            foreach (var result in results)
            {
                Console.WriteLine("result: {0}", result);
            }

            // Notice the output: it will say that it got imported from some wacky place
            // which I think is an indication that it was imported from (legacy) Windows
            // PowerShell (5.1)--something like
            //
            //      "~\AppData\Local\Temp\remoteIpMoProxy_PSDiagnostics_1.0.0.0_localhost_9c08982f-951c-4119-9325-80631e83bf5a\remoteIpMoProxy_PSDiagnostics_1.0.0.0_localhost_9c08982f-951c-4119-9325-80631e83bf5a.psm1"
            //
            // But if you go to the bin dir and manually move the "Modules" folder from
            // "runtimes\win\lib\net5.0", up next to the EXE (and S.M.A.dll), and then
            // re-run, you will get the expected result: PSDiagnostics loaded from the
            // Modules directory you just placed in the bin dir.

            Console.WriteLine("[enter] to exit");
            Console.ReadLine();
        }
    }
}
```

## Expected results:
No "unix" stuff in my output dir. My app should be able to load and use the PSDiagnostics module (and other modules) that were included as part of the SDK.

## Actual results:
When you build and then run the EXE, it shows that PSDiagnostics is getting loaded from some strange location (in my case: "`~\AppData\Local\Temp\remoteIpMoProxy_PSDiagnostics_1.0.0.0_localhost_9c08982f-951c-4119-9325-80631e83bf5a\remoteIpMoProxy_PSDiagnostics_1.0.0.0_localhost_9c08982f-951c-4119-9325-80631e83bf5a.psm1`")

But if you manually move the “Modules” directory to be next to the EXE (and S.M.A.dll), then re-run it, it will correctly load the PSDiagnostics module from the Modules folder.

It really does make a difference that I’m making my app an SCD—if I get rid of that (just deleting that part in the .csproj, thus making it the default, fx-dependent), then that changes where S.M.A.dll gets put, and it manages to find the Modules directory okay in that case.

**Comment by ALIENQuake** [comment]
@jazzdelightsme 
FWIW, this is my solution:

```
<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
    </PropertyGroup>
    
    <Target Name="CopyModulesWin" AfterTargets="Publish" Condition="$(RuntimeIdentifier.StartsWith('win'))">
        <Exec Command="xcopy /s /y /i $(PublishDir)runtimes\win\lib\$(TargetFramework)\Modules $(PublishDir)Modules"/>
    </Target>
    
    <Target Name="CopyModulesUnix" AfterTargets="Publish" Condition="!$(RuntimeIdentifier.StartsWith('win'))">
        <Exec Command="cp -R $(PublishDir)runtimes/unix/lib/$(TargetFramework)/Modules $(PublishDir)Modules"/>
    </Target>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.0"/>
    </ItemGroup>
    
</Project>

```

**Comment by daxian-dbw** [comment]
> NOTE: Quote from https://github.com/PowerShell/PowerShell/issues/16525#issuecomment-983108982

This is because the modules are not correctly deployed to the publish folder when you specify `dotnet publish -r <RID>`. A few PowerShell built-in modules are shipped with the `Microsoft.PowerShell.SDK` nuget package, and when running `dotnet build` or `dotnet publish`, the modules will be deployed to `bin\...\runtimes\win\lib\net5.0`, next to the `System.Management.Automation.dll`, whose location is `$PSHOME` for the powershell hosted by the application.

However, when build with `dotnet publish -r <RID>`, all powershell assemblies are deployed in a flat list under `<RID>\publish` folder, but the modules are still at `<RID>publish\runtimes\win\lib\net5.0`. So `$PSHOME` becomes `<RID>\publish` and the `Modules` folder is missing from there.

This is a known issue, and it was done so because
1. There was no way (at least at the time when doing this) for a nuget package to choose where to deploy some content files depending on whether or not `-runtime` is specified.
2. Most applications that need to host PowerShell care more about `dotnet publish` scenario due to cross-platform portability.

So, the decision was made to accommodate `dotnet build` and `dotnet publish`, and leave `dotnet publish -r <RID>` broken.

The workaround is simple, just have a post-build script that copy the `Modules` folder from `<RID>publish\runtimes\win\lib\net5.0` to `<RID>publish`.
