### ISSUE TITLE
Azure.Storage.Blobs causes Connect-AzAccount to fail when using version 7.0.6 (.Core 3.1)

### ISSUE THREAD

**Issue by TheAtomAnt** [PowerShell/PowerShell#15277]
Using Azure.Storage.Blobs 12.8.1
PowerShell ConsoleHost version 7.0.6 (.Core 3.1)
PSVersion 7.1.3
Az PowerShell Cmds 5.8.0

Under the above conditions using Connect-AzAccount will throw
Could not load file or assembly 'Azure.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. The system cannot find the file specified.

However, I can use the same command in Visual Studio Code PowerShell for 7 (and ISE for 5.1)
If I uninstall Azure.Storage.Blobs the call works as expected

I can toggle back and forth between seeing the above error and the code working by installing and uninstalling Azure.Storage.Blobs.

## Steps to reproduce
Setup an Azure Account
Setup a Service Principal (service username/password)
Execute Connect-AzAccount -ServicePrincipal (with other required parameters)

With Azure.Storage.Blobs installed, ps.Streams.Error will contain an error with the text above. Without Azure.Storage.Blobs the AzAccount connection works as expected.

How to setup a service principal (powershell)
```
#Remember to log in as an Azure Admin FIRST (via Connect-AzAccount)
$UserName="AzureDevTestUser";
$Password="ThisIsAPasswordHere";
$TenantId = (Get-AzContext).Tenant.Id
$credentials = New-Object Microsoft.Azure.Commands.ActiveDirectory.PSADPasswordCredential -Property @{StartDate=Get-Date; EndDate=Get-Date -Year 2024; Password=$Password}
New-AzAdServicePrincipal -DisplayName $UserName -PasswordCredential $credentials
$sp = Get-AzADServicePrincipal -DisplayNameBeginsWith $UserName
$ApplicationId = $sp.ApplicationId;
New-AzRoleAssignment -ApplicationId $ApplicationId -RoleDefinitionName 'Contributor'
```

More detailed code. When running this code make sure to copy the ApplicaitonId and TenantId into the code in place of the variable names!
```
var iss = InitialSessionState.CreateDefault();
iss.ExecutionPolicy = ExecutionPolicy.Bypass;
var rs = RunspaceFactory.CreateRunspace(iss);
rs.Open();

var ps = PowerShell.Create();
ps.Runspace = rs;
ps.AddScript("$PWord = ConvertTo-SecureString -String ThisIsAPasswordHere -AsPlainText -Force;");
ps.AddScript("$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $PWord;");
ps.AddScript("$account=Connect-AzAccount -ServicePrincipal -Credential $Credential -Tenant $TenantId;");
ps.Invoke();

var errors = ps.Streams.Error.ToArray();
var informations = ps.Streams.Information.ToArray();
var verboses = ps.Streams.Verbose.ToArray();

var er = errors.FirstOrDefault();

var v = rs.SessionStateProxy.GetVariable("ver");
var commands = rs.SessionStateProxy.GetVariable("commands");
var account = rs.SessionStateProxy.GetVariable("account");
var t = rs.SessionStateProxy.GetVariable("t");
var accountsVer = rs.SessionStateProxy.GetVariable("accountsVer");
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please triage/classify the issue?

**Comment by JamesWTruher** [comment]
@TheAtomAnt - could you provide the output of `Get-Error` after you get this error? Having more information may help narrow the issue down.

**Comment by daxian-dbw** [comment]
@dingmeng-xue Could you please take a look at this issue? Could it be something with the `Azure.Storage.Blobs` module?

**Comment by dingmeng-xue** [comment]
Azure PowerShell are in different Github org and issue cannot be moved. Could you create a new Github issue our Azure PowerShell repo? We will follow up.
