### ISSUE TITLE
Piping off Invoke-RestMethod not expanding as expected

### ISSUE THREAD

**Issue by JAK1047** [PowerShell/PowerShell#15272]
## Steps to reproduce

This may not be an issue at all and just something in Powershell I am unaware of. While making a call to an internal REST API I noticed a difference when piping to a ForEach-Object vs saving the output to a variable first and running in a ForEach loop. If I do not either expand a property on the call or save it to a variable first then the output gets piped over to the foreach a single time as the full array. Does it have to serialize the data first or something? I've tried finding any relevant documentation for this exact scenario but haven't had any luck so far.

```powershell
$APIKey = 'APIKeyHere'
$Address = 'https://nagiosxi.contoso.com/nagiosxi/api/v1'

$Count1 = 0
$Count2 = 0

Invoke-RestMethod -Method GET -Uri "$Address/Config/contact?apikey=$APIKey" | ForEach-Object {$Count1++}

$Contacts = Invoke-RestMethod -Method GET -Uri "$Address/Config/contact?apikey=$APIKey"
ForEach ($Contact in $Contacts) {$Count2++}

Write-Output "Object count was: $Count1"
Write-Output "Object count was: $Count2"
```

## Expected behavior

```none
Object count was: 274
Object count was: 274
```

## Actual behavior

```none
Object count was: 1
Object count was: 274
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This is probably due to how the API returns the result, it can depend on the endpoint, but it is noticeably different at times to how Windows PowerShell handled it, I think. There's been a lot of discussion over it, and at the moment I don't recall if there was ever an agreement to change the behaviour or not.

The quick workaround is just to pipe the result through `Write-Output` to force it to enumerate -- `Invoke-RestMethod ...| Write-Output | ...`

**Comment by JAK1047** [comment]
That's interesting. I imagine any change to the behavior would probably be a breaking change, so if it's something already at least somewhat known it's certainly easy enough for me to work around. Was just the first time I had ever encountered it and my 15 minutes of Google didn't return me anything that seemed to match documentation wise.

**Comment by mklement0** [comment]
Yes, when `Invoke-RestMethod` receives an _array_, it sends that _as a whole_ to the pipeline, which contravenes PowerShell's usual behavior of _enumerating_ arrays, i.e. sending their elements _one by one_.

`ConvertFrom-Json` _used to_ behave this way, but the behavior was changed (effective as of at least 7.0), and a `-NoEnumerate` switch was added as an opt-in to the old non-enumeration behavior - see #3424 for the original discussion.

It would make sense to me to change `Invoke-RestMethod` in the same fashion, which would (again) be a breaking change, however.

A simpler, albeit a collect-all-output-in-memory-in-full-first alternative to the `Write-Output` workaround mentioned by @vexx32  is to simply enclose the `Invoke-RestMethod` in `(...)`, which also forces enumeration.

**Comment by JAK1047** [comment]
Order of operations type deal I got it. From a user perspective I can say the behavior I expected was enumeration like most every other command you send down the pipeline, but if the trade-off of changing the functionally does more harm then good then it may not be worth it in the grand scheme of things.

It would definitely make sense to me however to add a footnote on this objectively, nonstandard behavior to the Microsoft docs page for the cmdlet since I feel that's where most users, like myself, would turn to for guidance.

**Comment by mklement0** [comment]
> It would definitely make sense to me however to add a footnote on this objectively, nonstandard behavior to the Microsoft docs page for the cmdlet since I feel that's where most users, like myself, would turn to for guidance.

Good idea, please see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7504

> I don't know the consensus on why ConvertFrom-JSON was changed and if this checks similar boxes

To me, definitely - if the change was worth it for `ConvertFrom-JSON`, then it's also worth it for the same functionality that is built into `Invoke-RestMethod`.

**Comment by iSazonov** [comment]
> > I don't know the consensus on why ConvertFrom-JSON was changed and if this checks similar boxes
> 
> To me, definitely - if the change was worth it for `ConvertFrom-JSON`, then it's also worth it for the same functionality that is built into `Invoke-RestMethod`.

If it is true behavior please open new clear issue with the request.

**Comment by mklement0** [comment]
Good idea, @iSazonov; please see #15280
