### ISSUE TITLE
Passing a file, function name and parameters don't work in 7.1 as in 5.1 from cmd

### ISSUE THREAD

**Issue by stephen147** [PowerShell/PowerShell#15281]
## Steps to reproduce

Save this to `test.ps1`.

```powershell
function Get-Test() {
  [cmdletbinding()]
  Param (
    [Parameter(Mandatory = $true, HelpMessage = 'The test string.')]
    [String]$stringTest
    )
  Write-Host $stringTest
  return
}
```

## Expected behaviour

In my batch file for my installed 5.1 works.

```none
rem Using PowerShell 5.1 works
powershell.exe ". '...pathto\test.ps1'; Get-Test ""help me"""
```

## Actual behaviour

In my batch file for my portable 7.1 doesn't work.

```none
rem Using PowerShell 7.1 Portable doesn't work
"pathto...\pwsh.exe" ". '...pathto\test.ps1'; Get-Test ""help me"""
```

Everything is the same only I've pointed the `powershell.exe` to the path of the portable build.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
So as to support Unix shebang lines, `pwsh`'s CLI now defaults to the `-File` parameter (which expects only a _script-file path_), whereas `powershell.exe` default to `-Command` / `-c`.

To make your commands work with `pwsh`, you must use `-Commnand` / `-c` _explicitly_.

**Comment by stephen147** [comment]
> To make your commands work with `pwsh`, you must use `-Commnand` / `-c` _explicitly_.

Thanks. What is the correct syntax?

Here's my attempt but it doesn't work.
```
"...\pwsh.exe" -File "...pathto\test.ps1" -Command Get-Test ""help""
```

**Comment by mklement0** [comment]
`-File` and `-Command` were always mutually exclusive.

All you need is to prefix your command string(s) with the `-c` parameter:

```powershell
pathto...\pwsh.exe" -c ". '...pathto\test.ps1'; Get-Test ""help me"""
```

**Comment by stephen147** [comment]
> All you need is to prefix your command string(s) with the `-c` parameter:

Ah thanks.

Now the same syntax is working for both versions.

```
rem Both commands are now working in both v 5.1 and v7.1.
rem v7.1
"...pathto\pwsh.exe" -c ". '...pathto\ps-functions.ps1'; Get-Test ""help me"""
rem v5.1
powershell.exe -c ". '...pathto\ps-functions.ps1'; Get-Test ""help me"""
```
