### ISSUE TITLE
Make Invoke-RestMethod enumerate array-valued results by default, analogous to ConvertFrom-Json

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15280]
## Summary of the new feature/enhancement

* `ConvertFrom-Json`'s behavior was changed in v7.0 so as not to contravene the fundamental expectation that arrays are _enumerated_ in the pipeline - even though that change constituted a breaking one. A `-NoEnumerate` switch was added as an opt-in to the old, non-enumerating behavior (array being sent as a whole, as a _single object_ through the pipeline).
  * For the original discussion, see #3424.

* By contrast, `Invoke-RestMethod`, which has `ConvertFrom-Json` built in, in a manner of speaking, still exhibits the old, non-enumerating behavior, which leads to surprising behavior, especially with `ForEach-Object` and `Where-Object` - see #15272, for example.

Therefore, I suggest we change `Invoke-RestMethod` to follow `ConvertFrom-Json`'s new behavior:

* Array-valued results should be _enumerated by default_.

* A new `-NoEnumerate` switch would provide an opt-in to the old, non-enumerating behavior.

**Comment by JAK1047** [comment]
In my original issue I in particular was using Invoke-RestMethod. Would the changes recommended here for Invoke-WebRequest also backport to that cmdlet?

**Comment by MatejKafka** [comment]
@kilasuit Still relevant, please reopen.

**Comment by reaching-for-libra** [comment]
This caught me by surprise today (pwsh 7.6.1). I was sending the result of invoke-restmethod through to measure-object, and the output was a count of 1. This was super misleading, since the result of invoke-restmethod was an empty array
