### ISSUE TITLE
Combining -Recurse with -Name can lead to empty output

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15283]
Follow-up from https://github.com/PowerShell/PowerShell/issues/15259#issuecomment-823256524

Note: The problem seems to affect the `FileSystem` provider only; the other in-box hierarchical providers, `Registry`, `WSMan`, and `Certificate` are _not_ affected.

## Steps to reproduce

Note that `$PROFILE` is used as the path, i.e. a _file_ path, so by definition `-Recurse` should have no effect.

```powershell
Get-ChildItem -Path $PROFILE -Recurse -Name | Should -Be (Split-Path -Leaf $PROFILE)

Get-ChildItem -LiteralPath $PROFILE -Recurse -Name | Should -Be (Split-Path -Leaf $PROFILE)
```

## Expected behavior

Both tests should succeed, as indeed they do _without_ `-Recurse`

## Actual behavior

Both tests fail, because the empty string is unexpectedly output.

```none
Expected strings to be the same, but they were different. Expected length: 32 Actual length: 0
```

## Environment data

```none
PowerShell Core 7.2.0-preview.5
```

**Comment by iSazonov** [comment]
@mklement0 Thanks for opening the issue!

Oh, I'm afraid to even ask -  what about other providers?

**Comment by mklement0** [comment]
What other providers? :)
Fortunately, only the `FileSystem` provider seems to be affected - I've updated the initial post accordingly.
