### ISSUE TITLE
Running scripts targeting 5.1 or 7.1 from .Net5 Windows Forms Application

### ISSUE THREAD

**Issue by abhiphirke** [PowerShell/PowerShell#15288]
## Steps to reproduce

I have a requirement to develop Windows Forms (desktop) application in .Net5. This application is expected to run multiple different PowerShell scripts as may be required in a particular run. I am required to support PowerShell version 5.1 and/or 7.1. When I try to use the System.Management.Automation.PowerShell class, in test application, to begin with.

## Expected behavior

I am confused if this is problem of Windows Form application or .Net version or PowerShell version.

I am not able to understand what the issue is and how can I make it work.

Also, if different scripts that I am supposed to run target different PowerShell versions (one of 5.1 or 7.1), how can I control it from the same application?

Any reference material or hints or any help will be of much value since I am stuck on this.

## Actual behavior

In my simple test application, .Net5 Windows Forms Application, I am receiving following error. 

![image](https://user-images.githubusercontent.com/8724807/115531177-1aa79200-a2b2-11eb-8624-be6c79fcbbe0.png)

If I try the same in .Net Framework 4.7.2, it works!

## Environment data

I have PowerShell 5.1 and  7.1.3 are installed on my machine.

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ALIENQuake** [comment]
@abhiphirke You need to add `https://www.nuget.org/packages/Microsoft.PowerShell.SDK/` so you project will use NET5-release of System.Management.Automation.PowerShell.

**Comment by iSazonov** [comment]
You could read great post from @rjmholt  https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/

As meta note, currently MSFT released preview version of MAUI https://devblogs.microsoft.com/dotnet/announcing-net-multi-platform-app-ui-preview-3/ and if you are starting new project for many years maybe you should look this way, but no one has gone this way yet.

**Comment by rjmholt** [comment]
Impossible to know for sure from your screenshot (we'd need the full error and stack trace), but I strongly suspect you are compiling for one .NET platform and trying to run on another, which won't work.

Your starting point has a fundamental issue in it, which is that you have an application (i.e. a standalone executable) that needs to work with two different PowerShells. An application can only target one framework (if you target multiple, you will have multiple executables created in your publish step), but different PowerShells run different .NET frameworks. PowerShell is itself an executable, but that executable just wraps a set of assemblies that you can reuse via something like the SDK or the reference assemblies.

So the question essentially is: what are your base requirements? That will determine whether you need to build:

- Two different applications (the same code with two `TargetFrameworks`), one targeting .NET 4.8 and one targeting .NET Core 3.1, that each load PS 5.1 and PS 7 respectively
- A single application written in whatever you like that uses a serialisation layer to talk to its PowerShell of choice out of process
- A PowerShell module targeting .NET Standard and PowerShell standard that can be loaded by both PS 5.1 and PS 7, and a script that starts the relevant PowerShell, loads your module, and runs your "application" from that (this is what PowerShell Editor Services does)

**Comment by abhiphirke** [comment]
Thank you for all the help!
