### ISSUE TITLE
pwsh hung because it wants to connect to the Internet

### ISSUE THREAD

**Issue by fly4us** [PowerShell/PowerShell#15290]
We use pwsh to run scripts on win from ubuntu 18.04 in a private network every x minutes,  that's ok for a while. But someday, pwsh hungs, can't run any scripts. We found it trying to access the internet. After we used the proxy to connect to the Internet once, it no longer requested to connect to the Internet and returned to ok.

Can I close the Internet request? Or don't hung up. There is no internet in this project.
![image](https://user-images.githubusercontent.com/146662/115647215-fdc49a80-a355-11eb-8136-20eca83c951f.png)

![image](https://user-images.githubusercontent.com/146662/115647250-0a48f300-a356-11eb-8c9f-6691889f2978.png)

**Comment by anmenaga** [comment]
@fly4us try setting this environment variable before starting `pwsh`:
`export POWERSHELL_UPDATECHECK=Off`

The internet request on start is most likely check if a newer version was released. However this is not supposed to be a blocking call. @daxian-dbw may have some ideas on what can go wrong there.

**Comment by fly4us** [comment]
Thank you. 
Normally, the following information is in syslog 
![image](https://user-images.githubusercontent.com/146662/115656261-813ab780-a367-11eb-945d-8e6900254172.png)
When a problem occurs, the following information is in the syslog 
![image](https://user-images.githubusercontent.com/146662/115656324-a62f2a80-a367-11eb-9d76-4182c2b391bc.png)

**Comment by anmenaga** [comment]
Also outgoing connections may be the telemetry, which can be disabled with:
`export POWERSHELL_TELEMETRY_OPTOUT=1`

@fly4us please advise if you still see hangs after setting both env vars `POWERSHELL_UPDATECHECK` and `POWERSHELL_TELEMETRY_OPTOUT`.

**Comment by daxian-dbw** [comment]
@fly4us The additional syslog entries indicated that snap was trying to do an update, so it's likely snap is the one that requesting internet access and the cause of a crash.

PowerShell doesn't depend on internet access, both the ps update check and telemetry are not blocking.

**Comment by DejayRezme** [comment]
Just to add: About 2 months ago I didn't have internet access and powershell would hang for about 5 seconds every time I launch a new instance. I can't reproduce the issue now but it's definitely the case that depending on network config, powershell can hang with a timeout on startup.

**Comment by SuperCatss** [comment]
> Just to add: About 2 months ago I didn't have internet access and powershell would hang for about 5 seconds every time I launch a new instance. I can't reproduce the issue now but it's definitely the case that depending on network config, powershell can hang with a timeout on startup.

I have the same problem, I work in an environment with no internet, and every startup needs to wait 5-10 seconds
