### ISSUE TITLE
Add telemetry and logging to the `LoadAssemblyFromNativeMemory` API

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#15293]
This issue is opened to follow up on the code review comment https://github.com/PowerShell/PowerShell/pull/14652#discussion_r618521816:
> The use of this API should be logged, at minimum on Windows platform.
@TravisEz13  Do you have any ideas on where it should be logged?  I am thinking a new ETW PowerShell log entry for this.

It is an unusual API that bypasses our normal scriptblock or module logging, so logging should be added for defense in depth.
Also, consider add telemetry as well, so we know how much this API gets used.

**Comment by daxian-dbw** [comment]
The logging is better to happen on all platforms. For ETW, we may or may not need to update our ETW manifest.

**Comment by iSazonov** [comment]
> It is an unusual API that bypasses our normal scriptblock or module logging

It's strange there is an old Windows PowerShell API that does not have this.

**Comment by daxian-dbw** [comment]
https://github.com/PowerShell/PowerShell/pull/14652#issuecomment-827142603 from the security working group:

> there should be non-repudiation logging, which should include:
>
>- The user
>- the process
>- a size and hash or the assembly (or something else to identify the assembly)
>
>Once we have code for the logging, the security working group should review the PR
