### ISSUE TITLE
Should $PSScriptRoot be added to foreach-object-Parallel？

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#15302]
# Should $PSScriptRoot be added to foreach-object-Parallel？

Currently, this automatic variable is not implemented. Use & "${PSScriptRoot}/xxx.ps1 in a child thread, an error will be reported.

## Proposed technical implementation details (optional)
```
 xxx | ForEach-Object  -Parallel {
		${PSScriptRoot} = $using:PSScriptRoot #default add this line
		& "${PSScriptRoot}/xxx.ps1"
}
```
@PaulHigin

**Comment by mklement0** [comment]
See #12240, which more generally proposes copying the caller's state to the runspaces of the parallel threads on an opt-in basis.

**Comment by SeeminglyScience** [comment]
@mklement0 `PSScriptRoot` would need to be handled on it's own.  It's the closest thing PowerShell has to a lexically scoped variable and is overwritten at the start of every new command.

e.g.

```powershell
$PSScriptRoot = 'test'
. { $PSScriptRoot }
# empty
```

`-Parallel` would need to recreate the scriptblock with something like this:

```csharp
var ast = Parser.ParseFile(originalSb.ToString(), originalSb.Ast.Extent.File, ref _, ref _);
ast.GetScriptBlock();
```

but then the challenge is that the `PowerShell` API does not make it easy to directly invoke a scriptblock (#15004).

<sub>(I know you already know that last bit, included for context)</sub>

**Comment by PaulHigin** [comment]
This can be considered as part of the #12240 work.

**Comment by PaulHigin** [comment]
Closing and merging as part of #12240.
