### ISSUE TITLE
$PostMatch and $PreMatch variable

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15307]
Hi Guys !

in PS we can use $Matches to see the matches. its awesome to add 2 new variable to see the pre-match match and the post-match. example:

```
PS C:\> 'powershell' -match 's'
True
PS C:\> $Matches

Name                           Value
----                           -----
0                              s

PS C:\> $PreMatch
power
PS C:\> $PostMatch
hell
```

**Comment by 237dmitry** [comment]
It's not entirely clear what the profit is?
```
 > 'powershell' -match '^(.+)(s)(.+)$'
True
 > $matches

Name                           Value
----                           -----
3                              hell
2                              s
1                              power
0                              powershell

 > 'powershell' -split '(?<=^.+)(s)(?=.+$)'
power
s
hell
```

**Comment by p0W3RH311** [comment]
@237dmitry 

thanks 

yes i know we can use regex for this ans also we can use maybe psbreakpoint to create this variables prematch and postmatch in global scope.

but the benefit to $prematch and $postmatch is like $matches. we can use these variables outside the context of regex like $matches

**Comment by vexx32** [comment]
As @237dmitry demonstrated, it's pretty trivial to retrieve these values when necessary.

I'm not sure I see the benefit of having pwsh _always_ spend extra cycles performing additional operations to retrieve these values when not even asked to do so.
