### ISSUE TITLE
$PSModuleAutoLoadingPreference on Linux not functioning

### ISSUE THREAD

**Issue by VaughanJ** [PowerShell/PowerShell#15318]
Setup:
Powershell Version: 7.1.3

Linux Ubuntu18 Container

$PSModuleAutoLoadingPreference="All"

AWSPowershell installed:
```
Directory: /root/.local/share/powershell/Modules

ModuleType Version PreRelease Name                             PSEdition ExportedCommands

---------------------------------------------------------------------------------------------------------

Binary           4.1.2.0                     AWSPowerShell.NetCore Desk
```

Steps to reproduce:

Command:

Use-STSRole

Output:

Use-STSRole: The term 'Use-STSRole' is not recognized as a name of a cmdlet, function, script file, or executable program.

Commands:

Import-Module AWSPowerShell.NetCore

Use-STSRole

Output:

Use-STSRole: No credentials specified or obtained from persisted/shell defaults.

Expected results:

When I run Use-STSRole when the $PSModuleAutoLoadingPreference="All" the module should auto load (no need to import) and the command be called. This is what occurs on Windows and I believed the functionality would be the same, but that's not what I'm seeing.

**Comment by daxian-dbw** [comment]
> AWSPowershell installed:
>```
>Directory: /root/.local/share/powershell/Modules
>
>ModuleType Version PreRelease Name                             PSEdition ExportedCommands
>
>---------------------------------------------------------------------------------------------------------
>
>Binary           4.1.2.0                     AWSPowerShell.NetCore Desk
>```

@VaughanJ The module output from your PR description shows now `ExportedCommands`, can you verify if that's the case?

**Comment by VaughanJ** [comment]
I meant to come back to you, it was that the PSD1 didn't have the "FunctionsToExport" explicitly listed. Which looks to prevent them from autoloading.

I swapped out to the new AWS.Tools which had the "FunctionsToExport" defined.

Thanks
