### ISSUE TITLE
Allow New-Guid to accept optional byte array

### ISSUE THREAD

**Issue by chelnak** [PowerShell/PowerShell#15317]
## Summary of the new feature/enhancement

As a user I would like `New-Guid` to accept an optional custom byte array at creation time, allowing me to control the bytes that are used to create the Guid object.

## Proposed technical implementation details (optional)

For example something like...

``` PowerShell

$Bytes = [System.Byte[]]::new(16)
$RNG = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()
$RNG.GetBytes($Bytes)

$VersionByteIndex = [System.BitConverter]::IsLittleEndian ? 7 : 6
$Bytes[$VersionByteIndex] = $Bytes[$VersionByteIndex] -band [char]0x0F -bxor [char]0x40
$Bytes[9] = $Bytes[9] -band 0x3F -bxor 0x80

New-Guid -Bytes $Bytes

```

The underlying c# implementation would have a code path that calls `new Guid(Byte[])`.

https://docs.microsoft.com/en-us/dotnet/api/system.guid.-ctor?view=net-5.0#System_Guid__ctor_System_Byte___

Also if you want to ensure that the result is v4 RFC 4122 compliant then some sort of validation would be needed.

**Comment by mklement0** [comment]
Note that `New-Guid` is just a wrapper around `Guid.NewGuid()`, i.e. it generates a _new_ GUID for you.

By contrast, the [constructors](https://docs.microsoft.com/en-us/dotnet/api/system.guid.-ctor) of the `Guid` type essentially _convert preexisting data_ to a `Guid` instance.

In other words: surfacing the constructor functionality wouldn't be an extension to the cmdlet's current mandate, but would mean adding entirely new functionality to it, and to me the question is:

Is this a common enough use case to warrant extending `New-Guid`, given that calling the constructors directly is already an option?

```powershell
# Using an empty byte array for simplicity. Note that System.Guid also doesn't provide validation.
$bytes = [byte[]]::new(16)
[Guid]::new($bytes)
```

Alternatively, using the [`New-Object`](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/new-object) cmdlet to call constructors (passing an _array_ as the only constructor argument makes this awkward):

```powershell
# Using an empty byte array for simplicity. Note that System.Guid also doesn't provide validation.
$bytes = New-Object byte[] 16
New-Object Guid (, $bytes)
```

**Comment by chelnak** [comment]
Nice, thank you for the clear comment.

Agree about calling the constructor directly and is what I do in these edge cases.
