### ISSUE TITLE
PowerShell crash with System.Management.Automation.PSInvalidOperationException on hosted PowerShell application

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15313]
A crash happens when a hosted application using PowerShell SDK have couple of statements added.

The code for the application looks like:

```csharp
static void Main(string[] args)
{
    var ps = System.Management.Automation.PowerShell.Create();
    ps.Commands.Clear();

    var t = Task.Run(() => { Thread.Sleep(3000); ps.Stop(); ps.Dispose(); });

     ps.Commands.AddCommand("Import-Module").AddArgument("PackageManagement")
      .AddStatement()
      .AddScript("Get-Childitem -Path '~' -Recurse")
      .AddStatement()
      .AddScript("Get-Childitem -Path '~' -Recurse");

    var result = ps.InvokeAsync();

    Task.WaitAll(result);

    foreach(dynamic r in result.Result)
    {
        Console.WriteLine($"{r.FullName}");
    }
}
```

The expectation is that we get a `PipelineStoppedException` and not a a crash.

The SDK version used is `7.1.3`.

## Steps to reproduce

```none
```

## Expected behavior

```none
PipelineStoppedException
```

## Actual behavior

```none
System.Management.Automation.PSInvalidOperationException
  HResult=0x80131509
  Message=Objects cannot be added to a closed buffer. Make sure the buffer is open for Add and Insert operations to succeed.
  Source=System.Management.Automation
  StackTrace:
   at System.Management.Automation.PSDataCollection`1.InternalInsertItem(Guid psInstanceId, Int32 index, T item)
   at System.Management.Automation.PSDataCollection`1.InternalAdd(Guid psInstanceId, T item)
   at System.Management.Automation.PSDataCollection`1.Add(T item)
   at System.Management.Automation.PowerShell.AppendExceptionToErrorStream(Exception e)
   at System.Management.Automation.PowerShell.BatchInvocationWorkItem(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

## Environment data
```none
SDK version `7.1.3`
```

**Comment by adityapatwardhan** [comment]
@JamesWTruher - knows whats going on here. `Stop` stops the current command not the whole execution.

**Comment by adityapatwardhan** [comment]
The expectation of the app developer is to stop all pipelines that are invoked asynchronously. The `Stop` API as documented stops the current command. So when there are more commands in the pipeline and `Dispose` is called, we get a `PSInvalidOperationException`. 

**Feature enhancement** is to add new API for overloading `Stop` which will take a enum parameter for either stopping the current command or the whole pipeline.

Workaround is to add `Dispose()` after the `Task.WaitAll()` instead of in the Task, this will make sure that after cancelling the current command, the next command completes.

If the intention is to stop all the commands, then they need to be in a single statement. So instead of `AddCommand().AddStatement().AddCommand()`, it should be changed to `AddScript(<command1>; <command2>; <command3>)`

**Comment by et1975** [comment]
A curious aspect is that it doesn't matter where in the queue the current command is. Even if it's the last command `Stop` will still crash. This can be seen with this little example:

```csharp
        public static int Main () {
            var ps = PowerShell.Create();
            ps.AddCommand("Import-Module").AddArgument("PackageManagement")
              .AddStatement()
              .AddScript("Get-ChildItem -Path '~' -Recurse");
            var t = Task.Run(() => { Thread.Sleep(4_000); ps.Commands.Clear(); ps.Stop(); ps.Dispose(); } );
            try {
                ps.InvokeAsync().Wait();
            } catch {}
            return 0;
        }
```
Adjust the timeout any way you like, the process will still crash. As you can see I also tried clearing the commands before calling `Stop` and `Dispose` - predictably, it does not help.

**Comment by et1975** [comment]
Also, would be good to adhere to [ca1065](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065). I.e. `Dispose` should not throw, let alone crash regardless of what the pipelines are doing.

**Comment by et1975** [comment]
Why was this closed (as completed!), was anything fixed?
