### ISSUE TITLE
Easily index a list with `for` command

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#15321]
In addition to the other requests to more easily iterate through the _index_ of an object list:
- [`#14724` implement indexer in loop](https://github.com/PowerShell/PowerShell/issues/14724)
- [`#13772` Automatic variable for the pipeline index](https://github.com/PowerShell/PowerShell/issues/13772)

There are currently common ways to iterate through the _index_ of an object list:

```PowerShell
$List = @(
    [pscustomobject]@{Name = 'One';   Value = 1}
    [pscustomobject]@{Name = 'Two';   Value = 2}
    [pscustomobject]@{Name = 'Three'; Value = 3}
)
```
```PowerShell
For ($i = 0; $i -lt $List.Count; $i++) {
    Write-Host $List[$i].Name '=' $List[$i].Value
}
```
```PowerShell
0..($List.Count - 1) |ForEach-Object {
    Write-Host $List[$_].Name '=' $List[$_].Value
}
```

Knowing that the `For` command generates an error when no parenthesis are used:

> ```PowerShell
> PS C:\> For $Test
> ParserError:
> Line |
>    1 |  For $Test
>      |     ~
>      | Missing opening '(' after keyword 'for'.
> ```

It might might just generate a (new) index if a object (list) is supplied.

**Wishful thinking:**
```PowerShell
For $List {
    Write-Host $List[$_].Name '=' $List[$_].Value
}
```
Or using the pipeline:
```PowerShell
$List |For {
    Write-Host $List[$_].Name '=' $List[$_].Value
}
```

Caveat: As with the `ForEach-Object`, it might be required to force the input to an array: `@($List) |For { ...`

**Comment by iSazonov** [comment]
> ```powershell
> $List |For {
>     Write-Host $List[$_].Name '=' $List[$_].Value
> }
> ```

Follow does not work for you?

```powershell
$List |ForEach {
     Write-Host $_.Name '=' $_.Value
 }
```

**Comment by iRon7** [comment]
@iSazonov 

> Follow does not work for you?

I think that I oversimplified the examples in the purpose... 🥴
Yes, that works with the examples but not if I want also need to use the index for some thing else, like:

```PowerShell
$Dutch = @(
    [pscustomobject]@{Name = 'Een';  Value = 1}
    [pscustomobject]@{Name = 'Twee'; Value = 2}
    [pscustomobject]@{Name = 'Drie'; Value = 3}
)

For ($i = 0; $i -lt $List.Count; $i++) { # purposed syntax: $List |For {
    [PSCustomObject]@{
        Number  = $List[$i].Value
        English = $List[$i].Name
        Dutch   = $Dutch[$i].Name
    }
}
```

**Comment by mklement0** [comment]
@iRon7, it seem to me that your expanded example - processing the corresponding elements from two (or more) collections - is more elegantly handled by the proposal in #14732; e.g.:

```powershell
# Wishful thinking.
foreach ($en, $nl in $List, $Dutch) {
    [PSCustomObject] @{
        Number  = $en.Value
        English = $en.Name
        Dutch   = $nl.Name
    }
}
```

And since #14732 can be combined with #14724, you could easily add an index with
`foreach ($en, $nl in $List, $Dutch; $i) ...`

**Comment by daxian-dbw** [comment]
@iRon7 What you are proposing here is more of a command (the pipeline behavior `$list | For`). You can implement one by wrapping the existing `for` loop, like this extremely simplified example:
```
function MyFor
{
    param($list, $sb)
    for ($i = 0; $i -lt $list.Count; $i++) { & $sb } }
}
```
Then I got
```
PS:103> MyFor $List {
>>     [PSCustomObject]@{
>>         Number  = $List[$i].Value
>>         English = $List[$i].Name
>>         Dutch   = $Dutch[$i].Name
>>     }
>> }

Number English Dutch
------ ------- -----
     1 One     Een
     2 Two     Twee
     3 Three   Drie
```
The proposal in  #14732 is more general purpose to discuss, so I will close this one.

**Comment by iRon7** [comment]
@mklement0,

>  is more elegantly handled by the proposal in #14732

You have a good point here. Yet, if these proposal(s) do not make it, I think it could be alternative.
Besides, I don't think that the "lengthy" common `For ($i = 0; $i -lt $List.Count; $i++)` or `0..($List.Count - 1) |ForEach-Object` statements will be completely disappear from the scene by any or all of these proposals.

@daxian-dbw 

> You can implement one by wrapping the existing for loop, like this extremely simplified example

Agree (thanks for adding the prototype 😀).
The question is whether this is to the scripter to add or could be a part of native PowerShell.
As a comparison: years ago, PowerShell had no easy syntax for an inline if, probably because it could be implemented with an *extremely simplified [`IIf` function](https://stackoverflow.com/a/25682508/1701026)*. Today, we have an  `Immediate if`/`ternary If` syntax included in PowerShell.
