### ISSUE TITLE
Add a couple of simple tests case for invoke-restmethod/webrequest, and move the rest of the tests for feature.

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#1532]
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
@Francisco-Gamino We have some tests already, do we still need this issue?

**Comment by Francisco-Gamino** [comment]
@SteveL-MSFT: No, we do not need this anymore. I've added a couple of CI test cases to validate both invoke-webrequest and invoke-restmethod, so we can close this issue.

**Comment by Francisco-Gamino** [comment]
Here is the link to CI tests that I've added:https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1#L811.
