### ISSUE TITLE
Add an operator to allow safe checking for property names in Strict Mode

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#15338]
## Summary of the new feature/enhancement

Currently Strict Mode is very difficult to use effectively, as there isn't really a good way to safeguard code against errors that may arise from objects not having certain properties. Given how mutable objects can be in powershell, this makes working in strict mode more frustrating than it needs to be.

## Proposed technical implementation details (optional)

Currently the only real way to check this is with the somewhat obscure `$object.PSObject.Properties.Name -contains $propName` -- an operator should be provided that checks whether the property exists in a similar way (can we be more thorough than this? Should we?) and safely returns a null or false so that these expressions are easier to write.

Temporarily borrowing the `?.` operator for now (we don't _have_ to use this operator, but at least to me it sort of makes sense here), it would look something like this:

```powershell
$value = if ($myObj?.Property) {
    $myObj.Property
}
else {
    $safeDefault
}

# nice and neat if we use null coalescing too

$value = $myObject?.Property ?? $safeDefault
```

**Comment by iRon7** [comment]
With the latest version of `Set-StrictMode` there are even two different kind of strict errors here:

```PowerShell
$MyObject = [PSObject]@{ Property = 1 }
Set-StrictMode -Version Latest
```

The object not exists (is `$Null`):
```PowerShell
$ObjectNotExists.Propery
```
> InvalidOperation: The variable '$ObjectNotExists' cannot be retrieved because it has not been set.

and the property not exists:
```PowerShell
$MyObject.ProperyNotExists
```
> PropertyNotFoundException: The property 'ProperyNotExists' cannot be found on this object. Verify that the property exists.

Meaning that this probably requires also two enhancements:
If the object potentially not exists (is `$Null`):
```PowerShell
$myObject?.Property
```
and if the property potentially  not exists:
```PowerShell
$myObject.Property?
```
Or where potentially both the object and the property might not exist:
```PowerShell
$myObject?.Property?
```
