### ISSUE TITLE
Default "View Format" (Format.ps1xml) cannot be extended

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/PowerShell#15332]
I'm attempting to **extend** the default format view (`format.ps1xml`) and it's not clear from the [documentation ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-7.1) how to do that. 

All I've managed to do is **overwrite** the default view, or create a new view that I then have to explicitly request (`Format-List -View MyView`).

For example:

I want to add an additional property to the TimeSpan list view:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/PowerShell/PowerShell/master/src/Schemas/Format.xsd">
  <ViewDefinitions>
    <View>
      <Name>System.TimeSpan</Name>
      <ViewSelectedBy>
        <TypeName>System.TimeSpan</TypeName>
      </ViewSelectedBy>
      <ListControl>
        <ListEntries>
          <ListEntry>
            <ListItems>
              <ListItem>
                <Label>Human</Label>
                <ScriptBlock>
                  [Humanizer.TimeSpanHumanizeExtensions]::Humanize($_, 3)
                </ScriptBlock>
              </ListItem>
            </ListItems>
          </ListEntry>
        </ListEntries>
      </ListControl>
    </View>
  </ViewDefinitions>
</Configuration>
```

I either get this:

```powershell
Update-FormatData -AppendPath my.formats.ps1xml
[TimeSpan]::FromDays(1.4)

Days              : 1
Hours             : 9
Minutes           : 36
Seconds           : 0
Milliseconds      : 0
Ticks             : 1209600000000
TotalDays         : 1.4
TotalHours        : 33.6
TotalMinutes      : 2016
TotalSeconds      : 120960
TotalMilliseconds : 120960000
```

No "Human" field is displayed.

Or this:

```powershell
Update-FormatData -PrependPath my.formats.ps1xml
[TimeSpan]::FromDays(1.4)

Human : 1 day, 9 hours, 36 minutes
```
All the default properties have disappeared.

What I'm expecting to see is:

```powershell
[TimeSpan]::FromDays(1.4)

Days              : 1
Hours             : 9
Minutes           : 36
Seconds           : 0
Milliseconds      : 0
Ticks             : 1209600000000
TotalDays         : 1.4
TotalHours        : 33.6
TotalMinutes      : 2016
TotalSeconds      : 120960
TotalMilliseconds : 120960000
Human             : 1 day, 9 hours, 36 minutes
```

Is there a way to achieve what I want? It surprised me that ``Append`` did not append my definition to the existing one.
Do I need to structure my XML differently, or is there something missing in the XSD that allows inheritance? e.g. something like:

```xml
...
<ListItems>
  <Inherit />
    <ListItem>
      ...
    </ListItem>
</ListItems>
```

Usage Scenarios:

1. I don't want to have to replace/re-apply any changes to the default formats when powershell is updated.
2. I want to benefit from multiple modules extending/altering views e.g [with colors/icons](https://github.com/devblackops/Terminal-Icons), [better length values](https://github.com/dfinke/PowerShellHumanizer) etc. It seems impossible to use both modules at once because one will overwrite the format of the other. Currently, it seems only manually merging the formats is possible.

**Comment by daxian-dbw** [comment]
The formatting view doesn't support inheritance or extending today, but it sounds an interesting thing to discuss about.
