### ISSUE TITLE
Powershell add-computer breaking existing PCs in ADMy bug report

### ISSUE THREAD

**Issue by gthubuser1** [PowerShell/PowerShell#15336]
Hi, I started using Powershell add-computer script to join my PCs to the domain and I quickly found out, rather painfully, is that the command will replace the GUID in AD so if another PC already exists in AD, it will replace it and I suddenly get a broken PC in AD that the users were using. Why?

So to make it harder, I am using MDT to mass deploy images and as such, I can not install RSAT on every workstation to get the AD powershell module installed in Powershell. Can anyone please recommend a method to prevent my imaging to pop existing PCs in AD using MDT or if there is a way to tell the function to not change existing PCs?

**Comment by daxian-dbw** [comment]
@gthubuser1 Thanks for opening the issue. `Add-Computer` is only available in Windows PowerShell (version 5.1), while issues tracked here are only for PowerShell Core 6 and higher. The Windows PowerShell specific issues should be opened on [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell).

So please report the `Add-Computer` issue there, and make sure include as much details of the issue as possible.
