### ISSUE TITLE
Excessive memory usage after Start-Transcript

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#15341]
I noticed PowerShell seemed to be hung for 8+ hours after running a long running script for multiple days. While investigating, I noticed my machines memory usage was at 99%.

I attached JetBrains dotMemory to the process and found 48GB of memory in use by 215 million instances of System.String. My PowerShell script is just a simple wrapper around running external executables like this:

```powershell
fuzz.exe > fuzz.log 2>&1
```

When I looked at `fuzz.log`, it was about 22GB - so there is some correlation between the output of the native executable and the total memory used.

Here is the retention path for 54GB of memory (over 3 instances of PipelineProcessor)

```
Retention path of System.String[134217728]

0x000001c482840fe0 System.Management.Automation.Internal.PipelineProcessor._eventLogBuffer ->
0x000001c482841080 System.Collections.Generic.List<System.String>._items ->
0x000001d351fb1020 System.String[134217728]
```

Here is a random sampling of strings retained in this object:

```
CommandInvocation(out-lineoutput): "out-lineoutput"
ParameterBinding(out-lineoutput): name="LineOutput"; value="Microsoft.PowerShell.Commands.Internal.Format.TextWriterLineOutput"
ParameterBinding(out-lineoutput): name="InputObject"; value="G:\job\fuzz.exe -max_total_time=300 -print_final_stats=1 -print_corpus_stats=1 corpus >fuzz-11.log 2>&1"
ParameterBinding(out-lineoutput): name="InputObject"; value="INFO: Loaded 1 PC tables (15410 PCs): 15410 [00007FF7CD6C1F78,00007FF7CD6FE298), "
```

Tracing through the code, I did notice that this logging might be related to `Start-Transcript` and I can confirm I was using `Start-Transcript` at the time.

**Comment by daxian-dbw** [comment]
The `_eventLogBuffer` is actually used only if [NeedToLog()](https://github.com/PowerShell/PowerShell/blob/a95b2cb17fecc8640533420b3baa9aec0f3749cb/src/System.Management.Automation/engine/pipeline.cs#L231) returns true, which _may_ return true only if the `EnableModuleLogging` group policy setting is enabled. So, in most of cases, logging strings are collected into this list, but is never actually used.

We should not collect the logging strings when we are not going to log them. I will submit a PR for this.

**Comment by lzybkr** [comment]
The buffer should still be flushed periodically to avoid OOM conditions like I was effectively hitting.

**Comment by daxian-dbw** [comment]
Yeah, but that's a little tricky as the [LogToEventLog()](https://github.com/PowerShell/PowerShell/blob/a95b2cb17fecc8640533420b3baa9aec0f3749cb/src/System.Management.Automation/engine/pipeline.cs#L229) (_write a pipeline execution detail event_) is not called until a pipeline processor is done executing and being teared down.

Actually, this design has a fundamental flaw when __eventLogBuffer_ holds a large number of logging messages -- the event may be lost when the payload is too large (the size limit for an ETW event is 64K). In your case, the length of the string array is 134217728. That's a lot strings, and the event payload will exceed the limit for sure. It should be fixed to write out the detail event in parts, when it's getting close to the event size limit, and of course those partial events need to be correlated.
