### ISSUE TITLE
Powershell 7.1.3. does not run under Raspberry Pi 4

### ISSUE THREAD

**Issue by Gill-Bates** [PowerShell/PowerShell#15356]
When running Powershell Core 7.13 under Raspbian on a Raspberry Pi 4, I get a Dotcom-Exception.

I've followed these Installation Instructions:

[https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation---raspbian](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1#installation---raspbian)

A little bit of Googleing revealed, that it seems, Powershell 7.13 does not support the Processor (Broadcom BCM2711).

With my Raspberry Pi 3 everything works fine. Is there an official statement about this?

**Comment by vexx32** [comment]
If there is an issue with supporting the processor, that's going to be a .NET level issue and not something PowerShell directly has any way of controlling. 

This seems to be a current list of officially supported OSes and architectures under .NET 5 (which I think is what PS 7.1.3 is running under?)

**Comment by daxian-dbw** [comment]
@Gill-Bates Can you share the error message you go when failing to run PS 7.1.3 on Raspberry Pi 4?
I did a quick search and found this article [Installing and Developing .NET 5 Apps on Raspberry Pi 4](https://mycsharpdeveloper.wordpress.com/2020/09/12/installing-and-developing-net-5-apps-on-raspberry-pi-4/), so it looks like .NET 5 works on Raspberry Pi 4. /cc @anmenaga

**Comment by adityapatwardhan** [comment]
@Gill-Bates Please provide information about the OS that is installed on the Raspberry Pi 4 and the error message that you are seeing. Also please mention if it was executed on 32-bit or 64-bit.

**Comment by anmenaga** [comment]
Here is example of PS 7.1.3 running on Raspberry Pi 4 Model B on latest [Raspberry Pi OS with desktop](https://www.raspberrypi.org/software/operating-systems/#raspberry-pi-os-32-bit) (`2021-03-04-raspios-buster-armhf.img`)

![Pi4_ps713](https://user-images.githubusercontent.com/11860095/118072159-20970d00-b35e-11eb-998d-52e82fce2321.png)

**Comment by ErikApption** [comment]
Ok so out of the box - and following the instructions I get
```
[22:39:20] openhabian@openhab:/opt/powershell$ ./pwsh
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at Microsoft.PowerShell.NativeCultureResolver.get_UICulture()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
Aborted
```
I got passed this error after changing the pwsh.runtime.json but after I get the following error
And libicu is installed.

```
[22:38:25] openhabian@openhab:/opt/powershell$ ./pwsh
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

No usable version of libssl was found
Aborted
```
And libssl1.1 libssl1.1-dev are installed.
