### ISSUE TITLE
Write-Error Fails When Category = ParserError

### ISSUE THREAD

**Issue by BinaryWizard904** [PowerShell/PowerShell#15354]
In PowerShell v7.1.3, `Write-Error` fails with an `InvalidOperation` error when the Category is ParserError and the ErrorAction is Continue or SilentlyContinue.

## Steps to reproduce

```powershell
Write-Error -Message "Testing 123" -Category ParserError -ErrorAction Continue
$Error
```

## Expected behavior
The specified error is output to the Error Stream and/or console.
```none
Write-Error:
Line |
   1 |  Write-Error -Message "Testing123" -Category ParserError -ErrorAction  …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Testing123
```
*The example output above is taken from the output of `Write-Error` when ErrorAction is set to Stop.
## Actual behavior
Write-Error fails and outputs the following error to the Error Stream.  Nothing is output to console.
```none
InvalidOperation:
Line |
 110 |  …                      $line = $positionMessage[1].Substring(1) # skip  …
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

InvalidOperation: An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute..
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
I think this is probably intentional. ParserErrors are only supposed to be utilised from the PowerShell parser itself, and they are by definition terminating errors. If a script can't be parsed, it can't be executed, period.

**Comment by daxian-dbw** [comment]
The error is thrown from the formatting script for the Concise error view: https://github.com/PowerShell/PowerShell/blob/f38c97e4f44b06304e5ce34aa879034c4639ac19/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1158-L1159

@SteveL-MSFT can you please take a look?

**Comment by BinaryWizard904** [comment]
> 
> 
> I think this is probably intentional. ParserErrors are only supposed to be utilised from the PowerShell parser itself, and they are by definition terminating errors. If a script can't be parsed, it can't be executed, period.

It worked in older versions of PowerShell, though I haven't narrowed down the latest version it did so (probably before the new error output style, though).  Even assuming nobody intended for this category to ever be manually invoked as done in the reproduction steps, the ease with which it can be tells me this should be handled better.  `Write-Error` is not the sort of thing that should cryptically and silently fail when invoked in such a simplistic manner.  That's just asking for people (especially newcomers) to get into bad error handling habits to workaround the 'unreliable' `Write-Error`.
