### ISSUE TITLE
Need a means to configure the culture settings from within PowerShell on Linux

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#15364]
## Summary of the new feature/enhancement

On my Linux boxes `ls -l` _does_ display date and time formats in my preferred way (`yyyy-MM-dd HH:mm`):

```none
PS❯  ls -l /tmp/foo
-rw-rw-r-- 1 sto sto 4 Aug 12  1995 /tmp/foo
PS❯  ls -l /tmp/foo --full-time
-rw-rw-r-- 1 sto sto 4 1995-08-12 23:59:59.000000000 +0200 /tmp/foo
PS❯  touch /tmp/bar
PS❯  ls -l /tmp/bar
-rw-rw-r-- 1 sto sto 0 May  8 16:44 /tmp/bar

```

whereas PowerShell seems to use the locale-imported settings:

```none
PS❯  locale -k LC_TIME
abday="Sun;Mon;Tue;Wed;Thu;Fri;Sat"
day="Sunday;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday"
abmon="Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec"
mon="January;February;March;April;May;June;July;August;September;October;November;December"
am_pm="AM;PM"
d_t_fmt="%a %d %b %Y %r %Z"
d_fmt="%m/%d/%Y"
t_fmt="%r"
t_fmt_ampm="%I:%M:%S %p"
era=
era_year=""
era_d_fmt=""
alt_digits=
era_d_t_fmt=""
era_t_fmt=""
time-era-num-entries=0
time-era-entries="S"
week-ndays=7
week-1stday=19971130
week-1stweek=1
first_weekday=1
first_workday=2
cal_direction=1
timezone=""
date_fmt="%a %d %b %Y %r %Z"
time-codeset="UTF-8"
alt_mon="January;February;March;April;May;June;July;August;September;October;November;December"
ab_alt_mon="Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec"
PS❯   date
Sat 08 May 2021 04:26:03 PM CEST
PS❯   (Get-Culture).DateTimeFormat

AMDesignator                     : AM
Calendar                         : System.Globalization.GregorianCalendar
DateSeparator                    : /
FirstDayOfWeek                   : Sunday
CalendarWeekRule                 : FirstDay
FullDateTimePattern              : dddd, MMMM d, yyyy h:mm:ss tt
LongDatePattern                  : dddd, MMMM d, yyyy
LongTimePattern                  : h:mm:ss tt
MonthDayPattern                  : MMMM d
PMDesignator                     : PM
RFC1123Pattern                   : ddd, dd MMM yyyy HH':'mm':'ss 'GMT'
ShortDatePattern                 : M/d/yyyy
ShortTimePattern                 : h:mm tt
SortableDateTimePattern          : yyyy'-'MM'-'dd'T'HH':'mm':'ss
TimeSeparator                    : :
UniversalSortableDateTimePattern : yyyy'-'MM'-'dd HH':'mm':'ss'Z'
YearMonthPattern                 : MMMM yyyy
AbbreviatedDayNames              : {Sun, Mon, Tue, Wed…}
ShortestDayNames                 : {S, M, T, W…}
DayNames                         : {Sunday, Monday, Tuesday, Wednesday…}
AbbreviatedMonthNames            : {Jan, Feb, Mar, Apr…}
MonthNames                       : {January, February, March, April…}
IsReadOnly                       : True
NativeCalendarName               : Gregorian Calendar
AbbreviatedMonthGenitiveNames    : {Jan, Feb, Mar, Apr…}
MonthGenitiveNames               : {January, February, March, April…}
PS❯  gi /tmp/foo

        Directory: /tmp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-----         8/12/1995  11:59 PM              4 [  foo
PS❯  gi /tmp/bar

        Directory: /tmp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-----          5/8/2021   4:44 PM              0 [  bar

```

We need a way to define the culture settings within PowerShell, independently from the Linux-level locale settings.

Even something that sets those settings in a volatile way from the profile would be a first step.

This is probably related to https://github.com/PowerShell/PowerShell/issues/3833

**Comment by sba923** [comment]
> My system locale is fully `en_US.utf8`. But in $profile:
> 
> ```
> [Threading.Thread]::CurrentThread.CurrentCulture = 'ru-RU'
> ```
> 
> ```
>  $ (Get-Culture).DateTimeFormat
> 
> AMDesignator                     : AM
> Calendar                         : System.Globalization.GregorianCalendar
> DateSeparator                    : .
> FirstDayOfWeek                   : Monday
> CalendarWeekRule                 : FirstFourDayWeek
> FullDateTimePattern              : dddd, d MMMM yyyy 'г'. HH:mm:ss
> LongDatePattern                  : dddd, d MMMM yyyy 'г'.
> LongTimePattern                  : HH:mm:ss
> MonthDayPattern                  : d MMMM
> PMDesignator                     : PM
> RFC1123Pattern                   : ddd, dd MMM yyyy HH':'mm':'ss 'GMT'
> ShortDatePattern                 : dd.MM.yyyy
> ShortTimePattern                 : HH:mm
> SortableDateTimePattern          : yyyy'-'MM'-'dd'T'HH':'mm':'ss
> TimeSeparator                    : :
> UniversalSortableDateTimePattern : yyyy'-'MM'-'dd HH':'mm':'ss'Z'
> YearMonthPattern                 : MMMM yyyy 'г'.
> AbbreviatedDayNames              : {вс, пн, вт, ср…}
> ShortestDayNames                 : {В, П, В, С…}
> DayNames                         : {воскресенье, понедельник, вторник, среда…}
> AbbreviatedMonthNames            : {янв., февр., март, апр.…}
> MonthNames                       : {январь, февраль, март, апрель…}
> IsReadOnly                       : False
> NativeCalendarName               : григорианский календарь
> AbbreviatedMonthGenitiveNames    : {янв., февр., мар., апр.…}
> MonthGenitiveNames               : {января, февраля, марта, апреля…}
> 
>  $ get-date
> 
> суббота, 8 мая 2021 г. 20:13:10
> ```

That's OK for you because you want to use the predefined settings for an existing culture.

But that's _not_ my case ;-)

**Comment by vexx32** [comment]
WG-Engine had a look at this today.

As far as we know, this is already possible, although PowerShell doesn't expose _specific_ settings for it. Some options:

### Override the current culture instance in .NET

Create a new CultureInfo object (`[cultureinfo]::new('en-us')` - substitute whatever base culture you want to work from) and set its `DateTimeFormat` property members to behave the way you'd like, then assign the resulting object back to `[cultureinfo]::CurrentCulture` -- this would affect most `$datetime.ToString()` usages, and should also affect formatted output containing dates.

### Override the default ToString() method in ETS

```powershell
Update-TypeData -TypeName datetime -MemberType ScriptMethod -MemberName ToString -Value { '{0:yyyy-MM-dd HH:mm}' -f $this }
```

This will be more "powershell specific" in that it won't affect anything in the .NET side of things that is directly calling `ToString()` on DateTime instances, but it should affect pretty much everything in PowerShell.

Both these methods should be relatively straightforward to include in a profile script. Whether PowerShell can expose a more straightforward way to do this is a bit of a larger question, but we aren't sure it warrants something like configuration options natively in PowerShell necessarily.

**Comment by arejay1** [comment]
Please unsubscribe me from powershell as I am an elderly woman and GitHub does not interest me. Regards from Raylee Heading

Sent from Mail for Windows
