### ISSUE TITLE
`ExternalScriptInfo` does not have property for `CmdletBinding` like `CmdletInfo`

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15379]
`ExternalScriptInfo` object should expose the property for `CmdletBinding` like `CmdletInfo` or `FunctionInfo`.

The only was to find if the `ExternalScriptioInfo` object has `CmdletBinding` attribute is to look through the attributes on the `ScriptBlock`.

But in the case of the following example, it is considered that the object has `CmdletBinding` with the explicit attribute.

```Powershell
param(
  [parameter()]
  $Path
)
```

**Comment by daxian-dbw** [comment]
A more concrete example:
```
PS:17> cat .\test.ps1
##[CmdletBinding()]
param(
  [parameter()]
  $Path
)
PS:18>
PS:18> gcm .\test.ps1 -Syntax
.\test.ps1 (alias) -> C:\arena\tmp\playground\test.ps1

.\test.ps1 [[-Path] <Object>] [<CommonParameters>]

PS:19> $c = gcm .\test.ps1
PS:20> $c.ScriptBlock.Attributes
PS:21>
```

**Comment by JamesWTruher** [comment]
your example commented out the CmdletBinding attribute, so I wouldn't expect to see the attribute

here's what I see
```
PS> cat /tmp/test.ps1
[CmdletBinding()]
param (
[Parameter(Mandatory=$true,Position=0)]
$Path
)
END {
    "Path is $Path"
}
PS> $es = gcm /tmp/test.ps1
PS> $es.ScriptBlock.Attributes

PositionalBinding       : True
DefaultParameterSetName : 
SupportsShouldProcess   : False
SupportsPaging          : False
SupportsTransactions    : False
ConfirmImpact           : None
HelpUri                 : 
RemotingCapability      : PowerShell
TypeId                  : System.Management.Automation.CmdletBindingAttribute


PS> $es.ScriptBlock.Ast.ParamBlock.Parameters[0].Attributes

PositionalArguments : {}
NamedArguments      : {Mandatory, Position}
TypeName            : Parameter
Extent              : [Parameter(Mandatory=$true,Position=0)]
Parent              : [Parameter(Mandatory=$true,Position=0)]
                      $Path

```

**Comment by vexx32** [comment]
@JamesWTruher Yeah that's part of the point. A scriptblock is considered to have cmdletbinding if:
- It actually has the [CmdletBinding()] attribute, OR
- It has *any* `[Parameter()]` attributes on any of its parameters.

In other words, it's quite a pain to find the information properly without the proper helper properties that are provided on FunctionInfo and CmdletInfo.

**Comment by JamesWTruher** [comment]
I guess I'm just not seeing the pain

`$es.ScriptBlock.Attributes` vs `$es.Attributes` ???

**Comment by adityapatwardhan** [comment]
While trying to look for `CmdletBinding` in an `ExternalScriptInfo` for platyPS, it proved to be a challenge. For checking if the `CmdletBinding` attribute exists, I have to iterate over the attributes to find if a `CmdletBindingAttribute` is found. This can be an expensive operation as compared to looking up a property on the `ExternalScriptInfo` object. 

For platyPS scenarios, there can be multiple ExternalScriptInfo object that have to be processed and iterating over the attributes for each of them will degrade performance.

Moreover, if there is no `CmdletBindingAttribute` but a `ParameterAttribute`, we must assume it has `CmdletBinding`. I would consider this as tribal knowledge. Having an explicit property on ExternalScriptInfo makes it clear.
