### ISSUE TITLE
Distribution Support Request for openSUSE Leap 15

### ISSUE THREAD

**Issue by phillipsj** [PowerShell/PowerShell#15376]
## Details of the Distribution

There is already a .NET repository for openSUSE Leap 15 that works well and supports Tumbleweed too. It would be nice to get a PowerShell repo for it too.

- Name of the Distribution: openSUSE
- Version of the Distribution: Leap 15.x 
- Package Types
    - [ ] Deb
    - [x] RPM
    - [ ] Tar.gz
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request):
- The following is a requirement for supporting a distribution **without exception.**
    - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [ ] An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by rjmholt** [comment]
Adding this distribution request for PS committee review.

**Comment by JamesWTruher** [comment]
https://github.com/orgs/PowerShell/teams/powershell-committee has reviewed this request, and our current position is that adding any new release to our current list of supported platforms would be cost prohibitive.
