### ISSUE TITLE
How to protect my business script?

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#15386]
I have a business script a.ps1. I want to compile and embed a.ps1 in a binary program. 
In the binary program, execute pwsh -f a.ps1, which needs to be used across platforms.
powershell v7 has been installed on this machine.

I heard that .net core5 has "single file deployment" and "NativeAOT". What is the difference between the two? 
Which solution is suitable for my scenario?

Don't want more people to see it? Can also tell me secretly

In my business project,Only a few core scripts need to do this.

**Comment by 237dmitry** [comment]
Encrypt with password and run with password? Such a self-decrypted script with entered password (`Read-Host`). For example:
```powershell
$ErrorActionPreference = 'SilentlyContinue'
 
$code = '76492d1116743f0423413b16050a5345MgB8ADIAYQBZAHcASQA1AHkAMQBGADIAagBSAFUAcwBRAGYAYwB0ADYAVwBRAEEAPQA9AHwAMwBmADQAMwAyAGEANQA3ADUANQAwADYAYQBiADYAMwA2ADcANAA2ADcANQBmADIAZgBhADgANAA1ADEAYQBiADEAZgA5ADgAZAA0ADEAOAA0AGIAMQAyADYANgAxADkANgA2ADEAYQAyADkAZgBlADgAYgA1AGMAOAA4ADkAYQA0ADAAMQAzAGUAZQA5ADQAMgA5AGUAOQBhADEANwAwADEAZgA0ADEAMQBlADEAMAA3ADIAZQBhADAAYwBhADEANgAyADYAOQBkAGMANwA4ADEAMQA2ADAANQBjAGYAZABmAGQAMQBiAGMAOAA3ADYAMAAwADUAMABmADcAZQAzADMAMwAzADcAYQBmAGMANAA4ADMAYgBlADMAYQA0ADgAMQBiAGYAYgBkAGUAMwA0ADkAZABmADUAMwAwAGUAZAA5AGMANQBjAGYAZABjADEAOQBmADAAMAA4ADUANABlADIAOAAwADEAMAA4ADMAZgBmADYAMwBkAGQAMwBiAGUANAAwAGEAZQA0ADMAOQBlAGIAMQBkAGQANgA5ADAANAA0AGIAMAAwAGYAZgA5AGMANwA3ADUAMgBkADcAYQAzAGQAYgA4AGQAOAA5ADkAZQBmAGEAYgBlAGUAOAA4ADAAZABkAGEANQAwADMAZgAwAGUANwAzADEAYgBlADIAYQAxAGUANgA5ADIANAA0ADcANgA4ADQANgA1ADYAYwAzAGIAOQA5ADgAMwBjAGMAMgBjADMAYgAzADYANwBmADUA'
 
# password as plain text
# $key = ConvertTo-SecureString -String 'aaaa' -AsPlainText 

$key = Read-Host "Enter Password" -AsSecureString
 
$pass  = [byte[]][char[]][Net.NetworkCredential]::New($null,$key).Password
$pass += [byte[]] (0..(31 - $pass.count))
 
Invoke-Expression $(ConvertTo-SecureString $code -Key $pass |
                    ConvertFrom-SecureString -AsPlainText)
```

**Comment by jborean93** [comment]
There’s no way to do this. If you need to be able to run a script the same user needs to be able to decode it somehow for PowerShell to run. You can add more layers to obfuscate the code but thats just delaying the inevitable.

**Comment by 237dmitry** [comment]
> the same user needs to be able to decode it

I am using encrypted scripts like this on different computers and in different OS. No need to be "the same user" just enter password.

For Windows PowerShell compatibility:
```powershell
$ErrorActionPreference = 'SilentlyContinue'
 
$code = '76492d1116743f0423413b16050a5345MgB8ADIAYQBZAHcASQA1AHkAMQBGADIAagBSAFUAcwBRAGYAYwB0ADYAVwBRAEEAPQA9AHwAMwBmADQAMwAyAGEANQA3ADUANQAwADYAYQBiADYAMwA2ADcANAA2ADcANQBmADIAZgBhADgANAA1ADEAYQBiADEAZgA5ADgAZAA0ADEAOAA0AGIAMQAyADYANgAxADkANgA2ADEAYQAyADkAZgBlADgAYgA1AGMAOAA4ADkAYQA0ADAAMQAzAGUAZQA5ADQAMgA5AGUAOQBhADEANwAwADEAZgA0ADEAMQBlADEAMAA3ADIAZQBhADAAYwBhADEANgAyADYAOQBkAGMANwA4ADEAMQA2ADAANQBjAGYAZABmAGQAMQBiAGMAOAA3ADYAMAAwADUAMABmADcAZQAzADMAMwAzADcAYQBmAGMANAA4ADMAYgBlADMAYQA0ADgAMQBiAGYAYgBkAGUAMwA0ADkAZABmADUAMwAwAGUAZAA5AGMANQBjAGYAZABjADEAOQBmADAAMAA4ADUANABlADIAOAAwADEAMAA4ADMAZgBmADYAMwBkAGQAMwBiAGUANAAwAGEAZQA0ADMAOQBlAGIAMQBkAGQANgA5ADAANAA0AGIAMAAwAGYAZgA5AGMANwA3ADUAMgBkADcAYQAzAGQAYgA4AGQAOAA5ADkAZQBmAGEAYgBlAGUAOAA4ADAAZABkAGEANQAwADMAZgAwAGUANwAzADEAYgBlADIAYQAxAGUANgA5ADIANAA0ADcANgA4ADQANgA1ADYAYwAzAGIAOQA5ADgAMwBjAGMAMgBjADMAYgAzADYANwBmADUA'
 
# password as plain text
# $key = ConvertTo-SecureString -String 'aaaa' -AsPlainText 

$key = Read-Host "Enter Password" -AsSecureString
 
$pass  = [byte[]][char[]][Net.NetworkCredential]::New($null,$key).Password
$pass += [byte[]] (0..(31 - $pass.count))
 
$code = ConvertTo-SecureString $code -Key $pass

switch ($PSEdition)
{
    'Core'    { Invoke-Expression $(ConvertFrom-SecureString -SecureString $code -AsPlainText) }
    'Desktop' { Invoke-Expression $([Net.NetworkCredential]::New($null,$code).Password) }
}
```

**Comment by jborean93** [comment]
My point is for a user to invoke a script they need to be able to decode/decrypt it from the obfuscated state. Without being able to do that they cannot run the script. Whether it's encrypted with a password or encrypted to some user context secret the end result is the same. PowerShell even has builtin logging to log any scriptblock that is invoked making it even easier to determine what was actually run and get in plaintext.

**Comment by 237dmitry** [comment]
> to invoke a script they need to be able to decode/decrypt it from the obfuscated state.

I did not understand why user who knows password can not run the script?:
```
> .\script
Enter password: ****
# Get-Date output
# $Env:UserName or $Env:USER
```
> PowerShell even has builtin logging to log any scriptblock that is invoked making it even easier to determine what was actually run and get in plaintext.

There logs are? Is this `about_Logging` help?

**Comment by doctordns** [comment]
@237dmitry - there are numerous logs for Powershell, depending on whether you mean windows PowerShell or PowerShell 7 (aka core).  To discover them, you can use Get-WinEvent, like this:

```Console
PS C:\Foo> get-winevent -ListLog *powershell*

LogMode   MaximumSizeInBytes RecordCount LogName
-------   ------------------ ----------- -------
Circular            15728640        2603 Windows PowerShell
Circular            15728640        2469 PowerShellCore/Operational
Circular            15728640        1652 Microsoft-Windows-PowerShell/Operational
Retain            1048985600           0 Microsoft-Windows-PowerShell/Admin
Circular             1052672           0 Microsoft-Windows-PowerShell-DesiredStateConfiguration-FileDownloadManager/Op…
```
You can view the events in Powershell, or event viewer.

**Comment by 237dmitry** [comment]
> there are numerous logs for Powershell

Among these logs, I did not find any script blocks.

**Comment by doctordns** [comment]
Script block logging is a bit of a resource hog so is disabled by default. 

See the [about_logging help page](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_logging_windows?view=powershell-7.1) and look for enabling script block logging.

**Comment by 237dmitry** [comment]
> Script block logging is a bit of a resource hog so is disabled by default.
>> disabled

That's why I asked
> Is this about_Logging help?

PS. (Not personally) I offered -- you answered. The more offers the better.

**Comment by daxian-dbw** [comment]
> I heard that .net core5 has "single file deployment" and "NativeAOT". What is the difference between the two?

Neither of those two is for your scenario. If you want, you can embed your script as a resource stream in your .NET application, and at runtime, you can read the text from the resource stream and run `pwsh -command <script-text>`.

**Comment by kasini3000** [comment]
I know this may involve hackers, so it is necessary to briefly talk about my project.
This is one of the most outstanding powershell projects. The name is [k4t]. It is similar to k8s and has not been released yet. The core code does not want to be open source.

The ps1 script on the master side runs on win and linux platforms. The script on the node side runs on the linux platform. It is used by customers and cannot be encrypted by password. I just want to protect the source code.

@daxian-dbw  Thank you for your reply. Do me still need to install .net core to run this binary?
If it is, I cannot adopt this scheme. If not, can you tell me more or give me a few blog posts?

In fact, I considered using golang, compiling and embedding, to protect the ps1 source code. 
Before that, I want to pin my last hope on this help post.
