### ISSUE TITLE
Remove unimplemented parameters from Set-AuthenticodeSignature

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#15392]
## Summary of the new feature/enhancement

`Set-AuthenticodeSignature` and `Get-AuthenticodeSignature` are both derived from the base class `SignatureCommandsBase`. The parameters are defined in the base class but implemented in the cmdlet class. `Get-AuthenticodeSignature` implements the **SourcePathOrExtension** and **Content** parameters, but `Set-AuthenticodeSignature` does not.

The problem is that `Get-Command` shows that parameters even though they are not implemented, causing confusion to the users and in the documentation.

## Proposed technical implementation details (optional)

We have update the docs to explain that the parameters are not implemented. 

The code should be changed. The parameters should be moved out of the base class and into the cmdlet class `GetAuthenticodeSignatureCommand`. That way, the parameters only apply to that cmdlet.

See related Docs issue https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7564.

**Comment by BrucePay** [comment]
A breaking change.

**Comment by sdwheeler** [comment]
@BrucePay  It is a breaking change in that the parameter will not appear for `Set-AuthenticodeSignature` but since they are not implemented for that cmdlet there is no impact. Unless I am missing your point. Can you elaborate?

**Comment by BrucePay** [comment]
@sdwheeler Even if a parameter does nothing, removing a parameter from a cmdlet is a breaking change.

**Comment by MartinGC94** [comment]
How far should Powershell go to maintain backwards compatibility though? I can't imagine any actual scenario where you would use an unimplemented parameter (that apparently throws an error if used).

**Comment by sdwheeler** [comment]
I agree that it would be a breaking change. But I think it falls into the category of minimal risk and impact, since it was never implemented. We take changes like that all the time. Ultimately, it's the committee's decision.

**Comment by vexx32** [comment]
The only real concern I can see with this is not really so much the removal of parameters that throw anyway (great, they'll just throw generic parameter binding errors instead, not really a big deal), but moreso that modifying the parent class may break some other code that isn't owned or controlled by PowerShell.

The `SignatureCommandsBase` class is a public API itself, so changes to that may impact folks inheriting from it. I've not taken a close look to see what the real impact would be if those properties were removed, but it's possible that it may be of a little more concern than simply removing non-functioning parameters from the affected command.

I would generally agree that this suggested change is a good idea, though. I suspect the likelihood of breaking something else is fairly minimal, but it might be worth taking a closer look before making a final decision. 🙂

**Comment by jdhitsolutions** [comment]
I would say that if this is well documented and a user can learn this from running `Get-Help` that we leave this alone. A potentially confused user is not enough to warrant making these types of changes, especially when nobody can definitively say what the result might be. I'd say that's why this type of change is considered breaking.
