### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by FDFessler** [PowerShell/PowerShell#15399]
Test-Connection gives very different results between PS 5 and PS 7

## Steps to reproduce

```powershell v5
$TC_PS5 = Test-Connection {computername}
$TC_PS5 | Get-Member
   or
$TC_PS5 | Format-List *
``` pwsh v7
$TC_PSCore7 = Test-Connection {computername}
$TC_PSCore7 | Get-Member
   or
$TC_PSCore7 | Format-List *

## Expected behavior
I would expect to see the same results/values or at least everything that is in v5 in v7.

## Actual behavior
Vastly different results/values!  See attached docs.

## Environment data
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042

<!-- provide the output of $PSVersionTable -->
```PS 5 = 5.1.19041.906
```PS 7 = 7.1.3

[TC_PS5.txt](https://github.com/PowerShell/PowerShell/files/6473160/TC_PS5.txt)
[TC_PSCore7.txt](https://github.com/PowerShell/PowerShell/files/6473162/TC_PSCore7.txt)
[TC_PS5_Members.txt](https://github.com/PowerShell/PowerShell/files/6473163/TC_PS5_Members.txt)
[TC_PSCore7_Members.txt](https://github.com/PowerShell/PowerShell/files/6473164/TC_PSCore7_Members.txt)

**Comment by vexx32** [comment]
The cmdlet in Windows PowerShell uses Windows API functionality to do its thing. This fundamentally isn't cross-platform, so the cmdlet had to be rewritten. There wasn't really a way around it.

If there are specific features you feel are missing from the new version, it would be better to request those specifically, so that we can properly assess whether reintroducing any missing features is feasible with the cross-platform .NET API.

**Comment by FDFessler** [comment]
I see, that makes a lot of sense.  I have only been using ResponseTimeToLive (TTL ) and StatusCode from PS 5.  TTL would probably be the only one that would be helpful to me as that helps me determine if I am talking to a Windows machine or Linux machine.
**I see that is available in .Reply.Options.Ttl so I guess I have everything I need!!**

I try to code to both versions (non-core and core) so when the names are "different" it's just more code and a **surprise** when it doesn't work in the "other" version.

I am all set as far as this is concerned.  Thank You for your RAPID response.  You can close this out.  :-)
