### ISSUE TITLE
Powershell variable can't be passed to script switch parameter?

### ISSUE THREAD

**Issue by rtestardi** [PowerShell/PowerShell#15395]
Hopefully someone can just explain this -- I want to fill in a variable with "-switch" or "" and pass it to a script, but that does not seem to work...

The script:

```
param(
    [switch]$switch1 = $false,
    [switch]$switch2 = $false,
    [switch]$recurse = $false
)

function func()
{
    "try 1"
    $arg="-switch1"
    & $MyInvocation.PSCommandPath $arg -recurse

    "try 2"
    & $MyInvocation.PSCommandPath -switch1 -recurse
}

if ($recurse) {
    "switch1 = $switch1"
    "switch2 = $switch2"
    "args = $args"
} else {
    func
}
```

Why cannot $arg be passed to a child as a switch?

I expected try 1 and try 2 to be the same?

```
PS C:\temp\dbe\src\services\datavalidation\tests\ust> powershell .\param.ps1

try 1
switch1 = False
switch2 = False
args = -switch1

try 2
switch1 = True
switch2 = False
args =
```

Note in the first case, "-switch1" ends up in $args, which I assume is because it was unprocessed by param()?

Thanks for any explanation!

**Comment by rtestardi** [comment]
PS If I do:

    "try 3"
    & $MyInvocation.PSCommandPath "-switch1" -recurse

I get the same answer I don't like. :-)

I'm hoping for a way to programmatically pass switches or not.

**Comment by vexx32** [comment]
There are two ways. Key thing to remember is passing switch values like this generally just means passing the value as a boolean -- almost.

```powershell
$switchValue = $true # or false, if you want to explicitly "not" pass the switch
& $MyInvocation.PSCommandPath -switch1:$switchValue -recurse
```

If `$switchValue` is true, the switch is registered as passed. If it's false, it's registered as omitted. The `:` here to join the switch to its value is necessary; otherwise, PS would assume the value belongs to a positional parameter (since switches normally don't take explicit values).

```powershell
$params = @{
    switch1 = $true # or false, if "omitting" the switch
}
# The -Recurse switch here could also be placed in $params if you preferred
& $MyInvocation.PSCommandPath @params -Recurse
```

**Comment by rtestardi** [comment]
Cool, thanks so much!
