### ISSUE TITLE
Displaying SwitchParameter causes subsequent output to fail...

### ISSUE THREAD

**Issue by rtestardi** [PowerShell/PowerShell#15390]
Put this in a file like testme.ps1:

```
param(
  [switch]$skip = $false,
  [switch]$weird = $false
)

if (! $skip) {
    $weird  # skip this line and it works!
}

$hash2=@{}

$hash2["aaa"]=1

"hash value is"

$hash2

```

Without the -skip parameter, nothing gets printed for the hash value...

```
PS C:\temp> powershell .\testme.ps1

IsPresent
---------
    False
hash value is

PS C:\temp> powershell .\testme.ps1 -skip
hash value is

Name                           Value
----                           -----
aaa                            1

PS C:\temp>
```

I would have expected the hash value output to be the same in both cases?

I see the same behavior on Core 7.1.3 and Desktop 5.1.19041.906.

Is there a workaround?

Thanks.

**Comment by vexx32** [comment]
This is rather an odd case. 🤔 

In general I tend to recommend against having more than one type of object be output from a single function; there are some known issues with the formatter that look a bit like this. But it is only a formatting problem; the data is still output.

If you do `$data = & ./testme.ps1` then $data will still have all three values in it.

**Comment by rtestardi** [comment]
> I tend to recommend against having more than one type of object be output from a single function

I think I agree -- but when you get errors and such and/or start trying to instrument code to see what is going on, that becomes pretty hard to ensure.

The bottom line is output just gets randomly swallowed up sometimes -- that seems a usability issue.

The strange thing is if I output an object before the switchparameter like "@{bbb=1}", then the $hash output shows up again...

It just seems so fragile. :-(

**Comment by 237dmitry** [comment]
It works with this syntax:
```
param(
  [switch]$skip  = $false,
  [switch]$weird = $false
)

if ($PSBoundParameters.keys -notcontains 'skip')
{
    # $weird  # skip this line and it works!
    'not $skip'
}

$hash2=@{}
$hash2["aaa"]=1

"hash value is"
$hash2

$PSBoundParameters
```

**Comment by vexx32** [comment]
Yeah, something with the SwitchParameter being sent to the formatter directly (and not as part of a string) is confusing it, looks like.

**Comment by jhoneill** [comment]
> > I tend to recommend against having more than one type of object be output from a single function
> 
> I think I agree -- but when you get errors and such and/or start trying to instrument code to see what is going on, that becomes pretty hard to ensure.
>
It is at this point `write-verbose` and `write-debug` become your friends  
```
[cmdletbinding()]
param(
  [switch]$skip ,
  [switch]$weird 
)
if (! $skip) {
    Write-Verbose     $weird  
}
$hash2=@{}
$hash2["aaa"]=1
"hash value is"
$hash2
}
```

As @vexx32  said 

> [it]   is still output. If you do `$data = & ./testme.ps1` then $data will still have all three values in it.

Unless you use verbose/debug/host the _instrumentation_ gets mixed up with the _output_ and you need need to keep enabling and disabling it. 

(the behavior after outputting a switch is still broken, but that's another issue)

**Comment by vexx32** [comment]
Yeah, I'd echo @jhoneill's point and say if you need informational / debugging messages, use of `Write-Verbose` / `Write-Debug` and/or `Write-Host` depending on your exact needs is what you really want; those all avoid putting the data in the output stream and causing issues like this.

For errors I'd use `throw` or `Write-Error`, or (specifically in a function with [cmdletbinding()]) you can also use `$PSCmdlet.ThrowTerminatingError()` or `$PSCmdlet.WriteError()`.

That is a bit tangential; this behaviour is still broken, but hopefully using those you should be able to work around it for the current problem you have. 🙂
