### ISSUE TITLE
using regular command 

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/PowerShell#15398]
Hi Guys !!

there are many regular command : executable file we can run with PS but sometimes we  have conflict between executable file and PS command.

the idea is to use a symbol ex "^" before the regular command if we want use executable file for example:

```
UNIX PS> foo
function foo
UNIX PS> rm function:foo
UNIX PS> ^rm function:foo 
# ERROR 
```

**Comment by jborean93** [comment]
I feel like this just adds more work for little gain, the best thing to do is to not create a function that shadows a native command. This is usually not a problem if you follow the `Verb-Noun` syntax that is encouraged in PowerShell. If you do have a shadow then you need to explicitly invoke the command like `&(Get-Command foo -CommandType Application)`.

**Comment by p0W3RH311** [comment]
@jborean93 

thanks,  there are many powerfull external command in nix and also in  windows and sometimes its used by the users...i know it exist crescendo module but its not the  same concept  used by the regular users. with this syntax:`

PS> ^command ....etc`

its more explicit.  if the user postfix any command with "^" then the regular command its used and not any function/cmdlet/alias/configuration/filter is used

**Comment by vexx32** [comment]
I don't really see much additional value being added here that isn't possible to do in most cases by simply affixing the file extension to the command name (e.g., `cmd.exe` vs `cmd`). Saving two characters doesn't really make it seem worthwhile to me.
