### ISSUE TITLE
Feature Request: install-powershell.ps1: Being able to install latest servicing/LTS release and not just Current

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#15403]
## Summary of the new feature/enhancement

[install-powershell.ps1](https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1) offers the option of installing Current, preview or daily but not LTS. This would e.g. be useful to test the LTS version as well in CI as hosted agents like LTS are usually on the Current version.

## Proposed technical implementation details (optional)

The [metadata.json](https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json) file is already used to determine the right version and already has the version of the last servicing/LTS release. The script is not elegant as it already has a switch for preview and daily, therefore adding a `LTS` switch would at least keep it consistent as we'd likely not want to break existing syntax.

**Comment by adityapatwardhan** [comment]
Maintainers reviewed the issue and we think it is a good idea. Eventually we will be having more that one LTS releases so there would be some need to specify which version needs to be installed.

**Comment by bergmeister** [comment]
So are you saying that an -LTS switch would not be acceptable? To me it sounds like the current and lts switches should just install the latest lts or current 'flavour'. Anything that is not latest current or latest lts, a version switch could be offered instead where people can pin major and minor version?

**Comment by kilasuit** [comment]
Hey @bergmeister  I have been working on this as part of #19883 as hadn't seen this request whilst I was looking through the issues sorry. The PR for it is #19884 so hopefully should be merged soon :-)

**Comment by kilasuit** [comment]
This is still `In-PR`

@bergmeister until that PR is merged you can make use of the version of it from my fork as per the code samples in this blog post of mine [Installing PowerShell Side by Side for testing purposes](https://blog.kilasuit.org/2023/09/09/installing-powershell-side-by-side-for-testing-purposes/) to install specific versions too, though I'm gonna spend a little more time on this to give it more durability than it has right now as this hasn't yet been merged.
