### ISSUE TITLE
The `minimal` progress view doesn't handle window resizing

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#15407]
The `Minimal` progress view doesn't handle console window resizing

## Steps to reproduce

```powershell
1..100 | % { Write-Progress -Activity "123456789012345678901234567890123456789012345678901234567890" -Status "S" -PercentComplete $_ -SecondsRemaining $_ ; Sleep 1}
```
While running this command, try resizing the console window.

## Expected behavior

Progress rendering should be able to handle the resizing in a reasonable way.
The `Classic` view handles resizing a little better, though not perfect.

## Actual behavior

It doesn't handle the resizing properly.

![image](https://user-images.githubusercontent.com/127450/118309379-08300b00-b4a2-11eb-870f-816d58f06f4c.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This was improved, but there are limits to what can be done.  When the terminal is resized, the progress is recalculated and drawn, but the position won't be perfect as drawing and clearing is not atomic so if the terminal is resized between such operations then the progress renderer has no way of knowing.
