### ISSUE TITLE
Why does console size affects powershell redirection

### ISSUE THREAD

**Issue by rtestardi** [PowerShell/PowerShell#15404]
Start with a narrow (50 characters) console window and run:

```
PS C:\temp> ps >ps.txt
PS C:\temp> (gc .\ps.txt | %{ $_.length } | measure-object -max).maximum
49
PS C:\temp>
```

Then make your console window full screen and run it again:

```
PS C:\temp> ps >ps.txt
PS C:\temp> (gc .\ps.txt | %{ $_.length } | measure-object -max).maximum
157
PS C:\temp>
```

Why does the console size affect output written to (redirected to) a file?

Is there a way to not see this behavior?  I'd like my scripts to generate the same file data regardless of the size of the console they happen to be invoked in.

In Linux/bash, you can only query the window dimensions thru a tty handle, and when you redirect an operation to a file handle, that query fails, so all console/window processing (even pagers) get disabled...  But with powershell, it seems file redirection still leaves the underlying operation inherently knowing (and using!) the console handle (that is not even involved in the write!).

Thanks for any explanation!

PS You can see the same behavior with write-information "..." 6>file, but not with write-output "..." >file -- I am not sure why...

**Comment by 237dmitry** [comment]
Out-String with Width parameter
```
Get-Process | Format-Table * | Out-String -Width 1000 | Set-Content gps.txt
```

**Comment by rtestardi** [comment]
That still doesn't answer my question -- *why* would (should) the console width affect files my script generates?  There are lots of cases where this happens and it seems fundamentally wrong -- shouldn't the console width *only* be used for output actually going to the console, not output redirected to files?

In my case the issue is more complicated than adding an out-string -width -- I'm using information stream file redirection to allow a script to both have console output the user can see (which I'm fine being clipped) as well as writing *all unclipped data* to a log file...  But my log file ends up with line breaks every time a line is wider than the console width, which of course, makes the log file impossible to grep/parse.

This seems like a trivially simple example that should always work:

ps >ps.txt

But it doesn't -- can we fix it?  Thanks!

**Comment by rtestardi** [comment]
PS any idea how I would fix this in a 50 character console?  I don't see where to put the out-string or other command.

PS C:\temp> write-information ("*"*200) 6>info.log
PS C:\temp> (gc .\info.log | %{ $_.length } | measure-object -max).maximum
49
PS C:\temp>

**Comment by rtestardi** [comment]
PPS interesting -- write-output behaves differently than write-error, write-warning, and write-information (which all clip strings to the console width):

```
PS C:\temp> write-output ("*"*200) >output.log
PS C:\temp> (gc .\output.log | %{ $_.length } | measure-object -max).maximum
200

PS C:\temp> write-error ("*"*200) 2>error.log
PS C:\temp> (gc .\error.log | %{ $_.length } | measure-object -max).maximum
49

PS C:\temp> write-warning ("*"*200) 3>warning.log
PS C:\temp> (gc .\warning.log | %{ $_.length } | measure-object -max).maximum
49

PS C:\temp>
```

**Comment by vexx32** [comment]
You're redirecting output that normally comes to the console. That output is going to be formatted for the current console width for display. If you want to serialise data instead, you need to indicate what format you want to use. You could convert it to JSON, CSV, or CLIXML as you please, but the default redirection behaviour doesn't have a set serialization format, it just redirects whatever the console output would be.

**Comment by rtestardi** [comment]
Understood -- I'm questioning if that's a valid model when compared to Linux/bash, which says that once output is redirected to a file, it no longer has console artifacts...  I think folks use powershell *both* to talk to the console *and* to talk to files and other objects -- but they seem inseparable from the console now.

Any idea why the information stream behaves differently than the output stream in the example above?  It almost seems like "write-output" was fixed, and "write-error", "write-warning", and "write-information" got missed?

I'd expect them *all* to be "formatted for the current console" from what you indicate?  (Or *none* of them, if I had my way! :-)

**Comment by vexx32** [comment]
Write-Output doesn't demand a specific format, it's designed to handle any kind of object. Submitting a string to it and then writing it to a file is the exact same operation (albeit effectively doing a little bit of work twice) as just saving that string directly to the file. In other words, these two statements are equivalent:

```powershell
"*"*200 > file.txt
Write-Output ("*"*200) > file.txt
```

No formatting really happens here because you only have a simple string, there's no complex object to format.

However, non-output streams are strongly typed -- they enforce a specific object type which all other output sent to them must be converted to. For `Write-Warning`, this is `WarningRecord`, much as for `Write-Error` it's `ErrorRecord`, and similar for all the others. 

When saving this to a file, they're not simple strings or values, and get run through the formatter to determine the appropriate string representation. So, much like other examples that have been mentioned, the exact representation can depend on the console size at the time.

Whether that's the "correct" model or not is a bit of a debate topic, I suppose, but it's how it has been designed up to this point. This has been the case since sometime around PSv3 when most of the alternate streams were introduced (Information stream was a bit later, being introduced in PS 5.1).

**Comment by rtestardi** [comment]
Thanks for the explanation -- might there be a way to get something like this not to clip?  I'm using stream 6 as a detailed log file -- that might have more information (i.e., many more lines) than are sent to the console, though typically a pure superset of that -- that seems to be in line with the intended usage of stream 6 [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_output_streams?view=powershell-7.1).

```
PS C:\temp> write-information ("*"*200) 6>info.log
PS C:\temp> (gc .\info.log | %{ $_.length } | measure-object -max).maximum
49
PS C:\temp>
```

But I can't seem to figure it out...

IIUC, write-information generates -- and stream 6 only accepts -- [InformationRecord] objects.  The "6>info.log" above has to convert these objects to strings, and **always** uses the console width to do so.  Is that accurate?

I can definitely hack the console width with the following, but if I don't have to, I'd rather not:

`$Host.UI.RawUI.BufferSize = New-Object Management.Automation.Host.Size (1000, $Host.UI.RawUI.BufferSize.height)
`

Thanks again.

**Comment by vexx32** [comment]
If you intend the result to go purely to a file and never the console, I probably wouldn't really bother involving stream 6; you can redirect or otherwise write strings to files without it.

If for whatever reason you need to use the information stream to output text data, it'd probably be a better idea to just take the `MessageData` property off of the object when saving to a file, or if you need the other data that InformationRecords contain, you could convert it to CSV perhaps.

```powershell
(Write-Information ("*"*200) 6>&1).MessageData | Set-Content -Path info.log

# or perhaps
Write-Information ("*"*200) 6>&1 | Export-Csv -Path info.log
```

**Comment by rtestardi** [comment]
Thanks.  My particular issue is I have a bunch of concurrent background jobs and I want to synchronize their output thru the stream to a single log file...

So my main script starts with just re-invoking itself recursively (BTW, I'd love to have a bash-like "exec 6>runust.log" to skip the reinvocation and just redirect the stream in the main script live, but the reinvocation is easy enough!):

```
if (! $redirected) {
    & $PSCommandPath -include $include -exclude $exclude -failure $failure -list:$list -redirected $hash 6>runust.log
    exit 0
}
```

And then all my jobs launched by the sub-script can use write-output (to just go to the console), write-information (to just go to the log file), or both (to go to both :-).

(The main script is careful to do timely receive-jobs for all jobs as they run.)

Maybe there's a much better way to do this, but other than the line breaks in the log file, it is really simple and works really well...

Anyway, thanks again for all the explanations and thoughts/recommendations -- it really is amazing how responsive (all) you folks are for powershell issues (or enhancements :-).

**Comment by JamesWTruher** [comment]
Since `>` is a wrapper for out-file, you can achieve something close to what you want directly with `out-file`. It's not quite the same but it may be something you can do. Also, you can use `$PSDefaultParameterValues['out-file:width'] = 200` to increase the default output width. Then this would work as you expect
```powershell
.{ "#" * 200; write-error ("*"*200);write-verbose -verbose ("@"*200) } > /tmp/output 2>/tmp/errout 4>/tmp/verbout
```
each redirected file should use the width as designated

**Comment by rkeithhill** [comment]
> $PSDefaultParameterValues['out-file:width'] = 200

That's a nice way to handle this.  This is something that I have struggled with RE logging over the years.  I created my own set of `Write-Log` functions (alias Log) that would use `Out-String -Width` to control the "width of output" in the log file.  I wonder if the $PSDefaultParameterValues idea could be made a bit more discoverable?  Maybe via a help topic on `logging output to file`?

**Comment by rtestardi** [comment]
Wow, that is totally nice thank you -- this makes everything good for me, without resizing my window!!!

`$PSDefaultParameterValues['out-file:width'] = 1000`

Thank you again!

**Comment by vexx32** [comment]
> Wow, that is totally nice thank you -- this makes everything good for me, without resizing my window!!!
> 
> `$PSDefaultParameterValues['out-file:width'] = 1000`
> 
> Thank you again!
> 
> PS is there a list of default parameter values documented anywhere? How did you find this?

Basically it can be used to set _and_ cmdlet/function's default parameter values for the session. The syntax is `$PSDefaultParameterValues['Cmdlet-Name:ParameterName'] = $value` -- and note that you can use wildcards for cmdlet or parameter names, so for example you could enable -Force by default for all *Item commands (get-item, get-childitem, etc) with: `$PSDefaultParameterValues['-*Item:Force'] = $true`

**Comment by vexx32** [comment]
Opened #15474 to track the future enhancement. 🙂

**Comment by daxian-dbw** [comment]
As is called out in https://github.com/PowerShell/PowerShell/issues/15404#issuecomment-849674486, we should make this workaround more discoverable by updating the powershell help docs.
@rkeithhill has volunteered to open issues regarding this in the PowerShell-Doc repo, thanks @rkeithhill!
