### ISSUE TITLE
Feature Request: Support passing command line args with -Command option.

### ISSUE THREAD

**Issue by erinlah-ms** [PowerShell/PowerShell#15417]
## Summary of the new feature/enhancement

Requesting support for passing arguments via command line to be passed to the command the user is requesting to be executed. Compare with python:

```
python.exe -c "import sys; print(sys.argv[1])" "It's `your`, not `you're`"
```

**NOTE:** this request is not about invoking PowerShell from within PowerShell as a cmdlet. I'm aware that there's special processing there that translates -Command / -Args to the command line parameters -encodedCommand and -encodedArguments. This is specifically regarding creating a process where the native command line arguments passed to the process include -Command and -Args -- e.g. invoking PowerShell form some other shell, such as bash or cmd.

## Proposed technical implementation details (optional)

Propose extending `-Command` to support `-Args` when passed as command line arguments to the PowerShell host. This would apply any time that:
1. The argument immediately following -Command starts with '{' and ends with '}', once whitespace has been trimmed.
2. The 2nd argument after -Command is the argument -Args (ordinal case insensitive)
3. -Args is followed by zero or more additional command line arguments.

When this occurs, the $Args value will be bound with an array of the remaining command line arguments following the -Args argument. 

Backwards compat risk: estimated to be small, but non-zero. When attempting to use -Command with the first argument being a script block scring, I found no way to pass -Args afterward and result in a correcltly parsing powershell command, let alone a useful one. I suspect it can be done, but is unlikely to be practical. If nothing else, the change is definitely smaller in impact than the breaking changes to Set-Content between pwhs 5.1 and 6.0. 

Note: proposing no change to -Command or -Args parsing when invoking the Powershell function/commandlet from within powershell. That behavior will remain unchanged -- namely, when invoking PowerShell from within Powershell, the -Command and -Args arguments are replaced with -encodedCommand and -encodedArguments before the process is launched. This already has full fidelity today.

## Rationale

Note that this greatly simplifies string escaping. Being able to pass arguments after the command allows the user to only have to deal with one level of string escaping -- the current shell they're interacting with. 

In contrast, schemes like `powershell.exe -Command "{ param($a) echo $a }" -A 'my example'`, the argument `my example` gets parsed twice -- first in your current shell (e.g. PowerShell, Bash, or Windows Command Shell), and then again by the powershell parser when parsing it as part of the `-Command` argument. This makes it prohibitively difficult to forward arguments between scripts, or invoke PowerShell via exec/CreateProcess from another program.

For example, passing the string "It's \`your\`, not \`you're\`" PowerShell through another script is exceedingly difficult, e.g. if embedded in the -Command argument. For instance, if you don't quote the string, PowerShell will treat the whitespace as argument separators. Also, PowerShell will parse the "\`" characters as escapes, and the "'" characters as unescaped string literals. This is on top of the unescaping the outer shell has already performed on the user input -- e.g. in bash, the user probably wrapped the above in single or double quotes in order to be able to include spaces in the argument.

As discussed in issue https://github.com/PowerShell/PowerShell/issues/15410, Powershell only support passing arguments to a -command when invoked as a function from within powershell, not when invoked externally.

## Examples in other script environments:

- Python (invoked from cmd)
    > $ c:\bin\Python26\python.exe -c "import sys; print(sys.argv[1])" "It's `your`, not `you're`"
    > It's `your`, not `you're`
- JavaScript/node (invoked from cmd)
    > $ c:\bin\node.exe -e "console.log(process.argv[1])" "It's `your`, not `you're`"
    > It's `your`, not `you're`
- sh (invoked from cmd)
    > $ C:\bin\busybox.exe sh -c "echo $0" "It's `your`, not `you're`"
    > It's `your`, not `you're`
- bash (invoked from PowerShell)
    > bash -c 'echo $0' "It's ``your``, not ``you're``"
    > It's `your`, not `you're`

**Comment by SteveL-MSFT** [comment]
It makes sense to support this.  To avoid breaking the current design where everything after `-Command` is part of the command, we can just support specifying `-Args` before `-Command`.  This will be a bit confusing to users, but we should just have good examples in the docs.

**Comment by aaronla-ms** [comment]
@SteveL-MSFT I hear your concern about breaking changes -- while I can't think of a case where `-Args` is valid, I have to admit PowerShell constantly impresses me with its principle of most surprise. 

But if `-Args` appears before `-Command`, how do you know if `-Command` is an argument to the script vs an argument to the host? In other languages, all args after the command are eaten up and passed to the script, even if they match host command line args.

Counter-proposal:
- add a new argument `-Command1`. This works like `-Command`, except that it only gobbles up a single argument, instead of all subsequent arguments. 
- add a new argument `-ArgsN`. This works like `-Args`, except instead of accepting a single argument (which may be an array when invoked from powershell), it gobles up all remaining arguments into an array.

E.g. `powershell -Command1 C -ArgsN 1 2 3` would pass 3 arguments to the command "C"

**Comment by SteveL-MSFT** [comment]
@aaronla-ms I was thinking that the value of `-Args` would have to be a comma separated string with quotes, if there is whitespace.  However, I like your proposal better.  Maybe it should be `-CommandWithArgs` which accepts a single string and then `-Args` can take everything after it and pass to the command.

**Comment by aaronla-ms** [comment]
@SteveL-MSFT Exactly. Comma separated makes so many things unnecessarily difficult: (a) difficult to forward %* args to powershell from batch scripts (b) complications with passing commas in arguments when invoking powershell (e.g. how do i pass "a,b" as a single argument to powershell?) (c)... should i go on?

With your new proposal, would the powershell commandlet work the same way? E.g. in powershell could I say `-CommandWithArgs { echo $args[1] } -Args one two` and it would print `two`?

**Comment by aaronla-ms** [comment]
FYI, for folks looking for a short term workaround, I'm using [Environment]::GetCommandLineArgs and a carefully placed line comment to work around this limitation for now. Posting here as it might help others with the same issue.

**Workaround**: https://github.com/aaronla-ms/powershell-tips-and-tricks/blob/main/examples/embed.cmd

**Comment by Jaykul** [comment]
I'm super confused. This is just asking for there to be an **explicit** named `-Args` parameter which is literally ignored.

You can already do this. From CMD, for instance:
```PowerShell
powershell -command Get-ChildItem %UserProfile% -File
```

The limitation in #15410 is not on passing parameters, it's on passing script blocks. There's no way to pass a scriptblock like `{param(...) ... }` to PowerShell -- so an `-Args` parameter would not help you at all.

**Comment by Jaykul** [comment]
For what it's worth, apart from GetCommandLineArgs, the other way to pass through %* to your powershell code is to **have an actual file or command** and actually pass %* to it. I've frequently used this trick.

The in-line version is like this:
```CMD
@PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Command function hello {param($User, $Greeting); Write-Host "$Greeting, $User! How are you?"}; hello %*
```
If you call that like: `.\hello.cmd Joel Welcome` it should work fine.

I've also used it to wrap large scripts by embedding the script at the bottom of the .cmd file after a `GOTO :EOF` and then copying the file within the batch:

```CMD
:: <# BEGIN POWERSHELL AS BATCH HEADER
@ECHO OFF
copy %0 %0.ps1 >nul
PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Command function :: {}; %0.ps1 %*
del %0.ps1 >nul
:: To avoid potentially leaving a window hanging, you could EXIT
:: This is much nicer if you're calling this from an existing cmd window
GOTO :EOF
:: END POWERSHELL AS BATCH HEADER #>
## Write whatever PowerShell script you want ...
## The dot-source plus @Args is a hack to let you use a param block even though the first line of the file is ::
. {

param($User='Nobody', $Greeting='Greetings')
Write-Host "$Greeting, $User! How are you?"

} @Args
```

The `function :: {}` lets PowerShell ignore the `::` on the first line.

**Comment by aaronla-ms** [comment]
@Jaykul writes
> For what it's worth, apart from GetCommandLineArgs, the other way to pass through %* to your powershell code is to **have an actual file or command** and actually pass %* to it. I've frequently used this trick.
> 
> The in-line version is like this:
> 
> ```batchfile
> @PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Command function hello {param($User, $Greeting); Write-Host "$Greeting, $User! How are you?"}; hello %*
> ```

DO NOT USE THIS CODE, it is vulnerable to code injection attacks:

```
aaronla@aaronla-rabbit:scratch$ dir /b a.txt
a.txt

aaronla@aaronla-rabbit:scratch$ hello.cmd "$(del a.txt)"
 ! How are you?

aaronla@aaronla-rabbit:scratch$ dir /b a.txt
File Not Found
```

Again, I'm emphasizing, passing arguments via command line is _very *very*_ hard to do correctly in powershell. Request a feature to do so instead of risk gettin

**Comment by Jaykul** [comment]
> aaronla@aaronla-rabbit:scratch$ hello.cmd "$(del a.txt)"

LOL, as if you needed to pass `DEL` from dos into PowerShell to run it 😉 

However, that's also **the same thing** that would happen when calling it from PowerShell.

To be clear, my point is that you don't need an -Args -- you can already pass parameters.

![image](https://user-images.githubusercontent.com/192942/135566184-e9e5e15b-d8a3-4ece-be5f-e5f81005c9a8.png)

The fact that PowerShell parses sub-expressions in parameters is a **feature** of PowerShell which you can only avoid by escaping or single-quoting the parameters, not by giving them a different name. 

As a side note -- if we did add an `-Arguments` parameter, it would **have** to come before the `-Command` parameter to avoid breaking the existing syntax for parameters. And yes, many core PowerShell commands already take parameters named (or aliased as) `Args`. Try `Get-Command -ParameterName Args`

**Comment by aaronla-ms** [comment]
> LOL, as if you needed to pass `DEL` from dos into PowerShell to run it 😉 

This _has_ happened before.

> there's no need to nitpick my rusty DOS skills (yeah, I should have used `%~s0` and should have done `'%1' '%2'` instead of `%*` to quote the results). The first example clearly shows that you can pass arguments _without_ creating an extra file, and that was the whole point.

No nitpicking intended. I only mean to clarify that there's a bug in the proposed program, and it has security implications. You didn't show that it's possible -- your program corrupted the argument, and failed to print `$(del a.txt)! How are you.` Even worse, the program deleted a file in the process. 

> On top of that, it's **the same thing** that would happen when calling the command that way from PowerShell, so the sub-expression is somewhat irrelevant to the discussion at hand.

Red herring... I'm not asking about calling the command from PowerShell. I'm asking about passing command line options. I could be building a dedicated program in C# that launches the PowerShell script using `Process.Create`, for instance. It still shouldn't delete the file.

Secondly, It's _not_ what happens when calling the command "that way" from PowerShell. Take my `embed.cmd` example above -- observe that the argument _is_ passed correctly without being interpreted if you quote the string correctly>

```
PS C:\scratch> Test-Path a.txt
True
PS C:\scratch> .\embed.cmd '$(del a.txt)'
argcount=1
args0=$(del a.txt)
PS C:\scratch> Test-Path a.txt
True
```

And observe what happens if I call your script from PowerShell in a similar manner:

```
PS C:\scratch> Test-Path a.txt
True
PS C:\scratch> .\hello.cmd '$(del a.txt)'
 ! How are you?
PS C:\scratch> Test-Path a.txt
False
```


> 
> To be clear, my point is that you don't need an -Args
> 
> ## You can already pass parameters fine by just sticking them on the end of the line.
> ![image](https://user-images.githubusercontent.com/192942/135566184-e9e5e15b-d8a3-4ece-be5f-e5f81005c9a8.png)
> 
> The fact that PowerShell parses sub-expressions in parameters is a **feature** of PowerShell which you can only avoid by escaping or single-quoting the parameters, not by giving them a different name.
> 
> In PowerShell:
> 
> ```powershell
> pwsh -noprofile -command '&{param($first,$last) Write-Host ""Welcome $Last, $First!"" }' "Joel" '''$(del foo.ps1)'''
> ```
> 
> In DOS:
> 
> ```batchfile
> pwsh -noprofile -command "&{param($first,$last) Write-Host ""Welcome $Last, $First!"" }" "Joel" "'$(del foo.ps1)'"
> ```
> 
> As a side note -- if we did add an `-Arguments` parameter, it would **have** to come before the `-Command` parameter to avoid breaking the existing syntax for parameters. And yes, many core PowerShell commands already take parameters named (or aliased as) `Args`. Try `Get-Command -ParameterName Args`

**Comment by Jaykul** [comment]
> Please note that if you call powershell from powershell using the -Command / -Args pattern, that feature does not activate:

Like I said. The solution is to wrap it in single quotes, as I showed above. It has *nothing* to do with Args.

**Comment by aaronla-ms** [comment]
> > Please note that if you call powershell from powershell using the -Command / -Args pattern, that feature does not activate:
> 
> Like I said. The solution is to wrap it in single quotes, as I showed above. It has _nothing_ to do with Args.

Please illustrate how to handle passing the arg if %1 already contains single quotes? E.g. if the user input is `'+$(del a.txt)+'`. You still have an input sanitization issue.

**Comment by mklement0** [comment]
FWIW, this was first proposed as a breaking change in 2017, pre-v6, in the context of better aligning the PowerShell CLI with that of POSIX-compatible shells:

* https://github.com/PowerShell/PowerShell/issues/4024#issuecomment-311541803

I think `-CommandWithArgs` (perhaps aliased to `-ca`) would help, but to avoid confusion around the syntax for `-Args` I would simply _omit_ `-Args` and use purely positional processing: the first argument following `-CommandWithArgs` would be the PowerShell code, and all remaining arguments would implicitly be the arguments to pass to it.

That is, the equivalent of the following `sh` command line (note the unfortunate need for `-`, which binds to `$0`, which is something we can avoid in PowerShell):

```sh
# Run from Bash, for instance.
$ sh -c 'for a; do echo "[$a]"; done' - '$fun' '@times'
[$fun]
[@times]
```

would then be:

```
pwsh -CommandWithArgs '$args | % { "[$_]"'  '$fun' '@times'
```

Note that, as in `sh` and Python, for instance, the `$args | % { "[$_]"` argument would _implicitly_ act like a script block, so no need for `{ ... }` enclosure; to put it differently: the argument would act like an anonymous, in-memory script file.
