### ISSUE TITLE
Should use ellipsis instead of a single dot when message is truncated during progress rendering

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#15412]
The issue is to track the review comment https://github.com/PowerShell/PowerShell/pull/15264#discussion_r632704011

## Steps to reproduce

Resize the console window to use a small width.

```powershell
1..100 | % { Write-Progress -Activity "123456789012345678901234567890123456789012345678901234567890" -Status "S" -PercentComplete $_ -SecondsRemaining $_ ; Sleep 1}
```

## Expected behavior

Use ellipsis when a message is truncated.

## Actual behavior

A single dot is used instead:

![image](https://user-images.githubusercontent.com/127450/118310760-e041a700-b4a3-11eb-8771-8ab9ec3b4d61.png)

**Comment by SteveL-MSFT** [comment]
This was already fixed
