### ISSUE TITLE
Using -Args with -Command does not work as documented

### ISSUE THREAD

**Issue by aaronla-ms** [PowerShell/PowerShell#15410]
The powershell command line docs suggest that the "-Command" option may be used with the "-args" option to pass extra arguments to a script block. However, this does not work as described. 

Recommend updating the command line documentation to document the actual behavior of -Command, which does not support an `-args` option.

```
Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
```

## Steps to reproduce

```shell
powershell.exe -Command "{ echo $args[1] }" -args one two three
```

## Expected behavior

print `two`

## Actual behavior

error:

```none
aaronla@aaronla-r:scratch$ dotnet pwsh -command "{ echo $args[1] }" -args one two three
ParserError:
Line |
   1 |  { echo $args[1] } -args one two three
     |                    ~~~~~
     | Unexpected token '-args' in expression or statement.
```

## Environment data

```none
aaronla@aaronla-r:PowerApps-CoreServices$ dotnet pwsh -command echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
The command needs to be written as a script block, not a string, and the args as an array

`pwsh  -command { echo $args[1] }  -args one,two,three`

**Comment by aaronla-ms** [comment]
@jhoneill No dice for me. Similar error:

```
aaronla@aaronla-r:repos$ powershell -command { echo $args[1] } -args one,two,three
At line:1 char:19
+ { echo $args[1] } -args one,two,three
+                   ~~~~~
Unexpected token '-args' in expression or statement.
At line:1 char:25
+ { echo $args[1] } -args one,two,three
+                         ~~~
Unexpected token 'one' in expression or statement.
At line:1 char:28
+ { echo $args[1] } -args one,two,three
+                            ~
Missing argument in parameter list.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

> When a string is used in place of the script block, -args isn't allowed ,but you can do something like `pwsh -c "dir" "function:"`

Yes, but then string escaping between shells gets to be a nightmare. I'd like something I can reasonably forward cmd's `%*` args through. E.g.

```
REM example
powershell.exe -command { & .\init.ps1; & .\myscript.ps1 @args } -args %*
```

**Comment by vexx32** [comment]
It works -- but it only works if the shell you're running it in is itself powershell/pwsh. The scriptblock handling that allows `-Command` to take an actual scriptblock requires that the shell handing the argument to the executable is powershell or pwsh, which will actively serialize the input to a format that the new shell instance can parse.

Without that, everything following `-Command` is assumed to be a single command string/script, so `-Args` is never read as an executable argument, but interpreted as part of the command string.

**Comment by 237dmitry** [comment]
It is works in bash:
```
pwsh -c '{ echo $args.count; $args[0]; $args -join " "}.Invoke(1,2,3)'
```
returned:
```
3
1
1 2 3
```

**Comment by jhoneill** [comment]
> @jhoneill No dice for me. Similar error:
> I'd like something I can reasonably forward cmd's `%*` args through. E.g.
> 
> ```
> REM example
> powershell.exe -command { & .\init.ps1; & .\myscript.ps1 @args } -args %*
> ```
> 
> Obviously the above doesn't work. But how do you fix it?

My brain is having trouble with writing a batch file that runs PowerShell (why not have everything in one PS script)  but this works 

`powershell -noprofile -command "echo %*" `

**Comment by aaronla-ms** [comment]
@jhoneill

> My brain is having trouble with writing a batch file that runs PowerShell 

A few practical reasons reasons:

- Out of the box, PowerShell scripts aren't executable. Windows lacks the equivalent of #!, and the default shell verb for PowerShell is to edit it in notepad. Batch scripts are.
- To get consistent behavior from machine to machine, with varying user profiles and permission policies, we need to launch PowerShell with the additional arguments `-ExecutionPolicy Bypass -NonInteractive -NoProfile`. Batch scripts are a handy way to automate this. 
- MSbuild lacks a built in task for running PowerShell . But it includes built in support for batch scripts via the Exec task. This makes batch scripts a handy place to add PowerShell to the build.

Hopefully that helps understand our motivations here.

> but this works: `powershell -noprofile -command "echo %*"`

It does not work if %* contains quotations. I'm looking for something that can _generally_ forward arguments, not work in some limited specific cases.

**Comment by aaronla-ms** [comment]
@vexx32

> It works -- but it only works if the shell you're running it in is itself powershell/pwsh

Thanks for the clarification vexx. If that's the intended behavior, that this feature only work from specific shells, then perhaps that's the scope of the bug. Update the documentation to reflect that this only works on bash and powershell, and not via exec / CreateProcess / batch / Windows command line.

**Comment by aaronla-ms** [comment]
> It works in bash:
> 
> ```
> pwsh -c '{ echo $args.count; $args[0]; $args -join " "}.Invoke(1,2,3)'
> ```
> 

Thanks for the feedback @237dmitry, but I get a very similar error when run on bash. `-Args` doesn't seem to work there either.

On bash 
```
aaronla@aaronla-r:~/scratch$ echo "${BASH_VERSION}"
echo "${BASH_VERSION}"
5.0.3(1)-release
aaronla@aaronla-r:~/scratch$ dotnet pwsh -Command "{ echo \$args[1] }" -args one two three
ParserError:
Line |
   1 |  { echo $args[1] } -args one two three
     |                    ~~~~~
     | Unexpected token '-args' in expression or statement.
```

**Comment by rjmholt** [comment]
@sdwheeler are you able to transfer this to PowerShell-Docs?

**Comment by 237dmitry** [comment]
> but I get a very similar error when run on bash

It works, I think string arguments in `.Invoke()` should be in quotation marks:

![1_000](https://user-images.githubusercontent.com/78153320/118536476-769bf400-b754-11eb-8aae-afd4df55ade0.png)

**Comment by aaronla-ms** [comment]
I've seen some people on the thread claim this works when invoked from powershell, but if you debug the child process, you'll observe that powershell-launching-powershell never passes the -command/-args combo, but instead treats -Command/-Args as an alias for -encodedCommand/-encodedArgs.

Example repro:

```
aaronla@aaronla-rabbit:echoapp$ cat Program.cs
∩╗┐class Program {
static void Main(string[] args) =>
    System.Console.WriteLine("Args=" + System.Environment.CommandLine);
}

aaronla@aaronla-rabbit:echoapp$ dotnet build -nologo
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  echoapp -> C:\scratch\echoapp\bin\Debug\net6.0\echoapp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.78

aaronla@aaronla-rabbit:echoapp$ cd bin\Debug\net6.0\

aaronla@aaronla-rabbit:net6.0$ set path=%cd%;%path%

aaronla@aaronla-rabbit:net6.0$ C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\scratch\echoapp\bin\Debug\net6.0> powershell -Command { echo "hello $($args[0])" } -args world
Args=C:\scratch\echoapp\bin\Debug\net6.0\echoapp.dll -encodedCommand IABlAGMAaABvACAAIgBoAGUAbABsAG8AIAAkACgAJABhAHIAZwBzAFsAMABdACkAIgAgAA== -encodedarguments PAA/AHgAbQBsACAAdgBlAHIAcwBpAG8AbgA9ACIAMQAuADAAIgAgAGUAbgBjAG8AZABpAG4AZwA9ACIAdQB0AGYALQAxADYAIgA/AD4APABPAGIAagBzACAAVgBlAHIAcwBpAG8AbgA9ACIAMQAuADEALgAwAC4AMQAiACAAeABtAGwAbgBzAD0AIgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBtAGkAYwByAG8AcwBvAGYAdAAuAGMAbwBtAC8AcABvAHcAZQByAHMAaABlAGwAbAAvADIAMAAwADQALwAwADQAIgA+ADwATwBiAGoAIABSAGUAZgBJAGQAPQAiADAAIgA+ADwAVABOACAAUgBlAGYASQBkAD0AIgAwACIAPgA8AFQAPgBTAHkAcwB0AGUAbQAuAEMAbwBsAGwAZQBjAHQAaQBvAG4AcwAuAEEAcgByAGEAeQBMAGkAcwB0ADwALwBUAD4APABUAD4AUwB5AHMAdABlAG0ALgBPAGIAagBlAGMAdAA8AC8AVAA+ADwALwBUAE4APgA8AEwAUwBUAD4APABTAD4AdwBvAHIAbABkADwALwBTAD4APAAvAEwAUwBUAD4APAAvAE8AYgBqAD4APAAvAE8AYgBqAHMAPgA= -inputFormat xml -outputFormat text
```

**Comment by aaronla-ms** [comment]
I propose updating the documentation for -Args to indicate that it is not supported as a command line argument, and only supported as an alias when powershell is invoked using the powershell function/alias.

**Comment by rjmholt** [comment]
> If that's the intended behavior, that this feature only work from specific shells, then perhaps that's the scope of the bug. Update the documentation to reflect that this only works on bash and powershell, and not via exec / CreateProcess / batch / Windows command line.

From [about_powershell.exe](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-command):

> The Command parameter only accepts a script block for execution when it can recognize the value passed to Command as a ScriptBlock type. This is only possible when running powershell.exe from another PowerShell host. The ScriptBlock type may be contained in an existing variable, returned from an expression, or parsed by the PowerShell host as a literal script block enclosed in curly braces ({}), before being passed to powershell.exe.

> using the powershell function/alias

It's working as the standard executable here, it's just that the invoking PowerShell process is able to translate the scriptblock passed as an argument into an encoded command under the hood.

**Comment by aaronla-ms** [comment]
> It works, I think string arguments in `.Invoke()` should be in quotation marks:

My issue is not with the .Invoke method, it's with the -Args command line argument.

**Comment by rjmholt** [comment]
> I propose updating the documentation

Also please note that the repo for that is https://github.com/PowerShell/PowerShell-Docs.

**Comment by sdwheeler** [comment]
This works, as stated in the docs, when it is run from within a PowerShell session.

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> pwsh -command { echo $args[1] } -args one,two,three
two
PS> powershell -command { echo $args[1] } -args one,two,three
two

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS> powershell -command { echo $args[1] } -args one,two,three
two
PS> pwsh -command { echo $args[1] } -args one,two,three
two
PS>
```

**Comment by rjmholt** [comment]
Given the discussion in the issue, I think the docs already cover this case and have marked it resolved. If there are changes you'd like to see in the documentation, please open an issue in https://github.com/MicrosoftDocs/PowerShell-Docs.

**Comment by aaronla-ms** [comment]
Thanks for clarifying @rjmholt. The docs make it seem like it's a command line argument, but now I see what you mean -- it's more intended as a _powershell_ function argument to be used from within powershell, and not to be used at the command line / StartProcess / exec.
