### ISSUE TITLE
Powershell disable horrible colored lines when we need a standard CLEAR output

### ISSUE THREAD

**Issue by filzek** [PowerShell/PowerShell#15423]
Hi,

Powershell is a awesome tool but it lacks from a simples COLOR disable output, as if we try to caputre it outputs its always colored and destroy any work possible for a RAW output from any kind of console application.

It is a must to have an option at the console to just running a command as powershell -disabllecoloredoutput -c command

That is so simple, thousand of people asking for it around the internet, and still not being answered by the devs, WHY?

**Comment by jborean93** [comment]
There's a new feature added for 7.2 that will give you a way to control this using env vars https://github.com/PowerShell/PowerShell/issues/14964.

**Comment by doctordns** [comment]
One partial fix is to Remove the PSReadline Module.
