### ISSUE TITLE
PowerShell object offers no way to reset/clear scripts

### ISSUE THREAD

**Issue by et1975** [PowerShell/PowerShell#15427]
## Summary of the new feature/enhancement

`PowerShell`'s `Invoke()` and its derivatives run commands and scripts that have been added.
If I want to reuse the instance of `PowerShell` I can clear the commands with `ps.Commands.Clear()`, but there's no counterpart for the scripts.

## Proposed technical implementation details (optional)

Please add/or document if it exists how to clear the scripts as well as commands.

**Comment by vexx32** [comment]
As far as I can tell, scripts are considered to be part of the `.Commands` property as well. Scripts are added with `ps.Commands.AddScript(script)` and the entry is removed from `ps.Commands` when you call `ps.Commands.Clear()`

**Comment by jborean93** [comment]
Just to add more info a script and command are represented by [Command](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.command?view=powershellsdk-7.0.0) and the only difference is a script has `IsScript -eq $true`. Just to verify

```powershell
$ps = [Powershell]::Create()
[void]$ps.AddScript('1')
$ps.Commands.Commands | Select *

# Parameters                           : {}
# CommandText                          : 1
# IsScript                             : True
# UseLocalScope                        : False
# CommandOrigin                        : Runspace
# IsEndOfStatement                     : False
# MergeUnclaimedPreviousCommandResults : None

[void]$ps.AddScript('2')
$ps.Commands.Commands | Select *

# Parameters                           : {}
# CommandText                          : 1
# IsScript                             : True
# UseLocalScope                        : False
# CommandOrigin                        : Runspace
# IsEndOfStatement                     : False
# MergeUnclaimedPreviousCommandResults : None

# Parameters                           : {}
# CommandText                          : 2
# IsScript                             : True
# UseLocalScope                        : False
# CommandOrigin                        : Runspace
# IsEndOfStatement                     : False
# MergeUnclaimedPreviousCommandResults : None

$ps.Commands.Clear()
[void]$ps.AddScript('3')
$ps.Commands.Commands | Select *

# Parameters                           : {}
# CommandText                          : 3
# IsScript                             : True
# UseLocalScope                        : False
# CommandOrigin                        : Runspace
# IsEndOfStatement                     : False
# MergeUnclaimedPreviousCommandResults : None
```

**Comment by et1975** [comment]
yep, just wrote some code to check this as well and indeed command.Clear also clears the scripts. The relationship between ps.Commands content and ps content was the point of confusion for me - I'd assumed the commands are for commands only and didn't look for scripts in there. @jborean93 comment clears it up, thanks.
