### ISSUE TITLE
Cannot load PSReadline module.  Console is running without PSReadline.

### ISSUE THREAD

**Issue by garfieldbanks** [PowerShell/PowerShell#15426]
Every time I open powershell I get this error:
`Cannot load PSReadline module.  Console is running without PSReadline.
`
I added an alias to a profile.ps1 file in my user documents folder. (I have since removed it.) I think I started seeing the error after I opened powershell in VSCode the first time after adding the alias. (It asked a question about powershell when I opened it.) But now, all the powershell windows I open give this error. I have tried lots of policy execution changes and trying to install / remove PSReadline but nothing seems to work. I cannot get this error to leave me alone.
```
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Obvious question perhaps , have you tried running with -noprofile ?

**Comment by garfieldbanks** [comment]
Running with -noprofile results in the same error.

**Comment by ThomasNieto** [comment]
What happens if you run:

```powershell
Get-Module PSReadline -ListAvailable
```

and if you try to load the module manually:

```powershell
Import-Module PSReadline
```

**Comment by garfieldbanks** [comment]
Get-Module PSReadline -ListAvailable
```
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLi…
```
Import-Module PSReadline
```
Import-Module: Errors occurred while loading the format data file:
C:\apps\powershell\7\Modules\PSReadline\PSReadLine.format.ps1xml, , C:\apps\powershell\7\Modules\PSReadline\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: File C:\apps\powershell\7\Modules\PSReadline\PSReadLine.format.ps1xml cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy..
```
I've looked at my group policy and I have no idea which setting would be causing this error.

**Comment by jhoneill** [comment]
Check the file in windows explorer,  look for the downloaded file block and check the digital signatures page, details says the sig is OK and the signer matches the one on the PSM1 file.

**Comment by ThomasNieto** [comment]
You may also try running

```powershell
Unblock-File C:\apps\powershell\7\Modules\PSReadline\PSReadLine.format.ps1xml
```

**Comment by garfieldbanks** [comment]
> You may also try running
> 
> ```powershell
> Unblock-File C:\apps\powershell\7\Modules\PSReadline\PSReadLine.format.ps1xml
> ```

I tried this but still get the error.

**Comment by garfieldbanks** [comment]
> Check the file in windows explorer, look for the downloaded file block and check the digital signatures page, details says the sig is OK and the signer matches the one on the PSM1 file.

Hmmm... I think it's telling me it was revoked by the issuer.

**Comment by ThomasNieto** [comment]
Lets try updating to the latest version. Then reloading the console.

```powershell
Install-Module -Name PSReadline -AllowPrerelease -Force
```

**Comment by garfieldbanks** [comment]
`Install-Module -Name PSReadline -AllowPrerelease -Force
Install-Module: The 'Install-Module' command was found in the module 'PowerShellGet', but the module could not be loaded. For more information, run 'Import-Module PowerShellGet'.`

**Comment by garfieldbanks** [comment]
For now I'm just using clear in a profile to get rid of this annoying error message. Definitely not ideal!

**Comment by garfieldbanks** [comment]
What are all the different locations for settings files that I can check? I've tried uninstalling and reinstalling but no luck. Is there any surefire way of resetting powershell without refreshing windows?

**Comment by garfieldbanks** [comment]
Trying a windows refresh, keeping files, but chose the option to download from the cloud. So we'll see if this is enough to get rid of the error.

**Comment by doctordns** [comment]
Sounds like Group Policy is the culprit here.,

To find the location of the module:

```console
PS > Get-Nodule PsrReadLine | Format-List -Properety ModuleBase

ModuleBase : C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0
```

**Comment by garfieldbanks** [comment]
Refreshing (resetting) the PC did not get rid of the error. Not going to do a clean install right now though.

This command returns nothing:
`Get-Module PSReadLine | Format-List -Property ModuleBase`

**Comment by doctordns** [comment]
Odd - You would seem to have removed PSReadline somehow.

You can also try:

```powershell
Get-Module PsReadLine  -List | Format-List -Property ModuleBase # find any versions on the host
```
If that shows nothing then somehow you have managed to remove the module from PowerShell's ability to find it. I have no idea  how you could have done that. The simplest resolution would be to just reinstall the module using `Install-Module` and specify **PSReadLine*. Then restart PowerShell.

**Comment by garfieldbanks** [comment]
Get-Module PsReadLine  -List | Format-List -Property ModuleBase
```
ModuleBase : C:\apps\powershell\7\Modules\PSReadLine
ModuleBase : C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0
```

**Comment by garfieldbanks** [comment]
I was able to get admin to work without the error message following these steps:

Windows Administrative Tools > Local Security Policy > Enforcement > All users except administrators

Then I used `Import-Module PSReadline` in an admin console and from then on my admin consoles have not had the error.

Anyone have any idea how to make my non-admin consoles get rid of the error?

**Comment by garfieldbanks** [comment]
Import-Module PSReadline
`Import-Module: Errors occurred while loading the format data file:
C:\Documents\PowerShell\Modules\PSReadline\PSReadLine.format.ps1xml, , C:\Documents\PowerShell\Modules\PSReadline\PSReadLine.format.ps1xml: The file was skipped because of the following validation exception: File C:\Documents\PowerShell\Modules\PSReadline\PSReadLine.format.ps1xml cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy..`

**Comment by garfieldbanks** [comment]
Is there a way to install things as an admin but for my user account?

**Comment by garfieldbanks** [comment]
I tried both -Scope Global and -Scope Local but no luck
` Import-Module PSReadline -Scope Local`
` Import-Module PSReadline -Scope Global`

**Comment by garfieldbanks** [comment]
Oh wow. I found it!
`Install-Module -Name PSReadline -AllowPrerelease -Force`
This didn't work before because I hadn't yet been able to run even as admin properly. Now that admin is working again I ran this command again and it actually fixed my unelevated console. No more error!

**Comment by daNutzzzzz** [comment]
I had to use:

```
Set-ExecutionPolicy RemoteSigned
Import-Module PSReadline
```

**Comment by tianberg** [comment]
hi all ,

I had meet same error as @garfieldbanks showd above , and try every suggestions list above .

The error still exists.  I could provice some clue which caused  to trigger this error .

I installed powershell extension into  Visual Studio Code  . The  vs code powershell console show me below command today :

> File
> D:\apps\powershell\7\Modules\PSReadline\PSReadLine.format.ps1xml
> is published by CN=Microsoft Corporation, O=Microsoft
> Corporation, L=Redmond, S=Washington, C=US and is not trusted on
> your system. Only run scripts from trusted publishers.
> [V] Never run  [D] Do not run  [R] Run once  [A] Always run
> [?] Help(default is "D"):  V

I comfirmed the question by input  V  , which means   [V] Never run .

After this moment , each time when I open Windows Terminal , there are always show the  message " Cannot load PSReadline module.  Console is running without PSReadline. " , even if set the environment policy to **Unrestricted**  .

At current situation , the only way I can load the PSReadline into console is by run command each time when I open console  :  

> Import-Module 'C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadline.psd1'

when the current cosole closed , PSReadline module gone too .

**Comment by jhoneill** [comment]
> hi all ,
> 
> I had meet same error as @garfieldbanks showd above , and try every suggestions list above .
> 
> The error still exists. I could provice some clue which caused to trigger this error .
> 
> I installed powershell extension into Visual Studio Code . The vs code powershell console show me below command today : 

```  
File <<path>> PSReadLine.format.ps1xml  
is published by  CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US  
and is not trusted on  your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help(default is "D"):  V
```
> I comfirmed the question by input V , which means [V] Never run .
> 
> After this moment , each time when I open Windows Terminal , there are always show the message " Cannot load PSReadline module. Console is running without PSReadline. " , even if set the environment policy to **Unrestricted** .

I was testing something yesterday and I find if I set Policy to **AllSigned** I get the  `PSReadLine.format.ps1xml  is published by Microsoft but isn't trusted` message. 

`Get-AuthenticodeSignature` shows the thumbprint for this file is the same as .psm1 and .psd1 files 

```
EnhancedKeyUsageList : {Microsoft Publisher (1.3.6.1.4.1.311.76.8.1), Code Signing (1.3.6.1.5.5.7.3.3)}
NotAfter             : 03/03/2021 18:39:47
NotBefore            : 04/03/2020 18:39:47
SerialNumber         : 3300000187721772155940C709000000000187
Thumbprint           : 2485A7AFA98E178CB8F30C9838346B514AEA4769
Issuer               : CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Subject              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
```

Note that although this cert has NOW expired it has a certified time stamp of ‎02 ‎November ‎2020 22:52:45 when it was valid. 

**PowerShell files are signed with a newer cert, and it appears the cert used for PSReadline is *not* trusted by default.**

``` 
EnhancedKeyUsageList : {Microsoft Publisher (1.3.6.1.4.1.311.76.8.1), Code Signing (1.3.6.1.5.5.7.3.3)}
NotAfter             : 01/09/2022 19:32:59
NotBefore            : 02/09/2021 19:32:59
SerialNumber         : 33000002528B33AAF895F339DB000000000252
Thumbprint           : 8740DF4ACB749640AD318E4BE842F72EC651AD80
Issuer               : CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Subject              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
```

I suspect answering NEVER to `[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] `  puts that cert on a dis-trusted list and nothing signed with that will run in future.

**Comment by holyPunch420** [comment]
> hi all ,
> 
> I had meet same error as @garfieldbanks showd above , and try every suggestions list above .
> ...
> At current situation , the only way I can load the PSReadline into console is by run command each time when I open console :
> 
> > Import-Module 'C:\Program Files\WindowsPowerShell\Modules\PSReadline\2.0.0\PSReadline.psd1'
> 
> when the current cosole closed , PSReadline module gone too .

Hello everyone. This is my first post here so it also serves as a little introduction. I am a c0d3r by heart, php dev since 20 years. I love scripting but i like many languages, scripts, markup, etc... Anyhow - i read about you all's problem. Just today i ran into the same issue after screwing around with powersHell, 4-6 modules paths, NcopyPaste {^_-}

than i got the error when i powershelled in... This is my solution, without touching gPolicy.
in this case we temporary set the execPolicy for localMachine to remoteSigned,
we execute whatever, then we set the policy back to restricted. like so:

 1 > log into an administrator prompt ( ctrl-shift LeftClick ) ; then
 2 > log into the psPrompt - type: powershell  OR
 2 > login to powershell as admin at step 1 and skip that.
 3 > Set-ExecutionPolicy RemoteSigned -Scope LocalMachine
 x > Import-Module PSReadline
 x > Install-Module PSReadline
 4 > Set-ExecutionPolicy Restricted -Scope LocalMachine
 5 > exit && shutdown /r /f /t 0

that was it for me. let me know if it worked for you too, or not.

#!Cheers,
~Joe.

**Comment by xishian** [comment]
> > hi all ,
> > I had meet same error as @garfieldbanks showd above , and try every suggestions list above .
> > The error still exists. I could provice some clue which caused to trigger this error .
> > I installed powershell extension into Visual Studio Code . The vs code powershell console show me below command today :
> 
> ```
> File <<path>> PSReadLine.format.ps1xml  
> is published by  CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US  
> and is not trusted on  your system. Only run scripts from trusted publishers.
> [V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help(default is "D"):  V
> ```
> 
> > I comfirmed the question by input V , which means [V] Never run .
> > After this moment , each time when I open Windows Terminal , there are always show the message " Cannot load PSReadline module. Console is running without PSReadline. " , even if set the environment policy to **Unrestricted** .
> 
> I was testing something yesterday and I find if I set Policy to **AllSigned** I get the `PSReadLine.format.ps1xml is published by Microsoft but isn't trusted` message.
> 
> `Get-AuthenticodeSignature` shows the thumbprint for this file is the same as .psm1 and .psd1 files
> 
> ```
> EnhancedKeyUsageList : {Microsoft Publisher (1.3.6.1.4.1.311.76.8.1), Code Signing (1.3.6.1.5.5.7.3.3)}
> NotAfter             : 03/03/2021 18:39:47
> NotBefore            : 04/03/2020 18:39:47
> SerialNumber         : 3300000187721772155940C709000000000187
> Thumbprint           : 2485A7AFA98E178CB8F30C9838346B514AEA4769
> Issuer               : CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> Subject              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> ```
> 
> Note that although this cert has NOW expired it has a certified time stamp of ‎02 ‎November ‎2020 22:52:45 when it was valid.
> 
> *_PowerShell files are signed with a newer cert,_
> 
> ```
> EnhancedKeyUsageList : {Microsoft Publisher (1.3.6.1.4.1.311.76.8.1), Code Signing (1.3.6.1.5.5.7.3.3)}
> NotAfter             : 01/09/2022 19:32:59
> NotBefore            : 02/09/2021 19:32:59
> SerialNumber         : 33000002528B33AAF895F339DB000000000252
> Thumbprint           : 8740DF4ACB749640AD318E4BE842F72EC651AD80
> Issuer               : CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> Subject              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> ```
> 
> I suspect answering NEVER to `[V] Never run [D] Do not run [R] Run once [A] Always run [?] ` puts that cert on a dis-trusted list and nothing signed with that will run in future.

So how to solve it? Has any ideas?

**Comment by doctordns** [comment]
Not sure what solution you are looking for.
If it were me, I#'d just remove the old module at: ModuleBase : C:\Program Files\WindowsPowerShell\Modules\PSReadline.
Removing that folder and everything below, in effect, removes the older module.  And even better, remove the one at

**Comment by doctordns** [comment]
Accidently reopened it. Sorry!

**Comment by alexquentin** [comment]
Failed to load PSReadline module. The console works without PSReadline.
1. In Administrator mode, launch PowerShell and run Set-ExecutionPolicy RemoteSigned
2. Confirm switching - Y

After this, the PSReadline module will load normally.

**Comment by kumarchandresh** [comment]
Encountered this in 2024, and landed here...

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config
ExecutionPolicy is stored separately for Windows PowerShell and cross-platform PowerShell. To change ExecutionPolicy
for both instances of PowerShell, execute the Set-ExecutionPolicy command on each instance separately.
Windows PowerShell settings are stored in the Windows Registry, whereas cross-platform PowerShell settings are
stored in a JSON file.

  - `$env:USERPROFILE\Documents\PowerShell\powershell.config.json` (user)
  - `$env:ProgramFiles\PowerShell\7\powershell.config.json` (system)

The **default ExecutionPolicy** of the cross-platform PowerShell is **RemoteSigned** at the time of installation, since it is shipped with the PSReadLine module.

If you recently changed your ExecutionPolicy to something more restrictive than RemoteSigned, then you'll get the following error.
```
Cannot load PSReadline module. Console is running without PSReadline.
```

To revert it back, use one or both of the following commands depending upon which setting you had changed.
```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
```

**Comment by Roushelfy** [comment]
> > > hi all ,
> > > I had meet same error as @garfieldbanks showd above , and try every suggestions list above .
> > > The error still exists. I could provice some clue which caused to trigger this error .
> > > I installed powershell extension into Visual Studio Code . The vs code powershell console show me below command today :
> > 
> > 
> > ```
> > File <<path>> PSReadLine.format.ps1xml  
> > is published by  CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US  
> > and is not trusted on  your system. Only run scripts from trusted publishers.
> > [V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help(default is "D"):  V
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > I comfirmed the question by input V , which means [V] Never run .
> > > After this moment , each time when I open Windows Terminal , there are always show the message " Cannot load PSReadline module. Console is running without PSReadline. " , even if set the environment policy to **Unrestricted** .
> > 
> > 
> > I was testing something yesterday and I find if I set Policy to **AllSigned** I get the `PSReadLine.format.ps1xml is published by Microsoft but isn't trusted` message.
> > `Get-AuthenticodeSignature` shows the thumbprint for this file is the same as .psm1 and .psd1 files
> > ```
> > EnhancedKeyUsageList : {Microsoft Publisher (1.3.6.1.4.1.311.76.8.1), Code Signing (1.3.6.1.5.5.7.3.3)}
> > NotAfter             : 03/03/2021 18:39:47
> > NotBefore            : 04/03/2020 18:39:47
> > SerialNumber         : 3300000187721772155940C709000000000187
> > Thumbprint           : 2485A7AFA98E178CB8F30C9838346B514AEA4769
> > Issuer               : CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> > Subject              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that although this cert has NOW expired it has a certified time stamp of ‎02 ‎November ‎2020 22:52:45 when it was valid.
> > *_PowerShell files are signed with a newer cert,_
> > ```
> > EnhancedKeyUsageList : {Microsoft Publisher (1.3.6.1.4.1.311.76.8.1), Code Signing (1.3.6.1.5.5.7.3.3)}
> > NotAfter             : 01/09/2022 19:32:59
> > NotBefore            : 02/09/2021 19:32:59
> > SerialNumber         : 33000002528B33AAF895F339DB000000000252
> > Thumbprint           : 8740DF4ACB749640AD318E4BE842F72EC651AD80
> > Issuer               : CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> > Subject              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I suspect answering NEVER to `[V] Never run [D] Do not run [R] Run once [A] Always run [?] ` puts that cert on a dis-trusted list and nothing signed with that will run in future.
> 
> So how to solve it? Has any ideas?

I ran into the same problem. After hours of struggling, it worked. Just run the following command:

Get-ChildItem -Path Cert:\CurrentUser\Disallowed | Where-Object {$_.Subject -like "*Microsoft Corporation*"} | Remove-Item

and everything is down

**Comment by 1438250** [comment]
Garbage powershell, Microsoft is the most garbage company in the world. Such common bugs appear repeatedly. I tried all the above solutions and all the solutions provided by ai, but they could not be solved. I suggest that people who encounter the same problem in the future directly uninstall powershell.
ジャンクなpowershell、マイクロソフト社は世界で最もジャンクな会社です。このようなよくあるバグが繰り返し発生しています。私は上記のすべての案とaiが提供するすべての案を試してみましたが、解決できませんでした。将来また同じ問題に直面した人に直接powershellをアンインストールすることをお勧めします
PowerShell, Microsoft est la société la plus poubelle dans le monde, de tels bugs communs récurrents, j'ai essayé tous les scénarios ci-dessus et tous les scénarios fournis par l'IA, ne peut pas résoudre, je recommande à ceux qui rencontrent le même problème à l'avenir directement désinstaller PowerShell
쓰레기 powershell, Microsoft 는 이 세상에서 가장 쓰레기인 회사입니다. 이렇게 흔한 bug 가 반복되고 있습니다. 저는 위의 모든 방안과 ai 가 제공하는 모든 방안을 시도해 보았습니다. 해결할 수 없습니다. 앞으로 같은 문제가 다시 발생할 경우 powershell 을 직접 제거할 것을 제안합니다.
垃圾 powershell, 微软公司是这个世界上最垃圾的公司, 这么常见的bug反复出现,我尝试了上面所有的方案和ai提供的所有方案, 都无法解决, 建议未来再遇到同样问题的人直接卸载 powershell

**Comment by 3ltrashpanda** [comment]
I had same problem, noticed the path for the default powershell executable in Terminal was different.  Changed it to a powershell folder in "Program Files\WindowsApps" with the pwsh.exe file.
