### ISSUE TITLE
Shell Script SRE

### ISSUE THREAD

**Issue by ashishsme14** [PowerShell/PowerShell#15425]
We have given task as

![Shell](https://user-images.githubusercontent.com/61864865/118823082-53994d80-b8d6-11eb-9e8b-008023b8d476.JPG)

for this we written as -

`*/1 * * * * root /opt/cpu_usage.sh;`

![command](https://user-images.githubusercontent.com/61864865/118823394-9529f880-b8d6-11eb-87d7-76604373db8d.JPG)

Getting error as below , also not getting what rest steps mean -

```
cpu_usage.sh: 1: cpu_usage.sh: */1: not found
top: failed tty get
top: failed tty get
```

**Comment by daxian-dbw** [comment]
This is not related to PowerShell.
