### ISSUE TITLE
Feature Request - Transcription status

### ISSUE THREAD

**Issue by Robert-LTH** [PowerShell/PowerShell#15429]
## Summary of the new feature/enhancement

I would like to be able to tell if transcription is active either by calling a function or by checking a variable

## Proposed technical implementation details (optional)

Maybe make this function available somehow?: https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs#L426

or set a variable named $TranscriptActive = $true when Start-Transcript is called successfully.

**Comment by Nevember** [comment]
This is a great idea! I can think of several types of circumstances when getting a boolean response on transcription status would be beneficial, especially when handling volatile and/or sensitive data.

**Comment by jdhitsolutions** [comment]
I think this should go a step further and we need a `Get-Transcript` command that would report on all transcription events. Here's a mockup of the suggested output.

```powershell
Path      : D:\Temp\trans.txt
Started   : 6/14/2021 2:33:50 PM
Runtime   : 00:34:21.8291729
Author    : company\jeff
ProcessID : 29076
```

At a prompt, I could run this to make sure no transcript is currently running that I'm not aware of, that might capture sensitive information. Or I could use this in a script to take other action. I'd also like to see an option with `Stop-Transcript` to kill a transcript based on a file path. But that may require a separate issue.

**Comment by SteveL-MSFT** [comment]
Alternate consideration is to make some internal members public

**Comment by PaulHigin** [comment]
@wg-security
We do not see a security concern providing information on whether transcripts are currently running.  Also 'Get-Transcript' is a great idea, but we feel the path to the transcript file is sensitive information and should not be divulged, as this could invite tampering.

**Comment by jdhitsolutions** [comment]
I don't expect you'll see this before 7.3 at the earliest.

**Comment by jdhitsolutions** [comment]
The Cmdlet Working Group has decided the best course of action is to add a new cmdlet, most likely called, `Get-Transcript`. A [separate issue](https://github.com/PowerShell/PowerShell/issues/16778) has been opened.

**Comment by kilasuit** [comment]
There are occasions where I as an admin, would not want my users, including other admins, to be able to find out that transcription is enabled at all & therefore we should be able to configure this being something that can be denied from returning one way or another.
