### ISSUE TITLE
Better experience running DSC resources and configurations interactively

### ISSUE THREAD

**Issue by JohnLudlow** [PowerShell/PowerShell#15420]
DSC resources and configurations are kind of... opaque in terms of what they tell you when they are running. They don't tell you much unless you pass `-Verbose` which can feel like opening the floodgates.

## Summary of the new feature/enhancement

As a configuration user I would like better feedback (such as indications of progress and success) while running my configuration in a console window so that I can understand the state of my configuration.

As a resource developer I would like better feedback (in particular, success indication) while running and testing my resources so that I can tell whether they are working or not.

## Proposed technical implementation details (optional)

* Invoke-DscResource *should* output an failed result object if the resource failed and a successful result object if it succeeded
* Invoke-DscResource *could* show a progress banner while running. Perhaps long-running resources could use `Write-Progress` as a matter of convention.
* Start-DscConfiguration *should* show a progress bar while running, showing how far through the configuration you are and the name of the currently running resource
* Start-DscConfiguration *should* output the result objects of each resource it processes (either as it goes, or at the end)

**Comment by gaelcolas** [comment]
Bear in mind that **in PowerShell** (pwsh) Configuration documents are not usable (they can only be compiled). So currently there's no such thing as _state of configuration_, and there's no command like `Start-DscConfiguration` (PS 4 up to 5.1).

Implementing it _would_ be a valid request, but that's a different one.  
Worth noting that GuestConfiguration does it in some way, but that's neither Open Sourced, nor Supported outside of the whole Azure Policy Guest Configuration service (but we're working on making this available in the GuestConfiguration module for testing purposes, and as experimental feature for now).

Finally, resource's `Set` method don't return anything (in case of success).
That's the job of the `Get` method, and for you to run after to see if it's compliant. 
To throw errors when running the `Set()` is the responsibility the resource implementation, not PowerShell (so open the issue in the resource repository, or discuss with the DSC Community if something needs to be addressed across all resources the DSC Community manage).
If a resource throws when running a Set, I'm pretty sure using `Invoke-DscResource` will throw the exception when invoking it (if not it's a bug to raise).

As a side note, as per [the Guest Configuration requirements](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create#get-targetresource-requirements), we're introducing `Reasons` to explicitly describe when a resource is not compliant (when running the Get). As you've noted, that's a much better experience than using verbose (you can check `JeaDsc` as an example).

**Comment by JohnLudlow** [comment]
Ahhh I kind of assumed the core cmdlets had been carried over to core already. I can raise another issue to implement something like `Start-DscConfiguration` if you like

I should clarify - I wasn't saying the `Set` method or the `Set-TargetResource` function would return anything. Rather, the thing that's calling the resource (`Invoke-DscResource` for example) should emit an object indicating whether the `Set` method or the `Set-TargetResource` function threw an error. 

I'll test whether Invoke-DscResource throws. It probably does.

Reasons will definitely help, but when is `Get` called? Is that called after `Set`, or just when doing a consistency check before applying?
