### ISSUE TITLE
DISM cmdlets not working in Powershell 7

### ISSUE THREAD

**Issue by blacklightpy** [PowerShell/PowerShell#15428]
## Steps to reproduce

Type
```
Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
```

## Expected behavior

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Administrator> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
```

## Actual behavior

```
PowerShell 7.2.0-preview.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\openssh> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
Get-WindowsCapability: Class not registered
```

## Environment data

Powershell 5.1 (working)

```
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.21376.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.21376.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Powershell 7 (installed from Store)
```
PS C:\openssh> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.21376
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
## Additional Notes

Referenced in Powershell/WindowsCompatibility#87
I wasn't sure if it was the right place to report this issue, so I'm reporting here.

**Comment by FuccDucc** [comment]
Just like this isn't working on Github powershell:

`Get-AppxPackage appname | Remove-AppxPackage`
Error:
```
Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
```

But it is working on Powershell.exe from `C:\Windows\System32\WindowsPowerShell\v1.0` (Built into Windows 10)

**Comment by TravisEz13** [comment]
I am not able to reproduce this issue
![image](https://user-images.githubusercontent.com/10873629/119909839-b60fd080-bf0a-11eb-91bf-052976c34f8d.png)
It looks like you are running an insider build of Windows.  The problem may be there.

**Comment by blacklightpy** [comment]
Yes, I was on build 21376, and I'm not on 21390 and it is still there.

Also, apparently it seems to recognize the command when I'm running without elevation.

```
PS C:\Users\Blacklight> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
Get-WindowsCapability: The requested operation requires elevation.
```
But this is different to the output on Powershell 5.1
```
PS C:\Users\Blacklight> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
Get-WindowsCapability : The requested operation requires elevation.
At line:1 char:1
+ Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
```

It's like Powershell 7 recognizes the cmdlet itself that it requires elevation, but doesn't know it's function.
I thought that was worth adding.

**Comment by davetapley** [comment]
@TravisEz13 I was able to repro this in a Windows 10 Pro VM on Azure (after installing Powershell 7):

(I was following [this guide](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)).

<img width="654" alt="Screen Shot 2021-11-23 at 1 16 00 PM" src="https://user-images.githubusercontent.com/48232/143097257-cddc77f3-9270-4318-80a7-fc2909ba85a0.png">

<img width="728" alt="Screen Shot 2021-11-23 at 1 19 12 PM" src="https://user-images.githubusercontent.com/48232/143097710-304fe1eb-5c65-4185-8252-34e387ae83ac.png">

**Comment by iSazonov** [comment]
This works well for me. Can you check on fresh Windows 10?

**Comment by blacklightpy** [comment]
> This works well for me. Can you check on fresh Windows 10?

I can't right now because I have a lot of apps required for work

**Comment by francogp** [comment]
If I run the command on OLD powershell, it works
![image](https://user-images.githubusercontent.com/2739706/152975331-6175d625-2eb7-4e64-89eb-1fda3480642b.png)

But If I use the new powershell, it fails
![image](https://user-images.githubusercontent.com/2739706/152975433-216825b8-114d-4891-a874-05a2f64b00fb.png)

**Comment by jgwinner** [comment]
I can duplicate this issue on Windows 11 and just updated last night. It's quite irritating as I can't get VS Code SSH setup for a critical work issue.

It takes QUITE a long time as well.

**Comment by doctordns** [comment]
Running latest Insiders Win 11 build (22557) and it works as expected:
```powershell
PS C:\Foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22557
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.1}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Foo> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
```

**Comment by jgwinner** [comment]
Why is this closed? It's still a bug.

**Comment by jgwinner** [comment]
@doctordns Interesting, as near as I can tell our versions were identical. I don't use PS that much (I use JPSoft's TCC), so maybe there's something you've installed that I didn't - that Get-WindowsCapability doesn't check for but relies on.

**Comment by Dyvergence** [comment]
I am able to reproduce with PowerShell installed using the msixbundle, but not installed using the MSI (the service error can safely be ignored as a result of running in Windows Sandbox).
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/100308708/180006662-6cf22a4c-6cc0-4aec-aa8f-3c455e35a0b7.png">
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/100308708/180007165-d2e8bcff-df57-4a14-9814-688bfd4f01bd.png">

**Comment by doctordns** [comment]
The DISM module is a Windows PowerShell module, NOT a PowerShell 7 module. 

I see this:
```powershell

PS C:\Foo> Get-WindowsCapability -Online | ft

Name                                                                State
----                                                                -----
Accessibility.Braille~~~~0.0.1.0                               NotPresent
Analog.Holographic.Desktop~~~~0.0.1.0                          NotPresent
App.StepsRecorder~~~~0.0.1.0                                    Installed
App.WirelessDisplay.Connect~~~~0.0.1.0                         NotPresent
Browser.InternetExplorer~~~~0.0.11.0                            Installed
DirectX.Configuration.Database~~~~0.0.1.0                      NotPresent
```

**Comment by jgwinner** [comment]
I see this, running in an elevated prompt:

```
PowerShell 7.2.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Windows\System32> Get-WindowsCapability -Online | ft
Get-WindowsCapability: Class not registered

PS C:\Windows\System32>
```

**Comment by jgwinner** [comment]
It's really simple. You should be able to install PowerShell 7, on a new machine, and it should work. If it doesn't, either it's not installing enough 'stuff' or the error message needs to indicate what does need to be installed. Empty stubs do no one any good.

My bets on a bad install program.

```
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.25158
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```

**Comment by doctordns** [comment]
That sounds like a borked Windows. Class not registered means that something is missing from your windows installation.  The DISM cmdlets are shipped with Windows and the installation should properly register any classes needed. 

One suggestion is an upgrade-install. Use the ISO of your current windows version and use it "upgrade" your existing installation. this should re-register the class. Or just do a fresh install and move on.

**Comment by jgwinner** [comment]
My windows is not borked. It _was_ a fresh install. 

It works fine for everything else.

YOUR windows looks like it's been upgraded over the years - you probably installed something a long time ago, that a fresh install doesn't install.

I installed OpenSSH another way, and everything is fine - and most other PowerShell things work fine. 

Have YOU tried a fresh install on a new box?

**Comment by WebTiger89** [comment]
Shit still happens with Powershell 7.2.6 installed as Appx package

**Comment by ModelsRUs** [comment]
I don't know why this issue is closed. I'm experiencing the same thing.
Windows 11 Pro.
Running PowerShell 7.3.0 in VS Code Terminal.
Statement: Get-WindowsDriver -online -all

> with Admn rights,  returns "Class not registered".
> without Admin rights:, returns "The requested operation requires elevation"

> running the same under PowerShell ISE ( 5.1.22000.832 ) as Administrator, I get output as expected.

**Comment by doctordns** [comment]
The reason the issue is closed (here) is that this is not a PowerShell issue. The module is/was a Windows PowerShell module. It appears in later versis of Windows, the module works fine (assumein elevation). This is not an issue we can fix.

**Comment by rez9x** [comment]
As this was the first result in a web search of this issue, I want to add how I resolved my issue. On a fresh install of Windows 11, I installed PowerShell 7 from the Microsoft Store. After reading Nytrona's comment, I removed the PowerShell install from the Microsoft Store and downloaded the MSI from Github. Both are 7.3.0, but the issue was resolved by installing the MSI instead.

This seems to be a Microsoft Store issue, not a PowerShell issue.

**Comment by jgwinner** [comment]
> The reason the issue is closed (here) is that this is not a PowerShell issue.

It certainly is - rez9x showed it's a PowerShell in the Microsoft Store issue. That's still a Microsoft issue.

Having an incorrect install I would think is still a PowerShell install. How does anyone else in the company know what to install if you guys don't give them the right install? Seems weird.

And you know, it doesn't matter if "it works on my machine" kind of crap. It's a MICROSOFT issue. If you're going to close a real issue, you should at least open another issue with the correct group.

This kind of "closed because it's not a problem" is utterly rife with the new Microsoft. What happened? You guys used to be a great company. 

Now, people complain endlessly about stupid crap that should be a trival fix and the attitude is "closed due to Triage" (that's not what Triage is!) or "not our problem".

It's all your problem. Fix your stuff. Somehow.

**Comment by Loki44** [comment]
So the official advice from microsoft, is to not trust the microsoft store to install things correctly?

**Comment by doctordns** [comment]
I suspect the best advice is that you have many ways to install PowerShell 7. Some come with limitations based on the underlying delivery mechanisms. You need to choose what is best for your organisation.

Personally, I use the `iInstall-PowerShell.ps1` script in this repo which gives me all the control I need over installation. 
Winget and Chocolatey are also methods you can use. Chocolatey even has cmdlets to simplify your journey. For simple use cases, you can also use a more locked-down version of PowerShell delivered via the Store. And if you are really hard-core, you can come here and get the release components directly from the source.

**Comment by rizolo** [comment]
I can confirm that using `winget install Microsoft.PowerShell`, after uninstalling the MS Store copy, that this does in fact let me use ` Get-WindowsOptionalFeature -Online`

**Comment by WebTiger89** [comment]
@rizolo That's because winget installs the .msi Version of Powershell. **But this issue is about the appx (UWP) version of powershell which can be obtained via Microsoft Store**. While the powershell appx version 5.1 works, Powershell 7.2.6 and 7.3.0-preview.8 don't. I didn't test the final powershell 7.3.0 version.

**Comment by WebTiger89** [comment]
@doctordns
There is enough evidence here that the UWP version does not work as expected.

It is fine if this topic is too complicated for you and you don't understand what is going on, but understand that this is a real issue that should be tackled but reopen this issue or remove powershell from store and or do not provide an UWP version.

**Comment by FuccDucc** [comment]
> And you know, it doesn't matter if "it works on my machine" kind of crap. It's a MICROSOFT issue. If you're going to close a real issue, you should at least open another issue with the correct group.
>
> This kind of "closed because it's not a problem" is utterly rife with the new Microsoft. What happened? You guys used to be a great company.

It's bureaucracy and that the teams within large companies don't really work together/communicate properly or at all..
Even after more than a year, Microsoft didn't accomplish to let the OS/Appx team, make a Microsoft product (that advertises itself as an improvement over the standard version) integrate properly. It's a failure of the chain or maybe the MS devs in github here are low level ones that don't have enough connections within the "real" company and can't break some barriers of team interoperability and cooperation. Of course, in the end, the result being produced is a symptom of lack of quality as a company, but the maintainers of this repo don't care enough and it's convenient to shove any such things with the thought "Not our problem / we dont get paid for this / there is invisible walls within Microsoft we cant break up, neither are we interested in looking at a solution for that"

**Comment by daxian-dbw** [comment]
Just FYI, the "Class not registered" error happens in PowerShell installed from MS Store is likely due to the registry virtualization applied to Store apps, see https://github.com/PowerShell/PowerShell/issues/13866#issuecomment-717568846. The issue is tracked by #13866, and this is the latest updates on that issue: https://github.com/PowerShell/PowerShell/issues/13866#issuecomment-1400708859

**Comment by Warrentheo** [comment]
I can confirm that deleting the msstore version corrected this issue for me.

**Comment by JunielKatarn** [comment]
Running this command **from Windows Powershell (Admin)** (not PWSH) worked, but it failed on the first attempt:

```pwsh
Add-WindowsCapability -Online -Name $someRsatFeature
```

**Comment by thegitworker** [comment]
Confirm 5 years later still an issue. I cannot run the `Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'` command in PowerShell 7.6.3. downloaded from the Microsoft Store. After uninstalling and installing PowerShell 7.6.3 from the MSI it works.

No idea why this is closed when the issue still exists.

**Comment by kilasuit** [comment]
Closing as duplicate of #13866 as whilst the cmdlets mentioned are different the underlying issue is the same
