### ISSUE TITLE
Get-ClusterParameter not accepting pipeline commands

### ISSUE THREAD

**Issue by simonwhybrow** [PowerShell/PowerShell#15422]
It seems within PowerShell v7.1 the Get-ClusterParameter function no longer correctly accepts certain functions being passed in via the pipeline.

Below is just one example, but from testing anything from Get-ClusterResource being passed in to Get-ClusterParameter fails with the same error.

## Steps to reproduce
Within PowerShell 7 the following command throws an error:
```powershell
> Get-ClusterResource -Name 'File Share Witness' | Get-ClusterParameter
```
## Expected behavior
The command being run in PS v5.1 outputs correctly:
```none
Object             Name             Value                           Type
------             ----             -----                           ----
File Share Witness SharePath        \\fileshare\cfsw\clustername    String
File Share Witness ArbitrationDelay 6                               UInt32
File Share Witness ImpersonateCNO   1                               UInt32
```

## Actual behavior
The below error is thrown in PS v7.1.1
```none
Get-ClusterParameter: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do
not match any of the parameters that take pipeline input.
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.1
PSEdition                      Core
GitCommitId                    7.1.1
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
It sounds like the `FailoverClusters` (module that contains these commands) haven't been marked as compatible with PSCore and thus runs in an implicit remoting session where any input/output are serialized. You can check this out by running the following to check the designated editions.

```powershell
Import-Module FailoverClusters -PassThru | Select Name, Version, CompatiblePSEditions
```

If it doesn't say `Core` then you will need to run all your commands in 1 session to ensure the type information isn't lost like so:

```powershell
$session = New-PSSession -UseWindowsPowerShell
$info = Invoke-Command -Session $session -ScriptBlock { Get-CluserResource -Name 'File Share Witness' | Get-ClusterParameter }
$session | Remove-PSSession
```

Anything in the `Invoke-Command` ScriptBlock is run in Windows PowerShell as well but instead of each individual command being run the whole pipeline is preserving the type information of the object.

**Comment by simonwhybrow** [comment]
@jborean93 thank you for that. You are correct in that the designated edition doesn't specify core.

Running in the single session does the job though, thank you.

Hopefully this will be rectified soon so that this workaround doesn't have to be applied when dealing with this particular function.

**Comment by jborean93** [comment]
I think the pwsh team are investigating allowing pipelined data in a proxy module like this automatically but I'm unsure if that's still on the cards. Unfortunately the real goal would be to have the `FailoverClusters` module updated/marked as `Core` compatible so it doesn't use the implicit remoting setup at all but that's down to the MS team who maintains that module :(
