### ISSUE TITLE
Parameter starting with colon (:) is expanded with working directory.

### ISSUE THREAD

**Issue by no1xsyzy** [PowerShell/PowerShell#15435]
Only happens when spawning other processes, any parameter starting with colon (`:`) is expanded with working dir if not wrapped by single quote (`'`).

I tried existing pre-release in this repo and found that the problem is between `v7.1.3..v7.2.0-preview.1`, though I do not have compiling environment at hand for bisecting deeper. `aur/powershell-preview-bin 7.2.0.preview.5-1` also bugs. [Results from ProcMon maybe help?](https://i.stack.imgur.com/GN9Vk.png)

More information can be found [here (SuperUser question)](https://superuser.com/questions/1650842/why-foo-expands-to-working-dir-foo).

## Steps to reproduce

```powershell
PS D:\path > cmd /c "echo" ":foo"
PS D:\path > cmd /c "echo" ':foo'
```

## Expected behavior

```none
:foo
:foo
```

## Actual behavior

```none
D:\path\:foo
:foo
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.4
PSEdition                      Core
GitCommitId                    7.2.0-preview.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@mklement0 Could you please clarify? Dup?

**Comment by mklement0** [comment]
@iSazonov: It's a bug in the experimental `PSNativePSPathResolution` feature; the duplicate is #13640

**Comment by no1xsyzy** [comment]
Yes, confirmed to be a duplicate. I think better to keep it for future search?

**Comment by iSazonov** [comment]
@no1xsyzy No need, cross-links already present.
