### ISSUE TITLE
Clear-Host does not clear the entire Windows Terminal after running Lee's rick-roll

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#15432]
## Steps to reproduce

```powershell
iex (New-Object Net.WebClient).DownloadString("http://bit.ly/e0Mw9w")
```

## Expected behavior

After terminating the rick-roll, executing `clear-host` should clear the entire console but it does not.  

## Actual behavior

This is my console right after executing `clear-host`:

![image](https://user-images.githubusercontent.com/5177512/119076385-b14d9880-b9af-11eb-861d-ca315c34fe92.png)

Notice that there is still text at the bottom of the screen.  I don't see this problem in the PowerShell console.  It appears that the script resets what PS thinks is the terminal size.  That actually resets the console size but that does not impact the Windows Terminal tab size.  Before running the script, PS sees the WIndows Terminal buffer/window size as:

```
BufferSize            : 121,68
WindowSize            : 121,68
```

After the script runs (and is aborted by pressing `Q`)) it is:

```
BufferSize            : 83,45
WindowSize            : 83,45
```

It would appear `Clear-Host` is operating on bad buffer/size data.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Related: #644

**Comment by 237dmitry** [comment]
> iex (New-Object Net.WebClient).DownloadString("http://bit.ly/e0Mw9w")

This is potentially dangerous.

**Comment by rkeithhill** [comment]
@237dmitry fair point.  I've attached Lee Holmes' script (with the sort alias corrected to sort-object) so folks can look at it before running it.  


[rick-roll.ps1.txt](https://github.com/PowerShell/PowerShell/files/6523954/rick-roll.ps1.txt)

**Comment by 237dmitry** [comment]
I have already downloaded the script by removing `iex` and writing output to a file, but it does not work in Linux

I tried to fix script, commented out all related to (for playing music):
- ComObject (unavailable)
- MTA (unavailable)

As a result I got a screen completely filled with similar lines `@;;;;;;;;+###@@@####++#######;;;;;';::;::,:;:::::#'`

**Comment by vexx32** [comment]
Yeah, the way it works isn't really cross platform. As far as I know there aren't really any readily-accessible APIs built into core .NET (or pwsh) that allow playing audio and are cross platform. 

The ASCII lines are how the script renders the "video" in the console. Not sure if there are discrepancies in the console on Linux, though. Hard to say without reworking the script a bit, I think. It wasn't written with an expectation to run on Linux, so it makes use of Windows-specific APIs a fair bit there.

**Comment by rkeithhill** [comment]
Yes, this is not a cross-platform issue.  The issue is specific to running the script within **Windows Terminal**, which causes `Clear-Host` to not work correctly afterwards.

**Comment by vexx32** [comment]
If this script is modifying the window size and not just the buffer size, and Windows Terminal is not respecting those changes properly, I don't think Clear-Host has much of a chance of working correctly.

I would probably expect that either:

- The script should be OK to change the buffer size, but changing the window size is an odd choice -- and in any case, it should properly restore the original window and buffer sizes once it is quit, OR
- This is either a console host issue, or a Windows Terminal issue, whichever end of that is responsible for the change in windowsize being ignored / not picked up on by Windows Terminal.

**Comment by rkeithhill** [comment]
Yup, a simple repro is to dump a bunch of text to the terminal (dir ~) and then execute:
```powershell
$host.UI.RawUI.WindowSize = New-Object System.Management.Automation.Host.Size 83,45
Clear-Host
```

**Comment by 237dmitry** [comment]
I at last tried the script in Windows in Windows Terminal Preview (v. 1.8.1032.0).  Clear-Host works without problem. pwsh 7.1.3

**Comment by rkeithhill** [comment]
I'm on the same version of both and see the issue - even with the simple repro above.

**Comment by 237dmitry** [comment]
Maybe `$profile`, `Prompt{}` and `settings.json` (config of wt) settings has some effect?

**Comment by rkeithhill** [comment]
Behaves the same with `-noprofile`.

**Comment by 237dmitry** [comment]
I think this code has to be executed in call-block to avoid the remaining variables. You also need to return the default state of the esc-sequences:
```
& { iex (New-Object Net.WebClient).DownloadString("http://bit.ly/e0Mw9w") }; "`e[0m"
```
If just run the script it leaves many variables, you could see them `dir variable:`
They did not appear immediately, but then they made themselves felt in the form of white background stripes.

**Comment by 237dmitry** [comment]
In my opinion, this script is not written neatly. It leaves a lot of garbage behind.

**Comment by rkeithhill** [comment]
@237dmitry ignore the script. This issue is really about why the following breaks `Clear-Host` functionality in Windows Terminal:
```powershell
dir C:\Windows
$host.UI.RawUI.WindowSize = New-Object System.Management.Automation.Host.Size 83,45
Clear-Host
```

**Comment by 237dmitry** [comment]
This is issue to team of Window Terminal. In standard host window changed its size but not in WT or Alacritty.

![ss-20210522024053](https://user-images.githubusercontent.com/78153320/119207562-43849800-baa7-11eb-817a-90e144cddd96.png)

**Comment by theJasonHelmick** [comment]
The interactive WG has reviewed this issue.  We can repo the issue and it appears that .NET is properly being set, however this is not being respected by the Windows Terminal.  For future problems in this area, please file an issue with the Windows Terminal team.
