### ISSUE TITLE
Script PowerShell

### ISSUE THREAD

**Issue by betopicapiedra** [PowerShell/PowerShell#15448]
**_Hello, where can I download the PowerShell 7 script
which allows me to put PowerShell in the context menu
I want to implement it but for the PowerShell that it brings by default
Windows 10_**

**Comment by daxian-dbw** [comment]
The functionality is already available in the MSI installer.

![image](https://user-images.githubusercontent.com/127450/119554574-b022bf80-bd51-11eb-8fac-502c32f57d03.png)

**Comment by betopicapiedra** [comment]
**### I do not intend to use PowerShell 7
I want to use the PowerShell that comes by default
windows 10, that's why I want the script to try to adapt it to the PowerShell that it brings by default
windows 10**
