### ISSUE TITLE
Feature Request: New-ScheduledTaskTrigger should be able to create Monthly schedules

### ISSUE THREAD

**Issue by kaiser-roy** [PowerShell/PowerShell#15446]
## Summary of the new feature/enhancement
As a user I want to programmatically create scheduled tasks that run on e.g., the 5th of the month, or say, the 3rd Tuesday. So that I can fully automate my scheduled job creation.  Currently New-ScheduledTaskTrigger allows the creation of daily and weekly schedules, but not monthly.

## Proposed technical implementation details (optional)

Example powershell experience:
`ps> $act = New-ScheduledTaskAction -Execute "calc.exe"`
`ps> $sch = New-ScheduledTaskTrigger -Monthly -At 3pm -DaysOfMonth 5 # Jan 5th, Feb 5th, etc.`
`ps> Register-ScheduledTask -Action $act-Trigger $sch -TaskName 'My task name'`

**Comment by TravisEz13** [comment]
This is a windows powershell cmdlet.  Please file a uservoice issue per the bug template:
Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)
