### ISSUE TITLE
Investigate fixing CA1822: Mark members as static

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15455]
With .NET 6 preview 4, we are getting new warnings about CA1822: Mark members as static. 

Please look at: https://github.com/PowerShell/PowerShell/pull/15452/commits/efa4495a7466df5c4b5ec71f0ac4c722c796efce for files with warning disabled.

Investigation is needed on finding out how to fix these.

## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by iSazonov** [comment]
All the warnings are for Microsoft.Management.UI.Internal which is frozen. So we can suppress the warnings in csproj file.
