### ISSUE TITLE
Investigate fixing IDE1005: Delegate invocation can be simplified.

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15457]
With .NET 6 preview 4, the SDK is showing warning about IDE1005: Delegate invocation can be simplified.

We need to investigate and fix the warnings. 

The commit which disabled the warning is at: https://github.com/PowerShell/PowerShell/pull/15452/commits/356643696e5996bc6e0089a0fbcd89f75e0162de

## Steps to reproduce

```powershell

```

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by iSazonov** [comment]
All the warnings are for Microsoft.Management.UI.Internal which is frozen. So we can suppress the warnings in csproj file.

**Comment by adityapatwardhan** [comment]
Maintainers are fine suppressing the warning as the code is not under current development and we do not want to take any changes unless absolutely needed.
