### ISSUE TITLE
ConvertTo-CSV not escaping backslash

### ISSUE THREAD

**Issue by vdurante** [PowerShell/PowerShell#15453]
## Steps to reproduce

```powershell
$data= @(
    @{Name="Peter";Country="USA";Age="25"},
    @{Name="Marco";Country="Brazil\";Age="20"},
    @{Name="Maria";Country="Mexico";Age="45"}) | % { New-Object object | Add-Member -NotePropertyMembers $_ -PassThru }
$data | ConvertTo-CSV
```

## Expected behavior

Backslash should be escaped when using a delimiter, specially when the field ends in backslash
```none
"Name","Age","Country"
"Peter","25","USA"
"Marco","20","Brazil\\"
"Maria","45","Mexico"
```

## Actual behavior

Backslash is not escaped, therefore it breaks csv parsers/readers 
```none
"Name","Age","Country"
"Peter","25","USA"
"Marco","20","Brazil\"
"Maria","45","Mexico"
```

**Comment by 237dmitry** [comment]
> not escaping backslash

Should it? I didn't find a specification of the CSV format (rfc4180) where this would be indicated.

>  Fields that contain a special character (comma, CR, LF, or double quote), must be "escaped" by enclosing them in double quotes (Hex 22)

**Comment by iSazonov** [comment]
What is Excel behavior?

**Comment by vdurante** [comment]
You guys are correct! I guess this is the correct behavior. Thank you!
