### ISSUE TITLE
PowerShell 7.1 "Operating System" attribute is empty in Azure Active Directory

### ISSUE THREAD

**Issue by larnera** [PowerShell/PowerShell#15468]
We have a AAD Conditional Access Policy in place which blocks unknown operating systems for our enterprise apps and users. 

When using PowerShell 7.1.3, the operating system is showing as empty in "device info" under the "sign-in log within AAD. This has resulted in blocking access to our Enterprise App (SharePoint PnP PowerShell). 

![image](https://user-images.githubusercontent.com/2369339/119807504-1a1aa080-bedb-11eb-8676-c81949f78245.png)

When we use PowerShell 5.1, the operating system; "Windows 10" is shown and access is granted to our Enterprise App. 

![image](https://user-images.githubusercontent.com/2369339/119807613-37e80580-bedb-11eb-8a89-6594b4f0f499.png)

## Steps to reproduce

1. Create a "Block Access" Conditional Access Policy in AAD with "device platform" condition set to:

Include = "any device"
Exclude = "Android, iOS, Windows Phone, Windows, macOS"

![image](https://user-images.githubusercontent.com/2369339/119807394-03744980-bedb-11eb-8019-300e8f09b35f.png)

2. in PowerShell 7, run command: Connect-PnPOnline -Url https://www.xxxxxxxx.com/sites/commsSite -Credentials (Get-Credential)
3. Enter credentials

## Expected behaviour

Access token is provided.

## Actual behaviour

Access token is not provided:

```none
Connect-PnPOnline: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.
Trace ID: a99d8841-0ad6-4d71-b9a5-c602ee844301
Correlation ID: 79c2241b-37af-4ff2-9e66-fe0e2d4c0f81
Timestamp: 2021-05-27 09:50:37Z

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
Connect-PnpOnline is in this repo:  https://github.com/pnp/powershell
They would need to make the change to address this.

**Comment by larnera** [comment]
> Connect-PnpOnline is in this repo: https://github.com/pnp/powershell
> They would need to make the change to address this.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/296298081/933a6d00-072b-11eb-839d-56df16c29588"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[pnp/powershell](https://github.com/pnp/powershell)**PnP PowerShell. Contribute to pnp/powershell development by creating an account on GitHub.

Thanks Travis. I'll raise there but thought this would have been an issue with PowerShell rather than PnP given previous versions worked fine.

**Comment by larnera** [comment]
Can this be re-opened please @TravisEz13? [Other modules](https://github.com/pnp/powershell/issues/737#issuecomment-855823402) experience the same issue when using PowerShell 7.1.

**Comment by TravisEz13** [comment]
I updated the issue you opened and explained what they are doing wrong.  I have no idea what the fix is, but it is in that module.

**Comment by larnera** [comment]
Thanks @TravisEz13 for investigating the issue.

**Comment by TravisEz13** [comment]
@larnera no problem
