### ISSUE TITLE
Feature Request : Tail and watch like functionality

### ISSUE THREAD

**Issue by colin-small** [PowerShell/PowerShell#15462]
I would love to have functionality in Powershell similar to the Linux tail command. This would be very useful to monitor various files (logs, etc..) in somewhat real-time.

Something similar to the "watch" command in Linux would also be very useful.

[https://en.wikipedia.org/wiki/Tail_(Unix)](https://en.wikipedia.org/wiki/Tail_(Unix))

[https://en.wikipedia.org/wiki/Watch_(command)](https://en.wikipedia.org/wiki/Watch_(command))

**Comment by 237dmitry** [comment]
```
Try   { Get-Content -Tail 5 -Wait file.ext -ErrorAction 1 }
Catch { "File not exist or deleted" }
```
