### ISSUE TITLE
SSH MOTD repeated on connection

### ISSUE THREAD

**Issue by needs-coffee** [PowerShell/PowerShell#15473]
## Steps to reproduce
- install OpenSSH client for windows - either the windows release through add/remove features, or latest binary from [repo](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/V8.6.0.0p1-Beta)
- open powershell core (v7+) directly and ssh to a linux server with `ssh 192.168.50.55`
- The provided MOTD from the server is either printed once (as intended) or repeated twice. 
- This does not happen on every connection but will reliably happen every few connections.
- This does not happen from windows CMD, powershell (native windows installed version), PuTTY or any linux client. 
- Occurs on multiple servers with different distros, OpenSSH server versions and configurations.
- This does not happen from powershell core when opened from within windows terminal - only from the native executable. 
- This happens on the included openssh version 8.1 and the latest binary release 8.6 (which included a fix from the ssh side for this in Powershell/Win32-OpenSSH#1736 )
- This does not happen when the Powershell core window is maximised - it only happens when in a non maximised window

## Expected behavior
SSH MOTD is printed once and only once on connection.

## Actual behavior
SSH MOTD is printed once or twice on connection to a linux server when opened from powershell core. 

## Environment data
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2 
OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3 (8.6.0.0)
Connecting to - Debian Buster, Ubuntu 20.04, Ubuntu 18.04, raspbian buster

```
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.6
PSEdition                      Core
GitCommitId                    7.2.0-preview.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

EDIT - 
added further details about commands used.

**Comment by TravisEz13** [comment]
Please provide the command you use to
> ssh to a linux server.
in your repro

**Comment by needs-coffee** [comment]
> Please provide the command you use to
> in your repro

`ssh 192.168.50.54 `and edited initial post to reflect this

**Comment by bytos** [comment]
Using OpenSSH portable 8.6.0.0 on Windows 10 and seeing MOTD posted twice when connecting to a RPi.

**Comment by needs-coffee** [comment]
Using powershell with windows terminal and the latest OpenSSH i have not noticed this happening again. 
This issue still may exist when using CMD natively but with the state of windows terminal i dont see a need to put effort into fixing this.
Closing
