### ISSUE TITLE
git command fails in PWSH and does not in CMD

### ISSUE THREAD

**Issue by KoleckOLP** [PowerShell/PowerShell#15479]
## Steps to reproduce
1. create a repository with git
2. try `git reset HEAD@{0}` --this should reset the repo at current head, which does notthing but demontrates my issue
in CMD.EXE the command runs fine and you get no output
in PWSH.EXE (7.1.3):
```
PS D:\dokumenty\okurz\Github\pyCrypt> git reset HEAD@{0}
error: unknown switch `e'
usage: git reset [--mixed | --soft | --hard | --merge | --keep] [-q] [<commit>]
   or: git reset [-q] [<tree-ish>] [--] <pathspec>...
   or: git reset [-q] [--pathspec-from-file [--pathspec-file-nul]] [<tree-ish>]
   or: git reset --patch [<tree-ish>] [--] [<pathspec>...]
   or: DEPRECATED: git reset [-q] [--stdin [-z]] [<tree-ish>]

    -q, --quiet           be quiet, only report errors
    --mixed               reset HEAD and index
    --soft                reset only HEAD
    --hard                reset HEAD, index and working tree
    --merge               reset HEAD, index and working tree
    --keep                reset HEAD but keep local changes
    --recurse-submodules[=<reset>]
                          control recursive updating of submodules
    -p, --patch           select hunks interactively
    -N, --intent-to-add   record only the fact that removed paths will be added later
    --pathspec-from-file <file>
                          read pathspec from file
    --pathspec-file-nul   with --pathspec-from-file, pathspec elements are separated with NUL character
    -z                    DEPRECATED (use --pathspec-file-nul instead): paths are separated with NUL character
    --stdin               DEPRECATED (use --pathspec-from-file=- instead): read paths from <stdin>
```

## Environment data

<pre>
PS D:\dokumenty\okurz\Github\pyCrypt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

</pre>
This bug prevents me from using powershell 7 as my default shell.

**Comment by iSazonov** [comment]
I gues dup #15289

**Comment by KoleckOLP** [comment]
I experimented but more and

to o run ``git show @^`` you need to type 
```git show `@^``` or ```git show '@^'```

and to run ``git reset HEAD@{1}`` you need to run 
```git reset HEAD@`{0`}``` or ```git reset 'HEAD@{0}'```

**Comment by kilasuit** [comment]
@KoleckOLP I'd recommend using this syntax instead `git reset HEAD~1` as this 100% works in PowerShell as I've used it for years
