### ISSUE TITLE
Formatting data for strings or when redirecting to a file should not be affected by the console width

### ISSUE THREAD

**Issue by vexx32** [PowerShell/PowerShell#15474]
## Summary of the new feature/enhancement

Currently, `Out-File`, `Out-String`, `>`, and `>>` all use the current console width when formatting data. This can cause a lot of truncation and loss of data, especially when logging.

See #15404 for additional context.

## Proposed technical implementation details (optional)

The default behaviour when formatting data for a string or when sending data to a file should be to format as though the console width is near-infinite. So, these should all function without truncating the data:

```powershell
Get-ChildItem | Format-Table -Property * | Out-String
Get-ChildItem | Format-Table -Property * | Out-File -Path $filePath
Get-ChildItem | Format-Table -Property * > $filePath
Get-ChildItem | Format-Table -Property * >> $filePath
```

Users could still customize the width in the case of using `Out-String` or `Out-File` specifically, but our default for these cases should be arbitrarily large to avoid unnecessarily truncating data.

**Comment by iSazonov** [comment]
Can we have/use Write-* cmdlets?

**Comment by vexx32** [comment]
Not entirely sure what you're suggesting @iSazonov; can you elaborate? 🙂

**Comment by rkeithhill** [comment]
I posted an [initial PR](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/7656) with proposed wording for 7.2.  Want to solidify that wording before adding it to previous versions.

**Comment by rkeithhill** [comment]
After doing some experiments, I do not think we want to attempt to use a "near infinite" width based on impact to performance.  

![image](https://user-images.githubusercontent.com/5177512/121062645-94bca900-c782-11eb-9b0e-1695821f4cf4.png)

**Comment by iSazonov** [comment]
Uh! If we set the width to int.MaxValue we will create every output line with the width (with huge spaces in tail)!

**Comment by vexx32** [comment]
Does it? If so, I'd consider that a bit of a bug tbh. -Width should be an upper bound, not a forced padding imo.
