### ISSUE TITLE
File system provider should find a hidden file if the path to the file is explicitly specified

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#15477]
## Summary of the new feature/enhancement

Originated from #15323

For a hidden file `C:\arena\tmp\hiddenFile.xml`, both `Get-Item` and `Get-ChildItem` cannot find the file even if the path to the file is explicitly specified:
```
PS:1> Get-Item C:\arena\tmp\hiddenFile.xml
Get-Item: Could not find item C:\arena\tmp\hiddenFile.xml.
PS:2> Get-ChildItem C:\arena\tmp\hiddenFile.xml
Get-ChildItem: Could not find item C:\arena\tmp\hiddenFile.xml.
```

Today, `-Force` parameter is required for the above commands to work.

However, on the other hand:
1. tab completion on the hidden file works fine for those cmdlets.
  ```
       PS:1> Get-Item hiddenF<tab> # => Get-Item .\hiddenFile.xml
  ```
2. `Get-ChildItem` works on hidden folders. 
  ```
        PS:1> Get-ChildItem -Hidden

            Directory: C:\arena\tmp

        Mode                 LastWriteTime         Length Name
        ----                 -------------         ------ ----
        d--h-           5/27/2021  7:07 PM                hiddenFolder
        -a-h-           5/18/2021  9:15 PM          63571 hiddenFile.xml

        PS:2> Get-ChildItem .\hiddenFolder

            Directory: C:\arena\tmp\hiddenFolder

        Mode                 LastWriteTime         Length Name
        ----                 -------------         ------ ----
        -a---           5/27/2021  7:07 PM              0 abc.txt
  ```

The inconsistency add confusion to the current behavior. It would be good to make the `FileSystemProvider` able to find a hidden file without requiring `-Force`, if the path to the file is explicitly specified.

## Proposed technical implementation details (optional)

The proposed the behavior change is:
__when the path to a hidden file is explicitly specified (no wildcards in play), `Get-Item` and `Get-ChildItem` should be able to find that file without requiring the `-Force` parameter.__

The change would be in the `FileSystemProvider` code. This behavior change should kick in only when the specified path is an explicit path to a hidden file. When the specified path contains wildcards, the current behavior should be kept -- hidden files are not returned without the `-Force` parameter.

Also, see @mklement0's thoughts on the fix: https://github.com/PowerShell/PowerShell/issues/15323#issuecomment-831991311

**Comment by iSazonov** [comment]
What is _hidden_ flag for? Hidden conception is "_exclude file system objects from file system tree (not content!) manipulations_".
So the PowerShell behavior:
> For a hidden file C:\arena\tmp\hiddenFile.xml, both Get-Item and Get-ChildItem cannot find the file even if the path to the file is explicitly specified

is consistent with this concept and is correct.

**Comment by rkeithhill** [comment]
On Linux, dot-prefixed files are hidden and not shown by `ls` by default.  But if I specify `ls .profile`, ls will show the file even though it is hidden.  On Windows, File Explorer may not show AppData or ProgramData by default but if I type that path into the address bar, File Explorer will then happily show the contents of the "hidden" dir.

**Comment by iSazonov** [comment]
In both cases it is an established behavior that has been there for many years.
Why not then change the behavior of ls? It is the one that raises more doubts. The references to ls look like speculation.

As far as PowerShell is concerned, this is a breaking change which is dangerous. And the right question here is what types of business scripts are blocked or forced to be expensive? I don't know of any and can't think of any.

The PowerShell behavior seems conceptually correct and safer.

**Comment by iSazonov** [comment]
cmd.exe doesn't show hidden files by default.
