### ISSUE TITLE
Windows arm64 installation via winget

### ISSUE THREAD

**Issue by Alovchin91** [PowerShell/PowerShell#15481]
## Summary of the new feature/enhancement

As a user I want to use `winget` to install PowerShell arm64 on my Surface Pro X / Snapdragon Development Kit.

## Proposed technical implementation details (optional)

Currently the implementation is blocked by either #12116 or https://github.com/microsoft/winget-cli/issues/140. Whichever is implemented first could unblock this story.

**Comment by iSazonov** [comment]
I can track this in #12116
