### ISSUE TITLE
Color and Text properties not getting restored properly

### ISSUE THREAD

**Issue by rashil2000** [PowerShell/PowerShell#15484]
## Steps to reproduce

This is a bug that was recently discovered through a module - [GuiCompletion](https://github.com/nightroman/PS-GuiCompletion), in nightroman/PS-GuiCompletion#5.

The premise is that `GetBUfferContents` and `SetBufferContents` do not fetch and restore all color and text properties properly. See the attached GIF there for a look.

## Environment data

This occurs on both Windows PowerShell and PowerShell Core.

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by theJasonHelmick** [comment]
@rashil2000 - Thanks for reporting this issue - It does seem to be a bug. Let me get @SteveL-MSFT and @daxian-dbw to review.

**Comment by SteveL-MSFT** [comment]
The problem is that `GetBufferContents()` doesn't understand ANSI.  It only works for `[ConsoleColor]` really.  Internally, it's calling `GetConsoleScreenBufferInfo()` which returns a `CONSOLE_SCREEN_BUFFER_INFO` which is limited to certain [attributes](https://docs.microsoft.com/en-us/windows/console/console-screen-buffers#character-attributes).

The win32 API would need to change to give the full set of attributes supported by ANSI.  Best bet would be to ask the https://github.com/Microsoft/Terminal folks (which also owns conhost) to support this.

**Comment by rashil2000** [comment]
Sorry if it may sound trivial, but I have a couple of doubts.
Is it not possible for `GetConsoleScreenBufferInfo()` to use the new Virtual Terminal Sequences for these scenarios? 
Isn't it unlikely that Windows Console APIs would be changed to accommodate this when using VT is the current recommended way for use in commandline applications (as outlined [here](https://docs.microsoft.com/en-us/windows/console/classic-vs-vt))?

**Comment by SteveL-MSFT** [comment]
@rashil2000 it's certainly possible for the api to be updated but it's an api owned by the console team hence pointing to their repo

**Comment by rashil2000** [comment]
Oh, okay.
Will this be communicated internally or should I open the issue in their repo, pointing to the discussion here?
