### ISSUE TITLE
Invoke-command  to windows session to get-item return not right 

### ISSUE THREAD

**Issue by guijunhua** [PowerShell/PowerShell#15493]
HI， I use powershell 7.1.3 to Invoke-command to windows server 2016, the server use windows powershell 
cmmand is :

Invoke-Command  -Session $Session -ScriptBlock {      Get-Item -Path "C:\Zabbix"  }

the return is wrong . 
it is worked on windows powershell to to windows powershell 
![BUG](https://user-images.githubusercontent.com/32589055/120130462-da182e00-c1f8-11eb-966b-dbd45cd08c18.png)

## Environment data
7.1.3

```none

```

**Comment by iSazonov** [comment]
It seems we already have such issue registered in the repo for years.

**Comment by jborean93** [comment]
Some fun spelunking here https://github.com/PowerShell/PowerShell/issues/10759 and https://github.com/PowerShell/PowerShell/issues/11400.
