### ISSUE TITLE
Set $matches variable to $null when -match returns $false

### ISSUE THREAD

**Issue by nmbell** [PowerShell/PowerShell#15494]
## Steps to reproduce

```
'cat','dog','hamster' | ForEach-Object { $null = $_ -match 'a'; If ($matches) { Write-Host "$_ has an 'a' in it." } }
```

## Expected behavior

```
cat has an 'a' in it.
hamster has an 'a' in it.
```

## Actual behavior

```
cat has an 'a' in it.
dog has an 'a' in it.
hamster has an 'a' in it.
```
To get the correct results, $matches must be explicitly set to $null before matching:
```
'cat','dog','hamster' | ForEach-Object { $matches = $null; $null = $_ -match 'a'; If ($matches) { Write-Host "$_ has an 'a' in it." } }
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
I think this makes sense... though depending on the implementation it might end up being something like forcibly calling `$matches.Clear()` before populating the hashtable with the new entries instead.

I'm not sure if folks would expect / depend on the current behaviour, though, so it has potential to break things that currently work -- although I guess you could argue it's almost working by accident at that point.

Would be nice to lock down the behaviour a bit more and ensure consistency this way, though. 🤔

**Comment by iSazonov** [comment]
Interesting, what is a scope where $matches lives?

**Comment by vexx32** [comment]
That's a good question. If you inspect `$matches` in a brand new PS session, it is actually null. That seems to indicate to me that it's not an automatic variable, just that it's set in the current scope when `-match` is used.

Not an exhaustive investigation, but that's my bet until I've had time to look through the code 😁

**Comment by SeeminglyScience** [comment]
Usually you'd do something like this:

```powershell
if ($in -match 'pattern') {
    $matches
}
```

Not sure what the point would be to null out the boolean value and then test `$matches` specifically.  Either way it's very likely that folks are depending on the current behavior.

**Comment by iSazonov** [comment]
By default the `$Matches` is defined in global scope.

**Comment by SeeminglyScience** [comment]
@iSazonov Looks like current scope

```powershell
& {
    'test' -match 'e'

    # Nothing
    $global:matches

    # Something
    $matches
}

# Nothing
$matches
```

**Comment by iSazonov** [comment]
I tested from command prompt and gets the result in global but more correct test is:
```powershell
& {
'cat','dog','hamster' | ForEach-Object { $null = $_ -match 'a'; If ($matches) { Write-Host "$_ has an 'a' in it." } }
    # Nothing
    $global:matches

    # Something
    $matches
}

# Nothing
$matches
```
This show the cmdlet processes all iterations in the same nested scope. So the behavior is by design but I think this operator should recreate this variable every time, even if the search fails.

**Comment by jhoneill** [comment]
> Not sure what the point would be to null out the boolean value and then test `$matches` specifically. Either way it's very likely that folks are depending on the current behavior.

I'd say one *should* use the boolean returned here's a trivial bit of code which would break if matches was nulled out by the operator. 
```powershell
$items = 'cat','dog','hamster','mouse'; 
foreach ($i in $items) { $null = $i -match '^.*a.*$'} 
Write-Host "Last match was $($matches[0])"
```

`Last match was hamster`

**Comment by nmbell** [comment]
From the [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.1#-match-and--notmatch):

> `-match` and `-notmatch` support regex capture groups. Each time they run, they overwrite the `$Matches` automatic variable. When `<input>` is a collection the `$Matches` variable is `$null`.

I don't think the current behavior is consistent with these statements.

**Comment by jhoneill** [comment]
> From the [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.1#-match-and--notmatch):
> 
> > `-match` and `-notmatch` support regex capture groups. Each time they run, they overwrite the `$Matches` automatic variable. When `<input>` is a collection the `$Matches` variable is `$null`.
> 
> I don't think the current behavior is consistent with these statements.

The docs should be clearer, I think more people reading that would interpret it as the variable is cleared / overwritten with _nothing_ , than would say 'overwrite' only applies when there is a value.

**Comment by rkeithhill** [comment]
At the very least, the docs on `-match` should be updated to be clearer on the $Matches behavior.  This paragraph on `-notmatch` is clearer on the matter (except for the typo):

> The -notmatch operator populates the $Matches automatic variable when the
input is scalar and the result is False, that it, when it detects a match.

**Comment by iSazonov** [comment]
If anybody wants to grab and pull PR https://github.com/iSazonov/PowerShell/commit/c1bad4141f136f25e1f20e1990f69c3b77ff38c0

**Comment by rkeithhill** [comment]
The `WG-Engine` group reviewed this and agrees that the documentation should be updated to match the current behavior.  We do not want to change the current behavior because that would be a breaking change.  The documentation changes can be viewed [here](https://github.com/MicrosoftDocs/PowerShell-Docs/commit/3800e988213a0282552ca6d47e608c412c577225#diff-ed087a39474c8097c9b116de7f2d59dedd2b6ecedc5cb53749c79abe101a298e).
