### ISSUE TITLE
Powershell keeps trying to connect to telemetry

### ISSUE THREAD

**Issue by JayDoubleu** [PowerShell/PowerShell#15495]
## Steps to reproduce

- Open powershell
- See it trying to connect to microsoft servers

## Expected behavior

powershell should not be trying to connect anywhere

## Actual behavior

powershell tries to connect to microsoft servers when launched even with `POWERSHELL_TELEMETRY_OPTOUT` environment variable set to 1.

Even if single IP address gets blocked, soon it tries another one for example `95.101.18.109`. Blocked 5 so far and it keeps finding new ones.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
In ApplicationInsightsTelemetry() we do nothing if POWERSHELL_TELEMETRY_OPTOUT is 1.
If only ApplicationInsights itself does something in shadow.

**Comment by vexx32** [comment]
How are you setting that environment variable? Depending on the scope you set the variable at, you may need to reboot the machine or log off and log on again before it is properly picked up by new processes.

**Comment by JayDoubleu** [comment]
I do have the `POWERSHELL_TELEMETRY_OPTOUT` set to 1 on both System and User variables (Under usual guy used for environment variables in windows 10)
Even after reboot powershell is still trying to connect to number of addresses.

**Comment by badrelmers** [comment]
Maybe this connection is made by the update check not telemetry. add this to disable updates and see
POWERSHELL_UPDATECHECK=Off

I m using this variables before starting powershell and not connection is made:
```batch
set POWERSHELL_TELEMETRY_OPTOUT=1
set DOTNET_TELEMETRY_OPTOUT=1
set POWERSHELL_CLI_TELEMETRY_OPTOUT=1
set DOTNET_CLI_TELEMETRY_OPTOUT=1

set POWERSHELL_UPDATECHECK=Off
```

**Comment by leojonathanoh** [comment]
there really ought to be better documentation on this.

**Comment by iSazonov** [comment]
It is documented already.

**Comment by leojonathanoh** [comment]
i must be missing it then. i've only found docs on `POWERSHELL_TELEMETRY_OPTOUT`, the other env vars in https://github.com/PowerShell/PowerShell/issues/15495#issuecomment-941928682 are scattered around issues.

**Comment by iSazonov** [comment]
POWERSHELL_TELEMETRY_OPTOUT and POWERSHELL_UPDATECHECK are documented in PowerShell docs.
Others are .Net env variables and are documented in .Net docs.

**Comment by leojonathanoh** [comment]
what i mean is that something as basic as a few things that new users might not be aware of, that affects startup speed, should at least be well part of a FAQ of this repo. Even as a powershell for a few years now, i don't always look at the official powershell docs for docs on stuff. And the fact that this issue is still open, shows there is an apparent documentation issue. I don't think i'm the only one that that feels the docs should be more elaborate.

**Comment by iSazonov** [comment]
You can request this in https://github.com/MicrosoftDocs/PowerShell-Docs

**Comment by JamesWTruher** [comment]
engine WG:
we're not sure what's happening here, however, there may be other reasons for external connections to be made.
If you've opted out of telemetry via `$env:POWERSHELL_TELEMETRY_OPTOUT = 1` we won't even _initialize_ the telemetry client.  Please note that this variable must be set _before_ PowerShell is started.
There's a pretty simple way to determine whether you have disabled PowerShell telemetry.
Please run the following script and let us know the results. It will tell you whether telemetry is enabled and whether the telemetry client is initialized.

```powershell
$bf = [reflection.bindingflags]"NonPublic,Instance,Static,Public"
$aIT = [Microsoft.PowerShell.Telemetry.ApplicationInsightsTelemetry]
$canSendTelemetry = $aIT.GetMethod("get_CanSendTelemetry",$bf).Invoke($null,$null)
$telemetryClient = $aIT.GetMethod("get_s_telemetryClient", $bf).Invoke($null, $null)
[pscustomobject]@{
    SendTelemetry = $canSendTelemetry
    ClientInitialized =  $telemetryClient -ne $null
}
```

if SendTelemetry and ClientInitialized are true, it means that we didn't see the proper values in the variable.
