### ISSUE TITLE
Add new analyzer rules

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#15498]
We need to add new Microsoft.CodeAnalysis.NetAnalyzers rules 
See https://github.com/dotnet/runtime/commit/72ff0df4638ced1cc2b15c92c055f842c51e32d2

/cc @xtqqczze

**Comment by xtqqczze** [comment]
I think we should take a different approach to dotnet/runtime#53158 and add the rules in a separate PR. We can enable any rules later.
