### ISSUE TITLE
Invoke-WebRequest not returning forms or parsedhtml

### ISSUE THREAD

**Issue by nchurkin** [PowerShell/PowerShell#15500]
## Steps to reproduce

```powershell
$r = Invoke-WebRequest -Uri 'https://github.com/login'
$r.Forms[0]
```

## Expected behavior
```powershell
Id Method Action   Fields
-- ------ ------   ------
   post   /session {[authenticity_token, ncCnggrETXXZRpc1xgyg6PNDhDi4SEYLKNlGftdSZCfd7ZmfC1x0jdGA28ICG/6UvNGZreSuyQ==], [login_field, ...
```

## Actual behavior
No forms property.
```powershell
```

## Environment data
```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
These features are solely reliant on Internet Explorer and thus not cross-platform compatible. The Invoke-WebRequest cmdlet was completely rewritten back in version 6.x for cross-platform compatibility, so it no longer supports those features.

If you want to scrape the HTML in a structured matter, you might want to look at using Selenium, which can let you analyse a webpage directly and pull back whatever information you might need.
