### ISSUE TITLE
Variables in using instruction

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#15514]
## Summary of the new feature/enhancement
Add ability to use environment variables in `using assembly` instruction. In case of loading from custom assembly location and in order to not writing full path.

## Proposed technical implementation details (optional)
For example:
```
using assembly $HOME\libs\taglib-sharp\taglib-sharp.dll
```

**Comment by SeeminglyScience** [comment]
`using` is a parse time concept, so unless the variable is a true constant (which PowerShell doesn't really have) that wouldn't work very well.

You can however do *script* relative paths with `using assembly ./lib/something.dll`.  In a `using` statement that switches from current directory relative to script relative (confusing I know).

**Comment by 237dmitry** [comment]
> parse time concept

Sorry, I did not understand phrase, tried to translate, but I didn't catch the exact meaning.
Ok, if `using` is a just concept then `Add-Type` is more flexible variant.

**Comment by vexx32** [comment]
`using` statements are resolved before any code is actually executed, in most cases. PowerShell reads the script top to bottom and processes it, and it's during this step, before it actually runs any of the code, that these statements are processed and resolved.

As a result, variables don't have any actual value to read when trying to resolve those statements.

And yeah, Add-Type can do similar things but will still support variable usage and so on. 🙂

**Comment by 237dmitry** [comment]
> As a result, variables don't have any actual value to read when trying to resolve those statements.

Thank you, I understand now.
