### ISSUE TITLE
PowerShell fails to start in case of weird permissions in TEMP/strange behavior of antivirus

### ISSUE THREAD

**Issue by Niehweune** [PowerShell/PowerShell#15523]
On some of our client's servers, PowerShell sometimes throws an UnauthoziedAccessException when starting.

Issue is practically the same as mentioned in https://github.com/PowerShell/PowerShell/pull/8627 , however we're not getting an IOException, but an UnauthorizedAccessException.

Root cause analysis showed a particular antivirus package (Sophos) was changing the attributes on the __PSScriptPolicyTest_*.psm1 file (and only on that file), presumably to prevent access while the file is being scanned. PowerShell seems to crash if this attribute change happens between the moment that the OS returns a handle for the DELETE operation, and an attempt is made to delete the file.

As a workaround, we adding an exception on __PSScriptPolicyTest* files in the antivirus, after which the issue was resolved. However, this is not a good idea from a security point of view, because an attacker might use this file naming scheme to install a malicious workload.

So this exception (or maybe any exception) should be caught here too:
https://github.com/PowerShell/PowerShell/blob/ea19ceac4a4afac2e8dd456a85a5591aeb2dacb0/src/System.Management.Automation/utils/PathUtils.cs#L442

## Steps to reproduce

- Open CMD on the affected (Windows) system
- Start pwsh

## Expected behavior

PowerShell should start

## Actual behavior

About 3 out of 10 times, pwsh.exe crashes with the exception
```
Process terminated. The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
  at System.Environment.FailFast(System.String, System.Exception)
  at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
  at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.TypeInitializationException: The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.
---> System.UnauthorizedAccessException: Access to the path _TempFolderName_\\\_\_PSScriptPolicyTest\__RandomString_.psm1' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at System.Management.Automation.PathUtils.TryDeleteFile(String filepath)
   at System.Management.Automation.Security.SystemPolicy.GetAppLockerPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetLockdownPolicy(String path, SafeHandle handle)
   at System.Management.Automation.Security.SystemPolicy.GetSystemLockdownPolicy()
   at System.Management.Automation.Runspaces.InitialSessionState..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault2()
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
```

At the time of crashing a __PSScriptPolicyTest_*.psm1 file is left in the $ENV:TMP folder.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@Niehweune Please issue template and share more information ($PSVersionTable)

**Comment by TravisEz13** [comment]
Some background, these files are used to detect if AppLocker is enabled.  We delete them to keep from leaving garbage around which may slow future scans.

Personally, I feel that this is an area that PowerShell can be more resilient at, but this resilience would likely be in the form of leaving these temporary files around as this is in a critical path for PowerShell startup and we don't want to affect startup performance.

I discussed this with @PaulHigin  and he felt strongly that we should not ignore the deletion failure.  
If this interfered with our ability to call AppLocker, I would agree.

From the stack trace, this is not the case, but I would encourage you to contact Sophos and report this issue with their product.

**Comment by iSazonov** [comment]
We could:
1. repeat the delete like `while (iteration++ < 2)`
2. delay the delete and put the action into background task.
3. create the test files in locked mode, i.e. replace IO.File.WriteAllText() with FileStream FileShare.Read.

**Comment by PaulHigin** [comment]
WG-Security:
Since this occurs during PowerShell start up, we prefer to not perform repeated tasks or create a back ground task.

We feel options to fix are:
1. @iSazonov idea to create the test files without share flag to prevent AV from locking it.
1. Catch any exception when removing the test file and leave file on disk.

The first is preferable since that should ensure the test files are removed, but needs to be tested.
