### ISSUE TITLE
[DSL support] Improve user and module scope interleaving for DSL keywords

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15532]
## Summary of the new feature/enhancement

Related to https://github.com/PowerShell/PowerShell/issues/15105.

PSArm accomplishes some DSL functionality by [using](https://github.com/PowerShell/PSArm/blob/e22c29dfea6b2f489964d427cf0ec09270dd7d8b/src/Commands/Template/NewPSArmResourceCommand.cs#L91-L99) the [`ScriptBlock.InvokeWithContext()` API](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.scriptblock.invokewithcontext) to allow the definition of keywords within a user-supplied scriptblock.

However, this is awkward to use, especially from C#, because:

- The supplied context must be a dictionary of scriptblocks, which makes sense when written in PowerShell as a hashtable but is not as simple in C# (compared to being able to contextually define cmdlets, for example)
- The thread where the scriptblock is executed and where the supplied context has affinity is implicitly defined, so needs to be managed carefully
- Creating variables to supply in the list is not straightforward compared to doing something like providing another dictionary
- No other inputs (like parameters or arguments) can be supplied

When defining DSLs in PowerShell, it's useful to be able to provide commands in a contextual way to be executed in user-provided scriptblocks, and the `ScriptBlock.InvokeWithContext()` API is probably the best way to do this today, but still requires a fair amount of work to use well.

We should:

- Review the API and see if anything can be added to make it easier to use from PowerShell (like better overloads or a cmdlet API)
- See if we can also come up with a more C#/.NET-oriented API/overload that provides some finer grain control over things implicitly taken care of in PowerShell (like the execution thread), while also doing more of the work to make calling the API from C# less of a chore (like using more generalised inputs for variable and command contexts)

**Comment by iSazonov** [comment]
> * The thread where the scriptblock is executed and where the supplied context has affinity is implicitly defined, so needs to be managed carefully

This seems to be a stumbling block.
The API looks like a _local_ closure while we need a _global_ one.
So that other hosts or applications can use PowerShell flexibly and safely, we either need to get rid of this dependency or create a more appropriate API.
