### ISSUE TITLE
Question on .net Split Change

### ISSUE THREAD

**Issue by JAK1047** [PowerShell/PowerShell#15538]
Just a question on what I assume is due to a change in .net 5. I've encountered a small breaking change when converting one of my Powershell 5.1 scripts to be Powershell 7 compatible. In our environment I have an import script where I can't be positive on the delimiter in a string, so previously I used the .net string split method like: .Split(';:,') which would split on any of those characters. Seems that that's changed in Powershell 7 assumedly due to a change in .net.

![image](https://user-images.githubusercontent.com/29665481/121088440-c306ac80-c7b3-11eb-9962-0c1f2e9bd3d3.png)

Super easy fix I can either chain .splits together or in my case I just swapped to the regex split operator: -split ',|:|;'. But I can't seem to find any documentation on either the .net or Powershell side mentioning what this change would have been. Any help for an explanation?

---
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by 237dmitry** [comment]
```
'a;b:c,d'.Split([char[]]';,:')
```

**Comment by JAK1047** [comment]
So previously the .Net String Split method defaulted with the Char[] overload and now defaults to String[] or something along those lines? Was that a .Net change somewhere between framework and core? Not looking for a solution just trying to find the reason behind the difference and documentation of the change if possible.

**Comment by 237dmitry** [comment]
Windows Powershell has no `string` separator, just `string[]`. PowerShell Core has . This is why the separator type has to be specified. As I think.
```
(''.Split).OverloadDefinitions
```

**Comment by JAK1047** [comment]
Gotcha so those extra overloads were added at some point with Core and now in my example instead of being read as a string array or char array, checking each character individually against the string, it's instead by default just read as a singular string? (Unless of course I specify the type explicitly)

Am I getting the gist of it?

**Comment by 237dmitry** [comment]
> it's instead by default just read as a singular string?

Yes. Otherwise, it is impossible to distinguish a string from a set of delimiters.

**Comment by JAK1047** [comment]
That answers my question on the difference then. Thank you!
