### ISSUE TITLE
Doc Bug in AddScript API

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#15537]
Copied from https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4472

This is a bug in the API documentation for AddScript(). The API documentation comes from `///` comments in the source code to this must be fixed in the source code. The example shown in the docs is using AddCommand() instead of AddScript. Also the line break and indentation could be improved for readability.

Both overloads are affected:

https://github.com/PowerShell/PowerShell/blob/659dff09e4e1fd15e9f404b4f3460bd9f239ea90/src/System.Management.Automation/engine/hostifaces/PSCommand.cs#L153-L156

https://github.com/PowerShell/PowerShell/blob/659dff09e4e1fd15e9f404b4f3460bd9f239ea90/src/System.Management.Automation/engine/hostifaces/PSCommand.cs#L195-L198

**Comment by octos4murai** [comment]
Hi folks. I'm a first-time contributor to PowerShell and would like to take this on.

**Comment by iSazonov** [comment]
@octos4murai Feel free to pull PR.
