### ISSUE TITLE
`AppDomain.Unload` usage is deprecated and should be removed

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15535]
As per, https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0024 the usage of `AppDomain.Unload` is deprecated and should be removed.

It is used at: https://github.com/PowerShell/PowerShell/blob/4aaed08955cba4e08e9022bba9ca35b6a3f575e5/src/System.Management.Automation/engine/ExecutionContext.cs#L222-L233

As per discussion with @daxian-dbw the code is old and not used anymore and should be cleaned up.

## Steps to reproduce

Compile code with .NET 6 preview 5 will throw a warning causing a build break: https://github.com/PowerShell/PowerShell/runs/2764430556?check_suite_focus=true#step:4:105

**Comment by rjmholt** [comment]
Fixed in https://github.com/PowerShell/PowerShell/pull/15554
