### ISSUE TITLE
[DSL support] Provide a way to execute a scriptblock in a clean or custom scope

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15533]
## Summary of the new feature/enhancement

Motivated by https://github.com/PowerShell/PSArm/pull/133 and related to https://github.com/PowerShell/PowerShell/issues/15532.

There are a number of cases for PowerShell DSLs where a user-provided scriptblock needs to be executed in a local scope but where normal commands and aliases should not apply.

One example in PSArm is where resource keywords (defined as functions) are overridden by global aliases which are unhelpful in that scope. In order to prevent these aliases from affecting the DSL, PSArm has to do some kind of scope teardown and restore (or compromise the UX of the DSL).

Another example is in Pester, where Pester defines mocks while also storing the true definition of commands in a hashtable to safely use the latter while defining the former for testing.

Because of the altered-universe semantics of many DSLs, it would be nice if there were a finer-grained control over scopes for this kind of problem, allowing things like:

- Running a scriptblock in an alias-free environment or an environment where only supplied aliases are defined
- Being able to "freeze" the current scope (and call back into it when needed) and pushing a new scope
- Being able to create a new child scope where exactly the desired commands/functions/aliases/variables are defined and no others (essentially https://github.com/PowerShell/PowerShell/issues/15532)

While this issue was opened separately from https://github.com/PowerShell/PowerShell/issues/15532 because the two are solved separately in PSArm, it's easy to imagine the "clean scope" and the "scope interleaving" problems could easily be accomplished by a well thought out "custom child scope" API.

**Comment by iSazonov** [comment]
It seems that we will have to redesign and reimplement Engine to make it work transparently and fast. :-)
