### ISSUE TITLE
Tokenizer treats `.` as a separator when parsing a parameter token, which causes problem to argument parsing for native commands

### ISSUE THREAD

**Issue by delanym** [PowerShell/PowerShell#15541]
I use powershell to run build commands like
`mvn --% install -Dmaven.test.skip -Dmaven.repo.local=.m2/repository -Dbuild.deployAtEnd=true -Dgib.disable`

I NEVER expect the dot to act like a property selection operator. I don't want to have to quote every time I use a dot, and I'd rather not have to specify --% for every command.

Is it reasonable to expect a setting in pwsh.runtimeconfig.json to disable parsing of command arguments? Call it dumb mode or whatever.

I see other people are also doing strange things to work around this https://stackoverflow.com/questions/18923315/using-in-powershell

**Comment by vexx32** [comment]
Unless I'm missing something, you shouldn't need to use `--%` most of the time. That command you have there will work as-is without it, I'd think.

**Comment by delanym** [comment]
You're not the first person to suggest that, but the fact is I've never seen it work without --%, on many machines running powershell 5 or 7. It evens highlights the syntax

![image](https://user-images.githubusercontent.com/5310238/121206643-efd0c780-c878-11eb-9e9b-62d6cd3e7efa.png)

What makes you think I don't need the --% ?

**Comment by rkeithhill** [comment]
Yeah, there is a difference without `--%`:

![image](https://user-images.githubusercontent.com/5177512/121212614-c2fdbf80-c83a-11eb-9050-8e6ce1ea496a.png)

Using `--%` in PS:

![image](https://user-images.githubusercontent.com/5177512/121212819-ee80aa00-c83a-11eb-832a-b6b2e3f0941e.png)

**Comment by vexx32** [comment]
That feels like a bug, frankly. I don't see any good reason for the `.` characters to have special meaning. There aren't any variables or other special tokens involved here.

**Comment by daxian-dbw** [comment]
Another native command argument parsing issue related to tokenizer: https://github.com/PowerShell/PowerShell/issues/15279

**Comment by ceztko** [comment]
This seems the same as the older #6291. I fail to understand if this a confirmed bug and if this will be solved in a future version of powershell.

**Comment by mklement0** [comment]
Good point, @ceztko. In fact, 

* https://github.com/PowerShell/PowerShell/issues/6291 

is just one of several related bugs, which the following search surfaces ("Parameter parsing.passing" in the title, 8 issues as of this writing):

*  https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+parameter+parsing%2Fpassing+in%3Atitle

**Comment by rkeithhill** [comment]
I ran into this again on macOS with the updated native command passing:
```
g++ ./hello.cpp -target arm64-apple-macos11 -mmacosx-version-min=11.0 -o hello_arm  
clang: error: no such file or directory: '.0'
```
You can quote the `11.0` to get around this or use `--%`.  The issue seems to be that `-mmacosx-version-min=11` is considered a parameter name by PowerShell following by a `.0` as a `ConstantExpressionAst`.  Possible fix is to recognize this situation in the NativeCommandProcessor and fix up the resulting parameter passed to the native app.

**Comment by mklement0** [comment]
@rkeithhill, it's the same old bug, #6291, and it is both unrelated to and long predates `$PSNativeCommandArgumentPassing`, as are the other linked bugs.

The simplest workaround is  to quote the _whole argument_:`'-mmacosx-version-min=11.0'`

**Comment by delanym** [comment]
Also, I can't use `--%` in commands which invoke a script. For example with this script "fast.ps1"

```powershell
./mvnw clean install $args -D"surefire.skip"
```

And this command `fast --% something`

The token "--%" gets passed to Maven. So I'm forced to quote.

**Comment by doggy8088** [comment]
@delanym What's your `$PSNativeCommandArgumentPassing` value?

**Comment by delanym** [comment]
@doggy8088 i just installed Powershell 7.4.1 and the value is "Windows"

**Comment by delanym** [comment]
https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.4#psnativecommandargumentpassing

It makes no difference whether this property is set to Windows, Standard or Legacy.

**Comment by ceztko** [comment]
Maybe this issue should be kept open/assigned a milestone?
