### ISSUE TITLE
PowerShell throwing Unhandled Exception after launch

### ISSUE THREAD

**Issue by pulak777** [PowerShell/PowerShell#15550]
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6


Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at System.Collections.Concurrent.ConcurrentBag`1.Initialize(IEnumerable`1 collection)
   at System.Management.Automation.Runspaces.InitialSessionState.UpdateFormats(ExecutionContext context, Boolean update)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind_UpdateFormats(ExecutionContext context, Boolean updateOnly)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

[process exited with code 2]
```
I suddenly started getting this error yesterday, for default powershell terminal
### Additional Info 
* Windows - 10.0.19043 Build 19043
* I have ```.NET SDK 5.0.300 (x64)``` installed

**Comment by rjmholt** [comment]
> Windows PowerShell

This seems to be Windows PowerShell 5.1. This repo pertains to PowerShell 7, a related but different PowerShell version with a separate implementation. You may find PowerShell's [community support resources](https://docs.microsoft.com/en-us/powershell/scripting/community/community-support) helpful in solving your issue.

I'll close this issue as unrelated to PowerShell 7. However, if it is related, please feel free to reopen this issue with more information.

**Comment by pulak777** [comment]
Hi, actually I read the instruction given by default. Which states that  - 
```
For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the following link instead:
Windows PowerShell [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

This repository is **ONLY** for PowerShell Core 6 and PowerShell 7+ issues.
```
But the link provided here is **inactive**. That's why I put the issue here, as I cannot find any reliable solution for tackling this issue. Any solution will be highly appreciated. Thanks.

**Comment by rjmholt** [comment]
Also /cc @PaulHigin in case there's anything you can think of off the top of your head here

**Comment by pulak777** [comment]
@rjmholt it will be really helpful. As till now I don't have any reliable solution in hand. Thanks a lot.

**Comment by PaulHigin** [comment]
@pulak777   Since this is WindowsPowerShell, please report this via [UserVoice](https://microsoftteams.uservoice.com/)

I don't think WindowsPowerShell has changed much, but this seems like a CLR issue.

/cc: @daxian-dbw

**Comment by rkeithhill** [comment]
@pulak777 The version of .NET Core does not matter since Windows PowerShell uses the desktop .NET Framework.  The version I'm running (as shown by $PSVersionTable) in WinPS 5.1 on Windows 10 build 19043.985) is:
```
CLRVersion                     4.0.30319.42000
```
The MS docs say this: `For .NET Framework 4.6 and later versions, it has the form 4.0.30319.42000`. 

I do see this in the stack-trace `InitialSessionState.UpdateFormats`.  Do you have any profile script or modules that might be trying to update type or view formats?  What happens if you try running `powershell.exe -noprofile`?  Does it still crash?

**Comment by pulak777** [comment]
@rkeithhill 
```
Microsoft (R) .NET CLR Version Tool  Version 4.8.3928.0
Versions installed on the machine: v4.0.30319
```
I have tried ```powershell.exe -noprofile``` but getting the same error logs.
Is this causing for VS code? As I'm getting the same error log for ```Developer CP for VS 2019``` and VS installer isn't opening.

**Comment by pulak777** [comment]
Finally solved. There was a problem in the `C:\$Mft` file.
