### ISSUE TITLE
Support lowered TrustLevel for Start-Process

### ISSUE THREAD

**Issue by ringerc** [PowerShell/PowerShell#15562]
## Summary of the new feature/enhancement

I propose the addition of a `Start-Process -DropPrivileges` or `Start-Process -TrustLevel 'Basic User'` option to the `Start-Process` cmdlet to make it simple to run a child-process with lowered privileges from within a Powershell script that is running with elevated (effective Administrator) privileges.

`Start-Process -Wait` and `Wait-Process` should both behave like they would without the drop privileges option, `-NoNewWindow` should internally create pipes to forward the I/O to and from the child process, `Stop-Process` should properly terminate the process if passed the returned process object, and the exit code from the child process should be available if `Start-Process -PassThru` is used. In short, it should behave just like a normal process that was launched without dropping administrator privileges.

Presently it appears to be exceedingly difficult to run a new process without elevated (Administrator) privileges from an elevated powershell session, wait for the process to exit, consume its stdout/stderr, and capture its exit code when it terminates. See my example in https://github.com/PowerShell/PowerShell/issues/15555#issuecomment-859248204 `trustlevel.ps1`.

I further suggest that the same option should also be added to `Start-Job` (but obviously not `Start-ThreadedJob`) so powershell jobs can be launched with reduced rights in a simple, straightforward manner, and interacted with as normal.

## Proposed technical implementation details (optional)

Add new `-TrustLevel 'Basic User'` option to `Start-Process` on Windows, where the available options to `TrustLevel` correspond to the fields exposed by `runas.exe /showtrustlevels`

```
PS C:\Users\test> runas /showtrustlevels
The following trust levels are available on your system:
0x20000 (Basic User)
```

Internally, Powershell would:

* Create named pipes for any non-redirected I/O channels and set any required privileges to permit them to be accessed by the less-privileged child process (probably none, since the process SID will still be the same, it just won't be elevated)
* [Launch a new `pwsh.exe` with the lowered trustlevel](https://stackoverflow.com/a/23901718/398670) e.g. using `SaferCreateLevel()`, `SaferComputeTokenFromLevel()` and `CreateProcessAsUser()`
* Have the new `pwsh.exe` child attach to the named pipes so that the child pwsh's stdio 
* Invoke the requested `Start-Process` cmdlet *without* the `-TrustLevel` option from the child `pwsh.exe`, preserving all other arguments exactly
* When the process exits, return a serialized representation of the `Process` object from `Start-Process -Passthru` to the parent pwsh if `-Passthru` was requested
* In the parent pwsh, service the child pwsh's named pipes, forwarding input and output as appropriate, and wait for the child pwsh to exit. If `-Passthru` was requested, deserialize and return the `Process` object, with `ExitCode` etc intact and set appropriately.

The user experience would thus look like

```powershell
$proc = Start-Process -TrustLevel 'Basic User' -Passthru -NoNewWindow -Wait -FilePath 'mycommand.exe' -ArgumentList @('arguments here')
# ... mycommand.exe output is printed as it is generated by the command, and the session blocks waiting for it to exit.
if ($proc.ExitCode -ne 0) {
    Write-Error "Oops, mycommand.exe exited with $($proc.ExitCode)"
}
```

On Linux the capabilities(7) model could be exposed instead of using a `TrustLevel`, but it's less important. Linux users already have much simpler ways to do things with lowered privileges than are available under Windows, and tools like `sudo` and `setpriv` do not suffer from the same limitations as `runas.exe` re exit code, stdio, etc.

## Why I suggest a Windows-specific TrustLevel in preference to a generic DropPrivileges option 

It'd be cross platform friendly, but less specific, to add a `-DropPrivileges `option.

The problem with this is that it's not very clear which privileges are being dropped and which are to be retained. Consider the output of running `whoami /all` on Windows:

```
& ${env:\WINDIR}\system32\whoami.exe /all

[...]

PRIVILEGES INFORMATION
----------------------

Privilege Name                            Description                                                        State  
========================================= ================================================================== =======
SeIncreaseQuotaPrivilege                  Adjust memory quotas for a process                                 Enabled
SeSecurityPrivilege                       Manage auditing and security log                                   Enabled
SeTakeOwnershipPrivilege                  Take ownership of files or other objects                           Enabled
SeLoadDriverPrivilege                     Load and unload device drivers                                     Enabled
SeSystemProfilePrivilege                  Profile system performance                                         Enabled
SeSystemtimePrivilege                     Change the system time                                             Enabled
SeProfileSingleProcessPrivilege           Profile single process                                             Enabled
SeIncreaseBasePriorityPrivilege           Increase scheduling priority                                       Enabled
SeCreatePagefilePrivilege                 Create a pagefile                                                  Enabled
SeBackupPrivilege                         Back up files and directories                                      Enabled
SeRestorePrivilege                        Restore files and directories                                      Enabled
SeShutdownPrivilege                       Shut down the system                                               Enabled
SeDebugPrivilege                          Debug programs                                                     Enabled
SeSystemEnvironmentPrivilege              Modify firmware environment values                                 Enabled
SeChangeNotifyPrivilege                   Bypass traverse checking                                           Enabled
SeRemoteShutdownPrivilege                 Force shutdown from a remote system                                Enabled
SeUndockPrivilege                         Remove computer from docking station                               Enabled
SeManageVolumePrivilege                   Perform volume maintenance tasks                                   Enabled
SeImpersonatePrivilege                    Impersonate a client after authentication                          Enabled
SeCreateGlobalPrivilege                   Create global objects                                              Enabled
SeIncreaseWorkingSetPrivilege             Increase a process working set                                     Enabled
SeTimeZonePrivilege                       Change the time zone                                               Enabled
SeCreateSymbolicLinkPrivilege             Create symbolic links                                              Enabled
SeDelegateSessionUserImpersonatePrivilege Obtain an impersonation token for another user in the same session Enabled
```

The "PRIVILEGES INFORMATION" can have different contents for different levels of rights. A service running under `NT AUTHORITY\SYSTEM` or `NT AUTHORITY\NETWORK SERVICE` will be an "administrator" but have a different set of rights to (say) an Administrator user logged in over ssh, or the same Administrator user in an interactive command prompt in a UAC-enabled desktop login session. 

Similarly on Linux, you have a capabilities set which can be observed with `capsh --print`, e.g.

```
root# capsh --print
Current: =ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
Ambient set =
Current IAB: 
Securebits: 00/0x0/1'b0 (no-new-privs=0)
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=0(root)
Guessed mode: UNCERTAIN (0)
```

vs

```
craig$ capsh --print
Current: =
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
Ambient set =
Current IAB: 
Securebits: 00/0x0/1'b0 (no-new-privs=0)
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=1000(craig) euid=1000(craig)
gid=1000(craig)
groups=10(wheel),11(cdrom),18(dialout),36(kvm),54(lock),156(stapusr),158(stapdev),970(power),974(docker),983(libvirt),1000(craig)
Guessed mode: UNCERTAIN (0)
```

Would `-DropPrivileges` behave like running the command under `setpriv --no-new-privs --inh-caps '-all' --bounding-set '-all'  --ambient-caps='-all'` ? Or what?

And what would `-DropPrivileges` mean for group memberships? It's just too fuzzy.

## Rationale for why Powershell should help the user with this

It's desirable to encourage people to do things with lowered privileges whenever possible so this is something that should really be easy. It's often rather impractical to run your script as an unprivileged user or under a UAC-protected admin then elevate only the specific parts you require: If under UAC, the user is barraged with interactive UAC prompts, and if under a non-UAC lesser-privileged role, you have to actually handle username/password credentials for the admin in your script due to the apparent lack of any way to delegate trust to authorize a lesser-privileged user to impersonate a privileged admin. You need `Start-Process -Credentials` with an actual admin username and password.

The specific case I encountered this with was a CI system where setup tasks require elevated privileges, but most of the task should be done without effective admin rights, while preserving the same file ownership etc and without requiring any passwords to be embedded in scripts.

## Bonus suggestion

I think it'd make a lot of sense to piggy-back support for `__COMPAT_LAYER=RunAsInvoker` on this too, with a `Start-Process -RunAsInvoker`. It's the reciprocal of the issue discussed above. Right now it's a bit fiddly, annoying, and distinctly under-documented in win32 to override an application's "run as administrator" manifest flag and run it without elevation or UAC prompting.

**Comment by jborean93** [comment]
> -NoNewWindow should internally create pipes to forward the I/O to and from the child process,

I don't think this is really the way to go. It would mean you need to have some background task that is constantly reading and writing the stdio streams and redirecting it. What should happen is that the existing console should be inherited to the new process. This is how `-NoNewWindow` works normally right now. I've got a snippet below that tested this scenario out and it works just fine in that particular case.

For your technical details I'm not sure why the process object needs to be serialized. The proposed `Start-Process` should return the process object and start the filename and arguments as requested. This avoids any serialization and extra middleman work that would need to occur to synchronize the data and the object returned back is actually live. I don't see why this wouldn't be possible using the combination of APIs you have mentioned unless I'm missing something

Here is some test code I wrote to try out the APIs you mentioned, I've never heard of the `Safer*` ones so I was intrigued.

<details>
  <summary>Click to view code</summary>

```powershell
Add-Type -TypeDefinition @'
using Microsoft.Win32.SafeHandles;
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace Safer
{
    public class SafeLevelHandle : SafeHandleZeroOrMinusOneIsInvalid
    {
        public SafeLevelHandle() : base(true) { }

        protected override bool ReleaseHandle()
        {
            return NativeMethods.SaferCloseLevel(this);
        }
    }

    public enum LevelScope : uint
    {
        Machine = 1,
        User = 2,
    }

    public enum Level : uint
    {
        Disallowed = 0x00000,
        Untrusted = 0x01000,
        Constrained = 0x10000,
        NormalUser = 0x20000,
        FullyTrusted = 0x40000,
    }


    [Flags]
    public enum CreateFlags : uint
    {
        None = 0x0,
        NullIfEqual = 0x1,
        CompareOnly = 0x2,
        MakeInert = 0x4,
        WantFlags = 0x8,
    }

    public class NativeMethods
    {
        [DllImport("Advapi32.dll")]
        public static extern bool SaferCloseLevel(
            SafeHandle hLevelHandle
        );

        [DllImport("Advapi32.dll", EntryPoint = "SaferComputeTokenFromLevel", SetLastError = true)]
        private static extern bool NativeSaferComputeTokenFromLevel(
            SafeHandle LevelHandle,
            IntPtr InAccessToken,
            out SafeFileHandle OutAccessToken,
            CreateFlags dwFlags,
            IntPtr lpReserved
        );

        public static SafeHandle SaferComputeTokenFromLevel(SafeHandle level, IntPtr token, CreateFlags flags)
        {
            SafeFileHandle newToken;
            if (!NativeSaferComputeTokenFromLevel(level, token, out newToken, flags, IntPtr.Zero))
                throw new Win32Exception();

            return newToken;
        }

        [DllImport("Advapi32.dll", EntryPoint = "SaferCreateLevel", SetLastError = true)]
        private static extern bool NativeSaferCreateLevel(
            LevelScope dwScopeId,
            Level dwLevelId,
            int OpenFlags,
            out SafeLevelHandle pLevelHandle,
            IntPtr lpReserved
        );

        public static SafeHandle SaferCreateLevel(LevelScope scope, Level level)
        {
            SafeLevelHandle levelHandle;
            if (!NativeSaferCreateLevel(scope, level, 1, out levelHandle, IntPtr.Zero))
                throw new Win32Exception();

            return levelHandle;
        }
    }
}
'@

# I honestly do not know the difference between Machine and User
$level = [Safer.NativeMethods]::SaferCreateLevel('Machine', 'NormalUser')
$token = [Safer.NativeMethods]::SaferComputeTokenFromLevel($level, [IntPtr]::Zero, 'None')

# Use $token with CreateProcessAsUser
# Start-ProcessEx is from https://gist.github.com/jborean93/a7c181b1ea0a4c0c8b815af9a8cbe508 and calls CreateProcessAsUser
Start-ProcessEx powershell.exe -Token $token -CreationFlags None
```
</details>

One thing we should be wary of is the `runas.exe /trustlevel` and the `Safer*` APIs seem to be a product from the Windows XP era before the whole UAC token split was a thing. What I found when inspecting the tokens is that there are some differences between a user's limited token and the one created by `SaferComputeTokenFromLevel`. These differences are

* A safer token only contained the `SeChangeNotifyPrivilege` privilege whereas a limited token had that and `SeIncreaseWorkingSetPrivilege`
* The token still contains the `High Mandatory Label` unlike your normal limited token which has a `Medium` one
* It looks like the LogonLUID is still the same as the admin one, this is mostly inconsequential but has some connotations when it comes ot things like mapped drives

In saying all that it's a lot simpler to use this `Safer` API and would even work to strip a full admin account to a more restricted token compared to the limited UAC token a normal process runs as.

**Comment by TobiasPSP** [comment]
@PowerShell/wg-powershell-cmdlets has been extensively discussing this issue. The mechanisms to both elevate and de-elevate processes depend largely on the underlying operating system. Since PowerShell is operating system neutral, adding such a feature would require specific code for specific target operating systems. 

That said, given the different OS architectures, the requested feature may be useful only for certain operating systems. For example, in Windows, where there is no sudo and support for elevating in-process, such a feature may be more useful than in Linux.

The group concluded that such a feature should surface in a separate OS-specific cmdlet. Such a cmdlet can be developed and maintained outside the core engine and hosted in a gallery module. 

Since on Windows there are many different routes an implementation of such a feature can take, the group encourages the community to experiment and come up with a working example. Once such a working sample exists and lives up to the expectations, the group gladly revisits this topic and discusses whether it would be helpful for enterprises to ship out of box due to security and trust reasons. For now, because of above reasoning we close the issue.

**Comment by bbkane** [comment]
Was there any solution to this?

When I SSH into my Windows machine, I get an admin prompt, and there appears to be [no way to drop privileges from the SSH prompt](https://github.com/PowerShell/Win32-OpenSSH/issues/1652).

**Comment by kfsone** [comment]
I find this to routinely be an issue because you don't actually run with "elevated permissions", you run as a different user.

Ergo:

```
subst T: $env:TEMP
echo "hello" >T:foo.txt
start -verb runas cmd -argumentlist "/c", "copy", t:foo.txt, $env:TEMP\copy.txt
```

will fail, because T: does not exist for the elevated user, the point being that if you are already elevated, you can't yield back to regular user space.

Perhaps the real solution then is to find a way to create yourself an elevated ps session to which you can pass invoke-command stuff.

**Comment by Kreijstal** [comment]
> Was there any solution to this?
> 
> When I SSH into my Windows machine, I get an admin prompt, and there appears to be [no way to drop privileges from the SSH prompt](https://github.com/PowerShell/Win32-OpenSSH/issues/1652).

same
