### ISSUE TITLE
Start-PSBootstrap failure doesn't fail the CI step

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15561]
In https://github.com/PowerShell/PowerShell/pull/15548 and https://github.com/PowerShell/PowerShell/pull/15491, `Start-PSBootstrap` fails but does not cause the particular CI step to fail. Instead the next step fails in a less specified way, since its failure is due to the bad state from the previous step.

We should fix the build task so that a failure in `Start-PSBootstrap` causes its own build step to fail.

**Comment by anmenaga** [comment]
Maintainer review:   could not find the repro, so closing this until new occurrence happens.

**Comment by rkeithhill** [comment]
I think this can be closed because the issue lies with the AZ/GH PowerShell action step.  See https://github.com/Azure/powershell/issues/39
