### ISSUE TITLE
Distribution Support Request: PowerShell for iOS

### ISSUE THREAD

**Issue by hez2010** [PowerShell/PowerShell#15563]
## Details of the Distribution

- Name of the Distribution: iOS
- Version of the Distribution: iOS 15
- Package Types
    - [ ] Deb
    - [ ] RPM
    - [ ] Tar.gz
    - [x] ipa
    - Snap - Please file issue in https://github.com/powershell/powershell-snap.  This issues type is unrelated to snap packages with a distribution neutral.
- Processor Architecture (One per request): ARMv8
- The following is a requirement for supporting a distribution **without exception.**
    - [x] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).
- The following are requirements for supporting a distribution.
  Please write a justification for any exception where these criteria are not met and
  the PowerShell committee will review the request.
    - [x] The version of the Distribution is supported for at least one year.
    - [x] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

## Progress

- [ ] ~An issues has been filed to create a Docker image in https://github.com/powershell/powershell-docker~ Docker images are not needed

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by BrucePay** [comment]
For what purpose? The iOS execution environment would pretty much cripple PowerShell as a management tool. Do you have a specific scenario in mind? (Personally I think it would be kind of cool but kind of cool probably isn't enough to justify the amount of work needed. )

**Comment by hez2010** [comment]
Yeah iOS has lots of restrictions and cannot runn apps with a JIT compiler, making it nearly impossible to run PowerShell. 

I'm closing this issue.
