### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by paulaustin-automutatio** [PowerShell/PowerShell#15579]
## Steps to reproduce

```powershell
>Get-LocalGroupMember -Group "Administrators"
Get-LocalGroupMember: Failed to compare two elements in the array.
```

Administrators group contains the following members

* Administrator
* AzureAD\<user> (S-1-12-1-....)
* S-1-12... for some groups and roles
* 
## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none

```

**Comment by iSazonov** [comment]
Please use our issue template to report bug.

Also the cmdlet is not in the repo. Please use Windows Feedback tool to report the bug.
