### ISSUE TITLE
Add the ability to disable the default prompt

### ISSUE THREAD

**Issue by Maxpxt** [PowerShell/PowerShell#15572]
## Summary of the new feature/enhancement

To customize the prompt, one defines `function Prompt { ... }`, whose output is displayed as the prompt. In the body of this function, the user may want to display the prompt by printing it themselves instead of returning it:

```powershell
function Prompt { Write-Host "my prompt> " -NoNewline }
```

This is common when the user wants a colored prompt (`Write-Host -BackgroundColor`) or even a prompt implemented in another language other than PowerShell (`Prompt` just calls a prompt program or a wrapper over a previously loaded dynamic library).

The issue is that, currently, when the return value of `Prompt` is `$null` or something that is displayed as an empty string `""`, the default prompt (`PS>`) is displayed:
```powershell
function Prompt { "my prompt >" }
# Prompt is "my prompt>"

function Prompt { $null }
# Prompt is "PS>"

function Prompt { "" }
# Prompt is "PS>"

Add-Type -MemberDefinition 'public override string ToString() => "";' -Namespace "My" -Name "OpaqueEmpty"
function Prompt { [My.OpaqueEmpty]::new() }
# Prompt is "PS>"
```

This behavior makes it impossible for one to have an "empty" prompt, or, more usefully, a `Prompt` function that prints the prompt itself and does not trigger the default prompt:

```powershell
function prompt { Write-Host "my prompt> " -NoNewline -ForegroundColor Blue }
# Prompt is "my prompt> PS>"

function prompt { Write-Host "my prompt> " -NoNewline -ForegroundColor Blue; "" }
# Prompt is "my prompt> PS>"
```

The proposal is that some mechanism be provided allowing the default prompt to not be displayed even when nothing displayable is returned by `Prompt`.

### Alternative 1: Only show the default prompt when `$null` is returned

Modify the current logic that triggers the default prompt to trigger it only when `$null` is returned by the `Prompt` function. This would allow disabling the default prompt by simply returning an empty string `""`.

```powershell
function Prompt { Write-Host "my prompt> " -NoNewline; "" }
# Prompt would be "my prompt>"
```

It is worth noting that this is the way [the docs about the prompt](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.1#the-default-prompt) say it currently works:

> The default prompt appears only when the `Prompt` function generates an error or does not return an object.

So, the actual current behavior of triggering the prompt on `""` is in disagreement with the docs.

#### Advantages

* This approach is the more intuitive. "if null then default" is a common pattern.
* With this approach, the solution is easy to discover by trial and error.

#### Disadvantages

* This changes current behavior and, therefore, impacts preexisting code that relies (possibly unintentionally) on this behavior. 

### Alternative 2: A custom type

Add a special type or object, say, `PromptConfig` which can be returned by the prompt to instruct the default prompt to not trigger.

```powershell
$env:NoDefaultPompt
function Prompt { Write-Host "my prompt> " -NoNewline; [PromptConfig]::NoDefaultPrompt }
# Prompt would be "my prompt>"
```

#### Disadvantages

* Somewhat inconsistent in that `PromptConfig` return values would be special-cased to not be displayed and configure the prompt instead.
* With this approach, the solution would only be discovered once the user reads the docs.

### Alternative 3: An environment variable

Add an environment variable, say, `$env:NoDefaultPompt`, which defaults to `$false`, but can be set by the user. When `$env:NoDefaultPompt` is `$true`, never show the default prompt, regardless of what happens in the `Prompt` function.

```powershell
$env:NoDefaultPompt = $true
function Prompt { Write-Host "my prompt> " -NoNewline }
# Prompt would be "my prompt>"
```

#### Disadvantages

* "Leaks" the local issue (asking not display the default prompt) into a global space (the environment variables).
* The actual behavior of the prompt would now depend on two things, the `Prompt` function and `$env:NoDefaultPompt`.
* With this approach, the solution would only be discovered once the user reads the docs.

**Comment by 237dmitry** [comment]
> This behavior makes it impossible for one to have an "empty" prompt,

```
function prompt { "`r" }
```

**Comment by Maxpxt** [comment]
@237dmitry The point is not for the prompt to be actually empty, but printed inside `Prompt` without `Prompt` returning anything. None of these work:

```powershell
function Prompt { Write-Host "my prompt>" -NoNewline; "`r" }
```

![image](https://user-images.githubusercontent.com/19475500/122139542-97bd3680-ce1f-11eb-896a-65362a4548d1.png)

```powershell
function Prompt { Write-Host "my prompt>" -NoNewline; "`e" }
```

![image](https://user-images.githubusercontent.com/19475500/122139632-c9360200-ce1f-11eb-882d-8f84adc657ec.png)


@rkeithhill Could you open this again?

**Comment by rkeithhill** [comment]
This seems to be working as you want.

![image](https://user-images.githubusercontent.com/5177512/122147280-d221d600-ce15-11eb-85d0-382a81ddbad5.png)

Just to make sure nothing else is interfering, run `pwsh -noprofile` and try the prompt function. 
```powershell
function prompt { Write-Host "my prompt> " -NoNewline; "`e" }
```

**Comment by Maxpxt** [comment]
Just ``"`e"`` doesn't work:

![image](https://user-images.githubusercontent.com/19475500/122153078-a401bd80-ce38-11eb-9bb7-6a7b27f3ff95.png)

But ``"`e[0m"`` works fine.

Thanks for the help!
