### ISSUE TITLE
Set-LocalGroupMembers

### ISSUE THREAD

**Issue by paulaustin-automutatio** [PowerShell/PowerShell#15578]
## Summary of the new feature/enhancement

Please add a Set-LocalGroupMembers function that would set the group to have only the member specified.

Right now you'd need to use Add-LocalGroupMember. Then Get-LocalGroupMember followed by Remove-LocalGroupMember to remove any that aren't in the list.

Although Get-LocalGroupMember throws an error if you have Azure-AD elements

**Comment by jdhitsolutions** [comment]
Under review by the Cmdlet Working Group

**Comment by SteveL-MSFT** [comment]
Those cmdlets are part of the `LocalAccounts` module which isn't part of PS7 as they use private APIs and thus can't be Open Source.

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets reviewed this.  The LocalAccounts module is part of Windows PowerShell and not PowerShell 7 (although it works with PS7).  It is not Open Source as it uses undocumented APIs and thus not something this project can extend.  Our recommendation is for the community to develop a cross-platform account management module covering all the appropriate capabilities.

**Comment by iSazonov** [comment]
I did an experiment a few years ago. There is no way to achieve compatibility either with this microsoft.powershell.localaccounts module or with ActiveDirectory one. Nevertheless, it is possible to create a useful module.

@SteveL-MSFT Can we do what we did with the Archive module? I.e., create an RFC first and preview under the MSFT team umbrella?

**Comment by birojnayak** [comment]
@iSazonov if a doc can be put out we would be more than happy to review and see which cmdlets we can build in cross platform way..

**Comment by SteveL-MSFT** [comment]
@iSazonov if you want a place to have an RFC discussion, I think you could perhaps use https://github.com/powershell/powershellmodulecoverage.  I think any resulting module should be developed and owned by the community and shipped on PSGallery, however.
