### ISSUE TITLE
PWSH ignores system trusted CAs

### ISSUE THREAD

**Issue by cawoodm** [PowerShell/PowerShell#15581]
PWSH 7.3 (Windows) is not respecting the trusted root CA's of the system - POWERSHELL v5 is:
![image](https://user-images.githubusercontent.com/498834/122032029-8ba98880-cdcf-11eb-81e2-c183c44aef63.png)

## Steps to reproduce

```powershell
(iwr https://some.ssl.site.com).statuscode
```

## Expected behavior

```none
200
```

## Actual behavior

```none
 The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
```

IE shows the cert as OK and the CA Root and Issuer are correctly installed:
![image](https://user-images.githubusercontent.com/498834/122032374-ddeaa980-cdcf-11eb-8ced-8bf9526dfff3.png)

## Environment data

```none
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I couldn't reproduce it. Windows 10 and Linux.

**Comment by iSazonov** [comment]
PowerShell uses .Net API HttpClient. Please report the issue to .Net Rumtime repository (they ask c# repro.)
