### ISSUE TITLE
Different behaviour calling [System.Net.HttpWebRequest] and certificate property between PS7 and PS5

### ISSUE THREAD

**Issue by FrankCarius** [PowerShell/PowerShell#15582]
I used a PowerShell Code segment from https://docs.microsoft.com/de-de/azure/information-protection/requirements#firewalls-and-network-infrastructure to test connectivity to a AIP remote host

```
$request = [System.Net.HttpWebRequest]::Create("https://admin.na.aadrm.com/admin/admin.svc")
$request.GetResponse()
$request.ServicePoint.Certificate.Issuer
```
It works fine with PowerShell 5 but not with 7.1.3

## Steps to reproduce

Rund these three lines in PSWH.EXE and PowerShell.exe

PS7: The Property "$request.ServicePoint.Certificate" is "$null"
PS5: the Property is a "System.Security.Cryptography.X509Certificates.X509Certificate"
And the output is "CN=Microsoft Secure Server CA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"

## Expected behavior

Powershell 7+ should fill this Property and return the Issuer

## Actual behavior

The property is a $null-object, so a script cannot verify the certificate

## Environment data

Working environment

```none
PS C:\Users\fcarius> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Not working environment
```
PS C:\Users\fcarius> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
This is a .NET type, so if there's a difference here between .NET Framework and .NET Core / .NET 5, PowerShell can't do anything about it.

**Comment by FrankCarius** [comment]
Thanks for that hint.
https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepoint.certificate?view=netcore-3.1 contains the details:

> Starting in .NET Core 1.0 and later including .NET 5.0 and later, the Certificate property always returns null. The ServerCertificateCustomValidationCallback is the recomendded way to access the server certificate.

I will close that bug. So even as a consultant, i have to dig deeper into the classes.  Thanks
