### ISSUE TITLE
Get-LocalGroupMember doesn't work with AzureAD joined groups and roles

### ISSUE THREAD

**Issue by paulaustin-automutatio** [PowerShell/PowerShell#15585]
## Steps to reproduce

Join a Windows 10 laptop to a Microsoft Endpoint Manager domain.

It will add the following to the Administrators group

- Global Administrator (role)
- Azure AD Joined Device Local Administrator (Role)
- The user who joined the domain

```powershell
Get-LocalGroupMember -Group "Administrators"
```

## Expected behavior

```none
Show a list of the members of the group
```

## Actual behavior

```none
Get-LocalGroupMember: Failed to compare two elements in the array.
```

I did some experimenting and it works with adding AzureAD users (e.g. AzureAD\me@domain.com) but doesn't work with ID's of the form S-1-12-1-9999999999-9999999999-9999999999-9999999999 which are Azure AD groups or roles.

Would it be trying to compare the names of the two items but can't as it doesn't have the name for the Azure AD groups or roles. And by having a null pointer check in the sorting code it would work.

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by paulaustin-automutatio** [comment]
https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/GetLocalGroupMemberCommand.cs

Change the following so that (sorry I'm a Java developer so I'm using Pseudo code

- Mane in comment is changed to name
- In the lambda expression:
```
 If p1.Name is null {
    if p2.Name is null {
     compare p1.SID and p2.SID
    } else {
      p1 is > p2 where name is null
    }
  } else {
    if p2.Name is null {
      p2 is > p1 where name is null
    } else {
     
      string.Compare(p1.Name, p2.Name, StringComparison.CurrentCultureIgnoreCase));
    }
  }
```
 
```c#
// sort the resulting principals by mane
rv.Sort(static (p1, p2) => string.Compare(p1.Name, p2.Name, StringComparison.CurrentCultureIgnoreCase));
```

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please use Windows Feedback tool to report the issue.

**Comment by jborean93** [comment]
This cmdlet is in this repository so it’s not an external issue AFAIK. It’s even linked in https://github.com/PowerShell/PowerShell/issues/15585#issuecomment-861510270.

**Comment by paulaustin-automutatio** [comment]
@iSazonov see my comment above showing the line of code in this repository that doesn't handle the case where the name is null. And a solution for that. It should be a really quick fix for someone who knows c#

**Comment by jeffbi** [comment]
I believe the primary reason the cmdlet is excluded from the build is that it is not cross-platform. It uses Windows-specific APIs.

**Comment by iSazonov** [comment]
> This cmdlet is in this repository

No, the module was removed due to complianceissues.

**Comment by jborean93** [comment]
Ah my apologies I was not aware of that.

**Comment by paulaustin-automutatio** [comment]
Some feedback from an end user.

1. How are users supposed to know where to submit bug reports to? I got to this issue tracker from the Microsoft hosted documentation page https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/get-localgroupmember?view=powershell-5.1
2. If the code is no longer used in the project then remove it. Having it in the project makes it look like it's still being used.
3. If there is code that has been moved somewhere else, can you forward those bugs to the appropriate team who would be able to fix it? I found a different API that works for my needs so won't be spending any more time on this.

**Comment by iSazonov** [comment]
> How are users supposed to know where to submit bug reports to?

Now MSFT have simplified the process very much and users can use single tool - Windows Feedback Tool.

**Comment by iSazonov** [comment]
Fixed in community module https://www.powershellgallery.com/packages/LocalAccounts

**Comment by paulaustin-automutatio** [comment]
That command returns 

Get-LocalGroupMember: The server cannot be contacted.

User accounts in the group are in the form AZUREAD\x@y.com
