### ISSUE TITLE
404 error on downloading Microsoft product GPG keys

### ISSUE THREAD

**Issue by duanqn** [PowerShell/PowerShell#15595]
I was following the documentation on [this page](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1) to install Powershell for Ubuntu. But I got a 404 error when trying to download the Microsoft product GPG key.

## Steps to reproduce

```powershell
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
```

## Expected behavior

Downloads Microsoft product GPG keys

## Actual behavior

wget returns 404 error

## Environment data

```none

```

**Comment by JAK1047** [comment]
Looks like at the time there was a major outage for packages.microsoft.com

https://github.com/dotnet/core/issues/6381#issuecomment-862858197

**Comment by duanqn** [comment]
@JAK1047  Thanks for the info. I've verified that the command is now working, so I closed this issue.
