### ISSUE TITLE
System.Speech.Synthesis.SpeechSynthesizer Speak method throws Object reference not set to an instance of an object." in PowerShell 7.x, but not in PowerShell 5.1.

### ISSUE THREAD

**Issue by cybercastor** [PowerShell/PowerShell#15596]
### Speech.Synthesis.SpeechSynthesizer Broken in CORE

RE-OPENED [8809](https://github.com/PowerShell/PowerShell/issues/8809)

## Steps to reproduce

```
Add-Type -AssemblyName System.speech
$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
$speak.Speak("test");

```

## Expected behavior

```
hear "test" from speakers, just like in PS 5.1

```

## Actual behavior

```
Exception calling "Speak" with "1" argument(s): "Object reference not set to an instance of an object."

```

## Environment data

POWERSHELL 5
```
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

POWERSHELL CORE 7.1.3
```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by 237dmitry** [comment]
> `-AssemblyName System.speech`

Try exactly point to a System.speech.dll from Net Frameworks. I do not think this would be working properly.

**Comment by cybercastor** [comment]
Same Results: All the functions returns 
```
 $synthesizer.Speak("test")
**MethodInvocationException: Exception calling "Speak" with "1" argument(s): "Object reference not set to an instance of an object."**
```


But it work Fine on Windows Powershell v5.0

**Comment by cybercastor** [comment]
You can COPY this function in a file and run it in Powershell 5 and Powershell 7:

```

function TestVoice{
        Add-Type -AssemblyName System.speech
        $VersionMajor=$global:PSVersionTable.PsVersion.Major
        $VersionMinor=$global:PSVersionTable.PsVersion.Major
        $Statement="This is a test of Text To Speech. Powershell Version " + $VersionMajor
        $Statement += " dot " + $VersionMinor
        Write-Host "############################" -f DarkRed
        Write-Host $Speech -f DarkRed
        
        try{
            $David=New-Object System.Speech.Synthesis.SpeechSynthesizer
            $David.SelectVoice('Microsoft David Desktop')
            $David.Speak($Statement)
        }
        catch {
            Write-Host "ERROR: $_.Exception.Message" -b DarkRed -f Yellow
        }
}
```

**Comment by 237dmitry** [comment]
You can use Sapi:
```
$sp = New-Object -ComObject Sapi.SpVoice
[void] $sp.Speak('text')

$sp | Get-Member  # for settings
```

**Comment by SeeminglyScience** [comment]
There's nothing PowerShell can do about this.  That library took a dependency on the name of a private field (`RegistryKey.hkey`, now renamed to `_hkey`) and that's why it's throwing.  Until that assembly (which is not part of this repo) is updated, you'll need to find an alternative API.

**Comment by cybercastor** [comment]
All good. I understand. Thank you for the time you took for this reply. I will go down the rabbit hole and let the community know if I figure out anything. Cheers!

**Comment by fMichaleczek** [comment]
@cybercastor It's working on my system. (not with PS 7.1.3)

```
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.6
PSEdition                      Core
GitCommitId                    7.2.0-preview.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by cybercastor** [comment]
https://cybercastor.github.io/index.html

Text 2 Speech Test Script
Try this my dude.

Run it with Powershell Core (6+). Try SAPI (will work). DOTNET. If it fails, it will start a winwows powershell 5 sessiobn to test.
Test-Text2Spk
Save to disk
Open Powershell Core and run the script. You will reproduce the failure
Upon failure, you will be setup to retry with Windows Powershell

**Comment by fMichaleczek** [comment]
@cybercastor can you confirm it's working on PS7.2 for you ?

**Comment by cybercastor** [comment]
To close this matter.; On Powershell Core, **_New-Object System.Speech.Synthesis.SpeechSynthesizer_** fails.
```
$David=New-Object System.Speech.Synthesis.SpeechSynthesizer
$David.SelectVoice('Microsoft David Desktop')
$David.Speak($Statement)
```

But **_New-Object -ComObject Sapi.SpVoice_** WORKS
```
$sp = New-Object -ComObject Sapi.SpVoice
[void] $sp.Speak('text')
```

I don't know if the fact that System.Speech.Synthesis.SpeechSynthesizer isn't supported in PWSH 7 is a bug, but my problem is fixed in that I circumvented the issue by using Sapi.SpVoice.

Thanks!

**Comment by fMichaleczek** [comment]
@cybercastor No. You open an "issue" about a problem, please stay focus on the "current" subject.
System.Speech.Synthesis.SpeechSynthesizer work on PowerShell 7.2 with an recent OS ( at least Microsoft Windows 10.0.19043).

Workaround : use PowerShell 7.2 + upgrade your OS or use another library

**Comment by SeeminglyScience** [comment]
Just to fully clarify, this will work in the latest preview because PowerShell happens to ship with a new version of the `System.Speech` library that no longer has this bug.  The label for this could be switched to `Resolution-Fixed`.
