### ISSUE TITLE
PSBoundParametersDictionary is exposed in PowerShell and has public members, but is internal to C#

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15592]
## Summary of the new feature/enhancement

The `PSBoundParametersDictionary` type is internal, but has public members and is itself exposed as a public property as `Cmdlet.MyInvocation.BoundParameters`:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/engine/ParameterBinderBase.cs#L1973-L1991

This means that, because PowerShell assesses access based on runtime reflection, you can access those members from PowerShell:

```powershell
function Test
{
    # This completes and is valid - it's public and people depend on it
    $PSBoundParameters.BoundPositionally
}
```

However, the actual `Cmdlet.MyInvocation.BoundParameters` property is exposed as `Dictionary<string, object>`. In fact the property itself may be a simple `Dictionary<string, object>`:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/engine/InvocationInfo.cs#L196-L211

However, in practice the parameter binder sets this to a `PSBoundParametersDictionary` instance in most conventional cases:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/System.Management.Automation/engine/ParameterBinderBase.cs#L2015-L2020

This creates an API mismatch between PowerShell and C#, and also makes this difficult to rely on from PowerShell, and in a way that users probably don't expect.

## Proposed technical implementation details (optional)

We should make the `PSBoundParametersDictionary` type public and expose it as the type of the `BoundParameters` property, ensuring that all the instances of this property are always that type.

**Comment by SeeminglyScience** [comment]
Note that changing the typing of `BoundParameters` would be a binary breaking change.  It may need a new property or documentation that the consumer would need to explicitly cast.

**Comment by rjmholt** [comment]
> Note that changing the typing of BoundParameters would be a binary breaking change

Given that `PSBoundParametersDictionary` inherits from `Dictionary<string, object>`, what examples of (non-reflection) breakage remain possible?

**Comment by SeeminglyScience** [comment]
Any usage of `BoundParameters` would need to be recompiled. Otherwise at JIT time it would throw a missing member exception because it would no longer be able to find a method with the signature `Dictionary<string, object> get_BoundParameters()`

**Comment by SeeminglyScience** [comment]
Here's a repro for what I'm talking about:

<details>

<summary>Script to generate example projects</summary>

```powershell
New-Item -ItemType Directory DemoBinaryBreak | Set-Location
New-Item -ItemType Directory Library | Set-Location

dotnet new classlib

Set-Content ./Class1.cs -Value 'using System.IO;

namespace Library
{
    public class Class1
    {
        public FileSystemInfo Info => null;
    }
}
'

New-Item -ItemType Directory ../Consumer | Set-Location

dotnet new classlib
dotnet add reference ../Library

Set-Content ./Class1.cs -Value '
namespace Consumer
{
    public class Class1
    {
        public static string GetName(Library.Class1 source) => source.Info.Name;
    }
}
'

dotnet publish

Set-Location ../Library

Set-Content ./Class1.cs -Value 'using System.IO;

namespace Library
{
    public class Class1
    {
        public FileInfo Info => null;
    }
}
'

dotnet publish

Get-ChildItem ./bin/debug/*/publish/Library.dll | ForEach-Object { Add-Type -Path $_.FullName }

# Explicitly do *not* recompile `Consumer`
Set-Location ../Consumer

Get-ChildItem ./bin/debug/*/publish/Consumer.dll | ForEach-Object { Add-Type -Path $_.FullName }

[Consumer.Class1]::GetName($null)
```

</details>

You should get:

```
MethodInvocationException:
Line |
  55 |  [Consumer.Class1]::GetName($null)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetName" with "1" argument(s): "Method not found: 'System.IO.FileSystemInfo Library.Class1.get_Info()'."
```

**Comment by rjmholt** [comment]
Really appreciate the repro, thanks!
