### ISSUE TITLE
Improvements in falsy or handling for CI scenarios

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShell#15594]
## Summary of the new feature/enhancement

I try to use as many of the new operators in PS7 as possible but I sometimes find myself in an unwinnable situation…

Let’s say I logically want this:
```pwsh
$a = $emptyStr || $emptyStr2 || $real
```
Where `$a` gets the value of `$real` because the first 2 or falsy

that doesn’t work. It sets it to `$emptyStr` because pipeline chain ops only relate to exit code basically

So then I think ok whatabout `-or`?
```pwsh
$a = $emptyStr -or $emptyStr2 -or $real
```
but unfortunately that turns `$a` into a boolean… So then I think ok how about the `??=` operator:
```pwsh
$a = $emptyStr
$a ??= $real
```
but no… that ends up with an empty string because `$a` has a value of empty string and `??=` only works if it’s `null` which I think makes sense personally.

I _could_ do ternaries:

```pwsh
$a = $empty ? $empty : $empty2 ? $empty2 : $real
```
but that's evil. So then I go back to old reliable:
```pwsh
$a = if($emptyStr) { $emptyStr } elseif($emptyStr2) { $emptyStr2 } else { $real }
```
but it’s just so much extra text.

Here's the scenario I was actually trying to solve in GitHub actions where I'm trying to consolidate values in a few places into one centralized output:

```pwsh
          $releaseBranch = '${{ steps.get-release-branch.outputs.release_branch }}'
          $passedInBranch = '${{ github.event.inputs.vscodebranch }}'

          $branch = if ($releaseBranch) {
              $releaseBranch
          } elseif ($passedInBranch) {
              $passedInBranch
          } else {
              'main'
          }

          Write-Host "Branch to use: $branch"
          Write-Host "::set-output name=chosen_branch::$branch"
```
## Proposed technical implementation details (optional)

idk... in TypeScript `||` and `&&` also handle truthy/falsy stuff so that to me is ideal... but I guess a different operator like `-eor` or `-eand` maybe for backcompat.

**Comment by rjmholt** [comment]
I discussed some thoughts on this in https://github.com/PowerShell/PowerShell/issues/3241#issuecomment-383263156.

In that issue there seemed to be broad agreement that that `&&`/`||` syntax should be reserved for Bourne shell-style control operators for chaining commands.

Fuzzy-boolean coalescence lives in the world of expression values rather than command effects, so the existing PowerShell expression operator syntax seems appropriate.

I think I've proposed it somewhere else, but basically a thought I've had in my head was to just make expression-value-conserving versions of the existing boolean operators that work like JavaScript's `&&' and `||`:

```powershell
'' -eor 'default' # evaluates to 'default'

'' -eand 'second' # evaluates to ''
```

(The `e` stands for "expression", since we want the actual expression result &mdash; just a suggestion!)

**Comment by 237dmitry** [comment]
Maybe I'm wrong, but I considered this construction as the result of executing a command. Success or failure.
```
Get-Item variable:fake -ea 0 || Get-Item variable:fake2 -ea 0 || 'Failure'
Get-Item variable:fake -ea 0 || Get-Item variable:PSHome -ea 0 && 'Success'
```

**Comment by rjmholt** [comment]
@237dmitry yeah, you've characterised your example correctly.

I think the issue with that is that it requires a cmdlet to be executed and to succeed or fail to use PowerShell's `&&`/`||` operators.

Rather than shoulder that complexity, it would be nice to just have a way to coalesce expressions directly:

```powershell
$fake -eor $fake2 -eor 'Failure'
```

While I think more on it, it turns out you can kind of do something similar with the existing boolean operators:

```powershell
$null = ($result = $fake) -or ($result = $fake2) -or ($result = 'Failure')
```

That takes advantage of (1) the result of the assignment occurring before conversion to boolean, (2) the value of an assignment statement being the value of the assigned value for the purposes of a subpipeline, and (3) the short-circuit logic of boolean operators.

**Comment by 237dmitry** [comment]
This is success as there are not terminated errors:
```
$fake && $fake2 && 'Success'
```
For checking null-values:
```
$fake ?? 'This is $null'
$fake ??= 10            # if fake is $null set it to 10
$fake
```

**Comment by rjmholt** [comment]
Yeah, in the first case `$fake` being unset, null or the empty string won't affect the result. You'll always get the concatenation of the outputs as the final result.

In the second case, the null assignment only checks for null values, not falsey ones.

**Comment by rkeithhill** [comment]
I suppose you could introduce a new operator that checked IsNullOrEmpty instead of just IsNull e.g.:
```
$emptyStr ??~ $emptyStr2 ??~ $real
```
Not crazy about that operator token.

**Comment by 237dmitry** [comment]
> In the second case, the null assignment only checks for null values, not falsey ones.

Yes, I agreed

> `??~`

This is beauty ))

**Comment by rjmholt** [comment]
> that checked IsNullOrEmpty

I was thinking the underlying test would be [`LanguagePrimitives.IsTrue(value)`](https://github.com/PowerShell/PowerShell/blob/77054ff586d2c723114862347b798bd89f8e0c56/src/System.Management.Automation/engine/LanguagePrimitives.cs#L987). However, it looks like `-and` and `-or` don't use a `LanguagePrimitives` API:

https://github.com/PowerShell/PowerShell/blob/77054ff586d2c723114862347b798bd89f8e0c56/src/System.Management.Automation/engine/parser/Compiler.cs#L5659-L5662

> `??~`

I would normally associate `~` in an operator with regex, like [in Perl](https://www.tutorialspoint.com/perl/perl_regular_expression.htm), [bash](https://stackoverflow.com/questions/19441521/bash-regex-operator), or [Haskell](http://www.serpentine.com/blog/2007/02/27/a-haskell-regular-expression-tutorial/).

**Comment by rkeithhill** [comment]
RE `~` I was thinking "approximately".  In the 90's I worked on a graphical programming environment for engineering and we had an `~=`  operator that would compare floating point numbers such that they were considered "equal" if they were within `epsilon` of one another.  But I agree, these days `~` is more often associated with regex operations.

**Comment by vexx32** [comment]
Here's another slightly cursed option that I've probably used at some point before:

```powershell
$a = @($emptyStr, $emptyStr2, $real).Where({$_}, 1)
```

**Comment by SeeminglyScience** [comment]
> However, it looks like `-and` and `-or` don't use a `LanguagePrimitives` API:

It's confusing at a glance, but `Convert` there is an extension method that does eventually call `LanguagePrimitives`. You're (understandably) thinking of `Expression.Convert` which doesn't.

**Comment by rjmholt** [comment]
> an extension method that does eventually call LanguagePrimitives

Ah, I had my suspicions. It seemed like it was doing that given things like `'hello' -and 'goodbye'`

**Comment by rjmholt** [comment]
> Here's another slightly cursed option that I've probably used at some point before

Yeah I wrote something like this as a demo:

```powershell
function Coalesce
{
    foreach ($a in $args) { if ($a) { return $a } }
}

Coalesce $first $second 'default'
```

You could probably make this work more generally like in https://github.com/PowerShell/PowerShell/issues/8098#issuecomment-434540830 too.
