### ISSUE TITLE
ConvertTo-Json incorrectly generates output when the InputObject parameter is $null

### ISSUE THREAD

**Issue by jurjenoskam** [PowerShell/PowerShell#15590]
## Steps to reproduce

According to the [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-7.1) of ConvertTo-Json, when the InputObject parameter is `$null` no output should be generated. What actually happens is that a string containing the literal text `null` is returned.

## Expected behavior

```powershell
PS C:\data> ConvertTo-Json -InputObject $null
PS C:\data> $null -eq (ConvertTo-Json -InputObject $null)
True
PS C:\data>
```

(This is actual output of PowerShell 5.1)

## Actual behavior

```powershell
PS /home/joskam> ConvertTo-Json -InputObject $null
null
PS /home/joskam> $null -eq (ConvertTo-Json -InputObject $null)
False
PS /home/joskam>
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

...and also on:

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
I _think_ the documentation might need to be updated here. `null` is a valid JSON literal, as far as I recall, and I think the change was deliberate.

@iSazonov might remember more of the background here?

**Comment by jurjenoskam** [comment]
For what it's worth, I actually prefer the current behavior; the only reason I used the term "incorrectly generates output" is because the documentation explicitly goes out of its way to specify what is supposed to happen in this case, and then something else happened instead :)

**Comment by iSazonov** [comment]
@jurjenoskam Please open new issue in PowerShell-Docs repository.

**Comment by jurjenoskam** [comment]
I've opened [this issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/7712) in the PowerShell-Docs repo.
