### ISSUE TITLE
New-WindowsImage fails from WinPE if restore points exist

### ISSUE THREAD

**Issue by WlodekC** [PowerShell/PowerShell#15598]
## Steps to reproduce

Create WinPE with powershell added as per:
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-adding-powershell-support-to-windows-pe
Boot into WinPE (i have created bootable usb stick). Attempt to capture offline windows 10 partition where SystemProtection is enabled and there is an restore point present. If i am not mistaken, they get captured into System Volume Information folder.
```

## Expected behavior

New-WindowsImage commandlet will capture wim of windows 10 partition.

```

## Actual behavior

New-WindowsImage fails with error:
New-WindowsImage : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

note, dism.exe will successfully capture wim image

```

## Environment data

PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
The cmdlet is not in the repo. Please use Windows Feedback tool to report the issue.
