### ISSUE TITLE
My bug report

### ISSUE THREAD

**Issue by 2nleyrtonc** [PowerShell/PowerShell#15606]
## Steps to reproduce
Insrtall Powershell 7.2.0 preview 7
Launch Powershell
```powershell

```

## Expected behavior
 PowerShell launches

```

## Actual behavior

PowerShell Crashes

```

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-preview.7
OS: Microsoft Windows 10.0.20348
BufferWidth: 120
BufferHeight: 9001
```none
PowerShell Crashes... Uninstalled powershell 7.2.0 preview 7

Name                           Value
----                           -----
PSVersion                      5.1.20348.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rjmholt** [comment]
@2nleyrtonc can you provide an error message, stack trace, dump file, terminal output or any other indication of the nature of the crash?

**Comment by rkeithhill** [comment]
> Microsoft Windows 10.0.20348
That is an older Windows 10 Insider (pre-release) build.  I tried this on Windows 10 Insider build 21390 and I don't see a crash.

![image](https://user-images.githubusercontent.com/5177512/122614416-d92e2b80-d043-11eb-92de-88ed2010eb4b.png)

From preview.6 and onward, you want to be on `PSReadLine 2.2.0-beta3`.  Try `Install-Module PSReadLine -AllowPrerelease -Force -AllowClobber`.

**Comment by 2nleyrtonc** [comment]
Thanks.

I will upgrade my build … 

 

------------------------------------------------------------

Clarke, Nathaniel

**Comment by 2nleyrtonc** [comment]
Installed PSReadLine 2.2.0-beta3. then reinstalled powershell 7.2.0 preview 7 successfully. 
Thx.
