### ISSUE TITLE
Where can I ask questions / raise issues about the GuestConfiguration module?

### ISSUE THREAD

**Issue by JohnLudlow** [PowerShell/PowerShell#15605]
## Summary of the new feature/enhancement

This is more of a question than anything else. I've been looking at using the GuestConfiguration module demonstrated in a [recent DSC Community call](https://dsccommunity.org/community_calls/2021-06-02-notes/). I've had a couple of issues with it, but this could be just me doing something wrong. Either way, I'm not sure where I can discuss these issues as the Project Site URL on the [module](https://www.powershellgallery.com/packages/GuestConfiguration/3.3.0-preview0003) goes to https://github.com/PowerShell/GuestConfiguration which gives me a 404. 

It's possible that the GuestConfiguration repo has moved or is marked as private.

## Proposed technical implementation details (optional)

Correct the URL in the module or make the repo accessible.

**Comment by daxian-dbw** [comment]
@nitinbps Has the `GuestConfiguration` repo gone public?

**Comment by JohnLudlow** [comment]
@daxian-dbw  I had a message from Mike on Twitter saying he would add me to the repo.

Thanks
