### ISSUE TITLE
TabCompletion: Miscellaneous completion tests - Test completion with splatted variable

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15601]
The following test is failing on Ubuntu 20.04 in PS 7.2.0-preview.7:

https://github.com/PowerShell/PowerShell/blob/945a23234170bd5ebdace8b6d10b82754354f68f/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1#L1026-L1031

The error message is:

```
Expected a collection with size 4, but got collection with size 2 @(System.Management.Automation.CompletionResult, System.Management.Automation.CompletionResult).
```

**Comment by vexx32** [comment]
Probably related to https://github.com/PowerShell/PowerShell/pull/14623, I guess?

**Comment by rjmholt** [comment]
I think CI passed on that PR, which is strange

**Comment by daxian-dbw** [comment]
Possibly a mismatch between tests and pwsh (new tests running on old pwsh).

**Comment by iSazonov** [comment]
If there is old pwsh then only in release process because CIs are passed in PRs.
