### ISSUE TITLE
Parameter Binding Tests: Dynamic parameter is found even if globbed path does not exist

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PowerShell#15600]
The following test is failing on Ubuntu 20.04 in PS 7.2.0-preview.7:

https://github.com/PowerShell/PowerShell/blob/945a23234170bd5ebdace8b6d10b82754354f68f/test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1#L259-L265

The error is:

```
Expected an exception, with FullyQualifiedErrorId 'ParameterArgumentValidationError' to be thrown, but the FullyQualifiedErrorId was 'NamedParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand'. from /home/vsts_azpcontainer/PSPackage/download/Test/test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1:264 char:47
+         { Copy-Item "~$guid*" -Destination ~ -ToSession $null } | Sh ?
+                                               ~~~~~~~~~~
```

**Comment by iSazonov** [comment]
I wonder again how out CIs passed this in #15525. Also there was a request to redesign the code with minor breaking change.
