### ISSUE TITLE
Feature Request - Better Detailed Security for End-Users.

### ISSUE THREAD

**Issue by SirTwsted** [PowerShell/PowerShell#15619]
While implementing a PowerShell theme on both PowerShells on Windows, [Windows PowerShell & PowerShell v7+
I was looking at the list of PowerShell execution policies:  Because I needed to turn off some security in order to get a PowerShell them going..?? 😒🤔👀
And it seems to me that this leaves a huge hole in security on Windows Desktop users.
Microsoft needs to implement another policy called "secured user" that allows the user to run theme scripts locally such as this Theming script,  but in order to implement,
it would need the user to type a password to allow THAT specific particular file to always run while protecting the user from other scripts running wild in the system, like Linux does.  
preventing any malicious scripting to just run wild on peoples computers.
With the current types of execution policies list,  it would seem that its either [Open-All] or [nothing]........  but nothing in-between to protect a user.
Its either open all permissions or close all permissions.  - I have tried all of the PowerShell execution policies 
[ AllSigned,  Default,  Bypass,  RemoteSigned,  Restricted,, Undefined,  Unrestricted ] --------  Is there a way to have certain policies set while allowing only certain permitted files on a system to have permission?
I would love to know that.......

All I want is a nice theme for ALL my powershell versions and CMD thats on my computer.
I dont want to put security-holes on my computer just to enjoy some nice themes to enjoy my computer.  🤷‍♂️

**Comment by vexx32** [comment]
Execution policy is explicitly _not_ a security feature. At most, it's a safeguard against accidental changes by users who don't know what they're doing, nothing more. Execution policy can be bypassed simply by providing a command line argument to powershell.exe / pwsh.exe, regardless of which level it's set at.

**Comment by jborean93** [comment]
Adding to this, PowerShell doesn't allow a user to do something it doesn't already have the rights to. You cannot use PowerShell to elevate your rights beyond what they have already been granted, PowerShell is just another means to do what you can already with the benefit of it running as a script.

**Comment by SirTwsted** [comment]
Ok Thank you, 😜👌  So its not just actually opening up security holes to the world for anything to just use PowerShell...
.
I am also wondering,  I don't know if you guys have seen this, and what measures do you guys have against this.
Its using PowerShell / CLI to do what it wants.  https://www.youtube.com/watch?v=msO-gmd3Qyg
Its one of the main reasons why I previously asked my question. 

Anything you guys can do to prevent anything like this from just executing things without the express permission of the owner.?
I'm just curiously asking.  Because to me, this is a serious security issue.
Anyways, I hope you guys sit down and have a conversation about this and how to mitigate this to protect users.

Only wishing 😉🤞

**Comment by 237dmitry** [comment]
> Its using PowerShell / CLI to do what it wants

Where is PowerShell in the video clip?

**Comment by SirTwsted** [comment]
> 
> 
> > Its using PowerShell / CLI to do what it wants
> 
> Where is PowerShell in the video clip?

Rubber Ducky and Bash Bunny was specifically built to infiltrate and use PowerShell.
If you google it, you will see.  This is just 1 cyber security site out of thousands that shows it.
https://cyberarms.wordpress.com/2017/03/27/bash-bunny-windows-remote-shell-using-metasploit-powershell/

![picture-4](https://user-images.githubusercontent.com/15247713/122673465-916fe700-d19e-11eb-91d4-0ec58e237437.png)

![picture-3](https://user-images.githubusercontent.com/15247713/122673469-96349b00-d19e-11eb-8493-19c50fa821af.png)


The vulnerability is from from several major windows security problems. 
1 - USB port being triggered by USB and activating PowerShell from USB.
2 - Windows doesnt have a proper way of securing account users passwords, its either in plain text or hash which can both be extremely easily broken, as shown in the video by a world known network engineer with CCIE certification. 
There are even tiny programs that are portable apps used for windows, that you double click to trigger, it uses PowerShell to go into registry of the computer, and pull out the account users password.

**Comment by 237dmitry** [comment]
> powershell.exe

This is Windows PowerShell. And this code does not work in either `powershell.exe` neither in `pwsh.exe`:
```
$nc = [net.WebClient]::new()
$nc.proxy = [net.WebRequest]::GetSystemWebProxy()
$nc.proxy.Credentials = [net.CredentialCache]::defaultCredentials
$nc.proxy.Credantials
```

**Comment by vexx32** [comment]
I don't really know what you expect PowerShell to do about Windows' vulnerability issues, tbh. That's like asking zsh to fix MacOS security vulnerabilities.

The OS is responsible for fixing those. :shrug:

**Comment by rkeithhill** [comment]
I agree with @vexx32.  These are mostly OS issues you'd have if you were using another shell on Windows e.g. CMD or cygwin bash.  Consider using the Windows Feedback tool to raise these issues on Windows security.

PowerShell does provide some security "speed bumps" such as:

* Script signing support (requires execution policy AllSigned or RemoteSigned)
* PS will not execute from the current dir unless the user specifies the current dir e.g.:  .\foo.ps1 instead of foo.ps1
* PS does not define an "Open" verb to prevent users from getting into trouble by double-clicking .ps1 email attachments.  This avoids I LOVE YOU.vbs virus type issues.
* JEA remoting endpoints - this is for using a remote server but it limits what commands users have access to on the remote server.

Also, you can disable PSRemoting if that is a concern.
