### ISSUE TITLE
Tab Autocomplete not working as expected anymore

### ISSUE THREAD

**Issue by artifact4727** [PowerShell/PowerShell#15613]
### Discussed in https://github.com/PowerShell/PowerShell/discussions/15612

<div type='discussions-op-text'>

<sup>Originally posted by **artifact4727** June 19, 2021</sup>
Somewhere on the Internet I read that a .NET framework update could change the order of autocomplete.

E.g, if you have the files:
foo.bat 
foo_bar.bat
foo_bar_foo.bat

If you typed "foo "Tab key was stepping through them in descending order. Which makes sense IMHO because foo is a closer match to "foo.bat" than to "foo_bar_foo.bat". However, suddenly it started iterating backwards for me and I assume it has something to to with .NET framework as I wrote initially.  Can you still, please check if this behavior is possible to fix within Powershell Core? I would be very thankful since it makes my life easier.</div>

**Comment by iSazonov** [comment]
Please continue in https://github.com/PowerShell/PowerShell/discussions/15612
