### ISSUE TITLE
PS 7.1.3 and SMBv1/SMBv2 detection and disabling commands blocks PS

### ISSUE THREAD

**Issue by jmroyb** [PowerShell/PowerShell#15610]
Hi folks,

based on [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-US/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3). Please see my testings:

```
## Steps to reproduce
SMBv1 detection:
1. Start PS 7.1.3 as admin
2. Run Get-WindowsOptionalFeature -Online -FeatureName smb1protocol  
**Result: PS blocked**

SMBv1 disabling:
1. Start PS 7.1.3 as admin
2. Run Disable-WindowsOptionalFeature -Online -FeatureName smb1protocol 
**Result: PS blocked**

SMBv2 detection:
1. Start PS 7.1.3 as admin
2. Run Get-WindowsOptionalFeature -Online -FeatureName smb2protocol  
**Result:    EnableSMB2Protocol: true ** (fast and PS does not blocks)

SMBv2 disabling:
1. Start PS 7.1.3 as admin
2. Run Disable-WindowsOptionalFeature -Online -FeatureName smb2protocol 
**Result: PS blocked**

SMBv3 detection:
1. Start PS 7.1.3 as admin
2. Run Get-WindowsOptionalFeature -Online -FeatureName smb3protocol  
**Result:    EnableSMB2Protocol: blank message ** (fast without blocked)

```
## Expected behavior
1. SMBv1 detection:  Some message describing if protocol is installed or not as fast as possible.
2. SMBv1 disabling:  Some message describing if protocol has been disabled as fast as possible.
3. SMBv2 detection:  seems OK
4. SMBv2 disabling:  Some message describing if protocol has been disabled as fast as possible.
5. SMBv3 detection:  Some message describing if protocol is installed or not as fast as possible.

## Actual behavior

PS is blecked and must be close by X close windows button

```

## Environment data

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by doctordns** [comment]
Actually PowerShell is not 'blocked', at least here.

The actual error message is not 'blocked' but:
```powershell
PS C:\Foo> Get-WindowsOptionalFeature -Online -FeatureName smb1protocol
Get-WindowsOptionalFeature: The requested operation requires elevation.
```
If you run the command in an elevated console, it is not blocked.

**Comment by jmroyb** [comment]
Please see step 1 step on every test : Start PS 7.1.3 as admin. I'm testing as elevated console.

**Comment by jborean93** [comment]
What do you mean by blocked, what's the actual error you get back?

**Comment by jmroyb** [comment]
> What do you mean by blocked, what's the actual error you get back or does it just not do anything and seems like it never runs?

I am referring I cannot break the execution of the command with CTRL+Break and I have to close PS using X button on top right of the PS window

**Comment by StevenBucher98** [comment]
Hi @jmroyb is this still an issue with the latest version of PowerShell? I am unable to reproduce.
