### ISSUE TITLE
Change workflow to use Ubuntu 20.04

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15628]
cc: @TravisEz13

> Ubuntu 16.04 is being deprecated. It is not recommended for new users.
> If any of your workflows use Ubuntu 16.04, migrate to Ubuntu 20.04 or 18.04.

[actions/virtual-environments#3287](https://github.com/actions/virtual-environments/issues/3287)

**Comment by xtqqczze** [comment]
There are brownouts scheduled for the following dates and times, where Ubuntu 16.04 builds will fail:
> September 6, 2021 5:00pm UTC – 10:00pm UTC
> September 14, 2021 5:00pm UTC – 10:00pm UTC

**Comment by iSazonov** [comment]
I see .Net team will continue support 16.04 in .Net 5.0 and 6.0.

**Comment by xtqqczze** [comment]
> I see .Net team will continue support 16.04 in .Net 5.0 and 6.0.

Yes it seems so, but we still need to change CI workflow for Azure Pipelines.

**Comment by anmenaga** [comment]
Maintainer review: the result of discussing this was to switch to Ubuntu 20.
FYI. @JamesWTruher started this work, but away for some time.

**Comment by iSazonov** [comment]
For reference #15663

**Comment by xtqqczze** [comment]
Fixed by https://github.com/PowerShell/PowerShell/pull/15906.
