### ISSUE TITLE
PowerShell 7 not reporting updated environment variable values if setting them in PowerShell 5.1

### ISSUE THREAD

**Issue by loxia01** [PowerShell/PowerShell#15626]
## Steps to reproduce
Set a new value for an environment variable (have tested with TEMP/TMP) in PowerShell 5.1 using the `SetEnvironmentVariable` method. Then, in PowerShell 7, issue a command to get the value of the environment variable, either using the `GetEnvironmentVariable` method or `Get-ItemProperty` for the registry value, in this case: `Get-ItemProperty Registry::HKCU\Environment`. 
```powershell

```

## Expected behavior
PowerShell 7 reporting the correct updated value for the environment variable or the registry entry.
```none

```

## Actual behavior
PowerShell 7 will report the old NOT updated value. This behavior is persistent across reboots. However, if referencing the environment variable using the `$env:` notation, the correct value is used.
```none

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
The SetEnvironmentVariable() method has overloads for various use cases, but the default option for it only sets the environment for the current process only. You need to provide additional options if you want that to persist to other new processes.

**Comment by loxia01** [comment]
OK, but if I change the environment registry values directly with `Set-ItemProperty` in PowerShell 5.1, PowerShell 7 shows the same behavior in reporting the wrong environment values.

**Comment by vexx32** [comment]
To my knowledge, setting the registry will not update the current logged in user's environment. As I understand it, the OS reads those registry values on startup (for machine-scope variables) and on login (for user-scope variables). I'm sure there are ways to update the user scope variables on the fly, but I think doing so requires a p/invoke call as well as the registry change -- I think .NET normally handles that when you call SetEnvironmentVariable() with the appropriate parameters to set the variables at the proper scopes.

**Comment by loxia01** [comment]
This issue is persistent across reboots/logins. PowerShell 7 still shows the old environment variable value after reboot/login, but `$env:TEMP` contains the correct value.

**Comment by vexx32** [comment]
Hmm. Which installation method are you using? MSI? MSIX? Windows Store?

**Comment by rkeithhill** [comment]
I can't repro this.  If I set a USER env var in Windows PowerShell and then start up a new PS 7, it sees the env var.  It seems you do have to start a new instance of PowerShell to see the newly defined "USER" env var.  That is consistent with my understanding that env vars are read at process start time.  If you use `$env:` to get/set an env var, you are setting a PROCESS env var which is only visible to that process.

![PowerShellEnvVarSet](https://user-images.githubusercontent.com/5177512/122800744-8c836400-d280-11eb-8e62-c7cdb597e7ac.gif)

Maybe you can post the exact commands you are using?  Also, if your issue is with `[System.Environment]::GetEnvironmentVariable()`, you should bring that up in the .NET FX repo: https://github.com/dotnet/runtime

**Comment by loxia01** [comment]
> 
> 
> Hmm. Which installation method are you using? MSI? MSIX? Windows Store?

Windows Store.

**Comment by vexx32** [comment]
Hmm. If you can try a more recent preview version, I'd be interested to see if that changes what you see. I know @SteveL-MSFT had been working on some issues that looked pretty similar to this one.

This might be another case of the Windows Store sandboxing pwsh into a contained environment which we hit a few times in the past.

**Comment by loxia01** [comment]
Did some more testing and oddly this issue only seems to affect the TEMP & TMP environment variables (and corresponding registry entries). Tested with PATH variable and a custom created environment variable and in those cases everything seemed to be working as expected.
Also tested to manually change registry values for TEMP and TMP in RegEdit and got the same issue with PowerShell 7 not reporting the updated values even after reboot/logout.

**Comment by loxia01** [comment]
> 
> 
> Hmm. If you can try a more recent preview version, I'd be interested to see if that changes what you see. I know @SteveL-MSFT had been working on some issues that looked pretty similar to this one.
> 
> This might be another case of the Windows Store sandboxing pwsh into a contained environment which we hit a few times in the past.

I will try that as soon as I get time.

**Comment by 237dmitry** [comment]
This works regardless of the version of PowerShell. After shell restarting.
```
[environment]::SetEnvironmentVariable('TMP','A:\TMP','User')
```

**Comment by loxia01** [comment]
Have now tested in 7.2.0-preview.7 and there it is working as expected!
