### ISSUE TITLE
Add missing `Remove-Alias` HelpUri

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15625]
The `RemoveAliasCommand` has an empty `HelpUri`.

`Remove-Alias` was added in #5143 so this issue exists since [v6.0.0](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0).

**Comment by iSazonov** [comment]
//cc @sdwheeler

**Comment by xtqqczze** [comment]
@iSazonov Can you please reopen, in case we want to backport fix?

**Comment by theJasonHelmick** [comment]
Thank you @xtqqczze - this has been fixed as stated above. Resolve fixed.
