### ISSUE TITLE
Start-Process: strange behavior when using a file variable

### ISSUE THREAD

**Issue by reneederer** [PowerShell/PowerShell#15623]
c:\test.ps1 exists and is an empty file.

```
Start-Process -filepath powershell -argumentlist { -noexit -file "c:\test.ps1" }
```
opens a new powershell window and keeps it open.

Instead,
```
$a = "c:\test.ps1"
Start-Process -filepath powershell -argumentlist { -noexit -file "$a" }
```
briefly flashes a new Powershell window and then closes it immediately.
I wonder why?

(I tested this with versions 7.1.3 and 5.1.19041.1023, it happens with both)

**Comment by 237dmitry** [comment]
```
Start-Process -filepath powershell -argumentlist  "-noexit -file $a" 
```

**Comment by reneederer** [comment]
Thank you, this works. Are variables not resolved when using curly braces? Is this a workaround or intended?

**Comment by vexx32** [comment]
By way of explanation; the -ArgumentList value for Start-Process is a string. If you supply a scriptblock as you did in the OP, the literal string value of the scriptblock will be used -- it's roughly the same thing as if you'd put the whole argument within single quotes. As a result the $a variable wouldn't have been expanded, so the file wouldn't be found in that instance. 🙂
