### ISSUE TITLE
Settings to turn this section off?

### ISSUE THREAD

**Issue by RobFosterNYC** [PowerShell/PowerShell#15636]
Is there any way I can go into the settings for powershell and just turn off this section.?

![Screenshot_35](https://user-images.githubusercontent.com/18384135/122853894-eddb1f80-d2e0-11eb-87a8-dee907735d1e.png)

**Comment by rkeithhill** [comment]
Create an environment variable `POWERSHELL_UPDATECHECK` and set it to `Off`.  See the [docs on this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.1).

 In your Windws Terminal setting for Windows PowerShell, add the command line arg `-NoLogo`: 
 
![image](https://user-images.githubusercontent.com/5177512/122858913-5a9dec00-d2d8-11eb-989b-783ddb6b9dee.png)

That should get rid of of the startup text.

**Comment by RobFosterNYC** [comment]
Perfect - Thank you @rkeithhill
