### ISSUE TITLE
#Requires -Command "some-command"

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShell#15649]
## Summary of the new feature/enhancement

As a shell scripting language, PowerShell scripts often depend on a non-PowerShell CLI such as `git`, `kubectl`, or `az`. These requirements should have the same support as other requirements implemented with the `#Requires`  directive.

## Proposed technical implementation details (optional)

When the interpreter sees a `#Requires -Command "some-command"` directive, it will invoke `Get-Command "some-command"`. If the result of that invocation is null/empty, it will throw an assertion error equivalent to existing `#Requires` directives.

**Comment by rjmholt** [comment]
My personal perspective on this is that `#requires` is a generally poorer substitute for doing something like `Get-Command git -ErrorAction Stop`. `#requires` is harder to reason about, compose with other language elements and generalise, and it's often run at a different time to when users expect it (for example, commands are available based on the `$env:PATH`, which can be modified by a script, but a script with `#requires -Command` in it will fail before it can modify the `$env:PATH`).

**Comment by chriskuech** [comment]
I agree requires is not ideal for all situations, but it seems like at least a few of your complaints are with PowerShell's existing implementation of `#requires` and would best be addressed by ensuring `#requires` throws a transparent exception (even if it can't be caught within the same script) and ensuring the exception message contains enough information to reason about.
