### ISSUE TITLE
$Host.UI.RawUI hangs when executed in noninteractive container environment

### ISSUE THREAD

**Issue by VeryEarly** [PowerShell/PowerShell#15647]
## Description
$Host.UI.RawUI hangs in noninteractive container (not docker) at odd time executions.
For example, 
```powershell
Write-Output "First try"
$Host.UI.RawUI
Write-Output "Second try"
$Host.UI.RawUI
Write-Output "Third try"
$Host.UI.RawUI
Write-Output "Fourth try"
$Host.UI.RawUI
```
execution will be hung after "First try", user need to press enter to resume, same behavior remain after "Third try". Second try and fourth try went smooth.

There are no problem with execution of following command:
```powershell
$Host
$Host.UI
$Host.UI.RawUI.Lengthinbuffercells('3')
```
or other public member of "System.Management.Automation.Internal.Host.InternalHostRawUserInterface" 

## Steps to reproduce

Require container (SQLPAL) environment provided by Resilliency team, however PowerShell script executed in it are as simple as I listed above.

## Expected behavior

```none

```

## Actual behavior

```none

```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.9200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0à}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
Finished
```

**Comment by iSazonov** [comment]
Does the hang occur on Write-Output command or on $Host.UI.RawUI?

> noninteractive container
> user need to press enter to resume

Has the container a console?

Is there an test environment where we could investigate the issue?

Could you run `pwsh -NonInteractive` and check again?

**Comment by VeryEarly** [comment]
> Does the hang occur on Write-Output command or on $Host.UI.RawUI?
> 
> > noninteractive container
> > user need to press enter to resume
> 
> Has the container a console?
> 
> Is there an test environment where we could investigate the issue?
> 
> Could you run `pwsh -NonInteractive` and check again?

Hi @iSazonov 

I do not think there is a visible console I can see.

I created VM for this case, maybe I can share screen with you tomorrow to show how to reproduce. (it's not straight forward to set up the environment).

I tried pwsh -NonInteractive and it didn't help.

**Comment by rjmholt** [comment]
If you use `$null = $Host.UI.RawUI` instead, does the problem still occur?

**Comment by rjmholt** [comment]
Also given your mention of SQLPAL, you might want to reach out to the PowerShell team directly

**Comment by VeryEarly** [comment]
Hi @iSazonov @rjmholt ,

Thanks for the prompt response. After discussed with SQLPAL team, this is a bug in their environment (shortage in their PeekConsoleInput API). Will close this issue.

Thanks
