### ISSUE TITLE
`Update-Help` fails for module `PackageManagement`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15654]
Blocking CI.

```
PS C:\source\PowerShell> Update-Help -Module PackageManagement -UICulture en-US -Verbose
VERBOSE: Resolving URI: "https://aka.ms/powershell70-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.0/"        
VERBOSE: Performing the operation "Update-Help" on target "PackageManagement, Current Version: 0.0.0.0, Available Version: 7.0.1.0, UICulture: en-US".
VERBOSE: Resolving URI: "https://aka.ms/powershell51-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-5.1/"        
VERBOSE: Performing the operation "Update-Help" on target "PackageManagement, Current Version: 0.0.0.0, Available Version: 5.2.0.0, UICulture: en-US".
VERBOSE: PackageManagement: Updated C:\Users\xtqqczze\Documents\PowerShell\Help\PackageManagement\1.0.0.1\en-US\Microsoft.PowerShell.PackageManagement.dll-Help.xml. Culture en-US Version 5.2.0.0
Update-Help: Failed to update Help for the module(s) 'PackageManagement' with UI culture(s) {en-US} : Help content cannot be found. Make sure 
the server is available and the help content location is properly defined in the HelpInfo XML..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

**Comment by rjmholt** [comment]
I just tried to reproduce this:

```console
> Update-Help -Module PackageManagement -Force -Scope CurrentUser -Verbose -UICulture en-US
VERBOSE: Resolving URI: "https://aka.ms/powershell70-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7/"
VERBOSE: Performing the operation "Update-Help" on target "PackageManagement, Current Version: 0.0.0.0, Available Version: 7.0.1.0, UICulture: en-US".
VERBOSE: PackageManagement: Updated C:\Users\Robert Holt\Documents\PowerShell\Help\PackageManagement\en-US\Microsoft.PowerShell.PackageManagement.dll-Help.xml. Culture en-US Version 7.0.1.0
VERBOSE: Resolving URI: "https://aka.ms/powershell51-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-5.1/"
VERBOSE: Performing the operation "Update-Help" on target "PackageManagement, Current Version: 0.0.0.0, Available Version: 5.2.0.0, UICulture: en-US".
VERBOSE: PackageManagement: Updated C:\Users\Robert Holt\Documents\PowerShell\Help\PackageManagement\1.0.0.1\en-US\Microsoft.PowerShell.PackageManagement.dll-Help.xml. Culture en-US Version 5.2.0.0
```

**Comment by xtqqczze** [comment]
> I just tried to reproduce this, but I don't get the error at the end for some reason:
> 
> ```
> > Update-Help -Module PackageManagement -Force -Scope CurrentUser -Verbose -UICulture en-US
> VERBOSE: Resolving URI: "https://aka.ms/powershell70-help"
> VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7/"
> VERBOSE: Performing the operation "Update-Help" on target "PackageManagement, Current Version: 0.0.0.0, Available Version: 7.0.1.0, UICulture: en-US".
> VERBOSE: PackageManagement: Updated C:\Users\Robert Holt\Documents\PowerShell\Help\PackageManagement\en-US\Microsoft.PowerShell.PackageManagement.dll-Help.xml. Culture en-US Version 7.0.1.0
> VERBOSE: Resolving URI: "https://aka.ms/powershell51-help"
> VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-5.1/"
> VERBOSE: Performing the operation "Update-Help" on target "PackageManagement, Current Version: 0.0.0.0, Available Version: 5.2.0.0, UICulture: en-US".
> VERBOSE: PackageManagement: Updated C:\Users\Robert Holt\Documents\PowerShell\Help\PackageManagement\1.0.0.1\en-US\Microsoft.PowerShell.PackageManagement.dll-Help.xml. Culture en-US Version 5.2.0.0
> ```

I no longer get the error either, maybe the issue is resolved?

**Comment by rjmholt** [comment]
> I no longer get the error either, maybe the issue is resolved?

Apparently an aka.ms link was broken and has been fixed. I'll open a PR to revert the test workaround.

**Comment by sdwheeler** [comment]
I recently changed the module markdown files to use https://aka.ms/powershell70-help instead of the FWLink. There was in error in the target URL for powershell70-help. That has been fixed so update help should be working now.
