### ISSUE TITLE
Command tab completion should not look for commands in current path if not in FileSystem provider

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#15652]
## Summary of the new feature/enhancement
Tab-completing commands while in a slow provider (VMware datastore, SCCM, etc.) is painfully slow.

Demonstration:

```
cd C:\
Measure-Command -Expression {TabExpansion2 -inputScript Get-ChildItem -cursorColumn 1}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 35

cd vmstores:\vcenter01@443\test\datastore01
Measure-Command -Expression {TabExpansion2 -inputScript Get-ChildItem -cursorColumn 1}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 8
Milliseconds      : 254
```
I think this is because it looks for commands to execute in the current path, which makes sense on a filesystem with commands like ping.exe but not in many/any other providers. For example even if you cd into the Function provider and try to tab complete a function you will get something like `.\prompt` which isn't even a valid command.

## Proposed technical implementation details (optional)
There are a few options:

- Don't look for commands in the current path if the current path isn't from a filesystem provider.
- Don't look for commands in the current path unless the user has typed in something that looks like a path like .\
- Add either an opt-in or opt-out system for providers so they can control this behavior.

**Comment by iSazonov** [comment]
I remember I did a proposal to add new attribute to mark parameters where it make sense to fallback to FileSystem provider. This could resolve issue. And I believe it would be acceptable breaking change.

**Comment by MartinGC94** [comment]
That's a different (but highly desirable feature). What I'm talking about is tab-completing commands, not their parameters or parameter values. If you CD into a slow location you don't get a noticeable slowdown when tab completing parameters or parameter values (unless they have to fall back to path completion).

**Comment by mklement0** [comment]
👍 re the issue at hand; as for the fallback issue: see #14147
