### ISSUE TITLE
-split doesn't emit quotation marks to its script block

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell#15655]
Hello, Amazing PowerShell Team! 😊

I was trying to write a script that splits a string but understand string qualifiers too because `$Content -split ';'` alone doesn't work. My solution was to use the `<String> -Split {<ScriptBlock>}` syntax. (See [about_Split][1] for details.) It didn't work. I attached a debugger to my code and observed that `-split` doesn't emit quotation marks (`'` and `"`) to its script block.

**Important notice:** I'm not here to ask for workarounds or solutions to my script's problem. Please focus on the bug report.

## Steps to reproduce

```powershell
$Content = $env:Path+'"C:\;";'

$AreWeInsideASubstring = $False
$Content -split { 
  if ($_ -eq '"') {
    $AreWeInsideASubstring = -not $AreWeInsideASubstring
    return $False
  }
  if ($_ -eq ';') {
    return (-not $AreWeInsideASubstring)
  }
}
```

## Expected behavior

```none
C:\Windows\system32
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0
C:\Program Files\PowerShell\7\
C:\Program Files\dotnet\
"C:\;"
```

## Actual behavior

```none
C:\Windows\system32
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0
C:\Program Files\PowerShell\7\
C:\Program Files\dotnet\
"C:\
"
```

## Environment data

```none
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

[1]: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_split?view=powershell-7

**Comment by vexx32** [comment]
I checked with a slightly simpler use case:
```powershell
$Content = 'otherstuff;"C:\;";otherstuff'

$Content -split {
    Write-Host "char: $_"
    $false
}
```

<details>
<summary><strong>Results</strong>

```
o
t
h
e
r
s
t
u
f
f
;
"
C
:
\
;
"
;
o
t
h
e
r
s
t
u
f
f
otherstuff;"C:\;";otherstuff
```

</details>

This shows that the `"` are correctly given to the scriptblock. The `'` characters delineate the string literal itself, so are not part of the string's characters. If you add `$env:PATH` and the string `'"C:\;";'`, the same happens. The single quotes aren't included in the string, they're only the syntax markers that tells pwsh that that token is a string.

**Comment by vexx32** [comment]
I played with this a bit and I think the fundamental issue here is actually one of scoping. The `$AreWeInsideASubstring` variable is not looking in the expected scope. This appears to work as expected:

```powershell
$Content = $env:Path + '"C:\;";'

$substring = $false
$Content -split { 
  if ($_ -eq '"') {
    $script:substring = -not $script:substring
    return $False
  }
  if ($_ -eq ';') {
    return (-not $script:substring)
  }
}
```

**Comment by skycommand** [comment]
The scope was the first thing that I thought of. But when I tried to test it using the Debugger, I noticed the skipping issue that I am reporting.

Okay, this clearly needs more testing on my side. I might have to report a debugger bug after all. 

Thanks for your help. Closing.
