### ISSUE TITLE
Switching to ICU

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#15668]
### Summary of the new feature / enhancement

We caught an amazing problem in #14513 - a test failed because of a difference in string sorting on different platforms.

I tested on different Windows systems and was very amazed to see different behavior on _different Windows_ versions too.

After consulting with .Net team it turned out that although the latest versions of .Net work with ICU but _Windows 10 older versions do not support ICU completely_. This is the version used in PowerShell CI Windows. 

See https://github.com/dotnet/runtime/issues/54472#issuecomment-867108314 and follow comments.

If we want to have full consistency across all platforms and versions we should include System.Globalization.AppLocalIcu package in our Windows distribution.

This probably makes sense since users may also encounter unpredictable string handling and sorting is just one of those scenarios.

### Proposed technical implementation details (optional)

https://github.com/dotnet/runtime/issues/54472#issuecomment-867108314

```
<ItemGroup">
  <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2" />
</ItemGroup>
```

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we are concerned about the additional size of the dlls being pulled in from the ICU package vs the benefit of this change due to a locale not being specified.   We do not approve to add a dependency on this package.

**Comment by vexx32** [comment]
How big are these DLLs?

**Comment by iSazonov** [comment]
> How big are these DLLs?

Up to 40 MB.

I closed the issue since users can manually install ICU on old Windows versions and manually configure PowerShell to use App-local ICU in runtimeconfig.json https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu
