### ISSUE TITLE
Support self-updating pwsh

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#15666]
## Summary of the new feature/enhancement

Similar to how Chrome and VSCode have a self-updating feature that informs the user a new version is available and that a restart will run the new version, we should have something similar for pwsh.  Some things we need to work through:

- Is this a new package or something that could/should be supported by our existing packages? (MSI, Snap, zip, etc...) Sandboxed packages like Snap and msix wouldn't be self-updating, but they already have their own updating model.
- What about LTS, stable, and preview channel support?
- From a size perspective, we would need to lay down a side-by-side copy of PS7 and perhaps just update symlinks, but would there be a concern about disk usage?
- Need to think about configuration so user can opt-out.
- Also need to consider which remote source is being used and how that impacts enterprises which have restrictions on remote network locations that are allowed.
- Presumably, this is built into the Console host.

**Comment by iSazonov** [comment]
>  we should have something similar for pwsh

Why for? Who will be the consumer? Are there really so many that a special update channel is required?
Usually you say that this should be a separate community project. :-)

> What about LTS, stable, and preview channel support?

In general it doesn't matter. This is the concern of the update service.

> Presumably, this is built into the Console host.

Let's look how other applications do (on Windows):
1. Need specific update service with installer elevated permissions and permissions to download new version.
2. Need schedule tasks to trigger checks, notifications and install/update/upgrade
3. Application it self trigger p.2.

If an application has not the elevated update service the update process will ask user to elevate.

> Presumably, this is built into the Console host.

I hope this doesn't happen in pwsh itself. There are already many means for updating applications. Now also winget. It is their task to implement the required update model.

This can most likely only be implemented on the basis of links and my main concern is that it is completely incompatible with WindowsUpdate.

**Comment by WSLUser** [comment]
Bash updates itself through a package manager.  You could have multiple terminal panes/tabs/windows using the same host and the other bash sessions will continue working while the updates continue. and either require resourcing bash or restarting the host. Pwsh could do similar and I'm presuming this request is to help users of WinGet more than users on other systems.

**Comment by theJasonHelmick** [comment]
@iSazonov - I see your point about the various update channels. I think having a notification and upgrade within PowerShell would serve linux customers already accustomed to the experience - and it gives an additional option to Windows users.

**Comment by Almagnus1** [comment]
IMO a command like update-powershell would do wonders for usability.

**Comment by RokeJulianLockhart** [comment]
This would solely be useful in an uncontrolled environment. Were it implemented, it would need to be disabled in standard packages due to it interfering with the expected update cycles. Perhaps a compile-time flag would be best.

**Comment by TomasHubelbauer** [comment]
Could this get re-opened? I just went in looking for an open suggestion for a self-updating command after updating PowerShell from 7.4.0 to 7.5.0 by downloading the installer off the GitHub release and running it and wondering why this is still the way to do this in 2025. Like was already mentioned, tools like VS Code and even CLI-based tools like Bun have self-updating commands making it a breeze. This level of polish, user-friendliness and developer experience would be really welcome for PowerShell as well.
