### ISSUE TITLE
Mixing initialized and uninitialized properties in custom classes breaks the ordering of properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15679]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

```powershell
class Custom {
  [string] $A
  [string] $B
  [string] $C = 'value'
}

[Custom]::new()
```

### Expected behavior

```console
A B C
- - -
    value
```

### Actual behavior

```console
C     A B
-     - -
value
```

### Environment data

```powershell
PowerShell Core 7.2.0-preview.7
```

**Comment by iSazonov** [comment]
Is this ask about Formatting Subsystem or Engine API?

**Comment by mklement0** [comment]
Engine.

**Comment by IISResetMe** [comment]
I took a look at this issue after first determining the formatting behavior seems to have changed around the release of 6.1.

While trying figure out whether I could pinpoint the change in behavior in the underlying `System.Reflection.Emit` library between FX and Core (thereby establishing some pre-change "baseline"), I accidentally found that even on .NET Framework/WPS, the member order of dynamic types _is not consistent either_:

```powershell

powershell -c {
  class C {
    [int]$A
    [int]$B = 123
  }

  $a = [C]@{}

  'Reflected order: [{0}]' -f $([C].GetProperties().Name -join ', ')

  $a
}

powershell -c {
  class C {
    [int]$A
    [int]$B = 123
  }

  $a = [C]@{} |Format-Table

  'Reflected order: [{0}]' -f $([C].GetProperties().Name -join ', ')

  $a
}
```

The only difference here is that the first command enumerates the property metadata _before_ letting the formatting subsystem render an instance of `[C]`, whereas the second one does it _after_ - and somehow that affects _both_ the type created AND the order in the type adapter - going all the way back to at least 5.1:

![image](https://user-images.githubusercontent.com/7413755/168093676-9551b5e4-2190-4a18-bf3c-def5e366eb32.png)

I'll keep digging and see what comes up (let me know if you have any ideas or more surprising examples @mklement0) :)
