### ISSUE TITLE
PowerShell 7.2-Preview.7 bombs in Windows Terminal with System.TypeLoadException

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#15673]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

Just did the automatic Windows update to PowerShell 7.2 Preview.7.
![Posh_WU_2021-06-25_9-34-08](https://user-images.githubusercontent.com/19892435/123437237-738af380-d59d-11eb-9bd3-5b18a83f2752.jpg)

1. Click on Wndows "Start", then on the PowerShell 7.2 Preview shortcut.
2. Windows Terminal opens, but PowerShell ends with an System.TypeLoadException: System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

![Posh72prev72021-06-25_9-58-14](https://user-images.githubusercontent.com/19892435/123435897-12165500-d59c-11eb-9412-93e76ba48a97.jpg)

### Expected behavior

```console
To get to the PowerShell prompt without exceptions errors.
```

### Actual behavior

```console
trying to open PowerShell Preview:

PowerShell 7.2.0-preview.7
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\max_t>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-preview.7
OS: Microsoft Windows 10.0.21390
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
'''

'''

### Exception
'''
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset() in Microsoft.PowerShell.PSReadLine2.dll:token 0x60004ca+0x0
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset() in Microsoft.PowerShell.PSReadLine2.dll:token 0x600049b+0x7
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics) in Microsoft.PowerShell.PSReadLine2.dll:token 0x6000101+0x118
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken) in Microsoft.PowerShell.PSReadLine2.dll:token 0x60000fa+0x60
```
```


### Environment data

```powershell
Microsoft Windows [Version 10.0.21390.2025]

Windows Terminal Preview: Version: 1.9.1523.0
```

**Comment by MaximoTrinidad** [comment]
This has been happening to me since PowerShell 7.2-preview.6:https://github.com/PowerShell/PowerShell/issues/15496
But this issue was closed with no explanation nor resolution.

**Comment by iSazonov** [comment]
Yes, 2.2.0-beta3 is needed. Please report the issue in https://github.com/PowerShell/PowerShell/discussions/15510

**Comment by MaximoTrinidad** [comment]
I'm trying to install PSRL 2.2.-beta3 with elevated privileges, but it is failing:
```
pwsh -noprofile -command "Install-Module PSReadLine -Force -SkipPublisherCheck -AllowPrerelease -Scope CurrentUser"
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Administrator rights are required to install or update. Log on to the computer with an account that
     | has Administrator rights, and then try again, or install by adding "-Scope CurrentUser" to your
     | command. You can also try running the Windows PowerShell session with elevated rights (Run as
     | Administrator).
```
I will figure it out! :)

**Comment by MaximoTrinidad** [comment]
So, I can manually remove the PSReadline module folder from the 'C:\Program Files\PowerShell\7-preview\Modules" location.
Now, I can open PowerShell 7.2-preview.7 without PSRL.

I still trying to install the PSRL 2.2.0.-beta3.

**Comment by MaximoTrinidad** [comment]
@iSazonov,

Strange behavior to resolve this issue. 

I had to log on with the "Administrator" user-id in order to install PSReadLine 2.2.0-Beta3.
Only then I can go back and sign on with my normal user-id and run PowerShell 7.2-Preview.7 without any issues in Windows Terminal.

I'm good now! But have I notice that when I sign on with the Administrator ID, PowerShell will open the prompt outside Windows Terminal App. I never had to use the Administrator ID for anything, until now.

**Comment by iSazonov** [comment]
Installing to C:\program files\ has always required elevated permissions.

**Comment by aungminko93750** [comment]
________________________________
