### ISSUE TITLE
Compiler reserved method name surfaced for record types

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#15672]
### Steps to reproduce

```powershell
Add-Type -TypeDefinition 'public record Person(string Name);'

$person = [Person]::new('Ted')
$person | Get-Member
$person.'<Clone>$'()
```

### Expected behavior

I honestly don't know.  Aside from actually implementing a similar `with` syntax, I don't know what the engine should do about this. Hide the method all together? Pretend it's actually called `Clone`?

But it seems odd for such a big C# feature to have such awkward usage and completion results in PowerShell.  If nothing else it should probably be documented somewhere.

### Actual behavior

```console
TypeName: Person

Name        MemberType Definition
----        ---------- ----------
<Clone>$    Method     Person <Clone>$()
Deconstruct Method     void Deconstruct([ref] string Name)
Equals      Method     bool Equals(System.Object obj), bool Equals(Person other), bool IEquatable[Person].Equals(Person other)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
Name        Property   string Name {get;set;}

Name : Ted
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.7
PSEdition                      Core
GitCommitId                    7.2.0-preview.7
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Also related is #13819 as all record properties are init only.

**Comment by daxian-dbw** [comment]
powershell should hide the method `<Clone>$` from `Get-Member` by default (and thus from tab completion), but allow it to be called normally at run time. The method should be shown when running `Get-Member -Force`.

Implementation wise, we can it similarly as the `hidden` member of a PowerShell class, see an example below:
```
> class bar { hidden [void] PrintName() { Write-Host "Name" } }
> $b = [bar]::new()
> $b | gm

   TypeName: bar

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()

> $b | gm -Force

   TypeName: bar

Name        MemberType   Definition
----        ----------   ----------
pstypenames CodeProperty System.Collections.ObjectModel.Collection`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, Publi…
psadapted   MemberSet    psadapted {GetType, ToString, Equals, GetHashCode}
psbase      MemberSet    psbase {GetType, ToString, Equals, GetHashCode}
psextended  MemberSet    psextended {}
psobject    MemberSet    psobject {BaseObject, Members, Properties, Methods, ImmediateBaseObject, TypeNames, get_BaseObject, get_Members, get_Proper…
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
PrintName   Method       void PrintName()     ## <==== the hidden member
ToString    Method       string ToString()

> $b.PrintName()
Name
```

One thing I'm not very clear is how the method `<Clone>$` gets hidden by C# intellisense. I cannot find anything in IL that indicates it's hidden, and my theory is that C# compiler just treats any member start with `<` and ends with `>$` as a hidden members. Filtering based on `<` prefix and `>$` suffix would be a breaking change, but should fall in the bucket 3.

**Comment by SeeminglyScience** [comment]
> One thing I'm not very clear is how the method `<Clone>$` gets hidden by C# intellisense. I cannot find anything in IL that indicates it's hidden,

Yeah there's nothing in the metadata that would help. It would have been great if they just slapped a `EditorBrowsable` on it at the very least but no such luck :/

> and my theory is that C# compiler just treats any member start with `<` and ends with `>$` as a hidden members. Filtering based on `<` prefix and `>$` suffix would be a breaking change, but should fall in the bucket 3.

Hard to nail down the exact code in roslyn responsible but the best I can tell is it ignores anything it considers "uncallable". Pretty much "does this contain any character which isn't in our identifier token pattern" which is a lot more strict then PowerShell's standards.

I think your plan is probably the best bet.  They use the same pattern for top level statements as well (`<Program>$.<Main>$()`) so it should hopefully catch future additions.

**Comment by vexx32** [comment]
We discussed this in the Engine working group meeting (2021/07/22). We agree that these members should be hidden by default. Given that they're accessible from reflection, we also agree that it doesn't make sense to actively prevent users from invoking them if they choose to do so; the syntax of the method is sufficiently unusual that it's unlikely to be hit by accident, especially if we hide it from tab completion.
