### ISSUE TITLE
Provide more descriptive error message for `Set-Location` permissions error

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#15680]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

![image](https://user-images.githubusercontent.com/23485114/123624139-76971580-d823-11eb-9ccc-11881e3e0369.png)

### Expected behavior

```console
Write "Access is denied." (like Command Prompt) because `C:\$bitmap` exist.
```

### Actual behavior

```console
Set-Location: Cannot find path 'C:\$bitmap' because it does not exist.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by joeyaiello** [comment]
@PowerShell/area-cmdlets-management decided that this can be fixed by handling an access denied exception and giving a more descriptive error message. This isn't a top priority, but we would accept it from the community as an `Up-for-grabs` issue

**Comment by ayousuf23** [comment]
@joeyaiello I am interested in resolving this issue. Please let me know which file contains the relevant code for `Set-Location`

**Comment by iSazonov** [comment]
@ayousuf23 Joey left the project.

The code you ask https://github.com/PowerShell/PowerShell/blob/186d6be47d858460a3d0ba6abd81f779cb633b55/src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs#L714

**Comment by ayousuf23** [comment]
@iSazonov How I can a deny access to a particular folder in Windows? I tried to do so using the security tab, but PowerShell was still able to access the folder.

**Comment by iSazonov** [comment]
@ayousuf23  You could try to use an existing system folder for the test.

**Comment by ayousuf23** [comment]
@iSazonov I did some digging and I found that when `Set-Location 'C:\$bitmap'` is called, PowerShell tries to check if the file exists. Eventually, a method called `Microsoft.PowerShell.Commands.FileSystemProvider.GetFileSystemInfo` is called. 

This method creates a new `System.IO.FileInfo` object. Unfortunately, 'System.IO' is not throwing an exception when the `System.IO.FileInfo` object is created. Hence, the method checks the object's attributes, sees that it does not exist, and returns null. Thus, PowerShell thinks the path does not exist.

I think what should happen is that  `System.IO.FileInfo` should throw an exception when a path with security restrictions is trying to be accessed, but that is not occurring.

**Comment by iSazonov** [comment]
I think we fall in misunderstanding.
![image](https://user-images.githubusercontent.com/22290914/149633420-5abbe929-ef9a-4cf1-aabe-2d6784d1050a.png)

In typical scenario we can "see" a folder (`dir -Hidden c:\rec*`) but haven't access to its content. The screenshot demonstrates this. It is how Windows permissions work.

As for `C:\$bitmap`, it is system hidden NTFS folder - nobody can see and access it. (You can see it only in low level file system traces).

So I close the issue.
