### ISSUE TITLE
Windows Update does not fresh-install Preview 7

### ISSUE THREAD

**Issue by alexbuzzbee** [PowerShell/PowerShell#15692]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

Follow steps based on [Preview updating PowerShell 7.2 with Microsoft Update](https://devblogs.microsoft.com/powershell/preview-updating-powershell-7-2-with-microsoft-update/):

Ensure PowerShell 7.1.3 is installed but no PowerShell preview releases are installed.

Create registry values `[HKEY_LOCAL_MACHINE\Software\Microsoft\PowerShellCore]UseMU:dword=1` and `[HKEY_LOCAL_MACHINE\Software\Microsoft\PowerShellCore\InstalledVersions\39243d76-adaf-42b1-94fb-16ecf83237c8]Install:dword=1`. Additionally, as directed in a workaround described in #15510, create a registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore\InstalledVersions\31ab5147-9a97-4452-8443-d9709f0516e1`.

Ensure Windows Update is set to _Receive updates for other Microsoft products when you update Windows_. In my case, this is enforced by my organization through MDM.

Reboot and check Windows Update, installing all available updates and manually rechecking until no updates appear.

### Expected behavior

```console
PS> pwsh-preview
PowerShell 7.2-preview.7
PS>
```

### Actual behavior

```console
<See screenshot below>
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> (Get-CimInstance Win32_OperatingSystem) | Select-Object -Property Version, Caption

Version    Caption
-------    -------
10.0.19042 Microsoft Windows 10 Enterprise

PS> Get-WindowsUpdateLog

<Very long console output snipped, see below-attached file WindowsUpdate.log created by command>
```

### Visuals

![msups](https://user-images.githubusercontent.com/2061796/123836671-f4b4f400-d8d7-11eb-9678-229cea5e6e12.png)
[WindowsUpdate.log](https://github.com/PowerShell/PowerShell/files/6735103/WindowsUpdate.log)

**Comment by TravisEz13** [comment]
From windowsupdate.log, `F13D5FD1-FA6A-4F9E-88D4-8B15EA0DBA4C` is the PowerShell update and it deferred by policy on your machine.  Can you send a screen shot of your advanced windows update settings?

```
021-06-29 12:50:25.3909115 4508  8416  Agent           Update deferred by policy: F13D5FD1-FA6A-4F9E-88D4-8B15EA0DBA4C.200
```

**Comment by TravisEz13** [comment]
You probably can install this using the `PSWindowsUpdate` module (using the API).  I'm assuming whatever policy it is, it only affects Automatic Updates and not the API.

Once you have installed the module,
```powershell
Get-WindowsUpdate -CategoryIDs c90a4362-d2b6-4bb4-b316-76d14fed63a5 | Install-WindowsUpdate -Download
```
This says, get all the updates for PowerShell preview, download, and install them.

**Comment by alexbuzzbee** [comment]
Ah, yes. We have organizational policy through Endpoint Manager to defer non-security updates. That explains this.

**Comment by 237dmitry** [comment]
How could you update Powershell via Windows Update? From the first (6+ may be) to 7.1.3 i it was updated by hands (msi).

**Comment by alexbuzzbee** [comment]
@237dmitry See [this blog article](https://devblogs.microsoft.com/powershell/preview-updating-powershell-7-2-with-microsoft-update/).

**Comment by 237dmitry** [comment]
> See this blog article.

You never know who will write something.

**Comment by TravisEz13** [comment]
@alexbuzzbee RE: https://github.com/PowerShell/PowerShell/issues/15692#issuecomment-871408740, Thanks for explaining what policy was in place, the logs don't say that.   It makes the answer more complete.
