### ISSUE TITLE
Powershell on Mac : Get-NetIPAddress not recognized

### ISSUE THREAD

**Issue by nikk0** [PowerShell/PowerShell#15693]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

Hello

I installed powershell v7.1 for mac.
I am facing the following issue when executing Get-NetIPAddress: 
![pbPS](https://user-images.githubusercontent.com/8555147/123838898-c7366d80-d90c-11eb-835d-17f9e2951c37.jpg)

Is this cmdlet supposed to be supported in such env ?

Regards.

nikk0 

### Expected behavior

```console
I expect Get-NetIPAddress working.
```

### Actual behavior

```console
Get-NetIPAddress: The term 'Get-NetIPAddress' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
To my knowledge, that cmdlet is only available on Windows. It uses some Windows OS APIs that aren't available on other platforms.

A quick search seems to indicate that probably the nearest approximation currently available on Unix systems is:

```powershell
[System.Net.Dns]::GetHostAddresses($(hostname))
```

**Comment by jborean93** [comment]
> It uses some Windows OS APIs that aren't available on other platforms.

More specifically it's a CDXML cmdlet that relies on CIM/WMI and it's class to be present for it to work.  It would have to be rewritten in C#/PowerShell to be cross platform.
