### ISSUE TITLE
Can't get OperationTimeout to work with New-PsSession

### ISSUE THREAD

**Issue by Veverke** [PowerShell/PowerShell#15696]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

I can't get `OperationTimeout` setting to work with `New-PsSession`. Please refer to [this post](https://stackoverflow.com/q/68176305/1219280) I posted earlier today in StackOverflow.

In a short, I found a supposedly working snippet at [Windows Powershell In Action 2nd Edition, by Bruce Payette, at Chapter 13 - Remoting](https://livebook.manning.com/book/windows-powershell-in-action-second-edition/chapter-13/225).

I slightly adapted the script to look as follows:
```
$password = "myPass"
$domainAndUser = "myDomain&User"
$computerName = "myRemoteComputerIp"
$pwSession = convertto-securestring -AsPlainText -Force $password
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $domainAndUser,$pwSession
$pso = New-PSSessionOption -OperationTimeout (5*1000)
$session = new-pssession -computername $computerName -credential $cred -SessionOption $pso
Invoke-Command $session { 1..10 | foreach {"$_" + ('*' * $_) ; Start-Sleep 1} }
```
I expected to see the same `The WinRM client cannot complete
the operation within the time specified` error as described in the snippet from the book. But I am not able to achieve such result. Tried several variations.

Reproduces in both Powershell 5.1 and 7.1.3, on Windows. 

### Expected behavior

```console
Error `The WinRM client cannot complete
the operation within the time specified` should be displayed.
```

### Actual behavior

```console
Invoke-Command script block proceeds till completion, without being aborted due timeout.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Best that I can tell, `OperationTimeout` is only used for [WSMan operations](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsmv/10a60f39-7bb8-49b3-a4dc-2de481fef094) and not used at the PSSession layer.  I think what you want is https://github.com/PowerShell/PowerShell/issues/5434

**Comment by iSazonov** [comment]
> Best that I can tell, `OperationTimeout` is only used for [WSMan operations](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsmv/10a60f39-7bb8-49b3-a4dc-2de481fef094) and not used at the PSSession layer. I think what you want is #5434

Having both could confuse users.

**Comment by Veverke** [comment]
My confusion is really straightforward and I can't see how anyone else will not be confused the same way:

1. [New-PsSession](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssession?view=powershell-7.1) accepts a `-SessionOption` parameter (`PsSessionOption`)
2. [New-PsSessionOption](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionoption?view=powershell-7.1) configures a set of different settings, among them timeout settings, and one of them being `OperationTimeout`. Should I not naturally assume creating a `PsSessionOption` setting `OperationTimeout` should affect the `New-PsSession` created by passing this very `PsSessionOption` as a parameter ?

**Comment by Veverke** [comment]
> > Best that I can tell, `OperationTimeout` is only used for [WSMan operations](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wsmv/10a60f39-7bb8-49b3-a4dc-2de481fef094) and not used at the PSSession layer. I think what you want is #5434
> 
> Having both could confuse users.

It definitely does.

My confusion is really straightforward and I can't see how anyone else will not be confused the same way:

New-PsSession accepts a -SessionOption parameter (PsSessionOption)
New-PsSessionOption configures a set of different settings, among them timeout settings, and one of them being OperationTimeout. Should I not naturally assume creating a PsSessionOption setting OperationTimeout should affect the New-PsSession created by passing this very PsSessionOption as a parameter ?

**Comment by jborean93** [comment]
> Should I not naturally assume creating a PsSessionOption setting OperationTimeout should affect the New-PsSession created by passing this very PsSessionOption as a parameter ?

It does affect the PSSession created when it's a WSMan one but the operation timeout isn't what you think it is. It's the timeout for how long the WSMan server can take before it responds back with some data. Where this is actually used is in the `Receive` requests that PowerShell is sending to the server. The request will wait until either there is data to send back to the client or the operation timeout is hit. The standard operation is to just resend the `Receive` request when a timeout is received as that is bound to happen with any long running script. The only time `-OperationTimeout` would actually cause a failure here is if the time it took to create the actual shell/command took longer than that value. The actual running of the command is not affected.

What this really needs is a doc update to clarify what `-OperationTimeout` affects, mostly nothing.

**Comment by vexx32** [comment]
Yeah, I don't think `OperationTimeout` is the greatest description of that from a user perspective. If anything, that sounds more like implementation detail than anything that really needs to be user facing.

**Comment by Veverke** [comment]
> > Should I not naturally assume creating a PsSessionOption setting OperationTimeout should affect the New-PsSession created by passing this very PsSessionOption as a parameter ?
> 
> It does affect the PSSession created when it's a WSMan one but the operation timeout isn't what you think it is. It's the timeout for how long the WSMan server can take before it responds back with some data. Where this is actually used is in the `Receive` requests that PowerShell is sending to the server. The request will wait until either there is data to send back to the client or the operation timeout is hit. The standard operation is to just resend the `Receive` request when a timeout is received as that is bound to happen with any long running script. The only time `-OperationTimeout` would actually cause a failure here is if the time it took to create the actual shell/command took longer than that value. The actual running of the command is not affected.
> 
> What this really needs is a doc update to clarify what `-OperationTimeout` affects, mostly nothing.

Thanks a lot for that (by the way [this ](https://www.bloggingforlogging.com/2020/08/21/wacky-wsman-on-linux/)article you wrote was already of much help in the past, on a different issue). In case you have a StackOverflow account, you can leave this as an answer [here](https://stackoverflow.com/q/68176305/1219280).

**Comment by Veverke** [comment]
@jborean93 : what about understanding the script excerpt mentioned above taken from Bruce Payette's Powershell book (see details [here](https://stackoverflow.com/q/68176305/1219280))?

How do I know if I am using WSMan or PsSession ? I mean the script itself is based on a PsSession. Yet, the book example does seem to infer OperationTimeout does affect the duration of the Invoke-Command.

I think this is the last bit missing to completely solve this issue.

**Comment by jborean93** [comment]
> how do we understand the script excerpt mentioned above taken from Bruce Payette's Powershell book (code excerpt (screenshot) here)?

Honestly I don't know why it says what it says. I've tested all the way back to PowerShell v2 and the behaviour that occurs today is the same. Maybe it was tested with some internal build I'm honestly not sure. If you do find out then I'm definitely interested to hear what it was.

> How do I know if I am using WSMan or PsSession ? I mean the script itself is based on a PsSession. Yet, the book example does seem to infer OperationTimeout does affect the duration of the Invoke-Command.

Essentially everything before powershell v5 used WSMan. All the options in `New-PSSessionOption` relate to WSMan settings and AFAIK don't affect any of the other transports added. You know it's WSMan because the session was created with `-ComputerName`. SSH uses `-HostName`, Hyper-V direct uses `-VMName`, etc.

I'm unsure what the usual process is here but I assume the issue should be raised on https://github.com/MicrosoftDocs/PowerShell-Docs as that is where this information lives.
