### ISSUE TITLE
Periodically remote connecting via New-PsSession from docker container to windows machines seems to leak memory

### ISSUE THREAD

**Issue by Veverke** [PowerShell/PowerShell#15699]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

Issues [5244](https://github.com/PowerShell/PowerShell/issues/5244) & [7204 ](https://github.com/PowerShell/PowerShell/issues/7204)seem related.

This was [originally reported at Unix StackExchange on April 12th.](https://unix.stackexchange.com/q/644673/433212)

**Description**: I have a multi containerized app orchestrated via docker-compose, where one of these containers performs powershell remote connections to windows machines, periodically.

In order to reproduce, I prepared the following code snippet that simulates the work the container mentioned above performs: 

```
$password = "myPass"
$domainAndUser = "myDomainAndUser"
$computerName = "myComputerIpAddress"

For ($i = 0; $i -lt 2000; $i++) {
	$pwSession = convertto-securestring -AsPlainText -Force $password
	$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $domainAndUser,$pwSession
	$session = new-pssession -computername $computerName -credential $cred -Authentication Negotiate #-SessionOption $pso 
    
	Invoke-Command -Session $session -ScriptBlock { 1..1 | foreach { "$using:i" + ' completed' ; Start-Sleep 0.5 } } 
    Start-Sleep 1
    Remove-pssession $session.Id
}
```

1. Run the code above in a powershell session (`pwsh`) inside a docker container. 
2. Open a new linux terminal and run `docker stats [container name]`

You should notice that MEM % column increases over time. In this case, by 0.01 in average, in a matter of dozens of seconds.
Over a couple of hours we confirm that memory consumption had increased above 10%.

### Expected behavior

```console
Memory consumption would not increase over time or at least not all the time, forever.
```

### Actual behavior

```console
My remote connection code uses: 
1. New-PsSession to open a session
2. Invoke-Command on that session
3. Remove-PsSession on that session
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 0949761511** [comment]
README.md

**Comment by 0949761511** [comment]
https://www.facebook.com/profile.php?id=100017202002072

**Comment by PaulHigin** [comment]
WG-Remoting:
To get a good idea of memory use, there should be periodic CLR garbage collections.
The script block changes for each loop iteration, and so the memory increase may be due to script block caching.  Each unique script block is cached per PowerShell session.  But the cache size is limited (though large), so the memory increase should eventually end in the this case.

**Comment by Veverke** [comment]
1. Can I control script block caching here? Could not find how in a preliminary search. If possible, should I assume that setting it to a relatively low value would reduce the memory consumption of the app ?
2. Using dotnet-gcdump would help me here in analyzing whether memory allocation constantly increases over GC "rounds" ?

**Comment by iSazonov** [comment]
Really PowerShell uses some caches to increase performance. The caches is internal and you can not manage its. Also PowerShell can compile script block and PowerShell classes, load modules - all this consumes memory over time and can not be unloaded.

**Comment by iSazonov** [comment]
@Veverke PowerShell can not unload compiled resources like assemblies. 
Internally PowerShell has some caches. Most of them are of limited size. So if you run something in cycle you will see increasing memory consumption but not indefinitely. Also GC in .Net Core is too lazy and in some scenarios we can see huge memory consumption but as soon as you stop the script the memory will be freed in a few minutes.

**Comment by PaulHigin** [comment]
With the CLR garbage collector, 'memory consumption' is difficult to determine.  As @iSazonov points out, the CLR uses different heuristics for garbage collection depending on which heap generation an object is placed.
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals

Over the years we have done quite a bit of testing of the remote system to ensure resources (managed and unmanaged) are properly cleaned up.  Of course that doesn't mean a leak hasn't creeped in at some point.  The only current issue I am aware of is with implicit remoting that generates large unique script blocks that get cached and use up a lot of memory on the client.  However, the memory usage is ultimately limited since the cache has an fixed size limit

**Comment by iSazonov** [comment]
> implicit remoting that generates large unique script blocks that get cached and use up a lot of memory on the client

Can you please point the code? Perhaps we could skip the caching if it makes sense.

**Comment by PaulHigin** [comment]
Script block caching is performed at a low level and is not easily skipped from within implicit remoting.  The fix I was thinking of was more along the line of not using unique GUIDs for implicit remoting module names for the same imported modules.
