### ISSUE TITLE
Read-Host is printing the data if the input is given from file | Ubuntu 16 

### ISSUE THREAD

**Issue by aksh7860** [PowerShell/PowerShell#15707]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Steps to reproduce

I am experiencing issues with Read-Host when I am trying to read input from file

Let's see  you create a file read.pwsh having the following contents

$a = Read-Host;

and their is input file input.in having the following content
hello

After executing command on terminal 
pwsh read.pwsh < input.in

then I am getting the following output
hello
The above behaviour seems to be incorrect

### Expected behavior

```console
pwsh read.pwsh < input.in
```
this should not print anything

### Actual behavior

```console
pwsh read.pwsh < input.in
```
the input is getting printed

### Environment data

```powershell
OS Details        :  Ubuntu 16.04.4 LTS
Poweshell Version :  PowerShell 6.2.2
```

**Comment by iSazonov** [comment]
If you redirected input why did not you redirect output?

**Comment by aksh7860** [comment]
@iSazonov 
My use case is I wanted to take input from file and then perform some operations on that print the output of the operations with Write-Host

For Eg: Adding Two Numbers Given In a File and Printing the output of the sum

**Comment by iSazonov** [comment]
Read-Host cmdlet is interactive cmdlet and the behavior is by-design. 

If you have a file you can use Get-Content cmdlet.
