### ISSUE TITLE
Distribution Support Request - Ubuntu 21.04 ARM64

### ISSUE THREAD

**Issue by RobertHenry6bev** [PowerShell/PowerShell#15702]
### Name of the Distribution

ubuntu

### Version of the Distribution

21.04

### Package Types

- [X] Deb
- [ ] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

aarch64 (aka ARM64)

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [ ] The version of the Distribution is supported for at least one year.
- [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by kilasuit** [comment]
@TravisEz13  - is this one in the backlog as there seems to be a number of issues related to users trying to run the snap install on Ubuntu 21.04 as per #15567, #15101, #15029 & #15608

**Comment by sbe-arg** [comment]
@RobertHenry6bev can you update the title to match 21.04?

**Comment by adityapatwardhan** [comment]
The version Ubuntu 21.04 is an interim release. We do not support adding distribution request for interim release as per here: [interim release](https://ubuntu.com/about/release-cycle)

**Comment by adityapatwardhan** [comment]
Snap package and tar.gz packages might work.
