### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by RobertHenry6bev** [PowerShell/PowerShell#15703]
### Name of the Distribution

windows

### Version of the Distribution

Server 2022 Datacenter

### Package Types

- [ ] Deb
- [ ] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

aarch64 (aka ARM64)

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [ ] The version of the Distribution is supported for at least one year.
- [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by RobertHenry6bev** [comment]
is there another issue already open re questing support  for modern linux and windows?  I opened 3 yesterday, and all were closed without explanation

**Comment by vexx32** [comment]
I'm not aware of any issues with supporting current Windows or Ubuntu versions? If there are specific issues when running pwsh on those systems I'd recommend raising them individually. As far as I'm aware, current Windows and Ubuntu versions are generally always in the support matrix.

**Comment by RobertHenry6bev** [comment]
I tried building on ubuntu 21.04 x86_64.  There's a shell script tools/installpsh-debian.sh that enumerates the set of acceptable distributions. Hacking that script to accept 21.04 the build continues on, until it finds that the libssl (I think it was) had an unacceptable version number.  At that point, on the brink of version hell, I gave up.

**Comment by iSazonov** [comment]
> I opened 3 yesterday, and all were closed without explanation

.Net has still limited support for ARM64.

**Comment by TravisEz13** [comment]
Windows ARM64 is already supported (with the .NET limitations)
