### ISSUE TITLE
Get-WinEvent cannot read Winlogon events in Application log using FilterHashtable

### ISSUE THREAD

**Issue by VShrubowich** [PowerShell/PowerShell#15713]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to the [known issues](https://docs.microsoft.com/powershell/scripting/whats-new/known-issues-ps6).

### Description

When using the **FilterHashtable** parameter for **Get-WinEvent** and specifying both, the **Application** event log and the **Microsoft-Windows-Winlogon** event log provider, the errors "_The specified providers do not write events to any of the specified logs_" and "_The parameter is incorrect_" are returned.  However, when specifying the event log without the provider or the provider without the event log, **Microsoft-Windows-Winlogon** events are returned from the **Application** log if any are present.  

The following shows that the **Microsoft-Windows-Winlogon** event log provider does indeed write to the **Application** log:
```
PS> (Get-WinEvent -ListLog Application).ProviderNames | Where-Object {$_ -eq 'Microsoft-Windows-Winlogon'}
Microsoft-Windows-Winlogon
```

The following shows that **Get-WinEvent** does work when the **FilterHashtable** parameter is used to specify the **Application** event log and another provider:
```
PS> Get-WinEvent -FilterHashtable @{ LogName='Application'; ProviderName='Microsoft-Windows-Defrag' }

   ProviderName: Microsoft-Windows-Defrag

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
6/30/2021 7:27:31 AM           258 Information      The storage optimizer successfully completed retrim on OSDisk (C:)
(additional lines of output left out)
```

Running the following code shows that, when using the **FilterXML** parameter to specify the **Application** log and the **Microsoft-Windows-Winlogon** provider instead of using the **FilterHashtable** parameter, the results are as expected:
```
<# Code:

Get-WinEvent -FilterXML @'
<QueryList>
  <Query Id="0" Path="Application">
    <Select Path="Application">*[System[Provider[@Name='Microsoft-Windows-Winlogon']]]</Select>
  </Query>
</QueryList>
'@

#>

# Output:

PS> Get-WinEvent -FilterXML @'
>> <QueryList>
>>   <Query Id="0" Path="Application">
>>     <Select Path="Application">*[System[Provider[@Name='Microsoft-Windows-Winlogon']]]</Select>
>>   </Query>
>> </QueryList>
>> '@

   ProviderName: Microsoft-Windows-Winlogon

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
7/1/2021 8:51:39 PM           1002 Information      The shell stopped unexpectedly and explorer.exe was restarted.
```

The **FilterXPath** parameter also works:
```
PS> Get-WinEvent -LogName 'Application' -FilterXPath '*[System[Provider[@Name="Microsoft-Windows-Winlogon"]]]'

   ProviderName: Microsoft-Windows-Winlogon

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
7/1/2021 8:51:39 PM           1002 Information      The shell stopped unexpectedly and explorer.exe was restarted.
```

### Steps to reproduce

1. Cause the **Microsoft-Windows-Winlogon** provider to write one or more events to the **Application** event log.  One way to accomplish this is to open a **File Explorer** window, then, in **Task Manager** on the **Processes** tab, right-click on **Windows Explorer** and select **Restart**.

2. Run Get-WinEvent like below:

`Get-WinEvent -FilterHashtable @{ LogName='Application'; ProviderName='Microsoft-Windows-Winlogon' }`

### Expected behavior

```console
PS> Get-WinEvent -FilterHashtable @{ LogName='Application'; ProviderName='Microsoft-Windows-Winlogon' }

   ProviderName: Microsoft-Windows-Defrag

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
7/1/2021 8:51:39 PM           1002 Information      The shell stopped unexpectedly and explorer.exe was restarted.
```

### Actual behavior

```console
PS7> Get-WinEvent -FilterHashtable @{ LogName='Application'; ProviderName='Microsoft-Windows-Winlogon' }
Get-WinEvent: The specified providers do not write events to any of the specified logs.
Get-WinEvent: The parameter is incorrect.
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
`Get-WinEvent -ListProvider * | ? {$_.Name -eq "Microsoft-Windows-Winlogon" }`

```
Name     : Microsoft-Windows-Winlogon
LogLinks : {Microsoft-Windows-Winlogon/Diagnostic, Microsoft-Windows-Winlogon/Operational, System}
Opcodes  : {win:Info, win:Start, win:Stop, NotificationPended…}
Tasks    : {AuthenticateUser, UpdatePerUserSystemParameters, CheckWindowsLicenseStatus, RestoringNetConnections…}
```

LogLinks doesn't contains Application log. So it is OS issue. You could report the issue by Windows Feedback tool.

**Comment by BillieJTurner** [comment]
No I don't think so I Have a ISSUE NO OTHER THAN I DON'T KNOW WHAT ALL YOU ARE DOING BUT I DON'T THINK I EVER GAVE YOU PERMISSION TO ANYTHING FROM MY PHONE'S TO ANYTHING WITH MY ACCOUNT
.... ISSUE WILL BE HERE....game one,BYe COMMAND POWER BJT.... BB.

**Comment by 237dmitry** [comment]
LogName and ProviderName can't use together. There are different parameter sets.
```
 PS > (gcm Get-WinEvent).ParameterSets.Where({ $_.Parameters.Name -eq 'LogName' }).Foreach({ $_.Parameters.Name })
LogName
MaxEvents
ComputerName
Credential
FilterXPath
Force
Oldest
Verbose
Debug
ErrorAction
WarningAction
InformationAction
ErrorVariable
WarningVariable
InformationVariable
OutVariable
OutBuffer
PipelineVariable
```

**Comment by uw-dc** [comment]
@237dmitry 

This not a valid example then?
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-7.3#example-18--use-filterhashtable-to-get-application-errors
