### ISSUE TITLE
Investigate impact of Roslyn analyzers on build times

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15718]
@iSazonov

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#reportanalyzer
https://www.meziantou.net/understanding-the-impact-of-roslyn-analyzers-on-the-build-time.htm

**Comment by iSazonov** [comment]
We can hardly do more than #15640

**Comment by xtqqczze** [comment]
@iSazonov I am not seeing a material impact in local build times (build of revision 03b07a006):

`> Measure-Command { Start-PSBuild -Clean }`
TotalSeconds: 140.4434262

`> Measure-Command { Start-PSBuild -SkipRoslynAnalyzers -Clean }`
TotalSeconds: 132.8133084

Could you please run these commands on your machine?

**Comment by iSazonov** [comment]
190 vs 110 seconds for cold builds.

The number of analyzers will only increase over time.
