### ISSUE TITLE
> hmm, is finding xcworkspace random?

### ISSUE THREAD

**Issue by Devkey19** [PowerShell/PowerShell#15716]
> hmm, is finding xcworkspace random?

Seems related to #3076. I wonder if that change introduced a race condition where now, whichever project loads faster is selected for building.

_Originally posted by @elliottwilliams in https://github.com/Carthage/Carthage/issues/3211#issuecomment-870197573_

**Comment by iSazonov** [comment]
You reference wrong repository.
