### ISSUE TITLE
Change telemetry from opt-out to opt-in

### ISSUE THREAD

**Issue by redgryphon** [PowerShell/PowerShell#15722]
### Summary of the new feature / enhancement

As with time users are getting more and more focused in their right to privacy and their data every kind of data policy should never be opt-out but rather opt-in.

### Proposed technical implementation details (optional)

The environment variable would become something like `POWERSHELL_CLI_TELEMETRY_OPTIN` instead of `POWERSHELL_CLI_TELEMETRY_OPTOUT` and the code behind the telemetry itself would just need to change all the boolean references to the variable.

**Comment by SydneyhSmith** [comment]
Thanks for opening up this issue @redgryphon! 
Opt in vs Opt out is something that we discussed with the PowerShell community as we made the decision to add some basic telemetry. 
We chose to include only non-identifying telemetry as to be very sensitive to the privacy of PowerShell users, at the same time we felt that by making telemetry opt-in it would bias and limit our telemetry in a way that would make less useful to our users. Our hope is that the targeted telemetry that we collect can help us make better decisions around the development of PowerShell and be a value add to our users. With that being said we hoped to make the opt-out process accessible to users.

**Comment by redgryphon** [comment]
While I get that having a opt-in policy would limit the amount of data that you can collect I still believe that most of the people, when asked during install time they would press the yes button on a binary choice, exactly as most people press the accept button on the cookie request on every website.

Obviously the problem gets to be "where to place the binary choice". In the website when people download the binaries? In the installers? I don't know and I'd like to see other people to give ideas.

At the end I just want to stress two things. The first is that privacy friendly defaults should always be the norm, especially when we talk about open source projects. The second is that I strongly respect the hard work you're doing and that I want thank you for that.
