### ISSUE TITLE
CodeFactor "complex method" false positives

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15721]
cc: @iSazonov 

I'm seeing many CodeFactor "complex method" false positives issues in CI, perhaps we should disable this issue category.

**Comment by iSazonov** [comment]
I wouldn't want to hide the fact that there really are a lot of methods that should have been simplified.
Such methods are difficult to read and understand, and what is especially unpleasant is that they are a source of bugs.
 CodeFactor is an auxiliary tool for us, so I wouldn't worry about false-positives.

**Comment by xtqqczze** [comment]
The false positives make it hard to tell if a failed check is "real" from Github PR summary:

![image](https://user-images.githubusercontent.com/45661989/124503010-8c28b400-ddbc-11eb-9583-8018762b3b53.png)

Also Github desktop:

![image](https://user-images.githubusercontent.com/45661989/124503247-0ce7b000-ddbd-11eb-9ccb-1d6c92a9d2b9.png)

Also it leads to a bad experience for new contributors.

**Comment by xtqqczze** [comment]
The failed check also appears as a favicon:

![image](https://user-images.githubusercontent.com/45661989/124503465-87183480-ddbd-11eb-8a9c-da0ae0c9a24c.png)

**Comment by xtqqczze** [comment]
@iSazonov Could you please reopen?
