### ISSUE TITLE
Update supported platforms in README

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15723]
The list of supported platforms in [README.md](https://github.com/PowerShell/PowerShell/blob/4c2d6dcfca29894c91bbac2008a374d6cc4c5a3a/README.md) may be outdated.

_Issue initially communicated in: 13dca6e9fe5c2618ae34a5e75d69356b77284642._

**Comment by iSazonov** [comment]
We always update the list near next release.

**Comment by xtqqczze** [comment]
For example, it is claimed that Fedora 30 is supported, but PowerShell LTS (7.0) uses .NET 3.1, which [no longer supports this distribution](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md).

**Comment by iSazonov** [comment]
You can look https://devblogs.microsoft.com/powershell/announcing-powershell-7-1/ where Fedora 30 was mentioned as supported OS for PowerShell 7.1.

PowerShell release process and support lifecycles are under full control by MSFT team.

**Comment by xtqqczze** [comment]
> You can look https://devblogs.microsoft.com/powershell/announcing-powershell-7-1/ where Fedora 30 was mentioned as supported OS for PowerShell 7.1.
> 
> PowerShell release process and support lifecycles are under full control by MSFT team.

That blog post appears to be based on https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md which states:

> "When a platform version reaches end-of-life as defined by the platform owner, PowerShell Core will also cease to support that platform version."

Clearly there are platforms on that list that are end-of-life and should therefore be removed.

**Comment by xtqqczze** [comment]
I've opened dotnet/core#6431 to clarify .NET support for Fedora 32.

**Comment by xtqqczze** [comment]
@iSazonov Please could you reopen?

**Comment by iSazonov** [comment]
Official support for official MSFT distributives is a completely MSFT team internal process. They will update the documents during the next release.
