### ISSUE TITLE
Can't use New-PSSession to "https://ps.compliance.protection.outlook.com/powershell-liveid/"

### ISSUE THREAD

**Issue by jmcadams-r7** [PowerShell/PowerShell#15735]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$Username = <username>
$Password = <password>
$SecPassword = ConvertTo-SecureString $Password -AsPlainText -Force
$Office365URI = "https://ps.compliance.protection.outlook.com/powershell-liveid/"
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $Office365URI -Credential $Credentials -Authentication Basic -AllowRedirection

### Expected behavior

```console
$Session is a valid session in exchange online
```

### Actual behavior

```console
New-PSSession: /powershell/Connection.ps1:19
Line |
  19 |  $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne …
     |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [ps.compliance.protection.outlook.com] Connecting to remote
     | server ps.compliance.protection.outlook.com failed with the
     | following error message : MI_RESULT_FAILED For more
     | information, see the about_Remote_Troubleshooting Help topic.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

NA

**Comment by jmcadams-r7** [comment]
Some additional information. This worked up until Monday (July 5th 2021). We had this script suddenly fail across several organizations and we're not sure what changed.

**Comment by PaulHigin** [comment]
WG-Remoting:

**Comment by jmcadams-r7** [comment]
This ended up being a problem with docker. I couldn't tell you the root cause. I had to uninstall and reinstall docker to get it to work. A simple reset of docker wasn't enough.
