### ISSUE TITLE
PowerShell Gallery availability is degraded

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#15730]
PowerShell Gallery availability is degraded and may affect CI.

> July 6th, 2021 20:58 UTC The PowerShell Gallery is experiencing latency due to lower availibility with CDN.

https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md#powershell-gallery-status

**Comment by daxian-dbw** [comment]
@xtqqczze PowerShell Gallery issue should not be tracked in this repo given that the action items should be on the gallery repo side.

**Comment by xtqqczze** [comment]
@daxian-dbw since this issue is affecting CI, I think it is helpful to track here.

**Comment by iSazonov** [comment]
Thanks for the information but it is too noisy to have issues for external services if we shouldn't to fix something or add a workaround or temporary pending some tests.
