### ISSUE TITLE
Test-Json doesn't take in count the dependencies in the json schema.

### ISSUE THREAD

**Issue by RobertoRojas** [PowerShell/PowerShell#15748]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am working in a script to validate if a version defined in a JSON file is valid (major or equal). And to do this I choose the follow items to define the version:

- Major
- Minor
- Patch

But the thing is that the patch property can only be define when the minor property exists. To do that I use the "dependencies" definition in the JSON schema.

# Schema:
```JSON
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "required": [
    	"major"
    ],
    "properies": {
    	"major": {
        	"type": "integer"
        },
    	"minor": {
        	"type": "integer"
        },
    	"patch": {
        	"type": "integer"
        }
    },
	"dependencies": {
		"patch": ["minor"]
	}
}
```

```JSON
{
    "major": 1,
    "patch": 1
}
```

In this case, the result of Test-Json must be False, but this function is not taking in count this property and return true, because "major" exists. I tested this example in this web page and it shows the expected result:

https://www.jsonschemavalidator.net/

Dependencies in json-schema.org:

https://json-schema.org/understanding-json-schema/reference/conditionals.html#dependencies

### Expected behavior

```console
PS> Test-Json -Json $(Get-Content -Path .\test.json | Out-String) -SchemaFile .\test.schema.json;
False
```

### Actual behavior

```console
Test-Json -Json $(Get-Content -Path .\test.json | Out-String) -SchemaFile .\test.schema.json;
True
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
PowerShell uses https://github.com/RicoSuter/NJsonSchema so please report the issue there.
