### ISSUE TITLE
Can't use FOR from cmd.exe

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#15747]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying to run [this FOR script](https://superuser.com/questions/823959/how-to-view-all-the-symbolic-links-junction-points-hard-links-in-a-folder-using/1138469#1138469) which works in `cmd.exe`:
````
FOR /F "Tokens=*" %A IN ('DIR /al /b /s G:\') DO @( for /F "Tokens=2,4 delims=<[]>" %B IN ('DIR /al "%~A"? ^| FIND /I " %~nA " ^| FIND /I "<" ^| FIND /I ">" ') DO @( ECHO.%~B: "%~A" → "%~C" ) )
````

### Expected behavior

```console
Print all links
```

### Actual behavior

```console
Error:
`
ParserError:
Line |
   1 |  FOR /F "Tokens=*" %A IN ('DIR /al /b /s G:\') DO @( for /F "Tokens=2, …
     |     ~
     | Missing opening '(' after keyword 'for'.
````
```


### Error details

_No response_

### Environment data

```powershell
`
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````
```


### Visuals

_No response_

**Comment by vexx32** [comment]
`for` is not a native application, it's an internal command used by Command Prompt, so yes, you cannot use it without using Command Prompt.

PowerShell does not follow the language nor internal functions of Command Prompt, it has its own syntax and grammar that needs to be followed, just like any other programming language.

Try `Get-Help about_for` for instructions on using PowerShell's `for` statement.

**Comment by superbonaci** [comment]
So could you reformulate that command for powershell?

**Comment by rkeithhill** [comment]
If you're looking for reparse points, try:
```poweshell
Get-ChildItem G:\ | Where-Object Attributes -match ReparsePoint
```

**Comment by superbonaci** [comment]
> 
> 
> If you're looking for reparse points, try:
> 
> ```
> Get-ChildItem G:\ | Where-Object Attributes -match ReparsePoint
> ```
> 
> If you need to search recursively, add the `-Recurse` parameter to `Get-ChildItem`.

It works, but it adds too much metadata when searching recursively. How to get this result:
````
G:\folder -> D:\share\doc\html\use
G:\xx -> C:\doc\yy
````

**Comment by rkeithhill** [comment]
```powershell
Get-ChildItem G:\ | Where-Object Attributes -match ReparsePoint | Format-Table FullName,Target
```

**Comment by superbonaci** [comment]
> Get-ChildItem G:\ | Where-Object Attributes -match ReparsePoint | Format-Table FullName,Target

That's more like it, however it does not display the full path, just abbreviations:
````
PS C:\> Get-ChildItem -Recurse C:\ | Where-Object Attributes -match ReparsePoint | Format-Table FullName,Target

FullName                                 Target
--------                                 ------
C:\Program Files\Common Files\Oracle\Ja… C:\Pr…
````

**Comment by iSazonov** [comment]
Get-ChildItem -Recurse C:\ | Where-Object Attributes -match ReparsePoint | Format-Table FullName,Target -AutoSize
or
Get-ChildItem -Recurse C:\ | Where-Object Attributes -match ReparsePoint | Format-List FullName,Target

**Comment by superbonaci** [comment]
@iSazonov perfect just what needed.
