### ISSUE TITLE
Leak CancellationTokenSource in ConvertTo-Json

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#15740]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

https://github.com/PowerShell/PowerShell/blob/6d08db612e6d1788d0a0ae518583dae9faa6917b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs#L32

We should dispose _cancellationSource.

**Comment by xtqqczze** [comment]
Also in `Microsoft.PowerShell.Commands.WebRequestPSCmdlet`:

https://github.com/PowerShell/PowerShell/blob/9fb3c2e97c739710900e1272a491bb5160c6b86b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L923

**Comment by xtqqczze** [comment]
FYI: https://github.com/aspnet/AspNetKatana/pull/109
