### ISSUE TITLE
Support hosted apps for Windows

### ISSUE THREAD

**Issue by ayamadori** [PowerShell/PowerShell#15758]
### Summary of the new feature / enhancement

Are there any plan for this?
https://blogs.windows.com/windowsdeveloper/2020/03/19/hosted-app-model/
> An example would be a script file which requires its host (eg: `Powershell` or Python) to be installed.

The benefit for user is the deep integration with .ps1 script and Windows showed in above blog post.
Especially, I want to integrate with context menu.
> hosted apps to look and behave like a separate app on the system – where it has its own start tile, identity, and deep integration with Windows features such as BackgroundTasks, Notifications, and Share

### Proposed technical implementation details (optional)

https://docs.microsoft.com/en-us/windows/uwp/launch-resume/hosted-apps

> For example, a `PowerShell` or Python script could be delivered as a hosted app that requires a host to be installed in order to run.

**Comment by iSazonov** [comment]
Please add more information how users could benefit from the feature.

**Comment by ayamadori** [comment]
I added a little

**Comment by iSazonov** [comment]
It is not clear what you ask. You can already register pwsh as host and create a hostapp.
