### ISSUE TITLE
Rename-Item optimization bug: renaming to a case variant is situationally quietly ignored in case-insensitive file-systems

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15755]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: Renaming a _directory_ to a case variation of its current name is currently broken altogether - see #14903 - but the same behavior should apply to both directories and files.

On case-_insensitive_ file-systems (by default: Window, macOS), renaming a file to a _case variation_ of its current name works _in principle_, but there seems to be an optimization that situationally _prevents_ renaming:

* If the `-Path` / `-LiteralPath` argument is case-identical to the `-NewName` argument, the call is a quiet _no-op_.

* However, the `-Path` / `-LiteralPath` argument  may refer to a file-system item whose _actual_ case differs from the `-NewName` argument and therefore still requires renaming.

```powershell
# Create a temporary dir. to experiment in.
Push-Location -ErrorAction Stop ($tmpDir = New-Item -Force -Type Directory (Join-Path temp: $PID))

try {

  # Create a sample dir with an initial *uppercase* letter.
  $null = New-Item -Type Directory -Force Foo

  # Try to rename it to all-lowercase, incidentally using the all-lowercase form
  # to match the current name too.
  Rename-Item foo foo

  (Get-Item foo).Name | Should -BeExactly foo

} finally {
  Pop-Location
  Remove-Item $tmpDir -Recurse
}
```

### Expected behavior

```console
The test should succeed.
```

### Actual behavior

```console
The test fails, because no renaming was performed:


String lengths are both 3. Strings differ at index 0. Expected: 'foo' But was:  'Foo'
```

### Environment data

```powershell
PowerShell Core 7.2.0-preview.7
```

**Comment by iSazonov** [comment]
> Note: Renaming a _directory_ to a case variation of its current name is currently broken altogether - see #7829 - but the same behavior should apply to both directories and files.

It seems to be an wrong link.

**Comment by mklement0** [comment]
Thanks, @iSazonov - the link should have been the following (also fixed in the OP now):

* #14903

**Comment by mklement0** [comment]
Closed in favor of:
* #12483
