### ISSUE TITLE
PowerShell 7 is unable to create a junction on relative paths while PS 5 can

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#15750]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Try to create a junction with powershell 7:
````
PS E:\> mkdir 'Program Files (x86)\Steam'
PS E:\> New-Item -ItemType Junction -Path 'C:\Program Files (x86)\Steam' -Target 'Program Files (x86)\Steam\'
````

### Expected behavior

```console
Create the symlink in PS7 like in PS 5.
```

### Actual behavior

```console
Gives error:
```
````
New-Item: Could not find item Program Files (x86)\Steam\.
````

### Environment data

This version does not create the symlink:
````
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

This version DOES work:
````
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
````
```


### Visuals

_No response_

**Comment by 237dmitry** [comment]
I think you confused the `Path` with the `Target`

**Comment by superbonaci** [comment]
@237dmitry no I didn't, because the folder `C:\Program Files (x86)\Steam` was moved to another drive.
Also, using `Value` instead of `Target` doesn't work:
````
PS E:\> mkdir 'Program Files (x86)\Steam'
PS E:\> New-Item -ItemType Junction -Path 'C:\Program Files (x86)\Steam' -Value 'Program Files (x86)\Steam\'
````
Which is recommended here: https://github.com/PowerShell/PowerShell/issues/6232

**Comment by superbonaci** [comment]
Finally found the problem. PowerShell 7 can't work with relative paths when creating junctions on directories. However PS5 can. So to fix it, you must provide always a full path. So with a full path works with PS 5 and PS 7, and you can use `Target` or `Value` both work.

Either way it works now. Remember to run powershell as admin which can be required:
````
New-Item -ItemType Junction -Path 'C:\Program Files (x86)\Steam' -Value  (Get-Item 'Program Files (x86)\Steam\').FullName
New-Item -ItemType Junction -Path 'C:\Program Files (x86)\Steam' -Target (Get-Item 'Program Files (x86)\Steam\').FullName
````

**Comment by rkeithhill** [comment]
I think you are running into an issue where relative symlink paths are relative to the process's (not the PS file system provider's) current working dir.  See https://github.com/PowerShell/PowerShell/issues/15235#issuecomment-859286180

**Comment by superbonaci** [comment]
Yeah but something changed too much if works with PS5 and not with PS7. This is kind of incompatibility thing which shouldn't happen I guess...

**Comment by rkeithhill** [comment]
> This is kind of incompatibility thing which shouldn't happen
 
Agreed but unfortunately regressions happen, and often when someone has the good intention of fixing some bug or implementing an enhancement request.

**Comment by superbonaci** [comment]
Yeah the idea if that's a regression or done on purpose.
