### ISSUE TITLE
Unquoted numbers with two or more dots should cast to a `[version]` rather than`$Null`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#15756]
Related: [How can Powershell compares between string and double?](https://stackoverflow.com/q/68335669/1701026)

### Summary of the new feature / enhancement

Currently an unquoted number with two or more dots casts to a `$Null` instead of leaving an expected `... is not recognized as a name of a cmdlet` error.

```PowerShell
$Version = 2.0.9
$Null -eq $Version
True
```

I would like to suggest to cast numbers with 3 or 4 dots (as `2.0.9` and `2.0.7.0`) automatically to a version as a semantic PowerShell sugar.

**Comment by 237dmitry** [comment]
Yes, `ipaddress` and `datetime` too. What makes these types worse?  If syntax then all of sugar.
```
[datetime] '10.7.21'
[ipaddress] '10.7.21'
[version] '10.7.21'
```

**Comment by iRon7** [comment]
> Yes, `ipaddress` and `datetime` too. What makes these types worse? If syntax then all of sugar.

Good point, there no specific type here.
At the other hand, it shouldn't cast to `$null`, without warning/error too...

**Comment by SeeminglyScience** [comment]
> At the other hand, it shouldn't cast to `$null`, without warning/error too...

Note that it's not actually casting to anything here, it's attempting to access a property.

```powershell
> Update-TypeData -TypeName System.Double -MemberType NoteProperty -MemberName 0 -Value 'example'
> 2.0.0
example
```

**Comment by iRon7** [comment]
I have given it some deeper thoughts:

> Yes, `ipaddress` and `datetime` too. What makes these types worse? 

I think that the **generality** and the **specificity**  of a type defines how it would/should be normally perceived.
Like `2` is perceived an `[int]` and not as a `[double]` and `2.0` is perceived as a `[Double]` and not as something as a `[Version]`.

### `[ipaddress]`
*IP Addresses* are less general then *versions numbers* as you might have *IP Address Versions* but  not something like a *Version Addresses* (at least, I can't think of any). Besides, it concerns  an ***IP** Address* here, which even makes it less general than an (general) *address*.

### `[datetime]`
The fact that `[datetime] '10.7.21'` has a lot of different formats (along with `[datetime] '10/7/21'` and `[datetime] '10-7-21'`) makes it less specific. Meaning that if I would read something like: `$x -gt 10.7.63`, I would automatically presume a *version* not a *date* (even it is my birthday 😃).

At the moment, I can't think of any other (general) type with a string constructor that accepts numbers separated by multiple dots.

**Comment by iSazonov** [comment]
I'd rather thought it is typo in double then intention to type a version or another type.

**Comment by iRon7** [comment]
> I'd rather thought it is typo in double then intention to type a version or another type.

Point taken, but that would mean that it should return an error.

**Comment by vexx32** [comment]
I don't think it's reasonable for PS to assume the user's intent here. If we wanted numerals like this to parse as a specific type, we'd need to use a specific format, probably somewhat similar to how we have the existing number formats with a suffix like `84u`, using either a prefix or suffix.

**Comment by SeeminglyScience** [comment]
> I wouldn't expect PS to figure out the users intent but I would at least expect an error if PS can't make head or tails about it. I would at least expect the same behavior as

You can use `Set-StrictMode` to configure that, but by default PowerShell does not throw when accessing a property that doesn't exist by design.
