### ISSUE TITLE
New-PSDrive -Persist should not also require -Scope Global

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#15752]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

Related: #7829

### Steps to reproduce

Note:

  * While the current behavior is [_documented_]((https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7.2), the better alternative to documenting counterintuitive behavior is to _fix_ it, as suggested below.

---

To establish a _persistent_ network drive mapping on Windows (independently of PowerShell, for the current user, as `net use /persistent:yes` does), `New-PSDrive` must be invoked with the `-Persistent` switch.

Unexpectedly, however, when calling from a script (a scope other than the global one), `-Scope Global` is _also_ required - even though the concept of PowerShell scopes is inapplicable to such drive mappings.

Therefore, 

* The behavior should be changed to make `-Persistent` effective even without `-Scope Global` (but continue to allow the latter for backward compatibility).

* Ideally, trying to combine `-Persist` with  `-Scope Local` or `-Scope Script` should result in a statement-terminating error, as such a combination makes no sense; the alternative is to quietly _ignore_ the `-Scope` argument in this case.

```powershell
# Use a UNC share that works on your system
& { New-PSDrive -Persist T FileSystem "\\$env:COMPUTERNAME\C`$" }
```

### Expected behavior

A persistent network drive mapping `T:` should be established for the current user, as confirmed by running `net user T:`

### Actual behavior

No _persistent_ drive mapping is established (that is, a PS-only drive is created, which goes out of scope when the script block exits.

In effect, `-Persist` is _quietly ignored_ in any scope other than the _global_ one (except if `-Scope Global` is added, which is logically extraneous and should therefore not be required).

### Environment data

```powershell
PowerShell Core 7.2.0-preview.7 on Windows
```

**Comment by iSazonov** [comment]
I can create new persist drive without Scope parameter but I can not it with Remove-PSDrive.

**Comment by mklement0** [comment]
Thanks, @iSazonov, but the problem only occurs when running _outside the global scope_ - please see the updated OP (I have since been able to confirm that the problem still exists).

The separate bug that prevents _removal_ of successfully established persistent drive mappings is also mentioned in the OP, but, to be safe, here is the link again: #7829

**Comment by jdhitsolutions** [comment]
The Cmdlets and Modules Working group has investigated and discussed this issue. It is our consensus to not make any changes to New-PSDrive. The cmdlet has parameters that a script author can use to explicitly achieve the desired scoped result. PowerShell expressions should always be clear and concise. The best solution for this issue is improved documentation.

**Comment by mklement0** [comment]
Here's my suggestion for improving the documentation:

"
This cmdlet has a glaring design flaw that we have decided not to fix (even though we could without breaking anything):

When you attempt to establish a _persistent_ drive mapping from a script with `-Persist`, your request will be quietly ignored - unless you inexplicably also specify an additional, conceptually unrelated argument - `-Scope Global` (persistent drive mappings are a system-wide concept unrelated to PowerShell scopes; any persistent drive mapping is invariably visible in all PowerShell scopes).

An added pitfall is that, because a _transient, scope-local PowerShell-only_ drive _is_ created in this case, you may not notice the problem until you try to use the drive in (non-descendant) other scopes, child processes, or future sessions.
"

**Comment by iSazonov** [comment]
From the WS conclusion it is not clear why don't implement "Ideally, trying to combine -Persist with -Scope Local or -Scope Script should result in a statement-terminating error,".

**Comment by mklement0** [comment]
Agreed, @iSazonov, but the most important fix is to consistently make `-Persist` work  _without_ a `-Scope` argument;  combining the latter - whatever its value - never made any sense with `-Persist`.
