### ISSUE TITLE
Expose PWSH_VERSION environment variable

### ISSUE THREAD

**Issue by beatcracker** [PowerShell/PowerShell#15753]
### Summary of the new feature / enhancement

Shells such Bash, Zsh, Fish, Ksh expose their version as an environment variable, usually in the form of `{ShellName}_VERSION`. This makes it easy for a child processes and scripts to implement shell-specific code paths, e.g.:

- modifying shell profile file for current shell: `.bashrc`, `.zshrc`, etc...
- outputting eval code for specific shell: `eval "$(docker-machine env default)"`

Docs:
- https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bash-Variables (`BASH_VERSION`)
- https://zsh.sourceforge.io/Doc/Release/Parameters.html#index-ZSH_005fVERSION (`ZSH_VERSION`)
- https://fishshell.com/docs/current/language.html#special-variables (`FISH_VERSION`)
- https://linux.die.net/man/1/ksh (`KSH_VERSION`)

### Proposed technical implementation details (optional)

PowerShell should expose an environment variable with it's version, e.g.: `PWSH_VERSION`
This is very easy to implement, has infinitesimally low chance of breaking something and would perfectly align with what other shells do.

**Comment by mklement0** [comment]
Note that none of these variables are _environment_ variables (they are _shell_ variables), so child processes do _not_ see them - unless they happen to be _subshells_ (i.e. clones of the original shell process).

**Comment by beatcracker** [comment]
@mklement0 Thanks, I really should've checked the docs more thoroughly and not rely on my preconceptions. In this case `PSVersionTable` fits the bill for PowerShell interoperability and this feature request doesn't make much sense.

**Comment by beatcracker** [comment]
Thanks everyone, sorry again for brining this up without proper research. Closed.
