### ISSUE TITLE
Set-Service with Gmsa

### ISSUE THREAD

**Issue by dbznico** [PowerShell/PowerShell#15766]
### Summary of the new feature / enhancement

Hi,

I try to use the set-service command to implement a group managed service account as a logon service.

But it seems to be impossible to use the -credential with a blank password

Here is a way to do that with powershell please ?

It would be great if this cmdlet can be compatible with Gmsa

Many thanks

Best regards

**Comment by iSazonov** [comment]
It seems underlying API doesn't support this. See workaround https://www.stefanroth.net/2018/04/12/powershell-change-windows-service-login-to-group-managed-service-account/

**Comment by iSazonov** [comment]
PowerShell calls ChangeServiceConfigW and [docs](
https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-changeserviceconfigw) say:
```
If the account name specified by the lpServiceStartName parameter is the name of a managed service account or virtual account name, the lpPassword parameter must be NULL.

Passwords are ignored for driver services.
```
So the request could be implemented.

**Comment by dbznico** [comment]
When i type no password to set NULL, i have an error that the password is incorrect
In theory the password is not null, but only the computer that is allow to retrieve can read it

**Comment by iSazonov** [comment]
> When i type no password to set NULL

Get-Credentail set the password to empty, not null, so we need a simple fix as proposed above.

**Comment by dbznico** [comment]
ok i understand. Thanks but i don't arrive to use your fix
where i need to put you code please ?
My command is set-service -name test -credential test
then it ask me a password

**Comment by jborean93** [comment]
The code works today, the trick is creating as `PSCredential` with an empty password as required by a gMSA. To do so just create a new `SecureString` object like so and then use that credential with `Service-Service`.

```powershell
$cred = [PSCredential]::new('DOMAIN\mygMSA$', [Security.SecureString]::new())
Set-Service -Name ServiceName -Credential $cred
```

I can confirm this works perfectly fine on my host with a gMSA installed.

**Comment by dbznico** [comment]
Many Thanks, it works like a charm

Thnk you very much for your help and quick response, I appreciate :)
