### ISSUE TITLE
Use forward slashes in autocomplete on Windows

### ISSUE THREAD

**Issue by aminya** [PowerShell/PowerShell#15764]
### Summary of the new feature / enhancement

I have been trying to avoid using `\` for path separation, but PowerShell still uses `\` in its autocomplete when I press TAB. Could you make this configurable so it uses `/` instead?

![pwsh-path-autocomplete](https://user-images.githubusercontent.com/16418197/125441883-9972941f-7b91-4c9d-b511-dc76e5b25ecc.gif)

**Comment by theJasonHelmick** [comment]
This is by design. The directory separator on Windows and linux are different. Making this configurable would require us to also make changes to the native command processor because many win32 executables require backslashes.

**Comment by aminya** [comment]
As far as I remember, I don't use any application that requires backslashes. Everything I work with expects forward slashes (they might accept backslashes for backward compatibility).

Given the problems that Powershell already has for calling native applications (#1995 and #13068), I don't think this conflicts with this issue.

**Comment by parkovski** [comment]
Both `wsl` and `cmake` require forward slashes so autocomplete doesn't work with them. Yes, some other tools require backslashes. Windows is a "both" system, **not** a backslash only system, and it'd be nice to have this acknowledged.

**Comment by aminya** [comment]
The strange behaviour is that it doesn't keep what I have already written! So I have to avoid autocomplete altogether.

**Comment by parkovski** [comment]
@aminya Good point, it'd be nice at least if I started typing `./` or `SomeFolder/` if it would complete forward slashes.
