### ISSUE TITLE
Get-Random -Maximum doesn't include the max number

### ISSUE THREAD

**Issue by HCSS-JamesKerens** [PowerShell/PowerShell#15774]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running Get-Random with -Maximum number never returns the maximum number but in the code is says "Maximum number  to generate" [code ref](https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L209)

I tried running the newest PowerShell but it keeps crashing. I think my PSReadLine settings are conflicting with it.

### Expected behavior

```console
PS> (1..10000 | foreach { Get-Random -Maximum 11 } | where { $_ -eq 11 }).Count -gt 0
True
```

### Actual behavior

```console
PS> (1..10000 | foreach { Get-Random -Maximum 11 } | where { $_ -eq 11 }).Count -gt 0
False
```

### Error details

```console
No errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
As per [the docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-random?view=powershell-7.1):

> `Get-Random` returns a value that is less than the maximum (not equal)

**Comment by HCSS-JamesKerens** [comment]
Sorry I'm an idiot. Can we chalk it up to having one of those days? 😅
