### ISSUE TITLE
Break command inside ForEach causes a return in function

### ISSUE THREAD

**Issue by tikicoder** [PowerShell/PowerShell#15777]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Here is a sample code below. Basically I am trying to take an array and then break in the foreach. When I do this in a function it causes the script to end.

$rulesets_keys = @("rule1", "rule2", "rule3")
function test2($rulesets_keys){
  write-host "test call"
  test -rulesets_keys $rulesets_keys
  write-host "end test"
}
function test($rulesets_keys){

  try {
    $rulesets_keys | foreach { $_; break}
  }
  catch {}
  write-host "after"

}

test -rulesets_keys $rulesets_keys
test2 -rulesets_keys $rulesets_keys

---------------
output 
PS C:\Users\utruero> test -rulesets_keys $rulesets_keys
rule1
PS C:\Users\utruero> test2 -rulesets_keys $rulesets_keys
test call
rule1

### Expected behavior

```console
I would expect that the break would just break the foreach function
```

### Actual behavior

```console
it causes the whole script to break at that point
```

### Error details

```console
none
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/787308/125691049-88bbd571-0da2-470e-8941-e7ba51ef9c18.png)

**Comment by jborean93** [comment]
See https://github.com/PowerShell/PowerShell/issues/15762. Using `foreach` like this is just an alias for `ForEach-Object` which isn't an actual loop in PowerShell. When you use `break/continue` it will continue to unwind the stack until it finds the language level loop which in this case is the whole stack causing it to act like return.

While using `return` in a `ForEach-Object` block is similar to `continue` there's no real equivalent to `break` here. The closest is to have a check at the start and just return when it's true like so:

```powershell
$break = $false
1..5 | ForEach-Object -Process {
    if ($break) { return }

    if ($_ -eq 3) {
        $break = $true
        return
    }

    $_
}
```
