### ISSUE TITLE
Format-Table generates unnecesary empty line at beggining of file

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#15779]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This command generates an empty line at the beginning of output file:
````
Get-ChildItem C:\samples\ -recurse -force | Format-Table FullName -HideTableHeaders  | Out-File result.txt
````

### Expected behavior

```
C:\samples\file-1.csv
C:\samples\file-2.csv
```

### Actual behavior (note a new empty line at the beginning + a new one at the end)

```

C:\samples\file-1.csv
C:\samples\file-2.csv

```

### Error details

No errors.

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This is currently a result of design of Format-Table and how it works within the current formatting system.  The empty line is there for grouping (each new group starts with a newline).  With the current formatting system, to remove that newline is not trivial.

**Comment by superbonaci** [comment]
I think that does it.
