### ISSUE TITLE
Cannot change directory into wsl distro 

### ISSUE THREAD

**Issue by clayms** [PowerShell/PowerShell#15773]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This issue was supposedly fixed https://github.com/PowerShell/PowerShell/pull/10674

However, I am still seeing the exact same issue described in https://github.com/PowerShell/PowerShell/issues/10360 and https://github.com/PowerShell/PowerShell/issues/15497.

### Expected behavior

```console
PS C:\Users> cd //wsl$/fedoraremix/
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\fedoraremix>
```

### Actual behavior

```console
PS C:\Users> cd //wsl$/fedoraremix/
Set-Location: Cannot find path '//wsl$/fedoraremix/' because it does not exist.
```

### Error details

```console

Set-Location: Cannot find path '//wsl$/fedoraremix/' because it does not exist.
```

### Environment data

```console
PS> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.7
PSEdition                      Core
GitCommitId                    7.2.0-preview.7
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

and 

```console
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
Do you see the issue without final  '/'?

**Comment by clayms** [comment]
@iSazonov 
Yes.  All of the following return the same error

+ `cd //wsl$/fedoraremix/`
+ `cd //wsl$/fedoraremix/`
+ `cd //wsl$/fedoraremix/`
+ `cd //wsl$/fedoraremix/`

**Comment by vexx32** [comment]
I thought you needed to target `\\wsl$\distro` rather than `//wsl$/distro`?

**Comment by rkeithhill** [comment]
Both backward and forward slashes work for me:
```
dir //wsl$/Ubuntu

        Directory: \\wsl$\Ubuntu


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----        11/21/2019   6:51 PM                bin
d----         9/22/2017  10:15 AM                boot
d----          7/9/2021  12:16 PM                dev
d----          7/9/2021   5:12 PM                etc
...
```

**Comment by iSazonov** [comment]
@rkeithhill Please share your Windows version.

@clayms Is WSL running in your test?

**Comment by rkeithhill** [comment]
I'm using 21H1 (10.0.19043).

**Comment by clayms** [comment]
@iSazonov
  Yes, in another shell, because I thought it had to be **actively** running.  So I started it in another shell on the same computer and left it running ***before*** I started another shell and tried to `cd` into the wsl directories.  However, I just found out that I have to run `wsl` in the exact same shell session that I want to `cd` into the wsl directories.  After `exit`ing wsl back to PowerShell can I then successfully `cd` into the wsl directories from that session and only that session.  It does not matter how many other active wsl sessions are running on the same computer.

**Comment by SteveL-MSFT** [comment]
This is working for me without starting wsl in the same process.  If this still repros for you, try from cmd.exe and see if it repros to determine if it's WSL.

**Comment by Thynix** [comment]
For what it's worth to other people from the future, this now works for me:
```
PS C:\Users\Steve> cd \\wsl$\Ubuntu-20.04
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu-20.04>
```

```
> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.26100.9444
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.26100.9444
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
