### ISSUE TITLE
Subtraction in PowerShell results in strange result value

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#15789]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`11111.11 - 11110.01` or `11111.11 - 11110`

### Expected behavior

```console
PS> 11111.11 - 11110.01
1.1

PS> 11111.11 - 11110
1.11
```

### Actual behavior

```console
PS> 11111.11 - 11110.01
1.10000000000036

PS> 11111.11 - 11110
1.11000000000058
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.6
PSEdition                      Core
GitCommitId                    7.2.0-preview.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

N/A

**Comment by vexx32** [comment]
This is related to a change in .NET in the last year or two where they defaulted the string formatting for `double` (and I think `float` as well?) to what they called the 'shortest roundtrippable string' -- the shortest number that is a "true" representation of the floating point value, where if you parse that value back to a number you will get the exact same result.

I believe the only thing we'd need to change here is to ensure we use whatever ToString() method they were using as default prior to that change, if we want.

**Comment by iSazonov** [comment]
The history is in #9893.

**Comment by lukeb1961** [comment]
[decimal]11111.11 - 11110.01
1.10
[decimal]11111.11 - 11110
1.11

**Comment by SteveL-MSFT** [comment]
Decimal gives expected results, but to change the default would be a breaking change

![image](https://user-images.githubusercontent.com/11859881/193721906-40cf8aa4-89a4-408b-bd9b-495cca396c65.png)
