### ISSUE TITLE
New DetailedView could use some extra color highlighting from ConciseView

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#15783]
### Summary of the new feature / enhancement

The current ConciseView uses colors to draw your eye to the problem:

![image](https://user-images.githubusercontent.com/5177512/125826825-d3cdbd8b-2d04-4f21-b552-6332036b3ca2.png)

The new `DetailedView` setting for `$ErrorView` is great for log files but when looking through all this text, I miss the red squiggle to draw my eye quickly to the problem line in the script:

![image](https://user-images.githubusercontent.com/5177512/125826991-30913806-cc86-42bb-873c-aee9af738b86.png)

### Proposed technical implementation details (optional)

Highlight the position message and maybe the error message:

![image](https://user-images.githubusercontent.com/5177512/125827922-143242bb-dd1e-429a-9a6d-27b34b7fdc5b.png)

The actually "coloring" is totally up for debate but my primary goal is to make it easy to scan all this text for the error message and position.  I also would not want to "overdo it" with too much colorization.

**Comment by SteveL-MSFT** [comment]
This seems reasonable and minimal use of red pointing to most relevant information

**Comment by SteveL-MSFT** [comment]
Got something working, however, instead of trying to guess which Exception/ErrorRecord message to highlight, I'm going to simplify it to highlight any `Message` member:

![image](https://user-images.githubusercontent.com/11859881/125853505-73d93266-159d-47ed-8bec-296b71de8f0d.png)

**Comment by rkeithhill** [comment]
That would be handy for nested exceptions.
