### ISSUE TITLE
Get-Help Get-WindowsUpdate -Online Directed to Wordpress

### ISSUE THREAD

**Issue by supersalt97** [PowerShell/PowerShell#15792]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using PowerShell version 7.1.3
Run (to get latest Help files):
`Update-Help`

Run:
`Get-Help Get-WindowsUpdate -Online`

### Expected behavior

```console
Should be directed to Microsoft Help page for Get-WindowsUpdate
```

### Actual behavior

```console
You are directed to this Wordpress page:
https://commandlinegeeks.wordpress.com/
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/87588682/126052482-bb2b8016-cfb6-4ff4-93b2-ed50be33295e.png)

**Comment by 237dmitry** [comment]
```
 PS > Get-Command Get-WindowsUpdate
Get-Command: The term 'Get-WindowsUpdate' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: Get-WindowsUpdateLog, Get-WindowsImage, Get-WindowsPackage.

 PS > Get-Command Get-WindowsUpdate*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-WindowsUpdateLog                               1.0.0.0    WindowsUpdate
```

**Comment by SeeminglyScience** [comment]
That command is from [PSWindowsUpdate](https://www.powershellgallery.com/packages/PSWindowsUpdate/2.2.0.2) which is a community module.  You'd need to contact them if you'd like them to change up their help in some way.
