### ISSUE TITLE
Enter-PSSession breaks consolehost if used in a nested prompt

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#15791]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run this:

```
$Host.EnterNestedPrompt()
Enter-PSSession -VMName Server1 -Credential (Get-Credential)
```

When you do, you get the default `PS>` prompt and any command you enter will display `You should only run a nested pipeline from within a running pipeline.`   
The only way out from this state is to either interrupt the connection to the new runspace (unplug network cable/turn off VM) or close the window.
Other hosts like ISE and the VS code host don't have this problem and work exactly like you would expect (Although ISE does lose its tabcompletion/intellisense features).

### Expected behavior

```console
An interactive remote session to server1.
```

### Actual behavior

```console
The default prompt: "PS>" and attempting to run any commands displays the message: You should only run a nested pipeline from within a running pipeline.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.7
PSEdition                      Core
GitCommitId                    7.2.0-preview.7
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
WG-Remoting:
This appears to be a bug only for the Hyper-V connection.  Other connections (WinRM, SSH) provide a proper error message.
However, this is an unusual repro, not sure why anyone would do this.
