### ISSUE TITLE
The Update-Module cmdlet seems to want to downgrade a module

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell#15800]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm experiencing a problem with the `Update-Module` cmdlet. Today, when I ran it with the  `-WhatIf` switch, I saw the following output:

```output
What if: Performing the operation "Update-Module" on target "Version '2.2.5' of module 'PackageManagement', updating to version '1.4.7'".
```

It seems to be trying to update the PackageManagement module from version 2.2.5 to version 1.4.7. To further diagnose the issue, I ran the cmd with `-WhatIf -Verbose` switches. Here is the output.

```output
VERBOSE: Checking for updates for module 'PowerShellGet'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names: 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PowerShellGet'.
VERBOSE: Using the specified source names: 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'' for ''.
VERBOSE: Total package yield:'4' for the specified package 'PackageManagement'.
VERBOSE: Skipping installed module PowerShellGet 2.2.5.
What if: Performing the operation "Update-Module" on target "Version '2.2.5' of module 'PackageManagement', updating to version '1.4.7'".
```

On the face of it, PowerShell seems unable to correctly distinguish the "PackageManagement" module from the "PowerShellGet" module.

I've reproduced this issue both on PowerShell 7.1.3 and 7.2.0 Preview 7.

### Expected behavior

I expect PowerShell not to confuse modules for one another

### Actual behavior

On the face of it, PowerShell seems unable to correctly distinguish the "PackageManagement" module from the "PowerShellGet" module. The Update-Module cmdlet seems to want to downgrade a module.

### Environment data

```output
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.7
PSEdition                      Core
GitCommitId                    7.2.0-preview.7
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

[PowerShell 2021-07-20 11_37_46.zip](https://github.com/PowerShell/PowerShell/files/6846244/PowerShell.2021-07-20.11_37_46.zip)

**Note:** It's a screenshot in lossless WebP format. The PNG equivalent would have been ten times size and exceeded my allotted GitHub upload limit. If you, for some reason, don't have a default image viewer that displays this popular format, drag and drop it into Microsoft Edge.

**Comment by vexx32** [comment]
PowerShellGet has a dependency on PackageManagement, so updating one will usually update the other. Not sure why it's trying to downgrade it, though. You might be better off asking on the PowerShellGet repo, as it is generally reponsible for dependency resolution.

**Comment by skycommand** [comment]
I resolved the issue by completely uninstalling PowerShell, deleting its folder in `C:\Program Files`, and reinstalling it.

PackageManagement 1.4.7 and PowerShellGet 2.2.5 come with the latest version of PowerShell.
