### ISSUE TITLE
Cannot change the exported date format in Export-Csv (as I could in PS5.1)

### ISSUE THREAD

**Issue by o-o00o-o** [PowerShell/PowerShell#15828]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

 In Powershell 5.1 (my user has en-GB culture set)

If I do this

```
@([PSCustomObject]@{Name="test1";Date=(Get-date)},[PSCustomObject]@{Name="test2";Date=(Get-date)})| ConvertTo-Csv -NoTypeInformation
"Name","Date"
"test1","26/07/2021 12:22:27"
"test2","26/07/2021 12:22:27"
```

However to correct the datetime representation I could do this

``` powershell
$(Get-Culture).DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd' ## ensure that csv exports dates in universal format
@([PSCustomObject]@{Name="test1";Date=(Get-date)},[PSCustomObject]@{Name="test2";Date=(Get-date)})| ConvertTo-Csv -NoTypeInformation
"Name","Date"
"test1","2021-07-26 12:21:04"
"test2","2021-07-26 12:21:04"
```

However in Powershell 7 I get this error when trying to change the ShortDatePattern

SetValueInvocationException: Exception setting "ShortDatePattern": "Instance is read-only."

### Expected behavior

```console
I should be able to (somehow) modify the date string format used by Export-Csv or ConvertTo-Csv

Some discussion around this area in https://github.com/PowerShell/PowerShell/issues/3833

Also https://stackoverflow.com/questions/14909954/set-date-format-to-be-used-in-powershell-export-csv
```

### Actual behavior

```console
SetValueInvocationException: Exception setting "ShortDatePattern": "Instance is read-only."
```

### Error details

```console
Exception             :
    Type           : System.Management.Automation.SetValueInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception setting "ShortDatePattern": "Instance is read-only."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ExceptionWhenSetting
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 3
            HistoryId        : -1
            Line             : $(Get-Culture).DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd' ## ensure that csv
exports dates in universal format
            PositionMessage  : At line:1 char:3
                               + $(Get-Culture).DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd' ## ensu …
                               +   ~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : ConvertToMethodInvocationException
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation,
Version=7.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception,
Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    Message        : Exception setting "ShortDatePattern": "Instance is read-only."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type       : System.InvalidOperationException
        TargetSite :
            Name          : set_ShortDatePattern
            DeclaringType : System.Globalization.DateTimeFormatInfo
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        StackTrace :
   at System.Globalization.DateTimeFormatInfo.set_ShortDatePattern(String value)
   at CallSite.Target(Closure , CallSite , Object , String )
        Message    : Instance is read-only.
        Source     : System.Private.CoreLib
        HResult    : -2146233079
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
FullyQualifiedErrorId : ExceptionWhenSetting
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 3
    HistoryId        : -1
    Line             : $(Get-Culture).DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd' ## ensure that csv exports
dates in universal format
    PositionMessage  : At line:1 char:3
                       + $(Get-Culture).DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd' ## ensu …
                       +   ~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Hopefully the above is clear

**Comment by iSazonov** [comment]
The property is exposed as read-only by .Net. You can use `Get-Date -Format "yyyy-MM-dd"` to get a format you need.

**Comment by o-o00o-o** [comment]
Hi thanks for the response. 

The properties in Powershell are all marked as get/set?
```
Get-UICulture | gm
....
DateTimeFormat                 Property   System.Globalization.DateTimeFormatInfo DateTimeFormat {get;set;}
                                                                                                      *****
```
Also the suggestion doesn't deal with the use case that I raised. ```Get-Date``` doesn't apply to ConvertTo-Csv/Export-Csv so not sure if I'm missing something but doesn't seem relevant?

The only way that I can figure out how to do it is to apply a custom Select-Object Property Parameter and loop through applying an appropriate transform on each field. Pretty painful to code and inefficient to run rather than just being able to apply culture format string as per PS5.1

Feels like there should be a simpler way in Powershell that gets back to a one line solution as per Powershell 5.1. Is this not considered a bug if not a known documented departure from PS 5.1? Should I raise as a feature request if not considered as a bug?

**Comment by iSazonov** [comment]
You assign ShortDatePattern which can be readonly. PowerShell follows .Net.

**Comment by rjmholt** [comment]
> The property is exposed as read-only by .Net.

Just to clarify, the property on the type is settable, but the CultureInfo object we get from .NET is readonly:

```console
> [cultureinfo]::CurrentCulture.IsReadOnly
True
```

> Is this not considered a bug if not a known documented departure from PS 5.1?

`Get-Culture` is just a thin wrapper around the CultureInfo .NET API. .NET seem to have made a change here and there's not much we can do about it.

I have opened https://github.com/dotnet/runtime/issues/56405 to discuss this or at least get it documented.

The workaround is:

```powershell
$culture = [cultureinfo]::new('en-GB')
$culture.DateTimeFormat.ShortDatePattern = 'yyyy-MM-dd'
Set-Culture $culture
```

**Comment by rjmholt** [comment]
So from the discussion in the .NET repo, this actually seems to be a bug in Windows PowerShell; the default CurrentCulture property is supposed to be a readonly instance in all .NET versions.

> Ok I've looked into this further (I originally took the original user's report at face value) and I have a rather mysterious result.
> 
> Running this directly as a .NET program I get the expected error:
> 
> ![image](https://user-images.githubusercontent.com/7009879/127217228-58b6aede-a075-4dd1-899f-70fae4cc9329.png)
>
> But running the same thing from Windows PowerShell "works":
> 
> ![image](https://user-images.githubusercontent.com/7009879/127217487-382484d6-e074-4207-8bd1-4d1d8394a057.png)
>
> And now it throws again in PS 7...
>
> So this is clearly a PowerShell issue of some kind, but I have no idea how...
