### ISSUE TITLE
Register-PackageSource: Source Location 'https://www.nuget.org/api/v2' is not valid.

### ISSUE THREAD

**Issue by Jainam13** [PowerShell/PowerShell#15823]
### Prerequisites

- [X] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When registering source package using below command:
Register-PackageSource -provider NuGet -name nuget.org -location https://api.nuget.org/v3/index.json

### Expected behavior

```console
Package installation succeeded.
```

### Actual behavior

```console
Getting below error:
Register-PackageSource: Source Location 'https://api.nuget.org/v3/index.json' is not valid.
```

### Error details

```console
Getting below error:
Register-PackageSource: Source Location 'https://api.nuget.org/v3/index.json' is not valid.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please report the issue https://github.com/oneget/oneget
