### ISSUE TITLE
Out-GridView should allow quicker keyboard filtering and selection

### ISSUE THREAD

**Issue by tolgabalci** [PowerShell/PowerShell#15826]
### Summary of the new feature / enhancement

Out-GridView is often used with -PassThru to help make a selection and continue to the next pipeline.

Right now however filtering the list and making a selection is cumbersome to do with the keyboard.

It would be great if the filter text box was selected to begin with, but even while the filter text box is selected, the up, down and selection keyboard buttons are captured. 

The idea here is when the grid view opens, the user should be able to type in a filter until they see what they need, use the arrow keys to select it and press enter, all without having to use the mouse or any other unnecessary keys.

### Proposed technical implementation details (optional)

Here is an example when calling Get-ChildItem C:\Windows\System32\WindowsPowerShell\v1.0\ | Out-GridView -PassThru | Do-SomethingWithFiles

![image](https://user-images.githubusercontent.com/2467618/126881933-6b813dd0-67f0-4ac2-9892-21f5fabbf68d.png)

The user should be able to just type ".config", then down arrow once and press enter to select powershell.exe.config. (9 keystrokes total) The user should be able to do this without any other keystrokes or having to use the mouse.

![image](https://user-images.githubusercontent.com/2467618/126881965-cbef9096-4918-4750-8d9c-3f299a873b27.png)

**Comment by vexx32** [comment]
This is probably a better fit for the https://github.com/PowerShell/GraphicalTools repository. As far as I'm aware, the Out-Gridview cmdlet currently shipped in PowerShell is effectively feature-frozen, as it only works on Windows and isn't considered worth the effort to continue development on.

The GraphicalTools repo (and module) contains a cross-platform implementation of Out-Gridview that is still being developed.

**Comment by tolgabalci** [comment]
I like the GraphicalTools Console Version of Grid View (Out-ConsoleGridView) even better and works pretty close to my needs. Thanks.
