### ISSUE TITLE
New user can not install azure powershell

### ISSUE THREAD

**Issue by ruowan** [PowerShell/PowerShell#15834]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Here is my step. I follow this doc https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.2.1. But seems there is something wrong. It makes me confuse when I first use powershell. How can I fix it?

![image](https://user-images.githubusercontent.com/52271048/127258282-92fd92fb-cc40-424e-b509-22dc8f8dbb78.png)

### Expected behavior

```console
I expected it works.
```

### Actual behavior

```console
It failed.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ruowan** [comment]
When I using this `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber` Add -AllowClobber arguments. It works for me.

**Comment by SteveL-MSFT** [comment]
The error message tells you to use the `-AllowClobber` since you already have a version installed.  This experience is being addressed as part of PowerShellGet v3
