### ISSUE TITLE
.indexof() is not working for an array of int64

### ISSUE THREAD

**Issue by AtleVa** [PowerShell/PowerShell#15835]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

[int64[]]$testarray=(10,20,40,50)
$testarray.indexof(20)

### Expected behavior

```console
Return position of indexed value. (1)
```

### Actual behavior

```console
The returned position returned is always -1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Northman-de** [comment]
This works:  `$testarray.indexof([int64]20)`
You have to cast as int64, otherwise it's interpreted as int32.
` (20).Gettype()`

**Comment by vexx32** [comment]
You can also use the `L` suffix to write int64 literals; `$testArray.IndexOf(20L)`

IndexOf() I believe has `object` as the parameter type, so it won't auto-cast to `long`.

**Comment by iSazonov** [comment]
```powershell
$testarray.indexof

OverloadDefinitions
-------------------
int IList.IndexOf(System.Object value)
```
