### ISSUE TITLE
Consider supporting GNU style double-hyphen prefixed parameters 

### ISSUE THREAD

**Issue by oising** [PowerShell/PowerShell#1584]
From psmvp list

> is there any plan to support gnus-style double hyphen parameter parsing on *nix? It seems there's already some leeway there for environment specific tweaks (if reading through the github issues list is taken into account.) What am I talking about? Well, how fully specified arguments for gnu utils are provided like --debug (double), but can be abbreviated as -d (single). Is there room to update the binder to support both -debug and --debug? (for example.) I can't see that being a breaking change, but it might be a nice spot of grease to ease the muscle memory.

**Comment by TheElf** [comment]
@SteveL-MSFT 

two questions, 

- Is this support only intended to be added to *nix environments?
  - A large number of tools released cross platform use --long-option for their options. 
- Is there any update on this? 6.0.0-Alpha.11 was reached in October.

**Comment by SteveL-MSFT** [comment]
@TheElf work for this hasn't started yet (assigned means someone is actively working on it, unassigned means the opposite).  I updated the Milestone to indicate this is something we should have before we declare a beta.  The Alpha.11 milestone used was before we had defined our 6.0.0 and 6.0.0-beta milestones and meant anything not for the first public release.

**Comment by lzybkr** [comment]
I think this requires some discussion before anyone starts work.
Is the proposal to allow `--parameter` to mean the same thing as `-parameter` when calling PowerShell commands?
If so, I have one big concern about portability. Should we do this for Windows, or *nix only? Either way, it will allow folks to write scripts that are not portable to Windows PowerShell.

**Comment by joeyaiello** [comment]
We talked about this one in our last @PowerShell/powershell-committee meeting. We definitely have a strong desire to align with Linux conventions (and are open to any other suggestions in that space). 

However, there's a few reasons why we feel like this could provide a negative value without a strong counter-benefit:

- As @lzybkr says, this will break portability with Windows PowerShell scripts downlevel (though @jpsnover maintains, and many of us agree, that this isn't a reason in and of itself to reject places where we can align with Linux)
- `--PascalCase` still won't look like `--lisp-case`
- `--d` will actually work for `--debug` when there's not a disambiguation problem
- One can be (reasonably) certain when mixing and matching native commands and PowerShell cmdlets that `--arguments` apply to native commands

**Comment by SteveL-MSFT** [comment]
Based on @PowerShell/powershell-committee decision, we are not moving forward with this
