### ISSUE TITLE
Ordered Dictionary keys are not numerically indexable

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#15843]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Indexing keys in a hash table does make much sense as the keys are unordered by design.
But are expected to work on an [`[ordered]`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_hash_tables#creating-ordered-dictionaries) dictionary.

```PowerShell
$a = [ordered]@{ a = 1; b = 2; c = 3 }
$a.Keys[0] # $a.get_Keys()[0]
$a.Keys[1] # $a.get_Keys()[1]
```

### Expected behavior

```console
# Index 0 return a
$a.Keys[0] # $a.get_Keys()[0]
a

# Index 1 return b
$a.Keys[1] # $a.get_Keys()[1]
b
```

### Actual behavior

```console
# Index 0 returns all keys
$a.Keys[0] # $a.get_Keys()[0]
a
b
c

# Index 1 and successive indices return $Null
$a.Keys[1] # $a.get_Keys()[1]
```

### Error details

```console
No errors (unless strict mode is set)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The same issue exists in **Windows PowerShell 5.1**
Related:

- [`#2861` Deserialized Ordered Dictionary via Import-Clixml is not numerically indexable](https://github.com/PowerShell/PowerShell/issues/2861)
- [`#14791` [Ordered] doesn't fully support numeric keys](https://github.com/PowerShell/PowerShell/issues/14791)

**Comment by iRon7** [comment]
Related:

- [`#2861` Deserialized Ordered Dictionary via Import-Clixml is not numerically indexable](https://github.com/PowerShell/PowerShell/issues/2861)
- [`#14791` [Ordered] doesn't fully support numeric keys](https://github.com/PowerShell/PowerShell/issues/14791)

**Comment by scriptingstudio** [comment]
a workaround
```
@($a.Keys)[0]
a
```

**Comment by vexx32** [comment]
This would be a .NET issue, anyway; OrderedDictionary is a .NET type.

The type of the Keys property is `OrderedDictionaryKeyValueCollection` which apparently doesn't implement an indexer, so unless .NET adds one, there's only so much PowerShell can do there, I think.

**Comment by iRon7** [comment]
> This would be a .NET issue, anyway;

Does that mean that you like me to open a new issue at the .Net repository and close this one?

**Comment by SeeminglyScience** [comment]
You'd have to ask them to change the return type of `IDictionary.Keys` to `IList`.  You're welcome to open that issue, but fair warning that that is very unlikely.  It'd be a massive breaking change to a sort of out dated API.

Some workarounds:

```powershell
([object[]]$dict.Keys)[0]

$dict.Keys.ForEach{ $_ }[0]

$keys = [object[]]::new($dict.Keys.Count)
$dict.Keys.CopyTo($keys, 0)
$keys[0]
```

**Comment by iRon7** [comment]
I have transferred this into a .Net issue: [`#6517` Change the return type of `IDictionary.Keys` to `IList`](https://github.com/dotnet/core/issues/6517)

**Comment by iRon7** [comment]
@vexx32, can you/*the pwsh team* confirm my assumptions at related **.Net** issue: [`#6517` Change the return type of `IDictionary.Keys` to `IList`](https://github.com/dotnet/core/issues/6517)?
