### ISSUE TITLE
Steppable Pipeline breaks $? value, always returning true

### ISSUE THREAD

**Issue by brunovieira97** [PowerShell/PowerShell#15858]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a PowerShell module that overrides `Out-Default` using a steppable pipeline to color the output of some Cmdlets. The problem is, while using my module, `$?` will always return `True`, regardless if the last command had failed or not.

I believe `$?` is returning `True` due to the last actual command running being the `$steppablePipeline.End()`, thus affecting the last exit code capture.

Since I'm not very experienced in PowerShell, I don't know if this is an expected limitation, or if there should be an internal logic for going around this.

Here's a snippet of my module's code:
```powershell
function Out-Default {
	[CmdletBinding(HelpUri = 'http://go.microsoft.com/fwlink/?LinkID=113362', RemotingCapability = 'None')]
	param(
		[switch] ${Transcript},
		[Parameter(Position = 0, ValueFromPipeline = $true)][PSObject] ${InputObject}
	)

	begin {
		try {
			$outBuffer = $null

			if ($PSBoundParameters.TryGetValue('OutBuffer', [ref] $outBuffer)) {
				$PSBoundParameters['OutBuffer'] = 1;
			}

			$wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand('Microsoft.PowerShell.Core\Out-Default', [System.Management.Automation.CommandTypes]::Cmdlet);
			$scriptCmd = {& $wrappedCmd @PSBoundParameters }

			$steppablePipeline = $scriptCmd.GetSteppablePipeline();
			$steppablePipeline.Begin($PSCmdlet);
		} catch {
			throw
		}
	}
	
	process {
		try {
			# do some stuff
				
                        $steppablePipeline.Process($_);
		} catch {
			throw
		}
	}

	end {
		try {
			$steppablePipeline.End();
		} catch {
			throw
		}
	}
}
```

### Expected behavior

```console
# provoking an error so $? will be "false"
PS> ll
ll: The term 'll' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS> $?
False
```

### Actual behavior

```console
# provoking an error so $? will be "false"
PS> ll
ll: The term 'll' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS> $?
True
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
It has nothing to do with steppable pipeline, but only because the customized `out-default` is a script cmdlet. See the below example:
```
function Out-Default {
    process {
        [Console]::WriteLine($_.ToString())
    }
    end {
        # non-op
        $null = 1+1
    }
}

PS:2> ll
The term 'll' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS:3> $?
True
```
So basically, when the end block of this `Out-Default` runs, it's a script block execution, and it runs successfully, therefore, `$?` gets set to `true`, which overrides the previous `false` value.

**Comment by daxian-dbw** [comment]
The Engine WG discussed this issue today. It may be possible to fix this issue by saving the `$?` value before executing `Out-Default` and restoring the value after execution -- we should do this only for the top level pipeline, so we would need to check if the current pipeline is the only one in the pipeline stack, and if that's the case, we assume the `out-default` command is automatically added by the host, and thus make it not affect `$?` value.

However, it's not clear if this behavior change would cause unexpected issue elsewhere, especially to the other host implementations such as in PowerShell VSCode extension and PowerShell Jupyter sub-kernel. We are open to further discussion, but we'd need substantial extra validation before we go changing things.
