### ISSUE TITLE
Error when trying to open Pwsh-preview 7.2.0.preview-8

### ISSUE THREAD

**Issue by minoseah629** [PowerShell/PowerShell#15851]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

installed powershell 7.2.0.preview-8 on macosx version 11.5.1 and intel x64 processor
launch pwsh-preview 

### Expected behavior

```console
powershell should launch properly
```

### Actual behavior

```console
pwsh-preview does not launch
```

### Error details

```console
get bad CPU type in executable: pwsh-preview
```

### Environment data

```powershell
unavailable since unable to launch pwsh-preview
```

### Visuals

<img width="377" alt="Screen Shot 2021-07-30 at 8 11 04 PM" src="https://user-images.githubusercontent.com/1980068/127722476-d1bb5b0a-3d2d-4b55-99a4-cca8e8656450.png">

**Comment by jborean93** [comment]
Curious what shows up when you do `file $(which pwsh)`?

**Comment by minoseah629** [comment]
I am invoking pwsh-preview directly

**Comment by minoseah629** [comment]
i see what happened.  i accidentally install arm instead x64
