### ISSUE TITLE
Show-MarkDown displays two lines on the same line if the first one ends with bold or italic text

### ISSUE THREAD

**Issue by pluma9** [PowerShell/PowerShell#15852]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Use `Show-MarkDown` to display a file with the following content:
```md
- This line ends with a italic *word*
- This line should be be displayed on a separate line
- This line ends with a bold **word**
- This line should be be displayed on a separate line
```

### Expected behavior

The following text is rendered:

>- This line ends with a italic *word*
>- This line should be be displayed on a separate line
>- This line ends with a bold **word**
>- This line should be be displayed on a separate line

### Actual behavior

The following text is rendered:

>- This line ends with a italic word- This line should be be displayed on a separate line
>- This line ends with a bold word- This line should be be displayed on a separate line

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/16544647/127748286-3045d743-bf05-4842-add4-277bf6b7c1a2.png)

**Comment by 237dmitry** [comment]
To start a new line, add two spaces at the end of the line. To start a new paragraph, add a new empty line.
```powershell
@"
aaa *aaa*  
bbb **bbb**  
ccc ccc

ddd ddd
"@ | Show-Markdown
```

**Comment by jhoneill** [comment]
This also happens with numbered lists as well as bulleted ones and will happen if the line ends with a link - it seems if it last thing in the line isn't plain text then the lines are concatenated. 

In addition  a `  ``` `   is treated as a single backquote wrapped in backquotes   ```   `  `  `   ```
so 
`  ``` ` 
` some powershell `
` #a comment` 
` ``` `
renders as  
``` ` ```
some powershell 
### A comment 
```  ` ```
