### ISSUE TITLE
Copy-Item with -Filter or -Include ignores -Recurse if -Path has a wildcard

### ISSUE THREAD

**Issue by Herr-Sepp** [PowerShell/PowerShell#15867]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
File structure
    ├──destination
    └──source
            ├─ file1.txt
            ├─  dict1
            │    └─ file2.txt
            └─ dict2
                  └─ file3.jpg
```

`Copy-Item -Path .\source  -Destination .\destination\ -Filter "*.txt" -Recurse`
Works as I expect: It copy all .txt to destination, keeps the container structure and omits file3.jpg

```
    └───destination
              └─source
                  ├─ file1.txt
                  ├─ dict1
                  │    └─ file2.txt
                  └───dict2
```

but 
`Copy-Item -Path .\source\*  -Destination .\destination\ -Filter "*.txt" -Recurse`
does not copy dict1 and file2.txt.

### Expected behavior

```console
└────destination
        ├── file1.txt
        └───dict1
            └── file2.txt

the same as "Copy-Item -Path .\source  -Destination .\destination\ -Filter "*.txt" -r"
but without the source folder.
```

### Actual behavior

```console
└────destination
         └─  file1.txt

it apparently did not search recursively although it was specified to do so
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Interesting, this works for GetChildItem.
