### ISSUE TITLE
PowerShell package in yum repository needs to have a payload digest.

### ISSUE THREAD

**Issue by agentoranger** [PowerShell/PowerShell#15866]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem when attempting to install PowerShell from the Microsoft yum repo when using FIPS mode on RedHat 8.4.  An additional SHA256 digest needs to be added to the package so that FIPS enabled systems running Redhat 8+ can validate the payload of the package.

https://access.redhat.com/solutions/4460971

### Expected behavior

```console
yum install powershell

Powershell would then be installed
```

### Actual behavior

```console
yum install powershell

Powershell is not installed, failing validation.
```

### Error details

```console
Error: Transaction test error:
  package powershell-7.1.3-1.centos.8.x86_64 does not verify: no digest

[root@test75-rhel8 ~]# rpm --checksig -v /var/cache/dnf/packages-microsoft-com-prod-37360e73ce94b4be/packages/powershell-7.1.3-1.centos.8.x86_64.rpm
/var/cache/dnf/packages-microsoft-com-prod-37360e73ce94b4be/packages/powershell-7.1.3-1.centos.8.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID be1229cf: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA256 Signature, key ID be1229cf: OK
    MD5 digest: NOTFOUND
```

### Environment data

```powershell
Redhat Enterprise Linux v8+ or CentOS v8+ when running in FIPS mode
```

### Visuals

![Capture](https://user-images.githubusercontent.com/9388401/128183438-447dc0e5-0b2c-451a-b478-a8cf6eb6080a.PNG)

**Comment by iSazonov** [comment]
Perhaps #15678 has fixed this.

/cc @adityapatwardhan

**Comment by agentoranger** [comment]
I had a few minutes of free time this morning, so I hopped back into that server and attempted to install PowerShell using yum.  I can see that the digest issue is still occurring.

![image](https://user-images.githubusercontent.com/9388401/132007130-539d502c-72ca-41dd-a0d9-ba0f7ac000c2.png)
