### ISSUE TITLE
[Console]::OutputEncoding unable switch to cp950 encoding in Linux

### ISSUE THREAD

**Issue by doggy8088** [PowerShell/PowerShell#15865]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Download a text file encoded with `cp950` (big5) encoding/charset

    ```sh
    curl https://blog.miniasp.com/big5-example.txt -o big5-example.txt
    ```

2. Check my Ubuntu version

    ```sh
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 20.04.2 LTS
    Release:        20.04
    Codename:       focal
    ```

3. Enter PowerShell

    ```sh
    $ pwsh
    PowerShell 7.1.3
    Copyright (c) Microsoft Corporation.

    https://aka.ms/powershell
    Type 'help' to get help.

    PS /home/will>
    ```

4. Switch encoding to big5

    ```ps1
    $PSDefaultParameterValues['*:Encoding'] = 'big5'
    ```

5. Try to cat file content but get wrong result

    ![image](https://user-images.githubusercontent.com/88981/128143569-dbdaffe6-b8fc-48ad-b85b-7938dd38c1ec.png)

### Expected behavior

This is my Windows 10 result. It's expected result.

1. Open PowerShell Core and download a text file encoded with `cp950` (big5) encoding/charset

    
    Invoke-WebRequest -Uri https://blog.miniasp.com/big5-example.txt -OutFile 'big5-example.txt'
    

2. Check my `$PSVersionTable`

    ```sh
    PS C:\> $PSVersionTable

    Name                           Value
    ----                           -----
    PSVersion                      7.1.3
    PSEdition                      Core
    GitCommitId                    7.1.3
    OS                             Microsoft Windows 10.0.19043
    Platform                       Win32NT
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0
    ```

3. Try to cat file content but get wrong result

    ![image](https://user-images.githubusercontent.com/88981/128144523-3b6c2b3b-680d-41c9-b588-b4f1e09cffd4.png)

4. Switch encoding to big5

    ```ps1
    $PSDefaultParameterValues['*:Encoding'] = 'big5'
    ```

5. Try to cat file content but get CORRECT result

    ![image](https://user-images.githubusercontent.com/88981/128144523-3b6c2b3b-680d-41c9-b588-b4f1e09cffd4.png)

### Actual behavior

See **Steps to reproduce**.

### Error details

See **Steps to reproduce**.

### Environment data

In my linux box:

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

See **Steps to reproduce**.

**Comment by 237dmitry** [comment]
Try `Get-Content` instead of `cat`. It works in my environment (Arco Linux, pwsh-7.1.3).

**Comment by doggy8088** [comment]
@237dmitry Wow, it works. Thanks!
