### ISSUE TITLE
Get-ChildItem of (Get-Volume) Paths does not work as expected

### ISSUE THREAD

**Issue by PowershellScripter** [PowerShell/PowerShell#15872]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

During the creation of a module, I run back and forth between 5.1 and pwsh (currently 7.1.3) to make sure the module will work in both versions.

While running in PWSH-7.1.3:

$ISO = 'C:\WindowsImages\Win10_21H1_English_x64.iso'
$Drive = Mount-DiskImage $ISO -StorageType ISO -NoDriveLetter -PassThru
gci -LiteralPath (Get-Volume | ?{($_.DriveType -match 'CD') -and ($_.Size -match $Drive.Size)}).Path -fo -re

I get back a live list of all the files found in 'C:\'

### Expected behavior

```console
In powershell 5.1, I get back all the files found in:

Directory: \\?\Volume{1a1cbe60-f411-11eb-aec7-001a7dda7113}
```

### Actual behavior

```console
In PWSH 7.1.3, I get back all the files found in:

Directory: C:\
```

### Error details

```console
No Errors, I just dont get the correct results path in PWSH
```

### Environment data

```powershell
Name                           Value                                                                                                  
----                           -----                                                                                                  
PSVersion                      5.1.19041.1023                                                                                         
PSEdition                      Desktop                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                
BuildVersion                   10.0.19041.1023                                                                                        
CLRVersion                     4.0.30319.42000                                                                                        
WSManStackVersion              3.0                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                    
SerializationVersion           1.1.0.1                                                                                                


&



Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Powershell 5.1

![image](https://user-images.githubusercontent.com/71091773/128242532-a1e4568a-c4d8-4042-b977-e9e9f0a93586.png)

Powershell 7.1.3

![image](https://user-images.githubusercontent.com/71091773/128242687-7078d35c-31fc-42e8-bdfc-41a9cc5dfeb5.png)

**Comment by fgimian** [comment]
I suspect this may be related to an issue I'm seeing in PowerShell 7.2.x, I don't recall this in 7.0.x.  `Get-Volume` ocassionally doesn't return any results.

```powershell
C:\Users\Fots> Get-Volume

DriveLetter FriendlyName       FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining      Size
----------- ------------       -------------- --------- ------------ ----------------- -------------      ----
D           Overflow           NTFS           Fixed     Healthy      OK                    199.57 GB 687.37 GB
E           Kontakt Libraries  NTFS           Fixed     Healthy      OK                    262.43 GB   1.29 TB
            Work Windows 10 NTFS           Fixed     Healthy      OK                     46.76 GB 244.12 GB
H           Fotsies Backup 2   NTFS           Fixed     Healthy      OK                      2.78 TB   3.64 TB
I           Fotsies Backup 1   NTFS           Fixed     Healthy      OK                      2.78 TB   3.64 TB
F           Sample Packs       NTFS           Fixed     Healthy      OK                     18.71 GB  56.37 GB
C           Windows 11         NTFS           Fixed     Healthy      OK                    104.52 GB 488.17 GB
G           Backup             NTFS           Fixed     Healthy      OK                    753.89 GB   1.82 TB
```

As you can see, the first call to `Get-Volume` returned nothing.  This is causing my scripts to fail on the first run.

@SteveL-MSFT Can you confirm if this is the same issue or does my problem look different?  Just went on the hunt for similar issues before opening a fresh one.

Huge thanks
Fotis

**Comment by iSazonov** [comment]
@fgimian It is another issue and I can not reproduce. If you can reproduce on _clean_ system please open new issue.

**Comment by Binomimus** [comment]
Still an issue in 7.2.5
