### ISSUE TITLE
How to read pipeline with iso-8859-1 encoding characters?

### ISSUE THREAD

**Issue by doggy8088** [PowerShell/PowerShell#15871]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Download a text file encoded with `ISO-8859-1` (Latin-1) encoding/charset

    ```sh
    curl https://blog.miniasp.com/latin1-example.txt -o latin1-example.txt
    ```

2. Check my Ubuntu version

    ```sh
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 20.04.2 LTS
    Release:        20.04
    Codename:       focal
    ```

3. Enter PowerShell and use linux's `cat` to simulate `ISO-8859-1` (Latin-1) encoding output

    ```sh
    $ pwsh
    PowerShell 7.1.3
    Copyright (c) Microsoft Corporation.

    https://aka.ms/powershell
    Type 'help' to get help.

    PS /home/will>cat ./latin1-example.txt > ./cc.txt
    ```
    
    ![image](https://user-images.githubusercontent.com/88981/128235895-8760ec92-d67e-434f-b6e0-b369c06b5ef9.png)

4. Configure `$PSDefaultParameterValues` and try again

    ```sh
    PS /home/will> $PSDefaultParameterValues['*:Encoding'] = 'iso-8859-1'
    PS /home/will> Get-Content ./latin1-example.txt
    ´ú¸Õ
    PS /home/will> wc ./latin1-example.txt
    0 0 4 ./latin1-example.txt
    PS /home/will> cat ./latin1-example.txt > ./cc.txt
    PS /home/will> Get-Content ./cc.txt
    ???
    ```

    ![image](https://user-images.githubusercontent.com/88981/128235573-d7b053e2-aed1-490d-b56f-642bc03c0ac0.png)

### Expected behavior

```console
I expected to read the pipelines data using the same encoding/charset.
```

### Actual behavior

```console
PowerShell can't handle pipelines with encoding correctly.
```

### Error details

```console
I'm in a Linux environment. I have a command which can only output ISO-8859-1 encoding text.  I'd like to read it and save AS IS. But PowerShell seems will always save with a wrong charset. The content will not be the original one.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
`/usr/bin/cat` nothing knows about file encoding and powershell's encoding. You need to start it from `bash` (to avoid powershell's redirection `>`) or use `Get-Content`:

```
PS > $PSDefaultParameterValues['*:Encoding'] = 'iso-8859-1'
PS > bash -c "cat ./latin1-example.txt > cc.txt"
PS > Get-Content ./cc.txt
´ú¸Õ
PS > Get-Content ./latin1-example.txt > cc.txt
PS > Get-Content ./cc.txt
´ú¸Õ
```

**Comment by doggy8088** [comment]
It PowerShell can have a `$InputEncoding` predefined variable. Probably this can be solved.

**Comment by jborean93** [comment]
That's what `[Console]::OutputEncoding` is meant to be for. PowerShell/.NET should be using that when reading the stdout/stderr bytes from the native application. This is what it does on Windows and I would assume it's also what it does on Linux.
