### ISSUE TITLE
Make `-Replace` operator support multiple Regex/Substitution pairs. 

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#15876]
### Summary of the new feature / enhancement

Currently the only way to do multiple replacements in a string is to chain the [`-Replace`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_comparison_operators#replacement-operator) operator like:

```PowerShell
'hello world' -Replace 'h', 'H' -Replace ' ' -Replace 'w', 'W'
HelloWorld
```
See StackOver flow issues:
* [How to replace multiple strings in a file using PowerShell](https://stackoverflow.com/q/3403217/1701026)
* [Replacing pesky 'umlaut' | standard way does not work](https://stackoverflow.com/q/68636502/1701026)
* [Replace many variable strings with one -replace expression](https://stackoverflow.com/q/28953516/1701026)
* ...

Currently the `-Replace` Operator returns an error when more than 2 elements are supplied:

```PowerShell
'Hello World' -Replace 'a', 'b', 'c'
```

> `InvalidOperation: The -Replace operator allows only two elements to follow it, not 3.`

But I think there are no technical obstacles to support multiple **Regex**/**Substitution** pairs.

### Proposed technical implementation details (optional)

<details>
  <summary>Prototype</summary>

```PowerShell
function Replace-String {
    [CmdletBinding()][OutputType([string])] param(
        [Parameter(Mandatory = $True, ValueFromPipeLine = $True)]$InputObject,
        [Parameter(Mandatory = $True, Position = 0)][Array]$Pair,
        [Alias('CaseSensitive')][switch]$MatchCase
    )
    for ($i = 0; $i -lt $Pair.get_Count()) {
        if ($Pair[$i] -is [Array]) {
            $InputObject = $InputObject |Replace-String -MatchCase:$MatchCase $Pair[$i++]
        }
        else {
            $Regex = $Pair[$i++]
            $Substitute = if ($i -lt $Pair.get_Count() -and $Pair[$i] -isnot [Array]) { $Pair[$i++] }
            if ($MatchCase) { $InputObject = $InputObject -cReplace $Regex, $Substitute }
            else            { $InputObject = $InputObject -iReplace $Regex, $Substitute }
        }
    }
    $InputObject
}; Set-Alias Replace Replace-String
```
</details>

In this prototype idea, you can supply the **Regex**/**Substitution** pairs as a flat array:

```PowerShell
$String = 'Das Üben von Xylophon und Querflöte ist zweckmäßig.'
$String |Replace -MatchCase 'ö','oe', 'ä','ae', 'ü','ue', 'ß','ss', 'Ö','Oe', 'Ü','Ue', 'Ä','Ae'
Das Ueben von Xylophon und Querfloete ist zweckmaessig.
```

Or  as **Regex**/**Substitution** pairs:
<sub>(knowing that the elements normally should be of type `[String]`, `[Regex]` or `[ScriptBlock]`)</sub>

```PowerShell
$String = 'Das Üben von Xylophon und Querflöte ist zweckmäßig.'
$String |Replace -MatchCase ('ö','oe'), ('ä','ae'), ('ü','ue'), ('ß','ss'), ('Ö','Oe'), ('Ü','Ue'), ('Ä','Ae')
Das Ueben von Xylophon und Querfloete ist zweckmaessig.
```

```PowerShell
'hello world' |Replace ('h','H'), ' ', ('w','W')
HelloWorld
```

```PowerShell
'Name1234' |Replace ('\d', '#'), ('\w', '@')
@@@@####
```

**Comment by iSazonov** [comment]
It is unlikely that we can do any better than a simple Regex.Replace.

**Comment by iRon7** [comment]
I guess this propose doesn't have enough support to keep alive and therefore should be labeled as <kbd>Resolution-Declined</kbd>
Anyways, I decided to closed it.
