### ISSUE TITLE
Generic Linux support

### ISSUE THREAD

**Issue by hros** [PowerShell/PowerShell#15875]
### Summary of the new feature / enhancement

Support generic Linux distributions with a bootstrap that does not rely on a distribution-specific binary

My motivation is for the Julia binary package build system, but it would be useful for a variety of thin containers

**Comment by iSazonov** [comment]
There is already powershell-7.2.0-preview.8-linux-x64-fxdependent.tar.gz

**Comment by hros** [comment]
thanks.
is it possible to use it in a "vanilla" linux container/sandbox?
what about the required .NET framework? is there a portable / distribution-agnostic version?
