### ISSUE TITLE
Get-AIPFileStatus and Set-AIPFileLabel PowerShell crashing on dataset loops or object loops

### ISSUE THREAD

**Issue by seschu01** [PowerShell/PowerShell#15870]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

StephenSchuster-2883 asked · 3 hours agoActions
AIP - GetAIPFileStatus and Set-AIP Labels cause Powershell to crash....any ideas?
So apparently the Powershell commands for Get AIPFileStatus and Setting a label are not working properly in bulk operations.

I have been testing this over the past two weeks and can consistently replicate this on both my personal machine and at work. My Personal Machine means my DEV Azure instance whereas work is using theirs.

From what I can tell there is no rhyme or reason to this and it may actually work from time to time, but it will ultimately fail with one of the two errors listed below:

An error has occurred that was not properly handled. Additional information is shown below. The Windows PowerShell process will exit.
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

or...

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.InformationProtection.Internal.SdkWrapperPINVOKE.delete_Opaque(HandleRef jarg1)
at Microsoft.InformationProtection.Internal.Opaque.Dispose(Boolean disposing)
at Microsoft.InformationProtection.Internal.Opaque.Dispose()
at Microsoft.InformationProtection.Internal.ProtectionEngine.Observer.SwigDirectorMethodOnGetRightsForLabelIdSuccess(IntPtr rights, IntPtr context)

When this does happen it will also trigger an Event Viewer failure which is about as helpful as a poke in the eye:

ER1nTNoQB-pBihwE-t0SNeAB0RJOm6ekn8PtkU2Sw77qJQ

I have executed this via direct PowerShell, PowerShell ISE, and a Scheduled PowerShell Job. I do find that the scheduled job will continually run but when going through my log files I find that it does not apply the Labels properly or simply crashes when doping the initial get.

My final code looked something like this:

Get-ChildItem $strDestSource -File -Recurse | Get-AIPFileStatus | Where-Object {($_.SubLabelId -eq $aipExistingLabelId)}

I would use this for count purposes. Sometimes this fails ...

Then we would do the actual apply:

Get-ChildItem $strDestSource -File -Recurse | Get-AIPFileStatus | Where-Object {($_.SubLabelId -ne $aipExistingLabelId)} | Set-AIPFileLabel -LabelId $secID -PreserveFileDetails -JustificationMessage "Automated Labeling before migration"

...and again this would work sometimes but would eventually fail randomly.

To be fair I also grabbed the Get-ChildItem object and did a foreach loop and tried to update the files one by one, but again - random failure.

Function aip{
param([parameter(ValueFromPipeline)][object[]]$inclusionsFiles)
Write-Host "AIP Calculation for file: " $inclusionsFiles -ForegroundColor Green
Process{
foreach ($file in $inclusionsFiles){
try{
.....
Set-AIPFileLabel -Path $file.FullName -LabelId $aipSubLabelId -PreserveFileDetails -JustificationMessage "Automated Labeling before migration $startTime" | Out-Null
.....

Has ANYONE seen ANYTHING from MS on this bug. Is it confirmed, when is it going to be fixed????

### Expected behavior

```console
I would expect PowerShell to not crash and the Labels to be set properly. This seems to work sporadically and definately if I manually powershell the command per file.
```

### Actual behavior

```console
The actual behaviour is it will randomly generate the following errors:

An error has occurred that was not properly handled. Additional information is shown below. The Windows PowerShell process will exit.
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

or...

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.InformationProtection.Internal.SdkWrapperPINVOKE.delete_Opaque(HandleRef jarg1)
at Microsoft.InformationProtection.Internal.Opaque.Dispose(Boolean disposing)
at Microsoft.InformationProtection.Internal.Opaque.Dispose()
at Microsoft.InformationProtection.Internal.ProtectionEngine.Observer.SwigDirectorMethodOnGetRightsForLabelIdSuccess(IntPtr rights, IntPtr context)
```

### Error details

```console
Errors:

An error has occurred that was not properly handled. Additional information is shown below. The Windows PowerShell process will exit.
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

or...

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.InformationProtection.Internal.SdkWrapperPINVOKE.delete_Opaque(HandleRef jarg1)
at Microsoft.InformationProtection.Internal.Opaque.Dispose(Boolean disposing)
at Microsoft.InformationProtection.Internal.Opaque.Dispose()
at Microsoft.InformationProtection.Internal.ProtectionEngine.Observer.SwigDirectorMethodOnGetRightsForLabelIdSuccess(IntPtr rights, IntPtr context)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     2.11.58.0  AzureInformationProtection          {Add-AIPScannerRepository, Clear-AIPAuthentication, Export-AIPLogs, Get-AIPFileStatus...}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.4.7      PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
```

### Visuals

None, all PS
![Error](https://user-images.githubusercontent.com/16479772/128233692-f3909a5d-151f-4ccd-83db-4f02537f1d86.png)

**Comment by fMichaleczek** [comment]
@seschu01 You are in the PowerShell Core repository, so no support for PowerShell 5.1. Then, your problem is located in a module, so please contact your module provider.
I think you can close your issue.
PS : you should try a higher module version and disabled your antivirus.

**Comment by SteveL-MSFT** [comment]
As best I can tell this module might be owned by AzPS team, try opening an issue in this repo: https://github.com/Azure/azure-powershell
