### ISSUE TITLE
PowerShell fails to fetch Certificate object from Current user certificate store when launched as Different user

### ISSUE THREAD

**Issue by v-kajaye** [PowerShell/PowerShell#15878]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using smart card credentials when PowerShell is running as a different user from the user currently logged in to Windows fails to fetch the certificate of Smart Card from the current user  certificate store[certmgr.msc]

The logged-in user account is different than the smart card account. 

Steps to repro:
-Launch PS 5.1 or 7 as a different user[type 2 authentication] and use the Smart card to authenticate when prompted for Windows credential, enter the pin for PSC
-connect to Azure AD or any module : for example Connect-AzureAD
-Use the UPN of the AD account that is mapped to Smart card and proceed further. Prompted to select password or pin/smart card. When selecting the latter, the certificate fails to fetch from the current user store

However, I can connect to Azure AD with the same PSC when PS is launched in elevated mode[run as Administrator] or local user account. The certificate object gets successfully detected and I get a prompt to enter Pin. 

### Expected behavior

```console
Steps to repro:
-Launch PS 5.1 or 7 as a different user[type 2 authentication] and use the Smart card to authenticate when prompted for Windows credential, enter the pin for PSC
-connect to Azure AD or any module: for example Connect-AzureAD
-Use the UPN of the AD account that is mapped to Smart card and proceed further. Prompted to select password or pin/smart card. When selecting the latter, the certificate fails to fetch from the current user store
```

### Actual behavior

```console
On selecting Certificate-based authentication, the auth prompt should fetch the certificate appropriate for the scenario and allow us to enter a pin to authenticate. In the reported scenario, the certificate request times out and throws an error No valid client certificate found
```

### Error details

```console
No valid client certificate found in the request. No valid certificates found in the user's certificate store. Please try again after closing and reopening the browser and choose a different authentication method.
```

### Environment data

```powershell
PS C:\Users\v-kajaye> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

[PS-Certificate Prompt failure.zip](https://github.com/PowerShell/PowerShell/files/6940083/PS-Certificate.Prompt.failure.zip)

**Comment by PaulHigin** [comment]
@WG-Security
This appears to be an external issue with the `Connect-AzureAD` azure module, which the PowerShell team does not own.
The azure module handles how certificates are retrieved and the modules owners need to investigate.
https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0

**Comment by v-kajaye** [comment]
Hi Paul,

This is not just with Azure AD module. I noticed the same issue with MSOLS and other PS module that connect to Azure or Exchange online.

Regards,
Jayesh Kamat
***@***.******@***.***> | DXC Technology Services LLC
***@***.***> Windows Tier II Support
Employee Experience
Support Contacts:

  *   Phone:  (866) 539-4191 or Click Here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.service-now.com%2Fsp%3Fid%3Dcall&data=02%7C01%7Cv-kajaye%40microsoft.com%7C84442e6ae1da44b12a6a08d7dea49ad4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637222670949475940&sdata=5koMtnGvSxTGJ%2BTGnc7hz6cwQ719Rno8%2BA%2BvfVDUD%2Bw%3D&reserved=0>
  *   Yammer:  Click Here​<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FBingIT%2FSitePages%2FSkypeCall.aspx&data=02%7C01%7Cv-kajaye%40microsoft.com%7C84442e6ae1da44b12a6a08d7dea49ad4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637222670949575888&sdata=wBD8kW4RLL7IJ6qS65bj1l8w17oumfqiNm3wwIxksnQ%3D&reserved=0>
  *   Chat:  ***@***.***>
***@***.***
