### ISSUE TITLE
`System.Management.Automation.SwitchParameter` is not properly passed to Remote `Invoke-Command` Sessions

### ISSUE THREAD

**Issue by aolszowka** [PowerShell/PowerShell#15884]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Attempt to execute the following script; you will need at least one remote machine:

```powershell
function Test-SwitchRemoteBehavior {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $false, ValueFromPipelineByPropertyName = $true)]
        [System.Management.Automation.SwitchParameter]$Force
    )
    process {
        # In these cases the -Force switch works as expected
        Write-Host "###########################################################"
        Write-Host "# Show how this works locally                             #"
        Write-Host "###########################################################"
        Write-Host "Force was false: $($Force -eq $false)"
        Write-Host "Force was NOT present: $($Force.IsPresent -eq $false)"

        # In these cases the -Force switch works as expected still
        Invoke-Command -ScriptBlock {
            param([System.Management.Automation.SwitchParameter]$Force)
            process {
                Write-Host "###################################################"
                Write-Host "# Show on the local Computer via Invoke-Command   #"
                Write-Host "###################################################"
                Write-Host "Force was false: $($Force -eq $false)"
                Write-Host "Force was NOT present: $($Force.IsPresent -eq $false)"
            }
        } -ArgumentList @($Force)

        # In this case the value of the -Force switch is lost for some reason
        # it appears to be a bug
        Invoke-Command -ComputerName 'SomeRemoteMachineHere' -ScriptBlock {
            param([System.Management.Automation.SwitchParameter]$Force)
            process {
                Write-Host "###################################################"
                Write-Host "# Show on a Remote Computer via Invoke-Command    #"
                Write-Host "###################################################"
                Write-Host "Force was false: $($Force -eq $false)"
                Write-Host "Force was NOT present: $($Force.IsPresent -eq $false)"
            }
        } -ArgumentList @($Force)
    }
}

Test-SwitchRemoteBehavior -Force
```

For what its worth this behavior is also present in PowerShell 5.1 and several others have encountered it as seen around the Internet:

StackOverflow: https://stackoverflow.com/questions/24011684/powershell-pass-a-switch-to-a-function-with-invoke-command
VMWare Post: https://communities.vmware.com/t5/VMware-PowerCLI-Discussions/How-to-past-Boolean-variables/td-p/2820126

The work around is to pass this using `$Force.IsPresent` but it would be great to understand why this quirk exists, as far as I can tell there was never a bug report or even an explanation of why this behavior differs.

### Expected behavior

```console
###########################################################
# Show how this works locally                             #
###########################################################
Force was false: False
Force was NOT present: False
###################################################
# Show on the local Computer via Invoke-Command   #
###################################################
Force was false: False
Force was NOT present: False
###################################################
# Show on a Remote Computer via Invoke-Command    #
###################################################
Force was false: False
Force was NOT present: False
```

### Actual behavior

```console
###########################################################
# Show how this works locally                             #
###########################################################
Force was false: False
Force was NOT present: False
###################################################
# Show on the local Computer via Invoke-Command   #
###################################################
Force was false: False
Force was NOT present: False
###################################################
# Show on a Remote Computer via Invoke-Command    #
###################################################
Force was false: True
Force was NOT present: True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Jaykul** [comment]
Switch parameters _explicitly_ and _inherently_ cannot be bound positionally. The workarounds are legion.

- use `$using:force` instead of passing a parameter at all
- use a boolean in the parameter block inside Invoke
- prefix it with `[Parameter(Position=0)]` to make it positional

**Comment by aolszowka** [comment]
@Jaykul I appreciate the response; can you expound upon how you gained this knowledge? Are there other parameters that are affected by this?

> Switch parameters explicitly and inherently cannot be bound positionally.

I was attempting to do more research on my own to find where this might be documented and ran across this old post: 

https://devblogs.microsoft.com/powershell/how-and-why-to-use-splatting-passing-switch-parameters/

I suspect that it works because even though it is using [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.1), it is using the `HashTable` behavior as opposed to the `Array` behavior which would have made it positional.

As far as this issue itself, not sure what to do here. I think this is `by-design` and perhaps just closing the issue with a comment to that effect is good enough? Would it be worth documenting anywhere?

**Comment by vexx32** [comment]
It might be worth documenting in one of the remoting articles, or even for Invoke-Command itself. Would also bear mentioning here as well: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.1#switch-parameters

**Comment by Jaykul** [comment]
Hmm. That's always a fun question: how do you know that?

I'm honestly not sure how I learned that initially. I noticed it again recently while prototyping ... I was working on something recently in Pester where I needed to replicate positional parameters. I "knew" how it worked, but as usual, I prototyped in the terminal to validate my knowledge, and I wrote something like this:

```PowerShell
function Test-Parameter {
  [CmdletBinding()]param(
    [string]$Path,
    [switch]$Force,
    [string]$Destination
  )
}
```

And then ran this to get positional parameters:

```PowerShell
(Get-Command Test-Parameter).Parameters.Values.Where{ $_.Attributes.Position -ge 0 }
```

```output

Name            : Path
ParameterType   : System.String
ParameterSets   : {[__AllParameterSets, System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : False
Aliases         : {}
Attributes      : {, System.Management.Automation.ArgumentTypeConverterAttribute}
SwitchParameter : False

Name            : Destination
ParameterType   : System.String
ParameterSets   : {[__AllParameterSets, System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : False
Aliases         : {}
Attributes      : {, System.Management.Automation.ArgumentTypeConverterAttribute}
SwitchParameter : False

```

If you run that without the `.Where` filter, you'll see all the "built in" parameters and switch(es), but when you filter for positional parameters, it skips over the `Force` switch. PowerShell adds implicit `[Parameter()]` and `[ArguymentTypeConverter()]` attributes on all parameters, but the implicit ParameterAttribute does not include a Position value for switches (or rather, it's set to `[int]::MinValue`). I was relieved by that (and slightly surprised by the "ExperimentName" and "ExperimentAction" fields that I had never seen before) and it stuck with me.

I also know that in C# [the type documentation](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.switchparameter?view=powershellsdk-7.0.0) says it "can **only** be used as a switch" (emphasis mine), so that's clearer than the PowerShell about doc.

I just opened [a PR against the about topic](https://github.com/MicrosoftDocs/PowerShell-Docs/pull/8027) to make it clearer there.

**Comment by aolszowka** [comment]
I have not seen any documentation updated to specifically reference Switch Parameters being improperly passed to `Invoke-Command`.

The documentation from @Jaykul was updated to talk about how `Switch parameters are excluded from positional parameters by default.` but this still does nothing to note that this won't work in `Invoke-Command` @sdwheeler had a comment on the linked PR that indicated that we should update the docs, but that didn't appear to go anywhere.

I'd still consider this open, but if you're trying to clean out the backlog I'd understand closing the issue out. Hopefully the next DevOps Engineer runs across this when it doesn't work in their environment as the documentation still makes no mention of it!

I'm going to leave this as open unless one of the maintainers wants to close this out as `WONTFIX`.

**Comment by sdwheeler** [comment]
@aolszowka Please open an issue in the documentation repository describing what needs to be documented about `Invoke-Command`.

**Comment by aolszowka** [comment]
@sdwheeler Thank you, I went to do so and in the process of opening the new issue found that You and Chase Wilson actually did merge in a resolution here: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/8084/files. I appreciate this and will close this as resolved.

The section that I found most important:

```
Parameters for the scriptblock can only be passed in from ArgumentList by
position.Switch parameters cannot be passed by position. If you need a parameter
that behaves like a SwitchParameter type, use a Boolean type instead.
```
