### ISSUE TITLE
ubuntu 18.04 installation fails

### ISSUE THREAD

**Issue by simon-eda** [PowerShell/PowerShell#15890]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

i am experiencing an issue with installation of ubuntu 18.04 after succesfull installation of wsl2 and ubuntu20.4 on windows developer. 
the installation fails in microsoft store and powershell using following commands: 

1.
PS C:\WINDOWS\system32> wsl --install -d Ubuntu-18.04
download: Ubuntu 18.04 LTS
install: Ubuntu 18.04 LTS
Ubuntu 18.04 LTS installed.
Ubuntu 18.04 LTS will start... # installation stopps here withour error message
PS C:\WINDOWS\system32>

2.
PS C:\WINDOWS\system32> curl.exe -L -o ubuntu-1804.appx https://aka.ms/wsl-ubuntu-1804       
PS C:\WINDOWS\system32> Add-AppxPackage .\ubuntu-1804.appx
Add-AppxPackage : Fehler bei Bereitstellung. HRESULT: 0x80073CF6, Das Paket konnte nicht registriert werden.
Interner Fehler 0x80070005. Weitere Informationen zum Diagnostizieren von Problemen bei der Bereitstellung von Apps
finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=235160".
HINWEIS: Wenn Sie weitere Informationen wünschen, suchen Sie im Ereignisprotokoll nach [ActivityId]
abea83d0-8c48-0005-59e1-fdab488cd701, oder verwenden Sie die Befehlszeile Get-AppxLog -ActivityID
abea83d0-8c48-0005-59e1-fdab488cd701
In Zeile:1 Zeichen:1
+ Add-AppxPackage .\ubuntu-1804.appx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\WINDOWS\system32\ubuntu-1804.appx:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

when starting powershell i get following error:
. : Die Datei "C:\Users\Simon\Documents\WindowsPowerShell\profile.ps1" kann nicht geladen werden. Die Datei             "C:\Users\Simon\Documents\WindowsPowerShell\profile.ps1" ist nicht digital signiert. Sie können dieses Skript im        aktuellen System nicht ausführen. Weitere Informationen zum Ausführen von Skripts und Festlegen der
Ausführungsrichtlinie erhalten Sie unter "about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170)..
In Zeile:1 Zeichen:3
+ . 'C:\Users\Simon\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

3. microsoft store error  Code: 0x80070005

can you please help to fix the issue?

thanks,
Simon 

### Expected behavior

```console
installing ubuntu 18.04
```

### Actual behavior

```console
installation of ubuntu 18.04 fails
```

### Error details

```console
1.
PS C:\WINDOWS\system32> wsl --install -d Ubuntu-18.04
download: Ubuntu 18.04 LTS
install: Ubuntu 18.04 LTS
Ubuntu 18.04 LTS installed.
Ubuntu 18.04 LTS will start... # installation stopps here withour error message
PS C:\WINDOWS\system32>


2.
PS C:\WINDOWS\system32> curl.exe -L -o ubuntu-1804.appx https://aka.ms/wsl-ubuntu-1804       
PS C:\WINDOWS\system32> Add-AppxPackage .\ubuntu-1804.appx
Add-AppxPackage : Fehler bei Bereitstellung. HRESULT: 0x80073CF6, Das Paket konnte nicht registriert werden.
Interner Fehler 0x80070005. Weitere Informationen zum Diagnostizieren von Problemen bei der Bereitstellung von Apps
finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=235160".
HINWEIS: Wenn Sie weitere Informationen wünschen, suchen Sie im Ereignisprotokoll nach [ActivityId]
abea83d0-8c48-0005-59e1-fdab488cd701, oder verwenden Sie die Befehlszeile Get-AppxLog -ActivityID
abea83d0-8c48-0005-59e1-fdab488cd701
In Zeile:1 Zeichen:1
+ Add-AppxPackage .\ubuntu-1804.appx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\WINDOWS\system32\ubuntu-1804.appx:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand


when starting powershell i get following error:
. : Die Datei "C:\Users\Simon\Documents\WindowsPowerShell\profile.ps1" kann nicht geladen werden. Die Datei             "C:\Users\Simon\Documents\WindowsPowerShell\profile.ps1" ist nicht digital signiert. Sie können dieses Skript im        aktuellen System nicht ausführen. Weitere Informationen zum Ausführen von Skripts und Festlegen der
Ausführungsrichtlinie erhalten Sie unter "about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170)..
In Zeile:1 Zeichen:3
+ . 'C:\Users\Simon\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
3. microsoft store error  Code: 0x80070005

### Environment data

```powershell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.21387.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.21387.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MaximoTrinidad** [comment]
@simon-eda 

Curious!! Have you tried using PowerShell 7.1.3 console? or, reopen the console, and try:

```
## - to verify after installation status:
wsl -l -v

## start distribution from within PowerShell session: 
wsl --distribution ubuntu-18.04

```

Sometimes I use the "wsl --shutdown" to clear any failed condition.

**Comment by simon-eda** [comment]
> @simon-eda
> 
> Curious!! Have you tried using PowerShell 7.1.3 console? or, reopen the console, and try:
> 
> ```
> ## - to verify after installation status:
> wsl -l -v
> 
> ## start distribution from within PowerShell session: 
> wsl --distribution ubuntu-18.04
> ```
> 
> Sometimes I use the "wsl --shutdown" to clear any failed condition.

thanks for the suggestions. same issue in powershell 7

**Comment by simon-eda** [comment]
16.04, 20.4 and docker image can be installed, only 18.04 wont work
