### ISSUE TITLE
Remove workaround for disabling implicit namespace imports

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#15894]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Remove the workaround as the feature will be disabled after .NET preview 7.

The work around add the following to the Powershell.Common.props:

```
<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
<DisableImplicitNamespaceImports_DotNet>true</DisableImplicitNamespaceImports_DotNet>
```

### Expected behavior

```console
Removal of workaround
```

### Actual behavior

```console
Workaround is present
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
@adityapatwardhan is this resolved by above PRs?

**Comment by adityapatwardhan** [comment]
Yes, this can be closed.
