### ISSUE TITLE
`Invoke-WebRequest` is not annotated with `OutputTypeAttribute`

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#15905]
### Steps to reproduce

```powershell
$script = '(Invoke-WebRequest google.com).'
(TabExpansion2 -inputScript $script -cursorColumn $script.Length).CompletionMatches
```

### Expected behavior

```console
CompletionText    ListItemText      ResultType ToolTip
--------------    ------------      ---------- -------
BaseResponse      BaseResponse        Property System.Net.Http.HttpResponseMessage BaseResponse { get; set; }
Content           Content             Property byte[] Content { get; }
Headers           Headers             Property System.Collections.Generic.Dictionary[string,System.Collections.Generic.IEnumerable[string]] Headers { get; }
RawContent        RawContent          Property string RawContent { get; }
RawContentLength  RawContentLength    Property long RawContentLength { get; }
RawContentStream  RawContentStream    Property System.IO.MemoryStream RawContentStream { get; }
RelationLink      RelationLink        Property System.Collections.Generic.Dictionary[string,string] RelationLink { get; }
StatusCode        StatusCode          Property int StatusCode { get; }
StatusDescription StatusDescription   Property string StatusDescription { get; }
Equals(           Equals                Method bool Equals(System.Object obj)
GetHashCode(      GetHashCode           Method int GetHashCode()
GetType(          GetType               Method type GetType()
ToString(         ToString              Method string ToString()
```

### Actual behavior

```console
# Nothing
```

### Error details

N/A

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.7
PSEdition                      Core
GitCommitId                    7.2.0-preview.7
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---

Needs `OutputTypeAttribute` decoration:

```diff
a/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
+++ b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
@@ -13,6 +13,7 @@ namespace Microsoft.PowerShell.Commands
     /// This command makes an HTTP or HTTPS request to a web server and returns the results.
     /// </summary>
     [Cmdlet(VerbsLifecycle.Invoke, "WebRequest", HelpUri = "https://go.microsoft.com/fwlink/?LinkID=2097126", DefaultParameterSetName = "StandardMethod")]
+    [OutputType(typeof(WebResponseObject))]
     public class InvokeWebRequestCommand : WebRequestPSCmdlet
     {
         #region Virtual Method Overrides
```

**Comment by iSazonov** [comment]
Are there other cmdlets we should fix too?

**Comment by SeeminglyScience** [comment]
So I ran a test.  This checks for binary cmdlets that are not decorated with `OutputTypeAttribute` but have a reference to `WriteObject` somewhere in their disassembled source.  This is not a perfect test and will have false negatives and positives.

```powershell
$typesWithNoOutputType = ClassExplorer\Find-Type -InheritsType System.Management.Automation.Cmdlet {
    $_.IsDefined([Management.Automation.CmdletAttribute], $true) -and
    -not $_.IsDefined([OutputType], $true)
}

$needsOutputType = foreach ($type in $typesWithNoOutputType) {
    $disassem = dnSpy.Console.exe --md $type.MetadataToken $type.Assembly.Location |
        Out-String -Width 10000
    if ($disassem.Contains('WriteObject', [StringComparison]::Ordinal)) {
        # yield
        $type
    }
}

$needsOutputType | % { $ExecutionContext.InvokeCommand.GetCmdletByTypeName($PSItem) }
```


That gives the list below.  Note that some of these may have their type inference hard coded into the engine, or they may not be able to meaningfully describe their output via a static type name.  These should probably still be annotated for tools like PSSA that may use `OutputType` to determine *if* a command outputs rather than *what* a command outputs. Also some of these may only output when a flag is passed like `PassThru`, which may also be difficult to annotate currently.

Some however definitely just need an annotation (looking at you `Get-TimeZone`).

<details>

<summary>Command List (click to expand)</summary>

```powershell
Invoke-History
ForEach-Object
Where-Object
Invoke-Command
Receive-Job
Receive-PSSession
Out-Default
Get-Help
Get-Acl
Rename-Computer
Get-ItemPropertyValue
Push-Location
Pop-Location
Resolve-Path
Remove-Service
Get-TimeZone
Set-TimeZone
Add-Member
Compare-Object
ConvertTo-Html
Export-Csv
ConvertFrom-Csv
Out-GridView
Get-Unique
Import-LocalizedData
Import-PowerShellDataFile
New-Object
Select-Object
Show-Command
Sort-Object
Tee-Object
Test-Json
Trace-Command
Update-List
New-Variable
Invoke-RestMethod
ConvertFrom-Json
ConvertTo-Json
Invoke-WebRequest
Write-Output
Enable-WSManCredSSP
Get-WSManCredSSP
Invoke-WSManAction
New-WSManSessionOption
Test-WSMan
Set-WSManQuickConfig
Get-WSManInstance
Set-WSManInstance
New-WSManInstance
```

</details>

**Comment by iSazonov** [comment]
It is nice to have but I'd prefer to implement OutputType per ParameterSet first.

**Comment by SeeminglyScience** [comment]
You can already annotate per `ParameterSet` (`[OutputType(typeof(Something), ParameterSetName = "PassThru")]`), though type inference doesn't actually try to verify it.  It just treats it the same as if you did not specify a parameter set name.

Not all of the ones on that list need anything other than a normal `OutputType` decoration though.

**Comment by iSazonov** [comment]
@SeeminglyScience Could you please add more info? It seems we haven't ParameterSet attribute. Or you say about ParameterAttribute?

**Comment by vexx32** [comment]
The Output type attribute already has a field to specify which parameter set name it applies to. For multiple parameter sets, you just add multiple OutputType attributes, each specifying a different parameter set.

**Comment by iSazonov** [comment]
Ah, thanks! It's even easier than I thought. We have to add this analysis first and then fix the commands.

**Comment by jdhitsolutions** [comment]
Is this being considered a bug or a cmdlet enhancement?

**Comment by SeeminglyScience** [comment]
> Is this being considered a bug or a cmdlet enhancement?

Could be either.  It's technically probably closest to an enhancement but you could also argue that any obviously missing output type decorations is a mistake.

**Comment by iSazonov** [comment]
We forget about _Providers_ - they are annotated with OutputTypeAttribute too.

**Comment by SeeminglyScience** [comment]
> We forget about _Providers_ - they are annotated with OutputTypeAttribute too.

Yeah that's correct, the list wasn't manually vetted and likely has other false negatives and positives.

**Comment by iSazonov** [comment]
I have started to prepare the fix but it turned out to be a little complicated because the attribute allows many-to-many mappings. :-)
