### ISSUE TITLE
Class 177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D missing on Windows 11 ARM64 when using PowerShell x64 or ARM64

### ISSUE THREAD

**Issue by dennisameling** [PowerShell/PowerShell#15916]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Originally reported to the Visual Studio team, which indicated that this is apparently a PowerShell issue: https://developercommunity.visualstudio.com/t/class-177f0c4a-1cd3-4de7-a32c-71dbbb9fa36d-missing/1491726#T-N1499903

(Run on an ARM64 device with Windows 11, e.g. a Surface Pro X)
- Open x64 or ARM64 `pwsh`
- `git clone https://github.com/nodejs/node-gyp`
- `cd node-gyp`
- `pwsh -ExecutionPolicy Unrestricted -Command "Add-Type -Path .\lib\Find-VisualStudio.cs; [VisualStudioConfiguration.Main]::PrintJson()"`

You can also simply copy the contents of https://github.com/nodejs/node-gyp/blob/master/lib/Find-VisualStudio.cs to a file if you don't want to clone the whole repo.

Note that this works as expected on x86 `pwsh` and `powershell` on an ARM64 device (see screencast below) - only x64 and ARM64 are affected.

### Expected behavior

```console
PS C:\repos\node-gyp> pwsh -ExecutionPolicy Unrestricted -Command "Add-Type -Path .\lib\Find-VisualStudio.cs; [VisualStudioConfiguration.Main]::PrintJson()"
[{"path":"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview","version":"17.0.31606.5","packages":["Microsoft.VisualStudio.Product.Community","Microsoft.V.....
```

### Actual behavior

```console
PS C:\repos\node-gyp> pwsh -ExecutionPolicy Unrestricted -Command "Add-Type -Path .\lib\Find-VisualStudio.cs; [VisualStudioConfiguration.Main]::PrintJson()"
MethodInvocationException: Exception calling "PrintJson" with "0" argument(s): "Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Klasse is niet geregistreerd (0x80040154 (REGDB_E_CLASSNOTREG))."
```

### Error details

```console
See above
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

See below a side-by-side of PowerShell x86, x64 and ARM64, respectively, running on an ARM64 Surface Pro X with Windows 11. The script works on x86 PowerShell, but not x64 and ARM64.

https://user-images.githubusercontent.com/17739158/129261076-c1729ff3-1824-4e8d-a260-2b6d87e7aa1a.mp4

**Comment by dennisameling** [comment]
Closing this issue as a Microsoft employee, despite what was being said earlier, confirmed that [this is not a PowerShell but a VS issue](https://developercommunity.visualstudio.com/t/class-177f0c4a-1cd3-4de7-a32c-71dbbb9fa36d-missing/1491726#T-N1499903-N1502782).

**Comment by ZacWalk** [comment]
Small update on this: From VS 17.2 preview 3, support will be added allowing the Microsoft.VisualStudio.Setup.Configuration component to be instantiated in an ARM64 process. 

Indeed this is not a powershell issue rather a problem that an ARM64 compatible version of this component does not currently exist. Unfortunately the Developer Community issue is already closed and I cannot comment there.

**Comment by dennisameling** [comment]
I actually noticed this a few days ago indeed - there's now a `C:\ProgramData\Microsoft\VisualStudio\Setup\arm64ec` folder which registers the ARM64 component. This resolves the issue I reported originally 🎉
