### ISSUE TITLE
New-PSDrive bad credentials, security reports

### ISSUE THREAD

**Issue by clementbey** [PowerShell/PowerShell#15913]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello there,
I think this issue are same than #11045 but I want to add more details with my lab environnement. When I want to mount a SMB drive (not persistent), the first credential sending is the current user who's execute the script.
In my environment, client `Windows Server 2019` and Server `Windows Server 2012 R2` are out of domain **and have different password**.
```Powershell
whoami
awx2019\administrateur
```
Here the code to test :

```Powershell
#Credentials
[string]$userName = 'backup1'
[string]$smbServer = '172.16.19.250'
[SecureString]$securePwd = ConvertTo-SecureString "4c&[rvPh0m[0yGb)" -AsPlainText -Force
[PSCredential]$credObject = New-Object System.Management.Automation.PSCredential -ArgumentList $userName, $securePwd
#Mount PSDrive
New-PSDrive -Name "SaveBackup" -PSProvider "FileSystem" -Root "\\$smbServer\client1" -Credential $credObject
```
Content of `$credObject` :
```powershell
UserName                     Password
--------                     --------
backup1  System.Security.SecureString
```
The current user who's start the script are `Administrateur` on SMB Client. The SMB Server should recive first `backup1` but recives `Administrateur` with all informations of `Administrateur` client (including password !).

Here a screenshot on SMB Server event log (Security) :
![image](https://user-images.githubusercontent.com/88830012/129197096-e713b7af-a28b-423d-a432-363f88b65c3b.png)

After 3 attempts sending `Administrateur`, Powershell try with the correct user `backup1` and can open the SMB Share. 
![image](https://user-images.githubusercontent.com/88830012/129197286-e397058c-f86a-4554-973e-fcb213f02e48.png)

A Wireshark capture confirm than `Administrateur` is sent first :
![image](https://user-images.githubusercontent.com/88830012/129198494-1f87cbb9-7649-483a-9e0b-11e7ea561f69.png)

This issue is a problem for tools intrusion detection. More than 100 of my servers are blocked by security agent for generate a lot of ID 4625 (brute-force detected). Is it a PowerShell problem, SMB problem or Windows Server problem ? ...

Regards,
Clement.

### Expected behavior

```console
Send on first `backup1` (remote service account of SMB Server) user and not the current user who's start the script.
```

### Actual behavior

```console
Sending the current user who's start the script.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

AND

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fMichaleczek** [comment]
I made a small script which use the Win32 API _WNetAddConnection2A_ under the hood.

Can you try it ? 
I put all URL references and use enums, so in case, you want to change some parameters and debug.
The code in PSDrive is located here, if you want to check the default 
https://github.com/PowerShell/PowerShell/blob/b70f06ccc6041281b0f4dc6eaeefdbe5c649636d/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L666

Can you also compare with a _net use_ inside a cmd ? 

If the problem is in the win32 API, that's a Windows bug.

```
Add-Type -TypeDefinition @'

using System;
using System.Runtime.InteropServices;

namespace Utils 
{
    public class Native
    {
        [DllImport("Mpr.dll", EntryPoint = "WNetAddConnection2", CallingConvention = CallingConvention.Winapi)]
        public static extern int WNetAddConnection2(NetResource lpNetResource,
                                                    string lpPassword,
                                                    string lpUsername,
                                                    UInt32 dwFlags);
                                                     
        [DllImport("Mpr.dll", EntryPoint = "WNetCancelConnection2",CallingConvention = CallingConvention.Winapi)]
        public static extern int WNetCancelConnection2(string lpName,
                                                       UInt32 dwFlags,
                                                       Boolean fForce);
    }

    [StructLayout(LayoutKind.Sequential)]
    public class NetResource
    {
        public int dwScope;
        public int dwType;
        public int dwDisplayType;
        public int dwUsage;
        public string lpLocalName;
        public string lpRemoteName;
        public string lpComment;
        public string lpProvider;
    }
    
    public enum ResourceScope
    {
        CONNECTED  = 0x00000001,
        GLOBALNET  = 0x00000002,
        REMEMBERED = 0x00000003
    }

    public enum ResourceType
    {
        ANY,
        DISK,
        PRINT
    };

    public enum ResourceUsage
    {
        CONNECTABLE   = 0x00000001,
        CONTAINER     = 0x00000002
    };

    public enum ResourceDisplayType
    {
        GENERIC,
        DOMAIN,
        SERVER,
        SHARE
    };
    
    public enum Connect
    {
        UPDATE_PROFILE = 0x00000001,
        UPDATE_RECENT  = 0x00000002,
        TEMPORARY      = 0x00000004,
        INTERACTIVE    = 0x00000008,
        PROMPT         = 0x00000010,
        REDIRECT       = 0x00000080,
        CURRENT_MEDIA  = 0x00000200,
        COMMANDLINE    = 0x00000800,
        CMD_SAVECRED   = 0x00001000,
        CRED_RESET     = 0x00002000
    };
    
}

'@

$username  = 'ComputerName\UserName'
$password  = 'Passw@rd'
$driveName = 'R:'
$sharePath = '\\ComputerName\Share'

# see https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetcancelconnection2a
[Utils.Native]::WNetCancelConnection2($driveName, 0, $true) | Out-Null

# see https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/ns-winnetwk-netresourcea
$netResource = [Utils.NetResource]@{
    dwScope       = [Utils.ResourceScope]::GLOBALNET
    dwType        = [Utils.ResourceType]::DISK
    dwDisplayType = [Utils.ResourceDisplayType]::GENERIC
    dwUsage       = [Utils.ResourceUsage]::CONNECTABLE
    lpLocalName   = $driveName
    lpRemoteName  = $sharePath
}

# see https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetaddconnection2a
$result = [Utils.Native]::WNetAddConnection2($netResource, $password, $username, [Utils.Connect]::TEMPORARY)
if ($result -ne 0) {
    Write-Host "Error $result :" ([System.ComponentModel.Win32Exception]::new($result)).Message
}
```

**Comment by clementbey** [comment]
Thanks for your work and answering @fMichaleczek !
When I use `net use` like this:
```Batch
net use U: \\172.16.19.250\client1 /user:backup1 "4c&[rvPh0m[0yGb)" /persistent:No
```
**No ID 4625 are generating**. 1 ID 4776 and 1 ID 4624 are generate. 

When I use your script, with `Windows PowerShell 5.1`, `PWSH 7.1` and `7.2 Preview 8`, 1 ID 4776 and 1 ID 4624. **No ID 4625 are generating**. It works.

I have just one question, when I use `New-PSDrive -Name "SaveBackup" -PSProvider "FileSystem" -Root "\\$smbServer\client1" -Credential $credObject` I am using `-Root` option. It's important for us to haven’t a drive letter. It's possible to do the same with your syntax? I'm not used to this way of doing.

Out of my case, do you think this problem can be fixed (Powershell teams or Windows teams)?

**Comment by fMichaleczek** [comment]
@clementbey I will continue to investigate (need to build a lab to reproduce). But the Win32 API works as expected. The problem seems located  in the PowerShell basecode. I hope to make a workaround function and propose a solution to PowerShell Teams.
/cc @SteveL-MSFT

**Comment by clementbey** [comment]
Hello @fMichaleczek (and happy new year),
Any news or plan about this issue ?

**Comment by EdwardsCP** [comment]
This bug still exists in PS 74.1
```
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by angolo40** [comment]
any news about this?

**Comment by clementbey** [comment]
@angolo40 No... 
Security problem is not priority.

**Comment by angolo40** [comment]
But it should be!
Many cybersecurity tools depend on the Windows Event Log for effective monitoring and analysis.
Let’s hold off for now and wait for further updates.
