### ISSUE TITLE
Execute a file path that contains spaces

### ISSUE THREAD

**Issue by matcha1024** [PowerShell/PowerShell#15929]
### Summary of the new feature / enhancement

in cmd, we can execute a file path that contains spaces.  
For example, `'C:\Program Files\Java\jdk-16.0.2\bin\java.exe' -version`  
but in powershell, can't this.  
To do this you will need to do something like this. `&"C:\Program Files\Java\jdk-16.0.2\bin\java.exe" -version`  
I think that PowerShell should be able to type the same commands as CMD.

### Proposed technical implementation details (optional)

When the file path to be executed is enclosed in quotation marks, `&` is automatically added internally.

**Comment by vexx32** [comment]
This would be a rather large breaking change, and would prevent users from outputting strings that happen to contain paths from a function.

I very much doubt this would ever be an acceptable change.

**Comment by BrucePay** [comment]
Yeah - this would be a really  big breaking change. PowerShell is an expression oriented language. A literal value (string, number or whatever) is simply echoed to the output. If you want to execute an arbitrary value, then you must prefix it with '&' (the call operator). This addresses a variety of scenarios: executing entities having invalid characters in their names,  scripblocks, commandinfos,  and module specific command names.  Remote contexts where considered but never, unfortunately, implemented. Changing the requirement for '&' is unlikely however there may at be things we can do from a  pedagogical perspective that would help (new) users.
