### ISSUE TITLE
Window is slow and flickers 7.1.4

### ISSUE THREAD

**Issue by cartesius82** [PowerShell/PowerShell#15926]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When running the PowerShell 7.1.4 (perhaps also previous version), window flickers on enter, when hitting the Ctrl-L (clear screen) there is a visible lag. I come from the Linux world and Mac OS terminals like Kitty which are >=100 FPS opengl accelerated and this is very ugly.

### Expected behavior

```console
No flicker at all. High fps.
```

### Actual behavior

```console
Flicker on various events, simplest is the clear screen.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fMichaleczek** [comment]
Do you use a console or a terminal ? :)
https://www.hanselman.com/blog/WhatsTheDifferenceBetweenAConsoleATerminalAndAShell.aspx

I advice you to try the Windows Terminal
https://docs.microsoft.com/en-us/windows/terminal/

WebStore App
https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?WT.mc_id=-blog-scottha&rtc=1&activetab=pivot:overviewtab

**Comment by 237dmitry** [comment]
> Expected behavior

Standart host
Windows Terminal Preview 1.10.1933.0
Alacritty 0.9.0

pwsh 7.1.4
