### ISSUE TITLE
Create a feature to execute a file remotely

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#15938]
### Summary of the new feature / enhancement

This would be like invoke-expression, but it would transmit, perssit, and execute the file with parameters. 

It would be good it did caching.

This would allow a signed file to execute in full language mode over remoting.

**Comment by TravisEz13** [comment]
talked about some implementation details with @PaulHigin offline

**Comment by PaulHigin** [comment]
I think this is a very interesting idea.  Also, as an extension we could have an 'import a module file remotely' function as well.

**Comment by jborean93** [comment]
Are you talking about binaries to execute remotely? There's a whole can of worms that this opens up like binary compatibility as well as the availability of shared dll's that may not be present on the remote system. If you are talking about powershell scripts is it something extra that `Invoke-Command -FilePath ...` does not offer?

**Comment by iSazonov** [comment]
I always thought it was blocked by design for security reasons 😕

**Comment by PaulHigin** [comment]
@jborean93 Just PowerShell script files.  Invoke-Command copies the contents of script files as text over remote connection and executes it as a scriptblock.  This would copy the file /w signature (if any) so the contents can be verified before being run.

**Comment by PaulHigin** [comment]
@iSazonov  What is your security concern?

**Comment by jborean93** [comment]
> This would copy the file /w signature (if any) so the contents can be verified before being run.

Is this the only benefit? With code signing being stuck on Windows only (for now) and the fact that you can just run arbitrary scriptblocks anyway with PSRemoting it seems like a trivial thing to bypass anyway.

**Comment by PaulHigin** [comment]
Yes, this would be Windows only for now.  Bypass how?

**Comment by jborean93** [comment]
> Bypass how?

By just running `Invoke-Command -FilePath blah.ps1` of `Invoke-Command -ScriptBlock ([ScriptBlock]::Create((gc blah.ps1 -Raw))`. The remoting API allows you to send the script as a string which is what happens today so what's to stop a nefarious actor from doing what can be done today. JEA could lock things down a bit more but now you are restricted with WinRM and not SSH.

**Comment by PaulHigin** [comment]
Oh yes, the user would not be forced to use it, it is just an option.  But it would be very useful for Windows users remoting into a node that has CI policy enforcement.  The CI policy could validate the file signature and run it as trusted in that environment.

But it could also be useful for non-Windows platforms, as the cache would remove the need to copy the entire file contents each time.  Same with remotely importing a module file remotely.

**Comment by iSazonov** [comment]
> @iSazonov What is your security concern?

This allows regular user with limited remoting permissions to copy a code to remote system. It is not security hole but it is change current practice how we delegate management permissions.
Code signing is not protect us. Thus trojans broadly use Winternal utils to do bad actions (psexec can copy an application to remote host, SDelete cfn wipe).

I have no strong objections from the feature but nervous. :-)

**Comment by PaulHigin** [comment]
Default PowerShell remoting allows users to copy file data, save as file, and execute on remote sessions now in a multitude of ways.  But I agree that we would have to restrict this for remote sessions in NoLanguage mode, similar to Copy-Item.

**Comment by PaulHigin** [comment]
@WG-Remoting
Remoting working group: removing needs triage label, keeping enhancement label.
