### ISSUE TITLE
Who can tell me why this can work on Powershell 5.1 of Windows10 and cannot work with any version of this repo

### ISSUE THREAD

**Issue by inshua** [PowerShell/PowerShell#15942]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Here I find a strange sample, it maybe caused by command line parser or the Parser itself.

### Expected behavior

```console
# start from cmd
cmd /c powershell -C "'powershell ""function f(){2}f'""| out-default"
```

it will output 
```
powershell "function f(){2}f
```

### Actual behavior

```console
# start from cmd
cmd /c pwsh -C "'powershell ""function f(){2}f'""| out-default"


Nothing output, I've checked the error, error id is "TerminatorExpectedAtEndOfString".
```

### Error details

```console
TerminatorExpectedAtEndOfString
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Windows integrated Powershell version:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```


### Visuals

_No response_

**Comment by inshua** [comment]
Solved, it must call CommandLineToArgvW(GetCommandLineW()) to handle arguments instead of SegmentCommandLine like most .net app.

**Comment by mklement0** [comment]
If we take PowerShell as the _caller_ out of the picture and call the following from `cmd.exe`:

```sh
C:\>pwsh -c "'powershell ""function f(){2}f'""| out-default"
# !! No output
```

What an application that uses the C/C++ argument parsing (which includes .NET applications and, I believe, `pwsh.exe`) see as the last argument is the following, _verbatim_ (after stripping syntactic double quotes):

```
'powershell "function f(){2}f'"| out-default
```

This is _not_ a valid PowerShell command line, due to the unbalanced second `"`.

That `pwsh.exe` fails _quietly_ in the face of such a syntactically invalid command is a bug, and it probably has the same underlying cause as #14284.
