### ISSUE TITLE
ANSI rendered file listings lose items when  scrolling in "legacy" console host but not windows terminal

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#15945]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

* Install PowerShell 7.2.Preview8 on windows. 
* Start PowerShell from the recently added programs on the start menu 
* Use  `Enable-ExperimentalFeature PSAnsiRenderingFileInfo`  to turn on on colours for file info; exit and restart PowerShell 7.2 preview
* Run the `dir` command in a directory with a multiple files  directories (I used my PowerShell folder which has a symbolic link, highlighted PowerShell files and an `.exe` it may be some combination of  and my home directory which doesn't have links but does have a zip files) 
* Scroll text off screen and back on with the mouse wheel

### Expected behavior

```console
All text scrolls
```

### Actual behavior

```console
Some text disappears (format-applied and default and occasionally the prompt), see screenshot below, but may return when ps readline formats the next command line.   
If Windows Terminal is installed, Preview is automatically added and appears not to suffer from this, it only applies to the legacy host (which is the one the start menu icon launches)
```

### Error details

```console
No error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/16209593/129879552-f4bc2993-8656-4345-a004-4b232d680f0e.png)

**Comment by SteveL-MSFT** [comment]
This seems to be a side effect of the old Windows console's support of ANSI.  You can open an issue in https://github.com/microsoft/terminal
