### ISSUE TITLE
FileSystemProvider.NameString uses realpath in Linux which resolves all links while Windows just returns the next target

### ISSUE THREAD

**Issue by Jozkee** [PowerShell/PowerShell#15958]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create 2 links and 1 file:
```bash
touch foo
ln -s bar foo
ln -s baz bar
```

so you have baz -> bar -> foo

I used the following Cmdlet to exemplify the error:
```cs
using System.Management.Automation;  // Windows PowerShell assembly.
using Microsoft.PowerShell.Commands;

namespace SendGreeting
{
  [Cmdlet(VerbsCommunications.Send, "Greeting")]
  public class SendGreetingCommand : Cmdlet
  {
    protected override void ProcessRecord()
    {
      WriteObject("Hello " + name + "!!");
      string fileName = FileSystemProvider.NameString(new PSObject(new System.IO.FileInfo("/home/user/baz")));
      WriteObject(fileName);
    }
  }
}
```
```pwsh
Import-Module /home/user/Cmdlet/bin/Debug/net5.0/Cmdlet.dll
Send-Greeting
```

### Expected behavior

```console
baz -> bar
```

### Actual behavior

```console
baz -> foo
```

### Error details
This differs with Windows and also seems to differ when realpath fails since it fallsback to readlink:
https://github.com/PowerShell/PowerShell-Native/blob/deb01d6f65b07a0861933a2986cce2318fd60492/src/libpsl-native/src/followsymlink.cpp#L39-L54

### Environment data

```powershell
PS /home/jozky/pscore> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The ` FileSystemProvider.NameString()` is used in Formatting subsystem primary in `dir` scenario where users investigate full path chain step-by-step. So it is a bug (and a minor breaking change).

**Comment by JamesWTruher** [comment]
WG discussed this and agree that the behavior is a little surprising - as far as we can tell there aren't any other *nix tools (like ls, readlink, stat) that behave this way. It's unknown if PowerShell has internal code that rely on the current behavior. This _is_ a breaking change as the API results will definitely be different, so anyone relying on previous results may be affected.
