### ISSUE TITLE
SSH compatibility in alias

### ISSUE THREAD

**Issue by danielnainggolan** [PowerShell/PowerShell#15954]
### Summary of the new feature / enhancement

like alias in Linux that allows the user to set ssh function to the alias, it will be convenient for the user if this is added to alias compatibility in Powershell

**Comment by rkeithhill** [comment]
@danielnainggolan Can you provide a specific example of what you're looking for?  I suspect this is a dupe of #12962. 

For SSH in particular, you can create a `config` file in your .ssh dir with entries like:
```
Host server1
    User wileycoyote
    Hostname server1.acme.com

Host server2
    User wileycoyote
    Hostname server2.acme.com    
```
Then you can use `ssh server1` and `ssh server2`.

**Comment by danielnainggolan** [comment]
ahh yes, just realize this is a duplicate, basically what I need is to be able to do this in PowerShell 
```bash
>> alias tunnelserver='ssh -i some_key user@server.acme.com'
>> tunnelserver 
```

**Comment by rkeithhill** [comment]
Also you can do this with a function defined in your profile script:
```powershell
function tunnelserver() { ssh -i some_key user@server.acme.com }
```

**Comment by danielnainggolan** [comment]
awesome, thanks @rkeithhill
