### ISSUE TITLE
Disable/postpone another process from restarting the computer while the script is running.

### ISSUE THREAD

**Issue by chrisbachmann** [PowerShell/PowerShell#15952]
### Summary of the new feature / enhancement

We are working on a script that installs the Ubuntu distro for WSL. While the appx is downloading, another intune process is restarting the computer, therefore interrupting the download and the install doesn't happen. What we'd like to do is to be able to tell windows "I need you to not reboot while I'm running. Wait until I'm done."

### Proposed technical implementation details (optional)

I don't know the windows internals, but calling it with a command like 'Postpone-Restart' would be sufficent.

**Comment by vexx32** [comment]
I'm not even sure Windows itself has a functionality to provide this, short of the process refusing to close when asked... had a bit of a search around, but didn't find anything promising. 😕 

Not sure if there's a way to deliberately trigger that behaviour. 🤔

**Comment by jborean93** [comment]
> I'm not even sure Windows itself has a functionality to provide this

I'm fairly confident there is not. You can abort a shutdown request that is in place with `shutdown.exe /a`. So theorectically you could have a loop that continues to run that (or at least the Win32 API equivalent) but this won't catch things that are shutting the host down immediately with no time to wait.

**Comment by thezim** [comment]
For Windows I believe there are some registry keys you can set but I believe this only guarded against Windows updates.
