### ISSUE TITLE
Start-Job -Name "InstalledProgramsFile" doesn't output to file

### ISSUE THREAD

**Issue by PeterKW** [PowerShell/PowerShell#15970]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`
  Start-Job -Name "InstalledProgramsFile" -scriptblock {
    "MS Uninstallable" >> $InstalledProgramsFile
    "" >> $InstalledProgramsFile
    Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table –AutoSize > $InstalledProgramsFile
    "" >> $InstalledProgramsFile
    
    #Remove-Job -Name InstalledProgramsFile
  }`

If I remove the Start-Job block then the code runs fine and outputs to the file but it blocks up my terminal. I would like to be able to run this code to add lists to a file in the background but when I use the Start-Job code even after it has completed state at 'Get-Job -Name InstalledProgramsFile' the file at the file path variable has not been affected at all.

Is there any way to get it working outputing a list to a file in the background? At the moment I have to comment out the Job part of the code which then blocks up use in PowerShell.

### Expected behavior

```console
Id     Name            PSJobTypeName   State         HasMoreData     Location
--     ----            -------------   -----         -----------     --------
1      InstalledProgr… BackgroundJob   Running       True            localhost

Loading personal and system profiles took 1360ms.
PS P:\Documents> Get-Job -Name InstalledProgramsFile

Id     Name            PSJobTypeName   State         HasMoreData     Location
--     ----            -------------   -----         -----------     --------
1      InstalledProgr… BackgroundJob   Completed     False           localhost

PS P:\Documents> File at  $InstalledProgramsFile exists and is uptodate
```

### Actual behavior

```console
Id     Name            PSJobTypeName   State         HasMoreData     Location
--     ----            -------------   -----         -----------     --------
1      InstalledProgr… BackgroundJob   Running       True            localhost

Loading personal and system profiles took 1360ms.
PS P:\Documents> Get-Job -Name InstalledProgramsFile

Id     Name            PSJobTypeName   State         HasMoreData     Location
--     ----            -------------   -----         -----------     --------
1      InstalledProgr… BackgroundJob   Completed     False           localhost

PS P:\Documents> File at  $InstalledProgramsFile Does Not Exist like it is containered and not effecting device
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Background jobs run in a completely separate environment, so local variables and functions are not available to them directly. YOu aren't defining `$InstalledProgramsFile` in the job itself, so those `>> $installedProgramsFile` expressions are the same as `>> $null` which just discards the data.

**Comment by PeterKW** [comment]
Thank you very much. That makes a lot of sense. I've re-added in defining the variables that seems to have worked.

Is there any way to remove the job when it has finished? 
`Remove-Job -Name InstalledProgramsFile`

**Comment by PeterKW** [comment]
> Thank you very much. That makes a lot of sense. I've re-added in defining the variables that seems to have worked.
> 
> Is there any way to remove the job automatically in the code when it has finished?
> `Remove-Job -Name InstalledProgramsFile`

Got it all working now :D 

`
  Register-ObjectEvent -InputObject $job -EventName StateChanged -Action {
    Unregister-Event $EventSubscriber.SourceIdentifier
    Remove-Job $EventSubscriber.SourceIdentifier
    Remove-Job -Id $EventSubscriber.SourceObject.Id
} | Out-Null`

Thank you very much!
