### ISSUE TITLE
`PS*` properties overshadow properties of the same name in registry

### ISSUE THREAD

**Issue by catthehacker** [PowerShell/PowerShell#15971]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
New-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE -Name PSPath -PropertyType String -Value C:\
Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE -Name PSPath | select-object -ExpandProperty PSPath
```

### Expected behavior

```console
C:\
```

### Actual behavior

```console
Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\SOFTWARE
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.21390
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
🤔 I'd imagine the same happens for added PS* properties in other providers too. Not sure if there's a workaround for this kind of case.

**Comment by catthehacker** [comment]
It will definitely happen everywhere where `PS*` properties are mixed with raw kv maps.

**Comment by jborean93** [comment]
You can use the provider to open the key but then use .NET to get the property/name as well to simplify things

```powershell
(Get-Item HKCU:\SOFTWARE).GetValue('PSPath')
```
