### ISSUE TITLE
Function and System.Collections.ArrayList must Out-null

### ISSUE THREAD

**Issue by ThierryRassat** [PowerShell/PowerShell#15977]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello Powershell Teams,

I have a bug when I use System.Collections.ArrayList in a function. I must use out-null when I add a element to list

I write this function

function simplefunction
{
    $collection = New-Object System.Collections.ArrayList
    $collection.add("Toto")
    return $collection
}
-> the result about simplefunction is
0
Toto

I must use out-null 

function simplefunction
{
    $collection = New-Object System.Collections.ArrayList
    $collection.add("Toto")|out-null
    return $collection
}

-> the result is now OK when I use this function
Toto

Kind Regards
Thierry

### Expected behavior

```console
Toto
```

### Actual behavior

```console
0
Toto
```

### Error details

```console
I must used out-null after add function in System.Collections.ArrayList object
```

### Environment data

```powershell
Microsoft Powershell 7.1.3
```

**Comment by Jammrock** [comment]
The output is part of the .NET behavior. PowerShell just echoes the return from the Add method.

https://github.com/microsoft/referencesource/blob/master/mscorlib/system/collections/arraylist.cs

```c#
        // Adds the given object to the end of this list. The size of the list is
        // increased by one. If required, the capacity of the list is doubled
        // before adding the new element.
        //
        public virtual int Add(Object value) {
            Contract.Ensures(Contract.Result<int>() >= 0);
            if (_size == _items.Length) EnsureCapacity(_size + 1);
            _items[_size] = value;
            _version++;
            return _size++;   // <----- This is where the element number in PowerShell comes from.
        }
```

The more efficient method of blocking the output is to use "$null =". It doesn't impact the Add(), prevents console output, and is faster than pipelining to Out-Null.

```PowerShell
function simplefunction
{
   $collection = New-Object System.Collections.ArrayList
   $null = $collection.add("Toto")
   return $collection
}
```

**Comment by jborean93** [comment]
You can also use a generic list which has a void Add method

```powershell
$list = [System.Collections.Generic.List[Object]]::new()
$list.Add("foo")
```

The other benefit of a generic list is that you can explicitly set the type of the entries. The example above is set to allow `Object` which is essentially anything but say you wanted a list of strings then do `[System.Collections.Generic.List[String]]::new()`.

**Comment by ThierryRassat** [comment]
Thank you for yours messages. I do that
