### ISSUE TITLE
Update CLI 

### ISSUE THREAD

**Issue by PeterKW** [PowerShell/PowerShell#15989]
### Summary of the new feature / enhancement

Is there a way of updating to the next version of powershell when the user gets alerted by using cli? Either winget or choco package managers or something else?

"

 ```
A new PowerShell preview release is available: v7.2.0-preview.9
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.2.0-preview.9

```
"

**Comment by adityapatwardhan** [comment]
Yes, PowerShell is available on winget. Here are the instructions: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-7.1#install-powershell-via-the-windows-package-manager
