### ISSUE TITLE
RunspaceInvoke  is missing in Version7.4.1

### ISSUE THREAD

**Issue by henry-us** [PowerShell/PowerShell#15984]
### Summary of the new feature / enhancement

I have found some alternatives in the [discussion](https://github.com/PowerShell/PowerShell/issues/13004).
But, If I want to output an error message, which method should I use, I don't seem to have found an alternative in PowerShell.

`out IList errors`

```
public Collection Invoke(string script, IEnumerable input, out IList errors)
{
        if (_disposed == true)
        {
            throw PSTraceSource.NewObjectDisposedException("runspace");
        }
        if (script == null)
        {
            throw PSTraceSource.NewArgumentNullException("script");
        }

        Pipeline p = _runspace.CreatePipeline(script);
        Collection<PSObject> output = p.Invoke(input);
        // 2004/06/30-JonN was ReadAll() which was non-blocking
        errors = p.Error.NonBlockingRead();
        return output;
}
```

**Comment by rjmholt** [comment]
How about:

```powershell
using (var pwsh = PowerShell.Create())
{
    pwsh.AddScript("Write-Error 'Bad'").Invoke();

    PSDataCollection<ErrorRecord> errors = pwsh.Streams.Error;
}
```

**Comment by henry-us** [comment]
I'm not very familiar with the methods in Powershell.Is it possible to transmit error information to an object?
Just like:
```
using (var pwsh = PowerShell.Create())
{
    pwsh.AddScript("Write-Error 'Bad'").Invoke();

    PSDataCollection<ErrorRecord> errors = pwsh.Streams.Error;
    test=pwsh.AddScript("Write-Error 'Bad'").Invoke().xx(errors);
}
```

**Comment by henry-us** [comment]
> How about:
> 
> ```csharp
> using (var pwsh = PowerShell.Create())
> {
>     pwsh.AddScript("Write-Error 'Bad'").Invoke();
> 
>     PSDataCollection<ErrorRecord> errors = pwsh.Streams.Error;
> }
> ```

Thank you for your help. I'm not very familiar with the methods in Powershell.Is it possible to transmit error information to an object?
Just like:
```
using (var pwsh = PowerShell.Create())
{
    pwsh.AddScript("Write-Error 'Bad'").Invoke();

    PSDataCollection<ErrorRecord> errors = pwsh.Streams.Error;
    test=pwsh.AddScript("Write-Error 'Bad'").Invoke().xx(errors);
}
```

**Comment by jborean93** [comment]
Invoke will return the output stream, you need to access `Streams.Error` after you run the invoke to get the error stream (and other streams).

**Comment by henry-us** [comment]
> Invoke will return the output stream, you need to access `Streams.Error` after you run the invoke to get the error stream (and other streams). See https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.invoke?view=powershellsdk-7.0.0#System_Management_Automation_PowerShell_Invoke for details on `Invoke()` and https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.streams?view=powershellsdk-7.0.0 for details of the `Streams` property.

Okay thanks Jordan, l've solved it now.
