### ISSUE TITLE
Write-Error With Try Block Called from Simple Function

### ISSUE THREAD

**Issue by Stroniax** [PowerShell/PowerShell#15996]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using a simple function to call an advanced function with `-ErrorAction Stop` does not properly execute a `catch` block within the advanced function if Write-Error is invoked within a try block, even though it will if you call that same function from the command line or within an advanced function.

Repro:
```
function foo {
    [CmdletBinding()]
    param()
    process {
        try { Write-Error 'Foo error' }
        # Calling Write-Output from catch will stop the catch block when foo is called with -ea stop; must use Write-Host
        catch { Write-Host 'Foo catch' }
        finally { Write-Host 'Foo finally' }
    }
}
function bar { foo -ea stop }
function baz {
    [cmdletbinding()]
    param()
    process{
        foo -ea stop
    }
}
```

### Expected behavior

```console
PS> foo -ea stop
Foo catch
Foo finally
PS> bar
Foo catch
Foo finally
PS> baz
Foo catch
Foo finally
```

### Actual behavior

```console
PS> foo -ea stop
Foo catch
Foo finally
PS> bar
Foo finally
PS> baz
Foo catch
Foo finally
```

### Environment data

```powershell
# Also tested in 7.2.0-preview.9 and 5.1.0
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Both test cases seem to catch the error for me, at least in 7.2.0-preview9 on MacOS. My test:

```ps1
function error {
    [CmdletBinding()]
    param()
    process {
        try { write-error 'error' }
        catch { write-host 'caught' }
        finally { write-host 'finally' }
    }
}

function simple { error -ea stop }

function advanced {
    [CmdletBinding()]
    param()
    process { error -ea stop }
}

Write-Host "simple:"
simple

Write-Host "advanced:"
advanced

Write-Host "direct:"
error -ea stop
```

My results:

```
simple:
caught
finally
advanced:
caught
finally
direct:
caught
finally
```

I'd also expect to see normal red error text if the error wasn't being caught, which doesn't seem to be what you're seeing -- it seems to still be caught, but the write-host in the catch block doesn't seem to run when it's called from the simple function from what your output shows?

**Comment by Stroniax** [comment]
I swear I tested this in three separate PowerShell processes but now that I've copied that code over it's working like I'd expect now. I'll... reopen this if I can figure out why it hadn't been working, I guess?
