### ISSUE TITLE
Background-job operator is quietly ignored in remote sessions on Unix

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16004]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:

* Enter an interactive remote session targeting a macOS or Linux machine with `Enter-PSSession`

* Try to use the post-positional ` &` operator to start a background job:

```powershell
Get-Date &
```

### Expected behavior

A job should be created and information about it should print to the display.

### Actual behavior

The command is executed synchronously, as if ` &` hadn't been specified at all.

Note that the normally equivalent command, `Start-Job { Get-Date }` works as expected.

### Environment data

```powershell
PowerShell Core 7.2.0-preview.9 on macOS and Linux.
```

**Comment by PaulHigin** [comment]
WG-Remoting
I see this behavior with any interactive session, regardless of platform.  It may have something to do with the '&' character when forming the remote command.  Note that this does work:

```powershell
[computer1]: PS C:\> (Get-Date &)

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
7      Job7            BackgroundJob   Running       True            localhost            Microsoft.PowerShell.Man…
```
