### ISSUE TITLE
7.2.0-preview9: & arguments no longer remove quotes

### ISSUE THREAD

**Issue by nohwnd** [PowerShell/PowerShell#16017]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Have a program that just prints out it's args: 
```cs
using System;
using System.Linq;

namespace ConsoleApp29
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Arguments:");
            args.ToList().ForEach(arg => Console.WriteLine(arg));
        }
    }
}
```

Invoke the program with `&` and pass some params.

### Expected behavior

```console
& ".\ConsoleApp29.exe" @("a", '"a"')

Arguments:
a
a
```

### Actual behavior

```console
& ".\ConsoleApp29.exe" @("a", '"a"')

Arguments:
a
"a"
```

### Error details

```console
The "" are no longer stripped from the argument in 7.2.0-preview9, while in 7.1.3 they are stripped.
```

### Environment data

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Haplois** [comment]
We also see this in our repository, when executing this line: 

https://github.com/microsoft/testfx/blob/a5fc7c9c91d5de10fe3824d86872d31f847a682d/scripts/Build.ps1#L225

**Comment by SeeminglyScience** [comment]
This is due to the experimental feature `PSNativeCommandArgumentParsing`.  As a workaround, you can disable the feature or control it with this variable:

```powershell
$oldMode = $PSNativeCommandArgumentPassing
try {
    $PSNativeCommandArgumentPassing = 'Legacy'
    InvokeExeHere
} finally {
    $PSNativeCommandArgumentPassing = $oldMode 
}
```

**Comment by nohwnd** [comment]
Thanks Patrick.

Or probably just rely on variable scoping to reset it for us:

```powershell
& { 
    $PSNativeCommandArgumentPassing = 'Legacy'
    InvokeExeHere
}
```

**Comment by Haplois** [comment]
Thanks @nohwnd, @SeeminglyScience.

**Comment by jborean93** [comment]
Just as an FYI this should be the desired behaviour as it is escaping the values correctly. It will allow you to do `my.exe '{"foo": "bar"}'` without you having to manually escape the double quotes yourself.
