### ISSUE TITLE
AD Cmdlets add properties to AD Objects when accessing non-existent properties

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#16018]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am using PowerShell 7.x on a Win 11 box. I am using the Active Directory cmdlets to manage an AD and have observed a very weird behaviour (tested on 7.1.4 and 7.2.preview9. If I use ``Get-ADUser`` to return an AD user, I can store the returned object in a variable and use the variables properties (as you would expect). However, if I type a property name wrong (you all know how lousy my typing is), I discover that PowerShell creates a property of the same name. LIke this:

```powershell-console
PS C:\Foo> $PSVersionTable.PSVersion.tostring()
7.2.0-preview.9
PS C:\Foo> $User = Get-ADUser -Identity JerryG
PS C:\Foo> $User.Name
Jerry Garcia
S C:\Foo> $User | Get-Member n*

   TypeName: Microsoft.ActiveDirectory.Management.ADUser

Name                                MemberType Definition
----                                ---------- ----------
Name                                Property   System.String Name {get;}

PS C:\Foo> $User.nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAme      # now for the fun
PS C:\Foo> $User | Get-Member n*

   TypeName: Microsoft.ActiveDirectory.Management.ADUser

Name                                MemberType Definition
----                                ---------- ----------
nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAme Property   Microsoft.ActiveDirectory.Management.ADPropertyValueCollection nAAAAAAA…
Name                                Property   System.String Name {get;}
```

Should PowerShell be adding properties to an object when the property did not previously exist? Or is this some arcane behaviour on the part of the AD objects? 

I am baffled!

### Expected behavior

```console
PS C:\Foo> $User.nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAme      # now for the fun
PS C:\Foo> $User | Get-Member n*

   TypeName: Microsoft.ActiveDirectory.Management.ADUser

Name                                MemberType Definition
----                                ---------- ----------
Name                                Property   System.String Name {get;}
```

### Actual behavior

```console
See above - accessing any non-existant property name results in a new property of that name being added to the object.
```

### Environment data

```powershell
PS C:\Foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.0-preview…
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
The underlying type appears to be some form of dictionary/collection.  
```
PS> $adUser.psobject.typenames
Microsoft.ActiveDirectory.Management.ADUser
Microsoft.ActiveDirectory.Management.ADAccount
Microsoft.ActiveDirectory.Management.ADPrincipal
Microsoft.ActiveDirectory.Management.ADObject
Microsoft.ActiveDirectory.Management.ADEntity
Microsoft.ActiveDirectory.Management.ADPropertyCollection  <<===
System.Object
```
I suppose it is not too surprising that PS allows you to modify that collection.  Whatever properties you add, show up in the `ModifiedProperties` property and `GetEnumerator()` output.

**Comment by vexx32** [comment]
The AD objects are odd, at best. Whatever behaviour this is, it's something defined by the AD module itself.

**Comment by iSazonov** [comment]
What behavior is in Windows PowerShell?

**Comment by doctordns** [comment]
> What behavior is in Windows PowerShell?

While the output is slightly different, it does the same thing. :-( 

Thus, I suspect this is a 'feature' of the module - but I've never seen this behaviour on any object before. I'm curious as to how accessing a non-existent property causes the property to be created and populated?

**Comment by iSazonov** [comment]
I guess the cmdlet read limited set of properties and if user want change a property which is not in the list the module would have to do a request of AD schema that is a performance lost. So they postpone the check until change request is sent to server.
