### ISSUE TITLE
.NET Core: Opening a Runspace fails

### ISSUE THREAD

**Issue by derSchweiger** [PowerShell/PowerShell#16022]
Currently it's not possible to fire up a runspace instance in .NET Core. As soon as the .Open() method is called, the program gets stuck and errors after some time.

### Steps to reproduce

Corresponding code:
```
Runspace rs;
var pspi = new PowerShellProcessInstance();
pspi.Process.StartInfo.FileName = @"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe";
pspi.Process.Start();
rs = RunspaceFactory.CreateOutOfProcessRunspace(new TypeTable(new string[0]), pspi);
rs.Open();

using (PowerShell powershell = PowerShell.Create()) {
    powershell.Runspace = rs;
    powershell.AddScript(<some code>);
    var output = powershell.Invoke();
}
```

### Expected behavior
Open the runspace instance like in .NET Framework.

### Actual behavior

The following Error occurs. 

```
System.Management.Automation.Remoting.PSRemotingTransportException HResult=0x80131501 
Nachricht = The background process reported an error with the following message: D 
Quelle = System.Management.Automation
```

### Environment data

- .NET Core 5.0 Console Application
- Packages: Microsoft.PowerShell.SDK & System.Management.Automation (up-to-date)
- Windows 10 Pro

**Comment by vexx32** [comment]
Is it expected that pwsh's `OpenOutOfProcessRunspace` should work with Windows PowerShell rather than pwsh @PaulHigin ?

**Comment by derSchweiger** [comment]
Initializing the runspace with the `.CreateRunspace()` method instead of `.CreateOutOfProcessRunspace()` works but than it's not possible to use the cmdlet "Add-PSSnapin" anymore. I've to preload multiple powershell runspaces with the Exchange Management Shell Snapin. So this is kind of an unfortunate situation.

**Comment by vexx32** [comment]
Yeah, Add-PSSnapin has been deprecated for years now. There are [newer Exchange modules](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps) available that don't use snap-ins available, though I don't know whether it works for what you're looking for specifically.

**Comment by derSchweiger** [comment]
This module only supports Exchange Online and no On-Premise infrastructure - therefore, unfortunately, this doesn't fit into our needs. Since the "Add-PSSnapin" doesn't work with the newer Powershell SDKs, I've tried to open a "standalone" Powershell process with the `.CreateOutOfProcessRunspace()` method and import the Snapin afterwards.
However, if this method isn't supported either, I think that there is no chance to load the Exchange PSSnapin in a persistant runspace?

**Comment by vexx32** [comment]
There is definitely a way to do it, though I'm not super familiar with how it works. From a scan through the code used for `Import-Module -UseWindowsPowerShell` it looks like `New-PSSession` is used to create a session with Windows PowerShell, and then that session is used to send commands into it.

See:

https://github.com/PowerShell/PowerShell/blob/e2ee8e7e1fa3854fb22dc1c494c01351f19ddff6/src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs#L1912-L1915

https://github.com/PowerShell/PowerShell/blob/e2ee8e7e1fa3854fb22dc1c494c01351f19ddff6/src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs#L2018-L2091

https://github.com/PowerShell/PowerShell/blob/e2ee8e7e1fa3854fb22dc1c494c01351f19ddff6/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L4827-L4850

**Comment by PaulHigin** [comment]
@derSchweiger Yes, WindowsPowerShell is supported with PowerShellProcessInsance, but you are not using it correctly.  You should not use the default constructor but one of the parameterized constructors that sets up the internal state.  PowerShell has to be started in 'server mode' in the new process instance.  Yours does not run in server mode and so cannot communicate over the remote channel, and you see the hang.  Also you should provide the default type table to ensure common types are re-hydrated over the connection.

```powershell
PS C:\> $typeTable = [System.Management.Automation.Runspaces.TypeTable]::LoadDefaultTypeFiles()

PS C:\> [System.Management.Automation.Runspaces.PowerShellProcessInstance]::new

OverloadDefinitions
-------------------
System.Management.Automation.Runspaces.PowerShellProcessInstance new(version **powerShellVersion**, pscredential
credential, scriptblock initializationScript, bool useWow64, string workingDirectory)
System.Management.Automation.Runspaces.PowerShellProcessInstance new(version **powerShellVersion**, pscredential
credential, scriptblock initializationScript, bool useWow64)
```

For example:
```powershell
PS C:\> $typeTable = [System.Management.Automation.Runspaces.TypeTable]::LoadDefaultTypeFiles()
PS C:\> $pi = [System.Management.Automation.Runspaces.PowerShellProcessInstance]::new("5.1", $null, $null, $false)
PS C:\> $rs = [runspacefactory]::CreateOutOfProcessRunspace($typeTable, $pi)
PS C:\> $rs.Open()
PS C:\> $ps = [powershell]::Create($rs)
PS C:\> $ps.AddScript('$psversionTable').Invoke()

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
CLRVersion                     4.0.30319.42000
PSVersion                      5.1.19041.1151
BuildVersion                   10.0.19041.1151
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSEdition                      Desktop
```

**Comment by derSchweiger** [comment]
@vexx32 connecting with a new PSSession should work, but that's my least favorized method because I would have to handle Exchange requests differently than usual requests. I'll use it, if there is no other option to import the Exchange Management Shell Snapin. I aim at deploying a single method to query all Powershell requests - regardless if it's for Exchange or any other cmdlet.

@PaulHigin it seems like that this did the trick. I will test it and provide you with feedback afterwards.

Thanks to both of you!

**Comment by derSchweiger** [comment]
Everything works as it should. Thank you very much, I appreciate it!
