### ISSUE TITLE
Output formatting for [System.Reflection.Assembly] instances should show relevant information, not properties only relevant in Windows PowerShell

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16020]
### Summary of the new feature / enhancement

The default output formatting for `[System.Reflection.Assembly]` instances shows information that only applies to _Windows PowerShell_ (.NET Framework):

```powershell
PS>  [object].Assembly

GAC    Version        Location
---    -------        --------
False  v4.0.30319     /Users/mklement/.powershell-PREVIEW/System.Private.CoreLib.dll
```
* .NET Core / 5+ has no GAC, so this information is irrelevant.

* The `Version` property value is seemingly a fixed default value; it is unrelated to the assembly's actual version number.

Therefore:

* the `GAC` display column should be removed
* the `Version` display column should report the actual assembly version number.
* other meaningful display columns could be added.

Note that changing _output formatting_ is _not_ considered a breaking change - for-display formatting details aren't considered part of the backward-compatibility contract.

---

Written as of PowerShell Core 7.2.0-preview.9.

**Comment by rkeithhill** [comment]
I see what you're saying but this doesn't seem like a particularly high priority issue.  How about we put this "up for grabs"?

**Comment by iSazonov** [comment]
We could output the version:
```powershell
[object].Assembly.GetName()

Version        Name
-------        ----
6.0.0.0        System.Private.CoreLib
```

**Comment by rjmholt** [comment]
The Engine Working Group discussed this and agree we should change the formatted output.

The suggested properties to display are the file path and the properties from the assembly name, name, version, culture and public key.

**Comment by iSazonov** [comment]
@rjmholt What is right WG-* label for the isuue?
