### ISSUE TITLE
Multi-choise SP column with New-MgSiteListItem 

### ISSUE THREAD

**Issue by apospa** [PowerShell/PowerShell#16031]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`New-MgSiteListItem -ListId $ListId -SiteId $SiteId -Fields @{
        "Title" = $user.DisplayName ; 
        "UPN" = $user.UserPrincipalName ; 
        "TestChoise" = @("A", "B")  
        
    
    }`

### Expected behavior

```console
should create record with choises A and B in choise column.
```

### Actual behavior

```console
problem with multiple choise column. PnP works well but i need to use MG now.

When i change column to single value it works great bud after switch to multiple value it goes to error.
```

### Error details

```console
New-MgSiteListItem : Invalid request
At line:1 char:1

New-MgSiteListItem -ListId $ListId -SiteId $SiteId -Fields @{
  + CategoryInfo          : InvalidOperation: ({ SiteId = f812...GraphListItem }:<>f__AnonymousType4`3) [New-MgSiteListItem_CreateExpanded], RestExc  
 eption`1
  + FullyQualifiedErrorId : invalidRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgSiteListItem_CreateExpanded
```

### Environment data

```powershell
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by vexx32** [comment]
This module isn't in this repository, nor is PowerShell v5.1. Please follow up with the module author for third-party modules 🙂

**Comment by apospa** [comment]
ok sorry. :-)
