### ISSUE TITLE
$? of redirection >, >>, 2>, and 2>> is unexpected.

### ISSUE THREAD

**Issue by XValue** [PowerShell/PowerShell#16033]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$? of redirection >, >>, 2>, and 2>> is unexpected.

### Expected behavior

```console
PS> "hello"
hello
PS> "abc" > $null
PS> $?
True
PS>
PS>
PS> 2 + "a"
InvalidArgument: Cannot convert value "a" to type "System.Int32". Error: "Input string was not in a correct format."
PS> "abc" > $null
PS> $?
True
```

### Actual behavior

```console
PS> "hello"
hello
PS> "abc" > $null
PS> $?
True
PS>
PS>
PS> 2 + "a"
InvalidArgument: Cannot convert value "a" to type "System.Int32". Error: "Input string was not in a correct format."
PS> "abc" > $null
PS> $?
False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Bug](https://user-images.githubusercontent.com/89930529/131734016-759fef73-0e87-4da8-a577-a8dc491e4605.png)

**Comment by vexx32** [comment]
I'm seeing the same on the latest preview. I wonder if this is because it's considered a 'pure' expression and thus doesn't set `$?`? was it an intentional change in this instance?

**Comment by XValue** [comment]
I don't think it's considered a 'pure' expression.
PS> "hello"
hello
PS> "abc" > C:\1.txt
Out-File: Access to the path 'C:\1.txt' is denied.
PS> $?
False

**Comment by XValue** [comment]
![Bug2](https://user-images.githubusercontent.com/89930529/131979585-4e824fa4-b0cc-49f9-a379-6ae6820af152.png)

**Comment by daxian-dbw** [comment]
The Engine WG reviewed this issue and agreed this is a bug that should be fixed. Hopefully #16046 will fix it.
