### ISSUE TITLE
`[AllowEmptyString()]` for `-Description` in `Set-LocalGroup`/`Set-LocalUser`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#16049]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

See: StackOverflow question: [How to set the description of a local group to blank](https://stackoverflow.com/q/69041644/1701026)

The `Set-LocalGroup`/`SetLocalUser` cmdlet do not allow empty strings for the `-Description` parameter (which is set to `[ValidateNotNull()]`):

```PowerShell
New-LocalGroup -Name 'Group1' -Description 'My description'

Name   Description
----   -----------
Group1 My description

Set-LocalGroup -Name 'Group1' -Description ''
```

### Expected behavior

Description set to a zero length string:

```PowerShell
Get-LocalGroup -Name 'Group1'

Name   Description
----   -----------
Group1
```

### Actual behavior

> `Set-LocalGroup: Cannot bind argument to parameter 'Description' because it is an empty string.`

```PowerShell
Consequently it is not possible to clear the description with the concerned cmdlets.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The module is not in the repository. Please report the issue with Windows Feedback tool.

**Comment by iRon7** [comment]
> The module is not in the repository. Please report the issue with Windows Feedback tool.

@iSazonov , I am somewhat confused here:
If I:
* go to the [`Set-LocalGroup`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/set-localgroup?view=powershell-5.1) documentation web page
<sup>(https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/set-localgroup?view=powershell-5.1)</sup>
* In the bottom, under:
**Feedback**
_Submit and view feedback for_
* Click: [**`[This Product]`**](https://github.com/PowerShell/PowerShell/issues/new/choose)
I end up in this [**PowerShell/PowerShell** repository](https://github.com/PowerShell/PowerShell/issues/new/choose)...

Afaik, the related commands are here:
[`PowerShell/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/`](https://github.com/PowerShell/PowerShell/tree/c531098f3be5c6f5e671a162e6c49751474609f6/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands)

What do you mean with the **Windows Feedback tool**?

**Comment by iSazonov** [comment]
The module is not compiled in the repository because of compliance issues. So it is only Windows PowerShell module.



> What do you mean with the **Windows Feedback tool**?

On Windows press Start button and type Feedback

**Comment by iRon7** [comment]
I feel a little 😳 that I wasn't aware of the **Windows Feedback tool**.
Anyways I have opened a case in there at referred to this issue.

**Comment by iSazonov** [comment]
Fixed in community module https://www.powershellgallery.com/packages/LocalAccounts
