### ISSUE TITLE
powershell found by windows-start-menu-search, if run as adminstrator, causes UAC to be minimized

### ISSUE THREAD

**Issue by hgkamath** [PowerShell/PowerShell#16053]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. - login as unprivileged non-adminstrator user (or administrative user, does not matter, for administrative user UAC only warns without needing authentication )
2. - press windows start-key/click on windows start button
2. - start typing "power..."' or "pw..." . This switches the start menu to the type-to-search, which shortlists the powershell programs available in the startmenu/windows-system
3. - For each search-result found, the right-half-pane of the start menu, shows additional actions. Clicking on ">" sign of other "powershell versions" changes the right-half-pane to their additional actions.
4. - After choosing whichever powershell application, click on "Run as Administrator" action that shows up in the right-half-pane.
5. - UAC starts minimized (background), blinking orange on taskbar. IMHO the UAC should have foregrounded. This should happen only when background processes or not-in-focus applications request elevation. However, in this case the user is actively/intentfully starting an application.

Windows-10 ver 21H1, OS build 19043.1202
version of "windows powershell" : 5.1.19041.1202
version of "pwsh/powershell" 7.1.3 installed via chocolatey to C:\Program Files\PowerShell\7 (choco install powershell-core)
UAC level setting for ordinary user on highest 
UAC level setting for admin user is on second highest. 

Normally for most other apps, like cmd, cleanmgr, compmgmt, diskmgmt, the UAC dims screen and shows up in the foreground. One only needs to press Escape, or click-OK/press-spacebar to dismiss the UAC
The issue is, that for the above given procedure, one is forced to additionally click on orange blinking minimized UAC in taskbar to dismiss it.

Behavior/issue happens 
* ~~for "windows powershell", "windows powershell (x86)" and "Powershell 7 (x64)/pwsh"~~ [see comment](https://github.com/PowerShell/PowerShell/issues/16053#issuecomment-913086154)
* when logged in as a ordinary non-administrative user or as user with administrative privileges

Behavior/Issue does not happen for the following cases
* ~~Does not happen for "powershell 7 preview (x64)" and "Windows Powershell ISE"~~ [see comment](https://github.com/PowerShell/PowerShell/issues/16053#issuecomment-913086154)
* when "powershell" or "Windows powershell" is scrolled to in the start menu, right click, "run as administrator"
* when "windows powershell (Admin)" is started from right click of windows start button
* when "Open file location" is used to show shortcut locations in explorer, and run by "right click - run as administrator" .
* when "powershell exe" locations are located in windows-explorer and run by "right click - run as administrator"
In the above cases, UAC is foregrounded as expected.

It is somewhat disconcerting to move mouse to click on taskbar to maximize UAC just for powershell.

The question boils down to why does powershell elevated start behave differently when started it is started using windows-type-to-search.

### Expected behavior

```console
UAC should come in the foreground, dim rest of screen.
Should not start as orange blinking minimized UAC in taskbar .
One only needs to press Escape, or click-OK/press-spacebar to dismiss the UAC
```

### Actual behavior

```console
Starts as orange blinking minimized UAC in taskbar. One is forced to additionally click on orange blinking minimized UAC in taskbar to dismiss it.
```

### Error details

```console
NA
```

### Environment data

```powershell
PS C:\Users\admin> # pwsh / Powershell 7 (x64)
PS C:\Users\admin> echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\WINDOWS\system32> # windows powershell
PS C:\WINDOWS\system32> echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1202
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1202
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1



PS C:\Users\admin> # powershell 7 preview (x64)
PS C:\Users\admin> echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Visuals

[see comment](https://github.com/PowerShell/PowerShell/issues/16053#issuecomment-913086154)

### Ref
[] "...The UAC elevation mechanism uses the HWND as part of determining whether the elevation is a background or foreground elevation..." https://answers.microsoft.com/en-us/windows/forum/all/how-do-you-maximize-user-account-controluac-window/b5c96c91-08a6-4c8c-8c7a-571ed5ea74b4  , also https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/07cf27b0-ac60-4469-a440-34c0b1a4a73f/uac-elevation-dialog-minimized?forum=windowssecurity

**Comment by vexx32** [comment]
This sounds more like a Windows issue than a powershell issue to me. 😕

**Comment by hgkamath** [comment]
I felt so too, but powershell is so tightly coupled to windows, that windows-type-to-search might be treating powershell differently, or powershell reacting differently to being started by windows-type-to-search. 
I also confirmed that same happens on my other widows device (SP3), but I do appinstall/setup/configure things similarly on both devices. So I wonder if this reproducible on any window machine.

**Comment by vexx32** [comment]
The fact it's still happening for PowerShell 7, which is entirely separate from Windows, would indicate to me that whatever the issue is, it's something in Windows. Doubly so because it seems to be pretty situational, from your description. I've not seen anything similar myself, though I don't know if that's just because I tend to use Windows Terminal rather than launching pwsh directly.

**Comment by hgkamath** [comment]
okay, I noticed something. 

![image](https://user-images.githubusercontent.com/3323558/132115457-b34619c0-2d7a-4957-a0dd-7630bea9de78.png)

In the right-side actions list, for every powershell version, there seems to be two "run as administrator" actions
1) one with colored icon
2) one with windows-standard outline icon
The first is the one that causes UAC to goto background
The second brings the UAC normally. 

The colored icon "run as administrator" shows up before pressing the "⌄" sign in the right hand pane which shows additional actions. In the image above the "⌄" has already been pressed and has turned into a "⌃" which is to hide the additional actions.

I think the colored icon "run as administrator" is populated as a form of quick shortcut.

If this is correct, the workaround is to just avoid the attention grabbing colored icon "run as administrator"

So in the original issue description, issue is not selective by powershell version. It happens for every powershell version including the 'windows powershell ISE', as long as the colored icon "run as administrator"  is clicked. Strangely, for the 'Windows powershell ISE' the colored icon "run as administrator" does not appear in its won action list is appended to but that of "Window powershell"

Other applications when run as administrator, do not make this extra colored icon "run as administrator"

I hope I am not jumping to hasty conclusion an not have to retract this.

**Comment by hgkamath** [comment]
I uninstalled powershell-core-7.2.0-preview8 and pwsh-7.1.3 and installed powershell-core-7.1.4 ```choco install powershell-core```. As of a fresh install, those accelerated colored-icon actions do not exist. They still exist for the windows bundled "windows powershell-5" and "windows powershell-ISE". 
I'll update here in case I notice something.

**Comment by StevenBucher98** [comment]
Is this still an issue @hgkamath? From reading I do suspect it might be a Windows issue but am curious if recent updates have fixed this.

**Comment by hgkamath** [comment]
As of 7.2.4, it still is. 

I have powershell-core 7.2.4 upgraded via chocolatey.  I have been upgrade through the minor version upgrades using it. 
Both it and the standard-powershell 5.1.19041.1682, have the double standard-outline-icon and the colored-in-icon shortcuts. 
WIn10 has also been getting its monthly patch Tuesday cumulatives and is now at 21H2 19044.1706 

I've sort of learned to ignore the colored-icon and become habituated to pressing the outline-icon.

Perhaps, a question to ask, is how those shortcuts got created. The answer to that might also explain why they look and behave differently .

**Comment by hello-smile6** [comment]
Can reproduce this without installing any other copies of PowerShell than the default.
![Screenshot of search UI](https://user-images.githubusercontent.com/73048226/169948634-545c9658-f607-447c-ad74-80f211b399e9.png)

**Comment by hgkamath** [comment]
I uninstalled powershell-core-7.2.4 from the settings/apps&features. (did not reboot, relogin)

Same behavior happens with shortcuts of win10 standard-powershell-5.1, even without installing 7.2.4

**Comment by hello-smile6** [comment]
> I uninstalled powershell-core-7.2.4 from the settings/apps&features. (did not reboot, nor relogin). Also did a `choco-uninstall powershell-core` for any cleanups.
> 
> Same behavior happens with shortcuts of win10 standard-powershell-5.1, even without installing 7.2.4
> 
> Can you confirm to me that the same behavior is seen by you?
> 
> I reinstalled 7.2.4 `choco install powershell-core`. Upon this fresh-install, this time, for powershell-7.2.4, the outline-icon-shortcut is not present in the menu. The colored-in-icon-shortcut is bringing the UAC dialog to the foreground as expected. I am not optimistic that this will prevail for long, at some point that outline-icon-shortcut will get generated/populated in the menu and the troublesome behavior may re-appear. So, maybe, I think it happens when both shortcuts are present.

I can't test it, unfortunately.
