### ISSUE TITLE
Set-CASMailbox is not working inside ScriptBlock using RunspacePools

### ISSUE THREAD

**Issue by chandragm** [PowerShell/PowerShell#16050]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

To be frank I am a newbie to Powershell. 

I am currently working on a project where-in I am trying to use ExchangeOnlineManagement PS module to manage Exchange email access for an organisation.

Example:
I am trying to control the mailbox policies per user using Set-CASMailbox cmdlet

`Set-CASMailbox -Identity $Identity -ActiveSyncAllowedDeviceIDs @{Add=$DeviceIds} -ActiveSyncBlockedDeviceIDs @{Remove=$DeviceIds}`

The above works just fine normally. But then we decided to run it in parallel to speed up the process by making use of RunspacePools as it has been taking way too much of a time for any number of users more than 100.

```
$Job = [powershell]::Create().AddScript($ScriptBlock).AddArgument($DeviceIds).AddArgument($Identity)
$Job.RunspacePool = $RunspacePool
```

Somehow the command is not working inside the ScriptBlock:

The core piece of the ScriptBlock is:
```
$ScriptBlock = {
    Param (
    [string[]]$DeviceIds,
    [string]$Identity
    )

    Set-CASMailbox -Identity $Identity -ActiveSyncAllowedDeviceIDs @{Remove=$DeviceIds} -ActiveSyncBlockedDeviceIDs @{Add=$DeviceIds}
}
```

I could get this to work by calling again
`Connect-ExchangeOnline -Credential $psCred -CommandName Set-CASMailbox`
inside the ScriptBlock. But that would be too much of an overhead and kinda defeats the purpose of speeding it up.

Tried:
1.
`Import-PSSession -Session $Session –AllowClobber -CommandName Set-CASMailbox`
This is hanging with CPU usage peaking at 100% on the server machine.

2. Tried to import modules into initialsessionstate and passing it to RunspacePool 

None of the above worked.

Interesting fact:
The exported commands like 
`Get-EXOMobileDeviceStatistics`
are working inside the ScriptBlock without doing any extra work so the Runspace is indeed getting the connected PSSession context.

Do let me know if you have any ideas on how to make Set-CASMailbox work inside the ScriptBlock.

### Expected behavior

```console
$ScriptBlock = {
    Param (
    [string[]]$DeviceIds,
    [string]$Identity
    )

    Set-CASMailbox -Identity $Identity -ActiveSyncAllowedDeviceIDs @{Remove=$DeviceIds} -ActiveSyncBlockedDeviceIDs @{Add=$DeviceIds}
}

Should modify the whitelist/blacklist accordingly
```

### Actual behavior

```console
Not working
```

### Environment data

```powershell
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Do you use Exchange Online V2 PowerShell module? Only version >= 2.0.4 support PowerShell 7.

**Comment by chandragm** [comment]
@iSazonov Yes.
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.0.5                 ExchangeOnlineManagement            Desk      {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPermission, Get-EXOMailboxFolderStatistics…}
Manifest   2.2.1                 PSWSMan                             Core      {Disable-WSManCertVerification, Enable-WSManCertVerification, Get-WSManVersion, Install-WSMan…}

**Comment by chandragm** [comment]
> Do you use Exchange Online V2 PowerShell module? Only version >= 2.0.4 support PowerShell 7.

@iSazonov Yes

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.0.5                 ExchangeOnlineManagement            Desk      {Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPermission, Get-EXOMailboxFolderStatistics…}

**Comment by iSazonov** [comment]
Did you try `ForEach-Object -Parallel`?

**Comment by chandragm** [comment]
> Did you try `ForEach-Object -Parallel`?

Yes. 

also tried
`Start-ThreadJob`

**Comment by chandragm** [comment]
Any ways to tackle this would be of great help.
