### ISSUE TITLE
Remote server PS version detection logic appears to be wrong, misidentify PowerShell 4+ as 5+

### ISSUE THREAD

**Issue by jantari** [PowerShell/PowerShell#16058]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When trying to research a different question ("Does Windows PowerShell 5.1 depend on WSMAN for OutOfProcess Runspaces?" - and no, I haven't been able to find an answer) I read some remoting-related source code in this repository, and noticed the following:

https://github.com/PowerShell/PowerShell/blob/17986d88c10eb6271b1aad2ca955889e45e2b285/src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs#L1905-L1909

This appears to assume that when we get a RunspaceConnectionInfo of Type NewProcessConnectionInfo we must be in PowerShell 5.x or newer, and in order to test this I created jobs on a Windows Server 2012 R2 instance with no upgraded WMF so still running PowerShell 4.0 but I got a ConnectionInfo of type `NewProcessConnectionInfo` there too.

To be clear I have no idea what the impact of this possibly wrong version detection could be.
It looks to me like this would identify PowerShell 4.0+ as PowerShell5 .0+

I have made a screenshot from my 2012 R2 server below that shows I get a NewProcessConnectionInfo object from a Job:

### Expected behavior

```console
# Not applicable
```

### Actual behavior

```console
# Not applicable
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

### Visuals

![image](https://user-images.githubusercontent.com/25607767/132255306-dce06c15-65be-4bb4-add9-688075bc0714.png)

**Comment by jborean93** [comment]
>  ("Does Windows PowerShell 5.1 depend on WSMAN for OutOfProcess Runspaces?" - and no, I haven't been able to find an answer) 

Depends, for things like jobs no it does't. It uses the new powershell process' stdio handles to send and receive data. Only `-ComputerName ...` PSRemoting stuff relies on WSMan.

> To be clear I have no idea what the impact of this possibly wrong version detection could be.
It looks to me like this would identify PowerShell 4.0+ as PowerShell5 .0+

The only place where `GetRemoteServerPsVersion` is used is in `CreatePipeline` https://github.com/PowerShell/PowerShell/blob/17986d88c10eb6271b1aad2ca955889e45e2b285/src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs#L1875-L1884 where it is used to swap between a pwsh v2 and v3+ type of pipeline to handle things like `$using:` statements. If the detection was wrong then doing something like this might potentially fail

```powershell
$var = 'foo'
Start-Job { $using:var } | Wait-Job | Receive-Job
```

But when testing it does still work.

![image](https://user-images.githubusercontent.com/8462645/132258250-3780b614-aba9-4697-865c-9cc0548b2da2.png)

At a guess the code for Windows PowerShell 4 is built before v5 was a thing so this current bit of code in PowerShell is not present there, why would it ever know about future versions. Where this might be a problem is if you are running PowerShell 6+ on a host with just Windows PowerShell 4 and state you want to run the job on the Windows PowerShell instance which I don't even know if it's possible. The `NewProcessConnectionInfo` is not even public so it's not like there's 3rd party code out there legitimately using it.

**Comment by jantari** [comment]
> The NewProcessConnectionInfo is not even public so it's not like there's 3rd party code out there legitimately using it.

There is [an issue](https://github.com/PowerShell/PowerShell/issues/13435) for that and it also contains a legitimate usecase.

> Depends, for things like jobs no it does't. It uses the new powershell process' stdio handles to send and receive data. Only -ComputerName ... PSRemoting stuff relies on WSMan.

Thanks for the input. It is quite an important differentiation because WSMAN is not supported in WinPE according to comments in this codebase, and the docs site for [`NamedPipeConnectionInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.namedpipeconnectioninfo) makes it a point to state explicitly that it doesn't have a dependency on WSMan - but since `NewProcessConnectionInfo` is still private, there's no docs for it ...

I also tested `[System.Management.Automation.Runspaces.RunspaceFactory]::CreateOutOfProcessRunspace($null)` (which is a public API that uses the undocumented `NewProcessConnectionInfo`) inside WinPE and it worked, so I guess that's a good indicator.

**Comment by jborean93** [comment]
Yep the only thing that uses WSMan is [WSManConnectionInfo](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.runspaces.wsmanconnectioninfo?view=powershellsdk-7.0.0). It's a sealed class as well so nothing will be inherited that and any other `*ConnectionInfo` classes will use their own transport, the common one being the OutOfProc transports that work over some sort of read/write IO interface.

**Comment by PaulHigin** [comment]
WG-Remoting:

The above repro steps runs in WindowsPowerShell version 4, and so is not running any PowerShellCore code and the PowerShellCore code snippet shown above does not apply.

PowerShellCore only starts child processes for version 5.1 (if available) or the current running PowerShellCore version, so the code snippet is actually correct.  A child process can be started via `Start-Job` cmdlet or `CreateOutOfProcessRunspace` API.

`Start-Job` takes a `PSVersion` parameter, but only checks it for a value of `5.1`, and otherwise ignores it, starting a session version the same as the currently running version.  So again, the code snippet is actually correct, a new process will always run a version of `5.1` or the current parent version.

However, I did notice that the error message is incorrect if you try to start a job with PowerShell version 2.0.  So I am creating a new [Issue](https://github.com/PowerShell/PowerShell/issues/16062) for that.

I am closing this Issue since there appears to be no bug.  But please re-open if I am missing something.
