### ISSUE TITLE
Checksum fails for servicefabric_sdkcommon_1.4.2.deb

### ISSUE THREAD

**Issue by aukesj** [PowerShell/PowerShell#16051]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm using Foreman/Katello to synchronize Microsoft packages within my organization. When syncing the repo for Ubuntu Bionic, I get this error:

`A file located at the url https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/s/servicefabricsdkcommon/servicefabric_sdkcommon_1.4.2.deb failed validation due to checksum.`

Could you please check this repository for us?

Thanks in advance!

### Expected behavior

```console
A clean sync
```

### Actual behavior

```console
A failed sync due to checksum errors
```

### Error details

```console
`A file located at the url https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/s/servicefabricsdkcommon/servicefabric_sdkcommon_1.4.2.deb failed validation due to checksum.`
```

### Environment data

```powershell
Not applicable
```

**Comment by adityapatwardhan** [comment]
We do not own the package servicefabric_sdkcommon_1.4.2.deb. Resolving as external
