### ISSUE TITLE
Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by securewebsite** [PowerShell/PowerShell#16052]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I ma using MacOS Big Sur on Intel Platform. I have tried latest version of Powershell using 

brew cask install powershell.

I am able to start powersehll with pwsh command after that I Install module using Install-Module MSOnline and Imported module with Import-Module MSOnline after that whenever I tried to run the command Connect-MsolService. I get following error message

Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

I have install .net SDK 5 to see if that solved the problem but it did not. Following is the $PSVersionTable command

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Expected behavior

```console
Connect-MsolService command should work
```

### Actual behavior

```console
Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

### Error details

```console
Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

Connect-MsolService: Could not load file or assembly 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

### Environment data

```powershell
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Connect-MsolService Command should work.

**Comment by iSazonov** [comment]
MSOnline  is too old and does not supported on PowerShell 7.

**Comment by joshuaherr** [comment]
I don't see any resolution on this issue. So the resolution is Connect-MsolService doesn't work on Linux/MacOS? Can you clarify that? Is there a workaround? I'm not very satisfied with the current "resolution".

**Comment by yatishmadhav** [comment]
Hi there... I am experiencing the same. Please advise if anyone here has found resolution to this? Thank you

**Comment by WillFulmer** [comment]
Correct. This does not work on MacOS PowerShell. This requires a Windows OS with the Sign-In Assistant Module loaded.

**Comment by Drew-Alleman** [comment]
Is there any way to connect to the MSOL service on a linux ubuntu server?
