### ISSUE TITLE
Loading assemblies doesn't work in Terminal until I press Tab on the class name

### ISSUE THREAD

**Issue by ariel-co** [PowerShell/PowerShell#16054]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

At least for System.Windows.Media.GlyphTypeface, just loading PF with Add-Type isn't enough. I keep getting “Unable to find type” until I type all or part of the class without the closing bracket and try to autocomplete (I'm using PSReadLine).

It also fails with a test .ps1 file, and even if I rename Documents/PowerShell so it doesn't interefere.
[addtype-bug.ps1.txt](https://github.com/PowerShell/PowerShell/files/7110473/addtype-bug.ps1.txt)

### Expected behavior

```console
> [System.Windows.Media.GlyphTypeface]
InvalidOperation: Unable to find type [System.Windows.Media.GlyphTypeface].
> Add-Type -AssemblyName PresentationFramework
> [System.Windows.Media.GlyphTypeface]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    GlyphTypeface                            System.Object
```
```


### Actual behavior

> [System.Windows.Media.GlyphTypeface]
InvalidOperation: Unable to find type [System.Windows.Media.GlyphTypeface].
> Add-Type -AssemblyName PresentationFramework
> [System.Windows.Media.GlyphTypeface]
InvalidOperation: Unable to find type [System.Windows.Media.GlyphTypeface].
> [System.Windows.Media.GlyphTypeface]
InvalidOperation: Unable to find type [System.Windows.Media.GlyphTypeface].
> [System.Windows.Media.GlyphTypeface«TAB»]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    GlyphTypeface                            System.Object
```

### Error details

```console
> Get-Error

Type        : System.Management.Automation.RuntimeException
ErrorRecord :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : Unable to find type [System.Windows.Media.GlyphTypeface].
        HResult : -2146233087
    TargetObject          : System.Windows.Media.GlyphTypeface
    CategoryInfo          : InvalidOperation: (System.Windows.Media.GlyphTypeface:TypeName) [],
ParentContainsErrorRecordException
    FullyQualifiedErrorId : TypeNotFound
    InvocationInfo        :
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : -1
        Line             : [System.Windows.Media.GlyphTypeface]
        PositionMessage  : At line:1 char:1
                           + [System.Windows.Media.GlyphTypeface]
                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CommandOrigin    : Internal
    ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
TargetSite  :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation,
Version=7.2.0.9, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message     : Unable to find type [System.Windows.Media.GlyphTypeface].
Data        : System.Collections.ListDictionaryInternal
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input) in
System.Management.Automation.dll:token 0x600537f+0xb0
   at System.Management.Automation.Runspaces.Pipeline.Invoke() in System.Management.Automation.dll:token 0x600535d+0x0
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown,
ExecutionOptions options) in Microsoft.PowerShell.ConsoleHost.dll:token 0x600023c+0x153
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fMichaleczek** [comment]
The type _System.Windows.Media.GlyphTypeface_ is located into the assembly _PresentationCore_

```
Add-Type -AssemblyName PresentationCore
[System.Windows.Media.GlyphTypeface]
```

But the assembly _PresentationFramework_ has a referency to assembly _PresentationCore_, so it should work as expected.
As a workaround, if you use the _passthru_ parameter, it loads all the referencies assemblies.

```
Add-Type -AssemblyName PresentationFramework -PassThru | Out-Null
[System.Windows.Media.GlyphTypeface]
```

**Comment by fMichaleczek** [comment]
The Cmdlet _Add-Type_ doesn't load the referenced assemblies until the method _GetTypes_ is executed on the assembly object. 
 
This raw dotnet code demonstrates it : 
```
> [System.Reflection.Assembly]::LoadFrom("$PSHome\PresentationFramework.dll") | Out-Null
> [System.Windows.Media.GlyphTypeface] 

InvalidOperation: Unable to find type [System.Windows.Media.GlyphTypeface]


> [System.Reflection.Assembly]::LoadFrom("$PSHome\PresentationFramework.dll").GetTypes() | Out-Null
> [System.Windows.Media.GlyphTypeface] 

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    GlyphTypeface                            System.Object
```


On Windows PowerShell, it works 
```
> [System.Reflection.Assembly]::LoadWithPartialName("PresentationFramework") | Out-Null
> [System.Windows.Media.GlyphTypeface]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    GlyphTypeface                            System.Object
```

That's happening when the switch parameter _PassThru_ is used
https://github.com/PowerShell/PowerShell/blob/883ca98dd74ea13b3d8c0dd62d301963a40483d6/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L895-L898

or when the completion occurs interactively.
https://github.com/PowerShell/PowerShell/blob/17986d88c10eb6271b1aad2ca955889e45e2b285/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L6357-L6376



**3 possibles solutions :** 

1. Add assembly.GetTypes() to force the loading of dependencies https://github.com/PowerShell/PowerShell/blob/883ca98dd74ea13b3d8c0dd62d301963a40483d6/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L671-L676
2. Add a new switch parameter like "ImportDependencies"
3. Add a workaround in documentation :  use PassThru to force the loading of the referenced assemblies 

/cc @rjmholt @vexx32

**Comment by ariel-co** [comment]
> The type System.Windows.Media.GlyphTypeface is located into the assembly PresentationCore

Thanks Flavien, somehow I mixed up the two assemblies. For now loading the correct one directly serves me.

I did notice that autocompletion in general makes PS load additional assemblies (per *CurrentDomain.GetAssemblies()*).

**Comment by iSazonov** [comment]
Since it is standard assembly in distribution it make sense to preprocess it in TypeGen.

**Comment by fMichaleczek** [comment]
@iSazonov I agree with you for this particular type, but I don't think it will not solve the problem at the root. 

I downloaded a random nuget package without the dependencies. 
You can compare the difference in behavior between Windows PowerShell and PowerShell: there is a regression for referenced assemblies.

I understand there is a lot of technical changes around AppDomain, GAC, ALC, etc .. but at end, the behaviour is different. 

**Windows PowerShell**
```
> add-type -Path C:\temp\system.interactive.async.5.0.0\lib\netstandard2.0\System.Interactive.Async.dll
add-type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

> $error[0].Exception.LoaderExceptions
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
...
```

**PowerShell** 
```
> add-type -Path C:\Temp\system.interactive.async.5.0.0\lib\netstandard2.0\System.Interactive.Async.dll
> add-type -Path C:\Temp\system.interactive.async.5.0.0\lib\netstandard2.0\System.Interactive.Async.dll -PassThru
Add-Type: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
...
```

**Comment by iSazonov** [comment]
We could simply document `-PassThrou` as workaround since it is .Net Core behavior.

**Comment by vexx32** [comment]
I don't think it's unreasonable for folks to expect Add-Type to do what it says on the tin and actually import the types into the session. 🤔

**Comment by SeeminglyScience** [comment]
Note that loading referenced assemblies could break some scenarios. If an assembly is referenced, but you never call a code path that triggers that assembly to load, you don't technically have to ship that assembly.

I've seen modules rely on this behavior (even though it can sort of break tab completion of type names).

> I don't think it's unreasonable for folks to expect Add-Type to do what it says on the tin and actually import the types into the session. 🤔

I mean it kinda did though. PresentationFramework would maybe be worth an exception since it's really more like a group of assemblies.  But if I try to load `System.Collections.Immutable.dll` I wouldn't expect to be able to use `System.Runtime.CompilerServices.Unsafe` just because it happens to depend on it.

**Comment by vexx32** [comment]
The Engine WG discussed this issue in today's meeting.

This is by design, and while the disparity between how assemblies are handled when doing tab-completion vs simply looking up the type is unfortunate, it's not particularly feasible to fix it. The behaviour stems from .NET itself; it doesn't load _everything_ an assembly might need by default, instead deferring the loading until the types are actually required.

Due to how tab completion has to work, its enumeration of the types on the assembly ends up triggering the loading behaviour, but we don't think it's a good idea to mimic that behaviour for all type lookups as it can be quite expensive. Equally, because the behaviour stems from .NET, tab completion isn't in any way "aware" that it's triggering assembly loads, and while it might be useful to provide some kind of warning to users that they may want to load additional assemblies in a script context, it's not feasible to do so.
