### ISSUE TITLE
Windows PowerShell doesn't take environment variable changes when opened with Tasks -> Run as Administrator

### ISSUE THREAD

**Issue by jiasli** [PowerShell/PowerShell#16057]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On Azure Windows Server 2019 VM.

Make any change to the environment variable (either User or System):

![image](https://user-images.githubusercontent.com/4003950/132166058-ae3cda73-51e1-41ab-a811-4507a61d12a0.png)

![image](https://user-images.githubusercontent.com/4003950/132166192-f59632ce-985c-4929-b1c5-d07a67e6e421.png)

Launch Windows PowerShell using **Tasks -> Run as Administrator**:

![image](https://user-images.githubusercontent.com/4003950/132165966-db750c0a-6d50-4beb-aaa6-3bd6cf3b6284.png)

The environment variable change doesn't work:

![image](https://user-images.githubusercontent.com/4003950/132166361-646f3148-cb89-45ab-bc86-1076fc8e158e.png)

However, if PowerShell is launched with **More -> Run as administrator**

![image](https://user-images.githubusercontent.com/4003950/132166000-126d8549-4177-4f41-9a69-8c331931789f.png)

the environment variable works:

![image](https://user-images.githubusercontent.com/4003950/132166479-97ea8539-9e29-4089-9195-60f707d3c4c1.png)

It also works if Windows PowerShell is opened by directly clicking on the icon.

### Expected behavior

```console
Changes to environment variable should be reflected in PowerShell terminal.
```

### Actual behavior

```console
Changes to environment variable are not reflected in PowerShell terminal.
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.2090
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2090
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jiasli** [comment]
Same issue also happens on latest PowerShell 7:

![image](https://user-images.githubusercontent.com/4003950/132167246-0fce238f-7239-4043-9fcc-22c82db091bb.png)

- The upper one is started with Tasks -> Run as Administrator
- The lower one is started with More -> Run as administrator

![image](https://user-images.githubusercontent.com/4003950/132167313-ef0473c2-a3f2-48b0-ac26-0ba70ba19206.png)

**Comment by jiasli** [comment]
No issue is observed on local Windows 10.

**Comment by jborean93** [comment]
I don’t think this is a PowerShell problem but how explorer starts the process. PowerShell will just inherit whatever env vars are provided when it was started and in this case it’s explorer/UAC that’s starting it.

**Comment by daxian-dbw** [comment]
Also, Windows PowerShell specific issues should be reported with the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332), by choosing "Apps > PowerShell" in category.

**Comment by jiasli** [comment]
This also happens to PowerShell Core (https://github.com/PowerShell/PowerShell/issues/16057#issuecomment-913363431).

**Comment by daxian-dbw** [comment]
@jiasli Thanks for the clarification.
I think @jborean93's https://github.com/PowerShell/PowerShell/issues/16057#issuecomment-913543354 above is the right explanation of the observed behavior.

One more thing you can try out to validate is to start `cmd.exe` instead of `PowerShell` using **Tasks -> Run as Administrator**, and then run `echo %TESTNAME%` and see if that prints out `TESTVALUE`. If it just prints out `%TESTNAME%`, then it means the environment variable is not visible to `cmd.exe`.

**Comment by iSazonov** [comment]
The RunAs behavior is unexpected and should be reported as **Windows bug**.
