### ISSUE TITLE
[7.2 Preview 9] Add-Member to a string and converting to JSON produces a different result than 7.1

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#16069]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`'test' | add-member 'newmember' 'test' -passthru | convertto-json`

### Expected behavior

```console
{
  "value": "test",
  "newmember": "test"
}
```

### Actual behavior

```console
"test"
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
See https://github.com/PowerShell/PowerShell/pull/15665 as a deliberate breaking change.
