### ISSUE TITLE
Specialized collections do not bind correctly to array-typed parameters of binary cmdlets

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16061]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:

* `Select-String` is used as an example, but I presume the problem is fundamental to how arguments are bound in _binary_ cmdlets - _script_ cmdlets (advanced functions) do _not_ exhibit the problem.

* The example uses an ordered hashtable whose `.Keys` collection is of type `System.Collections.Specialized.OrderedDictionary+OrderedDictionaryKeyValueCollection`, which implements `ICollection` and `IEnumerable`; _unordered_ hashtables (`System.Collections.Hashtable+KeyCollection`, same interfaces) are equally affected - I don't know what the general pattern is, however.

```powershell
$ht = [ordered] @{
  'two' = 1
  'one' = 1
}

'-- use of @(...) (or cast to string[]): OK'
'one', 'two' | Select-String -Quiet -Pattern @($ht.Keys)
# !! BROKEN
'-- no cast'
'one', 'two' | Select-String -Quiet -Pattern $ht.Keys
'-- no cast with input matching the stringified key collection as a single-element array'
'two one' | Select-String -Quiet -Pattern $ht.Keys
```

What seems to be happening is that, instead of creating an array of values from the elements of the collection, the collection _as a whole_ is stringified (elements joined with spaces) and the result becomes a _single-element_ array.

### Expected behavior

```console
-- use of @(...) (or cast to string[]): OK
True
-- no cast
True
-- no cast with input matching the stringified key collection as a single-element array
True
```

### Actual behavior

```console
-- use of @(...) (or cast to string[]): OK
True
-- no cast
-- no cast with input matching the stringified key collection as a single-element array
True
```

### Environment data

```powershell
PowerShell Core 7.2.0-preview.9
```

**Comment by IISResetMe** [comment]
> I don't know what the general pattern is, however.

The patterns here is that the parameter binder only ever attempts an unchecked conversion to `IList` before deciding whether the parameter argument is to be coerced or wrapped as a single-element array. Since the key collections don't implement `IList`, the parameter binder treats it as a scalar and wraps it instead of attempting any actual conversion.

Default parameter binding behavior could be updated to allow coercion of a less specific interface (eg. `ICollection`) instead of `IList`, but I suspect it will require some significant work.

**Comment by Knele83** [comment]
https://github.com/PowerShell/PowerShell/issues/16061#issuecomment-932956381

**Comment by Knele83** [comment]
https://github.com/PowerShell/PowerShell/issues/16061#issuecomment-932956381
