### ISSUE TITLE
Get-Content fails with paths that contain brackets

### ISSUE THREAD

**Issue by AArnott** [PowerShell/PowerShell#16063]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a directory that contains a file whose name is literally `[[NAME]].csproj`. Then run this command from that directory:

```ps1
gci *csproj |% { get-content $_.FullName }
```

### Expected behavior

```console
The content of the file is printed to the console.
```

### Actual behavior

```console
Get-Content: An object at the specified path C:\VS\src\Tests\SolutionGenerator\ProjectTemplates\Lib.UWP\[[NAME]].csproj does not exist, or has been filtered by the -Include or -Exclude parameter.
```

I do however note that this command (which auto-completion helps to create) works:

```ps1
Get-Content '.\`[`[NAME`]`].csproj'
```

### Error details

```console
❯ get-error

Exception             :
    Type    : System.Exception
    Message : An object at the specified path C:\VS\src\Tests\SolutionGenerator\ProjectTemplates\Lib.UWP\[[NAME]].csproj does not exist, or has been filtered by
the -Include or -Exclude parameter.
    HResult : -2146233088
TargetObject          :
    Length : 74
CategoryInfo          : ObjectNotFound: (System.String[]:String[]) [Get-Content], Exception
FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetContentCommand
InvocationInfo        :
    MyCommand        : Get-Content
    ScriptLineNumber : 1
    OffsetInLine     : 18
    HistoryId        : 1
    Line             : gci *csproj |% { get-content $_.FullName }
    PositionMessage  : At line:1 char:18
                       + gci *csproj |% { get-content $_.FullName }
                       +                  ~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : get-content
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Brackets are one of the wildcard characters that pwsh recognises. To target a file with those characters in, you can either escape them as you found, or you can use `-LiteralPath` to indicate that the path needs to be taken fully literally. When referencing FileInfo objects' FullName, generally `-LiteralPath` is a better option than the `-Path` parameter (which is the default, if you aren't specifying the parameter by name).

**Comment by jborean93** [comment]
You can also just pipe the object from `gci` into `Get-Content` directly and it will use the literal path automatically `gci *csproj | get-content`.

**Comment by AArnott** [comment]
Interesting. I'll use `-LiteralPath` from now on. 
Looking at [the docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.1#parameters) for this cmdlet, I see that `-Path` mentions wildcard interpretation, but it doesn't specify which characters are interpreted as wildcards, so I'm left to assume the standard set of `* ?`. Is there more documentation that I should be discovering?

**Comment by jborean93** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.1 contains more info on wildcards in PowerShell.

**Comment by vexx32** [comment]
Check the [`about_Wildcards`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.1) help topic, that has the most comprehensive information I think.

**Comment by AArnott** [comment]
Thanks.

**Comment by ulhasmorbale** [comment]
Thanks, adding -LiteralPath worked for me too.
