### ISSUE TITLE
Set-Content: Unable to clear content of X because it is a directory. Clear-Content is only supported on files.

### ISSUE THREAD

**Issue by jonasjancarik** [PowerShell/PowerShell#16074]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Set-Content -Path test -Stream com.dropbox.ignored -Value 1` fails with `Set-Content: Unable to clear content of 'C:\Users\...\Dropbox\test' because it is a directory. Clear-Content is only supported on files.`

### Expected behavior

```console
The Set-Content command should succeed.

It should be possible to set the content of a stream for a folder like this - apparently this was working in older versions of PS; it is the recommended way of ignoring folders for Dropbox (https://help.dropbox.com/files-folders/restore-delete/ignored-files).
```

### Actual behavior

```console
PS> C:\Users\...\Dropbox> Set-Content -Path test -Stream com.dropbox.ignored -Value 1
Set-Content: Unable to clear content of 'C:\Users\...\Dropbox\test' because it is a directory. Clear-Content is only supported on files.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22449
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@jonasjancarik Please download latest daily build from main page of the repository and re-check the scenario.

**Comment by jonasjancarik** [comment]
> @jonasjancarik Please download latest daily build from main page of the repository and re-check the scenario.

Happy to report that it works well in 7.2.0-preview.9
