### ISSUE TITLE
Out-File accepts wildcards, even though it mustn't!

### ISSUE THREAD

**Issue by skycommand** [PowerShell/PowerShell#16076]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

According to the [documentation page for the Out-File cmdlet](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Utility/Out-File.md), the `-FilePath` parameter does not accept any wildcard characters. Yet, it does! The consequences are dire. Imagine running the following cmdlets:

``` PowerShell
' ' | Out-File -FilePath '.\[1-4].txt'
```

### Expected behavior

I expect `Out-File` to try to create a file called `[1-4].txt`. This is a perfectly valid name in NTFS. If this file exists, overwrite it. This outcome is according to the documentation page too.

### Actual behavior

1. If none of the following files exist: `1.txt`, `2.txt`, `3.txt`, and `4.txt`
    `Out-File` throws the following unreasonable error: "Out-File: Cannot perform operation because the wildcard path .\[1-4].txt did not resolve to a file."
1. If **one and only one** of the following files exist: `1.txt`, `2.txt`, `3.txt`, and `4.txt`
    `Out-File` overwrites the file, unless `-NoClobber` is specified.
    In complex situations, this could cause unexpected loss of data in files that should not be affected.
1. If **more than one** of the following files exist: `1.txt`, `2.txt`, `3.txt`, and `4.txt`
    `Out-File` throws the following unreasonable error: "Out-File: Cannot perform operation because the path resolved to more than one file. This command cannot operate on multiple files."

### Error details

Case 1
```
Exception             :
    Type       : System.IO.FileNotFoundException
    Message    : Unable to find the specified file.
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
    Source     : System.Management.Automation
    HResult    : -2147024894
TargetObject          : .\[1-4].txt
CategoryInfo          : OpenError: (.\[1-4].txt:String) [Out-File], FileNotFoundException
FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
ErrorDetails          : Cannot perform operation because the wildcard path .\[1-4].txt did not resolve to a file.
InvocationInfo        :
    MyCommand        : Out-File
    ScriptLineNumber : 1
    OffsetInLine     : 7
    HistoryId        : 20
    Line             : ' ' | Out-File -FilePath '.\[1-4].txt'
    PositionMessage  : At line:1 char:7
                       + ' ' | Out-File -FilePath '.\[1-4].txt'
                       +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Out-File
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

Case 3
```
Exception             :
    Type        : System.Management.Automation.PSInvalidOperationException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot perform operation because operation "ReportMultipleFilesNotSupported" is not valid. Remove operation "ReportMultipleFilesNotSupported", or investigate
why it is not valid.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    TargetSite  :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace  :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
    Message     : Cannot perform operation because operation "ReportMultipleFilesNotSupported" is not valid. Remove operation "ReportMultipleFilesNotSupported", or investigate why
it is not valid.
    Source      : System.Management.Automation
    HResult     : -2146233079
CategoryInfo          : InvalidArgument: (:) [Out-File], PSInvalidOperationException
FullyQualifiedErrorId : ReadWriteMultipleFilesNotSupported,Microsoft.PowerShell.Commands.OutFileCommand
ErrorDetails          : Cannot perform operation because the path resolved to more than one file. This command cannot operate on multiple files.
InvocationInfo        :
    MyCommand        : Out-File
    ScriptLineNumber : 1
    OffsetInLine     : 7
    HistoryId        : 32
    Line             : ' ' | Out-File -FilePath '.\[1-4].txt'
    PositionMessage  : At line:1 char:7
                       + ' ' | Out-File -FilePath '.\[1-4].txt'
                       +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Out-File
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Use `-LiteralPath $pathValue` if you need to supply a path that may contain wildcards.

I'm not really sure why Set-Content and Out-File allow use of wildcards to be honest, I don't think either of them can _use_ a path that resolves to multiple files. It would be more sensible IMO to behave like New-Item whose `-Path` parameter behaves implicitly like -LiteralPath, but I suppose that ship has sailed.

**Comment by skycommand** [comment]
Perhaps we should focus on how to correct this. Two courses of action come to mind:

1. In the subsequent releases, change `-FilePath` into an alias for `-LiteralPath`.
2. In the subsequent releases, change the `-LiteralPath` into the default unnamed parameter, and explain the consequences of using `-FilePath` on the documentation page.

In both cases, change `-Path` into an alias for `-LiteralPath`.

**Comment by jborean93** [comment]
I can somewhat understand why it supports wildcards. Say you had some sort of backup log file that had a date or pid in the filename you could do something like `"my info" | Out-File application-*.log` and it will put it in the file that matches the pattern specified. It's use is arguably limited though as it will fail if multiple matches are found.

**Comment by skycommand** [comment]
@jborean93 Hi. The Principle of Least Astonishment is predicated on the fact that if you try hard enough, you can find some justification for everything after the fact.

The cmdlet's current behavior impedes the natural workflow of a system administrator because of its perverse (and definitely unintended) use of wildcards. To wit, wildcards are supposed to help select multiple files or folders, not make selecting one harder. This behavior, even if well-documented, does not lead to predictable behavior.

**Comment by jborean93** [comment]
I totally agree with you and personally I think `-Path` should be `-LiteralPath` and wildcards are the opt in scenario but that ship has sailed. I even created a custom PSScriptAnalyzer rule that detected scripts not using `-LiteralPath` for stuff I maintain. I was merely trying to explain that there could be a reason why it does support wildcards in comparison with `New-Item` which does not.

**Comment by iSazonov** [comment]
It is by design https://github.com/PowerShell/PowerShell/issues/6729#issuecomment-984165303

**Comment by skycommand** [comment]
@iSazonov By design or not, you have to appreciate all the unnecessary trouble it is giving us. Every time I wish to send a filename to PowerShell cmdlet, I have to use a helper function that scans the filename string for `[` and `]`. Once these characters are found, the function has to inject a number of backticks (<code>\`</code>) depending on what cmdlet receives it. `Get-ChildItem` needs two, `Out-File` needs one! I've seen cmdlets that need three! Now, what's the justification for all this trouble imposed upon us? That in a galaxy far, far away, an app named `bash` accepts wildcards? That's extremely unfair!

**Comment by SeeminglyScience** [comment]
@skycommand You can use `-LiteralPath` instead.

---

It may seem unnecessary to some folks, but wildcards can be useful interactively even only a single file can be specified.

I've also definitely seen code where folks depend on this to resolve part of a file path that is known not to be ambiguous but can change. For example, and application could have a directory structure like `app/settings-00000000-0000-0000-C000-000000000046/config.json` where the latter half of the folder name is a machine unique guid. I've seen code that resolves the path with `Out-File -FilePath app/settings-*/config.json`.

**Comment by skycommand** [comment]
@SeeminglyScience How do I determine how many `` ` `` I need to insert before `[` and `]` to convert them to a literal, in case I needed to use it as a wildcard as well? Other than trial and error, what can tell me which of the following is correct?

~~~PowerShell
"``[By serial number``] TMZ-[ABCDEF]01.lib"
"```[By serial number```] TMZ-[ABCDEF]01.lib"
"````[By serial number````] TMZ-[ABCDEF]01.lib"
~~~

**Comment by SeeminglyScience** [comment]
Should be the first. Though I'd recommend using <kbd>'</kbd> instead of <kbd>"</kbd> for literals as <kbd>`` ` ``</kbd> is an escape character for both wildcard patterns and the language itself. If using `-LiteralPath` instead of `-Path` you shouldn't need any back ticks.

**Comment by skycommand** [comment]
@SeeminglyScience **Bzzt! Wrong answer.** The last item is correct, i.e., you need four backticks (`` ` ``). Try this script to see for yourself.

```PowerShell
Out-File -LiteralPath '[By serial number] TMZ-A01.lib'
# ↑ Creates "[By serial number] TMZ-A01.lib"

Out-File -Path "`[By serial number`] TMZ-[ABCDEF]01.lib" -InputObject "Test"
# ↑ Out-File: Cannot perform operation because the wildcard path
# [By serial number] TMZ-[ABCDEF]01.lib did not resolve to a file.

Out-File -Path "``[By serial number``] TMZ-[ABCDEF]01.lib" -InputObject "Test"
# ↑ Out-File: Cannot perform operation because the wildcard path
# `[By serial number`] TMZ-[ABCDEF]01.lib did not resolve to a file.

Out-File -Path "```[By serial number```] TMZ-[ABCDEF]01.lib" -InputObject "Test"
# ↑ Out-File: Cannot perform operation because the wildcard path
# `[By serial number`] TMZ-[ABCDEF]01.lib did not resolve to a file.

Out-File -Path "````[By serial number````] TMZ-[ABCDEF]01.lib" -InputObject "Test"
# ↑ SUCCESS!
```

@iSazonov Given the above, can you at least see my concern?

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience **Bzzt! Wrong answer.** The last item is correct, i.e., you need four backticks (`` ` ``). Try this script to see for yourself.

I did say *should* to be fair 🙂 there's a few open issues about it already like #7999. Thankfully you can side step it pretty easily by just using `-LiteralPath` instead. Even if you couldn't though, I don't think the presence of bugs related to escaping is a good motivation for stripping out the functionality all together

**Comment by iSazonov** [comment]
>  like #7999.

I hope we will resolve such issues and more in FileSystem Provider V2.
