### ISSUE TITLE
File permissions libmi.so and libpsrpclient.so wrong after upgrade 7.1.3 to 7.1.4 on Ubuntu 20.04

### ISSUE THREAD

**Issue by SAE-Amsterdam** [PowerShell/PowerShell#16077]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Did an upgrade of 7.1.3 to 7.1.4 yesterday on ubuntu server 20.04 
Installed via the preferred method of adding the repositories to apt.

After install I lost the PSWSMan Modules, which was ok, just installed anew with scope allusers

My script runs on the www-data user, so no home directory and I could not get it to see the modules. 

Turns out that after the upgrade, I had a libmi.so.bak and libpsrpclient.so.bak file and the new libmi.so and libpsrpclient.so had permissions of 640 instead of 644.
(in /opt/microsoft/powershell/7/ )

### Expected behavior

```console
Upgrade of 7.1.3 to 7.1.4 should have set file permissions to 644 to libmi.so and libpsrpclient.so
```

### Actual behavior

```console
Upgrade of 7.1.3 to 7.1.4 set file permissions to 640 to libmi.so and libpsrpclient.so
```

### Environment data

```powershell
Is empty on Linux :-(
```

**Comment by jborean93** [comment]
> I had a libmi.so.bak and libpsrpclient.so.bak file

Just as an FYI `PSWSMan` creates these `.bak` files in case it needs to revert it back to the original ones.
