### ISSUE TITLE
Add alias for Measure-Object

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#16078]
### Summary of the new feature / enhancement

`Measure-Object` currently does not have a builtin alias. Suggest that `mo` be added to the built aliases. I did not see any native binary conflicts across Linux (Ubuntu 20.04), Windows, or MacOS (Big Sur).

The following is a bit laborious especially if you run the command first and then decide you wanted the count.

```powershell
(gci -r -file).Count
```

### Proposed technical implementation details (optional)

Add `mo` as an alias for `Measure-Object`.

```powershell
gci -r- file | mo
```

**Comment by iSazonov** [comment]
Aliases, with rare exceptions, create more problems (conflicts) in general than useful. It is not recommended to use them in scripts. Users can still create them locally for the convenience of working in an interactive session, but this is a _personal_ preference and this could be placed in user profile..

**Comment by doctordns** [comment]
None of the *-Objects have two letter aliases, by default. The object cmdlets do have aliases that are the same as the verb, so 

```powershell
gci -r- file | measure
```
If, while entering this line, you just type the M and E (of measure) then tab, tab completion completes the command correctly.

And as always - you can edit $Profile and add personal aliases.

**Comment by thezim** [comment]
I don't know how I over looked `measure`. On MacOS I have a 7 match on `me` but `mea` get me there.
