### ISSUE TITLE
Move-Item recursively creates "infinitely" nested directories

### ISSUE THREAD

**Issue by PAStheLoD** [PowerShell/PowerShell#16089]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
mkdir test
cd test

mkdir abc
mv * abc
```

Don't forget to hit ctrl-c fast.

`dir -Recurse t` shows the created structure. I used 7zip File Manager to shift-del the nested dir structure.

### Expected behavior

PS should not create the nested directory structure, it should ignore the target when expanding the wildcard into the source list, move everything else into the target directory.

In this example it should basically do a no-op, since there's nothing else to move into "abc".

### Actual behavior

A directory that contains a directory, that contains a directory ... t\abc\abc\abc\abc ...

### Environment data

```powershell
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@PAStheLoD Thanks for reporting the issue! It was fixed in #16029. You can download latest preview build and check the scenario.
