### ISSUE TITLE
Automatic setting of terminal progress state

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#16099]
### Summary of the new feature / enhancement

When running PowerShell within Windows Terminal, one can use OSC9;4 sequences to indicate (on the tab and on the taskbar) that a lengthy command is being executed:

````powershell
Write-Host "`e]9;4;3;100`a"
# something that will take quite some time to run
 Write-Host "`e]9;4;0;100`a"
````

It would be useful to have a built-in mechanism that sets the terminal's progress state "automatically" (should be configurable, of course).

This would give users a "seamless" experience like in any other apps that perform lengthy operations.

### Proposed technical implementation details (optional)

This should be done in such a way that it doesn't interfere with a potential future use of OSC9;4 by `Write-Progress` et al. (for instance, there should be some kind of function that computes the desired terminal progress state from a combination of _multiple_ sources).

In https://twitter.com/Steve_MSFT/status/1437467621599768576?s=20 @SteveL-MSFT  suggests:

> Maybe in PS7, if a command takes more than some predetermined time to complete (5 secs?), then the native command processor can set the terminal progress state and reset upon completion?

**Comment by rkeithhill** [comment]
This has been implemented.  If you have preview.9, try setting this `$PSStyle.Progress.UseOSCIndicator = $true` and then in Windows Terminal the taskbar will show progress, as will the terminal tab icon.

**Comment by sba923** [comment]
I've tried this with `gci -rec c:/` and get no 'indeterminate' progress indicator...

**Comment by SteveL-MSFT** [comment]
@rkeithhill that feature is tied to `Write-Progress`.  What @sba923 is asking for is if a command takes a long time (and doesn't write progress), then have PowerShell automatically emit that ANSI code so that tab indicates it is busy.

**Comment by sba923** [comment]
For reference, what's the link to that other `Write-Progress` feature?

**Comment by rkeithhill** [comment]
`Write-Progress` is a command you can use in your own functions to display progress of a long running function.  Right now, in PowerShell, it is up to the implementation of individual commands as to whether or not they display progress.  Invoke-WebRequest is one such command that displays progress.  Internally, commands use the same underlying code that `Write-Progress` uses to display progess.

You can try this with this command in PowerShell:

```powershell
1..100 | %{Write-Progress -Activity 'Busying doing foo' -Status "$_% complete" -PercentComplete $_; Sleep -m 250}
```

@SteveL-MSFT You refer to doing this for native commands but the OP asks about `gci` in a follow up post.  🤷

**Comment by sba923** [comment]
It seems my description of the feature was far from clear.

What I'm suggesting is a _seamless_ mechanism where PowerShell would automagically detect that I'm launching _any_ command, sets the progress indicator to "indeterminate" when the command starts, and resets the progress indicator when the command completes execution.

@SteveL-MSFT suggested to set the "indeterminate" state not when the command starts but when PowerShell internally has determined that the command has been running for longer than some predetermined amount of time.

My test with `gci` was just a randomly picked long-running command to test whether the desired behavior had already been implemented.

**Comment by SeeminglyScience** [comment]
You can set this up in your profile by overriding `PSConsoleHostReadLine`:

```powershell
function PSConsoleHostReadLine {
    Microsoft.PowerShell.Core\Set-StrictMode -Off
    Write-Host "`e]9;4;0;100`a" -NoNewline
    [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)
    Write-Host "`e]9;4;3;100`a" -NoNewline
}
```

I'm a little reluctant to agree that this should be a default though. If I have a PowerShell window open constantly running, like monitoring something, I don't really want the whole process group in the task bar to show as in-progress.  Also simply running `vim` or some other interactive console app would trigger it.

**Comment by vexx32** [comment]
I could see this being built into Write-Progress / the WriteProgress() method on PSCmdlet itself, potentially, but I agree that having it be a default thing for _any_ potentially long-running command is probably a bit of a broad stroke.

Alternatively, exposing methods for emitting these sequences easily via some API on the PSHost or something along those lines might be a neater solution?
