### ISSUE TITLE
Powershell Start-Transcript does not log the same information each time it is ran

### ISSUE THREAD

**Issue by bq824** [PowerShell/PowerShell#16095]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using the following command the data in the log file is not the each time it runs. I am trying to use this command to capture the compile and clone process. The attached document called buildOutput.txt has the expected results but when rerunning my script the second time it did not log anywhere near the same data as the first log. buildOutput2.txt does not contain the cloning or compiling process shown in the first screen shot. The results contained in the log file are not consistent each time I run the power shell script.
[buildOutput.txt](https://github.com/PowerShell/PowerShell/files/7164661/buildOutput.txt)
[buildOutput2.txt](https://github.com/PowerShell/PowerShell/files/7164663/buildOutput2.txt)

Start-Transcript  -Force -Path  $logfile

### Expected behavior

```console
See Attached buildOuput.txt
```

### Actual behavior

```console
See attached buildOutput2.txt file
```

### Error details

```console
No error returned
```

### Environment data

```powershell
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.19041.1151                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.19041.1151                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1
```

### Visuals

None

**Comment by iSazonov** [comment]
> PSVersion                      5.1.19041.1151     

The repository is only for PowerShell 7. Can you reproduce the issue in latest PowerShell 7.2 Preview?

**Comment by bq824** [comment]
Is this a known issue in the current version I have installed?

Ed L Wolf
Technical Advisor - Embedded Software
812-377-0831
***@***.***
Cummins Inc.
Mail Code: C7004
1460 National Road
Columbus, Indiana 47201
United States

**Comment by bq824** [comment]
Hi

During some more testing I found that the issue can be resolved by doing the following steps


  1.  Open a command prompt in Windows
  2.  Execute my powershell script that will use Start-Transcript and Stop-Transcript to log
  3.  When the script complete close the command prompt window
  4.  Repeat steps 1 thru 3 and everything works fine

If I don’t close the Command prompt window and rerun my powershell script the log file does not always contain all the information that was display in the terminal window.

Any suggestions?

Ed L Wolf
Technical Advisor - Embedded Software
812-377-0831
***@***.***
Cummins Inc.
Mail Code: C7004
1460 National Road
Columbus, Indiana 47201
United States

**Comment by doctordns** [comment]
With respect to this issue, you are using Windows PowerShell 5.1. Thie repository only tracks issues with PowerShell 7. 

Can you reproduce this issue in PowerShell 7?
