### ISSUE TITLE
Powerline support for pwsh.exe

### ISSUE THREAD

**Issue by hanskokx** [PowerShell/PowerShell#16093]
### Summary of the new feature / enhancement

I primarily use [Fluent Terminal](https://github.com/felixse/FluentTerminal/) (which, in my _humble_ opinion, is better than Windows Terminal. 🤷🏻‍♂️) In Fluent Terminal, I'm able to specify a powerline font, which looks lovely:

![image](https://user-images.githubusercontent.com/1911919/133313049-34b7d4dd-32cf-4d2c-ae6c-503481d257f3.png)

Unfortunately, I'm not able to specify a proper font when launching `pwsh.exe` directly, resulting in this monstrosity:

![image](https://user-images.githubusercontent.com/1911919/133313201-bb4a5d26-231a-40a3-83b6-4d8fc2c1e838.png)

I know the focus is on using Windows Terminal, in which I _can_ specify a powerline font... but can you _please_ add support to `pwsh.exe` for those rare instances in which I actually need to launch it directly? Pretty pwease?

**Comment by jborean93** [comment]
This is really a conhost question which is what is being spawned by PowerShell/pwsh automatically when you start the executable. It has limited support for fonts and unicode characters outside the BMP which is what Windows Terminals really alleviates. I believe in later releases you can change the default terminal that a console application opens to Windows Terminal which would somewhat solve this issue when you open `pwsh.exe` directly.

There's also something like https://github.com/Jaykul/PowerLine which you can try out which predates WT and gives a more PowerShell spin on the conhost side to get things working to an extent.

**Comment by hanskokx** [comment]
I mean, you're about 12% correct. Yes, the issue is that conhost doesn't support fonts other than bitmap fonts.  Everything beyond that, you're technically correct, but it doesn't apply.

In fact, I don't _want_ to use Windows Terminal.  I prefer Fluent Terminal.  Still, every once in a great while, I need to launch pwsh.exe directly:

![image](https://user-images.githubusercontent.com/1911919/133336059-5a96bc0a-5331-4bb4-a2cc-e9c9033c73e0.png)

This launches the conhost, as you've correctly surmised.

My issue is this: conhost should allow more fonts than just bitmap fonts, because it's no longer 1998. :)

**Comment by jborean93** [comment]
> My issue is this: conhost should allow more fonts than just bitmap fonts, because it's no longer 1998. :)

That's the crux of the issue, it's a conhost problem, that may or may not have a future at all. Pwsh just uses conhost because that's the behaviour in Windows when a console process is spawned without a console supplied. Starting `powershell.exe`, `cmd.exe`, or any other console compiled application will behave in the exact same way and thus this problem isn't something specific to `pwsh.exe`.

In saying all this, the link to the [PowerLine](https://github.com/Jaykul/PowerLine) module would potentially indicate it's possible to install the PowerLine font on conhost for use in PowerShell. Specifically see https://github.com/Jaykul/PowerLine#powerline-fonts-and-separators. I'm personally unsure how this is actually possible but potentially the fonts in question fit inside the BMP allowing it to be used in conhost.

**Comment by hanskokx** [comment]
Eh. Seems like an awful solution.  I'm glad to know the issue isn't PowerShell-specific, though.  (I use the term "glad" lightly.)

I might need to push this up the chain to conhost.  Thanks.

**Comment by jborean93** [comment]
I'm curious what's actually awful about it? You need the fonts to be installed to use the fonts.

**Comment by hanskokx** [comment]
![image](https://user-images.githubusercontent.com/1911919/133516823-50eb01cf-5881-44dc-ac2b-9f6f0071f5a7.png)

Tell me the font isn't installed. 🤷🏻‍♂️

**Comment by jborean93** [comment]
That's fair, I do remember reading something about conhost being selective around what fonts it can offer but even the current devs aren't 100% sure based on https://github.com/microsoft/terminal/issues/295.

Even so when I install the [nerdfont-hack](https://community.chocolatey.org/packages/nerdfont-hack) package with chocolatey I can see them as a selectable option in conhost

![image](https://user-images.githubusercontent.com/8462645/133518259-f4988821-3b6a-4c82-94e9-1c59c7b94c3a.png)

Once I select one of the nerd fonts it is able to display in conhost

![image](https://user-images.githubusercontent.com/8462645/133518951-c5539643-503a-4f60-a5c0-1cba6c8d1608.png)

You might need to ensure it's installed system wide and not just for the current user (no idea how to check that). Good luck in getting it working.

**Comment by hanskokx** [comment]
That's actually a useful clue. I'm try it tomorrow. Thanks!

**Comment by hanskokx** [comment]
Huh, yeah. That worked. Weird, but wonderful!  Thanks!

![image](https://user-images.githubusercontent.com/1911919/133668504-0db8d2d4-ecad-4622-8ab7-1fa98b850a9f.png)

**Comment by jborean93** [comment]
Glad you were able to get it working!
