### ISSUE TITLE
CTRL+ combos breaks with cyrillic

### ISSUE THREAD

**Issue by 243083df** [PowerShell/PowerShell#16101]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Open powershell 7.1.4
With cyrillic keymap press CTRL+С
After that al

### Expected behavior

```console
Powershell correctly execute command
PS> ^C
```

### Actual behavior

```console
Powershell print С and all CTRL+ combos stop working at all in both english and cyrillic keymap
PS> с
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please unload PSReadline and check again.

**Comment by 237dmitry** [comment]
With the current keyboard layout `Ru`, pressing the Ctrl-C combination returns:
In Windows terminal:
```
 PS > c
```
In standart host:
```
 PS > ^C
```

**Comment by 243083df** [comment]
After "Remove-Module PSReadline" all "CTRL+" start working, but in case "CTRL+C" not display "^C"

**Comment by daxian-dbw** [comment]
This is a duplicate issue of https://github.com/PowerShell/PSReadLine/issues/2865
