### ISSUE TITLE
[HP][CPS][Win11][21H2][PowerShell]The PowerShell Export-WindowsDriver command fail to export drivers with Value cannot be null

### ISSUE THREAD

**Issue by jason-cheng-tw** [PowerShell/PowerShell#16103]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Steps to repro:
-
1. Setup OS and update to 22000.168
2. Launch Powershell with administrator
3. Type export-windowsDriver command to export drivers
    Export-WindowsDriver -online -destination c:\Drvs
4. [Symptom] The Export-WindowsDriver cannot export the drivers

### Expected behavior

```console
Expected results:
- The Export-WindowsDriver can export the drivers
```

### Actual behavior

```console
Actual results:
-The Export-windowsDriver cannot export the drivers
```

### Error details

```console
Export-WindowsDriver : Value cannot be null.
Parameter name: SafeHandle cannot be null.
At line:1 char:1
+ Export-WindowsDriver -online -destination c:\Drvs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-WindowsDriver], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Dism.Commands.ExportWindowsDriverCommand
```

### Environment data

```powershell
Windows 11 21H2 OS version: 22000.184
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![PowerShell-Export-WindowsDriver Error](https://user-images.githubusercontent.com/69946368/133473495-00b90638-e2d8-4c4e-adfa-de130e3df840.png)

**Comment by vexx32** [comment]
This cmdlet comes from a module that's managed by the Windows product team rather than the PowerShell team. Please use the Windows Feedback tool to submit the issue and have it triaged by the appropriate team. 🙂
