### ISSUE TITLE
Powershell pipelines are still underperforming

### ISSUE THREAD

**Issue by psmolkin** [PowerShell/PowerShell#16115]
### Summary of the new feature / enhancement

Some examples with pipes using `tar.exe` and `wsl.exe`

PSVersion    7.1.4

1. Untar and pipe to `wsl.exe`
    ```pwsh
    Measure-Command {
      tar.exe -xf .\Fedora-Container-Minimal-Base-34-1.2.x86_64.tar -O acd0933ef68b42e175d6f6a7d968dc418d7acbb48cf08926b5b109f3699cc368/layer.tar  | 
      wsl.exe --import fed c:\WSL\fed -
      }  | select -exp TotalSeconds ; wsl --unregister fed
    ```
    Output disappointing...
    >```pwsh
    >14,0322798
    >Unregistering...
    >```

1. Now retrying to pass as an array entry:
    ```pwsh
    Measure-Command {
      ,(tar.exe -xf .\Fedora-Container-Minimal-Base-34-1.2.x86_64.tar -O acd0933ef68b42e175d6f6a7d968dc418d7acbb48cf08926b5b109f3699cc368/layer.tar)  | 
      wsl.exe --import fed c:\WSL\fed -
      }  | select -exp TotalSeconds ; wsl --unregister fed
    ```
    the result is better
    >```pwsh
    >8,0986971
    >Unregistering...
    >```
1. But compare to `cmd.exe`
    ```pwsh
    Measure-Command {
      cmd.exe /c 'tar.exe -xf Fedora-Container-Minimal-Base-34-1.2.x86_64.tar -O acd0933ef68b42e175d6f6a7d968dc418d7acbb48cf08926b5b109f3699cc368/layer.tar | wsl.exe --import fed c:\WSL\fed -'
    }  | select -exp TotalSeconds ; wsl --unregister fed
    ```
    Wow!
    >```pwsh
    >0,534397
    >Unregistering...
    >```

Even using "array hack" the performance between cmd and ps pipes is uncomparable.

## Bonustrack
The same using WSL Interop
```bash
time bash -c 'tar -xf ./Fedora-Container-Minimal-Base-34-1.2.x86_64.tar -O acd0933ef68b42e175d6f6a7d968dc418d7acbb48cf08926b5b109f3699cc368/layer.tar  | wsl.exe --import fed "c:\WSL\fed" -'; wsl.exe --unregister fed
```
😬
>
>
>_**real    0m1.809s**_
>user    0m0.060s
>sys 0m0.712s
>Unregistering...

**Comment by rjmholt** [comment]
>  it seems you have a PR for the scenario?

Still a WIP

> pipelines are still underperforming

This feels like an existing issue &mdash; it should probably be a comment on an already open issue.

**Comment by iSazonov** [comment]
Dup #1908
