### ISSUE TITLE
Powershell doesn't work with intellij

### ISSUE THREAD

**Issue by LegendaryReaper670** [PowerShell/PowerShell#16121]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Try to run intellij, the terminal won't work "Cannot open Local Terminal
Failed to start [powershell.exe] in C:\Users\username\IdeaProjects\UserLogger

Error running process: CreateProcess failed. Code 2

See IDE log (Help | Show Log in Explorer) for the details."

### Expected behavior

```console
The terminal is supposed to work
```

### Actual behavior

```console
Don't have a picture but the terminal is supposed to open and work
```

### Error details

```console
Get-Error : The term 'Get-Error' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ Get-Error
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Error:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![image](https://user-images.githubusercontent.com/79212718/133894529-402b1ff9-e5ee-48df-923f-17ba1b74d8e0.png)

**Comment by iSazonov** [comment]
The repository is only for PowerShell 7+. Can you reproduce the issue with latest PS7 Preview? For Windows PowerShell please use Windows Feedback tool.

**Comment by kilasuit** [comment]
This is an issue you should raise with Jetbrains the team behind IntelliJ which already has a very similar issue in thier bug tracker at https://youtrack.jetbrains.com/issue/IDEA-278224
