### ISSUE TITLE
BasicHtmlWebResponseObject does not parse self-closing <input> tags

### ISSUE THREAD

**Issue by richard-browne** [PowerShell/PowerShell#16126]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using 'Invoke-WebRequest -UseBasicParsing', the returned BasicHtmlWebResponseObject does not parse \<input\> tags correctly. It assumes they will be closed with a '/\>' or '\</input\>'. However in html, neither the slash nor closing tag is required/legal depending on your html flavour.

The bug is in BasicHtmlWebResponseObject.Common.cs. The s_inputFieldRegex is set to:

`@"<input\s+[^>]*(/>|>.*?</input>)"`

But it should be:

`@"<input\s+[^>]*(/>|>|>.*?</input>)"`

Looking at the history the problem has been there since PowerShell 3.0, and remains unfixed in the latest PowerShell Core.

### Expected behavior

```console
Suppose we will perform an HTTP GET thusly:

`$response = Invoke-WebRequest -UseBasicParsing -Url 'https://localhost/test.html'`

And the returned html is:

`<html><body><input name='foo' value='mcgoo'></body>/</html>`

$response.InputFields should contain 1 element. $response.InputFields.FindByName('foo') should return the element.
```

### Actual behavior

```console
Instead $response.InputFields contains no elements, and $response.InputFields.FindByName('foo') returns $null.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by farmerau** [comment]
I'll try to take a look into this.

**Comment by farmerau** [comment]
@richard-browne The fix for this was merged.

**Comment by CarloToso** [comment]
@iSazonov this is no longer an issue, could you please close it?
