### ISSUE TITLE
The PowerShell ISE

### ISSUE THREAD

**Issue by Tarjei-stavanger** [PowerShell/PowerShell#16127]
### Summary of the new feature / enhancement

I miss the ISE on Windows. It is a cheap and cheerful environment for quick development of small PowerShell scripts. Nothing fancy, just good enough. And significantly better than notepad and even Notepad++ for this purpose.

I realize that most developers will use a big fancy IDE. If you are into system management, that is not likely since you usually have to develop on the server which will eventually run the scripts. Visual Studio is a dramatic overkill for these jobs and it takes far too long to install.

So give us back the PowerShell ISE for Windows, please!

### Proposed technical implementation details (optional)

I suspect that you know how to resurrect the PowerShell ISE since it is a past product.

**Comment by iSazonov** [comment]
PowerShell ISE is frozen project. New project is Visual Studio Code with PowerShell Extension.

**Comment by Tarjei-stavanger** [comment]
Visual Studio is a dramatic overkill.

**Comment by iSazonov** [comment]
It is not Visual Studio. It is Visual Studio Code.

**Comment by Tarjei-stavanger** [comment]
It does not matter what you call it. It is still dramatic overkill.

**Comment by SeeminglyScience** [comment]
To be clear there are two very different products with similar names.  One is Visual Studio, which I would tend to agree it would be overkill.  The other is VSCode (Visual Studio Code) which is pretty lightweight. The only thing that is really the same is that they are named very similarly (which is confusing) and that you write code with both.

**Comment by rkeithhill** [comment]
Perhaps give VSCode a try: https://code.visualstudio.com/.  It's free and also open source (on GItHub).

**Comment by Tarjei-stavanger** [comment]
Most of you are trying to sell me a pack elephant when the need is a carrier bag.

The PowerShell IDE is ideal for doing small work on a server. It **works well** right out of the box.  It handles characters set used very well. Tab handling is excellent. I can write the code wih syntax help and then run with F5. And possibly save. It is ideal for the job.

I'm thoroughly unimpressed with Visual Studio Code. I don't like editors which I have to program before they work sensibly. It does not handle characte sets or tabs in a sensible manner out of the box. It is a shitty product for my needs.

I can live fine with 5.1 syntax checking in the IDE for the time being.
