### ISSUE TITLE
Write-Progress on macOS unexpectedly outputs additional whitespace characters to std out

### ISSUE THREAD

**Issue by shaun-od** [PowerShell/PowerShell#16139]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a script e.g test.ps1 with the following contents

```
Write-Warning "This is a warning"
Write-Progress -Activity "Progress" -PercentComplete 100
Write-Warning "This is a warning"
```

Run this script with the following command `pwsh test.ps1 > mac.txt` on macOS (probably Linux distros as well I just haven't tested)

Run this script with the following command `pwsh test.ps1 > win.txt` on Windows (tested on Windows 10)

I have attached the files that are produced from the commands above.

[mac.txt](https://github.com/PowerShell/PowerShell/files/7215286/mac.txt)
[win.txt](https://github.com/PowerShell/PowerShell/files/7215287/win.txt)

### Expected behavior

```console
The files contain the same content similar to below as shown in the windows output from above


WARNING: This is a warning
WARNING: This is a warning

```

[win.txt](https://github.com/PowerShell/PowerShell/files/7215287/win.txt)

### Actual behavior

```console
Based on the file content above (and linked below) you can see the mac version has lots of whitespace between the two warning messages and the second warning isn't on a new line as expected.

Whereas the file produced on Windows outputs as I expect it to.
```

[mac.txt](https://github.com/PowerShell/PowerShell/files/7215286/mac.txt)

### Environment data

```powershell
On macOS

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

On Windows 

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Please check with latest PowerShell 7.2 preview build.

**Comment by shaun-od** [comment]
Yes I have tried it with a preview version 

This seems to resolve the issue.

Is the timeframe known for when this is going to be released

[mac-preview.txt](https://github.com/PowerShell/PowerShell/files/7221665/mac-preview.txt)

```
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> Is the timeframe known for when this is going to be released?

Immediately after .Net 6.0 release
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/
> Speaking of the final release, we now have a date! Book off November 9-11 for .NET Conf 2021. We’ll launch .NET 6 on the 9th with many in-depth talks and demos that tell you everything you want to know about .NET 6.

**Comment by shaun-od** [comment]
Fantastic, thank you for getting back to me 😄
