### ISSUE TITLE
Unable to type after "Enter the GitLab instance URL (for example, https://gitlab.com/):"

### ISSUE THREAD

**Issue by jagruuti** [PowerShell/PowerShell#16132]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [ ] Search the existing issues.
- [ ] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [ ] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I want to register a Gitlab runner using Windows Shell .I'm unable to type after "Enter the GitLab instance URL (for example, https://gitlab.com/):"

### Expected behavior

```console
I should be able to type after "Enter the GitLab instance URL (for example, https://gitlab.com/):"
```

### Actual behavior

```console
I'm unable to type after "Enter the GitLab instance URL (for example, https://gitlab.com/):"
```

### Error details

```console
Please check the recording
```

### Environment data

```powershell
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.19041.1151                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.19041.1151                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1
```

### Visuals

[Issue reproduce.zip](https://github.com/PowerShell/PowerShell/files/7210304/Issue.reproduce.zip)

**Comment by doctordns** [comment]
Does invoking gitlab cause another modal dialog box to pop up? I have seen cases where dialog boxes get spawned and are not always visible - is a task bar icon flashing?

**Comment by Purav2596** [comment]
I faced the same issue. It seems that we must first install the Runner. Try the following in Powershell in the directory where the gitlab-runner is located- 

.\gitlab-runner.exe install
.\gitlab-runner.exe start
.\gitlab-runner.exe stop

Now try to register the runner. Probably, you should be able to enter the URL now.
