### ISSUE TITLE
Script output does not show up in the journal when run as a systemd service on Debian 11

### ISSUE THREAD

**Issue by BobVul** [PowerShell/PowerShell#16135]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running a powershell script as a systemd service on Debian 11 does not show any of its output in the journal/syslog as viewed via `journalctl`.

1. Create `/usr/local/bin/pwshscript` (`chmod +x`) =>
```powershell
#!/usr/bin/env pwsh
echo foo
```

2. Create `/etc/systemd/system/pwshscript.service` =>
```
[Service]
ExecStart=/usr/local/bin/pwshscript
```

3. Run `systemctl start pwshscript.service`

4. View log output with `journalctl -eu pwshscript.service`

### Expected behavior

The systemd journal should show the output of `foo`

Example from Debian 10:

```console
Sep 22 14:16:56 testbox systemd[1]: Started pwshscript.service.
Sep 22 14:16:56 testbox powershell[1205]: (7.1.4:1:80) [Perftrack_ConsoleStartupStart:PowershellConsoleStartup.WinStart.Informational] PowerShell console is starting up
Sep 22 14:16:56 testbox powershell[1205]: (7.1.4:8:80) [NamedPipeIPC_ServerListenerStarted:NamedPipe.Open.Informational] PowerShell has started an IPC listening thread on process: 1205 in AppDomain: None.
Sep 22 14:16:56 testbox powershell[1205]: (7.1.4:1:80) [Perftrack_ConsoleStartupStop:PowershellConsoleStartup.WinStop.Informational] PowerShell console is ready for user input
Sep 22 14:16:56 testbox pwshscript[1205]: foo
Sep 22 14:16:56 testbox systemd[1]: pwshscript.service: Succeeded.
```

### Actual behavior

The output of `foo` is missing from the journal in Debian 11:

```console
Sep 22 14:20:49 testbox systemd[1]: Started pwshscript.service.
Sep 22 14:20:49 testbox systemd[1]: pwshscript.service: Succeeded.
```

Note that an identical bash script works correctly in Debian 11:

```console
Sep 22 14:21:57 testbox systemd[1]: Started bashscript.service.
Sep 22 14:21:57 testbox bashscript[4403]: foo
Sep 22 14:21:57 testbox systemd[1]: bashscript.service: Succeeded.
```

So it's only PowerShell + Debian 11 that exhibits this behaviour. PowerShell + Debian 10, and Bash + Debian 11, both work as expected.

### Environment data

Both powershell and powershell-preview were tested, on Debian 10 and 11. Installed via snap package on both for consistency.

```powershell
PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.9
PSEdition                      Core
GitCommitId                    7.2.0-preview.9
OS                             Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I did not try to logging scripts in linux. Only in windows. Perhaps this helps:

```help about_logging_Non-Windows```

**Comment by BobVul** [comment]
I've narrowed it down further:

* deb package on Debian 10: `journalctl -eu pwshscript` shows output
* deb package on Debian 11: `journalctl -eu pwshscript` shows output
* snap package on Debian 10: `journalctl -eu pwshscript` shows output
* snap package on Debian 11: `journalctl -eu pwshscript` does not show output

So it's something specific to the snap package. More than that, it looks like the output actually does appear in the full `journalctl` log, it's just not linked correctly to the service it came from.

In this case it's looking more likely to be caused by a change in snapd, since the deb package works, rather than an issue with powershell itself.
