### ISSUE TITLE
Add Schema Validation to JsonConfigFileAccessor

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#1614]
Users may manually edit the file, so it we should add schema validation to ensure that it conforms to the expected schema.

**Comment by joeyaiello** [comment]
@mirichmo @Francisco-Gamino do you think this is critical for 6.0.0? What's the work and benefit involved here?

**Comment by mirichmo** [comment]
Yes, it will be beneficial. The work would be to create the schema and validate the JSON file against it when reading it. I don't expect it to be a huge amount of work, but I haven't investigated it in great detail. The schema also documents the supported values for the configuration file.

**Comment by joeyaiello** [comment]
@SteveL-MSFT Sounds like we should do this, what do you think?

**Comment by SteveL-MSFT** [comment]
Doesn't seem like a must have for 6.0.0

**Comment by iSazonov** [comment]
Now we have `Test-Json -Schema` and can resolve the issue.

**Comment by ThomasNieto** [comment]
@iSazonov this issue good to close now?

**Comment by iSazonov** [comment]
No, we haven't still the schema. I played a bit with the config file API and it has seem a not very good format from Json API and strong schema points.
