### ISSUE TITLE
How to interact with `pwsh` by `expect`

### ISSUE THREAD

**Issue by zhiburt** [PowerShell/PowerShell#16142]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I decided that this example may be a little bit more clear then the one in #16118 but the issue is the same.

Run this `expect` script.

`tclsh file_with_the_script.tcl`

```tcl
package require Expect

spawn pwsh

exp_send "ls -l\r"

expect {
        "README.md" { puts "Good repository" }
        timeout {
            puts "Timeout"
            puts "Bad repository"
        }
}
```

### Expected behavior

```console
`ls` command executed.
```

### Actual behavior

```console
Nothing is executed
```

### Environment data

```powershell
...
```

**Comment by SeeminglyScience** [comment]
Try launching with `pwsh -` and passing ``` \n\n``` as the end of command sequence.

**Comment by zhiburt** [comment]
@SeeminglyScience it did helped :(

```log
[mzhiburt@fedora expectrl]$ tclsh aaaaaaaa.tcl 
spawn pwsh -
ls -l

^[[5;1RTimeout
Bad repository
```

**Comment by zhiburt** [comment]
Note see #16118

When you send it before now something will be printed (but in a weird way, like not appended to terminal buffer but rather rewritten, almost sure by other ascii sequences )

```tcl
exp_send "\u001B\[12;1R"
```

**Comment by zhiburt** [comment]
Here I ran other command and leverage https://github.com/zhiburt/expectrl to see the inner buffer and as you see that's exactly what happens

```log
"\"\u{1b}[37m;\u{1b}[39;49m \u{1b}[92mreturn\u{1b}[39;49m \u{1b}[36m\" \"\u{1b}[39;49m \u{1b}[37m}\u{1b}[39;49m\u{1b}[0m\u{1b}[13;8H\u{1b}[?12l\u{1b}[?25h\u{1b}[13;8H\r\nEXPECTED_PROMPT>\u{1b}[?25l\u{1b}[14;17H\u{1b}[39;49m\u{1b}[0m\u{1b}[14;17H\u{1b}[?12l\u{1b}[?25h\u{1b}[14;17H\r\nEXPECTED_PROMPT>\u{1b}[?25l\u{1b}[15;17H\u{1b}[37m[System.Environment]::\u{1b}[97mSetEnvironmentVariable\u{1b}[37m(\u{1b}[36m\"TERM\"\u{1b}[90m,\u{1b}[39;49m \u{1b}[36m\"dumb\"\u{1b}[37m)\u{1b}[39;49m\u{1b}[0m\u{1b}[15;77H\u{1b}[?12l\u{1b}[?25h\u{1b}[15;77H\r\nEXPECTED_PROMPT>\u{1b}[?25l\u{1b}[16;17H\u{1b}[39;49m\u{1b}[0m\u{1b}[16;17H\u{1b}[?12l\u{1b}[?25h\u{1b}[16;17H\r\nEXPECTED_PROMPT>\u{1b}[?25l\u{1b}[17;17H\u{1b}[37m[System.Environment]::\u{1b}[97mSetEnvironmentVariable\u{1b}[37m(\u{1b}[36m\"TERM\"\u{1b}[90m,\u{1b}[39;49m \u{1b}[36m\"NO_COLOR\"\u{1b}[37m)\u{1b}[39;49m\u{1b}[0m\u{1b}[18;1H\u{1b}[?12l\u{1b}[?25h\u{1b}[18;1H\r\nEXPECTED_PROMPT>\u{1b}[?25l\u{1b}[19;17H\u{1b}[39;49m\u{1b}[0m\u{1b}[19;17H\u{1b}[?12l\u{1b}[?25h\u{1b}[19;17H\r\nEXPECTED_PROMPT>\u{1b}[?25l\u{1b}[20;17H\u{1b}[93mhostname\u{1b}[39;49m\u{1b}[0m\u{1b}[20;25H\u{1b}[?12l\u{1b}[?25h\u{1b}[20;25H\r\nfedora\r\n\u{1b}[?1h\u{1b}=\u{1b}]0;\u{7}\u{1b}[6n"
```
