### ISSUE TITLE
I think half-to-even rounding is too bad.

### ISSUE THREAD

**Issue by XValue** [PowerShell/PowerShell#16143]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
[test.txt](https://github.com/PowerShell/PowerShell/files/7225632/test.txt)

#
# test.ps1
#
""
'  $i    $a      $b'
"----  ------  ------"
for($i = 0; $i -lt 20; $i ++)
{
  $a = [Int32]($i / 2)              # Half-to-even rounding is too bad.
  $b = [Int32](($i / 2) + 0.001)    # I like this result.
  if($a % 2) {$c = "  "} else {$c = " |"}
  if($b % 2) {$d = "  "} else {$d = " |"}
  "{0,4}  {1,4}{3}  {2,4}{4}" -f $i, $a, $b, $c, $d
}
"`n"

$ESC = [Char]0x1B
$hideCursor = "$ESC[?25l"
$showCursor = "$ESC[?25h"
Write-Host -NoNewline $hideCursor
'        $e                          $f'
"not smooth                      smooth"
"----------                  ----------"
$str = ""
for($j = 0; $j -lt 100; $j ++)
{
  Write-Host -NoNewline ($str -replace ".", "`b")
  $e = [Int32]($j / 2)              # Half-to-even rounding is too bad.
  $f = [Int32](($j / 2) + 0.001)    # I like this result.
  $str = "{0,10}{1,28}" -f $e, $f
  Write-Host -NoNewline $str

  Start-Sleep -m 200
}
"`n"
Write-Host -NoNewline $showCursor

### Expected behavior

```console
$i    $a
----  ------
   0     0 |
   1     1
   2     1
   3     2 |
   4     2 |
   5     3
   6     3
   7     4 |
   8     4 |
   9     5
  10     5
  11     6 |
  12     6 |
  13     7
  14     7
  15     8 |
  16     8 |
  17     9
  18     9
  19    10 |
```

### Actual behavior

```console
$i    $a  
----  ------
   0     0 |
   1     0 |
   2     1  
   3     2 |
   4     2 |
   5     2 |
   6     3  
   7     4 |
   8     4 |
   9     4 |
  10     5  
  11     6 |
  12     6 |
  13     6 |
  14     7  
  15     8 |
  16     8 |
  17     8 |
  18     9  
  19    10 |
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Best take it up with the .NET folks, PowerShell follows the standard .NET rounding behaviour here.

If you'd rather a different rounding behaviour, you can use an overload of `[math]::Round()` to select an alternate rounding behaviour when rounding numbers for a calculation, but it's very unlikely PowerShell will change the default at this stage, especially because it would vary from the .NET default.

**Comment by iSazonov** [comment]
> PSVersion                      7.1.4

Please check with latest PowerShell 7.2 Preview and, if you can, please implement the same on C# and compare results.

**Comment by XValue** [comment]
Thanks.
