### ISSUE TITLE
Microsoft.PowerShjell.Commands.Management.dll missing from ref assemblies in SDK

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#16141]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When referencing the PowerShell SDK nuget package and trying to use the type Microsoft.PowerShell.Commands.ResolvePathCommand, the assembly is not found.

The ref directory is missing Microsoft.PowerShell.Commands.Management.dll, where the type is implemented.

```
    Directory: C:\Users\Staffan\.nuget\packages\microsoft.powershell.sdk\7.2.0-preview.9\ref\net6.0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2021-08-18    20:51         134656 Microsoft.PowerShell.Commands.Utility.dll
-a---          2021-08-18    19:41         576648 Microsoft.PowerShell.Commands.Utility.xml
-a---          2021-08-18    20:51           7168 Microsoft.PowerShell.ConsoleHost.dll
-a---          2021-08-18    19:41         166674 Microsoft.PowerShell.ConsoleHost.xml
-a---          2021-08-18    20:51         397312 System.Management.Automation.dll
-a---          2021-08-18    19:41        7651228 System.Management.Automation.xml
```

The same is true for the ref folder of the Microsoft.PowerShell.Commands.Management nuget package.
```
    Directory: C:\Users\Staffan\.nuget\packages\microsoft.powershell.commands.management\7.2.0-preview.9\ref\net6.0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2021-08-18    20:51         397312 System.Management.Automation.dll
-a---          2021-08-18    19:41        7651228 System.Management.Automation.xml

```

### Expected behavior

```console
Should be able to reference the SDK and use types from Microsoft.PowerShell.Commands.Management.
```

### Actual behavior

```console
Build error.
```

### Error details

```console
error CS0246: The type or namespace name 'ResolvePathCommand' could not be found (are you missing a using directive or an assembly reference?)
```
```


### Environment data

```powershell
Referenced the 7.2.0-preview9 SDK.
```

**Comment by powercode** [comment]
The code used to provoke the error is:

```csharp
    var iss = InitialSessionState.CreateDefault2();
    iss.Commands.Add(new SessionStateCmdletEntry("Resolve-Path", typeof(Microsoft.PowerShell.Commands.ResolvePathCommand), null));
```

The package reference:
```xml
<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.0-preview.9" />
```

**Comment by adityapatwardhan** [comment]
@powercode - I have verified the issue with the latest release v7.4.0-preview.2 and it is fixed. Please re-open if you still see the issue.

Fixed by https://github.com/PowerShell/PowerShell/pull/19302
