### ISSUE TITLE
Invoke-WebRequest not responding to «Ctrc+c»

### ISSUE THREAD

**Issue by 7-904-001-67-28** [PowerShell/PowerShell#16145]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with this comandlet.
I started it to downloading and turned off the router.  Comandlet hanged and hangs for more than 10 hours.
I think it should be breaked after I push «Ctrl+c», but it continue hanging.
Sorry my English.

### Expected behavior

```console
«Ctrl+c» – and Oll Korrect.
```

### Actual behavior

```console
Nothing changes.
```

### Error details

```console
I can not start the next command.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

I prepared the window of PowerShell and reduced the speed of the router to minimal:
![2021-09-23_12-46-50](https://user-images.githubusercontent.com/53446248/134578068-42ade46b-2db6-4e17-a228-ae6fd58dac89.png)
I pushed the «Enter»:
![2021-09-23_12-47-08](https://user-images.githubusercontent.com/53446248/134578104-8b0fa48b-2a57-433a-a844-e82ad77fc657.png)
I turned off the router:
![2021-09-23_12-47-24](https://user-images.githubusercontent.com/53446248/134578124-521521e6-f3b5-42c2-bd40-e102ce16145a.png)
Now I am trying unsuccessfully to stop it.

**Comment by iSazonov** [comment]
I can reproduce: start downloading an ISO and then disconnect Wi-Fi - PowerShell hang.

**Comment by 7-904-001-67-28** [comment]
If there is the VPN- or proxy-program **between** PowerShell and Internet, that program is returning the connection error and PowerShell by itself (without external intervention) is continue after 1-2 minutes with «`$_.Exception.HResult -EQ -2146232800`», «`$_.Exception.InnerException.ErrorCode -EQ 10053`» and «`$_.Exception.InnerException.Message -Like "Unable to read data from the transport connection: *"`».

**Comment by markekraus** [comment]
Even though we have `StopProcessing()` implemented, because we have `HttpClient.SendAsync()` being run synchronously.. I think it is blocking the cancellation.

https://github.com/PowerShell/PowerShell/blob/7cf1ef8c8599a90cd9579c7bb7b7676e097c4938/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1358
