### ISSUE TITLE
Powershell Script Html tags automatically capitalized and quotes removed from output

### ISSUE THREAD

**Issue by techyrajeev** [PowerShell/PowerShell#16157]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am using below powershell script to read an html file and wanted to modify certain tags with missing attributes.
```
$Source = Get-Content -path example.html -raw
$HTML = New-Object -Com "HTMLFile"
$HTML.IHTMLDocument2_write($Source)

$html.all.tags('HTML') |
	ForEach-Object{
		$_.document.documentElement.OuterHTML
	} | Out-File "test1.html"
```

I am facing a strange issue in which all tags gets capitalized and quotes are missing in final html file generated.

e.g 
1. `<div>` becomes `<DIV>`
2. `<p class="MListParagr" >`  becomes `<P class=MListParagr >`

I tried setting encoding as well but it didn't work as well
`$content | Out-File -Encoding utf8 "test1.html"`

Any idea how can I avoid the capitalization of HTML tags and also keep the attribute Quotes intact?

### Expected behavior

```console
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

### Actual behavior

```console
<HTML><HEAD>
<META content="text/html; charset=UTF-8" http-equiv=Content-Type>
<META name=Generator content="Microsoft Word 15 (filtered)">
<STYLE>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
> PSVersion                      5.1.19041.1237

The repository is only for PowerShell Core.  The scenario is not supported in PowerShell Core. So please use Windows Feedback tool to report the issue or discuss the issue on other resources.

**Comment by vexx32** [comment]
Aye. PowerShell is not and cannot be responsible for how COM objects behave, those are a completely external functionality built into Windows.
