### ISSUE TITLE
$env:PATH does not pick up settings in /etc/paths at startup on macOS

### ISSUE THREAD

**Issue by mcx808** [PowerShell/PowerShell#16151]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm using iTerm2 on macOS 11.8 and pwsh 7.1.4

I noticed an issue when I changed my iTerm default profile to run pwsh directly. Previously it would start zsh and issue the command pwsh, where my `$env:PATH` variable would match the `$PATH` variable of the zsh session that launched it.

When launching pwsh directly, the default `$env:PATH` value is `/usr/local/microsoft/powershell/7:/usr/bin:/bin:/usr/sbin:/sbin` and does not include any of the values specified in `/etc/paths` and `/etc/paths.d/`. 

I created a small workaround for now and added to my profile:
```
# Fix $env:PATH to include system paths. First turn the variable into an array
[System.Collections.ArrayList]$PATH = $env:PATH -split ':'
# Append the system paths 
$PATH += (Get-Content /etc/paths)
$PATH += (Get-ChildItem /etc/paths.d/ | ForEach-Object {Get-Content $_})
#Set the viariable
$env:PATH = ($PATH | Select-Object -Unique) -join ':' 
```

### Expected behavior

```console
$env:PATH should include the system entries from /etc/paths and /etc/paths.d/*, just like zsh (and likely bash) do.
```

### Actual behavior

```console
$env:PATH = /usr/local/microsoft/powershell/7:/usr/bin:/bin:/usr/sbin:/sbin
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by JamesWTruher** [comment]
@mcx808 
it's not clear in the issue how you're starting pwsh, but be sure to use -login when starting pwsh (or invoke with the tickbox for login shell).
here's an article that might help: 
https://stackoverflow.com/questions/1276703/how-to-make-zsh-run-as-a-login-shell-on-mac-os-x-in-iterm

**Comment by mcx808** [comment]
Hi @JamesWTruher, right you are.

I was starting pwsh by setting the command `/usr/local/microsoft/powershell/7/pwsh` as my powershell profile in iTerm2, and adding the `-login` switch does then set my $env:PATH correctly.

I'll add this screenshot of the correct setting for posterity:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/30801293/135605090-5c7cd201-66bd-4089-9456-26f93ea82753.png">

**Comment by rjmholt** [comment]
Just to add here:

- The /etc/paths behaviour only occurs for login shells
- pwsh supports this because it supports login shell behaviour by reusing zsh on macOS (it execs itself, so inherits all environment variables)
- However, you must ensure that pwsh is started as a login shell
- You can do this explicitly by passing `-l` as the first switch, or
- If you configure it as a login shell with `chsh` and add it to /etc/shells, the OS will start it with a `-` in the process name and it will infer that it's a login shell

**Comment by WeihanLi** [comment]
seems I could not make it works even I set it as default login shell or add the `-login` option

<img width="910" alt="image" src="https://github.com/user-attachments/assets/845e4186-6f35-4a87-81e4-7ca0b34488cf" />


<img width="469" alt="image" src="https://github.com/user-attachments/assets/0391ffe0-75d1-47a7-9773-208c69146cd8" />
