### ISSUE TITLE
Bug about format operator -f

### ISSUE THREAD

**Issue by XValue** [PowerShell/PowerShell#16150]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Bug about format operator -f

### Expected behavior

```console
PS> "{0:f1}" -f 0.35
0.4

PS> "{0:f2}" -f 0.075
0.08
```

### Actual behavior

```console
PS> "{0:f1}" -f 0.05
0.1
PS> "{0:f1}" -f 0.15
0.1
PS> "{0:f1}" -f 0.25
0.2
PS> "{0:f1}" -f 0.35
0.3
PS> "{0:f1}" -f 0.45
0.5
PS> "{0:f1}" -f 0.55
0.6
PS> "{0:f1}" -f 0.65
0.7
PS> "{0:f1}" -f 0.75
0.8
PS> "{0:f1}" -f 0.85
0.8
PS> "{0:f1}" -f 0.95
0.9


PS> "{0:f2}" -f 0.005
0.01
PS> "{0:f2}" -f 0.015
0.01
PS> "{0:f2}" -f 0.025
0.03
PS> "{0:f2}" -f 0.035
0.04
PS> "{0:f2}" -f 0.045
0.04
PS> "{0:f2}" -f 0.055
0.06
PS> "{0:f2}" -f 0.065
0.07
PS> "{0:f2}" -f 0.075
0.07
PS> "{0:f2}" -f 0.085
0.09
PS> "{0:f2}" -f 0.095
0.10
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
This is another instance of the default behavior of a dotnet API.  The format operator is essentially syntactic sugar for `[string]::Format('{0}', $arg)`.

```powershell
[string]::Format("{0:f1}", 0.05)
0.1
[string]::Format("{0:f1}", 0.15)
0.1
[string]::Format("{0:f1}", 0.25)
0.2
[string]::Format("{0:f1}", 0.35)
0.3
[string]::Format("{0:f1}", 0.45)
0.5
[string]::Format("{0:f1}", 0.55)
0.6
[string]::Format("{0:f1}", 0.65)
0.7
[string]::Format("{0:f1}", 0.75)
0.8
[string]::Format("{0:f1}", 0.85)
0.8
[string]::Format("{0:f1}", 0.95)
0.9


[string]::Format("{0:f2}", 0.005)
0.01
[string]::Format("{0:f2}", 0.015)
0.01
[string]::Format("{0:f2}", 0.025)
0.03
[string]::Format("{0:f2}", 0.035)
0.04
[string]::Format("{0:f2}", 0.045)
0.04
[string]::Format("{0:f2}", 0.055)
0.06
[string]::Format("{0:f2}", 0.065)
0.07
[string]::Format("{0:f2}", 0.075)
0.07
[string]::Format("{0:f2}", 0.085)
0.09
[string]::Format("{0:f2}", 0.095)
0.10
```

**Comment by jhoneill** [comment]
> This is another instance of the default behavior of a dotnet API. The format operator is essentially syntactic sugar for `[string]::Format('{0}', $arg)`.
> 
Just to confirm there's nothing special about the way PowerShell is passing things to the [string] , C# has the same behavior.

**Comment by SeeminglyScience** [comment]
Yeah, here's a [sharplab demo](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMAGAWAChcBGY4rUgTgAoq8A6AMQHtlIFaAiAbzxAAzUgF9ucAARM8AVgCUcgNyUa9UkzYcIXPgOFjJTUvKUq6DFu049+Q0eKmMcJ5SVUXN13XYOOAzC5mahpW2jZ69oaMACyBbubqllo6tvoOTDJxVAkhyeE+6YwAbFnuiZ5h3mlRAOylOUleqZGOABz1wY2Vzb5M1HFBHqEpeji9jHiyCq7ZnRUjQmOFeMbTg+XD+YJLUXjOa/Fzm1U7jngBB7NDeSfjeLGXZblNo3eZjw3zW6fSJR9HN1SPwmdX+1xeizu7TBG0Br2W/QOQA===) with the same output.
