### ISSUE TITLE
Resizing Wait-Event crashes PowerShell on macOS

### ISSUE THREAD

**Issue by yumaikas** [PowerShell/PowerShell#16174]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

0) Be on macOS Big Sur, Version 11.6
1) Launch a PowerShell session in Terminal.

2) Run `Wait-Event`, then stop it via Ctrl-C
3) Run. `Wait-Event` again, but resize the terminal.

### Expected behavior

```console
PowerShell doesn't exit
```

### Actual behavior

```console
Powershell exits on terminal resize. 

If the terminal is hosted inside Neovim, it shows shows "Process exited 130", 

If the terminal is only hosted inside of the macOS Terminal.app shows "[Process completed]"
```

### Error details

```console
(Nothing)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by yumaikas** [comment]
Of note, this issue gives me a lot of grief when I run long-running foreground commands in PowerShell in Neovim, like a custom file polling script I have. 

The above reproduces outside of that context.

**Comment by yumaikas** [comment]
Why does this have Issue-Question instead of Issue-Bug?

**Comment by iSazonov** [comment]
> Why does this have Issue-Question instead of Issue-Bug?

Work Group will do a conclusion.

Please update your repro steps (it is not clear about Neovim).

**Comment by yumaikas** [comment]
The repro steps are updated. Is there anything further I should do to help the WG be able to attack this? I can attempt to run PowerShell Core inside a debugger, and reproduce it there, though that will take some time.

**Comment by yumaikas** [comment]
So, I found out something curious about my setup that suggests this isn't a PowerShell specific bug:

I'd set up a pwsh.nologo script to act as my interactive shell with the following

```sh
#! /bin/zsh
/usr/local/bin pwsh -Login -nologo
```

I noticed that running this outside of a logo environment, didn't seem to run into the same error.

Switching it to:

```sh
#! /usr/local/bin/pwsh
/usr/local/bin/pwsh -Login -nologo
```

Seems to get rid of this bug. Unless you want something else from me, I'll close this issue in 48 hours.

**Comment by iSazonov** [comment]
I don't think we support `zsh`. /cc @rjmholt

**Comment by rjmholt** [comment]
Things should work running underneath another shell. I do that a lot on Linux myself.

However, for this issue it'd be nice to rule out this being caused by zsh interfering in some way.

I will say, I'm not sure why you'd want a login script to be a PowerShell script (with the pwsh shebang) that then calls PowerShell with arguments -- that means you're starting two PowerShell processes, one within another.

I'm fairly sure you can specify arguments in a shebang, but also I think you can give them in your login shell configuration (maybe in /etc/shells?).

**Comment by yumaikas** [comment]
I did do a decent amount of digging around trying to piece together how I got here, but this depth of customizing login shells is new territory for me, so there is a chance that I've missed something.

That being said, /bin/dash and /bin/sh both seem to not crash due to resizes, as well as /bin/pwsh, so it does look more related to zsh than pwsh.

**Comment by theJasonHelmick** [comment]
@yumaikas - Thanks for the issue - I haven't been able to reproduce this error using PowerShell 7.2.2 on MacOS using terminal or iTerm2.  Can you confirm?

**Comment by theJasonHelmick** [comment]
@yumaikas - thank you for the response -- It is possible that an upgrade to .NET may have fixed this.  We tried to repo on PowerShell 7.2.x and 7.3 -- the error did not reproduce.
