### ISSUE TITLE
PowerShell doesn't use the final target of a symbolic link when starting a process or running a native command on Windows

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#16171]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

**On Windows**

1. Open an elevated pwsh session, and create 2 symbolic links as follows in a folder:
    ```
    New-Item -ItemType SymbolicLink -Path pwsh-symlink -Value $pshome\pwsh.exe
    New-Item -ItemType SymbolicLink -Path pwsh-double-link -Value .\pwsh-symlink
    ```
3. Under the same folder, run `.\pwsh-symlink`, and you will see pwsh console window pops up.
4. Under the same folder, run `.\pwsh-double-link`, and you will see the "How do you want to open this file" window pops up.

> Note: `Start-Process` doesn't use the final target of a symbolic link either.

----------------------

However, **it works fine on Unix**

1. Create 2 symbolic links as follows in a folder:
    ```
    /bin/ln -s /opt/microsoft/powershell/7/pwsh pwsh-link
    /bin/ln -s /home/<user>/tmp/pwsh-link /home/<user>/tmp/pwsh-double
    ```
2. Under the same folder, run `./pwsh-link -c 1+1`, and you will get `2` printed out as the result.
3. Under the same folder, run `./pwsh-double -c 1+1`, and you will get `2` printed out as the result.

### Expected behavior

```console
On Windows:
1. pwsh should know that `pwsh-symlink` is actually a console application, and run into with the current console.
2. pwsh should be able to run `pwsh-double-link`, just like on Unix platforms.
```

### Actual behavior

```console
On Windows
1. pwsh opens `pwsh-symlink` in a separate console window, which means it doesn't use the link target to check if it's a console application, and thus starts the process with 'UseShellExecute = true'.
2. pwsh cannot run `pwsh-double-link`, because when using `UseShellExecute`, the Shell automatically uses the immediate link target of a symbolic link file, but doesn't do recursive resolution when the immediate link target is again a symbolic link.
```

### Environment data

```powershell
The latest build from master, and happen on all 7.2.0-preview.9 as well
```

### Visuals

![image](https://user-images.githubusercontent.com/127450/135180968-dc1fc21c-94db-4c11-a4f9-c02a42c9be4f.png)

![image](https://user-images.githubusercontent.com/127450/135180988-ff7ddcad-b0b6-46c9-aac7-e8e9a5cda252.png)

**Comment by iSazonov** [comment]
What is cmd.exe behavior?

**Comment by vexx32** [comment]
This feels related to another issue we discussed in the Engine WG a bit ago where on Unix the PowerShellNative code deliberately seems to _fully_ resolve symlinks and show the final target in output from Get-ChildItem whereas on Windows it only shows the next symlink target if there is a chain of symlinks.

**Comment by iSazonov** [comment]
> his feels related to another issue we discussed in the Engine WG

I did not found the issue :-(

**Comment by vexx32** [comment]
Let me see if I can dig it up... here: https://github.com/PowerShell/PowerShell/issues/13365

**Comment by daxian-dbw** [comment]
@vexx32 Yeah, but that will be resolved after we move to using `LinkTarget` property added in .NET 6.
pwsh doesn't resolve a symbolic link when dealing with native command or `Start-Process`, so on Unix plats, I think OS does the work.

**Comment by daxian-dbw** [comment]
> We shouldn't regress in .\file.txt scenario if we will fix the issue.

@iSazonov You'd better be specific on what scenario that is :) (link to an issue?).

**Comment by iSazonov** [comment]
> > We shouldn't regress in .\file.txt scenario if we will fix the issue.
> 
> @iSazonov You'd better be specific on what scenario that is :) (link to an issue?).

` .\file.txt` on Windows opens Notepad. If we will update the code we should add new tests for the scenario with symlinks in path.

**Comment by iSazonov** [comment]
> @vexx32 Yeah, but that will be resolved after we move to using `LinkTarget` property added in .NET 6. pwsh doesn't resolve a symbolic link when dealing with native command or `Start-Process`, so on Unix plats, I think OS does the work.

I wonder if cmd.exe resolves :-) If so isn't this a problem with the .Net API (Process class)?

**Comment by jborean93** [comment]
It looks like [CreateProcess](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) is unable to resolve symbolic links whereas [ShellExecute](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew) attempts to resolve the first target of a symlink before it creates the process. You can see this in action when using explorer or PowerShell to start a symlink that points directly to an executable (the commandline is the resolved path)

![image](https://user-images.githubusercontent.com/8462645/135355689-db4891c0-fb61-4f3c-b72f-831640ef8e42.png)

In this example I used PowerShell to start `C:\temp\link2` which is a symlink that targets `C:\Windows\System32\cmd.exe`. The same applies to starting a symlink in explorer.

If I was to manually call `CreateProcess` directly with the link as the file path it fails:

![image](https://user-images.githubusercontent.com/8462645/135355892-fcc8558c-6afa-4019-927c-0babbc88fe06.png)

Whereas a manual call to `ShellExecute` works just a simple symlink

![image](https://user-images.githubusercontent.com/8462645/135356174-d04201a0-544c-406e-92eb-5c5f3f565199.png)

But a call to `ShellExecute` with multiple link targets will cause the shell open dialogue box as reported by this issue (and what explorer does)

![image](https://user-images.githubusercontent.com/8462645/135356289-656fafb2-96f7-4c2c-a147-b3d7483d8914.png)

So if this is something that PowerShell wishes to support then it will most likely have to continue resolving the link paths until it reaches the end target before it is invoked so it works for both scenarios.

**Comment by iSazonov** [comment]
I think it makes sense to open new issue in .Net Runtime repo since we use Process.Start() too.

**Comment by JamesWTruher** [comment]
WG: we agree that this may be a bug, but we would like to wait at present for more investigation.

**Comment by SaschaWeisenberger** [comment]
Hi, I have the same problem with tools installed via winget.
Symlinks are created under C:\Users\<user>\AppData\Local\Microsoft\WinGet\Links\ but the target is never resolved.
In my case it was the tool scrcpy (https://github.com/Genymobile/scrcpy). 
```pwsh
PS C:\> where.exe scrcpy
C:\Users\<user>\AppData\Local\Microsoft\WinGet\Links\scrcpy.exe

PS C:\Users\<user>\AppData\Local\Microsoft\WinGet\Links> get-Item scrcpy.exe | select -ExpandProperty Target
C:\Users\<user>\AppData\Local\Microsoft\WinGet\Packages\Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe\scrcpy-win64-v2.0\scrcpy.exe
```

**Comment by Renari** [comment]
This should really be reopened, this still happens and it's really annoying.
