### ISSUE TITLE
Distribution Support Request - Debian 11 AMD64

### ISSUE THREAD

**Issue by singingtelegram** [PowerShell/PowerShell#16182]
### Name of the Distribution

Debian

### Version of the Distribution

11

### Package Types

- [X] Deb
- [ ] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

amd64

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by singingtelegram** [comment]
Debian 11 is supported as of the v7.1.4 release, however the PowerShell package is not included in [Microsoft's Debian 11 repo](https://packages.microsoft.com/debian/11/prod/).

**Comment by kasini3000** [comment]
I have already written a one-click installation script for debian11.
https://gitee.com/chuanjiao10/kasini3000_agent_linux/blob/master/debian11_install_powershell.bash
Of course, it is still not working properly. After this issue is done, welcome to help test my script.


Look forward to powershell to support debian11 soon.

**Comment by nanonyme** [comment]
I guess this is basically same thing as https://github.com/PowerShell/PowerShell/issues/16114

**Comment by kasini3000** [comment]
hi all: 
package for debian11 already done. up one click script work fine, tested!
no more problem ?  then close this issuse .

**Comment by kasini3000** [comment]
hi all: 
package for debian11 already done. up one click script work fine, tested!
no more problem ?  then close this issuse .

**Comment by nanonyme** [comment]
@kasini3000 this ticket is done when Microsoft repository for Debian packages has Power shell package for Debian 11. Last I checked the package was missing .
