### ISSUE TITLE
Using ToString on DateTime object after using AddDays produces incorrect month

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [PowerShell/PowerShell#16187]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PS>  $d = [DateTime]::ParseExact('2020-01-01', 'yyyy-mm-dd', $null)
PS> $d = $d.AddDays(31)
PS> $d; $d.ToString('yyyy-mm-dd'); $d.GetDateTimeFormats()[0]

### Expected behavior

```console
February 1, 2020 12:01:00 AM
2020-02-01
2020-02-01
```

### Actual behavior

```console
February 1, 2020 12:01:00 AM
2020-01-01
2020-02-01
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
`'yyyy-mm-dd'` -- year-minutes-days

**Comment by bigboy-pdb-spam** [comment]
Thanks. I had assumed that "mm" would be month since "%m" is for month.
