### ISSUE TITLE
Copy-Item -exclude doesn't work recursevly

### ISSUE THREAD

**Issue by ediulia** [PowerShell/PowerShell#16192]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to copy the directory with the content but want to exclude some child folders. Copy-Item applies the Exclude on the root level only

Example:
$ExcludeFolder="x"
$Source = "c:\temp"
$Destination = "d:\temp"
set-location $Source
Copy-Item * -exclude $ExcludeFolder -force -recurce -destination $Destination -verbose

$Source folders:
-->Folder 1
---->>Folder 1.1
---->>Folder 1.2
---->>Folder x
-->Folder 2
---->>Folder 2.1
---->>Folder 2.2
---->>Folder x
-->Folder x
---->>Folder x.1
---->>Folder x.2
---->>Folder x

$Destination folders:
-->empty

### Expected behavior

```console
$Destination folders:
-->Folder 1
---->>Folder 1.1
---->>Folder 1.2

-->Folder 2
---->>Folder 2.1
---->>Folder 2.2
```

### Actual behavior

```console
$Destination folders:
-->Folder 1
---->>Folder 1.1
---->>Folder 1.2
---->>Folder x
-->Folder 2
---->>Folder 2.1
---->>Folder 2.2
---->>Folder x
```

### Error details

```console
no errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Exclude and Include parameters is used in some cmdlets and we should have the same behavior for all of them. Ex., see #15159.
