### ISSUE TITLE
Add processor architecture information in $PSVersionTable

### ISSUE THREAD

**Issue by mcfi** [PowerShell/PowerShell#16209]
### Summary of the new feature / enhancement

Both x64 and ARM64 powershells can now run side-by-side on windows 11 on ARM64.  To better differentiate one from the other, for example, when accessing different registry keys, or loading dlls of different architectures, it is recommended to have a processor architecture field in the $PSVersionTable. This way, the cmdlets don't need to issue Windows API calls to determine the architecture of the powershell process.

**Comment by iSazonov** [comment]
If we consider PS modules too we need to request .Net Runtime to enhance System.Reflection.ProcessorArchitecture with ARM64 or migrate to another API in https://github.com/PowerShell/PowerShell/blob/e98a8c8601b8f15f479e894323beafb9f6a2300c/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs#L1854
(For reference #11046)
