### ISSUE TITLE
Copy-Item with -Include and -Recurse doesn't work

### ISSUE THREAD

**Issue by Karl255** [PowerShell/PowerShell#16219]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying to recursively copy specific files from a folder with this command:
```ps
Copy .\input -Destination .\output -Recurse -Include ("*.txt", "*.json")
```
Nothing gets copied whatsoever.

If I use `-Filter` instead and only specify one file type filter like:
```ps
Copy .\input -Destination .\output -Recurse -Filter "*.txt"
```
This works, copies all .txt files, keeps the folder structure AND even copies empty folders (with `-Include` *nothing* got copied at all).

### Expected behavior

```console
(for the first command) Files which fit any of the given filters get copied together with the whole folder structure (even empty folder, like with `-Filter`).
```

### Actual behavior

```console
Nothing gets copied.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets reviewed this.  The cmdlet is working as designed although we agree in a non-obvious kind of way.  Unfortunately `Get-ChildItem` and `Copy-Item` seem to treat `-Include` differently when `-Recurse` is used as `Copy-Item` applies `-Include` to `-Path` to enumerate recursively, while `Get-ChildItem` applies it after recursion.  As we expect existing users to be dependent on the current behavior, we recommend that no change should be made as it would result in breaking existing scripts.  Instead, this should be a doc issue making more clear how `-Include` and `-Exclude` is applied (today it merely says these parameters "qualify the Path parameter") and having some specific examples where the current behavior would be used.  Use of `-Filter` instead is the appropriate way to solve the original issue.

Created https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8601

**Comment by Karl255** [comment]
Thank you for your answer! I understand what `-Include` does now. Useful when using a wildcard for `-Path`.

> Use of `-Filter` instead is the appropriate way to solve the original issue.
The problem with `-Filter` is that it only accept one filter, which means I'd need to run several similar commands if I wanted to copy several specific file types. A `-Filters` parameter would be a good solution, user-wise at least.

**Comment by iSazonov** [comment]
> The cmdlet is working **as designed** although we agree in a non-obvious kind of way.

If you make such a conclusion there must be a **valid reason** without which the described behavior of the cmdlet is an obvious bug.

> The cmdlet is working as designed although we agree in a **non-obvious** kind of way.

From https://en.wikipedia.org/wiki/Software_bug
>A software bug is an error, flaw or fault in computer software that causes it to produce an incorrect or **unexpected result**, or **to behave in unintended ways**.

Are you going to argue that **every** user **expects** the next command to do **nothing**?
```powershell
Copy-Item c:\ d:\  -Include *.* -Recurse
```
I don't think anyone from the WG would risk even a cent against it :-)

In reality, users expect quite the opposite and have been forced to use workarounds for years in the form of `dir -recurse | copy-item`.
You can find countless examples of these on GitHub or at least look at follow
https://stackoverflow.com/questions/5432290/how-to-use-powershell-copy-item-and-keep-structure
https://stackoverflow.com/questions/18616581/how-to-properly-filter-multiple-strings-in-a-powershell-copy-script 

> As we expect existing users to be dependent on the current behavior, we recommend that no change should be made as it would result in breaking existing scripts.

After that you will still claim that someone is scripting on this absurd behavior?

Finally, I would really like to see the rationale behind **this design** - why do Get-ChildItem and Remove-Item behave differently with Include/Exclude than Copy-Item? 
Voting 2 vs 1. :-)

---
After reviewing the existing issues and documentation, I found many contradictions and ambiguities concerning Providers. The only way I see to put things in order is to clearly describe the basic principles in RFC (that I've been working on for the last few days).
Now I'm at a loss, how would you describe how filters work in PowerShell? "PowerShell Provider Engine implements include and exclude filters with follow behavior ...". 
Based on the WG's conclusion it would be "don't even try to guess". :-)

---
I am concerned about this precedent. I think it's more for WG-Engine-Providers than WG-Cmdlets-Management.
Look, this is not the problem of one cmdlet https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+is%3Aopen+Include+label%3AArea-FileSystem-Provider

**Comment by iSazonov** [comment]
It's really for WG-Engine-Providers.

We must get answers to _fundamental_ questions. Are these parameters proprietary to the engine or to cmdlets? If cmdlets then this leads to absurdly different behavior as we can see. Furthermore they are not individual cmdlets but Provider cmdlets, i.e. the cmdlets themselves are part of the PowerShell Provider Engine API - the developers do not implement these cmdlets, only the providers. So these parameters are still the property of the PowerShell Provider Engine which should define their unambiguous semantics for all kinds of providers, right? Then we should expect the parameters to work the same for all cmdlets. On the other hand if we look at the implementation we see a lot of flexibility, these parameters are saved in a CmdletProviderContext which unexpectedly contains these parameters and is not immutable! We see two consequences. Firstly, the provider can use the values of these parameters and create a different behavior than the engine. Using these parameters may be justified by their more efficient implementation, but deviations in behavior are unacceptable. Therefore we need mandatory tests for all providers which protect generic behaviors. Second, any provider's implementation can change values of these parameters on the fly, changing the behavior of the engine itself and even the behavior of other providers! This is also unacceptable and the engine should be modified to prevent this.

Recursion problem was discussed in #15159 at length without final conclusion. While implementation of globstart/pathspecs looks enticing this is extremely difficult to implement and difficult to use.
If we look at the implementation of recursion in .Net, there are two predicates - ShouldRecurse and ShouldInclude. Both predicates have full access to the _current_ Item. It is intuitively clear what they are doing.
In essence, we need exactly these two operations too - _anything else is just misleading_.
This leads us to agree that these parameters (Include/Exclude) work as ShouldInclude predicate - _it likely falls into bucket 3 (unlikely grey area)_.
We can not convert Recurse parameter in ShouldRecurse  predicate it would be hug breaking change. Really Recurse  works as `ShouldRecurse  *`. Does this remind you of anything? For example, the Path parameter with globbing support? :-) 
I can assume that this is enough for most typical scenarios. If you need something more than globbing in Path parameter, I'd rather consider new parameters (ShouldRecurse  and ShouldInclude) in the form of _script filter functions_ that take the current _item_ as a parameter (ex., like FileInfo). This is of course slower than the native implementation, but still noticeably faster than the current globbig implementation.
_So the minimum we need to do to put things in order is to admit that the parameters (Include/Exclude) work exclusively as ShouldInclude predicate and uniformly for all cmdlets._
