### ISSUE TITLE
Please release MSIX packages to GitHub.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [PowerShell/PowerShell#16213]
### Summary of the new feature / enhancement

Please upload MSIX packages for Windows PowerShell to the Assets section of every subsequent release of Windows PowerShell that shall be available via Github.

### Proposed technical implementation details (optional)

Upload the versions that are released to the Microsoft Store.

**Comment by adityapatwardhan** [comment]
MSIX apps are by default sandboxed and do not have full access to the machine registry. PowerShell needs full access to the registry to operate correctly. Having a PowerShell MSIX package which installs correctly without the Store is not supported right now. Are you asking for a sandboxed MSIX package?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@adityapatwardhan, creation and installation of MSIX-packages that are able able to utilise all system-resources is possible. Actually, installation of them via Microsoft Store is – or was until recently, if what you have stated is correct – not possible.

Research the ‘runFullTrust’ capability. Additionally, because PowerShell has already been distributed via the Microsoft Store at ‘http://microsoft.com/p/powershell/9mz1snwt0n5d’, I am confident that PowerShell has been packaged as MSIX. My sole proposition is addition of this to ‘http://github.com/PowerShell/PowerShell/releases’.

**Comment by SteveL-MSFT** [comment]
This should now be fixed starting with 7.2.2 and 7.3 preview 3
