### ISSUE TITLE
Get-PhysicalDisk cannot get disk when it run at a windows services

### ISSUE THREAD

**Issue by gland2015** [PowerShell/PowerShell#16226]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

write a c# program and regiser as windows service, and use powershell module execute "Get-PhysicalDisk" command

### Expected behavior

```console
1
```

### Actual behavior

```console
it is not return any
```

### Error details

```console
1
```

### Environment data

```powershell
1
```

### Visuals

1

**Comment by jborean93** [comment]
Weird, what's the full output you get back when trying to run it? If it's an error can you also run `$Error[0] | Select *` afterwards and share that output?

**Comment by jborean93** [comment]
How is your service running the command, is it creating a new process calling `pwsh -Command Get-PhysicalDisk` or is it using the `System.Management.Automation` API to spin up a new pipeline?

**Comment by jborean93** [comment]
Did you check with `ps.Streams.Error` to see if there are any errors in there. Because you are using the API you won't get errors through the `Invoke()` output as that's reserved for actual output of the cmdlet. I would also just simplify things by just invoking `ps.AddScript("Get-PhysicalDisk")` to rule out any other problems.

**Comment by gland2015** [comment]
your windows service is ok? There are many error here.

**Comment by gland2015** [comment]
so why it return nothing? when it is a ordinary program, it is work. when it is windows service, it not work. @jborean93

**Comment by jborean93** [comment]
I dont know, you shared a json as a comment and I assumed it just started working. What’s the context behind that message, did you check the error streams, did you try just calling the cmdlets withiut any of the extra calls you add on top.

**Comment by iSazonov** [comment]
Based on jborean93's thoughts I guess a root of the issue could be in the fact that Windows service has not a console.

**Comment by gland2015** [comment]
but Get-Disk / Mount-Disk / Get-Volume is return disk info at windows service. @iSazonov

**Comment by gland2015** [comment]
you should write a c# service, using System.Management.Automation API. @jborean93

**Comment by gland2015** [comment]
actually, Get-Disk replace Get-PhysicalDisk, so I want to know after execute "Import-Module Storage",  when execute "Get-Disk" twice,  The first execution takes twice as long as the second. @jborean93

**Comment by lostmsu** [comment]
Not sure if it is of any use, but I faced potentially related problem with `Get-PhysicalDisk` in 7.2.5 (have not tried other versions) called from a desktop C# app via SDK, where it would seemingly randomly return empty collection without any errors within the same program run. If anyone is interested in looking into it, I can try capturing a memory dump when that happens.

My setup is
```csharp
Runspace.DefaultRunspace = RunspaceFactory.CreateRunspace();
Runspace.DefaultRunspace.Open();

using var ps = PowerShell.Create(RunspaceMode.CurrentRunspace);
ps.AddCommand("Set-ExecutionPolicy")
    .AddParameter("ExecutionPolicy", "RemoteSigned")
    .AddParameter("Scope", "Process")
    .Invoke();
```
the first thing upon program startup (literally the first lines of `Main`)

Then I a launch a separate `Background==true` thread for all `Get-PhysicalDisk` calls that boils down to this:

```csharp
var runspace = RunspaceFactory.CreateRunspace();
runspace.Name = Invariant($"Runspace-{this.Name}");
runspace.Open();

Runspace.DefaultRunspace = runspace;

while (true) {
   WaitForRequestToRunGetPhysicalDisk();

    using var ps = PowerShell.Create();
    ps.AddCommand("Get-PhysicalDisk");
    var results = ps.Invoke();
    if (ps.HadErrors) throw new Exception(ps.Streams.Error);
    Debug.Assert(results.Count > 0); // this fails now and then

  SendResultToRequester(results);
}
```
