### ISSUE TITLE
Add `-UserAgent` parameter to `Start-BitsTransfer`

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#16239]
### Summary of the new feature / enhancement

BITS has many advantages over the `Invoke-WebRequest` cmdlet, but there doesn't seem to be any way to set a custom `User-Agent` header, like `Invoke-WebRequest` has (`-UserAgent`).

This means that whenever I'm downloading a file from a server where I need to change my `User-Agent` (e.g. some software distribution sites provide the file directly for well-known user agents like `Wget`, but show a website with download button for other user agents), I have to use `Invoke-WebRequest` instead of `Start-BitsTransfer`.

Would it be possible to add a similar parameter to `Start-BitsTransfer`?

**Comment by iSazonov** [comment]
`Start-BitsTransfer` is not in the repo. Please use Windows Feedback tool and other channels to request new feature.
