### ISSUE TITLE
Disable update check on startup

### ISSUE THREAD

**Issue by minusium** [PowerShell/PowerShell#16234]
### Summary of the new feature / enhancement

Hey, using a network inspector, I realized that Powershell sends a request to Microsoft servers on startup and I guess it's an update check, because once I get a notification on startup that there's a new Powershell version available. However, I don't like this behavior, and as I installed it from Microsoft Store I'll know if there's an update from there. I have some delay when I start Powershell (It's slow to show prompt and execute first command) so if there was a way to disable this it would help to reduce this delay.

**Comment by daxian-dbw** [comment]
Check out the configuration from the [about_Update Notification doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.2#long-description).

**Comment by minusium** [comment]
According to [this](https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging.md#disabling-managed-attachdebugging) page setting `COMPlus_EnableDiagnostics` to `0` disables debugger on .NET Core/.NET 5/.NET 6 apps. I had this problem. If you are a .NET programmer don't add it to environment variables or you'll have problem.
@JanRK @Northman-de
