### ISSUE TITLE
Why doesn't Alt+F4 close a powershell window ?

### ISSUE THREAD

**Issue by adamency** [PowerShell/PowerShell#16236]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I know about workarounds for this issue, but just wanted to get an actual answer as to the reasoning behind this choice in powershell, especially considering windows terminal has "[added](https://github.com/microsoft/terminal/pull/2526)" this functionality back in 2019 and it also work in legacy cmd.exe . Why is powershell still preventing this feature, contrasting with now all other microsoft programs ?

As per my research, there has been no public explanation for it and not a single visible issue deals with the topic here.

Please explain this decision and consider reverting the normal behavior.

### Expected behavior

```console
- Open a powershell window.
- Hit Alt+F4
- Powershell window should close.
```

### Actual behavior

```console
- Open a powershell window.
- Hit Alt+F4
- Powershell window doesn't close.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
Thank you @adamency - Alt+F4 DOES work in cmd.exe and terminal in Windows 11, however in our testing Windows 10 did have issues with consoleHost.
