### ISSUE TITLE
After execute "Import-Module Storage", Run "Get-Disk" twice, the first execution takes twice as long as the second

### ISSUE THREAD

**Issue by gland2015** [PowerShell/PowerShell#16242]
### Summary of the new feature / enhancement

After execute "Import-Module Storage", Run "Get-Disk" twice, the first execution takes twice as long as the second, this is why, Does anyone know?

**Comment by daxian-dbw** [comment]
It's probably because the first `Get-Disk` is a cold execution (fresh without caching), while the second is a warn execution (with caching made available from the 1st run).

**Comment by doctordns** [comment]
What would `Get-Disk` cache to make the second run faster? Just curious as to who is caching what and where.

**Comment by daxian-dbw** [comment]
That could be the internal implementation details of the `Get-Disk` cmdlet. Given that it's a CDXML module, it probably would be some implementation details of the WMI provider.
