### ISSUE TITLE
Enable shortcut CTRL + D to close Powershell

### ISSUE THREAD

**Issue by mathysie** [PowerShell/PowerShell#16256]
### Summary of the new feature / enhancement

In bash shell and other shells regularly found on Ubuntu systems, there is a shortcut CTRL + D to close the shell. In Powershell you have to enter the command `exit` or close the shell by a mouse click.

As I work with both bash shells and Powershell, my muscle memory first hits CTRL + D. Then, when there is no reaction from Powershell, I have to do additionally 5 keypresses to type `exit` and hit enter.

It's a minor annoyance, but it would help the quality of life for people working with both shells.

### Proposed technical implementation details (optional)

After hitting CTRL + D in Powershell, the shell must close. Just like bash shells.

**Comment by jhoneill** [comment]
just add this to your PowerShell profile
Set-PSReadLineKeyHandler -Chord 'Ctrl+d' -ScriptBlock { [System.Environment]::Exit(0) }

**Comment by teknoraver** [comment]
Yes, this works on Linux, it just have a small glitch described here: #16466

**Comment by mathysie** [comment]
@jhoneill thank you for the command! However as the command is not trivial, it feels like a workaround. Especially the less experienced PowerShell who switch often between bash and PS will appreciate CTRL + D as a standard shortcut, as they have no means of knowing adding a key handler to the profile is possible.

**Comment by jhoneill** [comment]
IIRC, in the Unix world Ctrl +D is the end of file marker  so ctrl + D will tell many programs from the unix world "no more input" and they terminate. 
End-of-file does that on Windows too, but  CP/M used Ctrl+Z , DOS copied that and so did Windows so  Ctrl Z [enter] gets you out of nslookup and similar programs that take piped input 
CMD and Windows PowerShell don't work that way, and I'm guessing the  behaviour carried over into pwsh.  So end of file won't close things, but you can any key combo a  short cut for exit. (Much childish fun can be had with _that_)

Should ctrl D ==> exit be a  default if PS-Readline see' it's on linux ? I can see the case for that on the grounds it's what a linux users expects of a a shell, but I wouldn't change what Windows users are used to.
