### ISSUE TITLE
"PowerShell.exe /?" is attempting reconnect on Nano server.

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PowerShell#1626]
## Steps to reproduce
- Install powershell-6.0.0-alpha.7-win10-x64 on Nano server 

[10.83.183.124]: PS C:\Users\Administrator\Documents\powershell-6.0.0-alpha.7-win10-x64\powershell-6.0.0-alpha.7-win10-x64> .\powershell.exe /?
WARNING: The network connection to 10.83.183.124 has been interrupted. Attempting to reconnect for up to 4 minutes...
WARNING: Attempting to reconnect to 10.83.183.124 ...
WARNING: Attempting to reconnect to 10.83.183.124 ...
WARNING: Attempting to reconnect to 10.83.183.124 ...
WARNING: Attempting to reconnect to 10.83.183.124 ...
WARNING: Attempting to reconnect to 10.83.183.124 ...
WARNING: The reconnection attempt to 10.83.183.124 failed. Attempting to disconnect the session...
WARNING: Computer 10.83.183.124 has been successfully disconnected.
The running command has been disconnected but is still running on the remote server.  Reconnect to get command operation status and output data.
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException

**Comment by joeyaiello** [comment]
@SteveL-MSFT do you have a Nano container handy to try a repro here? My hunch is this is either fixed or irrelevant.

**Comment by SteveL-MSFT** [comment]
@joeyaiello this doesn't repro with latest Nano Server as a container with beta.1 (and my [fix](https://github.com/PowerShell/PowerShell/issues/3463) for PSReadline)
