### ISSUE TITLE
`clip` alias for `Set-Clipboard`

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/PowerShell#16260]
### Summary of the new feature / enhancement

I love `clip`! It works on Windows, but not on Mac. Can we get an alias for `clip` to `Set-Clipboard`? I didn't even realize that `Set-Clipboard` worked until someone highlighted it in a chat room.

Would be great for have an xplat alias for clip. On Mac, I had to research and find some mclip thing.

**Comment by potatoqualitee** [comment]
Sure, but we do offer some built-in alises. `sls`, for example. I found out yesterday that the current alias for `Set-Clipboard` is `scb`. Perhaps that can be changed to `clip` instead? My profile currently sets `clip` to `pbclip`, but it would be nice to have it universally available and set to `Set-Clipboard` instead.

**Comment by potatoqualitee** [comment]
That response seems unnecessary, as I've demonstrated throughout my comments that I'm aware that aliases can be made. I would have appreciated a more substantial comment to end the conversation.

**Comment by iSazonov** [comment]
> Sure, but we do offer some built-in alises. `sls`, for example.

The conclusion was to remove conflicting aliases, but keep the rest for backward compatibility, and not to add new aliases in PowerShell distribution.

**Comment by potatoqualitee** [comment]
Ahh I'd forgotten about that, thanks @iSazonov
