### ISSUE TITLE
Failed to create CoreCLR, HRESEULT: 0x80004005 - PowerShell 7.2.0 on Windows 11 Dev

### ISSUE THREAD

**Issue by Echo64** [PowerShell/PowerShell#16288]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- Open PowerShell 7.2.0 Preview using default "Window Console Host"
- It immediately crashes

-----

- Open PowerShell 7.2.0 Preview using "Windows Terminal"
(either through setting Terminal as the default console or opening a tab within Terminal)
- The error message below is immediately displayed

### Expected behavior

```console
PowerShell 7.2.0-preview.10
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\*****>
```

### Actual behavior

```console
When using Windows Terminal, PowerShell immediately opens with an error and doesn't allow me to continue.

When starting PowerShell using the normal console host it immediately crashes.
```

### Error details

```console
Failed to create CoreCLR, HRESULT: 0x80004005

[process exited with code 2147516553]
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

(Unable to get to this point, it doesn't allow me to type anything in. This is copied from another computer with the same preview version, the only thing different (AFAIK) is that I'm running the latest Windows 11 Dev build instead of 10.)
```

### Visuals

![Screenshot 2021-10-21 135720](https://user-images.githubusercontent.com/8850780/138323330-00178fd4-ea5f-4083-988b-0a5b7614f3e8.png)

**Comment by daxian-dbw** [comment]
@Echo64 This CLR exception happens usually when CLR failed to create the named pipes for debugging and profiling in the `TMP` folder, see details in https://github.com/PowerShell/PowerShell/issues/13166#issuecomment-660358397. 

Can you try disabling CoreCLR diagnostics by setting the environment variable `export COMPlus_EnableDiagnostics=0` (as [instructed here](https://github.com/dotnet/coreclr/pull/15878)), and then try running your repro step again to see if that helps.
