### ISSUE TITLE
Invoke-RestMethod doesn't include automatic ContentType value when not using POST method

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#16318]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using a POST, ContentType is automatically set to `application/x-www-form-urlencoded`
```
 invoke-restmethod https://webhook.site/6a5097af-3644-4462-9d92-d910088d2f4d -Method POST -Body @{ Test = "test" }
```

When using other methods, it is not. It is blank. 

```
 invoke-restmethod https://webhook.site/6a5097af-3644-4462-9d92-d910088d2f4d -Method PUT -Body @{ Test = "test" }
```

![image](https://user-images.githubusercontent.com/1256531/139143331-e82931e0-d02e-4c7a-b3c8-c436d0565e3a.png)

### Expected behavior

```console
I would expect that the content type would default to form encoded for all request methods (or at least for PUT). 
```

### Actual behavior

```console
It is only set to form encoded for POST.
```

### Error details

```console
No errors.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-rc.1
PSEdition                      Core
GitCommitId                    7.2.0-rc.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by iSazonov** [comment]
@CarloToso I think yes but first we should look that is difference POST and PUT (maybe an RFC block this?) and what is behavior other utilities.

**Comment by CarloToso** [comment]
Curl doesn't add any Content-Type for POST and PUT

**Comment by iSazonov** [comment]
Search returns follow description:
> The difference between POST and PUT is that PUT requests are idempotent. That is, calling the same PUT request multiple times will always produce the same result. In contrast, calling a POST request repeatedly have side effects of creating the same resource multiple times.

Based on this, I think we should PUT must works as POST and we should add ContentType in PUT.
First, though, I would look at the implementation/workings of HttpClient and our web cmdlets to understand the source of the problem - either we add the ContentType ourselves or it's the HttpClientHandler that does it.

**Comment by CarloToso** [comment]
If -Headers and -ContentType are not set and  -Method is not POST or PUT --> No content type else "application/x-www-form-urlencoded"

Currently ContentType is set by:
- FillRequestStream (from -Headers or -ContentType or "application/x-www-form-urlencoded")
- GetMultipartStreamContent ("application/octet-stream")

ContentType has the precedence if both -Headers and -ContenType are present.

HttpClient gets the content type from the request.Content that often is ByteArrayContent that has no content type.
