### ISSUE TITLE
Expand *Action common parameters to allow a scriptblock

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#16314]
### Summary of the new feature / enhancement

As a Scripter, I want to better control ErrorAction, WarningAction etc by adding a Scriptblock option and additional *ActionScriptblock parameters to reduce potential lost context

**Comment by jhoneill** [comment]
> Why can't this be calculated before the cmdlet is executed? Please add more info and examples.

I guess the situation would be something like 
Send-money -account $a -value $v -confirm:{$NewBalance -lt -100}

**Comment by jdhitsolutions** [comment]
Under review with the Cmdlet Working Group

**Comment by jhoneill** [comment]
Reading my response above, I think I may have misread the original request at the time. 

We have `try / catch` and `trap`  but they don't handle *allow multiple errors to occur and process each one* scenarios. 

I'd like to see an example of something which is wanted in practice, but impossible or unwieldy with what we have

**Comment by jhoneill** [comment]
The working group have discussed this, and for now won't be taking the idea forward. At moment we can see an appeal in theory, but the limitations on where a script block can run after an error, and what it would be able access mean that we don't see significant benefit being delivered in practice. If examples appear which change that view, we may revisit this decision
