### ISSUE TITLE
Getting content and redirecting to the same file in a single command

### ISSUE THREAD

**Issue by Quaentor** [PowerShell/PowerShell#16331]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```console
PS> "hello" > o
PS> (Get-Content o) > o
```

### Expected behavior

```console
PS> Get-Content o
hello
```

### Actual behavior

```console
PS> Get-Content o
```

### Environment data

```powershell
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Isn't the first thing that happens when you specify    | out-file  is the begin phase opens it as a new file for writing, then during the process phase get-content reads the newly empty file.
