### ISSUE TITLE
add a terse method for suppressing errors

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16345]
### Summary of the new feature / enhancement

I would like to have a simple and concise method of suppressing errors and error messages, regardless of their type and source.

In a POSIX shell, I can do something like this:

```bash
set -e
rm nonexistent >/dev/null 2>&1 || : 
```

while this is not particularly beautiful, it works consistently. If anything, we should be able to do better in PowerShell.

This operator in PowerShell has different semantics based on `$ErrorActionPreference`, whether the command returns an exit code or throws an exception etc.. So using this idiom in PowerShell will not work. For example:

```powershell
$ErrorActionPreference = 'stop'
ri nonexistent *> $null || echo success
Remove-Item: Cannot find path 'C:\Users\rkitover\nonexistent' because it does not exist. 
```

in this case neither the error message is suppressed nor the alternate action is taken.

So, let's try something else:

```powershell
$ErrorActionPreference = 'stop'
try { ri nonexistent } catch {}; echo success
success
```

this is closest to what I want, with the caveat that the behavior still depends on `$ErrorActionPreference`, for example:

```powershell
$ErrorActionPreference = 'continue'
try { ri nonexistant } catch {}; echo success 
Remove-Item: Cannot find path 'C:\Users\rkitover\nonexistant' because it does not exist. 
success 
```

in this case the error message is not suppressed. So let's try another variant:

```powershell
$ErrorActionPreference = 'continue'
&{try { ri nonexistant } catch {}} *> $null; echo success
success
$ErrorActionPreference = 'stop'
&{try { ri nonexistant } catch {}} *> $null; echo success
success
```

this gives me consistent behavior regardless of `$ErrorActionPreference` and is the closest to what I'm trying to do in this case.

However, this is a pretty horrible construct.

### Proposed technical implementation details (optional)

I am not a PowerShell expert so I don't know what the best design for a feature like this would be, I just want to be able to run a command, function, cmdlet, .NET code, or whatever, and suppress all error output and exceptions.

Also it would be nice if the `catch {}` block for a `try {}` was optional.

**Comment by rkeithhill** [comment]
There are two things you haven't tried with respect to suppressing `non-terminating` errors: setting `$ErrorActionPreference = 'continue'` which I don't recommend doing at the script level and suppressing non-terminating errors at the command level via the common parameter `-ErrorAction`:

```powershell
ri nonexistant -ea SilentlyContinue
```

This will still store error info in the `$Error` collection so if you need to, you can inspect the error later.

```
PS> $Error[0]

Remove-Item: Cannot find path 'C:\Users\Keith\PSSupport\nonexistant' because it does not exist.
```

If you do not even want the error stored in `$Error` use:

```powershell
ri nonexistant -ea Ignore
```
By and large, PowerShell commands generate non-terminating errors for common errors like "file doesn't exist".  However for those commands that generate terminating errors, there is no way around using `try/catch`.   Well, except for using a trap statement at the top of your script that ignores all terminating errors - again not something I'd actually "recommend" doing:
```powershell
& { trap {"ignoring $_"} throw "kaboom" }; "success"

ignoring kaboom
success
```

**Comment by rkitover** [comment]
I did not know about `-ea ignore` that is very nice, thank you very much!

**Comment by rkitover** [comment]
I don't agree that the feature as I described it exists, or that the quirks in behavior I described should not be addressed, even though the alternate methods I was not aware of are helpful.
