### ISSUE TITLE
Error assigned to variable makes -notlike and -notmatch operators behave incorrectly

### ISSUE THREAD

**Issue by andvant** [PowerShell/PowerShell#16341]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If during variable assignment you get an error (such as ItemNotFoundException), the variable will have weird behavior when used with -notlike and -notmatch operators (they will return false). Whereas even non-existent or null variables will behave normally (return true if used with -notlike and -notmatch).

### Expected behavior

```console
PS> $brokenVar = Get-Item "nonexistent"
PS> if ($brokenVar -notlike "pattern") { echo "true" } else { echo "false" }
true
```

### Actual behavior

```console
PS> $brokenVar = Get-Item "nonexistent"
PS> if ($brokenVar -notlike "pattern") { echo "true" } else { echo "false" }
false
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Looks like when a variable value is `AutomationNull.Value`, as can happen in error cases, the `-notlike` and `-notmatch` operators don't evaluate at all, no value is returned:

```ps1
$autoNull = [System.Management.Automation.Internal.AutomationNull]::Value
$autoNull -notlike 'aaaa' # no output
$autoNull -notmatch 'aaaa' # no output
```

So as a result they register as "false" in an if statement, because nothing is returned from the expression. I can see why this might occur, but it's unclear what the "correct" behaviour would be here, to me.

**Comment by iSazonov** [comment]
> but it's unclear what the "correct" behaviour would be here, to me.

Changing the behavior will be huge breaking change. :-)

**Comment by vexx32** [comment]
Aye. Either we fix it, which potentially could break some things, or we document it. If we document it, we'll need to detail which operators behave this way and which don't, I imagine more than just these are probably affected.
