### ISSUE TITLE
Assignment of $NULL to a BOOL variable does not work

### ISSUE THREAD

**Issue by yecril71pl** [PowerShell/PowerShell#16346]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
[BOOL] $X = $NULL
```

### Expected behavior

```console
-NOT $X
```

### Actual behavior

```console
MetadataError
```

### Error details

```console
Cannot convert value "" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
```

### Environment data

```powershell
System.Management.Automation.PSVersionHashTable
```

**Comment by yecril71pl** [comment]
This breaks the following code:
```powershell
# declare a bunch of variables
[INT] $A, [BOOL] $B = @()
```

**Comment by yecril71pl** [comment]
Workaround (spooky 🤨)
```powershell
[INT] $A, [BOOL] $B = (,$FALSE) * 0X2
```

**Comment by 237dmitry** [comment]
> MetadataError

Could not reproduce:
```powershell
PS> [bool] $x = $null
PS> -not $x
True

PS> [int] $a, [bool] $b = @()
PS> $a; $b
0
False

PS> [int] $a, [bool] $b = (,$false) * 0x2
PS> $a; $b
0
False

PS> [int] $a = [bool] $b = $false
$a; $b
0
False

PS>  [string] (Get-Host).Version; $IsLinux
7.1.5
True

```

**Comment by vexx32** [comment]
I am seeing this on 7.2.0-rc.1 -- is this a recent regression? /cc @daxian-dbw

**Comment by daxian-dbw** [comment]
No, this is not a regression. It's the same behavior on PowerShell 7.1.x and even Windows PowerShell 5.1

**Comment by 237dmitry** [comment]
> It's the same behavior on PowerShell 7.1.x and even Windows PowerShell 5.1

No. In pwsh 7.1.5 and in powershell 5.1 there are not any errors:

![7](https://user-images.githubusercontent.com/78153320/139713996-c789f0a1-4c29-48d7-92cf-a0f7e3fddbc8.png)
![5](https://user-images.githubusercontent.com/78153320/139714038-c42e652f-5484-410a-b149-37b6605047bd.png)

**Comment by vexx32** [comment]
I see the error in PS 5.1 as well. Not sure what's going on there.

```ps1
PS> [bool]$a = $null
Cannot convert value "" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as
$True, $False, 1 or 0.
At line:1 char:1
+ [bool]$a = $null
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by 237dmitry** [comment]
> I suspect the error is hidden or nonexistent when it's not declared at script or global scope...

Unexpectedly, it really is... I was wrong. I prefer to try variables in `& {...}` in order to not to breed them.

**Comment by daxian-dbw** [comment]
Yep, when running in local scope, the variable `[bool]$a` is optimized and it doesn't emit error in that case.
