### ISSUE TITLE
Enter-PSSession fails obscurely when invoked via the CLI or from a script

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16350]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Currently, `Enter-PSSession` only behaves as expected - _synchronously_ entering an interactive remote session - when called _directly_ from an _interactive_ PowerShell session.

By contrast, it fails obscurely when called via `pwsh -Command` or from inside a `*.ps1` script (even if you called from an interactive session).

Note: If these scenarios cannot be supported for technical reasons, (a) the cmdlet would ideally detect these scenarios and _refuse to run_ and (b) the limitation needs to be documented.

CLI example:

```powershell
# On Windows, from an elevated session on a machine that is set up for remoting.
# On Unix, set the machine up for SSH remoting and use -Hostname  instead of -ComputerName
pwsh -nop -c 'Enter-PSSession -ComputerName .; $host; exit'
```

### Expected behavior

An interactive remoting session (to the same machine) should be entered.

Only after manually exiting that session should `$host` and `exit` execute, in the _local_ session, at which point the `pwsh` call as a whole should terminate.

### Actual behavior

A remoting session is initiated, but _local processing continues instantly_; that is, the local commands following `Enter-PSSession` are _executed right away_, locally.

Because the `exit` then terminates the entire process, an interactive remote session is never entered.

If `exit` is omitted, the `pwsh` call _hangs_, and even <kbd>Ctrl-C</kbd> doesn't help (this doesn't happen with `powershell.exe`, which exits implicitly).

If, by contrast, you were to place  `Enter-PSSession -ComputerName .; $host` - without the `exit` - in a `*.ps1` file and were to execute that file from an interactive local session, `$host` would execute locally right away, and a remote session would be entered _only after the script terminates_.

### Environment data

```powershell
PowerShell Core 7.2.0-rc.1
```

**Comment by PaulHigin** [comment]
@WG-Remoting
Remoting working group: The purpose of `Enter-PSSession` is to substitute a new (remote) session for the current interactive session, and is not intended to be called as a shell command or within script.

**Comment by mklement0** [comment]
* There's no reason _not_ to allow scripts to initiate an interactive remote session - just like you're free to invoke any other interactive shell from a script (giving the user a chance to perform open-ended operations in the interactive shell, before `exit`ing it to return to the calling script).
 
  * To provide a simple example of something that works:

```powershell
'Entering an interactive bash session; exit it to continue running this script...'
bash
'Resuming...'
```
  
* If this - unfortunate - decision not to support this scenario is upheld, at least the _clearly buggy current behavior_ must be addressed.

**Comment by LadyCailin** [comment]
+1 on reopening this. It's a super bad assumption to make that the parent script running doesn't need to block on this. Even if it were an additional -Wait flag on Enter-PSSession, and not the default, that would be good.
