### ISSUE TITLE
`Resolve-Path`: add parameter `-RelativeTo`

### ISSUE THREAD

**Issue by Quaentor** [PowerShell/PowerShell#16359]
This parameter should be a path that is used instead of the current directory.

**Comment by jdhitsolutions** [comment]
At first, I figured it would be just as easy to change location.
![image](https://user-images.githubusercontent.com/12089920/145630364-1910bfa5-12ec-47f0-bc6e-87fa6ce49bc9.png)

But that isn't necessarily scripting-friendly. I think what you want is something like this:

```dos
PS C:\scripts> resolve-path ~ -Relativeto c:\work\foo
..\..\Users\Jeff
```

Do I have this right?

**Comment by Quaentor** [comment]
@jdhitsolutions yes.

Right now I use the following function instead

```powershell
function Normalize-Path
(
    [string[]][Parameter(ValueFromPipeline)]$Path,
    [string]$To=(Get-Location),
    [switch]$Relative
)
{
process
{
    Push-Location $To
    $res = $Path | Resolve-Path -Relative:$Relative | %{ [string]$_ }
    if($Relative -and $res){
        $res = $res | %{ $_.Substring(2) }  # don't want ".\"
    }
    Pop-Location
    return $res
}
}
```

**Comment by jdhitsolutions** [comment]
I would like to know from the community other scenarios where having a `RelativeTo` parameter would be useful.

**Comment by iSazonov** [comment]
I investigate PowerShell providers for vNext and use the cmdlet for testing a _parsing_ of PowerShell paths. And I thought about adding `-Root` parameter (it is more right term in the context). As for real script scenarios, I think we have no need the new parameter.
So if I will find the feature useful for PowerShell providers testing I will add it for vNext.

**Comment by gaelcolas** [comment]
I think we've created something like this for the DSC Community and use in a couple of places.
When we manipulate Jacoco Test results and the like, sometimes we want to update the absolute path returned to a path relative to the source folder of our repos or similar...
We're also using this kind of feature in our test where we don't care about the absolute path in our test results, and the relative is more concise (specific case here, relative to module root): https://github.com/dsccommunity/DscResource.Test/blob/main/source/Private/Get-RelativePathFromModuleRoot.ps1

**Comment by Quaentor** [comment]
"Waiting on Author"? What for?

**Comment by iSazonov** [comment]
@Quaentor I guess it was a question about other scenarios where having a RelativeTo parameter would be useful.

**Comment by JamesWTruher** [comment]
The Cmdlet and Module Working Group has reviewed this issue. It is the group's consensus that although the requested feature is potentially useful, it does not reach the threshold for committing resources that would be required to implement it.
Additional parameters of this kind can often be implemented as Proxy Functions and the code shown on the issue could be used as the basis of a community-supported proxy function, which can be delivered from the PowerShell Gallery. When items in the gallery generate a significant positive response the PowerShell committee and/or working groups may reconsider whether they should form part of the main the PowerShell repo.
