### ISSUE TITLE
Cancel Stop-Computer

### ISSUE THREAD

**Issue by 89z** [PowerShell/PowerShell#16362]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a program on my system called `stopwatch.exe`, so sometimes I will have PowerShell open, and I will enter the command. However I also use tab completion, so I will usually enter:

~~~
stopw TAB
~~~

then press enter. However if on accident I enter:

~~~
stop TAB
~~~

Then I instead get Stop-Computer, which shuts down the computer. I have done this on accident now at least twice, and its very annoying.

### Expected behavior

Does anyone has a solution for this problem? I know with the old `shutdown.exe`, you could enter `shutdown /a` to cancel it, but I dont know if anything like that is available with PowerShell.

### Actual behavior

https://docs.microsoft.com/powershell/module/microsoft.powershell.management/stop-computer

### Environment data

```powershell
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
You can put new alias in your profile and redefine `stop` behavior.

**Comment by 89z** [comment]
As a workaround, I edited this file:

~~~
C:\PowerShell\Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1
~~~

Just comment out this line, or remove it:

~~~
"Stop-Computer",
~~~

You wont be able to shut down with PowerShell, but I dont think I have ever wanted or needed to do that. You can just push the power button on your computer, or shut down from the Start Menu.

**Comment by iSazonov** [comment]
> You can just push the power button on your computer, or shut down from the Start Menu.

Script can not to push the power button :-)

**Comment by 237dmitry** [comment]
The simplest way is to assign an alias to stopwatch.exe in `$profile`.
For example:
```
Set-Alias -Name sw -Value stopwatch.exe                   # If stopwatch.exe in $env:Path
Set-Alias -Name sw -Value "C:\Path\To\.\stopwatch.exe"    # if stopwatch.exe is not in $env:Path
```

**Comment by MartinGC94** [comment]
Instead of editing the file to remove Stop-Computer you can override it with a function or Alias that either does nothing, or executes stopwatch.exe. Functions and aliases have a higher precedence so if you create a dummy function like this: `function Stop-Computer {}` it should get executed instead of the Stop-Computer cmdlet.  
You would define this function inside your $profile file so it works in every session.
