### ISSUE TITLE
Update tag on master to 7.2.0-rc.1

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#16363]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Please update the tag on master.  The *7.2.0-rc.1* has been released 13 day ago yet the daily build of PowerShell still results with `Preview` tag. It seems that this issue is reappearing quite often (see #15244)

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10-137-g00d39fa4d5f562f3ee03df7f0d0355501eb1af4a
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Expected behavior

```console
7.2.0-rc.1
```

### Actual behavior

```console
7.2.0-preview.10-137-g00d39fa4d5f562f3ee03df7f0d0355501eb1af4a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10-137-g00d39fa4d5f562f3ee03df7f0d0355501eb1af4a
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
We forked after preview.10 and the changes flow in the other direction.  This is by design.

**Comment by TravisEz13** [comment]
To clarify, merging the tag back would cause too many conflicts.
