### ISSUE TITLE
Write-Output result identifies as `[pscustomobject]`  (`-is [pscustomobject]`)

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#16361]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
(Write-Output 1) -is [pscustomobject]  # unexpectedly True, although .GetType() returns Int32
(1) -is [pscustomobject]  # False, as expected

$x = Write-Output 1
$x -is [pscustomobject]  # also unexpectedly True
$y = 1
$y -is [pscustomobject]  # False, as expected
```

The issue seems reproducible in both `PowerShell 5.1` and `PowerShell Core 7.2.0-rc.1`.

### Expected behavior

```console
False each time (`Int32` is not a `pscustomobject`).
```

### Actual behavior

```console
PowerShell seems to think any object returned by `Write-Output` is somehow also `pscustomobject`.
```

Result of this issue is we can have a pair of "almost exactly the same" objects, but one of them thinks it's also a `pscustomobject`:

```
$x = 1
$y = echo $x  # I'd assume $y is the exact same thing as $x here...

$x -is [pscustomobject]
$y -is [pscustomobject]  # ...but it's not, because these two checks return different things.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-rc.1
PSEdition                      Core
GitCommitId                    7.2.0-rc.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
I could be wrong here but when you use `[PSCustomObject]` it isn't actually pointing to [System.Management.Automation.PSCustomObject](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscustomobject?view=powershellsdk-7.0.0) but rather [System.Management.Automation.PSObject](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psobject?view=powershellsdk-7.0.0)

```powershell
[PSCustomObject].FullName

# System.Management.Automation.PSObject

[System.Management.Automation.PSCustomObject].FullName

# System.Management.Automation.PSCustomObject
```

This is the part I cannot really explain too well but when you output an object on the pipeline it is somewhat transparently wrapped as a `PSObject` to give it access to the extended type system info for that type/object. So while it might be an `Int32` on the .NET side when you output it through `PSCustomObject` it is in reality a `PSObject` in the background. I might have clobbered the information here so someone who is more knowledgeable is free to share the correct information.

In the end , what's the purpose of checking if it's a `PSCustomObject` type? When you do `[PSCustomObject]@{...}` you are essentially creating a type with it's own properties and 1 `PSCustomObject` may not be the same as others. There might be a better method for your original purpose.

**Comment by vexx32** [comment]
Yep, you more or less got it. Anything passed through the pipeline is essentially wrapped in a PSObject wrapper, and checking `-is [psobject]` (and by extension `-is [pscustomobject]` as @jborean93 points out, as they are the same) is essentially meaningless.

It is effectively the same thing as doing `-is [object]` -- there's not many scenarios where it makes sense to check that kind of metadata.

**Comment by MatejKafka** [comment]
The reason I'm checking for `[psobject]` is because I'm invoking a script (provided by a user of my module at runtime), that either returns a primitive value (string/int/bool, maybe even PathInfo and similar), or a map (key-value) container like hashtable/psobject/pscustomobject with a fixed property name (among other properties).

I need to distinguish between these two cases, and testing with `-is` seemed like the best way, but apparently it isn't. Do you have any better alternatives? I could restrict the API to only accept a hashtable or a primitive value, but would prefer to also accept other map-like containers.

**Comment by 237dmitry** [comment]
```(Write-Output 1) -is [int] # True```

I think `.GetType()` method returns correct value.

**Comment by vexx32** [comment]
If you want to check for a true PSCustomObject, one constructed with `[pscustomobject]@{ .... }` you're probably best off doing `$object.PSTypeNames` and looking for the PSCustomObject type name in there.

`-is` will work for most things, but PSCustomObject is more a property bag than a type in and of itself, so it's not particularly suitable for that.

**Comment by SeeminglyScience** [comment]
You can also use the full type name for that test:

```powershell
(Write-Output 1) -is [System.Management.Automation.PSCustomObject]
# False
([pscustomobject]@{thing = 1; that = 2}) -is [System.Management.Automation.PSCustomObject]
# True
```

`PSCustomObject` is really a dummy instance used as the base object for `PSObject`s when there's no base object.  The type accelerator pointing to `PSObject`  is a little confusing but more helpful than harmful imo.

**Comment by SeeminglyScience** [comment]
> there's an argument for using `Int32` instead of `int`, `Boolean` instead of `bool` etc. (moving a function to a cmdlet in C# doesn't need to change type names).

Note that for those particular examples (and most primitives) there are matching keywords in C#.
