### ISSUE TITLE
Modernize the release pipeline

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#16370]
- [x] move to 1ES
- [ ] manual intervention tasks (less manual setup if we have to move)
- [ ] auto trigger other build
- [ ] Auto PR generation for
  - [ ] winget
  - [ ] dotnet docker
  - [ ] mcr
- [ ] Auto publish to store

**Comment by iSazonov** [comment]
I see Windows CI warns to move Windows-latest image.

**Comment by TravisEz13** [comment]
This is about release pipeline not CI pipelines.

**Comment by krilllind** [comment]
Yes please!

The DX is quite bad right now. You get a notification about a new release, however running `winget upgrade Microsoft.PowerShell`  returns "No applicable update found.". Package should be available at the same time for all major download platforms

**Comment by vedantmgoyal2009** [comment]
@TravisEz13 @iSazonov @adityapatwardhan @SydneyhSmith We can make a post-release workflow which can auto-generate PRs on [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) using a github personal access token (PAT) from any maintainers' account or some bot like @PoshChan.

Store submission can be performed using https://github.com/marketplace/actions/microsoft-store-publish.
