### ISSUE TITLE
Unclear Error Message from CommandInvocationIntrinsics.InvokeCommand

### ISSUE THREAD

**Issue by Stroniax** [PowerShell/PowerShell#16387]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
$ExecutionContext.SessionState.InvokeCommand.InvokeScript(
  <# script #> 'Test-Path C:',
  <# useNewScope #> $false,
  <# pipelineResultTypes #> 'All', # anything other than 'Output' and/or 'Error'
  <# input #> $null, # or @()
  <# params arguments #> @()
)
```

Obviously I can see now that this is not intended to be supported, but the exception seems like it could do with some improvement.

https://github.com/PowerShell/PowerShell/blob/ef69fdafc41017661203fde8ed3ab77414f5e14e/src/System.Management.Automation/engine/MshCmdlet.cs#L841-L845

### Expected behavior

```console
# Initially I expected this to run the script. It is documented on msdn that this is not supported but the error message was definitely not helpful in discerning that.
```

### Actual behavior

```console
Exception calling "InvokeScript" with "5" argument(s): "Cannot perform operation because operation "NewNotImplementedException at offset 34 in file:line:column <filename unknown>:0:0
" is not implemented."
```

### Error details

```console
# Huge error that doesn't explain the actual problem, which is that only Error and Output are supported for PipelineResultTypes
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
It looks to me a better error message should be used here.
