### ISSUE TITLE
Set-Service <name> -StartupType AutomaticDelayedStart sets startup to Automatic

### ISSUE THREAD

**Issue by LarsFosdal** [PowerShell/PowerShell#16380]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In PowerShell 7.1.5, with admin right, calling
Set-Service <name> -StartupType AutomaticDelayedStart
does not result in the service getting a change in the startup type.

### Expected behavior

```console
When I visually inspect the service in the Services window, I expected to see the Startup Type listed as "Automatic (Delayed Startup)"
```

### Actual behavior

```console
When I visually inspect the service in the Services window, I see the Startup Type listed as "Automatic"
```

### Error details

```console
No errors returned
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I checked with latest 7.2 build and this work well. Do you have permissions to do the operation?

**Comment by LarsFosdal** [comment]
Yes, the executing account has local admin rights and the script runs elevated, and the service is set up to log on as that account.

Can you verify that -StartupType Automatic and AutomaticDelayedStart gives different results in the Services window list?
For me, it appears that both set it to just Automatic.

**Comment by iSazonov** [comment]
> Can you verify that -StartupType Automatic and AutomaticDelayedStart gives different results in the Services window list?

Yes
![image](https://user-images.githubusercontent.com/22290914/140725564-cda3255e-ef9e-4efc-8de1-15f1370b8c00.png)

**Comment by LarsFosdal** [comment]
![image](https://user-images.githubusercontent.com/7009177/140727550-232db60d-dd30-43c6-822c-41d6d4e6a754.png)
Note that the delayed start flag has been manually enabled in the GUI.

**Comment by iSazonov** [comment]
PowerShell p/invoke ChangeServiceConfig2W - there are not arguments about Wow64.

**Comment by jborean93** [comment]
> The service is 32-bit and runs under WOW64.

AFAIK that's not really part of the service configuration and is just what happens when you get the service to start a 32-bit executable. Could you run `sc.exe config MyService start= delayed-auto` and see if you have the same behaviour?

**Comment by GaijinFizz** [comment]
I am experiencing the same issue on Windows Server 2019 Standard, specifying `AutomaticDelayedStart` sets the startup type to `Automatic`

**Comment by iSazonov** [comment]
Really there are two sc.exe - C:\Windows\System32\sc.exe and C:\Windows\SysWOW64\sc.exe
I guess it is only way to configure a 32-bit service from 64-bit pwsh without direct registry editing.

**Comment by jborean93** [comment]
> I guess it is only way to configure a 32-bit service from 64-bit pwsh without direct registry editing.

It shouldn’t be, the API the same. As long as PowerShell is setting the delayed flag through the API and not the registry directly it should work.

**Comment by iSazonov** [comment]
It works if pwsh is 32-bit.

**Comment by jborean93** [comment]
It seems to work for me.

```powershell
# Uses Ctypes - https://www.powershellgallery.com/packages/Ctypes/0.1.0

ctypes_struct SERVICE_DELAYED_AUTO_START_INFO {
    [bool]$DelayedAutoStart
}

$advapi32 = New-CtypesLib Advapi32.dll

$scm = $advapi32.SetLastError().OpenSCManagerW[IntPtr]($null, $null, 0xF003F)
if ($scm -eq [IntPtr]::Zero) {
    throw [System.ComponentModel.Win32Exception]$advapi32.LastError
}

$service = $advapi32.SetLastError().CharSet('Unicode').OpenServiceW[IntPtr]($scm, "AAA", 0xF01FF)
if ($service -eq [IntPtr]::Zero) {
    throw [System.ComponentModel.Win32Exception]$advapi32.LastError
}

$info = [SERVICE_DELAYED_AUTO_START_INFO]@{
    DelayedAutoStart = $true
}
$res = $advapi32.CharSet('Unicode').SetLastError().ChangeServiceConfig2W[bool](
    $service,
    3,  # SERVICE_CONFIG_DELAYED_AUTO_START_INFO
    [ref]$info)
if (-not $res) {
    throw [System.ComponentModel.Win32Exception]$advapi32.LastError
}
    
$advapi32.CloseServiceHandle[void]($scm)
$advapi32.CloseServiceHandle[void]($service)

(Get-Service -Name AAA).StartupType
```

I registered the service `AAA` with a binary I know is 32-bit. I ran the above code in PowerShell to set the delayed auto start flag. The output is `AutomaticDelayedStart` and the `services.msc` snappin shows it as `Automatic (Delayed)`.

**Comment by iSazonov** [comment]
> I registered the service `AAA` with a binary I know is 32-bit.

Can you confirm you registered it as 32-bit service with C:\Windows\SysWOW64\sc.exe and you see the service in SysWOW64 branch in registry?

**Comment by jborean93** [comment]
Yes, created with `C:\Windows\SysWOW64\sc.exe`, you can even see the `WOW64` dword in there

![image](https://user-images.githubusercontent.com/8462645/216035569-f83c1f50-0ff2-46f5-ab32-0893f7d3b8dd.png)

`ChangeServiceConfig2W` was able to flag such a service with the delayed flag when running in a 64-bit PowerShell.

**Comment by iSazonov** [comment]
@jborean93 And you cannot configure the service with the cmdlet?

**Comment by GaijinFizz** [comment]
In my case, it is a 64 bit service.
Both Set-Service and sc.exe work locally (AutomaticDelayedStart can be set).

While using `invoke-command -ScriptBlock {}` , I always get the same result:
![image](https://user-images.githubusercontent.com/2937588/216055241-fb0065bc-1b66-43c2-bf2b-035ad99d69f7.png)
I tried both sc.exe

**Comment by GaijinFizz** [comment]
Here is what I run

`
invoke-command -ScriptBlock {
	$ArtifactsPath = $args[0]
	$ReleasePath = $args[1]
	$User = $args[2]
	$Password = $args[3]
	$Server = $args[4]
	$ServiceName = $args[5]
	$ServiceAccount = $args[6]
	$ServiceAccountPassword = $args[7]


	... removed some stuff ...

	#Reinstalling/starting the Windows service
	Write-Host "Reinstalling/starting the Windows service"
	Write-Host "> Creating the service"
	New-Service -Name $ServiceName -BinaryPathName "$ReleasePath\$ServiceName.exe"
	Write-Host "> Setting service startup type"
	Set-Service $ServiceName -StartupType AutomaticDelayedStart
	Write-Host "> Setting service running account"
	Set-Service -Name $ServiceName -Credential $SVCCredentials
	Write-Host "> Starting up the service"
	Set-Service -Name $ServiceName -Status Running

	... removed some stuff ...

} -Configuration PowerShell.7.3.2 -Computer $Server -Credential $Credentials -ArgumentList $ArtifactsPath,$ReleasePath,$User,$Password,$Server,$ServiceName,$ServiceAccount,$ServiceAccountPassword
`

**Comment by iSazonov** [comment]
@jborean93 Thank you for your efforts! I was beginning to think we were dealing with a tricky Windows API. In fact, it's something in the private scenarios.

@GaijinFizz Could please create more simple repro script? Also Does the script work in Windows PowerShell 5.1 and pwsh 7.2? Can you run the script without `-Credential $Credentials` (current user should have remote admin permissions)?

**Comment by GaijinFizz** [comment]
Hi, I found a fix

I changed the order of the commands, setting the startup type after the service is started and it now works!

Not working:
```
	New-Service -Name $ServiceName -BinaryPathName "$ReleasePath\$ServiceName.exe"
	Set-Service -Name $ServiceName -StartupType Automatic
	Set-Service -Name $ServiceName -Credential $Credentials 
	Set-Service -Name $ServiceName -Status Running
```

Working:
```
	New-Service -Name $ServiceName -BinaryPathName "$ReleasePath\$ServiceName.exe"
	Set-Service -Name $ServiceName -Credential $Credentials 
	Set-Service -Name $ServiceName -Status Running
	Set-Service -Name $ServiceName -StartupType Automatic
```

Thanks for your help
