### ISSUE TITLE
A `catch` block in a try / catch statement qualified with type `System.Management.Automation.RuntimeException` traps *any* exception

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16392]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In practice, `catch [System.Management.Automation.RuntimeException] { ... }` seems to behave the same as an _unqualified_ `catch` block.

That is, it catches _any_ exception - even those _not_ derived from `System.Management.Automation.RuntimeException`

```powershell
try { throw ([System.ArgumentException] 'foo') }
catch [System.Management.Automation.RuntimeException] { 'What are you doing here? ' }
```

### Expected behavior

The exception thrown should surface as a script-terminating error, because its type isn't derived from `System.Management.Automation.RuntimeException`, so the `catch` block should not be entered.

### Actual behavior

`'What are you doing here?'` is output, because the `catch` block was unexpectedly entered.

### Environment data

```powershell
PowerShell Core 7.2.0-rc.1
```

**Comment by daxian-dbw** [comment]
The Engine WG discussed this issue today.

We think this behavior is an implementation detail that should be documented -- all exceptions are wrapped by `RuntimeException` within powershell, and thus `catch [RuntimeException] { ... }` will catch everything.
We also recommend a PSSA rule to caution against using `RuntimeException` as a `catch` clause type.

**Comment by daxian-dbw** [comment]
The doc issue: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8340
The PSSA issue: https://github.com/PowerShell/PSScriptAnalyzer/issues/1744
