### ISSUE TITLE
!! alias for the last run command

### ISSUE THREAD

**Issue by OldWorldOrdr** [PowerShell/PowerShell#16409]
### Summary of the new feature / enhancement

The majority of Linux shells let you use !! as an alias for the last run command.  This is useful for many things, like using `sudo !!` to run the previous command as root.  I believe this could also be very useful in PowerShell.

**Comment by iSazonov** [comment]
You can define the alias in your profile. (See Get-History cmdlet)

**Comment by lukeb1961** [comment]
I don't think Powershell can do what he asks in his example - "sudo !!"
and even trying to set an alias with a name of "!!" will give an error when run.
