### ISSUE TITLE
Modernize command output

### ISSUE THREAD

**Issue by yves-dolce** [PowerShell/PowerShell#16403]
### Summary of the new feature / enhancement

In a nutshell, support colored comand output the way `ls` does on *nix. That woud be a minimum. Then this can be improved during the feature design.

```
 -C                    list entries by columns
      --color[=WHEN]   colorize the output; WHEN can be 'always' (default
                       if omitted), 'auto', or 'never'; more info below
...
Using color to distinguish file types is disabled both by default and
with --color=never.  With --color=auto, ls emits color codes only when
standard output is connected to a terminal.  The LS_COLORS environment
variable can change the settings.  Use the dircolors command to set it.
```

**Comment by iSazonov** [comment]
I don't understand what you suggest. Please reword, add more info and examples.

**Comment by dwtaber** [comment]
The example provided sounds an awful lot like the new [`PSAnsiRenderingFileInfo`](https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.2#psansirenderingfileinfo) experimental feature.  @yves-dolce, have you tried that feature?
