### ISSUE TITLE
IScriptExtent.File not in reference assembly for 7.2.0

### ISSUE THREAD

**Issue by Stroniax** [PowerShell/PowerShell#16408]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Upgrading package reference for System.Management.Automation to version 7.2, I got the compiler error CS1061:
```
'IScriptExtent' does not contain a definition for 'File' and no accessible extension method 'File' accepting a first argument of type 'IScriptExtent' could be found (are you missing a using directive or an assembly reference?)
```
due to this line:
```
// statement is an instance of StatementAst
writer.WriteLine("### File: {0}", System.IO.Path.GetFileName(statement.Extent.File));
```

I have confirmed that the property exists in the interface while running PowerShell so it looks like this is just omitted from the reference assembly:
```
[System.Management.Automation.Language.IScriptExtent].GetProperty('File')
```

### Expected behavior

```console
No Error
```

### Actual behavior

```console
CS1061: 'IScriptExtent' does not contain a definition for 'File' and no accessible extension method 'File' accepting a first argument of type 'IScriptExtent' could be found (are you missing a using directive or an assembly reference?)
```

### Environment data

```powershell
NA. Referencing System.Management.Automation version 7.2.0
```

**Comment by SeeminglyScience** [comment]
Specifically it's just the ref assembly included in the nuget package.  Opening the ref assembly in dnSpy shows the property missing, but opening the real assembly shows `File` present on `IScriptExtent`
