### ISSUE TITLE
`$PSStyle.Progress.MaxWidth` doesn't allow 0

### ISSUE THREAD

**Issue by eddiezato** [PowerShell/PowerShell#16410]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PowerShell
PS > $PSStyle.Progress.MaxWidth = 0
```

### Expected behavior

As the documentation says:

> `$PSStyle.Progress.MaxWidth` - Sets the max width of the view. **Set to 0 for console width.** Defaults to 120

### Actual behavior

Causes an error:

*SetValueInvocationException: Exception setting "MaxWidth": "The MaxWidth for the Progress rendering must be at least 18 to render correctly. (Parameter 'MaxWidth')"*

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Can you please take a look to see if this is a doc issue or code issue?

**Comment by FireInWinter** [comment]
I hope it is supposed to be able to be set to 0 for console width.  Otherwise it will be sort of a pain to set it to a decent size as the default of 120 is really small when you have a really wide monitor.  You could probably set it to the max width by getting the window size from $host, but then you have to make sure you change it if the window size changes.

**Comment by eddiezato** [comment]
It seems to have been "solved" by fixing the [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress?view=powershell-7.3#description). So there is no point in this issue remaining open. 
> $PSStyle.Progress.MaxWidth - Sets the max width of the view. Defaults to 120. The minimum value is 18.
