### ISSUE TITLE
`Write-Progress` since 7.2.0 sets `CursorVisible` to `$true`

### ISSUE THREAD

**Issue by eddiezato** [PowerShell/PowerShell#16412]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the script:
```PowerShell
[Console]::CursorVisible = $false
Write-Host "Before wp - " -NoNewLine
[Console]::CursorVisible
0..10 | % {
    Write-Progress -Activity test -Status test -PercentComplete $_
    Start-Sleep -s 0.1
}
Write-Host "After wp - " -NoNewLine
[Console]::CursorVisible
```

### Expected behavior

`Write-Progress` shouldn't affect the state of `CursorVisible`

### Actual behavior

```PowerShell
PS > .\script.ps1
Before wp - False
After wp - True
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@SteveL-MSFT can you please take a look to see if this behavior is intentional?

**Comment by SteveL-MSFT** [comment]
I see where the cursor visibility is being changed, I'll submit a PR, should be a simple fix.
