### ISSUE TITLE
Launching PowerShell after Upgrading from PowerShell v7.1.5 to PowerShell v7.2.0 Generates Error

### ISSUE THREAD

**Issue by cloudgiant99** [PowerShell/PowerShell#16422]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Launching PowerShell after Upgrading from PowerShell v7.1.5 to PowerShell v7.2.0 Generates Error - Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### Expected behavior

```console
Prompt without error.
```

### Actual behavior

```console
Error:

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!
```

### Error details

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.22000
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Environment data

```powershell
Unable to run command.
```

**Comment by iSazonov** [comment]
It is PSRL related. Please update PSReadLine to latest Beta4 version.

**Comment by dansvel** [comment]
1. Open an Powershell session in Administrator privilege
2. Run `Remove-Module PSReadLine` to remove the auto-loaded PSReadLine module.
3. Run `Import-Module PSReadLine` (use PSReadLine with capital L)
4. Then run `Update-Help -Module PSReadLine -Force`
source : https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

**Comment by cloudgiant99** [comment]
I can't run the commands above in the PowerShell 7 environment, I get the same error after I hit enter. The environment is broken. So, I uninstalled PowerShell 7, then I ran the commands above in PowerShell 5, just to be sure. Then I installed PowerShell 7.1.4, which works without errors. Then, I ran the commands above in that environment as Administrator. I then installed PowerShell 7.2.0 and I get the same error. What am I missing?

**Comment by Shigbeard** [comment]
> 
> 
>     1. Open an Powershell session in Administrator privilege
> 
>     2. Run `Remove-Module PSReadLine` to remove the auto-loaded PSReadLine module.
> 
>     3. Run `Import-Module PSReadLine` (use PSReadLine with capital L)
> 
>     4. Then run `Update-Help -Module PSReadLine -Force`
> 
> 
> source : https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

This doesn't work, you're just reimporting the same PSReadLine module. In place of Step 3, instead of running `Import-Module`, run `Install-Module -Name PSReadLine -RequiredVersion 2.2.0-beta4 -AllowPrerelease` as this explicitly specifies the latest version of PSReadLine to install (At least at the time of writing)

After this, it's safe to import the module again. This is what fixed it for me.
