### ISSUE TITLE
when I use 'get-command', the path of the command display incompletely when the path are long.

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [PowerShell/PowerShell#16428]
### Summary of the new feature / enhancement

when I use 'get-command' to get the path of the command. However the command can't display completely if they are long!!
![image](https://user-images.githubusercontent.com/52443370/141134336-8914954e-aa81-4663-81aa-6ffedc42b264.png)
i hope the path can automatically use another line to display it 🤔

**Comment by SeeminglyScience** [comment]
You can pipe to `Format-Table -Wrap` or `Select-Object -ExpandProperty Source`.
