### ISSUE TITLE
Ignore Proxy

### ISSUE THREAD

**Issue by Iyappanj** [PowerShell/PowerShell#16424]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

How do I ignore proxy in Invoke-WebRequest

I see -NoProxy is supported after version 6

How can I ignore proxy on version 5.x ?

### Expected behavior

```console
I see -NoProxy is supported after version 6
```

### Actual behavior

```console
How can I ignore proxy on version 5.x ?
```

### Environment data

```powershell
How can I ignore proxy on version 5.x ?
```

**Comment by iSazonov** [comment]
Please fill the issue template as requested. Did you test with 7.2 version?

**Comment by Iyappanj** [comment]
@iSazonov Which template ? And I have most of my machines with 5.1 version. So I wanted to know how to ignore proxy in Invoke-WebRequest

**Comment by iSazonov** [comment]
The repository is only for PowerShell Core. For Windows PowerShell discussions please use other resources.
