### ISSUE TITLE
pwsh 7.20 fails to start on Windows 11 Pro Insider Preview Build

### ISSUE THREAD

**Issue by mazhar10** [PowerShell/PowerShell#16421]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install PowerShell 7.20 using the MSI package on Windows 11.
Try to start PowerShell 7.20 either by executing pwsh or by using Windows Terminal.

### Expected behavior

```console
PowerShell 7.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.
```

### Actual behavior

```console
Failed to create CoreCLR, HRESULT: 0x80004005

[process exited with code 2147516553 (0x80008089)]
```

### Error details

```console
PowerShell 7.20 does not start.
```

### Environment data

```powershell
Windows 11 Insider Preview Build 22489.
PowerShell 7.20 release version.
```

### Visuals

Launch pwsh after installing PowerShell 7.20.

**Comment by h8f1z** [comment]
Did you try to run as admin?
I am having similar issue on windows 10, after installing pwsh 7.2.
My pwsh doesn't show anything as a normal user (except the blinking cursor). But works fine when it's run as admin.

**Comment by mazhar10** [comment]
It works fine on Windows 10 release and Windows 10 insider builds.
On the Windows 11 build mentioned above, I executed pwsh from a cmd window running as administrator (the account I am using is a local administrator as well) and still get the same error.

**Comment by iSazonov** [comment]
> Insider Preview Build

I think it is better to report with Feedback tool to Windows team as a bug in Windows 11 Preview.

**Comment by IoTFier** [comment]
> > Insider Preview Build
> 
> I think it is better to report with Feedback tool to Windows team as a bug in Windows 11 Preview.

Disagree with the recommendation.

As we are using artifacts from this github repo, then why to report issues via Windows Feedback tool?
That's ok if the update were to come in via Windows update.

Please help in addressing this issue.

Thank you

**Comment by micahgoodreau** [comment]
error on win10 pro


### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19043
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

**Comment by iSazonov** [comment]
@IoTFier @micahgoodreau You say about another issue - you should update PSReadline to latest Beta4 version.

**Comment by IoTFier** [comment]
> @IoTFier @micahgoodreau You say about another issue - you should update PSReadline to latest Beta4 version.

I tried to follow steps outlined here - https://github.com/PowerShell/PowerShell/issues/16422#issuecomment-965204089
But, powershell doesn't show the command prompt.

Any steps that your recommend for updating PSReadline to latest Beta4 ?

I thought Powershell 7.2 is not in the beta any more. This is has messed up stable 7.1.x environment on my couple of PCs.

Please help.

**Comment by daxian-dbw** [comment]
@IoTFier and @micahgoodreau, the issue you reported here is unrelated to the original issue opened by @mazhar10, so I hided your comments as "Off Topic".
For your issues, please see https://github.com/PowerShell/PSReadLine/issues/3001#issuecomment-965569302 for fixes, and https://github.com/PowerShell/PSReadLine/issues/3001#issuecomment-966568775 for why it happened to you.

**Comment by daxian-dbw** [comment]
@iSazonov Let's keep this one open for now, and keep an eye on any incoming similar reported.

**Comment by iSazonov** [comment]
> Failed to create CoreCLR, HRESULT: 0x80004005

@daxian-dbw I guess it is known issue - pwsh cannot create a named pipe or something else in user temp folder.

**Comment by asishm-wk** [comment]
> Did you try to run as admin? I am having similar issue on windows 10, after installing pwsh 7.2. My pwsh doesn't show anything as a normal user (except the blinking cursor). But works fine when it's run as admin.

Same here. On Windows 10, I just updated to 7.20 - I just get a blinking cursor as a normal user but it works fine when run as admin. This is a big breaking change.

**Comment by mazhar10** [comment]
> 
> 
> > Did you try to run as admin? I am having similar issue on windows 10, after installing pwsh 7.2. My pwsh doesn't show anything as a normal user (except the blinking cursor). But works fine when it's run as admin.
> 
> Same here. On Windows 10, I just updated to 7.20 - I just get a blinking cursor as a normal user but it works fine when run as admin. This is a big breaking change.

I did try it on Windows 11 as admin, same issue with "Failed to create CoreCLR" message.

**Comment by daxian-dbw** [comment]
@asishm-wk from your description, it doesn't seem to be same issue reported here -- what @mazhar10 observed is that pwsh crashed with a CLR exception.
Can you open a new issue with detailed information of what you observed? Please also provide screenshot if possible.

**Comment by daxian-dbw** [comment]
@mazhar10 This CLR exception happens usually when CLR failed to create the named pipes for debugging and profiling in the `TMP` folder, see details in https://github.com/PowerShell/PowerShell/issues/13166#issuecomment-660358397. 

Can you try disabling CoreCLR diagnostics by setting the environment variable `export COMPlus_EnableDiagnostics=0` (as [instructed here](https://github.com/dotnet/coreclr/pull/15878)), and then try running your repro step again to see if that helps?

**Comment by mazhar10** [comment]
> 
> 
> @mazhar10 This CLR exception happens usually when CLR failed to create the named pipes for debugging and profiling in the `TMP` folder, see details in [#13166 (comment)](https://github.com/PowerShell/PowerShell/issues/13166#issuecomment-660358397).
> 
> Can you try disabling CoreCLR diagnostics by setting the environment variable `export COMPlus_EnableDiagnostics=0` (as [instructed here](https://github.com/dotnet/coreclr/pull/15878)), and then try running your repro step again to see if that helps?

I tried that with no joy. Here is what I did:
open a command window.
Execute: set COMPlus_EnableDiagnostics=0
Execute: start pwsh.

pwsh fails with the reported error.
The results are the same if the cmd window is opened as an administrator..

**Comment by iSazonov** [comment]
@mazhar10 What is temp directory in the user session? Can you confirm the user has full permissions to the directory and there is no security application blocking operations on the temp directory?

**Comment by mazhar10** [comment]
> 
> 
> @mazhar10 What is temp directory in the user session? Can you confirm the user has full permissions to the directory and there is no security application blocking operations on the temp directory?

The temp directory for the user session is %appddata%\..\Local\temp.
There is nothing blocking operations to this directory - as the user, I can edit, delete files and subdirectories under temp just fine.

**Comment by daxian-dbw** [comment]
@mazhar10 Can you collect .NET startup traces and share the trace file here?

From CMD.exe
```
set COREHOST_TRACE=1
set COREHOST_TRACEFILE=host.txt
<Run pwsh 7.2>
set COREHOST_TRACE=0
```

> This should produce host.txt with lot of detailed tracing. Please note that the file may contain information about the machine, local paths and env. variables. Make sure you're OK to share it first. I think the interesting part will be the few lines around the failure (should be near the end of the file).

**Comment by daxian-dbw** [comment]
Opened https://github.com/dotnet/runtime/issues/61740. We will see what the .NET team say about this crash.

**Comment by iSazonov** [comment]
I think they need the process dump. And I assume it's because of an unsupported CPU.

**Comment by mazhar10** [comment]
7.2.1 works fine.

**Comment by daxian-dbw** [comment]
@mazhar10 Thanks for reporting back. It could be something fixed in .NET 6.0.1, which is what PS 7.2.1 based off.
