### ISSUE TITLE
CLI: -File misinterprets any argument that starts with `-` (hyphen) and contains a `:` (colon) as a parameter-name-value combination (named argument)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16432]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create file `t.ps1`:

```powershell
@'
param($A, $B)

"`$A: [$A]"
"`$B: [$B]"
'@ > t.ps1
```

Then invoke it as follows:

```powershell
pwsh -nop -file t.ps1 -A foo -B "-:"
```

The problem is that _any_ combination of an initial `-` followed by a `:` anywhere in the remainder of the argument causes the argument to be misinterpreted as a
`-<parameter-name>:<value>`-style argument, i.e. as a _named_ argument that includes its target parameter name, instead of as a verbatim string value that binds to argument `-B`.

It is debatable what the correct behavior should be if the argument actually looks like a valid parameter(-name)-argument combination, such as `"-C:bar"` (note that on Unix PowerShell won't be able to tell whether quoting was originally used or not, which from within PowerShell serves to disambiguate between `-C:bar` (parameter-argument) and `'-C:bar'` (argument only). If it is `"-C :bar"` (note the space), it should definitely be an argument only.

### Expected behavior

```console
$A: [foo]
$B: [-:]
```

### Actual behavior

An error occurs, because `-:` isn't recognized as an _argument_ for parameter `-B`.

### Error details

```console
t.ps1: Missing an argument for parameter 'B'. Specify a parameter of type 'System.Object' and try again.
```

### Environment data

```powershell
PowerShell Core 7.2.0
```

**Comment by juwens** [comment]
second that, stumbled upon that, when i tried something fancy:

"pwsh .\build_script.ps1 --target=Build "--AdditionalMsBuildArgs=-p:Foobar=True"

gave me three items in $args
```
--target=Build
--AdditionalMsBuildArgs=-p
p:Foobar=True
```

$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by juwens** [comment]
haha, MSFT invests zero effort into the issue for two years and then closes it. well played.

**Comment by FlorianKirmaier** [comment]
Just a push that gets ignored.
This issue drives me crazy.

**Comment by juwens** [comment]
@FlorianKirmaier you can try `--%` the "[the-stop-parsing-token](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.5#the-stop-parsing-token)"

to make the example of the ticket author work, place it somewhere before the "evil" string

```
pwsh -nop -file t.ps1 -A foo -B --% "-:"
                                ^^^
```

<img height="50" alt="Image" src="https://github.com/user-attachments/assets/1b1b71b2-e600-429f-8cdb-a79ae048f1b4" />

When you execute this line inside an pwsh (tested with pwsh 7.5) you can place it as early as you like.  
When you execute this line in cmd, it only works if placed directly before `"-:"`, like in the first example
```
pwsh --% -nop -file t.ps1 -A foo -B "-:"
     ^^^
```

<img height="50" alt="Image" src="https://github.com/user-attachments/assets/529725e8-e403-4218-af88-5cefd10cbe0e" />


## called from cmd

<img height="150" alt="Image" src="https://github.com/user-attachments/assets/242210e9-cedf-4b62-bb4a-666c04e2335c" />

**Comment by stevenwdv** [comment]
@juwens From CMD `--%` doesn't seem to do anything useful. I'm trying to call PowerShell with `-s:a` but it becomes `-s` `a` regardless of `--%`. For `-s:` it just seems to skip the argument when prefixed with `--%`.


Really wish this would be fixed or that there's a workaround

**Comment by stevenwdv** [comment]
I now see that this was closed just because of a lack of activity. I hope that maybe someone can reopen this?
