### ISSUE TITLE
Set-Clipboard should copy data to clipboard after formatting has been applied

### ISSUE THREAD

**Issue by FireInWinter** [PowerShell/PowerShell#16431]
### Summary of the new feature / enhancement

PowerShell version : 7.2.0 (and 7.1.5)
OS: Windows 10 + Windows Server 2016

Set-Clipboard doesn't really work as expected.  It seems to do a ToString() on each object instead of using the formatting information.  As such, Set-Clipboard copies formatting information to the clipboard if you use Format-Table/Format-View.  As PowerShell now only supports plain text, this seems very pointless.  I actually use clip.exe instead of Set-Clipboard as it works closer to what I would expect on Windows.  Clip.exe also gives you something like what you see if you look at the output (really old thing WYSIWYG).  I would suggest applying formatting (Out-String -Stream) first and not calling ToString().

This doesn't seems to work at all like I would expect.  It's doing a ToString on the formatting objects, which is sort of pointless.
```
Get-ChildItem C:\ | Format-Table -Property LastWriteTime, FullName | Set-Clipboard
Get-Clipboard
Microsoft.PowerShell.Commands.Internal.Format.FormatStartData
Microsoft.PowerShell.Commands.Internal.Format.GroupStartData
Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData
...
Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData
Microsoft.PowerShell.Commands.Internal.Format.GroupEndData
Microsoft.PowerShell.Commands.Internal.Format.FormatEndData
```

However, clip.exe works more like what I expect.  
```
Get-ChildItem C:\ | Format-Table -Property LastWriteTime, FullName | clip.exe
Get-Clipboard

LastWriteTime         FullName
-------------         --------
12/7/2019 2:14:52 AM  C:\PerfLogs
11/10/2021 8:45:01 AM C:\Program Files
11/4/2021 2:58:14 PM  C:\Program Files (x86)
1/1/2021 5:24:11 PM   C:\Users
11/9/2021 9:44:30 PM  C:\Windows
```
Using clip.exe also works without doing a Format-Table.
```
Get-ChildItem C:\ | clip.exe
Get-Clipboard
    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           12/7/2019  2:14 AM                PerfLogs
d-r--          11/10/2021  8:45 AM                Program Files
d-r--           11/4/2021  2:58 PM                Program Files (x86)
d-r--            1/1/2021  5:24 PM                Users
d----           11/9/2021  9:44 PM                Windows
```

Set-Clipboard seems it is doing a ToString on each object and then putting that in the clipboard (basically just the FullName property).  This isn't going to be useful very often.  It would be like Export-CSV just doing a ToString() on each object (not on the individual properties).
```
Get-ChildItem C:\ | Set-Clipboard
Get-Clipboard
C:\PerfLogs
C:\Program Files
C:\Program Files (x86)
C:\Users
C:\Windows
```
I can get the same thing as Clip.exe if I use Out-String -Stream, but that isn't very nice to have to do it every time.  I have to include the -Stream parameter or it is just one string object that can have issues.
```
Get-ChildItem C:\ | Out-String -Stream | Set-Clipboard
Get-Clipboard
    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           12/7/2019  2:14 AM                PerfLogs
d-r--          11/10/2021  8:45 AM                Program Files
d-r--           11/4/2021  2:58 PM                Program Files (x86)
d-r--            1/1/2021  5:24 PM                Users
d----           11/9/2021  9:44 PM                Windows
```

### Proposed technical implementation details (optional)

Set-Clipboard should implicitly call Out-String -Stream instead of ToString() per object.  That way it is much easier to capture what you see on the screen.

**Comment by mklement0** [comment]
Conceptually related: `Select-String` too should apply `Out-String -Stream` implicitly: https://github.com/PowerShell/PowerShell/issues/10726#issuecomment-567628146

**Comment by FireInWinter** [comment]
@mklement0 Having Select-String do the same thing makes sense.  I think Set-Clipboard should be an even easier sell than that as the whole purpose is to copy plain text to the clipboard.  I frequently use Format-Table * | clip currently.  It works good and makes it easy to paste into Slack (as code).  Set-Clipboard doesn't need to worry about the performance implications of formatting the output as you don't normally put a million rows into your clipboard.  If you are doing more than a few thousand lines, you would probably be better off exporting your data a different way.

**Comment by FireInWinter** [comment]
Another issue is that the color codes are copied to the clipboard as well.  As far as I can see, there really isn't a good reason to be catching those as I haven't pasted them anywhere that uses them for the color.  This includes pwsh.  I guess I can open that as a new issue though.
