### ISSUE TITLE
7.2.0 win-fxdependent release packages do not include pwsh.exe

### ISSUE THREAD

**Issue by ajansveld** [PowerShell/PowerShell#16448]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- Install the .NET Desktop Runtime 6.0.0
- Download and expand PowerShell-7.2.0-win-fxdependent.zip or PowerShell-7.2.0-win-fxdependentWinDesktop.zip
- Run pwsh.exe

### Expected behavior

```console
PowerShell 7.2.0 starts (this worked in 7.2.0 RC1).
```

### Actual behavior

```console
Executable is not present, have to run 'dotnet pwsh.dll'.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@adityamandaleeka Is this intentional? I know some work was done to remove the executable from global tool.

**Comment by daxian-dbw** [comment]
According to @adityapatwardhan, this is intentional because the previously shipped `pwsh.exe` is platform specific, while a FxDependent package shouldn't be platform specific.

**Comment by adityapatwardhan** [comment]
Yes, that is correct. The executable is specific to the platform which it is built on. More information here: https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent

The guidance is to use `dotnet pwsh.dll` to use the framework dependent package.

**Comment by ajansveld** [comment]
That sounds like a breaking change from the RC1 release. Where was this documented?

It is my understanding that a framework-dependent app can still produce a platform-specific executable. The fact that the package is called PowerShell-7.2.0-**win**-fxdependent.zip certainly leads people to believe that this is meant for Windows only. I'd argue that if a truly cross-platform package is needed it should be published separately under a different name. 

Since PowerShell-7.2.0-win-fxdependentWinDesktop.zip will **never** be cross-platform since it depends on WinForms and WPF, can we please have pwsh.exe back?

**Comment by daxian-dbw** [comment]
`-win-` indicates it's for Windows, but doesn't indicate the process architecture it's targeting. For example, you should be able to use the FxDependent package on ARM64 or ARM32 windows. A platform specific executable won't work in that case.

**Comment by ajansveld** [comment]
This has been fixed (for different reasons) in https://github.com/PowerShell/PowerShell/pull/16535.
