### ISSUE TITLE
Distribution Support Request - OpenSuse leap 15.3

### ISSUE THREAD

**Issue by signed-log** [PowerShell/PowerShell#16446]
### Name of the Distribution

openSUSE

### Version of the Distribution

Leap 15.3

### Package Types

- [ ] Deb
- [X] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

amd64

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [x] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by adityapatwardhan** [comment]
@PowerShell/powershell-committee - Please guide us if there is enough interest in this for us to work on supporting this distribution. This would need additional testing for each release which supports this.

**Comment by JamesWTruher** [comment]
@powershell-committee has reviewed this request, and our current position is that adding any new release to our current list of supported platforms would be cost prohibitive.

**Comment by adityapatwardhan** [comment]
We are not planning on officially supporting OpenSuse leap with .RPM package. The package for RedHat might work but is not officially tested. The other option would be to use the tar.gz but it is not supported or tested either.
