### ISSUE TITLE
Distribution Support Request - OpenSUS Leap 15.3 ARM64

### ISSUE THREAD

**Issue by signed-log** [PowerShell/PowerShell#16447]
### Name of the Distribution

openSUSE

### Version of the Distribution

Leap 15.3

### Package Types

- [ ] Deb
- [X] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

arm64

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by TravisEz13** [comment]
FYI are ARM test resources are currently EXTREMELY limited.  This is unlikely to be officially supported any time soon.

**Comment by adityapatwardhan** [comment]
@PowerShell/powershell-committee  - This is similar to distribution request for x86_x64. Please let us know if we would work on this if there is enough interest.

**Comment by JamesWTruher** [comment]
@PowerShell/powershell-committee has reviewed this request, and our current position is that adding any new release to our current list of supported platforms would be cost prohibitive.

**Comment by TravisEz13** [comment]
Lack of official support doesn't prevent community support.  Try out the RPM, my experience is that no changes are needed for most distributions.
