### ISSUE TITLE
$Host.PrivateData colors are completely broken in PowerShell 7.2

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#16441]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`$PSStyle` has completely broken the PrivateData colors. Setting them no longer changes anything.

![image](https://user-images.githubusercontent.com/192942/141235572-13f54390-51d2-4069-8952-6188eefba82b.png)

### Expected behavior

```console
The colors on `$Host.PrivateData` should affect the output
```

### Actual behavior

```console
Changes to `$Host.PrivateData` don't do anything anymore
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

This is what I expected:
![image](https://user-images.githubusercontent.com/192942/141236901-724dbf60-77d5-430f-bdf4-3e9ae6174dab.png)

**Comment by iSazonov** [comment]
$Host.PrivateData works if there is no virtual terminal or it is disabled.

**Comment by 237dmitry** [comment]
> Setting them no longer changes anything.

If I change `$PSStyle.Progress.View` to `Classic` then the progress colors are from `$Host.PrivateData.Progress*`

**Comment by dwtaber** [comment]
Hm.  Error output obeys `$Host.PrivateData.ErrorForegroundColor` but not `$Host.PrivateData.ErrorBackgroundColor` for me, and only when `$ErrorView = ConciseView`.  For any other value of `$ErrorView`, no coloration is applied.

Meanwhile, the `Get-Error` cmdlet applies `$PSStyle.Formatting.Error` coloration to the value of the returned object's `Exception.Message` property, as well as to the position-marking tildes of `InvocationInfo.PositionMessage`

**Comment by Jaykul** [comment]
So **WITH NO NOTICE** a bunch of code was broken that customized error and verbose output colors, and **there is now no way** to customize them in a **compatible** fashion, except to feature-sniff for types/versions and _do it both ways_.

I raised this MONTHS AGO as a **_REGRESSION BUG_** and I feel like it was completely brushed off and basically ignored. 

What is going on with prioritization of development over there?!?

**Comment by SteveL-MSFT** [comment]
@dwtaber Error for classic view was a bug that was fixed via https://github.com/PowerShell/PowerShell/pull/17705

@Jaykul the WGs are working through issues, but haven't gotten to this one.  I would propose to have a new `$PSStyle.Formatting.UsePrivateDataColors` set to `$true` by default which would have the old stream output use the old settings.  We could automatically flip this to `$false` if any of the new formatting colors are set.

**Comment by Jaykul** [comment]
Maybe the more helpful thing would be to continue using PSStyle, but **update PSStyle** when the PrivateData values are set.

That is, if something does: `$Host.PrivateData.ErrorForeground = "Red"` then update `$PSStyle.Formatting.Error += "`e[31;1m"` (optionally, you could remove existing foreground colors, but it doesn't really matter **too** much)

**Comment by SteveL-MSFT** [comment]
@Jaykul that's is also an option.  The only problem is if then the user updates `$PSStyle`, it would not be possible to reflect that back into `PrivateData` unless they happen to use one of the 8 colors only.

**Comment by SteveL-MSFT** [comment]
Actually, there's a problem with your proposal.  `$Host.PrivateData` is managed by the host (ConsoleHost, EditorServices, etc...), so every host would have to adopt that pattern.  `PrivateData` is just a PSObject so a host can have whatever they want in there.  The colors are just a de facto convention.

**Comment by Jaykul** [comment]
I think going one way would probably be good enough. I mean, I have code for converting from 16bit colors to 16 colors.

**Comment by Jaykul** [comment]
> Actually, there's a problem with your proposal. `$Host.PrivateData` is managed by the host (ConsoleHost, EditorServices, etc...), so every host would have to adopt that pattern. `PrivateData` is just a PSObject so a host can have whatever they want in there. The colors are just a de facto convention.

So what you're saying is that the HOST is still trying to set the colors, but the engine is injecting escape sequences into the text that override the host's settings?

**Comment by SteveL-MSFT** [comment]
`Write-Error`, `Write-Verbose`, etc... are host callbacks.  It's up to the host to decide how to display them.  Here's the relevant section for ConsoleHost: https://github.com/PowerShell/PowerShell/blob/edac193cf05a540b1f5f59f23fd1eb29c2776ce1/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L1395-L1402.  Currently, if VT is supported, it goes the VT route and by-passes the older code path that relies on `[Console]` APIs that accept `[ConsoleColor]` and overrides the color codes in the string (the string value still contains them).

So in the end, it's up to the host to decide what to do.  This was an unfortunate design choice early on.

**Comment by Jaykul** [comment]
So, bottom line: you added a _non-host_ way of injecting virtual terminal escape sequences, _and then_ changed the default host so that if it thinks it's running in a terminal that supports escape sequences ... it ignores **it's own settings**. 

Is that right? Is backward compatibility just out the window forever?

**Comment by SteveL-MSFT** [comment]
I've proposed a solution due to the limitations of the existing design.  You had a different proposal which seemed good at first until I looked into it and it's not feasible.  If you have an alternate proposal, let's discuss it.

**Comment by Jaykul** [comment]
I'm frustrated, but I don't know _how_ I didn't understand that you'd deliberately deprecated PrivateData. Honestly, I don't think there's any point in putting a switch in. It would basically be the same as setting `$ENV:TERM = "dumb"` right?

Writing a warning that they're deprecated when someone sets those properties (in a host that `SupportsVirtualTerminal`?) would be nice, so people can be reminded those things are now useless ... but unless we can do that, I think we might as well just close this "as designed". 😣

**Comment by poidah** [comment]
I've just started reading about this and I can't believe **in 7 years nothing has been done**.

The time spent arguing about this since @Jaykul first asked about it on **Sep 29, 2016**, could have been used to implement his rather straight forward request.

There does need to be any breaking changes, just override the **Write-Host** to allow for **HEX** values for **ForegroundColor**.

The terminal window is not a graphic design tool, the RGB space is perfectly sufficient and slight display variations are the least of a coder's problems.

We just want a way of distinguishing one thing from another in the terminal - this doesn't have to made into rocket science. 

Interlectual wars aside, this is would benefit everyone - [Support for RGB console colors](https://github.com/PowerShell/PowerShell/issues/16442#issue-1050569479)

**Comment by theJasonHelmick** [comment]
The Interactive WG has reviewed this long standing issue.  We don't think that PrivateData can be linked well to PSStyle to remove a poor affect from PrivateData. We think the current behavior of PSStyle was the intended design change, however we want to review this committee before closing this issue.

**Comment by theJasonHelmick** [comment]
Thank you to all that commented on this issue.  The PowerShell committee has reviewed and concurs with the Interactive WG that this feature is by designed.  We will investigate in the future to emit a depreciation warning if any private data is changed.
