### ISSUE TITLE
update package dependency list for Linux packages

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#16451]
https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/tools/packaging/packaging.psm1#L1287-L1300

is missing some packages:

Here is .NET's list for they snap package, so they obviously use it :(
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/installer/pkg/snap/snapcraft.yaml#L33

Here is a json that describes all the package dependencies for .NET 6
[core/runtime-deps.json at 1d9c0f45e2d87c13ba262865f0c410d6e44ecaea · dotnet/core (github.com)
](https://github.com/dotnet/core/blob/1d9c0f45e2d87c13ba262865f0c410d6e44ecaea/release-notes/6.0/runtime-deps.json)

**Comment by iSazonov** [comment]
libtinfo5 is present in first file and not in second one. 😕

**Comment by TravisEz13** [comment]
I'll ask .NET...

**Comment by TravisEz13** [comment]
libtinfo5 is only required for building

**Comment by adityapatwardhan** [comment]
Already fixed.
