### ISSUE TITLE
The reader's MaxDepth of 64 has been exceeded

### ISSUE THREAD

**Issue by xenadmin** [PowerShell/PowerShell#16457]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PowerShell 7.2.0 (The error does not appear with PowerShell 7.0 LTS or with 7.1.5.)
Install VMware PowerCLI
Import Module: https://github.com/vmware/PowerCLI-Example-Scripts/blob/master/Modules/Backup-VCSA/**Backup-VCSA.psm1**
Connect-CisServer
Get-VCSABackupJobs

### Expected behavior

```console
Receive information from PowerCLI API.

The error does not appear with PowerShell 7.0 LTS or with 7.1.5.
```

### Actual behavior

```console
The reader's MaxDepth of 64 has been exceeded.
```

### Error details

```console
Get-CisService: 12.11.2021 17:19:49 Get-CisService  One or more errors occurred. (One or more errors occurred. (The reader's MaxDepth of 64 has been exceeded. Path
'result.output.STRUCTURE['com.vmware.vapi.metadata.metamodel.component_data'].info.STRUCTURE['com.vmware.vapi.metadata.metamodel.component_info'].packages[7].STRUCTURE.map-entry.value.STRUCTURE['com.vmware.vapi.metadata.metamodel.packa
ge_info'].services[0].STRUCTURE.map-entry.value.STRUCTURE['com.vmware.vapi.metadata.metamodel.service_info'].structures[6].STRUCTURE.map-entry.value.STRUCTURE['com.vmware.vapi.metadata.metamodel.structure_info'].fields[5].STRUCTURE['co
m.vmware.vapi.metadata.metamodel.field_info'].type.STRUCTURE['com.vmware.vapi.metadata.metamodel.type'].generic_instantiation.OPTIONAL.STRUCTURE['com.vmware.vapi.metadata.metamodel.generic_instantiation'].element_type.OPTIONAL.STRUCTUR
E['com.vmware.vapi.metadata.metamodel.type'].generic_instantiation.OPTIONAL.STRUCTURE['com.vmware.vapi.metadata.metamodel.generic_instantiation'].map_value_type.OPTIONAL.STRUCTURE['com.vmware.vapi.metadata.metamodel.type'].generic_inst
antiation.OPTIONAL.STRUCTURE['com.vmware.vapi.metadata.metamodel.generic_instantiation'].map_value_type.OPTIONAL.STRUCTURE['com.vmware.vapi.metadata.metamodel.type'].generic_instantiation.OPTIONAL.STRUCTURE['com.vmware.vapi.metadata.me
tamodel.generic_instantiation'].element_type', line 1, position 567214.))

Get-CisService: 12.11.2021 17:19:49 Get-CisService  CisService with name 'com.vmware.appliance.recovery.backup.job' was not found using the specified filter(s). 

Write-Error: Cannot bind argument to parameter 'Exception' because it is null.
```

### Environment data

```powershell
Debian 10 amd64

PS /usr/lib/zabbix/externalscripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> The reader's MaxDepth of 64 has been exceeded.

It comes from Newtonsoft serializer.

**Comment by daxian-dbw** [comment]
Thanks @iSazonov, this information is very helpful.
Quoted from: https://stackoverflow.com/a/68580426:
> In Json.NET [13.0.1](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/13.0.1), Newtonsoft changed the default MaxDepth for JsonReader (and hence all derived reader types including JsonTextReader) to 64:
>> Change - JsonReader and JsonSerializer MaxDepth defaults to 64

The `ConvertFrom-Json` command in PowerShell already specified the `MaxDepth` in `JsonSerializerSettings`, so it should not be affect. Therefore, it's likely that the PowerCLI module is directly calling APIs from `Newtonsoft.Json.dll`, and should be updated accordingly. @xenadmin can you please open an issue in https://github.com/vmware/PowerCLI-Example-Scripts about this?

https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs#L179-L187

**Comment by daxian-dbw** [comment]
Opened issue: https://github.com/vmware/PowerCLI-Example-Scripts/issues/494

**Comment by xenadmin** [comment]
@daxian-dbw Thank you very much for reviewing my issue. Although I'm not sure how to open an issues for VMware's PowerCLI, I didn't found a public bug tracker. I have the feeling that the example script repo is not the right place, as the issue is not with the example scripts, but with the PowerCLI commands itself (as far as I can tell).
