### ISSUE TITLE
Add Get-Help -Online support for the about_ topics

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#16452]
### Summary of the new feature / enhancement

As about_ articles are just .txt files and don't have a HelpUri attached to them, why can't we with Update-Help download an additional text file with the mappings about_topic<->Uri for all about_ articles. When we specify -Online, Get-Help could get the Uri from that file.

**Comment by theJasonHelmick** [comment]
This is an interesting idea. No matter what approach we take to improve this, it would require new features in the Help system and it would still not fix this for PowerShell 5.1. Ideally, we should look at creating an object model for about_ articles so that we can assign HelpUri links.
