### ISSUE TITLE
Add Windows display version to CIM/WIM instance(s)

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#16450]
### Summary of the new feature / enhancement

On the Windows Settings > System > About page, the "Windows specifications" section presents the following information.
```
Edition Windows 10 Enterprise
Version     20H2
OS build    19042.1288
```
Using the following reports the Version member as 19042.1288.

```
(Get-CimInstance -ClassName 'Win32_OperatingSystem').Version
```
Where can `20H2` be found in a CIM instance? I cannot find it in any of the following CIM instances.
```
CIM_OperatingSystem
Win32_OperatingSystem
Win32_SystemOperatingSystem
```

Most text from https://stackoverflow.com/q/69930904/447901

I posted on the Feedback Hub at https://insider.windows.com/en-us/feedbackhub/fb?contextid=58&feedbackid=dc091760-7f18-42ab-88bf-ba928019f3c4&form=1&utm_source=product-placement&utm_medium=feedback-hub&utm_campaign=feedback-hub-redirect

**Comment by jborean93** [comment]
This isn't really a question for PowerShell, the WMI/CIM classes are separate products and are integrated in Windows, PowerShell just retrieves the information for you.

Most likely the simplest option here is to obtain it from the registry as per your stackoverflow link.

**Comment by Liturgist** [comment]
Version information about the operating system should be available through CIM.

I can agree that Microsoft has made up a wide variety of labels for product versioning.

This is "Windows 10"
This one is build "19042"
But, sometimes you have to know something extra like "19042.1288"
But, sometimes we call it "20H2"

As a cross-platform tool, how will PowerShell make sense of all this?
