### ISSUE TITLE
we need a way to run all of our tests, not just CI

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#1646]
Currently, we only run Describe blocks tagged with `CI` and are not running tests tagged `Feature`, `Scenario`, or `Slow`. We really should have a way to regularly run all of our tests.

**Comment by TravisEz13** [comment]
Design Proposal:

- [ ] 1.  Refactor the AppVeyor.yml PowerShell code into a module
- [ ] 2. Refactor code which should be in build.psm1 into appVeyor.yml and the other way around
- [ ] 3. Add the code to AppVeyor.yml to allow for a scheduled build
- [ ] 4. Create a new AppVeyor Project and set it up to only run on a schedule
- [ ] 5. Add a badge for the daily build to the readme.

**Comment by TravisEz13** [comment]
Done
