### ISSUE TITLE
Test-Path does not throw an exception on invalid path

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#16465]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Given this code:

```
function IsPathValid {
Param ([string]$Path)

try {
    if (Test-Path -Path $Path -ErrorAction Stop) {
        Write-Host "path $Path exists"
    } else {
        Write-Host "path $Path does not exist"
    }
} catch {
    Write-Host "caught error on $Path"
}
}

$Paths = @(
    'C:\src\t'
    ,'C:\sr|c\t'
)
foreach ($Path in $Paths) { Write-Host "calling for $Path"; IsPathValid -Path $Path }
```

On Windows PowerShell 5.1, an invalid path given to `Test-Path` produces an exception.

```
PS C:\src\t> $PSVersionTable.PSVersion.ToString()
5.1.19041.1320
PS C:\src\t> .\IsPathValid.ps1
calling for C:\src\t
path C:\src\t exists
calling for C:\sr|c\t
caught error on C:\sr|c\t
PS C:\src\t>

```
However, on PowerShell Core 7.2, an exception is not thrown.

```
PS C:\src\t> $PSVersionTable.PSVersion.ToString()
7.2.0
PS C:\src\t> .\IsPathValid.ps1
calling for C:\src\t
path C:\src\t exists
calling for C:\sr|c\t
path C:\sr|c\t does not exist
PS C:\src\t>
```

### Expected behavior

```console
PowerShell 7.2 should throw an exception when an invalid path is used with `Test-Path`.
```

### Actual behavior

```console
PowerShell 7.2 does not throw an exception when an invalid path is used with `Test-Path`.
```

### Environment data

```powershell
PS C:\src\t> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It is by-design. For all Test-* cmdlets a right design is to return true or false. We discussed this already.

**Comment by Liturgist** [comment]
> It is by-design. For all Test-* cmdlets a right design is to return true or false. We discussed this already.

I trust this was rightly categorized as a breaking change.

Is there anything available that would test the validity of a path and not just the presence or absence of an item?

**Comment by iSazonov** [comment]
> Is there anything available that would test the validity of a path and not just the presence or absence of an item?

PowerShell has a code to try the check but it is a fundamental problem since only (file) system driver know whether the path valid or no.
See `Test-Path -IsValid`.

**Comment by Liturgist** [comment]
> > Is there anything available that would test the validity of a path and not just the presence or absence of an item?
> 
> PowerShell has a code to try the check but it is a fundamental problem since only (file) system driver know whether the path valid or no. See `Test-Path -IsValid`.

@iSazonov, `-IsValid` is a good suggestion. It appears to return `$true` for items that do not exist, but for which there is a valid path. Closing.

**Comment by Liturgist** [comment]
Just a minute...

```
PS C:\src\t> Test-Path -Path 'C:\sr|c\t' -IsValid
True
```

**Comment by iSazonov** [comment]
Only reliable way to check a path validity is to try to create the path.

**Comment by jasonwoerner** [comment]
This is a confusing determination. Is it by-design that the Test-Path call using the -IsValid parameter will not provide an accurate result? It returns true in all cases. The call using IsValid does not attempt to validate the path. What is the point of the IsValid parameter and why are we accepting its useless existence?

**Comment by danielniccoli** [comment]
> It is by-design. For all Test-* cmdlets a right design is to return true or false. We discussed this already.

If you would link to the discussion, we could inform ourselves.

> Only reliable way to check a path validity is to try to create the path.

I still don't understand why PowerShell 5 is able to correctly return `False` on `Test-Path -IsValid "C:\invalid?path"` and PowerShell 7 is not.
