### ISSUE TITLE
Pipeline binding parameter, setting byValue does not take effect

### ISSUE THREAD

**Issue by Odland** [PowerShell/PowerShell#16473]
### Prerequisites

- [X] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- I can only be used for a variety of reasons 7.2.0 - preview. 5 version, but I think it is nothing too big relations with version
- I wrote powershell functions that pipe the return value of the first command as an input parameter to the second command
- But the arguments to the second command all receive the return value of the first command
- The first command
```
PS>$data = Get-Datastore
PS>$data

CapacityGb FreeSpaceGb Id                                             IsAccessible        MaxReadRate              MaxWriteRate 
---------- ----------- --                                                         ------------    -----------    ------------     ----            
1443       1374        986137d8_vs_vol_rep3                           True         0           0            0                        0

PS>$data[0] | Get-Member
     
   TypeName: Test.Models.StorageResource

Name         MemberType Definition
----         ---------- ----------
Equals       Method     bool Equals(System.Object obj)
GetHashCode  Method     int GetHashCode()
GetType      Method     type GetType()
ToJsonString Method     string ToJsonString()
ToString     Method     string ToString()
CapacityGb   Property   System.Nullable[long] CapacityGb {get;set;}
FreeSpaceGb  Property   System.Nullable[long] FreeSpaceGb {get;set;}
Id           Property   string Id {get;set;}
IsAccessible Property   System.Nullable[bool] IsAccessible {get;set;}
MaxReadRate  Property   System.Nullable[long] MaxReadRate {get;set;}
MaxWriteRate Property   System.Nullable[long] MaxWriteRate {get;set;}
Name         Property   string Name {get;set;}
Type         Property   string Type {get;set;}

```
- The second command
```
PS>get-help new-vm -full
....
PARAMETERS
    -Name <String>
        Required?                    true
        Position?                    named
        Default value
        Accept pipeline input?       false
        Accept wildcard characters?  false
-Datastore <StorageResource>

        To construct, see NOTES section for DATASTORE properties and create a hash table.

        Required?                    false
        Position?                    named
        Default value
        Accept pipeline input?       true (ByValue)
        Accept wildcard characters?  false
-VMHost <IVMHost>
        To construct, see NOTES section for VMHOST properties and create a hash table.

        Required?                    false
        Position?                    named
        Default value
        Accept pipeline input?       true (ByValue)
        Accept wildcard characters?  false
...
```
- I set byValue in the second command
```
[Parameter(ValueFromPipeline)]
    [ValidateNotNull()]
    [Test.Category('Query')]
    [Test.Models.StorageResource]
    # To construct, see NOTES section for DATASTORE properties and create a hash table.
    ${Datastore},
```
- When I pass the datastore object to the second command, the second VMhost parameter is also assigned

### Expected behavior

```console
PS>$data[0] | new-vm -name test123456 -debug 
{
  "query": "mutation CREATEVM { 
         createVM(
             input:{
                  name: "test123456", 
                  datastoreID: "986137d8_vs_vol_rep3" 
             }) 
         { taskID targetID message }
 }"
}
```
```


### Actual behavior

```
console
- I just want the Datastore parameter of the second command to get the value,But other parameters of the second command are also assigned values

```
PS>$data[0] | new-vm -name test123456 -debug 
{
  "query": "mutation CREATEVM {
         deriveVirtualMachine(
         input:{  
               name: "test123456",
               hostID: "986137d8_vs_vol_rep3",  
               storageID: "986137d8_vs_vol_rep3"
         })
         { taskID targetID message } 
   }"
}
```

### Environment data

```
powershell
PS>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 6.1.7601 Service Pack 1
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0……}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by jhoneill** [comment]
your help output shows 

```
-Datastore <StorageResource>
        Accept pipeline input?       true (ByValue)
-VMHost <IVMHost>
        Accept pipeline input?       true (ByValue)
```

So PowerShell will try to assign the object in the pipeline to both of them. 
Parameter typing is "Attempt to cast to" not "Must already be", so it looks like the piped object  can be converted to an IVMHost.     

What does [Test.Models.IVMHost]$Data[0] give ?

**Comment by Odland** [comment]
> your help output shows
> 
> ```
> -Datastore <StorageResource>
>         Accept pipeline input?       true (ByValue)
> -VMHost <IVMHost>
>         Accept pipeline input?       true (ByValue)
> ```
> 
> So PowerShell will try to assign the object in the pipeline to both of them. Parameter typing is "Attempt to cast to" not "Must already be", so it looks like the piped object can be converted to an IVMHost.
> 
> What does [Test.Models.IVMHost]$Data[0] give ?

- The [Test.Models.IVMHost]$Data[0] command cannot be executed
-Datastore and VMHost are c# objects. I used the autorest framework to generate c# code to make powershell commands.
- Datastore object properties include Id, Name, CapacityGb, and FreeSpaceGb
- VMHost object contains attributes Id, Name, ManagementIP, and Description
- My hope is in the execution $data | new - vm command, after new - vm only receive corresponding Datastore object without receiving VMhost object. I looked at the documentation and set byValue to match the type the pipe passed in. 
- Is powershell always trying to match a type, rather than having to match a type?

**Comment by jhoneill** [comment]
Ah. Autorest claims another victim. 

Last point first. PowerShell as an interpreted scripting language tries to flatten out types as far as it possibly can, so a lot of places where C# would want you explicitly do "tostring" or process an expression to get a boolean PowerShell will just sort it  out: e.g. in PowerShell `2 * '5' ` is 10 but `'2' * 5` is 22222, and if you expect rigid typing everywhere that can be a culture shock.

When you decorate a PowerShell parameter with a type it is saying "cast whatever you get here as type X".  You can code validation for parameters which says "throw an error if it is not a..." but that won't help for the pipeline case. 

Now autorest...  IIRC it makes an API call with `Invoke-RestMethod` , which returns a `PSCustomObject` with a bunch of properties. It defines types for the responses, and converts the PSCustomObjects to those 
so it will build you something like  this 
```
Function Get-VMhost  {
param ($whatever_api_takes)
$customObject =    invoke-restmethod -url  blah/vmhost?params
$VMhostobject =  [vmhost]::new($customobject)
return $vmhostobject  
}
```
The constructor for VM host does something like this
```
foreach ($property in $DestinationObject.psobject.properties)  {
   if ($SourceObject.psobject.properties -contains $property) {$DestinationObject.$property = $SourceObject.$property}
} 
```
It ignores anything returned by the API which wasn't part of the object definition but it also means if you ask for 
`[vmhost]::new($Anything_with_an_id)` 
You'll get a VM host object with a nonsensical ID.  **I think that is what is happening to you**

The way around this is to avoid
```
param (
  [parameter(valueFromPipeline)]
  [type-X] $X,

  [parameter(valueFromPipeline)]
  [type-Y] $Y
)
```
When a `type-X` can be cast to a `type-Y` instead,  have 
```
Param (
 $X ,

 $Y,

[param(valueFromPipeline)]
$InputObject
)
if     ($InputObject -is [type x]) {$x = $InputObject}
elseIf ($InputObject -is [type y]) {$y = $InputObject}

if     ($x {looks like a name}) {$x = (Get-TypeX-ByName $x).id}
elseif ($x -is [Type-X]}) {$x = $x.id}
elseif ($x {doesn't look like an ID} )  {Error}
etc.
```
Do not type X and Y because (a) you'll get things cast when it is stupid to do so and (b) it forces people to provide input in a way which was the shortest way for you to code, not in the form they want. The last bit ensures whether X was piped, was passed as a variable holding an object, or a string holding a name it always becomes the ID of what you want it to be.  Don't make people write  
```
Process-Widget -widget (Get-Widget -name "Mine").id
```
Instead of
```
Process-Widget $w
``` 
or 
```
Process-Widget mine
```
