### ISSUE TITLE
Background jobs are stopped when Ctrl-c is used to interrupt the foreground program

### ISSUE THREAD

**Issue by rsauex** [PowerShell/PowerShell#16472]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Background jobs are be stopped along with the foreground one when Ctrl-c is pressed.

Steps to reproduce:

1. Create a background job:
```
PS> sleep 1000 &

Id     Name            PSJobTypeName   State         HasMoreData     Location
--     ----            -------------   -----         -----------     --------  
1      Job1            BackgroundJob   Running       True            localhost 
```

2. Check that it's running (PID is 3707):
```
PS> ps --forest -g (ps -o sid= -p $PID).Trim()
    PID TTY          TIME CMD
   3662 pts/0    00:00:00 bash
   3668 pts/0    00:00:01  \_ pwsh
   3688 pts/0    00:00:00      \_ pwsh
   3707 pts/0    00:00:00      |   \_ sleep
   3722 pts/0    00:00:00      \_ ps
```

3. Run a program and interrupt it by pressing `Ctrl-c`:
```
PS> sleep 1000
^C
```

4. Notice that the background job is not running anymore:
```
PS> ps --forest -g (ps -o sid= -p $PID).Trim()
    PID TTY          TIME CMD
   3662 pts/0    00:00:00 bash
   3668 pts/0    00:00:01  \_ pwsh
   3799 pts/0    00:00:00      \_ ps
```

### Expected behavior

```console
Background jobs should continue running after the foreground process is stopped
```

### Actual behavior

```console
Background jobs are stopped
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-rc.1
PSEdition                      Core
GitCommitId                    7.2.0-rc.1
OS                             Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@JamesWTruher are you interested in taking a look at this issue?
