### ISSUE TITLE
RegistryProvider not present in PowerShellStandard.Library

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#16475]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a C# binary cmdlet that references the `PowerShellStandard.Library`

> <PackageReference Include="PowerShellStandard.Library" Version="5.1.0" PrivateAssets="all" />

Try to reference the [RegistryProvider](https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/System.Management.Automation/namespaces/RegistrySecurity.cs) type

```csharp
using Microsoft.PowerShell.Commands;
using System;
using System.Management.Automation;

namespace MyNamespace
{
    [Cmdlet(
        VerbsCommon.Remove, "MyCmdlet",
        DefaultParameterSetName = "Path",
        SupportsShouldProcess = true
    )]
    public class RemoveTest : PSCmdlet
    {
        private string[] _paths = new string[0];
        private bool _shouldExpandWildcards;

        [Parameter(
            Mandatory = true,
            ValueFromPipeline = false,
            ValueFromPipelineByPropertyName = true,
            ParameterSetName = "LiteralPath")
        ]
        [Alias("PSPath")]
        [ValidateNotNullOrEmpty]
        public string[] LiteralPath
        {
            get { return _paths; }
            set { _paths = value; }
        }

        [Parameter(
            Position = 0,
            Mandatory = true,
            ValueFromPipeline = true,
            ValueFromPipelineByPropertyName = true,
            ParameterSetName = "Path")
        ]
        [ValidateNotNullOrEmpty]
        public string[] Path
        {
            get { return _paths; }
            set
            {
                _shouldExpandWildcards = true;
                _paths = value;
            }
        }

        protected override void ProcessRecord()
        {
            foreach (string path in _paths)
            {
                ProviderInfo provider;
                PSDriveInfo drive;
                List<string> regPaths = new List<string>();
                if (_shouldExpandWildcards)
                {
                    regPaths.AddRange(this.GetResolvedProviderPathFromPSPath(path, out provider));
                }
                else
                {
                    regPaths.Add(this.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
                        path, out provider, out drive));
                }

                if (provider.ImplementingType != typeof(RegistryProvider))
                {
                    // Filter out any paths that aren't a registry path.
                    continue;
                }

                foreach (string regPath in regPaths)
                {
                    // Do work here
                }
            }
        }
    }
}
```

I'm unsure whether this is done on purpose for cross platform uses, I have a workaround but not sure if this should be fixed for others.

### Expected behavior

```console
No failure, can reference `RegistryProvider`.
```

### Actual behavior

```console
> C:\temp\AdvReg\src\Commands\RegLink.cs(70,57): error CS0246: The type or namespace name 'RegistryProvider' could not be found (are you missing a using
directive or an assembly reference?) [C:\temp\AdvReg\src\AdvReg.csproj]
```

### Error details

```console
No ps error, it is a compile error.
```

### Environment data

```powershell
Not a problem in pwsh itself but with `PowerShellStandard.Library` not containing the reference.
```

**Comment by daxian-dbw** [comment]
@JamesWTruher Can you please take a look?

**Comment by bergmeister** [comment]
Because PowerShell Standard was created to be able to target both Windows PowerShell and PowerShell Core, which is now cross platform I can understand why the registry was not added as non-Windows systems do not have a registry. PowerShell Standard is not the solution to everything unfortunately and where the standard does not fit, you'll still have to multi-target.
Unless we want to do something special for Windows like a Windows specific Standard, I fear this might be 'by design'
