### ISSUE TITLE
Add milliseconds parameter to New-Timespan

### ISSUE THREAD

**Issue by alexis-spx** [PowerShell/PowerShell#16486]
### Summary of the new feature / enhancement

The lack of milliseconds as a parameter to New-Timespan seems like a needless omission from the parameter set.

Please could we add it, I assume it is an easy one

### Proposed technical implementation details (optional)

Add a new parameter 

        /// <summary>
        /// Allows the user to override the millisecond.
        /// </summary>
        [Parameter(ParameterSetName = "Time")]
        public int Milliseconds { get; set; }

pass it to 

result = new TimeSpan(Days, Hours, Minutes, Seconds, Milliseconds);

**Comment by NoMoreFood** [comment]
Seems like a simple and reasonable add.  I'd be willing to take care of it unless somebody has already jumped on it.

**Comment by iSazonov** [comment]
@NoMoreFood  We need to triage by WG-Cmdlets-Utility before.

**Comment by iSazonov** [comment]
Notice, there is an issue with alternative proposal for time suffixes like 10sec, 5ms and so on.

**Comment by jdhitsolutions** [comment]
Under review by the Cmdlet working group.

**Comment by jdhitsolutions** [comment]
The Cmdlet Working Group has reviewed this issue. The request is reasonable and supported in the .NET Framework. We are marking this as `Up-for-Grabs`.

**Comment by NoMoreFood** [comment]
You can assign it to me.

**Comment by fflaten** [comment]
Fixed in #17621
