### ISSUE TITLE
Inconsistent population of ErrorVariable\WarningVariable\InformationVariable when ErrorAction\WarningAction\InformationAction is Ignore

### ISSUE THREAD

**Issue by nmbell** [PowerShell/PowerShell#16491]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`ErrorVariable` is not populated when `ErrorAction` is `Ignore`.
[Documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.2#-erroraction) lists `Ignore` as an accepted value, but does not explicitly mention the expected behavior with regards to the `ErrorVariable` parameter.

`WarningVariable` is populated when `WarningAction` is `Ignore`.
[Documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.2#-warningaction) lists `Ignore` as an accepted value, but does not mention the expected behavior.

`InformationVariable` is populated when `InformationAction` is `Ignore`.
[Documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.2#-informationaction) lists `Ignore` as an accepted value, but does not explicitly mention the expected behavior with regards to the `InformationVariable` parameter.

```
$myErrors = $null
Write-Error 'Some error' -ErrorAction Ignore -ErrorVariable myerrors
$myErrors
Write-Error 'Some error' -ErrorAction SilentlyContinue -ErrorVariable myerrors
$myErrors

$myWarnings = $null
Write-Warning 'Some warning' -WarningAction Ignore -WarningVariable myWarnings
$myWarnings
Write-Warning 'Some warning' -WarningAction SilentlyContinue -WarningVariable myWarnings
$myWarnings

$myInformation = $null
Write-Information 'Some information' -InformationAction Ignore -InformationVariable myInformation
$myInformation
Write-Information 'Some information' -InformationAction SilentlyContinue -InformationVariable myInformation
$myInformation
```

The ErrorVariable\ErrorAction behavior feels intuitively correct; I think this should be implemented across the board.
Also, what about having `$Warning` and `$Information` automatic variables? Learn how it works with one, and you know how it works with all three.

### Expected behavior

```console
Should return:

Write-Error: Some error
Some warning
Some information
```
```


### Actual behavior

```console
Actually returns:

Write-Error: Some error
Some warning
Some warning
Some information
Some information
```
```


### Error details

```console
n/a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
WG-Engine:

This does look like an oversight in terms of how ActionPreference.Ignore is handled for non-Error streams. We're unsure whether it makes a lot of sense to have Ignore behave any differently to SilentlyContinue in this instance -- if this combination works it's essentially the same as simply not specifying a -WarningVariable at all.

Is there a real world use case for this?

We'll mark this as up for grabs for the time being; if anyone has the time to fix it, you're more than welcome to file a PR. 🙂

**Comment by iSazonov** [comment]
> it's essentially the same as simply not specifying a -WarningVariable at all.

But `Ignore` can be in a variable. So I'd expect all tree cases have the same behavior and _ignore_  (don't save in variable) as the keyword implies - I mean for error stream this works right and two other streams should be fixed.

**Comment by nmbell** [comment]
Sorry if I'm laboring the point, but my perspective is that the use cases are the same for all the streams. Sometimes you want to generate errors, sometimes warnings, sometimes information. Regardless of which, the way these are _handled_ should be the same. Think of the current situation from a new-user perspective: harder to train, harder to learn, harder to remember = harder to use. And that's just not PowerShell 😉.
