### ISSUE TITLE
`-match` operation is skipped when cast to `void` in the RHS of a variable assignment

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#16495]
### Steps to reproduce

Apologies for the title gore.

The compiler will skip emitting `ParserOps.MatchOperator` entirely when the expression is cast to `[void]` specifically when in the RHS of a *variable* assignment. It'll work as expected if there's no assignment or if the assignment is to `$null`.

Also if the LHS is a member expression the compiler will throw, breaking any script that contains it somewhere, but I'll make a separate issue for that.

### Expected behavior

```ps1
PS> $a = [void]('123' -match 1); $matches

Name                           Value
----                           -----
0                              1
```

### Actual behavior

```ps1
PS> $a = [void]('123' -match 1); $matches

# Nothing, $matches isn't set
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Looking at the expression tree generated by the compiler, you can see the match operation is omitted entirely.

#### Without assignment (correct)

```cs
// From { [void]('123' -match 1) } | Get-ScriptBlockDisassembly
funcContext._currentSequencePointIndex = 1;

if (context._debuggingMode > 0)
{
    context._debugger.OnSequencePointHit(funcContext);
}
ParserOps.MatchOperator(
    context,
    Fake.Const<InternalScriptExtent>("-match"),
    "123",
    1,
    false,
    true);
context.QuestionMarkVariableValue = true;
```

#### With assignment (not correct)

```cs
// From { $a = [void]('123' -match 1) } | Get-ScriptBlockDisassembly
funcContext._currentSequencePointIndex = 1;

if (context._debuggingMode > 0)
{
    context._debugger.OnSequencePointHit(funcContext);
}

// Basically equivalent of `$a = $null`
locals.Item009 = Fake.Dynamic<Func<CallSite, object, object>>(PSConvertBinder.Get(typeof(object)))(null);
context.QuestionMarkVariableValue = true;
```

**Comment by iSazonov** [comment]
If it is a broken code path are there other statement examples where compiler creates broken code?

**Comment by zett42** [comment]
Is there an actual use case of assigning a `[void]` casted `-match` result to a variable?

**Comment by SeeminglyScience** [comment]
> If it is a broken code path are there other statement examples where compiler creates broken code?

Yeah. I haven't made an issue for this yet but `$something.Value = [void]$anyExpressionHere` straight up fails to compile. Casting to void in general probably needs a closer look.

> Is there an actual use case of assigning a `[void]` casted `-match` result to a variable?

Not really, but the compiler omitting code on accident is still problematic. This was found by @JustinGrote on accident while testing some changes in the PowerShell extension for VSCode.

**Comment by SeeminglyScience** [comment]
Also for the fix, instead of replacing the converted expression with a constant `$null` it should emit an `Expression.Block` with the RHS expression and `$null`.

**Comment by SeeminglyScience** [comment]
Just to add some more test cases, it seems like most things are omitted when cast to `void` on the RHS of a variable assignment:

```powershell
$a = [void][PowerShell]::Create()

$a = [void]($ps = [PowerShell]::Create())

$a = [void][Environment]::CurrentDirectory

$a = [void]$anything.Something()

$a = [void]$(
    anything here
	including multiple statements
)
```

All of these things emit the exact same code gen of:

```csharp
locals.Item009 = Fake.Dynamic<Func<CallSite, object, object>>(PSConvertBinder.Get(typeof(object)))(null);
```
