### ISSUE TITLE
DateTime round-trip cast object -> string -> object does not work with Finnish locale

### ISSUE THREAD

**Issue by AnttiKurenniemi** [PowerShell/PowerShell#16492]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Working with datetimes as strings, I noticed that the cast to [datetime] from a string previously converted using ToString() (without specifying format) fails, if the host is using Finnish locale settings.

Example:

```
PS > $datetime = Get-Date
PS > $datetime_str = $datetime.ToString()
PS > $datetime_obj = [datetime]$datetime_str
```

I would expect that to work, but instead it throws an exception:

`InvalidArgument: Cannot convert value "19.11.2021 9.13.06" to type "System.DateTime". Error: "String '19.11.2021 9.13.06' was not recognized as a valid DateTime."`

It's a minor issue and easily circumvented, but I have had to fix a few scripts that trip over this, so I would suggest it is a bug or at least a "surprise feature" and should be corrected.

### Expected behavior

```console
PS > $datetime = Get-Date
PS > $datetime_str = $datetime.ToString()
PS > $datetime_obj = [datetime]$datetime_str

$datetime_obj now holds the same DateTime value as $datetime object.
```

### Actual behavior

```console
Exception is thrown.
```

### Error details

```console
> Get-Error

Exception             :
    Type           : System.Management.Automation.RuntimeException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot convert value "19.11.2021 10.10.01" to type "System.DateTime". Error: "Str
ing '19.11.2021 10.10.01' was not recognized as a valid DateTime."
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : -1
            Line             : $dateime_obj = [datetime]$datetime_str
            PositionMessage  : At line:1 char:1
                               + $dateime_obj = [datetime]$datetime_str
                               + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    Message        : Cannot convert value "19.11.2021 10.10.01" to type "System.DateTime". Error: "Stri
ng '19.11.2021 10.10.01' was not recognized as a valid DateTime."
    InnerException :
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "19.11.2021 10.10.01" to type "System.DateTime". Error:
"String '19.11.2021 10.10.01' was not recognized as a valid DateTime."
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
            InvocationInfo        :
                ScriptLineNumber : 1
                OffsetInLine     : 1
                HistoryId        : -1
                Line             : $dateime_obj = [datetime]$datetime_str
                PositionMessage  : At line:1 char:1
                                   + $dateime_obj = [datetime]$datetime_str
                                   + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                CommandOrigin    : Internal
            ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
        TargetSite     :
            Name          : ConvertWithCulture
            DeclaringType : System.Management.Automation.LanguagePrimitives+ConvertViaParseMethod, System.Mana
gement.Automation, Version=7.2.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert value "19.11.2021 10.10.01" to type "System.DateTime". Error: "
String '19.11.2021 10.10.01' was not recognized as a valid DateTime."
        Data           : System.Collections.ListDictionaryInternal
        InnerException :
            Type       : System.FormatException
            TargetSite :
                Name          : Parse
                DeclaringType : datetime
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Message    : String '19.11.2021 10.10.01' was not recognized as a valid DateTime.
            Source     : System.Private.CoreLib
            HResult    : -2146233033
            StackTrace :
   at System.DateTime.Parse(String s, IFormatProvider provider)
        Source         : System.Management.Automation
        HResult        : -2147467262
        StackTrace     :
   at System.Management.Automation.LanguagePrimitives.ConvertViaParseMethod.ConvertWithCulture(Object valueToConvert, T
ype resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTab
le)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    HResult        : -2146233087
CategoryInfo          : InvalidArgument: (:) [], RuntimeException
FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $dateime_obj = [datetime]$datetime_str
    PositionMessage  : At line:1 char:1
                       + $dateime_obj = [datetime]$datetime_str
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Does this work?
```
$datetime_obj = [datetime]::Parse($datetime_str)
$datetime_obj
```

**Comment by AnttiKurenniemi** [comment]
> Does this work?
> 
> ```
> $datetime_obj = [datetime]::Parse($datetime_str)
> $datetime_obj
> ```

Yes, that works correctly - no exception and the value of the object is what is expected.

**Comment by 237dmitry** [comment]
`[datetime]` uses neutral (or en-US?) culture format to parse string value on the fly. This is not only Finnish trouble. I always use `Parse` and `ParseExact` methods in the such cases.
```
[datetime] '19.11.2021' # 19th month? Error.
```

**Comment by vexx32** [comment]
Yeah, given the default .ToString() is culture-sensitive I think it makes sense for PS's default conversion path to use the culture-sensitive parse as well, and have the en-US parse used as a fallback (or vice-versa, either way should work).

**Comment by anttiah** [comment]
I don't think that typecast to `[DateTime]` is exact opposite of `.ToString()`. They are different operation and their results don't need to be compatible with each other.

The opposite operation of a typecast is another typecast:
```
C:\> [datetime][string](Get-Date)

sunnuntai 21. marraskuuta 2021 19.45.09
```

You can't expect to be able to typecast `.ToString()` output back to rich object:
```
[datetime](Get-Date).ToString()
InvalidArgument: Cannot convert value "21.11.2021 19.47.11" to type "System.DateTime". Error: "String '21.11.2021 19.47.11' was not recognized as a valid DateTime."
```

Nor can you parse typecast output (without specifying culture):
```
C:\> [datetime]::Parse([string](Get-Date))
MethodInvocationException: Exception calling "Parse" with "1" argument(s): "String '11/21/2021 19:48:56' was not recognized as a valid DateTime."
```

But you can parse `.ToString()` output (without specitying culture):
```
C:\> [datetime]::Parse((Get-Date).ToString())

sunnuntai 21. marraskuuta 2021 19.50.18
```

**Comment by vexx32** [comment]
> Basically, you are trying to inverse the output of a method by using type cast. It doesn't work like that. Of course it would be nice to be able to do so – and with certain cultures it probably works just fine – but they are two different operations and their results don't need to be compatible with each other.

Every single one of PS's type casts run through a conversion method. That semantic makes sense in C# -- sort of (it's overridable with a _method_ there anyway) -- but in PS this distinction doesn't make any sense in terms of the actual implementation, other than you can pick a different method overload and you can't directly alter the conversion logic with a typecast.

The conversion logic PS uses already uses Parse() methods, there's IMO no particular reason we can't also use current culture to aid the conversion.

**Comment by SeeminglyScience** [comment]
Seems to work if you cast all the way through, e.g.

```powershell
$datetime = Get-Date
$datetime_str = [string]$datetime
$datetime_obj = [datetime]$datetime_str
```

`ToString` is very often not the exact same as a cast. Personally, it makes sense to me that if you explicit call `ToString` then you also need to explicitly call `Parse`. Well, maybe it would have made sense to make those sync up in the first place in this instance, but if you change one of the conversion paths you'll need to change both or it just moves the problem.

**Comment by 237dmitry** [comment]
`ToString()` returns string of current culture's date and time format. And cast to string type returns neutral culture that needs for casting to datetime type.
```powershell
PS > (Get-Date).ToString(); [string] (Get-Date)
22.11.2021 20:44:16
11/22/2021 20:44:16

PS > [datetime][string] (Get-Date)  # returns localized Get-Date's output. Get-Date itself.
```

**Comment by bpayette** [comment]
PowerShell doesn't have date/time literals so, by design, casts happen in the invariant locale. This allows you to include an actual date in a script and have that script work in multiple locales. In general, we make a distinction between *processing* and *presenting*. Processing should be done in the invariant locale, presenting data to the user should be done in the current locale.
