### ISSUE TITLE
7.2.0 & ANSI escape sequences (color) not working in GitHub Actions

### ISSUE THREAD

**Issue by MSP-Greg** [PowerShell/PowerShell#16493]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

GitHub Actions windows images recently upgraded from 7.1.5 to 7.2.0.  I've got a few repos with ps1 scripts that use ANSI color codes.  The code has worked since Feb-2020.

When Actions switched to 7.2.0, the color text was rendered monochrome.  Note that a custom action (js) does render color, along with a Ruby script.  Also, I noticed no changes locally when upgrading.  The script displaying color can be run locally.

Any ideas?  With Actions, the following line is monochrome:
```ps1
Write-Host "`nThis is not color.."; Write-Host "`e[93mIs this color?`e[0m"; Write-Host "This is not color.."
```

### Expected behavior

```console
na
```

### Actual behavior

```console
na
```

### Error details

```console
na
```

### Environment data

```powershell
GitHub Actions windows images
```

**Comment by daxian-dbw** [comment]
This is likely because pwsh.exe is redirected in GitHub Action, and in 7.2, when the host is redirected, pwsh uses 'PlainText' as the output rendering style:

https://github.com/PowerShell/PowerShell/blob/fd4117e14552b6a8fa0bef6cc3c34bc67d4f8f0e/src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs#L379-L382

However, there should be a way to force using ANSI even if the host is redirected, but that seems impossible today.

**Comment by rkeithhill** [comment]
> there should be a way to force using ANSI even if the host is redirected

Agreed.  Our Jenkins build logs contain ANSI sequences from various different build tools and within Jenkins web UI those display with the appropriate colors.  Whenever I need to view the log raw, I use a browser extension (RetroTxt) to render the ANSI seqs.

**Comment by MSP-Greg** [comment]
@daxian-dbw

Thanks.  So it could be considered an 'edge case' breaking change?  Regardless, I'm ok to close...

**Comment by ClaudiuSchuster** [comment]
Same for Azure Pipelines....

with 7.1.5 ansi colors got displayed correctly, from 7.2.0 no colors in Azure DevOps Pipelines...

**Comment by ThomasPiskol** [comment]
Please don't close this issue. It's affecting valid and important use cases. 
We know so far that this issue impacts basically all major CI platforms and more likely to come:

- GitHub Actions
- Azure DevOps Pipelines
- Jenkins

From my point of view this is not an 'edge case', unless you consider CI/CD pipelines as not important.
Please also consider that this issue is present in a LTS version.

**Comment by SteveL-MSFT** [comment]
I think the correct thing here is to NOT deliberately suppress ANSI if `pwsh` is redirected and instead rely on users to set the appropriate env vars that control this behavior if they don't want ANSI

**Comment by rkeithhill** [comment]
>  env vars that control this behavior

And/or add a new pwsh command line switch `-NoAnsi`.

**Comment by ClaudiuSchuster** [comment]
I can confirm that with PowerShell 7.2.1 ANSI Colors in Azure DevOps Pipelines are displayed correctly again. 
(Without any change from our site since 7.1.5 when it worked last)

Thanks! :-)

**Comment by iSazonov** [comment]
> I can confirm that with PowerShell 7.2.1 ANSI Colors in Azure DevOps Pipelines are displayed correctly again. (Without any change from our site since 7.1.5 when it worked last)
> 
> Thanks! :-)

It wasn't a solution-just going around in circles. 😺 

All of this would have to be tested in an experimental feature, not in release...

**Comment by ClaudiuSchuster** [comment]
I want to mention that with pwsh 7.2.1 something new happens related to ANSI color codes:

With pwsh 7.1.5 and 7.2.0 you could do a 
```
$adUserString = Get-ADUser xxxx | Out-String
$adUserString -match "UserPrincipalName\s*:\s*([^\s]*)" | Out-Null
$emailAddress = $matches[1]
```
and you would get a fine EmailAddress what could be used with Send-MailMessage e.g.

with pwsh 7.2.1 this is not more working.
As $matches[1] will start with 
```
`e[0
``` 
and cmdlets like Send-MailMessage will crash if you use that match as to-address.
With pwsh 7.2.1 this is necessary now:
```
$emailAddress = $matches[1] -replace '\x1b\[[0-9;]*m',''
```

**Comment by iSazonov** [comment]
@ClaudiuSchuster  Please open new issue.
