### ISSUE TITLE
Add simpler way to add/remove file attributes

### ISSUE THREAD

**Issue by dwtaber** [PowerShell/PowerShell#16503]
### Summary of the new feature / enhancement

Inspired by #16478.  For users unaccustomed to working with flag enums, it may not be clear how to safely add or remove file attributes.  It is not intuitive, for instance, that `$Foo.Attributes += "Hidden"` does not _quite_ mean "make `$Foo` hidden."  The fact that this approach will _sometimes_ work (i.e. when the file isn't already hidden) makes it that much more surprising and confusing when it doesn't work.

I propose adding a pair of methods or cmdlets to serve as a more discoverable/intuitive wrapper for the bitwise operations that are necessary to reliably achieve a result like "if `$Foo` is hidden, remove that attribute."  Adding the `ScriptMethod`s below to `FileInfo` instances seems like a reasonably unobtrusive way to offer this feature.

### Proposed technical implementation details (optional)

```csharp
// System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
// Adding to System.IO.FileInfo region of file

newMembers.Add(@"AddAttribute");
AddMember(
    errors,
    typeName,
    new PSScriptMethod(
        @"AddAttribute",
        GetScriptBlock(@"$this.Attributes = $this.Attributes -bor [System.IO.FileAttributes]$args"),
        shouldCloneOnAccess: true),
    typeMembers,
    isOverride: false);

newMembers.Add(@"RemoveAttribute");
AddMember(
    errors,
    typeName,
    new PSScriptMethod(
        @"RemoveAttribute",
        GetScriptBlock(@"$this.Attributes = $this.Attributes -band -bnot [System.IO.FileAttributes]$args"),
        shouldCloneOnAccess: true),
    typeMembers,
    isOverride: false);
```

**Comment by iSazonov** [comment]
Make sense to generalize the proposal to Enum-s?
In the case AddAttribute/RemoveAttribute could be SetFlag, ClearFlag, IsDefined (`-is` ?).

**Comment by dwtaber** [comment]
> Make sense to generalize the proposal to Enum-s? In the case AddAttribute/RemoveAttribute could be SetFlag, ClearFlag, IsDefined (`-is` ?).

I do think a generalized version makes sense for flag enums.  I think I'd name the methods `AddFlag` and `RemoveFlag` to help distinguish them from methods like `FileInfo.SetAttributes`, which behaves more similarly to an `=` operator rather than a `+=` or `-=` operator.  I like the idea of something like `$foo -is "FlagName"`, but I'm wary of overloading `-is` when there's already an `Enum.HasFlag` method.

Honestly, my first choice would be to overload `+=` and `-=` for flag enums, but that's probably better addressed in a DotNet repo.
