### ISSUE TITLE
`Set-ScheduledTask` shouldn't accept a plain text Password

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#16502]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Along with the common security rules and defined by e.g. `PSScriptAnalyzer` rule **PSAvoidUsingPlainTextForPassword**:

> Parameter '$Password' should use SecureString,
> otherwise this will expose sensitive information.
> See ConvertTo-SecureString for more information.

Related: [StackOverflow: Hide not the output but the actual command containing sensitive info in devops logs](https://stackoverflow.com/q/70043139/1701026)

### Expected behavior

Have a [`[PSCredential]`](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.pscredential?view=powershellsdk-7.0.0) parameter instead

### Actual behavior

`Set-ScheduledTask` accepts a plain text password (`[[-Password] <String>]`)

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please use other channels to report the issue.

**Comment by iRon7** [comment]
Right, I have passed the issue to the Microsoft Feedback Hub. Unfortunately I haven't good feeling that anything happens with it as I have sent feedback ([`[AllowEmptyString()]` for `-Description` in `Set-LocalGroup`/`Set-LocalUser](https://github.com/PowerShell/PowerShell/issues/16049)`) using this hub before but never seen any responses...

**Comment by iSazonov** [comment]
> but never seen any responses

I could not find that your feedback on the Hub. Perhaps it is included in a collection? What title is there to find?

**Comment by iRon7** [comment]
I used the same title as in here, the word `ScheduledTask` should bring it up.
<sup>(note that I left the backticks in the title)</sup>
![2021-11-23_19h29_07](https://user-images.githubusercontent.com/8080834/143083403-fc7d983c-28f4-4490-bf4a-61513fe4d58e.png)
>

**Comment by iSazonov** [comment]
I can not find. Probably because I am in Windows Insider program.

**Comment by iRon7** [comment]
Thanks for checking, I have created another issue `Outsider Feedback`:
<img width="540" alt="2021-11-24_16h34_17" src="https://user-images.githubusercontent.com/8080834/143268266-e62291ac-f2e6-4602-9970-f2d949e468bf.png">
If this is also kept unnoticed, I will probably join the Insider program...

**Comment by iRon7** [comment]
Ok, I am an insider now (I think it makes quiet a difference as I can't even find back my own issues I created as an outsider...)
I have logged 3 new issues as an outsider:
* Outsider Feedback
* Set-ScheduledTask shouldn't accept a plain text Password
* [AllowEmptyString()] for -Description in Set-LocalGroup/Set-LocalUser

**Comment by iRon7** [comment]
Being a Microsoft insider member now for about 3 weeks, I feel rather disappointed.
I moved 3 issues into the insider program, but haven't seen any seen any (human) response.
Maybe the cases are not interested enough for Microsoft, but even for that I would expect at least some acknowledgement of the issues.
Sorry, for putting my grief in this case but (also) dropping it the feedback hub feels useless...

**Comment by iRon7** [comment]
Still no feedback *at all* on my `Feedback Hub` issues 😭.
I have copied them to the new Microsoft [**Feedback (web portal)**](https://feedbackportal.microsoft.com/feedback/):
* [Windows-PowerShell: Add forum for Windows-PowerShell](https://feedbackportal.microsoft.com/feedback/idea/25b997b6-4f95-ec11-a81c-0022485104c2)
* [Windows-PowerShell: Set-ScheduledTask shouldn't accept a plain text Password](https://feedbackportal.microsoft.com/feedback/idea/3b3d8ad3-4f95-ec11-a81c-0022485104c2)
* [Windows-PowerShell: [AllowEmptyString()] for -Description in Set-LocalGroup/Set-LocalUser](https://feedbackportal.microsoft.com/feedback/idea/02e0dd3f-5095-ec11-a81c-0022485104c2)
