### ISSUE TITLE
Multiple Ambiguous Error under Windows 11 but not Windows 10

### ISSUE THREAD

**Issue by markolbert** [PowerShell/PowerShell#16506]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This may be the result of me having recently built a new Windows 11 system and not configured powershell the same way as it's configured on my previous Windows 10 desktop. But I'm reporting it in case it's a real change.

I have a wake on lan powershell app I've used for several years on Windows 10. It uses the `System.Text.Json` serializer to deserialize a JSON file into a specific type of configuration object I've defined.

Under Windows 10 (all updates applied) the following call succeeds:

```PS
$config = [JsonSerializer]::Deserialize((Get-Content "c:/Users/Mark/PowerShell/Wake-Device/devices.json"), [Configuration], $null)
```

The third parameter, `$null`, is a placeholder for unneeded options.

Under Windows 11 on my new desktop this call throws the "multiple ambiguous" error, apparently because powershell cannot determine which `Deserialize()` method to call.

Removing the `$null` parameter fixes the problem.

This obviously isn't a big deal...but it's a subtle behavioral change that could cause problems. It certainly caused me to spend quite a bit of time figuring out what was going wrong :).

### Expected behavior

```console
The deserialization should succeed
```

### Actual behavior

```console
The deserialization fails if $null is passed as the third parameter
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It seems .Net issue. Please try to reproduce with simple C# app and report in .Net Runtime repository.

**Comment by daxian-dbw** [comment]
@markolbert What is the full name of the `[JsonSerializer]` and `[Configuration]` types? Also, are you using PS 7.2 on both Win10 and Win11?

**Comment by markolbert** [comment]
JsonSerializer is System.Text.Json.JsonSerializer

`Configuration` is a class defined in the psm1 file, along with `Device`:

```powershell
class Device {
	static [string]$BroadcastIP = '192.168.1.255'
	[string]$Name
	[string]$MacAddress

	[Byte[]]GetByteArray(){
		$macByteArray = $this.MacAddress -split "[:-]" | ForEach-Object { [Byte] "0x$_"}
		return (,0xFF * 6) + ($macByteArray * 16)
	}

	[void]Wake(){
		$macByteArray = $this.MacAddress -split "[:-]" | ForEach-Object { [Byte] "0x$_"}
		$magicPacket = (,0xFF * 6) + ($macByteArray * 16)

		$udpClient = New-Object System.Net.Sockets.UdpClient
		
		#$udpClient.Connect(([System.Net.IPAddress]::Broadcast), 9)
		# I have no idea why the default global address target doesn't work... but it sure doesn't!
		# no doubt some "feature" of Windows. Thanx, Microsoft :(
		$udpClient.Connect([Device]::BroadcastIP, 9)
		
		$udpClient.Send($magicPacket,$magicPacket.Length)

		$udpClient.Close()
		$udpClient.Dispose()
	}
}

class Configuration {
	[Device[]] $Devices

	[void]Wake([string]$name){
		$device = $this.Devices | Where-Object Name -eq $name

		if( $null -eq $device ){
			Write-Error "No device named $name on file"
		}
		else{
			$device.Wake()
			Write-Information -InformationAction Continue "Sent magic packet to $name at $($device.MacAddress) via $([Device]::BroadcastIP)"
		}
	}
}
```

I'm using Powershell 7.2.0 on Windows 11 and I believe that's the version I was using on Windows 10 as well (I've decommissioned that system).

**Comment by iSazonov** [comment]
> $config = [JsonSerializer]::Deserialize((Get-Content "c:/Users/Mark/PowerShell/Wake-Device/devices.json"), [Configuration], $null)

Could you please point in documentation what Deserialize() overload you use?

**Comment by markolbert** [comment]
Sorry, I thought that was clear from the original comment. This one: https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-6.0#System_Text_Json_JsonSerializer_Deserialize_System_String_System_Type_System_Text_Json_JsonSerializerOptions_

**Comment by iSazonov** [comment]
@markolbert Please point **exact** overload in docs.

**Comment by markolbert** [comment]
Please read **exact** report of problem. Here is the blasted link again! 
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-6.0#System_Text_Json_JsonSerializer_Deserialize_System_String_System_Type_System_Text_Json_JsonSerializerOptions_

That is copied directly from the URL I'm on when I'm looking at the exact overload. I don't know how to give you anything more **exact** than that.

The title of the overload is `Deserialize(String, Type, JsonSerializerOptions)`

If this is insufficient or you are incapable of figuring out what overload I'm using from all the code, links, etc. I'm providing please feel free to close this issue. Because, as I pointed out in the initial report, I solved my problem and am only reporting this in case Microsoft cares enough about having other people **not** run into the same problem to spend a **little** time looking into it.

Sheesh.

**Comment by iSazonov** [comment]
> The title of the overload is `Deserialize(String, Type, JsonSerializerOptions)`

Thanks! I asked because your link is not work as expected and doesn't open exact method description.

> If this is insufficient or you are incapable of figuring out what overload I'm using from all the code, links, etc. I'm providing please feel free to close this issue. Because, as I pointed out in the initial report, I solved my problem and am only reporting this in case Microsoft cares enough about having other people not run into the same problem to spend a little time looking into it.

It is great you want to care other people. You would save them a lot of time if you provided simpler and more accurate steps to reproduce the problem.

**Comment by iSazonov** [comment]
@daxian-dbw I guess follow conflicts
```
public static object? Deserialize (string json, Type returnType, System.Text.Json.JsonSerializerOptions? options = default);
public static object? Deserialize (string json, Type returnType, System.Text.Json.Serialization.JsonSerializerContext context);
```
Ex.:
```powershell
[System.Text.Json.JsonSerializer]::Deserialize("1", [int], $null)

MethodException: Multiple ambiguous overloads found for "Deserialize" and the argument count: "3".
```

**Comment by daxian-dbw** [comment]
@markolbert Thank you very much for providing the additional information, that helps a lot!

It's very likely you were using PS 7.1.x on the decommissioned Windows 10 machine.
PS 7.1.x is on top of .NET 5, and there is [only 1 overload that takes `String, Type` as the first 2 parameters in .NET 5](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-5.0):
```c#
JsonSerializer.Deserialize(String, Type, JsonSerializerOptions)
```
A lot more overloads were added in .NET 6, which include a new one that take `String, Type` as the first 2 parameters:
```c#
JsonSerializer.Deserialize(String, Type, JsonSerializerContext)
```
So, in PowerShell 7.2, `[JsonSerializer]::Deserialize(<string>, <type>, $null)` cannot resolve from those 2 overloads, because `$null` can be applied to both `JsonSerializerOptions` and `JsonSerializerContext`. And you will get the same error message when running 7.2 on Windows 10 as well.

It's great that you already figured out the fix 😄

**Comment by markolbert** [comment]
Thanx for the explanation!
