### ISSUE TITLE
Why does Set-Content implicitly add a newline?

### ISSUE THREAD

**Issue by MartinKiryakov** [PowerShell/PowerShell#16517]
### Summary of the new feature / enhancement

I created a Powershell script for automated updating and writing of a C header file. I use Get-Content -Raw (Which is a whole different can of worms, as to why 'Raw' is not implicit), then I use regex and finally I use Set-Content to write back to my file. In doing so, I noticed an ever-growing list of newlines at the end of my header file and as it turned out, Set-Content automatically appends a newline at the end of its contents and one must explicitly add `-NoNewLine` to avoid this. My question is, why is this the default? Is this not considered non-standard behavior? In what use case would an automatic newline append be desired?

### Proposed technical implementation details (optional)

Make the -NoNewLine parameter of Set-Content implicit, instead replace it with a parameter for explicit newline addition, i.e. -NewLine / -AddNewLine

**Comment by iSazonov** [comment]
Because Set-Content can get objects from pipeline.
Compare:
```
"a","b","c" | Set-Content -Path C:\tmp\z.txt

"a","b","c" | Set-Content -Path C:\tmp\z.txt "a","b","c" | Set-Content -Path C:\tmp\z.txt
```

**Comment by MartinKiryakov** [comment]
I see, that does make sense. Fair enough.
