### ISSUE TITLE
pwsh 7.2 CentOS 7 slow startup (30-60 seconds) if mounted SMB share is down

### ISSUE THREAD

**Issue by anton-knelts** [PowerShell/PowerShell#16512]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

mount any smb share to system
(i.e. mount //192.168.1.1/smb-share /mnt/custom-smb-share etc)
if remote resource (//192.168.1.1/smb-share) will become unavailable, simple run ./pwsh will be around 30-60 seconds to start until you umount "failed" smb share

### Expected behavior

```console
usual start ~1-5 seconds or maybe error message during startup that mount point is unavailable
```

### Actual behavior

```console
start around 40-60 seconds

Measure-Command { pwsh -noprofile -c exit }  

Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 0
Milliseconds      : 262
Ticks             : 602624509
TotalDays         : 0.000697482070601852
TotalHours        : 0.0167395696944444
TotalMinutes      : 1.00437418166667
TotalSeconds      : 60.2624509
TotalMilliseconds : 60262.4509
```

### Error details

```console
no errors returned
```

### Environment data

```powershell
PS /etc> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I think it is dup of #15061

**Comment by anton-knelts** [comment]
Well I don't have any startup issues with a few samba shares.
Issue happens only when samba share goes down. (also in case #15061 NFS shares not smb)

**Comment by iSazonov** [comment]
#15061 is that pwsh enumerates all volumes and this can take a lot of time, specially if an volume is unreachable.
