### ISSUE TITLE
Environment vars not refreshing even after `refreshenv`

### ISSUE THREAD

**Issue by AaronLayton** [PowerShell/PowerShell#16521]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have Windows Terminal 1.11.2921.0 installed and Powershell 7.2.0 installed.
I have just done a fresh install of NodeJS 16.13.0 and then close all terminal windows.

Open up Powershell 7 (which is set as the default for Win Terminal and try
`node -v` 

it says node is not installed even after I try and force a `refreshenv`

### Expected behavior

```console
Expected output


C:\Users\aaron>node -v
v16.13.0
```

### Actual behavior

```console
node -v
node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://user-images.githubusercontent.com/694964/143571362-c5edef5b-569a-4b0c-b277-5c1395e0b015.mp4

### Edit

see https://github.com/PowerShell/PowerShell/issues/16521#issuecomment-980323610 as I expect this may be a Windows Terminal issue

**Asking here if there is a built in way to refresh the environment variables for the current session**

**Comment by jborean93** [comment]
If refreshenv is a batch file it’s going to spawn a new cmd process and refresh the env vars in that process. This works for cmd as it runs it in process and thus updates the env vars for cmd. This is not the same for powershell or pwsh as it’s run in a separate process. You would need a powershell script that replicates refreshenv but in powershell itself.

**Comment by AaronLayton** [comment]
Thanks for the fast response @jborean93 

Looking into it `refreshenv` is a script that is installed with [Choco](https://chocolatey.org/). Your explanation sounds fine for teh `refreshenv` script, but if I quit Terminal / Powershell, shouldn't it then be loading up the new Env anyway?

**Comment by iSazonov** [comment]
You could open GUI for editing of environment variables and check if they was updated.

**Comment by AaronLayton** [comment]
@iSazonov yup I can open the Windows GUI and check they have definitely updated.

I have been playing around with this and I am loading up Powershell through Windows Terminal and I don't think that program is closing fully. If I manually end the Windows Terminal tasks and then re-open then I get the updated env variables.

I am going to link the Windows Terminal Issue I created and update this description here to ask "Is there a way to refresh the env variables in the current session" and if not can we add one?

https://github.com/microsoft/terminal/issues/11829

**Comment by jborean93** [comment]
> "Is there a way to refresh the env variables in the current session" and if not can we add one?

Yes you can enumerate the registry keys that store the env vars and use `Set-Item "env:\$name" $value` to set those updated env vars in the powershell process. Considering `refreshenv` isn't a builtin Windows thing I would doubt it would be something implemented by PowerShell itself but it can definitely be made by anyone and distributed through the PowerShell gallery.
