### ISSUE TITLE
Administrators do not have permissions to edit powershell.config.json when PowerShell is installed from MS Store

### ISSUE THREAD

**Issue by exchange12rocks** [PowerShell/PowerShell#16523]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install PowerShell from Microsoft Store.
2. Run it as administrator.
3. Execute the following command: `Set-ExecutionPolicy Restricted -Scope LocalMachine`

### Expected behavior

```console
The execution policy for the LocalMachine scope is set to "Restricted".
```

### Actual behavior

```console
Set-ExecutionPolicy: Access to the path 'C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.0.0_x64__8wekyb3d8bbwe\powershell.config.json' is denied.
To change the execution policy for the default (LocalMachine) scope, start PowerShell with the "Run as administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".
```
```


### Error details

```console
Exception             :
    Type       : System.UnauthorizedAccessException
    TargetSite :
        Name          : CreateFile
        DeclaringType : Microsoft.Win32.SafeHandles.SafeFileHandle
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Access to the path 'C:\Program
Files\WindowsApps\Microsoft.PowerShell_7.2.0.0_x64__8wekyb3d8bbwe\powershell.config.json' is denied.
    Source     : System.Private.CoreLib
    HResult    : -2147024891
    StackTrace :
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access,
FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare
share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share,
FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access,
FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode,
FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Management.Automation.Configuration.PowerShellConfig.OpenFileStreamWithRetry(String fullPath, FileMode
mode, FileAccess access, FileShare share)
   at System.Management.Automation.Configuration.PowerShellConfig.UpdateValueInFile[T](ConfigScope scope, String key,
T value, Boolean addValue)
   at System.Management.Automation.Internal.SecuritySupport.SetExecutionPolicy(ExecutionPolicyScope scope,
ExecutionPolicy policy, String shellId)
   at Microsoft.PowerShell.Commands.SetExecutionPolicyCommand.ProcessRecord()
CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException
FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
ErrorDetails          : Access to the path 'C:\Program
Files\WindowsApps\Microsoft.PowerShell_7.2.0.0_x64__8wekyb3d8bbwe\powershell.config.json' is denied.
                        To change the execution policy for the default (LocalMachine) scope, start PowerShell with the
"Run as administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope
CurrentUser".
InvocationInfo        :
    MyCommand        : Set-ExecutionPolicy
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Set-ExecutionPolicy Restricted -Scope LocalMachine
    PositionMessage  : At line:1 char:1
                       + Set-ExecutionPolicy Restricted -Scope LocalMachine
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Set-ExecutionPolicy
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by iSazonov** [comment]
Perhaps `C:\ProgramData` is more right place for the config but I don’t know if it’s possible for Store applications.

/cc @SteveL-MSFT

**Comment by rkeithhill** [comment]
@exchange12rocks Even though you may be an administrator, the error message would indicate you are not executing that command "as administrator".  If your machine has UAC enabled then even administrators run normally with a standard user token until they elevate a process.  Run PowerShell elevated (Run as Administrator) and then try that command - it should work.

![image](https://user-images.githubusercontent.com/5177512/143618860-79d1d6ee-e842-4587-8405-2e7bc9820d58.png)

**Comment by jborean93** [comment]
@rkeithhill it’s more likely to be an issue with the permissions of that directory. It’s typically restricted to even administrators and is the reason why you run store app executables from an app exec link in your user profile. When Windows invokes an app exec link it modifies your access token with a special SID that allows you to access that directory and start the real executable. There’s a good chance that while it has read and execute permissions on that dir it doesnt have write needed for this operation.

**Comment by rkeithhill** [comment]
Ah, I see in the exception details it does mention the path `C:\Program
Files\WindowsApps\Microsoft.PowerShell_7.2.0.0_x64__8wekyb3d8bbwe\powershell.config.json`.  So, it appears to be a Windows Store install.  It would be super helpful if the `$PSVersionTable` output mentioned the type of installation.

**Comment by B4Art** [comment]
I think, independetly from where Powershell 7.2 is installed from MS Store or not.
In elevated mode it should write AND read:
C:\Program Files\PowerShell\7\powershell.config.json

**Comment by Bridges369** [comment]
I have a same problem... I don't change with, and without, administrator
![image](https://user-images.githubusercontent.com/75232236/148819453-b7f0040c-8c36-4fae-a666-3a2eb76d5a07.png)
And no tutorial helps
![image](https://user-images.githubusercontent.com/75232236/148819840-1ca91aeb-c5f5-43e4-874d-d0a2e6e94c47.png)

**Comment by YuanfengZhang** [comment]
> 我有同样的问题......我不会改变管理员和没有管理员 并且没有教程有帮助 ![图片](https://user-images.githubusercontent.com/75232236/148819453-b7f0040c-8c36-4fae-a666-3a2eb76d5a07.png) ![图片](https://user-images.githubusercontent.com/75232236/148819840-1ca91aeb-c5f5-43e4-874d-d0a2e6e94c47.png)

The same.
![image](https://user-images.githubusercontent.com/71358306/160073066-0c76da33-5b75-4175-865e-b2d0bd682cd0.png)

**Comment by YuanfengZhang** [comment]
UPDATE: Reinstallation works for me.

**Comment by dqgthb** [comment]
I'm also interested in this issue.

**Comment by rgdelank** [comment]
I Installed PowerShell 7.3.0 from store with winget install powershell.
After this i have exact the same problem also with Administrator rights elevation and runas administrator
No way is not possible to change the policy

**Comment by EddieMaseman** [comment]
I have the same issue

**Comment by SteveL-MSFT** [comment]
This is dupe of https://github.com/PowerShell/PowerShell/issues/9278

**Comment by YakuBrangJa** [comment]
I reinstall the terminal with msi pakage and it works for me.
 https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3 and

**Comment by Leroy231** [comment]
I found a solution that doesn't require reinstalling: Run Windows PowerShell as admin (NOT PowerShell from MSFT Store), run `Set-ExecutionPolicy RemoteSigned`, then restart Terminal and then in PowerShell (NOT Windows PowerShell) I'm able to run .ps1 scripts.

**Comment by Uddhav07** [comment]
> I found a solution that doesn't require reinstalling: Run Windows PowerShell as admin (NOT PowerShell from MSFT Store), run `Set-ExecutionPolicy RemoteSigned`, then restart Terminal and then in PowerShell (NOT Windows PowerShell) I'm able to run .ps1 scripts.

why not ms store powershell huh

**Comment by Leroy231** [comment]
> why not ms store powershell huh

Using MS Store PowerShell didn't resolve this issue for me. Not sure why.

**Comment by aswordok** [comment]
https://github.com/powershell/powershell/releases
After searching for and deleting a few PowerShells from the Add/Remove program, download and reinstall the latest version from here. Then everything is OK.

<blockquote><img src="https://repository-images.githubusercontent.com/49609581/aad0ad80-cdec-11ea-8248-a37bc0571bfd" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/PowerShell/PowerShell/releases">Releases · PowerShell/PowerShell</a></strong></div><div>PowerShell for every system! Contribute to PowerShell/PowerShell development by creating an account on GitHub.</div></blockquote>
