### ISSUE TITLE
Select-Object: properties excluded with -ExcludeProperty are ignored when referenced by name string in calculated properties

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16524]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This probably won't arise too often in the real world, but is still a confusing bug worth fixing.

Scenario: You have a custom object for which you want to _rename_ a property while keeping all the others:

```powershell
[pscustomobject] @{ one = 1; two = 2; three = 3 } | 
  Select-Object -ExcludeProperty one -Property @{ n='uno'; e='one' }, *
```

That is, property `one` should be renamed to `uno`, keeping its value.

Note that the problem only occurs when the `e` (`Expression`) entry refers to the `one` object _by name string_ (`e='one'`).

By contrast, using a _script block_ works fine (`e={ $_.one }`)

### Expected behavior

```console
uno two three
--- --- -----
  1   2     3
```

### Actual behavior

```console
two three
--- -----
  2     3
```

That is, the calculated property was _quietly ignored_, due to the `-ExcludeProperty one` argument unexpectedly also preventing access to the excluded property's _value_ by _name_.

### Environment data

```powershell
PowerShell Core 7.2.0
```

**Comment by scriptingstudio** [comment]
`e` for `expression`
```powershell
[pscustomobject] @{ one = 1; two = 2; three = 3 } | 
Select-Object -ExcludeProperty one -Property @{ n='uno'; e='one' }, *

two three
--- -----
  2     3

[pscustomobject] @{ one = 1; two = 2; three = 3 } | 
Select-Object -ExcludeProperty one -Property @{ n='uno'; e={$_.one} }, *

uno two three
--- --- -----
  1   2     3
```

**Comment by mklement0** [comment]
@scriptingstudio, all of this information is in the OP, as far as I can tell.

**Comment by jhoneill** [comment]
@scriptingstudio  e / expression can be either a string holding a property name or a script block. 
What Mike's saying is -excludeproperty doesn't just remove it from the ones included by *,

```
[pscustomobject] @{ one = 1; two = 2; three = 3 } | 
Select-Object -ExcludeProperty o* -Property @{ n='uno'; e='one' }, @{ n='dos'; e='two' }, *e
.```
*e includes one and three; -excludeproperty take one out; so tree is in, two is included by name rather than script block. One needs to be written as {$_.one}
