### ISSUE TITLE
Changing colors via $Host.PrivateData only works for ErrorForegroundColor

### ISSUE THREAD

**Issue by ImportTaste** [PowerShell/PowerShell#16528]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$Host.PrivateData.DebugBackgroundColor = 'DarkBlue'
$Host.PrivateData.DebugForegroundColor = 'Cyan'
Write-Debug 'foo' -Debug
$Host.PrivateData.WarningBackgroundColor = 'DarkBlue'
$Host.PrivateData.WarningForegroundColor = 'Cyan'
Write-Warning 'foo'
$Host.PrivateData.ErrorBackgroundColor = 'DarkBlue'
$Host.PrivateData.ErrorForegroundColor = 'Cyan'
Write-Error 'foo'
$Host.PrivateData.ProgressBackgroundColor = 'DarkBlue'
$Host.PrivateData.ProgressForegroundColor = 'Cyan'
1..100 | ForEach-Object { Write-Progress -Activity 'foo' -PercentComplete $_ -Id 100 -Status 'bar'; Start-Sleep -Milliseconds 10 }
```
<ins>_Addendum:</ins> This code all behaves as expected in PowerShell 5.1_

### Expected behavior

_Equivalent output to_ `Write-Host 'foo' -BackgroundColor 'DarkBlue' -ForegroundColor 'Cyan'`

### Actual behavior

![image](https://user-images.githubusercontent.com/53661808/143944015-13b08be2-11e5-41f2-9e5e-393dfc1ae9d9.png)

### Environment data

```powershell
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
`$Host.PrivateData.Progress*` are working if `$PSStyle.Progress.View = 'classic'`

**Comment by ImportTaste** [comment]
Apparently $PSStyle is the way to do it now, disregard this issue.

> `$Host.PrivateData.Progress*` are working if `$PSStyle.Progress.View = 'classic'`

Thanks for the info.
