### ISSUE TITLE
PWSH 7.2 potential issue with default process ExecutionPolicy

### ISSUE THREAD

**Issue by johnthepro** [PowerShell/PowerShell#16533]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've installed PowerShell 7.2 via the MSSTORE.

I've noticed that when spawning a pwsh terminal, if I run ```Get-ExecutionPolicy -List``` the Process policy is 'Bypass' by default.

Is this expected behavior? I'd imagine not, as it seems to present an opportunity to circumvent the system's ExecutionPolicy.

### Expected behavior

```console
Described above.
```

### Actual behavior

```console
Described above.
```

### Error details

```console
No error returned.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22504
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/45504030/144103430-88fe7dbc-e0ca-4abb-a7e2-a7d7f8b34349.png)

**Comment by jhoneill** [comment]
There is no default process Execution policy. It's set when you run `pwsh -executionPolicy <something>` or if you have set the  PSExecutionPolicyPreference environment variable. 
Silly question, in Windows Terminal, if you go to settings and select PowerShell under profiles, does the command-line there set the execution policy?   
If you run pwsh outside of terminal (e.g. run cmd, and do a SET to check for PSExecutionPolicyPreference) what do you get ?

**Comment by johnthepro** [comment]
No, no such modification inside the Command Line section of the PowerShell 7 profile in Windows Terminal.

![image](https://user-images.githubusercontent.com/45504030/144120619-ef6da6fb-d7d9-42cc-8878-1d26c49b7171.png)

If I run pwsh from cmd first, the policy for the process is still Bypass.
Sorry, not sure what you meant by 'do a SET to check for PSExecutionPolicyPreference'

**Comment by johnthepro** [comment]
I did also just notice that I have 'PowerShell' and 'PowerShell 7' - I have both the "winget" sourced version installed, as well as the version from the MSSTORE.

Neither one has command line options that set the ExecutionPolicy.
Both of them have a Process ExecutionPolicy of Bypass, simply after spawning their respective shell prompts.

**Comment by johnthepro** [comment]
> If I run pwsh from cmd first, the policy for the process is still Bypass. Sorry, not sure what you meant by 'do a SET to check for PSExecutionPolicyPreference'

I figured out what you meant. Sorry, long day. That variable isn't present when running SET via cmd.

![image](https://user-images.githubusercontent.com/45504030/144184202-311d3643-defb-4828-b471-8223999b3167.png)

**Comment by jhoneill** [comment]
OK, well that's not expected behaviour, and we've crossed the two most obvious causes off the list.  Time for someone with more expertise about how the install process works  to take over ...

**Comment by johnthepro** [comment]
Happy to provide any information necessary!

**Comment by PaulHigin** [comment]
@WG-Security

More information is needed.  @johnthepro please provide more information about how PowerShell is launched.  The default ExecutionPolicy should be 'RemoteSigned', and we have verified that it is that on a new system.  It may be that you have a profile that is setting ExecutionPolicy for the shell instance.

Please try running pwsh.exe with the '-NoProfile' switch.

**Comment by johnthepro** [comment]
Thanks for the reply! I started a user level 'cmd' process, and called `pwsh.exe -noprofile` from it. I then ran `Get-ExecutionPolicy -list` and the results are the same. Process level is bypass.

![image](https://user-images.githubusercontent.com/45504030/145899544-796eec4b-e5d8-48f1-a92a-dea7fc35fa78.png)

Where might I go to figure out what might be doing it?

**Comment by johnthepro** [comment]
Thought you'd like to know that this 'issue' persists into PowerShell 7.2.1 and the latest version of Windows Terminal (1.11.3471)

**Comment by PaulHigin** [comment]
@johnthepro the Process scope ExecutionPolicy is stored and retrieved in the `PSExecutionPolicyPreference` process target environment variable.  A new process will pick up this environment variable setting from its parent.

I am able to repro this, but only by setting a machine wide environment variable:
`PSExecutionPolicyPreference = Bypass`
and then starting a cmd.exe shell and running `pwsh.exe -noprofile`.
The `PSExecutionPolicyPreference` environment variable appears in the pwsh session in `Process` target and so execution policy is set to `bypass` in that session.

I suspect that if you looked for `PSExectuionPolicyPreference` variable in your cmd.exe process you will see it set to `bypass`:

```powershell
C:\>echo %PSExecutionPolicyPreference%
Bypass
```

**Comment by johnthepro** [comment]
I'm beginning to wonder if SentinelOne has anything to do with this. I have a laptop that doesn't have it on it that I can check.

@PaulHigin what's the expected default for PSExecutionPolicyPreference ? A quick read seems to indicate that this variable is session specific, which then begs the question, from where would it decide that Bypass would be the default?

**Comment by johnthepro** [comment]
I'll have to break out the laptop this evening then and check that config versus this one here. Thanks for providing some additional insight!

It's nice to not be the only one with a problem!

![image](https://user-images.githubusercontent.com/45504030/159752598-269a9c31-378c-4c54-ba72-89cdbc9b3cc4.png)

**Comment by ZamElek** [comment]
Have the same issue

**Comment by ZamElek** [comment]
We tested and found out that the problem occurs after installing Sentinel One and rebooting the device. There is no such problem in a clean Windows OS. We have opened a ticket for Sentinel One.
