### ISSUE TITLE
ipmo -useWinPS doesn't work on unelevated pwsh 7.2

### ISSUE THREAD

**Issue by LuanVSO** [PowerShell/PowerShell#16534]
hey i'm on windows 10.0.19044.1348 and ps 7.2
but when i try to import any module with `-usewindowspowershell` i get an error, here's the shell history:
[PowerShell use windowsps.txt](https://github.com/PowerShell/PowerShell/files/7585211/PowerShell.use.windowsps.txt)

ps: if i run powershell elevated it works

_Originally posted by @LuanVSO in https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-976039800_

I've discovered this is because it tries to create files in the system temp folder which is locked for non-elevated users.
video:

https://user-images.githubusercontent.com/43626415/144127238-cd6bd3fa-fee6-4b2b-a4a3-89e584173e4d.mp4

**Comment by jborean93** [comment]
This seems to work for me on 7.2 at least. Is your user profile loaded for your unelevated process? If it isn't then `$env:TEMP` will be using `C:\Windows\TEMP` which as you've said the user won't have write access to. Best check in your unelevated process what the value of `$env:TEMP`, `$env:TMP`, and `$env:USERPROFILE` are.

**Comment by LuanVSO** [comment]
my %temp% is the user one, but %tmp% is the system one, i wonder if that's the right behavior
![image](https://user-images.githubusercontent.com/43626415/144150411-2f0bd8f8-6025-4845-9b54-8b966b4214db.png)

**Comment by jborean93** [comment]
Yea that doesn't sounds right to me, I'm unsure why it is actually set to that. You can see how it affects what temp dir is used

![image](https://user-images.githubusercontent.com/8462645/144151461-6e840a9a-48b5-426b-a359-d494d4d4297b.png)

Most likely PowerShell is using the .NET function which it uses the Win32 function [GetTempPath](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw). The docs there show how `TMP` is used as the first lookup value for what this should return. The temp path is used to store the proxy module scripts that define how pwsh talks to WinPS for the Appx module calls.

In the end you should look into what might be setting `TMP` to `C:\Windows\TEMP`, be it an explicit user env var, parent process, something else to fix this problem.

**Comment by LuanVSO** [comment]
ok fixed it here (i accidentally deleted it 2 days ago) thanks for pointing me in the right direction dude

**Comment by jborean93** [comment]
You're welcome, glad you were able to figure out the cause and fixed it.
