### ISSUE TITLE
Setting a value on a property in an iteration of a loop sets the same value on said property in all prior iterations of that loop

### ISSUE THREAD

**Issue by DragonHiei** [PowerShell/PowerShell#16531]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Copying an object within a loop multiple times, then updating each object with a different value for the same property. This issue occurs on all versions including 5.1. Please see code in the expected behavior section below.

### Expected behavior

```console
PS> $old = [System.Collections.Generic.List[Object]]::New()
$element = [PSCustomObject]@{
    Name         = 'Test'
    Type         = 'Normal'
    SomeProperty = 'Object1', 'Object2', 'Object3'
}
$old.Add($element)
$new = [System.Collections.Generic.List[Object]]::New()
$Property = 'SomeProperty'
foreach ($object in $old) {
    $SubArray = $object.$Property

    $element = $object
    foreach ($item in $SubArray) {
        $new.Add($element)
    }

    [int]$count = 0
    foreach ($item in $new) {
        $item.$Property = $SubArray[$count]
        $count = $count + 1
    }
}
$new

Name Type   SomeProperty
---- ----   ------------
Test Normal Object1
Test Normal Object2
Test Normal Object3
```

### Actual behavior

```console
Name Type   SomeProperty
---- ----   ------------
Test Normal Object3
Test Normal Object3
Test Normal Object3
```

### Error details

```console
None
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by DragonHiei** [comment]
@lovettbp enjoy

**Comment by vexx32** [comment]
This isn't a bug, this is by-design behaviour inherited from .NET.

PSCustomObject / PSObject is a reference-type object, so any time you add a given instance to an array or pass it around, you pass a reference to that same object in memory. Modifying any of the references will cause all the references to the object to reflect the changes when accessed.

If you want to create copies of the object, you need to do so explicitly with something like `$newObject = $oldObject.PSObject.Copy()` -- some object types also implement the IClonable interface and will expose a `.Clone()` method for this purpose.

Most objects you'll work with in PowerShell are [reference types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types).

[Value types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types) also exist in .NET but tend to be less used in .NET languages like PowerShell. Basic values like numbers, DateTime, Guid, and some other types are value types and have copy-on-assign behaviour that your code here expects.

Currently PowerShell doesn't have a native way to declare struct types, so any custom objects constructed in PowerShell itself will typically be reference types.

**Comment by DragonHiei** [comment]
Good to know, thanks for the info. I am all set.
