### ISSUE TITLE
PSReadLine ShowCommandHelp function does not work

### ISSUE THREAD

**Issue by johnnygerard** [PowerShell/PowerShell#16547]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Type a command then press F1 key.

### Expected behavior

```console
Help should display.
```

### Actual behavior

```console
Nothing visible happens.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by johnnygerard** [comment]
The issue is fixed.

Cause of the issue: I was using PSReadLine version 2.1.0.
The ShowCommandHelp function is a beta feature.

Solution: `Install-Module -Name PSReadLine -AllowPrerelease`.

Recommendation: flag beta features in the documentation.

**Comment by iSazonov** [comment]
> Recommendation: flag beta features in the documentation.

/cc @daxian-dbw for information.
