### ISSUE TITLE
Inconsistent Parameter Type Conversion in Function

### ISSUE THREAD

**Issue by PowershellNinja** [PowerShell/PowerShell#16540]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Load the following function:

```Powershell
function ConvertTo-Fahrenheit {
    param
    (
        [parameter(mandatory = $true)]
        $cels
    )

    Write-Host "Data Type: $($cels.GetType().Name)"

    $fahr = ($cels * 9) / 5 + 32
    return $fahr
}
```
Run the function without defining a parameter, then input "30" (or any numerical value) for the parameter "cels" when asked to provide the value for the mandatory parameter:
```Powershell
PS C:\Scripts> ConvertTo-Fahrenheit

cmdlet ConvertTo-Fahrenheit at command pipeline position 1
Supply values for the following parameters:
cels: 30
Data Type: String
60606060606060638
```
The result is... strange and does not have any obvious mathematical logic.

Second, run the function again and directly provide the same numerical value:
```Powershell
PS C:\Scripts> ConvertTo-Fahrenheit -cels 30
Data Type: Int32
86
```
This time, result is what I would have expected.

### Expected behavior

```console
I call the function and the type assumption / conversion should work the same regardless of if I provide the parameter directly to the function, or if I provide it over the "mandatory parameter" prompt.
```

### Actual behavior

```console
When I call the function and provide the numeric value directly, it is correctly assumed and typed as integer.
If I call the function without parameter and then provide the same numeric value to the "mandatory parameters" prompt, it is interpreted as a string.

If the parameter is strongly typed as integer, both versions work the same.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
```powershell
PS>  "30"*9

303030303030303030

PS>"30"*9/5+32

60606060606060638
```

**Comment by vexx32** [comment]
If you want to enforce a data type, it's generally best to annotate the parameter definition appropriately. Otherwise, as you saw, the default type for values entered at a prompt is a string.

**Comment by jhoneill** [comment]
> If you want to enforce a data type, it's generally best to annotate the parameter definition appropriately. Otherwise, as you saw, the default type for values entered at a prompt is a string.

It's expected because effectively it's read host  and that will get a string.  This one comes a surprise though 
```
ConvertTo-Fahrenheit 60
Data Type: Int32
140

ConvertTo-Fahrenheit 60.5
Data Type: Double
140.9

 ConvertTo-Fahrenheit -40
Data Type: String
Cannot convert value "-40-40-40-40-40-40-40-40-40" to type "System.Int32". Error: "Input string was not in a correct format."

```
But 
```
-40 * 9

-360
```
and if I modify the function to take piped input
```
-40 | ConvertTo-Fahrenheit
Data Type: Int32
-40
```

**Comment by vexx32** [comment]
Yeah, parsing rules are in effect when typing command arguments or expressions, but not at a Read-Host prompt.

**Comment by jhoneill** [comment]
> Yeah, parsing rules are in effect when typing command arguments or expressions, but not at a Read-Host prompt.

Except with negative numbers,  -1 in arguments will treated as a string,  but expressions will treat -1 as a number (as above);

**Comment by vexx32** [comment]
Yeah, the parsing rules differ a little bit in command arguments vs expressions, but the point was more just that PS doesn't really parse anything at all that's given to it as a prompt response.

**Comment by iSazonov** [comment]
Dynamic typing is power fundamental PowerShell feature and we have to pay for this.

**Comment by jhoneill** [comment]
> Dynamic typing is power fundamental PowerShell feature and we have to pay for this-

It's not really Dynamic typing which is causing the problem, in fact the OP could solve his problem using dynamic typing
 `$fahr = ($cels * 9) / 5 + 32`    
will produce 9 copies of a string    
` $fahr = (9* $cels) / 5 + 32`   
 Will convert the string to a number and multiply by 9. Any "ninja" should know that and probably wouldn't write ```$value = ...; return $value. ``` but not now, as the saying goes I'm adding insult to ninjary 

The answer to his question is 
** If you want a parameter to be mandatory, and user input to work, you have to allow for the prompt to be a read-host and the result will be a string**

I raised a side pointL if you do something like 
`-1 | convert`    
or 
`[math]::pi  | convert` 

What comes before the | sign is an *expression* and is evaluated so -1 or 3.1415 goes down the pipeline bt
`convert   `[math]::pi  `   sees a string literal - unless the expression is put in brackets.  It comes as a surprise to most people that -1 is not treated as a numeric literal but an expression.

**Comment by PowershellNinja** [comment]
Thanks for your answers @iSazonov @jhoneill , I wasn't aware that the prompt for a mandatory parameter is using Read-Host, that explains the behavior though - thanks for your time
