### ISSUE TITLE
App Crash. Unhandled NullReference Exception while copying to remote session

### ISSUE THREAD

**Issue by SergeyZalyadeev** [PowerShell/PowerShell#16542]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$cred=[PSCredential]::New('user',(ConvertTo-SecureString 'password' -AsPlainText -Force))
$session = New-PSSession <remoteComputerName> -Credential $cred
Copy-Item PathToLocalFile_10MB RemotePath -ToSession  $session

### Expected behavior

```console
No crash
```

### Actual behavior

```console
Pwsh terminated due to unhandled NullReferenceException 
 System.Management.Automation.Remoting.PrioritySendDataCollection.ReadOrRegisterCallback(OnDataAvailableCallback callback, DataPriorityType& priorityType)
at System.Management.Automation.Remoting.Client.WSManClientCommandTransportManager.SendOneItem()
at System.Management.Automation.Remoting.Client.WSManClientCommandTransportManager.OnRemoteCmdSendCompleted(IntPtr operationContext, Int32 flags, IntPtr error, IntPtr shellOperationHandle, IntPtr commandOperationHandle, IntPtr operationHandle, IntPtr data)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/475988/144474904-1cb4935a-807d-4673-9146-b3b5011aeff7.png)

Race condition in threads 

Dereference the member variable _dataToBeSent[1] when it has been cleared by the different thread that called Clear() method.
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/fanin/PriorityCollection.cs#L217-L226

![image](https://user-images.githubusercontent.com/475988/144484691-01a27f50-a5ce-4c52-a8b1-490488526eb4.png)

The stack of thread that cleared _dataToBeSent[1] member. 

![image](https://user-images.githubusercontent.com/475988/144485251-ebe05a75-e703-4b51-8c43-7bead92550d7.png)

Simple Fix: 
Insert lock and null check before dereferencing at line 226
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/fanin/PriorityCollection.cs#L226

                lock (_dataSyncObjects[promptResponseIndex])
                {
                    if (_dataToBeSent[promptResponseIndex] != null)

**Comment by iSazonov** [comment]
@SergeyZalyadeev Thanks for your investigations! Do you want to create PR?

**Comment by SergeyZalyadeev** [comment]
I'll try

**Comment by PaulHigin** [comment]
@WG-Remoting, Remoting working group agrees with the scenario and crash analysis.  Thanks!

**Comment by PaulHigin** [comment]
Adding simple null checks appears to have resolved this issue.
