### ISSUE TITLE
PowerShell replaces Windows File Explorer jump list handler

### ISSUE THREAD

**Issue by tasic99** [PowerShell/PowerShell#16550]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am having an issue with Windows File Explorer Jump List after installing PowerShell

![image](https://user-images.githubusercontent.com/52830724/144627735-75f055fc-84a1-456f-a7ac-c946a9de20af.png)

### Expected behavior

```console
Items in either Frequent or Recent lists should have called Explorer windows
```

### Actual behavior

```console
PS 7 RunAs windows is being opened
```

### Environment data

```powershell
> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
>  Items in either Frequent or Recent lists should have called Explorer windows

Not quite sure I follow.  Are you saying that when you mouse `left-click` on a File Explorer jump list item, a PowerShell console opens instead of a File Explorer window?  Or are you selecting a menu-item on the `right-click` context menu for a jump list item?

**Comment by tasic99** [comment]
Yes, when I left-click an item in either Pinned or Frequent list new PS RunAs window appears
this behavior is repited on several Srv 2016 boxes
when I do right-click - Open on such Item I get Explorer

**Comment by rkeithhill** [comment]
@tasic99 Is this Windows 10 (1607) or Windows Server 2016?

**Comment by JamesWTruher** [comment]
@tasic99 this certainly seem strange, but there's nothing that I can think of that we do in our installation that _should_ do this. Could you share _how_ you installed (options, etc)?

**Comment by tasic99** [comment]
it was our software developers who installed PS7 on our  app servers so I am not aware how it was happenning
now you gave me an idea to test various install options. so I uninstalled PS7 then downloaded msi package from github and reinstalled again. and now everything works fine.
so looks like I can not reproduce the issue after reinstalling from msi package.
thank you for help!
