### ISSUE TITLE
Copy-item -tosession returns an exception when source on Windows that isn’t on NTFS?

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#16565]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

copy-item -tosession $a -path 'd:\a.txt' -Destination 'D:\nush\' #problem  ,both source and target are drive letter "D"
copy-item -tosession $a -path 'e:\a.txt' -Destination 'D:\nush\' #normal

Cause of problem:
The drive letter of the source directory is the same as that of the target directory.
If the drive letter of the source directory difference target directory, normal.

### Expected behavior

```console
The copy succeeds without error messages and .Net exceptions
```

### Actual behavior

```console
The copy succeeds with error messages and .Net exceptions
```

### Error details

```console
get-error:
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 87
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : GetStreams
        DeclaringType : System.Management.Automation.Internal.AlternateDataStreamUtilities
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message         : 参数错误。
    Source          : System.Management.Automation
    HResult         : -2147467259
    StackTrace      :
   at System.Management.Automation.Internal.AlternateDataStreamUtilities.GetStreams(String path)
   at Microsoft.PowerShell.Commands.FileSystemProvider.PerformCopyFileToRemoteSession(FileInfo file, String destination
Path, PowerShell ps)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String destinationPath, Boolean
force, PowerShell ps)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItemLocalOrToSession(String path, String destinationPath, Bo
olean recurse, Boolean Force, PowerShell ps)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItem(String path, String destinationPath, Boolean recurse)
   at System.Management.Automation.SessionStateInternal.CopyItem(CmdletProvider providerInstance, String path, String c
opyPath, Boolean recurse, CmdletProviderContext context)
CategoryInfo          : NotSpecified: (:) [Copy-Item], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.CopyItemCommand
InvocationInfo        :
    MyCommand        : Copy-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 8
    Line             : copy-item -Path 'D:\h.txt' -Destination 'D:\j' -ToSession $a
    PositionMessage  : At line:1 char:1
                       + copy-item -Path 'D:\h.txt' -Destination 'D:\j' -ToSession $a
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : copy-item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
all version

local pc：copy files source
powershell 5.1.18362.1801 on win10
powershell 7.2.0 on win10



target pc1：copy files target
powershell 5.1.19043 on win10

target pc2：copy files target
powershell 5.1 on win11
```

### Visuals

The [copyto node script] of KASINI3000 is a copy-item -tosession package based on PowerShell.
I always hear people report that copying files failed. To this end, I added try and re copy, but someone still reported this.
After analyzing the log, I found the problem.Looks like a bug.

Although the file was copied successfully, KASINI3000 can't stand this exception. 
Because I wrote some code. If it is abnormal, script will copy it again and Exit 1.

## Problem phenomenon:
* copy files succeeded.
* Report "parameter error"（参数错误）
* Throw an exception.
* only for -tosession.It has nothing to do with -fromsession

**Comment by kasini3000** [comment]
![16565](https://user-images.githubusercontent.com/65390418/145017594-e29e7227-1ac7-4ce4-b5d8-14a3eb2a5b75.jpg)

**Comment by jborean93** [comment]
I cannot replicate this normally, I'm able to copy a file to the exact same path on the remote PSSession so I think your error is due to another problem.

Judging by the error message it seems like the failure is when calling `AlternateDataStreamUtilities.GetStreams(String path)`. The fact that the error is `ERROR_INVALID_PARAMETER` seems to indicate either your `D:` drive on either the local or remote does not support alternate data streams. For example either one of these two partitions could be formatted with FAT32 or some other formatting and not NTFS. This could explain why it works when you target a different drive on the local side it is fine.

**Comment by kasini3000** [comment]
![16565_2](https://user-images.githubusercontent.com/65390418/145151001-4d5b7b13-f9ce-4835-a56e-e44b0ca48c4b.png)
source=win10+ps7.2
target=new win11 vm
drive d on win11 vm =ntfs format

**Comment by iSazonov** [comment]
> 2147467259

It is "file being opened or locked"

**Comment by jborean93** [comment]
@iSazonov the key one in particular is `NativeErrorCode: 87` which refers to [ERROR_INVALID_PARAMETER 0x00000057](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d). The actual function in question here that is raising the `Win32Exception` is this https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L8568-L8628

Essentially either [FindFirstStream](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirststreamw) or [FindNextStream](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findnextstreamw) is the function that's failing and the only explicit mention about this is `FindFirstStream` where it states

> If the filesystem does not support streams, the function fails and GetLastError returns ERROR_INVALID_PARAMETER (87).

@kasini3000 you said that drive D on the Win 11 (what you said is the target) is NTFS but in reality the error is PowerShell trying to get the streams of drive `D:` on your source (Win 10). Can you verify that is also NTFS or some other file system format. Can you try running

```powershell
Get-Item -Path D:\h.txt -Stream *
```

**Comment by kasini3000** [comment]
@jborean93  oh,my drive "d" is fat32 partition, looks like you're close to the truth
In fact, I don't know whether the problem at the source or the target.

```
PS C:\ProgramData\kasini3000> Get-Item -Path D:\h.txt -Stream *
Get-Item: 参数错误。
```

**Comment by jborean93** [comment]
Thanks for confirming it’s definitely the source. Are you able to update the title of the ticket to reflect that Copy-Item -ToSession doesn’t work for a source on Windows that isn’t on NTFS?

**Comment by PaulHigin** [comment]
The ERROR_INVALID_PARAMETER error is misleading as documentation states this is the error returned when file system does not support alternate streams.  I'll update the code to ignore this error.

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirststreamw
