### ISSUE TITLE
pwsh 7.20 broke Get-Date -uformat results

### ISSUE THREAD

**Issue by JoeSalmeri** [PowerShell/PowerShell#16562]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Get-Help for ps 7.1.5 and ps 7.2.0 shows

 The valid UFormat specifiers are displayed in the following table:

| Format specifier |                                 Meaning                      |         Example          |
| ---------------------- | ------------------------------------------------------- | --------------------------  |
| `%u`                    | Day of the week - number                         | Sunday = 0               |

05/01/2022 is a Sunday therefore the -uFormat %u should return 0
ps 7.1.5 correctly  returns 0 for Sunday 
ps 7.2.0 incorrectly returns 7 for Sunday

I also tested other "Sunday" dates and got the same results.

The DayOfWeek property correctly returns Sunday and using [int} for the DayofWeek correctly returns 0 so the new issue being reported is caused by the -uFormat %u changes that occurred in 7.2.0 as shown by the following code:

    ps 7.1.5

        Get-Date 05/01/2022 -uformat %u           # returns 0              - Correct
        (Get-Date 05/01/2022).DayOfWeek         # returns Sunday    - Correct
        [int](Get-Date 05/01/2022).DayOfWeek   # returns 0              - Correct

    ps 7.2.0

        Get-Date 05/01/2022 -uformat %u            # returns 7              - Wrong
        (Get-Date 05/01/2022).DayOfWeek          # returns Sunday    - Correct
        [int](Get-Date 05/01/2022).DayOfWeek    # returns 0              - Correct

All code above was executed without my pwsh profile loaded (pwsh -noprofile)

This issue exists with ps 7.2.0 running on Linux and on Windows 10.

I also tested the issue on Linux using ps 7.1.3 and 7.1.4 and like 7.1.5 they do NOT have the issue.  

I found the following old issue for Get-Date -Uformat, however, it is from 09/04/2017 and the issue I'm reporting was broken by the changes in 7.2.0 as it worked correctly in ps 7.1.3, 7.1.4, and 7.1.5 (and earlier versions too as I have used this code for many years all the way back to ps 7.0)

    https://github.com/PowerShell/PowerShell/issues/4750

### Expected behavior

```console
Documented above for ps 7.1.5 and ps 7.2.0
```

### Actual behavior

```console
Documented above for ps 7.1.5 and ps 7.2.0
```

### Error details

```console
No errors occur, PS 7.2.0 just returns the the wrong value (7) for a Sunday date instead of the correct value 0 as per the documentation as per how it has worked in prior PS versions.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 5.15.5-1-default #1 SMP Thu Nov 25 09:36:40 UTC 2021 (83fc974)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by JoeSalmeri** [comment]
@iSazonov 

ps 7.1.5 Sunday, May 1, 2022 12:00:00 AM
ps 7.2.0 Sunday, May 1, 2022 12:00:00 AM

As show above in my bug report both 7.1.5 and 7.2.0 know that 05/01/2022 is a Sunday and
[int](Get-Date 05/01/2022).DayOfWeek both return 0 but -uformat %u returns 0 (correctly for 7.1.5) and returns 7 (incorrectly for 7.2.0)

Since they both return Sunday and both return 0 for [int] DayOfWeek it seems pretty clear that the -uformat %u code is what changed and is broken.

Did you try the examples I originally provided and get different results?

**Comment by iSazonov** [comment]
Doc for 7.2 https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7.2
> <html>
<body>


%u | Numeric day of the week (1-7) | Monday = 1, Sunday = 7
-- | -- | --



</body>
</html>

**Comment by iSazonov** [comment]
See also https://github.com/PowerShell/PowerShell/issues/4750#issuecomment-754365382

**Comment by JoeSalmeri** [comment]
Get-Help Get-Date -Full disagrees with what you posted

Did you see that in my bug report?  Here it is again.

Get-Help for ps 7.1.5 and ps 7.2.0 shows

 The valid UFormat specifiers are displayed in the following table:

| Format specifier |                                 Meaning                      |         Example          |
| ---------------------- | ------------------------------------------------------- | --------------------------  |
| `%u`                    | Day of the week - number                         | Sunday = 0               |

Sunday has returned 0 in every version of powershell all the way back to powershell 5.1

Here it is on Windows 10 powershell 5.1

PS C:\Users\Joe> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\Joe> Get-Date 05/01/2022 -uformat %u
0

Here it is converted to int on powershell 5.1

PS C:\Users\Joe> [int](Get-Date 05/01/2022).DayOfWeek
0



Why would a change like this be made which breaks all existing code over the last 5 to 10 years ?

I don't understand why this change was made.

In other UNRELATED bugs which I have reported I have been told that Yes what you found is a bug but we aren't fixing it because doing so would break people's code that depends on that behavior.

In this case pwsh 7.2.0 made a change from Sunday=0 to Sunday=7 breaking all existing code out there which depended on the documented behavior (which Get-Help Get-Date still has documented that way).   It's not even a bug in the older versions of powershell / pwsh.


Why would such a change be made when real bugs in other code won't be fixed because of code that depended on the broken behavior???   In this case the bug was created in 7.2.0.

This does not make sense to break existing code when there is no good reason to make the change to Sunday now equals 7.

Why would Get-Date 05/01/2022 -uformat %u return 7 but [int](Get-Date 05/01/2022).DayOfWeek return 0?

Obviously if MS really wants to change Sunday to 7 now instead of 0 somebody did an incomplete change because they forgot to update the documentation and [Int} DayOfWeek still says that Sunday = 0.

**Comment by JoeSalmeri** [comment]
> See also [#4750 (comment)](https://github.com/PowerShell/PowerShell/issues/4750#issuecomment-754365382)

Yes, I listed by OLD bug report in my initial bug report, however, what I reported is a change in PS 7.2.0 that was made which broke all existing code all the way back to powershell 5.1 that depended on the documented behavior.

I am confused as to why were are debating this issue?

Clearly 7.2.0 changed the documented behavior breaking existing code for now good reason and did not even do a complete job of making the change.

**Comment by JoeSalmeri** [comment]
@iSazonov @SteveL-MSFT 

Here's the (Get-Culture).DateTimeFormat from ps 7.2.0 (7.1.5 returns the same)

(Get-Culture).datetimeformat

AMDesignator                     : AM
Calendar                         : System.Globalization.GregorianCalendar
DateSeparator                    : /
FirstDayOfWeek                   : Sunday
CalendarWeekRule                 : FirstDay
FullDateTimePattern              : dddd, MMMM d, yyyy h:mm:ss tt
LongDatePattern                  : dddd, MMMM d, yyyy
LongTimePattern                  : h:mm:ss tt
MonthDayPattern                  : MMMM d
PMDesignator                     : PM
RFC1123Pattern                   : ddd, dd MMM yyyy HH':'mm':'ss 'GMT'
ShortDatePattern                 : M/d/yyyy
ShortTimePattern                 : h:mm tt
SortableDateTimePattern          : yyyy'-'MM'-'dd'T'HH':'mm':'ss
TimeSeparator                    : :
UniversalSortableDateTimePattern : yyyy'-'MM'-'dd HH':'mm':'ss'Z'
YearMonthPattern                 : MMMM yyyy
AbbreviatedDayNames              : {Sun, Mon, Tue, Wed…}
ShortestDayNames                 : {S, M, T, W…}
DayNames                         : {Sunday, Monday, Tuesday, Wednesday…}
AbbreviatedMonthNames            : {Jan, Feb, Mar, Apr…}
MonthNames                       : {January, February, March, April…}
IsReadOnly                       : True
NativeCalendarName               : Gregorian Calendar
AbbreviatedMonthGenitiveNames    : {Jan, Feb, Mar, Apr…}
MonthGenitiveNames               : {January, February, March, April…}

Note that the culture information says

FirstDayOfWeek                   : Sunday
CalendarWeekRule              : FirstDay

So culture also says that Sunday should be 0 like it has always been.

The ps 7.1 documentation also clearly states that Sunday = 0

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7.1

%u | Day of the week - number | Sunday = 0

As does the powershell 5.1 documentation

https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Get-Date?view=powershell-5.1

%u | Day of the week - number | Sunday = 0


So why was this code breaking change made which has been documented since at least powershell 5.1 to say that Sunday = 0?

This needs to be fixed.   We cannot have code breaking changes made for no good reason.

**Comment by iSazonov** [comment]
pwsh should have a consistency on all platforms.
%u is Unix format, it works right on Unix but not on Windows in previous versions. This was qualified as a bug. Now the behavior follow _ISO standard_ on all platforms.

**Comment by JoeSalmeri** [comment]
@iSazonov @SteveL-MSFT 

I agree TOTALLY that it should be consistent across platforms, however, this statement you made

    "%u is Unix format, it works right on Unix but not on Windows in previous versions."

is simply NOT true.

It *WAS* consistent on both Windows and Linux BEFORE the changes were made in PS 7.2.0

Prior to this change ALL prior versions of pwsh and powershell that I have used all the way back to powershell 5.1, so 5.1, 6.x, 7.x, 7.1.3, 7.1.4, 7.1.5 returned 0 for Sunday on BOTH Windows and Linux platforms ( where ps was available ).   

My existing code was regularly run on BOTH Windows and Linux platforms all the way back to Windows 7 and powershell 5.1 and on various Linux distros and Sunday always returned that it was 0.

Windows 7 came out in 2009 so to saying that it did NOT working right on Windows in previous versions was absolutely not a true statement as my code has been running for the last 12 YEARS.

When PS 6.x and 7.x came out I also started running the SAME ps code on Linux machines and in all cases the code worked flawlessly because Sunday consistently returned 0.

As I said above, [int]( Get-Date 05/01/2022).DayOfWeek still returns 0 so still treats Sunday as 0.

We need an answer which reflects the actual facts as to why this was changed because saying that it was inconsistent across platforms is not a fact as my code has worked fine for 12 years until this change was made.

**Comment by JoeSalmeri** [comment]
@iSazonov @SteveL-MSFT 

This change NOT only breaks existing code but it violates basic documented design principles of PS.

They [System.DayOfWeek] enum returns that Sunday = 0

If you run this code

    [System.Enum]::getvalues([type][System.DayOfWeek]) | ForEach-Object { echo "$_ $($_.value__)" }

It returns:

Sunday 0
Monday 1
Tuesday 2
Wednesday 3
Thursday 4
Friday 5
Saturday 6

The same results are returned on BOTH Windows and Linux even on PowerShell 5.1 on Windows!

This change is also inconsistent with basic fundamental powershell concepts that say that lists type items are zero based (just like in C and other languages).


Here is the PS 7.2.0 documentation for about_enum:

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_enum?view=powershell-7.2

Short description

The enum statement is used to declare an enumeration. An enumeration is a distinct type that consists of a set of named labels called the enumerator list.

Long description
The enum statement allows you to create a strongly typed set of labels. That enumeration can be used in the code without having to parse or check for spelling errors.

****Enumerations are internally represented as integers with a starting value of zero. The first label in the list is assigned the value zero.** The remaining labels are assigned with consecutive numbers.**

In the definition, labels can be given any integer value. Labels with no value assigned take the next integer value.


[System.DayOfWeek} is an enumerator therefore according to the PS documentation enumerators are ZERO based.

So you cannot use values of Monday=1 through Sunday=7 because they violate the PS documented design of enumerators.

You also cannot change the [System::DayOfWeek] enum to use values 1-7 because then you will break all the code out there that used that enum because they would then get different values than they have previously gotten on ALL prior versions of PS!

This code change also creates the following issue

       Get-Date 05/01/2022 -uFormat %u                 returning that Sunday = 7

       [int](Get-Date 05/01/2022).DayOfWeek           returning that Sunday = 0


I am struggling to see how such a simple bug report which documents a change that breaks existing code which worked on Windows and Linux all the way back to PowerShell 5.1 is not being seen a problem???

Whoever accepted this code change clearly did not consider the implications and code breakage and they did not make sure that the change was complete and not half done.

How are these issues going to be resolved because you clearly cannot have some code return that Sunday = 7 and other code return that Sunday = 0 and how are you going to resolve the PS documentation for enums say that they are ZERO based.

It seems pretty clear to me that the solution is to revert this change because ALL other options I have discussed (or additional changes listed above) will break existing code all the way back to PowerShell 5.1.   

I know I have repeated that multiple times because I want to stress the significance of of the issue.

How can you justify a code breaking change for something that was **not even a bug** and ignore more serious things **which are really BUGS** (like the fact that Copy-Item cannot produce consistent results) with the reason that fixing the Copy-Item bug would be code breaking???

It seems that the thought process is backwards:

We should NOT allow code breaking changes for something that is NOT REALLY a bug

and 

We should ALLOW code breaking changes to fix something that is REALLY a bug


I've been a developer for over 30 years and programmed in more languages that I can count.

I seriously doubt that most developers would think it makes sense to make code breaking changes for something that is NOT a bug and I also believe that those same developers would support code breaking changes that are to fix a bug.   

Isn't that why we fix bugs in the first place?

**Comment by iSazonov** [comment]
Again, %u is exclusively Unix format for years and it comes from ISO 8601. Unix `date` utility works so for years. See [example](https://github.com/PowerShell/PowerShell/issues/4750#issuecomment-754365382).
Main rule for pwsh is to be consistent across platforms. So Gate-Time -UFormat was fixed to follow ISO 8601 standard and Unix behavior.

In fact, pwsh already has hundreds of changes that are incompatible with Windows PowerShell, and each new version widens the gap. There is no other way but to test your scripts when upgrading to a new version.
