### ISSUE TITLE
Fresh Installation of 7.2 (arm version) on Apple Silicon reqiures Rosetta

### ISSUE THREAD

**Issue by darg2012** [PowerShell/PowerShell#16571]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Download and extract pwsh for MacOS (arm, currently powershell-7.2.0-osx-arm64.pkg) and try installation using the finder and right-click route.

### Expected behavior

```console
Rosetta-Less installation
```

### Actual behavior

```console
Installation requires Rosetta
```

### Error details

```console
To install "PowerShell - 7.2.0", you need to install Rosetta.
Do you want to install it now?

Rosetta enables Intel-based features to run on Apple silicon Macs. Reopening applications after installation is required to start using Rosetta.
```

### Environment data

```powershell
not applicable
```

**Comment by daxian-dbw** [comment]
@TravisEz13 Can you please take a look and comment?

**Comment by dahlia** [comment]
<img width="732" alt="To install “PowerShell - 7.2.1”, you need to install Rosetta.  Do you want to install it now?  Rosetta enables Intel-based features to run on Apple silicon Macs. Reopening applications after installation is required to start using Rosetta." src="https://user-images.githubusercontent.com/12431/149284791-c4f3a8e4-def6-46aa-a518-ef39cf4150a1.png">

The installer itself can run on M1 Pro without Rosetta, but it shows a pop-up window which requires the user to install Rosetter on their Mac.  It does not continue installing if I choose *Not Now*.
