### ISSUE TITLE
`ScriptBlock.InvokeWithContext` cannot set `PSCmdlet`

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#16575]
### Steps to reproduce

`InvokeWithContext` lets you set a lot of scope intrinsic variables like `$_`, `$this`, `$input` but it cannot set `$PSCmdlet`.

### Expected behavior

```powershell
{ $PSCmdlet }.InvokeWithContext($null, [psvariable]::new('PSCmdlet', 'testing'))
# testing
```

### Actual behavior

```powershell
{ $PSCmdlet }.InvokeWithContext($null, [psvariable]::new('PSCmdlet', 'testing'))
# no results
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

---

The use case for this is any `Use-*` type command with a body script block. Think something like this:

```powershell
Use-Location './project' {
    dotnet build
}
```

I was trying to avoid having to set some temporary variables for scope intrinsics but `PSCmdlet` in particular doesn't seem to work.

**Comment by 237dmitry** [comment]
I think this is because this automatic variable serves to process object parameters. `$args` and `$PSBoundParameters` don't work out either.

**Comment by SeeminglyScience** [comment]
`$args` is set by the third (omitted in the examples) parameter.`$PSBoundParameters` is another that would ideally also work but currently does not. Note that this API already has some code paths that explicitly enable the setting of some other scope intrinsic variables like `$this`, `$input`, `$_/$PSItem`.

It makes sense why it doesn't work, but it would be useful if that were changed.
