### ISSUE TITLE
Allow the changing of the prefix 'Write-Error' for Write-Error

### ISSUE THREAD

**Issue by mcx808** [PowerShell/PowerShell#16585]
### Summary of the new feature / enhancement

Add either a switch to disable the "Write-Error: " prefix when using Write-Error, or an option to customise it.

I'm using Write-Error in some automation pipelines that will validate some files and intend to be run in a pipeline by non-powershell users. Because Write-Error "Error Message" actually outputs `Write-Error: Error Message`, this could confuse people into thinking it's some kind of disk write error, since they have no idea of the underlying function being called to display this.

Especially since I'm writing the errors to a variable using -ErrorVariable that is returned at the end of the script after performing validation on multiple objects, having everything prepended with Write-Error makes even less sense.

### Proposed technical implementation details (optional)

My ideal solution would be a simple switch to suppress "Write-Error:" being prepended to the output, or certainly to suppress it being written to the error variable even if it must be written to the console.

**Comment by iSazonov** [comment]
If you collect errors you can do custom output:
```powershell
PS> Write-Error -Message "Error Message" -ErrorAction SilentlyContinue -ErrorVariable b

PS> $b

Write-Error: Error Message

PS> "My custom error output: $($b.Exception.Message)"
My custom error output: Error Message

**Comment by TobiasPSP** [comment]
Is this really an issue controlled by Write-Error? It may just be a "formatting feature" of exceptions. Try this: `Get-Process notthere`. The error message will also preprend the cmdlet name that threw the exception. IMHO this is a general behavior when a cmdlet throws an exception. Write-Verbose et al work differently because they do not output an exception.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this, we agreed that it makes sense for `Write-Error` to have a `-Source` parameter that the error formatting would have to leverage to present the error message instead of attributing it to the `Write-Error` cmdlet.

**Comment by mcx808** [comment]
> @PowerShell/wg-powershell-cmdlets reviewed this. `Write-Error` has a `-CategoryActivity` that renders correctly in PowerShell 7 already:
> 
> ```
> PS> Write-Error 1 -CategoryActivity test
> test: 1
> ```

Sorry I didn't get chance to reply before the housekeeping bot flew in, but yes this is a perfect solution, just not quite explained very well in the help for `Write-Error`.
