### ISSUE TITLE
arm32 and arm64 packages as part of normal build process

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#16595]
### Summary of the new feature / enhancement

Could you create RPM and Debian packages for the Linux arm32 and arm64 please? This would make it much more friendly to install on a Raspberry Pi.
I have been creating these manually, but it makes sense for this project to create them at the same time as the x86_64 packages.
These could then also be signed by your official key.

### Proposed technical implementation details (optional)

When a new build is created and you create the x86_64 rpm and deb, please also create and sign deb and rpm for arm32 and arm64.

**Comment by adityapatwardhan** [comment]
@rhubarb-geek-nz Could you open a new issue using the "Distribution Support Request" template. It would help us greatly in look at them. Thanks!

Template: https://github.com/PowerShell/PowerShell/issues/new/choose

**Comment by rhubarb-geek-nz** [comment]
Hi, I had a look at the distribution support request template and it looked like I would have to make four requests for each and every release. Want I wanted was for you to do is make four new packages every time you make a new release just like the existing amd64 rpm and deb packages as part of your normal process.

**Comment by rhubarb-geek-nz** [comment]
You currently build a tar.gz for both arm32 and arm64 Linux, those do not seem to be associated with any specific release of Linux. But you do manage to create both a Debian deb, and a RHEL rpm for the amd64 binaries. So I was hoping for something similar for arm32/arm64 to be packaged as deb and rpm for generic Linux systems using those packaging formats.

**Comment by rhubarb-geek-nz** [comment]
Raised https://github.com/PowerShell/PowerShell/issues/16617, thanks
