### ISSUE TITLE
GetDate -AsUTC does not treat inputs as UTC. 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#16594]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In #16593 I said there is a need for invariance with dates - meaning changing culture doesn't change the meaning of  [datetime]"12/10/2021".   With times  `[datetime]::new` allows code to create a date using **invariant time** (UTC) so that wherever this is run
``` 
 [datetime]::new(2022,06,30,12,0,0,[System.DateTimeKind]::Utc)
````
It returns `30 June 2022 12:00:00  Z`, which can be convert to a local time if needed. 

`Get-Date `  **Always** treats the values as **local** so      
`(Get-Date -Year 2022 -Month 6 -Day 30 -Hour 12 -Minute 0 -Second 0).ToUniversalTime()`   
on UK time Produces 
`30 June 2022 11:00:00`
and on pacific time produces
30 June 2022 19:00:00

The **-AsUTC** switch does not mean "These values describe a UTC time", but "These are local times but please the resulting  time in UTC"   so 
```
(Get-Date -Year 2022 -Month 6 -Day 30 -Hour 12 -Minute 0 -Second 0 -AsUTC )
```
is the same as the previous result. 

Changing the meaning of -AsUTC would be a breaking change so a new switch , perhaps "-Kind" taking a  `[System.DateTimeKind]` would be better 

### Expected behavior

```console
Get-Date -Year 2022 -Month 6 -Day 30 -Hour 12 -Minute 0 -Second 0 -AsUTC

Treats the times parameters as UTC times.
```

### Actual behavior

```console
Get-Date -Year 2022 -Month 6 -Day 30 -Hour 12 -Minute 0 -Second 0 -AsUTC

Treats the times parameters as local times and transforms the result into a UTC time. (i.e. This is 12 Noon local, and outputs 11AM UTC , not 12Noon UTC, a.k.a. 1PM local).
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I don't understand your request because it is works as designed and documented https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7.2#parameters
> -AsUTC
Converts the date value to the equivalent time in UTC.

**Comment by jhoneill** [comment]
@iSazonov 
Try this 
get-date -Day 10 -Month 12 -Year 2012 -hour 19 -Minute 11 -asutc

Change your time zone  and start a fresh PWSH   then run it again 

You'd expect the same time right ? 

Those inputs are always local time, and as -AsUTC says "Make me 19:11 Pacific time and convert the result to UTC) (Which will be the next day) 
There is no way to Get-Date to treat the values as UTC.  So the machine's timezone changes the result.

**Comment by iSazonov** [comment]
Let's take in the _same time_:
LocalTime1 - in time zone 1
LocalTime2 - in time zone 2

Obviously LocalTime1 != LocalTime2 but both one are converted in the same UTC time because of it is the same time.

**Comment by jborean93** [comment]
I've been burnt by this before thinking `-AsUtc` would create a `UTC` kind DateTime for the value I specified rather than the local time for the value specified then converted to UTC. Not sure if we can really change that now but even if it doesn't then updating the docs to be more specific for what `-AsUtc` does would be nice.

**Comment by iSazonov** [comment]
:-) It makes sense to read docs.

We discussed FromUnixTime parameter and this was implemented as UnixTimeSeconds parameter. So perhaps you think about FromUTC? Also there is #11731

**Comment by kasini3000** [comment]
-AsUTC out=utc. In=local. Obviously this caused ambiguity.
So I suggest:
rename parameter -asutc to -oututc
Increase the parameter -inutc

**Comment by iSazonov** [comment]
A request in #11410 was to convert output to UTC and this was implemented (without claims from @jhoneill)
Get-Date accepts only local time for years and changing this would more confuse.
(What do you expect `Get-Date -AsUTC` returns? What about `$anDateTime | Get-Date -AsUTC`? )

Best solution could be discussed in #13312.

**Comment by jhoneill** [comment]
@iSazonov  sorry I didn't search back as far as #13312 :-) 
The issue I have with `get-date` is you need to know the time zone of the machine it runs on.  
```
Get-Date -Year 2022 -Month 6 -Day 30 -Hour 12 -Minute 0 -Second 0 
```
_Means 12 noon local time_.  -AsUTC will make it it 11AM UTC if run on London/Dublin/Lisbon time. UK, 10AM UTC if run on Paris/Berlin time , 7PM UTC if run in US West coast time.  How do you get noon UTC ? 

And BTW 
[datetime]10/11/12  
uses invariant dates, not local dates. So this is October 11th world wide. 
```
function test {
param (    [datetime]$d )
$d 
}

> test 10/11/12

11 October 2012 00:00:00
```
It works if you declare a datetime parameter in your own function. 
````
>Get-date 10/11/12

10 November 2012 00:00:00
```
What ? Help says it is a [datetime] parameter but in get-date it uses local instead of invariant. 

Sorry that I'm pedantic about this stuff. Don't get me started on the Tan of 90 degrees having an Infinite error (that's .NET's fault).

**Comment by 237dmitry** [comment]
> What ?

You can set a culture you need at the moment:
```powershell
$culture = Get-Culture                                            
[System.Threading.Thread]::CurrentThread.CurrentCulture = 'en-UK' 
Get-Date 10/11/12                                                 
[System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
```

**Comment by jhoneill** [comment]
> > What ?
> 
> You can set a culture you need at the moment:

I know @237dmitry  but but some things use invariant culture. 
```
 Get-Culture

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
```

I'm on UK . 
```
> [datetime]"1/12/2021"

12 January 2021 00:00:00
```
That's invariant culture not local (see `[System.Globalization.CultureInfo]::InvariantCulture.DateTimeFormat`)  I might not like invariant being US, but it needs to pick one.  Invariant means my code does the same thing regardless of where I run it.     
But `-as [datetime]`  does it the other way round. 
```
> "1/12/2021" -as [datetime]

01 December 2021 00:00:00
```
If you know why they're different  you're doing better than I am :-)  

So what happens if I put `[datetime]$ParameterName` in a function? 
```
function test {param ([datetime]$d)  $d}

> test 1/12/2021
12 January 2021 00:00:00
```
Written that way I'd expect culture invariant, which is what I get.   
So let's have a look at Get-Date's parameters : 
```
 (get-command Get-Date).parameters['Date']

Name            : Date
ParameterType   : System.DateTime
```
So `Get-Date` also declares a `[datetime]` Parameter, so shouldn't that be invariant ? Nope, it uses local culture. 
```
> get-date -date 1/12/2021

01 December 2021 00:00:00
```

So if you use Get-Date on a server where  you don't know what culture and timezone are set 
```
> get-date -date 1/12/21 -hour 12 -minute 0 -second 0 
```
can mean one of three dates, and noon in any time zone.

**Comment by 237dmitry** [comment]
> but some things use invariant culture

Set invariant culture:
```powershell
[System.Threading.Thread]::CurrentThread.CurrentCulture = ''
```
Available cultures:
```powershell
[enum]::GetValues([Globalization.CultureTypes])   # types of cultures
[CultureInfo]::GetCultures('NeutralCultures')     # take a choise 
```

**Comment by jhoneill** [comment]
> > but some things use invariant culture
> 
> Set invariant culture:

Some things ignore the culture set on the thread and use invariant.  
Some things use whatever culture the thread uses.   You can make everything behave the same by setting the thread to invariant, IF you know in the first place which things need you to do so. 

Do you know why `[datetime]$x` is always invariant, and `$x -as [datetime]` is whatever the thread uses and why a [datetime] parameter is invariant in function but follows the thread in Get-Date and possibly other cmdlets ? 

And to the original question - apart from changing the timezone and changing it back, do you know how to make Get-Date return the right time when you don't know the timezone the machine is set to ?

**Comment by 237dmitry** [comment]
> do you know how to make Get-Date return the right time when you don't know the timezone the machine is set to ?

 If I have understood the problem.

```powershell
(Get-Date -AsUtc) + (Get-TimeZone).BaseUtcOffset
```

**Comment by jhoneill** [comment]
> > do you know how to make Get-Date return the right time when you don't know the timezone the machine is set to ?
> 
> If I have understood the problem.
> 
> ```powershell
> (Get-Date -AsUtc) + (Get-TimeZone).BaseUtcOffset
> ```

`get-date -month 6 -day 30 -hour 12`  etc   is on UTC+1  (UK + daylight savings time) but (Get-TimeZone).BaseUtcOffset returns zero (UK no dst)  so that doesn't work for most dates.

**Comment by 237dmitry** [comment]
I think there are not simple ways. [Read this article](https://devblogs.microsoft.com/scripting/check-for-daylight-savings-time-by-using-powershell/)

**Comment by iSazonov** [comment]
> The issue I have with `get-date` is you need to know the time zone of the machine it runs on.

@jhoneill This comes from [Datetime] limitations. I doubt we can solve all the problems by expanding Get-Date cmdlet. Perhaps migrating to [DatetimeOffset] and Get-DatetimeOffset cmdlet is right way to resolve all our problems with dates/times. I did not in-depth analyze but you can do in issues I referenced above.

**Comment by jhoneill** [comment]
@iSazonov  
Some of it is definitely [DateTime] . Some is how Get-Date is implemented. 

`Get-Date`   returns the current datetime as local time.  Most people would be surprised if it didn't give the same time as the clock in the system tray. So that's good. 


`Get-Date -utc `   returns the current time as UTC.  Many people would expect a way to get "absolute" or "zulu" time this is logical too. 

After that the behaviour is just **odd**. I haven't checked the code, but it seems to do this
```
$date = [datetime]::now()    # Current date, local format
if ($year)  {$date.year  = $year}
if ($month) {$date.month = $month}
..etc 
```
So if you give 21 as the year it sets the year 0021, and any parts that are omitted remain set to the current (local) value, and any parts which are provided become local 
 
Finally if does 
```
if ($asUtc) { $d.ToUniversalTime() } else { $d }  
```


This whole question came about because I was fixing someone else's code which split text and passed the results as parameters to `get-date` . Someone more experienced would use `[datetime]::new`  and specify a `DateTimeKind` or one of the parse methods `[datetime]` provides.

**Comment by jhoneill** [comment]
> :-) It makes sense to read docs.
> 

It's a shame no-one read them before they went out.  There are mark down tables in the notes and examples which are fine on-line but for get-help they each turned into a single long string 

The help for this cmdlet isn't up to the normal standard, and as far as I can see it is nearly the same in 7.2 as it was in 3.0

**Comment by iSazonov** [comment]
> The help for this cmdlet isn't up to the normal standard, and as far as I can see it is nearly the same in 7.2 as it was in 3.0

Please open new issue in https://github.com/MicrosoftDocs/PowerShell-Docs with examples what you want add/update.

**Comment by jhoneill** [comment]
I'm going to close this. @iSazonov  I think there is a "By Design" tag you can add. 

1. `Get-Date` always works from _local_ time, using either `[datetime]::now` which is the localize time or the `-Date` or  `-UnixTimeSeconds`  parameter converted to a local `[datetime]`
2.  If `-year`, `-month`, `-day`, `hour`, and/or `-minute`  are given they replace just that value part of the local time.
3. `-AsUTC`  is applied at the end.  So  `Get-Date  -Month 6 -Hour 2 -AsUTC`   keeps year, day, minutes, seconds and fractions of the seconds and changes the month to June (DST in the Northern Hemisphere) and the hour to 2AM and then converts to UTC.  Writing it as  `get-date -asutc  -month 6 -hour 2 ` of course produces the same result, but might suggest to the reader that we have changed the UTC hour. 
4. To reliably build a UTC time one should use `[datetime]::new()` and specify the kind as universal. To show the time for a different time zone one should use `[timezoneinfo]ConvertTimeBySystemTimeZoneId`
5. As a compiled cmdlet a `DateTime` parameter passed to Get-Date (`-date`) is converted using local culture settings. PowerShell handles compiled cmdlets and functions differently the conversion for Functions always uses invariant culture. The conversion of some types (including datetime) for compiled code uses local culture. It is a bug but fixing it would break too much existing code. 

I'll take my documentation thoughts for Get-Date to the proper place.
