### ISSUE TITLE
PowerShell 7.20 unstable when running from command line or MSBuild

### ISSUE THREAD

**Issue by yannicvandekuit** [PowerShell/PowerShell#16591]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For my example i used a simple script to output "Test":
`Write-Output "Test"`

Running the script from Command line result in unstable results.
Several times, the script will run correctly.
However after a running the scripts a few times, the script will not execute.

For running scripts in MSBuild, i get the same result. The script gets called by MSBuild, however the build will stop there as the script is not executed.

### Expected behavior

```console
Test
```

### Actual behavior

```console
Script not executing consistently
```

### Error details

```console
No Error returned
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

As seen in the image below, the scripts runs correct several times and outputs "Test".
At the last time we see the command is send, but the script is not executed.
Within the process explorer we see that pwsh.exe is running. When i close this one, the command line also works again as intended.

![image](https://user-images.githubusercontent.com/25219371/145573240-0fa08d5e-6983-4328-bd17-951e1e1aa24b.png)

**Comment by daxian-dbw** [comment]
@yannicvandekuit Does the `D:\experiments\Test.ps1` only contain `Write-Output "Test"` in it? If not, can you share the whole `Test.ps1` script?
Can you try `"c:\Program Files\PowerShell\7\pwsh.exe" -noprofile D:\experiments\Test.ps1` and see if you would run into the same problem?
Also, is the `cmd.exe` in the screenshot running as a 32-bit process or 64-bit process? (you can check this in Task Manager, click `Details`, find the process, then check the `Platform` column)

**Comment by yannicvandekuit** [comment]
@daxian-dbw thanks for your response.

`D:\experiments\Test.ps` indeed only contains `Write-Ourput "Test"`, and the `cmd.exe` process is running as a 64-bit process.

Using  `"c:\Program Files\PowerShell\7\pwsh.exe" -noprofile D:\experiments\Test.ps1` also results in the same problem.
![image](https://user-images.githubusercontent.com/25219371/145777629-8a9344cd-334a-4a80-885e-4c8bafe255a4.png)

**Comment by iSazonov** [comment]
@yannicvandekuit Can you run `pwsh -noninteractive` and share results?

**Comment by yannicvandekuit** [comment]
@iSazonov 
![image](https://user-images.githubusercontent.com/25219371/145825528-6483ab45-7999-4a7d-8c89-ae8410e0ad5f.png)
Same outcome once again.

**Comment by daxian-dbw** [comment]
@yannicvandekuit I cannot reproduce the hang locally. I'm afraid you will have to collect a dump from your repro, by [dotnet-dump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump). Please use `dotnet-dump collect -p <process-id> --type Heap -o <path-to-dump-file>`. Please share the dump in some way (OneDrive, etc.), and we will take a look.
