### ISSUE TITLE
PowerShell 7.2.0 - arrow navigation does not work on Linux, outputs letters on arrow key presses

### ISSUE THREAD

**Issue by blochl** [PowerShell/PowerShell#16606]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install PowerShell 7.2.0 from the package here: https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/powershell_7.2.0-1.deb_amd64.deb .
2. Start it (`pwsh`).
3. Try to go up in history (arrow up), or going left/right in a text line (left/right arrows).

### Expected behavior

Arrow keys up/down go up/down the history, arrow keys left/right navigate within the text line.

### Actual behavior

```console
PS /home> OAOAOAOAOAOAOAODODODOCOCOCOCOCOC
```
...Appears when the arrow keys are pressed.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@blochl Please install latest PSReadline version and check again. https://github.com/PowerShell/PSReadLine/releases/tag/v2.2.0-beta4

**Comment by 237dmitry** [comment]
This may be individual linux setting or settings of PSReadline module. What outputs:
```
Get-PSReadLineKeyHandler | Where { $_.key -like '*Arrow' }
```
And one more question -- what linux distribution do you use? I am using Arco Linux (arch-based) and always install Powershell from tar package.

**Comment by blochl** [comment]
> This may be individual linux setting or settings of PSReadline module. What outputs:
> 
> ```
> Get-PSReadLineKeyHandler | Where { $_.key -like '*Arrow' }
> ```
> 
> And one more question -- what linux distribution do you use? I am using Arco Linux (arch-based) and always install or update Powershell from tar package.

```powershell
> Get-PSReadLineKeyHandler | Where { $_.key -like '*Arrow' }

Cursor movement functions
=========================

Key        Function     Description
---        --------     -----------
LeftArrow  BackwardChar Move the cursor back one character
RightArrow ForwardChar  Move the cursor forward one character

History functions
=================

Key       Function        Description
---       --------        -----------
DownArrow NextHistory     Replace the input with the next item in the history
UpArrow   PreviousHistory Replace the input with the previous item in the history

Selection functions
===================

Key              Function           Description
---              --------           -----------
Shift+LeftArrow  SelectBackwardChar Adjust the current selection to include the previous character
Shift+RightArrow SelectForwardChar  Adjust the current selection to include the next character
```
I'm using Arch Linux.

**Comment by daxian-dbw** [comment]
According to the answer in https://vi.stackexchange.com/a/15328:

> When you press `Up`, the terminal sends the sequence:
>
>- (if it's in normal mode) `CSI A`, where `CSI` means `Control Sequence Introducer` and is produced by `ESC [;` in caret notation, the >whole sequence is displayed as `^[[A`
>- (if it's in application mode) `SS3 A`, where `SS3` is described as `Single Shift Select of G3 Character Set` here, and is produced by `ESC O`; in caret notation, the whole sequence is displayed as `^[OA`

So, it looks your terminal is in application mode for some reason.

**Comment by blochl** [comment]
> @blochl Please install latest PSReadline version and check again. https://github.com/PowerShell/PSReadLine/releases/tag/v2.2.0-beta4

I never needed to install PSReadline explicitly until now, and up to v7.1.5 everything worked fine. I think that I have the latest installed though, as `Install-Module PSReadline` returns immediately and without error.

**Comment by blochl** [comment]
> According to the answer in https://vi.stackexchange.com/a/15328:
> 
> > When you press `Up`, the terminal sends the sequence:
> > 
> > * (if it's in normal mode) `CSI A`, where `CSI` means `Control Sequence Introducer` and is produced by `ESC [;` in caret notation, the >whole sequence is displayed as `^[[A`
> > * (if it's in application mode) `SS3 A`, where `SS3` is described as `Single Shift Select of G3 Character Set` here, and is produced by `ESC O`; in caret notation, the whole sequence is displayed as `^[OA`
> 
> So, it looks your terminal is in application mode for some reason.

In the same terminal:
```
$ # Install PowerShell 7.1.5
$ sudo pacman -U ~/AUR/powershell-bin/powershell-bin-7.1.5-1-x86_64.pkg.tar.zst
...
$ pwsh
PowerShell 7.1.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.2.0 
   Upgrade now, or check out the release page at:       
     https://aka.ms/PowerShell-Release?tag=v7.2.0       

PS /home> # Arrows work...
PS /home> exit
$ # Install PowerShell 7.2.0
$ sudo pacman -U ~/AUR/powershell-bin/powershell-bin-7.2.0-1-x86_64.pkg.tar.zst
...
$ pwsh
PowerShell 7.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home> OAODOCODOAODOCODOCOAODOCOAOD
PS /home> # Arrows don't work...
```

**Comment by daxian-dbw** [comment]
Interesting, PS 7.1.5 and PS 7.2 both ship the 2.1.0 version of PSReadLine module, so it's not because of the PSReadLine module.
PS 7.1.5 uses .NET 5 while PS 7.2 uses .NET 6. I suspect something is changed in `Console.ReadKey`. Can you please try `[System.Console]::ReadKey($true)` in both PS 7.1.5 and PS 7.2 and share the results here?

**Comment by iSazonov** [comment]
I see only one change https://github.com/dotnet/runtime/pull/42432

**Comment by 237dmitry** [comment]
In my environment there are not problems. As I said I installed PowerShell just unpacking [powershell-7.2.0-linux-x64.tar.gz]( https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/powershell-7.2.0-linux-x64.tar.gz) to `/opt/microsoft/powershell/7/` and created symbolic link from `/opt/microsoft/powershell/7/pwsh` to `/usr/bin/pwsh`.
```
pushd /usr/bin
sudo ln -s /opt/microsoft/powershell/7/pwsh
popd 
```

**Comment by blochl** [comment]
> Interesting, PS 7.1.5 and PS 7.2 both ship the 2.1.0 version of PSReadLine module, so it's not because of the PSReadLine module. PS 7.1.5 uses .NET 5 while PS 7.2 uses .NET 6. I suspect something is changed in `Console.ReadKey`. Can you please **try `[System.Console]::ReadKey($true)` and press `UpArrow`** in both PS 7.1.5 and PS 7.2 and share the results here?

```
$ pwsh
PowerShell 7.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home> [System.Console]::ReadKey($true)

KeyChar     Key Modifiers
-------     --- ---------
       UpArrow         0

PS /home> exit
$ sudo pacman -U ~/AUR/powershell-bin/powershell-bin-7.1.5-1-x86_64.pkg.tar.zst
...
$ pwsh
PowerShell 7.1.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.2.0 
   Upgrade now, or check out the release page at:       
     https://aka.ms/PowerShell-Release?tag=v7.2.0       

PS /home> [System.Console]::ReadKey($true)

KeyChar     Key Modifiers
-------     --- ---------
       UpArrow         0

PS /home> exit
```

**Comment by daxian-dbw** [comment]
> So, it looks your terminal is in application mode for some reason.

Actually, .NET requires application mode to support Arrow key escape sequences. So being in application mode is expected.
Run out of clues at this point ... Can you try the [PS 7.2.1](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.1) that was released yesterday? It's on top of .NET 6.0.1.

**Comment by blochl** [comment]
Same with 7.2.1. (Installed from: https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell_7.2.1-1.deb_amd64.deb)

**Comment by chaplina** [comment]
I was having this same issue.  I ssh to the Oracle Enterprise Linux 7 host from my PC using urxvt and the TERM is set to rxvt.

I decided to export TERM=xterm and run pwsh and the command recall using arrow keys started to work again.

Since this was working fine pre 7.2 I'd consider this a bug. :)

**Comment by blochl** [comment]
Indeed! Just as @chaplina said!
I use the rxvt-unicode terminal as my main terminal, and it worked fine with PS 7.1.x. Now, with 7.2.x, I must run `TERM=xterm-256color pwsh` for the arrows to work.

Thanks, @chaplina , for the workaround.

And it does look like a bug / regression.

**Comment by B-Art** [comment]
Problem is the same when using bastion logon to VM running and then start `pwsh` (7.2.1).
`TERM=xterm-256color pwsh`
Works. Possibly something to do with Ascii colorcoding from `Get-PSReadLineOption`?

**Comment by daxian-dbw** [comment]
7.1.x ships with 2.1.0 version of PSReadLine, and 7.2.x ships the same version PSReadLine, so the issue you ran into should have nothing to do with PSReadLine. It's likely an issue rooted in .NET 6.

**Comment by daxian-dbw** [comment]
Opened the issue https://github.com/dotnet/runtime/issues/63387 on dotnet/runtime.
