### ISSUE TITLE
Test paths in docs/testing-guidelines/testing-guidelines.md needs to be updated

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#1660]
There are 3 sub-issues in 'docs/testing-guidelines/testing-guidelines.md':
* [ ] test run examples are using non-existing test paths

       > Start-PSPester -Directory test/powershell/engine/Api 
       > Start-PSPester -Directory test/powershell/engine/Api -Test XmlAdapter.Tests.Api 

* [ ] test layout at the end of the doc needs to be updated as the test folder has been changed

        > The current layout of tests is: 
        >   test/powershell/engine 

* [ ] in **Test Layout** section, the following sentence is not clear enough and needs to be updated

        > If you are unsure, you can make it part of your PR, or create an issue.

**Comment by JamesWTruher** [comment]
I've recently updated this list to what I believe it should be
