### ISSUE TITLE
7.2.1: $PSStyle.OutputRendering

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#16618]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I think this is not a good idea to set `$PSStyle.OutputRendering = 'Ansi'` by default since esc-sequences can spoil the output to the console or file.

```
dir | out-file file.txt
```

### Expected behavior

```console
$PSStyle.OutputRendering = 'Host'
```

### Actual behavior

```console
$PSStyle.OutputRendering = 'Ansi'
```

### Environment data

```powershell
This is one more example: `$PSVersionTable | Out-String | Set-Clipboard`

[38;2;80;80;80mName                           Value[0m
[38;2;80;80;80m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
This is a by design change because using `Host` by default exposes a spoofing issue. See https://github.com/PowerShell/Announcements/issues/28 for details.

**Comment by FireInWinter** [comment]
Seems like a bad "fix" for a security issue.  The announcement says it is temporary, but doesn't give an estimate on a fix and has comments disabled.  Any idea on when this will be resolved?

**Comment by daxian-dbw** [comment]
> What if the update breaks my script or module?
You can uninstall the newer version of PowerShell 7 and install the previous version of PowerShell 7.
**This should be treated as a temporary measure.**
Therefore, the script or module should be updated to work with the patched version of PowerShell 7.

Above is quoted from the announcement. It means using an older version of pwsh should be a temporary measure, not that this fix is temporary.
