### ISSUE TITLE
update-help使用出现问题

### ISSUE THREAD

**Issue by 597761249** [PowerShell/PowerShell#16620]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PS C:\> Update-Help                                                                                                   

### Expected behavior

```console
更新help
```

### Actual behavior

```console
Update-Help : 无法更新带有 UI 区域性 {zh-CN} 的模块“PSReadline”帮助: 在 HelpInfo XML 文件中检索不到 UI 区域性         zh-CN。确保模块清单中的 HelpInfoUri 属性有效或检查网络连接是否正常，然后重试该命令。
所在位置 行:1 字符: 1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

### Error details

```console
Update-Help : 无法更新带有 UI 区域性 {zh-CN} 的模块“PSReadline”帮助: 在 HelpInfo XML 文件中检索不到 UI 区域性         zh-CN。确保模块清单中的 HelpInfoUri 属性有效或检查网络连接是否正常，然后重试该命令。
所在位置 行:1 字符: 1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

·

**Comment by daxian-dbw** [comment]
I believe the help content is not available in zh-CN locale ... @sdwheeler can you please confirm?

**Comment by sdwheeler** [comment]
Help content is only available in English.

**Comment by daxian-dbw** [comment]
@sdwheeler Is there an issue somewhere to track the help content localization work that may happen in future?

**Comment by sdwheeler** [comment]
@daxian-dbw Not right now. There are multiple issues that need to be solved. First is PlatyPS has to support localization.
- https://github.com/PowerShell/platyPS/issues/535
- https://github.com/PowerShell/platyPS/issues/484

Then the docs build pipeline would need to support it and that is an even more difficult problem.

**Comment by 597761249** [comment]
（⊙ｏ⊙）Thank you for your answer.&nbsp;Does this mean that I need to change my operating system to English?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerShell/PowerShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 上午9:05
***@***.***&gt;;
抄送:&nbsp;"●??????若△ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerShell/PowerShell] update-help使用出现问题 (Issue #16620)





 
@daxian-dbw Not right now. There are multiple issues that need to be solved. First is PlatyPS has to support localization.
  
PowerShell/platyPS#535
 
PowerShell/platyPS#484
  
Then the docs build pipeline would need to support it and that is an even more difficult problem.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 597761249** [comment]
I try to use&nbsp; Update-Help -ErrorAction SilentlyContinue&nbsp; &nbsp;in PowerShell, But it didn't work




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "●??????若△ "                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 上午9:22
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [PowerShell/PowerShell] update-help使用出现问题 (Issue #16620)





（⊙ｏ⊙）Thank you for your answer. Does this mean that I need to change my operating system to English?


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PowerShell/PowerShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 上午9:05
***@***.***&gt;;
抄送:&nbsp;"●??????若△ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerShell/PowerShell] update-help使用出现问题 (Issue #16620)





 
@daxian-dbw Not right now. There are multiple issues that need to be solved. First is PlatyPS has to support localization.
  
PowerShell/platyPS#535
 
PowerShell/platyPS#484
  
Then the docs build pipeline would need to support it and that is an even more difficult problem.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daxian-dbw** [comment]
@597761249 Please try `Update-Help -UICulture en-US`, this will get you the help files for the `en-US` locale.

@sdwheeler Thanks for the additional info. It sounds this is something that we are surely aware of, and it will a relative long time to get the build infrastructure ready for help content localization. I will resolve this issue as by-design for now.

**Comment by 597761249** [comment]
Thank you. I tried, but the following is displayed：


Update-Help: Failed to update Help for the module(s) 'PSReadline' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerShell/PowerShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 上午9:50
***@***.***&gt;;
抄送:&nbsp;"●??????若△ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerShell/PowerShell] update-help使用出现问题 (Issue #16620)





 
@597761249 Please try Update-Help -UICulture en-US, this will get you the help files for the en-US locale.
 
@sdwheeler Thanks for the additional info. It sounds this is something that we are surely aware of, and it will a relative long time to get the build infrastructure ready for help content localization. I will resolve this issue as by-design for now.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daxian-dbw** [comment]
For that issue, check out https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/

**Comment by 597761249** [comment]
Thank you. The problem is solved


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PowerShell/PowerShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 上午10:50
***@***.***&gt;;
抄送:&nbsp;"●??????若△ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PowerShell/PowerShell] update-help使用出现问题 (Issue #16620)





 
For that issue, check out https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/
  PowerShell Team
Updating help for the PSReadLine module
Updating help for the PSReadLine module You may have noticed an error message when trying to update the help for the PSReadLine module. In the example above, I am trying to update help for the PSReadLine module on my Windows computer.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
