### ISSUE TITLE
Ability to display forward slashes instead of backward slashes everywhere in the shell for path, get-childitem, etc..

### ISSUE THREAD

**Issue by Manish0925** [PowerShell/PowerShell#16622]
### Summary of the new feature / enhancement

Option to display / instead of \ everywhere

### Proposed technical implementation details (optional)

Remove read-only property from [System.IO.path]::DirectorySeparatorChar.
[System.IO.path]::AltDirectorySeparatorChar exists as / but I want forward slashes to be displayed by default. As someone working across cross-platform, the looking at "\\" in shell is irritating.

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PowerShell/pull/8587#issuecomment-477375667
PowerShell has some bugs in the area (ex., see #9244) and we already have some issues for them. You can review them, discuss and try to fix.
