### ISSUE TITLE
Disambiguate -f to -Force when available.

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16621]
### Summary of the new feature / enhancement

I would really like to be able to write commands like:

```powershell
ri -r -f somedir
```

currently I have to write:

```powershell
ri -r -fo somedir
```

because PowerShell will throw an error about -f being ambiguous since there is also `-Filter`..

If we can agree that when people use `-f` they generally mean `-Force` when that parameter is available, as is common in POSIX commands.

I would like it even better if I could write:

```powershell
ri -rf somedir
```

but that is a much more complicated issue for another time.

### Proposed technical implementation details (optional)

In the parameter disambiguation code path, check for `-f` and see if a full parameter `-Force` is available, when there are multiple matches. Should be fairly simple. I could give it a try if you like.

**Comment by MartinGC94** [comment]
I think it's a bad idea to create this kind of inconsistency. It's not very intuitive to have one magic word that changes the way parameter binding works, and if we add -f today someone will ask for -r tomorrow and then it gets too complicated to learn.  
Personally I don't think this feature should even have existed in the first place, explicit parameter names and aliases should have been enough, especially with the great tab completion we have.

**Comment by kasini3000** [comment]
https://www.cnblogs.com/piapia/p/15403242.html
I want to sell you my PowerShell TUI free script "power alias"

**Comment by iSazonov** [comment]
Dup #11310

**Comment by kmccl922** [comment]
I'm going to report you'll to FBI harassment

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 16, 2021 at 3:02 PM, ***@***.***> wrote:   


Closed #16621.

**Comment by jhoneill** [comment]
Just to share something for the @rkitover  
PsReadline lets you run a script when Enter is pressed and that could change the -f to -force , the following works but I have not tested it heavily

```PowerShell
Set-PSReadLineKeyHandler -Key Enter -ScriptBlock {
    param($key, $arg)
    $line   = $null
    $cursor = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor) 
    $r = [regex]::Match($line,'\s-f\b')
    if ($r.Success) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace($r.Index, $r.Length, '  -Force') } 
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
}
```

**Comment by rkitover** [comment]
@jhoneill that is amazing, and opens up many possibilities, thank you very much!

**Comment by rkitover** [comment]
One possibility I thought of, is that this could be used to make an alias system similar to bash, as in, a hook for a command word that does not affect anything else.

**Comment by jhoneill** [comment]
@rkitover   You can use it in lots of ways.  :-) 

If you're going to have lots of search and replace terms  for perf, I'd make one big regex  in advance, and compiled
```PowerShell 
 $global:cmdRegex = [regex]::new( ' - f\b' -p\b' ,'Compiled')    
```
And them  in the script block I'd have 
```PowerShell
$replacement = @{' -f'=' -Force '; '-p'=' -Path ' } 
$r = $cmdRegex.Match($line)                                                      
If ($r.success)  { [Microsoft.PowerShell.PSConsoleReadLine]::Replace($r.Index, $r.Length,  $replacement[$r.value] ) } 
````

That way you avoid creating lots of regex objects and avoid a switch / multi-part if with  branch per option.
