### ISSUE TITLE
Alpine Linux packages on latest 7.3.0-preview.1 are missing powershell.config.json

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#16636]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Open Alpine packages for latest v7.3.0-preview.1 
One side effect of this is that all experimental features are disabled by default on Alpine v7.3.0-preview.1 packages.

### Expected behavior

```console
`powershell.config.json` should be next to `pwsh`.
```

### Actual behavior

```console
`powershell.config.json` is missing.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Linux 5.4.143-0-lts #1-Alpine SMP Tue, 31 Aug 2021 12:47:23 UTC
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
@anmenaga is this resolved in latest preview?

**Comment by adityapatwardhan** [comment]
Verified that it work with 7.3.0-preview.4

PS D:\PSGit\PowerShell> docker run -it --rm mcr.microsoft.com/powershell:preview-alpine-3.14
Unable to find image 'mcr.microsoft.com/powershell:preview-alpine-3.14' locally
preview-alpine-3.14: Pulling from powershell
8663204ce13b: Pull complete
25188b782f8e: Pull complete
a7e3a80b413f: Pull complete
Digest: sha256:988c6b1c4215b1f0784b6000de587ad5d094c57eac8226f660749dff5453d037
Status: Downloaded newer image for mcr.microsoft.com/powershell:preview-alpine-3.14
PowerShell 7.3.0-preview.4
PS /> dir $pshome\*.json

    Directory: /opt/microsoft/powershell/7-preview

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rw-r--r--                                      5/18/2022 18:25            425 powershell.config.
                                                                               json
-rw-r--r--                                      5/18/2022 18:25         127376 pwsh.deps.json
-rw-r--r--                                      5/18/2022 18:25            496 pwsh.runtimeconfig
                                                                               .json
