### ISSUE TITLE
Unblock-File cmdlet - Modules\PSReadLine\PSReadLine.format.ps1xml

### ISSUE THREAD

**Issue by klodoma** [PowerShell/PowerShell#16632]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Installed 7.2.1 and getting the following error:

```
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.


Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this
script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run
C:\bin\powershell\7\Modules\PSReadLine\PSReadLine.format.ps1xml?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"):
```

### Expected behavior

```console
Powershell runs.
```

### Actual behavior

```console
Do you want to run
C:\bin\powershell\7\Modules\PSReadLine\PSReadLine.format.ps1xml?
```

this message is displayed
```


### Error details

```console
Message is displayed
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

![image](https://user-images.githubusercontent.com/944350/146369586-9de88c28-3f51-40a2-af5f-f227cb3153ba.png)

**Comment by klodoma** [comment]
Update. I upgraded by using PowerShell-7.2.1-win-x64.zip. 
Installing PowerShell-7.2.1-win-x64.msi seems to fix the issue.

**Comment by jhoneill** [comment]
> Update. I upgraded by using PowerShell-7.2.1-win-x64.zip. Installing PowerShell-7.2.1-win-x64.msi seems to fix the issue.
> 
> OS is Windows 11.

If you unzip the download without unblocking the ZIP file first you will get some files which have the "blocked" flag set.  I find this a pain because every time I download a ZIP I forget, and the quickest thing is delete, unblock the zip, unzip again.

**Comment by klodoma** [comment]
Thanks. I didn't knew about **unblocking the ZIP**. 

Tried it out, seems good!

**Comment by jhoneill** [comment]
> Thanks. I didn't knew about **unblocking the ZIP**.
> 

- Don't worry, you're not the first, and won't be the last :-)  Like I said, I _know_ and I _still_ forget to do it.
