### ISSUE TITLE
The "A new PowerShell stable release is available" dialogue should only appear for major versions, all others should autoupdate.

### ISSUE THREAD

**Issue by HexCodeFFF** [PowerShell/PowerShell#16630]
### Summary of the new feature / enhancement

The "A new PowerShell stable release is available" dialogue should only appear for versions that are incompatible with the previous ones. there should also be an option to disable it entirely and info on how to do so within the dialogue.

### Proposed technical implementation details (optional)

Instead of linking to the powershell online download for every minor release, either have it autoupdate in the background, only show for major versions, or just suggest `winget upgrade powershell`
of course, if autoupdating is implemented, give users the option to turn it off.

**Comment by iSazonov** [comment]
Dup #16234

**Comment by kilasuit** [comment]
You can (on windows) already opt into auto update via Microsoft Update which will do so fine for each minor version. 

Also as PowerShell is an Administration tool, as an adminstrator I & many others (particularly in regualted sectors) do not want applications auto updating  (especially on servers but also on clients too) unless explictly opted in to like via MU or other tooling
