### ISSUE TITLE
$PsStyle.OutputFormatting =  PlainText is ineffective when host is not 'ConsoleHost'

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#16643]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Setting $PSStyle.OutputRendering = "PlainText"  removes colour. However it only seems to do so if the `$host.name` is  `ConsoleHost` so using a .Net Interactive notebook (which doesn't load the profile as a way to set psstyle preferences) or the the PowerShell Integrated console in VS Code.  (".NET Interactive Host"  and " Visual Studio Code Host" respectively) 

### Expected behavior

```console
Setting $PSStyle.OutputRendering = "PlainText"  removes colour
```

### Actual behavior

```console
Setting $PSStyle.OutputRendering = "PlainText" does not removes colour when the host is not "Consolehost" see visuals
```

### Error details

```console
No message
```

### Environment data

```powershell
[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Below both show labels in green despite plain text being selected. 
![image](https://user-images.githubusercontent.com/16209593/146528131-5638c91e-6806-433f-8939-43b9081593bb.png)

.Net Interactive notebook

![image](https://user-images.githubusercontent.com/16209593/146528299-4137c81c-67b0-4609-a22a-a9bf826fd1ef.png)

PowerShell Integrated Console  in VS Code. 

In the console host (Windows terminal, legacy console, and pwsh in VS Code outside the integrated vs code console).  plain text removes the green colouring.
![image](https://user-images.githubusercontent.com/16209593/146529165-ddbf20c6-f952-42da-b8e3-92d969bd4100.png)

**Comment by 237dmitry** [comment]
I do not know. In Windows Console Host and in VSCode all are working as expected. If I set to 'PlainText' the coloring disappeared.

**Comment by jhoneill** [comment]
@237dmitry  
In VS code does the drop down say "pwsh" or "PowerShell Integrated Console"  ?
For me, it works fine if it is pwsh, (just the same as if I do [win key] [r] pwsh, or if I use Windows Terminal)  - that's the bottom picture, but if it is the "PowerShell Integrated Console" I get the middle picture.

**Comment by 237dmitry** [comment]
Ah, sorry,  I was too hasty. In VSCode coloring is disappeared AFTER setting 'PlainText'. All strings before are still colored.

**Comment by daxian-dbw** [comment]
VSCode integrated console and PowerShell notebook use different hosts, which haven't been updated to work with `$PSStyle`. Can you maybe open separate issues in .NET Interactive and PSES repos about this?

**Comment by daxian-dbw** [comment]
Quote the discussion between @jhoneill and me from https://github.com/PowerShell/PowerShell/issues/16635#issuecomment-996901232

> just so I'm clear, although it's a change in PowerShell itself that caused it, the fix can only come from the people who produce the hosts?

Unfortunately, yes. In PowerShell itself, the work that strips off the ANSI code is done in ConsoleHost, and that makes it necessary for other host to do something similar.

But you made me start to think, maybe that's not the right design, maybe that should be done in formatting before sending the payload to host ... there could be other applications that hosts PowerShell out there in the wild, and requiring extra work to their host after upgrading to PS 7.2 is not a pleasant ask for sure.

We may want to rethink about where to strip off the ANSI code. Does this work have to be done in host implementation? If not, it's better to do it in PowerShell formatting, so various hosts out in the wild don't need to change for `$PSStyle` to work properly when upgrading to PS 7.2.

**Comment by jhoneill** [comment]
There seem to be other problems relating to different hosts, which suggest - per @daxian-dbw  above - **shifting this out of the host is a good idea.** 

The screen shot below is using a .NET interactive notebook. 
Red is used in the right most column to say "EXCEPT in these environments. 
The section labelled 1 in the screen, shows  without colour the environment name fits on one line  but when colour is added the same text is split over two lines - I assume because the codes for "foreground red" and "reset" are treated as visible characters.  I've mentioned on #16700  that because the _reset_ has moved down a line  _Panettone service_  gets trapped between the begin and end of colour for _shared services pre-release_, turning it red.

On the bottom row, blue is used to highlight some types of action and (2) shows the codes for "foreground blue" and "reset" have reduced padding before the next column. 

![image](https://user-images.githubusercontent.com/16209593/148264358-131c0ada-f829-4ab9-894d-a2ab12743d71.png)

Neither (1) nor (2) occurs in the default host, but making people who create other hosts bring over multiple pieces of functionality is not ideal.

**Comment by JustinGrote** [comment]
It seems to me that if a host could declare  or be constructed what formats it supports (plaintext only, console emits, ANSI support), then Powershell should send that output to the host and do that work, and the host can either pass it thorugh or do with it what it wants.

**Comment by ALIENQuake** [comment]
@daxian-dbw FWIW, I'm facing this issue using SAPIEN PowerShell Studio.

**Comment by jhoneill** [comment]
Looking for something else this is fixed with the newest PowerShell integrated console in VSCode, but the problem remains in .NET Interactive.

**Comment by daxian-dbw** [comment]
@jhoneill PowerShell integrated console started to wrap a console host instance internally. The .NET Interactive cannot wrap console host within it, because it's not facing a terminal, but the .NET Interactive stdin/stdout channel.

**Comment by jhoneill** [comment]
@daxian-dbw  so something that works that way can't get clean output then ?

**Comment by daxian-dbw** [comment]
The PowerShell sub-kernel host needs to be updated to strip off the VT sequences properly as controlled by `$PSStyle`, and that's not done yet :(

**Comment by jhoneill** [comment]
But it will be done at some point ?

**Comment by simonsabin** [comment]
> The PowerShell sub-kernel host needs to be updated to strip off the VT sequences properly as controlled by `$PSStyle`, and that's not done yet :(

Should that be a switch passed in via pwsh, to control stripping of characters when pwsh called directly

**Comment by theJasonHelmick** [comment]
The Working Group has reviewed this issue and agrees it should be filed with .Net Interactive. For discussions regarding the design of PSStyle and it implementation, please open a separate issue.

**Comment by jhoneill** [comment]
@theJasonHelmick  What troubles me here is:  Is .NET  interactive the only host with any meaningful user-base which needs to take on the extra work to integrate with PowerShell, or are there a few, or potentially many ? For small numbers filing an issue with them is the right course. For large numbers the solution should be coming from the PowerShell team. I don't know of any others so I'm happy with this marked as external and closed, at least for now.  We **may** need to re-visit but no sense it getting overly worried because it is more likely we won't. 
,
