### ISSUE TITLE
Upgrade powershell by command in powershell

### ISSUE THREAD

**Issue by ICLiuLi** [PowerShell/PowerShell#16647]
### Summary of the new feature / enhancement

Upgrade powershell by command in powershell

**Comment by kmccl922** [comment]
I'm getting the FBI on you'll about harassment stop the damn messages please 

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 18, 2021 at 12:45 AM, ***@***.***> wrote:   


Summary of the new feature / enhancement

Upgrade powershell by command in powershell

Proposed technical implementation details (optional)

No response

**Comment by iSazonov** [comment]
Dup #15666 #15666
