### ISSUE TITLE
PWSH 7.2.1: Set-Service: Service * cannot be configured due to the following error: Access is denied.

### ISSUE THREAD

**Issue by penalvch** [PowerShell/PowerShell#16649]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Open PWSH as Adminstrator via Start > PowerShell > PowerShell 7 (x64) > Run as Administrator and run the below command. In Windows PowerShell 5.1.x it works fine. Hence, seems a regression.
I haven't tried the command in any prior PWSH version.
Also, SCPolicySvc is not the only service set-service fails to set with the same error message. However, it doesn't fail to set all services, just certain ones.

### Expected behavior

```console
PS C:\WINDOWS\system32> set-service -name SCPolicySvc -startuptype disabled ; stop-service -name SCPolicySvc -force
PS C:\WINDOWS\system32>
```

### Actual behavior

```console
PS C:\Windows\System32> set-service -name SCPolicySvc -startuptype disabled ; stop-service -name SCPolicySvc -force
Set-Service: Service 'Smart Card Removal Policy (SCPolicySvc)' cannot be configured due to the following error: Access is denied.
PS C:\Windows\System32>
```

### Error details

```console
get-error

Exception             :
    Type           :
Microsoft.PowerShell.Commands.ServiceCommandException
    ServiceName    : SCPolicySvc
    Message        : Service 'Smart Card Removal Policy
(SCPolicySvc)' cannot be configured due to the following error:
Access is denied.
    InnerException :
        Type            : System.ComponentModel.Win32Exception
        NativeErrorCode : 5
        ErrorCode       : -2147467259
        Message         : Access is denied.
        HResult         : -2147467259
    HResult        : -2146233087
TargetObject          : System.ServiceProcess.ServiceController
CategoryInfo          : PermissionDenied:
(System.ServiceProcess.ServiceController:ServiceController)
[Set-Service], ServiceCommandException
FullyQualifiedErrorId : CouldNotSetService,Microsoft.PowerSh
ell.Commands.SetServiceCommand
InvocationInfo        :
    MyCommand        : Set-Service
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 359
    Line             : set-service -name SCPolicySvc
-startuptype disabled ; stop-service -name SCPolicySvc -force
    PositionMessage  : At line:1 char:1
                       + set-service -name SCPolicySvc
-startuptype disabled ; stop-service -n …
                       +
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : set-service
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :




PS C:\Windows\System32>
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```

### Visuals

![image](https://user-images.githubusercontent.com/8216601/146665237-d4d7d11f-d0ab-4733-b72b-c645c61ea0bf.png)

**Comment by iSazonov** [comment]
@penalvch Could you please check in previous pwsh versions (7.0,7.1,7.2) too?

**Comment by penalvch** [comment]
> @penalvch Could you please check in previous pwsh versions (7.0,7.1,7.2) too?

No, sorry. I'm just reporting the bug. I'll leave to devs to root cause+resolve.

Thanks!

**Comment by jborean93** [comment]
At a guess the problem was caused by https://github.com/PowerShell/PowerShell/commit/ffb1549aa91688bfc910da214fca56b701554aec#diff-042692a5a997e7343b8054779ae2a9cd4a0e697b6270951b8e6fa272ebc64b9eL1721-R1735 which changed the access rights used when opening the service from `SERVICE_CHANGE_CONFIG` to `SERVICE_CHANGE_CONFIG | NativeMethods.WRITE_DAC | NativeMethods.WRITE_OWNER`. Your account will have the ability to change the config but not write the DAC or owner thus it failing to open the service handle.

The extra access rights were added so that it would be able to set the service security descriptor. I think the better option here would be to only add those 2 extra access rights only if `-SecurityDescriptorSddl` was also specified rather than all the time.

**Comment by kvprasoon** [comment]
@iSazonov , on it. Thanks for the mention 😀.

**Comment by kvprasoon** [comment]
@jborean93 like this ?
```
hService = NativeMethods.OpenServiceW(
                        hScManager,
                        Name,
                        string.IsNullOrEmpty(SecurityDescriptorSddl) ? NativeMethods.SERVICE_CHANGE_CONFIG :
                        NativeMethods.SERVICE_CHANGE_CONFIG | NativeMethods.WRITE_DAC | NativeMethods.WRITE_OWNER
                        );
```

**Comment by jborean93** [comment]
Looks like it would work. You could also do something like

```csharp
var access = NativeMethods.SERVICE_CHANGE_CONFIG;
if (!string.IsNullOrEmpty(SecurityDescriptorSddl))
    access |= NativeMethods.WRITE_DAC | NativeMethods.WRITE_OWNER;
```

Either is fine and it's really up to you and whoever reviews your PR :)

**Comment by kvprasoon** [comment]
thanks, this looks more readable.
