### ISSUE TITLE
Get-ChildItem Recurse works on PowerShell 5.1 but not on 7.2.1

### ISSUE THREAD

**Issue by rafrafek** [PowerShell/PowerShell#16656]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have created simple script to find all files of a given name on my `C:\` disk. It is working on Windows PowerShell 5.1, but not on PowerShell 7.2.1.

Create empty file `demo-2021-12-20.txt` in `C:\ps_test`
![obraz](https://user-images.githubusercontent.com/23004737/146779877-fd62f7ca-4953-4b6e-91c1-4bef7cf995ec.png)
and run this `script.ps1`:
```PowerShell
Get-ChildItem -Path "C:\" -Filter "demo-2021*.txt" `
    -Recurse -Force -ErrorAction SilentlyContinue |
    ForEach-Object {
        $output = $_.Name + "`t" + $_.FullName
        Write-Host $output
    }
```

### Expected behavior

```console
demo-2021-12-20.txt     C:\ps_test\demo-2021-12-20.txt
```

### Actual behavior

```console
Line |
   1 |  Get-ChildItem -Path "C:\" -Filter "demo-2021*.txt" `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The system cannot find the path specified.
```

### Error details

```console
Error occurs when using PowerShell 7.2.1 but not when using Windows PowerShell 5.1.19041.1320 (same machine).
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can not reproduce
![image](https://user-images.githubusercontent.com/22290914/146802587-e0921b1c-1931-4041-9997-c12b37fa1795.png)
Are you sure you correctly typed "C:\"?

**Comment by rafrafek** [comment]
> Are you sure you correctly typed "C:"?

Yes, I've pasted my script here without changes.

Is your script running to the end without errors?

When I search for different names, it sometimes gives me one result, and after a while it stops with the _system cannot find the path specified_ error. Not only prints error, but also stops finding files, which makes my script useless on 7.2.1 :(

**Comment by rafrafek** [comment]
I've copied `demo-2021-12-20.txt` to root `C:\` directory, so there are two copies now. First one is being found by both PowerShell versions, but the second txt file is being found only by PowerShell 5.1. PowerShell 7.2.1 throws error and stops.

![obraz](https://user-images.githubusercontent.com/23004737/146818430-44d6b945-48dd-446f-9c23-f2290ec31a7b.png)

**Comment by rafrafek** [comment]
> The system cannot find the path specified.

This error tells nothing about actual path. It is not `C:\` but something deeper found by `-Recurse` flag. 

How can I check which exact path it is complaining about?

**Comment by rafrafek** [comment]
I think I have found the source of this error. I have paths on my disk that are over 260 characters in length. It was pain to figure it out, but in the end I got it simply by filtering whole disk recursive with "*". There is issue already for it: https://github.com/PowerShell/PowerShell/issues/16123

Thank you @iSazonov for testing! I'm closing this issue and I'll test it with 7.3 :)

**Comment by jhoneill** [comment]
Start with 
```PowerShell
Get-ChildItem -Path "C:\" -Filter "demo-2021*.txt"  -recurse
````
Without any of the other parts.  I'm guessing there is a problem directory which threw a non-terminating error before and is a terminating error now. 

You can try 
```PowerShell
Get-ChildItem   -path C:\ -Directory | foreach {write-host $_ ; Get-ChildItem  $_ -filter "demo-2021*.txt" -Recurse} 
```
And that well tell you which directory is causing the problem.
