### ISSUE TITLE
Support --option style for arguments

### ISSUE THREAD

**Issue by omidkrad** [PowerShell/PowerShell#16654]
### Summary of the new feature / enhancement

For compatibility with Bash, and Linux CLI commands I recommend supporting `--option` style for augments when the specified `option` exactly matches the parameter name. This should not conflict with the way powershell currently parses arguments.

For example, `ls --directory` currently fails with an error. This proposal is to allow this command since `directory` parameter exactly matches the parameter.

**Comment by MartinGC94** [comment]
This would actually be a breaking change. This syntax is currently treated like a positional parameter, so in your example it would be bound to Path and Get-ChildItem would look for an item called --directory in the current directory.

**Comment by iSazonov** [comment]
> For compatibility with Bash

Perhaps bash can become compatible with pwsh. 😺

**Comment by vexx32** [comment]
There's nothing stopping you from using `--option` style parameters when using command-line applications, if they support that style of option. In my opinion, it's unlikely PowerShell is going to change its parameter styling to match, though.

**Comment by kasini3000** [comment]
PowerShell, pwsh supports -- parameters of (win,linux) external commands, for example:
/usr/bin/curl --version    
As for PowerShell cmdlets, scripts, that's not necessary.
