### ISSUE TITLE
Not an issu

### ISSUE THREAD

**Issue by codecastor** [PowerShell/PowerShell#16651]
Deleted

**Comment by iSazonov** [comment]
```powershell
PS C:\tmp> "".Trim

OverloadDefinitions
-------------------
string Trim()
string Trim(char trimChar)
string Trim(Params char[] trimChars)
```

You say about C# method. PowerShell can not change the method. You can use script code like https://stackoverflow.com/questions/13062414/how-can-i-remove-the-part-http-from-a-string

**Comment by jhoneill** [comment]
If it isn't clear what @iSazonov  is saying 
```
$Path = "Computer\HKCU\Software\Microsoft"
$Path.Trim("romputeC\")
```
Might give you a clue. 


Does the same thing.  What is actually happening is "Computer\" is being converted to @( 'C', 'o', 'm', 'p'  ... ),   
use  `$Path -replace "^Computer\",""  `   or  `$Path -replace "Computer\$",""  `
