### ISSUE TITLE
Mac OS powershell

### ISSUE THREAD

**Issue by bitmastercoin** [PowerShell/PowerShell#16668]
### Summary of the new feature / enhancement

As an avid Mac OS user I would like to see powershell to be incorporated into the Mac OS.

**Comment by iSazonov** [comment]
Please clarify your request since there already is PowerShell installer for MacOs.

**Comment by ArmaanMcleod** [comment]
Did you check the MacOS installation guide? https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2
