### ISSUE TITLE
add 'TimeOut' and 'DefaultValue' parameter to read-host

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#16660]
### Summary of the new feature / enhancement

Pwsh has no timeout. Although there is timeout.exe on win, but not for read host.
At present, if you need cross platform application, you need to write your own code.

Details:
Increase parameter 'TimeOutSecond', value in seconds. default value is - 1.
Increase parameter 'DefaultValue' , default value is $null.

### Proposed technical implementation details (optional)

eg:
$foo = read-host -TimeOut 10 -DefaultValue 'bar' -prompt 'input xxx'

**Comment by jhoneill** [comment]
Back in the 1970s when I was writing programs in BASIC we had lines which said 
```
X = Input "Enter the X dimension of the thing we're calculating"
Y = Input "Enter the Y dimension"
```
People still like to use  `Read-Host`  to do the equivalent. Anything of that sort in PowerShell should be a mandatory parameter which can have help text (and behind the scenes calls the same thing as read host).
```PowerShell
[parameter(HelpMessage='Enter the X dimension of the thing we're calculating' , Mandatory=$true)]
$x
```
If run without specifying `-X` the user sees
```
Supply values for the following parameters:
(Type !? for Help.)
x: !?
Enter the X dimension of the thing we're calculating
x:
```

The only case for using `Read-Host` is "Here are some interim results, which path do you want to take".  And that is sometimes "Press enter to continue " with the implied (or `ctrl-c` to break). There are very few cases where you want _that_ to time out to a pre-determined default.  If the user leaves their screen either the commands bails and returns to the prompt so they need to run it again, or it continues when you needed the user to say "stop!"

If you absolutely need it you can use this
```PowerShell
$stopTime = [datetime]::Now.AddSeconds(10)
Write-Host "Partial results are wibble, wibble, and eckie"  
Write-Host "Input value for foo (default is 'bar'):" -NoNewline
while ([datetime]::Now -lt $stopTime -and -not [console]::KeyAvailable) {start-sleep -Milliseconds 50}
if ([console]::KeyAvailable) {$foo = read-host  } else {write-host ;$foo = 'bar' }

$foo
```

`Read-host` is actually calling something in `$host.ui` which implements  `Prompt`, `PromptForChoice`, `PromptForCredential` , `ReadLine`,  `ReadLineAsSecureString`:  this isn't just changing the _command_  it needs a change to all _hosts_ to support it - some hosts (like  .NET Interactive in notebooks) just don't support these inputs, others like VS Code do, but if a version of the language which needs the extra support finds itself on a host without them...  it's a sea of run time errors.

**Comment by mklement0** [comment]
I know everyone here probably knows it, but for the benefit of future readers: This feature request has since made a comeback, albeit without the `-DefaultValue`  part:

* #19664

  * @kasini3000's own custom implementation: https://gitee.com/chuanjiao10/kasini3000/blob/master/read-host+timeout_v2.1.ps1


* The `-DefaultValue` part to me is also still worth pursuing.

  * #14013 is an alternative / possibly complementary request, where the `-DefaultValue` argument is meant to be used to _pre-fill the edit buffer, allowing the user to just press <kbd>Enter</kbd> to accept that value or to modify the default value before submission.
