### ISSUE TITLE
Allow for 'Advanced' mode in markdig for markdown transformations

### ISSUE THREAD

**Issue by lowlydba** [PowerShell/PowerShell#16662]
### Summary of the new feature / enhancement

Allow for optional use of some (or all) [advanced markdig features](https://github.com/xoofx/markdig#usage) in the ConvertFrom-Markdown and related commands. Many of the common ones, like Pipe tables from Github Flavored Markdown, are used very frequently instead of HTML in markdown.

Allowing the advanced features to be available would greatly increase this command's usability with Github related markdown content and many other popular variations.

**Comment by michaeltlombardi** [comment]
This would require (I think) either adding a parameter to the Markdown cmdlets for additional extensions to load or loading all known extensions by default. I suspect the former would be better UX.

**Comment by michaeltlombardi** [comment]
This feature is still valid and would be useful for the Markdown cmdlets.

**Comment by lowlydba** [comment]
Uh, there is activity for sure bot :)

**Comment by kilasuit** [comment]
On a quick glance I think this will need work in the [MarkdownRender repo](https://github.com/PowerShell/MarkdownRender) before we could do anything in here to be able support this ask and #27792 

@theJasonHelmick do you know who is the maintainer for that repo?
