### ISSUE TITLE
$ErrorView = 'NormalView' is not colorizing errors

### ISSUE THREAD

**Issue by loxia01** [PowerShell/PowerShell#16665]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When $ErrorView is set to NormalView (or CategoryView), error text color changes from red to white. When checking the current value of $Host.PrivateData.ErrorForegroundColor it reports Red. It is possible to change the variable value but it has no effect in NormalView and CategoryView.
In ConciseView everything works as expected.

### Expected behavior

```console
Error text color should be the same as the $Host.PrivateData.ErrorForegroundColor value.
```

### Actual behavior

```console
Error text color is white whatever color you set to $Host.PrivateData.ErrorForegroundColor.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![2021-12-22 092221](https://user-images.githubusercontent.com/36552933/147060204-e4b1fe22-159d-442c-8d57-2232533aabf5.jpg)
![2021-12-22 092831](https://user-images.githubusercontent.com/36552933/147061218-e4c40a58-7a30-4570-8e00-52650146eb45.jpg)

**Comment by daxian-dbw** [comment]
@SteveL-MSFT can you please take a look?

**Comment by KevinMarquette** [comment]
The title of this issue should be updated to: "`$ErrorView = 'NormalView'` is not colorizing errors."

I just ran into this one trying to optimize the local dev experience. Errors are not even colored red when using this view, it's just plain text. It almost doesn't say the word error. 

```powershell
PS > 1/0
Attempted to divide by zero.
At line:1 char:1
+ 1/0
+ ~~~
+ CategoryInfo          : NotSpecified: (:) [], RuntimeException
+ FullyQualifiedErrorId : RuntimeException
```

I need to have the file path and line number in the error, but the detailed view is too much as a default setting.

**Comment by SteveL-MSFT** [comment]
Taking a look
