### ISSUE TITLE
Support OSTree-based systems

### ISSUE THREAD

**Issue by electricduck** [PowerShell/PowerShell#16679]
### Summary of the new feature / enhancement

On OSTree-based systems, at least most currently, packages cannot install things into `/usr/local/` as this is part of the "user" space and not the "immutable" space where it can keep track of changes properly: an issue which is outlined at coreos/rpm-ostree#233. This basically affects all `rpm-ostree` based distros, like Fedora Silverblue and Fedora IoT, as well as some other OSTree distros, such as openSUSE MicroOS.

I noticed a similar issue before with the package violating the Debian Policy (#13517), and now I'm curious why PowerShell even _puts_ things in `/usr/local` **as this also violates the FHS**: `/usr/local` is for the user, while `/usr` is for packages managed by the system.

The actual part of the package the installer complains about is the man pages it looks like, as outlined below.
```
$ sudo rpm-ostree install powershell
[...]
error: importing RPMs: Importing package 'powershell': Analyzing /usr/local/share/man/man1/pwsh.1.gz: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233
```

**Comment by adityapatwardhan** [comment]
We agree that it could be fixed. It is not high on the priority list, hence marking it as "Up for Grabs".

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/16679#issuecomment-1822557336

@microsoft-github-policy-service, per https://github.com/isaacs/github/issues/985#issuecomment-492826345, some users are subscribed solely to issue closure, so messages like https://github.com/PowerShell/PowerShell/issues/16679#issuecomment-1811662990 aren't useful.
