### ISSUE TITLE
PowerShell will sometimes use the wrong command in internal command calls

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#16672]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Type in the following:
```
function Get-VM {throw "Why was I run?"}
Enter-PSSession -VMName VM1 -Credential (Get-Credential)
```
And note how the error message is the same that we just added to Get-VM.
If we look at the code: https://github.com/PowerShell/PowerShell/blob/6c22065d77f0d150484ac0234938b0afb7ee11f1/src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs#L879 we can see that it runs the script `Get-VM -Name $args` and because of the command precedence rules, the function is run instead of the cmdlet.  
A simple solution to this would be to just run the command with the module qualified name: `Hyper-V\Get-VM` and that's how it's done elsewhere in this project but that doesn't solve the issue of someone intentionally overriding the module like this: `New-Module -ScriptBlock {function Get-VM{throw "Why was I run?"}} -Name Hyper-V` is there a better way to do it?

### Expected behavior

```console
A session to VM1.
```

### Actual behavior

```console
Exception: Why was I run?
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Perhaps we could use full qualified name for Get-VM cmdlet in the code.

**Comment by jborean93** [comment]
Even using the fully qualified name won’t work as you can define a function `ModuleName\My-Function` which will then be called. I’ve found you need to do something like `& (Get-Command -Name My-Function -Module Module) -Param1 foo bar …`. There might be a simpler way than this though but I’m not sure of it.

**Comment by iSazonov** [comment]
> Even using the fully qualified name won’t work as you can define a function `ModuleName\My-Function` 

User could re-define whole module :-) to break a script behavior.

I believe full-qualified name is best that we could do. Also there are other examples in PowerShell code where we could  do the same.

**Comment by PaulHigin** [comment]
@WG-Remoting
Remoting working group agrees that this is a remoting layer bug, and that the fix is to fully qualify the `Get-VM` module command.
