### ISSUE TITLE
Way to programmatically tell if this instance of PowerShell was started with -Interactive or -Login

### ISSUE THREAD

**Issue by hober** [PowerShell/PowerShell#16689]
### Summary of the new feature / enhancement

When I open a new terminal window/tab, I like my shell to display a random quote. In `zsh`, I do this by running `fortune` from inside my `.zshrc` file. But I **don't** want my shell to output a random quote when it's being run in some other (non-login shell) context. In `zsh`, you can do this by checking the `login` option:

```zsh
if [[ -o login ]]; then
    fortune
fi
```

Similarly, you can test `-o interactive` to see if `zsh` is running interactively or not.

PowerShell has a `-Login` parameter, but it doesn't appear to be an intuitive way to check for it from within my `Microsoft.PowerShell_profile.ps1` file.

It's also not clear how to check to see if PowerShell is running interactively. There's `[Environment]::UserInteractive`, but I can't tell if that's the right thing to check or not.

**Comment by 237dmitry** [comment]
```
if ((Get-Process -Id $pid).CommandLine -match 'Login') { 'Login' }
```

**Comment by iSazonov** [comment]
For implementing in Engine we need https://github.com/dotnet/runtime/issues/11305
