### ISSUE TITLE
Get-Volume often returns $null on the first attempt and works on the second

### ISSUE THREAD

**Issue by fgimian** [PowerShell/PowerShell#16688]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Simply running `Get-Volume` is all that's required to reproduce the problem.  The first time the command is issued, $null is returned.  Subsequent requests work OK until PowerShell is not used for a while, and then the issue appears again.

I have many drives on my system (at least 5 and often more if external backup drives are connected).  I'm not sure if this is a factory.

The problem did not seem to occur on the 7.0.6 release which I used for a very long time.  I recently moved to the 7.2.x releases and the problem appeared and is something I have to workaround in all my scripts or it affects my work daily.

### Expected behavior

```console
Get-Volume should always return drive information.
```

### Actual behavior

```console
Get-Volume returns $null on the first attempt, and returns results afterwards.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

N/A

**Comment by jhoneill** [comment]
Under the surface `get-volume` is calling 
`Get-CimInstance -ClassName MSFT_Volume -Namespace ROOT/Microsoft/Windows/Storage`   
If you do `import-module  storage` to get the formatting for volumes, does the CIM command do the same thing, or possibly return extra errors ? 

What you're describing sounds like (but might not be) the first call starting something but timing out before it is ready, and the second call using what the first started. And with many drives if some have gone into "sleep" mode that could be the cause. You're on a newer build of Windows than I am - I doubt if the CIM timeout has changed for Windows (`Get-CimInstance` uses the system default, and `Get-Volume` doesn't have a timeout setting. ) - but if was always OK before I'd start wondering where a timeout had changed.

**Comment by fgimian** [comment]
> import-module storage

Thank you so much for the reply.  I will try `Import-Module storage` a few times over the coming days and see if it shows anything interesting.  This could indeed be a bug that's been introduced in Windows 11 specifically, it is a little hard to say because there was a short timespan between my upgrade to PS 7.2.x and Windows 11.

Oh while writing all that, I reproduced the problem directly using `Get-CimInstance`:

```
C:\Users\Fots> import-module storage
C:\Users\Fots> import-module storage
C:\Users\Fots> Get-CimInstance -ClassName MSFT_Volume -Namespace ROOT/Microsoft/Windows/Storage
C:\Users\Fots> Get-CimInstance -ClassName MSFT_Volume -Namespace ROOT/Microsoft/Windows/Storage

DriveLetter FriendlyName       FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining      Size
----------- ------------       -------------- --------- ------------ ----------------- -------------      ----
H           Software Archive 2 NTFS           Fixed     Healthy      OK                      1.72 TB   4.55 TB
D           Overflow           NTFS           Fixed     Healthy      OK                    270.84 GB 687.37 GB
E           Kontakt Libraries  NTFS           Fixed     Healthy      OK                    210.97 GB   1.29 TB
            Telstra Windows 10 NTFS           Fixed     Healthy      OK                     44.88 GB 244.12 GB
I           Fotsies Backup 2   NTFS           Fixed     Healthy      OK                      2.78 TB   3.64 TB
F           Sample Packs       NTFS           Fixed     Healthy      OK                    679.57 MB  56.37 GB
C           Windows 11         NTFS           Fixed     Healthy      OK                    185.79 GB 488.17 GB
G           Backup             NTFS           Fixed     Healthy      OK                    762.68 GB   1.82 TB
```

**Comment by fgimian** [comment]
> Under the surface `get-volume` is calling `Get-CimInstance -ClassName MSFT_Volume -Namespace ROOT/Microsoft/Windows/Storage` If you do `import-module storage` to get the formatting for volumes, does the CIM command do the same thing, or possibly return extra errors ?
> 
> What you're describing sounds like (but might not be) the first call starting something but timing out before it is ready, and the second call using what the first started. And with many drives if some have gone into "sleep" mode that could be the cause. You're on a newer build of Windows than I am - I doubt if the CIM timeout has changed for Windows (`Get-CimInstance` uses the system default, and `Get-Volume` doesn't have a timeout setting. ) - but if was always OK before I'd start wondering where a timeout had changed.

**Comment by iSazonov** [comment]
@fgimian Please use Windows Feedback tool to report the issue to Windows team.

**Comment by fgimian** [comment]
> @fgimian Please use Windows Feedback tool to report the issue to Windows team.

No worries, all done and my feedback report is available at https://aka.ms/AAfdosc

In the meantime, this is how I'm working around the issue:

```powershell
do {
    $volumes = Get-Volume
} while ($null -eq $volumes)
```

Kindly let me know if there's anything further I can do to help
Fotis

**Comment by HollisTech** [comment]
why is this closed? It is clearly a bug. The first call to get-volume should behave exactly like the nth call to get-volume for any given set of volumes on a system.

**Comment by jhoneill** [comment]
@HollisTech   Because it is a bug, that affects PowerShell, so is correctly logged elsewhere, not a bug in PowerShell that code in this repo can fix.

**Comment by Jibun-no-Kage** [comment]
But... since we have no ability to prompt or promote this to the correct resource, maybe you can?  You have access to resources we do not.  Would think the PowerShell team would want to get core bugs fixed, right?
