### ISSUE TITLE
Getting problems with graphics

### ISSUE THREAD

**Issue by RobFosterNYC** [PowerShell/PowerShell#16690]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Don't know why this is happening, just started happening, and it didn't happen before.

### Expected behavior

```console
To work correctly
```

### Actual behavior

```console
graphics problem
```

### Error details

```console
nothing comes up
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Don't know why this is happening, just started happening, and it didn't happen before.

![Screenshot_88](https://user-images.githubusercontent.com/18384135/147894851-705c554d-c2d8-4131-b768-f8b8038527d7.jpg)

**Comment by daxian-dbw** [comment]
It's not clear what issue is being reported. Please be more specific on what is going wrong for you.

**Comment by RobFosterNYC** [comment]
Look at the line where the graphics is its broken lines going vertical.
See those black lines going through the prompt?

Here is another screenshot with another type of prompt line...
It only happens on the first line.
![Screenshot_85](https://user-images.githubusercontent.com/18384135/148174584-c6c39b26-5f6f-4bff-9fd1-53a4ef8bf446.jpg)


Then when I press ENTER key again,  it returns to normal again.
As shown here.
![Screenshot_86](https://user-images.githubusercontent.com/18384135/148174664-2e54223e-c93f-43a6-99d9-9255dc6f6136.jpg)

**Comment by kasini3000** [comment]
It seems to be a win terminal problem. Good picture

**Comment by daxian-dbw** [comment]
I doubt the issue is specific to your customized prompt, and maybe related to Windows Terminal.
Do you have the same problem with your customized prompt with PowerShell 7.2.0, [PowerShell 7.1.5](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.5), or [PowerShell 7.0.8](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.8)?

**Comment by RobFosterNYC** [comment]
yup, same issue no matter what PowerShell I use.
I even updated the customized prompt to see if the issue was that, and its not.
I changed the type of prompt & even the background. I even uninstalled all customization and rebooted computer
and reinstalled everything all over again and still get that problem.

When ANY of the PowerShells first load up, the very first line does this.  And when you press enter,
the second line comes out clean and looks proper.  as shown here.
Its just that first line thats always the problem.

![Screenshot_90](https://user-images.githubusercontent.com/18384135/148316461-773e2c17-cadb-47d1-b5da-7ad75b7819b8.jpg)

**Comment by daxian-dbw** [comment]
I suggest you open an issue in the [Windows Terminal repo](https://github.com/microsoft/terminal) asking about this.

**Comment by RobFosterNYC** [comment]
Ok np, I'll link them this post.
Thanks for trying.

**Comment by daxian-dbw** [comment]
Turns out this is a known issue in Windows Terminal: https://github.com/microsoft/terminal/issues/8341.
Will resolve as external.
