### ISSUE TITLE
Get-Date -UFormat output different from Linux

### ISSUE THREAD

**Issue by tundragon** [PowerShell/PowerShell#16692]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello,
I am using `get-date -UFormat "%V-%b-%Y"` in Windows. 
And the output is **1-Jan-2022**

I am using the same command in Linux as well
`date +"%V-%b-%Y"`
And the output is **01-Jan-2022**

%V for the week number.

As you can see, the output in Windows differs from the output in Linux.

From what i understood on https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-date?view=powershell-7.2 , `-UFormat` should "Displays the date and time in UNIX format." , but it does not.

The problem is that I am using a script in Linux which generates a file with the week number, then a script in Powershell that copies the file on the local machine.

And, because if this difference in the output ( missing 0 in the windows command ), the script fails.

Thank you

### Expected behavior

```console
get-date -UFormat "%V-%b-%Y"
01-Jan-2022
```

### Actual behavior

```console
get-date -UFormat "%V-%b-%Y"
1-Jan-2022
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by 237dmitry** [comment]
![gd](https://user-images.githubusercontent.com/78153320/147924743-0f392f1b-a21a-41eb-8118-cd0288925c1a.png)
