### ISSUE TITLE
Boolean environment variable is not negatable

### ISSUE THREAD

**Issue by lippertmarkus** [PowerShell/PowerShell#16693]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```console
PS> $env:myvar1 = $false
PS> !$env:myvar1
False
PS> -not $env:myvar1
False
PS> $env:myvar1 -eq $false
True
```

### Expected behavior

It should work like for non-environment variables:
```console
PS> $myvar2 = $false
PS> !$myvar2
True
PS> -not $myvar2
True
```

### Actual behavior

Boolean environment variable is not negatable

### Environment data

```powershell
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Environment variables are OS feature and are simple strings - no strong types exist.

**Comment by jborean93** [comment]
Adding to the above the behaviour you are seeing is how the boolean is being casted to a string. PowerShell is essentially doing `[string]$false` which becomes `False` as a string when you set the value. When you do `-not "False"` or `!"False"` the output is `$False` because the string value is not equal to `$False` when you cast it to to a bool. `$env:myvar1 -eq $false` is `$true` because it will cast the RHS to a string then compare.

**Comment by lippertmarkus** [comment]
got it, thanks!
