### ISSUE TITLE
[System.IO.File]::WriteAllBytes does not use current working directory

### ISSUE THREAD

**Issue by street-jimmy** [PowerShell/PowerShell#16697]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Calling [System.IO.File]::WriteAllBytes appears to use the directory the shell was opened at, not the current directory.

Repro:
Open the shell in <dir1>
Set-Location to <dir2>
Call [System.IO.File]::WriteAllBytes("some_valid_folder_in_dir2\file", $Byte)

### Expected behavior

```console
$Byte gets written to <dir2>\some_valid_folder_in_dir2\file
```

### Actual behavior

```console
MethodInvocationException: Exception calling "WriteAllBytes" with "2" argument(s): "Could not find a part of the path '<dir1>\some_valid_folder_in_dir2\file'."
```

### Error details

```console
MethodInvocationException: Exception calling "WriteAllBytes" with "2" argument(s): "Could not find a part of the path '<dir1>\some_valid_folder_in_dir2\file'."
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
Yep, this is the case for directly calling any .NET method that takes a file or folder path. .NET methods have no awareness of PowerShell's filesystem (or any other) provider. You must use Resolve-Path or similar to get the fully-qualified path to hand to the .NET method.

.NET's current directory cannot be reliably kept up to date with PowerShell's current session path, because the .NET current directory is process-wide, whereas PowerShell can have many "current" directories, each in their own runspace/thread.

**Comment by 237dmitry** [comment]
`System.IO.File]::WriteAllBytes("$PWD\some_valid_folder_in_dir2\file", $Byte)`
Use fullname path.

**Comment by street-jimmy** [comment]
Thanks for the detailed response!
