### ISSUE TITLE
? and % with no params should map to ?{ $_ } and %{ $_ }

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16705]
### Summary of the new feature / enhancement

I think it would be beautiful to be able to do this:

```powershell
'foo','','bar',$null,'baz',$true | ?
# foo,bar,baz,True

# or

(1,2),(3,4),(5,6) | %
# 1,2,3,4,5,6
```

### Proposed technical implementation details (optional)

Make `Where-Ojbect` and `ForEeach-Object` run `{ $_ }` when zero parameters are passed.

**Comment by jhoneill** [comment]
To what end ?  What you saying is you want typing  `| ?`  or `| %`   to do the same as not typing them, so why type them? 

btw `? {$_}`  will omit anything which converts to boolean false ($null, $false, "" , 0 , @() )  you may mean ? {$true}

**Comment by vexx32** [comment]
The latter is identical to piping to `Write-Output` as well, I think, so you could just alias that if you wanted to.

The former case has something of a use in that it acts as a filter for false-y values. `$array | where {$_}` filters out all the null or false-y values. I would agree that one is desirable, but I don't think there's really much use for the latter.

**Comment by JamesWTruher** [comment]
WG response: PowerShell aliases are not macro substitutions, but simple token substitutions. it's really beyond the design to this.

**Comment by rkitover** [comment]
This isn't about the alias, this is about `Where-Object` having this behavior with zero arguments.

**Comment by jcotton42** [comment]
> WG response: PowerShell aliases are not macro substitutions, but simple token substitutions. it's really beyond the design to this.

They're referring to changing the behavior of `Where-Object` and `ForEach-Object` when not given scriptblocks, they just referred to them by their aliases instead of by their full names.

**Comment by jhoneill** [comment]
@JamesWTruher  One way to do what he wants would be through `$PSDefaultParameterValues` but they don't seem to work if the value in the dictionary is a script block (it seems to be converted to a string before being passed in).  If that were fixed this would be trivial. (Not that I can understand why anyone wants it).

**Comment by jcotton42** [comment]
> @JamesWTruher One way to do what he wants would be through `$PSDefaultParameterValues` but they don't seem to work if the value in the dictionary is a script block (it seems to be converted to a string before being passed in). If that were fixed this would be trivial. (Not that I can understand why anyone wants it).

What's actually happening is the script block is being run, you can get around that by just "doubling up" the script block (i.e. `{{ script here }}` instead of `{ script here }`)

**Comment by rkeithhill** [comment]
@jcotton42 Nice!
```powershell
PS> $PSDefaultParameterValues['Where-Object:FilterScript'] = {{$_}}

PS> "a","","b","","c" | ?
a
b
c
```

**Comment by SeeminglyScience** [comment]
I've definitely written quite a few `Where-Object { $_ }` statements to filter out falsy. It'd be a nice non-breaking change to allow `Where-Object` by itself to do that.

That said, I'm not sure how feasible it is. Maybe it's simple, maybe it's impossible. That command is already pushed pretty close to the brink with it's parameter binding complexity.

**Comment by jcotton42** [comment]
Also, since I mentioned it, it's worth noting that other, already bound parameters, are available for reference in the script block. You can see this if you do

```powershell
$PSDefaultParameterValues['Some-Command:SomeParameter'] = {$Global:blah = Get-Variable}
```

If you look at `$blah` you'll see that the already bound params are available there

**Comment by jhoneill** [comment]
@jcotton42  Yup that works **thank you** 


@rkitover  / @SeeminglyScience  put either or both of these lines in your profile and you're good to go ... 
```PowerShell
$PSDefaultParameterValues.Add('ForEach-Object:Process',   {{$_}}   )
$PSDefaultParameterValues.Add('Where-Object:FilterScript',{{$true}})  # or $_ instead of $true
```

**Comment by rkeithhill** [comment]
Yeah, 32 different parameter sets on `Where-Object` is pretty wild.  I've used `Where-Object {$_}` before to filter out empty lines of text.  However, what I really want is a way to access the pipeline object instead of a property with the Where-Object parametersets e.g. ` ... | Where-Object PSItem -GT 0`  or `... | Where-Object _ -match '^\t\w'`

**Comment by SeeminglyScience** [comment]
> Yeah, 32 different parameter sets on `Where-Object` is pretty wild. I've used `Where-Object {$_}` before to filter out empty lines of text. However, what I really want is a way to access the pipeline object instead of a property with the Where-Object parametersets e.g. ` ... | Where-Object PSItem -GT 0` or `... | Where-Object _ -match '^\t\w'`

Or even just `Where-Object -gt 0` would be amazing though a lot harder to implement (maybe). I do see a lot of folks trying to do that exact syntax in the discord from time to time.

**Comment by rkitover** [comment]
> However, what I really want is a way to access the pipeline object instead of a property with the Where-Object parametersets e.g. ` ... | Where-Object PSItem -GT 0` or `... | Where-Object _ -match '^\t\w'`

Me too, but I was told that that has already been proposed and I didn't want to open a duplicate. I'll dig in the issues and see what happened there.

**Comment by rkitover** [comment]
> Where-Object _ -match '^\t\w'

That may be the easiest way to do it without further straining the parameter binder, we'd just have to assume no one has properties called `_`, which would probably be reasonable.

I think that reads better too, and still looks nicer than the scriptblock version.

**Comment by jhoneill** [comment]
> > Where-Object _ -match '^\t\w'
> 
> That may be the easiest way to do it without further straining the parameter binder, we'd just have to assume no one has properties called `_`, which would probably be reasonable.
> 
> I think that reads better too, and still looks nicer than the scriptblock version.

Actually . would work for this, since it parses OK (based on a very quick test: * doesn't work, ? does). It's technically possible to create a property named "."  but I've never seen it done in real world use
