### ISSUE TITLE
cmdlet Get-Clipboard like in Windows PowerShell

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#16702]
### Summary of the new feature / enhancement

Add `Format` parameter to `Get-Clipboard` cmdlet. Like it done in Windows PowerShell. For example:
```
$img = Get-Clipboard -Format Image
$img.Save("$PWD\file.png")
```
I am understanding that this can be done using .Net methods, but `Format` parameter make life better.
`TextFormatData` makes too.

### Proposed technical implementation details (optional)

```
Get-Clipboard
    -Format Text, FileDropList, Image, Audio                              Named
    -TextFormatData Text, UnicodeText, Rtf, Html, CommaSeparatedValue     Named
```

**Comment by iSazonov** [comment]
Dup #12290
