### ISSUE TITLE
Progress bar rendering doesn't play well with native command output

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#16716]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following script in Windows Terminal:

```
& {
    for ($i = 5; $i -gt 0; $i–-) {
        Write-Progress -Activity "Launching rocket" -SecondsRemaining $i
        Start-Sleep 1
        dotnet --version
    }
    
    Write-Host "Output messed up!" -Fore Yellow
}
```

### Expected behavior

```console
The output from PowerShell and native command gets displayed in order.
```

### Actual behavior

```console
The output is messed up.

I believe it's because we save the cursor position before doing progress rendering, then the cursor position was changed by the native command, but when completing the progress rendering, we reset the cursor position back to the saved value.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Screen GIF with 'Minimal' view:

![Animation](https://user-images.githubusercontent.com/127450/148624129-f8df5424-4363-4257-8755-107b64d26f8e.gif)

Screen GIF with 'Classic' view:

![Animation2](https://user-images.githubusercontent.com/127450/148624147-0769bb50-581c-411f-a501-c5436f308912.gif)

**Comment by 237dmitry** [comment]
I think that the native apps create its own subshell and progress bar redraw their output. This example has to work:
```
& {
     for ($i = 5; $i -gt 0; $i–-) {
         Write-Progress -Activity "Launching rocket" -SecondsRemaining $i
         Start-Sleep 1
         Write-Host $(cmd /c ver)
     }
     Write-Host "Output messed up!" -Fore Yellow
 }
```
