### ISSUE TITLE
When execute Can't execute

### ISSUE THREAD

**Issue by iwxfer** [PowerShell/PowerShell#16715]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello, I just downloaded last version PowerShell-7.2.1-win-arm64 from github and when executing a message: 

### Expected behavior

```console
Open PS
```

### Actual behavior

```console
Shows message
```

### Environment data

```powershell
I can't open PS, I have a 64 bit PC
```

### Visuals

![2022-01-07 11-56-11 No se puede ejecutar esta aplicación en el equipo](https://user-images.githubusercontent.com/642371/148579330-ca8ee3ba-c0d2-47bb-9521-2458a6791caa.png)

**Comment by vexx32** [comment]
`arm64` is generally not the architecture of most 64-bit PCs. You probably want the `win-x64` version instead. 🙂
