### ISSUE TITLE
Test-Path function doesn't make distinction between a file and a folder of the same name

### ISSUE THREAD

**Issue by MimiKLM** [PowerShell/PowerShell#16713]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. create an item with `New-Item -Path $env:USERPROFILE -Item PS #this is a file`
2. Test the path with the `Test-Path -Path "$env:USERPROFILE\PS" -PathType Container #checking for folder of name PS`
3. It returns true when is expected false, as PS folder does not exist. Just the PS file exists, but not a folder

### Expected behavior

```console
false
```

### Actual behavior

```console
true
```

### Error details

```console
no error, just false output
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
> `New-Item -Path $env:USERPROFILE -Item PS #this is a file`

This does not work for me, it gives "the type is not a known type for the file system. Only "file","directory", or "symboliclink" can be specified. (`-Item` maps to the `-ItemType` parameter, so that should be set to `-ItemType File` for this test, I think?)

If I fix that command and run:

```ps1
New-Item -Path $env:USERPROFILE -ItemType File -Name PS
```

and then subsequently use Test-Path to check for a container at that location, I get a false result back:

```ps1
PS> Test-Path $env:USERPROFILE\PS -PathType Container
False
```

**Comment by kasini3000** [comment]
Yes, I cannot reproduce the problem. I have the same situation as vexx32.
Test environment ps51, ps7.3 pr1

**Comment by iRon7** [comment]
What is in `$env:USERPROFILE`? any special characters? What happens with `-LiteralPath`?
