### ISSUE TITLE
Install worked but pwsh did not run 

### ISSUE THREAD

**Issue by BobFrankston** [PowerShell/PowerShell#16722]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I copied the in installation instructions to a shell file and it succeeded but when I tried to run on my pi4 with  64 Raspberry OS it I got

```
pi@pi4c:~/powershell $ ./pwsh 
bash: ./pwsh: No such file or directory
pi@pi4c:~/powershell $ ls -la pwsh*
-rwxr-xr-x 1 pi pi  60488 Dec  8 16:04 pwsh
-rw-r--r-- 1 pi pi 131241 Dec  8 16:05 pwsh.deps.json
-rw-r--r-- 1 pi pi 155648 Dec  8 16:05 pwsh.dll
-rw-r--r-- 1 pi pi   1732 Dec  8 16:05 pwsh.ni.r2rmap
-rw-r--r-- 1 pi pi    478 Dec  8 16:04 pwsh.runtimeconfig.json
-rw-r--r-- 1 pi pi   8682 Dec  8 16:04 pwsh.xml
pi@pi4c:~/powershell $ 
```
The script file

```
# Install libunwind8 and libssl1.0
# Regex is used to ensure that we do not install libssl1.0-dev, as it is a variant that is not required
sudo apt-get install '^libssl1.0.[0-9]$' libunwind8 -y

###################################
# Download and extract PowerShell

# Grab the latest tar.gz
wget https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-7.2.1-linux-arm32.tar.gz

# Make folder to put powershell
mkdir ~/powershell

# Unpack the tar.gz file
tar -xvf ./powershell-7.2.1-linux-arm32.tar.gz -C ~/powershell

# Start PowerShell
~/powershell/pwsh
```
OS Info

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Expected behavior

```console
powershell
```

### Actual behavior

```console
pi@pi4c:~/powershell $ ./pwsh 
bash: ./pwsh: No such file or directory
```
```


### Error details

_No response_

### Environment data

```powershell
No powershell
```

### Visuals

See shell script above which seemed to work just fine -- I do have a powershell directory

**Comment by iSazonov** [comment]
> wget https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/powershell-7.2.1-linux-arm32.tar.gz

Why do you install ARM32 if your OS is ARM64?

**Comment by BobFrankston** [comment]
Thanks. I guess this is a case where the section on "Install on Raspberry Pi OS" didn't even entertain the idea of a 64-bit version since it's still in beta. I suggest the script be updated to automatically detect the configuration. 

It works now.

Also lousy diagnostic message but that's on Linux, not Powershell.
