### ISSUE TITLE
Unable to list files of a Volume using GUID - Regression from Windows PowerShell

### ISSUE THREAD

**Issue by Kytech** [PowerShell/PowerShell#16721]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am unable to list the files in a volume that is not assigned a mount point using the volume GUID. Instead, the directory listing of C:\ is provided. This behavior works in Windows PowerShell v5.1, but it does not work in PSCore.

Since the below example is for the ESP Volume, the commands were tested from an administrator terminal for both Windows PowerShell v5.1 for the expected and PSCore (v7.2.1) for the actual behaviors.

This seems to be somewhat related to some of the comments on #11764 though I was never able to set the location to a volume GUID path even in PowerShell 5.1, so this seems like a separate issue.

### Expected behavior

```console
PS> Get-ChildItem -LiteralPath '\\?\Volume{a5a6fecd-ca27-444b-92e1-6f827725274c}\'

    Directory: \\?\Volume{a5a6fecd-ca27-444b-92e1-6f827725274c}

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          1/1/2022   2:32 PM                EFI
-a----        12/28/2021   5:44 PM        1029696 shellx64.efi
```

### Actual behavior

```console
PS> Get-ChildItem -LiteralPath '\\?\Volume{a5a6fecd-ca27-444b-92e1-6f827725274c}\'

    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           11/5/2021  2:10 PM                PerfLogs
d-r--          12/18/2021  9:10 PM                Program Files
d-r--            1/4/2022 11:31 PM                Program Files (x86)
d-r--          12/16/2021  3:49 PM                Users
d----          12/25/2021 11:14 PM                Windows
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Dup #15872
