### ISSUE TITLE
Uninstall-Module - Add Scope Parameter

### ISSUE THREAD

**Issue by weyCC81** [PowerShell/PowerShell#16729]
### Summary of the new feature / enhancement

**Situation**
`Get-Module -Name MicrosoftTeams -ListAvailable`
> Directory: C:\Users\[Username]\OneDrive - [Company]\Dokumente\WindowsPowerShell\Modules
> ModuleType Version    Name                                                                                   
> ---------- -------    ----                                                                                    
> Script     2.6.0      MicrosoftTeams                      
> Binary     2.3.2      MicrosoftTeams                      
> 
>Directory: C:\Program Files\WindowsPowerShell\Modules
> ModuleType Version    Name 
> ---------- -------    ----                                                                                    
> Script     3.0.0      MicrosoftTeams
> Binary     2.3.2      MicrosoftTeams

**Problem**
You can install Modules in different Scopes for example:
`Install-Module -Name MicrosoftTeams -RequiredVersion 2.3.2-preview -AllowPrerelease -Scope CurrentUser`

If you try to uninstall i am not able to uninstall the CurrentUser Version's with the Uninstall-Module:
`Uninstall-Module -Name MicrosoftTeams -RequiredVersion 2.6.0`
> PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'MicrosoftTeams'.

`Uninstall-Module -Name MicrosoftTeams -RequiredVersion 2.3.2 -AllowPrerelease`
> PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'MicrosoftTeams'

`Uninstall-Module -Name MicrosoftTeams`
> PackageManagement\Uninstall-Package : You cannot uninstall the module 'MicrosoftTeams' from 'C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.0.0'

`Uninstall-Module -Name MicrosoftTeams -AllVersions`
> PackageManagement\Uninstall-Package : You cannot uninstall the module 'MicrosoftTeams' from 'C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\3.0.0'

### Proposed technical implementation details (optional)

Add Scope Parameter to Uninstall-Module

`Uninstall-Module -Name MicrosoftTeams -RequiredVersion 2.6.0 -Scope CurrentUser`
`Uninstall-Module -Name MicrosoftTeams -RequiredVersion 2.3.2 -AllowPrerelease -Scope CurrentUser`

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please open new request in PowerShellGet repository.

**Comment by kilasuit** [comment]
@iSazonov can you not transfer this issue across or does that only work if you are also a maintainer in that repo too?

**Comment by iSazonov** [comment]
@kilasuit No, I haven't permissions. You can open new issue there yourself if you see the need.

**Comment by weyCC81** [comment]
Can be found here already:
https://github.com/PowerShell/PowerShellGet/issues/309
https://github.com/PowerShell/PowerShellGet/issues/595

**Comment by schittli** [comment]
Yet another Microsoft disgrace: they make so many billions from us customers that it's hard to count, but such simple and obvious feature requests are ignored for years.

**Comment by LordDouglasTheMighty** [comment]
I found this discussion due to my own annoyance, ended up figuring it out as much as is possible. Annoying that Install-Module has a -scope parameter but Uninstall-Module does not. The workaround is to run Powershell in Administrator mode to uninstall from AllUsers scope and just run as the user (non-admin mode) to uninstall from the user profile. And yes, I back the fact that -Scope should be added as a parameter to Uninstall-Module.
