### ISSUE TITLE
Add `IList` interface to the Range Operator

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#16725]
### Summary of the new feature / enhancement

Implementing the `IList` interface to the [Range Operator](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#range-operator-) would (presumably) require a easier syntax in case it is used for a (non-pipeline) parameter.

```PowerShell
$Table = @'
1,6,6,2,9,4
8,4,3,9,5,7
1,0,9,5,4,0
'@
```

Currently it is required to used the [Array subexpression operator `@( )`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#array-subexpression-operator--) to use a range as argument:

```PowerShell
ConvertFrom-Csv $Table -Header @('a'..'f') 
```

With the `IList` interface implemented, I expect the syntax to be simplified to:
```PowerShell
ConvertFrom-Csv $Table -Header 'a'..'f'
```

**Comment by iRon7** [comment]
Actually, I think my suggested lack of the `IList` interface  implementation suggestion is incorrect as the [grouping operator](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#grouping-operator--) also works:
```PowerShell
ConvertFrom-Csv $Table -Header ('a'..'f')
```
It is probably a syntax issue (also reading the related error closely):

> ConvertFrom-Csv: Cannot bind parameter 'Delimiter'. Cannot convert value "..f" to type "System.Char". Error: "String must be exactly one character long.

Anyhow, it would be nice it the range operator could be used without any parenthesis in an argument as syntaxial sugar.

**Comment by jhoneill** [comment]
It's more to do with how the command line parses  operators  
`ConvertFrom-Csv $Table -Header (' @('a','b','c') + @('d','e','f') ` 
Will fail because the + operator morphs into a value. You can do this 
`convertFrom-Csv $Table -Header .., ++ , -f, 2+3, 5..6 `    
 you'll get silly headings but it's valid.

**Comment by iRon7** [comment]
`Resolution answered`
