### ISSUE TITLE
out-file producing weird characters

### ISSUE THREAD

**Issue by computechrr** [PowerShell/PowerShell#16730]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using out-file with or without specifying any encoding the file has some weird characters at the beginning of the file

[32;1m NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName[0m
[32;1m ------    -----      -----     ------      --  -- -----------[0m

I've tried this on different computers all using ps 7.2.1, windows 10, server 2016 etc. When using the same get-process |out-file with powershell 5.1 it works as expected without those characters.  

### Expected behavior

```console
NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
```

### Actual behavior

```console
[32;1m NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName[0m
```

### Environment data

```powershell
7.2.1
```

### Visuals

![image](https://user-images.githubusercontent.com/43617080/148960349-6c269f09-e2f2-4e7e-b607-876cfd3b06e3.png)

**Comment by 237dmitry** [comment]
```powershell
& {                                
 $PSStyle.OutputRendering = 'Host'    # or PlainText
 Get-Process | Out-File gps.txt
 $PSStyle.OutputRendering  = 'Ansi'
 }

```

**Comment by computechrr** [comment]
I tried something else
Get-process |write-output > process.txt
It will also add the same characters to the output file as well.

Ted Reichelt

**Comment by computechrr** [comment]
That produced a clean output in the file

ted

**Comment by LeeHolmes** [comment]
This is a pretty major breaking change. This doesn't happen with other ANSI shells, such as Bash:

![image](https://user-images.githubusercontent.com/11475352/151269330-09d6e1aa-370e-4d64-99a6-d9cf618ea642.png)

**Comment by SteveL-MSFT** [comment]
This is because `ls` itself knows when it is being redirected and omits the VT.  PS7.2 handles this at the shell level due to things like formatting which happens within the PS engine.  If you run `ls -G > out.txt` within PS7.2, you'll still see that VT is omitted because `ls` decided to omit it.

I think the way to address this issue while addressing https://github.com/PowerShell/Announcements/issues/28 is to change the current regex for removing VT to have a fixed list of known VT codes that will be removed.  This would still need to go through a security review to ensure spoofing doesn't happen.

**Comment by gwojan** [comment]
@SteveL-MSFT this is particularly annoying when `$PSStyle` is doing full filename coloring and piping the output to `clip.exe`. It seems like I'm doing that with increasing frequency and pasting into Teams... 😔

**Comment by JohnMarkHowell** [comment]
Still happening in v7.4.2

Any suggestions other than always using a replace filter before the `Out-File` ?

**Comment by JasonDTX** [comment]
You may find some success using ascii as the default encoding for the entire session.

`$OutputEncoding = [Text.Encoding]::ASCII`

Sorry if this was already tried, it helped with my out-file encoding in pwsh 7

**Comment by JohnMarkHowell** [comment]
@JasonDTX - I just tried that and it did not alter the output (meaning the output still included escape characters).

**Comment by JohnMarkHowell** [comment]
@SteveL-MSFT, @PaulHigin - This still happens in 7.2.5 on Windows 11

**Comment by JasonDTX** [comment]
@JohnMarkHowell Sorry, I pasted an older attempt! Too many tabs open. This one is the one that fixed me.
`$PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText`
Out-File takes the format of the input object, so this strips any escape sequences out of my psobjects.

**Comment by JohnMarkHowell** [comment]
That is awesome, @JasonDTX ! That fixed it! Thank you!!!!!!!
