### ISSUE TITLE
UnixMode + UnixStat.Mode

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#16737]
### Summary of the new feature / enhancement

Please add:
 - the ability to display access rights in octal notation.
 - displaying  SGID, SUID and sticky bit in UnixMode

### Proposed technical implementation details (optional)

For example:
```
Get-Item ./1.ps1

    Directory: /home/user/Desktop

UnixMode      Octal  User   Group      LastWriteTime       Size Name
--------      -----  ----   -----      -------------       ---- ----
-rw-r--r-T     1644  user    user   11.01.2022 22:34        579 1.ps1

```

And the question -- where can I see the enum of unix access rights? Like this:
```
[flags()] enum access
{
    ExecuteAll   = 1
    WriteAll     = 2
    ReadAll      = 4
    ExecuteGroup = 8
    WriteGroup   = 16
    ReadGroup    = 32
    ExecuteOwner = 64
    WriteOwner   = 128
    ReadOwner    = 256
    StickyBit    = 512
    SGID         = 1024
    SUID         = 2048
  #              = 4096    # ???
    SymLink      = 8192    # And character special file ???
    Directory    = 16384
    File         = 32768
}
```

**Comment by jhoneill** [comment]
`get-typedata system.io.fileinfo | % members`      
shows that `Mode, ModeWithoutHardLink, VersionInfo, BaseName, Target, LinkType, NameString, LengthString, LastWriteTimeString` are added from the types information for **fileinfo** objects and  (on linux)    
 `get-typedata system.io.fileSysteminfo | % members`    
 shows types information adds script properties for 'UnixMode, User, Group, Size' to **fileSysteminfo** objects  

The script in `UnixMode` checks for the presence of `UnixStat` and  uses its `.GetModeString` Method to return the Unix mode as a formatted string.  (User, Group and Size also use `UnixStat`)

if I do something like  `$d = Get-Item ./PowerShell `  
`$d.GetFiles`  returns items **without** `UnixStat` members, (which is what the types info suggests) but `$d | gci` returns items **with** `UnixStat` - which implies it is added by `Get-Item`  / `Get-ChildItem` . It looks to be a "helper" designed to hide all the internals you want - exposing them doesn't seem to be a very difficult thing to do but I haven't searched for the code that does the work.

**Comment by 237dmitry** [comment]
Thank you. But I don't understand where can I look for `System.Enum` (like `System.IO.FileAttributes`) of linux access rights? In order to use net-methods (they are faster then scripts and _no need to assemble my own bike_) For example:
```
(gi ./Desktop/).UnixStat.Mode   # 16877
(gi ./Desktop/).UnixMode        # drwxr-xr-x
```
`16877` is:
```
d_rwx_r-x_r-x

d: 16384  # Directory

r: 256    # owner can read 
w: 128    # owner can write
x: 64     # owner can execute

r: 32     # group can read
w: 0      # group can not write
x: 8      # group can execute

r: 4      # other can read
w: 0      # other can not write
x: 1      # other can execute


16384 + 256 + 128 + 64 + 32 + 8 + 4 + 1 = 16877
```

**Comment by iSazonov** [comment]
P/Invoke read Unix `stat` struct and `mode_t` field of the struct is the mode you ask. You can find more info in https://man7.org/linux/man-pages/man0/sys_stat.h.0p.html

**Comment by 237dmitry** [comment]
From where `UnixStat.Mode` does get values? Is this an enum or not?

**Comment by iSazonov** [comment]
> From where `UnixStat.Mode` does get values? Is this an enum or not?

It copies mode_t from stat struct. It is `int` - see reference to docs above.

**Comment by 237dmitry** [comment]
I wanted to do it the right way, I did it as always, with the help of crutches (`/usr/bin/stat`).
![1](https://user-images.githubusercontent.com/78153320/149342859-440adc7a-7666-416d-80db-f5751bc38074.png)

**Comment by iSazonov** [comment]
You can also look https://github.com/PowerShell/PowerShell-Native where Unix P/Invokes implemented.

**Comment by kasini3000** [comment]
1 powershell is currently not perfect

2 You can judge the SGID, SUID, sticky attributes by the following commands:
(Get-Item './smy Matrix Digital Rain.ps1').Unixstat.IsSetUid
(Get-Item './smy Matrix Digital Rain.ps1').Unixstat.IsSetGid
(Get-Item './smy Matrix Digital Rain.ps1').Unixstat.IsSticky

3 You can get the string with the following commands and calculate it yourself:
  (Get-Item './smy Matrix Digital Rain.ps1').UnixMode[-3]
r

**Comment by 237dmitry** [comment]
> 3 You can get the string with the following commands and calculate it yourself

The variant, thanks. Just I don't want to parse strings to get result. Kind of this:
```
& {                                                                               
 -join ('drwxr-xr-x' -replace '[ldc]' `
                     -replace '-','0' `
                     -replace 'r','4' `
                     -replace 'w','2' `
                     -replace 'x','1' `                                 
                     -split '(?<=...)(?=(?:...)+$)' |                             
           Foreach-Object { [Linq.Enumerable]::Sum([int[]][string[]][char[]] $_) }
       )
 }

# 755
```

**Comment by 237dmitry** [comment]
I noticed that if `SUID` and `SGID` are in the file at the same time, then `UnixStat.IsSetUid` and `UnixStat.IsSetGuid` both show `False` but each of them must show `True`.

**Comment by jhoneill** [comment]
A shorter conversion :-) 

```PowerShell 
 [convert]::ToString([convert]::ToInt32(('drwxr-xr-x' -replace '[rwx]','1' -replace "[^1]","0"),2),8)

```

**Comment by 237dmitry** [comment]
Thanks to all.
