### ISSUE TITLE
Publish-Module should work in Core edition

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#1673]
I developed module [MarkdownLinkCheck](https://github.com/vors/MarkdownLinkCheck) fully on OS X. To my great surprise, I didn't encounter any cross-platform problems when I tested the result on inbox Windows PS version. 
It's particularly remarkable, because there is a binary part (netstandard assembly) in the package, but it works fine on full framework.

Today I tried to publish the module to PSGallery and it turns out to be **the only place** in the whole development cycle that required me to hop back to a windows machine.

Here is the result that I got on OS X:

```
PS /Users/vors/dev/MarkdownLinkCheck> Publish-Module -Name MarkdownLinkCheck -Verbose -RequiredVersion 0.1.0                                 
Publish-Module : Publish-Module is not supported on Nano Server and PowerShellCore.
At line:1 char:1
+ Publish-Module -Name MarkdownLinkCheck -Verbose -RequiredVersion 0.1. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme....PSScriptCmdlet:PSScriptCmdlet) [Publish-Module], InvalidOperationExcept 
   ion
    + FullyQualifiedErrorId : PublishModuleIsNotSupportedOnNanoServer,Publish-Module
```

cc @raghushantha @quoctruong @KrishnaV-MSFT

**Comment by SteveL-MSFT** [comment]
This issue was moved to PowerShell/PowerShellGet#26
