### ISSUE TITLE
Set-StrictMode -Version should support "off" as a parameter

### ISSUE THREAD

**Issue by Thomas-Yu** [PowerShell/PowerShell#16736]
### Summary of the new feature / enhancement

Currently, Set-StrictMode -Version accepts "latest" to indicate the most recent version of StrictMode. It would be beneficial to also accept "off" and remove the Set-StrictMode -Off option. The "off" option would turn StrictMode to version 0.0

Usage: Set-StrictMode -Version off

### Proposed technical implementation details (optional)

Invoke-Command -StrictMode allows "off" as a parameter.
Refer to this pull request https://github.com/PowerShell/PowerShell/pull/16545#discussion_r782709242

**Comment by daxian-dbw** [comment]
IMHO, I think `off` may not be a suitable value for `Set-StrictMode -Version`. `-Version latest` means the latest version, but `-Version off` doesn't seem to make sense that naturally. The parameter `-StrictMode` in `Invoke-Command` is different from `-Version`, and thus `-StrictMode off` reads much more naturally than `-Version off`.

**Comment by iSazonov** [comment]
> -StrictMode off

This duplicates cmdlet name. Maybe `Set-StrictMode -Off`.

**Comment by daxian-dbw** [comment]
Closing this issue given that the corresponding experimental feature is being removed: https://github.com/PowerShell/PowerShell/pull/18040
