### ISSUE TITLE
[console]::BufferHeight now gives wrong info in pwsh standalone, but correct in WT

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#16732]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

There are different behavior of console size when running in `pwsh` from desktop vs. using it with `Windows Terminal`.

Try running the following under each environment:
```powershell
"$([console]::BufferWidth) $([console]::BufferHeight)"

# From pwsh.exe (standalone) where I have used 9001 as buffer height.
120 9001

# From Windows Terminal (default, whatever that is.)
160 50

```

### Expected behavior

```console
"$([console]::BufferWidth) $([console]::BufferHeight)"
160 50
```

### Actual behavior

```console
"$([console]::BufferWidth) $([console]::BufferHeight)"
120 9001
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by eabase** [comment]
It seem that perhaps they are both correct, but then I must ask why (and how) WT is setting:  
` $([console]::BufferHeight) = $([console]::WindowHeight)`?

**Comment by vexx32** [comment]
Yeah I don't know that pwsh is doing anything wrong here. There's a deliberate difference between BufferHeight and WindowHeight -- the former is the size of the scrollback buffer, the latter is the actual rendered window size.

**Comment by jhoneill** [comment]
On the plus side, if you zoom with the scroll wheel WT knows the screen size has changed. The old-style console host doesn't (until you resize the window forcing a recalculation).  I spent a happy few minutes trying to work out why text was wrapping too soon if I ran powerShell.exe but not if I loaded pwsh or powerShell in WT.

**Comment by eabase** [comment]
Not sure how I can help here. Is this a WT or pwsh issue?

*Windows Terminal* is using different settings that I do not have access to (or do not know where they are). In pwsh at least I know where to find most settings in the registry, but for WT, there are literally hundreds of different paths to things related.

**Comment by SeeminglyScience** [comment]
> Not sure how I can help here. Is this a WT or pwsh issue?

You could call it a WT issue but it's more a conpty thing and it's by design. [microsoft/terminal#8312 (comment)](https://github.com/microsoft/terminal/issues/8312#issuecomment-731888271) goes into a bit more detail. Here's the relevant quote:

> We made a critical mistake approximately forty years ago (😁) and made the entire buffer (120x9001 or whatever the user requests) available to a console application. There's the viewport (120x30) and the buffer (120x9001), both of which the application can control. It can draw outside of its bounds, and it can know exactly where _in the buffer_ it's printing. Pretty cool!
> 
> Applications that have some amount of buffer awareness will eventually reach a point where they're on line 9001 and _oops_ the line under 9001 is **also** line 9001 (because the old line 0 got destroyed and shifted off the top of the buffer.) This bit is the crux of your issue 😄. We call it "circling."
> 
> Terminals have never supported that viewport/buffer split. They've only ever offered viewport control, and the buffer was an artifact owned by the terminal itself (because, like, it might have been a line printer or a serial device or a modem . . . instead of a terminal emulator application). That puts the terminal in charge of scrollback, and scrollback is stored in a place where the client application can't see (or change) it.
> 
> To account for this difference, ConPTY mode restricts the buffer size to _match the viewport size_. This restriction applies _regardless_ of `ENABLE_VIRTUAL_TERMINAL_PROCESSING` (which is a feature of conhost, even without Terminal involved.)
