### ISSUE TITLE
Support double-dash --paramname syntax for named parameters.

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16749]
### Summary of the new feature / enhancement

It would be nice to be able to execute commands like:

```powershell
rm --rec --force ~/somedir
```

the only difference in this command vs. one that currently works, is that parameter names start with a double dash `--` instead of a single dash `-`.

In this case, this same command is compatible with Linux (but not macOS unfortunately.)

Related: #6397

Here is one possible (slightly contrived) use-case in case you are wondering why anyone would want this:

```powershell
$servers = 'winserver','linuxserver','otherlinuxserver'

foreach ($server in $servers) {
    ssh $server -- rm --rec --force ~/some/path
    ...
}
```

**Comment by rkeithhill** [comment]
This already works:
```
mkdir -p foo/bar/baz
/bin/rm --recursive --force ./foo/
```
Or are you on Windows and are using `rm` as an alias for `Get-ChildItem`?  If it's the latter, you might want to make that more clear in your request.

Assuming it's the latter, what I'd would prefer is that `--` for a PowerShell parameter, require the full parameter name and not "match" based on the number of chars provided.  Partial matching becomes problematic as cmdlets add new parameter names.  I might get away with `Get-SomeNoun -f` for `-force` until later on when someone adds a `-Filter` parameter to the cmdlet. At that point, `Get-SomeNoun -f` is ambiguous and will error.  I wouldn't mind seeing `Get-SomeNoun --Force` where `Get-SomeNoun --f` would fail right away because there is no parameter named `F`.

**Comment by rkitover** [comment]
> Or are you on Windows and are using `rm` as an alias for `Remove-Item`? If it's the latter, you might want to make that more clear in your request.

Yeah I should have made that more clear, my apologies.

The reason I chose that particular Windows alias, is because the scenario I'm describing is where you want to run the same command on Linux and Windows, e.g. via `ssh`.

> Assuming it's the latter, what I'd would prefer is that `--` for a PowerShell parameter, require the full parameter name and not "match" based on the number of chars provided. Partial matching becomes problematic as cmdlets add new parameter names. I might get away with `Get-SomeNoun -f` for `-force` until later on when someone adds a `-Filter` parameter to the cmdlet. At that point, `Get-SomeNoun -f` is ambiguous and will error. I wouldn't mind seeing `Get-SomeNoun --Force` where `Get-SomeNoun --f` would fail right away because there is no parameter named `F`.

I think you're right, and this is a better way to go.

But in that case, would you support full parameter alias names as well? The equivalent to the `Remove-Item` `-Recurse` parameter for GNU coreutils `rm` is `--recursive`. So if `-Recursive` was an explicit parameter alias for `-Recurse` for `Remove-Item`, my usecase would still work with this command:

```bash
rm --recursive --force ~/some/path
```
.

**Comment by iSazonov** [comment]
> The equivalent to the Remove-Item -Recurse parameter for GNU coreutils rm is --recursive.

If you ask the package owners to replace `--recursive` with `-recursive` what answer do you expect? :-)

Here you can get only one obvious answer - it is how PowerShell language was designed for many years ago, changing this would be huge breaking change.

**Comment by rkitover** [comment]
> If you ask the package owners to replace `--recursive` with `-recursive` what answer do you expect? :-)

That's not what I meant, here we are talking about full names for parameters, and parameters can have explicit aliases, see "Alias attribute" here:

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2

**Comment by rkitover** [comment]
Some aliases you are using all the time: `-ea` for `-ErrorAction`, or `-ov` for `-OutVariable`.

**Comment by iSazonov** [comment]
Every language has rules that form the essence of a language. It makes no sense to turn C++ into C#, C# into Java or PowerShell into Bash, just as Windows into Linux and vice versa - each has its purpose and its benefits in a certain area where it should be used.

As for aliases, I advise you to forget about them. Every time somebody start discussing them, it turns into a pointless battle.
Aliases mattered in the days of PS 3.0, when there were 10 modules and 20 cmdlets. Now on Windows there are hundreds of OOB modules at once and already thousands of cmdlets. In this situation, aliases become an evil which must be got rid of.

**Comment by rkitover** [comment]
I really don't see the harm in having a `-Recursive` alias for `-Recurse` as parameter aliases are already extensively used. This is very unlikely to cause any confusion.

This has nothing to do with `bash` by the way, `--recursive` is a non-standard parameter for the external GNU coreutils `rm` command.

But that's a separate issue anyway, this one is about supporting a double dash `--Param` instead of only a single dash `-Param` syntax.

My question was, if the `--Param` syntax is implemented for full parameter names only, would any explicit aliases also be supported.

**Comment by 237dmitry** [comment]
> My question was, if the --Param syntax is implemented for full parameter names only, would any explicit aliases also be supported.

Everything should have some practical meaning. It's not for beauty that bash and other command shells use double or single dashes to indicate parameters. This is a syntax element that allows you to either use the full names of parameters or their abbreviations, which can be grouped into one parameter.
```
ls --recursive --size
ls -Rs
```
There is no such possibility in PowerShell, unless you write the binding function yourself, but PowerShell can auto-complete parameters and their values, shorten their spelling until there is a name conflict. In addition the new syntax even if it is as an option will break compatibility with other versions and editions of the shell.

**Comment by delixfe** [comment]
For a test script, I wanted to use double dashes. The reason is, that this script calls `dotnet` and `dotnet` uses double dashes.

A short sample:

```pwsh
# normal dotnet invocation
dotnet test --no-build

# my script invocation should look like so that users do not have to learn a new syntax
./my-test-script.ps1 --no-build

# so I have to use
./my-test-script.ps1 -no-build
```

**Comment by rkitover** [comment]
@delixfe You can still parse `$args` manually instead of using a `Param` block in such cases.

**Comment by delixfe** [comment]
@rkitover Yes, I could do that. However, many of Microsoft's CLI tools support the convention. Thus I would expect PowerShell to support that out of the box.

Some more samples:
- https://github.com/dotnet/command-line-api
- https://microsoft.github.io/coyote/#samples/tasks/bounded-buffer/

**Comment by aetonsi** [comment]
I think that having the possibility to _allow_ the use of double dash parameters _at least_ for my own functions, would be useful..
I don't know, something like
```powershell
[CmdletBinding()]
Param(
  [Parameter(AllowDoubleDash = $true)][string] $something
)
```

**Comment by henrik-jensen** [comment]
> @delixfe You can still parse `$args` manually instead of using a `Param` block in such cases.

@rkitover True, but wouldn't you miss all that lovely auto-completion you get with Param() blocks unless you write your own [auto-completer](https://techcommunity.microsoft.com/t5/itops-talk-blog/autocomplete-in-powershell/ba-p/2604524)?

**Comment by TheOriginalPiff** [comment]
Hi, who wants to do some DeBug bounty hunting??

Will need a small team to document debug/errors.

**Comment by MatejKafka-MSFT** [comment]
@delixfe It's not something I'd recommend for "serious" use, but you can support double-dashed parameters like this:
```powershell
function x {
    param(${-dash-param})

    ${-dash-param}
}

x --dash-param hello
```

The `${...}` syntax treats everything inside the braces as a literal variable name, and allows almost any char.

**Comment by MatejKafka** [comment]
@delixfe It's not something I'd recommend for "serious" use, but you can support double-dashed parameters like this:

```powershell
function x {
    param(${-dash-param})

    ${-dash-param}
}

x --dash-param hello
```

The `${...}` syntax treats everything inside the braces as a literal variable name, and allows almost any char, including `-`.
