### ISSUE TITLE
Powershell Embedded C# code fails when using different "{" convention

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#16753]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a Powershell script with embedded C# code. 

Being used to use the more compact "`function {`" programming convention for curly braces, I modified it by **only** moving `{` from below to next after the function name, like this:
```Powershell
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$CSharpCode = @'
...

public static SafeFileHandle GetConIn() {
    SafeFileHandle fileHandle = CreateFileW("CONIN$", GENERIC_READ, FILE_SHARE_READ, IntPtr.Zero, OPEN_EXISTING, 0, IntPtr.Zero);
    if (fileHandle.IsInvalid)
    {
        throw new System.ComponentModel.Win32Exception();
    }
    return fileHandle;
}
...
}
'@

$NativeMethods = Add-Type -Language CSharp -MemberDefinition $CSharpCode -Name NativeMethods -Namespace Console -PassThru -UsingNamespace 'Microsoft.Win32.SafeHandles' -ErrorAction SilentlyContinue
if (-not $NativeMethods) { throw "Fatal error: Unable to compile the necessary C# code." }

```

The script then fails with: 
```powershell
 $ .\get_console_mode_gist.ps1
Add-Type: C:\Users\xxxx\PowerShell\get_console_mode_gist.ps1:39
Line |
  39 |  … veMethods = Add-Type -Language CSharp -MemberDefinition $CSharpCode - …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot add type. Compilation errors occurred.
```

### Expected behavior

```console
To not make a difference on where I put my `{}`'s.
```

### Actual behavior

```console
Fails due to placement of the `{}`s.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
You example ends with:
```
}
...
}
``
there is an extra parenthesis.

**Comment by eabase** [comment]
@iSazonov  I was not pasting the full code! (Added `...` to show there is more, but completely irrelevant for the issue.

**Comment by eabase** [comment]
First convention fails. Why?

![image](https://user-images.githubusercontent.com/52289379/149635694-fe406eb1-c7bd-4c69-bca8-8917424b8501.png)

**Comment by eabase** [comment]
On further look it seem that compilation fails for **any change at all** to the C# code snippet. 
Can someone explain why that is?

**Comment by eabase** [comment]
ok sorry, I missed the point of `App Domain`'s.
