### ISSUE TITLE
Add advanced function attribute to not "leak" data to the pipeline unless explicitly returned with `return` keyword

### ISSUE THREAD

**Issue by jantari** [PowerShell/PowerShell#16758]
### Summary of the new feature / enhancement

Hi,

the fact that PowerShell functions "automatically" return any and all objects to the pipeline is a surprise factor for many people coming from other languages, but I totally get the intent and sometimes it can be a neat feature.

However, for other functions and usecases it only makes things harder.
It can be a frustrating experience to go through every line of code and ensure with hyper-vigilance that absolutely no cmdlet or method called may clog the pipeline with undesired objects and thus throw off the calling code by displacing the expected object or array of objects. You basically want to prepend `$null = ` to every line to make sure stuff doesn't break.

### Proposed technical implementation details (optional)

I propose a function decorator / attribute such as:

```powershell
function Invoke-MyFunction {
    [CmdletBinding()]
    [PipelineOutput(Mode = 'Explicit')]

    $DATA = Get-ChildItem $env:SystemDrive

    # Oops, I poisoned the pipeline!
    $DATA

    # I know System.Collections.ArrayList is deprecated and I don't use it in actual code,
    # but this is a "classic" example of a method that produces unexpected output for many people
    [System.Collections.ArrayList]::new().add('OH NO NOT AGAIN')

    return @(0, $DATA)
}
```

that the user can add to functions where "leaking" objects to the pipeline is undesired and total control is a better and more robust approach. Only objects explicitly returned to the pipeline with `return` will be sent on, anything "implicitly returned" will be discarded.

Thoughts?

**Comment by iSazonov** [comment]
It seems we already have such issue.

**Comment by MartinGC94** [comment]
See: https://github.com/PowerShell/PowerShell/issues/3669

**Comment by jantari** [comment]
Thanks @MartinGC94
