### ISSUE TITLE
Add -Property "LinuxNumber" to file & folder UnixMode

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#16757]
### Summary of the new feature / enhancement

https://github.com/PowerShell/PowerShell/issues/16737

Currently, the file & folder UnixMode of powershell has no numeric Property, user must write a script to calculate it by himself.

### Proposed technical implementation details (optional)

Property name is "LinuxNumber" or "Number"

Don't forget SGID, SUID and sticky bit, eg:
1777

When listing a directory, Property may not be displayed by default, but are displayed when format-list.

**Comment by 237dmitry** [comment]
And please fix `UnixMode` property. It doesn't always output the correct string. What is the reason I can't understand. Everything is correct in the system directories, but there are errors in the home directory. At the same time, `UnixStat` shows everything correctly.

![ArcoLinux_2022-01-16_17-21-55](https://user-images.githubusercontent.com/78153320/149664136-ba658a8c-ea28-4210-9aa2-840a9d2a4a4c.png)

**Comment by kasini3000** [comment]
i found “UnixFileMode.value__”  in powershell 7.3,
not have this Property on powershell 7.2 on linux.
Who would like to help add "close by pr no" ?

**Comment by kasini3000** [comment]
chmod 600 ./aaa.txt 
Get-Item './aaa.txt').UnixFileMode.value__
384 ----why?

**Comment by 237dmitry** [comment]
> 384 ----why?

Because there is not octal in Net. This is integer:
```
[convert]::ToString(384,8)
600
```

**Comment by kasini3000** [comment]
This kind of intentional incompatibility makes people feel like eating flies.   ：-（
