### ISSUE TITLE
scriptblock issue

### ISSUE THREAD

**Issue by pieterv-icloud-com** [PowerShell/PowerShell#16764]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following script:

```powershell
# Article: https://www.ipswitch.com/blog/understanding-powershell-scriptblocks

[string] $scriptblock = "{ 1 + 1 }"  

# Scriptblock

[scriptblock] $sb = [scriptblock]::Create($scriptblock)

$result = $sb.Invoke(@())

Get-Error

$result

# Call Operator

$result = & $sb

Get-Error

$result

# Invoke-Command

$result = Invoke-Command -ScriptBlock $sb -ArgumentList @() -NoNewScope

Get-Error

$result

# The only way it works

$result = &{ 1 + 1 }

$result

Get-Error
```

Looks like there is no way of loading the scriptblock from a string

### Expected behavior

```console
true 
true 
true 
true
```

### Actual behavior

```console
1 + 1 
1 + 1 
1 + 1 
true
```

### Error details

```console
None
```

### Environment data

```powershell
Powershell Core 7.2.1
```

**Comment by iSazonov** [comment]
> $scriptblock = "{ 1 + 1 }" 

You need use `$scriptblock = "1 + 1" `

**Comment by jborean93** [comment]
Adding to the above, you are essentially doing `&{ { 1 + 1 } }` which is just outputting a scripblock hence why it’s just showing the scriptblock contents.

**Comment by pieterv-icloud-com** [comment]
Thank you
