### ISSUE TITLE
-join problem with 【tab string】

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#16761]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
[string]$a = @'
	$aa = Get-Date -Format 'f'
	$bb = "/root/${aa}.txt"
	touch $bb
'@
$b = $a -split "`n"
$b -join 'zzzz'
#;       touch $bboot/${aa}.txt"'f'

$b.trim() -join 'yyyy' #normal
```
### Expected behavior

```console
$aa = Get-Date -Format 'f'zzzz$bb = "/root/${aa}.txt"zzzztouch $bb
```

### Actual behavior
```console
;       touch $bboot/${aa}.txt"'f'
```

### Environment data

```
powershell 5.1.19041.1320 on win10
PowerShell 7.3.0-preview.1 on win10
```

**Comment by iSazonov** [comment]
I can not reproduce.

**Comment by kasini3000** [comment]
[aaa-v2.ps1.txt](https://github.com/PowerShell/PowerShell/files/7882422/aaa-v2.ps1.txt)
i upload script

**Comment by iSazonov** [comment]
Ah, I see... You have spaces before $aa and the same on follow strings.

**Comment by kasini3000** [comment]
![16761](https://user-images.githubusercontent.com/65390418/149788124-c0fc21ef-3998-4b19-a148-91bde0d7effe.png)
right , powershell engine eat tab when paste console

**Comment by 237dmitry** [comment]
I couldn't paste the text without losing tabs in Windows Terminal, so I pasted it into the standard Windows console.

![Screenshot 2022-01-17 182901](https://user-images.githubusercontent.com/78153320/149797928-173b19a3-6b22-45f1-ac88-9c827a4f9d40.png)

**Comment by kasini3000** [comment]
If you want to reproduce the problem, don't paste, run the [aaa-v2.ps1] I uploaded

**Comment by iSazonov** [comment]
I don't understand what you expect. If the leading tabs is in @'' string literal the tabs is preserved in output - it i how string literals work.

**Comment by 237dmitry** [comment]
> run the [aaa-v2.ps1] I uploaded

Works if `-split '\r?\n'`

**Comment by jhoneill** [comment]
Don't split on \n when the file uses CRLF. It has nothing to do with tabs Otherwise the text is there but the 2nd line prints over the  1st, and line 3 prints over that 

It has been recommend for a long time to use 4 spaces instead of a tab character, and in a lot of cases pasting text with a tab in will act as if you pressed the tab key.

**Comment by kasini3000** [comment]
reproduce the problem by aaa-v2.ps1, on psv5.1 on psv7.x
If you reproduce the problem, the next step, 
I want to know , why does 【tab】 cause the -join problem?
The POINT is 【-split】? is 【-join】?

**Comment by 237dmitry** [comment]
>  why does 【tab】 cause the -join problem?

In your example the problem is not with `-join` but with `-split`.

Here is an example where the text is _already split_ into strings, it remains only to join them.: 
```
("	aaaa", "	bbbb", "	cccc") -join "zzzz"
```

**Comment by jhoneill** [comment]
Here is a hex dump your file with **cr lf**  and tab circled

![image](https://user-images.githubusercontent.com/16209593/149930622-90f0f89d-e2ea-4aac-a141-32a04ce05386.png)

Here it is **split properly.**  I have circled the tabs again. They are treated like any other character.  
![image](https://user-images.githubusercontent.com/16209593/149930885-f0798adb-ce8c-49a7-8505-faea0a7fcceb.png)

Here it is joined  - again tabs marked, and treated like any other character. 
![image](https://user-images.githubusercontent.com/16209593/149931210-49e3cd62-48e1-4fdd-a394-e4b92f69dea2.png)

Here is how it prints, with the joins and the tabs marked:
![image](https://user-images.githubusercontent.com/16209593/149931829-42479e6b-c8da-4324-b01f-ba025bd8204b.png)

Here is the same thing how you were splitting it: I've circled the CR without line feeds
![image](https://user-images.githubusercontent.com/16209593/149932261-e2d063eb-b098-4c16-af81-417c8a505b07.png)

When this prints each line writes over the previous ones
![image](https://user-images.githubusercontent.com/16209593/149932388-c705aa8e-e96c-4a9e-8e16-fa338283f7ea.png)

**Comment by kasini3000** [comment]
Oh, nothing to do with tab, 
it's each CR that overwrites the previous line of strings. 
thanks all.
