### ISSUE TITLE
Parameter completers do not work when prompting for input

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PowerShell#16770]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Write a command supporting an `ArgumentCompleter` on one of the parameters
2. Test the completer by tabbing a parameter value on the command line and note that it works.
3. Invoke the cmdlet without parameters on the command line such that you are prompted for input.
4. Attempt to tab-complete the parameter that supports the completer.

### Expected behavior

```console
PowerShell tab-completes the parameter.
```

### Actual behavior

```console
PowerShell does nothing.
```

### Environment data

```powershell
[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@chriskuech Please share demo script.

**Comment by jhoneill** [comment]
This is expected. 

When a mandatory parameter is omitted the fall back is to use the functionality of Read-Host to prompt for user input.  So it:
* Doesn't treat "," as a separator between items and requires multiple items as separate inputs
* Does process Variables  - `$PsversionTable` will be the literal text starting with a `$` sign not the value of the variable
* Doesn't need quotes where there are spaces and treats quotes and escape characters as literal text. 
* Doesn't have any of the functionality provided by the prompt (and in modern versions by PS Readline).  So  `[ctrl]`+`r`  is not search-history but inserts `^R" 
* Doesn't add to the search history
