### ISSUE TITLE
Redirection of external command output breaks ANSI sequences

### ISSUE THREAD

**Issue by PatTheMav** [PowerShell/PowerShell#16775]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

* Have Git for Windows installed
* Run Powershell 7.21 (either in ConHost or the new Terminal app, bug is reproducible in both)
* Create the following simple function:
```
function Test-Ansi {
    $VerbosePreference = 'Continue'
    Write-Verbose '------ Before ------'
    & "$Env:ProgramFiles\Git\usr\bin\patch.exe" --help > $null
    Write-Verbose '------ After ------'
}
```
* Observe properly formatted coloring for the line before
* Observe line after being uncolored and ANSI sequences instead printed verbatim

# Additional Notes

This behaviour was only observed in PowerShell 7 - running the same function on PowerShell 5 yields the expected behaviour with no breaking changes to the ANSI output. 

It also doesn't make a difference whether the redirection is done via `| Out-Null` or doing a `$null` assignment. Even just redirecting stderr via `2>$null` triggers the issue. _Not_ redirecting the command is the only way to have it run without breaking.

The issue also occurs independent of invocation, `Invoke-Expression` results in this bug as does using `Start-Command`.

Also running this slightly tweaked function:
```
function Test-Ansi-Async {
    $VerbosePreference = 'Continue'
    Write-Verbose '------ Before ------'
    Start-Process -FilePath "C:\Program Files\Git\usr\bin\patch.exe" -RedirectStandardOutput NUL -ArgumentList '--help' -NoNewWindow
    Write-Verbose '------ After ------'
}
```
will yield different bugs in ConHost or Windows Terminal:

* In ConHost browsing through command history will have corrupted output, with characters remaining on screen between history items
* In Windows Terminal the ANSI color codes of the next command will be corruped

(See screenshots for each case).

In both cases pressing "Enter" without any input restores proper output at the prompt.

### Expected behavior

```console
VERBOSE: ------ Before ------
VERBOSE: ------ After ------
```

### Actual behavior

```console
VERBOSE: ------ Before ------
←[33;1mVERBOSE: ------ After ------←[0m
```

### Error details

```console
PS C:\Windows\System32› Get-Error
PS C:\Windows\System32›
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

# Visual Corruption in ConHost

![2022-01-20_ConHost-ANSI-Bug](https://user-images.githubusercontent.com/9436503/150246602-cb223f99-dd1d-48d4-b0b4-a640910e4801.png)

# Broken ANSI Codes in Windows Terminal

![2022-01-20_Terminal-ANSI-Bug](https://user-images.githubusercontent.com/9436503/150246904-8c27fbb4-e203-490b-a272-66bfbbc3b0a1.png)

**Comment by PatTheMav** [comment]
Possible duplicate of https://github.com/PowerShell/PowerShell/issues/16741 (it even uses the companion tool `diff.exe` from the same package).

Should've searched for "ANSI" instead of just "color" or "redirection" in the issue navigator.. 😣

**Comment by iSazonov** [comment]
@jhoneill Is this dup?

**Comment by jhoneill** [comment]
@iSazonov   

It's very similar to #16741   everything looks similar enough for me to think they are probably the same cause and same fix. 

The one difference is that the case I had the effect only lasted as for one command (if that was a function or script other statements in the same function were impacted), and after control came back to the prompt the next command was OK.  With this one the effect continues.

**Comment by PatTheMav** [comment]
The key is in the original issue and its solution: https://github.com/PowerShell/PowerShell/pull/14413

As mentioned, the tools shipped as part of Git For Windows disable console VT mode. The PR added code that will reactivate it, but its trigger was implemented in `InputLoop.Run`.

Which fixes the issue for interactive prompt sessions, but not for script runs (which is how I found the issue originally). So if `patch` or `diff` is run as part of a script, there is no work for the `InputLoop` and VT mode stays deactivated for the remainder of the script's run.

https://github.com/PowerShell/PowerShell/pull/16612 fixes this to re-enable VT mode (if it was enabled before) in `NotifyEndApplication`, which should run after `patch` or `diff` have finished and before any other Cmdlets or other commands are run within the script (e.g. in my case `Write-Verbose`).

**Comment by 237dmitry** [comment]
Windows Terminal and Alacritty do not reproduce this behavior. ConHost does.

![Screenshot 2022-01-20 173112](https://user-images.githubusercontent.com/78153320/150358364-206aefa1-b246-4b58-850a-6b574869e484.png)

**Comment by PatTheMav** [comment]
FWIW I did encounter this issue in Windows Terminal first - what it doesn't exhibit is the ANSI sequences remaining on the screen (see the screenshots in the issue posting).

**Comment by 237dmitry** [comment]
> see the screenshots in the issue posting

Of course I looked first

![Screenshot 2022-01-20 203437](https://user-images.githubusercontent.com/78153320/150391685-48a4fd7a-ab2a-45c7-be1c-92522c4d2cb7.png)

**Comment by PatTheMav** [comment]
That's weird - here's my run of the same commands in Windows Terminal 1.11.3471.0 (happens with `OutputRendering` set to Host and Ansi:

<img width="1006" alt="2022-01-20_Terminal-ANSI-Bug" src="https://user-images.githubusercontent.com/9436503/150392906-83ff7ac4-8777-46bb-b73a-fabb6d8fc792.png">

As a bit of hack, wrapping the command in `cmd.exe /c './patch.exe --help > NUL'` avoids the disabling of VT for the PowerShell session as the redirection happens elsewhere.

**Comment by 237dmitry** [comment]
> 1.11.3471.0

Perhaps this is a reason. I am using Preview (1.12.3472.0).

**Comment by jhoneill** [comment]
@237dmitry   this demonstrates it in Windows Terminal  - at least for me .

![image](https://user-images.githubusercontent.com/16209593/150396451-bc9f2c96-396b-4ca7-aad8-9e4a4d2698a0.png)

```
$x= & "C:\Program Files\Git\usr\bin\diff.exe" --help; $y = "`e[31m Red Text `e[0m"; $Y
```

if I run `$y ` as the next command it outputs correctly.

**Comment by PatTheMav** [comment]
Yeah that makes sense, as running the command triggers the InputLoop which restores the VT setting.

**Comment by 237dmitry** [comment]
I think it depends more on the terminal (as an application) in which to run it than on PowerShell. There is no problem in Alacritty too. 

![Screenshot 2022-01-20 212517](https://user-images.githubusercontent.com/78153320/150399057-3e26e754-e4a2-437b-8136-a1f5bdba10df.png)

**Comment by iSazonov** [comment]
Dup #16741
