### ISSUE TITLE
Get-ComputerRestorePoint can't resolve CreationTime

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/PowerShell#16779]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I can create a computer restore point in PowerSHell 7.2.1. 

```powershell
Checkpoint-Computer -description "pre winget updates"
Get-ComputerRestorePoint
```

But getting the restore point doesn't show the creation time. The value is there in the object as a DMTF string. But it doesn't get formatted. This works as expected in Windows PowerShell.

### Expected behavior

```console
PS C:\> Get-ComputerRestorePoint

CreationTime           Description                    SequenceNumber    EventType         RestorePointType
------------           -----------                    --------------    ---------         ----------------
1/20/2022 2:11:26 PM   Pre winget updates             63                BEGIN_SYSTEM_CHA… APPLICATION_INSTALL
```

### Actual behavior

```console
PS C:\> Get-ComputerRestorePoint

CreationTime           Description                    SequenceNumber    EventType         RestorePointType
------------           -----------                    --------------    ---------         ----------------
                       Pre winget updates             63                BEGIN_SYSTEM_CHA… APPLICATION_INSTALL
```

### Error details

```console
There are no errors.
```

### Environment data

```powershell
PS C:\> $PSVersionTable 

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/12089920/150407520-473be104-7406-4324-8f0f-6c207986a46e.png)

This works in Windows PowerShell on Windows 11 with no problem.

![image](https://user-images.githubusercontent.com/12089920/150407818-9605fbf8-0ca8-4588-a9e1-a9fb844016d9.png)

**Comment by jhoneill** [comment]
**I think**   Get-ComputerRestorePoint is a Windows PowerShell 5 command, 
but formatting is defined  for the object it returns in Pwsh 7 

```
ps 7 > Get-FormatData System.Management.ManagementObject#root\default\SystemRestore | % FormatViewDefinition | % control | % rows | % columns | select -First 1 -ExpandProperty displayentry |  % value

                    return $_.ConvertToDateTime($_.CreationTime) 
```

ConverttoDateTime is script method which is is added  - but is lost in the serialization / de-serialization process when the command is run in a remote (compatibility) session.

**Comment by iSazonov** [comment]
The cmdlets was in  Microsoft.PowerShell.Management but never was ported to Core due to .Net Core lacks.

I think right way is to try to restore the cmdlets https://github.com/PowerShell/PowerShell/issues/11732#issuecomment-580877408
