### ISSUE TITLE
Azure uses YAML. Please finally add ConvertFrom-Yaml, ConvertTo-Yaml

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#16785]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Start using PowerShell and Azure Pipelines with YAML
2. Now Microsoft expects that customers have to install uncontrolled opensource modules just so PowerShell can work with YAML
3. For us, this is extremely unexpected
4. And it's a pain for many years that M$ has no inner motivation to keep the PowerShell technology stack up to date.

### Expected behavior

```console
Get-Content 'config.yaml' | ConvertFrom-Json
# of course, ConvertTo-Yaml is missing too.

# It's a shame that we have to explain it.
```

### Actual behavior

```console
# 1. Search an open Source PowerShell module that handles yaml
# 2. make a review to be sure it has no security issues
# 3. Install and test the module
# 4. Search the next module, test it
# 5. If you finally have a Module, install and use it.
# 6. For each Modul-Update, restart at step 3.
```

### Environment data

```powershell
# Rel. 7.x must have yaml support
# Rel. 5.x should have yaml support

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Conclusion "Won't fix" was made by WG-Cmdlets in Aug,2021 

It seems .Net hasn't plans to implement YAML so close as duplication.

**Comment by jhoneill** [comment]
To  put  everything  in one place here is what was said in 3607 

> @PowerShell/wg-powershell-cmdlets has been discussing this issue, and despite the extremely high demand (and my own personal desire to have strong, canonical YAML cmdlets), we're unfortunately going to have to close it (for now) as Won't Fix. The reasoning is two-fold:

> (1) While the PowerShell package is already fairly large, we're doing our best not to add new dependencies to the package so that we don't continue to grow our size unfettered, and because **we believe that pulling modules from the PowerShell Gallery (or an internal trusted Gallery, having been vetted appropriately by an enterprise) should be a standard part of a PS7 workflow**.
> (2)  As a team, we simply don't have the capacity to build a .NET YAML parser from scratch, nor do we have the capacity to vet, support, and service a 3rd party library for which the security implications are high-stakes.
>If .NET were to officially support a YAML library, we (as Microsoft) could potentially look into supporting a YAML module on the Gallery. But until that point, the existing community modules will have to suffice.

[The community module referred to](https://www.powershellgallery.com/packages/powershell-yaml/0.4.2) has been downloaded 18 million times. It is based on  [YamDotNet](https://www.nuget.org/packages/YamlDotNet/) has been download from Nuget 36 Million times.   But as the quote above says the team don't have the capacity to _"vet support and service"_  it (I'm not sure what happened with NewonSoftJson before .NET added native JSON support). 

We have a classic case of **different Microsoft teams ignoring each other** 

-  **Azure Pipelines team**  YAML Is new and shiny let's be the first to use it!!!
- ** PowerShell team **  Customers want us to do more things than Microsoft gives resource for.  We can't write parsers for JSON, XML, YAML etc. (or validate 3rd party ones)  we need .NET to do that. A module which uses a community parser needs to be a community module. 
- ** .NET team **  We don't see the need to support every markup as it is invented, and there are good community libraries. 

 and customers like the OP say they don't want "community"  stuff they want everything to come from Microsoft. (Though from the use of "M$"  I assume the OP doesn't like paying for it).
