### ISSUE TITLE
Export-WindowsDriver cmdlet fails on Windows 11 (22000) and later on 7.2.1

### ISSUE THREAD

**Issue by andrewbaker-uk** [PowerShell/PowerShell#16788]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Open PowerShell 7 as administrator
2. Run command `export-windowsdriver -Online -Destination C:\drivers'

### Expected behavior

```console
PS> export-windowsdriver -Online -Destination C:\drivers
PS>

Drivers exported to C:\drivers
```

### Actual behavior

```console
PS> export-windowsdriver -Online -Destination C:\drivers

'Export-WindowsDriver: SafeHandle cannot be null. (Parameter 'pHandle')'
```

### Error details

```console
Exception             :
    Type       : System.ArgumentNullException
    Message    : SafeHandle cannot be null. (Parameter 'pHandle')
    ParamName  : pHandle
    TargetSite :
        Name          : ThrowArgumentNullException
        DeclaringType : System.ThrowHelper, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Source     : System.Private.CoreLib
    HResult    : -2147467261
    StackTrace :
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Dism.Commands.DismInterop._DismExportDriver(UInt32 Session, String Destination, SafeWaitHandle
CancelHandle, ProgressCallback Progress, IntPtr UserData)
   at Microsoft.Dism.Commands.ExportWindowsDriverCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Export-WindowsDriver], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Dism.Commands.ExportWindowsDriverCommand
InvocationInfo        :
    MyCommand        : Export-WindowsDriver
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : export-windowsdriver -Online -Destination C:\drivers
    PositionMessage  : At line:1 char:1
                       + export-windowsdriver -Online -Destination C:\drivers
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : export-windowsdriver
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22538
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://user-images.githubusercontent.com/10560135/150562770-bf893b2e-1cf8-48cd-a412-6b76878562ca.mp4

**Comment by andrewbaker-uk** [comment]
Same issue also occurs on PowerShell 5.1 on production Windows 11 device - I've raised individual feedback on FBH

**Comment by iSazonov** [comment]
@andrewbaker-uk The cmdlet and module are not in the repository. So Windows Feedback tool is right way to report.

**Comment by andrewbaker-uk** [comment]
@iSazonov awesome. Should I close this issue?

**Comment by GarrettAdamPhillips** [comment]
So, what is the resolution? This issue is still happening.

**Comment by andrewbaker-uk** [comment]
Not much @GarrettAdamPhillips. Filed it on Feedback Hub 3mths ago and there hasn't been any activity on it

https://aka.ms/AAgrlch

**Comment by andrewbaker-uk** [comment]
Same issue is occurring on PowerShell 7.2.2

**Comment by thuutien** [comment]
this is annoying. I really need this issue to be fixed.

**Comment by GarrettAdamPhillips** [comment]
Using dism is a work around NOT a fix.

**Comment by andrewbaker-uk** [comment]
@iSazonov please can this be reopened. Nothing seems to have changed in 3 months

**Comment by 1DanielKing** [comment]
Also having this issue.

_PS C:\WINDOWS\system32> export-windowsdriver -online -destination E:\DRIVERS
export-windowsdriver : Value cannot be null.
Parameter name: SafeHandle cannot be null.
At line:1 char:1
+ export-windowsdriver -online -destination E:\DRIVERS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-WindowsDriver], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Dism.Commands.ExportWindowsDriverCommand_

**Comment by turric4n** [comment]
Same error using WIndows Server 2022 (21H2)

**Comment by kudasaixc** [comment]
Same error here, using PowerShell 7.

**Comment by wrecklesswun** [comment]
have tried something like get-windowsdriver | export-windowsdriver ?

**Comment by nudlsoop** [comment]
This seems to have been broken for ages, see [Export-WindowsDriver doesn’t work?](https://oofhours.com/2020/12/21/export-windowsdriver-doesnt-work/) for a workaround using `dism` directly.

**Comment by andrewbaker-uk** [comment]
What version of the Dism module do you have? I've just tested on 22621.1848 and it works now. 

```
PS C:\Windows\system32> get-command export-windowsdriver

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Export-WindowsDriver                               3.0        Dism


PS C:\Windows\system32> get-module dism

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0        Dism                                {Add-AppProvisionedSharedPackageContainer, Add-AppxProvisi...
```

**Comment by exnerit** [comment]
any news on this?
