### ISSUE TITLE
Right click -> Copy column value in the Out-GridView

### ISSUE THREAD

**Issue by leechristensen** [PowerShell/PowerShell#16789]
### Summary of the new feature / enhancement

As a PowerShell user for several users, I didn't realize until recently that you can select a row in Out-GridView and hit Ctrl+C to copy the row's contents. My intuition told me to try and right click to see if there was a menu item with an entry labeled `Copy (Ctrl+C)` like in most applications, but there never was so I never knew. It'd be nice if you could:

1. Right click and have a context menu popup showing an entry for `Copy (Ctrl+C)`
2. Rather than copying the whole row, it'd be event better if I could copy a single cell (or even be able to select several cells and copy their contents)

**Comment by iSazonov** [comment]
@leechristensen The cmdlet is frozen and all new work is in https://github.com/PowerShell/GraphicalTools. Please open new issue there.
