### ISSUE TITLE
Output from Test-Connection ping contains extra charecters.

### ISSUE THREAD

**Issue by sawft99** [PowerShell/PowerShell#16783]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running 

`Test-Connection` with ping parameters piped into `Out-File` shows extra charecters. Also happend on linux.

### Expected behavior

```console
Same output without the extra charecters:


Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 MY-PC    9.9.9.9                        28         32 Success
   2 MY-PC    9.9.9.9                        28         32 Success
   3 MY-PC    9.9.9.9                        28         32 Success

```

### Actual behavior

```console
`[32;1mPing Source           Address                   Latency BufferSize Status[0m
[32;1m                                                   (ms)        (B)[0m
[32;1m---- ------           -------                   ------- ---------- ------[0m
   1 MY-PC    9.9.9.9                        28         32 Success
   2 MY-PC    9.9.9.9                        28         32 Success
   3 MY-PC    9.9.9.9                        28         32 Success`
```

### Error details

```console
None
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
`$PSStyle.OutputRendering =`  `Host` or `PlainText`

**Comment by jhoneill** [comment]
Can we add this to the list of  "Output is corrupt by default" reports. 

Do the team **really** think it is more important to have pretty green headers  (or the user's choice of colour) than to have clean text going to a file or external executables.

**Comment by sawft99** [comment]
> `$PSStyle.OutputRendering =` `Host` or `PlainText`

That worked for it.

**Comment by sawft99** [comment]
Should I close this as solved, or is this something that should be fixed in PowerShell?
