### ISSUE TITLE
Add nice column formating option to Export-Csv command

### ISSUE THREAD

**Issue by MrDRamos** [PowerShell/PowerShell#16792]
### Summary of the new feature / enhancement

I would like an optional switch parameter e.g. -Alligned that formats the CSV data as nice table by padding entries with space characters.

**Comment by iSazonov** [comment]
It is not right to place a formatting in regular cmdlets. For formatting PowerShell has Formatting system and Format-* cmdlets.

**Comment by MrDRamos** [comment]
But there are exceptions. The -Compress switch on ContertTo-Json removes extra white space without, This is ok because parsing jscon is not sensitive to white space. A similar argument can be made for the suggested -Alligned switch on Export-Csv, Extra white space does not effect  parsing csv content.

**Comment by MrDRamos** [comment]
But there are exceptions. The -Compress switch on ContertTo-Json removes extra white space which is ok because parsing jscon is not sensitive to white space. A similar argument can be made for the suggested -Alligned switch on Export-Csv, Extra white space does not effect  parsing csv content.
