### ISSUE TITLE
Functions destroy $?, cannot make wrapper function.

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#16793]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$grep = '/ProgramData/chocolatey/bin/grep.exe'

function grep {
    $input | &$grep --color @args
}

'bar' | &$grep -q foo
$? # False
'bar' | grep  -q foo
$? # True
```

### Expected behavior

```console
False
False
```

### Actual behavior

```console
False
True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22538
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
The function was executed successfully, so `True`
```
function a { param( [Parameter(Mandatory)] [int] $a); $a}
a 1
$?       # True

a 'a'
$?       # Error and False
```

**Comment by rkitover** [comment]
Never mind, I misunderstood the purpose of `$?` and I have a workaround:

```powershell
function global:grep {
    $input | &(command grep) --color $args
    if (-not $?) { write-error "exited: $LastExitCode" -ea stop }
}
```
.
