### ISSUE TITLE
$args and $psscriptroot should be visible in debug session

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#16795]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```ps
function testArgs {Write-Warning $($args -join ',');Wait-Debugger}
testArgs
```

### Expected behavior

```console
$args should be accessible at the debug prompt
```

### Actual behavior

```console
$args is blank
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/15258962/150812641-9f243493-a98d-4e90-80ac-6da7cab90b34.png)

**Comment by kasini3000** [comment]
``powershell
function testArgs
{
	$psscriptroot
	$args
	Wait-Debugger
}

testargs 'a' 'b' 1 2
```
psv 5.1 ps v7.x

**Comment by rkeithhill** [comment]
The Engine WG reviewed this issue today. We believe that being able to access these variables in the debugger is useful.  We would like to get our debugger expert's opinion on this issue before determining a direction to take.

**Comment by JustinGrote** [comment]
I believe that would be @PaulHigin?

**Comment by rkeithhill** [comment]
That's why we assigned to @PaulHigin.

**Comment by iSazonov** [comment]
I guess there are other special variables (not only `$args`) not visible in debugger, yes?
