### ISSUE TITLE
List of various Type completion flaws

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#16798]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've looked into the type completion and have come up with this list of issues:

1: It doesn't take conflicting `Using namespace` statements into consideration, for example:
```
using namespace System.Threading
using namespace System.Timers
[Timer<Tab>
```
will suggest "Timer" but if you actually tried to use that you would get a runtime error due to the ambiguous type (it's either System.Threading.Timer or System.Timers.Timer). Ideally it would find the shortest unambiguous name, which in this case would be Threading.Timer and Timers.Timer due to the implicit System namespace.

2: PowerShell types and Using namespace statements are only taken into consideration if they are included in the script text that is being completed. To demonstrate, you can add an Enum and a using statement to your $profile:
```
using namespace System.Collections.Generic
enum Whatever
{
    value1 = 1
}
```
From a new console, If you try to complete `Whatever` in the console you'll get no results. If you try to complete `List` it will suggest `System.Collections.Generic.List` instead of just `List`.  
Ideally PowerShell types defined in the script text as well as ones that have been loaded into the session should be included in the completions. For using statements, it should use the ones in the script text and if there aren't any, fall back to the ones loaded into the session.

3: PowerShell types imported through using module aren't considered for completion. Fixing the previous issue would partially fix this, but maybe it's also worth parsing the specified module? The Symbol resolver code does this at parse time so maybe the completion code should as well?

4: Namespaces aren't taken into consideration when completing input, their only use seems to be to trim types that are found. For example:
```
using namespace System.Collections
[Generic.List<Tab>
#or
[Generic.<Tab>
```

won't complete to anything. You have to type the full name to get any completions.

5: Quotes aren't handled properly in the namespace removal in the completion if used in `using namespace`
For example:
```
using namespace "System.Management"
[token<Tab>
```
completes to `[tomation.Language.Token]` instead of `[Automation.Language.Token]`
### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```powershell
PS C:\Users\Martin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
My concern is that some limitations in tab completion comes from how Engine works.
@vexx32 @SeeminglyScience Thoughts?

**Comment by vexx32** [comment]
I mean yeah, to an extent, but that doesn't mean the information about active `using namespace` declarations (or indeed any `using` statements that may impact tab completion) can't be recorded somewhere for the tab completion code to look at. 

It mightn't be entirely straightforward, but I think it's a worthwhile change to investigate.

**Comment by MartinGC94** [comment]
I've already looked into fixing these issues and I don't think it's impossible or even that hard to fix them. The hardest one to fix is issue 4 because the type completion cache is grouped into "dots" to make lookups faster. You could prepend each using statement to the wordToComplete and do multiple lookups but performance might take a hit so maybe it's better to find a different way to group them or maybe even avoid grouping them at all.

**Comment by iSazonov** [comment]
I guess it is type cache only? not namespace?
