### ISSUE TITLE
Update documentation for FileInfo/DirectoryInfo

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#16799]
### Summary of the new feature / enhancement

Issue copied from https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8505

Due to the addition of `ResolvedTarget` in issue https://github.com/PowerShell/PowerShell/issues/13366 and PR https://github.com/PowerShell/PowerShell/pull/16490, and the lack of any mention of PowerShell on the C# page for [`FileInfo`](https://docs.microsoft.com/en-US/dotnet/api/System.IO.FileInfo?view=net-6.0) and [`DirectoryInfo`](https://docs.microsoft.com/en-US/dotnet/api/System.IO.DirectoryInfo?view=net-6.0), it may make sense to create a separate page for these objects in the PowerShell documentation, so they may have the aforementioned `ResolvedTarget` property, which doesn't exist outside of PowerShell.

### Proposed technical implementation details (optional)

.NET API documentation must be updated in the PowerShell source code.

**Comment by 237dmitry** [comment]
Maybe `ResolveLinkTarget`?
```
PS >  [IO.FileInfo]::new("$pwd\file.ext") | gm *Target

   TypeName: System.IO.FileInfo

Name              MemberType    Definition
----              ----------    ----------
Target            AliasProperty Target = LinkTarget
ResolveLinkTarget Method        System.IO.FileSystemInfo ResolveLinkTarget(bool returnFinalTarget)
LinkTarget        Property      string LinkTarget {get;}
```

**Comment by hammy3502** [comment]
`ResolveLinkTarget` and `ResolvedTarget` are a bit different:
`ResolveLinkTarget` resolves the link target and returns `null` if the file isn't a symbolic link
`ResolvedTarget` resolves the link target, but returns a path to itself if it isn't a symbolic link
