### ISSUE TITLE
Get-CimInstance -Class Win32_Processor -Property Architecture

### ISSUE THREAD

**Issue by Adkimsm** [PowerShell/PowerShell#16802]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

![]('https://user-images.githubusercontent.com/75924586/150662651-acdc5565-9402-4a04-a696-f148561c5cf3.png')

When i run the command `Get-CimInstance -Class Win32_Processor -Property Architecture`,powershell will says "指定的类不存在"

When I use the [oh-my-posh]("https://github.com/JanDeDobbeleer/oh-my-posh"),i found this bug.

### Expected behavior

```console
https://github.com/JanDeDobbeleer/oh-my-posh/issues/1625 : JanDeDobbeleer says `Get-CimInstance -Class Win32_Processor -Property Architecture` should be a int, i don't know.but i don't think it throws errors.
```

### Actual behavior

```console
PS C:\Users\rafae> Get-CimInstance -Class Win32_Processor -Property Architecture
Get-CimInstance: 指定的类不存在。
```

### Error details

```console
PS C:\Users\rafae> Get-Error

OriginInfo            :
Exception             :
    Type            : Microsoft.Management.Infrastructure.CimException
    NativeErrorCode : InvalidClass
    ErrorData       : MSFT_ExtendedStatus
    MessageId       : HRESULT 0x80041010
    StatusCode      : 1
    TargetSite      :
        Name          : ProcessNativeCallback
        DeclaringType : Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1[T]
        MemberType    : Method
        Module        : Microsoft.Management.Infrastructure.dll
    Message         : 指定的类不存在。
    Source          : Microsoft.Management.Infrastructure
    HResult         : -2146233088
    StackTrace      :
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(Operati
onCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, St
ring errorMessage, InstanceHandle errorDetailsHandle)
CategoryInfo          : MetadataError: (:) [Get-CimInstance], CimException
FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
InvocationInfo        :
    MyCommand        : Get-CimInstance
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Get-CimInstance -Class Win32_Processor -Property Architecture
    PositionMessage  : At line:1 char:1
                       + Get-CimInstance -Class Win32_Processor -Property Architecture
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-CimInstance
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :




PS C:\Users\rafae>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![]('https://user-images.githubusercontent.com/75924586/150662651-acdc5565-9402-4a04-a696-f148561c5cf3.png')

**Comment by iSazonov** [comment]
The message says "Class does not exist". It is not PowerShell error. It is OS error. You should restore your OS.

**Comment by kasini3000** [comment]
The command works fine for me. Unable to reproduce the problem, please use a newly installed win10 virtual machine to test.
命令在我这里正常运行。无法重现问题，请使用新安装的，干净的，win10虚拟机测试。或者换台机器测试。

**Comment by Adkinsm2020** [comment]
before i upgrade win11, i can use it.but after this i cannot use it.Is this bug about win11?

**Comment by iSazonov** [comment]
> before i upgrade win11, i can use it.but after this i cannot use it.Is this bug about win11?

Maybe. But rather it is a bad in upgrade itself.

**Comment by Adkinsm2020** [comment]
But win11 is good,isn't it?

**Comment by iSazonov** [comment]
I haven't Win11 to check the issue. 
There are WMI tools which you could use to investigate and recover WMI. It is a topic for other forums.

**Comment by kasini3000** [comment]
command tested in my win11 vm ,normal

**Comment by Adkinsm2020** [comment]
what happend with my pc?
