### ISSUE TITLE
Remove-Item fails on FAT32 drive when encountering some Unicode characters

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#16804]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Consider the data in
[RADWIMPS.zip](https://github.com/PowerShell/PowerShell/files/7941251/RADWIMPS.zip)
(note: this is copyrighted material I rip-ped from a CD I legally own; please don't redistribute).

When this is found on a FAT32 drive, you cannot delete the file tree using `Remove-Item`:

 
![image](https://user-images.githubusercontent.com/12860484/151152989-b154bb34-35ad-4bf5-833d-70e6a3bbcb6e.png)

This repro's both in 7.2.1 and 7.3.0-preview.1.

CMD.EXE has no problem with the same data:

![image](https://user-images.githubusercontent.com/12860484/151153132-b8f78be7-7915-4080-af56-778159ed52cf.png)

### Expected behavior

```console
`Remove-Item` should remove the entire directory tree.
```

### Actual behavior

```console
`Remove-Item` fails with `Remove-Item: No mapping for the Unicode character exists in the target multi-byte code page.`
```

### Error details

```console
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 1113
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : IsReparsePointLikeSymlink
        DeclaringType : Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message         : No mapping for the Unicode character exists in the target multi-byte code page.
    Source          : System.Management.Automation
    HResult         : -2147467259
    StackTrace      :
   at
Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods.IsReparsePointLikeSymlink(FileSystemInfo
fileInfo)
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory,
Boolean recurse, Boolean force, Boolean rootOfRemoval)
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory,
Boolean recurse, Boolean force, Boolean rootOfRemoval)
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse)
   at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String
path, Boolean recurse, CmdletProviderContext context)
CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
InvocationInfo        :
    MyCommand        : Remove-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 78
    Line             : Remove-Item -Recurse -Force -LiteralPath J:\RADWIMPS -Verbose
    PositionMessage  : At line:1 char:1
                       + Remove-Item -Recurse -Force -LiteralPath J:\RADWIMPS -Verbose
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Remove-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
Can you create and share more simple repro steps/script?

**Comment by sba923** [comment]
Well, I can.... but the current repro is quite simple: 
1. extract the zipfile to a folder on a FAT32 USB stick
2. attempt to remove the folder using `Remove-Item -Recurse`

I'll check whether I can replace step 1 with a piece of PowerShell, is that what you'd like?

**Comment by iSazonov** [comment]
> I'll check whether I can replace step 1 with a piece of PowerShell, is that what you'd like?

It would great! See the test as example https://github.com/daxian-dbw/PowerShell/blob/203cbccfc4512a1ad738d6c5114d4b2756db0ad7/test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1#L256

**Comment by sba923** [comment]
What about this?

```powershell
$parentfoldername = 'PS16804'
$foldername = '天気の子'
$filename = '01 - 「天気の子」のテーマ.mp3'

$parentfolder_abspath = Join-Path -Path $PSScriptRoot -ChildPath $parentfoldername
$folder_abspath = Join-Path -Path $PSScriptRoot -ChildPath ("{0}\{1}" -f $parentfoldername, $foldername)

# start from a clean slate
if (Test-Path -LiteralPath $parentfolder_abspath)
{
    # use CMD since Remove-Item will not work
    cmd /c "rd /s /q $parentfolder_abspath"
}

if (Test-Path -LiteralPath $parentfolder_abspath)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $parentfolder_abspath)
    Exit(1)
}

New-Item -Path $folder_abspath -ItemType Directory -Force | Out-Null
if (!(Test-Path -LiteralPath $folder_abspath))
{
    Write-Host -ForegroundColor Red ("Failed to create '{0}'" -f $folder_abspath)
    Exit(1)
}

$filepath_abs = Join-Path -Path $folder_abspath -ChildPath $filename
"" | Out-File -LiteralPath $filepath_abs

Write-Host -ForegroundColor Yellow ("Attempting to remove '{0}' using Remove-Item -Recurse -Force" -f $parentfolder_abspath)
Remove-Item -Force -Recurse -Verbose -LiteralPath $parentfolder_abspath
if (Test-Path -LiteralPath $parentfolder_abspath)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $parentfolder_abspath)
}
else {
    Write-Host -ForegroundColor Green ("Removal of '{0}' succeeded" -f $parentfolder_abspath)
}

Write-Host -ForegroundColor Yellow ("Attempting to remove '{0}' using CMD /C RD /S /Q" -f $parentfolder_abspath)
cmd /c "rd /s /q $parentfolder_abspath"
if (Test-Path -LiteralPath $parentfolder_abspath)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $parentfolder_abspath)
}
else {
    Write-Host -ForegroundColor Green ("Removal of '{0}' succeeded" -f $parentfolder_abspath)
}
```
[PS16804.zip](https://github.com/PowerShell/PowerShell/files/7943166/PS16804.zip)

Here's the output this gets me:
![image](https://user-images.githubusercontent.com/12860484/151199417-34a47137-b1d0-4f2d-9b56-881383e85fdf.png)

**Comment by iSazonov** [comment]
@sba923 Thanks! Your script should run on FAT32 that's why I pointed to the test code that uses a virtual disk. Could you please add these steps in your script?

**Comment by sba923** [comment]
What about this?

```powershell
#requires -RunAsAdministrator

$testdrive = 'c:\tmp'

# create a virtual FAT32 drive and mount it
$vhdx = Join-Path -Path $TestDrive -ChildPath 'PS16804.vhdx'

if (Test-Path -Path $vhdx) {
    Remove-item -Path $vhdx -Force -Verbose
}

Dismount-DiskImage -ImagePath $vhdx -ErrorAction SilentlyContinue

$create_vhdx = Join-Path -Path $TestDrive -ChildPath 'create_vhdx.txt'

Set-Content -Path $create_vhdx -Force -Value @"
    create vdisk file="$vhdx" maximum=100 type=fixed
    select vdisk file="$vhdx"
    attach vdisk
    convert mbr
    create partition primary
    format fs=fat32
    assign letter="T"
    detach vdisk
"@

diskpart.exe /s $create_vhdx
Mount-DiskImage -ImagePath $vhdx > $null

$driveroot = 't:\'

if (Test-Path -LiteralPath $driveroot)
{

# repro the issue
$parentfoldername = 'PS16804'
$foldername = '天気の子'
$filename = '01 - 「天気の子」のテーマ.mp3'

$parentfolder_abspath = Join-Path -Path $driveroot -ChildPath $parentfoldername
$folder_abspath = Join-Path -Path $driveroot -ChildPath ("{0}\{1}" -f $parentfoldername, $foldername)

# start from a clean slate
if (Test-Path -LiteralPath $parentfolder_abspath)
{
    # use CMD since Remove-Item will not work
    cmd /c "rd /s /q $parentfolder_abspath"
}

if (Test-Path -LiteralPath $parentfolder_abspath)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $parentfolder_abspath)
    Exit(1)
}

New-Item -Path $folder_abspath -ItemType Directory -Force | Out-Null
if (!(Test-Path -LiteralPath $folder_abspath))
{
    Write-Host -ForegroundColor Red ("Failed to create '{0}'" -f $folder_abspath)
    Exit(1)
}

$filepath_abs = Join-Path -Path $folder_abspath -ChildPath $filename
"" | Out-File -LiteralPath $filepath_abs

Write-Host -ForegroundColor Yellow ("Attempting to remove '{0}' using Remove-Item -Recurse -Force" -f $parentfolder_abspath)
Remove-Item -Force -Recurse -Verbose -LiteralPath $parentfolder_abspath
if (Test-Path -LiteralPath $parentfolder_abspath)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $parentfolder_abspath)
}
else {
    Write-Host -ForegroundColor Green ("Removal of '{0}' succeeded" -f $parentfolder_abspath)
}

Write-Host -ForegroundColor Yellow ("Attempting to remove '{0}' using CMD /C RD /S /Q" -f $parentfolder_abspath)
cmd /c "rd /s /q $parentfolder_abspath"
if (Test-Path -LiteralPath $parentfolder_abspath)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $parentfolder_abspath)
}
else {
    Write-Host -ForegroundColor Green ("Removal of '{0}' succeeded" -f $parentfolder_abspath)
}
}
Dismount-DiskImage -ImagePath $vhdx > $null
Remove-item -Path $vhdx -Force
Remove-item -Path $create_vhdx -Force


```
[PS16804.zip](https://github.com/PowerShell/PowerShell/files/7944146/PS16804.zip)

Output:

![image](https://user-images.githubusercontent.com/12860484/151229024-f7b05918-d9fa-43ab-82d6-46f65307cd09.png)

**Comment by sba923** [comment]
BTW, I can't repro with Windows PowerShell 5.1:

![image](https://user-images.githubusercontent.com/12860484/151230748-af0ec25f-4042-4ecc-bc76-acea2aa8a375.png)

**Comment by jborean93** [comment]
I'm curious if you can delete the files with `[System.IO.File]::Delete($filePath)`? If this works it sounds like .NET is able to handle this particular scenario and the problem stems from extra code that PowerShell adds.

Based on the exception traceback it seems like the problem stems from [IsReparsePointLikeSymlink](https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L8250) which AFAIK is not present in 5.1. It could be that the FindFirstFileEx set of Win32 functions that are called aren't handling the FAT32 limitations problems. I know that FAT32 filesystems encode their file names in the OEM codepage and aren't actually unicode so the error message points to problems relating to that.

**Comment by iSazonov** [comment]
We could filter out based on 1113 native error code but I wonder why FindFirstFileEx return an error for FAT32 if no limitations are mentioned in docs - looks like OS bug. I guess perhaps the error code comes from p/invoke wrapper code and a bug is FindFirstFileExW return non-unicode string.

**Comment by kasini3000** [comment]
I am coming. It sounds like copying these files out using powershell and then copying them back will solve the problem. If so, it should be an old version of the software that did not use the correct encoding, or bypassed the win encoding mechanism and wrote the file directory. 

I'm not good at these and can't help much more.

**Comment by iSazonov** [comment]
> It sounds like copying these files out using powershell and then copying them back will solve the problem.

@kasini3000 Did you try on virtual disk like https://github.com/PowerShell/PowerShell/issues/16804#issuecomment-1022500443?

**Comment by sba923** [comment]
> I'm curious if you can delete the files with `[System.IO.File]::Delete($filePath)`

This works:

```powershell
Write-Host -ForegroundColor Yellow ("Attempting to remove '{0}' using [System.IO.File]::Delete()" -f $filepath_abs)
[System.IO.File]::Delete($filepath_abs)
if (Test-Path -LiteralPath $filepath_abs)
{
    Write-Host -ForegroundColor Red ("Failed to remove '{0}'" -f $filepath_abs)    
}
else {
    Write-Host -ForegroundColor Green ("Removal of '{0}' succeeded" -f $filepath_abs)    
}
```

![image](https://user-images.githubusercontent.com/12860484/151311459-698bc3a3-5ea9-472b-8be9-d4eaa4c325c8.png)

**Comment by kasini3000** [comment]
@iSazonov : 
no , 

```
Write-Host -ForegroundColor Yellow ("Attempting to remove '{0}' using Remove-Item -Recurse -Force" -f $parentfolder_abspath)
Remove-Item -Force -Recurse -Verbose -LiteralPath $parentfolder_abspath
```
Tested in my picture up ps code，normal.


In addition, I suggest that poster add the BOM header to his own script and run it again, there may be no problem.

**Comment by sba923** [comment]
> In addition, I suggest that poster add the BOM header to his own script and run it again, there may be no problem.

Adding the BOM to the script unsurprisingly doesn't solve anything.

**Comment by sba923** [comment]
> We could filter out based on 1113 native error code but I wonder why `FindFirstFileEx` return an error for FAT32 if no limitations are mentioned in docs - looks like OS bug. I guess perhaps the error code comes from p/invoke wrapper code and a bug is `FindFirstFileExW` return non-unicode string.

Is there anything I can do to help narrow this down?

@iSazonov Are you able to repro with my latest virtual disk-based script?

**Comment by iSazonov** [comment]
Yes, I can. Thanks!

**Comment by iSazonov** [comment]
@SteveL-MSFT found follow discussion https://groups.google.com/g/fastcopy-bb-eng/c/z6DJRzeGeL4/m/IEsaD7g6AgAJ?pli=1

In short, we could replace FindFirstFileExW with FindFirstFileW.

**Comment by KalleOlaviNiemitalo** [comment]
Does the failing FindFirstFileExW call have the particular file name in the `LPCWSTR lpFileName` argument, or is that only a directory path and a wildcard? I wonder if the error comes from the Win32 layer or from somewhere in FatQueryDirectory, perhaps [here](https://github.com/microsoft/Windows-driver-samples/blob/1fe4cc42bedfccb97a5b2cc169f9e5306d41d0de/filesys/fastfat/dirctrl.c#L574-L576); that does check for STATUS_UNMAPPABLE_CHARACTER though.
