### ISSUE TITLE
Start-Process pwsh Shell Corruption on Linux

### ISSUE THREAD

**Issue by juvtib** [PowerShell/PowerShell#16803]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

* Open  xfce4-terminal v0.8.10. 
* Run `pwsh`. 
* Enter `Start-Process pwsh`. 

### Expected behavior

```console
I expect to get a nested pwsh instance.
```

### Actual behavior

```console
The shell prints "5;1R;7R;12R;14R;" and so on with no keystrokes. Eventually, the shell is overwhelmed with corrupted text. 

```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.15.16-1-MANJARO #1 SMP PREEMPT Thu Jan …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
* [Install powershell on Manjaro Linux using the Snap Store | Snapcraft](https://snapcraft.io/install/powershell/manjaro)

### Visuals

* [screen capture 01](https://i.imgur.com/XApg0NY.png)
* [screen capture 02](https://i.imgur.com/iIw0N0q.png)

**Comment by 237dmitry** [comment]
`Start-Process` does not know in which terminal launch pwsh (bash, etc)
```
Start-Process xfce4-terminal -arg "-x pwsh -nologo"
```

**Comment by kasini3000** [comment]
i test again,
Start-Process -FilePath '/usr/bin/pwsh' -ArgumentList ' -f /ps1/20220127.ps1' #normal
NOTE: I didn't use the -nologo parameter, but it didn't print the logo on the parent process.

----

my problem similar with this， 
https://github.com/PowerShell/PowerShell/discussions/16583
Until now, I didn't know the cause of the problem.
on 16583，pwsh print like 【"5;1R;7R;12R;14R;" 】 after 2---3 second，and HANG.

**Comment by juvtib** [comment]
Sorry. The bug form threw me off. In terms of reproducing the bug, 

1. I just launch the default terminal for my distribution. In my case, Xfce Terminal. 
2. Then I start PowerShell: `pwsh`
3. Then I try to use Start-Process to launch a nested shell: `Start-Process pwsh`

The last step is what begins the corruption. 

My interest in using Start-Process to start pwsh was to troubleshoot someone else's code. This was as far as I got on my system. I assume the person I'm trying to help is on Windows and their error is unrelated.

**Comment by juvtib** [comment]
The only other detail is I'm using a Snap. 

[Install powershell on Manjaro Linux using the Snap Store | Snapcraft](https://snapcraft.io/install/powershell/manjaro)

**Comment by iSazonov** [comment]
> The only other detail is I'm using a Snap.

Is this mandatory to reproduce the issue?

**Comment by juvtib** [comment]
> Is this mandatory to reproduce the issue?

I don't know. But if there is some problem reproducing the issue on vanilla Linux, this might be a factor.

**Comment by mklement0** [comment]
* Use just `pwsh` to _synchronously_ enter another PowerShell session, i.e. invoke it _directly_.
* If you do want to use `Start-Process` (there's no good reason in this case, and rarely a good reason on Unix-like platforms in general), use `-Wait` to ensure synchronous execution - it is the _asynchronous_ execution that causes the problem - the calling session and the new session _compete for user input_.

See the following for background information:
* https://github.com/PowerShell/PowerShell/issues/17173#issuecomment-1741166896

**Comment by theJasonHelmick** [comment]
Thank you for this issue @juvtib.   One option is to start `Start-process pwsh -wait` or you can start the terminal application (i.e `start-process terminal.app`) and use the terminal app options to launch pwsh.  The Interactive working group has reviewed this and have decided this is by design.

**Comment by juvtib** [comment]
My interest was in reporting an apparent bug. Without a warning from the cmdlet or an obvious reference in the help file, this was a bug as far as I knew. If I see this issue again, I will use the `-Wait` parameter of `Start-Process`. I acknowledge I might have invoked `pwsh` directly. But I assume I was using some feature of `Start-Process` when I reported this issue two years ago. Regards,
