### ISSUE TITLE
Where-Object provides incorrect and inconsistent results

### ISSUE THREAD

**Issue by JoeSalmeri** [PowerShell/PowerShell#16815]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Where-Object produces incorrect and inconsistent results depending on whether a scriptblock or property is used for the criteria

I found this issue with much more complicated function I wrote BUT have reduced it down the following example code:

        $o = [pscustomobject] @{ Value1 = 'abc' ; Value2 = 'abc' }

        $o

             which displays the following ( as expected )

                      Value1 Value2
                      ------ ------
                      abc    abc

        $o.Value1 -eq $o.Value2

              which returns True ( as expected )

        $o | Where-Object Value1 -ne Value2

              which returns the following which is NOT expected

                    Value1 Value2
                    ------ ------
                    abc    abc

        $o | Where-Object { $_.Value1 -ne $_.Value2 }

                which returns NOTHING as expected since Value1 and Value2 are the same

Why does "$o | Where-Object Value1 -ne Value2" produce the wrong result and not the same result as 
"$o | Where-Object { $_.Value1 -ne $_.Value2 }"

I thought the purpose of simple Where-Object use was to avoid the script block?

What have I missed ?

### Expected behavior

```console
Documented inline with example
```

### Actual behavior

```console
Documented inline with example
```

### Error details

```console
Documented inline with example
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.15.12-1-default #1 SMP Wed Dec 29 14:50:16 UTC 2021 (375fcb8)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

*** NOTE: 

This issue was reproduced on Linux AND Windows using pwsh 7.2.1 but I have also reproduced back to pwsh 7.1.5
```

**Comment by vexx32** [comment]
The scriptblock-less parameter set only evaluates the first argument as resolving to a property name on the object. The fully laid out pattern is:

```powershell
$objects | Where-Object -Property PropertyName -eq -Value $someValue
```

In other words, only the `Value1` in your example is actually considered to reference the property, and the `Value2` in your example is treated as a literal string `"Value2"`.

**Comment by JoeSalmeri** [comment]
@vexx32 

Thanks very much, that makes perfect sense now.

Frequently my Where-Object logic needs a script block because it is more than one condition requiring -and / -or

A lot of the examples in the docs are very similar along the lines of 

Where-Object Something -eq 'somevalue' 

which the docs say are the same as 

Where-Object { $_.Something -eq 'somevalue'  }

I mistakenly jumped to the conclusion that ANY single value comparison could use the comparison logic instead of a script block.

Thanks very much for the clarification, I appreciate it!
