### ISSUE TITLE
This book as a book.

### ISSUE THREAD

**Issue by SynergyCoryS** [PowerShell/PowerShell#16817]
### Summary of the new feature / enhancement

I want this entire PowerShell Docs site as a downloadable (and printable - aka ring binder, take it to Staples and get it bound, etc) so I can have it as a desk reference.  I find paper books really helpful because they exist on my desk, and do not take up one of my monitors.  Bonus points for actually publishing these as paper books.  I'd give you $50 right now for this entire docs set as an actual book.  Maybe Reilly or someone would publish it?

### Proposed technical implementation details (optional)

Have a download PDF button for the entire PowerShell docs set.  Second, think about actually publishing this as an actual book through an actual publisher.  Or even have Docs sets available as books-made-to-order (maybe through Shutterfly)?

**Comment by SynergyCoryS** [comment]
Could be done Microsoft-Docs wide, for all the Docs.

**Comment by doctordns** [comment]
This is a great idea - but it's really not an issue for the PowerShell team. I suggest [the PowerShell docs team could do this](https://github.com/MicrosoftDocs/PowerShell-Docs) and raising the issue there is possibly more appropriate. 

I seem to recall at one time you could do something like this (click to create a PDC of help text) but not sure.

**Comment by SynergyCoryS** [comment]
Thanks, I wasn't sure where to leave it. I can print each page, then use the Windows print to PDF, but I would love to get a book. I will reach out to the PowerShell docs team.

**Comment by iSazonov** [comment]
It was Microsoft Doc site feature to save as PDF. Now I don't see the feature.
All PowerShell docs is in https://github.com/MicrosoftDocs/PowerShell-Docs. This allows to generate custom docs. I don't think PowerShell doc team will do this but you or community can. I guess there are already MD to PDF convertors.

**Comment by SynergyCoryS** [comment]
Sure, hence the product idea of a book.  Does MS still publish books? I
mean there are dozens of them (any you might recommend?) but an official MS
book would rock.  I remember back in the day there were books.
*Cory Sarzotti, CTS*
Programmer
*Synergy Media Group*
301 Brush Creek Road, Warrendale, PA 15086
p: 888.321.0040 <(888)%20321-0040>
c: 412-526-1705 <(412)%5261705>
www.synmediagroup.com

**Comment by adilio** [comment]
FWIW: My (somewhat biased) opinion of a great place to start in terms of books is the "Learn PowerShell in a Month of Lunches" series, if you're looking for a good place to start. It's the book that's most recommended for beginners in the PowerShell Community Slack/Discord.
