### ISSUE TITLE
pwsh faulting when using Ansi alternate screen buffer

### ISSUE THREAD

**Issue by natebarkei** [PowerShell/PowerShell#16818]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

pwsh.exe 7.2.1 is consistently crashing in terminal when using the alternant screen buffer ansi commands. It appears to not be able to read the console buffer after a return to the original screen (ESC[?1049l). 

This issue appears to not happen in 7.1.4, but does happen in 7.2.1.

Code to reproduce:
>
>   $ESC = [char]27
>    for($i=0; $i -lt 100; $i++) {
>        $host.ui.Write("$ESC[?1049h")
>        $host.ui.Write("Alternate screen buffer")
>        $host.ui.Write("$ESC[?1049l")
>        $host.ui.Write('.')
>    }

### Expected behavior

```console
Not having the pwsh application crash.
```

### Actual behavior

```console
[process exited with code 2148734499]
```

### Error details

```console
Since the process terminates it is impossible to use Get-Error however these are the event logs generated.

`Faulting application name: pwsh.exe, version: 7.2.1.500, time stamp: 0x61735063
Faulting module name: Microsoft.PowerShell.ConsoleHost.dll, version: 7.2.1.500, time stamp: 0x82fa903e
Exception code: 0x80131623
Fault offset: 0x000000000004e67a
Faulting process id: 0x4470
Faulting application start time: 0x01d81454ff876eb3
Faulting application path: C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.1.0_x64__8wekyb3d8bbwe\pwsh.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.1.0_x64__8wekyb3d8bbwe\Microsoft.PowerShell.ConsoleHost.dll
Report Id: f4a3f960-3476-482c-a6ce-3659f0956721
Faulting package full name: Microsoft.PowerShell_7.2.1.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App`

`Application: pwsh.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
Description: The process was terminated due to an unhandled exception.System.Management.Automation.Host.HostException: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
 ---> System.ComponentModel.Win32Exception (233): No process is on the other end of the pipe.
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ConsoleControl.GetConsoleScreenBufferInfo(SafeFileHandle consoleHandle)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
`
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
In my environment pwsh does not crash. Just jumped cursor:


https://user-images.githubusercontent.com/78153320/151585716-ca77d788-74a7-4ca0-865c-acfcedf089c7.mp4

**Comment by iSazonov** [comment]
@SteveL-MSFT In continuation of our discussion, this issue demonstrates why I concern that we are being forced to create "Windows Terminal".

**Comment by natebarkei** [comment]
The size of the terminal window and whether it has been maximized seems to effect this bug somewhat. There is defiantly a timing issue involved. But pwsh shouldn't just be hard faulting here... without looking at the code can't you try catch this call. I gave you the stacktrace.

https://user-images.githubusercontent.com/30415407/151594159-710a5b6e-501e-4922-8675-06ab387307b3.mp4

**Comment by natebarkei** [comment]
Honestly, if you have a workaround that would be fine as well. Clearly, the sample code I wrote to repro this isn't the actual reason I'm reporting this bug. I have tried inserting `start-sleep` in before I attempt to access the buffer again (through ansi calls to `$host.ui.Write`) to no avail (probably because it's single threaded and not allowing whatever needs to happen to happen). 
Throwing an error is fine, but just terminating the entire runtime without a way to recover or trap is insane.

**Comment by 237dmitry** [comment]
> The size of the terminal window and whether it has been maximized seems to effect this bug somewhat.

I couldn't reproduce the wt crash

![Screenshot 2022-01-28 203826](https://user-images.githubusercontent.com/78153320/151595364-0759e13a-1d78-467c-87ec-e9dc1852d57c.png)

**Comment by natebarkei** [comment]
Well since you are having such a hard time reproducing it that probably is a good indicator of why it's not fixed. Pwsh is clearly reading into an uninitialized buffer somewhere under some circumstances. I also doubt a lot of developers are using ansi codes and alt screen on windows with ps.

If you watch this video, you will see the following amazing events in real time:
- It terminating the runtime 7.2.1 (trying to switch back)
- It working under PS5
- It working under 7.2.1
- Maximizing terminal, working under 7.2.1
- Closing Terminal and reopening it
- It working under 7.2.1
- Maximizing terminal
- It terminating the runtime under 7.2.1 (trying to switch to)

https://user-images.githubusercontent.com/30415407/151597417-a62941e8-67ab-462d-8815-19fd3dea7ba4.mp4

**Comment by 237dmitry** [comment]
I don't know why this bug is not reproduced. In this video pwsh is launched in the standard windows console ( `Win+R > pwsh` ).

https://user-images.githubusercontent.com/78153320/151602658-09e0a38e-c1fc-4733-9d1f-81a5ed665b3d.mp4

**Comment by natebarkei** [comment]
Has anyone else been able to try and see if they can reproduce this issue? I have been able to personally repro it on three machines so far.

**Comment by 237dmitry** [comment]
I see only one difference - you installed pwsh from the store, and I installed it from the msi package. That's probably the reason.

**Comment by elsaco** [comment]
Can't repro either:

![pwsh_issue_16818](https://user-images.githubusercontent.com/3933920/152170126-5e5696ff-e34b-4d9d-a088-37a672ccbbb4.png)

**Comment by sdwheeler** [comment]
No repro for me.

I tested PowerShell versions:
- 5.1.22621.1778
- 7.2.13
- 7.3.6
- 7.4.0-preview.4

On Windows Terminal Preview Version: 1.18.1462.0
