### ISSUE TITLE
Speed up Import-Module for MicrosoftTeams Module 3.0+

### ISSUE THREAD

**Issue by donlassini** [PowerShell/PowerShell#16828]
### Summary of the new feature / enhancement

Importing the newer version of the Teams Online PowerShell module takes a long time.

PS> Measure-Command {Import-Module microsoftteams -RequiredVersion 3.1.0}
gives results from 15 to 35 seconds in my systems (PS7.2.1, but also tested on PS5.1)

The culprit is a section of this file:
**3.1.0\net472\Microsoft.Teams.ConfigAPI.Cmdlets.psm1**:
```
  if($exportsPath) {
    Get-ChildItem -Path $exportsPath -Recurse -Include '*.ps1' -File | ForEach-Object { . $_.FullName }
    $cmdletNames = Get-ScriptCmdlet -ScriptFolder $exportsPath
    #Export-ModuleMember -Function $cmdletNames -Alias (Get-ScriptCmdlet -ScriptFolder $exportsPath -AsAlias)      
  }

```
PowerShell has to dot load each individual export file (700) and verify its signature.
On my test systems, this section takes from 14 to 30 seconds the first time I load the module in a new shell.

By combining the export files into a single file, stripping the signatures from the file, and dot-loading that single file, I could import the whole module in less than 5 seconds.

### Proposed technical implementation details (optional)

I suggest that before release, you have the build process merge the export files into 1 file, and sign it, as that should significantly speed up whenever importing the module in a new shell.

**Comment by jhoneill** [comment]
It's a good suggestion, but that module is not managed as part of this repo. 
The module's page on the PowerShell gallery says its site is 
https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams

**Comment by donlassini** [comment]
Thank you. I apologise for the inconvenience :-)
