### ISSUE TITLE
ConvertFrom-Json does not fully parse input when StrictMode is set to 2 or higher

### ISSUE THREAD

**Issue by hero101111** [PowerShell/PowerShell#16829]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following code:

```
Set-StrictMode -version latest

[string] $content = @"
[
  {
    "First": "1"
  },
  {
    "Second": "2"
  }
]
"@

$json = (ConvertFrom-Json -InputObject $content)
$json.Second
```

### Expected behavior

```console
To get `2`.
```

### Actual behavior

```console
An error that says `The property 'Second' cannot be found on this object. Verify that the property exists.`
```

### Error details

```console
This issue was exhibiting itself in the context of a much larger script and it took me a while to narrow it down to Strict Mode... 

Inspecting the issue, I discovered that setting the Strict Mode to lower than 2 causes the issue to stop appearing and the input text to get parsed correctly.

Could not find any documentation about ConvertFrom-Json changing behavior in respect to Strict Mode, so I am guessing that this is a bug.
```

### Environment data

```powershell
PowerShell 7.2.1 on Windows 11 Professional x64.

As a note, the issue also is also reproducible on Windows PowerShell.
```

**Comment by hero101111** [comment]
Additional findings: If I change the format of the input text to be more compact, e.g. 
```
Set-StrictMode -version latest

[string] $content = @"
[
  {
    "First": "1",
    "Second": "2"
  }
]
"@

$json = (ConvertFrom-Json -InputObject $content)
$json.Second
```

then the code runs successfully, and prints '2', even though Strict Mode is set to 2 or higher.

**Comment by iSazonov** [comment]
```powershell
$json=(ConvertFrom-Json -InputObject $content)
$json

First
-----
1
```
With strict mode off the code shows First - only the property presents as NoteProperty. If we call $json.Second this shows Second. So it is expected behavior if strict mode is on to do not show Second.
```powershell
$json | Get-Member

   TypeName: System.Management.Automation.PSCustomObject

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
First       NoteProperty string First=1
```

 And question is whether the cmdlet works right and do not add Second. I think it would be amazing if this cmdlet added each element of the array as a property since the array could be very large.

**Comment by jborean93** [comment]
Isn't this because of how pwsh gets a property when the object itself is a collection. With the written json you have 2 objects that are stored with their own unique properties, the equivalent pwsh code is

```powershell
$json = @(
    [PSCustomObject]@{First = "1"}
    [PSCustomObject]@{Second = "2"}
)
```

The way PowerShell's formatter works is it only displays the properties in the first object (AFAIK) and because your 2nd object doesn't have `First` then it looks like it isn't there. Strict mode is also failing because the array itself does not have a property called `First` or `Second` thus to get what you want you need to do

```powershell
Set-StrictMode -version latest

[string] $content = @"
[
  {
    "First": "1"
  },
  {
    "Second": "2"
  }
]
"@

$json = (ConvertFrom-Json -InputObject $content)
$json[1].Second # Note the [1] here
```

**Comment by zett42** [comment]
I think the behaviour is as-expected. What you are doing with `$json.Second` is called [member enumeration](https://stackoverflow.com/questions/44607064/powershell-null-file-always-generated-output-of-compare-object/44620191#44620191). Member enumeration tries to read the given property from all array elements. Without strict mode, you can get by even if not all array elements contain the given property. With strict mode on, trying to access a non-existing property is an error.

Here is a possible workaround:
~~~powershell
$json.ForEach{ if( $_ | Get-Member Second ) { $_.Second } }
~~~

By calling the array method `.ForEach`, we can implement a safeguard against non-existing properties. Using `Get-Member` we check if the property exists and only then try to read its value. Note that the output can be an array if there are more than one elements in the JSON with a `Second` member.

With strict mode you get some safety but it comes at the price of some inconvenience.

**Comment by hero101111** [comment]
Glad to see this is not a bug of ConvertFrom-Json. Thanks for the concise answers and workaround.
