### ISSUE TITLE
Remove-Alias does not provide output when using -Verbose parameter

### ISSUE THREAD

**Issue by ev-dev** [PowerShell/PowerShell#16832]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Most (if not all) of the built-in PowerShell Cmdlets that accept the [Common Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-7.2), should respond to the `-Verbose` parameter by outputting some informational message about the cmdlet's invocation to the console.

The `Set-Alias` cmdlet of the same `Microsoft.PowerShell.Utility` source, responds to the -Verbose option as expected, so it follows that the `Remove-Alias` cmdlet as part of the general 'alias interaction' category of cmdlets, should as well.

```powershell
Function Dumby-Func { echo 'testing' }

PS> Set-Alias -Name dumbfun -Value Dumby-Func -Verbose
#--> VERBOSE: Performing the operation "Set Alias" on target "Name: dfun Value: Dummy-Func".

PS> dumbfun
#--> testing

PS> Remove-Alias -Name dumbfun -Verbose
#< No Output >
```

### Expected behavior

```console
PS> Remove-Alias MyAlias -Verbose
VERBOSE: Performing the operation "Remove Alias" on target "Name: MyAlias".
```

### Actual behavior

```console
PS> Remove-Alias MyAlias -Verbose
< No Output >
```

### Environment data

```powershell
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Strictly speak a `Remove-` operation should support `-whatif` as well and Remove-Alias doesn't. 
Often the verbose output comes from the `shouldProcess`  check  so adding `-whatIf` support would fix this.
