### ISSUE TITLE
Piping from statements (using a statement as the first "command" of a pipeline)

### ISSUE THREAD

**Issue by zett42** [PowerShell/PowerShell#16830]
### Summary of the new feature / enhancement

As a script developer I would like to use statements such as `switch` at the beginning of a pipeline, e. g.:
~~~powershell
# Wishful thinking

switch -File 'input.txt' { 
    '--start--'  { $include = $true } 
    { $include } { $_ }   # Output included line
    '--end--'    { $include = $false }
} | Set-Content 'output.txt'
~~~

This would allow me to use the output of such a statement in a _streaming_ fashion, without having to collect all output into a variable first.

Unfortunately this produces a **ParserError**:
~~~
Line |
   5 |  } | Set-Content 'output.txt'        
     |    ~
     | An empty pipe element is not allowed.
~~~

Currently I have to resort to this **workaround**, which wraps the statement in a **scriptblock**:
~~~powershell
# Workaround

& { switch -File 'input.txt' { 
    '--start--'  { $include = $true } 
    { $include } { $_ }   # Output included line
    '--end--'    { $include = $false }
}} | Set-Content 'output.txt'
~~~

While this works, it is not as clean as it could be. Inexperienced users stumbling upon such code have to learn about call operator and script blocks first, before understanding the code.
 
There is also some inconsistency compared to commands and expressions. While the output of a statement can be captured in a variable, it cannot be used _directly_ in a pipeline. Commands and expressions on the other hand have both abilities.

**Comment by iSazonov** [comment]
I guess you could use follow workaround:
```powershell
{ switch -File 'input.txt' { 
    '--start--'  { $include = $true } 
    { $include } { $_ }   # Output included line
    '--end--'    { $include = $false }
}} | Set-Content 'output.txt'
```
This shows it makes no sense to allow operators in pipelines.

**Comment by zett42** [comment]
> I guess you could use follow workaround:
> 
> ```powershell
> { switch -File 'input.txt' { 
>     '--start--'  { $include = $true } 
>     { $include } { $_ }   # Output included line
>     '--end--'    { $include = $false }
> }} | Set-Content 'output.txt'
> ```
> 
> This shows it makes no sense to allow operators in pipelines.

No, you need to use the call `&` or dot sourcing `.` operator in front of the script block, otherwise you will just pipe a `ScriptBlock` object, without executing it.

**Comment by MartinGC94** [comment]
You don't need a scriptblock, a subexpression is fine:

```
$(switch -File 'input.txt' { 
    '--start--'  { $include = $true } 
    { $include } { $_ }   # Output included line
    '--end--'    { $include = $false }
}) | Set-Content 'output.txt'
```

But regardless of which workaround you choose, you lose the main benefit of the pipeline where items are streamed as they are being processed. I like the idea but I don't know how practical it is to implement.

**Comment by zett42** [comment]
> But regardless of which workaround you choose, you lose the main benefit of the pipeline where items are streamed as they are being processed.

Actually, with the scriptblock workaround, you do get the desired streaming behaviour. Here is a simpler example, that can be run as-is:
~~~powershell
'--- subexpression ---'
$( foreach( $i in 0..1 ) { Write-Host "produce $i"; $i }
) | ForEach-Object { "consume $_" }

'--- scriptblock ---'
& { foreach( $i in 0..1 ) { Write-Host "produce $i"; $i }
} | ForEach-Object { "consume $_" }
~~~

Output:
~~~
--- subexpression ---
produce 0
produce 1
consume 0
consume 1
--- scriptblock ---  
produce 0
consume 0
produce 1
consume 1
~~~

The subexpression collects all output into an array first, then passes the array elements one-by-one to the next command in the pipeline.

The scriptblock produces one element and the next command in the chain immediately consumes it - as desired.

**Comment by iSazonov** [comment]
My example was not workaround, sorry. My intention was to demonstrate we _have to convert_ a statement to something that PowerShell expects. Parser process the input a statement by statement. In your example, Parser eats `switch` statement and then start to process next statement and recognizes a pipeline with empty first element.
PowerShell language defines [Pipeline](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipelines?view=powershell-7.2) as a series of _commands_ connected by pipeline operators. PowerShell expects an expression or an command on first place. Expression has one value (@MartinGC94's example). Command can write to pipeline many values (your workaround).

So you request is to auto convert an statement to a command. It is impossible because this breaks _shell_ language. `Enter` is a statement terminator - after you type full switch statement and press `Enter` PowerShell executes the statement. Forcing users to use only ';' as statement terminator is huge breaking change.

**Comment by MartinGC94** [comment]
> It is impossible because this breaks _shell_ language. `Enter` is a statement terminator

It's not impossible, PowerShell already does this with pipelines. This is valid code in newer versions of PowerShell:
```
ls C:\
| Select -First 1
```
Also, who said it needs to support new lines? The example the OP posted had the pipe on the same line as the closing brace of the switch.

**Comment by iSazonov** [comment]
@MartinGC94 Your example uses _command_ not _statement_.

**Comment by zett42** [comment]
> So you request is to auto convert an statement to a command. It is impossible because this breaks _shell_ language. `Enter` is a statement terminator - after you type full switch statement and press `Enter` PowerShell executes the statement. Forcing users to use only ';' as statement terminator is huge breaking change.

> Also, who said it needs to support new lines? The example the OP posted had the pipe on the same line as the closing brace of the switch.

Yes. This is not different how it currently works for scriptblocks (or commands with scriptblock parameters) in the shell. When pressing Enter after `}`, you can't continue writing pipeline commands. So I don't see a braking change when converting statement to command.

~~~powershell
# This doesn't work
ForEach-Object { 42 }
| Write-Host

# But you can write
ForEach-Object { 42
} | Write-Host

# Wishful thinking - no big difference to previous sample
foreach( $i in 0..1 ) { $i
} | Write-Host
~~~

**Comment by iSazonov** [comment]
@zett42 The same - your example uses _command_ not _statement_.

**Comment by MartinGC94** [comment]
@iSazonov you are missing the point we are trying to make here.  
Your argument against adding this feature is that the interactive experience would suffer because linebreaks act as statement terminators and that people shouldn't have to use semicolons. We are saying that's not a good argument against this because A: Nobody said we needed it to work on new lines. B: If it should work on new lines then we already have an example of a good implementation of that feature.

**Comment by jhoneill** [comment]
I remember asking this question a considerable time ago, and the response was that yes it would be nice to allow for / foreach / while / do / if / switch statements to be pipeable it requires a lot of change to make it happen. Too much for the benefit. 

IIRC the grammar of PowerShell says everything is either a _statement_  (loops, conditionals, try / catch , function, filter, break, continue, return, throw etc) or a _pipeline_ which  is either an expression or a command  or one of those two piped to a command.  And of course `& {xxx}`  and  `$( xxx )`  qualify as command and expression respectively even if `xxx` is a statement.  I think it was the changing the nature of statements which was the problem.

**Comment by SeeminglyScience** [comment]
This wouldn't be impossible, so I do think the language work group should discuss it.

That said, it would be incredibly challenging. As these are language elements, the compiler generates code for the switch and switch body inline. Everything that would write to the current output pipe is written as `funcContext._outputPipe.Add(item)`.

Conversely, a pipeline is generated as a direct call to `PipelineOps.InvokePipeline` containing all of the pipeline elements (command names, arguments, etc) as raw expressions to be evaluated by that method. There is not an existing concise way of spinning up a pipeline without an initial pipeline element and adding to it's input incrementally as the method execution continues.

That's not to say that it's not possible to add that, but it would take a considerable amount of effort in what is probably the most complicated part of the code base to make happen. Plus the grammar changes that @jhoneill brings up. The workaround of `& { }` is imo pretty ideal as far as workarounds go.

So I would personally say it's not worth the effort required.

**Comment by iSazonov** [comment]
> @iSazonov you are missing the point we are trying to make here.

This request comes from the lack of a clear description in the documentation of what a command, a statement, a pipeline and an expression are and how they relate to each other. That's what I tried to explain.
As for the implementation of this feature, we could implement anything as @SeeminglyScience point. But there are two main questions. To what extent will the request fit the design and the spirit of the language? Are there scenarios where it is very important to have this? I have no doubt that both answers are negative. At the same time, the alternative is well known and simple - `& { }` - as @SeeminglyScience said " pretty ideal".

**Comment by zett42** [comment]
Thanks for the replies! This looked like a seemingly simple change (syntax-wise), but the implementation effort seems to be more than expected. I agree that the benefits do not justify this.

**Comment by iSazonov** [comment]
You could request new conceptual article in PowerShell Docs repository with explanations of fundamental PowerShell conceptions like command, expression, statement, pipeline... It is not so easy but anybody from community could write such guideline.
