### ISSUE TITLE
Suggestion: PSStyle usage for MatchInfo object

### ISSUE THREAD

**Issue by reaching-for-libra** [PowerShell/PowerShell#16845]
### Summary of the new feature / enhancement

It would be great to have more control over the results from the Select-String cmdlet.  

One use case would be to colorize the Path that is shown. Presently - the matched value is emphasized, which is great. However, if there are long paths in the results - then it can be difficult to separate the Path from the Line that displays in the output.

It would be nice to customize the color of the Emphasis, as well. 

It seems like leveraging PSStyle would be a great way to put this into action, similar to how the FileInfo options are used.

**Comment by jhoneill** [comment]
These are all good points. 
For background: 
The `matchinfo` objects that `Select-String` returns have properties for the match (giving the range to emphasize), the  line,  context either side of the line, the line number, the full path, and filename.   
Turning these into what you see displayed isn't done via the formatting data where it it would be easier to modify; but was originally in the `ToString()` method and when emphasis was added so was `ToEmphasizedString()`    
And the formatting info says to display a MatchInfo Object  use the  `ToEmphasizedString()` method.  - you can see this with 
```
Get-FormatData   Microsoft.PowerShell.Commands.MatchInfo | % FormatViewDefinition | % control | % entries | % customitems | % expression | %  value
```

Customizing what is in those methods isn't really practical, but putting what they do into the format data would work.  So I've done that. 

![image](https://user-images.githubusercontent.com/16209593/152678641-683da5d3-dfcb-472d-b82f-c394a28f6de9.png)

You can download the format xml file  from https://gist.github.com/jhoneill/84150b5ab5fe3317b0b7104e15ce3e5f 
Load it with `Update-formatData -PrependPath MatchInfo.format.ps1xml`  (Append path didn't work, to over-ride what's there it needs to be prepend). 
In an ideal world the options would extend $PsStyle but for now they're standalone. A PSobject should work but I use a hash-table. 
```
$MatchInfoPreference =@{Prefix='--> '; MatchVTSeq=$PSStyle.Underline; PathVTSeq=$PSStyle.Foreground.Yellow; NumberVTSeq=''; ContextVTSeq=$PSStyle.Foreground.BrightBlack}
```

**Comment by 237dmitry** [comment]
> $MatchInfoPreference

Can your explain where I can read about this variable? I nothing found.

**Comment by reaching-for-libra** [comment]
that's a pretty effective workaround, I hadn't thought of overriding the format files. i used to something similar in the past by overriding out-default, but that had some performance issues.

**Comment by 237dmitry** [comment]
>  I hadn't thought of overriding the format files

`Update-FormatData` does not override any files. Formatting just prepends with custom data for current session.

**Comment by reaching-for-libra** [comment]
fair enough - poor wording on my part.

**Comment by vexx32** [comment]
WG-Engine discussed this today (5/12/2022).

We agree having the ability to customise this in $PSStyle makes a lot of sense. Our opinion is that limiting this just for customising MatchInfo itself is probably a bit too narrow-scoped given the general scope of $PSStyle, but it does seem to be the correct place to put this kind of customisation.

As a result, our suggestion is that:

- $PSStyle should be augmented to include a setting for `TextEmphasis` which can be customised by users
- The default value for this property should match the current formatting sequence for MatchInfo emphasis
- MatchInfo's formatting should be updated to use the formatting sequence from $PSStyle in its formatting to permit the customisations from users to take effect there.

It is well within the realm of possibility that other cmdlets, even community modules, would be able to make use of this emphasis and get by default a level of customisability from this kind of change, which we think would be valuable.

However, the PowerShell team may not currently have the resources to take on the implementation of this change directly. As such, we've marked it Up for Grabs and would be more than happy to accept a contribution for this change if interested parties are willing to look at making the changes themselves. 🙂 

/ccing @SteveL-MSFT here as well as it falls under some of the code he's most familiar with and he may be able to provide more specific pointers on implementation details.

**Comment by jhoneill** [comment]
I agree with the opening point that PS style having a different emphasis for this, that and the other is probably not the way to go and I like that suggestion.  

If the resources _can_ be found so that people can start using this new `TextEmphasis`  asap - instead of doing 101 forms of emphasis of their own design - that would be a positive.

**Comment by SteveL-MSFT** [comment]
@vexx32 I think a general `TextEmphasis` setting would make sense if it would be used by other cmdlets/scripts.  Longer term, it may make sense to expose an extensibility mechanism for cmdlets/modules to expose their settings via `$PSStyle` to aid with discoverability (that's a much bigger change).

The changes needed to enable this would be pretty small.  You can use [CustomTableHeaderLabel](https://github.com/PowerShell/PowerShell/search?q=CustomTableHeaderLabel) to see how to expose it via `$PSStyle` and how to use it within the C# code of the cmdlet.

**Comment by vexx32** [comment]
I think if we design $PSStyle as a general-purpose common formatting scheme, folks will likely adopt it. Doubly so the more extensible and end-user customisable it is, for both accessibility purposes and user preference / environment customisations (if I recall correctly, in some MacOS installations, the default terminal colors in pwsh are _unreadable_ unless you tinker with them, for example).
