### ISSUE TITLE
ConvertTo-PSExpression: serialise objects as valid expressions (superset of Export-PowerShellDataFile / Export-Psd1)

### ISSUE THREAD

**Issue by fsackur** [PowerShell/PowerShell#16843]
### Summary of the new feature / enhancement

Valuable discussion on #11300 and #2875

There is appetite for a cmdlet that accepts a hashtable and outputs a PowerShell expression that recreates that hashtable. The linked issues discuss this specifically for writing .psd1 files - which is 99% of the problem.

I see no reason to stop there. If you generate .psd1 data, writing it to a file is the trivial part. And why limit to hashtable input? You should be able to pass any object that's legal for a hashtable value in a .psd1 and "cut out the middleman".

Not all types can be serialised safely like this. I would be delighted with a constrained solution that throws on types outside a basic set of "primitive" types, bans scriptblocks, etc.

### Use case: 

$Employer has a long tail of legacy boxes to support, and we must still use PSEXEC. We have to convert objects to strings that we can put in a command expression. (I know about XML, but the legibility is poor and it imposes extra steps.)

```
$Hashtable = @{
    'restore-healthsnapshot' = @{
        maintenanceticket = '000000-10117'
        mainttype         = 'HardwareSwapStandalone'
        hardware = @(
            @{
                Component   = 'Memory'
                SwapType    = 'Downgrade'
                TargetValue = 8
            },
            @{
                Component   = 'Cpu'
                SwapType    = 'Reseat'
            }
        )
    }
}
$Hashtable | ConvertTo-PSExpression

@{'restore-healthsnapshot' = @{mainttype = 'HardwareSwapStandalone'; maintenanceticket = '000000-10117'; hardware = @(@{TargetValue = 8; Component = 'Memory'; SwapType = 'Downgrade'}, @{SwapType = 'Reseat'; Component = 'Cpu'})}}
```

We are agnostic about brace alignment, use of newlines, etc. I can use PSScriptAnalyzer\Invoke-Formatter for the brace alignment.

**Comment by doctordns** [comment]
An interesting idea. But I am not too sure of how much of an appetite there actually is for such a cmdlet. I have never seen someone ask for this before. 

This might be a great candidate for a separate PowerShell module and posted to the PS Gallery. If there really is a sufficient appetite, then we could consider folding it into PowerShell itself.,

**Comment by jhoneill** [comment]
Agree with @doctordns  - "No-one has asked for it" isn't the same as "No-one would want it" , an initial version shared via the gallery is the way to see what appetite there is.
