### ISSUE TITLE
PowerShell installer should not uninstall prior installations; should ignore or offer option

### ISSUE THREAD

**Issue by jtmoon79** [PowerShell/PowerShell#16847]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. install an older version of PowerShell, e.g. [release 7.1.5](https://github.com/PowerShell/PowerShell/releases/tag/v7.1.5).
a. Choose a unique path, e.g. `C:\PowerShell\7.1.5` (which installs to `C:\PowerShell\7.1.5\7`).
b. Installer _PowerShell 7-x64 Setup_ settings (though these should not affect this bug occurring)
☑Add PowerShell to Path Environment Variable
☑Register Windows Event Logging Manifest
☑Enable PowerShell remoting
c. Note the contents of the installation path (default `C:\PowerShell\7.1.5\7`) has the installation files, i.e. the following command will run `C:\PowerShell\7.1.5\7\pwsh.exe`.
2. install a newer version of PowerShell, e.g. [release 7.2.1](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.1)
a. Choose a unique path, e.g. `C:\PowerShell\7.2.1` (which installs to `C:\PowerShell\7.2.1\7`).
b. Installer _PowerShell 7-x64 Setup_ settings (though these should not affect this bug occurring)
☑Add PowerShell to Path Environment Variable
☑Register Windows Event Logging Manifest
☑Enable PowerShell remoting
3. run the old version, i.e. command `C:\PowerShell\7.1.5\7\pwsh.exe`.
The command fails with:
`C:\PowerShell\7.1.5\7\pwsh.exe: The term 'C:\PowerShell\7.1.5\7\pwsh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.`
The old PowerShell installation was unexpectedly removed.

This can be reproduced in a Windows Sandbox instance.

### Expected behavior

```console
PowerShell installer should either:
- ask the User installing if they would like to remove prior PowerShell installations (if "yes" then specify which ones)
- just not remove prior PowerShell installations

System-wide unique settings, i.e. settings that can only point to one instance of PowerShell, e.g. _Enable PowerShell remoting_, should be overwritten by the last run PowerShell installer.

Some Windows users may want multiple PowerShell installations side-by-side.
Especially developers testing PowerShell scripts on multiple versions of PowerShell.
```

### Actual behavior

```console
Prior PowerShell installations are removed despite not being requested by the user.
```

### Environment data

```powershell
PS C:\PowerShell\7.2.1\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by iSazonov** [comment]
It is how MSI works and it is by-design. If you want to have some versions side-by-side you can use zip distributives.

**Comment by zett42** [comment]
If you really have to use the MSI for some reason, you could try to edit it using an MSI editor (like Orca). Remove the "Upgrade" table to prevent the MSI from removing previous versions. I don't know if that really works, as the MSI may have been designed under the assumption that previous versions are always removed, but it could be worth a try.
