### ISSUE TITLE
Please make an MSI for ARM64

### ISSUE THREAD

**Issue by mgradwohl** [PowerShell/PowerShell#16848]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

go to aka.ms/pswindows
look for an ARM64 MSI
Don't find one
Be sad

### Expected behavior

```console
An ARM64 MSI exists
```

### Actual behavior

```console
None exists
```

### Environment data

```powershell
Windows 11 latest ARM64
```

### Visuals

Not needed

**Comment by iSazonov** [comment]
Please use Distribution Support Request template to create such issues if it doesn't exist already.
