### ISSUE TITLE
Output of value from a MatchInfo type object changes the following output to terminal

### ISSUE THREAD

**Issue by thegooddoctorgonzo** [PowerShell/PowerShell#16846]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The base_select var is of type MatchInfo. Running the below code will output the values of the vars, and ALL type properties. Comment out line 4 (#$base_select) and run, and the type info output is the common properties, not all.

$base = cmd.exe /c set 
$base_select = cmd.exe /c set | Select-String -SimpleMatch "LOGONSERVER" 
$base
$base_select
$base.GetType() 
$base_select.GetType()

### Expected behavior

```console
IsPublic IsSerial Name                                     BaseType                                                                                                                                                                 
-------- -------- ----                                     --------                                                                                                                                                                 
True     True     Object[]                                 System.Array                                                                                                                                                             
True     False    MatchInfo                                System.Object
```

### Actual behavior

```console
Exploded type info for lines 5 and 6 when only common properties expected.
```

### Environment data

```powershell
Tested with ver 5 and 7. VSCode and ISE.
```

**Comment by jhoneill** [comment]
Expected behaviour. If one command outputs two kinds of object the PowerShell formatter doesn't know how to format the second object 
try
```
 $base_select.GetType(); $base_select

$base_select;  $base_select.GetType(); 
```

**Comment by thegooddoctorgonzo** [comment]
Thank you @jhoneill. I seem to remember that caveat from years ago now.
