### ISSUE TITLE
Accessibility for Win installer - Name property of focusable element must not be null

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/PowerShell#16853]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Error is produced during accessibility testing using Accessibility Insights for Windows. The Windows installer, Destination folder screen:

"The Name property of focusable element must not be Null." Section 508 502.3.1

<img width="455" alt="Screen Shot 2022-02-06 at 12 17 51 PM" src="https://user-images.githubusercontent.com/12662278/152699924-47e80e76-4f51-4ac5-84cb-c6226b2aa34d.png">
 

### Expected behavior

```console
No error produced.
```

### Actual behavior

```console
"The Name property of focusable element must not be Null." Section 508 502.3.1

<img width="455" alt="Screen Shot 2022-02-06 at 12 17 51 PM" src="https://user-images.githubusercontent.com/12662278/152699924-47e80e76-4f51-4ac5-84cb-c6226b2aa34d.png">
```

### Error details

```console
"The Name property of focusable element must not be Null." Section 508 502.3.1

<img width="455" alt="Screen Shot 2022-02-06 at 12 17 51 PM" src="https://user-images.githubusercontent.com/12662278/152699924-47e80e76-4f51-4ac5-84cb-c6226b2aa34d.png">
```

### Environment data

```powershell
Windows 11
```

**Comment by adityapatwardhan** [comment]
This dialog is generated by Wix. We would have to re-write the dialog which would be significant amount of work and prone to regressions.
