### ISSUE TITLE
Add YAML Frontmattter support to ConvertFrom-Markdown

### ISSUE THREAD

**Issue by sean-r-williams** [PowerShell/PowerShell#16857]
### Summary of the new feature / enhancement

As a contributor to a Markdown wiki repo, I would like to be able to (cleanly) parse [YAML frontmatter](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) blocks in PowerShell via `ConvertFrom-Markdown`.

While there's a workaround available by manually extracting the HeaderBlock from parsed tokens and feeding its inline content to a YAML parser, this is very counterintuitive. Moreover, YAML frontmatter is rendered to HTML in the generated document, which isn't ideal either. (Normally, Markdig suppresses HTML generation for these tokens).

### Proposed technical implementation details (optional)

This is already a native feature of Markdig, so it should be as easy as calling [`.UseYamlFrontMatter()`](https://atashbahar.com/post/2020-06-16-extract-front-matter-in-dotnet-with-markdig) on `MarkdownPipelineBuilder` before `.Build()`.

Given that these are essentially document properties, a property added to `[Microsoft.PowerShell.MarkdownRender.MarkdownInfo]` instances that extracts YAML frontmatter (if present) and deserializes to a CLR object would likely be the most sensible to use.

**Comment by sewillia-msft** [comment]
It looks like this would require augmentation to [`[MarkdownConverter]`](https://github.com/PowerShell/MarkdownRender/blob/a8cf53764a1a6f97c6fccf9269aa0dd2154fc173/src/MarkdownConverter.cs#L61), where the underlying parser pipeline is built - let me know if I should cut an issue for PowerShell/MarkdownRender as well.

**Comment by iSazonov** [comment]
Since it doesn't involve new dependencies I am ok with the enhancement PowerShell/MarkdownRender

**Comment by adityapatwardhan** [comment]
Yup I am OK with it too.
