### ISSUE TITLE
pwsh stuck on (second) launch

### ISSUE THREAD

**Issue by xrajj** [PowerShell/PowerShell#16879]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a strange behavior of pwsh. I recently reinstalled my laptop and installed powershell-core. While it launches fine if started directly after a reboot, the second attempt to launch it fails and the window shows just the cursor. The pwsh process is still running but is spawning much less sub-threads than a successful launch (monitored with procmon), log attached
[Logfile.CSV](https://github.com/PowerShell/PowerShell/files/8060690/Logfile.CSV)
.

### Expected behavior

```console
pwsh launches and shows prompt.
```

### Actual behavior

```console
pwsh process starts but console window only shows cursor, no prompt.
```

### Error details

```console
no error message
```

### Environment data

```powershell

PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by iSazonov** [comment]
Please share version you use.

**Comment by xrajj** [comment]
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by e2ibrobbins** [comment]
I am experiencing similar issues with PS v.7.2.1.  I frequently use PS from the VSCode terminal, and I get only the cursor (no prompt).  It's as if PS is hung.  If I dump the terminal session and make a new one, it seems to load fine. I have also experienced this in Windows Terminal. Previous versions did not have this problem.

**Comment by xrajj** [comment]
Issue us gone after pwsh-core update, not sure where exactly the culprit was
