### ISSUE TITLE
PowerShell v7.2.1 - Windows Update Loop

### ISSUE THREAD

**Issue by hl2guide** [PowerShell/PowerShell#16876]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run Windows Update with PowerShell installed and check for updates.

### Expected behavior

```console
PowerShell v7.2.1 installs and completes.
```

### Actual behavior

```console
Same version of PowerShell is installed and again and again.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```
Version    Caption
-------    -------
10.0.19044 Microsoft Windows 10 Pro
```

### Windows update log

Please see [this gist](https://gist.githubusercontent.com/hl2guide/dffed20e92f4346395eb2ae0cc7317cf/raw/3ff41f46d544fc72b4507bfe55819a546c726018/gistfile1.txt).

**Comment by TravisEz13** [comment]
Can you run `dir HKLM:\SOFTWARE\Microsoft\PowerShellCore -Recurse` and send the output?

**Comment by TravisEz13** [comment]
<details><summary>Update install log - 1 cycle.  Not sure why the deploymentjob is failing, but it seems unrelated.<br/></summary>
<pre>
2022/02/11 10:44:46.4991299 5300  17136 UDP             Installing update: 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200
2022/02/11 10:44:46.4991355 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Created successfully.
2022/02/11 10:44:46.5811099 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Deploy updates for Installing created successfully.
2022/02/11 10:44:46.5816881 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Created DeploymentWorker(0) successfully.
2022/02/11 10:44:46.5817235 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Created CallbackWorker(0) successfully.
2022/02/11 10:44:46.5817257 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Initialized successfully.
2022/02/11 10:44:46.5817299 5300  17136 ComApi          WU client created update deployment job 91356ACB-5B40-4330-831F-EAA5A8969F83.
2022/02/11 10:44:46.5817327 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Resume request received. Job status = Not Processed
2022/02/11 10:44:46.5817353 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Resume request processing complete. Job Status = Ongoing
2022/02/11 10:44:46.5817373 5300  17136 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : End invoked for deployment job. Job status = Ongoing
2022/02/11 10:44:46.5817789 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Beginning Installing of updates, CallerId = MoUpdateOrchestrator.
2022/02/11 10:44:46.5817811 5300  6736  UDP               Title = PowerShell v7.2.1 (x64)
2022/02/11 10:44:46.5817931 5300  6736  UDP               UpdateId = 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200
2022/02/11 10:44:46.5817939 5300  6736  UDP                 Bundles 1 updates:
2022/02/11 10:44:46.5817958 5300  6736  UDP                   5B161332-AF23-452A-AF83-CC0587E09B22.200
2022/02/11 10:44:46.5847224 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Mutex for Deployment job is created.  Mutex = 2ff883b0-b409-4328-ab13-ec77f5bdb864
2022/02/11 10:44:46.5847267 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Update 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200 started delegate invoked.
2022/02/11 10:44:46.5903948 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Installing starting for update 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200, deployable update count = 1
2022/02/11 10:44:46.5916316 5300  6736  Handler         Registering JIT COM server with CLSID {29C99218-74B8-4FA7-9CD8-2A98E9104C77} and APPID {1936360F-A279-44C6-A9EC-C9AA53971883}
2022/02/11 10:44:46.5925779 5300  6736  Handler         Successfully registered JIT COM server
2022/02/11 10:44:46.5926103 5300  6736  Handler         Switching to UpdateDeploymentProvider.dll
2022/02/11 10:44:46.6055002 20440 11512 Handler         UH: CoCreateInstance of remote handler succeeded with CLSID 29c99218-74b8-4fa7-9cd8-2a98e9104c77
2022/02/11 10:44:46.6068510 20440 11512 Handler         UH: RegisterRemoteHandlerServer suceedded
2022/02/11 10:44:46.6102768 1500  10612 DownloadManager Preparing update for install, updateId = 5B161332-AF23-452A-AF83-CC0587E09B22.200.
2022/02/11 10:44:47.5025722 1500  10612 DownloadManager ExtractUpdateFiles
2022/02/11 10:44:47.5028035 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Update 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200 deployment data prepared successfully.
2022/02/11 10:44:47.5057728 20440 14180 Handler         * START *   Command Line Install  Updates to install = 1
2022/02/11 10:44:49.4412109 20440 14180 Handler         Command line install completed. Return code = 0x00000000, Result = Succeeded, Reboot required = false
2022/02/11 10:44:49.4413410 20440 14180 Handler         * END *   Command Line Install 0x0
2022/02/11 10:44:49.4414376 5300  19024 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : NotifyClient (19024)(0) called for update id 6FF302EF-661C-4E5E-81EA-7970E9F9437D, code = Update progress, percent complete = 100
2022/02/11 10:44:49.4448545 5300  6736  WIL             *FAILED* [80070002] file = onecore\enduser\windowsupdate\client\comapi\deploymentjobhost.cpp, line = 1468
2022/02/11 10:44:49.4448581 5300  6736  WIL             *FAILED* [80070002] file = onecore\enduser\windowsupdate\client\comapi\deploymentjobhost.cpp, line = 1147
2022/02/11 10:44:49.4448870 5300  6736  UDP             Mutex will be closed.  index = 0, HANDLE = 0x000009C0
2022/02/11 10:44:49.4449016 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Method succeeded for update 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200, hrDeploy = 0x00000000
2022/02/11 10:44:49.4449065 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Update 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200 complete delegate invoked.
2022/02/11 10:44:49.4510220 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Job complete delegate invoked.
2022/02/11 10:44:49.4510268 5300  6736  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : Ending Installing updates, CallerId = MoUpdateOrchestrator, Exit code = 0x00000000
2022/02/11 10:44:49.4510729 5300  8336  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : NotifyClient (8336)(0) called for update id 6FF302EF-661C-4E5E-81EA-7970E9F9437D, code = Update success, percent complete = 100
2022/02/11 10:44:49.4510883 5300  17848 UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : WaitForEnd invoked for deployment job. Beginning the wait now!
2022/02/11 10:44:49.4511009 20440 11512 Handler         *FAILED* [800700B7] Handler process got unexpected result: 0, exiting
2022/02/11 10:44:49.4535367 1500  10612 Agent           LogHistory called. idUpdate={6FF302EF-661C-4E5E-81EA-7970E9F9437D}.200, resultMapped=0, resultUnMapped=0
2022/02/11 10:44:49.4542174 1500  10612 Agent           WU client logged Install deloyment history, caller = MoUpdateOrchestrator, update 6FF302EF-661C-4E5E-81EA-7970E9F9437D.200, classification CD5FFD1E-E932-4E3A-BF74-18BF0B1BBD83
2022/02/11 10:44:49.4543583 5300  8336  WIL             *FAILED* [80070002] file = onecore\enduser\windowsupdate\client\comapi\deploymentjobhost.cpp, line = 1468
2022/02/11 10:44:49.4543615 5300  8336  WIL             *FAILED* [80070002] file = onecore\enduser\windowsupdate\client\comapi\deploymentjobhost.cpp, line = 1075
2022/02/11 10:44:49.4543706 5300  8336  ComApi          Deployment callback complete for UpdateID = 6ff302ef-661c-4e5e-81ea-7970e9f9437d, callback code = 6, CallbackInfo cookie length = 0
2022/02/11 10:44:49.4544794 5300  8336  UDP             Deployment job Id 91356ACB-5B40-4330-831F-EAA5A8969F83 : NotifyClient (8336)(0) called with Deployment callback code = Job complete, reboot status = no reboot
</pre>
</details>

**Comment by TravisEz13** [comment]
@hl2guide , Thanks for providing the logs, for this scenario, they aren't particularly useful as they do not log the evaluation of the detection logic.  The output from the registry might help in this situation.  If you have the ability, I would recommend opening a Support case so we can get the right people from Windows involved.

**Comment by hl2guide** [comment]
@TravisEz13 

_Since the bug resulted in PowerShell being installed over 30 times, I removed PowerShell, installed it again and then disabled the integration with Windows Update._

I hope that this gets resolved in the future, but my PC is for production and needs stability and reliability.

Command:

```
PS C:\Users\Dean> dir HKLM:\SOFTWARE\Microsoft\PowerShellCore -Recurse


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore


Name                           Property
----                           --------
InstalledVersions


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore\InstalledVersions


Name                           Property
----                           --------
31ab5147-9a97-4452-8443-d9709f SemanticVersion : 7.2.2
0516e1                         InstallDir      : C:\Program Files\PowerShell\7\
                               InstallLocation : C:\Program Files\PowerShell\7\


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore


Name                           Property
----                           --------
ProgramsMenuShortcut


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore\ProgramsMenuShortcut


Name                           Property
----                           --------
7                              installed : 1
```

**Comment by TravisEz13** [comment]
Most of the detection logic is driven off the registry.  Uninstalling would have erased the state that we need to investigate.

**Comment by dub505** [comment]
I am also having this issue but with PowerShell 7.2.2 installed.
