### ISSUE TITLE
PowerShell doesn't set PATH in fish

### ISSUE THREAD

**Issue by MaxG-Enpal** [PowerShell/PowerShell#16887]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Running fish shell
Installing PowerShell over brew

### Expected behavior

```console
PowerShell should be in PATH and run by pwsh.
Fish set path different than zsh.

Instead of "export" you use "fish_add_path".
```

### Actual behavior

```console
No Path is set
```

### Environment data
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```powershell
No avalible
```

 ~  pwsh                                                               
fish: Unknown command: pwsh

**Comment by iSazonov** [comment]
Please share Environment data

**Comment by MaxG-Enpal** [comment]
> Please share Environment data

How? If im unable to run PowerShell

**Comment by MaxG-Enpal** [comment]
Done!

**Comment by iMonZ** [comment]
> We do not set the PATH when installing through HomeBrew. It seems like it should be filed as an issue for HomeBrew.

After PoweShell installer is run it installs itself to a non regularly directory. Thus a Path must be set.
This is the job of the PowerShell installer and not HomeBrew. Except if PowerShell was a formula but this is a cask with a proprietary installer.

**Comment by iMonZ** [comment]
I checked again.
The script for the PATH is inside the pkg.
Please reopen this issue again!

**Comment by iMonZ** [comment]
@msftbot reopen

**Comment by dougpuob** [comment]
Please reopen this issue! It is still there. (It seems that PWSH is trying to push us to stand on python closer.)
