### ISSUE TITLE
PlainText parameter for `Show-Markdown` Cmdlet

### ISSUE THREAD

**Issue by vedantmgoyal2009** [PowerShell/PowerShell#16882]
### Summary of the new feature / enhancement

When using the `Show-Markdown` cmdlet, a user may want to get the output as plain text and save it somewhere rather than just displaying it in the terminal. Therefore, a new cmdlet like `Render-Markdown` or just a switch parameter can be added to get the output in just plain text.

**Comment by jborean93** [comment]
I'm not too familiar with these cmdlets but having a look at the [help page for Show-Markdown](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/show-markdown?view=powershell-7.2) it seems like it either accepts a string or the path to a file to render? Why not just output the string or use `Get-Content` on the file path?

**Comment by vedantmgoyal2009** [comment]
The plain text parameter should output utf8 version of rendered markdown instead of vt100 escape sequences.

**Comment by vedantmgoyal2009** [comment]
Also, if there's any workaround to get rendered markdown in plain text, please tell 🙏🏼

**Comment by 237dmitry** [comment]
> if there's any workaround to get rendered markdown in plain text, please tell

```
$PSStyle.OutputRendering = 'Host'
Show-Markdown file.md | Out-String | Set-Content file.txt
$PSStyle.OutputRendering = 'Ansi'
```

**Comment by jhoneill** [comment]
> > if there's any workaround to get rendered markdown in plain text, please tell
> 
> ```
> $PSStyle.OutputRendering = 'Host'
> Show-Markdown file.md | Out-String | Set-Content file.txt
> $PSStyle.OutputRendering = 'Ansi'
> ```

I wonder if `Out-String` in particular might benefit from a `-OutputRendering` parameter, rather than adding one to lots of commands .  That way you avoid changing what someone had set (as above).  You don't need it using what's available now.  

```
$or = $PSStyle.OutputRendering 
$PSStyle.OutputRendering = 'PlainText'
Show-Markdown file.md >  file.txt
$PSStyle.OutputRendering = $or
```

**Comment by 237dmitry** [comment]
> I wonder if Out-String in particular might benefit from a -OutputRendering parameter

That would certainly be good. New crutches, more elegant. But people will still ask questions why esc-sequences are output to the file, because for them this is wild behavior that they have never met anywhere.
