### ISSUE TITLE
Silent Update removes context menu entry if previously added

### ISSUE THREAD

**Issue by awsr** [PowerShell/PowerShell#16886]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Have PowerShell installed with the context menu entry added from the `Add 'Run with PowerShell 7' context menu for PowerShell files` option in the installer. *
2. Update PowerShell to the latest version via Windows Update.

### Expected behavior

Installer sees existing "Run with PowerShell 7" context menu entry and retains it after the update.

### Actual behavior

Installer removes context menu entry and installs the new version with default settings only (without context menu entry).

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

\* Referring to this option:
![Installer option](https://user-images.githubusercontent.com/27423064/99889643-1ddd1a00-2c4f-11eb-8ed4-d7b86a747878.png)

**Comment by iSazonov** [comment]
Do you ask the option must be `On` if previously it was `On`?

**Comment by awsr** [comment]
The option was on. That image is just an example from a different issue that I used to show which option I'm referring to.

**Comment by TravisEz13** [comment]
Does this happen through any silent MSI upgrade?

**Comment by ignant1** [comment]
Upgrading through winget removes the context menu. 

Getting it from the Windows Store, it installs a separate version if you previously installed via other means. It also does not give you the option add that context menu on the initial installation via the Windows Store, so there is no way to see if upgrading it remove it from the menu.

**Comment by ignant1** [comment]
I just installed Visual Studios 2019 which also added "Developer PowerShell for VS 2019" and now the "Run with PowerShell 7" Context Menu is gone. On top of this, uninstalling PowerShell 7 and then reinstalling it and checking the box to add the context menu still does not add it again.

**Comment by pat0026** [comment]
Still encountered this issue after updating from 7.2.4 to 7.2.5 via windows update. The context menu was gone, this could be fixed by manually tampering with registries but normal users should avoid this. Hope this issue will soon be fixed.

**Comment by marcoz-tsn** [comment]
> Still encountered this issue after updating from 7.2.4 to 7.2.5 via windows update. The context menu was gone, this could be fixed by manually tampering with registries but normal users should avoid this. Hope this issue will soon be fixed.

same problem here... !

**Comment by dgiesselbach** [comment]
Bug is still existing! We are running 7.2.4 (installed via msi with ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL=1 ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1) and after updating via windows update to 7.2.6 context menu is away!

Is a fix in progress?

**Comment by RanMLiang** [comment]
Have the same issue.
After updating Powershell 7 via Windows updates, the options for PoweShell 7 are disappeared on the system right-click menu list.
Currently, I have to manually download and install the latest verision of PoweShell 7 every time instead of using Windows updates.

**Comment by MdHusainhfz** [comment]
Same issue,
I installed Powershell 7.2.7 with context menu option,
then updated Windows 10 from 21H2 to 22H2, and Powershell context menu disappeared.

**Comment by DesertBear** [comment]
Still happening with 7.3.1.

I've been manually updating PowerShell 7 from the GitHub MSI installer to avoid this issue, however today I installed the "Patch Tuesday" updates and it automatically updated from PowerShell from 7.3.0 to 7.3.1 at the same time.  Therefore, I've now lost the right-click "Run with PowerShell 7" context menu.

**Comment by RealLKrieger** [comment]
For me the same as in the post before. I started a deployment of 7.3.0 on a decent amount of systems with the context enabled. Does work until the auto update from wsus with 7.3.1 rolls over, then its gone.

**Comment by Bidthedog** [comment]
I just did a reboot and noticed this has happened to me too. I use this context menu constantly. Win 11 on PS v7.3.3. here.

It's not entirely clear what has been installed to make this happen; I assume a windows update or a background update to PowerShell itself?

**Comment by patriml** [comment]
Silent update to PowerShell 7.3.5 on Windows 10.0.19045 removed context menu entries for me too.

**Comment by aleferri** [comment]
Keep happening to 7.3.6. Please resolve, or be honest and just disable the option of updating automatically as it doesn't work and there is no point on fooling the users.

**Comment by DreamCatcher13** [comment]
disappeared for me too, after silent update :( win 10, powershell 7.3.7

**Comment by awsr** [comment]
An interesting update. I've found that if I manually add the registry entries for the "Run With PowerShell 7" command instead of re-running the installer to add it, the setting will persist through upgrades. (This does mean I'll have to manually change the references to PowerShell 8 if this is still an issue by the time it comes out.)

The relevant lines for ALL of the registry entries in the installer setup are at: https://github.com/PowerShell/PowerShell/blob/dab6ca28f545d2c15dc4cc9e5121daf3b24b47bd/assets/wix/Product.wxs#L234-L283 and https://github.com/PowerShell/PowerShell/blob/dab6ca28f545d2c15dc4cc9e5121daf3b24b47bd/assets/wix/Product.wxs#L284-L294

I only use the "Run With PowerShell" feature, so I don't know if this also applies to the "Open With PowerShell" feature, but you can at least re-add the "Run With..." entry with the following registry file (from Windows 10 and **PowerShell 7x64**):
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Microsoft.PowerShellScript.1\Shell\PowerShell7x64]
"Icon"="C:\\Program Files\\PowerShell\\7\\pwsh.exe"
"MUIVerb"="Run with PowerShell 7"

[HKEY_CLASSES_ROOT\Microsoft.PowerShellScript.1\Shell\PowerShell7x64\Command]
@="C:\\Program Files\\PowerShell\\7\\pwsh.exe -Command \"$host.UI.RawUI.WindowTitle = 'PowerShell 7 (x64)'; if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & '%1'\""
```

**Comment by ceztko** [comment]
It just happened to me with Windows Update silent installation of 7.4.2.

**Comment by reduckted** [comment]
Just a small clarification on what to expect once that PR is merged. This problem will still exist for the _first_ version that contains the fix. The installer for that version will remember the options you choose. The version _after that_ will use those settings that were remembered.
