### ISSUE TITLE
Microsoft.PowerShell.SDK - AddScript does not work w/ script path or nested Powershell files

### ISSUE THREAD

**Issue by cmeyertons** [PowerShell/PowerShell#16893]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am attempting to invoke a Powershell file via c# using the Microsoft.PowerShell.SDK (7.2.1, net6)

I can only get back the return value if AddScript is passed the raw script text.  However, that method starts failing when nested Powershell files get used.

The [AddScript documentation](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addscript?view=powershellsdk-7.0.0) appears incorrect -- it only referes to AddCommand in the examples.

I was looking at the [Powershell.AddCommand(CommandInfo info](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addcommand?view=powershellsdk-7.0.0#overloads) overload, but all the constructors of those implementations have been marked `internal`, so that public overload does not allow anything to be passed into it? :/

I could only find a similar example [here](https://www.codelocker.net/p/5232/csharp-run-powershell-script-from-csharp-dotnet-core/)

C# code
```csharp
private object TestPowershell(string path)
    {
        var ps = PowerShell.Create();

        var text = File.ReadAllText(path);

        ps = ps
            // .AddScript(text) <- this works when using raw settings.  Nested powershell files does not
            // .AddCommand(path) <- does not work at all.
            .AddScript(path) // <- does not work at all.
            .AddParameter("Env", "local")
        ;


        var psResult = ps.Invoke();

        return psResult;
    }
```

simple powershell file:
```ps
Param (
    [string]$Env = "local"
)

$settings = @{
    Test = "hi!"
}

$settings
```
 
nested powershell file (invokes the one above)
```ps
Param (
    [string]$Env = "local"
)

return (& "$PSScriptRoot\..\local\Settings.ps1")
```

### Expected behavior

```console
Can pass in script path via AddScript + nested powershell files work the same as invoked from terminal
```

### Actual behavior

```console
When using the script path (or a nested script is involved), the result set is always empty.

Raw script text w/ just a simple file works fine (so I know I'm at least close!)
```

### Environment data

```powershell
<TargetFramework>net6.0</TargetFramework>
<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.1" />
```

**Comment by iSazonov** [comment]
> The [AddScript documentation](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.addscript?view=powershellsdk-7.0.0) appears incorrect -- it only referes to AddCommand in the examples.

I suggest you to open new issue in PowerShell Docs repository. https://github.com/MicrosoftDocs/PowerShell-Docs

**Comment by iSazonov** [comment]
Working example for AddScript https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/adding-and-invoking-commands?view=powershell-7.2#addscript

**Comment by cmeyertons** [comment]
@iSazonov  you are a life saver!  Was banging my head against the wall on that one for a while.

Would it be worth documenting this code path?  It seems like a pretty common pattern to invoke an existing .ps1 file from .NET core.  I don't see any samples in the [MSDN docs](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/host-application-samples?view=powershell-7.2) for this use case

For those that come across this, here is my final working example for running an external script using the Powershell SDK:

```csharp
private object TestPowershell(string path)
    {
        // not required, but nice to do if you don't want the execution policy to block
        var iss = InitialSessionState.CreateDefault();
        iss.ExecutionPolicy = Microsoft.PowerShell.ExecutionPolicy.Bypass;

        using var runspace = RunspaceFactory.CreateRunspace(iss);
        runspace.Open();
        using var pipeline = runspace.CreatePipeline();

        var cmd = new Command(path);
        cmd.Parameters.Add("Env", "local");

        pipeline.Commands.Add(cmd);

        return pipeline.Invoke();
    }
```

**Comment by cmeyertons** [comment]
Done on my side! Feel free to close if desired!

**Comment by iSazonov** [comment]
We keep the issue opened to fix docs in code https://github.com/PowerShell/PowerShell/issues/16893#issuecomment-1043035393

**Comment by sebsub321** [comment]
> <img alt="" width="48" src="https://camo.githubusercontent.com/8c4c7e371885737755956675db0958a29697fa30d1b46dd0eb3626f2b93adf86/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f6d656469612f6c6f676f732f6c6f676f2d706f7765727368656c6c2d736f6369616c2e706e67">
> **[Adding and invoking commands - PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/developer/hosting/adding-and-invoking-commands)**
> Adding and invoking commands

**Comment by daxian-dbw** [comment]
The doc issue is tracked by https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8594
