### ISSUE TITLE
[Issue-question] Two consecutive empty variables break a pipeline (Strange pipeline behavior)

### ISSUE THREAD

**Issue by scriptingstudio** [PowerShell/PowerShell#16909]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

What value will a variable get in expression like this?
```powershell
$var1 = if (1 -eq 2) {'value'} # $null?
$var1 -eq $null
True
```
### Test
```powershell
# implicit initialization
$var1 = if (1 -eq 2) {'value'}
$var2 = if (1 -eq 2) {'value'}
$var1,$var2 # output: none

$var1,$var2,'1111' # output: 1111
1111

$var1,$var2,'1111' | Where-Object {$_} # output: none

$var1,2222,$var2,'1111' | Where-Object {$_} # output: 2222
2222

2222,$var1,$var2,'1111' | Where-Object {$_} # output: 2222
2222

# workaround: break a "chain"
"$var1",$var2,'1111' | Where-Object {$_} # output: 1111
1111
2222,"$var1",$var2,'1111' | Where-Object {$_} # output: 2222 1111
2222
1111
"$var1",2222,$var2,'1111' | Where-Object {$_} # output: 2222 1111
2222
1111

# explicit initialization
remove-variable var1,var2
$var1 = if (1 -eq 2) {'value'} else {$null}
$var2 = if (1 -eq 2) {'value'} else {$null}
$var1,$var2,'1111' | Where-Object {$_} # output: 1111
1111
2222,$var1,$var2,'1111' | Where-Object {$_} # output: 2222 1111
2222
1111
```

In both cases of assignment the value is `$null` but a pipeline works differently.
Is it a bug or feature?

### Expected behavior

```console
$var1,$var2,'1111' | Where-Object {$_}
1111
```

### Actual behavior

```console
$var1,$var2,'1111' | Where-Object {$_} # output: none
```

### Error details

```console
none
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
When a variable is created and no value is assigned, it's not technically $null here, it's the `[AutomationNull]::Value`. I'm not sure if this is by design or not, but it's an interesting case.

@daxian-dbw might wanna give this a look over, it's a bit of an edge case but still feasibly something folks can run into from time to time.

**Comment by scriptingstudio** [comment]
Interestingly, there are no issues with undefinded variables
```powershell
$v11111111,$v2222222,1111 | Where-Object {$_}
1111
```

**Comment by vexx32** [comment]
Yep. Confusingly, variables that don't exist create a "true" `$null` value, whereas initialised variables that don't have a valid value are the automationnull.

I would be inclined to say we should have the latter _also_ be initialised to `$null` instead of persisting the automationnull value (which primarily exists for internal engine pipeline implementation reasons anyway). Unsure if that would be likely to break things, but it would make the experience more consistent.

**Comment by iSazonov** [comment]
It seems we already have/had an issue like that.

**Comment by scriptingstudio** [comment]
After additional investigation of `AutomationNull`  I have found the explanation of empty null
https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null?view=powershell-7.2#empty-null
Turns out this is by design but it is confusing and is breaking pipeline.

**Comment by iSazonov** [comment]
> Turns out this is by design but it is confusing and is breaking pipeline.

If I remember right we already discussed this in the repo and changing this would be more breaking and confusing.

**Comment by daxian-dbw** [comment]
@iSazonov Can you point us to the discussion about this issue (or a similar issue)?

**Comment by iSazonov** [comment]
> @iSazonov Can you point us to the discussion about this issue (or a similar issue)?

Oh, pity my AI :-)

I think that #9997 was the grandest discussion. With PowerShell Committee consideration :-)

**Comment by vexx32** [comment]
That issue is a mite different, though related for sure.

**Comment by iSazonov** [comment]
Dup #14920
