### ISSUE TITLE
Microsoft.Powershell.Sdk - Script hangs when running from runtime-specific published binary

### ISSUE THREAD

**Issue by genriquez** [PowerShell/PowerShell#16901]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- Unzip test project to some folder
- Publish binaries `dotnet publish PwshTest.csproj -o .\publish --configuration Release --runtime win10-x64`
- Run PwshTest.exe

### Expected behavior

```console
Application exits
```

### Actual behavior

```console
Application hangs
```

### Error details

Seems that creating an instance of `WScript.Shell` is causing the PS sdk library to hang (looping, since there is cpu usage going on). This is specific to using the `--runtime` parameter on publish. Publishing without specifying runtime does not hang, and running from sources in Debug and Release does not hang either. Removing creation of `WScript.Shell` from the script file makes it pass without issues.

Tested in SDK 7.1.5, the latest release for Net5 applications.

### Environment data

```powershell
<TargetFramework>net5.0-windows10.0.19041</TargetFramework>
<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.1.5" />
```

### Visuals

Test solution and script: [PwshTest.zip](https://github.com/PowerShell/PowerShell/files/8111031/PwshTest.zip)

**Comment by fMichaleczek** [comment]
@genriquez change your target framework to net5.0 and use this runtimeidentifier.

https://github.com/PowerShell/PowerShell/blob/31c14f2ad3714c262108acf6613ab023bc971012/src/powershell-win-core/powershell-win-core.csproj#L11

Some native dependencies are not copied to the build (MMI) if you are specifying Windows 10 as a target framework. (Win vs Win7 vs Win10 Runtime folder)

**Comment by genriquez** [comment]
Some findings with the test project (note that publish folder was deleted for each case, to avoid false positives):

- Changing to net5.0 target framework and those runtime identifiers still yields hanging binaries if using `--runtime win10-x64`
- Further changing `RuntimeIdentifiers` to `win10-x64` and keeping `--runtime win10-x64` yields working binaries still yields hanging binaries
- Compiling without `--runtime` flag yields working binaries in both previous steps, but that was already working without doing any changes

**Comment by genriquez** [comment]
@fMichaleczek Tested with these settings but still getting hanging binaries:

```
<TargetFramework>net5.0</TargetFramework>
<RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers> 
```

`dotnet publish PwshTest.csproj -o .\publish --configuration Release --runtime win7-x64`

**Comment by fMichaleczek** [comment]
@genriquez i can't help you more without more informations.

**Comment by genriquez** [comment]
Is there anything else I can provide @fMichaleczek? The test project is attached to the original post.

Removing the `--runtime` parameter is a valid workaround for us, so we can just leave this open for someone else to take a stab at it.

**Comment by fMichaleczek** [comment]
@genriquez I will try later on the same version and give you a feedback if I found something.

**Comment by genriquez** [comment]
@iSazonov the issue was not resolved. Can we get this bug re-opened?

**Comment by iSazonov** [comment]
@genriquez It is not a problem in PowerShell SDK. It is a problem with your project.

I modified your project and script, added output and did some experiments
[PwshTest.zip](https://github.com/PowerShell/PowerShell/files/8175258/PwshTest.zip)

Command line `dotnet publish PwshTest.csproj -o .\publish --configuration Release --runtime win7-x64 --self-contained`
See results below. 

![image](https://user-images.githubusercontent.com/22290914/156503307-87599274-e6b9-4143-a156-c7861e5e145a.png)

**Comment by genriquez** [comment]
@iSazonov Oh, so the net5 version of the package is no longer maintained?

**Comment by iSazonov** [comment]
Supported. (You must use the same .Net version for you project and PowerShell SDK. I used latest I have on my notebook.)

**Comment by genriquez** [comment]
If the proposed solution still requires to copy modules folder manually, I would still consider it a work around. Is there a separate nuget we can include to automate this?

**Comment by iSazonov** [comment]
@daxian-dbw Could you please answer?

**Comment by daxian-dbw** [comment]
See the explanation here: https://github.com/PowerShell/PowerShell/issues/16525#issuecomment-983108982

As for the hang, it's because the built-in module folder is not deployed along with your project. It was fixed by https://github.com/PowerShell/PowerShell/pull/16628 to detect that a built-in module is missing.

**Comment by fMichaleczek** [comment]
@daxian-dbw Have you planned a backport for the LTS? It's a pretty annoying bug and I'm happy with your fix on 7.3.

**Comment by daxian-dbw** [comment]
@fMichaleczek Unfortunately, LTS only accepts security and regression fixes, so this fix cannot be ported to 7.2.x.

**Comment by genriquez** [comment]
@daxian-dbw I guess a port to 7.1.x won't be happening either (we are still running on net5)? Having it error out certainly helps out a lot. As for the missing built-in modules, is there a reason why publishing without specifying a runtime somehow copies them (or the app does not hang for some other reason), but when I specify a win-x64 runtime it doesn't work?

**Comment by daxian-dbw** [comment]
I think porting to 7.1.x won't happen too. See https://github.com/PowerShell/PowerShell/issues/16525#issuecomment-983108982 for why it works this way. It's an unfortunate tradeoff, because there was no way (at least at the time when doing this) for a NuGet package to choose where to deploy some content files depending on whether or not `-runtime` is specified.
