### ISSUE TITLE
Get-ScheduledTask - Not working on Windows 11 21H2 image on Azure VM

### ISSUE THREAD

**Issue by kiazhi** [PowerShell/PowerShell#16905]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Provision an Azure VM with Windows 11 21H2 image
2. Launch PowerShell
3. Input the command below.
```powershell
Get-ScheduledTask
```

### Expected behavior

```console
Get-ScheduledTask Cmdlet should returns all the scheduled tasks on Windows 11.
```

### Actual behavior

```console
Experience Error 0x80070002
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/13409063/155283451-25f8637f-977f-40cd-95d5-f9000ac08400.png">

**Comment by iSazonov** [comment]
> 5.1.22000.282

The repository is for only PowerShell 7+. For Windows PowerShell please use Windows Feedback tool to report issues.

**Comment by kasini3000** [comment]
win11 vm 无法重现问题，上述命令正常。建议格式化重装。
msdn版
文件: zh-cn_windows_11_business_editions_updated_feb_2022_x64_dvd_72b0d7e6.iso
SHA-256: 59228436F87E793CCDA9C23400FFE821106983F6B0BE2570F1ABF69BD2D4F92A
ed2k://|file|zh-cn_windows_11_business_editions_updated_feb_2022_x64_dvd_72b0d7e6.iso|5555443712|6A2F44464A19109385BE33D1965333C2|/
