### ISSUE TITLE
Can i use powershell SDK remote  in asp.net core docker container?

### ISSUE THREAD

**Issue by guijunhua** [PowerShell/PowerShell#16903]
### Summary of the new feature / enhancement

Powershell SDK local is worked in docker containter.
buy when i try to create remote runspace the code return error blow 
![image](https://user-images.githubusercontent.com/32589055/155270081-17a21846-4273-4add-a247-b41536a1c8bc.png)

how can i use remote run space in docker ?

**Comment by guijunhua** [comment]
any one ??

**Comment by iSazonov** [comment]
I guess you use generic target in your project - try `win7-x64`.

**Comment by guijunhua** [comment]
> 
I want use in docker ,is it realy work ?

**Comment by PaulHigin** [comment]
@WG-Remoting
This does not appear to be related to WSMan/OMI on non-Windows platforms.  Instead, it sounds from the error like WinRM remoting is being attempted on a Windows docker image that does not include WinRM (WSMan).  If so, the solution is to have a docker image that includes WSMan client.  I agree that another solution may be to use SSH remoting, but only if the docker image has SSH client.

This does not appear to be a remoting issue but a docker image issue.
