### ISSUE TITLE
Invoke-WebRequest is unexpectedly slow

### ISSUE THREAD

**Issue by ruvceskistefan** [PowerShell/PowerShell#16914]
### Summary of the new feature / enhancement

The execution of the `Invoke-WebRequest` call is unexpectedly slow.

For example, when downloading a GitHub Actions Runner project, the use of `Invoke-WebRequest` is very slow.
This call:

`Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.285.1/actions-runner-win-x64-2.285.1.zip -OutFile actions-runner-win-x64-2.285.1.zip`

is significantly slower than this

`(New-Object Net.WebClient).DownloadFile("https://github.com/actions/runner/releases/download/v2.285.1/actions-runner-win-x64-2.285.1.zip", "$PWD\actions-runner-win-x64-2.285.1.zip")`

The performance difference with this ~70mb file (on my machine)?
`Invoke-WebRequest`: 154.4 seconds 
`Net.WebClient`: 3.41 seconds  

Can you investigate this problem and possibly fix the underlying commands so that the `Invoke-WebRequest` is faster?

**Comment by iSazonov** [comment]
I can not reproduce
![image](https://user-images.githubusercontent.com/22290914/155579439-58791da7-1198-4f4f-a874-98386e7eed6c.png)

**Comment by jborean93** [comment]
If you are using Windows PowerShell (5.1) then this is a known problem with how it uses the progress stream. You can set `$ProgressPreference = 'SilentlyContinue'`. This particular problem was fixed with PowerShell (7+) so you shouldn't see a slowdown on this version and higher.

**Comment by ruvceskistefan** [comment]
I assumed the problem was refreshing the progress bar, thanks for the explanation. I will close this issue, thank you!

**Comment by rdp** [comment]
Based on how common 5 is, might be nice to fix there :) :)

**Comment by valinet** [comment]
Why can't this fix be backported to the Windows PowerShell version as well? Why has this been a bug in the first place? How is one able to code something that badly and have it pass through QA and ship in so many products in such a broken state, it's mind blowing...

**Comment by keithzg** [comment]
> Why can't this fix be backported to the Windows PowerShell version as well? Why has this been a bug in the first place? How is one able to code something that badly and have it pass through QA and ship in so many products in such a broken state, it's mind blowing...

Welcome to using corporate software products! I gather you're new here, let me show you around . . .
