### ISSUE TITLE
Release Process: Don't update the current-release metadata until the release binaries are actually available

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16920]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`PowerShell 7.3.0-preview.2` was released on 24 Feb 2022, yet the metadata denoting the current preview release was updated _days before_, breaking both the links at https://github.com/PowerShell/PowerShell/blob/master/README.md and workflows based on relying on that metadata.

### Expected behavior

In the future, please ensure that the metadata isn't updated until _after_ the release artifacts referenced are actually available.

### Actual behavior

Broken links and workflows.

### Environment data

```powershell
PowerShell Core 7.3.0-preview.2
```

**Comment by adityapatwardhan** [comment]
This was a one-time error during the release process. It has been correctly documented in our internal release process documentation now.
