### ISSUE TITLE
PowerShell Preview not updating through Microsoft Update

### ISSUE THREAD

**Issue by edge261** [PowerShell/PowerShell#16927]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Click to "check for updates" on a Windows 11 Insider build.

### Expected behavior

```console
PowerShell should update silently through Microsoft Update.
```

### Actual behavior

```console
No updates appears on Windows Update, but it appears on the Terminal page.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.22563
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.22563 Microsoft Windows 11 Pro
```

### Windows update log

```markdown
n-a
```

### Visuals

![image](https://user-images.githubusercontent.com/79731301/155817873-bfbe45c4-93d6-47d5-8ec9-a3eccb7b67a5.png)

**Comment by TravisEz13** [comment]
We were not able to publish preview.2 to MU.  preview.3 should be out on MU around 4/4/2022
