### ISSUE TITLE
Inconsistent Get-Date behavior between windows powershell and powershellcore

### ISSUE THREAD

**Issue by TheOnlyWei** [PowerShell/PowerShell#16928]
### Summary of the new feature / enhancement

As a user, I want Get-Date to be consistent between windows powershell and powershellcore so I don't have to maintain separate, customized scripts for windows powershell and powershellcore.

If you run the following command, you get a decimal value in windows powershell and an integer value in powershellcore.
`(Get-Date -Date (Get-Date).AddSeconds(-60).ToUniversalTime() -UFormat %s)`

This should be consistent between the two so I can use the same script between windows powershell and powershell core.

**Comment by MartinGC94** [comment]
Seems like an intentional change made here: https://github.com/PowerShell/PowerShell/pull/4805 for the sake of consistency with the standard.  
If you want your script to work in both versions without having to add a version check condition you can parse it as a double and then round it `[System.Math]::Round([double]::Parse((Get-Date -UFormat %s)))`

**Comment by jhoneill** [comment]
`[int](Get-Date -Date (Get-Date).AddSeconds(-60).ToUniversalTime() -UFormat %s)`
or   
`[decimal](Get-Date -Date (Get-Date).AddSeconds(-60).ToUniversalTime() -UFormat %s)`


Will work in a script that runs on both versions.  Most real world scripts won't be affected by the difference

**Comment by TheOnlyWei** [comment]
@MartinGC94 Okay, so I gather that powershell 5 is not following the standard? Any plans to update that? My main concern was understanding why it is different, and whether powershell 5 or powershell 7 is in the wrong.

**Comment by iSazonov** [comment]
> Any plans to update that?

No, Windows PowerShell gets only critical (security) updates, all new features will be only in PowerShell 7+.
