### ISSUE TITLE
 pdfgrep on PowerShell :: file name not shown 

### ISSUE THREAD

**Issue by francesco1119** [PowerShell/PowerShell#16925]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm using `pdfgrep  `on WSL2 and while on Windows Terminal is working well on PowerShell is not printing the full output. 
At the beginning I guessed it was because of the colour of the output and PowerShell background being blue but now I'm not sure

**STEPS**

1. `apt-get install pdfgrep `
2. `pdfgrep -HinR 'SearchedWord' TargetFolder/` 

### Expected Behavior

In WSL2 on Terminal you see the file name: 

![image](https://user-images.githubusercontent.com/3397477/154648853-d24437a6-3e9f-43af-8f5b-f69ba88a1bed.png)

### Actual Behavior

In WSL2 on PowerShell you don't see the file name: 

![image](https://user-images.githubusercontent.com/3397477/154648903-483330bd-787f-45ce-8c39-4cf53b0e5703.png)

### Expected behavior

```console
PowerShell should print the whole output
```

### Actual behavior

```console
Windows Terminal is printing the whole output but not PowerShell
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

See pictures above

**Comment by iSazonov** [comment]
Try to set `TERM` env variable to `dump` or set `NO_COLOR` env variable to 1.

**Comment by jhoneill** [comment]
I think this is a PowerShell 5 problem in the traditional windows console. 

By default Windows PowerShell changes the console colour "Dark Magenta" in the old-style Windows console  to a shade of blue, and makes that the background colour. 
Looking at the screen shots, the file name is being output in .... Dark Magenta. 

if you use $host.UI.RawUI.BackgroundColor = "black"  and then run the command you'll see the text - to get it display in magenta you need to go to the console properties and set the 6th colour back to a dark magenta. 

If you use PowerShell core (6 or 7) or if you run Windows PowerShell in the new Windows Terminal the text will be visible (although not very visible on Windows PowerShell's blue background).

**Comment by francesco1119** [comment]
"Dark Magenta" was the problem.

`$host.UI.RawUI.BackgroundColor = "black"` didn't work because you switch to black but then it comes back to blue when you start WSL.

The solution was to install the latest PowerShell through `winget install --id Microsoft.Powershell --source winget`.

Fixed!
