### ISSUE TITLE
Resolve-path doesn't strip quotes...

### ISSUE THREAD

**Issue by wm2015email** [PowerShell/PowerShell#16933]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

ISSUE #1
----------

I think if you want to make powershell easy to use, then the shell should automatically strip quotes around files when calling resolve-path... its always the case that calls to things get nested and its complicated to think if you need quotes or not... my opinion is that powershell resolve-path should always strip quotes... to help users and make it easier to use...

# GOOD CASE
PS> $x = "C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\"
PS> $x
C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\
PS> Resolve-Path -Path $x

Path
----
C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\

# BAD CASE - No automatic quote stripping from files with quotes....
PS> $x = "`"C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\`""
PS> $p = Resolve-Path -Path $x
Resolve-Path : Cannot find drive. A drive with the name '"C' does not exist.
At line:1 char:6
+ $p = Resolve-Path -Path $x
+      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ("C:String) [Resolve-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

----------
ISSUE #2:

Actually... While I'm complaining... I don't like that resolve-path doesn't have an option to resolve a path that doesn't exist yet... always need to write this bogus code bullcrap code to get what i want:.

$pathfix = Resolve-Path -Path $file -ErrorAction SilentlyContinue -ErrorVariable ev
if (-not($pathfix)) {
    $pathfix - $ev[0].TargetObject
}

This is complete bullcrap... give use a switch to resolve paths that doesn't already exist yet....  it always happens that i need to resolve a path to a place where i;m creating a new file that doens't exist yet.... why not this instead:

PS> $pathfix = Resolve-Path -Path $file -NoRequireExists

now its nice and easy.....

### Expected behavior

```console
PS> $x = "`"C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\`""
PS> $p = Resolve-Path -Path $x
PS> Resolve-Path -Path $x

Path
----
C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\
```

### Actual behavior

```console
# BAD CASE - No automatic quote stripping from files with quotes....
PS> $x = "`"C:\Users\wpmoore\Desktop\VSC_MDU-R\tb\TB_VSC_B2_SRC\AIC Calibration Strobe Signal\`""
PS> $p = Resolve-Path -Path $x
Resolve-Path : Cannot find drive. A drive with the name '"C' does not exist.
At line:1 char:6
+ $p = Resolve-Path -Path $x
+      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ("C:String) [Resolve-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
```

### Error details

```console
Resolve-Path : Cannot find drive. A drive with the name '"C' does not exist.
At line:1 char:6
+ $p = Resolve-Path -Path $x
+      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ("C:String) [Resolve-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
```

### Environment data

```powershell
Resolve-Path : Cannot find drive. A drive with the name '"C' does not exist.
At line:1 char:6
+ $p = Resolve-Path -Path $x
+      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ("C:String) [Resolve-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
```

### Visuals

N/A

**Comment by iSazonov** [comment]
Please split to 2 issues.
