### ISSUE TITLE
Tab completion type inference does not account for generic method invocation with explicit type parameters

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#16934]
### Steps to reproduce

```powershell
TabExpansion2 -inputScript ($s = '[array]::Empty[int]().') -cursorColumn $s.Length |
    % CompletionMatches |
    select -f 5
```

### Expected behavior

```console
CompletionText ListItemText   ResultType ToolTip
-------------- ------------   ---------- -------
Count          Count            Property int Count { get; }
IsFixedSize    IsFixedSize      Property bool IsFixedSize { get; }
IsReadOnly     IsReadOnly       Property bool IsReadOnly { get; }
IsSynchronized IsSynchronized   Property bool IsSynchronized { get; }
Length         Length           Property int Length { get; }
```

### Actual behavior

```console
No results
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.2
PSEdition                      Core
GitCommitId                    7.3.0-preview.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
I'm working on this now, I've gotten it to work with the example in the OP but I'm having some trouble getting it to work with this example:

```
[System.Collections.Generic.List[int]]$list = @( 1, 2, 3, 4, 5 )
$result = [System.Linq.Enumerable]::Select[int, float](
    $list,
    [Func[int, float]]{
        param($item)
        [math]::Pow($item, 3)
    }
)
$result.<Tab>
```
The type inference sees it as an:

```
System.Collections.Generic.IEnumerable`1[[System.Single, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```
while the actual type after running it is:
```
System.Linq.Enumerable+SelectListIterator`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Single, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```

I've just updated the method here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs#L1702 to also have a parameter for the generic type arguments and then I simply run this: `var returnType = methodInfo.MakeGenericMethod(genericTypes).ReturnType;` to get the return type.  
What am I missing here?

**Comment by vexx32** [comment]
Type inference is seeing the static type definition -- see https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?view=net-6.0

It's declared as the IEnumerable type. The runtime (concrete) type that you see after actually running it is just some probably internally-visible-only type that implements that IEnumerable interface. Probably not quite as important as it might change between .NET versions anyway, and it's not likely that folks will be expecting to see any methods specifically from that type. Even in C# you only deal with it as the IEnumerable, the underlying types tend to be a bit opaque.

**Comment by SeeminglyScience** [comment]
Yeah unfortunately that seems like just another bug. Ideally it'd give you members for `float` but this also returns very little:

```powershell
([System.Collections.Generic.IEnumerable[float]]$null).<tab>
```

So your change works! And there's more work to be done separately 😁

**Comment by vexx32** [comment]
Yeah I suspect there's something to be added there for checking the element type of the IEnumerable and giving those members back.

**Comment by SeeminglyScience** [comment]
If I had to guess, I'd say we're probably looking for `IEnumerable<>` in *interfaces* of the inferred type, but not checking if the inferred type *itself* is `IEnumerable<>`.
