### ISSUE TITLE
Method overload selection involving delegates should use scriptblock parameters for selection hints

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#16940]
### Summary of the new feature / enhancement

Lets take the API `Enumerable.Select`

```powershell
[Linq.Enumerable]::Select

OverloadDefinitions
-------------------
public static IEnumerable<TResult> Select<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, TResult> selector);
public static IEnumerable<TResult> Select<TSource, TResult>(IEnumerable<TSource> source, Func<TSource, int, TResult> selector);
```

In order to use this API from PowerShell, you *must* explicitly cast your scriptblock as the target delegate type. Otherwise it is ambiguous which of the two overloads you want.

If PowerShell's binder was altered to use the param block of the scriptblock as a hint for overload resolution, you would be able to specify which overload you want, e.g.

```powershell
# First overload
[Linq.Enumerable]::Select[object, object](
    0..10,
    { param($source) })

# Second overload
[Linq.Enumerable]::Select[object, object](
    0..10,
    { param($source, $index) })
```

To avoid breaking changes, this should only be a *hint* for overload resolution. It should not affect binding outside of otherwise ambiguous overload choice.

**Comment by 237dmitry** [comment]
It probably depends on the specific task. How does the API know what will be as a delegate? A common mechanism is provided, this is a function. I understand it this way.
```powershell
[Linq.Enumerable]::Select(0..10, [func[object,object]] { if ($args[0] % 2) { $args[0] } } )
```

**Comment by iSazonov** [comment]
> If PowerShell's binder was altered to use the param block of the scriptblock as a hint for overload resolution, you would be able to specify which overload you want, e.g.

Do you mean to use parameter count or types too?

**Comment by SeeminglyScience** [comment]
> Do you mean to use parameter count or types too?

So **ideally** I'd say types too. It's possible that is just as easy, but I worry that it might drastically increase complexity. I would think parameter count alone would be reasonable in complexity and still solve a significant chunk of ambiguity issues. C# APIs tend to shy away from overloads with delegates of the same parameter count but differing types because typing lambdas is kinda awkward UX.

**Comment by iSazonov** [comment]
@SeeminglyScience Thanks for clarify! I totally agree. We can start with count.

**Comment by SeeminglyScience** [comment]
The Engine WG reviewed this today. We agree it would be a useful change and are marking it as up for grabs (meaning I'll probably not it out some weekend unless someone beats me to it).
