### ISSUE TITLE
Powershell installation throws error on SLES15 OS.

### ISSUE THREAD

**Issue by yogeshbirla** [PowerShell/PowerShell#16959]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Get the latest SLES15SP5 image. Try to install powershell using installpsh-suse.sh or install-powershell.sh script. It throws error saying OS is not supported.

Script supports SLES15 but there is bad code in there which prevents the execution.  Below code for checking OS has been deprecated after SLES12 so it works for SLES12 but not for SLES15. We need to check for /etc/os-release to get the correct OS version.

**elif [ -f /etc/SuSE-release ] ; then**

### Expected behavior

```console
installpsh-suse.sh or install-powershell.sh should install powershell on sles15.
```

### Actual behavior

```console
installpsh-suse.sh or install-powershell.sh throws error on sles15 because of deprecated code being used.
```

### Environment data

```powershell
localhost:~ # bash <(curl -s https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh) suse
Get-PowerShell MASTER Installer Version 1.2.0
Installs PowerShell and Optional The Development Environment
  Original script is at: https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools\install-powershell.psh
Arguments used: suse

Operating System Details:
  OS: linux
  DIST:
  DistroBasedOn:
  PSUEDONAME:
  REV:
  KERNEL: 5.3.18-57-default
  MACH: x86_64
  OSSTR:
Sorry, your operating system is based on  and is not supported by PowerShell or this installer at this time.
```

**Comment by iSazonov** [comment]
Please use our template for requesting new OS support.

**Comment by yogeshbirla** [comment]
This script currently supports anything above Sles12. I removed the bad code that I mentioned above "elif [ -f /etc/SuSE-release ] ; then" and I was able to install powershell for sles15. This is not new OS support. It is just some old code related to Sles12 needs to be removed.

**Comment by kasini3000** [comment]
hi @yogeshbirla ：
would you like to submit the script pr?
or
Submit tested improved script code to here

**Comment by yogeshbirla** [comment]
@kasini3000 I would like to submit PR for this change. Can you please let me know the process.

**Comment by kasini3000** [comment]
https://github.com/PowerShell/PowerShell/blob/25bc64f4b05b4a38858c300864c8f902d6977cc3/.github/CONTRIBUTING.md

**Comment by yogeshbirla** [comment]
I have the code ready. It is not allowing me to send Pull request. My git account is with email birlayogesh@gmail.com.

I am getting:
remote: Permission to PowerShell/PowerShell.git denied to yogeshbirla.

**Comment by vexx32** [comment]
Yeah, you can't push directly to this repository. What you want to do is create a new fork in your own Github account by clicking the `Fork` button at the top right of this repository. Then copy the Clone URL from there and add it as a remote to your local copy of the git repository (`git remote add personal https://replace.with.clone/url.git`). Then push the branch to your fork (`git push personal -u branch-name-here`).

Once that's done you can go to the Pull Requests page and GitHub normally will detect you've pushed a new branch to your fork and prompt you to open a pull request for that branch.

**Comment by yogeshbirla** [comment]
PR submitted. https://github.com/PowerShell/PowerShell/pull/16984

**Comment by adityapatwardhan** [comment]
The above PR https://github.com/PowerShell/PowerShell/pull/16984 has potentially fixed the issue. Please re-open it is still not working. Install script is not officially supported by the PowerShell team and is a community driven effort.
