### ISSUE TITLE
/dev/null analog

### ISSUE THREAD

**Issue by keklick1337** [PowerShell/PowerShell#16952]
### Summary of the new feature / enhancement

cmd supports creating references to null 

```
mklink filename NUL
```

but, i can't create null reference via powershell on file system.

If I'm wrong - correct me. I just did not find such functionality in powershell.

**Comment by vexx32** [comment]
Yeah, this isn't supported as is on the file system. What are you trying to do with this that requires the file system level null analogue?

You can discard data by piping to the `Out-Null` cmdlet if needed, is there another use case here that is better served with the file system level analogue?

**Comment by keklick** [comment]
> Yeah, this isn't supported as is on the file system. What are you trying to do with this that requires the file system level null analogue?
> 
> You can discard data by piping to the `Out-Null` cmdlet if needed, is there another use case here that is better served with the file system level analogue?

I need to create NULL references in the file system. I can do this only through cmd.exe

**Comment by 237dmitry** [comment]
> I need to create NULL references in the file system.

What is for in windows? Just curious. In linux i am using this to redirect `~/.xsession-errors` log to `/dev/null`.
```
PS > (gi .xsession-errors -force).target
/dev/null
```

**Comment by jborean93** [comment]
Pwsh seems to not allow you to reference NUL in it’s provider so you most likely have to shell out to `cmd /c mklink …` to do such a thing. I am curious why are you creating a symlink that points to NUL? Why not just use NUL instead of the link or if you want a placeholder file just create an empty file?
