### ISSUE TITLE
-MaskInput doesn't work properly

### ISSUE THREAD

**Issue by dannyboy9934** [PowerShell/PowerShell#16967]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Write `$password = Read-Host "Password" -MaskInput` in a .ps1 file and run it

### Expected behavior

```console
Password: ******
```

### Actual behavior

```console
Password -MaskedInput: notMaksed
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/50834782/157096360-c7b24bdb-621d-49f6-8460-1ee7d065d73c.png)

**Comment by vexx32** [comment]
Aye, Windows PowerShell is not v7.x, it's locked at v5.1. I'm not sure how you got the listed environment data, but that cmdlet's behaviour is going to be different in the earlier version there.

**Comment by dannyboy9934** [comment]
If I run the exact same command in the terminal, it works fine

**Comment by jhoneill** [comment]
You can see on the terminal it says "Windows PowerShell".  
Not sure how you're running the .ps1 file but it's running in Windows PowerShell (powershell.exe) not PowerShell 7 (pwsh.exe)

**Comment by dannyboy9934** [comment]
I tried in both versions of powershell, none worked with the .ps1 file, but they both worked when I typed directly in the terminal

**Comment by jhoneill** [comment]
That only happens if your PS1 file in Windows PowerShell 5.  Are you running it from the prompt in PowerShell 7?  I'm guessing you're running it from outside PowerShell.  Put `$psversiontable`  in the PS1 file above the your read host line.  I can pretty much guarantee that if the version says 7 you'll get correct operation, and if you're not the version will say 5.

**Comment by dannyboy9934** [comment]
Ok, I changed it so it runs in pwsh.exe instead of windows powershell, the code runner VSCode extension has windows powershell as default instead of pwsh.exe. Now it runs as it should :)
