### ISSUE TITLE
Invoke-RestMethod: When manually passing a `Content-Length` header on a POST, PS7.2.1 adds to it, breaking the headers

### ISSUE THREAD

**Issue by ThePoShWolf** [PowerShell/PowerShell#16968]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Build out a POST request, I was working on a multipart upload for Google Drive using [this code](https://gist.github.com/ConnorGriffin/dc804357bb10ff7522d0e21ddfdf9398) as a starting point.

**Make sure to specify the 'Content-Length' header**

Here is a rough scaffold:

```powershell
$body = @{
    Name = 'Value'
    Name2 = 'Value2'
} | ConvertTo-Json

$headers = @{
    'Content-Length' = $body.Length
}

$splat = @{
    Uri = 'https://domain.com/api/resource'
    Method = 'Post'
    Body = $body
    Headers = $headers
    'Content-Type' = 'application/json'
}

Invoke-RestMethod @splat
```

In my experience, this will throw an error complaining about the `Content-Type` parameter not being valid, which is weird, but since the `Content-Length` header ends up looking like: `Content-Length: 10, 10` I'm assuming that the parser is assuming that is part of the following header or something.

This problem is not present in Windows PowerShell 5.1.

### Expected behavior

```console
If I manually specify the `Content-Length` header, I would expect `Invoke-RestMethod` to either replace it  entirely or leave it alone.
```

### Actual behavior

```console
`Invoke-RestMethod` is appending to the `Content-Length` header.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/30065933/157096761-45667ffd-e515-40fa-830d-4c8094c98bc3.png)

**Comment by FordycetheSecond** [comment]
Is this going to be looked at at any point?  It's giving me huge issues.  If I'm required to include content-length and content-type in the headers, there's just no way around it that I can find.

**Comment by CarloToso** [comment]
Tests:

```ps1
(iwr "https://httpbin.org/post" -method post -headers @{'Content-Length'=2}).baseresponse.RequestMessage.Content.headers
```

-> `Invoke-WebRequest: Sent 0 request content bytes, but Content-Length promised 2.`

 ```ps1
(iwr "https://httpbin.org/post" -method post -body "a" -headers @{'Content-Length'=1}).baseresponse.RequestMessage.Content.headers
```
-> `Invoke-WebRequest: The cmdlet cannot run because the -ContentType parameter is not a valid Content-Type header. Specify a valid Content-Type for -ContentType, then retry. To suppress header validation, supply the -SkipHeaderValidation parameter.`

```ps1
(iwr "https://httpbin.org/post" -method post -body "a" -headers @{'Content-Length'=1} -SkipHeaderValidation).baseresponse.RequestMessage.Content.headers
```
-> `Invoke-WebRequest: 400 Bad Request`

```ps1
(iwr "https://httpbin.org/post" -method post -body "a" -headers @{'Content-Length'=1} -SkipHeaderValidation -SkipHttpErrorCheck).baseresponse.RequestMessage.Content.headers
```
->`Content-Length {1, 1}`
 `Content-Type   {application/x-www-form-urlencoded}`



`

**Comment by CarloToso** [comment]
@iSazonov @ThePoShWolf @FordycetheSecond It looks like it was fixed in master, can you please check? (I don't know exactly when it was fixed but it doesn't work in PS 7.3.2)
Test:
```ps1
$body = @{
    Name = 'Value'
    Name2 = 'Value2'
} | ConvertTo-Json

$headers = @{
    'Content-Length' = $body.Length
}

$splat = @{
    Uri = 'https://httpbin.org/post'
    Method = 'Post'
    Body = $body
    Headers = $headers
    ContentType = 'application/json'
}

Invoke-WebRequest @splat
Invoke-RestMethod @splat
```

**Comment by iSazonov** [comment]
Perhaps it was fixed in .Net 8 Preview1.

**Comment by CarloToso** [comment]
@iSazonov I confirm it works correctly in PS 7.4.0 preview2
