### ISSUE TITLE
Implement Resolve-DnsName -Type CAA

### ISSUE THREAD

**Issue by pastrylife** [PowerShell/PowerShell#16969]
### Summary of the new feature / enhancement

Please implement `Resolve-DnsName -Type CAA` to facilitate CAA record lookups via PowerShell.

### Proposed technical implementation details (optional)

https://datatracker.ietf.org/doc/html/rfc6844

**Comment by iSazonov** [comment]
The cmdlet is not in the repo. Please use Windows Feedback tool to request the feature.

**Comment by schittli** [comment]
> Please use Windows Feedback

Using Windows Feedback? 
What a joke. We're pretty sure that's a black hole. 
Is there any evidence that Windows feedback is actually being handled professionally? 
In our statistics, out of 100 requests, not a single one was processed professionally.

**Comment by schittli** [comment]
@pastrylife 

## Unfortunately, 
it is often the case with M$$ that their "developers" just develop the most minimal functions - and customers pay money for it. Every month. And if we ask for slightly more, we are directed to a feedback portal that ignores 98% of the requests.

## Fortunately, 
there are engineers who understand the problem to be solved and then provide a professional solution:
https://github.com/rmbolger/DnsClient-PS
I guess that it solves your request.

Too bad, those great engineering work does not get any centime from M$$.

**Comment by sjackson0109** [comment]
This is still an issue today.  Totally agree with the comments about MS Support.

```
PS C:\> resolve-dnsname -type caa google.com
Resolve-DnsName : Cannot bind parameter 'Type'. Cannot convert value "caa" to type
"Microsoft.DnsClient.Commands.RecordType". Error: "Unable to match the identifier name caa to a valid enumerator name.
Specify one of the following enumerator names and try again:
UNKNOWN, A_AAAA, A, NS, MD, MF, CNAME, SOA, MB, MG, MR, NULL, WKS, PTR, HINFO, MINFO, MX, TXT, RP, AFSDB, X25, ISDN,
RT, AAAA, SRV, DNAME, OPT, DS, RRSIG, NSEC, DNSKEY, DHCID, NSEC3, NSEC3PARAM, ANY, ALL, WINS"
At line:1 char:23
+ resolve-dnsname -type caa google.com
+                       ~~~
    + CategoryInfo          : InvalidArgument: (:) [Resolve-DnsName], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.DnsClient.Commands.ResolveDnsName
```

as for this rmbloger dnsclient. I can confirm his `resolve-dns -querytype CAA google.com` query works perfectly.
