### ISSUE TITLE
How to add Homebrew to PATH on PowerShell on Linux

### ISSUE THREAD

**Issue by vedantmgoyal2009** [PowerShell/PowerShell#16966]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Run `$env:PATH += ":/home/linuxbrew/.linuxbrew/bin/brew"`
2. Get the error:
```pwsh
brew: The term 'brew' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Expected behavior

```console
brew should be available and we should be able to run it.
```

### Actual behavior

```console
brew not found.
```

### Environment data

```powershell
PS /workspaces/vedantmgoyal2009> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.4.0-1069-azure #72~18.04.1-Ubuntu SMP Mon Feb 7 11:12:24 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
That PATH should contain the folder not the binary itself. This works just like any other shell.

**Comment by vedantmgoyal2009** [comment]
I have tried adding both `/home/linuxbrew/.linuxbrew/bin/brew` and `/home/linuxbrew/.linuxbrew/bin`, but none of them work. I don't know how to refresh environment variables on pwsh on linux. The documentation for Windows can be found everywhere but it's very hard to find any information for pwsh (linux).

**Comment by vedantmgoyal2009** [comment]
I believe that all of them have correct permissions (files in `/home/linuxbrew/.linuxbrew/bin`)

![image](https://user-images.githubusercontent.com/83997633/157028644-984df1a4-996c-445b-931c-d85324fb9b83.png)

**Comment by 237dmitry** [comment]
> Does the issue occur because of the Symlinks?

No. Check stat of `~/Homebrew/bin/brew`
```
stat -c %a ~/.linuxbrew/Homebrew/bin/brew
```
It has to be executable. If it has not:
```
chmod +x ~/.linuxbrew/Homebrew/bin/brew
```

**Comment by vedantmgoyal2009** [comment]
Thanks! The problem is solved now. Thank you🎉🎉🙏
