### ISSUE TITLE
Console.TreatControlCAsInput is acting weird

### ISSUE THREAD

**Issue by puxu-msft** [PowerShell/PowerShell#16965]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I built a test C# program with the sample code from https://docs.microsoft.com/en-us/dotnet/api/system.console.treatcontrolcasinput?view=net-6.0

Pasted it below:

```cs
using System;

ConsoleKeyInfo cki;
// Prevent example from ending if CTL+C is pressed.
Console.TreatControlCAsInput = true;

Console.WriteLine("Press any combination of CTL, ALT, and SHIFT, and a console key.");
Console.WriteLine("Press the Escape (Esc) key to quit: \n");
do
{
  cki = Console.ReadKey();
  Console.Write(" --- You pressed ");
  if((cki.Modifiers & ConsoleModifiers.Alt) != 0) Console.Write("ALT+");
  if((cki.Modifiers & ConsoleModifiers.Shift) != 0) Console.Write("SHIFT+");
  if((cki.Modifiers & ConsoleModifiers.Control) != 0) Console.Write("CTL+");
  Console.WriteLine(cki.Key.ToString());
} while (cki.Key != ConsoleKey.Escape);
```

It works bad with pwsh:

CASE 1

```ps1
PS> [Console]::TreatControlCAsInput = $false
PS> .\keyecho.exe
# Ctrl+C is handled
PS> [Console]::TreatControlCAsInput
True
```

```ps1
PS> [Console]::TreatControlCAsInput = $false
PS> & .\keyecho.exe
# Ctrl+C is handled
PS> [Console]::TreatControlCAsInput
True
```

CASE 2

```ps1
PS> [Console]::TreatControlCAsInput = $false
PS> Start-Process .\keyecho.exe -Wait -NoNewWindow
# Ctrl+C exits the program!
PS> [Console]::TreatControlCAsInput
False
```

```ps1
PS> [Console]::TreatControlCAsInput = $true
PS> Start-Process .\keyecho.exe -Wait -NoNewWindow
# Ctrl+C is handled
```

I think:

- `Console.TreatControlCAsInput` should be reset after case 1. We've done with the inner program, right?
- It's okay to keep the behavior on case 2, but could we make it more intuitive?

### Expected behavior

```console
CASE 1


PS> [Console]::TreatControlCAsInput = $false
PS> .\keyecho.exe
# Ctrl+C is handled
PS> [Console]::TreatControlCAsInput
False
```

### Actual behavior

```console
CASE 1


PS> [Console]::TreatControlCAsInput = $false
PS> .\keyecho.exe
# Ctrl+C is handled
PS> [Console]::TreatControlCAsInput
True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MatejKafka** [comment]
@kilasuit Please reopen. The issue is still present.

In my testing, it seems invoking any native command that internally messes with Ctrl-C handling results in the PowerShell process also reverting the value of `[Console]::TreatControlCAsInput` back to `$false`.

It's possible that this is a .NET issue, or even that it's by design on the Win32 API level and .NET cannot really do anything about it, but I'd still like to have this issue properly triaged.
