### ISSUE TITLE
Get-ChildItem  without printing current directory and option to remove newline

### ISSUE THREAD

**Issue by musm** [PowerShell/PowerShell#16961]
### Summary of the new feature / enhancement

I want
```
❯ gci
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----          3/5/2022   3:49 PM                bin
d----         4/29/2021  11:15 AM                code
d-r--          3/5/2022   4:24 PM                Downloads
```

instead of 

```
❯ gci

        Directory: C:\Users\Mus


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----          3/5/2022   3:49 PM                bin
d----         4/29/2021  11:15 AM                code
d-r--          3/5/2022   4:24 PM                Downloads

```

**Please note the newline printed after the output of gci. I would also like to make this configurable (i.e. print no new lines)**

I want
```
❯ Get-ChildItem | Format-Wide  -AutoSize
bin                code               Downloads
```
instead of
```
❯ Get-ChildItem | Format-Wide  -AutoSize

        Directory: C:\Users\Mus


bin                code               Downloads 

```

```
❯ $PSVersionTable    
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by jhoneill** [comment]
Multiple ways you can do it. 

Since you are on Windows, the easiest way is re-use the format-xml file from Windows PowerShell.

- Copy `C:\Windows\System32\WindowsPowerShell\v1.0\FileSystem.format.ps1xml` to your profile directory (or anywhere convenient) 
- View definitions begin at line 57, and you only need to change the first view .
- Line 63-66  Has a groupBy Section.  Delete it and save the file
- `Update-FormatData -PrependPath <<path>>\FileSystem.format.ps1xml` will put this formatting in with higher precedence than the build in format.
- Add that command to your profile to make the change in future sessions.

Here's how it looks for me.

```
#512 PS7 ~\Documents\PowerShell> Update-FormatData -PrependPath .\FileSystem.format.ps1xml
#513 PS7 ~\Documents\PowerShell> dir .\profile.ps1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---         23/02/2022     10:36              0 profile.ps1
```

**Comment by musm** [comment]
That doesn't quite work across all cases and doesn't resolve the extra newlines at the start and end. 

For example, it doesn't interact well with DirColors package and custom formatters.  E.g:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/4319522/157172871-a0f8c111-d324-4737-b4a2-c0c97f432e08.png">



In particular, that change isn't a very user-extensible workaround.

**Comment by musm** [comment]
Do newer version of pwsh store the xml format file somewhere else? Commenting those lines leads to bracketed folder names .  Is there a more comphrensive reference on the xml file that I need to modify to get my desired output?

**Comment by jhoneill** [comment]
Yes.  I think it was at the change from 5 to 6 the XML was moved into compiled files, you can the source in the code tree but the it it isn't in the same XML format, so you can work out what has been done (and you can use `get-formatData` to do the same thing) but it doesn't give you the XML to implement it. 
There's documentation here https://docs.microsoft.com/en-us/powershell/scripting/developer/format/format-schema-xml-reference?view=powershell-7.2  I find the easiest thing to do is to find something in PowerShell 5 xml files which does what I want, and cannibalize it. 

If you're getting bracketed folder names that sounds like you have more than one thing contributing to the output.

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine 
There are ways that customization for formatting can be done, but we don't see overriding value in changing this for all users. There are tools on the PowerShell gallery which can aid you in creating new formatting files (Module FormatTools, specifically, `New-TableFormat`)

**Comment by musm** [comment]
Not really answered since it's not clear how the XML for gci can be modified without corrupting the output in other ways.

**Comment by musm** [comment]
Is there any documentation for https://www.powershellgallery.com/packages/FormatTools/0.6.0 ?

**Comment by musm** [comment]
Is there any chance someone could provide a minimal working example of obtaining the output desired in the original post?
