### ISSUE TITLE
Remove dead code in StopJob.cs (line 164)

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#1696]
Jason found this through code inspection.  This code will never run because of the previous if statement and in fact the code is duplicated in the HandleStopJobCompleted() where it is correct.  So we can simply remove the code at line 164.

```csharp
var parentJob = job as ContainerParentJob;
if (parentJob != null && parentJob.ExecutionError.Count > 0)
{
    foreach (
        var e in
            parentJob.ExecutionError.Where(
                e => e.FullyQualifiedErrorId == "ContainerParentJobStopError"))
    {
        WriteError(e);
    }
}
```

**Comment by joeyaiello** [comment]
If we have a "code cleanup" label at some point, this would fall under it.

**Comment by travisty-** [comment]
Hi @powershell, I just submit a PR (#5091) for this issue.

**Comment by dantraMSFT** [comment]
Hmm, I seem to be missing something with this issue and the associated PR.  HandleStopJobCompleted appears to be only used for Job2 instances and not Job instances. While the code is duplicated, removing it for Job instances doesn't appear to be correct.
