### ISSUE TITLE
adb has been configured to the system environment variables, but cannot be invoked from the command line

### ISSUE THREAD

**Issue by xmhwws** [PowerShell/PowerShell#16975]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Command line run `adb`

### Expected behavior

```console
Android Debug Bridge version 1.0.41
Version 33.0.0-8141338
Installed as D:\Android\SDK\platform-tools\adb.exe

global options:
 -a                       listen on all network interfaces, not just localhost
...
```

### Actual behavior

```console
adb: The term 'adb' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.2
PSEdition                      Core
GitCommitId                    7.3.0-preview.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Right click inside a folder and open a terminal, type `adb`, enter and run, it will report an error.

![image](https://user-images.githubusercontent.com/42903751/157232885-76c11fcd-7a26-46e6-be83-63100b460855.png)

But right click on the Microsoft icon, open windows terminal, and type `adb` to run it normally.
adb is already configured in the system environment variable;
My computer system is Win11 Professional, I have this problem with the default Powershell, and I still have this problem with the latest version of github terminal;
I don't know why this is happening?

![image](https://user-images.githubusercontent.com/42903751/157232974-e5ab2f8f-cec4-45e2-9ba2-07bcccd6522d.png)
![image](https://user-images.githubusercontent.com/42903751/157233025-b779a9f3-ed17-4dc1-bad4-4c125decdaa8.png)

**Comment by 237dmitry** [comment]
Is `adb` in the `$env:Path`? If not you should run it with a relative or full path even if it is in the current directory:
```
PS > .\adb
```

**Comment by xmhwws** [comment]
> Is `adb` in the `$env:Path`? If not you should run it with a relative or full path even if it is in the current directory:

adb has been added to the system environment variables;
But when I run `$env:Path`, something very strange happens:

![image](https://user-images.githubusercontent.com/42903751/157254318-fc902352-5e43-4dae-9034-d3cfeec10537.png)

As you can see in the picture:
The image above shows me opening windows terminal by right clicking on the Microsoft icon;
The picture below shows me right-clicking on a folder to open windows terminal;

The above picture shows the environment variable with the directory where adb is located, but the below picture does not, which is probably why the above picture can invoke adb through the command line normally.

**Comment by rkeithhill** [comment]
> The picture below shows me right-clicking on a folder to open windows terminal

When you launch Windows Terminal from another app, it inherits the environment (including the PATH) from that app.  What is the app where you are right-clicking on a folder - File Explorer or ?

**Comment by xmhwws** [comment]
> I suspect a reboot would eliminate this issue.

You are right, after restarting the computer, right click in a random folder and open the terminal, you can invoke adb through the command line normally;
But it's strange, isn't it true that the environment variables in windows take effect in time? This is the first time I've encountered an environment variable that requires a restart of the computer to work, a bug in windows 11?

**Comment by iSazonov** [comment]
> But it's strange, isn't it true that the environment variables in windows take effect in time?

There is an issue for this in Windows Terminal repository.
