### ISSUE TITLE
Allow Wait-Process to wait for *any one* of multiple processes, as an opt-in alternative to waiting for *all* of them

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16972]
### Summary of the new feature / enhancement

Passing multiple processes to `Wait-Process` currently makes the latter wait for _all_ target processes.

However, it is sometimes desirable to only wait for _any one_ of these processes to terminate.

### Proposed technical implementation details (optional)

* Introduce an `-Any` switch that makes `Wait-Process` return as soon as any _one_ of the target processes terminates.

* Complement it with a `-PassThru` switch to pass a process-info object(s) for the terminated process(es) through - this should work whether or not `-Any` is used.

**Comment by SteveL-MSFT** [comment]
Queued for review in Cmdlets WG

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets  reviewed this and agreed that both of the suggested changes make sense providing utility and neither appear complicated to implement.
