### ISSUE TITLE
character garbled

### ISSUE THREAD

**Issue by he852100** [PowerShell/PowerShell#16983]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
$dump=c:\Users\he123\.vscode\extensions\cweijan.vscode-mysql-client2-4.6.0/sqlite/sqlite-v3.26.0-win32-x86.exe "C:\Users\he123\Videos\new\export\data\_\Original\databases\mmssms.db"  .dump
$name=[System.Text.Encoding]::GetEncodings().name
$name|%{
     [System.Text.Encoding]::UTF8.Getstring([System.Text.Encoding]::GetEncoding($_).GetBytes($dump[60] ))
    }
```

### Expected behavior

```console
INSERT INTO sms VALUES(37,20,'xxx',NULL,xxx,xxx,NULL,0,1,-1,1,0,NULL,'【xxxx】尊敬的客户：您在我行预授信备用金额度提升至800000元，有效期7个工作日，查利息回A，办理回Y，将由我行专员受理，退订回T','+xxx',0,-1,-1,'com.android.mms',0,1,0,-1,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1604889308964,0,-1,'',NULL,-1,NULL,0,0,0,1,0,0,0,NULL,NULL,NULL,0,0,0,0,0,xxx,-1,0,-1,0,0,-1,NULL,NULL,NULL,NULL,1,0);
```

### Actual behavior

```console
'【xxxx】尊敬的客户：您在我行预授信备用金额度提升至800000元，有效�?个工作日，查利息回A，办理回Y，将由我行专员受理，退订回T'
```

### Error details

```console
有效期7个工作日
有效�?个工作日
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by kasini3000** [comment]
猜测：
在用powershell解码字符串时，用了错误的编码。
这看起来跟powershell无关，
请给出$dump=‘xxx’，
或上传sqlite数据库的db文件。（为了减少数据暴露风险，在sqlite.db文件中，请只保留1---2条数据）

**Comment by he852100** [comment]
![image](https://user-images.githubusercontent.com/26913892/158079128-7a1d75b1-9fd7-4246-897e-9f26082ed68e.png)

![image](https://user-images.githubusercontent.com/26913892/158079063-b273f6dd-90eb-448e-8d1d-25d2851cc43e.png)

![image](https://user-images.githubusercontent.com/26913892/158079247-537208db-1f50-46ea-95dd-2e6940972ac2.png)
It can be displayed normally, but it cannot use variables or write files. It will have problems

**Comment by kasini3000** [comment]
hi 我来了。抱歉这么多天没看此贴。我都把这事忘了。
1 你给的sqlite数据库文件，和内里的中文，没有问题。
2 我用powershell查询，插入。没发现你贴的问题。这不是powershell的问题，请关闭此贴。
![QQ拼音截图20220409000204](https://user-images.githubusercontent.com/65390418/162480572-8ba481f0-acd9-4d5a-ad63-ff6cdf7ae177.png)


3 欢迎100元购买我写的powershell读写sqlite插件。支持中文，支持win，支持linux，支持ps5，支持ps7. 欢迎来mail咨询  我的邮箱  1328486072#qq。com   ------替换掉#和。
