### ISSUE TITLE
[pscustomobject] / [psobject] instances aren't auto-converted to strings in .NET method calls

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#16988]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Generally, objects of _any_ type are auto-convertible to strings when passed to `string`-typed .NET method parameters.

`[pscustomobject]` a.k.a `[psobject]` is the curious exception.

There is no reason for `[pscustomobject]` instances to act differently than instances of any other type (irrespective of whether implicit stringification makes sense in a given situation); to give a simple (but contrived) example:

If `(42).ToString((Get-Item /))` works, 
there's no reason why `(42).ToString(([pscustomobject] @{ foo=1 }))` shouldn't.

Note: 

* The problem doesn't just affect locally constructed custom objects, but also the `[psobject]` instances that the serialization infrastructure produces on deserialization, for the emulation of types it cannot re-create with type fidelity.

* Implicit stringification in the context of cmdlets / functions / script is _not_ affected; e.g., `Get-Date -Format ([pscustomobject] @{ foo=1 })` doesn't cause an error.

* Possibly related:
  * #6163

### Expected behavior

```console
PS> (42).ToString(([pscustomobject] @{ foo=1 }))
@{foo=1}  # I.e. the equivalent of (42).tostring('@{foo=1}')
```

### Actual behavior

The method call fails, because the `[pscustomobject]` isn't auto-converted to a string, and method overload resolution fails.

### Error details

```console
MethodException: Cannot find an overload for "ToString" and the argument count: "1".
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.2
```

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this yesterday. Initially we were unsure if this was done purposefully and decided it needed more research.

After looking into it, I'm pretty confident it is a bug. `LanguagePrimitives` internally replaces the `fromType` with `InternalPSObject` if the pso has no base object. The code in core adapter sort of tries to emulate `LanguagePrimitives`' code to fall back to the base object, but it omits the translation from an empty PSO to `InternalPSObject`.

The fallback code from `DotNetAdapter`:

https://github.com/PowerShell/PowerShell/blob/b46ac16e09dce433dbc1ecb19ab949754eef4978/src/System.Management.Automation/engine/CoreAdapter.cs#L860-L868

And from `LanguagePrimitives`:

https://github.com/PowerShell/PowerShell/blob/b46ac16e09dce433dbc1ecb19ab949754eef4978/src/System.Management.Automation/engine/LanguagePrimitives.cs#L4786-L4812

Marking up for grabs.
