### ISSUE TITLE
Powershell -replace for perl users: how to replace-match-$1 in PowerShell?  seems like a missing powershell feature...

### ISSUE THREAD

**Issue by wm2015email** [PowerShell/PowerShell#16991]
### Summary of the new feature / enhancement

Take a look at this perl code:

    $x = "this is a test      123 ... this is only a test"
    $x =~ s/"test\s+(\d+)"/"test $1"/   
    print $x
    this is a test 123 ... this is only a test

Notice that I match a number with regex (\d+), it gets put into the temporary variable $1, then it gets put in the output string as an expansion of $1 temporary variable...

Is there a way to do above perl replacement in powershell? I'm thinking if its possible then its something like this??

    $x = "this is a test      123 ... this is only a test"
    $x = $x -replace "test\s+(\d+)", "test $Matches[1]"
    write-host $x
    this is a test 123 ... this is only a test

Of course it doesn't work... I was curious how to do this since i have a lot of perl scripts to convert to PowerShell..

### Proposed technical implementation details (optional)

Ideally it would be better if Powershell supported this like perl:

    $x = "this is a test      123 ... this is only a test"
    $x = $x -replace "test\s+(\d+)", "test $1"  
    write-host $x
    this is a test 123 ... this is only a test

**Comment by fMichaleczek** [comment]
@wm2015email use "$($Matches[1])" instead of "Matches[1]" , then there is a dedicaced section in the manual about the syntax $1.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.2#regular-expressions-substitutions

**Comment by 237dmitry** [comment]
```
$x = "this is a test      123 ... this is only a test"
$x = $x -replace "test\s+(\d+)", 'test $1'         
write-host $x
```

**Comment by vexx32** [comment]
Aye, The `$1` syntax works with .NET regexes just fine, but because PowerShell also uses `$var` for variable names, you need to use single-quoted strings to disable its normal variable interpolation.

**Comment by jhoneill** [comment]
> Aye, The `$1` syntax works with .NET regexes just fine, but because PowerShell also uses `$var` for variable names, you need to use single-quoted strings to disable its normal variable interpolation.

Or escape the $ sign with ` 

> $x = "this is a test      123 ... this is only a test"
> $x -replace "test\s+(\d+)", 'test $1'
works , so does 
> $x -replace "test\s+(\d+)", "test `$1"

Note the correct way to output. Write-host is for things which are not output.

**Comment by kasini3000** [comment]
'$1'    or            "`$1"         or            $($Matches[1])  , 
from ps v 6.1,support code 
` $x -replace "test\s+(\d+)", {return 'a' + $($Matches[1]) + 'b'}`
this is a a123b ... this is only a test
