### ISSUE TITLE
What is the problem usually caused by ?

### ISSUE THREAD

**Issue by lost4git** [PowerShell/PowerShell#16993]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

![image](https://user-images.githubusercontent.com/65008815/158043786-74213ef6-1274-4773-a9f3-abd000d79c2b.png)

But `Out-Default` command can be found:

![image](https://user-images.githubusercontent.com/65008815/158043803-86dd70a7-0c00-45a0-900b-98fc2b104571.png)

### Expected behavior

```console
kill jobs successfully
```

### Actual behavior

```console
Entering an unknown mode, unable to execute any commands
```

### Environment data

```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
I have caused that (5 or 6 years ago!) by setting up restricted language mode incorrectly in a JEA session.
