### ISSUE TITLE
Install-Module can not install Modules

### ISSUE THREAD

**Issue by jsearpo** [PowerShell/PowerShell#17004]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After executing following command， results are as below picture. It always stays in this state.
` Install-Module ExchangeOnlineManagement`
![PS7](https://user-images.githubusercontent.com/78406087/158617230-2c5fc827-b0c1-46a2-a149-55a99bd5760f.PNG)

### Expected behavior

```console
downloaded successfully!
```

### Actual behavior

```console
downloaded 0 out of 100%!
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I had exactly the same situation, but then everything resolved itself. In my opinion, this is a Powershell Gallery problem.

**Comment by jsearpo** [comment]
> I had exactly the same situation, but then everything resolved itself. In my opinion, this is a Powershell Gallery problem.

For me, it can not work, I wait for two days,  it still can not download competely.  it is  merely 7MB.

**Comment by kasini3000** [comment]
Would you like to push the PowerShellGallery mirroring plan? see :
https://github.com/PowerShell/PowerShellGallery/issues/164
