### ISSUE TITLE
help -ShowWindow parameters only show first section of text.

### ISSUE THREAD

**Issue by joepuresdk** [PowerShell/PowerShell#17015]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In a *dll-Help.Xml file if a parameter has 2 or more `<maml:para>` blocks, only the 1st is shown in "ShowWindow".

For example, in the module SqlServer version 21.1.18245 `Microsoft.SqlServer.Assessment.Cmdlets.dll`)

In the help xml file the description for the Checkparameter: (`21.1.18245\en\Microsoft.SqlServer.Assessment.Cmdlets.dll-Help`)
```
        <command:parameter required="false" variableLength="true" globbing="false" pipelineInput="False" position="named" aliases="none">
          <maml:name>Check</maml:name>
          <maml:description>
            <maml:para>One or more checks, check IDs, or tags.</maml:para>
            <maml:para>For every check object, Get-SqlAssessmentItem returns that check if it supports the input object.</maml:para>
            <maml:para>For every check ID, Get-SqlAssessmentItem returns the corresponding check if it supports the input object.</maml:para>
            <maml:para>For tags, Get-SqlAssessmentItem returns checks with any of those tags.</maml:para>
          </maml:description>
```

In ShowWindow, only the 1st `<maml:para>` block of text is displayed.

Compare:
```
help Get-SqlAssessmentItem -ShowWindow
```
to 
```
help Get-SqlAssessmentItem -Parameter check
```

multiple `<maml:para>` blocks work fine in cmdlet description.

### Expected behavior

```console
All of the help text for each parameter should be displayed.
Platyps will create help XML files with multiple <maml:para> blocks.
```

### Actual behavior

```console
Only the first block is displayed.
```

### Error details

```console
There is no error given.
Silent failure.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
Thank you @joepuresdk -- The Interactive WG has determined that there is a bug in Get-Help -ShowWindow preventing the markup from being displayed.

**Comment by paziz001** [comment]
@theJasonHelmick Can I try fixing this?

**Comment by paziz001** [comment]
I think I might have fixed it.

**Comment by theJasonHelmick** [comment]
@paziz001 -- Thats wonderful!!  If you would like to share your solution here, that would be very welcome.  We are thinking about how to address this along with other considerations - so you knowledge is welcome.

**Comment by paziz001** [comment]
This was a long time ago but I have referenced the PR with the possible solution which has been partially approved.
