### ISSUE TITLE
PowerShell test gallery `https://www.poshtestgallery.com` is down

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#17019]
PowerShell test gallery `https://www.poshtestgallery.com` is down, we are investigating the root cause now.

We marked the PowerShellGet tests pending in the following files because of this
- PackageManagement.Tests.ps1
- PowerShellGet.Tests.ps1

Make sure to re-enable those tests when this issue is resolved.

**Comment by OscoreJohnSteiner** [comment]
Any update on this?

**Comment by daxian-dbw** [comment]
@OscoreJohnSteiner Are you blocked by the outage of the test gallery? What scenario do you depend on the test gallery?

**Comment by OscoreJohnSteiner** [comment]
I've inherited some code as follows:

`    $packageSource = Register-PackageSource -Trusted -ProviderName 'PowerShellGet' -Name 'Posh Test Gallery' -Location 'https://www.poshtestgallery.com/api/v2/' -Force
    Install-Module -Name 'AzureAD.Standard.Preview' -Force -Scope CurrentUser -SkipPublisherCheck -AllowClobber 
    Import-Module AzureAD.Standard.Preview

    $context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
    $graphToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.microsoft.com").AccessToken
    $aadToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://graph.windows.net").AccessToken

    Connect-AzureAD -AadAccessToken $aadToken -AccountId $context.Account.Id -TenantId $context.tenant.id -MsAccessToken $graphToken
`

Any sense of whether I should be able to just change poshtestgallery.com for powershellgallery.com (and remove the preview part from AzureAD.Standard.Preview?)  I'll give it a try but I'm sure there was a reason that poshtestgallery and not powershellgallery was chosen at the time.

**Comment by daxian-dbw** [comment]
You may want to try [AzureADPreview](https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.149) which is available on PowerShell Gallery. The test gallery does not have any service level agreement or objectives. Packages in it could be deleted without notifications. So, you should depend on `powershellgallery.com` only.

**Comment by daxian-dbw** [comment]
The `PackageManagement.Tests.ps1` and `PowerShellGet.Tests.ps1` are updated to test against `powershellgallery.com` (#17062).
The test gallery actually becomes Microsoft internal access only, due to a policy enforced in Microsoft. The gallery team is intended to keep it internal accessible only, so I will close this issue.
