### ISSUE TITLE
Powershell debugger can modify runtime behavior with same script

### ISSUE THREAD

**Issue by moutonjr** [PowerShell/PowerShell#17017]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I reduced the code at its minimum to highlight one very strange issue from Powershell

Same for pwsh 5.1.22000.282 and 7.2.2.

Code:
```shell
$outlook = new-object -com Outlook.Application;
$namespace = $outlook.GetNameSpace("MAPI");
$inputFolderObj=$namespace.Folders.Item('user@domain.com').Folders.Item('temp')
$scope = $inputFolderObj.FolderPath
$filter = ""
$search = $outlook.AdvancedSearch("'$scope'", $filter, $True)
$search.Results.Count
```

on CLI : 
```shell
PS C:\dummyfolder> .\test.ps1
0
PS C:\dummyfolder> .\test.ps1 # reproductible
0
PS C:\dummyfolder> Set-PSBreakpoint -Line 7 -Script .\test.ps1 | out-null
PS C:\dummyfolder> .\test.ps1
Passage en mode débogage. Utilisez h ou ? pour obtenir de l'aide.

Appuyez sur Point d'arrêt de ligne sur « C:\Udummyfolder\test.ps1:7 »

Au caractère C:\dummyfolder\test.ps1:7 : 1
+ $search.Results.Count
+ ~~~~~~~~~~~~~~~~~~~~~
[DBG]: PS C:\dummyfolder>> c
1
```

Is it a bug? Do I miss something here? Thanks,

### Expected behavior

```console
1 each time
```

### Actual behavior

```console
0 if run by Powershell directly
1 with a breakpoint.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@moutonjr Can you try running `. .\test.ps1` in a new 7.2.2 PowerShell session and share the results?

**Comment by FormindGMO** [comment]
Hi @daxian-dbw , Powershell 7.2.2 does the same thing. 
![image](https://user-images.githubusercontent.com/79926595/158991694-005df018-1ce8-4128-8726-568b30d3dd1b.png)

Please tell if I have to up/downgrade PoSH to another version.

Yes it is expected to retuirn 1 email placed in the "temp" folder.

**Comment by daxian-dbw** [comment]
> Can you try running `. .\test.ps1` in a new 7.2.2 PowerShell session and share the results?

@FormindGMO I was asking you to dot-source the test.ps1 script, not running it directly. Can you run it by dot-sourcing and share the results?

**Comment by FormindGMO** [comment]
When a dot makes all difference, sorry :)

Same error.. :/

![image](https://user-images.githubusercontent.com/79926595/159044445-d8d18839-ba22-43af-8cbc-cca7f4c3e3c5.png)

Is it reproductible on your side?
