### ISSUE TITLE
Pop "under" window behaviour

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#17026]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Apologies if my search-foo isn't working, but I can find this 

When run in Windows Terminal or in VSCode - but not in the legacy host child windows open behind the active window. 
So if one runs (e.g.) Notepad it's **not** a child window and it appears in the foreground, but `Get-Help -showWindow` or `Out-GridView` are often hidden (this is most obvious when running on a single screen - sometimes they will open on the other screen so *are* visible)

### Expected behavior

```console
Child Window is visible
```

### Actual behavior

```console
Child Window is hidden behind VS-Code or Windows Terminal
```

### Error details

```console
No message
```

### Environment data

```powershell
Name                           Value[0m
----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/16209593/158981153-dfd3a475-2eab-44d3-82cc-6160f024e345.png)

This show what happens immediately after running the command, an icon appears on the task bar for the child window, but VSCode (in this case) remains in the foreground giving the impression that nothing has happened. If code is running full screen you don't see the icon appear so nothing seems to have happened  but clicking the icon gives access. In dual screen mode the window may appear on another screen

**Comment by rkeithhill** [comment]
Related: https://github.com/microsoft/terminal/pull/12799

**Comment by zadjii-msft** [comment]
Absolutely, this is the upstream https://github.com/microsoft/terminal/issues/2988

**Comment by SeeminglyScience** [comment]
Thanks @zadjii-msft! Is the fix for any terminal utilizing ConPTY or is it specifically for WT?

**Comment by zadjii-msft** [comment]
> Is the fix for any terminal utilizing ConPTY or is it specifically for WT?

Well, it was designed so that any terminal emulator could use the fix, but they'd need to add some extra code on their part to enable it. We're just kinda testing it out in WT right now to make sure this works for all the cases we'd like before documenting it in greater detail. Wouldn't want to have to rewrite the whole docs if we're wrong 😅 The fix also isn't going to be in OS builds of ConPTY for quite some time yet, so that gives us a bit of wiggle room for making sure the surface is stable.

**Comment by rkeithhill** [comment]
@jhoneill Just tried the 1.14 release of Windows Terminal Preview and this bug appears to be fixed.  https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-14-release/  🎉
