### ISSUE TITLE
PowerShell Core 7.2.1 + Chef InSpec

### ISSUE THREAD

**Issue by HerbBoy** [PowerShell/PowerShell#17020]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I experienced this issue when I went to leverage Chef InSpec to run https://github.com/vmware/dod-compliance-and-automation (a compliance check against VMware DISA STIG's).

1. Using RHEL 8.4 or Ubuntu 18.04 (tested against both OS's)
2. Install PowerShell Core 7.2.1
3. Install Chef InSpec ver. 4.52.9
4. Git Clone https://github.com/vmware/dod-compliance-and-automation
5. Run the Chef InSpec role to run a complaince check against a ESXi https://github.com/vmware/dod-compliance-and-automation/blob/master/vsphere/7.0/vsphere/inspec/vmware-vsphere-esxi-7.0-stig-baseline/README.md

### Expected behavior

```console
When run on PowerShell Core 7.2.0 this works without issue.
```

### Actual behavior

```console
When run on PowerShell Core 7.2.1 this fails out.

Only thing i am not sure of is which tool is at fault, hence why i have issue open at InSpec Train https://github.com/inspec/train/issues/725
```

### Error details

```console
PS /root>> inspec exec ./vmware-vsphere-esxi-7.0-stig-baseline -t vmware:// --input vmhostName=192.168.1.62
here1
[string](Get-InstalledModule -Name VMware.PowerCLI | Select -ExpandProperty Version)
12.4.1.18769701
PS /root>
here2
ion)
12.4.1.18769701
PS /root>
here3
ion)
12.4.1.18769701
here4
echo $?
True
PS /root>
here5
o $?
True
PS /root>
here6
o $?
True
#<struct Train::Extras::CommandResult stdout="ion)\n\e[?1l12.4.1.18769701\n", stderr="", exit_status=1>
Unable to determine PowerCLI Module version, is it installed?
```

### Environment data

```powershell
PowerCLI Version: 12.5.0.19195797
OS: RHEL 8.4
PowerShell Core Version: 7.2.1-1.rh
```

### Visuals

n/a

**Comment by jhoneill** [comment]
I can see an ANSI escape sequence in the output. The main change in   7.2.1 was corrupting output with ansi sequences **by  default**   try this to get clean output

`$PSStyle.OutputRendering = "PlainText"` 

@SteveL-MSFT  I was thinking this was going to put right in 7.2.2 but it seems not. Do with an eta for when *host* can be norm again, because quite a few issues being raised at the moment relate it to it. 
It would be nice for the default to be able to `dir > file.txt` and or `$psversion | clip` and get what we always got.

**Comment by jhoneill** [comment]
They may need to make the parsing more robust, sure. Often that sort of parsing is wrong-footed by even quite small changes, but if they never thought an ANSI sequence could get into the output, you'd expect the appearance of one to cause a failure.

**Comment by HerbBoy** [comment]
@jhoneill 

![image](https://user-images.githubusercontent.com/61263592/159192994-7977cded-6425-43fa-8305-2ec66fee287c.png)

![image](https://user-images.githubusercontent.com/61263592/159192972-b5be2128-fd21-4510-a1f7-8fc6996ecabe.png)

Any other ideas?

**Comment by jhoneill** [comment]
If inspec is launching its own copy of PowerShell setting the option in the session won't work ,  
`$env:NO_COLOR=$true` might
 I'm not quite sure what the sequence [esc][?1l does or where it comes from. And I could be barking up the wrong tree, that message might not mean the output that its getting is wrong but if it worked with 7.2 and not 7.2.1  that's too big a coincidence.

**Comment by jhoneill** [comment]
@HerbBoy  Good news :-) , I think they need to make their parsing a bit harder to throw off track.

**Comment by SteveL-MSFT** [comment]
I believe https://github.com/PowerShell/PowerShell/pull/16811 should resolve this

**Comment by jhoneill** [comment]
@SteveL-MSFT  do we have an ETA on when #16811 will be delivered? The default has not changed back to Host in 7.2.2
