### ISSUE TITLE
Add-Printer -WhatIf actually adds a printer (rather than tests/simulates it)

### ISSUE THREAD

**Issue by middletonk** [PowerShell/PowerShell#17028]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Tested and validated in PowerShell 5.1 and 7.2.2:

**Add-Printer -ConnectionName \\CONTOSOPR01\ABC123 -WhatIf** returns no "WhatIf" responses and instead fully adds a printer for the current user.

### Expected behavior

```console
Expect an Out-Host style textual confirmation: "WhatIf: Adding printer ABC123"
```

### Actual behavior

```console
Actual behavior is that the printer is added to the OS.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please use Windows Feedback tool to report the issue.

**Comment by jhoneill** [comment]
Just a side note `Add-Printer` ships with Windows as part of Windows PowerShell 5, it's in the `PrintManagement `module under  `C:\Windows\system32\WindowsPowerShell\v1.0\Modules`  so isn't looked after as part of this repo.

It's a cim-cmdlet and looking inside the function that's created there's a "Supports Should Process" at the top but no "Should process" code in it - somewhere a setting is missing in `MSFT_Printer_v1.0.cdxml`  which defines the CIM cmdlet, I'm not clued up enough on the XML schema for these to things to know what it is, but some of the MSFT folk here will know, and hopefully will have contacts in the right group to get the fix made.
