### ISSUE TITLE
PowerShell 7 not being updated by Microsoft Update

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell#17034]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am running PowerShell 7,2,1, As expected (following the release of 7.2.2) when I run PowerShell I get the notification message. This is consistent with several hosts. However, on every host - I installed PowerShell 7 using the MSI AND selecting the option to update by MU. The update to 7.2.2 is not happening on all my Win 11 (Insiders) hosts.

I can appreciate it might take a few days after the release hits Github. But it should be the case the MU updates work at the same time as the message starts to appear. In a perfect world, I should never see that message as MU should have updated my version of PowerShell 7. 

### Expected behavior

```console
Powershell 7.2.1 should see the update, and thanks to MU, that update should be downloaded, installed, and becomes useful.
```

### Actual behavior

```console
7.2.2 appears only to be installable manually.
```

### Environment data

```powershell
PS C:\Foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22572
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.1}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PowerShell/discussions/16459#discussioncomment-2389665

**Comment by sdwheeler** [comment]
FYI - This is what our documentation says:

https://docs.microsoft.com/powershell/scripting/install/microsoft-update-faq?#what-version-of-windows-is-required-to-support-the-microsoft-update-feature

> **How soon after release are updates advertised by Microsoft Update?**
> When a new version of PowerShell is released, it can take up to two weeks for that version to become available through Microsoft Update. Updates are delivered as optional software updates, even if the update contains a security fix.
