### ISSUE TITLE
Invoke-Expression doesn't work if Write-Output hasn't been called at least once.

### ISSUE THREAD

**Issue by gerardog** [PowerShell/PowerShell#17031]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Found a quite strange behaviour with Invoke-Expression.
It does nothing depending on how PowerShell was initialized... Same behaviour on 7.2.1 and Windows Powershell (5.1.22000.282)

Windows 11 21H2 Home (Build 22000.556)

When I use `-noprofile` or `-noprofile -noni` and the first command is Invoke-Expression, it does nothing.

```
C:\Users\gerar>pwsh -nop
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\gerar> '1+1' | iex       # Expected: 2   Actual: void
PS C:\Users\gerar> Invoke-Expression '1+1' # Expected: 2   Actual: void
PS C:\Users\gerar> Write-Output ''    # This line initializes something?

PS C:\Users\gerar> '1+1' | iex # Expected: 2   Actual: 2
2
PS C:\Users\gerar>
```

### Expected behavior

```console
Invoke-Expression runs the expression.
```

### Actual behavior

```console
Invoke-Expression does nothing.
```

### Error details

```console
Get-Error returns nothing.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by gerardog** [comment]
I ran procmon to see if I could found something else.
Found a Invoke-Expression.ps1 file in the path. 

I created it a while ago, when I was experimenting....

I used:
``` powershell
[System.Management.Automation.ProxyCommand]::Create((gcm invoke-expression))
```
Wrapped that into `function Invoke-Expression {` `}` and saved as `Invoke-Expression.ps1` in the path.

I still not sure to close this issue... maybe it should have worked anyway?.

**Comment by SeeminglyScience** [comment]
I would guess that it's any command from the module `Microsoft.PowerShell.Utility` that causes it to start working. The code gen for proxy commands generates a command lookup that *does not* auto import modules. So once the module is imported it'll find the proxy target and start working.

**Comment by RamiSJ12** [comment]
Need one more code...

{
else wrong;
else error;
else i = 0;

     Return
}
