### ISSUE TITLE
Fix help for PackageManagement, PowerShellGet, PSDesiredStateConfiguration, and PSReadLine

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#1703]
## Steps to reproduce

Currently, update-help does not work on Linux. Because of this, help content needs to be added for the following modules on Linux (as a nuget package):
- PackageManagement
- PowerShellGet
- PSDesiredStateConfiguration
- PSReadLine
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by ScriptAutomate** [comment]
I get a more extensive version of issues with Update-Help, not just limited to the three mentioned in this issue.

OS: Ubuntu 14.04
PowerShell Version: v6.0.0-alpha.9

Error message when running Update-Help:

update-help : Failed to update Help for the module(s) 'Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core, Microsoft.PowerShell.Host, Microsoft.PowerShell.Management, Microsoft.PowerShell.Security,      Microsoft.PowerShell.Utility, PackageManagement, PowerShellGet, PSReadLine' with UI culture(s) {en-US} : The type initializer for 'System.Management.Automation.Internal.CabinetExtractorFactory' threw an exception.

**Comment by joeyaiello** [comment]
Changing title to fix help for those modules. We might want to ship the help with PowerShell 6.0 itself, but it could also make sense to just get Update-Help working (which @adityapatwardhan is working on).

**Comment by Francisco-Gamino** [comment]
@joeyaiello : Update/save-help already worked on Linux. This was fix by my PR https://github.com/PowerShell/PowerShell/issues/2164.

The only standing issue is that help content for Pester and PSDesiredStateConfiguration is not available on Linux. This could be because we do not have .zip files with content on the Download Center. @adityapatwardhan  could you please confirm?

**Comment by joeyaiello** [comment]
I worded my statement a little casually. I know that Update-Help as a cmdlet works, I just meant we need to "enable the Update-Help pipeline for these modules". And you're right, that means uploading all this content to Azure blob storage (we're not using the Download Center anymore).

**Comment by joeyaiello** [comment]
@adityapatwardhan have you already solved this problem?

**Comment by TravisEz13** [comment]
Update-Help works on Linux, this doesn't seem like it is needed anymore?
@adityapatwardhan  to verify

**Comment by adityapatwardhan** [comment]
This is fixed by: 
PackageManagement: https://github.com/OneGet/oneget/pull/323
PSGet: https://github.com/PowerShell/PowerShellGet/pull/195
PSReadline: https://github.com/PowerShell/PowerShell-Docs/pull/1709
