### ISSUE TITLE
CimCmdlets module not supported on Powershell Linux 

### ISSUE THREAD

**Issue by sadiqueurfarbaz** [PowerShell/PowerShell#17041]
### Summary of the new feature / enhancement

Hey, I wasn't sure where to report this, I tried StackOverflow and Technet too but didn't get any response, wanted to know why is [CimCmdlets] module is not supported on platforms other than Windows? I've got a script that I need to run on both Linux and windows but couldn't do that because this module is missing. Also, the Get-WmiObject commandlet doesn't seem to be working on Linux.
FYI- The script I'm running is basically using -computerName flag and the device mentioned for this tag is a windows machine only. with the script, we are trying to fetch the windows device information on the Linux machines.

**Comment by sadiqueurfarbaz** [comment]
@jhoneill  so there's no direct way to execute these scripts in Linux? is there any plan to add a CIM module in Linux Powershell?

**Comment by kasini3000** [comment]
https://gitee.com/chuanjiao10/kasini3000/tree/master/node_script
on this folder , i write script to get cpu ,mem,disk,  info for free use.

normal we use windows master pc,copys this folder files and subfolder to every linux node,
then 
```
$foo = krun { /etc/kasini3000/node_script/xxx.ps1} #from master pc
```
to copy-files : 
```
cdip 1.2.3.4 #win,linux node ip
./kctf复制主控机node_script目录脚本到当前被控机.ps1
```

I love powershell, this project is my dedication.
The slogan of this project is "ditch the YAML, powershell makes the command line great again."

**Comment by jhoneill** [comment]
> @jhoneill so there's no direct way to execute these scripts in Linux? is there any plan to add a CIM module in Linux Powershell?

To the best of my knowledge, no, but I'm happy for someone to correct me.

**Comment by jhoneill** [comment]
Just found something I thought I knew was wrong
In the Windows Sandbox (effectively a VM on my Laptop) I can remote to my own machine with   
`New-PSSession -ComputerName 192.168.0.39 -Credential $mycred` 

On WSL the same command gives an access denied (my memory was the `-ComputerName` parameter wasn't available on Linux), it gives this error as the first one which suggests more support for the WSMan than I thought. 

```
System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.Initialize(Uri connectionUri, WSManConnectionInfo connectionInfo)
```
I had the firewall rules wrong so the sandbox couldn't connect, but the WSL was still coming back with access denied pretty much instantly, so I don't think the error is generated without ever sending anything from the Linux side. 

@kasini3000   is your stuff enabling WSMAN from Linux to Windows? 

(doesn't change the substantive point that the CIM module isn't available, but it might open the chance to change that).

**Comment by fMichaleczek** [comment]
@jhoneill The subject has been studied here (with a fully detail blog)
https://github.com/jborean93/omi

**Comment by fMichaleczek** [comment]
@kasini3000 it's not supported by the PS team so it's not something to recommend or advice.

**Comment by daxian-dbw** [comment]
The `CimCmdlets` module is Windows only, and there is no plan to support it on Linux.
