### ISSUE TITLE
let pwsh and here-strings support【＠“strings”＠】 

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#17048]
### can not use full-width single quotes on title?

```
＠＂string＂＠
```

# Context:
Powershell often interacts with other command line and terminal software. cmd, bash, etc. 
These software use single quotes, double quotes. So, in powershell, you can't use single quotes, or double quotes, unless you use escaping.
At present, powershell supports the use of full-width single quotes and full-width double quotes, which partially solves the escaping problem, but it is not enough.

Why？
Because on the powershell command line, full-width single quotes will form a pair with single quotes,
which violates the powershell rule **not to use any single and double quotes**.

**This Enhancement mainly solves the problem of command line escaping and compatibility with other shells.
It's like cybersquatting a domain name.
pwsh sucks if other shells use this idea first.**

### Summary of the new feature / enhancement

I was expecting [within script] and command line parse to support here-strings like this:
```powershell
ssh root@ip " pwsh -c ＠“   1+2 ; write-host “abc” ”＠ "
```
Especially the command line.

### Proposed technical implementation details (optional)

# Rules: (discussion welcome)
1 break change,let pwsh recognize the outermost here-string as the start and end of a powershell command.
Only full-width single quotation marks and full-width double quotation marks can be used inside, and there cannot be any single quotation marks or double quotation marks.

```
pwsh -c  ＠＂powershell code＂＠
```

or

```
pwsh -c ＠＇powershell code＇＠
```

or

```
pwsh -c2   ＠＂【single quotes】  new line 」   〖 double quotes〗＂＠             ? 
```

2let pwsh recognize the inner here-string as here-string.

----

# tips
ps > ssh root@ip { pwsh -c '1+1' } # not work，you cannot replace double quotes with "{" on powershell or pwsh

# Here-strings
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2

----

My plan b, I don't like it,You don't like it either.

```
「 」
 ⎣   ⎤
『  』
【】
〖〗
〔 〕
〘  〙
〚  〛



﴾       ﴿        U+FD3E,U+FD3F
⁅ ⁆
⦑ ⦒      U+2991,U+2992


⦓ U+2993 
⦔ U+2994

⦕ U+2995
⦖ U+2996


⦋ ⦌
⦍ ⦎
⦏  ⦐
------
〈 〉
❪ ❫
❬ ❭
❰ ❱
❲ ❳
❴ ❵
⟦ ⟧
⟨ ⟩
⟮ ⟯
⦃ ⦄
⦅ ⦆
------
⦗ ⦘
⧼ ⧽
⸨ ⸩
❮ ❯
⟪ ⟫
⦇ ⦈
⦉ ⦊
⌈ ⌉
⌊ ⌋
「 」
〈 〉
〔 〕


⧏
U+29CF
⧐
U+29D0


⧼
U+29FC
⧽
U+29FD


```

----

[kasini3000](https://gitee.com/chuanjiao10/kasini3000)    
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline) 
Open source, free, cross-platform 
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

[kasini3000_agent_linux](https://gitee.com/chuanjiao10/kasini3000_agent_linux) Shell script,one click install powershell on linux,modify sshd_config for PsRemote.

now，you can use：
```
cdip 1.2.3.4; $a = krun { powershell command on node }
or
$a = k_run_ip -ip 1.2.3.4 { powershell command on node }
```
It encapsulates the powershell remote, at least you can use {} instead of single quotes, double quotes.

**Comment by jhoneill** [comment]
Just to be clear, you're talking about this as quotes round a -Command parameter to pwsh.exe **NOT**  as part of the PowerShell language - the latter would be a problem 

But something which allowed this 
```
 pwsh -noprofile -command 'Write-host "Computer name is ''$env:computerName'' " ' 
```
Without doubling up / escaping the single quotes round the name would make things a little easier

if something needs   `run  "command"`  or  `run  'command'`    it would usually have a way of escaping quotes in _command_ 
So you're looking to avoid stuff like this ? 
``` 
run ' pwsh -noprofile -command ''Write-host "Computer name is ''''$env:computerName'''' " '' ' 
```

**Comment by kasini3000** [comment]
hi @jhoneill

When the powershell command line and the bash command line are used at the same time, the question of who the quotes belong to will arise.
My proposal attempts to suggest other characters for pwsh -c2.

Q: How does pwsh -c2 work?
A: It gets the characters between ＠＇＇＠，
replaces the 【】 in it with single quotes, and then executes it.
