### ISSUE TITLE
Win7SP1 x64 PowerShell.exe crash

### ISSUE THREAD

**Issue by raghushantha** [PowerShell/PowerShell#1705]
I built using the Win7 CoreCLR runtime.

`Start-PSBuild -Runtime win7-x64`

![pasted image at 2016_08_09 06_44 pm](https://cloud.githubusercontent.com/assets/11727200/17539570/076bce64-5e64-11e6-8a8b-53cfbb1461da.png)

**Comment by rkeithhill** [comment]
Well I'm glad I ran across this.  I've been running into various issues trying to build on Win7 x64 using the VC++build tools (instead of VS).  Looks like I can save myself some time and pitch that experiment and try again on a Windows 10 VM.

**Comment by mirichmo** [comment]
The PInvokes look like they are targeting incorrect versions of the API sets. I'm adjusting them to see if that resolves the issue.
