### ISSUE TITLE
On pwsh open: 3x ANOMALY: meaningless REX prefix used

### ISSUE THREAD

**Issue by roxberry** [PowerShell/PowerShell#17054]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Installed 7.2.2, launch from installer, immediately see problem:

[0x7FF89B045090] ANOMALY: meaningless REX prefix used
[0x7FF89B018A30] ANOMALY: meaningless REX prefix used
[0x7FF89B6E7E10] ANOMALY: meaningless REX prefix used

### Expected behavior

```console
On pwsh open, start with PS> prompt
```

### Actual behavior

```console
On pwsh open, displays the following

[0x7FF89B045090] ANOMALY: meaningless REX prefix used
[0x7FF89B018A30] ANOMALY: meaningless REX prefix used
[0x7FF89B6E7E10] ANOMALY: meaningless REX prefix used

then opens PS> prompt
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/761326/159770736-5b77e7ed-ef20-4a07-a1d1-e03a65b1cc5a.png)

**Comment by jborean93** [comment]
Having a read online and it seems like this might be unrelated to PowerShell but potentially some 3rd party dll causing the problem http://www.os2museum.com/wp/anomaly-meaningless-rex-prefix-used/. A few people have found tools like AVG, Raptr have been culprits in the past so maybe check if have any of those installed. I would also search the message and see what other people say.

**Comment by Masterrulax** [comment]
> This issue has been marked as answered and has not had any activity for **1 day**. It has been closed for housekeeping purposes.

useless
