### ISSUE TITLE
When running a .msi file install in windows command window installer fails to initialize

### ISSUE THREAD

**Issue by jcoryatjr** [PowerShell/PowerShell#17053]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Launch any .msi file within powershell core command window.

I just updated to 7.2.2 and develop windows installers using the Wix toolset.  When launching the compiled msi installer inside of a powershell command prompt the

I am seeing this will any .msi file I try and execute within a powershell core window.

I also noticed that the $env:temp value is altered to include a folder path of 1 i.e. C:\users\<username>\AppData\Local\Temp\1
where the system defined value does not include this folder in the path for $env:temp

On the previous version this was not a problem nor was the temp variable get modified like this.

### Expected behavior

```console
Windows installer (msi) file will execute the same as within a windows command window
```

### Actual behavior

```console
installer will fail to initialize with the message: "The installation package couild not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a vlaid Windows Installer package."
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jcoryatjr** [comment]
Please disregard, seeing the same behavior from command window now.  This is local to my system.

**Comment by jborean93** [comment]
> Launch any .msi file within powershell core command window.

Can you share how you are launching it. Are you launching the msi directly or through msiexec? Are you using `Start-Process` or just like `PS C:\> C:\path\to\my.msi`?

> I also noticed that the $env:temp value is altered to include a folder path of 1 i.e. C:\users<username>\AppData\Local\Temp\1 where the system defined value does not include this folder in the path for $env:temp

Typically env vars are just inherited from the parent that launched PowerShell. When you run through certain logons, like RDP, compared to a direct console logon; Windows will add the suffix. For example when I login through RDP the temp path ends with `\2`.

**Comment by jcoryatjr** [comment]
I closed the issue. Restarted my system and started seeing it in non-elevated command window as well. The elevated command window still shows the correct user temp folder path. Sorry for any inconvenience caused and thank you for the information.Jim
