### ISSUE TITLE
Include more info in $PSVersionTable, like .NET version

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShell#17059]
### Summary of the new feature / enhancement

Would be great if $PSVersionTable could include some more relevant information to its' environment. For instance:

## OS agnostic

* [New key] .NET version built upon
* [New key] OS Architecture (x64, x86, ARM, ARM64 etc.)
* [New key] Process architecture (x64, x86, ARM, ARM64 etc.)

## Windows

* [Existing key] Update "OS" key to include build number (cumulative)
* [Existing key] Update "OS" key to include edition (Home / Pro / Enterprise)
  * If someone can't get BitLocker cmdlets to work, but running Windows 10 Home.. :)

<hr>

I'm thinking suggested additions in addition to being useful for end users, might be helpful when adding ```$PSVersionTable``` to issues on GitHub too, to give some more context out of the box.

### Proposed technical implementation details (optional)

Add more keys and more info to existing keys, to the hashtable that is $PSVersionTable.

![image](https://user-images.githubusercontent.com/6450056/159868335-850b87c3-97cb-4606-89a6-4c68474716de.png)

**Comment by ArmaanMcleod** [comment]
I've also wondered why `GitCommitId` doesn't actually have a real commit ID? Seems to just mirror `PSVersion`.

**Comment by daxian-dbw** [comment]
@ArmaanMcleod For the stable and preview versions, the commit id is the tag for the release, which happens to be the same as `PSVersoin`. If you are using a daily build, you will see the commit id as in hash code.

**Comment by JamesWTruher** [comment]
The WG discussed this and we're concerned that the $PSVersionTable could grow to be unwieldy (and we would like to keep `PSVersionTable` from trying to have _everything_).  However, we do see the need for diagnostic tools which collect this information (and perhaps more). We would be happy to entertain proposals for _additional_ tools to provide that.
