### ISSUE TITLE
Powershell 7.2.2 does not show missing dll popup when running an application on Windows

### ISSUE THREAD

**Issue by alcroito** [PowerShell/PowerShell#17060]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When opening a windows application that can't find a required dll in powershell, the usual dialog that mentions that a .dll is not found is not shown.
It is shown when opening the application directly from within cmd.exe.

This is similar to https://github.com/microsoft/terminal/issues/9788#issuecomment-817920167 except there is no Windows terminal involved, I'm running powershell 7.2.2 directly from the windows start menu, which was installed via an .msi installer.

### Expected behavior

```console
A dialog / popup mentioning which dll is missing
```

### Actual behavior

```console
No dialog shown, no stdout / stderr either.
```

### Environment data

```powershell
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

No results in powershell
<img width="885" alt="Screenshot 2022-03-24 at 17 13 02" src="https://user-images.githubusercontent.com/252084/159961194-3fb0a042-705f-46d8-836a-0290823b4524.png">

Proper dialog when run from cmd.exe
<img width="902" alt="Screenshot 2022-03-24 at 17 13 42" src="https://user-images.githubusercontent.com/252084/159961330-5c84e2a7-fed3-4e3c-b3a1-b17f2df6ae86.png">

**Comment by daxian-dbw** [comment]
Thanks for reporting this. It's a duplicate of #16468

**Comment by alcroito** [comment]
Sorry, i searched the issues, but i guess my terms were not good enough. Thanks for linking!
