### ISSUE TITLE
Object specifies the type of printer (Software/Hardware) | Get-Printer cmdlet

### ISSUE THREAD

**Issue by My3hab** [PowerShell/PowerShell#17066]
### Summary of the new feature / enhancement

Microsoft Windows operating system comes with preinstalled virtual printers such as _Microsoft Print to PDF_, _Microsoft XPS Document Writer_, _Fax_, etc.

Sometimes it is required to select only the hardware printers (Cannon, HP, etc.).

The ```Get-Printer``` cmdlet does not have an object that differentiates between hardware and software printers. 

I'm suggesting to introduce a new object to specify the type of printer.

**Comment by iSazonov** [comment]
The cmdlet is not in the repository. Please use Windows Feedback tool or Microsoft forums to share your suggestion.
