### ISSUE TITLE
How do I re-open bug #16960?

### ISSUE THREAD

**Issue by DJackman123** [PowerShell/PowerShell#17069]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I wrote bug #16960 a couple of weeks ago.  Someone prematurely added the "answered" label and the bug was auto-closed.  But it's clear from the conversation in the bug that the behavior is *not* as expected and it should still be an open bug.  I didn't see any way to remove the "answered" label or re-open the bug.  So I'm creating this issue instead.  Is it possible to re-open the bug?  Or should I just create a new identical issue?

### Expected behavior

```console
n/a
```

### Actual behavior

```console
n/a
```

### Environment data

```powershell
n/a
```

**Comment by vexx32** [comment]
Reopened it and removed the auto-closing label. 🙂 

I'll close this one for now.
