### ISSUE TITLE
Immediate Write-Host after Invoke-WebRequest

### ISSUE THREAD

**Issue by dperez83** [PowerShell/PowerShell#17072]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Write-Host "before dl"
Invoke-WebRequest -Uri https://github.com/Naunter/BT_BlockLists/releases/download/master/bt_blocklists.gz -OutFile bt_blocklists.gz 
Write-Host "test 1"
Write-Host "test 2"
Write-Host "test 3"
Write-Host "test 4"
```

### Expected behavior

```console
Immediate Write-Host "test 1" after Invoke-WebRequest should be written on console.
```

### Actual behavior

```console
"test 1" is not written.
```

### Error details

```console
No error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/42227137/160304224-69f7bbdc-9c46-4f1b-bf76-61ef9e06849f.png)

**Comment by 237dmitry** [comment]
I think this is terminal problem. I could not reproduce.

![ArcoLinux_2022-03-28_12-48-37](https://user-images.githubusercontent.com/78153320/160372673-788f6931-c644-42ac-9186-b55bc5a36bfe.png)

**Comment by dperez83** [comment]
Thank you for your test. The problem only seems to happen with the integrated terminal on Visual Studio Code. Just opened an issue on PowerShell/vscode-powershell : https://github.com/PowerShell/vscode-powershell/issues/3895

Thank you
