### ISSUE TITLE
Class with hidden property breaking for-display formatting?

### ISSUE THREAD

**Issue by santisq** [PowerShell/PowerShell#17071]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Object instances with _hidden or private_ properties could be breaking the [for-display formatting](https://stackoverflow.com/questions/71631192/implicit-conversion-to-bool-of-struct-defined-in-c-sharp-fails-in-powershell/71632418?noredirect=1#comment126599208_71632418) when piped to `Get-Member` as well as `Select-Object *`.

```powershell
class MyBool2 {
    hidden [bool] $Value
    
    MyBool2([bool] $Value) {
        $this.Value = $Value
    }

    [string] ToString() {
        return "$($this.Value)"
    }
}
```

### Expected behavior

```powershell
PS /> $instance = [MyBool2] $true
PS /> $instance
True

PS /> $instance | Get-Member

   TypeName: MyBool2

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()

PS /> $instance
True

PS /> $instance.ToString()
True
```

### Actual behavior

```powershell
PS /> $instance = [MyBool2] $true
PS /> $instance
True

PS /> $instance | Get-Member

   TypeName: MyBool2

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()

PS /> $instance


PS /> $instance.ToString()
True
```

### Error details
_No errors._

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by zett42** [comment]
It might be hard to see, the output of `$instance` after the call to `Get-Member` only consists of a newline instead of the expected `True`.

**Comment by kasini3000** [comment]
Seems this a vague question，
Actual behavior same with Expected behavior

**Comment by zett42** [comment]
> Actual behavior same with Expected behavior

It isn't. Compare the output of `$instance` after call to `Get-Member`.

Expected:
~~~powershell
PS /> $instance | Get-Member
...
PS /> $instance
True
~~~

Actual:
~~~powershell
PS /> $instance | Get-Member
...
PS /> $instance

~~~
Note that there is just an **empty line** in the actual output of `$instance`.

When inserting a `[Console]::WriteLine()` call in the `ToString()` method, we can observe that `ToString()` isn't even called anymore. It appears that `Get-Member` corrupts the object in a way that its default output no longer works.

The corruption only occurs for the object that gets passed to `Get-Member`. When creating a new instance of `MyBool2` afterwards, it's output is correct again.

More observations:
~~~powershell
$instance | Get-Member
"$instance"                   # works
$instance | Out-String  # doesn't work
~~~

**Conclusion:** Any output that involves PowerShell's **formatting system** appears to be broken.

**Comment by kasini3000** [comment]
I understood the problem and found inconsistent behavior.


```powershell
class MyBool2
{
	hidden [bool] $Value

	MyBool2([bool] $V)
	{
		$this.Value = $V
	}

	[string] ToString()
	{
		if ($this.Value -eq $true)
		{
			return 'true'
		}
		else
		{
			return 'false'
		}
	}
}
'-----1----'
$instance = [mybool2] $true
$instance
'-----2----'
$instance  | Get-Member
$instance
'-----3----'
"$instance"

```

## ps 5.1,ps 6.2.7:

```
-----1----
true
-----2----


   TypeName: MyBool2
Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
true
-----3----
true
```


## ps 7.3.3
```
-----1----
true
-----2----

   TypeName: MyBool2

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()

-----3----
true

```
