### ISSUE TITLE
 Where-Object returns abnormally when only 1 object matched

### ISSUE THREAD

**Issue by aksssdf** [PowerShell/PowerShell#17083]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a Problem when using  Where-Object to filter objects.
1.When **only 1** object matched, Where-Object returns **abnormally**. 
FinaList.Count is 2 instead of 1. And FinaList[0] is ('xxx') instead of ('xxx','bbb').
_Code：_
$OutPutList = [System.Collections.ArrayList]::new()
$OutPutList.Add(@('xxx','bbb')) | Out-Null
$OutPutList.Add(@('mmm','bbb')) | Out-Null
$OutPutList.Add(@('myy','bbb')) | Out-Null
$FinaList = $OutPutList | Where-Object {$_[0] -like "x*"}
$FinaList.Count 
$FinaList[0]
_Output：_
![image](https://user-images.githubusercontent.com/102647035/160763063-c48f84af-7b3e-4f34-b891-8e2dc2f8466a.png)

2.When **2** objects matched, Where-Object returns **correctly**.
FinaList.Count is 2. And FinaList[0] is ('mmm','bbb').
_Code：_
$OutPutList = [System.Collections.ArrayList]::new()
$OutPutList.Add(@('xxx','bbb')) | Out-Null
$OutPutList.Add(@('mmm','bbb')) | Out-Null
$OutPutList.Add(@('myy','bbb')) | Out-Null
$FinaList = $OutPutList | Where-Object {$_[0] -like "m*"}
$FinaList.Count 
$FinaList[0]
_Output：_
![image](https://user-images.githubusercontent.com/102647035/160763734-db69989c-8517-4424-acc5-d955bbc0b072.png)

### Expected behavior

```console
$OutPutList = [System.Collections.ArrayList]::new()
$OutPutList.Add(@('xxx','bbb')) | Out-Null
$OutPutList.Add(@('mmm','bbb')) | Out-Null
$OutPutList.Add(@('myy','bbb')) | Out-Null
$FinaList = $OutPutList | Where-Object {$_[0] -like "x*"}
$FinaList.Count 
$FinaList[0]
Output：
1
xxx
bbb
```

### Actual behavior

```console
$OutPutList = [System.Collections.ArrayList]::new()
$OutPutList.Add(@('xxx','bbb')) | Out-Null
$OutPutList.Add(@('mmm','bbb')) | Out-Null
$OutPutList.Add(@('myy','bbb')) | Out-Null
$FinaList = $OutPutList | Where-Object {$_[0] -like "x*"}
$FinaList.Count 
$FinaList[0]
Output：
2
xxx
```

### Environment data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
If I understand it correctly this is because Where-Object is outputting objects that match. When there is only one object you get that actual object back rather than a single array of 1 object. If you get multiple matches you get multiple objects back which is encapsulated inside an array. To always ensure you have an array back, whether it be empty or a single entry, wrap your pipeline inside `@()`, e.g.

```ps
$obj = @(1..3 | Where-Object { $_ -eq 2 })
```

By putting it inside the array subexpression it will ensure that the output is always an array. Even if you have multiple matches it will be those matches as array elements rather than an array in an array.

**Comment by aksssdf** [comment]
thanks @jborean93 Seem to have correct output after adding @ ()

> $OutPutList = [System.Collections.ArrayList]::new()
> $OutPutList.Add(@('xxx','bbb')) | Out-Null
>$OutPutList.Add(@('mmm','bbb')) | Out-Null
>$OutPutList.Add(@('myy','bbb')) | Out-Null
>$FinaList = @($OutPutList | Where-Object {$_[0] -like "x*"})
 >$FinaList.Count
1
> $FinaList[0]
xxx
bbb

**Comment by jhoneill** [comment]
> If I understand it correctly this is because Where-Object is outputting objects that match. When there is only one object you get that actual object back rather than a single array of 1 object. If you get multiple matches you get multiple objects back which is encapsulated inside an array. 

**Yes.** When ` Where-Object` was asked to select from arrays, the OP either got one array in` $finalList` - meaning count told him the number of members in that single array,  or `$finallist` was an array of arrays so count told him how many arrays inside it held.     

> By putting it inside the array subexpression it will ensure that the output is always an array. Even if you have multiple matches it will be those matches as array elements rather than an array in an array.

**Yes** another is to add the result to an empty array.
