### ISSUE TITLE
pwsh script stuck at the end of running a native Linux command or binary if the script is called from a program instead of interactively

### ISSUE THREAD

**Issue by yfengBTI** [PowerShell/PowerShell#17082]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a weird one. 
I have a pwsh script that calls `psql` which in turn runs a `.sql` script which runs fine if I invoke the script from shell, but it would stuck if run from a program with `pwsh -file script.ps1`.
(The program is running as root)

I found that the issue is only with Linux binaries or native shell commands.
For example, a simple script like this would be stuck.
```pwsh
ls
```
or 

```pwsh
ls > /tmp/test.out
Set-Content /tmp/continue "good"
```
However, as long as I only use pwsh commands, the script would finish.

Also, the linux binaries like `psql` and `ls` does actually run to finish but stuck at passing back control to the pwsh script.
In the above test script, `/tmp/test.out` does actually get written but the `Set-Content` never gets run.

### Expected behavior

```console
The script continues running
```

### Actual behavior

```console
Stuck at binaries or native commands
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 4.14.268-205.500.amzn2.x86_64 #1 SMP Wed Mar 2 18:38:38 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> For example, a simple script like this would be stuck.

In my environment this simple script did not stuck
![ArcoLinux_2022-03-30_11-56-23](https://user-images.githubusercontent.com/78153320/160793354-2e74c00a-c352-4bed-a42c-a06302ac0964.png)

**Comment by yfengBTI** [comment]
> In my environment this simple script did not stuck

> If I run script (with executable bit) from third-party application (from mc) it works too:

@237dmitry,
It very well is because of the application that I am dealing with.
I did have the executable bit turned on and I also tried with `-NoProfile`.
What's third-party application from mc that you tested with or any other application that can run shell scripts?
I can test them out and if they do work, then it's my app, and if they don't work, then it's my Linux.

**Comment by kasini3000** [comment]
This binary is malicious to pwsh. It should be wanted ;)
what is its name?
Where is his file path?
Where can I download its installation package?

**Comment by 237dmitry** [comment]
> What's funny is that if I call sh /tmp/test.sh that calls pwsh -file /tmp/test.ps1, then it works.

It's hard to say about `/bin/sh` as in ArcoLinux this is symlink to `/bin/bash`. So I can't test real `sh`. You can try such `shebang`:
```
#!/usr/bin/env -S pwsh -noprofile

script body
```

**Comment by yfengBTI** [comment]
> It's hard to say about `/bin/sh` as in ArcoLinux this is symlink to `/bin/bash`. So I can't test real `sh`. You can try such `shebang`:
> 
> ```
> #!/usr/bin/env -S pwsh -noprofile
> ```
> 
> or if in your _Enterprise Server_ /usr/bin/env has not switch key `-S`
> 
> ```
> #!/usr/bin/env pwsh
> ```

Using `bash` instead of `sh` also works fine in my test.
Tried both `shebang`, no luck.

**Comment by andysza** [comment]
I have the same problem - on a fresh install:

[root@localhost ~]# cat /etc/rocky-release
Rocky Linux release 8.6 (Green Obsidian)
[root@localhost ~]# pwsh
PowerShell 7.2.6
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 3737ms.
PS /root> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Tue Aug 2 16:19:42 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /root> ls
anaconda-ks.cfg  install

ls never returns to the prompt.

**Comment by beckerr-rzht** [comment]
I have the same problem with Powershell 7.3.1.

The error seems to occur after the Unix command has terminated and control is returned to powershell readline.

#### Test:
```bash
$ pwsh -noprofile
PowerShell 7.3.1
PS /home/powershell> sleep 5
```
Before the 5 seconds are up, `pstree` displays this:
```bash=
pstree $(ps -e | awk '$NF=="pwsh"{print $1}')
pwsh─┬─sleep
     └─13*[{pwsh}]
```
After 5 seconds the powershell is **still not responding and hangs**, but `pstree` shows:
```bash=
$ pstree $(ps -e | awk '$NF=="pwsh"{print $1}')
pwsh───13*[{pwsh}]
```

### TERM environment variable as workaround?
The problem seems to be related the value of the `TERM` environment variable.
In particular, when `TERM=linux` is used the problem **does not occur**.

#### `TERM=screen-256color` cases powershell to hang:
```bash=
$ env TERM=screen-256color pwsh -noprofile
PowerShell 7.3.1
PS /home/powershell> sleep 5 
```

#### With `TERM=linux` it works like a charm
```bash=
$ env TERM=linux pwsh -noprofile
PowerShell 7.3.1
PS /home/powershell> sleep 5 
PS /home/powershell> 
```


Even if `TERM=linux` seems to be a workaround, I hope this message helps to find the actual cause of the hangs.
