### ISSUE TITLE
Breakpoint set on return doesn't work properly

### ISSUE THREAD

**Issue by PrzemyslawKlys** [PowerShell/PowerShell#17081]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Putting breakpoint on return will stop on next line rather on return itself. 

```powershell
function TestMe {
    [cmdletBinding()]
    param(

    )

    $Test = Get-Verb

    Write-Host "Test"
    return
}

function TestMe2 {
    [cmdletBinding()]
    param(

    )

    $Test = Get-Verb


    if ($test.count -eq 5) {
        Write-Host "test1"
        return
    } elseif ($test.count -eq 1) {
        Write-Host "test"
        return
    }
    Write-Host "Test"
    return
}

TestMe2
```

![image](https://user-images.githubusercontent.com/15063294/160710849-527ec8a3-330b-4383-b18a-8334fd79b767.png)

Originally reported in https://github.com/PowerShell/vscode-powershell/issues/3896

According to @SeeminglyScience it's a PowerShell bug:

![image](https://user-images.githubusercontent.com/15063294/160710991-f8b83f6b-2365-4405-a72f-46ee7afccd17.png)

This gets even worse if you try to do a blank line after return and put a breakpoint on return. 

```powershell
function TestMe2 {
    [cmdletBinding()]
    param(

    )

    $Test = Get-Verb


    if ($test.count -eq 5) {
        Write-Host "test1"
        return
    } elseif ($test.count -eq 1) {
        Write-Host "test"
        return
    }
    Write-Host "Test"
    return

}

TestMe2
```

Breakpoint won't be hit. If you put `return ""` breakpoint will work properly. 

### Expected behavior

```console
Breakpoint should be at return as expected.
```

### Actual behavior

```console
Breakpoint stops 1 line after expected place
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

But is there also for PS 5.1
```

**Comment by SeeminglyScience** [comment]
Yeah the compiler does not create a sequence point for a return statement if there's no argument. Code in question below, we should consider adding an `else` clause that adds a sequence point.

https://github.com/PowerShell/PowerShell/blob/93a0f9b8dc4149fb8ac65a3e6fa47faff099091e/src/System.Management.Automation/engine/parser/Compiler.cs#L5569-L5621

**Comment by SeeminglyScience** [comment]
> I think this is expected. There may be differences of opinion and controversy.

Could you elaborate on why you would not want a breakpoint on `return` to trigger?

> Do we need to submit a Review - Committee?

It's currently open to both the engine and language working groups. Could go to either but it's mostly the same folks and engine meets more frequently so it'll likely be discussed there.

**Comment by kasini3000** [comment]
1 A single return, without any variables after it, represents the end of the function and has no other meaning.

2 Set a breakpoint on the return line, set a breakpoint on the line returned by the return line, or set a breakpoint on the line returned by the next line, the effect is the same.

3 The breakpoint should be set on a separate return line on the previous line, and the breakpoint on the next line, not on the return line.

4 Set a breakpoint on the return line, which looks unprofessional.

5 is just my personal opinion, others may think differently.

**Comment by PrzemyslawKlys** [comment]
Well, you're basically denying me the ability to debug this because you expect me to add another line before return just to be able to find out whether the condition matched. 

```powershell
$MyVar = $true
if ($MyVar -eq $true) {
    return
} else {
    return $false;
}
```

**Comment by SeeminglyScience** [comment]
> 1 A single return, without any variables after it, represents the end of the function and has no other meaning.
>
> 2 Set a breakpoint on the return line, set a breakpoint on the line returned by the return line, or set a breakpoint on the line returned by the next line, the effect is the same.
> 
> 3 The breakpoint should be set on a separate return line on the previous line, and the breakpoint on the next line, not on the return line.

We already create a sequence point for `exit` which is the closest parallel. We also add an extra sequence point at the end of a function pointing to nothing really.

> 4 Set a breakpoint on the return line, which looks unprofessional,likes beginer.

It's pretty useful to place to break to inspect the state before exiting the block. I do it all the time in C#.

More to the point though, are you saying that if a sequence point were added that it would hurt your workflow? If you can think of a way it would negatively impact folks who choose not to set a breakpoint on `return`, that would be helpful in illustrating your objection.

**Comment by PrzemyslawKlys** [comment]
What I'm interested in is consistent behavior. If I set a breakpoint on line X and the script doesn't stop - it means it doesn't work. I have a function that's like 100 lines of code, and in the middle of the code I set a breakpoint on return and it doesn't work. I don't know what happened, was the return never reached? 

I would say fixing bugs has usually more priority than new features - but that's just me - and not something I have the power to manage. Your priorities and plans are not up to me.

**Comment by rkeithhill** [comment]
Having used debuggers for various other languages, I would have expected this to work in PS.  Too bad it doesn't. I agree that setting a breakpoint on a naked return statement is useful.

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this today and agree that it would be ideal if `return` statements had a sequence point.

Marking up for grabs. Note: this will likely not be an easy solve. Anyone looking to take this on should be very familiar with LINQ expression trees.

**Comment by SeeminglyScience** [comment]
> Note: this will likely not be an easy solve. Anyone looking to take this on should be very familiar with LINQ expression trees.

Nvm we were already tracking return label so it turned out to be about as easy as it gets.
