### ISSUE TITLE
virtualenv when activated no information in powershell 7

### ISSUE THREAD

**Issue by vai21** [PowerShell/PowerShell#17080]
### Summary of the new feature / enhancement

this is the image of the virtualenv activated in powershell 7
![image](https://user-images.githubusercontent.com/5057763/160684033-eeffa16e-dfd1-4db9-bbb8-96d1b94f49a6.png)
and this is the image of the virtualenv activated in cmd
![image](https://user-images.githubusercontent.com/5057763/160684236-039e11f1-0f2a-4edc-87cc-9733624ed4f0.png)
I think this feature in CMD is quite informative and useful...
Thank you

**Comment by jborean93** [comment]
How are you activating the venv, if in PowerShell make sure you run the `activate.ps1` script and not just `activate`.

![image](https://user-images.githubusercontent.com/8462645/160687844-8c2817a6-43d0-412a-9f8e-2c68187a0a06.png)
