### ISSUE TITLE
Invoke-Restmethod | If response is <null> I should still see the HTTP Status Code in the error?

### ISSUE THREAD

**Issue by CloudViking86** [PowerShell/PowerShell#17085]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I recently had quite a weird behaviour when using "Invoke-Restmethod";
* I was doing a 'POST' with a payload ("body") that I wasn't actually sure was 100% right
* The response even with the "-Verbose" parameter was;
```
VERBOSE: POST with 4475-byte payload
VERBOSE: received -byte response of content type application/json
Invoke-RestMethod:
```
* Upon checking in Postman I can see that the response body was <null> but I could also see the actual issue; "Status 403 Forbidden" (I had only read-privileges' on the API which explained why my initial GET's where working)

Shouldn't the response from "Invoke-Restmethod" be "403 Forbidden" or similar even though the actual response body is <null>?

When running "Get-Error" to post this there I can clearly see that it is "403" but shouldn't this be shown directly when "Invoke-Restmethod" error out?

Best Regards

### Expected behavior

```console
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
```

### Actual behavior

```console
Invoke-RestMethod:
^ i.e. <null> after the semicolon
```

### Error details

```console
Exception             : 
    Type       : Microsoft.PowerShell.Commands.HttpResponseException
    Response   : StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
                 {
                 Server: nginx/1.21.6
                 Date: Wed, 30 Mar 2022 12:46:38 GMT
                 Transfer-Encoding: chunked
                 Connection: keep-alive
                 Vary: Accept-Encoding
                 Cache-Control: no-cache, no-store, max-age=0, must-revalidate
                 Pragma: no-cache
                 X-Frame-Options: SAMEORIGIN
                 X-Robots-Tag: none
                 X-UA-Compatible: IE=Edge,chrome=1
                 X-Request-ID: 35820fb270233138b1f266f5c9dfaff8
                 X-Runtime: 0.070207
                 Strict-Transport-Security: max-age=15552000; includeSubDomains
                 Content-Type: application/json; charset=utf-8
                 Expires: Fri, 01 Jan 1990 00:00:00 GMT
                 }
    TargetSite : 
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.2.2.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Response status code does not indicate success: 403 (Forbidden).
    Source     : System.Management.Automation
    HResult    : -2146233088
    StackTrace : 
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Method: POST, RequestUri: 'https://api.meraki.com/api/v1/networks/<redacted>/groupPolicies', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
                        {
                        Authorization: Bearer <redacted>
                        Accept: application/json
                        User-Agent: Mozilla/5.0
                        User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.19044; en-US)
                        User-Agent: PowerShell/7.2.2
                        Content-Length: 4475
                        Content-Type: application/json
                        }
CategoryInfo          : InvalidOperation: (Method: POST, Reque…application/json
                        }:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          : 
InvocationInfo        : 
    MyCommand        : Invoke-RestMethod
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 30
    Line             : Invoke-Restmethod -Headers $headers -Method POST -Uri $($meraki_baseurl + $meraki_networks + "/" + $get_networkid_jpn + "/" + "groupPolicies") -Body $grouppolicy_json -PreserveAuthorizationOnRedirect -Verbose
    PositionMessage  : At line:1 char:1
                       + Invoke-Restmethod -Headers $headers -Method POST -Uri $($meraki_baseu …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-Restmethod
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
ame                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![prntscrn_pscore_invoke-restmethod_403_bugreport_300322](https://user-images.githubusercontent.com/45990856/160843557-763a976d-5e9a-4626-bf9f-57bf0e981081.PNG)

**Comment by OsvaldoRino** [comment]
> ### Prerequisites
> * [x]  Write a descriptive title.
> * [x]  Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
> * [x]  Search the existing issues.
> * [x]  Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
> * [x]  Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).
> 
> ### Steps to reproduce
> I recently had quite a weird behaviour when using "Invoke-Restmethod";
> 
> * I was doing a 'POST' with a payload ("body") that I wasn't actually sure was 100% right
> * The response even with the "-Verbose" parameter was;
> 
> ```
> VERBOSE: POST with 4475-byte payload
> VERBOSE: received -byte response of content type application/json
> Invoke-RestMethod:
> ```
> 
>  * Upon checking in Postman I can see that the response body was  but I could also see the actual issue; "Status 403 Forbidden" (I had only read-privileges' on the API which explained why my initial GET's where working)
> 
> Shouldn't the response from "Invoke-Restmethod" be "403 Forbidden" or similar even though the actual response body is ?
> 
> When running "Get-Error" to post this there I can clearly see that it is "403" but shouldn't this be shown directly when "Invoke-Restmethod" error out?
> 
> Best Regards
> 
> ### Expected behavior
> ```
> Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
> ```
> 
> ### Actual behavior
> ```
> Invoke-RestMethod:
> ^ i.e. <null> after the semicolon
> ```
> 
> ### Error details
> ```
> Exception             : 
>     Type       : Microsoft.PowerShell.Commands.HttpResponseException
>     Response   : StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
>                  {
>                  Server: nginx/1.21.6
>                  Date: Wed, 30 Mar 2022 12:46:38 GMT
>                  Transfer-Encoding: chunked
>                  Connection: keep-alive
>                  Vary: Accept-Encoding
>                  Cache-Control: no-cache, no-store, max-age=0, must-revalidate
>                  Pragma: no-cache
>                  X-Frame-Options: SAMEORIGIN
>                  X-Robots-Tag: none
>                  X-UA-Compatible: IE=Edge,chrome=1
>                  X-Request-ID: 35820fb270233138b1f266f5c9dfaff8
>                  X-Runtime: 0.070207
>                  Strict-Transport-Security: max-age=15552000; includeSubDomains
>                  Content-Type: application/json; charset=utf-8
>                  Expires: Fri, 01 Jan 1990 00:00:00 GMT
>                  }
>     TargetSite : 
>         Name          : ThrowTerminatingError
>         DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.2.2.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
>         MemberType    : Method
>         Module        : System.Management.Automation.dll
>     Message    : Response status code does not indicate success: 403 (Forbidden).
>     Source     : System.Management.Automation
>     HResult    : -2146233088
>     StackTrace : 
>    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
> TargetObject          : Method: POST, RequestUri: 'https://api.meraki.com/api/v1/networks/<redacted>/groupPolicies', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
>                         {
>                         Authorization: Bearer <redacted>
>                         Accept: application/json
>                         User-Agent: Mozilla/5.0
>                         User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.19044; en-US)
>                         User-Agent: PowerShell/7.2.2
>                         Content-Length: 4475
>                         Content-Type: application/json
>                         }
> CategoryInfo          : InvalidOperation: (Method: POST, Reque…application/json
>                         }:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
> FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> ErrorDetails          : 
> InvocationInfo        : 
>     MyCommand        : Invoke-RestMethod
>     ScriptLineNumber : 1
>     OffsetInLine     : 1
>     HistoryId        : 30
>     Line             : Invoke-Restmethod -Headers $headers -Method POST -Uri $($meraki_baseurl + $meraki_networks + "/" + $get_networkid_jpn + "/" + "groupPolicies") -Body $grouppolicy_json -PreserveAuthorizationOnRedirect -Verbose
>     PositionMessage  : At line:1 char:1
>                        + Invoke-Restmethod -Headers $headers -Method POST -Uri $($meraki_baseu …
>                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     InvocationName   : Invoke-Restmethod
>     CommandOrigin    : Internal
> ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
> ```
> 
> ### Environment data
> ```powershell
> ame                           Value
> ----                           -----
> PSVersion                      7.2.2
> PSEdition                      Core
> GitCommitId                    7.2.2
> OS                             Microsoft Windows 10.0.19044
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
> 
> ### Visuals
> ![prntscrn_pscore_invoke-restmethod_403_bugreport_300322](https://user-images.githubusercontent.com/45990856/160843557-763a976d-5e9a-4626-bf9f-57bf0e981081.PNG)

**Comment by jhoneill** [comment]
The error details field contains the page body that was returned, and that is what is shown in a short error. In this case its null. I just tried creating a 404 error and got masses of text in the message and where you have a blank line where you get the error.  Null pages or massively verbose ones aren't helpful. But there will be scripts out there which look for things in the body returned as a response when there is an error, so changing this would break things.
