### ISSUE TITLE
When running remote pwsh over SSH - PS7.2.2 adds $' and \r' to anything returned

### ISSUE THREAD

**Issue by rcrum003** [PowerShell/PowerShell#17094]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Happens with 7.2.2, doesn't happen with 6.x

Linux Host -> Windows Host over SSH
`ssh -n -o myaccount@windowserver "pwsh.exe c:\mydir\basicscript.ps1"`
The basicscript.ps1 simply 
`write-output "foo"`

returns:
`$'foo\r'`

### Expected behavior

```console
Expected output
foo
```

### Actual behavior

```console
returns:
`$'foo\r'`
```

### Error details

```console
Powershell returns no error
```

### Environment data

```powershell
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rcrum003** [comment]
Note: setting:
`$PSStyle.OutputRendering = 'PlainText' `
or
` $PSStyle.OutputRendering = 'Host' `

Had no effect on behavior

**Comment by jborean93** [comment]
I cannot seem to replicate this, the output seems to be returning just fine. Can you share the following:

* What's the sshd version on the Windows host?

```powershell
$service =  Get-CimInstance -ClassName Win32_Service -Filter "PathName LIKE '%sshd.exe%'"
(Get-Item -Path $service.PathName.Trim('"')).VersionInfo | Select FileVersion, ProductVersion, FileName
```

* What's your `DefaultShell` set to for ssh, is it cmd, powershell, pwsh, something else?

```powershell
Get-ItemPropertyValue -Path HKLM:\SOFTWARE\OpenSSH -Name DefaultShell
# If prop does not exist it will be cmd
```

* What's the shell of the Linux host, are you just running this from bash, pwsh, something else?

* Do you have anything set in `~/.ssh/config` for the Windows host you are connecting to?

I'm also curious what the `-n -o` arguments are meant to be for. I can see `-n` refers to setting stdin to `/dev/null` but `-o` usually needs to be set with an actual option rather than signifying something by itself.

**Comment by kasini3000** [comment]
After install microsoft OMI or jborean93/omi , then you can connect from linux to windows by WINRM-5985 (ntlm).
you can use this script: free
https://gitee.com/chuanjiao10/kasini3000/blob/master/k_run_ip_port_l2w_user_pwd.ps1
but OMI has some bug ,sctipt file name on windows does not support characters other than English.

there has a Chargeable script for batch,20$.you can contact me .

----

kasini3000
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline)
Open source, free, cross-platform
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

kasini3000_agent_linux Shell script,one click install powershell on linux,modify sshd_config for PsRemote.

I love powershell, this project is my dedication.
The slogan of this project is "ditch the YAML, powershell makes the command line great again."
