### ISSUE TITLE
Default color scheme is unusable on Mac

### ISSUE THREAD

**Issue by GrantMeStrength** [PowerShell/PowerShell#17097]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install PowerShell on Mac following instructions 

### Expected behavior

```console
Readable text
```

### Actual behavior

```console
yellow text on white background, breaking accessibility guidelines
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Screen Shot 2022-04-01 at 2 30 01 PM](https://user-images.githubusercontent.com/1928855/161345039-eb824103-3e4c-420f-9086-a1b00992f8e2.png)

**Comment by corbob** [comment]
Allow me to show that 7.3.0 is going to make this absolutely unusable without piping through `out-string` (unless there's a way to turn this coloring off that I have not yet found 🤔 )
<img width="239" alt="2022-06-11_18-13-25" src="https://user-images.githubusercontent.com/30301021/173210127-bacee237-3960-4d63-81ef-e68527e4d4ed.png">

**Comment by theJasonHelmick** [comment]
Hi @GrantMeStrength - I'm not sure which terminal your using, however the color scheme is defined in PSReadLine and works well for black and dark blue backgrounds.  The good news is you can change the colors of each individual element to adjust to your color preferences.  The cmdlet to see the colors is Get-PSReadLineOption - and here is a link to documentation on how to change the colors to your needs -> https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.2#example-1-set-foreground-and-background-colors

**Comment by rkeithhill** [comment]
It is worth noting that the "default" color scheme on the macOS Terminal has a white background. I switched to the "Pro" profile which has a black background since PS looks way better on a dark background. It is too bad PS can't detect the bg (dark/light) and adjust the default colors for the background.
