### ISSUE TITLE
get-help about_<topics> does not work on Linux

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#1709]
## Steps to reproduce

get-help about_<topic>
## Expected behavior

Get-help returns all the matches for given topic
## Actual behavior

Get-help is unable to find the about topics help files
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by Liturgist** [comment]
I agree that the problem is with wildcards. Entering the full, correct name works. Ubuntu 16.04 running 6.0.0-alpha.10.

**Comment by NReilingh** [comment]
@jpsnover Is it possible this is related to #2028? There are some interesting discoveries in that thread that are even affecting PS5 help on Windows.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
