### ISSUE TITLE
Issue with multidimensional array

### ISSUE THREAD

**Issue by aelsantex** [PowerShell/PowerShell#17108]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is good:
PS> $test=@{ 'A' = @( @("Text 1", "Text 2"), @("Check 1", "Check 2") ) }
PS> foreach ($key in $test.Keys) { foreach ($item in ($test[$key])) { "Test $($key) with item: $($item[0]) $($item[1])" } }
Test A with item: Text 1 Text 2
Test A with item: Check 1 Check 2

But with only one element into the first level array:
PS> $test=@{ 'A' = @( @("Text 1", "Text 2") ) }
PS> foreach ($key in $test.Keys) { foreach ($item in ($test[$key])) { "Test $($key) with item: $($item[0]) $($item[1])" } }
Test A with item: T e
Test A with item: T e

### Expected behavior

```console
PS> $test=@{ 'A' = @( @("Text 1", "Text 2") ) }
PS> foreach ($key in $test.Keys) { foreach ($item in ($test[$key])) { "Test $($key) with item: $($item[0]) $($item[1])" } }
Test A with item: Text 1 Text 2
```

### Actual behavior

```console
PS> $test=@{ 'A' = @( @("Text 1", "Text 2") ) }
PS> foreach ($key in $test.Keys) { foreach ($item in ($test[$key])) { "Test $($key) with item: $($item[0]) $($item[1])" } }
Test A with item: T e
Test A with item: T e
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
The `@()` syntax only ensures that it's contents are in an array. If it's contents are already in an array, it will do nothing.

In this scenario you want a unary comma:

```powershell
$test=@{ 'A' = ,@("Text 1", "Text 2") }
foreach ($key in $test.Keys) {
    foreach ($item in ($test[$key])) {
        "Test $($key) with item: $($item[0]) $($item[1])"
    }
}
```
