### ISSUE TITLE
PowerShell Get-Help not displaying local script's Comment Based Help

### ISSUE THREAD

**Issue by FilBot3** [PowerShell/PowerShell#17109]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am providing PowerShell Core 7.2.2 on Fedora 35 Linux a PowerShell script that I have written locally. At the top of the file, I have a comment based help section with synopsis, description, and a link. However, when I use `Get-Help` nothing shows. The same happens when I use help except it opens a pager.

```powershell
<#
.NAME
    Export-ADOlibrary-RestAPI.ps1

.SYNOPSIS
    Export Azure DevOps Library Groups into JSON files.

.DESCRIPTION
    Export an Azure DevOps Library Group into a JSON file. Then use that file to
    set some parameters and save them as encrypted files in the Azure DevOps Git
    Repo.

.NOTE
    This script was written by person of company for project.
#>

Write-Host "This is some output."
```

However, when I use the `Get-Help` and `help` commands, this is what I get

```powershell
> Get-Help ./Export-ADOlibrary-RestAPI.ps1
Export-ADOlibrary-RestAPI.ps1 

```

Same thing for `help ./Export-ADOlibrary-RestAPI.ps1`.

I should see the same thing as what's being described in the documentation for [Comment Based Help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.2#comment-based-help-for-a-function). 

### Expected behavior

```console
Display Comment Based Help
```

### Actual behavior

```console
Nothing displays
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.16.18-200.fc35.x86_64 #1 SMP PREEMPT Mon Mar 28 14:10:07 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by FilBot3** [comment]
Same deal even after removing NAME and modifying NOTE to NOTES

```powershell
> Get-Help ./Export-ADOlibrary-RestAPI.ps1
Export-ADOlibrary-RestAPI.ps1 

> Get-Help ./Export-ADOlibrary-RestAPI.ps1 -Full
Export-ADOlibrary-RestAPI.ps1 

> head -n15 ./Export-ADOlibrary-RestAPI.ps1
<#
.SYNOPSIS
    Export Azure DevOps Library Groups into JSON files.

.DESCRIPTION
    Export an Azure DevOps Library Group into a JSON file. Then use that file to
    set some parameters and save them as encrypted files in the Azure DevOps Git
    Repo.

    This script is an interactive script. The user will be prompted for input
    to override the defaults.

.NOTES
    This script was written by person of company for project.
#>
```

**Comment by FilBot3** [comment]
I see the [Autogetnerated Content](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.2#autogenerated-content) listing the NAME as you said.

**Comment by SeeminglyScience** [comment]
> Same deal even after removing NAME and modifying NOTE to NOTES

Make sure it's in a new session, help content (including lack of) is cached.

Also ensure you don't have a function directly after the help context, if you do then you need to include two new lines or a `param()` statement.

**Comment by FilBot3** [comment]
That was it. There was a comment directly after the closing `#>`. Is that called out anywhere and I missed it?

**Comment by SeeminglyScience** [comment]
It's called out a little bit in [#comment-based-help-for-a-script](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.2#comment-based-help-for-a-script). I usually try to ensure that I have a `param()` statement following it immediately, e.g.

```powershell
<#
.SYNOPSIS
    Export Azure DevOps Library Groups into JSON files.
#>
param()

etc
```

**Comment by FilBot3** [comment]
Of course, my eyes skipped over it and went straight to the code examples. Thank you @SeeminglyScience
