### ISSUE TITLE
Network share path expansion should support forward slashes

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#17111]
### Summary of the new feature / enhancement

As a user using the French keyboard layout, entering a forward slash (`Shift+:`) is _way more convenient_ than entering a backslash (`AltGr+8`). So using forward slashes throughout PowerShell has become muscle memory...

This works in most cases.

Alas, tab expansion for inputs like

````
\\hostname\x<TAB>
````

works, but this doesn't:

````
//hostname/x<TAB>
````

**Comment by MartinGC94** [comment]
This is handled here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4304 at a glance, it looks like a relatively simple thing to fix.

**Comment by sba923** [comment]
Had almost found it 😆, now I need to remember how to build the repo and will give it a shot!

**Comment by sba923** [comment]
Tomorrow is another day 😜

![image](https://user-images.githubusercontent.com/12860484/161831268-10435b01-1db1-4932-95b9-3f2b01363506.png)

**Comment by SeeminglyScience** [comment]
@sba923 You just wanna add `-ResGen`

**Comment by sba923** [comment]
Is adding this comment OK? What's the preferred way of referring to issues? Absolute GH URL or `#nnnnn`?

```csharp
// support both / and \ when entering UNC paths for typing convenience (#17111)
```

**Comment by SeeminglyScience** [comment]
> Build still emits this error... _after_ producing `pwsh.exe`:

Yeah I dunno what's up with that but I get it too so 🤷 

> ![image](https://user-images.githubusercontent.com/12860484/161839276-c671e52f-c811-47e0-a2d6-8279a9d9eaa4.png)
> 
> Is that good enough or would you consider optimizing the regex?

That can be settled in the review. I would recommend making it a literal (`@"pattern here"`) instead though so it's somewhat feasible to read 😁 (I know it was like that before, but while we're there might as well).

> Is adding this comment OK? What's the preferred way of referring to issues? Absolute GH URL or `#nnnnn`?

I think that's good, but also can be settled in the review if needed.

**Comment by sba923** [comment]
OK. This works fine, so I'll proceed with creating the PR:

![image](https://user-images.githubusercontent.com/12860484/161992753-30b88235-0a8b-48c6-8737-fd57f9cc3635.png)

**Comment by sba923** [comment]
PR https://github.com/PowerShell/PowerShell/pull/17117 created. Was not completely sure about the "impact completers" section of the checklist, though.
