### ISSUE TITLE
Powershell 7.2.2/7.3.0 adds Content-Length header to Invoke-RestMethod Get request

### ISSUE THREAD

**Issue by kevinrr3** [PowerShell/PowerShell#17118]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

While working with a rest api of a ITSM system we're using I ran into the issue that I was able to use PowerShell 5.1 to issue GET request via the Invoke-RestMethod cmdlet but when I did the same on PowerShell 7.2.2/7.3.0 the request always seemed to fail with an http 400 error. I did some digging around with Fiddler and I found that the request done with PowerShell 7.2.2 added a Content-Length header to the request.

**Request details when done from PowerShell 5.1:**

```
GET https://api.somesite.com/v1/me HTTP/1.1
Authorization: Bearer xxxxxxx
User-Agent: Mozilla/5.0 (Windows NT; Windows NT 10.0; nl-NL) WindowsPowerShell/5.1.19041.1320
Content-Type: application/json
Host: api.somesite.com
Connection: Keep-Alive
```

**Request details when done from PowerShell 7.2.2/7.3.0:**

```
GET https://api.somesite.com/v1/me HTTP/1.1
Host: api.somesite.com
Authorization: Bearer xxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19044; nl-NL) PowerShell/7.3.0
Content-Type: application/json
Content-Length: 0
```

### Expected behavior

```console
Invoke-RestMethod -Method Get should not add Content-Length header to request
```

### Actual behavior

```console
Invoke-RestMethod -Method Get does add Content-Length header to request
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment]
Is this an issue in PowerShell, or is it .NEET adding this header?

**Comment by kevinrr3** [comment]
Probably PowerShell because 5.1 doesn't show this behaviour.

**Comment by CarloToso** [comment]
Can't reproduce bug with PS 7.3.1
Test: `(Invoke-WebRequest "https://httpbin.org/get").BaseResponse.RequestMessage.Content.Headers` --> Nothing
