### ISSUE TITLE
PowerShell 7.2.2 /7.2.5 /7.3.0-preview.3 startsp slowly in win10 computer without internet

### ISSUE THREAD

**Issue by SuperCatss** [PowerShell/PowerShell#17119]
### Prerequisites

- [X] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Download and install through GitHub, each startup needs to wait 10 seconds

### Expected behavior

```console
Directly start "C:\Program Files\PowerShell\7\pwsh.exe"
```

### Actual behavior

```console
be able to enter immediately
```

### Error details

```console
No Error
```

### Environment data

```powershell
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![QQ图片20220407141843](https://user-images.githubusercontent.com/24800663/162133278-3f2dc501-8b45-4c9b-b0a6-ad3cdaa88464.png)

**Comment by SuperCatss** [comment]
I have read,
[https://github.com/PowerShell/PowerShell/issues/10983](url)
[https://superuser.com/questions/578065/powershell-very-slow-to-open-respond](url)
[https://stackoverflow.com/questions/59341482/powershell-steps-to-fix-slow-startup](url)
 but I didn't get help.
I have disabled the startup update detection, but the startup is still slow

**Comment by jhoneill** [comment]
It may be Telemetry trying to find its server in which case Setting the environment variable  `POWERSHELL_TELEMETRY_OPTOUT` to true, yes, or 1 might help

But I think this is checking to see if there is a new version, and if it can't contact the server there is a timeout issue. 

Paging @doctordns  - you've said you'd like PowerShell not to give the message about new versions when they are setup to come from WU and it doesn't have them yet,  should "no check for new versions at all"  be an option for (e.g.) servers which aren't allowed internet access.

**Comment by doctordns** [comment]
Thanks for the page @jhoneill!

So on the day when 7.2.2 was released, as expected, I get the message that there is a new version. FIne, I thought, I KNOW I d setup MU to update it. But the error is not going away - I will need to wait a MONTH. My reaction is not positive. If an update is important enough for me to be notified, then we need to get the package to MU faster. I mean - how long would MSFT wait to fix CVE types bugs??   

And - unlike VSCode which can fix this issue, there is no ```Update-PowerShell``` cmdlet in the console. So either I just wait a month and get annoyed at each console I open - or I just go and run the update manually. Seems somewhat sub-optimal.😊All in all, the message, for most users, is not actionable easily. 

There are several suggestions;
1. Ensure MU gets and pushes upgrades in less than a month. Seems to me that the update would be available on MU within 48 hours of it being on GitHub. That may need more work but it seems the best answer.
2. In the absence for a in-box ```Update-PowerShell``` cmdlet, PowerShell should not put the message out until the update is on MU. 
3. Perhaps give MU 2 weeks and only show the message after, say., 2 weeks.
4. Change the message to tell the user what to do -that is, give them a simple way to fix the issue. 
5. Create, as James suggests, environment variables to tell PowerShell what to do in the case a new version, if found. Your point about air-gapped servers is apt!

**Comment by SuperCatss** [comment]
> It may be Telemetry trying to find its server in which case Setting the environment variable `POWERSHELL_TELEMETRY_OPTOUT` to true, yes, or 1 might help
> 
> But I think this is checking to see if there is a new version, and if it can't contact the server there is a timeout issue.
> 
> Paging @doctordns - you've said you'd like PowerShell not to give the message about new versions when they are setup to come from WU and it doesn't have them yet, should "no check for new versions at all" be an option for (e.g.) servers which aren't allowed internet access.

Thanks for your help, it looks like it's working now.

**Comment by SuperCatss** [comment]
> Thanks for the page @jhoneill!
> 
> So on the day when 7.2.2 was released, as expected, I get the message that there is a new version. FIne, I thought, I KNOW I d setup MU to update it. But the error is not going away - I will need to wait a MONTH. My reaction is not positive. If an update is important enough for me to be notified, then we need to get the package to MU faster. I mean - how long would MSFT wait to fix CVE types bugs??
> 
> And - unlike VSCode which can fix this issue, there is no `Update-PowerShell` cmdlet in the console. So either I just wait a month and get annoyed at each console I open - or I just go and run the update manually. Seems somewhat sub-optimal.blushAll in all, the message, for most users, is not actionable easily.
> 
> There are several suggestions;
> 
> 1. Ensure MU gets and pushes upgrades in less than a month. Seems to me that the update would be available on MU within 48 hours of it being on GitHub. That may need more work but it seems the best answer.
> 2. In the absence for a in-box `Update-PowerShell` cmdlet, PowerShell should not put the message out until the update is on MU.
> 3. Perhaps give MU 2 weeks and only show the message after, say., 2 weeks.
> 4. Change the message to tell the user what to do -that is, give them a simple way to fix the issue.
> 5. Create, as James suggests, environment variables to tell PowerShell what to do in the case a new version, if found. Your point about air-gapped servers is apt!

I have manually updated to 7.2.5 and the problem reappeared. and I have set the relevant environment variables.

![image](https://user-images.githubusercontent.com/24800663/182303830-4152b608-4c50-4c54-b7e6-83e465d2dfea.png)

**Comment by SuperCatss** [comment]
This is a historical issue. It looks like the same problem has existed since 2019.
> https://github.com/PowerShell/PowerShell/issues/10983

If anyone has the same problem, please refer to the link below. It solved my problem.
> https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-779819256

**Comment by SuperCatss** [comment]
> 

Now my startup time has changed from 5-10 seconds to 2-3 seconds.

> This is a historical issue. It looks like the same problem has existed since 2019.
> 
> > #10983
> 
> If anyone has the same problem, please refer to the link below. It solved my problem.
> 
> > [#10983 (comment)](https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-779819256)

Now my startup time has changed from 5-10 seconds to 2-3 seconds.

**Comment by doctordns** [comment]
Regarding the time it takes for MU to get and then deploy the updated version of PowerShell. At one time, it did seem to take a month. But, it is taking much less time, it seems to me, these days - down to 2 weeks (or IIRC less recently). You are right that the solution within VSCode is rather more user-friendly.  So it's not QUITE as bad as you suggest, but I do take the point that we can do this better.  Maybe we move to sim-shipping - that is, releasing on GitHub ONLY when the package is available at MU.  Not sure how practical that is, but as I say we can do better.

**Comment by jhoneill** [comment]
> This is a historical issue. It looks like the same problem has existed since 2019.
> 
> > #10983
> 
> If anyone has the same problem, please refer to the link below. It solved my problem.
> 
> > [#10983 (comment)](https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-779819256)

This may get better in 7.3  
If you look at at 7.2 there are a lot of different certs being used to sign modules and DLLs, and pwsh.exe. 

Try 
```
CD $PSHOME
dir -re *.ps*,*powershell*.dll,pwsh.exe  | Get-AuthenticodeSignature | sort @{e={$_.SignerCertificate.Thumbprint}},path |    ft @{n="Cert";e={$_.SignerCertificate.Thumbprint}}, path

```
Repeating it with 7.3 preview things seem to moving to using the same cert as pwsh.exe .

**Comment by SuperCatss** [comment]
> 

Actually, I'm using version 7.2.5 now and the problem persists.

**Comment by SuperCatss** [comment]
> Regarding the time it takes for MU to get and then deploy the updated version of PowerShell. At one time, it did seem to take a month. But, it is taking much less time, it seems to me, these days - down to 2 weeks (or IIRC less recently). You are right that the solution within VSCode is rather more user-friendly. So it's not QUITE as bad as you suggest, but I do take the point that we can do this better. Maybe we move to sim-shipping - that is, releasing on GitHub ONLY when the package is available at MU. Not sure how practical that is, but as I say we can do better.

I don't think it's about the update, it's the fact that the checking of the system certificate in the absence of a network blocks the powershell thread, resulting in a slow startup.

**Comment by SuperCatss** [comment]
> > This is a historical issue. It looks like the same problem has existed since 2019.
> > > #10983
> > 
> > 
> > If anyone has the same problem, please refer to the link below. It solved my problem.
> > > [#10983 (comment)](https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-779819256)
> 
> This may get better in 7.3 If you look at at 7.2 there are a lot of different certs being used to sign modules and DLLs, and pwsh.exe.
> 
> Try
> 
> ```
> CD $PSHOME
> dir -re *.ps*,*powershell*.dll,pwsh.exe  | Get-AuthenticodeSignature | sort @{e={$_.SignerCertificate.Thumbprint}},path |    ft @{n="Cert";e={$_.SignerCertificate.Thumbprint}}, path
> ```
> 
> Repeating it with 7.3 preview things seem to moving to using the same cert as pwsh.exe .
> 
> **EDIT** I think those modules which are built separately and then brought into the PowerShell distribution bundle _still_ select their cert independently, but PsReadline is now using the same cert as the rest of PowerShell.

Actually, I'm using version 7.2.5 now and the problem persists.
Can you tell me how this workaround works?

**Comment by queglay** [comment]
Disabling attempts to look us query the Certificate Revocation List fixes the slowdown, but security may not want you to do this.  Is there a proper solution to this?  Why does a shell need to phone home at all?
