### ISSUE TITLE
[PS 7.2] operator && doesn't recognize exit

### ISSUE THREAD

**Issue by Raffaello** [PowerShell/PowerShell#17122]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using PS 7.2

for eg running this 1 line script:
```powershell
PS C:\> $host.Version | Where-Object {$_.Major -eq 7} && exit 1  
```

it will result in the following error output:
```powershell

Major  Minor  Build  Revision
-----  -----  -----  --------
7      2      2      -1
exit: The term 'exit' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again
```

### Expected behavior

```powershell
Major  Minor  Build  Revision
-----  -----  -----  --------
7      2      2      -1
[process exited with code 1 (0x00000001)]
```

### Actual behavior

```powershell
It doesn't recognize exit keyword
```

### Error details

```powershell
PS C:\>Get-Error

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'exit' is not recognized as a name of a cmdlet, function, script file, or executable
program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
            HResult : -2146233087
        TargetObject          : exit
        CategoryInfo          : ObjectNotFound: (exit:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 50
            HistoryId        : 1
            Line             : $host.Version | Where-Object {$_.Major -eq 7} && exit
            PositionMessage  : At line:1 char:50
                               + $host.Version | Where-Object {$_.Major -eq 7} && exit
                               +                                                  ~~~~
            InvocationName   : exit
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : exit
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation,
Version=7.2.2.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'exit' is not recognized as a name of a cmdlet, function, script file, or executable
program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
SearchResolutionOptions searchResolutionOptions, Com
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Duplicate of #10967

**Comment by Raffaello** [comment]
well actually through the duplicate i found that in this way works:
```powershell
 $host.Version | Where-Object {$_.Major -eq 7} && $(exit 1)

Major  Minor  Build  Revision
-----  -----  -----  --------
7      2      2      -1

[process exited with code 1 (0x00000001)]
```

so, yes it could be more a decisin decision disccusion rather than a bug.

I am closing this ticket as i am not considering it a bug anymore, but more my lack of knoledge in PS. :)

**Comment by jhoneill** [comment]
What comes after && must be a valid as pipeline so  if/while/do/switch/exit/return statements won't work - There's plenty at #10967 but if it doesn't work with the |  it won't work with || or &&

I was about to post the $()  solution but as I was typing your reply appeared 

You do realise that where-object _successfully_ running includes returning _nothing_ so the right hand side always runs in your example :-)

**Comment by jhoneill** [comment]
I'd use an if  - anything which isn't null, 0, empty or $false will be treated as true. (So it's rare to need .count etc)
 
`if ($host.Version.Major -eq 7) { exit 1 }`   
or better
`if ($host.Version -ge 6.0.0 ) { exit 1 }`   

This will exit if the version is 5.0, 6.0, or 7.0
`if (-not $host.Version.Minor) { exit 1 }`   

If it is something complicated I can put a pipeline in the () 

`if ($host.Version | Where-Object {$_.Major -eq 7}) { exit 1 } `

This pattern is quite common
``` $fileList = get-item *.ps1```
```if (-not $fileList)   ```
followed by  one of
``` 
{Write-Warning "No files " ; return}
{throw "no files" }
{exit 2}  # error for 'file not found'
```
and then 
```
foreach ($f in $fileList}
```

Exit as some strange behaviour  have a look at the end of this which I wrote after someone I was talking to was going made working out  why they didn't get an exit code back.   https://jhoneill.github.io/powershell/2019/08/21/ExitThrowReturnEtc.html
