### ISSUE TITLE
Duplicated errors when using $ErrorEnvirable with $ErrorActionPreference = 'Stop'

### ISSUE THREAD

**Issue by dolauli** [PowerShell/PowerShell#17123]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a test.ps1 with following content.
```
function Test-error1 {
    [CmdletBinding()]
    param ()
    process {
        try {
            Test-error2 @PSBoundParameters
        } catch {
            throw
        }
    }
}
function Test-error2 {
    [CmdletBinding()]
    param ()
    process {
        try {
            write-error "This is error#2"
        } catch {
            throw
        }
    }
}
```
2. run following command in PowerShell
```
PS > Import-Module .\test.ps1
PS > $ErrorActionPreference = 'Stop'
PS > Test-error1 -ErrorVariable erroralias
PS > $error
PS > $erroralias
```

### Expected behavior

```console
The output of $erroralias should be the same as $error as below.

PS > $error

Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2
```

### Actual behavior

```console
The actually result is there are duplicated errors as below.

PS > $erroralias

ErrorRecord                 : This is error#2
WasThrownFromThrowStatement : True
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: This is error#2
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : 
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.Runspaces.Pipeline.Invoke()
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)


Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2


Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2


Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2


Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2


Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2


Test-error2: C:\Users\dolauli\source\test\test.ps1:33:13
Line |
  33 |              Test-error2 @PSBoundParameters
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This is error#2


PS C:\Users\dolauli\source\test>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

When $ErrorActionPreference = 'Continue', it works as expected.
![image](https://user-images.githubusercontent.com/11451757/162346033-4acefba7-5134-4910-9206-705be9b1388a.png)

When $ErrorActionPreference = 'Stop', there will be duplicated errors.
![image](https://user-images.githubusercontent.com/11451757/162346203-fbaf5ef0-1e78-4d7f-a534-51179125a044.png)

**Comment by jhoneill** [comment]
![image](https://user-images.githubusercontent.com/16209593/162398185-ad802f01-0eb9-4121-9ef6-3bc62057bd3b.png)

The above suggests the error is only created once.

**Comment by jhoneill** [comment]
Here is a simpler repro
```
#501 PS7 ~\Documents\PowerShell> function foo {1/0}
#502 PS7 ~\Documents\PowerShell> $Error.Count
0
#503 PS7 ~\Documents\PowerShell> foo
RuntimeException: Attempted to divide by zero.
#504 PS7 ~\Documents\PowerShell> $ErrorActionPreference="Stop"
#505 PS7 ~\Documents\PowerShell> foo
ParentContainsErrorRecordException: Attempted to divide by zero.
#506 PS7 ~\Documents\PowerShell> $Error.Count
3
#507 PS7 ~\Documents\PowerShell> $Error[0].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     RuntimeException                         System.SystemException

#508 PS7 ~\Documents\PowerShell> $Error[1].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ErrorRecord                              System.Object

#509 PS7 ~\Documents\PowerShell> $Error[2].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ErrorRecord                              System.Object
```

The error itself adds an _error record_ to `$error` , and to anything specified in `-errorVariable` 

The ErrorActionPreference means the error generates a _runtime exception_ which is logged separately to $error and will be the more recent event there.  

 **However** specifying ErrorAction as a switch for the function does not log a duplicate - see below   
 preference as continue, no commandline switch adds 1 error. 
 preference as continue, with commandline switch adds 1 error. 
 preference as stop, no commandline switch adds 2 errors. 
 preference as stop, with commandline switch adds 2 errors.  

```
#501 PS7 ~\Documents\PowerShell> function foo {[cmdletbinding()] param() 1/0 ; 1/2}
#502 PS7 ~\Documents\PowerShell> foo
RuntimeException: Attempted to divide by zero.
0.5
#503 PS7 ~\Documents\PowerShell> $error.count
1
#504 PS7 ~\Documents\PowerShell> foo -ErrorAction stop
foo: Attempted to divide by zero.
#505 PS7 ~\Documents\PowerShell> $error.count
2
#506 PS7 ~\Documents\PowerShell> $ErrorActionPreference="Stop"
#507 PS7 ~\Documents\PowerShell> foo
foo: Attempted to divide by zero.
#508 PS7 ~\Documents\PowerShell> $error.count
4
#509 PS7 ~\Documents\PowerShell> foo -ErrorAction Stop
foo: Attempted to divide by zero.
#510 PS7 ~\Documents\PowerShell> $error.count
6
```

**Either** the erroractionPreference SHOULD NOT ADD the second entry,  
**Or** the -ErrorAction switch  SHOULD ADD it. 

But it isn't consitant

**Comment by triynko** [comment]
This is a NASTY bug.  I'm invoking a script block `& $script $arguments`. The scrip looks like `{ param($branch) git checkout "$branch"}`.  I call this twice, with two different argument. I check $Error.Count before and after each call, and if an error occurs, I print it.  I'm 100% that $branch is 'A' in the first call, and 'B' in the second call. I'm also 100% sure that after each call, a new error is generated and added to $Error, because I'm checking the count before and after.  However, THE ERRORS ARE THE SAME.  The 2nd error is a duplicate of the first, and both errors reference only branch 'A'.   This is in spite of having Write-Host $branch wrapped in the script around the checkout call, and being absolutely certain that git checking 'A" is called the first time and git checkout 'B' runs the second time.  So this is absolutely some kind of nasty, error-duplicating bug. Leading me to this very thread. I'm using POWERSHELL 5.1, which comes standard with Windows 11, which I was just upgraded to on this lovely October 2024.

If I make a single change to the logic... simply calling $Error.Clear before each call, then it works as expected, and $Error[-1] contains text referring to the respective branch that git checkout was called on.
