### ISSUE TITLE
.NET Forms DPI Awarness Trick Involving WPF Breaks .NET Forms Legacy Scale Mode for all Forms Presented after Trick is Conducted One Time

### ISSUE THREAD

**Issue by brandoncomputer** [PowerShell/PowerShell#17129]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When run the first time, this form becomes DPI aware. The proper math will adjust the form to the users monitor scale.
Upon running the second time, the form is DPI aware at the start of the session, meaning $vscreen already returns the monitors height instead of the legacy scale height.

**_Any .Net form presented on the system afterwards will be DPI aware which is not the intent._** 

```
Add-Type -AssemblyName System.Windows.Forms, System.Drawing, presentationframework
$vscreen = [System.Windows.Forms.SystemInformation]::VirtualScreen.height

[xml]$xml = @"
            <Window
                    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
            </Window>
"@
$dum = (New-Object System.Xml.XmlNodeReader $xml)
$win = [Windows.Markup.XamlReader]::Load($dum)

$screen = [System.Windows.Forms.SystemInformation]::VirtualScreen.height

$global:ctscale = ($screen/$vscreen)
    
$Form = New-Object System.Windows.Forms.Form
	$Form.Text="Form"
	$Form.Width = 600 * $ctscale
	$Form.Height = 480 * $ctscale
    

	$Button1 = New-Object System.Windows.Forms.Button
		$Button1.Text="Button1"
		$Button1.Width=75 * $ctscale
		$Button1.Height=23 * $ctscale
		$Button1.Top=84 * $ctscale
		$Button1.Left=144 * $ctscale
        $Form.Controls.Add($Button1)
		#$Button1.add_Click({[System.Windows.Forms.MessageBox]::Show("Button1 click!","Example Event","OK",64) | Out-Null})
[System.Windows.Forms.Application]::Run($Form) | Out-Null
	#For consecutive forms use $Form.Show() or modal $Form.ShowDialog(). Only use Run once.
```

### Expected behavior

```console
.Net Form DPI awarness from the session should not stick after .Net Form is closed for other .Net Forms.
```

### Actual behavior

```console
.Net Form DPI awarness from the session sticks after .Net Form is closed for other .Net Forms.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Expected Appearance after above script is run for second script that is not using the WPF scaling trick
![image](https://user-images.githubusercontent.com/3017980/162585310-ec5b6291-3438-41a0-b792-5cfbfc4d242d.png)

### Actual Appearance after above script is run for second script that is not using the WPF scaling trick
![image](https://user-images.githubusercontent.com/3017980/162585324-160060d4-6091-44f1-bab6-c45ccd83f437.png)

**Comment by brandoncomputer** [comment]
Using the "Run with Powershell 7" context verb reliably produces the results above on scripts ran after the trick is conducted. Dot sourcing the script from the console works a few times until the issue is fully ingrained ~ it eventually does still break.

**Comment by vexx32** [comment]
While this is reproducible with PowerShell it's entirely using .NET APIs here, so I don't think there's anything PowerShell can reasonably do to make this more usable.

You're probably better off filing an issue in the [dotnet/wpf](https://github.com/dotnet/wpf) repository where the actual code for these APIs is maintained. They may be able to offer suggestions on better ways to do what you're after, or fix any relevant bugs. PowerShell simply consumes and exposes the API for use, we can't change what it's doing.

**Comment by brandoncomputer** [comment]
I do appreciate vexx32's comment here, and likely this will take some collaboration between the WPF, Forms, Runtime and Powershell teams to resolve, however I arrived at this difficulty from experiences with PowerShell specifically between 5.1 and 7.2.2.

Rather than get the run around on the stack carousel, I'll instead have the realization that ultimately either the PowerShell team cares about user experience, or they do not.  Ultimately users that run the code above will cause trauma to their _Powershell 7.2.2_ installation that will cause unexpected behaviors, so I think this is the best place for the issue to remain.

**Comment by brandoncomputer** [comment]
Further evidence is a cure exists, uninstall Powershell 7.2.2, reboot and reinstall Powershell 7.2.2, the UX experience is restored.
