### ISSUE TITLE
ConvertTo-Json Hangs and Consumes More and More Memory

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#17121]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

You can run this in any version of PowerShell from 5.1 to 7.2.2 and it will hang. I figure this bug exists somewhere but my GitHub googlin' wasn't yielding anything so feel free to close if this is a dupe. 

```
try { invoke } catch { $error[0] | ConvertTo-Json -Depth 100 }
```

It will also run away with memory until all memory on the system is gone. 

![image](https://user-images.githubusercontent.com/1256531/162280034-76b97ea6-d63e-42f3-bfc6-7f1de88bc7aa.png)

### Expected behavior

```console
ConvertTo-Json (even at max depth) either throws an error or doesn't continue to serialize this much data from a "simple" object.
```

### Actual behavior

```console
ConvertTo-Json consumes all memory on the system.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SeeminglyScience** [comment]
> ConvertTo-Json (even at max depth) either throws an error or doesn't continue to serialize this much data from a "simple" object.

I wouldn't really call it a simple object. At least without special handling to cherry pick the important properties.

Especially once you hit `Exception.TargetSite` you get a whole lot of branching recursive references. Short of hard coding handling for `Exception` I'm not sure what can be done here.

**Comment by adamdriscoll** [comment]
We kind of blindly fire stuff through `ConvertTo-Json` in PSU and I think that's part of my problem. We've worked around this by using async pipeline processing and terminating the pipe if it doesn't return after a few seconds of serialization. I'll just put some warnings on our docs and stuff (or may right in the UI) about it. 

It looks like NewtonSoft ignores TargetSite or has some special handling for exceptions. 

```
PS C:\Users\adamr> $var = try { invoke } catch { [NewtonSoft.Json.JsonConvert]::SerializeObject($error[0].Exception)  }
PS C:\Users\adamr> ConvertFrom-Json $var

ClassName              : System.Management.Automation.CommandNotFoundException
Message                : The term 'invoke' is not recognized as a name of a cmdlet, function, script file, or
                         executable program.
                         Check the spelling of the name, or if a path was included, verify that the path is correct
                         and try again.
Data                   : @{System.Management.Automation.Interpreter.InterpretedFrameInfo,
                         System.Management.Automation, Version=7.2.2.500, Culture=neutral,
                         PublicKeyToken=31bf3856ad364e35=System.Object[]}
InnerException         :
HelpURL                :
StackTraceString       :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                         funcContext, Exception exception)
                            at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                         frame)
                            at
                         System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                         frame)
                            at
                         System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                         frame)
RemoteStackTraceString :
RemoteStackIndex       : 0
ExceptionMethod        :
HResult                : -2146233087
Source                 : System.Management.Automation
WatsonBuckets          :
ErrorId                : RuntimeException
ErrorCategory          : 0
CommandName            : invoke
```

I guess I just didn't really grasp the impact of -Depth 100. It must never reach that depth while trying to serialize the world.

**Comment by adamdriscoll** [comment]
Found it: https://github.com/JamesNK/Newtonsoft.Json/blob/f7e7bd05d9280f17993500085202ff4ea150564a/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L302

**Comment by SeeminglyScience** [comment]
> I guess I just didn't really grasp the impact of -Depth 100. It must never reach that depth while trying to serialize the world.

Yeah `MethodInfo` has a ton of properties that cycle. Each layer of depth exponentially increases the total tree size. Depth 100 would take *some time* to hit 😁
