### ISSUE TITLE
```%ProgramW6432%\WindowsPowerShell\Modules``` not in ```$env:PSModulePath``` for PowerShell 7.2 nor 7.3

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShell#17120]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

With both [PowerShell](https://www.microsoft.com/en-us/store/apps/9mz1snwt0n5d) and [PowerShell Preview](https://www.microsoft.com/en-us/store/apps/9p95zzktnrn4) from Microsoft Store, and [latest stable MSI 64 bit](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.2), running on a 64 bit operating system, following:

* ```$env:PSModulePath.Split(';') | Sort-Object```

Is missing a what I consider crucial path for modules: The default install location for Windows PowerShell 5.1 when specifying ```-Scope AllUsers``` when running Windows PowerShell 5.1 as 64 bit on a 64 bit OS.

* But the 32 bit path is there!

**Is this intentional?**
If yes:

* Why?
* Why is the x86 Windows PowerShell modules location for system context there?

### Expected behavior

* I'll indicate what I consider a missing path with ```<--```.
* I've removed ```%OneDriveCommercial%``` paths from these outputs, as it's not really relevant, and few are likely using OneDrive for Business Known Folder Move (KFM) anyways.

#### Microsoft Store PowerShell

```
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\windowsapps\microsoft.powershell_7.2.2.0_x64__8wekyb3d8bbwe\Modules
C:\Program Files\WindowsPowerShell\Modules <--
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

#### Microsoft Store PowerShell Preview

```
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\windowsapps\microsoft.powershellpreview_7.3.3.0_x64__8wekyb3d8bbwe\Modules
C:\Program Files\WindowsPowerShell\Modules <--
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

#### PowerShell 7.2.2 MSI

```
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
C:\Program Files (x86)\WindowsPowerShell\Modules
c:\program files\powershell\7\Modules
C:\Program Files\PowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules <--
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

### Actual behavior

* I've removed ```%OneDriveCommercial%``` paths from these outputs, as it's not really relevant, and few are likely using OneDrive for Business Known Folder Move (KFM) anyways.

#### Microsoft Store PowerShell

```
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\windowsapps\microsoft.powershell_7.2.2.0_x64__8wekyb3d8bbwe\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

#### Microsoft Store PowerShell Preview

```
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
C:\Program Files (x86)\WindowsPowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\windowsapps\microsoft.powershellpreview_7.3.3.0_x64__8wekyb3d8bbwe\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

#### PowerShell 7.2.2 MSI

```
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
C:\Program Files (x86)\WindowsPowerShell\Modules
c:\program files\powershell\7\Modules
C:\Program Files\PowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

#### Microsoft Store PowerShell

```
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#### Microsoft Store PowerShell Preview

```
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#### PowerShell 7.2.2 MSI

```
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Hmm I can't repro this:

```powershell
> $env:PSModulePath -split ';'
C:\Users\pmeinecke\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\7\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\windows\system32\WindowsPowerShell\v1.0\Modules
```

Can you check

```powershell
[Environment]::GetEnvironmentVariable('PSModulePath', 'User')
[Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')
```

To see if it's set somewhere? Also check `[IntPtr]::Size`

**Comment by o-l-a-v** [comment]
Hmm, strange.

I have some other strange problems on this laptop alone, for instance ```-AcceptLicense``` parameter does not work with ```PackageManagement\Install-Package``` v1.4.7.

Output of ```[Environment]::GetEnvironmentVariable('PSModulePath', 'User')``` is nothing.

Machine:

```powershell
PS C:\Users\<user>> [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine').Split(';') | Sort-Object
%ProgramFiles(x86)%\WindowsPowerShell\Modules
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
PS C:\Users\<user>>
```

```[IntPtr]::Size``` is 8.

**Comment by SeeminglyScience** [comment]
> ```powershell
> %ProgramFiles(x86)%\WindowsPowerShell\Modules
> %SystemRoot%\system32\WindowsPowerShell\v1.0\Modules
> C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
> C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin
> ```

It seems like when one of the last two entries were written to the environment variable it was locked to the wrong bitness.

This is unfortunately a pretty common problem with .NET based installers do to how this particular API works. If folks alter an expand sz environment variable via this API, it loses `EXPAND` and hard codes the directories in the new variable value.

Happens with `%PATH%` *a lot* but most of the time it's done by a 64 bit installer so it doesn't become an issue for most. You can change it in the registry or with `[Environment]::SetEnvironmentVariable('PSModulePath', $newValue, 'Machine')` as admin.
