### ISSUE TITLE
Test-Path inconsistency when both file and folder match a pattern

### ISSUE THREAD

**Issue by k9wazere** [PowerShell/PowerShell#17134]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using wildcards in a Test-Path expression, if a pattern could match a file, then -PathType Leaf will return True but -PathType Container will return False, even if a folder would also match the pattern.

See expected/actual behaviour.

### Expected behavior

```console
mkdir blah1
New-Item -ItemType File blah2

Test-Path -PathType Container -Path blah*
True*
Test-Path -PathType Leaf -Path blah*
True*

*You could make the case for both being true or both being false, but they should both be the same result.
```

### Actual behavior

```console
mkdir blah1
New-Item -ItemType File blah2

Test-Path -PathType Container -Path blah*
False
Test-Path -PathType Leaf -Path blah*
True
```

### Environment data

```powershell
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by hamid-nazari** [comment]
This is still an annoying issue as of `7.4.2`.
Any plan on fixing it? 
Providing some description would be nice; Why, What, and possibly **When**?
