### ISSUE TITLE
Unwanted Verbose output from SCCM cmdlets

### ISSUE THREAD

**Issue by k9wazere** [PowerShell/PowerShell#17138]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

SCCM cmdlets honour the $VerbosePreference value of the calling scope.
If $VerbosePreference is set to "Continue", passing -Verbose:$false does not disable verbose output.

Workarounds are to put all SCCM cmdlets in their own script blocks, and override $VerbosePreference in each script block.
This introduces its own issues with variable scope.
An alternative is to save and restore the $VerbosePreference, before and after calling each cmdlet,
but this adds extra lines of unwanted code.

The docs for PS indicates that passing -Verbose:$false should disable verbose output, but clearly the SCCM cmdlets are not working in this way. As SCCM is another MS product I figured you wouldn't mind me opening a bug for this here ;)

### Expected behavior

```console
$VerbosePreference = "Continue" # module or script scope
$someCmApp | Move-CMObject -FolderPath \blah\de\blah -Verbose:$false
# no verbose output desired from SCCM cmdlet
```

### Actual behavior

```console
# pages of verbose output
# however...

$VerbosePreference = "Continue" # module or script scope
...
# other work where verbose output is desired
...
& {
  $VerbosePreference = "SilentlyContinue"
  Move-CMObject ...
  # no Verbose output with the nested script block
}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by k9wazere** [comment]
Also somewhat related: cmdlets like Copy-Item, Move-Item (etc) don't respond at all to $VerbosePreference.

The only way to get Copy-Item or Move-Item to show their verbose output is to use the -Verbose(:$true) switch every time you invoke that cmdlet. I'm not sure why?

**Comment by SeeminglyScience** [comment]
The ConfigurationManager module is not tracked in this repo. Suggestions and bug reports for it need to go through Feedback Hub. Marking as `Resolution-External`
