### ISSUE TITLE
PowerShell Get-WinEvent -FilterHashTable generates error on Windows 11 in user context

### ISSUE THREAD

**Issue by chippey5** [PowerShell/PowerShell#17145]
### Steps to reproduce

Previously I've been able to read event logs in user context using `Get-Winevent -FilterHashTable`. For some reason, I don't have permissions to filter the logs with `-FilterHashTable`. This can be tested with the following:

```
#Create Provider: "Test"
New-EventLog -LogName Application -Source "Test" -ErrorAction Ignore

#Create an event under the provider we just created
Write-EventLog -LogName "Application" -Source "Test" -EventID 100 -EntryType Information -Message "This is a test message"

#Filter out the event we just created
Get-WinEvent -ErrorAction Ignore -FilterHashtable @{
    ProviderName = "Test";
    LogName      = "Application";
}
```

When I run the last command as an Administrator however, it works. I can also find the event without `-FilterHashTable` (in user context) :

```
$logs = Get-WinEvent -LogName "Application" -MaxEvents 1000 -ErrorAction Ignore
$logs | Where-Object {$_.ProviderName -eq "Test"}

   ProviderName: Test

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
2022-04-13 09:21:48            100 Information      This is a test message

```

Tested on both PowerShell 5.1 (which comes shipped with W11) and PowerShell 7.2.2.

### Expected behavior

```console
PS> Get-WinEvent -FilterHashtable @{
    ProviderName = "Test";
    LogName      = "Application";
}
ProviderName: Test

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
2022-04-13 09:21:48            100 Information      This is a test message
```

### Actual behavior

```console
PS> Get-WinEvent -FilterHashtable @{
    ProviderName = "Test";
    LogName      = "Application";
}
Get-WinEvent: There is not an event provider on the localhost computer that matches "Test".
Get-WinEvent: The specified providers do not write events to any of the specified logs.
Get-WinEvent: The parameter is incorrect.
```

### Error details

```console
PS> Get-Error
Exception             :
    Type       : System.Diagnostics.Eventing.Reader.EventLogException
    Message    : The parameter is incorrect.
    TargetSite :
        Name          : Throw
        DeclaringType : System.Diagnostics.Eventing.Reader.EventLogException
        MemberType    : Method
        Module        : System.Diagnostics.EventLog.dll
    Source     : System.Diagnostics.EventLog
    HResult    : -2146233088
    StackTrace :
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
   at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtQuery(EventLogHandle session, String path, String query, Int3
2 flags)
   at System.Diagnostics.Eventing.Reader.EventLogReader..ctor(EventLogQuery eventQuery, EventBookmark bookmark)
   at System.Diagnostics.Eventing.Reader.EventLogReader..ctor(EventLogQuery eventQuery)
   at Microsoft.PowerShell.Commands.GetWinEventCommand.ReadEvents(EventLogQuery logQuery)
   at Microsoft.PowerShell.Commands.GetWinEventCommand.ProcessHashQuery()
   at Microsoft.PowerShell.Commands.GetWinEventCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Get-WinEvent], EventLogException
FullyQualifiedErrorId : System.Diagnostics.Eventing.Reader.EventLogException,Microsoft.PowerShell.Commands.Get
WinEventCommand
InvocationInfo        :
    MyCommand        : Get-WinEvent
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 13
    Line             : Get-WinEvent -FilterHashtable @{

    PositionMessage  : At line:1 char:1
                       + Get-WinEvent -FilterHashtable @{
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-WinEvent
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
1.
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

2.
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jdhitsolutions** [comment]
I just ran through the steps in 7.2.6 and 7.3-Preview8 with no issues.

![image](https://user-images.githubusercontent.com/12089920/197059025-bf725569-b5de-414d-9eab-eefce90c393c.png)

![image](https://user-images.githubusercontent.com/12089920/197059206-6ea465da-9112-40e0-97ab-c63694efced2.png)

I was running in an elevated session in those examples. In a Non-elevated session, I get the error.

![image](https://user-images.githubusercontent.com/12089920/197059627-ef15756b-4ad4-4438-a433-f1146eae646d.png)

Using an xPath filter DOES work in all situations.

![image](https://user-images.githubusercontent.com/12089920/197061044-e05e6e1b-0d93-41ab-beb2-2fd92246451d.png)

So this would seem to point to a bug with `Filterhashtable`.

**Comment by iSazonov** [comment]
> When I run the last command as an Administrator however, it works.

MSFT improved security on Windows 11 😄

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me:

![image](https://user-images.githubusercontent.com/11859881/198903443-c740c4f2-f398-4da3-9e7b-d5d7771324a6.png)

**Comment by SteveL-MSFT** [comment]
Try running with `-verbose` which will emit the created query

**Comment by SteveL-MSFT** [comment]
@chippey5 when it fails, can you try: wevtutil gp Test

**Comment by chippey5** [comment]
Hi, 

Since last time I have updated to W11 22H2, but the bug seems to remain:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3088413/203553154-db494bcc-8ec1-41b9-993d-c75f998ff3c9.png">

Same with PS 7.3:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/3088413/203559090-84d3309d-acc6-4628-8932-279d07b63ed1.png">

> Try running with `-verbose` which will emit the created query. Also, are you running anything that isn't en-US?

I believe I did last time, but right now I'm not:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3088413/203554646-9922a304-f123-4f68-8bd3-0e32e5c7f1cc.png">


> @chippey5 when it fails, can you try: wevtutil gp Test

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3088413/203553505-774062fa-d0b5-44c0-bf9b-5895b932e086.png">

Thanks for checking!

**Comment by SteveL-MSFT** [comment]
@chippey5 thanks for the screenshots.  Since `wevtutil` succeeds, then that indicates it's a problem in the cmdlet vs the ETW APIs.  The problem is getting a consistent repro I can debug.

**Comment by SteveL-MSFT** [comment]
Need a repro to further investigation

**Comment by chippey5** [comment]
Bump as this is likely not solved yet
