### ISSUE TITLE
Get-Counter corrupts/disables PerfLib or returns invalid data

### ISSUE THREAD

**Issue by ExSport** [PowerShell/PowerShell#17147]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When querying more counters at once and one of them is [User Input Delay Per Session] counterset, it fails with breaking the perfmon functionality (corrupted/disabled PerfLib, etc...).
It happens in some specific combinations like [User Input Delay Per Session] and [Memory] or [System] countersets. In such combinations invoking Get-Counter will terminate powershell process or returns non-zero Status property for the CounterSamples.
[User Input Delay Per Session] counterset works with .e.g. [SMB Server] counterset so not all are affected.
When two different get-counter cmdlets are invoked ([User Input Delay Per Session] separately), all counters are returned without issues.
Tested on Windows 2019, Powershell 5.1 and 7.2.2, same behavior.

### Expected behavior
When querying array of counters in one "dataset" and [User Input Delay per Session] is used, valid data should be returned without needing to read [User Input Delay per Session] separately.
So this should work:
```console
(Get-Counter -Counter @('\smb server\receive bytes/sec','\memory\page faults/sec','\user input delay per session(max)\max input delay') -SampleInterval 1 -MaxSamples 1).CounterSamples|Select InstanceName,Path,CookedValue,Status
```

### Actual behavior
When querying array of counters in one dataset and [User Input Delay per Session] is used, it starts to return invalid data or terminates powershell completely.
Issuing command:
```console
(Get-Counter -Counter @('\smb server\receive bytes/sec','\memory\page faults/sec','\user input delay per session(max)\max input delay') -SampleInterval 1 -MaxSamples 1).CounterSamples|Select InstanceName,Path,CookedValue,Status
```
Returns error and non-zero STATUS for MEMORY Counters:
```console
Get-Counter: The data in one of the performance counter samples is not valid. View the Status property for each PerformanceCounterSample object to make sure it contains valid data.
InstanceName Path                                                         CookedValue     Status
------------ ----                                                         -----------     ------
             \\ov2p2194\smb server\receive bytes/sec                                0          0
             \\ov2p2194\memory\page faults/sec                                      0 3221228472
max          \\ov2p2194\user input delay per session(max)\max input delay           0          0
```

### Error details

```console
Exception             :
    Type    : System.Exception
    Message : The data in one of the performance counter samples is not valid. View the Status property for each
PerformanceCounterSample object to make sure it contains valid data.
    HResult : -2146233088
CategoryInfo          : InvalidResult: (:) [Get-Counter], Exception
FullyQualifiedErrorId : CounterApiError,Microsoft.PowerShell.Commands.GetCounterCommand
InvocationInfo        :
    MyCommand        : Get-Counter
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 36
    Line             : (Get-Counter -Counter @('\smb server\receive bytes/sec','\memory\page faults/sec','\user input
delay per session(max)\max input delay') -SampleInterval 1 -MaxSamples 1).CounterSamples|Select
InstanceName,Path,CookedValue,Status
    PositionMessage  : At line:1 char:2
                       + (Get-Counter -Counter @('\smb server\receive bytes/sec','\memory\page …
                       +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-Counter
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Screenshot 2022-04-13 164222](https://user-images.githubusercontent.com/1260408/163207704-c9c256ba-1400-4339-a955-c160c149704d.png)

When [user input delay per session] removed, returned values are OK:
![Screenshot 2022-04-13 165212](https://user-images.githubusercontent.com/1260408/163208604-9d983bae-a758-49f5-b5b9-1db91b58a5c4.png)

**Comment by ExSport** [comment]
Seems no interest to this issue from MS side? Thanks for some update.

**Comment by ExSport** [comment]
Another source of the same issue when called via C#:
https://stackoverflow.com/questions/66333570/performancecounter-user-input-delay-per-session-disappears

**Comment by SteveL-MSFT** [comment]
I'm not able to repro this with 7.3, there was a [change to how the cmdlet interops with the perf API](https://github.com/PowerShell/PowerShell/pull/17779), can you see if this repros for you with 7.3?

**Comment by ExSport** [comment]
@SteveL-MSFT Hello Steve
Unfortunately not fixed (OS Win 2019, Posh 7.3.0-preview8):
![image](https://user-images.githubusercontent.com/1260408/194847671-545e4bf2-2bbb-41f9-a178-b2f6701e5ced.png)

**Comment by iSazonov** [comment]
@ExSport Please share `Get-Error` output.

**Comment by ExSport** [comment]
Get-Error output:
```
Exception             :
    Type    : System.Exception
    Message : The data in one of the performance counter samples is not valid. View the Status property for each
PerformanceCounterSample object to make sure it contains valid data.
    HResult : -2146233088
CategoryInfo          : InvalidResult: (:) [Get-Counter], Exception
FullyQualifiedErrorId : CounterApiError,Microsoft.PowerShell.Commands.GetCounterCommand
InvocationInfo        :
    MyCommand        : Get-Counter
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 4
    Line             : (Get-Counter -Counter @('\smb server\receive bytes/sec','\memory\page faults/sec','\user input
delay per session(max)\max input delay') -SampleInterval 1 -MaxSamples 1).CounterSamples|Select
InstanceName,Path,CookedValue,Status
    PositionMessage  : At line:1 char:2
                       + (Get-Counter -Counter @('\smb server\receive bytes/sec','\memory\page …
                       +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-Counter
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

**Comment by SteveL-MSFT** [comment]
I spent some time debugging this.  The actual error being returned as part of the PDH sample is PDH_CSTATUS_NO_OBJECT.  I can easily repro this with:

```powershell
(Get-Counter -Counter @('\memory\page faults/sec', '\user input delay per session(max)\max input delay') -SampleInterval 1 -MaxSamples 1).CounterSamples
```

Same with PS7 and 5.1.  So this is not a regression.  The interesting thing is if I use perfmon with the same two counters, I see the same problem.  No data is returned for `page faults/sec`.  However, if I ONLY have that counter (either the cmdlet or in perfmon), it shows data.  But in perfmon if I add back the second counter, it then doesn't show any data for the first one.  Based on the results of perfmon (and the cmdlet is consistent here), it seems that the problem is with the counter being used with another counter.

**Comment by ExSport** [comment]
@SteveL-MSFT You can combine more counters without issues but when multiple ones are used, you can't use "new" [user input delay] one which will affect other ones in most cases (as described in the first post):
https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters
Without this one, you are able to read more counters at once or your are able to read this one alone or with e.g. SMB counters but not with other ones like memory ones, etc.
It is possible to read them "together" in separate threads via RunSpace/PSJobs so you can read them almost at once, without any crashes but they can't be queried in one request.
It is not a flaw in PowerShell cmdlet only (all versions) but in perfmon API or the way how PowerShell/.net/C#/... queries these counters.
