### ISSUE TITLE
PowerShell doesn't call `SetCurrentDirectory()` when location changes nor sets `$env:PWD`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#17149]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This was reported by a Windows partner.

`GetCurrentDirectory()` is a Win32 API that returns the current working directory.  This is used by native commands to resolve things like relative paths.  It will currently always return the directory where pwsh was started.

```powershell
cd $env:WINDIR
[System.IO.Directory]::GetCurrentDirectory()
```

PS7 should call `SetCurrentDirectory()` when the main console thread changes location and also set `$env:PWD`.  There are no guarantees for multi-threads as the current working directory is process scope.

### Expected behavior

```console
c:\Windows
```

### Actual behavior

```console
Your home dir
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
> This is used by native commands to resolve things like relative paths. It will currently always return the directory where pwsh was started.

It's worth noting that for native command invocations we do already send the new working directory over:

https://github.com/PowerShell/PowerShell/blob/be998816f7c5346b1120c6b2eba0b90729f21086/src/System.Management.Automation/engine/NativeCommandProcessor.cs#L1380-L1385

Relevant discussion in #3428 (and a few linked threads there).

**Comment by Jaykul** [comment]
That would be a pretty big change. I mean, this has been like this (despite our pleas) since day 1 ...

Having said that, I've been adding SetCurrentDirectory into my prompt for over a decade, so I can't really think of any reason *not* to fix this, except the classic: It's bound to break **something** 😋😋

**Comment by SeeminglyScience** [comment]
If you change it to call `SetCurrentDirectory`, but only in one thread, that could be confusing for scripts that use dotnet APIs.

e.g.

```powershell
# script.ps1
cd temp:\
[IO.Directory]::GetFiles('./')
```

That script would then behave differently if invoked with `Start-ThreadJob`.

There may not be a lot of folks doing anything like that currently, but if we build the expectation that `cd` changes dotnet's view of the current directory, we likely will. I could see it being fine to set every REPL loop (like when `prompt` is called) but if the intention is to change it mid script execution I think that's problematic.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this.  We agreed that we should take this as an Experimental Feature.  The setting of the current directory via the API and $env:PWD should be done in the FileSystemProvider and only on the main console thread (somehow the context needs to be passed through).  No assurances for multiple threads as this information is process wide and also only for file system paths and not psprovider paths.  Cmdlets/scripts that can use pspaths should use the existing PS API.

**Comment by daxian-dbw** [comment]
> GetCurrentDirectory() is a Win32 API that returns the current working directory. This is used by native commands to resolve things like relative paths.

Given that the filesystem current working directory is passed in when starting a native command, why do we need `SetCurrentDirectory()` then? Is it for allowing a user to use .NET API directly with relative paths? If so, I think it will be confusing for someone to find something works in console, but not in a thread job or `ForEach-Object -Parallel`.

**Comment by iSazonov** [comment]
The current situation is already perplexing for people who don't know how runspace works. We have always told them that PowerShell keeps track of the current directory per runspace. This proposed change will confuse users even more. Furthermore, it will lead to race conditions.

It should also be noted that this completely destroys the basic principles of PowerShell. The current location is an inherent attribute of PowerShell providers. In other words, _by accepting this change, we must extend it to all providers._

**Comment by Hrxn** [comment]
There's also `[System.Environment]::CurrentDirectory` 😄 

(Can be both `{get; set;}` )

Which does reflect the currently active directory of the process itself (i.e. pwsh.exe) when changed with the `SetCurrentDirectory()` static method.

I always thought that this was by design, because PowerShell has this notion of runspaces, and what you see as the `gl | pwd | $PWD` is the currently active directory in only the currently active runspace.

That said, I have some sympathy for this change...

Because there's this one time (I guess we all could tell similar stories here) where a script I wrote tripped over the path given as a parameter value to a static method of a .NET type I was using, like [IO.File]::ReadLines , or [Net.WebClient]::DownloadFile ...

😄 

Always had to remember to use full path names in such cases.

**Comment by DHowett** [comment]
> Given that the filesystem current working directory is passed in when starting a native command, why do we need `SetCurrentDirectory()` then?

There are some other issues, of particular note for terminal authors and other more advanced users.

1. A terminal emulator that wants to track the working directory of the processes it's spawned -- for example, to enable session restoration -- will look at the process's working directory. If it is always the same, it becomes unreliable.
2. The current directory is held locked by the process "using" it; in PowerShell's case, this means that a shell that is spawned in one folder and "moved" to another will keep the _original_ directory handle open and make it impossible to delete or move.

**Comment by ForNeVeR** [comment]
Sorry for resurrecting this old thread, folks, but I am confused on its current state. So, a message here indicates the PowerShell committee agreed to introduce an experimental feature that will sync the cwd.

Has anything happened since then? Do you folks need help with the implementation? Or would a more detailed proposal now be accepted/require review?

**Comment by SeeminglyScience** [comment]
I would consider the committee decision to be no longer active. If you have a proposal that addresses the concerns in this topic (and ideally speaks a bit more to the benefits of the change) I'd definitely suggest opening up a new issue so the WG can discuss it

**Comment by ForNeVeR** [comment]
@DHowett, has Windows Terminal solver the problem in some other way since then?

**Comment by DHowett** [comment]
Not meaningfully, no. Terminal has to rely on a user's configured
Prompt to send OSC 9;9 informing it about the CWD. :(
