### ISSUE TITLE
cd\ vs cd~

### ISSUE THREAD

**Issue by gh658804** [PowerShell/PowerShell#17140]
### Summary of the new feature / enhancement

cd\ (without a space in between) seems to work fine. cd.. too. cd~ does not though, it returns a 'not recognized'  error. It would be nice if it did.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  Since there is already precedent for other functions that provide this capability for cd, we are ok adding one more.

**Comment by GigaScratch** [comment]
I have an open PR for this, can I please be assigned? @SteveL-MSFT

**Comment by k0T0z** [comment]
is this still need a PR?
