### ISSUE TITLE
Non-Recursive Listing of Files Where the Directory is Specified as a LiteralPath and the Filename Contains Wildcards 

### ISSUE THREAD

**Issue by thecliguy** [PowerShell/PowerShell#17162]
### Summary of the new feature / enhancement

Using `Get-ChildItem`, can anyone advise whether it's possible to non-recursively list files where the directory is specified as a LiteralPath and the filename(s) returned must match a given string containing wildcards?

This is the closest I've managed to get:

```powershell
Get-ChildItem -LiteralPath "C:\Bitbucket\Test\foo[1-5]bar" -Filter "*.doc" -File
```

The `-Filter` parameter uses the FileSystem provider rather than PowerShell wildcards _(`Get-Help about_Wildcard`)_. PowerShell wildcards are well understood and it's unlikely that the syntax will ever change dramatically (or at least not in a breaking change way). Whereas, when relying on the FileSystem provider for filtering, although there are many similarities to PowerShell wildcards, PowerShell has no influence over its behaviour, you are completely at the mercy of .Net Core and this makes me feel it's a potentially risky proposition to use.

_(The behaviour of `-Filter` has changed dramatically between Windows PowerShell and Powershell Core. To illustrate this, in Windows PowerShell if `C:\Bitbucket\Test\foo[1-5]bar` contained both `.doc` and `.docx` files then `Get-ChildItem -LiteralPath "C:\Bitbucket\Test\foo[1-5]bar" -Filter "*.doc" -File` would return files with both extensions, whereas this is not the case in PowerShell Core)_ 

Here are a couple of workarounds I've come up with... I'm not entirely sure if I'd trust the second option just in case there are any quirks or edge cases that I've failed to consider.

```powershell
################################################################################
# WORKAROUND 1
# Delegate responsibility for filtering to the Where method.
(Get-ChildItem -LiteralPath "C:\Bitbucket\Test\foo[1-5]bar" -File).Where({$_.name -like "*.doc"})
################################################################################
# WORKAROUND 2
# Use Get-ChildItem with a non-literal path to take advantage of PowerShell's
# wildcard filtering but before doing so, check that the directory path 
# "literally" exists, the filename is a value that can only be interpreted as a 
# file (not a directory) by ensuring that it does NOT contain any path 
# separators ("\" or "/") and then escape the directory path.
$DirectoryPath = "C:\Bitbucket\Test\foo[1-5]bar"
$Filename = "*.doc"

If (Test-Path -LiteralPath $DirectoryPath -Type Container) {
    If (!($Filename.ToCharArray().Where({ ('\', '/').contains([string]$_.ToString()) }))) {
        $DirectoryPathEscaped = [Management.Automation.WildcardPattern]::Escape($DirectoryPath)
        Get-ChildItem -Path "$DirectoryPathEscaped\$Filename" -File
    }
}
################################################################################
```

### Proposed technical implementation details (optional)

I'd be delighted if someone could tell me of a way to achieve the result I want using nothing but `Get-ChildItem`, however if that's simply not possible at present then I'd like to ask the PowerShell team and the community to consider whether it would be feasible and desirable to add new functionality that (somehow) enables a user to modify the behaviour of `-Filter` so that it can 
operate using PowerShell wildcard filtering?

Can anyone comment on whether the implementation of such a feature would theoretically offer performance benefits over using the `Where` method _(as shown in 'workaround 1')_ to perform filtering?

**Comment by thecliguy** [comment]
@jhoneill Thanks for taking the time to respond. I probably should have devised a better example but in my use case the path to the directory is specified by the consumer and I want it to be interpreted as literal. I don't want PowerShell to attempt any wildcard expansion in the path to the directory, it should "literally" exist, else the command should fail.

> I tried to repro what you said, I have one DOC and many DOCX file in the root of my documents folder and `Get-Childitem -LiteralPath C:\users\me\Documents\ -Filter *.doc -File` only returns the doc file but that was on PowerShell 7. When I fired up Windows PowerShell 5.1 - I get the same as you, i.e. the filter reproduces cmd behaviour in 5 but not in 7 - probably because being cross platform there was no sense bring those things to linux, which was an excuse to call time on some of them for windows.

You are quite right, this particular behaviour does only appear to be exhibited in PowerShell 5 but not in 7. That's a silly mistake on my part, I thought I had tested both versions but obviously not...

It's interesting and perhaps a little scary to see that the behaviour of `-Filter` has changed quite a bit between PowerShell 5 and 7... I'd be curious to know whether that's due to design changes within PowerShell _(unlikely because nothing mentioned in the docs)_ or whether the behaviour is entirely influenced by changes made in .Net Core...

I suppose my original question still stands, would the PowerShell team and the community to consider it feasible and desirable to add new functionality that (somehow) enables a user to modify the behaviour of `-Filter` so that it can operate using PowerShell wildcard filtering?

**Comment by daxian-dbw** [comment]
> It's interesting and perhaps a little scary to see that the behaviour of -Filter has changed quite a bit between PowerShell 5 and 7... I'd be curious to know whether that's due to design changes within PowerShell (unlikely because nothing mentioned in the docs) or whether the behaviour is entirely influenced by changes made in .Net Core...

The `-Filter` directly pass the search pattern to .NET APIs like `Directory.GetFiles(string path, string searchPattern)`, and it seems the behavior of that API has changed in .NET Core:
```
PS> dir C:\arena\tmp\repro\repro\

    Directory: C:\arena\tmp\repro\repro

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/21/2022  2:59 PM              0 a.doc
-a---           4/21/2022  3:00 PM              0 b.docx
```
From PowerShell 7.2 (.NET 6):
```
PS> [System.IO.Directory]::GetFiles("C:\arena\tmp\repro\repro", "*.doc")
C:\arena\tmp\repro\repro\a.doc
PS>
```
From Windows PowerShell 5.1:
```
PS> [System.IO.Directory]::GetFiles("C:\arena\tmp\repro\repro", "*.doc")
C:\arena\tmp\repro\repro\a.doc
C:\arena\tmp\repro\repro\b.docx
PS>
```

> I suppose my original question still stands, would the PowerShell team and the community to consider it feasible and desirable to add new functionality that (somehow) enables a user to modify the behaviour of -Filter so that it can operate using PowerShell wildcard filtering?

The purpose of having `-Filter` is for performance. Certain providers may have the filtering capability supported in its underlying component, and thus have better performance than the PowerShell wildcard globing. For the built-in providers, currently only the FileSystemProvider supports `-Filter` because .NET API can do this to some extent. Below is copied from the help content of `-Filter` parameter:
> The filter string is passed to the .NET API to enumerate files. The API only supports * and ? wildcards.

Here is an example for you to get a sense of the perf difference:

```
## Using PowerShell globing
PS:49> Measure-Command { dir C:\windows\System32\* }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 798
Ticks             : 7984646
TotalDays         : 9.24148842592593E-06
TotalHours        : 0.000221795722222222
TotalMinutes      : 0.0133077433333333
TotalSeconds      : 0.7984646
TotalMilliseconds : 798.4646

## Using -Filter
PS:50> Measure-Command { dir C:\windows\System32\ -Filter * }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 61
Ticks             : 619072
TotalDays         : 7.16518518518519E-07
TotalHours        : 1.71964444444444E-05
TotalMinutes      : 0.00103178666666667
TotalSeconds      : 0.0619072
TotalMilliseconds : 61.9072
```

Given that, making it do PowerShell wildcard globing will defeat its original purpose.

**Comment by thecliguy** [comment]
@daxian-dbw Thank you for your response. 

Just to clarify, I'm not suggesting any changes be made to the default behaviour of `-Filter`. I was asking whether it would be possible to introduce some means whereby the user can enable `-Filter` to operate using PowerShell wildcards.

In order to non-recursively list files where the specified directory path should be treated as literal but the filename value should allow for wildcard expansion, do you think `Get-ChildItem` should make some provision for this? Or do you think it is better to just use one of the following workarounds? 

> ```powershell
> ################################################################################
> # WORKAROUND 1
> # Delegate responsibility for filtering to the Where method.
> (Get-ChildItem -LiteralPath "C:\Bitbucket\Test\foo[1-5]bar" -File).Where({$_.name -like "*.doc"})
> ################################################################################
> # WORKAROUND 2
> # Use Get-ChildItem with a non-literal path to take advantage of PowerShell's
> # wildcard filtering but before doing so, check that the directory path 
> # "literally" exists, the filename is a value that can only be interpreted as a 
> # file (not a directory) by ensuring that it does NOT contain any path 
> # separators ("\" or "/") and then escape the directory path.
> $DirectoryPath = "C:\Bitbucket\Test\foo[1-5]bar"
> $Filename = "*.doc"
> 
> If (Test-Path -LiteralPath $DirectoryPath -Type Container) {
>     If (!($Filename.ToCharArray().Where({ ('\', '/').contains([string]$_.ToString()) }))) {
>         $DirectoryPathEscaped = [Management.Automation.WildcardPattern]::Escape($DirectoryPath)
>         Get-ChildItem -Path "$DirectoryPathEscaped\$Filename" -File
>     }
> }
> ################################################################################
> ```

**Comment by daxian-dbw** [comment]
> In order to non-recursively list files where the specified directory path should be treated as literal but the filename value should allow for wildcard expansion, do you think Get-ChildItem should make some provision for this? Or do you think it is better to just use one of the following workarounds?

I agree it would be nice for `Get-ChildItem` to allow doing that with the PowerShell wildcards by itself, but it would likely be a non-trivial work with relatively high risk of regression given the complexity of the FileSystem provider. So, given that simple workarounds like `.Where(..)` and `... | Where-Object` exist, I don't think the value would justify the cost.

**Comment by iSazonov** [comment]
> I was asking whether it would be possible to introduce some means whereby the user can enable `-Filter` to operate using PowerShell wildcards.

By design, `-Filter` is transparently delegated to Provider and, in the case we discuss, FileSystem Provider delegates this to .Net.

And by design, we already have wildcard (Regex) processing in PowerShell Provider Engine itself with `-Include` and `-Exclude`. But really they don't work in the scenario and we already have some registered issues for such scenarios.

**Comment by Hrxn** [comment]
What am I missing here?

This example you give here:

`Get-ChildItem -LiteralPath "C:\Bitbucket\Test\foo[1-5]bar" -Filter "*.doc" -File`

is working as intended...

To recapitulate, what you are trying to do, is matching both `.doc` and `.docx` files in that specific directory you picked with -LP?

As already pointed out `-Filter` uses the underlying .NET searchstring pattern for matching, and that has been changed some time ago from old legacy Windows matching, to the new, sane matching with correct globbing patterns.

This seems to work for me:
`[System.IO.Directory]::GetFiles('D:\Temp\Test' ,'*.doc?')`

Therefore `-Filter '*.doc?'` would work as well.
