### ISSUE TITLE
Passing the value of a type-constrained assignment through via the grouping operator (`(...)`) passes the input value rather than the converted one

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17165]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: This may not arise often in practice, but there are two concerns:

* The original behavior is surprising.
* _Repeating_ the command - for an already type-constrained variable - _changes_ the behavior.

```powershell
Remove-Variable -ErrorAction Ignore var # Make sure no $var variable exists.

([bool] $var = 42).GetType().Name # !! 'Int32', i.e. the type of the input rather than the stored converted value.

# Repeating the command - even with a different constraining type - then *does* return the converted value.
# NB: The symptom only surfaces with the same variable, i.e. with a *previously type-constrained* one.
([string] $var = 42).GetType().Name # !! 'String'
```

### Expected behavior

```console
Boolean
String
```

### Actual behavior

```console
Int32
String
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.3
```

**Comment by SeeminglyScience** [comment]
And only when the compiler is running unoptimized (dot sourcing, debug scenarios, etc).

So

```powershell
& { ([string] $a = 42).GetType() }
# string

& { . { ([string] $a = 42).GetType() } }
# int
```
