### ISSUE TITLE
Add an option to disable globbing on Linux

### ISSUE THREAD

**Issue by Shayan-To** [PowerShell/PowerShell#17176]
### Summary of the new feature / enhancement

PowerShell now expands the globs when using native commands on Linux. This is very inconvenient to me for a few reasons:

- I use PowerShell on both Linux and Windows, and I have to always be cautious so that I don't make mistakes. (I can use `git checkout master -- *` on Windows, but I have to quote the `*` on Linux. It was really scary when I once ran `yarn up **` on Linux...)
- When working with `bash`, I know that it will always expand the globs I use. When working with PowerShell on Windows, I know that it will never do that. But on Linux, it has an inconsistent behavior that I have to think about before running commands. (This gets worse when the same command can mean different things on Windows and Linux, like `rm` and `ls` and the likes.)
- PowerShell glob expansion still needs work (#15959 and #13098 for example), and I don't want to get caught in the middle of my work.
- I don't like glob expansion in bash anyways. It is a somewhat scary feature to me. (I almost always quote my wildcards in bash, if the command I'm using recognizes them (like `git`), or switch to PowerShell if it doesn't.)

### Proposed technical implementation details (optional)

Add a configuration to PowerShell to disable glob expansion on Linux, or if such configuration already exists, include a mention to it in the docs ([here](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/unix-support) for example).

**Comment by andrewhickman** [comment]
This is particularly annoying with the splat operator. For example,
```
$arguments = @('*')
printf @arguments
```
On linux, this is treated as a glob and I don't think there's any way to escape it.

**Comment by Storm-BE** [comment]
I'm also having this issue (with the splatting), and haven't found any workaround yet.

**Comment by andrewhickman** [comment]
The workaround I used was to invoke bash with globs disabled on Linux

```
sh -f -c @arguments
```
