### ISSUE TITLE
Using Where-Object command with multiple 'not equals' operators returns unexpected results for PSCustomObjects

### ISSUE THREAD

**Issue by phall-au** [PowerShell/PowerShell#17177]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Filtering PSCustomObjects with multiple 'not equal' operators returns fewer results than expected. For example, consider the following sample code.

An object is created with multiple PSCustomObjects added containing the first and last names of users:
```powershell
$OldFile = @()

$OldFile += [PSCustomObject]@{firstName = 'Peter'; lastName = 'Hall'}

$OldFile += [PSCustomObject]@{firstName = 'Peter'; lastName = 'Griffin'}

$OldFile += [PSCustomObject]@{firstName = 'Peter'; lastName = 'Greenwood'}

$OldFile += [PSCustomObject]@{firstName = 'Jane'; lastName = 'Greenwood'} 

$OldFile += [PSCustomObject]@{firstName = 'John'; lastName = 'Greenwood'}

$OldFile += [PSCustomObject]@{firstName = 'James'; lastName = 'Greenwood'}

$OldFile


firstName lastName
--------- --------
Peter     Hall
Peter     Griffin
Peter     Greenwood
Jane      Greenwood
John      Greenwood
James     Greenwood
```

Filtering the object to exclude users with a first name of 'Peter' and last name of 'Hall' incorrectly excludes Peter Griffin and Peter Greenwood too:
```powershell
$OldFile | Where-Object {$_.firstName -ne 'Peter' -and $_.lastName -ne 'Hall'}


firstName lastName
--------- --------
Jane      Greenwood
John      Greenwood
James     Greenwood
```

If this is the intended behaviour, reversing the logic should see Peter Hall, Peter Griffin, and Peter Greenwood included in the results, but this is not the case:
```powershell
$OldFile | Where-Object {$_.firstName -eq 'Peter' -and $_.lastName -eq 'Hall'}


firstName lastName
--------- --------
Peter     Hall
```

### Expected behavior

```console
$OldFile | Where-Object {$_.firstName -ne 'Peter' -and $_.lastName -ne 'Hall'}


firstName lastName
--------- --------
Peter     Griffin
Peter     Greenwood
Jane      Greenwood
John      Greenwood
James     Greenwood

# Peter Griffin and Peter Greenwood are correctly included in the results.
```

### Actual behavior

```console
$OldFile | Where-Object {$_.firstName -ne 'Peter' -and $_.lastName -ne 'Hall'}


firstName lastName
--------- --------
Jane      Greenwood
John      Greenwood
James     Greenwood

# Peter Griffin and Peter Greenwood are incorrectly excluded from the results.
```

### Environment data

```powershell
$PSVersionTable                                                       


Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:x…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Northman-de** [comment]
Where-Object let everything pass, where the result is TRUE.
You use AND. Only TRUE AND TRUE = TRUE
Step by step:
Firstname = Peter / Lastname = Griffin
$_.firstName -ne 'Peter' = FALSE
$_.lastName -ne 'Hall' = TRUE
FALSE AND TRUE = FALSE
Therefore it does not pass the where-object

Use this:
```
[PS]> $OldFile | Where-Object {-not ($_.firstName -eq 'Peter' -and $_.lastName -eq 'Hall')}

firstName lastName
--------- --------
Peter     Griffin
Peter     Greenwood
Jane      Greenwood
John      Greenwood
James     Greenwood

```

**Comment by phall-au** [comment]
Oh my, PEBKAC here. Thank you @Northman-de!
