### ISSUE TITLE
Resolve-Path can't handle paths with square brackets in file names.

### ISSUE THREAD

**Issue by ttappr** [PowerShell/PowerShell#17185]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
$tempRoot = Split-Path (New-TemporaryFile).FullName
$tempDir = New-Item "$tempRoot\$(New-Guid)" -Type Directory
$squareDirPath = "$tempDir\[some-filename]" 
New-Item $squareDirPath -Type Directory

Get-ChildItem $tempDir   # You can see the folder "[some-filename]" listed.

$resolved = Resolve-Path $squareDirPath   # Returns $null

Write-Host "Resolved path: $resolved"
```

### Expected behavior

```console
PS> .\above-code.ps1
  :
  :
Resolved path: C:\Users\yourname\AppData\Local\Temp\04f23865-f882-4240-9583-f3665aa4ba73\[some-filename]
```

### Actual behavior

```console
PS> .\above-code.ps1
  :
  :
Resolved path:
```

### Error details

```console
Get-Error doesn't report any errors from the above code.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

This problem may not be specific to Resolve-Path. I suspect other path related commands are not dealing with file names with square brackets properly.

**Comment by ThomasNieto** [comment]
Does it work if you use -LiteralPath parameter instead of -Path?

**Comment by ttappr** [comment]
Yes, it does. Thank you.

**Comment by ttappr** [comment]
I wasn't able to find the issues related to square brackets in paths earlier when I filed this. But I do see mention of known issues with square bracket and paths on stackoverflow. I'll assume I they're there. Using -LiteralPath does solve my problem. So, I'm going to close this.
