### ISSUE TITLE
Add Push/Pop mechanism for Preference-Variables

### ISSUE THREAD

**Issue by kevinholtkamp** [PowerShell/PowerShell#17186]
### Summary of the new feature / enhancement

We all know the code constructs like this:
```Powershell
$Temp = $ErrorActionPreference
$ErrorActionPreference = "stop"
(Doing Stuff)
$ErrorActionPreference = $Temp
```
With any of the many available preference variables. When "Doing Stuff" is only calling one cmdlet, this can easily be simplified using the `-ErrorAction "silentlycontinue"` parameter, but when you need to set it for multiple calls and some in-between lines of code, that can get very annoying and confusing.

When working with locations, you could use `Push-Location` and `Pop-Location` to make your code very concise and easy to read. Something similar for preference variables would simplify code snippets like the example above a lot.

### Proposed technical implementation details (optional)

Since preference variables are mutable enums, I don't think for example `$ErrorActionPreference.Push("stop")` would work, instead cmdlets like `Push-ErrorActionPreference "stop"` similar to locations would need to be made.

Also some thought would need to be put into how this would work in conjunction with the common parameter `-ErrorAction`, for example that every time the parameter is explicitly specified, it gets pushed, and on end of the cmdlet, it is popped.

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this yesterday and concluded that scopes already provide a easy syntax for push/pop semantics. For instance:

```powershell
$ErrorActionPreference = 'Break'
& { 
    $ErrorActionPreference = 'SilentlyContinue'
    Get-ChildItem doesnotexist
}

# ErrorActionPreference will be back to Break and a breakpoint will be hit below
Get-ChildItem doesnotexist
```

**Comment by kevinholtkamp** [comment]
I see, thanks for taking the time!
