### ISSUE TITLE
Partner CmdLets are missing or not loading

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#1718]
The following CmdLets are expected to be available in Nano but are not:
- [ ] Get-DnsClient
- [ ] Get-DnsClientGlobalSetting
- [ ] Get-DnsClientServerAddress
- [ ] Get-AutologgerConfig
- [ ] Get-EtwTraceProvider
- [ ] Get-EtwTraceSession
- [ ] Get-NetAdapter
- [ ] Get-NetAdapterAdvancedProperty
- [ ] Get-NetAdapterChecksumOffload
- [ ] Get-NetAdapterLso
- [ ] Get-NetAdapterPowerManagement
- [ ] Get-NetFirewallAddressFilter
- [ ] Get-NetFirewallApplicationFilter
- [ ] Get-NetFirewallInterfaceFilter
- [ ] Get-NetFirewallInterfaceTypeFilter
- [ ] Get-NetFirewallPortFilter
- [ ] Get-NetFirewallProfile
- [ ] Get-NetFirewallRule
- [ ] Get-NetFirewallSecurityFilter
- [ ] Get-NetFirewallServiceFilter
- [ ] Get-NetFirewallSetting
- [ ] Get-NetCompartment
- [ ] Get-NetIPAddress
- [ ] Get-NetIPInterface
- [ ] Get-NetIPv4Protocol
- [ ] Get-NetIPv6Protocol
- [ ] Get-NetNeighbor
- [ ] Get-NetOffloadGlobalSetting
- [ ] Get-NetPrefixPolicy
- [ ] Get-NetRoute
- [ ] Get-NetTCPConnection
- [ ] Get-NetTCPSetting
- [ ] Get-NetTransportFilter
- [ ] Get-NetUDPEndpoint
- [ ] Get-NetUDPSetting
- [ ] Get-NetIPConfiguration
- [ ] Test-NetConnection
- [ ] Get-PnpDevice
- [ ] Get-PnpDeviceProperty
- [ ] Get-DiskSNV
- [ ] Get-PhysicalDiskSNV
- [ ] Get-Disk
- [ ] Get-DiskStorageNodeView
- [ ] Get-InitiatorId
- [ ] Get-MaskingSet
- [ ] Get-Partition
- [ ] Get-PhysicalDisk
- [ ] Get-PhysicalDiskStorageNodeView
- [ ] Get-ResiliencySetting
- [ ] Get-StorageAdvancedProperty
- [ ] Get-StorageFaultDomain
- [ ] Get-StorageNode
- [ ] Get-StoragePool
- [ ] Get-StorageProvider
- [ ] Get-StorageSetting
- [ ] Get-Volume
- [ ] Get-SupportedFileSystems
- [ ] Get-VolumeCorruptionCount
- [ ] Get-VolumeScrubPolicy

**Comment by joeyaiello** [comment]
@SteveL-MSFT adding High Priority here because it's something we need to close on for Nano Server by our RC. 

@xumins we should talk about this in our next sync.

**Comment by SteveL-MSFT** [comment]
@joeyaiello based on our last discussion with Nano team, it seems we can take this off `6.0.0-HIghPriority`

**Comment by joeyaiello** [comment]
Just to summarize before I pull this off of `HighPriority`: I believe the fix here is basically to somehow include `system32` in the PowerShell Core on Nano when those modules are present.

**Comment by SteveL-MSFT** [comment]
@joeyaiello perhaps the way to solve this problem is a StartupConfig setting to include WindowsPowerShell module path?

**Comment by TravisEz13** [comment]
@SteveL-MSFT This fix would be specific to nano

**Comment by lzybkr** [comment]
One possible fix - we don't change PSModulePath at all, instead we create symbolic links under PowerShell Core's `$PSHome\Modules` path to the **tested** Windows PowerShell modules.

This way, we don't pick up everything from Windows PowerShell, only stuff we've tested.

**Comment by chrisfcarroll** [comment]
May I comment that although this issue is labelled OS-Windows, most of this list are things we'd want to have cross-platform, e.g. Get-Net* ?

**Comment by iSazonov** [comment]
@chrisfcarroll Could you please open new Issue and enumerate all needed cmdlets Get-Net*?

**Comment by TravisEz13** [comment]
Also adding how you would use them would be useful.

**Comment by SteveL-MSFT** [comment]
This specific issue should be addressed by the WindowsPSModulePath module on PSGallery

**Comment by chrisfcarroll** [comment]
Noted ; and thankyou. I opened https://github.com/PowerShell/PowerShell/issues/6076
