### ISSUE TITLE
Microsoft.PowerShell.SDK: Custom script parameters are not fully serialized, when invoked via remote session

### ISSUE THREAD

**Issue by moerwald** [PowerShell/PowerShell#17195]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In the following example I'm calling a script block on a remote server. The scriptblock receives an `$Inventory` parameter, which is a nested C#  object (depth > 1). It seems that the parameter is only serialized with `depth=1`. Based on `$Inventory | Export-Clixml "$env:TEMP\f2.txt"` I can see that the CLI-XML doesn't contain nested information.

```
var wsManInfo = new WSManConnectionInfo();
var runSpace = RunspaceFactory.CreateRunspace(wsManInfo);
runSpace.Open();
var powerShell = PowerShell.Create();
powerShell.Runspace = runSpace;
powerShell.AddScript(@"
Param($Inventory)


$Inventory | Export-Clixml ""$env:TEMP\f2.txt""


$Inventory.SoftwareInventory.Groups[0].Software

").AddParameter("Inventory", variables);
var results = powerShell.Invoke();
```

Would be great to create an option to set the serialization depth of custom objects.

Actually the depth is `1`, based on `PSObject`:

```
  public virtual void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            if (info == null)
            {
                throw PSTraceSource.NewArgumentNullException(nameof(info));
            }

            // We create a wrapper PSObject, so that we can successfully deserialize it
            string serializedContent;
            if (this.ImmediateBaseObjectIsEmpty)
            {
                PSObject serializeTarget = new PSObject(this);
                serializedContent = PSSerializer.Serialize(serializeTarget);
            }
            else
            {
                serializedContent = PSSerializer.Serialize(this);
            }

            info.AddValue("CliXml", serializedContent);
        }
```

Is it possible to set the serialization depth via the API?

### Expected behavior

```console
A custom object shall be serialized in required depth.
```

### Actual behavior

```console
A custom object is serialized with depth=1.
```

### Environment data

```powershell
Microsoft.PowerShell.SDK 7.2.2
```

**Comment by daxian-dbw** [comment]
You can set the serialization depth to 2 on the client side. The `SerializationDepth` is a setting in the ETS (type system).
You can set it either by `Update-TypeData`, such as `Update-TypeData -TypeName 'OuterObject' -SerializationDepth 2`, or by having a `.ps1xml` file for the new type settings -- an example can be found here: https://github.com/PowerShell/PowerShell/issues/3549#issuecomment-293844899
