### ISSUE TITLE
Symbol lookup error: …/libmi.so: undefined symbol: SSL_library_init

### ISSUE THREAD

**Issue by Zocker1999NET** [PowerShell/PowerShell#17193]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with connecting to Office 365 to administer it using PowerShell in Docker. I am using the mcr.microsoft.com/azure-powershell Docker image on Debian.

To connect to the Office 365 servers, I use following snippet:
```powershell
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid -Credential $null -Authentication Basic -AllowRedirection -ErrorAction Stop
Import-PSSession $Session -ErrorAction Stop
```

This issue is related to #16615 as they share the same error message. There is a workaround described, which indeed works, however a permanent solution should be implemented to fix this issue as, in my opinion, this is a use case which worked before out of box and should continue to work out of box with the official Docker image.

Thanks for your work on PowerShell.

### Expected behavior

```console
PowerShell credential request
Enter your credentials.
User: xxx@xxxx.com
Password for user x: *********************

…

PS>
```

### Actual behavior

```console
PowerShell credential request
Enter your credentials.
User: xxx@xxxx.com
Password for user x: *********************

pwsh: symbol lookup error: /opt/microsoft/powershell/7/libmi.so: undefined symbol: SSL_library_init
# exits docker container runtime
```

### Error details

```console
# I cannot execute Get-Error afterwards because PowerShell is forcefully exiting the session
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.16.0-5-amd64 #1 SMP PREEMPT Debian 5.16.14-1 (2022-03-15)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS>
```

**Comment by daxian-dbw** [comment]
The [OMI](https://github.com/microsoft/omi) project is in maintenance mode and won't fix the OpenSSL version issues like this one. The best shot is to move to the [PSWSMan](https://www.powershellgallery.com/packages/PSWSMan/) module as @jborean93 suggested.

**Comment by c-0815** [comment]
Hello,

OMI Project has fixed it and provides libs linked against openssl 3 libs. I could test it successfully on Ubuntu 22.04 with the latest 7.2 lts released by just replacing the libmi.so and removing the dead links in `/opt/microsoft/powershell/7/` . In the 7.4 branch it seems that the necessar code has removed. The prolem is, that this is the only way do connect to W2K16 servers. So plz put it back to 7.4.

kind regards

Ralph
