### ISSUE TITLE
Windows Long Paths isn't enabled.

### ISSUE THREAD

**Issue by Fragmachine** [PowerShell/PowerShell#17197]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Calling e.g. 'Remove-Item' on a path longer than MAX_PATH will result in the following error,
`Remove-Item: The system cannot find the path specified.`
This works as expected in the PowerShell 5.1 version. 
Specifically, the `longPathAware` setting is missing from the manifest. Doing a simple Hex find in the executable reveals this while being there in the older PowerShell version.

Suggested fix is to add the following to the manifest (from [Microsoft](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)):
`
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
`

### Expected behavior

```console
PS> Remove-Item <SOME_MAX_PATH_EXCEEDING_PATH>
PS>
```

### Actual behavior

```console
PS> Remove-Item <SOME_MAX_PATH_EXCEEDING_PATH>
Remove-Item: The system cannot find the path specified.
```

### Error details

```console
PS> get-error

Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 3
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : IsReparsePointLikeSymlink
        DeclaringType : Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message         : The system cannot find the path specified.
    Source          : System.Management.Automation
    HResult         : -2147467259
    StackTrace      :
   at Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods.IsReparsePointLikeSymlink(FileSystemInfo fileInfo)
   at Microsoft.PowerShell.Commands.RemoveItemCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
InvocationInfo        :
    MyCommand        : Remove-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 43
    Line             : Remove-Item -Recurse -Force -ErrorAction Ignore -Path '<SOME_MAX_PATH_EXCEEDING_PATH>'
    PositionMessage  : At line:1 char:1
                       + Remove-Item -Recurse -Force -ErrorAction Ignore -Path '<SOME_MAX_PATH_EXCEEDING_PATH> …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Remove-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Fragmachine** [comment]
I noticed that issue wasn't there anymore when syncing and building the latest on github. Turns out I hit an edge case when the path was exactly at 260 characters that was [fixed a few months ago](https://github.com/PowerShell/PowerShell/commit/7bb8fa16abdbfb6d2610402491860c1feff9154e) but has yet to reach a release. Could it perhaps be part of a hotfix?

**Comment by iSazonov** [comment]
Please add more exact repro steps.

**Comment by Fragmachine** [comment]
In the current release paths that are exactly 260 characters can't be removed with Remove-Item, e.g.

```
PS> "c:\$(@('aaaaaaaaaa')*23 -join '\')\aaaa" | %{mkdir $_} | %{Remove-Item $_.FullName}
Remove-Item: The system cannot find the path specified.
```
Add/remove one character from the path and it works,

```
PS> "c:\$(@('aaaaaaaaaa')*23 -join '\')\aaaaa" | %{mkdir $_} | %{Remove-Item $_.FullName}
PS>
```

As already stated, this has been fixed in the developer line but a hotfix would be nice.

**Comment by iSazonov** [comment]
The fix you mentioned is for edge case. Root fix for long path support was added early and presents in 7.2 version.

**Comment by Fragmachine** [comment]
Yes, I hit an edge case as already explained. So this bug can be closed since I didn't realize it at the time. Should I create a new request for the edge case fix to go into a hotfix or is there a new release on the horizon which has the fix included?

**Comment by iSazonov** [comment]
Policy is to backport only critical and security fixes. So you have to wait next release or use preview version (they are stable too).

**Comment by Fragmachine** [comment]
Thanks for the information, time to close :-)
