### ISSUE TITLE
A dictionary type that only implements the generic IDictionary interface doesn't support dot notation (property-access syntax)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17190]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Related:
* #15204

`[Tomlyn.Model.TomlTable]`, from the [Tomlyn package](https://github.com/toml-lang/toml),  is an example of a type that implements ``IDictionary`2``, but not also its non-generic counterpart, `IDictionary`.

Seemingly, this prevents use of dot notation (property-access syntax via the member-access operator) to access the dictionary's entries.

```powershell
# Determine the package's local installation location.
# If it isn't installed, install it first, in the current user's scope.
while (-not ($installDir = (Get-Package -ErrorAction Ignore -ProviderName NuGet Tomlyn).Source)) {
  $null = Install-Package -Scope CurrentUser -ErrorAction Stop -ProviderName NuGet Tomlyn
}

# Load the package's assembly into the session.
Add-Type -ErrorAction Stop -LiteralPath (Join-Path $installDir '../lib/netstandard2.0/Tomlyn.dll')

# Define a sample TOML string to parse.
$tomlStr = @'
foo = "bar"
'@

# Parse the TOML string into an object mod)el (nested dictionaries).
$tomlTable = [Tomlyn.Toml]::ToModel($tomlStr)

# Output the global section's 'foo' value,
# first via an indexer, then via dot notation.
$tomlTable['foo'], $tomlTable.foo | ForEach-Object { "[$_]" }
```

### Expected behavior

```console
[bar]
[bar]
```

### Actual behavior

```console
[bar]
[]
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.3
```

**Comment by iSazonov** [comment]
It seems we already have an issue about generic enumerators. (Or was an discussion in an PR?)

**Comment by mklement0** [comment]
@iSazonov, the OP links to https://github.com/PowerShell/PowerShell/issues/15204 - or are you thinking of yet another issue? Note that while said issue may have the same root cause (which is why I liked to it), the issue at hand isn't about enumeration.

**Comment by iSazonov** [comment]
@mklement0 Yes, it seems #15204 was in my mind but I mean rather #12412. I would like to see all aspects of support for these generics.
