### ISSUE TITLE
The MSIX Release v7.2.3 seems not correctly signatured?

### ISSUE THREAD

**Issue by C8H17OH** [PowerShell/PowerShell#17202]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I try to install Powershell-7.2.3.msixbundle, Windows Application Installer tells me it is not signatured ans thus not trusted. It's OK to install using the .msi file. I didn't see this MSIX package's hash value in release note, either, but it's truly within the assets. What's wrong with this?

Btw I found this problem when try to use WinGet-Create to update the manifest of Powershell in winget-pkg, and winget-create reports an System.IO.FileNotFoundException error. I guess it's the same problem with what I encountered as below.

### Expected behavior

```console
MSIX package installed successfully.
```

### Actual behavior

```console
Windows Application Installer tells me it is not signatured ans thus not trusted.
```

### Environment data

```powershell
Current Version: 7.2.2
Want to update to: 7.2.3
```

**Comment by SteveL-MSFT** [comment]
This should now be fixed
