### ISSUE TITLE
Test-Connection -quiet parameter not working as documentation states in 7+

### ISSUE THREAD

**Issue by xKoloblicin** [PowerShell/PowerShell#17204]
### Steps to reproduce

Test-Connection with the -quiet parameter is performing inversely to what the microsoft documents state it will. The description of -quiet states "If any ping to a given target succeeds, $True is returned. If all pings to a given target fail, $False is returned." I can confirm this works as described in Powershell 5.1, but in 7+ it appears to work inversely. If any of the the replies are fail then the bool returns $false. I have tested it several times and it has always reproduced the same results. Thank you in advance for your assistance everyone. 

Documentation for the Test-Connection commandlet. 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.2#:~:text=False-,%2DQuiet,-The%20Quiet%20parameter

### Expected behavior

```console
Test-Connection -TargetName 10.250.18.81 -Quiet 
#This assumes at least 1 reply. 

Result
True
```

### Actual behavior

```console
Test-Connection -TargetName 10.250.18.81 -Quiet 
#This assumes at least 1 reply. 

Result
False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


AND Tested the Preview as well. 

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

7.2.3
![image](https://user-images.githubusercontent.com/83723506/165547908-ccd68dd0-04ed-48e2-a307-3c95199b8fc8.png)
VS 5.1
![image](https://user-images.githubusercontent.com/83723506/165547627-3ba4e467-1929-4e80-9115-719460c1e7ce.png)

**Comment by vexx32** [comment]
Relevant code is here:
https://github.com/PowerShell/PowerShell/blob/f4e38e8fa73e9409f83db619eb5655ff565bd01d/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs#L602-L657

It's possible some of this code is not working as described; in particular I'm suspicious of the `&=` operator used to combine results; maybe this should be `|=` ?

**Comment by xKoloblicin** [comment]
@vexx32 Thank you for the rapid response. I personally would think the original function of the cmdlet was the more useful as if there is any reply from the target, it at least has marginal connectivity. In the method I am using it, the command was throwing false positives with around 1% packet loss at times. But perhaps I am an outlier in this situation.

**Comment by vexx32** [comment]
I think in general it makes some sense to assume there is likely to be _some_ packet loss in any real-world scenario, so from that perspective I would say the described behaviour in the live documentation makes more sense. But I will leave the final decision to the Cmdlets working group for now 🙂

**Comment by iSazonov** [comment]
The loss of ping packets clearly shows that there is a problem on the network.

**Comment by kasini3000** [comment]
ping2.ps1 is my powershell script tool for you.
if all package timeout by parameter -n,then lost property return true
https://gitee.com/chuanjiao10/kasini3000/blob/master/lib/ping2_v2.02.ps1

**My purpose of writing this script:**
1 The information output by ping.exe of winxp and win7 is different. Chinese win, English win, the output ping information is different. Different scripts are required for bat, and I can use this to unify.
2 The ping.exe of winxp and win7 will only output information and will not return information. My script can return information.
For example, remove the # in the last line of the script to return, $private:script:n, $private:script: time statistics.maximum.
They are the number of pings and the maximum time, respectively. Of course, other values can also be returned.
3 The ping function that comes with powershell2.0, Test-Connectionn, cannot return the ping delay time.
4 The ping function that comes with powershell3.0, Test-Connectionn, can return the ping delay time, but cannot get the number of timeouts. I can.
5 In the ps of win and linux, the details returned by Test-Connectionn are different.

------

kasini3000 site mirror:(https://github.com/kasini3000/kasini3000)
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline)
Open source, free, cross-platform
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

kasini3000_agent_linux Shell script,one click install powershell on linux,modify sshd_config for PsRemote.
