### ISSUE TITLE
Document that running Powershell.exe from PowerShell results in a different version of PowerShell

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#1720]
## Steps to reproduce

`PowerShell.exe`
## Expected behavior

It should open the same version of powershell that I'm running
## Actual behavior

It actually opens the inbox PowerShell

```
PS C:\Program Files\PowerShell\6.0.0.7> powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Program Files\PowerShell\6.0.0.7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14901.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14901.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
## Environment data

``` powershell
> $PSVersionTable
PS C:\Program Files\PowerShell\6.0.0.7> $psversiontable

Name                           Value
----                           -----
GitCommitId                    v6.0.0-alpha.7-378-g86c5d3e4c88fe1489dcb657132e64dd8535da6a1
WSManStackVersion              3.0
PSEdition                      Core
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
CLRVersion


```

**Comment by joeyaiello** [comment]
I agree with @vors here. This is by design, PATH precedence should always win (though it would certainly make things easier if we emitted the version in the startup header). 

Did the investigation by @HemantMahawar or @BrucePay show anything?

**Comment by TravisEz13** [comment]
If we decide this is the correct behavior, there should be a definitive way to execute a new process with the same version of PowerShell.

**Comment by MaximoTrinidad** [comment]
I'm not sure how useful it will be. But, if PowerShell Core will coexist with Windows PowerShell, maybe it will be good to investing in a simple cmdlet to help detect which versions are available. Then, it can give you the option to pick which version to execute.  

This may be useful when doing WinRm between Windows systems having both Windows PowerShell and PowerShell Core.

:)

**Comment by joeyaiello** [comment]
Is it not simply `& $PSHOME\powershell.exe`? 

Or are you thinking about a cmdlet wrapper like `Start-PowerShell`?

**Comment by TravisEz13** [comment]
` & $PSHOME\pewershell.exe` works for me, but we should document this as $PSHOME was not required previously.

**Comment by TravisEz13** [comment]
this has been fixed
