### ISSUE TITLE
PowerShell v7.2.1 through v7.2.2 - Windows Update Doesn't Install into Original Directory

### ISSUE THREAD

**Issue by thakyZ** [PowerShell/PowerShell#17211]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- Download Powershell v7.2.1 x64 MSI installer
- Install Powershell into an internal secondary drive
- Make sure to enable MU features in the installer
- Run Windows Update
- Windows Update should start downloading and installing Powershell v7.2.2
- After Update notice how the Powershell install folder on the secondary drive is empty and Powershell is now installed on your main drive.

### Expected behavior

```console
Windows Update should update Powershell 7 to the original directory you installed it in.
```

### Actual behavior

```console
Windows Update has no regard for where you would like programs installed and instead chooses to install Powershell 7 updates on the main drive.
```

### Environment data

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
> (Get-CimInstance Win32_OperatingSystem) | Select-Object -Property Version, Caption
Version    Caption
-------    -------
10.0.19044 Microsoft Windows 10 Pro
```

### Windows update log

```markdown
> Get-WindowsUpdateLog
# Couldn't seem to upload the log so here is the log on a secret gist.
# https://gist.github.com/thakyZ/52291db72017e22300845488b3c32c9c
```

**Comment by TravisEz13** [comment]
Did you install PowerShell to a custom folder during setup?

**Comment by thakyZ** [comment]
Yes I did.

**Comment by TravisEz13** [comment]
The update doesn't support that scenario. Due to technical limitations in Windows Update.  Can you share the following information?
1. The path you originally installed to
2. the output of the following PowerShell script
```
$env:ProgramFiles
dir -recurse HKLM:\SOFTWARE\Microsoft\PowerShellCore\
```

**Comment by thakyZ** [comment]
```
PS> $env:ProgramFiles
C:\Program Files

PS> dir -recurse HKLM:\SOFTWARE\Microsoft\PowerShellCore\
    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore

Name                           Property
----                           --------
InstalledVersions

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore\InstalledVersions

Name                           Property
----                           --------
31ab5147-9a97-4452-8443-d9709f SemanticVersion : 7.2.3
0516e1                         InstallDir      : D:\Program Files\PowerShell\7\
                               InstallLocation : D:\Program Files\PowerShell\7\

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore

Name                           Property
----                           --------
ProgramsMenuShortcut

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShellCore\ProgramsMenuShortcut

Name                           Property
----                           --------
7                              installed : 1
```

**Comment by thakyZ** [comment]
I have since upgraded, just to note, but its in the same install dir

**Comment by TravisEz13** [comment]
I'll add a test for this case, but to be clear, we cannot detect this condition correctly through microsoft update.  So, the correct behavior is to not update the installation at all.   We discussed removing the option to install anywhere but the expected location but decided against it.

**Comment by TravisEz13** [comment]
Filed work item 25 in the update automation project.

**Comment by thakyZ** [comment]
May I have an update about this if you can provide one? I am currently on 7.2.5 and am still having issues while it's installed into my secondary drive. Also, if this has been fixed, which since is a "Resolution-External" it's probably with Windows itself, is it only fixed on Windows 11 or does it apply to Windows 10?
