### ISSUE TITLE
Powershell stuck on startup waitting futex syscall on Ubuntu 20.04

### ISSUE THREAD

**Issue by hongwen000** [PowerShell/PowerShell#17229]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. `apt update` and `apt upgrade` the OS the last version
> Linux hostname 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
2. Make sure that powershell package version to be the latest

> Package: powershell
> Version: 7.2.3-1.deb
> Priority: extra
> Section: shells
> Maintainer: PowerShell Team <PowerShellTeam@hotmail.com>
> Installed-Size: 191 MB
> Depends: libc6, libgcc1, libgssapi-krb5-2, libstdc++6, zlib1g, libicu72|libicu71|libicu70|libicu69|libicu68|libicu67|libicu66|libicu65|libicu63|libicu60|libicu57|libicu55|libicu52, libssl1.1|libssl1.0.2|libssl1.0.0
> Homepage: https://microsoft.com/powershell
> License: MIT License
> Vendor: Microsoft Corporation
> Download-Size: 69.4 MB
> APT-Manual-Installed: yes
> APT-Sources: https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages
> Description: PowerShell is an automation and configuration management platform.
>  It consists of a cross-platform command-line shell and associated scripting language.

3. Install Powershell from offical repo `sudo apt install powershell`
4. Start powershell `pwsh -NoLogo -NoProfile `

### Expected behavior

```console
Powershell launches and waits for user input.
```

### Actual behavior

```console
Pwsh stucks and command line never shows.
```

### Error details

```console
`strace -f pwsh -NoLogo -NoProfile` shows the process is stucking at
`futex(0x555c967a37a4, FUTEX_WAIT_PRIVATE, 0, NULL`
```

### Environment data

```powershell
Actually, this problem can be reproduced even in an cleaned environment.

env -i bash --noprofile --norc 
bash-5.0$ env
```
> PWD=/home/username
> SHLVL=1
> _=/usr/bin/env

### Visuals

![image](https://user-images.githubusercontent.com/25456415/165944567-03c3070e-cdc8-4faf-ae0b-41eba8c4c9aa.png)

**Comment by hongwen000** [comment]
Make-up: 
At first I met this issue when I found my backup script written in powershell stuck for days. And this problem would happen definitely in a period of time, but does not reappear in latter days.
So I'm wondering if it is the **powershell automatic update check** caused the problem, which stucks powershell on network IO and gives no warning.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.2

**Comment by ulbi** [comment]
Hi, not sure whether this is still relevant.
I just found this hint: https://github.com/PowerShell/PowerShell/issues/10173#issuecomment-1139345623

In my case one NAS did hang - after unmounting it, powershell did start working again.

Maybe this helps.

**Comment by hongwen000** [comment]
@ulbi Thank you for the reminding me this. This recalls me that I was mounting an unstable NFS to my Linux server when I ran into this problem. I didn't link this problem with the NFS mount because I didn't expect these mounts might get touched even when powershell just launches.
