### ISSUE TITLE
Get-AppxProvisionedPackage -Online not working and seeing error.

### ISSUE THREAD

**Issue by kaboddy** [PowerShell/PowerShell#17232]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I can't seem to run 'get-appxprovisionedpackage -Online' via PS 7.2.3.  Seems to run fine in 5.1 still.

### Expected behavior

```console
PS C:\Users\keith> Get-AppxProvisionedPackage -Online


DisplayName  : B9ECED6F.133F79A42C6
Version      : 2018.611.704.0
Architecture : neutral
ResourceId   : ~
PackageName  : B9ECED6F.133F79A42C6_2018.611.704.0_neutral_~_qmba6cd70vzyy
Regions      :

DisplayName  : Microsoft.549981C3F5F10
Version      : 4.2203.4603.0
Architecture : neutral
ResourceId   : ~
PackageName  : Microsoft.549981C3F5F10_4.2203.4603.0_neutral_~_8wekyb3d8bbwe
Regions      :

DisplayName  : Microsoft.BingNews
Version      : 4.9.30001.0
Architecture : neutral
ResourceId   : ~
PackageName  : Microsoft.BingNews_4.9.30001.0_neutral_~_8wekyb3d8bbwe
Regions      :
etc, etc, etc...
```

### Actual behavior

```console
PS C:\Users\keith> Get-AppxProvisionedPackage -Online
Get-AppxProvisionedPackage: Class not registered
```

### Error details

```console
PS C:\Users\keith> Get-Error

Exception             :
    Type       : System.Runtime.InteropServices.COMException
    ErrorCode  : -2147221164
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation,
Version=7.2.3.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Class not registered

    Source     : System.Management.Automation
    HResult    : -2147221164
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
CategoryInfo          : NotSpecified: (:) [Get-AppxProvisionedPackage], COMException
FullyQualifiedErrorId : Microsoft.Dism.Commands.GetAppxProvisionedPackageCommand
InvocationInfo        :
    MyCommand        : Get-AppxProvisionedPackage
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : Get-AppxProvisionedPackage -Online
    PositionMessage  : At line:1 char:1
                       + Get-AppxProvisionedPackage -Online
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-AppxProvisionedPackage
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

PS C:\Users\keith>
```

### Environment data

```powershell
PS C:\Users\keith> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/69687422/166007343-ab6074cb-34f3-43b2-b14b-0f61876f30fb.png)

**Comment by daxian-dbw** [comment]
The command works fine for me, either on an MSI installation or a zip package installation:

![image](https://user-images.githubusercontent.com/127450/166973673-94effbf9-6df7-4019-a7ff-628f21ca1405.png)

Are you using the pwsh installed from Microsoft Store?

**Comment by daxian-dbw** [comment]
> Are you using the pwsh installed from Microsoft Store?

I verified that the error only occurs in the Store version of pwsh. It's likely due to the restriction from being a Store app.
The workaround is to use either the MSI version or the zip version of pwsh. For MSI installation, you can setup in the installer to use Windows Update to upgrade pwsh, so it will be similar to the Store version from the upgrade perspective, but with no restriction.

**Comment by kaboddy** [comment]
Weird.  I replied earlier but it didn't appear.  Ah well.

Yeah, I think I did originally install through the MS Store.  I'll take a look at what you've suggested.

Should I uninstall before re-installing via msi / zip?

**Comment by daxian-dbw** [comment]
> EDIT: This seems to happen a lot with apps from the Microsoft Store - Why are things so inconsistent?

This is because Windows Store apps are tightly sandboxed, which doesn't work well for PowerShell given the shell needs to touch things that may be restricted from store apps.

> All Windows Store apps are tightly sandboxed. This means Windows Store apps run in their own virtual space (the sandbox) and whatever happens to it does not affect any other app running or the OS itself.

**Comment by kaboddy** [comment]
I believe my original install was from the MS Store.  It’s been a bit since I upgraded, I’m not sure how I upgraded – Might have been winget.

Keith
