### ISSUE TITLE
请求新增windwos server 2003对高版本powershell的支持

### ISSUE THREAD

**Issue by audio79** [PowerShell/PowerShell#17236]
### Summary of the new feature / enhancement

请求新增windwos server 2003对高版本powershell的支持。

**Comment by kasini3000** [comment]
https://github.com/PowerShell/PowerShell/releases/download/v7.2.3/PowerShell-7.2.3-win-x86.zip
我没有win2003环境，请你试试此解压版是否能运行？如果可以，就试试下面的安装板。
如果不行，请贴出报错信息。谢谢。


==============
https://github.com/PowerShell/PowerShell/releases/download/v7.2.3/PowerShell-7.2.3-win-x86.msi

**Comment by jhoneill** [comment]
Translation says this is a request for current PowerShell on Server 2003  
Extended support for 2003 ended in July 2015,  and current versions of PowerShell are supported on 2012 R2 and later and not supported on 2012 and earlier.  
Server 2012 is the oldest OS still in extended support, so ideally PowerShell _should_  support that.  
But the number of customers wanting to keep out-of-support OSes in production, **and** add new software to them is so small that it the effort can't be justified.
