### ISSUE TITLE
Requesting to implement the "Show Script Pane Left" Button on the Windows PowerShell ISE

### ISSUE THREAD

**Issue by NFSCoder9821** [PowerShell/PowerShell#17240]
### Summary of the new feature / enhancement

There are only 3 options available to see the Script Pane and the result window. They are:

- Show Script Pane Top
- Show Script Pane Right
- Show Script Pane Maximized

Could you please implement the "Script Pane Left and the result window right" feature as this is also looks better to the developers and useful.

Thank You Microsoft!

**Comment by SeeminglyScience** [comment]
The ISE is no longer in active feature development. The recommendation is to use [Visual Studio Code](https://code.visualstudio.com/) with the [PowerShell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell).

Note that VSCode allows you to position editor panes and terminal panes wherever you'd like.
