### ISSUE TITLE
PowerShell runspace pool hang during asynchronous batch processing

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#17250]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The hang occurs when PowerShell is running batched commands (with statement separators) that are invoked asynchronously in a runspace pool.
This is not a recent regression, as I see the same behavior in Windows PowerShell (5.1).

```powershell
$runspacePool = [RunspaceFactory]::CreateRunspacePool()
[void]$runspacePool.SetMaxRunspaces(2)
[void]$runspacePool.SetMinRunspaces(1)
$runspacePool.Open()

$thread = [powershell]::Create()
$thread.RunspacePool = $runspacePool

[void] $thread.AddScript("Write-Output 'Hello'")
[void] $thread.AddStatement().AddScript("Write-Output 'Goodbye'")

Write-Verbose -Verbose "Invoking synchronously..."
$output = $thread.Invoke()
Write-Output $output

Write-Verbose -Verbose "Invoking asynchronously..."
$job = $thread.BeginInvoke()
$output = $thread.EndInvoke($job)
Write-Output $output
```

### Expected behavior

```console
VERBOSE: Invoking synchronously...
Hello
Goodbye
VERBOSE: Invoking asynchronously...
Hello
Goodbye
```

### Actual behavior

```console
VERBOSE: Invoking synchronously...
Hello
Goodbye
VERBOSE: Invoking asynchronously...
# PowerShell hangs here
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
The problem is with AddStatement(), which doesn't support async.

**Comment by JamesWTruher** [comment]
@WG-engine
we agree it looks like a bug
