### ISSUE TITLE
PowerShell becomes unresponsive if child process is suspended

### ISSUE THREAD

**Issue by GrantMoyer** [PowerShell/PowerShell#17269]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Either:
1. install WSL 1
2. Run `wsl vi` from PowerShell prompt
3. Press <kbd>Ctrl</kbd>+<kbd>z</kbd>

Or:
1. Download [PsSuspend][1]
2. Run a command line app from PowerShell prompt, for example `ftp`
3. Run `pssuspend.exe <ID of process from step 2>`

[1]: https://docs.microsoft.com/en-us/sysinternals/downloads/pssuspend

### Expected behavior

Either PowerShell creates a suspended PowerShell background job for the child process (which can later be resumed), or PowerShell immediately resumes the child process to prevent becoming unresponsive.

### Actual behavior

PowerShell becomes unresponsive to all input until child process is resumed (either via pssuspend or `kill -SIGCONT` for WSL jobs) or killed.

### Environment data

```powershell
Name                      Value
----                      -----
PSVersion                 7.2.3
PSEdition                 Core
GutCommitId               7.2.3
OS                        Microsoft Windows 10.0.19044
Platform                  Win32NT
PSCompatibleVersions      {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion      1.1.0.1
WSManStackVersion         3.0
```

**Comment by daxian-dbw** [comment]
> 1. install WSL 1
>2. Run `wsl vi` from PowerShell prompt
>3. Press <kbd>Ctrl</kbd>+<kbd>z</kbd>

Am I supposed to run 2 and 3 from pwsh that opened directly on Windows?
I'm using WSL v2, and I cannot reproduce the issue:

![CompletionPredictor](https://user-images.githubusercontent.com/127450/166978824-3d1872e7-8efd-4900-abde-0bbe182fd15d.gif)

**Comment by GrantMoyer** [comment]
> Am I supposed to run 2 and 3 from pwsh that opened directly on Windows?

Yes, the steps in your screen capture are exactly correct, except you need to use WSL v1. Although I have not tried to repoduce the issue in WSL v2, since WSL v1 is a translation layer, and WSL v2 uses a linux virtual machine, and the issue has to do with Windows process states, it makes sense to me that the issue is reproducible in v1 but not in v2.

**Comment by daxian-dbw** [comment]
Thanks for the reply. Given that it doesn't reproduce in WSL v2, it's likely a specific issue with related to WSL v1. I will resolve this as external then.

**Comment by GrantMoyer** [comment]
@daxian-dbw Note that the issue also occurs without WSL at all, using the alternative repro steps.

**Comment by daxian-dbw** [comment]
When run a console application like `ftp` from the pwsh prompt, pwsh will be waiting for the `ftp` process to exit. When you run `PsSuspend` to suspend the `ftp` process, it's suspended but not exited, so pwsh will keep waiting for it. That's the by design behavior.

**Comment by GrantMoyer** [comment]
I'd consider this behavior very unexpected for an interactive shell. Most other interactive shells I've used will recognize if a child process is suspended, make the child process a background job, and return to the shell's prompt.

**Comment by kasini3000** [comment]
win is not linux, there is no fg/bg in win, only multiple windows.
Powershell is not a terminal software, maybe the terminal software supports vi better.
My personal advice:
Use vscode+remote ssh extension instead of vi.
Use vscode+remote wsl extension instead of vi.
