### ISSUE TITLE
Parse error when string concat operator on new line in PS 7.2.3

### ISSUE THREAD

**Issue by agaace** [PowerShell/PowerShell#17298]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This doesn't work:

```powershell
$longText = "Hi, I'm a very long string that likes to be broken down to several lines so that it fits"
  + " within character limit nicely without horizontal scrollbars."

Write-Host $longText
```

But this does:

```powershell
$longText = "Hi, I'm a very long string that likes to be broken down to several lines so that it fits" +
  " within character limit nicely without horizontal scrollbars."

Write-Host $longText
```

For a demo, save this as `BugDemo.ps1`:
```powershell
$longText = "Hi, I'm a very long string that likes to be broken down to several lines so that it fits"
  + " within character limit nicely without horizontal scrollbars."

Write-Host $longText

```

### Expected behavior

```console
PS> ./BugDemo.ps1
Hi, I'm a very long string that likes to be broken down to several lines so that it fits within character limit nicely without horizontal scrollbars.
```

### Actual behavior

```console
PS> ./BugDemo.ps1
InvalidArgument: C:\Agata\Projects\BugDemo.ps1:2:3
Line |
   2 |    + " within character limit nicely without horizontal scrollbars."
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value " within character limit nicely without horizontal scrollbars." to type "System.Int32". Error: "Input
     | string was not in a correct format."

Hi, I'm a very long string that likes to be broken down to several lines so that it fits
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
That is normal behaviour
The parser reads this
```
$longText = "Hi, I'm a very long string that likes to be broken down to several lines so that it fits"
  + " within character limit nicely without horizontal scrollbars."
```
And sees the first line as complete.  So it assigns the string to the variable. Then it moves on to the next line

if you have 
```
$longText = "Hi, I'm a very long string that likes to be broken down to several lines so that it fits"  + 
```
or 
```
$longText = "Hi, I'm a very long string that likes to be broken down to several lines so that it fits 
```
or
```
$longText = ("Hi, I'm a very long string that likes to be broken down to several lines so that it fits" 
```
The parser sees that the + needs another operand, or the " or (  needs to be closed  and sees one _logical_ line despite line break character(s)   this applies to any operator not just concatenation and arithmetic, the | or "," can be followed by white space and/or line break as can  -and , -eq etc.

If you don't want the  line break be seen as the end of a syntactically complete statement use `  as the last character before the line break - this causes the parser to ignore it, it must be the **last** character if there are spaces after the ` the first space is escaped and the line break still completes the statement..

**Comment by SeeminglyScience** [comment]
Note that that's a runtime error rather than parse time.

The new line makes parse as a unary plus. The docs say it "makes a number out of an object" so it's basically trying to cast it to int. But yeah, most operators need to be on the previous line tell the parser to ignore new lines.

**Comment by JamesWTruher** [comment]
please remember that this is a *Shell*. Imagine typing this at the command line, the first line in your example is complete statement unto itself. The second line in your example is as @SeeminglyScience states. This is by design.
