### ISSUE TITLE
Get-Help -ShowWindow has inconsistent indentation for example lines

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#17296]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
function testExampleIndent {
  <#
  .SYNOPSIS
  Example of indent problem
  .EXAMPLE
  My-Commandline-Text

  The Result

  This text is not indented in -ShowWindow but is in Get-Help

  #>
  [CmdletBinding()]
  param(

  )
}
```

### Expected behavior

```console
Consistency between -ShowWindow and command line
```

### Actual behavior

```console
Inconsistency. ShowWindow additional text should also be indented the same as Get-Help, but is not
```

### Environment data

```powershell
7.2.2
```

### Visuals

![image](https://user-images.githubusercontent.com/15258962/167512103-d891dd46-bccc-4759-a773-6d1b9d229484.png)
![image](https://user-images.githubusercontent.com/15258962/167512117-1ea6ac25-88a4-4c78-93f9-d8bd5869e04b.png)

**Comment by sdwheeler** [comment]
I was able to reproduce this. This is specific to rendering comment-based help with the **ShowWindow** parameter. It appears that any descriptive text is render without indentation. This can be multiple lines.

PowerShell 5.1 has the same behavior. This may be by design.

**Comment by theJasonHelmick** [comment]
Thank you @JustinGrote  for reporting this issue.  The Interactive WG has reviewed this issue and agrees that there is an issue with the display of -ShowWindow.  At this time, we are not interested in investing in the UI components.
