### ISSUE TITLE
$PSNativeCommandArgumentPassing = "Windows" doesn't work with empty args

### ISSUE THREAD

**Issue by rmccampbell** [PowerShell/PowerShell#17305]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When PSNativeCommandArgumentPassing is enabled and $PSNativeCommandArgumentPassing = "Windows", empty arguments don't work with native commands. I copied the exact example shown in the [PS docs](https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.2#psnativecommandargumentpassing), along with the TestExe.exe sample program compiled from the [source](https://github.com/PowerShell/PowerShell/blob/master/test/tools/TestExe/TestExe.cs), but with the feature variable set to "Windows":
```
> $PSNativeCommandArgumentPassing = "Windows"
> .\TestExe.exe -echoargs '' a b ''
Arg 0 is <a>
Arg 1 is <b>
```
"Standard" mode works just fine and according to the example. According to the [docs](https://docs.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.2#psnativecommandargumentpassing), I would expect the "Standard" and "Windows" modes to be the same other than the special cases mentioned.

### Expected behavior

```console
> $PSNativeCommandArgumentPassing = "Windows"
> .\TestExe.exe -echoargs '' a b ''
Arg 0 is <>
Arg 1 is <a>
Arg 2 is <b>
Arg 3 is <>
```

### Actual behavior

```console
> $PSNativeCommandArgumentPassing = "Windows"
> .\TestExe.exe -echoargs '' a b ''
Arg 0 is <a>
Arg 1 is <b>
```

### Environment data

```powershell
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
have a look my feedback here:
https://github.com/PowerShell/PowerShell/discussions/16605

**Comment by daxian-dbw** [comment]
The expected result probably should be the following (got it from running in CMD)
```
C:\>C:\arena\repos\PowerShell\test\tools\TestExe\bin\Debug\net7.0\win-x64\publish\testexe.exe -echoargs '' a b ''
Arg 0 is <''>
Arg 1 is <a>
Arg 2 is <b>
Arg 3 is <''>

C:\>
```

**Comment by rmccampbell** [comment]
@daxian-dbw The intention is to pass the *contents* of the arguments verbatim to the program, not the raw powershell syntax. Powershell interprets the empty quotes as empty strings. When passed to the underlying program they should be passed as double quotes so the C runtime interprets them as empty strings. This is how the "Standard" mode works.

**Comment by daxian-dbw** [comment]
@rmccampbell That makes sense!

**Comment by rmccampbell** [comment]
This seems to have been fixed at some point, though I don't know in which version. The test program shows the expected behavior above on 7.3.6. So this can be closed.
