### ISSUE TITLE
Quoted slash problem

### ISSUE THREAD

**Issue by inshua** [PowerShell/PowerShell#17301]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The problem is 
````
[AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.Location.Length -And $_.Location.Split('\')[-1].Equals("mscorlib.dll") }
````
works fine.

but
````
[AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.Location.Length -And $_.Location.Split('\\')[-1].Equals("mscorlib.dll") }
````
failed.

for '\\' not recognized as escaped string, and both them will output found item in Windows Powershell.

### Expected behavior

```console
PS> [AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.Location.Length -And $_.Location.Split('\\')[-1].Equals("mscorlib.dll") }

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll
```

### Actual behavior

```console
PS> [AppDomain]::CurrentDomain.GetAssemblies() | Where-Object { $_.Location.Length -And $_.Location.Split('\\')[-1].Equals("mscorlib.dll") }

Nothing output.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
This is due to an additional overload in `String.Split`. In 7.3 it selects the new `String.Split(string)` overload where previously it converted to `char[]` and selected `String.Split(char[])`.

Note that in neither version is it considered an escape character, it was just previously splitting on  any of the characters in the string rather than the exact string. You may be looking for a split that uses regex (`String.Split` does not), that would be either the split operator (`-split`) or the `[regex]::Split` method.

**Comment by inshua** [comment]
Thank you @SeeminglyScience
