### ISSUE TITLE
Bug in docu of Set-Content (in PS 7.2 LTS)

### ISSUE THREAD

**Issue by moerwald** [PowerShell/PowerShell#17309]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Docu of [Set-Content](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-7.2) states:

---

## Parameters

\-AsByteStream

Specifies that the content should be **read** as a stream of bytes. This parameter was introduced in PowerShell 6.0.

A warning occurs when you use the **AsByteStream** parameter with the **Encoding** parameter. The **AsByteStream** parameter ignores any encoding and the output is returned as a stream of bytes.

--- 

### Expected behavior

```console
Shouldn't it be ?

> Specifies that the content should be WRITTEN as a stream of bytes.
```

### Actual behavior

```console
Wrong docu
```

### Environment data

```powershell
PS 7.2 LTS
```

**Comment by daxian-dbw** [comment]
@sdwheeler, can you please move this issue to the PowerShell-Doc repo?

**Comment by daxian-dbw** [comment]
OK, created the doc issue: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8802
@moerwald Thanks for reporting the issue!

**Comment by sdwheeler** [comment]
@daxian-dbw Thanks for creating the doc bug.
