### ISSUE TITLE
High cpu usage when parsing scripts that include [ordered]

### ISSUE THREAD

**Issue by Sjark** [PowerShell/PowerShell#17308]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We are parsing multiple powershell scripts in parallel using Parser.ParseInput but are having issues with perf when the scrips being parsed includes multiple [ordered] attributes/types.

The parser starts to use 100% cpu, and it takes a long time for the parsing to complete.

[Repro here](https://github.com/Sjark/PowershellParsingIssue)

The console app above has 2 identical powershell scripts included, the only difference is that on of them has a bunch of [ordered] before the hashtable assignments.

The one without [ordered] completes almost instantly, while the one with [ordered] takes some time and uses a lot of cpu.

### Expected behavior

```console
Parsing to complete in about the same time with both scripts.
```

### Actual behavior

```console
Parsing takes a lot longer and uses a lot more resources when the script includes [ordered].
```

### Error details

The error seems to be related to `LookForTypeInAssemblies` method within the TypeResolver.cs:68

Every time it finds a [ordered] in the script it goes through all loaded assemblies to try and find the matching type, but since [ordered] is not actually a type (just a helper for creating `System.Collections.Specialized.OrderedDictionary`) the method returns null, and will search again the next time it finds an [ordered] attribute.

I think there should either be a cache for types that did not match any assemblies, so that it doesn't have to look through the same assemblies for the same type multiple times, or there should be a special case for [ordered] so that it does not even try to search through the assemblies for it.

### Environment data

```powershell
We are using nuget package: System.Management.Automation version 7.2.3
```

**Comment by vexx32** [comment]
My general understanding is that `[ordered]` is one of the standard type accelerators, so it should be resolved almost immediately in terms of type lookup. Also, it's not even a real type, afaik it's just a parser trick to tell PowerShell to build the resulting dictionary completely differently (since if it was built the normal way and _then_ cast, the resulting dictionary would not retain the original order in the script).

Flagging this for WG-Engine to have a look at.

**Comment by SeeminglyScience** [comment]
Believe it or not, there's no actual type accelerator associated. I would have thought that the compiler would skip type resolution for it though, since it doesn't actually use the resolution at all.

Adding a type accelerator to `OrderedDictionary` would likely solve this problem, and also ease a ton of confusion around this pseudo keyword

**Comment by vexx32** [comment]
Oh, yeah? Interesting. I would also have expected it to simply skip the type resolution completely, since it's... not intended to be a type in itself. 🤔 

Even if you define a type called `[ordered]` in the current session, it still doesn't get _used_ for an `[ordered]@{ ... }` expression, so it's very odd to me that type lookup would ever be implicated. For example:

```ps1
PS> class ordered {ordered([System.Collections.Specialized.OrderedDictionary]$d) { }}
PS> $a = [ordered]@{ a = 1; b = 2 }
PS> $a

Name                           Value
----                           -----
a                              1
b                              2

PS> $a.GetType().FullName
System.Collections.Specialized.OrderedDictionary
```

Also... a type simply named "ordered" is actually _unusable_ because of how the parser handles `[ordered]`:

```ps1
PS> $b = [ordered]$a
ParserError:
Line |
   1 |  $b = [ordered]$a
     |      ~~~~~~~~~~~
     | The ordered attribute can be specified only on a hash literal node.
```

So it's... really weird... that `[ordered]` does _any_ type lookups whatsoever.

**Comment by daxian-dbw** [comment]
I think there are 2 problems worth discussing here:
1. `[ordered]` is treated as a special attribute solely for the syntax `[ordered] + <literal hash table>`. Is that something we want to change?
2. more generally, shall we optimize the parser to not keep attempting to resolve a type name when it cannot be resolved?

There could be another repro for this issue: I'm using the type name `[sometypename]` in my script at tons of places, but the type is not available until at run time -- a call to `Add-Type` or `Import-Module` will load the assembly containing that type. Parsing the script will experience the same slowness.

**Comment by SeeminglyScience** [comment]
> I think there are 2 problems worth discussing here:
> 
> 1. `[ordered]` is treated as a special attribute solely for the syntax `[ordered] + <literal hash table>`. Is that something we want to change?

I think it would be reasonable to make it an actual type accelerator and have fall back logic like we already do for `[pscustomobject]`. Maybe not fall back as that might lead to confusion that we already face with `[pscustomobject]` outside of compiler recognized scenarios. But we can at least make it resolvable.

> 2. more generally, shall we optimize the parser to not keep attempting to resolve a type name when it cannot be resolved?
> 
> There could be another repro for this issue: I'm using the type name `[sometypename]` in my script at tons of places, but the type is not available until at run time -- a call to `Add-Type` or `Import-Module` will load the assembly containing that type. Parsing the script will experience the same slowness.

I think the second part answers the first part here 🙁. We can't actually know if a type will *never* be resolvable.

That said, I'm not really sure why type resolution isn't done lazily outside of classes. Does the parser really care what the true type is?

**Comment by Sjark** [comment]
> Believe it or not, there's no actual type accelerator associated. I would have thought that the compiler would skip type resolution for it though, since it doesn't actually use the resolution at all.
> 
> Adding a type accelerator to `OrderedDictionary` would likely solve this problem, and also ease a ton of confusion around this pseudo keyword

Would a type accelerator be able to initialize the OrderedDictionary, then add the items of the hashtable?

Just replacing `[ordered]` with `[System.Collections.Specialized.OrderedDictionary]` works fine with empty hashtable `@{ }`, but if the hashtable contains multiple properties, it will fail to cast the hashtable to OrderedDictionary

**Comment by SeeminglyScience** [comment]
> Would a type accelerator be able to initialize the OrderedDictionary, then add the items of the hashtable?

It wouldn't change runtime behavior of anything that currently works. It just makes the type resolvable. The compiler specifically checks for the literal text `ordered`, and doesn't actually try to resolve it (unlike the parser apparently).

**Comment by daxian-dbw** [comment]
> I think the second part answers the first part here 🙁. We can't actually know if a type will never be resolvable.

But can we know if a type will never be resolvable at parsing time only? What would cause new types available at parsing time? PowerShell classes are already taken care of when resolving symbols, and `using module/assembly` can only appear at the beginning of a script.

**Comment by daxian-dbw** [comment]
WG-Engine discussed this one today (5/12/2022).
> 1. `[ordered]` is treated as a special attribute solely for the syntax `[ordered] + <literal hash table>`. Is that something we want to change?
> 2. more generally, shall we optimize the parser to not keep attempting to resolve a type name when it cannot be resolved?

To the 1st question, we think it's a good idea to make `[ordered]` a true type accelerator for `[System.Collections.Specialized.OrderedDictionary]` and remove the parser code that restricts `[ordered]` to only be used before a literal Hashtable. We believe this will help making the `[ordered]` type less special and more consistent with `[pscustomobject]`.

To the 2nd question, the same performance degradation would happen to another non-resolvable type name in the script, so it would be nice to resolve this perf issue in the root -- not looking up a non-resolvable type name multiple times during parse would provide a significant boost to performance.

**Comment by daxian-dbw** [comment]
#17328 was merged to mitigate the perf issue regarding `[ordered]` specifically:
> This alone cuts the wallclock time for parsing `[ordered]@{}` compared to `[nonexisting]@{}` by 45-50%:

**Comment by Sjark** [comment]
Thanks for the quick fix. I guess this will be included in the next version of System.Management.Automation package (7.2.5)? If so, do you have any target date for that release?
