### ISSUE TITLE
An Uninitialized declared array leads to string concatenation

### ISSUE THREAD

**Issue by DanielAdeniji** [PowerShell/PowerShell#17313]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

<#
Code Availed Online @ https://gitlab.com/-/snippets/2319534
#>
<#
  Declare Variables
#>
[int] $i=0;
[int] $numberofEntries =0;
[string] $FORMAT_NAME_DETAIL="";
[string] $FORMAT_NAME_AGGREGATE="";
[string] $title="";

<#
    Declare strongly typed array of string 
#>
[string[]]$nameListInitialized = $null;
[string[]]$nameListUnInitialized;

<#
   Prepare Variables
#>
$FORMAT_NAME_DETAIL = "{0,3}) {1,-60}"
$FORMAT_NAME_AGGREGATE = "`tNumber of entries:- {0}"

<#
   Populate Array
#>
$nameListInitialized += "Joya";
$nameListInitialized += "Tom";
$nameListInitialized += "Kate";

<#
   Populate Array
#>
$nameListUnInitialized += "Joya";
$nameListUnInitialized += "Tom";
$nameListUnInitialized += "Kate";

$i =0;

$FORMAT_NAME_DETAIL = "{0,3}) {1,-60}"

Write-Host "";   

Write-Host "";   

$title = "List - `$nameListInitialized";

Write-Host $title;

Write-Host "";   

<#
    Iterate list of names
#>
foreach ($name in $nameListInitialized)
{
        
    $i = $i + 1;
        
    $log = $FORMAT_NAME_DETAIL -f $i, $name;
        
    Write-Host $log
        
    Write-Host "";   
}

$numberofEntries = $nameListInitialized.count;

$log = $FORMAT_NAME_AGGREGATE -f $numberofEntries;
    
Write-Host $log
    

<#
    Iterate list of names
#>

$i =0;

Write-Host "";   
Write-Host "";   

$title = "List - `$nameListUnInitialized";

Write-Host $title;

Write-Host "";   

foreach ($name in $nameListUnInitialized)
{
        
    $i = $i + 1;
        
    $log = $FORMAT_NAME_DETAIL -f $i, $name;
        
    Write-Host $log
        
    Write-Host "";   
}

$numberofEntries = $nameListUnInitialized.count;

$log = $FORMAT_NAME_AGGREGATE -f $numberofEntries;
    
Write-Host $log
    
Write-Host "";   

### Expected behavior

```console
1) Joya

  2) Tom

  3) Kate

        Number of entries:- 3
```

### Actual behavior

```console
1) JoyaTomKate

        Number of entries:- 1
```

### Environment data

```powershell
>powershell -Command "$PSVersionTable"

Name                           Value
----                           -----
PSVersion                      5.1.19041.1645
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1645
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![nameListInArrayInitialization 01 20220511 1003AM](https://user-images.githubusercontent.com/4267788/167906686-5e6c9a20-fd5f-4056-b218-5797efcc12fd.jpg)

**Comment by SeeminglyScience** [comment]
> <# Declare strongly typed array of string #> [string[]]$nameListInitialized = $null; [string[]]$nameListUnInitialized;

So the latter isn't actually declaring anything. It's just casting `$nameListUnInitialized` (which will be null at that time) to `string[]`. Only the former actually creates a variable, so this behavior is by design.

**Comment by DanielAdeniji** [comment]
Patrick:-

Good one.

Thanks so very much for the very quick, yet accurate, clarification.

Credited you here.

  1.  PowerShell:- Datatype – Array – Declaration & Initialization
Link<https://learningintheopen.org/2022/05/11/powershell-datatype-array-declaration-initialization/>
  2.  PowerShell:- Datatype – Array – Declaration & Initialization – Bug ? – Patrick Meinecke Response
Link<https://learningintheopen.org/2022/05/11/powershell-datatype-array-declaration-initialization-bug-patrick-meinecke-response/>

Daniel
________________________________
