### ISSUE TITLE
7.2.3: Invoke-Webrequest Tls 1.3 not working properly

### ISSUE THREAD

**Issue by Hamsterman** [PowerShell/PowerShell#17333]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have found that this Invoke-WebRequest -Method GET -Uri "somesite" -SslProtocol Tls13 fails when it's an Tls1.3 ONLY website.

PS> Invoke-WebRequest -Method GET -Uri "tls13.1d.pw" -SslProtocol Tls13
Invoke-WebRequest: The client and server cannot communicate, because they do not possess a common algorithm.

When the website support other TLS versions ASWELL as Tls1.3 the command works fine.

### Expected behavior

```console
It is working
```

### Actual behavior

```console
It is giving an error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
PowerShell does nothing with Tls, it follows .Net and OS. So you could use a sniffer to investigate the issue.

**Comment by Hamsterman** [comment]
> PowerShell does nothing with Tls, it follows .Net and OS. So you could use a sniffer to investigate the issue.

What would be the .NET version of the Invoke-WebRequest. Or in other words what do I need to do to reproduce in .NET

**Comment by mortenlerudjordet** [comment]
Have you tried to set tls before calling Invoke-WebRequest?

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls13

**Comment by Hamsterman** [comment]
This issue is really not answered - I can't see the working solution here.
