### ISSUE TITLE
Let each RunSpace have an IServiceProvider

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#17335]
### Summary of the new feature / enhancement

Using dependency injection in PowerShell is hard today. (I'm thinking about C# modules)

I'm considering adding an IServiceProvider property to Runspace/SessionState (and InitialSessionState) to help with getting hold of an IServiceProvider in a way that is accessible from cmdlets, and also easy to inject when writing tests.

Is this something that has already been considered?

Worth a PR?

**Comment by daxian-dbw** [comment]
@powercode More description about the scenario with examples would be helpful.

**Comment by powercode** [comment]
#17349 shows possible implementations.

The bigger context is being able to write testable modules in C#, where common services can be injected into cmdlets.
Normally, things like this are done by injection into the constructors, but since PowerShell owns the construction of cmdlets, we can at least be able to resolve services via an IServiceProvider.

I want to be able to have a common base class library for the things that are common across our modules, for example, logging, telemetry, and default implementations for things that are abstracted for testing, such as IFileSystem, IEnvironment, and a native process abstraction we have to make testing easier.

Tests are often run in parallel, and having the serviceprovider for each test (often with mocked interface implementations) injected into each powershell would really make it easier.

**Comment by PaulHigin** [comment]
@powercode   Please provide examples of how this would be used.

**Comment by powercode** [comment]
To be able to test code like this, that depends on things that needs to be mocked for testing:

```csharp


public interface IDateProvider
{
    DateTime Now { get; }
    DateTime UtcNow { get; }
}


[Cmdlet(VerbsCommon.Get, "Date")]
[OutputType(typeof(DateTime))]
public class GetDateCommand : PSCmdlet
{
    private IDateProvider DateProvider => SessionState.ServiceProvider.GetRequiredService<IDateProvider>();
    private ILogger<GetDateCommand> Logger => SessionState.ServiceProvider.GetRequiredService<ILogger<GetDateCommand>>();

    protected override void EndProcessing()
    {
        var logger = Logger;
        
        var date = DateProvider.Now;

        logger.LogInformation("Getting date {now}", date);
        
        WriteObject(date);
    }
}
```

A host could do the following:

```csharp

public class DefaultDateProvider : IDateProvider
{
    public DateTime Now => DateTime.Now;
    public DateTime UtcNow => DateTime.UtcNow;
}

class Program
{
    public static int Main(string[] args)
    {
        var services = new Microsoft.Extensions.DependencyInjection.ServiceCollection()
            .AddLogging(builder => { builder.AddEventSourceLogger(); })
            .AddSingleton(new DefaultDateProvider());
                        
        var iss = InitialSessionState.Create();
        iss.ServiceProvider = services.BuildServiceProvider();

        var exitCode = Microsoft.PowerShell.ConsoleShell.Start(iss, "Banner", "Help", args);
        return exitCode;
    }
}
```

And test could look like this:
```csharp

[TestClass]
public class DateTests
{
    [TestMethod]
    public void TestGetUtcDate()
    {
        var services = new Microsoft.Extensions.DependencyInjection.ServiceCollection()
            .AddLogging(builder => { builder.AddDebug(); })
            .AddSingleton(GetMockedDateProvider(
                () => new DateTime(2022, 10, 10, 11, 12, 13, DateTimeKind.Utc),
                () => new DateTime(2022, 10, 10, 11, 12, 13, DateTimeKind.Local)));

        var iss = InitialSessionState.CreateDefault();
        iss.ServiceProvider = services.BuildServiceProvider;

        iss.Commands.Add(new SessionStateCmdletEntry("Get-Date", typeof(GetDateCommand), null));

        using var ps = PowerShell.Create(iss);
        ps.AddCommand(new CmdletInfo("Get-Date", typeof(GetDateCommand)));
        var actual = ps.Invoke<DateTime>().First();
        var expected = new DateTime(2022, 10, 10, 11, 12, 13, DateTimeKind.Utc);
        Assert.AreEqual(expected, actual);
    }
    
    IDateProvider GetMockedDateProvider(Func<DateTime> utcFunc, Func<DateTime> nowFunc)
    {
        var dateMock = new Moq.Mock<IDateProvider>();
        dateMock.Setup(d => d.UtcNow).Returns(utcFunc());
        dateMock.Setup(d => d.Now).Returns(nowFunc());
        return dateMock.Object;
    }
}

```

**Comment by powercode** [comment]
If we need to use the default host, we can fall back to something like:

```csharp
private IDateProvider DateProvider => SessionState.ServiceProvider.GetService<IDateProvider>() ?? new DefaultDateProvider();
```

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this yesterday. We agree that there is value in providing a uniform way to use dependency injection in PowerShell, but we would need an alternate proposal that solves the conflict issue described in [#17349 (comment)](https://github.com/PowerShell/PowerShell/pull/17349#discussion_r874075860). We would need a way to ensure that a module author could obtain an `IServiceProvider` that is unique to their module (or group of modules).

For now we recommend utilizing the pattern suggested in [#17349 (comment)](https://github.com/PowerShell/PowerShell/pull/17349#discussion_r873888306).

**Comment by iSazonov** [comment]
Isn't this the same problem with isolating modules using the same library? We discussed this for a long time and came to the consensus that it is the task of the author of the module to provide isolation. Perhaps the DJ already supports this? If not, perhaps this should be discussed in the .Net repository?

**Comment by SeeminglyScience** [comment]
> Isn't this the same problem with isolating modules using the same library? We discussed this for a long time and came to the consensus that it is the task of the author of the module to provide isolation.

Technically you could get around this with ALC isolation but I wouldn't say it's the same issue. Considering how much trouble related issues have been, I don't think it's a good idea to add more on that pile. Especially since the use of DI is not blocked, I gave an example of a working pattern one can use today.

> Perhaps the DJ already supports this? If not, perhaps this should be discussed in the .Net repository?

A service provider is mostly intended to be used by a single author + maybe the framework that is being utilized. I'm unsure what their answer would be other than recommending a different service provider per author, but you're welcome to start a discussion there.
