### ISSUE TITLE
Update via Windows Update is stuck

### ISSUE THREAD

**Issue by oroboros** [PowerShell/PowerShell#17343]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

It's been a couple of days that I see PowerShell v7.2.3 (x64) stuck on "Installing - 0%".

I've tried to manually install the update (using the msi install from GitHub), but it shows that there's an installation already in progress.

I've tried to reboot a couple times.

### Expected behavior

```console
I'd expect the installation progress with time to be mroe than 0%
```

### Actual behavior

```console
Even after reboot it's always at 0%, even tried running Windows Update troubleshoot tool
```

### Environment data

```powershell
sorry
```

### OS Data

```powershell
sorry
```

### Windows update log

```markdown
sorry
```

### Visuals

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1668665/168421817-826f17c8-3b14-4351-8a9b-b0395656795d.png">

**Comment by StevenBucher98** [comment]
Hmm it looks like Windows Update was able to successfully update PS to v7.2.3 for me. @oroboros What was the version you are upgrading from? v7.2.2 presumably?

**Comment by TravisEz13** [comment]
Without windows update log this isn't actionable.
