### ISSUE TITLE
Get-ComputerInfo shows false OSVersion

### ISSUE THREAD

**Issue by Hope-IT-Works** [PowerShell/PowerShell#17348]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. `winver` -> results in Windows 11
2. `(Get-ComputerInfo).OSVersion` -> results in Windows 10

### Expected behavior

```console
should output windows 11 and subversion e.g.:

PS> (Get-ComputerInfo).OSVersion
11.0.22000
```

### Actual behavior

```console
PS> (Get-ComputerInfo).OSVersion
10.0.22000
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

1. `winver` -> results in Windows 11
2. `(Get-ComputerInfo).OSVersion` -> results in Windows 10

![image](https://user-images.githubusercontent.com/52013820/168501396-2bb0e806-a759-465a-8172-e8bd72e8af18.png)

**Comment by 237dmitry** [comment]
![Screenshot 2022-05-16 063531](https://user-images.githubusercontent.com/78153320/168515612-260c8e37-0c76-4be1-bbbe-3bda707989d5.png)

**Comment by ALIENQuake** [comment]
@Hope-IT-Works @237dmitry Everything is fine, Windows 11 has the major version equal to 10. Same story when Windows 7 was released - the major version was not increased to not confuse developers and application version requirements.

**Comment by 237dmitry** [comment]
> Everything is fine

That's what I'm talking about

**Comment by Hope-IT-Works** [comment]
Alright, thanks for the quick response.
