### ISSUE TITLE
format.ps1xml files fail to load if they reference properties in types.ps1xml file only in module manifest

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#17345]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Make a format and type file, format file should reference type file properties (Examples: https://github.com/JustinGrote/JAz.PIM/tree/main/Source/Formats)
2. Add the files to module manifest FormatsToProcess and TypesToProcess
3. Import the module, the format will not show correctly
4. Add this or a similar line to .psm1:
```
Get-ChildItem "$PSScriptRoot\Formats\*.Format.PS1XML" | Foreach-Object {
    Update-FormatData -PrependPath $PSItem
}
```
It now works.

I think this may be because formats load before types when specified via the module manifest, and this load order should be swapped.

### Expected behavior

```console
Format of object shows correctly
```

### Actual behavior

```console
Default formatting is shown.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22610
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by JustinGrote** [comment]
@SteveL-MSFT relevant to our twitter discussion.

**Comment by SeeminglyScience** [comment]
iirc the manifest field uses `AppendPath` which will essentially not override existing format definitions. If you need `PrependPath` (to override existing formats) then you need to load it in the psm1

**Comment by JustinGrote** [comment]
@SeeminglyScience I didn't consider the fact that these formats might be published by the `Az` or `Mg` module, even if they are defaults. Might be a bad test case, let me try to repro with more simple formats.

**Comment by SeeminglyScience** [comment]
Can also try `-AppendPath` in the psm1, see if you get the same behavior

**Comment by iRon7** [comment]
> Might be a bad test case, let me try to repro with more simple formats.

I experienced the same issue with `<TableControl>` format as shown here: https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?#example-add-calendar-data-to-culture-objects
