### ISSUE TITLE
Minimal Progress Bar PercentComplete not working correctly in VSCode

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#17379]
@SteveL-MSFT 
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
1..100 |% {write-progress -Activity 'ok' -Status 'ok' -PercentComplete $_;sleep 0.1}
```

### Expected behavior

```console
Normal Progress
```

### Actual behavior

```console
It gets hung up 1/3 of the way, it seems like it is miscalculating the window size
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22616
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## VSCode Windows (PSIC or Powershell External Term, doesn't matter)

https://user-images.githubusercontent.com/15258962/169166731-a0c44a4d-d8e7-45a6-ab6b-7adb09e13041.mp4

## Windows Terminal (Works Fine)

https://user-images.githubusercontent.com/15258962/169167060-247c2571-52d8-4cbb-8285-5eee6c67bf99.mp4

**Comment by daxian-dbw** [comment]
It works fine for me in VSCode, both the default shell and PowerShell integrated console:

![CompletionPredictor](https://user-images.githubusercontent.com/127450/169882594-3aea4157-3667-4a23-a02b-f5bb691ec332.gif)

![CompletionPredictor](https://user-images.githubusercontent.com/127450/169882715-72d7f22a-1edd-4c7e-b4ab-9efe1b0bf6a2.gif)

Does this have anything to do with the width/height of the terminal, or even the prompt used?

**Comment by JustinGrote** [comment]
@daxian-dbw might be the prompt, let me see if I am a special snowflake.

**Comment by JustinGrote** [comment]
@SeeminglyScience fresh vscode data folder install, with that the only setting. No dice.
![image](https://user-images.githubusercontent.com/15258962/170086071-22f6dcf3-399d-4bd1-81a2-8c3157ed8aa4.png)


I'm on Windows Insiders if that makes a difference, let me try a diff computer.

**Comment by SeeminglyScience** [comment]
Yeah if it's not insiders I'm at a loss there. Even tried stretching my window size to match yours, works every time 🤷

**Comment by JustinGrote** [comment]
Looks like it might be insiders special snowflake, I tried on a non-insiders and it worked fine. I'll close for now but we should keep an eye out for this in the next windows release.

**Comment by SeeminglyScience** [comment]
Maybe good to also report on feedback tool or https://github.com/microsoft/terminal since they own conpty

**Comment by eddiezato** [comment]
I encounter the described behavior in both VS Code Insiders and Terminal Preview.

```
PowerShell 7.2.4
Windows 11 22000.739
VS Code 1.69.0-insider 2022-06-17
Terminal Preview 1.14.1452.0
```
