### ISSUE TITLE
Powershell 7.2.x says use Windows Update to update, but its not shown as a Window Update

### ISSUE THREAD

**Issue by VashJuan** [PowerShell/PowerShell#17373]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I just want powershell to auto-update (in VScode insiders) automatically without my 'managing it' with extra commands, clicks/diversions of workflow. I'm on win 10 insiders, all software is the latest available. 

Currently I have to go to Windows Update which says I'm up-to-date (last checked 5 minutes ago...), then back to aka.ms to actually get and install the minor update. WASTED TIME FOR ME. Is there some way to just say "auto-install" powershell updates as soon as they are available? I'm happy to tolerate any bugs, as I'm NOT a power user.

Thx.

### Expected behavior

```console
NO time out of my work flow.
```

### Actual behavior

```console
About 4 minutes of (not so agonizing) clicking
```

### Environment data

```powershell
PS C:\Projects\rangertrak> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.19044 Microsoft Windows 10 Pro
```

### Windows update log

```markdown
PS C:\Projects\rangertrak> Get-WindowsUpdateLog
...
WindowsUpdate.log written to C:\Users\John\Desktop\WindowsUpdate.log
```

### Visuals

-

**Comment by TravisEz13** [comment]
Your installation is already up to date.

**Comment by VashJuan** [comment]
I know - because I MANUALLY updated it this morning. I want it to be automatic in the future...

**Comment by TravisEz13** [comment]
[Updates through windows update takes 1-2 weeks after we release.  ](https://docs.microsoft.com/en-us/powershell/scripting/install/microsoft-update-faq?view=powershell-7.2#how-soon-after-release-are-updates-advertised-by-microsoft-update)

**Comment by TravisEz13** [comment]
there is an issue about the timing of the message already filed here:  https://github.com/PowerShell/PowerShell/issues/17369

**Comment by TravisEz13** [comment]
The package from the Windows Store is more automatic.  There are some known issues with it, but they are corner cases, and we are working with Windows to resolve those issues.
