### ISSUE TITLE
Behavior of "cd -"

### ISSUE THREAD

**Issue by puya-ms** [PowerShell/PowerShell#17374]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`cd -` should navigate to the previous directory. However on Powershell Core on Windows it is similar to Windows back button. This is confusing for Linux users.

### Expected behavior

```console
1- currently in dir1
1- `cd -` # go to previous directory dir2
3- `cd -` # go to previous directory dir1
```

### Actual behavior

```console
1- currently in dir1
1- `cd -` # go to previous directory dir2
3- `cd -` # go to the directory previous to dir2, dir3
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rkeithhill** [comment]
@puya-ms PowerShell's `Set-Location` command, aliased to `cd`, implements a stack.  You use `-` to go backward in the stack and `+` to go forward in the stack.  In your case, try `cd -` and then `cd +` to see if that gets you the behavior you want.

**Comment by puya-ms** [comment]
Awesome thank you @rkeithhill!
