### ISSUE TITLE
Get-CimInstance Win32_ComputerSystem does not have Username property when using -ComputerName Optoin

### ISSUE THREAD

**Issue by koquinn75** [PowerShell/PowerShell#17371]
### Summary of the new feature / enhancement

I just moved from powershell 5.x to 7.2 and realized get-wmiobject was replaced by get-ciminstance.   Command output of **Get-CimInstance Win32_ComputerSystem** with **-ComputerName** option returns less data.

`get-ciminstance -ClassName Win32_ComputerSystem -Property *`

UserName displayed as an available property

`get-ciminstance -ClassName Win32_Computersystem -ComputerName Computer1 -Property *`

UserName is not an available property

I have tried adding Select-Object UserName and Format-Table Username with no success.    I have also tried $session=New-CimInstance -ComputerName Computer1 with and without DCOM option, the trying to using that Cimsession to retrieve value with no success.

**Comment by iSazonov** [comment]
Try `get-ciminstance -ClassName Win32_Computersystem | fl * -Force`

**Comment by jborean93** [comment]
The docs for `UserName` state

> Name of a user that is logged on currently. This property must have a value. In a terminal services session, UserName returns the name of the user that is logged on to the console not the user logged on during the terminal service session.

Because you are now no longer logged into that server directly and are accessing it through the network it's not going to have a user that is logged on interactively/console. This is expected behaviour, you should see it populated if someone has logged onto the host interactively (not just through RDP) and you run it remotely at the same time.

**Comment by koquinn75** [comment]
> The docs for `UserName` state
> 
> > Name of a user that is logged on currently. This property must have a value. In a terminal services session, UserName returns the name of the user that is logged on to the console not the user logged on during the terminal service session.
> 
> Because you are now no longer logged into that server directly and are accessing it through the network it's not going to have a user that is logged on interactively/console. This is expected behaviour, you should see it populated if someone has logged onto the host interactively (not just through RDP) and you run it remotely at the same time.
> 
> A better question is, what are you using it for? There might be a better and more reliable method available to you to get the desired information.

Jborean93,  I just have some basic scripts that I want to know the logged in users of the machine for  informational purposes for troubleshooting instead of remoting in just to find the user.   I can go back to PS 5.1 and use gwmi.   I am new to PS 7.x so if there is another way to pull the logged in user of a computer easily please let me know.  I have tried numerous ways and everytime I add the -ComputerName option it always returns blank but if I go to a computer and run (get-ciminstance -Class Win32_OperatingSystem).username it will work fine just not remotely.

**Comment by jborean93** [comment]
You will find that `Get-WmiObject` will have the same problem. Both cmdlets just gather the WMI class information and the `UserName` property is going to be null/empty if there are no interactive users present.

**Comment by koquinn75** [comment]
That is correct.  I would expect it to be blank if no one is logged in, but when there is a user logged in `Get-WmiObject` will return the user but `Get-CimInstance` will still return blank.

Is my syntax correct for `Get-CimInstance`?

`(Get-CimInstance -Classname Win32_ComputerSystem -ComputerName Computer1).username`

I have also tried

`Get-CimInstance -Classname Win32_ComputerSytem -ComputerName | Select -Object Username`

I'm not tied to that command so if there is another way to pull logged in user in 7.x PS I am all for it. 

Thank you everyone for your responses
