### ISSUE TITLE
Incorrect SHA256 Hashes of the release artifacts for Release v7.2.4

### ISSUE THREAD

**Issue by CodyALohse** [PowerShell/PowerShell#17377]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Looking to install the latest release v7.2.4 but it looks like the asset hashes are incorrect from what has been listed:

https://github.com/PowerShell/PowerShell/releases/tag/v7.2.4

I tested a couple assets:

PowerShell-7.2.2-win-x64.msi:

`Get-FileHash -Algorithm SHA256 .\PowerShell-7.2.2-win-x64.msi`

Results:
447b49fb3deaf1d1b632711a48978f18ae43f0a2fe4cdba007218026a6e39010

powershell-7.2.4-1.rh.x86_64.rpm
`Get-FileHash -Algorithm SHA256 .\powershell-7.2.4-1.rh.x86_64.rpm`

Resutls:
DCA598E6312AAD0BC04655601306E877C346596F38C11C1BA65D21D2AEEFB234

Apologies if I'm incorrectly generating these hashes.

### Expected behavior

```console
Get-FileHash -Algorithm SHA256 .\PowerShell-7.2.2-win-x64.msi
acf2d2ff232fa641b028c951ea184bc3e7e26c82b2f7df7f7a9a32478685988c
```

### Actual behavior

```console
Get-FileHash -Algorithm SHA256 .\PowerShell-7.2.2-win-x64.msi
447B49FB3DEAF1D1B632711A48978F18AE43F0A2FE4CDBA007218026A6E39010
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version
-------
10.0.22000
```

### Windows update log

```markdown
NA
```

**Comment by TravisEz13** [comment]
I tested this for the file you mentioned and the version you mentioned and found no issue.

hash listed for the **7.2.4** win-x64 MSI:
<img width="1241" alt="CleanShot 2022-05-18 at 16 27 48@2x" src="https://user-images.githubusercontent.com/10873629/169171543-620dad8a-df2c-4ca4-85de-46000bb0740f.png">


Local hash when I downloaded the file and ran get-filehash:
<img width="735" alt="CleanShot 2022-05-18 at 16 28 43@2x" src="https://user-images.githubusercontent.com/10873629/169171615-36a6c7e7-9487-4d5d-99ec-15695ee56c2a.png">

Also matches in hashes.sha256:
<img width="1087" alt="CleanShot 2022-05-18 at 16 30 52@2x" src="https://user-images.githubusercontent.com/10873629/169171809-75da45c3-a636-473b-b902-2dc9eec74ad1.png">

**Comment by CodyALohse** [comment]
Ah yes, my apologies. I had an older version (PowerShell-7.2.2-win-x64.msi) in the same directory and tab completed. Thanks for checking. Kind regards,

**Comment by TravisEz13** [comment]
No problem, If there was a problem, I'd want to hear about it right away.
