### ISSUE TITLE
[feature request] Searching and installing Microsoft Store apps directly from the PowerShell terminal

### ISSUE THREAD

**Issue by Foadsf** [PowerShell/PowerShell#17382]
### Summary of the new feature / enhancement

It is really annoying that the Appx module does not provide any functionality to search Microsoft Store and install applications directly from a Powershell terminal.

### Proposed technical implementation details (optional)

People have written [some scripts](https://serverfault.com/questions/1018220/how-do-i-install-an-app-from-windows-store-using-powershell), for a `Download-AppxPackage` but they seem to be outdated already. Plus a `Search-AppxPackage` would also be nice.

**Comment by doctordns** [comment]
This module is not part of PowerShell, but rather part of Windows PowerShell and thus not something the PowerShell team can fix. I agree that a tool to search the Windows store might be nice, it's probably outside the scope of this repo.

**Comment by Foadsf** [comment]
Hi @doctordns ,

Thanks for the response. Do you know where is the best place to request a feature request for "Windows PowerShell"? 🤔

**Comment by doctordns** [comment]
You can try here https://techcommunity.microsoft.com/

That being said, I would doubt you will get much if any traction. Virtually no Windows Powershell management tools have been touched in years. If the Windows feature teams can't even create PowerShell 7 native cmdlets, extending existing modules is highly unlikely. I suggest the best solution to be a rich App Store module for the Gallery.

**Comment by Foadsf** [comment]
Thanks @doctordns for the reply again. You seem to be an expert with PS. Maybe you can take a look at the available scripts on [this page](https://serverfault.com/questions/1018220/how-do-i-install-an-app-from-windows-store-using-powershell) and help me with them? 

- Are they safe to use on a work machine? 
- Do they work actually? I can't do try-errors on my device. 
- Is it possible to get already installed software updated through the terminal as well? something like `upgrade-AppxPackage`

**Comment by Foadsf** [comment]
For those who end up here, I submitted a new feature request through Feedback Hub [here](https://aka.ms/AAgzay2). Please upvote it so it gets more attention.

**Comment by doctordns** [comment]
> Thanks @doctordns for the reply again. You seem to be an expert with PS. Maybe you can take a look at the available scripts on [this page](https://serverfault.com/questions/1018220/how-do-i-install-an-app-from-windows-store-using-powershell) and help me with them?
> 
> * Are they safe to use on a work machine?
> * Do they work actually? I can't do try-errors on my device.
> * Is it possible to get already installed software updated through the terminal as well? something like `upgrade-AppxPackage`

Had a brief look. The `Download-AppxPackage` function just used `Invoke-WebRequest` to download the .APPX file. so should be safe. As to whether they work - harder to say. The _should_ wor,k, but I have not tested them and am NOT an APPX expert!

As a suggestion, for help on stuff like this, consider looking at the  [Spiceworks PowerShell Forum](https://community.spiceworks.com/programming/powershell). The regulars there may be able to provide more help.
