### ISSUE TITLE
Test-Connection with -TcpPort only tries IPv6 connection for localhost

### ISSUE THREAD

**Issue by javidcf** [PowerShell/PowerShell#17383]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Open an TCP server on some local port of the IPv4 loopback interface. For example, with Python 3 run a simple HTTP server with `python -m http.server --bind 127.0.0.1 8000`.
2. In another terminal, run `Test-Connection localhost -TcpPort 8000`.

### Expected behavior

The command returns `True`.

### Actual behavior

The command returns `False`.

If we run `Test-Connection 127.0.0.1 -TcpPort 8000` or `Test-Connection localhost -IPv4 -TcpPort 8000`, the returned result is `True`. The command `Test-NetConnection localhost -Port 8000` does give the correct answer, although it first tries connecting to `::1 : 8000` and fails.

### Error details

It seems `Test-Connection` is just testing the first loopback address it is finding, which is the IPv6 `::1` address. I think this behaviour is surprising, especially since locally deployed servers are most frequently bound to `127.0.0.1` only.

### Environment data

```
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
> It seems Test-Connection is just testing the first loopback address it is finding, which is the IPv6 ::1 address. I think this behaviour is surprising, especially since locally deployed servers are most frequently bound to 127.0.0.1 only.

Why surprising? It is how name resolving works. What do you expect to get from `ping localhost`?

**Comment by doctordns** [comment]
The basic `Test-NetConnection` uses ICMP to ping the remote host. By specifying the `-Port` parameter, the cmdlet used TCP to attempt to make a connection to the specified port. If you have port 8000 open, the cmdlet should report true if the remote host accepts the connection. Firewalls do have a way of interfering, though.

My home has full IPV6 connectivity and I find Windows seems to choose IPv6. Looking at Tracert traces the IPv6 path tends to be a little shorter and faster than IPv4, but mileage varies.

**Comment by vexx32** [comment]
It seems reasonable that if multiple possible addresses are found and the user hasn't specified either the `-IPv4` or `-IPv6` switches, `Test-Connection` could retry through the list of possible addresses?

**Comment by iSazonov** [comment]
> It seems reasonable that if multiple possible addresses are found and the user hasn't specified either the `-IPv4` or `-IPv6` switches, `Test-Connection` could retry through the list of possible addresses?

Why do you ask about IPv4 vs IPv6 if it is possible assign some IPv4 to single name (or some IPv6 to single name)? :-)

**Comment by jhoneill** [comment]
In pwsh 7,  `Test-Connection` always returns a Boolean but the help says it should return a rich object, as it did in Windows PowerShell. It is behaving as if `-Quiet` is always specified

When a name resolves to multiple IP addresses (especially if one is ipV4 and the other is V6) the help doesn't give indication if the Boolean returned should be ALL addresses work , ANY address works, or THE FIRST address works.   

The OP says it doesn't do what is *expected* - at the very least expectations could be set properly.

**Comment by vexx32** [comment]
@iSazonov 
> Why do you ask about IPv4 vs IPv6 if it is possible assign some IPv4 to single name (or some IPv6 to single name)? :-)

I'm not really sure what you're asking here, can you clarify?

> In pwsh 7, Test-Connection always returns a Boolean but the help says it should return a rich object, as it did in Windows PowerShell. It is behaving as if -Quiet is always specified

In both pwsh 7.2.4 and 7.3-preview1, it behaves as described in documentation:

```powershell
PS> test-connection localhost

   Destination: localhost

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 DESKTOP-TEHPDG2  ::1                             0         32 Success
   2 DESKTOP-TEHPDG2  ::1                             0         32 Success
   3 DESKTOP-TEHPDG2  ::1                             0         32 Success
   4 DESKTOP-TEHPDG2  ::1                             0         32 Success
```

Has that changed recently?

**Comment by iSazonov** [comment]
> > Why do you ask about IPv4 vs IPv6 if it is possible assign some IPv4 to single name (or some IPv6 to single name)? :-)
> 
> I'm not really sure what you're asking here, can you clarify?

I say your proposal makes no sense. If we wanted round trip we would have to allow all combinations for users. But it makes no sense - the cmdlet emulates classic ping and work like any service which request to resolve ip by name.

**Comment by jhoneill** [comment]
> @jhoneill
> 
> > In pwsh 7, Test-Connection always returns a Boolean  
> 
> In both pwsh 7.2.4 and 7.3-preview1, it behaves as described in documentation:
> 

Yesterday it was behaving like -Quiet was always on. Today it is working per the docs. Darned if I know what has changed.

**Comment by vexx32** [comment]
@iSazonov since a DNS address _can_ have resolve to often both IPv6 and IPv4 addresses, why would Test-Connection _not_ retry with the both addresses if one doesn't work, in the case that the user hasn't specified which IP standard to use?

Just because a tool that existed starting _before IPv6 ever existed_ doesn't do that, doesn't mean we can't make the user experience here better.

**Comment by iSazonov** [comment]
@vexx32 Combining ping and nslookup into one utility? I don't see the usefulness of that. I can't imagine the capabilities you're talking about would be useful to someone for network diagnostics or in a script.
I would prefer this cmdlet to reliably do the simplest things like ping.

**Comment by vexx32** [comment]
It already does DNS lookups. We're not adding anything extra there, just making use of the information it already has.

**Comment by jhoneill** [comment]
OK my failing brain has finally caught up ... 
The helps says "`Test-Connection` returns a TestConnectionCommand+PingStatus object` which it does for a ping, but isn't appropriate for a test of a of TCP port. It doesn't say the -TCPPort changes this to a boolean, nor does it give an example of using TCPPort. 
PowerShell 5 doesn't have the TCPPort option and returns a CIM object, which isn't great for cross platform.

**Comment by vexx32** [comment]
Ah, you're right, that's true. #11452 would improve that somewhat 🙂 

Though you're right, some examples would also be a good addition.

**Comment by doctordns** [comment]
> It seems reasonable that if multiple possible addresses are found and the user hasn't specified either the `-IPv4` or `-IPv6` switches, `Test-Connection` could retry through the list of possible addresses?

Thinking about it - `Test-Connection` has `IPv4` and `IPv6` switches. It might be useful for `Test-NetConnection` to have those same parameters to allow the user to specify a particular IP Version.

**Comment by vexx32** [comment]
Test-NetConnection is not a cmdlet owned ordeveloped by the PowerShell team, and is not distributed with pwsh. If the relevant Windows team is able to and wants to add those parameters, they can do so.
