### ISSUE TITLE
Way to mix c# syntax and powershell

### ISSUE THREAD

**Issue by lakani** [PowerShell/PowerShell#17394]
### Summary of the new feature / enhancement

are we able somehow to mix the both worlds in one script file, i know that we can write cmdlet in c# , but this is not what im asking for , i'm just wondering is there is a way to to do this or not, because it may be simpler to me to write If, case, define variable and other c# syntax

**Comment by SeeminglyScience** [comment]
Yes take a look at the [Add-Type](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type?view=powershell-7.2) cmdlet.
