### ISSUE TITLE
ConvertFrom-Json not properly handling an array of arrays with one element.

### ISSUE THREAD

**Issue by GingerSnap-xx** [PowerShell/PowerShell#17398]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a string representing array of arrays with one root element that contains an array of two strings.
Create a string representing array of arrays with two root element that contains an array of two strings each.
Convert them from json. Call them $foo and $bar respectively.
Address $foo's first items first index and assert that it is equal to $bar's first item's first index.

The first index of the first index should be the whole string "abc", however it is collapsing it down to an array of strings, and yielding back the first index of the string e.g. "a"

PS Snippet:
```
$foo = ConvertFrom-Json '[["abc","def"]]'
$bar = ConvertFrom-Json '[["abc","def"],["ghi","jkl"]]'
$foo[0][0]
$bar[0][0]
$foo[0][0] -eq $bar[0][0]
$foo[0][0] -eq $bar[0][0][0]
$foo[0][0][0] -eq $bar[0][0][0]
```

### Expected behavior

```console
PS> $foo = ConvertFrom-Json '[["abc","def"]]'
>> $bar = ConvertFrom-Json '[["abc","def"],["ghi","jkl"]]'        
>> 
>> $foo[0][0]
>> $bar[0][0]
>> $foo[0][0] -eq $bar[0][0]
>> $foo[0][0] -eq $bar[0][0][0]
>> $foo[0][0][0] -eq $bar[0][0][0]
abc
abc
True
False
True
```

### Actual behavior

```console
PS> $foo = ConvertFrom-Json '[["abc","def"]]'
>> $bar = ConvertFrom-Json '[["abc","def"],["ghi","jkl"]]'        
>> $foo[0][0]
>> $bar[0][0]
>> $foo[0][0] -eq $bar[0][0]
>> $foo[0][0] -eq $bar[0][0][0]
>> $foo[0][0][0] -eq $bar[0][0][0]
a
abc
False
True
True
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals
Image showing behavior in Firefox console behaving as expected just for comparison.
![image](https://user-images.githubusercontent.com/1896889/169589120-3caa3e0a-29bc-4c81-be92-1332bcc28538.png)

**Comment by jhoneill** [comment]
This is not specific to `convertFrom-Json`. PowerShell has a somewhat eccentric, but long established behaviour . 
```
PS> $x = @(@(@("ABC","DEF")))
PS> $x.count
2 
```

You might think `$x` would have one member, which has one member which has two members, but the inner members get promoted.   
```
PS>  $y = @(@(@("ABC","DEF","GHI")),$null)
PS>  $y.count
2

PS>  $y[0].count
3
```
Adding a null to the topmost array keeps it as an array, but the next levels have done a similar promotion. 

And just when you think "OK so one member arrays aren't treated as arrays at all then?" 
```
PS<  $z = @(123)
PS>  $z.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```

Unless you convert it to a Boolean - many items are always true, even if each is false, a single converts to Boolean as if it wasn't in an array.
```
PS>  $z -as [boolean]
True

PS>  $z = @(0)
PS>  $z -as [boolean]
False

PS>  $z = @(0,0)
PS>  $z -as [boolean]
True
```

"Fixing" this quirk would introduce subtle bugs into existing scripts.
