### ISSUE TITLE
Provide a way to install/update the package within terminal

### ISSUE THREAD

**Issue by TisnKu** [PowerShell/PowerShell#17408]
### Summary of the new feature / enhancement

From time to time, I get the message when I open terminal. I would need to open github release page, find the matched version and install an MSI. The process is super inconvenient.
![image](https://user-images.githubusercontent.com/10512841/169763022-0f8ee7c9-663b-479d-93a0-d6fda6e783a0.png)

Really appreciate it if I can install/update the package within terminal directly. Maybe we can add a command in the update message to inform user how to update PSCore within terminal.

**Comment by jhoneill** [comment]
https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1  will do the job. 
 I think there's a case to include it with the PowerShell installation.  Probably time to page @doctordns  because I know this is something he's been taking an interest in, and there multiple variations on the "this message isn't helpful" theme.

**Comment by dwtaber** [comment]
> ```
> iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI" 
> ```

It would be convenient to have this as a built-in function.  Or for more flexibility, maybe this:
```powershell
 iex "& { $(irm https://aka.ms/install-powershell.ps1) } $args"
```

**Comment by daxian-dbw** [comment]
You can enable Windows Update when installing the MSI package, and then pwsh will be automatically updated within 2 weeks of a new release.

**Comment by TisnKu** [comment]
Thanks @jhoneill ! Love the solution. And I agree with @dwtaber to have it as built-in function.

@daxian-dbw Do you mean this option in windows update settings?
![image](https://user-images.githubusercontent.com/10512841/170432408-e5b02230-9c21-40d9-88bb-3099022f0cd8.png)

**Comment by doctordns** [comment]
yes - I have long been a fan of doing rather better than just saying "there's an update'''". 

IF the team wanted to ship ``install-powershell.ps1`` as part of the installation, that would solve my problem (well, that and updating the message to say "run install-powershell to install newest version".

Should I raise another issue to get this idea debated and discussed?

**Comment by jhoneill** [comment]
@doctordns  Not sure what the best way is but if you've seen this https://github.com/PowerShell/PowerShell-RFC/pull/324/files 
Jason is trying to get an "install current PowerShell" included with **Windows PowerShell 5** to get round the "Windows life > .net life" issue which prevents PowerShell 7 going in the box with windows and sends people round the houses to get it. 

That proposal is trying to avoid scope creep but the same command should be runnable in any version of PowerShell and get the latest.

**Comment by doctordns** [comment]
Indeed - I have added some comments. I am not sure we need a NEW command - the install-powershell.ps1 script handles all the key scenarios. Admittedly no support for installation from the store - but that is probably not relevant as there is no app store on Server.

My personal preference is an `Install-PowerShell.,ps1` shipped inside BOTH WIndows PowerShell and PowerShell 7. Those updated versions should also have an updated message to run this new command. That woudl handle both the "I just have 5 and want 7" and the "I have 7, but need an update faster than Windows Update can provide" scenairos.

**Comment by jhoneill** [comment]
@doctordns  best if the substantive comments are on the RFC, but I agree - if the existing script went into PS7, and a future windows update dropped it into PS5 (and possibly older OSes with PS4)  that would do >90% of what's needed.

**Comment by daxian-dbw** [comment]
@TisnKu It's 2 checkboxes when running the MSI installer. Once you check them and install, it will be automatically updated as long as your Windows Update is on.

![image](https://user-images.githubusercontent.com/127450/170545809-ad892e12-707c-4183-8a9e-dc5b02159780.png)

**Comment by doctordns** [comment]
Does install-powershell.ps1 script support those two options so we can do a silent install and specify MU updating?
