### ISSUE TITLE
{@{}}.Invoke() returns unexpected result

### ISSUE THREAD

**Issue by DoPeRaSo** [PowerShell/PowerShell#17436]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The result from invoked scriptblock behaves different when the return type is [Hashtable] and the call is made using [ScriptBlock]:Invoke()

Invoke-ScriptBlock leads to expected results.

### Expected behavior

```console
PS> {@{}}.Invoke().Count
0
PS> (Invoke-Command -ScriptBlock {@{}}).Count
0
```

### Actual behavior

```console
PS> {@{}}.Invoke().Count
1
PS> (Invoke-Command -ScriptBlock {@{}}).Count
0
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Linux 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
```

**Comment by vexx32** [comment]
Yep. The method signature for `Invoke()` is [Collection<PSObject>[(https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.scriptblock.invoke?view=powershellsdk-7.0.0).

Thus, when you call `Count` on the resulting collection you get `1`, because there is one item in the collection.

**Comment by dwtaber** [comment]
> Thus, when you call `Count` on the resulting collection you get `1`, because there is one item in the collection.

That was my first thought, but `Invoke()` doesn't behave this way for all collections.

```powershell
PS> {@()}.Invoke().Count
0

PS> {[System.Collections.Generic.List[string]]::new()}.Invoke().Count
0

PS> {[System.Collections.Generic.Dictionary[[string],[string]]]::new()}.Invoke().Count
1
```
