### ISSUE TITLE
Casting method group to delegate fails when instance is PSObject

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#17433]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For **every** object, this is true:
```PowerShell
$InputObject.ToString -as [Func[String]]
```

But if I put that code in a function:
```PowerShell
filter ConvertTo-String {
    [CmdletBinding()]
    param([Parameter(ValueFromPipeline)]$InputObject)
    if ($InputObject.ToString -as [Func[String]]) {
        $PSStyle.Foreground.Yellow + $InputObject.ToString()
    }
}
```

It's literally **never** true.

I had to add this:

```PowerShell
    elseif ($InputObject.psobject.BaseObject.ToString -as [Func[String]]) {
        $PSStyle.Foreground.Cyan + $InputObject.ToString()
    }
```

The weird thing is that `$InputObject.ToString.GetType() -eq $InputObject.psobject.BaseObject.ToString.GetType()` so I don't know why one is castable and the other is not.

For what it's worth, my original goal was to write some "duck typing" where I check for "ToPsMetadata" and "FromPsMetadata" and assume the object implements `IPSMetadataSerializable`:

```csharp
public interface IPsMetadataSerializable {
    string ToPsMetadata();
    void FromPsMetadata(string Metadata);
}
```

### Expected behavior

```console
`$Object.ToString -as [Func[String]]` should always return the delegate
```

### Actual behavior

```console
If the `$Object` is a PSObject, the PSMethodInfo can't be cast to the delegate
```

### Environment data

```powershell
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Basically when `PSGetMemberBinder` calls `PSGetMemberBinder.CloneMemberInfo` it's not unwrapping psobjects. So the instance type "doesn't match" when creating the delegate with `MethodInfo.CreateDelegate`

Binder disassembly for when wrapped in a pso:

![image](https://user-images.githubusercontent.com/24977523/170174942-1a1bdf0c-9f65-4ded-a803-3a581e64b9a5.png)

Binder disassembly for when *not* wrapped in a pso:

![image](https://user-images.githubusercontent.com/24977523/170174981-65c9243c-eb30-45ee-bad4-f0ec3565176c.png)

Notably, the former does not unwrap `self` (what I named the instance var) and just passes it as is. It should either unwrap, or take the `instance` field from the source object.
