### ISSUE TITLE
Documentation disagreement. Scopes. 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#17459]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In 7.2.4 and 7.3.0-Preview-4 I see the following for `get-help new-variable -Parameter scope`
```
-Scope <System.String>
    Specifies the scope of the new variable. The acceptable values for this parameter are:

    - `Global` - Variables created in the global scope are accessible everywhere in a PowerShell process. 
    - `Local` - The local scope refers to the current scope, this can be any scope depending on the context. 
    - `Script` - Variables created in the script scope are accessible only within the script file or module they are created in. 
    - `Private` - Variables created in the private scope cannot be accessed outside the scope they exist  in. 
```
(Although the markdown bullet points are not processed correctly) 
According to this private **IS** a scope.  

However, creating a variable with `-Scope Private` is not the same as `-Visibility Private` or `-Option Private`, and variables **can** be seen in other scopes 
```
PS>  new-variable -Name one -Value "111" -Scope Private -Force
PS>  $one
111
PS>  & {$one}  # NOT private
111 

PS>  new-variable -Name two -Value "222" -Visibility Private
PS>  $two  # Private from ourselves 
PermissionDenied: Cannot access the variable '$two' because it is a private variable.
PS>  & {$two} # but visible in the child scope
222

PS>  new-variable -Name three -Value "333" -Option Private
PS>  $three
333
PS>  & {$three}   # Not visible in the child scope

PS>
```

This behaviour mirrors what `about_scope` says 
```
  [!NOTE] PRIVATE is not a scope. It is an option that changes the  visibility of an item outside of the scope where the item is defined.
```

`Private` being an _option_, not a _scope_ and distinct from the _visibility_ setting, appears to be correct and the cmdlet help appears to be wrong.  

### Expected behavior

```console
Cmdlet help agrees with about and matches behaviour
```

### Actual behavior

```console
It doesn't
```

### Error details

```console
n/a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.4
PSEdition                      Core
GitCommitId                    7.3.0-preview.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Thanks for spotting this @jhoneill! 

@sdwheeler `about_scope` is the better source of truth correct? and also where would we make this change to the `New-Variable` documentation?

**Comment by sdwheeler** [comment]
Note the behavior:

```powershell
PS> Get-Variable one, two, three | fl *

Name        : one
Description :
Value       : 111
Visibility  : Public
Module      :
ModuleName  :
Options     : None
Attributes  : {}

Get-Variable: Cannot access the variable '$two' because it is a private variable.
Name        : three
Description :
Value       : 333
Visibility  : Public
Module      :
ModuleName  :
Options     : Private
Attributes  : {}
```

**Comment by sdwheeler** [comment]
So it seems that running `New-Variable varname -Scope Private` does nothing. Is this intentional code behavior?

**Comment by StevenBucher98** [comment]
Opened issue in Docs: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8908

**Comment by StevenBucher98** [comment]
> In other words, it's private to the specific scope that created it, and normal variable discovery can't find it. But if you target the correct scope value explicitly, you can find it from any other scope.

So would it make more sense to clarify that `Private` is limited its in discovery? Within the `Get-Help New-Variable` documentation. I'd imagine changing the name from Private to something else would not be recommended 😄  i.e somethink like:
`    - Private - Variables created in the private scope can only be accessed if specifically targetted in different scopes and cannot normally be accessed outside the scope it was created.`

**Comment by vexx32** [comment]
There's still confusion between the Private option on Set-Variable, which behaves that way to the private scope itself, which is (currently) a valid option on New-Variable which seemingly does nothing. Despite `$private:` being a valid scope qualifier for normal variables which apparently sets the Private _option_ but does nothing in regards to scope.

And then the Private -Visibility option which does something else entirely. It's all a bit of a tangled web here.

**Comment by jhoneill** [comment]
> There's still confusion between the Private option on Set-Variable, which behaves that way to the private scope itself, which is (currently) a valid option on New-Variable which seemingly does nothing.


AIUI - and what `about_scope`  seems to say  re private is  - although `$private:`  looks like a scope qualifier, it isn't..    `$Anything:Something`  seems to treat "anything" as a PS Drive _except for the special cases_ `Global`, `Script`, `Local` and `Private`. `$C:SomeName` gets the contents of a file with no extension in the current directory of C:  - if one exists. `$0:someName` returns nothing unless you create a drive "0" and the file exists in the current directory - it can't be used to access scope 0, 1 , 2... that needs to go through `*-Variable` .  Of the four special cases 3 are scopes and one applies a label. I guess it is a bit like `$env:` in some ways that's like a scope, but really it's a drive. 

And the "Seemingly doing nothing" is plain weird. 

```
>  new-variable -Name one -Value "222" -scope Two
New-Variable: Cannot process argument because the value of parameter "Scope" is not valid. Valid values are "Global", "Local", or "Script",
```

`New-Variable` _accepts_ `private` in the scope parameter, but if you enter something random, it gives a list of valid scopes, which excludes `private`

> And then the Private -Visibility option which does something else entirely. It's all a bit of a tangled web here.

Indeed it is :-)

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine 
we definitely agree that the behaviors could be more completely described, and we believe that there may a couple of issues discovered during that process. Currently, we think the proper approach is to make sure the documentation is correct and then decide what steps we should take with regard to behavior.

**Comment by sdwheeler** [comment]
The docs were updated in https://github.com/MicrosoftDocs/PowerShell-Docs/pull/8926. Let me know what else needs to change in the docs.
