### ISSUE TITLE
New verb(s) for "Prepare" / "Do what was prepared" 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#17450]
### Summary of the new feature / enhancement

I can feel people saying "oh no, not another verb request" But bear with me. 

I've been playing with creating crescendo commands for terraform. 
Terraform has the concepts of     
**plan**  examine the desired state and current actual state and decide what needs to be done. 
**apply**  'Make it so' either by executing steps which were (optionally) saved at by a plan operation or planning steps on the fly. 

 This can be shoehorned into PowerShell verbs by making "plan" a noun instead of verb, so we can "create a New plan," instead of "planning a deployment". And we can "Deploy a configuration" (from a plan, or not).   
In fact doing what was prepared seems to fit existing verbs - if the authors of terraform had chosen, deploy,  import, merge,  publish, push, submit,  or update instead of "apply" no-one would have noticed, but there's nothing  to replace "plan"

There are other cases in data transformation, where there is a preliminary phase before data is imported/exported/saved/converted.  "Prepare" seems the most logical verb to me, right now, but there may be another which is just as suitable. 
 
 
 

### Proposed technical implementation details (optional)

Add a verb to the approved list.

**Comment by SeeminglyScience** [comment]
> This can be shoehorned into PowerShell verbs by making "plan" a noun instead of verb, so we can "create a New plan," instead of "planning a deployment". And we can "Deploy a configuration" (from a plan, or not).

Can you elaborate a bit on why the verbs `New` and `Deploy` don't fit?

> In fact doing what was prepared seems to fit existing verbs - if the authors of terraform had chosen, deploy, import, merge, publish, push, submit, or update instead of "apply" no-one would have noticed, but there's nothing to replace "plan"

For folks not familiar with terraform (including myself) it may be helpful to describe in greater detail the scenario you're referring to and it's impact on this discussion.

**Comment by jhoneill** [comment]
@SeeminglyScience 

In terraform there is command `plan`  which is "compare desired state with actual state and determine steps to carry out" - this can optionally output a file which holds those steps. Whether you output the file or not, it shows what it is going to do - this output can be JSON and doing stuff with crescendo I can turn that into something PowerShelly.  It's a _preview_ but not a `-WhatIf`  

I can bend the meaning of it to "Create a new plan file" , but it if not file is specified it isn't creating a new anything so right now I _do_ have `New-TerraformPlan [-Outfile <path>]` but if don't supply a parameter it's not  creating something new, so it feels wrong.

If I create the plan file then the next phase _does_ fit into `deploy` -  what terraform calls `apply` is either "run the steps in the plan file", or "plan the steps and immediately apply them"  in the terraform case , and I think more generally, the "Do the thing you prepared" fits into existing verbs. 

@doctordns  - terraform comes from a whole other organization, they could have picked the imperative form of other verbs  for their commands. "Apply" could be replaced with others, but there isn't a ready alternative for "plan". It would need the product to be redesigned without that function, not just giving it another name.   
I'm on record as saying Microsoft should fire anyone who tries to introduce a new, non-PowerShell command-line tool for Windows, so you can guess my take on winget from there.

**Comment by kilasuit** [comment]
Test IMO is the closest current verb to what you want here and should cover your needs

**Comment by jhoneill** [comment]
@kilasuit  there is a `validate` so, really, test is taken. And I did think about using that, but it seems wrong for creating output which then is used for something else.

**Comment by kilasuit** [comment]
@jhoneill we don't have validate as an approved verb in PowerShell today - is this perhaps in terraform?

**Comment by jhoneill** [comment]
@kilasuit  Yes. sorry validate is a terraform command, which translates neatly to being Test in Powershell



> > I can bend the meaning of it to "Create a new plan file" , but it if not file is specified it isn't creating a new anything so right now I _do_ have `New-TerraformPlan [-Outfile <path>]` but if don't supply a parameter it's not creating something new, so it feels wrong.
> 
> `New` does not have to refer to a file, like `New-Object` for instance. If you scroll through `Get-Command -Verb New` most of them do not create files.
> 
It doesn't need to create a _file_, but new means _something_ exists afterwards which didn't exist before, with `terraform plan` sometimes a new file exists afterwards and sometimes nothing new exists. I'm using new but it feels wrong.   

> > If I create the plan file then the next phase _does_ fit into `deploy` - what terraform calls `apply` is either "run the steps in the plan file", or "plan the steps and immediately apply them" in the terraform case , and I think more generally, the "Do the thing you prepared" fits into existing verbs.
> 
> I know `Invoke` gets overused, but it seems to fit very well here.

The problem with crescendo is it ends up doing things like ["Invoke-ls"](https://github.com/PowerShell/Crescendo/blob/master/Microsoft.PowerShell.Crescendo/Samples/ls.crescendo.json) and tbh, I'm trying not to just turn _every_ terraform command into `Invoke-TerraformThis` and `Invoke-TerraformThat`, there may be cases where that is unavoidable . `Invoke-PrerequisteStepsForTerrraformDeployment`  is a bit ugly. "Prepare-TFConfig" and "Deploy-TFConfig" would be natural.

**Comment by ThomasNieto** [comment]
After looking at the documentation for Terraform (I have not used Terraform before). The `Build` verb could be used in place for plan. According to the documentation plan takes a set of input (configuration) and compares that to the current state of the system and builds a set of actions to get it into the desired state. Build also fits in nicely with the build and deploy model.

If a user runs `Build-TerraformPlan` and no changes are required it could return null as it would be in the desired state. If the system is out of compliance it could return an object of all the proposed changes. That could then be piped to `Deploy-TerraformPlan`. The user could also send the object/output to a file for later use.

**Comment by jhoneill** [comment]
@ThomasNieto Yes, that works. Deploy makes sense, and Build as the step before deploy also makes sense, and the process is similar to a building software.  I still think Prepare is a good idea, but I may well use build for now. Thanks!

**Comment by rkeithhill** [comment]
While I super appreciate that we have common verbs for operations like `Remove` instead of `del`, `delete`, `erase`, etc.  I've also come to believe that there are going to be non-approved verbs and that's OK.  Don't get me wrong, we want folks to use approved verbs **when** there's a good fit.  But there isn't always a good fit.  There are so many problem domains out there where those users need verbs that better map to their problem domain instead of a bad force fit to approved verbs.  Either that or PowerShell starts accepting more verbs, but that seems like a never-ending issue.  Just my 2 cents.

**Comment by vexx32** [comment]
Eh in my opinion if a verb offers something that is truly not represented in the existing list of approved verbs, it's reasonable to look to add it in. If it doesn't add anything that isn't already covered by another approved verb, then in general there's no reason not to use that other verb. 🤷

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine discussed this and didn't see the value in adding this new verb.

**Comment by jhoneill** [comment]
@rkeithhill  - yeah I became a fan of not using 101 synonyms for the same verb pretty early on. Easy to get wedded to a specific one (we still "Format" volumes which is the wrong sense of the word) 
 `Get-Verb` gives 100 verbs and if the one I think it _should be_ isn't one of those or a synonym for one which flips easily - my first thought is that I'm describing the task poorly. Something for "do the things that get this ready" is a missing one. Sure I _can_ use "Prepare-Configuration"  and then "Complete-Configuration"  but I think adding verbs is bad.

For my case there are multiple alternatives to Complete, I could  "Build-Environment", "Send-Configuation", "Deploy-Configuration", or "submit-configuration",  "Push-Configuration"  Or "Publish-Configuration"  Possibly "enable" it, "Import" it. or simply "use" it. That's 10 verbs for using what I've prepared but doing the prep...?

@JamesWTruher   Insufficient demand, or served well enough with existing verbs ?

**Comment by Pablo1q** [comment]
Yes. Its very bad because i have been on judge with my ex Wife. And I don't
feel good for go outside. And

**Comment by Pablo1q** [comment]
Well. Work was good a few days ago!
Well sometimes I don't feel confortable for go outside because i remember  the court and the judge and I don't feel good.  Anyway posible to fix the work? Its slow
