### ISSUE TITLE
Add command line argument to specify $Profile location

### ISSUE THREAD

**Issue by dartacao** [PowerShell/PowerShell#17462]
### Summary of the new feature / enhancement

Is it possible to change the location of the profile.ps1 file with a command argument? In my view, a -p [path] argument would make configuring powershell much much easier.

**Comment by MatejKafka** [comment]
Related: #13815

**Comment by jhoneill** [comment]
As a workround you can  use
```
pwsh -noprofile -noexit -file .\profile.ps1 
```

The problem with overriding the profile is which one are you replacing, because at start-up PowerShell processes FOUR
all-users all-hosts
current-user all-hosts
all-users current-host
current-user current-host.

**Comment by jhoneill** [comment]
get-help about_profile says all of them and gives and order of precedence. I must admit I only use one of them, but my understand has always been that you can have your all-hosts profile do common things, and then have extras for ISE / VSCode/ Normal-host

**Comment by daxian-dbw** [comment]
Decline the enhancement request given the answers from @jhoneill
