### ISSUE TITLE
PowerShell crash with "The path is not in legal form" error when launched without temp path access

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1746]
Build PSRPOverSSH prototype code.
$s = New-PSSession -HostName "paulhig-1" -UserName "PaulTest" -KeyPath "C:\Program Files\OpenSSH-Win32\Debug\id_rsa"

Result:
Occassionally you get a crashing error from launching PowerShell:
"The path is not in legal form.".
Expected:
No error

Paul Higinbotham (POWERSHELL):
I ran into this while working on the PSRP over SSH prototype.  This happens when PowerShell is launched by the sshd process under the test "User" account that has no temp directory.  The error is thrown in the GetAppLockerPolicy() method when running the managed method IO.Path.GetTempPath().

This looks like a bug in the .Net class since the error only occurs randomly.  The fix is to add an ArgumentException catch block and return the correct policy result when no temp directory is available.

**Comment by tanin47** [comment]
I have this problem as well. It only happens maybe 1 out of 5 times.

I am ssh'ing into a remote windows machine with OpenSSH-Win32 (5_30_2016) and powershell (version 5, I believe). Here's the error message:

```
> powershell -command dir
debug2: channel 0: rcvd ext data 72
debug2: channel 0: rcvd ext data 34
The shell cannot be started. A failure occurred during initialization:
The path is not of a legal form.
```

I'll try ensure that the user has temp directory. If you happen to know how to ensure it through a command line, please let me know. Thanks.

**Comment by tanin47** [comment]
Setting the TMP env seems to solve the problem. Here's the command:

ssh .... "set TMP=%USERPROFILE%\appdata\local\temp\ && powershell -command $env:tmp".

I ran this command like 20 times and encountered no error.

**Comment by PaulHigin** [comment]
This was fixed as part of PSRP over SSH changes.
