### ISSUE TITLE
The parameter @scope:registry are not executed correctly

### ISSUE THREAD

**Issue by jackyking-cn** [PowerShell/PowerShell#17466]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

execut `npm config set @scope:registry https://npmmirror.com/`

### Expected behavior

```console
`@scope:registry=https://npmmirror.com/` in `>.npmrc`
```

### Actual behavior

```console
`https://npmmirror.com/=` in `>.npmrc`
```

### Error details

```console
nothing
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/1309499/171323395-468dd665-2c3c-457b-a31c-900bd033f4ef.png)

Other details: https://github.com/microsoft/terminal/issues/13188

**Comment by rkeithhill** [comment]
`@` is a special character in PowerShell used in several scenarios such as hashtables `@{}`, to ensure output is an array `@(1)` and argument splitting `@npmArgs`.  In this case, PowerShell thinks you're trying to splat which you can see by looking at the AST:
```powershell
{npm config set @scope:registry https://npmmirror.com/}.Ast.EndBlock.Statements.PipelineElements.CommandElements
```
If you "escape" the `@` char with a back-tick, it should work as intended:
```powershell
npm config set `@scope:registry https://npmmirror.com/
```
You could also quote that argument:
```powershell
npm config set '@scope:registry' https://npmmirror.com/
```
Or you could use PowerShell's stop parsing operator to "dumb down" PowerShell command line parsing:
```powershell
npm config set --% @scope:registry https://npmmirror.com/
```

**Comment by rkeithhill** [comment]
I believe `@my-scope:registry` works because when parsing, the syntax for a scoped variable reference is `@<scopename>:<variablename>` where a `-` is not allowed in a scope name.  Therefore, the parser determines the `@my-scope:registry` can't be a splatted variable. This is also what the AST indicates.

![image](https://user-images.githubusercontent.com/5177512/171553295-fab18f79-91ad-4966-b0b1-9fa84003c828.png)

**Comment by jackyking-cn** [comment]
Sorry，my english is poor. 
You mean `my-scope` is not allowed a scope name?

This is scope docs, https://docs.npmjs.com/cli/v7/using-npm/scope :
> A scope follows the usual rules for package names (URL-safe characters, no leading dots or underscores). 

Anyway, It's a little trouble, can be acceptable.
Thank you very much.
