### ISSUE TITLE
Major startup time regression between 7.3.0-preview.2 and preview.3 on Windows 10

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#17465]
### Steps to reproduce

These steps work on my machine (Windows 10 21H2), but probably won't be reproducible universally, otherwise this would be already reported. I'll be happy to give more information about my setup if necessary.

1. Install PowerShell v7.3.0-preview.2
2. Run `hyperfine 'pwsh -noprofile -nologo -c exit'` (or use any other command to measure command run time)
3. Install PowerShell v7.3.0-preview.3
4. Re-run step 2

### Expected behavior

Similar startup time for both versions.

### Actual behavior

PowerShell v7.3.0-preview.2
```console
$> hyperfine 'pwsh -noprofile -nologo -c exit' --runs 30
Benchmark 1: pwsh -noprofile -nologo -c exit
  Time (mean ± σ):     281.3 ms ±  18.1 ms    [User: 2.0 ms, System: 6.2 ms]
  Range (min … max):   258.0 ms … 334.7 ms    30 runs
```

PowerShell v7.3.0-preview.3
```console
$> hyperfine 'pwsh -noprofile -nologo -c exit' --runs 30
Benchmark 1: pwsh -noprofile -nologo -c exit
  Time (mean ± σ):     567.4 ms ±  37.8 ms    [User: 3.8 ms, System: 6.2 ms]
  Range (min … max):   524.0 ms … 697.8 ms    30 runs
```
For -preview.4, the startup time is similar to -preview.3, both almost 2 times slower than -preview.2.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.2
PSEdition                      Core
GitCommitId                    7.3.0-preview.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MatejKafka** [comment]
Update: I can also reproduce this regression in a Windows 11 VM on the same machine, so it's not specific to Windows 10. I don't think it's relevant, but the machine is a Dell Latitude 7490 laptop (8th gen i5 Intel, 16 GB RAM, NVMe).

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3
OS                             Microsoft Windows 10.0.22610
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MatejKafka** [comment]
Hyperfine measurements with more versions: [pwsh-benchmarks.zip](https://github.com/PowerShell/PowerShell/files/10676913/pwsh-benchmarks.zip)
All of the measurements were done by running `hyperfine 'pwsh -noprofile -nologo -c exit' --runs 100 --export-json ([string]$PSVersionTable.PSVersion + ".json")` inside the respective version of pwsh.

It seems that the performance regression was almost fixed in further updates, but the current 7.4.0-preview.1 is still ~20ms slower than 7.3.0-preview.2 to start up.

**Comment by iSazonov** [comment]
Thanks! We will move to .Net 8 Preview soon. This will open new capabilities to improve pwsh performance.

**Comment by MatejKafka** [comment]
Seems fixed over time.
