### ISSUE TITLE
Allow a simple method that allows capturing all output (including verbose) to a file but excluding verbose on console

### ISSUE THREAD

**Issue by o-o00o-o** [PowerShell/PowerShell#17482]
### Summary of the new feature / enhancement

As a Powershell Tool designer I want a command like Start/Stop-Transcript that will capture verbose output but not display it to the console So that the user of the tool gets an easy to consume minimal console experience but there is a detailed log available in case of problems with tools that run for longer than 10 mins or if the issue is not easily reproducable.

Today it seems that we either need to roll our own centralised complex logging routines or highly decorated contents of our scripts using redirection operators (something like ```Tee-Object 'filename' 4>$null```) but this does not work consistently in many scenario's

### example

``` powershell
function Invoke-MyTool {
Start-DetailedLog 'myfile.log'
Write-Host 'Hello World'
Write-Verbose 'Hello underworld!
Stop-DetailedLog 'myfile.log'
}

Invoke-MyTool
# or perhaps 
# Invoke-MyTool -Verbose 
# either would be acceptable as long as the behaviour was defined
```

Screen output would be
```
Hello World
```

myfile.log would be 
```
Hello World
Hello underworld!
```

It would be nice to be able to have timestamps on each line in the log also

If this is possible to incorporate this functionality in to Start-Transcript then that would be great

**Comment by o-o00o-o** [comment]
Some of the issues related to other people trying to solve this issue
https://stackoverflow.com/questions/11973775/powershell-get-output-from-receive-job
https://github.com/PowerShell/PowerShell/issues/5848

**Comment by kasini3000** [comment]
Receive-Job -InstanceId $private:job2.InstanceID *>&1,then tee-object
If you use ps-remote, welcome to use my packaged powershell framework.

It uses multi-process, multi-threading, runs commands remotely on win-linux node pc, gets results from standard output, and writes to sqlite database. Support time period, IP address of the node pc, query (table, list).

----


[kasini3000](https://gitee.com/chuanjiao10/kasini3000) site mirror:(https://github.com/kasini3000/kasini3000)   
win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline) 
Open source, free, cross-platform 
English manual: https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

[kasini3000_agent_linux](https://gitee.com/chuanjiao10/kasini3000_agent_linux) Shell script,one click install powershell on linux,modify sshd_config for PsRemote.

**Comment by o-o00o-o** [comment]
@kasini3000 I'm sorry but I don't understand how your suggestion helps to fulfil this request

Receive-Job doesn't send seem to stdout from the job through the pipeline, it seems to flush the current stdout in the job through a different method when it is called. I think #5848 and #9585 talks about this

If I use *>&1 then I don't believe there is any way to then remove the verbose as it is all sent to the success stream, so cannot fulfil the requirement

Please provide a working example if you think it can

**Comment by o-o00o-o** [comment]
@SeeminglyScience Thanks for the illustrated suggestion. I wasn't aware of the internal pipe behaviour here. I will experiment with that.

I suppose that this necessitates some kind of wrapper function/script to save having to decorate every line of each function with this pipe to Tee-OutputOnly or is there a more elegant way of solving that. I suppose that the Transcript method would have this advantage.

**Comment by SeeminglyScience** [comment]
> I suppose that this necessitates some kind of wrapper function/script to save having to decorate every line of each function with this pipe to Tee-OutputOnly or is there a more elegant way of solving that? I guessed that the Transcript method would have the advantage of not needing this wrapper

I probably should have commented there, but that's very explicitly only a problem with verbose and warning. The manner in which they're written to the screen isn't controlled by formatting like everything else, but instead based on an internal property on the `PSObject` wrapping it. Everything else will be written as it's typically formatted, just those two records need a little bit of help.

**Comment by o-o00o-o** [comment]
After briefly testing it, I don't believe that it works with Receive-Job. It seems that Receive-Job doesn't pass output through the pipeline, for some reason it bypasses it and flushes outputs directly to stdout not via the pipeline. Showing with just Tee-Object

``` powershell
$myjob = Start-Job {Write-Host 'blah'; Write-Verbose 'blah verby'; Write-Warning 'im warning you'}
$logpath = 'blah.txt'
Receive-Job $myjob | Tee-Object -filePath $logPath
```

$logPath file doesn't exist

but if I run

```
'blah' | Tee-Object -filePath $logPath
```

Then $logPath contains ```blah``` as expected

I think the same thing is discussed [here](https://stackoverflow.com/a/11991815/7815011) - and this is where I got the idea of extending Start-Transcript as that was the preferred solution there after a number of different approaches

**Comment by SeeminglyScience** [comment]
@o-o00o-o you still need the merging redirection, so `Receive-Job $myJob *>&1 | Tee-Object etc`

**Comment by o-o00o-o** [comment]
Thanks but sorry I still can't get it to work. 

I only get the Write-Host into the file using the Tee-OutputOnly and still everything written to the screen. I corrected a typo but otherwise it is the function you posted

What am I missing? Full example

``` powershell
function Tee-OutputOnly {
     [CmdletBinding(PositionalBinding = $false)]
     param(
         [Parameter(ValueFromPipeline)]
         [psobject] $InputObject,

         [Parameter(Position = 0)]
         [string] $FilePath,

         [Parameter()]
         [switch] $Append
     )
     begin {
         $filePipe = { Out-File @PSBoundParameters }.GetSteppablePipeline($MyInvocation.CommandOrigin)
         $filePipe.Begin($PSCmdlet)
     }
     process {
         if ($InputObject -is [System.Management.Automation.VerboseRecord]) {
             $filePipe.Process("VERBOSE: $PSItem")
             Write-Verbose $InputObject.Message
             return
         }

         if ($InputObject -is [System.Management.Automation.WarningRecord]) {
             $filePipe.Process("WARNING: $PSItem")
             Write-Warning $InputObject.Message
             return
         }

         $filePipe.Process($PSItem)
         if ($InputObject -is [System.Management.Automation.ErrorRecord]) {
             $PSCmdlet.WriteError($InputObject)
             return
         }

         if ($InputObject -is [System.Management.Automation.InformationRecord]) {
             $PSCmdlet.WriteInformation($InputObject)
             return
         }

         return $InputObject
     }
     end {
         $filePipe.End()
     }
 }
 
$myjob = Start-Job {
    Write-Host 'blah'
    Write-Verbose 'blah verby' -verbose
    Write-Warning 'im warning you'
}
$logpath = 'blah.txt'
```

then run
``` powershell
Receive-Job $myjob *>&1 | Tee-OutputOnly -FilePath $logpath
```
screen has

```
blah
VERBOSE: blah verby
WARNING: im warning you
```

but file has just 

```
blah
```

I may be missing something in the script but I would want everything written to the file but everything but verbose sent to the screen

**Comment by SeeminglyScience** [comment]
Ah yeah that one definitely acts differently. @PaulHigin might have some ideas

**Comment by PaulHigin** [comment]
@WG-Security
Working security group feels this is not a security issue since it only involves existing PowerShell data streams, and the issue appears to be a problem with the Receive-Job cmdlet.
