### ISSUE TITLE
Invoke-Webrequest hangs on query to certain websites 

### ISSUE THREAD

**Issue by Dods80** [PowerShell/PowerShell#17499]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have tested from a fresh install of Powershell 7.2.4 over multiple devices and different network locations.
when you execute for example:

(invoke-webrequest -Uri 'https://www.adidas.co.uk' -UseBasicParsing).Content

The command never times out or errors.
When executing the same command from a powerhsell 5 session from the same host it executes straight away.

### Expected behavior

```console
PS>(invoke-webrequest -Uri 'https://www.adidas.co.uk' -UseBasicParsing).Content
<!DOCTYPE html><html lang="en" class="theme-adidas" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#" data-reactroot=""><head><link rel="stylesheet" href="https://www.adidas.co.uk/glass/pkgs/reset.css"/><link rel="stylesheet" href="https://www.adidas.co.uk/static/theme/css/v1.22.7/foundation-adidas.css"/><link data-chunk="app" rel="stylesheet" href="/glass/react/ac74c8e/adidas/modern/glass-vendor-adidas.css"/><link data-chunk="app" rel="stylesheet" href="/glass/react/ac74c8e/adidas/modern/glass-app-adidas.css"/><link data-chunk="lp" rel="stylesheet" href="/glass/react/ac74c8e/adidas/modern/glass-7205-adidas.css"/><link data-chunk="lp" rel="stylesheet" href="/glass/react/ac74c8e/adidas/modern/glass-4925-adidas.css"/><link data-chunk="lp" rel="stylesheet" href="/glass/react/ac74c8e/adidas/modern/glass-9624-adidas.css"/><link data-chunk="lp" rel="stylesheet" href="/glass/react/ac74c8e/adidas/modern/glass-lp-adidas.css"/><title data-rh="true">adidas Official Website UK | Sportswear</t> etc......
```

### Actual behavior

```console
PS>(invoke-webrequest -Uri 'https://www.adidas.co.uk' -UseBasicParsing).Content
_ (Just hangs until you break out)
```

### Environment data

```powershell
PS> $PSVersiontable
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vexx32** [comment]
I get a response back with just a `-Headers @{ Accept = 'text/html' }` and nothing else.

I'm curious though that the OP's Expected Behaviour is a JSON response blob. I don't know why that would be being returned, even in 5.1. I can only get a normal HTML response back from this web address, as I would expect since it appears to be a website index page.

**Comment by jhoneill** [comment]
Possibly if the accept has all those bits in it needs accept-encoding and accept-language as well.

**Comment by Dods80** [comment]
> I get a response back with just a `-Headers @{ Accept = 'text/html' }` and nothing else. I'd wager this server for some reason doesn't have a default fallback as to what kind of response to provide when no headers are present.
> 
> I'm curious though that the OP's Expected Behaviour is a JSON response blob. I don't know why that would be being returned, even in 5.1. I can only get a normal HTML response back from this web address, as I would expect since it appears to be a website index page.

Sorry I had posted the wrong expected response now corrected it to HTML.

**Comment by Dods80** [comment]
So it seems that this behaviour is expected from running in a powershell 7 environment and not to be compared to what happens in Powershell 5. @[jhoneill](https://github.com/jhoneill). Thanks for the tip on header construction by monitoring in Edge. I will now close this issue.
