### ISSUE TITLE
Add a parameter to `Out-File` and `Out-String` to bring back the previous behavior that got changed by #17455

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#17509]
For reference:
- Issue: https://github.com/PowerShell/PowerShell/issues/17452
- PR that fixed the issue: https://github.com/PowerShell/PowerShell/pull/17455

### Context summary

The previous behavior in 7.2.x is: `Out-File` and `Out-String` remove escape sequences from the passed-in strings when `$PSStyle.OutputRendering` is `Host` or `PlainText`.

There are some problems with this behavior, especially when having `Host` to be the default value for `$PSStyle.OutputRendering`. See https://github.com/PowerShell/PowerShell/pull/17455#issuecomment-1147680515 for the details of those problems.

Therefore, that behavior was changed by #17455 to be:
- when the input object is pure string, these 2 cmdlets keep the string input unchanged regardless of the `RenderingOutput` setting
- when the input object needs to have formatting views applied to it, these 2 cmdlets remove escape sequences from the formatting output strings based on the `RenderingOutput` setting, which is the same as the existing behavior.

### Recommendation from PowerShell Committee

The committee reviewed #17455 and recommended to add a new parameter to `Out-String` and `Out-File` to keep the previous behavior. Quote the comments https://github.com/PowerShell/PowerShell/pull/17455#pullrequestreview-1000516051 and https://github.com/PowerShell/PowerShell/pull/17455#issuecomment-1150521455 below:

> I think we should seriously consider adding a parameter to out-string and out-file which retains our current behavior. Perhaps a parameter `-AsPlainText` or some such will allow users to have the older behavior while we provide a safer default behavior.
>
> powershell-committee reviewed this, we would recommend adding a parameter to enable users to get back the previous behavior.
>

**Comment by daxian-dbw** [comment]
I think we should wait until there is any issue reports that a user is really depending on the previous behavior, for the following reasons:
1. IMHO, the previous behavior is more like a bug and unexpected to users. Take the following as an example, I think most users won't expect these 2 pipelines to behave differently depending on `$PSStyle.OutputRendering`, since this scenario is not about output rendering at all.
    ```
    Get-Content file-a | Set-Content file-b
    Get-Content file-a > file-b
    ```
2. Given that the previous behavior may alter the string input when `$PSStyle.OutputRendering` is `Host` or `PlainText`, a user may run into the [spoofing issue](https://github.com/PowerShell/Announcements/issues/28) without knowing when these 2 output rendering options are in use. So even if we add parameter to `Out-File` and `Out-String` to bring back the previous behavior, we probably still need to warn users to be careful using this parameter, and later on, it may become a good-practice within the community to avoid using this parameter.

3. If a user really want to remove Ansi escape sequences from strings, they can do it explicitly by using `StringDecorated` type (example below), or we can expose another cmdlet just for that. I think being explicit is better.
    ```
    Get-Content file-a | % { [System.Management.Automation.Internal.StringDecorated]::new($_).ToString("PlainText") } | Out-File file-b
    ```

**Comment by vexx32** [comment]
I'm in favour of exposing a cmdlet specifically for handling ANSI sequences in strings, that sounds like something that folks would find helpful as we continue to add them to formatting things.

**Comment by SteveL-MSFT** [comment]
@daxian-dbw the primary consideration that makes the parameter different is that it's explicitly opt-in for those cmdlets so users would be expected to understand the side-effects.  So from that perspective, documentation is sufficient and a warning is not necessary.

The Committee believes there is utility to have the previous behavior where a cmdlet (like `Select-String`) which explicitly adds VT codes (rather than go through formatting) and the user may want those removed before having something else process it as plain text.  Although you are correct that `[StringDecorated]` exposes this capability already, it's more dev centric and not discoverable compared to a switch on existing cmdlets.

**Comment by daxian-dbw** [comment]
For `Select-String`, the VT codes are added in formatting for the `MatchInfo` object. The `MatchInfo.Line` doesn't contain VT codes, and if you use `Select-String -Raw`, it output strings, without VT codes.

It's possible for a cmdlet to directly output strings with VT codes, but in that case, it's more likely the VT codes are not for decoration purpose but something the caller should consume. In contrast, it's more likely for an executable to write out VT decorated strings, where removing the VT sequences becomes interesting.

However, for both cases, I think exposing another cmdlet just for removing VT sequences is probably better, so that the operation is explicit and predictable (behavior won't change based on a global setting such as `$PSStyle.OutputRendering`).

**Comment by daxian-dbw** [comment]
The proxy function is an interesting idea. But I assume you mean to have `Out-String/File -RemoveAnsi` to always remove ANSI, regardless of what `$PSStyle.OutputRendering` is. If so, then that's not the previous behavior anymore, but is still something we can consider, I guess.

**Comment by michaeltlombardi** [comment]
@daxian-dbw should we hold off on MicrosoftDocs/PowerShell-Docs#8892 until there's clarity on this or go ahead with that issue in the meantime?

My current thought is that if this issue won't get resolved before the next release, we'll need to document that change at least temporarily in the preview docs.

CC @sdwheeler

**Comment by daxian-dbw** [comment]
@michaeltlombardi The default behavior of `Out-File` and `Out-String` is determined. If a parameter to `Out-File` and `Out-String` is decided to be needed, we only need to update the docs of `Out-String` and `Out-File`. So, for the updates to https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2, I think we can go ahead and do it.

**Comment by jhoneill** [comment]
> The proxy function is an interesting idea. But I assume you mean to have `Out-String/File -RemoveAnsi` to always remove ANSI, regardless of what `$PSStyle.OutputRendering` is. If so, then that's not the previous behavior anymore, but is still something we can consider, I guess.

I was thinking of two cases "always remove" and "conditionally-remove". I think always is more common, but if it a script has 
` <external program> |  <removal tool >` I can see a desire for it to honour the value of `outputRendering`

**Comment by mklement0** [comment]
As an aside: [`System.Management.Automation.Internal.StringDecorated`](https://learn.microsoft.com/en-US/dotnet/api/System.Management.Automation.Internal.StringDecorated) suffers from the "pubternal" affliction - a public class in an `Internal` namespace. If the intent is to facilitate the class' use by end users, there should probably be a `[stringdecorated]` type accelerator.
