### ISSUE TITLE
The settings loaded in `profile.ps1` are not applied

### ISSUE THREAD

**Issue by NightMachinery** [PowerShell/PowerShell#17502]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

I have the following file at `~/.config/powershell/profile.ps1`:

```console
###
using namespace System.Management.Automation
using namespace System.Management.Automation.Language
###
echo "profile.ps1 started"
###
Import-Module PSReadLine

Set-PSReadLineOption -EditMode Emacs
##
#: see https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/SamplePSReadLineProfile.ps1

Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

Set-PSReadLineKeyHandler -Key Alt+LeftArrow -Function BackwardWord
Set-PSReadLineKeyHandler -Key Alt+RightArrow -Function ForwardWord

# Clipboard interaction is bound by default in Windows mode, but not Emacs mode.
Set-PSReadLineKeyHandler -Key Ctrl+C -Function Copy
Set-PSReadLineKeyHandler -Key Ctrl+v -Function Paste
###
echo "profile.ps1 ended"
```

When I run `pwsh`, this profile is loaded successfully:
```
pwsh
PowerShell 7.2.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

profile.ps1 started
profile.ps1 ended
Loading personal and system profiles took 614ms.
PS /Users/evar/scripts> 
```

But the settings are not applied at all. I need to run them again manually (by copy pasting the commands) and then they work as expected.

### Screenshot

NA

### Environment data

```console
PS Version: 7.2.4
PS HostName: ConsoleHost
PSReadLine Version: 2.2.5
PSReadLine EditMode: Vi
OS: Darwin Fereidoons-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
BufferWidth: 85
BufferHeight: 21
```

### Steps to reproduce

.

### Expected behavior

I expected hotkeys such as `Ctrl+A`, `Alt+LeftArrow`, etc. to work. 

### Actual behavior

The hotkeys did not work.

**Comment by NightMachinery** [comment]
[**@vexx32**](https://github.com/vexx32) commented on [Jun 9, 2022, 2:14 AM GMT+4:30](https://github.com/PowerShell/PowerShell/issues/17502#issuecomment-1150445017 "2022-06-08T21:44:32Z - Replied by Github Reply Comments"):
> Interesting, I have a similar profile setup on my Mac and it works just fine... Out of curiosity does this work if you remove the `using  namespace` lines from the profile?

No, I actually added those to see if they helped. They didn't.

**Comment by SethArchambault** [comment]
I'm experiencing this issue too - using windows via parallels on a mac as well.
