### ISSUE TITLE
Progress bar causes display issues when in debugger

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#17516]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to debug a module and if a progress bar is present when the debugger is entered it causes display issues by being always present at the bottom of the prompt. You can also see that the curser is on the same line as the and when text is typed it writes over the progress bar. Maybe the progress bar should be hidden when the debugger is displayed or detached from the bottom of the prompt.

### Expected behavior

```console
The progress bar does not causes display issues with the prompt.
```

### Actual behavior

```console
The progress bar stays at the bottom of the interactive prompt and causes display issues.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/38873752/172968790-0567c46f-3ea8-4479-af15-cf330cea8bcf.png)

**Comment by theJasonHelmick** [comment]
@ThomasNieto - Thank you for reporting this issue in the debugger.
