### ISSUE TITLE
Member-access enumeration on arrays of hashtables (dictionaries) works with dot notation, but not with index notation

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17514]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:
* Arguably, as the (new) name of the feature suggests, member-access enumeration should only apply to the behavior of `.`, the member-access operator, not also to `[]`, the index operator. However, even though it is a distinct operator with its own name, it still _accesses a member_, namely the parameterized `Item` property that `[]` is syntactic sugar for.

* However, given that dictionaries can be accessed with either operator (e.g. `@{ foo = 1 }['foo']` or `@{ foo = 1 }.foo`, the non-support for `[]` on collections  makes for an awkward asymmetry:

```powershell
# Index notation with key:
(@{ foo = 1 }, @{ foo = 2 })['foo']  # !! NO OUTPUT

# Dot notation (property access):
(@{ foo = 1 }, @{ foo = 2 }).foo     # OK -> 1, 2
```

### Expected behavior

Both commands should produce the same output.

### Actual behavior

The first command (index notation with key) produces no output.

### Environment data

```powershell
PowerShell Core v7.3.0-preview.4
```

**Comment by jhoneill** [comment]
I think this is a quirk of how the member and index operations work
`@(@{1="One"},@{1="Uno"})[1]` 

Applies the index to the array.    And `.1` doesn't work at all (it's not a valid member name)

So in your example `(@{ foo = 1 }, @{ foo = 2 })[1]` is the first item of the array.  

`@(1,2,3)["Hello"]`  Doesn't throw an error even through a string isn't valid as an array index.   And we can apply indexes to things which don't actually have them `$pid[0]`  is the same as `$pid` and `$pid[1]` or `$pid["hello"]` don't throw errors.   
`$Array.Something` acts as `foreach ($item in array) {$item.something}` and this is relied on in more places than we can count (especially where code assumes it is dealing with one object but is actually dealing with a single-member array,  note that with `$pid[0]`.  `$pid.count`, `foreach ($p in $Pid)`  etc we can make the opposite assumption ). 

Is there a need for a special behaviour in the index operator when the supplied index for an array is not an number?  Certainly there are cases like displaying a list of files and doing "$f = Read-Host "Enter the Number(s) of the files you want" and then getting `$files[$f]`  where we would not want the user typing `Name` to get all the file names .  If pushed I could argue the case for not allowing index to do anything different, I just wonder if there is a stronger counter-argument?

**Comment by mklement0** [comment]
It looks like you've found another inconsistency, given that `@{1="One"}.1` works just fine, why shouldn't
`(@{1="One"}, @{1="Uno"}).1`?

(That something like `@{1a="One"}` doesn't work as a hashtable literal unless the key is quoted, and that `@{'1a'="One"}.1a` doesn't work as a property access are separate problems: #15925 and #14036).

Re `[1]`: Note that we needn't consider _positional_ indexing in this discussion, because in member-access enumeration positional indexing is always applied to the _collection itself_, given that type-native members take precedence over looking for members on the elements of the collection.

Note that, strictly speaking, `IDictionary` entries aren't _members_ (properties), but as a _syntactic convenience_ PowerShell _usually_ allows you to treat them as such, with dot notation being supported interchangeably with _key_-based indexing (with subtle differences around key types).

And it is the inconsistency of this interchangeable use only applying to _scalars_ in the case of key-based indexing that this issue is about.

I don't feel strongly about this, and given that I only stumbled upon it recently, it suggests that not too many run into it.
Whether or not a change is made, I'd day that a note in [about_Member-Access_Enumeration](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Member-Access_Enumeration) is called for.

**Comment by jhoneill** [comment]
> It looks like you've found another inconsistency, given that `@{1="One"}.1` works just fine, why shouldn't `(@{1="One"}, @{1="Uno"}).1`? See #17520.

I can't imagine why it would be - some of these have a logic whether one agrees with it or not: but any logic I can think of depends on .1  _Never working_ if it ever works, it should always work. 

I think most of it can be  addressed with documentation.

**Comment by fluffy-cakes** [comment]
Updated to v7.2.5 yesterday, and this just bit me in the bum. Why did it have to change?  Now I need to update all my scripts 😢

**Comment by SeeminglyScience** [comment]
The Engine-WG discussed this yesterday and concluded that the behavior is by design. Indexing is considered an operation that already targets collections specifically. We do not believe it makes sense to propagate the operation to items in the collection.

**Comment by SeeminglyScience** [comment]
> Updated to v7.2.5 yesterday, and this just bit me in the bum. Why did it have to change? Now I need to update all my scripts 😢

This thread is a just a feature request (one that was declined), no changes have come from it.

If you'd like help troubleshooting what broke in your script you can open a discussion or ask on the [PowerShell discord server](https://aka.ms/psdiscord).

**Comment by mklement0** [comment]
Non-actionable food for thought that may help with conceptual clarity in future matters: 

This issue wasn't so much a feature request but was meant to highlight an inconsistency that may be surprising.

I should have framed it better originally: An index operation (`[...]`) is just as much a _member access_ as using `.` is; `[...]` is simply syntactic sugar for `.Item(...)`.

While hash tables (dictionaries) are technically collections, in PowerShell they're more treated like _scalar objects_ with the collection of entries treated like _properties_ - hence the interchangeable use of `.foo` and `['foo']`, for instance, and the non-enumeration of dictionaries in the pipeline.

Thus, my sense is that PowerShell users aren't likely to conceive of `['foo']` (let alone `.foo`) as accessing a _collection_.

Given what the index expression is syntactic sugar for, one might expect this to work (though `.foo` is simpler anyway), but it doesn't:

```powershell
# !! -> .Item() is preempted by the Array type's own method, 
# !!     which breaks with an argument that can't be coerced to [int]
(@{ foo = 1 }, @{ foo = 2 }).Item('foo')
```

That is, the precedence that member-access enumeration gives to members that exist directly on the collection type itself seems to be based on _name only_ : that the collection's elements may have a better overload match in terms of argument type or even have the _only_ match if the parameter count differs isn't considered (doing so may not be practical).

To bypass this problem, use of the intrinsic `.ForEach()` method _should_ help, but currently doesn't:

```powershell
# !! Inexplicably fails (returns empty collection).
# !! It does work with [ordered], however.
(@{ foo = 1 }, @{ foo = 2 }).ForEach('Item', 'foo')
```

See #17649
