### ISSUE TITLE
ANSI escape prompt incorrectly rendered when using git in Powershell

### ISSUE THREAD

**Issue by xudyang1** [PowerShell/PowerShell#17510]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am using the lastest Powershell with some prompt customization utilities. When I attempted to use Git in Powershell, the ANSI escapes in prompt were outputed as raw text.

Steps:
1. Install [Oh My Posh](https://ohmyposh.dev/docs/installation/windows) or [Starship](https://starship.rs/guide/#%F0%9F%9A%80-installation), and choose a theme or use the default one.
- For example, use `Oh My Posh`:
```pwsh
>winget install oh-my-posh
>#restart terminal
>oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json" | Invoke-Expression
```
```
>mkdir -p ps_debug; cd ps_debug; git init
>git remote add origin {REMOTE GITHUB REPO}
>git pull origin master # or maybe main
>git pull origin NOT_EXISTED_REMOTE_BRANCH
fatal: couldn't find remote ref NOT_EXISTED_REMOTE_BRANCH
←[38;2;195;134;241m←[0m←[48;2;195;134;241m←[38;2;255;255;255m username ←[0m←[38;2;195;134;241m←[0m←[38;2;255;71;156;49m←[7m←[0m←[48;2;255;71;156m←[38;2;255;255;255m   ps_debug ←[0m←[48;2;255;251;56m←[38;2;255;71;156m←[0m←[48;2;255;251;56m←[38;2;25;53;73m master ≢ ←[0m←[38;2;255;251;56m←[0m←[38;2;131;118;156;49m←[7m←[0m←[48;2;131;118;156m←[38;2;255;255;255m ﮫ626ms⠀←[0m←[48;2;233;30;99m←[38;2;131;118;156m←[0m←[48;2;233;30;99m←[38;2;255;255;255m  ←[0m←[38;2;233;30;99m←[0m←[K←[0J←[K←[0J←]0;pwsh in ps_debug←[0m
```

 Related Issues:
https://github.com/JanDeDobbeleer/oh-my-posh/issues/2396
https://github.com/starship/starship/issues/4044

### Expected behavior

```console
ANSI escapes in prompt should be rendered correctly.
```

### Actual behavior

```console
The raw text was printed.
```

### Error details

```console
none
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Capture](https://user-images.githubusercontent.com/61672396/172766919-a24a1aa9-36e7-4aba-8e98-c087f49f20d7.JPG)

**Comment by jhoneill** [comment]
I think this is a version of #16741  
That has been fixed in 7.3 preview but remains in 7.2.4 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/16209593/172829137-bd93e7f7-6346-4134-a297-b6f0714f3919.png">

Above 7.2.4 with the problem, below 7.3-preview4 with the fix.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/16209593/172829303-4d8d9109-33f0-4fb6-9cb9-661b5f0456c5.png">

It's worth trying on 7.3 preview to see if it is the same problem, or a new variant.

**Comment by daxian-dbw** [comment]
@xudyang1 Please give 7.3 preview a try and see if the issue you observed was fixed.

**Comment by xudyang1** [comment]
> @xudyang1 Please give 7.3 preview a try and see if the issue you observed was fixed.

Yes, the prompt is rendered correctly in 7.3 preview .
