### ISSUE TITLE
parameter name doesn't work with strings if numeric start 

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#17521]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
```
param
(
	[String]$1abc
)

Write-Host ${1abc}
```

trace-command -PSHOST -Name ParameterBinding { a:\pscode\TEMP_2022\temp144\aaa-v1.ps1 -1abc 'xxx' }
DEBUG: 2022-06-12 13:23:33.5542 ParameterBinding Information: 0 : BIND arg [-1abc] to parameter [1abc]
DEBUG: 2022-06-12 13:23:33.5572 ParameterBinding Information: 0 :     Executing DATA GENERATION metadata: [System.Management.Automation.ArgumentTypeConverterAttribute]
DEBUG: 2022-06-12 13:23:33.5576 ParameterBinding Information: 0 :         result returned from DATA GENERATION: -1abc
DEBUG: 2022-06-12 13:23:33.5580 ParameterBinding Information: 0 :     BIND arg [-1abc] to param [1abc] SUCCESSFUL
DEBUG: 2022-06-12 13:23:33.5588 ParameterBinding Information: 0 : BIND NAMED cmd line args [Write-Host]
DEBUG: 2022-06-12 13:23:33.5590 ParameterBinding Information: 0 : BIND POSITIONAL cmd line args [Write-Host]
DEBUG: 2022-06-12 13:23:33.5594 ParameterBinding Information: 0 : BIND REMAININGARGUMENTS cmd line args to param: [Object]
DEBUG: 2022-06-12 13:23:33.5597 ParameterBinding Information: 0 :     BIND arg [System.Collections.Generic.List`1[System.Object]] to parameter [Object]
DEBUG: 2022-06-12 13:23:33.5599 ParameterBinding Information: 0 :         COERCE arg to [System.Object]
DEBUG: 2022-06-12 13:23:33.5602 ParameterBinding Information: 0 :             Parameter and arg types the same, no coercion is needed.
DEBUG: 2022-06-12 13:23:33.5606 ParameterBinding Information: 0 :         BIND arg [System.Collections.Generic.List`1[System.Object]] to param [Object] SUCCESSFUL
DEBUG: 2022-06-12 13:23:33.5609 ParameterBinding Information: 0 : MANDATORY PARAMETER CHECK on cmdlet [Write-Host]
DEBUG: 2022-06-12 13:23:33.5611 ParameterBinding Information: 0 : CALLING BeginProcessing
DEBUG: 2022-06-12 13:23:33.5612 ParameterBinding Information: 0 : CALLING ProcessRecord
-1abc
DEBUG: 2022-06-12 13:23:33.5659 ParameterBinding Information: 0 : CALLING EndProcessing

### Expected behavior

```console
xxx
```

### Actual behavior

```console
a:\pscode\TEMP_2022\temp144\aaa-v1.ps1 -1abc -1
-1abc

a:\pscode\TEMP_2022\temp144\aaa-v1.ps1 -1abc 1
-1abc

a:\pscode\TEMP_2022\temp144\aaa-v1.ps1 -1abc 'xxx'
-1abc
```

### Environment data

```powershell
win+powershell5.1
win+powershell7.3.0-preview.4
```

**Comment by mklement0** [comment]
Good catch; minimal repro:

```powershell
PS> & { param($1a) $1a } -1a foo
-1a   # !! Parameter name wasn't recognized as such, treated as positional argument.
```

As an aside: the _inverse_ problem (affecting the CLI only) is discussed in #17519

**Comment by Pablo1q** [comment]
Working

**Comment by mklement0** [comment]
Not working 

(I've carefully matched the amount of information contained in your comment in my response.)

**Comment by Pablo1q** [comment]
Yes . Its working.  Everything is good

**Comment by kasini3000** [comment]
> As an aside: the _inverse_ problem (affecting the CLI only) is discussed in #17519

i found this issue one year ago, saw your issue yesterday and reminded me of this issue
