### ISSUE TITLE
Member access bug: Using a given integer first for property access in a session breaks hashtable access with dot notation for that number

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17525]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: This is an edge case, given that "number string" property names such as `101` are rare, but the bug is quite insidious in its subtlety.

Credit goes to @jhoneill for discovering the bug, including [how to reproduce it](https://github.com/PowerShell/PowerShell/issues/17520#issuecomment-1154527363)

In short: If a given integer, say `.101`, is used to access a _property_ of a custom object in a session _before_ using `.101` on a _hashtable_ that has an entry with such an `[int]`-typed key, the latter access fails _for the remainder of the session_ (only _index syntax_ (`[101]`) works consistently). If the order is reversed (hashtable access first in the session), everything works as expected.

```powershell
# Define hashtable with numeric key..,
$h = [hashtable]@{ 101 = 'foo' }
# ...and an equivalent [pscustomobject], 
#    where the number implicitly becomes a property-name *string*.
#    Note that the numbers must be the *same* to surface the bug.
$o = [pscustomobject]@{ 101 = 'foo' }

# === These always works as expected: property access on the object, index access on the hastable.
# !! If you comment out the next line and re-run the code *in a new session*, the symptom goes away.
[pscustomobject] @{ object = 'pscustomobject'; access='.101'; value = $o.101 }
[pscustomobject] @{ object = 'hashtable'; access='[101]'; value = $null -eq $h[101] ? '$null' : $h[101] }

# === !! These *normally* work, but stop working for the remainder of the session, regardless of scope,
#     !! if `$o.101` was executed *first* in the session.
[pscustomobject] @{ object = 'hashtable'; access='.101'; value = $null -eq $h.101 ? '$null' : $h.101 }
[pscustomobject] @{ object = 'hashtable'; access='.([int] 101)'; value = $null -eq $h.([int] 101) ? '$null' : $h.([int] 101) }
```

### Expected behavior

```console
object         access       value
------         ------       -----
pscustomobject .101         foo
hashtable      [101]        foo
hashtable      .101         foo
hashtable      .([int] 101) foo
```

### Actual behavior

```console
object         access       value
------         ------       -----
pscustomobject .101         foo
hashtable      [101]        foo
hashtable      .101         $null  # !!
hashtable      .([int] 101) $null  # !!
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.4
```

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine We will revisit this in 6 months to see if there's any interest in providing a PR, if not we will likely resolve as won't fix
