### ISSUE TITLE
Add-Type / PowerShell 7+: No wildcard accepted for -AssemblyName parameter

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#17529]
### Steps to reproduce

The [Microsoft documentation on `Add-Type`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type#parameters) claims that the `AssemblyName` parameter accepts wildcards.

However, when I try using `Add-Type -AssemblyName '*SqlServer.Smo'` in PowerShell Core, it doesn't work. I get the error message: "`Add-Type: Cannot load assembly '*.SqlServer.Smo'`":

![PowerShell Add-Type](https://i.stack.imgur.com/sOTsd.png)

### Expected behavior

```powershell
Add-Type -AssemblyName '*SqlServer.Smo'
```
… should exactly behave like …
```powershell
Add-Type -AssemblyName 'Microsoft.SqlServer.Smo'
```

### Actual behavior

See screenshot above.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
It works if assembly.dll in current directory or maybe in `PATH`.
```powershell
 > pushd $pshome
 > dir Ma*.dll  

    Directory: /opt/microsoft/powershell/7

UnixMode     ACL    User   Group      LastWriteTime    Size Name
--------     ---    ----   -----      -------------    ---- ----
-rw-r--r--   644    root    root   11.05.2022 23:01    1,1M Markdig.Signed.dll

  > Add-Type -AssemblyName "*.Signed"  # No Error          
```

**Comment by SetTrend** [comment]
I see, so it doesn't need to be in `PATH` if you don't use wildcards, but it must be in `PATH` when you do?

Isn't this observation odd?

**Comment by 237dmitry** [comment]
I think wildcards are available only if assembly dll in the current directory. As a variant you can use Path parameter:
```
Add-Type -Path "$pshome\*csharp*"
```

**Comment by SetTrend** [comment]
PowerShell 5.1 seems to be able to resolve above example on the same machine without flaw. I'm still not confident that `Add-Type` should require a `PATH` entry.

You know, all modules and .NET libaries are stored at predictable locations. They never reside in any folder that's mentioned in `PATH`.

**Comment by 237dmitry** [comment]
> You know, all modules and .NET libaries are stored at predictable locations. They never reside in any folder that's mentioned in PATH

In my environment they are all in `$PSHome`. When pwsh started `$PSHome` automatically sets in `$env:Path`

pwsh:
```powershell
> $env:PATH -split ':'
/opt/microsoft/powershell/7
/home/herz/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/var/lib/flatpak/exports/bin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
/var/lib/snapd/snap/bin
```
bash:
```bash
$ echo $PATH | sed 's/:/\n/g'
/home/herz/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/var/lib/flatpak/exports/bin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
/var/lib/snapd/snap/bin
```

**Comment by vexx32** [comment]
> You know, all modules and .NET libaries are stored at predictable locations. 

This is only true under .NET Framework (<= 4.8.x) where there is a Global Assembly Cache for .NET applications to reference. That's likely one of the main reasons that this works as expected in Windows PowerShell.

For PowerShell 7, there is no such global cache to reference. The only reasonable place pwsh could search by default would be $PSHOME, and I'd agree that it probably should search that when a wildcard is given to Add-Type. Beyond the assemblies shipped with pwsh though, I'm not sure there is anywhere else it could reasonably search.

**Comment by SetTrend** [comment]
@vexx32: That's very enlightening, thank you! 👍👍

However, though, why does it (presumingly) find `Microsoft.SqlServer.Smo` when I don't use wildcards then? According to your statement, PowerShell 7+ would require a path then, too. Omitting the wildcard doesn't help in locating an assembly, AFAIK, does it?

**Comment by vexx32** [comment]
Unsure how the code paths diverge here exactly I'm afraid, but I suspect there's some reliance on .NET's default behaviour for loading assemblies here that we'll likely need to compensate for.

**Comment by SetTrend** [comment]
Do you believe this is something that needs investigation and amendment?

I suspect, the documentation is quite clear on the input and outcome:

> Specifies the name of an assembly that includes the types. Add-Type takes the types from the specified assembly. This parameter is required when you're creating types based on an assembly name.
>
> Enter the full or simple name, also known as the partial name, of an assembly. Wildcard characters are permitted in the assembly name.

**Comment by SetTrend** [comment]
Hmm, shouldn't this issue be handled somehow? Non-acting and eventually closing shouldn't be a solution.

**Comment by Thoufeequeintellipaat** [comment]
Hi Team,

I need help with a PS script.

I have 1000+ ASG in application RG in different subscriptions (for example RG1) and I want to move this from RG1 to RG2 in the same subscription. can I get assistance how to pull the data from excel and take action.

Thanks & Regards

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  The probing for assembly is entirely handled by .NET.  When it is not found, then it falls back to custom code which uses the wildcard against the current location only.  We decided that it would be best to document this specific behavior rather than adding probing with wildcard.

**Comment by SteveL-MSFT** [comment]
Created https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10931

**Comment by SetTrend** [comment]
Thanks for adding this valuable information to the documentation 👍👍👍

However, I believe it wouldn't have hurt to add a line similar to …

```
if ($env:windir)
{
  [string]$path = "$($env:windir)\assembly\$searchTerm"
  (if Test-Path $path) { result += (Get-ChildItem -Path $path) }

  $path = "$($env:windir)\Microsoft.NET\assembly\$searchTerm"
  (if Test-Path $path) { result += (Get-ChildItem -Path $path) }
}
```
… to the PowerShell code.
