### ISSUE TITLE
Set-AuthenticodeSignature does not handle MIME type "application/timestamp-reply"

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1752]
Description: Problem:
When using Set-AuthenticodeSignature and specifying a TimeStampServer http URL, if the time stamp server returns content/MIME type of: "application/timestamp-reply" the cmdlet returns an unknown error with a status of "ASN1 bad tag value met". This is non-compliant according to RFC3161 for Time-Stamp protocol via HTTP.

Expected - Set-AuthenticodeSignature with a specified timestampserver URL appropriately handles the "application/timestamp-reply" content/MIME, commits the authenticode signature as well as the timestamp from said server without error.

Additionally, the success case today is when using Set-AuthenticodeSignature with a specified timestampserver URL and the response is content/MIME type of "application/octet-stream" the cmdlet returns without error, the authenticode signature is committed and the timestamp is commited without error.

**Comment by SteveL-MSFT** [comment]
TFS:6897298

**Comment by joeyaiello** [comment]
We could certainly use a better repro here if someone has one. Either way, it's a fairly low-pri issue, moving it out.

**Comment by kechols2406** [comment]
$test = Set-AuthenticodeSignature -Certificate $cert -IncludeChain All -FilePath C:\Powershell
\script.ps1 -TimeStampServer "http://sha256timestamp.ws.symantec.com/sha256/timestamp"
$test.StatusMessage

**Comment by chandj** [comment]
`set-authenticodesignature c:\test.ps1 -certificate $mycert -hashalgorithm "SHA256" -timestampserver "http://sha256timestamp.ws.symantec.com/sha256/timestamp"`  

will reproduce this error.  Please consider bumping this up in priority, as it stops us from timestamping signed scripts according to Microsoft's new timestamping standards.  Thanks!

**Comment by SteveL-MSFT** [comment]
Not sure if there's much we can do here, it appears that the cmdlet simply passes the signing to the native [CryptUIWiz](https://github.com/PowerShell/PowerShell/blob/4bc52d2358222084738157a08907fac32d13bd3a/src/System.Management.Automation/security/nativeMethods.cs#L511) API which is returning this error.  Looking at the CryptAPI, it appears they only support `octet-stream`.  They would need to support `timestamp-reply` and this cmdlet should just work.

Best way to get this supported is to open or upvote a issue here: https://wpdev.uservoice.com/

**Comment by gillesveyet** [comment]
Vote [here](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/33239629-cryptuiwiz-to-support-timestamp-reply) to support Jordan Chan proposal "Cryptuiwiz to support timestamp-reply"

**Comment by GregoryOtt** [comment]
User Voice is no longer up... Anyone knows where we can follow this issue?

**Comment by gillesveyet** [comment]
Sorry I don't know, and I am less interested in this as I have switched to http://timestamp.digicert.com  which works with PowerShell.

Note : Anyone using legacy VeriSign and symantec time stamping services should switch to digicert : https://knowledge.digicert.com/alerts/migration-of-legacy-verisign-and-symantec-time-stamping-services.html

**Comment by pl4nty** [comment]
For what it's worth, http://timestamp.acs.microsoft.com also triggers this bug on 26100.6508

<blockquote></blockquote>
