### ISSUE TITLE
Member-access enumeration doesn't work with numeric hashtable keys

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17520]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Undoubtedly an edge case, but it makes me wonder whether other discrepancies between single-object dot notation (property access) and member-enumeration-based dot notation exist:

```powershell
@{ 42 = 'foo' }.42           # OK -> 'foo'

(@{ 42 = 'foo1' }, @{ 42 = 'foo2' }).42  -join ', ' # !! No output
```

Note that  the problem does _not_ occur with _string_-valued hashtable keys (which is what's typical), e.g. 
`(@{ a42 = 'foo1' }, @{ a42 = 'foo2' }).a42  -join ', '`
Similarly, the following works as expected:
`([pscustomobject] @{ 42 = 'foo1' }, [pscustomobject] @{ 42 = 'foo2' }).42  -join ', '`

### Expected behavior

```console
foo
foo1, foo2
```

### Actual behavior

```console
foo
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.4
```

**Comment by jhoneill** [comment]
**Supplementary** 

> ```powershell
>   @{  42  = 'foo' }.42      #Returns "foo"
>  (@{  42  = 'foo' }).42     #Returns "foo"
> @(@{  42  = 'foo' }).42     #Returns nothing
> @(@{ "42" = 'foo' }).42     #Returns "foo"
> ```

It appears the member operator converts its operand to a string when processing members of an array.

**Comment by scriptingstudio** [comment]
It never worked because "selector" `.42` is expected to be a string, so expression `(@{ 42 = 'foo1' }, @{ 42 = 'foo2' }).42` is incorrect itself

**Comment by mklement0** [comment]
@scriptingstudio, please note the first example in the OP, which _does_ work: `@{ 42 = 'foo' }.42` - the issue at hand is that with _member-access enumeration_ it doesn't.

**Comment by mklement0** [comment]
To put it differently: the promise of member-access enumeration is that:

```powershell
(@{ 42 = 'foo1' }, @{ 42 = 'foo2' }).42 # !! BROKEN
```

is shorthand for:

```
@{ 42 = 'foo1' }, @{ 42 = 'foo2' } | ForEach-Object { $_.42 }   # OK
```

Clearly, the promise isn't being fulfilled here.

**Comment by scriptingstudio** [comment]
That is NOT shorthand, because your array is not array of psobjects

**Comment by scriptingstudio** [comment]
psobject property type is always a string, but a hashtabe is a diff story

**Comment by mklement0** [comment]
This issue is about the behavior of the member-access operator, `.` - it doesn't matter what .NET type it operates on, and that with hashtables, as a syntactic convenience, it allows accessing entries _as if they were_ properties.

The point is that  if a given `.` works with a given scalar, it should work via member-access enumeration on a collection of such scalars.

Otherwise, we're faced with a confusing inconsistency for which I see no justification; see also: https://github.com/PowerShell/PowerShell/issues/17514.

**Comment by jhoneill** [comment]
> It never worked because "selector" `.42` is expected to be a string, so expression `(@{ 42 = 'foo1' }, @{ 42 = 'foo2' }).42` is incorrect itself

@scriptingstudio  yes., that would be fine if `@{ 42 = 'foo1' }.42`  did not work either.  

@mklement0  `$h = @{ 42 = 'foo1' } ; $h.42`   
returns nothing but  `$h = @{ "42" = 'foo1' } ; $h.42` returns foo1 so it looks like its the @{}. combination is processed differently from everything  else - it's no applicable to other hashtables 
```
 (@{ 42 = 'foo1' }, @{ 42 = 'foo2' } | ForEach-Object { $_.42 } 
```
Outputs nothing.

**Comment by mklement0** [comment]
@jhoneill, I think you swapped the two scenarios:

```powershell
$h = @{ 42 = 'foo1' } ; $h.42   # -> 'foo1': property "name" type ([int]) matches the type of the hash-entry key.

$h = @{ '42' = 'foo1' } ; $h.42   # -> $null; property "name" type does *not* match

# Quoting fixes the mismatch
$h = @{ '42' = 'foo1' } ; $h.'42'   # -> 'foo1'
```

This distinction is tricky, for sure, and specific to hash tables, but it has always worked this way - and it is a separate issue from the one at hand.

**Comment by jhoneill** [comment]
@mklement0 
<img alt="image" src="https://user-images.githubusercontent.com/16209593/173437788-2e98c87a-7331-44d3-bf44-3362e8e04d5a.png">


That's what I got which showed $h.42 converted 42 to a string

**Comment by mklement0** [comment]
As an aside: while switching to `[pscustomobject]` avoids this particular problem -  `$o = [pscustomobject] @{ '42' = 'foo1' } ; $o.42` works without needing to quote the property name - the fact that a property name is generally parsed _as a number literal_ if it _looks like one_ can also break `[pscustomobject]` access; e.g.:

```powershell
$o = [pscustomobject] @{ '1L' = 'foo1'; '1' = 'why me?' } ; $o.1L  # -> !! 'why me?'
```

That is, the `1L` in  `.1L` was parsed as a `[long]` with value `1`, and the stringified version of it is just `'1'`, so that was the property that was accessed.

**Comment by jhoneill** [comment]
Can you explain this, because it beats me :-) 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/16209593/173440317-9c46c836-6ab7-447d-9a8c-69b2d9874cd2.png">

**Comment by mklement0** [comment]
@jhoneill, that is very curious - the behavior on the right side is what I expect and see consistently; I have no explanation for the left side. Can you consistently reproduce the left-side behavior and, if so, how?

**Comment by jhoneill** [comment]
@mklement0  I still had the window I tested in the first time open, so I've just dumped the history out and reproduced it. But I can't see anything which would change the the behaviour of the member operator.
It's in this gist if you want to have a play 
https://gist.github.com/jhoneill/7239a13c0faaa2b875c267ea093464dd

**Comment by jhoneill** [comment]
I got it down to this
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/16209593/173460291-c12c9233-b63e-4a94-be5a-287a75741d72.png">

It's almost like the member operator remembers that it has seen a string property "42" causing it to change behaviour - try with and without line 2 :-) 
```
$psco = [pscustomobject]@{ 42 = 'foo1' }
$Psco.42
$h = @{ 42 = 'foo1' }
$h.42
$h = (@{ "42" = 'foo1' })
$h.42
```
