### ISSUE TITLE
$ErrorActionPreference accept "Continue" but not "SilentlyContinue"

### ISSUE THREAD

**Issue by Gill-Bates** [PowerShell/PowerShell#17539]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I set an `$ErrorActionPreference` in Powershell, a `Continue `is accepted without quotes and a `SilentlyContinue` is not. This is inconsistent!

### Expected behavior

```console
$ErrorActionPreference = SilentlyContinue should also work as $ErrorActionPreference = Continue
```

### Actual behavior

```console
$ErrorActionPreference = 'SilentlyContinue' = Works
$ErrorActionPreference = SilentlyContinue = Works not!

SilentlyContinue: The term 'SilentlyContinue' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
You can run `$ErrorActionPreference = Continue` because `continue` is a valid keyword in that context but it doesn't actually set the `$ErrorActionPreference` to `continue`, that's just the default value it has.

**Comment by scriptingstudio** [comment]
because `SilentlyContinue` is a command and `'SilentlyContinue'` is a string. Argument is expected to be a `string`.

**Comment by jhoneill** [comment]
= Continue is valid as syntax.  But it doesn't **work** 

`$ErrorActionPreference=break`  also runs  because break is a keyword. BOTH exit the assignment without setting it 

```
PS>  $ErrorActionPreference=break

PS>  $ErrorActionPreference
Continue

PS>  $ErrorActionPreference="break"

PS>  $ErrorActionPreference        
Break

PS>  $ErrorActionPreference=continue

PS>  $ErrorActionPreference
Break

PS>  $ErrorActionPreference="continue"

PS>  $ErrorActionPreference
Continue
```
