### ISSUE TITLE
Get-Item different times and results for V5.1.19041.1682 and V7.2.4

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#17537]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using V7 takes considerably longer that V5 and it does not return the same results. 

[GetDLLTest.zip](https://github.com/PowerShell/PowerShell/files/8929138/GetDLLTest.zip)

In the zip file execute the Get-Dll-Test.ps1 script on both V5 and V7 and note the time differences and the number of items returned.

To compare the contents of the returned data the results are exported via export-clixml which does take a while - be patient.

When you have both the V5 and V7 xml files you can run Get-Dll-Test.ps1 to see the differences.

I was trying to find the most efficient way to execute a similar command on a number of files and the best way to see timing differences is to have a large number as this shows what if any improvements can be made by changing the way you approach the issue at hand. The commented-out code was going to be addressed next, but I thought I would report this first.

91 items not returned in V7 and it is slower by 2 minutes
 

### Expected behavior

```console
PS C:\> S:\DirTest\Get-Dll-Test.ps1

Days              : 0
Hours             : 0
Minutes           : 3
Seconds           : 20
Milliseconds      : 149
Ticks             : 2001498795
TotalDays         : 0.00231654953125
TotalHours        : 0.05559718875
TotalMinutes      : 3.335831325
TotalSeconds      : 200.1498795
TotalMilliseconds : 200149.8795

29737 items returned in 3.3 minutes
```

### Actual behavior

```console
PS C:\> S:\DirTest\Get-Dll-Test.ps1

Days              : 0
Hours             : 0
Minutes           : 5
Seconds           : 3
Milliseconds      : 191
Ticks             : 3031919100
TotalDays         : 0.003509165625
TotalHours        : 0.084219975
TotalMinutes      : 5.0531985
TotalSeconds      : 303.19191
TotalMilliseconds : 303191.91

29646 items returned in 5 minutes
```

### Error details

```console
No actual errors produced but I cannot explain why a different number of items are returned given it is the exact same script, and it took two minutes longer in V7.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

None - run the code to get the visuals on you screen.

**Comment by jhoneill** [comment]
There is a difference in the filter behaviour

On **PS 5** using a simplified version of your code
``` 
PS > $pfPaths = 'C:\Program Files*\', 'C:\Windows\'
PS > $result2 = Get-ChildItem -Path $PFPaths -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue
PS > $result2.Count
40471
PS > $result2.where({$_.Extension -eq ".dll"}).count
40061
```
You can see files where the 8.3 name ends .DLL but the normal extension doesn't using    ~
`$result2.where({$_.Extension -ne".dll"})`

on **ps 7**
```
PS> $result2 = Get-ChildItem -Path $PFPaths -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue
PS> $result2.count
40061
```
`C:\Program Files*\`  will not always process they way you want to  The extra step below is needed to work round that 
```
 $result3 = (get-item $pfpaths | Get-ChildItem -Recurse -ErrorAction SilentlyContinue -file).where({$_.Extension -eq ".dll"})
```
returns 40061 items in 25 seconds on PowerShell 5 and 
and 40061 items in 16 seconds on PowerShell 7  (obviously there are some machine specifics and variation from run to run) 

That I thought the version information was slowing things down but 
```
PS> $result3 | Where {$_.VersionInfo.ProductVersion -or $_.VersionInfo.FileVersion}   | measure
```

Got  28548  items in 12 seconds on both PowerShell 7 and 5

**Comment by RG255** [comment]
@jhoneill  Thanks for those examples. I can see where some confusion lies in the way things are processed.

I put those examples into the attached script, there is a difference in times (Agreed it is machine specific) but PS7 is a lot slower? That said the second method is faster than the first for PS7 and slower for PS5

Also, in the two methods we end up with a difference of 1 item in PS7 & PS5

The reason for this is that hall.dll is a directory not a file. So, I do need to add the -file parameter anyway but then I get a large difference in numbers: 

Result2 Numbers
52403
Result2 eq dll
52003
Result2 ne dll
400

I will continue to work on things. and ensure I only get files and not directories.

Is there any reason why PS7 should be taking longer?

=======================================
PS 7
S:\DirTest\Get-Dll-Test_1.ps1
Result2 Starting

Days              : 0
Hours             : 0
Minutes           : 3
Seconds           : 1
Milliseconds      : 954
Ticks             : 1819542415
TotalDays         : 0.00210595186921296
TotalHours        : 0.0505428448611111
TotalMinutes      : 3.03257069166667
TotalSeconds      : 181.9542415
TotalMilliseconds : 181954.2415

Result2 Numbers
62125
Result2 eq dll
62125
Result2 ne dll
0

Result3 Starting
Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 1
Milliseconds      : 329
Ticks             : 1213299042
TotalDays         : 0.00140428129861111
TotalHours        : 0.0337027511666667
TotalMinutes      : 2.02216507
TotalSeconds      : 121.3299042
TotalMilliseconds : 121329.9042

Result3 Numbers
62124
Result3 eq dll
62124
Result3 ne dll
0
InputObject   : C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\sym\hal.dll
SideIndicator : <=

=======================================
PS 5
PS C:\> S:\DirTest\Get-Dll-Test_1.ps1
Result2 Starting

Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 7
Milliseconds      : 306
Ticks             : 673068861
TotalDays         : 0.000779014885416667
TotalHours        : 0.01869635725
TotalMinutes      : 1.121781435
TotalSeconds      : 67.3068861
TotalMilliseconds : 67306.8861

Result2 Numbers
62529
Result2 eq dll
62125
Result2 ne dll
404

Result3 Starting
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 38
Milliseconds      : 555
Ticks             : 985551129
TotalDays         : 0.00114068417708333
TotalHours        : 0.02737642025
TotalMinutes      : 1.642585215
TotalSeconds      : 98.5551129
TotalMilliseconds : 98555.1129

Result3 Numbers
62124
Result3 eq dll
62124
Result3 ne dll
0

The compare in PS5 was taking too long - I gave up waiting. In fact I think it was hanging lots of CPU so I killed the task.

[Get-Dll-Test_1.zip](https://github.com/PowerShell/PowerShell/files/8933975/Get-Dll-Test_1.zip)

**Comment by RG255** [comment]
So, I have found the quickest way so far is shown below but the exercise has been useful thanks for your help.

(if there is a better way then please advise)

  function Get-Dll
  {
    param
    (
      [System.IO.FileSystemInfo]
      [Parameter(Mandatory = $True, ValueFromPipeline = $True, HelpMessage = 'Data to filter')]
      $InputObject
    )
    process
    {
      if ($InputObject.extension -eq '.dll' -and ($InputObject.VersionInfo.ProductVersion -or $InputObject.VersionInfo.FileVersion))
      {
        $Result = [Ordered]@{
          Name            = $InputObject.Name
          ProductVersion  = $InputObject.VersionInfo.ProductVersion
          FileVersion     = $InputObject.VersionInfo.FileVersion
          FileDescription = $InputObject.VersionInfo.FileDescription
          FullName        = $InputObject.FullName
        }
        New-Object -TypeName PSObject -Property $Result
      }
    }
  }
$PFPaths = 'C:\Program Files*\', 'C:\Windows\'
$DLLs=(Get-Item -Path $PFPaths |
    Get-ChildItem -Recurse -ErrorAction SilentlyContinue -File |
    Get-Dll)
