### ISSUE TITLE
Format-Table (and Format-List) should have a -FormatString  parameter. 

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#17544]
### Summary of the new feature / enhancement

Sending some data through format table I see this 

```
Product         Birmingham          Cardiff        Edinburgh          Glasgow           London
-------         ----------          -------        ---------          -------           ------
Asparagus             26.5               26 26.6666666666667 28.1666666666667 27.3333333333333
Cucumber  27.6666666666667 27.3333333333333             33.5 21.1666666666667 28.3333333333333
Lettuce   29.6666666666667             23.5 35.1666666666667 25.1666666666667 35.1666666666667
Potato                21.5 26.1666666666667 24.3333333333333             24.5               30
Tomato    32.3333333333333               32 28.8333333333333 29.1666666666667             26.5

```

Using custom properties I can specify a format string for each column. But that needs to be done 5 times - and may places of decimals limit the number of columns that can be fitted in. 

In an ideal world we would have  `<blah> | format-table * -FormatString "0.00" `

**Comment by 237dmitry** [comment]
With right-side alignment?

**Comment by jhoneill** [comment]
When you use @{f="0.00";e='ColumnName'} numbers remain right aligned.  
Where `@{e={$_.ColumnName.Tostring("0.00")}}`  would be left aligned  

```
ps> $dataToPivot | ConvertTo-CrossTab -ValueName sales -RowName product -columnname location -Aggregate Average  | ft product, @{f="0.00";e="Cardiff"}

product   Cardiff
-------   -------
Asparagus   29.86
Cucumber    33.86
Lettuce     34.00
Potato      34.86
Tomato      37.71

ps> $dataToPivot | ConvertTo-CrossTab -ValueName sales -RowName product -columnname location -Aggregate Average  | ft product, @{n="Long name goes here"; e={$_.Cardiff.tostring("0.00")}}

product   Long name goes here
-------   -------------------
Asparagus 29.86
Cucumber  33.86
Lettuce   34.00
Potato    34.86
Tomato    37.71
 ```

I just don't want to write 
```
 ft product, @{f="0.00";e="Birmingham"} , @{f="0.00";e="Cardiff"},@{f="0.00";e="Edinburgh"}, @{f="0.00";e="Glasgow"},@{f="0.00";e="London"} 
 ```
 especially as in this case I don't what the column names will be before I run the command

**Comment by SteveL-MSFT** [comment]
Alternate proposal is to have the formatting engine always format floats to 2 decimal places for tables by default.  I think this will be useful in general as most people don't need more than 2 decimal places and the actual object always retain the actual value.

**Comment by iSazonov** [comment]
We always say Formatting System follow current culture. So we should use the format from current culture from OS
![image](https://user-images.githubusercontent.com/22290914/177686520-7cad9c51-8941-4297-8fb1-06d02f3e7291.png)

**Comment by jhoneill** [comment]
@iSazonov  (cc @SteveL-MSFT )
 
YES

**Comment by SteveL-MSFT** [comment]
@iSazonov yes, using current culture absolutely makes sense.  I'll create a PR.

**Comment by jhoneill** [comment]
Downloaded the preview and first tests look like **exactly what I wanted** (though not as I asked for it in when I opened the issue). Big thanks to all those who made it happen
