### ISSUE TITLE
Out-File is adding control characters when given a hashtable or list of PSCustomObject

### ISSUE THREAD

**Issue by StingyJack** [PowerShell/PowerShell#17543]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

``` pwsh
PS C:\Users\me> $newRecords = @{}
>> $newRecords.Add("abc", 123)
>> $newRecords.Add("Def", 435)
>> $newRecords.GetEnumerator() | Out-File c:\temp\newRecs.txt
>> type c:\temp\newRecs.txt

Name                           Value
----                           -----
abc                            123
Def                            435

PS C:\Users\me> invoke-item C:\temp\newRecs.txt
```
Actual: (cant paste images in the actual/expected fields on this form)
![image](https://user-images.githubusercontent.com/15381181/174522942-7cc458ad-c970-4072-bd57-4256257afd12.png)
``` pwsh
PS C:\Users\me>notepad c:\temp\newRecs.txt
```
![image](https://user-images.githubusercontent.com/15381181/174522972-544bad81-6c89-4750-a0c8-15b51eff80ff.png)

Expected:
![image](https://user-images.githubusercontent.com/15381181/174523087-0a97f4c9-7e95-4293-ad8f-9f2e5a55f58b.png)

I dont remember having this problem before, and it does not happen when I pipe strings to `out-file`.  It does happen if I made PSCustomObjects with a Name and Value, added them to a list and tried to emit them to a file. I tried the different encodings for Out-File and none of them made a difference. 

### Expected behavior

```console
See STR, cant paste images here
```

### Actual behavior

```console
See STR, cant paste images here
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
It is fixed in 7.3 preview, but annoying in 7.2  

Workround for now is `$psstyle.OutputRendering = "plaintext"` or ``$psstyle.OutputRendering = "Host"``
