### ISSUE TITLE
Mandatory params defined in NetworkControllerAdapter not shown for get cmdlet

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1754]
Repro steps:

> help new-NetworkControllerState

NAME
    Get-NetworkControllerState
SYNTAX
    Get-NetworkControllerState [-ConnectionUri <uri>] [-CertificateThumbprint <string>] [-Credential <pscredential>]
    [-PassInnerException]  [<CommonParameters>]

Mandatory parameter defined in NetworkControllerAdapter.cs ConnectionUri is shows as optional in ps.

**Comment by SteveL-MSFT** [comment]
TFS:8384570

**Comment by joeyaiello** [comment]
This issue was moved to MicrosoftDocs/windows-powershell-docs#55
