### ISSUE TITLE
I'm receiving notifications about version 7.2.5 – but there's no 7.2.5 released

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#17556]
PowerShell 7.2.4 and VS Code both display notifications, advertising PowerShell Core 7.2.5. But there's no 7.2.5 listed in Microsoft Docs nor here in the Releases table.

**Is this a phishing scam situation?** What is the truth about version 7.2.5?

**Comment by daxian-dbw** [comment]
7.2.5 was released 2 days ago: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.5

**Comment by SetTrend** [comment]
Thanks, @daxian-dbw, for clarifying! 👍
