### ISSUE TITLE
Docs suggest MSI installer should show Microsoft Update options during repair install

### ISSUE THREAD

**Issue by soyfrien** [PowerShell/PowerShell#17551]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the MSI installer and choose the Repair option and proceed to finish.

### Expected behavior

Expected dialogue with two options related to Microsoft Update. (The second bullet point in the [Troubleshooting section of the docs](https://docs.microsoft.com/en-us/powershell/scripting/install/microsoft-update-faq?view=powershell-7.2) says "Do a repair install using the MSI to ensure that both checkboxes are checked.")

### Actual behavior

The Microsoft Update options are not presented and the repair install completes.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3
```

### Visuals

![PowerShellRepairInstall](https://user-images.githubusercontent.com/3385925/174764190-05438db6-8734-4438-a9a8-6b2d3d50dcf3.gif)

**Comment by soyfrien** [comment]
The docs have changed regarding this issue. If I can figure out how to build the project (have been trying on and off for a few weeks but I always get `could not load file or assembly microsoft.codeanalysis 4.3.0.0` errors) I think I can enable the options, but I don't want to have more issues open than necessary so I am closing this.

**Comment by StevenBucher98** [comment]
Thanks @soyfrien! I didnt see the recent changes to made an additional PR clarifying further since I intrepreted the fix as the current pain point 😆  this is my PR: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/9008
