### ISSUE TITLE
Users who installed PowerShell through Microsoft Store can't upgrade to 7.2.5 without installing previous verions first and losing all customization with it as part of this path

### ISSUE THREAD

**Issue by zagros** [PowerShell/PowerShell#17557]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

# Issue

* Got a message to upgrade to `7.2.5`
* I installed using Microsoft Store, so I need to update using it as well
* I don't get an upgrade option (see screenshot)

### Expected behavior

```console
To be able to upgrade 7.2.4 to 7.2.5 using Microsoft Store
```

### Actual behavior

```console
I'm forced to uninstall everything (and lose my customization) then re-install 7.2.5
```

### Environment data

```powershell
n/a
```

### OS Data

```powershell
Windows 11 Enterprise
```

### Windows update log

```markdown
see screenshot
```

### Visuals

![image](https://user-images.githubusercontent.com/157666/174983985-8089e7e2-1a22-4b87-852f-3ffccad84ef2.png)

**Comment by dkaszews** [comment]
Can you please explain what you mean by "customization"? I am not aware of anything outside of `$PROFILE` file which you can easily backup.

**Comment by TravisEz13** [comment]
Use the upgrade function through the store.
https://www.intowindows.com/how-to-update-apps-installed-from-store-in-windows-10/
