### ISSUE TITLE
Allow downloading multiple files with Invoke-WebRequest

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#17554]
### Summary of the new feature / enhancement

Right now there is no way to download multiple files with Invoke-WebRequest, trying to do so with `Invoke-WebRequest -Uri link1,link2` will result in error `Invoke-WebRequest: Cannot convert 'System.Object[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not supported.`, this feature depends on https://github.com/PowerShell/PowerShell/issues/17553

**Comment by jborean93** [comment]
If worse comes to worse you can always use `ForEach-Object -Parallel` which is great for situations like like

```powershell
$url1, $url2 | ForEach-Object -Parallel {
    Invoke-WebRequest -Uri $_ ...
}
```

**Comment by soredake** [comment]
> but not all URIs translate to a sensible / usable file name if I call http://host/service/api/id=123?params and http://host/service/api/id=456?params I'm not sure how reliable one can make a rule for selecting a file name automatically

Curl for example has `-O` for selecting remote file name, wget has `--content-disposition` for the same purpose, and many (if not most) site from which you need to download something (mpv scripts from github in my case) will provide a correct remote file name.

**Comment by jhoneill** [comment]
> Curl for example has `-O` for selecting remote file name, wget has `--content-disposition` for the same purpose, and many (if not most) site from which you need to download something (mpv scripts from github in my case) will provide a correct remote file name.

This is one the cmdlet working group should talk about and  doing something similar is an option



> If worse comes to worse you can always use `ForEach-Object -Parallel` which is great for situations like like

The script block can determine the name and for slow downloads running in parallel is an obvious speed advantage. 
But supporting multiple targets from one call is still desirable - where possible.

**Comment by soredake** [comment]
Can someone reopen this?

**Comment by soredake** [comment]
@jborean93

**Comment by soredake** [comment]
@iSazonov

**Comment by jhoneill** [comment]
@iSazonov   Ilya either this or #17553  (or both) should stay open - I'm putting it in the front of the cmdlet working group and we'll see that happens there. The response might be that the workaround posted here is enough or might be some change to the cmdlet is appropriate but if could wait for that before closing it ?

**Comment by SteveL-MSFT** [comment]
The Cmdlet WG discussed this and agreed that adding concurrency support into the cmdlet is not needed and would add lots of complexity (such as determining the output filenames where not all sites include it in the URL or the header).  PowerShell jobs is intended to be used for parallel execution so we recommend adding an example of how to do this in the Invoke-WebRequest documentation.  That doc issue has been created here: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8998
