### ISSUE TITLE
allow to download file to specified folder with Invoke-WebRequest

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#17553]
### Summary of the new feature / enhancement

Right now there is no way to specify folder in which file will be downloaded, so i propose adding a parameter like `-OutFolder` for it

**Comment by jhoneill** [comment]
`-OutFile c:\temp\foo.html` 

works

**Comment by soredake** [comment]
I know about this..... `-OutFolder` is needed for this https://github.com/PowerShell/PowerShell/issues/17554

**Comment by 237dmitry** [comment]
> works

I think it would be nice to save the downloaded file without specifying its name. Without processing URI.

```powershell
$url = [uri] "https://somesite/somefile.ext"
$url.Segments[-1]
```

**Comment by 237dmitry** [comment]
> But not all URIs work like that.

This is clearly. Since this is not a file download program (like wget or aria2), there is no common solution.

**Comment by jhoneill** [comment]
> > But not all URIs work like that.
> 
> This is clearly. Since this is not a file download program (like wget or aria2), there is no common solution.

Some people will want to use it as a download program. 

If there is a solution which works most of the time it's a "Post a script to the gallery" answer. If there is a solution which works nearly 100% of the time it's an "include it in PowerShell" answer. So I'm trying to understand what the percentage is likely to be -  I make a lot of calls to things where the file name isn't easy to select, but I don't think I'm typical.

**Comment by soredake** [comment]
> If the file is not specified then the file name is taken from the last segment of the url

https://github.com/PowerShell/PowerShell/issues/17554#issuecomment-1162683217

**Comment by soredake** [comment]
Seriously?

**Comment by soredake** [comment]
@iSazonov
