### ISSUE TITLE
What's the purpose of PInvokeDllNames.cs

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#17563]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm wondering what the purpose of https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/PInvokeDllNames.cs, specifically

* Why is there a counter for each entry as a comment
* Why is there a constant for each extern name rather than just the DLL itself
* Why do some things use these constants while others do not
  * https://github.com/PowerShell/PowerShell/blob/2db0fe7207b5e22dc0043434dcb60af438086fb6/src/System.Management.Automation/security/nativeMethods.cs#L491-L493 uses `crypt32.dll`
  * https://github.com/PowerShell/PowerShell/blob/2db0fe7207b5e22dc0043434dcb60af438086fb6/src/System.Management.Automation/security/nativeMethods.cs#L495-L501 uses the onecore constant in `PInvokeDllNames.cs`
* Further to the above, why do these use the one core dll names where others do not

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Error details

```console
N/A
```

### Environment data

```powershell
N/A
```

**Comment by daxian-dbw** [comment]
@KalleOlaviNiemitalo is right on the purpose of constants in this file. Now that only `coreclr` related code is left, the constants in this file is not necessary anymore, but it also doesn't offer much value to remove this file and replace all PInvoke declarations with the API set names -- there could be oversight mistakes when doing the replacement, and it doesn't really worth the review time.

**Comment by jborean93** [comment]
Thanks for the info

**Comment by iSazonov** [comment]
> One thing that would be good to know is why do we allow both the OneCore API names in some cases but still use the DLL name in others

We reverted from OneCore APIs in some cases to get pwsh working on Win7/8.
