### ISSUE TITLE
List Subexpression Operator

### ISSUE THREAD

**Issue by draproctor** [PowerShell/PowerShell#17578]
### Summary of the new feature / enhancement

# Context

A typical problem that PowerShell beginners encounter is gathering an unknown number of objects into a single collection. The beginner will find an example on StackOverflow where someone initializes an empty array and add some objects to it. This novice may end up writing something like this:

```powershell
$movies = @()
$shows = @()
foreach ($video in $videos) {
    if ($video -like 'Movie -*') {
        $movies += $video
    } else {
        $shows += $video
    }
}
```

This solves their immediate problem, but they don't understand that arrays are statically sized. Similarly, a programmer coming from Python or Ruby may also expect the array subexpression operator to in fact be the syntax used to initialize empty, but dynamically sized collections.

These people may encounter a problem down the line where their script is suddenly and inexplicably slow. After some fair googling, they discover that what they're doing is in fact copying and recreating the same collection many times. They may end up doing one of the following to address their problem and scratch their heads as to how they didn't know this sooner.

```
$results = foreach ($thing in $myThings) {
    $thing.SomeMethod('foo')
}
```

Other .NET developers will find themselves using generic lists or other collections in this case. However, there is a new problem:
* You can't use `using namespace` inside a script block passed to `ForEach-Object -Parallel`.
```powershell
PS>  1..10 | ForEach-Object -Parallel {
>>   using namespace System.Collections.Generic
>>   [List[object]]::new()
>> }
ParserError:
Line |
   2 |    using namespace System.Collections.Generic
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A 'using' statement must appear before any other statements in a script.
```
* You can't use the shortened type names inside a multithreaded script block.
```powershell
PS> using namespace System.Collections.Generic
PS> 1..5 | ForEach-Object -Parallel { [List[object]]::new() }
InvalidOperation: Unable to find type [List].
InvalidOperation: Unable to find type [List].
InvalidOperation: Unable to find type [List].
InvalidOperation: Unable to find type [List].
InvalidOperation: Unable to find type [List].
```
* If you need to work around this, typing `[System.Collections.Generic.List[object]]` is very long.

# Proposal

Provide a "list subexpression operator" in the form of `@[]`. 

This new operator is similar to the existing `@{}` and `@()` operators which provide easy access to collections. The brackets are also similar to how you would define a dynamic collection in both Python and Ruby, which would be friendly to new developers. With four keystrokes, it's now trivial to access a generic List in _any_ context. 

### Proposed technical implementation details (optional)

You would expect the list subexpression operator to be similar to the array subexpression operator, so you could use it to initialize an empty `List<object>` and easily add items to it.

```powershell
PS> $list = @[]
PS> $list.GetType().Name
List`1
PS> $list.Add('I am a list!')
```

You could also use it to gather objects into a single `List<object>`.

```powershell
$myFiles = @[Get-ChildItem -Path ~/Documents -Filter *.txt]
```

Like the array subexpression operator, you could add the items of many expressions into a single `List<object>`.

```powershell
$executables = @[
  Get-ChildItem -Path ~/bin -Filter *.exe
  Get-ChildItem -Path ~/another_dir -Filter *.exe
  Get-ChildItem -Path ~/and_another_one -Filter *.exe
]
```

**Comment by 237dmitry** [comment]
$using?
```powershell
using namespace System.Collections.Generic
$list = [List[object]]::new()
1..5 | foreach-object -Parallel { ($using:list).Add($_) }
$list
```

**Comment by draproctor** [comment]
What I posted is a scenario where one might try to initialize a List in a multithreaded use case, not reuse a list between threads as `$using:` would provide.

**Comment by draproctor** [comment]
Didn't mean to close this.

**Comment by 237dmitry** [comment]
> You can't use `using namespace` inside a script block passed to `ForEach-Object -Parallel`

```powershell
1..5 | foreach-object -Parallel {

    [ScriptBlock]::Create("
    
        using namespace System.Collections.Generic
        [List[object]]::new().GetType()
    
    ").Invoke()
}
```

**Comment by MartinGC94** [comment]
There's an old thread about this here: https://github.com/PowerShell/PowerShell/issues/5643

**Comment by draproctor** [comment]
Sorry, I missed this! Thanks for the link.
