### ISSUE TITLE
Format-Table inhibit colouring of column headers

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#17570]
### Summary of the new feature / enhancement

get-process -pid 20256 | format-table -AutoSize
in PowerShell 7 will output the column headings in green

get-process -pid 20256 | format-table -AutoSize | out-file <drive>:\FormatTablePS7.txt -Encoding ascii

Writes the "green" escape sequence to the file
[FormatTablePS7.txt](https://github.com/PowerShell/PowerShell/files/8968551/FormatTablePS7.txt)

Using PowerShell 5 there is no such escape sequences in the output
[FormatTablePS5.txt](https://github.com/PowerShell/PowerShell/files/8968554/FormatTablePS5.txt)

see the results of a hex comparison here:
[HexCompareReport.txt](https://github.com/PowerShell/PowerShell/files/8968555/HexCompareReport.txt)

Unless I have missed it there is no way to turn this escape sequence formatting off in Format-Table PS V7.

I found this because the output of a script I have was messed up due to the escape sequences being written to the output to the file.

### Proposed technical implementation details (optional)

To have an option to output format-table to a file in plan ascii with no added escape sequences the same as it is in PSv5, 

Alternatively:

an option for those that want it to turn format the column header colors in PSv7

**Comment by iSazonov** [comment]
Please try latest pwsh preview.

**Comment by RustyF** [comment]
I just got 7.3.0-preview.5 and it's fixed

**Comment by RG255** [comment]
I have just installed that version to see, it did not run my script as expected. I am not very conversant yet with VSCode and I am having trouble getting the debugger to work and stop on the set breakpoints. Can you advise on what I need to configure to make it work please, I have had no success this afternoon apart from I can get the terminal to run v7.3p5 but I cannot debug the script to see what is going on. Sorry.
