### ISSUE TITLE
Completions directory for PowerShell on Linux

### ISSUE THREAD

**Issue by ajeetdsouza** [PowerShell/PowerShell#17582]
### Summary of the new feature / enhancement

Bash, fish, and zsh all have a completions directory on Linux, where applications can add their completion files. Does PowerShell have anything similar? If not, consider this a feature request.

Bash: `/usr/share/bash-completion/completions/`
Fish: `/usr/share/fish/completions/`
Zsh: `/usr/share/zsh/vendor-completions/`

**Comment by kasini3000** [comment]
For powershell modules, cmdlets, and ps1 scripts, functions: no and no special completion files are required. This is the function of the psreadline module. And this feature is cross-platform.

Other binary command line programs, because they are not developed according to the powershell specification. Completion files are required to guide the psreadline module for completion.

In my opinion, this should be a Q&A issue, not an enhancement.

**Comment by ajeetdsouza** [comment]
@kasini3000 is there a directory where one can put completion files so that they are loaded by default, like the other shells I mentioned?

**Comment by ThomasNieto** [comment]
To add PowerShell argument completers `Register-ArgumentCompleter` [cmdlet](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.2) is used and is usually shipped via PowerShell modules and imported in the session with a [profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2) script.

For Unix completers the PowerShell team created the `Microsoft.PowerShell.PSUnixTabCompletion` [module](https://github.com/PowerShell/UnixCompleters) that uses native completers from zsh and bash.

**Comment by 237dmitry** [comment]
Load scripts from your `$profile` (analog of `~/.bashrc`)

```powershell
 > (gi $profile).ToString()
/home/user/.config/powershell/Microsoft.PowerShell_profile.ps1
```
Modules:
```powershell
 > $env:PSModulePath -split ':'      
/home/user/.local/share/powershell/Modules
/usr/local/share/powershell/Modules
/opt/microsoft/powershell/7/Modules 
```

**Comment by kasini3000** [comment]
Why not talk about your usage scenarios and ideas?

PowerShell scripts, and modules, don't need autocomplete files, and don't need such directories.
Is the advantage of powershell over other shells. It is also the reason why businesses and users use powershell.

**Comment by ajeetdsouza** [comment]
The reason I'm asking is -- I have PowerShell installed on Linux. I use a bunch of command line tools. Some of these binaries have shell completions available in their GitHub repositories. For bash, fish, or zsh, I can simply move these completion files to the required directories and it just works. However, I don't think PowerShell supports something like this, which is why I've raised a feature request.

**Comment by 237dmitry** [comment]
For these purposes, I use auto-completion of the command history. As a rule, frequently used commands are found very quickly, even if they are long (multiline too).

```powershell

  >  Get-PSReadLineKeyHandler | ? Key -match '(Up|Down)Arrow' | fl

Key         : UpArrow
Function    : HistorySearchBackward
Description : Search for the previous item in the history that starts with the current input - like PreviousHistory if the input is empty
Group       : History

Key         : DownArrow
Function    : HistorySearchForward
Description : Search for the next item in the history that starts with the current input - like NextHistory if the input is empty
Group       : History
```

If command in the PSReadline history then `UpArrow` and `DownArrow` will search matching by input of text.

```powershell
  >  help Set-PSReadLineKeyHandler
```
The PSReadline history file is `~/.local/share/powershell/PSReadline/ConsoleHost_history.txt`

**Comment by jhoneill** [comment]
> The reason I'm asking is -- I have PowerShell installed on Linux. I use a bunch of command line tools. Some of these binaries have shell completions available in their GitHub repositories. For bash, fish, or zsh, I can simply move these completion files to the required directories and it just works. However, I don't think PowerShell supports something like this, which is why I've raised a feature request.


You have two routes. 
(1) PowerShell native completers 
(2) As Thomas said above the PowerShell team created the Microsoft.PowerShell.UnixTabCompletion [module](https://github.com/PowerShell/UnixCompleters) that uses native completers from zsh and bash. So configure your binaries to complete in those, load the module, away you go.

**Comment by kasini3000** [comment]
(3) use my 《poweralias》 ，it is  a TUI interface alias ps1 script ，
for win，linux ，ps51，psv7
https://gitee.com/chuanjiao10/powershell/tree/master/win-linux%E9%80%9A%E7%94%A8/poweralias

**Comment by kasini3000** [comment]
(3) use my 《poweralias》 ，it is  a TUI interface alias ps1 script ，
for win，linux ，ps51，psv7
https://gitee.com/chuanjiao10/powershell/tree/master/win-linux%E9%80%9A%E7%94%A8/poweralias

**Comment by sharpchen** [comment]
A standard completion search path could hugely benefit to the ecosystem, software maintainers can manage and package their completion script on upstream, otherwise users will have to pollute their profile and leave the completion out of sync.
Powershell doesn't have many completion sources from community mostly because of this, there's no simple way to manage them, you have to publish them as modules while no declarative way to restore them, and it also pollutes user profile.
I don't want to see a lot of checking statements to ensure a completion modules is installed in my profile.
Just hide them to a simple search path variable, it would be a saver feature.
