### ISSUE TITLE
[7.2.5] PowerShell installer requires restart of PowerToys

### ISSUE THREAD

**Issue by ashemedai** [PowerShell/PowerShell#17584]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PowerShell's installer wants to shut down PowerToys.Run for some reason.

### Expected behavior

```console
Installer installs/updates PowerShell, doesn't touch a running PowerToys.
```

### Actual behavior

```console
PowerShell installer wants PowerToys.Run to be restarted.
```

### Environment data

```powershell
Not applicable.
```

### Visuals

![image](https://user-images.githubusercontent.com/610865/175807051-fd182dcc-2059-47b7-89a7-081b5d603c08.png)

**Comment by eamodio** [comment]
Didn't know it was powertoys, but when installing via `winget` the powershell installer just hangs at "Removing Previous Versions". And after reading this issue, I tried exiting powertoys when it "hung" and then the powershell installer continued successfully.

**Comment by ashemedai** [comment]
@PaulHigin That was my initial thought a while ago and I reported it to [PowerToys](https://github.com/microsoft/PowerToys/issues/8049), granted for PowerLauncher, and the response there was that there is nothing in PowerToys to warrant that.

@crutkas Can you help out here?

**Comment by TravisEz13** [comment]
We have no control here.  Windows installer does the detection.  If any file we install is locked, then the process locking the file will have to be shut down.  This is external and by design.

**Comment by sba923** [comment]
PowerShell 7.2.7's MSI installer needs to stop PowerToys.Run. Annoying.

**Comment by asheroto** [comment]
Agreed, the msiexec switch similar would be `/qb!`.

This causes problems with automated installation.
