### ISSUE TITLE
Updates for native modules pre-packaged with Powershell

### ISSUE THREAD

**Issue by blueboy90780** [PowerShell/PowerShell#17585]
### Summary of the new feature / enhancement

There are a lot of pre-built modules that comes natively with Powershell Core when we install it into our system. These modules are not easy to update, they were not installed from PSGallery, so the "Update-Module" cmdlet from PowerShellGet module does not work. If we want to update an built-in module, we have to force install that module, leaving behind the old version which never gets used. Then we have to manually uninstall that same module.

When we scale this up, for example, trying to update every single pre-built module that comes with powershell core, we'd either have to do this manually for each module or we can write a script, though there is limited resources on available scripts that actually work and are reliable.

It would be much more convenient if this feature can come pre-built instead.

**Comment by blueboy90780** [comment]
Thank you, this has answered my question

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I certainly desire this, because having a consistent way to update every module would ease automation.

Consequently, @blueboy90780, please reopen this, because I do not believe that @PaulHigin's response was entirely negative.

Python's pip allows this despite its modules being available via alternative repositories.

**Comment by iSazonov** [comment]
Core modules are highly integrated with Engine, use internal API and can not be distributed individually.
