### ISSUE TITLE
Add callback feature to `Start-Transcript`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#17588]
### Summary of the new feature / enhancement

Judging from the StackOverflow questions, it appears to me that custom log files implementations are more often used then the native [`Start-Transcript`](https://docs.microsoft.com/powershell/module/microsoft.powershell.host/start-transcript) cmdlet and suspect that this is due to the fact enterprise companies (as the one I am working for) want their own logging facilities which might be a specific log format (e.g. including a specific time stamp per entry) up till writing (specific) entries to a database.

### Proposed technical implementation details (optional)

A `-Script <ScriptBlock>` parameter that refers to a script that is called at each logging event. Within the script (which might need to run in a different scope), I would expect to have access to information (via current item (`$_`)?) as:
- A reference to thr output streams since last event
- The timestamp of the event (basically the current time)
- Transcript properties/parameters (as the `Path` if supplied)
- ...

**Comment by PaulHigin** [comment]
@WG-Security
Working security group discussed this and have concerns about inadvertently exposing sensitive information to arbitrary providers, that may move the data off-box.  PowerShell transcripts captures all data written to the console, which can include secrets, and therefore it is more sensitive to where that data goes.  If we implemented a transcript collection provider architecture, we would have to also include some sort of encryption scheme.

**Comment by SeeminglyScience** [comment]
@PowerShell/wg-powershell-engine reviewed this. We think transcripts are best suited to auditing rather than log writing (even with the proposal to bring it closer to logging).

That said, a custom `Out-Default` or even `PSHost` implementation could accomplish similar results as the proposal (though slightly more involved).
