### ISSUE TITLE
BinderUtils.GetLanguageModeCheckIfHasEverUsedConstrainedLanguage() throws null reference exception

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1758]
Paul Higinbotham:
I found this while debugging a running workflow.  This method (GetLanguageModeCheckIfHasEverUsedConstrainedLanguage()) uses the ExecutionContext object obtained from LocalPipe.GetExecutionContextFromTLS(), but this can return a null value which is not checked.  The result is a null reference exception.  I only saw this on a workflow during a trace call that caught all exceptions so it is not noticed.  But this method should check for a null context and return the correct BindingRestrictions.

**Comment by SteveL-MSFT** [comment]
TFS:8039691

**Comment by joeyaiello** [comment]
@SteveL-MSFT Implications? Relevance?

**Comment by SteveL-MSFT** [comment]
This is code cleanup work

**Comment by iSazonov** [comment]
It was fixed in #2591
