### ISSUE TITLE
 Make the to-Boolean coercion (conversion) of a zero (null) pointer, [IntPtr]::Zero / [UIntPtr]::Zero, evaluate to $false

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17601]
### Summary of the new feature / enhancement

`0`, across all numeric types,  is coerced to `$false`.

By contrast, a zero _pointer_ is coerced to `$true`, which is surprising:

```powershell
[IntPtr]::Zero -eq 0 # -> $true, as expected

# Note: The same applies to [UIntPtr]
[bool] [IntPtr]::Zero # -> !! $true
-not [IntPtr]::Zero   # -> !! $false
```

In other words: an `[IntPtr]` / `[UIntPtr]` instance is currently _always_ coerced to `$true`,
whereas cocercing `[IntPtr]::Zero` /`[UIntPtr]::Zero`  to `$false` would be less surprising and allow for the usual shorthands (`if ($someIntPtr) ...` / `if (-not $someIntPtr) ...`

There should be no backward-compatibility concerns, because the current behavior makes it pointless to evaluate pointers in  a Boolean context (given that the result is _always_ `$true`).

**Comment by rkeithhill** [comment]
WG-Engine discussed this today (7/7/2022).

The WG believes this is a fix for consistency's sake which we decided was not compelling.  And given the lack of requests for this feature and a reasonable workaround (`$ptr -eq [IntPtr]::Zero`), we decided the requested enhancement is not worth pursuing.

**Comment by mklement0** [comment]
Good point, @KalleOlaviNiemitalo, but to me your scenario perfectly exemplifies a [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change: a breaking change worth making for its benefits, given that it is unlikely that existing code is impacted.

@rkeithhill, the upcoming .NET 7+ change that @KalleOlaviNiemitalo points makes it even more compelling to fix the behavior of `[IntPtr]` and `[UIntPtr]`, more fundamentally - see #17677

On a philosophical note re, re the proposed change not being compelling:

PowerShell has amassed a [sizable collection of warts](https://github.com/PowerShell/PowerShell/issues/6745), some of which cannot be fixed if backward compatibility must be maintained.

Leaving warts that _can_ be removed in place ensures that the pain of stumbling upon them is carried forward, tripping up not only newcomers, but even seasoned users who may have stumbled upon them before, but have forgotten about them.

A (reasonable) _workaround_ being available is _not_ sufficient to ease this pain.

(And that a fix wasn't requested doesn't mean that people haven't run into the problem or don't want a fix. Especially pre-open-source, PowerShell users were successfully trained to resign themselves to what they were given and to live with workarounds.)

For that reason, (not-too-breaking) wart removals are compelling _in general_, except perhaps if the implementation effort is too great, which I don't think is the case here.
