### ISSUE TITLE
 Get preference variable values in a compiled cmdlet

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#17604]
#17593

### Summary of the new feature / enhancement

I'm creating a new Runspace inside a compiled cmdlet. I'd like to forward preference variables to the Runspace, so that e.g. verbose prints inside the created Runspace are shown if the caller of my cmdlet passes `-Verbose`.

In an advanced function, the preference variable is accessible as an ordinary `$VerbosePreference` variable. However, these are not available for a compiled cmdlet, where the streams are automatically managed. Is there a way to access the preference variable values, or automatically forward them to another Runspace?

**Comment by jhoneill** [comment]
In a c# cmdlet you should be able to use  `base.GetVariableValue("VerbosePreference")` There are few occasions where this is helpful in a script cmdlet 
```
        [Parameter(DontShow=$true)]
        [ActionPreference]$VerbosePreference = $PSCmdlet.GetVariableValue('VerbosePreference')
```
See https://devblogs.microsoft.com/powershell-community/how-to-have-more-control-of-preferences-in-functions-and-the-role-of-modules-on-inheritance/

**Comment by MatejKafka** [comment]
@jhoneill This does not seem to work – this gets the preference from the parent scope, meaning setting `$VerbosePreference = "Continue"` will work, but passing `-Verbose` will not (`.GetVariableValue("VerbosePreference")` returns `"SilentlyContinue"`).

Test code:
```c#
using System.Management.Automation;

[Cmdlet("Test", "VerbosePreference")]
public class TestVerbosePreferenceCommand : PSCmdlet {
    protected override void BeginProcessing() {
        base.BeginProcessing();
        WriteObject(GetVariableValue("VerbosePreference"));
    }
}
```

**Comment by jhoneill** [comment]
Sorry. What I told you is based on the title, not the body of the question. It will get the variable from outside the cmdlet with a given name. If you want to know if the cmdlet has been run with -Verbose 
`base.MyInvocation.BoundParameters.ContainsKey("verbose")`  will tell you if the cmdlet has been run with -Verbose. 
You may need to combine the two because if it is not run with Verbose, do you want to heed what the preference variable says?

**Comment by MatejKafka** [comment]
Non-ideal, but it works, thanks. :)
