### ISSUE TITLE
Invoke-Item should fallback to ShellExecute if path is not a filesystem path

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#17616]
### Summary of the new feature / enhancement

```powershell
invoke-item https://bing.com
```

This should be equivalent to the cmd.exe `start https://bing.com` which will automatically open that URL into your default browser.  However, PowerShell complains that `https:` is not a valid drive.  There are also other scheme associations that would work like `file://` or anything registered with the shell.

### Proposed technical implementation details (optional)

In the `Invoke-Item` cmdlet, if the path fails with a `DriveNotFoundException`, then fallback to using ShellExecute to allow the shell to try to resolve it to a handler.

**Comment by 237dmitry** [comment]
> This should be equivalent to the cmd.exe `start https://bing.com`

Full equivalent:
```
start https://bing.com
```

**Comment by iSazonov** [comment]
I believe it is more fundamental problem since it is possible to use `:` char on Unix file systems.

**Comment by TobiasPSP** [comment]
The cmdlet working group reviewed this and concluded: 
`Start-Process` is the cmdlet that runs executable code as well as monikers like 'https:' awhere you can submit an *unstructured* executable path and run it through *ShellExecute*-like functionality.
The *-item family of cmdlets on the other hand has a much different deign and works strictly *structured* through means of providers and the drives they expose, exposing just the functionality that the provider authors have implemented.
If you wanted to extend this system for any reason you can add new providers. 
We feel that adding a generic *ShellExecute*-like functionality to `Invoke-Item` would violate the structured provider concept and add attack surfaces without on the other hand adding fundamentally new capabilities. 
For *ShellExecute*-like functionality, plase continue to use the existing `Start-Process`.
