### ISSUE TITLE
A public method with the same name as an explicit interface implementation's method hides the latter, even with different signatures

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17614]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: This is at least conceptually related to #10654, which was ultimately resolved by merely _documenting_ the behavior. Perhaps that is the right answer for this issue too, though the behavior at hand is more baffling - on the other hand, it probably won't arise often in practice.

PowerShell surfaces even _explicit_ .NET interface implementations as if they were direct members of a type, which is convenient and obviates the need for interface casts.

However, if a given type has a  public method that happens to have the same name as, but _different signature_ than a method of an explicit interface implementation, the interface method is _not_ found, despite targeting the right overload.

A real world example is that if you choose to implement `System.Collections.IEqualityComparer` explicitly, PowerShell won't find its `.GetHashCode(object o)` method (except with an interface cast), because the presence of `System.Object.GetHashCode()` hides it.

```powershell
Add-Type @'
using System;

public class Foo1: IFormatProvider {
  // Explicit interface implementation
  object IFormatProvider.GetFormat (Type formatType) {
      return "interface impl1";
  }
}

public class Foo2: IFormatProvider {
  // Explicit interface implementation
  object IFormatProvider.GetFormat (Type formatType) {
      return "interface impl2";
  }
  // Define a public method with the same name, but different signature
  public object GetFormat() {
      return "public member";
  }
}
'@


# OK
# PowerShell finds the method even thought it is part of an explicit interface implementation.
[Foo1]::new().GetFormat([int])

# !! FAILS
# !! Seeingly the public GetFormat() method
# !! hides the interface GetFormat() method, even though it has a different signature.
[Foo2]::new().GetFormat([int])
```

### Expected behavior

```console
interface impl1
interface impl2
```

### Actual behavior

```console
interface impl1
MethodException: /path/to/foo.ps1:27
Line |
  27 |  [Foo2]::new().GetFormat([int])
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find an overload for "GetFormat" and the argument count: "1".
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.5
```

**Comment by rkeithhill** [comment]
WG-Engine discussed this today (7/7/2022).

We agree this is a (low priority) bug and fixing it should be non-breaking. We'd take a fix for this. We are labeling it `Up-for-Grabs`.
