### ISSUE TITLE
Jed Editor locked up when started from PowerShell

### ISSUE THREAD

**Issue by colhountech** [PowerShell/PowerShell#17610]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Tested on macos Monterey 12.4 with default terminal (zsh)

* Install and open jed editor (Ctrl-X, Ctrl-C to quit)
```
% brew install jed
% jed README.md
```
* Start a Powershell and open jed editor 
```
% pwsh
PS /Users/micheal/> jed README.md
```
screen goes blank and displays:
```
loading /usr/local/Cellar/jed/0.99-19/jed/lib/emacs.sl
````
Terminal stops responding to any keyboard input

Process does not respond to SIGHUP, SIGTERM, but can kill with SIGKILL
```
kill -HUP 21938     # no response
kill  -TERM 21938  # no response    
kill -KILL 21938       # pwsh is killed

```

Jed is a very stable and fast editor that acts as a drop in replacement for emacs and is available on most platforms for the past 20 years. 

### Expected behavior

```console
jed editor start normally
```

### Actual behavior

```console
jed screen locks up and only responds to SIGKILL
```

### Error details

```console
no error.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
pwsh console interaction, terminal, may be completely inconsistent with the system shell

try：
Start-Process -FilePath '/usr/bin/nohup' -ArgumentList "sh jed README.md"

or

“jed README.md” | /bin/bash    -----or  your shell like "sh"

**Comment by colhountech** [comment]
I'm sorry, I don't understand. This makes no sense. Can you clarify what this comment means @kasini3000 ?

>
> pwsh console interaction, terminal, may be completely inconsistent with the system shell
> 

does this mean that an editor such as Jed would never work with pwsh?

Is there any way I can help?

**Comment by MatejKafka** [comment]
It may be useful to provide `strace` (or whatever the alternative is on Mac :) ) from the startup, maybe it will become more apparent why it hangs up.

**Comment by kasini3000** [comment]
@colhountech   I'm not sure. I would like to provide a bypass method to try.
