### ISSUE TITLE
"Failed to create CoreCLR, HRESULT: 0x80070008" when using *latest*

### ISSUE THREAD

**Issue by Kralizek** [PowerShell/PowerShell#17624]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In my build script I have a step that spawns a docker container based on the powershell:latest image that fails with the error in the title.

Here is the command executed on the build server

```bash
docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e COMMIT_SHA1=$CIRCLE_SHA1 --network project_default mcr.microsoft.com/powershell pwsh -command '
  Install-Module -Name AWS.Tools.Installer -Force
  Install-AWSToolsModule AWS.Tools.S3 -Force -CleanUp
  Invoke-WebRequest -Uri http://entrypoint-api/docs/v1.0/schema.json -OutFile /tmp/schema.json
  Write-S3Object -File /tmp/schema.json -BucketName "some_bucket" -Key "some_key/$env:COMMIT_SHA1.json" -AccessKey $env:AWS_ACCESS_KEY_ID -SecretKey $env:AWS_SECRET_ACCESS_KEY
'
```

The command has worked without any issue until few days ago. Then we started getting the error specified above: "Failed to create CoreCLR, HRESULT: 0x80070008"

```
Unable to find image 'mcr.microsoft.com/powershell:latest' locally
latest: Pulling from powershell

018f9d1d: Pulling fs layer 
Digest: sha256:844fb73db69ed0bbe82d159d4ba50aea06ef4d42bda766c52f2928683f5c8d09
Status: Downloaded newer image for mcr.microsoft.com/powershell:latest
Failed to create CoreCLR, HRESULT: 0x80070008

Exited with code exit status 137
CircleCI received exit code 137
```

After some testing, I noticed that the issue is only happening when using `latest` which is pointing at `ubuntu-22.04`.

If I use `7.2.0-debian-10`, `7.2-debian-10`, `7.2-alpine-3.14`, `alpine-3.14`, `ubuntu-22.04` it works without any problem.

In issue #13166 it was suggested to set `COMPlus_EnableDiagnostics` to `0`. This didn't help.

### Expected behavior

```console
Being able to run a container with latest image of powershell.
```

### Actual behavior

```console
Container can't start
```

### Error details

```console
Unable to find image 'mcr.microsoft.com/powershell:latest' locally
latest: Pulling from powershell

018f9d1d: Pulling fs layer 
Digest: sha256:844fb73db69ed0bbe82d159d4ba50aea06ef4d42bda766c52f2928683f5c8d09
Status: Downloaded newer image for mcr.microsoft.com/powershell:latest
Failed to create CoreCLR, HRESULT: 0x80070008

Exited with code exit status 137
CircleCI received exit code 137
```

### Environment data
Don't have it.

**Comment by FelixSFD** [comment]
The tag `ubuntu-22.04` doesn't work for me either. (no surprise given that `latest` points to the same version)

```
Status: Downloaded newer image for mcr.microsoft.com/powershell:ubuntu-22.04
mcr.microsoft.com/powershell:ubuntu-22.04
Failed to create CoreCLR, HRESULT: 0x80070008
Process exited with code 137
```

**Comment by anamnavi** [comment]
What version of powershell are you using? I'll look into replicating this my side and resolving soon!

**Comment by Kralizek** [comment]
@anamnavi the faulty command is launched in  a `mcr.microsoft.com/powershell` container.

Basically it's a step of a job in a CircleCI build. The job uses `mcr.microsoft.com/powershell` as executor and itself spawns another container based off the same image.

In our tests we didn't need to change the outer container but just the one we were using to execute those commands.

**Comment by uecasm** [comment]
I'm not the OP, but I'm hitting the same issue (with a simpler script, but the same container).  My host is a relatively ancient Debian box running docker 19.03.  The host does have ~3GB free RAM and running that command on the host just reports a max long value, as does running it inside the container.

Running the full powershell command on a Windows 10 host runs without issues, so it does seem to be something host-specific.  Using a different powershell container also works on my ancient host.

**Comment by Kralizek** [comment]
@anamnavi Here is what I got in the host container

```bash
root@d1e24fe67e4c:~/project# docker run --rm mcr.microsoft.com/powershell
Failed to create CoreCLR, HRESULT: 0x80070008
root@d1e24fe67e4c:~/project# docker-compose up -d
[...]
root@d1e24fe67e4c:~/project# /bin/sh -c 'grep hierarchical_memory_limit /sys/fs/cgroup/memory/memory.stat'
hierarchical_memory_limit 4320133120
root@d1e24fe67e4c:~/project# docker-compose down
[...]
root@d1e24fe67e4c:~/project# /bin/sh -c 'grep hierarchical_memory_limit /sys/fs/cgroup/memory/memory.stat'
root@d1e24fe67e4c:~/project# hierarchical_memory_limit 4320133120
```

**Comment by Kralizek** [comment]
@anamnavi 

Here it is 

[log.txt](https://github.com/PowerShell/PowerShell/files/9134664/log.txt)

**Comment by TravisEz13** [comment]
The log shows a failure loading `/opt/microsoft/powershell/7-lts/libcoreclr.so` which is the CoreCLR itself.

**Comment by daxian-dbw** [comment]
@Kralizek Digging into the error `HRESULT: 0x80070008` points an issue with a syscall being blocked due to `SECCOMP` in an container environment. For example, https://github.com/dotnet/runtime/issues/1634 shows that this error happened when .NET called `sched_setaffinity` to set thread's CPU affinity mask in a Snap confined environment that doesn't have the `process-control` interface.

You will want to read this article: https://www.linuxserver.io/blog/anatomy-of-an-issue, which points out a similar problem due to using old versions of Docker engine. Their resolution may be helpful to you: https://docs.linuxserver.io/faq#jammy.

**Comment by Kralizek** [comment]
@daxian-dbw thanks for the reply. Do you have an idea why older images and images based off different distributions like alpine don't suffer of the same problem?

**Comment by daxian-dbw** [comment]
I'm not sure, but article I referenced to has the following that may be an explanation:
> The problem is that if a new syscall gets introduced but Docker doesn't have it included in the profile then your containers can't use it and if, as in this case, the syscall replaces an older one, new distros using it will break previously functional containers.

Does either of the resolutions suggested at https://docs.linuxserver.io/faq#jammy work for you?

**Comment by Kralizek** [comment]
@daxian-dbw I'll try when I get back to work. Currently on vacation

**Comment by Pentadome** [comment]
```docker-compose
    deploy:
      resources:
        limits:
          pids: 1
```

accidently had the same pids twice in my docker-compose.yml, causing this error.
