### ISSUE TITLE
Please add option to disable auto completion

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#17635]
### Summary of the new feature / enhancement

The latest version of the PowerShell extension's integrated console comes with an Auto Completion feature:

![PS Auto Complete](https://user-images.githubusercontent.com/9283914/177522337-923df358-d9af-45ad-b7cc-b3b7bf3e441e.png)

I strongly feel distracted from this auto completion feature while I'm typing. Yet, I couldn't find a setting to disable the auto completion feature.

Please add a Boolean setting to disable the Auto Completion feature.

**Comment by MatejKafka** [comment]
`Set-PSReadLineOption -PredictionSource None`

**Comment by MatejKafka** [comment]
> or remove-module psreadline

You quite definitely don't want to do that, you'll lose most keyboard shortcuts, syntax highlighting, searching,...

**Comment by 3052** [comment]
https://github.com/PowerShell/PSReadLine/issues/4168
