### ISSUE TITLE
Stop-Transcript cmdlet ignores -ErrorAction parameter and always throws on error

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1763]
Both of these throw errors if no transcript has been started:
  Stop-Transcript
  Stop-Transcript -ErrorAction Ignore
## See output below.

PS C:\Users\scbaker> $PSDefaultParameterValues['*:ErrorAction'] = 'Stop'
PS C:\Users\scbaker> Get-Item DoesNotExist
Get-Item : Cannot find path 'C:\Users\scbaker\DoesNotExist' because it does not exist.
At line:1 char:1
- Get-Item DoesNotExist
- ~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\Users\scbaker\DoesNotExist:String) [Get-Item], ItemNotFoundException
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
    PS C:\Users\scbaker> Stop-Transcript
    Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
    At line:1 char:1
- Stop-Transcript
- ~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
  - FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand
    PS C:\Users\scbaker> Get-Item DoesNotExist -ErrorAction Ignore
    PS C:\Users\scbaker> Stop-Transcript -ErrorAction Ignore
    Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
    At line:1 char:1
- Stop-Transcript -ErrorAction Ignore
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
  - FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand

**Comment by SteveL-MSFT** [comment]
TFS:7421567

**Comment by JoeDacey** [comment]
try {stop-transcript | out-null} catch {}

**Comment by joeyaiello** [comment]
@SteveL-MSFT are you suggesting here that this should be a non-generic, non-terminating error instead of low-level exceptions like `ItemNotFoundException` and `PSInvalidOperationException`? 

If yes, I think we can move this out with no milestone. It's wonky, but try/catch is a valid workaround today.

**Comment by joeyaiello** [comment]
Also, if the answer to my question is "yes", can you mark it `Up-for-grabs` please? :)

**Comment by SteveL-MSFT** [comment]
Not needed for 6.0.0
