### ISSUE TITLE
Get-ChildItem in Out-GridView with ANSI Escape sequences :-(

### ISSUE THREAD

**Issue by theuserbl** [PowerShell/PowerShell#17636]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using for example PowerShell 7.3.0-preview.5 on Windows 10 21H1.
With PowerShell 7.1.4 it don't work, because it needs the file and directory coloring.
Input then `Get-ChildItem | Out-GridView` on the PowerShell in a directory with subdirectories and *-.exe-files.

### Expected behavior

```console
That a directory called "Downloads" is in the Out-GridView shown as "Downloads".
And that an executable called "program.exe" is in the Out-GridView shown as "program.exe".
```

### Actual behavior

```console
The directory called "Downloads" is in the Out-GridView shown as "[44;1mDownloads[0m".
And the executable called "program.exe" is in the Out-GridView shown as "[32;1mprogram.exe[0m".
```

### Error details

```console
there is no error
```

### Environment data

```powershell
PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.5
PSEdition                      Core
GitCommitId                    7.3.0-preview.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS D:\>
```

### Visuals

<img width="674" alt="outgrid" src="https://user-images.githubusercontent.com/8337032/177521924-636f2d7f-6d06-482d-a57f-f1a1f34a1f4b.png">

**Comment by MatejKafka** [comment]
This is a more general issue – also happens with `ls >out.txt`, `ls | clip`,...

It seems that `ls` unconditionally adds the colors whenever the output is converted to string, without checking if the output actually goes to the terminal.

**Comment by theuserbl** [comment]
@MatejKafka No, if I output it to out.txt it isn't there.

But I don't know, why they are using on any point of the PowerShell Escape sequences.

If I write in C# a program with
```
Console.ForegroundColor=ConsoleColor.Red;
Console.Write("Hello ");
Console.ForegroundColor=ConsoleColor.Yellow;
Console.WriteLine("there!");
```

I can move it to Out-GridView and every point else and there are no escape sequences.

If I write in PowerShell
`Write-Host -ForegroundColor "Red" "Hello " -NoNewLine ; Write-Host -ForegroundColor "Yellow" "there!"`

Thats the way  https://github.com/joonro/Get-ChildItemColor works.
And Get-ChildItemColor is written in PowerShell, creates an colorizes Get-ChildItem output, and it can be output to Out-GridView without ANSO escape sequences.

So why have the current implementation of the Get-ChildItem ANSI escape sequences, when they are not needed and other implementations are possible?

**Comment by MatejKafka** [comment]
@theuserbl Ah, you're right, the `ls >out.txt` scenario must have been fixed somewhere between -preview.2 (which I use) and -preview.5.

**Comment by MatejKafka** [comment]
As for your other points, I think VT color escape sequences might be used to allow easier configuration using `$PSStyle`, but I'm only guessing.

**Comment by StevenBucher98** [comment]
Yes seems to be a bug with the `PSAnsiRenderingFileInfo` experimental feature. The bug does not happen when it is disabled

**Comment by SteveL-MSFT** [comment]
I believe the problem is that `out-gridview` is using the formatdata and not the original object data

**Comment by SteveL-MSFT** [comment]
Trying to see if this is a somewhat easy fix as this would affect any formatting that adds ANSI escape sequences and used with Out-GridView

**Comment by ThomasNieto** [comment]
@SteveL-MSFT this is also impacting `Out-ConsoleGridView` https://github.com/PowerShell/PowerShell/issues/17439. If you fix it for one it may be fixed for both.
