### ISSUE TITLE
Reading host input from a child runspace causes a deadlock when Ctrl-C is pressed

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#17633]
### Steps to reproduce

Buggy code:
```c#
using System.Management.Automation;
using System.Management.Automation.Runspaces;

[Cmdlet(VerbsLifecycle.Invoke, "RunspacePrompt")]
public class InvokeRunspacePrompt : PSCmdlet, IDisposable {
    private readonly PowerShell _ps = PowerShell.Create();

    protected override void BeginProcessing() {
        base.BeginProcessing();
        _ps.Runspace = RunspaceFactory.CreateRunspace(Host);
        _ps.Runspace.Open();
        _ps.AddScript(@"$Host.UI.Write('Input: '); $Host.UI.ReadLine()");
        _ps.Invoke();
    }

    protected override void StopProcessing() {
        base.StopProcessing();
        // this call causes the deadlock
        _ps.Stop();
    }

    public void Dispose() {
        _ps.Runspace?.Dispose();
        _ps.Dispose();
    }
}
```

Steps to reproduce:
1. Create a cmdlet which creates a new Runspace, which:
   - Uses the same `Host` as the main runspace
   - Runs a script that reads from the host (either using `$Host.UI.ReadLine` directly, or by calling `Read-Host`)
   - The cmdlet implements `StopProcessing`, which stops the runspace.
2. Run the cmdlet.
3. When prompted for input, pres Ctrl-C.
4. The input freezes and you have to kill the whole `pwsh` instance.

### Expected behavior

The runspace is stopped and the cmdlet also stops.

### Actual behavior

The input freezes and you have to kill the whole `pwsh` instance.

Interestingly, in PowerShell 5.1, Ctrl-C works correctly the first time, but freezes when you run the cmdlet a second time.

### Error details

It seems to me that the issue is in the `HandleBreak` thread, which gets stuck and cannot stop the runspace when it's waiting for host input.

Stack of both runspace threads:
- The inner runspace thread, blocked waiting for input in `NativeMethods.ReadConsole`:
```
[Managed to Native Transition]
ConsoleControl.NativeMethods.ReadConsole()
ConsoleControl.ReadConsole()
ConsoleHostUserInterface.ReadLineFromConsole()
ConsoleHostUserInterface.ReadLine()
ConsoleHostUserInterface.ReadLine()
InternalHostUserInterface.ReadLine()
[Lightweight Method Call]
UpdateDelegates.UpdateAndExecute1<object, object>()
DynamicInstruction<object, object>.Run()
EnterTryCatchFinallyInstruction.Run() [2]
EnterTryCatchFinallyInstruction.Run() [1]
Interpreter.Run()
LightLambda.RunVoid1<System.Management.Automation.Language.FunctionContext>()
DlrScriptCommandProcessor.RunClause()
DlrScriptCommandProcessor.Complete()
CommandProcessorBase.DoComplete()
PipelineProcessor.DoCompleteCore()
PipelineProcessor.SynchronousExecuteEnumerate()
LocalPipeline.InvokeHelper()
LocalPipeline.InvokeThreadProc()
LocalPipeline.InvokeThreadProcImpersonate()
ExecutionContext.RunInternal()
[Native to Managed Transition]
```
- The main (original) runspace thread, waiting for script completion in `PowerShell.Invoke`:
```
WaitHandle.WaitOneNoCheck()
PipelineBase.Invoke()
Pipeline.Invoke()
PowerShell.Worker.ConstructPipelineAndDoWork()
PowerShell.Worker.CreateRunspaceIfNeededAndDoWork()
PowerShell.CoreInvokeHelper<object, System.Management.Automation.PSObject>()
PowerShell.CoreInvoke<object, System.Management.Automation.PSObject>()
PowerShell.CoreInvoke<System.Management.Automation.PSObject>()
PowerShell.Invoke()
PowerShell.Invoke()
InvokeRunspacePrompt.BeginProcessing()
Cmdlet.DoBeginProcessing()
CommandProcessorBase.DoBegin()
CommandProcessor.DoBegin()
PipelineProcessor.Start()
PipelineProcessor.SynchronousExecuteEnumerate() [2]
PipelineOps.InvokePipeline()
ActionCallInstruction<object, bool, CommandParameterInternal[][], CommandBaseAst[], CommandRedirection[][], FunctionContext>.Run()
EnterTryCatchFinallyInstruction.Run() [2]
EnterTryCatchFinallyInstruction.Run() [1]
Interpreter.Run()
LightLambda.RunVoid1<System.Management.Automation.Language.FunctionContext>()
DlrScriptCommandProcessor.RunClause()
DlrScriptCommandProcessor.Complete()
CommandProcessorBase.DoComplete()
PipelineProcessor.DoCompleteCore()
PipelineProcessor.SynchronousExecuteEnumerate() [1]
LocalPipeline.InvokeHelper()
LocalPipeline.InvokeThreadProc()
LocalPipeline.InvokeThreadProcImpersonate()
PipelineThread.WorkerProc()
ExecutionContext.RunInternal()
[Native to Managed Transition]
```
- The HandleBreak signal handler thread, waiting for **something?** in `PowerShell.Stop`
```
WaitHandle.WaitOneNoCheck()at D:\_\JetBrains Rider\config\config\resharper-host\SourcesCache\ae38ed1b9f125d13c59ee2eaed08dcf53cfb8dc1cefafbef3d16c2be9752f8\WaitHandle.cs:line 139
LocalPipeline.StopHelper()at D:\programming\_cloned\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalPipeline.cs:line 800 [2]
LocalPipeline.ImplementStop() [2]
PipelineBase.CoreStop() [2]
PipelineBase.Stop() [2]
PowerShell.Worker.Stop()
PowerShell.CoreStop()
PowerShell.Stop()
InvokeRunspacePrompt.StopProcessing()
Cmdlet.DoStopProcessing()
PipelineProcessor.Stop()
PipelineStopper.Stop()
LocalPipeline.StopHelper() [1]
LocalPipeline.ImplementStop() [1]
PipelineBase.CoreStop() [1]
PipelineBase.Stop() [1]
Executor.Cancel()
Executor.CancelCurrentExecutor()
ConsoleHost.HandleBreak()
[Native to Managed Transition]
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.2
PSEdition                      Core
GitCommitId                    7.3.0-preview.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The issue also reproduces in 7.3.0-preview.5 and 7.2.5 (stable).

**Comment by MatejKafka** [comment]
Reading through the stack trace again, it seems that `PowerShell.Stop()` called in `HandleBreak` thread runs almost to the end, but gets stuck waiting for the pipeline to finish. My guess would be that the pipeline is stuck waiting for host input and doesn't "notice" that it should end. The question then probably is, why does this work when there's only one runspace involved, but not when there's a nested runspace?

Is it incorrect to call `PowerShell.Stop()` in the `StopProcessing` handler, or is this an internal PowerShell issue and this is supposed to work?

**Comment by fMichaleczek** [comment]
If you use the async methods PowerShell.BeginStop and PowerShell.EndStop, it's working as expected.

![image](https://user-images.githubusercontent.com/6187529/177456064-e356e11f-95e5-4b88-8b07-cd57e12935f3.png)


```
using System;
using System.Management.Automation;
using System.Management.Automation.Runspaces;

[Cmdlet(VerbsLifecycle.Invoke, "RunspacePrompt")]
public class InvokeRunspacePrompt : PSCmdlet, IDisposable {
    private readonly PowerShell _ps = PowerShell.Create();
    protected override void BeginProcessing() {
        base.BeginProcessing();
        _ps.Runspace = RunspaceFactory.CreateRunspace(Host);
        _ps.Runspace.Open();
        _ps.AddScript(@"$Host.UI.Write('Input: '); $Host.UI.ReadLine()");
        Console.WriteLine("Invoking");
        _ps.Invoke();
    }

    protected override void StopProcessing() {
        base.StopProcessing();
        _ps.BeginStop(ar => { _ps.EndStop(ar); /*System.Threading.Thread.Sleep(30000);*/ Console.WriteLine("PS Stopped") ;}, null);
        Console.WriteLine("StopProcessing Done.");
    }

    public void Dispose() {
        _ps.Runspace?.Dispose();
        _ps.Dispose();
    }
}
```

**Comment by MatejKafka** [comment]
@fMichaleczek This almost works, but it seems there's a race condition between the child runspace starting to run another command and getting stopped. Try changing
```c#
_ps.AddScript(@"$Host.UI.Write('Input: '); $Host.UI.ReadLine()");
```
to
```c#
_ps.AddScript(@"$Host.UI.Write('Input: '); $Host.UI.ReadLine(); $Host.UI.Write('Input done.')");
```

At least on my machine, the second input prompt triggers before the runspace is stopped:
![image](https://user-images.githubusercontent.com/6414091/177525309-2c53d5b9-6fb4-4479-be4f-d08d2f0e31ce.png)

**Comment by MatejKafka** [comment]
The race condition I describe above only seems to manifest when .NET methods are used. If the `$Host.UI.ReadLine()` call is replaced with `Read-Host`, the container reliably stops without running the next command. Same when `$Host.UI.Write('Input done.')` is replaced with `Write-Host "Input done."`.

My guess would be that a series of .NET method calls is executed as one block, without checking if the runspace should stop in the meantime, so when the runspace is requested to stop while executing a .NET method, it only stops on the next cmdlet invocation.

I assume that fixing this would probably degrade the performance of blocks of .NET methods, and there's a reasonably simple workaround (using powershell cmdlets instead of .NET methods), so I don't expect this to get fixed.

---

Examples of scripts invoked inside the runspace:

All prints are executed when Ctrl-C is pressed on the input:
```
$out = $Host.UI.ReadLine()
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
```

Nothing is executed after Ctrl-C, as the PowerShell runtime has control in the `Read-Host` cmdlet:
```
$out = Read-Host
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
```

Nothing is executed after Ctrl-C, as the PowerShell runtime receives control in the `Write-Host` cmdlet and stops:
```
$out = $Host.UI.ReadLine()
Write-Host ('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
```

Nothing is executed, as the for loop gives control back to the PowerShell runtime:
```
$out = $Host.UI.ReadLine()
for ($i = 0; $i -lt 10; $i++) {
	$Host.UI.WriteLine('Input done: ' + $out)
}
```

**Comment by MatejKafka** [comment]
I reported the "race condition" described in the last comment in a new issue: #19112. The solution proposed by @fMichaleczek fixes the original issue, as long as you are careful to also avoid #19112.
