### ISSUE TITLE
UnixFileMode property on FileInfo object can be used instead of the PInvoke on Linux

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#17644]
### Summary of the new feature / enhancement

With .NET 7 Preview 6 a new property is added for FileInfo object to show the UnixFileMode. This can be used to calculate the `Mode` string. This would replace the PInvoke done in psl-native. 

### Examples:

**Works for files**

```
PS /mnt/d/PSGit/PowerShell> Get-Item ./build.psm1 | fl UnixMode, UnixFileMode

UnixMode     : -rwxrwxrwx
UnixFileMode : OtherExecute, OtherWrite, OtherRead, GroupExecute, GroupWrite, GroupRead, UserExecute, UserWrite, UserRe              ad
```

**Works for directories**

```
PS /mnt/d/PSGit/PowerShell> Get-Item $pwd | fl unixmode, unixfilemode

UnixMode     : drwxrwxrwx
UnixFileMode : OtherExecute, OtherWrite, OtherRead, GroupExecute, GroupWrite, GroupRead, UserExecute, UserWrite, UserRe             ad
```

**No information about symbolic links**

```
PS /mnt/d/PSGit/PowerShell> Get-Item ./a2.txt | fl UnixMode, UnixFileMode

UnixMode     : lrwxrwxrwx
UnixFileMode : OtherExecute, OtherRead, GroupExecute, GroupRead, UserExecute, UserRead
```

### Proposed technical implementation details (optional)

Use the FileInfo.UnixFileMode property instead of psl-native PInvoke on non-Windows.

**Comment by rkeithhill-keysight** [comment]
Available `System.IO.UnixFileMode` enum values are:
```
None
OtherExecute
OtherWrite
OtherRead
GroupExecute
GroupWrite
GroupRead
UserExecute
UserWrite
UserRead
StickyBit
SetGroup
SetUser
```

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine 
while the missing link info is pretty important, the PInvoke returns quite a bit more information than just the mode data - user/group/size (which is a little different from length) - it also includes the entire common stat structure.
