### ISSUE TITLE
Handle the new WSL filesystem path for the last Windows Build

### ISSUE THREAD

**Issue by fMichaleczek** [PowerShell/PowerShell#17640]
### Summary of the new feature / enhancement

The PR https://github.com/PowerShell/PowerShell/pull/13120 added a feature on Windows so that the paths of scripts hosted in WSL are recognized as in the computer security zone.

Over the last builds of WSL, paths have been added:

WSL Release Change (default in bold)
| Initial  | 20175 | 21354
| ------------- | ------------- | ------------- |
| **\\\wsl$**  | \\\wsl$  | \\\wsl$\ |
|   | **\\\wsl**  | **\\\wsl.localhost** |

- WSL Build 20175 : 
  - Change  \\\wsl$ prefix to \\\wsl to support URI parsing. 
  - The old \\\wsl$ path is still supported.
[WSL/release-notes#build-20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175)

- WSL Build 21354 : 
  - Switch the \\\wsl prefix to \\\wsl.localhost to avoid issues when there is a machine on the network named "wsl". 
  - \\\wsl$ will continue to work.
[WSL/release-notes#build-21354](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-21354)

https://github.com/PowerShell/PowerShell/issues/13106 is came back depending on Windows version and channel.

### Proposed technical implementation details (optional)

- Append the path \\\wsl.localhost to the computer security zone.

https://github.com/PowerShell/PowerShell/blob/b5277c0fb771edca57e98b0ebb6faa1ad256f852/src/System.Management.Automation/engine/Utils.cs#L736

- Support both path : 
```
# Execute a script inside the home Ubuntu-20.04
pwsh.exe -file '\\wsl$\Ubuntu-20.04\home\flavien\test.ps1'
pwsh.exe -file '\\wsl.localhost\Ubuntu-20.04\home\flavien\test.ps1'
```

**Comment by iSazonov** [comment]
The fix should be in
https://github.com/PowerShell/PowerShell/blob/8cc39848bcd4fb98517adc79cdbe60234b375c59/src/System.Management.Automation/utils/ClrFacade.cs#L236-L237
because Host is `wsl.localhost`

Request Security group to approve.

**Comment by PaulHigin** [comment]
@WG-Security
Security working group feels the original change #13120 should be updated to support the new wsl path format along with the old.  We feel the old format `\\wsl$` is potentially problematic but that we need to continue providing support for down level versions.  We understand that this is a defense-in-depth feature and we don't want to introduce a breaking change.

**Comment by fMichaleczek** [comment]
> The fix should be in
> 
> https://github.com/PowerShell/PowerShell/blob/8cc39848bcd4fb98517adc79cdbe60234b375c59/src/System.Management.Automation/utils/ClrFacade.cs#L236-L237
> 
> 
> because Host is `wsl.localhost`

@[iSazonov](https://github.com/iSazonov) \\\wsl$ is an uri and an Unc but written at the first line of the method, maybe because ReadFromZoneIdentifierDataStream (WSL is more trust than the download folder). I can update https://github.com/PowerShell/PowerShell/pull/13120 or rewrite the whole method, but that not the same job. 

```
 internal const string[] WslRootPath =  new[] { @"\\wsl$"; @"\\wsl.localhost\" }; 

if (filePath.StartsWith(Utils.WslRootPath[0], StringComparison.OrdinalIgnoreCase) || filePath.StartsWith(Utils.WslRootPath[1], StringComparison.OrdinalIgnoreCase) )
```

\* WslRootPath need contain an additional slash to deny \\\wsl.localhost*

**Comment by iSazonov** [comment]
@fMichaleczek Feel free to pull PR!

One more question I have is should we address all URLs with `.localhost` suffix and return `SecurityZone.MyComputer`?
