### ISSUE TITLE
Intrinsic .ForEach() method doesn't work with methods / parameterized properties of hashtables

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17649]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: Only `[hashtable]` is affected, not also `[ordered]` hashtables / generic dictionaries.

```powershell
# The call on the *unordered* hashtable fails quietly.
# .ForEach('ToString') would yield an analogous symptom.
(@{ foo = 1 }, [ordered] @{ foo = 2 }).ForEach('Item', 'foo')
```

### Expected behavior

```console
1
2
```

### Actual behavior

```console
2
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.5
```

**Comment by jhoneill** [comment]
Since you're gathering some of the weirder things hash tables do, I imported something which was equivalent to   
`@{locks=1; keys=2}`    Which `.Keys` would you expect to have precedence ?

**Comment by mklement0** [comment]
For it to be consistent with member-access enumeration, the type-native `.Keys` property _should_ take precedence, but it is the other way around, unfortunately (workaround: ` @{locks=1; keys=2}.get_Keys()` or `@{locks=1; keys=2}.psbase.Keys`) - see #7758

**Comment by mklement0** [comment]
For it to be consistent with member-access enumeration, the type-native `.Keys` property _should_ take precedence, but it is the other way around, unfortunately (workaround: ` @{locks=1; keys=2}.get_Keys()` or `@{locks=1; keys=2}.psbase.Keys`) - see #7758

**Comment by jhoneill** [comment]
:-)  No surprise that it's come up before and if anyone knew it , I guess you would.  
 
I got to `get_keys()`  - eventually. But I had to go some serious bafflement and swearing before it dawned on me that  I was getting something back from an API call which got converted into a hashtable which had "keys" as a key.
