### ISSUE TITLE
Start-Process: The parameter '-Verb' is not supported for the cmdlet 'Start-Process' on this edition of PowerShell.

### ISSUE THREAD

**Issue by DzianisMatveyeu** [PowerShell/PowerShell#17645]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run in docker mcr.microsoft.com/powershell:lts-7.2-nanoserver-1809
and try run pwsh as admin `pwsh.exe -Command "& {Start-Process pwsh.exe -Verb "RunAs"}"`

### Expected behavior

```console
Expected run pwsh as admin
```

### Actual behavior

```console
Start-Process: The parameter '-Verb' is not supported for the cmdlet 'Start-Process' on this edition of PowerShell.
```

### Environment data

```powershell
C:\>pwsh.exe -v
PowerShell 7.2.5
```
```


### OS Data

```powershell
nanoserver-1809
```

### Windows update log

```markdown
Get-WindowsUpdateLog: The term 'Get-WindowsUpdateLog' is not recognized as a name of a cmdlet, function, script file, or
 executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by TravisEz13** [comment]
The default user on nano server should have the permissions you need.  If choco is telling you need to run as admin, that code needs to special case nano.
