### ISSUE TITLE
Support for `$global:rprompt` function

### ISSUE THREAD

**Issue by rashil2000** [PowerShell/PowerShell#17641]
### Summary of the new feature / enhancement

Many modern shells like elvish, tcsh, fish, zsh, xonsh, cmd (through Clink) have a feature to display text/information on the far right side of the input line (which disappears if you type a long command). This big and useful feature is missing from PowerShell.

Here's an example gif of the Cmd shell (with Clink) showing right prompt printed at the far end of input line:

![cursor2](https://user-images.githubusercontent.com/46838874/177708539-2ff725fa-e722-4ad6-8408-788b38fd852f.gif)

The right prompt reappears if you erase the long command.

---
Link to documentation of various shells:

- **elvish**: https://elv.sh/ref/edit.html#prompts
- **xonsh**: https://xon.sh/envvars.html#right-prompt
- **fish**: https://fishshell.com/docs/current/cmds/fish_right_prompt.html
- **cmd**: https://chrisant996.github.io/clink/clink.html#right-side-prompt
- **zsh**: https://zsh.sourceforge.io/Doc/Release/Parameters.html#:~:text=This%20prompt%20is%20displayed%20on%20the%20right%2Dhand%20side%20of%20the%20screen%20when%20the%20primary%20prompt%20is%20being%20displayed%20on%20the%20left.
- **tcsh**: https://linux.die.net/man/1/tcsh#:~:text=The%20string%20to%20print%20on%20the%20right%2Dhand%20side%20of%20the%20screen%20(after%20the%20command%20input)%20when%20the%20prompt%20is%20being%20displayed%20on%20the%20left.

### Proposed technical implementation details (optional)

This is my current rudimentary workaround:

```powershell
$curr_prompt_func = $Function:prompt

function global:rprompt {
  param($text)
  $oc = $Host.UI.RawUI.CursorPosition
  $Host.UI.RawUI.CursorPosition = New-Object System.Management.Automation.Host.Coordinates ($Host.UI.RawUI.WindowSize.Width - $text.Length),$Host.UI.RawUI.CursorPosition.Y
  $Host.UI.Write($text)
  $Host.UI.RawUI.CursorPosition = $oc
}

function global:prompt {
    rprompt (Get-Date -Format "HH:mm:ss")
    return $curr_prompt_func.Invoke()
}
```

**Comment by rashil2000** [comment]
> > This big and useful feature is missing from PowerShell.
> 
> You can write your own prompt function.
> 
> ![ss-20220707130122](https://user-images.githubusercontent.com/78153320/177748351-a626985d-9cd8-4bd4-87ca-fb2ee231c0e1.png)

No, I'm talking about right-hand-side (w.r.t. the input line) prompt. Your example shows left side prompt.


The current workaround I use quite hacky and is not built into PowerShell (unlike other shells).

**Comment by jhoneill** [comment]
As someone who tries to reduce the amount of stuff which is competing for my eye, this request baffles me - more text jumping about in more places - no thanks. But, hey, different work styles,   -  as a quick way you can do this
```
function prompt {"PS>{0,$($Host.UI.RawUI.WindowSize.Width - 4 )}     `e[1A"-f $executionContext.SessionState.Path.CurrentLocation} 
````
This makes the prompt text <host width -1> characters wide, and adds  enough spaces at then to put the cursor after PS> and moves up one row. 

The text on the right gets overwritten but it isn't cleanly tidied up - that would need something added to psreadline.

**Comment by rashil2000** [comment]
> This makes the prompt text <host width -1> characters wide, and adds enough spaces at then to put the cursor after PS> and moves up one row.

Thanks for the workaround! But yes I do feel something more robust for this should be in built.

**Comment by 237dmitry** [comment]
>> I'm talking about right-hand-side (w.r.t. the input line) prompt. Your example shows left side prompt.

> Thanks for the workaround!

If you want the input text not to overwrite the information on the right side of prompt line you can do blank prompt (then you press enter without command).

![ss-20220707180650](https://user-images.githubusercontent.com/78153320/177807480-32e62eee-2c04-4f25-94f5-b2c1dfad8cd0.png)

**Comment by kasini3000** [comment]
>function prompt {"PS>{0,$($Hos

vvvvvvvvvvery good, good for my command line mahjong game. it‘s not start devel yet.

**Comment by rashil2000** [comment]
This is a feature request - why was this closed by the bot? 

It needs correspondence from the maintainers.

**Comment by kilasuit** [comment]
Personally I think that this is something that could be expanded on in docs on how to customise your prompt, as there is no real need, that I can see, in having this not fully contained within the prompt itself and being an additional thing that's needed

**Comment by theJasonHelmick** [comment]
Thank you @rashil2000 for this issue.  The Interactive Working Group has reviewed this and we think there are challenges in creating the right side behavior you're looking for.    As a note - This issue is for the module PSReadLine.
