### ISSUE TITLE
Intermittent CLI failure: "assertion failed [block != nullptr]: BasicBlock requested for unrecognized address"

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17655]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:

* This happens as of PowerShell Core 7.3.0-preview.5, but not in 7.2.5
* It happens on an M1 Mac (ARM CPU) - haven't looked for it on other platforms.
* It happens _intermittently_, hence the repetition of the command below.
* I don't know if PowerShell or perhaps .NET is to blame.

```powershell
1..1e2 | % { pwsh -nop -c '"hi"' }
```

### Expected behavior

```console
hi 
... # repeated 100 times in total
```

### Actual behavior

```console
hi
...
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
...
hi
...
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
hi
...
```

### Error details

_Intermittently_, you'll see the following error message - sometimes `hi` prints, sometimes it doesn't:

```none
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
```

### Environment data

```powershell
PowerShell Core v7.3.0-preview.5 (.NET 7.0.0-preview.5.22301.12) on macOS 12.4, on an M1 (ARM) MacBook Pro.
```

**Comment by kasini3000** [comment]
hi, I use win10 x86 platform and can't reproduce it.
anybody try it on win,linux vm on mac?

**Comment by StevenBucher98** [comment]
If I copy directly the code: `1..1e2 | % { pwsh -nop -c '"hi"' }` I get:

`hi: The term 'hi' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.` 

but if I rather do something like this `1..1e2 | % { pwsh -nop -c Write-Host "hi" }` seems to work fine. I am Windows 11 x64 and 7.3.0-preview5

**Comment by mklement0** [comment]
Thanks, @kasini3000  and @StevenBucher98:

I realized that I was inadvertently running the x64 version of PowerShell on my M1 (ARM64) Mac (using the Rosetta 2 emulation environment), and it seems that the problem only occurs there.

 * As an aside: This happened because the installation script currently isn't ARM-aware on non-Windows platforms:
   * #17663

Since this is an exotic setup, I presume it isn't worth pursuing, so I'm closing this.

---

As for `1..1e2 | % { pwsh -nop -c '"hi"' }` not working for you, @StevenBucher98.
This implies that you've either turned off the `PSNativeCommandArgumentPassing` experimental feature or you've set `$PSNativeCommandArgumentPassing` to `Legacy`.

 * I was going to suggest `1..1e2 | % { pwsh -nop -c  { "hi" } }` as the simplest (albeit slower) workaround, which caused me to stumble upon this:
    * #17665
