### ISSUE TITLE
Obscure failure of the CLI with repeated script-block based invocations, on Windows only

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17665]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: 

* I'm seeing the following only on _Windows_ (x64), and neither on an Intel nor on an M1 Mac...
* ... and only preview.5

Repeated invocations of the CLI with a script block eventually fail.

```powershell
(1..40 | % { pwsh -nop -c { "hi" } } | Measure-Object).Count
```

### Expected behavior

```console
40
```

### Actual behavior

```powershell
32  # plus 8 duplicates of the error below.
```

### Error details

```console
-encodedCommand: The term '-encodedCommand' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

### Environment data

```powershell
PowerShell Core 7.3.0-daily20220707.1  on W10 21H2 (x64)
PowerShell Core 7.3.0-preview.5 on W10 21H2 (x64)
```

**Comment by iSazonov** [comment]
It seems daily build is on Preview6 already. Can you reproduce the issue on daily build?

**Comment by mklement0** [comment]
Yes, it happens with daily build 7.3.0-daily20220707.1  as well.

**Comment by iSazonov** [comment]
I can reproduce only with Release build (in Debug no problem).

/cc @daxian-dbw @SteveL-MSFT

**Comment by SeeminglyScience** [comment]
Interestingly it does not occur when `-c` is omitted (for me anyway). FWIW you do typically want to omit `-c` if you're using the minishell syntax (though this should ofc still be fixed).

**Comment by SeeminglyScience** [comment]
Was talking this over with @JamesWTruher and he discovered that for whatever reason when it starts failing it's passing the `-c` *as well as* the `-encodedCommand`. The minishell parameter binder is *supposed* to remove `-c` from the args passed to the new process.

Still working out why.

**Comment by SeeminglyScience** [comment]
Tracked it down to a change in .NET (dotnet/runtime#72550), looks like an easy fix 🎉. We'll track it there.
