### ISSUE TITLE
Update-Help fails to update 2 modules on Windows 10 Pro x64

### ISSUE THREAD

**Issue by nogeekleftbehind** [PowerShell/PowerShell#1766]
## Steps to reproduce

Install PowerShell_6.0.0.8.msi 
PowerShell 6 as an Administrator
Run Update-Help
## Expected behavior

Expected that all modules will update help successfully
## Actual behavior

PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Cannot load PSReadline module.  Console is running without PSReadline.
PS C:\Program Files\PowerShell\6.0.0.8> update-help
update-help : Failed to update Help for the module(s) 'NetworkControllerDiagnostics, StorageReplica' with UI culture(s)
{en-US} : One or more errors occurred. (An error occurred while sending the request.)
At line:1 char:1
- update-help
- ~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
  - FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
## Environment data

Name                           Value

---

SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.8
CLRVersion
BuildVersion                   3.0.0.0

``` powershell
> $PSVersionTable

```

**Comment by kilasuit** [comment]
These are new modules available in the TP's of Server 2016 if I'm not mistaken?

If so then this do you get this issue using the inbox version of PowerShell on there or not?

If so then this would need to be reported on UserVoice so that it can hopefully be corrected before 2016 Launch

**Comment by Liturgist** [comment]
Update-Help works well on Windows 10 Pro 5 with 6.0.0-alpha.10.

Update-Help does not work well on Ubuntu 16.04 with 6.0.0-alpha.10.

```
PS /home/pwatson> Update-Help                                                   
     Update-Help : Failed to update Help for the module(s)                      'Microsoft.PowerShell.Core, Microsoft.PowerShell.Host, e                        Microsoft.PowerShell.Management, Microsoft.PowerShell.Security,                 Microsoft.PowerShell.Utility' with UI culture(s) {en-US} : The type oooooooooo] initializer for                                                                 'System.Management.Automation.Internal.CabinetExtractorFactory' threw an 
exception.
At line:1 char:1
+ Update-Help
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.Upd 
   ateHelpCommand

```

**Comment by joeyaiello** [comment]
This has been fixed.

**Comment by joeyaiello** [comment]
Also, any future Server help module failures should be reported to https://github.com/MicrosoftDocs/windows-powershell-docs
