### ISSUE TITLE
New syntax for invoking generic methods doesn't support overload reporting when invoked without parentheses

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17668]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Invoking a method name without parentheses (without actually _calling_ the method) is a convenient reflection feature in PowerShell; e.g. `(42).ToString` lists all overloads of the `[int]` type's `.ToString()` method.

However, this doesn't work with the new-in-7.3 syntax (see [about_Calling_Generic_Methods](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Calling_Generic_Methods)) for calling generic methods with explicit type arguments (e.g., `[Array]::Empty[int]()` to create an empty `[int[]]` array):

```powershell
[Array]::Empty         # OK without type argument
[Array]::Empty[int]    # !! BROKEN: treats [int] as an *index* expression
```

### Expected behavior

```console
OverloadDefinitions
-------------------
static T[] Empty[T]()

static int[] Empty[int]()
```

### Actual behavior

```console
ParserError: ...
Line |
  51 |  [Array]::Empty[int]
     |                 ~
     | Array index expression is missing or not valid.
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.5
```

**Comment by vexx32** [comment]
My memory's a little hazy here (@daxian-dbw may recall better than I) but I think this was a necessary concession to ensure that index operations on static members would continue to work? 🤔

**Comment by kborowinski** [comment]
I think it's related to the [following issue](https://github.com/PowerShell/PowerShell/issues/16870#issuecomment-1054848038).

**Comment by daxian-dbw** [comment]
The reported issue is the by-design behavior. Please see the issue pointed to by @kborowinski and the PR description of the fix: https://github.com/PowerShell/PowerShell/pull/16937.

**Comment by mklement0** [comment]
Thanks, @daxian-dbw:

* If this assessment stands, please ensure that this limitation is documented in the new conceptual [about_Calling_Generic_Methods](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Calling_Generic_Methods) help topic

* However, I don't see a connection between this issue and the ones you and @kborowinski point to, given that they seem to relate to using _nested_ type literals or _expressions_ inside what could be interpreted as the type arguments of generic method calls - can you explain?

**Comment by daxian-dbw** [comment]
See the `And allowing to declare generic arguments for property causes unexpected behaviors:` part in https://github.com/PowerShell/PowerShell/issues/16870#issuecomment-1054848038, and also the `Besides, there is no point to allow declaring generic arguments for a property.` part in https://github.com/PowerShell/PowerShell/pull/16937.

Now that I read them again, I'd say that's why the parsing of `[Array]::Empty[int]` or `"string".Length[nonexis]` was removed, but not why `[Array]::Empty[int]` cannot be made work -- return the generic parameter resolved method signature. Of course, a lot more validations will be needed to make sure it works only for method group that support generic parameter types.
