### ISSUE TITLE
Align the behavior of IntPtr / UInPtr with .NET 7's new behavior of becoming numeric types (allowing pointer arithmetic)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17677]
### Summary of the new feature / enhancement

As @KalleOlaviNiemitalo pointed out in the conceptually related #17601, .NET 7 has decided to make `[IntPtr]` proper _numeric types_ with support for arithmetic, for better low-level support of working with pointers:

```csharp
// Error up to .NET 6, because '+' wasn't defined for pointer types.
// In .NET 7, performs arithmetic and returns an IntPtr instance.
 IntPtr.Zero + IntPtr.Zero
```

(Previously, it was _C#_ that allowed arithmetic via its `nint` and `nuint` types, which, while mapped to `IntPtr` and `UIntPtr`, _overlaid_ them with arithmetic support. This behavior is now moving in the BCL/CLR, and going forward `nint` and `nuint` are mere _aliases_ for `IntPtr` and `UIntPtr` - see https://github.com/dotnet/csharplang/issues/6065)

In short: `IntPtr` will behave like `Int32` / `Int64` and `UIntPtr` like `UInt32` / `UInt64`  in 32-bit/64-bit processes

PowerShell should align with these changes in two respects:

* Allow arithmetic that preserves the pointer type, if possible.

  * Currently, PowerShell does do arithmetic, but (a) it doesn't preserve the pointer type and (b) it is _broken_; e.g. `[IntPtr] 2147483648 + 0` causes an overflow exception(!) even in 64-bit processes (`2147483648` is `[int]::MaxValue+1`, which shouldn't cause an overflow in 64-bit processes where `IntPtr` is essentially `Int64` (`[long]`).

* Treat `IntPtr.Zero` / `UIntPtr.Zero` _as a number_ that is therefore `$false` when coerced to a Boolean, as originally proposed in #17601
  * Currently, `[bool] [IntPtr]::Zero` and `[bool] [UIntPtr]::Zero` are unexpectedly `$true`

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this and concluded we should not special case `IntPtr`, but instead we should look into the new generic math interfaces. I've opened #18915 to track that.
