### ISSUE TITLE
In-line splatting

### ISSUE THREAD

**Issue by saladproblems** [PowerShell/PowerShell#17706]
### Summary of the new feature / enhancement

Currently you must define a variable to splat parameters to a command. Allow splatting a hashtable directly.

This could simplify syntax and reduce mistakes from splatting in loops where the current loop fails to update the splatted variable and the wrong iteration's parameters are applied.

Additionally, it may to provide parameter tab completion for an in-line splat than a variable defined before the function is called.

### Proposed technical implementation details (optional)

```
Invoke-Command @{
    ComputerName = 'computer1','computer2','computer3'
    ScriptBlock = { 'my name is {0}' -f $env:computername }
    ErrorAction = 'stop'
}

```

**Comment by iRon7** [comment]
I think this is a duplicate with: #10073

**Comment by saladproblems** [comment]
You're absolutely right. I searched for splatting and hashtables, but didn't see it at the time.
