### ISSUE TITLE
PowerShell should be better able to reveal developer information on an unknown object

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#17701]
### Summary of the new feature / enhancement

PowerShell `Write-*` cmdlets are sending information to the related output streams which (all?) are eventually displaying information in a way the end-user would probably prefer to receive it but as a script *developer*, the way this is displayed is often misleading.

For a new PowerShell scripter, a known pitfall is the object enrolment were is unclear what type is actually being output from the pipeline in the case of a single item.
And there are a lot of different object types that *all* show the same "**empty**" result as e.g. `''`, `$Null`, `@()`, `@('')`, `@($Null)`,`@($Null, '')`,

See e.g. [`#17683` $null should be indicated by a blank line, especially when within an array](https://github.com/PowerShell/PowerShell/issues/17683).

### Proposed technical implementation details (optional)

It would be nice if e.g. the `Write-Debug` cmdlet would an addition `-Object` parameter that reveals *developer* information about a specific object.

Currently, any argument other than a string provided to the `Write-Object` cmdlet results in an error:

```PowerShell
$Name  = 'John', 'Doe'
Write-Debug $Name
```
> **Write-Debug: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.**

What I would like to see instead (as a developer), is a formatted object that doesn't leave any room for misinterpretation (e.g. the same way as it is required to be formatted for the PowerShell engine)

**Wishful thinking:**

```PowerShell
$Name  = 'John', 'Doe'
Write-Debug $Name
'John',
'Doe'
```

```PowerShell
$Name  = $Null
Write-Debug $Name
$Null
```

```PowerShell
$Name  = ''
Write-Debug $Name
''
```

```PowerShell
$Name  = @()
Write-Debug $Name
@()
```

```PowerShell
$Name  = @('', $Null)
Write-Debug $Name
@('', $Null)
```

This could go as deep as something prototyped here: [ConvertTo-Expression](https://github.com/iRon7/ConvertTo-Expression) which definitely doesn't make it an easy request.

**Comment by fMichaleczek** [comment]
I think you are asking for new Format-* cmdlets.

Format-Hex is nice for string, char and valuetype, but not good with null

Format-Custom is nice with object, hashtable and collections.

A command Format-Pretty should be a good feature.

```powershell
PS C:\> $Name  = 'John', 'Doe'
PS C:\> $Name | Format-Hex

   Label: String (System.String) <4BDBB0C1>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 4A 6F 68 6E                                     John

   Label: String (System.String) <4A3432CE>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 44 6F 65                                        Doe

PS C:\> (Get-UICulture).Calendar | Format-Custom -Depth 1

class GregorianCalendar
{
  MinSupportedDateTime =
    class DateTime
    {
      Date = 1/1/0001 00:00:00
      Day = 1
      DayOfWeek = Monday
      DayOfYear = 1
      Hour = 0
      Kind = Unspecified
      Millisecond = 0
      Microsecond = 0
      Nanosecond = 0
      Minute = 0
      Month = 1
      Second = 0
      Ticks = 0
      TimeOfDay = 00:00:00
      Year = 1
      DateTime = Monday, January 1, 0001 00:00:00
    }
  MaxSupportedDateTime =
    class DateTime
    {
      Date = 12/31/9999 00:00:00
      Day = 31
      DayOfWeek = Friday
      DayOfYear = 365
      Hour = 23
      Kind = Unspecified
      Millisecond = 999
      Microsecond = 999
      Nanosecond = 900
      Minute = 59
      Month = 12
      Second = 59
      Ticks = 3155378975999999999
      TimeOfDay = 23:59:59.9999999
      Year = 9999
      DateTime = Friday, December 31, 9999 23:59:59
    }
  AlgorithmType = SolarCalendar
  CalendarType = Localized
  Eras =
    [
      1
    ]

  TwoDigitYearMax = 2029
  IsReadOnly = True
}
```

The base serialization is CliXml, if you want to import/export object, you could export and display CliXml.

```powershell
PS>  (Get-UICulture).Calendar | Export-CliXml -Path $env:TMP/cal.clixml -Depth 1 -Force
PS> Get-Content -Path "$env:TMP/cal.clixml"
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Globalization.GregorianCalendar</T>
      <T>System.Globalization.Calendar</T>
      <T>System.Object</T>
    </TN>
    <ToString>System.Globalization.GregorianCalendar</ToString>
    <Props>
      <DT N="MinSupportedDateTime">0001-01-01T00:00:00</DT>
      <DT N="MaxSupportedDateTime">9999-12-31T23:59:59.9999999</DT>
      <S N="AlgorithmType">SolarCalendar</S>
      <S N="CalendarType">Localized</S>
      <Obj N="Eras" RefId="1">
        <TN RefId="1">
          <T>System.Int32[]</T>
          <T>System.Array</T>
          <T>System.Object</T>
        </TN>
        <LST>
          <I32>1</I32>
        </LST>
      </Obj>
      <I32 N="TwoDigitYearMax">2029</I32>
      <B N="IsReadOnly">true</B>
    </Props>
  </Obj>
</Objs>

PS> Import-Clixml  -Path "$env:TMP/cal.clixml"

MinSupportedDateTime : 1/1/0001 00:00:00
MaxSupportedDateTime : 12/31/9999 23:59:59
AlgorithmType        : SolarCalendar
CalendarType         : Localized
Eras                 : {1}
TwoDigitYearMax      : 2029
IsReadOnly           : True

```

**Comment by iRon7** [comment]
> `# Could be any statement/cmdlet or even a kind of developer mode`

Second thoughts: I think this should actually controlled from a kind of `SupportsDebugging` [cmdlet binding attribute](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute) which would also cover the pitfall mentioned in #15781 [Strict Write-Output](https://github.com/PowerShell/PowerShell/issues/15781).

Meaning if the `SupportsDebugging` attribute is supplied to an advanced function and the concerned function is invoked with the common `-Debug` parameter, the objects at the end of the success stream will displayed _in PowerShell notation_ rather than end-user strings.

This would imply that most existing cmdlets (that produce objects) might support this `SupportsDebugging` attribute as well in the future. But `write-*` cmdlets should specifically be excluded (except for maybe [`Write-Output`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-output) which in fact -afaik- handles the display output at the end of the pipeline)

**Wishful thinking**

```PowerShell
function MyScript {
    [CmdletBinding(SupportsDebugging=$True)]
    Param( 
    )
    Param ($Parameter1)
    
    Begin{}
    Process{ ConvertFrom-JSON "[]" }
    End{}
}

MyScript

MyScript -Debug
$Null
```

**Comment by rkeithhill** [comment]
WG-Engine discussed this today (8/22/2022).

Such a feature (Format-Pretty|Debug|All|???) would be a good candidate for a community-supplied PowerShell module.  We're not sure using the `-Debug` parameter would be appropriate since that simply enables `Write-Debug` messages to go to the Debug stream.  Those do not go to the Output stream.
