### ISSUE TITLE
Unexpected return value of $Host.UI.SupportsVirtualTerminal

### ISSUE THREAD

**Issue by RuntimeErrorz** [PowerShell/PowerShell#17703]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Input `$Host.UI.SupportsVirtualTerminal` in Windows Terminal

### Expected behavior

```console
PS>  $Host.UI.SupportsVirtualTerminal
True
```

### Actual behavior

```console
PS>  $Host.UI.SupportsVirtualTerminal
False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### The bug's origin
I found this question using oh-my-posh, I have discussed this question in oh-my-posh community, they were sure it's not an issue of oh-my-Posh. They believed the return value of "$Host.UI.SupportsVirtualTerminal" is the key.
### Expected Behavior

The terminal returns `True`. And the terminal's appearance looks like this.
![image](https://user-images.githubusercontent.com/71929239/179397291-a12d9c0c-f128-4d28-9b28-9866d2a1e60d.png)

### Actual Behavior

The terminal outputs `False`. The terminal's appearance looks like this.
![image](https://user-images.githubusercontent.com/71929239/179397275-c95506e4-668a-4bda-a593-91959d555b2c.png)

And it's weird since the "virtual terminal processing" (see [MS docs](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)) should have been enabled by default in Windows Terminal.
Even after I uninstalled oh-my-posh and reinstalled Powershell, `$Host.UI.SupportsVirtualTerminal` still returns `False`. But another computer's `$Host.UI.SupportsVirtualTerminal`  returns `True` at all times.

**Comment by jhoneill** [comment]
> another computer's $Host.UI.SupportsVirtualTerminal returns True at all times.

Indeed 
I just tried this in Windows terminal on my machine with PowerShell 7.3 preview, 7.2, 6.2, and 5.1  and get true at all times.   

Even running PWSH outside of Windows terminal (on Windows 11 - 10 should be the same) I get true. 

**This would seem to machine-specific setup thing rather than a PowerShell bug.** 

I'd create a new profile in Terminal to run `<path>pwsh.exe -noprofile`  and see if it is a profile setting - I'd point the finger at oh-my-posh, but that's not based on nay actual evidence.

**Comment by RuntimeErrorz** [comment]
> I'd create a new profile in Terminal to run `<path>pwsh.exe -noprofile` and see if it is a profile setting

I tried but it still returns `False`, even open Powershell directly.
![image](https://user-images.githubusercontent.com/71929239/179526812-9a7f362e-f47a-4e04-8d93-8f701a1ebeb0.png)

**Comment by SeeminglyScience** [comment]
Do you have any value in `$env:TERM`?

**Comment by RuntimeErrorz** [comment]
Oh, thank you very much, I solve the problem by deleting this environment variable.
