### ISSUE TITLE
Register-PackageSource: Doesn't save credentials to `nuget.config` file

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#17712]
### Current Behavior

When I enter …
```powershell
Register-PackageSource -Name 'Test' -Location 'https://test.contoso.com/' -ProviderName 'NuGet' -Credential (Get-Credential) -ForceBootstrap -Trusted
```
… no credentials are getting saved to the `nuget.config` file.

### Expected Behavior

If the `Credential` argument is provided with `ProviderName` being "NuGet", `Register-PackageSource` should save provided credentials to `nuget.config` file.

**Comment by ThomasNieto** [comment]
The command and provider isn't in this repo. Please log your issue here: https://github.com/OneGet/NuGetProvider

**Comment by SetTrend** [comment]
Thanks, guys, for pointing me to the right direction!

I now created an issue [here](https://github.com/OneGet/NuGetProvider/issues/67).
