### ISSUE TITLE
Error import ActiveDirectory module

### ISSUE THREAD

**Issue by drano** [PowerShell/PowerShell#17711]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have an issue when importing activeDirectory module.
1- Import-module ActiveDirectory is ok with powershell directly
2- Using Powershell SDK (Microsoft.PowerShell.SDK 7.2.5) in C#, import-module ActiveDirectory fails with error message

### Expected behavior

```console
Import-module ActiveDirectory ok with Microsoft.PowerShell.SDK
```

### Actual behavior

```console
Error message
```

### Error details

```console
System.Management.Automation.RuntimeException: The following error occurred while loading the extended type data file:
, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ActiveDirectory\ActiveDirectory.Types.ps1xml(231) : Error in type "Microsoft.ActiveDirectory.Management.ADAuthenticationPolicySilo": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lawlercoppter** [comment]
Any updates on this?
