### ISSUE TITLE
Automation: Remoting ScriptBlock is not convertible from string

### ISSUE THREAD

**Issue by Zetanova** [PowerShell/PowerShell#17735]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to execute a simple pipe with an `foreach-object` remotely from a c# net6

The `ScriptBlock` parameter get converted to a string and throws an conversion exception on the remote site.

I found no possibility to do.

The remote site is linux pwsh 7.2.5

```
cmd = new Command("Get-ChildItem");
            cmd.Parameters.Add("Path", "/dev/disk/by-id/scsi-*");
            commands.Add(cmd);

            cmd = new Command("Foreach-Object");
            cmd.Parameters.Add("Process", ScriptBlock.Create("Join-Path -Path $_.Directory -Child $_.Target -Resolve"));
            commands.Add(cmd);
            
            //this is executed on a linux remote runspace
            var path = await power.InvokeAsync(commands).FirstOrDefaultAsync();
                   
´´´
               

### Expected behavior

```console
execute the foreach-object script block remotely
```

### Actual behavior

```console
error
```

### Error details

```console
.Management.Automation.RemoteException : Cannot bind parameter 'Process'. Cannot convert the "Join-Path -Path $_.Directory -Child $_.Target -Resolve" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
```

### Environment data

```powershell
net6, Microsoft.PowerShell (SDK.7.2.5)
```

**Comment by mklement0** [comment]
Unfortunately and bewilderingly, this behavior was declared to be by design - see duplicate
* https://github.com/PowerShell/PowerShell/issues/11698

**Comment by Zetanova** [comment]
grandiose design,
It is possible to `enter-pssession` into the remote system and execute everything

But with c# and a Runspace and Pipeline its impossible to `Get-ChildItems` + `Join-Path` in a single pipe

**Comment by jborean93** [comment]
An alternative that works in more scenarios is using `ps.AddScript()` like so

```csharp
PowerShell ps = PowerShell.Create();
ps.AddScript("Get-ChildItem -Path $args[0] | ForEach-Object { Join-Path -Path $_.Directory -Child $_.Target -Resolve }");
ps.AddArgument("/dev/disk/by-id/scsci-*");

var path = await ps.InvokeAsync(commands).FirstOrDefaultAsync();
```

Unless I'm mistaken you can also just do `| Select-Object -ExpandProperty FullName` rather than using `Join-Path` here.

**Comment by Zetanova** [comment]
@jborean93  thx for the example

Something changed from pwsh6 to pwsh7 the Target is now suddenly `relative` to `directory` property value

I used it here:
https://github.com/Zetanova/hyperv-csi-driver/blob/726552dc1716ec96996727bd394cdc8bad4b1663/src/hyperv-csi-driver/Infrastructure/HypervNodeService.cs#L102

Because of some bugs in the RunspacePool, I worte my own simple runspace pool management
and view Runspace utility extensions. Maybe you have interest/idea for it.

**Comment by jborean93** [comment]
Weird the `FullName` should be the absolute path, I know the behaviour of `ToString()` on the `FIleInfo` object changed from the file name to the absolute path but the `FullName` property stayed the same.

**Comment by Zetanova** [comment]
I need the target of the symlink and not the path of the symlink to discover the block device by VHDX ID (guid)
It is working now by a workaround, I query Directory and Target first and after execute a second pipe with them.
The `Join-Path` needs to be executed remotely because maybe the local system is running under windows. 

```
PS /root> Get-ChildItem -Path /dev/disk/by-id/scsi-*47f90bea* | fl

    Directory: /dev/disk/by-id

Name           : scsi-36002248047f90bead727987e9c2393f2
Length         : 9
CreationTime   : 7/20/2022 12:54:42 PM
LastWriteTime  : 7/20/2022 12:54:42 PM
LastAccessTime : 7/21/2022 7:57:31 PM
Mode           : l----
LinkType       : SymbolicLink
Target         : ../../sdb
VersionInfo    :

Name           : scsi-36002248047f90bead727987e9c2393f2-part1
Length         : 10
CreationTime   : 7/20/2022 12:54:42 PM
LastWriteTime  : 7/20/2022 12:54:42 PM
LastAccessTime : 7/21/2022 7:57:31 PM
Mode           : l----
LinkType       : SymbolicLink
Target         : ../../sdb1
VersionInfo    :


PS /root> Get-ChildItem -Path /dev/disk/by-id/scsi-*47f90bea* | select FullName

FullName
--------
/dev/disk/by-id/scsi-36002248047f90bead727987e9c2393f2
/dev/disk/by-id/scsi-36002248047f90bead727987e9c2393f2-part1

PS /root>
```

**Comment by jborean93** [comment]
Ah my apologise you are dealing with symlinks and `Target` that's my fault. Please ignore the `-ExpandProperty FullName` stuff.

**Comment by mklement0** [comment]
If memory serves, `.Target` was changed to report the target path _as defined_ rather than _what full path it resolves to_.

To resolve the target to a full path:

Since (at least?) 7.2, you can now use:

```
# $true means: follow to the ultimate target, if the target is itself a symlink.
(Get-Item /proc/self).ResolveLinkTarget($true).FullName
```

Since 7.3.0-preview.2, there's now an ETS `.ResolvedTarget` code property that reports the target's full path as a string; it simply calls `.ResolveLinkTarget($true).FullName`.

```
(Get-Item /proc/self).ResolvedTarget
```

**Comment by daxian-dbw** [comment]
> If memory serves, .Target was changed to report the target path as defined - which is often relative - rather than what full path it resolves to.

Just to link to the issue about this change: https://github.com/PowerShell/PowerShell/issues/13365

**Comment by Zetanova** [comment]
The change on now the extension of features are fine,

But that someone can't use `Foreach-Object` Command remotely with a pipeline of `Microsoft.PowerShell.SDK` looks like a regression. 

I could really find no option to pass the parameters to `Joint-Path` from the pipeline

And I am working with 
```csharp
AppContext.SetSwitch("System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization", true);`
```

@mklement0 
`ResolveLinkTarget()` is working like it should be:
```
PS /root> (Get-ChildItem -Path /dev/disk/by-id/scsi-*47f90bea*).ResolveLinkTarget($true).FullName
/dev/sdb
/dev/sdb1
```
