### ISSUE TITLE
Slow startup of Powershell Core

### ISSUE THREAD

**Issue by shyney7** [PowerShell/PowerShell#17734]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Start powershell with Windows Terminal

### Expected behavior

```console
startup < 4 seconds on Intel i7 without Module Imports
```

### Actual behavior

```console
startup takes > 4 seconds on intel i7 without any Imports of Modules
startup takes > 6 seconds with the following Imports:
Import-Module oh-my-posh
Import-Module PSReadLine
Import-Module -Name Terminal-Icons

I tried the following:
* added system path variables:
    ** POWERSHELL_TELEMETRY_OPTOUT=1
    ** POWERSHELL_UPDATECHECK_OPTOUT=1
* added pwsh.exe to Windows Defender exceptions
* added C:\Users\username\AppData\Roaming\Microsoft\Windows\PowerShell to Defender exceptions
* disabling Windows Defender SmartScreen
* tried to run ngen.exe install and ngen.exe update with the following scripts:
```
```
[AppDomain]::CurrentDomain.GetAssemblies() | ForEach-Object {
    $path = $_.Location
    if ($path) { 
        $name = Split-Path $path -Leaf
	#sn.exe -Vr $path
        Write-Host -ForegroundColor Yellow "`r`nRunning ngen.exe on '$name'"
        ngen.exe update $path /nologo
    }
}
```

But running ngen on Powershell dll's was giving me errors like "strong name validation failed" so I tried to run sn.exe -Vr but the errors still occurred.

### Error details

```console
no Errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
ngen doesn't work for pwsh since it is based on .Net Core.

You could clean PATH env variable for perf test.

**Comment by kasini3000** [comment]
my drive c is ssd ,typically startup time is less than 1 second，ps5 ，ps7
if you use hdd,try 
defrag c: /x /v /o  /l /k

**Comment by shyney7** [comment]
> my drive c is ssd ,typically startup time is less than 1 second，ps5 ，ps7
> if you use hdd,try 
> defrag c: /x /v /o  /l /k

I'm also using an SSD.

**Comment by shyney7** [comment]
Ok I managed to identify the culprit: its the following prifle config that is causing the high load time:
```
PSVersion    : 7.2.5
Profile      : CurrentUserAllHosts
Path         : C:\Users\username\Documents\PowerShell\profile.ps1
TimeMS       : 4331,2929
```
with the following content:
```
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& "C:\Users\olivei_m\Anaconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
#endregion
```

This was created by using the command conda init powershell I think. But is also needed to be able to use conda commands and manage environments...
