### ISSUE TITLE
SatelliteResourceLanguages

### ISSUE THREAD

**Issue by fMichaleczek** [PowerShell/PowerShell#17740]
### Summary of the new feature / enhancement

As a user I want PowerShell archive size should be more thin.

PowerShell is configured in NeutralLanguage in PowerShell.Common.Props : 
```
    <NeutralLanguage>en-US</NeutralLanguage>
```

But there is a lot of subfolders in the release (30MB for Windows edition) from the satellite ressources : 
![image](https://user-images.githubusercontent.com/6187529/180321249-8283307a-ca69-4aa1-a3b2-07f641021794.png)

### Proposed technical implementation details (optional)

Configure SatelliteResourceLanguages same as NeutralLanguage : 
```
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
```

**Comment by iSazonov** [comment]
Step back from localization? :-)

**Comment by fMichaleczek** [comment]
@iSazonov could you reopen it ?
