### ISSUE TITLE
Compare-Object with [char] instances is unexpectedly case-sensitive by default

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17758]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If `[char]` instances were consistently compared case-insensitively to each other and to strings, all of the following commands would output `0`.

```powershell
# OK: [string] vs. [string]
(Compare-Object ('a') ('A')).Count
# OK: [string] vs. [char]
(Compare-Object ('a') ([char] 'A')).Count
# !! BROKEN: [char] vs. [char]
(Compare-Object ([char] 'a') ([char] 'A')).Count
# !! BROKEN: [char] vs. [string]
(Compare-Object ([char] 'a') ('A')).Count
```

Note that `[char] 'a' -eq [char] 'A'` is `$true` (even though with `-gt`, `-lt`, `...` it is the _code points_ that get compared, resulting in case-sensitive behavior).

#12498 is conceptually related, but would not fix this issue, because use of the `IEquatable<T>` interface would also result in case-sensitive behavior.

### Expected behavior

```console
0
0
0
0
```

### Actual behavior

```console
0
0
2
2
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.6
```

**Comment by 237dmitry** [comment]
When comparing `[char]` converted into `[string]`? `Compare-Object`'s`CaseSensitive` parameter does not affect the result (and this is true behavior for nonstrings, IMO). But:
```
[char] 'a' -eq [char] 'A'     # True
[char] 'a' -ceq [char] 'A'    # False
```

**Comment by mklement0** [comment]
@237dmitry: They're not _technically_ compared as strings with `-eq` (if memory serves, `.ToUpperInvariant()` is called before comparing), but the intent is clearly the same: compare `[char]`s case-INsensitively.

Therefore, `Compare-Object`, which is also built on _equality_ comparison, should behave the same (with `-CaseSensitive` acting as opt-out).

**Comment by 237dmitry** [comment]
Thanks for the clarification.

**Comment by jhoneill** [comment]
> How do chars compare, as chars or as strings? `Compare-Object`'s`CaseSensitive` parameter does not affect the result (and this is expected behavior for non strings, IMO). But:
> 
> ```
> [char] 'a' -eq [char] 'A'     # True
> [char] 'a' -ceq [char] 'A'    # False
> ```

I think `-eq` is always `-ieq` The char type itself only does case sensitive comparisons 
```
PS>  [char]::Equals(([char]'a'),([char]'A'))
False
```
But string comparisons are case sensitive by default with the option to select culture and case sensitivity. 
```
PS>  [string]::Equals(([char]'a'),([char]'A'))
False

PS>  [string]::Equals(([char]'a'),([char]'A'), [System.StringComparison]::CurrentCultureIgnoreCase)
True
```

IEQ might call ToUpper or ToLower on both strings and a chars and compare the result or it might specify the comparison type for strings.    My hunch  is `Compare-Object` is only requesting insensitive for strings and not for chars. 
Because there is only a `-CaseSensitive` option for  `Compare-Object` the natural expectation is chars and strings both use case insensitive comparisons _by default_ and only case sensitive when the switch is specified.
