### ISSUE TITLE
New-ScheduledTaskTrigger should support advanced setting RepeatTask RepeatDuration

### ISSUE THREAD

**Issue by NaitWatch** [PowerShell/PowerShell#17756]
### Summary of the new feature / enhancement

As a user i want to schedule a job in the windows task scheduler, that repeats on a more frequent basis that a daily schedule.

### Proposed technical implementation details (optional)

New-ScheduledTaskTrigger
   [-RandomDelay < TimeSpan >]
   -At <DateTime>
   [-DaysOfWeek < DayOfWeek[] >]
   [-Weekly]
   [-WeeksInterval < UInt32 >]
   [-CimSession < CimSession[] >]
   [-ThrottleLimit < Int32 >]
   [-AsJob]
   [< CommonParameters >]

Please add the following parameters to set the advanced setting

[-RepeatTask < TimeSpan >]
[-RepeatDuration < TimeSpan >]

![grafik](https://user-images.githubusercontent.com/97656046/180637560-9e5d0b80-2f7c-4e6e-9b80-0d651a169d7e.png)

**Comment by fMichaleczek** [comment]
@NaitWatch The Cmdlet New-ScheduledTaskTrigger is a part of Windows, you should use Windows Feedback Hub instead. (Windows Team is responsible for Windows Modules)

**Comment by NaitWatch** [comment]
Ok thx for the info.
