### ISSUE TITLE
Symlinks cause weirdness related to trailing slash

### ISSUE THREAD

**Issue by halr9000** [PowerShell/PowerShell#1775]
I found that tab expansion doesn't work in a symlinked folder. Investigation found that the shell can't see ANY items in the $PWD, but /something/ causes things to right themselves in the same session.
## Steps to reproduce

``` powershell
cd /tmp
mkdir test1
mkdir test1/foo
mkdir test1/bar
ln -s test1 test2 # using /bin/ln here
dir test1 # "case A"
dir test2 # "case B"
```
## Expected behavior

Output from case A should equal case B, but the "Directory name" should read  "/tmp/test2".
## Actual behavior

Case B shows only the file entry of the symlink. That would be ok in some cases, HOWEVER what you see is that this behavior affects lots of things like tab expansion. For example, to continue repro:

``` powershell
cd test2
cd [TAB] # nothing happens with any tab completion commands here
```

Note that you can get around some of the issues by manually appending a forward-slash. e.g. `dir test2/`.
## Environment data

OSX 10.11.6

``` powershell
Name                           Value                                                                                     
----                           -----                                                                                     
PSVersion                      6.0.0-alpha                                                                               
PSEdition                      Core                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                   
BuildVersion                   3.0.0.0                                                                                   
GitCommitId                    v6.0.0-alpha.8                                                                            
CLRVersion                                                                                                               
WSManStackVersion              3.0                                                                                       
PSRemotingProtocolVersion      2.3                                                                                       
SerializationVersion           1.1.0.1         
```

**Comment by joeyaiello** [comment]
This may be related to #2865

**Comment by SteveL-MSFT** [comment]
@chunqingchen can you validate if your PR for the related issue fixes this and if we need to add a test case for this issue?

**Comment by SteveL-MSFT** [comment]
See if https://github.com/PowerShell/PowerShell/pull/3509 fixes this

**Comment by SteveL-MSFT** [comment]
Still repros with #2974

**Comment by chunqingchen** [comment]
@SteveL-MSFT @joeyaiello 
I used to be able to repro it on ubunto 14.04
Now I test the scenario on both macos 10.12.4 and ubunto 16.04 and it passes.

It seems this bug is OS version related but not powershell version related (the default powershell installed from ./tools/download.sh also passes).

Shall we set this bug as not repro?

**Comment by SteveL-MSFT** [comment]
This isn't repro'ing for me with beta1.  Looks like it was fixed with another change.
