### ISSUE TITLE
IDE0031: Use null propagation recommended by linter when taking .NET 7 preview 7

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#17769]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Multiple places where linter expects us to use `?.` instead of null checking. The full list is here:

> D:\a\PowerShell\PowerShell\src\System.Management.Automation\utils\RuntimeException.cs(217,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(985,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\DscSupport\CimDSCParser.cs(1015,29): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\utils\tracing\EtwActivity.cs(477,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemProvider.cs(4522,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemProvider.cs(4805,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(990,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(992,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1006,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1010,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1012,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1014,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1138,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1140,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1142,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\FileSystemContentStream.cs(1144,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\AliasProvider.cs(198,21): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\help\UpdateHelpCommand.cs(325,21): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\help\SaveHelpCommand.cs(263,21): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\help\SaveHelpCommand.cs(410,29): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(395,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(779,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(793,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(801,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(815,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(823,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(831,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\namespaces\CoreCommandContext.cs(1157,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\commands\ReceivePSSession.cs(407,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2726,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2792,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2794,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2796,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2798,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2800,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2802,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\common\RunspaceConnectionInfo.cs(2860,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\client\remoterunspaceinfo.cs(387,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\client\RemoteRunspacePoolInternal.cs(1829,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\client\RemoteRunspacePoolInternal.cs(1839,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\remoting\client\ClientRemotePowerShell.cs(169,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalPipeline.cs(490,21): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalConnection.cs(843,21): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalConnection.cs(853,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\hostifaces\LocalConnection.cs(1275,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\hostifaces\PowerShell.cs(5727,25): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\hostifaces\AsyncResult.cs(181,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\FormatAndOutput\common\OutputManager.cs(95,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\FormatAndOutput\common\OutputManager.cs(103,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\FormatAndOutput\common\FormattingObjectsDeserializer.cs(329,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\FormatAndOutput\common\ComplexWriter.cs(242,17): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\parser\Compiler.cs(6986,13): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
D:\a\PowerShell\PowerShell\src\System.Management.Automation\engine\CommandCompletion\PseudoParameterBinder.cs(1225,25): error IDE0031: Null check can be simplified [D:\a\PowerShell\PowerShell\src\System.Management.Automation\System.Management.Automation.csproj]
Exception: D:\a\PowerShell\PowerShell\tools\buildCommon\startNativeExecution.ps1:40

### Expected behavior

```console
Build should not fail
```

### Actual behavior

```console
Build failure with warning
```

### Environment data

```powershell
Dev environment
```

**Comment by fflaten** [comment]
I can look into this 🙂

**Comment by iSazonov** [comment]
@fflaten Don't forget about Unix :-) You can select Linux target (with Start-PSBuild) and cross-compile _locally_.

**Comment by fflaten** [comment]
I used the devcontainer, so if anything I'll forget something Windows-specific 😁

**Comment by daxian-dbw** [comment]
The PRs about using null propagation operator were all merged. Can we now turn on the IDE0031 warning that was disabled in https://github.com/PowerShell/PowerShell/pull/17770?

**Comment by fflaten** [comment]
Yes I believe so. I've submitted a PR to revert it.
