### ISSUE TITLE
Parameter declarations are accepted with names that cannot be bound with named arguments, such as those that look like negative numbers

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#17767]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:

* The problem applies to all-(decimal)-digit parameter names (e.g., `-1`) as well as those that _start with_ a digit (e.g., `-1a`)
* Not allowing all-digit names makes more sense, so as not create ambiguity between them and _negative numbers_.
* While you cannot bind such parameters _by name_ in direct invocation, it _is_ possible:
   * via _splatting_
   * due to what is arguably a bug when calling the CLI with `-File` - see #17519

Arguably, given the current behavior of the _typical_ use case - direct invocation - use of all-digit parameter names should be _categorically_ prevented, ideally in the _parsing_ stage. However, there is at least a hypothetical backward-compatibility concern.

```
# BREAKS: "-1" is interpreted as a positional argument:
#  -> A positional parameter cannot be found that accepts argument 'foo'
 & { [CmdletBinding()] param([string]$1) "[$1]" } -1 foo

# DOES WORK with SPLATTING
# -> '[foo]'
$ht = @{ '1'='foo' }; & { [CmdletBinding()] param([string]$1) "[$1]" } @ht
```

### Expected behavior

Consistent prevention of `-1` / `$1` as a parameter name / variable.

### Actual behavior

Error `A positional parameter cannot be found that accepts argument 'foo'`
String `[foo]`

### Environment data

```powershell
PowerShell Core 7.3.0-preview.6
```

**Comment by jhoneill** [comment]
It always puzzled me that this is also allowed
```
function test {

param (
    ${foo bar}
    )

    $PSBoundParameters
}
```

the parameter can be passed by position
```
> test 1

Key     Value
---     -----
foo bar     1
```

but tab completion builds `test -foo bar `   where `-foo` is sufficient to identify the parameter and `bar`  will become its value. 

You just know that out in the world someone who always passes parameters by position has a param block
`param ($1, $2, $3 )`  to write things very close to old style batch files.   Tightening up rules for parameter names will break those. So we may be stuck allowing people to pick stupid names, but relying on them not to do so

**Comment by mklement0** [comment]
> `${foo bar}`

You just need to call it correctly (I'm kidding): `` test -foo` bar hi `` 
As a bonus, such a parameter doesn't require an argument anymore: `` test -foo` bar `` (quiet no-op).

Well, I'd say that at least preventing something like `${foo bar}` at parse time is a prime candidate for a bucket 3 change - as is #17519 in my estimation (even though it has already been declined for fear of breaking things, but I think that fear is unfounded).

Fair point about the possibility of `param ($1, $2, $3)` - perhaps someone is willing to look at real-world scripts to see how common that is.

In general, this kind of permissiveness in naming that has only downsides appears to be a recurring theme - I'm reminded of #14025.

If something must not be broken, a PSScriptAnalyzer rule is the next best thing.

**Comment by jhoneill** [comment]
Definitely should be a script analyzer rule if nothing else. 
I doubt if the the `param ($1, $2, $3)` is common - even in batch files converted to PowerShell scripts, because I think people would tend to use `$args`  but the original Murphy's law had it that if can be done wrongly, someone will do that,  so if the syntax allows it, the script that _relies_ on it is out there somewhere - as I say, probably not common, but I'd guess more likely to break than #17519
