### ISSUE TITLE
Support : AdBlock Help¿

### ISSUE THREAD

**Issue by 80805504141995613430** [PowerShell/PowerShell#17761]
https://help.getadblock.com/support/solutions

**Comment by kilasuit** [comment]
I'm not sure what the ask is here, can you please expand before I mark this to be closed

**Comment by jhoneill** [comment]
@kilasuit  There are two spambot like messages from this ID. I'd delete both, and if poss block the account but another will spring up. Grrr

**Comment by doctordns** [comment]
This is just spam - let's close this issue.
