### ISSUE TITLE
PowerShell.exe launches profiles WindowsPowerShell based user profile directory

### ISSUE THREAD

**Issue by KrishnaV-MSFT** [PowerShell/PowerShell#1777]
Steps to reproduce
------------------
Have a $profile on your system (installing chocolatey via start-psbootstrap is sufficient), download alpha.8 pkg, run powershell.exe 

Expected behavior
-----------------
no error, note that executionpolicy is a different issue

Actual behavior
---------------
. : File C:\Users\slee\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\slee\Documents\WindowsPowerShell\Microsoft.PowerShell_pro ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by charub** [comment]
This is taken care off by #1769. Closing this issue
