### ISSUE TITLE
RemotePipeline does not transfer exit code

### ISSUE THREAD

**Issue by Zetanova** [PowerShell/PowerShell#17772]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The execution of a RemotePipeline to a linux system does not set `remotePipe.HasErrors` property correctly. 
A local `Pipeline` does set its `localPipe.HasErrors` on child-process exit code != 0 to true

```csharp
//hack for remote connection
            if (Runspace.DefaultRunspace == null)
            {
                var defaultRunspace = RunspaceFactory.CreateRunspace();
                defaultRunspace.Open();

                Runspace.DefaultRunspace = defaultRunspace;
            }

            var localRs = RunspaceFactory.CreateRunspace();

            var localPipe = localRs.CreatePipeline("pwsh -c 'exit 123'");

            localRs.Open();

            var localResult = localPipe.Invoke();

            Assert.True(localPipe.HadErrors);
            Assert.Empty(localResult);

            localRs.Close();


            var connectionInfo = new SSHConnectionInfo("root", "lnx1513", null);
            var remoteRS = RunspaceFactory.CreateRunspace(connectionInfo);

            var remotePipe = remoteRS.CreatePipeline("pwsh -c 'exit 123'");

            remoteRS.Open();

            var remoteResult = remotePipe.Invoke();

            Assert.True(remotePipe.HadErrors);
            Assert.Empty(remoteResult);

            remoteRS.Close();
```

### Expected behavior

```console
`remotePipe.HadErrors == true`
```

### Actual behavior

```console
`remotePipe.HadErrors == false`
```

### Environment data

```powershell
net6, Microsoft.PowerShell (SDK.7.2.5)
```

**Comment by PaulHigin** [comment]
First, you should use the `System.Management.Automation.PowerShell` type instead of the `System.Management.Automation.RemotePipeline` type, which has been deprecated.

```csharp
var connectionInfo = new SSHConnectionInfo("root", "lnx1513", null);
var remoteRS = RunspaceFactory.CreateRunspace(connectionInfo);
remoteRS.Open();

var ps = System.Management.Automation.PowerShell::Create(remoteRS);
ps.AddScript("pwsh -c 'exit 123'").Invoke();
ps.HadErrors
```

But the above example still does not work for a native command exiting with non-success return code.  The remoting system sets the `PowerShell.HadErrors` property only if a PowerShell `ErrorRecord` is returned over the remoting error stream.  But PowerShell does not currently emit an ErrorRecord if a native command returns a non-success code.  There has been some discussion about changing PowerShell to include native command return codes as ErrorRecords, and if I remember correctly, there are complications with doing something like this.

I'll tag this for committee review for awareness.

**Comment by Zetanova** [comment]
`System.Management.Automation.Pipeline` is depricated?
I am using Pipeline to create an `IObservable` or `IAsyncEnumeration` see:
https://github.com/Zetanova/hyperv-csi-driver/blob/master/src/hyperv-csi-driver/Automation/PNetPipeExtensions.cs

The current problem with `System.Management.Automation.PowerShell` is that it basically does not support
to stream input in and stream output out and abort in between. `Pipeline` does this over `PipelineReader` and `PipelineWriter`

**Comment by Zetanova** [comment]
About this issue, it would already be helpful and sufficient to create an Cmdlet in the base library to generate an ErrorRecord from $LastExitCode 

Example:
```csharp
ps.AddScript("pwsh -c 'exit 123' | Out-Error").Invoke();
//The result would be an ErrorRecord containing something with 'ErrorCode 123'
```

**Comment by PaulHigin** [comment]
The `PowerShell` object does indeed support streaming pipeline input/output via the `PSDataCollection` class.  See the overloads for `PowerShell.Invoke`, `PowerShell.BeginInvoke`, `PowerShell.InvokeAsync`.

**Comment by PaulHigin** [comment]
Regarding native command error handling, there has been a lot of discussion about it.  I hadn't followed the discussions much, but I think the main problem is that native commands are inconsistent in how they return error codes (especially on Windows).  I think @theJasonHelmick has done some work on this.

**Comment by Zetanova** [comment]
Yes you are correct, I didn't see the overloads of `PowerShell.InvokeAsync` that are accepting an output collection as a param,
only that `PowerShell.InvokeAsync` and `PowerShell.EndInvoke` returning one collection.

But still for long running pipes like log-tail or a monitor it will be useless, 
because all output items are stored in the output `PSDataCollection` and cannot be removed.

**Comment by PaulHigin** [comment]
`PSDataCollection` is a streaming collection that provides events for data added notifications or can be used as a blocking enumerator.

**Comment by SteveL-MSFT** [comment]
A non-zero exit code doesn't always mean error, but the remote behavior should try to be like the local behavior.  If locally a non-zero is interpreted as an error condition, then it makes sense to have the same for remote.

**Comment by PaulHigin** [comment]
@SteveL-MSFT  The remote case is quite a bit different than the local case, and currently only ErrorRecords affect `HadErrors`, by design.  Changing this would require updating the protocol which means updating versions, documentation, and compatibility tracking.  I feel it is better to address the issue of how native return codes are handled in PowerShell, in general.  But in either case it would be a potential breaking change.

**Comment by Zetanova** [comment]
@PaulHigin  Can the `PowerShell` output of `PSDataCollection` be used for a command that executes over 7-300 days
and generates 100MB / day ?

**Comment by PaulHigin** [comment]
@Zetanova 
Are you saying it cannot and that the collection object fills up with data?  If so then you are not using it as a streaming collection, where it acts as a temporary buffer.  You need to remove the data being collected and stream it to wherever the final destination is.  If you allow the data to only be collected then you will eventually run out of system resources, which is a limitation of the system not the collection object.

**Comment by PaulHigin** [comment]
@WG-Committee
The committee discussed this and agrees that ideally the remote case of `HadErrors` should work as it does in the local case, regarding how native command return codes are reported.  However, it currently does not and changing the behavior means updating the remoting protocol, which is something we would not do for such a small change.

The workaround is to write the remoting script such that it gets and examines native command return codes and reports back to the client via normal PowerShell error reporting.

**Comment by PaulHigin** [comment]
@Zetanova  In case I am not being clear, here is a simple example of using the streaming collection.

```csharp
            using (var ps = System.Management.Automation.PowerShell.Create(RunspaceMode.NewRunspace))
            {
                ps.AddScript(@"1..10 | foreach { sleep 1; ""Streaming $_""}");
                PSDataCollection<string> streamingIn = null;
                var streamingOut = new PSDataCollection<string>();
                var async = ps.BeginInvoke(streamingIn, streamingOut);
                // Remove streaming data from streamingOut collection as data becomes available.
                foreach (string item in streamingOut)
                {
                    Console.WriteLine(item);
                }
                ps.EndInvoke(async);
            }
```

**Comment by Zetanova** [comment]
@PaulHigin  thanks for explanation, I didn't see it.  I bit strange that the enumerator has the side effect of removing the items from the list. If the `steamingOut.EnumeratorNeverBlocks = true` and subscribe to `steamingOut.DataAdded` to then enumerate all buffered item, I assume that it would be non blocking.

**Comment by PaulHigin** [comment]
Yes, it can be used more or less as a normal collection as well.  But really it was designed to support pipeline streaming for the API.
