### ISSUE TITLE
`$host.EnterNestedPrompt()` should throw if `-NonInteractive` (but does not)

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#17786]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
pwsh -NonInteractive -Command { $host.EnterNestedPrompt() }
```

### Expected behavior

I expect the same sort of exception that I would get if I had run:
```powershell
pwsh -NonInteractive -Command { $host.UI.PromptForChoice( 'caption', 'msg', @('a', 'b'), 0 ) }
```
```console
MethodInvocationException: Exception calling "PromptForChoice" with "4" argument(s): "PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."
```

### Actual behavior

(it enters a nested prompt)

### Environment data

```powershell
I am on a pretty recent version, but I expect this repro's in every version, back to 5.

PS C:\Users\me> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.5
PSEdition                      Core
GitCommitId                    7.3.0-preview.5
OS                             Microsoft Windows 10.0.22940
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> `Read and Prompt functionality is not available`

Nested Prompt does not affect interactivity. Does not require user participation.

**Comment by jazzdelightsme** [comment]
Sorry, @237dmitry, I don't understand: in what way does a nested prompt not require user participation?

If you run the command in the repro steps, the new process will never exit... until the user interacts with it (by running `exit`). I claim it requires interactivity in the same way that `Read-Host` requires interactivity, and thus should also fail where `Read-Host` fails.

**Comment by 237dmitry** [comment]
It's difficult to come up with a use for `$host.EnterNestedPrompt()` in non-interactive mode. Unless, at some stage, freeze the execution of a script block in order to enter interactive mode and execute something else.

```powershell
pwsh -NonInteractive -Command { 0..9 | % { if ($_ -eq 5) { $host.EnterNestedPrompt() }; $_  }}
```

**Comment by jazzdelightsme** [comment]
"Non-interactive mode" (i.e. starting `pwsh` with the `-NonInteractive` switch) is used to indicate that a user should not (and likely *cannot*) interact with the program. Hence if you call `Read-Host` or `$host.UI.PromptForChoice` etc., they will throw an exception saying so. This allows you to adapt scripts to run in places like a session 0 service, where a user has no way to interact with it--if you make a mistake, and your script calls `Read-Host`, things won't hang--it will fail instead, which is the desired behavior here.

**Comment by daxian-dbw** [comment]
The Engine WG discussed this issue today, and we believe this is a by-design behavior.
`pwsh -noninteractive` actually gives you an interactive shell, despite the `-noninteractive` flag being specified. Within that environment, you can debug a script, which will call `EnterNestedPrompt` to setup the debugging prompt (see the screenshot below).

As for why `pwsh -noninteractive` gives back an interactive shell, @JamesWTruher believes it was for debugging scripts that are supposed to run in `noninteractive` mode.

The [help content](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-noninteractive) for the `-NonInteractive` flag says: _Does not present an interactive prompt to the user._ It's not very accurate and should be updated. Opened doc issue: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9156

![image](https://user-images.githubusercontent.com/127450/186042249-fdd0ab08-860f-4644-aa3b-ee9b0e1153ee.png)
