### ISSUE TITLE
Missing command alias: iwr

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#1778]
The `iwr` alias is missing in PowerShell Core, although `Invoke-WebRequest` works perfectly fine. Does this need to be added back?
- Ubuntu 16.04 LTS base image (Dockerized)
- .NET Core 1.0.0-preview2
- PowerShell Core 6.0.0-alpha

```
PS /powershell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.8
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

![image](https://cloud.githubusercontent.com/assets/466713/17637067/6b14036e-609e-11e6-856b-340d974bb16c.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by Francisco-Gamino** [comment]
Fixed.
