### ISSUE TITLE
[SecretManagment not supported in non-standard Windows accounts] Get-Secret breaks JEA transcript

### ISSUE THREAD

**Issue by pkosek** [PowerShell/PowerShell#17788]
Hi,

I've been investigating an odd issue, where Get-Secret is exposed through JEA. And when it's called, it breaks transcript logging for the reminder of the entire JEA session. I wonder if this a bug, or by design.

JEA transcript log:

**********************
Windows PowerShell transcript start
Start time: 20220329205906
Username: n/a
Host Application: C:\Windows\system32\wsmprovhost.exe -Embedding
Process ID: 2956
PSVersion: 5.1.17763.771
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.771
BuildVersion: 10.0.17763.771
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

PS>CommandInvocation(Get-Secret): "Get-Secret"
>> ParameterBinding(Get-Secret): name="Name"; value="testcred"
>> ParameterBinding(Get-Secret): name="Verbose"; value="True"
>> ParameterBinding(Get-Secret): name="Debug"; value="True"
>> CommandInvocation(Out-Default): "Out-Default"
**********************
Windows PowerShell transcript end
End time: 20220329205913
**********************

thanks
Pete

**Comment by PaulHigin** [comment]
Closing this issue as I feel it needs to be investigated by PowerShell team, since it is breaking PowerShell transcripts/data streams, and it has been transferred to PowerShell repository.

**Comment by PaulHigin** [comment]
Oh, I see this is the same PR just transferred.  Re-opening.

**Comment by LeonarddeR** [comment]
@PaulHigin It looks like the microsoft-github-policy-service bot is over actively closing stale issues. Would you be able to reopen this?
