### ISSUE TITLE
PowerShell 7 / Terminal window does not accept keystrokes when running over Azure WVD/RDS Webclient - See #17512

### ISSUE THREAD

**Issue by ABSPFD** [PowerShell/PowerShell#17783]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi all.
We have been banging out heads against PowerShell 7/Terminal windows on server 2022 and Win11 that simply do not type when keystrokes are entered.  
This happens exclusively when trying to type in a PowerShell window, running on Server 2022/Win11 Desktop or RemoteApp via AVD or RDS WebClient.  This happens even when running PS with in a cmd.exe session.
Note - this happens in 5.1 as well for reference.

All input except PowerShell is working correctly.

This is me typing to a PowerShell 7/Terminal window via RDS/AVD using webclient.  There is no input.
![image](https://user-images.githubusercontent.com/72078919/181193356-d358a0b7-aaae-4e97-90b1-772c7cb6e193.png)

This is me typing to the same window via RDS/AVD not by webclient.  RDP works fine.
![image](https://user-images.githubusercontent.com/72078919/181191068-ddb0619c-dc0d-4621-991b-2aeac2a806c9.png)

### Expected behavior

```console
Typing in PowerShell 7/Terminal should be reflected in the PS window
```

### Actual behavior

```console
Typing in PowerShell 7/Terminal is not reflected in the PS window
```

### Error details

```console
No errors or feedback of any kind
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
The AVD team has recommended that customers file an issue in Feedback Hub from the AVD host encountering the issue.  Please select the category “Problem”, followed by “Apps” and “Remote Desktop”.  Screenshot below.

<img width="1158" alt="feedback" src="https://user-images.githubusercontent.com/12662278/182879313-d4c3ee95-038c-4f25-bcab-56acbe0295ca.png">
￼

**Comment by ABSPFD** [comment]
Thanks for the info, though this is not just an Azure issue, it happens for RDS as well.  We get reports from IOS users running RDP client having the same issue.
It does seem like a PowerShell issue as the root cause, triggered by how it interacts with RDS portals.  To be clear, it is only PowerShell that has the problem.
Instead of pointing me to the Feedback = Null form, could we please investigate further?

**Comment by daxian-dbw** [comment]
Mark for the interactive console WG to review.

**Comment by daxian-dbw** [comment]
@ABSPFD Can you please provide the instructions to setup a repro environment?

**Comment by ABSPFD** [comment]
@daxian-dbw Happy to, ill shoot the details through ASAP.

**Comment by theJasonHelmick** [comment]
@ABSPFD Thank you for the help in getting steps to repo.  We review this and think it may be an issue with the .NET Console api.  We will share a program that you can use to help us determine the cause if you have time and are willing.

**Comment by JamesWTruher** [comment]
@ABSPFD Would you please compile and run the following in that environment?
```csharp
using System;
namespace test {
    public class Test {
        public static void Main() {
            Console.Write("type a string and press <ENTER>: ");
            string s = Console.ReadLine();
            Console.WriteLine("string is '{0}'", s);
            Console.Write("press a key: ");
            ConsoleKeyInfo c = Console.ReadKey();
            Console.WriteLine("\nkey is '{0}'", c.Key);
        }
    }
}
```

if working, you should see the string you typed and the key you pressed. If you don't see anything, then .NET is likely at issue.

**Comment by iSazonov** [comment]
Console.ReadKey() was improved in .Net 7 and perhaps it is already in .Net Preview7.

**Comment by ABSPFD** [comment]
Hi @theJasonHelmick @JamesWTruher 
Sorry for the delay getting back to you.

I've compiled and run the code supplied and Keystrokes work, though with different "key" output.  I have also tested on .Net 7p7, same result and only in PowerShell.
Interestingly, control key strokes (e.g. CTRL+V, Tab, etc.) and Enter and Backspace work too. 
Letter, numbers and special characters (!. @, $ etc.) do not.

Via RDS Webclient
![image](https://user-images.githubusercontent.com/72078919/184082527-b7b3660d-3e9d-4940-83f4-87a9996cb031.png)

Via RDS non-Webclient and local PC as a control
![image](https://user-images.githubusercontent.com/72078919/184082637-27fd1437-ec01-4f90-b579-5d7812c19aaf.png)

**Comment by papafe** [comment]
I am experiencing the same behaviour, including the results obtained with that piece of code. In my case it happens when using Microsoft Remote Desktop to connect to Windows.

**Comment by daxian-dbw** [comment]
@ABSPFD Thanks for trying that out and get back to us! The information about the `Packet` value is very helpful. I believe this was already fixed in the 2.2 version of PSReadLine by https://github.com/PowerShell/PSReadLine/pull/2632.

The v7.2.5 of PowerShell ships the v2.1.0 PSReadLine which doesn't have that fix. Please upgrade to [v2.2.6](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) of PSReadLine. See https://github.com/PowerShell/psreadline#upgrading for instructions if you are not familiar with upgrading PSReadLine.

**Comment by ABSPFD** [comment]
Hi @daxian-dbw 
I believe upgrading to v.2.2.6 worked.  I can type into a PS session inside the RDS webclient now.
![image](https://user-images.githubusercontent.com/72078919/184260421-d1149d56-6a04-4634-9e10-ba5c050e61c3.png)


Do we know if this will be rolled up into the next PS versions?

**Comment by daxian-dbw** [comment]
Yes, PowerShell 7.3 will ship with the v2.2.6 of PSReadLine, which has this fix.

**Comment by ABSPFD** [comment]
Thanks for the help @daxian-dbw.  Really glad to see there is a fix for this,
