### ISSUE TITLE
Distribute OSX release as a Homebrew formula

### ISSUE THREAD

**Issue by halr9000** [PowerShell/PowerShell#1779]
As a devops type nerd, I want to be able to install and update PowerShell/OSX via the CLI, and also with my preferred packaging tool, namely Homebrew (http://brew.sh). 

Yes, the the OSX native installer packages (.pkg) can be installed via CLI (with the `installer` command), but it requires sudo. AFAICT, PowerShell is installed to /usr/local/bin and does not require sudo at all otherwise. 

Homebrew is basically the de-facto CLI package manager on OSX like choco.exe is on Windows. It does not require sudo for packages to be installed.

Instructions to create a formula: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by niemyjski** [comment]
I'd also love to install via brew! I'm going to hold off installing until I can install via brew (so easy to update brew packages)!

**Comment by anurse** [comment]
This would be awesome. I'm happy to build the package but I don't want to stomp on a possible official homebrew tap. I hope we can get this soon! I want `brew install powershell` :)

**Comment by andschwa** [comment]
Keep in mind that we probably need https://github.com/dotnet/cli/issues/533 too (at least to do it right! in the short term we can install dotnet locally to build).

**Comment by luzlab** [comment]
Currently, `brew cask install powershell` works. I haven't done much testing, but it just downloads the .pkg and runs it.

**Comment by joeyaiello** [comment]
Given this has the most 👍's of any issue, I'm going to fix our install instructions today to make it more obvious how to do this.

**Comment by halr9000** [comment]
@joeyaiello I just tried a `brew cask reinstall powershell` and it gave me v6.0.0-beta.1. Something is not properly automated. I would dig in but no time to do so ATM.
