### ISSUE TITLE
Add to known issue that powershell attempts to load existing Windows PowerShell profile

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#1780]
See https://github.com/PowerShell/PowerShell/issues/1777 for issue

This is to make sure we add the known issue

**Comment by BrucePay** [comment]
On windows "windows powershell" uses "~/documents/windows powershell" for profiles, etc. and PowerShell 6.0 uses "~/documents/powershell" so nothing need be done for the issues document as it stands.
