### ISSUE TITLE
Write-Progress progress bar only accurate up to 12% complete

### ISSUE THREAD

**Issue by timGerken** [PowerShell/PowerShell#17812]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When executing the following script, the yellow progress bar is accurate up until about 12% after which it is only as long as the `-Status` text's length

```Powershell
0..100 | % {Write-Progress -Activity "pctComplete:" -Status "($_)" -PercentComplete $_; Start-Sleep -Milliseconds (500)}
```

### Expected behavior

```console
The progress bar's length continues to tick up to 100%
```

### Actual behavior

```console
The progress bar's length ticks up to 12% after which it is only renered as long as the `-Status` text's length
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://user-images.githubusercontent.com/14828396/182236097-84e4823d-ee6e-4190-bcff-64d689772ff8.mp4

**Comment by 237dmitry** [comment]
I think this is the problem of Windows Terminal, pwsh launched in conhost works correct. In linux progress-bar works correct too.

**Comment by fMichaleczek** [comment]
I test on different Windows Terminal version on Microsoft Windows 10.0.19044 :  
- 1.12.10982.0 => OK
- 1.13.11431.0 => OK
- 1.14.1432.0 => KO
- 1.14.1962.0 => KO
- 1.15.1862.0  => KO

Can someone confirm the symptom with Windows 11 and Windows Terminal >=  1.14 ?

**Comment by Mettcon** [comment]
WT preview 1.15.2003.0 
Windows Insiders 10.0.25169
PS `7.3.0-preview.6` and `PowerShell 7.2.5`
same behaviour

works fine with conhost

**Comment by kasini3000** [comment]
wt 1.14 + ps 7.3.0-preview.6  
I can reproduce the problem

**Comment by Chrisso** [comment]
See https://github.com/microsoft/terminal/issues/13617

**Comment by jhoneill** [comment]
> I test on different Windows Terminal version on Microsoft Windows 10.0.19044 :

> Can someone confirm the symptom with Windows 11 and Windows Terminal >= 1.14 ?

Yes. Windows 11, terminal 1.14.1963 ,PowerShell 7.3 preview 6
"Classic" progress bar is fine. 
"Minimal" progress bar increases in size up to 12% and at 13 shrinks to four characters wide

**Comment by timGerken** [comment]
> See [microsoft/terminal#13617](https://github.com/microsoft/terminal/issues/13617)

and the active, non-dupe, microsoft/terminal#13229
