### ISSUE TITLE
`out-file` overwrites existing file with empty file when taking piped input from `select-string`

### ISSUE THREAD

**Issue by charltonstanley** [PowerShell/PowerShell#17815]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. create a file in the current directory with a list of newline delimited strings. Here is what mine looks like:
```powershell
PS> cat ./testfile
a
b
c
e
f
g
PS>
```
2. Get the contents of the file and use `select-string` to filter out the letter `d`.
```powershell
PS> Get-Content $file | Select-String -Pattern 'd' -NoEmphasis -NotMatch -Raw
a
b
c
e
f
g
PS>
```
3. Pipe the output to `out-file` to overwrite the same `$file` with the filtered output.
```powershell
PS> Get-Content $file | Select-String -Pattern 'd' -NoEmphasis -Raw -NotMatch | out-file -Path $file 
PS>
```
4. Get the contents of the file.
```powershell
PS> Get-Content $file
```

### Expected behavior

```powershell
PS> Get-Content $file
a
b
c
e
f
g
PS>
```

### Actual behavior

```powershell
PS> Get-Content $file
PS>
```

### Error details

No error was returned.

### Environment data

The bug is experienced on both `7.3.0-preview.6` and `7.2.5`.

```powershell

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.6
PSEdition                      Core
GitCommitId                    7.3.0-preview.6
OS                             Linux 5.14.0-1045-oem #51-Ubuntu SMP Mon Jul 4 06:41:22 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.14.0-1045-oem #51-Ubuntu SMP Mon Jul 4 06:41:22 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
```
(Get-Content $file) | Select-String -Pattern 'd' -NoEmphasis -Raw -NotMatch | out-file -Path $file 
```

**Comment by charltonstanley** [comment]
@237dmitry Interesting. That did work, although I'm rather confused as to why.
Using your answer, I also found that if I first store the output of `Get-Content $file` in a variable, and substitute the variable for the `Get-Content $file` portion of the command, that works as well. So is it really a problem with `Get-Content` instead of with `Select-String`?

**Comment by 237dmitry** [comment]
When transferring data from a file through a pipeline, the file is open for reading and writing at the same time. Therefore, it is overwritten before it is fully read. You must first read the file, and then transfer its contents through the pipeline.

**Comment by jhoneill** [comment]
> When transferring data from a file through a pipeline, the file is open for reading and writing at the same time. Therefore, it is overwritten before it is fully read. You must first read the file, and then transfer its contents through the pipeline.
> 
> PS. The question is very very old, I think from the birth of Monad (the ancestor of powershell).

With the pipeline we have begin process and end steps for each command , 
Begin  
- `Get-Content` opens the file for read. 
- `Select-String` initializes any regex processor  it needs
- `Out-File` opens the file for write and reset its contents
Process
- `Get-Content` until we reach the end of the file read a line and output it WOAH! it's an empty file - move to the end block and close the file 
End 
- `Out-File` sees the other steps ending and closes the file too.  
 

Putting () round the `Get` means that value is obtained before the Begin step of the `out` runs 

If have written things so all the file reads happen in the begin stage AND the reset/re-write part happens in the end block to side step the problem, but I don't of any cmdlets which do that

**Comment by charltonstanley** [comment]
Thank you all for the explanations. It's still surprising to me, but if this is normal/expected behavior then it's obviously not a bug.  It's strange...I have been writing scripts for years; have never bumped into this chicken/egg scenario before. Just when you think you know it all... :smile: 

Thanks again!
