### ISSUE TITLE
Test-FileCatalog Fails to Validate a Single File when the Catalog Contains Two Files

### ISSUE THREAD

**Issue by kcbowhunter** [PowerShell/PowerShell#17824]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

[PeteTheCat.zip](https://github.com/PowerShell/PowerShell/files/9245920/PeteTheCat.zip)

The zip file contains 4 files that are used to demonstrate the issue.
PeteThe01.cat is a catalog that contains only one file, Green.dll
Test-FileCatalog works fine when there is one file in the catalog and one file is being tested.

PeteThe02.cat is a catalog that contains two files, Green.dll and Red.dll
Test-FileCatalog fails to validate Green.dll in the PeteThe02.cat file catalog.

I am new to using file catalogs, but this behavior looks incorrect.  If I'm doing something wrong, please indicate how to test one file in a catalog with multiple files.

### Expected behavior

```console
Testing the first catalog with one file works correctly:
a) without specifying any files
PS D:\Learn\TestCat\Test01> Test-FileCatalog -CatalogFilePath .\PeteThe01.cat -Detailed

Status        : Valid
HashAlgorithm : SHA256
CatalogItems  : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41]}
PathItems     : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41]}
Signature     : System.Management.Automation.Signature
(this shows that Petethe01.cat only contains one file)


b) The first test using PeteThe01.cat works correctly when specifying a single file to validate:
PS D:\Learn\TestCat\Test01> Test-FileCatalog -CatalogFilePath .\PeteThe01.cat -Detailed -Path .\Green.dll

Status        : Valid
HashAlgorithm : SHA256
CatalogItems  : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41]}
PathItems     : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41]}
Signature     : System.Management.Automation.Signature

--------------------------------------------------------------------

Second test using PeteThe02.cat, a catalog which contains two dll's.
First, not specifying any path to Test-FileCatalog shows that PeteThe02.cat is a valid catalog and it contains two dll's:
PS D:\Learn\TestCat\Test02> Test-FileCatalog -CatalogFilePath .\PeteThe02.cat -Detailed

Status        : Valid
HashAlgorithm : SHA256
CatalogItems  : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41], [Red.dll,
                23B1EE3F3D67F403E092BC88B2BCFCC19087EFCE142A2D071B737F9FF59C5411]}
PathItems     : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41], [Red.dll,
                23B1EE3F3D67F403E092BC88B2BCFCC19087EFCE142A2D071B737F9FF59C5411]}
Signature     : System.Management.Automation.Signature

-------------------------------------------------------------------
The problem occurs when specifying a path to validate one dll for PeteThe02.cat which contains two dll's:

The expected behavior is that when testing one file in the catalog with two dll's that the status should be valid:
PS D:\Learn\TestCat\Test02> Test-FileCatalog -CatalogFilePath .\PeteThe02.cat -Detailed -Path .\Green.dll

Status        : Valid
```

### Actual behavior

```console
This is the actual behavior that I am observing; when there are two files in the catalog, when I try to validate one file in the catalog the validation fails.  The syntax used is the same syntax for the first test performed where the validation passed when there was only one file in the catalog.


PS D:\Learn\TestCat\Test02> Test-FileCatalog -CatalogFilePath .\PeteThe02.cat -Detailed -Path .\Green.dll

Status        : ValidationFailed
HashAlgorithm : SHA256
CatalogItems  : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41], [Red.dll,
                23B1EE3F3D67F403E092BC88B2BCFCC19087EFCE142A2D071B737F9FF59C5411]}
PathItems     : {[Green.dll, FD16354EE3B868E122FE3154EF06AA5FB561393F867D538F0D1D6BAD4228CA41]}
Signature     : System.Management.Automation.Signature
```

### Error details

```console
Get-Error did not return anything from the Test-FileCatalog command.
```

### Environment data

```powershell
PS D:\Learn\TestCat\Test01> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PeteTheCat01](https://user-images.githubusercontent.com/9277839/182482062-cb1bff11-5bbd-421e-b719-2c8e2ffe1c3f.png)
![PeteTheCat02](https://user-images.githubusercontent.com/9277839/182482231-b6a6b48a-3c25-4d70-88f9-4d0b4b45f7d2.png)
![PeteTheCat03](https://user-images.githubusercontent.com/9277839/182482465-bed5e6ac-95a1-4f23-8003-90cd668cf837.png)

**Comment by kcbowhunter** [comment]
After doing more research and reading through the source code it looks like the behavior that I'm seeing is the intended behavior.  Also, it appears that you can't specify .\Filename.dll on the command line when the file is in the catalog as Filename.dll.

I was able to get the test I wrote to work by using the FilesToSkip option:

PS D:\Learn\TestCat\Test02> Test-FileCatalog -CatalogFilePath .\PeteThe02.cat -Detailed -Path Red.dll -FilesToSkip Green.dll

Status        : Valid
HashAlgorithm : SHA256
CatalogItems  : {[Red.dll, 23B1EE3F3D67F403E092BC88B2BCFCC19087EFCE142A2D071B737F9FF59C5411]}
PathItems     : {[Red.dll, 23B1EE3F3D67F403E092BC88B2BCFCC19087EFCE142A2D071B737F9FF59C5411]}
Signature     : System.Management.Automation.Signature

This is really not very practical when you have a catalog with 100+ files and you want to verify one specific file in the catalog.  How about adding a -VerifyOneFile option that would skip over all the files in the catalog except for the single file being verified.

My company is evaluating the use of software catalogs for generating a catalog of unsigned 3rd party dll's that we sign and ship with our products.  We need to give our customers an easy method for verifying that the hashes for the files installed are correct using the (signed) catalog we provide.  

Our current thinking is to create the files in the catalog during the build process on Azure DevOps pipelines by accumulating 3rd party unsigned dll's over many folders from the build and copying those files to a temporary location to create the catalog.  Therefore the relative paths of the files from where the software will be installed will not match the relative paths of the files in the catalog.  For our purposes, an option of -IgnoreRelativeFilePath or -VerifyHashOnly would be useful.  

Apologies for creating this as a defect if it is more appropriate as a feature request.

**Comment by PaulHigin** [comment]
@WG-Security
The `Test-FileCatalog` is intended to validate an entire catalog directory and not a single file.  It might make sense to have another cmdlet, or parameter set, that is intended to validate specific files in a catalog, similar to what Windows API does.

**Comment by iSazonov** [comment]
I wonder what is Path parameter semantic?

**Comment by kcbowhunter** [comment]
My example above shows that when there are two files in the catalog and you use the Path parameter to try and validate only one file the result is that the validation fails.

Our plan is to create a catalog of unsigned 3rd party dll's on our ADO build pipeline.  During the software build process all of the unsigned 3rd party dlls found in the build artifacts are copied  to a temporary folder on the build agent.  The catalog is created using New-FileCatalog from that folder.  

We don't include the dll's we create because we apply our digital signature to our dll's.  

We were hoping to use Test-FileCatalog to allow our customers to verify that the unsigned 3rd party dll's installed as part of installing one of our software products have not been tampered with.  

Because the unsigned 3rd party dlls are collected into a common folder and signed during the build process, the dll's in the catalog will not be found in the same folders when installed via our .msi installer.

This gives some of the background why it would be useful to us to for Test-FileCatalog to easily test / validate a single file in the catalog.  Thanks for reading! :-)

**Comment by LorenzoPigozzo** [comment]
I could not describe better this scenario and usecase, which is the same for the company I work for.
