### ISSUE TITLE
New-PSDrive does not give expected results with UNC Paths on Linux

### ISSUE THREAD

**Issue by JPEscher** [PowerShell/PowerShell#17845]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Issue: Unexpected result on linux from command: New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath" -Credential $creds -Scope Global

I originally suspected that this was user error. I did try variations such as inverting the \ to / and using "smb:" as a prepend. They did not work. In searching I found the following that make me wonder if this is user error or a restrictions I did not see in the documentation. I did see this in the documentation which leads me to believe there is a minimum of a documentation deficiency. Example/Reasoning:

-Persist
Indicates that this cmdlet creates a Windows mapped network drive. The Persist parameter is only available on Windows.

The above suggests that all other aspects of the command are transportable. The following show this has been a known issue for a while.
https://github.com/PowerShell/PowerShell/issues/1409 (opened 2016-07-18) - No examples and several signs it is not fixed even after:  joeyaiello added the Resolution-Fixed label on May 23, 2017
https://github.com/PowerShell/PowerShell/issues/6629 (opened 2018-04-11) - Still open. Please note as per others in this thread, the CIFS Mount pre-requisite is not an option for me due to Docker restrictions
https://github.com/PowerShell/PowerShell/issues/6759 (opened 2018-04-27) - Still open. Please note as per others in this thread, the CIFS Mount pre-requisite is not an option for me due to Docker restrictions

If an SMB Mount point turns out to be a pre-requisite, I suggest an update to the documentation. A notice that this is required on Linux due to restrictions. I would prefer finding a way to not require SMB Mounts.

Thank you in advance for your time. Please feel free to reach out to me if there are actions I may try to assist. Please

Command: New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath" -Credential $creds -Scope Global

Linux Tested Variants:
Command Variant: New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "//UNCServerName/FolderPath" -Credential $creds -Scope Global
Command Variant: New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "smb:\\UNCServerName\FolderPath" -Credential $creds -Scope Global
Command Variant: New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "smb://UNCServerName/FolderPath" -Credential $creds -Scope Global

### Expected behavior

```console
Expected Result (obtained on Windows): New PS Drive is available and usable for scripting
Unexpected Result (obtained on Linux): Obtain Errors
```

### Actual behavior

```console
Windows Environment/Outcome:
PS C:\Users\[myuser]> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\[myuser]> $creds = Get-Credential
PowerShell credential request
Enter your credentials.
User: [user]@[company]
Password for user [user]@[company]: ********************

PS C:\Users\[myuser]> New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath" -Credential $creds -Scope Global
Name           Used (GB)     Free (GB) Provider      Root                                                                                                     CurrentLocation
----           ---------     --------- --------      ----                                                                                                     ---------------
shareName                              FileSystem    \\UNCServerName\FolderPath

PS C:\Users\[myuser]>


Linux Environment/Outcome:
PS /home/[myuser]/development> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/[myuser]/development> $creds = Get-Credential
PowerShell credential request
Enter your credentials.
User: [user]@[company]
Password for user [user]@[company]: ********************

PS /home/[myuser]/development> New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath" -Credential $creds -Scope Global
New-PSDrive: The specified drive root "\\UNCServerName\FolderPath" either does not exist, or it is not a folder.

PS /home/[myuser]/development> Get-Error

Exception             :
    Type    : System.IO.IOException
    Message : The specified drive root "\\UNCServerName\FolderPath" either does not exist, or it is not a folder.
    HResult : -2146232800
TargetObject          : shareName
CategoryInfo          : ReadError: (shareName:PSDriveInfo) [New-PSDrive], IOException
FullyQualifiedErrorId : DriveRootError,Microsoft.PowerShell.Commands.NewPSDriveCommand
InvocationInfo        :
    MyCommand        : New-PSDrive
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath" -Credentia
l $creds -Scope Global
    PositionMessage  : At line:1 char:1
                       + New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-PSDrive
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :


PS /home/[myuser]/development> ping [UNCServerName]
PING [UNCServerName] ([ip address]) 56(84) bytes of data.
64 bytes from [UNCServerName] ([ip address]): icmp_seq=1 ttl=64 time=0.889 ms
64 bytes from [UNCServerName] ([ip address]): icmp_seq=2 ttl=64 time=1.23 ms
64 bytes from [UNCServerName] ([ip address]): icmp_seq=3 ttl=64 time=0.778 ms
64 bytes from [UNCServerName] ([ip address]): icmp_seq=4 ttl=64 time=1.48 ms
64 bytes from [UNCServerName] ([ip address]): icmp_seq=5 ttl=64 time=0.923 ms
64 bytes from [UNCServerName] ([ip address]): icmp_seq=6 ttl=64 time=1.42 ms
64 bytes from [UNCServerName] ([ip address]): icmp_seq=7 ttl=64 time=5.89 ms
^C
--- [UNCServerName] ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6084ms
rtt min/avg/max/mdev = 0.778/1.800/5.889/1.687 ms

PS /home/[myuser]/development>
```

### Error details

```console
PS /home/[myuser]/development> Get-Error

Exception             :
    Type    : System.IO.IOException
    Message : The specified drive root "\\UNCServerName\FolderPath" either does not exist, or it is not a folder.
    HResult : -2146232800
TargetObject          : shareName
CategoryInfo          : ReadError: (shareName:PSDriveInfo) [New-PSDrive], IOException
FullyQualifiedErrorId : DriveRootError,Microsoft.PowerShell.Commands.NewPSDriveCommand
InvocationInfo        :
    MyCommand        : New-PSDrive
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath" -Credentia
l $creds -Scope Global
    PositionMessage  : At line:1 char:1
                       + New-PSDrive -Name "shareName" -PSProvider "FileSystem" -Root "\\UNCServerName\FolderPath …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-PSDrive
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Windows Environment:
PS C:\Users\[myuser]> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Linux Environment:
PS /home/[myuser]/development> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
Filesystem paths go through the native OS' filesystem APIs to access and Linux does not have the ability to understand UNC paths or access SMB shares natively like you can on Windows. What you are meant to do is use a tool to mount the UNC path to a local folder and access it that way. Unfortunately this is a limitation of the OS in question and unless the FileSystem provider can support SMB shares itself (not a trivial thing to do) there is nothing that can be done here.

**Comment by iSazonov** [comment]
You could use automount.

**Comment by JPEscher** [comment]
> You could use automount.

docker security disables mount. this is the issue i am trying to get around. docker suggests using volumes, but then the underlying system allows ALL images attached to access the volume, which is also a security issue. 

similar restraints on windows, yet the new-psdrive command is reported to get around it according to posts i've seen.

as my company doesn't use docker on windows i cannot personally confirm this. 

more details: https://docs.docker.com/engine/security/seccomp/

note: my company doesn't allow the use of seccomp profiles, something my boss had me look into while waiting a decision on, so i do have a profile that would work, I'm just not allowed to use it, nor would efforts to refine it be worth while.

**Comment by JPEscher** [comment]
> Filesystem paths go through the native OS' filesystem APIs to access and Linux does not have the ability to understand UNC paths or access SMB shares natively like you can on Windows. What you are meant to do is use a tool to mount the UNC path to a local folder and access it that way. Unfortunately this is a limitation of the OS in question and unless the FileSystem provider can support SMB shares itself (not a trivial thing to do) there is nothing that can be done here.

this would suggest the documentation on new-psdrive be updated to note this. at this time there is no way to tell this from the documentation. as per this thread, there are three other threads started, likely due to the lack of this notation in the documents.
