### ISSUE TITLE
Distribution Support Request Fedora 35

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#17849]
### Name of the Distribution

Fedora

### Version of the Distribution

35

### Package Types

RPM

### Processor Architecture

AMD64

### .NET Support

* [.NET 6][linux-fedora]
* [.NET Core 3.1][linux-fedora]

[linux-fedora]: https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#supported-distributions

### Distribution Requirements

* [Fedora 35][f35] was released on 2021-11-02 and will be maintained for approximately [13 months][lifecycle].
  * **support ends in December 2022**.
 * Fedora 35 is not an interim release or equivalent.

[f35]: https://docs.fedoraproject.org/en-US/fedora/f35/release-notes/
[lifecycle]: https://docs.fedoraproject.org/en-US/releases/lifecycle/

### Exemption Justification

* No currently Fedora distributions have been tested.
* The last tested version (Fedora 34) has been end-of-life since [2022-06-07][eol].

[eol]: https://docs.fedoraproject.org/en-US/releases/eol/

### Progress

* PowerShell/PowerShell-Docker#686

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by xtqqczze** [comment]
Support for all Fedora release containers was removed in PowerShell/PowerShell-Docker#654.

Last commit of dependencies before deletion:
https://github.com/PowerShell/PowerShell-Docker/blob/1c3b285c4d3ae6d22dfde83e4964e3a35e6c5627/release/7-3/fedora34/test-deps/docker/Dockerfile
https://github.com/PowerShell/PowerShell-Docker/blob/1c3b285c4d3ae6d22dfde83e4964e3a35e6c5627/release/7-3/fedora34/test-deps/meta.json

**Comment by theJasonHelmick** [comment]
Hello @xtqqczze -- thank you for the request.  CentOS and Fedora distributions are no longer supported. The versions of these operating systems that were supported have reached their end-of-life dates. We are not supporting any newer versions. We've documented this [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2)

There are many distributions of Linux that are not officially supported by Microsoft. In some cases, PowerShell may be supported by the community for these releases. For more information, see [Community support for PowerShell on Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/community-support?view=powershell-7.2).

**Comment by xtqqczze** [comment]
> We are not supporting any newer versions. We've documented this [here](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2)

Thanks for linking to the documentation, I was not aware a decision had been made to drop support for Fedora.

Perhaps the PowerShell Committee could reconsider support for Fedora 36 once dotnet/core#7676 is completed?
