### ISSUE TITLE
As Administrator: Remove-AppxProvisionedPackage: Access is denied.

### ISSUE THREAD

**Issue by penalvch-zz** [PowerShell/PowerShell#17863]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with the following commands on Windows 11 for ARM Insider Preview. It is not reproducible with Windows PowerShell built-in (i.e. PowerShell 7.2.5 bug):

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.BingNews'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.BingWeather'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.GetHelp'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.MicrosoftStickyNotes'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.WindowsCamera'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.Windows.Photos'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.WindowsCalculator'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.Windowscommunicationsapps'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.Xbox.TCUI'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.XboxGameOverlay'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.XboxIdentityProvider'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.XboxSpeechtotextoverlay'} |Remove-AppxProvisionedPackage -online
Remove-AppxProvisionedPackage: Access is denied.

Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.ZuneVideo'} |Remove-AppxProvisionedPackage -Online
Remove-AppxProvisionedPackage: Access is denied.

### Expected behavior

```console
See above.
```

### Actual behavior

```console
See above.
```

### Error details

```console
get-error

Exception             :
    Type       : System.Runtime.InteropServices.COMException
    ErrorCode  : -2147024891
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.2.5.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Access is denied.

    Source     : System.Management.Automation
    HResult    : -2147024891
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
CategoryInfo          : NotSpecified: (:) [Remove-AppxProvisionedPackage], COMException
FullyQualifiedErrorId : Microsoft.Dism.Commands.RemoveAppxProvisionedPackageCommand
InvocationInfo        :
    MyCommand        : Remove-AppxProvisionedPackage
    ScriptLineNumber : 1
    OffsetInLine     : 95
    HistoryId        : 68
    Line             : Get-AppxProvisionedPackage -Online | Where-Object {$_.DisplayName -eq 'Microsoft.ZuneVideo'} |Remove-AppxProvisionedPackage -Online
    PositionMessage  : At line:1 char:95
                       + … ame -eq 'Microsoft.ZuneVideo'} |Remove-AppxProvisionedPackage -Online
                       +                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Remove-AppxProvisionedPackage
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.25158
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Are you running your shell as administrator? `Get-AppxProvisionedPackage -Online` needs elevated privileges to work.

**Comment by StevenBucher98** [comment]
Hmm I am unable to reproduce on my Windows 11 machine (not ARM preview), not sure of nuances from that particular version to mine that may be causing this...
