### ISSUE TITLE
powercfg /batteryreport /output "C:\battery-report.html" funktioniert auch unter Powershell 7.2 nicht

### ISSUE THREAD

**Issue by ber999** [PowerShell/PowerShell#17862]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

powercfg /batteryreport /output "C:\battery-report.html" funktioniert auch unter Powershell 7.2 nicht.

### Expected behavior

```console
PS creates report
```

### Actual behavior

```console
PS does nothing
```

### Environment data

```powershell
PS C:\Program Files\PowerShell\7> psversiontable
psversiontable: The term 'psversiontable' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jhoneill** [comment]
I'm assuming you are running elevated ? 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/16209593/183694292-ac847689-b1cb-43f7-8916-3062ca75e4eb.png">
