### ISSUE TITLE
Invoke-RestMethod Post unicode body data will become a question mark

### ISSUE THREAD

**Issue by kkbruce** [PowerShell/PowerShell#17872]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run this script, body includes Unicode text:

```
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/json")

$body = "{
`n    `"Hello`":`"測試`"
`n}"

$response = Invoke-RestMethod 'https://eob3ypv44n7x2sm.m.pipedream.net' -Method 'POST' -Headers $headers -Body $body
$response | ConvertTo-Json
```

### Expected behavior

```console
Get unicode text in body data.
```

### Actual behavior

```console
get two ?? data.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

I use https://requestbin.com service to get the test results:

![image](https://user-images.githubusercontent.com/2024682/184128386-89cb9063-84b8-467e-b493-f64bf75ad615.png)

**Comment by 237dmitry** [comment]
> Get unicode text in body data.

There is not `body` property:
```
{
  "about": "Pipedream is the fastest way to connects APIs. Build and run workflows with code-level control when you need it — and no code when you don't.",
  "event_id": "2DDHXkQxFcwKqHOBBIiPu6LboWi",
  "workflow_id": "p_JZCxaKP",
  "owner_id": "u_7bheL12",
  "deployment_id": "d_5ZsaMoG9",
  "timestamp": "2022-08-11T14:06:16.979Z",
  "inspect": "https://pipedream.com/@/p_JZCxaKP",
  "quickstart": "https://pipedream.com/quickstart/"
}
```

**Comment by kkbruce** [comment]
@237dmitry 

My negligence is that pipedream.com is a service that needs to log in to see the results.

I change another service:

```
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/json")

$body = "{
`n    `"Hello`":`"您好`"
`n}"

$response = Invoke-RestMethod 'https://www.toptal.com/developers/postbin/1660271986467-6472524027340
' -Method 'POST' -Headers $headers -Body $body
$response | ConvertTo-Json
```

After running the script, you can check the results of POST at the following URL:

https://www.toptal.com/developers/postbin/b/1660271986467-6472524027340

like this:

![image](https://user-images.githubusercontent.com/2024682/184275893-6d461595-fc46-4471-9872-0465fb3ab6d5.png)

**Comment by 237dmitry** [comment]
> I change another service

404 - Not Found

**Comment by kkbruce** [comment]
@237dmitry 

Sorry again. confirm https://www.toptal.com/developers/postbin/api#create-bin docs,  

> This bin is value for 30 mins after which time it will cease to exist and all operations on it will fail.

You can easily use https://www.toptal.com/developers/postbin/ service to create a test Url, then replace it to test code.

I'm just looking for an easy place to reproduce the problem, but I think it's not the problem itself since I've attached pictures of the test results.

**Comment by 237dmitry** [comment]
I confirm "Hello: ??"

Win-11, Linux, pwsh 7.2.5

**Comment by kasini3000** [comment]
It doesn't look like a bug, is it that you didn't encode the message?
eg:
```powershell
$body = "xxx"
$body2 = [System.Text.Encoding]::UTF8.GetBytes($body) 
Invoke-RestMethod -Body $body2
```

**Comment by CarloToso** [comment]
You can solve this issue by editing the charset encoding like this:

`
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", "application/json; charset=utf-8")
`
PR #18219 solves this issue by setting charset encoding to UTF8 by default
