### ISSUE TITLE
Public PowerShell extension for VSCode needs to be updated to work with PowerShell opensource

### ISSUE THREAD

**Issue by hiteshraigandhi** [PowerShell/PowerShell#1788]
@daviwil has this code in private repo. This needs to be made public along with PowerShell repo.

**Comment by andschwa** [comment]
@daviwil this was resolved right?

**Comment by daviwil** [comment]
Ahhh yep, happened on launch day :)

**Comment by andschwa** [comment]
I thought so 😄
