### ISSUE TITLE
$ErrorView = 'NormalView' leaves the console in Error color after rendering an ErrorRecord

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#17885]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Repro steps:
1. Open the latest PowerShell preview.7, and make sure using the default prompt
2. Run `$ErrorView = 'NormalView'`
3. Run `Write-Error 'error'`

This is a bug introduced by https://github.com/PowerShell/PowerShell/pull/17705.
The `Cosnole.ForegroundColor` and `Console.BackgroundColor` were changed but never set back after writing out the message.

https://github.com/PowerShell/PowerShell/blob/1ee27cf7dffeb0175dc42dcd47c39e1725c91b67/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1299-L1307

### Expected behavior

```console
The prompt after executing `Write-Error 'error'` doesn't have the color changed
```

### Actual behavior

```console
The prompt gets changed to the error color
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.7
PSEdition                      Core
GitCommitId                    7.3.0-preview.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/127450/184422300-f1ebe59e-3cc0-42eb-a393-acdfe6a56bd9.png)

**Comment by nightroman** [comment]
I experience this regression in the just released PowerShell 7.2.6.
PowerShell 7.2.5 works as expected.
