### ISSUE TITLE
Powershell v7.2.6 was not published to WinGet

### ISSUE THREAD

**Issue by baget** [PowerShell/PowerShell#17892]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following command
```powershell
winget show --id Microsoft.PowerShell
```

to see which version exists on the servers

### Expected behavior

```console
Powershell v7.2.6 in winget
```

### Actual behavior

```console
❯ winget show --id Microsoft.PowerShell
Found PowerShell [Microsoft.PowerShell]
Version: 7.2.5.0
Publisher: Microsoft Corporation
Publisher Url: https://github.com/PowerShell/PowerShell/
Publisher Support Url: https://github.com/PowerShell/PowerShell/issues
Author: Microsoft Corporation
Moniker: pwsh
```

### Error details

```console
Version 7.2.5.0 is installed


❯ winget show --id Microsoft.PowerShell
Found PowerShell [Microsoft.PowerShell]
Version: 7.2.5.0
Publisher: Microsoft Corporation
Publisher Url: https://github.com/PowerShell/PowerShell/
Publisher Support Url: https://github.com/PowerShell/PowerShell/issues
Author: Microsoft Corporation
Moniker: pwsh
```
```


### Environment data

```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/2453522/184499698-01d82cfa-29b3-4aa6-95af-57abbe64b02a.png)

**Comment by mdanish-kh** [comment]
The new version should be available now https://github.com/microsoft/winget-pkgs/pull/69586. At the moment it does not contain all installers, specifically the `msix` installers as those have not been released yet in the latest version.

**Comment by kilasuit** [comment]
Winget has their own repository for packages, like chocolatey that is not published to by the PowerShell team

Winget however has had this updated as per this [PR](https://github.com/microsoft/winget-pkgs/pull/69586)
