### ISSUE TITLE
Cannot update to 7.2.6 on Mac OSX

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#17898]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Currently when trying to update to 7.2.6 on OSX, brew can't pick up this version and marks my 7.2.5 as the latest.

### Expected behavior

```console
Expected to be able to install to 7.2.6
```

### Actual behavior

```console
pwsh --version
PowerShell 7.2.5

brew upgrade powershell --cask
Warning: Not upgrading powershell, the latest version is already installed
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELE…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Hi @ArmaanMcleod, we maintain a brew formula in this repo: https://github.com/PowerShell/Homebrew-Tap. You may have to uninstall cask and follow the instructions outlined in that repo in order to get the latest version of PowerShell

**Comment by ArmaanMcleod** [comment]
Thanks @StevenBucher98. Closing issue as its been resolved, thanks for your support 😄
