### ISSUE TITLE
cannot invoke method. method invocation is supported only on core types in this language mode

### ISSUE THREAD

**Issue by twangithub** [PowerShell/PowerShell#17900]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

![image](https://user-images.githubusercontent.com/4607600/184568432-76b22dbe-f4cb-4f5e-a576-d8be90692481.png)

when i  use the windows vscode ternimal , it happens here

It used to be normal at version 7.2.4, the 7.2.5, 7.2.6 happens still when i update.

### Expected behavior

```console
1
```

### Actual behavior

```console
1
```

### Environment data

```powershell
PS C:\Users\86137> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fflaten** [comment]
It's due to the new shell integration that's default on it VSCode 1.70.

It won't work when PowerShell is set to RestricedLanguage or ConstrainedLanguage (I guess this in your case) due to use of .NET methods like `[Console]::Write()`

Try disabling the shell integration using VSCode setting `"terminal.integrated.shellIntegration.enabled": "false"`

**Comment by fflaten** [comment]
Side note: that squiggly line shouldn't target the subexpression, but the method. 

Subexpressions are allowed in both modes, so it's not the string interpolation. So that's a bug.

**Comment by daxian-dbw** [comment]
@fflaten Thanks for the answer!
About the squiggly line, I just opened a separate bug to track it: https://github.com/PowerShell/PowerShell/issues/17918

**Comment by 5hanuj44nuththara** [comment]
![Screenshot 2023-02-16 161535](https://user-images.githubusercontent.com/125130443/219344282-51f75e54-a820-42a9-9811-73ce72c6fc64.png)
can you please help me with this
