### ISSUE TITLE
Missing arm64 version for Docker image

### ISSUE THREAD

**Issue by gerhard** [PowerShell/PowerShell#17915]
### Summary of the new feature / enhancement

Our CI pipeline would benefit from an `arm64` version of the Docker image. Context: https://github.com/dagger/dagger/pull/2942#issuecomment-1218143578

Our current issue when running on Docker for Mac ARM:

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/3342/185232655-054f05fd-7949-4710-b85e-e86f7c0dc359.png">

At this point, I am just wondering if this is feasible - I don't know enough about this area. Thank you!

cc @brittandeyoung @nabsul @cdhunt @ganeshkumar5699 @brendandburns

### Proposed technical implementation details (optional)

I am assuming that building a Docker image on `arm64` will suffice, but I don't know enough about your Docker build system. While I can see [`arm64` versions of PowerShell in the last release](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.6), I don't know how the official Docker image is built: https://hub.docker.com/_/microsoft-powershell?tab=description

**Comment by rhubarb-geek-nz** [comment]
[Please provide docker hub tags for ARM64](https://github.com/PowerShell/PowerShell-Docker/issues/520)
