### ISSUE TITLE
Question about correct folder storing modules 

### ISSUE THREAD

**Issue by dingmeng-xue** [PowerShell/PowerShell#17919]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Below is the output of paths of PowerShell module
```
PS C:\Dev >  $env:PSModulePath -split ';'
C:\Users\dummy\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\dev\powershell-7.2.1-win-x64\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
```

I **created** folder `MicrosoftGraph` under folder modules and copy/paste `Microsoft.Graph` modules to that folder. `Get-Module` shows me module is there.

```
PS C:\Dev >  get-module Microsoft* -ListAvailable

    Directory: C:\Users\dummy\Documents\PowerShell\Modules\MicrosoftGraph

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.11.0                Microsoft.Graph.Applications        Core,Desk {Add-MgApplicationKey, Add-MgApplicationPassword, Add-MgServicePrincipalKey, Ad…
Script     1.11.0                Microsoft.Graph.Authentication      Core,Desk {Connect-MgGraph, Disconnect-MgGraph, Get-MgContext, Get-MgProfile…}
Script     1.4.2                 Microsoft.Graph.Users               Core,Desk {Get-MgUser, Get-MgUserCreatedObject, Get-MgUserCreatedObjectByRef, Get-MgUserD…
......
```

### Expected behavior

Not sure whether module can be imported or not. If no, why do those modules show up under that folder? I do the similar thing for Azure PowerShell module. I created folder Az and put all Azure PowerShell under folder Az. But `Get-Module Az* -ListAvailable` cannot show them.

Original question comes from https://github.com/Azure/azure-powershell/issues/19246

### Actual behavior

But those module cannot be imported. The error is below

```console
PS C:\Dev> import-module MicrosoftGraph\Microsoft.Graph
import-module : The specified module 'Microsoft.Graph.Authentication' with version '1.11.0' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ import-module MicrosoftGraph\Microsoft.Graph
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Microsoft.Graph.Authentication:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

### Environment data

```powershell
PS C:\Dev >  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by kilasuit** [comment]
@dingmeng-xue apologies on delayed response on this but this is by design and the way you've put this is akin to storing all your submodules/dependencies in one folder, when we prefer being able to make use of them across other modules as to optimise and reduce disk space requirements.

We by design don't show dependencies that are bundled that way to reduce bloat in the module analysis cache that is used by Get-Command/Import-Module and other similar core cmdlets to the engine.

Hope that response helps you better understand how this all works under the hood.
