### ISSUE TITLE
Set-AuthenticodeSignature wrong HashAlgorithm

### ISSUE THREAD

**Issue by liesauer** [PowerShell/PowerShell#17912]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

i am trying to use `SHA384`
```
Set-AuthenticodeSignature -HashAlgorithm SHA384
```

### Expected behavior

```console
sign the file with SHA384
```

### Actual behavior

```console
sign the file with SHA256
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/8676741/185059838-93c6b1c1-2e14-4284-bd90-69a8183956c1.png)

this is what i am expected
![image](https://user-images.githubusercontent.com/8676741/185060224-9df21177-3d53-4790-95a8-8cec41103a0b.png)

**Comment by NoMoreFood** [comment]
I was able to reproduce. At first glance, it looks like it's getting into CryptUIWizDigitalSign() using the correct has OID, but then CryptUIWizDigitalSign() just seems to ignore it and sign with SHA256. It looks like signtool, which works, uses SignerSignEx2(). I'm curious is the Microsoft guys have any thoughts/opinions.

**Comment by PaulHigin** [comment]
I can verify that the `Set-AuthenticodeSignature` is using the provided hash algorithm (SHA384) oid when calling the Windows API.  However, the actual file signature is always the same regardless of what hash algorithm I choose.  So it does appear that the `CryptUIWizDigitalSign` API is ignoring the provided hash algorithm, and defaulting to SHA256.  I see the same behavior with WindowsPowerShell 5.1, so this does not appear to be a regression after @jborean93 refactor of this code.

We will need to check with internal teams to find out why the API is behaving this way.

**Comment by NoMoreFood** [comment]
@PaulHigin Did you ever talk to the internal teams on this?
