### ISSUE TITLE
Problem with "get-help select-string"

### ISSUE THREAD

**Issue by lmgr1992** [PowerShell/PowerShell#17920]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In Powershell Core 7.2.6 on Windows 11, type "get-help select-string" command and press enter.

### Expected behavior

```console
The help of the command select-string
```

### Actual behavior

```console
It doesn't show me the help but a bunch of characters, which I think mean languages and countries.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![WindowsTerminal_bPG0ZwLpXk](https://user-images.githubusercontent.com/95189964/185482840-51c6dc52-14a4-41c2-9c2a-0e5f4f65c97b.png)

**Comment by MartinGC94** [comment]
Maybe the syntax diagrams should have a limit on how many values it can show? The validateset attribute for Select-String has 816 values which is obviously not very useful to display by default.  
The online version doesn't include these valid values so if you update your help with `Update-Help` it you can avoid this problem.

**Comment by dkaszews** [comment]
Agreed that it's quite annoying, have run into it in the past. Truncating the `ValidateSet` output by default seems like a good solution.

**Comment by jhoneill** [comment]
You are getting the correct text when the help file for `Select-string`  is absent. 

What happens with no help file,  is `Get-Help` looks at the command's parameter-sets and for each one it builds a block under "syntax". Then for each parameter it looks to see what type it is, and if it has prescribed values in a validateSet or an enum.   The screen shot shows it works through `-Pattern` and `-Path` before it gets to `-culture`, and it will have `-SimpleMatch` `-CaseSensitive` etc after that. 
As @MartinGC94  says there is a LOT in the validate set for `-culture`, and `Get-Help` inserts the equivalent of
```
"{" +( (Get-Command Select-String).parameters["culture"].attributes[1].validvalues -join " | ") + "}"
```
 And repeats it for each of the six parameter sets which have a -culture parameter. So we get a lot, six times over. 

The default help text should end 

```
REMARKS
    Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help.
        -- To download and install Help files for the module that includes this cmdlet, use Update-Help.
```

**So the primary fix is to install help.** 
But in in some situations that's not an option (e.g. PowerShell installed from a private repo on a server without internet access).  As @dkaszews  says stopping the list after a certain number of items might be smarter. They can be stopped **at source** by putting something into https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs    (see from line 251 to 348 ) that limits the number of values from an enum or validate set. 
But if someone creates a help file with a stupid number of parameter values in a parameter value group, they will still be displayed. Maybe we want to honour what is in file on all occasions, but if not the change can be made **at output time**. I'm not sure where it stored in pwsh, but the formatting for _Windows PowerShell_ is defined by C:\Windows\System32\WindowsPowerShell\v1.0\Help.format.ps1xml  - in that file its line 212 which builds the output with
```
 " {$($_.ParameterValueGroup.ParameterValue -join ' | ')}"
 ```
It would be fairly easy (I think) to make that `$_.ParameterValueGroup.ParameterValue[0..20]`  and get only the first 20 values. 

If people think either option is worthwhile, a new issue can be opened asking for that.  (Upvote this comment enough and I'll do it!)

**Comment by dkaszews** [comment]
@jhoneill Sounds good, nice to see somebody already found the code in question! If possible, truncating to fixed length (rather than count) would probably provide nicer looking results, let's say 100 chars. That means for the locale in original issue we can display 100/7=14 items, while if the items were much longer, they wouldn't flood the screen again. Just remember to put a `...` at the end to indicate truncation:

```powershell
$values = " {$($_.ParameterValueGroup.ParameterValue -join ' | ')}"
if ($values.Length -gt 100) {
    $values = $values.Substring(0, 100) -replace '\|[^|]*' + '...'
}
```

For tests, best to just create couple noop functions with parameters with large validation sets.

**Comment by jhoneill** [comment]
@dkaszews  Yes. I've been experimenting with it this morning, 
```
$values = " {$($_.ParameterValueGroup.ParameterValue -join ' | ')}"  -replace "(^.{100}).*$", '$1' -replace "(^.*) \| .*[^}]$", '$1 | ... }'
```
Truncates at the 100 chars and if that cuts the closing  "}" it removes the last | and anything after it and puts "| ... }" saving an if statement :-) 

It looks `Get-FormatData` does list the types for help and trying to load a version of the help.ps1xml file doesn't have the desired effect. Nor does replacing the file in PowerShell 5. So I'm not exactly sure where the change needs to be made. But I can push it forward with the cmdlet working group if it seems like there is a demand for it.

**Comment by dkaszews** [comment]
@jhoneill I don't see a benefit in skipping the `if` statement, as depending on how efficient PowerShell implementation of regex is, you may waste a lot of time running complicated replacements just to do nothing.
