### ISSUE TITLE
failure in download file via invoke-restmethod or invoke-webrequest is suppressed and results in partial file download

### ISSUE THREAD

**Issue by AAATechGuy** [PowerShell/PowerShell#17931]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For context, 

See detailed analysis here: https://github.com/PowerShell/PowerShell/pull/17896#issuecomment-1214674697

See @iSazonov 's comment https://github.com/PowerShell/PowerShell/pull/17896#issuecomment-1219117740

> It is not easy to get an exception from the copy task. I disconnected network for ~1 minutes and restore it. Original cmdlet waits some seconds and silently stop with semi-downloaded file. With the change (without catching AggregateException) user get follow error:
![image](https://user-images.githubusercontent.com/3484074/185506928-f4f6ee47-a70b-4955-ae6d-290ca43d93df.png)
I think it is right behavior and we should remove the regression.

### Expected behavior

Throw an exception if download fails.

### Actual behavior

Does not throw an exception if download fails.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by ahmad-beshr** [comment]
I have the same behavior. The downloaded file is too small compared to the actual file. Is there any resolution for this? 
This is what I am using:
`Invoke-RestMethod -Uri $arm_file_uri -Method Get -ContentType "application/Json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} | Out-File $server_file_Path -Force`

**Comment by iSazonov** [comment]
@ahmad-beshr You should use latest daily build.
