### ISSUE TITLE
Batch script that returns ERRORLEVEL 1 in CMD returns $LASTEXITCODE 0 in PowerShell

### ISSUE THREAD

**Issue by sbj42** [PowerShell/PowerShell#17936]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When PowerShell runs a batch script which has `EXIT /B 1`, it generally sets `$LASTEXITCODE` to 1 and `$?` returns false.  But I found a case where it does not.  The follow batch script:
```bat
@ECHO OFF
(
    EXIT /B 1
    echo unreachable
)
```

Returns ERRORLEVEL 1 in `cmd`, but `$LASTEXITCODE` 0 in `pwsh`.  If `EXIT /B 1` is the last command in a code block, then it works as expected.  But if there are any commands after it then `$LASTEXITCODE` isn't set correctly.

### Expected behavior

```console
PS> .\test.bat
PS> $?
False
```

### Actual behavior

```console
PS> .\test.bat
PS> $?
True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
1 The culprit is the "brackets" that cause multiple lines to execute together.
2 You shouldn't write code like this.
3 For $LASTEXITCODE, I personally think it is as expected.
4 (exit 1 ; Write-Output 'aa' ) such powershell code will report an error, and $LASTEXITCODE = 0,
For bat, I think the same should be done.
At present, the step of reporting an error is missing.
5 I am very interested, what do you think?

**Comment by sbj42** [comment]
Regarding 1 and 2: Naturally the example I gave was not from a useful `.bat` script.  It was a simplification of a real-world script, which looks more like this:
```bat
REM some argument parsing before this
IF ["%ARG%"] == ["xyz"] (
    FOR %%T IN (dir1, dir2, dir3) DO (
        (pushd %%T && CALL build.bat %REST% && popd) || EXIT /B 1
    )
    EXIT /B 0
)
REM some other cases after this
```

So you see, in this case the `EXIT /B 1` is a way to exit the script early in case one of the loop iterations fails.  Even though there are no "extra commands" after that exit, it still returns `$LASTEXITCODE` 0.

Regarding 3 and 4: Perhaps there is some reason why powershell returns exit code 0 from `(exit 1; Write-Output 'aa')`.  It seems surprising to me, since my understanding is that `exit 1` should set the exit code and also stop the script.  So I don't see why the presence of commands that aren't run would "clear" the exit code.  Maybe it would be worth mentioning in [the documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-7.2&viewFallbackFrom=powershell-6#exit).

**Comment by scriptingstudio** [comment]
Powershell returns exit code of cmd shell, not your script.
So your "Actual behavior" is correct.

**Comment by sbj42** [comment]
@scriptingstudio after some testing I think I understand your comment, please tell me if I'm wrong:

I think you're saying that PowerShell executes `cmd /c ".\test.bat"` (or something similar).  It then sets lastexitcode to the exit code the `cmd.exe` process.

I tested in `cmd` and confirmed that while the command `test.bat` returns errorlevel 1, `cmd /c test.bat` returns errorlevel 0!  As described before that discrepancy happens only when there are additional commands in a code block after the `exit /b`.

So it seems the conclusion here is that if this is a bug, it is a bug in `cmd.exe` and not in PowerShell.

**Comment by sbj42** [comment]
If desired, PowerShell could work around the bug by running something like `cmd /c ".\test.bat && exit /b %errorlevel%"`

**Comment by scriptingstudio** [comment]
The doc states about `$lastexitcode`, `Contains the exit code of the last native program that was run.` The key word is `native`. In your case native program is `cmd.exe`.
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.2#lastexitcode

**Comment by 237dmitry** [comment]
> The key word is native. In your case native program is cmd.exe

Why then this batch returned errorlevel corectly?

```
@echo off
exit /b 666
echo unreachable
```

**Comment by scriptingstudio** [comment]
> Why then this batch returned errorlevel correctly?

different scope
``` cmd
EXIT [/B] [exitCode]

  /B          specifies to exit the current batch script instead of
              CMD.EXE.  If executed from outside a batch script, it
              will quit CMD.EXE

  exitCode    specifies a numeric number.  if /B is specified, sets
              ERRORLEVEL that number.  If quitting CMD.EXE, sets the process
              exit code with that number.
```

**Comment by 237dmitry** [comment]
> different scope

Is this different scope?
```
@echo off
(
    echo reachable
    exit /b 555
)
```

**Comment by monoblaine** [comment]
For folks whose research resulted in this page, here is the only solution that worked for me:

```
cmd /v:on /c ".\test.bat & exit /b !ERRORLEVEL!"
```

An `echo $LastExitCode` after the above command gives us the value of `ERRORLEVEL`.

`cmd /v:on` enables "delayed environment variable expansion" (source: https://ss64.com/nt/cmd.html) and I guess it's required in order to get the real value of `ERRORLEVEL`:

> this allows a FOR loop to specify !variable! instead of %variable% expanding the variable at execution time instead of at input time.

<blockquote><div><strong><a href="https://ss64.com/nt/cmd.html">CMD.exe (Command Shell) command - Windows CMD</a></strong></div></blockquote>
