### ISSUE TITLE
`pwsh -f <ps1-file>` fails to run in system lockdown environment if the `ps1-file` is signed (trusted)

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#17932]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a report from internal customer:
On a machine with Applocker (WDAC) enforcement, PowerShell runs in `ConstainedLanguage` mode by default. Running `pwsh -file <ps1-file>` fails with the following error when the `ps1-file` is signed (trusted).

![image](https://user-images.githubusercontent.com/127450/185546764-30f1147a-bacd-4f27-a477-4c0c99ab3239.png)
![deleteme](https://user-images.githubusercontent.com/127450/185547003-fda74273-5be0-40d3-a6e3-b1f1d26dce15.png)

---------------------

The problem is -- the user doesn't dot-source `CreateShortCut.ps1`, but just run it with `powershell -file`.

The root cause here is that `powershell.exe -f <ps1-file>` attempts to invoke the ps1 file without using a local scope, which is the same behavior as if it’s dot-source invoked.
In `ConsoleHost.cs`, it creates a `Command` instance with `Command(filePath, isScript: false, useLocalScope: false)`.

PowerShell core (pwsh) also does the same thing, and hence `pwsh -f <ps1-file>` will fail too in this case:

https://github.com/PowerShell/PowerShell/blob/8d25b5ae6e2eb83a957eac823c27546a70c229a0/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L1907-L1909

### Expected behavior

```console
`powershell -f <ps1-file>` and `pwsh -f <ps1-file>` should run no matter `ps1-file` is signed (trusted) or not in the WDAC locked down environment.
```

### Actual behavior

```console
`powershell -f <ps1-file>` and `pwsh -f <ps1-file>` fail to run.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I see the file is on network share? Can the customer put the file locally and check?

**Comment by daxian-dbw** [comment]
It works fine when the script is not signed (trusted). Quote the customer's words here:
> If he makes script not trusted, he gets event that script not allowed to run in applocker log, but it works as expected.

**Comment by PaulHigin** [comment]
So as not to introduce a breaking change, I feel the best solution is to add a new command parameter, something like: `-FileNewScope`, which runs the file script in a new scope rather than the global scope as it does now.

This is not a security issue, so I am removing the @wg-security tag.

**Comment by PaulHigin** [comment]
Note that there is a workaround (using `-command '& c:\filepath\filename.ps1`), so I feel this is not super high priority.

**Comment by JamesWTruher** [comment]
@sdwheeler @michaeltlombardi 
The @PowerShell/wg-powershell-engine discussed this a we're worried about making a behavioral change, but the way PowerShell behaves when using `-file` should definitely be documented.

**Comment by sdwheeler** [comment]
@daxian-dbw Can you open a doc issue for this?

**Comment by daxian-dbw** [comment]
It turns out the `-File` already calls out the `dot-sourcing` behavior in its doc:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.3#-file---f

> This is the default parameter if no parameters are present but values are present in the command line. The specified script runs in the local scope ("dot-sourced") of the new session,

@JamesWTruher @SeeminglyScience Do you think we should add additional information about this particular scenario -- using a singed .ps1 file for `pwsh -file` in a locked down system?

**Comment by SeeminglyScience** [comment]
> @JamesWTruher @SeeminglyScience Do you think we should add additional information about this particular scenario -- using a singed .ps1 file for `pwsh -file` in a locked down system?

Eh, I think it's fine as is.
