### ISSUE TITLE
PowerShell 7.2.6 doesn't ignore a module that requires 7.3

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#17942]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install `Microsoft.PowerShell.Archive 2.0.1-preview2` in user scope
2. Modify the incorrect (https://twitter.com/Steve_MSFT/status/1561009864784384002?s=20&t=gvVFcVRDXx9-OzGIBPGGPA)  manifest so that it specifies that 7.3 is required
![image](https://user-images.githubusercontent.com/12860484/185787205-098f8182-3a13-4602-9c81-b5c2c041fd71.png)

3. Launch PowerShell 7.2.6
4. Attempt to run `Compress-Archive`

### Expected behavior

```console
Compress-Archive from the built-in version 1 of Microsoft.PowerShell.Archive module should run
```

### Actual behavior

```console
PowerShell attempts to load version `2.0.1-preview2` of `Microsoft.PowerShell.Archive` and fails:

PS C:\Program Files\PowerShell\7> compress-archive
compress-archive: The 'compress-archive' command was found in the module 'Microsoft.PowerShell.Archive', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Archive'.
PS C:\Program Files\PowerShell\7> import-module microsoft.powershell.archive
Import-Module: The version of PowerShell on this computer is '7.2.6'. The module 'C:\Users\steph\OneDrive\Documents\PowerShell\Modules\microsoft.powershell.archive\2.0.1\microsoft.powershell.archive.psd1' requires a minimum PowerShell version of '7.3' to run. Verify that you have the minimum required version of PowerShell installed, and then try again.
```

### Error details

```console
PS C:\Program Files\PowerShell\7> get-error

Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The 'compress-archive' command was found in the module 'Microsoft.PowerShell.Archive', but the module could not be
loaded. For more information, run 'Import-Module Microsoft.PowerShell.Archive'.
            HResult : -2146233087
        TargetObject          : compress-archive
        CategoryInfo          : ObjectNotFound: (compress-archive:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 14
            Line             : compress-archive
            PositionMessage  : At line:1 char:1
                               + compress-archive
                               + ~~~~~~~~~~~~~~~~
            InvocationName   : compress-archive
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : compress-archive
    TargetSite  :
        Name          : TryModuleAutoDiscovery
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.2.6.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The 'compress-archive' command was found in the module 'Microsoft.PowerShell.Archive', but the module could not be
loaded. For more information, run 'Import-Module Microsoft.PowerShell.Archive'.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String
originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception&
lastError)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements,
CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : compress-archive
CategoryInfo          : ObjectNotFound: (compress-archive:String) [], CommandNotFoundException
FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 14
    Line             : compress-archive
    PositionMessage  : At line:1 char:1
                       + compress-archive
                       + ~~~~~~~~~~~~~~~~
    InvocationName   : compress-archive
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\Program Files\PowerShell\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Program Files\PowerShell\7> $env:PSModulePath -split ';' | % { $mp = join-path -path $_ -childpath 'Microsoft.PowerShell.Archive'; if (Test-Path -LiteralPath $mp) { gci -rec $mp -filter 'm*.psd1' } }

    Directory: C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\Microsoft.PowerShell.Archive\2.0.1

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          2022-08-20    19:33          16210 Microsoft.PowerShell.Archive.psd1

    Directory: C:\Program Files\PowerShell\7\Modules\Microsoft.PowerShell.Archive

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2020-02-11    19:01          13503 Microsoft.PowerShell.Archive.psd1

    Directory: C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2019-12-07    10:10            457 Microsoft.PowerShell.Archive.psd1

PS C:\Program Files\PowerShell\7> gcm *archive

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Compress-Archive                                   1.2.5      Microsoft.PowerShell.Archive
Function        Compress-Archive                                   1.0.1.0    Microsoft.PowerShell.Archive
Function        Expand-Archive                                     1.2.5      Microsoft.PowerShell.Archive
Function        Expand-Archive                                     1.0.1.0    Microsoft.PowerShell.Archive
Cmdlet          Compress-Archive                                   2.0.1      Microsoft.PowerShell.Archive
Cmdlet          Expand-Archive                                     2.0.1      Microsoft.PowerShell.Archive
```

### Visuals

![image](https://user-images.githubusercontent.com/12860484/185787354-8bdb9349-de26-4022-a7cb-09e3e2f9cb45.png)

**Comment by kilasuit** [comment]
This is currently by design & has been since PowerShell 5. This is due to how we look to import the the latest version of a module that has that command & do not fall back to a prior version automatically.
Could this be changed, sure. Will it, I don't think so as how are we meant to know all the reasons when or why we should fall back. Could we build some form of checking mechanism for things like this, sure, but is it worth the issue, when the workaround is to call `Import-Module` with the `RequiredVersion` parameter or for in scripts make use of the `#requires statement` to force correct module version loading which I detailed in this [twitter thread ](https://twitter.com/ryanyates1990/status/1555257498113802244) and explicitly state why in this [comment in the thread](https://twitter.com/ryanyates1990/status/1555377599949455360?s=20&t=7gIJG_rCSc0msXoKTHickQ)

**Comment by SteveL-MSFT** [comment]
In this case, the module manifest declares the min version of PowerShell required, so if you are using 7.2 and the module requires 7.3, then module discovery should skip that one and continue looking.  If someone explicitly tries to import a specific module and that isn't compatible, then the error is be design.

**Comment by sba923** [comment]
Thanks @SteveL-MSFT for your comment. Wasn't my description of the issue clear enough to point at _implicit_ module loading?

**Comment by kilasuit** [comment]
@SteveL-MSFT - I think this also depends on the ordering of the entries in PSModulePath in which if you say have module version 5 in user path and 6 in the system path, if the user path is first it loads that one and not the latest version. What I don't think works is that it loads 

Having just tested this  in 7.2.6 with a Test Module requiring PowerShell 8.0 as a minimum in the System path and one in the user path that doesn't specify a version, with user path first the working module will load, however if you switch the ordering and puth user path at the end of PSModulePath and run `Get-Command TestMod -Refresh -All -ListAvailable` to rebuild the Module Analysis Cache, then Get-Command will show the following and any attempt to load doesn't load the module or the one that should work that is in the user path

![image](https://user-images.githubusercontent.com/6355225/188202241-6d130153-f069-4f93-b9f0-c0353faa73d0.png)

Also in testing this on 7.3.0-preview7 when both versions are in the User module path it won't auto load the version that will work if there is a version that won't in the same path
I also get the same behaviour in v5.1 too on Windows 11t

So whilst it definitely would be nice for the next version possible to load, I 'd like it if there was also a switch that can be used to opt out of next version loading if the most recent version is not loadable. 
I think the issue becomes `How do we ensure we are loading the right module if not in the same path?` though that's manageable if we compare a set of properties in the module manifest which isn't always properly populated so may not be fully reliable but would be a viable way to do this.

**Comment by SteveL-MSFT** [comment]
@kilasuit I'm not proposing that we do anything in the case the module indicates it is compatible, but doesn't load for other reason (it's incorrectly marked, dependencies missing, etc...).  As we do have many folks running 5.1, PS7 and PS7-preview simultaneously, it would make sense that if the module manifest declares requiring a newer version, then an older version of PS should skip that module and continue it's normal search logic.

**Comment by kilasuit** [comment]
I agree @SteveL-MSFT and captured the above as test cases as currently we don't load the next working version 
1) We can auto load the next working version, which should be a lower version number, regardless of which path in PSModulePaths it is located,
2) We don't break current expectation for those that may not automatically want that to happen - example being in testing/use of preview versions of modules requiring preview versions of PowerShell

Whilst 1 is a definite need 2 is a nice to have IMO
