### ISSUE TITLE
Run cmd file (and no extension) with absolute path opens another terminal/console window

### ISSUE THREAD

**Issue by MSP-Greg** [PowerShell/PowerShell#17954]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using a simple cmd file
```
@echo off
@dir .
```
In a PowerShell window (Terminal), if one runs the cmd file with an absolute path, another window opens and runs the `dir .` command.  

If one runs it with a relative path (starting with `.` or `..`), the command (and output) runs in the PowerShell window.

The above is not using an extension (`.cmd) for the file.  If one adds an extension, the absolute path outputs to the PS window.

Even more interesting, in Terminal, I opened PS Core window, and opened a PS window next to it.  Running in the PS Core with an absolute path and no extension, the file switches to the PS windows and stays there...

PowerShell 5.1.22000.832 has the same issue.

### Expected behavior

```console
see above
```

### Actual behavior

```console
see above
```

### Error details

```console
na
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@MSP-Greg Please add exact examples (repro steps) in OP for every case..

**Comment by MSP-Greg** [comment]
@iSazonov

The issue is intermittent locally.  Haven't had time to determine why, but it's in my TODO list.
