### ISSUE TITLE
Apple Silicon version of Powershell still asking for Rosetta to be installed

### ISSUE THREAD

**Issue by VinceThompson** [PowerShell/PowerShell#17956]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Any version of Powershell (even preview) for M1 Mac OS is still prompting for Rosetta to be installed.  Cannot seem to get this to work natively on Apple Silicon. 

### Expected behavior

```console
Installer should work without prompting for Rosetta.
```

### Actual behavior

```console
Rosetta install pop-up still appears.
```

### Environment data

```powershell
M1 Mac OS running latest version.
```

**Comment by StevenBucher98** [comment]
How are you installing PowerShell? and can you please include what the pop up looks like? I currently have M1 Mac OS that I installed PowerShell via brew and have had no prompts about Rosetta

**Comment by lesiak** [comment]
Output on M2 Mac Air:
```
==> Installing Cask powershell
==> Running installer for powershell; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
installer: This package requires Rosetta 2 to be installed.
                Please install Rosetta 2 and then try again.
                    `sudo softwareupdate --install-rosetta`

installer: Error - PowerShell - 7.2.6 can’t be installed on this computer.
==> Purging files for version 7.2.6 of Cask powershell
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=user1 USER=user1 USERNAME=user1 /usr/sbin/installer -pkg /opt/homebrew/Caskroom/powershell/7.2.6/powershell-7.2.6-osx-arm64.pkg -target /` exited with 1. Here's the output:
installer: This package requires Rosetta 2 to be installed.
                Please install Rosetta 2 and then try again.
                    `sudo softwareupdate --install-rosetta`

installer: Error - PowerShell - 7.2.6 can’t be installed on this computer.
```

**Comment by lyona** [comment]
Setting up a new Mac studio and seeing the same. 

Using the direct link on this [page](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2)

 https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-7.2.6-osx-arm64.pkg

![image](https://user-images.githubusercontent.com/18350616/189750876-1aeadee4-b311-4ed0-864b-e091e171d0f5.png)

**Comment by vandre** [comment]
This is still an issue as of Powershell 7.5.2 @StevenBucher98 . I installed Powershell via the arm64 pkg posted on Github

EDIT: This seems to be a duplicate of https://github.com/PowerShell/PowerShell/issues/17130
