### ISSUE TITLE
Powershell Core Windows Exporer integration disappears after automatic Windows Update

### ISSUE THREAD

**Issue by golden-aries** [PowerShell/PowerShell#17967]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Download PowerShell Core installer PowerShell-7.2.5-win-x64.msi
During installation select options:
- Add 'Open here' context menus to Explorer
- Add 'Run with PowerShell 7' context menu for PowerShell files
- Choose options to allow updating PowerShell through Automatic  Windows Update.
Check that Windows Explorer Integration installed correctly.
Wait until PowerShell updates to version 7.2.6 with Automatic Windows Update.
Observe that Window Explorer Integration disappears

### Expected behavior

```console
Expected: PowerShell Core Windows Explorer Integration should not disappear after automatic Windows Update
```

### Actual behavior

```console
Powershell Core Windows Explorer integration installed with options:
- Add 'Open here' context menus to Exporer
- Add 'Run with PowerShell 7' context menu for PowerShell files
disappears after PowerShell was updated trhough Windows Update.

Environment:

[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19044  0


$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

The previous powershell version installed was 7.2.5
```

### Environment data

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/88808217/186711885-5e9456af-96c6-4ec6-8f2e-7a5dec956765.png)

**Comment by dkaszews** [comment]
Can you show `$PSVersionTable` before the update? `Platform: Win32NT` looks suspicious to me. From my experience with other programs, shell integration is one of the few things that does not work when installing 32bit programs on 64bit system, and the installer you mention is 64bit. So it may be a bug in Windows Update which incorrectly chooses 32bit version when upgrading.

**Comment by dkaszews** [comment]
There are also several options you can try to determine whether PowerShell is 32bit or 64bit https://stackoverflow.com/questions/8588960/determine-if-current-powershell-process-is-32-bit-or-64-bit

**Comment by golden-aries** [comment]
I am not sure how I can to show the $PSVersionTable of already updated version, but since I had installed it in a first place. I know for sure what it was:
```
PS D:\distrib\Microsoft\PowerShell\7.2.5> get-filehash *.msi

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          632A69EA46F966A03A1EE0AA1647C5970DF7B5936BDF27DF3CF18E6C63C21198       D:\distrib\Microsoft\PowerShell\7.2.5\PowerShell-7.2.5-win-x64.msi
		632a69ea46f966a03a1ee0aa1647c5970df7b5936bdf27df3cf18e6c63c21198 *PowerShell-7.2.5-win-x64.msi
```

**Comment by golden-aries** [comment]
To fix the issue I removed  updated version 7.2.6 downloaded installer:
```
PS D:\distrib\Microsoft\PowerShell\7.2.5> get-filehash *.msi

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          632A69EA46F966A03A1EE0AA1647C5970DF7B5936BDF27DF3CF18E6C63C21198       D:\distrib\Microsoft\PowerShell\7.2.5\PowerShell-7.2.5-win-x64.msi
		632a69ea46f966a03a1ee0aa1647c5970df7b5936bdf27df3cf18e6c63c21198 *PowerShell-7.2.5-win-x64.msi
```
and installed it. This is what $psversiontable looks right now:
```
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
it shows Win32NT despite the fact I was installing PowerShell-7.2.5-win-x64.msi

**Comment by golden-aries** [comment]
```
> [Environment]::Is64BitProcess
True
```

**Comment by BenMakesGames** [comment]
> (Are there any other issues open/closed similar to this?)

a few open ones, anyway :P I noticed a new version of PowerShell, and was hoping the change logs would mention this fix. alas.

* https://github.com/PowerShell/PowerShell/issues/18791
* https://github.com/PowerShell/PowerShell/issues/18479
* https://github.com/PowerShell/PowerShell/issues/16886
