### ISSUE TITLE
powershell for mips and mipsel

### ISSUE THREAD

**Issue by Modgames42** [PowerShell/PowerShell#17968]
### Summary of the new feature / enhancement

Hello, please make powershell for linux mips and mipsel, what is it for? so that you can install powershell on a router with entware and execute ps1 scripts (most routers mainly use the mips or mipsel processor architecture and less often arm or arm64)

**Comment by iSazonov** [comment]
PowerShell is based on .Net Runtime. Today it doesn't support MIPS. Tracking issue https://github.com/dotnet/runtime/issues/4234
