### ISSUE TITLE
[BUG] `Out-File`'s `-Width` doesn't do anything

### ISSUE THREAD

**Issue by pcroland** [PowerShell/PowerShell#17970]
I was trying to save my tool's output to a txt
![img](https://telegra.ph//file/c49c502f584b3b557831d.png)
But despite specifying `-Width 150` all lines has been wrapped at 80:
![img](https://telegra.ph//file/6566809cfacca377e11fb.png)
Is there any way to actually disable line wrapping?

Powershell version: 7.2.6

**Comment by kasini3000** [comment]
Weird bug, I can reproduce the problem.
```powershell
$a = '123456789-' * 6
Out-File -InputObject $a -FilePath "${PSScriptRoot}/a.txt"  -Width 11 -Encoding ASCII
Out-File -InputObject $a -Append -FilePath "${PSScriptRoot}/a.txt"  -Width 12 -Encoding ASCII
Out-File -InputObject $a -Append -FilePath "${PSScriptRoot}/a.txt"  -Width 21 -Encoding ASCII
```

But at the same time, I found that the commands in the manual are normal:
$Procs = Get-Process
Out-File -FilePath .\Process.txt -InputObject $Procs -Encoding ASCII -Width 50

**Comment by 237dmitry** [comment]
> Is there any way to actually disable line wrapping?

I don't use `Width` parameter, output did not wrap, the longest line is 121 symbol:
```powershell
PS > ffmpeg --help 2>&1 | Out-File help.txt
PS > [Linq.Enumerable]::Max([int[]] (gc help.txt).Length)
121
```

**Comment by pcroland** [comment]
```ps
[Linq.Enumerable]::Max( [int[]] (gc help.txt).foreach{ $_.Length } )
```
returns 0 for me.

**Comment by jhoneill** [comment]
@pcroland  the wrapping at 80 is coming from the original app.  And looking at the way the text is indented, where re-wrapping it would be mean stripping out  _some_ `[line break][spaces]` combinations, and keeping others is going to be painful. 

I think the help text is wrong or at least misleading.  Your app is sending back strings and let's see what PowerShell does when formatting stuff that is already a string....  

```
> "123456789 " * 5 | out-string -Width 30
123456789 123456789 123456789 123456789 123456789
```

So input is one or more strings `Out-String` just outputs them, but with objects... 

```dir |  out-string -Width 30

Mode             LastWriteTime
----             -------------
la---      18/10/2021    08:39
la---      20/05/2022    15:00
```

Non-strings are **formatted** with a maximum width

To prepare stuff for writing to a file, I think `Out-File`  pushes its input through `Out-String` . So the strings from your app won't have any formatting done to them. 

There are plenty of word wrapping regular expressions out there.   But you could try this (with the caveat that the formatting in that text is going to be nasty )

``` 
MyApp | Foreach-object {$_  -replace  "([^\n]{1,49}\S)(\s+|$)|(\S{50})(?=\S)","`$1`$3`r`n" }
```
the regular expression says  
if you find (49 non-newline characters, followed by a non-space) then either spaces or the end of the line
OR you find (50 non-spaces)  followed by a 51st non space. 
the Put a CR LF after (whichever you found)  

You MIGHT find that putting spaces after the `r`n at the end gives you workable formatting.

**Comment by pcroland** [comment]
The wrapping does not come from the app as you can see in my screenshot. Using
```sh
 | python -c "import sys; open('output.txt', 'w', encoding='utf-8').write(sys.stdin.read())"
```
instead of `out-file` works fine. bash/zsh also works fine, so it's definitely a powershell issue.
