### ISSUE TITLE
Native SQLite support

### ISSUE THREAD

**Issue by scriptingstudio** [PowerShell/PowerShell#17979]
### Summary of the new feature / enhancement

Taking advantage of the fact that Windows 10 now ships with SQLite support built-in (as winsqlite3.dll), it is good idea to implement basic commands to work with SQLite databases.
One can say, there are many modules by community. But native support is better, IMHO.

**Comment by kasini3000** [comment]
> indows 10 now ships with SQLite support built-in (as winsqlite3.dll)
thanks for share news , i don't know this

**Comment by dkaszews** [comment]
Couple technical questions:

1. What about non-Windows platforms? We would need to find good alternatives on Mac and Linux to ensure feature parity. It may turn out that the Windows dll means nothing if we have to reimplement it on other platforms anyways. Better to just grab any other sqlite nuget with right license and support. 
2. Do you want to implement it as `ConvertFrom-Sqlite` to take advantage of existing cmdlets which pretty much have SQL syntax like `Select-Object`, `Where-Object`, etc? Or build the selectors inside the cmdlet to take advantage of internal optimizations? Basically:
    ```pwsh
    Get-Content db.sqlite | ConvertFrom-Sqlite | Select-Object Name, Title | Where-Object { $_.Title -match 'Engineer' }
    # or
    Select-Sqlite -Select Name, Title -Where { $_.Title -match 'Engineer' }
    ```
3. As I mentioned, many cmdlets already provide SQL-like experience. The only one I found missing is `Join` which is provided by excellent [`Join-Object`](https://www.powershellgallery.com/packages/Join/3.7.2). Perhaps we would like to speak to the author about making it standard? No idea how it would proceed, but there is probably some precedence for it, in C++ world fmtlib became part of stdlib in C++20.

**Comment by jhoneill** [comment]
I wrote one of those community modules https://www.powershellgallery.com/packages/GetSQL/1.3.0.4  , which is sql for ODBC, SQLite or SQL server, there are others which are more sqlite focused which have many more downloads. 

@scriptingstudio  the PowerShell team's response to this is pretty standard. Roughly speaking it goes "There are many, many things which people think could usefully be part of the PowerShell distribution, but are in practice served through the gallery.  If all those were included it would turn PowerShell into a bloated monster. We think people should view adding modules as the norm."   Certainly  with chromium-based edge being part of Windows now, and SQLite being integral to chromium (see the gist below), Window has SQLite, but there have been .NET SQLite implementations which are available cross platform which have community support in PowerShell.

@dkaszews  There are multiple tables in a SQLite DB. See https://gist.github.com/jhoneill/e585bae781f3efa7ac1992b79e037713 - for some examples. TBH it needs to be able to run any SQL including inserts / deletes.

**Comment by dkaszews** [comment]
@jhoneill That is a very good point. While useful for many people, I don't see SQLite as a must have builtin, as opposed to JSON and CSV. I would argue that YAML is a more common format that should be integrated into core PowerShell, but there is a decent Gallery module for it so I cannot really complain. Even for people who use SQLite on daily basis, I cannot see them being able to hold ground arguing "I cannot believe it's not built in!" as it's also not builtin into C# or Python, to name a few.

With so many SQLite modules already on Gallery, why bother writing a new one? And why even bother integrating one into core, if all you have to do is run `Install-Module`? Maybe the better way would be for PowerShell team to create a curated list of recommended modules, so you can run `Install-Module -Recommended SQLite` and it will pick the "best".

**Comment by kasini3000** [comment]
I have a question that I would like to ask by the way:
Where can I find the official version, the latest file?
SQLite.Interop.dll
I already have for win-x86-64, linux-x86-64, cpu architecture.
**Now required for linux-arm-64, osx-arm-64.**

**Comment by jhoneill** [comment]
@ImportTaste  I just replied on @jdhitsolutions  repo, but the bits come from Nuget. System.Data.SQLite.Core , there's a little installer which gets the files from Nuget so I don't need to update the package myself and people don't need to trust binaries from me. 
The best thing would be for .NET to incorporate the functionality. 
There is a standard pattern
```
$connection  = New-Object    -TypeName  System.Data.Some_kind_of_Connection  ....
$dataAdapter = New-Object    -TypeName System.Data.matching_kind_off_DataAdapter .... 
$table       = New-Object     -TypeName System.Data.the_only_kind_off_DataTable ....
$dataAdapter.Fill($table) 
```
And it works for the SQL-Server client, ODBC, OLEDB, and SQL Lite and possibly others. So System.data.SQLite very much _does the right thing_  (it doesn't take many `if` statements in Get-SQL to say "If it's SQL-Server ... elseif it's SQLite ... else ..." and all the other stuff I've been playing with for 7 or 8 years works with another database) But  System.data.SQLite doesn't do it for every platform.  
So if .NET won't/can't take it over or produce an identical version, and include it with .NET itself, then the best thing is for its authors to support other platforms. I doubt that PowerShell coding SQLite support in order to plug the gap for arm would clear the bar for getting time allocated.
