### ISSUE TITLE
Unexpected behaviour while populating values in an ordered hash table

### ISSUE THREAD

**Issue by w1tht0uchp4d** [PowerShell/PowerShell#17971]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create an ordered hash table and populate some of its properties with values previously defined in the hash table. Sometimes the values get populated, sometimes not.

```
    $Api = [ordered]@{
        apiToken = ""
        validUntil = $(Get-Date)
        baseUrl = "https://someUrl.com"
        apiEndPoint = "api/config/v1"
        vaultEndpoint = "$($Api.baseUrl)/$($Api.apiEndPoint)/vault/account"
        tokenEndpoint = "$($Api.baseUrl)/oauth2/token"
        clientId = ""
        clientSecret = ""
    }
```

### Expected behavior

```console
PS> Write-Host $Api.tokenEndpoint
https://someUrl.com/oauth2/token
```

### Actual behavior

```console
PS> Write-Host $Api.tokenEndpoint
oauth2/token
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
IIRC 
If you run the code with no pre-existing hash table , $hashtable.key will be null. 
If you run it to recreate an existing hash table, it will use the pre-existing value, not the value you are putting into the new version.

**Comment by dkaszews** [comment]
Yeah, this is expected. Before you close the brace, `$Api` does not exist. So you are indexing into nonexistent variable, which returns null by default and is stringified into empty string. You can check it by setting `Set-StrictMode -Version 3.0` and observing the error. 

Can you please verify your example and actual behavior? `"$($Api.baseUrl)/oauth2/token"` should result in `"/oauth2/token"` and not `"oauth2/token"`

**Comment by mklement0** [comment]
To add to the existing comments: It sounds like you're looking for _Intra_-hashtable references, which aren't currently supported.

Such a feature - which would call for different syntax than in your attempt - has been requested  before (there's also a workaround there):

* #13782

**Comment by dkaszews** [comment]
If you really want this behavior, you could play around with something like this (note use of `'` instead of `"`:

```pwsh
$dict = [ordered] @{
    'url' = 'example.com'
    'endpoint' = '$($dict.url)/api/config'
}
foreach ($item in $dict.GetEnumerator()) {
    $dict[$item.Name] = Invoke-Expression ('"' + $dict.Value + '"') 
} 
```

**Comment by mklement0** [comment]
A simpler and more robust workaround, as also shown in the linked issue, is to use aux. variables:

```powershell
$dict =
  [ordered] @{
    url = ($url = 'example.com')
    endpoint = "$url/api/config"
  }
````

**Comment by w1tht0uchp4d** [comment]
Thank you very much. I think the answer of @mklement0 is exactly, what I am looking for.
