### ISSUE TITLE
PSDriveInfo is null for Get-Item -Path <provider qualified path>

### ISSUE THREAD

**Issue by wgross** [PowerShell/PowerShell#17986]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm implementing a custom cmdlet provider and stumbled upon an issue with provider qualified path:
- When getting an item with a rooted path like `drive:/path/to/item` the provider instance has assigned a PSDriveInfo instance on invocation by the base provider.
- When getting an item with a provider qualified path: `provider\qualified::drive:/path/to/item` the provider is invoked without having a PSDriveInfo instance assigned.

Within the provider I can compensate by parsing the drive name from the path and fetch the drive info from the session state: `SessionState.Drive.Get("drive")`. 

Also this changes the returned item which can be observed by the user:
- `Get-item C:\ | fl *` shows a PSDrive property.
- 'Get-item  "Microsoft.PowerShell.Core\FileSystem::c:\ | fl *" doesn't show a PSDrive property. 

I've debugged this with the code base for v7.2.6 and it look to me that `LocationGlobber.GetProviderPath(..)` should return the drive info in this case as well or should be called a second time with the provider name removed from the paths maybe? 

### Expected behavior

```console
PS> (get-item "Microsoft.PowerShell.Core\FileSystem::c:\").PSDrive -eq $null
False
```

### Actual behavior

```console
PS> (get-item "Microsoft.PowerShell.Core\FileSystem::c:\").PsDrive -eq $null
True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
A provider qualified path doesn't really reference the PSDrive. In this case, it just happens that the PSDrive shares the same name as the fully qualified path. This is made a little bit more clear with the registry provider:

```powershell
Get-Item Registry::HKEY_LOCAL_MACHINE\Software
```

Technically that references the same path as the PSDrive `HKLM:\` but the provider qualified syntax does not use PSDrives. You can even do `Get-Item Registry::HKLM:\Software` and it won't be able to find the path because that resolution doesn't happen.

**Comment by wgross** [comment]
Thanks for the quick reponse!

Just to clarify this for myself:
Using a provider qualified path delegates the path resolution (including the drives) to the provider implementation. 
This is similar to a call of a static method vs an instance method in C# where the instance method would be  the resolution of a non-provider qualified path?

Therefore what I did as a workaround (getting the PSDrive myself) is the intended behavior for a cmdlet provider?

**Comment by SeeminglyScience** [comment]
> Thanks for the quick reponse!
> 
> Just to clarify this for myself: Using a provider qualified path delegates the path resolution (including the drives) to the provider implementation.

Well it's more that it just doesn't resolve PSDrives at all. It's saying "here's the 'provider path', don't try to resolve it like a 'PSPath'".

This is similar to a call of a static method vs an instance method in C# where the instance method would be the resolution of a non-provider qualified path?

Yeah kinda. If you consider `PSDrive` to be sort of like a virtual dispatch table of paths.

> Therefore what I did as a workaround (getting the PSDrive myself) is the intended behavior for a cmdlet provider?

Well you're not dealing with a `PSPath`, you're dealing with a provider path. Even file system will have provider paths that don't resolve to a `PSDrive`, e.g. `Get-Item FileSystem::\\localhost\c$\Windows`

And probably only `FileSystem` will actually have PSDrive names line up exactly with literal path elements. I would say that the intended behavior is not to assume that a given provider path has an associated `PSDrive`.

**Comment by wgross** [comment]
I see, thank you!

**Comment by iSazonov** [comment]
This is definitely a departure from basic PowerShell concepts. Fixing this was declined in #5785.
