### ISSUE TITLE
powershell for entware

### ISSUE THREAD

**Issue by Modgames42** [PowerShell/PowerShell#17981]
### Summary of the new feature / enhancement

Hello, please make a powershell for entware, the structure of the ipk package is similar to the structure of the deb package, entware uses the same add-ons as debian but they have different names but the composition of the packages is the same.

**Comment by kasini3000** [comment]
From my past experience, your request will not be fulfilled quickly.
So allow me to give you a "community fans" level experience.
The Linux version of powershell is basically green software.
1 First, you need to install the libicu, openssl library of the distribution.
2Download the general linux package, decompress it, and set the soft link of pwsh. Then give pwsh execute permission.
3 I made a script for batch operations, you can refer to:
https://gitee.com/chuanjiao10/kasini3000/blob/master/zkj_install_powershell_offline_win2linux_keyfile.ps1

it is copy powershell files from "master" to "node".

Finally, it should be noted that:
At present, there are only packages for x86, arm cpu architecture, and other types of linux, which need to be compiled by themselves.
