### ISSUE TITLE
Bump Microsoft.Extensions.ObjectPool to 6.0.8

### ISSUE THREAD

**Issue by tomeyerman** [PowerShell/PowerShell#17998]
### Summary of the new feature / enhancement

I'd like to use expose some libraries I've written as Powershell cmdlets...however I'm unable to run them in PS currently because these libraries reference Microsoft.Extensions.ObjectPool 6.0.8 and PowerShell is still using version 5. If someone could bump it, I would greatly appreciate it :)

**Comment by tomeyerman** [comment]
Opened PR 17999 to address.

**Comment by daxian-dbw** [comment]
PowerShell doesn't directly reference `Microsoft.Extensions.ObjectPool`. Instead, PowerShell references `System.Private.ServiceModel`, which depends on `Microsoft.Extensions.ObjectPool (>= 5.0.10)` even for its latest version (4.10.0).

The `[cgmanifest.json](https://github.com/PowerShell/PowerShell/pull/17999/files#diff-2dbca354d25860d8a564159de6e6aa5be32423f7c475a9c120383d5df7c2d66a)` file is auto-generated to reflect the dependencies of PowerShell, which is then used to auto-generate our `ThirdPartyNotice`. So, it shouldn't be changed.

In you case, you may want to read [the "Resolving dependency conflict" doc](https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2#loading-through-net-core-assembly-load-contexts ). The samples in https://github.com/daxian-dbw/PowerShell-ALC-Samples may also be helpful to you.

**Comment by fMichaleczek** [comment]
@daxian-dbw Microsoft.Extensions.ObjectPool is distributed in the aspnet.core shared runtime. 

![image](https://github.com/PowerShell/PowerShell/assets/6187529/b3f6ac7f-e0ac-4633-b89e-5f1e4243ed93)

This has no impact for importing the PowerShell SDK into AspNet.Core. (dependencies are satisfied)
On the other hand, it can block the loading of AspNet.Core in PowerShell.

Wouldn't it be possible to put an explicit dependency in Microsoft.PowerShell.SDK?

I'm working on PowerShell WASM and need to be able to load AspNet.Core into PowerShell for easier development.
I put an ALC in my module but however it is possible to reopen the issue.

**Comment by OQO** [comment]
Suffering same problem. We cannot run PowerShell commandlets that use/reference aspnet.core 

As a workaround we currently manually remove or replace Microsoft.Extensions.ObjectPool.dll in the PowerShell installation directory.

Also see issue [https://github.com/dotnet/aspnetcore/issues/47352 ]

Would be great if this could be resolved.

**Comment by nczsl** [comment]
same problem trigger on .net 8.0.1

**Comment by nczsl** [comment]
> 遭受同样的问题。我们无法运行使用/引用 aspnet.core 的 PowerShell commandlet
> 
> 作为解决方法，我们目前手动删除或替换 PowerShell 安装目录中的 Microsoft.Extensions.ObjectPool.dll。
> 
> 另请参阅问题 [dotnet/aspnetcore#47352](https://github.com/dotnet/aspnetcore/issues/47352)
> 
> 如果这个问题能得到解决，那就太好了。

Your method seems to work
