### ISSUE TITLE
Implement a warning when trying to use known interactive console applications via PowerShell Remoting

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PowerShell#17994]
### Summary of the new feature / enhancement

By design, interactive use of PowerShell via Remoting does not support interactive console applications - as these requires a full console. Remoting is currently sending stdin and stdout back and forth via PS Remoting, hence an interactive application does not work.

Demo of the current user experience, using Enter-PSSession -Hostname against an Ubuntu VM with PowerShell 7 installed:

```
[adminjer@172.28.0.11]:` PS /home/adminjer> vim /etc/ssh/sshd_config
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

Trying a different editor such as nano also fails:
```
[adminjer@172.28.0.11]: PS /home/adminjer> nano test.txt
Error opening terminal: unknown.
```

Looking into Get-Help about_remote_troubleshooting reveals a section called entitled 'TROUBLESHOOTING UNRESPONSIVE BEHAVIOUR', which states:

```
TROUBLESHOOTING UNRESPONSIVE BEHAVIOR

This section discusses remoting problems that prevent a command from completing and prevent or delay the return of the PowerShell prompt.

HOW TO INTERRUPT A COMMAND

Some native Windows programs, such as programs with a user interface, console applications that prompt for input, and console applications that use the Win32 console API, do not work correctly in the PowerShell remote host.

When you use these programs, you might see unexpected behavior, such as no output, partial output, or a remote command that does not complete. To end an unresponsive program, type CTRL + C. To view any errors that might have been reported, type "$error" in the local host and the remote session.
```

Even though the above was originally written for Windows PowerShell towards Windows console applications, I suppose the same is true for Linux/MacOS as well, meaning console applications such as VIM won't work.

I recall Windows PowerShell ISE has this variable containing unsupported console applications:

```
$psUnsupportedConsoleApplications
wmic
wmic.exe
cmd
cmd.exe
diskpart
diskpart.exe
edit.com
netsh
netsh.exe
nslookup
nslookup.exe
powershell
powershell.exe
ssh-keygen
ssh-keygen.exe
```

Trying to launch one of them would result in a more user friendly error:

```
Cannot start "diskpart.exe". Interactive console applications are not supported. 
To run the application, use the Start-Process cmdlet or use "Start PowerShell.exe" from the File menu.
To view/modify the list of blocked console applications, use $psUnsupportedConsoleApplications, or consult online help.
At line:0 char:0
```

Would it be possible to have a similar variable and error message for PowerShell Remoting sessions? If so, I could file an issue for this. Or are there any obvious reasons it won`t be doable?

### Proposed technical implementation details (optional)

Implement a new variable containing unsupported console applications that is known to not work via PowerShell Remoting:

```
$psRemotingUnsupportedConsoleApplications
vim
nano
```

Trying to launch one of them would result in a more user friendly error:

```
Cannot start "vim". Interactive console applications are not supported via PowerShell Remoting. 
To run the application, use an interactive session - for example ssh@remote-host followed by launching pwsh.
To view/modify the list of blocked console applications, use $psRemotingUnsupportedConsoleApplications, or consult online help.
At line:0 char:0
```

**Comment by kasini3000** [comment]
It seems that it is not easy to achieve in a short time.
for other way:
I have written a replacement ps1 script similar to SED, support win, linux, 
I use it to implement remote batch replacement of strings, in linux text files
are you willing to consider it?

**Comment by kilasuit** [comment]
Hi @janegilring 

I personally can see this being of use though a static list perhaps isn't the most sensible way forward here, even though it worked well enough for the list in ISE, I'd be happier if we could dynamically work this out based on the application being called. especially as some executables can have both an interactive and non-interactive mode. As such I think this has enough cross over that we need to discuss this across 2 WG's so will get this rolling now.

**Comment by kilasuit** [comment]
I think that you can currently get round this in VSCode with it's SSH based remoting to open up files similar to how the ISE had remote tabs, but I haven't tested if that may work for you as opposed to in this case opening Vim/nano to do required changes.

**Comment by janegilring** [comment]
> 

That is exactly the approach I use personally. The question regarding vim via PowerShell Remoting popped up in a customer workshop, where someone who is used to leveraging vim wanted to use it via PowerShell Remoting and was wondering why it didn´t work.

**Comment by janegilring** [comment]
> It seems that it is not easy to achieve in a short time. for other way: I have written a replacement ps1 script similar to SED, support win, linux, I use it to implement remote batch replacement of strings, in linux text files are you willing to consider it?

Sure, it sounds useful to have in the tool belt.

**Comment by rhubarb-geek-nz** [comment]
Is this really necessary? It is no different to using ssh without allocation of a pseudo-terminal.

```
% ssh -T localhost vi /etc/ssh/sshd_config 
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

Is it realistic for PowerShell to maintain a list of every interactive console application on both Windows, macOS and Linux?

Would git and svn be included in the list because they may run an editor for a commit message, or apps that sometimes ask "Are you sure?" like apt and yum? 

Perhaps this depends on a "Minority Report" feature.
