### ISSUE TITLE
Invoke-WebRequest Invoke-RestMethod -MaximumRetryCount switch shoult not retry on 401 (Unauthorized)

### ISSUE THREAD

**Issue by zamothh** [PowerShell/PowerShell#18016]
### Summary of the new feature / enhancement

**What ?**
The retry function is a great function, but when the Web Request / API portal answers with
401 UnAuthorized
It is likely that retrying is purely useless

**Specification on the -MaximumRetryCount**
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.2
_Specifies how many times PowerShell retries a connection when a failure code between 400 and 599, inclusive or 304 is received. Also see RetryIntervalSec parameter for specifying number of retries._

### Proposed technical implementation details (optional)

**Ideally**, I think 401 should be removed from the list of errors that will try to get a retry on. It just does not mean anything to retry on that error code

**Optionally**, I think it might also be good to add a switch where we could specify other ports we don't want to have retry on. 

- Example : -RetryIgnoredCode [int[]]
- Description : List of error code on which the -MaximumRetryCount will not have a retry

There might be other cases where we don't want to have a retry on, depending on the web site.

**Comment by iSazonov** [comment]
It would be nice to compare with other web utilities/clients.
