### ISSUE TITLE
Hosting PowerShell Core in a plugin, many issues

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#18028]
### Summary of the new feature / enhancement

The attached project approximates my use case: PowerShell Core is hosted not by
an application but by its plugin which is dynamically loaded at runtime.

[TryPSCore.zip](https://github.com/PowerShell/PowerShell/files/9484128/TryPSCore.zip)

I.e. this straightforward plugin architecture:

(1) `ClassLibrary1` defines the plugin interface `Class1`.

(2) `ClassLibrary2` implements this interface as `Class2` and hosts PowerShell
Core in order to use PowerShell.
- post-build calls `dotnet publish -c $(Configuration) -o ..\bin\plugin --no-build`
- thus, the result plugin is published in `TryPSCore/bin/plugin`

(3) The application `TryPSCore` depends on `ClassLibrary1`, loads `ClassLibrary2`
by `LoadFrom`, finds and instantiates found implementation of `Class1` and
calls its virtual method `Invoke()`.
- its output directory is set to `TryPSCore/bin`, this is our test app.

The method `Invoke()` runs the following PowerShell code (see `ClassLibrary2` / `Class2.cs`):

```powershell
$ErrorActionPreference=1

'This works.'

<# Problem 1
Add-Type @'
public enum MyEnum {
    MyValue = 0,
}
'@
[MyEnum]::MyValue
#>

<# Problem 2
Get-CimInstance Win32_Environment
#>
```

### Problem 0 (solved by `AssemblyResolve`)

The test app fails with "Could not load file or assembly System.Management.Automation" (rather expectedly).

I worked around this using `AssemblyResolve` event handler (see the simplified variant in `Class2.cs`).

Then it works, prints 'This works.' Thus, whatever is built and assembled "by
default" may perform something in PowerShell. Actually, it mostly works, good.
But there are several issues, just two of them below.

> NB After seeing this issue [Make it possible to host PowerShell in a custom assembly load context](https://github.com/PowerShell/PowerShell/issues/17492)
I tried the ALC approach. It seems to have even more issues than using `AssemblyResolve` with a bunch of `LoadFrom`.

### Problem 1 (solved by copy `ref`?)

Uncomment the snippet `Problem 1`.
Then the test fails with:

```
Could not find a part of the path 'C:\Users\roman.kuzmin\source\repos\TryPSCore\bin\ref'.
```

Then copy

    ...\TryPSCore\bin\plugin\ref

to

    ...\TryPSCore\bin

After this copy step the snippet `Problem 1` works.

> Is this normal / expected that we have to copy `ref` to the application
directory? There are cases when this is not possible, we do not "own" this
application, we only provide the plugin for it.

My real use case is more complex. The application is not even .NET, native.
One of plugins hosts .NET Core and loads another plugin which hosts PowerShell
Core. In this real case the error is different:

```
Could not find a part of the path 'C:\Bin\Far\x64\FarNet\Modules\PowerShellFar\runtimes\win\lib\net6.0\ref'.
```

The real location of `ref` after `publish` is this:

```
C:\Bin\Far\x64\FarNet\Modules\PowerShellFar\ref
```

Like I said in Problem 0, my custom `AssemblyResolve` finds all not resolved
assemblies. So it seems PowerShell looks for `ref` in some "known locations".
They are not the same, depending on how an app is built. But in both cases
PowerShell does not check the "official" `ref` location created by publish,
i.e. in the publish output directory.

### Problem 2 (not solved)

Uncomment the snippet `Problem 2`.
Then the test fails with "method not found":

```
System.Management.Automation.CmdletInvocationException: The type initializer for 'Microsoft.Management.Infrastructure.Native.OperationCallbacks' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.Management.Infrastructure.Native.OperationCallbacks' threw an exception.
 ---> System.MissingMethodException: Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.
   at Microsoft.Management.Infrastructure.Native.OperationCallbacks..cctor()
   --- End of inner exception stack trace ---
   ...
```

> Is this the PowerShell Core problem? Or should I copy something like in the
Problem 1 or tweak something after the build and publish? Then what exactly
should I copy? Is this step documented somewhere? I read this:

https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/choosing-the-right-nuget-package?view=powershell-7.2

### Is this even a valid use case?

Is hosting PowerShell Core in a plugin a valid use case? Like I said, it mostly
works with described tweaks. But I worry that it works by chance, it is not
supposed to work, it is not officially supported and tested, etc. And on any
PowerShell update my plugin may stop working.

What is the official opinion, should this use case work normally?
At least with some documented extra post build / publish steps.

### Proposed technical implementation details (optional)

I am not sure what to propose because the use case might be not quite supported yet.

But at least (perhaps) the internal resolution of the folder `ref` could be better. As described, it looks like PS Core does not look for it in the location created by `publish`. Maybe it could with some extra tweak. One headache less for PS Core in a plugin.

**Comment by S3od11** [comment]
ً

**Comment by SteveL-MSFT** [comment]
`Add-Type` relies on reference assemblies to build the resulting assembly.  PS7 ships the reference assemblies in `$PSHome/ref`.  If you're hosting PS7, then you need to either make these ref assemblies available for `Add-Type` or use the `Add-Type -ReferencedAssemblies` parameter to specify them.

**Comment by nightroman** [comment]
@SteveL-MSFT `dotnet publish` makes these assemblies available as the directory `ref` in the publish destination. The issue I am describing is that PS Core does not look for this assemblies in this "natural" location. According to clear error messages with provided paths PS Core looks for `ref` in different locations and does not check the "natural" `dotnet publish` location which should be easy to calculate by relative paths.

Thus, to work around this issue I have to manually relocate this `ref` folder to the location from PS Core message. This does not look quite right.

**Comment by SteveL-MSFT** [comment]
@nightroman ok, now i see what you are saying.  See https://github.com/PowerShell/PowerShell/blob/736cf3ecbf441af05baec72ac31bad9619a2b3e2/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L622-L633

**Comment by nightroman** [comment]
Well, I'd say it's a bug, i.e. your wrong assumption about location of the `ref` produced by `dotnet publish`
Per your code and in my case it is this:
```
C:\Bin\Far\x64\FarNet\Modules\PowerShellFar\runtimes\win\lib\net6.0\System.Management.Automation.dll
```
but the actual produced by `dotnet publish` is
```
C:\Bin\Far\x64\FarNet\Modules\PowerShellFar
```

**Comment by nightroman** [comment]
Is `System.Management.Automation.dll` always published to `runtimes\XYZ\lib\net6.0`?
If yes then the correct way to find `ref` is to step 3 folders up from its location.

**Comment by nightroman** [comment]
@SteveL-MSFT @iSazonov 
Any comments on new discoveries? Should this be labeled as a bug, not a question? Or should I open a separate bug issue for the wrong `ref` location assumptions?

**Comment by iSazonov** [comment]
The PowerShell code exactly says that `ref` folder must be in SMA.dll folder for host scenarios. _It is best we can do._

`dotnet publish` is based on _standard_ MSBuild scripts from .Net SDK and can not address all specific scenarios. You have to customize build process in your prop/target/csproj files as needed and copy `ref` folder in place the SMA.dll expects.

**Comment by nightroman** [comment]
@iSazonov So by the PowerShell Core design, it fails instead of checking one more location for `ref` as described (4 folders up from SMA.dll) in addition to two already checked. Is this correct?

**Comment by nightroman** [comment]
If this is by design then the required custom build step should it should be described in
https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/choosing-the-right-nuget-package?view=powershell-7.2

Currently it omits the very important piece of information and only says:

> Publishing an application targeting Microsoft.Powershell.SDK will include all these assemblies, and any dependencies PowerShell requires. It will also include other assets that PowerShell required in its build, such as the module manifests for Microsoft.PowerShell.* modules and the ref directory required by [Add-Type](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/add-type).

It admits that `ref` is needed and provided but does not tell to copy `ref` to SMA.dll location.

**Comment by nightroman** [comment]
Also, the design is not quite right (if not just wrong) in the scenario when `Assembly.GetEntryAssembly()` is not null. In this case you require `ref` to be copied to the application executable directory. You assume that this is possible. This is not always the case (you may not own that application or have no right to access its folder).

Also, this is not just post-build step required but rather installation/deployment step because a plugin hosting PSCore might be added to already installed application.

**Comment by iSazonov** [comment]
> In this case you require `ref` to be copied to the application executable directory

Not in the application. _In SMA.dll_.

**Comment by nightroman** [comment]
> > In this case you require `ref` to be copied to the application executable directory
> 
> Not in the application. In _SMA.dll_ folder.

```
PathType.GetDirectoryName( 
         (Assembly.GetEntryAssembly() ?? typeof(PSObject).Assembly).Location), 
     "ref"); 
```

On the contrary, in the application folder, if `Assembly.GetEntryAssembly()` is not null. Not in _SMA.dll_ folder.
And this application folder may be not available for copying `ref`. This makes some valid scenarios impossible.

**Comment by iSazonov** [comment]
> On the contrary, in the application folder, if `Assembly.GetEntryAssembly()` is not null.

> My real use case is more complex. The application is not even .NET, **native**.
One of plugins hosts .NET Core and loads another plugin which hosts PowerShell
Core.

Is your application _native_? Or I misread your scenario?

**Comment by nightroman** [comment]
My sample attached application is .NET. My other application is native. I have all kind of use cases in practice.

**Comment by nightroman** [comment]
TBH the discussion is getting too long. If the issue remains labeled as question I close it. I got the some answers and the shape of things.

I think the PS Core design is not quite right. PS Core is not born yesterday. It's really the time to support plugin scenarios. If not fully then at least partially and with some help for users who really need plugins hosting PS Core.

**Comment by iSazonov** [comment]
I don't see a problem for a native host. If there is a host managed application, it is supposed to be the one that publishes the ref folder. If the SMA is a separate plugin, it is impossible to distinguish between the managed application itself and the plugin.
Perhaps we could check the existence of the folder in those two places.

@daxian-dbw Could you please comment?

**Comment by nightroman** [comment]
NB Semi-related note, this documentation introduces "another way" which has nothing to do with use cases when users really have to know where to put the `ref` folder. These use cases do not have `pwsh.dll`.

> Beginning in PowerShell 7, Add-Type does not compile a type if a type with the same name already exists. Also, Add-Type looks for assemblies in a ref folder under the folder that contains pwsh.dll.

https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Add-Type?view=powershell-7

This documentation presumably describes the `pwsh` installation. Interestingly, exactly in this case users do not have to know such a technical detail like the location of `ref`. It comes with `pwsh` out of the box.

**Comment by hyke123** [comment]
> I don't see a problem for a native host. If there is a host managed application, it is supposed to be the one that publishes the ref folder. If the SMA is a separate plugin, it is impossible to distinguish between the managed application itself and the plugin. Perhaps we could check the existence of the folder in those two places.
> 
> @daxian-dbw Could you please comment?

Hi @iSazonov @daxian-dbw  We're facing the same issue. Is there a workaround other than copying "ref" to the host.exe folder?

**Comment by iSazonov** [comment]
@hyke123 Nothing was changed in the logic.

**Comment by hyke123** [comment]
Another question: Will the add-type command still search for DLLs in the Assembly.GetEntryAssembly() + "ref" folder even if they have already been loaded into the current AppDomain?  @iSazonov

**Comment by iSazonov** [comment]
I guess you say about re-loading. If an assembly was loaded (by name) second attempt (by path) will be ignored.
