### ISSUE TITLE
Native globbing: character-individual backtick escaping of wildcard metacharacters is not respected

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18038]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

See also (the inverse problem): https://github.com/PowerShell/PowerShell/issues/10683

### Steps to reproduce

On Unix-like platforms, _unquoted_ arguments that look like globbing (wildcard) patterns are automatically resolved to matching paths when calling external programs.

While single- and double-quoting can be used to suppress this behavior, using character-individual backtick escaping does not:

```
/bin/echo `*
```

### Expected behavior

```console
*
```

### Actual behavior

```console
(list of file and subdirectory names in the current directory)
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.7 on Unix-like platforms.
```

**Comment by 237dmitry** [comment]
Why do you expect this ( `*` ) output?

![1_001](https://user-images.githubusercontent.com/78153320/188745533-a76b2437-f26a-4592-bb4a-10eb70ce2339.png)

**Comment by mklement0** [comment]
@237dmitry, why do you think that _Bash_ syntax is in any relevant here?

**Comment by mklement0** [comment]
In PowerShell terms: if ``Write-Output `"`` is the same as ``Write-Output '"'``,  why isn't `` `* `` the same as ``'*'``?

Granted, the escaping in `` `* `` isn't strictly escaping for _syntactic_ reasons, but if `'*'` serves to signal to the native globbing feature that it should not be applied, so should `` `* `` - unless there's a good reason I'm missing.

**Comment by 237dmitry** [comment]
> why do you think that Bash syntax is in any way relevant here?

Because in bash `/bin/echo *` outputs list of files.

**Comment by 237dmitry** [comment]
> It is not /bin/echo that performs the globbing

/bin/echo receives parameter that already globbed. Isn't it true?

**Comment by mklement0** [comment]
Yes, if you pass `*`. By contrast, if you _quote_ the `*` as `'*'` or `"*"`, PowerShell does _not_ apply native globbing and `/bin/echo` receives _verbatim_ `*` (which it prints _as-is_). And, by PowerShell's quoting / escaping rules, `` `* `` should be equivalent to the quoted forms, but isn't.

**Comment by 237dmitry** [comment]
> should be equivalent to the quoted forms, but isn't.

I'm already confused with escaping.
```powershell
PS > /bin/echo 1`n2
1
2

PS > Start-Process /bin/echo -ArgumentList 1`n2
1
2

PS > /bin/echo --% 1`n2
1`n2

PS > (Get-ExperimentalFeature -Name PSNativeCommandArgumentPassing).Enabled
True
```

**Comment by mklement0** [comment]
* `PSNativeCommandArgumentPassing` is incidental to this discussion, because in effect it only relates to `"` chars. embedded in arguments.
* Use of `--%` is virtually pointless on Unix-like platforms (and documented as such - for the backstory, see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4963).

---

Generally speaking, unquoted literal arguments are parsed _as if they were enclosed in `"..."`_; that is, ``/bin/echo 1`n2`` is the same as ``/bin/echo "1`n2"``, meaning that _escape sequence_ `` `n `` expands to a literal newline (LF).

Inside `"..."`, `` ` ``-escaping characters that do not form an escape sequence isn't necessary, but is tolerated; e.g. ``/bin/echo "`'"`` is the same as  `/bin/echo "'"` and prints verbatim `'`.

However, in an _unquoted_ argument, characters that wouldn't require escaping if enclosed in `"..."` _do_ require escaping if they contain argument-mode metacharacters, such as `'`, `"`, `&`, `|`, ..., so that, for instance, you have to use ``/bin/echo `| `` to print `|` verbatim.

From that perspective _alone_, `*` does _not_ require `` ` ``-escaping, because `*` isn't an argument-mode metacharacter: leaving the native globbing feature out of the picture, _all_ of the following output `*` verbatim: `Write-Output *`, `Write-Output '*'`, `Write-Output "*"`, and ``Write-Output `*``

The fact that _with respect to native globbing_ it makes a difference whether you use `'...'` / `"..."` quoting (suppression of the feature) or not, already amounts to special-casing the usual syntax rules, and this special-casing is applied by PowerShell _itself, during parameter binding_ (I don't know the details).

My point is that this special-casing should also apply to `` `* `` and `` `? ``, for consistency, i.e. these escaped forms should be treated the same as their quoted equivalents, `'*'` / `"*"` and `'?'` / `"?"`, because the intent to treat `*` and `?` _verbatim_ is expressed by all of these forms.

I do realize that this complicates matters, because an argument such as ``a`*b*`` would then have to treat the first `*` verbatim, while retaining the second one as a globbing metacharacter; expressed in Bash terms, it would have to be treated as `a\*b*`for globbing purposes.

**Comment by SteveL-MSFT** [comment]
cc @JamesWTruher 

It seems reasonable that `` `"` is a single literal double quote that `` `*` is a single literal asterisk.  `/bin/echo "*"` does do what you expect.

**Comment by JamesWTruher** [comment]
FWIW, this is behavior is in ps6 as well.
