### ISSUE TITLE
Static ::new() method honors a single-parameter constructor whose parameter is optional, while New-Object does not

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18049]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: The following may seem contrived, but it's actually useful to work around the limitation in C# 9 and below of not being able to use parameter-_less_ constructors in `struct`s.

```powershell
Add-Type @'
public struct MyConfig
{
    // Note the `int unused = 0` dummy parameter with a default value.
    public MyConfig(int unused = 0) { level = 42; }
    public int level;
}
'@

New-Object MyConfig  # !! Constructor is NOT called.
[MyConfig]::new()         # OK: constructor is called.
```

### Expected behavior

```console
level
-----
   42
   42
```

### Actual behavior

```console
level
-----
    0
   42
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.7
```

**Comment by SeeminglyScience** [comment]
Related (but not dupe) #13674
