### ISSUE TITLE
idiomatic (friendly) steppablePipeline

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#18054]
### Summary of the new feature / enhancement

As a user I would like to have an idiomatic PowerShell solution to set the `-ThrottleLimit` in the script scope or global scope:
See: [What is the best way to structure an advanced multi-threaded Powershell function to work both on the pipeline as well as non-pipeline calls?](https://stackoverflow.com/a/73646440/1701026)
Related: #16898 [ ThrottleLimit not respected by ForEach-Object $SCRIPTBLOCK -Parallel -InputObject $INPUTOBJECT -ThrottleLimit 8 -AsJob](https://github.com/PowerShell/PowerShell/issues/16898)

### Proposed technical implementation details (optional)

This might be a specific `-ThrottleLimit` parameter for the `ForEach-Object -Parallel` cmdlet or a more general solution as scope based parameters: e.g.:  `-Script:ThrottleLimit 16` or even a more idiomatic PowerShell steppable pipeline syntax (based on the existing `Invoke-Command` cmdlet?):
A (friendly) steppablePipeline might actually come at hand everywhere were it is required to invoke a cmdlet multiple time from within a `Process` block, as e.g.: [Split CSV with powershell](https://stackoverflow.com/questions/14754287) where I would like reuse a steppable pipeline for about 10,000 iterations and than open a new one.

Wishful thinking:
```PowerShell
[CmdletBinding()]
param (
    [Parameter(Mandatory,Position = 0,ValueFromPipeline)]
    [string[]]
    $InputPath
)
begin {
    $PSBoundParameters += @{
        ThrottleLimit = 4
        Parallel = { 'Do something' }
    }
    Invoke-Command -Begin ForEach-Object -ArgumentList $PSBoundParameters
}
process {
    # Not sure if the following command can be more efficient at all v.s. starting a complete new pipeline
    $InputPath.ForEach{ Invoke-Command -Process $MyCommand -Object $_ }
}
end {
    Invoke-Command -End $MyCommand
}
```

**Comment by jhoneill** [comment]
> As a user I would like to have an idiomatic PowerShell solution to set the `-ThrottleLimit` in the script scope or global scope:
> See: [What is the best way to structure an advanced multi-threaded Powershell function to work both on the pipeline as well as non-pipeline calls?](https://stackoverflow.com/a/73646440/1701026)
> Related: #16898  

Can we take this a bit at a time ? 
 Exactly what is the problem that you have setting the throttle-limit ? 
#16898 is `foreach ($n in 1..1000) {  «something as job»  } ` creates 1000 jobs , and `foreach ($n in 1..1000) {  $array[$n] |  foreach -parallel -throttle 8  } ` creates 1000 8-threaded jobs, which should be a surprise to no-one.

Are you saying you would like to have one thread pool and share it between multiple things ?  So you could write 
```
$SharedPool = New-ThreadPool -Limit 20
1..1000 | foreach -parallel { $data[$_] | foreach -parallel {«command» $_ } -threadPool $Using:SharedPool} 
```
That could be useful, but it's nothing to do with stepable pipelines, and only applies to nested foreach -parallel commands.

The stackoverflow Q (which I've replied to) seems to be "I want to take piped input or everything in a variable do something with the whole set"  The set is going to `foreach -Parallel` in this case but it could be `sort-object` or `select-object -unique` 

Based on the stackoverflow post I think you are trying to call the process block of "foreach" from the process block of your function based on a misunderstanding.  It is perfectly valid for something in the middle of a pipeline (i.e. "two" in `one | two | three`) to send its output in its end block  - and every function which doesn't define begin/process/end  _does that_.     
In `one | two | three`, two can output from its `end` block which is processed by the `process` block of three. Three only _starts_ its own end block when two's end block is finished. 

If you're saying this is not very friendly 
```
begin   {
         $parameters @{«name2» = «value2» ; «name2» = «value2»} 
         $wrappedCmd = Get-Command «command»
         $scriptCmd  = {& $wrappedCmd @parameters }
         $steppablePipeline = $scriptCmd.GetSteppablePipeline($myInvocation.CommandOrigin)
         $steppablePipeline.Begin($PSCmdlet)
}
process {$steppablePipeline.Process($_) }
end     {$steppablePipeline.End()       }
``` 
and it would be better to be able to write something like  this 
```
begin   {
         $parameters @{«name2» = «value2» ; «name2» = «value2»} 
         $steppablePipeline = Invoke-Command -BeginOnly  «command»  -argumentLies $parameters 
}
process {$steppablePipeline($_) }
end     {$steppablePipeline.End()       }
``` 

Yes, it condenses four lines into one. Whether that's a big help or a small one people can debate :-) I  have a feeling that it's  something the team would leave the community to do.

**Comment by jhoneill** [comment]
> I know, I also want to use the steppable pipeline to gain more performance as described here: [What good does a SteppablePipeline](https://stackoverflow.com/a/73074477/1701026) as _it is more efficient than the full invocation of the wrapped cmdlet in every iteration, in a nested pipeline_.

It depends on the command.  For a great many things it doesn't matter - shaving 0.1 sec off the time to get back to the prompt 1000 times in a week doesn't give back 1000 x 0.1 seconds back. Shaving 0.1 sec off each pass of loop which runs 1000 times _does_ give you the 100 seconds.  

Writing a wrapper which basically goes 
```
Function wrap {
param ([parameter(valueFromPipeline)]$P)
begin {$S =  {«block code»}.GetSteppablePipeline() ; $s.begin()} 
process {$S.process($p)} 
end {$s.end()} 
}
```
Is slower than just doing   `... | foreach-object {«block code»} `  

but 
```
Function wrap2 {
param ([parameter(valueFromPipeline)]$P)
process {
$q = «some result from $P»
$q | foreach-object {«block code»}.
}
``` 
Will be slower because  {«block code»} is set up for each $P passed. 

This 
```
Function wrap3 {
param ([parameter(valueFromPipeline)]$P)
begin   {$q = @()
process {$q += «some result from $P»}
end { $q | foreach-object -parallel {«block code»} } 
``` 
May be faster or slower depending on how quickly items arrive and how long they take to process. That link shows an example of all the items arriving ~ instantly so it is faster. If $q is ready quickly and  «block code» is slow, parallelism helps. 

 But if items arrive slowly, you get the first item noticeably sooner with a streaming method, and if the time to process is significant the last item completes noticeably  after it arrives. If the time process is small, then the time to get all items is shortly after the last one         
... but if (3) is slower `... | forEach  {«some result from $P»} | foreach-object -parallel {«block code»}`      
or (if the first block doesn't expand to many items)   
 `... | foreach-object -parallel {$r = «some result from $P» ; « code using $r»}` 
 probably beats creating your own steppable pipeline

**Comment by iRon7** [comment]
@jhoneill,

Thanks for your explanations and insights. I needed some time to process this all and further play around with the steppable pipeline.

> It depends on the command

Agree, yet using the **steppable pipeline** vs. a **full cmdlet call** could make quite some difference in performance for cmdlets as e.g. `Set-Content`. I was suspecting this for the mentioned StackOverflow question [Split CSV with powershell](https://stackoverflow.com/questions/14754287) and actually exceeded my own expectation with a [`Split-Content` function](https://stackoverflow.com/a/73671591/1701026) which is about 8 times faster than the accepted answer.

Anyways,

> Yes, it condenses four lines into one. Whether that's a big help or a small one people can debate :-)

I do see now that the purpose for more friendly syntax is a little overdone especially as one might start of with your suggestion `{«block code»}.GetSteppablePipeline()` therefore I have closed this issue.
