### ISSUE TITLE
Arrow keys don't work in the powershell console when invoked from a TTY

### ISSUE THREAD

**Issue by GeorgeBroughton** [PowerShell/PowerShell#18053]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

 - Install fedora 36
 - run the following commands in a TTY:
 ```bash
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
sudo dnf makecache
sudo dnf install powershell
pwsh
Get-ChildItem -Path "/"
```
 - Press `Up` arrow on keyboard

### Expected behavior

```console
PS /home/user> Get-ChildItem -Path "/"
```

### Actual behavior

```console
PS /home/user> OA
```

### Error details

```console
No error produced
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 5.19.6-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 31 17:58:15 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Info

This post is related to [Issue 16606](https://github.com/PowerShell/PowerShell/issues/16606)
$TERM for me is `Linux` as it's a TTY i'm invoking it from.

**Comment by 237dmitry** [comment]
Confirm:
Up -- `0A`
Down -- `0B`
Right -- `0C`
Left -- `0D`

Also, arrows keys are being read incorrectly in the terminal emulator.

```powershell
PS > [console]::ReadKey()

KeyChar    Key Modifiers
-------    --- ---------
       Escape         0

# After pressing arrow key in prompt:
# A:    UpArrow
# B:    DownArrow
# C:    RightArrow
# D:    LeftArrow
```

![ArcoLinux_2022-09-08_10-29-25](https://user-images.githubusercontent.com/78153320/189061824-55fb4c8c-431f-44c4-b90c-e82faf513f4c.png)

In TTY `[console]::ReaKey()` detects pressing the arrows correctly but not working properly arrows.
In virtual terminal arrows working properly but in `[console]::ReadKey()` result is incorrect.

**Comment by iSazonov** [comment]
Is it dup #16443?

**Comment by GeorgeBroughton** [comment]
> Is it dup #16443?

Possibly. There have been a number of posts about it, however the terminal emulator has always been different. Not enough information in the other thread about which terminal emulator they're using.

This was taken from their thread:
```ps
$CurrentHost = Get-Host
$key1 = $CurrentHost.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

## A bug with Linux and Mac where arrow keys are return in 2 chars.  First is esc follow by A,B,C,D
if ($key1.VirtualKeyCode -eq 0x1B) {
   ## Found that we got an esc chair so we need to grab one more char
   $key2 = $CurrentHost.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

   ## We just care about up and down arrow mapping here for now.
   if ($key2.VirtualKeyCode -eq 0x41) {
      # VK_UP = 0x26 up-arrow
      $key1.VirtualKeyCode = 0x26
   }
   if ($key2.VirtualKeyCode -eq 0x42) {
      # VK_DOWN = 0x28 down-arrow
      $key1.VirtualKeyCode = 0x28
   }

}

$key1
```

This is what i get when running directly from the ![TTY](https://user-images.githubusercontent.com/17716439/189174550-58cda2d7-eee7-470a-a3a1-1a83e191773f.jpg)

This is what i get when running from ![SSH](https://user-images.githubusercontent.com/17716439/189175260-b69f2cb4-1e19-408c-affe-7cc8f4ff4190.png)

Works in SSH, not in the TTY

**Comment by GeorgeBroughton** [comment]
Wrote a different script now that i understand what the other guy was trying to do

```ps
$CurrentHost = Get-Host

Write-Host "Press Up"
$Up = [PSCustomObject]@{
        Key             = "Up"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

Write-Host "Press Down"
$Down = [PSCustomObject]@{
        Key             = "Down"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

Write-Host "Press Left"
$Left = [PSCustomObject]@{
        Key             = "Left"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

Write-Host "Press Right"
$Right = [PSCustomObject]@{
        Key             = "Right"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

$Up,$Down,$Left,$Right
```

Output from the TTY:
![_DSC0164](https://user-images.githubusercontent.com/17716439/189186274-9b5d8289-fdf0-4e16-a532-57865b0888e7.jpg)

SSH seems to work the other way around. The script sees both the escape character and the keycode. So i had to modify the script:
```ps
$CurrentHost = Get-Host

Write-Host "Press Up"
$Up = [PSCustomObject]@{
        Key             = "Up"
        EscChar         = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

Write-Host "Press Down"
$Down = [PSCustomObject]@{
        Key             = "Down"
        EscChar         = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

Write-Host "Press Left"
$Left = [PSCustomObject]@{
        Key             = "Left"
        EscChar         = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

Write-Host "Press Right"
$Right = [PSCustomObject]@{
        Key             = "Right"
        EscChar         = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
        VirtualKeyCode  = "0x$('{0:X0}' -f $CurrentHost.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)"
}

$Up,$Down,$Left,$Right
```

Which then shows this:
![image](https://user-images.githubusercontent.com/17716439/189187315-709236c3-321b-4794-a456-99a5a29afc90.png)

**Comment by daxian-dbw** [comment]
The `Console.Key` re-write work (https://github.com/dotnet/runtime/pull/72193) was checked in .NET on 8/1 and will be included in the RC1 release. This issue is likely to be addressed by that change. Please verify if that's the case after we release the PowerShell RC1 this month.

**Comment by GeorgeBroughton** [comment]
Will do.
