### ISSUE TITLE
Support for SyntaxTrivia in the AST

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#1806]
[Roslyn](https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#syntax-trivia) accomplishes this by having LeadingTrivia and TrailingTrivia collections for each token in the Syntax Tree. PowerShell doesn't maintain this type of trivia in the AST so refactoring algorithms have to take the AST and parsed tokens into account when processing and reordering a script.

I feel like I talked to @lzybkr about this at one point so there may be a good reason for not doing this that I don't remember but I figure it'd be a cool discussion.

**Comment by iSazonov** [comment]
@bergmeister Perhaps it can be intereting for you.

**Comment by iSazonov** [comment]
I'd can investigate this but currently we have over 45 open PRs - slow reviews from MSFT team slow down community works 😕

**Comment by rjmholt** [comment]
No no, it's just a daydream for now. Tooling would benefit, but we should focus on what's being worked on currently for now.

**Comment by rjmholt** [comment]
The slow reviews are a consequence of driving other work at the moment -- hopefully it will pay dividends so that we can spend more time working on PowerShell itself.
