### ISSUE TITLE
Getting help for the parameter of the cmdlet by the alias of the parameter

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#18065]
### Summary of the new feature / enhancement

For example, you want to get help for the `ArgumentList` parameter of the `Get-Command` cmdlet. This parameter has the alias `Args`, but the `Get-Help -Parameter Args` command throws the error:

```powershell
 PS > Get-Help Get-Command -Parameter Args
Get-Help: No parameter matches criteria Args.

 PS > (Get-Command Get-Command).Parameters.ArgumentList.Aliases
Args
```

**Comment by dkaszews** [comment]
Sounds good to me, will take a look at it since I've already tinkered with help system (#17696 merged, #18021 in review)
