### ISSUE TITLE
Remove About_*** Help that is specific to Windows

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#1807]
There are a bunch of About topics which are very windows specific and need to be culled from the LInux distribution.
More generally, we need to have a mechanism for general About files, WIndows-only About files and Linux-only About files.

Examples:

about_Eventlogs
about_Group_Policy_Settings
about_PSSnapins
about_Windows_RT
about_WMI
about_WMI_Cmdlets
about_WQL
about_Workflows

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by joeyaiello** [comment]
Yeah, there's some (like Workflows, Snapins, and Workflows) that need to go away altogether. Then there's the Windows vs. Linux ones. This needs to be done by 6.0.0 for sure.

**Comment by rkeithhill** [comment]
Rather than remove, is there a way we can make about topics conditional to the OS PowerShell is running on?  

Module authors will run into this where an about topic may not apply to an OS or they will want to have different topic content depending on the OS.  It sure would be nice to have a single, cross-platform module distribution.  

Maybe use a module dir structure like the following (if it exists) to serve up OS-specific help:
```
help\Windows
help\Linux
help\macOS
```

**Comment by iSazonov** [comment]
Should we move the issue in PowerShell-Docs repo? /cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@iSazonov I don't believe the help documents nor PowerShell Help has a mechanism to differentiate help for a specific OS.  We need to add that capability first before addressing in Doc repo.  cc @adityapatwardhan

**Comment by AspenForester** [comment]
Is this something that `Update-Help` could do?  Allow `Update-Help` to determine what OS it's running on and clobber the "abouts" that aren't appropriate?

**Comment by adityapatwardhan** [comment]
@sdwheeler - Is the applicable OS part of the new schema?

**Comment by sdwheeler** [comment]
I had proposed adding metadata for platform that could be useful here. I hadn't thought about it for About_ topics but no reason not to include it. The hard part building platform specific cab files.

I think we should include the help for all platforms but have Get-Help filter the view to the platform and have a parameter to select the platforms you want to see.

**Comment by iSazonov** [comment]
I agree with @sdwheeler that we should have one Help package for all platforms. On Windows I can need to read Unix topics and vice versa. (Also there are remoting scenarios.)
I do not think we need new filter/parameter for the same reason.

**Comment by kilasuit** [comment]
I think that instead of removing these docs we should instead update them to call out they are only applicable in specific OS, (if the whole doc is OS specific) or sections where they contain OS specific documentation

**Comment by ThomasNieto** [comment]
@sdwheeler now that the help has OS notes can this issue be closed?

**Comment by sdwheeler** [comment]
Including the help content on all platforms is by design.  Help content has been updated to include OS-specific caveats.
