### ISSUE TITLE
`ConvertTo-Csv` and `Export-Csv` should unroll (embedded) arrays and lists

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#18071]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Knowing that the `-InputObject` "*Specifies the objects that are converted to CSV strings*", I would expect that any embedded array or list to unroll into objects (see also: [Suggestion: Add a chunking (partitioning, batching) mechanism to Select-Object, analogous to Get-Content -ReadCount](https://github.com/PowerShell/PowerShell/issues/8270#issuecomment-1243457103))

```PowerShell
$List = 1..5 |ForEach-Object {
    [pscustomobject]@{ id = $_; name = "name$_" }
}

,$List |ConvertTo-Csv
```

### Expected behavior

```console
"id","name"
"1","name1"
"2","name2"
"3","name3"
"4","name4"
"5","name5"
```
Similar to:
```PowerShell
$List |Convert-Csv # Without an unary comma
```
and to what `Add-Content` and `Set-Content` does for:
```Powershell
,(1..5) |Set-Content .\MyFile.txt
```
Or simply as it is being output:
```PowerShell
,$List

id name
-- ----
 1 name1
 2 name2
 3 name3
 4 name4
 5 name5
```

### Actual behavior

```console
"Length","LongLength","Rank","SyncRoot","IsReadOnly","IsFixedSize","IsSynchronized","Count"
"5","5","1","System.Object[]","False","True","False","5"
```

### Error details

```console
No Error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
As a side effect    
`ConvertTo-Csv $list`    
would also work.  Generally there needs to be a very good reason why `$x | cmdlet`  does something different from `cmdlet $x`, and I've never seen why this is an exception (`ConvertTo-Json` enumerates items, but `convertTo-Csv` outputs properties of the list object).

**Comment by SteveL-MSFT** [comment]
The comma that precedes the array in the examples above explicitly makes the array a single object that passes through the pipeline vs each element of the array/collection being passed to the cmdlet.  So in this case, the cmdlet sees it as a single object (keep in mind it could have also been an array of arrays) and serializes it as such vs unrolling the collection.  So this is working by-design so that the user can differentiate treating an array as a collection or a single object through the pipeline.

**Comment by mklement0** [comment]
@iRon7, based on the conversation in #8270, I encourage you to open a new issue that explains the rationale for your suggestion in more detail.

@SteveL-MSFT, the underlying idea is to intentionally allow `ConvertTo-Csv` and `Export-Csv` to accept _collections as a whole_ for the sake of _improved processing speed_ (at the expense of memory consumption).

`Set-Content` and `Out-File` (and `Write-Output`)  already do that, but it's especially compelling with `ConvertTo-Csv` and `Export-Csv` (and possibly others), where doing anything _other_ than _enumerating_ a collection passed as a single object serves no useful purpose (in other words: the current behavior in that case is useless).

@jhoneill:

>  Generally there needs to be a very good reason why `$x | cmdlet` does something different from `cmdlet $x`

The reason for the fundamental difference is that `$x` is _implicitly enumerated_ in the pipeline, which doesn't happen if `$x` is passed _as an argument_. That is, `cmdlet` sees the _elements_ of `$x` as input, one by one, in the pipeline scenario, whereas it sees `$x` _as a whole_ in the argument scenario.

* https://github.com/PowerShell/PowerShell/issues/4242

provides the backstory.

**Comment by SteveL-MSFT** [comment]
@mklement0 if the request is an optimization to unroll a collection in the cmdlet vs via the pipeline, then would a `-InputCollection` parameter make sense?

**Comment by jhoneill** [comment]
> @iRon7, based on the conversation in #8270, I encourage you to open a new issue that explains the rationale for your suggestion in more detail.
> 
> @SteveL-MSFT, the underlying idea is to intentionally allow `ConvertTo-Csv` and `Export-Csv` to accept _collections as a whole_ for the sake of _improved processing speed_ (at the expense of memory consumption).
> 
> `Set-Content` and `Out-File` (and `Write-Output`) already do that, but it's especially compelling with `ConvertTo-Csv` and `Export-Csv` (and possibly others), where doing anything _other_ than _enumerating_ a collection passed as a single object serves no useful purpose (in other words: the current behavior in that case is useless).
> 
> @jhoneill:
> 
> > Generally there needs to be a very good reason why `$x | cmdlet` does something different from `cmdlet $x`
> 
> The reason for the fundamental difference is that `$x` is _implicitly enumerated_ in the pipeline, which doesn't happen if `$x` is passed _as an argument_.  

@mklement0 

Yes, I'm well aware of that.   
There's an expectation that commands do the work need so that    
`cmdlet $x, $y , $z ` or `$x, $y, $z  | cmdlet`  or `$a = @($x, $y, $z)   ; cmdlet $a`  
 give the same result. There are a few cases where that wouldn't make sense, but where it would...

**Comment by mklement0** [comment]
@jhoneill, my point was that given how pipeline-binding parameters currently work, _you shouldn't have this expectation_ - as desirable as this symmetry may be - and if you do, you'll be disappointed, with only a few, not documented-as-such exceptions.

As noted before, the only solution that would provide _performance benefits_ is to make all cmdlets where this symmetry makes sense explicitly do their _own_ enumeration.

A _general_ solution, as part of the _plumbing_ - which would  _not_ be performance-enhancing, unfortunately - is suggested [here](https://github.com/PowerShell/PowerShell/issues/4242#issuecomment-453827133).

**Comment by mklement0** [comment]
Given the above, @SteveL-MSFT, I don't think a separate parameter is called for.

What would make sense is to do a systematic review of all standard cmdlets and decide which ones should perform their own enumeration _without ambiguity_ (i.e. those cmdlets for which _not_ enumerating results in _useless_ behavior), and update those (I haven't done this review, and it's possible that `ConvertTo-Csv` and `Export-Csv` are the only candidates).

Separately, implementing the (opt-in) plumbing solution mentioned above makes sense to me, even if it doesn't result in performance gains.

**Comment by iRon7** [comment]
The reason that I actually opened a *bug report* for this and not a *feature request* is because aside for the possible performance improvement, this statement

> this is working by-design so that the user can differentiate treating an array as a collection or a single object through the pipeline.

might be ***generally*** correct but is pointless for the `ConvertTo-Csv` - and `Export-Csv` which are only able to generate **flat** `csv` list by ***their*** design (in my opinion, the particular cmdlet designs should take president here).
Also note that this general statement doesn't apply the `Set-Content`/ `Add-Content` cmdlets and for the default display output (`Write-Output` cmdlet) where the user (script author) isn't actually able to *differentiate between an array or a single object* (see also: #17701).

There are a [few cases in stackoverflow](https://stackoverflow.com/search?q=PowerShell+%22Length%22%2C%22LongLength%22%2C%22Rank%22%2C%22SyncRoot%22%2C%22IsReadOnly%22%2C%22IsFixedSize%22%2C%22IsSynchronized%22%2C%22Count%22) that relate to this expectation where regardless of whether I supply the groups via the pipeline or via a parameter argument, I might (**could**) only expect a *flat* `csv` list as an output (see also: #3865 [Export-Csv -InputObject and ConvertTo-Csv -InputObject export/convert the collection object itself rather than its elements](https://github.com/PowerShell/PowerShell/issues/3865)):

```PowerShell
$Process = Get-Process | Group-Object -Property PriorityClass
ConvertTo-Csv $Process.Group

"Length","LongLength","Rank","SyncRoot","IsReadOnly","IsFixedSize","IsSynchronized","Count" # is bogus
"258","258","1","System.Object[]","False","True","False","258"
```

**Comment by jhoneill** [comment]
> @jhoneill, my point was that given how pipeline-binding parameters currently work, _you shouldn't have this expectation_ - as desirable as this symmetry may be - and if you do, you'll be disappointed, with only a few, not documented-as-such exceptions.

@mklement0  yes I think we understand each other.  That expectation grows up because that's how well written commands work. PowerShell classes teach people that `foreach ($f in $files)  {Invoke-Something $f} is rarely necessary and `$files | inovke-Something` or `invoke-Something $files`  is "normal", and to write new commands to work that way.    

 Your later description that in some cases " _not_ enumerating results in _useless_ behavior "  sums it up neatly :-)  Useless, and (I think) often unexpected   

Some things like `Get-Member`, do the right thing by _not_ enumerating, (how else do we learn about the enumerable object ?  ) For export-CSV it's the wrong thing - and finding and fixing similar cases would be a benefit.

**Comment by mklement0** [comment]
@iRon7, I agree that this is worth tackling, but in a generalized manner - which amounts to a nontrivial amount of work:

I forgot that I _did_ try to compile a list of all cmdlets where passing arrays as a whole results in unless behavior, namely those in Category C from #4242 (additions / corrections welcome).

Thus, as that issue's title states, one possible resolution - and to me the preferred one - is to make _all_ cmdlets in that category do their own enumeration of collections received as single objects.

#4242 has languished for 5 years now, and it is focused on the `-InputObject`-vs.-pipeline asymmetry.
But as this discussion here shows, it also prevents chunked input from the pipeline.

So the question is whether there's a willingness to tackle this, bot for the sake of invocation symmetry and, perhaps more importantly, for the performance benefits it offers.

**Comment by jhoneill** [comment]
@mklement0  I'm looking at your category C items with a view to taking them to the cmdlet working group 

There might be some quibbles about what is truly in category C.  With `Where-object`,  someone somewhere is bound to want to use the count of members or even `-is [Array]` in a _where_ condition. But the list is a helpful place to start from.

**Comment by mklement0** [comment]
Thanks, @jhoneill - cmdlet-specific evaluation is definitely called for.

In that context, revisiting how the pipeline-binding parameters are _typed_ is also worthwhile (`object[]` vs. `object`), as discussed in #4242, and with respect to _performance_, particularly, in https://github.com/PowerShell/PowerShell/issues/18070#issuecomment-1247008638

Worth noting: #4242, which was focused on just _by-argument_ parameter binding without _batching via the pipeline_ being in the picture, discusses assuming that pipeline input is _already enumerated_ and performing the cmdlet-internal enumeration only for _argument_-bound values.

In order to support batching, however, this distinction mustn't be made.

**Comment by mklement0** [comment]
A quick look suggests that only `Set-Content` / `Add-Content` and `Join-String` have `psobject[]` parameters, not the other ones in Category B - as discussed, `psobject[]` / `object[]` parameters best avoided so as not to create array-allocation overhead with scalar input objects from the pipeline.

In C# you cannot directly enumerate scalars with `foreach`, so reflection is needed to check if a given object is an enumerable.
