### ISSUE TITLE
Method overload resolution: [NullString]::Value doesn't guide toward picking a [string]-based overload

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18072]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

` [NullString]::Value` was specifically introduced to pass a true `$null` value to `string`-typed method parameters.
Yet, during method overload resolution, it doesn't reliably select a `[string]`-based overload:

```powershell
class Foo {
  [string] Test([bool] $bar) { return 'bool'}
  [string] Test([string] $bar) { return 'string' }
}

# *Should* select the `[string]` overload, but doesn't.
[Foo]::new().Test([NullString]::Value)
# OK, with cast:
[Foo]::new().Test([string] [NullString]::Value)
```

### Expected behavior

```console
string
string
```

### Actual behavior

```console
bool
string
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.7
```

**Comment by dkaszews** [comment]
Can I get some background on why `NullString` was introduced? Shouldn't `[string] $null` work already, or was it broken and deemed a breaking change to fix?

It looks like the `[NullString]::Value` prefers implicit conversion of null to false over implicit conversion to string. Don't quite remember C#'s implicit conversion rules to say how easy of a fix it would be.

Can you play around with other overload sets? What if you add an explicit overload for `[NullString]`? Or something that it does not covert to, e.g. some other struct, but skip the bool one?

**Comment by mklement0** [comment]
`[string] $null` passes the empty string, not null: `'' -eq [string] $null` is `$true`.
This behavior also applies when passing `$null` to .NET methods, which - prior to the introduction of `[NullString]::Value` - made it impossible to pass true `null` to `string` parameters of .NET APIs.

**Comment by mklement0** [comment]
> What if you add an explicit overload for `[NullString]`?

The above implies that `[NullString]` isn't meant to be used as an actual type; it's `::Value` property merely serves to indicate that it should be _translated to `null`_ in string contexts.

Because `[NullString]::Value` is a singleton of a [distinct type](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.Language.NullString), it should be easy to distinguish it from `$null`.
