### ISSUE TITLE
All error prompts are extremely slow, and other command also lag sometimes.

### ISSUE THREAD

**Issue by aswirl4** [PowerShell/PowerShell#18081]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

It can acturally reproduce every moment for me.

### Expected behavior

```console
ps> spelled Wrongly command
# error prompt display immediately
```

### Actual behavior

```console
ps> spelled Wrongly command
# lag for about 2s less or more
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals
As you can see there the error promts out after cursor flickered for many times.
![annoying](https://user-images.githubusercontent.com/25301986/189903900-b1731c51-0819-4543-bd29-0995d3bb8140.gif)

**Comment by jhoneill** [comment]
Any shell looks every directory on you path for quick.exe, quick.bat, quick.cmd, quick.msc, quick.cpl, quick.vbs etc. 
(You can compare CMD or even Start/run on Windows to get an idea how long this takes) . Before that PowerShell checks for a loaded command with the name quick, then looks in all unloaded modules for quick., and then searches the path for quick.ps1  before looking for the others.   

If you have installed a lot of packages which add themselves to your system path, the problem will be worse, and if you have many PowerShell modules that you don't use it will also be worse.  Things improve after the first check, because of the effects of caching. 




// I need to file a request with Git hub now to disable looping animations. I had to resize the window to only have the write-reply box in because that strobing away stops me typing

**Comment by dkaszews** [comment]
Going on @jhoneill 's suggestion about search path: does it still happen if you do `$env:PATH = ''`? For the modules I can't quite recall how to rule that one out.

**Comment by peroperotina** [comment]
> Any shell looks every directory on you path for quick.exe, quick.bat, quick.cmd, quick.msc, quick.cpl, quick.vbs etc. (You can compare CMD or even Start/run on Windows to get an idea how long this takes) . Before that PowerShell checks for a loaded command with the name quick, then looks in all unloaded modules for quick., and then searches the path for quick.ps1 before looking for the others.
> 
> If you have installed a lot of packages which add themselves to your system path, the problem will be worse, and if you have many PowerShell modules that you don't use it will also be worse. Things improve after the first check, because of the effects of caching.
> 
> // I changed my github accessibility settings to stop that video looping - initially resized the window to contain only the write-reply box because that strobing away stops me typing



> Going on @jhoneill 's suggestion about search path: does it still happen if you do `$env:PATH = ''`? For the modules I can't quite recall how to rule that one out.

Yeah, I considered about those possibilities. I tired delete all modules or $env:PSModulePath='', and $env:path='',  nothing changes.
Let me describe more specifically, I have freshly installed powershell 7.2.6 from microsofte store, microsoft docs msi installer or this github releases, and even powershell 7.3 from microsoft store.  All of them behave as the issuse title said, while my powershell 1.0, cmd and ubuntu wsl shell works as fast as expected.
I have also checked my .net framework update.

I made a virtual machine in this 'powershell problem computer' and tried powershell 7, it is also as fast as expected. So It can't be hardware problem.

**Comment by jhoneill** [comment]
what happens if you run `Pwsh -noprofile` any better or just the same?

**Comment by peroperotina** [comment]
> Pwsh -noprofile

just the same.
