### ISSUE TITLE
pwsh executable installed as .NET Global Tool is not signed

### ISSUE THREAD

**Issue by ArthurHNL** [PowerShell/PowerShell#18087]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install PowerShell as .NET Global Tool (`dotnet tool install --global PowerShell`)
2. Look at the properties of `pwsh.exe` in the .NET tool directory.

### Expected behavior

```console
I expect the binary pwsh.exe to be signed.
```

### Actual behavior

```console
The binary pwsh.exe is not signed.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Properties of `pwsh.exe` installed as a .NET Global Tool (note the lack of a 'Digital Signatures' tab):
![image](https://user-images.githubusercontent.com/31919595/190162586-0ee9841f-f170-4a2f-8345-f516a2d990c2.png)

Properties of `pwsh.exe` installed by the 'regular' PowerShell installer:
![image](https://user-images.githubusercontent.com/31919595/190162706-559c500f-13bb-48e6-bf06-dfd1f7b77d66.png)

**Comment by StevenBucher98** [comment]
cc @TravisEz13

**Comment by PaulHigin** [comment]
@WG-Security
We believe the `pwsh.exe` file referred to above is generated by dotNet (`c:\users\xxx\dotnet\tools\pwsh.exe`), so we have no control over signing it.

@adityapatwardhan  Can you confirm?
