### ISSUE TITLE
Get-Help -ShowWindow won't work

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#1808]
## Steps to reproduce

Get-Help Get-Command -ShowWindow

I know this feature might not work but wanted to be reported,
## Expected behavior

Popup window with topic or command documentation
## Actual behavior

Nothing shows up.
## Environment data

Ubuntu 16.04 - powershell_6.0.0-alpha.8-1_amd64-ubuntu.16.04-x64

![poshlinuxgethelperr_06](https://cloud.githubusercontent.com/assets/19892435/17665323/3bd0ee06-62c8-11e6-86b8-185ee756233d.jpg)

``` powershell
> $PSVersionTable

```

**Comment by akelling** [comment]
See this on my Macbook as well

**Comment by MaximoTrinidad** [comment]
By the way!  This also applies to Windows PowerShell 6.0.0.9.
:)

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by pcgeek86** [comment]
Still seeing this on Alpha 18. It launches `less` without actually displaying any content.  @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
`-showwindow` relies on WPF which isn't supported.  `-online` is "equivalent" for now.  Seems like maybe we should remove that switch.  In 6.1.0 timeframe, I'd like to support curses and have interactive help at the console (searching, clickable links, etc...)

**Comment by MaximoTrinidad** [comment]
Just an FYI

Since I posted this feedback and I understand that can't be done yet, I'm started to play with Python 'tk' library to build the GUI apps.  It seems to me like it's an opportunity to use Python in this case.  Although I'm not a Python programmer I have figured out a raw sample for displaying results in a limited DataGrid-type view then integrate Python with PowerShell.

This is something to looked at! I think. And, I know it's going to take time to get it done.

:)

![poshpythingui_2017-05-07_9-50-40](https://cloud.githubusercontent.com/assets/19892435/25781690/cd792efa-330a-11e7-9906-9b967931f77c.jpg)

**Comment by pcgeek86** [comment]
@MaximoTrinidad Brilliant idea!!

**Comment by joeyaiello** [comment]
There's also the work being done in https://github.com/PowerShell/Phosphor that's trying to do this with HTML/CSS. Either way, pushing this out as a lower-priority.

**Comment by iSazonov** [comment]
Which file format will we use for Help? I see PowerShell-Docs use .md files.

**Comment by joeyaiello** [comment]
Like for the Get-Help help system? We plan to continue using MAML/XML there for the short-term--PowerShell-Docs uses platyPS to convert our Markdown help to MAML before publishing it--but in the long-term we have a desire to natively support Markdown (but no timeline, it's just a dream we've been discussing for...two years? /cc @vors)

**Comment by iSazonov** [comment]
It would be wonderful to open up a Meta-Issue with Plan to add natively support for Markdown help that the desire becomes a reality faster.

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan has been investigating the native markdown support and will eventually publish a RFC, we should probably just open an issue now to let people know you're working on this

**Comment by SteveL-MSFT** [comment]
Fixed by https://github.com/PowerShell/PowerShell/pull/4903
