### ISSUE TITLE
Get-Help about_* returns nothing

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#1809]
## Steps to reproduce

(get-help about_*) | select name

or trying to create a powershell object

$l = get-help about_*) | select name
## Expected behavior

list of all existing "about_*" topics
## Actual behavior

Won't create results and won't clear the screen after the search.

![poshlinuxgethelperr_07](https://cloud.githubusercontent.com/assets/19892435/17666249/5c84fa84-62cd-11e6-8d7b-9868e9b001c0.jpg)
## Environment data

Ubuntu 16.04 - powershell_6.0.0-alpha.8-1_amd64-ubuntu.16.04-x64

``` powershell
> $PSVersionTable

```

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by SteveL-MSFT** [comment]
#1625

**Comment by Liturgist** [comment]
Same result in v6.0.0-alpha.10.

**Comment by bcdady** [comment]
I see essentially the same symptom on PS Core 6 (alpha) on Mac OSX.

**Comment by Liturgist** [comment]
Same result using v6.0.0.0-alpha.13 on Ubuntu 16.04.

**Comment by MaximoTrinidad** [comment]
And, it won't clear the search messages from the screen neither when returning to cursor.
Both Ubuntu 16.04.1 and Windows 10 Bash.

![gethelp_01_2016-12-05_15-09-10](https://cloud.githubusercontent.com/assets/19892435/20901067/d2e0b4be-bafe-11e6-9ac8-101aa30d0339.png)

**Comment by joeyaiello** [comment]
So we fixed the progress issue, and we're shipping about_* topics on Linux, but for some reason the query above doesn't work. I can do something like `Get-Help about_prompts` (not case-sensitive) and it works fine, but `Get-Help about_*` returns nothing.

**Comment by MaximoTrinidad** [comment]
PowerShell Core 6.0.0-beta.1

Yes! Still nothing in Linux Ubuntu 16.04.2 when executing the following line:

Get-Help About_* | Select Name

Windows is fine!

Sample Ubuntu
![help_2017-05-24_16-12-40](https://cloud.githubusercontent.com/assets/19892435/26423496/e1c1bc12-409b-11e7-8581-493820fbdb7c.jpg)

**Comment by chunqingchen** [comment]
Verified and resolved by PR #3852
