### ISSUE TITLE
General Help Issues/Dodgey Code

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#18094]
### Summary of Issues

I was reading over the formatting and generation of help code a lot last month and I made note of some areas that are either missing functionality, are seemingly dead code, or cause inconsistencies.

#### Missing from MAML Help
- When using the default Extended help you get parameter aliases, function aliases, `parameterValueGroup` (which provides a list of valid values from the `ValidateSetAttribute`), and whether a parameter `isDynamic`. These all appear to be absent the moment you provide function documentation. #6694, #3006, #2869

#### General Issues
- `pipelineInput` for parameters is not using the `TrueFalseControl` in the the help formatters and is thus does not have locale support (is that exists) because it does not pull from a resource file (`HelpDisplayStrings`). **See Help_format_ps1xml**
-There is a lot of duplicated code when creating remarks, alerts, examples, input types, and return types formatters, these could be created once in the array and reused. **See Help_format_ps1xml**
- **HelpCommands.cs** doesn't handle parameter uniqueness and keeps returning all parameters that match the search criteria even when they have already been found (i.e. `Get-Help Get-Help -Parameter Name, Na* Nam*` would return the Name parameter 3 times):
```csharp
        private PSObject[] GetParameterInfo(HelpInfo helpInfo)
        {
            List<PSObject> parameterInfosList = new List<PSObject>(Parameter.Length);

            foreach (var parameter in Parameter)
            {
                foreach (var parameterInfo in helpInfo.GetParameter(parameter))
                {
                    parameterInfosList.Add(parameterInfo);
                }
            }

            return parameterInfosList.ToArray();
        }
```
This could be better handled with a `Dictionary<String, PSObject>` of unique pairings of `Name` to `PSObject` that returns the `.Values` as an array.

#### Dead code/unimplemented
- There exist formatters for `terminatingErrors` and `nonTerminatingErrors`, but I could find nothing in the code that populated these fields unless they come from an undocumented XML help tag. **See Help_format_ps1xml**
- `possibleValues` and `possibleValue` are also in the same boat, nothing in the code explicitly sets these, I assume they have since been replaced with `parameterValueGroup` , but their formatters still exist. **See Help_format_ps1xml**
- Formatters for MAML help are missing for some of the component parts: `syntaxItem`, `inputType`, `returnValue`, `navigationLink`. **See Help_format_ps1xml**
- Various places in the help formatters seemingly use more bindings than needed
- **HelpV3_format_ps1xml.cs** is missing a wide variety of format views, but since this is for documentation-less code it would probably be wasted effort to add them

### Proposed technical implementation details (optional)

None of the above things are particularly high priority, I just noted them and wanted to make sure there was at least some level of tracking around them. They are all fairly quick fixes and I may end up doing some of them eventually if I have time.

**Comment by theJasonHelmick** [comment]
@LethiferousMoose - Thank you for the concise issue list. We are aware of many of these and we agree these are a low priority. We are investigating a path forward and would like to keep this issue alive for @sdwheeler and @adityapatwardhan to ask questions.
