### ISSUE TITLE
Get-Process -ComputerName parameter won't work crossplatform

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#1810]
## Steps to reproduce

Get-Process -computername '10.0.0.18'

I know this may not be supported yet but I needed to try it. :)
## Expected behavior

List of system processes
## Actual behavior

Access to processes on remote machines is not supported...
And I crash Windows PowerShell. :)

![getprocesslinuxerr_01](https://cloud.githubusercontent.com/assets/19892435/17670187/cb3726a8-62de-11e6-8fa4-6fca8233e2d8.jpg)

![getprocesslinuxerr_02](https://cloud.githubusercontent.com/assets/19892435/17670191/ce2e86c6-62de-11e6-8a13-a8ec036a7467.jpg)
## Environment data

Ubuntu 16.04 - powershell_6.0.0-alpha.8-1_amd64-ubuntu.16.04-x64.deb

``` powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
We should consider deprecating this in PSCore and encourage use of PSRP for remoting needs.  Add to known issues when addressed.

**Comment by joeyaiello** [comment]
Right now, the guidance is to use PSRP and Invoke-Command for these purposes. We're throwing PlatformNotSupportedException without crashing now, so this is not as egregious as initially reported.

**Comment by MaximoTrinidad** [comment]
Hum!!  There's still a bug.

In Linux, trying the Get-Process -Computername WindowsSystemName (earth2), it will give a decent error message which is fine.

![getprocesserror](https://cloud.githubusercontent.com/assets/19892435/26432537/5faccf80-40ca-11e7-836b-355a5365c88a.png)

But, when doing from Windows to a Linux system (orion), there's no errors and default to local machine.

![lingetproc_2017-05-24_21-37-56](https://cloud.githubusercontent.com/assets/19892435/26432508/39e21d82-40ca-11e7-8bc6-30b129bba2a5.jpg)

**Comment by joeyaiello** [comment]
Would you mind opening another issue for that one, @MaximoTrinidad? This one is still relevant, but that one sounds like a higher-pri issue with a much easier fix.

**Comment by iSazonov** [comment]
See #4960
