### ISSUE TITLE
read-host bug

### ISSUE THREAD

**Issue by 20-EverGreen-2** [PowerShell/PowerShell#18110]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Make manually any file with EM DASH character on filename like:

"this is a — file input.txt"

and copy filepath to clipboard

# NEXT ON POWERSHELL WINDOW
Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
# HIT ENTER
# PASTE CLIPBOARD WITH RIGHT CLICK, THEN HIT ENTER AGAIN

### Expected behavior

```console
PS C:\>Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
"C:\some directory\this is a — file input.txt"

    Directory: some directory


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        14/09/2022     13:18              0 this is a — file input.txt
```

### Actual behavior

```console
PS C:\>Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
"C:\some directory\this is a — file input.txt" # this is a input text from clipboard via right click!!!
Get-ItemProperty: Cannot find path 'C:\some directory\this is a — file input.txt' because it does not exist.
PS C:\>
```

### Error details

```console
PS C:\> Get-Error

Exception             :
    Type                 : System.Management.Automation.ItemNotFoundException
    ErrorRecord          :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot find path 'C:\some directory	his is a — file input.txt' because it
does not exist.
            HResult : -2146233087
        TargetObject          : C:\some directory	his is a — file input.txt
        CategoryInfo          : ObjectNotFound: (C:\some directory\this…file input.txt:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PathNotFound
    ItemName             : C:\some directory	his is a — file input.txt
    SessionStateCategory : Drive
    TargetSite           :
        Name          : GetGlobbedMonadPathsFromMonadPath
        DeclaringType : System.Management.Automation.LocationGlobber, System.Management.Automation, Version=7.2.6.500, Culture=neutral,
PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message              : Cannot find path 'C:\some directory	his is a — file input.txt' because
it does not exist.
    Source               : System.Management.Automation
    HResult              : -2146233087
    StackTrace           :
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext
context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths,
CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.SessionStateInternal.GetProperty(String[] paths, Collection`1 providerSpecificPickList, CmdletProviderContext context)
   at System.Management.Automation.PropertyCmdletProviderIntrinsics.Get(String path, Collection`1 providerSpecificPickList, CmdletProviderContext
context)
   at Microsoft.PowerShell.Commands.GetItemPropertyCommand.ProcessRecord()
TargetObject          : C:\some directory	his is a — file input.txt
CategoryInfo          : ObjectNotFound: (C:\some directory\this…file input.txt:String) [Get-ItemProperty], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
InvocationInfo        :
    MyCommand        : Get-ItemProperty
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
    PositionMessage  : At line:1 char:1
                       + Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-ItemProperty
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :




PS C:\>
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
```powershell
Get-ItemProperty -LiteralPath (Read-Host).Replace('"','')
Get-ItemProperty -LiteralPath (Read-Host).Replace('"',$null)
```

**Comment by jhoneill** [comment]
@20-EverGreen-2   I copied your file name and tried those steps but can't repro. 
```
PS>  cd \temp

PS>  dir | out-file -LiteralPath (get-clipboard)

PS>  Get-ItemProperty -LiteralPath ((read-host).Replace("`"",""))
this is a — file input.txt                      # <-- Ctrl V to paste no quotes

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          16/09/2022    17:05           1359 this is a — file input.txt


PS>  Get-ItemProperty -LiteralPath ((read-host).Replace("`"",""))
"this is a — file input.txt"                   # <-- Ctrl V to paste  manually add quotes which are removed.

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          16/09/2022    17:05           1359 this is a — file input.txt


PS>  Get-ItemProperty -LiteralPath ((read-host).Replace("`"",""))
"this is a — file input.txt"                   # <-- Right click to paste

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          16/09/2022    17:05           1359 this is a — file input.txt
```

**Comment by 20-EverGreen-2** [comment]
Hi [jhoneill](https://github.com/jhoneill) !!!

Maybe you need to copy the character from app like babelmap.

Character code from this app in UCN format is: \u2014
HTML format: &mdash;
this is the character again: — 
I tried to upload a file with the character.

**Comment by 20-EverGreen-2** [comment]
[this is a — file input.txt](https://github.com/PowerShell/PowerShell/files/9587033/this.is.a.file.input.txt)

**Comment by 20-EverGreen-2** [comment]
Another thing
Im on a es-ES windows build!

**Comment by 20-EverGreen-2** [comment]
Hi [237dmitry](https://github.com/237dmitry) !

You create file from powershell console or manually?.

You need to create file manually.

**Comment by 237dmitry** [comment]
> You need to create file manually.

What is the difference? I created from powershell console. You see that the symbol ```"`u{2014}"``` is present.

**Comment by 20-EverGreen-2** [comment]
237dmitry , but youre on a unix system?

Im on a windows 10 IoT Ent 21H2 es-ES build.
I think is a Culture UI problem.

**Comment by 237dmitry** [comment]
>  but youre on a unix system?

But on Windows this works too:

![11](https://user-images.githubusercontent.com/78153320/190814855-bafbf65b-3662-4d1f-86da-7c755cfc08b2.png)

**Comment by 20-EverGreen-2** [comment]
> > but youre on a unix system?
> 
> But on Windows this works too:
> 
> ![11](https://user-images.githubusercontent.com/78153320/190814855-bafbf65b-3662-4d1f-86da-7c755cfc08b2.png)
> 
> > I think is a Culture UI problem.
> 
> Maybe
> 
> ```powershell
> PS >  $host.CurrentUICulture
> 
> LCID             Name             DisplayName
> ----             ----             -----------
> 1033             en-US            English (United States)
> 
>  PS > [console]::InputEncoding | Select WindowsCodePage, EncodingName
> 
> WindowsCodePage EncodingName
> --------------- ------------
>            1200 Unicode (UTF-8)
> ```

PS C:\> $host.CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
3082             es-ES            español (España)

PS C:\> [console]::InputEncoding | Select WindowsCodePage, EncodingName

WindowsCodePage EncodingName
--------------- ------------
                Western European (DOS)



I have this, i try to change settings same as you have.

**Comment by 237dmitry** [comment]
> i try to change settings same as you have.

change in intl.cpl to UTF8, reboot and add to $profile: `$PSDefaultParameterValues['*:Encoding'] = 'Default'`

**Comment by 20-EverGreen-2** [comment]
> > i try to change settings same as you have.
> 
> change in intl.cpl to UTF8, reboot and add to $profile: `$PSDefaultParameterValues['*:Encoding'] = 'Default'`

I try, but not luck.

`PS Q:\tmp> Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
this is a - file input.txt
Get-ItemProperty: Cannot find path 'this is a - file input.txt' because it does not exist.
PS Q:\tmp> $host.CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

PS Q:\tmp> [console]::InputEncoding | Select WindowsCodePage, EncodingName

WindowsCodePage EncodingName
--------------- ------------
           1200 Unicode (UTF-8)

PS Q:\tmp> chcp
Página de códigos activa: 65001`

I set beta support for UTF-8 on intl.cpl.
And this powershell command 
`$profile: $PSDefaultParameterValues['*:Encoding'] = 'Default'`

Returns error

`PS Q:\tmp> $PROFILE: $PSDefaultParameterValues['*:Encoding'] = 'Default'
ParserError:
Line |
   1 |  $PROFILE: $PSDefaultParameterValues['*:Encoding'] = 'Default'
     |  ~~~~~~~~~
     | Variable reference is not valid. ':' was not followed by a valid variable name character. Consider
     | using ${} to delimit the name.`

**Comment by 20-EverGreen-2** [comment]
Im running out of ideas.

**Comment by 237dmitry** [comment]
> And this powershell command

Add this in `$profile` ))
```
$PSDefaultParameterValues['*:Encoding'] = 'Default'
```
If `$profile` does not exist create it
```
if (-not (Test-path $profile)) { new-item $profile -Force }  # Documents\PowerShell\Microsoft.PowerShell_profile.ps1
```

**Comment by jhoneill** [comment]
> Two form are same for me at least.
> And notice the character has changed to a "-" minus symbol!!!

So either what is going into the clipboard has a "-" , or it gets converted as it goes through the clipboard. It's not read-host 


I tested this  

```
[int[]][char[]](get-item '.\this is a — file input.txt').name
116
104
105
115
32
105
115
32
97
32
8212    <# Unicode for em dash 
32
102
105
108
101
32
105
110
112
117
116
46
116
120
116

PS>  (get-item '.\this is a — file input.txt').name | set-clipboard

[int[]][char[]](Get-clipboard)
116
104
105
115
32
105
115
32
97
32
8212    <# Still there 
32
102
105
108
101
32
105
110
112
117
116
46
116
120
116
```

You might want to paste what is in the clipboard into something else, check you still have an em-dash.

**Comment by 20-EverGreen-2** [comment]
> [int[]][char[]](Get-clipboard)

I get a get-clipboard converted
`PS Q:\tmp> Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"",""))
[int[]][char[]](get-item '.\this is a - file input.txt').name
PS Q:\tmp> [int[]][char[]](get-item '.\this is a - file input.txt').name
116
104
105
115
32
105
115
32
97
32
8212
32
102
105
108
101
32
105
110
112
117
116
46
116
120
116`


`PS Q:\tmp> (get-item '.\this is a - file input.txt').name | set-clipboard
PS Q:\tmp> [int[]][char[]](Get-clipboard)
91
105
110
116
91
93
93
91
99
104
97
114
91
93
93
40
71
101
116
45
99
108
105
112
98
111
97
114
100
41
PS Q:\tmp>`

**Comment by 20-EverGreen-2** [comment]
> > [int[]][char[]](Get-clipboard)
> 
> I get a get-clipboard converted
> 
> `PS Q:\tmp> Get-ItemProperty -LiteralPath $((Read-Host).Replace("`"","")) [int[]][char[]](get-item).name PS Q:\tmp> [int[]][char[]](get-item).name 116 104 105 115 32 105 115 32 97 32 8212 32 102 105 108 101 32 105 110 112 117 116 46 116 120 116 PS Q:\tmp> (get-item '.\this is a - file input.txt').name | set-clipboard PS Q:\tmp> [int[]][char[]](Get-clipboard) 91 105 110 116 91 93 93 91 99 104 97 114 91 93 93 40 71 101 116 45 99 108 105 112 98 111 97 114 100 41 PS Q:\tmp>`

SORRY, this above output is from powershell 5.1

add powershell 7 output below


`PS Q:\tmp> chcp
Página de códigos activa: 850
PS Q:\tmp>
PS Q:\tmp>
PS Q:\tmp> [int[]][char[]](get-item '.\this is a  file input.txt').name
Get-Item: Cannot find path 'Q:\tmp\this is a  file input.txt' because it does not exist.
PS Q:\tmp> chcp 65001
Página de códigos activa: 65001
PS Q:\tmp>
PS Q:\tmp>
PS Q:\tmp> [int[]][char[]](get-item '.\this is a  file input.txt').name
Get-Item: Cannot find path 'Q:\tmp\this is a  file input.txt' because it does not exist.
PS Q:\tmp>`

Notice the transparent character EM DASH, i copied from your comment above " [int[]][char[]](get-item '.\this is a — file input.txt').name "

**Comment by iSazonov** [comment]
Please unload PSReadline module and try again.

**Comment by 20-EverGreen-2** [comment]
> Please unload PSReadline module and try again.

How to do bro?

**Comment by jhoneill** [comment]
What you have put above seems to be corrupted. Possibly because of formatting issues  can you enter it as 
`   ```  ` 
`text` 
` ``` `

**Comment by 20-EverGreen-2** [comment]
> What you have put above seems to be corrupted. Possibly because of formatting issues can you enter it as

Thx!, for the next.
I test recently on a virtual machine, in this case W10 Enterprise LTSC en-US native as OS and i have same issue.
Idk what happens, i installed powershell 7.2 via .msi downloaded from here:
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#msi

**Comment by theJasonHelmick** [comment]
The Working Group reviewed this issue but was unable to reproduce.
