### ISSUE TITLE
Users with a profile which outputs anything cannot create PSSessions over SSH

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#18118]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. If OpenSSHD is not already present, install it (e.g. on Windows run `Add-WindowsCapability -Online -Name  OpenSSH.Server~~~~0.0.1.0`) 
2. Enable Remote sessions over ssh by editing the sshd config file as described in https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.2  (on Windows copy `C:\Windows\System32\OpenSSH\sshd_config_default`  to  `C:\ProgramData\ssh\sshd_config` to give yourself a file to start from)
3. Backup your profile.ps1 if you have one, and create a simple `profile.ps1`  e.g. ` 'hello' `
4. run `new-PSSession  -HostName localhost`
5. Observe the error `New-PSSession: [localhost] There is an error processing data from the background process. Error reported: Hello.` 
6. Think "A-ha I need to use -NoProfile so SSH works like WinRM", modify the config file, restart the sshd Service, try again, curse when the same error occurs

### Expected behavior

```console
PS>  new-PSSession  -HostName localhost
xxxx@localhost's password:

 Id Name            Transport ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            --------- ------------    ------------    -----         -----------------     ------------
  5 Runspace4       SSH       localhost       RemoteMachine   Opened        DefaultShell             Available
```

### Actual behavior

```console
PS>  new-PSSession  -HostName localhost
xxxx@localhost's password:
New-PSSession: [localhost] There is an error processing data from the background process. Error reported: Hello.
```

### Error details

```console
New-PSSession: [localhost] There is an error processing data from the background process. Error reported: Hello.
```

### Environment data

```powershell
PS>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.7
PSEdition                      Core
GitCommitId                    7.3.0-preview.7
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="667" alt="image" src="https://user-images.githubusercontent.com/16209593/190858893-b55377d5-844c-48e9-8fb7-707391e8914d.png">

**Comment by jhoneill** [comment]
This is linked to  #13753  and in particular this comment from @PaulHigin  https://github.com/PowerShell/PowerShell/issues/13753#issuecomment-705796860  

That issue was (wrongly) closed as a external - because it was thought to lie with open ssh.  As Paul's comment linked to above explains the code has always followed an incorrect path and it appears  it was intended that `-sshs` should carry an implicit `NoProfile` but this has never been done.

**Comment by jhoneill** [comment]
As a work round, it is possible to recognize a SSH _connection_ without an SSH _tty_  and add this line to the profile at or near the top.

`if   ($env:SSH_CONNECTION -and $env:SSH_CLIENT -and -not $env:SSH_TTY) {return}`

**Comment by dkaszews** [comment]
Is this a Windows-only thing, or does it also happen on Linux? I never noticed this being an issue on Linux, though my Linux server has bash as default (because it starts faster) and I drop into PowerShell manually as required.

**Comment by 237dmitry** [comment]
Is this for 7.3.0 ? In 7.2.6 no errors.

![ns](https://user-images.githubusercontent.com/78153320/190868533-a89988ba-4171-44b5-8f47-874a7e945dcb.png)

**Comment by jhoneill** [comment]
@dkaszews  
> Is this a Windows-only thing, or does it also happen on Linux? I never noticed this being an issue on Linux, though my Linux server has bash as default (because it starts faster) and I drop into PowerShell manually as required.

How open do you open a PSSession to bash ?  :-)  This only applies to a PSSession. `ssh localhost` is fine. `New-PSSession` falls over. 

@237dmitry  
Yes 7.2.6 for me. As shown above, with an empty profile file, or a profile which exits without printing anything, all is fine.    
With a  `write-host`  or other output  
```
New-PSSession: [localhost] There is an error processing data from the background process. Error reported: «Text output by profile»
```

**Comment by dkaszews** [comment]
@dkaszews Sorry, got confused because the title says SSH

**Comment by jhoneill** [comment]
@dkaszews  good point, I've made the title clearer.

**Comment by 237dmitry** [comment]
Since basically the output to the console is from the prompt function, what happens if you do not delete the profile, but reset the prompt function? And is the prompt function considered part of the profile if it is called from an external file (dot source)?

```powershell
# 1st question

PS > function prompt {}   # or del function:prompt
```
```powershell
# 2nd question

. prompt-script.ps1  # there is not prompt function in my $profile at all
```

**Comment by jhoneill** [comment]
@237dmitry  It's not the prompt. 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/16209593/190896438-0080146a-2ece-49e6-b7c5-2ba5b04fa483.png">


Just connecting using SSH with pwsh set as the default shell for `sshd`  is fine. There are two things with PSSessions   
 
1.  A PSSession over WSMan _does not_ process the profile. The command to start pwsh in an ssh _subsystem_ 
    `Subsystem	powershell	c:/progra~1/powershell/7/pwsh.exe -sshs  ...` does.  
2. Any output form subsystem at start up seems to cause an error

I think (2) is expected with openssh -if  you don't specify `-NoLogo`  in the subsystem you get an error citing the the PowerShell version message (The way I have installed 7.3 preview means I can't test on that - the help I linked to above says the `-NoLogo` isn't needed in 7.3, so this symptom may have been silently fixed) 
 
But (1)...  PSSessions should do the same things regardless of the connection mechanism.  But the `-sshs` switch doesn't do that automatically and causes `-NoProfile to be ignored`  unless someone tells me that has also changed for 7.3

**Comment by jhoneill** [comment]
BTW when I wrote this  https://jhoneill.github.io/powershell/2019/06/22/Many-Shells.html   6.1 was current and  the problem didn't happen there.   

I just tried changing to the subystem config to use pwsh 6.2 and I get the same error so 
**The may be specific to Windows 11 / the version of Open SSH installed there**   
So my version of sshd reports it is 8.1.0.1 built June 4th 2021

**Comment by jborean93** [comment]
This won't be a problem with OpenSSH itself. When you use pwsh remoting over SSH the subsystem line is essentially the command that OpenSSH spawns when a new subsystem is requested. This process then uses the stdout/stdin to communicate the XML payloads needed for PSRemoting to work. If your profile runs and outputs anything on the console that could interfere with these payloads you get this problem. What should really happen is that either `-sshs` also implied `-NoProfile` (what I would expect and keeps it in line with WSMan) or makes sure that when `-sshs` is run then nothing else can write to the console to interfere with the PSRemoting communication.
