### ISSUE TITLE
PowerShell does not save accents correctly into variables

### ISSUE THREAD

**Issue by ajeetdsouza** [PowerShell/PowerShell#18119]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Run an external program that produces an accent in its output.
2. Save the output to a variable.
3. Print the variable.

```
>> $result = python -c "print('à')"
>> echo $result
α
```

### Expected behavior

```console
The accent in a string should be retained.
```

### Actual behavior

```console
The accent was changed (`à` -> `α`).
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by 237dmitry** [comment]
![11](https://user-images.githubusercontent.com/78153320/190876530-2358d149-3462-4545-b539-f86933acaa2c.png)

I think this is a problem of the system locale.

**Comment by mklement0** [comment]
PowerShell decodes output from external programs based on the encoding stored in `[Console]::OutputEncoding`, which defaults to the system locale's _OEM_ code page.

Python doesn't play by these rules and instead uses the system locale's _ANSI_ code page.

The solution is to (temporarily) set `[Console]::OutputEncoding` to that encoding, or, preferably, to UTF-8, along with requesting UTF-8 output from Python, using `-X utf8` (in earlier versions, set `$env:PYTHONUTF8=1` first):

```powershell
[Console]::OutputEncoding = [System.Text.Utf8Encoding]::new()
$result = python -X utf8 -c "print('à')"
$result
# You may want to restore the original [Console]::OutputEncoding value afterwards.
```

See also:

* https://github.com/PowerShell/PowerShell/issues/14945

**Comment by ajeetdsouza** [comment]
That works, thank you!
