### ISSUE TITLE
can not pass right dotnet enum that has memeber just of the case different

### ISSUE THREAD

**Issue by metasong** [PowerShell/PowerShell#18114]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
enum MyEnum {
a,
A
}
```

[MyEnum]::A
error throw because there is a 'a' of just the case different

### Expected behavior

```console
can pass the enum, or provide a way to pass
```

### Actual behavior

```console
error
```

### Environment data

```powershell
no
```

**Comment by 237dmitry** [comment]
> PowerShell is as case-insensitive as possible while preserving case.

[about_Case-Sensitivity](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_case-sensitivity?view=powershell-7.2)

**Comment by mklement0** [comment]
For the inverse problem, see:

* https://github.com/PowerShell/PowerShell/issues/10303
