### ISSUE TITLE
Test-Path with brackets in name files "C:\Temp\[Test].txt" -> False

### ISSUE THREAD

**Issue by ThierryRassat** [PowerShell/PowerShell#18112]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a file on windows system  : C:\Temp\\[Test].txt
Test-Path "C:\\Temp\\[Test].txt"

### Expected behavior

```console
True
```

### Actual behavior

```console
False
```

### Error details

```console
the filename in brackets is not recognized as a file for Test-Path
Test-Path "C:\Temp\(Test).txt"  return True
```

### Environment data

```powershell
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Do you have files name `T.txt` ,  `e.txt` , `s.txt` or `t.txt`  ? if not you need to use `-LiteralPath` or escape the `[]` characters.

**Comment by ThierryRassat** [comment]
Thank you for your suggestion to use -LiteralPath
