### ISSUE TITLE
Bug: Delete Environment.CurrentDirectory: OperationStopped: Unable to find the specified file.

### ISSUE THREAD

**Issue by hannasm** [PowerShell/PowerShell#18121]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
mkdir tmp
cd tmp
pwsh
rm -rf ../tmp

write-host 'hello world';
```

### Expected behavior

```console
hello world
```
```


### Actual behavior

```console
OperationStopped: Unable to find the specified file.
```
```


### Error details

```console
After deleting the directory that powershell was opened with the entire environment becomes catatonic. From experience i know there are some wierd issues with folder paths, sometimes you need to manually change 


[Environment]::CurrentDirectory = (pwd).Path
```

to make things work correctly and this problem is solved by this command
```


### Environment data

```powershell
this is run from an up-to-date snap installation on debian linux
```

**Comment by SteveL-MSFT** [comment]
This was already fixed via https://github.com/PowerShell/PowerShell/pull/17579
