### ISSUE TITLE
Error while installing or using pwsh 7.2.6 inside docker container

### ISSUE THREAD

**Issue by Reverendyz** [PowerShell/PowerShell#18129]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to create a symbolic link/use pwsh inside a docker container. as follow below

`
ENV POWERSHELL_VERSION=7.2.6
curl -sL https://github.com/PowerShell/PowerShell/releases/download/v${POWERSHELL_VERSION}/powershell-${POWERSHELL_VERSION}-linux-alpine-x64.tar.gz -o powershell-${POWERSHELL_VERSION}-linux-alpine-x64.tar.gz
`
This part is ok but, I've tested it.

But when I try to link to my /usr/local/pwsh `ln -s /path/to/folder/pwsh /usr/bin/pwsh` then use it `pwsh` it returns me this error:

`Error relocating /usr/bin/pwsh: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found`

This only occurs in 7.2.6.

I tried the same code with version 7.0.12 and it works fine.

### Expected behavior

```console
open Powershell
```

### Actual behavior

```console
Error relocating /usr/bin/pwsh: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

### Error details

```console
Error relocating /usr/bin/pwsh: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

### Environment data

```powershell
NA
```

**Comment by jborean93** [comment]
What docker image are you running this on? Is it an alpine based image or something else that uses musl?

**Comment by Reverendyz** [comment]
Downgrading the image to python:3.8-alpine3.14 worked!

Thank you!

**Comment by Reverendyz** [comment]
> What docker image are you running this on? Is it an alpine based image or something else that uses musl? If so what version of Alpine are you building against? It sounds like there's a problem with a mismatch symbol that could be caused by trying to use a musl linked dotnet binary but on a glibc host or a newer version of musl is incompatible with what dotnet provided at that version.
> 
> Having a reproducer script for what you are doing will be helpful for others trying to replicate your problem and try to figure out what the root cause is.

Downgrading the image to python:3.8-alpine3.14 worked!

Thank you!
