### ISSUE TITLE
Why does System.Diagnostic.Process#HandleCount exist? 

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#1812]
## Steps to reproduce

$a,$b = gps
$a.pstypenames
## Expected behavior

System.Diagnostic.Process
System.Object
## Actual behavior

System.Diagnostic.Process#HandleCount
System.Diagnostic.Process
System.Object
## Environment data

``` powershell
jps> $a,$b = get-process                                                                                                              
jps> $a.pstypenames                                                                                                                   
System.Diagnostics.Process#HandleCount
System.Diagnostics.Process
System.Object
jps> $PSVersionTable                                                                                                                  

Name                           Value                                                                                                 
----                           -----                                                                                                 
PSVersion                      6.0.0-alpha                                                                                           
PSEdition                      Core                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   3.0.0.0                                                                                               
GitCommitId                    v6.0.0-alpha.8                                                                                        
CLRVersion                                                                                                                           
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1        

```

**Comment by SteveL-MSFT** [comment]
Making a change may break existing remoting scenarios particularly between WindowsPowerShell and PowerShell Core.  Does not impact the functionality.  Recommend no change.

**Comment by iSazonov** [comment]
I caught the Issue when writing Pester tests:
```powershell
Get-Process | Export-Csv -Path $testfile -Force

#TYPE System.Diagnostics.Process#HandleCount
"HandleCount","Name","SI","Handles","VM","WS","PM","NPM","Path","Company","CPU","FileVersion","ProductVersion","Description","Product","__NounName","SafeHandle","BasePriority","ExitCode","HasExited","ExitTime","Id","MachineName","MaxWorkingSet","MinWorkingSet","Modules","NonpagedSystemMemorySize64","PagedMemorySize64","PagedSystemMemorySize64","PeakPagedMemorySize64","PeakWorkingSet64","PeakVirtualMemorySize64","PriorityBoostEnabled","PriorityClass","PrivateMemorySize64","ProcessName","ProcessorAffinity","SessionId","StartInfo","Threads","VirtualMemorySize64","EnableRaisingEvents","StandardInput","StandardOutput","StandardError","WorkingSet64","MainModule","PrivilegedProcessorTime","StartTime","TotalProcessorTime","UserProcessorTime"
"0","ApplicationFrameHost","3","0","2199252946944","20496384","12066816","17936","C:\Windows\system32\ApplicationFrameHost.exe",,"0.28125",,,,,"Process","Microsoft.Win32.SafeHandles.SafeProcessHandle","8",,"False",,"5776",".","1413120","204800","System.Diagnostics.ProcessModuleCollection","17936","12066816","328544","13901824","27131904","2199287431168","True","Normal","12066816","ApplicationFrameHost","15","3",,"System.Diagnostics.ProcessThreadCollection","2199252946944","False",,,,"20496384","System.Diagnostics.ProcessModule (ApplicationFrameHost.exe)","00:00:00.1562500","10/17/2016 6:13:36 AM","00:00:00.2812500","00:00:00.1250000"
```
I believe that this is not exactly what is expected.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please comment on this?

**Comment by daxian-dbw** [comment]
@iSazonov The `HandleCount` was kept there just to make sure when running `$p = Invoke-Command -Session $sn { Get-Process -Id $pid }` on a down-level powershell client targeting a powershell core on server side, it doesn't throw exception on the down-level powershell client.

Object like `System.Diagnostics.Process` is deserialized to `Deserialized.System.Diagnostics.Process` when transferring from server to client. Type `Deserialized.System.Diagnostics.Process` is defined in `types.ps1xml`, and if you inspect the definition, you will see the property `HandleCount` is present, and it's expected when powershell deserializes the `Process` object. The missing of such property will cause an exception to be thrown on the client side.

We certainly can change `types.ps1xml` and powershell core to make it not expect the `HandleCount` property when deserializing `Process` objects from server. However, that won't help the existing down-level powershell instances out there, and we still want the down-level PS client to be able to remote to powershell core without problems. That's why we kept the `HandleCount` property, even though it's meaningless in CoreCLR.

**Comment by iSazonov** [comment]
@daxian-dbw Thanks for the _great_ in-depth explanation. This clearly. But my question is easier. My question is specifically about Export-Csv behavior.
Why do Export-Csv write "Type#HandleCount" in Powershell 6.0 while the _expected_ behavior is to write "Type"? I believe it is bug and regression.

In Powershell 5.0:
```powershell
$a= Get-Process -ComputerName comp
$a[0].psobject

ImmediateBaseObject : System.Diagnostics.Process (avagent)
BaseObject          : System.Diagnostics.Process (avagent)
TypeNames           : {System.Diagnostics.Process, System.ComponentModel.Component, System.MarshalByRefObject,
                      System.Object}
```
In Powershell 6.0:
```powershell
$a= Get-Process -ComputerName comp
$a[0].psobject

ImmediateBaseObject : System.Diagnostics.Process (ApplicationFrameHost)
BaseObject          : System.Diagnostics.Process (ApplicationFrameHost)
TypeNames           : {System.Diagnostics.Process#HandleCount, System.Diagnostics.Process, System.Object}
```

In code Export-Csv get TypeNames[0]. Perhaps we need to take **BaseObject** ? Or remove #HandleCount from TypeNames[0]? Or take TypeNames[1] if TypeNames[0] contains "#HandleCount"?

**Comment by lzybkr** [comment]
It seems somewhat useful to know the `HandleCount` property was synthesized and therefore not useful, e.g. we could change the display of `ProcessInfo` to not show the `HandleCount` property at all if the typename is `ProcessInfo#HandleInfo`.

**Comment by iSazonov** [comment]
@lzybkr If this will fix both (@jpsnover and my) issues, maybe should reopen the Issue?

**Comment by iSazonov** [comment]
According to #2207 it is CoreCLR bug that is waiting for a fix.

**Comment by SteveL-MSFT** [comment]
Recommendation is to change the formatting to not show this as it's not useful to admin and the property is still available for compat reasons

**Comment by iSazonov** [comment]
Where should it be fixed?  Maybe here in [Process.cs](https://github.com/PowerShell/PowerShell/blob/309bf603f9aff9009dce7e725d42b2d4f99f58c9/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L824)
```C#
             // In CoreCLR, the System.Diagnostics.Process.HandleCount property does not exist. 
             // I am adding a note property HandleCount and temporarily setting it to zero. 
             // This issue will be fix for RTM and it is tracked by 5024994: Get-process does not populate the Handles field. 
             PSMemberInfo hasHandleCount = processAsPsobj.Properties["HandleCount"]; 
             if (hasHandleCount == null) 
             { 
                 PSNoteProperty noteProperty = new PSNoteProperty("HandleCount", 0); 
                 processAsPsobj.Properties.Add(noteProperty, true); 
                 processAsPsobj.TypeNames.Insert(0, "System.Diagnostics.Process#HandleCount"); 
             } 
```
remove `processAsPsobj.TypeNames.Insert(0, "System.Diagnostics.Process#HandleCount");`
I have not found using this in code anywhere.

**Comment by SteveL-MSFT** [comment]
@iSazonov the suggestion is to change the formatter and keep the code for compat reasons.  this way it doesn't show up for the interactive user as it's not really useful anyways (IMHO), but still available on the object (on Windows for some dev scenarios).  while looking for the code, I already made a fix and will submit a PR

**Comment by iSazonov** [comment]
@SteveL-MSFT Clear! Thanks!
