### ISSUE TITLE
How to test whether pwsh.exe runs in scp

### ISSUE THREAD

**Issue by CY-Pan** [PowerShell/PowerShell#18127]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm running openSSH Server on Windows with pwsh as the default shell. I have the following line in $PROFILE:
`Set-PSReadLineOption -PredictionSource History`
 
When I use `scp` from other computer to this one, it always shows warning:
![image](https://user-images.githubusercontent.com/59761962/191028660-6bd4ae69-bf14-412f-bb99-442a462bcfc9.png)

I suppose openSSH Server always load the whole profile in both `ssh` and `scp`. I want to keep this setting in `ssh` connection, but not to load it in `scp`. I tried using `[Environment]::UserInteractive` variable, but it cannot tell `ssh` from `scp` (value is False for both).

So is there a proper command to test whether pwsh.exe is run in scp? (like `[[ $- == *i* ]]` in Linux)

### Expected behavior

```console
Disable some profile lines in `scp`.
```

### Actual behavior

```console
Always load the whole profile in `scp`.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
edit  C:\ProgramData\ssh\sshd_config ，add  -NoProfile  ，let you bypass profile see 13753  18118

---- 

Regardless of the topic.
Did you know:
powershell supports new-pssession and copy-item -fromsession and -tosession
Between linux master and win, linux node.

If you're interested, check out this script I wrote:
https://gitee.com/chuanjiao10/kasini3000/blob/master/k_copyfrom_ip_port_l2l_user.ps1
https://gitee.com/chuanjiao10/kasini3000/blob/master/k_copyto_ip_port_l2l_user.ps1

**Comment by CY-Pan** [comment]
> edit C:\ProgramData\ssh\sshd_config ，add -NoProfile ，let you bypass profile. see 13753 18118

This solution is not satisfying, since I do want profile in `ssh` connection.
But 18118 mentions another variable `SSH_TTY` that works.
The combination of `SSH_CONNECTION` and `SSH_TTY` successfully solve my problem, like this way:
![image](https://user-images.githubusercontent.com/59761962/191181539-9c565bfc-04b9-495f-822a-434907dd6ed1.png)

Thank you for your help!
