### ISSUE TITLE
Use `System.IO.Pipes.PipeStream`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#18145]
i.e: sync `System.Management.Automation.Runspaces.SSHConnectionInfo.OpenStream` code taken from dotnet with changes from https://github.com/dotnet/runtime/pull/44647

https://github.com/PowerShell/PowerShell/blob/5f4e1004569443fbe76d23b54caac96b6fb20a40/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2360-L2363

https://github.com/PowerShell/PowerShell/blob/5f4e1004569443fbe76d23b54caac96b6fb20a40/src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs#L2433

https://github.com/dotnet/runtime/blob/9d6396deb02161f5ee47af72ccac52c2e1bae458/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L840

**Comment by iSazonov** [comment]
What is benefits you expect?

**Comment by SteveL-MSFT** [comment]
Based on the [microbenchmarks](https://github.com/dotnet/runtime/pull/44647#issuecomment-734848834) it doesn't seem like there would be any noticeable perf difference.

**Comment by xtqqczze** [comment]
We have code in `src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs` taken from dotnet (see description). We should consider pulling upstream changes (i.e. use of `PipeStream`).

**Comment by xtqqczze** [comment]
(from #18751) We have code in `src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs` that could use `NamedPipeClientStream`.
