### ISSUE TITLE
Add `.foreach` and `.where` methods to `string` and/or `Text.StringBuilder` type

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#18157]
### Summary of the new feature / enhancement

One might easily index into a `string`:

```PowerShell
'Test'[1]
e
```

And a `Text.StringBuilder` type where it is even possible to write:

```PowerShell
$Test = [System.Text.StringBuilder]'test'
$Test[1] = 'a'
$Test.ToString()
Tast
```

From that aspect, one might also assume to be able to easily iterate through either of these types using the PowerShell  `.where` or `.foreach` methods. Yet, currently, it is required to setup a loop for this, similar to e.g.:
```PowerShell
for ($i = 0, $i -lt $Test.Length; $i++) { $_[$i] }
```
Or transform everything into a character array:
```PowerShell
$LongString.ToCharArray()
```
Which would be quiet expensive, if I would like to do something like this:
```PowerShell
$LongString.where({ $_ -ne $Char }, 'First').foreach{ ... }
```

A lot of use cases for this request might of cause also achieved with regular expressions, but regular expressions are not PowerShell and therefore more cryptic and limited to a certain complexity.

**Comment by jhoneill** [comment]
(a) It's a breaking change    `$x = $longstring.where({$_ -match ' ' }) `  is a short cut for
 ```
if ($longstring -match ` `) {$x = $longString} else {$x = $null}  
```
(b) What is so bad about   `[char[]]"LongString" | where {$_ -ne "o"} | foreach {"$_".toUpper()}`   ?
(c) Regular expressions are a core part of PowerShell - used by `-match` , `-split` etc.   `$longstring -split ''` gives an array of strings rather than chars so is better than (b) IMHO.

**Comment by iRon7** [comment]
You right, the feature request was based on a stupid mistake on my side (I had wrongly `$longstring.while{ ... }` written which produced an **InvalidOperation: Method invocation failed because [System.String] does not contain a method named 'While'."** which had put me on the wrong feet.

**Comment by iRon7** [comment]
...or use the [CharEnumerator](https://learn.microsoft.com/dotnet/api/system.charenumerator):

```PowerShell
"LongString".GetEnumerator().where{ $_ -ne 'o' }.foreach{ "$_".ToUpper() }
```
