### ISSUE TITLE
Object getting updated when I issue a "select-object" and "where-object" command

### ISSUE THREAD

**Issue by scott-doyland-burrows** [PowerShell/PowerShell#18150]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

A object is getting updated when all I am doing is querying the object.  Note how the ```phase``` below is altered when I issue:

```echo $values | select-object -expandproperty values | where {$_.phase = "abc"}```

May be my misunderstanding of what I am doing?

```
PS C:\Users\Administrator\json> $projects = cat scott.txt  | Convertfrom-Json
PS C:\Users\Administrator\json> $values = $projects |  select-object -expandproperty projects
PS C:\Users\Administrator\json> echo $values

project values
------- ------
p703    {@{region=foe; phase=System.Object[]; market=System.Object[]}, @{region=img; phase=System.Object[]; market=System.Object[]}, @{project=p703; region=taiwan; ph…

PS C:\Users\Administrator\json> echo $values |  select-object -expandproperty values

region phase                        market
------ -----                        ------
foe    {launch, pre-launch, reveal} {all, bel, cze, deu…}
img    {launch, pre-launch, reveal} {all, aus, tha, vnm…}
taiwan {launch, pre-launch, reveal} {all, twn}

PS C:\Users\Administrator\json> echo $values | select-object -expandproperty values | where {$_.phase = "abc"}
PS C:\Users\Administrator\json> echo $values |  select-object -expandproperty values

region phase market
------ ----- ------
foe    abc   {all, bel, cze, deu…}
img    abc   {all, aus, tha, vnm…}
taiwan abc   {all, twn}
```

### Expected behavior

```console
The object should not get updated.
```

### Actual behavior

```console
The object is getting updated.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by scott-doyland-burrows** [comment]
So it seems this was because I was using ```=``` rather than ```-eq```.

This selects the relevant info from the object:

```echo $values | select-object -expandproperty values | where {$_.phase -eq  "abc"}```

This updates the object so ```phase``` = ```xyz```:
```echo $values | select-object -expandproperty values | where {$_.phase =  "xyz"}```

**Comment by kilasuit** [comment]
Hi Scott

This is an easy mistake to make, hopefully with the below explanation and links to additional docs to read up on it won't be one that you make all that often

`=` in PowerShell is one of a few [assignment operators](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_assignment_operators?view=powershell-7.2)
whereas
`-eq` much like its opposite `-ne` is a [comparison operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.2)
