### ISSUE TITLE
pwsh -c 'Get-Module' not work on new version of WSL linux kernel (5.10.102.1-microsoft-standard-WSL2)

### ISSUE THREAD

**Issue by pacorreia** [PowerShell/PowerShell#18151]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Start a bash shell in Ubuntu (using WSL in my case)
2. Run: `pwsh -c 'Get-Module'

### Expected behavior

```console
~:pwsh -c 'Get-Module'
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.0.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}
```

### Actual behavior

```console
~:pwsh -c 'Get-Module'
~:
```

### Error details

```console
No error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Bug](https://user-images.githubusercontent.com/54323159/191996961-79e5f4f2-a4b7-4d2c-8e78-3dbdb98abe2b.gif)

**Comment by 237dmitry** [comment]
Could not reproduce on installed Linux (Not WSL, bash-5.1.16, pwsh-7.2.6)
![000](https://user-images.githubusercontent.com/78153320/192009490-5f114905-a265-492b-9e70-79352cd844c1.png)

**Comment by pacorreia** [comment]
> Could not reproduce on installed Linux (Not WSL, bash-5.1.16, pwsh-7.2.6)
> ![000](https://user-images.githubusercontent.com/78153320/192009490-5f114905-a265-492b-9e70-79352cd844c1.png)
> 
> 

Interesting, meanwhile the:
Get-Installed Modules worked, so what could cause the behavior?

**Comment by kasini3000** [comment]
# I can reproduce the problem in both and almalinux 8.6, openeuler 22.03,ubuntu 22.04,microsoft cblm 2.0

but can not reproduce the problem in centos7, in ubuntu20.04

There should be some reason here that I don't know.
My guess: It seems to be related to the kernel being too new, or not support for some reason


```
on my almalinux 8.6 vm:
[root@alma86 ~]# pwsh -c 'Get-Module'     <-------return none!
[root@alma86 ~]# pwsh
PowerShell 7.2.6
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOptio…

PS /root> exit
[root@alma86 ~]# pwsh -c 'Get-Module'
[root@alma86 ~]# pwsh -c '$psversiontable ;Get-Module'

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 06:07:14 EDT 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

[root@alma86 ~]# pwsh -c '$env:psmodulepath'
[root@alma86 ~]# pwsh
PowerShell 7.2.6
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> $env:psmodulepath
PS /root> $env:PSModulePath
/root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
PS /root> exit             
[root@alma86 ~]# pwsh -c '$env:PSModulePath'
/root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
[root@alma86 ~]# pwsh -c 'Get-Module'
[root@alma86 ~]# 


```
my vm is : AlmaLinux-8.6-x86_64-minimal.iso new install.

would you like change title to 【pwsh -c 'Get-Module' not work on new version of linux kernel】

**Comment by pacorreia** [comment]
> # I can reproduce the problem in both and almalinux 8.6, openeuler 22.03,ubuntu 22.04,microsoft cblm 2.0
> 
> but can not reproduce the problem in centos7, in ubuntu20.04
> 
> There should be some reason here that I don't know.
> My guess: It seems to be related to the kernel being too new, or not support for some reason
> 
> 
> ```
> on my almalinux 8.6 vm:
> [root@alma86 ~]# pwsh -c 'Get-Module'     <-------return none!
> [root@alma86 ~]# pwsh
> PowerShell 7.2.6
> Copyright (c) Microsoft Corporation.
> 
> https://aka.ms/powershell
> Type 'help' to get help.
> 
> PS /root> get-module
> 
> ModuleType Version    PreRelease Name                                ExportedCommands
> ---------- -------    ---------- ----                                ----------------
> Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOptio…
> 
> PS /root> exit
> [root@alma86 ~]# pwsh -c 'Get-Module'
> [root@alma86 ~]# pwsh -c '$psversiontable ;Get-Module'
> 
> Name                           Value
> ----                           -----
> PSVersion                      7.2.6
> PSEdition                      Core
> GitCommitId                    7.2.6
> OS                             Linux 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 06:07:14 EDT 2022
> Platform                       Unix
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> 
> [root@alma86 ~]# pwsh -c '$env:psmodulepath'
> [root@alma86 ~]# pwsh
> PowerShell 7.2.6
> Copyright (c) Microsoft Corporation.
> 
> https://aka.ms/powershell
> Type 'help' to get help.
> 
> PS /root> $env:psmodulepath
> PS /root> $env:PSModulePath
> /root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
> PS /root> exit             
> [root@alma86 ~]# pwsh -c '$env:PSModulePath'
> /root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
> [root@alma86 ~]# pwsh -c 'Get-Module'
> [root@alma86 ~]# 
> 
> 
> ```
> my vm is : AlmaLinux-8.6-x86_64-minimal.iso new install.
> 
> would you like change title to 【pwsh -c 'Get-Module' not work on new version of linux kernel】

Thanks, that makes sense, will do

**Comment by 237dmitry** [comment]
> on new version of linux kernel

I propose to clarify the title `on new version of WSL linux kernel`. For example, in my case everything works with new kernel:
```console
$  uname -r
5.19.10-arch1-1
```
In addition, the Linux kernel is too broad a concept to use without specifics. It can be vanilla or set up by maintainers for different distributions with different patches and settings.

**Comment by StevenBucher98** [comment]
cc @craigloewen-msft

**Comment by kasini3000** [comment]
## ms cblm 2.0
```
root@cbml2 [ ~ ]# uname -a
Linux cbml2 5.15.57.1-3.cm2 #1 SMP Wed Aug 24 23:46:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@cbml2 [ ~ ]# pwsh -c 'Get-Module'
root@cbml2 [ ~ ]# 
```

## ubuntu 22.04 lts
```
root@ubuntu2204:~# pwsh -c 'Get-Module'
root@ubuntu2204:~# uname -a
Linux ubuntu2204 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

## alma linux 8.6 
```
[root@alma86 ~]# uname -a
Linux alma86 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 06:07:14 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@alma86 ~]# pwsh -c 'get-module'
[root@alma86 ~]# 
```

## openeuler2203

```
[root@euler2203 ~]# uname -a 
Linux euler2203 5.10.0-60.57.0.85.oe2203.x86_64 #1 SMP Wed Sep 21 16:53:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@euler2203 ~]# pwsh -c 'get-module'
[root@euler2203 ~]# 
```

**Comment by iSazonov** [comment]
If I understand the issue correctly `Get-Module` works well in PowerShell session but not with `pwsh -c 'Get-Module'`, yes?
Questions:
- is there the issue with other cmdlets? `pwsh -c 'Get-Date'`
- what is we remove quotes? `pwsh -c Get-Module`

**Comment by pacorreia** [comment]
> If I understand the issue correctly `Get-Module` works well in PowerShell session but not with `pwsh -c 'Get-Module'`, yes? Questions:
> 
> * is there the issue with other cmdlets? `pwsh -c 'Get-Date'`
> * what is we remove quo


![cmdlets-bash](https://user-images.githubusercontent.com/54323159/192720479-8da74702-6a34-4191-ac65-d70e640128ab.gif)
tes? `pwsh -c Get-Module`
