### ISSUE TITLE
Date format "ddMMMyy" fails for September Dates (producing 01Sept22 not 01Sep22)

### ISSUE THREAD

**Issue by NETvide** [PowerShell/PowerShell#18165]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For September dates "{0:ddMMMyy}" -f $(Get-Date) produces the four character month abbreviation Sept rather than Sep. Problem first appeared in 7.2.6 not seen in any other version of Powershell 5, 6 or 7

### Expected behavior

```console
1..12 | foreach { ([DateTime] "2022-$_-01").ToString("ddMMMyy") }
...
01Aug22
01Sep22
01Oct22
...
```

### Actual behavior

```console
1..12 | foreach { ([DateTime] "2022-$_-01").ToString("ddMMMyy") }
...
01Aug22
01Sept22
01Oct22
...
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Set "en-US" culture and restarted pwsh session.
```powershell
Set-Culture -CultureInfo 1033
```
![Screenshot 2022-09-27 140859](https://user-images.githubusercontent.com/78153320/192510281-fc500638-4740-42ed-81b5-e0772ec51c02.png)

**Comment by NETvide** [comment]
Setting the Culture to en-US (1033) does fix the problem but by default I use en-GB (2057) and using set-culture to restore en-GB also brings the problem back so "ddMMMyy" bug is impacted by the current culture.

**Comment by 237dmitry** [comment]
I think this is such a format:
```powershell
 $ (Get-Culture -name 'en-GB').DateTimeFormat.AbbreviatedMonthNames
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sept
Oct
Nov
Dec

 $ (Get-Culture -name 'en-US').DateTimeFormat.AbbreviatedMonthNames
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
```
And this is rather dotnet issue
```powershell
 $ [Globalization.CultureInfo]::new(2057).DateTimeFormat.AbbreviatedMonthNames
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sept
Oct
Nov
Dec
```

**Comment by NETvide** [comment]
Agreed, are you able to post this as a verified issue to the dotnet Team as it's a difference from all other dotnet versions I've ever used.

**Comment by iSazonov** [comment]
```
(Get-Culture -name 'en-GB').DateTimeFormat.AbbreviatedMonthNames
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
```

I don't see the issue. 

Really .Net gets all the information from OS. So root of the issue is in Windows OS version you use.

**Comment by 237dmitry** [comment]
> Really .Net gets all the information from OS. So root of the issue is in Windows OS version you use.

On Linux the same.

**Comment by NETvide** [comment]
I've used the **DOTNET_SYSTEM_GLOBALIZATION_USENLS** environment variable (as documented here https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#nls) to force the use of NLS. This fixes the output of [Globalization.CultureInfo]::new(2057).DateTimeFormat.AbbreviatedMonthNames so SEP not SEPT. I can see no justification for en-GB producing SEPT when no Windows/.NET version has done so in the past and the en-US coding continues to produce the correct SEP. Can you escalate this to the .NET team or is there an alternative way of logging the problem.
