### ISSUE TITLE
File mode in Linux should reflect Linux modes

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/PowerShell#1817]
## Steps to reproduce

In any Linux installation run a dir command. 
## Expected behavior

I would expect the same mode ouput you would get running ls -al
## Actual behavior

Mode property is all ---------
## Environment data

<img width="338" alt="pslinux-mode" src="https://cloud.githubusercontent.com/assets/12089920/17675192/b7d643b0-62f6-11e6-8e04-dd10197ad5ac.png">

**Comment by SteveL-MSFT** [comment]
We should try to have a consistent experience for Linux Bash users.  See if we can add custom formatting for Linux to enable this.

**Comment by DHowett-MSFT** [comment]
Relies on/discussed further in dotnet/corefx#312

**Comment by iSazonov** [comment]
Fixed in #11042
