### ISSUE TITLE
macOS: opening documents by file path only is broken

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18181]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following is currently broken on macOS 12.6:

```powershell
'hi' > t.txt
./t.txt  # !! Nothing happens.
```

Note that `Invoke-Item ./t.txt` works.

### Expected behavior

`./t.txt` should open in the default text editor.

### Actual behavior

Nothing happens.

### Environment data

```powershell
PowerShell Core 7.3.0-preview.8 (also present in 7.2.6) on macOS 12.6 (M1)
```

**Comment by dkaszews** [comment]
I'll need to check it, but on Windows I always use `Start-Process ./t.txt` to open file in default program, I assumed that just `./t.txt` would throw an equivalent of "file is not executable"

**Comment by SteveL-MSFT** [comment]
I'm debugging this and on macOS, `UseShellExecute` is being set correctly as the file is not executable.  Not sure yet why it's not working as expected.

**Comment by StevenBucher98** [comment]
> I'll need to check it, but on Windows I always use `Start-Process ./t.txt` to open file in default program, I assumed that just `./t.txt` would throw an equivalent of "file is not executable"

When you do `./t.txt` it opens in notepad, also able to reproduce this on my mac. Typically with zsh it says "Command not found.

**Comment by SteveL-MSFT** [comment]
Took a bit of time going through different versions of pwsh to find out where the regression was introduced and it was in 7.2-preview.6.  It appears that the process is being started, but then immediately killed.  I'll have a fix.

**Comment by dkaszews** [comment]
@SteveL-MSFT Good job hunting it down. BTW, did you do it manually or use git bisect? It's an awesome tool not many people know about, you give it a passing and failing commit and a test script (here: compile, run test line, detect process started or prompt user to say whether case passes if it's too difficult to automate) and it finds the breaking chang
e with log2(n) steps.

**Comment by iSazonov** [comment]
@dkaszews Blame view in GitHub works faster :-)
