### ISSUE TITLE
Move-Item trying to create directory even though directory had already existed

### ISSUE THREAD

**Issue by solomoncyj** [PowerShell/PowerShell#18190]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. have a folder nested in one anther with the same name and be in the parent directory
2. run ```PS > mv  -Path ./drakensang\drakensang -Destination .\```

### Expected behavior

```console
PS > mv -Path ./drakensang\drakensang -Destination .\
job sucessfully completes with the contents of ./drakensang\drakensang in .\drakensang
```

### Actual behavior

```console
PS > mv  -Path ./drakensang\drakensang -Destination ./
Move-Item: Cannot create 'C:\Users\solomon\winget-pkgs\manifests\b\Bigpoint\drakensang' because a file or directory with the same name already exists.
```

### Error details

```console
Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : MoveDirectory
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Cannot create 'C:\Users\solomon\winget-pkgs\manifests\b\Bigpoint\drakensang' because a file or
directory with the same name already exists.
    Source     : System.Private.CoreLib
    HResult    : -2147024713
    StackTrace :
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Microsoft.PowerShell.Commands.FileSystemProvider.MoveDirectoryInfoUnchecked(DirectoryInfo directory, String
destinationPath, Boolean force)
   at Microsoft.PowerShell.Commands.FileSystemProvider.MoveDirectoryInfoItem(DirectoryInfo directory, String
destination, Boolean force)
TargetObject          : C:\Users\solomon\winget-pkgs\manifests\b\Bigpoint\drakensang\drakensang
CategoryInfo          : WriteError: (C:\Users\solomon\wi…akensang\drakensang:DirectoryInfo) [Move-Item], IOException
FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
InvocationInfo        :
    MyCommand        : Move-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 28
    Line             : mv  -Path ./drakensang\drakensang -Destination ./
    PositionMessage  : At line:1 char:1
                       + mv  -Path ./drakensang\drakensang -Destination ./
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : mv
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.7
PSEdition                      Core
GitCommitId                    7.3.0-preview.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I could not reproduce
![Screenshot 2022-09-30 163956](https://user-images.githubusercontent.com/78153320/193282467-3939ce11-52cc-4027-a607-fcd9624fe9c7.png)

**Comment by solomoncyj** [comment]
> I could not reproduce
> 
> ![Screenshot 2022-09-30 163956](https://user-images.githubusercontent.com/78153320/193282467-3939ce11-52cc-4027-a607-fcd9624fe9c7.png)
@237dmitry 

try
mkdir ./hi/hi
cd hi/hi
"hi" | set-content test.txt
cd ../..
move-item  -Path .\hi\hi -Destination ./

**Comment by solomoncyj** [comment]
my output:
![image](https://user-images.githubusercontent.com/74647769/193290981-b7417c20-c12d-44e4-ac22-55398e763a93.png)

**Comment by solomoncyj** [comment]
what is your environment data?

**Comment by solomoncyj** [comment]
@237dmitry

**Comment by solomoncyj** [comment]
ah, ok so changes rollback? @237dmitry

**Comment by jhoneill** [comment]
> my output: ![image](https://user-images.githubusercontent.com/74647769/193290981-b7417c20-c12d-44e4-ac22-55398e763a93.png)

Don't know why @237dmitry  is getting something different but I get this and it is correct.   
**You are trying to move a folder named HI into a folder which already contains a folder of that name.**    
That is always going to cause an error, doesn't matter where you copy it from 

If you want to move the contents of the child up one level   `mv hi\hi\*   .\hi -Force`  and then `del hi\hi`

**Comment by iSazonov** [comment]
We should check HResult -2147024713 (800700B7) here:
https://github.com/PowerShell/PowerShell/blob/618d1a7c78f0702156d5ba1cd1be31df6d7f54d7/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L6120-L6122

**Comment by solomoncyj** [comment]
maybe a 
``` catch 
{
copy-item $path $destination
delete-item $destination -Force -r
}```
?

**Comment by solomoncyj** [comment]
any updates?

**Comment by Cronus89** [comment]
Just upgraded to 7.3.0 and seeing this same issue. Cannot use Move-Item because it says directory already exists.

**Comment by kilasuit** [comment]
@237dmitry please don't delete your comments in future as it makes it hard to read issues like this

**Comment by euamotubaina** [comment]
Some of my older scripts that relied on Move-Item to merge some directories stopped working after I updated to 7.3. I'm pretty sure they used to work fine until around 7.2.7 (I used them for the last time around Nov 22)
