### ISSUE TITLE
Set-Clipboard is missing -AsHtml

### ISSUE THREAD

**Issue by adamm1471** [PowerShell/PowerShell#18196]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Set-Clipboard is missing -AsHtml in PS 7+   

There is no known workaround or alternative for this incredibly useful feature.  

### Expected behavior

```console
"<table><tr><td>Test</td><td>Test</td></tr></table>" | Set-Clipboard -AsHtml 

Should produce a table for any rich-text enabled Office application (Word, Outlook, OneNote) and maybe other applications that understand this.
```

### Actual behavior
-AsHtml does not exist.  Piping into `|ConvertTo-Html` does not work
```console
Plain-text paste: <table><tr><td>Test</td><td>Test</td></tr></table>
```

### Error details

```console
Set-Clipboard: A parameter cannot be found that matches parameter name 'AsHtml'.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> Should produce a table for any rich-text enabled Office application (Word, Outlook, OneNote) and maybe other applications that understand this.

Windows Powershell (**5.1.22621.169**), Win 11 22H2
```powershell
"<table><tr><td>Test</td><td>Test</td></tr></table>" | Set-Clipboard -AsHtml
```
Clipboard is empty.

**Comment by dkaszews** [comment]
I'm confused, is this a bug or feature request? Also, is it Windows-specific or can it also be used on other systems?

**Comment by 237dmitry** [comment]
In my opinion, this switch is not necessary. Even in the example given, you can use ConvertTo-Html with parameters
```powershell
ConvertTo-Html -Body "<table><tr><td>Test</td><td>Test</td></tr></table>" `
               -Title 'MyTitle' `
               -Head '<style></style>' | Set-Clipboard
```

**Comment by adamm1471** [comment]
```
ConvertTo-Html -Body "<table border=1><tr><td>Test</td><td>Test</td></tr></table>" `
               -Title 'MyTitle' `
               -Head '<style></style>' | Set-Clipboard
```
when pasting into OneNote, MS Word, etc, produces the text

![image](https://user-images.githubusercontent.com/3342826/193431776-b9bd918a-2fc6-4182-9b4f-08544601e89d.png)

In Powershell 5, doing 
`"<table border=1><tr><td>Test</td><td>Test</td></tr></table>"  | Set-Clipboard -AsHtml`
and pasting into OneNote, MS Word, etc (Office suite) produces this:

![image](https://user-images.githubusercontent.com/3342826/193431756-843e0d9e-9987-4016-a875-5d46710a17d2.png)

**Comment by adamm1471** [comment]
> Clipboard is empty. The switch is there, but it does not work.

The clipboard is not empty because you can CTRL+V into any Office application and get the effect.  Using Get-Clipboard on the CLI is going to be empty for some reason after using Set-Clipboard with the `-AsHtml` flag, but it works.

**Comment by adamm1471** [comment]
> I'm confused, is this a bug or feature request? Also, is it Windows-specific or can it also be used on other systems?

I consider it a bug because Set-Clipboard/Get-Clipboard was taken out of Powershell 6, then added back in Powershell 7 but Set-Clipboard is missing the -AsHtml functionality (which is _not_ the same thing as ConvertTo-Html).

**Comment by 237dmitry** [comment]
> The clipboard is not empty because you can CTRL+V into any Office application and get the effect.

Thanks Captain O, I did not know about ^V.

**Comment by 237dmitry** [comment]
> CTRL+V into any Office application and get the effect

Tried to paste in wordpad. Then pasted in online Word. Now I understand what you meant. A strange feature for a console shell.

**Comment by dkaszews** [comment]
For tables, you can just use `ConvertTo-Csv -Delimiter "`t"`. It's what I always use and I fail to see how this request provides anything else.

**Comment by adamm1471** [comment]
> For tables, you can just use `ConvertTo-Csv -Delimiter "`t"`. It's what I always use and I fail to see how this request provides anything else.

` ConvertTo-Csv "<table border=1><tr><td>Test</td><td>Test</td></tr></table>" -Delimiter "t" | Set-Clipboard`

results in:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/3342826/193447583-f49a7709-1d28-4068-a317-7e023d25d1e0.png">

**Comment by adamm1471** [comment]
> > CTRL+V into any Office application and get the effect
> 
> Tried to paste in wordpad. Then pasted in online Word. Now I understand what you meant. A strange feature for a console shell.

Indeed, a strange feature... but immensely useful! Going forward (if Powershell 7 will supersede version 5 at some point in the future), it would be good to retain this functionality.

**Comment by mklement0** [comment]
@adamm1471, please see https://github.com/PowerShell/PowerShell/issues/14758#issuecomment-777925566 for the status quo; the short of it: as of v7.3.0-preview.8, the clipboard cmdlets in PS Core support _plain text only_, and there are no plans I'm aware of to change that.

**Comment by dkaszews** [comment]
Slight offtop: Does PowerShell support non-text clipboards, eg files? It may be a useful feature for pasting into browser, email, etc. if you want to quickly select bunch of files based on some criterion.

**Comment by mklement0** [comment]
@dkaszews, only Windows PowerShell does; the linked comment summarizes the non-plain-text parameters supported in Windows PowerShell that PS Core no longer supports. The question is if there's a willingness to bring non-plain-text support back, and to what degree it can be implemented in a platform-agnostic fashion - having platform-specific parameters is generally undesirable.

**Comment by dkaszews** [comment]
@mklement0 Agreed that Windows-only features should not be put in Core, but rather in a separate module, even if one would also be supported by Microsoft. For other platforms, there are two questions: whether it is _possible_ to implement a feature and whether it is _useful_ to implement a feature. For example, copying files into clipboard could be considered less useful on Linux with its less GUI-oriented culture.

**Comment by 237dmitry** [comment]
> Does PowerShell support non-text clipboards

Clipboard class of `System.Windows.Forms` seems could.

**Comment by mklement0** [comment]
@dkaszews, I guess the determination as to whether it's useful should be based on the capabilities of the native clipboard on a given platform; the absence of a _standard_ GUI shell on Linux makes this problematic, but the linked issue does discuss supporting copying file objects in the context of freedesktop.org-compliant GUI shells.

@237dmitry, the fact that Windows PowerShell offers such features in and of itself implies that Windows supports such features, and the linked issue shows attempts to use lower-level (.NET) APIs to regain the functionality that PS Core no longer provides (yet).

Historically, one of PowerShell's strengths has always been to _transcend_ mere _console_-based functionality; to be the glue among many disparate subsystems, including the GUI world. As much as possible, that strength should also extend to _all_ supported platforms.

**Comment by 237dmitry** [comment]
> PowerShell 7 on Windows should have parity with Windows PowerShell 5.

I don't understand why the PowerShell team won't just take the necessary code from Windows Powershell and use it? Or is Microsoft just a name, and the project has nothing to do with the corporation?

**Comment by jhoneill** [comment]
> > PowerShell 7 on Windows should have parity with Windows PowerShell 5.
> 
> I don't understand why the PowerShell team won't just take the necessary code from Windows Powershell and use it? Or is Microsoft just a name, and the project has nothing to do with the corporation?

There are two primary reasons (a) The code is something which cannot be open sourced, for whatever reason and (b) for some reason it was supported in .NET Framework but is not longer available in current .NET (and WHY? is a valid question there). Clipboard support went away in V6 for .NET related reasons, and came back in V7; I think in V7 it may be different code, or possibly just the subset of code which works cross platform . Sometimes teams in Microsoft do re-invent the wheel rather than using something from another group, but I don't think is what is happening here.

**Comment by SteveL-MSFT** [comment]
I believe the reasoning on why this no longer exists has been answered.  I would also encourage folks to publish a clipboard module to PSGallery whether it's Windows only or, preferably, cross-platform.  The built-in one as part of PS7 is intentionally limited to have it cross-platform.
