### ISSUE TITLE
[System.Environment]::OSVersion.Version.Revision returns 0

### ISSUE THREAD

**Issue by mmseng** [PowerShell/PowerShell#18208]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Notes
Sorry in advance. This may not be the right place to report this, as it may be an issue with .NET instead of PowerShell itself, but I'm not sure and am unfamiliar with how I would report it otherwise. Please kindly direct me to the right place if this is not it.

P.S. This happens on PowerShell 7 and PowerShell 5.1.

### Expected behavior
When I enter `[System.Environment]::OSVersion.Version.Revision` into a PowerShell prompt, I expect to get the OS's current revision number, equivalent to `Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' | Select -ExpandProperty "UBR"`.

For example:
```console
PS> Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' | Select -ExpandProperty "UBR"
2006
PS> [System.Environment]::OSVersion.Version.Revision
2006
```

### Observed behavior
`0` is returned.
```console
PS> Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' | Select -ExpandProperty "UBR"
2006
PS> [System.Environment]::OSVersion.Version.Revision
0
```

### Environment data
```console
PS> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19044.0 Microsoft Windows NT 10.0.19044.0
```

**Comment by StevenBucher98** [comment]
I suggest opening and issue with .NET at https://github.com/dotnet/core/issues. Hopefully they may be able to give some more insight into whats wrong :)

**Comment by mmseng** [comment]
Thanks.
