### ISSUE TITLE
Install-Package should offer client certificate authentication

### ISSUE THREAD

**Issue by tylermontneyacc** [PowerShell/PowerShell#18209]
### Summary of the new feature / enhancement

For instance, my private NuGet server requires a client certificate. I cannot specify this with `Install-Package`.

### Proposed technical implementation details (optional)

As far as I can tell, `Install-Package` calls `Invoke-WebRequest`. This cmdlet does support client certificate authentication, which should be a simple pass through.

**Comment by dkaszews** [comment]
Sounds like a simple change, I could look at it but I'm not that familiar with NuGet and don't know how to set up a server for testing. Can you please share an example (can be a partial clone of your private server with changed cert)?

**Comment by SteveL-MSFT** [comment]
This is a request for Packagemangement not PowerShell https://github.com/oneget/oneget (although it's deprecated)

**Comment by dkaszews** [comment]
@SteveL-MSFT Why? It's about a missing param in `Install-Module` cmdlet. It's the same if .NET had an important feature in `System.Net.Http` that was not exposed via `Invoke-WebRequest`. Here it's possible to download a module via `Invoke-RestMethod` and then installing it from local file, but it makes more sense to add a credential to `Install-Module` directly

**Comment by tylermontneyacc** [comment]
@SteveL-MSFT I'm not using OneGet.

@dkaszews I hadn't considered installing from file. As for the server, does this work https://github.com/tylermontneyacc/ExampleNuGetServer?

**Comment by jborean93** [comment]
The `Install-Module` cmdlet is part of the `PowerShellGet` module and is not part of this repository so asking here is the wrong place to ask. The tricky thing is that `PowerShellGet` is going through a transition at the moment, there are 2 different versions out there

* V2 - https://github.com/PowerShell/PowerShellGetv2
  * This is what gets shipped with Windows and PowerShell 7 currently
  * You use `Install-Module` to install modules and it interacts with `PackageManagement` and `nuget.exe`
  * This is essentially on life support in favour of V3
* V3 - https://github.com/powershell/powershellget
  * Currently a beta but if the future of installing modules in PowerShell
  * You use `Install-PSResource` to install modules
  * There is a shim you can use to get backwards compatibility and make `Install-Module` sit on top of the new command
  * No hard dependency on `nuget.exe` being present on your system and no need for `PackageManagement`

Unfortunately when looking at `Get-Help Register-PSResourceRepository -Full` I cannot find any parameter that relates to certificate auth which means the functionality is not there. If you wish for this I recommend you raise a request for it at https://github.com/powershell/powershellget so the right people can see it.

**Comment by dkaszews** [comment]
@jborean93 Thanks, I assumed it's part of this repo since it comes bundled with the release.

If PowerShell uses v2 and it is not marked as closed yet, and there is no timeline for switching to v3, I think opening an issue there makes most sense.

@tylermontneyacc Feel free to put a link to the promoted issue here as a comment, I will take a look whether I can try and help.

**Comment by jborean93** [comment]
You can put it on the v2 repo but I doubt you will get any traction, all work for PowerShellGet is focused on v3 and getting that out the door so it is better to try and implement it there.

**Comment by tylermontneyacc** [comment]
@jborean93 That makes more sense, just assumed it was part of the PS core.

@dkaszews I'll throw it in V3.
