### ISSUE TITLE
ConvertTo-Json behaviour with array with single element inconsistent when piping

### ISSUE THREAD

**Issue by johanredeploy** [PowerShell/PowerShell#18203]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

# Single element
```pwsh
PS> $arr = @(1)
PS> ConvertTo-Json -InputObject $arr -Compress # [1]
PS> $arr | ConvertTo-Json -Compress # 1
```

# Multiple elements
```pwsh
PS> $arr = @(1,2)
PS> ConvertTo-Json -InputObject $arr -Compress # [1,2]
PS> $arr | ConvertTo-Json -Compress # [1,2]
```

### Expected behavior
I expected the same behaviour from both of these lines when an array contains one item:
```pwsh
PS> $arr = @(1)
PS> ConvertTo-Json -InputObject $arr -Compress # [1]
PS> $arr | ConvertTo-Json -Compress # [1]
```

### Actual behavior
`ConvertTo-Json` with piped input converts a single element array to a string without array characters (`[]`).

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/94831699/193566778-b4b3500a-2cda-459c-a8ed-5ec2b72d1564.png)

**Comment by jhoneill** [comment]
This is a quirk of how the PowerShell pipeline works  

When you pipe an array to something, the array is enumerated and the members are sent
so 
`@(1 ) | command`   is the same as 
`1 | command`    
and 
`@(1,2,3) | command ` sends 3 ints not a 3-item array-object

`ConvertTo-Json -Compress -InputObject @(1)`  works differently, it _doesn't_ expand the array (and rightly so).   
This is an exception to the general rule  `$x | command` and `command | $x`  do the same thing

**Comment by 237dmitry** [comment]
> This is an exception to the general rule `$x | command` and `command | $x` do the same thing

?? Maybe `command $x` ?

**Comment by johanredeploy** [comment]
@jhoneill makes sense when you explain it.

So this is a workaround I guesS?
```pwsh
$arr = @(1)
,$arr | ConvertTo-Json -Compress # [1]
```

I will either way restort to using `InputObject` in the future because this confused me for a fair while.

**Comment by jhoneill** [comment]
That should work  - I haven't tested it. 

When ConvertTo-JSON receives multiple objects it makes them an array so  a multi-element array become and an array again, but it can't tell if a single item started life in array.  This does create some inconsistencies, and if what you're outputting is an array which might have zero, one or many elements, it's a pain.

**Comment by nosalan** [comment]
This is quite error-prone behavior of `ConvertTo-Json` for single element arrays, I wish it was fixed.

**Comment by constantinmuraru** [comment]
What about `ConvertFrom-Json` ?

```
echo $(ConvertFrom-Json -InputObject '["abc"]').GetType().Name
String

echo $(ConvertFrom-Json -InputObject '["abc", "def"]').GetType().Name
Object[]
```

What would be a workaround here, given that a param that matches name 'Compress' for `ConvertFrom-Json` cannot be found?
