### ISSUE TITLE
Help topics for Expand-Archive, CompressArchive report a non-public enum value in their .Category property

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18224]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

_Update_: I see the symptom on **macOS** and **Linux**, but not on Windows.

This is a small issue, but causes unexpected output with commands such as 
`(Get-Help *).Category  | Sort-Object -Unique`  (apparent duplicates are shown).

All help topics that ship with PowerShell _except_ `Compress-Archive` and `Expand-Archive` report a _string_ value in their `.Category` property, such as `'Function'`.

The permitted values are ultimately based on a _non-public_ `System.Enum`-derived class, `System.Management.Automation.HelpCategory`.
`Compress-Archive` and `Expand-Archive` unexpectedly return a value from this non-public enumeration directly, rather than its stringified form, which is problematic both with respect to the inconsistent behavior relative to all other topics and the surfacing of a non-public type's members.

```powershell
(Get-Help *-Archive).Category | % { $_.GetType().FullName }
```

### Expected behavior

```console
System.String
System.String
```

### Actual behavior

```console
System.Management.Automation.HelpCategory
System.Management.Automation.HelpCategory
```

### Environment data

```powershell
PowerShell Core 7.3.0-preview.8
```

**Comment by SteveL-MSFT** [comment]
I'm not able to repro this.  I see `System.String` return as expected.  Can you try `Update-Help` and see if it repros for you?

**Comment by mklement0** [comment]
@SteveL-MSFT, I ran `Update-Help`, but I still see the symptom on macOS and Linux, but it seemingly never affected Windows (where I hadn't previously tried); I've updated the initial post.

**Comment by iSazonov** [comment]
Looking proposed PR I don't understand why it is Unix only issue. 😕 What is a root of the issue?
