### ISSUE TITLE
Ctrl-C does not clear line

### ISSUE THREAD

**Issue by dkaszews** [PowerShell/PowerShell#18221]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Regression from 7.2.4 on Linux ARM64 (I also use the same 7.3.0-preview-8 on my work Windows machine and it does not have the same issue).

Start writing any input, then press Ctrl-C.

### Expected behavior

```console
Line gets cleared
```

### Actual behavior

```console
A literal `@` gets added to the line
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.8
PSEdition                      Core
GitCommitId                    7.3.0-preview.8
OS                             Linux 5.15.0-1015-raspi #17-Ubuntu SMP PREEMPT Mon Sep 12 13:14:51 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/26599495/194141626-f0a04a8d-f285-4752-ae1e-9c8ae3ae1508.png)

**Comment by dkaszews** [comment]
Slightly different reproduction with `-NoProfile` - nothing happens, the line is not cleared but also `@` is not added.

Reproduces in raw terminal, in NeoVim terminal buffer, inside tmux, etc. Also reproduces when ssh'ing from my phone, so it is likely not a terminal issue (additionally shown by 7.2.4 working fine on same connection).

**Comment by 237dmitry** [comment]
I use `ESC` to clear line or script block.

**Comment by dkaszews** [comment]
Did quick bisection, the breaking change is between preview.7 and preview.8:
```diff
+ 7.2.6
+ 7.3.0-preview.4
+ 7.3.0-preview.6
+ 7.3.0-preview.7
- 7.3.0-preview.8
```

**Comment by 237dmitry** [comment]
>  I use Set-PSReadLineOption -EditMode vi

Then `Ctrl-U`

**Comment by dkaszews** [comment]
`Ctrl-U` has exact same behavior: line not cleared, `@` added

**Comment by 237dmitry** [comment]
`Get-PSReadLineKeyHandler` show `Ctrrl-Home`

```
Ctrl+Home        BackwardDeleteInput Delete text from the cursor to the start of the input
```

**Comment by dkaszews** [comment]
@237dmitry That's not a solution, just workaround. `Ctrl+Home` does work, but on my Chromebook it requires pressing `Ctrl+Search+Left`, much less convenient than `Ctrl+C`. Plus it does not do the same if the cursor is not at the end.

**Comment by dkaszews** [comment]
Testing with `git bisect v7.3.0-preview.7 v7.3.0-preview.8`, it looks like #18106 is at fault:

```pwsh
578aef29af131a8779a3b70106ad32f531e202f4 is the first bad commit
commit 578aef29af131a8779a3b70106ad32f531e202f4
Author: Aditya Patwardhan <adityap@microsoft.com>
Date:   Thu Sep 15 16:55:16 2022 -0700

    [release/v7.3.0-rc.1] Update `DotnetRuntimeMetadata.json` for .NET 7 RC1 build (#18106)

 DotnetRuntimeMetadata.json                         |  8 +++---
 assets/wix/files.wxs                               | 30 +++++++++++-----------
 global.json                                        |  2 +-
 ...Microsoft.PowerShell.Commands.Management.csproj |  2 +-
 .../Microsoft.PowerShell.Commands.Utility.csproj   |  6 ++---
 .../Microsoft.PowerShell.CoreCLR.Eventing.csproj   |  2 +-
 .../Microsoft.PowerShell.SDK.csproj                | 20 +++++++--------
 .../Microsoft.WSMan.Management.csproj              |  2 +-
 .../System.Management.Automation.csproj            | 14 +++++-----
 .../BenchmarkDotNet.Extensions.csproj              |  4 +--
 .../ResultsComparer/ResultsComparer.csproj         |  2 +-
 test/tools/TestService/TestService.csproj          |  2 +-
 test/tools/WebListener/WebListener.csproj          |  4 +--
 13 files changed, 49 insertions(+), 49 deletions(-)
```

Using `7.3.0-preview.8` with #18106 reverted does in fact fix the issue.

**Comment by 237dmitry** [comment]
> Ctrl+Home does work

`Set-PSReadLineKeyHandler`

**Comment by fMichaleczek** [comment]
https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0-preview.8

![image](https://user-images.githubusercontent.com/6187529/194532225-2a6fc1d5-a122-432e-ae2b-60f59c24e1cd.png)

**Comment by dkaszews** [comment]
@fMichaleczek Thanks, I somehow missed it when downloading the package 🤦 . It checks out as the commit I found by bisection updates .NET. At least I had some fun refreshing how to use `git bisect`.
