### ISSUE TITLE
vs code : Configured debug type 'coreclr' is not supported.

### ISSUE THREAD

**Issue by cosmic-blunder** [PowerShell/PowerShell#18240]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- Install .net6
- open vs code
- attach breakpoint on any line
- click in run option
- After that click on start debugg

### Expected behavior

```console
Debug must hit the line .
```

### Actual behavior

```console
C#
v1.25.0
Microsoft
18,003,040
(403)
C# for Visual Studio Code (powered by OmniSharp).
Set Color Theme
Disable
Uninstall
This extension is enabled globally.

Details
Feature Contributions
Changelog
Runtime Status
Categories
DebuggersProgramming LanguagesLintersSnippets
Extension Resources
Marketplace
Repository
License
Microsoft
More Info
Released on
26/02/2016, 21:50:58
Last updated
24/05/2022, 22:52:25
Identifier
ms-dotnettools.csharp
PROBLEMS
OUTPUT
DEBUG CONSOLE
TERMINAL

-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c
```

### Error details

```console
C#
v1.25.0
Microsoft
18,003,040
(403)
C# for Visual Studio Code (powered by OmniSharp).
Set Color Theme
Disable
Uninstall
This extension is enabled globally.

Details
Feature Contributions
Changelog
Runtime Status
Categories
DebuggersProgramming LanguagesLintersSnippets
Extension Resources
Marketplace
Repository
License
Microsoft
More Info
Released on
26/02/2016, 21:50:58
Last updated
24/05/2022, 22:52:25
Identifier
ms-dotnettools.csharp
PROBLEMS
OUTPUT
DEBUG CONSOLE
TERMINAL

-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c
```

### Environment data

```powershell
vs code in linux
```

### Visuals

You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c

**Comment by SeeminglyScience** [comment]
Seems like you found the right repo to file this (OmniSharp/omnisharp-vscode#5402) so I'm gonna go ahead and close this.
