### ISSUE TITLE
Thread safe class method defined in Powershell hangs inside a Lazy inside a ConcurrentDictionary

### ISSUE THREAD

**Issue by User1785604260** [PowerShell/PowerShell#18248]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a thread safe class method (it's static and empty) that is hanging when called inside of a ```System.Lazy``` initializer inside of a ```System.Collections.Concurrent.ConcurrentDictionary``` when used with ```ForEach-Object -Parallel```. Calling a normal dotnet method works fine (e.g. ```[System.Convert]::ToString(132456, 2)```), but my ```[Dead]::Lock()``` method call hangs.

This is as far as I was able to strip my repro code down while still causing the hang:
````Powershell
#Requires -Version 7

Write-Host "Starting job`n"

$dict = [System.Collections.Concurrent.ConcurrentDictionary[string, System.Lazy[string]]]::new()

$job = 1..16 | ForEach-Object -AsJob -ThrottleLimit 16 -Parallel {
    $threadNum = $_
    $dict = $using:dict

    class Dead {
        # This method should be thread safe(?)
        static [void] Lock() {
        }
    }

    [System.Console]::WriteLine("Starting thread #$threadNum")

    $lazy = $dict.GetOrAdd("same key", [System.Lazy[string]]::new(
        {
            # Calling this method causes the script to hang, even though it should(?) be thread safe
            [Dead]::Lock()

            $okToCall = [System.Convert]::ToString(132456, 2)
            return ""
        },
        [System.Threading.LazyThreadSafetyMode]::ExecutionAndPublication))

    [void]$lazy.Value

    [System.Console]::WriteLine("Completed thread #$threadNum")
}
try {
    while (!$job.Finished.WaitOne(1000)) {
        Write-Host "$(Get-Date): Waiting"
    }
    $job | Receive-Job

    Write-Host "`nFinished job`n"
} finally {
    $job | Stop-Job
}
````

Note: you may need to run this a bunch of times to actually see the hang. I'm also running this without my profile to ensure that's not interfering: ```pwsh.exe -NoProfile -File $Home\OneDrive\Scripts\bug.ps1```

I've had independent verification of the hang from at least one other user: https://www.reddit.com/r/PowerShell/comments/y035sc/calling_a_thread_safe_powershell_class_method/irre9u4/

### Expected behavior

```console
PS C:\> pwsh.exe -NoProfile -File $Home\OneDrive\Scripts\bug.ps1
Starting job

Starting thread #1
Starting thread #2
Starting thread #3
Starting thread #4
Starting thread #5
Starting thread #6
Starting thread #7
Starting thread #8
Starting thread #9
Starting thread #10
Starting thread #11
Starting thread #12
Starting thread #13
Starting thread #14
Starting thread #15
Starting thread #16
Completed thread #2
Completed thread #6
Completed thread #9
Completed thread #13
Completed thread #3
Completed thread #1
Completed thread #4
Completed thread #5
Completed thread #7
Completed thread #8
Completed thread #10
Completed thread #11
Completed thread #12
Completed thread #14
Completed thread #15
Completed thread #16

Finished job

PS C:\>
```

### Actual behavior

```console
PS C:\> pwsh.exe -NoProfile -File $Home\OneDrive\Scripts\bug.ps1
Starting job

Starting thread #2
Starting thread #1
Starting thread #3
Starting thread #4
Starting thread #5
Starting thread #6
Starting thread #7
Starting thread #8
Starting thread #9
Starting thread #10
Starting thread #11
Starting thread #12
Starting thread #13
Starting thread #14
Starting thread #15
Starting thread #16
10/10/2022 11:52:52: Waiting
10/10/2022 11:52:53: Waiting
10/10/2022 11:52:54: Waiting
10/10/2022 11:52:55: Waiting
10/10/2022 11:52:56: Waiting
10/10/2022 11:52:57: Waiting
10/10/2022 11:52:58: Waiting
10/10/2022 11:52:59: Waiting
10/10/2022 11:53:00: Waiting
10/10/2022 11:53:01: Waiting
10/10/2022 11:53:02: Waiting
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Duplicate of #12801

**Comment by SeeminglyScience** [comment]
This is a known issue (and somewhat by design) for static methods. Very recently a PR was merged [adding a way to strip runspace affinity for a class](https://github.com/PowerShell/PowerShell/pull/18138). Once that makes it to a preview, that will be the recommended way of handling it.

In earlier versions you can move to instance methods and use the work around described in https://github.com/PowerShell/PowerShell/issues/3651#issuecomment-306968528

**Comment by User1785604260** [comment]
Thanks! I don't think I ever would have found that existing issue. :) Looks like I hit the bug just in time for the NoRunspaceAffinity fix too. In my real code I just worked around this for now by copying in the body of the method I'm interested in. I'll stick to that for now as it's a tiny method and the workaround you linked doesn't looks like it's worth it for my case.

I'll double check my real code is fixed by NoRunspaceAffinity once it's available.

**Comment by SeeminglyScience** [comment]
> Thanks! I don't think I ever would have found that existing issue. :)

Oh yeah, you're good, we just mark it for tracking purposes :) We would always much prefer duplicates over issues going unreported ❤️

Especially with issues as impossible to search for as this 😁

**Comment by User1785604260** [comment]
I'm not using this... but I did come up with an _incredibly_ cursed way to get "per-thread" versions of my ```Profile``` class without having to modify it at all. 🤣

My normal profile looks like this:
````Powershell
#Requires -Version 7

# https://github.com/PowerShell/PowerShell/issues/3641

using assembly "C:\Program Files\PowerShell\7\System.Windows.Forms.dll"

using module NativeMethods
using module Profile

# Cmdlet defaults
$PSDefaultParameterValues = @{
    # Better JSON defaults
    "ConvertFrom-Json:AsHashTable" = $true
    "ConvertTo-Json:Depth" = 100
}
````

The ```using module Profile``` brings in my ```Profile``` class and assorted cmdlets that I like to have.

Currently, I bring that in with a ```. $using:Profile``` inside of my ```ForEach-Object -Parallel```. But instead, I can import this abomination:
````Powershell
#Requires -Version 7

# https://github.com/PowerShell/PowerShell/issues/3641

using assembly "C:\Program Files\PowerShell\7\System.Windows.Forms.dll"

using module NativeMethods

# Cmdlet defaults
$PSDefaultParameterValues = @{
    # Better JSON defaults
    "ConvertFrom-Json:AsHashTable" = $true
    "ConvertTo-Json:Depth" = 100
}

$id = Get-Random -Max ([long]::MaxValue)
$profileScript = [System.IO.File]::ReadAllText("$Home\OneDrive\Scripts\Modules\Profile\Profile.psm1")
$profileScript = $profileScript.Replace("class Profile", "class Profile$id")
$profileScript = $profileScript.Replace("[Profile]", "[Profile$id]")
[System.IO.File]::WriteAllText("$env:Temp\Profile$id.psm1", $profileScript)

. iex "using module `"$env:Temp\Profile$id.psm1`""

return $id
````

And then use it like so:
````Powershell
$id = . "$Home\OneDrive\Scripts\Profile_Parallel.ps1"
$ProfileClass = [type]"Profile$id"
$ProfileClass::Assert.Invoke($true)
````

I'm not proud of this, but also kind of am. 😂

**Comment by User1785604260** [comment]
Do you happen to know if ```Start-ThreadJob``` would exhibit this issue? I can't seem to reproduce the issue when using that. Thread jobs actually match what I'm really trying to do better anyway, the only reason I'm not using them currently is because with ```For-EachObject -Parallel``` I have a single job that I can ```.Finished.WaitOne``` on. But that's just a convenience thing. :) If ```Start-ThreadJob``` won't ever do this then I'll just refactor to use that.

**Comment by daxian-dbw** [comment]
You can avoid the thread-safe issue with `Start-ThreadJob`. This is because `Start-ThreadJob` doesn't directly run a script block, but first convert the script block to a string, and then start a new Runspace to execute the string script, so the class will be redefined in the new Runspace, but it will be a different class per every Runspace created by `Start-ThreadJob` -- that may not be what you expect, and possibly the reason for the hang.

**Comment by User1785604260** [comment]
Oh, that's weird that it was still hanging for me, I'll have to take another crack at it in the morning. I wonder if it's because in my real code I'm not directly defining the class, but bringing it in via ". $using:Profile"?

Have a separate instance of the class is totally fine for my case, I'm just trying to call a static utility method.
````Powershell
static [string] GetFileHash([string]$Path) {
try {
    $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
    try {
        return [System.Convert]::ToHexString([System.Security.Cryptography.SHA256]::Create().ComputeHash($stream))
    } finally {
        $stream.Dispose()
    }
} catch { throw }
}
```

The only reason I'm not using ```Get-FileHash``` here is because the cmdlet overhead piles up and slows things down when you're looking at tens of thousands of files.

**Comment by daxian-dbw** [comment]
Oh, referencing via `$using` will get you the same race condition. It's again running the not-thread-safe method in multiple Runspace's.

**Comment by User1785604260** [comment]
Ahh, kk. Well it was worth a shot anyway. 😊 At least in this case the method I want to use is tiny and just pasting a copy in is perfectly fine.

I only have one script file left with ```. $using:Profile``` inside of a ```Start-ThreadJob```, but it's calling utility methods that would be way too large duplicate in place. I seem to be getting away with it there for now though, so I just left a comment and I'll revisit once that new NoRunspaceAffinity attribute is available.
