### ISSUE TITLE
Improving the colours that are suitable for programmers to work for longer durations.

### ISSUE THREAD

**Issue by siddd26** [PowerShell/PowerShell#18256]
### Summary of the new feature / enhancement

If a programmer is using Windows Powershell for any reason, he or she should not get strain in their eyes because of the colour themes used.

### Proposed technical implementation details (optional)

Changing the colour theme of Windows Powershell as to reduce eye strain.

**Comment by siddd26** [comment]
Using colours that are soothing for eyes and give happy signals to human brain will help programmers to work for longer hours

**Comment by 237dmitry** [comment]
> Using colours that are soothing for eyes

You can set look and feel (and partly behavior) of PowerShell with `$PSStyle`, `Set-PSReadlineOption`, `$profile` and cmdlets custom output formatting.

**Comment by SteveL-MSFT** [comment]
@siddd26 you specifically mention Windows PowerShell, but this repo is for PowerShell 7.  The terminal controls color themes and not usually the shell (outside of user customizations as noted above).
