### ISSUE TITLE
New-LocalUser errors with -NoPassword flag

### ISSUE THREAD

**Issue by ceilingfish** [PowerShell/PowerShell#18264]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I run the cmdlet `New-LocalUser` with the `-NoPassword` flag it throws an error rather than creating a user.

I tried adding the type using `Add-Type -TypeDefinition $TelemetrySource -Language CSharp` with various combinations of the source code that matches the referenced types, in an attempt to remediate, but it didn't help.

### Expected behavior

```console
New-LocalUser MyUser -NoPassword
$user = Get-LocalUser MyUser
Write-Host "My user = $($user.Name)"
```

### Actual behavior

```console
New-LocalUser MyUser -NoPassword
New-LocalUser: Could not load type 'Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI' from assembly 'System.Management.Automation, Version=7.2.6.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

### Error details

```console
New-LocalUser: Could not load type 'Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI' from assembly 'System.Management.Automation, Version=7.2.6.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
It looks like a regression in the `Microsoft.PowerShell.LocalAccounts` module that ships in Windows.
Some changes were pushed to this module which depends on the `TelemetryAPI` type from Windows PowerShell. This type doesn't exist in PowerShell Core, and hence the error.

We will contact the owner team of the the `Microsoft.PowerShell.LocalAccounts` module about this.

**Comment by iSazonov** [comment]
Fixed in community module https://www.powershellgallery.com/packages/LocalAccounts
