### ISSUE TITLE
Add-Type -AssemblyName (on Windows) is useless?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#1828]
Even on Windows, it doesn't appear search the GAC the way `WindowsPowerShell` does, but only the local directory, so it's basically the same as `-Path`, right?

Repro:

```
PS>Add-Type -AssemblyName System.Web

Add-Type : Cannot find path 'C:\Users\Joel\System.Web.dll' because it
does not exist.
At line:1 char:1
+ Add-Type -AssemblyName System.Web
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Joel\System.Web.dll:String) [Add-Type], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by vors** [comment]
Thank you, @Jaykul . @andschwa and @daxian-dbw elaborated difference between `-Path` and `-AssemblyName`, so I'm going to close the issue. Feel free to reopen if you want to continue discussion.
