### ISSUE TITLE
The term 'new-eventlog' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by spottedmahn** [PowerShell/PowerShell#18281]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

execute: `New-EventLog -LogName Application -Source "Blah Blah"`

### Expected behavior

```console
whatever the previous output was in 5.X
```

### Actual behavior

```console
>new-eventlog: The term 'new-eventlog' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Error details

```console
>
Exception             :
    Type        : System.Management.Automation.CommandNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The term 'new-eventlog' is not recognized as a name of a cmdlet, function, script file, or
executable program.
                      Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
            HResult : -2146233087
        TargetObject          : new-eventlog
        CategoryInfo          : ObjectNotFound: (new-eventlog:String) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CommandNotFoundException
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 1
            HistoryId        : 6
            Line             : new-eventlog -logname application -source "Blah Blah"
            PositionMessage  : At line:1 char:1
                               + new-eventlog -logname application -source "Blah Blah"
                               + ~~~~~~~~~~~~
            InvocationName   : new-eventlog
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    CommandName : new-eventlog
    TargetSite  :
        Name          : LookupCommandInfo
        DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation,
Version=7.2.6.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The term 'new-eventlog' is not recognized as a name of a cmdlet, function, script file, or
executable program.
                  Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext
context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions,
CommandTypes commandTypes, Exception& lastError)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[]
commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : new-eventlog
CategoryInfo          : ObjectNotFound: (new-eventlog:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 6
    Line             : new-eventlog -logname application -source "Blah Blah"
    PositionMessage  : At line:1 char:1
                       + new-eventlog -logname application -source "Blah Blah"
                       + ~~~~~~~~~~~~
    InvocationName   : new-eventlog
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
>Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Shouldn't that cmdlet work now in 7.x in Windows?

The RFC, [Importing Windows PowerShell modules in PowerShell Core](https://github.com/PowerShell/PowerShell-RFC/blob/master/Final/RFC0050-Importing-Windows-PowerShell-modules-in-PowerShell-Core.md), is `Final` which means "fully complete and implemented in PowerShell", right ([source](https://github.com/PowerShell/powershell-rfc/blob/master/RFC0000-RFC-Process.md#final))?

**Comment by spottedmahn** [comment]
oh, I'm guessing I have to install a [windows compat module](
https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2022-ps) for this?

how, do I find the module `New-EventLog` is in? 🤔

**Comment by 237dmitry** [comment]
In Windows PowerShell.
```powershell
PS > powershell -c Get-Command -Module Microsoft.PowerShell.Management New-*
```

**Comment by spottedmahn** [comment]
that worked!  BUT, did that work b/c I already installed the correct module? 🤔

and why run another instance of PowerShell? 🤔

can't I just execute: ` Get-Command -Module Microsoft.PowerShell.Management New-*`?

thanks @237dmitry!! 🤝

**Comment by mklement0** [comment]
`New-EventLog` is indeed only available in _Windows PowerShell_.

See the conceptual [about_Windows_PowerShell_Compatibility](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility) help topic.

For in-session use in PowerShell _Core_ (with cross-process serialization behind the scenes), you can make `New-EventLog` available, as follows, but note the limitations discussed in the linked help topic:

```powershell
Import-Module  Microsoft.PowerShell.Management -UseWindowsPowerShell -WarningAction Ignore

New-EventLog -?
```

Note:

* `-WarningAction Ignore` suppresses two warnings:
  * The _specific_ warning about which specific commands are _not_ imported (via proxies), due to conflicting with edition-native versions of those commands.
  * The _general_ warning about the limitations of providing the commands via cross-process serialization; note that this warning as of PowerShell Core 7.3.0-preview.8 contains misleading information:
    *  It mentions `-AllowClobber`, which isn't a supported parameter; the real parameter name, `-NoClobber`, has the _inverse_ logic and  is _implied_ when you use `-UseWindowsPowerShell`
    *  It mentions `-SkipEditionCheck`, which would _not_ be effective in this case (leaving aside the fact that it is described as a necessary step, even though (parts of) the module already _have_ been imported).

* While `3>$null` is _usually_ equivalent to  `-WarningAction Ignore`  /  `-WarningAction SilentlyContinue` , it fails to suppress the _specific_ warning in this case.
