### ISSUE TITLE
Select-String doesn't render VT (ANSI) escape sequences in its for-display output with input from external programs on Windows

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18294]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a regression from 7.2.6 and only happens:
* on Windows (_not_ on macOS; haven't tried on Linux)
* in regular console windows (`conhost.exe), _not_ in Windows Termional
* with input from _external programs_

```powershell
cmd /c echo foo | sls f
```

### Expected behavior

`foo` should print with `f` highlighted, to indicate what part of the line matched.

### Actual behavior

```console
←[7mf←[0moo
```

That is, the VT escape sequences are mistakenly rendered as verbatim characters.

### Environment data

```powershell
PowerShell Core 7.3.0-preview.8 on Windows 10 21H2, Windows 11 22H2
```

**Comment by SeeminglyScience** [comment]
Interestingly I can't repro this on Windows 11. Can anyone else on 10 try?

I would assume this has to do with console modes. @mklement0 can you see if:

```powershell
$results = cmd /c echo foo | sls f
$results
```

has the same effect?

**Comment by mklement0** [comment]
Strange, @SeeminglyScience: I do see it in Windows 11 too, albeit only in `conhost.exe` windows, not in Windows Terminal - I've updated the initial post to clarify.

Yes, `(cmd /c echo foo | sls f)` (the equivalent of your commands) makes the problem go away (the VT sequences then render as expected).

**Comment by SeeminglyScience** [comment]
> Strange, @SeeminglyScience: I do see it in Windows 11 too, albeit only in `conhost.exe` windows, not in Windows Terminal - I've updated the initial post to clarify.

That's very interesting, FWIW I did try both `conhost` and WT and couldn't repro in either

**Comment by mklement0** [comment]
Mysterious (to recap: 7.3.0-preview.8, `conhost.exe` window, `$PSStyle.OutputRendering` at its default, `'Host'`, W10 21H2 and W11 22H2). Perhaps others can report what they get.

**Comment by SeeminglyScience** [comment]
What's your build number for w11? I'm on 22621.674 (Oct 2022) (last bit only appears in `winver` it seems)

**Comment by mklement0** [comment]
`2261.232` (I wouldn't expect it to make a difference, but for the record it is an ARM build running in a VMWare Fusion VM on an M1 Mac; however, the Windows 10 VM runs on an Intel Mac).

**Comment by SteveL-MSFT** [comment]
I'm able to repro this.  However, I think it's a problem with conhost:

```powershell
$psstyle.outputrendering = 'ansi'
cmd /c echo foo | sls f
cmd /c echo foo | sls f > out.txt
cat out.txt
```

![image](https://user-images.githubusercontent.com/11859881/196228306-1c06c95d-b4b1-4552-9e88-569fbbc29bf4.png)

**Comment by mklement0** [comment]
@SteveL-MSFT, glad to hear that you see it too, but note that it probably _isn't_ `conhost.exe`, given that the same command works fine in v7.2.6 - or do you see the symptom there too?
