### ISSUE TITLE
Range operator doesn't create succinct range of characters

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#18309]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The range operator adds a redundant whitespace character between each character within range.

### Expected behavior

```console
PS> [string]$characters = 'a' .. 'd'
PS> $characters
abcd
PS>$characters[1]
b
PS>
```

### Actual behavior

```console
PS> [string]$characters = 'a' .. 'd'
PS> $characters
a b c d
PS>$characters[1]
 
PS>
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PowerShell](https://user-images.githubusercontent.com/9283914/196031957-c23c42d6-7429-4590-b952-a4abf2976c97.png)

**Comment by 237dmitry** [comment]
```powershell
-join ('a'..'d')

# or

$OFS = ''
[string] ('a'..'d')
```

**Comment by SetTrend** [comment]
I see … Yet, is this behaviour intentional particularly for the range operator?

The behaviour you describe is not documented ("see [about_Operators](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators#range-operator-).

**Comment by MartinGC94** [comment]
The range operator doesn't matter in this context, it simply creates an array of characters that you can then use to do whatever you want. PowerShell will do this with any array you try to convert to a string like: `[string]("Hello","World")`.  
If you want to create a string with the range operator you need to do it the same way you would with any other char array. One example could be like this: `[string]::new("a".."z")` another would be using the join operator like @237dmitry showed.

**Comment by SetTrend** [comment]
Yes, I comprehend.

Yet, shouldn't this be documented in the documentation for the [range operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators#range-operator-) for further reference?

The documentation doesn't explain what you just did. So, it's hard to grasp, without this explanation, what actually happens when the range operator is used (on string).

Don't expect users to use PowerShell every day and to know the nitty gritties.

I propose there should as lease be a warning note, referencing the $OFS preference variable.

**Comment by SetTrend** [comment]
I created a corresponding issue for the PowerShell documentation team:

https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9315

**Comment by MartinGC94** [comment]
I agree that the wording for range operator is a little weird. This:
> Represents the sequential integers in an integer array, given an upper, and lower boundary.

Should probably be replaced by something like this:
> The range operator creates an array of integers or chars of the values between the start and end values specified.

I disagree that it needs a warning for using it as a string. The documentation should tell you what a feature does and how to use a feature, it shouldn't explain all the different ways you can combine the feature with other features to create neat little scripts.

**Comment by MartinGC94** [comment]
They probably call it a "warning" internally because the purple information box acts like a warning that says "Hey, when you are using this API you need to be aware of this thing". Regardless if they use a warning box or not I don't think writing about the string conversion behavior makes sense here.  
If they were to include it here, should they include that in every help page for features that output arrays? Should they include information about other array conversion tips? It makes more sense to have a general array or type conversion topic so people that want to understand why this works: `"Hello","World"` can look it up in a relevant location rather than having it as a random note in an unrelated operator.

**Comment by SetTrend** [comment]
Good point!

Though, I guess a hyperlink to the `OFS` variable wouldn't hurt.

An operator seems closer to the intrinsics of PowerShell than a function – as is the `OFS` variable.
