### ISSUE TITLE
Add internal source generator for experimental features

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#18302]
### Summary of the new feature / enhancement

There's a lot of boiler plate in experimental features, it'd be nice to have a source generator which takes this code:

**NOTE**: Of course this would only benefit folks working on this repo specifically, but it would greatly simplify adding experimental features in the engine and leave less room for typos/missed files.

```csharp
public partial class ExperimentalFeature
{
                          // Probably default to this
    [Experiment(Targets = ExperimentTarget.Windows | ExperimentTarget.Linux)]
    private static readonly ExperimentalFeature PSDoSomething = new ExperimentalFeature(
        nameof(PSDoSomething),
        "The description for the feature");

    [Experiment(Targets = ExperimentTarget.Linux)]
    private static readonly ExperimentalFeature PSDoSomething2 = new ExperimentalFeature(
        nameof(PSDoSomething2),
        "The description for the feature");
}
```

and have it generate:

```csharp
public partial class ExperimentalFeature
{
    internal static bool IsPSDoSomethingEnabled => EnabledExperimentalFeatureNames.Contains(nameof(PSDoSomething));

    
    internal static bool IsPSDoSomething2Enabled => EnabledExperimentalFeatureNames.Contains(nameof(PSDoSomething2));

	// Replacing the manual bit currently in the static ctor
    private static ExperimentalFeature[] CreateFeatureList()
    	=> new[]
        {
            PSDoSomething,
            PSDoSomething2,
        };
}
```

and

```json
// experimental-feature-linux.json
[
    "PSDoSomething",
    "PSDoSomething2"
]
```

```json
// experimental-feature-windows.json
[
    "PSDoSomething",
]
```

**Comment by daxian-dbw** [comment]
https://github.com/PowerShell/PowerShell/pull/18484 was merged to break the dependency on those 2 .json files for private build and CIs. So now, we don't need to update those 2 .json files when authoring an experimental feature. All you need when creating a new Engine experimental feature is to:
1. Add to the list in the static constructor of `ExperimentalFeature`
2. Optionally create a new constant variable in the `Constant member` section at the top of `ExperimentalFeature` class to represent the feature name.

I will assign this back to @SeeminglyScience to see if he wants to take further actions.
