### ISSUE TITLE
```where``` doesn't work, returns empty result

### ISSUE THREAD

**Issue by pratyakshm** [PowerShell/PowerShell#18310]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We typically use `where` to find the path of a binary.
 If I use `where java`, it should output location of the binary, but it doesn't - it returns an empty result.

### Expected behavior

```console
PS> where java
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\Program Files\Microsoft\jdk-17.0.4.101-hotspot\bin\java.exe
```

### Actual behavior

```console
PS> where java
PS>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/54220235/196050799-84c3e616-f46b-484f-8139-c302b964c0cb.png)

**Comment by 237dmitry** [comment]
```
where.exe java
```

**Comment by SteveL-MSFT** [comment]
You can always use `where.exe java`, however, `get-command java` or `gcm java` is the equivalent in PowerShell.  As noted above, if you just want the path, you can use dot notation.
