### ISSUE TITLE
VSCode not breaking in source

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#1831]
This is probably more than a question than bug but figured I would ask. I'm not able to break in source.

Video in this ZIP: 

[vsCodePowerShell.zip](https://github.com/PowerShell/PowerShell/files/420739/vsCodePowerShell.zip)

Steps to reproduce
------------------
1. Start .NET Core Launch configuration

Expected behavior
-----------------
Should stop at the entry point or at a breakpoint I set. 

Actual behavior
---------------
Doesn't stop at entry point. If I set a breakpoint, it says that no symbols are loaded for the current document. 

Environment data
----------------

![image](https://cloud.githubusercontent.com/assets/1256531/17706611/5397d4c0-63a2-11e6-8722-6ac006781bee.png)

**Comment by ealexjordan** [comment]
@adamdriscoll Finding breakpoints and stoponentry failing on Windows ONLY. Filed the above issue with  the vscode group, because I'm stumped at this point. Hoping that they can point me either to a vscode bug or a mistake we made.

**Comment by adamdriscoll** [comment]
Thanks for the follow up, @ealexjordan! I'll wait for their reply.

**Comment by weinand** [comment]
VS Code does not have .NET support, so I have moved #10678 to https://github.com/OmniSharp/omnisharp-vscode/issues/690
