### ISSUE TITLE
Remove code specifically for PSv2

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#18323]
### Summary of the new feature / enhancement

There's a bunch of legacy code specifically for compat with PSv2 (a more exhaustive search should be done locally as GitHub doesn't find all matches): https://github.com/PowerShell/PowerShell/search?l=C%23&q=psv2

Since PS 2.0 was officially deprecated Aug 2017 (https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/starting-the-windows-powershell-2.0-engine?view=powershell-7.2), there's no need to keep this code around.

### Proposed technical implementation details (optional)

Review and remove all PSv2 specific code paths

**Comment by CarloToso** [comment]
It seems like there are 50 references to PSv2 in 8 files

PowerShell/PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/LanguagePrimitives.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/PSVersionInfo.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/parser/ast.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
PowerShell/PowerShell/src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs

**Comment by SteveL-MSFT** [comment]
We can probably do these as separate PRs to avoid reviewing a single large PR (not necessarily 1 PR per file, but whatever logically makes sense)

**Comment by xtqqczze** [comment]
Can we remove PSv1 and PSv2 from `$PSVersionTable.PSCompatibleVersions`?

https://github.com/PowerShell/PowerShell/blob/1d129c9a7d8e82c9e742c5d0e5deeba1d5fb95f5/src/System.Management.Automation/engine/PSVersionInfo.cs#L100

**Comment by iSazonov** [comment]
> Can we remove PSv1 and PSv2 from `$PSVersionTable.PSCompatibleVersions`?

I agree to remove.
We have already so many breaking changes that we could remove all up to 7.0 :-)

**Comment by xtqqczze** [comment]
> > Can we remove PSv1 and PSv2 from `$PSVersionTable.PSCompatibleVersions`?
> 
> I agree to remove. We have already so many breaking changes that we could remove all up to 7.0 :-)

PR submitted: #18346

**Comment by xtqqczze** [comment]
> We have already so many breaking changes that we could remove all up to 7.0 :-)

Windows Server 2012 has Windows Management Framework 3.0 in-box. Microsoft is supporting Windows Server 2012 under Extended Security Updates until October 13, 2026.

In consideration of remoting scenarios, etc., we could keep PSv3 code for now.

https://learn.microsoft.com/en-us/windows-server/get-started/extended-security-updates-overview#what-are-extended-security-updates
https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/overview#wmf-availability-across-windows-operating-systems

**Comment by xtqqczze** [comment]
PowerShell 3.0 is also the last version available to install for Windows Server 2008 R2 SP1, which apparently is supported on Azure until January 9, 2024!

**Comment by JamesWTruher** [comment]
The @PowerShell/wg-powershell-engine discussed this, but we're concerned about taking any action since PowerShell v2 is still a selectable option for Windows11(!).
![Window11PS2](https://user-images.githubusercontent.com/10214008/199111921-d4b80aed-2831-41a8-96ed-220ea1fdb25a.png)

We're also concerned about a whole-scale approach to this due to possible backwards compatibility issues. However, we are generally in favor of removing obsolete code in manageable chunks.

**Comment by xtqqczze** [comment]
@SteveL-MSFT Can you please reopen.
