### ISSUE TITLE
Set-Location \  behaviour inconsistent between operating systems

### ISSUE THREAD

**Issue by GigaScratch** [PowerShell/PowerShell#18325]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In #18308 we found that running `cd\` will do different things depending on the operating system. 

Steps:
1. Navigate to any directory above your drive's root level. >  `Set-Location Drive:/LizardPhotos/Skinks`
2. Run `Set-Location \` or `cd\`
3. You should now be at your drive's root on windows, or your filesystem root on Linux & Mac.

### Expected behavior

```console
Windows, Mac, and Linux set location as the root of the current drive on`cd\`
```

### Actual behavior

```console
Windows sets location to the root of the current drive.
Mac and Linux sets location to the filesystem root.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.9
PSEdition                      Core
GitCommitId                    7.3.0-preview.9
OS                             Microsoft Wind…
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0…
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/19718175/196591327-79448a02-1587-4a5d-a0cf-cbd6b73e77df.png)
![image](https://user-images.githubusercontent.com/19718175/196592137-b7cd63c4-1250-407b-b70b-a244bfc6ebd7.png)
![image](https://user-images.githubusercontent.com/19718175/196592079-eccd14c6-5199-43ef-8d3d-f20c022c1478.png)

**Comment by GigaScratch** [comment]
@iSazonov New Issue created.

**Comment by iSazonov** [comment]
By default Unix haven't a drive and it is ok `cd\` to move to a root of current volume. But what if user uses a drive on Unix? Should we follow Windows behavior and move to a root of current drive?
```powershell
cd Temp:\
New-Item test -ItemType Directory
cd test
cd\
```

_I'd prefer consistency on all platforms._Otherwise, why do we need the drives if the cmdlets ignore them?

**Comment by 237dmitry** [comment]
> Windows, Mac, and Linux set location as the root of the current drive on`cd\`

On Linux partitions mounted to the root:
```
 $ lsblk        
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda      8:0    0 111.8G  0 disk 
└─sda1   8:1    0 111.8G  0 part /
sdb      8:16   0 465.8G  0 disk 
└─sdb2   8:18   0 465.8G  0 part /data
``` 

if you on Windows mount (or create junction) partition to the folder (not by letter) the result will be the same.

![Screenshot 2022-10-19 144817](https://user-images.githubusercontent.com/78153320/196682893-a9a3e1da-f359-44d3-9088-9b87d31da788.png)

**Comment by iSazonov** [comment]
@237dmitry The issue is about _drives_.

**Comment by 237dmitry** [comment]
> The issue is about drives.

OK, I misunderstood the difference between "drives" and "PSDrives"

**Comment by iSazonov** [comment]
To be correct no difference between psdrive and fs drive should be in PowerShell behavior.

**Comment by mklement0** [comment]
While consistency across platforms is generally desirable, I fear that's not an option here:

On Unix, if you make `/` refer to the root of a drive (which on Unix is by definition only ever a PS drive), you won't be able to change to the actual file-system root whenever the current location is drive-based.

Pragmatically speaking:

* _Interactively_, typing, say, `Set-Location Temp:/` isn't too much of a hardship.
* _Programmatically_, you can use the following (which would obviously be too cumbersome interactively):
   * `Set-Location ($PWD.Path -replace '(?<=[\\/]).*')`

**Comment by jhoneill** [comment]
> _Programmatically_, you can use the following to switch to the root of the _current drive_, on all platforms (which would obviously be too cumbersome interactively):
> * `Set-Location ($PWD.Path -replace '(?<=[\\/]).*')`

Since some of us already redefine CD to be something other than an alias for set location, that could be incorporated into a CD function.

/  is defined as a PS Drive on linux to ensure that cd / does in PowerShell what it does in other unix/linux shells 
What happens in all shells on the same OS is consistent rather than making pwsh on linux "windows like" and annoying linux oriented folks.

**Comment by JamesWTruher** [comment]
The WG has reviewed this and believe this to be ByDesign. There are fundamental differences between a singly rooted filesystem and a drive based filesystem that should not be consistent as we feel that would cause more confusion rather than reduce it.
