### ISSUE TITLE
Ubuntu software center does not show License information for PowerShell package

### ISSUE THREAD

**Issue by raghushantha** [PowerShell/PowerShell#1832]
![capture](https://cloud.githubusercontent.com/assets/11727200/17708383/9409a76c-6399-11e6-9c1b-8e7247a46b77.JPG)

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by andschwa** [comment]
As this is a packaging aesthetic and not a requirement, moving assignment to @raghushantha.

**Comment by JamesWTruher** [comment]
the use of the --deb-meta-file doesn't put the copyright file in the correct place, and putting a copyright file in the right place still doesn't get the information to show up correctly. We should be the copyright file in the right place, but getting it to show up in the app doesn't really need to be done for release.
