### ISSUE TITLE
Strange: `Start-Process CMD -Credential $c` Windows Focus+Input problem/hangs

### ISSUE THREAD

**Issue by gerardog** [PowerShell/PowerShell#18333]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This may be a windows problem. But I need your help to figure it out and can't reproduce on Windows Powershell

Just run: 
```
$c = Get-credential
Start-Process cmd -Credential $c
```
or one liner `Start-Process cmd -Credential $get-credential``
(I am using credentials of a local user from my machine. Not domain-joined.)

### Expected behavior

```console
A new window opens, I can write several lines in the new window, running as another user.
```

### Actual behavior

```console
A new window opens, I can write one line and press enter. Then the input on that window HANGS. Keypresses are not handled anymore.

If I switch focus back to the parent window, the input missing input is processed. If you keep playing, the input on the parent caller window may hang its processing too.
```

### Error details

```console
n/a
```

### Environment data

```powershell
-> Windows 11 Pro 21H2 22000.1098
-> Fails using Pwsh 7.2.6, unable to reproduce on Windows Powershell
-> Can reproduce with both legacy ConHost.exe or Windows Terminal Preview (1.16.2642.0)
-> Also happens on a second computer.

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/3901474/196816752-1bd7a2ba-ee48-49d4-9740-5f7df94bd327.png)

The second line, marked by the arrow, does not appear until you switch focus back and forth between both windows.

**Comment by gerardog** [comment]
Also, if I run `start-process cmd -Credential $c -LoadUserProfile` (with or without -LoadUserProfile)
And then run `pwsh` on that window (running as $c), it shows the following error:

```
C:\>pwsh
PowerShell 7.2.6
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

The specified drive root "C:\Users\gerar\AppData\Local\Temp\" either does not exist, or it is not a folder.
PS C:\>
```
Please note we are running as another user, not gerar. 
I suspect -LoadUserProfile is not working.

![image](https://user-images.githubusercontent.com/3901474/196827465-dc8d49f5-04db-48b2-99c5-1681f3aefd1e.png)

**Comment by mklement0** [comment]
See also:
*  #12129

**Comment by gerardog** [comment]
Lol, mklement0, you are two year ahead of the rest of us. /dupe

**Comment by jamie-sandbox** [comment]
## Workaround

https://github.com/PowerShell/PSReadLine/issues/288#issuecomment-1837606501
