### ISSUE TITLE
Remove `-DotnetFrameworkVersion` and `-ClrVersion` from `New-ModuleManifest`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#18330]
### Summary of the new feature / enhancement

Per https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9328 these members in the module manifest are no longer valid and keeping it can cause confusion on why it's not doing what the author thinks it should be doing.

**Comment by iSazonov** [comment]
What about ProcessorArchitecture?

**Comment by Jaykul** [comment]
> What about ProcessorArchitecture?
> 
> [#18320 (comment)](https://github.com/PowerShell/PowerShell/pull/18320#issuecomment-1281786821)

Surely there are PowerShell modules that don't/only work on ARM?

I would say that these parameters should be marked obsolete (via documentation) and hidden if possible from tab completion, but not removed (since they don't break things, and removing them _might_ break things). The cmdlet could even output a warning that these fields don't work in modern PowerShell.

Additionally, I think it would be great if we could _not_ put the commented out text for these in the psd1 (when there's no value passed in to the parameter).

**Comment by iSazonov** [comment]
Search results on Windows Server 2019 with RSAT:
```
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\BestPractices\BestPractices.psd1:33:CLRVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DFSR\DFSR.psd1:38:CLRVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1:34:    ClrVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PersistentMemory\PersistentMemory.psd1:31:CLRVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSScheduledJob\PSScheduledJob.psd1:17:CLRVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\RemoteDesktop\RemoteDesktop.psd1:41:CLRVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\ScheduledTasks\ScheduledTasks.psd1:9:    ClrVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\ServerManager\ServerManager.psd1:9:CLRVersion = '4.0'
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Whea\Whea.psd1:36:CLRVersion = '4.0'


C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DFSR\DFSR.psd1:35:DotNetFrameworkVersion = '4.0'


C:\Windows\System32\WindowsPowerShell\v1.0\Modules\AppvClient\AppvClient.psd1:18:ProcessorArchitecture = 'AMD64'
```

I also tried to find at least one module with ProcessorArchitecture with a non-empty value on GitHub, but I couldn't.

**Comment by iSazonov** [comment]
The only place to keep these things for backward compatibility is in the PSD file parser. Elsewhere they can be freely removed.

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets  reviewed this and agreed that these members don't serve value and at worst will be misleading to users.  Our proposal is to not make a breaking change by removing them now, but make them no-op and emit a warning when used.

**Comment by iSazonov** [comment]
> reviewed this and agreed that these members

What is "these"? Please clarify.
