### ISSUE TITLE
Microsoft Store Update 

### ISSUE THREAD

**Issue by Daviid-P** [PowerShell/PowerShell#18345]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I installed Powershell through the Microsoft Store and when I start Powershell I get an update notification.

![image](https://user-images.githubusercontent.com/7734808/197207608-a496dc22-b561-4e4c-9fec-50ad04037550.png)

However the Microsoft Store app is not up to date so I can't update.

### Expected behavior

```console
Since I installed the app through Microsoft Store don't prompt for update if the Microsoft Store's version is not actually updated.

Otherwise, provide a guide on how to update manually, I can see that pwsh.exe is installed, in my case, at `C:\Users\David\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe` however the `PowerShell-7.2.7-win-x86.zip` I downlaoded from the releases page contains many more files.

Do I actually need them all or just copying pwsh.exe will suffice?
```

### Actual behavior

```console
Prompting to update with a link to `https://github.com/PowerShell/PowerShell/releases/tag/v7.2.7`
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by egbakou** [comment]
Hi @Daviid-P ,
Check again !
I was able to update via the store.
![image](https://user-images.githubusercontent.com/26142591/197289379-4a9c8424-d73d-4a0b-b9e3-fa8f65df5436.png)
![image](https://user-images.githubusercontent.com/26142591/197289572-aca82fc4-4511-47d1-90c5-e2ab064613cd.png)

**Comment by Daviid-P** [comment]
Indeed, looks like it's been updated.

Thanks for the notice @egbakou

**Comment by egbakou** [comment]
You're welcome @Daviid-P
