### ISSUE TITLE
Why is there a non-lts release of some packages?

### ISSUE THREAD

**Issue by perjahn** [PowerShell/PowerShell#18344]
### Checklist

Could you explain why there's a non-lts release of some packages, what's the exact content difference between the lts and non-lts release packages? And why should anyone select the non-lts release? Does any difference only affect installations done using a package source (packages.microsoft.com), or also when downloading and installing a package manually as well?

**Comment by SeeminglyScience** [comment]
> Could you explain why there's a non-lts release of some packages, what's the exact content difference between the lts and non-lts release packages?

It's not exactly a package difference, but a version difference. Certain versions are marked as LTS meaning they stay in support for longer. The reason we have LTS and non-LTS releases is mostly to mirror .NET as our support cycle has to match. Generally speaking, the reason you have them is to allow faster iteration while still having an option for folks who want to stay on the same version for as long as possible.

> And why should anyone select the non-lts release? Does any difference only affect installations done using a package source (packages.microsoft.com), or also when downloading and installing a package manually as well?

Generally you want LTS for deployment across an enterprise, unless you explicitly need a feature from a non-LTS release. For workstations where you would be writing the script it's nice to be on the latest version including non-LTS, but not required unless you need a feature that is not yet in a LTS release. Installation source doesn't matter, it's the version itself that is marked LTS or non-LTS.
