### ISSUE TITLE
Error while installing the powershell in ubuntu 20.04

### ISSUE THREAD

**Issue by imskanand** [PowerShell/PowerShell#18350]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Not able to install in ubuntu 20.04

### Expected behavior

```console
Installation
```

### Actual behavior

```console
Fatel error
```

### Error details

```console
Unpacking powershell-lts (7.2.7-1.deb) ...
dpkg: error processing archive /home/imskanand/Downloads/powershell-lts_7.2.7-1.deb_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/pwsh', which is also in package powershell 7.2.3-1.deb
Errors were encountered while processing:
 /home/imskanand/Downloads/powershell-lts_7.2.7-1.deb_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Environment data

```powershell
NOTHING Available
```

**Comment by 237dmitry** [comment]
I don't use any package managers and everything works fine. Just unpack to `/opt/microsoft/powershell/7/`  and symlink pwsh to the `$PATH`, in `/usr/bin` for example. Forget about `dpgg` or `apt`

**Comment by StevenBucher98** [comment]
You can also try installing via the snap store, `sudo snap install powershell --classic`

**Comment by rhubarb-geek-nz** [comment]
The problem is trying to replace "powershell" with "powershell-lts". Both apt and dpkg will see them as two different packages as they have different package names.
```
trying to overwrite '/usr/bin/pwsh', which is also in package powershell 7.2.3-1.deb
```
Solution is to remove "powershell" 7.2.3 first or upgrade with "powershell" 7.2.7 instead of "powershell-lts" 7.2.7

**Comment by rhubarb-geek-nz** [comment]
> I don't use any package managers and everything works fine. Just unpack to `/opt/microsoft/powershell/7/` and symlink pwsh to the `$PATH`, in `/usr/bin` for example. Forget about `dpgg` or `apt`

I would recommend using packages. 

- They ensure the package dependencies are installed. 
- They let you see exactly what is installed on your system in one place.
- When you upgrade the obsolete files are removed.
