### ISSUE TITLE
Get-DhcpServerInDC Returns a DNS Alias as an authorized DHCP server

### ISSUE THREAD

**Issue by KevinWGagel** [PowerShell/PowerShell#18365]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a CNAME DNS entry that points to an authorized DHCP server.
2. Run Get-DhcpServerInDC.

### Expected behavior

```console
Expected behavior is for Get-DhcpServerInDC to return only authorized DHCP server listed in the "CN=NetServices,CN=Services,CN=Configuration,DC=DOMAIN" configuration of Active Directory.
```

### Actual behavior

```console
Get-DhcpServerInDC is returning objects that include a DNS alias for one of the authorized DHCP servers.
```

### Error details

```console
This causes errors when the objects are piped as the DNS Alias typically is not an Active Directory Computer Object and therefor generates errors in the pipeline.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

This is the results of Get-DhcpServerInDC (with a select to limit results to the server entries in question)
![Returns](https://user-images.githubusercontent.com/100967931/197600002-cf70e417-f928-4d71-a4a4-0d60a5ca0756.png)
Note that the top entry is the Alias from DNS. The bottom entry is the actual server.

This is shows that only the actual server is listed in Active Directory
![ADSI Edit Results](https://user-images.githubusercontent.com/100967931/197602043-abdfaf60-93ef-4913-8674-949cda83579b.png)

This shows partial results of "netsh dhcp show server". Only the entry in question is returned in the results - not the alias.
![Results of netsch](https://user-images.githubusercontent.com/100967931/197601155-c1ab1637-9b59-4a1e-bbf3-0e4c5a649a2a.png)

Attempting to use "Remove-DhcpServerInDC" for the erroneous entry results in this error.
![Remove Error](https://user-images.githubusercontent.com/100967931/197601770-aadcda67-3856-4908-bc55-ac066a683bc0.png)

**Comment by jhoneill** [comment]
This needs to be reported to the Windows team responsible for the module, not to the "PowerShell language" folks.

**Comment by KevinWGagel** [comment]
Where do I report this to the Windows team? I thought this is where such bugs got reported.
