### ISSUE TITLE
Native error handling: `$PSNativeCommandUseErrorActionPreference = $true` unexpectedly causes non-terminating, not statement-terminating errors

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18368]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The pre-v7.3 experimental `PSNativeCommandErrorActionPreference` feature allows setting the new `$PSNativeCommandUseErrorActionPreference` preference variable to `$true`, so that any call to an external (native) program that results in a nonzero exit code emits a PowerShell error (in addition to any preceding stderr output emitted by the external program itself).

For this error to be most useful, it should be a _statement-terminating_ error - i.e. one that can be caught with `try` / `catch`, whereas it currently is a _non-terminating_ error.

Note that the concept of a _non-terminating_ error is a PowerShell-specific one, and doesn't really apply to external programs.

```powershell
$PSNativeCommandUseErrorActionPreference = $true

try {
  # Call an external program that reports a nonzero exit code.
  & ($IsWindows ? 'cmd' : 'sh') ($IsWindows ? '/c' : '-c') 'exit 1'
}
catch {
  'caught!'
}
'after'
```

### Expected behavior

```console
caught!
after
```

### Actual behavior

```console
NativeCommandExitException: Program "sh" ended with non-zero exit code: 1.
after
```

That is, the unexpectedly _non_-terminating error wasn't caught.

### Environment data

```powershell
PowerShell Core 7.3.0-preview.8
```

**Comment by SteveL-MSFT** [comment]
@mklement0 the feature is as described in the variable name to use `$ErrorActionPreference` which is `continue` by default.  If you set `$ErrorActionPreference` to `Stop` then you can `try..catch` it.

**Comment by mklement0** [comment]
@SteveL-MSFT, what you're describing is incidental to the issue I'm raising here, given that `$ErrorActionPreference` acts on _both_ non-terminating and statement-terminating errors.

The problem is twofold:

* _Conceptually_, there is no such thing as a non-terminating error with respect to native programs.

* _Practically_, by making the error _non-terminating_, you take away the ability for easy _ad hoc_ error handling _irrespective of the value of `$ErrorActionPreference`_,  as shown in the initial post.
  * With `$ErrorActionPreference` at its default, `Continue`, you then have to either _also_ set it to `Stop` to work to get the  `try` statement to work, or you'll have to use an awkward dance of using `2>$null` to silence the PowerShell error (too), followed by `if ($LASTEXITCODE -eq 0) { ... }`
