### ISSUE TITLE
After installing and uninstalling windows cant run taskscheduler powershell.exe

### ISSUE THREAD

**Issue by NolanNolan** [PowerShell/PowerShell#18360]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi
after installing and uninstalling version 7.2.7 then creating a scheduled task in windows 11 the task dont run. It works on my stationary PC where this powershell app was never installed, but not on my laptop after uninstalling. Any solution ?

i assume its some leftover or registry taht was not properly reset

thanks

Nolan

### Expected behavior

```console
expected that an uninstall would revert windows setting back to standard powershell.exe
```

### Actual behavior

```console
cant run scheduled task anymore with action powershell.exe
```

### Environment data

```powershell
??
```

**Comment by jborean93** [comment]
PowerShell 7 should have no bearing in Windows PowerShell (powershell.exe). They are separate installs and don’t really touch any others settings. If you are having troubles starting powershell.exe from a scheduled task just try running the same action through cmd and see what problems may appear for debugging. Unfortunately without more information there’s not much we can do to help.

**Comment by NolanNolan** [comment]
Hi

ok thanks, thats weird though there is this differene between 2 PCs

best Nolan
