### ISSUE TITLE
Redirect stdout from loaded assembly console.writeline

### ISSUE THREAD

**Issue by itaymigdal** [PowerShell/PowerShell#18364]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Doubt if it's a bug, limitation or a lack of enough knowledge:
I'm loading arbitrary .NET assemblies (which I have no control of their source code) and invoke them.
A lot of them are using `console.writeline` (or similar functions), and I want to capture it, means redirecting it to a Powershell variable or even to a file, but nothing seems to catch this - it's just printing it to the console.
Tried about million ways to overcome this unsuccessfully (> file.txt , out-string, out-variable, and so on...)
here is the code:

```
$file = "path\to\my\compiled\assembly"
$bytes = [System.IO.File]::ReadAllBytes($file)
$assembly = [Reflection.Assembly]::Load($bytes)
$params = @(,[String[]]@("some params"))
$assembly.EntryPoint.invoke($null, $params)  # <-- I want to catch this output, into a variable or a file, but it keeps be printed to the screen.
```

### Expected behavior

```console
PS> $x = $assembly.EntryPoint.invoke($null, $params) | out-string
PS> $x
output
```

### Actual behavior

```console
PS> $x = $assembly.EntryPoint.invoke($null, $params) | out-string
PS> $x
nothing
```

### Environment data

```powershell
Name                           Value                                                                                                                                                                                           
----                           -----                                                                                                                                                                                           
PSVersion                      5.1.19041.1682                                                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                         
BuildVersion                   10.0.19041.1682                                                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                                                             
SerializationVersion           1.1.0.1
```

**Comment by SeeminglyScience** [comment]
You could do that in child PowerShell process, and redirect that, but that's about it. There's no way to generically redirect things written directly to stdout.

**Comment by MartinGC94** [comment]
You can also set the console output to a stream like this:

```
$Writer = [System.IO.StreamWriter]::new("$HOME\DemoLog.txt")
$Writer.AutoFlush = $true
$OriginalOut = [System.Console]::Out
try
{
    [System.Console]::SetOut($Writer)
    [System.Console]::WriteLine("Hello")
}
finally
{
    [System.Console]::SetOut($OriginalOut)
}
```

**Comment by SeeminglyScience** [comment]
Ah thanks for the correction! I think what I ran into when I tried that before was something using the the win32 console APIs directly. Definitely give that a go and see if it works for you @itaymigdal

**Comment by itaymigdal** [comment]
I have no control over the assemblies source code (so cannot use console.setout, and already played with the native console API.
Anyway, thanks for the help guys.

**Comment by MartinGC94** [comment]
You don't need access to the source code to set the console output. You set it in PowerShell and then you call the method in your class library and then you change the output target back to the original value from PowerShell. I've confirmed it works with a simple class library I built so either your library is doing something weird or you made a mistake when you tested this.

**Comment by itaymigdal** [comment]
@MartinGC94 
Just to note, I'm executing exe assemblies, not dll's.
Can you show me an example of how to do that?

**Comment by itaymigdal** [comment]
@MartinGC94 
Just to note I execute exe assemblies and not dlls.
I'll try your example and update, thanks.

**Comment by itaymigdal** [comment]
@MartinGC94
Seems like it's working, great catch! 
Thank you so much :)
