### ISSUE TITLE
REGEX_DEFAULT_MATCH_TIMEOUT behaves differently in console app vs. class library called via PowerShell

### ISSUE THREAD

**Issue by alexbuckgit** [PowerShell/PowerShell#18379]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using the sample code provided at [Regex.MatchTimeout Property - Remarks](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.matchtimeout?view=net-6.0#remarks) to set REGEX_DEFAULT_MATCH_TIMEOUT in a console app results in the expected behavior. But when using the same code in a class library and invoking it from PowerShell 7.2.7, REGEX_DEFAULT_MATCH_TIMEOUT is set properly but the value is ignored by Regex operations.

Why is this happening?

### Expected behavior

```console
PS> .\ConsoleApp.exe

Default regex match timeout: 00:00:02
Regular expression pattern: [aeiouy]
Timeout interval for this regex: 2 seconds
```

### Actual behavior

```console
PS> Import-Module .\ClassLibrary.dll; [ClassLibrary.Timeout]::SetRegexTimeout()

Default regex match timeout: 00:00:02
Regular expression pattern: [aeiouy]
Timeout interval for this regex: -0.001 seconds
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dwtaber** [comment]
I haven't found a more official source directly addressing this point, but [this blog post](https://kendaleiv.com/setting-regex-timeout-globally-using-dotnet-6_0-with-csharp/) seems to explain it:
>[setting the global default timeout] needs to happen as early as possible (first statement in Main would work), prior to any usage of `Regex` that causes this value to be read and cached. Once it’s cached it cannot be changed without restarting the application.

More specifically, it looks like once the default timeout value is set, you can still set new values via `domain.SetData` and read those values with `domain.GetData` without throwing errors, but new `Regex` objects won't actually use the new values.  Here's a console app I tested with:

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        AppDomain domain = AppDomain.CurrentDomain;

        Console.WriteLine("Creating object regexBefore");
        Regex regexBefore = new Regex("foo");
        Console.WriteLine($"regexBefore timeout: {regexBefore.MatchTimeout}\n");

        Console.WriteLine("Setting to 1 seconds.");
        domain.SetData("REGEX_DEFAULT_MATCH_TIMEOUT", TimeSpan.FromSeconds(1));
        Console.WriteLine($"GetData Result: {domain.GetData("REGEX_DEFAULT_MATCH_TIMEOUT")}\n");

        Console.WriteLine("Creating object regexAfter");
        Regex regexAfter = new Regex("foo");
        Console.WriteLine($"regexAfter timeout: {regexAfter.MatchTimeout}\n");

        Console.WriteLine("Setting to 2 seconds.");
        domain.SetData("REGEX_DEFAULT_MATCH_TIMEOUT", TimeSpan.FromSeconds(2));
        Console.WriteLine($"GetData Result: {domain.GetData("REGEX_DEFAULT_MATCH_TIMEOUT")}\n");
    }
}

// Output:
// Creating object regexBefore.
// regexBefore timeout: -00:00:00.0010000
// 
// Setting to 1 seconds.
// GetData Result: 00:00:01
// 
// Creating object regexAfter
// regexAfter timeout: -00:00:00.0010000
// 
// Setting to 2 seconds.
// GetData Result: 00:00:02
```

So I think what's probably happening is that some private/internal usage of `Regex` causes `REGEX_DEFAULT_MATCH_TIMEOUT` to be cached before your class library has a chance to set it to something else.
