### ISSUE TITLE
Out-Printer cmdlet prints ANSI escape sequences

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [PowerShell/PowerShell#18375]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Out-Printer` outputs ANSI control characters even if operating system does not support them and even if you disable it by modifying `$PSStyle` variable: `$PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText`

To reproduce, execute following commands:

```powershell
# Print using the default printer
$PSVersionTable | Format-Table -Property * | Out-Printer

# or print to a XPS document (if you don't have a printer)
$PSVersionTable | Format-Table -Property * | Out-Printer -Name 'Microsoft XPS Document Writer'
```

### Expected behavior

```console
Name                      Key                       Value
----                      ---                       -----
PSVersion                 PSVersion                 7.2.7
PSEdition                 PSEdition                 Core
GitCommitId               GitCommitId               7.2.7
OS                        OS                        Microsoft Windows 6.3.9600
Platform                  Platform                  Win32NT
```

### Actual behavior

```console
[32;1mName                      Key                       Value[0m
[32;1m----                      ---                       -----[0m
PSVersion                 PSVersion                 7.2.7
PSEdition                 PSEdition                 Core
GitCommitId               GitCommitId               7.2.7
OS                        OS                        Microsoft Windows 6.3.9600
Platform                  Platform                  Win32NT
```

### Error details

```console
# There is no error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I can reproduce this issue on Windows 10 and Windows 8.1

### Visuals

![image](https://user-images.githubusercontent.com/732366/197805838-21c4d453-59eb-4fd8-9b07-493104716206.png)

**Comment by jhoneill** [comment]
@daxian-dbw  - I think you were looking at all the places where ANSI sequences need to be removed, this is one of the less obvious ones and I'm guessing it was overlooked ?

**Comment by StevenBucher98** [comment]
I was able to reproduce this bug on Windows 11 too, expected but yeah.

**Comment by daxian-dbw** [comment]
I did overlooked `Out-Printer`. Will look into this.
