### ISSUE TITLE
`Measure-Command` reports incorrect results

### ISSUE THREAD

**Issue by RussKie** [PowerShell/PowerShell#18371]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a little .NET app (targeting .NET 6/7), and I want to measure how long it takes to launch it. The app automatically closes itself upon launch and reports the elapsed time. The time reported by `Measure-Command` cmdlet and inconsistent with the time reported by the app.

When I ran the cmdlet I get these results from the cmdlet:
```ps
PS throwaway\winforms-nativeaot> Measure-Command { .\bin\Release\net6.0-windows\winforms-nativeaot.exe }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 88
Ticks             : 881686
TotalDays         : 1.02046990740741E-06
TotalHours        : 2.44912777777778E-05
TotalMinutes      : 0.00146947666666667
TotalSeconds      : 0.0881686
TotalMilliseconds : 88.1686
```

DebugViewer report the data from the app:
```
[28008] winforms_nativeaot: time taken: 146.5512 ms || 1465512 ticks // 146 ms 
```

When I ran a comparable command from bash, I get these results:
```
$ time ./bin/Release/net6.0-windows/winforms-nativeaot.exe

real    0m0.266s
user    0m0.000s
sys     0m0.000s
```

And I also tried the good ol' cmd:
```
D:\Development\throwaway\winforms-nativeaot>cmd /v:on /c "echo !TIME! & .\bin\Release\net6.0-windows\winforms-nativeaot.exe & echo !TIME!"         
14:33:16.35 
14:33:16.59
```

App | PowerShell 5.1 | PowerShell 7.2 | Bash | Cmd
--|--|--|--|--
146 ms | 34.337 | 88.1686 | 266 | 240

It's clear that PowerShell reports grossly incorrect results as it can't take less time than the actual app. Bash reports the correct time as there's some overhead to launch the app before it gets to the `Main` entrypoint.

To verify, I have also run this, and results are surprising to say the least:
```ps
 Measure-Command { timeout 3 }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 322
Ticks             : 23221427
TotalDays         : 2.68766516203704E-05
TotalHours        : 0.000645039638888889
TotalMinutes      : 0.0387023783333333
TotalSeconds      : 2.3221427
TotalMilliseconds : 2322.1427
```

<details>
<summary>.NET app code</summary>

```cs
using System.Diagnostics;

namespace winforms_nativeaot;

static class Program
{
    [STAThread]
    static void Main()
    {
        Stopwatch stopwatch = Stopwatch.StartNew();

        // To customize application configuration such as set high DPI settings or default font,
        // see https://aka.ms/applicationconfiguration.
        ApplicationConfiguration.Initialize();

        Application.ApplicationExit += (s, e) =>
        {
            stopwatch.Stop();
            Trace.WriteLine($"winforms_nativeaot: time taken: {stopwatch.Elapsed.TotalMilliseconds} ms || {stopwatch.ElapsedTicks} ticks // {stopwatch.ElapsedMilliseconds} ms");
        };

        Application.Run(new Form1());
    }    
}

public partial class Form1 : Form
{
    public Form1()
    {
        this.Activated += (_, __) => Application.Exit();
    }
}
```

</details>

### Expected behavior

```console
The reported time is correct, at least within the same order of magnitude.
```

### Actual behavior

```console
The reported time is grossly inaccurate.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

----

Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
What does say the `Get-History`?   `(h)[-1].Duration`

**Comment by jhoneill** [comment]
` Measure-Command {notepad.exe} `  Will start notepad, and return to the PowerShell prompt. The time reported is the time to return from launching notepad, - the command doesn't wait for notepad to terminate  
to do that you need to use 
` Measure-Command {start -wait notepad.exe} `

**Comment by RussKie** [comment]
Thank you @jhoneill, but this still doesn't appear to provide a comparable result

* PS 7.2
```
> Measure-Command { start -wait .\bin\Release\net6.0-windows\winforms-nativeaot.exe }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 62
Ticks             : 10621881
TotalDays         : 1.229384375E-05
TotalHours        : 0.00029505225
TotalMinutes      : 0.017703135
TotalSeconds      : 1.0621881
TotalMilliseconds : 1062.1881
```

* PS 5.1
```
>  Measure-Command { start -wait .\bin\Release\net6.0-windows\winforms-nativeaot.exe }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 25
Ticks             : 10252342
TotalDays         : 1.18661365740741E-05
TotalHours        : 0.000284787277777778
TotalMinutes      : 0.0170872366666667
TotalSeconds      : 1.0252342
TotalMilliseconds : 1025.2342
```

* cmd
```
>cmd /v:on /c "echo !TIME! & .\bin\Release\net6.0-windows\winforms-nativeaot.exe & echo !TIME!"
13:48:08.82
13:48:09.03
```

* bash
```
$ time ./bin/Release/net6.0-windows/winforms-nativeaot.exe

real    0m0.241s
user    0m0.000s
sys     0m0.000s
```

For the these run the app's diagnostics reported between 129ms and 150ms.

**Comment by RussKie** [comment]
> What does say the `Get-History`? `(h)[-1].Duration`

This doesn't appear to produce any result.
```
PS D:\Development\throwaway\winforms-nativeaot> (Get-History)[0]

  Id CommandLine
  -- -----------
   1  Measure-Command { .\bin\Release\net7.0-windows\win-x64\winforms-nativeaot.exe }


PS D:\Development\throwaway\winforms-nativeaot> (Get-History)[0].Duration
PS D:\Development\throwaway\winforms-nativeaot>
```

**Comment by jhoneill** [comment]
`(h)[-1].Duration`

Works alone   (h is an alias for get history)

The time in cmd will be the time to return to the prompt - again try it with notepad - you'll get a time before the app has closed.  It's likely there is some overhead starting the process and I suspect start process polls to see if the process ID is still running so it won't give super accurate times. 

```
$p = new-object System.Diagnostics.Process
# Start info has other properties which to get process exactly as desired.  
$p.StartInfo.FileName = "C:\Windows\System32\notepad.exe" 
$p.start()
$p.WaitForExit()
$p.ExitTime - $p.StartTime

```
Should be more accurate.

**Comment by levicki** [comment]
@jhoneill 

> `Measure-Command {notepad.exe}` Will start notepad, and return to the PowerShell prompt. The time reported is the time to return from launching notepad, - the command doesn't wait for notepad to terminate
> to do that you need to use
> `Measure-Command {start -wait notepad.exe}`

I don't think this is fully accurate at least for console executables &mdash; if it didn't wait it would show 0 seconds (or some number of milliseconds very close to 0 like it does for your `notepad.exe` example). What happens for console executables is this:

```
PowerShell 7.6.1
PS C:\WORK\Projects\C#\DLTest\DLTest\bin\x64\Release> Measure-Command { .\dltest.exe }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 6
Milliseconds      : 734
Ticks             : 67345101
TotalDays         : 7.794571875E-05
TotalHours        : 0.00187069725
TotalMinutes      : 0.112241835
TotalSeconds      : 6.7345101
TotalMilliseconds : 6734.5101
```
Actual execution time:
```
C:\WORK\Projects\C#\DLTest\DLTest\bin\x64\Release>timethis DLTest.exe

timethis 1.0 (C) 2009 by Igor Levicki. All Rights Reserved.

*** TIMETHIS START ***

Starting download of 914.39 MB file, last modified on 2026-05-08T16:23:33
Downloading at 54.32 MB/s, 100% done...
Download completed successfully.

*** TIMETHIS END ***

Clocks : 53239949172
    ms : 17330
```
So what `powershell` outputs is totally invented number. Might as well rename `Measure-Command` to `Get-RandomTime`.

**Comment by phuclv90** [comment]
> So what `powershell` outputs is totally invented number. Might as well rename `Measure-Command` to `Get-RandomTime`.

The documentation already clearly states that the shell won't wait for the GUI apps to end

> If you run a 32-bit graphical user interface (GUI) application, cmd doesn't wait for the application to quit before returning to the command prompt
>
> https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start

> On Windows, the most common use case for Start-Process is to use the Wait parameter to block progress until the new process exits. On non-Windows system, this is rarely needed since the default behavior for command-line applications is equivalent to Start-Process -Wait.
>
> https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.5

The CreateProcess Win32 API also doesn't wait. For non-console apps it still need time to run so the returned value can't be 0. Read documentations and use it correctly before blaming

**Comment by levicki** [comment]
@phuclv90 

> The documentation already clearly states that the shell won't wait for the GUI apps to end

First, I wasn't talking about GUI apps at all &mdash; I was pointing out that their "`Measure-Command` doesn't wait" claim **does not seem to apply to console apps**. Console apps return neither 0 (doesn't wait) nor the correct time (full execution time). I even gave an example.

Second, [Measure-Command documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/measure-command?view=powershell-7.6) **doesn't say a thing about whether it does or doesn't wait**.

Third, unlike me, most people who use it in `powershell` aren't Windows developers since 1997.

> The CreateProcess Win32 API also doesn't wait.

It doesn't, and that's why when you are trying to time execution you do:
```
WaitForSingleObject(hProcess, INFINITE);
```
After creating it, and if you want time to not include process creation overhead you create your process suspended and then resume it right after starting your timer.

> Read documentations and use it correctly before blaming

I think you should refrain from commenting on stuff you don't understand.
