### ISSUE TITLE
Enable Gitter

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#1839]
Enable Gitter for communications

**Comment by kilasuit** [comment]
@TravisEz13 - So it seems that we are still going with Gitter #1869

**Comment by alexandair** [comment]
Why another chat platform, if PowerShell community already picked Slack?

**Comment by TravisEz13** [comment]
We plan to add Slack as well...

**Comment by lzybkr** [comment]
Some of us will hang out on slack here:
https://powershell.slack.com/archives/ps-contributors

There's also:
https://powershell.slack.com/archives/linux
