### ISSUE TITLE
Can I archive old versions of WMF for CI/CD purposes?

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/PowerShell#18406]
### Summary of the new feature / enhancement

I understand that Microsoft no longer supports older versions of PowerShell.

Many of my modules try to accommodate older versions of PowerShell and while I no longer use v3 or v4 in prod, I would like to continue testing these versions and need a reliable source for WMF.

Considering that Microsoft provides various ways to redistribute Windows Updates including WSUS, SCCM, local repositories and even DVDs, I would like to create my own repository and add the older versions of WMF to a GitHub repo. This will ensure I have continued access to the files when performing tests and I will ensure that it is known that these are no longer officially supported by Microsoft.

I believe the licensing allows for this but wanted to ask permission from the team.

Thanks,
Chrissy

**Comment by SteveL-MSFT** [comment]
Let me look into this

**Comment by SteveL-MSFT** [comment]
@potatoqualitee just FYI, I haven't forgotten about this, I just haven't gotten a response yet

**Comment by potatoqualitee** [comment]
Thank you, @SteveL-MSFT  🙇🏼

**Comment by SteveL-MSFT** [comment]
@potatoqualitee sorry it took so long, but it took a bit to explain to legal what WMF is and why you are looking to redistribute.  Long story short, WMF is considered a hotfix of Windows for downlevel platforms and thus WMF falls under Windows EULA.  So I can't answer your question directly, but you need to go to https://www.microsoft.com/en-us/useterms/ for guidance.

**Comment by potatoqualitee** [comment]
Thank you steve!
