### ISSUE TITLE
Get-Counter shows "performance counter path is not valid"

### ISSUE THREAD

**Issue by ilikesearch** [PowerShell/PowerShell#18404]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'd like to view the private working set of Task Manager.

At first do not start Task Manager.

Start powershell and type

`Get-Counter "\Process(taskmgr)\Working Set - Private"`

Press Enter, powershell shows

`Get-Counter: The \Process(taskmgr)\Working Set - Private performance counter path is not valid.`

This is ok because Task Manager is not running.

Then press `ctrl+alt+delete` and start Task Manager, and type again

`Get-Counter "\Process(taskmgr)\Working Set - Private"`

Press Enter, powershell shows

`Get-Counter: The \Process(taskmgr)\Working Set - Private performance counter path is not valid.`

Looks like powershell thinks Task Manager is not started.

P.S. If I start Task Manager first and then start powershell, there's no such issue.

### Expected behavior

```console
The private working set of Task Manager.
```

### Actual behavior

```console
Get-Counter: The \Process(taskmgr)\Working Set performance counter path is not valid.
```

### Error details

```console
Exception             :
    Type    : System.Exception
    Message : The \Process(taskmgr)\Working Set performance counter path is not valid.
    HResult : -2146233088
CategoryInfo          : InvalidResult: (:) [Get-Counter], Exception
FullyQualifiedErrorId : CounterPathIsInvalid,Microsoft.PowerShell.Commands.GetCounterCommand
InvocationInfo        :
    MyCommand        : Get-Counter
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : Get-Counter "\Process(taskmgr)\Working Set"
    PositionMessage  : At line:1 char:1
                       + Get-Counter "\Process(taskmgr)\Working Set"
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-Counter
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
If Taskmgr.exe is running then there is no errors.

![000](https://user-images.githubusercontent.com/78153320/198534767-9bdf1157-70ff-4e6d-ae71-485bb6d9c0a4.png)

**Comment by SteveL-MSFT** [comment]
This is by-design.  That perfcounter only exists if that process is running.  You can see the same in Perfmon.
