### ISSUE TITLE
winget upgrade powershell fails

### ISSUE THREAD

**Issue by pleabargain** [PowerShell/PowerShell#18426]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

cannot upgrade via winget

### Expected behavior

```console
winget upgrade powershell should work
```

### Actual behavior

```console
fail
```

### Error details

```console
fail
```

### Environment data

```powershell
windows 10
```

### Visuals

![image](https://user-images.githubusercontent.com/640846/199176215-550b5c02-4ea9-40ce-a807-75a61d917a74.png)

[wingetfail.zip](https://github.com/PowerShell/PowerShell/files/9907574/wingetfail.zip)

**Comment by pleabargain** [comment]
I updated manually but powershell doesn't seem to see that it was updated!
Note: I'm using 727 and winget is trying to upgrade to 727!
![image](https://user-images.githubusercontent.com/640846/199219200-1f2f1aba-2677-4fc3-a359-c38f72db808a.png)

**Comment by anamnavi** [comment]
@pleabargain did you manually install because when you tried to run `winget upgrade powershell` it said "you must manually uninstall powershell and reinstall with winget because the installation technology has changed"?

**Comment by pleabargain** [comment]
@anamnavi Yes. That is exactly why.

**Comment by anamnavi** [comment]
@pleabargain can you try uninstalling and installing with winget and see if this still happens? It should be resolved via the fix put in.

**Comment by pleabargain** [comment]
Working for me now. Thanks.
