### ISSUE TITLE
WindowStyle Hidden broke after update to PowerShell v7.2.7

### ISSUE THREAD

**Issue by bkoelman** [PowerShell/PowerShell#18423]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

The next shortcut on my desktop used to start the specified script without opening a console window. After updating to PowerShell v7.2.7, the console window always appears and remains visible.

"C:\Program Files\PowerShell\7\pwsh.exe" -WindowStyle Hidden "c:\path\to\script.ps1"

### Expected behavior

```console
Console window is hidden.
```

### Actual behavior

```console
Console window appears and remains visible.
```

### Environment data

```PowerShell
OS: Windows 11 Pro 22H2, build 22621.675
```

### Version

PowerShell v7.2.7

**Comment by bkoelman** [comment]
Apologies about the wrong repo, I didn't realize that.

After the update, I noticed the UI changed as well:

![image](https://user-images.githubusercontent.com/10324372/199186075-d9be3fee-23e3-41f0-baf6-1f5fe8a69d87.png)

It looks like it's now using Windows Terminal, which may be related to the observed behavior.

**Comment by StevenBucher98** [comment]
@bkoelman what is your Terminal setting set to under Settings>Privacy and Security> For developers
![image](https://user-images.githubusercontent.com/20605456/200397127-c75c8d3a-2bad-4188-b6e0-82005e8d08d6.png)
If it's terminal can you try setting it to console host and see if bug still happens?

**Comment by bkoelman** [comment]
Wow, that's a well-hidden setting! I've been searching for something like that. It was set to "Let Windows decide". After changing to "Windows Console Host", the problem went away.

Thanks for your help. Do you have any idea what caused this change? I'm asking because on my work laptop I also upgraded PowerShell, but did not observe the switch to using Windows Terminal there.

**Comment by StevenBucher98** [comment]
Hard to say exactly what may have caused it 🤷 very likely was not PowerShell and possibly some Windows update that made that change. Glad to hear problem went away!
