### ISSUE TITLE
parameter for x64 or x86 for download installer

### ISSUE THREAD

**Issue by janne-tech** [PowerShell/PowerShell#18420]
### Summary of the new feature / enhancement

parameter for x64 or x86 for download installer

### Proposed technical implementation details (optional)

parameter for x64 or x86 for download installer

**Comment by 237dmitry** [comment]
> parameter for x64 or x86 for download installer

Parameter where?
You can download any version using github api. For the latest releases (now 7.3.0-rc.1 and 7.2.7):
```powershell
$json = (iwr 'https://api.github.com/repos/PowerShell/PowerShell/releases').Content | ConvertFrom-Json
$json[0,1].assets | ? name -match 'win-x' | % browser_download_url
```

**Comment by SteveL-MSFT** [comment]
@janne-tech are you referring to the `install-powershell.ps1` script in this repo?  That script was really originally intended for use in CI when PS7 wasn't there.

**Comment by janne-tech** [comment]
yes, im referring to install-powershell.ps1
