### ISSUE TITLE
Switch-Process (exec) fails to make the replacement process inherit the calling process' environment variables

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18432]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

It is understood that the newly introduced, Unix-only `Switch-Process` cmdlet (alias `exec`) is _not_ designed to have full feature parity with the `exec` built-in in POSIX-compatible shells, notably not with respect to supporting stream redirections.

However, making the replacement process inherit the caller's environment is an important part of `exec` functionality (and it is how it works in POSIX-compatible shells).

Related discussion predating `Switch-Process`:
* #12750

```powershell
# Run on macOS or Linux.
# Note the use of `exec`; if you remove it, 'bar' prints as expected
pwsh -nop -c '$env:FOO=''bar''; exec /bin/sh -c ''echo $FOO'''
```

### Expected behavior

```console
bar
```

### Actual behavior

(no output)

### Environment data

```powershell
PowerShell Core 7.3.0-rc.1 on Unix-like platforms
```

**Comment by SteveL-MSFT** [comment]
Based on what I could find, `execv()` is supposed to automatically propagate the current env to the new process.  However, may need to switch to `execve()` to copy the env.
