### ISSUE TITLE
`Select-String` should have a `-AsPSObject` switch returning named groups as properties of an object

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#18434]
### Summary of the new feature / enhancement

Currently, if you run something like:

```console
PS /Users/steve/repos/PowerShell> ls -l *.md | select-string "(?<mode>.*?)\s+(?<hardlinks>[0-9]+)\s+(?<owner>\w+)\s+(?<group>\w+)\s+(?<size>[0-9]+)\s+(?<date>\w+\s[0-9]+\s[0-9:]+)\s+(?<filename>.+)"

-rw-r--r--  1 steve  staff   5122 Oct 24 08:37 ADOPTERS.md
-rw-r--r--  1 steve  staff  20383 Oct 27 09:33 README.md
```

`select-string` just highlights the matches (imagine the text above highlighted).  However, it would be useful to have a `-AsPSObject` switch so that if there are named groups, those becomes properties of an object instance:

```console
PS /Users/steve/repos/PowerShell> ls -l *.md | select-string "(?<mode>.*?)\s+(?<hardlinks>[0-9]+)\s+(?<owner>\w+)\s+(?<group>\w+)\s+(?<size>[0-9]+)\s+(?<date>\w+\s[0-9]+\s[0-9:]+)\s+(?<filename>.+)"

mode       hardlinks owner group size  date         filename
----       --------- ----- ----- ----  ----         --------
-rw-r--r-- 1         steve staff 20383 Oct 27 09:33 README.md
-rw-r--r-- 1         steve staff 20383 Oct 27 09:33 ADOPTERS.md
```

**Comment by jhoneill** [comment]
I like this idea. Someone is bound to ask "does this belong in `select-string` ?" and I think the answer is "yes, it does" :-)

**Comment by SteveL-MSFT** [comment]
Didn't realize how many parameter sets this cmdlet has.  That'll be the hardest part of adding this feature...

**Comment by iSazonov** [comment]
> Didn't realize how many parameter sets this cmdlet has. That'll be the hardest part of adding this feature...

In time we did last change in the cmdlet a conclusion was it better to have new cmdlet or cmdlets because of complicity of the cmdlet :-)
