### ISSUE TITLE
Disable-WindowsOptionalFeature has no counterpart to Enable-WindowsOptionalFeature

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#18431]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Installed version is `PowerShell-7.3.0-rc.1-win-x64.msi`.

Enable the feature using PowerShell 7. You will notice it works:
```
PS C:\Windows> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
Do you want to restart the computer to complete this operation now?
[Y] Yes  [N] No  [?] Help (default is "Y"):
```
Now try to disable it from same PowerShell, you will notice it does not work with either option:
```
PS C:\Windows> Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
Disable-WindowsOptionalFeature: A parameter cannot be found that matches parameter name 'All'.
PS C:\Windows> Disable-WindowsOptionalFeature -Offline -FeatureName Microsoft-Hyper-V -All
Disable-WindowsOptionalFeature: A parameter cannot be found that matches parameter name 'Offline'.
```

### Expected behavior

```console
`Disable-WindowsOptionalFeature` should undo all the changes made by `Enable-WindowsOptionalFeature` or at least the `Offline` feature should instead.
```

### Actual behavior

```console
The Microsoft official website does not explain or link on how to undo the change, apparently it's only one-way:
[url=https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/]Hyper-V on Windows 10[/url]
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This cmdlet is not part of PowerShell 7.  Per their docs the switches you are trying to use don't exist: https://learn.microsoft.com/en-us/powershell/module/dism/disable-windowsoptionalfeature?view=windowsserver2022-ps

**Comment by superbonaci** [comment]
That's the problem, that doesn't exist.

**Comment by jhoneill** [comment]
> That's the problem, that doesn't exist.

@superbonaci  - the module which contains these commands is owned by Windows, not by the PowerShell 7 language. 

I can't test on the machine I'm posting from,  but my memory ( from doing this a lot, but  quite some time ago) is that removing the parent feature removed all the children so there is no need for `-all` . If I'm mis-remembering and the child features _do_ need their own calls to `disable-`  then the inconsistency should be fixed, but it can't be fixed **here**

**Comment by superbonaci** [comment]
whatever
