### ISSUE TITLE
Switch-Process, when used to replace the PowerShell process with an interactive (different) shell session, breaks that session

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18433]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Clearly not a common use case, but a bug nonetheless:

When you use `Switch-Process` (`exec`) to replace the current PowerShell process (running an interactive session) with a different shell's interactive session (e.g., `bash`), that session's command-line editing is broken.

```powershell
# Run on macOS or Linux
Switch-Process /bin/bash
```

### Expected behavior

A regular interactive Bash session.

### Actual behavior

What the user types on the Bash command line doesn't print (however, submitting commands and printing output works normally).

### Environment data

```powershell
PowerShell Core 7.3.0-rc.1 on macOS 12.6 or Linux
```

**Comment by 237dmitry** [comment]
> is meant to replace the current process rather than create a child process. 

I understand. But it is unclear why this is necessary? You can simply run another shell right in the current session, in a different buffer, so as not to lose information in the main buffer.
```
"`e[?1049h"; Clear-Host; bash; "`e[?1049l"
```

**Comment by mklement0** [comment]
As stated in the initial post, this use of `exec` is uncommon - you'd only do this if you wanted to discard the PowerShell session in favor of a different shell's interactive session, _without needing to return to it_. 

That said, (a) it should still work and (b), not knowing what the underlying problem is, more common `exec` scenarios could be affected too (say the replacement process prompts for user input).

**Comment by 237dmitry** [comment]
>  you'd only do this if you wanted to discard the PowerShell session in favor of a different shell's interactive session, without needing to return to it.

Ok.

**Comment by SteveL-MSFT** [comment]
Using `switch-process` with zsh works as expected, but bash seems to not set the echo mode (tested on MacOS).  Workaround is to use `stty echo` within bash.  Based on what I could find, we may have to use `termios` to re-enable echo before `exec` call.

**Comment by SteveL-MSFT** [comment]
So, I don't think calling `termios` may be sufficient as `stty` already has echo on within pwsh and that doesn't resolve bash issue.

**Comment by mklement0** [comment]
Not sure how relevant it is in the real world, but `ksh` is also affected (as is `dash`, but no one uses that as an interactive shell); by contrast, `fish`, like  `zsh` is _not_ affected.

**Comment by daxian-dbw** [comment]
Instead of PowerShell, It could be what .NET does, or more specifically, what `[Console]::Readkey` does. The following is quoted from the blog about ["Console.ReadKey" improvement](https://devblogs.microsoft.com/dotnet/console-readkey-improvements-in-net-7/#sys-calls):

> [tcsetattr](https://linux.die.net/man/3/tcsetattr) allows for changing the terminal settings. It’s used by .NET to apply its own setting at startup, and restore the previous settings at rundown.
