### ISSUE TITLE
Send-MailMessage sends computer NetBIOS name instead of FQDN in EHLO with no option to change it

### ISSUE THREAD

**Issue by ekzp** [PowerShell/PowerShell#18459]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Some ISPs are rejecting email sent using Send-MailMessage with the following error:

Send-MailMessage : Command parameter not implemented. The server response was: 5.5.2 <COMPUTERNAME>: Helo command
rejected: need fully-qualified hostname.

### Expected behavior

```console
Send a correctly formed FQDN in the EHLO command as laid out in the RFC.

Options:
1. Concatenate the NetBIOS name and the primary DNS suffix into a valid FQDN and use _it_ in the EHLO command.
2. Provide a switch to override the hostname used in EHLO with an arbitrary value.
```

### Actual behavior

```console
Using WireShark can see that:
- On a computer with no primary DNS suffix configured, Send-MailMessage sends the computer's NetBIOS name.
- On a computer with a valid primary DNS suffix, Send-MailMessage still sends the computer's NetBIOS name only.
```

### Error details

```console
Send-MailMessage : Command parameter not implemented. The server response was: 5.5.2 <COMPUTERNAME>: Helo command rejected: need fully-qualified hostname.
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.859
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.859
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
`Send-MailMessage` doesn't transform the server value, so whatever you provide (FQDN, IP, Netbios name) is passed to the `SmtpClient` API.  Are you saying that if you provide the FQDN it still uses the Netbios name?

**Comment by ekzp** [comment]
Hi Steve, thank you for your reply. I believe you are confusing the receiving MTA's FQDN/IP address specified by the -SmtpServer parameter with the client's name by which it introduces itself to the target MTA in the EHLO command.

The Send-MailMessage cmdlet does not seem to implement a parameter to specify the hostname used in EHLO - see https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-7.2.

Neither (Get-Command Send-MailMessage).Parameters, nor the above article list any option to override what's passed by EHLO to the receiving MTA.

I need an FQDN passed by EHLO instead of a NetBIOS name. Send-MailMessage either needs to synthetize it by combining the NetBIOS name with the primary DNS suffix, or to let me override the default via a dedicated optional parameter such as -EhloHostName "sendinghost.domain.tld".

Supporting screenshots:
1. Hostname and primary DNS suffix - how the EHLO hostname should be composed in order to be accepted even by the more restrictively configured MTAs
2. Packet capture of an actual Send-MailMessage session showing that the hostname passed by EHLO to the receiving MTA is the NetBIOS name, even if there is a primary DNS suffix configured on the machine (see first screenshot also).
3. Packet capture of an actual failed SMTP conversation invoking a malformed hostname passed by EHLO, using Send-MailMessage, to the receiving MTA.

Looking forward to your feedback.

Thanks,
Zoltan

![1](https://user-images.githubusercontent.com/47029823/200192334-9ea74d96-9cba-4671-a412-2e47ce5a9add.png)
![2](https://user-images.githubusercontent.com/47029823/200192335-be493ecd-90dd-4131-a7af-0dc38cec40a6.png)
![3](https://user-images.githubusercontent.com/47029823/200192336-897436fc-1d42-4635-9300-dfb7f88c1207.png)

**Comment by ekzp** [comment]
From https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md:

![image](https://user-images.githubusercontent.com/47029823/200192839-61c03b9d-b368-4c94-bdd1-d4071e3d700b.png)

That's exactly what I need it for. Email me a small report once a day. One email per day. Does not need to scale, I don't want to compete with Mailchimp.

The problem is that its EHLO logic does not adhere to RFC and some mail services drop the connection as a result.

**Comment by SteveL-MSFT** [comment]
@ekzp This cmdlet is just a thin wrapper around the .NET SMTP client API which has other known issues and deprecated.  We also continue to ship `Send-MailMessage` for compatibility reasons for existing scripts.  It looks like there are at least 3 modules on PowerShellGallery already using MailKit https://www.powershellgallery.com/packages?q=mailkit.  I'm not personally endorsing any of them as i haven't used them nor have a need for this type of functionality, but I do suggest moving off of `Send-MailMessage`.
