### ISSUE TITLE
Uptime Linux

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#18469]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

There is too much difference in the readings of the `/usr/bin/uptime` and the `Get-Uptime` cmdlet

```powershell
 PS > uptime -p
up 2 days, 16 hours, 26 minutes
 
PS > (Get-Uptime).ToString()
1.13:45:12
```

### Expected behavior

```console
Expected equal values
```

### Actual behavior

```console
Different values
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-rc.1
PSEdition                      Core
GitCommitId                    7.3.0-rc.1
OS                             Linux 6.0.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 29 Oct 2022 14:08:39 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Visuals

![up](https://user-images.githubusercontent.com/78153320/200090691-424452a1-26ab-4c19-8f64-c32ed99a533c.png)

**Comment by SteveL-MSFT** [comment]
From what I can tell, the current implementation is simply relying on .NET which calls the [native `clock_gettime()` function](https://github.com/dotnet/runtime/blob/c4341d45acca3ea662cd8d71e7d71094450dd045/src/coreclr/gc/unix/gcenv.unix.cpp#L1474-L1512).  However, it may request `CLOCK_MONOTONIC` which gives the time since the system booted, but does NOT include any time when the system was suspended.  It seems that it should be `CLOCK_BOOTTIME` which includes any suspended time.  Looking through the .NET source, they only use `CLOCK_BOOTTIME` to calculate the start time of processes and is not public.  So it seems the best option is to P/Invoke the API on non-Windows.

**Comment by SteveL-MSFT** [comment]
I think it might depend on your distro as the reference code does have different API calls depending on what is available on the system.  On my Ubuntu 22.04 install, `uptime -p` and `get-uptime` match.

**Comment by 237dmitry** [comment]
> but does NOT include any time when the system was suspended.

Yes, after reboot values was identical, when I closed the lid of laptop for three minutes I got the difference in values.

**Comment by iSazonov** [comment]
> Looking through the .NET source, they only use `CLOCK_BOOTTIME` to calculate the start time of processes and is not public. So it seems the best option is to P/Invoke the API on non-Windows.

This doesn't work on all platforms.

Best option is to request new API in .Net `System.Environment.Uptime`.
Until that, since it is not critical, we could add a workaround for Linux systems and use `/proc/uptime`.

**Comment by 237dmitry** [comment]
> we could add a workaround for Linux systems and use /proc/uptime

This works.
```powershell
 $ [timespan]::FromMilliseconds(([int](gc /proc/uptime).Split()[0] * 1000)).ToString()
01:33:18
 
 $ uptime -p
up 1 hour, 33 minutes
```

**Comment by iSazonov** [comment]
We use `Stopwatch.GetTimestamp()` and if it takes into account suspend time on Windows but not on Unix this looks like a bug. It makes sense to open new issue in .Net Runtime repository.

**Comment by SteveL-MSFT** [comment]
@iSazonov I tend to agree that this seems like a bug that should be fixed in .NET

**Comment by xtqqczze** [comment]
@kilasuit Please reopen.
