### ISSUE TITLE
Unthrown exception in `SessionStateInternal.NewItem`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#18468]
A `PSArgumentNullException` object is initialized and then discarded:
 
https://github.com/PowerShell/PowerShell/blob/39756d5602546d5956d4e8d87922efa1e35f0d83/src/System.Management.Automation/engine/SessionStateContainer.cs#L3412

**Comment by SteveL-MSFT** [comment]
Looking at the code, it appears that `path` is only used if it's not null, otherwise it has no impact.  So it seems that the trace is not useful and maybe the code should be rewritten to make it more clear.  Perhaps a comment is also warranted here.

**Comment by xtqqczze** [comment]
It seems the parameters are validated by `ParameterBinderController`. So we might be able to remove validation logic and have the caller assume responsibility.

**Comment by SeeminglyScience** [comment]
> So it seems that the trace is not useful

The name of the class is a bit misleading. The method basically just constructs an instance of `PSArgumentNullException`

https://github.com/PowerShell/PowerShell/blob/39756d5602546d5956d4e8d87922efa1e35f0d83/src/System.Management.Automation/utils/MshTraceSource.cs#L229-L240

So the code in the OP really is just missing `throw` (or should be removed, or turned into an `Assert`)
