### ISSUE TITLE
Contextual menu disappears after PS auto upgrade

### ISSUE THREAD

**Issue by tmm360** [PowerShell/PowerShell#18479]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've installed PS enabling contextual menu integration. After autoupgrade contextual menu disappears.

### Expected behavior

```console
After auto autoupgrade all setup options should be stay as they was during first setup process.
```

### Actual behavior

```console
Contextual menu disappears after auto upgrade.
```

### Environment data

```powershell
Windows 10 22H2 x64
```

**Comment by StevenBucher98** [comment]
Thanks @tmm360! What operation did you add to the context menu? Just a open PowerShell here? Also between what versions of PowerShell did this happen?

**Comment by tmm360** [comment]
During the setup, I choose to add the option "open here". I've noticed this now with the upgrade to 7.2.7, but also with previous versions.

**Comment by kilasuit** [comment]
2 key questions
- How did you install?
- How did you upgrade? 
  - i,e, was it via Windows Update or via effectively an install over the existing version via msi/msix?

**Comment by tmm360** [comment]
Installed with MSI, upgraded with Windows Update, I think. I found it upgraded.

**Comment by SetTrend** [comment]
Hmm, shouldn't this issue be handled somehow? Non-acting and eventually closing shouldn't be a solution.
