### ISSUE TITLE
Class not registered Error when trying Enable-WindowsOptionalFeature in 7.3.0-rc.1

### ISSUE THREAD

**Issue by lulMeow** [PowerShell/PowerShell#18476]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run PowerShell as admin,
type
`Enable-WindowsOptionalFeature -online -FeatureName Containers-DisposableClientVM -All -norestart`

p.s it works fine with the preinstalled PowerShell 5.1.25236.1000

found a similar issue here from 2 years ago:
https://github.com/PowerShell/PowerShell/issues/13866

### Expected behavior

```console
Path          :
Online        : True
RestartNeeded : False
```

### Actual behavior

```console
Enable-WindowsOptionalFeature: Class not registered
```

### Error details

```console
PS C:\Windows\System32> get-error

Exception             :
    Type       : System.Runtime.InteropServices.COMException
    ErrorCode  : -2147221164
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation,
Version=7.3.0.101, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Class not registered

    Source     : System.Management.Automation
    HResult    : -2147221164
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
InvocationInfo        :
    MyCommand        : Enable-WindowsOptionalFeature
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Enable-WindowsOptionalFeature -online -FeatureName Containers-DisposableClientVM -All
-norestart
    PositionMessage  : At line:1 char:1
                       + Enable-WindowsOptionalFeature -online -FeatureName Containers-Disposa …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Enable-WindowsOptionalFeature
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

PS C:\Windows\System32
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-rc.1
PSEdition                      Core
GitCommitId                    7.3.0-rc.1
OS                             Microsoft Windows 10.0.25236
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/72892766/200167574-4645daf5-eebc-42d4-84d5-da18fc90b909.png)

**Comment by SteveL-MSFT** [comment]
Are you using the Store installed PS7?

**Comment by SteveL-MSFT** [comment]
Dupe https://github.com/PowerShell/PowerShell/issues/13866

**Comment by mavaddat** [comment]
The "solution" is to either not use PowerShell Core for managing Windows features and capabilities or else, use `Import-Module DISM -UseWindowsPowerShell` into Core to enable the abilities.

**Comment by doctordns** [comment]
> The "solution" is to either not use PowerShell Core for managing Windows features and capabilities or else, use `Import-Module DISM -UseWindowsPowerShell` into Core to enable the abilities.

IMHO, that is poor advice. First, just because YOU can not make the DISM cmdlets work does not mean they don't work:

```powershell
PS C:\Foo> Get-WindowsOptionalFeature -online | Measure-Object
Count             : 134
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :
PS C:\Foo> Get-WindowsOptionalFeature -online -FeatureName Hyperv*
FeatureName      : HypervisorPlatform
DisplayName      : Windows Hypervisor Platform
Description      : Enables virtualization software to run on the Windows hypervisor
RestartRequired  : Possible
State            : Disabled
CustomProperties :

```
These cmdlets work fine here.,  Likewise, there is no need to use the -UseWindowsPowerShell switch for this module as it loads natively. 

The issue here seems to be the store installs. Better advice, use the `install-powershell.ps1` script which has worked perfectly for several years here.
