### ISSUE TITLE
SemanticVersion does not properly compare build number revisions and labels

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#18489]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

## Reference
https://semver.org/#spec-item-11
```
Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:

Identifiers consisting of only digits are compared numerically.

Identifiers with letters or hyphens are compared lexically in ASCII sort order.

Numeric identifiers always have lower precedence than non-numeric identifiers.

A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.

Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.
```

### Steps to reproduce
```powershell
[SemanticVersion]'1.2.3-test+5' -lt [SemanticVersion]'1.2.3-test+9'
[SemanticVersion]'1.2.3-test+5' -ne [semanticversion]'1.2.3-test'
```

### Expected behavior

```console
true
```

### Actual behavior

```console
false
```

### Environment data

```powershell
7.2.3
```

**Comment by ThomasNieto** [comment]
Those commands and output look to be correct per semver as everything after the + sign is considered build metadata and not used for version comparision.

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

> Precedence MUST be calculated by separating the version into major, minor, patch and pre-release identifiers in that order (**Build metadata does not figure into precedence**).

**Comment by JustinGrote** [comment]
@ThomasNieto I think I got prerelease and build mixed up as I've been translating classic ver to prerelease. My bad! Thanks for reviewing, I'll reopen if I come across another edge case.
