### ISSUE TITLE
Write-Error prefixes message with cmdlet name

### ISSUE THREAD

**Issue by odonyde** [PowerShell/PowerShell#18490]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Execute `Write-Error "This is an error."`

### Expected behavior

```console
Displayed error message is prefixed with "ERROR: ":
`ERROR: This is an error.`
```

### Actual behavior

```console
Displayed error message is prefixed with cmdlet name:
`Write-Error: This is an error.`
```

### Environment data

```powershell
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Write-Error](https://user-images.githubusercontent.com/21695902/200642057-0688c597-5a0b-4941-9f13-609a67e53945.png)

**Comment by kilasuit** [comment]
I found out where this issue has come from and it is from this PR https://github.com/PowerShell/PowerShell/pull/17722

**Comment by SteveL-MSFT** [comment]
This is expected and consistent with 5.1 which prefixes the source of the error and not the string `ERROR:`

**Comment by MartinGC94** [comment]
When used inside a function or a script it will include the name of the function/script, for example:

```
function MyFunction
{
    Write-Error -Message "Hello"
}
MyFunction
```
Results in `MyFunction: Hello` which is pretty convenient. Maybe an exception could be made when calling `Write-Error` by itself on the command line but what's the use case for that?

**Comment by odonyde** [comment]
Hi, @SteveL-MSFT and @MartinGC94! Thanks for your replies.

I see. So while debug, verbose, and warning messages are prefixed with a string indicating their message type ("DEBUG: ", "VERBOSE: ", "WARNING: "), error messages aren't... What is the recommended way to achieve a consistent output for all message types? Should I suppress `Write-Error`'s output by adding `-ErrorAction SilentlyContinue` and then display the error message with `Write-Host -Message "ERROR: $errorMessage" -ForegroundColor Red`? Or is it -the other way around- possible to  let `Write-Debug`, `Write-Verbose`, and `Write-Warning` prefix their output with the calling function/script like `Write-Error` does?

**Comment by SteveL-MSFT** [comment]
@odonyde technically, the format of the messages are actually dependent on the host.  So the ConsoleHost has it one way and a different host may or may not prefix the messages, use different colors, etc...  The one thing consistent regardless of host is that PowerShell adheres the different messages to their individual streams so they can be redirected appropriately.  My suggestion is to not try and work around what the host does and just use `Write-Error` without any additional prefix.
