### ISSUE TITLE
Packaging conflict between powershell-7.3.0-1.rh.x86_64 and dotnet-apphost-pack-7.0-7.0.0-1.x86_64 on Fedora/RHEL

### ISSUE THREAD

**Issue by 13xforever** [PowerShell/PowerShell#18498]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am on Fedora 36 using official Microsoft repo.
I've installed dotnet-sdk-7.0 (which installes dotnet-apphost-pack as a dependency), but when I try to upgrade powershell (or install it for the first time), I get transaction check error

```
Error: Transaction test error:
  file /usr/lib/.build-id/3a/e57b4bedbff101146eb11e0260bd44b922bb46 from install of powershell-7.3.0-1.rh.x86_64 conflicts with file from package dotnet-apphost-pack-7.0-7.0.0-1.x86_64
```

Considering this belongs to dotnet runtime, I think this is powershell packaging issue specifically.

### Expected behavior

```console
You can install both dotnet-sdk-7.0 and powershell-7.3.0 at the same time
```

### Actual behavior

```console
Both packages try to install the same file, failing transaction test, so I can either install dotnet 7.0 or powershell 7.3.0
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 13xforever** [comment]
Symlink from powershell-7.3.0:
```
lrwxrwxrwx. 1 root root 43 Nov  8 03:25 e57b4bedbff101146eb11e0260bd44b922bb46 -> ../../../../opt/microsoft/powershell/7/pwsh
```
Symlink from dotnet-apphost-pack-7.0:
```
lrwxrwxrwx. 1 root root 111 Oct 18 21:54 e57b4bedbff101146eb11e0260bd44b922bb46 -> ../../../../usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/7.0.0/runtimes/linux-x64/native/apphost
```

**Comment by rhubarb-geek-nz** [comment]
Suggest PowerShell should not use build-ids in the RPM packaging if repackaging identical binaries.

`--define "_build_id_links none"
`

**Comment by adityapatwardhan** [comment]
We are looking at it.

**Comment by TravisEz13** [comment]
We need to regenerate the `build-id` using this tool: https://manpages.ubuntu.com/manpages/bionic/man8/debugedit.8.html

**Comment by TravisEz13** [comment]
for the packaging tool we use, you would add:
`--rpm-rpmbuild-define "_build_id_links none"`
