### ISSUE TITLE
Incorrect file permissions in latest release https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0

### ISSUE THREAD

**Issue by theofficialgman** [PowerShell/PowerShell#18495]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

tarfiles contain incorrect file permissions. the executables are makred as rw and NOT executable. not an issue on previous releases (eg: they are executable on 7.2.7). this also affects nearly all other files in the tarfile (most of them have different permissions from before)

### Expected behavior

executables are marked as executable
```console
-rwxr-xr-x
```

### Actual behavior

executables are not marked as executable and many files have different permissions
```console
-rw-r--r--
```

### Environment data

```powershell
Linux
```

**Comment by 237dmitry** [comment]
Could you give a concrete example. This problem was before version 7.2.6 inclusive, but then it was fixed. in 7.3.0 I did not find any `UnixMode` errors, it coincides with `UnixFileMode`.

```powershell
Get-Item /opt/microsoft/powershell/7/pwsh |
Foreach-Object {
    $_.UnixMode
    [convert]::ToString([int]$_.UnixFileMode,8)
    stat -c "%a" $_
}
```

**Comment by 237dmitry** [comment]
>  the powershell tarfile

Do you mean the tar archive of the release? Yes, `pwsh` in it was not executable. But `UnixMode` represents correct string as it does native `ls`

**Comment by theofficialgman** [comment]
See my script for the file I am talking about. This are the release archives.

**Comment by 237dmitry** [comment]
>  These are the official binary release archives that are now broken

Add to script `chmod +x /path/to/pwsh`

**Comment by theofficialgman** [comment]
You should look at the tarfile. That's not the only mistake.
Just diff the contents. This is a packaging issue

**Comment by 237dmitry** [comment]
> Everything is wrong

I did these steps and all works:

1. Downloaded
2. Unpacked
3. `chmod +x pwsh` 
4. Made symlinks in the $PATH to pwsh and pwsh.dll.

pwsh to /usr/bin. pwsh.dll to ~/bin

![ArcoLinux_2022-11-09_18-03-34](https://user-images.githubusercontent.com/78153320/200865526-fa081a0f-0581-41b2-819b-370fb77aba63.png)

**Comment by theofficialgman** [comment]
You are missing the point. It's a packaging issue. It was correct by default in previous releases as it should be.

**Comment by 237dmitry** [comment]
> You are missing the point. It's a packaging issue.

No, I did not. I do not refuse that this is the error of packagers.

>  the user shouldn't have to do anything to run from the archive

This is linux, I'm already used to all sorts of surprises ))

**Comment by theofficialgman** [comment]
> > You are missing the point. It's a packaging issue.
> No, I did not. I do not refuse that this is the error of packagers.

I will continue to wait till a maintainer comes around. there isn't any debate here, this is a mistake of the packaging. tarfiles contain the file permissions for a reason, so that you can extract and run without messing with permissions.

> > the user shouldn't have to do anything to run from the archive
> This is linux, I'm already used to all sorts of surprises ))

bad packages like this is what makes these surprises. your denial only further worsens that situation and makes the linux ecosystem less welcoming. @237dmitry I'm going to ask that you refrain from commenting here further. your comments do nothing for the issue.

previous releases with correct permissions on all files
```
-rwxr--r--  1 ubuntu ubuntu   199280 Sep 26 17:29 libSystem.Globalization.Native.so
-rwxr--r--  1 ubuntu ubuntu   854464 Sep 26 17:29 libSystem.IO.Compression.Native.so
-rwxr--r--  1 ubuntu ubuntu   198944 Oct 22  2021 libSystem.IO.Ports.Native.so
-rwxr--r--  1 ubuntu ubuntu   198944 Sep 26 17:29 libSystem.Native.so
-rwxr--r--  1 ubuntu ubuntu   199080 Sep 26 17:29 libSystem.Net.Security.Native.so
-rwxr--r--  1 ubuntu ubuntu   198968 Sep 26 17:29 libSystem.Security.Cryptography.Native.OpenSsl.so
-rwxr--r--  1 ubuntu ubuntu  2433384 Sep 26 17:18 libclrjit.so
-rwxr--r--  1 ubuntu ubuntu  6929448 Sep 26 17:18 libcoreclr.so
-rwxr--r--  1 ubuntu ubuntu   858808 Sep 26 17:12 libcoreclrtraceptprovider.so
-rwxr--r--  1 ubuntu ubuntu   791616 Sep 26 17:16 libdbgshim.so
-rwxr--r--  1 ubuntu ubuntu   461432 Sep 26 17:41 libhostfxr.so
-rwxr--r--  1 ubuntu ubuntu   461448 Sep 26 17:41 libhostpolicy.so
-rwxr--r--  1 ubuntu ubuntu  2589248 Sep 26 17:17 libmscordaccore.so
-rwxr--r--  1 ubuntu ubuntu  1774960 Sep 26 17:18 libmscordbi.so
-rwxr--r--  1 ubuntu ubuntu   242432 Oct 18  2021 libpsl-native.so
-rwxr--r--  1 ubuntu ubuntu    58504 Sep 26 17:29 mscorlib.dll
-rwxr--r--  1 ubuntu ubuntu   101504 Sep 26 17:29 netstandard.dll
drwxr-xr-x  2 ubuntu ubuntu     4096 Oct 17 23:21 pl
drwxr-xr-x  2 ubuntu ubuntu     4096 Oct 17 23:21 pt-BR
-rwxr-xr-x  1 ubuntu ubuntu   200424 Oct 17 23:17 pwsh
```

the incorrect packaging from 7.3.0
```
-rw-r--r--  1 ubuntu ubuntu   201568 Nov  7 22:23 libSystem.Globalization.Native.so
-rw-r--r--  1 ubuntu ubuntu   855568 Nov  7 22:23 libSystem.IO.Compression.Native.so
-rw-r--r--  1 ubuntu ubuntu   200200 Nov  7 22:23 libSystem.IO.Ports.Native.so
-rw-r--r--  1 ubuntu ubuntu   211560 Nov  7 22:23 libSystem.Native.so
-rw-r--r--  1 ubuntu ubuntu   200416 Nov  7 22:23 libSystem.Net.Security.Native.so
-rw-r--r--  1 ubuntu ubuntu   347184 Nov  7 22:23 libSystem.Security.Cryptography.Native.OpenSsl.so
-rw-r--r--  1 ubuntu ubuntu   856344 Nov  7 22:23 libclrgc.so
-rw-r--r--  1 ubuntu ubuntu  3085408 Nov  7 22:23 libclrjit.so
-rw-r--r--  1 ubuntu ubuntu  6866104 Nov  7 22:23 libcoreclr.so
-rw-r--r--  1 ubuntu ubuntu   990184 Nov  7 22:23 libcoreclrtraceptprovider.so
-rw-r--r--  1 ubuntu ubuntu   462392 Nov  7 22:23 libhostfxr.so
-rw-r--r--  1 ubuntu ubuntu   461848 Nov  7 22:23 libhostpolicy.so
-rw-r--r--  1 ubuntu ubuntu  2596432 Nov  7 22:23 libmscordaccore.so
-rw-r--r--  1 ubuntu ubuntu  1840944 Nov  7 22:23 libmscordbi.so
-rw-r--r--  1 ubuntu ubuntu   242432 Nov  7 22:23 libpsl-native.so
-rw-r--r--  1 ubuntu ubuntu    58496 Nov  7 22:23 mscorlib.dll
-rw-r--r--  1 ubuntu ubuntu   101040 Nov  7 22:23 netstandard.dll
drwxr-xr-x  2 ubuntu ubuntu     4096 Nov  7 22:26 pl
drwxr-xr-x  2 ubuntu ubuntu     4096 Nov  7 22:26 pt-BR
-rw-r--r--  1 ubuntu ubuntu   201272 Nov  7 22:23 pwsh
```

**Comment by mmitche** [comment]
@SteveL-MSFT, any idea about this issue?

**Comment by AndrewSav** [comment]
This is affecting us too

**Comment by SteveL-MSFT** [comment]
The Maintainers are looking at this today

**Comment by theofficialgman** [comment]
@TravisEz13 request to re-open. this issue is back on latest release

-rw-rw-r-- 1 gman gman 72544 Jun 18 10:15 /home/gman/powershell/pwsh
