### ISSUE TITLE
Questions.. and others. Download web search. and idea

### ISSUE THREAD

**Issue by oklokl** [PowerShell/PowerShell#18500]
### Summary of the new feature / enhancement

https://github.com/DigitalRuby/IPBan/releases
First of all, we have a website.
Here I want to download a file.

`IPBan-Windows-x64_1_8_0.zip`
`powershell.exe -Command "& {Invoke-WebRequest -OutFile $env:ProgramFiles\IPBan\IPBan-Windows-x64_1_8_0.zip -Uri "https://github.com/DigitalRuby/IPBan/releases/download/1.8.0/IPBan-Windows-x64_1_8_0.zip"}`
I can download like this.
But what I want.

I'd like to configure a command that automatically receives the file with the highest number all the time.

`powershell.exe -Command "& {Invoke-WebRequest -OutFile $env:ProgramFiles\IPBan\IPBan-Windows-x64???.zip -Uri "https://github.com/DigitalRuby/IPBan/releases/download/*/IPBan-Windows-x64*.zip" -New -One}`

`-One` Get one file command. my imagination.

`-New -One` I came up with the idea.
if i do this Retrieves and receives the highest number of files in the path. no see.
I'm a computer novice, so my comprehension is poor.
sorry. Please understand.

`releases/download/1.8.0(random)/IPBan-Windows-x64_1_8_0(random).zip`

In this case, what should I do.. Search through the command
Can I download it?...

If I know it, I think it can be applied to various areas.
I don't speak English, so I used Google Translate.

thank you.

Organize my writing.
My goal is to get the latest version files that are currently released.
through the command. That's my goal.
:)

### Proposed technical implementation details (optional)

idea
random address. It is marked with `???`.
`Invoke-WebRequest -Uri https://test.com/dd/???/test*.zip`

`Invoke-WebRequest -Uri -New` = Lets you select the highest number.
`Invoke-WebRequest -Uri -New1~6`, from the highest file to 6 output.

`-Old` the same. Measure from the bottom of the number. Alphabet is the same.
`-Old 1~6` numbers can be set by yourself.

Include all url addresses like test*.zip dir command.
application `*test*.zip`

`https://test.com/dd/[1-5,A-F]/test*.zip`
Only numbers from 1 to 5 are accepted. And if there is an alphabet after it, A to F are allowed.

for example
`Invoke-WebRequest -Uri https://test.com/dd/1A2B3d3/test*.zip`
This address is verified as the correct address. let me bring

Applications
`Invoke-WebRequest -Uri https://test.com/dd/[1~5,A-F.1~5,A-F.1~5,A-F]/test*.zip`
The address is expressed by putting a dot in the middle.

`Invoke-WebRequest -Uri https://test.com/dd/1A2B3d3.1A2B3d3.1A2B3d3/test*.zip`

**Comment by jhoneill** [comment]
The idea is nice. However there is no standard URL you can send to ask for the URL of the latest version. A lot of the time what has to happen is  GET  /SomePage ; process the result to find the latest version or URL for another version; then Get /FileYouReallyWant. 

It would be easy enough to write for one target, but it doesn't generalize

**Comment by oklokl** [comment]
Users can write anticipating certain keywords like a detective.
It is telling the AI ​​to output the configuration of a specific condition, such as predicting. I actually didn't like the `dir` command or the `cmd Tree` command.
This is because it is a command to output everything in the target. However.
I made it, and many people use it a lot.

So my thoughts. Try making it once.
And that's what you try.

And I would like to refine it and edit it.

And in the case of a standard url, you can set the pattern by standardizing the settings.
Only under certain conditions.

You don't have to be perfect in the first place.

Because it is the first time I try and it is the first time I make it.

Like math rules. A specific condition is entered by the user. if you find

It appears to be possible. If you think it's difficult

'dir' is what I'm thinking

It is simply ignorantly applying the rule pattern of `dir` if there are technical limitations.

Servers and data also have specific patterns.

And the slash is separated by `//`, but in the end, `\\` is in the form of a folder like a reverse slash.

It simply searches for it and outputs it according to the conditional expression.

there simply. The "*" wildcard inserts the difficult part of programming like a button easily and conveniently.

I used google translator.

**Comment by oklokl** [comment]
https://kin.naver.com/qna/detail.nhn?d1Id=1&dirId=104&docId=432288858

```
md "%USERPROFILE%\Downloads\IPBan"
cd "%USERPROFILE%\Downloads\IPBan"
$target = (Invoke-WebRequest -Uri 'https://github.com/DigitalRuby/IPBan/releases').Links.Href | findstr "tree";$targetStr = "";foreach($Line in $target) {$targetStr = $Line;break;}foreach($Line in $targetStr.Split('/')) {$targetStr1 = $Line;}$targetStr2 = $targetStr1 -replace "\.","_";Invoke-WebRequest ('https://github.com/DigitalRuby/IPBan/releases/download/'+$targetStr1+'/IPBan-Windows-x64_'+ $targetStr2 + '.zip') -OutFile ('%USERPROFILE%\Downloads\IPBan\IPBan-Windows-x64.zip');
```

Good news for me.. you made it available for download. He is a Seoul Korea expert. Naver intellectuals (forum Q/A to ask anything)
I didn't make it.
I mostly use single line commands.
:)

Since I often order from this person, he made them in one line.
I thought it would be impossible.

He seems to have kidnapped aliens. My humor..

thank you.
