### ISSUE TITLE
The application to execute does not exist : '/<script_path>/pwsh.dll'. When running script with shebang from bash with PS v7.3.0 installed

### ISSUE THREAD

**Issue by szymonos** [PowerShell/PowerShell#18510]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create /tmp/test.ps1 script with shebang using the below code:
```
#!/usr/bin/pwsh
$true
```
Set the executable bit with `chmod +x /tmp/test.ps1` command and run the script from **bash** shell on WSL/Linux with PowerShell v7.3.0 installed.

### Expected behavior

```console
$ /tmp/test.ps1
True
```

### Actual behavior

```console
$ /tmp/test.ps1
The application to execute does not exist: '/tmp/pwsh.dll'.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by szymonos** [comment]
So I've tried to copy pwsh.dll to script path, and got the error:
```
You must install .NET to run this application.

App: /opt/microsoft/powershell/7/pwsh
Architecture: x64
App host version: 7.0.0
.NET location: Not found
```

After installing dotnet 7.0.0
```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/user/.dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/<script_path>/pwsh.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/<script_path>/pwsh.runtimeconfig.json' file and specify the appropriate framework.
```
after copying 'libhostpolicy.so' from /opt/microsoft/powershell/7 to '/home/user/.dotnet' another error:
```
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
```

**Comment by szymonos** [comment]
> Create a symbolic link to pwsh.dll in the directory that is in $PATH

I did it, but it doesn't work.
Adding /opt/Microsoft/PowerShell/7 to $PATH doesn't help either.

**Comment by 237dmitry** [comment]
Check if pwsh is executable. In 7.3.0 I did `chmod +x pwsh`

**Comment by szymonos** [comment]
> Check if pwsh is executable. In 7.3.0 I did `chmod +x pwsh`

Come on, how would pwsh work otherwise? Everything is working fine, when I'm using PowerShell directly, it's just the shebang behavior, when running the script from non-pwsh shell, that is broken.

Yes, it is executable, I'm installing it using rpm/deb packages (depending on distro) which are not affected by the bug in tgz package.

Also, the script I'm running has the executable bit set (otherwise, it would throw an error: `bash: ./temp.ps1: Permission denied`.

It is really easy to replicate, Are you telling me, that it does work for you?

I've tested it on multiple freshly installed distros (on WSL): fedoraremix, Ubuntu, Debian, Opensuse-Tumbleweed, and also my bare metal Fedora Linux installation, and the behavior is exactly the same everywhere. I was also checking the same behavior on existing WSL distributions still on PowerShell v7.2.7 and shebangs on scripts were working, after updating to v7.3.0 it stopped which broke many of my automations.

**Comment by 237dmitry** [comment]
> Come on, how would pwsh work otherwise?

I deleted the post almost immediately, but you managed to read it. )) I was misled that in [powershell-7.3.0-linux-x64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.3.0/powershell-7.3.0-linux-x64.tar.gz) pwsh is not executable.

**Comment by TechnoRolo** [comment]
We have exactly the same issue after an automatic upgrade from 7.2.7 to 7.3 in LINUX redhat - All PowerShell scripts stopped working with the "The application to execute does not exist: '/XXX/pwsh.dll'.  where XXX is the location of the PS script .

Everything looks as it did on 7.2.7 as far as I can see, it's just not interpreting the shebang anymore.  Enter pwsh and run the script and it works fine.

**Comment by 237dmitry** [comment]
> Are sure you're calling script from bash?

![1](https://user-images.githubusercontent.com/78153320/201096102-1bc637a6-a088-46aa-bf56-8fc87c60606d.png)

**Comment by proutek** [comment]
Same here on Ubuntu after upgrade. The script does not start using Shebang.
It works when I start it with pwsh script.ps1

**Comment by rflor** [comment]
Ubuntu 20.04 and Ubuntu 22.04, after upgrading to 7.3.0 via apt same error.
Found a workaround:
#!/usr/bin/env pwsh  as shebang 

It's a common (ab)use of the env utility, it decouples the scripts from path prefix.

**Comment by dmitriyse** [comment]
This bug has been introduced long time ago somewhere in 7.3.0 preview.

The alternative workaround is to overwrite the startup file `/opt/microsoft/powershell/7/pwsh` from 7.2.7 version.

**Comment by dmitriyse** [comment]
Common! This issue requires not a triage, it requires 7.3.1 fix right now.
Few days after this ticket will be full of hate to PS.

**Comment by mklement0** [comment]
Not to add to the pain, but, historically speaking, shebang-line support has received little attention, as the list of open bugs shows: https://github.com/PowerShell/PowerShell/issues?q=is%3Aissue+in%3Atitle+shebang+is%3Aopen

**Comment by szymonos** [comment]
> 

Just to give full solution, to call it with `-NoProfile` parameter, you need to add `-S/--split-string` parameter to env.
Working shebang would look like this:

```sh
#!/usr/bin/env -S pwsh -NoProfile
```

**Comment by rhubarb-geek-nz** [comment]
> Found a workaround: #!/usr/bin/env pwsh as shebang

I recommend this approach for portable scripts, for example on macOS `pwsh` is `/usr/local/bin/pwsh` and the `#!/usr/bin/env` solution works with the path.

**Comment by daxian-dbw** [comment]
This is a regression in .NET 7 comparing with .NET 6. See https://github.com/dotnet/runtime/issues/78941 for details.

**Comment by paradizelost** [comment]
Can confirm that this breaks pwsh 7.3.0 on linux hosts for me when using scripts with a #!/usr/bin/pwsh shebang as well

**Comment by daxian-dbw** [comment]
The fix to https://github.com/dotnet/runtime/issues/78941 will be backported to .NET 7. Once the new .NET 7.x release is out, we will have a service release to 7.3 to include that .NET fix.

**Comment by daxian-dbw** [comment]
Re-open the issue. .NET will ship the fix in 7.0.3, which is supposed to be out in February. Will close this issue once we ship a servicing release with .NET 7.0.3.

**Comment by Mighty-Monarch** [comment]
For anyone keeping track, the problem still exists in 7.3.1

**Comment by shanselman** [comment]
Hit this today @daxian-dbw

**Comment by Mighty-Monarch** [comment]
This appears to have been resolved in 7.3.2

**Comment by webcompas** [comment]
> This appears to have been resolved in 7.3.2

I just tested the 7.3.2 but the error still occurs.

**Comment by Mighty-Monarch** [comment]
> > This appears to have been resolved in 7.3.2
> 
> I just tested the 7.3.2 but the error still occurs.

you are correct.  I must have been at a pwsh prompt instead of a bash prompt when I tested. 🤦‍♂️

**Comment by erichiller** [comment]
Yes, the same error persists in v7.3.2

**Comment by lzocateli** [comment]
Contributing to the feed, I also had the same problem as @szymonos, when I installed powershell 7.3.2 on RHEL 8 (4.18.0-425.10.1.el8_7.x86_64), however I removed it, and installed the 7.2.9 lts version ( sudo dnf install -y powershell-lts), then everything worked as usual!!

**Comment by szymonos** [comment]
In PowerShell v7.3.3 it is finally fixed :D.

**Comment by daxian-dbw** [comment]
The fix is included in .NET 7.0.3, which was released 2 weeks back.
PowerShell v7.3.3 targets .NET 7.0.3, so the fix is in for PowerShell.
