### ISSUE TITLE
DontShow affects all parametersets

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#18512]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

DontShow is set on individual parameter attributes, allowing you to define it for one parameterset but not another like this:

```
function Verb-Noun
{
    Param
    (
        [Parameter(ParameterSetName = "ParamSet1")]
        [switch]
        $ParamSet1,

        [Parameter(ParameterSetName = "ParamSet2")]
        [switch]
        $ParamSet2,

        [Parameter(ParameterSetName = "ParamSet1")]
        [Parameter(ParameterSetName = "ParamSet2", DontShow)]
        [string]
        $HiddenParam
    )
}
```
But even though it's only set for `ParamSet2` it remains hidden in `ParamSet1`. See: `TabExpansion2 'Verb-Noun -ParamSet1 -' | Select-Object -ExpandProperty CompletionMatches`

### Expected behavior

```console
Tab completion should take the resolved parameter set into account when deciding whether to hide or show parameters with the DontShow attribute set.
```

### Actual behavior

```console
DontShow always hides the parameter, regardless of the resolved parameter set by the pseudobinding.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasNieto** [comment]
What is the use case for doing it this way? Can't you just have that parameter in just the required parameter set?

**Comment by MartinGC94** [comment]
One use case could be deprecating parameters in a parameter set. For example, `Write-Progress` currently forces you to specify an `Activity`, even when it shouldn't be needed. If you update it to have a new parameter set for scenarios where it's not needed you can keep the `Activity` as a hidden optional parameter for backwards compatibility with the original parameterset.
