### ISSUE TITLE
Format-Table and Format-List ignore (calculated) properties for strings and .NET primitive types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18523]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Probably an exotic use case, but still worth fixing:

```powershell
# Calculated column is ignored; works with Select-Object, however.
1000, 2000 | format-table -Property @{ name='Num'; expression= { '{0:N0}' -f $_ } }
```

Update, based on the comments below:

* `-Force` is needed to make the above work.
* It isn't about _calculated_ properties per se, but most affected types (such as `[int]`) have no properties of their own.

### Expected behavior

```console
1,000
2,000
```

### Actual behavior

```console
1000
2000
```

That is, the calculated property was ignored and the default out-of-band formatting was applied.

### Environment data

```powershell
PowerShell Core 7.3.0
```

**Comment by SeeminglyScience** [comment]
It works if you add `-Force` to `Format-Table`

...but the docs for that parameter definitely don't make that clear, and I don't know if this even was on purpose. Opening to cmdlets WG

**Comment by SeeminglyScience** [comment]
I should also note that it's not necessarily about calculated properties. It's whether the default formatting view is wide/custom and marked as out of band? Not 100% on the specifics but `'10' | ft` also doesn't work without `-Force` even though string has a property, and same with error records.

**Comment by mklement0** [comment]
Good to know about `-Force`, and you're right that it's not about _calculated_ properties per se (though most of the out-of-band-formatted types have no properties, so using a calculated one is the only option).

Yes, I suspect it's about out-of-band-formatted types and about objects having no properties (`[pscustomobject] @{ } | Format-Table { 'hi' }` fails too), but seemingly not about types associated with formatting data with a custom view, given that `Get-Date | Format-Table` works _without_ `-Force`, for instance.

**Comment by jdhitsolutions** [comment]
Added to the review list for the Cmdlet WG

**Comment by michaeltlombardi** [comment]
Do we have a definitive answer on the conditions under which **Force** is required? Is it only when the input object doesn't have properties, or doesn't have a default set of properties defined for that view, or?

**Comment by mklement0** [comment]
@michaeltlombardi, I think the summary is:

If you want to use `Format-Table` or `Format-List` with  the `-Property` parameter - irrespective of whether the arguments given are property _names_ or _calculated properties_ - you need `-Force` under one of the following conditions:

* The input objects are normally formatted out-of-band (via `.ToString()`), which notably applies to `[string]`  and .NET primitive types, which are a superset of the built-in numeric types such as `[int]`, `[long]`, ...

  * The full list, gleaned from [the source code](https://github.com/PowerShell/PowerShell/blob/7dc4587014bfa22919c933607bf564f0ba53db2e/src/System.Management.Automation/FormatAndOutput/common/FormatViewManager.cs#L41), is:

    * `[string]`, `[sbyte]`, `[byte]`, `[int16]`, `[uint16]`, `[int]`, `[uint]`, `[long]`, `[uint64]`, `[char]`, `[single]`, `[double]`, `[bool]`, `[decimal]`, `[intptr]`, `[securestring]`, `[bigint]`
   * Note the absence of `[uintptr]`, which, however, is effectively formatted as out-of-band too, given that, like most (quasi) numeric types, has no properties (see next point)

* The input object(s) have _no_ (public) properties.

* The input objects are instances of the wrapper types PowerShell uses for its output streams _other_ than the success-output stream, notably  `System.Management.Automation.ErrorRecord` instances; note that this applies only when these wrapper types are sent _via the success-output stream_, which requires either having captured them via common parameters such as `-ErrorVariable` first, or using a redirection such as `*>&1` (without that, the `Format-*` cmdlets fundamentally don't receive them as input).

  * These types are, in order of their associated stream numbers:
    * [`[System.Management.Automation.ErrorRecord]`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.ErrorRecord), [`[System.Management.Automation.WarningRecord]`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.WarningRecord), [`[System.Management.Automation.VerboseRecord]`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.VerboseRecord), [`[System.Management.Automation.DebugRecord]`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.DebugRecord), [`[System.Management.Automation.InformationRecord]`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.InformationRecord).

  * Note: With the exception of `System.Management.Automation.ErrorRecord` and `System.Management.Automation.InformationRecord`, use of `-Force` with these types is currently _buggy_ in that the colored prefix used in default formatting still prints; e.g.:

```powershell
# !! Each output line is preceded by "WARNING: " printed in yellow.
Write-Warning 'beware' *>&1 | Format-List -Force
```

Whether or not the input objects have _formatting data_ associated with them is irrelevant.

----

On a meta note:

* The sheer complexity of the above points to the fact that it would have been far easier to fix the inconsistency; as a change that solely relates to the _presentation_ of data, it wouldn't even be considered breaking.
