### ISSUE TITLE
Cannot stop StartupScript set in PSSessionConfiguration with CTRL+C

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#18538]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

*This question was transferred from discussions*

Consider following setup:

1.  Computer **"A"**:
```powershell
Register-PSSessionConfiguration -Name 'Test' -StartupScript 'C:\Test.ps1'
```
with following content of the *Test.ps1* script (a loop):
```powershell
for($i=1;;$i++){$i; Start-Sleep 1}
```
2. Computer **"B"**:
```powershell
Enter-PSSession -Computer 'A' -ConfigurationName 'Test'
```

When you enter the session on computer **A** the **CTRL+C** does not stop the startup script execution. The only way is to restart *WinRM* service on computer **A**.

*Questions:*
1. Is there a way (workaround) to stop the startup script?
2. When registering *PSSessionConfiguration* the *StartupScript* is executed immediately, why? *(is it a bug or design choice?)*

### Expected behavior

```console
1. CTRL+C should stop StartupScript set in PSSessionConfiguration
2. StartupScript should not be executed when registering new PSSessionConfiguration
```

### Actual behavior

```console
1. Cannot stop StartupScript with CTRL+C
2. StartupScript is executed immediately when registering PSSessionConfiguration
```

### Error details

```console
N/A
```

### Environment data

```powershell
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
I'm fairly sure this is by design. The script is used to set restrictions on the remote environment for things like JEA. If it were possible to break the script it would be possible to make a JEA session a full admin one.  

Testing the script before configuring it as the one to run for a PSSessionConfiguration would seem to be the solution to the case you've described.

**Comment by kborowinski** [comment]
That makes sense. Thanks for the insight.
