### ISSUE TITLE
Expose a -Class <string[]> parameter for Export-ModuleMember 

### ISSUE THREAD

**Issue by astrutzenberg-godaddy** [PowerShell/PowerShell#18539]
### Summary of the new feature / enhancement

I would like to have the ability to export class definitions in a module as a means to automatically expose access to it.  Something like:

```
class MyClass{
   $MyMember1
   $MyMember2
}

export-modulemember -Class MyClass
```

The goal is to avoid having to pepper my scripts with explicit "using <modulename>" directives in my scripts/code

**Comment by SeeminglyScience** [comment]
Duplicate of #12533

**Comment by SeeminglyScience** [comment]
Thanks for the report! We're tracking this in the issue above, consider giving it a thumbs up!
