### ISSUE TITLE
disable distracting suggestion text which appears as I'm typing in v7.3.0

### ISSUE THREAD

**Issue by garretwilson** [PowerShell/PowerShell#18542]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I updated to v7.3.0 yesterday and suddenly every time I type something Powershell prints some "suggestion" text on the line in front of my cursor.

I guess that's what it is. It doesn't seem to function the way I would expect. Typing `<tab>` doesn't autocomplete the suggestion, and instead inserts _some other_ text. Is it a preview of what `<F8>` would do?

I have no idea, but it is immensely distracting. Most of the time I am typing a _new_ command; if I wanted to press `<F8>`, I would press `<F8>`.

Even worse on a color scheme such as the embedded shell inside VS Code, I can hardly tell the difference between what I'm typing and this new "suggestion text".

How can I turn this off?

### Expected behavior

```console
PS> foo|
```

### Actual behavior

```console
PS> foo| blah blah blah blah and other distracting stuff
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by garretwilson** [comment]
I don't even know what this thing is _called_! I searched the v7.3.0 [changelog](https://github.com/PowerShell/PowerShell/blob/master/CHANGELOG/7.3.md), but I couldn't find anything relevant for "preview" or "auto" or "type" or "text".

**Comment by MartinGC94** [comment]
It's technically a PSReadline thing, 7.3 just happens to include a newer version of PSReadline where it's enabled by default. You can disable it by adding this to your $profile: Set-PSReadLineOption -PredictionSource None

**Comment by garretwilson** [comment]
Thank you thank you thank you! What a relief (even though it already wasted an hour of my morning). I was seriously this close to downgrading to v7.2.x.

I appreciate the info very much. Thanks for responding so quickly.

**Comment by edoust** [comment]
How can I accept a displayed suggestion? Neither `Tab` nor `Enter` work for me

**Comment by loxia01** [comment]
> How can I accept a displayed suggestion? Neither `Tab` nor `Enter` work for me

`F8` works for me.

**Comment by SteveL-MSFT** [comment]
cc @theJasonHelmick

**Comment by jim3** [comment]
How do I disable this inside VS Code? At the moment, if I issue the command `Set-PSReadLineOption -PredictionSource None` at the integrated terminal in VS Code it disables it, which is what I want. But when I start/kill a terminal, it's back. I created a `Microsoft.VSCode_profile.ps1` and placed this command inside `C:\Users\MyUserName\Documents\PowerShell` but nothing changes. I search in Settings and couldn't find anything there no feedback elsewhere.

**Comment by jhoneill** [comment]
VS code has two versions of PowerShell - the integrated console and normal PowerShell in a window. 

`$profile.CurrentUserAllHosts`  gives the file which is used for all  both 

`C:\Users\me\Documents\PowerShell\Microsoft.VSCode_profile.ps1` will be the one if the terminal window is labelled "PowerShell Extension" but not if is simple "Pwsh"

**Comment by theJasonHelmick** [comment]
Hey! Here's some additional documentation on working with predictors if helpful: https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/using-predictors?view=powershell-7.3

**Comment by jim3** [comment]
> Hey! Here's some additional documentation on working with predictors if helpful: https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/using-predictors?view=powershell-7.3

This helps, so thanks!

**Comment by happyTonakai** [comment]
> > How can I accept a displayed suggestion? Neither `Tab` nor `Enter` work for me
> 
> By default right arrow. I have added this to my profile to allow ctrl-right-arrow to complete a word at a time or move over existing words depending on the context (I can't remember which kind member of the team provided it I didn't write it).
> 
> ```
>     Set-PSReadLineKeyHandler -Key Ctrl+RightArrow -ScriptBlock {
>        param($key, $arg)
>        $line = $null
>        $cursor = $null
>        [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
>        if ($cursor -lt $line.Length) {
>              [Microsoft.PowerShell.PSConsoleReadLine]::ForwardWord($key, $arg)
>        }
>        else {[Microsoft.PowerShell.PSConsoleReadLine]::AcceptNextSuggestionWord($key, $arg)}
>     }
> ```

How do I change the default right arrow to tab key?

**Comment by softyoda** [comment]
Hi, it was somehow enabled on another pc for no reason, I like it

I've seen it's called "predictors" and not autocompletion, (doc here : https://learn.microsoft.com/fr-fr/powershell/scripting/learn/shell/using-predictors?view=powershell-7.3 )

but I don't know how to enable it again, i'm in the reverse situation, how to enable it ?

I've tried the two commands Install-Module -Name PSReadLine and  Install-PSResource -Name PSReadLine but it says commandnotfoundexception

I have tried to install the [PowerShellGet v3](https://www.powershellgallery.com/packages/PowerShellGet/3.0.14-beta14) but it kept saying commandnotfoundexception and the nupkg file is not a .exe nor a .msi I could execute to install.

**Comment by softyoda** [comment]
It seem that the powershell i had with conda isn't the same as the one i can download on the store.
Impossible to know where is located the one on the store on my hard-drive tho, i'll won't be able to edit json config of terminal to open conda with last version of powershell if I can't know where it install it.
