### ISSUE TITLE
Minor flaw in error text coloring for "NormalView' still exists in v7.3.0

### ISSUE THREAD

**Issue by loxia01** [PowerShell/PowerShell#18549]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Set `$ErrorView = 'NormalView'`

2. Produce an error by issuing for example `Write-Error "blabla"` or `dir "nonexistant path"` 

### Expected behavior

Expected behavior would be that ALL error text is colorized (according to settings in  $host.PrivateData)

### Actual behavior

Main error text in `'NormalView'` is colorized correctly, but the command name and colon is not colorized, as it is in `'ConciseView'` and in PowerShell 5.1.

In addition to this I just discovered that in `'NormalView'`, when entering a command alias, the alias is not exchanged with the full command name as in `'ConciseView'` (but not in PowerShell 5.1). I don't know if this is expected behavior or not, or if it is related to the coloring flaw.

See screenshot.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![2022-11-13 222743](https://user-images.githubusercontent.com/36552933/201546020-ca4f6624-c664-4b18-b081-75b1e461abd8.jpg)

**Comment by 237dmitry** [comment]
```console
$PSStyle.Formatting is a nested object to control default formatting of debug, error, verbose, and warning messages.
You can also control attributes like bolding and underlining.
It replaces $Host.PrivateData as the way to manage colors for formatting rendering.
$Host.PrivateData continues to exist for backwards compatibility but isn't connected to $PSStyle.Formatting.
```

This issue rather relates to `$PSStyle.Formatting.ErrorAccent` that does not change anything.

![error](https://user-images.githubusercontent.com/78153320/201632256-742ba654-c801-4bfe-a97e-c3c0368a522d.png)
