### ISSUE TITLE
PowerShell 7.3.0 ssh: The term 'ssh' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by sysmat** [PowerShell/PowerShell#18544]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- I'm using in it in windows terminal
- with  PowerShell 7.2.x works fine
- I have OpenSSH in path it works in older power shell:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> Get-Command  ssh

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            8.1.0.1    C:\Windows\System32\OpenSSH\ssh.exe
```

- in  PowerShell 7.3.0

```
PowerShell 7.3.0
Loading personal and system profiles took 9805ms.
❯ ssh root@tet.si
ssh: The term 'ssh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Expected behavior

```console
- To be eble to use ssh.exe
```

### Actual behavior

```console
Not working
```

### Error details

```console
ssh: The term 'ssh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![env](https://user-images.githubusercontent.com/69830/201486067-26fe8dbe-f538-4d45-af61-323dfe4d6d2b.png)

**Comment by sysmat** [comment]
❯ $env:PATH
C:\Users\tomaz\apache\groovy-3.0.5\bin;C:\Program Files (x86)\PuTTY\;C:\Windows\System32\OpenSSH;C:\Program Files\nodejs;C:\ProgramData\bin;C:\ProgramData\Fish\Barrel\buffalo\0.14.2;C:\Program Files (x86)\sbt\bin;C:\Users\tomaz\lien.sh;C:\

**Comment by al-cheb** [comment]
I'm not able to reproduce it.
![image](https://user-images.githubusercontent.com/47745270/201489542-ddce0de5-454d-4fac-8533-0d7b391f7973.png)

**Comment by sysmat** [comment]
Hmm, OK, then is on my machine problem

**Comment by sysmat** [comment]
- The problem was that I install x86.msi version, I installed x64.msi version and it works fine

**Comment by ttiee** [comment]
> * The problem was that I install x86.msi version, I installed x64.msi version and it works fine

Great thanks for your solution. You saved my day.

**Comment by JeelRajodiya** [comment]
> * The problem was that I install x86.msi version, I installed x64.msi version and it works fine

Thanks a lot.
