### ISSUE TITLE
Powershell Direct doesn't respect $PSSessionConfigurationName

### ISSUE THREAD

**Issue by leoniDEV** [PowerShell/PowerShell#18557]
### Steps to reproduce

```Powershell
$PSSessionConfigurationName = "Powershell.7"
Enter-PSSession -VMName myvm -Credential (Get-Credential)
```

### Expected behavior

```Powershell
[myvm]: PS c:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.25217
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Actual behavior

```Powershell
[myvm]: PS c:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.25217.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.25217.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kilasuit** [comment]
You need to add `-ConfigurationName $PSSessionConfigurationName` to your command otherwise it will default to the 5.1 session.

**Comment by jborean93** [comment]
@kilasuit `$PSSessionConfigurationName` should still work, it's designed to be the default configuration name pwsh connects to if defined as per https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#pssessionconfigurationname.

**Comment by jborean93** [comment]
Still the problem here is that AFAIK configuration names only apply to the WinRM/WSMan PSRemoting sessions as it's a specific part of that protocol. I'm unsure if the Hyper-V based ones (what `-VMName` selects) supports such a thing. IIRC it does but I'm unsure how it is actually plumbed in. If it does support it then it would make sense for it to also use `$PSSessionConfigurationName`.

**Comment by jborean93** [comment]
Looks like it is in there https://github.com/PowerShell/PowerShell/blob/9c55e1e9ab7f77d8a16d28648db5a22978e087ba/src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs#L589

Would have to step through the code to see why `$PSSessionConfigurationName` isn't being applied there.

**Comment by leoniDEV** [comment]
@jborean93 The client is Windows 11 and I tested Powershell Direct against the most recente Azure Stack HCI Preview (build 25217), against Windows Server 2022 build (20348), and against Windows 11 Insider Preview build 25236, so we can exclude a too old version of Windows, I think.

**Comment by leoniDEV** [comment]
Why close this issue? It is not answered, the bug still there.

**Comment by kilasuit** [comment]
@leoniDEV it's was just an automated closure based on me adding the resolution-answered label. I've corrected this by reopening this issue & re-routing this to the right Working Group to investigate further. That was my bad & I apologise for the inconvenience caused
