### ISSUE TITLE
Web cmdlets feature should allow for scoping where headers are sent

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#18558]
### Summary of the new feature / enhancement

Using the new CookieContainer in dotNet, we should allow scoping of headers.

https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=net-6.0

**Comment by CarloToso** [comment]
Could you write a test to show how this feature works in curl or wget ?
