### ISSUE TITLE
Test-Connection cannot access network without sudo on Fedora 37

### ISSUE THREAD

**Issue by SMSourov** [PowerShell/PowerShell#18585]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Download and install Powershell 7.3.0 in Fedora 37
2. Open Terminal and type 
`touch powershell.ps1`
    This will create and empty file. This is needed to reproduce the bug easily.
3. Now, open the newly created **powershell.ps1** file, type and save 
`Test-Connection -TargetName www.bing.com -Ping -Count 1`
4. Open the Terminal again, type and run 
`pwsh powershell.ps1`
(this worked in v7.2.6)
5. One more time but this time with sudo (to confirm the bug)
`sudo pwsh powershell.ps1`

### Expected behavior

```console
For both cases:
`
   Destination: www.bing.com

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 fedora           204.79.197.200                 54         32 Success

`(something just like this)
```

### Actual behavior

```console
When the powershell file is run without root:
   1 |  Test-Connection -TargetName www.bing.com -Ping -Count 1
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).


When the powershell file is run with root:

   Destination: www.bing.com

Ping Source           Address                   Latency BufferSize Status
                                                   (ms)        (B)
---- ------           -------                   ------- ---------- ------
   1 fedora           204.79.197.200                 54         32 Success
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 6.0.8-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 11 15:09:04 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/81343486/202216720-bd7e05a2-e2bd-4265-aa3b-b04d7cf0fd34.png)

**Comment by iSazonov** [comment]
It would be nice to document this. @237dmitry Please open doc issue with your suggestion in PowerShell Docs repository.

**Comment by SMSourov** [comment]
> 

Thanks. It worked.
