### ISSUE TITLE
PowerShell 7.3 sends arguments to native apps differently

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#18617]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Please use the attached script `test.ps1` and satellite trivial `Get-Arg.exe` that prints all the arguments.

[_221118_1846-ps730.zip](https://github.com/PowerShell/PowerShell/files/10044247/_221118_1846-ps730.zip)

Or use/build from sources below:

*test.ps1*

```powershell
& $PSScriptRoot\Get-Arg.exe 1 'a a' '"b"' '\"c\"'
```

*Get-Arg.cs*

```csharp
using System;

internal class Program
{
    static void Main(string[] args)
    {
        foreach (var arg in args)
            Console.WriteLine(arg);
    }
}
```

**Test 1** Invoke by powershell 5.1:

```
powershell .\test.ps1
```

Output (good):

```
1
a a
b
"c"
```

**Test 2** Invoke by pwsh 7.2.7:

```
C:\Bin\pwsh.7.2.7\pwsh.exe .\test.ps1
```

Output (good, the same as above):

```
1
a a
b
"c"
```

**Test 3** Invoke by pwsh 7.3.0:

```
pwsh .\test.ps1
```

Output (not good, different from test 1 and 2):

```
1
a a
"b"
\"c\"
```

The third and forth arguments are sent differently.

### Expected behavior

```console
see above
```

### Actual behavior

```console
see above
```

### Error details

```console
.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by nightroman** [comment]
The release notes do not mention this change -- https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0

So this might be a bug or unintended change. If this is the intended change then it's worth mentioning because it breaks the behavior existed for years.

**Comment by jhoneill** [comment]
See #18614 
#18568 
and #18554

**Comment by nightroman** [comment]
@jhoneill Thank you. The suggested `$PSNativeCommandArgumentPassing = 'Legacy'` works as a workaround.

I agree that 7.3.0 works "better". But it clearly breaks things.
The change should be well documented and visible in release notes.

NB In the past, the PS team refused to fix some bugs for avoiding breaking effects like this.
