### ISSUE TITLE
GetPersonalModulePath() should be made a public method, and be configurable from powershell.config.json

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#18613]
### Summary of the new feature / enhancement

"As a user, I want to specify where my modules are installed by default, such as a non-OneDrive path or another drive for performance"

While a powershell.config.json setting exists to allow configuration of the `PSModulePath`, it does not allow someone to set the *default* install location for modules. The logic for this is hidden in an internal method, and as a result, products like PowerShellGet v2, PowershellGetv3, and ModuleFast have their own separate internal implementations that mirror this method.

By making the method public, and making the target overridable in powershell.config.json, package management tools can tie into PowerShell to be consistent with the intent of the use.

### Proposed technical implementation details (optional)

Update this to be public:
https://github.com/PowerShell/PowerShell/blob/9ae18ab0d18abea0569b691693e864adb77baeb5/src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs#LL962-L970C10

And add a powershell.config.json setting that will be checked by this method and override the default behavior if specified.

I am willing to attempt a PR if this is marked `up-for-grabs`

**Comment by SteveL-MSFT** [comment]
I believe @JamesWTruher was going to tackle this as a pre-requisite to https://github.com/PowerShell/PowerShell/issues/15552.  Specifically exposing an API to retrieve the user, shared, and system module paths.  This would be needed by PowerShellGet rather than using a priori knowledge.  I believe Jim had some concerns with simply making those APIs public instead of some sanitized versions, but don't recall the details.

**Comment by KirillOsenkov** [comment]
Can we please reactivate

**Comment by KirillOsenkov** [comment]
@JustinGrote @SteveL-MSFT

**Comment by JustinGrote** [comment]
@KirillOsenkov for note I am not a maintainer of the PowerShell repo, I'm just a community member, there's nothing I can do in this regard.

**Comment by KirillOsenkov** [comment]
sorry I thought you could reactivate as the author

**Comment by MatejKafka** [comment]
@kilasuit not completed, please reopen

**Comment by Jaykul** [comment]
It certainly would be useful to have access to this specific calculation _after_ the fallback is done (in case the values aren't in the powershell.config.json file)...

Of course, it would also be useful to just expose the location of the two config files or even the whole PSConfiguration class. I mean, it's not like you can stop anyone from finding the files and reading in the json, but it sure would be nice to be able to use your logic for fallback values, and there's a few other [settings in there](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.4) already I can imagine wanting to read, like the Compatibility and Policy settings.

**Comment by JamesWTruher** [comment]
It's already available via `GetPSModulePath("User")` - however, the configuration bit isn't there

**Comment by JustinGrote** [comment]
> It's already available via `GetPSModulePath("User")` - however, the configuration bit isn't there

Exactly, so it's fairly useless frankly, Here's a function I've written that lays out how I think it should behave:
https://github.com/PowerShell/PowerShell/issues/24274#issuecomment-2342636988

FYI This issue can probably be de-duped to #24274, there's more discussion there.

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this, we'd like to clarify the purpose of the configuration file options. They were intended to be an analog to the scoped environment variable `PSModulePath` in environments where the registry was not present (this would have been around the time 5.1 was shipping on nano server). They are not meant to change the location of a singular install location, at least not any more than the environment variable is today.

The `GetPersonalModulePath` method is already surfaced by `GetPSModulePath`, so making that method public wouldn't actually be useful. There are still plans to add a way to specify where modules should be installed, and when that happens `GetPSModulePath` will be updated to pull the new path with no code changes needed by the consumer. This work is already being tracked in #15552

**Comment by SeeminglyScience** [comment]
Note that I've marked it as declined here but it could probably more easily be labeled as duplicate. The feature itself is still planned and tracked separately, the specific implementation suggestion is declined. Hopefully that makes sense

**Comment by JustinGrote** [comment]
Yep makes sense, closing here.
