### ISSUE TITLE
String.ToCharArray yields error while inside function

### ISSUE THREAD

**Issue by TomEpsilon** [PowerShell/PowerShell#18615]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Define a function like so:
```powershell
function h([string]$s) {
    $s.tochararray()
}
```
2. Call the function:
```powershell
h("something")
```
It seems that my error is the first appearance on the issue board. I doubt that.

### Expected behavior

```console
PS> h("something")
s
o
m
e
t
h
i
n
g
```

### Actual behavior

```console
PS> h("something")
Get-History: Cannot bind parameter 'Id'. Cannot convert value "something" to type "System.Int64". Error: "The input string 'something' was not in a correct format."
```

### Error details

```console
Exception             :
    Type              : System.Management.Automation.ParameterBindingException
    Message           : Cannot bind parameter 'Id'. Cannot convert value "something" to type "System.Int64". Error:
"The input string 'something' was not in a correct format."
    ParameterName     : Id
    ParameterType     : long
    TypeSpecified     : string
    ErrorId           : CannotConvertArgumentNoMessage
    Line              : 1
    Offset            : 2
    CommandInvocation :
        MyCommand        : Get-History
        ScriptLineNumber : 1
        OffsetInLine     : 1
        HistoryId        : 2
        Line             : h("something")
        PositionMessage  : At line:1 char:1
                           + h("something")
                           + ~~~~~~~~~~~~~~
        InvocationName   : h
        PipelineLength   : 1
        PipelinePosition : 1
    ErrorRecord       :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind parameter 'Id'. Cannot convert value "something" to type "System.Int64". Error: "The
input string 'something' was not in a correct format."
            HResult : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Get-History], ParentContainsErrorRecordException
        FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetHistoryCommand
        InvocationInfo        :
            MyCommand        : Get-History
            ScriptLineNumber : 1
            OffsetInLine     : 2
            HistoryId        : 2
            Line             : h("something")
            PositionMessage  : At line:1 char:2
                               + h("something")
                               +  ~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite        :
        Name          : VerifyArgumentsProcessed
        DeclaringType : System.Management.Automation.CmdletParameterBinderController, System.Management.Automation,
Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data              : System.Collections.ListDictionaryInternal
    InnerException    :
        Type           : System.Management.Automation.PSInvalidCastException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot convert value "something" to type "System.Int64". Error: "The input string
'something' was not in a correct format."
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : InvalidCastFromStringToInteger
        TargetSite     :
            Name          : ConvertStringToInteger
            DeclaringType : System.Management.Automation.LanguagePrimitives
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message        : Cannot convert value "something" to type "System.Int64". Error: "The input string 'something'
was not in a correct format."
        InnerException :
            Type       : System.FormatException
            TargetSite :
                Name          : ThrowOverflowOrFormatException
                DeclaringType : System.Number, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Message    : The input string 'something' was not in a correct format.
            Source     : System.Private.CoreLib
            HResult    : -2146233033
            StackTrace :
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Int64.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture,
Object value)
        Source         : System.Management.Automation
        HResult        : -2147467262
        StackTrace     :
   at System.Management.Automation.LanguagePrimitives.ConvertStringToInteger(Object valueToConvert, Type resultType,
Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType,
Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean
recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String
parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
    Source            : System.Management.Automation
    HResult           : -2146233087
    StackTrace        :
   at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException
originalBindingException)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
arguments)
   at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- End of stack trace from previous location ---
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidArgument: (:) [Get-History], ParameterBindingException
FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetHistoryCommand
InvocationInfo        :
    MyCommand        : Get-History
    ScriptLineNumber : 1
    OffsetInLine     : 2
    HistoryId        : 2
    Line             : h("something")
    PositionMessage  : At line:1 char:2
                       + h("something")
                       +  ~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="340" alt="image" src="https://user-images.githubusercontent.com/81517212/202699369-63bb29cd-6b82-4117-960b-24d5ad24dc30.png">

**Comment by Northman-de** [comment]
"h" is an alias for get-history and can not be redefined. So you are calling `get-history ("something")`
This works as expected:
```powershell
function hh([string]$s) {
    $s.tochararray()
}
```

**Comment by mklement0** [comment]
To add to @Northman-de's comment:

* Among commands with the same name, aliases have higher precedence than functions - see the conceptual [about_Command_Precedence](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Command_Precedence) help topic

* PowerShell functions, cmdlets, scripts, and external programs must be invoked _like shell commands_ - `foo arg1 arg2` - _not_ like C# methods - `foo('arg1', 'arg2')`.  
If you accidentally use `,` to separate multiple arguments, you'll construct an _array_ that a command sees as a _single argument_.

  * Therefore (leaving the name collision aside), your call should be: `h "something"`

**Comment by jhoneill** [comment]
> "h" is an alias for get-history and can not be redefined. So you are calling `get-history ("something")` This works as expected:


Actually it can be defined. I have a function H to give me some extra functionality.  
alias h has precedence over function h.  so the alias must be removed to use it as a function.

**Comment by Northman-de** [comment]
> Actually it can be defined. I have a function H to give me some extra functionality.
> alias h has precedence over function h. so the alias must be removed to use it as a function.

Thanks for the hint. I wasn't aware that there is a new remove-alias cmdlet at least in PS7 .
I always thought that the default aliases are "write protected" to not mess up things...

**Comment by jhoneill** [comment]
I just use ` remove-item Alias:\h ` ` remove-item Alias:\cd `  so I can define those as functions I've been redefining cd since V1 first as an alias for `push-location` instead of `set` and now as a function which does some extra things.

**Comment by TomEpsilon** [comment]
I see! Thank you all for responding. Do we mark this as closed now?

**Comment by mklement0** [comment]
@TomEpsilon 👍. Given that tagging as `Resolution-Answered`, the issue will get closed automatically. However, you can always close your own issues anytime.

**Comment by mklement0** [comment]
Some more background info re built-in aliases and alias removal that may be helpful (I decided to dig deeper):

---

Generally speaking, it's better not to redefine / remove _built-in_ aliases, given that other code may rely on them, which notably applies to `%` and `?` (with an alias of a command focused on _interactive_ use, such as `Get-History`, that is less of a concern).

`%` and `?` as well as the _majority_ of the built-in ones actually are  - lightly - protected from accidental removal, because they're defined with the `ReadOnly` option. 
However, this protection can be overruled with `-Force`, e.g.  `Remove-Alias foo -Force`  or `Remove-Item alias:foo -Force` (in Windows PowerShell).

Quite a few built-in aliases are _not_ protected, however, and there doesn't appear to be any logic behind which are and which aren't (see the breakdown below).

That said, it _is_ possible to define aliases that can _not_ be removed once defined in a session (not even with `-Force`), namely with `New-Alias -Option Constant` (as opposed to `New-Alias -Option ReadOnly`, where removal can be forced with `Remove-Alias -Force`, as stated).
However, none of the built-in aliases are defined this way, as of v7.3.0.

(Trying something like `(Get-Alias foo).Options = 'None'` does _not_ work for `ReadOnly` and `Constant` aliases - though the opposite direction - adding `ReadOnly` or `Constant` to `None` or `AllScopes` - later works, irreversibly so in that session).

Note that option `AllScope` is unrelated to removability, and the pitfall with removing such aliases is that  they may continue to exist in preexisting scopes, such as previously imported modules, given that `AllScope` means that an alias definition is _copied to_ any new scope on creation (more on that below).

Here's a breakdown of the built-in aliases as of v7.3.0; note that _none_ have the `Constant` option, so they can all be removed:

```powershell
Get-Alias | Group Options
```
```none
Count Name                      Group
----- ----                      -----
   29 None                      {chdir, cls, erase, etsn…}
   69 ReadOnly                  {clc, clhy, cli, clp…}
    9 AllScope                  {cd, copy, del, dir…}
    5 ReadOnly, AllScope        {?, %, foreach, select…}
```

An aside re option `AllScope`:

* I'm unclear on when it is actually useful, given that simply defining an alias in the _global_ scope also makes it visible to all scopes.  

* However, the behavior differs in two scenarios:

  * On removal, given that `AllScope` copies the alias to each newly created scope, so that each scope has its own, independent copy. Therefore, while later removal of a global alias (defined without `-AllScope`) in effect removes it  from _all_ scopes, removing an `AllScope` alias only removes it from a single scope (the current one by default, or one specified via `-Scope`). While scopes are usually ephemeral, the ones in imported modules are not, so that already imported modules  continue to see the alias.

  * Defining an `AllScopes` alias  in a _non-global_ scope in effect makes it available to all scopes created from then on, but doesn't retroactively copy it to the global scope or to already-imported modules.
