### ISSUE TITLE
Improve debuggability of the ConstrainedLanguage mode

### ISSUE THREAD

**Issue by wasker** [PowerShell/PowerShell#18628]
### Summary of the new feature / enhancement

Today, if PowerShell starts in ConstrainedLanguage, there's no way to tell **why** did this happen.

The problem is simply manifested as:

```
Microsoft.PowerShell_profile.ps1: Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.
```

There're [multiple reasons](https://github.com/PowerShell/PowerShell/blob/319c93d6979fd99624c99b0a5ce49711378364bf/src/System.Management.Automation/security/wldpNativeMethods.cs#L186) for why the scripting is restricted and knowing which one exactly is very helpful when troubleshooting the issue.

### Proposed technical implementation details (optional)

That'd be great if one could start pwsh in a mode where it would print out the high-level source of the issue (WLDP, AppLocker, cached or not, system or user, file policy enforcement).

The best would be if it could analyze CI policies present on the machine and highlight which one is the culprit (stretch goal.)

**Comment by TravisEz13** [comment]
> That'd be great if one could start pwsh in a mode where it would print out the high-level source of the issue (WLDP, AppLocker, cached or not, system or user, file policy enforcement).

I think the above goal is doable.

> The best would be if it could analyze CI policies present on the machine and highlight which one is the culprit (stretch goal.)

This would be better implemented by WDAC/AppLocker.  AppLocker already has cmdlets that work reasonably well to the best of my knowledge.

**Comment by PaulHigin** [comment]
One thing we could do is add an additional message to the start-up logo, that indicates if PowerShell is running in CL mode under a lock down policy.  Logging when something is disallowed is another enhancement we could consider.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this.  We agreed it makes sense to add something like `[Constrained Language Mode]` to the logo on startup and additional logging to indicate why it failed and potentially updating the error message pointing to looking into the log, but not disclose why it failed directly in the error message as that may be sensitive information.
