### ISSUE TITLE
Running New-LocalUser in PowerShell 7.3 raises an error

### ISSUE THREAD

**Issue by trainee4it** [PowerShell/PowerShell#18624]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

To reproduce :

Open PowerShell 7.3 X64 . (latest)

Run the `New-LocalUser` Cmdlet

### Expected behavior

```console
Creation of Local User
```

### Actual behavior

```console
We get this error and the user does not get created.

New-LocalUser: Could not load type 'Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI' from assembly 'System.Management.Automation, Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

### Error details

```console
Exception             :
    Type       : System.TypeLoadException
    Message    : Could not load type 'Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI' from assembly 'System.Management.Automation, Version=7.3.0.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
    TypeName   : Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI
    TargetSite :
        Name          : ProcessRecord
        DeclaringType : Microsoft.PowerShell.Commands.NewLocalUserCommand
        MemberType    : Method
        Module        : Microsoft.PowerShell.LocalAccounts.dll
    Source     : Microsoft.PowerShell.LocalAccounts
    HResult    : -2146233054
    StackTrace :
   at Microsoft.PowerShell.Commands.NewLocalUserCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [New-LocalUser], TypeLoadException
FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.NewLocalUserCommand
InvocationInfo        :
    MyCommand        : New-LocalUser
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 6
    Line             : new-LocalUser -Name login2
    PositionMessage  : At line:1 char:1
                       + new-LocalUser -Name login2
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : new-LocalUser
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This is a problem in Windows PowerShell and that team is aware of this already.  For now, you'll have to use Windows PowerShell to use that cmdlet.

**Comment by idontsov** [comment]
> This is a problem in Windows PowerShell and that team is aware of this already. 
@SteveL-MSFT, could you please provide a link to the bug in the "external component" so that we receive a notification when the issue is resolved?

**Comment by h4wtd0gz** [comment]
Link to the bug would be super useful, as we also notice the same issue on 7.3.4.

**Comment by pc-robelbois** [comment]
PowerShell 7.3.4 ; same issue for me.

**Comment by thuynhyubi** [comment]
Has there been any progress on this? Also running into the same error PS7.3.5 on W11.

**Comment by arkadR** [comment]
Is there any update on this? Still hitting the error on 7.4.0-preview.4 and Windows 11.

**Comment by thuynhyubi** [comment]
> Is there any update on this? Still hitting the error on 7.4.0-preview.4 and Windows 11.

I found a workaround to this issue by using the below import.  

import-module microsoft.powershell.localaccounts -UseWindowsPowerShell

**Comment by ethanf53** [comment]
Still seeing this issue on 7.4.1 on Windows 11.

**Comment by mrcellal** [comment]
I am seeing it as well.  the workaround posted above does seem to allow it to function.

**Comment by iSazonov** [comment]
Fixed in community module https://www.powershellgallery.com/packages/LocalAccounts
