### ISSUE TITLE
7.3.0, Linux: Incorrect file attributes

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#18625]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Cmdlets give incorrect file attributes. Example:

From man page of `/usr/bin/chattr`:

```console
i      A file with the 'i' attribute cannot be modified: it cannot be deleted or renamed, no link can be created to this file, most of the  file's  metadata
       can not be modified, and the file can not be opened in write mode.  Only the superuser or a process possessing the CAP_LINUX_IMMUTABLE capability can
       set or clear this attribute.
```
Try:

```powershell
$null = New-Item 1.txt
(Get-Item 1.txt).Attributes     # Normal
lsattr 1.txt                    # --------------e------- 1.txt

sudo chattr +i 1.txt
(Get-Item 1.txt).Attributes     # Normal
lsattr 1.txt                    # ----i---------e------- 1.txt
Remove-Item 1.txt               # Error access denied

sudo chattr -i 1.txt
Remove-Item 1.txt
```
This can give the user a headache, especially when getting illogical errors while debugging scripts as ALL file permissions, owner and group remain the same.

### Expected behavior

```console
Cmdlets must output special file attributes
```

### Actual behavior

```console
Cmdlets do not return all of attributes 

```

### Error details

```console
No Errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
This seems like a dotnet/runtime issue with `System.IO.FileAttributes` not reflecting this attribute.  PowerShell just returns what FileInfo returns.  I would suggest creating an issue here https://github.com/dotnet/runtime
