### ISSUE TITLE
New-Item Type HardLink mistakenly resolves relative target paths against the working directory of the *process*

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18623]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
# On Windows

'hi' > temp.txt

[Environment]::CurrentDirectory = 'C:\'

New-Item -Force -Type HardLink temp_hl.txt -Target temp.txt

'---'

[Environment]::CurrentDirectory = $PWD.ProviderPath

New-Item -Force -Type HardLink temp_hl.txt -Target temp.txt

Remove-Item -ErrorAction Ignore, temp.txt, temp_hl.txt
```

### Expected behavior

Both `New-Item` calls should succeed.

### Actual behavior

The first `New-Item` call fails with "Could not find item temp.txt", because `temp.txt` is mistakenly looked for in `C:\`, the _process_' working directory.

### Environment data

```powershell
PowerShell Core 7.3.0 on Windows
```

**Comment by SteveL-MSFT** [comment]
It appears the code currently just passes the specified value to the `CreateHardLink()` Win32 API which uses the process working directory to resolve.  It seems that the code should resolve the path to the PowerShell working directory and if not a filesystem path, return an error.
