### ISSUE TITLE
Can't load Docker Module in Windows version 6.0.0.9

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#1863]
## Steps to reproduce

Just an observation.  you are providing a PowerShell Docker sample on "Adding Docker-PowerShell demo from announce recording #1862".

I works on Windows PowerShell 5.0 and 5.1 but not on Windows PowerShell version 6.0.0.9.

Is there a new set of installation commands? or, is there a workaround?
## Expected behavior

To Install PowerShell Docker module.
## Actual behavior

Setup commands won't work:

> dotnet restore
> dotnet publish .\src\Docker.PowerShell -o .\src\Docker.PowerShell\bin\Module\Docker -r win

![dockerxplatf_01_2016-08-17_21-45-19](https://cloud.githubusercontent.com/assets/19892435/17759502/87c479c8-64c5-11e6-9868-3b0bbadf6664.jpg)
## Environment data

Windows 10 Enterprise Insider Build 14901.rs_preprelease.160805-1700
 $PSVersionTable
Name                           Value

---

SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
CLRVersion
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9

**Comment by jterry75** [comment]
@MaximoTrinidad - The code that builds Docker-PowerShell for the 6.0.0-alpha9 build of PowerShell is not yet published. We are actively working on getting the build that was used in the demo published to the public repo's and then this should work.

**Comment by MaximoTrinidad** [comment]
Hi @jterry75! Thanks for the update. I'm looking forward to it.
:0

**Comment by joeyaiello** [comment]
This is external to the docker-powershell repo and should be fixed by now.
