### ISSUE TITLE
Exclude variables and functions decorated with `HiddenAttribute` from tab completion

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#18642]
### Steps to reproduce

(not really a bug, but the form kinda fits better. I'll fix the labels)

Some (admittedly edge case) scenarios require declaring a global function or variable containing implementation detail for a larger system. For example, in [VSCode's shell integration script](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1) and several things in PowerShellEditorServices.

Usually when this is required, a prefix is added to reduce the probability of a naming conflict, but it's still possible to end up in completion results.

```powershell
[System.Management.Automation.Hidden()] $global:__testing = 'found'

function __testing { [System.Management.Automation.Hidden()] param() }

(TabExpansion2 -inputScript ($s = '$__t') -cursorColumn $s.Length).CompletionMatches
(TabExpansion2 -inputScript ($s = '__t') -cursorColumn $s.Length).CompletionMatches
```

### Expected behavior

```console
No results
```

### Actual behavior

```console
CompletionText ListItemText ResultType ToolTip
-------------- ------------ ---------- -------
$__testing     __testing      Variable [string]$__testing
__testing      __testing       Command …
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
We already handle `DontShow` so should do HiddenAttribute too.

**Comment by kilasuit** [comment]
Is this perhaps not a case of order of execution?

**Comment by theJasonHelmick** [comment]
@SeeminglyScience -- Thank you for this feature request.  The WG has reviewed this request and finds it would be very useful include and accepts this request.
