### ISSUE TITLE
Sort-Object, unlike operators, uses the current culture and doesn't support requesting the invariant culture via -Culture

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18655]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Unlike PowerShell's _operators_, which use the _invariant_ culture for comparisons, `Sort-Object` seems to use the _current_ culture.

This unfortunate discrepancy between operators and cmdlets is nothing new:

  * See https://github.com/PowerShell/PowerShell/issues/6989

However, even with the de-facto discrepancy, there is no currently no way to _opt-into_ using the invariant culture, given that the `-Culture` parameter is `[string]`-typed and that the name of the invariant culture is the _empty string_ (`''`), and passing the empty string appears to be _ignored_ .

```powershell
[cultureinfo]::CurrentCulture = 'tr'

'i', 'I' | Sort-Object -CaseSensitive

'---'

'i', 'I' | Sort-Object -Culture ([cultureinfo]::InvariantCulture) -CaseSensitive
```

**Update**: There is a **workaround**: using the **LCID value** of the Invariant Culture, **`127`** (note that the majority of cultures no longer have unique LCID values and share the catch-all value `4096`, but the invariant culture's LCID is unique):

```powershell
'i', 'I' | Sort-Object -CaseSensitive -Culture 127  # OK
```

### Expected behavior

```console
I
i
---
i
I
```

That is, in the invariant culture `i` should sort _before_ `I`

### Actual behavior

```console
I
i
---
I
i
```

That is, the `-Culture` argument was effectively ignored.

### Environment data

```powershell
PowerShell Core 7.3.0
```

**Comment by 237dmitry** [comment]
What if we use `TwoLetterISOLanguageName`,  `ThreeLetterISOLanguageName` or `ThreeLetterWindowsLanguageName` standards instead of `Name`?

```powershell
'I', 'i' | Sort-Object -CaseSensitive -Culture tr
'---'                                            
'I', 'i' | Sort-Object -CaseSensitive -Culture iv
```

**Comment by jhoneill** [comment]
Oh Lordy, current vs invariant again. 
@mklement0  this looks like it comes from your checking things for #18638 (that answer should really go in a KB article somewhere, it's wasted as a github response, but that's another matter). 

So what we're saying is if the culture sort order doesn't match the invariant  `-gt` / `-lt`  and `sort-object` diverge.
````
PS>  [cultureinfo]::CurrentCulture = 'no'

PS>  "c" -gt "b"
True

PS>  "Å" -gt "b"
False

PS>  "c" , "Å" ,  "b"  | sort-object
b
c
Å
```

(I got a lecture about Å from a Norwegian client 10 years or so ago, so I keep using it).  

I would class this divergence as a **bug**

I am trying to think of a case where someone would set the machine's culture and want comparison operators to ignore it. I have clients who keep all their servers in one time zone, regardless of location, or keep all servers set to US culture etc.  There should at least be an "opt-in" for compare using current culture (if there is a change it's possible breaking change, so there needs to be an opt out, whether in or out is the default is debatable) 

I can also see a situation where someone would spot the difference in sort orders for an international company and specify scripts use a particular language, and invariant culture should work for this.  Converting a culture object to a string and not accepting empty string looks like a second **bug** to me.  The assumption that invariant = US holds for most things (not time format), so the work round is easy. But any culture parameter should process strings and culture objects correctly.

**Comment by mklement0** [comment]
Thanks, @jhoneill.

> I would class this divergence as a bug

I agree, but in the past a similar divergence was retained for fear of breaking backward compatibility:

* #6989

It is certainly desirable for all operators and cmdlets to consistently default to the _invariant_ culture.

> Converting a culture object to a string and not accepting empty string looks like a second bug to me.

Indeed, but this can easily be fixed.

Looking at the code, I realize that there are at least _workarounds_ for now: you may pass `127` or `0x7f` to `-Culture` and have it recognized as the invariant culture, via its LCID (Language Code Identifier):

https://github.com/PowerShell/PowerShell/blob/cba9dacb2957174e8729be77f4389b61718c87c0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs#L65-L94

Given the above, you can't help but wonder whether `object` would have been the appropriate parameter type, so that names  (strings), LCIDs, and `[cultureinfo]` instances can be detected as such.

It's worth noting, however, that LCIDs are _deprecated_: see https://learn.microsoft.com/en-us/windows/win32/intl/language-identifier-constants-and-strings

@237dmitry 

As you can see from the above, an argument (that can't be parsed as a number) is passed on to the `[cultureinfo]::new([string] $name)` constructor, which - with respect to _predefined_ culture-info objects - only accepts their `.Name` property value (case-insensitively), such as `'en-US'` for a specific culture, and `'en'` for a neutral culture.

The problem, however, is that - hypothetical - names of _non-predefined_ cultures are _also_ accepted, which will typically amount to _quiet failure_, namely if you have a _typo_ in your `-Culture` argument.

E.g., the following returns an ad hoc `[cultureinfo]` instance with the given, fictitious name; its other properties appear to be the same as that of `[cultureinfo]::InvariantCulture`:

```powershell
[cultureinfo]::new('foo-bar')
```

This could be helped by using the following method instead, which, however, is at least technically a breaking change (though existing code that relies on it by definition never worked as intended - unless a bogus name was deliberately chosen to in effect get the _invariant_ culture):

```csharp
// Failing sample call from PowerShell:
//      [cultureinfo]::GetCultureInfo('foo-bar', $true)
static cultureinfo GetCultureInfo(string name, bool predefinedOnly)
```

That, along with changing the `-Culture` parameter to `object` (so that preexisting, possibly custom `[cultureinfo]` instances can be accepted), would rule out quiet failures.
