### ISSUE TITLE
Get-ControlPanelItem and Show-ControlPanelItem missing from pwsh 7.3.0

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#18678]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

MS documentation has both [Get-ControlPanelItem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-controlpanelitem?view=powershell-5.1) and [Show-ControlPanelItem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/show-controlpanelitem?view=powershell-5.1), but then say its been removed from later pwsh, [here](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7). 

**How can I use this with pwsh 7.3.0 ??**

### Expected behavior

```console
That they should be present.
```

### Actual behavior

```console
# Get-ControlPanelItem
Get-ControlPanelItem: The term 'Get-ControlPanelItem' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

# Show-ControlPanelItem
Show-ControlPanelItem: The term 'Show-ControlPanelItem' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```powershell
irrelevant
```

**Comment by SeeminglyScience** [comment]
> MS documentation has both [Get-ControlPanelItem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-controlpanelitem?view=powershell-5.1) and [Show-ControlPanelItem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/show-controlpanelitem?view=powershell-5.1), but then say its been removed from later pwsh, [here](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7).

That's correct, they have been removed. The two help documents are only present for Windows PowerShell (v5.1)

**Comment by eabase** [comment]
@SeeminglyScience 

> That's correct, they have been removed. The two help documents are only present for Windows PowerShell (v5.1)

There's little point in just repeating what i just stated. Clearly I am asking what you have (or are planning) to replace those with? 

Or if MS is just going to continue enjoying removing random and highly useful commandlets every time they decide to update powershell?

**Comment by SeeminglyScience** [comment]
If you have a compelling use case for them I'd suggest adding it to #11732. You're the first to request them, and the first I've personally seen to find them useful so a good use case would be helpful for prioritization.

**Comment by mklement0** [comment]
The pragmatic _workaround_ (with limitations with respect to type fidelity) is to call via the Windows PowerShell CLI, `powershell.exe`; e.g.:

```powershell
powershell -NoProfile { Get-ControlPanelItem region }

powershell -NoProfile { Show-ControlPanelItem region }
```

---

Using the [Windows PowerShell Compatibility feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility) one would expect the following to work too, but _it doesn't_, as of v7..3.0:

```powershell
Import-Module  Microsoft.PowerShell.Management -UseWindowsPowerShell -Cmdlet *-ControlPanelItem
```

There are two problems:

* Seemingly, despite the use of `-Cmdlet` to _selectively_ import, a (benign, but noisy) attempt to import _all_ cmdlets is made nonetheless - this seems like a bug in its own right.

* After importing, running ` Get-ControlPanelItem Region`, for instance, reports the following error:

```none
Get-ControlPanelItem: Unable to cast COM object of type 'System.__ComObject' to interface type 'Shell32.Shell'.
This operation failed because the QueryInterface call on the COM component 
for the interface with IID '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error:
No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
```

**Comment by eabase** [comment]
@SeeminglyScience 
> You're the first to request them, and the first I've personally seen to find them useful

Let me just give you a common UX flow. 

*I want to do X, so I go to google and type in `How to do X`, and you end up looking at the MS docs for doing just that. So you open pwsh only to discover you're missing something. Maybe a module install. Ok so you find out what module you need, so you google that, and again end up on MS docs pages. You try to install it, and when it doesn't work, you go WTF! So you go back to google some more, just to find out in some obscure place that the function have been removed, and no reason stated.*

**This happens a lot!**

That said, I completely understand my possibly fringe case, but i doubt I'm the only one, as someone actually bothered to code this up at some point, and many other make blog posts about it..

**Comment by SeeminglyScience** [comment]
> there should be a BIG red flag on anything that has been removed, (and on every page) and with a good reason why.

I think that's a fair suggestion. I've opened MicrosoftDocs/PowerShell-Docs#9502

> That said, I completely understand my possibly fringe case, but i doubt I'm the only one, as someone actually bothered to code this up at some point, and many other make blog posts about it..

I can only speculate, but some commands were designed in a vacuum before PowerShell was open sourced. That seems like the type of thing were folks were asking for more ways to control things that can only be configured via the control panel.

Unfortunately, those commands only list the *top level* control panel categories (and none of the newer "settings" menus) and let you launch the UI of them. It *might* save you from having to learn what `.cpl` to type into the run box but that's the best use case I can come up with personally.
