### ISSUE TITLE
[Regression] Can't import Security module when calling PowerShell from Python

### ISSUE THREAD

**Issue by zurcher** [PowerShell/PowerShell#18681]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a python script that runs a .ps1 file which includes commands from the Microsoft.PowerShell.Security module. Starting with 7.3.0, these commands fail to import during script execution. This can be reproduced from a PowerShell window:

`python -c "import subprocess; subprocess.Popen('powershell -command Get-ExecutionPolicy')"`

OR

`python -c "import subprocess; subprocess.Popen('powershell -command Import-Module Microsoft.PowerShell.Security')"`

### Expected behavior

```console
PS C:\> python -c "import subprocess; subprocess.Popen('powershell -command Get-ExecutionPolicy')"
PS C:\> Restricted
PS C:\> python -c "import subprocess; subprocess.Popen('powershell -command Import-Module Microsoft.PowerShell.Security')"
PS C:\>
```

### Actual behavior

```console
PS C:\> python -c "import subprocess; subprocess.Popen('powershell -command Get-ExecutionPolicy')"
PS C:\> Get-ExecutionPolicy : The 'Get-ExecutionPolicy' command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded. For more
information, run 'Import-Module Microsoft.PowerShell.Security'.
At line:1 char:1
+ Get-ExecutionPolicy
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ExecutionPolicy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule


PS C:\> python -c "import subprocess; subprocess.Popen('powershell -command Import-Module Microsoft.PowerShell.Security')"
PS C:\> Import-Module : The following error occurred while loading the extended type data file: Error in TypeData "System.Security.AccessControl.ObjectSecurity": The
member AuditToString is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member AccessToString is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Sddl is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Access is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Group is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Owner is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Path is already present.
At line:1 char:1
+ Import-Module Microsoft.PowerShell.Security
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> python --version
Python 3.10.6
```

**Comment by zurcher** [comment]
Following [this comment from the PowerShell VSCode extension chat,](https://gitter.im/PowerShell/vscode-powershell?at=6371fd7a2cb6570240282b05) I found that the behavior was resolved by commenting out the "TypesToProcess" line from [Microsoft.PowerShell.Security.psd1](https://github.com/PowerShell/PowerShell/blob/2051c5f72bf53ec4d049c30c19dd1d69d4d847cc/src/Modules/Windows/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1#L16)

This does not occur with PowerShell 7.2.7.

**Comment by jborean93** [comment]
I believe this is a duplicate of https://github.com/PowerShell/PowerShell/issues/18530 but I'm not 100% sure. The problem is you start Python from PowerShell 7.3 which inherits the PSModulePath env var and that Python process then spawns Windows PowerShell with that inherited env var. it will try to import `Microsoft.PowerShell.Security` that is provided by PowerShell 7.3.0 when it should be using what Windows PowerShell ships with.

**Comment by SteveL-MSFT** [comment]
Yes, this looks like a dupe of #18530, the workaround suggested here https://github.com/PowerShell/PowerShell/issues/18530#issuecomment-1325691850 should work for you

**Comment by zurcher** [comment]
I'm hitting this bug in a long-term product support codebase and probably can't check in this workaround. I also suspect we'll see more reports of this issue as more people move to 7.3, and the error message gives no easy indication of what the problem is.

If `pwsh` already knows how to rebuild `PSModulePath`, could the `pwsh -> powershell.exe` special-case be applied to all executable calls?

**Comment by pcarnella** [comment]
I'm having the same problem after upgrading from 7.2 to 7.3 inside an ASP.Net Core app.  C# hosting the PowerShell SDK: 

PackageReference Include="Microsoft.PowerShell.SDK" Version="7.3.0"

The end-user sees this error:

ConvertTo-SecureString : The 'ConvertTo-SecureString' command was found in the module 'Microsoft.PowerShell.Security', 
but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'.
At C:\PSWeb\wwwroot\Scripts\OpenFiles.ps1:15 char:23
+     $SecurePassword = ConvertTo-SecureString $Password -AsPlainText - ...
+                       ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConvertTo-SecureString:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
    
This shows in the transcription log during the error:

Command start time: 20221213105815
**********************
PS>TerminatingError(Import-Module): "The following error occurred while loading the extended type data file: Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member AuditToString is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member AccessToString is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Sddl is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Access is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Group is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Owner is already present.
Error in TypeData "System.Security.AccessControl.ObjectSecurity": The member Path is already present.
"
>> TerminatingError(): "The 'ConvertTo-SecureString' command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'."
