### ISSUE TITLE
Comment-Based Help ".LINK" Section Duplicates Lines In Some Scenarios

### ISSUE THREAD

**Issue by Sekers** [PowerShell/PowerShell#18716]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In some scenarios on PowerShell 7.3, when using Get-Help [FunctionName], links are duplicated in the related links section. I've noticed that this only seems to happen if there is more than one line in the .LINK section.

**This will reproduce it:**
```
function ExampleFunctionDuplicateLink {
    <#
        .LINK
        http://google.com/
        Line 2
    #>

    # No Code
}
Get-Help ExampleFunctionDuplicateLink
```

**Output:**
```
RELATED LINKS
    http://google.com/
    Line 2
    http://google.com/
    Line 2
```

**Removing the single forward slash from the first line (after google.com) will have the output go back to normal:**
```
function ExampleFunctionDuplicateLink {
    <#
        .LINK
        http://google.com
        Line 2
    #>

    # No Code
}
Get-Help ExampleFunctionDuplicateLink
```

**Output:**
```
RELATED LINKS
    http://google.com
    Line 2
```

### Expected behavior

```console
RELATED LINKS
    http://google.com
    Line 2
```

### Actual behavior

```console
RELATED LINKS
    http://google.com/
    Line 2
    http://google.com/
    Line 2
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
@Sekers - thank you for reporting this. Let me add @sdwheeler and we will investigate.

**Comment by sdwheeler** [comment]
Adding @adityapatwardhan too
