### ISSUE TITLE
Get-Command with aliases: .Parameters collection does not include dynamic parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18714]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
# To avoid an unrelated bug (#18715), make sure that Get-ChildItem was referenced at least once in this session.
$null = Get-ChildItem -? 

# Compare the parameter name reported via Get-ChildItem vs. via alias gci
# Be sure to call this from a *file-system* location.
Compare-Object @((Get-Command Get-ChildItem).Parameters.Keys) @((Get-Command gci).Parameters.Keys)
```

See also: 
* #18715

### Expected behavior

No output (the same set of parameters should be reported by both `Get-Command` calls).

### Actual behavior

```console
InputObject   SideIndicator
-----------   -------------
Attributes    <=
FollowSymlink <=
Directory     <=
File          <=
Hidden        <=
ReadOnly      <=
System        <=
```

That is, all _dynamic_ parameters are missing from what `Get-Command gci).Parameters` reported.

### Environment data

```powershell
PowerShell Core 7.3.0
```

**Comment by kilasuit** [comment]
I get the following output in 2 different sessions (regardless of calling GCI or not) on a machine where I have previously used 7.3.0 & think these issues are due to the module command cache perhaps not having been built yet.


![image](https://user-images.githubusercontent.com/6355225/205418112-9879f7c5-b0ff-4948-89b9-637b20c4c0c6.png)

**Comment by mklement0** [comment]
Thanks, @kilasuit,  the way I constructed my sample command serendipitously bypassed #18715, but if you reverse the `Compare-Object` operands you'll run into it:

```powershell
# !! ERROR: "Cannot bind argument to parameter 'ReferenceObject' because it is null."
pwsh -nop { Compare-Object @((Get-Command gci).Parameters.Keys) @((Get-Command Get-ChildItem).Parameters.Keys) }
```

Adding a delay doesn't make a difference:

```powershell
# !! DITTO
pwsh -nop { 1..10 | % { Start-Sleep 1}; Compare-Object @((Get-Command gci).Parameters.Keys) @((Get-Command Get-ChildItem).Parameters.Keys) }
```

Therefore, it doesn't appear to be a matter of _timing_: having referenced `Get-ChildItem` explicitly in a session is a prerequisite, and is enough to _instantly_ make `(Get-Command gci).Parameters` return (the buggy) results.

**Comment by kilasuit** [comment]
I don't think you are right here as technically an alias has no parameters so you are getting the benefit of the engine knowing that you want to be lazy and use the alias in place of the full command name to give you access to it's parameters.

therefore the more that I think on this I think that this all works as it should

**Comment by mklement0** [comment]
An alias is just that: _another name_ for an existing command, it stands to reason that it reports the _latter's_ parameters, which it _mostly_ does:

There is _no_ justification either for the behavior reported here or the one in #18715. - both are unequivocally _bugs_.

**Comment by kilasuit** [comment]
Question really becomes

> Should we expose parameters of aliased commands in this way so that `(Get-Command gci).Parameters` acts like `(Get-Command Get-ChildItem).Parameters`

To which I think yes we should but should also place reminders that aliases can be overridden (as can commands) and that if you want to be certain you should be using the fully qualified command name. I also don't think this goes far enough and would like to be able to version pin as well. As I raised in [this issue](https://github.com/PowerShell/PowerShell/issues/8949) ages ago
