### ISSUE TITLE
New-SmbGlobalMapping creates mappings that do not handle DFS links correctly

### ISSUE THREAD

**Issue by braveness23** [PowerShell/PowerShell#18733]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a mapping with New-SmbGlobalMapping to \\server\share where share is a DFS namespace root

New-SmbGlobalMapping -LocalPath Z: -RemotePath \\server\share

Attempt any file operation on a subdirectory that is a DFS link.  For example, attempt to list the children of Target-1 where Target-1 is a DFS link.

Get-ChildItem Z:\Target-1

### Expected behavior

```console
Get-ChildItem Z:\Target-1\


    Directory: Z:\Target-1


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         12/1/2022   8:37 AM                New folder
```

### Actual behavior

```console
Get-ChildItem Z:\Target-1\
Get-ChildItem : The network location cannot be reached. For information about network troubleshooting, see Windows
Help.
At line:1 char:1
+ Get-ChildItem Z:\Target-1\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (Z:\Target-1\:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.859
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.859
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@braveness23 The repository is only for pwsh, not for Windows PowerShell. Also the New-SmbGlobalMapping cmdlet is not in the repository. You should use Windows Feedback tool to report the issue or other MSFT channels.
