### ISSUE TITLE
Operator value tab completion should also handle predefined Cim values

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#18754]
### Summary of the new feature / enhancement

Currently we can tab complete Enum values like this: `Get-Module | where {$_.AccessMode -eq <Tab>` (Only in the daily builds for now).
This should be extended to also work with cim class properties with predefined values like "OfflineReason" in "MSFT_Disk" so this: `Get-Disk | where {$_.OfflineReason -eq <Tab>`  would complete to the numbers 1-7 and the tooltip would show what each number means.  
It should also work with the Enums generated by CDXML modules so scenarios like this: `Get-NetAdapter | where {$_.MediaConnectState -eq <Tab>}` can tab complete to those enum values.

Remember to also add this for the native argument completer for `Where-Object` so this: `Get-NetAdapter | Where MediaConnectState -eq <Tab>` also works.

**Comment by theJasonHelmick** [comment]
Thank you @MartinGC94 for reporting this.  The Working Group agrees that this is great functionality to include.  The working group recommends that this be considered in development with the Cim/Wincompat changes for 7.4. We are concerned that with the change to Wincompat, the tab completion effort may be difficult to implement.
