### ISSUE TITLE
Add Centos 6 support (GLIBC 2.12)

### ISSUE THREAD

**Issue by agonzalezm** [PowerShell/PowerShell#1876]
I installed centos7 rpm on Centos 6 machine but it will not run because it requires a higher glibc 3.4 library. Is it possible if you add support for Centos6 as lot of linux installations are based on that yet?

[root@localhost ~]# powershell
powershell: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by powershell)
powershell: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.5' not found (required by powershell)
powershell: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by powershell)
powershell: /usr/lib64/libstdc++.so.6: version`GLIBCXX_3.4.15' not found (required by powershell)

**Comment by andschwa** [comment]
We would love to do this, but we're tied to our language, .NET Core, which currently supports [these platforms](https://github.com/dotnet/corefx#build--test-status). This does not yet include CentOS 6.

**Comment by agonzalezm** [comment]
I will open issue on coreclr to see if they can support. 

Mono runs on centos6, could you add the option to also run powershell on mono instead of requiring .net core? as i understand mono and .net core will support same netstandard version apis so they should be compatible.

**Comment by agonzalezm** [comment]
On CoreCLR they said centos6 has old libraries that will not work so they are not going to support it.

Would be possible if you have a powershell package that runs on top of mono instead of coreclr? or would this be a request for mono team so they add powershell as a supported language?

**Comment by andschwa** [comment]
Just to cross-reference: https://github.com/dotnet/coreclr/issues/6792

Thanks for investigating @agonzalezm

**Comment by joeyaiello** [comment]
This is blocked on .NET Core supporting CentOS 6.

**Comment by agonzalezm** [comment]
Looks like .net core unblocked this and now is possible to use .net core 2.0 in centos6.

https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

It is possible you build powershell core rpm for centos6 with net core and prequisites?

**Comment by agonzalezm** [comment]
@joeyaiello @andschwa do you think is possible to unblock this and assign milestone? to build powershell core with net core 2.0.x and package it with the 2 libs versions (ICU and CURL) that are needed for rhel/centos 6?

**Comment by agonzalezm** [comment]
any update on this? can you create a powershell with target rhel-x64 that supports running on centos 6?

https://github.com/dotnet/cli/issues/9375#issuecomment-393843956

**Comment by iSazonov** [comment]
.Net Core added support CentOs 6 (to address feedbacks) with many limitations as non-portable (!)solution. I'm afraid that even if we do this 
https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md
we will get unpredictable limitations in functionality. Also it is necessary to remember that SSH remoting should work, but most likely it will not.
I think we should close this.
/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Agree
