### ISSUE TITLE
Console Host redraws the current line after every character

### ISSUE THREAD

**Issue by DHowett** [PowerShell/PowerShell#1877]
## Steps to reproduce

Launch powershell. Type a command.
Observe that the cursor flickers left and right, back and forth, for every character you type.
This may require a terminal with slower refresh.
## Expected behavior

The input is only redrawn when it becomes necessary.
## Actual behavior

The input is redrawn for every input character.

I profiled this, and found that for the input (and output):

```
PS > powershell redraws a lot
```

... which is a paltry few bytes, we emit 52,501 bytes of ANSI escape sequences repositioning the cursor, drawing colours, repositioning the cursor some more, etc.
## Environment data

``` powershell
root@f49460ec9455:/# powershell -c '$PSVersionTable'

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by DHowett** [comment]
Thought: perhaps this is to mimic the Windows console's support for drawing characters at any coordinates (_without cursor moves_)? It looks like we could be trying to do the same thing, but because it's being used to such a high degree we're emitting a veritable boatload of CSIs.

It's especially noticeable over remote links with nonzero latency.

**Comment by lzybkr** [comment]
The current design exists to keep things simple - e.g. the color of text previously entered *might* change after typing a character.  The current design also performs much better on Windows than the simple alternatives.

At any rate, thanks for the report, this is a known issue that we definitely plan on addressing.

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#469

**Comment by masaeedu** [comment]
@lzybkr Is there a workaround for this? Still seeing this in the latest container published on docker. I don't know if it's extra noticeable for me because my machine sucks, but it makes it very difficult to do any useful work.

**Comment by masaeedu** [comment]
Nvm, just found it. For posterity:

```powershell
Remove-Module -Name PSReadline
```

**Comment by iSazonov** [comment]
@masaeedu Thanks for your report! Please open Issue about the session crash.

**Comment by masaeedu** [comment]
@iSazonov Is this another PSReadline bug or should I open it for this repo?

**Comment by iSazonov** [comment]
@masaeedu If the crash happens without PSReadline the Issue is for this repo.

**Comment by masaeedu** [comment]
@iSazonov The crash happens specifically when you *remove* PSReadLine from a running session, and I suspect the issue is that PSReadLine takes over some hooks for navigating history that don't get reset to their original state when you unload the module. In other words PSReadLine probably isn't designed to be `Remove-Module`d, which is fine because removing it isn't a common use case.

You'd have to start up powershell without PSReadLine loaded at all to determine whether the problem is independent of PSReadLine, and I don't know how to do that.

**Comment by iSazonov** [comment]
@masaeedu I cannot repo this. So you can open Issue in this repo. Later we can move it in PSReadLine repo.
