### ISSUE TITLE
Add description to help text of all commandlets

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#18772]
### Summary of the new feature / enhancement

Please add the 1st paragraph of MS document description, **to all commandlets**.

For example: 
```powershell
 $ help Get-Module

NAME
    Get-Module

SYNTAX
    Get-Module [[-Name] <string[]>] [-FullyQualifiedName <ModuleSpecification[]>] [-All] [<CommonParameters>]
...
```

This info is useless, if you don't already know what the command does. 

So add the 1st paragraph of the `Description` from your document [page](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/Get-Module?view=powershell-7.3&viewFallbackFrom=powershell-7):

> Description
> 
> The Get-Module cmdlet lists the PowerShell modules that have been imported, or that can be imported, into a PowerShell session. Without parameters, Get-Module gets modules that have been imported into the current session. The ListAvailable parameter is used to list the modules that are available to be imported from the paths specified in the PSModulePath environment variable ($env:PSModulePath).

**Comment by mklement0** [comment]
It sounds like you haven't yet downloaded offline help content, which you can do with [`Update-Help`](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/update-help).

**Comment by eabase** [comment]
@mklement0  
LoL! I had no idea this was necessary. 
I would have expected that all help files would be also be updated with windows update.

Anyway, I get a funny error message:
```powershell
$ Update-Help -UICulture en-US
Update-Help: Failed to update Help for the module(s) 
'ConfigDefenderPerformance, PSReadline, WindowsUpdateProvider' with UI culture(s) {en-US} : 
One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

**Comment by mklement0** [comment]
Not sure about `ConfigDefenderPerformance` and `WindowsUpdateProvider`, but I think there's a fix for `PSReadLine` (note that the error message uses a _lowercase_ L): https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

**Comment by eabase** [comment]
Indeed I no longer get that message, but I just noticed my pwsh is running PRL `2.2.0-beta5`, even though the `2.2.6` is installed.

```powershell
 $ Get-Module -ListAvailable "PSRead*"

    Directory: C:\Users\xxxx\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.2.0      beta5      PSReadLine
Script     2.1.0      rc1        PSReadLine

    Directory: C:\program files\powershell\7\Modules

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.2.6                 PSReadLine

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.1.0      rc1        PSReadLine
Script     2.0.4                 PSReadLine
Script     2.0.0      beta2      PSReadLine

```

I assume all those old version are there because of need to be compatible with old powershell 5.1 and below?
Any idea ,what can/should be removed and what should be kept?

**Comment by mklement0** [comment]
2.2.6 works with Windows PowerShell v5.1 too, so I suggest getting rid of everything else, in both editions.

Unless you've already done so in the user scope (which wouldn't show up from PS Core), you'll need to install 2.2.6 from Windows PowerShell (either in the user or the machine scope).

**Comment by eabase** [comment]
Great! Thank you.
 
I managed to remove some versions with:  `Uninstall-Module PSReadline -AllowPrerelease -RequiredVersion "2.2.0-beta5" -Force -Verbose`, but the other remain in: `C:\Program Files\WindowsPowerShell\Modules`....
What's the more proper way to remove these, other than just removing the folders of each?

**Comment by mklement0** [comment]
Simply removing the folders is fine.

`Uninstall-Module` by design only works on modules that were installed with `Install-Module`.
