### ISSUE TITLE
The colors for directories output look super wierd since Powershell 7.3 update

### ISSUE THREAD

**Issue by HymanZHAN** [PowerShell/PowerShell#18778]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I like the new effort of using ANSI formatting in `$PSStyle`. However, I don't think the outcome is ideal. At least not in the case of `FileInfo.Directory`.

### Expected behavior

```console
I should see the outcome of `ls` clearly. There should be enough contrast, and texts should be easy to read.
```

### Actual behavior

```console
The current style of having a blue background for directories is hard to read and looks awful.
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Current:

![image](https://user-images.githubusercontent.com/26806995/207308641-6c252907-5562-419c-9f0d-15e5d6e675f2.png)

What I think was intended:

![image](https://user-images.githubusercontent.com/26806995/207308879-6ac21ade-e1be-4670-9c4b-d82b536cac1d.png)

I am using the One Half Dark theme that comes with Windows Terminal.

**Comment by HymanZHAN** [comment]
Related issue: https://github.com/PowerShell/PowerShell/issues/18550

**Comment by petrsapak** [comment]
I'm experiencing the same issue in Windows Terminal 1.15.3466.0, One Half Dark (other color schemes are messed the same way) color scheme and Powershell 7.3.0 & 7.3.1. 
As a workaround I tried this: 

- I changed the color "Blue" to the same color as "Background" which fixed the issue, but caused some color issues when using posh-git module.
- I installed [PSColor](https://github.com/Davlind/PSColor) module, which fixed the issue, making my get-childitem calls look like this:
![image](https://user-images.githubusercontent.com/9948892/207796059-096b363b-46a5-43ea-b0e2-3ef0c1ada90c.png)

**Comment by HymanZHAN** [comment]
@petrsapak Thanks for your input~ Yeah, I already had my workaround in my `$PROFILE`, but I wish there would be an upstream fix.

As a side note, the full list of colors can be listed by `$PSStyle`:

![image](https://user-images.githubusercontent.com/26806995/208001348-647b8588-5280-408f-b4a0-40902a36cfee.png)

And you may set the style for `FileInfo.Directory` directly: 
```
$PSStyle.FileInfo.Directory = "`e[34m"
```
Hopefully, this would not cause issues on posh-git's side. (I also use posh-git, but I don't use its prompt. I am using starship instead.)

Another side note: The exactly identical issue occurred a few years ago on WSL1 using Ubuntu (18.04, I believe). Same colored background for directory listing, with low contrast and eyesore aesthetics. I hope this issue gets fixed soon.

**Comment by robinmalik** [comment]
Broke retrowave for me:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/8790561/211062470-1976e304-4322-48af-8c4f-b7ac8286f4fe.png">

**Comment by 9Rune5** [comment]
> * I installed [PSColor](https://github.com/Davlind/PSColor) module, which fixed the issue, making my get-childitem calls look like this:

I'd like to recommend https://github.com/DHowett/DirColors instead. Especially if you're using MIcrosoft Terminal.

**Comment by reeddunkle** [comment]
In case it helps someone else: the color formatting can be combined with bold formatting (for example):

```ps
$PSStyle.FileInfo.Directory = "`e[96;1m"
# Foreground.BrightCyan + Bold
```

There are also custom RGB definitions: https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting

**Comment by kilasuit** [comment]
This looks much better in 7.4.2 (tested without my profile as something in it is breaking this output)

![image](https://github.com/PowerShell/PowerShell/assets/6355225/86b59f48-2edc-4ba6-9f5b-66280efd73ec)

**Comment by theJasonHelmick** [comment]
@HymanZHAN -- Thank you for this issue.  The default colors were chosen for accessibility based on a black background and default theme.  Terminal themes may affect the colors and how they are displayed. This doc may help: https://learn.microsoft.com/powershell/scripting/learn/shell/using-light-theme
