### ISSUE TITLE
System.Management.Automation 7.3.1 depends on a missing nuget package

### ISSUE THREAD

**Issue by daviddenis-stx** [PowerShell/PowerShell#18782]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Building a project dependent on System.Management.Automation 7.3.1 will complain about missing System.Runtime.CompilerServices 7.0.0-preview.3.22119.2 (which is not pushed to nuget.org at the time of writing this, only preview.2 is). It's perhaps transient ?

A quick workaround is to add https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v2 to your NuGet.Config

### Expected behavior

```console
Should find the dependant System.Runtime.CompilerServices.Unsafe package, and build correctly
```

### Actual behavior

```console
error NU1102: Unable to find package System.Runtime.CompilerServices.Unsafe with version (>= 7.0.0-preview.3.22119.2)
error NU1102:   - Found 58 version(s) in nuget-org [ Nearest version: 7.0.0-preview.2.22152.2 ]
```

### Environment data

```powershell
7.3.1
```

**Comment by nightroman** [comment]
Same here.

**Comment by TravisEz13** [comment]
Until we have a better fix, you can work around this by adding the following line to the `.csproj` that references the SDK or SMA.

```xml
<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="7.0.0-preview.2.22152.2" NoWarn="NU1605" />
```

**Comment by jak-hammond** [comment]
I came across [this KB article](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/unsafe-package) stating that no new versions of this package will be created, so will that ultimately lead to it's removal as a dependency here and be covered by the main framework?

**Comment by adityapatwardhan** [comment]
@jak-hammond thanks for the link to the KB article. I have created PR to remove the dependency.

**Comment by nozakikouji** [comment]
何度インストールしてもインストールの催促が出る
パスワードはマイクロソフトと2022.07.17に変更要求に従って変更したパスワード
ユーザー名は変わらずこの私だ野﨑弘二で変わらぬこの名が使えぬとはどういう事だ
