### ISSUE TITLE
Bind error when using MSMQ module

### ISSUE THREAD

**Issue by SirMrDexter** [PowerShell/PowerShell#18783]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- Ensure MSMQ feature is installed
- Create a new queue
- Run `Remove-MsmqQueue -InputObject @(Get-MsmqQueue -Name "new-queue-name")`

### Expected behavior

```console
Queue should be deleted
```

### Actual behavior

```console
Remove-MsmqQueue: Cannot bind parameter 'InputObject'. Cannot convert the "private$\new-queue-name" value of type "Deserialized.Microsoft.Msmq.PowerShell.Commands.MessageQueue" to type "Microsoft.Msmq.PowerShell.Commands.MessageQueue".
```

### Error details

```console
The same command runs fine when you run it from PowerShell 5
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Screenshot 2022-12-14 112402](https://user-images.githubusercontent.com/803034/207474483-9c692f8a-a775-49f6-a4bb-0d1d8cd0052f.jpg)
![Screenshot 2022-12-14 112417](https://user-images.githubusercontent.com/803034/207474497-6dfb2255-3382-4635-bab0-920198a862a8.jpg)

**Comment by jborean93** [comment]
This cmdlet is part of a module that isn't shipped with PowerShell but is a Windows component. Unfortunately the module has not been updated to run in the newer dotnet versions that PowerShell 7 uses so PowerShell loads the module in a remote Windows PowerShell (5.1) process and serializes the input and output data. Unfortunately that means output from `Get-MsmqQueue` is going to be a deserialized object and then cannot be used in subsequent cmdlets like `Remove-MsmqQueue`.

As this is not something included in this repository you'll need to try and contact the MS team who maintain this component (maybe through Microsoft Answers) to see if they can update it so it supports newer dotnet versions and can be loaded natively.

A workaround is to run all your code in the remote session avoiding the serialization problem

```powershell
$s = New-PSSession -UseWindowsPowerShell
Invoke-Command -Session $s -ScriptBlock {
    Remove-MsmqQueue -InputObject @(Get-MsmQueue -Name "asdasd")
}
$s | Remove-PSSession
```

**Comment by SirMrDexter** [comment]
Have reported it to Microsoft Answers as recommended.
https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/issue-with-msmq-powershell-module-in-ps7/75d961cb-87e0-4dee-bca9-d1414eded0df

Have also tested the suggested workaround and it works.

Will close this issue.

Thanks @jborean93
