### ISSUE TITLE
Misleading error message when parsing `Configuration` keyword on ARM processor

### ISSUE THREAD

**Issue by ajhall** [PowerShell/PowerShell#18781]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I work on PowerShell DSC files on an ARM-based Mac, the PowerShell extension for VS Code claims that I'm in constrained language mode and warns that I can't use the `Configuration` keyword.

To reproduce:
1. Use an ARM-based Mac.
2. Ensure Constrained Language Mode is disabled.
```powershell
PS> $ExecutionContext.SessionState.LanguageMode
FullLanguage
```
3. Parse a script containing the `Configuration` keyword.
```powershell
$errors = $null
[System.Management.Automation.PSParser]::Tokenize("Configuration MyConfig {}",[ref]$errors)
```
4. View the resulting errors.
```
PS> $errors

Token                                Message
-----                                -------
System.Management.Automation.PSToken Configuration keyword is not allowed in constrainedLanguage mode.
```

### Expected behavior

The `Configuration` keyword should be supported, or the error message should accurately state why it's not supported.

### Actual behavior

The error message claims constrainedLanguage mode is enabled, which isn't true.

I believe this is caused by this block of code, which checks that either:
1. ConstrainedLanguage mode is enabled, or
2. The processor type is ARM.

https://github.com/PowerShell/PowerShell/blob/c3a080caf9c46c2a742b032e4a85d05c21129fe4/src/System.Management.Automation/engine/parser/Parser.cs#L2987-L2995

It uses the same error message ("Configuration keyword is not allowed in constrainedLanguage mode.") even if the real issue is that I'm using an ARM processor.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

From the Visual Studio Code PowerShell extension:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1380292/207406023-aa12111f-9dd5-4f06-900e-883839e80939.png">

**Comment by JamesWTruher** [comment]
@wg-engine
This looks like a bug, we'll investigate the proper fix. Not sure if it's just an additional error message, but we need to more deeply investigate whether configuration on arm is supported in this context.

**Comment by SteveL-MSFT** [comment]
We don't have an ARM64 specific build of libmi which is used to generate the mof from a `configuration` file.  So it seems we should split the check into two and have an appropriate error message regarding ARM64.  Note that on osx, if you still currently need this capability, you can use the x64 built version of PS7 and through osx emulation have it work.

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine 
agrees that we should have error messages appropriate for the condition.

**Comment by TravisEz13** [comment]
Tests need to be fixed if this issues is fixed:  https://github.com/PowerShell/PowerShell/pull/19040/files#diff-393e1fa171a673ad5e5c3c1f3700ad03d32d46031ffcf72e4eaac1a7c7c46579R2001

**Comment by bgshacklett** [comment]
PowerShell scripts and configurations may be written on a Mac with Apple silicon for machines which _do_ support DSC. In these cases, the language server which provides assistance in editors uses the pwsh parser to read and validate the code, though it is not actually being executed (one would hope!).

In addition to splitting out the two error scenarios above, it seems that they should really be handled at a higher level than the Parser. Perhaps a warning makes sense at the parser level, but an actual error should only be thrown when we get into a state where the activity is truly unsupported (i.e.: when the Configuration block is executed).

**Comment by iSazonov** [comment]
@StevenBucher98 Why do we close issues with WG conclusion that it is a bug?

**Comment by kilasuit** [comment]
> @StevenBucher98 Why do we close issues with WG conclusion that it is a bug?

@iSazonov - this is an unfortunate after effect of the recent changes to the bot policies and I have raised #21018 to stop this going forward when there is the  `Up-For-Grabs` label applied to an issue
