### ISSUE TITLE
Support Custom Host Method Hooks

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#18796]
### Summary of the new feature / enhancement

As a module developer I would like to create a module that can enhance the way that PowerShell works in the standard console/terminal context. There are a few mechanisms in the PSHost that make some actions hard to customise and are limited to what PowerShell includes in box. For example I feel like the following 4 calls are ripe for customisation

* [PromptForCredential](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.promptforcredential?view=powershellsdk-7.2.0) - Can utilize a more modern Windows prompt (or use some Linux/macOS keyring UI) like https://gist.github.com/jborean93/586382429f869bdc1415d0ccb90db2e7
* [Prompt](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.prompt?view=powershellsdk-7.2.0)
* [PromptForChoice](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.promptforchoice?view=powershellsdk-7.2.0) (and the choices overload)
* [WriteProgress](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.host.pshostuserinterface.writeprogress?view=powershellsdk-7.2.0)

The builtin choice mechanisms are currently rudimentary with them looking like

![Builtin Choice](https://s9.gifyu.com/images/choice-builtin.gif)

and for multiple choice selection

![Builtin Choices](https://s9.gifyu.com/images/choices-builtin.gif)

Being able to use something like [Spectre.Console](https://spectreconsole.net/) you could make them much more usable like

![PSGhost Choice](https://s9.gifyu.com/images/choice-psghost.gif)

and for multiple choice selection

![PSGhost Choices](https://s9.gifyu.com/images/choices-psghost.gif)

If someone doesn't like the currently hardcoded selection of progress styles, this would allow someone to do their own like

![PSGhost Progress Percentage](https://s9.gifyu.com/images/prog-per-psghost.gif)

Currently the only way to customise these is to start a new runspace with a custom host. This is not ideal as

* You need to implement all the PSHost and PSHostUserInterface methods, not just the ones you want
* You can't push a local runspace onto the stack - https://github.com/PowerShell/PowerShell/issues/5735
* Even if you could, you now loose all the context of the runspace you were in

By opening up customisation of the current PSHost you allow module authors to do whatever they wish and provide their own spin.

### Proposed technical implementation details (optional)

I'm not sure on a good way of doing this but I'm hoping this issue can open it up for ideas and suggestions. While we could try and open up the host API to allow a module to push their own PSHost implementation on the stack (like what [PSGhost](https://github.com/jborean93/PSGhost) does). I don't think this is ideal as implementing your own host is not the simplest thing and if a module author only wants to touch the prompt calls they still need to add a shim for the rest.

Potentially we could use the same functionality of the `prompt` function where the default PSHost call will just call that function. There are probably performance implications here so I'm definitely keen to hear other people's thoughts on how we could implement such a thing.

**Comment by iSazonov** [comment]
I agree that the current host looks outdated and that there are many unpleasant limitations.
But I feel that these problems cannot be solved simply by adding hooks. These public interfaces are more likely to be a stopgap to resolving the underlying problems.
I would rather vote for designing and building an alternative host as an experimental feature.

**Comment by SteveL-MSFT** [comment]
I think it makes sense to expose the Host callbacks as extensible and separately Progress rendering as pluggable (so that both could be modules you install from PSGallery, but then need to consider how to register/unregister if you have several installed).  For the Host callbacks, need to consider how this would work with EditorServices.  @jborean93 would you be willing to write-up a proposal?

**Comment by Jaykul** [comment]
For prompting, the ideal thing would be to expose the current functionality as cmdlets in the [ConsoleGuiTools](https://github.com/PowerShell/GraphicalTools/) module, and have the current Host APIs call the cmdlets by their simple names (i.e. not module-qualified). As long as the command resolution respected the normal module import order, that would let us override the prompt cmdlets by just importing a module that clobbered the commands. And going forward, you'd be able to improve on the module, and even add new prompt options -- scripters would naturally migrate away from the Host APIs...

I think progress needs to be a separate conversation, because it's a _stream_, and has major performance considerations...

**Comment by jborean93** [comment]
> would you be willing to write-up a proposal?

I can certainly look into it, would take some time to figure out the various ways this could be done and trying to weigh up the pros and cons.

> For prompting, the ideal thing would be to expose the current functionality as cmdlets in the [ConsoleGuiTools](https://github.com/PowerShell/GraphicalTools/) module, and have the current Host APIs call the cmdlets by their simple names (i.e. not module-qualified)

I'll certainly look into that module, I am concerned around the performance aspect of C# code doing a function lookup for each of these prompts but maybe for things like PromptForChoice or PromptForCredential that's not really too much of a concern.

> And going forward, you'd be able to improve on the module, and even add new prompt options -- scripters would naturally migrate away from the Host APIs...

While a nice idea, the host APIs are nice in that they effectively have a common shim for remote runspaces. I do agree they are quite limited in their functionality but it's nice for things like `Get-Credential` and `$host.UI.PromptForCredential(...)` to work seamlessly.

>  think progress needs to be a separate conversation, because it's a stream, and has major performance considerations...

Agreed, it probably even needs a further extension to how it works as currently it relies on the REPL to be cleared by `prompt` to clear the existing progress output. For PSGhost I had to [hook into the `prompt` function](https://github.com/jborean93/PSGhost/blob/248297410e961d3173d9396125e8137fc53ac129/src/Commands/PSGhost.cs#L83-L85) to tell Spectre's progress output to stop and clear as it was unaffected by the the clearing of the console buffer.

I'll have to ponder it a bit more and consider the options. I'm definitely keen to hear other people's thoughts and ideas on how it could possibly be done.

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine 
We discussed this and we agree this would be a welcome behavioral addition, but we would really need an RFC to work through all the intricacies of the proposal. We also wonder whether this is more an @wg-interactive-console issue, so we've added that working group to get their opinion.
