### ISSUE TITLE
Microsoft store version of Powershell Preview is still on 7.3-preview.rc.1

### ISSUE THREAD

**Issue by ShreyasJejurkar** [PowerShell/PowerShell#18790]
I am using Powershell Preview app installed via Microsoft Store. When I open PowerShell I get a banner saying that there is a new version available, but when I go to the store for updating PowerShell, I don't see any updates. It looks like PowerShell is getting updated to the new version, but the store is still pointing towards or using the old PowerShell version! 

![image](https://user-images.githubusercontent.com/17148381/207553939-8d3c624a-729b-4dad-9386-e1bc9432d9f1.png)

Store version 
![image](https://user-images.githubusercontent.com/17148381/207553994-407b7a27-cbbc-497a-8893-a89c184063d1.png)

So I wanted to know can you guys please release a new update to Microsoft store for Powershell preview app!?

**Comment by 237dmitry** [comment]
This is the latest Preview branch release.

**Comment by CarloToso** [comment]
@iSazonov we can close
