### ISSUE TITLE
Missing Explorer Menus

### ISSUE THREAD

**Issue by dastanmoy96** [PowerShell/PowerShell#18791]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The directory context menu of PowerShell, "Open PowerShell Here" is gone after the latest update.
Version 7.3.0 was installed through Windows Installer Package (.msi), and "Open PowerShell Here" was properly visible.
But it's missing after the Windows Update to version 7.3.1

### Expected behavior

```console
Should show "Open PowerShell Here" in Directory Context Menu
```

### Actual behavior

```console
"Open PowerShell Here" Directory Context Menu is missing
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.22621 Microsoft Windows 11 Home Single Language
```

### Windows update log

```markdown
https://www.mediafire.com/file/d4xkayfk9v34rjf/WindowsUpdate.log/file
```

**Comment by BenMakesGames** [comment]
duplicates:

* https://github.com/PowerShell/PowerShell/issues/18479
* https://github.com/PowerShell/PowerShell/issues/17967
* https://github.com/PowerShell/PowerShell/issues/16886
