### ISSUE TITLE
Master v. Source Depot Branch

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#1880]
Please add info about branches and their use to the ReadMe.md in every branch. If you give me the info, I'll do it, but it needs to be done.

**Comment by juneb** [comment]
Also, we need best-practice contribution guidelines, e.g. using forks, branches, rebase. Do you want a new branch for each PR? 

@TravisEz13, we might want labels to distinguish documentation of this GitHub project v. documentation of PowerShell that's delivered with the installation.

**Comment by vors** [comment]
Relevant documentation is here https://github.com/PowerShell/PowerShell/tree/master/docs/git#understand-branches

There are few leftover branches from our github transition (I.e. source-depot). They will eventually go away. No need to do enemy them separately.

**Comment by juneb** [comment]
I just found the contribution guidelines, too. My mistake. A bit too excited. I'll close this. Thanks!

**Comment by TravisEz13** [comment]
@juneb Product documentation issues are planned to be tracked in https://github.com/PowerShell/PowerShell-Docs
