### ISSUE TITLE
The public System.Management.Automation v7.3.1 nuget references System.Runtime.CompilerServices.Unsafe (>= 7.0.0-preview.3.22119.2) that doesn't exist on nuget.org

### ISSUE THREAD

**Issue by BobbyCannon** [PowerShell/PowerShell#18807]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

v 7.0.0-preview.3.22119.2 of System.Runtime.CompilerServices.Unsafe is not available on nuget.org.

System.Management.Automation v7.3.1 depends on this package.

### Expected behavior

```console
Don't post updates to dependencies that are not available.
```

### Actual behavior

```console
Updates should be able to work.
```

### Environment data

```powershell
it's a nuget issue, not a powershell issue
```

**Comment by iSazonov** [comment]
Thanks! Fixed in #18806.
