### ISSUE TITLE
Removal of depreciated dependency System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by jak-hammond** [PowerShell/PowerShell#18803]
### Summary of the new feature / enhancement

Sorry, I couldn't see a general question template, so feel free to re-classify as necessary.

Relating to the #18782 I came across [this KB article](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/unsafe-package) stating that no new versions of this package will be created, so will that ultimately lead to it's removal as a dependency here and be covered by the main framework?

**Comment by iSazonov** [comment]
@jak-hammond Thanks!
Please add you comment to https://github.com/PowerShell/PowerShell/issues/18782

**Comment by jak-hammond** [comment]
Will do!
