### ISSUE TITLE
ConvertFrom-Json flattens single-item arrays into objects when opening brace of JSON isn't on first line

### ISSUE THREAD

**Issue by Adunaphel** [PowerShell/PowerShell#18804]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using ConvertFrom-Json to convert a JSON file to a PSCUstomObject, I have run into a weird behavior when the JSON's main object doesn't start on line 1, but instead starts either with a blank line, or a comment (In this case I put a comment there to prevent any trim function to strip the newline, but the result is the same whether or not the first line is a comment or just blank, as long as it isn't `{`

Take the following JSON file, test.json in the behavior examples below:
```
// This file contains test data
{
  "testArray": [
    {
      "name": "test"
    }
  ],
  "testArray2": [
    {
      "name": "test2"
    },
    {
      "name": "test3"
    }
  ]
}

```
And process it with ConvertFrom-Json, you'd expect it to be the same as when processing the following file:
```
{
  "testArray": [
    {
      "name": "test"
    }
  ],
  "testArray2": [
    {
      "name": "test2"
    },
    {
      "name": "test3"
    }
  ]
}

```

But in the first case, testArray is represented as a PSCUstomObject, not an array of objects.

### Expected behavior

```console
PS> $testContent = Get-Content test.json | ConvertFrom-Json

PS> $testContent.testArray.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```

### Actual behavior

```console
PS> $testContent = Get-Content test.json | ConvertFrom-Json

PS> $testContent.testArray.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
You're seeing the results of an (unfortunate) heuristic built into `ConvertFrom-Json`, as previously discussed in:

* #12229

To avoid the problem, use `Get-Content -Raw` in order to pass the entire document _as a single string_, which not only avoids the ambiguity, but speeds up your command as well.
