### ISSUE TITLE
Python script started as .\script.py runs in new window

### ISSUE THREAD

**Issue by oldium** [PowerShell/PowerShell#18811]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Tested under Windows Terminal 1.15.3466.0 in Windows 11 22H2 22621.963 in PowerShell 7.3.1 profile with Python 3.11.0 installed. Steps to reproduce:

1. Execute python script directly by specifying its name: `.\script.py`.

script.py:

```python
print("Hello, press ENTER")
input()
```

File association as shown by the Command Prompt (cmd.exe):

```console
C:\Users\work> ftype Python.File
Python.File="C:\WINDOWS\py.exe" "%L" %*
```

When the following is executed directly in the PowerShell prompt, it works fine, i.e. no new window is opened:

1. `C:\WINDOWS\py.exe .\script.py`
2. `C:\Users\work\AppData\Local\Programs\Python\Python311\python.exe .\script.py`

The same `.\script.py` works fine when executed from Command Prompt profile (`cmd.exe`).

### Expected behavior

The script is executed in the same window, i.e. with output:

```console
C:\Users\work\> .\script.py
Hello, press ENTER
```

### Actual behavior

New console window opens with text:

```console
Hello, press ENTER
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by oldium** [comment]
You are my hero, it finally works. I could not find anything mentioning this very crucial information.

**Comment by jeremych1000** [comment]
> Try running `$env:PATHEXT += ';.PY'` first. If that helps, update the persistent definition of `PATHEXT` to include this extension.
> 
> Presence of an extension in `$env:PATHEXT` is seemingly required for an associated console application to run in the current console.

Is it possible to set this permanently?

**Comment by powercode** [comment]
Look at `setx` or 
```
[Environment]::SetEnvironmentVariable

OverloadDefinitions
-------------------
static void SetEnvironmentVariable(string variable, string value)
static void SetEnvironmentVariable(string variable, string value, System.EnvironmentVariableTarget target)
```

The latter overload allows you to pass 'User' or 'Machine' as the last parameter
