### ISSUE TITLE
The scope in the different script blocks of «Switch» are different too

### ISSUE THREAD

**Issue by u20221022** [PowerShell/PowerShell#18816]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
$Private:P = "PP"
$Local:L = "LL"
$Global:G = "GG"
"`$P=$P `$L=$L `$G=$G"
Switch ($AnyValue) {
	{"`$P=$P `$L=$L `$G=$G" | Out-Host; $True} {"`$P=$P `$L=$L `$G=$G"}
}
```

### Expected behavior

```console
$P=PP $L=LL $G=GG
$P=PP $L=LL $G=GG
$P=PP $L=LL $G=GG
```

### Actual behavior

```console
$P=PP $L=LL $G=GG
$P= $L=LL $G=GG
$P=PP $L=LL $G=GG
```

### Environment data

```powershell
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Intriguing: 
 * Indeed, a script block used as a `switch` branch _conditional_ runs in a _child_ scope, whereas an _action_ script block runs _directly in the caller's scope_.

Pragmatically speaking, this will rarely be a problem, given that it is best to avoid operations _with side effects_ in conditionals.

See also:

* #7157

**Comment by u20221022** [comment]
> side effects

Where do you see the side effect?

**Comment by 237dmitry** [comment]
Private option exists to make variable not visible in child scope

```
private: - Specifies that the name is Private and only visible to the current scope.

Note:
private is not a scope. It is an option that changes the visibility of an item outside of the scope where the item is defined.
```

**Comment by u20221022** [comment]
> Private option exists to make variable not visible in child scope

And what?  Why the behaviour is different for the one and SAME operator?

**Comment by mklement0** [comment]
The behavior is different for the - de facto - reasons I've explained.

There are no side effects in _your_ example, but my (implied) point was that - due to PowerShell's dynamic scoping - the fact that the script blocks used as _conditionals_ run in a _child_ scope _usually_ doesn't matter, because such script blocks usually do not attempt to  modify the caller's scope - and generally _shouldn't_.

That said:

* I agree that there's _no_ good reason to treat conditional vs. action script block differently - the issue I linked to essentially makes the same point with respect to other contexts.

* With a _private_ scope defined in the caller's scope, a script block used as a _conditional_ won't see variable defined in that private scope, so the difference does matter in that case.

**Comment by u20221022** [comment]
Is it hoped this bug will be fixed?

**Comment by u20221022** [comment]
> such script blocks usually do not attempt to modify the caller's scope - and generally _shouldn't_

Modifying the caller's scope is easy:
```
# Declaring variables
$Private:P = "PP"
$Local:L = "LL"
$Global:G = "GG"

# Using declared variables
"1: `$P=$P `$L=$L `$G=$G"
Switch (, ("2: `$P=$P `$L=$L `$G=$G" | Out-Host)) {
    {Set-Variable -Name P -Value "pppp" -Scope 1; "3: `$P=$P `$L=$L `$G=$G" | Out-Host; $True} {"4: `$P=$P `$L=$L `$G=$G"}
}
```

1: $P=PP $L=LL $G=GG
2: $P=PP $L=LL $G=GG
3: $P= $L=LL $G=GG
4: $P=pppp $L=LL $G=GG

**Comment by mklement0** [comment]
> Is it hoped this bug will be fixed?

I have no say in that (I'm just a fellow user), but, personally, yes, I think it should be fixed.

> Modifying the caller's scope is easy:

Yes, but cross-scope variable modification is best avoided for conceptual reasons (encapsulation).

**Comment by u20221022** [comment]
Thank you for your moral support.

**Comment by 237dmitry** [comment]
> And what? Why the behaviour is different for the one and SAME operator?

Where are the same operations?

```
# parent scope

switch (# parent scope)
{
    { # child scope }  { # parent scope }
}

# parent scope
```

**Comment by u20221022** [comment]
> Where are the same operations?

Are the words «operator» and «operation» synonymous?  Take a closer look (in https://www.merriam-webster.com/, for example).

**Comment by 237dmitry** [comment]
> Are the words «operator» and «operation» synonymous?

Why do you think that a variable with `private` option should be visible in the child scope? I don't understand this and dictionaries won't help here. There is `about_scopes` help page, study it carefully.

**Comment by u20221022** [comment]
> Why do you think that … in the child scope?

I asking in what the child scope is doing there? The 7th version of PowerShell, and no one fixing this error.  Do not to troll me.

**Comment by 237dmitry** [comment]
> I asking in what the child scope is doing there?

This was always...
![Screenshot 2022-12-18 132037](https://user-images.githubusercontent.com/78153320/208293005-127561a7-3fdd-413e-9530-94c4f4395fb3.png)

**Comment by u20221022** [comment]
What is the black screen? Katsap fascists bombed a power plant?  My eyes do not perceive such pornography.

**Comment by kilasuit** [comment]
@u20221022 please edit that last comment as there's no need for those words at all

**Comment by SteveL-MSFT** [comment]
@u20221022 please follow our [Code of Conduct](https://github.com/PowerShell/PowerShell/blob/master/CODE_OF_CONDUCT.md).  We want to keep this repo professional.  Thanks.

**Comment by u20221022** [comment]
> Code of Conduct

Вы так много внимания уделяете поддержке тех, кто не может самостоятельно передвигаться из-за слабых ног, потому что это МОДНО.  В то же самое время вы просто плюёте на тех, у кого слабое зрение, потому что это НЕ модно.  Вместо того, чтобы одёрнуть тролля, который навязывает мне – потому что я просил его оставить меня в покое – совершенно тёмные изображения, на которых вообще ничего разобрать невозможно, вы травите меня.  Да хоть забаньте меня, лучше ваша глючная программа не станет.  Я прекрасно проживу и без неё.  А самих вас скоро уничтожат борцуны с «белым расизмом».  Туда вам и дорога.

https://www.translate.ru/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9?text=%D0%92%D1%8B%20%D1%82%D0%B0%D0%BA%20%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%B2%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D1%8F%20%D1%83%D0%B4%D0%B5%D0%BB%D1%8F%D0%B5%D1%82%D0%B5%20%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B5%20%D1%82%D0%B5%D1%85%2C%20%D0%BA%D1%82%D0%BE%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D1%81%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B2%D0%B8%D0%B3%D0%B0%D1%82%D1%8C%D1%81%D1%8F%20%D0%B8%D0%B7-%D0%B7%D0%B0%20%D1%81%D0%BB%D0%B0%D0%B1%D1%8B%D1%85%20%D0%BD%D0%BE%D0%B3%2C%20%D0%BF%D0%BE%D1%82%D0%BE%D0%BC%D1%83%20%D1%87%D1%82%D0%BE%20%D1%8D%D1%82%D0%BE%20%D0%9C%D0%9E%D0%94%D0%9D%D0%9E.%20%20%D0%92%20%D1%82%D0%BE%20%D0%B6%D0%B5%20%D1%81%D0%B0%D0%BC%D0%BE%D0%B5%20%D0%B2%D1%80%D0%B5%D0%BC%D1%8F%20%D0%B2%D1%8B%20%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%20%D0%BF%D0%BB%D1%8E%D1%91%D1%82%D0%B5%20%D0%BD%D0%B0%20%D1%82%D0%B5%D1%85%2C%20%D1%83%20%D0%BA%D0%BE%D0%B3%D0%BE%20%D1%81%D0%BB%D0%B0%D0%B1%D0%BE%D0%B5%20%D0%B7%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%2C%20%D0%BF%D0%BE%D1%82%D0%BE%D0%BC%D1%83%20%D1%87%D1%82%D0%BE%20%D1%8D%D1%82%D0%BE%20%D0%9D%D0%95%20%D0%BC%D0%BE%D0%B4%D0%BD%D0%BE.%20%20%D0%92%D0%BC%D0%B5%D1%81%D1%82%D0%BE%20%D1%82%D0%BE%D0%B3%D0%BE%2C%20%D1%87%D1%82%D0%BE%D0%B1%D1%8B%20%D0%BE%D0%B4%D1%91%D1%80%D0%BD%D1%83%D1%82%D1%8C%20%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D1%8F%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9%20%D0%BD%D0%B0%D0%B2%D1%8F%D0%B7%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%20%D0%BC%D0%BD%D0%B5%20%E2%80%93%20%D0%BF%D0%BE%D1%82%D0%BE%D0%BC%D1%83%20%D1%87%D1%82%D0%BE%20%D1%8F%20%D0%BF%D1%80%D0%BE%D1%81%D0%B8%D0%BB%20%D0%B5%D0%B3%D0%BE%20%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%D0%BC%D0%B5%D0%BD%D1%8F%20%D0%B2%20%D0%BF%D0%BE%D0%BA%D0%BE%D0%B5%20%E2%80%93%20%D1%81%D0%BE%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%20%D1%82%D1%91%D0%BC%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%2C%20%D0%BD%D0%B0%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85%20%D0%B2%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%20%D0%BD%D0%B8%D1%87%D0%B5%D0%B3%D0%BE%20%D1%80%D0%B0%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D1%82%D1%8C%20%D0%BD%D0%B5%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%2C%20%D0%B2%D1%8B%20%D1%82%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D0%B5%20%D0%BC%D0%B5%D0%BD%D1%8F.%20%20%D0%94%D0%B0%20%D1%85%D0%BE%D1%82%D1%8C%20%D0%B7%D0%B0%D0%B1%D0%B0%D0%BD%D1%8C%D1%82%D0%B5%20%D0%BC%D0%B5%D0%BD%D1%8F%2C%20%D0%BB%D1%83%D1%87%D1%88%D0%B5%20%D0%B2%D0%B0%D1%88%D0%B0%20%D0%B3%D0%BB%D1%8E%D1%87%D0%BD%D0%B0%D1%8F%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%20%D0%BD%D0%B5%20%D1%81%D1%82%D0%B0%D0%BD%D0%B5%D1%82.%20%20%D0%AF%20%D0%BF%D1%80%D0%B5%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D0%BE%20%D0%BF%D1%80%D0%BE%D0%B6%D0%B8%D0%B2%D1%83%20%D0%B8%20%D0%B1%D0%B5%D0%B7%20%D0%BD%D0%B5%D1%91.%20%20%D0%90%20%D1%81%D0%B0%D0%BC%D0%B8%D1%85%20%D0%B2%D0%B0%D1%81%20%D1%81%D0%BA%D0%BE%D1%80%D0%BE%20%D1%83%D0%BD%D0%B8%D1%87%D1%82%D0%BE%D0%B6%D0%B0%D1%82%20%D0%B1%D0%BE%D1%80%D1%86%D1%83%D0%BD%D1%8B%20%D1%81%20%C2%AB%D0%B1%D0%B5%D0%BB%D1%8B%D0%BC%20%D1%80%D0%B0%D1%81%D0%B8%D0%B7%D0%BC%D0%BE%D0%BC%C2%BB.%20%20%D0%A2%D1%83%D0%B4%D0%B0%20%D0%B2%D0%B0%D0%BC%20%D0%B8%20%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B0.
