### ISSUE TITLE
Highlight all occurrences of a text (`Select-String` with infinite context)

### ISSUE THREAD

**Issue by Simran-B** [PowerShell/PowerShell#18813]
### Summary of the new feature / enhancement

The `Select-String` cmdlet is super powerful, but a fixed number of `-Context` lines doesn't always give you the needed overview. Sometimes, it would be better to have it print the entire string or file content and highlight (all) matches.

### Proposed technical implementation details (optional)

The first thing I tried was `Select-String "..." -Context -1`, which isn't supported.

Interestingly, `[int32]::MaxValue` (2147483647) leads to an error (context uses System.Int32):
> Select-String: Array dimensions exceeded supported range.

With a value of `2147483591` or lower, it takes several seconds while it eats a ton of memory and eventually fails with:
> Select-String: Specified argument was out of the range of valid values. (Parameter 'capacity')

Curiously, a value of 1073741823 (`[int][Math]::Floor([int]::MaxValue/2)`) leads to this error again:
> Array dimensions exceeded supported range

My proposed feature should either have a dedicated code path in the `Select-String` implementation to work efficiently, or be a separate cmdlet, e.g. `Highlight-String`.

**Comment by mklement0** [comment]
If you feed an entire file's content to `Select-String` and use `-AllMatches`, you'll get the desired behavior (the efficient way to provide a file's content as a single, multiline string is `Get-Content -Raw`).

E.g.:

```powershell
@'
A foo
and more foo
...
and a final foo
'@ | Select-String foo -AllMatches
```

**Comment by Simran-B** [comment]
The `-AllMatches` option highlights more than one match per line but lines without matches are not printed. The desired behavior is to get the full content but with highlighting.

**Comment by mklement0** [comment]
The previous comment shows a command that produces the desired behavior with a  here-string, and also mentions how to achieve the same effect with a file (`Get-Content -Raw ... |  Select-String -AllMatches ...`)

**Comment by Simran-B** [comment]
The concrete use case is to highlight a search phrase of a programs help text, e.g. using ripgrep. There is neither a string nor a file, and the option does not work in this scenario:

`rg --help | Select-String 'file' -AllMatches`

**Comment by mklement0** [comment]
To spell it out: you need to provide the input as a _single, multi-line string_.

Given that output from _external programs_ is relayed _line by line_, you need to create a single-line string explicitly:

```powershell
rg --help | Out-String | Select-String 'file' -AllMatches
```

**Comment by Simran-B** [comment]
Thanks, that does the trick. It doesn't quite meet my UX expectations, however. I suppose I need to set up a cmdlet to make it more usable, possibly combining it with `Out-Host -Paging` (although that has serious usability issues on its own).

**Comment by mklement0** [comment]
A quick-and-dirty solution (collects all input first, before producing output):

```powershell
function Show-Matches { @($input) -join "`n" | Select-String  -AllMatches @args | Out-Host -Paging }

# Sample call
rg --help | Show-Matches file
```

As for UX expectations: Note that `Select-String`'s purpose is to _filter_, which is different from your use case.

**Comment by SteveL-MSFT** [comment]
Perhaps an option is a `-IncludeNonMatches` type switch to have it output lines that don't match?

**Comment by iSazonov** [comment]
A strange tendency arises when we keep mixing functions and formatting...

**Comment by jdhitsolutions** [comment]
Added to the Cmdlet Working Group for review.

**Comment by doctordns** [comment]
The committee has reviewed this. We do not think that this should be a part of Select-String. Additionally, there are existing tools to show vs return matches. We also feel that the requested functionality lies outside of PowerShell and with other existing tools (eg, less, more, etc.)

**Comment by Simran-B** [comment]
Fair enough. It would be nice to see improvement to the pager but that's not what this issue is about. Thanks for discussing my idea and thanks again to @mklement0 for the workarounds.
