### ISSUE TITLE
Loading personal and system profiles took 1s, even when the profiles are empty.

### ISSUE THREAD

**Issue by mark5231** [PowerShell/PowerShell#18817]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Open the PowerShell, even when the profiles are empty, it still takes about 1s to load.

### Expected behavior

```console
Should be faster?
```

### Actual behavior

```console
Open is slow.
```

### Error details

```console
I follow this: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3
to check my profiles. 
All these files are empty but still take time to load.
```

### Environment data

```powershell
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/91494227/208266646-caab54d1-5242-478b-9f69-ac559c76025a.png)

**Comment by MartinGC94** [comment]
Do you have any endpoint protection agents like SentinelOne installed? Some of them will inject themselves into the process which will also trigger this message.

**Comment by theJasonHelmick** [comment]
@mark5231 - Thank you for reporting this issue. The working group can not reproduce.
