### ISSUE TITLE
Unthrown exception in `ShouldPreserveOutputInCaseOfException`

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#18812]
https://github.com/PowerShell/PowerShell/blob/b48943ce31534b12736df9768efc670c76a09163/src/System.Management.Automation/engine/parser/ast.cs#L7384

**Comment by iSazonov** [comment]
@vexx32 @SeeminglyScience Should we throw or remove the code?

**Comment by vexx32** [comment]
Looking at where this is, it _looks_ like we probably shouldn't be throwing from this method. Whether this code path should be outright removed or would be better served as a return path though, I'm not sure.
