### ISSUE TITLE
Copy-item does not create folder to destination when copy one file

### ISSUE THREAD

**Issue by Petri-X** [PowerShell/PowerShell#18828]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi,
When running the following command:
`Copy-Item -Path .\test.txt -Destination .\TestFolder\ `

I do get the following error:
`Copy-Item: The filename, directory name, or volume label syntax is incorrect. : 'C:\Temp\TestFolder\'`

This is the same behavior on PowerShell and also Windows PS.

### Expected behavior

```console
Obviously I'm expecting that copy-item creates the folder as I asked and copy the file into it. And this is actually what it does when copy folder instead single file.
```

### Actual behavior

```console
The following error message:
`Copy-Item: The filename, directory name, or volume label syntax is incorrect. : 'C:\Temp\TestFolder\'`

And the file is not copied.
```

### Error details

```console
PS C:\Temp> get-error

Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : CopyFile
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, Public
KeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : The filename, directory name, or volume label syntax is incorrect. : 'C:\Temp\TestFolder\'
    Source     : System.Private.CoreLib
    HResult    : -2147024773
    StackTrace :
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String destinationPath, Boolean
force, PowerShell ps)
TargetObject          : C:\Temp\test.txt
CategoryInfo          : WriteError: (C:\Temp\test.txt:FileInfo) [Copy-Item], IOException
FullyQualifiedErrorId : CopyFileInfoItemIOError,Microsoft.PowerShell.Commands.CopyItemCommand
InvocationInfo        :
    MyCommand        : Copy-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 12
    Line             : Copy-Item -Path .\test.txt -Destination .\TestFolder\
    PositionMessage  : At line:1 char:1
                       + Copy-Item -Path .\test.txt -Destination .\TestFolder\
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Copy-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS C:\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by doctordns** [comment]
Use -force  to create the necessary folder structure.

**Comment by Petri-X** [comment]
Big thanks @doctordns for your propose, but:
`PS C:\Temp> Copy-Item -Path .\test.txt -Destination .\TestFolder\ -Force`
Still gives the following:
`Copy-Item: The filename, directory name, or volume label syntax is incorrect. : 'C:\Temp\TestFolder\'`

**Comment by mklement0** [comment]
* `Copy-Item` currently doesn't support what you're trying to do, namely on-demand creation of the target directory. Its [`-Force`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/copy-item?view=powershell-7.3&WT.mc_id=ps-gethelp#-force) parameter is unrelated to target-directory creation (unlike with `New-Item -Type Directory -Force`, see below).

* The error message is confusing, the more sensible one - which you can provoke by appending a dummy file name to the path - would  be "Could not find a part of the path 'C:\Temp\TestFolder\'"

I agree that on-demand target-directory would be useful, but I suggest framing this as an _enhancement_ that requires _opt-in_, and the syntax for that needs to be worked out.

In fact, this has come up before, in the context of #12805, where I've [proposed an on-demand-directory-creation switch tentatively named `-CreateOnDemand`](https://github.com/PowerShell/PowerShell/issues/12805#issuecomment-657586660)

The - cumbersome - workaround for now is:

```powershell
# Note: New-Item -Type Directory -Force returns a directory-info object either for a preexisting directory 
# or one created on demand.
Copy-Item -Path .\test.txt -Destination (New-Item -Type Directory -Force .\TestFolder)
```
