### ISSUE TITLE
Powershell 7.3.1 seems to break gcloud, works fine in Powershell 7.2.8

### ISSUE THREAD

**Issue by SalimGangji** [PowerShell/PowerShell#18821]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Creating a bug report for documentation purposes

## Notes

`gcloud` is a proprietary binary from Google, and so I'm not sure if it's appropriate to use for reproduction steps here. If it's not appropriate I can delete or rewrite this issue, please kindly let me know.

However I'm only using `gcloud` to illustrate that the behavior changed between PSVersion 7.2.8 and PSVersion 7.3.1. The only change that happened on the system was that Powershell Core was updated.

## Pre-requisites and steps to reproduce

To reproduce the error in Powershell core is very simple, although there are a couple of pre-requisites:

1. Windows OS
2. gcloud SDK installed
3. Run the powershell commands: `$PSVersionTable; [System.Environment]::NewLine; gcloud version;`

### Case PSVersion = 7.2.8 resulting in expected output

```text
Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Google Cloud SDK 412.0.0
bq 2.0.83
core 2022.12.09
gsutil 5.17
```

### Case PSVersion = 7.3.1 resulting in unexpected error output

```text
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


C:\Users\salim\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe: can't find '__main__' module in ''
```

### Expected behavior

```console
The actual versions of the gcloud binaries are immaterial, the only thing that matters is that the command executed and a result was returned.

Google Cloud SDK 412.0.0
bq 2.0.83
core 2022.12.09
gsutil 5.17
```

### Actual behavior

```console
C:\Users\salim\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe: can't find '__main__' module in ''
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Thanks for the issue @SalimGangji! This is a known issue, see #18529 and the gcloud submitted issue, https://issuetracker.google.com/issues/259295558.  Closing as duplicate, give the gcloud issue an upvote so we can get it fixed sooner :)

**Comment by SalimGangji** [comment]
Fantastic, thank you very much @StevenBucher98 !
