### ISSUE TITLE
Misspelling of link: only one / instead of two.

### ISSUE THREAD

**Issue by aidanjuma** [PowerShell/PowerShell#18830]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run a script without altering permissions in Windows 11 - the following is returned (issue denoted in double asterisks):

```
yarn : File C:\Users\aidan\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at **https:/go.microsoft.com/fwlink/?LinkID=135170**.
At line:1 char:1
+ yarn
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

### Expected behavior

```console
yarn : File C:\Users\aidan\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at **https://go.microsoft.com/fwlink/?LinkID=135170**.
At line:1 char:1
+ yarn
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
```


### Actual behavior

```console
yarn : File C:\Users\aidan\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at **https:/go.microsoft.com/fwlink/?LinkID=135170**.
At line:1 char:1
+ yarn
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
```


### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
Good catch, but note that this has since been fixed in PowerShell _Core_, which is what this repo is about.

As the issue template notes:

* For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)
This repository is ONLY for PowerShell Core 6 and PowerShell 7+ issues.

**Comment by aidanjuma** [comment]
> Good catch, but note that this has since been fixed in PowerShell _Core_, which is what this repo is about.
> 
> 
> 
> As the issue template notes:
> 
> 
> 
> * For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)
> 
> This repository is ONLY for PowerShell Core 6 and PowerShell 7+ issues.
> 
> 

Ah, perfect - thank you! Sorry about the unnecessary issue on this repo.

Best,
Aidan
