### ISSUE TITLE
PowerShell terminal hangs when running scripts from VS Code

### ISSUE THREAD

**Issue by florinangelescu** [PowerShell/PowerShell#18836]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When running scrips from VS Code the terminal of PowerShell hangs with blue screen and nothing happens anymore.
This doesn't happen if you type in you code or if you run the script line by line.

### Expected behavior

```console
This is before running the code:
![Screenshot 2022-12-21 at 10 16 41](https://user-images.githubusercontent.com/45992068/208854501-f26d557f-1ff1-47ca-b5a1-886232ec6f12.png)
```

### Actual behavior

```console
This is after running the code:
![image](https://user-images.githubusercontent.com/45992068/208854557-69e10a41-3d8a-41b3-87e6-14a00b655f5e.png)
```

### Environment data

```powershell
VS Code: 1.74.2
PowerShell: v2022.12.1
```

**Comment by ronascentes** [comment]
I'm getting the same issue.

**Comment by andschwa** [comment]
Hi @florinangelescu could you please open an issue in [vscode-powershell](https://github.com/PowerShell/vscode-powershell/issues/new/choose) following the bug report template? Including logs and screenshots of the whole thing (those don't show the script that was being executed). Thanks!

**Comment by florinangelescu** [comment]
It seems it is a PowerShell issue.
If I revert to previous version of PowerShell, this doesn't happen anymore.

![image](https://user-images.githubusercontent.com/45992068/208988984-92055f29-6187-49ae-8f01-c75a0ddd1071.png)
