### ISSUE TITLE
Make errors from outside commands clickable

### ISSUE THREAD

**Issue by noheromen** [PowerShell/PowerShell#18839]
### Summary of the new feature / enhancement

Hi, I would love to be able to click on error and that would open location of that error in file. Like VSCode does it. Here, we would have to specify tool which would open that file which contains error.

I use neovim, and when I compile C code, I would love to click on error file and have it open in neovim on that specifci line. I tried to think about it, how to implement it without raising this issue, but I dont know how to make it general for any command run in powershell. Of course I could use 2>&1 to redirect error stream, and then run some function on it, to create hyperlink and then write it to console, but this wouldnt make it generic.... 

### Proposed technical implementation details (optional)

Maybe if terminating error comes, and when the Write-Error is called (or whatever other functions that write error output to console), error text could be scanned for any file path and then make it clickable using hyperlink feature. Only thing that is missing is how to make that hyperlink open in specified file editor... and I guess this is not part of powershell, but rather windows OS itselft...

**Comment by StevenBucher98** [comment]
+1 on this idea! We may not be able to do the specific line number based on some little testing I did but could potentially make the file path in the error a hyperlink to open in whatever the user's default text editor is (notepad by default).

**Comment by SteveL-MSFT** [comment]
The errors in `ConciseView` are already formatted in a way that VSCode understands them and can be clicked (assuming it's a line in a script).  iTerm2 also detects the string is a file path to a line and clicking it opens it up in your default editor associated with the file to the location.  So I think this feature is really owned by the terminal and not the shell (which is already using a standard syntax for the file:line:char)

**Comment by noheromen** [comment]
Hi yes you are right. Thanks. I will put this reqeust to windows terminal github repo... it should be handled by windows terminal.
