### ISSUE TITLE
Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent]

### ISSUE THREAD

**Issue by msps20221129** [PowerShell/PowerShell#18838]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Examples from:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.psuseragent?view=powershellsdk-7.3.0
https://powershellmagazine.com/2012/11/20/pstip-powershell-and-the-pre-configured-user-agent-strings/

`PS > $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome`
InvalidOperation: Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].
`PS > [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox`
InvalidOperation: Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].
`PS > [Microsoft.PowerShell.Commands.PSUserAgent]::InternetExplorer`
InvalidOperation: Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].
`PS > [Microsoft.PowerShell.Commands.PSUserAgent]::Opera`
InvalidOperation: Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].

`PS > [Microsoft.PowerShell.Commands.PSUserAgent].GetProperties()`
InvalidOperation: Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].

### Expected behavior

```console
Do not know.
```

### Actual behavior

```console
The bug.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].
            HResult : -2146233087
        TargetObject          : Microsoft.PowerShell.Commands.PSUserAgent
        CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…ommands.PSUserAgent:TypeName) [], ParentContains
ErrorRecordException
        FullyQualifiedErrorId : TypeNotFound
        InvocationInfo        :
            ScriptLineNumber : 1
            OffsetInLine     : 14
            HistoryId        : -1
            Line             : $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
            PositionMessage  : At line:1 char:14
                               + $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
                               +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : ResolveTypeName
        DeclaringType : System.Management.Automation.TypeOps, System.Management.Automation, Version=7.3.1.500, Culture=
neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : Unable to find type [Microsoft.PowerShell.Commands.PSUserAgent].
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
   at System.Management.Automation.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : Microsoft.PowerShell.Commands.PSUserAgent
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…ommands.PSUserAgent:TypeName) [], RuntimeException
FullyQualifiedErrorId : TypeNotFound
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 14
    HistoryId        : -1
    Line             : $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
    PositionMessage  : At line:1 char:14
                       + $userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
                       +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
This works without errors on Windows 11 and on Linux.

**Comment by StevenBucher98** [comment]
Hmm yeah it seems to work for me as well, perhaps something went wrong on install? @msps20221129 how did you install, and can you try reinstalling?

**Comment by jborean93** [comment]
I can replicate this issue only from a fresh session, it seems like the assembly the type is defined in is not automatically loaded.

![image](https://user-images.githubusercontent.com/8462645/209241552-fef295d2-5112-470a-95b5-6745257587a2.png)

The type is in the `Microsoft.PowerShell.Commands.Utility` so any cmdlets in that assembly being called will load that assembly for you. You can see what other cmdlets are in this assembly by doing (once it has been loaded).

```powershell
[Microsoft.PowerShell.Commands.PSUserAgent].Assembly.DefinedTypes | Where-Object { $_.IsSubclassOf([System.Management.Automation.Cmdlet]) }
```

A workaround is to explicitly load the assembly first

```powershell
Add-Type -AssemblyName Microsoft.PowerShell.Commands.Utility
[Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
```

I'm not sure if pwsh should pre-load this one or add some further documentation around it.

**Comment by 237dmitry** [comment]
> I can replicate this issue only from a fresh session

Yes, me too. If I launched pwsh with noprofile.

**Comment by SteveL-MSFT** [comment]
As noted, this type is from the Utility module so that has to be loaded.  This is the same for WinPS.
