### ISSUE TITLE
alpha 9 for osx in releases

### ISSUE THREAD

**Issue by kangman** [PowerShell/PowerShell#1884]
can you put in the osx alpha 9 artifact in releases?

**Comment by alexandair** [comment]
You can find powershell-6.0.0-alpha.9.pkg on https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.9

**Comment by mgill25** [comment]
It's not there.

**Comment by alexandair** [comment]
I've just downloaded https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.9/powershell-6.0.0-alpha.9.pkg

**Comment by kangman** [comment]
the link is not there in your first URL. 

<img width="829" alt="screen shot 2016-08-18 at 1 35 07 pm" src="https://cloud.githubusercontent.com/assets/299950/17784058/f61c85cc-6548-11e6-93f5-e3e8e4c43e3d.png">

**Comment by alexandair** [comment]
I don't understand. powershell-6.0.0-alpha.9.pkg is the third entry in that list.

**Comment by kangman** [comment]
sorry didn't know pkg extension was for OSX in particular.  as the previous release name had OSX within the file name.

**Comment by andschwa** [comment]
@kangman Yeah, adding the .NET Core RID to the end of the package names was done by me, and technically incorrect, so I removed them. The [Get PowerShell matrix](https://github.com/PowerShell/PowerShell#get-powershell) should direct you to the correct package for your platform.

**Comment by kangman** [comment]
thanks @andschwa~
