### ISSUE TITLE
Add property to CommandInfo that shows the output type of individual parametersets

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#18845]
### Summary of the new feature / enhancement

You can declare different output types for different parametersets like this:

```
function Verb-Noun
{
    [OutputType(ParameterSetName="Set1", [char])]
    [OutputType(ParameterSetName="Set2", [int])]
    Param
    (
        [Parameter(ParameterSetName="Set1")]
        [switch]
        $Set1,

        [Parameter(ParameterSetName="Set2")]
        [switch]
        $Set2
    )
    if ($PSCmdlet.ParameterSetName="Set1")
    {
        [char](100..110 | Get-Random)
    }
    else
    {
        100..110 | Get-Random
    }
}
```

but there doesn't seem to be any way to actually get that data from the CommandInfo returned by `Get-Command`.  
Adding this data would enable editors to more easily tell end users what kind of objects to expect from various commands and improve the type inference used by the tab completion.

**Comment by jborean93** [comment]
While I totally agree that the ParameterSetName value should be surfaced in the `OutputTypes` property you can technically get this info for script functions through the AST.

```powershell
(Get-Command Verb-Noun).ScriptBlock.Ast.Body.ParamBlock.Attributes |
    Where-Object { $_.TypeName.Name -eq 'OutputType' }
```

It's probably possible to do this with binary cmdlets as well by scanning the attributes applied to the class and going that route, .e.g.

```powershell
System.Attribute]::GetCustomAttributes((Get-Command Get-Command).ImplementingType) |
    Where-Object { $_.GetType() -eq [System.Management.Automation.OutputTypeAttribute] }

**Comment by iSazonov** [comment]
There is also a complication with dynamic parameters and providers.
