### ISSUE TITLE
Windows: WinForms and WPF assemblies are missing from the ARM64 builds

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18858]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

_Update_: The problem is specific to Windows ARM64 builds, irrespective of installation method - see [below](https://github.com/PowerShell/PowerShell/issues/18858#issuecomment-1366298974)

~~Whether the WinForms and WPF assemblies ship with PowerShell Core depends on the installation method~~:

* ~~YES:~~
    * ~~MSI package~~ [the only reason this worked is because I accidentally installed the x64 version, not the ARM64 one]
* ~~NO~~:
    * ~~`winget install Microsoft.PowerShell` (Microsoft Store)~~
    * ~~Installation via https://aka.ms/install-powershell.ps1~~

Thus, WinForms code breaks ~~with the latter two installation methods~~ with ARM64 builds, because~~ `Add-Type -AssemblyName System.Windows.Forms` fails due to the absence of the relevant assemblies.

  * Note:  The .NET Framework version in the GAC is _not_ found, though loading it explicitly with `Add-Type -LiteralPath C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Windows.Forms.dll` does seem to work in practice.

Verify the presence / absence with:

 ```powershell
Get-Item $PSHOME/System.Windows.Forms.dll
```

~~Is this a known / by-design? If so, it should at least be documented, with a detailed list of what's absent when not using the MSI installer.~~

---

Note that there's also technically distinct, but related problem (which also happens if the WinForms assemblies _are_ present): the ability to load the WinForms assembly via  `using assembly System.Windows.Forms` has been broken since using  before v7..0:
 * see https://github.com/PowerShell/PowerShell/issues/11856

### Expected behavior

The file should be present.

### Actual behavior

The file is present only if PowerShell was installed via the MSI installer

### Environment data

```powershell
PowerShell Core v7.3.1 (.NET 7.0.0)
PowerShell Core v7.4.0-preview.1 (.NET 7.0.1) 
on Microsoft Windows 11 Pro (ARM 64-bit Processor; Version 22H2, OS Build: 22621.963)
```

**Comment by jborean93** [comment]
> Note: The .NET Framework version in the GAC is not found, though loading it explicitly with Add-Type -LiteralPath C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Windows.Forms.dll does seem to work in practice.

Dotnet will not check the GAC for you anymore which is why you need to use the full path.

**Comment by mklement0** [comment]
Thanks, @jborean93, but if memory serves, PowerShell does its own GAC probing: https://github.com/PowerShell/PowerShell/blob/6b5d6a0075ea87577f658504b66a28464b362258/src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs#L331 (I've never looked at the details).

**Comment by jborean93** [comment]
Hmm I might stand corrected sorry.

**Comment by fMichaleczek** [comment]
@mklement0 can not reproduce with my setup
![image](https://user-images.githubusercontent.com/6187529/209741121-3870fc7b-f885-4daa-b302-e45d305eb7b1.png)

**Comment by SteveL-MSFT** [comment]
This seems to be a win-arm64 specific problem.  The build script does an explicit check for `win7-*` runtime, but arm64 is `win-arm64` so it gets excluded accidentally.  Fix coming.

**Comment by mklement0** [comment]
Thanks, @SteveL-MSFT - good to know, and glad to hear a fixe is coming.

As a - somewhat moot, in this case - aside: 

In the absence of the relevant .NET (Core) assemblies, can you shed light on what PowerShell does and doesn't look for in the (by definition .NET Framework-only) GAC?

**Comment by mklement0** [comment]
Just to clarify: In the initial post I framed the problem incorrectly (since updated): this wasn't about _installation methods_, only about architecture; the only reason I didn't see the problem with the MSI package was that I accidentally installed the x64 rather than the ARM64 package.

**Comment by SteveL-MSFT** [comment]
@mklement0 I believe the GAC search is simply a fail over case.  If the assembly isn't found through the normal means ($PSHome, module, I think current path?), then it tries looking through the GAC.  There isn't an allowlist/denylist type model.  Many .NET Framework assemblies actually work in .NET (Core) so long as it's not using some API that isn't available in .NET (Core).  The absence of an assembly is no worse than trying to load a .NET Framework assembly that fails to load.

**Comment by mklement0** [comment]
Thanks, @SteveL-MSFT, good to know, but it doesn't explain why - in the absence of .NET Core assemblies - the GAC version of `System.Windows.Forms` _wasn't_ found with `-AssemblyName`, yet explicit loading it with `-LiteralPath` _did_ work (`Add-Type -LiteralPath C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Windows.Forms.dll`).

Is there some architecture-specific aspect to the GAC fallback?

**Comment by SteveL-MSFT** [comment]
The GAC fallback tries MSIL first, then the architecture specific folder.  It looks like if you're on Arm64, it actually tries to look in `FrameworkArm64` and not `Framework64`.  Looking on my win-arm64 system, there is a `System.Windows.Forms.dll` there so I would have expected that to have tried to load.

**Comment by wmmc88** [comment]
I use PowerShell 7.3.2 and the issue described is present. I see that it was marked as completed in #18859, but has the fix not been released yet? If not, how soon until it does?
