### ISSUE TITLE
Type inference should handle executables

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#18864]
### Summary of the new feature / enhancement

Output from executables like `ipconfig.exe` are saved as strings in PowerShell. The type inference should be aware of this so we can get tab completion like: `ipconfig.exe | foreach {$_.<Tab>`  
One problem here is that there's no way for PowerShell to know whether or not an executable actually outputs anything, but I think it's safe to assume that every executable outputs something and when that assumption is wrong the end user probably won't notice anyway since they have no reason to attempt to tab complete the output.

**Comment by StevenBucher98** [comment]
@MartinGC94 are you interested in tab completion for `System.String` member types?  or inner members of ipconfig's output?

**Comment by MartinGC94** [comment]
Just the string members. I'm aware that Crescendo exists and can wrap executables to make them feel more like native PowerShell commands but not every executable is going to be wrapped, so when you just want to do some quick string manipulation of the output it's nice to have tab completion for the various members.

**Comment by theJasonHelmick** [comment]
Thank you @MartinGC94 for reporting this.  The Working Group agrees that this is reasonable functionality to include.
