### ISSUE TITLE
update System.Management.Automation to 7.3.1 getting a NU1102

### ISSUE THREAD

**Issue by FlorianGrimm** [PowerShell/PowerShell#18879]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

from
`	<ItemGroup>
		<PackageReference Include="System.Management.Automation" Version="7.2.8" />
	</ItemGroup>
`
to
`
	<ItemGroup>
		<PackageReference Include="System.Management.Automation" Version="7.3.1" />
	</ItemGroup>
`

### Expected behavior

```console
can update to a public version
```

### Actual behavior

```console
NU1102: Unable to find package System.Runtime.CompilerServices.Unsafe with version (>= 7.0.0-preview.3.22119.2)
```

### Error details

```console
the current availible nuget is
System.Runtime.CompilerServices.Unsafe  7.0.0-preview.2.22152.2
```

### Environment data

```powershell
not requiered for this
```

**Comment by daxian-dbw** [comment]
Hi @FlorianGrimm, this is a known issue with 7.3.1 release. Please see the "Known Issues" section in https://github.com/PowerShell/PowerShell/releases/tag/v7.3.1 for more details and workaround.
