### ISSUE TITLE
Unable to install powershell on Ubuntu 

### ISSUE THREAD

**Issue by ajaykumar127** [PowerShell/PowerShell#1887]
Hi,

I'm running into this issue when trying to install Powershell on Ubuntu.

![screen shot 2016-08-18 at 10 58 35 pm](https://cloud.githubusercontent.com/assets/10769039/17783823/62a833d2-6597-11e6-9a91-7c8a7ee73358.png)

Any help regarding this would be most useful.

**Comment by tuchfarber** [comment]
If you are on Ubuntu you should install the .deb package for Ubuntu. You are currently trying to install a CentOS .rpm package which will not work.

**Comment by ajaykumar127** [comment]
I'm sorry i attached the wrong screenshot. This is the correct one.

![screen shot 2016-08-18 at 11 33 19 pm](https://cloud.githubusercontent.com/assets/10769039/17784938/41a96a7a-659c-11e6-9be4-dcbd0e3f6139.png)

**Comment by epennaz** [comment]
does the .deb file exist on the system: i.e. did you wget the pkg before installing it? 

wget https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.9/powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb

**Comment by ajaykumar127** [comment]
Yeah , i just got it working now. Had some issues from the VPN access. Its sorted out now. Thanks so much for quick reverts.
