### ISSUE TITLE
Wrong culture 

### ISSUE THREAD

**Issue by kingma-sbw** [PowerShell/PowerShell#18873]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The website is in english the windows OS in dutch but a german language powershell is installed 

### Expected behavior

```console
Dutch
```

### Actual behavior

```console
German
```

### Error details

```console
wrong culture languages
```

### Environment data

```powershell
letest
```

**Comment by mklement0** [comment]
As far as I know, the PowerShell (Core) edition (v6+), which this repo is solely devoted to, doesn't even _have_ localized versions - see https://github.com/PowerShell/PowerShell/issues/666.

Does your problem relate to _Windows PowerShell_ or, perhaps, are you seen localized output from a program that is external to PowerShell?

In general, please fill in explicit version information when you create an issue.

**Comment by kilasuit** [comment]
@kingma-sbw we can't help you with this little details, so you need to provide more information as to allow us to help you

**Comment by mklement0** [comment]
It _is_ related. 
But it's still not clear what your problem is. Where do you see [the wrong] localized elements show up?

**Comment by kingma-sbw** [comment]
Thanks I seem not to be able to reproduce this issue, sorry.
