### ISSUE TITLE
Type inference should have a special case for Get-Random

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#18889]
### Summary of the new feature / enhancement

Get-Random can be used on collections like this: `$RandomFiles = Get-ChildItem $PSHOME -File | Get-Random -Count 5` the type inference should handle this the same way it does with `Select-Object -First X` so tab completion can work like you would expect, eg: `Get-ChildItem $PSHOME -File | Get-Random -Count 5 | where {$_.<tab>`

**Comment by iSazonov** [comment]
I never cease to wonder how it is implemented and why it does not work as generic if there AST tree. 😕
