### ISSUE TITLE
Property assignments should get the same completions as variables

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#18885]
### Summary of the new feature / enhancement

Variables that are declared with an enum type gets tab completion for the possible values as seen here: `TabExpansion2 '[System.Management.Automation.ProgressView]$Test =' | select -ExpandProperty CompletionMatches`
This feature is missing for property assignments: `TabExpansion2 '$PSStyle.Progress.View=' | select -ExpandProperty CompletionMatches`.

**Comment by theJasonHelmick** [comment]
Thank you @MartinGC94 for reporting this.  The Working Group agrees that this is great functionality to include - and specifically for $PSStyle.
