### ISSUE TITLE
How to modify the text color of autocomplete text?

### ISSUE THREAD

**Issue by pedoc** [PowerShell/PowerShell#18890]
### Summary of the new feature / enhancement

![image](https://user-images.githubusercontent.com/6604230/210697429-50d5d420-7e92-42ce-ad13-5105e6a42244.png)

As shown in the figure, the text marked in the red box is automatically completed, but the color of the text is very difficult to recognize, so can the color be modified?

### Proposed technical implementation details (optional)

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.25267
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SteveL-MSFT** [comment]
This color is actually defined by PSReadLine.  Example:

```powershell
set-psreadlineoption -Colors @{ InlinePrediction = "`e[2m" }
```

**Comment by pedoc** [comment]
big thanks
