### ISSUE TITLE
FileSystemAclExtensions::GetAccessControl does not work until using Get-Acl once

### ISSUE THREAD

**Issue by Northman-de** [PowerShell/PowerShell#18896]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a script to create a report on filesystem permissions. For performance reasons I use `[System.IO.FileSystemAclExtensions]::GetAccessControl()` instead of `Get-Acl`.
This is working fine in 7,1.3 but does not work in 7.3.1 or 7.4.0-preview.1

Steps to reproduce:
```powershell
 [System.IO.FileSystemAclExtensions]::GetAccessControl( [System.IO.DirectoryInfo]::new( "c:\windows"))
```
It will provide the expected output after using `Get-Acl` once, regardless of the path (e.g. `Get-Acl HKCU:`).

### Expected behavior

```console
Path Owner                       Access
---- -----                       ------
     NT SERVICE\TrustedInstaller CREATOR OWNER Allow  268435456…
```

### Actual behavior

```console
Path Owner Access
---- ----- ------
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Issue_GetAccessControl](https://user-images.githubusercontent.com/10359738/210964192-699b45d3-14c9-4c58-a456-b93d229c1841.png)

**Comment by MartinGC94** [comment]
IIRC the extended properties were moved to the `Microsoft.PowerShell.Security` module to improve startup times. You can import the module to use them.

**Comment by mklement0** [comment]
Just to spell it out, because it confused me:

* The .NET call itself _always succeeds_, whether or not PowerShell's `Microsoft.PowerShell.Security` module has been imported or not (either explicitly or implicitly, via a `Get-Acl` call).

* PowerShell's formatting data for the output type uses _only_ properties that are added via PowerShell's ETS (Extended Type System), which are only available _after `Microsoft.PowerShell.Security` has been loaded_.

* To see the _type-native_ properties (too), pipe to `Format-List *`, for instance.

**Comment by Northman-de** [comment]
@MartinGC94 Thanks. Importing the module did the trick.
The great question: is this somewhere documented? How am I supposed to know which modules I need to import to use specific classes? Or to be more specific: to get a useful result. The class itself was available (unlike, e.g. when I want to use WPF forms).
Especially when it's a breaking change?

Looking at all the release notes I found this in [preview.7](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0-preview.7):

> Move the type data definition of `System.Security.AccessControl.ObjectSecurity` to the `Microsoft.PowerShell.Security` module ( #16355)

To be honest: I would have never get the link between this and my issue...

BTW: How much does it improve startup time?
Importing all ten Microsoft.PowerShell.* modules needs less than 400ms. I guess I will add this to my profile to avoid future trouble ;-)

A big advantage of PowerShell is the direct access to all .net classes. They are harder to use than cmdlets but MUCH faster.
My script finishes in 60 seconds on c:\windows using the class. With `Get-Acl` it runs for 27 minutes....

**Comment by MartinGC94** [comment]
ETS is a standard feature in PowerShell and I'm sure there's some help topic that explains all the details. I'm not aware of any way to know where type data was loaded from but generally speaking, modules only modify type data for types they use.  
As for startup time, I don't know but every little bit helps. IMO PS is way too slow to start up.

As for using .NET, it may be faster but as you can see here you lose some of the benefits that PowerShell provides for you. The DirectorySecurity class doesn't contain the properties that are missing in your screenshot: https://learn.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.directorysecurity so if you want to use .NET directly then be prepared to work a little harder.

**Comment by mklement0** [comment]
As for documenting the ETS (Extended Type System): there is currently no single topic, but there should be:
See https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6763, which not only proposes introducing a conceptual help topic named, say, `about_Types_Extended`, but also provides a high-level overview of what  (I think) it should contain.

@Northman-de, pragmatically speaking:

* You'll need to modify existing code to include an `Import-Module Microsoft.PowerShell.Security` statement at the start.
* The one-time-per-session penalty you pay for that import presumable won't negate the performance benefits of direct use of the .NET types overall.

**Comment by mklement0** [comment]
A tip for discovering a given type (instance's) ETS properties: use the intrinsic `.psextended` property (if there are none or  the relevant module hasn't yet been imported, you'll  (curiously) get `psextended {}` as the output):

```powershell
[System.IO.FileSystemAclExtensions]::GetAccessControl([System.IO.DirectoryInfo]::new( "c:\windows")).psextended
```

As for knowing _which module_ defines a given type's ETS type members, that takes some effort:

```powershell
$instance = [System.IO.FileSystemAclExtensions]::GetAccessControl([System.IO.DirectoryInfo]::new( "c:\windows"))
$typeNames = $instance.pstypenames -ne 'System.Object'
Get-ChildItem -LiteralPath ($env:PSModulePath -split [IO.Path]::PathSeparator).Where({ Test-Path -LiteralPath $_ }) -Recurse -Filter *.types.ps1xml |
  Select-String $typeNames | 
  ForEach Path | Split-Path
```

**Comment by Northman-de** [comment]
@MartinGC94 Using .net instead of a cmdlet may be harder, but in some cases the decrease of the script runtime is significant (see above: one minute compared to nearly half an hour. And this was just a small directory. The script is intended to run on much larger volumes).

@mklement0 I already added the import-module as Martin suggested and it solved my problem. I do not see this as a big deal. My problem was to identify what was missing.

Many thanks to all of you for your effort to explain and to provide helpful code (already saved for future use). I appreciate that very much.

**Comment by DarkLite1** [comment]
Stumbled upon this thread  because of this error:

>  Method invocation failed because [System.IO.DirectoryInfo] does not contain a method named 'GetAccessControl' Method invocation failed because [System.IO.DirectoryInfo] does not contain a method named 'GetAccessControl'

If I read and understood it all correctly, this should work:

```powershell
Import-Module Microsoft.PowerShell.Security

$testItem = Get-ChildItem 'c:\windows'
$testItem.GetAccessControl()
```

However, PowerShell 7.4.1 is still complaining that the method does not exist. What are we missing here? Seems similar to this [issue](https://github.com/chocolatey/choco/issues/2789).
