### ISSUE TITLE
PowerShell community Power BI dashboard has no new data since August 2022

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShell#18897]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Don't know if this is the right repo for it, but it seems like the PowerShell community Power BI dashboard (https://aka.ms/psgithubbi) has no new data since August 2022. Can't see usage of PowerShell v7.3 for instance.

### Expected behavior

```console
PBI dashboard should be live and kicking.
```

### Actual behavior

```console
PBI dashboard is not live and kicking.
```

### Environment data

```powershell
Not relevant.
```

**Comment by StevenBucher98** [comment]
We are working to get it fixed, we had some backend changes that caused it to be broken

**Comment by kasini3000** [comment]
Recommended Update Version Options:
6.x
7.0
7.1
7.2
7.3

Statistical distribution: 
it is recommended to incorporate alma-linux, rocky-linux, openeuler, etc. into centos

**Comment by StevenBucher98** [comment]
We have created a new community dashboard that can be found at aka.ms/PSPublicDashboard
