### ISSUE TITLE
Is the behavior around the 'writeErrorStream' property still supported ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#18901]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
```powershell
get-service|
 foreach-object {
        $red=$_.status -eq 'stopped';
         Add-member -InputObject $_ -MemberType NoteProperty -name 'writeErrorStream' -value $red -PassThru -force
}
```

### Expected behavior

```console
It depends if the behavior around the 'writeErrorStream' property is supported or not.
```

### Actual behavior

```console
The behavior around the 'writeErrorStream' property is not supported.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, …
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/4894452/211150762-10989392-4579-4c57-9b6b-2c586ebbe196.png)

**Comment by SteveL-MSFT** [comment]
Looks like that support was removed in this PR https://github.com/PowerShell/PowerShell/pull/8785

**Comment by LaurentDardenne** [comment]
Thank you.
