### ISSUE TITLE
Piping to "gvim -" hangs saying "reading from stdin..."

### ISSUE THREAD

**Issue by unclenull** [PowerShell/PowerShell#18900]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On windows, `echo aaaa | gvim -`, then gvim opens being non-responsive.
vim works fine, `echo aaaa | vim -`.

### Expected behavior

```console
gvim opens with content "aaaa"
```

### Actual behavior

```console
Empty and non-responsive.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/40857001/211141549-832a15ae-532f-4125-ad43-3424b164fccc.png)

**Comment by 237dmitry** [comment]
I don't understand is this problem of pwsh or gvim or Windows? For example on linux gedit works fine:
```
Write-Output aaaa | gedit -
# or
Write-Output aaaa | gedit $input
```
PS. Gvim is not installed (vi and vim too).

**Comment by jborean93** [comment]
This fails because gvim is a GUI windows exe which PowerShell handles differently. It’s most likely that pwsh doesn’t even attempt to write to the stdin handle of the new process in this scenario because it’s not expecting a GUI app to actually have one. Sounds like assumption needs to change and pwsh needs to do the same here if data is piped into the native binary regardless of its type.

**Comment by SeeminglyScience** [comment]
I don't have gvim installed atm but can you try this?

```powershell
echo aaaa | gvim - | echo
```

iirc that forced AutoHotkey to work in a similar situation

**Comment by SteveL-MSFT** [comment]
@unclenull can you also confirm if this ever worked with Windows PowerShell?

**Comment by MR0205** [comment]
> ```powershell
> echo aaaa | gvim - | echo
> ```
@SeeminglyScience, that indeed somehow lets vim no to suspend awaiting  for the stdin, and thus solves the problem. Thank you for a bypass method.

**Comment by Bert-R** [comment]
I'm running the latest PowerShell 7 (see below) and the issue still exists

```
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Bert-R** [comment]
The issue still exists, even in 7.4.0:

```
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mfle** [comment]
The issue still exists, even in 7.4.1 (gvim 9.1):
```

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ptcalex** [comment]
Do this:
`echo aaaa | cmd /c gvim -
`

**Comment by Atario** [comment]
I never had this issue till today, after updating to 9.2.  Worked fine before

**Comment by babywonderland** [comment]
> I never had this issue till today, after updating to 9.2. Worked fine before

Older versions invoked gvim through a .bat or .cmd file, which had the effect of applying @ptcalex's workaround. Now it puts the .exe directly into $env:PATH so there's no cmd middleware ensuring the pipe closes.

**Comment by Atario** [comment]
Seems like the old approach was superior, then
