### ISSUE TITLE
Passing arguments with the Start-Process cmdlet

### ISSUE THREAD

**Issue by lclutz** [PowerShell/PowerShell#18906]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing issues running external programs with the `Start-Process` cmdlet.

For example I think the following two commands should produce the same output but they do not:

```Powershell
PS> pwsh -Command 'Write-Host "`"Hello World!`""'
"Hello World!"
```

```Powershell
PS> Start-Process -FilePath 'pwsh' -ArgumentList @('-Command', 'Write-Host "`"Hello World!`""') -Wait -NoNewWindow
Hello World!`
```

There seems to be an issue with how parameters in the `ArgumentList` are passed to the external program.

### Expected behavior

```console
PS> Start-Process -FilePath 'pwsh' -ArgumentList @('-Command', 'Write-Host "`"Hello World!`""') -Wait -NoNewWindow
"Hello World!"
```

### Actual behavior

```console
PS> Start-Process -FilePath 'pwsh' -ArgumentList @('-Command', 'Write-Host "`"Hello World!`""') -Wait -NoNewWindow
Hello World!`
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
When you use `Start-Process` with a single `-ArgumentList` argument (which is advisable to work around #5576), you're in charge of formulating the _raw process command line_, and therefore requires you to `\`-escape any `"` instances that you want to be retained as part of the command:

```powershell
# Note the "\" instances.
Start-Process -FilePath 'pwsh' -ArgumentList @('-Command', 'Write-Host "`\"Hello World!`\""') -Wait -NoNewWindow
```

By contrast, with _direct_ invocation of `pwsh`, in 7.3.0 and 7.3.1, with `$PSNativeCommandArgumentPassing` set to either `Standard` or `Windows`, PowerShell performs this `\`-escaping for you.

**Comment by 237dmitry** [comment]
```
Start-Process pwsh -ArgumentList ' -Command Write-Host "`""hello`""" ' -NoNewWindow -wait
```

**Comment by mklement0** [comment]
Yes, unlike the Windows PowerShell CLI, `powershell.exe`, the PowerShell Core CLI, `pwsh.exe`, now also supports `""` as an escaped `"` on the command line, as an alternative to `\"` (the latter is usually preferable, because it is more universally recognized).

The point is the same, however: with `Start-Process`, you must perform the escaping _yourself_.

**Comment by lclutz** [comment]
Hey Michael,

thank you for your explanation of what is happening here. I was not aware of any of that. With that information I think I can come up with a workaround for my situation. 

Since there is already an open issue that is more comprehensive and targeting the same underlying problem this issue can be closed as a duplicate. Sorry that I missed the other issue.

I'm not that familiar with Github manners - should I close it? Or should I leave it for a maintainer to close?

**Comment by mklement0** [comment]
Glad to hear it helped, @lclutz.

Yes, I think it's fine to close it, and perhaps someone from the team, perhaps @iSazonov, can tag it as a duplicate.

Your issue did highlight an aspect that #5576 doesn't explicitly mention yet, however:

* When the original problem gets fixed, hopefully by introducing a new `-ArgumentArray` (`-arga`) parameter, as proposed [here](https://github.com/PowerShell/PowerShell/issues/5576#issuecomment-666566501), that parameter should perform the same automatic escaping that direct invocation does in 7.3.+ - that is, not only do values with spaces need to be enclosed in `"..."` on the process command line, _embedded_ `"` must also be automatically escaped as `\"`

* By contrast, the old behavior for `-ArgumentList` (`-args`) must remain in effect for backward compatibility (with an alias of `-ArgumentString`), which is then best used with a _single_ `-ArgumentList` value encoding _all_ arguments, which means the user must construct the _raw process command line_ themselves, i.e. with explicit embedded `"` chars. and `\`-escaping.

  * Applied to your case, using a single string:

```powershell
# Note: With #5576 fixed as proposed, -ArgumentString could be used in lieu of -ArgumentList
Start-Process -FilePath 'pwsh' -ArgumentList '-Command Write-Host "`\"Hello World!`\""' -Wait -NoNewWindow

```

**Comment by lclutz** [comment]
duplicate of #5576
