### ISSUE TITLE
Use a different method to block support on Windows 8.1 (and future versions as needed)

### ISSUE THREAD

**Issue by heaths** [PowerShell/PowerShell#18909]
### Summary of the new feature / enhancement

Per the discussion in #18854, we can't use any way - even via DLL custom action - in Windows Installer to properly block install on Windows 10 and newer (and whatever equivalent Server SKU...2019?) because of AppCompat shims that cause every version API - including `RtlGetVersion` and friends - to lie about the version. At best you can check for Windows 8.1 era SKUs.

Instead, we need a different way to block install as needed to prevent customers getting into a bad situation where PowerShell may not work - especially problematic if they just upgraded a version that did work.

### Proposed technical implementation details (optional)

I discussed a couple options with @SteveL-MSFT offline, listed in preferred order:

1. I can write an EXE appropriately manifested that does not get shimmed by AppCompat (hopefully; it tends to be sticky). DLL custom actions get lied to because they run in an _msiexec.exe_ host process which does get shimmed, but a separate EXE appropriately manifested and using `RtlGetVersion` could return 0 or 1 for supported or not supported, respectively. In this case, we'd probably just bake the requirements into the EXE rather than some way of passing an expression in, leading to potential overflows, etc. This could be built in the native repo and packaged along with other native binaries - consumed in the PowerShell/PowerShell repo.

2. Write a burn chainer using WixStdBA that provides a simple XAML-like syntax, but we'd have to port the existing MSI-based UI. Initially this wouldn't be cheap, but may be slightly cheaper to maintain going forward that MSI-based UI authoring in Wix. IMO, the XAML-like grammar is a little easier to grok. But every package manager reference would have to be updated, so it's not just the authoring cost but the cost of updating all the references; though, this would likely be a one-time cost. What's unknown is how this would affect admin deployments that might assume the MSI, like any existing Active Directory deployments via GPOs. It also adds some amount - though relatively small - to the overall package size.

**Comment by iSazonov** [comment]
> What's unknown is how this would affect admin deployments that might assume the MSI, like any existing Active Directory deployments via GPOs.

Oh, it is big headage for enterprise admins.

**Comment by heaths** [comment]
EXEs can also be distributed via WSUS, AD, etc. I wrote various extraction tools that took single- and multi-package chainers (Burn, or our previous chainers including those we've used since VS2005 and ~.NET 3.0) that would transpose is-installed and can-install logic. It's doable, but still overkill if an EXE CA can avoid the version lies.

**Comment by jborean93** [comment]
My apologies I linked the wrong URL there.

**Comment by stdin82** [comment]
`RtlGetNtVersionNumbers` (and `RtlGetNtProductType`) are not affected by the manifest thing

or you can directly read KUSER_SHARED_DATA structure for NtMajorVersion, NtMinorVersion, NtProductType
and NtBuildNumber (only populated for NT 10.0)

**Comment by stdin82** [comment]
@heaths "Update for Windows 10 (KB5001716)" is msi package, and it's using the following for LaunchCondition (both x64 and x86)
`VersionNT>=603 AND MsiNTProductType=1 AND NOT CURRENTBUILD="9600" | This application only runs on Windows 10 Client`

CURRENTBUILD is read from registry "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion"

here's the update to check:
`http://download.windowsupdate.com/c/msdownload/update/software/updt/2023/02/windows10.0-kb5001716-x64_3c582d454e57fdbbc46bb3ce89fe7d74a315a3dc.cab`

i checked msiexec.exe on Windows 11/10/8.1, and it's indeed manifested for Windows 8.1

**Comment by heaths** [comment]
VersionNT 603 was the latest version any Windows Installer package will ever get, so I'm not sure what this proves. Version 6.3 was Windows 8.1. There's nothing higher.

I've talked with Windows in the past about this, as the VS setup architect trying to find ways to work around it as well as having worked on WiX Burn. Within an MSI, options are extremely limited and one should not rely on undocumented registry data. Taking advantage of undocumented features especially in a first-party product is less than ideal.
