### ISSUE TITLE
[question] Why config file is in ~/Documents?

### ISSUE THREAD

**Issue by Freed-Wu** [PowerShell/PowerShell#18913]
### Summary of the new feature / enhancement

In <https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3#the-profile-files>

> Current User, All Hosts
> 
>     Windows - $HOME\Documents\PowerShell\Profile.ps1
>     Linux - ~/.config/powershell/profile.ps1
>     macOS - ~/.config/powershell/profile.ps1
> 
> Current user, Current Host
> 
>     Windows - $HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
>     Linux - ~/.config/powershell/Microsoft.Powershell_profile.ps1
>     macOS - ~/.config/powershell/Microsoft.Powershell_profile.ps1

I feel confused: why powershell (in windows) put its config in `~/Documents`?
According to standard, it seems to be `~/AppData/Local/` or `~/AppData/Roaming/`?

**Comment by jhoneill** [comment]
I think it's a historical thing. AppData didn't exist in Windows XP and only appeared with Windows vista. (IIRC) 
It should be where  `[System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::ApplicationData`  points but changing it creates more annoyance than leaving it where it is.

**Comment by SeeminglyScience** [comment]
> > I feel confused: why powershell (in windows) put its config in ~/Documents?
> 
> I do not like this too. I think this is due to Microsoft's desire to transfer everyone to the clouds, to OneDrive (where Documents folder is if your account is not local).

Well it's been there long before OneDrive existed, and we're trying to move it out of there partially because of how it interacts poorly with cloud services. So no, that's not why.

I think this is a duplicate of #15552. I'm unsure why it is in documents in the first place (@jhoneill's explanation sounds reasonable) but we're working on moving it.

**Comment by Freed-Wu** [comment]
> we're working on moving it

Thanks for your effort!

> I think this is a duplicate of #15552.

Looks similar. Close.
