### ISSUE TITLE
Using a specific string in the csv header and calling it with a variable causes it to stop.

### ISSUE THREAD

**Issue by vadhbka** [PowerShell/PowerShell#18912]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
$csv=@"
郡
test
"@ | ConvertFrom-Csv

$header="郡"

$csv.$header #freeze

```

### Expected behavior

```console
PS> $csv.$header
test
```

### Actual behavior

```console
$csv.$header
#freeze
```

### Error details

```console
The csv header is the string "郡" and 
When I try to call it using a variable, it freezes.
It was fine when the header was set to "郡郡" or any other Kanji character.
It seems to occur only when I use a single character "郡" in the header.
Also, it was okay to specify $csv."郡" directly.
I have tried various ways, but it seems that this problem requires two conditions: the header must be "郡" and the variable must be used.

translated by https://www.deepl.com/
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
To add an additional data point: the hang does _not_ occur on macOS 13.1

**Comment by mklement0** [comment]
I misspoke earlier: I _do_ see the problem, on _all_ platforms in v7.3.1, but _no longer_ in v7.4.0-preview.1

**Comment by vadhbka** [comment]
I also tried v7.4.0-preview.1 and had no problems.
Thanks mklement0 for letting me know.

**Comment by vadhbka** [comment]
By updating the version to v7.3.3, this problem no longer occurs, so I will close it.
Thank you very much.
