### ISSUE TITLE
Get-ComputerInfo command returns wrong data on modern Windows versions

### ISSUE THREAD

**Issue by LorenzoDePasquale** [PowerShell/PowerShell#18923]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Invoke the command `Get-ComputerInfo` on a Windows 11 machine (or up-to-date Windows 10 machine)

### Expected behavior

```console
PS> Get-ComputerInfo -Property WindowsProductName, WindowsCurrentVersion

WindowsProductName WindowsCurrentVersion
------------------ ---------------------
Windows 11 Pro     10.0
```

### Actual behavior

```console
PS> Get-ComputerInfo -Property WindowsProductName, WindowsCurrentVersion

WindowsProductName WindowsCurrentVersion
------------------ ---------------------
Windows 10 Pro     6.3
```

### Error details

```console
It seems to me that this error occurs because the Powershell code in this file (https://github.com/PowerShell/PowerShell/blob/8e14d2d7aa1d7bf3c3fbe7b2244c374d4b9f468e/src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs) gets those values from the `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion` key, which has not been updated in latest Windows versions. Using the Cim to obtain the same information yields the following (correct) result:

~~~
❯  Get-CimInstance Win32_OperatingSystem | Format-Table Caption, Version

Caption                  Version
-------                  -------
Microsoft Windows 11 Pro 10.0.22000
~~~
```

### Environment data

```powershell
❯  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by LorenzoDePasquale** [comment]
I'd like to add that the value `ReleaseId` in the same key `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion` is out-of-date too, and the same information can be obtained on Windows 10 and 11 with the value `DisplayVersion` in the same key

**Comment by iSazonov** [comment]
```
Get-ComputerInfo -Property OSVersion, WindowsCurrentVersion

OsVersion  WindowsCurrentVersion
---------  ---------------------
10.0.19044 6.3
```

**Comment by mklement0** [comment]
Good to know about `OSVersion`. 

To summarize the status quo for Windows 10 and above:

* `OSVersion` and `OSName` show the non-legacy values.

* A faster alternative is `Get-CimInstance Win32_OperatingSystem | Select-Object Version, Caption`

What is missing from _both_ commands:

* The _display version_, as shown in `winver.exe`, for instance (e.g. `22H2`); as you note, it seemingly can only be obtained from the registry.

* The "OS build" value shown in `winver.exe`  (e.g., `19044.963`); in terms of `Get-ComputerInfo` properties, it is the composite of the  `OsBuildNumber` and `WindowsUBR` properties; in `Get-CimInstance Win32_OperatingSystem` terms, there is `BuildNumber`, but the UBR value (Update Build Revision) is missing and must be obtained from the registry too.

Convenience commands to collect all of the above:

* With `Get-ComputerInfo` (much slower, but potentially offers _more_ properties).

```powershell
Get-ComputerInfo | 
  Select-Object OsName, 
                OsVersion, 
                @{ Name='OsDisplayVersion'; Expression={ Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DisplayVersion } },
                @{ Name='OsBuildName'; Expression={ '{0}.{1}' -f $_.OSBuildNumber, $_.WindowsUBR } }
```

* With `Get-CimInstance Win32_OperatingSystem` (much faster):

```powershell
Get-CimInstance Win32_OperatingSystem | 
  Select-Object Caption, 
                Version, 
                @{ Name='DisplayVersion'; Expression={ Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DisplayVersion } },
                @{ Name='BuildName'; Expression={ '{0}.{1}' -f $_.BuildNumber, (Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' UBR) } }
```

**Comment by iSazonov** [comment]
> To summarize the status quo for Windows 10 and above:

Windows 8.1 and above. 😸

**Comment by kilasuit** [comment]
I think this is something that I'm pretty sure I've also already fed back via the windows insider preview feedback hub, though that piece of feedback doesn't seem to be available to me anymore.

**Comment by iSazonov** [comment]
You can read #18854 why it is by-design.

**Comment by mmseng** [comment]
Still an issue.
