### ISSUE TITLE
Bug with 7.3.1 and Azure command "Get-AzApplicationGateway"

### ISSUE THREAD

**Issue by pgbfnf** [PowerShell/PowerShell#18929]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Update to Powershell 7.3.1 and install Az Module, then execute command Get-AzApplicationGateway with appropriate variables for your environment:

GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

### Expected behavior

```console
Expected behavior is to return the object in question.
```

### Actual behavior

```console
Actual behavior is returning an error:
GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
```

### Error details

```console
GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by pgbfnf** [comment]
Also note:
Az Module version 9.3.0 (latest version)

**Comment by kilasuit** [comment]
Ideally this should be raised in the [AzPowerShell Repo](https://github.com/Azure/azure-powershell) as it is likely an issue in their code than that of code in this repo

**Comment by pgbfnf** [comment]
Well, the problem occurs when updating to Powershell 7.3.0 or later. It doesn't occur as a result of updating the Az module code.

**Comment by ArmaanMcleod** [comment]
@pgbfnf  Have a look at: https://github.com/Azure/azure-powershell/issues/18721.

**Comment by pgbfnf** [comment]
yes, I saw that, and it's clearly still not fixed.
I don't know who is responsible for fixing it, but someone needs to.

**Comment by pgbfnf** [comment]
I reinstalled 7.3.1 and now I can't reproduce the error. I don't understand what's different, but I guess it's not a problem after all. Gremlins.
