### ISSUE TITLE
Add Repair-AppxPackage Or Something Similar?

### ISSUE THREAD

**Issue by kpcintegrations** [PowerShell/PowerShell#18927]
### Summary of the new feature / enhancement

Hello, I often have to repair appx apps on Windows 11, but going to settings>Installed Apps>The App>Repair is pretty tedious because the list of all installed programs takes forever to load. I know there's a Reset-AppxPackage command, but I don't want to lose userdata. So if you guys could add either an option like -Repair to Reset-AppxPackage or add a Repair-AppxPackage command, that would make my life easier.

**Comment by kilasuit** [comment]
I think that this is better raised in Windows Insider Feedback Hub

**Comment by daxian-dbw** [comment]
PowerShell doesn't own the Appx module, so you should report this to the right team using Feedback Hub.

**Comment by Kein** [comment]
Is there any way to update said module manually? I'm `Reset-Appx` on 21h2

**Comment by kpcintegrations** [comment]
> Is there any way to update said module manually? I'm `Reset-Appx` on 21h2

Not that I know of. I haven't even been able to find how Repair works for appx packages to even create a powershell module for it. I imagine it reinstalls all files besides the userdata ones, but I have no idea how to recreate that in a powershell script/module.

**Comment by Kein** [comment]
Can we just gut it out of that insider release?
