### ISSUE TITLE
Out-GridView crashes on Windows 11 ARM64 installation

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18930]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Similar to, but distinct in symptom to the much older #13119

I _suspect_ that this happens only on ARM64 installations.

```powershell
pwsh -NoProfile { 1 | Out-GridView; pause }
```

### Expected behavior

`Out-GridView` should display the results.

### Actual behavior

The PowerShell process crashes as a whole.

### Error details

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.TypeLoadException: Could not load type 'MS.Internal.SecurityCriticalDataForSet`1' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Management.UI.Internal.OutGridViewWindow.<>c__DisplayClass16_0.<StartWindow>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Environment data

```powershell
PowerShell Core 7.3.1
PowerShell Core 7.4.0-preview.1
on Microsoft Windows 11 Pro (ARM 64-bit Processor; Version 22H2, OS Build: 22621.963)
```

**Comment by StevenBucher98** [comment]
I am also unable to use Out-GridView on my Windows ARM 64 installation, this is the error message I get below:

```

An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.TypeLoadException: Could not load type 'MS.Internal.SecurityCriticalDataForSet`1' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Management.UI.Internal.OutGridViewWindow.<>c__DisplayClass16_0.<StartWindow>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Out-GridView: Exception has been thrown by the target of an invocation.

[process exited with code 3762504530 (0xe0434352)]
```

**Comment by mklement0** [comment]
Thanks for confirming, @StevenBucher98. Note that the same error message is already quoted in the initial post.

**Comment by guyrleech** [comment]
I too get the error on Win 11 ARM with 7.3.3. Windows PowerShell 5.1 on the same machine does not have the issue

**Comment by mklement0** [comment]
Thanks, @guyrleech, I see that too. Fortunately, the crash no longer occurs in v7.4.0-preview.2

**Comment by StevenBucher98** [comment]
Fixed in latest previews, still does not work with 7.3.9 but work with 7.4-rc1
