### ISSUE TITLE
Get-Volume ( and all other MSFT_[Storage Classes] ) on WSFC Node return remote values , not local ones

### ISSUE THREAD

**Issue by TwiggyG85** [PowerShell/PowerShell#18935]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Environment is a WSFC with 2 Nodes (DEV-NODE1 and DEV-NODE2) WinServer2022 and fileshare witness.

When I run Get-Volume on DEV-NODE2 and DEV-NODE1 is online, I get the Volumes from NODE1 and not NODE2. When NODE1 is offline, it returns the correct local values.

This Behaviour can also reproduced on 2 NODE WSFC 2019 with PS5.1. I googled hours and found bit here and bit there but nothing helpful.

### Expected behavior

```console
PS C:\Users\Administrator.local> ping dev-node1

Pinging DEV-NODE1.dev.local [192.168.0.91] with 32 bytes of data:
Reply from 192.168.0.92: Destination host unreachable.
Request timed out.
Reply from 192.168.0.92: Destination host unreachable.
Request timed out.

Ping statistics for 192.168.0.91:
    Packets: Sent = 4, Received = 2, Lost = 2 (50% loss),
PS C:\Users\Administrator.local> get-volume

DriveLetter FriendlyName FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining     Size
----------- ------------ -------------- --------- ------------ ----------------- -------------     ----
                         FAT32          Fixed     Healthy      OK                     67.17 MB    96 MB
                         NTFS           Fixed     Healthy      OK                     83.39 MB   523 MB
C                        NTFS           Fixed     Healthy      OK                     33.97 GB 63.37 GB
```

### Actual behavior

```console
PS C:\Users\Administrator.local> ping dev-node1

Pinging DEV-NODE1.dev.local [192.168.0.91] with 32 bytes of data:
Reply from 192.168.0.91: bytes=32 time<1ms TTL=128
Reply from 192.168.0.91: bytes=32 time<1ms TTL=128
Reply from 192.168.0.91: bytes=32 time<1ms TTL=128
Reply from 192.168.0.91: bytes=32 time<1ms TTL=128

Ping statistics for 192.168.0.91:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
PS C:\Users\Administrator.local> get-volume

DriveLetter FriendlyName   FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining     Size
----------- ------------   -------------- --------- ------------ ----------------- -------------     ----
                           FAT32          Fixed     Healthy      OK                     67.17 MB    96 MB
                           NTFS           Fixed     Healthy      OK                     83.39 MB   523 MB
C                          NTFS           Fixed     Healthy      OK                     34.03 GB 63.37 GB
            New Volume     NTFS           Fixed     Healthy      OK                    495.74 MB   512 MB
            MP_USERDATA001 ReFS           Fixed     Healthy      OK                      1.18 GB  1.94 GB
            New Volume 2   NTFS           Fixed     Healthy      OK                    113.89 MB   128 MB
```

### Environment data

```powershell
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
1: That seems to be by design: https://learn.microsoft.com/en-us/powershell/module/storage/get-volume?view=windowsserver2022-ps#notes I was a bit surprised when I learned that as well.  
2: This repository doesn't contain the code for that module. Your only option for feedback regarding that module is to use the black hole called "Feedback hub" where feedback goes to die.

**Comment by TwiggyG85** [comment]
> 1: That seems to be by design: https://learn.microsoft.com/en-us/powershell/module/storage/get-volume?view=windowsserver2022-ps#notes I was a bit surprised when I learned that as well. 2: This repository doesn't contain the code for that module. Your only option for feedback regarding that module is to use the black hole called "Feedback hub" where feedback goes to die.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/382ce86f55d4ae5a699c57478dfeb9bc2df1c7cf64dace5d66a1fd6a21cecc62/68747470733a2f2f6c6561726e2e6d6963726f736f66742e636f6d2f656e2d75732f6d656469612f6c6f676f732f6c6f676f2d6d732d736f6369616c2e706e67">**[Get-Volume (Storage)](https://learn.microsoft.com/en-us/powershell/module/storage/get-volume)**Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.

Ah OK, I see 👍 

> Notes
> When used in Failover Cluster, cmdlets from the Storage module operate on cluster level (all servers in the cluster).

So unnecessary. Maaah. Nice description of the Feedback Hub ^^ Made me smile.

I will
