### ISSUE TITLE
How to delete wrong autocomplete?

### ISSUE THREAD

**Issue by TheOnlyWei** [PowerShell/PowerShell#18938]
### Summary of the new feature / enhancement

I want to be able to remove wrong autocompletes.

Example of autocomplete:
<img width="152" alt="Screenshot_20230112_124743" src="https://user-images.githubusercontent.com/19400755/212178107-d5ac254a-d64f-495c-8b69-a5164cfd96b2.png">
Except I entered wrong commands sometimes and they suggest the wrong one every time.

### Proposed technical implementation details (optional)

A configuration somewhere or a command that allows us to remove the currently cached autocompletes.

**Comment by 237dmitry** [comment]
> currently cached autocompletes.

PSReadline history? Clear `(Get-PSReadLineOption).HistorySavePath` or optimize it. I sometimes replace the content of this file with a template of the commands I use most often. You also can configure behavior of PSReadline (with `AddToHistoryHandler`) to filter saved history.

```
Get-PSReadlineOption
Set-PSReadlineOption
```

**Comment by TheOnlyWei** [comment]
@237dmitry I don't know what that does. I am talking about autocomplete for the new PowerShell Core.

**Comment by Himanshu-Singh-Chauhan** [comment]
not a satisfactory answer, I type lots of wrong command everyday, and I don't want to go and manually remove them.

**Comment by KostaMadorsky** [comment]
This raises concerns about potentially storing secrets in a plain text file without users knowing about it.
I can see there is some logic around not storing commands that have word "password" in it, however, this would be stored:
```
util -p:"P@ssW0rD!"
```

Tip: use https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertto-securestring 
E.g. 

```
$pwd = ConvertTo-SecureString "P@ssW0rD!" -AsPlainText -Force
util -p:$pwd 
```
