### ISSUE TITLE
Tab completion of Windows commands is not aligned with cross-platform "best practice"

### ISSUE THREAD

**Issue by Andrew74L** [PowerShell/PowerShell#18942]
### Summary of the new feature / enhancement

According to an [article on powershell.org](https://powershell.org/2019/02/tips-for-writing-cross-platform-powershell-code/):

> On Windows, executable files have the
> .exe
> extension. On Linux/MacOS, an executable has file system permissions that mark a file as executable. If you’re searching for or running a command that could exist on all operating systems, omit the extension from the name. On Windows, PowerShell will implicitly add the
> .exe
> extension for you (it actually uses the extensions in the
> PATHEXT
> environment variable to look for commands).

The issue is that PS7 tab-completion does not follow this guideline for Windows executables. For example, typing `dot[Tab]` results in `dotnet.exe`, not `dotnet`.

### Proposed technical implementation details (optional)

Tab-completion for executables should follow the format `basename`, not `basename.ext`.
Either that or the extension appears, but in dark-grey.

An alternative would be to tab-complete to the basename, and a second tab would add the extension.
So `robo[Tab]` gives `Robocopy`, and `robo[Tab][Tab]` gives `Robocopy.exe`.

**Comment by MartinGC94** [comment]
Personally I prefer to explicitly add the file extension to make it clear that I'm not calling a native PowerShell command but I can see how having an option to leave it out can be practical for cross platform scripts.

**Comment by 237dmitry** [comment]
This behavior is most likely dictated by the fact that in addition to native applications there are functions and aliases.
For example:
```powershell
whe<tab>where<tab>Where-Object<tab>where.exe
```
The developers of PSReadline were probably looking for the optimal algorithm for autocompletion. Exactly the same behavior in Windows Powershell.

**Comment by jhoneill** [comment]
If you have a windows EXE with the same name as a PowerShell alias like SORT. The .EXE is needed. 

You may also have multiple files with the same name in different places.   I have install.exe, install.bat, install.cmd and install.ps1 files 

It's not "cross platform best practice" it's "pretending for linux users that windows executables don't have extensions".

**Comment by Andrew74L** [comment]
> Personally I prefer to explicitly add the file extension to make it clear that I'm not calling a native PowerShell command but I can see how having an option to leave it out can be practical for cross platform scripts.

Would the following display work for you?

`"Robocopy$($PSStyle.Foreground.BrightBlack).exe$($PSStyle.Reset)"`

That makes things clearer, without actually including the extension.

Or perhaps a new preference?

$PSTabCompletionOfExecutables = BasenameOnly | BasenamePlusExtension

**Comment by Andrew74L** [comment]
> If you have a windows EXE with the same name as a PowerShell alias like SORT. The .EXE is needed.

So type; sort.exe. The issue is the behavior of tab-completion on executables. There is no suggestion that '.exe' should never appear in PS7 scripts & functions. However, ancient commands should not be prioritized over cross-platform compatibility.

> You may also have multiple files with the same name in different places. I have install.exe, install.bat, install.cmd and install.ps1 files

I would suggest using more specific names, like PSInstall.ps1 and CInstall.cmd.

> It's not "cross platform best practice" it's "pretending for linux users that windows executables don't have extensions".

In the vast majority of cases the extension isn't required, owing to the PATHEXT environment variable. Tab completion should let PATHEXT do its work.

**Comment by 237dmitry** [comment]
> In the vast majority of cases the extension isn't required, owing to the PATHEXT environment variable.

What to do in other cases? Tab completion works by following the order: `alias -> function -> cmdlet -> $env:pathext`.
You can create issue in [PSReadline github](https://github.com/PowerShell/PSReadLine/issues).  Maybe they'll fix the order of precedence.

**Comment by jhoneill** [comment]
First off a quick apology if my tone was  bit snappy - was trying to answer with people screaming around me 

> Perhaps a new preference?
> 
> $PSTabCompletionOfExecutables = BasenameOnly | BasenamePlusExtension

This makes more sense, because there is a long history of the current behaviour and changing it will annoy at least as many people as it pleases. This way everyone can be happy. 

To me it's a complete non issue at the command line, you're told the file name explicitly, it runs, end of story. 
When tab expansion is completing something for a script,  it would mean than a script written on Windows to run `git.exe` won't run  `git`  on linux.  For every person who sees this as a problem, another will want the full name. So the preference setting is a chance to please both sides.

**Comment by Andrew74L** [comment]
> For every person who sees this as a problem, another will want the full name. So the preference setting is a chance to please both sides.

Sounds good to me. Thanks for your comments.

**Comment by Andrew74L** [comment]
> To me it's a complete non issue at the command line, you're told the file name explicitly, it runs, end of story. When tab expansion is completing something for a script, it would mean than a script written on Windows to run `git.exe` won't run `git` on linux. For every person who sees this as a problem, another will want the full name. So the preference setting is a chance to please both sides.

Might it be a better to have a new strict mode, rather than a new preference - one that enforces cross-platform compatibility? As the strict modes seem to be cumulative with rising version numbers, I'm not sure what version would work. Perhaps...?

`Set-StrictMode -Version 10.0`

For versions -ge 10, the cmdlet should ignore any version -lt 10. Then if you wanted version 1.0 or 2.0 also, use:

`Set-StrictMode -Version 11.0`
OR
`Set-StrictMode -Version 12.0`

I'm sure there's a better way of doing it!

**Comment by jhoneill** [comment]
My advice on strict mode has long been,
(1) write and test your own code with it on and set the worst level. 
(2) for anything written by anyone else set it to the most permissive level or all manner of things will break. 

Besides strictmode mode is about disallowing code at run. It can't tell if (e.g.) install.exe is necessary to avoid install.somethingelse. It needs to be there when the code is composed.

**Comment by mklement0** [comment]
Good point that `Set-StrictMode` isn't the right solution, @jhoneill, but for clarity let me add that you should never use `Set-StrictMode -Version Latest` in _production code_, as that may break your code in future versions.

This is the second request in recent memory for customization of tab-completion, the other one being #18180 (which was _declined_, however).

My suggestion is to handle such customizations - if deemed to be of general interest - as follows:

* At the _API_ level: 

  * Via the `options` parameter of [`System.Management.Automation.CommandCompletion.CompleteInput`](https://docs.microsoft.com/en-US/dotnet/api/System.Management.Automation.CommandCompletion.CompleteInput)

* As for how to _surface_ these customizations:

  * In the _console / terminal_: 
    * Via `PSReadLine`'s  [ `Set-PSReadLineOption`](https://learn.microsoft.com/powershell/module/psreadline/set-psreadlineoption) cmdlet.
  * In _editors_, such as Visual Studio Code:
     * Through a setting of the [PowerShell extension](https://github.com/PowerShell/vscode-powershell).

This keeps preferences relating to a  purely _interactive_ feature such as tab-completion out of PowerShell itself, and also allows _console/terminal_ behavior (where you're usually _not_ concerned with cross-platform considerations) and _editor_ behavior (where you _may_ care about cross-platform use) to be configured separately.

**Comment by jhoneill** [comment]
> Good point that `Set-StrictMode` isn't the right solution, @jhoneill, but for clarity let me add that you should never use `Set-StrictMode -Version Latest` in _production code_, as that may break your code in future versions

Thank you. 

Strictmode is IIRC, scoped, so it can be set in a function or script. However setting it globally can be expected to break a lot of things. 

Since I accept Murphy's law (in its original form, of "If it can be done wrongly, then someone will do it wrong), as basic behaviour, it follows that any way that a language allows a task to be done, will be used eventually, it's just a matter of enough programmer hours . It doesn't take many hours before one creates something strict mode fails with.  

Whilst strictMode for the scope of a script says "I won't do one of this list of thing on purpose, throw an error if I do them by accident"  if the list changes (e.g. by use of "latest") some people's code is certain to break, it's just a matter of whose, and if it's your code _the question you've gotta ask yourself is 'Do I feel lucky?'_  and will that luck extend to the maintainers and versions of the future. All runs of good luck also end.

**Comment by mklement0** [comment]
Agreed, @jhoneill, but my point was that even if you carefully manage to scope of your strict-mode settings to avoid affecting _other_ code, even _your own code_ is at risk of breaking if you ship something with `Set-StrictMode -Latest` in effect, given that if a future PowerShell version introduces a new strict-mode version with even more stringent checks, your code may then fail those checks.
