### ISSUE TITLE
OSX build instructions

### ISSUE THREAD

**Issue by dunn** [PowerShell/PowerShell#1894]
The OSX build instructions have the following line:
```
brew link --force openssl
```
This is not recommended and, as of https://github.com/Homebrew/brew/pull/597 is not possible, since it can create a header/library mismatch.  See that PR and https://langui.sh/2015/07/24/osx-clang-include-lib-search-paths/ for more information on the issue and the security implications.

So, a recommendation, and a question:
- For bootstrapping PowerShell, instead of trying to link OpenSSL to `/usr/local`, you should instruct users to pass `$(brew --prefix)/opt/openssl` to the compiler.
- Is the `.pkg` release of PowerShell build with a force-linked OpenSSL?  If so you should double-check that it's linked correctly.

**Comment by dunn** [comment]
Oh, I see this was mostly fixed in https://github.com/PowerShell/PowerShell/pull/1645; so just a matter of updating the documentation.

**Comment by andschwa** [comment]
Yes, sorry. I forgot to update the docs. Also need to note that .NET CLI will ask you to do the above step, which is no longer allowed.

**Comment by setsquared** [comment]
Can you please add .net core as a requirement the number of issues people are raising with modules not working as a result is indicative of an issue.

**Comment by andschwa** [comment]
@setsquared I'm sorry, can you clarify what you mean? If you mean add that .NET CLI is a requirement to build PowerShell, I believe that's well covered by the documentation (it's our build tool). But you mention modules, and I'm unsure what that means with respect to .NET CLI.

**Comment by andschwa** [comment]
Fixed in #2175.
