### ISSUE TITLE
Consider providing a single-file binary to make powershell similar to docker image.

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#18948]
### Summary of the new feature / enhancement

release a single-file binary of powershell

### Proposed technical implementation details (optional)

This is just my imperfect expectation. AOT in . net7 makes this idea possible. Welcome to discuss.

* In fact, the binary powershell on win and linux is green software, which is easy to deploy.

* Single file binaries, slightly easier to deploy.

* Single file binaries can help attract more customers to try. This may make powershell even greater.

* Single file binary program can reduce some functions. Or put some functions in the external dll.

* It is better to support freebsd and unix. Or put these support in an external dll.

* Provide a "file system" that allows users to embed ps1 scripts into it. It also supports automatic operation. 
For example： force the name of the autorun script file to be "main.ps1"

* Provide a packaging script, or syntax: similar to using dockerfile to generate docker-image

* Single file binaries liks docker-image ,easy self update.

* Single file binaries are NOT “powershell docker-image”. The former can run without a docker.

* A single file binary program that supports existing external module directories. 
There is also a module directory in "Internal file system", which has the highest priority.

Maybe these are easy to implement.
just need to implement the file system in memory, decompress binaries self, and run it.

**Comment by 237dmitry** [comment]
Maybe Appimage would be useful for someone. For example there is [bash on Appimagehub](https://www.appimagehub.com/p/1623134)

**Comment by SeeminglyScience** [comment]
> AOT in . net7 makes this idea possible.

There are several very large (for us specifically) limitations on what you can do with native AOT deployments.

- Trimming to only the APIs you use is required (which we can't do as we don't know what PowerShell scripts will use, and we heavily use reflection anyway)
- No built-in COM interop
- Cannot dynamically load assemblies (so no binary modules period)
- No runtime code generation (I believe there is some limited support for expression trees, but interpreted only so actual PowerShell code would be slower)

Even with native AOT, you still need to ship a few extra libs alongside your application anyway.

(Source: [Limitations of Native AOT deployment](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/#limitations-of-native-aot-deployment))

---

There *is* a build option to create a single file, but it's important to note that it's essentially a self extracting (to temp:\) archive. Personally, I'm not sure that the benefit is high enough to publish a separate self-contained executable that simply dumps the contents into temp:\

**Comment by kasini3000** [comment]
It seems that AOT technology can not be used for requirements.
self-extracting to temporary directory is one of the options. Self-decompression to memory is a better option.

I think it is not difficult to realize these, but it can bring great benefits. 

If there is a "single file powershell and auto-run mechanism", the developer only needs to provide a ps1 script to the customer without considering the deployment issue.
