### ISSUE TITLE
Invoke-SqlCmd returns incorrectly sized results for binary columns

### ISSUE THREAD

**Issue by jeroen-mostert** [PowerShell/PowerShell#18966]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Invoke-SqlCmd` returns incorrect types for columns of `BINARY`/`VARBINARY` types. Specifically, it will return `MaxBinaryLength` bytes (default 1024) even if the column contains fewer. Since no length information is made available elsewhere, it's not possible for the consumer to compensate for this unless they already happen to know the length some other way.

`Invoke-SqlCmd` is certainly not my preferred tool of choice for executing queries, as opposed to scripts (its lack of support for parameterized queries alone damns it), but it is worth noting that `sqlcmd` (the thing it's trying to copy, for better and worse) does not exhibit this behavior; binary values that don't exceed the display width are formatted as appropriately-sized hexstrings.

### Expected behavior

```console
PS> (Invoke-SqlCmd -Server '(localdb)\mssqllocaldb' -Query 'SELECT 0x00 AS A').A.Length
1
```

### Actual behavior

```console
PS> (Invoke-SqlCmd -Server '(localdb)\mssqllocaldb' -Query 'SELECT 0x00 AS A').A.Length
1024
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Matteo-T** [comment]
Hi @jeroen-mostert - you may want to log an issue at https://github.com/microsoft/SQLServerPSModule/issues/. I can take a look at it and see what is going on. Thanks!

**Comment by jeroen-mostert** [comment]
Reported at https://github.com/microsoft/SQLServerPSModule/issues/19 .
