### ISSUE TITLE
Investigate optimizing casting to a strongly typed array

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#18960]
### Summary of the new feature / enhancement

It's not uncommon to cast an array literal (`1, 2`), or array expression (`@()`) to a strongly typed array. Currently this will create an `object[]` to store the array, and *then* cast that `object[]` to the new array type.

Example:

```powershell
$bytes = [byte[]](0xFFuy, 0x1Fuy)
```

We could make this type of statement a compiler intrinsic and emit the code to create a `byte[]` up front. Assuming every literal in the array literal is already statically a byte, this is pretty easy to hook up.

---

More challenging would be arbitrarily doing the same for any casted `@()` or literal whose contents are not literals. For example:

```powershell
$bytes = [byte[]]@(
    Get-Content something.dll -AsByteStream
    Get-Content somethingelse.dll -AsByteStream
    0..50
)
```

This could be implemented by adding an "expected type" to AST result capture (there is probably a better term for this, but that's what the compiler calls it).  I'm not sure that avoiding the extra array allocation and copy will be impactful often enough to justify the extra complexity, but it's worth investigating.

**Comment by iSazonov** [comment]
This comes up from time to time as a consequence of PowerShell fundamentals - the engine works with `objects` with packaging in `PSObject` to do clever things while C# and .Net gravitate towards strong types. Jason even once mentioned that if C# dynamic existed at the time, it might have been used instead of `PSObject`. On the other hand, I saw a mention in the .Net repository that it's possible to do something more modern than `dynamic' and that should have been thought about. But apparently this is too narrow an area and no progress there. Although development in this direction could bring amazing results.

**Comment by SeeminglyScience** [comment]
It's definitely true that most of PowerShell's binders skew towards returning `object`, and definitely true that expression trees are missing some new (and old) capabilities.

Thankfully none of that should hinder this particular compiler optimization though.

**Comment by JamesWTruher** [comment]
I'd also want to understand the behavior for error conditions
`[byte[]](0xFF, 0xEE, "HaHa - No")`

**Comment by SeeminglyScience** [comment]
So take this code

```ps
$null = [byte[]](0xFFuy, 0xEEuy, "HaHa - No")
```

this currently compiles to something like this:

```cs
Fake.Dynamic<Func<CallSite, object[], byte[]>>(
    PSConvertBinder.Get(typeof(byte[])))(
        new object[] { 255, 238, "HaHa - No" });
```

My thought is that it could instead compile to

```cs
new byte[]
{
    255,
    238,
    Fake.Dynamic<Func<CallSite, string, byte>>(PSConvertBinder.Get(typeof(byte)))("HaHa - No")
};
```

It would not be *exactly* the same error behavior, but pretty close. Well, behavior wise it should be the exact same, even the same error message, but call stack will be slightly different... I think that's it.

**Comment by SeeminglyScience** [comment]
This would have to be further restricted to expressions unlikely to have side effects.

For instance, take this code:

```ps
[byte[]](0, 1, 2, 3, 'fail', (Write-Host test))
```

Currently, `test` would still write. With the proposed changes, that would no longer be the case. The compiler could verify that all literal elements are "simple" and unlikely to change state (basically fallback if there's a command or similar), but that does complicate the change quite a bit.
