### ISSUE TITLE
WebCmdlets SetRequestContent wrong logic?

### ISSUE THREAD

**Issue by CarloToso** [PowerShell/PowerShell#18973]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I was cleaning up the code of WebCmdlets #18964 and I noticed some code that seems incorrect. (WebRequestPSCmdlet.Common.cs lines 1114-1134)

```cs
if (content is FormObject form)
                {
                    SetRequestContent(request, form.Fields);
                }
                else if (content is IDictionary dictionary && request.Method != HttpMethod.Get)
                {
                    SetRequestContent(request, dictionary);
                }
                else if (content is XmlNode xmlNode)
                {
                    SetRequestContent(request, xmlNode);
                }
                else if (content is Stream stream)
                {
                    SetRequestContent(request, stream);
                }
                else if (content is byte[] bytes)
                {
                    SetRequestContent(request, bytes);
                }
                else if (content is MultipartFormDataContent multipartFormDataContent)
```

### Expected behavior

```console
`else if (content is IDictionary dictionary && request.Method != HttpMethod.Get)`

It seems this line doesn't set the request.Content if the method is GET and the body is a dictionary
```

### Actual behavior

```console
I think we should have a consistent behaviour for other type of bodys, for form and infile

Should we always set the request.Content, or never do it?
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It would be great to find an example/test/scenario which demonstrates the problem.

From https://www.diffen.com/difference/GET-vs-POST-HTTP-Requests. 
> When the method is GET, all form data is encoded into the **URL**, appended to the action URL as query string parameters. With POST, form data appears within the message **body** of the HTTP request.

This says that our code is right.
