### ISSUE TITLE
Powershell Prompt Double Execution

### ISSUE THREAD

**Issue by whatevergeek** [PowerShell/PowerShell#1897]
Version: powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb
Platform: Ubuntu 14.04
## Steps to reproduce
1. Modify $profile file and add the following function inside
   function prompt
   {
   Write-Host ("This>")
   return " "
   }
2. Exit and re-enter powershell
3. Check the commandline prompt
## Expected behavior

It should only print "This>" once.
## Actual behavior

It prints "This>" twice.
## Environment data

``` powershell
> $PSVersionTable
Name                           Value                                                                 
----                           -----                                                                 
PSVersion                      6.0.0-alpha                                                           
PSEdition                      Core                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                               
BuildVersion                   3.0.0.0                                                               
GitCommitId                    v6.0.0-alpha.9                                                        
CLRVersion                                                                                           
WSManStackVersion              3.0                                                                   
PSRemotingProtocolVersion      2.3                                                                   
SerializationVersion           1.1.0.1       
```

**Comment by lukemgriffith** [comment]
I'm also seeing the same on MacOS 10.11.6


PS /Users/luke/Downloads> $IsOSX                                                                                                                                                   
True
PS /Users/luke/Downloads> $PSVersionTable                                                                                                                                          

Name                           Value                                                                                                                                              
----                           -----                                                                                                                                              
PSVersion                      6.0.0-alpha                                                                                                                                        
PSEdition                      Core                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                            
BuildVersion                   3.0.0.0                                                                                                                                            
GitCommitId                    v6.0.0-alpha.9                                                                                                                                     
CLRVersion                                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                
SerializationVersion           1.1.0.1  


with $VerbosePreference = "Continue"

function prompt {

  Write-Verbose "Test"

}

I see the verbose "Test" twice.

**Comment by Jaykul** [comment]
Ditto for Ubuntu 16.04

**Comment by myyc** [comment]
@Jaykul can you share details? it seems ANSI escape sequences aren't supported out of the box

**Comment by whatevergeek** [comment]
@myyc which details you need? 
my hunch is that whatever posted by write-host 
gets posted twice

i'm still in the process of getting the source built on my machine... will try to help also once i get the setup done :-)

**Comment by myyc** [comment]
@whatevergeek details on how to use escape sequences instead of write-host ...

**Comment by theaquamarine** [comment]
@myyc there's a bit of an example here https://github.com/dahlbyk/posh-git/issues/282#issuecomment-218881623

**Comment by Jaykul** [comment]
Oh, I'm sorry, I didn't mean to leave you hanging. Here's what I have so far, it works on Windows 10 and Linux, even in VS Code ... but obviously not anywhere that ANSI escape sequences don't work (e.g. ISE): http://poshcode.org/6485

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#468
