### ISSUE TITLE
Casting a (single) number to `System.Collections.IEnumerable` inappropriately converts to a (single) string

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#18987]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: 

* Casting to an _interface_ should never change the operand data type, yet that is what happens here with numeric input types.
* A cast from a type that does _not_ implement `IEnumerable` should _fail_, consistently.
* (As an aside, because it may be surprising: casting to `[IEnumerable]` (or `[IEnumerable[char]]`) from a _string_ works correctly, given that `[string]` implements those interfaces, for enumeration of a string's _characters_)

```powershell
using namespace System.Collections
using namespace System.Collections.Generic

# With [int] input, for instance.
# !! -> 'System.String'
# Other (non-enumerable) types, e.g. [datetime], cause an error, as expected, and so does use of the
# the generic interface; e.g. 
#    [IEnumerable] (Get-Date)  
#    [IEnumerable[int]] 42
([IEnumerable] 42).GetType().FullName
```

### Expected behavior

The cast should fail, given that `[int]` doesn't implement `IEnumerable`.

### Actual behavior

`'System.String'` is output, implying that the cast converted the `[int]` operand to `[string]`

### Environment data

```powershell
PowerShell Core 7.3.1
PowerShell Core 7.4.0-preview.1
(Also WinPS)
```

**Comment by 237dmitry** [comment]
In 7.3.1 (Linux) it returned error
```
$  [System.Collections.Generic.IEnumerable] 42                             
InvalidOperation: Unable to find type [System.Collections.Generic.IEnumerable].

$  [System.Collections.Generic.IEnumerable[int]] [int[]] 42
42
```

**Comment by mklement0** [comment]
You have  a typo: `[System.Collections.Generic.IEnumerable] 42` -> `[System.Collections.IEnumerable] 42`; the behavior isn't platform-specific.

**Comment by rkeithhill** [comment]
The Engine WG reviewed this issue and agree that it is a bug that needs to be investigated for a potential fix.

**Comment by ninmonkey** [comment]
Here is a similar error where `@( String )` fails to coerce to `[string[]]` when using a `List[String]`
```ps1
# works
[Collections.Generic.List[Object]]$names = 'bob', 'jen'
$names.AddRange(@( 'sue', 'bill'))

# errors
[Collections.Generic.List[String]]$names2 = 'bob', 'jen'
$names2.AddRange(@( 'sue', 'bill'))
```
```ps1
Cannot convert argument "collection" with 
     value: "Object[]", 
     for "AddRange" 
     to type "IEnumerable`1[String]": 

"Cannot convert the "Object[]" value 
    of type "Object[]" 
    to type "IEnumerable`1[String]"."
```

**Comment by scriptingstudio** [comment]
This works `$names2.AddRange([string[]]( 'sue', 'bill'))`
You have to use explicit type because you have a typed list
