### ISSUE TITLE
(Non-)issue installing on Ubuntu 16.05

### ISSUE THREAD

**Issue by roehst** [PowerShell/PowerShell#1899]
Hi, I was able to install powershell from the .deb on Ubuntu 16.04, even though this failed:

$ sudo apt-get install libunwind8 libicu52
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libicu52

Which is recommended in https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604

**Comment by MaximoTrinidad** [comment]
Just in case! I did separate the dependencies. I did had a successful installation
(Ahum! The *.deb package need to be downloaded first) 
:)

$ sudo apt-get install libunwind8
$ sudo apt-get install libicu52
$ cd Downloads
$ sudo dpkg -i powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb

**Comment by andschwa** [comment]
Please look at the Ubuntu 16.04 instructions and the note that on that distribution, it's libicu55.

**Comment by MaximoTrinidad** [comment]
Good catch! I had the libicu55 because I was testing it on Windows Bash. Oops!
:P
Thanks

**Comment by andschwa** [comment]
It's definitely a pretty annoying change in dependencies :)
