### ISSUE TITLE
Unable to load DLL api-ms-win-core-console-l2-1-0.dll

### ISSUE THREAD

**Issue by superbonaci** [PowerShell/PowerShell#19006]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install `PowerShell-7.3.1-win-x86.msi` on 32 bits system.

### Expected behavior

```console
Launch.
```

### Actual behavior

```console
Does not launch.
```

### Error details

```console
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>cd C:\Program Files\PowerShell\7\

C:\Program Files\PowerShell\7>pwsh.exe
Process terminated. Unable to load DLL 'api-ms-win-core-console-l2-1-0.dll' or o
ne of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-console-l2-1-0.
dll' or one of its dependencies: The specified module could not be found. (0x800
7007E)
   at Microsoft.PowerShell.ConsoleControl.NativeMethods.GetConsoleScreenBufferIn
fo(IntPtr consoleHandle, CONSOLE_SCREEN_BUFFER_INFO& consoleScreenBufferInfo)
   at Microsoft.PowerShell.ConsoleControl.GetConsoleScreenBufferInfo(SafeFileHan
dle consoleHandle)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface..ctor(ConsoleHostUserInte
rface mshConsole)
   at Microsoft.PowerShell.ConsoleHostUserInterface..ctor(ConsoleHost parent)
   at Microsoft.PowerShell.ConsoleHost..ctor()
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText,
 Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
C:\Program Files\PowerShell\7>
```

### Environment data

```powershell
Not available.
```

**Comment by superbonaci** [comment]
Version `PowerShell-7.2.5-win-x86.msi` is working fine.

**Comment by jborean93** [comment]
Windows 6.1 is either Windows 7 or Server 2008 R2 which is no longer supported by dotnet or PowerShell. You need to upgrade your OS to be able to use the newer PowerShell versions.

**Comment by superbonaci** [comment]
Which PowerShell version 7 is the latest compatible with Windows 6.1?

**Comment by superbonaci** [comment]
> 7.2.8 should work

Totally right. Closing.

**Comment by Temik007** [comment]
Solution - https://github.com/PowerShell/PowerShell/issues/19816

**Comment by greenozon** [comment]
7.2.22 works just fine on Win7 x64 SP1

**Comment by superbonaci** [comment]
> 7.2.22 works just fine on Win7 x64 SP1

What about Win7 x32 SP1?

**Comment by greenozon** [comment]
@superbonaci  no clue, sorry mate
never used x32 windows (the last one was windows xp 20 years +- ago....)

not sure it makes sense to use 32 bit OS (as it has a hard limit of 4 GB RAM, eating near 1 GB for its own needs...)
so you see my point

regular RAM onboard is 16..32...even 64 GB in 2024

just curious - what is your use-case for win7 x32?

**Comment by superbonaci** [comment]
@greenozon Intel Atom CPU 32 bits, not possible to run 64 bits software, just old hardware which I want to keep around.
https://github.com/chocolatey/choco/issues/3268

**Comment by greenozon** [comment]
I see, then you really need x32...
sad but true

**Comment by superbonaci** [comment]
I don't need it, it's not a primary device, and I can still use the default powershell 2.0 which comes with Windows 7, very similar.
https://github.com/PowerShell/PowerShell/issues/14631
