### ISSUE TITLE
Using module causes Get-Command to incorrectly show using module cmdlets

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#19008]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If you create a module that has a `using module` statement, then when calling `Get-Command -Module` will cause the module to show the using module cmdlets in addition to its own.

```powershell
BeforeAll {
    "using module PSReadline" > TestDrive:/Test.psm1
    Import-Module TestDrive:/Test.psm1
}

Describe 'Get-Command' {
    It "Get-Command -Module Test should be empty" {
        Get-Command -Module Test | Select-Object -ExpandProperty Name | Should -BeNullOrEmpty
    }
}
```

### Expected behavior

```console
Test should pass
```

### Actual behavior

```console
Describing Get-Command
  [-] Get-Command -Module Test should be empty 8ms (5ms|3ms)
   Expected $null or empty, but got @('PSConsoleHostReadLine', 'Get-PSReadLineKeyHandler', 'Get-PSReadLineOption', 'Remove-PSReadLineKeyHandler', 'Set-PSReadLineKeyHandler', 'Set-PSReadLineOption').
   at Get-Command -Module Test | Select-Object -ExpandProperty Name | Should -BeNullOrEmpty, C:\Users\Thomas\Documents\PowerShell\Modules\Test\Pester.Tests.ps1:9
   at <ScriptBlock>, C:\Users\Thomas\Documents\PowerShell\Modules\Test\Pester.Tests.ps1:9
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Just to summarize:

* I don't know what the design intent was, but, yes, `using module` invariably imports the targeted module _session-globally_, causing it to show up in subsequent `Get-Module` calls.

* Only `Import-Module` offers localizing the import on demand with `-Scope Local`, but `Import-Module` lacks the ability to import `class` definitions from a module.
