### ISSUE TITLE
'New-Item -ItemType:SymbolicLink ... -Force' deletes existing link if not called from elevated session

### ISSUE THREAD

**Issue by ZonderP** [PowerShell/PowerShell#19011]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1.) Create symbolic link for a file with 'New-Item -ItemType:SymbolicLink ...' in an elevated session.
2.) Try to 're-target' that now existing symbolic link from within a not elevated session (via using the '-Force' switch parameter).
The symbolic link will get deleted and the error 'New-Item : Administrator privilege required for this operation.' gets displayed to the console.

Happens with Powershell Core 7.3.1 (but most probably also with all previous Powershell Core versions) as well as with Windows Powershell Core 5.1 on Windows 10 Enterprise 22H2.

Most probably it will NOT be reproducible on Windows 10 (build 14972 or newer) with Developer Mode enabled.
See here:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3
under note to parameter description of '-ItemType'.

### Expected behavior

```console
The existing symbolic link must not be deleted.
```

### Actual behavior

```console
The existing symbolic link gets deleted.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Andrew74L** [comment]
According to icacls.exe, Authenticated Users have Modify permission on the symbolic link (as opposed to the link target).
```
icacls C:\temp\symlink\ /L
C:\temp\symlink\ BUILTIN\Administrators:(I)(OI)(CI)(F)
                 NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                 BUILTIN\Users:(I)(OI)(CI)(RX)
                 NT AUTHORITY\Authenticated Users:(I)(M)
                 NT AUTHORITY\Authenticated Users:(I)(OI)(CI)(IO)(M)
```
So in that regard the expected and actual behaviour does match.

**Comment by jhoneill** [comment]
> According to icacls.exe,  ...

In addition mklink in cmd.exe requires admin to create the link, but del doesn't require it to delete it.

**Comment by 237dmitry** [comment]
> According to icacls.exe

The issue is why `New-Item` removes symlink if it cannot replace an existing one. It turns out that the symlink is first deleted and only after that the rights to create are checked.

**Comment by jhoneill** [comment]
> > According to icacls.exe
> 
> The issue is why `New-Item` removes symlink if it cannot replace an existing one. It turns out that the symlink is first deleted and only after that the rights to create are checked.

1. It's probably down to the provider, not the cmdlet. 
2. Usually an API call gets made and the failure is reported, e.g. path not found (2)  access denied (5) or in this case  "Administrator privilege required for this operation" (1314), it looks like this is translated into "Administrator privilege required for this operation."  , but it doesn't look like a "pre check" is made. It's not being an admin, but having the "Create Symbolic links" right in local security policy/user rights assignment that controls it. Deleting symbolic links is uncontrolled.

**Comment by Andrew74L** [comment]
> The issue is why `New-Item` removes symlink if it cannot replace an existing one. It turns out that the symlink is first deleted and only after that the rights to create are checked.

This is also an issue:
```
New-Item C:\temp\ -Name symlink -Value C:\temp\target2\ -ItemType SymbolicLink -Force -WhatIf
What if: Performing the operation "Create Symbolic Link" on target "Destination: C:\temp\symlink".
```

By the way, if 'New' counts as a verb because it's an action word, why is the operation to be performed not "New Symbolic Link"? That seems like an inconsistency to me.

**Comment by 237dmitry** [comment]
> Deleting symbolic links is uncontrolled.

I think it would be better if such cmdlets call UAC automaticaly. As it does [gsudo](https://github.com/gerardog/gsudo?ysclid=ld9267i2w1313459343) (C#)
