### ISSUE TITLE
Doesnt look like CLA process is enabled?

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#1902]
It looks like that Repo doesnt have the CLA process enabled right now - or is that just me?

**Comment by TravisEz13** [comment]
@kilasuit , can you point to a PR with an issue?

**Comment by TravisEz13** [comment]
It looks like it is working to me:
![image](https://cloud.githubusercontent.com/assets/10873629/17789049/52ee38da-6545-11e6-9560-b88e2a3c8838.png)

**Comment by kilasuit** [comment]
May have been just because I was looking at an old tab open with older PR's from before the Repo went l public like these below

<img width="814" alt="cla" src="https://cloud.githubusercontent.com/assets/6355225/17789770/9730927c-658b-11e6-8ad3-0f8df00ea6d0.PNG">


You'll see these don't have the CLA label added at all but that is expected behaviour isnt it?

**Comment by TravisEz13** [comment]
Yes, that is expected issue unless you close and reopen the issue.  I'll close the issue if you agree?

**Comment by kilasuit** [comment]
@TravisEz13 - That makes sense & will know for next time :wink:
