### ISSUE TITLE
Multiline values are not correctly copied out of Out-GridView

### ISSUE THREAD

**Issue by ernestasjuska** [PowerShell/PowerShell#19035]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi,

When using Out-GridView it is sometimes useful to copy view to Excel to do better filtering, sorting, etc. Normally it works just fine, but multiline values cause it to misalign values.

### Expected behavior
I think copying out of Out-GridView should at least align the cells correctly. However, there is no need to split them into separate cells in Excel case (see details at the end of this issue).

```console
PS> [pscustomobject]@{ A = 'A'; B = 'B', 'B' | Out-String } | Out-GridView
PS> # Copy what is shown in the Out-GridView to clipboad.
PS> Get-Clipboard
A       B
        B
```

or (works with Excel)

```console
PS> [pscustomobject]@{ A = 'A'; B = 'B', 'B' | Out-String } | Out-GridView
PS> # Copy what is shown in the Out-GridView to clipboad.
PS> Get-Clipboard
A       "B
B"
```

### Actual behavior

```console
PS> [pscustomobject]@{ A = 'A'; B = 'B', 'B' | Out-String } | Out-GridView
PS> # Copy what is shown in the Out-GridView to clipboad.
PS> Get-Clipboard
A       B
B
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

When you copy values to Excel you get
![image](https://user-images.githubusercontent.com/53167314/214793348-a71d5b19-d2be-44b3-a2d2-778fceeb6717.png)

when you should get
![image](https://user-images.githubusercontent.com/53167314/214794117-8bd5f34c-f5a0-4fa4-8012-4d2e0264e9a4.png)

### Escaping clipboard values so it would work with Microsoft Excel

Microsoft Excel accepts CSV format from clipboard:
- values are separated by `TAB` character;
- values are optionally quoted using `"` character (new lines that appear before closing `"` are part of the cell value);
- `"` is escaped by repeating it twice `""`.

This
```powershell
"A`t`"B`nB`"" | Set-Clipboard
```
gets pasted as (you need to expand row vertically, because Excel does not do that automatically)
![image](https://user-images.githubusercontent.com/53167314/214798017-99eaa319-6bde-48a3-84c3-97aec7b49fda.png)

### Code in question

```cs
        private string GetClipboardTextLineForSelectedItem(object value)
        {
            StringBuilder entryText = new StringBuilder();

            foreach (InnerListColumn column in this.InnerGrid.Columns)
            {
                object propertyValue;
                if (!FilterRuleCustomizationFactory.FactoryInstance.PropertyValueGetter.TryGetPropertyValue(column.DataDescription.PropertyName, value, out propertyValue))
                {
                    propertyValue = string.Empty;
                }

                entryText.Append(CultureInfo.CurrentCulture, $"{propertyValue}\t");
            }

            return entryText.ToString();
        }
```
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/Innerlist.cs#L587

**Comment by jhoneill** [comment]
> I think copying out of Out-GridView should at least align the cells correctly. However, there is no need to split them into separate cells in Excel case (see details at the end of this issue).

I don't think this will happen.   
What is copied is columns separated with Tabs (chr 9), and rows separated with CR LF (chr 13, 10),  changing this to pad cells to the correct column width and indent where there is a line break, and cope with line breaks in multiple cells isn't trivial - the effort is large and benefit small. 

However 
```
Get-Clipboard -Raw | ConvertFrom-Csv -Delimiter "`t" 
``` 
Should work, escaping the ` " ` character and wrapping text containing it or a line break in quotes would fix things which break now without breaking anything else. 
Whether PowerShell code is Out-GridView determines what happens, or whether it is part of a control which PowerShell uses but doesn't write, is another matter - it may be a .Net control which needs to be updated.
