### ISSUE TITLE
Have a way to clean up experimental features once they are no longer experimental

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/PowerShell#19034]
### Summary of the new feature / enhancement

In order to improve performance and reduce clutter, there should be a way to get rid of any "old" or "previously" experimental  features configurations.

### Proposed technical implementation details (optional)

Have a parameter for `Disable-ExperimentalFeature` that would clean up all experimental features that are no longer available via `Get-ExperimentalFeature`. Something like `Disable-ExperimentalFeature -Clean`, open to suggestions on better wording or syntax on how to do this?

Another possible option is for when someone does `Enable-ExperimentalFeature <name>` we can do a behind the scenes check on features that may be in configurations but not experimental features any more and then remove them.

**Comment by StevenBucher98** [comment]
cc @JamesWTruher

**Comment by mklement0** [comment]
See also:

* #18970
