### ISSUE TITLE
$script: scope not propogated on script invocation

### ISSUE THREAD

**Issue by hannasm** [PowerShell/PowerShell#19039]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a file defineMyVariable.ps1 as follows:

```powershell
<# defineMyVariable.ps1 #>

$script:MyVariable = 'Hello World';

function Get-MyVariable {
  if ($script:MyVariable) {
    return $script:MyVariable;
  } else {
    return 'Goodbye World';
  }
}
```

Create another file invokeMyVariable.ps1
```powershell
<# invokeMyVariable.ps1 #>

write-host (Get-MyVariable);
```

The $script:MyVariable with value 'Hello World' is not in scope when ./invokeMyVariable.ps1 runs however the function `Get-MyVariable` is defined, leading to a very clear difference in behavior between invoking the command directly from the console and when it is invoked from a script file. However, in general usage, if scripts are relying on this property of the $script: scope very unexpected and undesirable things may occur.

### Expected behavior

```console
A simple session involving these two scripts results in unexpected output:


PS /home/hannasm/devel/pwsh_bug_20230126> . ./defineMyVariable.ps1
PS /home/hannasm/devel/pwsh_bug_20230126> Get-MyVariable
Hello World
PS /home/hannasm/devel/pwsh_bug_20230126> ./invokeMyVariable.ps1  
Hello World
PS /home/hannasm/devel/pwsh_bug_20230126> 
```

### Actual behavior

```console
A simple session involving these two scripts results in unexpected output:


PS /home/hannasm/devel/pwsh_bug_20230126> . ./defineMyVariable.ps1
PS /home/hannasm/devel/pwsh_bug_20230126> Get-MyVariable
Hello World
PS /home/hannasm/devel/pwsh_bug_20230126> ./invokeMyVariable.ps1  
Goodbye World
PS /home/hannasm/devel/pwsh_bug_20230126> 
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
The `$MyVariable` is not defined in `invokeMyVariable.ps1`. Where is another script scope. You are sourced `$script:MyVariable` to the current console session but not in `invokeMyVariable.ps1`.

**Comment by kasini3000** [comment]
> two scripts 

when "two scripts": use global, 
```
$global:a = 1
```

**Comment by hannasm** [comment]
[https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.3#scope-modifiers](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-7.3#scope-modifiers)

> script: - Specifies that the name exists in the Script scope. Script scope is the nearest ancestor script file's scope or Global if there is no nearest ancestor script file.

Wouldn't this be considered a situation where 'there is no nearest ancestor script file'? It seems like in this situation, at least, the variable would be defined in the global scope.

**Comment by mklement0** [comment]
To expand on @237dmitry's comment:

PowerShell's scoping is _dynamic_, so that your function sees as `$script:` the script scope of _whatever script (scope) it happens to be invoked from_.

A simpler example:

```powershell
 $script:foo = 'original'; function foo { $script:foo }; foo  # -> 'original'
 & { $script:foo = 'changed'; foo } # -> 'changed'
```

That is, inside the script block invoked with `&`, which therefore runs in a _child_ scope, that script block's own top-level code constitutes the script scope.

If desired, you can create a closure of sorts by wrapping the function in a _module_:

```powershell
$null = New-Module {  $script:foo = 'original'; function foo { $script:foo } }
foo # -> 'original'
 & { $script:foo = 'changed'; foo } # -> !! still 'original'
```

Modules live in separate scope domains ("session states"), and the only state they share with outside callers is the _global_ state. Therefore, `foo` inside the module continues to see its _module_'s script scope, irrespective of what outside scope it is called from. While this behavior is helpful from an encapsulation perspective, it has problematic side effects: see #4568.

Note that `$global:` variables are best avoided, because they are truly _session_-global - and by default linger after your code exits.

**Comment by mklement0** [comment]
> > script: - Specifies that the name exists in the Script scope. Script scope is the nearest ancestor script file's scope or Global if there is no nearest ancestor script file.
> 
> Wouldn't this be considered a situation where 'there is no nearest ancestor script file'? It seems like in this situation, at least, the variable would be defined in the global scope.

The explanation in the docs is a bit too narrow: it isn't just about script _files_, but, as the example above shows, script _blocks_, which is the unit of execution underlying script files as well. 

In your case, `/invokeMyVariable.ps1` is the "nearest ancestor script file" (another way of putting it: the _enclosing_ script file/block), and since no `MyVariable` variables is defined _there_, `Get-MyVariable` sees none.

**Comment by hannasm** [comment]
I see, so without modifying the script i could just load the script as a **new-module** instead of dot-sourcing (keeping in mind the numerous caveats discussed in #4568)

```console
PS /home/hannasm/devel/pwsh_bug_20230126> $null = New-Module (Get-Command ./defineMyVariable.ps1 | select -expandProperty ScriptBlock)
PS /home/hannasm/devel/pwsh_bug_20230126> Get-MyVariable     
Hello World
PS /home/hannasm/devel/pwsh_bug_20230126> ./invokeMyVariable.ps1   
Hello World
```

Based on my intention, i could also rewrite this as below, where the **Get-MyVariable** function references **$MyVariable** (without scope modifiers) instead of referencing **$script:MyVariable**

```
<# defineMyVariable.ps1 #>

$script:MyVariable = 'Hello World';

function Get-MyVariable {
  if ($MyVariable) {
    return $MyVariable;
  } else {
    return 'Goodbye World';
  }
}
```

I think what i really want is something like a $file: scope modifier that would:
  * avoid polluting the global / parent variable space 
  * provide encapsulation of variables  similar to the **New-Module** approach (as shown by @mklement0 above) but at the script level

That said, i'm not sure there would be many substantial differences between this and a module aside from having much less ceremony than writing a full-on module.
