### ISSUE TITLE
Need a way to setup PowerShell WSMan remoting on windows ARM64

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#19046]
Need a way to setup PowerShell remoting on windows ARM64

Tests were disabled:
https://github.com/PowerShell/PowerShell/pull/19040/files#diff-e1e806318005ddcef198d46d559d049458a8c0a48b1dc138cc976f58c6f68c7dR13

https://github.com/PowerShell/PowerShell/pull/19040/files#diff-680d51ad5fb8c79ea1c7814d350c3bf78a66938fad12acb35a2397e932835621R116

https://github.com/PowerShell/PowerShell/pull/19040/files#diff-c89cbaa4465300dbb2e3a970e9f9c8fbb92f745e2a06b1bb189d5ca8bee13506R129

**Comment by rhubarb-geek-nz** [comment]
Enable-PSRemoting should work

On Windows Dev Kit 2023 I use OpenSSH and integrate PowerShell with that,

In C:\ProgramData\ssh\sshd_config I have

`Subsystem powershell c:/progra~1/WindowsApps/Microsoft.PowerShell_7.3.0.0_arm64__8wekyb3d8bbwe/pwsh.exe -sshs -nologo`
