### ISSUE TITLE
Invoke-WebRequest -OutFile "" strange behaviour on windows

### ISSUE THREAD

**Issue by CarloToso** [PowerShell/PowerShell#19043]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Invoke-WebRequest "https://example.com" -Method GET -OutFile ''`
--> No error, no outfile

`Invoke-WebRequest "https://example.com" -Method GET -OutFile ' '`
--> Error

Same behaviour in PS5 and PS7

### Expected behavior

```console
Both or none should throw an error
```

### Actual behavior

```console
The two commands have different behaviours
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
It looks like `-OutFile $null` and `-0utFile ''` (empty string) are unexpectedly treated as if `-OutFile` hadn't been specified.

Note that `-OutFile ' '` actually succeeds on Unix-like platforms, where you _can_ create a file whose name is a single space.
While it makes sense to report an error on Windows, the error message is misleading: the space is in effect ignored, so that the current _directory_ is targeted, and instead of complaining that you cannot save to a _directory_, it spuriously claims "Could not find part of a path"

Not surprisingly, `Invoke-RestMethod` is equally affected.

**Comment by 237dmitry** [comment]
There are no errors if the file name is specified. If the argument to this parameter is a zero-length string, then the parameter is ignored.

![ArcoLinux_2023-01-27_17-01-26](https://user-images.githubusercontent.com/78153320/215106092-d80099a1-3978-4da0-8efc-0d682c04c4b3.png)

**Comment by CarloToso** [comment]
So, I guess we should have different behaviours for windows and unix

**Comment by mklement0** [comment]
Indeed - no platform-specific behavior needed. It comes down to this:

* That `-OutputFile $null` /  `-OutputFile ''` cause `-OutputFile` to be _ignored_ is a bug: an error should be reported that these arguments aren't accepted, just like when you try to pass `''` or `$null` as the file path to `Set-Content`, for instance.

* Separately, there's a mostly cosmetic problem when an invalid path is passed (and what constitutes an invalid path is platform-specific, with very few constraints existing on Unix-like platforms): the currently _misleading_ error message should be fixed.
