### ISSUE TITLE
Add PowerShell to Ubuntu Repositories

### ISSUE THREAD

**Issue by Maltysen** [PowerShell/PowerShell#1905]
Right now to install it on  ubuntu, you have to download the `.deb` and then use `dpkg -i`. This is what `apt-get` is meant to not make you do. Can you guys make your own PPA and put it on that?

**Comment by RobCannon** [comment]
Why would anyone down-vote this.  I should be able to apt-get powershell

**Comment by dragon788** [comment]
This might be solved. https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md

**Comment by SteveL-MSFT** [comment]
As @dragon788 pointed out, you can `apt-get` (and `yum`) install PSCore6 today via the Microsoft repository, getting into the official Ubuntu repository will be more difficult until after 6.0.0 is out I would believe

**Comment by joeyaiello** [comment]
Given the fact that we support packages.microsoft.com, and that Ubuntu is highly unlikely to take our packages until we've reached a stable state, I'm moving this out to 6.1.0 (meaning "post-6.0.0").

**Comment by chalbersma** [comment]
@SteveL-MSFT If getting into the official repos is tough, what about a PPA?

**Comment by SteveL-MSFT** [comment]
@chalbersma what is PPA?

**Comment by chalbersma** [comment]
[PPA](https://launchpad.net/ubuntu/+ppas) are a semi-sanctioned way to create & host packages for ubuntu. Generally it's used to provide newer or development packages straight from maintainers or to provide packages that aren't in the ubuntu base repos.

**Comment by dragon788** [comment]
It should also be possible to just create a regular repository at Bintray
or other repository hosting services, as this does not necessarily have to
be a Launchpad PPA (which I believe requires using Bazaar to host the code
being compiled).

**Comment by SteveL-MSFT** [comment]
We've already been publishing to the official Microsoft Linux repository packages.microsoft.com so it's not clear to me the value of publishing to another repository other than the distro's official one?

**Comment by chalbersma** [comment]
@SteveL-MSFT It gives a standard way to publish and subscribe to the repos and it will help you build repositories for all Ubuntu Releases (like 17.04).

**Comment by SteveL-MSFT** [comment]
@chalbersma got it, this is something we can look into, but I don't think it's something that's high priority for the 6.0.0 release, leaving as 6.1.0 work item

**Comment by chalbersma** [comment]
@SteveL-MSFT Fair enough. Thanks for considering it.

**Comment by iSazonov** [comment]
As I mentioned [here](https://github.com/PowerShell/PowerShell/issues/5406#issuecomment-355624813) we could publish packages only for LTS versions.

**Comment by pcgeek86** [comment]
Although I prefer to use Docker containers to obtain PowerShell, I agree that this would be a valuable add to the official Ubuntu repositories.

**Comment by SteveL-MSFT** [comment]
Now that PSCore6 is published as a snap and Ubuntu 18.10 install includes option to install snaps as part of install (and PSCore6 does show up there), I consider this closed.
