### ISSUE TITLE
Get-hotfix is broken on ARM64 because native lib doesn't load

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#19052]
### Error details

```console
Win32Exception: Failed to load required native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
```

https://github.com/PowerShell/PowerShell/pull/19040/files#diff-7d4c5413f75f680ef7dad393c3cddb268877c6e85c2b475d0c6d128fe6422056R12

**Comment by SteveL-MSFT** [comment]
Created bug https://github.com/dotnet/runtime/issues/81400

We might have to change this cmdlet to use MMI instead of WMI

**Comment by iSazonov** [comment]
Didn't you want to get rid of MMI in general?

**Comment by SteveL-MSFT** [comment]
> Didn't you want to get rid of MMI in general?

Yes, our eventual goal is to remove MMI (which means Windows users would just use the built-in cimcmdlets).

However, `Get-HotFix` is a built-in cmdlet...
