### ISSUE TITLE
Unable to install on M1 Mac from releases page

### ISSUE THREAD

**Issue by kristianjaeger** [PowerShell/PowerShell#19053]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Go to https://github.com/PowerShell/PowerShell/releases/tag/v7.2.9 (VS code takes you here after installing the Powershell extension)
- attempt to install on a m1 mac with ventura

### Expected behavior

```console
Provide simple instructions like "brew install powershell" :). Thanks.
```

### Actual behavior

```console
Installation fails
```

### Error details

```console
n/a
```

### Environment data

```powershell
n/a
```

### Visuals

![image](https://user-images.githubusercontent.com/8645887/215195382-1250caa2-5dd4-458e-88ec-567cbefb8d5a.png)

**Comment by mklement0** [comment]
The instructions are [here](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.3), and they both include Homebrew instructions and explain how to get around the issue you're facing:

"

If you are running on macOS Big Sur 11.5 or higher you may receive the following error message when installing the package:

> "powershell-7.3.1-osx-x64.pkg" cannot be opened because Apple cannot check it for malicious software.

There are two ways to work around this issue:

* Using the Finder

* Find the package in Finder.
  * Control-click (click while pressing the Ctrl key) on the package.
  * Select Open from the context menu.

* From the command line
  * Run `sudo xattr -rd com.apple.quarantine powershell-7.3.1-osx-x64.pkg`. Include the full path to the `.pkg` file.
  * Install the package as you normally would.

Note
* This is a known issue related to package notarization that will be addressed in the future.

"

**Comment by kristianjaeger** [comment]
Thanks for responding. Cheers.
