### ISSUE TITLE
Copy-Item with -ToSession throws "Incorrect function" error when the from path is an Azure File Share

### ISSUE THREAD

**Issue by ryanewtaylor** [PowerShell/PowerShell#19056]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I attempt to copy a file from Azure File Storage to a Remote Virtual Machine using Copy-Item and the -ToSession I receive an "Incorrect function" error. The file appears to be created, but the Copy-Item still throws an error.

**Environment**
* VM1 (source), PowerShell 7.2.8, Windows Server 2019
* VM2 (destination), PowerShell 5.1, Windows Server 2019
     
**Steps to Reproduce**

On VM1 use Copy-Item to copy a file from azure storage to VM2 via a remote session as shown

 ```powershell
 $session = New-PSSession -ComputerName VM2
 $fromFile = "\\storage\account\path\to\file.txt"
 $toFile = "C:\temp\file.txt"
 Copy-Item -Path $fromFile -Destination $toFile -ToSession $session
 ```

All Copy-Item operations without -ToSession work fine, even the azure file share. For instance, the following works

```powershell
 $fromFile = "\\storage\account\path\to\file.txt"
 $toFile = "\\VM2\C$\temp\file.txt" # note using the default administrative share
 Copy-Item -Path $fromFile -Destination $toFile
```

It does not matter if I am using PowerShell 7 or PowerShell 5 on the sending end. Either generates the same error.

### Expected behavior

```console
The file is copied to VM2 in its C:\temp\ folder and no error is generated.
```

### Actual behavior

```console
The file is copied to VM2 in its C:\temp\ folder and Copy-Item throws "Incorrect function"
```

### Error details

```console
Copy-Item Incorrect function
```

![image](https://user-images.githubusercontent.com/1215819/215581445-9d491c7e-3cdb-4033-8d28-a8e9596ff557.png)

### Environment data

```powershell
## VM1

Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## VM 2
Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by kasini3000** [comment]
Mark, it looks like #16565. 
I'm not sure,it need to investigate.

**Comment by PaulHigin** [comment]
@ryanewtaylor Can you paste in the actual error you are getting (Get-Error on PowerShell 7)?  It is not clear if this is the same issue as #16565.  Since the file is actually copied, it seems like this is a different issue.

**Comment by ryanewtaylor** [comment]
@PaulHigin , I updated the description with a screenshot of the specific error.

**Comment by PaulHigin** [comment]
Yes, this is the same as Issue #16565.  The error is actually bogus, and the file is copied correctly.  I'll resolve this one as duplicate and will have a fix soon.
