### ISSUE TITLE
Implicit-remoting modules, at least as used by the Windows PowerShell Compatibility feature, do not honor `$ProgressPreference`

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19063]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The Windows PowerShell Compatibility feature auto-generates script modules that use implicit remoting,  such as for the `Appx` module.

Several of the `Appx` module's cmdlets put up a progress bar, such as `Add-AppxPackage`.

It is currently impossible to silence their progress display via implicit remoting, even with `$global:ProgressPreference = 'SilentlyContinue'` (the use of a _global_ variable is - unfortunately - required due to a fundamental problem with how _script_ modules (don't) see a caller's preference variables - see #4568)

```powershell
$global:ProgressPreference = 'SilentlyContinue'

# Note: for the progress bar shown during *creation of the script module*,
#  `$ProgressPreference = 'SilentlyContinue' *is* effective.
Import-Module Appx -UseWindowsPowerShell 3>$null

# Note: Pick any *.appx file on your system that is suitable for experimentation
$packagePath = 'C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.Midi.GmDls\10.0.22621.0\Appx\Neutral\MidiVoices.appx'

Add-AppxPackage $packagePath

[Console]::Write("`nPress a key to exit."); $null = [Console]::ReadKey()
```

### Expected behavior

No progress bar should show.

### Actual behavior

A progress bar generated by `Add-AppxPackage` is shown.

Note: The fact that the progress bar _stays visible_ even though `Add-AppxPackage` has already terminated is a separate problem stemming from the cmdlet neglecting to hide the progress bar on termination:

* #19022

### Environment data

```powershell
PowerShell Core 7.3.2
PowerShell Core 7.4.0-preview.1
```

**Comment by SteveL-MSFT** [comment]
It seems feasible to copy the current preference variables to the remote session, but not to keep them dynamically updated if they change after creating the session.
