### ISSUE TITLE
Via Powershell Cannot Format Disk with File System NTFS?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [PowerShell/PowerShell#19079]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Via Powershell Cannot Format Disk with File System NTFS?

The following code works up until the format attempt. The script is run as administrator. Not the file system is NTFS. The block size is the default for the disk and NTFS. I consistently get access denied at format attempt. The environment is Windows 11 fully patched/updated as the date of this post.

    Clear-Disk -Number 6 -RemoveData -Confirm:$false
    Initialize-Disk -Number 6 -PartitionStyle GPT -Confirm:$false
    New-Partition -DiskNumber 6 -UseMaximumSize -DriveLetter 'T'
    Format-Volume -DriveLetter 'T' -FileSystem NTFS -NewFileSystemLabel 'Test' -AllocationUnitSize 4096

Example...

PS C:\WINDOWS\system32> Clear-Disk -Number 6 -RemoveData -Confirm:$false
PS C:\WINDOWS\system32> Initialize-Disk -Number 6 -PartitionStyle GPT -Confirm:$false
PS C:\WINDOWS\system32> New-Partition -DiskNumber 6 -UseMaximumSize -DriveLetter 'T' 

DiskPath: \?\usbstor#disk&ven_hitachi_&prod_dk23aa-60&rev_0000#000000000000&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b} PartitionNumber DriveLetter Offset Size Type

2 T 16777216 5.58 GB Basic

PS C:\WINDOWS\system32> Format-Volume -DriveLetter 'T' -FileSystem NTFS -NewFileSystemLabel 'Test' -AllocationUnitSize 4096 Format-Volume : Access Denied Activity ID: {adc29ae6-3193-0002-4318-dbb09331d901} At line:1 char:1

    Format-Volume -DriveLetter 'T' -FileSystem NTFS -NewFileSystemLabel ' ...

      + CategoryInfo          : PermissionDenied: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Format-Volume], CimException
      + FullyQualifiedErrorId : StorageWMI 40001,Format-Volume

If I change the file system to say FAT32, the format command works. This makes no sense to me. When the script is run as administrator.

Example using other file system...

PS C:\WINDOWS\system32> Format-Volume -DriveLetter 'T' -FileSystem FAT32 -NewFileSystemLabel 'Test' -AllocationUnitSize 4096

DriveLetter FriendlyName FileSystemType DriveType HealthStatus OperationalStatus SizeRemaining Size

T TEST FAT32 Fixed Healthy OK 5.57 GB 5.57 GB

If I the exact same steps via the UI or Command prompt say via diskpart, no error. Any suggestions welcome.

### Expected behavior

```console
Format-Volume completes with out error.
```

### Actual behavior

```console
Format-Volume aborts reporting access denied, even though the script is executed via administrator privilege is present.
```

### Error details

```console
Format-Volume -DriveLetter 'T' -FileSystem NTFS -NewFileSystemLabel ' ...

      + CategoryInfo          : PermissionDenied: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Format-Volume], CimException
      + FullyQualifiedErrorId : StorageWMI 40001,Format-Volume
```

### Environment data

```powershell
Windows 11 Pro...
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎20/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  963
```

**Comment by Jibun-no-Kage** [comment]
A bit more testing.  If I add -Full -Force, the the Format-Volume command above, it works.  Why would the mode or type of format be a security issue?  Could the access denied be a missing leading error message?

**Comment by daxian-dbw** [comment]
`Format-Volume` is a cmdlet from the `Storage` module, which is not owned by the PowerShell team. You may want to submit your feedback through the [Windows Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) instead.

**Comment by Jibun-no-Kage** [comment]
Ah,... I did not realize that.  I will do as you suggest.  Thanks for the clarification.
