### ISSUE TITLE
Need a better mechanism for differing types of logos shown including a customisable logo or not showing a logo at all

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#19074]
### Summary of the new feature / enhancement

This is to help get a good acceptable middle ground based on the comments in the following issues & comments that have highlighted a need for different logos being shown at different times and can be better managed and maintained going forward.

These are just a few that I gathered in looking through issues and comments - please feel free to tag additional issues/comments as needed  

- [Show what experimental features are turned on at the start of interactive sessions](https://github.com/PowerShell/PowerShell/issues/14862)
- [`-nologo` should be the default ](https://github.com/PowerShell/PowerShell/issues/15644) - specifically this [comment by @blowdart](https://github.com/PowerShell/PowerShell/issues/15644#issuecomment-966290490) & [Steve Lee's Comment](https://github.com/PowerShell/PowerShell/issues/15644#issuecomment-984730918) & [this comment on customisable logos by @dancojocaru2000 ](https://github.com/PowerShell/PowerShell/issues/15644#issuecomment-989112014) & this [comment by @terrajobst  ](https://github.com/PowerShell/PowerShell/issues/15644#issuecomment-1010269620) 
- [Update when notification text for new release shows & what it says](https://github.com/PowerShell/PowerShell/issues/17369)
- [Don't show a logo](https://github.com/PowerShell/PowerShell/issues/14862#issuecomment-1425244618) Comment by @iSazonov that also ties with the `-nologo should be the default` series of comments above

**Comment by Andrew74L** [comment]
The current logo format is short enough that it could possibly be eliminated in favor of:

`[console]::Title = 'Powershell 7.4.0'`

Although this doesn't quite fit the Terminal tab width:

`[console]::Title = 'Administrator: Powershell 7.4.0'`

**Comment by kilasuit** [comment]
@Andrew74L that's an issue for Windows Terminal repo not PowerShell as you wouldn't have that issue if you were to use the windows console host instead. 

also this should fit the current width set in Windows Terminal `[console]::Title = 'Admin: Powershell 7.4.0'`

**Comment by Andrew74L** [comment]
> also this should fit the current width set in Windows Terminal `[console]::Title = 'Admin: Powershell 7.4.0'`

As does: `[console]::Title = 'Powershell 7.4.0 (Elevated)'`

**Comment by 237dmitry** [comment]
I turn it off everywhere. It would be nice if it wasn't there by default. Change logic, use `-logo` instead of `-nologo`.

**Comment by theJasonHelmick** [comment]
The Interactive working group has reviewed this meta issue.  The 2 primary points discussed were suppressing the update notification and setting -nologo as the default. The update notification can be suppressed today using the environment variable `POWERSHELL_UPDATECHECK=0`.  The -nologo as a default has been previously discussed and is still being explored as a user configurable option.
