### ISSUE TITLE
Get-Help command line templates

### ISSUE THREAD

**Issue by Andrew74L** [PowerShell/PowerShell#19098]
### Summary of the new feature / enhancement

People learning Powershell, or those who just need a quick reminder, might appreciate `Get-Help` providing VSCode-style syntax help (I'm not sure what it's called). Using a `-Template` switch...
```
PS > Get-Help about_While -Template
while (<condition>) {
>>    <# statement list #>
>>}
```
```
PS > Get-Help about_Foreach -Template
foreach ($<item> in $<collection>) {
>>    <# statement list #>
>>}
```
If the user just wants the syntax, without the 'live' command line...
```
PS > Get-Help about_Foreach -TemplateText
foreach ($<item> in $<collection>) {
    <# statement list #>
}
```
Using the syntax proposed in #19076, combined with `-Template` switch, we get...
`PS > foreach | Get-Help -Template`
... replaced on-screen by ...
```
PS > foreach ($<item> in $<collection>) {
>>    <# statement list #>
>>}
```
Do-While|Until would be a little trickier. Might require some 'helper' code...
```
$while = [System.Management.Automation.Host.ChoiceDescription]::new('&while', 'In a DO-WHILE loop, the condition is evaluated after the statement list has run. As in a While loop, the statement list is repeated as long as the condition evaluates to true.')
$until = [System.Management.Automation.Host.ChoiceDescription]::new('&until', 'A DO-UNTIL loop always runs at least once before the condition is evaluated. However, the statement list runs only while the condition is false.')
$choices = [System.Management.Automation.Host.ChoiceDescription[]]@($while, $until)
```
`PS > do | Get-Help -Template`
... triggers ...
`$int = $host.UI.PromptForChoice('do {<statement list>} while|until (<condition>)', 'Which keyword do you want help for?', $choices, 0)`
... and is replaced on-screen with ...
```
do {<statement list>} while|until (<condition>)
Which keyword do you want help for?
[W] while  [U] until  [?] Help (default is "W"): 
```
Assume "W" choice...
```
PS > do {
>>    <statement list>
>>} while (
>>    <condition>
>>)
```
Not sure if I like this next idea, but there could be a case for getting command line 'components' like this...
`PS > foreach | Get-Help -Template -PromptForComponents`
...
```
PS > foreach ($<item> in $<collection>) {
>>    <# statement list #>
>>}
# Read-Host -Prompt 'Enter <item> name'
Enter <item> name: PSItem
```
... updates to ...
```
PS > foreach ($PSItem in $<collection>) {
>>    <# statement list #>
>>}
# Read-Host -Prompt 'Enter <collection> name'
Enter <collection> name: 
```
... etc.

The general idea idea is that `Get-Help` starts to help the user build command lines, and not just dump documentation.

By the way, the `>>` markers seem to clutter the syntax. Are they absolutely necessary?

**Comment by iSazonov** [comment]
Get-Help -Examples

**Comment by Andrew74L** [comment]
> Get-Help -Examples

Is that the content of your upcoming Powershell book?

**Comment by Andrew74L** [comment]
> @Andrew74L - Thank you for the suggestion. This is out of scope for our current help system, but this is an interesting idea that we will explore in the future. /cc @sdwheeler

Thanks Jason

**Comment by Andrew74L** [comment]
A similar idea is reverse-splatting (to coin a term).

I wanted a summarized view of RAM data, so I started with:
`Get-CimInstance Win32_PhysicalMemory | Select-Object BankLabel,Capacity,ConfiguredClockSpeed,ConfiguredVoltage,Manufacturer | Format-Table`

Then changed the command line to:
`Get-CimInstance Win32_PhysicalMemory | Select-Object @{name='Bank';expr={$_.BankLabel -replace 'BANK ' -as [int]}},@{name='Capacity(GB)';expr={$_.Capacity / 1gb}},@{name='ClockSpeed(MHz)';expr={$_.ConfiguredClockSpeed}},@{name='Volts';expr={($_.ConfiguredVoltage / 1000)}},Manufacturer | Format-Table`

I made a couple of careless syntax errors on the way. Wishful thinking then came up with this:
`Get-CimInstance Win32_PhysicalMemory | Select-Object @BankLabel,@Capacity,@ConfiguredClockSpeed,@ConfiguredVoltage,Manufacturer | Format-Table`

On Enter (or perhaps a key-combo like Shift-Enter), pwsh would expand the 'splats', but without Enter, so that the command line could be edited as required...
`Get-CimInstance Win32_PhysicalMemory | Select-Object @{name='BankLabel';expr={$_.BankLabel}},@{name='Capacity';expr={$_.Capacity}},@{name='ConfiguredClockSpeed';expr={$_.ConfiguredClockSpeed}},@{name='ConfiguredVoltage';expr={$_.ConfiguredVoltage}},Manufacturer | Format-Table`
