### ISSUE TITLE
"Export-ModuleMember -Alias * -Function *" does not work

### ISSUE THREAD

**Issue by roysubs** [PowerShell/PowerShell#19099]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a module that has functions and aliases. On the last line of the module, I have:
```
Export-ModuleMember -Alias * -Function *
```
In Windows PowerShell 5.1 this works fine, and the aliases load.
However, when I take this module to PowerShell 7.x, it no longer works. The module loads fine when I start a new PowerShell 7.x session, but the aliases do not load (until after I have first run any function in the module, which somehow forces the aliases to load).
This looks to be a bug in PowerShell 7.x

### Expected behavior

```console
Export-ModuleMember -Alias * -Function *
# Should load all aliases in the module into every new session
```

### Actual behavior

```console
Export-ModuleMember -Alias * -Function *
# Does nothing
```

### Error details

```console
There is no error, it just fails to load the aliases
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasNieto** [comment]
This is by design due to performance reasons, see this issue for more details. https://github.com/PowerShell/PowerShell/issues/9379

If you would like the alias to work without having to manually running `Import-Module` then you should define `AliasesToExport` key in the module manifest with explicit values not wildcards.

`AliasesToExport = @("MyAlias1", "MyAlias2", "MyAlias3")`

**Comment by loxia01** [comment]
It would be a good idea to update the `Export-ModuleMember` docs about this issue, especially since the docs now promotes its use as "best practice".
