### ISSUE TITLE
Install-Module not working for psgallery

### ISSUE THREAD

**Issue by fishman** [PowerShell/PowerShell#1910]
Steps to reproduce
------------------

Pick a module from PSGallery and run install:

    Install-Module -Name Posh-SSH

Expected behavior
-----------------

The module should be installed

Actual behavior
---------------

	PackageManagement\Install-Package : Could not compare "6.0.0-alpha" to "5.0". Error: "Cannot convert value "5.0" to type                                 "System.Management.Automation.SemanticVersion". Error: "Cannot process argument because the value of argument "version" is not valid. Change the value of     the "version" argument and run the operation again.""                                                                                                         At /usr/local/microsoft/powershell/6.0.0-alpha.9/Modules/PowerShellGet/PSModule.psm1:1706 char:21ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo] + ...          $null = PackageManagement\Install-Package @PSBoundParameters                                                                                   +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
		+ FullyQualifiedErrorId : ComparisonFailure,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

Environment data
----------------

	$PSVersionTable

	Name                           Value
	----                           -----
	PSVersion                      6.0.0-alpha
	PSEdition                      Core
	PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
	BuildVersion                   3.0.0.0
	GitCommitId                    v6.0.0-alpha.9
	CLRVersion
	WSManStackVersion              3.0
	PSRemotingProtocolVersion      2.3
	SerializationVersion           1.1.0.1

**Comment by kilasuit** [comment]
Duplicate of #1773

**Comment by fishman** [comment]
must have missed it in my search, soz

**Comment by kilasuit** [comment]
@fishman - no problem at all - its better to have been reported than not reported :smile:

**Comment by bmanikm** [comment]
## Please use one of the following options to install the modules

### Option 1: Replace the PSModule.psm1 file under PowerShellGet module base with the updated file from master branch (https://github.com/PowerShell/PowerShell).
    Install-Module error got resolved by adding a workaround in PowerShellGet module.
    Please replace the PSModule.psm1 file under PowerShellGet module base with https://github.com/PowerShell/PowerShell/blob/master/src/Modules/Shared/PowerShellGet/PSModule.psm1.
    For more details --> #1927


### Option 2: Get the latest CI build
    https://ci.appveyor.com/project/PowerShell/powershell/build/artifacts
        OR
    https://travis-ci.org/PowerShell/PowerShell/builds/ 


### Option 3: Use NuGet provider to install the required module to the target location.
    Install-Package -Name $ModuleName -Source https://www.powershellgallery.com/api/v2/ -ProviderName NuGet -ExcludeVersion -Destination $YourTargetLocation
