### ISSUE TITLE
[PSCustomObject] How to format the output of non-integer numbers?

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#19107]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I already opened a similar issue, then I did not receive a reasonable answer, I decided to wait until the new release, but nothing has changed.

If you use the table format, then trailing zeros are added to the non-integer numeric value:
```powershell
[pscustomobject] @{ dollar = 1.95; monat = 20.01 }

dollar  monat
------  -----
 1,950 20,010
 ```
If I cast these values to a string type, then I will have to format the alignment in the columns of the table:
```powershell
[pscustomobject] @{ dollar = 1.95; monat = 20.01 }
| Format-Table @{lab='dollar'; exp={$_.dollar.ToString()}; a='right'},
               @{lab='monat'; exp={$_.monat.ToString()}; a='right'}


dollar monat
------ -----
  1,95 20,01
```
or
```powershell
[pscustomobject] @{ dollar = [string] 1.95; monat = [string] 20.01 }
| Format-Table @{lab='dollar'; exp={$_.dollar}; a='right'},
               @{lab='monat'; exp={$_.monat}; a='right'}
```
Or get this object as a list.

But the situation is such that the script outputs an object with more than thirty values and six properties.
Thus, the complete list will be 30 * 6 + 30 separators = 210 lines. The only possible option is a table.
But I will not format the output of the script directly in the console.

The variant with alignment right during the formation of the object is also not suitable, because there will be indents when viewed as a list.

```powershell
[pscustomobject] @{ dollar = '{0,6}' -f 1.95; monat = '{0,5}' -f 20.01; weather = 'clear' }
| Format-List


dollar  :   1,95
monat   : 20,01
weather : clear
```
Advise what to do, in Windows it is tolerable, there is only one zero added, up to hundredths, and in Linux two zeros, up to thousandths.

### Expected behavior

```console
Table view of PsCustomObject should not add trailing zeroes, should return value of non-integer numeric as is.
```

### Actual behavior

```console
PSCustomObject adds trailing zeroes to table format.
```

### Error details

```console
No Errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Linux 6.1.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:39 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Horror

**Comment by rhubarb-geek-nz** [comment]
I would suggest that if you expect an exact formatting of floating point numbers, especially when they represent money then you should explicitly specify the format you want and not rely on defaults. I notice that your decimal point is being localised to a comma.

**Comment by mklement0** [comment]
> I already opened a similar issue, then I did not receive a reasonable answer

At the very least you should reference the previous issue:
* https://github.com/PowerShell/PowerShell/issues/18492

You [did receive a reasonable answer there](https://github.com/PowerShell/PowerShell/issues/18492#issuecomment-1308978730), you just [chose not to engage with it meaningfully](https://github.com/PowerShell/PowerShell/issues/18492#issuecomment-1309049945).

The discrepancy in the number of decimal places seems to come down to a difference in .NET:  for reasons unknown to me, the `N` standard number format results in _two_ decimal place on Windows, and _three_ on Unix-like platforms; e.g., `'{0:N}' -f (1/9)` yields `0.11` on Windows, and `0.111` on Unix-like platforms.

While this discrepancy may be surprising, note that there's no guarantee that culture-specific representations work the same across platforms, and that _for-display_ representations aren't part of PowerShell's commitment to backward compatibility.

Indeed, if you need to control the exact display format, use _explicit_ formatting, via the `formatstring` (`f`) entry in [calculated properties](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Calculated_Properties) you can pass to the `Format-*` cmdlets:

```powershell
[pscustomobject] @{ dollar = 1.95; monat = 20.01; weather = 'clear' } | 
  Format-List @{ e='dollar'; f='{0,6:f2}' }, @{ e='monat'; f='{0,6:f2}' }, weather
```

Output:

```none
dollar  :   1.95
monat   :  20.01
weather : clear
```

---

@rhubarb-geek-nz

> I notice that your decimal point is being localised to a comma.

_For-display_ output (as produced by the formatting system) is always localized. Try
`pwsh -noprofile { [cultureinfo]::CurrentCulture = 'fr-FR'; 1.2 }`

**Comment by 237dmitry** [comment]
> I would suggest that if you expect an exact formatting of floating point numbers

Exactly.

> especially when they represent money then you should explicitly specify the format you want

Money is an abstract example. Replace `dollar` with `flower`. Where I could specify format?
I expect in table view the same values as in list view:

![ArcoLinux_2023-02-05_08-02-11](https://user-images.githubusercontent.com/78153320/216802720-517fdaca-932a-4559-9c5b-7e2e83989c4f.png)

**Comment by 237dmitry** [comment]
> For-display output (as produced by the formatting system) is always localized.

Did not help:

![ArcoLinux_2023-02-05_08-29-40](https://user-images.githubusercontent.com/78153320/216803559-8071edf5-8872-4469-b3a3-eea15e46625e.png)

![ArcoLinux_2023-02-05_08-36-08](https://user-images.githubusercontent.com/78153320/216803613-b1daa3fc-410c-45ee-b6d9-261636d96a33.png)

**Comment by 237dmitry** [comment]
> that for-display representations aren't part of PowerShell's commitment to backward compatibility.

You (not you personally) always have something wrong to blame Net Core

**Comment by jhoneill** [comment]
A change was made and I was one of the people who called for it. 

In Windows PowerShell 5.1 you get this 
```
[pscustomobject] @{ dollar = 1.95; monat = 20.01; pie = 22/7 }, [pscustomobject] @{  dollar = 1.1; monat = 20.1; pie = 3.1  ;  }

dollar monat              pie
------ -----              ---
  1.95 20.01 3.14285714285714
   1.1  20.1              3.1
```

The decimal points don't line up and we rarely need 10 places of decimals. 

In PowerShell 7.3 "N" formatting is applied so if your culture says "," as a decimal separator and 3 places of decimals, that is what you will get. If it says "." and 2 places you get that. 


```
 [pscustomobject] @{ dollar = 1.95; monat = 20.01; pie = 22/7 }, [pscustomobject] @{  dollar = 1.1; monat = 20.1; pie = 3.1  ;  }

dollar monat  pie
------ -----  ---
  1.95 20.01 3.14
  1.10 20.10 3.10
```

As @mklement0 has said there do seem to be inconsistencies between the number of places of decimals running on linux and on windows - where most cultures are 2 places, which is ideal for their currency.

**Comment by 237dmitry** [comment]
> In Windows PowerShell 5.1 you get this

Okay, but you have to be smart about making these changes. Let the user round the value to the desired decimal place.

- User has better control over output
- User receives not a string, but is forced to format the output, he has no other choice, but the real type of a non-integer numeric value (double).

```powershell
[pscustomobject] @{
    aaa = 1
    bbb = [math]::round(1.123456,1)
}

aaa     bbb
---     ---
  1     1.1

# not

aaa     bbb
---     ---
  1   1.100 
```
Or are you of the opinion that the user should complicate his scripts? One switch to display a table with formatted string values, and the other to display a full-fledged object?

 `10/9` -- Great explanation

**Comment by 237dmitry** [comment]
> In PowerShell 7.3 "N" formatting is applied so if your culture says "," as a decimal separator and 3 places of decimals, that is what you will get. If it says "." and 2 places you get that.

What does the category separators, comma, period, or even a hyphen have to do with the topic.

![ArcoLinux_2023-02-05_17-19-05](https://user-images.githubusercontent.com/78153320/216824879-58696cde-334a-4d87-87fd-f4f622767656.png)

**Comment by mklement0** [comment]
> I expect in table view the same values as in list view:

You shouldn't. Space is limited in table view. In list view, more information can and _should_ be presented.
Alignment of values isn't usually important in list view. If you need it, you can use the approach from [my previous comment](https://github.com/PowerShell/PowerShell/issues/19107#issuecomment-1416907732),

> Did not help [changing to `en-US`]

No one said it would. The decimal mark is incidental to this discussion; I was just addressing @rhubarb-geek-nz's comment about it, by explaining that PowerShell's for-display output-formatting system is culture-sensitive.

>  Let the user round the value to the desired decimal place.

With `Format-Table` output, the solution is even simpler (`f2` asks for 2 decimal places, and alignment is handled by `Format-Table`):

```powershell
[pscustomobject] @{ dollar = 1.95; monat = 20.01; weather = 'clear' },
[pscustomobject] @{ dollar = 11.95; monat = 120.01; weather = 'foggy' } | 
  Format-Table @{ e='dollar'; f='f2' }, @{ e='monat'; f='f2' }, weather
```

> What does the decimal separators, comma, period, or even a hyphen have to do with the topic?

The decimal mark  and thousands-grouping character _per se_ have no relevance to this discussion, but the fact that _the effective culture (locale) determines the default formatting of numbers_ does.

Again, it is somewhat unfortunate that even a _given_ culture such as `en-US` exhibits different behavior _across platforms_, but PowerShell is just the messenger here.

The article [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) suggests that these difference should no longer exist in .NET 5+ on recent Windows 10 versions and (I presume) on Windows 11, so it may be worth raising this issue at https://github.com/dotnet/runtime/issues.

**Comment by 237dmitry** [comment]
> You shouldn't.

Tables are often output to a file. Various statistics, ten or more columns.

> With Format-Table output, the solution is even simpler

Get object from script and format in console? Such a pleasure. Scripts may return an object, not a table. Depending on what needs to be received, a table, a list, or a single value the output is processed in the console. How to find the optimal solution? That is the question. I will make a branching in scripts so that they output data depending on the parameters (switches).

> so it may be worth raising this issue at https://github.com/dotnet/runtime/issues.

Possibly, but I'm not qualified enough for that. It is difficult for me to formulate the issue.

**Comment by mklement0** [comment]
> Tables are often output to a file.

Never expect _for-display_ formatting to produce something that is suitable for _programmatic_ processing - it is solely intended for the _human observer_ - whether it prints directly to the display or redirected to a file.

> Scripts may return an object, not a table. 

Well-behaved scripts only ever return _data_ (objects), _not their for-display representation_.

Given _data_, PowerShell decides on what it _presumes_ to be the best _for-display_ representation based on simple rules (`4` or fewer (public) properties -> table; `5` or more -> list) - _unless_ the output objects's type is covered by type-specific [predefined formatting files](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Format.ps1xml).

Currently, it isn't possible for a given script or function to control the for-display formatting of its output objects _itself_ - it requires a formatting file, as usually provided in the context of an enclosing _module_.

The following issue proposed enabling a self-contained script/function solution, but, unfortunately, it didn't go anywhere:
* #10463

**Comment by 237dmitry** [comment]
> Never expect for-display formatting to produce something that is suitable for programmatic processing

Real task. For viewing metadata tags of music files off entire album. In Windows use `ogv`, on linux output  to `/tmp/get-tags.txt` +` mcview` (viewer of Midnight Commander) to view it. As `/tmp` is mounted with `tmpfs` it is by fact the RAM.

For example this is raw metadata of a track:
```
ARTIST=Cigarettes After Sex
TITLE=Don't Let Me Go
ALBUM=Cry
DATE=2019
TRACKNUMBER=01
GENRE=Alternative
ALBUMARTIST=Cigarettes After Sex
rating=5
ADDED_TIMESTAMP=132611399741178108
FIRST_PLAYED_TIMESTAMP=132611399741178108
LAST_PLAYED_TIMESTAMP=132611399741178108
PLAY_COUNT=1
```

Plus fields with boolean values `LIRICS` and `COVER`:

![ArcoLinux_2023-02-06_05-49-21](https://user-images.githubusercontent.com/78153320/216872362-e6d01440-a1a4-4693-8bb6-6ca8780ed88c.png)

**Comment by mklement0** [comment]
As many times before, @237dmitry, it's unclear how your comment relates to the arguments that have been made.

**Comment by 237dmitry** [comment]
> it's unclear how your comment relates to the arguments that have been made.

I do not know English, translate online. Sometimes I am lazy to open google translate and so there are overlays.

**Comment by SteveL-MSFT** [comment]
I think @mklement0 has graciously explained the intent of the current design as well as provided workarounds for custom formatting.

We cannot predict what the user wants exactly, but as noted, the default table views are intended for interactive use and any programmatic use can use the available custom table formatting feature to format it however you'd like or need.

**Comment by 237dmitry** [comment]
> I think @mklement0 has graciously explained the intent of the current design as well as provided workarounds for custom formatting.

I don't think so. He didn't explain why you decided that the pscustomobject + table view should add trailing zeros to the non-integer output.

You've decided (for everyone) that non-integer output would look better with two digits (on Linux, three) after the delimiter. Great idea. Round down only that values which have more than two digits after separator.

```
1.1234  #  Ok        1.123
1.1     #  What???  1.100 
```

Why are you so cruel to users?

**Comment by iSazonov** [comment]
> Why are you so cruel to users?

:smile: It is common standard. We follow .Net and use current culture for formatting. For numbers it is [System.Globalization.CultureInfo]::CurrentCulture.NumberFormat.NumberDecimalDigits. So you can configure OS culture and adjust the value as you need.

**Comment by 237dmitry** [comment]
> So you can configure OS culture and adjust the value as you need.

What culture do I need to achieve the desired result?

![ArcoLinux_2023-02-05_17-19-05](https://user-images.githubusercontent.com/78153320/216824879-58696cde-334a-4d87-87fd-f4f622767656.png)

**Comment by iSazonov** [comment]
See https://github.com/dotnet/runtime/issues/45308#issuecomment-735438395

**Comment by 237dmitry** [comment]
Thank you:
```powershell
PS > [Globalization.CultureInfo]::CurrentCulture.NumberFormat.NumberDecimalDigits = 2
PS > [pscustomobject] @{ aaa = 1.0; bbb = 1.01 }                                     

 aaa  bbb
 ---  ---
1.00 1.01
```
But the trailing zeroes issue is opened. And this works only with invariant culture.

**Comment by iSazonov** [comment]
> But the trailing zeroes issue is opened.

I don't see such option on Windows. You could look ICU and if it has such option, you could ask .Net to add it.

**Comment by mklement0** [comment]
@237dmitry, while you're setting the right property in principle, note that `[cultureinfo]::CurrentCulture` is _read-only_, so you'll have to create a read-write copy first, modify that, and then assign it to  `[cultureinfo]::CurrentCulture`; e.g.:

```powershell
[cultureinfo]::CurrentCulture = & { ($clone=[cultureinfo]::CurrentCulture.Clone()).NumberFormat.NumberDecimalDigits = 2; $clone }
[pscustomobject] @{ aaa = 1.0; bbb = 1.01 }
```

**Comment by 237dmitry** [comment]
> note that [cultureinfo]::CurrentCulture is read-only

I really had such an error on Linux, but only once. But then it didn't show up again. Tried on Windows, no errors. I don't remember under what conditions this exception occurred. Thanks for the advice, I'll keep it in mind, maybe it will come in handy in another similar situation.

**Comment by mklement0** [comment]
@237dmitry, it's not about the host platform, its about PS Core vs. WinPS: in PS Core (.NET), `[cultureinfo]::CurrentCulture` is read-only (always, in my tests; error message "Instance is read-only."), in WinPS (.NET Framework) - surprisingly - it is read-write.

**Comment by 237dmitry** [comment]
>  its about PS Core vs. WinPS: in PS Core (.NET), [cultureinfo]::CurrentCulture is read-only (always, in my tests; error message "Instance is read-only.")

This works if a specific culture was previously set with `System.Threading.Thread`. I think it's similar to the `Clone()` method.

```
[Threading.Thread]::CurrentThread.CurrentCulture = 'inv'            # without this will be error "read-only"
[CultureInfo]::CurrentCulture.NumberFormat.NumberDecimalDigits = 2  # no errors
```

**Comment by mklement0** [comment]
As for avoiding trailing zeros:

While .NET does provide a way to make decimal places optional, by using `#` instead of `0` in the format string, the optional places are simply _omitted_ (rather than replaced with spaces), so that the resulting strings don't align by the decimal mark:

```powershell
# Left-space-padded to 6 chars. overall, but decimal marks NOT aligned
PS> 12.3, 1.34, 123 | % { [string]::Format('{0,6:.##}', $_) }
  12.3
  1.34
   123
```

As @iSazonov notes, you may have to propose an enhancement to .NET; possibly:
 * Suggest a refinement to the padding syntax (`,6` above) that results in alignment by the decimal mark, say `{0,6f:.##}`

For now, you'd have to roll your own:

```powershell
# Left-space-padded to 10 chars. overall,  no trailing zeros, with decimal marks aligned.
0.9, 12.3, 1.34, 123, 1000.12345 | % { 
  '{0,10:N2}' -f $_ -replace 
    ('(\{0})([^0]*)(0+)$' -f [cultureinfo]::CurrentCulture.NumberFormat.NumberDecimalSeparator), 
    { $_.Groups[1].Value * [bool] $_.Groups[2].Value.Length  + $_.Groups[2].Value + ' ' * $_.Groups[3].Length }
}
```

Output:

```none
      0.9 
     12.3 
      1.34
    123  
  1,000.12
```

**Comment by 237dmitry** [comment]
There are no problems with processing the table view. But only on the condition that the user himself prepares the pscustomobject. But if it is obtained dynamically, then there may be a situation where the names of the parameters and their order are not known. And, unforeseen breakdowns of scripts may occur when moving from powershell to pwsh.

Separators themselves become, as in the culture settings:
```
0.9, 12.3, 1.34, 123, 1000.12345, 1.0 | % {  '{0,10:0.##}' -f $_  }
       0.9
      12.3
      1.34
       123
   1000.12
         1
```

**Comment by mklement0** [comment]
Your example repeats the first one  from my previous comment, so I'm unclear on what you're trying to say. 
I also cannot make sense of the paragraph above, but note the following:

* Changes in _display formatting_ are _not_ considered breaking changes; display formatting is for the _human observer_, and shouldn't be relied on for _programmatic_ processing.

* At least technically, the `Format-Table` code could implement decimal-mark-aligned  display without trailing zeros, as shown above, however:
  * Without support at the .NET level, that would be cumbersome, and performance may become an issue.
  * Even with .NET support, the question is whether there's sufficient interest in the community to make such a change. If you feel strongly about this, I suggest creating a focused _feature request_.

* If you want a generic solution for now - which would undoubtedly be cumbersome, slow, and limited - write a proxy function for `Format-Table`  that creates `[pscustomobject]` clones of all input objects, with any `[single]`, `[double]` and `[decimal]` properties replaced with _string_ properties with the desired custom formatting applied, and assign the original type names to `.pstypename`, then forward to `Format-Table`. The challenge is that you'd have to make assumptions about column widths, and that may clash with the width specified in formatting files.

**Comment by 237dmitry** [comment]
> Changes in display formatting are not considered breaking changes; display formatting is for the human observer, and shouldn't be relied on for programmatic processing.

That's exactly what I mean. The user himself must decide where zeros are needed and where not. But the decision was made for him. Maybe he needs `1.25399` instead of `1.25`, but now he will have to deal with formatting and alignment. Who would come up with this "clever" idea?

```powershell
[pscustomobject] @{                  
     aaa = [math]::Round(123.123456,1)
     bbb = [math]::Round(789.10111213,5)
}

   aaa    bbb
   ---    ---
123.10 789.10    <------ What the...?
```
```powershell
[pscustomobject] @{
    aaa = [string][math]::Round(123.123456,1)
    bbb = [string][math]::Round(789.10111213,5)
}

aaa   bbb  ----------> We are used to seeing numbers on the right, shouldn't it look like a string?
---   ---
123.1 789.10111
```
```powershell
[pscustomobject] @{                  
    aaa = [string][math]::Round(123.123456,1)
    bbb = [string][math]::Round(789.10111213,5)    
} | ft @{ e='aaa'; a='right' }, @{ e='bbb'; a='right' }   <---- Who dreams to align 10-fields table?

  aaa       bbb
  ---       ---
123.1 789.10111
```

**Comment by 237dmitry** [comment]
> That's what custom formatting via calculated properties is for.

I'm talking about Joe, and you're talking about John again. You must be a lawyer in the pscustomobject department.
The user can use these tables as he sees fit. View in the console or output to a file or print.

And this is only in pscustomobject, other table views are still working, maybe only until the next release.


```
 $ @{hash = 1.01; table = 1.123 }

Name                           Value
----                           -----
hash                           1,01
table                          1,123
```

**Comment by mklement0** [comment]
Dear John:

They're not "working" if you want alignment; try `@{hash = 1.01; table = 11111.123; more = 100/ 9 }`

`[hashtable]` table views are scontrolled by specific formatting data (relating to the type of the hashtable _entries_, `System.Collections.DictionaryEntry`):
* They only ever have two columns, so there's less of a space concern.
* Also, hashtable values can be of any type, and are independent objects, not the values of a given property of (usually) input objects of uniform type. 
* The formatting data makes no attempt to control alignment or number formatting (which results in left alignment, and in (culture-sensitive `.ToString()` formatting).

I have no opinion on whether hashtable table formatting should be aligned with that of non-dictionary objects with respect to floating-point values.

By `[pscustomobject]` instances cannot be governed by a formatting file, because there are no known-in-advance properties that formatting could be defined for.
Thus, `Format-Table` must provide reasonable defaults.

**Comment by mklement0** [comment]
However, a case could be made that `Format-Table`'s  `-AutoSize` switch should result in the same `.ToString()` behavior as in `Format-List` view (with only as many decimal places as needed, capped at `16` significant digits overall), but _with alignment at the decimal mark_.

Again, that would call for a new, focused feature request.

**Comment by 237dmitry** [comment]
Here's what I want:

- values in tables should be as they are
- the user himself must control the view of them

That's all I want.

![think-02](https://user-images.githubusercontent.com/78153320/217882270-4f123aeb-bc5e-428a-af6d-c9d500c8a395.png)
![think-03](https://user-images.githubusercontent.com/78153320/217882310-70bc119e-c631-48df-867e-31774e9ad2e3.png)

**Comment by jhoneill** [comment]
Well stop making bad custom objects then
Really that is the problem @237dmitry , you are artificially making something with a particular number of decimals and expecting the format process to apply different formatting which changes for each number.  We can all write code which does something stupid. Try calculating the tangent of 90 degrees for example. 

Take this bit of code. 
```
(1/2), (2/3), (3/4) , (4/5), (5/6)| % { 
   [pscustomobject][ordered]@{"Scale"=$_; "Diameter"=($_*144); "Circumference"=($_*144*[math]::pi) }}
```
 
Should it output 
```
            Scale Diameter    Circumference
            ----- --------    -------------
              0.5       72 226.194671058465
0.666666666666667       96  301.59289474462
             0.75      108 339.292006587698
              0.8    115.2 361.911473693544
0.833333333333333      120 376.991118430775
```

Or 
```
Scale Diameter Circumference
----- -------- -------------
 0.50    72.00        226.19
 0.67    96.00        301.59
 0.75   108.00        339.29
 0.80   115.20        361.91
 0.83   120.00        376.99
```

I originally made a request that to fix the problem in the first, format table could take a parameter for number formatting for all columns. This became a simpler "Apply local number format", which defines separator and decimal places. 


> And this is only in pscustomobject, 
No it is anything where format-table does not have formatting information for the number

try
```

(Get-Process -Id $pID).TotalProcessorTime 

(Get-Process -Id $pID).TotalProcessorTime | ft -a *
#or  
 (Get-Process -Id $pID).TotalProcessorTime | select totalM*
```

In my case the former shows a _list_ with 2.428125 for total minutes. I'm not sure who works in minutes and cares about the last millionth of a minute. 
The latter show 2.43 which is more useful, to most people, most of the time. 
You can be as obtuse or as stubborn as you want, but most of the time the extra digits are unhelpful, and especially the varying number of digits, are unhelpful. If the code looked at the first item to decide on the format, that would be wrong, and often excessive. 

```
 (Get-Process pwsh).TotalProcessorTime | select TotalMinutes

      TotalMinutes
      ------------
 0.201302083333333
 0.544270833333333
0.0216145833333333
        2.43203125
```
Is a **lot** less helpful than
```
(Get-Process pwsh).TotalProcessorTime | select TotalMinutes     

TotalMinutes
------------
        0.20
        0.54
        0.02
        2.43
```

**Comment by 237dmitry** [comment]
> I originally made a request that to fix the problem in the first, format table could take a parameter for number formatting for all columns. This became a simpler "Apply local number format", which defines separator and decimal places.

Thank you.

I don't have enough nerves. Ten times I correct the translation in the translator, showing pictures))

I really hope for you personally, I think you can somehow help with this.

By the way, thanks for fixing the bug with Get-Process's command line output . Previously, the output was without spaces, like this `pwsh-Nologo-Noprofile`

**Comment by mklement0** [comment]
To answer my own question:

> the `N` standard number format results in two decimal place on Windows, and three on Unix-like platforms; e.g., `'{0:N}' -f (1/9)` yields `0.11` on Windows, and `0.111` on Unix-like platforms.

As it turns out, even though .NET 5+ moved to ICU in principle, on _Windows_ you _in effect_ still get NLS date-time / number / calendar / currency settings, because the values in `HKEY_CURRENT_USER\Control Panel\International` are still honored _by default_, and these values (unless modified by the user) are a (static) copy of the NLS settings for a given culture.

Therefore, for _consistent_ ICU behavior (you _partially_ get it by default, but only with respect to string comparisons and sorting, ... other behaviors?), an _opt-in_ is required; expressed in PowerShell code:

```powershell
# ICU opt-in.
[cultureinfo]::CurrentCulture = [cultureinfo]::DefaultThreadCurrentCulture = 
  [cultureinfo]::GetCultureInfo([cultureinfo]::CurrentCulture.Name)
```


See https://github.com/dotnet/runtime/issues/81853#issuecomment-1424974267 for a more detailed summary.

**Comment by 237dmitry** [comment]
> for a more detailed summary.

Good comment. Three digits on Windows, just like on Linux. I correctly understood that your code blurs the line between displaying some formats on different platforms?

**Comment by mklement0** [comment]
Yes, the statement in my previous comment (`[cultureinfo]::CurrentCulture = [cultureinfo]::DefaultThreadCurrentCulture = 
  [cultureinfo]::GetCultureInfo([cultureinfo]::CurrentCulture.Name)
`) makes PowerShell use ICU on _all_ platforms.

Note that the setting applies _session-wide_, so restoring the original settings may be required if other code should not be affected.

This will _typically_ result in cross-platform consistency, but note that it isn't _guaranteed_:
Because the ICU libraries do not ship with .NET, it is the _platform's_ libraries that matter, and they can be on different versions across platforms.

For instance, on Windows 11 22H2 the [ICU](https://icu.unicode.org/) version is 68.2.0.10, whereas on macOS Ventura 13.1 it is 70.1

.NET offers a mechanism to bundle / reference specific ICU libraries with / in an _application_ (which doesn't help in PowerShell): https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu
