### ISSUE TITLE
Text piped to Out-Host displays broken characters

### ISSUE THREAD

**Issue by comiluv** [PowerShell/PowerShell#19115]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install Korean localized Windows 11
2. wsl --help | Out-Host -Paging
3. see error

### Expected behavior

```console
Unicode characters are preserved
```

### Actual behavior

```console
Unicode characters are broken
```

### Error details

```console
n/a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

error:
<img width="867" alt="화면 캡처 2023-02-08 113224" src="https://user-images.githubusercontent.com/19642705/217413831-eb4c1a6b-b6b4-4721-afd7-106f639d67b7.png">

expected:
<img width="867" alt="2023-02-08 112937" src="https://user-images.githubusercontent.com/19642705/217413778-62d3d7c6-6adb-4f0f-aa9c-326c66f39d4d.png">

**Comment by mklement0** [comment]
`wsl --help` exhibits nonstandard behavior in that it outputs UTF-16LE-encoded strings instead of respecting the console's code page.

The solution is to (temporarily) set `[Console]::OutputEncoding` to match that encoding:

```powershell
[Console]::OutputEncoding  = [System.Text.Encoding]::Unicode
```

**Comment by comiluv** [comment]
closing as it's wsl.exe problem
