### ISSUE TITLE
[Feature Request] PowerShell Device and Drivers

### ISSUE THREAD

**Issue by agowa338** [PowerShell/PowerShell#1911]
Currently there is no way to manage devices and drivers from PowerShell (or from any other managed code).
I want to request implementation of these commands:
Uninstall-DeviceDriver -Force -DeleteDriver -Device <Device>(like you would from Device Manager)
Install-DeviceDriver -Device <Device> (installing a driver for e.g. an "Unknown Device")
Get-DeviceDriver -Device <Device> (Returns information about the currently used driver)
Get-Device (Returns Device Objects)

**Comment by lzybkr** [comment]
Are you looking for cmdlets to manage Windows, or all platforms?

**Comment by agowa338** [comment]
For Windows, but others would be nice too, somehow.

**Comment by oising** [comment]
query drivers like this:

`driverquery /fo csv /v | convertfrom-csv | sort "driver type", "display name" | ft "module name", "display name", state, "start mode" -groupby "driver type" | more`

Also you could use pnptutil.exe to add/enumerate/delete packages. For full command line driver tinkering, there's also devcon.exe (part of the windows SDK) - https://msdn.microsoft.com/en-us/library/windows/hardware/ff544707(v=vs.85).aspx

**Comment by oising** [comment]
oh, and: https://networchestration.wordpress.com/2016/07/11/how-to-obtain-device-console-utility-devcon-exe-without-downloading-and-installing-the-entire-windows-driver-kit-100-working-method/

**Comment by oising** [comment]
Oh... @lzybkr -- look what I found :) Source! https://github.com/Microsoft/Windows-driver-samples/tree/master/setup/devcon

**Comment by agowa338** [comment]
@oising Thats true, but pnptutil.exe cannot uninstall the driver, only remove it from the store
and devcon is a separate download, you cannot assume it to be present on the target machine, and including as base64 and out-fileing it isn't good practice and even that doesn't provide the flexibility of PSRemoting like other cmdlets do...

Also all of the current ways feel like crude hacks around the core issue.

**Comment by oising** [comment]
@agowa338 I'm with you -- just trying to fill in some gaps. :)

**Comment by agowa338** [comment]
@oising I'm very pleased to hear that, so do I ;-)

**Comment by jdhitsolutions** [comment]
Submitted to the Cmdlet Working Group for consideration and discussion.

**Comment by doctordns** [comment]
It's an attractive suggestion - but as ever the devil is in the details.

One thought - could someone use Crescendo to wrap driverquery and pnputil to create at least some cmdlets?

perhaps a Drivers module with such code that also includes drivercon from Github?

**Comment by jdhitsolutions** [comment]
Do commands in the `PnpDevice` module which ships with PowerShell fill in any of these gaps?

**Comment by agowa338** [comment]
Hi @jdhitsolutions,

The PnpDevice module has these Functions:
* Disable - Allows disabling a device
* Enable - Allows enabling a device
* Get - Allows to query devices
* Get Properties - Allows to query properties

**However, what's missing is**:
* Uninstall - As you would from Device Manager so that the device is no longer available and needs to be rediscovered. As well as to allow deleting an old (may be buggy) driver before reinstalling.
* Install - Installing a driver for e.g. an "Unknown Device", same as the "select from list" and "select from file" within device manager. Also to replace a currently installed driver with another one.
* Set Properties - Update properties of drivers that have options in the driver's menu in the device manager (like Bluetooth, network, serial/parallel-port, ... drivers)
* Handling of non-pnp drivers
* Refresh - Scan for hardware change
* Install non-pnp driver
* Query data from the Events tab of a device driver
* Power Management - Allow configuring the power management settings (e.g. "Allow the computer to turn this device to save power" on and off)
* Set write-cache policies of disk drives

**Comment by TobiasPSP** [comment]
A comprehensive device management module would indeed be very useful for many users. The available module “PnPDevice” with its rather limited capabilities was added during the “Windows PowerShell” timeframe. It is no longer actively maintained. 
With the advent of cross-platform “PowerShell”, the PowerShell team focuses on the core automation engine and general features that are platform-independent. Since device management is highly OS specific with no dependencies to the PowerShell engine, this would be a perfect example for the community to invest in a comprehensive modern device management module. 
For the mentioned reasons, the PowerShell team is not able to evolve the PnPModule. Its status is “frozen”at the current feature level and exists primarily for backwards compatibility, similar to “Windows PowerShell”
