### ISSUE TITLE
When reading host input using `$Host.UI.ReadLine()`, pressing Ctrl-C does not stop the execution of follow-up .NET method calls

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#19112]
### Steps to reproduce

1. Run the following code snippet:
    ```
   $out = $Host.UI.ReadLine()
   $Host.UI.WriteLine('Input done: ' + $out)
   ```
2. While the `.ReadLine()` call is waiting for input, press `Ctrl-C`.
3. Observe that the second line was also executed.

### Context

As noted in #12101, .NET methods are not interrupted when Ctrl-C is pressed. For example, run `[System.Threading.Thread]::Sleep(5000)` and try pressing Ctrl-C. Additionally, a block of .NET methods is executed together, and Ctrl-C only interrupts the command after the whole block finishes. For example, try running `[System.Threading.Thread]::Sleep(2000); $Host.UI.WriteLine("print")` and pressing Ctrl-C during the sleep. The second line is still executed.

However, for PowerShell cmdlets, Ctrl-C is registered immediately. If you replace the `.WriteLine` call in the previous example with `Write-Host`, it's not executed.

The issue is that `$Host.UI.ReadLine()` internally checks for Ctrl-C and returns with `null` when it's pressed. This results in the PowerShell runtime executing more code after the `.ReadLine()` call, as long as the follow-up statements are also .NET method calls. See the following examples:

Both prints are executed when Ctrl-C is pressed while waiting for input:
```
$out = $Host.UI.ReadLine()
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
```

Nothing is executed after Ctrl-C, as the PowerShell runtime has control in the `Read-Host` cmdlet:
```
$out = Read-Host
$Host.UI.WriteLine('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
```

Nothing is executed after Ctrl-C, as the PowerShell runtime receives control in the `Write-Host` cmdlet and stops:
```
$out = $Host.UI.ReadLine()
Write-Host ('Input done: ' + $out)
$Host.UI.WriteLine('Input done: ' + $out)
```

Nothing is executed, as the for loop gives control back to the PowerShell runtime:
```
$out = $Host.UI.ReadLine()
for ($i = 0; $i -lt 10; $i++) {
	$Host.UI.WriteLine('Input done: ' + $out)
}
```

### Proposed solution

I assume that checking if Ctrl-C was pressed between .NET method calls might be too expensive in terms of performance. However, it might be feasible to stop execution inside the `.ReadLine()` call when Ctrl-C is detected. Alternatively, just documenting this behavior (and the interaction of Ctrl-C with .NET calls in general) might be enough.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
The interactive WG discussed this and we agree that the inconsistency in checking for interrupts is not ideal, but we feel that adding additional checks would not have the impact needed to balance out the risk involved.

---

Some additional notes from me: there are two different aspects here.

1. > Additionally, a block of .NET methods is executed together, and Ctrl-C only interrupts the command after the whole block finishes
3. And also (and the main thing behind #17633) we don't really have a way to cancel an input request. See #19664 for a description of all the issues I've had attempting to do it in PSES over the years

As a workaround, if you want to inject a check for stops with the least amount of extra code gen possible, add this where you'd like:

```ps
do {} until ($false)
```

When not debugging it's roughly two extra field accesses and branch instructions.
