### ISSUE TITLE
Get-NetIPConfiguration succeeds but fills up $Error variable with noise

### ISSUE THREAD

**Issue by Borgquite** [PowerShell/PowerShell#19125]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following code in PowerShell 7.3.2:
```
$Error.Clear()
Get-NetIPConfiguration | Out-Null
$Error
```

### Expected behavior

```console
The command should run successfully without errors in $Error automatic variable.
```

### Actual behavior

```console
The command succeeds but creates 'noisy' errors in the $Error automatic variable.

If the underlying module is using -ErrorAction SilentlyContinue could it be changed to -ErrorAction Ignore to prevent these noisy errors?
```

### Error details

```console
Get-NetRoute: No matching MSFT_NetRoute objects found by CIM query for instances of the ROOT/StandardCimv2/MSFT_NetRoute
 class on the
CIM server: SELECT * FROM MSFT_NetRoute  WHERE ((DestinationPrefix LIKE '0.0.0.0/0')) AND ((InterfaceAlias LIKE
'OpenVPN Wintun')). Verify query parameters and retry.


Get-NetRoute: No matching MSFT_NetRoute objects found by CIM query for instances of the ROOT/StandardCimv2/MSFT_NetRoute
 class on the
CIM server: SELECT * FROM MSFT_NetRoute  WHERE ((DestinationPrefix LIKE '::/0')) AND ((InterfaceAlias LIKE 'OpenVPN
Wintun')). Verify query parameters and retry.


Get-NetConnectionProfile: No MSFT_NetConnectionProfile objects found with property 'InterfaceAlias' equal to 'OpenVPN Wi
ntun'.  Verify the value
of the property and retry.


Get-NetRoute: No matching MSFT_NetRoute objects found by CIM query for instances of the ROOT/StandardCimv2/MSFT_NetRoute
 class on the
CIM server: SELECT * FROM MSFT_NetRoute  WHERE ((DestinationPrefix LIKE '::/0')) AND ((InterfaceAlias LIKE 'WiFi')).
Verify query parameters and retry.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/53898223/217856413-aa3595fa-3e59-43d7-a8d5-ef6ec81c9faa.png)

**Comment by mklement0** [comment]
The [CDXML](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/cdxml-overview)-based cmdlets from the `NetTCPIP` module, such as `Get-NetIPConfiguration` unfortunately use `-ErrorAction SilentlyContinue`  in their implementation in cases where `-ErrorAction Ignore` would suffice, namely when a command's errors are not only to be silenced, but can also be ignored.
  
_Conceivably_, the CDXML cmdlet-generation code predates v3 of PowerShell, when the `Ignore` value was introduced.

If you're only interested in the errors emitted by `Get-NetIPConfiguration` _itself_ or _intentionally passed through_, use the [common `-ErrorVariable` parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_CommonParameters#-errorvariable).

**Comment by Borgquite** [comment]
@daxian-dbw Umm... @mklement0's answer explains **why** this is an issue and how it **could* be fixed (updating the CDXML cmdlets to use -ErrorAction Ignore) - but that's not a fix! Please can you re-open this!

**Comment by daxian-dbw** [comment]
@Borgquite Thanks for clarifying. The CDXML module `NetTCPIP` is not owned by the PowerShell team, so your request will have to go through the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) (changed to use the "Resolution-External" label).

**Comment by Borgquite** [comment]
@daxian-dbw Thanks for that. I have reported in the feedback hub and for anyone else experiencing the same issue you can upvote it here: https://aka.ms/AAjlt18

**Comment by mklement0** [comment]
Thanks, @Borgquite.

@daxian-dbw, out of curiosity: Does the CDXML _generation_ code live in _this_ repository? If so, is it worth creating another issue _here_ in order to discuss how this generation works?

**Comment by daxian-dbw** [comment]
@mklement0 The script cmdlet `Get-NetIPConfiguration` is not generated from CDXML, but is defined in `NetIPConfiguration.psm1` of the module `NetTCPIP`. So, it has nothing to do with the script generator for the CDXML files.

**Comment by mklement0** [comment]
Thanks for clarifying, @daxian-dbw.

On a related note: For non-insiders is there simple guidance that can be provided to determine whether a given Microsoft-authored module is maintained here or not (short of searching through the source code)?

It looks like checking if the "Version" dropdown list on the left side of the documentation pages shows a _Windows_ version rather than a _PowerShell_ version is a good indicator, e.g.:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/588825/220940394-0f754b66-05ee-4e7b-a035-f0e234cd88be.png">

Is that sufficient?

It's probably worth adding such guidance to the issue template.

**Comment by DarkLite1** [comment]
Same issue, fixed it like this with the help of [StackOverflow](https://stackoverflow.com/questions/75335166/faulty-powershell-cmdlets-filling-up-error-automatic-variable):
```powershell
Function Get-NetIPConfigurationHC {
    $HashCode = if ($Error) { $Error[0].GetHashCode() }
    Get-NetIPConfiguration
    While($Error -and $Error[0].GetHashCode() -ne $HashCode) { $Error.RemoveAt(0) }
}
```
