### ISSUE TITLE
 Error hit when install AzureAD module in Linux/Debian

### ISSUE THREAD

**Issue by Icybiubiubiu** [PowerShell/PowerShell#19127]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Env:
OS Version: Debian GNU/Linux 11 (bullseye) Kernel: Linux 5.10.0-21-cloud-amd64
powershell version: PowerShell 7.3.2

successfully to install latest powershell following this document:
https://learn.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.3

Errors:
1. when install AzureAD module and import Azure Ad module, always hit errors:

![image](https://user-images.githubusercontent.com/61815812/217901787-e8d38984-d62e-4ba3-a4bf-73b831197c20.png)

PS /home/icy> import-module AzureAD
Import-Module: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

ASK:
1. whether powershell and AzureAD module is supported in Linux?
2. if yes, please help to investigate this issue.

### Expected behavior

```console
Azure AD module could be imported successfully
```

### Actual behavior

```console
PS /home/icy> import-module AzureAD
Import-Module: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

### Environment data

```powershell
Env:
OS Version: Debian GNU/Linux 11 (bullseye) Kernel: Linux 5.10.0-21-cloud-amd64
powershell version: PowerShell 7.3.2

successfully to install latest powershell following this document:
https://learn.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.3
```

**Comment by jborean93** [comment]
> whether powershell and AzureAD module is supported in Linux?

It's not, it mentions on Windows hosts and .NET Framework in https://learn.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0. It also mentions that the module is deprecated and to start using the graph module instead

> Azure AD PowerShell is planned for deprecation. For more details on the deprecation plans, see the [deprecation update](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/azure-ad-change-management-simplified/ba-p/2967456). You can start trying [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview) to interact with Azure AD as you would in Azure AD PowerShell. In addition, Microsoft Graph PowerShell allows you access to all Microsoft Graph APIs and is available on PowerShell 7. For answers to frequent migration queries, see the [migration FAQ](https://learn.microsoft.com/en-us/powershell/azure/active-directory/migration-faq?view=azureadps-2.0).

Luckily the graph module is cross platform and will work on Linux/macOS just fine.

**Comment by ArmaanMcleod** [comment]
Related #18892
