### ISSUE TITLE
`OSDisplayVersion` property is missing from `Get-ComputerInfo`

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19120]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Windows PowerShell, as of at least v5.1.22621.963 (as found on Windows 11 22H2), now supports a ([currently undocumented](https://learn.microsoft.com/en-US/dotnet/api/Microsoft.PowerShell.Commands.ComputerInfo?view=powershellsdk-1.1.0)) `OSDisplayVersion` property, with a value such as `22H2`:

```powershell
(Get-ComputerInfo).OSDisplayVersion
```

This property should be added to PowerShell Core's implementation too.

### Expected behavior

```console
22H2
```

(for instance; should be whatever value 
`Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DisplayVersion` returns)

### Actual behavior

```console
No output.
```

### Environment data

```powershell
PowerShell Core v7.3.2 (.NET 7.0.2) on Microsoft Windows 11 Pro (ARM 64-bit Processor; Version 22H2, OS Build: 22621.1105)
```

**Comment by CarloToso** [comment]
`(Get-ComputerInfo).OSDisplayVersion` --> No Output 
PowerShell 5.1.19041.2364, OS Windows 10 22H2

**Comment by 237dmitry** [comment]
> (Get-ComputerInfo).OSDisplayVersion --> No Output

Because this property does not exist

**Comment by mklement0** [comment]
@CarloToso, you're on Windows _10_.
Note what it says in the initial post:
> Windows PowerShell, as of at least v5.1.22621.963 (as found on Windows 11 22H2)

**Comment by CarloToso** [comment]
@mklement0 I was just confirming the property does not exist in Windows 10

**Comment by BobBuildingCode** [comment]
This is still an issue with PowerShell 7.3.9.

**Comment by andreybrasil** [comment]
This is still an issue with PowerShell 7.4.10.
