### ISSUE TITLE
Update New-FileCatalog -CatalogVersion default to 2

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#19131]
### Summary of the new feature / enhancement

Now that Windows 7 is no longer supported please update `New-FileCatalog -CatalogVersion` to `2`. Here is the section from the help documenation.

> However, `1.0` is the only supported algorithm on Windows 7 and Server 2008R2.

### Proposed technical implementation details (optional)

Change this line to 2.

https://github.com/PowerShell/PowerShell/blob/2f43013df380e6ea1f04ddcf32d9efdefa9ae6a3/src/Microsoft.PowerShell.Security/security/CatalogCommands.cs#L163

**Comment by ThomasNieto** [comment]
@kilasuit can we get the WG to review this?

**Comment by minerva26** [comment]
https://instagram.com/_breeeeendaa?igshid=NTc4MTIwNjQ2YQ==

**Comment by SydneyhSmith** [comment]
@security-wg discussed this, and we agree that updating the default to 2 makes the most sense, while leaving 1 as an option

**Comment by ThomasNieto** [comment]
I'll get a PR created for this.
