### ISSUE TITLE
Powershell 7 in Windows PE

### ISSUE THREAD

**Issue by Andrew74L** [PowerShell/PowerShell#19138]
### Summary of the new feature / enhancement

Are there plans to allow PS7 installation into [WinPE](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro?view=windows-11)?
I'm hoping this occurs by the time PS7 is included in Windows.

### Proposed technical implementation details (optional)

Following a process similar to [this](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-adding-powershell-support-to-windows-pe?view=windows-11) would add Powershell 7 support to WinPE.

**Comment by SteveL-MSFT** [comment]
PS7 works on WinPE.  I'll reach out to that team to update their install instructions.

**Comment by Andrew74L** [comment]
> PS7 works on WinPE. I'll reach out to that team to update their install instructions.

I don't see an official update yet, but I followed Johan Arwidmark's [script](https://www.deploymentresearch.com/adding-powershell-7-to-winpe/) and got PS7 working in PE.
