### ISSUE TITLE
cannot chsh to powershell without editing /etc/shells

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#1913]
Steps to reproduce
------------------
`chsh -s /usr/bin/powershell`

Expected behavior
-----------------
should be able to change the shell to powershell

Actual behavior
---------------
it says `/usr/bin/powershell is an invalid shell`

Environment data
----------------

```powershell
> $PSVersionTable
alpha.9

```

**Comment by TravisEz13** [comment]
I suggest that the package should add PowerShell as a Shell and remove it when it is removed.

**Comment by mmckinst** [comment]
needs to have --after-install and --after-remove options added at https://github.com/PowerShell/PowerShell/blob/33fcdf37e558e9e9a7800b01a083e65f4127d7fd/build.psm1#L1082-L1102 for this with a shell script like below:

```
# after-install
if ! [ -f /etc/shells ] || ! grep -q '^/usr/bin/powershell$' /etc/shells; then
  echo '/usr/bin/powershell' >> /etc/shells
fi

# after-remove
sed -i '\!^/usr/bin/powershell$!d' /etc/shells
```

**Comment by jldeen** [comment]
Just tested on Ubuntu 14.04.05 and was able to chsh by first adding the path /opt/microsoft/powershell/6.0.0-alpha.9/powershell to /etc/shells 

Then I typed sudo chsh -s /opt/microsoft/powershell/6.0.0-alpha.9/powershell. Note: I received the following errors, but still seemed to work. 

sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting

I then changed the shell back by typing chsh -s /bin/bash
