### ISSUE TITLE
wait keyword/cmdlet for async tasks

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#19141]
### Summary of the new feature / enhancement

As a user I want to be able to call dotnet async methods/tasks and get the result easily. Currently I need to remember to do

```powershell
$task = $class.MethodAsync()
while (-not $task.AsyncWaitHandle.WaitOne(200)) {}
$task.GetAwaiter().GetResult()
```

This is a handful to remember and annoying to write.  I could theoretically just do `$class.MethodAsync().GetAwaiter().GetResult()` or `$class.MethodAsync().GetAwaiter().Result` but the while loop and GetResult is preferred as:

* It will respond to ctrl+c/stop events during each loop iteration (every 200ms) vs hang until the method is complete
* `.Result` will ignore any exceptions due to how pwsh ignores exceptions in property getters

Being able to just do `wait $class.MethodAsync()` is a lot simpler and less things that can go wrong. PowerShell can also ensure that the engine is able to response to stop events if requested and that exceptions are checked and raised if occurred in the async task.

### Proposed technical implementation details (optional)

Essentially something like

```powershell
Function wait {
    param($Task)

    while (-not $Task.AsyncWaitHandle.WaitOne(200)) {}
    $Task.GetAwaiter().GetResult()
}

wait $class.MethodAsync()
```

But it would probably need to be a compiled cmdlet to take advantage of `StopProcessing`. Not sure if it should be a keyword instead and implemented that way.

**Comment by jborean93** [comment]
I'm happy to write this myself and submit a PR but wanted confirmation that the concept would at least be accepted in PowerShell before doing the work.

**Comment by rhubarb-geek-nz** [comment]
My understanding is that while this pattern can work in simple cases it can result in deadlocks in more complicated scenarios if the task is not started in another thread. There is also the question of whether `ConfigureAwait(false) `should be used.

**Comment by SeeminglyScience** [comment]
`ConfigureAwait(false)` won't actually have an effect when you're waiting synchronously. There is of course risk of dead locks when blocking until a task completes but no more than when calling `GetAwaiter().GetResult()` on your own. Worth bringing up though for sure.

**Comment by JamesWTruher** [comment]
The WG discussed this today, and while we don't believe that this should be a new keyword (especially in the light of clobbering anyone that has implemented a function with this name), we would be interested in a gallery module/cmdlet to cover this behavior. It would be possible to more fully build out the behavior (timeout/etc) with a cmdlet approach.

**Comment by jborean93** [comment]
Seems a bit silly to have to download a module for something I believe should be included in the actual engine. It reminds me of the whole leftpad problem in the node environment. This is also a C# language feature that will appear in more and more methods. I'll continue doing it the manual way but it would be great if this could be reconsidered at a future point in time.
