### ISSUE TITLE
Strange: [PSCustomObject] blocks the output of [hash]

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#19140]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

write code to a ps1 file instead of pasting at the command line
a.ps1 

```powershell
$psc1 = [pscustomobject] @{
	one = 'o'
	two = 't'
}
$psc1 

$hash22 = @{
	aa = 1
	bb = 2
}
$hash22
```
If the line [$psc1] is commented, the $hash22 output is normal

### Expected behavior

```console
one two
--- ---
o   t


Name                           Value
----                           -----
aa                             1
bb                             2
```

### Actual behavior

```console
one two
--- ---
o   t
```

### Environment data

```powershell
powershell 5.1.19041.1320 on win10
PowerShell 7.4.0-preview.1 on win10
```

**Comment by mklement0** [comment]
The behavior is surprising, but currently by design. In short, the _first_ object's properties _alone_ determine the output columns. If later objects don't have these properties, they effectively don't display.
Improvements are discussed in:
* #7871

**Comment by kasini3000** [comment]
thanks for your reply

**Comment by IISResetMe** [comment]
FWIW you can force PowerShell to render the output of one statement before proceeding to the next:

$psc1 = [pscustomobject] @{
    one = 'o'
    two = 't'
}
$psc1 |Out-Host   # this will complete the output rendering of `$psc1` before the next statement

$hash22 = @{
    aa = 1
    bb = 2
}
$hash22  # no longer hidden
