### ISSUE TITLE
Running powershell under emacs results in an error

### ISSUE THREAD

**Issue by mcraveiro** [PowerShell/PowerShell#1914]
Hi Powershellers,

Thanks for a fantastic project. I just tried using Powershell on Linux (Debian Testing) and it runs fine on a terminal so that is great news! Now, on Windows, I normally consume Powershell from within Emacs thanks to the amazing Powershell Mode[1]. On Linux, this did not work so well, with the shell failing to start. Whilst trying to get to the bottom of this, I decided to start Powershell within Emacs via bash and I got the following rather strange behaviour:

```
 $ /usr/bin/powershell
PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

[6n[6nPS /home/marco> [6n[6n

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
[6n[[6n
```

Characters such as `[6n[6n` appear without any key presses. Not really sure what could be causing this?

Many thanks for your time.

Marco

[1] https://www.emacswiki.org/emacs/Powershell.el

**Comment by kilasuit** [comment]
Firstly I think this may be to do with PSReadline so I'm adding in @lzybkr 

Does it happen when you try running powershell with the -noprofile switch ?

**Comment by mcraveiro** [comment]
Hi @kilasuit,

Thanks for the prompt reply. I'm afraid I get the exact same behaviour even with ```-noprofile```. I get these spurious characters appearing after a few seconds or so - not sure if it makes any difference. They stop after a while and then I get the above exception.

Cheers

**Comment by andschwa** [comment]
Hello! I just want to say that it makes me *incredibly* happy to see someone using PowerShell under Emacs!

I just want to give a quick hypothesis: this looks to me like an `System.Console` API we're depending on unexpectedly returned 0 (because of the Emacs `TERM` it's running under); probably something like `BufferWidth`; which of course isn't very useful.

Also, the `�[6n�[6n` you're seeing are *likely* just the ASCII colors (again, a guess; I'm not an termcap code expert, I'd have to look it up).

**Comment by mcraveiro** [comment]
Aha, great theory @andschwa! So if I use Emacs' ansi-term then suddenly Powershell behaves just like it does in a regular terminal. Sadly, this is not a solution for Powershell Mode.

**Comment by mcraveiro** [comment]
Also, FWIW, when in regular shell:

```
$ echo $TERM
dumb
```

**Comment by andschwa** [comment]
90% chance if you set TERM to dumb even in a proper emulator like xterm, the same problems will arise. We might be able to be outsmart System.Console; but really we should file a bug with CoreFX.

@mcraveiro are you using this particular fork of [PowerShell mode](https://github.com/jschaf/powershell.el)?

**Comment by mcraveiro** [comment]
@andschwa good point - I installed it from ELPA/MELPA/etc (```package-list-packages```), without paying too much attention. Didn't realise it had been forked.

**Comment by andschwa** [comment]
As far as I could tell, there half a dozen forks floating around. That appears to be the most recently maintained one.

**Comment by mcraveiro** [comment]
By the by, tried using ```dumb``` within a regular gnome terminal. Not quite the same behaviour as Emacs, but a certain amount of oddness to it:

```
$ export TERM=dumb
$ echo $TERM      
dumb
$ powershell      
PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS /home/marco> PS /home/marco> l                                                               
PS /home/marco> ls  
<snip>
PS /home/marco> 
PS /home/marco> PS /home/marco> e
                                PS /home/marco> ex
                                PS /home/marco> exi
                                PS /home/marco> exit                                                            
```

Cheers

Marco

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#467
