### ISSUE TITLE
Hashtable conditional property assignment breaks for empty arrays

### ISSUE THREAD

**Issue by chscott** [PowerShell/PowerShell#19143]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Assignment of an empty array to a hashtable property works when set directly but does not work when set conditionally. Example, where $bar is undefined:
```
C:\Users\Chad\Downloads> $foo = @{
>> Body = if ($bar) { 'bar' } else { @() }
>> }
C:\Users\Chad\Downloads> $foo

Name                           Value
----                           -----
Body

C:\Users\Chad\Downloads> $foo | ConvertTo-Json
{
  "Body": null
}
C:\Users\Chad\Downloads> $foo = @{ Body = @() }
C:\Users\Chad\Downloads> $foo

Name                           Value
----                           -----
Body                           {}

C:\Users\Chad\Downloads> $foo | ConvertTo-Json
{
  "Body": []
}
```

Note that a non-empty array works fine with conditional assignment.

```
C:\Users\Chad\Downloads> $foo = @{
>> Body = if ($bar) { 'bar' } else { @('apple', 'banana', 'cherry') }
>> }
C:\Users\Chad\Downloads> $foo

Name                           Value
----                           -----
Body                           {apple, banana, cherry}
```

### Expected behavior

```console
The empty array should be preserved when using conditional assignment.
```

### Actual behavior

```console
As demonstrated above.
```

### Error details

```console
N/A
```

### Environment data

```powershell
C:\Users\Chad\Downloads> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by mklement0** [comment]
Worth adding:

* A concise - albeit obscure to the uninitiated - alternative to `Write-Output -NoEnumerate @()` is `, @()`

* And speaking of concise: if you use an _expression_ instead of a _language statement_ such as `if`, the enumeration behavior is bypassed. Thus, you can use a ternary conditional - which is an expression - as an alternative:

```powershell
@{
  Body = $bar ? 'bar' : @() 
}.Body.GetType().Name # -> 'Object[]'
```

**Comment by IISResetMe** [comment]
There is one more pre-ternary hack you can employ here:

```
$foo = @{
  Body = @($null,@())[[bool]$bar]
}
```

The result of `[bool]$bar` will eventually be coerced to either `0` (`$false`) or `1` (`$true`) for the array index operation, and thus if `$bar` has a truthy value, `@()` will be assigned to `$foo['Body']`

**Comment by 237dmitry** [comment]
As a workaround:
```
$foo = @{ Body = $bar ? 'bar' : @() }
```
