### ISSUE TITLE
Should `Remove-Item` skip confirmation checks when used with `-Stream` ?

### ISSUE THREAD

**Issue by santisq** [PowerShell/PowerShell#19154]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Remove-Item` prompts for confirmation even though `-Confirm:$false` is used while trying to remove a stream from a folder having child items. `-Recurse` can't be used together with `-Stream`.

```powershell
$folder = New-Item testfolder -ItemType Directory -Force
Set-Content $folder -Value 'teststream' -Stream test
Set-Content (Join-Path $folder 'testfile.ext') -Value ''
Remove-Item $folder -Stream test -Confirm:$false
```

As a workaround we can use `EngineIntrinsics` to remove the alternate stream without confirmation checks however not all folks would know how and this might bring questions in the future, i.e.: https://stackoverflow.com/questions/75442886/remove-alternative-data-stream-using-powershell/75443083.

- Workaround

```powershell
$folder = New-Item testfolder -ItemType Directory -Force
Set-Content $folder -Value 'teststream' -Stream test
Set-Content (Join-Path $folder 'testfile.ext') -Value ''
$ExecutionContext.InvokeProvider.Item.Remove((Get-Item $folder -Stream test).PSPath, $false)
Get-Item $folder -Stream test
```

### Expected behavior

```powershell
PS> Remove-Item $folder -Stream test -Confirm:$false
PS> Get-Item $folder -Stream test

Get-Item: Could not open the alternate data stream 'test' of the file ...
```

### Actual behavior

```powershell
PS> Remove-Item $folder -Stream test -Confirm:$false

The item at path\to\testfolder has children and the Recurse parameter was not specified. If you        
continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

### Error details

```console
No errors.
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
`$ConfirmPreference` does not work in this case too.
