### ISSUE TITLE
NVIDIA-SMI and NVIDIA Driver won't work in Microsoft PowerShell terminal but fine in other terminals

### ISSUE THREAD

**Issue by RosterMouch** [PowerShell/PowerShell#19158]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have install WSL2 VM at a none c:/ disk,which the ext4 image located at e(due to my c:/ drive doesn't have enough space to store my files).
So the bug is that: When i want to launch Ubuntu22.04 dist and type `nvidia-smi` in PowerShell like this:
```powershell
PS C:\Users\98246> wsl.exe --version
WSL 版本： 1.0.3.0
内核版本： 5.15.79.1
WSLg 版本： 1.0.47
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.1105
PS C:\Users\98246> wsl -d Ubuntu-22.04
(base) elin@ElinsStation:/mnt/c/Users/98246$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

Failed to properly shut down NVML: Driver Not Loaded

(base) elin@ElinsStation:/mnt/c/Users/98246$
```
It raise the error like this,which meaning the `nvidia-smi` program which in my WSL2 vm doesn't recognize the NVIDIA Driver.
But when i launch the same dist in MobaXterm and type the same command,it working fine properly:
```ascii
(base) elin@ElinsStation:~$ nvidia-smi
Wed Feb 15 20:49:23 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   54C    P0    29W /  80W |   1055MiB /  6144MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        21      G   /Xwayland                       N/A      |
|    0   N/A  N/A        21      G   /Xwayland                       N/A      |
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
|    0   N/A  N/A       211      C   /python3.9                      N/A      |
+-----------------------------------------------------------------------------+
(base) elin@ElinsStation:~$
```
The first time i though it might me a WSL2 Kernel error or vm error,so i reinstall the dist vm and WSL Kernel,but it still have this problem.
I google it this issuse,someone says make a linking of wsl/lib folder or reinstall cuda on host machine would be fine,but in my side it still not work.
That's might not a crtical bug,but pretty annoying for the developer who love use PowerShell to debugging WSL2 program workflows.

### Expected behavior

```console
Please fix this issuse,that's might not a crtical bug,but pretty annoying for the developer who love use PowerShell to debugging WSL2 program workflows.
```

### Actual behavior

```console
Got no idea to write this.
```

### Environment data

```powershell
the version of this bug error raised are below:

WSL 版本： 1.0.3.0
内核版本： 5.15.79.1
WSLg 版本： 1.0.47
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.1105

Host CUDA Version:
```powershell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```
Ubuntu WSL2 VM CUDA Version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```
Host NVIDIA Video Driver Version:GeForce GameReady Driver 528.49
```


### Visuals

_No response_

**Comment by 237dmitry** [comment]
Is nvidia module loaded?

```
lsmod | grep 'nvidia'
```
> But when i launch the same dist in MobaXterm and type the same command,it working fine properly

It is possible that this Xserver is loading the required modules. Try load by hand:
```
sudo modeprobe nvidia
```

**Comment by RosterMouch** [comment]
> Is nvidia module loaded?
> 
> ```
> lsmod | grep 'nvidia'
> ```
> 
> > But when i launch the same dist in MobaXterm and type the same command,it working fine properly
> 
> It is possible that this Xserver is loading the required modules. Try load by hand:
> 
> ```
> sudo modprobe nvidia
> ```
> 
> _It is not clear what powershell has to do with this_

I will have a try and bring your reply as soon as possible.

**Comment by RosterMouch** [comment]
> Is nvidia module loaded?
> 
> ```
> lsmod | grep 'nvidia'
> ```
> 
> > But when i launch the same dist in MobaXterm and type the same command,it working fine properly
> 
> It is possible that this Xserver is loading the required modules. Try load by hand:
> 
> ```
> sudo modprobe nvidia
> ```
> 
> _It is not clear what powershell has to do with this_

Hi i tried all command,it seems it doesn't detect the module of NVIDIA Driver yet.Output below:
```ascii
(base) elin@ElinsStation:~$ lsmod | grep 'nvidia'
(base) elin@ElinsStation:~$ sudo modprobe nvidia
[sudo] password for elin:
modprobe: FATAL: Module nvidia not found in directory /lib/modules/5.15.79.1-microsoft-standard-WSL2
(base) elin@ElinsStation:~$
```

**Comment by RosterMouch** [comment]
> > Is nvidia module loaded?
> > ```
> > lsmod | grep 'nvidia'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > But when i launch the same dist in MobaXterm and type the same command,it working fine properly
> > 
> > 
> > It is possible that this Xserver is loading the required modules. Try load by hand:
> > ```
> > sudo modprobe nvidia
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _It is not clear what powershell has to do with this_
> 
> Hi i tried all command,it seems it doesn't detect the module of NVIDIA Driver yet.Output below:
> 
> ```
> (base) elin@ElinsStation:~$ lsmod | grep 'nvidia'
> (base) elin@ElinsStation:~$ sudo modprobe nvidia
> [sudo] password for elin:
> modprobe: FATAL: Module nvidia not found in directory /lib/modules/5.15.79.1-microsoft-standard-WSL2
> (base) elin@ElinsStation:~$
> ```

Also forget to tell you that `nvidia-smi` is also work in the visual studio code and dedicated distro.exe like below
![image](https://user-images.githubusercontent.com/75596885/219547867-e1f13d5c-7ec0-465a-9e34-8bc15516807e.png)
![image](https://user-images.githubusercontent.com/75596885/219548027-11b02a8d-18cd-4bf0-a851-262258453c9e.png)
Weried!Pretty weried,here is my boot attributes in Powershell:
![image](https://user-images.githubusercontent.com/75596885/219548252-28adb12a-73d7-4f1c-bb7e-15cce0c9ac4b.png)
I also post this issuse to the repo of PowerShell yet,hope Microsoft Team can fix that lol😂

**Comment by daxian-dbw** [comment]
I don't think this has anything to do with PowerShell. All you did in PowerShell was to start `wsl -d Ubuntu-22.04`. Can you run `wsl -d Ubuntu-22.04` from CMD.exe and see if `nvidia-smi` works in that case?

**Comment by RosterMouch** [comment]
> 

Still not working:
![image](https://user-images.githubusercontent.com/75596885/219824312-403452f7-7017-450e-a807-ec831a439359.png)

**Comment by RosterMouch** [comment]
> I don't think this has anything to do with PowerShell. All you did in PowerShell was to start `wsl -d Ubuntu-22.04`. Can you run `wsl -d Ubuntu-22.04` from CMD.exe and see if `nvidia-smi` works in that case?

So i'm guessing is that error caused by WSL command?I boot directly from the stand alone distro.exe in here and it's work.
![image](https://user-images.githubusercontent.com/75596885/219824599-e494e4fa-8aec-45ad-a05b-ade08c774a1e.png)

**Comment by RosterMouch** [comment]
Funny thing:I turn off the boot option `Run this terminal as Administrator` and both `wsl -d Ubuntu-22.04` and use `Ubuntu-22.04` section worked.
Close issue by fix it.
