### ISSUE TITLE
string like

### ISSUE THREAD

**Issue by lbj2014** [PowerShell/PowerShell#19163]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

describe from https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.3
```
`* - Match any character as a literal (not a wildcard character)
12`*4 matches 12*4
12`*4 doesn't match 1234
```
Why  "1234" -like "12`*4" return True

### Expected behavior

```console
PS > "1234" -like "12`*4"
False
```

### Actual behavior

```console
PS > "1234" -like "12`*4"
True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core 
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iRon7** [comment]
A backtick (`` ` ``) has a special meaning in PowerShell and is used to escape (special) characters, see: [about special character](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_special_characters)
This means that in an expandable string (using double quotes), PowerShell that will either replace a know escaped character (like `` `n ``) with a special character (like a newline) or take the character following the backtick as a literal character, see [about quoting rules](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules)
Thus:
```PowerShell
"12`*4"
```
Will just return:
```PowerShell
"12*4"
```
Which will be considered the matching pattern in your syntax.
To prevent this from happening you should use a **literal** (single quoted) string:
```PowerShell
"1234" -like '12`*4'
False
"12*4" -like '12`*4'
True
```

**Comment by kasini3000** [comment]
PS A:\pscode> "1234" -like "12*4"
True
