### ISSUE TITLE
Need Get-ArchiveItem command

### ISSUE THREAD

**Issue by sglewis09** [PowerShell/PowerShell#19174]
### Summary of the new feature / enhancement

I've been using the **Compress-Archive** and **Expand-Archive** commands and realized that there appears to be no way to list the contents of a zip file created by the existing PowerShell Archive commands.  I think that there should be a way to list the contents of **.zip** files.

My suggestion would be to create a command with a syntax similar to **Get-ChildItem** that lists the contents of a **.zip** file.  Following the current naming conventions for PowerShell commands, I would use the name **Get-ArchiveItem** and would base it on the current **Get-ChildItem** command.

**Comment by ThomasNieto** [comment]
That cmdlet is in a different repo and there is an issue for the this request https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/111
