### ISSUE TITLE
InvokeWeb-Request -WebSession -AllowInsecureRedirect -MaximumRedirection together wrong number of redirections

### ISSUE THREAD

**Issue by CarloToso** [PowerShell/PowerShell#19183]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I think the behaviour when we handle the redirects* and use -MaximumRedirection and -WebSession is incorrect.
Each time we handle a redirection the WebSession.MaximumRedirection parameter is reduced by one.
In the example below it goes from 3 to 0.
When we use the web session I would expect the -MaximumRedirection to be 3 in each follow up request, instead WebSession.MaximumRedirection is 0 and stays 0

Test:
```ps1
Invoke-WebRequest "http://mockbin.org/redirect/300?to=https://mockbin.org/redirect/301?to=http://mockbin.org/redirect/302?to=https://mockbin.org/redirect/303?to=http://mockbin.org/redirect/308?to=https://mockbin.org/status/200" -MaximumRedirection 3 -SessionVariable session -AllowInsecureRedirect
[int]($error[0].Exception.statuscode) #--> 303
$session.MaximumRedirection #--> 0 (i think it should be 3)
Invoke-WebRequest "http://mockbin.org/redirect/300?to=https://mockbin.org/redirect/301?to=http://mockbin.org/redirect/302?to=https://mockbin.org/redirect/303?to=http://mockbin.org/redirect/308?to=https://mockbin.org/status/200" -WebSession $session -AllowInsecureRedirect 
# I expect -MaximumRedirection == 3
[int]($error[0].Exception.statuscode) #--> 300
$session.MaximumRedirection #--> 0
```

If this issue is confirmed, I will fix it in my next PR

* We currently handle the redirects in 3 cases -AllowInsecureRedirect (https to http redirect); -PreserveAuthorizationOnRedirect; -PreserveHttpMethodOnRedirect in the other cases HttpClient handles the redirects

### Expected behavior

```console
After setting -MaximumRedirection 3 it should remain 3 in the following requests
```

### Actual behavior

```console
It changes
```

### Environment data

```powershell
Latest Build
(every build since https://github.com/PowerShell/PowerShell/commit/ca4b6162f49aff1b89fa624a2e059794c740b6cb)
```

**Comment by iSazonov** [comment]
I'd check other WebSession properties too.

**Comment by CarloToso** [comment]
WebSession.MaximumRedirection is the only WebSession property that changes after beeing set.
https://github.com/PowerShell/PowerShell/blob/0be3eeac38e3065fb4cb7dd49d1c86aee4cb04fc/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1241-L1245
