### ISSUE TITLE
Sort-Object not on pipeline

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#19182]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I cannot understand how to sort object without pipeline as this variant is much faster on big data
If I sort via pipeline it works as expected but not if I determine input object as argument

```powershell
$a = @{ aaa = Get-Date; b = 'bbb' },
     @{ aaa = (Get-Date).AddDays(-1); b = 'bbb' }   
     
$res = Sort-Object -Property aaa -Bottom 1 -InputObject $a
$res
     
Name                           Value
----                           -----
b                              bbb
aaa                            2/20/2023 3:42:41PM
b                              bbb
aaa                            2/19/2023 3:42:41PM
```

```powershell                                                         
$a = @{ aaa = Get-Date; b = 'bbb' },
     @{ aaa = (Get-Date).AddDays(-1); b = 'bbb' }   
     
$res = $a | Sort-Object -Property aaa -Bottom 1            
$res

Name                           Value
----                           -----
b                              bbb
aaa                            2/20/2023 3:43:00PM
```

```powershell
Get-Command Sort-Object -Syntax

Sort-Object [[-Property] <Object[]>] [-Stable] [-Descending] [-Unique] [-InputObject <psobject>] [-Culture <string>] [-CaseSensitive] [<CommonParameters>]

Sort-Object [[-Property] <Object[]>] -Top <int> [-Descending] [-Unique] [-InputObject <psobject>] [-Culture <string> ] [-CaseSensitive] [<CommonParameters>]

Sort-Object [[-Property] <Object[]>] -Bottom <int> [-Descending] [-Unique] [-InputObject <psobject>] [-Culture <string>] [-CaseSensitive] [<CommonParameters>]
```

### Expected behavior

```console
Sort-Object should work as expected in both variants -- input object via pipeline or as argument to -InputObject parameter
```

### Actual behavior

```console
Sort-Object does not work as expected.
```

### Error details

```console
No errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Linux 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by scriptingstudio** [comment]
`-InputObject` does not enumerate its value
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-7.3#-inputobject

**Comment by mklement0** [comment]
For the backstory, see

* #4242

**Comment by 237dmitry** [comment]
> -InputObject does not enumerate its value

Multiple objects cannot be sorted? Only properties of a single one?
```diff
- The second day I can not optimize the script by replacing pipelines
+ What I was able to do was to optimize from 7 to 5 seconds by replacing pipes in sls
```
There is the `Group-Object` also  which also works strangely without pipeline.

**Comment by mklement0** [comment]
You have been given two separate pointers as to what the problem with your attempt to use `-InputObject` _directly_ is.

It would be helpful if you engaged with the information provided by these pointers instead of posting provoking questions.

`Group-Object` doesn't meaningfully support `-InputObject` either.

In short: Only those cmdlets that are explicitly designed to accept arrays as `-InputObject` arguments, or accept `object` and perform on-demand enumeration based on reflection, meaningfully support passing arrays (enumerables) _directly_ to `-InputObject`. 

With few exceptions , it's best to think of `-InputObject` as an _implementation detail_ for facilitating _pipeline input_, i.e. an auxiliary parameter that isn't meant to be used _directly_.

That is indeed unfortunate, but rooted in the fundamentals of the current design.
If you want to weigh in on a potential future solution (which may or may not ever come to pass), feel free to join the discussion at https://github.com/PowerShell/PowerShell/issues/4242.

**Comment by 237dmitry** [comment]
Ok, I thought it was possible to sort the array of hashtables like this. 

> instead of posting provoking questions.

Provoking for what?

**Comment by mklement0** [comment]
> Provoking for what?

I took your comment to be sarcastic, given that (a) you already know how to sort multiple objects (namely via the pipeline), and (b) had already been given an explanation for why passing directly to `-InputObject` cannot be expected to work.

If you weren't sarcastic, I apologize for jumping to that conclusion, but the advice to engage with the information you have already been given still applies (I do realize that there may be a language barrier).

---

To answer your specific questions in detail:

> Multiple objects cannot be sorted? 

No, you cannot sort objects by passing them to `-InputObject`.
Multiple objects passed to `-InputObject` are treated as a _single_ (collection-type) object (an _array_ object in your case, which has no `.aaa` property / entry), whereas sorting only ever meaningfully applies to _multiple_ objects.

Applying `Sort-Object` to a _single_ input object is always a no-op.

Note that a hashtable - even though it is technically an enumerable that enumerates its _entries_ - is always considered a _single object_ by PowerShell (to enumerate the entries, call `.GetEnumerator()`).

> Only properties of a single one?

`Sort-Object` sorts multiple _objects_, which are output _as-is_, only in _different order_, i.e. sorted. The sort order is determined either by comparing them as a _whole_ (by default) or by comparing them by the values of property/ies whose name/s are passed to `-Property`.

In the case of a hashtable, its _entries_ are treated _like properties_, with the entry keys being considered the property names.

`Sort-Object` itself fundamentally doesn't support sorting _the properties_ of a _single object_, though you can pass a single input object's `.psobject.Properties` collection / a hashtable's entries via `.GetEnumerator()` (of necessity as _pipeline_ input) and sort either by name/key (`-Property Name`) or value (`-Property Value`).

This means that both the input and output objects will be `System.Management.Automation.PSPropertyInfo` / `System.Collections.DictionaryEntry` instances.
