### ISSUE TITLE
Pasting text into PowerShell is slow on Linux

### ISSUE THREAD

**Issue by diego-crespo** [PowerShell/PowerShell#19181]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I paste a line of text into PowerShell on the Raspberry Pi 8gb there is a noticeable lag in the output of the text. I would normally chalk this up to the Raspberry Pi being underpowered, but the pasting action is much faster in Bash. I've uploaded two short videos demoing what I'm talking about. 

### Expected behavior

```console
I would expect the lines to paste almost instantaneously
```

### Actual behavior

```console
There is a noticeable delay
```

### Environment data

```powershell
PowerShell 7.3.2
```

### Visuals

Video of Bash
https://youtu.be/sGbBTsiohCo

Video of PowerShell
https://youtu.be/k2UPThcN0qw

**Comment by 237dmitry** [comment]
In my environment (X11, clipman):
 shell  | ctrl-v | ctrl-shift-v | mouse | shift-insert (primary) | mouse (primary) |
--------| -------| -------| ------|-----|------|     
pwsh | fast  | slow | slow | slow | slow |
bash | none | fast | fast | fast | fast |

**Comment by mklement0** [comment]
On Unix-like platforms, PowerShell (PSReadLine) uses _simulated typing_ for pasting, which I think is the cause of the slowdown.

See the following for the (long) backstory:

* https://github.com/PowerShell/PSReadLine/issues/579
