### ISSUE TITLE
PSStyle.OutputRendering = "PlainText" or NO_COLOR not working, need to use __SuppressAnsiEscapeSequences

### ISSUE THREAD

**Issue by castortech** [PowerShell/PowerShell#19188]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

First off this issue doesn't appear if running the script from a terminal in VSCode

But I am launching PS scripts from Java and passing values for both PSStyle.OutputRendering & NO_COLOR and I'm able to see that the values are there if I output them during execution.

But the following, which here throws an exception since the store doesn't exist, will produce some Ansi code:
Get-SecretVault -Name xxStore | ConvertTo-Json

Finally found this [issue ](https://github.com/actions/runner/issues/1495#issuecomment-974339936) and decided to also set the __SuppressAnsiEscapeSequences and everything started to work correctly. I would have expected that the other variants would have set that variable, but again showing during execution, it wasn't set, unless I passed the value manually.

### Expected behavior

```console
Get-SecretVault: C:\Users\XXXX\AppData\Local\Temp\psscript_167700463450917082999875903795167.ps1:15
Line |
  15 |  Get-SecretVault -Name xxStore | ConvertTo-Json
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Vault xxStore does not exist in registry.
```

### Actual behavior

```console
[31;1mGet-SecretVault: [0mC:\Users\XXXXX\AppData\Local\Temp\psscript_16770047511711965109290211120660.ps1:15[0m
[31;1m[0m[36;1mLine |[0m
[31;1m[0m[36;1m[36;1m  15 | [0m [36;1mGet-SecretVault -Name xxStore[0m | ConvertTo-Json[0m
[31;1m[0m[36;1m[36;1m[0m[36;1m[0m[36;1m     | [31;1m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[31;1m[0m[36;1m[36;1m[0m[36;1m[0m[36;1m[31;1m[31;1m[36;1m     | [31;1mVault xxStore does not exist in registry.[0m
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
> But I am launching PS scripts from Java

Are you launching `pwsh.exe` from Java?

> passing values for both PSStyle.OutputRendering & NO_COLOR

Can you share how you set values to "PSStyle.OutputRendering & NO_COLOR"?

**Comment by castortech** [comment]
> Are you launching `pwsh.exe` from Java?
Yes, here is the process details:
``` pb = new ProcessBuilder("cmd.exe", "/c", "chcp", codePage, ">", "NUL", "&", powerShellExecutable, "-ExecutionPolicy", "Bypass", "-NonInteractive","-NoExit", "-NoProfile", "-Command", "-"); ```

where powerShellExecutable here is pwsh.exe
> 
> > passing values for both PSStyle.OutputRendering & NO_COLOR
> 
> Can you share how you set values to "PSStyle.OutputRendering & NO_COLOR"?
Essentially we set the process environment to include the required values.
```//this is to make sure that we don't get any ANSI codes in returned error stream content.  
Map<String, String> environment = pb.environment();  
environment.put("PSStyle.OutputRendering", "plaintext");  
environment.put("__SuppressAnsiEscapeSequences", "1");  //finally what worked for me, but not well documented, opened issue in PS github  
environment.put("NO_COLOR", "1");```

**Comment by JamesWTruher** [comment]
Setting PSStyle as an _environment_ variable isn't going to work as `PSStyle` is a _powershell_ variable rather than an environment variable.
