### ISSUE TITLE
Error in help URI for module: Microsoft.PowerShell.Operation.Validation, SqlServer

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#1918]
On Windows 10 Anniversary Update, I'm getting this error:

> Save-Help : Failed to save Help for the module(s) 'Microsoft.PowerShell.Operation.Validation, SqlServer' with UI
culture(s) {en-US} : The value of the HelpInfoUri key in the module manifest must resolve to a container or root URL
on a website where the help files are stored. The HelpInfoUri 'https://www.msn.com/?ocid=NEFLS000' does not resolve to
a container.
At line:1 char:16
+ mkdir \pshelp; save-help -DestinationPath c:\pshelp
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Save-Help], Exception
    + FullyQualifiedErrorId : InvalidHelpInfoUri,Microsoft.PowerShell.Commands.SaveHelpCommand

To repro, simply run `Save-Help`. Looks like a bad MSN URI in the module manifest.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by kilasuit** [comment]
The SQL Server one has been previously reported to the SQL Team via Uservoice so should be getting fixed though have your installed the August 2016 version of SSMS ?

Though the HelpInfoUri link in Microsoft.PowerShell.Operation.Validation directs to a broken link so this may need to be raised on the OVF repo if not already raised.

**Comment by juneb** [comment]
There are so many of these. I just wrote a blog post about it.
http://info.sapien.com/index.php/scripting/scripting-help/helpuri-v-helpinfouri

Also:
DellBiosProvider, LXCAPSTool, WSAProvder...

**Comment by SteveL-MSFT** [comment]
@JamesWTruher did you make this fix on GitHub as well?

**Comment by JamesWTruher** [comment]
nope - this module is not part of PowerShell Core
