### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by xmha97** [PowerShell/PowerShell#19184]
### Summary of the new feature/enhancement

What is the latest version that works on Windows 7?
"PowerShell-7.3.0-preview.8-win-x64"?

**Comment by daxian-dbw** [comment]
Windows 7 is out of support. I think the last version that works on Win7 is [v7.2.7](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.7).

**Comment by xmha97** [comment]
> Windows 7 is out of support. I think the last version that works on Win7 is [v7.2.7](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.7), but didn't try it myself.
> 
> If you're asking about preview versions, then yes, [v7.3.0-preview.8](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.0-preview.8) is the last preview release that works on Win7.

Ok, thanks 👍

**Comment by Temik007** [comment]
Solution - https://github.com/PowerShell/PowerShell/issues/19816

**Comment by greenozon** [comment]
7.2.22 works  just fine on Windows 7 SP1 x64
