### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by gk4delltech** [PowerShell/PowerShell#19192]
### Name of the Distribution

openSUSE Leap

### Version of the Distribution

15.4

### Package Types

- [ ] Deb
- [X] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

x86_64

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by gk4delltech** [comment]
FYI, when building powershell-7.3.2-linux-x64.tar.gz on openSUSE Leap 15.4 is links to openssl 1.0.0 instead of 1.1.1 which is outdated.

**Comment by jborean93** [comment]
> FYI, when building powershell-7.3.2-linux-x64.tar.gz on openSUSE Leap 15.4 it links to openssl 1.0.0 instead of 1.1.1 which is outdated.

Are you sure that's not just the libmi stuff which is only used for WSMan/WinRM PSRemoting. PowerShell relies on dotnet to perform TLS work which is linked dynamically at runtime through dlopen calls as per https://github.com/dotnet/runtime/blob/288cdc300cf9c335bbc27a81b37cca21f30d8d9d/src/native/libs/System.Security.Cryptography.Native/opensslshim.c#L55.

**Comment by gk4delltech** [comment]
Thanks for the clarification.   Please close.
