### ISSUE TITLE
Microsoft.PowerShell.SDK .NET C# doesnt work

### ISSUE THREAD

**Issue by MJMODZZ-V3** [PowerShell/PowerShell#19195]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

So I have installed the NuGet package Microsoft.PowerShell.SDK. If i try to do
```cs
using Microsoft.PowerShell.SDK;
```
it gives me following error:
```
Error	CS023
The type or namespace name 'PowerShell' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```
Yes it doesnt appear in references but i installed it throught NuGet. I also reloaded the project and did everything.

im on .NET Framework 4.7.2 Winforms, VS2022

### Expected behavior

```console
using Microsoft.PowerShell.SDK;
```

### Actual behavior

```console
Error	CS0234
The type or namespace name 'PowerShell' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```

### Error details

```console
Check the description up
```

### Environment data

```powershell
Check the description up
```

### Visuals

![image](https://user-images.githubusercontent.com/125826136/220770273-7f4fd66c-4f90-42db-8868-4ed45caf9efe.png)
![image](https://user-images.githubusercontent.com/125826136/220770320-a3ebca6b-b57c-4977-b368-d5474eca0cdb.png)

**Comment by mklement0** [comment]
`Microsoft.PowerShell.SDK` is the name of the NuGet package, but it isn't a _namespace_.

The PowerShell SDK's types are in the `System.Management.Automation` namespace.

**Comment by MJMODZZ-V3** [comment]
> System.Management.Automation

It still gives me the error
```
Error	CS0234
The type or namespace name 'Automation' does not exist in the namespace 'System.Management' (are you missing an assembly reference?)
```

**Comment by MJMODZZ-V3** [comment]
A thing is that it really doesnt pop up in the references but the NuGet package is installed

**Comment by MJMODZZ-V3** [comment]
Also after installing the System.Management.Automation NuGet package it doesnt work

**Comment by mklement0** [comment]
I miessed the following:

> I'm on .NET Framework 4.7.2 Winforms, VS2022

The [`Microsoft.PowerShell.SDK`](https://www.nuget.org/packages/Microsoft.PowerShell.SDK/) NuGet package is the PowerShell _Core_ SDK, which isn't compatible with .NET Framework.

To write a .NET Framework application, you must use the _Windows PowerShell_ SDK, via the [`Microsoft.PowerShell.5.ReferenceAssemblies`](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/) NuGet package.

If you want your code to run in _both_ PowerShell editions - based on preexisting iPowerShell installations - use the [PowerShellStandard.Library](https://www.nuget.org/packages/PowerShellStandard.Library/) NuGet package (used to implement cross-edition cmdlets and PowerShell hosts).

Do _not_ use tthe `System.Management.Automation` NuGet package.

**Comment by MJMODZZ-V3** [comment]
Ive fixed it by adding the reference manually into the csproj

**Comment by mklement0** [comment]
Glad to hear it.

Generally, please note that this repo is only for PowerShell _Core_ (whose SDK runs only on .NET (Core)), not also for _Windows PowerShell_ issues (whose SDK runs only on .NET Framework).
To report Windows PowerShell issues as well as issues with Microsoft-authored modules that aren't maintained in this repository, use the [Feedback Hub application](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

**Comment by MJMODZZ-V3** [comment]
Yea now its fixed so i dont care anymore. In the NuGet package this repo was linked

**Comment by mklement0** [comment]
But it's good that you'll know for the future.

It is appropriate for the [`Microsoft.PowerShell.SDK`](https://www.nuget.org/packages/Microsoft.PowerShell.SDK/) NuGet package page to link here, given that it is the PowerShell _Core_ SDK (and now you know the relationship between the SDKs and the .NET frameworks).

It is unfortunate, however, that the "README" tab on the package page doesn't make that fact clear - it currently just states "Runtime for hosting PowerShell".

Granted, just "PowerShell" is now the preferred name for PowerShell Core, but an explicit delineation would certainly be helpful here.

Perhaps the package read-me can be amended, @SteveL-MSFT?

**Comment by MJMODZZ-V3** [comment]
I just use that automation only for now and my shell backdoor works perfect
