### ISSUE TITLE
System.Management.Automation.PowerShell throws type initializer issue at self-contained .NET6 app

### ISSUE THREAD

**Issue by WD1993** [PowerShell/PowerShell#19206]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

 

       /// <summary>
        /// Get Volume for a drive.
        /// </summary>
        /// <param name="driveLetter">Drive Letter.</param>
        /// <returns>PSObject.</returns>
        private static **PSObject** GetVolumeByDriveLetter(char driveLetter)
        {
            using (**System.Management.Automation.PowerShell** ps = System.Management.Automation.PowerShell.Create())
            {
                ps.AddCommand("Get-Volume");
                ps.AddParameter("DriveLetter", driveLetter);

                Collection<PSObject> result;
                try
                {
                    result = ps.Invoke();
                    CheckPsErrorStream(ps);
                }
                catch (Exception e)
                {
                    throw new InvalidOperationException(
                        string.Format(CultureInfo.InvariantCulture, ServerConfigurationsManagementMessages.VolumeNotFoundByDriveErrorMessage, driveLetter, e.Message));
                }

                return result.First();
            }
        }

### Expected behavior

```console
return correct result of ps command run
```

### Actual behavior

```console
throws exception The type initializer for 'System.Management.Automation.ExperimentalFeature' threw an exception
```

### Environment data

```powershell
Self-contained .NET6 app running as windows service on windows server 2019
```

**Comment by WD1993** [comment]
we understand that https://www.nuget.org/packages/Microsoft.PowerShell.SDK/ should be added but after installing it the error still repros.

**Comment by daxian-dbw** [comment]
What version of `Microsoft.PowerShell.SDK` nuget package are you using for your .NET 6 application? You need to use the 7.2.x nuget packages instead of 7.3.x, because the latter targets .NET 7.

Also, a simple reproducing C# project would be useful for investigating the issue.

**Comment by WD1993** [comment]
I did two repros and found different issues:

### **Repro1:  local ps run under worker service (console app) failed with error "unable to load module"**

vanilla worker service 

```
>   <Project Sdk="Microsoft.NET.Sdk.Worker">
> 
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <Nullable>enable</Nullable>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <UserSecretsId>dotnet-WorkerService1-92239f64-bd21-448d-b5ed-af2739f67167</UserSecretsId>
>     <PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
>     <SelfContained>true</SelfContained>
>     <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
>     <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.2.3" />
>     <PackageReference Include="System.Management.Automation" Version="7.2.3" />
>   </ItemGroup>
> </Project>
```

run following ps command after service up

>         /// <summary>
>         /// Get Volume for a drive.
>         /// </summary>
>         /// <param name="driveLetter">Drive Letter.</param>
>         /// <returns>PSObject.</returns>
>         private static PSObject GetVolumeByDriveLetter(char driveLetter)
>         {
>             using (System.Management.Automation.PowerShell ps = System.Management.Automation.PowerShell.Create())
>             {
>                 ps.AddCommand("Get-Volume");
>                 ps.AddParameter("DriveLetter", driveLetter);
> 
>                 Collection<PSObject> result = new Collection<PSObject>();
>                 try
>                 {
>                     result = ps.Invoke();
>                 }
>                 catch (Exception e)
>                 {
>                     Console.WriteLine(e.Message);
>                     Console.WriteLine(e.StackTrace);
>                 }
> 
>                 return null;
>             }
>         }

error says:
The 'Get-Volume' command was found in the module 'Storage', but the module could not be loaded. For more information, run 'Import-Module Storage'.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at WorkerService1.Worker.GetVolumeByDriveLetter(Char driveLetter) in D:\CodeFactory\WorkerService1\WorkerService1\Worker.cs:line 41



### **Repro2: publish repro1's proj as self-contained and single-file, then type init issue repros:**
 
The type initializer for 'System.Management.Automation.ExperimentalFeature' threw an exception.
   at System.Management.Automation.Runspaces.InitialSessionState.AddVariables(IEnumerable`1 variables)
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke()
   at WorkerService1.Worker.GetVolumeByDriveLetter(Char driveLetter) in D:\CodeFactory\WorkerService1\WorkerService1\Worker.cs:line 41
info: WorkerService1.Worker[0]
      Worker running at: 02/27/2023 09:23:06 -08:00

**Comment by daxian-dbw** [comment]
> publish repro1's proj as self-contained and single-file

PowerShell doesn't yet support .NET single-file application. See a similar issue https://github.com/PowerShell/PowerShell/issues/18109. The PR #18674 may address it but I'm not sure. For now, please don't publish as a single-file.

So, for the `"Storage" module cannot be loaded` error, it may be related to publishing it as a single-file application. You can try directly run `Import-Module Storage` as suggested by the error, and see the error returned by it, which should contain more useful information about why this module cannot be loaded. If possible, you can also run `$env:PSModulePath` in that application and share the result here.

**Comment by WD1993** [comment]
Hi Dongbo thanks for the investigation, for the cannot be loaded error, it doesnt get published as single file app but just run under local as it is, so wondering why issue still there.

**Comment by WD1993** [comment]
After checking with @daxian-dbw type initializer issue is caused by singlefile publish which is not supported with ps right now. however there is a new issue raised after we cancel the singlefile publish. Will open a new issue against it.
