### ISSUE TITLE
Use correct exceptions

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#19212]
### Summary of the new feature / enhancement

In PowerShell code base there are some places where we are not accurate with exceptions.
Typical example: https://github.com/PowerShell/PowerShell/blob/4314e634cadde65a743d359106def376ed1c59ee/src/System.Management.Automation/engine/CommandInfo.cs#L286-L294

Here we throw ArgumentNullException that is not correct if the argument is empty. (There are examples with other exceptions.)

My proposal is to fix such code and throw ArgumentNullException if argument is null and ArgumentException is argument is empty.

This is not even a breaking change, as it is not a functional exception, and it is worth correcting it for the correct one. If someone even uses this behavior in their code, it is catastrophically bad code.

The proposal  comes from the fact that we are blocked from using new .Net API like ArgumentException.ThrowIfNullOrEmpty(). The API makes code more friendly for .Net Rumtime optimizations (like inlining). We already use this kind of API in a lot of places and it's worth updating the rest.

**Comment by daxian-dbw** [comment]
There is no argument around using `ArgumentException.ThrowIfNullOrEmpty()` when it's applicable, so removing the `Review - Maintainer` label, and marking `Up-for-Grabs`.

**Comment by iSazonov** [comment]
`NullOrEmpty` is the most common, but there are others (ex., where Count or Length == 0). (Better to search by `throw new Argument` pattern.)

**Comment by daxian-dbw** [comment]
It's better not mix all together.
- For cases where the existing `ThrowIfXXX` APIs fit properly, it's generally fine to accept the change.
- For cases where the existing `ThrowIfXXX` APIs don't fit, for example, when checking if a collection is `null` or empty, or when checking if an argument or one of its members is `null`, we should not apply the `ThrowIfXXX` APIs blindly. For those cases, please use a different issue to describe the intended changes, for maintainers to review.
