### ISSUE TITLE
Breakpoint actions not invoked after reimporting module with using module statement

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#19222]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create the files below in your current directory and run `debug.ps1`

MainModule.psm1
```ps1
# Everything works when line below is removed
using module .\ClassModule.psm1

function Get-Demo {
    'Finished!'
}
```

ClassModule.psm1
```ps1
# doesn't matter. leave empty
```

debug.ps1
```ps1
Get-PSBreakpoint | Remove-PSBreakpoint

$null = Set-PSBreakpoint -Script ./MainModule.psm1 -Line 5 -Action { Write-Host "Hello from breakpoint $($_.Id) on line $($_.Line)" }

Get-PSBreakpoint | Format-Table -auto

Import-Module -Name './MainModule.psm1' -Force
Get-Demo
Get-Module -Name 'MainModule' -All | Remove-Module -Force

Get-PSBreakpoint | Format-Table -auto

Import-Module -Name './MainModule.psm1' -Force
Get-Demo
Get-Module -Name 'MainModule' -All | Remove-Module -Force
```

### Expected behavior

Breakpoint action are invoked on both runs. This works if you remove the `using module` statement in `MainModule.psm1`.

```ps1
> .\debug.ps1

ID Script          Line Command Variable Action
-- ------          ---- ------- -------- ------
 1 MainModule.psm1    5                   Write-Host "Hello from breakpoint $($_.Id) on line $($_.Line)"

Hello from breakpoint 1 on line 5
Finished!

ID Script          Line Command Variable Action
-- ------          ---- ------- -------- ------
 1 MainModule.psm1    5                   Write-Host "Hello from breakpoint $($_.Id) on line $($_.Line)"

Hello from breakpoint 1 on line 5
Finished!
```

### Actual behavior

Breakpoint action is only invoked after the first module import.

```ps1
> .\debug.ps1

ID Script          Line Command Variable Action
-- ------          ---- ------- -------- ------
 2 MainModule.psm1    5                   Write-Host "Hello from breakpoint $($_.Id) on line $($_.Line)"

Hello from breakpoint 2 on line 5
Finished!

ID Script          Line Command Variable Action
-- ------          ---- ------- -------- ------
 2 MainModule.psm1    5                   Write-Host "Hello from breakpoint $($_.Id) on line $($_.Line)"

Finished!
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by BrucePay** [comment]
Unlike scripts, modules only execute once on first import. Subsequent imports just copy references from the existing instance in the main module table. Since the code only runs once, the breakpoint action only fires once. You can use -force if you want to force them to be (re)executed.

**Comment by fflaten** [comment]
> Unlike scripts, modules only execute once on first import. Subsequent imports just copy references from the existing instance in the main module table. Since the code only runs once, the breakpoint action only fires once. You can use -force if you want to force them to be (re)executed.

I don't follow. The breakpoints in the repro are called by invoking the `Get-Demo`-function, not by any loose code in the `psm1` triggered on import.

**Comment by fflaten** [comment]
Was never triaged. Please reopen
