### ISSUE TITLE
Convertfrom-cipolicy cmdlet error isn't being displayed on the console in PowerShell 7.3.3

### ISSUE THREAD

**Issue by HotCakeX** [PowerShell/PowerShell#19223]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

[SupplementalPolicy.zip](https://github.com/PowerShell/PowerShell/files/10831509/SupplementalPolicy.zip)

Download the SupplementalPolicy.zip file I uploaded, it has a WDAC supplemental policy (.XML file) that has a wrong rule in it. If I run the command below in PowerShell 7.3.3, I don't see any errors and the cmdlet just silently doesn't create the `.cip` file.

```PowerShell
ConvertFrom-CIPolicy .\SupplementalPolicy.xml '{C791D8CB-14C4-4D01-B858-C671C3995287}.cip'
```

But If I run the same command in Windows PowerShell 5.1, it successfully shows me the error message and tells me what's wrong with the XML file.

I upload the XML file myself because explaining how to create it needs a whole blog post.

### Expected behavior

```console
This error should be shown on the console:


ConvertFrom-CIPolicy : Only base policies can have SupplementalSigners.
At line:1 char:1
+ ConvertFrom-CIPolicy .\SupplementalPolicy.xml '{C791D8CB-14C4-4D01-B8 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (Microsoft.Secur...CIPolicyCommand:ConvertFromCIPolicyCommand) [ConvertFrom
   -CIPolicy], CIPolicyException
    + FullyQualifiedErrorId : InvalidPolicyFile,Microsoft.SecureBoot.UserConfig.ConvertFromCIPolicyCommand
```

### Actual behavior

```console
No error is shown on the console
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.25300
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/118815227/221362696-4130955e-a2bd-4103-b797-b2db520f3f98.png)

**Comment by SteveL-MSFT** [comment]
Looks like the problem is that this module isn't compatible with PS7, so it's loaded via WinPS and the error isn't getting propagated back properly
