### ISSUE TITLE
Document which parts of the codebase are frozen

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShell#19220]
>  For `Microsoft.Management.UI.Internal`, we ship it and own the code, so I think it's OK to make changes to it. But
> - for code that we don't build/ship (e.g. `ScheduledJob`, `LocalAccounts`), we should avoid changing it.
> - for the code that came from .NET (e.g. `ComInterop`), we should avoid changing it unless the original code in dotnet/runtime was also updated to use `ArgumentException.ThrowIfNullOrEmpty`.

_Originally posted by @daxian-dbw in https://github.com/PowerShell/PowerShell/issues/19213#issuecomment-1444578761_

Of the above, only `ComInterop` is documented at: `src\System.Management.Automation\engine\ComInterop\README.md`

**Comment by iSazonov** [comment]
Also WinRM code. It is very sensitive.

**Comment by xtqqczze** [comment]
@iSazonov Please reopen
