### ISSUE TITLE
Tab completion should suggest values from variable when completing comparison operator values

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#19234]
### Summary of the new feature / enhancement

In the shell, if you save something to a variable and later want to filter on the values like this:
```
PS C:\> $Disks = Get-Disk
PS C:\> $Disks | where OperationalStatus -eq <Tab>
```
you get no completions unless the property happens to be an enum. This limitation makes sense when it's just working with type inference, but if the variable already contains the data we may as well use it to provide completion results.

Note: It shouldn't override the current enum completion for variable property values because people may still want to be able to filter values that don't appear in the variable data.

### Proposed technical implementation details (optional)

The C# equivalent to `$Disks | Select-Object -ExpandProperty OperationalStatus | Sort-Object -Unique | foreach {New-CompletionResult $_}`

**Comment by adityapatwardhan** [comment]
Thank you for the suggestion! We believe that having a complete solution which works for all operators (like -match, etc. ) and all possible values in the variable seems impossible.

**Comment by MartinGC94** [comment]
@adityapatwardhan But we are already doing it with Enums? I don't feel that extending it to also work with other types is a huge work item. Obviously it will only really work with properties that can be represented as strings but even that is a pretty useful enhancement IMO.
If you still feel like it's an impossible task then that's fine, but I hope that a future PR from me or someone else that does this will be accepted.

**Comment by iSazonov** [comment]
> If you still feel like it's an impossible task

I guess they skipped that the proposal is not for type inference but for real data.
