### ISSUE TITLE
Piping text to a file inserts the BOM on OS/X

### ISSUE THREAD

**Issue by absherwin** [PowerShell/PowerShell#1923]
Steps to reproduce
------------------
"Test">test.txt
cat test.txt

Expected behavior
-----------------
cat should print Test

Note that Set-Content -Path test.txt -Value "Test" produces the expected output without the BOM

Actual behavior
---------------
cat prints ??Test

`type text.txt -Encoding Byte` confirms that the first two bytes are 255 and 254 which is the BOM.

Environment data
----------------

Name                           Value                                              
----                           -----                                              
PSVersion                      6.0.0-alpha                                        
PSEdition                      Core                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                            
BuildVersion                   3.0.0.0                                            
GitCommitId                    v6.0.0-alpha.9                                     
CLRVersion                                                                        
WSManStackVersion              3.0                                                
PSRemotingProtocolVersion      2.3                                                
SerializationVersion           1.1.0.1

**Comment by mihaipopescu** [comment]
Isn't this the same behaviour as on Windows ? checking the encoding it seems that it shouldn't add the BOM

```shell
[Console]::OutputEncoding                                                                                                     


EncodingName    : Unicode (UTF-8)
WebName         : utf-8
IsSingleByte    : False
EncoderFallback : System.Text.EncoderReplacementFallback
DecoderFallback : System.Text.DecoderReplacementFallback
CodePage        : 65001
```

**Comment by oivindoh** [comment]
Title should be redirecting, not piping.

This is a known issue as per https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md

**Comment by andschwa** [comment]
Closing as known issue.
