### ISSUE TITLE
Powershell unable to find dotnet runtime when DOTNET_ROOT is set on Mariner

### ISSUE THREAD

**Issue by sirkiza** [PowerShell/PowerShell#19242]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On Mariner, when DOTNET_ROOT is set, the dotnet runtime cannot be found. 
The same behavior works without issue when using Ubuntu.

```bash
echo $DOTNET_ROOT
dotnet --list-runtimes
pwsh -c "echo Hello"
mkdir -p /tmp/hostedtoolcache/dotnet
export DOTNET_ROOT=/tmp/hostedtoolcache/dotnet
dotnet --list-runtimes
pwsh -c "echo Hello"
```

### Expected behavior

From Ubuntu

```console
> 
> Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> Hello
> Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> Hello
```

### Actual behavior

From Mariner

```console
>
> Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> Hello
> Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> You must install .NET to run this application.
>
> App: /opt/microsoft/powershell/7/pwsh
> Architecture: x64
> App host version: 7.0.3
> .NET location: Not found
>
> Learn about runtime installation:
> https://aka.ms/dotnet/app-launch-failed
>
> Download the .NET runtime:
> https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=mariner.2.0-x64&apphost_version=7.0.3
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
How was PowerShell installed? From a formal package such as https://github.com/PowerShell/PowerShell/releases/download/v7.3.3/powershell-7.3.3-1.cm.x86_64.rpm ?

**Comment by sirkiza** [comment]
@rhubarb-geek-nz

It was installed by package mariner manager: `tdnf install powershell`
Which should be from formal package

**Comment by rhubarb-geek-nz** [comment]
I installed using yum and got

```
Installing:
powershell           x86_64        7.3.3-1.cm       mariner-official-microsoft   112.48M 117946331
```

My /foo/bar does not exist

```
$ export DOTNET_ROOT=/foo/bar     
$ pwsh
PowerShell 7.3.3
PS /home/bythesea> 
```

**Comment by rhubarb-geek-nz** [comment]
Similar runtimes

```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by sirkiza** [comment]
`yum` is just a symlink to `tdnf` so it doesn't make any difference

I believe the reason why it works in your case is because `/foo/bar` doesn't exist.
Sorry should mentioned in the description the part of folder creation...

**Comment by rhubarb-geek-nz** [comment]
What is in your directory pointed to by [DOTNET_ROOT](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_root-dotnet_rootx86) ?

Is it a full copy of the dotnet 7 installation?

**Comment by sirkiza** [comment]
It is empty directory

**Comment by sirkiza** [comment]
The extended scenario I want to make working: this directory contains dotnet 6 for example, but doesn’t contain dotnet 7. On Mariner it doesn’t work… on Ubuntu it works. 
It seems that on Ubuntu powershell looks into default dotnet location as well as inside DOTNET_ROOT. This is the behavior I want also on Mariner.

**Comment by rhubarb-geek-nz** [comment]
I suggest that the purpose of DOTNET_ROOT is to tell dotnet where to find its files. PowerShell is built using dotnet, so it does not surprise me that pwsh run looks for the dotnet binaries there.

Generally on UNIX applications don't check for files in lots of places if they have been given an environment variable indicating where they should be. For example with java you can have multiple installations of java, and then you set JAVA_HOME to point to one of the installations to say that is the one you want to use.

The way the dotnet net files are laid out in /usr/share/dotnet is so that you can have multiple versions of dotnet all in that single tree, you don't need to install different versions of dotnet in different directories, the packages already do that for you. Then the version of dotnet-host is the most recent one and it determines the correct dotnet-hostfxr to use for the version of the application you are running.

What version of Ubuntu are you running and where did the dotnet come from?

Now Ubuntu-22:04 is different because the dotnet from the Ubuntu repositories are not in the same directories as that defined by Microsoft.

```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
```

This is because these are customised by Ubuntu so actually behave differently.

But your file paths on Ubuntu look like they are in the Microsoft defined location.

**Comment by sirkiza** [comment]
Small inconsistency might cause problems...

I am using Ubuntu 22.04.2 LTS. Installed pwsh by [package manager](https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.3#installation-via-package-repository).

Using `PowerShell 7.3.3`

**Comment by sirkiza** [comment]
To bring more clarity that it is not a problem that came from the air.

I am trying to solve issue with running ADO pipelines on Linux agent that has pwsh installed.

There is a commonly used task [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines) that installs dotnet (for example dotnet6 sdk) into specific directory and sets `DOTNET_ROOT` value to that directory (different from default).

After that task I run powershell script. On Ubuntu it works as it searches for the runtime both in DOTNET_ROOT and in `/usr/share/dotnet/`. But on Mariner I receive an error above.

**Comment by rhubarb-geek-nz** [comment]
One difference you have is on Ubuntu you only have dotnet 7 whereas on Mariner you have both dotnet 6 and 7

**Comment by rhubarb-geek-nz** [comment]
And 7.0.0 is installed and it is looking for 7.0.3

**Comment by rhubarb-geek-nz** [comment]
If you installed dotnet-runtime-7.0.3 on Mariner does it fix the problem?

**Comment by rhubarb-geek-nz** [comment]
So my theory is that PowerShell actually comes with its own version of the dotnet runtime, but because you set the DOTNET_ROOT it no longer uses that and wants to find it via the environment variable or default location

**Comment by rhubarb-geek-nz** [comment]
Interesting...

I ran ( in bash ) ...

```
echo exit | ( DOTNET_ROOT=/foo/bar strace pwsh ) 2>trace.log
```

... on both Ubuntu 22.04 and Mariner and only the Mariner trace.log had any mention of /foo

```
$  grep /foo trace.log 
readlink("/foo", 0x7ffdc7b81a90, 1023)  = -1 ENOENT (No such file or directory)
```

So it looks like they are behaving differently.

**Comment by rhubarb-geek-nz** [comment]
And only Mariner had any reference to /usr/share/dotnet 

```
$ grep /usr/share/dotnet trace.log | head
access("/usr/share/dotnet/host/fxr", F_OK) = 0
openat(AT_FDCWD, "/usr/share/dotnet/host/fxr", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
access("/usr/share/dotnet/host/fxr/7.0.3/libhostfxr.so", F_OK) = 0
openat(AT_FDCWD, "/usr/share/dotnet/host/fxr/7.0.3/libhostfxr.so", O_RDONLY|O_CLOEXEC) = 3
access("/usr/share/dotnet/libcoreclr.so", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/dotnet/shared/Microsoft.NETCore.App", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
access("/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.3", F_OK) = 0
readlink("/usr/share/dotnet", 0x7ffdc7b81170, 1023) = -1 EINVAL (Invalid argument)
readlink("/usr/share/dotnet/shared", 0x7ffdc7b81170, 1023) = -1 EINVAL (Invalid argument)
readlink("/usr/share/dotnet/shared/Microsoft.NETCore.App", 0x7ffdc7b81170, 1023) = -1 EINVAL (Invalid argument)
```

**Comment by rhubarb-geek-nz** [comment]
And there Mariner is looking for ... 

```
openat(AT_FDCWD, "/usr/share/dotnet/host/fxr/7.0.3/libhostfxr.so", O_RDONLY|O_CLOEXEC) = 3
```

like I suggested.

**Comment by rhubarb-geek-nz** [comment]
Where as the Ubuntu version is looking straight at it's own copy of dotnet runtime

```
$ grep libhostfxr.so trace.log 
access("/opt/microsoft/powershell/7/libhostfxr.so", F_OK) = 0
openat(AT_FDCWD, "/opt/microsoft/powershell/7/libhostfxr.so", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by sirkiza** [comment]
Interesting. From your logs, it appears that you were trying to open the file `/etc/dotnet/install_location_x64` but received a permission denied error due to insufficient permission

`openat(AT_FDCWD, "/etc/dotnet/install_location_x64", O_RDONLY) = -1 EACCES (Permission denied)`

I tried the following command on Mariner and IT WORKS!

`sudo pwsh --version`

This suggests that the behavior of pwsh/dotnet may change based on whether the file `/etc/dotnet/install_location` is empty or inaccessible. If the file is empty, it seems that pwsh/dotnet searches in `/usr/share/dotnet` first.

I wonder if it is by design or not...

**Comment by sirkiza** [comment]
Doesn't seem like a correct behavior though as it works when `DOTNET_ROOT` is empty...

**Comment by iSazonov** [comment]
Usually pwsh is installed as self-contained app. This assumes that .Net Runtime is installed with pwsh and pwsh uses the private dotnet copy (search for other versions is not performed).
If you installed FX pwsh package it is dotnet shared application. It requires dotnet to be installed in order to run it. How searching of installed dotnet is performed are described in https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md

----

Since sudo resolve the issue on Mariner and you use [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines) to install dotnet I suggest you report the issue to DevOps pipeline team.

**Comment by 237dmitry** [comment]
On official dotnet cite they say that dotnet directory has to be in $PATH.

```
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
```

**Comment by sirkiza** [comment]
@iSazonov 

`UseDotNet@2` is used externally to install additional SDKs, so it has nothing to do with issue.

Powershell doesn't seem to be self-contained though... It use dotnet runtime which is installed **alongside** with pwsh package. I mentioned above that I used package manager to install powershell: `tdnf install powershell`. Essentially it is installing dotnet-runtime7.0 as a part of installation process. 

Indeed, because PowerShell is not self-contained (on Linux) I am facing issues :)

**Comment by sirkiza** [comment]
@237dmitry `dotnet` is inside the path.
Otherwise `dotnet` command will not be resolved from terminal...
Moreover `dotnet` command doesn't care about `DOTNET_ROOT`.

What is interesting that powershell don't care about `dotnet` from the PATH. It looks into dotnet location stored inside `/etc/dotnet/install_location` or inside `DOTNET_ROOT` or inside `/usr/share/dotnet` (under normal circumstances)

**Comment by 237dmitry** [comment]
> Otherwise dotnet command will not be resolved from terminal...

I don't know what is the directory hierarchy in _your_ dotnet installation. If you have questions like this, then you are doing something wrong. And, executable files can be launched via a symlink... For example, as it is in powershell, which itself temporarily adds $PSHome to $env:PATH for the current session. To run the pwsh executable, you need to link it to a directory in $PATH or add $PSHome to it. Depending on the installation, the environment may differ.

**Comment by sirkiza** [comment]
Agree. Issue seems to be in the logic that determines where to search for dotnet runtime.

Thank you, @rhubarb-geek-nz as together with him we found out that difference between Mariner and Ubuntu is permissions model which in Mariner case does not allow reading from `/etc/dotnet/install_location` as non-root user.

@iSazonov, fix me if I am wrong but PowerShell core is run using "App-contained hosts" and need to know how to find install locations to locate shared frameworks.

@iSazonov, do you know in which repository I can raise an issue on the algorithm which determines where to search for dotnet runtime?

**Comment by iSazonov** [comment]
> @iSazonov, fix me if I am wrong but PowerShell core is run using "App-contained hosts" and need to know how to find install locations to locate shared frameworks.

It is true for all .Net apps https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md

> @iSazonov, do you know in which repository I can raise an issue on the algorithm which determines where to search for dotnet runtime?

Since you found `sudo` resolves the issue this says that dotnet installer has a bug. So I suggest you to report the issue DevOps team which can investigate and fix the issue or report to .Net installer team. You could start with https://learn.microsoft.com/en-us/azure/devops/user-guide/provide-feedback?view=azure-devops

**Comment by sirkiza** [comment]
Sorry, I am not catching, how is it connected with Azure DevOps?

**Comment by iSazonov** [comment]
Where do you use Mariner?

**Comment by sirkiza** [comment]
On Virtual Machine or WSL

**Comment by iSazonov** [comment]
I guess Azure team is owner. Nevertheless there is https://github.com/microsoft/CBL-Mariner

**Comment by sirkiza** [comment]
Does Azure team own dotnet runtime? :)
Cause issue clearly with **algorithm of finding runtime**. 
Not connected with installation... 

Nevertheless thank you for help
