### ISSUE TITLE
Make updating the Linux snap part of the release process

### ISSUE THREAD

**Issue by juvtib** [PowerShell/PowerShell#19247]
Thank you for updating the SnapCraft website on March 14. 

However, this does not resolve the issue. 

It is clear from the past few release cycles that either: 

1. Updating the snap is not a part of the normal release process. -or- 
1. Issues with updating the snap are not communicated clearly. 

I would appreciate an official response. 

Thanks,

---

*Original Issue*

The Linux snap has not been updated to 7.3.3. This is a common problem with the release process. 

https://snapcraft.io/powershell

**Comment by StevenBucher98** [comment]
Publishing to the snap store is part of our formal release process, we ran into an error with 7.3.3 that causes it to be delayed. 

Thanks, closing as resolved.
