### ISSUE TITLE
There's no completion for quoted namespaces

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#19254]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Type in `using namespace "sys<Tab>`

### Expected behavior

```console
Tab completion to: `using namespace "system"`
```

### Actual behavior

```console
Nothing.
```

### Environment data

```powershell
PS C:\Users\Martin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I wonder if we support this.

**Comment by MartinGC94** [comment]
> I wonder if we support this.

The type resolution supports it just fine, but tab completion struggles a bit. `using namespace "System.Collections.Generic";[List<Tab>]` results in: `using namespace "System.Collections.Generic";[st]` but I have PR that fixes that specific issue.

**Comment by theJasonHelmick** [comment]
Thanks @MartinGC94 -- We would enjoy reading that PR.
