### ISSUE TITLE
copy-item -tosession not working in powershell 7

### ISSUE THREAD

**Issue by jszabo98** [PowerShell/PowerShell#19253]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I don't see "copy-item -tosession (new-pssession comp001)" working in any powershell 7 (lts/stable/preview).

### Expected behavior

```console
# works in 5.1

copy-item hi.ps1 c:\users\me\documents -tosession (new-pssession comp001)
icm comp001 { dir }



    Directory: C:\Users\me\Documents


Mode                LastWriteTime         Length Name                                PSComputerName
----                -------------         ------ ----                                --------------
d-----         3/1/2023   8:30 AM                WindowsPowerShell                   comp001
-a----       10/11/2022  10:33 AM            135 winactivetest.ps1                   comp001
```

### Actual behavior

```console
copy-item hi.ps1 c:\users\me\documents -tosession (new-pssession comp001)
icm comp001 { dir }

# no output, no errors
# EDIT: I didn't include the empty columns:

    Directory: C:\Users\me\Documents

Mode                LastWriteTime         Length Name                                PSComputerName
----                -------------         ------ ----                                --------------
                                                                                     comp001
                                                                                     comp001

```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
I'm not sure if the problem is local or remote.

1 change remote pc or use new install vm.
2 change local powershell code by my open source powershell project :
c:\ProgramData\kasini3000\k_copyto_ip_port_w2w_user_pwd.ps1

It seems that Credential is not entered correctly,need more info.

----

main site: https://gitee.com/chuanjiao10/kasini3000
site mirror: https://github.com/kasini3000/kasini3000 --- Welcome give star to project

win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline)
Open source, free, cross-platform

English manual:
https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

tech：
https://www.cnblogs.com/piapia/p/16534765.html

**Comment by dwtaber** [comment]
Testing with both 7.3.3 and 7.4.0-preview.1, I'm unable to reproduce the issue.

**Comment by jszabo98** [comment]
Here's $psversiontable on the destination (windows 5.1).  Both sides are on active directory.

```powershell
Name                           Value
----                           -----
PSEdition                      Desktop
WSManStackVersion              3.0
BuildVersion                   10.0.19041.2364
PSRemotingProtocolVersion      2.3
CLRVersion                     4.0.30319.42000
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSVersion                      5.1.19041.2364
```

**Comment by dwtaber** [comment]
My first attempt wasn't on domain-joined machines, so I've tried again on a pair of domain computers, and I still can't reproduce the issue.  Have you tried a different computer on either end of the connection?

**Comment by jszabo98** [comment]
I think I see my confusion.  Get-childitem over invoke-command displays column heading with nothing underneath.  So the copy works, but I just can't see it.

```powershell
# elevated prompt
 icm localhost { get-childitem } | ft -a

    Directory: C:\Users\ccfadmin\Documents

Mode LastWriteTime Length Name PSComputerName
---- ------------- ------ ---- --------------
                               localhost
                               localhost
                               localhost
```

**Comment by kasini3000** [comment]
```
icm localhost { get-childitem } | ft -a

    Directory: C:\Users\admin\Documents

Mode LastWriteTime Length Name PSComputerName
---- ------------- ------ ---- --------------
                               localhost
```

This is normal because psv5 and psv7 serialization are incompatible.
If it is not necessary to return the object from the node computer to the master computer, you can do this:
```
get-childitem |out-string
```
---

I am more concerned about copy-item. How is it now?

**Comment by jszabo98** [comment]
The copy-item actually works.  The output of get-childitem is just confusing.
