### ISSUE TITLE
Unable to find type [Microsoft.PowerShell.Commands.WebRequestSession]

### ISSUE THREAD

**Issue by CarloToso** [PowerShell/PowerShell#19250]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```ps1
[Microsoft.PowerShell.Commands.WebRequestSession]::New()
#InvalidOperation: Unable to find type [Microsoft.PowerShell.Commands.WebRequestSession].
new-object Microsoft.PowerShell.Commands.WebRequestSession
<#Headers                : {}
Cookies                : System.Net.CookieContainer
UseDefaultCredentials  : False
Credentials            :
Certificates           :
UserAgent              : Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; it-IT) PowerShell/7.3.3
Proxy                  :
MaximumRedirection     : -1
MaximumRetryCount      : 0
RetryIntervalInSeconds : 0
#>
```

### Expected behavior

```console
They should both work
```

### Actual behavior

```console
`[Microsoft.PowerShell.Commands.WebRequestSession]::New()` doesn't work (it worked in PS 5)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Windows Store version

**Comment by 237dmitry** [comment]
In my environment all woks as expected.

**Comment by iSazonov** [comment]
This works for me too.

**Comment by CarloToso** [comment]
I found out it works if I input the two commands in reverse order
```ps1
new-object Microsoft.PowerShell.Commands.WebRequestSession
<#Headers                : {}
Cookies                : System.Net.CookieContainer
UseDefaultCredentials  : False
Credentials            :
Certificates           :
UserAgent              : Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; it-IT) PowerShell/7.3.3
Proxy                  :
MaximumRedirection     : -1
MaximumRetryCount      : 0
RetryIntervalInSeconds : 0
#>
[Microsoft.PowerShell.Commands.WebRequestSession]::New()
<#Headers                : {}
Cookies                : System.Net.CookieContainer
UseDefaultCredentials  : False
Credentials            :
Certificates           :
UserAgent              : Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; it-IT) PowerShell/7.3.3
Proxy                  :
MaximumRedirection     : -1
MaximumRetryCount      : 0
RetryIntervalInSeconds : 0
#>
```

**Comment by iSazonov** [comment]
I guess you should import Utility module before.

**Comment by CarloToso** [comment]
it works correctly when using `Import-Module Microsoft.PowerShell.Utility`. I didn't have this problem in PS 5 what could be the origin of the issue?

**Comment by iSazonov** [comment]
It seems Windows PowerShell loads Utility module from start.

**Comment by CarloToso** [comment]
Should we do something about this? Or should I just close the issue?

**Comment by iSazonov** [comment]
> Should we do something about this? Or should I just close the issue?

Let's wait MSFT team conclusion.
/cc @daxian-dbw @SeeminglyScience

**Comment by daxian-dbw** [comment]
It's the same behavior on Windows PowerShell 5.1, as long as the `Utility` module is not loaded:

![image](https://user-images.githubusercontent.com/127450/222231450-4214e866-61f8-4e4f-aed9-5b1b395b6cf8.png)

So, I'm inclined to treat this issue as by design.

**Comment by CarloToso** [comment]
Thanks (I must have changed somethin in my PS 5), I'll close
