### ISSUE TITLE
Old bug back on Macos: "violates the constraint of type 'T'"

### ISSUE THREAD

**Issue by alan-converge** [PowerShell/PowerShell#19273]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On Get-AzVm, getting "violates the constraint of type 'T'".  Returned to 7.2.9 and problem no longer occurs.

Code: 

# Set Context
$azContext = Set-AzContext -Subscription $Subscription
$subscriptionId = $azContext.Subscription.Id

# Get Bearer token for REST API from the current authenticated session
$azProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
$profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient($azProfile)

$token = $profileClient.AcquireAccessToken($azContext.Tenant.TenantId)
$tokenBearer = ('Bearer {0}' -f ($token.AccessToken))

# Get the VM
$vmTarget = Get-AzVm -Name $Name -ResourceGroup $ResourceGroupName

### Expected behavior

```console
Return VMTarget.
```

### Actual behavior

```console
Exception.
```

### Error details

```console
GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
```

### Environment data

```powershell
7.3.3
```

**Comment by daxian-dbw** [comment]
@alan-converge Are you using the latest version of Az modules?
- If not, please try the latest version, which should have it fixed.
- If so, please report the issue to the [Azure PowerShell repository](https://github.com/Azure/azure-powershell).
