### ISSUE TITLE
Format schema GroupBy does not recognize Label property

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#19275]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am using XML schema validation for the format file and noticed a bug where in a `GroupBy` tag the `Label` tag isn't being recognized as a valid property even though it is.

Here is the VS Code settings pointing to the schema file.
```json
  "xml.fileAssociations": [
        {
          "systemId": "https://raw.githubusercontent.com/PowerShell/PowerShell/master/src/Schemas/Format.xsd",
          "pattern": "**/*.Format.ps1xml"
        },
        {
          "systemId": "https://raw.githubusercontent.com/PowerShell/PowerShell/master/src/Schemas/Types.xsd",
          "pattern": "**/*.Types.ps1xml"
        },
        {
          "systemId": "https://raw.githubusercontent.com/PowerShell/PowerShell/master/src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xsd",
          "pattern": "**/*.cdxml"
        }
    ],
```

![image](https://user-images.githubusercontent.com/38873752/222777876-279dca29-a0a6-4bf6-8d8f-d2e884b936e6.png)

### Expected behavior

```console
Label is listed as a valid property.
```

### Actual behavior

```console
Label is not listed as a valid property.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
>  the Label tag isn't being recognized as a valid property even though it is.

In `GroupBy` is `PropertyName`

```
      <GroupBy>
        <PropertyName> ... </PropertyName>
      </GroupBy>
```
`Label` is a property of view definitions (table, list)

```
    <TableControl>
       <TableHeaders>
       ...
          <TableColumnHeader>
            <Label> ... </Label>
          </TableColumnHeader>
       ...
        </TableHeaders>
    </TableControl>
```

**Comment by ThomasNieto** [comment]
@237dmitry `Label` is a valid tag in `GroupBy` as it is the value to display the GroupBy headers. You can have it group by a property name or script block, either of those can have an optional label. For example `Directory` is the label:

```powershell
    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           12/7/2019  3:14 AM                PerfLogs
d-r--           11/4/2022  8:16 PM                Program Files
d-r--            2/8/2023 12:19 PM                Program Files (x86)
d----           2/13/2023  2:40 PM                Temp
d----           2/25/2023  8:46 AM                Test
d-r--            2/4/2022 11:42 PM                Users
d----           2/21/2023 12:25 PM                Windows
```

See the [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-7.3):

> The <GroupBy> tag contains a <PropertyName> tag that specifies the object property by which items are to be grouped. It also contains either a <Label> tag that specifies a string to be used as a label for each group or a <CustomControlName> tag that references a custom control defined elsewhere using a <Control> tag. The <Control> tag contains a <Name> tag and a <CustomControl> tag.

**Comment by 237dmitry** [comment]
> Label is a valid tag in GroupBy

Yes. I am wrong. But I tried `Label` and got no errors:

```xml
      <GroupBy>
        <PropertyName>PSParentPath</PropertyName>
        <Label>Directory</Label>
<!--        <CustomControlName>FileSystemTypes-GroupingFormat</CustomControlName> -->
      </GroupBy>
```
Directory + PSParentPath:

```
Directory: Microsoft.PowerShell.Core\FileSystem::C:\
```

**Comment by ThomasNieto** [comment]
Found the issue the schema is specifically looking for `<PropertyName>` or `<ScriptBlock>` tags to be defined first before `<Label>` tag. Changing the order caused the error to disappear. Not sure why the schema is requiring a specific order to be in place since PowerShell doesn't enforce it.
