### ISSUE TITLE
Do not remove files/directories beginning with a FULL STOP (period, dot) without -Force

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#19282]
### Summary of the new feature / enhancement

As a user, I want PowerShell to ignore files and directory names beginning with a FULL STOP (period, dot) character during remove actions with a wildcard specification. This would be the same as cmd.exe and bash.

PowerShell already requires the -Force switch on Get-ChildItem to include item names beginning with a FULL STOP.

Here are example scripts showing that cmd.exe does -not- delete the ".allmine" directory, but pwsh.exe does.

```
CD /D "C:\src"
MKDIR "dt-cmd"
CD "dt-cmd"
ECHO>"t.txt" now
MKDIR ".allmine"
DIR
DEL /Q "..\dt-cmd\*"
DIR
```
Sample execution of cmd script.

```
C:\src>CD /D "C:\src"
C:\src>MKDIR "dt-cmd"
C:\src>CD "dt-cmd"
C:\src\dt-cmd>ECHO>"t.txt" now
C:\src\dt-cmd>MKDIR ".allmine"
C:\src\dt-cmd>DIR
 Volume in drive C has no label.
 Volume Serial Number is 62B0-F7C3

 Directory of C:\src\dt-cmd

2023-03-05  21:07    <DIR>          .
2023-03-05  21:07    <DIR>          ..
2023-03-05  21:07    <DIR>          .allmine
2023-03-05  21:07                 5 t.txt
               1 File(s)              5 bytes
               3 Dir(s)  305,616,617,472 bytes free

C:\src\dt-cmd>DEL /Q "..\dt-cmd\*"
C:\src\dt-cmd>DIR
 Volume in drive C has no label.
 Volume Serial Number is 62B0-F7C3

 Directory of C:\src\dt-cmd

2023-03-05  21:07    <DIR>          .
2023-03-05  21:07    <DIR>          ..
2023-03-05  21:07    <DIR>          .allmine
               0 File(s)              0 bytes
               3 Dir(s)  305,616,613,376 bytes free
```

PowerShell script.

```
Set-Location -Path C:/src
New-Item -ItemType Directory -Name dt-pwsh | Out-Null
Set-Location -Path dt-pwsh
Set-Content -Path ./t.txt -Value 'now'
New-Item -ItemType Directory -name .allmine | Out-Null
Get-ChildItem
# Remove-Item -Recurse -Force -Path ../dt-pwsh/*
Remove-Item -Recurse -Path ../dt-pwsh/*
"The $(Get-Location) directory contains $((Get-ChildItem -Recurse -Force).Length) items"
```
PowerShell script example execution.

```
PS C:\src> Set-Location -Path C:/src
>> New-Item -ItemType Directory -Name dt-pwsh | Out-Null
>> Set-Location -Path dt-pwsh
>> Set-Content -Path ./t.txt -Value 'now'
>> New-Item -ItemType Directory -name .allmine | Out-Null
>> Get-ChildItem
>> # Remove-Item -Recurse -Force -Path ../dt-pwsh/*
>> Remove-Item -Recurse -Path ../dt-pwsh/*
>> "The $(Get-Location) directory contains $((Get-ChildItem -Recurse -Force).Length) items"
>>

    Directory: C:\src\dt-pwsh

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2023-03-06    06:34                .allmine
-a---          2023-03-06    06:34              5 t.txt
The C:\src\dt-pwsh directory contains 0 items
```

**Comment by 237dmitry** [comment]
Hidden files have to be deleted with `-Force` switch. Probably on Windows such files should not be considered hidden.
```poweshell
 $ dir -ah -file 

    Directory: ~

UnixMode     Num   UID   GID      LastWriteTime    Size Name
--------     ---   ---   ---      -------------    ---- ----
-rw-------   600  1000  1000   06.03.2023 01:07      3K .bash_history
-rw-r--r--   644  1000  1000   02.02.2023 09:38      21 .bash_logout
-rw-r--r--   644  1000  1000   02.02.2023 09:38      57 .bash_profile
-rw-r--r--   644  1000  1000   27.01.2023 14:09     540 .bashrc
-rw-r--r--   644  1000  1000   06.03.2023 00:12      23 .dmrc
-rw-r--r--   644  1000  1000   05.03.2023 18:24     576 .gtkrc-2.0
-rw-------   600  1000  1000   22.02.2023 11:51       0 .ICEauthority
-rw-------   600  1000  1000   05.03.2023 23:11      20 .lesshst
-rw-r--r--   644  1000  1000   26.02.2023 14:42     690 .profile
-rw-r--r--   644  1000  1000   02.02.2022 18:00    3,6K .screenrc
-rw-------   600  1000  1000   06.03.2023 07:41      50 .Xauthority
-rw-r--r--   644  1000  1000   18.01.2023 14:13     214 .xinitrc
-rw-r--r--   644  1000  1000   22.02.2023 13:05     232 .xprofile
-rw-r--r--   644  1000  1000   05.03.2023 18:24      36 .Xresources
-rw-r--r--   644  1000  1000   18.01.2023 14:13      63 .xsession
```

```console
-Force <System.Management.Automation.SwitchParameter>
    Allows the cmdlet to get items that otherwise can't be accessed by the user, such as hidden or system files.
```

**Comment by Liturgist** [comment]
> Hidden files have to be deleted with `-Force` switch. Probably on Windows such files should not be considered hidden.

I have revised the pwsh example. After the `Remove-Item -Recurse -Path ../dt-pwsh/*` statement, the `.allmine` directory has been deleted. This would not happen in cmd.exe or bash.

**Comment by jhoneill** [comment]
Del in your cmd example won't delete any directories, it's not the . which is doing it.  It will delete a file beginning with . like any other file.  
IIRC unix had the convention of hiding file names beginning with . back in about 1985 when I first used it; but the FAT file system used in DOS had Hidden, and System (sort of super hidden and read only) file attributes by 3.1 and probably earlier, and that inherited into Windows NT and NTFS. 
If you want . files/directories not to be deleted on windows the safest thing to do is to set the file attribute on them.

To change the behaviour of `Remove-Item` for all users would be a bad idea - there is an unknowable number of scripts which depend on the present behaviour without knowing it. 

But you can  set the exclude parameter for remove-item to default to "*" 
https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_parameters_default_values?view=powershell-7.3 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/16209593/223118520-9814401a-4b99-4e76-848f-d8d158250a98.png">

Specify a different exclusion (including an empty one) DOES delete as seen in the screen shot.
just add `  $PSDefaultParameterValues["Remove-Item:Exclude"] = ".*" ` to your profile.

**Comment by 237dmitry** [comment]
> This would not happen in cmd.exe or bash.

I did not have the opportunity to check the behavior of cmd.exe, but I got to Windows. `cmd.exe` shows and deletes dot-files:

![Screenshot 2023-03-06 172117](https://user-images.githubusercontent.com/78153320/223136870-cd0f1886-c3ec-4c5f-8ef3-52e6966713cb.png)

**Comment by SteveL-MSFT** [comment]
I also don't see `cmd` treating a file starting with a period differently than any other character which is what I expected as it doesn't have special meaning on Windows.  Also, Windows PowerShell doesn't treat filenames with a period in front any differently, so any change here on Windows would be a breaking change.

**Comment by iSazonov** [comment]
.Net consider such files as _hidden_. I wonder if pwsh don't follow this.

**Comment by jhoneill** [comment]
> .Net consider such files as _hidden_. I wonder if pwsh don't follow this.

**It follows the OS conventions**  On Windows `.` has no special meaning at the start of a file name, and it's been this way back to MS-DOS and the FAT-12 file system - I started with DOS 3.1,  which had the hidden/system/archive attributes I don't know if they were in DOS 1 or came with directories in DOS 2. 
```
PS>  dir .. > .dont_delete_me

PS>  [system.IO.File]::GetAttributes("$Pwd\.dont_delete_me")
Archive
```

But on WSL `.` hides the file.  
```
#513 PS7 ~> dir .p*
#514 PS7 ~> dir .p* -Force

    Directory: /home/mcp

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rw-r--r-- mcp              mcp                03/07/2022 21:04            807 .profile
-rw------- mcp              mcp                05/11/2022 13:49              7 .python_history

#515 PS7 ~>  [system.IO.File]::GetAttributes("$Pwd/.profile")
Hidden

#516 PS7 ~> dir > .am_I_hidden
#517 PS7 ~>  [system.IO.File]::GetAttributes("$Pwd/.am_I_hidden")
Hidden
```

I think the OP also has a misunderstanding about the behaviour of DEL in cmd (which replicates what command.com did in MS-DOS) 
```
[cmd] C:\Users\mcp\AppData\Local\Temp> dir /b demo
.file

[cmd] C:\Users\mcp\AppData\Local\Temp> del demo /q

[cmd] C:\Users\mcp\AppData\Local\Temp> dir demo
 Volume in drive C has no label.
 Volume Serial Number is 1465-B795

 Directory of C:\Users\mcp\AppData\Local\Temp\demo

07/03/2023  11:25    <DIR>          .
07/03/2023  11:23    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  1,092,391,333,888 bytes free
```

`Del` does not delete directories, only files.   And **does delete files** which start with `.`

 Granted this divergence between Unix and Microsoft OSes can annoying but it pre-dates Windows (and Linux) so we're probably stuck with it.

**Comment by rhubarb-geek-nz** [comment]
Referring to existing behaviour, Visual Studio creates a ".vs" directory and on Windows it also has the hidden attribute.

**Comment by SteveL-MSFT** [comment]
The `hidden` attribute is respected by PowerShell, but a `.` prefix on Windows doesn't mean anything unlike on Unix systems

**Comment by Liturgist** [comment]
The difficulty appeared in working through the "Learn Git the Hard Way" book. https://leanpub.com/learngitthehardway

I am working through the book, written for bash scripting, on a PowerShell console. The UNIX `rm -rf` command does not remove '.' file names. The PowerShell `Remove-Item -Recurse -Force` command does.

The exercise to recover a local copy when "all" files had been deleted failed on PowerShell when `-Force` was used. Using `-Force remove the "hidden" .git directory when left recover with nothing to recover from. One more, sometime consequential, piece of trivia to remember about the difference between UNIX `rm` and PowerShell `Remove-Item` (del, erase, rd, ri, rm, rmdir).

**Comment by Liturgist** [comment]
The difficulty appeared in working through the "Learn Git the Hard Way" book. https://leanpub.com/learngitthehardway

I am working through the book, written for bash scripting, on a PowerShell console. The UNIX rm -rf command does not remove '.' "hidden" file names. The PowerShell Remove-Item -Recurse -Force command does.

The exercise to recover a local copy when "all" files had been deleted failed on PowerShell when -Force was used. Using -Force remove the "hidden" .git directory when left recover with nothing to recover from. One more, sometime consequential, piece of trivia to remember about the difference between UNIX rm and PowerShell Remove-Item (del, erase, rd, ri, rm, rmdir).
