### ISSUE TITLE
Invoke-WebRequest / Invoke-RestMethod fail with an [xml] -Body argument if the document has an XML declaration but no "encoding" attribute.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19280]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Said cmdlets try to glean the desired encoding from the `encoding` attribute of an `[xml]` instance's XML declaration.

However, it is possible to have an XML declaration _without_ such an attribute, which unexpectedly causes an error, because the code seemingly makes the assumption that this attribute is _always_ there:

```powershell
# Note: If you remove the XML declaration or add a valid "encoding" attribute, the problem goes away.
Invoke-RestMethod https://postman-echo.com/post -Method POST -ContentType text/xml -Body ([xml] '<?xml version="1.0"?><foo/>')
```

### Expected behavior

The call should succeed and output a `[pscustomobject]` instance.

### Actual behavior

The call fails with the following error:

```console
Invoke-RestMethod: '' is not a supported encoding name. [...]
```

### Environment data

```powershell
PowerShell Core 7.4.0-preview.1
```

**Comment by CarloToso** [comment]
Confirmed in PS 5 and 7.3.3

**Comment by CarloToso** [comment]
Fixed the problem in local, PR later
