### ISSUE TITLE
Providing a value for Options in the VariableDefinitions parameter of New-PSRoleCapabilityFile results in an error

### ISSUE THREAD

**Issue by jessegri** [PowerShell/PowerShell#19293]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`$PathToFile = <A valid path you provide>; New-PSRoleCapabilityFile -VariableDefinitions @{Name = "FakeName"; Value = "FakeValue"; Options="AllScopes"}  -path $PathToFile`

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-psrolecapabilityfile?view=powershell-7.3#-variabledefinitions 
Any valid value for the Options listed in the link above will result in the same error.  If the Options key is present in the hashtable this error is generated. 

### Expected behavior

```console
No error, and a file with the VaribleDefintions Options properly defined.
```

### Actual behavior

```console
New-PsRoleCapabilityFile: The key 'Options' in the member 'VaribleDefinitions' is not valid. Change the key in the file...
```

### Error details

```console
New-PsRoleCapabilityFile: The key 'Options' in the member 'VaribleDefinitions' is not valid. Change the key in the file...
```

### Environment data

```powershell
Reproduced on:
Name                           Value

----                           -----

PSVersion                      7.2.10

PSEdition                      Core

GitCommitId                    7.2.10

OS                             Microsoft Windows 10.0.20348

Platform                       Win32NT

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1

WSManStackVersion              3.0

 

And

 

Name                           Value

----                           -----

PSVersion                      5.1.20348.1366

PSEdition                      Desktop

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

BuildVersion                   10.0.20348.1366

CLRVersion                     4.0.30319.42000

WSManStackVersion              3.0

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
Looking at the code, this appears to be a doc issue: https://github.com/PowerShell/PowerShell/blob/4c586a7a86515869a4732532b5c8c29c9e58fa70/src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs#L1040-L1049 in that `Options` is only supported for Functions and not Variables.  cc @PaulHigin 

Created https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9927
