### ISSUE TITLE
Passing the value of a type-constrained assignment through via the grouping operator ((...)) passes the input value rather than the converted one, if the variable was created separately

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19292]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a variation of #17165, which _has_ been fixed (in https://github.com/PowerShell/PowerShell/pull/17174),

```powershell
# OK: -> 'Boolean'
# Variable creation is part of the expression.
([bool] $a = 42).GetType().Name

# !! BROKEN: -> 'Int32'
# Type-constrained variable was created beforehand.
[bool] $b = $false
($b = 42).GetType().Name
```

Note:

* As @237dmitry has discovered, the problem only occurs when a script, script block, or function is _dot-sourced_ or _directly at the interactive prompt_. Normal invocation of a script / script block / function work as expected.

* As @jhoneill points out, the problem equally applies to _multi-assignments_ (`[bool] $b = $false; $result = $b = 42; $result.GetType().Name`)

### Expected behavior

```console
Boolean
Boolean
```

### Actual behavior

```console
Boolean
Int32
```

### Environment data

```powershell
PowerShell Core 7.4.0-preview.1
```

**Comment by 237dmitry** [comment]
In script-blocks this works as expected.

**Comment by mklement0** [comment]
Good point, @237dmitry, though it isn't about script blocks (and therefore also functions and scripts) per se, but whether they are _dot-sourced_:

```powershell
# OK
& { [bool] $b = $false; ($b = 42).GetType().Name }

# !! BROKEN
. { [bool] $b = $false; ($b = 42).GetType().Name }
```

I've updated the initial post accordingly.

**Comment by mklement0** [comment]
Yes, more generally it is about using an assignment _as an expression_, which not only applies to `(...)`, but also to _multi-assignments_.

Aside from that, the above distinction with respect to dot-sourcing applies equally.

**Comment by jhoneill** [comment]
yes. 
`& { [bool] $b = $false; $x = $b = 42; $x ;$b }`  and `. { [bool] $b = $false; $x = $b = 42; $x ;$b }` give different things.   

Although it is implicit in the title it depends on the constraint being specified separately     
`. { [bool] $b = $false; $x = [bool]$b = 42; $x ;$b }` gives the same behaviour as running the block with `&`
