### ISSUE TITLE
Question: `Group-Object` group order

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#19307]
### Summary of the new feature / enhancement

[`Group-Object`](https://learn.microsoft.com/powershell/module/microsoft.powershell.utility/group-object) might be used to update and object list with an other list (See e.g. Stackoverflow: [Compare CSV file with extra Column data](https://stackoverflow.com/questions/75692796/compare-csv-file-with-extra-column-data)):

```PowerShell
$csv1 = ConvertFrom-Csv @'
Alert_ID, Server, Type, Timestamp,  Severity
    1234, Srv1,   WIN,  2023-03-10, Critical
    1235, Srv1,   Net,  2023-03-9,  Critical
    1236, Srv2,   WIN,  2023-03-8,  Critical
    1237, Srv3,   WIN,  2023-03-10, Critical
'@

$csv2 = ConvertFrom-Csv @'
Alert_ID, Server, Type, Timestamp,  Severity, Ticket
    1234, Srv1,   WIN,  2023-03-10, Critical, INC1
    1236, Srv2,   WIN,  2023-03-8,  Critical, INC3
'@

$csv2 + $csv1 |Group-Object -Property Alert_ID |Foreach-Object { $_.Group[0] } |Format-Table

Alert_ID Server Type Timestamp  Severity Ticket
-------- ------ ---- ---------  -------- ------
1234     Srv1   WIN  2023-03-10 Critical INC1
1235     Srv1   Net  2023-03-9  Critical
1236     Srv2   WIN  2023-03-8  Critical INC3
1237     Srv3   WIN  2023-03-10 Critical
```

But this highly depends on the order of the grouped objects

**Questions:**
* (Not using any additional switches as -AsHashTable`) Is it safe to presume that the order of the grouped object list is the same as the order of the input list?
* Is this part of the integration tests (or can it be integration tested, so that it is guarantied in the future)?

This feature (if existing at all) is not documented (or I missed it).
If it is safe to rely on the order, I will do a documentation update request

**Comment by jhoneill** [comment]
I think there will be scripts that assume it (I'm sure I have cases where I want the group sorted so I do    
```get-stuff | sort-object -property foo | group-object -property bar```
 re-ordering groups would be extra work, any default ordering would be wrong a lot of the time, and breaking scripts which rely on the behaviour wouldn't be acceptable, but that is as near as you'll get to a guarantee. 

So I think it is reasonably safe to rely on it, and the docs can describe it.

**Comment by mklement0** [comment]
It's actually the (ascending) _sort order_ of the input objects / grouping properties that determines the order of output groups, not the _input_ order (in the code in the initial post the input objects happen to be sorted already), as the following examples demonstrate

```powershell
 10..1 + 1..10 | Group-Object 

Get-ChildItem -File  | Group-Object Length
```

But, yes, it's fair to assume that existing script rely on this behavior, and it definitely should be documented.

**Comment by iRon7** [comment]
@mklement0 ,

> It's actually the (ascending) `sort order`

Sorry, apparently there are 2 sort orders in play and I wasn't clear on that.
(I actually meant the inner grouped sort order.

```PowerShell
$x = ConvertFrom-Csv @'
@,#
b,4
a,3
b,2
a,1
'@
```

As you defined , the outer sort order appears to be ascending:
```
"$(($x |Group-Object '@').Name)" |Should -be 'a b'
```
But about the inner group order{s}:
```PowerShell
"$(($x |Group-Object '@')[0].Group.'#')" |Should -be '3 1'
```
Will they stay in order?
In other words, In the code in the initial post, I take the first occurrence in the grouped list (`$_.Group[0]`).
Can I safely presume that this is an object from the `$csv2` list if the concerned property (`Alert_ID`) exists in both (`$csv1` and `$csv2`) lists?

**Comment by mklement0** [comment]
Thanks, good to know - I misunderstood the question.

**Comment by iRon7** [comment]
Related document: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/9892
