### ISSUE TITLE
Convert SecureString to plain text: System.Runtime.InteropServices.Marshal only returns the first character of SecureString  

### ISSUE THREAD

**Issue by kneufeld-pbp** [PowerShell/PowerShell#19317]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When converting SecureString to plain text, we only get back the first character of the string when using `[System.Runtime.InteropServices.Marshal]`  workaround is to create a PSCredential Object `(New-Object PSCredential 0, $SecurePassword).GetNetworkCredential().Password`

### Expected behavior

```console
$SecurePassword = ConvertTo-SecureString "helloworld" -AsPlainText -Force
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword)
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

helloworld
```

### Actual behavior

```console
$SecurePassword = ConvertTo-SecureString "helloworld" -AsPlainText -Force
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword)
[System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)

h
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
You must use `[System.Runtime.InteropServices.Marshal]::PtrToStringBSTR` rather than `PtrToStringAuto`. I know a lot of examples use auto in the second method call, but it's incorrect. It only happens to work on Windows because `Auto` does it based on a platform specific default

**Comment by kneufeld-pbp** [comment]
Yes, that was the issue. closing this issue 

Thanks
