### ISSUE TITLE
Not able to process file with [ in the file name, ie Remove-Item or Rename-Item 

### ISSUE THREAD

**Issue by tdn4it** [PowerShell/PowerShell#19323]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

(a) Create a test folder, ie. c:\Test; 
(b) Create files and one or two with a left square bracket in the name [, ie: C:\Test\Test [File 
(c) Create a file list variable, ie `$fileList = Get-ChildItem -path 'C:\Test' -File`
(d) Run test code 
`ForEach ($file in $fileList) {
  Remove-Item $file.fullname
}`
(e) Files **without** the left square bracket are removed. This is tested with version 5.5 and 7.3.3. Same problem with Rename-Item.
Tested with: (a) PowerShell (5.5 and 7.3.3) in Administrative mode, (b) Ran with -STA, (c) Tested in ISE mode. Further testing, PowerShell couldn't "find" the file, even though PS found the [files with Get-ChildItem to create the $fileList.

### Expected behavior

```console
The expected behavior is cmdlet Remove-Item or Rename-Item to behave as expected for all file in the folder. Remove-Item or Rename-Item to be able to find the file in the $fileList created by Get-ChildItem and to complete the command for "ALL" files in the $fileList.

All files in the folder had the "same" attribute - normal.
```

### Actual behavior

```console
Remove-Item/Rename-Item performed the expected action on files without the left square bracket in the filename, but could not find the file with the square bracket in the filename to perform the task.
```

### Error details

```console
Message in PowerShell 7.3.3 and PowerShell 5.1
Remove-Item: Cannot retrieve the dynamic parameters for the cmdlet. The specified wildcard character pattern is not valid: Instructions on Accessing CyberDefense Clinic[35.pdf

Important to Note: When the cmdlet is run as a standalone, Remove-Item $file.Fullname, where $file.fullname has the full path and filename, NO error was returned and the file was NOT removed (or rename as in the case of rename
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Four image files are uploaded - Left Window [PowerShell] - Right Window [File Explorer Folder]:
(a - Before) [ PS-Empty ] [ Explorer: Folder/Files]
(b - After) [PS ran script ] [ Explorer: Files with left square bracket were not removed (others were removed) ]
(c - Standalone) [ PS ran cmdlet ] [ Explorer: no affect on files ]
![Before](https://user-images.githubusercontent.com/50829955/224905425-92bf7842-548f-47f0-9af6-faa269f5ea65.jpg)
![After](https://user-images.githubusercontent.com/50829955/224905456-3c5d8281-7597-4281-877f-5ac249b3dd5e.jpg)
![Standalone](https://user-images.githubusercontent.com/50829955/224905485-ce2d7a58-c86d-4157-8237-e833335165d4.jpg)

**Comment by jborean93** [comment]
You need to use `-LiteralPath‘ for pwsh not to treat the path as one with wildcards. You can also pipe the file object into the cmdlet and it will bind to PSPath which is an alias for `-LiteralPath`.

**Comment by CarloToso** [comment]
Related to https://github.com/PowerShell/PowerShell/issues/12168

**Comment by tdn4it** [comment]
Thanks, figured it out… from the web articles.

**Comment by tdn4it** [comment]
Is there anyway to pull the issue from GitHub, as not to receive anymore reply?
