### ISSUE TITLE
Ubuntu 14.04 packages are installable on Debian/Devuan Jessie as well.

### ISSUE THREAD

**Issue by sdaugherty** [PowerShell/PowerShell#1932]
Might want to update documentation. The Ubuntu 14.04 package will work on Debian (or Devuan) jessie.

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by voltagex** [comment]
Yes, but this isn't recommended (on the Debian side). See https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

There's work both here and in Debian to get powershell available as an official package. I'd hope Devuan doesn't duplicate any work but I have no contact with anyone in that project.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834756

**Comment by sdaugherty** [comment]
@voltagex That specifically refers to *repositories* not individual packages. Repositories not meant for Debian can break a system because they can pull in packages as dependencies that conflict with, or are newer than Debian packages. (and therefore, won't automatically receive security updates.

**Comment by sdaugherty** [comment]
As an aside, despite what Debian may claim, packages in "stable" often *are* too old to be useful, at least if you expect any support from upstream maintainers or communities. Ruby, nodejs, and the like are all practically useless as packaged by Debian because of the glacially slow release cycles in Debian.

**Comment by voltagex** [comment]
I agree with you on stable packages being too old. I'd still like to try to get things done the "right" way.

**Comment by sdaugherty** [comment]
@voltagex There's plenty of software that simply maintains a single current, third party package compatible with both Ubuntu and Debian - this is the approach used by Visual Studio Code and with Google Chrome., so it's nothing really new.

**Comment by andschwa** [comment]
Until we're actually supported Debian (as in, added its RID to our build scripts, run tests on it, and ship a package, regardless of it being the Ubuntu package or not), we're not going to claim support in documentation. Thanks for investigating though!
