### ISSUE TITLE
PowerShell 7.3.3 Hangs on Copy-Item to Remote Server

### ISSUE THREAD

**Issue by h4xhor** [PowerShell/PowerShell#19324]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

# Windows Hyper V Server 2019

On Hyper-V Server 2019, using PowerShell set up PSRemoting:
```
Enable-PSRemoting -Force
```
Set the wildcard for WinRM TrustedHosts:
```
winrm set winrm/config/client '@{TrustedHosts="*"}'
```

Set `MaxEnvelopeSizeKb` to about 100GB and `MaxTimeoutms` to 10 hours:
```
winrm set winrm/config '@{MaxTimeoutms="36000000"}'
winrm set winrm/config '@{MaxEnvelopeSizeKb="100000000"}'
```

Restart WinRM
```
Restart-Service -Force WinRM
```
# CentOS 8

Create a file of 375 kB for testing the file transfer later on.

```
fallocate --length 375k my_375k.txt
```

Install PowerShell 7.3.3 on CentOS 8 Stream.

Start PowerShell
```
sudo pwsh
```
Install `WSMan`
```
Install-Module -Force -Name PSWSMan
Install-WSMan
```

Exit PowerShell.
```
exit
```
Start PowerShell again as normal user:
```
pwsh
```

`Administrator` is the administrator user on the Hyper-V server. Create the `$creds`. Enter the login password:
```
$creds = Get-Credential -UserName Administrator
```

`192.168.0.23` is the IP address of Hyper-V server. Start a session.
```
$Session = New-PSSession -ComputerName 192.168.0.23 -Authentication Negotiate -Credential $creds
```

Try to transfer a 375 kB file using `Copy-Item` using the stored `$Session`
```
Copy-Item "my_375k.txt" -Destination "C:\Users\Administrator\" -ToSession $Session -verbose
```

Copy-Item will hang:
```
VERBOSE: Performing the operation "Copy File" on target "Item: /home/c8-00/test/my_375k.txt Destination: C:/Users/Administrator/".
Copying /home/c8-00/test/my_375k.txt to C:/User… [From localhost to 192.168.0.23            ]
```

# Windows 10

On Windows 10 I can use `Copy-Item` to transfer a 10GB file fine to the Hyper-V server at `192.168.0.23`.

In PowerShell, create a file about 10GB in size.

```
fsutil.exe file createnew my_10g.txt 10000000000
```
```
$creds = Get-Credential -UserName Administrator
$Session = New-PSSession -ComputerName 192.168.0.23 -Authentication Negotiate -Credential $creds
Copy-Item "my_10g.txt" -Destination "C:\Users\Administrator\" -ToSession $Session
```

### Expected behavior

```console
Linux PowerShell Copy-Item should of transferred the file to a remote Hyper-V Server.
```

### Actual behavior

```console
Linux PowerShell Copy-Item hanged when transferring the file to a remote server.
```

### Error details

```console
Copy-Item hanged with

VERBOSE: Performing the operation "Copy File" on target "Item: /home/c8-00/test/my_375k.txt Destination: C:/Users/Administrator/".
Copying /home/c8-00/test/my_375k.txt to C:/User… [From localhost to Hyper-V.virtualbox888.o…]
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 4.18.0-448.el8.x86_64 #1 SMP Wed Jan 18 15:02:46 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
This looks like a problem with the PSWSMan module which isn't part of PowerShell itself. Do you get the same problem if you try to go from Linux to windows using SSH as a remote session transport ?

**Comment by kasini3000** [comment]
mark, I also want to know the answer.
seem:
https://github.com/PowerShell/psl-omi-provider/issues/129
