### ISSUE TITLE
Please, return the old view of floating numbers in pscustomobject's table view!!!

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#19347]
### Summary of the new feature / enhancement

Please return the old non-rounded view. Instead of:
```
 $ [pscustomobject] @{ aaa = 1.001234 }

 aaa
 ---
1.00
```
should be
```
 $ [pscustomobject] @{ aaa = 1.001234 }

     aaa
     ---
1.001234
```

### Proposed technical implementation details (optional)

The implementation is administrative rather than technical.

**Comment by iSazonov** [comment]
Current culture format data is used for output formatting. 
![image](https://user-images.githubusercontent.com/22290914/225695814-087e351c-a452-4c74-ae81-ac24eef2babc.png)

**Comment by 237dmitry** [comment]
This does not solve the problem. I set 9 digits after delimiter:

```
$ [pscustomobject] @{ aaa = 1.001234 }

        aaa
        ---
1,001234000
```
The result is different than expected:

![Screenshot 2023-03-16 204915](https://user-images.githubusercontent.com/78153320/225708705-af8c59d8-3ecb-4702-9348-c267b7e8d2f7.png)

**Comment by dwtaber** [comment]
Is this not just a rehash of #19139, #19107, and #18492?

**Comment by 237dmitry** [comment]
Where is resolution? This issue is for enhancement. They broke everything and they say that it should be so. Users themselves must decide how many digits to leave in the output.

**Comment by iSazonov** [comment]
> Users themselves must decide how many digits to leave in the output.

Users can customize output formatting in PowerShell for many years. 
Current defaults was approved by team and pwsh follows OS defaults like all applications.

**Comment by 237dmitry** [comment]
> Current defaults was approved by team and pwsh follows OS defaults like all applications.

Where I can sea these standards for linux platform? Why I have to convert output to string in order to get desired result. This is out of my understanding.
