### ISSUE TITLE
Update-ScriptFileInfo adds two new lines to script file on each execution

### ISSUE THREAD

**Issue by jasoth** [PowerShell/PowerShell#19349]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following command multiple times. Each time it adds two new lines between PSScriptInfo block and the description block.
```PowerShell
Update-ScriptFileInfo '<ScriptPath>' -Version 1.1
```

Updated Script header:
```PowerShell
<#PSScriptInfo

.VERSION 1.1

...
#> 

### <== 2 new lines are added here every time the command is run

<# 

.DESCRIPTION 
 asdf 

#> 
param ()
```

### Expected behavior

```console
When updating the script info, only the updated values will be updated in the file.
```

### Actual behavior

```console
The script file grows indefinitely with two new lines added with each run.
```

### Error details

```console
No Errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasNieto** [comment]
This command is in the PowerShellGet repository.

**Comment by jasoth** [comment]
> This command is in the PowerShellGet repository.

Good call. I re-created this issue on the PowerShellGet repo.
