### ISSUE TITLE
The system command does not display Chinese correctly

### ISSUE THREAD

**Issue by yuwenlong** [PowerShell/PowerShell#19345]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Enter system commands, for example:
```
ipconfig /all
```

### Expected behavior

```console
Display Chinese correctly, pwsh should follow the system language!
```

### Actual behavior

```console
pwsh does not display Chinese, does not follow the system language!
Version: 7.3.3
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22624
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals
![image](https://user-images.githubusercontent.com/11555324/225615023-a12006bb-f122-4dc2-9acb-bcb9ef80d632.png)
![image](https://user-images.githubusercontent.com/11555324/225615070-759265c2-9a26-4d5c-920b-99567d9e8cbd.png)

**Comment by kasini3000** [comment]
i test again on win11 22h2 vm + ps v7.3.3 ,normal. the build version is 22621. 
10.0.22624 looks like : win11 insider preview ,maybe that's why.

**Comment by yuwenlong** [comment]
Yes, I'm using Win11 Insider Preview, so can the problem be fixed?
@kasini3000

**Comment by yuwenlong** [comment]
![image](https://user-images.githubusercontent.com/11555324/225796222-dd739ad9-4689-4f79-999d-e474144a5dc0.png)
Please look at the second picture, the system comes with no problem!

**Comment by yuwenlong** [comment]
@kasini3000 @daxian-dbw 
Yes, I'm using Win11 Insider Preview, so can the problem be fixed?

**Comment by kasini3000** [comment]
Since it works normally in Powershell v5, I think this might solve the problem:
powershell.exe -c "ipconfig /all" on ps v 7.3.3
If it still doesn't work, you can only use the old release version of Windows 11 , which has fewer issues.

**Comment by daxian-dbw** [comment]
@yuwenlong Can you share the values of `$OutputEncoding`, and `[console]::OutputEncoding` from both the pwsh.exe and powershell.exe sessions?

Also, can you run `Start-Process ipconfig -ArgumentList '/all' -NoNewWindow -Wait` from pwsh.exe and share the results?

**Comment by yuwenlong** [comment]
![image](https://user-images.githubusercontent.com/11555324/226526206-750c9422-6d6e-4d25-b438-37534402a829.png)
![image](https://user-images.githubusercontent.com/11555324/226526222-2d5a3a1d-49b8-4c0c-bedd-f7aad77405fc.png)
@kasini3000 @daxian-dbw Please see the screenshot above.

**Comment by yuwenlong** [comment]
![image](https://user-images.githubusercontent.com/11555324/226526869-86b47b2c-5aca-4a49-8d0a-de1e0fdc6d73.png)
![image](https://user-images.githubusercontent.com/11555324/226526892-83d3f08f-fb20-4b55-a446-c48e867f47f9.png)

**Comment by yuwenlong** [comment]
![image](https://user-images.githubusercontent.com/11555324/226783719-cfc04296-3942-428c-bb67-aa7f9e1ad5a1.png)
![image](https://user-images.githubusercontent.com/11555324/226783738-ae0444f6-35f2-46df-9fb1-0fa3456ce4d9.png)
![image](https://user-images.githubusercontent.com/11555324/226783819-e6d5cd46-47de-4946-b9d2-e93ec0cd1076.png)
@kasini3000 @daxian-dbw

**Comment by kasini3000** [comment]
Looks like your environment is wrong
try :
[console]::OutputEncoding = [System.Text.Encoding]::GetEncoding(936)
ipconfig /all

**Comment by yuwenlong** [comment]
![image](https://user-images.githubusercontent.com/11555324/226856598-3fed3eab-2bb3-443d-ba0a-9dfcf4a8b705.png)
That's fine, but why doesn't the software follow the system language? Do you want the user to set it manually?
@daxian-dbw @kasini3000

**Comment by daxian-dbw** [comment]
PSReadLine [restores the initial `Console.OutputEncoding` when an input is accepted](https://github.com/PowerShell/PSReadLine/blob/84858553682a19c2ae213a4bbe19c69f1e51945b/PSReadLine/ReadLine.cs#L455-L457), so what you observed is not caused by PSReadLine.

I'm not sure why .NET doesn't pick up the system language. Also, not sure if this is a problem in general or only in your particular system environment. I don' have a repro machine for this. @kasini3000 Do you have a machine with the Chinese system language? If so, can you please try and see if you can reproduce the issue?

**Comment by daxian-dbw** [comment]
Thanks @kasini3000 for the help! I have marked this issue with `Resolution - External`.

**Comment by Collins-Leo** [comment]
@yuwenlong 我解决了这个问题，就是将他持久化，而不是仅仅修改当前终端，你需要打开`$PROFILE` 文件，它是`powershell`的配置文件，并将之前的那一句代码给写入`[console]::OutputEncoding = [System.Text.Encoding]::GetEncoding(936) ` 然后保存退出即可。

**Comment by Collins-Leo** [comment]
@yuwenlong I solved this problem, that is, to persist it, instead of just modifying the current terminal, you need to open the `$PROFILE` file, which is the configuration file of PowerShell, execute `notepad $PROFILE` and insert the following line of code  `[console]::OutputEncoding = [System.Text.Encoding]::GetEncoding(936)` and then save and exit.

**Comment by Collins-Leo** [comment]
Interestingly, I didn't join the Win11 Insider Preview., but the issue still arises.
![image](https://github.com/PowerShell/PowerShell/assets/68361024/eaa1bc1c-914e-4ede-9b4d-2830830a1fb5)

**Comment by yuwenlong** [comment]
@Collins-Leo 谢谢，所以还是需要 @daxian-dbw 看看吧
