### ISSUE TITLE
On uninstall we should provide option to remove any Reg Keys set for install/updates

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#19356]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install powershell via any method that also sets the reg keys needed for Microsoft Update
Uninstall PowerShell
Reboot
Check for updates
PowerShell then will install

`Came from a chat message in the PowerShell Discord/Slack`

### Expected behavior

```console
We should give option to remove regkeys as not to have a reinstall loop
```

### Actual behavior

```console
Currently it reinstalls on each reboot
```

### Environment data

```powershell
Windows
```

**Comment by kilasuit** [comment]
@TravisEz13 / @SteveL-MSFT this was something we'd missed when we added this functionality via the installer process

**Comment by kilasuit** [comment]
I believe that using the below would mitigate this if users/admins needed this (must be run from an admin session)

 ```powershell
function DoNotInstall-PwshPreview {
    $pwshRegPath = "HKLM:\SOFTWARE\Microsoft\PowerShellCore"
    $previewPath = Join-Path -Path $pwshRegPath -ChildPath "InstalledVersions\39243d76-adaf-42b1-94fb-16ecf83237c8"
    if (!(Test-Path -Path $previewPath)) {
        $null = New-Item -Path $previewPath -ItemType Directory -Force
    }
    Set-ItemProperty -Path $pwshRegPath -Name UseMU -Value 0 -Type DWord
    Set-ItemProperty -Path $previewPath -Name Install -Value 0 -Type DWord
}
function DoNotInstall-Pwsh {
    $pwshRegPath = "HKLM:\SOFTWARE\Microsoft\PowerShellCore"
    $previewPath = Join-Path -Path $pwshRegPath -ChildPath "InstalledVersions\31ab5147-9a97-4452-8443-d9709f"
    if (!(Test-Path -Path $previewPath)) {
        $null = New-Item -Path $previewPath -ItemType Directory -Force
    }
    Set-ItemProperty -Path $pwshRegPath -Name UseMU -Value 0 -Type DWord
    Set-ItemProperty -Path $previewPath -Name Install -Value 0 -Type DWord
}

DoNotInstall-Pwsh
DoNotInstall-PwshPreview
Restart-Computer -Force
```

**Comment by SteveL-MSFT** [comment]
Talking to @TravisEz13 , the `UseMU` is used for both stable and preview to determine if updates are delivered via Microsoft Update.  So if you uninstall stable, but still have preview, then this reg value will still apply to preview, but no longer to stable.  The `Install` reg value exists within the installed version reg key and that reg key DOES get removed on uninstall.  So it seems that there shouldn't be a problem here unless there's a clear repro.

**Comment by kilasuit** [comment]
@SteveL-MSFT 

Looking at this further it seems to me that the location of `Use_MU` should be a level lower than where it is currently set so that this can be set per version and not across all versions. But that is perhaps was at the time a design decision as not to clutter the registry unnecessarily. But this stops the scenario where you may want to install and update both versions and then at a later date only want to have 1 version be updated via MU, perhaps as you've decided to stick to a particular stable version but allow for updates for the preview version on specific users/systems for testing purposes. Also perhaps it's too late for us to change this without explicitly also setting `Use_MU` to 0 in respective installed version key as a way forward, but I realise that would require additional work outside of the current PR to be able to achieve this for a smallish but IMO worthwhile win from both an admin and dev perspective.

I am however happy that on removal of the Install property per version this doesn't then cause for the version to then be reinstalled via MU.
