### ISSUE TITLE
the process architecture should be a convenience variable

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#19357]
### Summary of the new feature / enhancement

A constant variable which represents the process architecture would be helpful in a number of circumstances. Currently, I have to get `[System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture`
Much in the same way we have `$IsWindows` it would be useful to have initial session state also set:
`$PSProcessArchitecture = [System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture` as a global, constant variable.

**Comment by rhubarb-geek-nz** [comment]
Devil's advocate, is it really that useful? 

When I need to know I use

```
$RID = [System.Runtime.InteropServices.RuntimeInformation]::RuntimeIdentifier
```

to find out details. But if you are dropping to that level then you are already in the weeds.

The information is already there, in well documented places and easily accessible.

The question shouldn't be "is this machine an X.Y.Z?", it should be "is the feature I want available to be used". That shouldn't depend on CPU architecture.

**Comment by rhubarb-geek-nz** [comment]
.. that said, the `$PSVersionTable` should include the `RID` just like `dotnet --info` does, just so the information gets captured when people create their issues here.

**Comment by vexx32** [comment]
WG-Engine discussed this today. We agree having this information readily available would be nice, but we aren't really convinced it makes sense to add a separate variable just for this.

Instead, we would suggest creating a sort of parallel table to $PSVersionTable where we collect specifically system / environment information that users may need. Taking values from the RuntimeInformation class as well as some values from System.Environment were suggested as a basis for this.

It may also prove to be a more useful and sensible place to expand in future for various convenience-of-access values that we don't necessarily want in $PSVersionTable (which should generally stick to just information directly relevant to pwsh itself).

**Comment by mklement0** [comment]
I don't think there's a need for a _parallel_ table to `$PSVersionTable`:

It is derived from `[hashtable]` and therefore intrinsically extensible.

A related discussion can be found in:

* #19121

If the concern is that additional entries shouldn't _display_ by default, this could be addressed with formatting data specific to the `System.Management.Automation.PSVersionHashTable` type.

Info for troubleshooting - such as when opening issues in this repo - could be obtained with `$PSVersionTable | Select-Object *` (ordering may need to be addressed).

**Comment by mklement0** [comment]
Come to think of it:

* _For-display_ representations aren't part of the backward-compatibility contract.

* Perhaps the better approach may therefore be:
  * Keep all existing entries for _programmatic_  backward-compatibility, but by default _hide from display_ those that probably aren't _typically_ of interest, such as `GitCommitId`, `PSCompatibleVersions`, `PSRemotingProtocolVersion`, `SerializationVersion`, and `WSManStackVersion`
  * Instead, by default only _display_ those relevant _for troubleshooting_ (in addition to `PSVersion`, which is _always_ of interest).

**Comment by vexx32** [comment]
The concern wasn't "is PSVersionTable too big" it was "there are things in PSVersionTable that don't make sense there". The intention for PSVersionTable is (paraphrasing from folks on the WG) to be "information/metadata about PowerShell _itself_." From that standpoint, environment or operating system information does not belong there, and the little there is already there should never have been added in the first place.

**Comment by rhubarb-geek-nz** [comment]
> The intention for PSVersionTable is (paraphrasing from folks on the WG) to be "information/metadata about PowerShell _itself_." 

It does not include what build of `pwsh` is running. `pwsh` is native app but does not say what CPU architecture it is for or was it built for RHEL, Debian or Alpine.
