### ISSUE TITLE
Powershell 5.1 not accepting keyboard input when using the Remote Resktop HTLM5 Web Client 

### ISSUE THREAD

**Issue by brolifen** [PowerShell/PowerShell#19355]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install the latest RDS HTML5 client on a RDS deployment as specified here: https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin

1. Open a web browser session and start an RDS session. 
2. Start powershell
3. keyboard input not working
4. start Powershell ISE
5. keyboard input works fine

The only key input that is accepted is the enter key or Ctrl+ combinations.

### Expected behavior

```console
test
```

### Actual behavior

```console
nothing happens
```

### Environment data

```powershell
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.20348.1366                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.20348.1366                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

**Comment by kilasuit** [comment]
@brolifen this repo is not for PowerShell 5.1 related issues so is very unlikely to get any traction from the team at all & as such I believe this is an issue that should be submitted to the Windows Server Team instead as it is an issue with RDS
