### ISSUE TITLE
invoke-command -ScriptBlock exception

### ISSUE THREAD

**Issue by Dimutrulkin** [PowerShell/PowerShell#1935]
Steps to reproduce
------------------
1. Install powershell-6.0.0-alpha.9.pkg
2. Run powershell in the iTerm
3. Run command:
     invoke-command -ScriptBlock {restart-computer} -ComputerName server1

Expected behavior
-----------------
Do something  on a remote computer with Windows Server 2012 R2

Actual behavior
---------------
PS /Users/dmitriy> invoke-command -ScriptBlock {restart-computer} -ComputerName server1

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Remoting.PrioritySendDataCollection.Clear()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.WSManClientSessionTransportManager.CloseAsync()
   at System.Management.Automation.Remoting.Client.BaseClientTransportManager.Finalize()
[1]    5369 abort      powershell

Environment data
----------------
PS /Users/dmitriy> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

 dmitriy@MacBook-Pro> uname -a
Darwin mbp-dmitriy.kontur 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Comment by DexterPOSH** [comment]
PowerShell remoting is not working with the current release of 6.0.0-alpha (GitCommitId  v6.0.0-alpha.8), the issue with New-PSSession is documented in the known issues. 

Perhaps Invoke-Command should be added to the list as well.

https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md

**Comment by Dimutrulkin** [comment]
Thanks.
