### ISSUE TITLE
pwsh 7.3.3 on RHEL 8 core dumps in a specific circumstance

### ISSUE THREAD

**Issue by tonyguadagno** [PowerShell/PowerShell#19351]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

hi, i have powershell 7.3.3 installed on rhel 8 (current patching).  running pwsh from command line always seems to work, but i am using Nagios and the NCPA agent.  in this case, i have the NCPA agent calling a wrapper script like this:

```
#!/usr/bin/bash
/usr/bin/pwsh -file /usr/local/bin/ps_PHPFPMStatusCheck.ps1 -statusuri /php-fpm-status
exit $?
```
running this wrapper from command line works fine, even when i am logged in as the ncpa user(nagios), but when the ncpa daemon calls it, i get this:
```
Mar 16 10:34:08 server powershell[806740]: (7.3.3:1:80) [Perftrack_ConsoleStartupStart:PowershellConsoleStartup.WinStart.Informational] PowerShell console is starting up
Mar 16 10:34:08 server powershell[806740]: (7.3.3:B:80) [NamedPipeIPC_ServerListenerStarted:NamedPipe.Open.Informational] PowerShell has started an IPC listening thread on process: 806740 in AppDomain: None.
Mar 16 10:34:08 server powershell[806740]: (7.3.3:1:80) [Perftrack_ConsoleStartupStop:PowershellConsoleStartup.WinStop.Informational] PowerShell console is ready for user input
Mar 16 10:34:08 server kernel: traps: pwsh[806750] general protection fault ip:7f038d1d1929 sp:7ec262d824c8 error:0 in libcoreclr.so[7f038d0cf000+4e0000]
Mar 16 10:34:08 server systemd[1]: Started Process Core Dump (PID 806759/UID 0).
Mar 16 10:34:09 server systemd-coredump[806760]: Resource limits disable core dumping for process 806740 (pwsh).
Mar 16 10:34:09 server systemd-coredump[806760]: Process 806740 (pwsh) of user 977 dumped core.
Mar 16 10:34:09 server systemd[1]: systemd-coredump@38-806759-0.service: Succeeded.
```

Powershell is core dumping when the daemon runs the script but not when the user does. 
does anyone have a suggestion on how to avoid this issue, i need the ncpa daemon to be able to run this script.

i should also say that i have 4 similarly configured RHEL 8 servers, all at the same patch level.  on 2, the daemon is able to run the script successfully, on the other 2, i get these core dumps.  i know there must be some differences between the servers but i have looked and i don't see any

thanks

### Expected behavior

```console
no core dumps
```

### Actual behavior

```console
Mar 16 10:34:08 server powershell[806740]: (7.3.3:1:80) [Perftrack_ConsoleStartupStart:PowershellConsoleStartup.WinStart.Informational] PowerShell console is starting up
Mar 16 10:34:08 server powershell[806740]: (7.3.3:B:80) [NamedPipeIPC_ServerListenerStarted:NamedPipe.Open.Informational] PowerShell has started an IPC listening thread on process: 806740 in AppDomain: None.
Mar 16 10:34:08 server powershell[806740]: (7.3.3:1:80) [Perftrack_ConsoleStartupStop:PowershellConsoleStartup.WinStop.Informational] PowerShell console is ready for user input
Mar 16 10:34:08 server kernel: traps: pwsh[806750] general protection fault ip:7f038d1d1929 sp:7ec262d824c8 error:0 in libcoreclr.so[7f038d0cf000+4e0000]
Mar 16 10:34:08 server systemd[1]: Started Process Core Dump (PID 806759/UID 0).
Mar 16 10:34:09 server systemd-coredump[806760]: Resource limits disable core dumping for process 806740 (pwsh).
Mar 16 10:34:09 server systemd-coredump[806760]: Process 806740 (pwsh) of user 977 dumped core.
Mar 16 10:34:09 server systemd[1]: systemd-coredump@38-806759-0.service: Succeeded.
```

### Error details

```console
Mar 16 10:34:08 server powershell[806740]: (7.3.3:1:80) [Perftrack_ConsoleStartupStart:PowershellConsoleStartup.WinStart.Informational] PowerShell console is starting up
Mar 16 10:34:08 server powershell[806740]: (7.3.3:B:80) [NamedPipeIPC_ServerListenerStarted:NamedPipe.Open.Informational] PowerShell has started an IPC listening thread on process: 806740 in AppDomain: None.
Mar 16 10:34:08 server powershell[806740]: (7.3.3:1:80) [Perftrack_ConsoleStartupStop:PowershellConsoleStartup.WinStop.Informational] PowerShell console is ready for user input
Mar 16 10:34:08 server kernel: traps: pwsh[806750] general protection fault ip:7f038d1d1929 sp:7ec262d824c8 error:0 in libcoreclr.so[7f038d0cf000+4e0000]
Mar 16 10:34:08 server systemd[1]: Started Process Core Dump (PID 806759/UID 0).
Mar 16 10:34:09 server systemd-coredump[806760]: Resource limits disable core dumping for process 806740 (pwsh).
Mar 16 10:34:09 server systemd-coredump[806760]: Process 806740 (pwsh) of user 977 dumped core.
Mar 16 10:34:09 server systemd[1]: systemd-coredump@38-806759-0.service: Succeeded.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Thu Feb 2 13:01:45 EST 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by tonyguadagno** [comment]
i am not sure if this is helpful, but i have an strace of the issue failing and also of one that succeeds.
[ncpa-works.txt](https://github.com/PowerShell/PowerShell/files/10993837/ncpa-works.txt)
[ncpa-failed.txt](https://github.com/PowerShell/PowerShell/files/10993838/ncpa-failed.txt)

**Comment by 237dmitry** [comment]
Why not run `/usr/local/bin/ps_PHPFPMStatusCheck.ps1` directly? Make it executable and add shebang header.

```
#!/usr/bin/pwsh

script body
```

**Comment by MostHated** [comment]
I just stated getting this today for some reason, but on v7.3.4, and on Ubuntu. Last time this happened, somewhere in v7.2.x, I just changed all my scripts to use pwsh-preview for a while, then checked again a few weeks later, and it was working again. No actual idea as to why or what caused it. It was working fine last night, then today, it is not.

This is what it gives me if I try to run a script from bash, either by means of `./script_name.ps1' using a shebang, or `pwsh -file script_name.ps1`. If I enter a pwsh session, and run the script from within powershell, it will run.

```log
May 18 13:24:11 mosthated-pc kernel: [12475.449290] traps: pwsh[113929] general protection fault ip:7f6da3ec5457 sp:7f2c615fe6e0 error:0 in libcoreclr.so[7f6da3dc2000+4e2000]
```
I tried reinstalling it, and what not, but that made no difference, so I am just using pwsh-preview again for the time being.

**Comment by tonyguadagno** [comment]
hi, initially i had some servers working and others not.  after openening this issue, the rest stopped working and i could not use powershell in this way at all.  so i kind of abandoned the idea.
after your post, i revisited it and wow....its working again...what changed?  well, here is the versiontable and i am on 7.3.4 now.  also the kernel is a small bit newer?
i don't know what the issue was or why it is working now, but it is working.....good luck!

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 4.18.0-425.19.2.el8_7.x86_64 #1 SMP Fri Mar 17 01:52:38 EDT 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
