### ISSUE TITLE
Issue Template should require for the OS to be reported / Update PSVersionTable Output

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#1936]
In the current Issue Template there isn't a request for the OS to be reported and although I think updating the template to include it would be simple I personally think that updating $PSVersionTable to also report the OS & bitness would be a great change to make as this can provide a 1 stop variable for us to get most of the required information we'd need for simple issue triaging going forward

Any thoughts on either?

**Comment by SteveL-MSFT** [comment]
#2009 needs to work to make this easy

we should probably still include this in the template, for the template @kilasuit you can submit a PR

**Comment by SteveL-MSFT** [comment]
once the work to add OS info #1635 into psversiontable is complete, it is implicitly in the template.  no additional work needed.
