### ISSUE TITLE
Support for Windows package manager `winget` 

### ISSUE THREAD

**Issue by upyesp** [PowerShell/PowerShell#19360]
### Summary of the new feature / enhancement

Hi,

For several weeks PowerShell has notified me of a new release, v7.3.3.

It would be great to update PowerShell using the Windows Package Manager, winget.

Request: Please add winget updates as part of the release strategy.

Thanks.

**Comment by doctordns** [comment]
There are several ways to get this update and those depend on how you installed PowerShell 7:

1. If you used the MS Store, PowerShell should be updated pretty quickly and automagically. It DOES take time from when the build hits GitHub (and the metadata now tells PowerShell there is a newer version). I think we hope for less than 2 weeks.
2. If you used an external packager manager, such as Chocoltey, and WinGet - you should be able to use their update functions once their repositories have the update. I like Chocolately and find them fairly up-to-date but mileage may vary! You should contact your packager manager team to ask them to update PowerShell faster. :-)
3. If, like me, you used the `Install-PowerShell.ps1` script (get it here: https://github.com/PowerShell/PowerShell/blob/master/tools/install-powershell.ps1).. you can just rerun the script using the `-UseMSI` switch. 
4. If you used the MSI to install PowerShell 7, either via the script or by downloading it directly from GitHub, the MSI allows you to specify that Microsoft Update should update PowerShell. This is similar to the store. Initially, it took about 2 weeks for MU to perform the updates, but this seems to be getting faster (again, the mileage may vary).

One thing about the MU Updates - MU does not update from a Long Term Support version (eg 7.2.x) to a shorter-term support version (eg any of the 7.3 releases). I am _not_ sure what is going to happen when the team release 7.,4 (later this year). I assume 7.2 builds WILL get updated (but I need to check) - so 7.2.x to 7.4.x.
