### ISSUE TITLE
Add an option to refrain from getting the 'a new stable release..'

### ISSUE THREAD

**Issue by abirstolov** [PowerShell/PowerShell#19369]
### Summary of the new feature / enhancement

It is annoying to keep getting the 'there is a new stable powershell version available..'

I may want to opt to keeping the same version for various reasons (e.g. the changes aren't relevant for me, the new featues are not worth it, etc..)

I suggest to add in the configuration a way to disable this message or the new version check.

**Comment by jhoneill** [comment]
I use pwsh -nologo / powershell.exe -nologo  to remove all the start up clutter, and IIRC that includes the new version announcements. I have the current release of 7 so I can't check, but it certainly hides the message from 5.

**Comment by SteveL-MSFT** [comment]
This is already supported: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.3
