### ISSUE TITLE
Whats the difference in CTL checkling when using -noni (-NonInteractive)?

### ISSUE THREAD

**Issue by matsmcp** [PowerShell/PowerShell#19362]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If I start PWSH on a non internet connected system the startup is very slow due to attempts to reach aka.ms and CTLDL.windowsupdate.com as documented  (and I did verify with Wireshark)

according to older threads about this it's a Windows "feature" and nothing related to Powershell. 
However if I launch PWSH with the -noni switch it does not try to call CTLDL.windowsupdate.com and the startup is very fast. 

This seems to indicate to me that it is something in Powershell that gets loaded unless -noni is used that causes these CTL checks. Since using Noni is a little disruptive it would be nice to have a way to just avoid the function that calls the CTL check and not the rest of the functions that gets disabled by -noni

### Expected behavior

```console
Fast start every time
```

### Actual behavior

```console
Slow start then not using -noni
```

### Error details

```console
15-30 sec startup time when powershell 5 takes about 1 second. This is not a good user experience 

the developers/users are not admins on the machines and can therefore not change any system settings like CTL timeouts
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
In my environment set variables to disable telemetry and update checking. Linux variant:
```powershell
 $ gc /etc/environment | sls 'POW' -raw
POWERSHELL_TELEMETRY_OPTOUT=1
POWERSHELL_CLI_TELEMETRY_OPTOUT=1
POWERSHELL_UPDATECHECK=Off
POWERSHELL_UPDATECHECK_OPTOUT=1
```

**Comment by mklement0** [comment]
Thanks, @237dmitry. 

[Section "PowerShell environment variables"](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Environment_Variables#powershell-environment-variables) in [about_Environment_Variables](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Environment_Variables) doesn't mention `POWERSHELL_CLI_TELEMETRY_OPTOUT` and `POWERSHELL_UPDATECHECK_OPTOUT`, however, and those names also don't appear in the source code.

From what I can tell, ad hoc, CLI parameters only allow you to suppress the _update-notification_ check, but not also _telemetry_ (for the latter you need to environment variables).

`-noninteractive` alone does _not_ seem to suppress the _update-notification_ check - see https://github.com/PowerShell/PowerShell/blob/69e9b439fd38177ff7f3af1ef62f5617454bcf23/src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs#L908-L912 -  but `-nologo` does, as do any parameter combinations that result either in run-in-server-mode or execute-something-and-exit behavior.

**Comment by matsmcp** [comment]
Telemetry and updatechecking is not related to this. 
This is Powershell on Windows causing 
1	0.000000	X.X.X.X	Y.Y.Y.Y	DNS	83	Standard query 0x29ac A ctldl.windowsupdate.com
......
7	8.032771	X.X.X.X	Y.Y.Y.Y	DNS	83	Standard query 0x29ac A ctldl.windowsupdate.com

If you start with -Noni there are no attempts to reach ctldl.windowsupdate.com
Disabling telemetry or updatechecks or profile loading does not affect the attempts to call ctldl

**Comment by 237dmitry** [comment]
> Disabling telemetry or updatechecks or profile loading does not affect the attempts to call ctldl
>> ctldl

Expired or wrong сertificates? Try to restore them:
```
certutil /?
# certutil -f -verifyCTL AuthRoot
# certutil -f -verifyCTL Disallowed   # or DisallowedWU ?
```

**Comment by mklement0** [comment]
Ah, good point: I completely missed the certificate angle.
Glancing at the code it is unclear to me how `-noninteractive` translates into _not_ contacting `CTLDL.windowsupdate.com` or `aka.ms`, but perhaps someone more knowledgeable in this area can help.

(It is also curious that interactively navigating to `https://ctldl.windowsupdate.com` gives a _certificate error_ ("This server could not prove that it is ctldl.windowsupdate.com; its security certificate is from *.hs.llnwd.net"))

As an aside: As the name suggests, `-NonInteractive` isn't suitable for interactive sessions; curiously, however, you're currently allowed to start an interactive session with `pwsh -NonInteractive` - see #13518

**Comment by 237dmitry** [comment]
What about delay when rebooting?
I do not know where this settings (from group policies):

![https://habrastorage.org/r/w1560/files/f9f/61e/24d/f9f61e24dc7145e084e339a0e1885ab3.png](https://habrastorage.org/r/w1560/files/f9f/61e/24d/f9f61e24dc7145e084e339a0e1885ab3.png)

**Comment by iSazonov** [comment]
It is old history related PSReadLine. See https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-552023412 and follow comments there.

**Comment by matsmcp** [comment]
No It's not a duplicate and it's not solved 

As I stated in the first post "he developers/users are not admins on the machines and can therefore not change any system settings like CTL timeouts" therefore refering to changing the CTL timeout doesn't help at all

**Comment by matsmcp** [comment]
@mklement0 

Yes. I have seen that one but as you said - Still open after four years. 

I found a different approach today (needs more testing) but it seems to work. 
`https://social.technet.microsoft.com/Forums/en-US/f245b6ff-bad5-45db-8727-c57afea60054/gpo-disable-check-for-publishers-cerficate-revocation?forum=winserverGP
`
Being an HKCU setting making it useful even if the user doesn't have admin rights. 
It's a little bit better than killing it in system level to. More like using a cannon to kill the bug rather than dropping a nuke on it

**Comment by matsmcp** [comment]
@mklement0 

I my eyes being able to disable CRL checking is a security risk in a connected system. I hope that there is a GPO to enforce it in that situation. 

There has been compromised certificate issuers and there have been fraudulent certificates from genuine issuers (ex the well known MS certificate https://www.theregister.com/2001/03/23/microsoft_vexed_by_falsified_certs/)

**Comment by nanoric** [comment]
I'm facing the same probem but didn't find any solution here, so why this issue is closed?
