### ISSUE TITLE
IFeedbackProvider should be able to be called when there is not an error

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#19372]
### Summary of the new feature / enhancement

It should be possible to call the predictor in those cases where there wasn't an error.
For example, if the user types a command which was successful, but there is a better way to express the operation.
ex.
```powershell
PS> uname -a
```
could be prompted to run
```powershell
PS> uname -a | jc --uname | convertfrom-json
```
if the `jc` command is installed.

**Comment by JamesWTruher** [comment]
this is related to: https://github.com/PowerShell/PowerShell/issues/19364

**Comment by daxian-dbw** [comment]
@JamesWTruher I think you mean the `IFeedbackProvider`.

**Comment by StevenBucher98** [comment]
Closing because this is fixed in #19525
