### ISSUE TITLE
PowerShell ISE incorrectly respecting DragHeight & DragWidth values

### ISSUE THREAD

**Issue by 29039** [PowerShell/PowerShell#19377]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

REG add "HKCU\Control Panel\Desktop" /v "DragHeight" /t REG_SZ /d "200" /f
REG add "HKCU\Control Panel\Desktop" /v "DragWidth" /t REG_SZ /d "200" /f

Sign out of Windows, and back in.

Open PowerShell ISE

Open a Powershell script (or text document) with many lines to it.

In the script editing area, try highlighting the text with the mouse cursor

### Expected behavior

```console
The text should highlight as normal
```

### Actual behavior

```console
The mouse needs to be left clicked and dragged (at the same time) over 200 pixels (in this example) before the text actually starts to highlight.

The DragHeight and DragWidth is meant to apply to dragging icons around Windows Explorer, not for the purposes of highlighting text.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

First I have left click and dragged from Lorem to amet. No highlighting:

![image](https://user-images.githubusercontent.com/61966298/226544350-227fd8ab-9880-4977-acd8-15882f2b4bae.png)

Now I go past the "amet." and it starts to highlight from where I started:

![image](https://user-images.githubusercontent.com/61966298/226544505-c5b3fda3-63d7-4d30-a057-0756d2c451fa.png)

Same but instead of going Horizontal, I have gone straight down vertical:

![image](https://user-images.githubusercontent.com/61966298/226544648-500250b9-8c79-4d4c-9ba0-cbaad50e68c4.png)

**Comment by 29039** [comment]
> This repo is concerned with PowerShell 7, the issues relating to Windows Power (5) and the ISE need to be raised with the windows team via the windows feedback tool.

In PowerShell ISE, Go to Help > Windows PowerShell ISE Help

It opens URL https://go.microsoft.com/fwlink/?LinkID=275852

At the bottom of this page it says "Submit and view feedback for [This Product]"

It takes me to this repo.

Therefore, this should be the correct place to post it.

Thanks.

**Comment by jhoneill** [comment]
The link on that page is incorrect. Nothing related to the PowerShell ISE is in this repo (AFAIK, the ISE has not been open sourced). Anything related to PowerShell 6 and later is here. Modules shipped with Windows, and Windows PowerShell itself are looked after by different people.  You can hope that someone developing PowerShell 7 passes your issue over to someone maintaining Windows PowerShell, or you can open feed back for the Windows team. But if you get an  answer it won't be here.
