### ISSUE TITLE
Literal Calculated Property Value

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#19386]
### Summary of the new feature / enhancement

Simply adding a literal value to an object using `Select-Object` with a calculated property results in an error:

```PowerShell
[PSCustomObject]@{
    b = 2
    c = 3
} |Select-Object @{ n='a'; e=1 },b,c

Select-Object:
Line |
   4 |  } |Select-Object @{ n='a'; e=1 }
     |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The "e" key has a type, System.Int32, that is not valid; expected types are {System.String, System.Management.Automation.ScriptBlock}.
```

Or in a `$Null`
```PowerShell
[PSCustomObject]@{
    b = 2
    c = 3
} |Select-Object @{ n='a'; e='1' },b,c

a b c
- - -
  2 3
```

Or simply disappears: (???)
```PowerShell
[PSCustomObject]@{
    b = 2
    c = 3
} |Select-Object @{ n='a'; e='1*1' },b,c

b c
- -
2 3
```

To get this to work, I am obliqued to invoke an *expression*:
```PowerShell
[PSCustomObject]@{
    b = 2
    c = 3
} |Select-Object @{ n='a'; e={1} },b,c

a b c
- - -
1 2 3
```

### Proposed technical implementation details (optional)

Apart from the unattractive syntax (with embedded curly brackets), the value is not always required to be (re)evaluated, as in the Stackoverflow question: [powershell add key value to the json](https://stackoverflow.com/questions/75799549/powershell-add-key-value-to-the-json), I would just like to add a `name=(literal)value` at a certain position, e.g.,:

```PowerShell
Select-Object @{ n='apiVersion'; e='2016-06-01' }, kind, properties 
```

**Comment by mklement0** [comment]
While I understand the desire for simplification, a _string_-valued `Expression` entry in a hashtable serving as a calculated expression has existing semantics (which may not be obvious), and allowing arbitrary values would clash with that:

A _string_-valued `Expression`  value is interpreted as a _property name_; e.g.:

```powershell
[pscustomobject] @{
  '2016-06-01' = 'hi'
} | Select-Object @{ n='apiVersion'; e='2016-06-01' }
```

Output:
```
apiVersion
----------
hi
```

There's an older issue that proposed a fundamental simplification of the object-literal syntax:

* #8107

**Comment by iRon7** [comment]
@mklement0,

> A string-valued `Expression` value is interpreted as a *property name*

Thanks , this explains the unexpected behavior.

I have:
* Created a document issue: [`#9945` A string-valued Expression value is interpreted as a property name for Select-Object](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9945)
* Closed this issue
* Created a new request: #19388
