### ISSUE TITLE
enable support for accessing old servers as there is no possibility to upgrade them as they run legacy applications. No matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

### ISSUE THREAD

**Issue by insinfo** [PowerShell/PowerShell#19389]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

try accessing an old SSH server and you will see the problem
ssh root@192.168.66.4

### Expected behavior

```console
I hope it loads the SSH shell normally
```

### Actual behavior

```console
> ssh root@192.168.66.4
Unable to negotiate with 192.168.66.4 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
```

### Error details

```console
Unable to negotiate with 192.168.66.4 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
```

### Environment data

```powershell
PS C:\MyDartProjects\new_sali> $PSVersionTable                                                                                         

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/12227024/226934511-2da0c20a-26bc-4a67-a2d2-0bff81e9f302.png)

**Comment by kasini3000** [comment]
What is your Linux distribution and version?

try old version of ssh.exe at here:
https://github.com/PowerShell/Win32-OpenSSH/releases

**This tip comes from powershell fans**

**Comment by rhubarb-geek-nz** [comment]
What does this have to do with PowerShell? 

If I run "ssh" on Linux it uses the native version typically in `/usr/bin/ssh`. If I use "ssh" on a Windows machine it uses the one from `c:\windows\system32\OpenSSH\ssh.exe`

If you want to run a legacy version of ssh.exe that is entirely up to you.

**Comment by jborean93** [comment]
Yep `ssh` is something separate from PowerShell itself and is not controlled by PowerShell. You'll have to ensure the policies you've configured on the client and server match up to allow an algorithm to use. This is all done outside of PowerShell.

**Comment by insinfo** [comment]
even removing "c:\windows\system32\OpenSSH\ssh.exe" from the path. Powershell ssh continues to work, which seems to me that Powershell has ssh built-in, that's why I opened the problem here because until a while ago it was working normally on the Linux Debian 6 server. I ended up finding a solution
```console
PS C:\MyDartProjects\new_sali> cat C:/Users/isaque.neves/.ssh/config
Ciphers +aes128-cbc,aes256-cbc,3des-cbc
KexAlgorithms +diffie-hellman-group14-sha1
HostkeyAlgorithms +ssh-rsa
# If you authenticate using a keypair:
PubkeyAcceptedAlgorithms +ssh-rsa
```

**Comment by kasini3000** [comment]
Are you a powershell fan?
Powershell on ssh let you pass objects on both local and remote Linux servers by powershell-ssh-remoting.
Translate and read my post powershell tip using a browser:
http://bbs.chinaunix.net/thread-4319932-1-1.html
----
As far as I know, Debian 8 can use the powershell.
I don't know if the new version of Powershell will run on Debian 6.
But,because the powershell can be decompressed and run.
https://github.com/PowerShell/PowerShell/releases/download/v7.0.13/powershell-7.0.13-linux-x64.tar.gz
https://github.com/PowerShell/PowerShell/releases/download/v6.2.7/powershell-6.2.7-linux-x64.tar.gz
Would you like to try it on debian 6?

**Comment by rhubarb-geek-nz** [comment]
> even removing "c:\windows\system32\OpenSSH\ssh.exe" from the path. Powershell ssh continues to work

You may have multiple different ssh.exe on your path. One way to identify what is being used is to start an ssh session with another host and then use with Windows Task manage to find the "ssh" process and then use "open file location" to see where it lives
