### ISSUE TITLE
Long strings with multi-byte characters are not properly pasted onto PowerShell 

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/PowerShell#19396]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Repro steps:
1. Open attached file to these repo steps (repro_text.txt) with notepad. This file contains texts with several multi-byte characters.
2. Copy all texts in the file to clipboard.
3. Open PowerShell on Mac or Linux - Or open PowerShell in Azure Cloud Shell, then paste the text.
4. Multi-byte characters are not pasted properly (garbled) after string reaches to some length.
<img width="857" alt="Screenshot 2023-03-22 at 3 23 50 PM" src="https://user-images.githubusercontent.com/12662278/227051890-5326a502-e04e-4519-bf81-1cdd4a9e3778.png">

[repro_text.txt](https://github.com/PowerShell/PowerShell/files/11045157/repro_text.txt)

### Expected behavior

```console
Paste without garbled characters.
```

### Actual behavior

```console
Described in repo steps
```

### Error details

```console
described in repo steps
```

### Environment data

```powershell
This affects PowerShell 7.2 7.3 on linux.  PowerShell 7 on Windows and Windows PowerShell 5.1 do not have this problem.
```

**Comment by 237dmitry** [comment]
Linux:

![ArcoLinux_2023-03-23_08-50-05](https://user-images.githubusercontent.com/78153320/227115447-a9930fd5-a76c-42d6-832e-460415b28839.png)

**Comment by rhubarb-geek-nz** [comment]
> 3. Open PowerShell on Mac or Linux - Or open PowerShell in Azure Cloud Shell, then paste the text.

How are you opening PowerShell on Mac or Linux? You say this is from Windows so are you using another Terminal together with ssh or is this PSRemote? 

What browser are you using when connecting to Azure?

When you open the connection, what do you have the language settings set to for (a) the client and (b) the server? You refer to "multi-byte characters", so this is not UNICODE or UTF8? 

Do you have the same problem if pasting into a normal bash, similar shell or text editor on the target system?

**Comment by jhoneill** [comment]
With Windows terminal 

- Pasted into PowerShell 7 running natively OK
- Pasted into PowerShell 7 running on WSL on the same machine - corrupt
- Pasted into bash running on WSL  on the same machine OK.

My first instinct was that this was a terminal problem not a PowerShell one, but those results suggest differently. 

CRLF looked like a problem but changing to simply LF doesn't help.  I also get it with pwsh on WSL with just one line and no final line break.

**Comment by rafatecoy** [comment]
Hello! What's the status here? I have another customer facing the same issue and looks like this request was closed without activity. Thank you!
