### ISSUE TITLE
Selective disabling/re-enabling of VT support (ANSI escape sequences) is broken

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19395]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

As discussed in #18771, which was inappropriately closed, as well as in https://github.com/PowerShell/PowerShell/issues/19101#issuecomment-1421180987:

Note:

* Applies to `conhost.exe` windows (regular console windows on Windows) only. 

```powershell
cmd /c ver | Select-String Microsoft
```

### Expected behavior

```console
Microsoft Windows [Version 10.0.22621.1413]
```

... with the word `Microsoft` highlighted

### Actual behavior

```console
←[7mMicrosoft←[0m Windows [Version 10.0.22621.1413]
```

That is, the ANSI escape sequences meant to highlight the matching part of the line aren't rendered as such.

### Environment data

```powershell
PowerShell 7.4.0-preview.2 on Windows
```

**Comment by jhoneill** [comment]
@mklement0  It might avoid "works for me" messages if you made it explicit that this is in conhost only.

**Comment by mklement0** [comment]
Thanks, @jhoneill  - good idea; I've updated the initial post.

**Comment by SteveL-MSFT** [comment]
This appears to be conhost specific

```powershell
ipconfig | select-string wireless
```

as it doesn't repro in Windows Terminal.  It seems that conhost is not rendering ESC correctly for some reason.

**Comment by mklement0** [comment]
@SteveL-MSFT, we've been through this before, in #18771, which was equally labeled incorrectly - but since all arguments to that effect fell on deaf ears, I opened _this_ issue with a simpler repro.

Between all the information in the initial post and the linked issues / comments it should by now be obvious that the problem is _PowerShell_'s selective dis- and re-enabling of ANSI escape sequences.

Again, implementing  #19101 would make this problem go away, but this opportunity was passed up.

**Comment by mklement0** [comment]
Also, @SteveL-MSFT, as a reminder: `cmd /c ver | Select-String Microsoft` works just fine in the current LTS version, 7.2.10.
