### ISSUE TITLE
SqlServer Module does not load all the Test- Cmdlet's

### ISSUE THREAD

**Issue by 460163** [PowerShell/PowerShell#19394]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install-Module sqlserver # (as admin)
Import-Module sqlserver
Get-Command -module sqlserver Test*

### Expected behavior

```console
Get-Command -module sqlserver Test*

CommandType     Name                                               Version    Source                                                                    
-----------     ----                                               -------    ------                                                                    
Cmdlet          Test-SqlAvailabilityGroup                          21.1.18256 SqlServer                                                                 
Cmdlet          Test-SqlAvailabilityReplica                        21.1.18256 SqlServer                                                                 
Cmdlet          Test-SqlDatabaseReplicaState                       21.1.18256 SqlServer                                                                 
Cmdlet          Test-SqlSmartAdmin                                 21.1.18256 SqlServer
```

### Actual behavior

```console
Get-Command -module sqlserver Test*
** Nothing is returned **
```

### Error details

```console
No errors
```

### Environment data

```powershell
Get-Module -ListAvailable | Where-Object { $_.Name -Match 'SqlServer' }

    Directory: C:\Users\xxxx\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     21.1.18256            SqlServer                           Desk      {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGroupListenerStaticIp, Add-SqlAzureAuthenticationContext…}

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Visual Studio Code
Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

**Comment by 460163** [comment]
Just to add more details: The issue is with latest version of PowerShell

In PowerShell 7.3.3
$PS1> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      3

PS1> (Get-Module -l SqlServer).path
C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18256\SqlServer.psd1

PS1> Get-Command -Module "SqlServer" | Where-Object { $_.Name -Match 'Test-' }
PS1> 

In PowerShell 5.1
PA1> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2673
PS1> (Get-Module -l SqlServer).path
C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18256\SqlServer.psd1

PS1> Get-Command -Module "SqlServer" | Where-Object { $_.Name -Match 'Test-' }

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Test-SqlAvailabilityGroup                          21.1.18256 SqlServer
Cmdlet          Test-SqlAvailabilityReplica                        21.1.18256 SqlServer
Cmdlet          Test-SqlDatabaseReplicaState                       21.1.18256 SqlServer
Cmdlet          Test-SqlSmartAdmin                                 21.1.18256 SqlServer

**Comment by kilasuit** [comment]
I can replicate this in versions of PowerShell going as far back as 6.0.0 - therefore I think that this is an issue with how this module is written & in my testing even testing in PowerShell `7.3.3` with the current latest preview module version which is `22.0.49` I only get the following `Test` Cmdlet show - `Test-SqlSmartAdmin` as shown below

![image](https://user-images.githubusercontent.com/6355225/227075598-6747f1df-41b5-423c-a923-b323d6c22f4c.png)


So for now this module isn't fully supported in PowerShell versions beyond the latest 5.1 included in windows builds and if you need to use those cmdlets you'd need to revert to 5.1.

I have, however, sent a report via the [PowerShellGallery's Contact Owners feature for this module](https://www.powershellgallery.com/packages/SqlServer/22.0.49-preview/ContactOwners), (which you can do for any module that doesn't have a Project Site listed on the PowerShell Gallery page listing), to the module owner so we may get a response as to when they expect all the other cmdlets will work.

However as this is a module issue and not a PowerShell issue this will be marked as resolution external & resolution answered for now.

**Comment by 460163** [comment]
Oh I didn't know that this was possible.  Does the module have a compatibility setting somewhere, so that I can check?
