### ISSUE TITLE
On linux, Powershell 7 reserves 200Gb+ virtual memory

### ISSUE THREAD

**Issue by suglasp** [PowerShell/PowerShell#19397]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I just wonder, I see this on a RHEL8 (Kernel 4.18) and RHEL9 (Kernel 5.18) flavors, that the Virtual memory is set to 261.Gb of ram.
It's not a problem for working of course, the real memory usage is very low. But i was just wondering if it is something in .Net or is it a Powershell 'issue' or config problem? I use the standard packages provided from the Microsoft repo's.

$ top    # (and sort on memory with SHIFT+M)
    PID USER      PR  NI    **VIRT**    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 158886 doomguy   20   0  **261.6g** 119016  92588 S   0.0   0.7   0:02.59 pwsh

$ ps -aux
USER         PID %CPU %MEM    **VSZ**   RSS TTY      STAT START   TIME COMMAND
doomguy  158886  0.8  0.8 **274302468** 142880 pts/0 Ssl+ 10:33   0:04 /opt/microsoft/powershell/7/pwsh

### Expected behavior

```console
Should ramp up when more allocated memory is needed.
```

### Actual behavior

```console
Virtual Memory that get's reserved seems very high.
```

### Environment data

```powershell
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Thu Jan 12 16:32:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
look my post :
https://github.com/PowerShell/PowerShell/discussions/17500
@vexx32

**Comment by 237dmitry** [comment]
This is more of a declarative indicator. A measure of the maximum amount of memory an application (and a complete list of shared libraries) is able to use. Certainly in the presence of the real hardware.

**Comment by suglasp** [comment]
Yes, I'm aware of that.

**Comment by iSazonov** [comment]
I suggest consulting with .Net team. I guess it is how .Net memory manager works.

**Comment by suglasp** [comment]
Close issue unresolved.

**Comment by pearj** [comment]
For anyone reading this later, it seems to be a feature of the dot net core garbage collector. It allocates the maximum about of virtual memory available for a given machine.

https://habr.com/en/articles/779564/

> ... As you remember, not accessed virtual memory is not allocated...

> Why .NET needs this? That’s because .NET garbage collector needs continuous address space for the heap, so it allocates the [maximum available amount](https://github.com/dotnet/runtime/blob/26158bfdf528fe164634f79777313f9cd7e310a9/src/coreclr/gc/unix/gcenv.unix.cpp#L1091) of address space.
