### ISSUE TITLE
Add support for defining starting date for -Audit parameter of New-CIPolicy cmdlet

### ISSUE THREAD

**Issue by HotCakeX** [PowerShell/PowerShell#19407]
### Summary of the new feature / enhancement

[`New-CIPolicy -Audit`](https://learn.microsoft.com/en-us/powershell/module/configci/new-cipolicy) scans the entire event viewer logs and creates a WDAC policy based on them. I need to be able to tell it to only scan event viewer logs since X minutes ago or so, just not the entire event logs of Code integrity operational.

Useful related document: https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/audit-windows-defender-application-control-policies

### Proposed technical implementation details (optional)

```powershell
$date = (get-date) - (New-TimeSpan -Minutes 30)
New-CIPolicy -FilePath $EventsPolicy -Audit -AuditLogsSince $date -Level FilePublisher -Fallback Hash –UserPEs -MultiplePolicyFormat
```

It can accept a [DateTime] object

**Comment by SteveL-MSFT** [comment]
That cmdlet is part of Windows and not part of this repo.  You'll need to report your feedback via the Windows Feedback tool.
