### ISSUE TITLE
Corrupted terminal output after window resized

### ISSUE THREAD

**Issue by RoadToDream** [PowerShell/PowerShell#19405]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Open PowerShell from any folder such that primary prompt is longer than one line.
2. Enter any command and click enter.
3. Maximize PowerShell window so primary prompt is arranged within one line.
4. Cursor will be off-position and overwrite my primary prompt.
Video attached below:

https://user-images.githubusercontent.com/8088354/227744895-bd440e71-d068-4d41-9034-75efeeabce17.mp4

### Expected behavior

```console
PS C:\Program Files\Windows Defender Advanced Threat Protection\Classification> ls
```

### Actual behavior

```console
PS C:\Program FilelsWindows Defender Advanced Threat Protection\Classification>

Please note the input 'ls' replaces my primary prompt.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Note, although the OP is using the legacy console host in Windows Sandbox, it applies to both Windows PowerShell 5 and PowerShell  7 in Windows terminal outside the sandbox.  Cmd does appear to learn the window has been resized and doesn't seem to have the issue.

**Comment by RoadToDream** [comment]
Hi @jhoneill, thanks for adding more context to the issue. Yes, the behavior exists in both host and Windows Sandbox environments, I provide recording of PowerShell in Windows Sandbox to prevent impact from any other installed modules or custom settings.

**Comment by mklement0** [comment]
To add another data point: `PSReadLine` is the culprit. (If you run `Remove-Module PSReadLine` before maximizing the window, the problem goes away.)

**Comment by RoadToDream** [comment]
Hi @mklement0 , it does seem to be the case... Let me also submit a bug report to them...

**Comment by StevenBucher98** [comment]
Yep seems to be a bug with PSReadLine, closing this issue to track in, https://github.com/PowerShell/PSReadLine/issues/3637
