### ISSUE TITLE
Invoke-WebRequest with credential not working in Linux, but does in Windows

### ISSUE THREAD

**Issue by phillippover** [PowerShell/PowerShell#19428]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using Invoke-WebRequest with a Credential object for NTLM Negotiate authentication is returning a 401 Unauthorized response from Linux (both PowerShell running inside a Ubuntu WSL instance, as well as a Docker Container using Microsoft's Alpine based PowerShell Docker Image). The same command works fine from a Windows instance. URL is HTTPS protocol in both instances.

`Invoke-WebRequest -Uri $request.Uri -Method Get -Credential $credentials -Headers $headers -PreserveAuthorizationOnRedirect -ContentType "application/json"`

From Linux:
```
Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

From Windows:
```
StatusCode        : 200
StatusDescription : OK
Content           : {[REDACTED]
                    }
                    }
RawContent        : HTTP/1.1 200 OK
                    Cache-Control: no-cache
                    Server: Microsoft-IIS/8.5
                    ...[REDACTED]
Headers           : {[REDACTED]}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 35
RelationLink      : {}
```

### Expected behavior

```console
HTTP 200 response
```

### Actual behavior

```console
HTTP 401 Unauthorized response
```

### Error details

```console
Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

![image](https://user-images.githubusercontent.com/79399357/228848960-b134ec00-9c49-4106-8e80-e6ee66ddfee7.png)

**Comment by CarloToso** [comment]
Could you test it in PowerShell 7.4preview2 ?

**Comment by jborean93** [comment]
I know there is code in dotnet to do HTTP auth with Kerberos and NTLM (if the native libs are present) but I don’t think Invoke-WebRequest on Linux tries to use that.

**Comment by phillippover** [comment]
> Could you test it in PowerShell 7.4preview2 ?

Same result in the latest preview.

**Comment by BuriedStPatrick** [comment]
I've tested this in various different image-configurations and versions as I am having the same issue on an Arch based host system. So far it seems it largely depends on the base image, lesser so the version itself. With `7.3.3` I've gotten all Debian based images to work for instance, but Alpine does seem to struggle in this regard. This leads me to think it must have something to do with a missing underlying component somewhere that the credentials-functionality relies on.

Going from `7.3-alpine-3.14` to `7.2-alpine-3.14` for instance I get a more noisy error:

```powershell
# Response in 7.2-alpine-3.14
Invoke-WebRequest: GSSAPI operation failed with error - An invalid name was supplied (Configuration file does not specify default realm).

# Response in 7.3-alpine-3.14
Invoke-WebRequest: You do not have permission to view this directory or page.
```

It seems to be the same kind of error you get from a `dotnet restore` that uses NTLM as the authentication method on some Linux systems. I would personally appreciate a more telling error message or - at the very least - AN error message like how it worked previously. Returning a `401` status code hides the actual error and makes it very difficult to troubleshoot.

**Comment by Celer21** [comment]
Any update on this issue? Iam trying this on PS 7.5.0-preview.1 but always get error 401. On windows, the same code is working.

**Comment by Malikabdullah33550** [comment]
Any update on this issue? I am also stuck on this

**Comment by gerneio** [comment]
Interestingly I had this issue on an Ubuntu 22.04 docker image as well as WSL (also 22.04). Tested with PS 7.4-7.6. When I tried a 24.04 docker image (`mcr.microsoft.com/powershell:7.5-ubuntu-24.04`), then it worked no problem. With that in mind, I tried to install WSL with `Ubuntu-24.04`, however the 401 issue happened again (same PS version as docker container). Super strange. Clearly there is something installed on the docker image that isn't in the WSL counter part, just not sure what that is. Problem for another day...

**Comment by gnugnug** [comment]
I can confirm the observations of @gerneio. Using the image _mcr.microsoft.com/powershell_ which currently defaults to Powershell 7.4.2 on Ubuntu 22.04.4 Invoke-WebRequest is not able to perform a NTLM authentication against a webserver.
When switching to _mcr.microsoft.com/powershell:ubuntu-24.04_ which is currently using Powershell 7.5.0 on Ubuntu 24.04.1 NTLM authentication starts working without any other code changes.
It would be good if someone who creates those images could explain what their differences are.
