### ISSUE TITLE
Import-Module -Version doesn't load version provided

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#19427]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On a machine with multiple versions of PowerShellGet (as an example) 

```powershell
Import-Module PowerShellGet -Version 1.0.0.1
Get-Module PowerShellGet
```

### Expected behavior

```console
PowerShellGet 1.0.0.1 is loaded
```

### Actual behavior

```console
Latest version of PowerShellGet is loaded
```

### Environment data

```powershell
7.4.0-preview2
```

**Comment by kilasuit** [comment]
Adding to this personally I feel this is a case of Developer experience vs expected administrator experience.
To change this would be a breaking change & I believe has been discussed as to why it is this way already however on a quick search I could not find a respective issue for this.

To fix this in my mind going forward would be to add additional functionality to Import-Module as opposed to changing the overall logic flow completely of this cmdlet.

- [ ] In interactive use add a confirm prompt to the user that states the version they have listed with the -Version Parameter is not the latest one and do they want to continue to load this version or would they rather load the latest version
- [ ] for non-interactive use have a verbose output that states version loaded is not the one provided and that they should instead make use of the RequiredVersion parameter if they **really** mean to import the version provided.

This also seems like not a lot of code to add for those 2 additional paths, so would be something that I'd be happy to work on.

**Comment by ThomasNieto** [comment]
The parameter `-Version` is an alias for `-MinimumVersion` you'll want to use the `-RequiredVersion` parameter to get that exact version specified.

**Comment by kilasuit** [comment]
@ThomasNieto I know & logically from a linguistic perspective, as I alluded to from the initial comment in the `dev vs admin mindset` you'd **typically** expect that when `Version` is given, it is not aliased to `MinimumVersion` but instead `RequiredVersion`

also I had raised this issue from inspecting the current code for Import-Module and supposedly the GitHub flow from clicking `Reference in a New Issue` was  at one point meant to have referenced the lines I highlighted, however it did not, likely due to the Issue templates being used in this repo & is a GitHub Platform issue and not a PowerShell Repo issue.

Those lines in the Import-Module Cmdlet for reference are as below 
https://github.com/PowerShell/PowerShell/blob/51f55f716ea29f94ba7373e2f619cb23569c8c5d/src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs#L285-L298

**Comment by ThomasNieto** [comment]
@kilasuit while I agree that the current behavior is unintuitive and should have had a better design from the get-go, the current behavior matches [module manifest](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_module_manifests?view=powershell-7.3#requiredmodules), [ModuleSpecification](https://learn.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.modulespecification?view=powershellsdk-7.2.0), and [FullyQualifiedName](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_module_manifests?view=powershell-7.3#requiredmodules) behavior. The `ModuleVersion` value denotes minimum version. This behavior feature looks to have been added with PS 3.0. As a side note this behavior also matches NuGet where the version alone means minimum version inclusive. I'm not sure if the PS team got the inspiration from NuGet when designing this feature.

I don't agree with adding a confirmation prompt for interactive use as that would be a breaking change in my opinion and would change the cmdlet behavior when running interactive vs non-interactive. I am not aware of any cmdlets that change behavior when running interactive vs non-interactive excluding user interactive cmdlets like `Read-Host`. I also question the value of adding a verbose message to non-interactive.

**Comment by kilasuit** [comment]
Value of verbose or a debug message in non interactive is for troubleshooting CI/CD or other scripted scenarios.

Also I had on raising this issue envisioned on the addition of the confirmation prompt in a way to only show if Confirm was provided or ConfirmPreference is set , as to not _unintentionally_ break the current experience.

However it may make more sense that this is moved to a verbose/debug/information message as opposed to a continuation prompt due to PowerShell defaulting to High as a commandpreference value

**Comment by ThomasNieto** [comment]
I don't know if this sufficient for your desire verbose message but `Import-Module` currently writes out the module path which contains the version if the module was installed with PSGet.

```powershell
PS C:\Users\Thomas> Import-Module powershellget -Version 1.0 -Verbose
VERBOSE: Loading module from path 'C:\Users\Thomas\Documents\PowerShell\Modules\powershellget\3.0.19\powershellget.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Thomas\Documents\PowerShell\Modules\powershellget\3.0.19\PSGet.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module powershellget.
VERBOSE: Loading module from path 'C:\Users\Thomas\Documents\PowerShell\Modules\powershellget\3.0.19\netstandard2.0\PowerShellGet.dll'.
```
