### ISSUE TITLE
`Get-ChildItem` doesn't work with paths containing semicolons

### ISSUE THREAD

**Issue by aetonsi** [PowerShell/PowerShell#19434]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If i try to get a directory listing for something with a name containing a semicolon (which is **not** a [reserved character](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), and is supported by my underlying FS -NTFS-), nothing is found, unless i _glob_ it:
```
PS C:\Users\u6\OneDrive\Desktop > mkdir 'x;asd'

    Directory: C:\Users\u6\OneDrive\Desktop

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2023-03-31    12:45                x;asd

PS C:\Users\u6\OneDrive\Desktop > ls '.\x;asd\'
PS C:\Users\u6\OneDrive\Desktop > ls '.\x;asd'
PS C:\Users\u6\OneDrive\Desktop > ls 'x;asd'
PS C:\Users\u6\OneDrive\Desktop > ls 'x;asd\'
PS C:\Users\u6\OneDrive\Desktop > ls x*

    Directory: C:\Users\u6\OneDrive\Desktop

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          2023-03-31    12:45                x;asd
```

### Expected behavior

```console
any of the strings i've tried ('x;asd', 'x;asd\', etc) should return the same thing as the last one with the glob
```

### Actual behavior

```console
the expressions return $null
```

### Error details

```console
no errors
```

### Environment data

```powershell
( my version )
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


( required test version )
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by aetonsi** [comment]
Sidenote: `Remove-Item '.\x;asd\'` works without problems

**Comment by mklement0** [comment]
`Get-ChildItem` (`ls`), when given a _literal_ directory path, lists that directory's _entries_ (children).

Your newly created directory has no entries, so there's nothing to list.

By contrast, when you match a directory via a _wildcard_ (globbing), that directory _itself_ is listed (rather than its entries), which explains why `ls x*` produced output.

In short: I don't think there's a problem.

**Comment by mklement0** [comment]
P.S.: If you want to predictably target a directory _itself_ - whether by literal name or by wildcard - use `Get-Item` instead of `Get-ChildItem`.

**Comment by aetonsi** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️  Ohhh i see, you're totally right, my bad!
I even knew all of this.. I missed it because i was messing around with files **_and_** folders for hours and i didn't consider this difference.

Thanks and sorry for the mistake and disturbance, I'm closing the issue.
