### ISSUE TITLE
Add a `FilterText` property to `CompletionResult`

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PowerShell#19430]
### Summary of the new feature / enhancement

This is going to be a somewhat difficult to convey succinctly so bare with me.

Editors like VSCode optimize LSP calls to get intellisense by getting an initial set of results and then filtering on those results. By doing this they can reduce the amount of calls to roughly one call per *identifier* rather than one per *keystoke*.

For example:

1. You type `Get-C`
2. `C` marks a new identifier, so VSCode sends a completion request to the LSP
3. The LSP returns `Get-ChildItem` and `Get-Content`
4. You then type `o` making it `Get-Co`
5. VSCode looks at the filter text for `Get-ChildItem` and see it does not match. It narrows down the result to `Get-Content` without needing a second call to the LSP

This works great a lot of the time, but sometimes PowerShell returns results that make it difficult to determine what the `FilterText` should be.

Example:

1. You type `$PSHOME\System.Management`
2. VSCode sends a completion request
3. The LSP returns `'C:\Program Files\7-preview\System.Management.Automation.dll'`
4. If the vscode-powershell extension uses that completion result as-is as the `FilterText`, no results will show at all

Currently we hard code support for *some* of these scenarios, but as far as I know it is not possible to know generically. We can't reconstruct, simply based on the completion result, what part of the input was replaced. Or which parts aren't relevant, like the quotes.

The completion API would have this information already though, so it could be surfaced via an additional property on `CompletionResult`. Not for everything, custom argument completers would need to implement it themselves if needed, but a large chunk of the completions that do not currently work could be lit up.

### Proposed technical implementation details (optional)

```diff
namespace System.Management.Automation;

public class CompletionResult
{
+   private string? _filterText;

+   public string FilterText
+    {
+       get => _filterText ?? CompletionText;
+       set => _filterText = value;
+   }
}
```

(and then setting this in `CompletionCompleters` or similar where needed).

**Comment by andschwa** [comment]
This would be awesome.

**Comment by MartinGC94** [comment]
2 thoughts:
1: Have you looked at how ISE filters results?
If I type in `$env:windir\<Ctrl+Space>` and then type "System32" it seems to filter the results exactly like I would expect. Even more complicated scenarios work like you would expect. Example:

```
$Var1 = "Windows"
$Var2 = "WindowsPowerShell"
cd C:\$Var1\system32\$var2\v1.0\Modules\<Ctrl+space>
```
The only problem with the way ISE filters results is that it doesn't work with quotes, eg: "$env:windir\<Ctrl+Space>" doesn't filter anything when you type.

2: The tab completion shouldn't be replacing variables in the path completiontext in the first place. Of course this isn't the only scenario where output wildly differs from input but it's probably the only thing that is hard to handle. Other scenarios like wildcards in command names, or type completion have quite predictable results.

**Comment by SeeminglyScience** [comment]
> 2 thoughts: 1: Have you looked at how ISE filters results? 

I haven't but I imagine it just gets completion results every keystroke. I'll check though.

> Other scenarios like wildcards in command names, or type completion have quite predictable results.

For type completion, that's one of the scenarios we hard code and it's [more involved than you'd think](https://github.com/SeeminglyScience/PowerShellEditorServices/blob/f4548aa4fa4ca964007bfd428e353b7a8e4cb839/src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs#L394-L431). Not terrible, but not ideal.

For wildcards in command names, I'm not really sure how we would construct `FilterText` dynamically. It might be possible, but it's still one extra thing to hard code and the complexity is increasing.

Also keep in mind that `g-ci` now completes to `Get-ChildItem` which presents additional challenges. Ideally for that specifically we'd set the `FilterText` to the same as the input text, `g-ci`. (`g-cit` no longer matches for that completion, but we can handle that as well. The main part is having the inability to present the `g-ci` completion currently)

---

Some things can be hard coded, but even if we do that then there's no path to fixing custom completers that behave similarly
