### ISSUE TITLE
Need some way to overwrite the InvocationInfo for command errors in functions

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#19437]
### Summary of the new feature / enhancement

As a function author, I want to be able to report errors from underlying commands as if they came from my command.  
For example, if you have a function like this:
```
function MyCommand
{
    [CmdletBinding()]
    Param
    (
        [Parameter(Mandatory)]
        [string[]]
        $Path
    )
    Process
    {
        $ResolvedPath = Resolve-Path $Path
    }
}
```
and Resolve-Path writes an error it gets written like this:
```
PS C:\Users\Martin> MyCommand D
Resolve-Path:
Line |
  12 |          $ResolvedPath = Resolve-Path $Path
     |                          ~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\Martin\D' because it does not exist.
```
Whereas I would want it written like this:
```
PS C:\Users\Martin> MyCommand D
MyCommand: Cannot find path 'C:\Users\Martin\D' because it does not exist.
```

If you use: `$PSCmdlet.WriteError()` to write the error then it works exactly like I want but I'm missing a good way to catch the errors so I can rewrite them. I could use something like:
```
$ResolvedPath =try
{
    Resolve-Path $Path -ErrorAction Stop
}
catch
{
    $PSCmdlet.WriteError($_)
}
```
but then `Resolve-Path` would stop on the first error, instead of continuing to resolve the other paths.  
The closest I can get to a solution is like this:
```
$ResolvedPath = Resolve-Path -Path $Path -ErrorAction SilentlyContinue -ErrorVariable MyErrorVar
foreach ($Item in $MyErrorVar)
{
    $PSCmdlet.WriteError($Item)
}
```
And aside from it being inconvenient to use, it also delays the writing of errors until after `Resolve-Path` is finished so the end user can no longer end the command early on the first error with `-ErrorAction Stop`.

Note, there are times where you want it to report the internal invocationinfo data, for example when writing scripts that use `cmdletbinding` features or when debugging a module. For this reason we can't just change the current behavior, an option should be added so function authors can decide if errors should use the internal invocationinfo or not.

### Proposed technical implementation details (optional)

Maybe a common parameter could be added so commands could be run like this: `Resolve-Path $Path -UseParentInvocationInfoForErrors`.

**Comment by rhubarb-geek-nz** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.psdatastreams?view=powershellsdk-7.3.0

Can you redirect the output to various data streams while executing and then restore on exit?

**Comment by MartinGC94** [comment]
> Can you redirect the output to various data streams while executing and then restore on exit?

Sure, I could do something like this:

```
Resolve-Path $Path 2>&1 | ForEach-Object -Process {
    if ($_ -is [System.Management.Automation.ErrorRecord])
    {
        $PSCmdlet.WriteError($_)
    }
    else
    {
        $_
    }
}
```
and that works pretty well but it's not very convenient, it hurts the performance and could be problematic in edge cases where I want to pass an ErrorRecord through the pipeline.

**Comment by MartinGC94** [comment]
You are right that `ConciseView` presents this differently when you have an actual module file, but it's still not quite the same as `$pscmdlet.WriteError()`. It reports that the error came from the internal `Resolve-Path` command, instead of the command the user actually called, see:

```
PS C:\Users\Martin> Verb-Noun d
Resolve-Path: Cannot find path 'C:\Users\Martin\d' because it does not exist.
```

Also, if you change the `ErrorView` to `NormalView` then you get the same internal view of the module that you get without a module file.

**Comment by SeeminglyScience** [comment]
Note that I would caution against making any changes to default behavior (I know you're not asking for any @MartinGC94, just speaking generally). The current behavior is still very useful to distinguish between expected and unexpected errors. For a module of mine (and I've made this recommendation before) I will explicitly catch and `WriteError` (often with a custom message) any expected errors. Unexpected errors bubble up normally, showing the correct invocation info pointing to where the bug is.

Changing that would make troubleshooting unexpected error reports a lot harder.

---

A common parameter to control that doesn't 100% sit well with me primarily because you don't know yet if the error is actually expected without seeing it first. It would be nice to instead have a more fluent way to handle errors as they occur, ideally with a better way to wrap the resulting error record with a little bit less ceremony.
