### ISSUE TITLE
String comparison ignores NULL bytes

### ISSUE THREAD

**Issue by svhelden** [PowerShell/PowerShell#19438]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Two strings are considered identical even if one has a NULL bytes at the end while the other has not, and even their length is different.

### Expected behavior

```console
PS F:\> $a = "ABC"+[char]0
PS F:\> $b = "ABC"
PS F:\> $a.length
4
PS F:\> $b.length
3
PS F:\> $a -eq $b
False
```

### Actual behavior

```console
PS F:\> $a = "ABC"+[char]0
PS F:\> $b = "ABC"
PS F:\> $a.length
4
PS F:\> $b.length
3
PS F:\> $a -eq $b
True
```

### Environment data

```powershell
PS F:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
PowerShell is just the messenger here for .NET's behavior:

`$a -eq $b`

translates into

`[string]::Equals($a, $b, [System.StringComparison]::InvariantCultureIgnoreCase)`, which is `$true`

PowerShell's operators (mostly) use the _invariant_ culture, and this involves _linguistic_ string comparisons, where characters such as `NUL` (``"`0"``, `[char] 0`) are _ignored_.

---

To perform _ordinal_ comparison, i.e. comparison based on _code points only_, use

`[string]::Equals($a, $b, [System.StringComparison]::OrdinalIgnoreCase)`

**Comment by svhelden** [comment]
Thanks! 

In that case it's obviously not a bug in PowerShell, but probably an inaccuracy in documentation. That says:

_When the left-hand side is scalar, -eq returns True if the right-hand side is **an exact match**,_ 

Personally I'd not call two strings **an exact match** when they only identical from linguistic perspective. But anyway, at least it's now clear why it is like it is.

**Comment by mklement0** [comment]
Good point, @svhelden - I encourage you to crate an issue at https://github.com/MicrosoftDocs/PowerShell-Docs/issues
