### ISSUE TITLE
start-process with credentials leaks a process

### ISSUE THREAD

**Issue by jjsmeets** [PowerShell/PowerShell#19448]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Start-Process -credential $Credentials cmd
correctly start cmd-command prompt (as another user) but when that command prrompt is closed there remains another process running. Is name is OpenConsole.exe

This does not happen when no other credentials are specified.

### Expected behavior

```console
Only cmd.exe should be running as another user
```

### Actual behavior

```console
cmd.exe is running as another user
OpenConsole.exe is running as the current user
OpenConsole.exe is not terminated when cmd.exe is closed
```

### Environment data

```powershell
32;1mName                          [0m[32;1m Value[0m
[32;1m----                          [0m [32;1m-----[0m
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
WG-Security: The security group reviewed this and can see no security issue here.  This appears to be a `Start-Process` cmdlet bug to be investigated.
