### ISSUE TITLE
New-PSSession command is not accepting both -Authenticate Negotiate and -ComputerName ipv6_address  in redhat 

### ISSUE THREAD

**Issue by mdlokesh007** [PowerShell/PowerShell#19444]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Try New-PSSession with -ComputerName ipv6address .

### Expected behavior

```console
same command is working with ipv4 .
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/36881932/229509882-c60270dd-dbe7-4574-965d-67959c546ff6.png">

which is having issues over ipv6 address .
```

### Actual behavior

```console
When we dont give -Authenticate  , we are getting ACCESS_DENIED . 
When we give we are getting , INVALID_PARAMETER.  screenshot attached. . 
<img width="1161" alt="Screenshot at Apr 03 17-57-49" src="https://user-images.githubusercontent.com/36881932/229509547-648d4d4b-f224-4c16-87f1-c01c6a25814d.png">
```

### Environment data

```powershell
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Linux 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0\u2026}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mdlokesh007** [comment]
<img width="1161" alt="Screenshot at Apr 03 17-57-49" src="https://user-images.githubusercontent.com/36881932/229511262-36b408a0-ae47-4b58-b0e0-dba8fac4b9fc.png">

**Comment by mdlokesh007** [comment]
<img width="1412" alt="Screenshot at Apr 03 18-06-55" src="https://user-images.githubusercontent.com/36881932/229511455-2846b054-0c45-4cec-b217-a557557a93a6.png">

**Comment by SteveL-MSFT** [comment]
On Linux, PowerShell relies on https://github.com/microsoft/omi for WSMan remoting and that project no longer supports PowerShell.  We recommend moving to SSH based remoting: https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-7.3

**Comment by mdlokesh007** [comment]
there seems to be some confusion , we dont have omi rpm installed . 

[root@lokesh12 ~]# rpm -qa | grep omi
libatomic_ops-7.6.2-3.el8.x86_64
boost-atomic-1.66.0-10.el8.x86_64
[root@lokesh12 ~]# 
[root@lokesh12 ~]# 
[root@lokesh12 ~]# rpm -qa | grep powershell
powershell-preview-7.1.0_rc.2-1.centos.8.x86_64

let me add few more details ,
we are trying remoting from linux to windows machine . 

this looks like some validation of ipv6 address issue .  
When we add ipv6_Address to /etc/hosts file and if we give same hostname in computername parameter . its working . 


Examples :

Fail : 
New-PSSession -ComputerName 2001:420:54ff:4::415:11 -Authentication Negotiate -Credential admin


Success : 

(1) ipv6 address
vi /etc/hosts 
2001:420:54ff:4::415:11 ipv6_addr

New-PSSession -ComputerName  ipv6_addr -Authentication Negotiate -Credential admin

(2) ipv4 address
New-PSSession -ComputerName  10.77.123.98 -Authentication Negotiate -Credential admin


our ask is when we use ipv6 address , in computername param in above commad .. we are getting invalid_param error which needs to be fixed .
