### ISSUE TITLE
„Powershell 7.3.3“ crash

### ISSUE THREAD

**Issue by dziugas1959** [PowerShell/PowerShell#19443]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing problems with launching „Powershell 7.3+“ 
![paveikslas](https://user-images.githubusercontent.com/53124670/229384850-56fe5054-c716-4131-bb67-e8d80a3b7ed5.png)
Running „Powershell 7.2.10“ works perfect, but it displays to update, upon updating it crashes.
Running the installer for „Powershell 7.4 preview“ displays an installer error of it only supporting „Windows 8.1 and above“, meaning 7.3+ should be the last version, but I can't seem to get it running the way it should, I have a theory that it has something to do with .NET 7, but installing the framework for it did not seem to fix it. So it might be another issue.

### Expected behavior

```console
Program launches without errors
```

### Actual behavior

```console
Unhandled exception.
```

### Error details

```console
Provided in the image (since you can't copy on a crash)
```

### Environment data

```powershell
„Powershell 7.3.3“
```

### Visuals

![paveikslas](https://user-images.githubusercontent.com/53124670/229385048-a22dd3df-4058-44d0-8585-320be9e74740.png)

**Comment by jborean93** [comment]
Windows 7 is not supported on 7.3, see the [changelog](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-73?view=powershell-7.3#breaking-changes-and-improvements)

> In this release, Windows APIs were updated or removed for compliance, which means that PowerShell 7.3 doesn't run on Windows 7. While Windows 7 is no longer supported, previous builds could run on Windows 7.

The 7.4 preview does add a check in the installer which I think 7.3 should have but that doesn't change the fact that you are using an outdated OS which PowerShell/dotnet no longer supports.

**Comment by dziugas1959** [comment]
> Windows 7 is not supported on 7.3, see the [changelog](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-73?view=powershell-7.3#breaking-changes-and-improvements)
> 
> > In this release, Windows APIs were updated or removed for compliance, which means that PowerShell 7.3 doesn't run on Windows 7. While Windows 7 is no longer supported, previous builds could run on Windows 7.
> 
> The 7.4 preview does add a check in the installer which I think 7.3 should have but that doesn't change the fact that you are using an outdated OS which PowerShell/dotnet no longer supports.

The problem is, that it does support it, the only version that it does not support is .NET 8+
If there really is an dependency that is broken by it being „Windows 7“, then they should release „Powershell 7.3.11“ disabling the „Update available click to download“ prompt. 
![paveikslas](https://user-images.githubusercontent.com/53124670/229516516-365464f8-423b-4802-bc0b-fa7012d60039.png)

**Comment by dziugas1959** [comment]
Not mentioning that it hooks itself to „Windows update“ if you select the option, meaning it should work by all means.

**Comment by SteveL-MSFT** [comment]
cc @TravisEz13

**Comment by TravisEz13** [comment]
PowerShell has more dependencies than .NET and some of those dependencies no longer support .NET.

**Comment by dziugas1959** [comment]
> PowerShell has more dependencies than .NET and some of those dependencies no longer supported on Windows 7 as it is out of support itself.

In any case, the issue remains that „Powershell 7.2.10“ keeps nagging about updating to a newer version and the newer version doesn't have a check for compatibility. 
.11 release would probably be needed.

**Comment by kilasuit** [comment]
@dziugas1959 - you can set the Environment Variable `POWERSHELL_UPDATECHECK` to `0` as per [about_update_notifications](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.4) to turn off the update notifications

**Comment by dziugas1959** [comment]
> @dziugas1959 - you can set the Environment Variable `POWERSHELL_UPDATECHECK` to `0` as per [about_update_notifications](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.4) to turn off the update notifications

Until a finalized version of 7.2.X comes out, this will be the temporary solution.

**Comment by dziugas1959** [comment]
Sadly, I don't see how to apply a closed until further notice button. this will have to do.

**Comment by Temik007** [comment]
Solution - https://github.com/PowerShell/PowerShell/issues/19816
