### ISSUE TITLE
PowerShell doesn't set current working directory correctly

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#19446]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Writing a binary module I noticed that the current working directory isn't set correctly on Windows.

`[System.Environment]::CurrentDirectory` always returns `C:\Windows\system32`, no matter what.

### Expected behavior

```console
PS> Set-Location 'C:\Temp'
PS> [System.Environment]::CurrentDirectory
C:\Temp
```

### Actual behavior

```console
PS> Set-Location 'C:\Temp'
PS> [System.Environment]::CurrentDirectory
C:\Windows\system32
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PowerShell CWD error](https://user-images.githubusercontent.com/9283914/229575723-6572b64b-741c-4bb7-946d-09aa8d070b35.png)

**Comment by rhubarb-geek-nz** [comment]
> Then how is a binary module supposed to retrieve the current working directory?

What kind of binary module? 

Let's say that it should not assume, and should be given the directory to use as current directory as a parameter if it is to be a good PowerShell citizen.

**Comment by mklement0** [comment]
Related:

* #3428 (original issue, explains the design rational that @rhubarb-geek-nz has summarized)
* #17149 (follow-up issue, debatable plan to make the _main_ thread only sync with the process-wide working dir.

> Then how is a binary module supposed to retrieve the current working directory?

Derive your binary cmdlet from `PSCmdlet`, which gives you access to the PowerShell session state.

A simple (contrived) PowerShell example (the script block with `[CmdletBinding()]` exposes `$PSCmdlet`, which gives you access to the base-class members):

```powershell
& { [CmdletBinding()] param() $PSCmdlet.SessionState.PSVariable.Get("PWD") }
```

**Comment by jborean93** [comment]
I've always found the answer on this SO post to be quite helpful in trying to reimplement the `Path` and `LiteralPath` parameter set in binary cmdlets https://stackoverflow.com/questions/8505294/how-do-i-deal-with-paths-when-writing-a-powershell-cmdlet. It shows you how you can expand the paths given from a relative/glob-like string to the absolute path on the filesystem. I even create a base class in which my cmdlets inherit from which include a helper function to convert the 2 path parameters into a single array of resolved paths https://github.com/jborean93/PowerShell-OpenAuthenticode/blob/11e21d87d59e75d8d7967ebe7a371347540f1d83/src/OpenAuthenticode/OpenAuthenticodeSignature.cs#L25-L61.

**Comment by ThomasNieto** [comment]
The easiest way I've found for a binary cmdlet to get the current working directory is:

```csharp
this.SessionState.Path.CurrentFileSystemLocation.Path;
```

https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.pathintrinsics.currentfilesystemlocation?view=powershellsdk-7.2.0#system-management-automation-pathintrinsics-currentfilesystemlocation

**Comment by SetTrend** [comment]
@rhubarb-geek-nz:

I'm providing something similar to a `Move-Item` Cmdlet. It's provided by the user with a relative path to handle. So, that's intrinsic functionality to the binary module.

@mklement0:

I would have expected an expression like `MyInvocation.PSScriptRoot` to be successful, but to no avail.

I couldn't find a way to create unit test session in Visual Studio 2022 that's calling a binary module's Cmdlet, allowing me to debug into the Cmdlet code by debugging the unit test. So, I'm not able to examine any session state variable in my binary module.

@ThomasNieto:

Marvellous! Great solution! Thanks!!! 👍👍👍

<br/>

Nonetheless, I believe it would be less awkward and opaque if the first thread running when the Shell is launched was to immediately call something like `[System.Environment]::CurrentDirectory = this.SessionState.Path.CurrentFileSystemLocation.Path;`

**Comment by mklement0** [comment]
Good point, @ThomasNieto - that's the best solution. Worth adding that if you want a _native_ file-system path (rather than one potentially based on a PS-only drive), use `this.SessionState.Path.CurrentFileSystemLocation.ProviderPath`;
(And if you want the current location even if it isn't a _file-system_ location, use `this.SessionState.Path.CurrentLocation`)

**Comment by mklement0** [comment]
@SetTrend 

> I would have expected an expression like `MyInvocation.PSScriptRoot`

That gives you the directory in which the calling script happens to be located.

> I believe it would be less awkward and opaque if the first thread running when the Shell is launched was to immediately call something like `[System.Environment]::CurrentDirectory = this.SessionState.Path.CurrentFileSystemLocation.Path;`.

That's the subject of https://github.com/PowerShell/PowerShell/issues/17149, but it presents its own challenges, as code then behaving differently depending on whether it runs on the main thread or not is obscure too.

> I propose to have the CWD being thread local, being initialized on thread start by the creating process.

That's not possible, unfortunately, because at the _process_ level there can only be _one_ working directory.

PowerShell in essence already has thread-local working directories, but it is a PowerShell-specific concept that only native PowerShell commands know of and honor.

It is therefore a problem for all _in-process_ calls to _non-PowerShell_ code, notably when calling .NET APIs with relative paths.

**Comment by SetTrend** [comment]
Thanks for clarifying, @mklement0.

Yet, isn't this a comon issue with all kinds of programs? I remember writing multi threaded code for decades, and it's been an ongoing challenge to not alter non thread-safe properties accidentally and to cache non thread-safe properties in a thread once read. So, does it make sense to bother here when basically no other platform does?

**Comment by mklement0** [comment]
>  So, does it make sense to bother here when basically no other platform does?

I'm afraid I don't understand the question.

Note that PowerShell is unusual in that is both a shell and a sophisticated automation framework that in effect allows _multiple_ shell sessions in a single process.

In a shell, the current working directory is an important concept, so any given PowerShell thread (runspace) in a given process must be able to use and modify it, without affecting other threads.

**Comment by rhubarb-geek-nz** [comment]
> Yet, isn't this a common issue with all kinds of programs? ... .So, does it make sense to bother here when basically no other platform does?

Absolutely it does, the reason is that PowerShell is attempting to provide a reliable multithreaded programming environment. If it is a well-known problem that process wide current working directory does not work well with threads then it means it should not be part of a reliable multithreaded programming environment.

With references to Raymond.

https://devblogs.microsoft.com/oldnewthing/20210816-00/?p=105562 from 2021

https://devblogs.microsoft.com/oldnewthing/20101109-00/?p=12323 from 2010

**Comment by mklement0** [comment]
Good links, @rhubarb-geek-nz, but just to be clear: 

Avoiding per-thread working directories is _not_ an option in PowerShell - nor is it _desirable_.

**Comment by fededim** [comment]
You can add as first script line this

`[System.Environment]::CurrentDirectory = (Get-Location)
`
