### ISSUE TITLE
Native command args with colon being incorrectly split

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#19451]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

cargo clippy -- -Dclippy::pedantic

### Expected behavior

```console
Rust clippy runs
```

### Actual behavior

```console
error: multiple input filenames provided (first two filenames are `src\main.rs` and `:pedantic`)
```

### Error details

```console
It seems that PowerShell parser is treating `-Dclippy::pedantic` as two arguments.  PSReadLine rendering of the AST shows that `-Dclippy:` and `:pedantic` as two arguments.

Related, but not exactly the same: https://github.com/PowerShell/PowerShell/issues/16432
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.25324
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The issue is specific to  `--` preceding the `-`-prefixed arguments that also contain `:`

On a meta note, @SteveL-MSFT: consider changing the issue template to not enclose the content of the `Expected behavior` and `Actual behavior` in code blocks - it frequently leads to unintended, distracting formatting.
