### ISSUE TITLE
Port 5985 isn't listenning although winrm service is running

### ISSUE THREAD

**Issue by tsukiazuma** [PowerShell/PowerShell#19453]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I try enable winrm services:
1. Enable with command line:
```
psexec $computername -h -d powershell.exe -Command "Set-Service -Name WinRM -StartupType Automatic; Start-Service -Name WinRM"
```
2. Check winrm services with:
```
Test-WSMan
```
winrm services have run but port 5985 still is not listenning.

### Expected behavior

```console
winrm and port 5985 are enable
```

### Actual behavior

```console
winrm is enable, but port 5985 is not listenning.
```

### Error details

```console
No response
```

### Environment data

```powershell
Powershell v5.1 on Windows Server 2012 R2
```

### Visuals

![image](https://user-images.githubusercontent.com/75791054/229975650-0efbb2bd-c5be-4cd7-8cf2-d6b68616724e.png)
![image](https://user-images.githubusercontent.com/75791054/229975744-443a8c73-a729-48c9-bdae-9cf2d4cccfb9.png)

**Comment by jborean93** [comment]
Starting the service isn't the only thing that needs to be done. There needs to be a configured winrm listener (`winrm enumerate winrm/config/listener`) for that port.

Typically you configure WinRM by doing `winrm quickconfig` or if you want WinRM + the PSRemoting side use `Enable-PSRemoting`.

In any case, WinRM is something external to PowerShell so this isn't the right repo to ask about it.

**Comment by tsukiazuma** [comment]
> Starting the service isn't the only thing that needs to be done. There needs to be a configured winrm listener (`winrm enumerate winrm/config/listener`) for that port.
> 
> Typically you configure WinRM by doing `winrm quickconfig` or if you want WinRM + the PSRemoting side use `Enable-PSRemoting`.
> 
> In any case, WinRM is something external to PowerShell so this isn't the right repo to ask about it.

Thank you for your advice.
I use default config for winrm, so service should run on port 9585 and 5986.
And can you give some repo more suitable ?

**Comment by kasini3000** [comment]
check firewall on win2012：
Enable-PSRemoting -SkipNetworkProfileCheck -Force
Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP-NoScope" -RemoteAddress Any
Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP" -RemoteAddress Any

trust server on client pc：
Set-Item WSMan:\localhost\Client\TrustedHosts  -Value '*'

then  Restart-Service WinRM

**Comment by tsukiazuma** [comment]
> check firewall on win2012： Enable-PSRemoting -SkipNetworkProfileCheck -Force Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP-NoScope" -RemoteAddress Any Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP" -RemoteAddress Any
> 
> trust server on client pc： Set-Item WSMan:\localhost\Client\TrustedHosts -Value '*'
> 
> then Restart-Service WinRM

I don't think it is problem from server. Because, I can run command on server, but port isn't listening on client.

Thank you for your advice, I will try it and response.

**Comment by tsukiazuma** [comment]
> check firewall on win2012： Enable-PSRemoting -SkipNetworkProfileCheck -Force Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP-NoScope" -RemoteAddress Any Set-NetFirewallRule -Name "WINRM-HTTP-In-TCP" -RemoteAddress Any
> 
> trust server on client pc： Set-Item WSMan:\localhost\Client\TrustedHosts -Value '*'
> 
> then Restart-Service WinRM

Hi, I tried enable inbound FW but nothing changes. I disabled inbound FW on uat, but winRM can workUntitled

![Untitled](https://user-images.githubusercontent.com/75791054/230257455-dbc37d7b-044d-43b8-a3d5-4fa2aed1cb39.png)

Port 5985 can listen on client when I run: presec $computername -h -d powershell.exe -Command "Set-Service -Name WinRM -StartupType Automatic; Start-Service -Name WinRM" But in live enviroment, port 5985 can't listenning on client.
