### ISSUE TITLE
Native globbing on macOS is broken with respect to wildcard `*` in isolation

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19457]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On macOS - but seemingly _not_ on Linux - native globbing with `*` is broken (but works with `*.txt`, for instance):

```powershell
# Note: Run on macOS
/bin/echo *
```

### Expected behavior

Should print a list of file and directory names in the current directory.

### Actual behavior

```console
*
```

That is, no globbing occurred.

### Environment data

```powershell
PowerShell 7.3.3 on macOS 13
PowerShell 7.4.0-preview.2 on macOS 13
```

**Comment by MartinGC94** [comment]
Works fine for me in WSL (Ubuntu 20.04.5 LTS).

**Comment by mklement0** [comment]
Thanks, @MartinGC94 - indeed it seems to affect macOS only (and there it also affects 7.3.3)  - I've updated the title and the initial post.

**Comment by jrdodds** [comment]
With PowerShell 7.3.3 on macOS 12, I can't reproduce this. 

```
/bin/echo *
```

produces a list of file and directory names as expected.

**Comment by mklement0** [comment]
Thank you all for verifying that it isn't a general problem.

My bad: I jumped to conclusions: it wasn't about the OS per se.

The presence of a file literally named `foo\bar` quietly breaks native globbing with `*` 

Closing this in favor of #19460
