### ISSUE TITLE
NFS home directory not accessible

### ISSUE THREAD

**Issue by MathiasMagnus** [PowerShell/PowerShell#1946]
When I try to use PS on a remote Linux node which has it's home mounted via NFS, it fails to create the ConsoleHost_history.txt file.
## Steps to reproduce

export a directory with server settings:
`*(rw,no_root_squash,async,no_subtree_check)`

mount it on a client with settings:
`nfs rsize=8192,wsize=8192,timeo=14,intr`
## Expected behavior

`AMDAPPSDK.conf  Build    Downloads  Mate.zip   alice.tgz  Develop  Git   PP_TRandom5_GPU_500000.zip create_users.sh`
## Actual behavior

```
ls
Error reading or writing history file '/home/mnagy/.local/share/powershell/PSReadLine/ConsoleHost_history.txt': Access to the path '/home/mnagy/.local/share/powershell/PSReadLine/ConsoleHost_history.txt' is denied.
AMDAPPSDK.conf  Build    Downloads  Mate.zip   alice.tgz  Develop  Git   PP_TRandom5_GPU_500000.zip   create_users.sh
```
## Environment data

UID/GID of user that launched the PowerShell session remotely (user mnagy) is the same on both the NFS server and the client. The client also uses libnss-extrausers that loads clusterwide user info from an NFS store, but because it is a built-in authentication extension, the origin of this user data should remain invisible to consuming code, so long as they resort to correct auth methods. (I have no idea how to do it exactly, but all Linux utils automagically work.)

`````` powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1```
``````

**Comment by alexp789** [comment]
I just wanted to add that I'm also experiencing this issue.  I've tested both without SELinux enabled (to rule this out) and also after opening up the permissions on the ConsoleHost_history.txt, neither of which helped.

**Comment by joeyaiello** [comment]
It's unclear to me the implications of this. We should discuss it when we triage the Linux/Mac Usability project.

**Comment by MathiasMagnus** [comment]
This issue has been resolved by one of the updates. At least on current beta-1 builds it's no longer an issue (and has been for the past 5-6 builds or so).

The only problem now is that the console is pretty much useless when used over SSH. After pressing every key, it prints the content of the line thus far in a new line, but this is a separate issue. Happens both with PowerShell/Open-SSH and the one that ships with Git for Windows. (In slightly different ways)
```Powershell
PS /home/mnagy> PS /home/mnagy> g
                PS /home/mnagy> gc
                PS /home/mnagy> gci
```

**Comment by joeyaiello** [comment]
Yeah, we're tracking a whole host of SSH-related issues. Glad this one got fixed, though.
