### ISSUE TITLE
`Format-Table` of a `[pscustomobject]` containing decimal number, always prints 2 digits

### ISSUE THREAD

**Issue by aetonsi** [PowerShell/PowerShell#19463]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

hi
i created a small utility that returns a `[pscustomobject]@{...}`.
One of its properties is a `[double]` without decimals.
I discovered that when i print it with `| format-list` i get it without decimal part, while `| ft` always prints 2 decimals, whether the number actually has more or less decimals. This means that for numbers like `1.458789`, it prints `1.46`, and for `2` it prints `2.00`.
`Format-List` on the other hand always prints decimals up until the last one.

### Expected behavior

```console
PS> ([pscustomobject]@{x=[double]2; y=1.456789}) | ft

x         y
-         -
2  1.456789
```

### Actual behavior

```console
PS> ([pscustomobject]@{x=[double]2; y=1.456789}) | ft

   x    y
   -    -
2.00 1.46
```

### Error details

```console
NA
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/18366087/230598347-0b00d25c-25f6-4717-a555-468ebbd90875.png)

**Comment by doctordns** [comment]
I can not repo this. Here ix what I see:

```powershell
PS C:\Foo> $PSVersionTable.PSVersion
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      0      preview.2

PS C:\Foo> [pscustomobject]@{x=[double]2; y=1.323232; z= [double] 43.4343344} | fl

x : 2
y : 1.323232
z : 43.4343344
```

**Comment by crlogic** [comment]
> I can not repo this

Try `Format-Table` ;)

```
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2673


PS C:\> [pscustomobject]@{x=[double]2; y=1.323232; z= [double] 43.4343344} | Format-Table

x        y          z
-        -          -
2 1.323232 43.4343344


PS C:\> pwsh
PowerShell 7.4.0-preview.2
[0]ms C:\> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      0      preview.2

[20.09]ms C:\> [pscustomobject]@{x=[double]2; y=1.323232; z= [double] 43.4343344} | Format-Table

   x    y     z
   -    -     -
2.00 1.32 43.43

[132.72]ms C:\>
```

**Comment by CarloToso** [comment]
Duplicate of https://github.com/PowerShell/PowerShell/issues/18492

**Comment by mklement0** [comment]
Also:
 * [detailed discussion] #19107
 * #19139

**Comment by aetonsi** [comment]
guys i'm incredibly sorry i have no idea how i missed those 😔.. also, in the meantime i had already found the "solution" of casting to string to get the number of decimals desired. so i'm closing the issue
