### ISSUE TITLE
macOS: Using the clear-screen-and-reset-scrollback-buffer keyboard shortcut makes PowerShell misplace user input

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19479]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is the same symptom that has been reported for `PSReadLine`  in:
 * https://github.com/PowerShell/PSReadLine/issues/841

However, at least on macOS (don't know about Linux), the same problem also occurs with `PSReadLine` _unloaded_, suggesting that PowerShell itself is affected too  (whereas on _Windows_ the problem only occurs with `PSReadLine` loaded).

* Open a terminal window and run PowerShell, or use VSCode's integrated terminal with a _general-purpose_ PowerShell session (do not use the PIC, where `PSReadLine` cannot be unloaded).
* Run `Remove-Module PSReadLine` to rule out `PSReadLine` as the source of the problem.
* Run `1..200` to fill the screen and create content for the scrollback buffer.
* Press <kbd>Command-K</kbd> to clear the screen and the scrollback buffer.

### Expected behavior

Subsequent user input should show on the first line of the newly cleared screen.

### Actual behavior

Except for the first character typed, subsequent user input appears on the line where the cursor was _before_ the screen was cleared.

### Environment data

```powershell
PowerShell Core 7.4.0-preview.2 on macOS, in both Terminal.app and iTerm2.app
```

**Comment by StevenBucher98** [comment]
Able to reproduce with 7.3.4 with both Terminal and iTerm2

**Comment by elise1993** [comment]
Just encountered this issue for powershell in VScode (version info below). Clearing the terminal works fine outside of VScode (same version), but not within VScode. If I switch to cmd in VScode, there's no issue.


PSVersion                      5.1.26100.2161
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.26100.2161
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

![Image](https://github.com/user-attachments/assets/56e6cf5a-34e5-4a31-87ed-0d34b57ab707)

**Comment by pypimo** [comment]
I am facing the same issue as above
Dont know why this issue is closed - its definitely not resolved
