### ISSUE TITLE
Press tab in pwsh to complete  but  get stuck

### ISSUE THREAD

**Issue by oison111** [PowerShell/PowerShell#19476]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- this is my $profile

Import-Module PSReadLine
#Set-PSReadLineOption -EditMode Emacs     
Set-PSReadlineKeyHandler -Key Tab -Function Complete
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward

### Expected behavior

```console
...
```

### Actual behavior

```console
...
```

### Environment data

```powershell
Administrator in ~
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
@oison111 can you provide some more details about what version of PSReadLine are you running? I am unable to reproduce this with given steps and PSReadLine 2.3.0-beta.0

**Comment by oison111** [comment]
@StevenBucher98 

PowerShell 7.3.3
Loading personal and system profiles took 3939ms.
Administrator in ~
❯ Get-InstalledModule -Name PSReadLine

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.2.6                PSReadLine                          PSGallery            Great command line editing in the PowerS…

**Comment by oison111** [comment]
resolved

**Comment by StevenBucher98** [comment]
@oison111  How did you resolve it? or what was the issue causing this?

**Comment by oison111** [comment]
> @oison111 How did you resolve it? or what was the issue causing this?

@StevenBucher98 
i have some configuration about pip in my $profile, i deleted it , and then it's ok
