### ISSUE TITLE
The path that `$PROFILE` refers to does not exist.

### ISSUE THREAD

**Issue by ryuujo1573** [PowerShell/PowerShell#19475]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [ ] Search the existing issues.
- [ ] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [ ] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using
```ps1
python -m pip completion --powershell | Out-File -Encoding default -Append $PROFILE
```
it output:
> Out-File: Could not find a part of the path 'C:\Users\______\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'.

The cause of the issue is that `~\Documents\PowerShell` directory does not exist.
It is strange for a built-in variable `$profile` to be unavailable.

### Expected behavior

```console
Create the folder to `$profile` when fresh installations / updates.
```

### Actual behavior

```console
It isn't created.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
> ### Expected behavior
> ```
> Create the folder to `$profile` when fresh installations / updates.
> ```

One problem with that solution is that if PowerShell is installed from an MSI it is a system wide installation where as the profile is per user.

**Comment by ryuujo1573** [comment]
> 

Thanks for the reply.

I did not mean for any specific path, and whatever it goes, the path should always be available.

**Comment by rhubarb-geek-nz** [comment]
[about_Profiles](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3)

The specification for the variable does not promise that the file will already exist, their examples show testing to see if the file exists first then using `New-Item`.

Eg

```
if (!(Test-Path -Path $PROFILE)) {
  New-Item -ItemType File -Path $PROFILE -Force
}
```

I read that as `$PROFILE` variable indicates where PowerShell will look for the profile and not having a profile is completely valid.

**Comment by ryuujo1573** [comment]
Learned today! Thank you for your reply.
