### ISSUE TITLE
Make TypeAccelerators public

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#19488]
### Summary of the new feature / enhancement

As a user I want to be able to define my own TypeAccelerators to allow shorter names of long types in my scripts.

### Proposed technical implementation details (optional)

There are quite a few blog posts out there that show how access the `TypeAccelerators` class through reflection as it is currently an `internal` scoped class:

+ https://4sysops.com/archives/using-powershell-type-accelerators/
+ https://powershellmagazine.com/2012/04/27/a-day-in-the-life-of-a-poshoholic-creating-and-using-type-accelerators-and-namespaces-the-easy-way/
+ https://adamtheautomator.com/powershell-data-types/
+ https://learn-powershell.net/2013/10/10/quick-hits-finding-creating-and-removing-powershell-type-accelerators/
+ I could keep on going

The fact that the reflection method is so pervasive has made an internal API into something that is somewhat part of the stable interface. I propose making the class `public` as well as a type accelerator itself to make it easier for people to define their own type accelerators. The docs and class structure even seems to indicate that this is meant to be a public API with lines such as [this](https://github.com/PowerShell/PowerShell/blob/9d036c4876fb078d09002eca66bf6fc7ecd9aab0/src/System.Management.Automation/engine/parser/TypeResolver.cs#L849-L851).  There is a tentative PR for this at https://github.com/PowerShell/PowerShell/pull/19481.

Unfortunately due to the caching of types the PR had to remove the caching if the value was a type accelerator which could have a performance impact. It's worth having a conversation as to whether we need type accelerators for types that are in the `System` namespace as they are already accessible directly due to the implicit `using namespace System` that pwsh has during the type lookup.

**Comment by kilasuit** [comment]
I would like to see this made public especially as it seems that there was design scope to allow it when it was originally implemented

**Comment by jborean93** [comment]
That does sound like a better solution, this issue and PR was mostly just a way to get closure on the whole TypeAccelerator and why it isn't public. If that's the direction that the pwsh team want to move towards I'll be happy with that.

**Comment by vexx32** [comment]
WG-Engine discussed this today. 

We think that the design of this API currently is not sufficient for it to be a public API. There are thread-safety concerns and general usability concerns about the current form of this code. We do however think it could be quite useful to add some cmdlets to expose a more complete interface to interact with it, although we would require some safeguards to be added around the internal backing storage used here to make that work.

@JamesWTruher is looking at some initial exploratory work stubbing out what this might look like. Given the API they'll need to interact with will remain internal, the cmdlets will likely have to be builtins.

We agree there is some potential overlap with the `using type =` syntax, but feel the use cases are sufficiently different enough that there is likely space for both to exist and complement each other.
