### ISSUE TITLE
Support for Azure Quantum 

### ISSUE THREAD

**Issue by Bradben** [PowerShell/PowerShell#19492]
### Summary of the new feature / enhancement

Are there plans to support or add cmdlets for the Azure Quantum service? I can get back a quantum.workspace object, but only the generic properties - none of the specific properties that let me create or edit a quantum.workspace resource.

**Comment by rhubarb-geek-nz** [comment]
Is this an issue for [Azure/azure-powershell](https://github.com/Azure/azure-powershell) rather than the core PowerShell?

**Comment by Bradben** [comment]
Thanks, I will move it over there.
