### ISSUE TITLE
Tab-completion doesn't honor the provider context provided by a previous argument when surfacing dynamic parameters

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19498]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
Push-Location function:  # change to a non-file-system location
(TabExpansion2 'Get-ChildItem -LiteralPath $PSHOME -Fi').CompletionMatches.ListItemText
Pop-Location
```

### Expected behavior

```console
Filter
File
```

### Actual behavior

```console
Filter
```

That is, even though the file-system provider is implied by the `-LiteralPath` argument, tab-completing `-Fi` didn't surface the dynamic `-File` parameter.

### Environment data

```powershell
PowerShell Core 7.4.0-preview.2 (behavior dates back to Windows PowerShell)
```

**Comment by MartinGC94** [comment]
This is only a problem with partial input. If you write: `Get-ChildItem -LiteralPath $PSHOME -<Tab>` it shows the filesystem parameters as you would expect. I think I know where the problem is, and will take a look later today.
