### ISSUE TITLE
start-job failing

### ISSUE THREAD

**Issue by eric-jesover** [PowerShell/PowerShell#1949]
version 6.0.0.9

Steps to reproduce
------------------
start-job -Name "Testing" -ScriptBlock {get-process}
receive-job -id xxx

Expected behavior
-----------------
le process list

Actual behavior
---------------
[localhost] The background process reported an error with the following message: -Version : The term '-Version' is not
recognized as the name of a cmdlet, function, script file, or operable program. .
+ CategoryInfo : OpenError: (localhost:String) [], PSRemotingTransportException
+ FullyQualifiedErrorId : 2100,PSSessionStateBroken

this working correctly on 5.1.14393.0 on windows 10

Environment data
----------------
windows 10

Name                           Value
----                           -----
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.9
PSRemotingProtocolVersion      2.3
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
SerializationVersion           1.1.0.1
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0

**Comment by kort3x** [comment]
This is a well known issue: The background job cmdlets are available and work with the important exception of Start-Job.
https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md

**Comment by eric-jesover** [comment]
thanks
