### ISSUE TITLE
Add 'tail' and 'head' to Map Book for Experienced Bash users

### ISSUE THREAD

**Issue by bobthomson70** [PowerShell/PowerShell#1950]
tail -f ./filename maps to Get-Content -Path .\filename -Wait in Powershell

tail -X ./filename maps to Get-Content -Path ,\filename -Tail X in Powershell

head -X ./filename maps to Get-Content -Path ,\filename -Head X in Powershell

Could also add 'more' and point it out it's much the same and is the equivalent of 'less' also.

I appreciate these are not actually bash commands but coming from Linux these are ones that I immediately searched for on starting with Powershell.

**Comment by szollo** [comment]
Hey @bobthomson70,

Which platform are you running this on? I have tried both OSX and a CentOS Docker container, and neither maps to Get-Content.

```
PS /> uname -a
Linux 9607d7d659fb 4.4.16-moby #1 SMP Tue Aug 9 17:20:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
PS /> get-alias tail
get-alias : This command cannot find a matching alias because an alias with the name 'tail' does not exist.
At line:1 char:1
+ get-alias tail
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (tail:String) [Get-Alias], ItemNotFoundException
    + FullyQualifiedErrorId : ItemNotFoundException,Microsoft.PowerShell.Commands.GetAliasCommand
```
```
PS /Users/Stevie> uname -a
Darwin repeatable 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
PS /Users/Stevie> get-alias tail
get-alias : This command cannot find a matching alias because an alias with the name 'tail' does not exist.
At line:1 char:1
+ get-alias tail
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (tail:String) [Get-Alias], ItemNotFoundException
    + FullyQualifiedErrorId : ItemNotFoundException,Microsoft.PowerShell.Commands.GetAliasCommand
```

Cheers
Stevie

**Comment by bobthomson70** [comment]
Hi Stevie, I didn't word this very well, my bad, I was suggesting an update to the 'learning-powershell' doc which lists common bash to Powershell mappings - 

https://github.com/PowerShell/PowerShell/tree/master/docs/learning-powershell

Although head and tail are not built into bash, I think, people like me who are used to *NIX and start to try to make use of Powershell as a shell on Wintel will wonder what the equivalents are for these.

Another such example that springs to mind is 'ls -lrt'

**Comment by SteveL-MSFT** [comment]
@bobthomson70 perhaps you could submit a PR on the proposed doc change?

**Comment by joeyaiello** [comment]
I'll try to do this this week.

**Comment by ThomasNieto** [comment]
@sdwheeler what do you think of this issue? Can it be closed?

**Comment by sdwheeler** [comment]
The documentation cited in https://github.com/PowerShell/PowerShell/issues/1950#issuecomment-241056582 has been moved into the official documentation or retired.

For information about the PowerShell aliases on Linux, see https://learn.microsoft.com/en-us/powershell/scripting/whats-new/unix-support?view=powershell-7.3#aliases-not-available-on-linux-or-macos.
