### ISSUE TITLE
[enum]-typed parameters inappropriately accept *multiple* values even for non-[Flags]-decorated enumeration types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19513]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
enum SomeEnum {one; two; three}

& { param([SomeEnum] $someEnumVal) $someEnumVal } -SomeEnum one, two
```

Note:
* I've since realized that the behavior isn't restricted to _parameters_, and that something like `[SomeEnum] 'one, two'` and `[SomeEnum] ('one', 'two')` unexpectedly work as well - the former is supported by .NET itself (`[Enum]::Parse[SomeEnum]('one, two')`, the latter is PowerShell-specific.

### Expected behavior

Since the `[enum]`-derived type isn't decorated with `[Flags()]` and is therefore not a _bit field_, the parameter binder should permit passing only _one_ value.

### Actual behavior

```console
two
```

That is, multiple values are invariably accepted, numerically bit-ORed, and then interpreted as a single `[SomEnum]` value. 

That is, it exhibits behavior that is only appropriate for `[Flags()]`-decorated enumeration types.

### Environment data

```powershell
PowerShell Core 7.4.0-preview.2
```

**Comment by 237dmitry** [comment]
I think that the definition of parameter expected single argument

```powershell
enum SomeEnum {one; two; three}

& { param([SomeEnum[]] $someEnumVal) $someEnumVal } -SomeEnum one, two, three    # 0,1,2
```

**Comment by mklement0** [comment]
Indeed, @237dmitry, but that is the very point: 

* The parameter is a _scalar_ (non-array).
* Yet, PowerShell allows you to pass an _array_ of values to it.
  * This is only appropriate for `[Flags]`-decorated enumeration-based types (whose values are bit flags that can be _combined_), yet PowerShell currently permits it for _any_ such type.
