### ISSUE TITLE
Installed from MS Store, prompted to update to version that is not available in MS Store

### ISSUE THREAD

**Issue by fredemmott** [PowerShell/PowerShell#19520]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- install latest powershell from ms store

### Expected behavior

```console
- ms store should have the latest version
- ms store builds should not show update prompts for versions that are not available on the ms store
- if ms store is no longer supported for powershell, that should be made clear in the release notes and on the MS store page
```

### Actual behavior

```console
1. get 'out of date, update now' message
2. check MS store for updates
3. no updates available even when checking 'get updates'
```

### Environment data

```powershell
PS C:\Users\fred> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

```
PowerShell 7.3.3

   A new PowerShell stable release is available: v7.3.4
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.3.4

PS C:\Users\fred> winget update powershell
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.
```

**Comment by jhoneill** [comment]
The store always lags behind the release by a few days. There are already issues opened with ideas around changing the way the "update now" message is pushed, so people who deployed via the store aren't told to update until it is ready.

**Comment by eduarddejong** [comment]
Note that this also applies to the PowerShell extension in Visual Studio Code, which shows you the exact same message.
Automatic detection that you already have the latest release from the Microsoft Store, but just not from Github, followed by a message which is more specific and a tiny little bit less invasive than the current one, would be helpful.
Especially when the version number difference is so small or when no security related bugfix is involved.

**Comment by StevenBucher98** [comment]
Store should be updated now with 7.3.4, thank you for your patience.

**Comment by fredemmott** [comment]
Is this actually fixed, or will it reoccur with the next update?

**Comment by StevenBucher98** [comment]
We manually publish to the store and the one person with access was on vacation until today but going forward we will have someone with backup access. Fluke issue, we will try our best to ensure quick publishing going forward

**Comment by ThomasNieto** [comment]
> We manually publish to the store and the one person with access was on vacation until today but going forward we will have someone with backup access. Fluke issue, we will try our best to ensure quick publishing going forward

@StevenBucher98 is there an issue we can track to have that manual process moved to automated CI/CD?

**Comment by jhoneill** [comment]
There is another issue open about the message to update appearing prematurely. 

AIUI PowerShell's check for "new version" is "what is the latest downloadable via the github link". It really needs to look at something else, and say "what should I be telling people to update to", which should only get updated when the store is ready.

**Comment by StevenBucher98** [comment]
Here is an issue to track automating the process https://github.com/PowerShell/PowerShell/issues/19528

As for the update message I don't think we would be able to change that easily based on the type of install, @TravisEz13 may know better. Additionally we have a delay from our release on GitHub to Microsoft Update that unfortunately is not "work-around-able" 😆 but that would be another case a different update message would be helpful. 

> AIUI PowerShell's check for "new version" is "what is the latest downloadable via the github link". It really needs to look at something else, and say "what should I be telling people to update to", which should only get updated when the store is ready.

Yea I agree, it would be helpful to make it so the update message is relevant to whatever your specific upgrade is. I will add that to my investigation in issue linked above.

**Comment by fredemmott** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-getcurrentpackagefullname can be used to determine if it's running from an MSIX

One option would be to completely suppress the upgrade notice if running from MSIX - as, unless the user has explicitly disabled windows services to opt-in to doing updates themselves - it will be automatically updated by windows when possible.
