### ISSUE TITLE
Clear-Host doesn't work in PowerShell on Linux

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#1952]
Steps to reproduce
------------------
`Clear-Host`

Expected behavior
-----------------
It should clear a screen.

Actual behavior
---------------
Error mesage:
```
Program 'clear' failed to run: SuccessAt line:1 char:1ng
+ & (Get-Command -CommandType Application clear | Select-Object -First  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1ce             Continue
+ & (Get-Command -CommandType Application clear | Select-Object -First  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
Environment data
----------------

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment]
@alexandair *Please* post your operating system and version. "On Linux" is vague (what distro? in a container? on WSL (not Linux)? kernel version?). If you note; `Clear-Host` is simply calling the `clear` command, which is a native Linux utility, and it's failing on your system for unknown reasons. Can you please test if `clear` works by itself?

**Comment by luebking** [comment]
"clear" is part of ncurses, not coreutils.

**Comment by alexandair** [comment]
@andschwa  It's on WSL. Sorry, for not being precise.
I was puzzled that "clear" work on bash on Ubuntu on Windows, but when Clear-Host call it inside of PowerShell, it couldn't be find.

**Comment by andschwa** [comment]
@alexandair after investigating, please file a bug with [BashOnWindows](https://github.com/Microsoft/BashOnWindows), and link back here.

**Comment by alexandair** [comment]
Done. https://github.com/Microsoft/BashOnWindows/issues/988
