### ISSUE TITLE
Get-Help should provide an option to remove the path to the script when displaying comment-based help

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#19539]
### Summary of the new feature / enhancement

The current behavior of `Get-Help` when invoked for a script, even in the current directory, is the following:

```powershell
PS> help ./foo.ps1
```
![image](https://user-images.githubusercontent.com/12860484/233146244-5233890d-2916-41a0-9ddb-2c5e1c4989b9.png)

It would be more user-friendly (think of: sharing the output, printing it to PDF...) to have the option of excluding the path to the script, and keeping only the name (`foo.ps1`).

**Comment by doctordns** [comment]
The detailed help information that you show only happens if you explicitly include comment-based help within the script file. For completeness, `Get-Help` shows the complete path to the script. That makes the output unambiguous with respect to which foo.ps1 file the user is looking at.

**Comment by sba923** [comment]
I think I understand the rationale beyond the current implementation, that's why I'm proposing to add an option for those scenarios where showing the full path is undesirable.

**Comment by doctordns** [comment]
I would not be in favour of changing the default behaviour.  You could, I suppose, do one of two things. First, add a .NAME key in the CBH block to show explicitly the name you choose. Or, add a parameter to Get-Help that just returns the leaf file name. In am, though, not sure if there is sufficient support for changing the current behaviour, so more evidence would be useful.

**Comment by sba923** [comment]
I've never suggested to change the default behavior. Adding an optional parameter that would restrict the name to the leaf (filename) part would be perfectly fine. As mentioned in my original description, I have in mind a number of scenarios (e.g., reviewing the help content) where the help output would be shared with someone for which the original full path would not be useful, would not even make sense because it's a local path that's only valid for the person sharing. 

Additionally, when the full pathname is so long that the line needs to be wrapped, readability is not that great.

**Comment by sdwheeler** [comment]
@sba923 Thanks for the suggestion. The working group reviewed this. We don't see there being enough benefit to the majority of our users. There are many ways to alter the output for your publishing needs. We agree with @doctordns, the output is unambiguous with respect to which foo.ps1 file the user is looking at.

**Comment by sba923** [comment]
> @sba923 Thanks for the suggestion. The working group reviewed this. We don't see there being enough benefit to the majority of our users. There are many ways to alter the output for your publishing needs. We agree with @doctordns, the output is unambiguous with respect to which foo.ps1 file the user is looking at.

Well, the working group hath spoken 😜.

There are probably many ways.... but the first two I've come up with just don't work... Any clues?

![image](https://github.com/PowerShell/PowerShell/assets/12860484/49b34b25-818f-4620-bb6d-f794eef4cd02)

**Comment by sdwheeler** [comment]
This should work.

```powershell
get-help ./foo.ps1 | %{
    $name = (Get-Item $_.name).name
    $_.name = $name
    $_.details.name = $name
    $_.syntax | %{ $_.syntaxitem.name = $name }
    $_
}
```

**Comment by sba923** [comment]
> This should work.
> 
> ```powershell
> get-help ./foo.ps1 | %{
>     $name = (Get-Item $_.name).name
>     $_.name = $name
>     $_.details.name = $name
>     $_.syntax | %{ $_.syntaxitem.name = $name }
>     $_
> }
> ```

It does, thank you!

![image](https://github.com/PowerShell/PowerShell/assets/12860484/5883a1e1-e90b-4116-a65d-db7fccc73422)

Will probably turn this in to a `Get-HelpNoPathToScript.ps1` proxy script to make interactive work simpler.

P.S. it was far from obvious to me, I discovered only today that `Get-Help` outputs an object 😜

**Comment by sba923** [comment]
> This should work.
> 
> ```powershell
> get-help ./foo.ps1 | %{
>     $name = (Get-Item $_.name).name
>     $_.name = $name
>     $_.details.name = $name
>     $_.syntax | %{ $_.syntaxitem.name = $name }
>     $_
> }
> ```

This does not work if the script uses parameter sets (because in that case `$_.syntaxitem` itself is an array).

My current workaround is as follows:

```powershell
get-help ./foo.ps1 | Foreach-Object {
                $name = (Get-Item $_.name).name
                $_.name = $name
                $_.details.name = $name
                $_.syntax | ForEach-Object {
                    @($_.syntaxitem) | Foreach-Object {
                        if ($_.PSObject.Properties.Name -contains 'name')
                        {
                            $_.name = $name 
                        }
                    }
                }
                $_
            }
```

**Comment by sba923** [comment]
> We agree with @doctordns, the output is unambiguous with respect to which foo.ps1 file the user is looking at.

@sdwheeler Today's experiments revealed some inconsistency in `Get-Help`'s behavior: if the script doesn't contain any comment-based help, the full path to the script is **not** displayed:

```powershell
PS> get-help c:\tmp\foo_nohelp.ps1
foo_nohelp.ps1 [[-a] <string>] [[-b] <string>]
```

**Comment by sba923** [comment]
> My current workaround is as follows:

This covers more cases -- but I'm probably bound to discover more scenarios I don't have in mind, right? @sdwheeler --:

```powershell
get-help ./foo.ps1 | Foreach-Object {
                $name = (Get-Item $_.name).name
                $_.name = $name
                if ($_.PSObject.Properties.Name -contains 'details')
                {
                    $_.details.name = $name
                }
                if ($_.PSObject.Properties.Name -contains 'syntax')
                {
                    $_.syntax | ForEach-Object {
                        @($_.syntaxitem) | Foreach-Object {
                            if ($_.PSObject.Properties.Name -contains 'name')
                            {
                                $_.name = $name 
                            }
                        }
                    }
                }
                $_
            }
```

**Comment by sdwheeler** [comment]
> Today's experiments revealed some inconsistency in `Get-Help`'s behavior

Create a new issue for the buggy behavior

**Comment by sba923** [comment]
> > Today's experiments revealed some inconsistency in `Get-Help`'s behavior
> 
> Create a new issue for the buggy behavior

👍🤣

**Comment by sba923** [comment]
> > Today's experiments revealed some inconsistency in `Get-Help`'s behavior
> 
> Create a new issue for the buggy behavior

https://github.com/PowerShell/PowerShell/issues/19645

**Comment by sba923** [comment]
Note that https://github.com/PowerShell/PowerShell/issues/19645 breaks the path-removal logic above:

```powershell
get-help c:/tmp/foo_nohelp.ps1 | Foreach-Object {
>                 $name = (Get-Item $_.name).name
>                 $_.name = $name
>                 if ($_.PSObject.Properties.Name -contains 'details')
>                 {
>                     $_.details.name = $name
>                 }
>                 if ($_.PSObject.Properties.Name -contains 'syntax')
>                 {
>                     $_.syntax | ForEach-Object {
>                         @($_.syntaxitem) | Foreach-Object {
>                             if ($_.PSObject.Properties.Name -contains 'name')
>                             {
>                                 $_.name = $name
>                             }
>                         }
>                     }
>                 }
>                 $_
>             }
Get-Item:
Line |
   2 |                  $name = (Get-Item $_.name).name
     |                           ~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Windows\Temp\foo_nohelp.ps1' because it does not exist.
PropertyNotFoundException:
Line |
   2 |                  $name = (Get-Item $_.name).name
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'name' cannot be found on this object. Verify that the property exists.
foo_nohelp.ps1 [[-a] <string>] [[-b] <string>]
```
