### ISSUE TITLE
High Memory Usage on Ubuntu

### ISSUE THREAD

**Issue by elliotd123** [PowerShell/PowerShell#1953]
Ubuntu 16.04.1 and 14.04.5 - installed from latest docker image.

Each instance of powershell shows as using ~80MB of RAM - 3-4x the amount it uses on Win10 on the same hardware:

```
PS /> top -b  
top - 12:38:47 up 1 day, 22:01,  0 users,  load average: 0.23, 0.12, 0.07
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.0 us,  0.2 sy,  0.0 ni, 98.6 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2048456 total,    93428 free,   671832 used,  1283196 buff/cache
KiB Swap:  2095100 total,  1992348 free,   102752 used.  1129180 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    1 root      20   0   18236   3268   2796 S  0.0  0.2   0:00.00 bash
  459 root      20   0 2992440  85504  53208 S  0.0  4.2   0:02.78 powershell
  556 root      20   0 2983392  77372  50192 S  0.0  3.8   0:01.93 powershell
  575 root      20   0   36532   3052   2692 R  0.0  0.1   0:00.00 top
```

This seems like an unnecessarily high amount of usage

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by larsth** [comment]
Virtual memory is only allocated in physical RAM and/or swap, then it is used.

**Comment by elliotd123** [comment]
True, but I'm referring to real memory in this instance, not virtual.

**Comment by kumarharsh** [comment]
I'm running ConEMU on a Windows 10 Pro 1803, and the latest pwsh binary takes around 82.4MB per instance, whereas the default Windows Powershell (5.1.17134.165) takes only 42.3MB. Cmd takes a paltry 1.5MB.

**Comment by iSazonov** [comment]
@SteveL-MSFT @daxian-dbw We need to close the issue or update because we already is on .Net Cor 3.0.

**Comment by SteveL-MSFT** [comment]
@elliotd123 please comment or reopen this issue if this is still an issue with PS7 Preview.  Thanks.
