### ISSUE TITLE
Error code: Wsl/Service/ERROR_PATH_NOT_FOUND

### ISSUE THREAD

**Issue by DevOpsJazz** [PowerShell/PowerShell#19547]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Trying to install 

### Expected behavior

```console
wsl.exe --import wsl-vpnkit --version 2 $env:USERPROFILE\wsl-vpnkit wsl-vpnkit.tar.gz
Importen er i gang. Dette kan tage et par minutter.
Den angivne sti blev ikke fundet.
Error code: Wsl/Service/ERROR_PATH_NOT_FOUND
```

### Actual behavior

```console
Error code: Wsl/Service/ERROR_PATH_NOT_FOUND
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
@DevOpsJazz, please also note that this repo is only PowerShell (Core) issues; for problems with Windows PowerShell, please use the Feedback Hub application.
That said, as implied by @237dmitry's comment, if your problem is indeed PowerShell-related and you can demonstrate that with a still-supported PowerShell (Core) version, please do.
