### ISSUE TITLE
On Linux Get-ChildItem UnixMode property does not include the + to indicate extended ACLs exist for the item

### ISSUE THREAD

**Issue by JoeSalmeri** [PowerShell/PowerShell#19541]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

# Create test directory

mkdir test

# Set default ACL to be rwx for user and group

setfacl -d -m u::rwx,g::rwx test

# Show ACLs for test

getfacl test
# file: test
# owner: joe
# group: joe
user::rwx
group::---
other::---
default:user::rwx
default:group::rwx
default:other::---

# Using bash display test

ls -ald test

drwx------+ 2 joe joe 4.0K Apr 19 14:44 test

NOTE: the + sign indicating that extended ACLs exist for the item

# Display using pwsh

    Directory: /hd

UnixMode        User          Group            LastWriteTime           Size Name
--------                  ----             -----                 -------------                     ----    ----
drwx------           joe             joe                 4/19/2023 14:44         4096 test

Note that pwsh does not show that there are extended ACLs for the item.

### Expected behavior

```console
# Display using pwsh

    Directory: /vol/hd

UnixMode    User             Group                 LastWriteTime           Size Name
--------    ----             -----                 -------------           ---- ----
drwx------+ joe              joe                 4/19/2023 14:44           4096 test
```

### Actual behavior

```console
See steps to reproduce
```

### Error details

```console
No errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 6.2.10-1-default #1 SMP PREEMPT_DYNAMIC Thu Apr  6 10:36:55 UTC 2023 (ba7816e)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
The shell rather duplicates `/usr/bin/stat` and is unaware of extended access lists.

```
stat -c "%A" test
```

**Comment by JoeSalmeri** [comment]
> The shell rather duplicates `/usr/bin/stat` and is unaware of extended access lists.
> 
> ```
> stat -c "%A" test
> ```

So maybe that's not the best way for the pwsh to get that information since pretty much every other shell I've tried shows a + when extended acl information is available?

**Comment by 237dmitry** [comment]
I think only with native utilities. All we have is `UnixFileMode` and `UnixStat`.  This is common stat:

```powershell
[convert]::ToString([int](Get-Item ./test).UnixFileMode, 8)
755

[convert]::ToString((Get-Item ./test).UnixStat.Mode, 8)
40755     # 40000 means directory (in octal)
```

**Comment by JoeSalmeri** [comment]
> I think only with native utilities. All we have is `UnixFileMode` and `UnixStat`. This is common stat:

I think it is important for pwsh to provide core features like all the other linux shells provide, otherwise it makes the case for switching more difficult.

**Comment by doctordns** [comment]
I agree, in general, with @JoeSalmeri. That said, it's even more important to be specific. Yes, I'd like PowerShell to implement all the important features IT Pros across the spectrum are able to use. That said, We need to be specific on the exact core features you are meaning. Seems to me, we've done a pretty good job with PWSH7 to close the gap. Is this issue one of them.

And how important is this? I ask as someone who has very limited Linux experience.
