### ISSUE TITLE
`[type]` cast and `-as [Type]` malfunction with strings that contain "]" (only)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19559]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
# OK
[Type] 'int'
'int' -as [Type]

# !! BROKEN - these calls succeed, despite obviously broken input.
# Note that prepending "[" *would* fail, as expected, given that [Type] "[int]" doesn't - and shouldn't - work.
# It doesn't matter what, if anything, follows the closing-only "]"
[Type] 'int]whatever'
'int]whatever' -as [Type]
```

### Expected behavior

Output of two `[type]` instances, and two errors.

### Actual behavior

Output of _four_ `[int]` instances. That is, the broken type names were unexpectedly accepted.

### Environment data

```powershell
PowerShell Core 7.4.0-preview.3
```

**Comment by mklement0** [comment]
@MartinGC94, not that I recall - just did a quick search, but the only thing vaguely related I could find is https://github.com/PowerShell/PowerShell/issues/15197

**Comment by doctordns** [comment]
PLaying a bit with this - it looks like the ']' character is detected as ending the type name; So
`"int]foo" -as [Type}` creates an int (int32). But if you use `"Intf]00" -as [Type]` you get nothing.

**Comment by MartinGC94** [comment]
@doctordns Correct observation. It uses the parser to parse the string but doesn't actually validate that the whole string was parsed so any character that would make the parser end the type parsing (most special characters) would do this.

**Comment by doctordns** [comment]
Not sure what the correct thing to do would be. :-)  

Should the parser just throw an error trying to parse the malformed type name?  That might be a simple fix, but I don;t know how often folks would do something like this and what else might break!

Is this a common issue? I don't recall coming across this issue before, but I am forgetful these days.

**Comment by mklement0** [comment]
This strikes me as a straightforward bug fix: report a (statement-)terminating error, just like what already happens with _other_ invalid / nonexistent types:

```powershell
# -> Error "Cannot convert the "..." value of type "System.String" to type "System.Type"."
'foo' -as 'bar'
'foo' -as '&#*!'
```
