### ISSUE TITLE
Query members of SCCM distribution point group

### ISSUE THREAD

**Issue by joshiajanimesh** [PowerShell/PowerShell#19555]
### Summary of the new feature / enhancement

`get-cmDistributionPointGroup` cmdlet on MEM CB 2103 doesn't have a property/method to list members
`start-cmContentDistribution` accepts `[-DistributionPointGroupName <string[]>] [-DistributionPointName <string[]>]` as arguments. 

I have a custom function the enables a user to provide:

1. Package source directory path
2. Package content 
3. DPs to distribute package to
4. DP group(s) to distribute package to

To avoid duplication in distribution, if I can query members of a DP group, I can filter unique DPs from the list of supplied DP names. This way `start-cmContentDistribution` can be called for the DP group name first and then only for the DPs that don't exist in the group(s)

**Comment by jhoneill** [comment]
It's a reasonable thing to ask, but this repo is for PowerShell itself, and the question needs to go to the SCCM team.

**Comment by SeeminglyScience** [comment]
As mentioned, this repo does not contain the code for the ConfigurationManager module. The SCCM console [has a feedback button](https://learn.microsoft.com/en-us/mem/configmgr/core/understand/product-feedback) you can use to submit feedback to that team.
