### ISSUE TITLE
Invoke-RestMethod on Ubuntu 23.04 taking a long time to complete

### ISSUE THREAD

**Issue by dharmatech** [PowerShell/PowerShell#19557]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

OS: Ubuntu 23.04

# Invoke-RestMethod

The following `Invoke-RestMethod` command:

```
Measure-Command { $result = Invoke-RestMethod 'http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json' }
```

takes over 4 minutes to complete:

![image](https://user-images.githubusercontent.com/20816/233812110-0cae6f1e-0770-494f-89d7-00f2fa7a1c86.png)

# Browser

If I load the same URL in a browser:

```
http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json
```

it loads in less than a few seconds:

![image](https://user-images.githubusercontent.com/20816/233812210-bea150a2-f5c1-44fd-ba73-f4d27a7d9b0d.png)

### Expected behavior

```console
The command should return in less than a few seconds.
```

### Actual behavior

```console
It's taking over 4 minutes.
```

### Environment data

```powershell
(see screenshot above)
```

**Comment by jhoneill** [comment]
If you try the command with $global:result = Invoke-webrequest ... 
How long does that take.  ? 
You can try convertFrom-Josn $result.content afterwards - it's possible that it is the JSON to PowerShell object conversion that is adding the time, but 4 Minutes is pretty horrible!

**Comment by CarloToso** [comment]
```ps1
Measure-Command { $result = Invoke-WebRequest 'https://www.treasurydirect.gov/' }
#--> Seconds           : 21

Measure-Command { $result = curl 'https://www.treasurydirect.gov/' }
#--> Milliseconds      : 972
```
It seems like there are some issues in connecting to this website with Invoke-WebRequest

**Comment by dharmatech** [comment]
@CarloToso Thank you for those measurements!

Here's the results on Windows 11:

![image](https://user-images.githubusercontent.com/20816/233854603-bff262e2-3b53-4c32-a6df-32367480f12e.png)

```
PS C:\Users\dharm> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\dharm> Add-Type -AssemblyName System.Net.Http
PS C:\Users\dharm> $client = [System.Net.Http.HttpClient]::new()
PS C:\Users\dharm> Measure-Command { $result = $client.GetAsync('http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json').GetAwaiter().GetResult() }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 42
Milliseconds      : 951
Ticks             : 429519333
TotalDays         : 0.000497128857638889
TotalHours        : 0.0119310925833333
TotalMinutes      : 0.715865555
TotalSeconds      : 42.9519333
TotalMilliseconds : 42951.9333
```

**Comment by dharmatech** [comment]
@CarloToso 

And good call on noticing the issue occurs with `System.Net.Http.HttpClient`. 👍

**Comment by scriptingstudio** [comment]
@CarloToso really?

windows 11

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


Add-Type -AssemblyName System.Net.Http
$client = [System.Net.Http.HttpClient]::new()
Measure-Command { $result = $client.GetAsync('http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json').GetAwaiter().GetResult() }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 601
Ticks             : 16019735
TotalDays         : 1,85413599537037E-05
TotalHours        : 0,000444992638888889
TotalMinutes      : 0,0266995583333333
TotalSeconds      : 1,6019735
TotalMilliseconds : 1601,9735
```

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$client = [System.Net.Http.HttpClient]::new()
Measure-Command { $result = $client.GetAsync('http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json').GetAwaiter().GetResult() }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 126
Ticks             : 11266892
TotalDays         : 1,30403842592593E-05
TotalHours        : 0,000312969222222222
TotalMinutes      : 0,0187781533333333
TotalSeconds      : 1,1266892
TotalMilliseconds : 1126,6892
```

**Comment by dharmatech** [comment]
# Ubuntu 22.04.02 in WSL

```
PS /home/dharmatech> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/dharmatech> Add-Type -AssemblyName System.Net.Http
PS /home/dharmatech> $client = [System.Net.Http.HttpClient]::new()
PS /home/dharmatech> Measure-Command { $result = $client.GetAsync('http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json').GetAwaiter().GetResult() }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 375
Ticks             : 13754970
TotalDays         : 1.59201041666667E-05
TotalHours        : 0.0003820825
TotalMinutes      : 0.02292495
TotalSeconds      : 1.375497
TotalMilliseconds : 1375.497


PS /home/dharmatech> cat /etc/issue
Ubuntu 22.04.2 LTS \n \l
```

**Comment by dharmatech** [comment]
@CarloToso Thank you for those measurements!

@scriptingstudio Thank you for the report! Very interesting that it returns quickly for you. I just tried again on Windows 11 and it's still slow for me.

**Comment by CarloToso** [comment]
@dharmatech The plot thickens, I just repeated the measurements in another city (500km away, different ISP, same pc with windows 10) and I got the same results as @scriptingstudio (1.6 seconds). I don't know what could cause this problem.
The problem is present both on Powershell 5 (that uses `System.Net.WebClient`) and on Powershell 7 (that uses `System.Net.Http.HttpClient`)

**Comment by iSazonov** [comment]
You could use a sniffer to investigate the issue.

**Comment by dharmatech** [comment]
# Ubuntu 22.04.02 on WSL (Windows 11) : Fast

![image](https://user-images.githubusercontent.com/20816/233934937-d8539112-6b82-4564-89ad-8bcb6dc7b5f1.png)

**Comment by dharmatech** [comment]
# Windows 11

This is very odd... If I use `test-treasurydirect-delay-issue.ps1`, these are the results:

```
WebClient:  slow
HttpClient: fast
wsl curl:   fast
```

![image](https://user-images.githubusercontent.com/20816/233935911-346b04d0-6ac7-40cc-a866-dcba65502b24.png)

If I then run the script again immediately, these are the results:

```
WebClient:  fast
HttpClient: fast
wsl curl:   fast
```

![image](https://user-images.githubusercontent.com/20816/233936406-7f5f5ace-cf96-46a6-85a9-9ec0208d85e0.png)

**Comment by dharmatech** [comment]
It appears that while the first call made is slow, subsequent ones are fast.

# Windows 11

```
PS C:\Users\dharm> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\dharm> $url = 'https://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json'
PS C:\Users\dharm> Measure-Command { $result_webclient = (New-Object System.Net.WebClient).DownloadString($url) } | Select-Object TotalSeconds; $result_webclient.Substring(0, 70)

TotalSeconds
------------
  21.8049647
[{"cusip":"912797FG7","issueDate":"2023-05-02T00:00:00","securityType"


PS C:\Users\dharm> Measure-Command { $result_webclient = (New-Object System.Net.WebClient).DownloadString($url) } | Select-Object TotalSeconds; $result_webclient.Substring(0, 70)

TotalSeconds
------------
   0.4380311
[{"cusip":"912797FG7","issueDate":"2023-05-02T00:00:00","securityType"
```

**Comment by stevenebutler** [comment]
Previous comments benchmark takes 2 seconds for me, on first invocation and 0.8 seconds on second (on windows, pwsh 7.3.4

When I run the original I get similar results - so I'm wondering if it's related to some network routing issues.

Measure-Command { $result = Invoke-RestMethod 'http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json' }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 736
Ticks             : 27363535
TotalDays         : 3.16707581018518E-05
TotalHours        : 0.000760098194444444
TotalMinutes      : 0.0456058916666667
TotalSeconds      : 2.7363535
TotalMilliseconds : 2736.3535

On an ARM64 AWS instance in Sydney Data centre I get
 Measure-Command { $result = Invoke-RestMethod 'http://www.treasurydirect.gov/TA_WS/securities/search?issueDate=2023-04-11,2023-05-26&format=json' }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 358
Ticks             : 23588181
TotalDays         : 2.73011354166667E-05
TotalHours        : 0.00065522725
TotalMinutes      : 0.039313635
TotalSeconds      : 2.3588181
TotalMilliseconds : 2358.8181
