### ISSUE TITLE
unicode and emoji files rename cant find the file

### ISSUE THREAD

**Issue by eix128** [PowerShell/PowerShell#19556]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Get-ChildItem -Path . -File | ForEach-Object {
    $new_name = "$(New-Guid).$($_.Extension)"
    Rename-Item -Path $_.FullName -NewName "$new_name.webm"
}

### Expected behavior

```console
All files on Rename-Item should be found.
```

### Actual behavior

```console
Rename-Item seems like not recognizing emoji files and unicode files ?




But the file exist in path
```

### Error details

```console
Rename-Item : Cannot rename because item at 'C:\Users\Administrator\Desktop\zeki\Zeki Müren'in Karikatür Anısı
[NblWvBD0kiQ].webm' does not exist.
At line:3 char:5
+     Rename-Item -Path $_.FullName -NewName "$new_name.webm"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Rename-Item], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand
```

### Environment data

```powershell
(base) PS C:\Users\Administrator\Desktop\zeki> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
You're using the `-Path` parameter, which means that path argument is interpreted as a  [wildcard](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Wildcards) expression, in which  `[` and `]` have special meaning.

Use the `-LiteralPath` parameter instead or - preferably - use a [delay-bind scriptblock](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_script_blocks#using-delay-bind-script-blocks-with-parameters):

```powershell
Get-ChildItem -LiteralPath . -File  |  
  Rename-Item -NewName  { "$(New-Guid)$($_.Extension).webm" }
```

**Comment by mklement0** [comment]
Also note that the issue template states:

> For Windows PowerShell 5.1 issues, suggestions, or feature requests please use the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)
This repository is ONLY for PowerShell Core 6 and PowerShell 7+ issues.
