### ISSUE TITLE
New-Item -Type File -Path "Name" creates a new file, but locks it until the script ends

### ISSUE THREAD

**Issue by tps800** [PowerShell/PowerShell#19571]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Creating a new file with:
```
$file = New-Item -Type File -Path "$env:TEMP\UsersTempFile.txt"
```
Creates the file, but if this file is intentionaly opened by an other application this application will throw an error: `Failed to open log file: open C:\Users\sct-muc\AppData\Local\Temp\2023-04-26_17-31-26_rclone.log: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.`

or `Failed to open log file: open "C:\Users\sct-muc\AppData\Local\Temp\2023-04-26_17-31-26_rclone.log": Die Syntax f├╝r den Dateinamen, Verzeichnisnamen oder die Datentr├ñgerbezeichnung ist falsch.`

The file cant be opened for writing. The lock on this newly created file vanishes if the script creating it terminates.

### Expected behavior

```console
$file = New-Item -Type File -Path "$env:TEMP\UsersTempFile.txt"
Remove-Item -Path "$env:TEMP\UsersTempFile.txt"
```
Creating a file, but leaving it unlocked to be opened for writing by other applications.

### Actual behavior

```console
$file = New-Item -Type File -Path "$env:TEMP\UsersTempFile.txt"
Remove-Item -Path "$env:TEMP\UsersTempFile.txt"
Remove-Item: The process cannot access the file 'C:\Users\<user>\AppData\Local\Temp\UsersTempFile.txt' because it is being used by another process.
```
Created file is locked. Other applications are not able to open it.

### Error details

```console
PS> Remove-Item "$env:TEMP\UsersTempFile.txt
Remove-Item: The process cannot access the file 'C:\Users\<user>\AppData\Local\Temp\UsersTempFile.txt' because it is being used by another process.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
The Error is seen with latest version 7.4 too:
```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.2
PSEdition                      Core
GitCommitId                    7.4.0-preview.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
The Error is not seen with PowerShell 5.1

**Comment by 237dmitry** [comment]
Try:

```
$file = (New-Item -Type File -Path "$env:TEMP\UsersTempFile.txt")
```

**Comment by tps800** [comment]
I could successful create a file with
```powershell
$Job = Start-Job -Name "CreateFile" -ScriptBlock { New-Item -Type File -Path "$env:TEMP\UsersTempFile.txt" } 
Wait-Job $Job
Remove-Job $Job
```
The file was created within a new powershell instance, this instance terminates. The file is closed. Afterwards I could do something like:
```shell
&"cmd.exe" "/C" "dir > $env:TEMP\UsersTempFile.txt"
```

Without having an error about a non writable file.

**Comment by 237dmitry** [comment]
> using (...) can't be expected to make a difference here

Maybe you are right. In my case, it works with and without brackets. We need a specific example.

![ArcoLinux_2023-04-26_23-12-03](https://user-images.githubusercontent.com/78153320/234692632-71824147-d64a-4f83-8037-afe1fdf6f4f9.png)

**Comment by kasini3000** [comment]
mormal:
```
$f = "$env:TEMP\UsersTempFile.txt"
$f2 = New-Item -Type File -Path $f
$f2
'-------------'
Start-Sleep -Seconds 1
Remove-Item -Path $f
Get-ChildItem -Path $f

```

**Comment by StevenBucher98** [comment]
Yeah I am unable to reproduce this issue, are you able to work around your issue with some of the suggestions above @tps800?
