### ISSUE TITLE
Executionpolicy set in GPO is ignored in Powershell 7.2.11

### ISSUE THREAD

**Issue by krylosz** [PowerShell/PowerShell#19589]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Powershell 7 ignores Executionpolicy settings made in GPO. Machinepolicy remains undefined even though it is set via GPO and displayed and used correctly in Powershell 5 on the same machine.
![Powershell-Executionpolicy](https://user-images.githubusercontent.com/123062074/235170481-f4db09ec-6175-487b-beb9-7ef6be70b5c9.png)

### Expected behavior

```console
PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
```

### Actual behavior

```console
PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.11
PSEdition                      Core
GitCommitId                    7.2.11
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by PaulHigin** [comment]
@TravisEz13  can you please take a look?

**Comment by TravisEz13** [comment]
Please install the PowerShell 7 GPO and set that and see if you still have this issue:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_group_policy_settings?view=powershell-7.3
