### ISSUE TITLE
Can't access HttpResponseHeaders key values

### ISSUE THREAD

**Issue by nwalk7800** [PowerShell/PowerShell#19582]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After getting an error from Invoke-RestMethod, you can't get the value for a specific response header by key.  This works as expected in PowerShell 5.1

You can get the value using TryGetValues.

I know that there was a change from WebClient to HttpClient, but I'm not sure if this behavior is intended.

### Expected behavior

```console
PS D:\> Invoke-RestMethod "https://api.publicapis.org/entries/NA"
Invoke-RestMethod : 404 page not found
At line:1 char:1
+ Invoke-RestMethod "https://api.publicapis.org/entries/NA"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
PS D:\> $Error[0].Exception.Response.Headers

Key                    Value
---                    -----
Date                   {Thu, 27 Apr 2023 17:32:51 GMT}
Server                 {Caddy}
X-Content-Type-Options {nosniff}
PS D:\> $Error[0].Exception.Response.Headers["Server"]
Caddy
PS D:\>
```

### Actual behavior

```console
PS D:\> Invoke-RestMethod "https://api.publicapis.org/entries/NA"
Invoke-RestMethod: 404 page not found
PS D:\> $Error[0].Exception.Response.Headers

Key                    Value
---                    -----
Date                   {Thu, 27 Apr 2023 17:32:51 GMT}
Server                 {Caddy}
X-Content-Type-Options {nosniff}
PS D:\> $Error[0].Exception.Response.Headers["Server"]
PS D:\> $t = $null
PS D:\> $Error[0].Exception.Response.Headers.TryGetValues("Server", [ref] $t)
True
PS D:\> $t
Caddy
PS D:\>
```

### Environment data

```powershell
PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by CarloToso** [comment]
Some more tests on PS 7.3.4
```ps1
Invoke-RestMethod "https://api.publicapis.org/entries/NA"
#-->Invoke-RestMethod: 404 page not found
$Error[0].Exception.Response.Headers
<#
Key                    Value
---                    -----
Date                   {Thu, 27 Apr 2023 17:32:51 GMT}
Server                 {Caddy}
X-Content-Type-Options {nosniff}
#>
$Error[0].Exception.Response.Headers.Date
<#
DateTime      : 27/04/2023 22:36:24
UtcDateTime   : 27/04/2023 22:36:24
LocalDateTime : 28/04/2023 00:36:24
Date          : 27/04/2023 00:00:00
Day           : 27
DayOfWeek     : Thursday
DayOfYear     : 117
Hour          : 22
Millisecond   : 0
Microsecond   : 0
Nanosecond    : 0
Minute        : 36
Month         : 4
Offset        : 00:00:00
Second        : 24
Ticks         : 638182317840000000
UtcTicks      : 638182317840000000
TimeOfDay     : 22:36:24
Year          : 2023
#>

$Error[0].Exception.Response.Headers.Server
<#
Product Comment
------- -------
Caddy
#>

$Error[0].Exception.Response.Headers.XContentTypeOptions
#-->NOTHING
```

**Comment by CarloToso** [comment]
More tests with hyphenated keys
```ps1
$Error[0].Exception.Response.Content.Headers
<#
Key            Value
---            -----
Content-Length {19}
Content-Type   {text/plain; charset=utf-8}
#>

$Error[0].Exception.Response.Content.Headers.ContentLength
#-->19

$Error[0].Exception.Response.Content.Headers.ContentType
<#
CharSet Parameters      MediaType
------- ----------      ---------
utf-8   {charset=utf-8} text/plain
#>
```

**Comment by mkht** [comment]
This is due to the migration from WebClient (Windows PowerShell) to HttpClient (pwsh). The type of `$Error[0].Exception.Response.Headers` has been changed from [WebHeaderCollection](https://learn.microsoft.com/ja-jp/dotnet/api/system.net.webheadercollection) to [HttpResponseHeaders](https://learn.microsoft.com/ja-jp/dotnet/api/system.net.http.headers.httpresponseheaders). So values cannot be accessed using expressions such as `$Headers['Server']`.

This issue is also mentioned in #18884

**Comment by IISResetMe** [comment]
As you've found the new `HttpResponseHeaders` type doesn't provide an index accessor. 

To get the value(s) associated with a given header, use [`GetValues()`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders.getvalues#system-net-http-headers-httpheaders-getvalues(system-string)):

```
$Error[0].Exception.Response.Headers.GetValues('Server')
```

**Comment by CarloToso** [comment]
Some `HttpResponseHeaders` properties can be accessed directly:
```
AcceptRanges
Age
CacheControl
Connection
ConnectionClose
Date
ETag
Location
NonValidated
Pragma
ProxyAuthenticate
RetryAfter
Server
Trailer
TransferEncoding
TransferEncodingChunked
Upgrade
Vary
Via
Warning
WwwAuthenticate
```
from https://learn.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpresponseheaders?view=net-8.0#properties
for `$Error[0].Exception.Response.Headers`.

Instead for `$error[0].Exception.Response.Content.Headers` this properties can be accessed directly:
```
Allow
ContentDisposition
ContentEncoding
ContentLanguage
ContentLength
ContentLocation
ContentMD5
ContentRange
ContentType
Expires
LastModified
```
from https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/HttpKnownHeaderNames.cs
