### ISSUE TITLE
support for session histories  longer than 4096 commands

### ISSUE THREAD

**Issue by Didjacome** [PowerShell/PowerShell#19593]
### Summary of the new feature / enhancement

Ensure that Get-History saves histories greater than 4096 commands. With that you can have visibility of old commands and so you can have an example history with more than 1000000 commands.

This idea came up because I have a stored history of over 700000 commands in a historico.clixml file. but whenever it is imported using Import-Clixml historico.clixml | Add-History poweshell always only brings back the last 4096 commands. All commands that are in the historico.clixml file are unique, no repeating commands.

acceptance criteria: Make sure that Get-History saves histories with more than 4096 commands

**Comment by 237dmitry** [comment]
```
$MaximumHistoryCount

Determines how many commands are saved in the command history for the
current session.

VALID VALUES: 1 - 32768 (Int32)

DEFAULT: 4096
```

```
help About_Preference_Variables
help Set-PSReadlineOptions
```

**Comment by Didjacome** [comment]
Hi @237dmitry,

hope you are well

According to the documentation, you can increase the value of $MaximumHistoryCount of the System.Management.Automation.ValidateRangeAttribute type up to 32767. But even if you change $MaximumHistoryCount and even Get-PSReadLineOption | Select-Object MaximumHistoryCount the import commands are up to 4096.
docs: 

- [learn - MaximumHistoryCount](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_history?view=powershell-7.3#maximumhistorycount)
- [Increase PowerShell Command History to the Max (Almost)](https://devblogs.microsoft.com/scripting/increase-powershell-command-history-to-the-max-almost/)
- [about_preference_variables - MaximumHistoryCount](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#maximumhistorycount)
- [Windows PowerShell 5.1 and PowerShell Core also save the last 4096](https://woshub.com/powershell-commands-history/)



However, even increasing 4096 to 32767, there would still be a delimiter. **My proposal is that there should be no history delimiter in Powershell 7**, just as we have in linux bash that, with some configuration, can have unlimited history

### acceptance criteria: Make sure that Get-History saves histories with more than 4096 commands

**Comment by 237dmitry** [comment]
> But even if you change $MaximumHistoryCount and even Get-PSReadLineOption | Select-Object MaximumHistoryCount the import commands are up to 4096.

Which history were you asking about, session history or PSReadline history?

This is a count of commands in  `(Get-PSReadlineOption).HistorySavePath`:
```
Set-PSReadlineOption -MaximumHistoryCount 1e9    # That's enough for a long time
```

This is a count of commands in current session:
```
$MaximumHistoryCount = 32768
```
Set this values in `$Profile` to save them.

**Comment by Didjacome** [comment]
@237dmitry 

My suggestion is that the session history that has a delimiter in System.Management.Automation.ValidateRangeAttribute from 1 to 32767. Making it impossible to have longer histories.

**My proposal is that there is no session history delimiter in Powershell 7**

### acceptance criteria: Make sure that Get-History saves histories with more than 4096 commands

**Comment by doctordns** [comment]
In my experience, the history maintained by PSReadLine is more than adequate. Is that not good enough? If there needs to be a change, I would favour updating PSReadLine. Comments?

**Comment by Didjacome** [comment]
Hi @doctordns 

hope you are well

I understand that PSReadLine can help, because it saves all commands in a file called WindowsPowerShellhistory.txt

- but let's say we want an old command and can't remember how it was done, it is much simpler to run` get-history | Select-String ""` instead of looking in PSReadLine in the file \WindowsPowerShellhistory.txt

- Let's assume another scenario, you have a Windows server core and want to have the session history of executed commands for auditing. This would not be possible with PSReadLine.

- Let's assume another scenario, you have a Windows server core and want to check who executed certain commands, in` get-history` you can see the command executed, when it was and how long the execution lasted, and with that you can see the login logs and compare what time the command was executed with who logged in that period

I don't think it is that difficult to increase the session history range, since in Dotnet Core you can increase the System.Management.Automation.ValidateRangeAttribute to much more than 32767.

I cannot say what impacts this change would have 

If there is an easier way or you know something that might help, please let me know

**My proposal is that there is no session history delimiter in Powershell 7**

### acceptance criteria: Make sure that Get-History saves histories with more than 4096 commands

**Comment by Didjacome** [comment]
![image](https://user-images.githubusercontent.com/83463639/235372158-7e1add94-104f-4390-84ef-4ddf901ddaf8.png)

**Issue resolved by the community, it will be closed.**

### Thank you very much for the help of everyone involved
