### ISSUE TITLE
ps window loses focus after start-process

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#19606]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
Start-Process -FilePath  "pwsh"  -ArgumentList " -NonInteractive -NoProfile -WindowStyle hidden -file a:\pscode\TEMP_2023\temp135\aaa-v2.ps1 "
```
When "Start-Sleep -second 5" on aaa-v2.ps1,The parent powershell process will soon return to focus.
When "Start-Sleep -second 55" on aaa-v2.ps1,The parent powershell process will long time return to focus.

### Expected behavior

```console
Return to focus right now after The parent powershell process script end  .
```

### Actual behavior

```console
ps window loses focus after start-process
```

### Error details

Cause:
The powershell window loses focus after start-process. 
When the "start-process process" ends, focus will resume, depending on the length of the process execution time.

If your script contains "start-process", 
in order to retrieve the focus of the powershell window, you will frequently click on the window,

----
I want to write a script to fix it. 
But it was found the script works normally in powershell, but does not work in win terminal.

### Environment data

```powershell
powershell 5.1.19041.1320 on win10
PowerShell 7.4.0-preview.3 on win10
all version win terminal.
parent powershell child pwsh,
parent pwsh child powershell,
```

**Comment by mklement0** [comment]
By design, `Start-Process` makes the newly launched process' main window the active window (the foreground window with the input focus).

Since your intent appears to be to launch a _hidden_ PowerShell instance, use `-WindowStyle Hidden` _with `Start-Process`_ rather than the `-WindowStyle hidden` _CLI parameter_, which bypasses the problem of losing focus.

**Comment by kasini3000** [comment]
good , 3q！
