### ISSUE TITLE
copy progress in 7.4 preview 3 does not work if files are in a single directory and does not show correct total to copy

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PowerShell#19600]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a digital camera memory card with a root folder DCIM and 3 sub folders - the first contains ~ 250 files, the second 500 files and the third ~250 files. Average size is 44MB Roughly 44 GB to copy.

Copy speed from my card reader is ~100MB/sec, so copying the recent files from one folder will take 1-2 minutes, and the new progress bar would be nice. 

`copy D:\DCIM\140PENTX\*   C:\temp\deleteme\ -Recurse`    
Displays no progress

`copy D:\DCIM\*   C:\temp\deleteme\ -Recurse`    
Displays progress as in  the video at https://github.com/PowerShell/PowerShell/pull/18735  HOWEVER it only **shows the count of files** and number of bytes to copy for the first directory.  ie. instead of 1000 files /44 GB it shows 251 files, 

### Expected behavior

```console
All large copies show progress
```

### Actual behavior

```console
Copying a lot of data from one directory does not.
```

### Error details

```console
No error. Command runs, but shows no progress.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://user-images.githubusercontent.com/16209593/235725342-ccf58749-f36a-4c04-95c8-9e7cd2ec48f4.mp4

**Comment by SteveL-MSFT** [comment]
The problem is that when copying a single folder, it's just a single .NET API call, so there's no way to know and write progress.  We would have to split it into individual copy calls to be able to render progress which would slow down the operation.

**Comment by theJasonHelmick** [comment]
Thank you @jhoneill  -- The implementation of this feature is not fully understood and needs further investigation. We also recommend that this behavior be turned into an experimental feature.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this.  We can investigate showing a static progress message when copying lots of files that don't result in subfolders being copied.

**Comment by jhoneill** [comment]
> The problem is that when copying a single folder, it's just a single .NET API call, so there's no way to know and write progress. We would have to split it into individual copy calls to be able to render progress which would slow down the operation. I think the best we could do is show a "progress" pane with the total number of files to be copied, but it wouldn't show progress, just that copying was happening.
> 
> If the WG decides not to add a static progress pane, then we should at least document this behavior so it's not surprising.
Yeah, I suspect for my case - copying dozens or a few hundred large files, the overhead of making one call per file is not significant. For the reverse case - copying thousands of small files the overhead of the extra copy calls and updating the progress after each one probably is. It's not at all clear what's best overall but it's unlikely that one choice will delight everyone. (I'm not wholly against saying 'if you want copy with progress, use the GUI or Robocopy, but it's not really expected in a shell')

The issue I reported above was it actually reports wrong information, the numbers given being the first directory of multiple ones.

**Comment by SteveL-MSFT** [comment]
@jhoneill just had a fix merged in, can you check if this is still a problem after we have a release with that change (or if you're adventurous build that branch)
