### ISSUE TITLE
Assertion failed when cancelling remote prompt

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#19607]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Build PowerShell from latest master and open 2 instances
2. Use `Enter-PSHostProcess` to enter the other instance
3. Type in `Write-Progress -Completed`
4. When you get a prompt for the mandatory parameter, press Ctrl+C

### Expected behavior

```console
No crash.
```

### Actual behavior

```console
Crash.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2-1488-g07e041fe10d4c753dfccfa46008bdedebdfd3027
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://user-images.githubusercontent.com/42123497/235995588-989836da-08dd-4122-8e78-bff416a21a53.png)

**Comment by rhubarb-geek-nz** [comment]
This is on a preview  [7.2.0-preview.2](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.2) from 2020.

Have you tested It on the latest [7.2.11](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.11)? or [7.3.4](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.4)?
