### ISSUE TITLE
chaining script cmdlets which use `-pipelinevariable` do not work as expected

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#19618]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

create 2 functions:
```powershell
PS> function cmdletB {[CmdletBinding()]param()BEGIN{"b2"}PROCESS{"! p2 !"}END{"e2"}}                                              
PS> function cmdletA {[CmdletBinding()]param()BEGIN{"b1"}PROCESS{"! p1 !";cmdletB}END{"e1"}}               
```

this will operate as expected:
```powershell
PS> cmdletA -pv a| % {"> $a <"}
> b1 <
> ! p1 ! <
> b2 <
> ! p2 ! <
> e2 <
> e1 <
```

however, if you add `-pv a` to the invocation of `cmdletB`, you can see the issue.

```powershell
PS> function cmdletA {[CmdletBinding()]param()BEGIN{"b1"}PROCESS{"! p1 !";cmdletB -pv a}END{"e1"}}
PS> cmdletA -pv a| % {"> $a <"}                                                                   
> b1 <
> ! p1 ! <
> ! p1 ! <
> ! p1 ! <
> ! p1 ! <
> e1 <
```

it seems to lose all output from `cmdletB`.
It doesn't seem to matter if you choose a different pipeline variable for `cmdletB`

```powershell
PS> function cmdletA {[CmdletBinding()]param()BEGIN{"b1"}PROCESS{"! p1 !";cmdletB -pv b}END{"e1"}}
PS> cmdletA -pv a| % {"> $a $b <"}                                                                
> b1  <
> ! p1 !  <
> ! p1 !  <
> ! p1 !  <
> ! p1 !  <
> e1  <
```

possibly related to:
https://github.com/PowerShell/PowerShell/pull/16199
https://github.com/PowerShell/PowerShell/pull/12766

### Expected behavior

```console
PS> cmdletA -pv a| % {"> $a <"}
> b1 <
> ! p1 ! <
> b2 <
> ! p2 ! <
> e2 <
> e1 <
```

### Actual behavior

```console
PS> cmdletA -pv a| % {"> $a <"}                                                                   
> b1 <
> ! p1 ! <
> ! p1 ! <
> ! p1 ! <
> ! p1 ! <
> e1 <
```

### Error details

```console
no error
```

### Environment data

```powershell
PS> $psversiontable     

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3-29-g07e041fe10d4c753dfccfa46008bdedebdfd3027
OS                             Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
No pipeline, no pipeline variable. `cmdletB -pv a` cannot expand `$a` (just nowhere). This function works (every script block) but has no output.
