### ISSUE TITLE
Ubuntu 16.04 PowerShell installation will fail instruction correction needed.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#1963]
Steps to reproduce
------------------
I just created a dual boot on my laptop (Windows 10 and Ubuntu Desktop 16.04).

After downloading the "powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb" into my Ubuntu and then executed the following commands from the setup instruction page.

$ sudo apt-get install libunwind8 libicu55
$ sudo dpkg -i powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb
dpkg: error processing archive powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb

Expected behavior
-----------------
To install PowerShell without errors.

Actual behavior
---------------
dpkg: error processing archive powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb

Workaround
---------------
Need to change directory to Downloads, then execute dpkg.

$ cd Downloads
$ sudo dpkg -i powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb

Environment data
----------------
Ubuntu Desktop 16.04.1

$PSVersionTable                                        

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.9                                  
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

**Comment by andschwa** [comment]
It appears to me that you have not downloaded the package: `powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb`.

If you note, the error you received says:

> cannot access archive: No such file or directory

You need to have the package to install it.

Please follow this first step in the [documentation](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604):

>Using Ubuntu 16.04, download the Debian package powershell_6.0.0-alpha.9-1ubuntu1.16.04.1_amd64.deb from the releases page onto the Ubuntu machine.

Let me know if you need more help.
