### ISSUE TITLE
Error loading ConfigManager module

### ISSUE THREAD

**Issue by jcasale** [PowerShell/PowerShell#19630]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When hosting an instance of PowerShell v7.3.4, I am unable to load an older PS module for Config Manager.

I am aware that some cmdlets are not supported in PowerShell Core, but many are and they work in `pwsh.exe` v7.3.4.

When I create a console project with `Microsoft.PowerShell.SDK` v7.3.4 using the following code:

```CSharp
using System.Management.Automation.Runspaces;
using System.Management.Automation;
using Microsoft.PowerShell;

namespace Repro
{
    internal class Program
    {
        private static async Task Main()
        {
            var initialSessionState = InitialSessionState.CreateDefault();
            initialSessionState.LanguageMode = PSLanguageMode.FullLanguage;
            initialSessionState.ExecutionPolicy = ExecutionPolicy.RemoteSigned;

            using var runspace = RunspaceFactory.CreateRunspace(initialSessionState);
            runspace.Open();

            using var powerShell = PowerShell.Create();
            powerShell.Runspace = runspace;

            var script = """
                Set-StrictMode -Version Latest

                $CMServer = 'host.example.com'
                $CMSiteCode = '...'

                Import-Module (Join-Path $env:SMS_ADMIN_UI_PATH '..\ConfigurationManager.psd1')
                if(!(Get-PSDrive $CMSiteCode -ErrorAction SilentlyContinue))
                {
                    New-PSDrive -Name $CMSiteCode -PSProvider CMSite -Root $CMServer -Description 'Primary site' -ErrorAction Stop |Out-Null
                }

                Push-Location ('{0}:' -f $CMSiteCode)
                """;

            powerShell.AddScript(script);

            var results = await powerShell.InvokeAsync().ConfigureAwait(false);
        }
    }
}
```

it fails to load the module. If I open `pwsh.exe` v7.3.4 and execute the same code, it works and I can execute all the supported cmdlets.

What does the host created by `pwsh.exe` do differently that allows the module to load successfully?

### Expected behavior

```console
The script executes without error.
```

### Actual behavior

```console
The script throws a `System.Management.Automation.ActionPreferenceStopException` error while importing the module.


Unhandled exception. System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at HostingRepro0.Program.Main() in C:\scm\Repro\Repro\Program.cs:line 44
   at HostingRepro0.Program.<Main>()
```

### Error details

```console
n/a
```

### Environment data

```powershell
n/a
```

**Comment by LxLeChat** [comment]
Hello @jcasale 
Did you find a solution? I m facing the same issue..

**Comment by jcasale** [comment]
Hi @LxLeChat 
Sadly, I did not. I imagine it has something to do with [type loading](https://devblogs.microsoft.com/powershell/resolving-powershell-module-assembly-dependency-conflicts/) functionality that the interactive shell implements.

However, I have not explored how they might implement this in a generic fashion.
