### ISSUE TITLE
Type that implements `IDictionary<,>` but also implements its own indexer unexpectedly prioritizes the interface's indexer for GET operations

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19649]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: 
* The scenario is exotic and may even be ill-advised, but the inconsistency is curious and does _not_ arise in C# code.
* Note the use of `new`, which makes the type implement its own indexer that is _not_ part of an interface implementation. This new, type-specific indexer _is_ honored with `[...]` syntax on _setting_, but not on _getting_. It appears that on getting the `IDictionary<,>` interface's indexer is called instead.

```powershell
Add-Type @'
using System;
using System.Collections.Generic;
public class CustomDict<T1, T2> : Dictionary<T1, T2>
{
    public new T2 this[T1 key]
    {
        get { return (T2) (object) 20; }
        set { base[key] = (T2) (object) 10; }
    }
}
'@
$o = [CustomDict[string, int]]::new()
$o['foo'] = 42  # HONORS the type-specific indexer (sets 10)
$o['foo']       # BYPASSES the type-specific indexer (gets 10)
$o.Item('foo')  # HONORS the type-specific indexer (gets 20)
```

### Expected behavior

```console
20
20
```

### Actual behavior

```console
10
20
```

### Environment data

```powershell
PowerShell 7.4.0-preview.3
```

**Comment by SeeminglyScience** [comment]
Clarification, an override would be `override` instead of `new`. This is a new indexer with the same name, but it is no longer the implementation of `IDictionary<,>` or `Dictionary<,>`'s indexer.

**Comment by mklement0** [comment]
Understood re terminology, thanks - what's the best way to phrase it?

**Comment by SeeminglyScience** [comment]
Kind of tricky to summarize succinctly

Maybe "Type that implements `IDictionary<,>` but also surfaces its own unrelated indexer prioritizes the `IDictionary<,>` indexer"?

**Comment by mklement0** [comment]
@SeeminglyScience, sounds good, thanks; I've tweaked the wording slightly and have updated the title and  the initial post.
