### ISSUE TITLE
Get-Help doesn't resolve the script's filespec to a full absolute path if no comment-based help is found in the script

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#19645]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When invoking `Get-Help` for a script that contains comment-based help, the script's filespec is resolved to the script's full absolute path (see https://github.com/PowerShell/PowerShell/issues/19539):

```powershell
get-help ./foo.ps1

NAME
    C:\tmp\foo.ps1

SYNOPSIS
    syntax


SYNTAX
    C:\tmp\foo.ps1 [[-a] <String>] [[-b] <String>] [<CommonParameters>]
```

This is not the case if the script doesn't contain comment-based help, only the script's name is output:

```powershell
get-help ./foo_nohelp.ps1
foo_nohelp.ps1 [[-a] <string>] [[-b] <string>]
```

This affects both Windows PowerShell 5.1 and PowerShell 7.3.4.

### Expected behavior

```console
# for consistency's sake
get-help ./foo_nohelp.ps1
c:\tmp\foo_nohelp.ps1 [[-a] <string>] [[-b] <string>]
```

### Actual behavior

```console
get-help ./foo_nohelp.ps1
foo_nohelp.ps1 [[-a] <string>] [[-b] <string>]
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by sdwheeler** [comment]
The Working Group reviewed this. We would classify this as a low priority bug. We would welcome a PR to address this issue.

**Comment by sba923** [comment]
The problem stiill repro'es with 7.4.0

![image](https://github.com/PowerShell/PowerShell/assets/12860484/ad2cc47d-730d-435a-888d-24e79bc339f3)
