### ISSUE TITLE
Az.Storage is no longer working for Get-AzStorageAccount

### ISSUE THREAD

**Issue by wrharper-AASP** [PowerShell/PowerShell#19646]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

    $AzureContext = (Connect-AzAccount).context
    Select-AzSubscription -Context $AzureContext
$global:AzStorageContext = (Get-AzStorageAccount).Context  #<--- error happens here in visual studio code

The latest version of powershell cannot be used. I have tried:
Install-Module Az -AllowClobber -Scope CurrentUser
Install-Module Microsoft.Graph -Scope CurrentUser -AllowClobber
Import-Module Az.Accounts
Import-Module Az.Storage

### Expected behavior

```console
Should be able to assign storage account context
```

### Actual behavior

```console
Get-AzStorageAccount : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Storage.StorageManagementClient' from assembly 'Microsoft.Azure.PowerShell.Storage.Management.Sdk, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by kilasuit** [comment]
@wrharper-AASP please open this issue in the [Azure-PowerShell](https://github.com/Azure/azure-powershell/issues/) repo as this seems to be an issue with that module and is not on any version of PowerShell that this repo supports.
