### ISSUE TITLE
Out-GridView: Is there a way to force single item selection when -PassThru is used?

### ISSUE THREAD

**Issue by Phillyclause89** [PowerShell/PowerShell#19642]
### Summary of the new feature / enhancement

If not consider this a feature request for such a switch?  I have use cases where I want to force my users to only be able to select a single row displayed in the Out-GridView window.

**Comment by MartinGC94** [comment]
`Get-ChildItem | Out-GridView -OutputMode Single`

**Comment by Phillyclause89** [comment]
Thanks @MartinGC94! That's exactly what I needed!
