### ISSUE TITLE
Get-ChildItem - Can't Exclude Folders

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19654]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I’m calling **Get-ChildItem** as shown below. I need it to skip folders in the directory tree that have the strings **test**, **prototype** or **_vti** in the name. None of the excluded folders are at the top of the tree.

```
Write-Host  "Looking for new & changed files in $LocalRoot & subfolders"
$exclusions = @("*test*","*prototype*","*_vti*")
Write-Host  "Exclusions: $exclusions`n"
$stopwatch  = [system.diagnostics.stopwatch]::StartNew()
$files      = Get-ChildItem -Path $LocalRoot -Recurse -Attributes Archive -Exclude $exclusions
```

Before terminating, the script produces this output: 

```CONFIGURATION FILE:  C:\Users\Dick\Documents\tch\code\scripts\PowerShell\UpdateTchSite.config
CONFIGURATION DATA:

        LocalRoot=C:/Users/Dick/Documents/tch/site
        ServerRoot=/
        SiteNameInWinSCP=CyberHymnalSFTP

Looking for new & changed files in C:/Users/Dick/Documents/tch/site & subfolders
Exclusions: *test* *prototype* *_vti*
**```**

### Expected behavior

```console
The script should report the number of files found.
```

### Actual behavior

```console
The script aborts with an error after a few minutes
```

### Error details

```console
**Cannot bind parameter 'Property'. Cannot convert the "C:\Users\Dick\Documents\tch\site\img\b\e\e\s\_vti_cnf\beesley_e.jpg" value of type "System.IO.FileInfo" to type "Microsoft.PowerShell.Commands.PSPropertyExpression".**

As you can see, the file is in a folder named **_vti_cnf**, which should have been excluded from the search.

Is this a bug, or am I doing something wrong?
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/6260602/d29d65ee-adb0-4e64-b8d7-d8e07e8dd836)

**Comment by mkht** [comment]
`-Exclude` only matches the name of the item, not the name of the parent directory.
An easy workaround is to filter by `Where-Object`.

```PowerShell
$exclusionPattern = @("test","prototype","_vti") -join "|"
$item = Get-ChildItem -Path $LocalRoot -Recurse -Attributes Archive | Where-Object FullName -notmatch $exclusionPattern
```

**Comment by aksarben** [comment]
Wow. That seems to do the trick.

Could someone add that example to the Get-ChildItem documentation?

___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________

**Comment by kilasuit** [comment]
@aksarben the docs are open source so you could raise a PR for this if you wanted to - the repo for that is at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs/tree/main/reference)

However I have flagged this for the docs team, just in case that you don't feel confident in adding an example (though it's really not that difficult once you understand how to)
