### ISSUE TITLE
Get-ChildItem - How Many Entries Did It Check While Recursing?

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19658]
### Summary of the new feature / enhancement

1. Can you add a property to Get-ChildItem that would tell how many entries it checked? Not how many it **_chose_**, but how many candidates it **_examined_**. I’d like to know the count to verify whether I specified the search parameters correctly.

2.  While recursing a directory tree, can we have an option to make Get-ChildItem to display the the name of each folder so we have an idea of progress?

### Proposed technical implementation details (optional)

I use Get-ChildItem to recurse a very large directory tree, with over 50,000 files, so it's hard to verify it's doing what I intended without more feedback, such as number of items checked, progress display, etc.

**Comment by jhoneill** [comment]
```PowerShell
function Watch-Progress {
    param (
        [Parameter(ValueFromPipeline=$true,Position=0)]
        $InputObject,
        [Parameter(Position=1)]
        $Activity = "Progress",
        [Parameter(Position=2)]
        $Every = 1
    )
    begin   {$dirCount = $fileCount = 0}
    process { 
        if ($InputObject -is [System.IO.DirectoryInfo] ) {
            $dirCount ++
            if ($dirCount % $every -eq 0) {Write-Progress -Activity $Activity -Status "$DirCount Directories, $fileCount Files."} 
        }
        elseif ($InputObject -is [System.IO.FileInfo]) {$fileCount ++}
        Write-Output $InputObject
    }
}
```
Specify an optional label and how often you want it to update - writing to the console is fairly slow, so you might want the use `-Every 10`

Works like this - obviously you can store results in a variable or pipe into another command. 

<img width="653" alt="image" src="https://github.com/PowerShell/PowerShell/assets/16209593/6ca86d66-c850-476d-96e2-a3b65d87cbd6">

**Comment by aksarben** [comment]
Well, of couse, I've seen progress indicators coded before, and this one is similar.

What I'm unclear on is where this would get its input data. When we call Get-ChildItem we don’t receive any information until it finishes. Unless I’m missing something, which is possible, since I’m very new to PowerShell.

Dick Adams
___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________

**Comment by 237dmitry** [comment]
> When we call Get-ChildItem we don’t receive any information until it finishes.

Pipe output to view information. But I do not understand what is this for.

```powershell
Get-Childitem C:\Windows -Recurse -ErrorAction 0 | Foreach-Object { $_.FullName }
```
