### ISSUE TITLE
Get-ChildItem Fails: Can't Convert Folder Name to Microsoft.PowerShell.Commands.PSPropertyExpression

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19655]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I’m writing a script to find files in a directory tree.

### Expected behavior

```console
It returns the file count.
```

### Actual behavior

```console
After running for about 12 seconds, the script aborts with the error message in “Error details” below. The folder mentioned in the error message (C:\Users\Dick\Documents\tch\site\ogg\m\o) is several levels down from the root and has no special properties. It has many sibling directories just like it.

Here is the script’s output before it aborts:

Enter password: *

CONFIGURATION FILE:  C:\Users\Dick\Documents\tch\code\scripts\PowerShell\UpdateTchSite.config
CONFIGURATION DATA:

        LocalRoot=C:/Users/Dick/Documents/tch/site
        ServerRoot=/
        SiteNameInWinSCP=CyberHymnalSFTP

Looking for new or changed files in C:/Users/Dick/Documents/tch/site & subfolders
Exclusion pattern: test|prototype|_vti
```

### Error details

```console
Cannot bind parameter 'Property'. Cannot convert the "C:\Users\Dick\Documents\tch\site\ogg\m\o" value of type "System.IO.DirectoryInfo" to type "Microsoft.PowerShell.Commands.PSPropertyExpression".
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Screen shot from Visual Studio Code:

![image](https://github.com/PowerShell/PowerShell/assets/6260602/b66a533e-0b58-4913-b767-fcd5f1646c54)

**Comment by 237dmitry** [comment]
It's not clear from your screenshot.

**Comment by mklement0** [comment]
It's not `Get-ChildItem` that fails, it's `Measure-Object`, and that is to be expected:

Your attempt, `Measure-Object $item`, is the equivalent of the following, because `Measure-Object`'s first _positional_ parameter is `-Property`:

```powershell
$item = (Get-ChildItem -Directory $HOME)
Measure-Object -Property $item
````
`-Property` expects the names of properties of the input objects to measure, which isn't your intent.

To pass _input_ to `Measure-Object`, you must bind its non-positional `-InputObject` parameter, which can only be meaningfully bound _via the pipeline_: 

```powershell
(Get-ChildItem -Directory $HOME) | Measure-Object
```

**Comment by aksarben** [comment]
I uncovered a clue. The folder in question (**C:\Users\Dick\Documents\tch\site\ogg\m\o**) had the archive bit set (not sure why, but it did). When I removed the archive bit from the folder & re-launched the script, I got a similar error, but this time **for a subfolder in ogg/m/o.** 

If I could figure out how to tell **Get-ChildItem** I want only **_files_** (with their complete paths, of course), **_not folder objects_**, I suspect that would fix the problem. I tried changing the call parameter to **Attributes Archive !Directory**, but that gave a different error.

Would appreciate any insight on how to call Get-ChildItem to find **only files** with the archive bit set. The documentation doesn't seem to address the topic of multiple attribute settings.

**Comment by aksarben** [comment]
> It's not `Get-ChildItem` that fails, it's `Measure-Object`, and that is to be expected:
> 
> Your attempt, `Measure-Object $item`, is the equivalent of the following, because `Measure-Object`'s first _positional_ parameter is `-Property`:
> 
> ```powershell
> $item = (Get-ChildItem -Directory $HOME)
> Measure-Object -Property $item
> ```
> 
> `-Property` expects the names of properties (or expressions expressing _calculated_ properties) of the input objects to measure, which isn't your intent.
> 
> To pass _input_ to `Measure-Object`, you must bind its non-positional `-InputObject` parameter, which can only be meaningfully bound _via the pipeline_:
> 
> ```powershell
> (Get-ChildItem -Directory $HOME) | Measure-Object
> ```
Don't think that's the issue. It never gets to the line with the Measure-Object call. The script throws an error while executing Get-ChildItem.

**Comment by aksarben** [comment]
Ok, I have egg on my face. The Measure-Object call **_was_** the culprit. I changed it to **$item.Length**, and all is well.

But now I've uncovered a new problem: Get-ChildItem is returning folders as well as files. Anyone know how exclude folders from the returned array? In other words**, I want only files, not folders.**

**Comment by aksarben** [comment]
Solved the mystery. The correct syntax for specifying multiple attributes requires a plus sign. Here’s the code that finally did the trick:
```
$exclusions = "test|prototype|_vti"
$files = Get-ChildItem -Path $LocalRoot -Recurse -Attributes Archive+!Directory | Where-Object FullName -notmatch $exclusions
```
Note to Microsoft: Please update the Get-ChildItem documentation page. Feel free to use my code as an example if you think others would find it helpful.

**Comment by aksarben** [comment]
Thanks for taking the time to look at it, Michael.

I replied to your comment on the bug report page. I eventually fixed by using $items.count. Had a couple of other things to fix, including how to exclude directories from the returned items, but eventually found the right syntax. Details are on the bug report thread.

Don't forget tell your mom happy Mother's Day!

God bless,

Dick Adams
___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________

**Comment by mklement0** [comment]
Glad to hear you found a fix, @aksarben.

Note that the email you replied to was simply a notification of activity here in this thread.

`Measure-Object $item.Length` won't report any errors, but will effectively be a no-op (no output).

As for the documentation of `Get-ChildItem`'s `-Attribute` parameter:

It is [here](https://learn.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Get-ChildItem?view=powershell-7.3#parameters) and it does show an example similar to yours.

However, `Get-ChildItem -File -Attribute Archive` should work too.

Happy Mother's Day to your mother too.
