### ISSUE TITLE
File with square brackets '[' in the filename cannot be read using Get-Content or Switch -File Method on Windows

### ISSUE THREAD

**Issue by HCRitter** [PowerShell/PowerShell#19663]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Issue: File with square brackets '[' in the filename cannot be read using Get-Content or Switch -File Method on Windows

**Description:**
There is a known issue in the latest PowerShell 7.X and Windows PowerShell versions where files containing square brackets '[' in their filenames cannot be read using the `Get-Content` or `Switch -File` methods on Windows. The issue specifically affects files with opening square brackets '[' in their names.

**Steps to Reproduce:**
1. Run the following PowerShell script to check which filenames are legal on Windows by creating a test file:
```powershell
# Check which filenames are legal on Windows by creating a test file
for ($i = 32; $i -le 126; $i++) {
    $char = [char]$i
    try {
        $fileName = "C:\Temp\legalchartest\$char.txt"
        $null = New-Item -Path $fileName -ItemType File -Force -Value "Test" -ErrorAction Stop
        $char
    }
    catch {
        # Invalid character, do nothing
    }
}
```
**Execute the following code to check the results: **
```powershell
$TestResult = (Get-ChildItem -Path "C:\Temp\legalchartest\").ForEach({
    $returnobject = [PSCustomObject]@{
        Character = $PSItem.BaseName
        GetContentResult = $null
        SwitchFileResult = $null
    }

    try {
        Get-Content -Path $PSItem.FullName -ErrorAction Stop | Out-Null
        $returnobject.GetContentResult = $true
    }
    catch {
        $returnobject.GetContentResult = $false
    }
    
    try {
        switch -File ($PSItem.FullName) {
            default{
                
            }
        }
        $returnobject.SwitchFileResult = $true
    }
    catch {
        $returnobject.SwitchFileResult = $false
    }
    
    $returnobject
})
$TestResult
```

### Expected behavior

```console
Files with square brackets '[' in their filenames should be readable using the Get-Content and Switch -File methods on Windows.
```

### Actual behavior

```console
Files with square brackets '[' in their filenames should be readable using the Get-Content and Switch -File methods on Windows.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by mklement0** [comment]
* As for `Get-Content`:
  * The short of it is: use `-LiteralPath`
  * For more information, see https://github.com/PowerShell/PowerShell/issues/19594#issuecomment-1529018912

* As for `switch`: 
  * Unfortunately, there is no `-LiteralPath` equivalent yet:
    *  See #8988
  * Thus, your only option at the moment is to use _escaping_:
    * `switch -File ([WildcardPattern]::Escape($PSItem.FullName))`
