### ISSUE TITLE
Is it time to officially support rhel9?

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PowerShell#19672]
### Summary of the new feature / enhancement

Ready to officially support rhel9?

### Proposed technical implementation details (optional)

The official version of rhel 9.2 has been released. I suggest powershell 
 officially(strengthening) support for it. 
Specific:

* Add support here: 
https://github.com/PowerShell/PowerShell/blob/master/README.md

* Add installation package here:
http://packages.microsoft.com/rhel/9/prod/Packages/p/

----

### About Name:
Due to the marginalization of centos,
My suggestion the name is: 'All rhel9 compatible version'
What is your opinion on names?

----

# Do you need a longer testing period?

What is your opinion?

http://packages.microsoft.com/rhel/8/prod/Packages/p/powershell-7.3.4-1.rh.x86_64.rpm

i tested ps v7.3.4 on rocky linux 9.1 ,normal currently.

**Currently, Centos8 is highest support for powershell on Powershell.md. What are the stones on the rhel9 way?**

**Comment by rhubarb-geek-nz** [comment]
Builds prior to 7.2 used to have the full OS and version in the package name, eg

```
powershell-7.0.11-1.rhel.7.x86_64.rpm
powershell_7.0.11-1.debian.9_amd64.deb
powershell_7.0.11-1.debian.10_amd64.deb
powershell_7.0.11-1.debian.11_amd64.deb
```

But that naming was dropped with 7.2, now the names are like

```
powershell_7.3.4-1.deb_amd64.deb
powershell-7.3.4-1.rh.x86_64.rpm
powershell-7.3.4-1.cm.x86_64.rpm
```

Without any indication of the the operating system release.

So now you don't actually know what version of OS any particular package will work on until you attempt to install it and it complains about some ssl or glibc bindings missing.

**Comment by rhubarb-geek-nz** [comment]
[[Microsoft .NET 8 preview prompts debate](https://devclass.com/2023/05/18/is-asp-net-on-the-right-path-microsoft-net-8-preview-prompts-debate-and-visual-studio-17-6-rolls-out/)](https://devclass.com/2023/05/18/is-asp-net-on-the-right-path-microsoft-net-8-preview-prompts-debate-and-visual-studio-17-6-rolls-out/)

```
The required version of glibc on Linux is being updated for .NET 8. “.NET 8 is built targeting Ubuntu 16.04, for all architectures … .NET 8 will fail to start on distro versions that include an older glibc, such as Ubuntu 14.04 or Red Hat Enterprise Linux 7,” said Douglas.
```

**Comment by kasini3000** [comment]
？？？ centos 7 eol date is 2024-06-30，.net8 release date is 2023-10 , 
So FALSE message from you

**Comment by rhubarb-geek-nz** [comment]
> ？？？ centos 7 eol date is 2024-06-30，.net8 release date is 2023-10 ,

If .NET 8 is released requiring a version of glibc that is not on Centos 7 then it won't work on Centos 7, it doesn't matter what the [end of support for Centos 7](https://wiki.centos.org/About/Product) is. Normally the final support for an operating system is patching critical bugs, not upgrading features and major versions of libraries.

```
During the Maintenance updates phase, only Security errata and select mission critical bug fixes will be released. There will be few, if any, Update Sets released upstream.
```

**Comment by kasini3000** [comment]
You're right
https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md
. net8 will be released in October 2023, while centros7 will be available for EOL on June 30, 2024, and will generally be available for use within one year.
Centos7 is not dead yet,. net8 is in a hurry to bury Centos7 alive!!!

**Comment by rhubarb-geek-nz** [comment]
For example, according to the [URL](https://wiki.centos.org/About/Product) , Centos 7 Aarch64 is still supported. However the build for [powershell-7.3.4-linux-arm64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/powershell-7.3.4-linux-arm64.tar.gz) does not work, as it errors with

```
./pwsh: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./pwsh)
./pwsh: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./pwsh)
```

So it depends on the specific binary linkages for any distribution.

**Comment by rhubarb-geek-nz** [comment]
7.4.1 is available at packages.microsoft.com/rhel/9, does it not work?
powershell-7.4.1-1.rh.x86_64.rpm
[](https://packages.microsoft.com/rhel/9/prod/Packages/p/powershell-7.4.1-1.rh.x86_64.rpm)

**Comment by theJasonHelmick** [comment]
This request is being tracked in #17548

**Comment by ceztko** [comment]
> For example, according to the [URL](https://wiki.centos.org/About/Product) , Centos 7 Aarch64 is still supported.

@rhubarb-geek-nz unfortunately even some Microsoft documentation is outdated and it appears like rhel/centos 7 is still supported ([link](https://learn.microsoft.com/en-us/powershell/scripting/install/install-rhel?view=powershell-7.4#installation-via-direct-download)), while the doc with official [support statements](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.4#red-hat-enterprise-linux-rhel) is clearly saying rhel7 is not.

For anyone that desperately needs Powershell 7.4 in rhel/centos 7 like me, I'm testing this `RUN` statement in docker:

```
RUN yum -y install https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell-7.4.2-1.rh.x86_64.rpm \
    && sed -i '$ d' /etc/shells \
    && wget http://www.vuln.cn/wp-content/uploads/2019/08/libstdc.so_.6.0.26.zip \
    && md5sum -c <<< "197608e4ffc485169cf52f365f5ecde7  libstdc.so_.6.0.26.zip" \
    && unzip libstdc.so_.6.0.26.zip \
    && mv libstdc++.so.6.0.26 /lib64/ \
    && rm libstdc.so_.6.0.26.zip \
    && echo $'#!/usr/bin/env sh\nLD_PRELOAD=/lib64/libstdc++.so.6.0.26 /usr/bin/pwsh "$@"' > /usr/local/bin/pwsh \
    && chmod +x /usr/local/bin/pwsh
```

Trivial tests are ok, so far.
