### ISSUE TITLE
Turn on optimization for non-windows

### ISSUE THREAD

**Issue by kunalspathak** [PowerShell/PowerShell#19677]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I noticed powershell sets `Optimize=false` on non-windows which might make it slow to execute on those OSs.

 https://github.com/PowerShell/PowerShell/blob/master/PowerShell.Common.props#L189-L194

Can we see if the problem has resolved and turn optimize it back on?

### Expected behavior

```console
Optimize=true
```

### Actual behavior

```console
Optimize=false
```

### Environment data

```powershell
non-windows
```

**Comment by 237dmitry** [comment]
I'am afraid of any "optimizations". Everything works quickly, faster than on Windows (maybe hardware). Slower than `/usr/bin/bash` (difference `0.0*` for native utilities), but still fast for human perception. What is slower is shebang scripts.

**Comment by SeeminglyScience** [comment]
It's referring to compiler optimizations, which we absolutely should be enabling if at all possible. Reading the blame and involved threads it looks like we need to fix some interop code.
