### ISSUE TITLE
Timeout Option for Read-Host

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19684]
### Summary of the new feature / enhancement

Can an optional timeout value be added to Read-Host?

### Proposed technical implementation details (optional)

Syntax could look like this:

Read-Host [-timeout <seconds>]

**Comment by mklement0** [comment]
Good idea, but your issue is a duplicate of:

* #19664

**Comment by aksarben** [comment]
“I see,” said the blind carpenter, as he picked up his hammer & saw.

I subscribed (I think) to the other topic. Can’t wait to hear what people think of the idea!

Thanks for the quick turnaround.

Dick Adams

___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________
