### ISSUE TITLE
Clear-History isn't working on OS X 10.11.6

### ISSUE THREAD

**Issue by blooodorange** [PowerShell/PowerShell#1968]
## Steps to reproduce

Clear-History
## Expected behavior

https://technet.microsoft.com/en-us/library/hh849733.aspx
## Actual behavior

Clear-History does not delete previously used commands
## Environment data

``` powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

**Comment by fxlv** [comment]
Tried same thing on OSX also, indeed you still get your history with arrow keys, but if you query the history with `Get-History` then it appears cleared.
Perhaps 2 different sets of history are kept?

**Comment by fxlv** [comment]
I did some dtracing.
Looks like there are indeed 2 sets of history, one from the powershell, other from readline.

The readline one is in `~/.local/share/powershell/PSReadLine/ConsoleHost_history.txt` and it is not cleared when calling `Clear-History`

**Comment by fxlv** [comment]
I did more digging. This is https://github.com/lzybkr/PSReadLine that is saving the history.

So in fact the `Clear-History` might not even be doing anything wrong (though it is misleading).
There are some workarounds, such as removing the history file - http://stackoverflow.com/questions/13257775/powershell-clear-history-doesnt-clear-history

But probably PowerShell guys will provide much better answer.

**Comment by lzybkr** [comment]
This issue was moved to lzybkr/PSReadLine#465
