### ISSUE TITLE
Proposed New Verb - “Simulate”

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19713]
### Summary of the new feature / enhancement

I’d like to suggest the word “Simulate” be added to the list of approved PowerShell verbs.

My Use Case: I am writing a new FTP client, and am going to create special functions to call (instead of the regular functions) when simulating file uploads. I would like to give the functions names that start with “Simulate.” For example, Simulate-SendingFile, Simulate-ChangingServerWorkingDirectory, etc.

That way, future developers could set breakpoints inside the simulated functions to, for example, examine the logic for determining the target directory on the server, updating number of bytes sent, estimated completion time, experiment with code changes, etc., **all without endangering the integrity of a _real_ upload**. This would be especially valuable if a new programmer lacked a robust development environment.

Plus, anyone doing a high level review of the code could easily see all functions whose name with “Simulate” so he would know where to focus his attention when looking at protocol compliance, etc.

Another benefit is that all the “Simulate” functions could be put in their own module(s). This would avoid the overhead of importing unnecessary modules during production runs.

I'll be writing the functions regardless of whether I can name them “Simulate-xxx.” However, the names will not as helpful in describing what they actually do.

And of course,  the verb “Simulate” could have widespread use far beyond FTP. There are many software development fields which use simulations. Weather forecasting and military war gaming come to mind, as just two examples.

**Comment by aksarben** [comment]
Found additional examples of where simulation is used: User Interface development & software testing. 

The -WhatIf parameter is similar/related, but IMHO, not as powerful as dedicated simulation code.

**Comment by jhoneill** [comment]
> The -WhatIf parameter is similar/related, but IMHO, not as powerful as dedicated simulation code.

Nothing is stopping you using a non-approved verb in your own development code.  It's only if you release a module that others you'll nagged about it. 

In pester commands are `mocked` so they are called with the same name and that is normal way this is done for testing

Generally "dedicated simulation code" means two copies of the same code, and `-whatif` / `shouldProcess`  side steps this. I'd advise against changing your code from and from calling Verb-Noun, to calling Simulate-Verb noun.  If your really need separate code for simulation you can load the simulation version with the same name (effectively as a mock), run the original code that calls those names.

**Comment by kilasuit** [comment]
Wouldn't this use case be covered by the Test Verb? Especially if that command returns a true/false response & any errors that occurred if it's desired result isn't achieved? 
The other suggestion I'd have is to have a Test Parameter on your commands and then contain the test logic in the commands themselves - keeping it all cleaner and together though that would be almost a re-write of how `Should Process` does this for you.

**Comment by aksarben** [comment]
I probably didn't explain too well.

It's not a flag, to determine whether we're IN a simulation. It's an indicator to the reader that the code about to executed is simulated (i.e., has no effect on real world objects).  Hope that clarifies.

___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________
