### ISSUE TITLE
src/libpsl-native/test/googletest/ does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by ajensenwaud** [PowerShell/PowerShell#1971]
aj:PowerShell/ (master✗) $   pushd src/libpsl-native                                                                                                                                            [7:25:19]

~/PowerShell/src/libpsl-native ~/PowerShell ~/PowerShell/src ~
aj:libpsl-native/ (master✗) $   cmake -DCMAKE_BUILD_TYPE=Debug .                                                                                                                                [7:25:20]

-- The C compiler identification is Clang 3.4.1
-- The CXX compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at test/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /home/aj/PowerShell/src/libpsl-native/test/googletest

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/aj/PowerShell/src/libpsl-native/CMakeFiles/CMakeOutput.log".

Are some files missing / not committed yet?

**Comment by qrwteyrutiyoup** [comment]
Take a look at https://github.com/PowerShell/PowerShell#downloading-the-source-code

You probably didn't use --recursive when cloning, so you don't have the submodules (googletest is one of them). Try to update the submodules with

git submodule update --init

**Comment by Sum1n** [comment]
https://www.youtube.com/watch?v=8iztXdjBDMw&feature=youtu.be

**Comment by josteink** [comment]
I can second that. I had issues building libpsl-native until I did a recursive clone. Looking over the documentation, it's all there really, but it's still a simple mistake to miss.

I suggest closing this issue.

**Comment by lzybkr** [comment]
Closing as it sounds like the question has been addressed - reopen if the solution doesn't help.
