### ISSUE TITLE
[Feature Request] Tab complete improvements: Drop down menu like modern web UIs with application specified suggestions and fuzzy search

### ISSUE THREAD

**Issue by octopushugger** [PowerShell/PowerShell#19712]
### Summary of the new feature / enhancement

Besides making it easier to select suggestions that are a few down the list this could potentially turn tab complete into a powerful auto quick search function saving you the time of having to run a manual search through another command or even worse through the gui. 

I find myself constantly running manual searches because I can't remember or just don't know the exact names of commands, packages, arguments, whatever. I feel all those could be solved if tab complete was more like modern web search suggestions.

I realize this could be awkward to implement when the line you're typing on is at the bottom of the window. I don't have a perfect solution for that but my first thought is to make it like the context menu where it travels upwards instead of down when it's too close to the bottom of the screen. Perhaps also make the list slightly transparent so it doesn't fully block any text that you might be trying to read directly above where you're typing. 

Let me know what you guys think.

**Comment by 237dmitry** [comment]
> saving you the time of having to run a manual search through another command or even worse through the gui.

In this situation I search with `Ctrl-Space`.

```
PS > Get-Content -<Ctrl+Space>
```

**Comment by MartinGC94** [comment]
As @237dmitry said, the `MenuComplete` feature in PSReadline (triggered by default with Ctrl+Space) already does this pretty well.  
In addition to that, the Windows terminal team is working on adding a shell integration feature which in the future may make the completion experience feel more like traditional IntelliSense. You can see a demo of it here: https://youtu.be/nDa8JWkW1_g?t=1683

Also, here's a tip you may not be aware of: Tab completion for commands supports wildcards. If you type in: `*-VM<Ctrl+Space>` you will see all the VM commands.

**Comment by jhoneill** [comment]
> In this situation I search with `Ctrl-Space`.
> 
> ```
> PS > Get-Content -<Ctrl+Space>
> ```

Ctrl+space is what is normally suggested. 

> Also, here's a tip you may not be aware of: Tab completion for commands supports wildcards. If you type in: `*-VM<Ctrl+Space>` you will see all the VM commands.

I use this a lot when first working with a new module. 

You can also use 

- `#part of a command`  `[tab]` to find commands from the current session when you can't remember the syntax for all the things you discovered over an afternoon 
- `[ctrl]+[r]  part of command` to search through your history.

Ps readline also has past-line completion so if you start typing `set-widget -fettle medium`  after a little while it recognises what you are doing and suggests that line. `[f2]` will toggle this to showing a list of similar possibilities. (useful if you have 20 different set-widget commands in your history). 

You need to run ` Set-PSReadlineOption  -PredictionSource History`   to turn this on and this is best done from your profile. 
I customize this so I can bring the whole line back or bring it back a word at a time with [ctrl]+[right arrow] code is in this gist
https://gist.github.com/jhoneill/cd5a7114335d25cb8f0b6281bf73fb83 


There are numerous other suggestions about how completion and suggestion _could_ be improved and more ideas for the pot are generally welcome - some things that people who work on it would like to do are very challenging.  I think with this one is just not widely known - one PowerShell veteran I know was shocked to discover it and then to find it had been in the Windows PowerShell ISE for a long time.
