### ISSUE TITLE
ForEach-Object -Parallel Performance With Inline Code Block

### ISSUE THREAD

**Issue by NoMoreFood** [PowerShell/PowerShell#19721]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For sufficiently large code blocks, it appears that using commands like New-Module or Invoke-Expression within the ForEach-Object script block to import code is significantly faster than having the code inline.  I added two simple files that demonstrate this.  I have much more significant "real world" results that caused me to stumble across this.  The issue does seem to scale with the size of the code block.  I am willing to dive into the PowerShell codebase myself to investigate this, but I wanted to make sure there was nothing "obvious" that would explain this difference.  Interestingly, the gap widens even more when Windows Defender is disabled.  I expect this performance increase overall, in general, due to AMSI integration but I thought huge drop in one versus the other was notable.

To put it another way:

```
$CodeBlock = @'
... lots of code / functions ...
'@

ForEach-Object -Parallel {
   Invoke-Expression $using:CodeBlock
}
```

Is noticeably faster than:

```
ForEach-Object -Parallel {
... lots of code / functions ...
}
```

[Performance-InlineVersusInvoke.zip](https://github.com/PowerShell/PowerShell/files/11582202/Performance-InlineVersusInvoke.zip)

### Expected behavior

```console
- With Windows Defender On

pwsh -File Performance-Invoke.ps1

Total Time: 8.3013503
Object Total: 100000

- With Windows Defender Off

pwsh -File Performance-Invoke.ps1

Total Time: 1.0237361
Object Total: 100000
```

### Actual behavior

```console
- With Windows Defender On

pwsh -File Performance-Inline.ps1

Total Time: 18.7531856
Object Total: 100000

- With Windows Defender Off

pwsh -File Performance-Inline.ps1

Total Time: 16.9042796
Object Total: 100000
```

### Error details

```console
None
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
### big problem ？！

Run Performance-Invoke. ps1 3 times, and found that the memory usage is getting larger and larger. Can clean memory by
```
$Passed = $null
$TimeResult = $null
[System.GC]::Collect()
[System.GC]::WaitForPendingFinalizers()
[System.GC]::Collect()
[System.GC]::WaitForPendingFinalizers()
[System.GC]::Collect()
[System.GC]::WaitForPendingFinalizers()
```

Run Performance-Inline.ps1 3 times and found that the memory usage is getting larger and larger. Cannot clean memory by THE CODE
