### ISSUE TITLE
Incorrect sort order when using tab completion and listing items

### ISSUE THREAD

**Issue by rboxman** [PowerShell/PowerShell#19736]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am inside a directory that looks as follows.  Notice how it's listing out files in the incorrect order!  This applies to tab completion as well and the "broken" items will be completed before the correct items.  There must be a sort-order bug someplace...
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/29/2023  5:26 AM           6060 check_cmake_consistency_config.py    <-- broken; wrong order
-a---           5/29/2023  5:26 AM          14928 check_cmake_consistency.py
-a---           5/29/2023  5:26 AM           5119 check_deprecated.py
-a---           5/29/2023  5:26 AM           6025 check_descriptions.py
-a---           5/29/2023  5:26 AM           2147 check_header_duplicate.py
-a---           5/29/2023  5:26 AM          15793 check_licenses.py
-a---           5/29/2023  5:26 AM           3792 check_mypy_config.py    <-- broken; wrong order
-a---           5/29/2023  5:26 AM           2908 check_mypy.py
-a---           5/29/2023  5:26 AM          13648 check_spelling_c_config.py    <-- broken; wrong order
-a---           5/29/2023  5:26 AM          23475 check_spelling.py
-a---           5/29/2023  5:26 AM           2524 check_unused_defines.py
```

### Expected behavior

```console
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/29/2023  5:26 AM          14928 check_cmake_consistency.py
-a---           5/29/2023  5:26 AM           6060 check_cmake_consistency_config.py
-a---           5/29/2023  5:26 AM           5119 check_deprecated.py
-a---           5/29/2023  5:26 AM           6025 check_descriptions.py
-a---           5/29/2023  5:26 AM           2147 check_header_duplicate.py
-a---           5/29/2023  5:26 AM          15793 check_licenses.py
-a---           5/29/2023  5:26 AM           2908 check_mypy.py
-a---           5/29/2023  5:26 AM           3792 check_mypy_config.py
-a---           5/29/2023  5:26 AM          23475 check_spelling.py
-a---           5/29/2023  5:26 AM          13648 check_spelling_c_config.py
-a---           5/29/2023  5:26 AM           2524 check_unused_defines.py
```

### Actual behavior

```console
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           5/29/2023  5:26 AM           6060 check_cmake_consistency_config.py    <-- broken; wrong order
-a---           5/29/2023  5:26 AM          14928 check_cmake_consistency.py
-a---           5/29/2023  5:26 AM           5119 check_deprecated.py
-a---           5/29/2023  5:26 AM           6025 check_descriptions.py
-a---           5/29/2023  5:26 AM           2147 check_header_duplicate.py
-a---           5/29/2023  5:26 AM          15793 check_licenses.py
-a---           5/29/2023  5:26 AM           3792 check_mypy_config.py    <-- broken; wrong order
-a---           5/29/2023  5:26 AM           2908 check_mypy.py
-a---           5/29/2023  5:26 AM          13648 check_spelling_c_config.py    <-- broken; wrong order
-a---           5/29/2023  5:26 AM          23475 check_spelling.py
-a---           5/29/2023  5:26 AM           2524 check_unused_defines.py
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Those are in the correct order. 
The .Net string method is local-culture aware and does not sort by strict character codes. In English  Å is sorted before B, even though the character code is miles away. In Norwegian it sorts after Z.       
You can see how it works with 
```
32..255 | foreach-object {[string]::new($_)} | Sort-Object -culture en-gb | ForEach-Object {"$_  "+ [int][char]$_  }
```
try other cultures like no-no

So with your file names. 

```
> "check_cmake_consistency_config.py"  -lt "check_cmake_consistency.py"
True
> "_" -lt "."        # string "_" is before "." 
True
> [int][char]"_" -lt [int][char]"."   #char code for "_" is AFTER char code for "."
False
```

IIRC PowerShell asks .NET for a list of items in the directory, and .NET returns them pre-sorted, and they are not re-sorted by PowerShell.  You could sort by `basename` in this case (`name` is `basename . extension`) 

Note that for some people .NET sorting where `A`, `Á` , `a` and `á` coming before `B` and `b` is _looks wrong_ and `A` and `B` should be in one place and `a` and `b` in a second and `á` somewhere else.  For most people, most of the time the localized .net way is better, but for some of us, seeing it _not_  in strict ASCII order induces something like sea-sickness

**Comment by mklement0** [comment]
.NET's sorting behavior on Windows _changed_ with .NET 5's move to cross-platform, ICU-based internationalization, as described in [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu).
PowerShell v7.1+ is based on .NET 5+

Therefore, the sort order of `_` vs. `.` is now different relative to _Windows PowerShell_ (based on .NET Framework, which uses Windows-specific NLS sorting rules), and explains your experience:

```powershell
# WinPS:    -> '.', '_' 
# PS v7.1+: -> '_', '.' 
'.', '_' | Sort-Object
```

In PS Core, `Get-ChildItem` performs its own sorting on all platforms, using case-insensitive current-culture sorting (as `Sort-Object` does by default): 
https://github.com/PowerShell/PowerShell/blob/1f02772fd97fea7395fbb7b68e2befd5790db392/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L1632-L1633.

**Comment by MartinGC94** [comment]
> .NET's sorting behavior on Windows _changed_ with .NET 5's move to cross-platform, ICU-based internationalization, as described in [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu).

Neat. From that article it seems you can see an environment variable to revert this change in behavior:
![image](https://github.com/PowerShell/PowerShell/assets/42123497/b2c9758d-1829-4cd0-b028-f9fe2f4d780e)

Of course you should be careful about setting this because it affects more than just sorting but it's good to know that users have some control over this.

**Comment by rboxman** [comment]
@mklement0 Indeed! Wooo! Thanks for that link. I'm just going to modify the pwsh runtime config to use `"System.Globalization.UseNls": true,` which seems to work.  I can probably move on from using pwsh 7.0.x now since that was the last series that was sane.

Finally, tab-completion order that makes sense!

What a bone-headed decision this is.  Doesn't align with what Explorer shows.  Doesn't align with what Linux shows in their UIs or cmd lines. I hope they never drop this Nls option.

**Comment by mklement0** [comment]
Thanks, @MartinGC94, good to know.
It's implied by your screenshot, but let me spell it out: the environment variable was must be defined _before_ PowerShell is launched to be effective.

Glad to hear the link helped, @rboxman.

Do note that by configuring PowerShell with the NLS opt-in you'll fundamentally change how string sorting works in your session, along with other behaviors, as @MartinGC94  notes (the areas are affected are listed near the top of [.NET globalization and ICU](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu).

> What a bone-headed decision this is. Doesn't align with what Explorer shows.

I suspect it wasn't so much an explicit decision on the PowerShell side but an accidental fallout from the change in .NET (though it sounds like PS Core did exhibit the `_` before `.` behavior from the beginning on Unix, where globalization was always ICU-based).

* File Explorer, as an unmanaged application, still uses NLS, and additionally has custom-sorting logic for numbers embedded in file names even without fixed-width padding.

*  On Unix platforms, the picture is inconsistent (assuming `en_US.UTF-8` as the locale - NOT something like `C.UTF-8`):
   * On Ubuntu (Linux): `ls` _does_ behave like PS Core (`_` before `.`)
   * On macOS: `ls` does _not_.
   * Curiously, on _both_ platforms, the native `sort` utility places `.` before `_` -  I would expect all native utilities to use the same  ICU libraries as .NET

**Comment by rboxman** [comment]
The WSL2 variant of Ubuntu seems to be using `C.UTF-8` by default which is what my comparisons were against.

**Comment by mklement0** [comment]
@rboxman, yeah, that is a very unfortunate default - explicitly warned against in [StringComparer.CurrentCultureIgnoreCase](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparer.currentcultureignorecase), for instance -  given that it _lacks  support for case-insensitivity_ on Linux (but not on macOS, unlike what the linked topic claims) and seemingly always performs _ordinal_ (code point-based) comparisons.

E.g., `Write-Output Z a z | Sort-Object` - which normally yields `'a', 'Z', 'z'` - then yields  `'Z', 'a', 'z'`

**Comment by mklement0** [comment]
My bad, @rboxman: `ls` on Linux does place `.` before `_`, after all, even with a proper locale such as `en_US.utf8` - my tests must have been flawed.
The following command - which must be run from Bash - demonstrates this:

```sh
# -> 
#  a.b
# a_b
LANG=en_US.utf8 sh -c 'mkdir -p /tmp/$$ && cd /tmp/$$ && touch a.b a_b && ls -1 && rm -r /tmp/$$'
```

As noted, I'm mystified by different sorting behavior also occurring with `sort`, as I would expect the same ICU libraries to be used both by the  native utilities and .NET.

Another point of interest is that if a "C" or "POSIX" locale is in effect (as reflected in `locale`), .NET _falls back to the the `en-US` .NET culture_ (as reflected in `[cultureinfo]::CurrentCulture`, meaning that .NET APIs and PowerShell cmdlets - unlike native utilities - are _not_ affected by the lack of case-insensitivity support.

**Comment by jhoneill** [comment]
Since @kilasuit  has marked this as resolved I've removed the needs-triage flag. 
@rboxman  please say if you're unhappy with either.

**Comment by rboxman** [comment]
Yeah, as long as the NLS option remains available to pwsh it's fine and you can probably close this issue.

**Comment by jhoneill** [comment]
@rboxman   Thanks. The bot will mark this closed after a 24 hours of inactivity.
