### ISSUE TITLE
Meta issue: How/where should complaints about working-group members be lodged?

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19730]
### Summary of the new feature / enhancement

The [Code of Conduct](https://opensource.microsoft.com/codeofconduct/)  (understandably) only _broadly_ defines unacceptable behaviors; e.g., "Disruptive behavior".

It also states:

> We encourage all communities to resolve issues on their own whenever possible.

In that vein: 

The responsibilities of working groups are laid out [here](https://github.com/PowerShell/PowerShell/blob/master/docs/community/governance.md#working-groups-wgs) and [here](https://github.com/PowerShell/PowerShell/blob/master/docs/community/working-group.md).

Resolving complaints in the context of PowerShell's working groups seems like something that should be handled on a community (repository) level, yet the linked documents do not define a process for that - all there is are DOs and DON'Ts, and the following admonishment:

> It's worth noting that Working Group members who repeatedly speak on behalf of the Working Group without consensus, they may be censured or removed from the team.

Therefore:

 * If a community member perceives inappropriate behavior on the part of a working-group member, how can a complaint be lodged? 
   * Raise a separate issue here?
   * @-mention a specific user designated as an arbiter / point of first contact in the context of the issue at hand?
   * Send an email to a yet-to-be-announced  _working-group/community-specific_ email address?

**Comment by mklement0** [comment]
As a test case, I'm self-reporting this comment as "Abuse" to the repository maintainers.

Arguably, the same technique could be used to report a specific _issue_ or a specific _post_ on an issue with respect to perceived violations of a working-group member's mandate (but you cannot report a _user_ this way, as users can only be reported to _GitHub_, not the repository maintainers).

However, the fundamental problem is that _no context can be provided_ when you do that, so I don't think it is a solution to this problem.

**Comment by SteveL-MSFT** [comment]
Yes, this got reported as Abuse, so certainly I would recommend using that existing feature in GitHub.  For this topic itself, I'll bring it to the attention of all the WGs.

**Comment by kilasuit** [comment]
So I think this is perhaps more a discussion than an issue, but lets leave as is for now as can always convert it later if needed at all.

However this is a difficult one due to many missing features in the functionality that GitHub provides that could make this much easier not just for us but other communities too (which is something I have been thinking about for a many years now)

This is especially true with missing access depending on where what permissions you have to the repo & organisation as this restricts access to certain features (I think by default in GitHub) that could potentially help 
 - `team @ mentions` - which as it stands I don't think community members or WG Members from the community can use these - only those as part of the PowerShell Organisation can use them.
 - as you mentioned the Abuse functionality is as basic as it possibly could be & isn't able to be amended to a custom process (I don't think )
- we could look at using another issue template for this (but I'm not really a fan of that)
- we could point to a dedicated form for this external to GitHub
- we could extend the features of the bot that @SteveL-MSFT and team have built to add some reporting functionality 
- as mentioned we could set up a dedicated email for this too

All in all there are loads of possible ways forward from a technical perspective, however I do think that's something collectively a decision will get made once there's been a wider discussion here.

Having managed communities (public & company internal) before I'm not a fan of any form of public comments being made where there is perhaps a clash between 2 or more people, where at all possible. Especially in forum feature like communities like this. This is because it can be very easily perceived by those on the receiving end to be a pile on, which can is very likely to lead to WG Members  & those from the community deciding to step back from interacting here, which we really don't want. It's also easy for people to get defensive and ideally we don't want issues littered with lots and lots of back and forth kinda comments like that where at all possible, especially as hiding/moving/deleting them is much more work for the team & not some thing that I currently can do & personally I don't think it's fair to have to rely on an already stretched PowerShell team to do this. 
 
I'd sorta like this one if GitHub had a way of private messaging on the platform for those that allowed that functionality but it would need to be a PM and not just an @ tag
 > @-mention a specific user designated as an arbiter / point of first contact in the context of the issue at hand?

So perhaps this or a form, is the next best solution. Personally a form makes more sense than a dedicated email address
> Send an email to a yet-to-be-announced working-group/community-specific email address?

As it stands I don't think any external to Microsoft WG Members will get any abuse reports, & may even only be @SteveL-MSFT that currently gets them. 

A slight off topic for the issue detail but closely aligned topic would be that we could do with a better process all together for dealing with similar issues that may be raised between community members (whether or not that includes WG or PowerShell team members as we are all members of this community at the end of the day) this should also be similarly managed as to ensure consistency in process.

Hope to see more input from others across the WG's soon enough.

**Comment by doctordns** [comment]
There is a balance to be struck here. Creating an all-singing, all-dancing abuse policy/process will take work. And, in my experience, barrack room lawyers will just find a way around it - leading to more process, Repeated ad nausea.

I believe ALL the posters here are responsible adults and not internet trolls. As such, some of us may get a little imprecise in our grammar but this is not really abusive. I have posted in the past where the tone of my comment was not well received. A quick heads-up was all it took to fix the language.

At the same time, abuse is in the eye of the beholder. Just because YOU are offended may be YOUR problem not the posters. For example, i once attempted to explain why I thought a proposed parameter name was bad - in some parts of the world, the proposed name had unfortunate biological interpretations and I explained why in as polite and refined language possible. Yet, my comment was flagged as abuse. NO idea why someone thought that an explanation was abusive.  So not all reports of abuse really are abuse.

Do we really need a formal, long-winded abuse policy? What is the harm here and is there really sufficient "abuse" to warrant the work?

**Comment by mklement0** [comment]
@doctordns, this is issue isn't about cases where someone gets _offended_ - for that, reporting a Code of Conduct violation is sufficient.

Instead, it is about _perceived violations of a working-group member's mandate_, such as the example quoted from the working-group charter document quoted in the initial post.
That is, potentially inappropriate behavior by a working-group member in the _specific context of acting as such_. 

It is for the cases when resolution through dialogue - which should indeed always be attempted first - end up _not_ being possible.

All this issue asks for is for an officially established way to lodge such complaints.

The [approach above](https://github.com/PowerShell/PowerShell/issues/19730#issuecomment-1574349309) - despite its awkwardness - could be _one_ way of dealing with it: post a comment with context for the complaint, then self-report _that_ comment as "Abuse" (for a want of a more appropriate category) to the _maintainers_.

However, the issues, as pointed out by @kilasuit,  are:

* It is a very _public_ way of lodging a complaint, which not everyone may appreciate.

* It only goes to the repository _maintainers_, which - unless they do feel they should be the arbiters themselves (a question to be answered too: who will be the arbiters?) - burdens them with contacting others.

**Comment by mklement0** [comment]
@doctordns 

> I believe WG members can and should post their views here.

I am genuinely curious: What makes you think that this issue is about preventing WG members from _posting their views_?
It it is certainly not what I ever meant to express or imply.

> It's also useful for members to help to reduce the number of issues the WG ends up considering.

That is fine and helpful in general when it comes to cases such as duplicates and answered questions or even - after a respectful and constructive discussion - a user of their own volition withdrawing a feature request.

It is _not_ fine when it comes to unilaterally trying to sink a feature request (or at least taking shortcuts that lack transparency), for instance.

It is also not fine when WG members _block_ community members, as it robs them of the ability to respond / react to those members' posts / comments.

> I remain of the view we do not need a formal set of words.

I'm not sure what you mean by _formal set of words_, as I didn't ask for wording to be changed.
This issue asks for a _complaint and complaint-resolution procedure_ - or did you mean to say we don't need _that_?

> possibly after contacting the WG member directly first.

As noted, the premise of this issue is to handle cases where one-on-one resolution wasn't possible.

>  just reach out to the other WG members

Please elaborate on what _reaching out_ means. Publicly, by @-mentioning? Look up who the members are, and @-mention them one by one?

More importantly, we're talking about procedural matters that aren't specific to _one_ particular WG, so - at least as a last resort - there should be a way to have a complaint discussed at the overall WG governance level.

> a long, involved process

The aim is to _streamline_ the process, so that it doesn't have to be _improvised_ - it is the latter that probably makes for a longer and more laborious process.

---

If the consensus here ends up being that no specific procedure is needed, 
I'll go with the post-a-public-comment-with-the-complaint-and-report-that-as-abuse-to-the-maintainers approach, but I think it is suboptimal and can lead to strife.

**Comment by jhoneill** [comment]
@doctordns , @SteveL-MSFT  @kilasuit  

I have the power to add and remove tags from issues. ( and to close them)  In a previous issue I felt discussion had run its course, and removed the "needs triage" tag and asked if owner would close it.   @mklement0  likes to argue with everything I say so took umbrage at this and saw as my abusing my powers and created this (now 2000 word) issue to discuss that and - in my view as an indirect attack on me personally, plus a second one on the use of the needs triage tag (we have >3000 open issues, 1/4 of which apparently  have not be triaged and that needs attention), plus a large diversion in yet a third thread. 

**It would serve everyone's interests if this were brought to a close.** If people want to post extensively and enjoy the debate sending them elsewhere to do so seems heavy handed, but there is a point where it becomes disruptive and disrespectful of others' time. Part of the initial beef was I only take things to the WG which I think are worth the time of it's members. I took the trouble to say why. @doctordns  has now brought that issue to the WG to say he's opposed to doing it, and  I'm also opposed to doing it but we _can only close the issue_ by having half a dozen people make it one of the dozen or so things they talk about in a month. An unwillingness to close a debate has wasted a lot of other peoples time and prevented discussion of something more useful. When doing that shades into disruption and disrespect we have a code of conduct for it.  If work group members (including but not limited to me) seem high handed or too combative from time to time people should be able call us on it.   

It seems to me this is looking to give more structure to the complaint process than other workgroup activity, and so far the only wish to complain we know of has been @mklement0 's against me.  He and I are both stubborn people, we'll both argue until everyone else gives up, either of us could be charged with acting like this is our own personal web site and we should stay away from each other as much as practicality allows.

**Comment by vexx32** [comment]
> (...) I think a complaint process is worth defining, especially to avoid (extended) public spats.
>
> If no one ever ends up having to use it - then all the better.

I agree. 

A process that includes no formal accountability is a process that contains unlimited potential for abuse, discrimination, and general unpleasantness.

I don't know what to say to some of the comments in this thread, other than that it feels deeply unpleasant to be so against accountability.

**Comment by doctordns** [comment]
> A process that includes no formal accountability is a process that contains unlimited potential for abuse, discrimination, and general unpleasantness.

True and I am not suggesting that. We already have a procedure - if someone is unhappy with how a WG member or a WG decision - the correct procedure is to raise it to the PowerShell committee. 

What I am against is a long involved process.  And a process that is knee-jerk retaliation to comments a poster felt unhappy over. We are all volunteers here trying to do the best for PowerShell. Making a mountain out of a mole hill just is not helpful.

**Comment by mklement0** [comment]
@doctordns 

> We already have a procedure - if someone is unhappy with how a WG member or a WG decision - the correct procedure is to raise it to the PowerShell committee.

If that were the case, shouldn't this have been your _first_ comment here?

The only context in which the committee is mentioned in the [WG-definition document](https://github.com/PowerShell/PowerShell/blob/master/docs/community/working-group.md) is in a matters of _due course_ (appealing WG decisions) - this is very different from what I'm asking here.

If I were to guess, the committee wouldn't be too happy to be pinged in matters of _conduct complaints_.
Also, @SteveL-MSFT - who has already commented on this issue - would have mentioned it, and t would still be a _public_ way of complaining.

> What I am against is a long involved process.

Asking for a _complaint mechanism_ (and not even about how such complaints should be _resolved_) is different from a "long involved process", so this strikes me as a straw man.

> knee-jerk retaliation to comments

Asking for an official mechanism, to be followed by everyone in the future, is the opposite of "knee-jerk"

Characterizing the desire to lodge a complaint as "retaliation" is both incorrect and inappropriate.

> comments a poster felt unhappy over.

The specific incident that inspired me to ask for a complaint mechanism is irrelevant, but, for the record: it was my perception of an inappropriate _action_, not comments - though the comments _accompanying_ the action do in my mind constitute a problematic understanding of the duties of a WG member.

Either way, please don't dismiss a complaint based on [specific reasoning](https://github.com/PowerShell/PowerShell/issues/19680#issuecomment-1561639220) as a "comment someone felt unhappy over".
You may not _agree_ with the reasoning, but that's a different matter.

> We are all volunteers here trying to do the best for PowerShell.

Thinking that volunteer status somehow absolves WG members from having to act within their mandate is a non sequitur.

> Making a mountain out of a mole hill just is not helpful.

This is another straw man.

We're not talking about a specific issue here, we're talking about a general mechanism for lodging complaints regarding conduct in a specific context, so that the relevant people are notified and can adjudicate the complaint.

Opposing the very existence of such a mechanism indeed betrays a troubling indifference to accountability.

**Comment by doctordns** [comment]
> Opposing the very existence of such a mechanism indeed betrays a troubling indifference to accountability.

Not understanding we have a mechanism and that we do have accountability is equally troubling.

**Comment by mklement0** [comment]
@doctordns, my previous comment argues in detail why we - by all appearances - we do _not_ have a mechanism.
Is there something that strikes you as incorrect about these arguments? If so, what?

Do you still think that @-mentioning the committee is the right mechanism to address complaints about WG-member _conduct_ relative to their _mandate as a WG member_ (as opposed to using this to appeal technical decisions that were made based on regular, proper conduct)?

If so, where is this mechanism documented?
Does anybody else know about this / has the same interpretation as you?

Do you think the committee is the right body to deal with matters of _conduct_?

**Comment by jhoneill** [comment]
> A process that includes no formal accountability is a process that contains unlimited potential for abuse, discrimination, and general unpleasantness.
> 
> I don't know what to say to some of the comments in this thread, other than that it feels deeply unpleasant to be so against accountability.

@vexx32  I don't think **anyone** is against accountability. 
As it stands someone responsible has had occasion to ask me to think twice about being as combative as I sometimes appear in posts. However despite wide awareness of why the OP is asking for a formal mechanism for him to abuse me (I removed the triage tag from an issue I considered to be triaged, and understood that the WG- tags are for "will go on the agenda of the WG" so didn't add a WG tag)  no one has said "What happened with the tags was wrong, you need to do this in future", to me or as a general reminder  nor censured me for the calls I made. 

Clearly if people cannot be held to account for their behaviour, bad behaviour will go unchecked. Multiple people are now calling for one of the non-WG-member posters here to be held account for his disruptive, disrespectful/abusive and generally unpleasant behaviour.  It's simple - if any post looks falls under the headings you named, click the... on the title bar, chose, Abuse, Spam or Off Topic and click "report to repository admins". If anyone linked to the product team is found to behave in a way which is bad for the community and/or the product they will be dealt with. If a group closes ranks to protect its own, the committee is the backstop.  IIRC I explained to the owner of the issue in question what had been done, that could have been reported. Incidentally the complainant is not the owner of issue that was declined, as the person he is attacking, it's probably better not to post my assumptions about motivations.  

We certainly can do more things to be seen to be accountable. However as one of the cmdlets working group said when we met this week, we don't want 200 pages of legalese. The working groups are not very formalised and we need to do the right thing AND keep a sense of proportion. IIRC you're on another WG yourself, if a troll wants to subject you or me to "abuse, discrimination, and general unpleasantness" we should be wary of giving them tools to do so. Mechanisms to put people on the spot will be abused by malcontents as well used by those who have been wronged. I'd put what we should do as Be accountable, be sensible, be mindful of trolls.

**Comment by mklement0** [comment]
* Any references to _specific incidents_ as well as  any musings about _potential abuse_ of a formal complaint mechanism are irrelevant and a distraction.

* The only thing that matters is: 
  * WG members are accorded powers to be exercised in accordance with their mandate.
  * If they exercise their powers _inappropriately_, there has to be a mechanism to hold them to account.
  * Because there currently is none, this issue asks for one to be established.
  * Regarding future complaints lodged via this yet-to-be-established mechanism:
     * If they're found to be frivolous, they can be dismissed.
       * The complainant should be provided with an explanation to that effect.
     * If they're found to be substantive:
       * The WG member(s) named in the complaint should be censured; if no shared understanding can be reached, they should be removed, in accordance with the statement already contained in the WG document with respect to a _speific_ transgression:
          * > t's worth noting that Working Group members who repeatedly speak on behalf of the Working Group without consensus, they may be censured or removed from the team.
       * Independently, Ii the behavior at issue wasn't sufficiently clarified in the [WG document](https://github.com/PowerShell/PowerShell/blob/master/docs/community/working-group.md), that document should be amended.

**Comment by doctordns** [comment]
@mklement0 more words but I am in too much pain to really read then and parse them (I threw out my back and in an in a lot of pain). But this looks like a continuation of your trolling.

If you want to take this further, then rather than asking questions, get off your butt and issue a PR for updated terms of reference. ALLL you seem to do Mark is complain, complain, and complain. And I am tired of it.  Instead of rasing a trolling Meta-issue, why not actually write down your thoughts on how WG members should behave and issue a PR. j

IMHO, this issue does not need triage. It is just a continuation of your trolling.

**Comment by mklement0** [comment]
If it wasn't clear to begin with that a complaint process is needed, the grim irony is that the actions by @doctordns and @jhoneill both here and in the linked issue have made that need painfully obvious.

The linked issue, in addition to the original complaint, now contains several others. They ware worded in a manner suitable for easy adaptation and inclusion as additional DON'Ts in the [WG section of the governance document](https://github.com/PowerShell/PowerShell/blob/master/docs/community/governance.md#working-groups-wgs).

I just noticed that the [following section](https://github.com/PowerShell/PowerShell/blob/master/docs/community/working-group.md#reporting-working-group-members-abuse) was recently added to the WG document:

> #### Reporting Working Group members abuse

> Working group members are individuals and in many cases volunteers.
There may be situations where a working group member might exhibit behavior that is objectionable,
exceed the authority defined in this document or violate the [Code of Conduct](../../CODE_OF_CONDUCT.md).
We recommend to report such issues by using the [Report Content](https://docs.github.com/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam) mechanism to bring it to the attention of the maintainers to review.

While I welcome this addition, my concern is still that the Report Content mechanism is too abstract: "Abuse" is the only applicable category, and no context can be provided.
The only way to provide context is via a _public_ comment - and we've seen what that leads to.

@SteveL-MSFT, please clarify if you think Report Content is indeed sufficient or whether it's worth continuing this discussion to refine the process. If the former, I'll close this issue.

**Comment by doctordns** [comment]
As ever,  do the work and create a PR. And stop trolling.

**Comment by SeeminglyScience** [comment]
> Also, IMHO, this issue does not need any triage - it is just a continuation of your trolling. And as this issue has been dealt with, I think it can be closed.

@doctordns You're way out of line here and you really need to step away from the conversation.

I've been in my fair share of off the rails discussions with @mklement0, and to be honest in the original issue I think they were equally part of the problem (although I wrote this part without seeing what that thread devolved into. Both you and @jhoneill really need to re-read that thread and think about if you're proud of how you handled the situation).

In this thread though, they've tried very hard to stay off the subject of the original issue and only talk about what was actually missing in our process. Even after other folks keep trying to bring it up, they bring it back to the actual topic. They aren't trolling.

> However despite wide awareness of why the OP is asking for a formal mechanism for him to abuse me

@jhoneill Reporting a comment is not abuse. It does nothing to you **at all** if it's wrong. There's still a human on the other side making decisions.

**Comment by mklement0** [comment]
@SeeminglyScience:

* Let me state unequivocally that I greatly appreciate your comment.

* Let me _briefly_ and as _impersonally as possible_ address your "they were equally part of the problem" comment - and there is definitely no need to discuss this any further _here_: I encourage anyone who's interested in what happened to read the thread in the [original issue](https://github.com/PowerShell/PowerShell/issues/19680) _in full_.
   * I was (and will continue to be) _persistent_: As long as I think there are _counterarguments to be made_, I will make them: my aim is always to reach a _shared understanding_ or, absent that, to reach a point _where the remaining disagreement is expressed as clearly and succinctly as possible_.
   * As long as actual _arguments_ are made, _this has to be acceptable_. It is entirely unrelated to "trolling" or other improper conduct. The _mere fact_ of continuing to respond to others' posts _with arguments_ should not and must not be misconstrued as a personal attack or an attempt to be disruptive.
   Such a stance is _especially_ inappropriate if taken by WG members.

   * Anyone is free to decide when to _exit_ a debate, based on when _they_ think it has run its course and additional exchanges would be unproductive.

**Comment by SteveL-MSFT** [comment]
Reports of abuse should use the GitHub `Report Comment` feature.  The Maintainers (who are notified of the reports) will perform initial triage and raise any compelling offenses to the @PowerShell/powershell-committee.  The PS-Committee will review and decide if any violated the Code of Conduct.  Note that I have a PR to update how we enforce violations https://github.com/PowerShell/PowerShell/pull/19810.

**Comment by mklement0** [comment]
To bring closure to this post:

A "Code of Conduct Enforcement" section has since been added to [CONTRIBUTING.md](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#code-of-conduct-enforcement), with the following content as of this writing:

> Reports of abuse will be reviewed by the PS-Committee and if it has been determined that violations of the Code of Conduct has occurred, then a temporary ban may be imposed.   
> The duration of the temporary ban will depend on the impact and/or severity of the infraction.   
> This can vary from 1 day, a few days, a week, and up to 30 days.  
> Repeat offenses may result in a permanent ban from the PowerShell org. [sic]


As for the tangentially related issue of many existing issues appearing to be in limbo, raised in #19731,
@kilasuit [has graciously started to tackle the backlog](https://github.com/PowerShell/PowerShell/issues/19731#issuecomment-1620609705), and I've seen
a new label, [`WG-NeedsReview`](https://github.com/PowerShell/PowerShell/labels/wg-needsreview),  appear, which is encouraging.

**Comment by mklement0** [comment]
Lastly (possibly in more than one sense), let met state the following, on a semi-personal note:

Presumably based on my comments in the [aforementioned issue](https://github.com/PowerShell/PowerShell/issues/19680), I was banned for 30 days, i.e. the _maximum_ period - save for a _permanent_ ban.

The ban was announced with the following wording:

>  Repeated patterns of disruptive behavior

No other justification was provided.
You can read the full email pronouncing the ban, as well as my response, [here](https://www.dropbox.com/s/qyplqxolf1bvyc5/Re%20PowerShell%20GitHub%20Code%20of%20Conduct%20violations.pdf?dl=0).

As far as I'm concerned, my [previous arguments](https://github.com/PowerShell/PowerShell/issues/19730#issuecomment-1585941143) stand - the fact that some of the _arguments_ that I made could have been packaged more graciously notwithstanding.

I'm aghast at this - argument-free - ruling that was handed down, and I contend that anyone  invested in this community should be gravely concerned about how @PowerShell/PowerShell-Committee exercises their powers with respect to stifling speech in this repository.
