### ISSUE TITLE
Distribution Support Request - PowerShell is not published to the RHEL 9 Repo. Please add it: https://packages.microsoft.com/rhel/9/

### ISSUE THREAD

**Issue by mbrownewu** [PowerShell/PowerShell#19748]
### Name of the Distribution

Red Hat Enterprise Linux

### Version of the Distribution

9

### Package Types

- [ ] Deb
- [X] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

x86_64

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by kilasuit** [comment]
Also requested in #19672

**Comment by mbrownewu** [comment]
Any idea when this might happen?

It doesn't make PowerShell for Linux very enterprise when it's not in the Repository that can be easily updated with Red Hat Satellite.

**Comment by theJasonHelmick** [comment]
This request is being tracked in #17548
