### ISSUE TITLE
RegEx Pattern works on regex101.com but does not work with select-string -pattern

### ISSUE THREAD

**Issue by B-Art** [PowerShell/PowerShell#19754]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$vssadmin =  vssadmin list writers
($vssadmin | Select-String -Pattern "(?msi)^Writer name: (?'writer'.*)\r?\n *Writer Id: (?'id'[^:]*)\r?\n *Writer Instance Id: 
(?'instance'[^:]*)\r?\n *State: (?'state'[^:]*)\r?\n *Last error: (?'err'[^:]*)\r?\n$" -AllMatches ).Foreach{$_}

### Expected behavior

```console
Named groups of matches. writer, is, instance, state and err.
```

### Actual behavior

```console
Empty string
```

### Error details

```console
No error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

(https://regex101.com/r/Itarw8/1)

**Comment by krzydoug** [comment]
I think your regex has multiple issues. I don't have time at the moment to really dig into it, but wanted to offer an alternative approach.

```Powershell
switch -regex ($vssadmin){
    "^\w.*'(?<Name>.*)'$" {$ht = @{Name = $matches.name}}
    "^\s+(?<Name>\w[\w\s]*): (?<Value>.*)$" {
        $ht.Add($matches.Name,$matches.Value)
        if($matches.Name -like '*err*'){
            [PSCustomObject]$ht
        }
    }
}
```

**Comment by iRon7** [comment]
I suspect that `$vssadmin` is not a multiline (here) string but `$vssadmin -is [array]`
Possible solution:
```PowerShell
$vssadmin = vssadmin list writers |Out-String
```

**Comment by B-Art** [comment]
> I think your regex has multiple issues. I don't have time at the moment to really dig into it, but wanted to offer an alternative approach.
> 
> ```powershell
> switch -regex ($vssadmin){
>     "^\w.*'(?<Name>.*)'$" {$ht = @{Name = $matches.name}}
>     "^\s+(?<Name>\w[\w\s]*): (?<Value>.*)$" {
>         $ht.Add($matches.Name,$matches.Value)
>         if($matches.Name -like '*err*'){
>             [PSCustomObject]$ht
>         }
>     }
> }
> ```

I miss some output with this code

**Comment by jhoneill** [comment]
Multiple problems with the regex.  which I've fixed below, @iRon7  had the main problem though. 

```
$Pattern = "(?msi)" +
           "^Writer name: (?'writer'[^\r\n]+)"           +  #  select after label to the end of line
           "\s*Writer Id: (?'id'[^\r\n]+)"               +  #  skip newline and spaces at the start,
           "\s*Writer Instance Id: (?'instance'[^\r\n]+)"+  #  and repeat
           "\s*State: (?'state'[^\r\n]+)"                + 
           "\s*Last error: (?'err'[^\r\n]+)"
vssadmin list writers | Out-String | 
        Select-String -Pattern $Pattern -AllMatches | ForEach-Object matches |ForEach-Object  {
            $_.groups | where-object name -ne 0  | 
                foreach-object -begin {$ht=@{}} -process {$ht[$_.Name] = $_.value} -end {[pscustomObject]$ht}
        }
``` 

<img width="891" alt="image" src="https://github.com/PowerShell/PowerShell/assets/16209593/a98aeeec-8120-4d3e-b598-c8b64f385267">

**Comment by mklement0** [comment]
On a general note, @B-Art:

* With respect to regexes, PowerShell is just the facilitator: the _.NET regex engine_ does all the work.

* Unless you have reason to believe that there is a problem with _how PowerShell facilitates this access_ (which would require showing a PowerShell statement that behaves differently from the equivalent direct .NET API call), a potential bug with respect to regex processing should be reported at https://github.com/dotnet/runtime/issues (I don't think there is one here).

  * A notable difference between PowerShell-mediated regex functionality vs. direct .NET API use is that PowerShell uses case-_insensitive_ regexes by default.

* With respect to  using regex101.com  - a great tool, to be sure - for PowerShell, there are pitfalls:
  * It assumes _different defaults_ (even if you choose the NET (C#) flavor): notably, the `m` (`Multiline`) option is _on_ by default, and `i` (`CaseInsensitive`) is _off_ by default; the `g` (global) option, which has no direct .NET equivalent is _on_ by default, but it doesn't apply to `match` or `switch -Regex`, for instance.
  * It assumes (verbatim) C# string-literal syntax, requiring escaping of `"` chars. as `""`
  *  See https://github.com/firasdib/Regex101/issues/1838 for a request to support a PowerShell-specific flavor that would eliminate these problems.
  * However, two pitfalls will remain:
      * The site only supports a _single, multiline input string_ to test against.
        * This notably contrasts with PowerShell often reporting lines as a stream of _multiple, individual (newline-free) strings_, as when you use `Get-Content` (without `-Raw`) and when you process output _from external programs_, such as `vssadmin.exe` in your case.
         * As @iRon7 has pointed out, piping to `Out-String` is the simplest solution for external programs; for `Get-Content`, it is `-Raw`.
         * Also note that `Select-String`, when given a _file_ (path or file-info object) as input also searches _line by line_; searching _across_ lines requires an idiom such as `Get-Content -Raw ... | Select-String ...`

    * Pasting multi-line strings as subject strings (field "TEST STRING") invariably converts CRLF (Windows-format) to LF (Unix-format) newlines.

**Comment by B-Art** [comment]
@mklement0 
Thank you for your excellent explanation.
I am aware that lost of functionality in PowerShell leans on .Net.
For instance -Replace is completely different to .Replace(,) I know.
-Replace can use Regex while .Replace(,) cannot.

I use PowerShell almost every day and I will keep on using it.

Again, thanks for your reply.
