### ISSUE TITLE
Meta Issue: can't explicitly search for a cmdlet name in an issue

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#19753]
### Summary of the new feature / enhancement

Because of [`#3080` Searching difficulties with hyphens (-) and periods (.)](https://github.com/craftcms/cms/issues/3080) and due to the fact that PowerShell uses a [verb-noun](https://learn.microsoft.com/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands) pair for the names of cmdlets, it is quite difficult to narrow an issue search to a meaningful cmdlet name, e.g.:
```
Write-Output in:title
```
Results in 8+25=33 issues where only 19 issues actually have `Write-Output` in the title.
(not even mentioning here to do a wide general search on all comments in an issue)

### Proposed technical implementation details (optional)

Not sure whether I missed some documentation or workaround for this...
Anyways, creating labels for each known cmdlet (as `Add-Member`, `Write-Host`, ...) and automatically add that cmdlet label when recognized in a comment might help here.

**Comment by doctordns** [comment]
is this something the PowerShell team do much about? Or is this a challenge for GitHub?

**Comment by iRon7** [comment]
@doctordns,

> is this something the PowerShell team do much about? Or is this a challenge for GitHub?

Good question, I think it depends how you look to it.
* if you see it as GitHub bug/enhancement, it likely will be qualified as "by design" (hyphens aren't indexed) and never be resolved.
* if you see it as configuring and customizing GitHub, it might be something for the GitHub owner (the PowerShell team) to pick up knowing that there apparently exists already a `msftbot` (no clue what it is capable of).

FYI, there are currently nearly 300 `Microsoft.PowerShell` cmdlets: 
`(get-command |Where-Object Source -like Microsoft.PowerShell.*).Count`

**Comment by iRon7** [comment]
Opened new `issues and projects` discussion here: https://github.com/orgs/community/discussions/58606

**Comment by kilasuit** [comment]
@iRon7 I have moved this to Needs Investigation as I am hoping this is something that is globally off but can be turned on at org/repo level and have reached out asking about this. Will report back if/when I hear further

**Comment by martinwoodward** [comment]
Does it not work when the cmdlet name is provided in quotes?  Such as ["get-command"](https://github.com/search?q=repo%3APowerShell%2FPowerShell+%22get-command%22&type=issues)

**Comment by kilasuit** [comment]
>Does it not work when the cmdlet name is provided in quotes? Such as ["get-command"](https://github.com/search?q=repo%3APowerShell%2FPowerShell+%22get-command%22&type=issues)

Commented on https://github.com/orgs/community/discussions/58606 with more details as that's actually the right place for the GitHub team to look at going forward as this is wider than just for us as I was getting what I would call getting some results as expected and then partial matches - if this is the case then it may be nice for GitHub to split these as exact/partial match and allow additional search parameters to control this behaviour

regarding this comment from @iRon7 
> if you see it as configuring and customizing GitHub, it might be something for the GitHub owner (the PowerShell team) to pick up knowing that there apparently exists already a msftbot (no clue what it is capable of).

We may be able to look adding some of our own tooling that on issue creation do a lookup and have a bot post a "did you mean one of these existing issues" however they almost always cause more noise than are a real help, but that's up to @SteveL-MSFT and team to really decide on whether they want to do that or not. I would be happier to see that added natively to GitHub but it would be very hard to get right without a lot of customisation options.

I've done all the investigation in this that I can for now but plan to come back to this to see

One point too add is that whilst `in:title` searches are worthwhile these also could miss issues too as not all the issues are well named

**Comment by iRon7** [comment]
@kilasuit.

> We may be able to look adding some of our own tooling...

The thing that I had in mind is (presuming that the `msftbot` can be triggered on every issue update), that it scans the current issue (excluding fenced code blocks?) for known cmdlet names and automatically adds a comment (or updates an existing comment) like the following comment suggestion:

**Comment by iRon7** [comment]
## Cdmlet tag handles:

> [`Get_Command`](https://docs.microsoft.com/en-us/dotnet/api/Get-Command) [`Write_Host`](https://docs.microsoft.com/en-us/dotnet/api/Write-Host) [`ConvertTo_Json`](https://docs.microsoft.com/en-us/dotnet/api/ConvertTo-Json) [`ConvertFrom_Json`](https://docs.microsoft.com/en-us/dotnet/api/ConvertFrom-Json)

The above **cmdlet tags** are for searching issues regarding specific cmdlets. To search for a specific cmdlet in an issue, use a underscore (`_`) instead of hyphen (`-`) (e.g. `Get_Command`)

For more background see: [`#19753` Meta Issue: can't explicitly search for a cmdlet name in an issue](https://github.com/PowerShell/PowerShell/issues/19753) (*or a formal document*).

**Comment by kilasuit** [comment]
I'm not sure that the msftbot which is a wider than PSTeam bot, has that level of customisation, so **if** it were to be done it would need to be a PS built and managed integration and whilst this would be a "very nice to have" it's likely to be hard to prioritise compared to other areas due to the reasons I listed above.

It's a good idea and whilst I can only speak from my experience and for the team, it may be something that was have to revisit regularly to see if GH have improved their searches results via some tuning, which may be back end feasible for them.
