### ISSUE TITLE
Class Constructor Error - Can't Set Variable Values

### ISSUE THREAD

**Issue by aksarben** [PowerShell/PowerShell#19756]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I’m writing a PowerShell class as follows:

```
class FileTransferStatus {

    [System.IO.FileInfo[]]$files
    $totalBytesToTransfer
    $bytesLeftToTransfer

    FileTransferStatus([System.IO.FileInfo[]]$files)
    {
        this.$totalBytesToTransfer = 0
        foreach ($file in $files) {
            this.$totalBytesToTransfer += $file.length
        }
        this.$bytesLeftToTransfer = this.$totalBytesToTransfer
    }
}
```

### Expected behavior

```console
No error message
```

### Actual behavior

```console
Visual Studio Code reports an error on the last line of the constructor, which tries to initialize $bytesLeftToTransfer. The message is:

**Variable is not assigned in the method.**
```

### Error details

```console
The error is from Visual Studio Code during editing, not from running the script.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
This: `this.$totalBytesToTransfer` is not the right syntax. When you want to refer to `this` you use the automatic variable: `$this` which lets you access all the members your class like this: `$this.MemberName`.

**Comment by aksarben** [comment]
“I see, said the blind carpenter,” as he picked up his hammer & saw.

It’s always the little things that get you. I looked at that 10 times and didn't see it.

Thanks for the quick reply.
