### ISSUE TITLE
Package the Ubuntu 16.04 with the snap format

### ISSUE THREAD

**Issue by pharaone** [PowerShell/PowerShell#1976]
Please package the Ubuntu 16.04 in the .snap format. snap packages work of many behind Linux and then have some kind of Linux universal package (they works on arch linux, Ubuntu, Red Hat, Fedora, Gentoo, Debian and others)

**Comment by SRGOM** [comment]
Would love to get this on Arch.

**Comment by rliessum** [comment]
Also make is suitable for 17.04 to stay in line with LTS.

**Comment by KexyBiscuit** [comment]
@rliessum In case you don't know, I'd like to remind that Ubuntu 17.04 is not a LTS version... But PowerShell currently supports non-LTS version of Ubuntu like 16.10.

**Comment by iSazonov** [comment]
@TravisEz13  Should we close the issue?

**Comment by TravisEz13** [comment]
@SRGOM  @KexyBiscuit  the snap package is based on Ubuntu 16.04 (or 18.04 in the future.)  For non-LTS versions, this and the tar.gz is the only package we plan to supply.  For the latest stable release see https://snapcraft.io/powershell or for the latest preview release see https://snapcraft.io/powershell-preview
