### ISSUE TITLE
PowerShell custom classes: Improve the error message for ineffective attempts to access instance properties via their declaring variables

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#19767]
### Summary of the new feature / enhancement

Consider the following custom `class`:

```powershell
class Foo {
  $Foo = 'bar'
  [string] Get() {
    # !! Mistaken, but understandable attempt to access the variable that declares property .Foo
    return $Foo
  }
}
```

As @jhoneill notes in https://github.com/PowerShell/PowerShell/issues/19757#issuecomment-1580547278: 

> The class doesn't make the "variable" accessible in the method. **In fact, the meta lesson here is scopes don't inherit into methods.**

That is, for the above code to work, `return $Foo` must be `return $this.Foo` - which isn't _intuitively obvious_ (despite being _documented_).

The current error message provides _little guidance_ as to what the problem may be:

```none
Variable is not assigned in the method.
```

### Proposed technical implementation details (optional)

Improve the error message with a hint that instance properties must be referenced as (wording to be tweaked; I'm being deliberately verbose):

```
Variable is not assigned in the method. 
To reference instance properties, use
$this.<PropertyDeclaringVariableNameWithout"$"Prefix>
```

**Comment by aksarben** [comment]
I think the proposed error message modification is great! Thanks for going the extra mile. I think it will be a great help, especially for PowerShell newcomers.
