### ISSUE TITLE
Cannot implement a PSDriveInfo with custom size because of implementation

### ISSUE THREAD

**Issue by Scal-Human** [PowerShell/PowerShell#19778]
### Summary of the new feature / enhancement

Hello,
The Free and Used properties of the PSDriveInfo (Get-PSDrive) are implemented in TypeTable_Types_Ps1Xml.cs as NoteProperty's.
This prevents any drive implementer to supply its own sizing and stick those properties to filesystem drives only.
I tried providing such properties on a drive (deriving PSDriveInfo), hoping that the "isOverride: false" of the AddMember was for that purpose but with no luck.
FI I am currently implementing multiple drives some of which require such sizing to be shown.

See TypeTable_Types_Ps1Xml.cs lines 109 and 127. I pointed there when creating this isssue but I am not sure it links to it (sorry).
Have a nice day/night,
Scal

### Proposed technical implementation details (optional)

The AddMember('"Free") And AddMember('"Used") could be skipped if the actual implementation type derived from PSDriveInfo already provides those properties.
Alternatively, properties could be implemented in Filesystem-specific PSDriveInfo and not as added NoteProperties which would be a cleaner solution, but I did not find it in the PowerShell code (that's huge, hey ;-).

As workaround, as I already have a "Dimensions" property with multiple possible sizing depending on the type of drive, I will use a custom formatting for the Get-PSDrive.

I am not sure I did it right, despite decades in the field, this is the first issue I fill in.

**Comment by 237dmitry** [comment]
PSDrives is virtual drives, their size is the whole partition size.

**Comment by Scal-Human** [comment]
Okay, and what about a drive that is not filesystem-related which is the case when creating a custom provider ?

**Comment by Scal-Human** [comment]
Okay, found it, using Update-TypeData.
Update-TypeData -TypeName "PSSnapshotDrive.PSLiteDBDrive" -MemberType ScriptProperty -MemberName "Free" -Force -Value { 12.34 * 1GB <# or whatever *> }
Update-TypeData -TypeName "PSSnapshotDrive.PSLiteDBDrive" -MemberType ScriptProperty -MemberName "Used" -Force -Value { 34.56 * 1GB <# or whatever *> }
gives:

Name   Used (GB) Free (GB) Provider         Root                           CurrentLocation
----   --------- --------- --------         ----                           ---------------
LiteDB     34.56     12.34 PSLiteDBProvider C:\Sandbox\PSLiteDBTest.litedb

Thanks, anyway.
Scal
