### ISSUE TITLE
Add support for '\' (backspace) escaped double quotes in double-quoted string literals

### ISSUE THREAD

**Issue by nam20485** [PowerShell/PowerShell#19811]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

## Benefit

TerraForm and its auto-completion library https://github.com/posener/complete are unable to offer autocomplete functionality because of the lack of support for the otherwise-standard '\\'-escaped quotes. This also breaks many other scripts written scripts and commands (e.g. those written for cmd.exe and batch files for one example) that have been written to rely on the standard '\\'-escaped quotes.

### Steps to reproduce

Enter following on the command line:

```shell
PS> "name"=\"value\""
```

### Expected behavior

Command line should accept the string, similar to when using '""' double quote-escaped double quotes or as in other modern shells such as BASH, cmd.exe, and BATCH (.bat) files:

```shell
PS> "name=""value"""
name="value"
```

### Actual behavior

ParseError: Unexpected token 'value\""' in expression or statement.

```shell
PS> "name=\"value\""
ParserError:
Line |
   1 |  "name=\"value\""
     |          ~~~~~~~~
     | Unexpected token 'value\""' in expression or statement.
```

### Error details

```console
Type        : System.Management.Automation.ParseException
Errors      :
    Extent  : value\""
    ErrorId : UnexpectedToken
    Message : Unexpected token 'value\""' in expression or statement.
Message     : At line:1 char:9
              + "name=\"value\""
              +         ~~~~~~~~
              Unexpected token 'value\""' in expression or statement.
ErrorRecord :
    Exception             :
        Type    : System.Management.Automation.ParentContainsErrorRecordException
        Message : At line:1 char:9
                  + "name=\"value\""
                  +         ~~~~~~~~
                  Unexpected token 'value\""' in expression or statement.
        HResult : -2146233087
    CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    FullyQualifiedErrorId : UnexpectedToken
    InvocationInfo        :
        ScriptLineNumber : 1
        OffsetInLine     : 9
        HistoryId        : -1
        Line             : "name=\"value\""
        PositionMessage  : At line:1 char:9
                           + "name=\"value\""
                           +         ~~~~~~~~
        CommandOrigin    : Internal
TargetSite  :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation,
Version=7.3.4.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown,
ExecutionOptions options)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/1829396/59a5fc88-3a85-4141-8fd1-104cf32878e5)

**Comment by kasini3000** [comment]
Let me share some options with you:

----

Write your own powershell tab completion code.
You can refer to: kubectl completion powershell | Out String

----

https://github.com/KaiKorla/TerraformCompletion

----

 Use cloud native powershell commands instead of terraform.
AWS: https://learn.microsoft.com/zh-cn/powershell/module/az.accounts/?view=azps-8.3.0#accounts
Azure: https://docs.aws.amazon.com/powershell/index.html

----

My project Kasini3000 provides many multi cloud consistent powershell scripts
https://github.com/kasini3000/kasini3000

**Comment by MartinGC94** [comment]
PowerShell already includes an escape character (the backtick). AFAIK this was chosen over the more common backslash to make it easier to deal with Windows paths like: `"C:\Windows"`.  
Some may not like it but every time I have to add a Windows path to a JSON file I think about how annoying it is to escape `\` so I've come to appreciate this design choice.

Regardless of how you feel about this design choice, changing it now seems unrealistic. It would be a huge breaking change for practically every script out there that uses a Windows path for anything.
