### ISSUE TITLE
PowerShell 7.3.4 on Windows 7

### ISSUE THREAD

**Issue by Temik007** [PowerShell/PowerShell#19816]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For work it on Windows 7 it's need copy few *.dll from 7.2.0 release
api-ms-win-core-com-l1-1-0.dll
api-ms-win-core-console-l2-1-0.dll
api-ms-win-core-shlwapi-legacy-l1-1-0.dll
API-MS-Win-Eventing-Provider-L1-1-0.dll

### Expected behavior

```console
PowerShell 7.3.4
PS C:\Program Files\PowerShell\7> $PsVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      4

PS C:\Program Files\PowerShell\7>
```

### Actual behavior
Without *.dlls
```console
Unhandled exception
```

### Environment data

```powershell
PowerShell 7.3.4
PS C:\Program Files\PowerShell\7> $PsVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      4

PS C:\Program Files\PowerShell\7>
```

### Visuals

![test1](https://github.com/PowerShell/PowerShell/assets/47690657/d1d16d9a-ed99-4beb-a6b6-a1e0f9ca5996)
![test2](https://github.com/PowerShell/PowerShell/assets/47690657/5a460bed-2355-4ffd-9935-9e201a8027c6)

**Comment by ThomasNieto** [comment]
PowerShell no longer supports Windows 7 as it is out of support.

[PowerShell supported Windows OS](https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.3#windows)
[Windows 7 End of Life](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962)

**Comment by Temik007** [comment]
> 
I know it, just advice on how to make it work

**Comment by kasini3000** [comment]
@Temik007  Powershell fans owe you a ”thank you ！“

**Comment by acoul** [comment]
it worked. thank you so much.

**Comment by greenozon** [comment]
Windows 7 still rocks  even in 2024! :)

![image](https://github.com/user-attachments/assets/5fc0cf23-b26b-40f4-b649-4b5fe563e526)

**Comment by bt4ibwem8** [comment]
@Temik007 
do you know how to make it work also for the 7.4.4 version? Version 7.4.3 works...

**Comment by greenozon** [comment]
@bt4ibwem8  what issue do you observe?
I just got the 744 x64 zip archive, unpacked it on my old good golden Win7 x64 SP1 and... I see 0 issues! amazing

![image](https://github.com/user-attachments/assets/e2d18294-9dbc-4ee2-bab5-21e6d3bcf8bb)

are there any more heavy commands to test out inside pwsh 744 on Windows 7?

**Comment by bt4ibwem8** [comment]
i get this:

![image](https://github.com/user-attachments/assets/a871a187-cc91-406b-90a5-5556893a52a2)

I will try to copy that dll into system32

**Comment by greenozon** [comment]
There is a tool named Dependency Walker
what do you see in your case for pwsh.exe?

here is mine:

![image](https://github.com/user-attachments/assets/eec4d25c-739b-4927-a92a-3dc2ffdf2913)

**Comment by bt4ibwem8** [comment]
![image](https://github.com/user-attachments/assets/0ee30396-e936-4f12-822e-462abfcfe20d)

**Comment by greenozon** [comment]
Looks like I understand what is going on...
I've installed recently 7.2.22 and in it's dir - "c:\Program Files\PowerShell\7\"
there are lots of those ami-ms... dlls
and its set much bigger comparing to the one from 7.4.4

thus, I recommend to install 7.2.22 and then get archive of 7.4.4, unpack it and run it
In my understanding it'll reuse missing dlls from 722 dir

pls give it a try, just curious if this theory works

**Comment by Temik007** [comment]
> @Temik007 do you know how to make it work also for the 7.4.4 version? Version 7.4.3 works...
@greenozon
@bt4ibwem8

Still work, just copy *.dll from 7.2.0 release into C:\Program Files\PowerShell\7\
api-ms-win-core-com-l1-1-0.dll
api-ms-win-core-console-l2-1-0.dll
api-ms-win-core-shlwapi-legacy-l1-1-0.dll
API-MS-Win-Eventing-Provider-L1-1-0.dll

**Comment by bt4ibwem8** [comment]
@Temik007 
i did, but it works only with 7.4.3 version...

**Comment by bt4ibwem8** [comment]
i am now getting error even with 7.4.3 version:

![image](https://github.com/user-attachments/assets/da9d8141-a42b-411d-a8c9-cf562542a576)

**Comment by greenozon** [comment]
what command did you run in pwsh?

**Comment by bt4ibwem8** [comment]
none because it crashes so i cannot write any command

**Comment by greenozon** [comment]
you mean you could not even pwsh.exe itself and see the console window?

**Comment by bt4ibwem8** [comment]
yes, like i posted in screenshot

**Comment by greenozon** [comment]
Do you have .NET 8 installed?
I never saw that kind of error in any Windows OS, to be honest...

**Comment by bt4ibwem8** [comment]
Host:
  Version:      6.0.16
  Architecture: x64
  Commit:       1e620a42e7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.16 [C:\Users\lolo\scoop\apps\dotnet-6.0-desktopruntime-np\current\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Users\lolo\scoop\apps\dotnet-6.0-desktopruntime-np\current\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by greenozon** [comment]
as per my understanding pwsh 7.4.4 is .NET8 based app, 
you could see it inspecting for example pwsh.dll that will show:
```
[assembly: TargetFramework(".NETCoreApp,Version=v8.0", FrameworkDisplayName = ".NET 8.0")]
```

so, I suggest you to install .NET8 from MS site
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

eg - .NET Desktop Runtime 8.0.7

PS you have 2 different .NET5 versions installed on your PC - I suggest to remove 6.0.16 one and keep just a single version

**Comment by bt4ibwem8** [comment]
i did but still the same error, output from dotnet --info:
.NET runtimes installed:
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by greenozon** [comment]
OK, this is very very interesting...
Looks like it is a time for debugging or so :)

PS
Have you tried to install 7.2.22
and then get zip archive of 7.4.4 and run it?

**Comment by bt4ibwem8** [comment]
I also get this error for 7.2.22 version. Before it worked fine, something is broken on my system...

**Comment by greenozon** [comment]
yeah... 
try to do some system cleanup eg
sfc /scannow
etc

**Comment by flawrist** [comment]
``` console
$ ver && dotnet --info
Microsoft Windows [Version 6.1.7601]

Host:
  Version:      8.0.17
  Architecture: x64
  Commit:       77545d6fd5
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

PowerShell 7.2.24 (the last official version for Windows 7) launches as expected. But Pwsh 7.3-7.6 does not work out of the box, although NET Desktop Runtime 8 is installed. 

These PowerShell versions start working on Windows 7 with `api-ms-*.dll` and `ext-ms-*.dll` from 7.2.24 and `setx DOTNET_EnableWriteXorExecute 0`.

**Question**. Since these DLLs were removed from 7.3+, is it assumed that newer Windows OS have them by default? Or they are installed as a part of some NET/whatever package?
