### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by kjacobsen** [PowerShell/PowerShell#19817]
### Name of the Distribution

Armbian

### Version of the Distribution

TBC

### Package Types

- [ ] Deb
- [ ] RPM
- [X] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

ARMv7 32bit

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [ ] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by kjacobsen** [comment]
Hey Folks, I have been working with an [Orange Pi One]((http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-One.html) running [Armbian]((https://www.armbian.com/orange-pi-one/) 23.02.2, and have gotten PowerShell 7.3.4 up and running.

The process for setup/install is the same as the Raspberry Pi ([Installing on Raspberry Pi OS](https://learn.microsoft.com/en-au/powershell/scripting/install/install-raspbian?view=powershell-7.3)), with a small change to the prereqs. 

I wasn't sure if I should raise a Distribution Support Request, or just an update for the Microsoft Doc's/Learn page.

**Comment by rhubarb-geek-nz** [comment]
If the existing arm tar.gz works on armbian then there is no need for a new distribution. A tar.gz does not not encode the dependencies like a proper deb package does.

If you want an arm debian package then join the queue.

https://github.com/PowerShell/PowerShell/issues/19083

**Comment by theJasonHelmick** [comment]
This request is not supported on .NET.
