### ISSUE TITLE
Problems with enabling Virtual Terminal Mode when streaming program output on conhost

### ISSUE THREAD

**Issue by Herrmel** [PowerShell/PowerShell#19813]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On PowerShell with conhost use the following Command:
```powershell
dotnet --version | Write-Verbose -Verbose
```

If dotnet is not installed you can also use `cmd /c ver` or any other programm.

### Expected behavior

Printing the following output in yellow:

```console
VERBOSE: 7.0.100
```

### Actual behavior

The following Text is printed colorless:

```console
[33;1mVERBOSE: 7.0.100[0m
```

### Error details

For some very odd reason after I type an incorrect parameter like this:

```console
dotnet --version | Write-Verbose -u # -u does not exist
```
The error-message is again displayed with ansi escape signs:
```console
←[31;1mWrite-Verbose: ←[31;1mA parameter cannot be found that matches parameter name 'u'.←[0m
```
But after this the previous example works as expected (See image below).

When the text is not streamed for example when intercepting the output with out-string (without the -Stream parameter) it also works.

I already had an issue for this in #18771 wich got blamed on the terminal repo and closed without any investigation. In my opinion this must be an issue with powershell because:
1. It worked in older 7.2.x versions
2. It randomly works after a runtime error
3. The terminal guy thinks so aswell

We provide powershell commands with our program and it really sucks to explain to every customer that we can't fix this and that they have to install an older version or another terminal to fix this.

Also some other items that seem related:
#16612
#18294
#19425
```


### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Also tested with 7.3.4 and 7.4.0-preview.3
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/36636591/a07b6a58-59e9-46b3-808d-4e4ad7a40fb5)

**Comment by 237dmitry** [comment]
> You are using the new windows terminal, not conhost

No difference:

![Screenshot 2023-06-15 162304](https://github.com/PowerShell/PowerShell/assets/78153320/a027fe9a-72eb-41ba-8813-f014253ae6f1)

**Comment by Herrmel** [comment]
Is this on windows 10? As far as I've read online the conhost got replaced in windows 11.

**Comment by 237dmitry** [comment]
>  As far as I've read online the conhost got replaced in windows 11.

![Screenshot 2023-06-15 163043](https://github.com/PowerShell/PowerShell/assets/78153320/f4e27e77-01a8-48c0-9bd9-93132596dea1)

**Comment by Herrmel** [comment]
Maybe conhost is diffrent in windows 11 or is an alias for backwards compatibility. Please test it on a windows 10 or windows server 2016/2019. I've tested this on multiple pcs already and in my previous issues other people like @mklement0  could reproduce this as well.

**Comment by 237dmitry** [comment]
> Please test it on a windows 10 or windows server 2016/2019.

I can't. Try to set `$PSStyle.OutputRendering = 'Host'`

**Comment by Herrmel** [comment]
![image](https://github.com/PowerShell/PowerShell/assets/36636591/f28b0b41-672f-49b9-b370-fedeb6ca6f77)
(outputrendering was already set to host). Setting it to PlainText works but then all colors are missing.

**Comment by 237dmitry** [comment]
I do not know then. Maybe you can try to set:

```
 ％ (gp hkcu:\Console).VirtualTerminalLevel
1
```
![Screenshot 2023-06-15 164924](https://github.com/PowerShell/PowerShell/assets/78153320/5c07b196-fbee-4c89-b0d5-aaa8216e30e8)

**Comment by SteveL-MSFT** [comment]
I believe this is an issue on conhost and works correctly in Windows Terminal.  If you can confirm, then you'll need to open the issue in the conhost repo.

**Comment by Herrmel** [comment]
I already did, see [here](https://github.com/microsoft/terminal/issues/14554). @zadjii-msft even [answered on my last thread](https://github.com/PowerShell/PowerShell/issues/18771#issuecomment-1351756893) but we got no further response because it got already closed because of the external label. Please do not auto close this again before at least investigating. Yes it works fine on windows terminal.
But like I said, it works completly fine on 7.2.X and a random error message fixes the problem somehow? That really seems suspicious. It really seems like a 7.3+ issue for me.

**Comment by Herrmel** [comment]
My guess would be something like this:
PowerShell disables VT-Mode when executing a program (to support native program output or something like that?)
PowerShell does not reenable VT-Mode until after the program is finished so that write-* commands that use Ansi do not work correctly
Maybe when an error occurrs in a command down the pipe a flag for the end of programm exection is not set and VTSupport is never getting disabled again? (pure speculation)

**Comment by Herrmel** [comment]
Again, this commit here seems really suspicious to me: #16612
it got introduced in 7.3.0-preview.2. I just tested 7.3.0-preview.2 and 7.3.0-preview.1 and behold, it works fine on preview 1 and does not work on preview 2. Please take a look at it.

**Comment by 237dmitry** [comment]
> Maybe conhost is diffrent in windows 11 or is an alias for backwards compatibility. 

I think it depends on the terminal. I was unable to reproduce the issue in my environment. I also tried on linux:

![verbose](https://github.com/PowerShell/PowerShell/assets/78153320/f3d8fa57-3231-4aa6-899c-67fdfa556069)

**Comment by Herrmel** [comment]
Yes, all my assumptions/problems are specific to conhost on win10/win server 2016/win server 2019/(maybe also 2022, have not tested). Those should be supported by PowerShell, right?

**Comment by Herrmel** [comment]
I guess they just don't want to fix it. I'm tired of @SteveL-MSFT just slapping the external label on this issue without any hesitation to close this issue. I guess I'll have to stick to 7.2 forever.
