### ISSUE TITLE
Module name on Windows is using casing from import command

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#19821]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

After importing a module on Windows, running `Get-Module` displays the module name the way it was written during import, not according to module branding.

This does not occur in Unix (ex. repo devcontainer).

### Expected behavior

Module name is shown in correct casing, set by the author, on all platforms

```console
# Windows
> Import-Module threadJOB
> Get-Module Thread*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.0.3                 ThreadJob                           Start-ThreadJob

# Unix
> Import-Module threadJOB                                                       
> Get-Module Thread*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.0.3                 ThreadJob                           Start-ThreadJob
```

### Actual behavior

```console
# Windows - Bug
> Import-Module threadJOB
> Get-Module Thread*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.0.3                 threadJOB                           Start-ThreadJob

# Unix - Working
> Import-Module threadJOB                                                       
> Get-Module Thread*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.0.3                 ThreadJob                           Start-ThreadJob
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
The fundamental problem is a limit in .NET.  On Unix, additional code was added as the filesystem is typically case-sensitive to perform a case-insensitive search for matching filename.  PowerShell internally will use the user supplied name to find a valid file path to the module.  .NET (probably a perf optimization when it doesn't matter on case-insensitive filesystems) simply uses the input name as the output name instead of the actual name on disk.

So to change this on Windows to use the Unix code would incur a perf hit.  Ideally, the .NET `Path.GetFileName()` method would return the actual casing of the file and this would be automatically addressed.  The Windows behavior is consistent with Windows PowerShell.

**Comment by fflaten** [comment]
Thanks for the detailed explanation @SteveL-MSFT! Like @ThomasNieto I would expected this to adhere to the name set in the manifest, and maybe the module file name as fallback.

The perf hit I'm not so sure about. This only applies when manually importing the module by name/path, right? At that point the user has commited to process both module manifest and module file which could take seconds. The time required to read the manifest twice (worst case) should be negligible compared to the actual import.

Even a fallback variant like `[System.IO.Directory]::GetFiles("c:\directory","fileNAME.ps1")` to get the properly case-sensitive path, should be very fast unless the module folder contains thousands of files. Though to avoid complexity, I'd be happy even with just checking the manifest.

**Comment by fflaten** [comment]
Really?
