### ISSUE TITLE
Error when running application with PowerShell version 7: "Get-ExecutionPolicy" command not found

### ISSUE THREAD

**Issue by Abhijay007** [PowerShell/PowerShell#19833]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Description: 

I encountered an error while running my application with PowerShell version 7. The error message states: "Get-ExecutionPolicy: The 'Get-ExecutionPolicy' command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded. For more information, run `Import-Module Microsoft.PowerShell.Security.` I would like to know how to resolve this issue and understand the possible cause of the error.

Additional Details: 

I have successfully run the application using PowerShell version 5 without any errors. However, when I switch to PowerShell version 7, I encounter this specific error. I have already attempted to resolve it by using the command Import-Module Microsoft.PowerShell.Security in an administrative setting, but it did not work. I also referred to the Microsoft documentation on importing modules (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.3#description), but the issue persists.

you can reproduce this error from here: https://github.com/EtherealEngine/etherealengine-control-center/pull/77, The purpose of this pull request is to add a new prerequisite that checks whether the user has permission to run ps1 scripts. Specifically, it verifies if the user has `Get-ExecutionPolicy` set to `unrestricted` or not. 

Currently, everything is functioning smoothly with PowerShell version 5. However, when attempting to run it with PowerShell version 7, the aforementioned error occurs.

PS : I already tried steps mentioned in  issue https://github.com/PowerShell/PowerShell/issues/18530  but it still not working 

the solution I tried is: I unset the environment variable `PSModulePath` in cmd by `set PSModulePath=` before starting powershell.exe and then `Import-Module Microsoft.PowerShell.Security` but it is still showing the same error

### Expected behavior

```console
Expected behavior: It should not throw an error when executing Get-ExecutionPolicy, display the output, and verify the prerequisites, just as it does in powershell version 5. It is functioning correctly in that version.
```

### Actual behavior

```
console
it is dropping the error, and not able to call the `get-excutionPolicy` it states "command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded"

```

### Error details

```
console
Get-ExecutionPolicy: The 'Get-ExecutionPolicy' command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'."

At line:1 char:1
+ Get-ExecutionPolicy;
+ ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (Get-ExecutionPolicy:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
I would like to know how to resolve this issue and understand the possible cause of the error.

```
```


### Environment data

```PowerShell
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      4
```

### Visuals

In my PowerShell 7 despite policy being unrestricted I am getting the following error

![245066178-043c08ea-ee21-4165-828c-13fe3d7c24b3 (1)](https://github.com/PowerShell/PowerShell/assets/64387054/19070489-9daf-41eb-b9a8-3ea31adfc644)

**Comment by 237dmitry** [comment]
Check your environment from pwsh.exe:

```powershell
$PSHome
$env:PSModulePath -split ';'
$PSModuleAutoLoadingPreference      # should be nothing or 'All'
Get-Module
```

**Comment by Abhijay007** [comment]
`

**Comment by Abhijay007** [comment]
> Check your environment from pwsh.exe:
> 
> ```powershell
> $PSHome
> $env:PSModulePath -split ';'
> $PSModuleAutoLoadingPreference      # should be nothing or 'All'
> Get-Module
> ```

here are outputs of commands : 

```
PS C:\Windows\System32>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
PS C:\Windows\System32> $PSHome
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.4.0_x64__8wekyb3d8bbwe

```
PS C:\Windows\System32> $env:PSModulePath -split ';'
C:\Users\notMyUserName\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\windowsapps\microsoft.powershell_7.3.4.0_x64__8wekyb3d8bbwe\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

```

PS C:\Windows\System32> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.6                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

```

**Comment by 237dmitry** [comment]
The only I can say -- do not install pwsh from Store. This is my personal opinion.

**Comment by Abhijay007** [comment]
> The only I can say -- do not install pwsh from Store. This is my personal opinion. 

okay I will try to install it  using alternate method and will see if that works

**Comment by Abhijay007** [comment]
> The only I can say -- do not install pwsh from Store. This is my personal opinion.

also is this the correct way of doing it ?  as the solution suggested in the previous issues, or I am missing something here? 


> the solution I tried is: I unset the environment variable `PSModulePath` in cmd by `set PSModulePath=` before starting powershell.exe and then `Import-Module Microsoft.PowerShell.Security` but it is still showing the same error

**Comment by 237dmitry** [comment]
Install msi from release page.

>  as the solution suggested in the previous issues, or I am missing something here?

$env:PSModulePath of pwsh.exe is not visible from powershell.exe or cmd.exe. I don't khow where it is stored, in registry or generates in pwsh session.

**Comment by Abhijay007** [comment]
> Install msi from release page.
> 
> > as the solution suggested in the previous issues, or I am missing something here?
> 
> $env:PSModulePath of pwsh.exe is not visible from powershell.exe or cmd.exe. I don't khow where it is stored, in registry or generates in pwsh session.

@237dmitry, I think if we don't enforce the non-usage of the Windows Store in this application, could you please suggest any alternative approach if you know of one? Additionally, could you please add the 'Needs-Triage' label to this issue? It was accidentally removed when the issue was closed

**Comment by 237dmitry** [comment]
> could you please suggest any alternative approach if you know of one?

I don't know how to solve your problem. I've already seen a few issues specific to the Store version. I suspect that this is due to application isolation and insufficient user rights. But I can be wrong.

> could you please add the Needs-Triage label to this issue?

I am common user and can't label your issue.

**Comment by abatishchev** [comment]
@Abhijay007 please reopen. I'm getting the same error in https://github.com/loekd/ServiceFabric.Mocks/pull/181 and it has nothing to do with Windows Store, the failure occurs inside a GitHub workflow

**Comment by Abhijay007** [comment]
> @Abhijay007 please reopen. I'm getting the same error in [loekd/ServiceFabric.Mocks#182](https://github.com/loekd/ServiceFabric.Mocks/pull/182) and it has nothing to do with Windows Store, the failure occurs inside a GitHub workflow

Hi @abatishchev you can follow this thread here on Discord:  https://discord.com/channels/180528040881815552/1122099214944571452 , this helped me to resolve this issue

**Comment by abatishchev** [comment]
Can you invite me to this channel? The link works but displays nothing. My Discord user name = GitHub. Thanks!

**Comment by Abhijay007** [comment]
> Can you invite me to this channel? The link works but displays nothing. My Discord user name = GitHub. Thanks!

Hi @abatishchev, here is the discord [invite link](https://discord.gg/powershell) for the PowerShell community
