### ISSUE TITLE
Native pipeline fails to redirect stdout to files, always to console ( PSNativeCommandPreserveBytePipe enabled )

### ISSUE THREAD

**Issue by mitchcapper** [PowerShell/PowerShell#19836]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

See attached script and output. Or: open the latest daily pwsh.exe  and do something like `hostname.exe > somefile`  instead it will write to stdout.  You do not need to use the repro script from any specific powershell version, as it downloads the daily and uses that for the repro.

Thanks though for byte pipes just amazing to have this native now. 

[result.txt](https://github.com/PowerShell/PowerShell/files/11829118/result.txt)
[repro.ps1.zip](https://github.com/PowerShell/PowerShell/files/11829123/repro.ps1.zip)

### Expected behavior

```console
native program stdout is written to the redirected file
```

### Actual behavior

```console
native program stdout is written to console stdout always
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 4cq2** [comment]
you should provide an example command.

**Comment by SeeminglyScience** [comment]
Thanks for the report! I was able to repro, opened #19841 to fix.
