### ISSUE TITLE
Missing prompt autocomplete options on case-sensitive filesystems

### ISSUE THREAD

**Issue by Hashbrown777** [PowerShell/PowerShell#19843]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Type out a directory containing files with the same name but differing case, hit tab to get suggestions

### Expected behavior

```console
Shows the available files
```

### Actual behavior

```console
Only shows one of them, furthermore it appears to be random which one it chooses
```

### Error details

```console
If you type a non-displayed option manually, then hit tab, pwsh "corrects" you to the wrong file..
```

### Environment data

```powershell
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/6907206/51a79834-8ab3-4809-ae53-f9c30e4ab857)

**Comment by MartinGC94** [comment]
What happens if you enter this command: `TabExpansion2 'cat ./' | select -ExpandProperty CompletionMatches`? Does it list all 4 results like you would expect? If so, then this is a PSReadline issue. It filters out apparent duplicates but I thought a fix for that had been implemented.

**Comment by Hashbrown777** [comment]
`(TabExpansion2 'cat ./').CompletionMatches` shows all the results, yep

**Comment by theJasonHelmick** [comment]
Thank you @Hashbrown777 -- The WG can not reproduce what your seeing in the latest version of PSReadLine preview, but we do see it PSReadLine 2.2.6 -- you can upgrade to the preview version ([link](https://www.powershellgallery.com/packages/PSReadLine/2.3.1-beta1)) or take the upcoming GA release.

**Comment by Hashbrown777** [comment]
Hm, `2.3.1-beta1` does solve this immediate issue, but it has strange behaviour (for a linux user) where it still thinks distinct filename stems are the same (but at least displays them now). I actually like this, but `touch a1 Ax; ./A[tab]` shows both `a1` and `Ax` as options; `a` & `A` are distinct glyphs and only `a1` was expected as a valid autocomplete.

Now if this is *intended* then that's great! Pulling away from bash-esque constraints of needing to be so specific will make CLI much easier, and is definitely a strength of pwsh.
But I would probably submit that files beginning with `á` et cetera should also match, which otherwise are much more annoying to type than mere case sensitivity, this would make pwsh absolutely amazing.

If it's not intended though and is a side-effect of just fixing this immediate issue there might be side-effects to look into.. so just checking.
