### ISSUE TITLE
Invoke-RestMethod is sending empty body with PUT requests

### ISSUE THREAD

**Issue by onetocny** [PowerShell/PowerShell#19844]
### Steps to reproduce

`Invoke-RestMethod` is sending empty body under following circumstances:
- `PUT` method is used and
- body object is passed directly to `Invoke-RestMethod`.

See the complete working example below. To demonstrate this issue I am using testing [JSONPlaceholder API](https://jsonplaceholder.typicode.com/) that returns body it received (it is just adding id property). Note that described scenario is failing just in case of `PUT` method as `POST` example below works as expected. The theory is that `Invoke-RestMethod` fails to serialize passed payload but silently continues with an empty body. I would expect either throwing an error or working just fine as in `POST` scenario.

```powershell
$body = @{
    name = "Gandalf"
};
$post = "https://jsonplaceholder.typicode.com/posts";
$put = "https://jsonplaceholder.typicode.com/posts/1";


# Sending empty body
$response1 = Invoke-RestMethod -Uri $put -Method Put -Body $body
Write-Host $response1

# Working
$response2 = Invoke-RestMethod -Uri $put -Method Put -Body ($body|ConvertTo-Json -Depth 99) -ContentType "application/json"
Write-Host $response2

# Working
$response3 = Invoke-RestMethod -Uri $post -Method Post -Body $body
Write-Host $response3

# Working
$response4 = Invoke-RestMethod -Uri $post -Method Post -Body ($body|ConvertTo-Json -Depth 99) -ContentType "application/json"
Write-Host $response4
```

### Expected behavior

```console
@{name=Gandalf; id=1}
@{name=Gandalf; id=1}
@{name=Gandalf; id=101}
@{name=Gandalf; id=101}
```

### Actual behavior

```console
@{id=1}
@{name=Gandalf; id=1}
@{name=Gandalf; id=101}
@{name=Gandalf; id=101}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by CarloToso** [comment]
@onetocny Could you test it in Powershell 7.4preview3 ?

**Comment by onetocny** [comment]
I can confirm that sample script works as expected in Powershell 7.4preview3.
