### ISSUE TITLE
`New-Item -ItemType Junction` checks for invalid parameter (Target)

### ISSUE THREAD

**Issue by gaiking-uk** [PowerShell/PowerShell#19849]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`New-Item` parameter set / parameter checking gives an incorrect error message when trying to create a junction... It specifies that a `Target` parameter is needed, however there is no parameter called `Target`.

I raised this initially as a documentation issue [#10199](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10199), but @sdwheeler advised that this is a bug as there is no parameter called `Target`, and actually `Target` is an alias for `Value`

### Expected behavior

```console
$JuncName = "Foo"
$JuncTarget = "D:\Junction_Target"
> New-Item -ItemType Junction -Name $JuncName -Path $JuncTarget

Junction created successfully.
```

### Actual behavior

```console
$JuncName = "Foo"
$JuncTarget = "D:\Junction_Target"
> New-Item -ItemType Junction -Name $JuncName -Path $JuncTarget

ERROR: Link "D:\Junction_Target" cannot be created because Target was not specified.
```

### Error details

```console
Link cannot be created because Target was not specified.
```

### Environment data

```powershell
> $PSVersionTable
Name                           Value
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> Link cannot be created because Target was not specified.

Specify it. Use `-Target` or `-Value` instead of `-Path`

**Comment by gaiking-uk** [comment]
> Specify it. Use `-Target` or `-Value` instead of `-Path`

Sure, the residual point I (and I believe @sdwheeler) are making, is that currently the coding of the `New-Item` cmdlet error handling / parameter checking is something like:
```
If (!($Path -and $Value)) {
    Throw-Error "Link $Path cannot be created because **PARAMETER THAT DOES NOT EXIST** was not specified."
}
```

The current error message told me to supply a `Target` parameter, which caused confusion as `Target`:
* Didn't show up in autocomplete
* Wasn't listed as an option in `Show-Command New-Item`
* And wasn't mentioned on the [New-Item help page](https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3).

***

▶️ The error message should be amended to give the correct instruction / actual parameter names required.

**Comment by sdwheeler** [comment]
The [New-Item help page](https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3) does document that **Target** is an alias for the **Value** parameter. We also include an example that uses `-Target`. The problem is the error message in PowerShell should reference the **Value** parameter, not its alias.

See https://github.com/PowerShell/PowerShell/blob/04f503a3b7a1b6e493d86839efd70c542563bd3c/src/System.Management.Automation/resources/SessionStateStrings.resx#L595

**Comment by 237dmitry** [comment]
> Wasn't listed as an option in Show-Command New-Item

Get-Command?

```powershell
 ％ (Get-Command New-Item).Parameters.Value

Name            : Value
ParameterType   : System.Object
ParameterSets   : {[__AllParameterSets, System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : False
Aliases         : {Target}
Attributes      : {, System.Management.Automation.AliasAttribute}
SwitchParameter : False
```

**Comment by gaiking-uk** [comment]
No-one is disputing that Target is not an alias for Value. The issue is the error help directs the user to specify a parameter that does not appear on of of the cmdlets's [Syntax](https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3#syntax) (Parameter Sets) or list of [Parameters](https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.3#parameters).

Respectfully, I have spent an hour on this now, completed two issue forms, provided multiple examples, links, cross-references. I think the issue (and requested action) has been made clear, but if you disagree and want to close this issue that is up to you.

**Comment by sdwheeler** [comment]
@gaiking-uk I submitted a PR to change the error message.

**Comment by gaiking-uk** [comment]
@sdwheeler -- Thanks Sean, appreciate it! 👍🏼

... I know no change is ever quite as easy as it seems, but in this case it does appear to be literally just ***changing 1 word*** in the code, so hopefully shouldn't be too tricky for the team.
