### ISSUE TITLE
Get-ChildItem -Recurse -File <pattern> returns nothing, though matching files exist in a subdirectory.

### ISSUE THREAD

**Issue by crasshacker** [PowerShell/PowerShell#19852]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've run across a case where "ls -Recurse -File <pattern>" returns nothing, even though files matching the pattern exist in a child directory.  I've only found one directory where this problem occurs, though, and I'm not sure what makes it unique.  In my particular case, I'm in a directory with a subdirectory named "Microsoft Azure in Action", and in that subdirectory are three files (Microsoft_Azure_in_Action_v6_MEAP.epub, along with .mobi and .pdf files with the same base name).  If I type "ls -File 'Microsoft Azure in Action'", all three files are returned.  If I type "ls -File -Recurse", all three files are returned.  But if I type "ls -File -Recurse *Azure*" nothing is returned, even though there are those three matching files in the "Microsoft Azure in Action" subdirectory.

[Transcript.txt](https://github.com/PowerShell/PowerShell/files/11851339/Transcript.txt)

### Expected behavior

```console
A recursive search for files matching a pattern should match all files in any subdirectories (recursively) that have filenames matching that pattern.
```

### Actual behavior

```console
In certain cases, Get-ChildItem returns no files even though matching files exist.  A transcript follows; look at the last command (3 lines from the bottom) and note that it returns nothing, even though the earlier "ls" command clearly shows files existing.

~\Dropbox\Apps\Manning Books>
PS>ls '.\Microsoft Azure in Action\*Azure*'
>> CommandInvocation(Out-Default): "Out-Default"
>> ParameterBinding(Out-Default): name="InputObject"; value="C:\Users\Computer\Dropbox\Apps\Manning Books\Microsoft Azure in Action\Microsoft_Azure_in_Action_v6_MEAP.epub"

    Directory: C:\Users\Computer\Dropbox\Apps\Manning Books\Microsoft Azure in Action

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            5/5/2023 10:12 AM       34324149 Microsoft_Azure_in_Action_v6_MEAP.epub
>> ParameterBinding(Out-Default): name="InputObject"; value="C:\Users\Computer\Dropbox\Apps\Manning Books\Microsoft Azure in Action\Microsoft_Azure_in_Action_v6_MEAP.mobi"
-a---            5/5/2023 10:12 AM       11948032 Microsoft_Azure_in_Action_v6_MEAP.mobi
>> ParameterBinding(Out-Default): name="InputObject"; value="C:\Users\Computer\Dropbox\Apps\Manning Books\Microsoft Azure in Action\Microsoft_Azure_in_Action_v6_MEAP.pdf"
-a---            5/5/2023 10:12 AM       21569930 Microsoft_Azure_in_Action_v6_MEAP.pdf

~\Dropbox\Apps\Manning Books>
PS>ls -Recurse -File *Azure*
>> CommandInvocation(Out-Default): "Out-Default"
~\Dropbox\Apps\Manning Books>
```

### Environment data

```powershell
Note: In addition to version 7.4.0-preview.3 (details below), I see the same problem with PowerShell 7.3.4 and Windows PowerShell 5.1.

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iRon7** [comment]
What is the exact command you giving?
This is probably common behavior of the [Get-ChildItem](https://learn.microsoft.com/powershell/module/microsoft.powershell.management/get-childitem)

**Comment by 237dmitry** [comment]
In my environment all works

```
dir -s -file *paper*   # returns all files like Wallpaper-##.ext
```

**Comment by crasshacker** [comment]
Yes, the command I'm having trouble with generally works properly.  It only fails to work properly in one specific location that I've found, and that's' in my "~/Dropbox/Apps/Manning Books" directory hierarchy.  Here is a transcript:

C:\Users\Computer\Dropbox\Apps\Manning Books> Get-ChildItem -Recurse -File

    Directory: C:\Users\Computer\Dropbox\Apps\Manning Books\Microsoft Azure in Action

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            5/5/2023 10:12 AM       34324149 Microsoft_Azure_in_Action_v6_MEAP.epub

C:\Users\Computer\Dropbox\Apps\Manning Books> Get-ChildItem -Recurse -File -Path *Azure*
C:\Users\Computer\Dropbox\Apps\Manning Books>

The first command, Get-ChildItem -Recurse -File works properly, returning the one file that exists in this directory hierarchy.  However, the next command, Get-ChildItem -Recurse -File -Path *Azure* returns nothing, even though there's clearly a file whose name matches.  If I copy that file to a different directory structure and perform the same test, everything works properly.  It's only in this one particular area of the filesystem that the problem arises.  So there's something special about this location, but I just have no idea what it is.

The directory where the failure occurs is within my Dropbox hierarchy.  In fact, the "Apps/Manning Books" directory wasn't even created by me; it was created by Dropbox when I purchased ebooks through Manning and had them shipped by Manning to my Dropbox.  So perhaps the Dropbox app does something peculiar to the directories it creates, though I can't imagine what that would be.

I don't consider this to be a huge issue, because it only seems to occur in this one area.  But it's very disturbing because it's possible that it occurs elsewhere, and if that's the case it means that recursive searches for files matching a pattern is inherently untrustworthy.  It would be really good to know what's causing this behavior, so that we're confident other people won't run into this (at least not often).

**Comment by iRon7** [comment]
[`-Path Azure`}(https://learn.microsoft.com/powershell/module/microsoft.powershell.management/get-childitem#-path) defines the ***Path*** (or paths) from where the search is initiated, not each file that found in the recursive search folder . To match all the files named `Azure` your current folder, you should use the [`-Include`](https://learn.microsoft.com/powershell/module/microsoft.powershell.management/get-childitem#-include) parameter::

```PowerShell
Get-ChildItem -recurse -Include Azure
```

**Comment by crasshacker** [comment]
Yes!  It works when using -Include.  However, this brings up another question, related to the way the Path parameter to Get-ChildItem works.  Look at the following example:

=========================BEGIN TRANSCRIPT ==========================

C:\TEMP\giggle> ls -Recurse

    Directory: C:\TEMP\giggle

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           6/24/2023 10:59 AM                Test

    Directory: C:\TEMP\giggle\Test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           6/24/2023 10:59 AM              5 FOO
-a---            5/5/2023 10:12 AM       34324149 Microsoft_Azure_in_Action_v6_MEAP.epub

C:\TEMP\giggle> Get-ChildItem -recurse -File -Path *Azure*

    Directory: C:\TEMP\giggle\Test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            5/5/2023 10:12 AM       34324149 Microsoft_Azure_in_Action_v6_MEAP.epub

========================== END TRANSCRIPT ==========================

In the second Get-ChildItem command, we pass *Azure* as the Path parameter, but there is no *Azure* file or directory in the C:\TEMP\giggle directory that *Azure* could match.  Instead, it seems to treat it as if it were passed as the Include parameter, because the matching file in the Test subdirectory is returned (and the FOO file is not returned because it doesn't match *Azure*).  Very strange behavior, and probably what got me confused because this command format, where I pass the pattern in the Path parameter rather than the Include parameter, seems to work (matching filenames against the pattern) everywhere I've tried except that one location in my Dropbox hierarchy.  So I'm still confused about the inconsistent behavior I'm seeing (i.e., why the command works differently in this one particular "Dropbox/Apps/Manning Books" directory than any other directory), but things work properly with the -Include parameter so I consider this a misunderstanding on my part and consider the issue can be closed.

**Comment by crasshacker** [comment]
User misunderstanding (misuse of cmdlet parameters).
