### ISSUE TITLE
`Test-Path` gives incorrect result when used with `-NewerThan` and `-OlderThan` parameters together.

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#19855]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using `Test-Path` with both `-NewerThan` and `-OlderThan` parameters together, it can return incorrect results if a file is newer than a datetime but not older than a datetime.

I believe this is because the file system provider first checks `OlderThan` before `NewerThan`: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L3320-L3328

Which means that the true result from `NewerThan` overwrites `OlderThan` incorrect result. I would expect the result to act as a logical AND, and take both results into consideration since it should validate similar to a time range.

### Expected behavior

```console
PS> New-Item -Path test # Newly created file
PS> Test-Path test -NewerThan (Get-Date).AddDays(-1) -OlderThan (Get-Date).AddHours(-1)
False
```

### Actual behavior

```console
PS> New-Item -Path test # Newly created file
PS> Test-Path test -NewerThan (Get-Date).AddDays(-1) -OlderThan (Get-Date).AddHours(-1) # Newly created file should not be older than 1 hour
True
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Is there logical OR instead of logical AND?

| logical operator | file exists | newer | older | result |
|----- |--------|---------|------------|-----|
| and | true | true | false | false |
| or | true | true | false | true |

**Comment by ArmaanMcleod** [comment]
@237dmitry I believe the current state is closer to logical OR but not really since it checks `OlderThan` before `NewerThan` and overwrites result.

If you use logical AND then the behaviour makes more sense if both parameters are used:

```powershell
PS> New-Item -Path test # Newly created file
PS> Test-Path test -NewerThan (Get-Date).AddDays(-1) -OlderThan (Get-Date).AddHours(-1)
False # New file is not older than 1 hour
```

But current behaviour you would get `True` because `NewerThan` result overwrites the false result from `OlderThan`.

Also there are no tests for these parameters. which in any case should be added.

@iSazonov What do you think?

**Comment by iSazonov** [comment]
I'd expect we filter by range.
Another question should the range be open or close  - ( .. ), ( .. ], [ .. ), or [ .. ]. How filter `Today` files?

**Comment by ArmaanMcleod** [comment]
I believe this is a bug if we expect it to filter by range.

@SteveL-MSFT @iSazonov should this be reviewed by working group to confirm this behaviour. If it is a bug I am happy to fix it and add tests. I personally don't think anyone would rely on this behaviour since it does not do what you would expect from range filtering, would probably fit in **Bucket 3: Unlikely Grey Area** breaking change.
