### ISSUE TITLE
Up to date LTS version shouldn't notify about higher version Stable release

### ISSUE THREAD

**Issue by sassdawe** [PowerShell/PowerShell#19850]
### Summary of the new feature / enhancement

As an LTS user who already running the latest version I don't need to be notified that a higher version Stable-version exists.

However I still want to know when I am not running the later LTS version. 

![image](https://github.com/PowerShell/PowerShell/assets/10754765/6d9ee3d2-e8dd-4e8b-913c-88eb3145f934)

### Proposed technical implementation details (optional)

Could the LTS update check mechanism be restricted to only check the for the same release and ignore the others? 

This of course doesn't apply to Stable, because there could be higher version TLS release already available when Stable is ending it's support and there will be no supported Stable version for a couple of months.

**Comment by kilasuit** [comment]
Agreed and I think that the logic for this may need to be controllable by a settable env var or config file or registry setting etc

**Comment by daxian-dbw** [comment]
You can set the `POWERSHELL_UPDATECHECK` environment variable to `LTS`, then it will only notify of updates to long-term-servicing (LTS) GA releases.
See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.3

**Comment by sassdawe** [comment]
That was an epic oversight on my part. For some reason I only remembered that I can only turn ON or OFF the update checks. *facepalm*

**Comment by sassdawe** [comment]
@daxian-dbw I am sorry but what if a user has multiple versions installed? 

The documentation is not clear if we should set this environment variable on the OS level or in the Profile file. 

The OS level environment variable is used by all installed versions at the same time, right? So, that can only be used to properly notify about the updates of one PowerShell version.

**Comment by kilasuit** [comment]
@sassdawe You are right about the Env Var being OS Level & I think the check is done whilst the profile is being loaded. So even if you set in process with the profile it would use the OS level one and not give you the experience I think you are looking for.
However with some work prior to running the pwsh process you can (although it ain't great experience) you can change the env vars used in a nested process
So something like this would work for what you want

So something like this should get you on the right direction & should do what you want
```powershell 
C:\ps-7.3.6\pwsh.exe -nop -noexit -command '$env:POWERSHELL_UPDATECHECK = "LTS";  & C:\ps-7.2.10\Pwsh.exe' 
```

**Comment by sassdawe** [comment]
Maybe @Jaykul and his issue #20210 has more luck because this was actually my second request. **Fingers crossed**

**Comment by sassdawe** [comment]
Maybe @Jaykul and his issue #20210 has more luck because this was actually my second request. **Fingers crossed**
