### ISSUE TITLE
Opensource the DSC Pull Server

### ISSUE THREAD

**Issue by gigi81** [PowerShell/PowerShell#1986]
In light of the recent move to opensource powershell on Linux, I was wondering if there is any plan to opensource the DSC pull server.
There is already a uservoice for this:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/12428307-opensource-the-pull-server

On the uservoice Justin King explains very well why the community needs this part of DSC opensourced. For some reason is the only part that is still proprietary and only included in the server editions of Windows.

**Comment by erwinwildenburg** [comment]
I would really really like this too!
But is the code for having a pull client even available? That part is not available in nano server also.

**Comment by SteveL-MSFT** [comment]
DSC Pull Server isn't part of PowerShellCore, continue tracking it on Uservoice
