### ISSUE TITLE
Make a PowerShell page with straight-forward download button like vscode

### ISSUE THREAD

**Issue by LazaroOnline** [PowerShell/PowerShell#19868]
### Summary of the new feature / enhancement

The current updating process is:
Every few months when a new PS version is released, I get the message in the top of a new terminal window:
![image](https://github.com/PowerShell/PowerShell/assets/13026853/66fd4cf2-7859-4ddb-aa84-04bffdf08bb0)

So I click on it, and it opens the github's releases page:
https://github.com/PowerShell/PowerShell/releases/tag/v7.3.5

then I have to scroll down to find the installer that matches my computer.
I always think that the web-page already knows I'm on a Windows x64 computer, 
and I wish it was easier and the download page had a more finished and professional look.

### Proposed technical implementation details (optional)

Creating a product page just like [VisualStudio code](https://code.visualstudio.com/),
maybe something like: https://powershell.com or https://powershell.microsoft.com where I could find a big download button with my system pre-selected like this:

![image](https://github.com/PowerShell/PowerShell/assets/13026853/05e78aad-13ce-44c2-bb64-612f8fbd88e0)

**Comment by MartinGC94** [comment]
Maybe it should just link to the readme page instead: https://github.com/PowerShell/PowerShell#get-powershell that table is pretty simple to follow.

**Comment by LazaroOnline** [comment]
I was asking for a single big download button with my system pre-selected, but the readme page has instead even more options to choose from than the existing one! The readme gets even more confusing since it also has LTS and preview versions, so users may click to get the latest (stable) version and end up downgrading to LTS instead...

Having multiple download options with different installers/platforms etc is great, but I think that is a complexity for special cases that should be put aside from the mainstream simple user that just want to download the latest version.

Also if a new user tries to get PowerShell, could be overwhelmed by the options and may get discouraged from trying it, it feels like you have to do a research just to know which version you should download, because you don't want to risk installing the wrong one and breaking your system. When in reality it is simpler than that, and a product page could give you a nice default, with all extra options behind the lateral drown-down button.

**Comment by cStralpt** [comment]
i always looking the way where i can do update my pwsh by just typing a command line, just like updating my package manager like
```
pnpm update
```

**Comment by LazaroOnline** [comment]
> i always looking the way where i can do update my pwsh by just typing a command line, just like updating my package manager like
> 
> ```
> pnpm update
> ```
> 
> it's a lot simpler

That would also be nice!
I would like to have both, the product page for new installs and to see the new features/bugfixes and the command option for other cases.

**Comment by kilasuit** [comment]
This isn't a feature request for PowerShell itself and is really more like a docs issue on installation methods. It may be plausible to do as is asked but would need more investigation on the feasibility of it - thoughts @sdwheeler @SteveL-MSFT ??

@cStralpt depending on how you installed there is no real unified way to then upgrade easily however there are install scripts available in this repo & tools like [PSReleaseTools](https://github.com/jdhitsolutions/PSReleaseTools) from @jdhitsolutions that may be of use to you. Though these depend on platform. and if installed via platform specific package manager, if so then you should already be able to upgrade via that package managers upgrade functionality.

also if you use Winget then they have an update sequence 
as does Chocolatey and other Windows Package manager tooling

**Comment by sdwheeler** [comment]
@kilasuit The installation methods are well documented already. There is no way in the docs platform to host a page like the one described by @LazaroOnline.

**Comment by BigKatGalarraga** [comment]
@LazaroOnline I typically don't use the GitHub download option when upgrading. To upgrade PWSH, use the following (assuming you have brew and winget install, if not, I suggest you get it):

For MAC I use brew: 
``` zsh
brew upgrade powershell
```
For Windows I use winget:
``` pwsh
winget upgrade Microsoft.PowerShell -h
```
Both of these methods eliminates having to manually find the correct build, download, run exe, etc.  Hope this helps :) 
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.3

**Comment by kilasuit** [comment]
> @kilasuit The installation methods are well documented already. There is no way in the docs platform to host a page like the one described by @LazaroOnline.

I didn't think there was a way for a page like that in the docs platform and did expect it to be website that would need to be built and hosted by the team, though also wondering if the current page that VS Code uses is already available as a repo that could be amended for use with PowerShell. If so then that simplifies things but there needs to be appetite to host a page like the one that code has. If so, then it needs asked just how much effort it would take to maintain by the team in future & whether this really is worth it or not.
