### ISSUE TITLE
Powershell can't run on macos 14 beta2

### ISSUE THREAD

**Issue by teslachina** [PowerShell/PowerShell#19869]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

install powershell-7.3.5-osx-arm64.pkg ok
run powershell Application PowerShell cannot be opened

### Expected behavior

```console
-
```

### Actual behavior

```console
-
```

### Environment data

```powershell
-
```

**Comment by rhubarb-geek-nz** [comment]
Do you have Rosetta installed? There was a problem where MacOS thought that PowerShell.app required Rosetta...

https://github.com/PowerShell/PowerShell/issues/18548
