### ISSUE TITLE
Rename-Item arbitrarily disallows changing capitalization of filenames.

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [PowerShell/PowerShell#19877]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create file or directory.  Attempt "Rename-Item" with altered capitalization.

### Expected behavior

```console
PS> Rename-Item .\test_1\ TEST_1
PS> Get-ChildItem -name
TEST_1
```

### Actual behavior

```console
PS> Rename-Item .\test_1\ TEST_1
Rename-Item : Source and destination path must be different.
At line:1 char:1
+ Rename-Item .\test_1\ TEST_1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\TGIF\test\TEST1\:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by kilasuit** [comment]
Windows doesn't actually care about whether or not the file/folder has mixed cases - so if you issue another rename in the middle like this you won't get this issue.

```powershell
Rename-Item .\test_1\ TEST__1 # note the extra _
Rename-Item .\TEST__1\ TEST_1
```

This will work for what you are looking to  do

**Comment by TheGoodIdeaFairy** [comment]
Yes, I've already worked around the issue.  My reasoning for taking the time to post the report is that there doesn't seem to be an obvious reason for the cmdlet to prevent this in the first place, and therefore require a workaround.

**Comment by kilasuit** [comment]
Sorry if my reply wasn't detailed enough, I sometimes will be quick with a response as to help out as quickly as I can with the issue at hand.
Though as I stated this is something that within .Net framework which PowerShell 5.1 is built on doesn't care whether you are using lower case and then renaming into upper case or not and as such needed that work around. 

Explorer will handle this for you automatically when you try renaming a file or folder whereas this isn't handled in PowerShell 5.1 but this is handled in the latest versions of PowerShell which is built from this repository

Also just as an FYI this repo doesn't actually support PowerShell 5.1 issues but as it was a nice easy one I thought it best to answer to you whilst I had the chance to.

Hope that helps explain things further 🙂
