### ISSUE TITLE
PSNativeCommandPreserveBytePipe hangs on piping to python scripts in Windows

### ISSUE THREAD

**Issue by rmccampbell** [PowerShell/PowerShell#19876]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm trying out the preview feature PSNativeCommandPreserveBytePipe, and it seems to work in most cases but I've noticed it hangs when piping to Python scripts in certain situations. I have both Python 3.9.7 and 3.11.0 installed and the standard python launcher. I have some simple python scripts:

repr.py, which should print the escaped binary contents of stdin:
```
import sys
print(repr(sys.stdin.buffer.read()).lstrip('b'))
```
echo.py, which just prints it's arguments:
```
import sys
print(' '.join(sys.argv[1:]))
```
I also have cat.exe and echo.exe binaries from Cygwin 64-bit as well as WSL2 (Ubuntu).

The following commands hang with PSNativeCommandPreserveBytePipe enabled, until hitting Ctrl+C:
```
.\echo.py hello | .\repr.py
echo.exe hello | .\repr.py
wsl echo hello | .\repr.py
'hello' | cat.exe | .\repr.py
'hello' | wsl cat | .\repr.py
[byte[]](1, 2, 3) | cat.exe | .\repr.py
[byte[]](1, 2, 3) | wsl cat | .\repr.py
```

However, if I prefix the repr.py script with `python.exe` or `py.exe` (the python launcher) they work as expected:
```
> .\echo.py hello | py .\repr.py
'hello\r\n'
> [byte[]](1, 2, 3) | cat.exe | python .\repr.py
'\x01\x02\x03'
```
Also piping strings or bytes directly from Powershell to the un-prefixed script works:
```
> 'hello' | .\repr.py
'hello\r\n'
> [byte[]](1, 2, 3) | .\repr.py
'\x01\x02\x03'
```
So it seems that this only effects native-to-native commands involving the Python launcher launched implicitly via file association as the target of the pipe. I haven't tried using other scripting languages to see if it effects other implicitly launched binaries. I confirmed that this effects both Python 3.9 and 3.11.

Also `assoc` and `ftype` show the .py file association as:
```
> cmd /c assoc .py
.py=Python.File
> cmd /c ftype Python.File
Python.File="C:\WINDOWS\py.exe" "%L" %*
```

### Expected behavior

```console
The expected behavior for the first 5 hanging commands is to print `'hello\r\n'`, and the last 2 to print `'\x01\x02\x03'`.
```

### Actual behavior

```console
The commands hang and nothing happens until I hit Ctrl+C, which stops the command with no output.

Running the commands with PSNativeCommandPreserveBytePipe disabled does not hang and shows the legacy behavior (bytes are passed as line-separated strings).
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
Pipeline transmission of binary data is amazing to me.
Who can tell me the principle. How does it distinguish between binary data or not?
Can we make a common parameter, similar to 【-PipelineBinaryData】, 
be used to force a single line script to only pass binary data through a pipeline?

**Comment by rmccampbell** [comment]
I believe with the preview feature all native-to-native pipelines are treated as binary data, so no distinction is needed. Between Powershell commands and native binaries it depends on the type, so a byte array e.g. `[byte[]](1,2,3)` is passed as raw binary input. (There are some commands like Get-Content that can return byte arrays with the -AsByteStream flag).

**Comment by 237dmitry** [comment]
I tried your script only on Linux. It works if repr.py has python shebang and  bit for execution.

```
#!/usr/bin/env python
import sys
print(repr(sys.stdin.buffer.read()).lstrip('b'))
```

```powershell
$ gi ./repr.py                                           

    Directory: ~/Desktop

UnixMode     Num   UID   GID      LastWriteTime    Size Name
--------     ---   ---   ---      -------------    ---- ----
-rwxr-xr-x   755  1000  1000   01.07.2023 07:58      82 repr.py

$ /usr/bin/echo "hello" | ./repr.py
'hello\n'

$ [byte[]](1, 2, 3) | /usr/bin/cat | ./repr.py
'\x01\x02\x03'
```

**Comment by rmccampbell** [comment]
Oh probably should have made it clear this is windows. I imagine it is a detail of how programs are executed on windows and not a generic bug.

**Comment by 237dmitry** [comment]
I can’t try on Windows, there is no python and no wsl. There are also no Unix utilities.
Could you give another example, without python, only with native Windows utilities?

**Comment by rmccampbell** [comment]
I found that this also effects ruby in the same way. So calling a ruby script like
```
echo.exe hello | .\script.rb
```
hangs while
```
echo.exe hello | ruby .\script.rb
```
prints expected output.

This confirms it's not specific to Python/the Python launcher, but is an artifact of starting an interpreter via file association.

**Comment by rmccampbell** [comment]
Ok I think this is a minimal example that hangs out-of-the-box on Windows:
```
cmd /c echo hi | .\hello.vbs
```
where hello.vbs is
```
WScript.Echo "hello"
```
Note that .vbs by default runs with the WScript binary which is a GUI app rather than console, and displays a windowed message box. With this pipeline it still shows the window but then hangs the terminal indefinitely even after the window is closed. If PSNativeCommandPreserveBytePipe is disabled or it is called like `cmd /c echo hi | wscript .\hello.vbs` then then it returns control to the terminal without hanging.

**Comment by 237dmitry** [comment]
With `Start-Process` it works as expected. Especially unzipped 7.4.0-preview.4

```
cmd /c echo hi | Start-Process .\Desktop\hello.vbs -ea 0
```

![Screenshot 2023-07-01 161128](https://github.com/PowerShell/PowerShell/assets/78153320/e7fa9004-1674-460c-95c7-c97a6d466adf)

I think the issue is really exists. The pwsh 7.4.0-preview.4 does not properly lead the file associations with enabled this experimental feature.

**Comment by kasini3000** [comment]
```
PS C:\ProgramData\kasini3000> echo "hi" | cscript.exe a:\pscode\TEMP_2023\temp152\aaa.vbs
Microsoft (R) Windows Script Host Version 5.812
版权所有(C) Microsoft Corporation。保留所有权利。

hello
PS C:\ProgramData\kasini3000>

Write-Output "hi" | a:\pscode\TEMP_2023\temp152\aaa.vbs

```
normal 

----

hang

```
cmd /c "echo hi" |  a:\pscode\TEMP_2023\temp152\aaa.vbs
```

**Comment by rmccampbell** [comment]
@237dmitry I think that Start-Process just discards the piped data though. Without the "-ea 0" powershell complains that the command doesn't take pipeline input, and modifying the vbs script to read from stdin it gets EOF. Whereas if I call it explicitly with wscript (or cscript) it receives the input.

I also confirmed that the scripts don't hang on startup; they execute ok until they first try to read stdin and then hang, or hang on exit if they never read stdin. Demonstrated with this script:
```
WScript.Echo "hello"
WScript.Echo WScript.StdIn.ReadLine
```

**Comment by SeeminglyScience** [comment]
I can repro, thanks for the report @rmccampbell! Lookin' into it
