### ISSUE TITLE
The `help` function includes the `-ShowWindow` parameter on non-Windows platforms

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#19904]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`help` is a proxy function for `Get-Help` that is loaded into the initial session state when PowerShell starts. As a proxy function, it defines all the parameters that `Get-Help` has. The definition of the proxy function was created for Windows PowerShell but never adjusted for non-Windows.

See source code - https://github.com/PowerShell/PowerShell/blob/73630960efa0a84475731bfbee4b46c046be72ad/src/System.Management.Automation/engine/InitialSessionState.cs#L4185-L4187

The proxy function includes the `-ShowWindow` parameter for all platforms.

### Expected behavior

```console
PS /home/sdwheeler> help Get-Command -ShowWindow
help: A parameter cannot be found that matches parameter name 'ShowWindow'.
```

### Actual behavior

```console
PS /home/sdwheeler> help Get-Command -ShowWindow
Get-Help:
Line |
  64 |      $help = Get-Help @PSBoundParameters
     |                       ~~~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'ShowWindow'.
```

### Environment data

```powershell
PS /home/sdwheeler> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/sdwheeler> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by theJasonHelmick** [comment]
Thank you @sdwheeler for reporting this issue.Yes, the WG agrees this is a bug.  We will mark this up-for-grabs or look forward to your pr if you'd like to contribute.
