### ISSUE TITLE
Right clicking on the console window doesn't paste special characters

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [PowerShell/PowerShell#19915]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Copy any text with special characters e.g. `’` (U+2019).

Right click on the Powershell window.

### Expected behavior

```console
Special characters should be included in the paste when right clicking on the Powershell window.
```

### Actual behavior

```console
The pasted text is missing special characters.
```

### Environment data

```powershell
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
In my environment, the text skips this character only in the conhost, but not in the Windows terminal.

**Comment by sdwheeler** [comment]
I get the same result as @237dmitry. It works in Windows Terminal. Does not work in conhost. This is a conhost behavior.

**Comment by sdwheeler** [comment]
After further testing, I removed PSReadLine and now the paste worked in conhost.

I tested using this string:

```
"’" | fhx
```

**Comment by theJasonHelmick** [comment]
Thank you @a84r7a3rga76fg for reporting this issue.  This is a known issue with .NET: https://github.com/dotnet/runtime/issues/38966 and we are not able to address this in the PowerShell code base.
