### ISSUE TITLE
Omit validation on the `ValueFromPipeline` parameter in a proxy command

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#19949]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Not sure whether this qualifies as a bug or is actually by design (or even could be resolved):

When creating a proxy command from a script that has validation on the `ValueFromPipeline` parameter, I would expect that validation to be remove for the current item as that item is likely be modified in the `process` block:

```PowerShell
function Test-Cmdlet {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true, Position=0, ValueFromPipeline=$true)]
        [ValidatePattern('^\w+$')]
        [string] $String
    )
    begin {}
    Process { $String.ToUpper() }
    end {}
}

function Test-Proxy {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true, Position=0, ValueFromPipeline=$true)]
        [string] $String
    )
    begin {
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$Null)) { $PSBoundParameters['OutBuffer'] = 1 }
        # $PSBoundParameters['String'] = $PSBoundParameters['String'] -Replace '\W'

        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand('Test-Cmdlet', [System.Management.Automation.CommandTypes]::Function)
        $scriptCmd = {& $wrappedCmd @PSBoundParameters }

        $steppablePipeline = $scriptCmd.GetSteppablePipeline()
        $steppablePipeline.Begin($PSCmdlet)
    }
    Process {
        $_ = $_ -Replace '\W'
        $steppablePipeline.Process($_)
    }
    end {
        $steppablePipeline.End()
    }
    clean {
        if ($null -ne $steppablePipeline) { $steppablePipeline.Clean() }
    }
}

Test-Proxy 'Test 123'
```

### Expected behavior

```PowerShell
TEST123
```
(No error)

### Actual behavior

```console
Test-Cmdlet: C:\Users\boder\GDrive\Scripts\PowerShell\GitHub\Base64-SecureString\bug.ps1:24
Line |
  24 |          $scriptCmd = {& $wrappedCmd @PSBoundParameters }
     |                                      ~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'String'. The argument "Test 123" does not match the "^\w+$" pattern. Supply an argument
     | that matches "^\w+$" and try the command again.
OperationStopped: C:\Users\boder\GDrive\Scripts\PowerShell\GitHub\Base64-SecureString\bug.ps1:31
Line |
  31 |          $steppablePipeline.Process($_)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Object reference not set to an instance of an object.
```

### Workaround

Also modify adjust the `ValueFromPipeline` value in the `begin` block (as comment-out in the issue example):

```PowerShell
$PSBoundParameters['String'] = $PSBoundParameters['String'] -Replace '\W'
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
I think most of the time validations which were needed in the original function are still needed in the proxy. 
It is easier to have the developer remove the validation for the parameter which they fix in the process block, than it is for them to put the validation back if they don't fix it.

**Comment by iRon7** [comment]
@jhoneill,

> I think most of the time validations which were needed in the original function are still needed in the proxy.

 I think most of the time someone creates a proxy is because he wants to extent the function with extra features which might included features that are restricted by the validation. As in my used case were I was trying to write a prototype for [`ConvertTo-SecureString`](https://github.com/PowerShell/PowerShell/issues/19948#:~:text=Support%20newlines%20in%20Hexadecimal%20(and%20Base64)%20strings) that accepts Hexadecimal strings with newlines...

Anyways, I just wanted to reported and I generally agree that this issue low impact.
