### ISSUE TITLE
List help parameters by position instead of by text collation sequence

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#19943]
### Summary of the new feature / enhancement

It would be helpful if `help` listed parameters ordered by `Position` rather than text collation sequence.

Is it possible to encode something in the comment-based help to produce this? Is there a switch on the `help` or `Get-Help` command  to produce this?

**Comment by iRon7** [comment]
@Liturgist,

> It would be helpful if help listed parameters ordered by Position rather than text collation sequence.

How would it help?
To my opinion it is easier to find a parameter back by name than position.
Also knowing that you should try to [Avoid Using Positional Parameters](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingpositionalparameters)

Anyways, you might order them as follows:
```PowerShell
(Get-Help -Full Send-MailMessage).Parameters.Parameter | Sort-Object Position
```

**Comment by sdwheeler** [comment]
In the interactive console you have tab completion, menu completion (<kbd>CTRL</kbd>+<kbd>Space</kbd>), and predictors to help you with entering parameters.

Changing the order that `Get-Help` lists parameters doesn't really work or solve the problem. Cmdlets, scripts, and functions can have multiple parameters sets. A given parameter may be in one position in one parameter set and in a different position (bad idea) or named in another. Give that, what order should `Get-Help` use?

**Comment by Liturgist** [comment]
Different positions in different parameter sets? This is not going anywhere. Closing.
