### ISSUE TITLE
set a random color when initializing the tab

### ISSUE THREAD

**Issue by softchar** [PowerShell/PowerShell#19959]
### Summary of the new feature / enhancement

Like this：
![image](https://github.com/PowerShell/PowerShell/assets/5159098/71520391-16b6-4fe5-885f-75a1dd4833e6)

**Comment by SeeminglyScience** [comment]
Please open your issue on the [microsoft/terminal](https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) repo. PowerShell does not control the color that WT uses for its tabs.
