### ISSUE TITLE
Why do M$ customers have to google for the answer to the top 2 PowerShell use cases? (Setup and Update PowerShell)

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#19978]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Wait until M$ releases a new PowerShell release
2. M$ reports the new release e.g in VS Code or PowerShell
3. A customer decided to upgrade (or install) PowerShell
4. M$ does not offer the answer to the top 2 most important use cases in readme.md: upgrade / install 
5. Even if customers have found the getting started link (probably by accident, because it is not obvious), then they do not easily get the answer to those 2 most important use cases.
6. As usual for modern M$ SW, it's even worse: readme.md does not even have a TOC

### Expected behavior

```console
As a customer, we expect:
1. that M$ employees understand their craft and work professionally from a to z, i.e. including documentation. it should be better than our first-year apprentices create it.
2. and very practical that there is a TOC in readme.md.
3. and in the TOC there is a section that explains how to install and update the SW
4. it is hoped that the instructions for installation and upgrade are done with one command each and that it always works, i.e. installation and upgrade are intelligent and can solve any problems by themselves.
```

### Actual behavior

```console
See "Steps to reproduce"
```

### Environment data

```powershell
Of course, it should work with both PowerShell versions:
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by kilasuit** [comment]
Adding the below from my experience from within the community as FYI to those coming to this issue but do think this is best for @sdwheeler / @michaeltlombardi to add to the below points if they think this is needed.

- There docs both in this repo and in the [PowerShell Docs Repo](https://github.com/microsoftDocs/powerShell-Docs) which get published to the [official PowerShell Docs Pages](https://learn.microsoft.com/en-us/powershell/) - can these help with the points above...?
- Upgrade/install processes can be maintained in **so many** different ways, some managed by individual admins/devs or by IT Teams & some of this is already contained in `readme.md` and in the official docs
  - It is hard to keep all dos updated across all the different places without lots of duplication & all involved are doing best as possible on keeping official docs maintained including the `readme.md` in here 
  - We could amend the `Get PowerShell section in `readme.md` of this repo updated to clarify around upgrade processes. 
- Depending on how you are reading the Readme.md you can in lots of tools get an autogenerated TOC in the previewer of  any markdown file from how the headers are used.
  - Listing a TOC inside of these files adds more error prone work that needs additional effort to maintain.
     - I recommend testing out some other tooling for previewing or reading these files as this might help you going forward, there are lots out there that have this feature, especially those that publish to the official docs repo.


I hope the above helps those reading this issue.

**Comment by doctordns** [comment]
There are a number of methods of instilling PowerShell - you can use the MS Store, any of the package managers (e.g. Chocolatey), or use the install-PowerShell.ps1 script here in this repo. Updating is also easy: you can get AU to update it or have the Store update it for installations via the store. Personally, I just use the install-powershell.ps1 script to install and update.
