### ISSUE TITLE
Unable to launch .pkg installer for 7.3.6 on OSX

### ISSUE THREAD

**Issue by alohawolf** [PowerShell/PowerShell#19974]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Attempt to start .pkg installer.
<img width="276" alt="Screenshot 2023-07-14 at 18 18 38" src="https://github.com/PowerShell/PowerShell/assets/20135961/0b6b3126-c60a-40bb-af9c-6b5797ccf67b">

### Expected behavior

```console
Installer should launch
```

### Actual behavior

```console
Installer does not launch
```

### Environment data

```powershell
Intel OSX 13.4.1(c)

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/REL…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Are you able to bypass this OS check via the `Privacy and Security` tab in your system settings on Mac? usually there should be an option to open unverified packaged with password there.

**Comment by StevenBucher98** [comment]
It should look something like this: 
![Screenshot 2023-07-17 at 2 28 30 PM](https://github.com/PowerShell/PowerShell/assets/20605456/1cdbec4b-3348-4857-9a5d-92c7b006cce2)
Another option that I recommend is downloading via `brew` it can make upgrading a lot easier

**Comment by alohawolf** [comment]
Yes, I'm able to get to the installer via that route - normally unsigned software triggers a different error message however.

I actually forgot that I had installed it from brew before - so I've solved my particular upgrade issue.

Is this a normal error message? if so perhaps the release page should be updated with that information.

**Comment by StevenBucher98** [comment]
This error message is expected, we have documented some instructions to bypass here: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.3#installation-via-direct-download

**Comment by StevenBucher98** [comment]
You can also use `Unblock-File`, https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.3
