### ISSUE TITLE
pwsh does not wait to run when in a pipe

### ISSUE THREAD

**Issue by Gremious** [PowerShell/PowerShell#19984]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Trying to run a very simple set of commands: `fd '(ps1$|sh$)' C:\Users\Username\bin\ | fzf --sync | pwsh`

`fd` every ps1 script in my `~/bin` folder, pipe them through synchronous fzf for selection, pipe fzf result to run in powershell (tried with `-File`/`-File -` also).

### Expected behavior

```console
I make an fzf selection, then `pwsh` launches runs the ps1 script in the terminal.
```

### Actual behavior

```console
A new `pwsh` launches in the middle of my fzf selection, never waits for the pipe to get to it. Running this in Windows PowerShell, as opposed to Powershell 7, actually produces the expected behavior.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
Can you try `... | pwsh -noprofile -command -` instead?

**Comment by Gremious** [comment]
Yep, that works exactly as expected! (thank you!)

I am not sure if it is intended behavior for `pwsh` to launch itself in the middle if a pipe, so I'll keep the issue open, feel free to close as appropriate.
