### ISSUE TITLE
Parsing of first symbol ignored after ${function:

### ISSUE THREAD

**Issue by ImportTaste** [PowerShell/PowerShell#19998]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Expected / Actual behavior

```powershell
&{
	"`n" + 'EXAMPLE 1' + "`n"
	${function://foo} = { $MyInvocation.MyCommand.Name + "  : success!`n" }
	"This will work, but shouldn't:"
	/foo
	"This is NOT WORKING, but SHOULD:"
	//foo

	"`n" + 'EXAMPLE 2' + "`n"
	${function::\bar} = { $MyInvocation.MyCommand.Name + "  : success!`n" }
	"This will work, but shouldn't:"
	\bar
	"This is NOT WORKING, but SHOULD:"
	:\bar

	"`n" + 'EXAMPLE 3' + "`n"
	${function:::qux} = { $MyInvocation.MyCommand.Name + "  : success!`n" }
	"This will work, but shouldn't:"
	:qux
	"This is NOT WORKING, but SHOULD:"
	::qux

	trap {
		[Console]::ForegroundColor = $Host.PrivateData.ErrorForegroundColor
		$Host.UI.WriteErrorLine(('{0} : [{1}]' -f $_.InvocationInfo.InvocationName, $_.FullyQualifiedErrorId))
		[Console]::ResetColor()
		[Console]::WriteLine()
		continue
	}
}
```

### Description

The first symbol after `${function:` is ignored in both PowerShell Desktop and Core. In the case of Example 3, two symbols are ignored, though that seems to be a special case. @mklement0's [excellent reply](https://github.com/PowerShell/PowerShell/issues/19998#issuecomment-1650431549) explains this far better than I could.

As a workaround, I've been using `${function::` instead of `${function:` when necessary.

### Use case

I create short, script-contained functions that start with `//` (since `/` can't be used in linux paths and linux paths never start with two slashes). Sometimes I need to call these functions as part of a job, so I need to bind them with `using:` like so:

```powershell
function //foo { 'hello' }
$job = Start-Job {
    ${function:://foo} = ${using:function:://foo}
    //foo
}
Receive-Job $job -Wait -AutoRemoveJob
```

### Environment data (Core)

```text
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Environment data (Desktop)

```text
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.3031                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.3031                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
To add some context:

Pragmatically speaking:
 *  `::` after `function` indeed seems to be a reliable workaround that even works with `:`-prefixed function names (e.g. `${function:::foo} = ' "hi" '; :foo`
    * Whether that is by design or not, I don't know.
    * Additionally, you would expect `${function::bar} = ' "hi" '; :bar` to work, but it does _not_: the second `:` is _invariably_ considered part of the separator.
---

As for the use of `\` and `/` after `function:`

In namespace variable notation, which fundamentally supports _paths_ - even though in the case of _functions_ the concept of a _path_ doesn't apply -  `${function:foo}` and `${function:\foo}` and `${function:/foo}` are _equivalent_, on _all_ platforms.

That is, a `\` or `/` following the `:` is considered a _path separator_.

 * Surprisingly, however,  _two_ path-separator instances seem to be treated as a _single_ path one, namely if either both or at least the _second_ one is the _platform-native_ path separator (this is _reminiscent_ of the way it works  in _file-system_ paths (e.g., on Unix `ls ///tmp` in lieu of `ls /tmp` works just fine), but unexpected in this context).

 * Examples:
   * Windows: `${function:\\help}` works the same as `${function:\help}` (and `${function:help}`)
   * Unix: `${function://help}` works the same as `${function:/help}` (and `${function:help}`)
   * Replacing the _first_ separator after `:` with `/` on Windows and with `\` on Unix works too, but _not_ the second, which has to be platform-native.

**Comment by IISResetMe** [comment]
Alternative option for registering function names starting with slash:

    New-Item function:\ -Name '//foo' -Value {return 123}

**Comment by JamesWTruher** [comment]
@PowerShell/wg-powershell-engine discussed this, and while we understand this behavior may be surprising, we are concerned that any change here would lead to a breaking change. We don't believe we should make any changes in this space.
