### ISSUE TITLE
The man page for `pwsh` on Linux/macOS is not in sync with `pwsh -?`

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#19990]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run `man pwsh` on Linux or macOS. Compare that to the output from `pwsh -?`.

### Expected behavior

```console
The help shown does not match the output of `pwsh -?`. There are many missing options and the descriptions are not as detailed.
```

### Actual behavior

```console
see above
```

### Error details

```console
Also, the output of `pwsh -?` contains a lot of Windows-specific information. We should create non-Windows string resources for that output.
```

### Environment data

```powershell
PS> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
There are not man pages in archive distribution (tar.gz) at all. 7.4.0-preview.4

**Comment by sdwheeler** [comment]
> There are not man pages in archive distribution (tar.gz) at all. 7.4.0-preview.4

That is by design. The man page has to be installed, so it is only included in installable packages (rpm, deb, or pkg for macOS). 

There is only one man page that gets installed. It is built from the following source file:
- https://github.com/PowerShell/PowerShell/blob/master/assets/pwsh.1.ronn

You could submit a feature request to have the man page included in the archive distribution (tar.gz). However, it would still be a manual install.
