### ISSUE TITLE
Protocol about communicating with native binaries with strong type.

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#1999]
In this situation

``` powershell
cmdlet | native.exe | cmdlet
```

Purpose a protocol to acquire typed output from `native.exe` directly.

**Comment by vczh** [comment]
@be5invis Why not author a PS script to invoke native.exe and parse its output to a strong typed value? But this is not a good way to publish a tool, so maybe PowerShell can search native.exe.ps, which should be put in the same folder as native.exe .

**Comment by GeeLaw** [comment]
Defining a universal and convenient protocol is hard. It is better to leave the gluing job to each native tool author. Like, anyone can write a native utility and a PowerShell cmdlet that does marshalling and calling.

**Comment by DHowett** [comment]
That only holds up until we have already done it.

```
(australis) ~\Projects\ShowArgs % .\Debug\ShowArgs.exe {gci}
0  : C:\Users\Dustin\Projects\ShowArgs\Debug\ShowArgs.exe
1  : -encodedCommand
2  : ZwBjAGkA
3  : -inputFormat
4  : xml
5  : -outputFormat
6  : text
```

Now we have an informal, non-universal, and inconvenient protocol that does some gluing. :frowning:

**Comment by oising** [comment]
I'm not sure if it's generally known (probably not) but native commands can already emit typed object(s) consumable by PowerShell in the line-oriented textual CliXml format, but it requires that the first line to be the magic string `#< CLIXML` -- there's a space between the `<` and `CLIXML`.
