### ISSUE TITLE
Microsoft Authenticator / Powershell Versions Greater than 7.3.4

### ISSUE THREAD

**Issue by lgroves317** [PowerShell/PowerShell#20003]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Our company uses Microsoft Authenticator to connect to Exchange Online. 
This worked fine on PowerShell until 7.3.5 was released.
It is still not working in version 7.3.6. 

After we enter the Authenticator code in Microsoft Edge, we get an error in Edge saying:
 "The connection for this site is not secure."
Then the Connect-ExchangeOnline command hangs in the PowerShell console.

If we use PowerShell 7.3.4 or below, we get the message :
Authentication complete. You can return to the application. Feel free to close this browser tab.
Then we get connected successfully to Exchange Online.

### Expected behavior

```console
Get connected to ExchangeOnline
```

### Actual behavior

```console
Connect-ExchangeOnline command hangs in PowerShell console.
```

### Error details

<details>
<summary>stack trace of separate Get-ChildItem issues</summary>
<code>
Exception             :
    Type       : System.UnauthorizedAccessException
    TargetSite :
        Name          : CreateDirectoryHandle
        DeclaringType : System.IO.Enumeration.FileSystemEnumerator`1[TResult]
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Access to the path 'C:\Users\john.doe\Templates' is denied.
    Source     : System.Private.CoreLib
    HResult    : -2147024891
    StackTrace :
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean
ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String
expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget
searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at Microsoft.PowerShell.Commands.FileSystemProvider.Dir(DirectoryInfo directory, Boolean recurse,
UInt32 depth, Boolean nameOnly, ReturnContainers returnContainers, InodeTracker tracker)
TargetObject          : C:\Users\john.doe\Templates
CategoryInfo          : PermissionDenied: (C:\Users\john.doe\Templates:String) [Get-ChildItem],
UnauthorizedAccessException
FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
InvocationInfo        :
    MyCommand        : Get-ChildItem
    ScriptLineNumber : 1
    OffsetInLine     : 121
    HistoryId        : 8
    Line             : Get-ChildItem -force . -ErrorAction SilentlyContinue | ? { $_ -is
[io.directoryinfo] } | ForEach { $numberOfFiles = 0 ; Get-ChildItem -recurse -force $_.fullname
-ErrorAction SilentlyContinue | ? {$_ -is [io.fileinfo] } | % {$numberOfFiles += 1} ; $currentDirInfo =
[pscustomobject]@{path = $_.fullname; numberOfFiles = $numberOfFiles} ; $currentDirInfo } | Sort-Object
numberOfFiles -Descending
    PositionMessage  : At line:1 char:121
                       + … Files = 0 ; Get-ChildItem -recurse -force $_.fullname -ErrorAction Si …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-ChildItem
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
</code>
</details>

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/10578777/78e0a975-9778-4536-a779-1db23a216b0d)

**Comment by TravisEz13** [comment]
I think this has to be related to one of the security updates released in 7.3.5.  These were all .NET updates.  One question is, did it break in 7.2.12 as well?  

I'm trying to get MSAL/Exchange Online involved, but I would recommend you open a support case with Exchange Online.

**Comment by lgroves317** [comment]
It worked on 7.3.4.Sent from my iPhoneOn Jul 24, 2023, at 2:08 PM, Travis Plunk ***@***.***> wrote:﻿
I think this has to be related to one of the security updates released in 7.3.5.  These were all .NET updates.  One question is, did it break in 7.2.12 as well?
I'm trying to get MSAL/Exchange Online involved, but I would recommend you open a support case with Exchange Online.

**Comment by TravisEz13** [comment]
I spoke to exchange online and they have asked that you open a support request:  https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide

**Comment by ritikmit** [comment]
@lgroves317 Can you also elaborate on this point? -- "Our company uses Microsoft Authenticator to connect to Exchange Online."

**Comment by lgroves317** [comment]
Awesome. Thank you!Sent from my iPhoneOn Jul 27, 2023, at 12:11 PM, Travis Plunk ***@***.***> wrote:﻿
I spoke to exchange online and they have asked that you open a support request:  https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide
Get support - Microsoft 365 adminLearn how to get online or phone support for your Microsoft 365 for business subscription. You must be an admin for a business subscription to get support.

**Comment by lgroves317** [comment]
> @lgroves317 Can you also elaborate on this point? -- "Our company uses Microsoft Authenticator to connect to Exchange Online."

We use two factor authentication to connect to M365 for all users. We just happen to use MS Authenticator. When one us needs to access Exchange Online, a browser is launched asking for the MS Authenticator code. Usually we would just type the code in and everything was copacetic.

After the update to PS 7.3.5, it just stopped working.

**Comment by JamesLear92** [comment]
Not sure why this was closed. I have exactly the same issue. 
Is there a work around?

**Comment by lgroves317** [comment]
I have a ticket open with Microsoft support. They said they would be getting back to me by tomorrow with next steps. I'll post their reply when I get it.

**Comment by lgroves317** [comment]
> I have a ticket open with Microsoft support. They said they would be getting back to me by tomorrow with next steps. I'll post their reply when I get it.

I just got off a call with MS Support. They had me send them more log files.
