### ISSUE TITLE
Lone assignment statements (including pre/post-increment) don't result in a value in string interpolation

### ISSUE THREAD

**Issue by Hashbrown777** [PowerShell/PowerShell#20007]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a variable, attempt to insert it into a string whilst acting upon it (`=`, `++` or `--`).

### Expected behavior

```console
PS> $bob = 7; "_$(++$bob)_"
_8_
```

### Actual behavior

```console
PS> $bob = 7; "_$(++$bob)_"
__
#$bob is still successfully set to `8`, though
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Debian GNU/Linux…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, …
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/6907206/ad2ce013-6c43-40a3-8039-d4d5fe4a4c49)

**Comment by jhoneill** [comment]
It's not a string interpolation thing.  To my eye it looks like a bug in the evaluation of $()

I only tested this with ++ but ... 
Assignment , including =, +=, -=,  /=  does not - by default return a value. += 1, and -= 1 don't so -- and ++ follow the same defaults  so  `$bob ++`  or `++ $bob`  return nothing.  

But   `"This is " + ($bob = 7)` sees the 7 and `$x = $bob = 7 `  works as `$x = ($bob = 7)` and   `1 + ++ $bob`   or  `1 + $bob ++`   work as `1 + (++ $bob)` / `1 + ($bob ++ )` respectively.  

Usually putting $ in front of () forces evaluation before other things - in fact that's how I explain it in string interpolation  but it doesn't work with assignments 

`($bob = 7)` returns 7 
`$($bob = 7)` returns nothing but DOES set $bob  all the +=, /= etc and ++ seem do the same. 

 `1 + (++ $bob)` returns 9 but ` 1 + $(++ $bob)`  gives 1

You're seeing it in string interpolation, but it happens outside.  To my mind that's a bug. Fixing it might break existing scripts that rely on the behaviour but I can't see a case where anyone would.

**Comment by mklement0** [comment]
I think the behavior is as designed, if a bit surprising: 

* `$(...)` outputs and - inside `"..."` also stringifies - _whatever `...` would produce as output when run directly_.
* Assignment statements, including increment/decrement statements, do _not_ produce output, hence `$(++$bob)` produces no output, which stringifies to the _empty string_.
   * In isolation, `++$bob` is just an assignment (as the equivalent `$bob += 1` is), and therefore produces no output - enclosure in `$(...)` or `@(...)` does _not_ change that - only `(...)` does (see below).
   * It is only in the context of _expressions_ that increment/decrement operations return a value; e.g. `1 + ++$bob`
* Enclosing assignments in `(...)` causes the assigned value to be _passed through_, so the solution is:
  *  `$bob = 7; "_$((++$bob))_"`
  * A small caveat is that with _post_-increment/decrement, it is the _previous_ value that is passed through; thus, the following yields `'_0_'` (but `$bob` is correctly incremented):
      * `$bob = 0; "_$(($bob++))_"`

**Comment by jhoneill** [comment]
For completeness on $() and @() 

```
PS>  $a , $b , $c = 1,2,3

PS>  $(++ $a , -- $b , $c)
2
1
3

PS>  @(++ $a , -- $b , $c)
3
0
3
```

Which means as well as `$(  ($bob++)  )`  one can use `$(,++$bob  )` 

```
PS> $bob = 7; "_$(,++$bob  )_"
_8_
 ```

**Comment by Hashbrown777** [comment]
@mklement0 it's not by design, it's a byproduct of a different area which *is* by design; the area you noted in your comment as well as mine. Fixing *this* unintended side effect wouldn't break existing scripts as I'm specifically talking about string interpolation, not changing the behaviour of those other areas, just as there is existing special behaviour for function calls as shown.

You did mention one word though that would probably make a way better title of my submission; "String interpolations should be treated as expressions" (id est forcing values out of assignments).
It's important to note, esp for @jhoneill too, that `"$()"` and `$()` are **not** the same things at all.

The bit about pre/post increment isnt a caveat.. that's exactly what they're meant to do. Your description that it passes through the "assigned variable" just isn't correct. Assignments all have a *result*, and += /= %= -= *= et cetera as well as preincrement have a result which is the assigned value, post increment has a *result* which is the original value.

These results are ignored in powershell if it can be interpreted as not being part of an *expression* (for the express purpose of not dumping mere assignments to the stream/host every time you use one without piping to Out-Null), which I'm saying is *incorrect behaviour with respect to string interpolation*.

James, one could parenthesise or arrayify the assignment to force an expression interpretation, but this is a workaround for a bug, not what I would say is what powershell users should [have to be] be doing. Likewise imagine if for function calls you had to do that all the time? It makes the language worse and more bash-like with it's myriad of confusing syntax requirements.

The intention in powershell with these assignment statements was to be smart about it, as exemplified with the function calls (eg `received(++$bob)`), and I'm just saying that string interpolation was simply forgotten about when this existing intended behaviour was implemented, which we can rectify here.

**Comment by mklement0** [comment]
@Hashbrown777:

> it's not by design

* Unless you've designed it or can point to documentation explicating the design, you don't know whether it is by design, and you shouldn't make definitive claims.

* This is why I said _I think_ it's by design, and I've given a _potential_ rationale - which, as far as I can tell, offers a straightforward conceptualization.

> `"$()" and $() are not the same things at all.`

`"$()"` is `$()` _with stringification_, as I've suggested. 

And conceptualizing it as that makes the most sense to me.

Changing the fundamental behavior of `$()` _just because it happens to occur in the context of string interpolation_ seems ill-advised.

As an - inconsequential - aside:

>  it passes through the "assigned variable" just isn't correct.

That's probably  because I never said that.

What I _did_ say was: "causes the assigned value to be passed through" - which, indeed, is _typically_, but _not always_ correct - namely not in the post-increment/decrement case, hence my caveat to clarify this exception.

**Comment by Hashbrown777** [comment]
That's fair, but I'm not saying to change the behaviour of `$()`.

I would ask if `"$()"` really is `$()` under the covers, because I'm assuming `"$()"` is just dressed up to look like `$()` but is actually it's own thing, which could well be wrong.

In that case I would instead argue to change `"$()"` to actually be `()` under the covers, which would fix everything and not change existing expected behaviour of `$()`.

---

To your aside though;
 > causes the assigned value to be passed through

It *doesn't*, is what I'm saying; it *causes the **result** to be passed through*, which indeed with your clarification ***typically** is the assigned value*. I stand by that conceptualising it your way was wrong.

**Comment by 237dmitry** [comment]
> it's not by design

In Windows PowerShell the same behavior. It's rather by design.

**Comment by Hashbrown777** [comment]
> In Windows PowerShell the same behavior. It's rather by design.

@237dmitry they're built from the same source, of course it has the same behaviour, that's why I didn't mention linux in the bug report. I actually discovered it in windows (you'll see the screenshot is actually windows), linux is just where I have the preview installed (as the requirement for bug submission is using the latest build of powershell).

Please provide a link to documentation; stating it's by design merely because you can observe something is less helpful than no comment at all. Quite literally every bug ever would be 'by design' using that logic. I think Michael would be best suited to tracking that down so I'd leave it to him.

**Comment by 237dmitry** [comment]
> that's why I didn't mention linux in the bug report.

Nothing different in this.

PS. I meant PowerShell 5.1

**Comment by Hashbrown777** [comment]
So did I, I program exclusively in the standard powershell that comes with win10 for compatibility.

Again, that just proves that it's *old*, jury's still out on *intentional*. I mean we only just recently got executable->executable binary pipes (issue 1908, deliberately unlinked because it creates references in the other thread).
We cant improve the language because some ancient oversight exists in 5.1 now?

**Comment by 237dmitry** [comment]
> We cant improve the language because some ancient oversight exists in 5.1 now?

I have a feeling that you cannot read or are unable to understand what you read. I wrote that this is how it was intended and migrated from PowerShell 5.1. I didn’t say a word that there was no need to improve and fix it. That's all. I agree with you, why did you get the idea that I'm trying to refute you?

**Comment by Hashbrown777** [comment]
It came from your asserting this
> It's rather by design.
In conjunction with the entire thread being about whether it's intended behaviour [or otherwise something that should be fixed].

Sorry if I misread what you meant, but I'm genuinely failing to interpret it another way :(

**Comment by 237dmitry** [comment]
I just meant that this behavior is from the first versions of PowerShell, which means it's by design. I also sorry for not making my point clear.

**Comment by Hashbrown777** [comment]
Nah that's cool. Online text chats can get argumentative quickly :/ yeah I guess my only point would be that doesnt make it by design at all, just potentially unnoticed all this time

**Comment by jhoneill** [comment]
> 

>. It's important to note, esp for @jhoneill too, that `"$()"` and `$()` are **not** the same things at all.


$ basically says "value of"  `$Name` is the value of the variable "name" and `$( statement   )`  is the value(s) returned by the statement.  This is true inside or outside quotes.     
So this ` for ($i = 0 ; $i -lt 5 ; $i ++) {$i}  |  where {$_ % 2}`   gives a syntax error. A for _statement_ (unlike the foreach cmdlet) can't be piped.  But  for `$( for ($i = 0 ; $i -lt 5 ; $i ++) {$i} ) |  where {$_ % 2}  `   says "take the values from the for statement and pipe those" which does work and if we wrap it in double quotes     
` "My numbers are $( for ($i = 0 ; $i -lt 5 ; $i ++) {$i} ) " ` the evaluated statement works . 

Many people don't realise that this parses `$PSVersionTable.       PSVersion` -  Powershell allows space after the `.` when used as a _member_ operator.   (`.` at the start of a line  or in, for example $x = .  .\profile.ps1 is the call_in_current_scope operator). 
That gives a problem for string interpolation, and how to parse  `"$PSVersionTable.PSversion"` and the implementation goes for simple parsing $ followed by alphanumerics treats those as a variable name and $(     ) works as outside. 


> James, one could parenthesise or arrayify the assignment to force an expression interpretation, **but this is a workaround for a bug, not what I would say is what powershell users should [have to be] be doing.**

Totally agree. It's a work round BUT I'm also advancing that to support  that this is a long standing accident of implementation, not a deliberate design.  

Here's another case. 
```
PS>  $x = 2

PS>  if (  $x -1 ) {"foo"}
foo

PS>  if ($($x -1)) {"foo"}
foo

PS>  if (  $x -- ) {"foo"}
foo

PS>  $x = 2

PS>  if ($($x --)) {"foo"}

PS>
```
And it is not just increments or decrements, it's a all assignments 
```

PS>  if ($s=[datetime]::Now.Second) {"Not the top of a minute"}
Not the top of a minute

PS>  if ($($s=[datetime]::Now.Second)) {"Not the top of a minute"}

PS> 
``` 

> I'm just saying that string interpolation was simply forgotten about when this existing intended behaviour was implemented, which we can rectify here.

I don't think that is the case - I think string interpolation is surfacing a problem that exists elsewhere - the difference being that outside strings the writing of `$()` is usually optional.

**Comment by Hashbrown777** [comment]
> $ basically says "value of" `$Name` is the value of the variable "name" and `$( statement )` is the value(s) returned by the statement. This is true inside or outside quotes.

I'm still not convinced that they are meant to be the same things, they are described in the docs to be used for similar things and on the face of it use the same characters to express it, but I still see there's some nuance to the intention behind them both.
Take likewise regular expressions in javascript; `\t` for example 'says' "I'd like a tab character". However even though `/\t/` and `new RegExp('\t')` do both result in a state machine looking for tab characters they go about it by different mechanisms.
The former tells the regex engine directly "hey I'd like you to search for a tab" in the same way you can directly ask it to search for a digit `\d`, however the latter tells the interpreter "hey I'd like a literal tab character in this string; oh, and hey regex engine, can you search for this string?".

> Many people don't realise that this parses `$PSVersionTable. PSVersion` - Powershell allows space after the `.` when used as a _member_ operator.

That's kind of what I'm getting at; `$()` could well (and I'm saying should-well-if-not) be not `"$()" #but inside strings` at all, it's just something people don't run into so they don't know.
I feel this distinction is important because I do not want to get this ticket caught up in either of the following scenarios:
 - do we change the behaviour of `$()` globally?
 - do we add additional logic on top of it specially for `"$()"` as it wraps `$()`?

It should really, hopefully, only be:
 - ah we just gotta do something for `"$()"`... (Idk, I didn't help make this amazing software).

I just want to keep this issue on track, or if it is to go off track, that there's some *proof* for that, other than "it sure fits the way I've always looked at it!".
To reference 1908 again, that issue was specifically about powershell interpreting binary data coming out of an exe, manipulating it wherever it saw a newline, and sending broken data to another exe (think `tar | gzip`).
Other people, I mean quite rightly, came in with "Yes! I have trouble sending binary data like `myCmdlet | gzip`" and "what about receiving data like `gunzip | myCmdlet`?!", but these other problems have run-on sideeffects in trying to solve them.

I think those other cases, albeit difficult but nevertheless valid, are still unresolved, yet the issue at hand, `tar | gzip` was so obviously broken, and so narrow in scope so that there weren't really any chance of accidentally breaking legacy code that it was able to get a patch.
`"$(++bob)"` is *obviously* exhibiting unintentional behaviour (my opinion, granted) and is so narrow in scope that either no-one is already using it in their code, or they are already working around it; it'll break no code to make correct.
Whilst there may be issues with `$()` I don't think it really helps to declare that those and `"$()"` are one-and-the-same until *this* issue is triaged and we can confirm with that assigned dev that such things might be related and discussed.

>  (`.` at the start of a line or in, for example $x = . .\profile.ps1 is the call_in_current_scope operator). That gives a problem for string interpolation, and how to parse `"$PSVersionTable.PSversion"` and the implementation goes for simple parsing $ followed by alphanumerics treats those as a variable name and $( ) works as outside.

See? You're waaay off into the weeds now and we still don't know exactly how or even if this ties back to actual string insertion syntax (unless you're the actual dev that made it or sleuthed into the code).

> And it is not just increments or decrements, it's a all assignments

Yes, my title reflected that too. Michael had me realise above that *if* '`"$()"` is built using `$()`' then;
> ...this ticket would instead be a call to change "$()" to actually be ["() [-with-stringification]"](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.3#grouping-operator--) under the covers, which would fix everything and not change existing expected behaviour of $(), nor I think have any ramifications for existing uses of string interpolation either.

So none of that matters.. hopefully.

---

> So this ` for ($i = 0 ; $i -lt 5 ; $i ++) {$i} | where {$_ % 2}` gives a syntax error. A for _statement_ (unlike the foreach cmdlet) can't be piped. But for `$( for ($i = 0 ; $i -lt 5 ; $i ++) {$i} ) | where {$_ % 2} `

As an aside I don't think I've ever *needed* to use `$()`.
In this scenario specifically I'm more fond of `.{}` id est `.{ for ($index = 0 ; $index -lt 5 ; ++$index { $index } } | ?{ $_ % 2 }` because this would actually maintain the piping nature (like blocking, processing arguments as they're generated et cetera), whereas `$()` would buffer all the outputs into one big array and try to push them down the pipe all at once...
Other cases fit use of `()` or `@()` instead.

**Comment by jhoneill** [comment]
> I feel this distinction is important because I do not want to get this ticket caught up in either of the following scenarios:
> 
> * do we change the behaviour of `$()` globally?
> * do we add additional logic on top of it specially for `"$()"` as it wraps `$()`?
> 
> It should really, hopefully, only be:
> 
> * ah we just gotta do something for `"$()"`... 

I **think** (without knowing the internals either), that  it needs to be changed globally OR there would be special logic to something different inside and outside strings.  

> As an aside I don't think I've ever _needed_ to use `$()`.

IIRC it was Bruce Payette or Jason Shirk who gave me the trick of `  $( unpipeable statement  )  |   ....`    
I think ` . {  unpipeable statement  } ` is functionally the same, with a trivial amount of extra work to make a script block and then execute it.  
But I'm fairly sure $() is the same inside and outside a string - so fixing this anomaly in one place _should_ fix it in both.

**Comment by Hashbrown777** [comment]
> IIRC it was Bruce Payette or Jason Shirk who gave me the trick of ` $( unpipeable statement ) | ....` I think `. { unpipeable statement }` is functionally the same

Well let me give you this one! It's quite actually different, say your for loop is network bound and takes seconds to execute, and/or your processing on the other end of the pipe is cpu intensive and takes a while to chug through each one, `.{}` will go way faster as `$()` waits for the internal statement to complete, then tries to feed all the data at once down the pipe

Try 

    .{ for ($index = 0; $index -lt 3; ++$index) { Sleep 1; $index } }

Vs

    $(for ($index = 0; $index -lt 3; ++$index) { Sleep 1; $index })

Not only that but if it produces *a lot* of data the overhead of that alone I've seen slow down powershell as opposed to streaming it as soon as it comes through.

**Comment by jhoneill** [comment]
> > IIRC it was Bruce Payette or Jason Shirk who gave me the trick of ` $( unpipeable statement ) | ....` I think `. { unpipeable statement }` is functionally the same
> 
> Well let me give you this one! It's quite actually different, say your for loop is network bound ....

You're correct - for those cases where the statement is doing something which involves a lot of wait intervals, and the if the processing afterwards is significant then the script-block method does the same job more efficiently - the example is 1[pause]2[pause]3[pause] vs [pause][pause][pause]123 but I get the point.. 
But we're getting off the track and risk losing your original point that $( )  has anomalous behaviour with assignments, and mine that the issue is real, wider than your observation, and warrants attention.

**Comment by mklement0** [comment]
To provide as much context as I can think of (without - for now - weighing in on whether a change is warranted at all, and, if so, which):

* On a meta note: 

  * That something is _by design_ doesn't necessarily mean that it cannot be changed - but the bar for justifying what then amounts to an  _invariably breaking_ change will be higher.
  * In particular, the design _intent_ should be clarified, so that it can be assessed what may be lost / broken in the event of a change.
  * Either way, the impact on backward compatibility must be assessed, and how much existing code there is that relies on the by-design behavior likely corresponds to how intuitively clear / well-documented the design intent is.
  * Key elements of good design are not to contravene users' intuitive expectations and achieving the design intent with _as few rules as possible_ that users have to remember.

* As for whether the behavior is by design:

  * Turns out that it _is_ by design, according to the [language specification](https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-01) (which dates back to v3 and is the latest one available):
    * [7.1.1 Grouping parentheses](https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-07?view=powershell-7.3#711-grouping-parentheses) specifically spells out for the need for `(...)` enclosure inside `$(...)` for a _top-level_ expression with _side effects_ (meaning _assignment_ operations, including increment and decrement)  in order _to produce output_ - search for `"taking place in a string literal"` to find the specific example.

   * The - simple - rules [spelled out above](https://github.com/PowerShell/PowerShell/issues/20007#issuecomment-1646078327) are therefore consistent with this design intent; to recap:
     * `$(...)` produces the same output as `...`; if `$(...)` happens to be placed inside `"..."`, whatever output there is is _stringified_; if there is no output, the result is the _empty string_.

       * As an inconsequential aside, there _is_ a difference: Strictly speaking, when `...` outputs "nothing", i.e. an "enumerable null" ("Automation null", i.e. [`[System.Management.Automation.Internal.AutomationNull]::Value)`](https://learn.microsoft.com/en-US/dotnet/api/System.Management.Automation.Internal.AutomationNull), `$(...)` outputs a genuine `$null`. 

     * `$(...)` encloses _one or more statements_; a statement _exclusively_ comprising a side-effect-producing  _assignment_ expression such as  `++$bob` (or `$bob += 1` or `$bob = 42`) has _no_ output; hence `$(++$bob)` has no output.
     *  Since enclosing a top-level assignment operation in `(...)` is required in order to produce (pipeline) _output_, something like  `$((++$bob))` is therefore needed.

* When does a top-level assignment operation _implicitly_ output a value?

  * Only in  _conditionals_ of language statements such as `if`, `while`, `switch`, ... and even in a `foreach` loop's _input specification_ (e.g. `foreach ($i in $j = 42) { $i }` - this is the _de-facto_ behavior; I'm not sure where that is documented; it is _not_ spelled out in the [Statements](https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-08) chapter.

  *  With the exception of `foreach`, the syntactically required presence of `(...)` (e.g., in `if ($files = Get-ChildItem *.txt) { ... }`) can serve as a visual reminder of this behavior.

* In what contexts is `$(...)` useful / required?

  * `$(...)` _required_ inside `"..."` (interpolating aka _expandable_ strings)  in order to embed anything that goes beyond merely referencing _a variable (value) as a whole_ (e.g. `"$var"` vs. `"$($var.Property)"`).
    * Arguably, this is the _primary_ use case for `$(...)`

  * `$(...)` is _useful_ in the following contexts _outside_ `"..."`:

    * To allow the output from a language statement (compound statement) such as `foreach` and `switch` to act as _pipeline input_:

      * As noted, using `. { ... }` or `& { ... }` is the preferred alternative for providing the output from `...` in a _streaming_ fashion (rather than the _collect-all-output-first_ semantics implied by `$(...)`)

      *  However, the `$(...)` approach may come into play:

         * In cases where _collect-all-output-first_ semantics is _explicitly desired_, such as to collect input to a subsequent command in full, up front, so as to ensure that processing in the subsequent command cannot interfere with input collection.

         * In _existing code_ written by users unaware of the `. { ... }` / `& { ... }` alternative.

         * See also: #6817

    * To allow the output from either a language statement and/or or from _multiple_ statements to act as _command arguments_; e.g. (somewhat contrived):

        * `Write-Host 'This year and last year:'  $((Get-Date).Year; (Get-Date).AddYears(-1).Year)`
        * Note: For _single_, _non-language_ statements, `(...)` is sufficient and preferable; e.g.:
          * `Write-Host 'This year:' (Get-Date).Year`

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this. The behavior is by design as described by @mklement0. While we can see the merits of treating increments differently when inside an expandable string, we cannot change that at this point due to how much code it would break.
