### ISSUE TITLE
Dockerfile should build PowerShell from current repo state

### ISSUE THREAD

**Issue by colemickens** [PowerShell/PowerShell#2001]
The Dockerfile in the repo doesn't actually build from source.

The Dockerfile in a repo should be able to build the repo from it's current state. As of right now, I can't `git checkout` an old revision and then do a `docker build` to get a container containing the state of the container.

I filed a similar issue in [the new azure-cli](https://github.com/Azure/azure-cli/issues/168) repository and they moved to a Dockerfile that builds from the real state of the repo.

As-is, this project is missing out on the benefits of Docker. I want to be able to clone this repo and type `docker build -it ps .` and get a build of `master` inside a Docker container. This makes it easier for others to contribute.

(It also directly lends itself to making #2002 easier).

**Comment by RobertKozak** [comment]
I took a shot at this with https://github.com/RobertKozak/Docker-Powershell.

my setup.sh is based on /Tools/download.sh but I had to remove sudo and did some apt-get cleanup but I am not familiar with Centos or Darwin package system to know what to clean up maybe someone else can look at it and suggest changes so we can make a proper PR

**Comment by colemickens** [comment]
That's basically the opposite of what I'm asking for. There's already a `Dockerfile` in this repo that just installs the latest release.

The `Dockerfile` should live in the source code tree and should be able to build the container, from source, from the same checkout.

**Comment by bjtucker** [comment]
I've made a dockerfile that does build powershell in #2192 

It's not polished. I followed the Linux build instructions and worked around the problems. It's a place to start. Please try it out. Any refinements or criticisms are very

**Comment by RobertKozak** [comment]
Its already being taken care of on #1992

**Comment by andschwa** [comment]
This is implemented. Next step is to setup automated Docker hub with appropriate tags.

**Comment by colemickens** [comment]
Nice, I really like how it was solved so that you have minimal release containers but can still dev/test on master with docker. Thank you!

**Comment by andschwa** [comment]
My pleasure!
