### ISSUE TITLE
`[pscustomobject]` / hashtable literals misrepresent the location of statement-terminating errors that occur during initialization

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20013]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If an error occurs during construction of a `[pscustomobject]` / hashtable based on a (multiline) _literal_:

* It is the line of the (last) _preceding_ entry (property) that initializes a property with a _command_ (or command _pipeline_) that is mistakenly reported as the offending line, even if a later, _expression-based_ entry causes the actual, invariably _statement-terminating_ error.

* If no _commands_ are among the entry values, the error message invariably reports the _first_ line as the offending one.

These problems analogously apply to _single-line_ `[pscustomobject]` literals (with entries separated with `;`), in which case it is the _wrong part of the line_ / the _entire line_ that is underlined as the offending part.

The problems also affect Windows PowerShell.

```powershell
[pscustomObject] @{                            
  # This line causes the problem, because it   
  # contains a *command* (pipeline)            
  UnrelatedPreviousLineWithCommand = Get-Date  
  # A line with a (non-failing) *expression* has no bearing 
  # on the bug.                                
  UnrelatedPreviousLineWithExpression = 42     
  # The expression-based line that causes the statement-terminating error.
  OffendingLine          = $null.ThisFails()   
}                                              

[pscustomObject] @{                                
  # A failing *expression*, in the absence of      
  # entries initialized with *commands*, is never  
  # reported by its specific line.                 
  SomeExpression = 1 / 0                           
}                                                  
```

### Expected behavior

```console
InvalidOperation: C:\...\some.ps1:4
Line |
   m |    OffendingLine          = $null.ThisFails()   
     |                             ~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
RuntimeException: C:\...\some.ps1:12
Line |
   n |  SomeExpression = 1 / 0 
     |                   ~~~~~
     | Attempted to divide by zero.
```

### Actual behavior

```console
InvalidOperation: C:\...\some.ps1:4
Line |
   4 |    UnrelatedPreviousLineWithCommand = Get-Date
     |                                       ~~~~~~~~
     | You cannot call a method on a null-valued expression.
RuntimeException: C:\...\some.ps1:12
Line |
  12 |  [pscustomObject] @{
     |  ~~~~~~~~~~~~~~~~~~~
     | Attempted to divide by zero.
```

That is, in the first case the _unrelated_ command-based line is mistakenly reported as the offending line.
In the second case, it is the _first_ line, not the offending line.

### Environment data

```powershell
PowerShell 7.4.0-preview.4
```

**Comment by MartinGC94** [comment]
I think this is a duplicate of this: https://github.com/PowerShell/PowerShell/issues/15742

**Comment by mklement0** [comment]
Thanks, @MartinGC94  - indeed it is. 
When I looked for preexisting issues, my search terms were too narrow (and I was focused on `[pscustomobject]` only).
