### ISSUE TITLE
Out-GridView filtering doesn't work with 7.4.0-preview.4

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#20015]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using filtering with `Out-GridView` in PowerShell 7.4.0-preview.4, `Out-GridView` closes itself.

### Expected behavior

```console
@(1,2,3) | Out-Gridview
then enter "2" in the "Filter" box

Result should be the Out-GridView window with only the "2" displayed
```

### Actual behavior

```console
@(1,2,3) | Out-Gridview
then enter "2" followed by `Enter` in the "Filter" box

The Out-GridView window disappears.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
I am able to reproduce and was checking the expected behavior with 7.3.6 and seemed to have found an additional bug I have posted here #20016 😅

**Comment by daxian-dbw** [comment]
Marking "7.4-blocking" as it's potentially a regression.

**Comment by sba923** [comment]
Fix confirmed in `7.4.0-preview.5`. Good job!

**Comment by sba923** [comment]
@SteveL-MSFT @StevenBucher98 

I hate to say but I just repro'ed this on 7.5.0

Please advise on how to follow up on this.

**Comment by sba923** [comment]
So 7.5.0 was released despite the fact that a regression had been detected in a RC?

**Comment by iSazonov** [comment]
It's sad, but it's true.

**Comment by sba923** [comment]
Given that this affects both 7.5.0 and 7. 6.0-preview.2, I think I might look for a way to install 7.4.7 next to those two for the cases where I need to use Out-Gridview....

**Comment by sba923** [comment]
> Given that this affects both 7.5.0 and 7. 6.0-preview.2, I think I might look for a way to install 7.4.7 next to those two for the cases where I need to use Out-Gridview....

Done. Works fine in 7.4.7.

![Image](https://github.com/user-attachments/assets/224bee0c-78c1-4898-8ce8-f7c42c075b47)

**Comment by sba923** [comment]
> For some reason I personally didn't detect that while using 7.5 previews...

I'll blame myself for that.
