### ISSUE TITLE
Get-AuthenticodeSignature successfully verifies a signature on files without Digital Signatures

### ISSUE THREAD

**Issue by palkoc** [PowerShell/PowerShell#20027]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```Get-AuthentiCodeSignature``` successfully verifies a digital signature on a file, which has no "Digital Signature" tab in the  Properties:

```powershell
(venv) PS C:\Users\aa\Documents\Projects\PowerShell\PathHashCalc\dist> Get-AuthenticodeSignature "C:\Program Files\Common Files\microsoft shared\MSInfo\msinfo32.exe" 

    Directory: C:\Program Files\Common Files\microsoft shared\MSInfo

SignerCertificate                         Status                                StatusMessage                         Path
-----------------                         ------                                -------------                         ----
58FD671E2D4D200CE92D6E799EC70DF96E6D2664  Valid                                 Signature verified.                   msinfo32.exe
```

Properties:

![nodigital](https://github.com/PowerShell/PowerShell/assets/6809559/60019831-ccab-4c19-a1b5-cd3b92aa096f)

### Expected behavior

Expected behaviour is to say, there's no signature:

```powershell
PS C:\Users\aa\Downloads\osslsigncode-2.6-windows-x64-mingw\bin> .\osslsigncode.exe verify "C:\Program Files\Common Files\microsoft shared\MSInfo\msinfo32.exe"
PE checksum   : 0005CC67

No signature found

Failed
```

### Actual behavior

Actual behavior is as described in  ```Steps to reproduce```

### Error details

No error returned

### Environment data

```powershell
PS C:\Users\aa\Downloads\osslsigncode-2.6-windows-x64-mingw\bin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\aa\Downloads\osslsigncode-2.6-windows-x64-mingw\bin>
```

Sample file added.

[sample.zip](https://github.com/PowerShell/PowerShell/files/12177283/sample.zip)

**Comment by SydneyhSmith** [comment]
Thanks @palkoc msinfo32.exe is signed via catalog, if you need more info please contact Windows support-- thanks!

**Comment by palkoc** [comment]
Hi @SydneyhSmith. 

Do you mean https://learn.microsoft.com/en-us/windows-hardware/drivers/install/catalog-files ?
