### ISSUE TITLE
History stack not empty

### ISSUE THREAD

**Issue by Ricky-Tigg** [PowerShell/PowerShell#20025]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1.
```
> Set-PSReadlineOption -HistorySaveStyle SaveNothing
> Remove-Item (Get-PSReadlineOption).HistorySavePath
```
2. Execute at least one command;
3. Close tool's current session then start a new one;
4. As same user as in previous session, press <kbd>down-arrow</kbd>and <kbd>up-arrow</kbd> in order to call the elements of the history stack.

### Expected behavior

```console
History stack to be empty as a consequence of step _1_.
```

### Actual behavior

```console
History stack not empty.
```

### Environment data

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> History stack not empty.

In the `(Get-PSReadlineOption).HistorySavePath` or in an history of the current session? These are different entities of history. PSReadline history is rather history log or backup and a session history is the object with id, status and datetime and timespan values.

**Comment by Ricky-Tigg** [comment]
Isn't step _1_ already enough to empty all entities of history thus empty all history stacks of all times?

**Comment by 237dmitry** [comment]
> Isn't step 1 already enough to empty all entities of history thus empty all history stacks of all times?

No. It relates only on PSReadline history. I think you could add `Clear-History` to your prompt function to delete every previous command. In this case in history would be the only just entered command. I was not trying myself.

**Comment by Ricky-Tigg** [comment]
As sole goals:
- No history stack available at start of **new** session.
- Commands entered in current session temporarily **saved** in history stack.
- Temporarily **saved** history stack emptied at exit of session according to step _1_.

That context makes `Clear-History` unsuitable.

**Comment by Ricky-Tigg** [comment]
As sole goals:
- No history stack available at start of **new** session.
- Commands entered in current session temporarily **saved** in history stack.
- Temporarily **saved** history stack emptied at exit of session according to step _1_.

That makes `Clear-History` unsuitable.

**Comment by 237dmitry** [comment]
>>> History stack not empty

>> Commands entered in current session temporarily saved in history stack.

> That makes Clear-History unsuitable.

??

**Comment by Ricky-Tigg** [comment]
What did you think you would achieve by manipulating irrationally someone's quotes. That must be a pattern known to others users but not yet to me. Indeed that _??_; that what you get when you play that game. Was that the best you could show as developer?

**Comment by Ricky-Tigg** [comment]
What did you think you would achieve by manipulating irrationally someone's writings.  That's a pattern you won't observe with a genuine developer. Indeed your _??_; that what you get when you play that game. How could you assume that a reader other than you would not notice your trick? You just made yourself a reputation.

**Comment by 237dmitry** [comment]
> by manipulating irrationally someone's quotes

How I could understand you?

I asked you:
> In the `(Get-PSReadlineOption).HistorySavePath` or in an history of the current session?

Your answer:
> Isn't step 1 already enough to empty all entities of history thus empty all history stacks of all times?

Did you do mean all history stacks of all times, current history and saved one?

I understood that you do not need a history at all, but how else to understand?

**Comment by mklement0** [comment]
`Set-PSReadlineOption -HistorySaveStyle SaveNothing`:

 * applies to the _current session only_

   * The `PSReadLine` module currently does _not_ have its own persistence mechanism; any non-default settings you want to persist, i.e. settings you want to apply to all future sessions, must be added as `Set-PSReadLineOption` calls to a profile file, such as `$PROFILE`.
  
 * only governs whether interactively submitted commands are _persisted_ (saved to the history _file_).
   * Recalling commands submitted in the _current session_ ALWAYS works, irrespective of the `(Get-PSReadlineOption).HistorySavePath` setting.
   * On _Windows_ , even _unloading_ the `PSReadLine` module (`Remove-Module PSReadLine`) does _not_ prevent the availability of a session-level history (recall of commands with <kbd>Up-arrow</kbd>, for  commands submitted _after_ the `Remove-Module` call), because Windows console windows maintain their own current-session-only history.

**Comment by Ricky-Tigg** [comment]
> In the (Get-PSReadlineOption).HistorySavePath or in an history of the current session?

I can observe myself that
- it wasn't answered to in my next comment. as i understood it partially; that _(Get-PSReadlineOption).HistorySavePath_ i could not yet interpret correctly while that _history of the current session_ i could.
- being non-answered must had bothered me because in a next comment of Jul 25, 2023, 8:30 PM GMT+3,  i attempted to answer globally with explicit conditions.
>  No history stack available at start of new session.

Didn't this imply _all history stacks of all times_, which itself implied _all those saved_.

> Commands entered in current session temporarily saved in history stack.
> Temporarily saved history stack emptied at exit of session according to step 1.

Didn't this imply _history of the current session is needed_, hence _must be saved in order to be available in the current session_ and at last _must be emptied at the end of session_ so that the condition _No history stack available at start of new session._ can be met.

What we learned from the comment history of the present ticket is that all this activity happened **before** your comment of Jul 25, 2023, 9:30 PM GMT+3.

**Comment by Ricky-Tigg** [comment]
I needed a proper answer, so I had to investigate to find a source that provided it. Finally I was able to find it, although provided by a non-Microsoft source. I make a note here **for myself** for record purpose.

1. Before ending each session | `Remove-Item -Confirm -LiteralPath C:\Users\$Env:UserName\appdata\roaming\microsoft\windows\powershell\PSReadLine\ConsoleHost_history.txt`
2. End the session by exiting the console from the **UI**, not by `Exit` in command line since it would be saved thus present in history when starting a new session.

**Comment by Ricky-Tigg** [comment]
It's statistically good. At least one developer who was unable to reproduce the symptom described in this report. However unknown is still your demonstration. I can't wait to read, probably like anyone here, how you managed to not get a non-empty history stack at the start of new sessions using **those very commands** presented in this report.

As for the very case I was reasonably expecting one of yours to recommend the use of a permanent alias for the command `Remove-Item -LiteralPath C:\Users\$Env:UserName\appdata\roaming\microsoft\windows\powershell \PSReadLine\ConsoleHost_history.txt`, be it without `-Confirm` or not. But no.

I naively assumed it would be as simple as Unix/Linux made it. I had to learn that it would have been too good to be true. So we won't know neither how you would have done, by choosing to keep things simple. Yet too often i can testify how some developers easily became addictive to cultivate the _Art of doing things by complicating them even when they could be done with simplicity._.

**Comment by Ricky-Tigg** [comment]
No need to bother to pretend. Who is still unaware today of how everything is destined to end at Microsoft? The correct answer, and nothing else. This is what **I and any reader** were are entitled to expect. Even I, novice in regard to code culture practises at Microsoft, I am able to manage answering properly, then by fully meeting the requirements here set, which i do now.

I have to assume the reader is fully aware of those nameless things that are called in Microsoft's jargon _PowerShell_, _Windows Defender_; let's stop here, i have not time to lose by citing its whole production. **Fancy names**, we get it.

### Methodology

Check whether the _Controlled folder access_ property is enabled:

```powershell
> Get-MpPreference | Select-Object -ExpandProperty EnableControlledFolderAccess
2
```
When it is, as administrator, add the PowerShell 7+ application as **allowed** in regard to _Controlled folder access_.
```powershell
> Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\PowerShell\7\pwsh.exe"
```
Paths to each of the **four** profiles for the Windows PowerShell console:
```powershell
> ($PROFILE | Select-Object -ExcludeProperty Length | Format-List | Out-String).Trim()
AllUsersAllHosts       : C:\Program Files\PowerShell\7\PROFILE.ps1
AllUsersCurrentHost    : C:\Program Files\PowerShell\7\Microsoft.PowerShell_PROFILE.ps1
CurrentUserAllHosts    : C:\Users\vince\Documents\PowerShell\PROFILE.ps1
CurrentUserCurrentHost : C:\Users\vince\Documents\PowerShell\Microsoft.PowerShell_PROFILE.ps1
```
Determine the existence of a profile; for instance $PROFILE:
```powershell
> Test-Path $PROFILE
False
```
Then no profile exits yet for` $PROFILE`'s file.

Create a new profile (is persistent), for instance for `$PROFILE` which can be referred as well as `$PROFILE.CurrentUserCurrentHost:`
```powershell
> New-Item -force -type file -path $PROFILE
    Directory: C:\Users\[name]\Documents\PowerShell
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            8.15.2023    11.07              0 Microsoft.PowerShell_PROFILE.ps1
```
Create a new persistent alias, for instance for this profile:. To achieve this task, select preferably a text editor with support for code language syntax coloring to edit this profile; _notepad++_ will do.

Model of alias:
```powershell
function [function_name] {
 # to be run
}

Set-Alias [alias_name] [function_name]
```
Alias that I have applied on my system; shown for convenience:
```powershell
function CurrentUserPowerShellHistoryCompleteVacuum {
 Remove-Item -Confirm -LiteralPath C:\Users\$Env:UserName\appdata\roaming\microsoft\windows\powershell\PSReadLine\ConsoleHost_history.txt
 Write-Output ""
 Write-Output 'Now, if you chose to empty the history, end this session by closing this terminal within UI.'
}

Set-Alias vacuum CurrentUserPowerShellHistoryCompleteVacuum
```
Once the profile saved, end your session by closing your terminal within UI. The modification will take effect at start of a new terminal session. At last, ensure the alias is operational by executing it; for instance `vacuum` in my system.
```
> vacuum

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove File" on target
"C:\Users\[name]\appdata\roaming\microsoft\windows\powershell\PSReadLine\ConsoleHost_history.txt".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

Now, if you chose to empty the history, end this session by closing this terminal within UI.
```

**Comment by Ricky-Tigg** [comment]
No need to bother to pretend. Who is still unaware today of how everything is destined to end at Microsoft? The correct answer, and nothing else. This is what **I and any reader** were entitled to expect. Even I, novice in regard to code culture practises at Microsoft, I am able to manage answering properly, then by fully meeting the requirements here set, which i do now.

I have to assume the reader is fully aware of those nameless things that are called in Microsoft's jargon _PowerShell_, _Windows Defender_; let's stop here, i have not time to lose by citing its whole production. **Fancy names**, we get it.

### Methodology

Check whether the _Controlled folder access_ property is enabled:

```powershell
> Get-MpPreference | Select-Object -ExpandProperty EnableControlledFolderAccess
2
```
When it is, as administrator, add the PowerShell 7+ application as **allowed** in regard to _Controlled folder access_.
```powershell
> Add-MpPreference -ControlledFolderAccessAllowedApplications "C:\Program Files\PowerShell\7\pwsh.exe"
```
Paths to each of the **four** profiles for the Windows PowerShell console:
```powershell
> ($PROFILE | Select-Object -ExcludeProperty Length | Format-List | Out-String).Trim()
AllUsersAllHosts       : C:\Program Files\PowerShell\7\PROFILE.ps1
AllUsersCurrentHost    : C:\Program Files\PowerShell\7\Microsoft.PowerShell_PROFILE.ps1
CurrentUserAllHosts    : C:\Users\vince\Documents\PowerShell\PROFILE.ps1
CurrentUserCurrentHost : C:\Users\vince\Documents\PowerShell\Microsoft.PowerShell_PROFILE.ps1
```
Determine the existence of a profile; for instance $PROFILE:
```powershell
> Test-Path $PROFILE
False
```
Then no profile exits yet for` $PROFILE`'s file.

Create a new profile (is persistent), for instance for `$PROFILE` which can be referred as well as `$PROFILE.CurrentUserCurrentHost:`
```powershell
> New-Item -force -type file -path $PROFILE
    Directory: C:\Users\[name]\Documents\PowerShell
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            8.15.2023    11.07              0 Microsoft.PowerShell_PROFILE.ps1
```
Create a new persistent alias, for instance for this profile:. To achieve this task, select preferably a text editor with support for code language syntax coloring to edit this profile; _notepad++_ will do.

Model of alias:
```powershell
function [function_name] {
 # to be run
}

Set-Alias [alias_name] [function_name]
```
Alias that I have applied on my system; shown for convenience:
```powershell
function CurrentUserPowerShellHistoryCompleteVacuum {
 Remove-Item -Confirm -LiteralPath C:\Users\$Env:UserName\appdata\roaming\microsoft\windows\powershell\PSReadLine\ConsoleHost_history.txt
 Write-Output ""
 Write-Output 'Now, if you chose to empty the history, end this session by closing this terminal within UI.'
}

Set-Alias vacuum CurrentUserPowerShellHistoryCompleteVacuum
```
Once the profile saved, end your session by closing your terminal within UI. The modification will take effect at start of a new terminal session. At last, ensure the alias is operational by executing it; for instance `vacuum` in my system.
```
> vacuum

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove File" on target
"C:\Users\[name]\appdata\roaming\microsoft\windows\powershell\PSReadLine\ConsoleHost_history.txt".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

Now, if you chose to empty the history, end this session by closing this terminal within UI.
```

**Comment by mklement0** [comment]
@Ricky-Tigg, to spare you frustration in the future let me try to delineate what this repo is and isn't about:

* It _is_ about:

  * Driving the _development_ of PowerShell, based on _bug reports_ and  _feature requests_.

* It is _not_:
 
  * A _support_ forum.
  * A forum for off-topic rants and posting solutions to very specific, personal use cases.

**Comment by Ricky-Tigg** [comment]
Is it so? But if only it could only be that. But it is still [and you can go on for each of your _It is about:_ and _It is not:_].
