### ISSUE TITLE
`Select-String` as pipeline | corrupted output

### ISSUE THREAD

**Issue by Ricky-Tigg** [PowerShell/PowerShell#20026]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. '`tpmtool /?`'or '`TPMTOOL /?`'; output truncated:
```
> tpmtool /? 
Parameters:
 GETDEVICEINFORMATION                     Displays the basic information of the TPM. 
Examples:
 tpmtool getdeviceinformation
```
2. '`tpmtool /? | Select-String -AllMatches -Pattern 'getdevice' `'

### Expected behavior

```console
> tpmtool /? | Select-String -AllMatches -Pattern 'getdevice' 
 GETDEVICEINFORMATION                     Displays the basic information of the TPM. 
 tpmtool getdeviceinformation
```

Non-corrupted original text structure.
```


### Actual behavior

```console
> tpmtool /? | Select-String -AllMatches -Pattern 'getdevice'
    ←[7mGETDEVICE←[0mINFORMATION                     Displays the basic information of the TPM.
    tpmtool ←[7mgetdevice←[0minformation
```

Corrupted original text structure.
```


### Error details

_No response_

### Environment data

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
In my environment (win 11 22H2):

![Screenshot 2023-07-25 201745](https://github.com/PowerShell/PowerShell/assets/78153320/f5c29ffc-d61a-4d26-85bc-85a5b1654e9e)

**Comment by mklement0** [comment]
This is a known problem, and its affects:

*`Select-String` pipelines with input from _native programs_ (simple repro: `cmd /c ver | Select-String ver`)
* but only on Windows, and there only in regular (`conhost.exe`) console windows.

See:

* #19425

**Comment by 237dmitry** [comment]
>  and there only in regular (conhost.exe) console windows.

![Screenshot 2023-07-25 213558](https://github.com/PowerShell/PowerShell/assets/78153320/135b68a4-c040-45c6-8063-01373e20b129)

**Comment by mklement0** [comment]
@237dmitry, that only works with an _opt-in_ (having manually set the `VirtualTerminalLevel` value in registry key `HKEY_CURRENT_USER\Console ` to `1` in a previous session) - which _shouldn't  be necessary_; I've updated the linked issue to make that clearer.

**Comment by 237dmitry** [comment]
>  that only works with an opt-in (having manually set the VirtualTerminalLevel value in registry key HKEY_CURRENT_USER\Console  to 1

Yes exactly. Now I remembered. This registry value I actually set.

**Comment by Ricky-Tigg** [comment]
Another issue, out of scope though; the non-reliability of `Get-ComputerInfo` that reports _Windows 10 Home_ as OS while installed is _Windows 11 Home_, upgraded from _Windows 10 Home_.

**Comment by mklement0** [comment]
@Ricky-Tigg:

* If you found another issue, I encourage you to create a new bug report.

* As for the issue at hand: 
  * If you agree that your issue is a variation of  #19425, I encourage you to close this issue.
  * If not, please elaborate.
