### ISSUE TITLE
Start-Process does not work as expected with NoNewWindow argument

### ISSUE THREAD

**Issue by rbalaz** [PowerShell/PowerShell#20023]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Run Start-Process with the following arguments: -FilePath,-ArgumentList(optional),-Wait,PassThru,-NoNewWindow
2. Observe that the execution fails no matter what is being executed, always end with error: "Start-Process: This command cannot be run due to the error: The filename, directory name, or volume label syntax is incorrect."
3. Removing the NoNewWindow fixes the problem, but causes output from the command to be lost.

### Expected behavior

```console
Start-Process -FilePath "C:\Windows\System32\msinfo32.exe" -Wait -PassThru -NoNewWindow
 NPM(K)    PM(M)      WS(M)     CPU(s)      Id  SI ProcessName
 ------    -----      -----     ------      --  -- -----------
      5     0.86       3.53       0.00   43404   1 msinfo32
- window opens with MSInfo
```

### Actual behavior

```console
Start-Process -FilePath "C:\Windows\System32\msinfo32.exe" -Wait -PassThru -NoNewWindow
Start-Process: This command cannot be run due to the error: The filename, directory name, or volume label syntax is incorrect.
```

### Error details

```console
Issue started occurring after I upgraded from 7.3.5 to 7.3.6. It worked before and also works as intended on the PowerShell bundled in my Windows machine.
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by UselessGuru** [comment]
I cannot reproduce the issue.

<img width="691" alt="image" src="https://github.com/PowerShell/PowerShell/assets/30080938/5d93e161-02d3-4171-b986-771dc4e50f0d">

**Comment by rbalaz** [comment]
It seems this was some temporary misconfiguration of PowerShell, as the issue seems to have fixed itself after my system reboot due to an update.
