### ISSUE TITLE
Continous Integration should push images to Docker Hub

### ISSUE THREAD

**Issue by colemickens** [PowerShell/PowerShell#2002]
After #2001, it would be good to publish continously integrated Docker containers of PowerShell to Docker Hub under an official account `docker.io/microsoft/powershell` or `docker.io/powershell/powershell` maybe.

**Comment by joeyaiello** [comment]
I know @pcgeek86 wanted to submit a PR on this, I'm sure we'd be willing to take it if it was done right :)

**Comment by pcgeek86** [comment]
@joeyaiello Thank you for roping me in!

I sent you guys a Dockerfile via e-mail, however it has gone through some changes since then. Can we define some requirements around "done right?" I'd be happy to contribute automated builds.

**Comment by andschwa** [comment]
Pending. Will be doing this probably tomorrow. @joeyaiello need to run some tag organization questions by you.

**Comment by andschwa** [comment]
FYI, while I'm waiting for #2263 to get settled, this works swell:

```
docker run -it andschwa/powershell
```

I've set the latest tag to be the Ubuntu 16.04 minimal/stable image (i.e. package installed; not built from master).

**Comment by andschwa** [comment]
This is done as far I as I have permissions to do so; assigning over to @SteveL-MSFT for final integration to the official Docker hub.

**Comment by andschwa** [comment]
This is done 😄
