### ISSUE TITLE
`Start-Process nohup` does not work if shell is immediately killed

### ISSUE THREAD

**Issue by ThomasETN** [PowerShell/PowerShell#20036]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

For example, a one-liner commands like this works normally:
```
Start-Process nohup "`"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`" google.com"
```

However, if the shell is exited immediately afterwards, the process is NOT started:
```
Start-Process nohup "`"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`" google.com"; exit
```
(Inspecting the `nohup.out` file, nothing is appended)

### Expected behavior

```console
Processes should be started by `Start-Process nohup`, before the lines afterwards are executed.
```

### Actual behavior

```console
If the shell is terminated immediately after `Start-Process nohup`, the process is not started.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Darwin 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasETN** [comment]
Adding some `Start-Sleep` time would "circumvent" the issue, if that helps 🙃

For example:
```
Start-Process nohup "`"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`" google.com"; Start-Sleep 0.5; exit
```

**Comment by 237dmitry** [comment]
Tried with firefox and it starts, nohup.out with stderr of firefox.

```
Start-Process nohup -args 'firefox google.com'; exit
```

**Comment by jdhitsolutions** [comment]
Added for the Cmdlet WG to review.

**Comment by JamesWTruher** [comment]
@ThomasETN 
  Could you try adding `-passthru` to your example and see if the behavior changes? There's definitely a timing element to this, my conjecture is that powershell is exiting before the process chain is really started (Process.Start isn't _really_ synchronous, and this is complicated by the `exec` in `nohup`). If you return the process object, then you can check that it is really started. Since `nohup` usually just calls `execvp` on the app, once `ProcessName` is available on the returned object and is what you think it should be, it should be safe to exit.
  
I'm not sure that putting checks in `Start-Process` would be worth the investment, as it's seems pretty specific to this double execution (`nohup` invoking _arbitrary app_), and I would really dislike special casing `nohup`.

**Comment by ThomasETN** [comment]
Executing:
```
Start-Process nohup "`"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`" google.com" -PassThru; exit
```
chrome still exits immediately.

(I have also updated powershell to `7.4.5`)

**Comment by ThomasETN** [comment]
Not sure if this helps but I also found out that if the shell hosting terminal is not exited, Chrome is started properly.

e.g. if I start terminal with powershell, then start another instance of powershell with `pwsh`, and run the same command (with or without the `-PassThru` argument), Chrome starts propertly while the terminal returns to the outer powershell instance.

**Comment by ThomasETN** [comment]
I have no clue how the terminal and shell actually works, yet it appears to me that the key to making the `Start-Process nohup` command work is to make sure that the hosting terminal stays alive before the process is started; it seems to have nothing to do with whether the shell instance is exited or not.
I tested on both "iTerm" and "Terminal", and this behavior is the same for the two terminals.

**Comment by TobiasPSP** [comment]
The cmdlet WG reviewed this. It seems to be a timing issue in a specific scenario where a process spawning another process does not complete fast enough. This is expected behavior of the approach used. Adding the code to make sure these edge cases work is not worth the investment.
