### ISSUE TITLE
Regression in debugger broke setting breakpoints in VS Code PowerShell extension

### ISSUE THREAD

**Issue by andyleejordan** [PowerShell/PowerShell#20044]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Reproduction steps are in https://github.com/PowerShell/vscode-powershell/issues/4668. The latest preview, `preview.4` breaks setting breakpoints in the PowerShell extension for VS Code. I was able to reproduce this with a build from `master` and then noted it no longer reproduced after reverting the changes introduced by https://github.com/PowerShell/PowerShell/pull/14953.

### Expected behavior

```console
The breakpoints set in the extension should actually be set in PowerShell
```

### Actual behavior

```console
The breakpoints are never set (or maybe hit?)
```

### Environment data

```powershell
preview.4
```

**Comment by fflaten** [comment]
Can't reproduce on Ubuntu (PowerShell-repo devcontainer), but can on Windows.

@nohwnd @andyleejordan PR replaced a `OrdinalIgnoreCase` string comparison on script-path with string-key in dictionary.

**Works in PS 7.3.6 Windows**
```powershell
> Set-Content file.ps1 "'Hello World'"
# Adding breakpoint with different case
> Set-PSBreakpoint -Script ".\FILE.ps1" -Line 1

  ID Script                      Line Command                     Variable                   Action
  -- ------                      ---- -------                     --------                   ------
   1 FILE.ps1                       1

> .\file.ps1
Hit Line breakpoint on 'C:\Users\Frode\FILE.ps1:1'

At C:\Users\Frode\file.ps1:1 char:1
+ 'Hello World'
+ ~~~~~~~~~~~~~
[DBG]:
```

**Works in PS 7.4.0-preview.4 Windows**
```powershell
> Set-Content file.ps1 "'Hello World'"
# Adding breakpoint with different case
> Set-PSBreakpoint -Script ".\FILE.ps1" -Line 1

  ID Script                      Line Command                     Variable                   Action
  -- ------                      ---- -------                     --------                   ------
   1 FILE.ps1                       1

# Does not trigger
> .\file.ps1
Hello World

# Adding breakpoint with correct case
> Set-PSBreakpoint -Script ".\file.ps1" -Line 1

  ID Script                      Line Command                     Variable                   Action
  -- ------                      ---- -------                     --------                   ------
   2 file.ps1                       1
# Triggers
> .\file.ps1
Entering debug mode. Use h or ? for help.

Hit Line breakpoint on 'C:\Users\Frode\file.ps1:1'

At C:\Users\Frode\file.ps1:1 char:1
+ 'Hello World'
+ ~~~~~~~~~~~~~
[DBG]:
```

Don't have a Windows dev-machine to build and test, but maybe enough to make it case-insensitive again [here](https://github.com/PowerShell/PowerShell/blob/91447e62dec9fdbd5d24822eb8fefcc2b216d1b1/src/System.Management.Automation/engine/debugger/debugger.cs#L985)?
```diff
-_pendingBreakpoints = new ConcurrentDictionary<string, ConcurrentDictionary<int, LineBreakpoint>>();
+_pendingBreakpoints = new ConcurrentDictionary<string, ConcurrentDictionary<int, LineBreakpoint>>(StringComparer.OrdinalIgnoreCase);
_boundBreakpoints = new ConcurrentDictionary<string, Tuple<WeakReference, ConcurrentDictionary<int, LineBreakpoint>>>(StringComparer.OrdinalIgnoreCase);
```
