### ISSUE TITLE
System.Console.Write(Line) can't output text in remote session

### ISSUE THREAD

**Issue by sim590** [PowerShell/PowerShell#20054]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Invoke-Command -ComputerName localhost -ScriptBlock { $Host.UI.SupportsVirtualTerminal }
```

I am actually trying to use this approach:

https://beatcracker.wordpress.com/2020/09/12/write-host-with-ansi-colors/

for getting correct colors inside Azure DevOps Pipeline output log. It works for commands executing locally, but as soon as `write-host` is called from inside a remote Powershell session, then it fails to give the correct color coding. I understood that it was due to the fact that `$Host.UI.SupportsVirtualTerminal` was giving `False` in a remote powershell session.

Please, if my interpretation of the issue is not right, I would like to know why and if I could directed towards a way to solve this, I would appreciate.

### Expected behavior

```console
PS> Invoke-Command -ComputerName localhost -ScriptBlock { $Host.UI.SupportsVirtualTerminal }
True
```

### Actual behavior

```console
PS> Invoke-Command -ComputerName localhost -ScriptBlock { $Host.UI.SupportsVirtualTerminal }
False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.12
PSEdition                      Core
GitCommitId                    7.2.12
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
It looks like you accidentally submitted your issue twice - please close the accidental duplicate, #20053

**Comment by mklement0** [comment]
* When PowerShell code executes _via remoting_, there is no console / terminal involved, which is why `$Host.UI.SupportsVirtualTerminal` reports `$false` (in local invocations, the PowerShell host is `ConsoleHost` (`$host.Name`), whereas it is `ServerRemoteHost` in remote calls).

* However - irrespective of whether you're making a local or a remote call - it is the _caller's_ host that is responsible for rendering VT/ANSI escape sequences.

I don't know how Azure DevOps captures session output in a log, but if it uses [`Start-Transcript`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.host/start-transcript), that would explain the lack of coloring:

* See #11567

**Comment by mklement0** [comment]
The linked function uses `[System.Console]::Write()` /  `[System.Console]::WriteLine()` whose output PowerShell does _not_ relay from remote sessions.

In addition to removing the condition on `$Host.UI.SupportsVirtualTerminal`, try replacing `[System.Console]::$Method($item)` with:
`if ($NoNewLine) { Write-Host -NoNewLine $item } else { Write-Host $item }`

**Comment by sim590** [comment]
OK, so I just replaced with:

```
if ($NoNewLine) { Microsoft.PowerShell.Utility\Write-Host -NoNewLine $item } else { Microsoft.PowerShell.Utility\Write-Host $item }
```

And it works well!!!

![image](https://github.com/PowerShell/PowerShell/assets/4147254/a3a49a82-eb62-4284-adf9-786dc79c1cbd)

**Comment by sim590** [comment]
OK, So I retitled the issue since it wasn't really on point... I'm closing this now. Thanks again!

**Comment by mklement0** [comment]
Glad to hear it, @sim590; my pleasure.
