### ISSUE TITLE
Get-Verb Verb parameter argument completer

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20059]
### Summary of the new feature / enhancement

The `Get-Verb -Verb` parameter should have argument completion.

**Comment by kilasuit** [comment]
This would be very nice to have 
I'd like to see this not only for this parameter in this cmdlet but for others in the wider codebase too.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets feels this is a useful enhancement.
