### ISSUE TITLE
Debugger could trigger breakpoint in wrong script on case sensitive filesystems

### ISSUE THREAD

**Issue by fflaten** [PowerShell/PowerShell#20057]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run in linux:

```powershell
"'Hello from LOWERCASE file'" > file.ps1
"'Hello from UPPERCASE file'" > FILE.ps1

# Set breakpoint on lowercase file
Set-PSBreakpoint -Script file.ps1 -Line 1

# Invoke uppercase file
& ./FILE.ps1

# Enters debugger (issue)
Entering debug mode. Use h or ? for help. 

Hit Line breakpoint on '/tmp/file.ps1:1'

At /tmp/FILE.ps1:1 char:1
+ 'Hello from UPPERCASE file'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected behavior

Does not enter debugger as the breakpoint is set for the lowercased file only.

See https://github.com/PowerShell/PowerShell/pull/20046#discussion_r1279671261.
VSCode extension relies on the current behavior atm because it sets breakpoint using a lowercase drive letter on Windows.

### Actual behavior

Enters debugger because breakpoint matches script using `OrdinalIgnoreCase` string comparison.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by andyleejordan** [comment]
Cross-posting for visibility: https://github.com/PowerShell/PowerShellEditorServices/issues/2047#issuecomment-1660759942

> Per a VS Code developer in https://github.com/Microsoft/vscode/issues/68325#issuecomment-462239992, this has been brought up as breaking others before, but the decision is "something we cannot change anymore."
> 
> In summary, this isn't something PSES or vscode-powershell is doing _wrong_, it's a consequence of receiving URIs from VS Code where they enforce the drive-letter being lowercase, and this does not match up with PowerShell's own expectation that the drive-letter is upper-case. **So @fflaten I think that when https://github.com/PowerShell/PowerShell/issues/20057 is fixed to support distinguishing files in the PowerShell debugger on case-sensitive filesystems, the simplest answer is to fix it _only_ when on a case-sensitive filesystem.**
> 
> I don't like the idea of trying to handle this in PSES be re-upper-casing drive letters in each and every handler; we're going to miss something and things will suspiciously break again.

**Comment by MartinGC94** [comment]
What a baffling design decision. If you are going to normalize a path, why not make it correct? Nothing in Windows reports the driveletter in lowercase AFAIK so it makes no sense that their normalization process does this.

**Comment by fflaten** [comment]
> the simplest answer is to fix it only when on a case-sensitive filesystem.

The question is how. I just learned this case sensitivity could differ by directory and there's no API to check it atm, see https://github.com/dotnet/runtime/issues/34235. I know this is a stretch, but it means we maybe shouldn't set comparison mode based on OS like I've usually seen in other codebases.

I did some research/troubleshooting:

- The extension/PSES has invalid drive-letter, but **rest of path seems to be good.**
- `Set-PSBreakpoint` validates the script path and stores the case-sensitive path. This means breakpoints will have the proper path set in `Script`
  ```powershell
  Set-PSBreakpoint c:\Users\Frode\Desktop\closureDemo.psm1 -Line 3 | % Script
  C:\Users\Frode\Desktop\closureDemo.psm1  # Notice uppercased drive letter
  ```
- The [newer breakpoint API](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.debugger.setbreakpoints?view=powershellsdk-7.3.0) however **does not resolve the path** (which was useful, see below).

The VSCode extension is only affected when running [PS 7.0 or above](https://github.com/PowerShell/PowerShellEditorServices/blob/bfe334df7e4bdd4b92c5c0319655e40444e185ff/src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs#L109) because it switches to the new breakpoint APIs to support breakpoints in untitled documents.

In general users will not touch the newer API. They will either:
- Use `Set-PSBreakpoint` which fixes the path automatically
- Use an IDE like VSCode, hopefully powered by PSES.

So if PSES behaves correctly, then using `Ordinal` comparison would likely work great for 99%, right?

> I don't like the idea of trying to handle this in PSES be re-upper-casing drive letters in each and every handler; we're going to miss something and things will suspiciously break again.

Normally I agree, but in this scenario it might be easier for PSES to uppercase the driveletter in `ScriptFile.FilePath` once in the setter. That way PowerShell don't have to assume which mode the filesystem/directory is in or string-replace on every step.

**Comment by andyleejordan** [comment]
The trouble is in PSES is that it's _not_ just `ScriptFile.FilePath`, as I was tracing this through I also found handlers where we're using a path value straight off an LSP request, and I can't say for certain how many of those there are.

We could fix it _in_ the breakpoint APIs? Smaller surface area to apply the fix.

**Comment by fflaten** [comment]
> * `Set-PSBreakpoint` validates the script path and stores the case-sensitive path. This means breakpoints will have the proper path set in `Script`
>   ```powershell
>   Set-PSBreakpoint c:\Users\Frode\Desktop\closureDemo.psm1 -Line 3 | % Script
>   C:\Users\Frode\Desktop\closureDemo.psm1  # Notice uppercased drive letter
>   ```

Sorry, was to quick here. 😞 
`Set-PSBreakpoint` uses `SessionState.Path.GetResolvedPSPathFromPSPath()` which only fixes the drive letter. 

```powershell
Set-PSBreakpoint -Script c:\users\frode\file.ps1 -Line 1 | % script
C:\users\frode\file.ps1
# When Ordinal (PS 7.4-preview.4), this breakpoint won't trigger when calling `file.ps1` which has full path `C:\User\Frode\file.ps1`
```

**Comment by krzydoug** [comment]
Set-PSBreakpoint -Script c:\users\frode\file.ps1 -Line 1 | % script
    C:\users\frode\file.ps1
    # When Ordinal (PS 7.4-preview.4), this breakpoint won't trigger when calling `file.ps1` which has full path `C:\User\Frode\file.ps1`

Is this a typo `C:\User\` vs `C:\users`

**Comment by fflaten** [comment]
Yes. Thanks for catching that, fixed now. 🙂
