### ISSUE TITLE
Get-Verb invalid verb should error

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20058]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If you try to get an invalid verb no error is thrown.

```powershell
Get-Verb -Verb abc
```

### Expected behavior

```console
# Error is thrown
```

### Actual behavior

```console
# No error is thrown
```

### Error details

```console
N/A
```

### Environment data

```powershell
7.4-preview4
```

**Comment by kilasuit** [comment]
I think this is a bug, but also assigning to WG for them to review and decide if this is the case or not.

**Comment by JamesWTruher** [comment]
The WG has discussed this and believe that this cmdlet behaves as designed and operates as a filter. We also believe that this is more of a design time tool, which further reduces the opportunity for confusion.

**Comment by ThomasNieto** [comment]
@JamesWTruher, @SteveL-MSFT  I don't agree with this as the behavior does not match other core cmdlets. Look at these examples when trying to get a non-existent item errors. Do you have any examples of this filter behavior where filter is the behavior and not error?

```powershell
PS C:\> Get-PSDrive a
Get-PSDrive: Cannot find drive. A drive with the name 'a' does not exist.
PS C:\> Get-Service a
Get-Service: Cannot find any service with service name 'a'.
PS C:\> Get-Item a
Get-Item: Cannot find path 'C:\Users\TN021943\a' because it does not exist.
```
