### ISSUE TITLE
Get-Verb Verb and Group parameters have ValueFromPipeline

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20060]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Both `Verb` and `Group` parameters for `Get-Verb` have `ValueFromPipeline`. This causes string pipeline input to be accepted by `Group` instead of `Verb`. 

https://github.com/PowerShell/PowerShell/blob/0502da710977fcee6cbd1137f5122c3ec42607a0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs#L21

https://github.com/PowerShell/PowerShell/blob/0502da710977fcee6cbd1137f5122c3ec42607a0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs#L30

### Expected behavior

```console
# Verb is the only parameter that has pipeline input
```

### Actual behavior

```console
# Verb and Group parameters have have pipeline input
```

### Error details

```console
N/A
```

### Environment data

```powershell
7.4-preview4
```

**Comment by kilasuit** [comment]
I think this is a case of missing parametersets on this cmdlet.

This works, 
```powershell
[pscustomobject]@{Verb='D*'; Group='Lifecycle'} | get-verb
```
this doesn't
```powershell
[pscustomobject]@{Verb='D*'} | get-verb
```

nor does this though should without needing to pass
```powershell
[pscustomobject]@{Group='Lifecycle'} | get-verb
```

But assigning to WG to review too

**Comment by kilasuit** [comment]
I know my examples shows by propertyname & not type & were to show that on top of your report that I think there are [potentially some additional test cases missing for this cmdlet](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Verb.Tests.ps1) & that I think that Parameter Sets could potentially fix your issue as well as what I have identified whilst I was looking at this too.

**Comment by jdhitsolutions** [comment]
Looks buggy to me. Getting the WG to take a look.

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets discussed this and believe that the current behavior supports a couple of limited, but useful scenarios when the one of the parameter is specified

```powershell
"get","set" | get-verb -group common
```

or 

```powershell
"common","data" | get-verb -verb s*
```

Basically, the parameter binder will know which to bind to if one of the parameters is already provided.

We agree that the behavior when not explicitly specified is somewhat confusing, but we suggest that we document this behavior and not make any change.
