### ISSUE TITLE
Change 'OSX' to 'macOS' in README.md

### ISSUE THREAD

**Issue by rickyngan** [PowerShell/PowerShell#2008]
as subject

**Comment by CameronBanga** [comment]
As a quick note, this change from OS X to macOS doesn't occur until Sierra release, so should stay OS X until Sierra is supported platform.

**Comment by lzybkr** [comment]
See PR #1934

**Comment by ealexjordan** [comment]
Appears fixed in both README.md and in PR #1934 , closing.
