### ISSUE TITLE
Feature Request: Provide a keyboard shortcut for PS-ReadLine prediction

### ISSUE THREAD

**Issue by stu0408** [PowerShell/PowerShell#20105]
### Summary of the new feature / enhancement

Hi,

Since version 7.3, PowerShell automatically enables the prediction/completion PS-ReadLineOption -PredictionSource to HistoryAndPlugin. I don't like it when it shows up automatically, sometimes it's really annoying, but on the other hand I don't want it to be disabled because it's a nice feature. We need something between automatic and disabled -> show the completion when you need it.

Would it be possible to provide a simple keyboard shortcut that displays the ListView or InlineView via a keyboard shortcut when I need it.

The steps would be the following:
- I am writing a command.
- Auto-completion is disabled -> doesn't bother me.
- When I need the completion/prediction, I press an appropriate keyboard shortcut and the ListView/InlineView appears with configured -PredictionSource.

It would work similar as the Ctrl + Space IntelliSense completion. 

---

User Story: As a PowerShell user I do want to call manually the prediction/completer via a keyboard shortcut when I need it.

Kind regards,
Smiljan

**Comment by jhoneill** [comment]
PSReadline supports it but you need to turn it on. 
For me normal completion is good, List view is hateful - except very, very rarely when it is massively useful  [F2] toggles between them by default. 

Put this in your profile and F2 will cycle between Normal, List, None and back to Normal
```powershell
Set-PSReadLineKeyHandler -Key f2 -ScriptBlock {
    $PSRLO = GET-PSReadLineOption
    #if prediction is off set it to history and inlne view
    if ($PSRLO.PredictionSource -ne "History") {
            Set-PSReadLineOption -PredictionSource    History
            Set-PSReadLineOption -PredictionViewStyle InlineView
    }
    #if prediction is history and inline view select list view 
    elseif ($PSRLO.PredictionViewStyle -eq "InlineView") {
            Set-PSReadLineOption -PredictionViewStyle ListView
    }
    #if prediction is on and list view turn it off 
    else {  Set-PSReadLineOption -PredictionSource None }
} 
```

You can put which ever of those options you prefer in your profile for the starting setting.  And of course you could customize this to assign some other key to do similar things.

**Comment by stu0408** [comment]
Hi @jhoneill, 

Thanks a lot! I have modified your script for my needs and it does what I wanted. 

 ```
# Set default
Set-PSReadLineOption -PredictionViewStyle ListView 
Set-PSReadLineOption -PredictionSource None
Set-PSReadLineOption -MaximumHistoryCount 10

# Switch with F2
Set-PSReadLineKeyHandler -Key f2 -ScriptBlock {
    $PSRLO = GET-PSReadLineOption
    $obj = New-Object -com Wscript.Shell

    if ($PSRLO.PredictionSource -ne "History") {
        Set-PSReadLineOption -PredictionSource    History
        Set-PSReadLineOption -PredictionViewStyle ListView
        $Host.Ui.RawUI.WindowTitle = "Prediction: ON"

        # Hack to refresh at current cursor position
        $obj.SendKeys(" ")
        $obj.SendKeys("{BACKSPACE}")

    }
    else {
        Set-PSReadLineOption -PredictionSource None 
        $Host.Ui.RawUI.WindowTitle = "Prediction: OFF"

        # Hack to refresh at current cursor position
        $obj.SendKeys(" ")
        $obj.SendKeys("{BACKSPACE}")
    }
}
 ```

I will close the opened issue with this comment.  Thanks again for your reply!

**Comment by Himanshu-Singh-Chauhan** [comment]
Set-PSReadLineKeyHandler -Chord Alt+u -Function SwitchPredictionView
