### ISSUE TITLE
'Phantom' symbols after some commands (exit, clear) in the PowerShell running on MacOS

### ISSUE THREAD

**Issue by GeorgiiZagladin** [PowerShell/PowerShell#20104]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- MacOS Ventura v. 13.5
- Open any shell (zsh, bash, fish)
- Install the latest stable version via brew (`brew install --cask powershell`)
- Run `pwsh` script
- Try to print `exit`, or `clear `or `l` symbols.

### Expected behavior

```console
Nothing more is visible after the printed symbols.
```

### Actual behavior

```console
After the command text, there will be 'phantom' symbols like

PS /Users/georgiizagladin> clear1;33R
PS /Users/georgiizagladin> exit3;32R
PS /Users/georgiizagladin> l7;35Re7;41Ra7;47Rr7;53R

However, these symbols are not blocking the execution of the command (you may finish the command, for example, print 'clear', press 'enter' key, and the log will be cleared)

'1;33R' and '3;32R' looks like the coordinates of the pointer in the terminal window.
```

### Error details

```console
Nothing is printed out.
```

### Environment data

```powershell
PS /Users/georgiizagladin> $PSVersionTable                                        

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="1014" alt="image" src="https://github.com/PowerShell/PowerShell/assets/134053550/42d149ab-2cd1-4442-81fa-c1790903a9b0">

<img width="1127" alt="image" src="https://github.com/PowerShell/PowerShell/assets/134053550/d1a5a85a-38aa-46ae-8eac-72543d1a5dbf">

**Comment by GeorgiiZagladin** [comment]
Hello @StevenBucher98, yes, I found that file it contained all the commands history. I cleared everything from this file, and the error disappeared. Now there are no more additional symbols at the end of a command. Do you know why it works?

**Comment by StevenBucher98** [comment]
I am not sure how you got the phantom symbols to begin with, since they were in the history file, history predictor automatically tries to suggest a command based on what you have executed perviously. If you'd like to disable this behavior you can run `Set-PSReadLineOption -PredictionSource None`.

**Comment by GeorgiiZagladin** [comment]
Thank you for your explanation.
