### ISSUE TITLE
On top of `#19989`, add `-Format` parameter to `Write-Host`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#20121]
### Summary of the new feature / enhancement

Add `-Format` parameter (or something similar) to `Write-Host` on top of #19989
Coming from: [Powershell Get-ChildItem progress indication](https://stackoverflow.com/questions/76909526/powershell-get-childitem-progress-indication)

Wishful thinking:

```PowerShell
Get-ChildItem -Recurse | Write-Host -PassThru -Format "Processing: $_" | Measure-Object -Property Length -Sum
```

**Comment by iRon7** [comment]
Linked: #19989

**Comment by mklement0** [comment]
This too sounds like it could be addressed with  @dkaszews' yet-to-be-fully-fleshed-out `Tee-Object -Process { ... }` proposal:

* https://github.com/PowerShell/PowerShell/issues/19989#issuecomment-1646214609

**Comment by dkaszews** [comment]
I don't get, how would it differ from just `Write-Host "Processing: $_"`?

**Comment by iRon7** [comment]
@dkaszews, 

> I don't get, how would it differ from just `Write-Host "Processing: $_"`?

You can't put that in the middle of a pipeline as it writes by default to the **information*" stream, e.g.:

```powershell
1,2,3 | Write-Host -PassThru -Format "Processing: $_" | Set-Content .\test.txt
```

**Comment by dkaszews** [comment]
But you're talking about `Write-Host -PassThru` which is another proposal. What I'm asking is: if `Write-Host -PassThru` exists, how will `1,2,3 | Write-Host -PassThru -Format "Processing: $_" | Set-Content .\test.txt` differ from `1,2,3 | Write-Host -PassThru "Processing: $_" | Set-Content .\test.txt`.

If this `-Format` switch would be required to properly anchor `$_`, I think you'd be better of with any of the following for this specific usecase, as they achieve the same exact thing and are either already possible or IMO easier to implement:
```pwsh
... | %{ Write-Host "Processing: $_"; $_ } | ...
... | %{ Write-Host "Processing: $_" -PassThru } | ...
# Alternative proposal
... | %{ Write-Host "Processing: $_" } -PassThru | ...
```

**Comment by iRon7** [comment]
@dkaszews,

> how will `1,2,3 | Write-Host -PassThru -Format "Processing: $_" | Set-Content .\test.txt` differ from ...

Just to be clear:
* Just `1,2,3 | Write-Host "Processing: $_"` (currently) produces an error:
`Write-Host: The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.`
(meaning that you need to create an addition parameter if you want to use the value-from-pipeline)
* `Write-Host` doesn't currently output to the success stream but directly to the information stream (host)
*  For all (different) implications, the `-PassThru` parameter causes a cmdlet that doesn't output to the success stream

For your suggestions that [embed a cmdlet in a ScriptBlock](https://learn.microsoft.com/powershell/scripting/dev-cross-plat/performance/script-authoring-considerations#avoid-wrapping-cmdlet-pipelines) (`{ ... }`), that is one of the reasons for my initial purpose as this would involve a *complete* new pipeline with the overhead of *all* (`Begin`, `End`) processing blocks.
This would not be always necessarily, e.g. something like this:

```PowerShell
... | Foreach-Object {  $_ | Export-Csv -Path .\Log.csv; $_ } | ...
```
or
```PowerShell
... | Foreach-Object { Write-Host -Format "Processing: $_"; $_ } | ...
```

Could have a nicer syntax and presumably preforms better if it could be written as (follow up issue #20133):

```PowerShell
... | Export-Csv -Path .\Log.csv -Reprocess | ...
```
or
```PowerShell
... | Write-Host -Format "Processing: $_" -Reprocess | ...
```

**Comment by mklement0** [comment]
@iRon7, I understand your intent, but as an aside: `"Processing: $_"` could never work, because it would be expanded _up front_, at which point `$_` has no meaningful value, so perhaps you meant `'Processing: $_'` (single-quoting), or, more idiomatically, `{ "Processing: $_" }`.

**Comment by iRon7** [comment]
@mklement0,

> so perhaps you meant 'Processing: $_' (single-quoting),

Yes, you're right.
Anyways, I will close this "add-on" purpose as it is now covered by my new purpose #20133

**Comment by mklement0** [comment]
Sounds good, @iRon7; on a quick meta note: the words you're looking for are ["proposal"](https://www.ahdictionary.com/word/search.html?q=proposal) (as a noun) and ["propose"](https://www.ahdictionary.com/word/search.html?q=propose) (as a verb).
