### ISSUE TITLE
Module parameter argument completion returns nested module

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20127]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If you try to complete a module parameter for `Get-Command` or `Get-Module` it will return nested module, in this example PSReadLine2 is returned.

```powershell
Get-Command -Module Microsoft.PowerShell.<tab>
```

### Expected behavior

```console
PSReadLine2 is not returned
```

### Actual behavior

```console
PSReadLine2 is returned
```

### Error details

```console
N/A
```

### Environment data

```powershell
7.4-preview4
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/38873752/cc0065b3-8edd-4c3b-b369-171b53ba9ed3)

**Comment by SteveL-MSFT** [comment]
This just seems like a bug as it shouldn't show modules you can't use directly

**Comment by sdwheeler** [comment]
I reproduced the problem in PowerShell 5.1 with PSReadLine loaded. I ran `powershell -noprofile -noninteractive` so that PSReadLine would not be loaded. The problem didn't occur. Next I loaded PSReadLine 2.2.0 (to rule out newer versions). The problem returned. So it looks like this is something in the PSReadLine code.

**Comment by theJasonHelmick** [comment]
Thank you @ThomasNieto for reporting this experience. We agree that normally you don't see nested modules, and that this is a bug.

**Comment by ThomasNieto** [comment]
@daxian-dbw could you please move this issue to the PSReadLine repo?
