### ISSUE TITLE
Requires statement error should show which version of module you need

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#20142]
### Summary of the new feature / enhancement

If I have a `#requires` statement at the top of the script:

```powershell
#Requires -Modules @{ ModuleName = 'CosmosDB'; RequiredVersion = '4.6.0'}
```

And run the `script.ps1`, It does not include the required version in the error message:

```powershell
.\script.ps1: The script 'script.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: CosmosDB.
```

I would expect it to include the version of module you need:

```powershell
.\script.ps1: The script 'script.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: CosmosDB Version 4.6.0.
```

This is also the same behaviour if you specify `ModuleVersion` or `MaximumVersion`.

### Proposed technical implementation details (optional)

Perhaps include version in the error message to make it easier for script developers to figure which version(required, minimum, maximum) is required without having to look at the script.

**Comment by kilasuit** [comment]
I think that this could be easily fioxed with edits in 

https://github.com/PowerShell/PowerShell/blob/a46843de2119203dc9c8db258138450d4a847c12/src/System.Management.Automation/engine/CommandDiscovery.cs#L289-L317

and 

https://github.com/PowerShell/PowerShell/blob/a46843de2119203dc9c8db258138450d4a847c12/src/System.Management.Automation/resources/DiscoveryExceptions.resx#L203-L204

But assigning to Engine team to confirm id this is as simple a fix as I think it could be

**Comment by ArmaanMcleod** [comment]
@kilasuit Thanks. I have also included in the issue this is the same behaviour for `MaximumVersion` and `ModuleVersion`.

And easy fix would probably be just using `ToString()` from `ModuleSpecification`

```powershell
.\script.ps1: The script 'test.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: @{ ModuleName = 'CosmosDB'; RequiredVersion = '4.6.0' }.
```

Which outputs the string hash table. Not surer if Engine team would like something nicer though 😄.

**Comment by ArmaanMcleod** [comment]
As discussed with @SteveL-MSFT @iSazonov in the PR, the hashtable syntax is not user friendly if this needs to include many modules.

I think we have a couple options for more user-friendly format:

- `<module> <version>` e.g `CosmosDB 4.6.0`. Draw back I can see here is that it doesn't specify what type of version.
- `<module> <version type> <version>` e.g. `CosmosDB RequiredVersion 4.6.0`.
- `The module <module> cannot be found with <version type> <version>` e,g. `The module CosmosDB cannot be found with RequiredVersion 4.6.0`. Draw back is that this is quite verbose if for many modules.

I think the second option is the best of both worlds and not too verbose.

What does everyone think, happy to do whatever is most user friendly 😄.
