### ISSUE TITLE
Powershell in Termux Proot

### ISSUE THREAD

**Issue by phoenixbyrd** [PowerShell/PowerShell#20150]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I get this error when running pwsh in debian proot in termux

./pwsh 
GC heap initialization failed with error 0x8007000E
Failed to create CoreCLR, HRESULT: 0x8007000E

### Expected behavior

```console
.
```

### Actual behavior

```console
.
```

### Error details

```console
.
```

### Environment data

```powershell
.
```

**Comment by StevenBucher98** [comment]
Looks like this may be related to https://github.com/dotnet/runtime/issues/85757, what version of PowerShell are you trying to use? May be something fixed in the later previews and would suggest requesting some support in the dotnet repo.

**Comment by atikattar1104** [comment]
there is a workaround that worked for me for this is setting GC heap hard limit to `10000000` using: 

```
export DOTNET_GCHeapHardLimit=10000000
```
and then calling powershell makes it run without any error. 

this sets the limit to approx 7GB. 

![Image](https://github.com/user-attachments/assets/c20d5ffd-e8cc-414c-a423-b757e6268395)

originally found on this comment: https://github.com/dotnet/runtime/issues/79612#issuecomment-1352378682

**Comment by beedell-roke** [comment]
@atikattar1104, that causes:

<blockquote>

~~~sh
-bash-5.2$ export DOTNET_GCHeapHardLimit=10000000
-bash-5.2$ pwsh
PowerShell 7.5.4
malloc(): corrupted top size
Aborted 
~~~

</blockquote>

…with the environment described at [`nix-community/nix-on-droid/issues/500`](https://github.com/nix-community/nix-on-droid/issues/500#issuecomment-3906075082).

**Comment by atikattar1104** [comment]
> [@atikattar1104](https://github.com/atikattar1104), that causes:
> 
> > -bash-5.2$ export DOTNET_GCHeapHardLimit=10000000
> > -bash-5.2$ pwsh
> > PowerShell 7.5.4
> > malloc(): corrupted top size
> > Aborted
> 
> …with the environment described at [`nix-community/nix-on-droid/issues/500`](https://github.com/nix-community/nix-on-droid/issues/500#issuecomment-3906075082).

maybe it's inclusion in environment might be causing this. try this:

```
DOTNET_GCHeapHardLimit=10000000 pwsh
```

or try changing the value to low or high, maybe with trial and error approach. i am not sure about how it may work.

**Comment by beedell-roke** [comment]
@atikattar1104, that works! Thank you. That should be documented *somewhere*, unless its automatic application would be worth an FR, for devices with limited SDRAM available?
