### ISSUE TITLE
Windows: Preserve shell state across PC restarts initiated by WU

### ISSUE THREAD

**Issue by AndrewGaspar** [PowerShell/PowerShell#2015]
It would be useful for PowerShell sessions to be restored to some degree after a Windows Update. I'll often have several PowerShell windows open with different contexts for different projects and lose all that state whenever my Windows OS updates.

As a Windows Insider, my machine frequently takes OS updates. After update, only applications that register for ["Application Restart"](https://msdn.microsoft.com/en-us/library/aa373347%28v=vs.85%29.aspx) are restarted. This includes a hodge podge of Visual Studio, Office, and some in-box apps. Currently PowerShell is a notable exception.

I'm not asking for full state restoration - I understand that it would probably be impossible to preserve variables faithfully enough to attempt that. I just want enough context to allow me to quickly re-orient myself to what I was working on, say, the previous Friday. It would be useful for each shell to be re-opened to the same working directory as when it closed and with a copy of the previous session's console output displayed before the prompt, with a clear demarcation that the output is a different session.

Mock-up:
![image](https://cloud.githubusercontent.com/assets/2292643/17860985/1ea5eb98-6844-11e6-9a08-097032ad3d33.png)

**Comment by joeyaiello** [comment]
Yeah, I'd find this super useful as well. I didn't realize that "Application Restart" was a thing until Outlook started itself a few updates in a row without being registered as a Startup app.

Might be as simple as capturing the buffer and sticking it back in without reloading any assemblies or state.

**Comment by iSazonov** [comment]
Perhaps it should be PSReadline feature.

**Comment by lzybkr** [comment]
This definitely wouldn't be a `PSReadLine` specific feature, but `PSReadLine` could participate. I'm imagining PowerShell would give each module an opportunity to persist some state which then gets restored on restart.

[Yori](https://github.com/malxau/yori) is an example of a shell that implements application restart, see [restart.c](https://github.com/malxau/yori/blob/c64034de5517d37df4682b3ba028ed123116a754/sh/restart.c) for implementation details.

**Comment by iSazonov** [comment]
My comment was about "Might be as simple as capturing the buffer and sticking it back in without reloading any assemblies or state."
Save/restore state for AD or Azure module I believe is very problematic. In particular, we can save/restore a credentials to Windows but not yet on Unix-es.

**Comment by lzybkr** [comment]
I don't think many modules would opt-in, but I'm not a fan of pretending to restore minimal state in PSReadLine, I'd much rather it be a core PowerShell feature that PSReadLine extends.

And folks would definitely want expect some state restored, like environment variables, and global variables (probably with serialization, so they won't be live objects on restore, but might still be useful.)

**Comment by iSazonov** [comment]
Eh, I would be happy if AD module could restore the previous state, but I believe that most AD cmdlets/scripts will not work with objects restored using serialization. It seems the command history and the trace log are the best that we can get here.
Also as user I'd expect that PowerShell save/restore state for _all_ loaded in current session modules.

**Comment by lzybkr** [comment]
And there lies the dilemma - if you restore some state but not what the user expects, are you providing value? Is it all or nothing, or is some in between valuable?

If restoring some but not all state is reasonable, then I'd start with what I suggested instead of just the screen and the maybe the current command line.

**Comment by kilasuit** [comment]
Adding the engine WG to this issue

**Comment by SteveL-MSFT** [comment]
I think the terminal should be responsible for preserving the scroll buffer contents on restart (iTerm2 sort of does this).  However, pwsh could preserve the current working directory location.  I would hesitate on trying to provide full fidelity as people may come to expect it and bad behaviors can happen if it's not 100%.  Instead, make it clear it's NOT anything more than scroll buffer (which PowerShell won't have and can't restore) and working directory.
