### ISSUE TITLE
(🎁) Keyboard shortcut to force kill the currently executing command

### ISSUE THREAD

**Issue by KotlinIsland** [PowerShell/PowerShell#20166]
### Summary of the new feature / enhancement

'As a consumer, I want "force kill currently executing command keyboard shortcut" so that "when a process is ignoring keyboard interrupt, it's still possible to kill it".' 

It should be <kbd>ctrl + d</kbd> or <kbd>ctrl + k</kbd>, this would stand for "die" or "kill" respectively.

### Proposed technical implementation details (optional)

```command
> py -c "while True:
>>    try: input()
>>    except: pass"
```

Pressing <kbd>ctrl + c</kbd> or <kbd>ctrl + pause</kbd> here will have no effect, as the program is eating these signals.
Upon pressing the new Microsoft© PowerShell™ Experience® keyboard shortcut <kbd>ctrl + d</kbd>, the python process will be `Stop-Process -Force`'ed.

**Comment by JamesWTruher** [comment]
@KotlinIsland for what platform are you suggesting this? On MacOS, for example, `^\` does indeed stop the python process.

**Comment by KotlinIsland** [comment]
> @KotlinIsland for what platform are you suggesting this? On MacOS, for example, `^\` does indeed stop the python process.

I had no idea mac behaves like this. I guess this request is targeted at Windows / LInux
