### ISSUE TITLE
Test-Connection with -TcpPort always returns True

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/PowerShell#20174]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

* run `Test-Connection -TargetName 192.168.192.14` with an unreachable IP address
* run the same command, but add -TcpPort, e.g. `Test-Connection -TargetName 192.168.192.14 -TcpPort 1234`

### Expected behavior

```console
The second command returns False.
```

### Actual behavior

```console
The second command returns True, regardless of the TCP port number and whether or not the target is reachable.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
7.3.6 on Windows and 7.4.0-preview.5 on Linux return False

**Comment by anthonyvdotbe** [comment]
Strange, I can't reproduce anymore either. Closing for now, thanks for testing.
