### ISSUE TITLE
An attempt to modify a collection while it is being enumerated doesn't always result in an error

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20181]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Attempting modification of a collection while it is being enumerated should result in an _error_:
* `An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute.`

This error isn't consistently surfaced - note that this is a regression from Windows PowerShell:

```powershell
# OK: Reports an error for the attempt to modify the collection being enumerated.
'--- foreach'
$l = [System.Collections.Generic.List[string]] @('one', 'two')
foreach ($e in $l) { $l.Remove($e) }

# !! Fails QUIETLY in PS CORE as of v7.4.0-preview.5
'--- pipeline'
$l = [System.Collections.Generic.List[string]] @('one', 'two')
$l | ForEach-Object { $l.Remove($_) }
```

**Important**: The quiet failure only occurs when the code is executed _via a script file_; if you paste the last two statements into an _interactive_ console, the error does surface.

**[_Update_: NOT PowerShell's fault - see [below](https://github.com/PowerShell/PowerShell/issues/20181#issuecomment-1699515501)]** The following WinForms example affects Windows PowerShell too (both interactively and in a script):

```powershell
using namespace System.Windows.Forms
Add-Type -Assembly System.Windows.Forms

$f = [Form]::new()
$f.Controls.AddRange((
  [CheckBox]::new(),
  [CheckBox]::new()
))

# !! Should fail with an error message, but quietly aborts after the first .Remove() call.
$f.Controls | ForEach-Object { $f.Controls.Remove($_) }

$f.Controls.Count # !! still nonzero
```

### Expected behavior

First snippet:

* Both the `foreach` and the `ForEach-Object` statement should report the expected error.

Second snippet:

* The expected error should occur.

### Actual behavior

First snippet:

* The `ForEach-Object` statement doesn't report an error and quietly aborts the pipeline after the first `.Remove()` call

Second snippet:

* The expected error doesn't occur; quietly aborts the pipeline after the first `.Remove()` call.

### Environment data

```powershell
PowerShell 7.4.0-preview.5
```

**Comment by DarkVillager** [comment]
I can reproduce as per [my stackoverflow post](https://stackoverflow.com/questions/77000219/windows-form-foreach-remove-only-removes-half-form-control-elements/77004054#77004054)

**Comment by SeeminglyScience** [comment]
The first one where the error isn't displayed when it's in a script is a formatting bug. You can see the error if you do `$Error[0] | fl * -f` (/cc @SteveL-MSFT)

---

The second is just how that enumerator works. The implementation of `ControlCollectionEnumerator` just indexes, it has no checks against modification during enumeration. Possibly feedback worth giving to that project but I assume it's by design.

**Comment by SeeminglyScience** [comment]
Repro steps for the formatting bug:

```ps
$content = @'
$l = [System.Collections.Generic.List[string]] @('one', 'two')
$l | ForEach-Object { $l.Remove($_) }
'@

Set-Content temp:/testing.ps1 $content
& temp:/testing.ps1
$e = $Error[0]
$e
# Formatting is empty here
$e | Format-List * -Force
```

**Comment by mklement0** [comment]
Thanks, @SeeminglyScience.

I've update the OP to make it clear that the second snippet isn't PowerShell's problem.
I do think it's worth providing feedback to the [WinForms project](https://github.com/dotnet/winforms/issues), as this seems to be a common gotcha; @DarkVillager, are you willing to do this?
