### ISSUE TITLE
New-ModuleManifest doesn't need SupportsShouldProcess

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2018]
I don't understand the risk that this cmdlet poses. There doesn't seem to be any need for SupportsShouldProcess = $True. I can submit a PR for this change, but before I do, I wanted to see if there was any need for this that I didn't foresee.

**Comment by lzybkr** [comment]
Can it clobber an existing file?  If so, I think that meets the bar for needing SupportsShouldProcess.

**Comment by juneb** [comment]
Okay, fair enough. Thanks, Jason.
