### ISSUE TITLE
Win32 does not display window when executed from PowerShell

### ISSUE THREAD

**Issue by Zingam** [PowerShell/PowerShell#20199]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have a simple Win32 application and when executed from PowerShell no window is displayed.

- No such issues if executed via debugger, Command Prompt or Windows Explorer.

What's wrong?

### Expected behavior

```console
Win32 works
```

### Actual behavior

```console
Win32 does not work
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
That sounds very unusual. Can you provide minimal code to reproduce the issue?

**Comment by Zingam** [comment]
> That sounds very unusual. Can you provide minimal code to reproduce the issue?

[RToolBox - Copy.zip](https://github.com/PowerShell/PowerShell/files/12518715/RToolBox.-.Copy.zip)

Thank you. Here is a minimal example attached. It requires CMake 3.27, ninja, MSVC  (VS 2022), optionally Visual Studio Code. If used with VSCode, you should probably remove (.vscode, .vs) first.

**Comment by iSazonov** [comment]
Do you mean your application attached to current pwsh windows but you expect new windows opened?

**Comment by Zingam** [comment]
> Do you mean your application attached to current pwsh window but you expect new window opened?

I don't understand exactly what you mean by " application attached to current pwsh window".

My application is a standard (almost) C++ Win32 application. Which creates a window by:

```C++
// Register the window class.
  WNDCLASS wc = {};

  const auto utf8_to_wstring = [](const std::string& str) {
    std::wstring_convert<std::codecvt_utf8<wchar_t>> myconv;
    return myconv.from_bytes(str);
  };

  auto titleStr = utf8_to_wstring(description.title);

  wc.lpfnWndProc = &Window_Implementation::WindowProcedure;
  wc.hInstance = ::GetModuleHandle(nullptr);
  // wc.hIcon = LoadIcon(wc.hInstance, MAKEINTRESOURCE(IDI_APPICON));
  wc.lpszClassName = titleStr.c_str();

  ::RegisterClass(&wc);

  // Create the window.

  hwnd = ::CreateWindowEx(
    0,                   // Optional window styles
    titleStr.c_str(),    // Window class
    titleStr.c_str(),    // Window text
    WS_OVERLAPPEDWINDOW, // Window style

    // Size and position
    CW_USEDEFAULT,
    CW_USEDEFAULT,
    CW_USEDEFAULT,
    CW_USEDEFAULT,

    NULL,         // Parent window
    NULL,         // Menu
    wc.hInstance, // Instance handle
    NULL          // Additional application data
  );
```

I have tested the following scenarios:

1. Windows Explorer: double click - the Win32 window is displayed
2. Command Prompt (cmd.exe) - the Win32 window is displayed
3. Visual Studio Code with cpptools - default debugger - the Win32 window is displayed
4. 3. Visual Studio Code with cpptools - CodeLLDB debugger - the Win32 window is NOT displayed (I am not sure if CodeLLDB issue is related)
5. Visual Studio Code with cpptools - run app (uses Pwsh.exe) - the Win32 window is NOT displayed
6. Windows Terminal - Command Prompt- run app with ".\MyExcutable.exe" - the Win32 window is displayed
7. Windows Terminal - PowerShell - run app with ".\MyExcutable.exe" - the Win32 window is NOT displayed

BTW I am using `main()` instead of `WinMain` as this code is supposed to be cross-platform. I couldn't test Visual Studio 2022 as my setup requires CMake 3.27 and VS2022 is on 3.26.


This is what I expect to see (Windows Terminal is on the top):

![image](https://github.com/PowerShell/PowerShell/assets/3337419/0b0e86f2-95b3-4d4f-bb82-28a9b31bbe01)

When executing via PowerShell (the main Window of my Application isn't getting displayed):

![image](https://github.com/PowerShell/PowerShell/assets/3337419/26c64d84-34c7-4fa2-992d-2c587f9c64a7)

**Comment by Zingam** [comment]
I compile the application with:

```CMake
add_executable("SimpleGame")
set_property (TARGET "SimpleGame"
  PROPERTY
    $<$<AND:$<PLATFORM_ID:Windows>,$<CXX_COMPILER_ID:Clang>>:WIN32_EXECUTABLE TRUE>
)
```

**Comment by Zingam** [comment]
My system  is:

![image](https://github.com/PowerShell/PowerShell/assets/3337419/68aefd43-ec3b-4a92-81b2-44b5a0bf56b5)

**Comment by iSazonov** [comment]
I guess your application is compiled as console application but you need Windows application. It is a flag in exe file. PowerShell check the flag.

**Comment by Zingam** [comment]
@iSazonov So basically if I use this `#pragma comment(linker, "/ENTRY:mainCRTStartup` to enable my main function to be `main()` instead of `wWinMain()`, the app window will not be displayed under certain circumstances, probably because of PowerShell.

Why is that limitation of PowerShell?

I narrowed down this with the default Visual Studio 2022 Windows project by converting it to CMake as I need to use CMake for cross platform compilation, which is the reason I'd like to use `main()` instead of `wWinMain()` and avoid `#ifdef` as much as possible.
This may have been a long standing issue which I notices just now.

[WindowsProject1.zip](https://github.com/PowerShell/PowerShell/files/12534890/WindowsProject1.zip)

**Comment by iSazonov** [comment]
I believe you should use winmain to avoid problems. Thus pwsh checks win flag of exe file and will redirect output of that exe if it is a console application (no win flag). That's not what you want.

Related https://stackoverflow.com/questions/2753761/how-do-i-tell-cmake-not-to-create-a-console-window

**Comment by Zingam** [comment]
> I believe you should use winmain to avoid problems. Thus pwsh checks win flag of exe file and will redirect output of that exe if it is a console application (no win flag). That's not what you want.

@iSazonov First thank you for taking your time to explain!
In the example from my previous post above: I converted the default MSBuild sample project to CMake. It uses `/SUBSTYTEM:WINDOWS` linker flag and `wWinMain()`. This setup works as expected in PowerShell and in VS2022 debugger.

Then I ported these changes to my actual project, which I build in VSCode with the cpptools extension (due to needing CMake 3.27 as I use C++ modules). And it doesn't work (yet). It looks like it may be more to it than just `/SUBSTYTEM:WINDOWS` linker flag and `wWinMain()`.

But there is also a difference between the VS2022 debugger and the VSCode cpptools debugger as in the latter case the debugger fails to start the application with a windows just like when starting it from PowerShell, which makes the situation even more interesting.

Thank you for your time. I'll need to dig deeper and apparently I'll need to abstract the main function like some GUI toolkits do.

**Comment by Zingam** [comment]
@iSazonov 

It seems that if I call

```cmake
  STARTUPINFO si;
  GetStartupInfo(&si);
  nCmdShow = si.wShowWindow;
```

To fetch the nCmdShow, even though during debugging it appears the same `nCmdShow` as the value passed to `WinMain`, the window will not be shown in PowerShell.

**Comment by iSazonov** [comment]
@Zingam I know that the debugger can change a behavior of the application in some cases. Perhaps this is one of those cases. You might want to look for a more appropriate forum to learn more. As long as pwsh works correctly in basic scenarios we can't change anything. If you will have more information on how to improve the debugger scenario, then it would be worth posting it here.

**Comment by Zingam** [comment]
> @Zingam I know that the debugger can change a behavior of the application in some cases. Perhaps this is one of those cases. You might want to look for a more appropriate forum to learn more. As long as pwsh works correctly in basic scenarios we can't change anything. If you will have more information on how to improve the debugger scenario, then it would be worth posting it here.

For the record. It appears that when executing the program under PowerShell:

```c++
 STARTUPINFO si;
 GetStartupInfo(&si);
 nCmdShow = si.wShowWindow;
```

and

```c++
int __clrcall WinMain(
  [in] HINSTANCE hInstance,
  [in] HINSTANCE hPrevInstance,
  [in] LPSTR     lpCmdLine,
  [in] int       nShowCmd
);
```
Don't return the same value for `nCmdShow`. I worked around by storing and passing the value returned by `WinMain`.

BTW. Visual Studio Codes cpptools extension debugger behaves like `cmd.exe` and the Visual Studio 2022 debugger behaves like `pwsh`.

**Comment by LightAndLight** [comment]
I ran into a similar problem, but I've managed to fix it. This may not be a PowerShell issue.

The [startup info struct](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa#members) also has a field for startup flags (`STARTF_*`). I confirmed that when I launched my app from PowerShell, the `STARTF_USESHOWWINDOW` flag was *unset*. In that case, the right move is to use [`SW_NORMAL`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow) as the value of `nCmdShow`.

```rust
let nCmdShow = if si.dwFlags & STARTF_USESHOWWINDOW == 1 { si.wShowWindow } else { SW_NORMAL };
```
