### ISSUE TITLE
C# record with property named Address does not work with property enumeration

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#20194]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PowerShell
Add-Type -TypeDefinition "public record MyRecord(string Address, string City);"

$r = @(
  [MyRecord]::new("Address1", "City1")
  [MyRecord]::new("Address2", "City2")
)

```

### Expected behavior

```console
PS> $r.City

City1
City2

PS> $r.Address

Address1
Address2
```

### Actual behavior

```console
PS> $r.City

City1
City2

PS> $r.Address

OverloadDefinitions
-------------------
MyRecord&, q141crp3.fsi, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null Address(int  = default)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by powercode** [comment]
It's not just records!

```PowerShell
class Person {
    [string] $Name
    [string] $Address
}

@(
    [Person] @{
        Name = 'John'
        Address = '123 Main St'
    }
    [Person] @{
        Name = 'Jane'
        Address = '456 Main St'
    }
).Address
```
```text

**Comment by IISResetMe** [comment]
This is expected behavior - member enumeration is a fallback operation only attempted when the member cannot be resolved on the immediate target.

From `about_Member-Access_Enumeration`:

> When you use the member-access operator to access a member **that does not exist on a collection**, PowerShell automatically enumerates the items in the collection and attempts to access the specified member on each item.

`Address` is available on all concrete array instances at runtime as specified in ECMA-335 §I.8.9.1

**Comment by powercode** [comment]
A bit unfortunate :) 

I understand it will not change, but it will almost never be what a PowerShell user wants.

**Comment by IISResetMe** [comment]
> it will almost never be what a PowerShell user wants.

You're probably right about that, my best advise is to promote use of `$collection |ForEach-Object -MemberName member` instead of `$collection.member` :)
