### ISSUE TITLE
Build scripts don't detect installed cmake

### ISSUE THREAD

**Issue by thoemmi** [PowerShell/PowerShell#2019]
The provided build scripts are not able to find `cmake`. Both `Start-PSBuild` and `Start-PSBootstrap` say that `cmake` is missing, however choco states differently:
![image](https://cloud.githubusercontent.com/assets/73690/17871219/f2fc9074-68ba-11e6-85af-a096bc7cee3f.png)

On first run the `Start-PSBootstrap` installed `cmake` and `cmake.install`. However, the scripts still can't detect `cmake`. I tried both running powershell as normal and elevated, even rebooted to sort out `%PATH%` issues.

Running Windows 10 build 14905, VS2015 at latest patch level, Chocolatey v0.10.0.

**Comment by McAndersDK** [comment]
I had this problem :) 
$env:path got wrong path to cmake. (X64 vs X86)
I just added the counter part to the path, and it worked :)

**Comment by thoemmi** [comment]
@McAndersDK thanks for the hint. After I changed `C:\Program Files (x86)\CMake\bin` to `C:\Program Files\CMake\bin` the build could continue.
