### ISSUE TITLE
Save current location in command history

### ISSUE THREAD

**Issue by eyalk11** [PowerShell/PowerShell#20203]
### Summary of the new feature / enhancement

I meant to save current cwd for every command executed. It should also be kept in permanent storage. 
This way the commands would be coupled with locations, and additional software could be written that either  fuzzy search only the commands that were executed in the same directory, or given a command it would select a directory if the user chooses to.

I think it is quite strong and will save a lot of time. 

 

### Proposed technical implementation details (optional)

Probably requires a change in  HistoryInfo in 

https://github.com/PowerShell/PowerShell/blob/ec8c163369ae44d45fbb7668ec216f94dc6ae8c9/src/System.Management.Automation/engine/hostifaces/History.cs#L846

**Comment by kilasuit** [comment]
Whilst this could be added directly in the engine this may also could be surfaced in PSReadLine's history. So flagging for both WG's to discuss this

**Comment by sdwheeler** [comment]
This could be implemented, today, without change to any core code using the PSReadLine AddToHistoryHandler interface. You could create a function that saves the command line and `$PWD` to some local file. It would have to be separate from the existing history file. And you might want to have a history log per session using `$ExecutionContext.Host.Runspace.InstanceId.Guid` in the filename.

**Comment by eyalk11** [comment]
I didn't know it. Thanks!

**Comment by theJasonHelmick** [comment]
Thank you @eyalk11 for this feature enhancement request.  The Interactive Working Group has reviewed this and thinks this could be useful information to include in PSReadLine.  In fact, I believe the PSReadLine team has a similar request: https://github.com/PowerShell/PSReadLine/issues/1886  

This is not a request we plan to service in the engine with the HistoryInfo object.
