### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by csekerka281** [PowerShell/PowerShell#20200]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with X, I think Y should happen but Z is actually happening.

### Expected behavior

```console
PS> 2+2
4
```

### Actual behavior

```console
PS> 2+2
5
```

### Error details

```console
PS> Get Error
```

### Environment data

```powershell
PS> $PSVersionTable
```

### Visuals

NULL

**Comment by mklement0** [comment]
@csekerka281, that's totally an all-caps PROBLEM.

While I can't reproduce your specific problem, I empathize with your predicament, given that I too see a symptom that I cannot explain:

```powershell
PS> Write-Host black
Fifty Shades of Grey
```
