### ISSUE TITLE
CI Builds aren't emitting Ubuntu 16 packages

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2020]
CI Builds aren't emitting Ubuntu 16 packages. @bmanikm 

https://github.com/PowerShell/PowerShell/issues/1773#issuecomment-241538978

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by andschwa** [comment]
I don't plan to do this. The Travis CI infrastructure makes Ubuntu 14.04 available; not Ubuntu 16.04. "Release" packages for Ubuntu 16.04 are available under [releases](https://github.com/PowerShell/PowerShell/releases), and packages can be automatically created using [Docker](https://github.com/PowerShell/PowerShell/tree/master/docker). 

Until #2263 is resolved and more official containers are uploaded, if you *need* immediate access to nightly Ubuntu 16.04 packages, you can try the tag [unstable-ubuntu16.04](https://hub.docker.com/r/andschwa/powershell/tags/) from my personal fork's automated builds (these are obviously provided as-is). This container has a nightly package installed, and moreover, the package file itself is left inside the container, available to be copied out.
