### ISSUE TITLE
Clicking Launch PowerShell opens Windows Terminal

### ISSUE THREAD

**Issue by ChaseKnowlden** [PowerShell/PowerShell#20201]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Download PowerShell from https://github.com/PowerShell/PowerShell/releases/latest.
Start install like normal.
PowerShell just opens Windows Terminal.

### Expected behavior

```console
It should launch PowerShell.
```

### Actual behavior

```console
It opens Windows Terminal.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> It opens Windows Terminal

I think you set ` Windows Terminal` as default terminal application.

**Comment by mklement0** [comment]
To add to @237dmitry's comment:

In Windows 11, you can change what terminal (console) application console-subsystem applications such as PowerShell use,  via the relevant setting in the `Settings` application - this setting applies system-wide, to all console applications, and is not controlled by PowerShell itself; the default value is `Let Windows decide` (I'm unclear on _how_ it decides), which in your case apparently defaulted to Windows Terminal.

* Run `Start-Process ms-settings:developers` to open the relevant page of the Settings application.
* Under `Terminal` (the second item from the bottom in the main pane), select the desired terminal (console) app from the dropdown list; to return to the old-style console windows (provided via `conhost.exe`), select `Windows Console Host`.

**Comment by 237dmitry** [comment]
This can also be done using the registry:

```powershell
$ Get-Item HKCU:\Console\%%Startup

    Hive: HKEY_CURRENT_USER\Console

Name                           Property
----                           --------
%%Startup                      DelegationConsole  : {00000000-0000-0000-0000-000000000000}
                               DelegationTerminal : {00000000-0000-0000-0000-000000000000}
```

"Let Windows decide": `{00000000-0000-0000-0000-000000000000}`
"Windows Console Host": `{B23D10C0-E52E-411E-9D5B-C09FDF709C7D}`
"Windows Terminal Preview": `{06EC847C-C0A5-46B8-92CB-7C92F6E35CD5}`

For example "Windows Console Host":
```powershell
Set-ItemProperty -Path HKCU:\Console\%%Startup -Name DelegationConsole -Type String -Value '{B23D10C0-E52E-411E-9D5B-C09FDF709C7D}'
Set-ItemProperty -Path HKCU:\Console\%%Startup -Name DelegationTerminal -Type String -Value '{B23D10C0-E52E-411E-9D5B-C09FDF709C7D}'
```

**Comment by kilasuit** [comment]
For reference these are some additional links for reading
https://devblogs.microsoft.com/commandline/windows-terminal-as-your-default-command-line-experience/
https://learn.microsoft.com/en-us/windows/terminal/
https://learn.microsoft.com/en-us/windows/terminal/install

**Comment by ChaseKnowlden** [comment]
Gotcha!
