### ISSUE TITLE
pwsh.exe crash on Windows 7 (snapshot attached)

### ISSUE THREAD

**Issue by Dragodraki** [PowerShell/PowerShell#20217]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

- using Windows 7 Professional 64-Bit with latest updates
- downloaded PowerShell-7.3.6-win-x86.zip (latest release version) and extracted
- ran pwsh.exe direct (tried also via call from cmd.exe)
-> Powershell crashes (for details see snapshot)

<img width="473" alt="crash_win7_PowerShell-7 3 6-win-x86 zip" src="https://github.com/PowerShell/PowerShell/assets/76787321/3fa3cda2-410e-49e0-ab59-5db81b0ed22c">

### Expected behavior

```console
PowerShell x.x.x
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\Jan\Downloads\PowerShell-7.2.1-win-x86>
```

### Actual behavior

```console
it crashed completely (please take a look at attachment)
```

### Error details

```console
it crashed completely (please take a look at attachment)
```

### Environment data

```powershell
No custom environment set
```

### Visuals

<img width="473" alt="crash_win7_PowerShell-7 3 6-win-x86 zip" src="https://github.com/PowerShell/PowerShell/assets/76787321/e43de242-b7fa-4105-b035-70ae28372e6f">

**Comment by 237dmitry** [comment]
I think you should determine Windows 7 is supported or not. Maybe this help you [19816](https://github.com/PowerShell/PowerShell/issues/19816)

**Comment by Dragodraki** [comment]
Yes, thank you.
I searched issues and docs for it, because I supposed something like that. But since I did not find anything and websites continue to tell latest Powershell Core is compatible with Windows 7, I had doubts.
Microsoft should inform people a little bit better, I think.

However, the ticket can be closed.
