### ISSUE TITLE
PWSH 7.3.6 on Linux/Mac cannot find $pshome\System.Windows.Forms.dll

### ISSUE THREAD

**Issue by JPEscher** [PowerShell/PowerShell#20212]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have installed PWSH on Ubuntu 20.04 and Mac OSX (forget the exact version) for work to develop a powershell script with a portable gui (assigned task by manager) and i have been unable to find the System.Windows.Forms.dll outside of Windows, which drives the form for the gui. 
i have searched via google and duckduckgo both this site specifically and the web in general, i have seen a few issues pointing to .net needing to be ported, but they all say that starting with 7.x a ported version is embedded in PowerShell.

i am sorry if this should be in .Net instead, but is there a reason i have missed on why System.Windows.Forms.dll is not ported? 

### Expected behavior

```console
System.Windows.Forms.dll is in $PSHome in a fresh install
```

### Actual behavior

```console
System.Windows.Forms.dll is not present in $PSHome
```

### Environment data

```powershell
not available (work computers are locked down. i had to search once i got home to find a solution)
```

**Comment by mklement0** [comment]
[WinForms](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms), i.e. the APIs in the `System.Windows.Forms` namespace, are a Windows-only technology, and therefore by definition not available on non-Windows platforms.

It is legacy technology with deep roots in Windows and therefore won't be ported to other platforms (similarly, WPF will remain Windows-only).

You'll need to use cross-platform UI frameworks, such as [Avalonia](https://github.com/AvaloniaUI/Avalonia) (there's also [MAUI](https://github.com/dotnet/maui), but it lacks Linux support).

**Comment by JPEscher** [comment]
Thank you. that explains what i was unable to find.
