### ISSUE TITLE
Out-GridView filtering via criteria in 7.4.0-preview.5 yields incorrect results

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#20223]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using the "Add criteria" and filtering that way in 7.4.0-preview.5 yields incorrect results:

```powershell
@(@{"a" = '=='},@{"b"='<='},@{"c"='>='}) |ogv
```

![image](https://github.com/PowerShell/PowerShell/assets/12860484/709b0ae4-32a2-4eb2-9ff4-e793386d5711)

Here's the correct outcome with 7.3.6:

![image](https://github.com/PowerShell/PowerShell/assets/12860484/827cba75-4258-4dc0-a85d-fc249a3313db)

### Expected behavior

```console
Objects matching the specified filter should be displayed.
```

### Actual behavior

```console
Filtering removes all objects even those matching the criteria.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.5
PSEdition                      Core
GitCommitId                    7.4.0-preview.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
The fundamental problem is that when we removed use of `BinaryFormatter` this completely broke `out-gridview` which depended on it as a way to copy filter rules.  The manual `clone()` workaround wasn't sufficient.  Tried using XmlSerializer and reflection, but neither works the same as `BinaryFormatter` to get an exact copy.
