### ISSUE TITLE
Failing to correctly sort objects by multiple properties

### ISSUE THREAD

**Issue by Ricky-Tigg** [PowerShell/PowerShell#20227]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Sorting objects by multiple properties.  Are assumed:
- Default order : **ascending**
- The **order of properties** of `Sort-Object` 's `-Property` attribute matters.

Execute either
```powershell
> Get-Command -Verb 'Get' | Sort-Object -Property Source,CommandType | Select -First 11 | Format-Table -AutoSize -Property CommandType,Name,Source
```
or
```powershell
> Get-Command -Verb 'Get' | Sort-Object -Property Source, @{Expression = "CommandType"; Descending = $false} | Select -First 11 | Format-Table -AutoSize -Property CommandType,Name,Source
```

### Expected behavior

```console
> Get-Command -Verb 'Get' | Sort-Object -Property Source,CommandType | Select -First 11 | Format-Table -AutoSize -Property CommandType,Name,Source
CommandType Name                             Source
----------- ----                             ------
   Function Get-AppBackgroundTask            AppBackgroundTask
      Alias Get-AppPackage                   Appx
      Alias Get-AppPackageAutoUpdateSettings Appx
      Alias Get-AppPackageDefaultVolume      Appx
      Alias Get-AppPackageLastError          Appx
      Alias Get-AppPackageLog                Appx
      Alias Get-AppPackageManifest           Appx
      Alias Get-AppPackageVolume             Appx
     Cmdlet Get-AppxVolume                   Appx
   Function Get-AppxLog                      Appx
   Function Get-AppxLastError                Appx
```

### Actual behavior

```console
> Get-Command -Verb 'Get' | Sort-Object -Property Source,CommandType | Select -First 11 | Format-Table -AutoSize -Property CommandType,Name,Source
CommandType Name                             Source
----------- ----                             ------
   Function Get-AppBackgroundTask            AppBackgroundTask
      Alias Get-AppPackage                   Appx
      Alias Get-AppPackageAutoUpdateSettings Appx
      Alias Get-AppPackageDefaultVolume      Appx
      Alias Get-AppPackageLastError          Appx
      Alias Get-AppPackageLog                Appx
      Alias Get-AppPackageManifest           Appx
      Alias Get-AppPackageVolume             Appx
   Function Get-AppxLog                      Appx
   Function Get-AppxLastError                Appx
     Cmdlet Get-AppxVolume                   Appx

_Observations:_
- objects sorted correctly by property Source.
- objects not sorted correctly by property CommandType.
```

### Environment data

```powershell
PSVersion                      7.4.0-preview.5
PSEdition                      Core
GitCommitId                    7.4.0-preview.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
It sounds like you're expecting `Function` to sort _after_ `Cmdlet` in the output, but note that the `.CommandType` property is of type `[enum]` and therefore sorts _numerically_.

Specifically, it is of type [`System.Management.Automation.CommandTypes`](https://learn.microsoft.com/en-US/dotnet/api/System.Management.Automation.CommandTypes), and `Function` has value `2`, whereas `Cmdlet` is `8`, so `Function` sorts first.

If you want _alphabetical_ sorting, replace `-Property Source, CommandType` with `-Property Source, { [string] $_.CommandType }`

**Comment by Ricky-Tigg** [comment]
Not yet. 
```powershell
> Get-Command -Verb 'Get' | Sort-Object -Property Source, { [string] $_.CommandType } | Select -First 9 | Format-Table -AutoSize -Property CommandType,Name,Source
CommandType Name                             Source
----------- ----                             ------
   Function Get-AppBackgroundTask            AppBackgroundTask
      Alias Get-AppPackage                   Appx
      Alias Get-AppPackageAutoUpdateSettings Appx
      Alias Get-AppPackageDefaultVolume      Appx
      Alias Get-AppPackageLastError          Appx
      Alias Get-AppPackageLog                Appx
      Alias Get-AppPackageManifest           Appx
      Alias Get-AppPackageVolume             Appx
     Cmdlet Get-AppSharedPackageContainer    Appx
```
Let it be unfixed. That's the rule here anyway.

**Comment by mklement0** [comment]
That output looks correct to me: `Alias` sorts before `Cmdlet` (the `Function` line has a different `Source` value).

**Comment by Ricky-Tigg** [comment]
Was ordered nothing else than the **alphabetical order**, therefore "_a, b, c, (...)_", and Microsoft serves us with some “_a, c, b, (...)_”. As we learn, in Microsoft's jargon, a "_sort objects by multiple properties_", must have meant that fantasy output and so of course must the interpretation, "_looks correct to me_" have meant "_looks correct to me since it is a fantasy output_". We can never point it out enough –_Microsoft_.

**Comment by SteveL-MSFT** [comment]
@Ricky-Tigg, the @PowerShell/powershell-committee reviewed this issue discussion:

As @mklement0 pointed out, the behavior is working as intended even if unexpected by some.  In our docs, [example 5](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-7.3#example-5-use-a-hash-table-to-sort-properties-in-ascending-and-descending-order) does show that enums are sorted by their value and not textual representation. 

In your second example, it does sort by `Source` first as you specified, then by the `CommandType` text.

Specifically regarding your [last comment](https://github.com/PowerShell/PowerShell/issues/20227#issuecomment-1716130218).  We agreed that this violates our [Code of Conduct](https://github.com/PowerShell/PowerShell/blob/master/CODE_OF_CONDUCT.md) as derogatory and disrupting the technical discussion.
