### ISSUE TITLE
there are still test gaps in our cmdlet coverage

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#2022]
we still have a number of cmdlets without any tests, those test gaps should be closed

**Comment by thezim** [comment]
Is there a coverage report?

**Comment by kilasuit** [comment]
@JamesWTruher It would be good to gather a task list of Cmdlets missing tests in this issue and then in this thread people (like me for example) could put forward a claim to write those tests so that there is a confirmed plan ahead.

Do you think that sounds like a good idea?

**Comment by joeyaiello** [comment]
Here's a pointer to a doc that outlines all the cmdlets that have *some* kind of coverage (even if it's extremely minimal): https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/PowerShellCoreTestStatus.md

@JamesWTruher: do you think it's worth it to enumerate some high-pri gaps in that doc?

**Comment by joeyaiello** [comment]
@JamesWTruher: this might be a generic enough issue that we can close it. If you agree, go for it.

**Comment by SteveL-MSFT** [comment]
Closing this as it's not actionable.  Once we start having reliable code coverage data, we should open separate issues for additional test coverage.
