### ISSUE TITLE
Compress-Archive - Request "DeleteAfterZipped" Argument

### ISSUE THREAD

**Issue by leewilmott** [PowerShell/PowerShell#20229]
### Summary of the new feature / enhancement

I like the Compress-Archive PowerShell cmdlet, but I would really like a "DeleteAfterZipped" parameter that would delete the original file once it has been successfully added to a zip file.

Please consider this for a future release.

**Comment by iSazonov** [comment]
The cmdlet is in https://github.com/PowerShell/Microsoft.PowerShell.Archive Please open the request there.
