### ISSUE TITLE
Extend the semantics of `PSCustomTableHeaderLabelDecoration` to also highlight calculated table columns with names that happen to match property names

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20232]
### Summary of the new feature / enhancement

The _experimental_ [PSCustomTableHeaderLabelDecoration](https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features#pscustomtableheaderlabeldecoration) feature  applies special formatting - italics by default, controllable via `$PSStyle.Formatting.CustomTableHeaderLabel` - to any column _name_ that doesn't match the name of a property of the type being formatted, which is helpful in helping users understand whether an actual _property_ by that name exists.

However, this logic doesn't currently extend to calculated columns whose name _does_ match a property of the type - yet, due to the calculation - doesn't report that property's _true value_.

For instance, the `Name` display column in `Get-Alias` output _builds on_ the `Name` _property_, but augments it to show the alias _target_.

E.g., `Get-Alias gci` outputs the following:

```none
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           gci -> Get-ChildItem
```

The true `.Name` property value is just `'gci'`, but the formatting data augments it by appending `' -> Get-ChildItem'`

It would be helpful if the `Name` column too were printed _in italics_ too, based on the following _generalization_ of the feature:

* Highlight column headers (labels, names)
  *  that do not correspond to property names (e.g., `NPM(K)` in `Get-Process` output) (the current implementation)
  * _and_ those whose column _values_ are _calculated_ - even if the header matches the name of a property.

Strictly speaking, the latter criterion includes the former, as any calculated value by definition doesn't correspond to a property member, so the simpler generalization is: 

 * Highlight the headers of all columns that are calculated.

**Comment by SteveL-MSFT** [comment]
The original intent of the feature was users complaining that the table format gives heading labels that imply they are properties of the object, so when they try to use dot-notation to access that member, they get `$null` as it doesn't actually exist.

Created doc bug to address this https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11354

**Comment by mklement0** [comment]
Thanks for opening the docs issue, @SteveL-MSFT.

However, note that users may equally be confused by column values that don't match the property values of  the property implied by the column header.

The gist of my proposal was: 

* Visually indicate _whenever a column value doesn't correspond to the value of a type-native member_, which may be for two distinct reasons: (a) the column _header_ is "made up", i.e. doesn't correspond to a type-native member or (b) the column _value_ is "made up", i.e. doesn't correspond to the corresponding type-native member's _value_.

You could argue that _distinct_ visual styles may be called for to distinguish (a) and (b) - though that may be considered overkill.

Using a _single_ visual style for _both_ (a) and (b) still strikes me as preferable to only applying it to (a), which is the status quo.
