### ISSUE TITLE
Provide official AppImage builds for Linux

### ISSUE THREAD

**Issue by probonopd** [PowerShell/PowerShell#2024]
Please provide PowerShell in the AppImage format for Linux.

[AppImage](http://appimage.org/) is a packaging format for Linux that lets users download one single file, set the executable bit and run the application (here: PowerShell). Unlike other solutions, no special runtime infrastructure must be installed on the target system(s).

![PowerShell](https://lh3.googleusercontent.com/-L8aJhKxmYww/V7YKJ1sS5QI/AAAAAAAAASc/T6jPV_-h-WQTnbIqx2FZ6egnTHP2XaEbACL0B/w506-h358/snap.png)

An unofficial PowerShell AppImage has been available on https://bintray.com/probono/AppImages/PowerShell#files. It has been tested on
- CentOS-7.0-1406-x86_64-GnomeLive.iso
- CentOS-7-x86_64-LiveGNOME-1511.iso
- Chromixium-1.5-amd64.iso
- Fedora-Live-Workstation-x86_64-22-3.iso
- Fedora-Live-Workstation-x86_64-23-10.iso
- SL-72-x86_64-2016-02-03-LiveDVDgnome.iso
- debian-live-8.0.0-amd64-xfce-desktop+nonfree.iso
- debian-live-8.4.0-amd64-gnome-desktop.iso
- elementary_OS_0.3_freya_amd64.iso
- kali-linux-2.0-amd64.iso
- kali-linux-2016.1-amd64.iso
- kubuntu-14.04.4-desktop-amd64.iso
- kubuntu-15.04-desktop-amd64.iso
- kubuntu-16.04-desktop-amd64.iso
- linuxmint-17.3-cinnamon-64bit.iso
- neon-devedition-gitunstable-20160814-0806-amd64.iso
- netrunner-17-64bit.iso
- ubuntu-14.04.1-desktop-amd64.iso
- ubuntu-16.04-desktop-amd64.iso
- ubuntu-gnome-16.04-desktop-amd64.iso
- ubuntu-mate-16.04-desktop-amd64.iso
- xubuntu-16.04-desktop-amd64.iso

To try it, run

```
PS="PowerShell-6.0.0.alpha.9-x86_64.AppImage"
wget -c "https://bintray.com/probono/AppImages/download_file?file_path=$PS" -O "$PS"
chmod a+x "$PS"
./"$PS"
```

@TravisEz13 mentioned that the AppImage works for him and @andschwa mentioned that he likes the idea of having one format for all Linux distributions.

The script that generated the AppImage is [here](https://github.com/probonopd/AppImages/blob/master/recipes/powershell/Recipe). Feel free to use it, e.g. as part of the automated Travis CI build process. I am happy to help.

**Comment by andschwa** [comment]
I like it a lot, want to open a Pull Request? You should be able to setup Travis CI on your own fork for testing.

**Comment by probonopd** [comment]
@andschwa seem to be running into issues with the Travis CI build unrelated to AppImage; https://travis-ci.org/probonopd/PowerShell/builds/154306325#L719-L750

**Comment by TravisEz13** [comment]
@probonopd The root error is here:  https://travis-ci.org/probonopd/PowerShell/builds/154306325#L722
git cannot get the last tag.  Looking for a workaround...

**Comment by TravisEz13** [comment]
I believe this will fix/workaround the issue.  https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

Your clone depth was 50... I would suggest increasing to 100.

**Comment by TravisEz13** [comment]
I filled issue #2029  for the clone depth issue.

**Comment by probonopd** [comment]
Ping

**Comment by qury** [comment]
PowerShell-6.0.0.alpha.9-x86_64.AppImage works fine on Slackware64-14.2 as well.

**Comment by probonopd** [comment]
Thanks for providing an AppImage.

**Comment by zaxebo1** [comment]
the AppImage download for " PowerShell v6.0.0-alpha.17 Release" provided at url https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.17 currently has the name "PowerShell-x86_64.AppImage"

I think  currently the filename **"PowerShell-x86_64.AppImage"** file should be **renamed** as 
**"powershell-x86_64-6.0.0-alpha.17.AppImage"** . Just like filename of other download formats, Appimage filename should also include version

**Comment by zaxebo1** [comment]
POINT #2: Currently when i run the downloaded file "PowerShell-x86_64.AppImage" from url https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.17, **then it first gives the some warnings and then successfully launches Powershell**

````
myuser1@abc-machine1:~$ chmod a+x *.AppImage
myuser1@my-machine1:~$ ./PowerShell-x86_64.AppImage
/bin/bash: /tmp/.mount_kvGjoY/usr/lib/libtinfo.so.5: no version information available (required by /bin/bash)
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_kvGjoY/usr/bin/powershell.wrapper from within an AppImage.
PS /home/myuser1> 
````

Are these warnings OK? **Is there anything which still needs to be done to remove these warnings?**

**Comment by TravisEz13** [comment]
@zaxebo1 Great points, but it would be better to capture them as a new issue or set of issues.  I'd rather not reopen this issue.  The new issue will give us something track the work that needs to be done to fix these issues.  Thanks!

**Comment by zaxebo1** [comment]
@TravisEz13 
okk. Filed new issues, as per your suggestion

**Comment by SRGOM** [comment]
Aren't appimages being distributed anymore? They were very convenient. I had to download the 'official linux binary' and `tar xvf` created a bit of a mess.

**Comment by TravisEz13** [comment]
@SRGOM 	 We have switch to a [Snap package](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#snap-package).  This got us better support for more platforms with lower maintenance costs.

cc @joeyaiello
