### ISSUE TITLE
Support for older (10.8.5) version of Mac OS

### ISSUE THREAD

**Issue by ishu3101** [PowerShell/PowerShell#2026]
Do you have plans to support Powershell on Mac running version prior to OS 10.11?

**Comment by thezim** [comment]
Currently running on less than 10.11.

```PowerShell
PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS /Users/greg> $PSVersionTable                                                                                                     

Name                           Value                                                                                               
----                           -----                                                                                               
PSVersion                      6.0.0-alpha                                                                                         
PSEdition                      Core                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                             
BuildVersion                   3.0.0.0                                                                                             
GitCommitId                    v6.0.0-alpha.9                                                                                      
CLRVersion                                                                                                                         
WSManStackVersion              3.0                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                 
SerializationVersion           1.1.0.1                                                                                             


PS /Users/greg> sw_vers                                                                                                             
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1909
PS /Users/greg>
```

**Comment by ishu3101** [comment]
So how did you install Powershell on Mac OSX 10.10?

**Comment by ishu3101** [comment]
When I run Powershell on Mac OSX 10.8.5, I get a message saying **Abort trap: 6** and then the powershell process exits.

**Comment by vors** [comment]
Thank you for point it out!
PowerShell uses CoreCLR and cannot work on the platforms that are not supported by it.
CoreCLR is supported [known to work](https://github.com/dotnet/coreclr#build-status) on 10.11 and *known to work* on 10.10. 
They also [say](https://github.com/dotnet/coreclr/blob/master/Documentation/building/osx-instructions.md#environment) that it **could** work on the previous versions but no guarantee.

I'm going to change the title to be more specific.

**Comment by vors** [comment]
Just found where we have an explicit statement about OS X versions https://github.com/PowerShell/PowerShell/blob/c695d41c47c8baa48db1a590fe7378641a9e0ab9/docs/building/macos.md#build-powershell-on-macos 

> NET Core (and by transitivity, us) only supports macOS 10.11, per CoreFX issue #[7731](https://github.com/dotnet/corefx/issues/7731)

I'm going to close this issue. Please, feel free to re-open if I didn't answer your question.
