### ISSUE TITLE
powershell changed the assembly load behavior

### ISSUE THREAD

**Issue by hyke123** [PowerShell/PowerShell#20263]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create one .net6 project with using powshell.sdk 7.2.0
2. add AppDomain.CurrentDomain.AssemblyResolve event to resolve dependce from lib folder
3. After calling Runspace.Open() function,Assembly.LoadFrom always look for dependce(System.Runtime.Caching) from GAC first instead of lib folder.
4. If we remove powershell code,all works fine.
5. Demo code:https://github.com/hyke123/ProjectA/tree/master/ProjectA

### Expected behavior

```console
.net6 project should not find dependce from GAC first.
```

### Actual behavior

```console
.net6 project always look for dependce from GAC first when using powershell.
```

### Error details

![image](https://github.com/PowerShell/PowerShell/assets/20555703/ceccb772-20a6-40e6-a40e-44d53e8db170)

### Environment data

```powershell
PSVersion: 7.2.0
PSEdition: Core
GitCommitId: 7.2.0
OS: Microsoft Windows 10.0.19045
Platform: Win32NT
PSCompatibleVersions: System.Version[]
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
```

**Comment by fMichaleczek** [comment]
@hyke123 AppDomain.CurrentDomain.AssemblyResolve is an old API, please migrate your code to AssemblyLoadContext.
https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext

There is also a specific PowerShell Guideline
https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2#assembly-load-contexts

**Comment by hyke123** [comment]
Hi team.Thanks for your reply.To use AssemblyLoadContext can resolve my  issue.

**Comment by hyke123** [comment]
Hi @fMichaleczek 
Could you please specify which DLLs must be referenced when using PowerShell.SDK on .NET 6.0 for Windows? Our project relies on third-party DLL references rather than package references.
