### ISSUE TITLE
Can't access GitHub downloads and some other links via irm, iwr.

### ISSUE THREAD

**Issue by vgnod** [PowerShell/PowerShell#20279]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Any package managers like scoop, chocolatey can't download anything from GitHub.
Any iwr/irm command to GitHub results in infinite waiting. No errors from PowerShell is present. I had to restart Powershell, otherwise nothing happens for hours.
Iwr/irm commands to other websites and download links works normal. GitHub is accessible and nothing appears to be blocked. That same download links is accessible with any other browsers and methods except Powershell. 

### Expected behavior

```console
PS C:\Users\[username]> iwr https://github.com/kopia/kopia/releases/download/v0.13.0/kopia-0.13.0-windows-x64.zip -OutFile d:test.zip
[some download behavior here]
```

### Actual behavior

```console
PS C:\Users\fuwa> iwr https://github.com/kopia/kopia/releases/download/v0.13.0/kopia-0.13.0-windows-x64.zip -OutFile d:test.zip
_ (blinks)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/112317292/f2b58ebb-8705-4292-940a-f1725aadaccc)

**Comment by mklement0** [comment]
> Any package managers like scoop, chocolatey can't download anything from GitHub.

That suggests that the problem is unrelated to PowerShell - or do you _not_ see the same problem when you use _external programs_ such as `curl.exe` or `wget.exe`?

(`iwr https://github.com/kopia/kopia/releases/download/v0.13.0/kopia-0.13.0-windows-x64.zip -OutFile test.zip` works as intended for me.)

**Comment by vgnod** [comment]
I fixed it.

**Comment by krzydoug** [comment]
D:Test isn't a valid path

**Comment by mklement0** [comment]
@krzydoug, while using such a path is probably not a good idea, it _is_ valid: Assuming that drive `D:` exists, it'll target whatever PowerShell's current directory on that drive is.
