### ISSUE TITLE
Import-Module TabCompletion should let me type just the last part of the name

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#20281]
### Summary of the new feature / enhancement

As a user of ~Install-Module~, ~Install-PSResource~, Microsoft.PowerShell.PSResourceGet, I want to be able to `Import-Module PSR{Tab}` instead of needing to type _all of_ "Microsoft.PowerShell.PSR{Tab}" or **remember** that I can type `Import-Module *.PSR{Tab}`

In general, in the face of growing numbers of modules with company prefixes like "Microsoft." and "Microsoft.PowerShell." (instead of "MS." and "PS.") I would like to be able to type the most significant part of the module name (without explicitly typing the `*`) and tab-complete the rest.

### Proposed technical implementation details (optional)

My best case implementation would be for the TabCompletion for module names when I've typed "WordToComplete" to check for completions for modules with names that _start_ with that (i.e. `-like "WordToComplete*"`) but _also_ try looking for that as the first part of a dotted name (i.e. `-like "*.WordToComplete*"`)

**Comment by ThomasNieto** [comment]
The module `TabExapansionPlusPlus` has a [completer](https://github.com/lzybkr/TabExpansionPlusPlus/blob/deea6b96fcfb290f98da44104336f27d0be68fed/Microsoft.PowerShell.Core.ArgumentCompleters.ps1#L243-L293) for `Import-Module` module names but this feature should shipped by default.

**Comment by MartinGC94** [comment]
Are you sure you only want it to fallback to the last part of the module name if it finds no other results? So if you for example type in `PSR<Tab>` it should only return `PSReadline`, and not `PSResourceGet` ?

**Comment by kilasuit** [comment]
As an aside ask to this issue, Do we also want to be super lazy and allow for cycling through partial matches for searches like

> Import-Module -Name ower
> Ipmo ower

etc so that it is implicitly doing a full wildcard match like this does today 

>  > Import-Module -Name *ower*

so that when we tab through (or use Ctrl+Space with PSReadline) we'd get any other modules with PowerShell, PowerCLI, PowerBI, PNP.PowerShell etc listed too

I ask as right now this doesn't happen, would also be a `nice to have` & doesn't from the build from the linked PR that @MartinGC94 has worked on, but @Jaykul your ask `I want to be able to Import-Module PSR{Tab}` does from that PR build as I've tested it.

**Comment by MartinGC94** [comment]
> As an aside ask to this issue, Do we also want to be super lazy and allow for cycling through partial matches for searches

I think it would be annoying if typing in `Import-Module PS<Tab>` would show me `Laps`. When tab completing you want as few results as possible so you don't have to tab through results that feel irrelevant.

**Comment by Jaykul** [comment]
> Are you sure you only want it to fallback to the last part of the module name if it finds no other results? So if you for example type in `PSR<Tab>` it should only return `PSReadline`, and not `PSResourceGet` ?

PSR<Tab> to Microsoft.PowerShell.PSResourceGet was explicitly the ask. 

I mean, it should definitely _also_ return PSReadline in that case

But PSResourceGet was the reason I thought of this, because with Microsoft moving to put all their modules behind "Microsoft.PowerShell." I find myself typing too much 😉

**Comment by theJasonHelmick** [comment]
The Interactive WG reviewed this issue and agree it's a helpful feature we would like to see implemented for local module components such as Import-module, get-module and get-command -module.  We also suggest this be behind an experimental flag.

**Comment by ThomasNieto** [comment]
@theJasonHelmick please keep this issue open as it has already been approved by the working group and should be tagged with up for grabs.

**Comment by MartinGC94** [comment]
Another solution to avoid having the bot close it in 6 months is to just review and merge the existing PR 😁
