### ISSUE TITLE
Some native commands are unable to write all of their output to Write-Host

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/PowerShell#20280]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
ssh-keygen | Write-Host
```

Note that just writing `ssh-keygen` as a workaround isn't an option, as I want to write a function as below, where none of `ssh-keygen`'s output ends up in the success stream.

```powershell
function Test-Foo {
    ssh-keygen | Write-Host
    Write-Output 'foo'
}
```

### Expected behavior

```console
All of `ssh-keygen`'s output is displayed
```

### Actual behavior

```console
Not all of `ssh-keygen`'s output is displayed and it's impossible to complete the command without seeing the prompts
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The problem isn't specific to `Write-Host`, it is intrinsic to how PowerShell parses output from external ("native") programs:

* Their stdout output is parsed _line by line_, meaning that only a _complete_ line (as indicated by a _newline_) is passed on.

* If an external program issues an _interactive prompt_, the _prompt message_ (assuming it isn't followed by a newline) _won't be seen until after the prompt has been answered_ - which, unfortunately, means that you won't get to see the prompt message at the time the prompt must be answered.

Here's a minimal repro on Windows:

```powershell
cmd /c 'set /p foo=Enter a value: ' | Write-Host
```

This prompts for interactive input _first_, _without_ printing `Enter a value: `, which only prints _after_ input has been provided.

**Comment by anthonyvdotbe** [comment]
Thanks for taking the time to explain the root issue, much appreciated.

For the record, I just found out that I can achieve the desired behavior with:
```powershell
function Test-Foo {
    Start-Process -FilePath 'ssh-keygen' -Wait -NoNewWindow
    Write-Output 'foo'
}
```

**Comment by mklement0** [comment]
My pleasure, @anthonyvdotbe - thanks for sharing the workaround.
