### ISSUE TITLE
PowerShell how to cancel call to InvokeAsync?

### ISSUE THREAD

**Issue by moerwald** [PowerShell/PowerShell#20297]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm using PowerShells `InvokeAsync` method. Is there a way to cancel a long running operation, AFTER `InvokeAsync` was called. Why does the API doesn't support a CancelationToken?

Since there doesn't seem to be any question topic I'm posting my question here.

### Expected behavior

```console
---
```

### Actual behavior

```console
---
```

### Error details

```console
---
```

### Environment data

```powershell
---
```

**Comment by SteveL-MSFT** [comment]
Use [StopAsync](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.stopasync?view=powershellsdk-7.3.0#system-management-automation-powershell-stopasync)

**Comment by SeeminglyScience** [comment]
As Steve said, `StopAsync`, `BeginStop` or `Stop` is the way. If you want to support a cancellation token you can use `CancellationToken.Register` e.g.

```csharp
static async Task InvokeAsync(PowerShell pwsh, CancellationToken cancellationToken)
{
    using var registration = cancellationToken.Register(
        state => ((PowerShell)state).Stop(),
        pwsh);

    await pwsh.InvokeAsync();
}
```
