### ISSUE TITLE
I AM P*SS* OF*!!!!!! with POP UPS"  A new PowerShell stable release is available: vx.x.x" every single time!!

### ISSUE THREAD

**Issue by gbr000** [PowerShell/PowerShell#20319]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Start PowerShell

### Expected behavior

```console
I want just the clear empty (default) screen from PowerShell,

`PS C:\Users\userXXX>`

I don't want any new messages telling me what I should do or not! It's distracting me and I need consistent focus on my projects.

Give user option to remind a new update every:

- new release
- every week
- every month
- never
```

### Actual behavior

```console
`A new PowerShell stable release is available: v7.3.7`

every time I open PowerShell when it releases a new version,

=================================
NOTE:
================================

I completely understand that's not ***advisable to anyone who works in a company***, but I have PowerShell for recreational purposes at home only.

I do understand PowerShell fixes many bugs every release, and I am very thankful for that, but for now it's annoying the amount of reminders it gives me every X while.

I believe if it showed only "once" the first time you opened the program, but the following times do not. It would make things a lot cleaner, and give me proper pace to continue my work without interrupting it. I don't want to stop working every time I update PowerShell.

Please fix this,
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by xe0n11** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.3

**Comment by SeeminglyScience** [comment]
@gbr000 Please see the link above for instructions to disable the update check. Additionally please read the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/), thanks!

**Comment by gbr000** [comment]
I am tired of snowflakerism, or someone trying to be entitled to others feelings, emotions, opinions, vocabulary, decisions they made in life. Everyone is entitled to their ***own opinions*** but ***you must not feel entitled to others***. If not that will lead to society not long ago from that Führer who used to punish people to express themselves. Feeling tired, angry, pissed off is a human behavior and after all, machines are built from humans, we are not machines. ***Just a note***

**Comment by Luckz** [comment]
If you run it via WT or a shortcut you can modify, you can append the -NoLogo launch parameter:
`"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo`
