### ISSUE TITLE
process stdout does not render emojis in pwsh but does in cmd.exe

### ISSUE THREAD

**Issue by fire332** [PowerShell/PowerShell#20328]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Compile this C code:
```c
#include <stdlib.h>
#include <locale.h>
#include <stdio.h>

int main(void)
{
  setlocale(LC_ALL, "en_US.UTF-8");
  printf_s("✅\n");
  printf_s("❌\n");
  return EXIT_SUCCESS;
}
```
with either Clang 16.0.5 or MSVC 19.37.32824.0.

Run executable in Powershell through Windows Terminal 1.17.11461.0 with active codepage 65001 & `$OutputEncoding = [System.Text.Encoding]::UTF8`.

### NOTE
Expected behavior occurs with cmd.exe through Windows Terminal with code page 65001 and pasting emojis into PowerShell works so font cannot be the issue.

Additionally, running the same program through cmd.exe and redirecting stdout to a file, then using `cat` on the file in PowerShell displays the expected behavior. 

Doing the above but running the program through PowerShell will show up as
```
Ô£à
ÔØî
```
in both cat and in the text file.

### Expected behavior

```console
✅
❌
```

### Actual behavior

```console
?
?
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
`$OutputEncoding` is only for encoding strings piped into external executables. PowerShell uses `[Console]::OutputEncoding` to decide how to decode the output bytes into a string. Also using `[System.Text.Encoding]::UTF8` can be problematic as it's set to emit a BOM causing problems when you try to pipe strings to an external application. I find it's best to just set all three unless you need anything special.

```powershell
$OutputEncoding = [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
```


I've covered a bit of this in more detail under https://gist.github.com/jborean93/44b4688cc518d67bd7bc2192648384a3.

**Comment by fire332** [comment]
Thanks, this solves it. Sorry for the issue. I couldn't find anything after hours of googling.
