### ISSUE TITLE
How to Custom build on windows

### ISSUE THREAD

**Issue by mr-woot** [PowerShell/PowerShell#2032]
# I want to build this project on my own on windows and Linux, please provide docs for the same in readme.md

**Comment by adamdriscoll** [comment]
All those instructions are here: https://github.com/PowerShell/PowerShell/tree/master/docs/building

**Comment by mirichmo** [comment]
I am closing this issue because the question has been answered. If the existing documentation is not sufficient for you, reopen the issue with more specific questions or concerns.
