### ISSUE TITLE
PowerShell Remoting SPN?

### ISSUE THREAD

**Issue by McAndersDK** [PowerShell/PowerShell#2034]
Where in the code do I see the part where it Choose the SPN to use?
The issue at hand is this: [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11087799-psremoting-breaks-because-it-used-spn-name-with-cl)

So how do we fix this?

**Comment by mirichmo** [comment]
Within the repository, most of the client-side remoting code is located here: [...\src\system.management.automation\engine\remoting](https://github.com/PowerShell/PowerShell/tree/master/src/System.Management.Automation/engine/remoting)

A search for the string "SPN" will point you in the right direction.

**Comment by McAndersDK** [comment]
I really cant find the code that create the SPN "string".
Maybe it's just using windows normal http "engine" to connect? and not a custom made "engine" ?

Maybe it's just not possible to make it work with the SPN WSMAN/{Server} without complete rewrite that part?

The only thing about wsman I can find is sections about CrepSSP.
So maybe Microsoft only wanted to use the WSMAN SPN for CrepSSP? (for kerberos delegation?)

**Comment by iSazonov** [comment]
It seems the SPN is hardcoded for security reason. Also WSMAN is deprecated so close.

**Comment by McAndersDK** [comment]
Oh wow, say what again? any link to information about deprecating WSMAN ? @iSazonov

**Comment by iSazonov** [comment]
https://github.com/PowerShell/PowerShell/issues/11674#issuecomment-578947118

Implementation is based on SOAP which was deprecated.
