### ISSUE TITLE
Provide an option not to automatically configure apt, when installing the deb package 

### ISSUE THREAD

**Issue by rgl** [PowerShell/PowerShell#20379]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install the powershell ubuntu/debian package.

### Expected behavior

The debian package postinst script should not (unconditionally) install/configure the apt repository. That goes against the expectation that we, the administrators, are in control of all the repository sources. Also, having a .deb setup the repository source, is a really weird pattern, as one will have a new package source that we have no idea what created it (e.g. dpkg -S does not return that file).

So please, do not modify or put anything in the host /etc/apt/sources.list.d directory.

At least, the package should be modified to have a dconf setting to prevent it from automatically configure APT. That way, it can still support the current behavior.

For example, before I install the package, I would set the dconf setting as:

```bash
debconf-set-selections <<'EOF'
powershell powershell/skip_package_repository_configuration boolean true
EOF
```

For reference, this also happens with the vscode package, which has its own issue at https://github.com/microsoft/vscode/issues/190960.

### Actual behavior

It messes with the host APT configuration.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.14
PSEdition                      Core
GitCommitId                    7.2.14
OS                             Linux 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
I downloaded both https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/p/powershell/powershell_7.2.14-1.deb_amd64.deb and https://github.com/PowerShell/PowerShell/releases/download/v7.2.14/powershell_7.2.14-1.deb_amd64.deb and expanded the postinst script from control.tar.gz and could not see any reference to /etc/apt/sources.list.d

Which deb package is the offender in this case?

**Comment by rgl** [comment]
oh, indeed, thank you for looking into this!

not sure what happened... I might got confused with some other microsoft package that was doing that (e.g. the linked vscode one). it seems I have hallucinated... sorry.
