### ISSUE TITLE
After installing the preview version of PowerShell 7 (7.4.0-preview.5), it launches by default when I call `pwsh`. How do I get 7.3.7 to remain as the default PowerShell version side by side with the preview?

### ISSUE THREAD

**Issue by fmotion1** [PowerShell/PowerShell#20374]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Ensure you have PowerShell 7 (7.3.7) installed on your machine.
2. Install the preview version of PowerShell 7 (7.4.0-preview.5) via `winget install --id Microsoft.Powershell.Preview --source winget`
3. Press `WIN-R` to open the run dialog, and type `pwsh`.
4. Observe that `7.4.0` opens now instead of `7.3.7.`

Interestingly enough, if I open a command prompt (windows cmd), and then type `pwsh`, it opens the correct version (`7.3.7`)

### Expected behavior

```console
Running `pwsh` opens the non-preview version of PowerShell 7.
```

### Actual behavior

```console
Running `pwsh` opens the preview version of PowerShell 7.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.5
PSEdition                      Core
GitCommitId                    7.4.0-preview.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Removed

**Comment by 237dmitry** [comment]
Check:

Win+R > pwsh.exe

`where.exe pwsh.*`

**Comment by fmotion1** [comment]
I ended up doing a repair install of PowerShell 7.3.7 and now everything is working as expected - both versions are coexisting side by side. Someone on Discord hypothesized that the problem might be that the preview installer is setting `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\pwsh.exe` to the preview version of `pwsh.exe`. 

Since everything is running correctly now on my end, I'm not inclined to reinstall and test.

**Comment by StevenBucher98** [comment]
Interesting, on my machine I am facing the same issue but dont seem to have anything in the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\pwsh.exe` key on my system.

**Comment by fmotion1** [comment]
An unfortunate update: The behavior is back again, even after performing a repair install. Has anyone figured out how to prevent the preview version from launching as default over `7.3.7`? I'd really like to have both side by side, but if this behavior persists, I'm just going to uninstall preview. Help would REALLY be appreciated.

**Comment by SteveL-MSFT** [comment]
The problem appears to be this addition: https://github.com/PowerShell/PowerShell/blob/master/assets/wix/Product.wxs#L214-L216

Basically, the last install takes precedence so I believe even Microsoft Update will keep updating this and will make it hard for the user to predict what will start from Win+R

**Comment by heaths** [comment]
It's a shared registry value, so it either gets written or it doesn't. Is the desire here just to register the GA version and not the preview?

**Comment by SteveL-MSFT** [comment]
@heaths yes, I think the right behavior is that only stable versions register to `app paths` and preview does not.

**Comment by heaths** [comment]
Per offline discussion, I'll remove the shared registration for `pwsh.exe` and only write it for the stable release. Until the next stable upgrade, any uninstall of a preview will yield an error if you try to Win+R `pwsh.exe`, but a repair of any stable version will fix it:

```pwsh
# Fast, but external dependency I wrote a long time ago and still maintain.
Install-PSResource MSI # Or Install-Module MSI
Get-MSIProductInfo -Name '*PowerShell*' | Where-Object VersionMajor -ge 7 | Repair-MSIProduct -ReinstallMode 'mu'
```
Or
```pwsh
# Slow, but no external dependency
Get-CimInstance -ClassName Win32_Product -Filter "Name like '%PowerShell%' AND Version > '7.'" | ForEach-Object {
  Start-Process msiexec.exe -Wait -ArgumentList '/fmu', $_.IdentifyingNumber, '/qn'
}
```
