### ISSUE TITLE
Cannot install module from Azure DevOps feed

### ISSUE THREAD

**Issue by Agazoth** [PowerShell/PowerShell#20387]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Follow this guide: https://learn.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops

### Expected behavior

```console
Installs my module
```

### Actual behavior

```console
Install-Package: Cannot find the path 'C:\Users\Me\AppData\Local\Temp\1414719836\MyModule.0.0.2\MyModule.psd1' because it does not exist.
```

### Error details

```console
Exception             :
    Type    : System.Exception
    Message : Cannot find the path 'C:\Users\Me\AppData\Local\Temp\1414719836\MyModule.0.0.2\MyModule.psd1' because it does not ex
ist.
    HResult : -2146233088
TargetObject          : Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…lets.InstallPackage:InstallPackage) [Install-Package], Exceptio
n
FullyQualifiedErrorId : PathNotFound,Test-ValidManifestModule,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
InvocationInfo        :
    MyCommand        : Install-Package
    ScriptLineNumber : 9711
    OffsetInLine     : 34
    HistoryId        : 292
    ScriptName       : C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1
    Line             : $installedPackages = PackageManagement\Install-Package @PSBoundParameters

    PositionMessage  : At C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711 char:34
                       + … talledPackages = PackageManagement\Install-Package @PSBoundParameters
                       +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\program files\powershell\7\Modules\PowerShellGet
    PSCommandPath    : C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1
    InvocationName   : PackageManagement\Install-Package
    CommandOrigin    : Internal
ScriptStackTrace      : at Install-Module<Process>, C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1: line 97
11
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by prayaas-a** [comment]
I believe this is because PowerShellGet (which is internally used by PowerShell) is incompatible with NuGet v3 feeds, which is what Azure Artifacts uses (as it should - v2 is deprecated).

PowerShellGet is being replaced by Microsoft.PowerShell.PSResourceGet which I believe does support NuGet v3 repositories, but hasn't been released yet (it's in RC). Can owners here confirm if that module will, in fact, make it to PowerShell 7.4? It may even be possible to bring it downlevel to supported 7.x using v3 of PowerShellGet (the compatibility pack).

**Comment by SteveL-MSFT** [comment]
`Install-Package` is part of OneGet (aka PackageManagement) and not part of PS7.  PSResourceGet added support for nuget v3.

**Comment by Agazoth** [comment]
I see! Guess I'll try this tomorrow: https://devblogs.microsoft.com/powershell/psresourceget-preview-is-now-available/

Updating this issue with the results after upgrade.

**Comment by Agazoth** [comment]
I can confirm that PSResourceGet works. I just followed the instructions in the link above. Closing this issue
