### ISSUE TITLE
Update-AzDatabricksWorkspace command for updating Managed Services CMK and Managed Disk CMK fails

### ISSUE THREAD

**Issue by satishraj777** [PowerShell/PowerShell#20380]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello I am from Azure Databricks PG team at Microsoft. You can reach me out at v-sgandamuni@microsoft.com. 

I am writing this issue since we have some anomalies while running the below commands. 

Update-AzDatabricksWorkspace -SubscriptionId 7a9974b4-****-490d-a02d-b9b3a07332f6 -ResourceGroupName quickstart-template-validation -Name workspace456 -PrepareEncryption

Update-AzDatabricksWorkspace -SubscriptionId ead****-2100-4b4d-981a-3225eb77daa7 -ResourceGroupName lz-az-comm****-d-rg -Name lz-ncil01-d-db -EncryptionKeySource 'Microsoft.KeyVault' -ManagedServicesKeyVaultPropertiesKeyName 'cet-adb05-k01' -ManagedServicesKeyVaultPropertiesKeyVaultUri 'https://******-kv.vault.azure.net/' -ManagedServicesKeyVaultPropertiesKeyVersion '*****'

Update-AzDatabricksWorkspace -SubscriptionId eadb****-2100-4b4d-981a-3225eb77daa7 -ResourceGroupName lz-az-community-d-rg -Name lz-ncil01-d-db -EncryptionKeySource 'Microsoft.KeyVault' -ManagedDiskKeyVaultPropertiesKeyName '***-adb05-k01' -ManagedDiskKeyVaultPropertiesKeyVaultUri 'https://***-adb05-kv.vault.azure.net/' -ManagedDiskKeyVaultPropertiesKeyVersion '*****' -ManagedDiskRotationToLatestKeyVersionEnabled

Update-AzDatabricksWorkspace -SubscriptionId eadb9dfd-2100-4b4d-981a-3225eb77daa7 -ResourceGroupName lz-az-community-d-rg -Name lz-ncil01-d-db -EncryptionKeySource 'Microsoft.KeyVault' -EncryptionKeyVaultUri 'https://***-adb05-kv.vault.azure.net/' -EncryptionKeyName '***-adb05-k01' -EncryptionKeyVersion '****'

We are getting this error while we try to run any of the above commands. Also attaching the screenshot. 
![cmkbug](https://github.com/PowerShell/PowerShell/assets/91755069/9c567ccc-2ee8-4cfd-99a4-2d34d123bfb7)

![image](https://github.com/PowerShell/PowerShell/assets/91755069/b1722a94-76ec-4213-985a-0862ba7738d0)

After checking our backend logs what we see is that while we run a simple update workspace (the first command) to set prepareEncryption true, the request payload also checks in managedServices key source set failing with the error message. Below is the screenshot and highlighted set which is being called, which is not something we are calling in the command. 

![image](https://github.com/PowerShell/PowerShell/assets/91755069/8dec42cc-a1b0-46e2-a9b7-dbe49d1fef24)
![cmkbugms](https://github.com/PowerShell/PowerShell/assets/91755069/e1fa83be-c118-4b9f-b281-ac16fa155ee9)

Similar issue with other commands as well. As a workaround we saw that the commands run fine when the encryptionKeySource property parameter is removed from the commands. But ideally it should not create any problem / break to a request involving Managed Services or Managed Disk CMK. Below are the commands which work fine, after we remove the encryptionkeySource property parameter

Update-AzDatabricksWorkspace -SubscriptionId eadb****-2100-4b4d-981a-3225eb77daa7 -ResourceGroupName lz-az-community-d-rg -Name lz-ncil01-d-db -ManagedDiskKeyVaultPropertiesKeyName '***-adb05-k01' -ManagedDiskKeyVaultPropertiesKeyVaultUri 'https://***-adb05-kv.vault.azure.net/' -ManagedDiskKeyVaultPropertiesKeyVersion '*****' -ManagedDiskRotationToLatestKeyVersionEnabled

Update-AzDatabricksWorkspace -SubscriptionId ead****-2100-4b4d-981a-3225eb77daa7 -ResourceGroupName lz-az-comm****-d-rg -Name lz-ncil01-d-db -ManagedServicesKeyVaultPropertiesKeyName 'cet-adb05-k01' -ManagedServicesKeyVaultPropertiesKeyVaultUri 'https://******-kv.vault.azure.net/' -ManagedServicesKeyVaultPropertiesKeyVersion '*****'

Can you please take a look into this and help fix this? 

### Expected behavior

```console
Command should run successfully
```

### Actual behavior

```console
Fails
```

### Error details

```console
Update-AzDatabricksWorkspace -Subscriptionld 7a9974b4-6ef3-490d-a02d-b9b3a07332f6 -ResourceGroupName quickstart-template-validation 
AZ. Databricks . aldentity : The keysource is 
specified as keyvault but keyvault details are not correctly provi ded. 
At \OneDrive 
Mi ndowspowershel 1 Databri cks\l. 2. cksWorkspace . PSI : 391 char :17 
Az . Databri cks . pri vate\New-AzDatabr i cksWorks pace_CreateVi a 
-Name workspace456 
+ Categorylnfo 
. ma um" 
. Inval idoperation: ({ body = { 
} [New-AzDatabrick... eateVi aldentity] , Exception 
+ FullyQua1ifiedErrorId 
. Inval idEncrypti onEntitiesKeyVau1 tVa1ue , Mi crosoft . Azure. PowerShe11 . Cmdl ets . Databri cks . Cmdl ets .
```

### Environment data

```powershell
Name                           Value                                                                                                                                            
----                           -----                                                                                                                                            
PSVersion                      5.1.22621.1778                                                                                                                                   
PSEdition                      Desktop                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                          
BuildVersion                   10.0.22621.1778                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                              
SerializationVersion           1.1.0.1
```

### Visuals

Below error is while running 1st command i.e. $workSpace = Update-AzDatabricksWorkspace -Name workspace456 -ResourceGroupName quickstart-template-validation -PrepareEncryption .

![image](https://github.com/PowerShell/PowerShell/assets/91755069/fc1b3120-dbd4-4e69-89db-c8a7ba5da174)

Below error is while running 2nd command i.e. Update-AzDatabricksWorkspace -ResourceGroupName quickstart-template-validation -Name test-disk-workspace -EncryptionKeySource 'Microsoft.KeyVault' -ManagedServicesKeyVaultPropertiesKeyName 'keyc' -ManagedServicesKeyVaultPropertiesKeyVaultUri 'https://constantkv.vault.azure.net/' -ManagedServicesKeyVaultPropertiesKeyVersion 'a9c9a6da3f024f1a83bac2588faaaaad'

![image](https://github.com/PowerShell/PowerShell/assets/91755069/a2ef83db-22aa-423b-8679-ac9972d11eec)

Below error is while running 3rd command i.e. Update-AzDatabricksWorkspace -ResourceGroupName quickstart-template-validation -Name test-disk-workspace -EncryptionKeySource 'Microsoft.KeyVault' -ManagedDiskKeyVaultPropertiesKeyName 'keyc' -ManagedDiskKeyVaultPropertiesKeyVaultUri 'https://constantkv.vault.azure.net/' -ManagedDiskKeyVaultPropertiesKeyVersion 'a9c9a6da3f024f1a83bac2588faaaaad' -ManagedDiskRotationToLatestKeyVersionEnabled

![image](https://github.com/PowerShell/PowerShell/assets/91755069/693a9dd9-185b-4af2-a603-7260893e019b)

**Comment by satishraj777** [comment]
Hello we have customer also reporting this similar issue. While trying to update DBFS encryption using the below command it fails with InvalidEncryptionEntitiesKeyVaultValue. 

_Update-AzDatabricksWorkspace -SubscriptionId 7a9974b4-6ef3-490d-a02d-b9b3a07332f6 -ResourceGroupName quickstart-template-validation -Name test-workspace3-928 -EncryptionKeySource 'Microsoft.Keyvault' -EncryptionKeyVaultUri 'https://constantkv.vault.azure.net/' -EncryptionKeyName 'keyc' -EncryptionKeyVersion 'a9c9a6da3f024f1a83bac2588faaaaad'_


**Error message:** 
Az.Databricks.private\New-AzDatabricksWorkspace_CreateViaIdentity : The keysource is specified as keyvault but 
keyvault details are not correctly provided.
At C:\Users\v-sgandamuni\OneDrive - 
Microsoft\Documents\WindowsPowerShell\Modules\Az.Databricks\1.2.0\custom\Update-AzDatabricksWorkspace.ps1:391 
char:17
+ ...             Az.Databricks.private\New-AzDatabricksWorkspace_CreateVia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = {
  "...mium"
  }
} }:<>f__AnonymousType7`1) [New-AzDatabrick...eateViaIdentity], Exception
    + FullyQualifiedErrorId : InvalidEncryptionEntitiesKeyVaultValue,Microsoft.Azure.PowerShell.Cmdlets.Databricks 
   .Cmdlets.NewAzDatabricksWorkspace_CreateViaIdentity

Here is the payload of the request we see in our logs when the above command is being invoked. 

Request content: {"properties":{"encryption":{"entities":{"managedServices":{"keySource":"Microsoft.Keyvault","keyVaultProperties":{"keyVaultUri":"https://constantkv.vault.azure.net/","keyName":"keyc","keyVersion":"a9c9a6da3f024f1a83bac2588faaaaad"}},**"managedDisk":{"keySource":"Microsoft.Keyvault","rotationToLatestKeyVersionEnabled":false**}}},"managedResourceGroupId":"/subscriptions/7a9974b4-6ef3-490d-a02d-b9b3a07332f6/resourceGroups/databricks-rg-test-workspace3-928-v4gehmkk7v3ts","parameters":{"enableNoPublicIp":{"value":false},"natGatewayName":{"value":"nat-gateway"},"publicIpName":{"value":"nat-gw-public-ip"},"prepareEncryption":{"value":false},"encryption":{"value":{"keySource":"Microsoft.Keyvault","KeyName":"keyc","keyversion":"a9c9a6da3f024f1a83bac2588faaaaad","keyvaulturi":"https://constantkv.vault.azure.net/"}},"requireInfrastructureEncryption":{"value":false},"storageAccountName":{"value":"dbstoragen22d62mefbhki"},"storageAccountSkuName":{"value":"Standard_GRS"},"vnetAddressPrefix":{"value":"10.139"}},"authorizations":[{"principalId":"9a74af6f-d153-4348-988a-e2672920bee9","roleDefinitionId":"8e3af657-a8ff-443c-a75c-2fe8c4bcb635"}],"createdDateTime":"0001-01-01T00:00:00Z"},"sku":{"name":"premium"},"location":"eastus"}

If you see the above payload you can see that the managedDisk encryption property set is getting called and it is invalid, hence the command fails. The main concern is why is the managedDisk encryption property is being pushed here, while the command is to update DBFS encryption. Both of them are different scenarios.

**Comment by ArmaanMcleod** [comment]
This issue should be transferred to https://github.com/Azure/azure-powershell

**Comment by satishraj777** [comment]
Thanks for checking in Armaan ! Would you be able to transfer this internally or do you suggest us to file a ticket separately with Az PowerShell?
