### ISSUE TITLE
7.4.0-preview.5 and 6 - Get-AD* tools do not work

### ISSUE THREAD

**Issue by xpwn3rx** [PowerShell/PowerShell#20403]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install PowerShell preview and issue a get-ad* command such as get-aduser username

### Expected behavior

```console
Return this:

PS C:\Users\ag24413> get-aduser ag24413                                                                                 

DistinguishedName : CN=nope,OU=Server and Storage Systems,OU=SOMETHING,OU=SOMETHING,DC=domain,DC=com
Enabled           : True
GivenName         : Allen
Name              : nope
ObjectClass       : user
ObjectGUID        : 643f4992-fd92-49ee-8a06-0f98714c3148
SamAccountName    : nope
SID               : S-1-5-21-821248920-976842980-1539857752-31835
Surname           : George
UserPrincipalName : Allen.George@domain.com
```

### Actual behavior

```console
PS C:\Windows\System32> get-aduser ag24413
Get-ADUser: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.
```

### Error details

```console
All AD tools return this error:
Get-ADUser: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.
```

### Environment data

```powershell
PS C:\Windows\System32> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.6
PSEdition                      Core
GitCommitId                    7.4.0-preview.6
OS                             Microsoft Windows 10.0.25951
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/19785522/951e38a3-0a5e-4a6c-9c3f-4df960f1e28a)

This works on PowerShell 5.1 on the same machine.

![image](https://github.com/PowerShell/PowerShell/assets/19785522/50fde21f-610f-4437-8fff-d955f1aa2b45)

**Comment by jazzdelightsme** [comment]
What happens if you run this first?

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13
```

**Comment by xpwn3rx** [comment]
I get the same error unfortunately.
![image](https://github.com/PowerShell/PowerShell/assets/19785522/9a107db7-d58f-46dc-a812-182c1d0f6355)

**Comment by jborean93** [comment]
See https://github.com/PowerShell/PowerShell/issues/20168, will be fixed when net8 rc2 comes out and pwsh ships with it.

**Comment by xpwn3rx** [comment]
Thank you, I'm not sure why that didn't come up when I searched before opening this.
