### ISSUE TITLE
`Start-Process -Verb` should have argument completer

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#20414]
### Summary of the new feature / enhancement

Currently if you try to tab complete verbs with `Start-Process -Verb` there is no tab completion. 

Given the verbs per extension(select few for example) are shown in the following [table](https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.3&WT.mc_id=ps-gethelp#-verb
): 

<html>
<body>

File type | Verbs
-- | --
.cmd | Edit, Open, Print, RunAs, RunAsUser
.exe | Open, RunAs, RunAsUser
.txt | Open, Print, PrintTo
.wav | Open, Play

</body>
</html>

it makes sense to have tab completion for these extensions if `FilePath` is specified with an extension.

E.g. `Start-Process -FilePath powershell.exe -Verb <tab>` -> should give 3 options (open, runas, runasuser).

The other option maybe is to include all options to `ValidateSet` but that won't help complete for specific file types. Additionally, given this requires too many verbs and no consistency between systems, it's probably not a good option.

### Proposed technical implementation details (optional)

- If `FilePath` has an extension, get `Verbs` from `System.Diagnostics.ProcessStartInfo` and complete for the given path. Tests can probably check against this as well since verbs can vary on different systems.
- Given `-Verb` only works on Windows, we can limit this completion to `Platform.IsWindowsDesktop` given `-Verb` only works with this platform type and doesn't seem to work with headless windows SKU.
- If `FilePath` has no extension, skip completion unless filepath can be resolved with an extension e.g. `powershell` executable resolving to `powershell.exe` by checking the `Application` command type.

**Comment by ArmaanMcleod** [comment]
Had this one come up recently as well when I was using `Start-Process` for my own stuff.

Thought it was a good idea to raise it and see if anyone would find this useful to have 🙂.

**Comment by mklement0** [comment]
👍 for the enhancement.

Note that you can use the `.Verbs` property of `ProcessStartInfo` to discover available verbs (e.g. `([System.Diagnostics.ProcessStartInfo] @{ FileName = 'x.exe' }).Verbs`) - though that appears to be flaky (["and other possible verbs are not always detected depending on your system setup."](https://learn.microsoft.com/en-US/dotnet/api/System.Diagnostics.ProcessStartInfo.Verbs)). However, it might discover some nonstandard verbs that a particular file type defines; note that the discovery is purely based on the _filename extension_, so an executable specified without extension would have to be resolved to its full name first.

**Comment by ArmaanMcleod** [comment]
Thanks @mklement0

I've also noticed that `System.Diagnostics.ProcessStartInfo` gives unpredictable results depending on system. E.g. on my machine if I do `Start-Process -FilePath mytextfile.txt -Verb` the only verbs shown are `printto`, when the documentation has `open`, `print` and `printto` for `.txt` extension.

Looking at the source code: https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/ProcessStartInfo.cs,75bd50346bca44e3,references it looks at ProgId defined under `HKCR\.ext` registry key. This SO post goes into more detail: https://stackoverflow.com/questions/31809435/get-list-of-available-verbs-file-association-to-use-with-processstartinfo-in-c

Also in https://github.com/dotnet/runtime/issues/52960 it seems that all possible verbs are not shown.

I guess tab completion for this will be a best effort scenario 😄 .

**Comment by iSazonov** [comment]
For reference https://learn.microsoft.com/en-us/visualstudio/extensibility/registering-verbs-for-file-name-extensions?view=vs-2022

**Comment by RokeJulianLockhart** [comment]
> it makes sense to have tab completion for these extensions if FilePath is specified with an extension.

What if it's not? Could PowerShell use a command like `file` to introspect the current path, thereby determining its filetype? After all, a MIME-type might be more useful in this case, considering that anything attributed with `text/*` would be afforded its relevant flags (usage of `*.txt.cmd` or `*.txt.ps1` is less common).
