### ISSUE TITLE
`ConvertFrom-StringData` -Raw switch to parse data field as literal

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#20418]
### Summary of the new feature / enhancement

It would be better to add a `-Raw` switch to the `ConvertFrom-StringData` cmdlet. Thanks to this, the user can avoid potential errors, especially in non-interactive mode, in scripts. In a large volume of input data it can be difficult to find the source of the error.

```powershell
$ "TITLE=Some Title\Compilation" | ConvertFrom-StringData
ConvertFrom-StringData: Invalid pattern 'Some Title\Compilation' at offset 12. Unrecognized escape sequence \C.

$ "TITLE=Some Title\Compilation" -replace '\\','\\' | ConvertFrom-StringData

Name                           Value
----                           -----
TITLE                          Some Title\Compilation
```

### Proposed technical implementation details (optional)

Wishful:

```powershell
$ $metadata | ConvertFrom-StringData -Raw    # @{ key = "literal string" }
```

**Comment by jdhitsolutions** [comment]
Added to the working group to review

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  Although the docs do mention the scenario, it does seem valid to have a new `-AsLiteral` switch that would effectively auto-escape the input where pipeline input would be commonly used with this cmdlet.  We think that `-Raw` would be too confusing to users.
