### ISSUE TITLE
ConvertFrom-StringData: datafield after the first delimiter should be literal string.

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#20417]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`\C` characters sequence in the field after the separator causes an error:

```powershell
$ 'aaa=aaa\Ccc' | ConvertFrom-StringData                                                 
ConvertFrom-StringData: Invalid pattern 'aaa\Ccc' at offset 5. Unrecognized escape sequence \C.
```

### Expected behavior

```console
Data field after the first delimiter should be the literal. Without escapes:


$ 'aaa=aaa\\Ccc' | ConvertFrom-StringData

Name                           Value
----                           -----
aaa                            aaa\Ccc
```

### Actual behavior

```console
Data field causes the parse error
```

### Error details

```console
$ (Get-Error).Exception                                                                        

Type           : System.Text.RegularExpressions.RegexParseException
Error          : UnrecognizedEscape
Offset         : 5
Message        : Invalid pattern 'aaa\Ccc' at offset 5. Unrecognized escape sequence \C.
ParamName      : 
TargetSite     : Char ScanCharEscape()
Data           : {}
InnerException : 
HelpLink       : 
Source         : System.Text.RegularExpressions
HResult        : -2147024809
StackTrace     :    at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
                    at System.Text.RegularExpressions.RegexParser.UnescapeImpl(String input, Int32 i)
                    at Microsoft.PowerShell.Commands.ConvertFromStringDataCommand.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.6
PSEdition                      Core
GitCommitId                    7.4.0-preview.6
OS                             ArcoLinux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/23ceedb2-fcac-4e36-9f38-1413b0475554)

**Comment by mklement0** [comment]
From [the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-stringdata):

> supports escape character sequences that are allowed by conventional machine translation tools. That is, the cmdlet can interpret backslashes (`\`) as escape characters in the string data by using the [Regex.Unescape Method](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.unescape)

In other words:

* The behavior is by design, and changing it would be a serious breach of backward compatibility.
* Your issue could be framed as a _feature request_, and would require a _new switch_ - say `-Raw` - as an _opt-in_ to the desired behavior.

**Comment by 237dmitry** [comment]
> Your issue could be framed as a feature request

How I can do it without recreation of initial issue?

**Comment by mklement0** [comment]
Recreating wouldn't be hard - you can just copy the text of the initial post into a new issue of type "Feature Request / Idea" and adapt it based on this conversation.

Otherwise, you'd have to ask someone who has labeling privileges - say @iSazonov - to add the relevant label to _this_ issue (but updating the initial post is required either way).
