### ISSUE TITLE
`Get-Command -Verb` should have verb argument completer

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#20412]
### Summary of the new feature / enhancement

Related to #20059.

`Get-Command -Verb` should probably use the same argument completer for `Get-Verb -Verb`. 

Could also see if filtered completion is needed if `-Noun` is specified as well.

For example:

```powershell
Get-Command -Noun Acl -Verb <Get or Set>
```

I would expect only `Get` or `Set` to be recommended since those are the only possible verbs for `Acl` noun.

```powershell
> Get-Command -Noun Acl

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-Acl                                            7.0.0.0    Microsoft.PowerShell.Security
Cmdlet          Set-Acl                                            7.0.0.0    Microsoft.PowerShell.Security
```

### Proposed technical implementation details (optional)

- Make `VerbArgumentCompleter` complete verbs for `Get-Command -Verb`.
- If `-Noun` parameter specified, recommend possible verbs for the given noun.

**Comment by ArmaanMcleod** [comment]
@ThomasNieto @kilasuit thoughts on this?

**Comment by jhoneill** [comment]
Completers should be provided where-ever practical. For Get-Command -verb is easy enough to ask why it doesn't already work that way. Noun is likely to be too slow to work as a completer because it requires getting all the commands and figuring out what nouns they have.

**Comment by MartinGC94** [comment]
I have my own personal Noun completer: https://github.com/MartinGC94/UsefulArgumentCompleters/blob/main/ScriptCompleters/Shared/GetCommandAndVerb.ps1#L44 from my experience the performance is perfectly fine. It's similar to the normal command completion (which makes sense, since we are doing the exact same command discovery + a bit more processing).

**Comment by ArmaanMcleod** [comment]
Given we are already have a `NounArgumentCompleter` which uses `Get-Command` to get possible nouns it should  not be a performance concern if we follow similar implementation.
