### ISSUE TITLE
Upload sometimes fails; use appveyor CMDLET to upload

### ISSUE THREAD

**Issue by probonopd** [PowerShell/PowerShell#2042]
## Steps to reproduce

Send pull requests
## Expected behavior

Pull requests get built and tested successfully by AppVeyor
## Actual behavior

Sometimes CoreCLR tests fail to upload, e.g., here:
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-alpha.9-183#L4132
The test section of the CI system then stopped and didn't set the FullCLR path.

@TravisEz13 [suggests](https://github.com/PowerShell/PowerShell/pull/2027#issuecomment-241905545)

> We should use the appveyor CMDLET to upload the results. 
## Environment data

n/a

**Comment by TravisEz13** [comment]
I already fixed this here: https://github.com/PowerShell/PowerShell/blob/master/tools/appveyor.psm1#L243
https://github.com/PowerShell/PowerShell/commit/f8520e06b3ccc9e58f18a9645d992cf0685413c5
