### ISSUE TITLE
Set-StrictMode -Version PSVersion values

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShell#20430]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Why does `Set-StrictMode -Version` accept any valid PSVersion? I could see if a new strict mode came out with each PS version but that never materialized. I believe it would be better to make this parameter only accept the existing strict mode version values and removed the check for any valid PS version.

Excerpt from the help:

> Specifies the conditions that cause an error in strict mode. **This parameter accepts any valid PowerShell version
    number**. Any number higher than `3` is treated as `Latest`. The value supplied must be the string `Latest` or a
    string that can be converted to a System.Version type. The version must match a valid release version of
    PowerShell.

### Expected behavior

```console
Only accepts existing strict mode values
```

### Actual behavior

```console
Accepts valid `PSVersion`
```

### Environment data

```powershell
7.4-preview6
```

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  Although we agree that -Version should have been an enum since there is a fixed set of versioned rules, a search on GitHub shows that at least a few folks have used versions other than 1, 2, 3 and latest so would break.  We should add a new ruleset for 7.0 and ensure that any new language changes also add support for strict mode.
