### ISSUE TITLE
Bypass the personal and system profiles if the `Shift` key is hold down.

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#20435]
### Summary of the new feature / enhancement

PowerShell startup problems are often caused by the `$Profile` script as e.g.: [Powershell 7 Blank](https://stackoverflow.com/questions/77226427/powershell-7-blank), yet troubleshooting requires to open a different (*none-PowerShell*) prompt or playing with the shortcuts of the Operating System.
Probably the easiest way (*from Windows*) is [`Start` --> `Run` --> `pwsh -NoProfile`](https://devblogs.microsoft.com/scripting/powertip-start-powershell-with-no-profile/).
For an end-user, this isn't always that obvious as the `$Profile` script might also cause less clear issues (e.g. different host colors than expected). Besides, instructions might be limited to the `Run with PowerShell` context-menu or a locked-down system with a single custom shortcut.

### Proposed technical implementation details (optional)

Bypass the personal and system profiles while holding down the <kbd>Shift</kbd> (or any other control) key.

By adding the following code in the top of my `$Profile`, I simulated this propose.
```PowerShell
 Add-Type -Name Keyboard -Namespace GetKeyState -MemberDefinition @'
    [DllImport("user32.dll", CharSet=CharSet.Auto, ExactSpelling=true)] 
    public static extern short GetAsyncKeyState(int virtualKeyCode); 
'@
if ([GetKeyState.Keyboard]::GetAsyncKeyState(16) -eq -32767) { return 'bypassed PowerShell Profile' }
```
But as other (unwanted) scripts might simply replace the complete `$Profile` script, it should actually be managed by the PowerShell engine.

**Comment by 237dmitry** [comment]
> For an end-user, this isn't always that obvious as the $Profile script might also cause less clear issues (e.g. different host colors than expected)

I don't understand how this can be implemented with all the variety of launch methods. For example, I run the pwsh profile in the Windows Terminal with `Ctrl-Shift-2` and will I have to hold down another `Shift` with my other hand? The same story with launching elevated pwsh from lnk-file with `Ctrl-Shift+click`

I believe that end-users can run `pwsh -nop`

**Comment by iRon7** [comment]
@237dmitry,

> I don't understand how this can be implemented with all the variety of launch methods.

It not supposed to be a solution for any CLI (as e.g. #8072).
But when launched (in anyway) from any UI, as e.g. a (pinned) shortcut in Windows.

**Comment by jhoneill** [comment]
I was going to post "You can put this in your profile to skip it if shift is held down" but you have already found that :-) 
I found that myself because it seemed way back (V2 or V3) that this should be built in and wasn't - starting in "safe" mode by holding down shift (or sometimes ctrl) goes back decades and I've never had an explanation for why PowerShell can't. 

Anyone _can_ run pwsh -noprofile - some of us even create shortcuts for that (I have one in terminal) but it would save enough people a few seconds often enough that I'd add it

**Comment by kilasuit** [comment]
> Probably the easiest way (from Windows) is [Start --> Run --> pwsh -NoProfile](https://devblogs.microsoft.com/scripting/powertip-start-powershell-with-no-profile/).

in a session you can relaunch pwsh but for your usecase would this in windows be of use? (been reviewed but if we can get more yes'es then it can become something that you get outta the box for free) https://github.com/PowerShell/PowerShell/issues/18148

**Comment by iRon7** [comment]
@kilasuit

> in a session you can relaunch pwsh

In what session? What if I can't open any new `pwsh` session anymore as it is broken due to `$Profile`?
In Windows, I know my way around (I would probably open `CMD` *if available*) but in other Operating Systems, I feel less secure to go (or guide somebody) through a repair process unless I would still be able to open PowerShell (in "safe mode").
In other words:
If PowerShell doesn't start anymore, a very likely cause is the `$Profile`.
To **resolve** this, the instructions would be some something like (Maybe something for [about Profiles](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_profiles)):
1. Open PowerShell while holding down the <kbd>Shift</kbd> key
2. Rename the each `$Profile`:
```PowerShell
$Profile.PSObject.Properties | Where-Object value -Like *profile.ps1 | ForEach-Object {
    Rename-Item $_.Value "$($_.Value).Bak" -Force -ErrorAction SilentlyContinue
}
```
* Note that the renaming of some of these profiles requires administrator rights.

These instructions will probably get a lot more complicated (OS specific and taking specific configurations consideration) when there isn't any `pwsh` session available anymore...
