### ISSUE TITLE
PowerShell for Linux VERY slow to start in WSL

### ISSUE THREAD

**Issue by RobCannon** [PowerShell/PowerShell#20442]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I start PowerShell in a WSL session, sometimes the start time can be VERY slow (2-5 minutes).  I have tried removing my profile and this continues to happen.  It will also happen if I start PowerShell like this `pwsh -nop -noni`.

If I restart WSL (with `wsl.exe --shutdown`), it will work fine for a while, but after a couple of hours, it will happen again.

I am using Powershell 7.3.7, Ubuntu 22.04 in WSL.  Here is the WSL and Windows version info:
```
WSL version: 2.0.0.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.57
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22623.1095
```

I don't know if this would happend in a real Linux environment or if this is somehow specific to WSL.  This does not occur with the same version of Powershell in Windows.  This only started occurring with the 7.3.7 release.

### Expected behavior

```console
PowerShell would start in a second or so.
```

### Actual behavior

```console
PowerShell takes many minutes to start.  I have not timed it.  But I started entering this issue when this occurred, and it is still stuck.
```

### Error details

```console
There are no error messages.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Linux 5.15.123.1-microsoft-standard-WSL2 #1 SMP Mon Aug 7 19:01:48 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
> I don't know if this would happend in a real Linux environment

Not 7.3.7 but I think there is no difference

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/4314470d-7592-41d5-bdeb-3ecae147c986)

**Comment by ThomasNieto** [comment]
Do you also experience the issue on 7.4-preview6?

**Comment by RobCannon** [comment]
I have not installed a preview version.  This is critical to my team's function and I don't want to use a preview version.  I can try rolling back to the previous version.

**Comment by SteveL-MSFT** [comment]
@RobCannon you shouldn't use a preview version in production, but each version of PS7 has a new version of .NET and there are likely changes in .NET that impact startup time (generally, it should be getting better though).  If you could verify that 7.4-preview.6 improves or is the same, it might help with diagnosing the issue.

**Comment by RobCannon** [comment]
I will have to switch to that version for all of my usage since this does not occur the first time that I use PowerShell.  It starts happening a few hours into the day, so it might be a while before I can confirm this has an effect.

**Comment by RobCannon** [comment]
I am still seeing the slow down occur using 7.4-preview.6.

**Comment by RobCannon** [comment]
I rebuilt my WSL instance (which I had done shortly a week or two before this started happening) and the issue has not come up since.  Since no one else was seeing it, it seems to be something was messed up in my WSL installation.
