### ISSUE TITLE
Remove-AzResourceGroup does not run as a background job

### ISSUE THREAD

**Issue by martinthong125** [PowerShell/PowerShell#20448]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This command works as expected but have to wait before running the next line of command.
```
Remove-AzResourceGroup -Name $($resourceGroup.ResourceGroupName) -Force
```
This command seems to work as the command runs but it did not delete the resource group.
```
Remove-AzResourceGroup -Name $($resourceGroup.ResourceGroupName) -Force -AsJob
```

### Expected behavior

```console
The 2nd command should run as a background job and delete the resource group.
```

### Actual behavior

```console
The 2nd command did not run as a background job and hence did not delete the resource group.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Darwin 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
Please open an issue in the repository for Azure PowerShell models: https://github.com/Azure/azure-powershell
