### ISSUE TITLE
ScriptMethods should know themselves, so they can optionally chain

### ISSUE THREAD

**Issue by StartAutomating** [PowerShell/PowerShell#20456]
### Summary of the new feature / enhancement

I would like to make a ScriptMethod that chains until the last step.

Unfortunately, a ScriptMethod lacks two key pieces of information that would enable this:

* A ScriptMethod does not know its own name
* A ScriptMethod does not know it's calling AST

### Proposed technical implementation details (optional)

These two pieces of information should be embedded into variables, if possible.

**Comment by SeeminglyScience** [comment]
I can only think of one way you could mean "chain" but I'm not sure how that information would help with that. Could you elaborate?

**Comment by StartAutomating** [comment]
> I can only think of one way you could mean "chain" but I'm not sure how that information would help with that. Could you elaborate?

Sure thing!

I want a method to return an updated $this _if and only if_ the next ScriptMethod has a value.   One cannot do it without callstack peeking in each ScriptMethod and knowing the name of the method.

I recently wanted to do something like this within [Posh](https://github.com/StartAutomating/Posh)'s "stackable" functions, which are used for prompt modifications.

[This is an example of a painful workaround](https://github.com/StartAutomating/Posh/blob/main/Types/Posh.Stackable/Replace.ps1) (letting an additional $true boolean are be a signal to pass thru).

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this and decided that we're not currently interested in providing information about the method's caller. However, we do think there is value in improving `InvocationInfo` for the `InvokeWithPipe` code path. We have opened issue #20500 to track that.

**Comment by StartAutomating** [comment]
@SeeminglyScience thanks for the update, I hope the improved invocation info is enough to be able to accomplish the scenario.

Close it?

**Comment by SeeminglyScience** [comment]
> Close it?

The bot will do that now that the label `Resolution-Declined` is applied, but you're more than welcome to do so as well. Either way works!
