### ISSUE TITLE
Make TypeConfigurationEntry and RunspaceConfiguration public under System.Management.Automation.Runspaces

### ISSUE THREAD

**Issue by proxb** [PowerShell/PowerShell#2045]
Steps to reproduce
------------------
Working with runspaces in PowerShell core presents some issues when it comes to adding Type data files into the new runspace. The first problem is that the RunspaceConfiguration property is hidden so you cannot get to anything within it other than using reflection. Because of this, you cannot get to the Types collection within the property to add extra type files to the runspace. The next issue is that the TypeConfigurationEntry which is required to be added to the Types collection is also a private type and unreachable without using reflection to invoke the constructor.

```PowerShell
$Runspace = [runspacefactory]::CreateRunspace()
$TypeFile = "C:\Temp\TypeFile.ps1xml"
#This fails because TypeConfigurationEntry is private
$TypeEntry = New-Object System.Management.Automation.Runspaces.TypeConfigurationEntry -ArgumentList $TypeFile
#This will fail because RunspaceConfiguration is private
$Runspace.RunspaceConfiguration.types.Append($TypeEntry)
```

Expected behavior
-----------------
The type files should be used to build the TypeConfigurationEntry object which in turn should added to the Types collection under the RunspaceConfiguration property of the runspace. The RunspaceConfiguration property should be accessible to view.

**TypeConfigurationEntry Object**
```PowerShell
PS C:\> $TypeEntry


FileName : C:\Temp\TypeFile.ps1xml
TypeData : 
IsRemove : False
Name     : C:\Temp\TypeFile.ps1xml
PSSnapIn : 
BuiltIn  : False
```

**RunspaceConfiguration Property**
```PowerShell
PS C:\> $Runspace.RunspaceConfiguration


ShellId               : Microsoft.PowerShell
Cmdlets               : {Get-WinEvent, New-WinEvent, Get-Counter, 
                        Import-Counter...}
Providers             : {Registry, Alias, Environment, FileSystem...}
Types                 : {C:\Windows\System32\WindowsPowerShell\v1.0\GetEvent.ty
                        pes.ps1xml, C:\Windows\System32\WindowsPowerShell\v1.0\
                        types.ps1xml, C:\Windows\System32\WindowsPowerShell\v1.
                        0\typesv3.ps1xml}
Formats               : {C:\Windows\System32\WindowsPowerShell\v1.0\Event.Forma
                        t.ps1xml, C:\Windows\System32\WindowsPowerShell\v1.0\Di
                        agnostics.Format.ps1xml, C:\Windows\System32\WindowsPow
                        erShell\v1.0\Certificate.format.ps1xml, C:\Windows\Syst
                        em32\WindowsPowerShell\v1.0\DotNetTypes.format.ps1xml..
                        .}
InitializationScripts : {}
Scripts               : {}
Assemblies            : {Microsoft.PowerShell.Commands.Diagnostics, 
                        Version=3.0.0.0, Culture=neutral, 
                        PublicKeyToken=31bf3856ad364e35, 
                        ProcessorArchitecture=MSIL, 
                        Microsoft.PowerShell.ConsoleHost, Version=3.0.0.0, 
                        Culture=neutral, PublicKeyToken=31bf3856ad364e35, 
                        ProcessorArchitecture=MSIL, 
                        System.Management.Automation, Version=3.0.0.0, 
                        Culture=neutral, PublicKeyToken=31bf3856ad364e35, 
                        ProcessorArchitecture=MSIL, 
                        Microsoft.PowerShell.Commands.Utility, 
                        Version=3.0.0.0, Culture=neutral, 
                        PublicKeyToken=31bf3856ad364e35, 
                        ProcessorArchitecture=MSIL...}
AuthorizationManager  : Microsoft.PowerShell.PSAuthorizationManager
```

Actual behavior
---------------
Errors are thrown about the type not being found when attempt to create the TypeConfigurationEntry object using the path of the type file as its argument. The RunspaceConfiguration property is not publicly available to dig into the types collection to add the type files. Attempting to view the property results in no data being displayed.

Workaround
----------------
I can get around this by using reflection to locate the RunspaceConfiguration property and then further using reflection to locate and use the constructor for TypeConfigurationEntry to build the object and then apply it to the RunspaceConfiguration object so the runspace has the proper type files loaded.

```PowerShell
$Runspace = [runspacefactory]::CreateRunspace()
$TypeFile = "C:\Temp\TypeFile.ps1xml"

#Use the necessary flags to locate the property
$Flags = 'nonpublic','static','instance'
$_RunspaceConfig = $Runspace.GetType().GetProperty('RunspaceConfiguration',$Flags)

#Pull the RunspaceConfiguration property
$RunspaceConfig = $_RunspaceConfig.GetValue($Runspace,$Null)

#Locate the constructor of the TypeConfigurationEntry object 
$ctor = $RunspaceConfig.Types[0].GetType().GetConstructor([string])

#Invoke the constructor with the type file to build the object
$TypeConfigEntry = $ctor.Invoke($TypeFile)

#Load the type files into the RunspaceConfiguration
$RunspaceConfig.Types.Append($TypeConfigEntry)

```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSEdition                      Core
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.9-107
PSRemotingProtocolVersion      2.3
CLRVersion
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0

```

**Comment by lzybkr** [comment]
There are 2 runspace initialization apis, `RunspaceConfiguration` from V1, and `InitialSessionState` from V2 onwards.

We had plans to remove `RunspaceConfiguration` from PowerShell Core, partly because we don't need to support snap-ins, but also trying to reduce the api surface.

We made the apis internal in PowerShell Core for the time being, e.g.

https://github.com/PowerShell/PowerShell/blob/c1faf1e6e10fc1ce45e84ef6f49ae7136c67a111/src/System.Management.Automation/minishell/api/RunspaceConfiguration.cs#L107

But longer term, we'd hoped we could remove them completely.

Is `InitialSessionState` and the corresponding apis like `SessionStateTypeEntry ` and `SessionStateFormatEntry` a viable replacement for you?

Note that one reason we want to remove them - maintaining the 2 code paths is extra work, e.g. the work I did to speed up PowerShell startup was primarily done for `InitialSessionState`, so runspaces using `RunspaceConfiguration` won't see the same improvements.

**Comment by proxb** [comment]
Nice! If those are the V2+ apis to replace `RunspaceConfiguration` then that will definitely be a viable solution for me as I want to ensure that my module keeps up with what the latest apis are. I'll work on testing `InitialSessionState`, `SessionStateTypeEntry` and `SessionStateFormatEntry` and integrating them into my [module ](https://github.com/proxb/PoshRSJob) so it is up to date. Appreciate the heads up on the updated apis!

**Comment by proxb** [comment]
Using the public apis worked like a champ! Thanks for the heads up on these.
