### ISSUE TITLE
`winget` hangs prompting for approval of source agreement terms in 7.4.0-preview.6

### ISSUE THREAD

**Issue by sba923** [PowerShell/PowerShell#20452]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When `winget` needs to prompt for approval of the source license terms, it hangs when run under 7.4.0-preview.6.

This works fine under 7.3.7.

````
PS> winget list smartm
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No:
````

Entering 'Y' at this point does nothing: `winget` cannot read keyboard input.

### Expected behavior

```console
PS> winget list smartm
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: Y
```

### Actual behavior

```console
PS> winget list smartm
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No:
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.6
PSEdition                      Core
GitCommitId                    7.4.0-preview.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sba923** [comment]
This is issue is _precisely_ triggered by `winget source reset --force` which is part of my working around an issue with the `winget` CDN (see: https://x.com/SBarizien/status/1710661893948321892?s=20).

I'll open an issue in the `winget` repo and see where we get from there.

**Comment by sba923** [comment]
Created https://github.com/microsoft/winget-cli/issues/3742

@StevenBucher98  are you using Windows Terminal? I'm using Preview 1.19.2309.25002 FWIW.

**Comment by StevenBucher98** [comment]
@sba923 I used WT (1.17) and their canary build (1.20) and still works fine for me. Same thing with conhost.

**Comment by sba923** [comment]
Well... I can't repro anymore...
