### ISSUE TITLE
Remove-Service does not have a help page url in version 7.3.7

### ISSUE THREAD

**Issue by JimMoyle** [PowerShell/PowerShell#20468]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If I run `help remove-service -online` I get an error:

<img width="856" alt="image" src="https://github.com/PowerShell/PowerShell/assets/20442811/05f84bb6-3523-4da3-a52c-21aace386a0b">

### Expected behavior

```console
It should open the page https://learn.microsoft.com/powershell/module/microsoft.powershell.management/remove-service?view=powershell-7.3
```

### Actual behavior

```console
The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.PSInvalidOperationException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : The online version of this Help topic cannot be displayed because the Internet address (URI) of
the Help topic is not specified in the command code or in the help file for the command.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    TargetSite  :
        Name          : WriteObjectsOrShowOnlineHelp
        DeclaringType : Microsoft.PowerShell.Commands.GetHelpCommand
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message     : The online version of this Help topic cannot be displayed because the Internet address (URI) of the
Help topic is not specified in the command code or in the help file for the command.
    Source      : System.Management.Automation
    HResult     : -2146233079
    StackTrace  :
   at Microsoft.PowerShell.Commands.GetHelpCommand.WriteObjectsOrShowOnlineHelp(HelpInfo helpInfo, Boolean
showFullHelp)
   at Microsoft.PowerShell.Commands.GetHelpCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand
InvocationInfo        :
    MyCommand        : Get-Help
    ScriptLineNumber : 64
    OffsetInLine     : 13
    HistoryId        : 1
    Line             : $help = Get-Help @PSBoundParameters

    PositionMessage  : At line:64 char:13
                       +     $help = Get-Help @PSBoundParameters
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-Help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 64
                        at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS C:\Users\jimoyle> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="859" alt="image" src="https://github.com/PowerShell/PowerShell/assets/20442811/49870602-9499-4fb3-8d25-d4898b585209">

**Comment by jhoneill** [comment]
I still have 7.3.7 and the Help / get-help -online  and both work and (get-command ..).HelpUri returns the 7.2 URI.
Online shouldn't need the local help to be updated - but possibly if there is a local help file without the URI that could break things.  Remove-Service is part of PS 7 so it shouldn't be picking up a PowerShell 5 help file unless something very odd has happened

**Comment by JimMoyle** [comment]
Just retested with a clean Win11 install in Azure from the marketplace and PowerShell install from the store. Remover-Service is the only command in the Microsoft.PowerShell.management module.

I've added the ARM template I downloaded after creating the machine so you can see the VM details

<img width="1076" alt="image" src="https://github.com/PowerShell/PowerShell/assets/20442811/1770d318-0a7e-4300-81dd-a2d06818215a">
[template.zip](https://github.com/PowerShell/PowerShell/files/12869880/template.zip)

**Comment by JimMoyle** [comment]
Update-Help works in this scenario, but not on my local machine.  It looks like remove-service is the only command in the module where the helpuri isn't there by default.

<img width="1012" alt="image" src="https://github.com/PowerShell/PowerShell/assets/20442811/140b6343-b5df-45ad-9168-762057a5259b">

**Comment by kilasuit** [comment]
Interestingly it is set in the source code for that cmdlet so somewhere it's been removed as I get this on my machine too and from some of my zip installs too

 https://github.com/PowerShell/PowerShell/blob/ea01a28490204f79eeb22566b2a1fd6d428fe243/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L1416

**Comment by kilasuit** [comment]
Prior comment was wrong as it is missing & should be an easy enough fix. 

https://github.com/PowerShell/PowerShell/blob/ea01a28490204f79eeb22566b2a1fd6d428fe243/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs#L2349-L2354

**Comment by sdwheeler** [comment]
If you run `Update-Help` you should get a **HelpUri**. But one should be added to the code for completeness.
