### ISSUE TITLE
Install on git bash?

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#20465]
### Summary of the new feature / enhancement

As a user, I want to install PowerShell Core for Linux on git bash so that I can run and test code using Linux pwsh without having to install wsl, Ubuntu, etc.

Yes, I know that PowerShell Core for Windows will run under git bash. I would like to run PowerShell Core for Linux to ensure that the PowerShell code is written correctly to run multi-platform without requiring change. Is that possible?

**Comment by RokeJulianLockhart** [comment]
Isn't `git`'s Windows `bash` compilation merely that? It shouldn't be a virtualized Linux instance where installation is necessarily possible, to my knowledge.

**Comment by kilasuit** [comment]
I'm 99% this isn't possible as it's not actually a linux environment that git bash is running but a recompiled version for windows but assigning for maintainers to have a review to be sure

**Comment by Liturgist** [comment]
Using git bash, the following will produce a file with UNIX \x0A line endings. That makes me think that there is more UNIX in it than Windows.
```
echo sadf >junk.txt
echo qwer >>junk.txt
$ od -Ax -tcx1 junk.txt
000000   a   s   d   f  \n   q   w   e   r  \n
        61  73  64  66  0a  71  77  65  72  0a
00000a
```

**Comment by RokeJulianLockhart** [comment]
@Liturgist, I expect a `tree ..` would make this more evident.

**Comment by kilasuit** [comment]
So according to this [SO thread](https://stackoverflow.com/questions/32712133/package-management-in-git-for-windows-git-bash) this potentially could be possible

**Comment by Liturgist** [comment]
@kilasuit, from the SO thread I got the impression that it is more impossible or not worth it than it was possible.

If so, what are the alternatives, Docker image of some Linux, WSL, Cygwin, VMWare image, ...? What gives the most bang for the buck/effort?

**Comment by SeeminglyScience** [comment]
WSL is pretty low effort and works well to test most things.

**Comment by Liturgist** [comment]
@SeeminglyScience, there has not been a definitive response from the maintainers that @kilasuit said he would assign. Please restore the `Needs-Triage` tag and remove the `Resolution-Answered` tag.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/20465#issuecomment-1760509718

@SeeminglyScience, https://github.com/PowerShell/PowerShell/issues/20465#issuecomment-1758616291

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience, there has not been a definitive response from the maintainers that @kilasuit said he would assign. Please restore the `Needs-Triage` tag and remove the `Resolution-Answered` tag.

Sorry for not being clear, I'm one of the maintainers. Git bash is just a port of bash to Windows. You can already run PowerShell on Windows, so there isn't really anything for us to do there.

> Using git bash, the following will produce a file with UNIX \x0A line endings. That makes me think that there is more UNIX in it than Windows.

Redirection is a shell feature, so that's really just the bash port making that decision. A shell can do unixy things without really emulating a whole OS.
