### ISSUE TITLE
$psStyle.FormatHyperlink should passthru in build environments

### ISSUE THREAD

**Issue by StartAutomating** [PowerShell/PowerShell#20472]
### Summary of the new feature / enhancement

As the author of many formatting files, I want to make hyperlinked formatters.

Unfortunately, within certain environments, like GitHub Workflows, hyperlinks will not render.

Rather than show nothing, $psStyle.FormatHyperlink should ideally be intelligent enough to pass thru under certain conditions.

### Proposed technical implementation details (optional)

As loathe as I am to introduce anything like strong coupling, I see the easiest path between two points here to be:

* Make a list of environment variables that do hint hyperlink formatting is not present
* If any of these are present, $psStyle.FormatHyperlink should return the text (without the hyperlink)

To start off that list:

* `$env:GITHUB_WORKSPACE` indicates you are within a GitHub workflow.

**Comment by 237dmitry** [comment]
Could you show some example? It's not entirely clear what you are proposing.

`psStyle.FormatHyperlink()` is a method where you format a hyperlink and get the desired result.

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/31c23f9d-6ff0-4406-9b9f-39bd386169ef)

**Comment by StartAutomating** [comment]
@237dmitry if you run that method within a GitHub workflow, you'll get

"The is a [LITERAL BLANK] hyperlink"

The syntax sugar works, it just does not gracefully degrade in contexts that do not support it.

Make sense?
