### ISSUE TITLE
getRequestStream (System.Net.HttpWebRequest): Method invocation failed

### ISSUE THREAD

**Issue by HeinoLengfelder** [PowerShell/PowerShell#2047]
Steps to reproduce
------------------
Running a script, which works fine on Windows, causes a RuntimeException on Mac when executing the method getRequestStream (System.Net.HttpWebRequest).
```
...
$reqst = $req.getRequestStream()
```

Actual behavior
---------------
The unexpected error message:
```
Method invocation failed because [System.Net.HttpWebRequest] does not contain a method named 
'getRequestStream'.
At line:1 char:1
+ $reqst = $req.getRequestStream()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

Environment data
----------------

```
PSVersion                      6.0.0-alpha                                                         
PSEdition                      Core                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                             
BuildVersion                   3.0.0.0                                                             
GitCommitId                    v6.0.0-alpha.9                                                      
CLRVersion                                                                                         
WSManStackVersion              3.0                                                                 
PSRemotingProtocolVersion      2.3                                                                 
SerializationVersion           1.1.0.1

```

**Comment by ffeldhaus** [comment]
getRequestStream is not implemented in .NET Core. Check the documentation of [System.Net.WebRequest](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.webrequest#System_Net_WebRequest). Try `GetRequestStreamAsync()` instead.

Here's a full working example

    $request=[System.Net.HttpWebRequest]::Create("https://www.google.com")
    $request.GetRequestStreamAsync()

What are you trying to achive by using the .NET method instead of `Invoke-RestMethod` or `Invoke-WebRequest`?

**Comment by rkeithhill** [comment]
So does PowerShell need the equivalent of C#'s `await` keyword to work with more predominantly async APIs in .NET Core?

**Comment by HeinoLengfelder** [comment]
Thanks for the link, ffeldhaus.
I am not using `Invoke-WebRequest`, because I am sending a SOAP request inside HTTP. And as far as I know it is not possible to do this with `Invoke-WebRequest`.
I am trying your suggestion, but now I have problems with the rest of my the code. I have to work on it.

**Comment by HeinoLengfelder** [comment]
Thanks for the link, ffeldhaus.
I am not using `Invoke-WebRequest`, because I am sending a SOAP request inside HTTP. And as far as I know it is not possible to do this with `Invoke-WebRequest`.
I am trying your suggestion, but now I have problems with the rest of my the code. I have to work on it.
