### ISSUE TITLE
Mismatched Certificate and File Hash on pwsh.exe

### ISSUE THREAD

**Issue by adamdriscoll** [PowerShell/PowerShell#20481]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm pretty certain I have had some sort of virus affect my machine, but I want to call attention to this to make sure that I'm understanding this properly and have a second set of eyes look at this. 

My experience is documented here: https://serverfault.com/questions/1145755/powershell-failure-to-load-built-in-modules-due-to-software-restrictions

My findings so far: 

I have 3 executables (that I am aware of) on my machine that are signed by a revoked Microsoft certificate. 

They include:

- pwsh.exe (7.3.8)
- pwsh.exe (7.4.0-preview.6)
- devenv.exe (Enterprise 2022)

Running `Get-AuthenticodeSignature` against any of them returns the same thumbprint (6E78B3...) and does not match the thumbprints of the code signing certs on another machine running PS 7.3.7 and DevEnv 2022 Enterprise. 
 
```
PS C:\Users\adamr> Get-AuthenticodeSignature "C:\Program Files\PowerShell\7\pwsh.exe" | fl *


SignerCertificate      : [Subject]
                           CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           330000034D4E91A61A28B0788F00000000034D

                         [Not Before]
                           3/16/2023 1:43:28 PM

                         [Not After]
                           3/14/2024 1:43:28 PM

                         [Thumbprint]
                           6E78B3DCE2998F6C2457C3E54DA90A01034916AE

TimeStamperCertificate : [Subject]
                           CN=Microsoft Time-Stamp Service, OU=nShield TSS ESN:8D00-05E0-D947, OU=Microsoft America
                         Operations, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Issuer]
                           CN=Microsoft Time-Stamp PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                         [Serial Number]
                           33000001CD55072AE7CAC1991D0001000001CD

                         [Not Before]
                           5/25/2023 2:12:05 PM

                         [Not After]
                           2/1/2024 1:12:05 PM

                         [Thumbprint]
                           68A9F7A6D8A2B3B916632126227C6A2554E77204

Status                 : NotTrusted
StatusMessage          : File C:\Program Files\PowerShell\7\pwsh.exe is signed but the signer is not trusted on this
                         system.
Path                   : C:\Program Files\PowerShell\7\pwsh.exe
SignatureType          : Authenticode
IsOSBinary             : False
```

Uploading the suspicious pwsh.exe to Virus Total does not indicate any known infections. This PS version was upgraded via Windows Update and originally installed via the MSI. This morning, I did an uninstall and reinstall of PS 7.3.8 with the same result. 

https://www.virustotal.com/gui/file/7802fcb62e20269e14c671d23511b1600e1a952eddcc7282dd87d1d3a0339539

It also states that the pwsh.exe is successfully signed by Microsoft. 

![image](https://github.com/PowerShell/PowerShell/assets/1256531/0ed6849e-e797-453c-912d-c2130fe91485)

I also uploaded pwsh.exe 7.3.8 that I downloaded directly from GitHub right now and extracted from the ZIP. The hash is different and has a different Virus Total profile. I notice that at the top, it states: File distributed by Microsoft while the other pwsh.exe does not. 

https://www.virustotal.com/gui/file/768fc34505e6a90a2e3097d61520bd9404c39a33ab9b4fd2efb5d00acfd98931

You'll also notice the signing key is different. 

![image](https://github.com/PowerShell/PowerShell/assets/1256531/06593ae9-84eb-46b0-83d1-2414639060c9)

So I realize this may not be a PowerShell bug per se but I wanted to raise attention to the PS team and PS users because I am not getting any notifications from Defender and, as shown above, Virus Total does not detect anything. 

With that in mind, I am unable to run many commands in PS 7.3.8. For example: 

```powershell
Get-AuthenticodeSignature "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" | Format-List
Get-AuthenticodeSignature: The 'Get-AuthenticodeSignature' command was found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded due to the following error: [The following error occurred while loading the extended type data file:
, C:\program files\powershell\7\Modules\Microsoft.PowerShell.Security\Security.types.ps1xml: The file was skipped because of the following validation exception: File C:\program files\powershell\7\Modules\Microsoft.PowerShell.Security\Security.types.ps1xml cannot be loaded because its operation is blocked by software restriction policies, such as those created by using Group Policy..
]
For more information, run 'Import-Module Microsoft.PowerShell.Security'.
```

The certificate is, in fact, in the Disallow List on my machine. 

![image](https://github.com/PowerShell/PowerShell/assets/1256531/546ac02d-6cc3-4400-af6d-32a050b455e9)

I do have an AMSI notification in defender. This happened after I began having this problem but it was me trying to see if I could work around AMSI to see if that was the issue. 

![image](https://github.com/PowerShell/PowerShell/assets/1256531/ea621658-6916-4622-9890-0d3e33117039)

I have no issues with Windows PowerShell. 

I am likely going to wipe the machine and start over but wanted to check with the team and community if I should collect anything before doing so. 

### Expected behavior

```console
- PowerShell 7.3.8 can run commands
- Suspicious certificates are not on my machine
- PowerShell Extension for VS Code loads
```

### Actual behavior

```console
- PowerShell 7.3.8 loads but cannot run anything in Microsoft.PowerShell.Security nor connect to Named Pipes
- Suspicious certificate is installed in the Disallow List
- PowerShell Extension for VS Code never loads (named pipe connection hangs)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by jborean93** [comment]
> Running Get-AuthenticodeSignature against any of them returns the same thumbprint (6E78B3...) and does not match the thumbprints of the code signing certs on another machine running PS 7.3.7 and DevEnv 2022 Enterprise.

I've got PowerShell 7.3.8 that has been installed by Windows Update and I can see that the certificate which signed the executable was with the thumbprint `6E78B3DCE2998F6C2457C3E54DA90A01034916AE` and the SHA256 hash of the exe is `7802FCB62E20269E14C671D23511B1600E1A952EDDCC7282DD87D1D3A0339539`.

This matches up with the `pwsh.exe` located in the 7.3.8-x64.zip in the pwsh releases page so I don't see any issues there.

> I also uploaded pwsh.exe 7.3.8 that I downloaded directly from GitHub right now and extracted from the ZIP

The exe you've downloaded indicates it's for the 7.3.7 release based on the FileVersion and signing date. The hash for 7.3.7 also aligns with the virus total hash.

```powershell
PS C:\Users\jborean> Get-FileHash -Path C:\Users\jborean\Downloads\PowerShell-7.3.7-win-x64\pwsh.exe                    
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          768FC34505E6A90A2E3097D61520BD9404C39A33AB9B4FD2EFB5D00ACFD98931       C:\Users\jborean\Downloads\Powe…
```

The signing keys do have a different thumbprint but they do seem to have the same subject and expiry times.

```powershell
# 7.3.7
Certificate   : [Subject]
                  CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                [Issuer]
                  CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                [Serial Number]
                  330000034EB53C7AC1846FEB2B00000000034E

                [Not Before]
                  17/03/2023 4:43:29 AM

                [Not After]
                  15/03/2024 4:43:29 AM

                [Thumbprint]
                  72105B6D5F370B62FD5C82F1512F7AD7DEE5F2C0

# 7.3.8
Certificate   : [Subject]
                  CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                [Issuer]
                  CN=Microsoft Code Signing PCA 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

                [Serial Number]
                  330000034D4E91A61A28B0788F00000000034D

                [Not Before]
                  17/03/2023 4:43:28 AM

                [Not After]
                  15/03/2024 4:43:28 AM

                [Thumbprint]
                  6E78B3DCE2998F6C2457C3E54DA90A01034916AE
```

As the thumbprint is essentially an MD5 hash of the certificate data that means something has changed. When analyzing the raw X509 data I can see a few differences

* The serial numbers are different
* The public key is different
* The subject key idenfier is different
* The SANs are different
  * 7.3.7 - `DirName:/OU=Microsoft Corporation/serialNumber=230012\+500516`
  * 7.3.8 - `DirName:/OU=Microsoft Ireland Operations Limited/serialNumber=230012\+500517`

Everything else like the issuer, Authority Key Identifier, expiry, subject, algorithms are all the same. I don't know why there are 2 different certs but I assume MS has a complex signing process which is the cause of this.
Based on this information I wouldn't have any cause for alarm, they are both signed by the same issuer and the subject still indicates it's the same entity.

As for the errors, it seems like some process has added it to the revoked list causing Windows to invalidate it. Even using `certutil -f -urlfetch -verify C:\path\to\cert.cer` works for both the 7.3.7 and 7.3.8 certs.
I'm unsure why AMSI picked it up as a threat but the hash and signatures in my installed copy as well as the copy from the pwsh release page match up with your results.
