### ISSUE TITLE
Invoke-Webrequest triggers IE ESC Warnings

### ISSUE THREAD

**Issue by Itzrukutsk** [PowerShell/PowerShell#2048]
## Steps to reproduce

Run Invoke-Webrequest -uri somewebsite that isn't in the trusted sites / local intranet zone on a windows server where Internet Explorer ESC is enabled.
## Expected behavior

The webrequest completes successfully or fails.
## Actual behavior

An IE ESC popup halts execution of the script.

``` powershell
> $PSVersionTable
PSVersion                      5.0.10586.117                                                                                                                                        
PSCompatibleVersions {1.0, 2.0, 3.0, 5.0...}                                                                                                                                        
BuildVersion                   10.0.10586.117                                                                                                                                      
CLRVersion                     4.0.30319.34014                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                          
SerializationVersion           1.1.0.1      
<!-- provide the output of $PSVersionTable -->
```

**Comment by Tadas** [comment]
As a workaround you might want to look into `-UseBasicParsing` parameter, I think that way PowerShell doesn't invoke IE. You will lose DOM parsing, which sometimes is a problem.

**Comment by Itzrukutsk** [comment]
Can confirm that it is a working workaround, but the parsing is really nice to have.

**Comment by 1RedOne** [comment]
There's a workaround, using Add-Type to ignore IE Errors.  However this doesn't work w/ Linux.
```

add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
```

[Source for this workaround](http://stackoverflow.com/questions/11696944/powershell-v3-invoke-webrequest-https-error)

I'd like to see this addressed as a Switch param, -IgnoreSslWarnings would be an obvious and discoverable name for such a switch.

**Comment by Itzrukutsk** [comment]
This isn't a certificate related issue.

Invoke-Webrequest seem to use some part of Internet Explorer for parsing the html on the webpage. This subsequently triggers Internet Explorer Enhanced Security configuration to pop up with multiple dialogs stating that both powershell and the requested website isn't in the trusted sites. It's reproducible on any Windows Server 2012 setup where IE ESC is enabled. 

Screenshot of the offending dialog
[http://i.imgur.com/GFNIa5j.png](url)

Some possible solutions that i can think of, with little to no knowledge about the code:
- Don't use IE to parse the html
- Find a way that circumvents IE ESC (Probably not a good idea due to security reasons)
- Disable IE ESC while the command is running (Probably not a good idea either).

**Comment by adamdriscoll** [comment]
Might be a breaking change but it could utilize the HtmlAgilityPack. I think that would work on .NET Core as well as not using IE for parsing. Not sure what the team's take on third-party libraries is.

https://www.nuget.org/packages/HtmlAgilityPack

**Comment by GeeLaw** [comment]
This is expected since when `-UseBasicParsing:$false` is used, PS uses `HTMLFILE` object to parse the resulting content -- even scripts in the page will run. Moreover, on Windows Server without Internet Explorer, if you do not set `-UseBasicParsing`, you get an error because it cannot parse the content.

Since scripts can run, you might also get offended if the page `alert`s, the only way to reduce these things is to `-UseNasicParsing`.

**Comment by Itzrukutsk** [comment]
Some javascript content won't be run. I've noticed that with some sites that implement AngularJS stuff.

**Comment by GeeLaw** [comment]
@ltzrukutsk no. Only inline scripts can run. Basically what happens is:

1. Create a HTMLFILE object;
2. Write the content into it.

The HTMLFILE object has no idea what the URL of the page is, therefore it cannot load scripts via `src` attribute. Similarly, inline codes that rely on it will surely break in the object.

**Comment by Itzrukutsk** [comment]
@GeeLaw That explains a lot, now i know why. Thanks. I've already started using PantomJS for those purposes.

**Comment by 1RedOne** [comment]
@Geelaw, are you certain about that?  Even when we run Invoke-WebRequest
with -UseBasicParsing we get the same error.

**Comment by markekraus** [comment]
@SteveL-MSFT Digging through some of the older issues and I have found quite a few that are not related to PowerShell Core, but instead are related to Windows PowerShell. How should we handle these? link to uservoice and close?

**Comment by SteveL-MSFT** [comment]
@markekraus yes, for Windows PowerShell if there's a corresponding issue on Uservoice, I think we should link it, and resolve as external.  Thanks!

**Comment by markekraus** [comment]
@Itzrukutsk As this issue pertains to Windows PowerShell 5.1 and older, this repository is now only for PowerShell Core, and PowerShell Core no linger has any reliabce on Internet Explorer, can you please open a uservoice for this issue?

https://windowsserver.uservoice.com/forums/301869-powershell
