### ISSUE TITLE
Add a `$PSAssignedParameters` automatic variable

### ISSUE THREAD

**Issue by DevOpsJeremy** [PowerShell/PowerShell#20484]
### Summary of the new feature / enhancement

There is currently a [`$PSBoundParameters`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables#psboundparameters) automatic variable which includes any parameters/values passed to the command. But this variable doesn't include parameters which have default values. There are times when users want any _assigned_ parameter key/values passed to another function--including any default values if the user didn't pass a value to that parameter. Basically any parameter variables which hold a value, whether that value was provided by the user or a default value.

I'd like to propose a `$PSAssignedParameters` automatic variable which includes _any_ parameters with assigned values, whether they be _bound_ parameters passed by the user, or parameters not passed by the user, but with default values.

#### Current functionality:

```powershell
PS > function Get-BoundParameters {
    param (
        $Param1 = "This is param1",
        $Param2,
        $Param3
    )
    [PSCustomObject] $PSBoundParameters
}
PS > Get-BoundParameters -Param2 "This is param2"

Param2
------
This is param2
```

Currently, only `$Param2` is returned, whereas the desired result (for the proposed `$PSAssignedParameters` variable) is that both `$Param1` and `$Param2` are returned, since both variables have assigned values--`$Param1` from the default value, and `$Param2` from the value passed by the user.

#### Desired functionality:

```powershell
PS > function Get-AssignedParameters {
    param (
        $Param1 = "This is param1",
        $Param2,
        $Param3
    )
    [PSCustomObject] $PSAssignedParameters
}
PS > Get-AssignedParameters -Param2 "This is param2"

Param1         Param2
------         ------
This is param1 This is param2
```
The `$PSAssignedParameters` automatic variable would hold any parameters which have _assigned_ values, whether that value was assigned by the user during runtime, or it's a default value. In this example, it returns `$Param1` with the default value and `$Param2` with the user-provided value, but doesn't return `$Param3` because it doesn't have a value at all.

### Possible challenges / considerations

- How to approach switch/boolean parameters. If the switch/boolean is unused, should it be included in the `$PSAssignedParameters` hash with a `$false` value, or should it not be included at all?
- How to handle dynamic parameters

**Comment by StartAutomating** [comment]
@DevOpsJeremy thanks for submitting this!

@SteveL-MSFT this is something @Jaykul and I have discussed many times as being desired and valuable.

It _greatly_ streamlines the process of splatting down to a command.

**Comment by mklement0** [comment]
Good point, but your issue is a duplicate of this issue (from 2017, alas):

* #3285

**Comment by 237dmitry** [comment]
And what could be practical use? If the parameter has a default value then this parameter is already assigned and can be used without checking whether it is present or not. What is the logic in this?

**Comment by DevOpsJeremy** [comment]
@237dmitry if a number of parameter key/values are being passed to another cmdlet via splatting, the default values need to be manually added to the follow-on cmdlet since they aren't included in `$PSDefaultParameters`. With `$PSAssignedParameters` (or a similar functionality), any parameters with values would be included without additional code needed for handling default values.

**Comment by DevOpsJeremy** [comment]
Closing due to duplicate of #3285
