### ISSUE TITLE
PowerShell updates via Windows Update gets stuck on `RegisterMicrosoftUpdate.ps1`

### ISSUE THREAD

**Issue by freya022** [PowerShell/PowerShell#20483]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Let Windows Update update PowerShell automatically

### Expected behavior

```console
Update completing
```

### Actual behavior

```console
The update is stuck at 0% and I can see the PowerShell setup processes hanging for 30+ minutes
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.22000 Microsoft Windows 11 Famille
```

### Windows update log

```markdown
[WindowsUpdate.log](https://github.com/PowerShell/PowerShell/files/12886793/WindowsUpdate.log)
```

**Comment by StevenBucher98** [comment]
Hmm this is weird, the latest MU release went out 10/10 and is 7.3.8, are you saying you are having trouble upgrading to 7.3.8 or you are on 7.3.8 and see the hung MU status?

**Comment by freya022** [comment]
I was on 7.3.7, and WU was installing some other updates alongside the 7.3.8 update, while the other updates worked, the PowerShell update hung up while running a script, so I had to kill the processes to let WU continue updating other stuff.

I did not do anything manually, everything happened in the background. Yesterday, WU tried to update to 7.3.8 again and succeeded, so at least its working at some point.

**Comment by StevenBucher98** [comment]
Sounds good, thanks for the information @freya022! Closing as resolved but feel free to reopen or submit a new issue if it happens again.

**Comment by TravisEz13** [comment]
The MSI logs might give us a clue as to what is going on.   MU already had a timeout for the process, but I don't know what it is.  To find the MSI logs, run:

``` 
Get-ChildItem $env:Windir\temp\powershell*.log
```

The time will be the only real clue as to which log had the hang.

**Comment by vince-hardwick** [comment]
I've had the same issue - last entry in PowerShell_7.3.8.0-x64_20231016224326_000_PowerShell_7.3.8_win_x64.msi in the %windir%\temp folder:

MSI (s) (90:88) [22:43:59:887]: Executing op: CustomActionSchedule(Action=EnableMU,ActionType=3137,Source=BinaryData,Target=CAQuietExec,CustomActionData="C:\Program Files\PowerShell\7\pwsh.exe" -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\PowerShell\7\RegisterMicrosoftUpdate.ps1")

**Comment by TravisEz13** [comment]
Hmm, that code already has a timeout.  

https://github.com/PowerShell/PowerShell/blob/master/assets/MicrosoftUpdate/RegisterMicrosoftUpdate.ps1

We could pass the parameter to MSI when executing to skip this Custom Action:
* The behavior is not per version, so it doesn't need to be ported to the newer install.
* This assumes the update doesn't need to update the MU registration, but it seems unlikely.

**Comment by TravisEz13** [comment]
Hmm, that code already has a timeout.  

https://github.com/PowerShell/PowerShell/blob/master/assets/MicrosoftUpdate/RegisterMicrosoftUpdate.ps1

We could pass the parameter to MSI when executing to skip this Custom Action:
* The behavior is not per version, so it doesn't need to be ported to the newer install.
* This assumes the update doesn't need to update the MU registration, but it seems unlikely.

It might be easier to record that we have ran this in the MSI and have the MSI skip the action during subsequent runs.  I know this is conceptually possible, but I'd need to research how to make it work.

**Comment by freya022** [comment]
I once again got the stuck install, same as before, WU doing the update by itself, I saw it after 3 hours

I tried to run the script manually by opening PS (which did successfully get updated to 7.3.9 anyway) and running the script, which tell me the script isn't trusted, so I assume the installer is stuck waiting for an input too
![image](https://github.com/PowerShell/PowerShell/assets/41875020/39fa8b9c-d1fd-4808-8832-d164685b1198)

These are my execution policies:
![image](https://github.com/PowerShell/PowerShell/assets/41875020/ec2733c9-0ce6-42dc-b04f-7336811dbc95)

Even the script for this command was not trusted either, even though I never had that issue before
