### ISSUE TITLE
Slice array with negative indexes's get the unlogic result's

### ISSUE THREAD

**Issue by LutAle** [PowerShell/PowerShell#20497]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm build grab docker cli string output with slicing waste header and processing remain string as need.
I is assumed that index -1 point  last element in array, that is convenience.
But with reverse index i get items in reverse order, with garbage string header  the it need  drop.
Assumed that Array[0..Count] and slice operator [1..-1] produce sequence item's in direct odrder's [1], [2], [3], ... [Count] , but it  in real case has output that slice with reverce item order       [1], ...  [0], [Count] 
This operation rotate item sequence in buckward dirrection  

### Expected behavior

```console
PS:\user>docker ps
CONTAINER ID   IMAGE              COMMAND     CREATED        STATUS        PORTS     NAMES
230d25385033   python:3.12-slim   "bash"      32 hours ago   Up 32 hours             pedantic_herschel
3f4b28c315cd   neovim             "sh"        37 hours ago   Up 37 hours             xenodochial_murdock
8b88e3fa3e4a   alpine             "/bin/sh"   47 hours ago   Up 47 hours             zen_meninsky

PS:\user>(docker ps)[1..-1]
230d25385033   python:3.12-slim   "bash"      32 hours ago   Up 32 hours             pedantic_herschel
3f4b28c315cd   neovim             "sh"        37 hours ago   Up 37 hours             xenodochial_murdock
8b88e3fa3e4a   alpine             "/bin/sh"   47 hours ago   Up 47 hours             zen_meninsky

For buil command like: (docker ps)[1..-1]  |  % {docker stop $_.Split(' ')[0]}
I get:
PS:\user>(docker ps)[1..-1] | % {$_.Split(' ')[0]}
230d25385033
CONTAINER
8b88e3fa3e4a
```

### Actual behavior

```console
PS:\user>(docker ps)[1..-1]
230d25385033   python:3.12-slim   "bash"      33 hours ago   Up 33 hours             pedantic_herschel
CONTAINER ID   IMAGE              COMMAND     CREATED        STATUS        PORTS     NAMES
8b88e3fa3e4a   alpine             "/bin/sh"   2 days ago     Up 2 days               zen_meninsky
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.6
PSEdition                      Core
GitCommitId                    7.4.0-preview.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/25406539/0ad21da8-f140-449d-a70d-131d05cb3952)
![image](https://github.com/PowerShell/PowerShell/assets/25406539/1bb71b2b-0777-489a-96de-ae3c69cb22a1)

**Comment by mklement0** [comment]
While it is understandable to expect `1..-1` inside `[...]` to refer to the range of elements from the _second_ (`1`) _through to the last_ (`-1`), this is - by design - _not_ how it works.

`..` is the [range operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#range-operator-), which exists independently of index expressions (`[...]`), and, if used in the latter, has no knowledge of the array / collection being addressed: `1..-1` _invariably_ results in the following array of indices: `1, 0, -1`; e.g.:

```powershell 
PS> (1..10)[1..-1]  # Gets the second (1), the first (0), and the last (-1) element.
2
1
10
```

See the following proposal for introducing a syntax that does what you're looking for:

* #7940

**Comment by 237dmitry** [comment]
I always wondered why this was the case, and it has always been like this. Then I got used to it, the main thing is to know this behavior.

Workaround:

```powershell
($a = 1..10)[1..$a.Count]
```

**Comment by mklement0** [comment]
Indeed, @237dmitry, though in the case at hand it would be: `($a = 1..10)[1..($a.Count-2)]`  in order to get `2`, `3`, ... `9`

**Comment by 237dmitry** [comment]
> though in the case at hand it would be

Yes, for `[1..-2]`

For `[1..-1]` the error does not occur if you specify the last index that is obviously larger than the actual one.
```
(1..10)[1..100]   # more iterations but the same result
(1..10)[1..1e6]   # very slow
```

**Comment by mklement0** [comment]
Good point, I confused the `-2` and `-1` use case.
It may not  often arise in practice, but note that with `Set-StrictMode -Version 3` or higher in effect, `($a = 1..10)[1..$a.Count]` breaks.

**Comment by 237dmitry** [comment]
> but note that with Set-StrictMode -Version 3

I did not know it. Now I will, although I don’t use such restrictions at all (and I don’t understand why a home user needs them).
