### ISSUE TITLE
Ctrl+V do not work on ssh password

### ISSUE THREAD

**Issue by devyodamaster** [PowerShell/PowerShell#20498]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Search the existing issues.
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

ssh usename@host
when prompt for password?
press ctrl+v
enter

### Expected behavior

```console
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-84-generic x86_64)
```

### Actual behavior

```console
Permission denied, please try again.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Your actual behavior indicates the password may be invalid, is PowerShell blocking pasting in this scenario? Can you provide more details about what PowerShell may be doing to prevent pasting?

**Comment by devyodamaster** [comment]
Do you really think I did not test if password is correct?

**Comment by StevenBucher98** [comment]
The error message you provided is a common ssh error and does not indicate it could be PowerShell related. Is PowerShell preventing the pasting from happening? Does this happen with any other shells? We need more detail in order to be able to help with your issue.

**Comment by devyodamaster** [comment]
> This sounds like an issue with ssh, if you are using the Win32-OpenSSH client you can submit an issue to their repo, https://github.com/PowerShell/Win32-OpenSSH/issues.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/db743cf2d923ac7d0c3f8ef95f2df34029e2006033430d3581d7df7254980f67/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f353963303766383031666433626161326232373965636264663363646630366466396235636536626364646261616537316334396437323333393639663935372f506f7765725368656c6c2f57696e33322d4f70656e535348"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Issues · PowerShell/Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH)**Win32 port of OpenSSH. Contribute to PowerShell/Win32-OpenSSH development by creating an account on GitHub.

So could you explain why right mouse click pasting password correct and ctrl+V not please?
