### ISSUE TITLE
Add `-Property` switch to `Foreach-Object`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#20491]
### Summary of the new feature / enhancement

> *What happens in `PSObject`, stays in `PSObject`...*

It appears to me that some effort has been taken to hide the intrinsic members from a novice user as these properties do not show up with a plain `Get-Member` command but only when explicitly executed with the `-Force` switch:

```PowerShell
[PSCustomObject]{ a = 1; b =2 } | Get-Member PSObject -Force
```

Yet, to be able to iterate through the (node)properties, it is required to be aware of these intrinsic members to do something general as iterating through the property names and - values, to e.g. [convert a PSCustomObject into a hashtable](https://learn.microsoft.com/powershell/scripting/learn/deep-dives/everything-about-pscustomobject#convert-pscustomobject-into-a-hashtable).

### Proposed technical implementation details (optional)

Wishful thinking:

```PowerShell
$hashtable = @{}
$myObject | Foreach-Object -Property { $hashtable[$_.Name] = $_.Value }
```

**Comment by mklement0** [comment]
I think you meant to say `ForEach-Object` in the title, not `Invoke-Command`.

While I agree that an easier way to reflect on an object's properties one by one is called for - and also a hashtable's entries, to avoid the awkward `.GetEnumerator()` call - it probably calls for a _dedicated cmdlet_, named, say `ForEach-Property`.

This would avoid confusion with the core mandate of `ForEach-Object`, which is to operate on _multiple objects_, one by one _as a whole_.

`ForEach-Property` could then act on the enumeration of `.psobject.Properties` for `[pscustomobject]`s (and non-dictionaries in general), and the enumeration of `.GetEnumerator()` for dictionaries, in both cases making `$_` contain an object that has has `.Name` and `.Value` properties.

  * Caveat: 
     * In the case of a _hashtable_'s entries, this works because `.Name` is an _alias property_ of `.Key` defined for `[System.Collections.DictionaryEntry]` instances.
     * Currently, no such alias property is defined for the `[System.Collections.Generic.KeyValuePair[T1, T2]` instances returned by `[System.Collections.Generic.IDictionary[T1, T2]]` instances.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  We don't believe adding a `-Property` type parameter to `ForEach-Object` is the right approach.  Instead, we agree that @mklement0's proposal would be a better and more general solution.  However, we don't believe this cmdlet needs to be part of PS7 at this time and would suggest publishing it as a module to PowerShellGallery.
