### ISSUE TITLE
Get-PSCallstack -First/-Skip

### ISSUE THREAD

**Issue by StartAutomating** [PowerShell/PowerShell#20493]
### Summary of the new feature / enhancement

In the majority of cases where I want to peek into the callstack, I only need to peek up one or two frames.

One good example of this would be finding the `[CommandAst]` of the current invocation, where one needs to look up exactly one frame.

Another good example is supporting Get-Command -Syntax for smart aliases, which also needs to look up exactly one frame.

Given that the stack frames can be expensive to enumerate, it seems logical that we allow basic pagination on Get-PSCallstack

### Proposed technical implementation details (optional)

Add a -First and -Skip parameter to Get-PSCallstack, which limit the number of items returned.

**Comment by SteveL-MSFT** [comment]
Is it better to have these built into this cmdlet vs using `Select-Object`?  Do we want to set a precedent that different cmdlets would implement what `Select-Object` already provides?  If typing less is the concern, would it be better to have `first` and `skip` functions that call `Select-Object`?

**Comment by StartAutomating** [comment]
@SteveL-MSFT a few notes here (in no particular order):

* Given the way that Get-PSCallstack enumerates, I don't believe Select-Object would short circuit the expense of callstack enumeration.
* Select-Object has known NoLanguage/ConstrainedLanguage security concerns (may be less of a thing for the debugger, but would be just as pertinent of feedback for similar proposed changes in Get-Event)
* Having some centralized logic / automatic handling of this scenario might be nice (just to avoid the duplication of code)
* CmdletBinding has SupportsPaging (unfortunately, it does not appear that compiled cmdlets honor it)


While not _all_ cmdlets would benefit from -First/-Skip, I'd suggest a large number of them would benefit from it being part of syntax.

That stated, the only way I can see to "square this circle" would be making SupportsPaging work automagically for compiled cmdlets.

**Comment by ThomasNieto** [comment]
> CmdletBinding has SupportsPaging (unfortunately, it does not appear that compiled cmdlets honor it)

What do you mean by compiled cmdlets don't honor that attribute? `Import-CliXml` is the only core cmdlet with that attribute set to `true`, `-First` and `-Skip` work as expected.

> That stated, the only way I can see to "square this circle" would be making SupportsPaging work automagically for compiled cmdlets.

My understanding those parameters are just support to facilitate a common parameter interface as the main benefit is for the cmdlets to limit calls to the underlying system to reduce execution time. If it was automatically implemented it wouldn't have any performance benefits over just calling `Select-Object` as the objects would still have to be retrieved.

**Comment by StartAutomating** [comment]
> > CmdletBinding has SupportsPaging (unfortunately, it does not appear that compiled cmdlets honor it)
> 
> What do you mean by compiled cmdlets don't honor that attribute? `Import-CliXml` is the only core cmdlet with that attribute set to `true`, `-First` and `-Skip` work as expected.


I mean that it did not populate .BoundParameters as expected.  Took a quick look at Import-Clixml and see how it works in there.  Will update the PR.

Thanks for the pointer!

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  We agreed that cmdlets should only implement their own paging support if there is a significant perf improvement instead of relying on `Select-Object` which provides a more consistent experience to users.  The current docs https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute?view=powershell-7.3#supportspaging on that attribute explicitly indicates that this is intended for large datasets which a call stack would not be.  We also agreed that Import-CliXml is not necessarily a good cmdlet to use as a model for other cmdlets.

**Comment by StartAutomating** [comment]
@SteveL-MSFT this is a fine resolution for the Get-PSCallstack issue.  Closing accordingly.

Get-Event has a similar series of fixes, and also includes a `-Descending` flag.  If the WG feels the same about paging in Get-Event, it should still keep in mind the benefit of ordering.
