### ISSUE TITLE
GroupBy parameter for Format-* cmdlets does not work as expected

### ISSUE THREAD

**Issue by loxia01** [PowerShell/PowerShell#20502]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using the `GroupBy` parameter for `Format-* ` cmdlets like this:

`Get-Service | Format-Table -Property Name -GroupBy StartupType`

This is just an example. This issue is not exclusive for `Get-Service` output.

### Expected behavior

```console
Expected behavior would be something like this with output grouped into just four tables, one for each value of StartupType:


   StartupType: Automatic

Status   Name               DisplayName
------   ----               -----------
...      ...                ...

   StartupType: Manual

Status   Name               DisplayName
------   ----               -----------
...      ...                ...

   StartupType: Disabled

Status   Name               DisplayName
------   ----               -----------
...      ...                ...

   StartupType: AutomaticDelayedStart

Status   Name               DisplayName
------   ----               -----------
...      ...                ...
```

To produce expected behavior I used the cmdlet `Group-Object` which works as expected:
```
Get-Service | Group-Object StartupType | ForEach-Object {
    "`n   StartupType: $($_.Name)"
    $_.Group | Format-Table
}
```

### Actual behavior

Actual behavior is that output is grouped into numerous (more than 50) tables based on the four values of StartupType, but with no discernible pattern why service names are split in so many groups.

### Error details

N/A

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ThomasNieto** [comment]
`Format-Table` requires input objects to already be sorted by the desired property.

```powershell
Get-Service | Sort-Object -Property StartupType | Format-Table -GroupBy StartupType
```

**Comment by loxia01** [comment]
Okay, thanks for the info. I should have read the parameter description more carefully.
I close this issue.
