### ISSUE TITLE
New Approved Verb - Login

### ISSUE THREAD

**Issue by simone-cw** [PowerShell/PowerShell#20513]
### Summary of the new feature / enhancement

PowerShell should have the verb `Login` for functions initiating an authentication process.
The closest verb at the moment is probably the `Enter`, however commands using that verb tend to move the current session in another scope, such as entering a remote PowerShell session.

In addition to this, Microsoft already makes use of the unapproved `Login` verb in a couple of Az PowerShell Modules.
```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Login-AzAccount                                    2.12.1     Az.Accounts
Alias           Login-AzAsAccount                                  1.1.4      Az.AnalysisServices
Alias           Login-AzureAsAccount                               1.1.4      Az.AnalysisServices
```

**Comment by mklement0** [comment]
I'm not weighing in on whether introducing a new verb is called for, but let me provide some context:

* The `Login-*` command names you're showing are _aliases_, and aliases aren't expected to conform to PowerShell's verb-noun naming convention.

* From what I can tell, these aliases  refer to `Connect-*` cmdlets, and `Connect` (and `Disconnect`) _is_ an approved verb.

That said, the fact that the Az module authors felt the need to provide aliases not to _shorten_ command names, as is typical, but to _substitute a different verb_ (that isn't approved in a non-alias command) suggests that they are concerned about the discoverability of `Connect` in the context of logging in.
Curiously, while the documentation, e.g. for [`Connect-AzAccount`](https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount), uses the _term_ login, it  doesn't mention the alias.

From what I understand, these cmdlets create _global state_ that subsequent commands from the same module then operate in the context of.

As for the login pattern where you obtain a _token_ of sorts (a session object) that you must then pass as _as an argument_ to subsequent calls: The precedent set by PowerShell itself for that is to use the `New` "verb" with the word `Session` in the noun part, namely `New-PSSession`.

**Comment by kilasuit** [comment]
@mklement0 is correct in the analysis above

For additional context 
Personally I don't think this is needed & to give context `Login` was first used by the Azure Modules, then they changed the verb to `Add` (with an alias back to `Login`) & then to `Connect` with guidance from many of us in the PowerShell community & is only in the module still for back compat reasons - I'd actually quite like to see it removed but its unlikely to happen

**Comment by ThomasNieto** [comment]
Logged https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10593 to add `Login` as a synonym for `Connect`.
