### ISSUE TITLE
is ActiveDirectory powershell module supported on powershell container images?

### ISSUE THREAD

**Issue by RealCoder1980** [PowerShell/PowerShell#20518]
### Summary of the new feature / enhancement

is ActiveDirectory powershell module supported on powershell container images?

### Proposed technical implementation details (optional)

is ActiveDirectory powershell module supported on powershell container images?

**Comment by jhoneill** [comment]
You would need to ask that team in Microsoft. This repo only covers the development of the the core of PowerShell (6 and later).  Supported means they fix any issue which manifests itself - in this case in a container image but not Window PowerShell 5.1 without containers?  Maybe they do, maybe they don't 

Lots of stuff _works_ without being _supported._  People here may be able to tell if it works or needs special steps to make it work.

**Comment by StevenBucher98** [comment]
Please refer to https://learn.microsoft.com/en-us/powershell/windows/module-compatibility?view=windowsserver2022-ps for module compatibility. It looks like it is supported on the specified versions of Windows but it is very old.
