### ISSUE TITLE
Invoke-WebRequest using Get method doesn't allow content-body

### ISSUE THREAD

**Issue by thiezn** [PowerShell/PowerShell#2054]
Making a HTTP GET requests using either Invoke-WebRequest or Invoke-RestMethod with a content-body throws an exception. [HTTP RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.1) describes that a content-body is allowed even though the response of the webserver might be 

>    A payload within a GET request message has no defined semantics;
>    sending a payload body on a GET request might cause some existing
>    implementations to reject the request.

This is making it difficult to interface with various RESTful API's like InfoBlox and ElasticSearch that rely on JSON payloads for retrieving data.
## Steps to reproduce

$uri = 'http://www.microsoft.com'
$payload = @{Microsoft='loves linux'}
$result = Invoke-WebRequest -Uri $uri -Body ($payload | ConvertTo-Json) -ContentType 'application/json' -Method Get
## Expected behavior

HTTP OK
## Actual behavior

Invoke-WebRequest : Cannot send a content-body with this verb-type.

**Comment by adamdriscoll** [comment]
This is a limitation of the [.NET class](https://msdn.microsoft.com/en-us/library/d4cek6cc(v=vs.110).aspx) that Invoke-WebRequest is using. Not sure what the best way would be to work around it.

**Comment by rkeithhill** [comment]
File this bug on the [CoreFx repo](https://github.com/dotnet/corefx)?

**Comment by thiezn** [comment]
Thanks, I've raised the issue on the CoreFX repo:

 dotnet/corefx#11211
