### ISSUE TITLE
pwsh.exe shim from .NET tool install is not signed

### ISSUE THREAD

**Issue by mthalman** [PowerShell/PowerShell#20557]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`dotnet tool install --global PowerShell`

### Expected behavior

```console
`%USERPROFILE%\.dotnet\tools\pwsh.exe` should be a signed file

This is particularly needed for the .NET SDK container images which [install PowerShell as a global tool](https://github.com/dotnet/dotnet-docker/blob/6ba62d6825b9f45b3d665ab6cc930808a40d63c6/src/sdk/8.0/nanoserver-ltsc2022/amd64/Dockerfile#L39-L47).
```

### Actual behavior

```console
`%USERPROFILE%\.dotnet\tools\pwsh.exe` is unsigned
```

### Environment data

```powershell
PowerShell 7.3.8
```

**Comment by mthalman** [comment]
There is documentation for how this shim can be predelivered rather than generated at install time. This would allow PowerShell to deliver a signed version of it.

https://github.com/dotnet/sdk/blob/main/documentation/general/signing-global-tool-packages.md

**Comment by SteveL-MSFT** [comment]
cc @adityapatwardhan
