### ISSUE TITLE
PowerShell dependencies use non-portable RIDs which causes exceptions when using PowerShell.SDK in a .net 8 project

### ISSUE THREAD

**Issue by andy250** [PowerShell/PowerShell#20559]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to run some powershell from C# console app written in .net 8.

When building the project I get this warning:
```
1>C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-x64, win10-x86, win7-x64, win7-x86, win81-x64, win81-x86, win8-x64, win8-x86. Affected libraries: Microsoft.Management.Infrastructure.Runtime.Win. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

When executing this code: 
`var rs = System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace();`
 or this code:
`var ps = System.Management.Automation.PowerShell.Create();`

I get this error: 

```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code
Could not load file or assembly 'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
Stack trace
```
at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportPSSnapIn(PSSnapInInfo psSnapInInfo, PSSnapInException& warning)
   at System.Management.Automation.Runspaces.InitialSessionState.CreateDefault()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
```

I read this article: https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206

And I can fix the above issue by adding this XML to csproj of the executing project:
```
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
</ItemGroup>
```

I think the PowerShell.SDK should move to only portable RIDs, otherwise for .net 8 (and newer) all projects will require the `UseRidGraph` workaround to run PowerShell from C#. As explained in the article: _Note that the old RID graph is no longer updated and exists only as a backwards compatibility option._

### Expected behavior

```console
When running PowerShell within a .net 8 project I expect the runtime to resolve `Microsoft.Powershell.SDK` package dependencies correctly using only portable RIDs.
```

### Actual behavior

```console
As explained in https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206 .net 8 by default does not resolve dependencies which have only non-portable RIDs specified. I.e. one of PowerShell.SDK dependencies `Microsoft.Management.Infrastructure` has lots of RIDs specified, but all of them are OS-version specific (e.g. win10-x64), and none of them are portable (which would be e.g. win-x64).
```

### Environment data

```powershell
OS: win10 and win11
.NET Version: 8.0.100-rc.2.23502.2 x64
VS2022 17.8 preview 4

Locally I have installed PowerShell 7
My .net project has installed `Microsoft.PowerShell.SDK 7.3.8` from nuget.
```

**Comment by ALIENQuake** [comment]
@andy250 I've added `<UseRidGraph>true</UseRidGraph>` and  <RuntimeIdentifier>win7-x64</RuntimeIdentifier> into my csproj file but it didin't mitigate the issue. Any clue?

**Comment by andy250** [comment]
> @andy250 I've added `<UseRidGraph>true</UseRidGraph>` and win7-x64 into my csproj file but it didin't mitigate the issue. Any clue?

@ALIENQuake This is my csproj which works for me:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
...
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
  </ItemGroup>
....
</Project>
```

**Comment by BornToBeRoot** [comment]
Updating to `7.4.0-rc.1` resolved the issue for me.

```
<PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.0-rc.1" />
```

Seems like the ItemGroup is no longer required then.

**Comment by daxian-dbw** [comment]
The need to setting `UseRidGraph=true` is due to an intentional breaking change in .NET 8 -- Starting in .NET 8, the .NET SDK won't recognize version-specific RIDs by default, such as win7-x64, see https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/rid-graph for details.

We fixed all PowerShell SDK packages to not use specific RIDs in 7.4.0-rc.1. Now that 7.4.0 is out, can you simply use the v7.4 PowerShell sdks when targeting .NET 8.

**Comment by ALIENQuake** [comment]
And if you want trimming, include this one in csproj file:
```
    <Target Name="Microsoft-Management-Infrastructure-IsTrimmable-False" BeforeTargets="PrepareForILLink">
        <ItemGroup>
            <ManagedAssemblyToLink Condition="'%(Filename)' == 'Microsoft.Management.Infrastructure'">
                <IsTrimmable>false</IsTrimmable>
            </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
```
