### ISSUE TITLE
`Get-Command -List` doesn't consider implied executable filename extensions when a PowerShell-native command by a given name takes precedence

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20562]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Get-Command -List` is meant to list _all_ forms of a given command, in descending order of precedence.

* Without `-List`, and with `-List` if the effective form of the command happens to be an _external executable_, commands can be discovered even without their filename extension, e.g. `Get-Command findstr` to discover `findstr.exe`)

* However, if an external program with a given base name happens to be shadowed by a PowerShell command with higher precedence, it isn't discovered by `Get-Command -List`

```powershell
# On Windows
Get-Command findstr
'---'
function findstr { 'dummy' }
Get-Command  -List findstr
```

### Expected behavior

```console
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     findstr.exe                                        10.0.2262… C:\Windows\system32\findstr.exe
---
Function        findstr
Application     findstr.exe                                        10.0.2262… C:\Windows\system32\findstr.exe
```

### Actual behavior

```console
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     findstr.exe                                        10.0.2262… C:\Windows\system32\findstr.exe
---
Function        findstr
```

That is, the `-List` invocation no longer discovered `findstr.exe`, because a shadowing PowerShell command exists.

### Environment data

```powershell
PowerShell 7.4.0-preview.6 on Windows 11 22H2
```

**Comment by 237dmitry** [comment]
In 7.3.8
```
Get-Command -List findstr    # return only function
Get-Command -List findstr*   # return function and executable (in this order)
```

**Comment by MartinGC94** [comment]
There is no `-List` parameter. `-List` does get expanded to `-ListImported` though. Are you thinking about the `-All` parameter? If so, then it seems to work as expected:
![image](https://github.com/PowerShell/PowerShell/assets/42123497/d6ab9ea2-db4a-471f-a7c9-264967bb3b8f)

**Comment by mklement0** [comment]
Good point, @MartinGC94, I must have confused it with `Get-Module -List`.

So the bug isn't what I expected, but a different one - or at least an inconsistency.

Since the concept of _imported_ never applies to external programs, it doesn't ever make sense to include them - yet if no PowerShell command by that name exists, they are.

Before I re-title and modify the original post: Do you agree? Just want to make sure there's isn't something I'm missing.

**Comment by MartinGC94** [comment]
I am not sure. You are of course right that applications can never be imported so from that perspective they should never show up if `-ListImported` has been specified but was that really the intent behind that parameter? Probably not. The point of `-ListImported` is seemingly just to exclude PS modules that hasn't been imported yet.

**Comment by mklement0** [comment]
Thanks, @MartinGC94, you're right: I got stuck on the concept of `-All`, i.e. including _shadowed_ commands, but that isn't inherent to `-ListImported`. Closing this.
