### ISSUE TITLE
Distribution Support Request

### ISSUE THREAD

**Issue by toddglewis** [PowerShell/PowerShell#20561]
### Name of the Distribution

ubuntu

### Version of the Distribution

jammy

### Package Types

- [X] Deb
- [ ] RPM
- [ ] Tar.gz
- [ ] Snap - Stop! Please file your issue in [PowerShell-Snap](https://github.com/powershell/powershell-snap) instead.

### Processor Architecture

x86

### .NET Core Support

- [X] The version and architecture of the Distribution is [supported by .NET Core](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#linux).

### Distribution Requirements

- [X] The version of the Distribution is supported for at least one year.
- [X] The version of the Distribution is not an [interim release](https://ubuntu.com/about/release-cycle) or equivalent.

### Exemption Justification

There are no source packages provided for powershell, only binaries.  `apt source` does not work, and `https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/source/` is empty.  Please fix or let me know if you need help.  tlewis@brickabode.com

### Progress

- [ ] An issue has been filed to create a Docker image in [PowerShell-Docker](https://github.com/powershell/powershell-docker)

### For PowerShell Team **ONLY**

- [ ] Docker image created
- [ ] Docker image published
- [ ] Distribution tested
- [ ] Update `packages.microsoft.com` deployment
- [ ] [Lifecycle](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Support-Lifecycle.md) updated
- [ ] Documentation Updated

**Comment by kasini3000** [comment]
Would you like to take a look at the powershell installation script I maintain?
https://gitee.com/chuanjiao10/kasini3000_agent_linux

```
curl -L https://gitee.com/chuanjiao10/kasini3000_agent_linux/raw/master/ubuntu2204_install_powershell.bash | /bin/bash
```

Welcome to provide feedback

**Comment by rhubarb-geek-nz** [comment]
You are asking for x86 on Linux. Dotnet is not supported on Linux on the intel 32bit platform, only the x86_64/amd64.

The amd64 binary is listed in `https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/main/binary-amd64/Packages` as

```
Package: powershell
Version: 7.3.9-1.deb
Architecture: amd64
Section: shells
Priority: extra
Installed-Size: 172238
Maintainer: PowerShell Team <PowerShellTeam@hotmail.com>
Description: PowerShell is an automation and configuration management platform.
 It consists of a cross-platform command-line shell and associated scripting language.
Homepage: https://microsoft.com/powershell
Depends: libc6, libgcc1, libgssapi-krb5-2, libstdc++6, zlib1g, libicu72|libicu71|libicu70|libicu69|libicu68|libicu67|libicu66|libicu65|libicu63|libicu60|libicu57|libi
cu55|libicu52, libssl3|libssl1.1|libssl1.0.2|libssl1.0.0
Vendor: Microsoft Corporation
License: MIT License
SHA256: 8ec60ee3bd4721f5097f7faf55c1aabf984118821ed78baca70be3612516cc9b
Size: 69171666
Filename: pool/main/p/powershell/powershell_7.3.9-1.deb_amd64.deb
```

I don't think you will find a ubuntu 22.04 for x86 either.

**Comment by theJasonHelmick** [comment]
This request is not supported on .NET.
