### ISSUE TITLE
The font used for autocomplete has swapped to italics after updating to latest RC

### ISSUE THREAD

**Issue by XenoPanther** [PowerShell/PowerShell#20575]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Update from 7.4.0 Preview6 to 7.4.0 RC.1

### Expected behavior

```console
For Powershell's autocomplete to not automatically use italics
```

### Actual behavior

```console
Powershell uses italics
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-rc.1
PSEdition                      Core
GitCommitId                    7.4.0-rc.1
OS                             Microsoft Windows 10.0.25977
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/81916167/e8cae7ec-4a0e-4654-bca6-70a0e3c0f0a6)

**Comment by StevenBucher98** [comment]
This is due to 7.4rc shipping with the latest version of PSReadLine (2.3.4) which changes the default history predictions to `dim white italic` to help with readability for terminals without a pure black background. You chance the color back by running 
```
set-psreadlineoption -Colors @{ "InlinePrediction" = "`e[38;5;238m" }
```
