### ISSUE TITLE
Digit Separators

### ISSUE THREAD

**Issue by JohnLBevan** [PowerShell/PowerShell#20589]
### Summary of the new feature / enhancement

Similar to what we [now have in C#](https://github.com/dotnet/roslyn/issues/216), it would be great to introduce digit separators to PowerShell, so we can enter numbers in a more legible way; e.g.

```powershell
$myVar = 1_000_000
```

Today we can get away with converting a string as below; but this then makes our code culture dependent.

```powershell
$myVar = [int]'1,000,000'
```

This relates to #13590 in that both are to do with formatting numbers for legibility; only this request is for formatting the input/code, whilst #13590  is for formatting the output.

**Comment by mklement0** [comment]
I like the idea, but, unfortunately, it looks like this was previously decided against (in the context of introducing support for `[bigint]` and binary number literals):

* https://github.com/PowerShell/PowerShell/pull/7993#issuecomment-442651543

**Comment by JohnLBevan** [comment]
Ah, thanks for digging that out @mklement0 ; sorry I'd not spotted befor opening this request.  Closing as previously answered.
