### ISSUE TITLE
PWSH 7.4x: [System.Reflection.Assembly]::Load("System.Windows.Forms") breaks Invoke-RestMethod

### ISSUE THREAD

**Issue by UselessGuru** [PowerShell/PowerShell#20585]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Invoke-RestMethod is not working after loading windows forms:

```
[Void] [System.Reflection.Assembly]::Load("System.Windows.Forms")
$Form = New-Object System.Windows.Forms.Form
```
After these two commands `Invoke-RestMethod -Uri "www.google.com"` will freeze pwsh. 
I can reproduce the issue on 3 different Windows 11 clients

With older versions of PWSH (Up to latest 7.3.9) Invoke-RestMethod works flawlessly even AFTER window forms has been loaded.

### Expected behavior

```console
Invoke-RestMethod -Uri "www.google.com"
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="de-CH"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="lf9ivsda7InbvejPMxI-9A">(function(){var _g={kEI:'YNI6Zaq-A62C9u8P_LSxwAE',kEXPI:'0,1365468,206,4804,2316,383,246,5,1129120,1578490,16115,19398,9286,22430,1362,12311,17588,4998,17075....
```

### Actual behavior

```console
pwsh freezes - no response. Need to kill session
```

### Error details

```console
n/a (session is frozen)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-rc.1
PSEdition                      Core
GitCommitId                    7.4.0-rc.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by yiya0802** [comment]
Hi, cannot repro on PSVersion 7.3.8.

**Comment by UselessGuru** [comment]
> Hi, cannot repro on PSVersion 7.3.8

Thank you for your effort,
7.3.8 does not have the issue. It only happens with 7.4x
