### ISSUE TITLE
`Group-Object` displays dates using a `MM/dd/yyyy` format regardless of the set culture (PowerShell 7.4 Preview)

### ISSUE THREAD

**Issue by matteocoder** [PowerShell/PowerShell#20584]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. start PowerShell as admin;
2. `Set-Culture it-IT`
3. `Get-ChildItem | Group-Object -Property LastWriteTime`

### Expected behavior

```console
Count Name                Group
----- ----                -----
    1 2022-07-17 17:30:00 {...}
...
```

### Actual behavior

```console
Count Name                Group
----- ----                -----
    1 07/17/2022 17:30:00 {...}
...
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.6
PSEdition                      Core
GitCommitId                    7.4.0-preview.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/22897138/8d76e211-a20b-4aad-8138-07795116c626)

**Comment by 237dmitry** [comment]
As a workaround:

```
Get-ChildItem | Group-Object { $_.LastWriteTime.ToString() }
```

**Comment by jhoneill** [comment]
This does not happen in 7.3.8 - and it may be worth changing the title because it may be a regression in 7.4 preview. 


It's a common problem behaviour depending on how the date is converted. 
```
> $d = get-date

> "today is $d"
today is 10/26/2023 20:09:15
> "today is {0}"  -f $d
today is 26/10/2023 20:09:15
> $d -as [string]
26/10/2023 20:09:15
> [string]$d
10/26/2023 20:09:15
```

If there is a regression I'll put a small bet on someone changing the way the "group by" property is cast to a string.  (e.g. a cast replacing a call to `ToString()` )

**Comment by matteocoder** [comment]
Thank you for your replies. @237dmitry Thank you for the workaround, I'll use that for now. @jhoneill I'll update the title accordingly then.

**Comment by trackd** [comment]
yea i've also seen this problem, i left a comment on [pull#19018](https://github.com/PowerShell/PowerShell/pull/19018)

looking over the changes it's part of the rather large refactor [pull#18974](https://github.com/PowerShell/PowerShell/pull/18974)

the actual change [diff](https://github.com/CarloToso/PowerShell/commit/b85fe99f5aa3bed704da0669a5f44140854e7f75#diff-f756948572a883b69d843b9d5628468a230a6744c14b53dcbc013c1e0e4b1422L156)

```ps
# PS 7.3.8
PS 7.3> Use-Culture -Culture en-us -ScriptBlock { (Get-Date | Group-Object).Name }
10/20/2023 10:04:22 AM
PS 7.3> Use-Culture -Culture sv-se -ScriptBlock { (Get-Date | Group-Object).Name }
2023-10-20 10:04:14

# PS 7.4.0-preview.6
PS 7.4> Use-Culture -Culture en-us -ScriptBlock { (Get-Date | Group-Object).Name }
10/20/2023 09:57:52
PS 7.4> Use-Culture -Culture sv-se -ScriptBlock { (Get-Date | Group-Object).Name }
10/20/2023 09:57:39
```

**Comment by jhoneill** [comment]
> yea i've also seen this problem, i left a comment on [pull#19018](https://github.com/PowerShell/PowerShell/pull/19018)
> 

> 
> the actual change [diff](https://github.com/CarloToso/PowerShell/commit/b85fe99f5aa3bed704da0669a5f44140854e7f75#diff-f756948572a883b69d843b9d5628468a230a6744c14b53dcbc013c1e0e4b1422L156)
> 

Yes the changes there at line 156 and 164 will cause this (I think)
In the old version the `.ToString()` would use current culture and bypass the (erroneous) `Invariant culture`  - the replacement will display numbers wrongly if your culture doesn't use `.` as the decimal separator, and dates wrongly for every country except the US.
