### ISSUE TITLE
The output of sort-object is different on ps5 and ps7

### ISSUE THREAD

**Issue by H4de5-7** [PowerShell/PowerShell#20596]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I execute this code I get different answers, which makes me confused. It looks like the ps5 output is out of order.

@(1..9)|sort-object {1}

powershell 5's output:
7
6
9
8
5
2
1
4
3

powershell7's output:
1
2
3
4
5
6
7
8
9

### Expected behavior

```console
1
2
3
4
5
6
7
8
9
```

### Actual behavior

```console
7
6
9
8
5
2
1
4
3
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3-512-g66767aa54ee1659ea02f65f12b4af95c807af140
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
(a) This Repo won't process fixes to bugs in in PowerShell 5
(b) I Can't repro the this 
(c) `sort-object {script block}` will evaluate a the script block as a the sort property - normally  the script block contains` $_` but that you have is "sort by a constant", which doesn't guarantee output order = input order and which is what pwsh7 gives you e.g.  `@(1..9)|sort-object {1}`  isn't sorted. 
(d) There are some very subtle changes to sort order with culture changes between different versions of .NET used in different versions of PowerShell.

**Comment by iRon7** [comment]
@H4de5-7

> `@(1..9)|sort-object {1}`

Not sure what  you trying to do here as your [calculated property](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_calculated_properties) is a static value and therefore there isn't any way for the `Sort-Object` cmdlet to prioritize one object above (or below) the other. What does appear here, is that apparently the older 5.1 `Sort-Object` cmdlet does index the items (probably with a unordered hashtable), something similar to:

```PowerShell
$List = 1..9 | % { [PSCustomObject]@{ a = 1; b = $_ } }
```

#### Windows-PowerShell 5.1
```PowerShell
$List | Sort-Object 'a'

a b
- -
1 7
1 6
1 9
1 8
1 5
1 2
1 1
1 4
1 3
```

#### PowerShell (Core) 7:
```PowerShell
$List | Sort-Object 'a'

a b
- -
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
```
