### ISSUE TITLE
Syntax typo in russian README

### ISSUE THREAD

**Issue by NovaAbramson** [PowerShell/PowerShell#20592]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Typo of markdown in `doc/README-ru.md` makes the navigation button to English README fuse with the button of Chinese README

### Expected behavior

```console
[<a href="../README.md">English</a>]
```

### Actual behavior

```console
[<a href="../README.md">English]
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by perpetualsquid** [comment]
@NovaAbramson Hi, I'd like to fix this. Could you please point me to the file? I can't find it.

**Comment by SteveL-MSFT** [comment]
@sdwheeler looks like there's a problem with the Russian translated version

**Comment by sdwheeler** [comment]
@SteveL-MSFT @NovaAbramson What document did you find this in? The file `doc/READM-ru.md` does not exist in this repository or in the docs repository.

**Comment by NovaAbramson** [comment]
> @SteveL-MSFT @NovaAbramson What document did you find this in? The file `doc/READM-ru.md` does not exist in this repository or in the docs repository.

Super sorry, opened issue for the wrong repo. That's the [bat](https://github.com/sharkdp/bat/blob/master/doc/README-ru.md)'s one. Was super tired and confused tabs 😅
