### ISSUE TITLE
PowerShell-7.3.9-win-x64.msi file download is pointing to GUID file !!!

### ISSUE THREAD

**Issue by Hoezer** [PowerShell/PowerShell#20609]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Go to https://github.com/PowerShell/PowerShell/releases/tag/v7.3.9 or https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#installing-the-msi-package 
2. Download the PowerShell-7.3.9-win-x64.msi
3. Download will show a GUID as file name
4. The file is exact hash but name is a GUID!!!

### Expected behavior

```console
Have the correct file to download with corect name and sha256
```

### Actual behavior

```console
File 15d32a25-976b-4970-bdd5-020005281986 (no extention) hash looks ok 5F57DEC05692D97BC052FD0BE1FEEE36C265A9629E3491CC259A2EED4A31EE14
```

### Environment data

```powershell
Does no apply
```

**Comment by EricZimmerman** [comment]
docfile? hehe

![image](https://github.com/PowerShell/PowerShell/assets/4265254/fd9e0f12-b1d3-419a-b4b4-0b73216f830d)

**Comment by EricZimmerman** [comment]
this appears to be fixed.
