### ISSUE TITLE
MSI installers don't support `TAGETDIR` for overriding install directory

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShell#20602]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PowerShell MSI installers don't support `TARGETDIR` for overriding install directory. This does not comply with Microsoft documentation on MSI properties which says "The **TARGETDIR** property specifies the root destination directory for the installation.".

* https://learn.microsoft.com/en-us/windows/win32/msi/targetdir

Seems to be related to WiX, but from what I've read so far it should be possible to work around this.

* https://github.com/microsoft/winget-cli/issues/1857

### Expected behavior

```console
Install with TARGETDIR="<somepath>" should install to "<somepath>".
```

### Actual behavior

```console
Install with TARGETDIR="<somepath>" installs to "<defaultpath>".
```

### Environment data

```powershell
Windows 11 22621.2428
```

### Visuals

<img width="1168" alt="image" src="https://github.com/PowerShell/PowerShell/assets/6450056/612d8e4a-b205-44f2-b4f9-2096a2e0ef4f">

**Comment by SteveL-MSFT** [comment]
@heaths any opinion on this?

**Comment by heaths** [comment]
Most don't these days. Using `TARGETDIR` for the root is antiquated, and in practice causes a lot of problems especially when a product may have multiple root folders (not that this one does). Instead, most WiX-based products use `INSTALLFOLDER` by convention. So you can pass `INSTALLFOLDER=<path>` instead.

`-l` and `--location` should not assume `TARGETDIR`. I'd be surprised if many MSIs even do that anymore. Instead, a winget manifest should allow MSIs to set their root folder, if it doesn't already. /cc @denelon

**Comment by o-l-a-v** [comment]
@heaths 

`INSTALLFOLDER` does not behave as I expect. I tried:

`msiexec /package "PowerShell-7.4.0-rc.1-win-x64.msi" /quiet /norestart INSTALLFOLDER="%ProgramW6432%\PowerShell\7.4-preview" /l*v "log74.txt"`

It installed to:

`%ProgramW6432%\PowerShell\7.4-preview\7-preview`

By the logs it looks like a child directory is added (`VersionFolder`) to `InstallDir` and `InstallLocation`.

```
...
MSI (s) (60:E0) [11:57:53:622]: Executing op: RegAddValue(Name=InstallDir,Value=C:\Program Files\PowerShell\7.4-preview\7-preview\,)
MSI (s) (60:E0) [11:57:53:622]: Executing op: RegAddValue(Name=InstallLocation,Value=C:\Program Files\PowerShell\7.4-preview\7-preview\,)
...
```

Is this expected behavior?

**Comment by sdwheeler** [comment]
> Is this expected behavior?

Yes, this is expected. If you need to control the full name of the location where you want to install PowerShell, install from the ZIP package.

**Comment by o-l-a-v** [comment]
Instead of expecting the PowerShell MSI installer to act like most installers (ability to set install root folder, expose a MSI standard install parameter to do so) I should write my own install logic and use the ZIP, got it.

**Comment by sdwheeler** [comment]
@o-l-a-v I have updated the documentation.

- `INSTALLFOLDER` - This property controls the installation directory. The default is `$env:ProgramFiles\PowerShell\`. This is the location where the installer creates the versioned subfolder. You can't change the name of the versioned subfolder.
  - For current releases, the versioned subfolder is `7`
  - For preview releases, the versioned subfolder is `7-preview`

**Comment by o-l-a-v** [comment]
Awesome @sdwheeler.

**Comment by eugenesvk** [comment]
> You can't change the name of the versioned subfolder

Why can't users do the simplest thing of controlling the install dir?
