### ISSUE TITLE
New-AzKeyVaultRoleAssignment does not work without HsmName parameter

### ISSUE THREAD

**Issue by passionInfinite** [PowerShell/PowerShell#20605]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing issues with using `New-AzKeyVaultRoleAssignment` without `-HsmName` as we are not using HSM. I simply want to perform role assignment to the AKV using `New-AzKeyVaultRoleAssignment`. The role assignment works using the `New-AzRoleAssignment` command but this requires whole lot new module to be installed.

### Expected behavior

```console
New-AzKeyVaultRoleAssignment `                                                                      
   -ObjectId  $SPN_OBJECT_ID `                                                                                                             
   -RoleDefinitionName "Key Vault Administrator" `
   -Scope "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RG_NAME/providers/Microsoft.KeyVault/vaults/$AKVNAME"

Role assignment must have been added provided the credentials that I am using to create this role assignment has permission to assign the roles.
```

### Actual behavior

```console
New-AzKeyVaultRoleAssignment `                                                                      
   -ObjectId  $SPN_OBJECT_ID `                                                                                                             
   -RoleDefinitionName "Key Vault Administrator" `
   -Scope "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RG_NAME/providers/Microsoft.KeyVault/vaults/$AKVNAME"

It asks for `HsmName` seems like it is a required parameter for running the `New-AzKeyVaultRoleAssignment` command.
```

### Error details

```console
cmdlet New-AzKeyVaultRoleAssignment at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
HsmName:
New-AzKeyVaultRoleAssignment: Cannot bind argument to parameter 'HsmName' because it is an empty string.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
I believe https://github.com/Azure/azure-powershell would be a better place for issues regarding Az cmdlets.

**Comment by passionInfinite** [comment]
Thank you @StevenBucher98  for pointing out. I have created issue in the azure-powershell repo: https://github.com/Azure/azure-powershell/issues/23106 

Shall I close it over here then?

**Comment by StevenBucher98** [comment]
Our bot will close it since it has the resolution tag 😄
