### ISSUE TITLE
libmi.dylib is still x86_64 on m1 mac causing error when invoking get-windowsfeature cmdlet through remote ssh session

### ISSUE THREAD

**Issue by Nova-Logic** [PowerShell/PowerShell#20607]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

libmi.dylib that is going with PowerShell 7 distro is still x86_64 instead of arm64. that's causing problem when I'm trying to call get-windowsfeature cmdlet through remote ssh session

### Expected behavior

```console
arm64 binary and working get-windowsfeature cmdlet that is invoked through remote ssh session
```

### Actual behavior

```console
PS /Users/test> $session1 = New-PSSession -HostName hyperv-03 -UserName k8s  -SSHTransport
PS /Users/test> invoke-Command -Session $session1 -ScriptBlock {get-windowsfeature}
OperationStopped: Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
dlopen(/usr/local/microsoft/powershell/7/libmi.dylib, 0x0001): tried: '/usr/local/microsoft/powershell/7/libmi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/libmi.dylib' (no such file), '/usr/local/microsoft/powershell/7/libmi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
dlopen(libmi.dylib, 0x0001): tried: 'libmi.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibmi.dylib' (no such file), '/usr/lib/libmi.dylib' (no such file, not in dyld cache), 'libmi.dylib' (no such file), '/usr/local/lib/libmi.dylib' (no such file), '/usr/lib/libmi.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/microsoft/powershell/7/liblibmi.dylib, 0x0001): tried: '/usr/local/microsoft/powershell/7/liblibmi.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/liblibmi.dylib' (no such file), '/usr/local/microsoft/powershell/7/liblibmi.dylib' (no such file)
dlopen(liblibmi.dylib, 0x0001): tried: 'liblibmi.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibmi.dylib' (no such file), '/usr/lib/liblibmi.dylib' (no such file, not in dyld cache), 'liblibmi.dylib' (no such file), '/usr/local/lib/liblibmi.dylib' (no such file), '/usr/lib/liblibmi.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/microsoft/powershell/7/libmi, 0x0001): tried: '/usr/local/microsoft/powershell/7/libmi' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/libmi' (no such file), '/usr/local/microsoft/powershell/7/libmi' (no such file)
dlopen(libmi, 0x0001): tried: 'libmi' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibmi' (no such file), '/usr/lib/libmi' (no such file, not in dyld cache), 'libmi' (no such file), '/usr/local/lib/libmi' (no such file), '/usr/lib/libmi' (no such file, not in dyld cache)
dlopen(/usr/local/microsoft/powershell/7/liblibmi, 0x0001): tried: '/usr/local/microsoft/powershell/7/liblibmi' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/microsoft/powershell/7/liblibmi' (no such file), '/usr/local/microsoft/powershell/7/liblibmi' (no such file)
dlopen(liblibmi, 0x0001): tried: 'liblibmi' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibmi' (no such file), '/usr/lib/liblibmi' (no such file, not in dyld cache), 'liblibmi' (no such file), '/usr/local/lib/liblibmi' (no such file), '/usr/lib/liblibmi' (no such file, not in dyld cache)
PS /Users/test>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Darwin 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
libmi is no longer supported.  We suggest trying https://www.powershellgallery.com/packages/PSWSMan/2.3.1 instead.

**Comment by Nova-Logic** [comment]
> libmi is no longer supported. We suggest trying https://www.powershellgallery.com/packages/PSWSMan/2.3.1 instead.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/ca767ff8f0625dd18823c74a8a69da3d93d9df23f87b6703e040b55ba100e9f4/68747470733a2f2f706f7765727368656c6c67616c6c6572792e636f6d2f436f6e74656e742f496d616765732f4272616e64696e672f5061636b61676544656661756c7449636f6e2e706e67">**[PSWSMan 2.3.1](https://powershellgallery.com/packages/PSWSMan/)**Module to install and manage the forked WSMan client libraries for Linux and macOS.
> > See https://github.com/jborean93/omi for more details.

Thanks, but problem the problem is that somehow invoke-command cmdlets somehow tries to use it, ignoring the fact that $session is an ssh session:

Thanks, but problem the problem is that somehow invoke-command cmdlets somehow tries to use it, ignoring the fact that $session is ssh session, and it's happening with this specific cmdlet,other remote cmdlets would work as usual:
test@test-MacBook-Pro ~ % PS /Users/test> $session1 = New-PSSession -HostName hyperv-03 -UserName k8s  -SSHTransport
PS /Users/test> invoke-Command -Session $session1 -ScriptBlock {get-windowsfeature}
test@test-MacBook-Pro ~ %
test@test-MacBook-Pro ~ % pwsh
PowerShell 7.3.9
PS /Users/test> $session1 = New-PSSession -HostName hyperv-03.-UserName k8s  -SSHTransport
PS /Users/test> invoke-Command -Session $session1 -ScriptBlock {get-windowsfeature}
OperationStopped: Unable to load shared library 'libmi' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
dlopen(/usr/local/microsoft/powershell/7/libmi.dylib, 0x0001): tried: '/usr/local/microsoft/powershell/7/libmi.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
