### ISSUE TITLE
PowerShell insists with "needs to update" window even though I did not asked for it!!

### ISSUE THREAD

**Issue by gbr000** [PowerShell/PowerShell#20600]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Some dev here that got triggered here because I reported this few months ago, only came to question my grammar and language, (snowflakism).

But did not provided me with any valid answer. The proof of that, I would not be here. Because trust me I don't want to be here.

I just want PowerShell to stop asking me for "new updates".

Dev provided me an answer with a VARIABLE=DEACTIVATE.

But after PowerShell install itself it looks like the variable IT'S RESETED.

DEVS please fix the issue for once and for all!!

### Expected behavior

```console
No more "update screen" at the start.
```

### Actual behavior

```console
Typical:


PowerShell 7.3.8

   A new PowerShell stable release is available: v7.3.9
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.3.9
```
```


### Error details


### Environment data

```powershell
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by mklement0** [comment]
https://github.com/PowerShell/PowerShell/issues/20319#issuecomment-1728602587

**Comment by gbr000** [comment]
No answers were provided. The issue persists!!

I guess this it's not a community, it's intended for people who have power and want to have power over the others.
