### ISSUE TITLE
Powershell no longer in repo

### ISSUE THREAD

**Issue by knightian** [PowerShell/PowerShell#20610]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am following Microsoft's instructions to set up the repo in Ubuntu 22.04

https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.3

Once I install Microsoft's repo, it seems that Powershell is no longer included in the "Packages" file that the repo pushes.

It used to work, why has Microsoft stopped pushing powershell onto the repo?

BOOOOOOOOOO

### Expected behavior

```console
I would like to `sudo apt install powershell`
```

### Actual behavior

```console
It says the package does not exist, because it has disappeared from the repo.
```

### Environment data

```powershell
Ubuntu 22.04, both amd64 and aarch64(arm64)
```

**Comment by 237dmitry** [comment]
Seriously, I wouldn't trust a package manager, be it apt, dnf or pacman. Only manual installation guarantees full operation of pwsh.

This is my experience since pwsh began to be distributed as a snap package (6.+)

**Comment by knightian** [comment]
> Seriously, I wouldn't trust a package manager, be it apt, dnf or pacman. Only manual installation guarantees full operation of pwsh.
> 
> This is my experience since pwsh began to be distributed as a snap package (6.+)

Thanks, but I have an automated build flow that uses the repo to get powershell into a docker container, the repo is nice because it automatically detects the architecture amd64/aarch64 etc and I have not had any problems with the delivered powershell in this case, until all of a sudden powershell is no longer in the repo.

**Comment by 237dmitry** [comment]
>  but I have an automated build flow that uses the repo

This is out of my practice. I think you need to wait a little longer, maybe repos haven't updated yet. This sometimes happens after the next release. I hope this is not related to system dependencies.

**Comment by knightian** [comment]
> maybe repos haven't updated yet.

Yea but usually when the repos are not updated, it just means that an older version remains.  22.04 is long tooth (LTS) so I don't think it is because of platform changes.

**Comment by StevenBucher98** [comment]
We don't publish an ARM64 ubuntu 22.04 package so that is the reason you cannot find it for that architecture. 

@knightian To help us better debug do you mind running the following commands on your amd64 machine and give us the output:

- apt-get update
- apt search powershell
- uname -a

**Comment by knightian** [comment]
Ah right, I must have confused myself because I thought in the past I was doing it on arm. I guess I was not then if you've never published it for arm. I just did it in Ubuntu under WSL on my PC which is x64 and it worked so I guess it is working for amd64 as designed. Thanks for the info.

**Comment by knightian** [comment]
For arm now I am using the dotnet global installer, actually it suits me anyway because I'm using the dotnet/sdk:8-jammy docker image and so I can easily dotnet install -g powershell and it is installing the arm version for me so all good :)
