### ISSUE TITLE
sshd_config gets reset  when apple updates the OS.

### ISSUE THREAD

**Issue by speed2048** [PowerShell/PowerShell#20625]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I update sshd_config on a mac to add the powershell SubSystem. It works until apple updates the OS and over writes the changes. Have to go back and edit the file in to reenable the SubSystem.

This may be a documentation change to let people know that this happens or is there another way.

### Expected behavior

```console
Powershell SubSystem should not disappear when Apple updates the OS.
```

### Actual behavior

```console
PowerShell SubSytem disappears when Os gets updated.
```

### Environment data

```powershell
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Darwin 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-1000…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Seems like a known problem with macOS https://discussions.apple.com/thread/252554155 over the last 10 years.  It may make sense to have a general statement about OS upgrades may require putting back the subsystem.  cc @sdwheeler

**Comment by SteveL-MSFT** [comment]
Would be best to open a new issue here https://github.com/MicrosoftDocs/PowerShell-Docs/issues

**Comment by speed2048** [comment]
Thanks Steve,

I create a PR in the PowerShell-Docs.

**Comment by rhubarb-geek-nz** [comment]
I add an entry in an additional config file, eg

```
/etc/ssh/sshd_config.d/50-rhubarb-pi-psremote.conf
```
and have the content

```
Subsystem powershell /usr/local/bin/pwsh -sshs -nologo
```

This should survive an OS update
