### ISSUE TITLE
How Does an Update Honor the LTS Channel?

### ISSUE THREAD

**Issue by bmkaiser** [PowerShell/PowerShell#20629]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

According to [this article](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#upgrading-an-existing-installation), if a device has an LTS version of PowerShell installed, it won't be upgraded to a non-LTS version. However, if you run an MSI for a non-LTS version, it will upgrade.

> When upgrading, PowerShell won't upgrade from an LTS version to a non-LTS version. It only upgrades to the latest version of LTS, for example, from 7.2.3 to 7.2.16. To upgrade from an LTS release to a newer stable version or the next LTS, you need to install the new version with the MSI for that release.
> 
> When the installed version isn't an LTS version, PowerShell upgrades to the latest stable version.

How is this logic handled during installation? Is there a Registry key or some other setting that is queried that controls this? Why doesn't an MSI honor this when an upgrade can?

### Expected behavior

```console
If you install the latest version PowerShell with the MSI, it should not overwrite an LTS version.
```

### Actual behavior

```console
When installing with an MSI, it will upgrade you to the latest version.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.16
PSEdition                      Core
GitCommitId                    7.2.16
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.20348 Microsoft Windows Server 2022 Standard
```

### Windows update log

```markdown
N/A
```

**Comment by TravisEz13** [comment]
This is handled in Windows update.

Windows update knows what version you are on and will only offer you an LTS update.   So, when 7.4 comes out, 7.2 will start being offered 7.4 updates.  We decide when that happens, so, around 7.4.1.

cc @StevenBucher98
