### ISSUE TITLE
installing 7.3.9 msi is NOT updating 7.3.8

### ISSUE THREAD

**Issue by pleabargain** [PowerShell/PowerShell#20626]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I've downloaded the msi
PowerShell-7.3.9-win-x86.msi

I install it 
but 
PS is not updating
![image](https://github.com/PowerShell/PowerShell/assets/640846/3d0e3d72-16a4-4eeb-8847-2702f352a4f7)

### Expected behavior

```console
PS should update
```

### Actual behavior

```console
PS is not updating
```

### Error details

```console
no error
```

### Environment data

```powershell
PowerShell 7.3.8
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/640846/3a2ae280-47be-4554-aa1f-5ab1e5dae24a)

**Comment by 237dmitry** [comment]
How did you install `7.3.8`? Perhaps there are different install methods between 7.3.8 and 7.3.9
What is `$PSHome` and `$env:Path`:

```
$PSHome
$env:Path.Split(';')
```

**Comment by Buster-de** [comment]
I tried to reproduce. Our software deployment tool uses `msiexec /i "PowerShell-7.3.9-win-x64.msi" /qn /norestart ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1`

Result is two entries in Programs list:
```
PS C:\> $software = $null
$software += get-itemproperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\* -Name Publisher,DisplayName,DisplayVersion,UninstallString -ErrorAction SilentlyContinue | Sort-Object -Property Publisher,DisplayName | Select-Object -Property Publisher,DisplayName,DisplayVersion,UninstallString
$software += get-itemproperty HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* -Name Publisher,DisplayName,DisplayVersion,UninstallString -ErrorAction SilentlyContinue | Sort-Object -Property Publisher,DisplayName | Select-Object -Property Publisher,DisplayName,DisplayVersion,UninstallString
$software += get-itemproperty HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\* -Name Publisher,DisplayName,DisplayVersion,UninstallString -ErrorAction SilentlyContinue | Sort-Object -Property Publisher,DisplayName | Select-Object -Property Publisher,DisplayName,DisplayVersion,UninstallString
$software += get-itemproperty HKCU:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* -Name Publisher,DisplayName,DisplayVersion,UninstallString -ErrorAction SilentlyContinue | Sort-Object -Property Publisher,DisplayName | Select-Object -Property Publisher,DisplayName,DisplayVersion,UninstallString
$software | sort Publisher,DisplayName | ? DisplayName -like "*PowerShell*" | ft Publisher,DisplayName,DisplayVersion,UninstallString -AutoSize -Expand Both

Publisher             DisplayName            DisplayVersion UninstallString                                                                           
---------             -----------            -------------- ---------------                                                                           
Microsoft Corporation PowerShell 7.3.8.0-x64 7.3.8.0        "C:\ProgramData\Package Cache\{1897b6e9-b6f9-4529-b7a6-f3f6547b8131}\PowerShell-7.3.8-w...
Microsoft Corporation PowerShell 7-x64       7.3.9.0        MsiExec.exe /X{959CB28B-C5F3-4B66-9F8C-EC1F02E15115}         
```

But it seems it was an error in 7.3.8 package that created that 1st entry. I have another windows server that updated from 7.3.4 to 7.3.9 and it only shows the 2nd entry after update. On both servers (7.3.8 to 7.3.9 and 7.3.4 to 7.3.9) running WIN+R pwsh.exe opens 7.3.9.

**Comment by pleabargain** [comment]
> How did you install `7.3.8`? Perhaps there are different install methods between 7.3.8 and 7.3.9 What is `$PSHome` and `$env:Path`:
> 
> ```
> $PSHome
> $env:Path.Split(';')
> ```

![image](https://github.com/PowerShell/PowerShell/assets/640846/9dc22583-7793-43c7-a191-4a3a28734d64)

**Comment by pleabargain** [comment]
For giggles I tried to use the PowerShell-7.3.9-win-x86.msi
uninstall tool.

No joy. 
7.3.8 is still there.
Tried installing with PowerShell-7.3.9-win-x86.msi
No joy. 
7.3.8 is still there.

**Comment by 237dmitry** [comment]
> PowerShell-7.3.9-win-x86.msi

Remove and install PowerShell-7.3.9-win-x64.msi

**Comment by pleabargain** [comment]
> > PowerShell-7.3.9-win-x86.msi
> 
> Uninstall and install PowerShell-7.3.9-win-x64.msi

I TRIED to install using PowerShell-7.3.9-win-x64.msi UI
No joy.

**Comment by pleabargain** [comment]
Uninstalling I see that 7.3.9 is installed but the PS UI say something else!
![image](https://github.com/PowerShell/PowerShell/assets/640846/b6f88cac-f9b3-4c1c-b85a-87e11af291b0)
UI shows
![image](https://github.com/PowerShell/PowerShell/assets/640846/fd3b64c6-56f2-46f4-9eda-e80936ebf683)

**Comment by 237dmitry** [comment]
Strange behavior, I upgraded from 7.3.8 without problems. If I had this problem, I would uninstall everything and install 7.3.9.

**Comment by brokedarius** [comment]
I have a similar issue where 7.3.9 and 7.3.0 co-exist typing pwsh leads to the 7.3.0 version...

**Comment by SteveL-MSFT** [comment]
cc @TravisEz13

**Comment by pleabargain** [comment]
Closing. After restart PS showed correct version.
