### ISSUE TITLE
Unable to pass double hyphens in Start-Process ArgumentList for particular parameter

### ISSUE THREAD

**Issue by blueelvis** [PowerShell/PowerShell#20645]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have downloaded `s5cmd` from [here](https://github.com/peak/s5cmd). I am using PowerShell to loop through all the buckets and then get the size of it using this.

But, I am running into a problem where if I pass `--profile` in the argument list to the `Start-Process`, it only sends `-profile` to the main program. I have tried various combinations but it is only happening with this parameter `--profile` and rest all are working as expected.

For example -
```
# Following command works
Start-Process -RedirectStandardError "error.txt" -RedirectStandardOutput "temp.txt" -Wait -FilePath "C:\Users\user\Downloads\s5cmd_2.2.2_Windows-64bit\s5cmd.exe"  -ArgumentList "du --humanize --all-versions `"s3://bucket-dev/*`""

# Following command doesn't work
Start-Process -RedirectStandardError "error.txt" -RedirectStandardOutput "temp.txt" -Wait -FilePath "C:\Users\user\Downloads\s5cmd_2.2.2_Windows-64bit\s5cmd.exe"  -ArgumentList "du --profile devops --humanize --all-versions `"s3://bucket-dev/*`""
```

### Expected behavior

```console
The command executes and provides the size of the bucket.

11.9G bytes in 28857 objects: s3://bucket-dev/*
```

### Actual behavior

```console
Incorrect Usage: flag provided but not defined: -profile

Name:
  du - show object size usage

Usage:
  du [options] argument

Options:
  --group, -g         group sizes by storage class (default: false)
  --humanize, -H      human-readable output for object sizes (default: false)
  --exclude value     exclude objects with given pattern  (accepts multiple inputs)
  --all-versions      list all versions of object(s) (default: false)
  --version-id value  use the specified version of an object
  --help, -h          show help (default: false)
  
Examples:
  1. Show disk usage of all objects in a bucket
     > s5cmd du "s3://bucket/*"

  2. Show disk usage of all objects that match a wildcard, grouped by storage class
     > s5cmd du --group "s3://bucket/prefix/obj*.gz"

  3. Show disk usage of all objects in a bucket but exclude the ones with py extension or starts with main
     > s5cmd du --exclude "*.py" --exclude "main*" "s3://bucket/*"

  4. Show disk usage of all versions of an object in the bucket
     > s5cmd du --all-versions s3://bucket/object

  5. Show disk usage of all versions of all objects that starts with a prefix in the bucket
     > s5cmd du --all-versions "s3://bucket/prefix*"
    
  6. Show disk usage of all versions of all objects in the bucket
     > s5cmd du --all-versions "s3://bucket/*"
  
  7. Show disk usage of a specific version of an object in the bucket
     > s5cmd du --version-id VERSION_ID s3://bucket/object
```

### Environment data

```powershell
PS C:\dev\workspace> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
`Start-Process` is not to blame here: it copies your single-string `-ArgumentList` argument _verbatim_ to the process command line - whatever it contains.

It looks like the problem is command-line syntax error in `s5cmd.exe`: it complains about not recognizing your `--profile` argument (though confusingly refers to it as just `-profile`); presumably it must be placed _before_ the `du` sub-command.

On a general note:

* To synchronously execute console applications or batch files in the current console window, call them _directly_ (`c:\path\to\some.exe ...` or `& $exePath ...`). This also allows you to capture their output directly and to later query their exit code via `$LASTEXITCODE`. Do _not_ use `Start-Process` (or the `System.Diagnostics.Process` API it is based on) - see [this SO answer](https://stackoverflow.com/a/51334633/45375). [GitHub docs issue #6239](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6239) provides guidance on when use of `Start-Process` is and isn't appropriate.

To put it all together:

```powershell
& "C:\Users\user\Downloads\s5cmd_2.2.2_Windows-64bit\s5cmd.exe" --profile devops du --humanize --all-versions "s3://bucket-dev/*" >tempt.txt 2>error.txt
```

**Comment by blueelvis** [comment]
@mklement0 - I cannot believe that I did this... I just compared the command I executed on another shell and this one and you are right. As soon as put `du` before profile, it stops working there as well. And the command is indeed what you have mentioned.

My bad. Thank you for the information regarding Start-Process as well. I will keep it in mind.
