### ISSUE TITLE
Add Native Support for CRC32 Checksums

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [PowerShell/PowerShell#20646]
### Summary of the new feature / enhancement

As the title suggests, Powershell currently has the ability to calculate hashes/Checksums for various files, including advanced algorithms like SHA256.

Although the use of these hashes is commonly for file integrity verification and duplicate detection. and they are each more secure and reliable implementations, in some cases of daily use, Hashes such as MD5 are very long and difficult to read for the user compared to old standards such as CRC32. which can be used for common use purposes where integrity or 1:1 parity is not vital. if it is not used as a simple "unique" file identifier, for example.

**Currently several software mainly file compressors such as RAR and 7zip. They rely (by default) on CRC32 to list files graphically and calculate checksums.** so implementing native CRC32 calculation support in Powershell could be useful in this type of scenario where the user or their file source only have CRC32 as a checksums.
![image](https://github.com/PowerShell/PowerShell/assets/64709446/24c34839-02e1-4d16-aeb0-9674952cb5f8)

If you try by intuition to create a command to calculate CRC32 currently Powershell returns the following error.
`Cannot validate argument on parameter 'Algorithm'. The argument "CRC32" does not belong to the set
     | "SHA1,SHA256,SHA384,SHA512,MD5" specified by the ValidateSet attribute. Supply an argument that is in the set
     | and then try the command again.`

- Although PowerShell can currently calculate CRC32 sums, these depend on additional lines of code and/or conversion, or the import of DLL's/WinAPI dependencies for it, depending on the method used {Example on [StackOverflow:](https://stackoverflow.com/questions/76961129/how-to-calculate-the-crc32-of-a-string-in-powershell) against hashes like MD5 and SHA 256 that can be calculated directly with a line like: `Get-MD5 $file.FullName` so its implementation and simplification in a command similar to `Get-CRC32 $file.FullName` would be useful. [This takes weight if we consider that unless you have an application like 7zip. it is not possible to obtain hashes easily for the average user] requiring the execution of additional lines or the creation of a ps1 script for their calculation could be frustrating for beginner users and an additional burden or little justification for writing from scratch in case that you work with few files.
- 
![image](https://github.com/PowerShell/PowerShell/assets/64709446/6e955c0f-8ee2-4bec-bda2-6cc0ce0bf4bd)

**An important note is that if you try asking for a code for this purpose, some artificial intelligences (Among them those operated with GPT-3) also refer to trying a method with** `Get-CRC32 $file.FullName or Get-FileHash -Algorithm CRC32 -Path $file.FullName`   _Although if the AIs are made aware that the code returns an error because the CRC32 is not native or specified, they try to solve it by adding to the script a line of code similar to the solutions proposed on Stackoverflow, however, this is not entirely the case. perfect and in some cases it can return errors if the user does not manually review and correct the code. something that could again be difficult for inexperienced users. or assisted by these tools_
![image](https://github.com/PowerShell/PowerShell/assets/64709446/9a8cb38b-d2da-43b6-a00c-b2ae6f37ad01)

### Proposed technical implementation details (optional)

Checksums/Hash like MD5 and SHA-256 that can be calculated directly with a line like:` Get-MD5 $file.FullName....` so its implementation and simplification in a command similar to `Get-CRC32 $file.FullName.....`

**Comment by 237dmitry** [comment]
> Hashes such as MD5 are very long and difficult to read

Do you really read hashes and compare them manually?

```
(Get-FileHash path/to/file.ext).Hash -eq (Get-FileHash path/to/backup/file.ext).Hash
```

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
> > Hashes such as MD5 are very long and difficult to read
> 
> Do you really read hashes and compare them manually?
> 
> ```
> (Get-FileHash path/to/file.ext).Hash -eq (Get-FileHash path/to/backup/file.ext).Hash
> ```

Well, not literally all of them, much less if it's a SHA256, those things are huge... That's what the machine is for LOL _(but the code is a good contribution because I don't doubt if there is someone who does it like that)._
-although I have done it a couple of times.

But, back to CRC32. Yes, it is relatively small and if you only have a couple of loose files it can be done by hand... Here we return to the initial point, we cannot simply use a `(Get-FileHash ` compare foo.ABC with the checksum with crc32 in powershell. A script with extra steps is needed.
_If it is an entire disk, it is fine, but let's think about that point where the number or locations are too few to make an entire script from scratch, but many to do it by hand._

**Comment by 237dmitry** [comment]
I don't mind your feature request. I just didn't understand manual hash comparison.

**Comment by SteveL-MSFT** [comment]
I can't vouch for the quality of this module, but there's one on PSGallery that does what you need: https://www.powershellgallery.com/packages/CRC

Since CRC32 is not considered safe, I don't think we'd include it in PS7 as it would only encourage folks to use it.

**Comment by zypA13510** [comment]
> Since CRC32 is not considered safe, I don't think we'd include it in PS7 as it would only encourage folks to use it.

Base64 is also not considered _safe_. It is not safe to store password in plaintext, will you disallow using plaintext in any files? Can you fix people using the wrong tool for the job? Is it something Microsoft should decide?

As the OP explained, there are many use cases CRC32, none of them has anything to do with security. You can either address them or ignore them. Please just don't use _not considered safe_ as an excuse.
