### ISSUE TITLE
`Remove-Item`: adding `-Recurse` when `-Filter` is also used ignores the filter, targets *all* items.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20651]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is a serious problem that can result in unwanted deletion of both files and subdirectories.

Related:
* #16153
* #20637

```powershell
# Create and switch to a temp. dir.
Push-Location ($tmpDir = New-Item -Force -Type Directory (Join-Path temp: $PID))

# Create two sample files and a sample subdir.
'1.txt', '2.csv' | % { '' > $_ }
$null = New-Item -Force -Type Directory subdir

# Use -Filter *.txt alone 
Remove-Item * -Filter *.txt -WhatIf

'---'

# Use -Filter *.txt with -Recurse
Remove-Item * -Filter *.txt -Recurse -WhatIf

# Clean up
Pop-Location
$tmpDir | Remove-Item -Recurse 
```

### Expected behavior

```console
What if: Performing the operation "Remove File" on target "/var/folders/_t/8x3_gp2n6lb1mpg106v6vsvc0000gn/T/64474/1.txt".
---
What if: Performing the operation "Remove File" on target "/var/folders/_t/8x3_gp2n6lb1mpg106v6vsvc0000gn/T/64474/1.txt".
```

### Actual behavior

```console
What if: Performing the operation "Remove File" on target "/var/folders/_t/8x3_gp2n6lb1mpg106v6vsvc0000gn/T/64474/1.txt".
---
What if: Performing the operation "Remove Directory" on target "/var/folders/_t/8x3_gp2n6lb1mpg106v6vsvc0000gn/T/64474/subdir".
What if: Performing the operation "Remove File" on target "/var/folders/_t/8x3_gp2n6lb1mpg106v6vsvc0000gn/T/64474/1.txt".
What if: Performing the operation "Remove File" on target "/var/folders/_t/8x3_gp2n6lb1mpg106v6vsvc0000gn/T/64474/2.csv".
```

That is, *all items* were targeted when -Recurse was added

### Environment data

```powershell
PowerShell 7.4.0-rc.1
```

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this. While we agree that it is a bug and would ideally work more like `-Include` does, we are worried about making a change in this particularly sensitive area and are marking this as `wontfix`.
