### ISSUE TITLE
Invoke-Command not reconnecting from Linux to Windows

### ISSUE THREAD

**Issue by upload2raj** [PowerShell/PowerShell#20666]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Install latest version of powershell7 on Linux Environment.
Install latest version of powershell7 on a windows machine.
Execute any command from Linux machine to windows machine using Invoke-Command which will interrupt network temporarily. In my case Remove-VMSwitch . 

### Expected behavior

```console
Invoke-Command needs to try reconnecting
In Windows to Windows remoting it tries to reconnect for 4 minutes
```

### Actual behavior

```console
Invoke-Command is hung for ever
```

### Environment data

```powershell
Linux Client
------------
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Linux 4.18.0-513.el8.x86_64 #1 SMP Fri Aug 25 14:33:28 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Windows Server:
---------------
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Does this still occur in 7.4?

**Comment by upload2raj** [comment]
> Does this still occur in 7.4?


Yes even after upgrading Linux and windows powershell to 7.4.0 same issue

**Comment by Azziii** [comment]
Confirmed for 7.5-preview. The problem appeared after installing updates for Windows, before that everything worked.
