### ISSUE TITLE
Release Windows on Arm64 MSIs/packages

### ISSUE THREAD

**Issue by prayaas-a** [PowerShell/PowerShell#20672]
### Summary of the new feature / enhancement

Please consider building and releasing official Windows on Arm64 releases with easy to use MSIs for PowerShell. Windows on Arm64 has been supported for a while now and currently the only way to install it on Arm64 machines is through the zip package which is a manual process and not ideal. Windows Store releases are also not the way to go here (at least exclusively) because PowerShell has Store version-only bugs.

Due to the lack of MSI packages, many users may end up inadvertently with the x64 version which offers a subpar experience in performance. Further, scripts (like those that install other programs) running in the x64 environment may read system variables under emulation incorrectly and assume they're on an x64 system, further exacerbating the problem.

### Proposed technical implementation details (optional)

Package and release MSI installer packages for Windows on Arm64 for all future releases.

**Comment by rhubarb-geek-nz** [comment]
See https://github.com/PowerShell/PowerShell/issues/16992 which says it is not supported in WiX

The Microsoft OpenJDK project is happy to create MSI for ARM64, see https://github.com/microsoft/openjdk/issues/344

**Comment by rhubarb-geek-nz** [comment]
I have a github project which creates PowerShell MSI from ZIP for ARM64, see https://github.com/rhubarb-geek-nz/PowerShell/tree/main/win

**Comment by kilasuit** [comment]
There are some open PR's for this #20516 & #17160 which are both from @anamnavi, so this is in play right now 

@anamnavi can we get an update on the status of either of those PRs please

**Comment by anamnavi** [comment]
@kilasuit @prayaas-a yes we'd love to be publishing a msi for win-arm64...that change is almost done. I hope to have it completed and out by end of November/early December at latest.

**Comment by anamnavi** [comment]
> See #16992 which says it is not supported in WiX
> 
> The Microsoft OpenJDK project is happy to create MSI for ARM64, see [microsoft/openjdk#344](https://github.com/microsoft/openjdk/issues/344)

It's supported in wix 3.14 so we will be using that for arm scenarios.

**Comment by prayaas-a** [comment]
Thanks, @anamnavi 😊 Any updates?

**Comment by awee85** [comment]
Many Thanks, @anamnavi any updates about this? 

Wishing all a prosperous and happy New Year.

**Comment by anamnavi** [comment]
@prayaas-a @awee85 ah sorry for the late response and happy new year! The PR is just waiting on review from folks on the team who were out from the holidays, hoping to have this out soon within the next release or one right after. Once I get a review from this week I can post a more accurate estimate for when this change will be present. Thanks for all the patience :)

**Comment by anamnavi** [comment]
Closing this issue as the PR to fix it has been merged. The change should be present in the next release. But feel free to re-open if needed

**Comment by prayaas-a** [comment]
@anamnavi any updates? It looks like 7.4.2 was just released and there aren't any MSIs for Windows Arm64.

**Comment by rhubarb-geek-nz** [comment]
> 7.4.2 was just released and there aren't any MSIs for Windows Arm64

[ARM packages for PowerShell 7.4.2](https://github.com/rhubarb-geek-nz/PowerShell/releases/tag/7.4.2)

I maintain these because apart from the CBL Mariner 2.0 rpm, the official ARM packages are either absent or not fit for purpose.

**Comment by anamnavi** [comment]
@prayaas-a thanks for bringing this up! The team initially planned to release the arm msi for preview releases, but upon discussing we'll release the arm msi for stable releases as part of the Github release, but not yet as part of the winget release for stable. Winget release will start including it when 7.5 becomes stable.

**Comment by prayaas-a** [comment]
@anamnavi thanks. I see that 7.4.2 was released on GitHub after this change was merged but didn't include an MSI package for Windows Arm64. Microsoft has announced the [latest Surface Laptop and Surface Pro that are both Arm64 machines](https://blogs.windows.com/devices/2024/05/20/introducing-the-ultimate-copilot-pcs-the-all-new-surface-pro-and-surface-laptop/) and will be hitting shelves next month. A very large number of users may end up with a subpar experience if this isn't resolved soon. I'd suggest 7.4.2 should at least have a Windows Arm64 MSI package released on GitHub retroactively.

**Comment by StevenBucher98** [comment]
Thanks @prayaas-a for the heads up! We have put adding Windows ARM MSI packages for supported versions into our planning, hopefully we can get to it in the next few months so it will be included in our release soon.
