### ISSUE TITLE
Parser.ParseInput returns null after version 7.3.0 (with no errors)

### ISSUE THREAD

**Issue by YotamEN** [PowerShell/PowerShell#20677]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using input: 
string input = "& {$outputencoding = [console]::outputencoding =[system.text.encoding]::utf*;$scriptfilestream = [system.io.file]::open('c:\\someuser\\somefolder\\somefile.ps*', [system.io.filemode]::open, [system.io.fileaccess]::read, [system.io.fileshare]::read);$calculatedhash = get-filehash 'c:\\someuser\\somefolder\\somefile.ps*' -algorithm sha***;if (!($calculatedhash.hash -eq '*d*db*a**af**a****a*dfbd***e****c****c**a**f**f**********b*e***c')) { exit ***;}; . 'c:\\someuser\\somefolder\\somefile.ps*' }"

in Parser.ParseInput(input, out Token[] tokens, out ParseError[] errors)

The results are null for version  >= 7.3.0
The results are good (or at least not null and I get a full list of Tokens) for version in [7.2.0,  7.2.16]

### Expected behavior

```c#
string input = "& {$outputencoding = [console]::outputencoding =[system.text.encoding]::utf*;$scriptfilestream = [system.io.file]::open('c:\\someuser\\somefolder\\somefile.ps*', [system.io.filemode]::open, [system.io.fileaccess]::read, [system.io.fileshare]::read);$calculatedhash = get-filehash 'c:\\someuser\\somefolder\\somefile.ps*' -algorithm sha***;if (!($calculatedhash.hash -eq '*d*db*a**af**a****a*dfbd***e****c****c**a**f**f**********b*e***c')) { exit ***;}; . 'c:\\someuser\\somefolder\\somefile.ps*' }"

ScriptBlockAst ast = Parser.ParseInput(input, out Token[] tokens, out ParseError[] errors)
```

Results:
ast != null
Tokens.Length == 74
Errors.Length == 1 (~You must provide a value expression following the '*' operator.)

### Actual behavior

```c#
string input = "& {$outputencoding = [console]::outputencoding =[system.text.encoding]::utf*;$scriptfilestream = [system.io.file]::open('c:\\someuser\\somefolder\\somefile.ps*', [system.io.filemode]::open, [system.io.fileaccess]::read, [system.io.fileshare]::read);$calculatedhash = get-filehash 'c:\\someuser\\somefolder\\somefile.ps*' -algorithm sha***;if (!($calculatedhash.hash -eq '*d*db*a**af**a****a*dfbd***e****c****c**a**f**f**********b*e***c')) { exit ***;}; . 'c:\\someuser\\somefolder\\somefile.ps*' }"

ScriptBlockAst ast = Parser.ParseInput(input, out Token[] tokens, out ParseError[] errors)
```

Results:
ast == null
Tokens.Length == 0
Errors.Length == 0

### Error details

No errors returned from Parser.ParseInput

### Environment data

run in C# unit-test code in netstandard2.0, net462 and .net 6

### Visuals

```c#
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Management.Automation.Language;
using System.Text.RegularExpressions;

string input = "& {$outputencoding = [console]::outputencoding =[system.text.encoding]::utf*;$scriptfilestream = [system.io.file]::open('c:\\someuser\\somefolder\\somefile.ps*', [system.io.filemode]::open, [system.io.fileaccess]::read, [system.io.fileshare]::read);$calculatedhash = get-filehash 'c:\\someuser\\somefolder\\somefile.ps*' -algorithm sha***;if (!($calculatedhash.hash -eq '*d*db*a**af**a****a*dfbd***e****c****c**a**f**f**********b*e***c')) { exit ***;}; . 'c:\\someuser\\somefolder\\somefile.ps*' }"

ScriptBlockAst ast = Parser.ParseInput(input, out Token[] tokens, out ParseError[] errors)
```

**Comment by YotamEN** [comment]
Tried running in .net6 and failed as well (returned null) for version 7.3.0
For .net7 it works. Is this by design? Is it not backwards compatible? I did not get that from the docs on version 7.3.*

**Comment by mklement0** [comment]
Can you please format the code in "Step to reproduce" and "Visuals" (which, incidentally, is meant to be used for screenshots) with fenced code blocks? (` ```c#<newline>...<newline>``` `)

With respect to the PowerShell Core SDK NuGet package (`Microsoft.PowerShell.SDK`), the gallery indeed suggests that its v7.3.x versions work with .NET 7 only, and that the v7.4 (currently preview) versions require .NET 8:

* https://www.nuget.org/packages/Microsoft.PowerShell.SDK/7.3.0#supportedframeworks-body-tab
* https://www.nuget.org/packages/Microsoft.PowerShell.SDK/7.4.0-rc.1#supportedframeworks-body-tab

**Comment by YotamEN** [comment]
Updated!
Thanks for your quick answer, is there a reason this can't be backwards compatible?
Anyways, for now I will not update until we update to .NET 7.

**Comment by mklement0** [comment]
>  is there a reason this can't be backwards compatible?

I don't know the answer, but perhaps @daxian-dbw can help.

**Comment by TravisEz13** [comment]
7.3 requires .NET 7.  Does the problem reproduce with .NET 7?
