### ISSUE TITLE
PowerShell 7 distributed via dotnet tool broken by upgrade to .NET 8

### ISSUE THREAD

**Issue by bradwilson** [PowerShell/PowerShell#20685]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

With today's release of .NET 8, I updated Visual Studio 2022 to install .NET 8 and removed the .NET 7 runtime. After the suggested reboot, PowerShell 7 was broken, and reinstalling it didn't help:

![59814fd4d0f0586c](https://github.com/PowerShell/PowerShell/assets/16944/06a3eba1-e37b-4b68-85a3-c65538369f69)

Uninstalling the `dotnet tool` distributed version and using the `WinGet` distributed version was an effective workaround.

### Expected behavior

```console
PowerShell works.
```

### Actual behavior

```console
PowerShell crashes on launch.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Did you remove .NET 7 yourself rather than it happening automatically? 

If so then the title should be changed to PowerShell tool installed that uses .NET 7 breaks when you uninstall .NET 7.

I have also updated Visual Studio and have

```
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

So I don't think the default update removes .NET 7

**Comment by bradwilson** [comment]
> Did you remove .NET 7 yourself rather than it happening automatically?

Yes. I said I did:

> > I updated Visual Studio 2022 to install .NET 8 and removed the .NET 7 runtime.

Perhaps you misread what I wrote.

> the title should be changed to PowerShell tool installed that uses .NET 7 breaks when you uninstall .NET 7.

If you wish. I don't think that makes a difference as to the fact that the tool is now broken. I presume with a clean version of Windows and nothing installed but .NET 8, it would still be broken, but that's a scenario for the PowerShell team could validate while investigating the bug.

> So I don't think the default update removes .NET 7

I didn't claim it did, and I'm unclear why you felt it was necessary to take such a passive/aggressive position here.

**Comment by rhubarb-geek-nz** [comment]
I was trying to establish what the root cause was, it wasn't the upgrade to .NET 8, it was the uninstalling of .NET 7 that caused the problem.

Each version of PowerShell uses a specific version of .NET, the 7.2.x use .NET 6, the 7.3.x use .NET 7 and the 7.4.x use .NET 8

So to have a version of the PowerShell dotnet tool that works with .NET 8 you would need a 7.4.x series one, which are currently still preview.

The dotnet installation directory tree is designed to support multiple different runtimes, so there should be no need to uninstall .NET 7.

**Comment by bradwilson** [comment]
The problem isn't that it requires .NET 7, it's that installation via `dotnet tool` when .NET 7 isn't installed isn't blocked and/or indicates the .NET 7 requirement.

**Comment by John0King** [comment]
@bradwilson   you can try `pwsh --roll-forward LatestMajor`     see msdoc here https://learn.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior

**Comment by rhubarb-geek-nz** [comment]
I would certainly agree that dependency management isn't robust, the installation of an SDK is unaware of dependent tools,

https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues

This has a few relevant paragraphs which apply

```
Roll forward doesn't occur between preview versions of the runtime or between preview versions and release versions. So, .NET tools created using preview versions must be rebuilt and republished by the author and reinstalled.
```

and

```
If an application can't find an appropriate runtime, it fails to run and reports an error.
```

So this looks like an inherent problem with dotnet tools

**Comment by rhubarb-geek-nz** [comment]
I did some testing on an ARM64 Debian environment in a docker and was able to use the PowerShell 7.3.9 tool with only the 8.0 SDK installed.

Show installed runtimes

```
root@bullseye:~# dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Show installed tool

```
root@bullseye:~# which pwsh
/root/.dotnet/tools/push
```

Check installed tool

```
root@bullseye:~# file /root/.dotnet/tools/pwsh
/root/.dotnet/tools/pwsh: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=6a0e2396473bac0483f73198673d81ab7e1b2dcb, stripped
```

```
root@bullseye:~# ldd /root/.dotnet/tools/pwsh
	linux-vdso.so.1 (0x0000ffffb6b3f000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffb6a9c000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffb6a88000)
	libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffffb68b0000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffb6805000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffffb67e1000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb666d000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffb6b0f000)
```

Run installed tool

```
root@bullseye:~# pwsh --version
PowerShell 7.3.9
```

```
root@bullseye:~# pwsh 
PowerShell 7.3.9
PS /root> exit
```

I must admit I am not a fan of dotnet tools, especially global ones on Linux, because they are not global, they are private to the root user. The MSI or Linux package at least have all the dependencies either referenced or contained and can be managed with the standard operating system tools.

**Comment by bradwilson** [comment]
> I must admit I am not a fan of dotnet tools, especially global ones on Linux, because they are not global, they are private to the root user.

That's because you're using the root user. It's private to the account you're using (and I'd strongly disrecommend using the root user as your interactive account).

"Global" means "not tied to a specific project", not "global to the machine". That's also true on Windows, as installing a global tool places it into your user folder. Here is an example that illustrates that (and also shows how a tool that needs a specific runtime should properly surface that requirement, rather than just outright crashing):

```
 pwsh$ dotnet outdated
You must install or update .NET to run this application.

App: C:\Users\bradwilson\.dotnet\tools\dotnet-outdated.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.25 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Note where the executable is located.

**Comment by adityapatwardhan** [comment]
Thank you @bradwilson for reporting this! There is another workaround for it. In the pwsh.runtime.config file under $pshome, change the value of rollForwardOnNoCandidateFx from 2 to 1.

**Comment by rhubarb-geek-nz** [comment]
I tried to replicate the full sequence on debian bookworm on amd64. 

I used https://packages.microsoft.com/debian/12/prod/pool/main/p/packages-microsoft-prod/packages-microsoft-prod_1.1-debian12_all.deb to provide the versions of dotnet.

Installing powershell tool with both SDKs 6.0 and 7.0 installed worked.

```
$ sudo apt-get update
...
$ sudo apt-get install dotnet-sdk-6.0 dotnet-sdk-7.0
...
$ dotnet tool install --global powershell
...
$ PATH=$PATH:$HOME/.dotnet/tools
$ pwsh
PowerShell 7.3.9
PS /home/bythesea> exit
```

Removing SDK 7.0 gave the expected error regarding missing 7.0 runtime

```
$ sudo apt remove dotnet-runtime-deps-7.0 dotnet-hostfxr-7.0 dotnet-targeting-pack-7.0  dotnet-apphost-pack-7.0
...
$ pwsh
You must install or update .NET to run this application.

App: /home/bythesea/.dotnet/tools/pwsh
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '7.0.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.25 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=debian.12-x64
```

Installing SDK 8.0 then fixed the issue

```
$ sudo apt-get install dotnet-sdk-8.0
...
$ pwsh
PowerShell 7.3.9
PS /home/bythesea> exit
```

**Comment by rhubarb-geek-nz** [comment]
Looking back at the original error message it suggests that it finds and uses the 8.0 runtime but fails to find a suitable Microsoft.Management.Infrastructure assembly.

**Comment by rhubarb-geek-nz** [comment]
This looks related, it also fails on the Microsoft.Management.Infrastructure assembly, and suggests that a 7.4 powershell tool would fix the issue.

https://github.com/PowerShell/PowerShell/issues/20559

**Comment by rhubarb-geek-nz** [comment]
7.4.0 is now available as the dotnet tool

```
$ dotnet tool install --global powershell
Skipping NuGet package signature verification.
You can invoke the tool using the following command: pwsh
Tool 'powershell' (version '7.4.0') was successfully installed.
$ $HOME/.dotnet/tools/pwsh
PowerShell 7.4.0
PS /home/bythesea>
```

**Comment by daxian-dbw** [comment]
> Thank you @bradwilson for reporting this! There is another workaround for it. In the pwsh.runtime.config file under $pshome, change the value of rollForwardOnNoCandidateFx from 2 to 1.

I believe changing `rollForwardOnNoCandidateFx` from 2 to 1 won't make the PowerShell global tool 7.3.9 run without .NET 7 installed, but will fail with a different error about not finding the compatible .NET runtime. But I guess that's a much clearer message to show why it doesn't work.
