### ISSUE TITLE
$ character in az uri string being interpreted by powershell as a command

### ISSUE THREAD

**Issue by abelal83** [PowerShell/PowerShell#20686]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When assigning output of an AZ cli rest command where URI contains a $ symbol powershell attempts to parse the value of $, even though the string is in quoted with single quotes.

### Expected behavior

```console
$t = az rest --uri 'https://management.azure.com/subscriptions/d904052e-5309-4000-9a3f-XXXXXXXXX/resourceGroups/plt-XXXXX-dev-rg-01/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter=asTarget()'
```

### Actual behavior

```console
$t = az rest --uri 'https://management.azure.com/subscriptions/d904052e-5309-4000-9a3f-XXXXXXXXX/resourceGroups/plt-XXXXX-dev-rg-01/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter=asTarget()'
'$filter' is not recognized as an internal or external command,
operable program or batch file.
```

### Error details

```console
'$filter' is not recognized as an internal or external command,
operable program or batch file.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

When I run just the below in powershell it works fine, but obviously I'm not assigning return value to anything.

az rest --uri 'https://management.azure.com/subscriptions/d904052e-5309-4000-9a3f-XXXXXXXXX/resourceGroups/plt-XXXXX-dev-rg-01/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter=asTarget()'

**Comment by jborean93** [comment]
I don't see this behaviour. Even when calling an exe that just outputs the args provided to it you can see the `$` is treated literally

![image](https://github.com/PowerShell/PowerShell/assets/8462645/c6d49033-ae2f-40db-8f44-1f4e7873c4b1)

How exactly are you calling it in PowerShell?

**Comment by abelal83** [comment]
Hi, thanks so much for the super quick response.

I'm calling it as below:

![image](https://github.com/PowerShell/PowerShell/assets/20558784/d51b135d-4e77-4e94-b35b-18e43c9dc771)

(red marked boxes are to mask senstive info)

When I don't include $filter it works as expected (I've included | ConvertFrom-Json to keep output small)

![image](https://github.com/PowerShell/PowerShell/assets/20558784/5e0215f8-b160-428c-81cb-dd01b4bfc1f9)

It's very strange, I was expecting anything in '' to be ignored.

**Comment by mklement0** [comment]
The problem is that the `az` CLI is implemented _as a batch file_ (`az.cmd`) and `cmd.exe` inappropriately parses a batch file's arguments as if they had been submitted _from inside a `cmd.exe` session.

When PowerShell rebuilds the process command line behind the scenes it decides which arguments to double-quote strictly based on whether a given argument _contains spaces_.

Thus, any space-less argument that happens to contain `cmd.exe` metacharacters such as `&` _breaks_ batch-file invocations; a simple repro is:

```powershell
# -> 'b' is not recognized as an internal or external command, operable program or batch file.
cmd /c echo 'a&b'
```

`cmd.exe` is one of the programs that exhibits the old, broken argument-passing behavior in  the default mode of the [`$PSNativeCommandArgumentPassing` preference variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Preference_Variables#psnativecommandargumentpassing), `Windows`, so the workaround is to use _embedded double-quoting_:

```powershell
# -> OK
cmd /c echo '"a&b"'
```

Therefore:

```powershell
$t = az rest --uri '"https://management.azure.com/subscriptions/d904052e-5309-4000-9a3f-XXXXXXXXX/resourceGroups/plt-XXXXX-dev-rg-01/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter=asTarget()"'
```


See also:
* #15143

**Comment by mklement0** [comment]
Glad to hear it helped, @abelal83.

I should mention that the `'"..."'` workaround comes with a caveat:

Should the Azure CLI ever move away from a batch-file entry point, the workaround will break.

A future-proof alternative is to call via `cmd /c` (using [`--%`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Parsing#the-stop-parsing-token) is also an option, but comes with many limitations):

```powershell
$t = cmd /c 'az rest --uri "https://management.azure.com/subscriptions/d904052e-5309-4000-9a3f-XXXXXXXXX/resourceGroups/plt-XXXXX-dev-rg-01/providers/Microsoft.Authorization/roleManagementPolicies?api-version=2020-10-01&$filter=asTarget()"'
```

Small caveat: If you explicitly set `$PSNativeCommandArgumentPassing = 'Standard'`, the `cmd /c` workaround breaks too (only the `--%` approach is truly independent of `$PSNativeCommandArgumentPassing`).

This highlights the general problems with `Windows` mode (which #15143  was meant to address by obviating the need for this mode altogether):

* You generally need to be aware of what executables it applies to, and there's the risk of the list of this list of executables growing piecemeal over time.

* The workarounds using embedded quoting / manual `\`-escaping of truly embedded `"` chars. rely on historical, _broken_ behavior that never made any sense and may confuse newcomers. 

* For a given third-party CLI - such as in the case at hand - you may not even know what type of executable it is, _nor should you have to_.

* If a given third-party CLI switches from a batch file to a different executable type in a future version, said workarounds will break.
