### ISSUE TITLE
Start-PSPester doesn't have -Directory or -Test parmeters

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#2070]

**Comment by dfinke** [comment]
In

https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#running-tests-outside-of-ci

If you wish to run specific tests, that is possible as well:

`Start-PSPester -Directory test/powershell/engine/Api`
Or a specific Pester test file:

`Start-PSPester -Directory test/powershell/engine/Api -Test XmlAdapter.Tests.Api`

The function in build.psm1 does not have this implemented

**Comment by vors** [comment]
Thanks for pointing it out!
The doc is a little bit out-of-date. I replaced both these paremeters by `-Path` in ea3e7db5

**Comment by dfinke** [comment]
`Start-PSPester` didn't run the tests, `Invoke-Pester` worked.

![image](https://cloud.githubusercontent.com/assets/67258/18034570/59a88c86-6d0e-11e6-96f5-9f47351ffe58.png)

**Comment by latkin** [comment]
Bump on this, please considering updating the docs soon. Currently the documented steps for running tests (`Start-PSPester`) simply don't work on either Windows or Mac. Very confusing/discouraging for anyone trying to be a good citizen contributor and run/add tests.

**Comment by lzybkr** [comment]
@JamesWTruher - can you make sure the docs are updated?

**Comment by iSazonov** [comment]
@lzybkr it seems @JamesWTruher is busy and I did the fix.

**Comment by daxian-dbw** [comment]
The doc has been updated and I verified that `Start-PSPester -Path` works.
