### ISSUE TITLE
Test-FileCatalog can't calculate a hash for an open file

### ISSUE THREAD

**Issue by dxk3355** [PowerShell/PowerShell#20703]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

With Notepad++ open, open powershell and run these commands:
```
New-FileCatalog -CatalogFilePath [test.cat](http://test.cat/) -Path 'C:\Program Files\Notepad++'
Test-FileCatalog -CatalogFilePath .\[test.cat](http://test.cat/) -Path 'C:\Program Files\Notepad++'
```

At this point I get the error "Test-FileCatalog: Unable to read file C:\Program Files\Notepad++\plugins\JsonTools\JsonTools.dll to calculate its hash."

Then close Notepad++ and run 
`Test-FileCatalog -CatalogFilePath .\[test.cat](http://test.cat/) -Path 'C:\Program Files\Notepad++'`

Now it should work.

If Notepad++ is not something you can use, most any other active program seems to cause this same problem.

Here's my output.  Get-FileHash is able to generate a file hash while notepad++ is open.

```

PS C:\Users\d\Downloads\PowerShell-7.4.0-rc.1-win-x64> New-FileCatalog -CatalogFilePath [test.cat](http://test.cat/) -Path 'C:\Program Files\Notepad++'


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/16/2023  1:21 PM          53728 [test.cat](http://test.cat/)

PS C:\Users\d\Downloads\PowerShell-7.4.0-rc.1-win-x64> Test-FileCatalog -CatalogFilePath .\[test.cat](http://test.cat/) -Path 'C:\Program Files\Notepad++'

Test-FileCatalog: Unable to read file C:\Program Files\Notepad++\plugins\JsonTools\JsonTools.dll to calculate its hash.

PS C:\Users\d\Downloads\PowerShell-7.4.0-rc.1-win-x64> Get-FileHash 'C:\Program iles\Notepad++\plugins\JsonTools\JsonTools.dll'


Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          E4E33D43BB06D866520C12E84F0F0760977670304DD275F5C70BE397246E1B30       C:\Program Files\Notepad++\plug…


PS C:\Users\d\Downloads\PowerShell-7.4.0-rc.1-win-x64> Test-FileCatalog -CatalogFilePath .\[test.cat](http://test.cat/) -Path 'C:\Program Files\Notepad++'

Valid


```

I've seen this on Windows 11 and Windows Server 2019.  I tested on PowerShell-7.4.0-rc.1-win-x64.  It also happens with PS 5.1.

This happens with any program. I first noticed when trying to use the catalogs to compare the differences between two servers files that the online server would fail.

### Expected behavior

```console
The Test-FileCatalog is only generating a hash with the Test-FileCatalog so it should be able to read open files.
```

### Actual behavior

```console
If file is in use it cannot create a hash.  This makes it impossible to use this to verify in use programs or files.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-rc.1
PSEdition                      Core
GitCommitId                    7.4.0-rc.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dxk3355** [comment]
I think the likely issue is this module is using File.Read() withouth the FileShare parameter.

https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/security/CatalogHelper.cs#L426
fileStream = File.Open(filePath, FileMode.Open, FileAccess.Read);

https://github.com/PowerShell/PowerShell/blob/094e22e97ddcb982687f5e7a66c2567907e51124/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs#177
Uses  openfilestream = File.OpenRead(path);


**File.OpenRead -** https://learn.microsoft.com/en-us/dotnet/api/system.io.file.openread?view=net-7.0
This method is equivalent to the [FileStream(String, FileMode, FileAccess, FileShare)](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=net-7.0#system-io-filestream-ctor(system-string-system-io-filemode-system-io-fileaccess-system-io-fileshare)) constructor overload with a [FileMode](https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-7.0) value of [Open](https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-7.0#system-io-filemode-open), a [FileAccess](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileaccess?view=net-7.0) value of [Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileaccess?view=net-7.0#system-io-fileaccess-read) and a [FileShare](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=net-7.0) value of [Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=net-7.0#system-io-fileshare-read).

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this, we agreed that Test-FileCatalog should open the files as shared read and this might simply be an oversight when this cmdlet was written.  We don't see any concerns with such a change.
