### ISSUE TITLE
[pscustomobject] type accelerator does not work in 7.4.0

### ISSUE THREAD

**Issue by shivtorov** [PowerShell/PowerShell#20719]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1) Open PowerShell 7.4.0 tab in Windows Terminal
2) cast a hashtable to pscustomobject type accelerator

Expected results: a new object created
Actual results: nothing  = no new object, no errors, no hashtable 

### Expected behavior

```console
PS> [pscustomobject]@{one=1; two=2}

one two
--- ---
  1   2
```

### Actual behavior

```console
PS> [pscustomobject]@{one=1; two=2}
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/31003608/973e0da0-add4-442d-88fa-22be8455e22a)

**Comment by trackd** [comment]
that's pretty strange, your example works for me on 7.4.0.

```ps1
PS > [pscustomobject]@{one = 1; two = 2 }
one two
--- ---
  1   2

PS > ([pscustomobject]@{one = 1; two = 2 }).Gettype().Name
PSCustomObject

PS > ([pscustomobject]@{one = 1; two = 2 }).One.Gettype().Name
Int32

PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by B-Art** [comment]
It does just work for me:
The only remark I have is that PSCompatibleVersions is displayed trackd shows. {1.0, 2.0, 3.0, 4.0…}
Not showing like {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
But 
```
$PSVersionTable.PSCompatibleVersions
```
Shows:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      -1     -1
2      0      -1     -1
3      0      -1     -1
4      0      -1     -1
5      0      -1     -1
5      1      -1     -1
6      0      -1     -1
7      0      -1     -1
```

**Comment by B-Art** [comment]
Also check how (in what way) you did install pwsh 7.4:
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

**Comment by HumanEquivalentUnit** [comment]
It works for me as well; do you get anything if you run this, to see if there is an output and it's just being hidden on your terminal somehow:

```powershell
PS> $x = [pscustomobject]@{one=1; two=2}
PS> $x | Get-Member
```

Or these, to check if the type accelerator is working?

```powershell
PS C:\> [pscustomobject]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSObject                                 System.Object

PS C:\> [pscustomobject].FullName
System.Management.Automation.PSObject

PS C:\> [System.Management.Automation.PSCustomObject]

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object
```

**Comment by shivtorov** [comment]
yeah, that's a weird issue.
I checked the same on a different Windows 11 23h2 PC and everything works as expected there.
I uninstalled and manually reinstalled 7.4.0 version using MSI (x64) installer on the affected PC - issue is still there.

![image](https://github.com/PowerShell/PowerShell/assets/31003608/c4b0e925-3e90-4d87-b498-8aaa870cd0a4)

The OS on the affected PC is freshly installed from ISO a week ago.
The only thing that is different on this PC is that it is managed by company policies pushed via Microsoft Intune.
One of these policies enabled "Constrained Language Audit Mode" (whatever it means).
I guess that this "Constrained Language Audit Mode" is breaking [pscustomobject].

I downloaded x64 ZIP versions 7.4.0 and 7.3.10 to test without installation - results are:

![image](https://github.com/PowerShell/PowerShell/assets/31003608/bc3c2eee-ace3-4683-a2b8-f3c7e9b99fc2)

I have a workaround for this problem for me - I will just use a different PC/VM for executing scripts using  [pscustomobject] type accelerator.

**Comment by shivtorov** [comment]
The issue is affecting all corporate laptops in our company.
It turned out that somehow corporate policies activate ConstrainedLanguage mode, but only v7.4.0
Strangely, the policies don't affect previous versions (such as 7.3.10)
My fix is to manually switch to FullLanguage mode.

![image](https://github.com/PowerShell/PowerShell/assets/31003608/3cab8e5b-7112-4aee-9882-3311b9337335)

**Comment by mklement0** [comment]
The odd thing is that if you _manually_ put a session in `ConstrainedLanguage` [language mode](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes), an attempt to create a `[pscustomobject]` literal _fails noisily_:

```powershell
# From a regular session (with language mode 'FullLanguage')
# CAVEAT: You won't be able to undo this in the same session.
$ExecutionContext.SessionState.LanguageMode = 'ConstrainedLanguage'
[pscustomobject] @{ foo = 1 }
```

Curiously, the error message depends on whether at least one such literal was defined earlier, _while the session was still in `FullLanguage` mode_:

* In the latter case:

```
InvalidArgument: Cannot convert value "System.Collections.Specialized.OrderedDictionary" to type "System.Management.Automation.LanguagePrimitives+InternalPSCustomObject". 
Error: "Cannot convert hashtable to an object of the following type: System.Management.Automation.LanguagePrimitives+InternalPSCustomObject. 
Hashtable-to-Object conversion is not supported in restricted language mode or a Data section."
```

* If no `[pscustomobject]` literal was defined before entering constrained mode:

```none
InvalidArgument: Cannot convert value to type "System.Management.Automation.LanguagePrimitives+InternalPSCustomObject". 
Only core types are supported in this language mode.
```

The fact that hashtable literals _alone_ work fine, and that `[pscustomobject]` is among the whitelisted types, as well as the fact that the equivalent `New-Object pscustomobject -property @{ foo = 1 }` _does_ work, leads me to believe that this is indeed a bug - though it isn't specific to 7.4.0 - I see it in 7.3.8 too, and even in _Windows PowerShell_.

The _different symptom_ in your policy-enforced `ConstrainedLanguage` scenario needs investigating too.

---

@shivtorov, note that `[System.Management.Automation.PSCustomObject] @{ foo = 1 }` _never_ worked - only `[pscustomobject] @{ foo = 1 }` does, because - confusingly - these aren't the same types (`[pscustomobject]` is the same type as `[psobject]`, i.e. `[System.Management.Automation.PSObject]`,  but the syntactic sugar only works with `[pscustomobject]`:
* #4344

**Comment by mklement0** [comment]
On further reflection, I think there are two separate bugs:

* #20768
* #20767
