### ISSUE TITLE
PS 7.4.0.0 Import-Module AppX fails with error 0x80131539 "Operation is not supported on this platform"

### ISSUE THREAD

**Issue by target-san** [PowerShell/PowerShell#20721]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install latest Powershell 7.4.0.0
2. Execute `Import-Module Appx`

Note: Existing issue on this was closed without actual resolution: [#13138](https://github.com/PowerShell/PowerShell/issues/13138)

### Expected behavior

```console
PS> import-module appx
Command succeeds
```

### Actual behavior

```console
PS> import-module appx
Import-Module: Operation is not supported on this platform. (0x80131539)
```

### Error details

```console
PS> Get-Error

Exception             :
    Type       : System.PlatformNotSupportedException
    TargetSite :
        Name          : GetExportedTypes
        DeclaringType : System.Reflection.RuntimeAssembly, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, Pu
blicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Operation is not supported on this platform. (0x80131539)
    Source     : System.Private.CoreLib
    HResult    : -2146233031
    StackTrace :
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, Str
ing name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& ali
ases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PS
SnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers
, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleI
nfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, String moduleName, Str
ing fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcess
ingFlags manifestProcessingFlags, String prefix, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecifi
cation moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOp
tions options, ManifestProcessingFlags manifestProcessingFlags, Object privateData, Boolean& found, String shortModuleN
ame, Nullable`1 manifestLanguageMode)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo m
anifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version mi
nimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& opti
ons, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String modu
leBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manif
estProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(PSModuleInfo parentModule, String moduleName,
String fileBaseName, String extension, String moduleBase, String prefix, SessionState ss, ImportModuleOptions options,
ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(PSModuleInfo parentModule, IEnumerable`1 modul
ePath, String name, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, PSMo
duleInfo& module)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOpt
ions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions i
mportModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Import-Module], PlatformNotSupportedException
FullyQualifiedErrorId : System.PlatformNotSupportedException,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        :
    MyCommand        : Import-Module
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : import-module appx
    Statement        : import-module appx
    PositionMessage  : At line:1 char:1
                       + import-module appx
                       + ~~~~~~~~~~~~~~~~~~
    InvocationName   : import-module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Does the given workaround work? 

```
Import-Module -Name Appx -UseWindowsPowerShell
```

**Comment by target-san** [comment]
Yes, it does:
```
PS C:\Users\User> Import-Module -Name AppX -UseWindowsPowerShell
WARNING: Module AppX is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
```
Unfortunately I encountered this issue while collecting WSL logs using their script. So it's not very clear where this issue belongs. I guess there are two, one with import itself, other with log collect script not warning it needs Windows Powershell 5.

**Comment by rhubarb-geek-nz** [comment]
You say WSL so are these Linux installation? I thought WinRT was a windows only thing, and Linux requires core.

**Comment by target-san** [comment]
Nope. It's from Windows side. I got my WSL completely broken by last cumulative update, so used their script to collect logs and encountered this error. Had to find workaround running it from Powershell 5.

**Comment by mklement0** [comment]
To provide additional context:

An explicit workaround shouldn't be needed, because any _Windows PowerShell_ system module whose module manifest doesn't explicitly indicate PS Core compatibility is automatically loaded via the [Windows PowerShell Compatibility feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility).

`Get-Module -ListAvailable -All Appx` shows only `Desk`, i.e. Windows PowerShell in the `PSEdition` column.

In other words: 

* `Import-Module Appx` should be the same as `Import-Module -UseWindowsPowerShell Appx`
* Normally, the only way to provoke the error your'e seeing is to explicitly override the compatibility check, with `-SkipEditionCheck`.

So the question is: Why does in `Import-Module Appx` in your case behave like `Import-Module -SkipEditionCheck Appx`?
Is the `-SkipEditionCheck` switch preset via the [`$PSDefaultParameterValues` preference variable](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Preference_Variables#psdefaultparametervalues), per chance?

**Comment by target-san** [comment]
Powershell 7.4:
```
PS> $PSDefaultParameterValues
PS>
```

**Comment by mklement0** [comment]
There's the culprit: Your `AppX` module is incorrectly manifested as being `Core`-compatible.

I vaguely remember seeing this before; the implication is that you're using an older version of Windows, with an outdated `AppX` module.

What is your specific Windows version, expressed as Windows 10 vs. Windows 11, and in terms of display version (`Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DisplayVersion`)?

**Comment by target-san** [comment]
Windows 10
```
PS> Get-ItemPropertyValue 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' DisplayVersion
22H2
```

**Comment by mklement0** [comment]
Thanks. 
As far as I can tell, your options are (I don't know if there's an official recommendation):

* Upgrade to a more recent version of Windows - I don't know if there's a Windows 10 update that would address it or only moving to Windows 11 would help.

* Use `$PSDefaultParameterValues` to automatically apply `-UseWindowsPowerShell` dynamically via a script block (if you place this is in a `$PROFILE` file, it will take effect for all future sessions, but note that profile loading can be _bypassed_ with `-NoProfile`):

```powershell
$PSDefaultParameterValues['Import-Module:UseWindowsPowerShell'] = { 
  if ((Get-PSCallStack)[1].Position.Text -match '\bAppX\b') { $true } 
}
```


* Modify `"C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Appx\Appx.psd1"` to remove `'Core'` from the `CompatiblePSEditions` entry.
  * This not only requires elevation, but requires taking ownership of the file first.
  * Obviously not a great solution, but I _think_ it would work, given that module doesn't appear to be signed.
  * If subsequent OS updates don't yet include the fixed module, you'll have to do it again.

**Comment by target-san** [comment]
Thanks for suggesting workaround, though I doubt I'll need it.
But there are other people hitting same issue in the closed issue I mentioned, so I guess it's worth investigating, esp. why `AppX` gets `Core` compatibility in manifest.

**Comment by mklement0** [comment]
Glancing at the linked issue, the history is:

* The module _was_ PowerShell Core-compatible, but only until v7.0.x.

* The move to .NET 5 (PowerShell 7.1+) broke this, due to the removal of built-in WinRT support from .NET.

* In PowerShell 7.1+, as of this writing, the only way to use the module is via the [Windows PowerShell Compatibility](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility) feature, with the performance penalty and the type-fidelity limitations that entails.

* The module _ships with Windows_, so it took a while for a version of the module to ship that indicated the lack of compatibility with PowerShell Core in Windows 11, but this was seemingly not back-ported to Windows 10.

I'll write up a summary in the linked issue.

**Comment by mklement0** [comment]
See https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-1820195503

**Comment by mklement0** [comment]
Thanks, @daxian-dbw - just to avoid confusion (emphasis added):

> We _didn't_ make the change to the module manifest of `Appx` to remove `Core` from its `PSEdition` key

I assume you meant to say _did_, because that's what happened.
(also, the module-manifest entry's key name is `CompatiblePSEditions`).

**Comment by wolfthegreat** [comment]
> Thanks.
> 
> As far as I can tell, your options are (I don't know if there's an official recommendation):
> 
> * Ad hoc:
>   
>   * Add `-UseWindowsPowerShell` to the `Import-Module AppX` call.
> * Persistently, one of the following:
>   
>   * Upgrade to Windows 11, which has an updated `AppX` module that indicates the lack of compatibility with PowerShell Core, causing `-UseWindowsPowerShell` to be _implied_.
>   * Use `$PSDefaultParameterValues` to automatically apply `-UseWindowsPowerShell` dynamically via a script block; if you place this is in a `$PROFILE` file, it will take effect for all future sessions, but note that profile loading can be _bypassed_ with `-NoProfile`:
>     ```
>     $PSDefaultParameterValues['Import-Module:UseWindowsPowerShell'] = { 
>       if ((Get-PSCallStack)[1].Position.Text -match '\bAppX\b') { $true } 
>     } 
>     ```
>   * Modify `"C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Appx\Appx.psd1"` to remove `'Core'` from the `CompatiblePSEditions` entry.
>     
>     * This not only requires elevation, but requires taking ownership of the file first.
>     * Obviously not a great solution, but I _think_ it would work, given that module doesn't appear to be signed.
>     * If subsequent OS updates don't yet include the fixed module, you'll have to do it again.

'\bAppX\b' from 2nd variant doesn't work, but runs fine with just 'AppX'

**Comment by wolfthegreat** [comment]
> @wolfthegreat, `'\bAppX\b'` is meant to make the command more robust to rule out false positives - however unlikely they may be; say `Import-Module MyAppX`.
> 
> If you're not worried about that, `'AppX'`works too, but note that `'\bAppX\b'` _does_ work as intended, as the following simplified example demonstrates:
> 
> ```powershell
> $sb = {
>   (Get-PSCallStack)[1].Position.Text -match '\bAppX\b'
> } 
> 
> & $sb AppX  # -> $true
> & $sb MyAppX # -> $false
> ```

I have figured out that my use case was to run Get-AppXPackage without Import-Module, so 'appx' without \b matches and hereby produces "true" positive so to speak.

**Comment by mklement0** [comment]
Good point, @wolfthegreat:

* My solution was focused on _explicit_ module import via an explicit `Import-Module` call, in line with the initial post.

* By contrast, you were relying on [module auto-loading](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Modules#module-autoloading), in the context of simply calling any of the cmdlets from the `AppX` module without explicitly importing the module first.

Given that _both_ scenarios are worth supporting, a _reasonably robust_ compromise is to use `'\bAppX'` instead, relying on the fact that all cmdlets from said module match the pattern `*-AppX*`.

I've updated both [my previous comment](https://github.com/PowerShell/PowerShell/issues/20721#issuecomment-1817595894) and the [linked summary](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-1820195503) accordingly.
