### ISSUE TITLE
Unexpected Behavior of return in Switch Block 

### ISSUE THREAD

**Issue by danstur** [PowerShell/PowerShell#20739]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Executing the following script in PowerShell 7.4.0 results in an unexpected behavior which also differs from PowerShell 5.1
```
function foo($x) {
    $val = switch ($x){
        1 { 5 }
        default {
            return 10 
        }
    }
    Write-Host "Val is $val" 
    $val + 1
}

Write-Host "foo 1: $(foo 1)"
Write-Host "foo 2: $(foo 2)"
```

PS 5.1 output:
```
Val is 5
foo 1: 6
foo 2: 10
```

PS 7.4.0 output:
```
Val is 5
foo 1: 6    
foo 2:
```

It's not clear if this is a bug or simply a documente change from classic PowerShell, but it certainly behaves in a way I don't find intuitive.

### Expected behavior

```console
PS> <execute script>
Val is 5
foo 1: 6
foo 2: 10
```

### Actual behavior

```console
PS> <execute script>
Val is 5
foo 1: 6
foo 2:
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by IISResetMe** [comment]
I have a feeling this isn't specific to `switch` statements - it appears the `return` expression ends up in the original assignment target when you return from any dot-sourced block:

```
function f {
  try {
    $value = . { return 10 }
  }
  finally {
    Write-Host "`$Value is: '${Value}'"
  }
}

$returnValue = f
Write-Host "Return value is: '${returnValue}'"
```

**Comment by mklement0** [comment]
The different behaviors can be demonstrated with the following simple command:

```powershell
$a = if ($true) { return 10 }
```

* Windows PowerShell and PowerShell (Core) 7.3.x (presumably earlier too):
  * No assignment, outputs `10`.
* PowerShell 7.4.0:
  * No assignment, _no output_.

That is, what the behaviors _share_ is that _no assignment takes place_, but that there is _no output_ in 7.4.0 is clearly a bug.

The WinPS / PS 7.3- behavior may be surprising, but is defensible:

* It is important to note that `return` does _not_ exit just a `{ ... }`-enclosed part of a _language statement_ such as `if` or `switch`, but _its enclosing function/script file/script block_. 

* That is, the `{ ... }` parts of such statements do _not_ function like stand-alone script blocks such as the ones passed to `ForEach-Object`, in which `return` truly only exits _that block_.

Therefore, in the original code the `return` immediately exits the _whole function_, with 7.4.0 inexplicably discarding the output.

**Comment by danstur** [comment]
@mklement0 The behavior of 7.3.x and previous is what I'd intuitively expect to happen when reading the code.
