### ISSUE TITLE
PS 7.4.0: "-Tail 0" ignores "-Wait" and immediately stops Get-Content

### ISSUE THREAD

**Issue by 6e6e58c4** [PowerShell/PowerShell#20731]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Get-Content -Path "<any file>" -Wait -Tail 0
```

### Expected behavior

```console
PS> Get-Content -Path "<any file>" -Wait -Tail 0
<no file content, waiting for new content>
```

### Actual behavior

```console
PS> Get-Content -Path "<any file>" -Wait -Tail 0
PS> <Get-Content immediately stops>
```

### Environment data

```powershell
PSVersion: 7.4.0
PSEdition: Core
GitCommitId: 7.4.0
OS: Microsoft Windows 10.0.19044
Platform: Win32NT
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
```

### Visuals

![gc-tail-broken](https://github.com/PowerShell/PowerShell/assets/35571800/c8f134dc-ea57-45e9-b973-e6e8e819b20d)

**Comment by 6e6e58c4** [comment]
Might be caused by #19715 and that `|| Tail == 0`

```
if (TotalCount == 0 || Tail == 0)
            {
                // Don't read anything
                return;
```
https://github.com/PowerShell/PowerShell/pull/19715/files#diff-0cf19feadd29d19fb01dcfe57f5fd9bd24be0d5fed7c1241f0cfa05da14c2fc1R90

**Comment by mklement0** [comment]
Yes, it looks like the - meaningful - combination of `-Tail 0` with `-Wait` wasn't considered in the linked PR.
Correct, @CarloToso?

**Comment by NoMoreFood** [comment]
In my opinion, `-Tail 0 -Wait` is a super common use case.

**Comment by CarloToso** [comment]
> Yes, it looks like the - meaningful and previously supported - combination of `-Tail 0` with `-Wait` wasn't considered in the linked PR. Correct, @CarloToso?

It was an oversight on my part, I'll open a PR to fix it later

**Comment by mklement0** [comment]
Thanks, @CarloToso.

Yes, I'd say there's no reason to not also support `-Head 0` (though probably an uncommon use case)

However, note that combining `-Head` with `-Wait` is currently _fundamentally_ broken, which predates your PR (same behavior in WinPS).

The [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content) don't mention any mutual exclusion for `-Wait` (other than, sensibly, `-Raw`).

At least hypothetically, there could be - conceptually flawed - code out there that relies on `-Wait` being ignored in the presence of `-Head` / `-TotalCount`, though that strikes me as a [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change still worth making.
@SteveL-MSFT, any thoughts?

**Comment by mklement0** [comment]
@CarloToso, a simple way forward is to fix the regression bug with respect to `-Tail` only.
The `-Head` case (if you will) can then be dealt with separately.

**Comment by echalone** [comment]
Well, good thing I looked in the open bugs, was about to report the same issue :D
