### ISSUE TITLE
7.4.0 Redirecting stdout and stderr to Two Separate Files Leaves Empty Files

### ISSUE THREAD

**Issue by twinter-amosfivesix** [PowerShell/PowerShell#20747]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When I redirect the output and error streams of a native command to two separate files (when I know the command writes to the error stream), both files are created but they are both empty. The error file should contain content. If I redirect only the error stream, the file will contain the correct content.

Here I'm using `dotnet` as an example but the same thing happens with other commands. If you run `dotnet garbage` it will write to the error stream.

```
dotnet >x.txt 2>y.txt garbage
```

### Expected behavior

```console
PS> dotnet >x.txt 2>y.txt garbage
                                                                                                              PS> Get-Content y.txt
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'garbage' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

### Actual behavior

```console
PS> dotnet >x.txt 2>y.txt garbage
                                                                                                                                                                                 PS> Get-Content y.txt
                                                                                                                                                                                 PS> dotnet 2>y.txt garbage
                                                                                                                                                                                 PS> Get-Content y.txt
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-garbage does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/66026737/125e9090-690e-4ef2-9260-6900f356f985)

![image](https://github.com/PowerShell/PowerShell/assets/66026737/cab9e08d-4563-4d4c-ad4f-17a218c4caac)

**Comment by mklement0** [comment]
Good find. It's a regression from 7.3.x. (and WinPS).

Here's a cross-platform repro:

```powershell
& ($IsWindows ? 'cmd' : 'sh') ($IsWindows ? '/c' : '-c') ('echo success{0} echo error >&2' -f ($IsWindows ? '&' : ';')) > o.txt 2> e.txt
Get-Item o.txt, e.txt
```

In 7.4.0, `e.txt` is unexpectedly always empty instead of capturing the stderr output.

**Comment by iSazonov** [comment]
Could you please indicate the PR that made this regression?

**Comment by mklement0** [comment]
@iSazonov, I don't actually know. I just inferred that this a regression from the fact that the command works fine in v7.3.8, for instance (and in Windows PowerShell).

**Comment by twinter-amosfivesix** [comment]
After installing each 7.4.0 preview version in turn from preview 1 upwards, it appears this bug was introduced with preview 4. 

Preview 3 works as expected:
![image](https://github.com/PowerShell/PowerShell/assets/66026737/46a9709b-0618-453b-bb11-ef2ed7e2ba0a)

But Preview 4 does not:
![image](https://github.com/PowerShell/PowerShell/assets/66026737/d3c42a51-ba6b-4a38-8c38-800bf3732a2e)

Note how I tried turning off `$PSNativeCommandUseErrorActionPreference` and I get the same behavior as I get in 7.4.0 where it's turned off by default.

**Comment by twinter-amosfivesix** [comment]
Looking through the [preview change log for preview 4](https://github.com/PowerShell/PowerShell/blob/f37f7dbb0ae837475448d6d5c6d8c9876694fba5/CHANGELOG/preview.md#740-preview4---2023-06-29) ([diff between 3 and 4](https://github.com/PowerShell/PowerShell/compare/v7.4.0-preview.3...v7.4.0-preview.4)), I see:

> Fix native executables not redirecting to file ([#19842](https://github.com/PowerShell/PowerShell/pull/19842))
>
> Support byte stream piping between native commands and file redirection ([#17857](https://github.com/PowerShell/PowerShell/pull/17857))

Both are from @SeeminglyScience 

My bug is for a native executable not redirecting to a file. So maybe it's related?

@SeeminglyScience, I hope it's not presumptuous of me to ask you to take a look at my issue to see if it could be related to your PRs? Thanks!

**Comment by twinter-amosfivesix** [comment]
It definitely seems to be related to `PSNativeCommandPreserveBytePipe`. Turning off the feature in preview 4 (and setting `$PSNativeCommandUseErrorActionPreference` to `false`) makes things work as expected.

![image](https://github.com/PowerShell/PowerShell/assets/66026737/f7dbebb7-14db-478d-b5a0-b623e0d95c66)

**Comment by SeeminglyScience** [comment]
Looking into it, thanks for the report!
