### ISSUE TITLE
Mapped drive reference broken

### ISSUE THREAD

**Issue by tkoker** [PowerShell/PowerShell#20748]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PS H:\> **_$executionContext.SessionState.Path.CurrentLocation.Drive_**

Name           Used (GB)     Free (GB) Provider      Root
\----           \---------     \--------- \--------      \----
H             2805267.99    1702906.76 FileSystem    **_System.Span\<UInt16\>[0]_** {broken value}

QASFPPISMA2 System.Span<UInt16>[0] - Tue 21 Nov 2023 17:41:20
PS H:\> net use h:
Local name        H:
Remote name       **\\CSAFSUSERS1\GlobalUsers\KokerT** {used to show this}
Resource type     Disk
Status            OK
\# Opens           3
\# Connections     1
The command completed successfully.

QASFPPISMA2 System.Span\<UInt16\>[0] - Tue 21 Nov 2023 17:41:55

### Expected behavior

```console
\CSAFSUSERS1\GlobalUsers\KokerT {used to show this}
```

### Actual behavior

```console
System.Span\<UInt16\>[0] {broken value}
```

### Error details

```console
n/a
```

### Environment data

```powershell
PS H:\> $PSVersionTable

Name                           Value
\----                           \-----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

QASFPPISMA2 System.Span\<UInt16\>[0] - Tue 21 Nov 2023 18:04:20
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/1890387/c8832a30-5482-4f93-bbf3-7fedb8395386)

**Comment by mklement0** [comment]
See also:

* #19903
