### ISSUE TITLE
POWERSHELL PERSISTS WITH UPDATE NOTIFICATIONS!! 3 ISSUES HERE AND NO ANSWERS!!! WHAT IS GOING ON!!

### ISSUE THREAD

**Issue by gbr000** [PowerShell/PowerShell#20742]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I AM DONE WITH THIS, NOT GIVING ANY REASONS JUST FIX THE ISSUE!!

### Expected behavior

```console
I AM DONE WITH THIS, NOT GIVING ANY REASONS JUST FIX THE ISSUE!!
```

### Actual behavior

```console
I AM DONE WITH THIS, NOT GIVING ANY REASONS JUST FIX THE ISSUE!!
```

### Environment data

```powershell
I AM DONE WITH THIS, NOT GIVING ANY REASONS JUST FIX THE ISSUE!!
```

**Comment by kilasuit** [comment]
@gbr000 you can turn off update notifications which is already documented as [per this doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications?view=powershell-7.3)

Hope that helps you further & apologies if it doesn't help fix your ultimate issue here, however I think that it should do.

**Comment by mklement0** [comment]
You're a good sport, @kilasuit.
@gbr000 was pointed to this solution 3 issues ago: https://github.com/PowerShell/PowerShell/issues/20319#issuecomment-1728599920

**Comment by gbr000** [comment]
@kilasuit @mklement0

Is NOT helping!!

Nobody reads what I posted. I tried `UPDATE_CHECK` is not setting the enviroment.

I tried:

`$env:POWERSHELL_UPDATECHECK = "Off"`
`$env:POWERSHELL_UPDATECHECK="Off"`

and,

`$POWERSHELL_UPDATECHECK = "Off"`
`$POWERSHELL_UPDATECHECK="Off"`

as well I tried, to put into a script but that doesn't work!

**Comment by kilasuit** [comment]
That's setting it in process & not at the system or user level, which new processes inherit from.

So you need to set it as either a user or system environment variable, my suggestion being to set it as a system one.

**Comment by mklement0** [comment]
To add to @kilasuit's comment:

As a general rule, environment variables must be set _before_ a process is launched in order for the latter to see and respect them (an application would have to go out of its way to detect environment-variable changes _in-session_).

**Comment by gbr000** [comment]
Can you specify or share a page where it shows an example. I am really not understanding the steps necessary!

> That's setting it in process & not at the system or user level, which new processes inherit from.

What do you mean by "it in process" and "not a the system or user level"

@mklement0  

Are you telling me that every command should care the variable like this:

`$env:POWERSHELL_UPDATECHECK="Off" powershell.exe -args argument`

I am not catching the grisp of what you're trying to tell me.

**Comment by mklement0** [comment]
To add to @kilasuit's comment:

It is clear that you need help with the fundamentals, so I've created the following request to improve the [relevant help topic](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_update_notifications):

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10696

---

As an aside (this would be impractical, given that I'm sure that you want to _persistently_ turn off the notifications):

* On an _ad hoc_ (session-specific) basis, i.e. where you set an environment variable _for the current process only_, a syntax such as `$env:POWERSHELL_UPDATECHECK="Off" pwsh ...` _would_ be nice (the POSIX-shell equivalent would be `POWERSHELL_UPDATECHECK=Off pwsh ...`):

*  Adding support for such syntax is the subject of this long-standing feature request:
    * #3316

* Currently, the equivalent in PowerShell would be the following; however, if it is undesired for the environment variable to _linger_ in the caller's session, you'd either have to unconditionally remove it afterwards (`$env:POWERSHELL_UPDATECHECK = $null`) or, preferably, to save and restore any preexisting value:

```powershell
$env:POWERSHELL_UPDATECHECK='Off'
pwsh …
```

**Comment by sdwheeler** [comment]
Here is a great reference that defines what environment variables are: https://wikipedia.org/wiki/Environment_variable

**Comment by gbr000** [comment]
@mklement0 Amazing answer! Thanks in advance,

I will be checking all of that soon. Maybe I was confusing it with the simple Linux/bash system where simply changing a variable could have changed the entire OS. But since it's PowerShell and this is Windows it seems different!

**Comment by gbr000** [comment]
> Here is a great reference that defines what environment variables are: https://wikipedia.org/wiki/Environment_variable
> 
> > **[Environment variable - Wikipedia](https://wikipedia.org/wiki/Environment_variable)**

I know what a variable is since 1996 I was 5 years old and I knew DOS OS which is not prompt, also I know very well Linux variables.

This is the problem here, everyone is saying well set a variable like this:

    $env:VARIABLE = "VALUE"

And I keep telling is not working! There is absolutely no ANSWERS HERE and I will keep opening new threads until the issue is solved.

**Comment by mklement0** [comment]
@gbr000, quoting your previous responses:

> Amazing answer!
> And I keep insisting is not working! There is absolutely no ANSWERS HERE

I'm confused: which one is it?

If the latter: Instead of posting a battle cry that vows eternal opposition, why don't you engage with the answers / information that you've been given, and explain where, in your estimation, they fall short?

**Comment by gbr000** [comment]
> @gbr000, quoting your previous responses:
> 
> > Amazing answer!
> > And I keep insisting is not working! There is absolutely no ANSWERS HERE
> 
> I'm confused: which one is it?
> 
> If the latter: Instead of posting a battle cry that vows eternal opposition, why don't you engage with the answers / information that you've been given, and explain where, in your estimation, they fall short?

Why don't you start to talk like a mature adult developer first?

**Comment by gbr000** [comment]
I will end up this thread in the right way, in the human way of doing things. No answers were provided 3x times, when I ask how to turn off the update check, until this last thread that I open by the time I made this post THE ANSWER WAS NOT PROVIDED, simply because it didn't exist. Now I checked after months, the user `mkelemnt0` added the answer,

that is the answer:

[Environment]::SetEnvironmentVariable('POWERSHELL_UPDATECHECK', 'Off', 'User')

***NOT*** like cynically and persistently devs told me all the time, "well do you want to set variable do this":

$env:VARIABLE = "VALUE"
