### ISSUE TITLE
alpine tar.gz missing from 7.4.0 Release

### ISSUE THREAD

**Issue by zkoppert** [PowerShell/PowerShell#20746]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Observe that the 7.3.0 release had an [alpine asset](https://github.com/PowerShell/PowerShell/releases/download/v7.3.0/powershell-7.3.0-linux-alpine-x64.tar.gz) attached
2. Observe that the 7.4.0 release does not. https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0

### Expected behavior

Expected an alpine release asset on v7.4.0

### Actual behavior

No alpine asset on v7.4.0

### Environment data

N/A

**Comment by rhubarb-geek-nz** [comment]
See https://github.com/orgs/PowerShell/discussions/20700#discussioncomment-7602107

**Comment by zkoppert** [comment]
> The new name for the package is powershell-7.4.0-linux-musl-x64.tar.gz

Thank you for the pointer @rhubarb-geek-nz !! ✨
