### ISSUE TITLE
Remove checking for new version on PowerShell startup

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#20759]
### Summary of the new feature / enhancement

I would like to be able to disable the checking for new versions of PowerShell on startup.

It should not be PowerShell's job to check for updates, the program has no idea if an update can successfully be installed for any given machine. It has no idea if the current user has the rights to update the program.

Other shells, tools and command prompts do not need to make network requests at startup, PowerShell should not need to either. It should operate completely standalone from the network unless a script or command explicitly makes network requests.

The responsibility for updates lies with operating system tools, package managers and system operators.

Let yum, apt, WSUS, WinGet (or even homebrew if you must) manage the updating of software.

### Proposed technical implementation details (optional)

Either remove the functionality or make an environmental configuration setting which by default is do not check for updates.

**Comment by mklement0** [comment]
See the conceptual [about_Update_Notifications](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Update_Notifications) help topic.

**Comment by rhubarb-geek-nz** [comment]
> See the conceptual [about_Update_Notifications](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Update_Notifications) help topic.

Thanks for that.

I will start adding POWERSHELL_UPDATECHECK=Off, along with DOTNET_CLI_TELEMETRY_OPTOUT=true and POWERSHELL_TELEMETRY_OPTOUT=true.

**Comment by rhubarb-geek-nz** [comment]
As per document, set environment variable

```
POWERSHELL_UPDATECHECK=Off
```

**Comment by mklement0** [comment]
Glad to hear it helped, @rhubarb-geek-nz.

Re telemetry, for the PowerShell side of things there's the conceptual [about_Telemetry](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Telemetry) help topic.
