### ISSUE TITLE
System lockdown / WDAC: Use of new audit-only mode prevents use of `[pscustomobject]` literals, behaves as if `ConstrainedLanguage` mode were in effect

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20768]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

If I understand correctly, the [new audit-only mode](https://learn.microsoft.com/en-us/powershell/scripting/learn/application-control?view=powershell-7.4#wdac-policy-auditing) - despite technically reporting `ConstrainedLanguage` via `$ExecutionContext.SessionState.LanguageMode` - is meant to be a _what-if_ constrained mode:

* In effect behave like `FullLanguageMode`, but _log_ operations that _would_ be prevented if `ConstrainedLanguage` mode were actually _enforced_.

However, with respect to `[pscustomobject]` literals that isn't the case: Their use _fails quietly_:

```powershell
#requires -RunAsAdministrator

# Simulate entering audit-only system lockdown
[Environment]::SetEnvironmentVariable("__PSLockdownPolicy", "0x80000008", 'Machine')

# Launch a new process that tries to use a [pscustomobject] literal
Start-Process -Wait pwsh '-NoProfile -C [pscustomobject] @{ foo = 1 } | Out-Host; pause'

# Turn lockdown back off
[Environment]::SetEnvironmentVariable("__PSLockdownPolicy", $null, 'Machine')
```

The **workaround**  is to simply execute `$ExecutionContext.SessionState.LanguageMode = 'FullLanguage'` in a session that was started in audit mode. (Is the ability to do so by design?)
However, even that doesn't work in other use cases: see
* #20785

As an aside:

* Arguably, `[pscustomobject]` literals should also work in true `ConstrainedLanguage` mode, but currently do not - see #20767

### Expected behavior

A `[pscustomobject]` instance should be constructed and output.

### Actual behavior

No output, i.e. the expression _fails quietly_ (but may be _logged_ - haven't verified that).

### Environment data

```powershell
PowerShell 7.4.0 on W11 22H2
```

**Comment by JrndD** [comment]
Thanks. My session defaulted to ConstrainedLanguage after update.

![image](https://github.com/PowerShell/PowerShell/assets/83746585/ba9fdb28-4712-4de4-8f59-d59d66b5963b)
