### ISSUE TITLE
Weird rendering of "<-" since 7.4.0

### ISSUE THREAD

**Issue by dehlong** [PowerShell/PowerShell#20766]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Make your powershell write "<-" with the Cascadia font (I use the nerd font version but those should be the same). Check image to see how it looks.
![2023-11-23_17-44](https://github.com/PowerShell/PowerShell/assets/112163027/508e2db8-13f3-4300-8440-a5887d40b298)

### Expected behavior

```console
Normal look of "<-"
```

### Actual behavior

```console
Badly rendered as on the image
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
I don't think pwsh renders the font. This work is for a terminal emulator.

conhost:
![Screenshot 2023-11-23 221733](https://github.com/PowerShell/PowerShell/assets/78153320/78d52f0c-3031-4e0f-bba7-06e896a853d9)

Windows Terminal:
![Screenshot 2023-11-23 223750](https://github.com/PowerShell/PowerShell/assets/78153320/7f450a86-393b-4234-ab5e-250ed155a0ee)

**Comment by AyushShuklagithub** [comment]
Ohho

**Comment by AyushShuklagithub** [comment]
Looks like I can fix it .. shall I?
