### ISSUE TITLE
Update Readme LTS links

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#20774]
I saw that in the Download table the "Download (LTS)" column still links to PowerShell 7.2 and the "Download (stable)" links to PowerShell 7.4. 
Is that on purpose?
![grafik](https://github.com/PowerShell/PowerShell/assets/54552094/f6656376-f99f-4a28-86f2-e3014cbcaf56)

_Originally posted by @diecknet in https://github.com/PowerShell/PowerShell/discussions/20700#discussioncomment-7629768_

**Comment by apetitjean** [comment]
Normally PS 7.4 should be LTS because it is based on .NET 8.0 LTS. And 7.5 should be the stable one. Right ?
