### ISSUE TITLE
Re-open (in an year): Linux uptime

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#20783]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Relates to [#18469](https://github.com/PowerShell/PowerShell/issues/18469)

Difference between `Get-Uptime` and `/usr/bin/uptime`

```powershell
$ & {
       $f = '\u\p\ d\ \d\a\y\s\,\ h\ \h\o\u\r\s\,\ m\ \m\i\n\u\t\e\s'

       [timespan]::FromSeconds((Get-Content /proc/uptime).Split()[0]).ToString($f)
       uptime -p
       (Get-Uptime).ToString($f)
    }
up 5 days, 5 hours, 53 minutes
up 5 days, 5 hours, 53 minutes
up 1 days, 18 hours, 1 minutes
```

There have been several releases over the year, but the problem has not been resolved.

### Expected behavior

```console
Identical values
```

### Actual behavior

```console
Different values, `Get-Uptime` shows clean timespan without suspend time.
```

### Error details

```console
No errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             ArcoLinux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
> ### Expected behavior
> ```
> Identical values
> ```

The behaviour is as documented, [Get-Uptime](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-uptime?view=powershell-7.4)

```
Get the TimeSpan since last boot.
```

So the tool does not say it caters for any time when the computer is suspended.

The Linux tool [uptime](https://man7.org/linux/man-pages/man1/uptime.1.html) makes no specific claim regarding suspended time either.

However it does have an --since option

```
       -s, --since
              system up since, in yyyy-mm-dd HH:MM:SS format
```

Suggest compare both "since" values

```
$ uptime --since
2023-11-19 15:13:39
$ pwsh -c "Get-Uptime -Since"

Sunday, 19 November 2023 15:13:39
```

**Comment by 237dmitry** [comment]
> Get the TimeSpan since last boot.

Yes, on Windows `Get-Uptime` works as expected, like `/usr/bin/uptime` on Linux:

```powershell
(Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUptime
``

**Comment by rhubarb-geek-nz** [comment]
> `Get-Uptime -Since` returns `datetime`, not `timespan`. How is this better than parsing `/proc/uptime`?

Parsing `/proc/uptime` is not a portable solution.

To get a `timespan`, ask for one.

```
New-TimeSpan -Start (Get-Uptime -Since) -End (Get-Date)
```

**Comment by 237dmitry** [comment]
> New-TimeSpan -Start (Get-Uptime -Since) -End (Get-Date)

I think you did not understand, Ok, picture:

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/a19759df-9b8c-4e27-ab5e-23aeedef9091)

**Comment by rhubarb-geek-nz** [comment]
It's just the presentation.

```
$f = '\u\p\ d\ \d\a\y\s\,\ h\ \h\o\u\r\s\,\ m\ \m\i\n\u\t\e\s'

(New-TimeSpan -Start (Get-Uptime -Since) -End (Get-Date)).ToString($f)
```

**Comment by 237dmitry** [comment]
> It's just the presentation

This is not the point of issue

**Comment by rhubarb-geek-nz** [comment]
> This is not the point of issue

I can only work with that you have posted. I can't tell what you are wanting.

You said they are different, and mine show the same values...

With the code above...

```
up 8 days, 1 hours, 40 minutes
```
And with 

```
$ uptime -p
up 1 week, 1 day, 1 hour, 40 minutes
```
Where I am saying that 1 week+1 day is 8 days.

**Comment by 237dmitry** [comment]
> You said they are different, and mine show the same values...

What Linux are you using? As you see in my environment results are different.

And every closing of the laptop lid distorts the values, since `Get-Uptime` for some reason does not take into account suspend time. There is no such problem on Windows.

**Comment by rhubarb-geek-nz** [comment]
> And every closing of the laptop lid distorts the values, since `Get-Uptime` for some reason does not take into account suspend time. 

You still have not said what you are expecting other than it is not what you want.

Should the returned time include the total time since boot, or only the time that the machine was awake?

**Comment by 237dmitry** [comment]
> Should the returned time include the total time since boot, or only the time that the machine was awake?

As it does `Get-Uptime` on Windows, as it does Linux'es `uptime`, the full timespan since the last OS boot (include suspend or hibernate time)

**Comment by rhubarb-geek-nz** [comment]
> the total timespan since the last OS boot

Getting the difference between the current time and when the system booted will give you that.

And that is what my code did and should be portable across Windows, macOS and Linux.

So it gives you a pure PowerShell workaround that avoids parsing /proc/uptime.

**Comment by rhubarb-geek-nz** [comment]
Can you confirm what the individual values for 

```
Get-Uptime -Since
```

and

```
Get-Date
```

Because if `GetUptime -Since` is not returning the actual date of boot then that is the root of the problem.

The alternative is that `Get-Date` is not giving the current date

Perhaps your system does not have or is not using its real-time clock to get the current date?

**Comment by 237dmitry** [comment]
> Can you confirm what the individual values for

I am tied:

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/034e1488-22b6-4a4d-a4a6-65892eb79f97)

**Comment by rhubarb-geek-nz** [comment]
[GetUptime.cs](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUptime.cs)

So it does not get the time boot directly, it calculates it from a stopwatch.

```
                    case SinceParameterSet:
                        // return Datetime when the system started up
                        WriteObject(DateTime.Now.Subtract(uptime));
                        break;
```

My guess is the stopwatch only counts the time while it is awake.

**Comment by 237dmitry** [comment]
>  So it does not get the time boot directly, it calculates it from a stopwatch

[#18469 answer](https://github.com/PowerShell/PowerShell/issues/18469#issuecomment-1304560999)

**Comment by rhubarb-geek-nz** [comment]
I suggest the workaround of reading /proc/uptime when on Linux as you suggest

```
#!/usr/bin/env pwsh

$f = '\u\p\ d\ \d\a\y\s\,\ h\ \h\o\u\r\s\,\ m\ \m\i\n\u\t\e\s'

(Get-Uptime).ToString($f)

(New-TimeSpan -Start (Get-Uptime -Since) -End (Get-Date)).ToString($f)

(New-TimeSpan -Seconds (Get-Content -Path '/proc/uptime').Split(' ')[0]).ToString($f)

uptime -p
```

```
$ ./Get-HowLongSinceBoot.ps1
up 8 days, 3 hours, 10 minutes
up 8 days, 3 hours, 10 minutes
up 8 days, 3 hours, 10 minutes
up 1 week, 1 day, 3 hours, 10 minutes
```

**Comment by 237dmitry** [comment]
> I suggest the workaround of reading /proc/uptime

It would be better to have a cmdlet that works as expected, in a way that is familiar to any user, so that they don't have to look for workarounds. Then it can be considered cross-platform. Actually, this is the purpose of my reopening this issue.

**Comment by rhubarb-geek-nz** [comment]
> It would be better to have a cmdlet that works as expected

Given what we have found, the fix could be done in the cmdlet and not depend on dotnet changes.

Absolutely true, but in the mean time you need a workaround you can trust, hopefully `$IsLinux` and `/proc/uptime` will provide that.

**Comment by 237dmitry** [comment]
> but in the mean time you need a workaround you can trust

Personally, I don't need either the `Get-Uptime` function or its proxy function. All I want is for `Get-Uptime` to return the correct value. The question is about сmlet and not about how to find a workaround.

**Comment by kilasuit** [comment]
From reading this is an issue on your specific distribution of Linux as @Steve_MSFT already tried to replicate on Ubuntu in your linked issue.

There is in thr linked issue a reference to an issue in the dotnet runtime repo which is still open & should be commented on as the underlying issue seems to be a dotnet one on your specific distro & may even be a distro issue not a dotnet one & requires investigation by dotnet / distro maintainers.

Once fixed there, then in a future release of dotnet or your distro, this should work as expected, so resolving as external for now as this isn't in my view a PowerShell issue.
