### ISSUE TITLE
`Get-Content`: `-Wait` is ignored in combination with `-Head`

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20781]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Currently, combining `-Head` (`-TotalCount`) with `-Wait` causes `-Wait` to be quietly ignored.
By contrast, the combination with `-Tail` works, and while the latter is probably the more common use case, there's no good reason not to allow the former too.

The [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content) don't mention any mutual exclusions for `-Wait` (other than, sensibly, `-Raw`).

At least hypothetically, there could be - conceptually flawed - code out there that relies on `-Wait` being ignored in the presence of `-Head` / `-TotalCount`, though that strikes me as a [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change still worth making.

At the very least, the docs should mention this pitfall

```
Get-Content $PROFILE -Wait -Head 5
```

### Expected behavior

The first 5 lines should print, and the wait stat should be entered.

### Actual behavior

The first 5 lines print, and the command exits, i.e `-Wait` was ignored.

### Environment data

```powershell
PowerShell 7.4.0
```

**Comment by rhubarb-geek-nz** [comment]
> The first 5 lines should print, and the wait stat should be entered.

What is it waiting for?

If there are less than 5 lines in the file will it eventually output the five lines when they are written?

I interpret the arguments as print the first five lines and then finish, but if there are less than five lines wait until they are all there, outputting them as they arrive.

**Comment by mklement0** [comment]
@rhubarb-geek-nz:

> What is it waiting for?

_New content_, which is the very purpose of the `-Wait` switch.

> I interpret the arguments as print the first five lines and then finish

Generally speaking:

* Don't speculate about what the user's intent is, _unless_ there is an _inherent contradiction_ in the specific combination of arguments passed.

* _Quietly ignoring_ arguments makes for a bad user experience ipso facto.

**Comment by rhubarb-geek-nz** [comment]
> * Don't speculate about what the user's intent is, _unless_ there is an _inherent contradiction_ in the specific combination of arguments passed.

The current behaviour is exactly what I would expect, it waits until the number of head lines have been read and then finishes.

If there are less than the number of lines indicated, it prints what it can and waits

As new lines appear it prints them out until the head limit is reached.

**Comment by mklement0** [comment]
**My bad**, @rhubarb-geek-nz (I've hidden my previous comment):

Indeed, your interpretation _matches the existing implementation_.

Given that this behavior isn't obvious (especially considering the symmetry with `-Tail`), I'll open a docs issue to ensure that the behavior is documented.

**Comment by rhubarb-geek-nz** [comment]
Linux "tail" command does have a -f or --follow switch
Linux "head" does not

So there is no symmetry to be expected between head and tail. However wait with head is useful if it is interpreted as wait for head lines to be written

**Comment by mklement0** [comment]
With _separate utilities_ (`tail` vs. `head`), there is indeed _less_ of an  expectation of symmetry.

However, with a _single_ command covering _both use cases_ symmetry is (a) expected and (b) if it doesn't apply, it must be _documented_ - see https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10668#issue-2011250215

**Comment by mklement0** [comment]
As an inconsequential afterthought, @rhubarb-geek-nz:

That the `head` Unix utility with _stdin_ input waits for _as many input lines as specified_ is unrelated to any _waiting_ functionality (such as `-f` and `-F`, only available with `tail`).

**Comment by rhubarb-geek-nz** [comment]
> As an inconsequential afterthought, @rhubarb-geek-nz:
> 
> That the `head` Unix utility with _stdin_ input waits for _as many input lines as specified_ is unrelated to any _waiting_ functionality (such as `-f` and `-F`, only available with `tail`).

Yes, the wait is as a result of a blocking READ(2) rather than clever poll or select.

I note that Get-Content does not work with stdin/pipeline if no file is provided
