### ISSUE TITLE
Breaking Change: JSONC no longer works after 7.4.0

### ISSUE THREAD

**Issue by kyle-ntx** [PowerShell/PowerShell#20782]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Include a comment in json, one example can be seen here:

```
'{
    // A Json comment
    "string": "test"
}' | Test-Json
```

In previous versions of PS this worked as expected. 

### Expected behavior

```console
PS> '{
    // A Json comment
    "string": "test"
}' | Test-Json
True
```

### Actual behavior

```console
PS> '{
    // A Json comment
    "string": "test"
}' | Test-Json

Test-Json: Cannot parse the JSON
```

### Error details

```console
Exception             : 
    Type           : System.Exception
    Message        : Cannot parse the JSON.
    InnerException : 
        Type               : System.Text.Json.JsonReaderException
        LineNumber         : 1
        BytePositionInLine : 4
        Message            : '/' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 1 | BytePositionInLine: 4.
        TargetSite         : 
            Name          : ThrowJsonReaderException
            DeclaringType : System.Text.Json.ThrowHelper, System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
            MemberType    : Method
            Module        : System.Text.Json.dll
        Source             : System.Text.Json
        HResult            : -2146233088
        StackTrace         : 
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
   at Microsoft.PowerShell.Commands.TestJsonCommand.ProcessRecord()
    HResult        : -2146233088
TargetObject          : {
    // A Json comment
    "string": "test"
}
CategoryInfo          : InvalidData: ({
    // A Json comΓÇª "string": "test"
}:String) [Test-Json], Exception
FullyQualifiedErrorId : InvalidJson,Microsoft.PowerShell.Commands.TestJsonCommand
InvocationInfo        : 
    MyCommand        : Test-Json
    ScriptLineNumber : 4
    OffsetInLine     : 6
    HistoryId        : 4
    Line             : }' | Test-Json
    Statement        : Test-Json
    PositionMessage  : At line:4 char:6
                       + }' | Test-Json
                       +      ~~~~~~~~~
    InvocationName   : Test-Json
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/112668616/d21d800a-5d02-4153-80da-73d98a22ee3e)
![image](https://github.com/PowerShell/PowerShell/assets/112668616/0f64d753-3be8-495f-b084-0d8b17b1201b)

**Comment by kyle-ntx** [comment]
It's likely the switch to System.Text.Json that has caused this: #18141

**Comment by rhubarb-geek-nz** [comment]
> Include a comment in json, one example can be seen here:
> 
> ```
> '{
>     // A Json comment
>     "string": "test"
> }' | Test-Json
> ```

Unlike XML, JSON does not have a representation for comments, see [The JavaScript Object Notation (JSON) Data Interchange Format](https://datatracker.ietf.org/doc/html/rfc7159).

What you have there is some JSON with a C++ style comment which is not part of the specification.

There are hundreds of JSON parsers and the only thing they have in common is the JSON specification. When you exchange JSON between different systems you risk parser failures if you don't stick to the spec.

**Comment by Nikolai48Nick** [comment]
README

**Comment by mklement0** [comment]
@kyle-ntx, this _selective_ switch to the `System.Text.Json` APIs is very unfortunate, as it is now at odds with the _lenient_ rules of the JSON.Net APIs that still underly the  [`ConvertFrom-Json`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json) utility:

Specifically, the latter supports:

* unquoted property _names_
* _single-quoted_ property _values_
* a single, extraneous trailing `,`
* C-style comments - both to-end-of-line `//` comments and `/* ... */` block comments.

Thus, there is now a blatant discrepancy between what `ConvertFrom-Json` accepts in practice, and what `Test-Json` flags as invalid - and while their behaviors definitely should align _by default_, there's not even an _opt-in_ for testing _strict_ adherence to the JSON spec. (seemingly _not_ offered by JSON.NET - see https://github.com/PowerShell/PowerShell/issues/10628#issuecomment-535962532)

```powershell
# All of these *succeed* with ConvertFrom-Json, but *fail* with Test-Json
@(
  '{ foo: "bar" }'
  "{ foo: 'bar' }"
  "{ foo: 'bar', }"
  "{ foo: 
    'bar' // bar it is
  }"
  "{ foo: /* et
    tu? */
    'bar'
  }"
) | Convertfrom-Json
```

**Comment by rhubarb-geek-nz** [comment]
While being lenient may sound helpful, in the words of The Fat Controller, it causes confusion and delay.

When passing JSON from one system to another you have no control over the other systems parser and should stick to the strict JSON specification. If you don't then you are basically passing garbage between one system and another and cannot trust any parser to interpret the data as you intended and may silent ignore some fields and accept others.

**Comment by mklement0** [comment]
@rhubarb-geek-nz:

* It is indubitably desirable to have the _option_ of performing a _strict_ check for compliance with the JSON spec.

* Historically, [`Test-Json`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json) used the same APIs as [`ConvertFrom-Json`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json), and the divergence discussed here therefore caused an _unacknowledged and undocumented breaking change_.

* It therefore makes sense for `Test-Json` and `ConvertFrom-Json` to continue to be aligned, with a - yet to be implemented - _opt-in_ to request _strict_ compliance checking - not only via `Test-Json` , but also via `ConvertFrom-Json`.

**Comment by mklement0** [comment]
Case in point: The `Test-Json` help topic still shows the following example as _succeeding_ (which was true up to v7.3.x), which now _fails_:

```powershell
"{'name': 'Ashley', 'age': 25}" | Test-Json
```

**Comment by mklement0** [comment]
@rhubarb-geek-nz,  from what I can tell, the `System.Text.Json` APIs  _fundamentally_ disallow _unquoted_ property names as well as _single-quoted_ property names and values (there's nothing in [`System.Text.Json.JsonSerializerOptions`](https://learn.microsoft.com/en-US/dotnet/api/System.Text.Json.JsonSerializerOptions) that suggests otherwise), so at least using these APIs _directly_ won't work for emulating what `ConvertFrom-Json` accepts.

**Comment by rhubarb-geek-nz** [comment]
You might have to bite the bullet and have the ConvertFrom-Json Cmdlet supporting both parsers, where a switch selects which one to use.

**Comment by kyle-ntx** [comment]
> Unlike XML, JSON does not have a representation for comments, see [The JavaScript Object Notation (JSON) Data Interchange Format](https://datatracker.ietf.org/doc/html/rfc7159).

While this is true, it does appear that [JSON with Comments](https://code.visualstudio.com/docs/languages/json#_json-with-comments) worked before, and does not now, and the introduction of this change has broken scripts which we have relied on for quite some time. 

I do agree that supporting things that are not part of a standard is fraught with danger, however, introducing a breaking change as part of a minor update and with out warning is not common practice and, if done at all, should be done with some forewarning.

**Comment by mklement0** [comment]
@IISResetMe: [As noted](https://github.com/PowerShell/PowerShell/issues/20782#issuecomment-1827053464), this isn't sufficient: what `System.Text.Json` _fundamentally_ lacks support for  - unless I'm missing something - are _unquoted_ property names and _single-quoted_ property names and string values.

That is, it won't be able to validate something `"{ foo: 'bar' }"`, which `ConvertFrom-Json` happily accepts.

**Comment by mklement0** [comment]
See also:

* https://github.com/PowerShell/PowerShell/issues/21338#issuecomment-1994650054

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  System.Text.Json.Node allows for options that would allow for comments.  We believe that the default behavior should adhere to the standards (enabling portable JSON), but have a new `-Option` parameter which takes an array of options (currently would support `Comments` and `TrailingComma`).

**Comment by mklement0** [comment]
@SteveL-MSFT, the proposed fix:

* doesn't acknowledge the fundamentally breaking change that occurred - see also: #21338
* even with the opt-in doesn't fully restore the previous functionality, as System.Text.Json fundamentally does not support _single-quoted_ tokens, and also doesn't support _bareword properties_.

**Comment by o-l-a-v** [comment]
Will this come to 7.4 or do we have to wait for 7.5?

**Comment by mklement0** [comment]
I'm inferring from how the linked PR (#23817) is labeled that it'll land in 7.5

**Comment by o-l-a-v** [comment]
I read that too. I'd consider this a fix more than a breaking change though, which is why I hoped it could trickle down to 7.4 too.

* Existing scripts won't stop working if `-Option` was not specified.
* The breaking change from \< 7.4 to 7.4 has already happened, ref this issue.
* JSON with comments works with `ConvertFrom-Json`, but not with `Test-Json` doesn't.
