### ISSUE TITLE
Constrained Language Audit mode breaks az.resources

### ISSUE THREAD

**Issue by lansalot** [PowerShell/PowerShell#20785]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Previously, in 7.3.9, I could use the Get-AzADGroup cmdlet from az.resources. This now fails in 7.4.0, logging the following warning to the event log, apparently due to Constrained Language mode. I have read the notes at https://learn.microsoft.com/en-us/powershell/scripting/learn/application-control?view=powershell-7.4#wdac-policy-enforcement but my understanding is that this is in warning-only mode, so not sure why this breaks.

Confirm 7.4.0 works fine where WDAC doesn't get involved. In both cases, $ExecutionContext.SessionState.LanguageMode reads as "FullLanguage" but with WDAC, we get the below error.

Can also confirm that rolling back to 7.3.9, Get-AZADGroup works fine again.

### Expected behavior

```console
PS > get-azadgroup -displayname azurevirtualdesktop

DisplayName         Id                 MailNickname Description
-----------         --                 ------------ -----------
AzureVirtualDesktop 4b5fc7cb.....745ff 61b71d76-7   Azure Virtual Desktop users
```

### Actual behavior

```console
PowerShell 7.4.0
[Constrained Language AUDIT Mode : No Restrictions]
PS > ipmo az.resources

PS> get-azadgroup -DisplayName azurevirtualdesktop
ParentContainsErrorRecordException: ....\Documents\PowerShell\Modules\az.resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1:3532
Line |
3532 |          $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
     | produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object."

PS > $ExecutionContext.SessionState.LanguageMode = 'FullLanguage'

PS > get-azadgroup -DisplayName azurevirtualdesktop
ParentContainsErrorRecordException: ....\Documents\PowerShell\Modules\az.resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1:3532
Line |
3532 |          $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvoc …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
     | produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object."
```
```


### Error details

```console
From PowershellCore/Operational:

Error Message = Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."
Fully Qualified Error ID = RuntimeException


Context:
        Severity = Warning
        Host Name = ConsoleHost
        Host Version = 7.4.0
        Host ID = e0d32791-7e3c-44a6-bbb3-c46817f36700
        Host Application = C:\Program Files\PowerShell\7\pwsh.dll
        Engine Version = 7.4.0
        Runspace ID = 33297d30-ce4f-4807-ba84-84f0aa1b96de
        Pipeline ID = 17
        Command Name = 
        Command Type = 
        Script Name = ....\Documents\PowerShell\Modules\az.resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1
        Command Path = 
        Sequence Number = 10
        Connected User = 
        Shell ID = Microsoft.PowerShell


User Data:
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lansalot** [comment]
Also, it appears that having failed once, it "ejects" the Get-AZADGroup command from my session?

```
Get-Command: ...\Documents\PowerShell\Modules\Az.Resources\6.12.0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1:3528:20
Line |
3528 |          $cmdInfo = Get-Command -Name $mapping[$parameterSet]
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Az.MSGraph.custom\Get-AzADGroup' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name,   
     | or if a path was included, verify that the path is correct and try again.
[DBG]: PS C:\github\Projects> get-azadgroup
The command get-azadgroup is part of Azure PowerShell module "Az.Resources" and it is not installed. Run "Install-Module Az.Resources" to install it.
The intelligent recommendation feature is in preview. Help us improve it by sharing your experience: https://go.microsoft.com/fwlink/?linkid=2202436
get-azadgroup: The term 'get-azadgroup' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[DBG]: PS > get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.12.0                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     0.2.0                 PowerShellEditorServices.Commands   {Clear-Host, ConvertFrom-ScriptExtent, ConvertTo-ScriptExtent, Find-Ast…}
Binary     0.2.0                 PowerShellEditorServices.VSCode     {Close-VSCodeHtmlContentView, New-VSCodeHtmlContentView, Set-VSCodeHtmlContentView, Show-VSCodeHtmlCo…Script     2.3.4                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandle…
[DBG]: PS C:\github\Projects> get-command -module az.resources get-azadgroup

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-AzADGroup                                      6.12.0     Az.Resources
```

**Comment by lansalot** [comment]
> Related:
> 
> * [System lockdown / WDAC: Use of new audit-only mode prevents use of `[pscustomobject]` literals, behaves as if `ConstrainedLanguage` mode were in effect #20768](https://github.com/PowerShell/PowerShell/issues/20768)

Thanks, I did see that in research - but I noted that the OP stated setting language mode to "FullLanguage" was a workaround. In my case above, I had FullLanguage, but problem still exists.

**Comment by lansalot** [comment]
Just to follow up on this, I'm now hours deep into fighting an issue where for whatever reason, BICEP is hanging when called from New-AZDeployment in 7.3.9 core, resulting in no output arm template and a hung process.

Works fine in PS5.1 and this has all come about since I had to roll back to 7.3.9. Procmon shows nothing useful, it doesn't even try to write a template file yet bicep works fine when called from the command line. Have re-installed pscore, bicep, az cli, dotnet core, you name it.

I wish I could bill someone for the hours I've wasted trying to fix this.

**Comment by ChristopherGLewis** [comment]
Confirmed that this is a critical error in PowerShell 7.4.0.  The Az Module is unusable and anything with [PSCustomObject] is unusable.  

This is insane that this made it through testing.

**Comment by anthony-c-martin** [comment]
@lansalot could you raise an issue for the behavior you're seeing with `New-AZDeployment` in the Bicep repo (https://github.com/Azure/bicep/issues)? It would be good to get some detailed repro steps, and dig into the "stuck process" behavior you're seeing in more detail.

**Comment by lansalot** [comment]
@anthony-c-martin I was going to give some repro steps, but had already pored through the logs to no avail, procmon, everything. Before I do that, would you have any suggestions exactly what to enable that might show the hang? I couldn't find the actual call to bicep.exe either for that matter..

**Comment by anthony-c-martin** [comment]
If you run with the `-Verbose` flag, you should see something like the following just before it attempts to call Bicep:
```
VERBOSE: Using Bicep v0.22.6
VERBOSE: Calling Bicep with arguments: build "/Users/ant/Code/bicep/src/vscode-bicep/src/test/e2e/examples/000/empty/main.bicep" --outdir "/var/folders/rg/wdkg_qq143x818th8s03s5080000gn/T/71cd4a40-cd9b-4c74-ac2e-dfe1854877b0"
```

**Comment by anthony-c-martin** [comment]
> However, getting a bit off-topic for this particular issue so I'm happy to take it up on the bicep repo instead.

@lansalot does https://github.com/Azure/azure-powershell/issues/23685 look like the same issue? If not, please could you make sure you've reported the separate issue under https://github.com/Azure/azure-powershell/issues?

**Comment by lansalot** [comment]
Thanks for fixing - I presume, no Release as yet? Is there a schedule for that?

Talking of which, am a little surprised that 7.4.0 wasn't pulled given how much trouble this has caused?

**Comment by nicpenning** [comment]
FYI - This also affects RSAT tools (Get-ADUser user75, Get-AdComputer computer75.. etc).
```
ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced
an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."
```

**Comment by TiTi** [comment]
Rollbacking to Powershell core 7.3.10 temporarily so that Get-AzADGroup work again...

**Comment by GregDSmith** [comment]
Another FYI it appears that the bug also affects the SqlServer Module - Invoke-Sqlcmd - I get the same error: "ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command
name, a script block, or a CommandInfo object."
