### ISSUE TITLE
Get-TenantAllowBlockListItems fails with url with hash character

### ISSUE THREAD

**Issue by katlim-br** [PowerShell/PowerShell#20790]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

$url = "sub.domain.com/folder/#ggfdggdg="
Get-TenantAllowBlockListItems -ListType Url -Entry $url

This command fails with this error: |System.Exception|Error sending HTTP request

### Expected behavior

```console
The url argument should be accepted and the command executed
```

### Actual behavior

```console
Error: "System.Exception|Error sending HTTP request"
```

### Error details

I suspect the error is when pwsh is trying to build the HTTP request.

The command New-TenantAllowBlockListItems accepts the value without issues.

### Environment data

```powershell
PowerShell 7.3.9
```

### Visuals

<img width="648" alt="image" src="https://github.com/PowerShell/PowerShell/assets/93484005/6dd34b20-3b42-448b-89f6-075b3dd070eb">

**Comment by mklement0** [comment]
Note that the cmdlet in question is part of the [`ExchangePowerShell` module](https://learn.microsoft.com/en-us/powershell/module/exchange/?view=exchange-ps) and therefore not maintained in this repo.

As for the specific problem, let me offer a _guess_: your `$url` value may be missing a protocol specifier such as `https://`

**Comment by katlim-br** [comment]
I'll post the issue there then.

Nope, I tried, and the error persists.
