### ISSUE TITLE
Documented $PsStyle "OutputRending" property "cannot be found on this object."

### ISSUE THREAD

**Issue by MarArMar** [PowerShell/PowerShell#20801]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run

```
Write-Host "Starting script"
Write-Host $PSVersionTable.PSVersion

$PsStyle.OutputRending = "Ansi"
exit 0
```
Property is documented : 
https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.psstyle.outputrendering?view=powershellsdk-7.3.0
https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.outputrendering?view=powershellsdk-7.3.0

### Expected behavior

```console
Working, property found
```

### Actual behavior

```console
 |  $PsStyle.OutputRending = "Ansi"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'OutputRending' cannot be found on this object. Verify that the property exists and can be set.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
You have  a typo: `$PsStyle.OutputRending` -> `$PsStyle.OutputRendering`

**Comment by MarArMar** [comment]
Ok indeed it worked, my bad
