### ISSUE TITLE
Cannot create a file if name contains '[' or ']' character (Windows 11)

### ISSUE THREAD

**Issue by UselessGuru** [PowerShell/PowerShell#20809]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Cannot create a file if name contains '[' or ']' character.

```
$Path = "MyFilename[1].txt"
"Text" | Out-File -FilePath $Path
```

These characters are allowed characters.
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
It is also possible to create such filenames in Explorer or in CMD shell.

Same issue also exists with legacy powershell 5.1

### Expected behavior

```console
'Text' written to file 'MyFilename[1].txt'
```

### Actual behavior

```console
Cannot perform operation because the wildcard path MyFilename[1].txt did not resolve to a file.
[C] Continue [I] Silently Continue [B] Break [S] Suspend [?] Help (default is "Continue"):
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
`Out-file -LiteralPath $Path`

**Comment by mklement0** [comment]
The `-Path` / `-FilePath` parameter of provider (file-handling) cmdlets (which the first _positional_ argument implicitly binds to), expects _wildcard_ expressions.

Because PowerShell's wildcard language also supports expressions such as `[a-z]`, paths meant to be _literal_ ones are misinterpreted if they happen to contain `[` chars.

To pass a literal path as such, use the `-LiteralPath` parameter explicitly.

**Comment by UselessGuru** [comment]
Learned something again ;-)
