### ISSUE TITLE
Subtracting and Dividing Bools unexpected type conversion

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#20817]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

While writing my last bug report about multiplying bools (#20816) I noticed a strange type error when dividing a bool by something. It causes an unexpected type conversion to int32.

I don't know why one would want to divide by a bool (esp. $false is 0 and dividing by 0 obv. fails), but I can see usages where one would divide a bool by something and expect another bool as a result.

writing `$isEnabled /= ($something+$somethingElse)` is basically the same as:
```
$isEnabled = ($isEnabled ? 1 : 0) / ($something+$somethingElse)
```

ok, I admit it's mostly useless, but the returned type is still unexpected...

Edit: This error also occurs when subtracting from a bool, which is a bit more useful than dividing, as it (if it would return a bool) is basically XOR.

### Expected behavior

```console
PS> $isEnabled = $true
PS> $isEnabled /= $true
PS> $isEnabled
True

PS> $isEnabled = $false
PS> $isEnabled /= $true
PS> $isEnabled
False

PS> $isEnabled /= $false
RuntimeException: Attempted to divide by zero.

PS> [bool]$isEnabled = $true
PS> $isEnabled /= $true
PS> $isEnabled
True

PS> [bool]$isEnabled = $false
PS> $isEnabled /= $true
PS> $isEnabled
False
```

### Actual behavior

```console
PS> $isEnabled = $true
PS> $isEnabled /= $true
PS> $isEnabled
1

PS> $isEnabled = $false
PS> $isEnabled /= $true
PS> $isEnabled
0

PS> $isEnabled /= $false
RuntimeException: Attempted to divide by zero.


PS> [bool]$isEnabled = $true
PS> $isEnabled /= $true
PS> $isEnabled
True

PS> [bool]$isEnabled = $false
PS> $isEnabled /= $true
PS> $isEnabled
False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
`[bool]` instances are consistently treated as `[int]` in _arithmetic_ operations - `$true` becomes `1`, `$false` becomes `0`, _except_ - surprisingly - in multiplication (`*`).

For _logical_ operations, there are dedicated operators.

Leaving the merits of what you're proposing aside: The current behavior is long-established and changing it would amount to an unacceptable breaking change.

**Comment by agowa** [comment]
The issue is in what the final variable gets set to. It for some reason changes type afterwards from bool to int. The final variable should still be a bool. Basically the same as when initialized with static type declaration.

**Comment by jhoneill** [comment]
> The issue is in what the final variable gets set to. It for some reason changes type afterwards from bool to int. _The final variable should still be a bool._ Basically the same as when initialized with static type declaration.

That's your mistake, the operators will convert the things either side of them  to the type (or more strictly one of the types) they work with
So 
```
> $true -split "u"
Tr
e
```
or 
```
> 3 * $true
3
```
With strings it gets strange
```
>  "33" + 44
3344
> 33 + "44"
77
```
The type of the left operand is the type of the result 
```
$x = 1
$x = "one"
```
Does not give an error. $x is of type Object and can hold a string object or an int, and merrily swap between them 
```
$x = $true
$x = 1
```
`[int]` $x puts a type conversion attribute onto X and says convert anything going into X becomes an int on the way
```
> [int]$x=1
> $x="one"
MetadataError: Cannot convert value "one" to type "System.Int32". Error: "The input string 'one' was not in a correct format." 
```
Note the text of the error, it is not that "one" is NOT an int32, it is that won't cast to one. 

So in your example 
```
> $isEnabled = $true
> $isEnabled / $true
```
Returns 1, and 1 is stored. 
```
[bool] $isEnabled = $true
$isEnabled / $true
```
Still returns 1 and 
```
 $isEnabled = 1
 $isEnabled
``` 
Now gives you true. 

The ++ / -- / += / -= / *= / /=  operators actually create a new variable. 
 
function demo {
$x ++ 
$a[1]=4
"during x is $x  A is $a" 
}
$x = 1
$a = @(0,1,2)
"before x is $x  A is $a" 
demo
"after x is $x  A is $a" 
 
The _assignment_ the demo scope (++ is just a shorter way to write X = X +1) made a new X which left the X in the parent scope untouched, but changing a member of $a changed the one in the parent scope. 

> Edit: And just fyi, I didn't open this ticket because I wanted something changed. I mainly opened it for documentation reasons as I didn't find anything about this quirk being considered before. Basically until now it wasn't specified one way or another. The goal of this ticket for me is to specify this properly (one way or another).

Which is fair enough - I can't go to it in the product documentation but what I've written above is explained pretty early in any training on PowerShell. People who've learned to program in anything with strong typing have a really hard time with these ideas, where those without any prior knowledge can't imagine anything else.

**Comment by kilasuit** [comment]
As this relates to a user expectation & this can be fixed with docs am resolving this as `Resoultion-External` & with `PowerShell-Docs Needed` labels especially as there is already an open issue for creating a doc for this

**Comment by agowa** [comment]
@kilasuit could you please also link the other issue that is already open regarding the docs?

**Comment by kilasuit** [comment]
> @kilasuit could you please also link the other issue that is already open regarding the docs?

@agowa - Please see the issue in the docs repo that @mklement0 mentioned in his comment above

**Comment by mklement0** [comment]
A help topic has since been created: [about_Type_Conversion](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_type_conversion), so the `PowerShell-Docs needed` label can be removed now.
