### ISSUE TITLE
7.4.0 File redirection with native executable no longer appends new line

### ISSUE THREAD

**Issue by twinter-amosfivesix** [PowerShell/PowerShell#20811]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

According to [about_Redirection](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.4):
> Using the redirection operator with a file target is functionally equivalent to piping to Out-File with no extra parameters.

The documentation for [Out-File](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-7.4) `-NoNewLine` says:
> No newline is added after the last output string.

Which means `Out-File` does normally add a newline. And this is what you see in PowerShell 7.3.10. If the output does not end in a newline, `Out-File` and file redirection add a newline. **But in PowerShell 7.4.0, with file redirection that newline is no longer added.** 

To make this easy to repro you'll want a native executable that outputs character data but no newline (LF or CR/LF) _at the end_. Here's a C# program that does that. You *don't have to* use this program to repro the problem. It just helps.
```
namespace Example;

internal class Program
{
    static void Main()
    {
        Console.Write("Hello"); // Note that it's not WriteLine()
    }
}
```

This appears to be related to the PR: https://github.com/PowerShell/PowerShell/pull/17857 by @SeeminglyScience that was added in preview 4

Appears to be related to #20747 and #20808.

### Expected behavior

```console
# See "Steps to reproduce" for source code for Hello.exe

PS> .\Hello.exe >x.txt

PS> (Get-Content x.txt -Raw).EndsWith([System.Environment]::NewLine)
True
```

### Actual behavior

```console
# See "Steps to reproduce" for source code for Hello.exe

PS> .\Hello.exe >x.txt

PS> (Get-Content x.txt -Raw).EndsWith([System.Environment]::NewLine)
False
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### 7.3.10
![image](https://github.com/PowerShell/PowerShell/assets/66026737/459ff3b6-8bdd-4a09-b938-881339997748)

### 7.4.0
![image](https://github.com/PowerShell/PowerShell/assets/66026737/adb8fc2a-e7a0-4e18-95cc-490823b78d7a)

**Comment by rhubarb-geek-nz** [comment]
I do remember discussions about piping between native programs so that if the pipe is not between PowerShell cmdlets then the native byte stream pipe would be used to maintain the fidelity between native programs.

This would be the same case, where piping out to a file is a case of opening a file descriptor and using it as stdout  and not interfering.

```
$ cat hello.c
#include <unistd.h>

int main()
{
        write(1,"hello",5);
        return 0;
}
$ cc hello.c
$ pwsh
PowerShell 7.4.0
PS> ./a.out > hello1
PS> ./a.out | Set-Content -Path hello2
PS> ls -l
total 20
-rwxr-xr-x 1 bythesea bythesea 7980 Nov 29 18:52 a.out
-rw-r--r-- 1 bythesea bythesea   68 Nov 29 18:52 hello.c
-rw-r--r-- 1 bythesea bythesea    5 Nov 29 18:52 hello1
-rw-r--r-- 1 bythesea bythesea    6 Nov 29 18:53 hello2
```

Writing stdout to a file gives 5 bytes
Piping through Set-Content gives 6 bytes

**Comment by twinter-amosfivesix** [comment]
> I'd say that's by design - though the docs need to catch up.

I guess I can see that. Though it seems to me that it should be listed as a [breaking change](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-74?view=powershell-7.4#breaking-changes).

**Comment by twinter-amosfivesix** [comment]
I put in a [documentation issue](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10677) saying this should be listed as a breaking change. We'll see if this issue or that issue wins. 😄

**Comment by mklement0** [comment]
@twinter-amosfivesix, thanks for opening the docs issue.

Yes, it's definitely a breaking change and definitely also an intentional - and long-awaited - one (finally makes PowerShell act like other shells with respect to redirections and between-utilities piping, which improves both performance and prevents inadvertent modification); I've updated my original comment with a link to [the relevant part of `about_Redirection`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Redirection#example-7-redirecting-binary-data-from-a-native-command)

**Comment by twinter-amosfivesix** [comment]
@mklement0, do you think I should open a doc issue for about_Redirection, because, as you say, it's no longer correct?

**Comment by mklement0** [comment]
@twinter-amosfivesix, it isn't incorrect per se, but the information is somewhat buried in the context of an _example_, and the introductory section mentions `Out-File` without pointing that `>` now acts differently with _external programs_, specifically.

I've just opened a docs issue for `Out-File` to mention that `>` is no longer an effective alias with respect to external programs: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10678

If you're up for it, please open an issue for `about_Redirection` that asks for that fact to be mentioned too, and to move the description of the raw-byte behavior out of an example.

**Comment by twinter-amosfivesix** [comment]
Look like everyone thinks it's just a doc change, which looks like it was done, so closing.
