### ISSUE TITLE
Strange copy/paste behavior in Powershell 7

### ISSUE THREAD

**Issue by mcdonamw** [PowerShell/PowerShell#20824]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Per discussion #20507, there is an issue pasting Powershell code when it is formatted with tab characters when pasting via right-click or Edit > Paste vs ctrl+v shortcut.  

The console interprets those tab characters as an opportunity to predict/autocomplete text, whereas the ctrl+v does not. This was explained as expected behavior.  

However, the Powershell console attempting to provide autocompletions for the hashtable I am currently writing, with the suggestions being hashtable keys I've already written **is not expected behavior** and so this bug report is being created.

Here is an example, more simplified than the discussion.  

```
$var1 = [PSCustomObject]@{
	'key1' = 'value1'
	'key2' = 'value2'
	'key3' = 'value3'
	'key4' = 'value4'
} 

```

### Expected behavior

Pasted format should look like:

```
PS C:\> $var1 = [PSCustomObject]@{
>>     'key1' = 'value1'
>>     'key2' = 'value2'
>>     'key3' = 'value3'
>>     'key4' = 'value4'
>>}

```

### Actual behavior

Pasted content instead duplicates some of the previous hash-table keys on the next line.

Note:  Interestingly, in this case it autocompletes the first key on the second line whereas in the discussion example several lines were autocompleted.

```
PowerShell 7.4.0
PS C:\> $var1 = [PSCustomObject]@{
>> 'key1' = 'value1'
>> key1'key2' = 'value2'
>> 'key3' = 'value3'
>> 'key4' = 'value4'
>>}

```

### Error details

```console
Not applicable
```

### Environment data

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://1drv.ms/v/s!AgLKGMVNs4_YhP5Oc8PQHsYxkcEPkQ?e=SXGJDq

**Comment by mklement0** [comment]
Your symptom is explained by this - very old and sadly still unresolved - `PSReadLine` issue:

* https://github.com/PowerShell/PSReadLine/issues/579

With right-click pasting, each line of your code is submitted _individually_, which causes the problem.

Pasting with <kbd>Ctrl+V</kbd> avoids this problem on Windows, but on Unix-like platforms that doesn't help either.

**Comment by mcdonamw** [comment]
Looks like they closed the issue related to this. I guess this will never be fixed?

With that said, I'll have to retest, but I'm fairly sure this is not an issue in Windows Powershell. What are they doing that Powershell 7 can't?

**Comment by mcdonamw** [comment]
I gotcha. Thanks as always!
