### ISSUE TITLE
Want to add tmux functionality

### ISSUE THREAD

**Issue by huajien** [PowerShell/PowerShell#20836]
### Summary of the new feature / enhancement

Can you add tmux functions to make the operation more comfortable

**Comment by rhubarb-geek-nz** [comment]
Are you referring to this [tmux](https://github.com/tmux/tmux) ?

What are you expecting in terms of PowerShell support?

I suggest this could be done as an independent and optional PowerShell module, it does not need to be part of the main PowerShell project.

I see that tmux is a single binary application so all operations would be simply calling the /usr/local/bin/tmux program.

**Comment by jantari** [comment]
If you want tmux functionality, you should just use tmux.

**Comment by psmux** [comment]
This exists now — [psmux](https://github.com/marlocarlo/psmux) is a native Windows terminal multiplexer that provides tmux functionality for PowerShell.

psmux maintainer here. To address @rhubarb-geek-nz's suggestion that this could be done as an independent module: that's exactly what psmux is. It's a standalone Rust binary (~4.5MB, zero runtime dependencies) that runs natively on Windows via ConPTY.

### What it provides

**Session management (detach/reattach):**
```powershell
tmux new-session -s work        # create named session
tmux detach                     # detach (Ctrl+B, d)
tmux attach -t work             # reattach from any terminal
tmux list-sessions              # see all running sessions
```

**Split panes:**
```powershell
tmux split-window -h            # horizontal split
tmux split-window -v            # vertical split
tmux resize-pane -R 10          # resize
```

**Window management, copy mode, mouse support, customizable status bar, vim key bindings, `.tmux.conf` compatibility** — 76 tmux-compatible commands total.

### Why psmux vs PowerShell background jobs

PowerShell `Start-Job` / `ThreadJob` run code in the background but give you no interactive terminal. You can't see output in real time, can't type into them, and can't detach/reattach. psmux gives you full interactive pseudo-terminals that persist independently of the terminal window.

| Feature | Start-Job | psmux |
|---------|-----------|-------|
| Interactive terminal | No | Yes |
| Detach and reattach | No | Yes |
| Split panes | No | Yes |
| Survives terminal close | No | Yes |
| Real-time output | Receive-Job polling | Direct |
| Mouse support | No | Yes |

### Install

```powershell
winget install psmux
```

Also available via `cargo install psmux`, `scoop install psmux`, `choco install psmux`.

Ships as `psmux.exe`, `pmux.exe`, and `tmux.exe` — the tmux alias means existing tmux scripts and tools (tmuxifier, tmuxp, etc.) work on Windows with zero modification.

Current release: [v0.4.10](https://github.com/marlocarlo/psmux/releases/tag/v0.4.10) — MIT licensed.

To @jantari's point — "just use tmux" is now actually possible on native Windows without WSL or Cygwin.
