### ISSUE TITLE
Conflict package version with Microsoft.Entityframework

### ISSUE THREAD

**Issue by fqh4** [PowerShell/PowerShell#20843]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

im getting a conflict error trying to update this packages on my project:

<img width="958" alt="image" src="https://github.com/PowerShell/PowerShell/assets/125499340/39dd2a05-7fcb-4058-a3fc-ec1e39188542">

NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0-2.final directly to project Agent.Common to resolve this issue. 
-> Microsoft.PowerShell.SDK 7.4.0 -> Microsoft.PowerShell.Commands.Utility 7.4.0 -> Microsoft.CodeAnalysis.CSharp 4.8.0-2.final -> Microsoft.CodeAnalysis.Common (= 4.8.0-2.final) 
-> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).

### Expected behavior

```console
ok
```

### Actual behavior

```console
NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0-2.final directly to project Agent.Common to resolve this issue. 
-> Microsoft.PowerShell.SDK 7.4.0 -> Microsoft.PowerShell.Commands.Utility 7.4.0 -> Microsoft.CodeAnalysis.CSharp 4.8.0-2.final -> Microsoft.CodeAnalysis.Common (= 4.8.0-2.final) 
-> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Common (= 4.5.0).
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by rhubarb-geek-nz** [comment]
I set `Microsoft.CodeAnalysis.CSharp.Workspaces` to` 4.8.0` rather than leave it at [4.5.0](url)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.0" />
  </ItemGroup>

</Project>
```

**Comment by fqh4** [comment]
THANKS!!!
