### ISSUE TITLE
Export-ModuleMember tab complete for parameters doesn't work

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2085]
## Steps to reproduce

```powershell
export-modulemember -a<tab>
export-modulemember -alia<tab>
export-modulemember -f<tab>
export-modulemember -func<tab>
```

## Expected behavior

-alias and -function tab complete
## Actual behavior

doesn't complete the parameter name
## Environment data
```
Name                           Value

---

PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.9
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
CLRVersion
```
\<repros on Win10 Anniversary\>

**Comment by SteveL-MSFT** [comment]
Reported via https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/15457641-wmf5-1-code-completion-fails-to-complete-a-para

**Comment by joeyaiello** [comment]
Oddly enough, `Export-ModuleMember -Alias -f<tab>` completes `-Function`. It's only on the first parameter that this fails. 

This may be related to #1265.

**Comment by ThomasNieto** [comment]
Is this still an issue? I wasn't able to reproduce with 7.1 preview 5.

**Comment by iSazonov** [comment]
I don't the issue with latest builds too.
