### ISSUE TITLE
`Get-Help` fails with script files whose base name is just a single character

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20862]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This bug dates back to Windows PowerShell and seems to affect macOS and Windows (except WSL) only.

Note that 2+-character base names work fine, and that a single-character _function_ name works fine too.

```powershell
# Create test script
'[CmdletBinding()] param($Foo) $PSBoundParameters' > t.ps1

# Try to invoke help
./t.ps1 -?
Get-Help ./t.ps1
```

### Expected behavior

```console
t.ps1 [[-Foo] <Object>] [<CommonParameters>]

t.ps1 [[-Foo] <Object>] [<CommonParameters>]
```

### Actual behavior

```console
Get-Help: The splatting operator '@' cannot be used to reference variables in an expression. '@PSBoundParameters' can be used only as an argument to a command. To reference variables in an
expression use '$PSBoundParameters'.
Get-Help: The splatting operator '@' cannot be used to reference variables in an expression. '@PSBoundParameters' can be used only as an argument to a command. To reference variables in an
expression use '$PSBoundParameters'.
```

### Environment data

```powershell
PowerShell 7.4.0 on macOS and Windows
```

**Comment by mklement0** [comment]
Thanks, @237dmitry - that was just a typo in the initial post. `t.ps1` is the name needed to reproduce the symptom. Please hide your comment, now that this has been resolved, and I will hide mine.

**Comment by 237dmitry** [comment]
This works (tested on Windows)

![Screenshot 2023-12-07 235158](https://github.com/PowerShell/PowerShell/assets/78153320/6964a150-2350-488b-9d0c-cbb2b7307fca)

**Comment by mklement0** [comment]
Thanks, @237dmitry - I think you meant _Linux_, where the problem indeed doesn't occur - I've updated the initial post.

Given that you say _Windows_, I assume you're running _via WSL_, which makes your _effective_ environment a _Linux_ one.
In general I suggest making it clear when you're talking about Windows _in the context of WSL_.

**Comment by 237dmitry** [comment]
> Given that you say Windows, I assume you're running via WSL, which makes your effective environment a Linux one.

No, I have not installed WSL at all. Linux on other laptops.

**Comment by mklement0** [comment]
Thanks, @237dmitry.

Sorry for the false alarm: Turns out there was something in my macOS and Windows environments that caused this, and I have yet to figure out the exact cause, but if it turns out there's a real problem, it will likely have to be framed very differently, so I am closing this.

**Comment by mklement0** [comment]
@237dmitry: Please see:
* #20868
