### ISSUE TITLE
Any way to backport the Get-FileHash Cmdlet from ps7 to ps5.1

### ISSUE THREAD

**Issue by blackops786187** [PowerShell/PowerShell#20870]
### Summary of the new feature / enhancement

I have noticed a significant performance increase when utiilsing the Get-FileHash from ps7 compared to ps5. Deploying powershell 7 in our org is not possible at this point in time but i would like to use the faster version on ps5. 

I suspect that backporting it will not be feasible for you nor appropriate. if so, are you able to suggest a way for us to  utilise the ps7 cmdlet whislt in ps5 to gain the performance benifit without needing ps7 installed. or is this not possible?

Aplogies if i've posted this in the wrong place.

**Comment by rhubarb-geek-nz** [comment]
The source is [here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs)

You could try and make a net482 or netstandard2.0 cmdlet out of it.
