### ISSUE TITLE
https://aka.ms/pwsh-buildinfo-lts is wrong with the release of 7.4

### ISSUE THREAD

**Issue by sassdawe** [PowerShell/PowerShell#20873]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Execute `(Invoke-RestMethod -UseBasicParsing -Uri https://aka.ms/pwsh-buildinfo-lts). ReleaseTag`

### Expected behavior

```console
PS> (Invoke-RestMethod -UseBasicParsing -Uri https://aka.ms/pwsh-buildinfo-lts).ReleaseTag
v7.4.0
```

### Actual behavior

```console
PS> (Invoke-RestMethod -UseBasicParsing -Uri https://aka.ms/pwsh-buildinfo-lts).ReleaseTag
v7.2.17
```

### Error details

```console
The [PowerShell 7.4 General Availability](https://devblogs.microsoft.com/powershell/powershell-7-4-general-availability/) posts say v7.4 is LTS, so I'd expect that the LTS build info would return that version as that is the latest LTS version not v7.2.17.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.17
PSEdition                      Core
GitCommitId                    7.2.17
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
@sassdawe Thanks for reporting the issue! The LTS buildInfo was corrected. There must be a bug in our releasing pipeline which we will track down.
