### ISSUE TITLE
GC heap initialization failed with error 0x8007000E Failed to create CoreCLR, HRESULT: 0x8007000E

### ISSUE THREAD

**Issue by Mafant13** [PowerShell/PowerShell#20884]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/powershell-7.4.0-linux-arm64.tar.gz

tar -xvf powershell-7.4.0-linux-arm64.tar.gz

./pwsh                                                        
GC heap initialization failed with error 0x8007000E
Failed to create CoreCLR, HRESULT: 0x8007000E

### Expected behavior

```console
./pwsh activates the programm
```

### Actual behavior

```console
./pwsh doesn't work because of error 0x8007000E
```

### Environment data

```powershell
.
```

**Comment by rhubarb-geek-nz** [comment]
What operating system is this on?

I have no problems on Debian 11 on Raspberry Pi 4

```
$ wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/powershell-7.4.0-linux-arm64.tar.gz
....
HTTP request sent, awaiting response... 200 OK
Length: 68068263 (65M) [application/octet-stream]
Saving to: 'powershell-7.4.0-linux-arm64.tar.gz'

powershell-7.4.0-linux-arm64.tar.gz               100%[=============================================================================================================>]  64.91M  2.96MB/s    in 19s

2023-12-10 14:16:53 (3.38 MB/s) - 'powershell-7.4.0-linux-arm64.tar.gz' saved [68068263/68068263]

$ tar xfz powershell-7.4.0-linux-arm64.tar.gz
$ ./pwsh
PowerShell 7.4.0
PS /home/bythesea/tmp>
```

**Comment by Mafant13** [comment]
@rhubarb-geek-nz this is on a ubuntu 20 vm that i got from andronix

**Comment by rhubarb-geek-nz** [comment]
I have just tested in a docker on `aarch64` on a Raspberry Pi 4

```
FROM ubuntu:20.04

[internal] load metadata for docker.io/library/ubuntu:20.04
```

That same tar worked cleanly.

```
$ ldd pwsh
        linux-vdso.so.1 (0x0000007f9427d000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f941da000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f941c6000)
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f93fe1000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f93f36000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f93f12000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f93d9f000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f9424d000)
```

**Comment by rhubarb-geek-nz** [comment]
Given the limitations of [Andronix](https://docs.andronix.app/get-started/limitations) I would not expect it to be a support environment.

**Comment by mklement0** [comment]
Note that  [`0x8007000E`](https://www.hresult.info/Search?q=0x8007000E) indicates an _out-of-memory_ condition.

**Comment by mklement0** [comment]
The list of supported platforms is [here](https://github.com/PowerShell/PowerShell?tab=readme-ov-file#get-powershell)

**Comment by Mafant13** [comment]
@rhubarb-geek-nz that makes sense, well i need to check other ones, thanks for the support

**Comment by johnem-msft** [comment]
Ran into this error on proot and andronix on Android arm64

Workaround:
pwsh 7.2.9 still works fine! 

wget https://github.com/PowerShell/PowerShell/releases/download/v7.2.9/powershell-7.2.9-linux-arm64.tar.gz

tar -xvf powershell-7.2.9-linux-arm64.tar.gz

./pwsh
PowerShell 7.2.9                           Copyright (c) Microsoft Corporation.                                                  https://aka.ms/powershell                  Type 'help' to get help.                                                              PS /root/pwsh> write-host hello world      hello world

**Comment by atikattar1104** [comment]
another workaround that worked for me for this is setting GC heap hard limit to `10000000` using: 

```
export DOTNET_GCHeapHardLimit=10000000
```
and then calling powershell makes it run without any error. 

this sets the limit to approx. 7GB. 

![Image](https://github.com/user-attachments/assets/c20d5ffd-e8cc-414c-a423-b757e6268395)

originally found on this comment: https://github.com/dotnet/runtime/issues/79612#issuecomment-1352378682
