### ISSUE TITLE
Scoop Autocomplete does not work on pwsh 7.4

### ISSUE THREAD

**Issue by nahid6970** [PowerShell/PowerShell#20900]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

install pwsh 7.4 and scoop autocomplete tab completion stops working

### Expected behavior

```console
when typing scoop install and typing some keywords and clicking tab or ctrl and space it should autocomplete or give a suggestion
```

### Actual behavior

```console
its not doing anything after  installing pwsh 7.4
```

### Environment data

```powershell
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Did you install a tab completer for scoop prior to 7.4? I cannot get any sort of tab completion on <7.4. This may be a problem with scoop, I suggest also submitting an issue to their repo: https://github.com/ScoopInstaller/Scoop/issues. (assuming this is the same scoop you are talking about)
