### ISSUE TITLE
`Start-Process` on Windows: `-Environment` is quietly ignored when `-Verb RunAs` is also specified, combination should be prevented.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20923]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: 
* I'm _assuming_ that the underlying .NET / Windows APIs don't support this combination; if so, an error should be reported.

* Indeed the .NET APIs actively _prevent_ the analogous combination  (not sure about direct use of the WinAPI): `.Verb = "RunAs"` requires `.UseShellExecute = true`, which in turn actively prevents modifying the environment via `.Environment` or `.EnvironmentVariables` (exception "The Process object must have the UseShellExecute property set to false in order to use environment variables.").

```powershell
Start-Process -Verb RunAs cmd -Environment @{ foo='new' } '/c "echo [%foo%]" & pause' -Wait
```

### Expected behavior

An error indicating that the specific parameter combination isn't supported.

### Actual behavior

The process is launched, and the `-Environment` argument is _quietly ignored_.

```
[%foo%]
```

### Environment data

```powershell
PowerShell 7.4.0 on W11 22H2
```

**Comment by StevenBucher98** [comment]
> Indeed the .NET APIs actively prevent the analogous combination
Sounds like its an issue with .NET, have you opened an issue in there repo?

**Comment by mklement0** [comment]
@StevenBucher98:

* I can't speak to whether the by-design limitation in .NET is ultimately an unavoidable limitation in the _Windows API_.

  * I am not personally interested in researching this further.

  * If someone does, and _if_ it turns out that the limitation could be overcome via a change in .NET, there's no guarantee that such a change would be made and, even if so, it would take a loooonng time for it to become available in PowerShell.

* Therefore, I don't think the `Resolution-External` label is appropriate here.

  * Instead, this is an `Issue-Bug`, due to allowing you to specify unsupported parameter combinations without so much as a warning.

  * Another way to resolve this would be for PowerShell itself to work around the .NET limitation, via direct WinAPI calls _if even possible_.

**Comment by StevenBucher98** [comment]
Marking up for grabs.
