### ISSUE TITLE
`Resolve-Path -RelativeBasePath` is ignored unless `-Relative` is also specified, should imply the latter

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20920]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The `-RelativeBasePath` string parameter qualifies the `-Relative` switch.

Currently, `-RelativeBasePath` is _ignored_ if `-Relative` isn't also specified.

The better solution is for `-RelativeBasePath` to _imply_ `-Relative`, analogous to how, with `Get-ChildItem`, `-Depth` implies `-Recurse`.

_Update_: Turns out that `-RelativeBasePath` _without `-Relative`_ does have a use case, albeit only with _relative_ input paths; see comments below.

```powershell
Resolve-Path $Home -RelativeBasePath /  # -Relative not specified; should be implied
```

### Expected behavior

E.g., on Windows:

```
.\Users\jdoe
```

### Actual behavior

E.g., on Windows:

```
Path
----
C:\Users\jdoe
```

That is, `-RelativeBasePath` was _quietly ignored_.

### Environment data

```powershell
PowerShell 7.4.0
```

**Comment by MartinGC94** [comment]
That was the initial implementation but I changed it here: https://github.com/PowerShell/PowerShell/pull/19755 so people could resolve a relative path to a full path like this:

```
PS C:\Users\Martin> Resolve-Path -Path .\System32 -RelativeBasePath C:\Windows

Drive Provider                             ProviderPath        Path
----- --------                             ------------        ----
C     Microsoft.PowerShell.Core\FileSystem C:\Windows\System32 C:\Windows\System32
```

Of course it's not very useful when you are specifying a full path as the input but we can't do anything about that.

**Comment by mklement0** [comment]
Thanks, @MartinGC94, I wasn't aware of this feature.

Let me try to summarize, as the basis for discussing potential changes / amending the documentation:

`-RelativeBasePath` has two distinct use case - one with and the other without also specifying `-Relative`.
In both cases, `-RelativeBasePath` acts as a _reference path_ for the resolution.

* **_With_ `-Relative`**:

  * **Returns _relative_ paths, as _strings_**, which describes _how to get from the input paths to the reference path_ (which defaults to the current location), using `.` and `..` components as needed.
  * This is equally **useful for both _relative_ and _absolute_  input paths**, but it is important to note that **a _relative_ input path is interpreted as *relative to `-RelativeBasePath`***.
   * Examples (using literal paths, but wildcards are supported, via `-Path`):

```powershell
# ABSOLUTE input path:
# Get the relative path from C:\Windows to, say, C:\Users\jdoe -> '..\Users\jdoe'
Resolve-Path $HOME -Relative -RelativeBasePath C:\Windows

# RELATIVE input path: 
# Get the relative path from C:\Windows to C:\Windows\System32  -> '.\System32'
Resolve-Path System32 -Relative -RelativeBasePath C:\Windows
# This is basically the equivalent of:
#    '.\' +  (Get-Item (Join-Path C:\Windows System32)).Name
```

* **_Without_ `-Relative`**:

  * **Returns _absolute_ paths, as  _`[System.Management.Automation.PathInfo]` instances_**.
  * This parameter combination It is therefore **only useful with _relative_ input paths**, given that there'd be nothing to resolve for absolute ones.

   * Example:

```powershell
# Get the absolute paths of items named Prog* in C:\
# -> [System.Management.Automation.PathInfo] instances for the following full paths:
#   'C:\Program Files'
#   'C:\Program Files (x86)'
Resolve-Path Prog* -RelativeBasePath C:\
# This is the equivalent of:
#   Resolve-Path (Join-Path C:\ Prog*)
```

---

**Potential resolutions**:

* The docs definitely need amending, at the very least to modify the useless `Resolve-Path -Path $ExecutablePath -RelativeBasePath $env:TEMP` example, which uses an _absolute_ input path.

* Given that `Resolve-Path Prog* -RelativeBasePath C:\` is essentially the same as  `Resolve-Path (Join-Path C:\ Prog*)`, maybe we could have done without the former, especially given the potential for confusion around `-Relative` - but I guess that ship has sailed.

* To lessen the potential for confusion, I suggest **renaming `-RelativeBasePath` to `-BasePath`** (and keeping the former a as an _alias_  of the latter, for backward compatibility):
  * This  avoids the expectation that `-RelativeBasePath` use _implies_ `-Relative` (which is what prompted creation of this issue).
  * By avoiding the word `Relative` in the name, users will be less tempted to think that the feature relateds exclusively to the `-Relative` switch.

**Comment by mklement0** [comment]
So that this issue doesn't die a slow death (which may still happen to the linked feature request), I'm closing this in favor of:

* A documentation bug report based on the above: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10738

* A feature request to rename the parameter: #20937
