### ISSUE TITLE
Add a `-Force` switch to `Convert-Path` and `Resolve-Path` so as to also support hidden files.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20929]
### Summary of the new feature / enhancement

Currently, both `Convert-Path` and `Resolve-Path` only ever report non-hidden files as matching a given _wildcard pattern_.

In order to also support hidden files, a `-Force` switch should be added, analogous to `Get-Item` and `Get-ChildItem`.

E.g., on Unix-like platforms:

```powershell
# Ditto for Resolve-Path
Convert-Path ~/.bash*
```

This currently produces NO output, because `.`-prefixed files and directories are considered hidden on Unix-like platforms.
Desired output (for example):

```
/Users/jdoe/.bash_sessions
/Users/jdoe/.bash_history
/Users/jdoe/.bash_profile
/Users/jdoe/.bashrc
```

Note: The problem arises only with _wildcard patterns_ - literal paths _are_ found.

**Comment by ArmaanMcleod** [comment]
This sounds like a great enhancement 👍 

It was always interesting how only `Get-ChildItem` had a `-Hidden` parameter which only displayed hidden files. If you also wanted non-hidden files you would also need to use `-Force`.

Makes sense to use `-Force` for consistency to include hidden files for all cmdlets.

**Comment by ArmaanMcleod** [comment]
I noticed as well on Ubuntu this seems to only be an issue with wildcards:

```pwsh
12-21 18:37:36 ~/git-repos/PowerShell [master ≡]> Convert-Path ./.gitignore
/home/armaan/git-repos/PowerShell/.gitignore
12-21 18:37:52 ~/git-repos/PowerShell [master ≡]> Convert-Path ./.git*
12-21 18:37:55 ~/git-repos/PowerShell [master ≡]>
12-21 18:37:55 ~/git-repos/PowerShell [master ≡]> Resolve-Path ./.gitignore

Path
----
/home/jdoe/git-repos/PowerShell/.gitignore

12-21 18:40:39 ~/git-repos/PowerShell [master ≡]> Resolve-Path ./.git*
12-21 18:40:42 ~/git-repos/PowerShell [master ≡]>
```

On Windows it works as expected:

```pwsh
12-21 18:39:15 ~\git-repos\PowerShell [master ≡]> Convert-Path .\.gitignore
C:\Users\jdoe\git-repos\PowerShell\.gitignore
12-21 18:39:20 ~\git-repos\PowerShell [master ≡]> Convert-Path .\.git*
C:\Users\jdoe\git-repos\PowerShell\.github
C:\Users\jdoe\git-repos\PowerShell\.gitattributes
C:\Users\jdoe\git-repos\PowerShell\.gitignore
12-21 18:39:23 ~\git-repos\PowerShell [master ≡]> Resolve-Path .\.gitignore

Path
----
C:\Users\jdoe\git-repos\PowerShell\.gitignore

12-21 18:40:05 ~\git-repos\PowerShell [master ≡]> Resolve-Path .\.git*

Path
----
C:\Users\jdoe\git-repos\PowerShell\.github
C:\Users\jdoe\git-repos\PowerShell\.gitattributes
C:\Users\jdoe\git-repos\PowerShell\.gitignore
```

**Comment by mklement0** [comment]
Thanks,  @ArmaanMcleod.

Good point about only wildcard expressions being affected (I've updated the initial post to clarify.) 

Note that `.`-prefixed files aren't necessarily hidden _on Windows_, which explains why even wildcard-based matching found it. There, it is the `Hidden` _attribute_ that matters, so if you hide, say, `.\.gitignore` with `attrib -h .\.gitignore`, `Convert-Path .\.git*` will no longer match it.

As an aside:

* The distinction between literal paths and wildcard-based matching with respect to hidden items generally makes sense - but, unfortunately, isn't observed by `Get-Item` and  `Get-ChildItem`
* See #6502

**Comment by mklement0** [comment]
I forgot that years ago I had asked for the same, only more comprehensively:

* `Test-Path`, `Split-Path -Resolve`, `Join-Path -Resolve`, and `Invoke-Item` too need a `-Force` switch in order to include hidden items _when using wildcards_ - see #6502.
