### ISSUE TITLE
cycling through tab completions doesn't work

### ISSUE THREAD

**Issue by garegin16** [PowerShell/PowerShell#2093]
You can't tab through completions in powershell for os x. in windows I can type get-childitem and then keep hitting tab and run through all the possible completions. On OS X, hitting tab just prints out all the possible completions and that's it. you can't keep pressing tab and cycle through them.
I found a way to correct this issue in bash.

http://hints.macworld.com/article.php?story=20050904022246573
bind '"\t":menu-complete'

**Comment by lzybkr** [comment]
If you're expecting the command line editing experience from Windows, then use `Set-PSReadlineOption -EditMode Windows`.

If you're expecting the default bash command line editing experience, but just want tab to behave like Windows, use:

```
Set-PSReadlineKeyHandler -Key Tab -Function TabCompleteNext
Set-PSReadlineKeyHandler -Key Shift+Tab -Function TabCompletePrevious
```

In PSReadline, `MenuComplete` is bound to `Ctrl+Space`, but I think it's better than `menu-complete` in bash.

**Comment by garegin16** [comment]
Thanks for thorough answers

**Comment by lzybkr** [comment]
Great - closing the issue then.
