### ISSUE TITLE
function-parsing does not match grammar (probably docs issue?)

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#20936]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

There is one drift between the defined parsing syntax and the implemented parser. We probably should consider this a docs issue (as it is probably way easier to fix the doc than the parser, esp. because there are currently (almost?) no 3rd party parser implementations). But as technically the parser definition is the source of truth for most implementations it makes it a parser issue. So I'm opening it in here for discussion.

The function definition says:

```
function-statement:
    function new-lines~opt~ function-name function-parameter-declaration~opt~ { script-block }
    filter new-lines~opt~ function-name function-parameter-declaration~opt~ { script-block }
    workflow new-lines~opt~ function-name function-parameter-declaration~opt~ { script-block }
```
And when resolved first contains the issue of referencing the `command-name-expr` that is missing a definition (probably a typo, see below). As well as missing a `new-lines~opt~` after the function-name token. This omission of the `new-lines~opt` causes the drift (See expected behavior section for examples why this makes a difference).

Additionally, I also noticed a (probably just) a typing error related to the `command-name-expr` which is part of the function-name definition. Either it is not defined at all, or it lacks a reference to https://learn.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-08?view=powershell-7.3#82-pipeline-statements
AND contains a typing error as it is written as `command-namecommand-name-expr`, which itself doesn't appear to be referenced by anything.

### Expected behavior

```console
# Documentation would mean parsing error for, as there is no new-lines~opt~ between function-name and the curved open bracket:
function
name
{
}

# Also parsing error for this (new line after the parenthesis of function-parameter-declaration, as this makes that token non optional anymore and it doesn't specify any new-lines~opt~ between it and the curved open bracket:
function
name
()
{
}

# Also technically omitting the white space before the curved open bracket should be a syntax error but currently isn't. Same for omitting the space between function-name and the round open bracket of function-parameter-declaration. At least if we consider the spaces in the definition to be part of the definition itself and not just for readability within the documentation.
# Otherwise, if we would consider the spaces to be NOT part of the syntax it would mean that this would have to be valid (which it currently isn't). That's because it doesn't contain anything about mandatory spaces then.
functionname(){}
```

### Actual behavior

```console
All of these are considered valid by the parser, except for `functionname(){}` which is currently considered invalid.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Arch Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
The language spec was written for version 3.0 and is mostly still available for historical reasons. There are no plans to update it (and at this point we'd likely need to write a new spec anyway)

**Comment by agowa** [comment]
It contains notes about features that were added later on though. That's why I thought that it was still up to date.
Can we somehow just compile one from the code base? Having the syntax within the documentation can be helpful for debugging when things appear to be parsed incorrectly as well as for many other things. So loosing it (or not maintaining it) would be a undesirable...

**Comment by jhoneill** [comment]
The way I read that is doesn't allow for  line break before the `{` for the script block .
```
function SayHello
{
    "Hello World"
}
```
Should not parse and needs to be 
```
function SayHello  {
    "Hello World"
}
```
Quite a lot of people - including some on the PowerShell team - put their function braces on a new line, although because of the way script block parameters work (`where-object` and `foreach-object` don't like a line break before `{` ) this is discouraged in style guides.  But the spec isn't a style guide. 

```
function

SayHello

($myParam)  {
    "Hello $myparam"
}
``` 
Is legal and really shouldn't be encouraged, but according to the spec would break with `{` on its own line

@SeeminglyScience If it's not practical to produce a current one, it might be wisest to add something to the doc saying it was written for V3 and isn't maintained.
