### ISSUE TITLE
Custom auto-completion not working anymore on 7.4.0

### ISSUE THREAD

**Issue by basketshoe** [PowerShell/PowerShell#20930]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to autocomplete options using tab key but after updating pwsh to version 7.4.0 it's not working anymore.
I have tried using scoop and chocolatey. Both are working on previous versions but not on 7.4.0

### Expected behavior

```console
Autocomplete is working using tab
```

### Actual behavior

```console
Nothing (or not related directories) is showing
```

### Error details

```console
none
```

### Environment data

```powershell
PS C:\Users\USERNAME> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Please provide more details.
What commands and command types are affected?
Is it only _syntax_ completion that is affected or _history_-based completion too?

**Comment by basketshoe** [comment]
>  What commands and command types are affected?

scoop with any of the options (update, status, home, etc). 
Same thing with choco.

>  Is it only syntax completion that is affected or history-based completion too?

Both

**Comment by StevenBucher98** [comment]
We are still going to need more detail here to be able to properly identify what is going wrong, in your title you say "Custom auto-completion" what customized completion have you added?

**Comment by basketshoe** [comment]
I've added this custom module https://github.com/Moeologist/scoop-completion/tree/master/src specifically

**Comment by StevenBucher98** [comment]
According to this comment it seems like it may be an issue with their completion specifically: https://github.com/Moeologist/scoop-completion/issues/35#issuecomment-1837473915

**Comment by basketshoe** [comment]
But it works on previous pwsh versions

**Comment by yan12125** [comment]
It seems Scoop uses `TabExpansion`, which is not supported by PowerShell >= 7.4 (https://github.com/PowerShell/PowerShell/pull/18337). Switching to Register-ArgumentCompleter like 
 https://github.com/Moeologist/scoop-completion/pull/25 may help.

**Comment by nahid6970** [comment]
is there any update or any solution? also how to solve it using  Register-ArgumentCompleter

**Comment by nahid6970** [comment]
> It seems Scoop uses `TabExpansion`, which is not supported by PowerShell >= 7.4 (https://github.com/PowerShell/PowerShell/pull/18337). Switching to Register-ArgumentCompleter like 
>  https://github.com/Moeologist/scoop-completion/pull/25 may help.
> 
> > Same thing with choco.
> 
> Chocolatey also needs a change: https://github.com/chocolatey/choco/issues/3364

seems like neither of pwsh or scoop developer want to fix it

**Comment by mklement0** [comment]
@nahid6970:

@yan12125's comment implies:

* An _intentional_ breaking change (removal of legacy code) was made in PowerShell 7.4.0: 

  * The _legacy_ `TabExpansion` function, _if still defined, which in v3+ requires an explicit third-party definition_, is now no longer called by PowerShell.

  * This broke the current versions of [Chocolatey](https://github.com/chocolatey/choco) and [scoop-completion](https://github.com/Moeologist/scoop-completion), because they rely on their custom - now obsolete - `TabExpansion` functions getting called for module-specific completions.

  * While the `TabExpansion` function does have a successor -  `TabExpansion2`, built-in since v3 - the preferable mechanism for module/command-specific custom completions is to use [`Register-ArgumentCompleter`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter), [available since (at least)  PowerShell 5.1](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/cmdlet-versions?view=powershell-7.4) (the latest and _last_ version of _Windows PowerShell_).

* The onus is therefore on _said modules_ - rather than PowerShell - to update, as tracked in the following issues:
  * scoop-completion: https://github.com/Moeologist/scoop-completion/issues/35
  * Chocolatey: https://github.com/chocolatey/choco/issues/3364

**Comment by nahid6970** [comment]
how to use tabexpansion or what should i add to my powershell profile for scoop complete work any workaround?

**Comment by mklement0** [comment]
The following is a polyfill that overrides the `TabExpansion2` function to exhibit the old behavior if a `TabExpansion` function happens to be defined. 
(Note that directly overriding this function is generally not a good idea - `Register-ArgumentCompleter` should be used instead, and Scoop and Chocolatey will hopefully switch to using it, which will make this polyfill unnecessary.)

You should be able to paste the code as-is into your `$PROFILE`

```powershell
# Polyfill for PowerShell 7.4+:
# Ensure that a legacy 'TabExpansion' function is still called, if defined.
if ($PSVersionTable.PSVersion -ge '7.4') {
  function TabExpansion2 {
    ### Copy of the parameter declarations from the built-in TabExpansion2 function.
    [CmdletBinding(DefaultParameterSetName = 'ScriptInputSet')]
    [OutputType([System.Management.Automation.CommandCompletion])]
    Param(
      [Parameter(ParameterSetName = 'ScriptInputSet', Mandatory = $true, Position = 0)]
      [AllowEmptyString()]
      [string] $inputScript,
      [Parameter(ParameterSetName = 'ScriptInputSet', Position = 1)]
      [int] $cursorColumn = $inputScript.Length,
      [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 0)]
      [System.Management.Automation.Language.Ast] $ast,
      [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 1)]
      [System.Management.Automation.Language.Token[]] $tokens,
      [Parameter(ParameterSetName = 'AstInputSet', Mandatory = $true, Position = 2)]
      [System.Management.Automation.Language.IScriptPosition] $positionOfCursor,
      [Parameter(ParameterSetName = 'ScriptInputSet', Position = 2)]
      [Parameter(ParameterSetName = 'AstInputSet', Position = 3)]
      [Hashtable] $options = $null
    )
    ###

    Set-StrictMode -Version 1
  
    if ($function:TabExpansion) { # Legacy function present: invoke it first.
      
      # Determine the arguments expected by the legacy TabExpansion function.
      $line = $inputScript.Substring(0, $cursorColumn) # the input line to the left of the cursor position
      $lastWord = & { # the token immediately preceding the cursor position, if any.
        # NOTE:
        #  * The following *emulates* what PowerShell in earlier versions did, which was apparently
        #    custom parsing that included *partial* support for recognizing *quoted* tokens.
        #  * The following uses PowerShell's language parser instead, which results in 
        #    *slightly different, but arguably IMPROVED* behavior (the old behavior is less helpful in all these cases):
        #     * If the cursor is right after a *syntactically complete* quoted
        #       string literal, $lastWord is set to '' (by definition, the argument is complete)
        #     * Similarly, *syntactically complete* $(...) / @(...) / (...) expressions result in $lastWord getting set to ''
        #     * Inside quoted string literals, *escaped* quotes are handled correctly.
        $tokens = $null
        # Note: The parser ignores incidental whitespace, so we place a dummy char. at the end.
        #       that helps us determine if a space *outside a string literal* is present.
        $null = [System.Management.Automation.Language.Parser]::ParseInput($line + [char] 1, [ref] $tokens, [ref] $null)
        if ($lastToken = $tokens[-2]) { # Get the penultimate token (the last one is always the EndOfInput token)
          if ($lastToken.Text -ne [char] 1) { # Only if the line doesn't end in a stand-alone space.
            $( 
              if ($lastToken.Value) { $lastToken.Value } # string literal: output its *content*
              else { $lastToken.Text } # otherwise (bareword, variable reference, ...): output its text.
            ).TrimEnd([char] 1) # remove the dummy char.
          }
        }
      }

      # Invoke the legacy expansion function, which returns $null, one, or multiple strings.
      $result = TabExpansion $line $lastWord
      
      # If results were received:
      if ($result) {
        # Wrap them in a [System.Management.Automation.CommandCompletion] instance, as required
        # by TabExpansion2.
  
        # Going backward from the current cursor position, find the previous whitespace,
        # so as to determine the start of the token being completed.
        $ndx = $inputScript.Substring(0, $cursorColumn).LastIndexOf(' ')
        $replacementLength = [math]::Max($cursorColumn - $ndx - 1, 0)
      
        # Construct the completion instance and output it.
        return [System.Management.Automation.CommandCompletion]::new(
          [System.Collections.ObjectModel.Collection[System.Management.Automation.CompletionResult]] $result, 
          -1, # current match index (later used to keep track of cycling through multiple matches)
          $cursorColumn - $replacementLength, # the start index of the token being completed.
          $replacementLength # the length of the token being completed.
        )
      }
      # No results? Continue below for default tab completion.
    
    } 
    
    ###  The following is the original function body (slightly streamlined;
    ###  you can see the original in a pristine session by submitting $function:TabExpansion2)
  
    if ($psCmdlet.ParameterSetName -eq 'ScriptInputSet') {
      return [System.Management.Automation.CommandCompletion]::CompleteInput(
        $inputScript,
        $cursorColumn,
        $options)
    }
    else { # 'AstInputSet'
      return [System.Management.Automation.CommandCompletion]::CompleteInput(
        $ast,
        $tokens,
        $positionOfCursor,
        $options)
    }
  
  }
  
}
```

**Comment by basketshoe** [comment]
Thanks, I'll try it tomorrow

**Comment by nahid6970** [comment]
@mklement0 thanks a lot working perfectly ❤️❤️❤️

**Comment by StevenBucher98** [comment]
Thanks for the work around @mklement0 marking as resolution external since it seems like there are updates needed on the scoop and choco tools.
