### ISSUE TITLE
The pwsh freezes when using a regular expression

### ISSUE THREAD

**Issue by korovindenis** [PowerShell/PowerShell#20949]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hello,
When using this regular expression "`"data`"(.*?|\n)+},", the PowerShell process hangs. Changing the regular expression resolves the issue, and the code executes successfully - "`"data`"(\n)+},"

```powershell
$obj = @{
	data = @{
		data = @{
			message = ""
		}
	}
}
$obj.data.data.message = "text"
$body = @{data=$obj.data.data} | ConvertTo-Json 

Write-Host $($body -replace "`"data`"(.*?|\n)+},")
```
### Expected behavior

```console
pwsh process not freezes
```

### Actual behavior

```console
pwsh process freezes
```

### Error details

```console
null
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![err](https://github.com/PowerShell/PowerShell/assets/43725617/4701df63-b1d0-4d95-be27-c78f37b41bcf)

![success](https://github.com/PowerShell/PowerShell/assets/43725617/86394232-77a8-41e9-bcdf-b257db8844b5)

**Comment by mklement0** [comment]
Fundamentally, please note that PowerShell's regex functionality is just a thin layer on top of the .NET regex APIs, so it's always worth checking if the problem also occurs when using these APIs directly (e.g., ``[regex]::Replace($body, "`"data`"(.*?|\n)+},", '')``) - which is indeed the case here. If so, issues need to be reported at https://github.com/dotnet/runtime/issues

However, in the case at hand I think the only problem is that you've created a very inefficient regex that takes a very long time to evaluate (about 7 seconds on my machine). That is, there is no hang.

I assume you're looking for something like the following (I'm only guessing), which evaluates virtually instantaneously:

```powershell
$body = @'
{
  "data": {
    "message": "text"
  }
}
'@

$body -replace '(?s)"data".+?\}'
```

Note, however, that using regexes to parse and manipulate JSON is best avoided, as it is inherently brittle.

**Comment by StevenBucher98** [comment]
Thanks for the issue @korovindenis! And thanks for the testing @mklement0! I also suggest opening an issue with dotnet since the issue seems to lie with them.

**Comment by mklement0** [comment]
I've created a .NET issue here:

* https://github.com/dotnet/runtime/issues/96340
