### ISSUE TITLE
Unexpected behavior in command execution when two files have the same basename.

### ISSUE THREAD

**Issue by nocentino** [PowerShell/PowerShell#2095]
## Steps to reproduce

Create two files
1. Simple shell script, name it **loop** and mark it executable
2. Simple powershell script, name it **loop.ps1**
## Expected behavior

Typing ./loop should launch the program loop
## Actual behavior

When you type ./loop you would expect loop (the first file) to execute. It does not, in fact loop.ps1 executes.
## Environment data

```
Name                           Value                                                                         
----                           -----                                                                         
PSVersion                      5.1.10032.0                                                                   
PSEdition                      Linux                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                       
BuildVersion                   3.0.0.0                                                                       
GitCommitId                    v0.6.0                                                                        
CLRVersion                                                                                                   
WSManStackVersion              1.0                                                                           
PSRemotingProtocolVersion      2.3                                                                           
SerializationVersion           1.1.0.1       
```

**Comment by joeyaiello** [comment]
Heads-up, I edited your comment to wrap `$PSVersionTable` in a code block.

**Comment by joeyaiello** [comment]
As far as the bug is concerned, that's definitely a problem, but I believe anything we do here is a breaking change that would need to be discussed. /cc @PowerShell/powershell-committee

**Comment by nocentino** [comment]
Cool, however I can help please let me know.

**Comment by andschwa** [comment]
This essentially comes down to the ordering of the paths [here](https://github.com/PowerShell/PowerShell/pull/1048/files#diff-3647720a015098e93e335bc9631753c7R68), which @lzybkr, @JamesWTruher, and I [discussed](https://github.com/PowerShell/PowerShell/pull/1048#r64978707) but I guess came to the wrong conclusion. At least now, I totally agree that `foo` should be ordered before `foo.ps1` (and it before `foo.*`).

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and since there is no extension (unlike Windows) to explicitly call the exe, we should make the change to call the native command first before the script
