### ISSUE TITLE
More granular control for `>` and `>>` defaults

### ISSUE THREAD

**Issue by brian6932** [PowerShell/PowerShell#20958]
### Summary of the new feature / enhancement

Sometimes I would like `>` to be
```pwsh
$PSDefaultParameterValues['Out-File:NoNewline'] = $true
```
While having `>>` be
```pwsh
$PSDefaultParameterValues['Out-File:NoNewline'] = $false
```
And vice versa, a way to control this more granularity would be kinda neat

**Comment by rhubarb-geek-nz** [comment]
I suggest this highlights one of the problems of defaults through environment. You always have fine control because you can pipe through Out-File directly with any of its command line parameters, then there is no conflict or ambiguity.

**Comment by brian6932** [comment]
Yea this is kinda niche, so I get it being closed as not planned/out of scope. I do think it'd be kinda of nice to have some type of operator scoping for `PSDefaultParameterValues`

**Comment by rhubarb-geek-nz** [comment]
> I do think it'd be kinda of nice to have some type of operator scoping for `PSDefaultParameterValues`

I think that is heavily overloading what the idea of default value is, especially if Out-File now needs to know why and how it was invoked to determine the default values to use. 

Keep things simple, do one thing well, have predictable behaviour, don't double and triple guess what the user thinks they really want, don't have modes and contexts that change behaviour.

**Comment by jhoneill** [comment]
I just checked this and `$PSDefaultParameterValues['Out-File:Encoding']="bigendianutf32"` _did_ change the encoding of `dir > delete.me `
Are you saying you want `PSDefaultParameterValues` for > & >> independent of the ones for  `Out-File` or additional operators doing the same syntactic sugar thing for  `| Out-File -someParameter` as > does for `| Out-File`

**Comment by brian6932** [comment]
I just wanted an independent way to adjust them, maybe didn't phrase the issue well enough

**Comment by mklement0** [comment]
@brian6932, if you _really_ want to do this (I personally suggest not doing it), you can use a _script block_ to determine the default value:

```powershell
$PSDefaultParameterValues['Out-File:NoNewLine'] = {
  -not $args[0].BoundParameters.Contains('Append')
}
```

**Comment by brian6932** [comment]
🤔 that works
