### ISSUE TITLE
Introducing **Fallback Fonts** in PowerShell Font 

### ISSUE THREAD

**Issue by chillcicada** [PowerShell/PowerShell#20957]
### Summary of the new feature / enhancement

Dear PowerShell Team,

I would like to suggest the introduction of a fallback fonts in the PowerShell font configuration. Currently, the fonts configuration of powershell only accepts a single string, limiting the flexibility in font selection. 🥺🥺

### Proposed technical implementation details (optional)

In the powershell configuration (setting.json), the related configurations is as follows:

```json
"font": 
        {
            "face": "MesloLGM Nerd Font Mono",
            "size": 12.0,
            "weight": "medium"
        },
```

Sadly that the `fonts.face` only accepts the string argument.

One solution is to make the `fonts.face` accept an array of string.

Other solution is to introduce a `set-font` function that independently set the `PrimaryFont` and `FallbackFonts`.

That's all, thanks.

**Comment by iSazonov** [comment]
> In the powershell configuration (setting.json)

It is Windows Terminal configuration. PowerShell hasn't such configurations (and can not have).
