### ISSUE TITLE
ValidateNotNullOrEmpty doesn't work when used in class with hashtable constructor

### ISSUE THREAD

**Issue by mkennedy-mqual** [PowerShell/PowerShell#20960]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
class Foo {
    [ValidateNotNullOrEmpty()][String]$Bar
    Foo([hashtable]$Properties) { 
        foreach ($Property in $Properties.Keys) {
            $this.$Property = $Properties.$Property
        }
    }
}
[Foo]::new(@{}) 
# or
New-Object Foo(@{})
```

### Expected behavior

```
Function Foo([ValidateNotNullOrEmpty()][String]$Bar) {}
Foo ""
#=> Foo: Cannot validate argument on parameter 'Bar'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

### Actual behavior

```
[Foo]::new(@{})

Bar
---

New-Object Foo(@{})

Bar
---
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
This is happening because the class is never assigning a value for `Bar` and thus won't actually run the validation logic. You can work around this by always assigning the value, if there is no `Bar` key in the hashtable then an empty string will be used thus causing the validation error.

```powershell
class Foo {
    [ValidateNotNullOrEmpty()][String]$Bar

    Foo([hashtable]$Properties) { 
        $this.Bar = $Properties.Bar
    }
}

[Foo]::new(@{}) 
```

**Comment by mkennedy-mqual** [comment]
Any ideas how I can make it work without explicitly naming each hash table key in the constructor?

**Comment by jborean93** [comment]
You can loop through the classes properties rather than the hashtable keys

```powershell
class Foo {
    [ValidateNotNullOrEmpty()][String]$Bar

    Foo([hashtable]$Properties) {
        foreach ($name in [Foo].GetProperties().Name) {
            $this.$name = $Properties.$name
        }
    }
}

[Foo]::new(@{})
```

**Comment by mkennedy-mqual** [comment]
Wonderful, thank you so much for the help!
