### ISSUE TITLE
A non-PSObject type like [System.Int32] becomes a PSObject inside a pipeline

### ISSUE THREAD

**Issue by mjr4077au** [PowerShell/PowerShell#20961]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

During the writing of a filter that was not working correctly, I observed that integers and other non-PSObject types, when piped into a filter, become PSObject types and it breaks comparisons I've been doing.
```PowerShell
PS C:\Users\mjr40> filter Test-Type {$global:var = $_}
PS C:\Users\mjr40> 2 | Test-Type
PS C:\Users\mjr40> $var
2
PS C:\Users\mjr40> $var.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType

PS C:\Users\mjr40> 2
2
PS C:\Users\mjr40> (2).GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType

PS C:\Users\mjr40> $var -is [System.Management.Automation.PSObject]
True
PS C:\Users\mjr40> 2 -is [System.Management.Automation.PSObject]
False
```
This happens in both Windows PowerShell 5.1 and PowerShell 7.4.0. I've tried to find an answer online but searching for PSObject is incredibly difficult as most articles pertain to how to make one, or how to use the `[pscustomobject]` accelerator.

### Expected behavior

```console
PS C:\Users\mjr40> $var -is [System.Management.Automation.PSObject]
False
```

### Actual behavior

```console
PS C:\Users\mjr40> $var -is [System.Management.Automation.PSObject]
True
```

### Environment data

```powershell
PS C:\Users\mjr40> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mjr4077au** [comment]
As an addition, this can be perhaps more simply tested with `Write-Output`:
```PowerShell
PowerShell 7.4.0
PS C:\Users\mjr40> (Write-Output -InputObject 2) -is [System.Management.Automation.PSObject]
True
PS C:\Users\mjr40> (2) -is [System.Management.Automation.PSObject]
False
PS C:\Users\mjr40> (Write-Output -InputObject 2).GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType

PS C:\Users\mjr40> (2).GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32                                    System.ValueType
```

**Comment by rhubarb-geek-nz** [comment]
The definition of [PowerShell.Invoke](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.invokeasync?view=powershellsdk-7.4.0) returns a `PSDataCollection<PSObject>` so would not be surprised that elements in a pipeline are wrapped with a PSObject, this can certainly get more expensive if individual bytes are being written rather than byte array.

**Comment by mjr4077au** [comment]
@rhubarb-geek-nz do you know if there's a way to unravel it once it's in the pipe? For all intents and purposes, the object in the pipe acts the way it's supposed to and the output of GetType() is equal to that of a bare object. I've tried sub-expressing it but it doesn't make a difference...

**Comment by rhubarb-geek-nz** [comment]
This is my [ultimate unravelling](https://github.com/rhubarb-geek-nz/AspNetForPowerShell/blob/main/PowerShellDelegate/PowerShellDelegate.cs)...

```
        private readonly static TypeWriter[] TypeWriters =
        {
            new TypeWriter(typeof(byte[]),(o,e)=>{ byte[] ba=(byte[])o; return e.stream.WriteAsync(ba,0,ba.Length); }),
            new TypeWriter(typeof(string),(o,e)=>e.WriteObject(e.encoding.GetBytes((string)o))),
            new TypeWriter(typeof(char[]),(o,e)=>e.WriteObject(e.encoding.GetBytes((char[])o))),
            new TypeWriter(typeof(byte),(o,e)=>e.WriteObject(new byte[]{(byte)o})),
            new TypeWriter(typeof(char),(o,e)=>e.WriteObject(new char[]{(char)o})),
            new TypeWriter(typeof(Encoding),(o,e)=>{ e.encoding=(Encoding)o; return Task.CompletedTask; }),
            new TypeWriter(typeof(PSObject),(o,e)=>e.WriteObject(((PSObject)o).BaseObject)),
            new TypeWriter(typeof(IEnumerable<byte>),(o,e)=>e.WriteObject(((IEnumerable<byte>)o).ToArray())),
            new TypeWriter(typeof(IEnumerable<char>),(o,e)=>e.WriteObject(((IEnumerable<char>)o).ToArray())),
            new TypeWriter(typeof(IEnumerable<object>),async (o,e)=>{ foreach(var obj in ((IEnumerable<object>)o)) { await e.WriteObject(obj); } })
        };
```

I think the answer for you is `BaseObject`, if anyone knows better please advise!

**Comment by mjr4077au** [comment]
I just tried doing a cast in brackets like you've shown (`([psobject]2).BaseObject`). BaseObject tab-completes, however the output is null. The same goes for an object in the pipe as well.
```PowerShell
PS C:\Users\mjr40> filter Test-Type {$_.BaseObject}
PS C:\Users\mjr40> 2 | Test-Type
```

**Comment by mjr4077au** [comment]
Looks like I've accidentally opened a duplicate... https://github.com/PowerShell/PowerShell/issues/5579

For now I've taken the feedback from https://github.com/PowerShell/PowerShell/issues/9557#issuecomment-490544771 and am just checking against `[System.String]` and `[System.ValueType]` types explicitly instead of checking against `[psobject]` and letting the other cases fall through. It's working for my requirements but doesn't feel as robust.

There's other tickets as well, such as:
* https://github.com/PowerShell/PowerShell/issues/11921
* https://github.com/PowerShell/PowerShell/issues/4344
* https://github.com/PowerShell/PowerShell/issues/9557
Someone needs to stop that `microsoft-github-policy-service` bot as it's closing off legitimate tickets at the drop of a hat...

**Comment by mklement0** [comment]
You find the right issues; a few more pointers:

* In _most_ cases - except the buggy ones listed in #5579 - you needn't worry about the mostly invisible `[psobject]` wrappers, which mostly behave like the wrapped object itself.

* To detect a `[pscustomobject]` instance, use `-is [System.Management.Automation.PSCustomObject]`; `-is [pscustomobject]` _should_ work, but doesn't, as discussed in #11921 - it is in effect the same as `-is [psobject]`

* If needed, `.psobject.BaseObject` gives you the wrapped object:

```powershell
 ($wrapped = Write-Output 42)  -is [psobject] # -> $true
 $wrapped.psobject.BaseObject -is [psobject] # -> $false
```

**Comment by mjr4077au** [comment]
Thank you for the pointers! I was working on a ConvertTo-Hashtable filter that I've had for years, it would have started off as code from somewhere on the net. I was trying to remove the parameter binding from it to just make it a simple, basic, recursive filter but was having unexpected behaviour from it. At least now thanks to #5579 I know precisely what the go is.
> * If needed, `.psobject.BaseObject` gives you the wrapped object:
> 
> ```powershell
>  ($wrapped = Write-Output 42)  -is [psobject] # -> $true
>  $wrapped.psobject.BaseObject -is [psobject] # -> $false
> ```
The above here was also the secret sauce I needed. I was trying to get the BaseObject without going through the hidden PSObject property first. That gives me the predictable behaviour I was wanting.

**Comment by SeeminglyScience** [comment]
Yeah to test for a PSCustomObject you need to check that there is no base object, e.g. `$null -eq $wrapped.psobject.BaseObject`

You can also test `$wrapped -is [System.Management.Automation.PSCustomObject]` as that's the placeholder used internally. Note that you *must* have the full type name including namespace (*even* if you're using `using namespace`) as `PSCustomObject` is confusingly just a type accelerator for `PSObject` itself.
