### ISSUE TITLE
Set-Content duplication with array of directories

### ISSUE THREAD

**Issue by tadghh** [PowerShell/PowerShell#20969]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Set-Content will duplicate content, when passed a wildcard directory containing shortcuts to folders
- Create a folder
- Create a shortcut to the folder
- create an ini file
- Pass Set-Content a wildcard and the parent directory containing the above folders
   - See $scoopInstall below

### ini file being written to

```bash
[Settings]
gtk-application-prefer-dark-theme=false
```

### Powershell script (outline)
See the project linked below for full context, however this captures the bug.
```pwsh
# Will contain both folders above even though they are the same.
$scoopInstall = "$env:USERPROFILE\scoop\apps\deluge\*\"

$currentSettingsPath = ($scoopInstall + "settings.ini")

$regex = '^\s*gtk-application-prefer-dark-theme\s*=\s*(true|false)\s*$'
$newValue = 'gtk-application-prefer-dark-theme=true'

$null = (Get-Content $currentSettingsPath) -replace $regex, $newValue | Set-Content -Path $currentSettingsPath -Force
```

### A project I encountered this issue with
[Link](https://github.com/tadghh/deluge-dark-mode/blob/a5593f725aefed119552632c658010f75bd591f2/Set-deluge-dark-mode.ps1)

### Expected behavior

Ini file will only update that one line, instead of being written to by both entries (the shortcut folder containing this file and the real folder). So $scoopInstall should only contain the "real" folder.

```console
[Settings]
gtk-application-prefer-dark-theme=false
```

### Actual behavior

When using the * instead of the path to the folder, this is because of the shortcut folder being included in $scoopInstall
```
# Bug occures with this, as it collects the shortcut too. 
"$env:USERPROFILE\scoop\apps\deluge\*\"

# Doesnt occur when used like this
"$env:USERPROFILE\scoop\apps\deluge\2.1.1\"
```

This is what happens when the wildcard is used, and the shortcut to the folder is included. All of the content inside of the ini file would be duplicated.
```console
[Settings]
gtk-application-prefer-dark-theme=false
[Settings]
gtk-application-prefer-dark-theme=true
```

### Error details
I feel the shortcut folder shouldnt be included since they are in the same parent directory. This is my first bug report, sorry if anything is incorrect.

### Environment data
- Deluge installed through scoop on Windows
```powershell


Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
The term _shortcut [file]_ usually applies to a Windows-only`.lnk` file, which PowerShell cannot read directly.

Are you talking about a _symbolic link_ instead?

**Comment by tadghh** [comment]
> The term _shortcut [file]_ usually refers to a Windows-only`.lnk` file, which PowerShell cannot read directly.
> 
> Are you talking about a _symbolic link_ instead?

I think so, ill double check later. If symbolic links are shown in file explorer than yes, however either way...

**Comment by mklement0** [comment]
Assuming _symlinks_ (symbolic links): 

* It is defensible that `Get-Content` targets _all_ its input paths, even if, among them, some _happen to_ refer to _each other_, via symlinks.

* By contrast - and this is a moot point here - it is problematic that `Set-Content` allows wildcard-based output paths to write to (potentially) _multiple_ output files (which in the case at hand apparently target the _same_ output file, one directly, the other via a symlink):

  * See #6729

**Comment by tadghh** [comment]
> Assuming _symlinks_ (symbolic links):
> 
> * It is defensible that `Get-Content` targets _all_ its input paths, even if, among them, some _happen to_ refer to _each other_, via symlinks.
> * By contrast - and this is a moot point here - it is problematic that `Set-Content` allows wildcard-based output paths to write to (potentially) _multiple_ output files (which in the case at hand apparently target the _same_ output file, one directly, the other via a symlink):
>   
>   * See [Set-Content should not allow writing to multiple files using wildcards #6729](https://github.com/PowerShell/PowerShell/issues/6729)

Hmm, so the file content duplicating is a feature?

**Comment by mklement0** [comment]
It's not a file-content duplication feature.

It is about `Get-Content` honoring all its input paths, whether or not they happen to point to the same file via symlinks (which isn't typical).

**Comment by mklement0** [comment]
If you expect your `$currentSettingsPath` wildcard to only ever to match _one_ file of interest (with any _additional_ matches presumed to be _symlinks to that file_), simply limit your processing to that one file:

```powershell
$targetFile = Get-Item $currentSettingsPath | Select-Object -First 1
(Get-Content -LiteralPath $targetFile) -replace $regex, $newValue | Set-Content -LiteralPath $targetFile
```

**Comment by tadghh** [comment]
> It's not a file-content duplication feature.
> 
> It is about `Get-Content` honoring all its input paths, whether or not they happen to point to the same file via symlinks (which isn't typical).

Regardless why would Get-Content include folders and symlinks that are in the same folder, the symlink should be ignored.



> If you expect your `$currentSettingsPath` wildcard to only ever to match _one_ file of interest (with any _additional_ matches presumed to be _symlinks to that file_), simply limit your processing to that one file:
> 
> ```powershell
> $targetFile = Get-Item $currentSettingsPath | Select-Object -First 1
> (Get-Content -LiteralPath $targetFile) -replace $regex, $newValue | Set-Content -LiteralPath $targetFile
> ```

I solved it by just using the name of the symlink itself. Wanted to post this issue because this behaviour should be changed. And as content for other people who might have the same issue. Thanks for helping me understand this and your workaround for now!

**Comment by 237dmitry** [comment]
I think Get-Content doesn't analyze whether a file is a symbolic link or not.

```powershell
$ "12345" | Set-Content file.txt
$ ln -sr file.txt file-symlink.txt
$ dir file*

    Directory: ~/Desktop

UnixMode     Num   UID   GID      LastWriteTime    Size Name
--------     ---   ---   ---      -------------    ---- ----
lrwxrwxrwx   644  1000  1000   26.12.2023 13:01       8 file-symlink.txt -> file.txt
-rw-r--r--   644  1000  1000   26.12.2023 13:00       6 file.txt

$ Get-Content file*
12345
12345
```

**Comment by mklement0** [comment]
> doesn't analyze whether a file is a symbolic link or not.

Indeed, @237dmitry, and I don't think it _should_: it isn't the mandate of wildcard pathname resolution (globbing)  to treat matches that happen to be symlinks differently, or to weed out duplicates.

POSIX-compatible shells such as Bash don't do that either.

Symlinks only get special treatment during _deletion_ (removing a symlink only removes the link itself, not its target) and in the context of _recursive enumeration_ of a directory tree (following directory symlinks requires opt-in via `-FollowSymlink`)

@tadghh, I'm glad we have a shared understanding now, but as for a potential change in behavior:

Given the above, I don't think the symlink should be ignored.
The very purpose of a symlink such as in your case (I'm assuming that it has an _abstract_ name such as `latest`) is to not require use of wildcards in the first place.

(On a general note: I'm just a fellow user.)
