### ISSUE TITLE
vs code : Configured debug type 'coreclr' is not supported.

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#2097]
On Windows 10. I pulled the latest, successfully did Start-PSBuild and ran the new version. 

Launched vs code  and pressed F5. On my other machine, it builds and runs the exe.

![image](https://cloud.githubusercontent.com/assets/67258/18030257/55a7e474-6c7d-11e6-8699-4c057c331f46.png)

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.0.10586.494                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.10586.494                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

**Comment by adamdriscoll** [comment]
Did you install the C# extension for VS Code and get the debugger extension?

**Comment by dfinke** [comment]
Thanks Adam, worked.

**Comment by MgKyaw** [comment]
Debugger extension means "Debugger for Chrome"?
I'm not still ok.
pls help me

**Comment by SridharPasham** [comment]
I am facing the same issue. What do mean by debugger extension?

**Comment by adamdriscoll** [comment]
Debugger for C#. When you install the C# extension, it downloads the OmniSharp packages which include the C# debugger.

**Comment by Mike-EEE** [comment]
For added clarity, this is the extension that is required:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

The message mentioned in the topic title went away after installing this extension.

**Comment by chaim1221** [comment]
It's worth mentioning (got here via the googles) that just because you have the C# package installed on the Windows side does not mean it is installed on the WSL server. Reinstall the extension with the WSL server open.

**Comment by PeterWone** [comment]
Apropos of the very important comment by @chaim1221 

Click the little cloud-download icon next to "SSH: LINUX-DOCKER-HOST"
![image](https://user-images.githubusercontent.com/5498936/133382792-41a018fe-4ee1-4f8b-bccb-0e063c9961a0.png)

You will get a list of locally installed extensions that you can push to the server.

![image](https://user-images.githubusercontent.com/5498936/133382990-e39eba70-253d-4ff4-a75f-e7e6d3f43caa.png)

Tick everything you need then click the OK button.

**Comment by devgis** [comment]
> On Windows 10. I pulled the latest, successfully did Start-PSBuild and ran the new version.
> 
> Launched vs code and pressed F5. On my other machine, it builds and runs the exe.
> 
> ![image](https://cloud.githubusercontent.com/assets/67258/18030257/55a7e474-6c7d-11e6-8699-4c057c331f46.png)
> 
> ```
> Name                           Value                                                                                   
> ----                           -----                                                                                   
> PSVersion                      5.0.10586.494                                                                           
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
> BuildVersion                   10.0.10586.494                                                                          
> CLRVersion                     4.0.30319.42000                                                                         
> WSManStackVersion              3.0                                                                                     
> PSRemotingProtocolVersion      2.3                                                                                     
> SerializationVersion           1.1.0.1                                                                                 
> ```
Hi , have you already fixed this issues,I met this on ubuntu .Could you please give me some suggests?Thanks!
