### ISSUE TITLE
Import-CliXML doesn't rehydrate object when TargetTypeForDeserialization is specified

### ISSUE THREAD

**Issue by MartinGC94** [PowerShell/PowerShell#20984]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

According to this blogpost: https://devblogs.microsoft.com/powershell/how-objects-are-sent-to-and-from-remote-sessions/ PowerShell includes the ability to rehydrate serialized objects if you add a TargetTypeForDeserialization property to the PSObject but this doesn't seem to work with `Import-CliXML` here's the code I've used to test this:
<details>
  <summary>C# class library (.NET standard 2.0)</summary>

```
using System;
using System.Management.Automation;

namespace ClassLibrary2
{
    public class Class1
    {
        public string Prop1 { get; set; }
        public int Prop2 { get; set; }
    }

    public class Class2 : PSTypeConverter
    {
        public override bool CanConvertFrom(PSObject sourceValue, Type destinationType)
        {
            return true;
        }

        public override bool CanConvertTo(PSObject sourceValue, Type destinationType)
        {
            return true;
        }

        public override object ConvertFrom(PSObject sourceValue, Type destinationType, IFormatProvider formatProvider, bool ignoreCase)
        {
            return new Class1();
        }

        public override object ConvertTo(PSObject sourceValue, Type destinationType, IFormatProvider formatProvider, bool ignoreCase)
        {
            return new Class1();
        }

        public override bool CanConvertFrom(object sourceValue, Type destinationType)
        {
            return true;
        }

        public override bool CanConvertTo(object sourceValue, Type destinationType)
        {
            return true;
        }

        public override object ConvertFrom(object sourceValue, Type destinationType, IFormatProvider formatProvider, bool ignoreCase)
        {
            return new Class1();
        }

        public override object ConvertTo(object sourceValue, Type destinationType, IFormatProvider formatProvider, bool ignoreCase)
        {
            return new Class1();
        }
    }
}
```

</details>

<details>
  <summary>types.ps1xml</summary>

```
<?xml version="1.0" encoding="utf-8" ?>
<Types>
    <Type>
        <Name>Deserialized.ClassLibrary2.Class1</Name>
        <Members>
            <MemberSet>
            <Name>PSStandardMembers</Name>
            <Members>
                <NoteProperty>
                    <Name>TargetTypeForDeserialization</Name>
                    <Value>ClassLibrary2.Class2</Value>
                </NoteProperty>
            </Members>
            </MemberSet>
        </Members>
    </Type>
</Types>
```

</details>

<details>
  <summary>PS code</summary>

```
Add-Type -Path $HOME\source\repos\ClassLibrary2\ClassLibrary2\bin\Debug\netstandard2.0\ClassLibrary2.dll
Update-TypeData -PrependPath $HOME\types.ps1xml
[ClassLibrary2.Class1]@{Prop1="Hello";Prop2=2} | Export-Clixml $HOME\TempExport.xml -Force
$Res = Import-Clixml $HOME\TempExport.xml
$Res.GetType()
```
</details>

I realize the blogpost is talking about remoting scenarios, but I still think it should work with `Import-Clixml` because if I try to Export/Import one of the types that are natively supported, like `ipaddress` then it works perfectly fine, so it seems to only be an issue for third party types.

### Expected behavior

```console
FullName             BaseType
--------             --------
ClassLibrary2.Class1 System.Object
```

### Actual behavior

```console
FullName                              BaseType
--------                              --------
System.Management.Automation.PSObject System.Object
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-rc.1
PSEdition                      Core
GitCommitId                    7.4.0-rc.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Does the exported file TempExport.xml have the fully qualified type name encoded in the TargetTypeForDeserialization property? Could you post here what that XML looks like?

**Comment by MartinGC94** [comment]
No, but I also don't think it should have that. My understanding of this is that the deserialization process creates a PSObject where the typenames include the original typenames with a `Deserialized.` prefix and then Extended Types System takes over and sees a type in the `types.ps1xml` file that says "Add these members" and one of those members is this magic deserialization property.

Here you can see the exported XML:

    <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
      <Obj RefId="0">
        <TN RefId="0">
          <T>ClassLibrary2.Class1</T>
          <T>System.Object</T>
        </TN>
        <ToString>ClassLibrary2.Class1</ToString>
        <Props>
          <S N="Prop1">Hello</S>
          <I32 N="Prop2">2</I32>
        </Props>
      </Obj>
    </Objs>

And the typenames for an imported object looks like this:

    PS C:\Users\Martin> $Res.psobject.TypeNames
    Deserialized.ClassLibrary2.Class1
    Deserialized.System.Object

I can even see the magic property:

```
PS C:\Users\Martin> $Res.PSStandardMembers.TargetTypeForDeserialization

FullName             BaseType
--------             --------
ClassLibrary2.Class2 System.Management.Automation.PSTypeConverter
```

**Comment by fMichaleczek** [comment]
@MartinGC94 you should read this one https://github.com/PowerShell/PowerShell/issues/3173

**Comment by MartinGC94** [comment]
@fMichaleczek Thank you, it works perfectly after modifying the types XML to look like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <Types>
       <Type>
          <Name>ClassLibrary2.Class1</Name>
          <TypeConverter>
             <TypeName>ClassLibrary2.Class2</TypeName>
          </TypeConverter>
          <Members>
             <MemberSet>
                <Name>PSStandardMembers</Name>
                <Members>
                   <NoteProperty>
                      <Name>SerializationDepth</Name>
                      <Value>1</Value>
                   </NoteProperty>
                </Members>
             </MemberSet>
          </Members>
       </Type>
       <Type>
          <Name>Deserialized.ClassLibrary2.Class1</Name>
          <Members>
             <MemberSet>
                <Name>PSStandardMembers</Name>
                <Members>
                   <NoteProperty>
                      <Name>TargetTypeForDeserialization</Name>
                      <Value>ClassLibrary2.Class1</Value>
                   </NoteProperty>
                </Members>
             </MemberSet>
          </Members>
       </Type>
    </Types>
