### ISSUE TITLE
`Start-Process` and `Invoke-Item` on Linux: opening document files is broken / doesn't provide meaningful error messages

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#20992]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note:

* Related: #20990 - `Start-Process` on Linux too seems to behave differently depending on whether a _mere file name_ or document _path_ is given.

* The problems may go away if `xdg-open` is installed on a given distro (which is required for opening _documents_) - I 
cannot verify that - but at the very least the misleading error messages should be fixed.

  * _Update_: @237dmitry confirms that with `xdg-open` present, `Invoke-Item` works properly, but `Start-Process` exhibits the same problem as on macOS (#20990). The upshot: the latter bug needs fixing, which both macOS and Linux will benefit from, and the error messages need updating (which is only relevant on Linux, given that macOS' `xdg-open` analog, `open`, ships with the OS).

```powershell
'hi' > sample.txt

Start-Process sample.txt
Start-Process ./sample.txt

Invoke-Item sample.txt
Invoke-Item ./sample.txt
```

The results below were obtained on a CBL-Mariner/Linux Docker image (`docker run -it mcr.microsoft.com/powershell:7.4-mariner-2.0-arm64`), without `xdg-open` present.

### Expected behavior

* Without `xdg-open` present, an error stating that it is required should be emitted.
* With `xdg-open` present, all commands should succeed.

### Actual behavior

The following errors occur:

```console
Start-Process: This command cannot be run due to the error: An error occurred trying to start process 'sample.txt' with working directory '/root'. No such file or directory
Start-Process: An error occurred trying to start process '/root/sample.txt' with working directory '/root'. Permission denied
Invoke-Item: An error occurred trying to start process '/root/sample.txt' with working directory '/'. No such file or directory
Invoke-Item: An error occurred trying to start process '/root/sample.txt' with working directory '/'. No such file or directory
```

Note how the two `Start-Process` calls result in different error message, similar to what happens on macOS (#20990)
The first `Start-Process` call and the two `Invoke-Item` calls essentially result in the spurious "No such file or directory" error.

### Error details

* `No such file or directory error`:

```console
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 2
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : ForkAndExecProcess
        DeclaringType : System.Diagnostics.Process
        MemberType    : Method
        Module        : System.Diagnostics.Process.dll
    Message         : An error occurred trying to start process '/root/sample.txt' with working directory '/'. No such file or directory
    Source          : System.Diagnostics.Process
    HResult         : -2147467259
    StackTrace      :
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32
userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.Commands.FileSystemProvider.InvokeDefaultAction(String path)
   at System.Management.Automation.SessionStateInternal.InvokeDefaultActionPrivate(CmdletProvider providerInstance, String path, CmdletProviderContext context)
CategoryInfo          : NotSpecified: (:) [Invoke-Item], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.InvokeItemCommand
InvocationInfo        :
    MyCommand        : Invoke-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 22
    Line             : Invoke-Item ./sample.txt
    Statement        : Invoke-Item ./sample.txt
    PositionMessage  : At line:1 char:1
                       + Invoke-Item ./sample.txt
                       + ~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

* `Permission denied` error:

```console
Exception             :
    Type            : System.ComponentModel.Win32Exception
    NativeErrorCode : 13
    ErrorCode       : -2147467259
    TargetSite      :
        Name          : ForkAndExecProcess
        DeclaringType : System.Diagnostics.Process
        MemberType    : Method
        Module        : System.Diagnostics.Process.dll
    Message         : An error occurred trying to start process '/root/sample.txt' with working directory '/root'. Permission denied
    Source          : System.Diagnostics.Process
    HResult         : -2147467259
    StackTrace      :
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32
userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : NotSpecified: (:) [Start-Process], Win32Exception
FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.StartProcessCommand
InvocationInfo        :
    MyCommand        : Start-Process
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 25
    Line             : Start-Process ./sample.txt
    Statement        : Start-Process ./sample.txt
    PositionMessage  : At line:1 char:1
                       + Start-Process ./sample.txt
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Start-Process
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
PowerShell 7.4.0 on Linux, without `xdg-open` present.
```

**Comment by 237dmitry** [comment]
Invoke-Item works, Start-Process returned error (Permission denied)

**Comment by mklement0** [comment]
Thanks, @237dmitry. This means that the `Start-Process` bug is the same as on macOS (#20990) and that - for the sake of Linux - the error messages in the absence of `xdg-open` should be improved. I've updated the initial post accordingly.

**Comment by mklement0** [comment]
@rhubarb-geek-nz, what you're quoting says "not recommended", not that it _shouldn't work_, but the root-user aspect is an incidental aspect anyway (came from my using a Docker image):

* When you do attempt to use `xdg-open` _directly_ as the root user, what happens? if it still works, then it should also work from PowerShell; if not, a _meaningful_ error message should be emitted.

  * As an aside: If you run in WSL 1 (I don't have access to WSL 2) without `xdg-open` present and target a document in the _Windows_ file system (`/mnt/c/...`), you'll get "Exec format error", because an attempt is made to directly execute a document, as seemingly _all_ files in the Windows file system have the execute bit set (`-rwxrwxrwx`). With `xdg-open` present, it still tries direct execution first, then falls back to `xdg-open` (or similar, see below).

* The bottom line is the problem now summarized in the initial post: there's a `Start-Process` bug that affects both macOS and Linux, and there's the problem of misleading / unhelpful error messages, which effectively surface only on Linux (because the `/usr/bin/open` utility required on macOS comes with the OS and is therefore guaranteed to be present).

  * That said, the unhelpful error messages may actually come from the .NET layer (see below).

---

It isn't PowerShell that depends on `xdg-open` (and on `/usr/bin/open` on macOS), but .NET itself, to support the [`.UseShellExecute`](https://learn.microsoft.com/en-US/dotnet/api/system.diagnostics.processstartinfo.useshellexecute) property in a cross-platform manner - unfortunately, the linked help topic doesn't state that, but you can see it in the source code:

* [Linux](https://github.com/dotnet/runtime/blob/9e31c21bcbb661fc4fa235839a66442a65ef447c/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs#L110): this actually shows that any one of _three_ utilities is used, if available: `xdg-open`, `gnome-open` or `kfmclient`

* [macOS](https://github.com/dotnet/runtime/blob/9e31c21bcbb661fc4fa235839a66442a65ef447c/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs#L52)

The confusing `No such file or directory` error message presumably reflects the inability to find one of the _helper utilities_ on Linux and therefore amounts to leaking an implementation detail.


---

Unless I missed something in my analysis, I'll eventually close this in favor of:

* #20990, for the PowerShell-side bug (`Start-Process`)
* A yet to be created .NET issue re misleading error message.

**Comment by rhubarb-geek-nz** [comment]
Regarding WSL, my wsl.conf has the following to stop it seeing the windows file system.

```
[automount]
enabled=false

[interop]
enabled=false
appendWindowsPath=false
```

**Comment by 237dmitry** [comment]
I would like to add. Files are opened without additional commands, just:

```
$ ./file.txt
$ ./Pictures/picture.png
````

**Comment by mklement0** [comment]
Good point, @237dmitry  - that is the equivalent of using `Invoke-Item`.

**Comment by mklement0** [comment]
Closing in favor of:

* #20990 for the `Start-Process` bug.

* [external] For the misleading error message: https://github.com/dotnet/runtime/issues/96565

* [external, documentation] https://github.com/dotnet/dotnet-api-docs/issues/9534
