### ISSUE TITLE
Provide build instructions of powershell source on linux that does not require a powershell binary to bootstrap.

### ISSUE THREAD

**Issue by gl-yziquel** [PowerShell/PowerShell#21010]
### Summary of the new feature / enhancement

Provide build instructions of powershell source on linux that does not require a powershell binary to bootstrap.

**Comment by kilasuit** [comment]
Adding this as a task for #21006

**Comment by gl-yziquel** [comment]
It's kind of a blocker for me: I like to use things I build myself.

If I can't build it, I usually tend to move to something else.

**Comment by jborean93** [comment]
You can look at how Gentoo builds pwsh themselves from scratch https://gitweb.gentoo.org/repo/gentoo.git/tree/app-shells/pwsh/pwsh-7.4.0.ebuild. IIRC this has been requested in the past but the pwsh team don't want to document and maintain such a thing and just rely on their existing build scripts for pwsh.

**Comment by SteveL-MSFT** [comment]
The PS7 codebase is complex to build so lots of the logic is in build.ps1.  When this project was simpler, we did have a bash script for builds, but maintaining both didn't make sense as we no longer relied on the bash script.  As MSBuild has evolved, there has been some small changes (by the community) to move some of the code in build.ps1 into csproj, but it's not a priority for the team.

**Comment by kilasuit** [comment]
There is the [docs/building/internals.md](https://github.com/PowerShell/PowerShell/blob/master/docs/building/internals.md) file that loosely goes into detail about how the build process works without needing to use the build module. This perhaps could be better highlighted in other docs but should still strongly recommend using the functions from the build.psm1 for building for the best experience.
