### ISSUE TITLE
Allow using [ and ] characters without backtick escaping

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#21017]
### Summary of the new feature / enhancement

This backtick escaping creates so much troubles:
https://github.com/PowerShell/PowerShell/issues/14149
https://github.com/PowerShell/PowerShell/issues/16218
https://github.com/PowerShell/PowerShell/issues/21013
https://github.com/PowerShell/PowerShell/issues/21016
https://github.com/PowerShell/PowerShell/issues/6232
https://github.com/PowerShell/PowerShell/issues/7999
https://stackoverflow.com/questions/64876760/powershell-auto-completion-escapes-special-characters-and-uses-single-quotes
https://stackoverflow.com/questions/69437163/tab-completion-problem-using-start-in-powershell

I really want powershell to work like bash or fish where escaping doesn't break programs like python or is not needed at all when you use "" or ''

**Comment by MartinGC94** [comment]
I completely agree that it was a mistake of them to use valid file name characters as wildcard characters but I can't imagine the PS team would accept such a breaking change now.

**Comment by 237dmitry** [comment]
It's part of the language. How is pwsh, without escaping, supposed to understand what is a directory and what is an indexed variable?

```
$null = mkdir '[test]', '$folders[0]'

$folders = dir -dir

get-item -lp $folders[0]
get-item -lp '$folders[0]'
```

**Comment by mklement0** [comment]
Indeed, the great `-Path` / `-LiteralPath` schism is highly unfortunate.

_Non-breaking_ solutions were previously discussed in (it's a lengthy post; I'm linking to a summary written by me):

* https://github.com/PowerShell/PowerShell/issues/12168#issuecomment-604383872

**Comment by mklement0** [comment]
P.S.: Revisiting the linked post, I see that the PowerShell committee made a recommendation (that is yet to be acted on):

* https://github.com/PowerShell/PowerShell/issues/12168#issuecomment-611241092

**Comment by ArmaanMcleod** [comment]
> P.S.: Revisiting the linked post, I see that the PowerShell committee made a recommendation (that is yet to be acted on):
> 
> * https://github.com/PowerShell/PowerShell/issues/12168#issuecomment-611241092

Another issue which is up for grabs and never should have been closed by bot.

**Comment by SteveL-MSFT** [comment]
Re-opened #12168 so resolving this as dupe
