### ISSUE TITLE
Create a OneBranch pipeline for vPack 

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#21058]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This is an issue for tracking progress.

### Expected behavior

```console
NA
```

### Actual behavior

```console
NA
```

### Environment data

```powershell
NA
```

**Comment by TravisEz13** [comment]
Completed
