### ISSUE TITLE
PowerShell Snap Out of Date

### ISSUE THREAD

**Issue by juvtib** [PowerShell/PowerShell#21056]
The [PowerShell snap](https://snapcraft.io/powershell) is out of date. I've reported this issue in the past and been told to buzz off. I'd like the release process to be smoother. 

Regards, 

``` PowerShell
PowerShell 7.4.0

   A new PowerShell stable release is available: v7.4.1 
   Upgrade now, or check out the release page at:       
     https://aka.ms/PowerShell-Release?tag=v7.4.1       

> sudo snap refresh
All snaps up to date.

> snap list powershell
Name        Version  Rev  Tracking       Publisher              Notes
powershell  7.4.0    261  latest/stable  microsoft-powershell✓  classic

```

**Comment by juvtib** [comment]
It has been three days, and the [PowerShell Snap](https://snapcraft.io/powershell) has not been updated. 

I know the reflex will be to say this is not important and nothing can be done. 

But let me point out several things. 

* I'm using an officially [supported build](https://learn.microsoft.com/powershell/scripting/install/install-other-linux). 
* This issue has occurred before: 
  * #17208 
  * #17564 
  * #18357
  * #19247 (Original Edit)
* Canonical has a [page dedicated](https://snapcraft.io/build) to supporting the Microsoft build process.  
* It was the PowerShell Team that decided to release at 5 o'clock on a Friday. 

And remember that if the release included a security patch—in PowerShell or .NET—I'd be going days without a fix simply because of a broken build process. 

I just want this obvious problem addressed. 

Thanks,

**Comment by BinaryWizard904** [comment]
Looks like they're having some issues with distribution in general lately.  The Microsoft Update version also hasn't been updated since November of 2023 (#21087), so the cause might be a bit broader than a snap-specific issue.

Distribution to the Microsoft Linux Software Repository still works, but I suppose that's to be expected as they specifically made modifications there when releasing v7.4.1.

**Comment by StevenBucher98** [comment]
@juvtib Please check that the snap release is there, it should be available now.

**Comment by juvtib** [comment]
I think this is a systemic problem. It is difficult to believe that one-off problems have affected every snap release. 

But I can see we don't agree. 

Regards,
