### ISSUE TITLE
v7.4.1 Debian package missing on https://packages.microsoft.com/debian/11/prod/pool/main/p/powershell/

### ISSUE THREAD

**Issue by gone-for-coding** [PowerShell/PowerShell#21075]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On 2024-01-11 the following versions were released:
- 7.4.1
- 7.3.11
- 7.2.18

A Debian package was pushed to https://packages.microsoft.com/debian/11/prod/pool/main/p/powershell/ for all but `7.4.1`. Please fix that because our build pipelines are failing. Thanks!

### Expected behavior

```console
7.4.1 has a Debian package on https://packages.microsoft.com/debian/11/prod/pool/main/p/powershell/.
```

### Actual behavior

```console
Package is missing.
```

### Environment data

```powershell
-
```

**Comment by rgl** [comment]
Ditto for Ubuntu.

Is there some kind of public place where we can see why those release deployments failed?
