### ISSUE TITLE
Private variables created inside profile script are treated as global

### ISSUE THREAD

**Issue by agaace** [PowerShell/PowerShell#21088]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create script `foo.ps1` that creates a local variable:

```pwsh
New-Variable -scope Local -option Private -name "foo" -value "My private foo"
Write-Host "Foo: $foo"
```

Now run the script:
```pwsh
PS> ./foo
Foo: My private foo
PS> Write-Host "Foo: $foo"
Foo:
```

All is well, the private variable works as expected.

Now save the same script as `$HOME/Documents/PowerShell/Microsoft.PowerShell_profile.ps1` and start a new PowerShell session so that it executes on startup.

Now run the following:
```pwsh
PS> Write-Host "Foo: $foo"
Foo: My private foo
```

I expected `$foo` to be undefined, but instead it's available globally in every session I start.

The private variable `$foo` is now in global scope, as if the execution of `$HOME/Documents/PowerShell/Microsoft.PowerShell_profile.ps1` never finished and I'm still inside the scope of the script.

If this behavior is by design, is it documented somewhere? How can I create temporary, private variables inside `$HOME/Documents/PowerShell/Microsoft.PowerShell_profile.ps1` that I don't want to be accessible globally in every session that I start?

### Expected behavior

```console
PS> Write-Host "Foo: $foo"
Foo:
```

### Actual behavior

```console
PS> Write-Host "Foo: $foo"
Foo: My private foo
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
> The private variable `$foo` is now in global scope, as if the execution of `$HOME/Documents/PowerShell/Microsoft.PowerShell_profile.ps1` never finished and I'm still inside the scope of the script.

The profile is dot sourced, so basically yes it's the same scope. You can manually create a new scope by enclosing in `& { }`, e.g.

```powershell
# profile.ps1
& {
    $myTempVar = 'something only needed in this block'
}

$stuffYouWant = 'var'
function ToBeAccessibleOutHere {
}
```
