### ISSUE TITLE
Get-Error can hang on certain exceptions

### ISSUE THREAD

**Issue by jborean93** [PowerShell/PowerShell#21083]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

There is something about the exception raised by `Assembly.GetTypes()` that is causing `Get-Error` to get stuck in some loop and use up all system resources. In dotnet 8 loading the `System.Data.SqlClient` causes an error when attempting to get the types of that assembly. While this is a known problem attempting to use `Get-Error` to produce more information causes the shell to hang and start to consume all the system resources.

I've narrowed it down to the formatting of this particular error record in the formatting code https://github.com/PowerShell/PowerShell/blob/b2ba58442353e740d5e2a45a804da6cfef6c21a3/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L831. You can run this in pwsh with https://gist.github.com/jborean93/54a9c7fc999b13ddddaf36d716fe7916 to be able to step through the code that hangs. I haven't figured out what property on this particular exception is actually causing the problem but there is something there. My money is on `Types` or `LoaderExceptions` in `$Error[0].Exception.InnerException`.

### Expected behavior

```console
Add-Type -Assembly System.Data.SqlClient

# This will raise an exception
[System.Data.SqlClient.SqlCredential].Assembly.GetTypes()

# Calling Get-Error after "hangs"
Get-Error
```

### Actual behavior

```console
Shows the error without hanging
```

### Error details

```console
Nothing, it hangs
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Arch Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ninmonkey** [comment]
I was having trouble getting tracing to log when running. I was able to figure out it seems to be in an infinite loop
It keeps running down until line 160, then jumps to 41, runs to 160, jumps to 41, and never quits looping.

I am piping a single `ErrorRecord` 

[40-160 maps to this script extent](https://github.com/PowerShell/PowerShell/blob/b2ba58442353e740d5e2a45a804da6cfef6c21a3/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L873C9-L989)

Ideas

- error record's types are modified while looping 
- `Show-ErrorRecord` *is* recursive and it's using LangyPrimatives to prevent conversion errors
- If you hit `ctrl+c` after `Get-Error` -- **there are no errors added to `$global:error.count`**

Maybe there *isn't* an error being thrown in `Get-Error`
Maybe it's a logic error, where the exit condition never occurs. 
That would align with error's not being added on `ctrl+c`

I tried manually triggering conversion errors on the properties of the ErrorRecord, thinking one of the properties would throw. I get nulls, but nothing throws. That's partly what made me think there might not be errors thrown.
```ps1
$NullStr = "`u{2400}"
$error[0].psobject.properties | %{
    $IsTrueNull = $null -eq $_.Value
    $Value?     = $IsTrueNull ? $NullStr : $_.Value
    $tinfo      = $IsTrueNull ? $NullStr : $_.Value.GetType()
    $tinfo_IsIEnumerable = $IsTrueNull ? $NullStr :
            ($null -ne $tinfo.GetInterface('IEnumerable'))            

    $render = $IsTrueNull ? $NullStr :
            $_.Value.ToString()

    [string]$LangyValue = ''
    $LangyOk = [System.Management.Automation.LanguagePrimitives]::TryConvertTo(
        $_.Value, [string], [ref]$LangyValue) -and $LangyValue -ne $null

    $Info = [ordered]@{
        Name               = $_.Name
        TrueNull           = $null -eq $_.Value
        Value              = $Value?
        Type               = $Tinfo
        TinfoIsIEnumerable = $tinfo_isIEnumerable
        ToStr              = $Render
        LangyOk            = $LangyOk
        Langy              = $LangyValue
    }
    [pscustomobject]$info
}|ft
```

```
Name                  TrueNull Type                                                              TinfoIsIEnumerable ToStr
----                  -------- ----                                                              ------------------ -----                                                                                                     
PSMessageDetails          True ␀                                                                 ␀                  ␀
Exception                False System.Management.Automation.MethodInvocationException            False              System.Management.Automation.MethodInvocationException: Exception calling "GetTypes" with "0" argument(s)…
TargetObject              True ␀                                                                 ␀                  ␀
CategoryInfo             False System.Management.Automation.ErrorCategoryInfo                    False              NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId    False System.String                                                     True               ReflectionTypeLoadException
ErrorDetails              True ␀                                                                 ␀                  ␀
InvocationInfo           False System.Management.Automation.InvocationInfo                       False              System.Management.Automation.InvocationInfo
ScriptStackTrace         False System.String                                                     True               at <ScriptBlock>, H:\data\2024\pwsh\sketch\2024-01-16-PwshCmdlet\debug_harness-iter2.ps1: line 37…
PipelineIterationInfo    False System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32] True               System.Collections.ObjectModel.ReadOnlyCollection`1[System.Int32]
```

**Comment by jborean93** [comment]
The problem occurs when trying to serialize an array of `Type` instances. In this case `Assembly.GetTypes()` contains an `InnerException` of [ReflectionTypeLoadException](ReflectionTypeLoadException) with the [Types](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception.types?view=net-8.0#system-reflection-reflectiontypeloadexception-types) property that is `Type[]`. The `Type` type has a lot of properties that is heavily nested and just contains a lot of runtime data that brings the serialization down to its knees. You can see this by doing `ConvertTo-Json ([string])`, the default depth shows how many properties need to be serialized and increasing the depth just causes it to hang.

A quick reproducer is

```powershell
class MyException : Exception {
    [Type[]]$Types

    MyException ([string]$Message) : base($Message) {
        $this.Types = @([string], [int])
    }
}

$exc = [MyException]::new("custom")

try { throw $exc } catch {}
Get-Error
```

The formatter should handle this and probably just return `FullName` or `Name` instead of trying to serialize the whole `Type` instance.

**Comment by jborean93** [comment]
PR which can handle this issue (as well as other primitive types) https://github.com/PowerShell/PowerShell/pull/21085
