### ISSUE TITLE
A Microsoft Update for PowerShell Has Not Been Released Since November 2023

### ISSUE THREAD

**Issue by BinaryWizard904** [PowerShell/PowerShell#21087]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I manage a number of Windows Server 2022 instances that have PowerShell 7 installed on them. Since Microsoft started releasing Updates for PowerShell through Microsoft Update in v7.2, we have been using that to reliably distribute updates to these servers via WSUS.  As a reminder, neither winget nor Microsoft Store are available on Windows Server, so this is the only supported means of automated updating.

Unfortunately, according to the [Microsoft Update Catalog](https://catalog.update.microsoft.com/Search.aspx?q=powershell), the last time an update for PowerShell was released was on 2023-11-27.  As such the latest versions of PowerShell available are: v7.3.10 or v7.2.17 (LTS).

There is _no_ general release of v7.4 LTS at all, and even the 7.2 &  7.3 releases are now out of date.  While the [documentation](https://learn.microsoft.com/en-us/powershell/scripting/install/microsoft-update-faq?view=powershell-7.4#how-soon-after-release-are-updates-advertised-by-microsoft-update) makes clear that some delay is to be expected, it is only supposed to take "up to two weeks for [a] version to become available through Microsoft Update".

[WindowsUpdate.log](https://github.com/PowerShell/PowerShell/files/13965953/WindowsUpdate.log)

### Expected behavior

```console
A Microsoft Update for releases of PowerShell will be issued within two weeks of release.
```

### Actual behavior

```console
No update is released.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.17
PSEdition                      Core
GitCommitId                    7.2.17
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.20348 Microsoft Windows Server 2022 Standard
```

### Windows update log

```markdown
[WindowsUpdate.log](https://github.com/PowerShell/PowerShell/files/13965953/WindowsUpdate.log)
```

**Comment by StevenBucher98** [comment]
Just so I am clear are you expecting 7.2.x and 7.3.x to be upgraded to 7.4? We were intentionally holding off updating these versions to 7.4 to ensure its stability however have ran into some roadblocks for updating any 7.4.x versions. We apologize for the inconvenience and hope to resolve this issue soon.

**Comment by BinaryWizard904** [comment]
I'm expecting you to issue updates for PowerShell via Microsoft Update.  Be they automatic updates from 7.2 and 7.3 to 7.4 or silod by minor version like 7.2 and 7.3 are now.

At worst, I expected that you would make it available as a pull-only update in the catalog so that interested admins could manually import it into WSUS.  Similar to many hot fixes.

**Comment by StevenBucher98** [comment]
7.2 and 7.3 minor versions have had no interruptions with their MU update cycles, they currently still have the 1-2 week delay from when the GitHub release is published, I believe the next update to these versions will be Monday. 7.4 is having issues but we are working hard to resolve it

**Comment by SteveL-MSFT** [comment]
Note that the 1-2 week delay is due to how we submit updates to Microsoft Update and not in our control

**Comment by OranguTech** [comment]
FWIW, 7.3.11 and LTS 7.2.18 are in the Update Catalog as of today at least, date published says 1/22/24.
That being said @SteveL-MSFT  - Some public communication besides having to find a github issue would be helpful. There's been no powershell blog posts since 7.4 GA, which is where I would look/expect.

P.S. - Slightly OT, but it does kinda of feel like the LTS aspect of Pwsh get overlooked: 

- https://learn.microsoft.com/en-us/powershell/scripting/install/microsoft-update-faq?view=powershell-7.4#i-am-on-powershell-7-2--why-have-i-not-been-upgraded-to-7-3 still lists 7.2 as current LTS.
- There no LTS marked version available in Winget, so if you winget as a source and try to keep updated w/ point releases, you get upgraded to the next version.
- I don't think I've ever seen a definitive list of what the default upgrade paths/behaviors are, or how to override them: Official documentation would be very helpful.

**Comment by SpaghettiCodeIsFun** [comment]
Powershell 7.4.1 was released on Microsoft Catalog on 20/02/2024 and is ready available on WSUS as well.

Interestingly, the base release is not available (7.4.0), just the RC.

**Comment by OranguTech** [comment]
Additionally, 7.4.x is still not listed as LTS in MUC. Search for 'Powershell LTS' and you only get 7.2.x results.

**Comment by StevenBucher98** [comment]
@OranguTech the LTS will be switched as soon as 7.2 is out of support

**Comment by OranguTech** [comment]
> @OranguTech the LTS will be switched as soon as 7.2 is out of support

Good to know, thanks. I've not seen that explained/announced anywhere.  I'm quite familiar with the vagaries of "support" for Microsoft's commercial offerings, but this is a slightly different model/pattern than I've seen used for anything else that has designated LTS versions. (At least in the larger Open Source world.)
