### ISSUE TITLE
`Invoke-WebRequest -PassThru`, when combined with `-OutFile`, should reflect the download file path.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#21082]
### Summary of the new feature / enhancement

Thanks to a contribution by @CarloToso, since v7.4.0 it has been possible to pass a _directory_  rather than a file path to `-OutFile`, in which the web cmdlets use the (ultimate) target URL's _last segment_ as the file name.

Given that, when redirections are involved,  you won't know what that last segment is, being able to _programmatically_ discover the resulting full download file path is important.

This will also apply to the planned support for using a  _server-suggested_ output file name via a `Content-Disposition` response header field - see PR https://github.com/PowerShell/PowerShell/pull/19385

(Using `-Verbose` is a way to discover the file name _interactively_; while it's technically possible to programmatically parse the verbose output, that would be both cumbersome and brittle).

Thus - at least when `-OutFile` is used - the `[Microsoft.PowerShell.Commands.WebResponseObject]` instance returned via `-PassThru` should have an `.OutFile` property or similar that reflects the output file's full path.

Related:

 * #21081

### Proposed technical implementation details (optional)

I don't know whether it's worth extending `[Microsoft.PowerShell.Commands.WebResponseObject]` or not.

If not, an ETS `NoteProperty` member could be used.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this, we agree that since the information is already available, it makes sense to have it as a NoteProperty rather than in the verbose stream
