### ISSUE TITLE
Add Cmdlets for storing Credentials in OS credential store

### ISSUE THREAD

**Issue by ffeldhaus** [PowerShell/PowerShell#2110]
The `Get-Credential` works well for interactive sessions, but to execute scripts non-interactively, credentials often need to get stored in a secure place, which is a challenge for most PowerShell users. As at least Windows and Mac OS X (Keychain) offer secure credential stores, it would be great if Cmdlets could be added to PowerShell to securely store credentials in the OS credential store. [PowerShell Credentials Manager, an implementation for Windows PowerShell can be found in the Technet Gallery](https://gallery.technet.microsoft.com/scriptcenter/PowerShell-Credentials-d44c3cde).

This would increase usability of PowerShell for non-interactive scripting and enhance security for the average user.

**Comment by devblackops** [comment]
I think @Jaykul implements what you are asking for in his [BetterCredentials](https://github.com/Jaykul/BetterCredentials) module. That module adds some extra functionality to `Get-Credential`.

```powershell
Get-Credential UserName -Store
```
> If you haven't stored the password for "UserName", you'll be prompted with the regular PowerShell credential prompt, otherwise it will read the stored password.
In either case, it will store (update) the credentials in the Vault 

Perhaps that type of behavior should be added to the native `Get-Credential` cmdlet.

**Comment by ffeldhaus** [comment]
BetterCredentials looks interesting, but it also relies on the `Advapi32.dll` for storing credentials which is Windows specific. Secure Credential Management is essential and enabline PowerShell to use the Credential stores Microsoft and Apple recommends would be a great way to increase security for PowerShell scripts (especially non-interactive ones).

**Comment by Jaykul** [comment]
Although I'd theoretically like to make mine cross-platform, I don't have a MacBookPro anymore, so I won't be implementing that myself...

Since even the credential prompt OS-specific -- they might as well implement cross-platform native storage in the core.

For better or worse, I've actually been considering going the opposite direction, and making the storage pluggable, so that it can use something that's not user+machine specific, maybe KeePass or Thycotic SecretServer etc.

**Comment by iSazonov** [comment]
RFC https://github.com/PowerShell/PowerShell-RFC/pull/208
Please discuss there.
