### ISSUE TITLE
Small typo in Test-Json -SchemaFile error message - PowerShell 7.5-Beta1

### ISSUE THREAD

**Issue by HotCakeX** [PowerShell/PowerShell#21106]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run the following command

```powershell
Test-Json -Path 'UserConfigurations.json' -SchemaFile "Schema.json"
```

With these 2 files

[UserConfigurations.json](https://github.com/PowerShell/PowerShell/files/13993744/UserConfigurations.json)
[Schema.json](https://github.com/PowerShell/PowerShell/files/13993745/Schema.json)

### Expected behavior

```console
The JSON is not valid with the schema: Value should have at least 9 properties at ''
```

### Actual behavior

```console
The JSON is not valid with the schema: Value should have at least9 properties at ''

There is no space between "least" and "9" in the error message
```

### Error details

```console
Test-Json: untitled:Untitled-1:1:1
Line |
   1 |  Test-Json -Path 'C:\Users\Admin\.WDACConfig\UserConfigurations.json'  …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The JSON is not valid with the schema: Value should have at least9 properties at ''
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.1
PSEdition                      Core
GitCommitId                    7.5.0-preview.1
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ArmaanMcleod** [comment]
I believe this is a typo from `JsonSchema.Net`. I linked a pull request, will need @gregsdennis to have a look 🙂.

**Comment by gregsdennis** [comment]
Once I've updated the lib, I'll need to make an update here.
