### ISSUE TITLE
Get-ChildItem does not work with -Path '\\?\'

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/PowerShell#21102]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We are migrating code from PowerShell 5.1 to PowerShell 7.4.1 while running into the following issue:

```powershell
$params = @{
    Path    = '\\?\C:\Temp' # does not work in PowerShell 7.4.1, but does in 5.1
    Recurse = $true
    Filter  = '*.ps1'
    Force   = $true
}
Get-ChildItem @params
```

We are working in a mixed environment where most of the machines are still running PowerShell 5.1 and most of the files are deeply rooted. This is why we use the `\\?\` syntax, to allow PowerShell to not stumble upon "Path too long" errors.

### Expected behavior

We are expecting all `.ps1` files to be found in both versions of PowerShell.

### Actual behavior

In PowerShell 7.4.1 no file is found when using `Path = '\\?\C:\Temp'`.

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Use `-LiteralPath` instead of `-Path`

PS. I don't remember UNC path ever working in PowerShell Core, I might be wrong.

**Comment by mklement0** [comment]
Please see:

* #10805

**Comment by DarkLite1** [comment]
@237dmitry  using `-LiteralPath` instead of `-Path` works fine in both PowerShell version but doesn't work when the code is executed within a PowerShell `job`.

```powershell
# works in PowerShell 5.1 and 7.4.1
$params = @{
    LiteralPathPath = '\\?\C:\Temp' # works in PS 5.1 and 7.4.1
    Recurse         = $true
    Filter          = '*.ps1'
    Force           = $true
}
Get-ChildItem @params
```

Does not work when wrapped within a job:
```PowerShell
$job = Invoke-Command -ScriptBlock {
    $params = @{
        LiteralPathPath = '\\?\C:\Temp' # fails in PowerShell 7.4.1
        Recurse         = $true
        Filter          = '*.ps1'
        Force           = $true
    }
    Get-ChildItem @params
} -ComputerName $env:COMPUTERNAME -AsJob

$job | Wait-Job | Receive-Job
```
This might have something to do with PowerShell 7.4.1 using PowerShell 5.1 within its job?
