### ISSUE TITLE
FileInfo returns different paths

### ISSUE THREAD

**Issue by matejskubic** [PowerShell/PowerShell#21104]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```ps1
cd /
New-Item test.txt

(ls .\test.txt).FullName
# C:\test.txt

([System.IO.FileInfo]".\test.txt").FullName
#  C:\WINDOWS\system32\test.txt
```

### Expected behavior

```console
C:\test.txt

C:\test.txt
```

### Actual behavior

```console
C:\test.txt

C:\WINDOWS\system32\test.txt
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
I suggest this is the difference between underlying operating system version of current directory and that maintained by PowerShell

dotnet itself does not know about PowerShell's current location per thread concept, it only knows about the operating system's per process current directory.

So the first one with New-Item is giving you the PowerShell version

The second is showing you DotNet's version.

You should see the difference between

```
Get-Location
```

and

```
[System.IO.Directory]::GetCurrentDirectory()
```

Should they be the same? They can't if you want each thread to have it's own logical location, as current directory is scoped to the process.

**Comment by matejskubic** [comment]
> dotnet itself does not know about PowerShell's current location

Yes, this is obvious.

But on the other hand, PowerShell knows dotnet, and each `Set-Location` (when the provider is `FileSystem`) should change the underlying dotnet's (`[System.Environment]::CurrentDirectory`) current working directory.

**Comment by rhubarb-geek-nz** [comment]
> Yes, this is obvious.

Apparently it isn't.

PowerShell's current location is per thread. DotNet's current directory is per process. It allows different PowerShell threads to focus on different locations. If one thread changed the current process's directory it would affect every other thread.

So the behaviour is that PowerShell leaves the current directory as it is at startup and then lets each thread have its own different logical location. 

When an external command or process is run, that is given the logical location as its current working directory.

**Comment by mklement0** [comment]
The behavior is a perennial pitfall; @rhubarb-geek-nz has explained the underlying technical reasons.

There is an existing proposal to selectively keep only the _foreground_ runspace's (thread's) file-system provider location in sync with the process working directory; concerns have been raised, and the discussion has stalled:

* #17149
