### ISSUE TITLE
`New-ItemProperty -PropertyType` should have tab completion

### ISSUE THREAD

**Issue by ArmaanMcleod** [PowerShell/PowerShell#21116]
### Summary of the new feature / enhancement

Currently `New-ItemProperty -PropertyType` does not have tab completion for the following registry value kinds below:

Unknown
String
ExpandString
Binary
DWord
MultiString
QWord
None

Which are documented [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-itemproperty?view=powershell-7.3#-propertytype).

Additionally, something worth noting is the type documented for this parameter is `RegistryValueKind` but the type is actually `string`, which seems like an issue in itself to fix the documentation. Can probably raise another issue for this.

#### Option 1

- Create argument completer which goes through values of `RegistryValueKind` and matches `wordToComplete` with possible enum values.
- Make sure path is using `Registry` provider and ignore any other provider.
- Add `ArgumentCompleter` attribute to `PropertyType` parameter.

#### Option 2 (Preferrable)

- Change type of `PropertyType` to `RegistryValueKind`. This will enable tab completion automatically since this type is an enum.
- Benefit here is that it aligns directly with documentation and is simpler. I don't believe this is a breaking change, since user can use enum parameter with strings the same way as before.

**Comment by iSazonov** [comment]
If the parameter is dynamic and coming from Registry provider we could make it `RegistryValueKind`.

**Comment by ArmaanMcleod** [comment]
> If the parameter is dynamic and coming from Registry provider we could make it `RegistryValueKind`. In the case the completion would work automatically.

Yeah that was the other option as well. Seems like that was the intention since documentation is using `RegistryValueKind` as type. Not sure on the history if this was a mistake in implementation to use `string`.

**Comment by ArmaanMcleod** [comment]
I have created two PRs with both options. When gets chosen as solution I will close the other.

**Comment by iSazonov** [comment]
> Not sure on the history if this was a mistake in implementation to use `string` or if it was deliberate. Probably need others to weigh in on that if anyone knows.

Perhaps there was a concern that there might be a type conflict, while string can be tried to convert to any type, but it makes no sense, because it is a dynamic parameter and even if another provider has a parameter with the same name, there is no conflict, because the path unambiguously defines the provider, and the provider unambiguously defines the type of the dynamic parameter.

**Comment by ArmaanMcleod** [comment]
Looks like Option 2 requires too many changes to public API to accommodate the type change. 

We had a couple options:

1. Change existing public API to expect `RegistryValueKind` instead of `string`. This is a breaking change. 
2. Create new public API overloads to support new type, which seems like too much work and refactoring for what it's worth. Could be done but you'd have to make a lot of changes to existing API to make this worth it and reuse implementation between overloads.
3. Convert `RegistryValueKind` to `string` using `ToString()` in cmdlet so we can use existing public API. Problem here is that there is too much converting back and forth between types: `RegistryValueKind` -> `string` -> `RegistryValueKind`. This is probably the easiest option but is very awkward.

Discussed above with @iSazonov and none of the options seem good, so opting to go with Option 1 and just use an argument completer.

**Comment by iSazonov** [comment]
@MartinGC94 Have you thoughts how we could implement a completer for the `PropertyType` parameter?

**Comment by MartinGC94** [comment]
I agree with @ArmaanMcleod and think option 1 is best. As for the completer itself, feel free to take inspiration from my own here:  https://github.com/MartinGC94/UsefulArgumentCompleters/blob/main/ScriptCompleters/Shared/ItemProperty.ps1 though looking at it now, I guess I should have used the `Path` parameter instead of `LiteralPath` when the `fakeBoundParameters` contains `Path`.

**Comment by iSazonov** [comment]
@MartinGC94 Thanks!

----

One more question. If we implement the partial completer what if an user already has custom completer and maybe for another property provider? Will we break the custom completer?

**Comment by MartinGC94** [comment]
> One more question. If we implement the partial completer what if an user already has custom completer and maybe for another property provider? Will we break the custom completer?

In my experience, the latest one that is applied with `Register-ArgumentCompleter` takes priority so that shouldn't be a problem.
