### ISSUE TITLE
Static void methods calls inside class

### ISSUE THREAD

**Issue by PatrykMilewski** [PowerShell/PowerShell#2111]
Steps to reproduce

```
class StaticClass {
	static [void]staticFunction() {
		return
	}
	$var = [StaticClass]::staticFunction() # first
	[StaticClass]::staticFunction()        # second
}

```

Expected behavior

Interpreter works fine with both function calls, since function does not returns any objects. Actually it shouldn't give errors even with functions, that returns something, because it's programmer business to take care about returning objects.

Actual behavior

Second call returns errors, Visual Studio 2015 Community edition, with update 3:

```
Missing clossing '}' in statement block or type definition.
Missing a property name or method definition.
An expression was expected after '('.
Unexpected token '}' in expression or statement.
```

PS output:

```
[ERROR] At C:\Users\Ja\Documents\Visual Studio 
[ERROR] 2015\Projects\pstests\pstests\pstests\Script.ps1:6 char:15
[ERROR] +     [StaticClass]::staticFunction()        #error 'Missing clossing ' ...
[ERROR] +                  ~
[ERROR] Missing a property name or method definition.
[ERROR] 
[ERROR] At C:\Users\Ja\Documents\Visual Studio 
[ERROR] 2015\Projects\pstests\pstests\pstests\Script.ps1:6 char:2
[ERROR] +     [StaticClass]::staticFunction()        #error 'Missing clossing ' ...
[ERROR] +     ~~~~~~~~~~~~~
[ERROR] Missing closing '}' in statement block or type definition.
[ERROR] 
[ERROR] At C:\Users\Ja\Documents\Visual Studio 
[ERROR] 2015\Projects\pstests\pstests\pstests\Script.ps1:6 char:32
[ERROR] +     [StaticClass]::staticFunction()        #error 'Missing clossing ' ...
[ERROR] +                                   ~
[ERROR] An expression was expected after '('.
[ERROR] 
[ERROR] At C:\Users\Ja\Documents\Visual Studio 
[ERROR] 2015\Projects\pstests\pstests\pstests\Script.ps1:7 char:1
[ERROR] + }
[ERROR] + ~
[ERROR] Unexpected token '}' in expression or statement.
[ERROR]     + CategoryInfo          : ParserError: (:) [], ParseException
[ERROR]     + FullyQualifiedErrorId : IncompleteMemberDefinition
```

Environment data
----------------

```
PSVersion                      5.1.14393.82                                    
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.14393.82                                   
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         

```

**Comment by jpsnover** [comment]
@PatrykMilewski Thanks for taking the time to write up an issue report but I *think* this is working correctly. 

This statement works:
    $var = [StaticClass]::staticFunction() # first
Because what you are doing is defining a property whose name is "var" on the class [StaticClass] whose value is the result of the call.  You can see that by commenting out the next line and do this:
PS> [StaticClass]::New() |fl *
var : 


This line fails:
   [StaticClass]::staticFunction()        # second
because it is not defining anything in the class.  That is what this error is all about:
    Missing a property name or method definition.
Because you are defining a class - you are limited to defining properties and methods and cannot run arbitrary code.
If you replace that line with "Get-Process", you will also get an error.

Does that make sense?
What would have been a better error message/experience?
Again - thanks!

**Comment by lzybkr** [comment]
Jeffrey's analysis is correct.

I think the error `Missing a property name or method definition` is pretty good, but presented the way you have, I can see why it might be confusing, and I'm not sure how we could improve the message.

**Comment by GeeLaw** [comment]
You cannot compile the following code in C#, for the same reason (you cannot invoke a method in class definition):

```CSharp
class StaticClass
{
    static void staticMethod() { }
    object var = staticMethod();
    staticMethod();
}
```

**Comment by PatrykMilewski** [comment]
You are right, that's my bad. I just got suggested by somebody else, and didn't really look on that, from that side. It's working correctly. 

I'm sorry for false alarm, and thank you for your time, you guys are doing great job :)

**Comment by jpsnover** [comment]
@PatrykMilewski NP but think through the experience and see if we could have produced a better error experience. 

Maybe 
[ERROR] Missing a property name or method definition.
should say
[ERROR] Missing a property name or method definition. When defining a class, you can only define properties and methods and cannot run arbitrary code.  See Get-Help About_xxxx for more details.
