### ISSUE TITLE
`New-Item` multiple files isn't supported

### ISSUE THREAD

**Issue by deadcoder0904** [PowerShell/PowerShell#21110]
### Summary of the new feature / enhancement

Coming from Linux, I like using `touch` while creating multiple files in the same directory.

In Powershell, I use `New-Item` or as a short-form `ni` like this:

```bash
ni input.tsx
```

But if I use 2 files, it isn't supported:

```bash
ni input.tsx select.tsx
```

Ideally, I'd like it to create 2 files at the same time.

Currently, I get an error:

> New-Item: A positional parameter cannot be found that accepts argument 'select.tsx'.

This shouldn't happen.

### Proposed technical implementation details (optional)

Just make it behave like `touch` so I can use `touch` command directly.

In anyways, I do use `touch` by setting an alias on Powershell:

```bash
Set-Alias touch ni
```

But it doesn't behave like it.

All I want is to create multiple files easily as I don't like using VSCode or File Explorer to create each file manually.

That's the entire reason I opt for Terminal but Powershell doesn't support it.

**Comment by rhubarb-geek-nz** [comment]
You are missing a comma to make a list

```
PS /tmp> ni input.tsx, select.tsx

    Directory: /tmp

UnixMode          User Group         LastWriteTime         Size Name
--------          ---- -----         -------------         ---- ----
-rw-r--r--     bythesea staff     01/20/2024 06:23            0 input.tsx
-rw-r--r--     bythesea staff     01/20/2024 06:23            0 select.tsx
```

**Comment by deadcoder0904** [comment]
I didn't get `touch` working at all that's why I could `alias` it. Probably can't alias global command, at least that's what should happen.

Anyways, here's the output I got:

```bash
PowerShell 7.4.1
PS C:\Windows\System32> which touch
which: The term 'which' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I'm not using WSL bdw.

Anyways, that answers my question but would love to know how to get `touch` working on PS7 :)
