### ISSUE TITLE
Reactivating CLRVersion in $PSVersionTable

### ISSUE THREAD

**Issue by theuserbl** [PowerShell/PowerShell#21122]
### Summary of the new feature / enhancement

It would be nice, if you reactivate the CLRVersion of the Windows Powershell in the new Powershell.

### Proposed technical implementation details (optional)

$PSVersionTable.CLRVersion = [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription -split '\s' | select -Last 1
$PSVersionTable.OSArchitecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture
$PSVersiontable

**Comment by mklement0** [comment]
See also:

* #19121
