### ISSUE TITLE
Cannot delete an empty folder

### ISSUE THREAD

**Issue by developer992** [PowerShell/PowerShell#21128]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Remove-Item -Force -Recurse -Path folder

```
Remove-Item : Cannot remove item C:\Users\....\folder: The process cannot access the file
'C:\Users\....\folder' because it is being used by another process.
At line:1 char:1
+ Remove-Item -Force -Recurse -Path django-admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (aila_admin:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Users\....\folder: The directory is not empty.
At line:1 char:1
+ Remove-Item -Force -Recurse -Path django-admin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\....\folder:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

but it's not ... i've closed down every app that had it open. 
is there a way to delete an empty unused folder without rebooting?

### Expected behavior

```console
deleted folder
```

### Actual behavior

```console
not deleted folder
```

### Environment data

```powershell
none
```

**Comment by developer992** [comment]
why provide a simple CLI tool to find out which process is using it when you can have 3rd party apps full of malware

https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows

**Comment by rhubarb-geek-nz** [comment]
> Which one shall I try first??

`Resource Monitor` as described in your link comes with Windows itself.

**Comment by SteveL-MSFT** [comment]
`openfiles` command is part of Windows

**Comment by rhubarb-geek-nz** [comment]
> It might be worthwhile to have the error message say what process has the open file handle

I would recommend against trying to add additional information to an error that was not in the original exception

- time has changed since the error occurred, the information that you find may not be related to the original error, the state may have changed
- not everyone needs to know the information and you may be spending time trying to look up that information
- you may not have the rights to look up that information
- you may cause an error trying to look up that information so the exception now becomes because of your looking up the information, not the original error

**Comment by OranguTech** [comment]
> why provide a simple CLI tool to find out which process is using it when you can have 3rd party apps full of malware
> 
> https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows
> 
> Which one shall I try first??

Why look up the solution to a common issue with the OS when you can complain about it on a barely-related github issue?

(That being said, the idea of surfacing that info in the error if possible is intriguing.)

https://learn.microsoft.com/en-us/sysinternals/downloads/procmon has been around forever.
https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith is newer, and nifty.
