### ISSUE TITLE
Need a param to hand sites with SSL issues

### ISSUE THREAD

**Issue by 1RedOne** [PowerShell/PowerShell#2114]
Steps to reproduce
------------------
-Use Invoke-RestMethod or Invoke-WebRequest on a site with SSL errors, like this one [EuroSport sample bad SSL page](https://tv.eurosport.com/)

Expected behavior
-----------------
Be able to load the site/retrieve an object

Actual behavior
---------------
Receive a terminating error of:
>The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

This can be worked around by using Add-Type to invoke some C# to set a new AcceptAllCertificates Policy, but this approach does not function on PowerShell for Linux/Mac OS, as the Core CLR doesn't have the types needed [X509].

I would love to see a new switch added to Invoke-WebRequest and Invoke-RestMethod, maybe titled `-AcceptAllSSL` or something similar.  

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.103                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.103                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 




```

**Comment by rkeithhill** [comment]
This sounds similar to what is being proposed in this pull request - https://github.com/PowerShell/PowerShell/pull/2006.  Is that the case, or is your scenario different?

**Comment by 1RedOne** [comment]
Good find Keith, I searched for some keywords but didn't find that one.  I'll close this one out.
