### ISSUE TITLE
Sharing types between functions and modules

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#21155]
### Summary of the new feature / enhancement

As a user I want a way to share type definitions among functions and modules. Searching has not turned up an answer yet. I tried looking through the PowerShell source to see how it is done, but it is not yet clear. Is using CTypes still a way to go? Is the best strategy to use PowerShell classes? It must work with PowerShell Core, but if it is not too limiting, then it would be good to work with Windows PowerShell 5.1. I do not care about going further back than 5.1.

Where should I look? Point me somewhere in the code or to a web site. Or, where can I ask this. SO would immediately squash a question like this just in case there might be more than one, singular way to do it.

**Comment by mklement0** [comment]
It's not entirely clear what you're asking, but here's one attempt at an answer:

* If you want `class` and `enum` definitions made inside a module available to an importer of that module, the importer must use `using module` rather than `Import-Module`. 

* If a module declares dependencies on .NET assemblies, the types from these assemblies are _invariably_ visible to the importer too.

**Comment by Liturgist** [comment]
I need to create types that can be shared across functions and across modules. They need to be publicly available like [System.IO.FileInfo] so that members are available for command completion.

**Comment by mklement0** [comment]
* .NET types loaded from on-disk assemblies, possibly via modules, are by default and invariably available process-wide, across scopes and runspaces.

* If you want PowerShell `class` and `enum` definitions defined in a module to be available in the same way:
  * Use the technique described in [Exporting classes with type accelerators](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Classes#exporting-classes-with-type-accelerators)
  * _Caveat_: 
    * _Cross-runspace_ use requires `class`es to be defined _without runspace affinity_ in order to prevent state corruption.
    * Decorating them with `[NoRunspaceAffinity()]` does that, but note that this attribute requires v7.4+ - see [NoRunspaceAffinity attribute](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Classes?view=powershell-7.5#norunspaceaffinity-attribute)

**Comment by Liturgist** [comment]
It sounds like the strongest way to go would be to create .Net types. Will going `.Net Core` and `PowerShell Core` ensure cross-platform operation (Linux, Mac, Windows)?

Some have suggested that PowerShell classes are not fully mature and there is a -long- list of limitations on the `about_Classes` page.

**Comment by mklement0** [comment]
Yes, PowerShell `class` support has many existing limitations, but as far as I understand the goal was never to reach feature parity with languages such as C#.

List of existing class issues here in this repo:

* #6652

Yes, creating persistent .NET assemblies (`.dll` files) via, say, C#, and shipping them with your modules works cross-platform, as long as you avoid / conditionally use platform-specific APIs.

**Comment by Liturgist** [comment]
While tempting, I am not sure that I want to cut off everything before PowerShell Core 7.4+.

Building .NET Core assemblies sounds like the harder path, but meets more of the goal. Thanks.
