### ISSUE TITLE
Grant jobs from Invoke-Command on the localhost the same permissions as Start-Job

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/PowerShell#21152]
### Summary of the new feature / enhancement

As a user of PowerShell it's a lot easier to only have to use one CmdLet instead of two to avoid the double hop issue.

## Code example
```powershell
$scriptBlock = {
    Test-Path '\\SERVER\c$\temp'
}

$invokeParams = @{
    ComputerName = 'localhost'
    AsJob        = $true
    ScriptBlock  = $scriptBlock
}
$job = Invoke-Command @invokeParams # fails because of double hop issue
$job | Wait-Job | Receive-Job

$job = Start-Job -ScriptBlock $scriptBlock # successful, no double hop issue
$job | Wait-Job | Receive-Job
```

## Workaround
```powershell
$job = if (
    ($computerName -eq 'localhost') -or
    ($computerName -eq $ENV:COMPUTERNAME) -or
    ($computerName -eq "$ENV:COMPUTERNAME.$env:USERDNSDOMAIN")
) {
    Start-Job -ScriptBlock $scriptBlock
}
else {
    Invoke-Command @invokeParams
}
```

## Desired solution
It would be great if we could only work with `Invoke-Command` for al hostnames, local and remote. It would then be up to the CmdLet `Invoke-Command` to decide if the code in the `ScriptBlock` is executed locally (to not have the double hop issue) or remotely (to have the double hop issue)..

This would also mean that the code above  in the workaround can be replaced by a single line of code:

```powershell
Invoke-Command @invokeParams 
```

**Comment by rhubarb-geek-nz** [comment]
Technically it already does, if you just provide a scriptblock it will just run it in the local scope

[Invoke-Command](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-7.4)

> You can also use Invoke-Command on a local computer to a run script block as a command. PowerShell runs the script block immediately in a child scope of the current scope.

```
PS> Invoke-Command -ScriptBlock { Write-Host 'foo'; }
foo
```

**Comment by DarkLite1** [comment]
The code does indeed run locally when `-ComputerName 'localhost'` is used. However, the code within the `-ScriptBlock` is not able to reach paths that are not on the local machine. While the same `-ScriptBlock` executed with `Start-Job`, also running on the local machine, does not have this issue.

**Comment by rhubarb-geek-nz** [comment]
Is that a current directory/current location issue?

**Comment by DarkLite1** [comment]
I don't really understand your question. But the path we try to reach with `Test-Path` does really exist.

**Comment by rhubarb-geek-nz** [comment]
With my testing `Invoke-Command -ComputerName localhost` still tries tries to run a command on a named computer rather than running locally.

> I don't really understand your question. But the path we try to reach with Test-Path does really exist.

If you simply invoke a local script it will be using the current working directory. If you execute a remote command, it will be using the default directory unless you change it. Are you using relative or absolute paths.  Do you manage the current location/directory in your script?

**Comment by DarkLite1** [comment]
Thanks for getting back to me, but I believe this is a security measure called "double hop". This means that when a user connects to a remote computer, the code in the remote session is not allowed to access resources outside that session (or outside that remote host). 

We can clearly see this because `Invoke-Command` is not allowed to access the path `\\SERVER2\c$\Temp` when the code is executed on 'SERVER1':

Example:
```powershell
$invokeParams = @{
    ComputerName = 'SERVER1'
    AsJob                 = $true
    ScriptBlock        = { Test-Path '\\SERVER2\c$\temp' }
}
$job = Invoke-Command @invokeParams # fails because of double hop issue
$job | Wait-Job | Receive-Job
```

This is by design. This issue is a request to remove that limitation when the code is run on the **local machine** instead of on a **remote machine**.

So in this example it would be great if this would still work, because the code is run in a local session on the local machine:
```powershell
$invokeParams = @{
    ComputerName = 'localhost' # code run locally
    AsJob                 = $true
    ScriptBlock        = { Test-Path '\\SERVER2\c$\temp' }
}
$job = Invoke-Command @invokeParams # this should not fail
$job | Wait-Job | Receive-Job
```

**Comment by DarkLite1** [comment]
IMHO if `Start-Job` can do this why would this be an issue for `Invoke-Command -ComputerName 'localhost' -AsJob`? 

The same logic would be applied as it is the same job type, execution place, code, ... .

**Comment by rhubarb-geek-nz** [comment]
As far as I can tell Invoke-Command -ComputerName 'localhost' is still going via a remote command. I don't see it doing bypass because of the name computer name.


```
PS> Invoke-Command -ComputerName 'localhost' -ScriptBlock { Get-Location }
OpenError: [localhost] Connecting to remote server localhost failed with the following error message : The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". For more information, see the about_Remote_Troubleshooting Help topic.
```

However if -ComputerName is not present it does just run it in the local scope.

**Comment by DarkLite1** [comment]
For me this code works fine in PowerShell 7.4.1:
```powershell
 Invoke-Command -ComputerName 'localhost' -ScriptBlock { Get-Location }
```

But I'm specifically talking about jobs here. So the differentation between `Start-Job` and `Invoke-Command -ComputerName localhost -AsJob` wouldn't be there.

**Comment by rhubarb-geek-nz** [comment]
> But I'm specifically talking about jobs here. So the differentation between `Start-Job` and `Invoke-Command -ComputerName localhost -AsJob` wouldn't be there.

```
PS> Invoke-Command -AsJob -ScriptBlock { Get-Location }
Invoke-Command: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

I suggest if you want to run local jobs, use Start-Job, if you want to run remote scripts or jobs use Invoke-Command. That way it is absolutely clear about the execution environment, credentials and rights that each invocation has.

**Comment by jhoneill** [comment]
@DarkLite1  have you tried `invoke-command -EnableNetworkAccess `
IIRC without that you always hit the double hop problem because you are going out via winrm to a remote PowerShell session and coming back into one which happens to be on the same machine (which will fail if remoting is not configured) 
That session runs in its own security context/session, and it's not the same as `start-process` or `start-job` which are running things in the same session as their PowerShell instance.

**Comment by DarkLite1** [comment]
Yes, thank you @jhoneill . That seems to work just fine. Didn't know about that parameter.

I think we can close this one now .
