### ISSUE TITLE
Add Fuzzy String comparison cmdlet

### ISSUE THREAD

**Issue by trackd** [PowerShell/PowerShell#21163]
### Summary of the new feature / enhancement

I would like to see a new cmdlet for comparing strings, something like

`Compare-String`

That uses fuzzymatch to compare two strings

it would be a nice companion to `Compare-Object`.

While it certainly is possible to do this as an external module,

the bulk of code is already implemented in pwsh and would be a nice built-in feature to expose to users.

### Proposed technical implementation details (optional)

re-use existing Fuzzymatch code (used in `Get-Command`)
[FuzzyMatch.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/utils/FuzzyMatch.cs)

an example implementation written in pwsh (that just add-type's the fuzzymatch.cs)
[PSFuzzyMatcher](https://github.com/trackd/PSFuzzyMatcher)

**Comment by rhubarb-geek-nz** [comment]
> which should really be made public

All you need to do is put it in the PowerShell Gallery!

If you are creating a module with just a C# class then I suggest publishing it as an already compiled assembly so each user does not have to compile it every time they use it.

**Comment by trackd** [comment]
> > which should really be made public
> 
> All you need to do is put it in the PowerShell Gallery!

that probably wont happen, maybe if someone really wants it..
i did actually fix so it runs on ps 5.1 😆 

> If you are creating a module with just a C# class then I suggest publishing it as an already compiled assembly so each user does not have to compile it every time they use it.

sure, with all the timesavings that gives you...?
```ps1
(Measure-Command { pwsh -nop -c 'Import-Module .\PSFuzzyMatcher.psd1;Compare-String foo bar 1' }).TotalSeconds
0,5932726
```
a small clarification, it's not everytime they use it, it's only the first time they run `Import-Module` (per session)


as i said in my post and in the repo, this was just an example to demo the functionality desired with a "minimum viable product"

As most of the code is already written and shipped with Powershell i think it would be an excellent addition in the `Microsoft.PowerShell.Utility` module.

a compromise might be to just make the class public so you dont need to add-type the C# code?

**Comment by rhubarb-geek-nz** [comment]
Thanks, I might have a play with that.

**Comment by trackd** [comment]
>I don't think we wanted to make the FuzzyMatch class public as there [faster implementations of libraries](https://www.nuget.org/packages?q=fuzzy) available that others can build upon and we didn't want to add another dependency that could create a version conflict with modules.
> 

Performance seems fine..

```ps1
# Frankenstein
# https://www.gutenberg.org/ebooks/84 
$sample = (Invoke-RestMethod 'https://www.gutenberg.org/cache/epub/84/pg84.txt') -split "\r?\n"
foreach ($line in $sample) {
    $fuzzedsample = $line -creplace 'A|B|C|D|E','0'
    if ($fuzzedsample -ne $line) {
        $Comparison = Compare-String -Candidate $line -Pattern $fuzzedsample -FuzzyThreshold 1
        if ($Comparison.isMatch -eq $true) {
            # lines where we only replaced one character
            $Comparison
        }
    }
}
<#
$test = Measure-Command { $results = .\silly_fuzzytest.ps1 }
$results.count
929
$test.TotalSeconds
0,9777117

# Moby Dick
# https://www.gutenberg.org/ebooks/2701
# https://www.gutenberg.org/cache/epub/2701/pg2701.txt
$results.count
3358
$test.TotalSeconds
1,7053552
#>
```

**Comment by JamesWTruher** [comment]
The @PowerShell/wg-powershell-engine  discussed this, and we don't believe that we should make the internal PowerShell API public. We believe the appropriate approach would be to have a stand-alone cmdlet published in the gallery.
