### ISSUE TITLE
External commands fail if delete the powershell invoked directory

### ISSUE THREAD

**Issue by k-takai** [PowerShell/PowerShell#2116]
## Steps to reproduce

'$' means execute on bash, 'PS>' means execute on powershell.
1. $ mkdir /tmp/test
2. $ cd /tmp/test/
3. $ powershell
4. PS> cd ../
5. PS> rmdir ./test/
6. PS> date
## Expected behavior

Normal output of Linux date command is expected.

```
Mon Aug 29 18:43:06 JST 2016
```
## Actual behavior

```
Unable to find the specified file.
At line:1 char:1
+ date
+ ~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException

```
## Environment data

Commands and outputs are following.

```
takai@ubuntu1604:~$ mkdir /tmp/test
takai@ubuntu1604:~$ cd /tmp/test/
takai@ubuntu1604:/tmp/test$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS /tmp/test> cd ../
PS /tmp> rmdir ./test/
PS /tmp> date
Unable to find the specified file.
At line:1 char:1
+ date
+ ~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException

PS /tmp>
```

``` powershell
PS /tmp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by wilsonmar** [comment]
I am getting the same error on v6.0.0-alpha.12. Can't run
Set-ExecutionPolicy Restricted

But if you want a work-around, this works for me:
$NOW = Get-Date -Format "yyyy-MM-ddTHH:mmzzz"
echo $NOW

**Comment by HemantMahawar** [comment]
@joeyaiello Add the results of your chroot scenario

**Comment by joeyaiello** [comment]
Ugh, trying to mess with chroot while in WSL via [this guide](http://www.ubuntubuzz.com/2015/09/a-basic-chroot-example-in-ubuntu.html), it doesn't want to work for me. 

In any case, if there's a way we *can* work around this, I think we probably should. It's annoying, just did it very easily.

**Comment by rkeithhill** [comment]
This is related to the fact that PS never changes the initial working directory after PS starts - even when you call Set-Location.  You can also work around this by calling `[System.IO.Directory]::SetCurrentDirectory("$HOME")` to change the process's current dir to one that is not being deleted.

**Comment by iSazonov** [comment]
Perhaps it is here https://github.com/PowerShell/PowerShell/blob/14f25c92e7616833639ceec6a729852fccfb31a4/src/System.Management.Automation/engine/InitialSessionState.cs#L3388

**Comment by TylerLeonhardt** [comment]
Unfortunately, I hit this issue a ton because I:

* run a full build of my product that creates a new directory
* open that directory in vscode
* run the command that runs my build in the vscode terminal (in PowerShell)
* then run a full build again which destroys the folder and recreates it

Unfortunately, even though the folder is recreated and everything is in place, this error shows up.

minimal repro:

Two pwsh windows:

window 1
```
PS > mkdir foo
PS > cd foo
# go to other shell
PS > ps aux
# see error
```

window 2
```
PS2 > Remove-Item -Recurse -Force foo
PS2 > mkdir foo
# go to other shell
```
