### ISSUE TITLE
Alpine (3.19) Support?

### ISSUE THREAD

**Issue by J0F3** [PowerShell/PowerShell#21172]
### Summary of the new feature / enhancement

Alpine Linux is widely used in containerized and cloud native environments due to its small footprint. But unfortunately PowerShells to drop support for Alpine Linux since version 3.18, for some reasons. Although there is still a release of PowerShell for Alpine available on GitHub the official documentation says its is not supported on Alpine 3.18 and the latest version 3.19 is not even mentioned. In additional the installation instructions do not work on Alpine 3.19 anymore. 
I have reported that already but the issue got immediately closed without any further explanations: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10775

I am sad to see that because it gives (again) the impression that PowerShell resp. Microsoft does not care about the cloud native and open source world.

So please, pleas  reestablish support for Alpine Linux again or at least explain a bit more in the documentation why it is not support or which issues one would have with Alpine Linux. Because, as far as I experience it, PowerShell can installed and works just fine on Alpine 3.19.

### Proposed technical implementation details (optional)

- Update documentation at: https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4#supported-versions  
Either that Alpine 3.19 ist supported or what more specifics why it is not supported.

- Update installation instructions (they seem to be very outdated). .NET has more up to date instructions here: https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies
And I made here also some suggestion already: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10775

**Comment by rhubarb-geek-nz** [comment]
[powershell-7.4.1-linux-musl-x64.tar.gz](https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/powershell-7.4.1-linux-musl-x64.tar.gz)

The RID naming conventions have  changed/simplified. What was _alpine_ is now _linux-musl_.

**Comment by J0F3** [comment]
@rhubarb-geek-nz Thx, but I got that and that is how I was able to install PowerShell on Alpine 3.19. 😄 

What I mean is the fact that here it states that Alpine newer than 3.17 is not supported: https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4#supported-versions

And the installation instructions here do not work anymore for Alpine 3.19 because some packages are not available anymore on Alpine 3.19 resp. are now in the stable branch and do not need to installed from edge branch anymore: https://learn.microsoft.com/en-us/powershell/scripting/install/install-alpine?view=powershell-7.4#installation-steps

**Comment by theJasonHelmick** [comment]
This request is being tracked #21316
