### ISSUE TITLE
Install-Module needs to be able to download from private feeds that require Entra (AAD) authentication.

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PowerShell#21181]
### Summary of the new feature / enhancement

In many environments it is a security requirement that scripts / end users do not install anything from a source that is not under direct control of the organization. So for example, if your users need some public NuGet package, then you snap a version of that public NuGet package into an organization-private feed, where it can be security-scanned, and is relatively protected from being updated unbenkownst to the organization; and users get the package from there, instead of from the public feed.

I'd like to be able to use `Install-Module` to install modules from such a private NuGet feed... but the problem is that my feed requires Entra (AAD) authentication, and I am not aware of a way to do that with a `PSCredential`. (And, BTW, we *really* do not want to use PATs.)

**Comment by mklement0** [comment]
My understanding is that the module underlying `Install-Module` is no longer maintained,
so you're better off requesting that in the context of its successor, `Install-PSResource`, at https://github.com/PowerShell/PSResourceGet/issues

**Comment by jazzdelightsme** [comment]
Thank you! Filed: https://github.com/PowerShell/PSResourceGet/issues/1551
