### ISSUE TITLE
PowerShell 7.4.1 - When pressing arrow key up, please bring cursor end of the last command.

### ISSUE THREAD

**Issue by survivor303** [PowerShell/PowerShell#21197]
### Summary of the new feature / enhancement

I'm not sure is this currently behavior a feature or misstep.

On cmd, when you press arrow up key, you can browse old commands what you have typed before and on PowerShell that working too, but the problem is that the cursor doesn't go end of the last command. That make me crazy :)

So is it possible to fix this to work as it works on cmd, or is there some kind of option somewhere, where user can set, how PowerShell behave on this. If not, perhaps it is good idea to add this to the PowerShell config files as a option.

**Comment by 237dmitry** [comment]
> the cursor doesn't go end of the last command.

```
Set-PSReadlineOption -HistorySearchCursorMovesToEnd
```
or
```
Set-PSReadlineOption -HistorySearchCursorMovesToEnd:$true     # or $false
```
