### ISSUE TITLE
Unable to override Accept-Encoding header with Invoke-WebRequest in version 7.4.1

### ISSUE THREAD

**Issue by yuenm18** [PowerShell/PowerShell#21205]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When using `Invoke-WebRequest` and defining an `Accept-Encoding` header, the specified header values are appended to the default `gzip, deflate, br` values, rather than replacing them. Powershell version 7.3 correctly replaces them.

1. Setup a request catcher subdomain https://requestcatcher.com/
2. Run `Invoke-WebRequest -Uri 'https://baefc974-c79b-11ee-ae6b-00155d6ef82d.requestcatcher.com/' -Headers @{ 'Accept-Encoding' = 'test' }` replacing baefc974-c79b-11ee-ae6b-00155d6ef82d with your subdomain
3. Notice that the Accept-Encoding header is `Accept-Encoding: test, gzip, deflate, br` instead of `Accept-Encoding: test`
4. Rerun the command using powershell version 7.3 and notice that the the Accept-Encoding header is `Accept-Encoding: test`

### Expected behavior

```console
GET / HTTP/1.1
Host: baefc974-c79b-11ee-ae6b-00155d6ef82d.requestcatcher.com
Accept-Encoding: test
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; en-US) PowerShell/7.4.1
```

### Actual behavior

```console
GET / HTTP/1.1
Host: baefc974-c79b-11ee-ae6b-00155d6ef82d.requestcatcher.com
Accept-Encoding: test, gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19045; en-US) PowerShell/7.4.1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Have you checked to see if this done by Net 8.0 itself or by PowerShell behaviour?

**Comment by yuenm18** [comment]
> Have you checked to see if this done by Net 8.0 itself or by PowerShell behaviour?

@rhubarb-geek-nz How do I test that?

**Comment by SteveL-MSFT** [comment]
It looks like [.NET](https://github.com/dotnet/runtime/blob/b1d7ad693362ccea4993bd75b670871a043c632b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L54-L67) will add those compression as accepted as long as they aren't disabled.

**Comment by yuenm18** [comment]
@SteveL-MSFT Is there a way to disable compression. I'm trying to remove "br" from the default Accept-Encoding header because an API I'm calling errors when it's there.

```json
{
    "fault": {
        "faultstring": "Unsupported Encoding \"br\"",
        "detail": {
            "errorcode": "protocol.http.UnsupportedEncoding"
        }
    }
}
```

**Comment by mklement0** [comment]
You can use the `curl` utility instead (in Windows PowerShell, use `curl.exe`):

```powershell
curl -H 'Accept-Encoding: test' https://baefc974-c79b-11ee-ae6b-00155d6ef82d.requestcatcher.com/
```

**Comment by yuenm18** [comment]
> You can use the `curl` utility instead (in Windows PowerShell, use `curl.exe`):
> 
> ```powershell
> curl -H 'Accept-Encoding: test' https://baefc974-c79b-11ee-ae6b-00155d6ef82d.requestcatcher.com/
> ```

Thanks for the workaround
