### ISSUE TITLE
Install-PackageProvider NuGet errors

### ISSUE THREAD

**Issue by homotechsual** [PowerShell/PowerShell#21204]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

On a machine running a nuget provider less than the latest (<3.0.0.1) run `Install-PackageProvider -Name nuget`.

### Expected behavior

```console
PS> Install-PackageProvider NuGet -ForceBootstrap

Package provider installed.
```

### Actual behavior

```console
PS> Install-PackageProvider NuGet -ForceBootstrap


Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package 
provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Also affects PowerShell 5.1
```

**Comment by SteveL-MSFT** [comment]
This is a OneGet issue and not PowerShell

**Comment by homotechsual** [comment]
How might one get this in front of the team responsible for OneGet?

**Comment by mklement0** [comment]
The `PackageManagement` repo (formerly known as `OneGet`) is [here](https://github.com/oneget/oneget).

Unfortunately, as the read-me there states, it is no longer actively developed and "is expected to receive only high-priority bug fixes".
