### ISSUE TITLE
Powershell 7 breaks Virtualmachinemanager (SCVMM) module

### ISSUE THREAD

**Issue by ErikApption** [PowerShell/PowerShell#21214]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

All the commands from the module 'Virtualmachinemanager' are failing with Powershell 7

```
Get-SCVirtualMachine
Get-SCVMMServer: The type initializer for 'Microsoft.VirtualManager.Utils.TraceProviders.IndigoLayer' threw an exception.
```

### Expected behavior

```console
Proper objects are returned
```

### Actual behavior

```console
All commands are throwing an exception
```

### Error details

```console
Exception             :
    Type           : System.TypeInitializationException
    TypeName       : Microsoft.VirtualManager.Utils.TraceProviders.IndigoLayer
    TargetSite     : System.Management.Automation.Cmdlet lambda_method36(System.Runtime.CompilerServices.Closure)
    Message        : The type initializer for 'Microsoft.VirtualManager.Utils.TraceProviders.IndigoLayer' threw an
exception.
    InnerException :
        Type       : System.TypeLoadException
        Message    : Could not load type 'System.Diagnostics.Eventing.EventProvider' from assembly 'System.Core,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
        TypeName   : System.Diagnostics.Eventing.EventProvider
        TargetSite : Void .ctor(Microsoft.VirtualManager.Trace.ComponentCode, Boolean)
        Source     : TraceWrapper
        HResult    : -2146233054
        StackTrace :
   at Microsoft.VirtualManager.Trace.TraceProvider..ctor(ComponentCode component, Boolean etwEnabled)
   at Microsoft.VirtualManager.Trace.TraceProvider..ctor(ComponentCode component)
   at Microsoft.VirtualManager.Utils.TraceProviders.IndigoLayer..cctor()
    Source         : Anonymously Hosted DynamicMethods Assembly
    HResult        : -2146233036
    StackTrace     :
   at lambda_method36(Closure)
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
CategoryInfo          : NotSpecified: (:) [], TypeInitializationException
FullyQualifiedErrorId : System.TypeInitializationException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 14
    HistoryId        : 2
    Line             : $VMMserver = Get-SCVMMServer -ComputerName "backup.office.apption.com" -TCPPort 8100
    Statement        : Get-SCVMMServer
    PositionMessage  : At line:1 char:14
                       + $VMMserver = Get-SCVMMServer -ComputerName "backup.office.apption.com …
                       +              ~~~~~~~~~~~~~~~
    InvocationName   : Get-SCVMMServer
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
That is unfortunate (first reported in #15026), but the code for the [`VirtualMachineManager`](https://learn.microsoft.com/en-us/powershell/module/virtualmachinemanager/?view=systemcenter-ps-2022) module isn't being maintained in this repo.

There used to be an umbrella repo for reporting such external-module issues - https://github.com/PowerShell/PowerShellModuleCoverage - but it is now _archived_ and contains the following advice (emphasis added):

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

---

You _may_ be able to use the following workaround, which has unavoidable limitations, due to use of the [Windows PowerShell Compatibility feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility):

```
Import-Module -UseWindowsPowerShell VirtualMachineManager
```

**Comment by ErikApption** [comment]
```
Import-Module -UseWindowsPowerShell VirtualMachineManager
```

I was not aware of this - thank you! This should make it to the official VMM docs.

**Comment by mklement0** [comment]
Glad to hear it helped, @ErikApption. 

Re documentation:

It looks like the [docs](https://learn.microsoft.com/en-us/powershell/module/virtualmachinemanager/?view=systemcenter-ps-2022) aren't being maintained on GitHub either, so there's only the generic 
<img width="81" alt="image" src="https://github.com/PowerShell/PowerShell/assets/588825/c3223eef-80f1-4f3a-98c7-139d97f6b2f8">
feature on the linked page, which I encourage you to use - assuming that you've verified that the workaround does actually work in practice (I cannot verify this myself).

**Comment by ErikApption** [comment]
Workaround is clunky - all examples expect objects but so far I've been able to pass names instead. I did report on feedback that the module was broken on PS7

This works
```pwsh
# Import the module
Import-Module -UseWindowsPowerShell VirtualMachineManager

$vmmServerHost = "vmmserver.contoso.com"
$newHost = "newHost1"
# Connect to the SCVMM server
$VMMserver = Get-SCVMMServer -ComputerName $vmmServerHost -TCPPort 8100

Write-Host "Connected to VMM server: " $VMMserver.Name

# Get the VM to clone
$sourceVM = Get-SCVirtualMachine -Name "source" -VMMServer $VMMserver.Name

Write-Host "Source VM: " $sourceVM.Name
# Get the host for the new VM where name starts with hvhost2

$VMHost = Get-SCVMHost -VMMServer $VMMserver.Name | Where-Object {$_.Name -like "host*"}
Write-Host "VM Host: " $VMHost.Name

# Clone the VM
$newVM = New-SCVirtualMachine -Name $newHost -VM $sourceVM.Name -VMHost $VMHost.Name -Path "D:\Hyper-V" -StartAction "NeverAutoTurnOnVM" -StopAction "SaveVM" -VMMServer $VMMserver.Name

# generate a random mac address
$macAddress = "{0:X2}:{1:X2}:{2:X2}:{3:X2}:{4:X2}:{5:X2}" -f (Get-Random -Maximum 0x3F), (Get-Random -Maximum 0x100), (Get-Random -Maximum 0x100), (Get-Random -Maximum 0x100), (Get-Random -Maximum 0x100), (Get-Random -Maximum 0x100)

Set-SCVirtualNetworkAdapter -VM $newVM.Name -VMMServer $VMMserver.Name -MACAddressType "Static" -MACAddress $macAddress
```

**Comment by jborean93** [comment]
The trouble with `Import-Module -UseWindowsPowerShell` is it loads the module in a WinPS (5.1) process and uses a proxy function to send and receive the inputs/outputs. As it's in another process all complex objects are serialized which typically breaks things like type checks and pipelining. Only more primitive types like strings, ints, DateTime, etc are preserved across the serialization boundary.

To avoid this it's best to just encapsulate all the code that requires this module in an `Invoke-Command` scriptblock like so

```powershell
$winPS = New-PSSession -UseWindowsPowerShell
try {
    Invoke-Command -Session $winPS -ScriptBlock {
        # Everything in here runs in the WinPS process, types are preserved like normal
        Import-Module VirtualMachineManager

        $VMMserver = Get-SCVMMServer -ComputerName $vmmServerHost -TCPPort 8100
        ...
    }
}
finally {
    $winPS | Remove-PSSession
}
```

You can provide any input you need through `-ArgumentList` or with `$using:var` like any normal `Invoke-Command` object. Any output can be an object but keep in mind it will be serialized so try and contain all the logic needed for this inside the scriptblock. With this method you can continue to use PS 7 for all your normal code and only selectively go back to WinPS for the code that needs it. Hopefully over time this situation improves but for now it's just something we have to deal with.

**Comment by ErikApption** [comment]
@jborean93 brilliant. I was not aware of this New-PSSession option
