### ISSUE TITLE
not execute the command

### ISSUE THREAD

**Issue by nczsl** [PowerShell/PowerShell#21211]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

  [void]Publish([string]$ways,[string]$runtime,[switch]$self_contained){
    $waysprojpath="$($this.appsdir)\$ways\$ways.Gateway\$ways.Gateway.csproj"
    echo-info $waysprojpath.gettype().fullname
    echo-info "$waysprojpath"
    # echo-info dotnet --version
    # echo-info tsc -v
    # echo-info $(dotnet --version)
    if(!(test-path $waysprojpath)){
      echo-error "the ways $ways is not exist."
      return
    }
    $r=''
    if($runtime){
      $r="--runtime $runtime"
    }
    if($self_contained){
      echo-info "dotnet publish $waysprojpath $r"
      Invoke-Expression "dotnet publish $waysprojpath $r --self-contained"
    }
    else{
      echo-info "dotnet publish $waysprojpath $r"
      Invoke-Expression "dotnet publish $waysprojpath $r"
      # invoke-command -scriptblock {dotnet publish $waysprojpath $r}
    }
    # echo-info $(dotnet publish -h)
    echo-success "the ways $ways was published."
    $this.log("the ways $ways was published.","$($this.appsdir)\$ways")
  }
//a class method name is Publish in the bizlib.ps1 
//i invoke the method the control is in the method is right, 
// but if i do not use invoke-expression then the "dotnet publish ..." is not execute
// Why is this happening？
// at the other method I can use dotnet new ... command do not need use invoke-expression cmdlet

### Expected behavior

```console
dotnet publish ... is execute
```

### Actual behavior

```console
dotnet publish ... is not execute
```

### Error details

```console
not report error message
```

### Environment data

```powershell
PS E:\netenv\bofu\dbmanager> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/5241693/fbebfa53-ecd8-452b-b71e-4d62390d48ab)

You can't see the problem from the output in the image, it can be called in its entirety, but if you don't use invoke-expression, it won't actually trigger the dotnet publish command

**Comment by mklement0** [comment]
* Generally, please format your post properly, using fenced code blocks (place a ` ``` `  line both before and after your code). Without that, not only is the code hard to read, but its _content may be altered_ by GitHub's rendering.

* If you think you've found a problem with PowerShell itself, please try to provide an [MCVE (Minimal, Complete, and Verifiable Example)](http://stackoverflow.com/help/mcve)
