### ISSUE TITLE
PowerShell creates unexpected files in my workspace directory

### ISSUE THREAD

**Issue by gingters** [PowerShell/PowerShell#21226]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I installed Powershell 7.4.1 in a devcontainer using the `ghcr.io/devcontainers/features/powershell:1` feature.
I also install some modules:

```
        "ghcr.io/devcontainers/features/powershell:1": {
            "version": "7.4.1",
            "modules": "posh-git,z,PSFzf,Terminal-Icons"
        },
```

I also install oh-my-posh.

My profile file looks like this:

```
Import-Module posh-git
Import-Module PSFzf -ArgumentList 'Ctrl+t', 'Ctrl+r'
Import-Module z
Import-Module Terminal-Icons

Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete

$env:POSH_GIT_ENABLED=$true
$env:POSH_THEME_FILE="%POSHTHEMEFILE%"

oh-my-posh prompt init pwsh --config $env:POSH_THEME_FILE | Invoke-Expression
```

When I launch pwsh in my dev container as the terminal in VS Code, some unexpeted files are written into my `/workspaces/{Reponame}` folder.

### Expected behavior

```console
No files are created in my workspace folder (if they are needed, they should go somewhere in the user folder).
```

### Actual behavior

```console
A file called `ModuleAnalysisCache-AE0255EC` is created in my workspace root.
Another file called `sentinel1-2024-2-14.done` is created in the folder `7.4.1`.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Ubuntu 22.04.3 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
In a normal PowerShell environment on Windows I do see similar files under AppData\Local, eg

```
%LOCALAPPDATA%\Microsoft\PowerShell\ModuleAnalysisCache-C3CB0CFF
```

and

```
%LOCALAPPDATA%\Microsoft\PowerShell\7.4.0\sentinel1-2023-11-25.done
```

So it looks like the PowerShell environment is not fully set up to know where to put its work files.

**Comment by gingters** [comment]
The devcontainer Powershell feature installs as root.
I sudo'ed to root and there the 7.4.1 folder and the ModuleAnalysisCache file is in `/root/.cache/powershell`

What would I need to do do have this running correctly?

**Comment by gingters** [comment]
I found the issue: I read a bit in the source code, where the ModuleAnalysisCache and the UpdateCheck (the sentinel file) should go. Both use `Platform.CacheDirectory` to select the directory.

This would select a value set under `XDG_CACHE_HOME` before falling to its default, but this variable is not set in my environment.

On Unix (this is a linux devcontainer) it would then default to the home dir and there `.cache/powershell/`. The `HOME` environment variable is correctly set to `/home/vscode`.

So, I would expect it to be written to `/home/vscode/.cache/powershell/`.
However, both files are written to `/workspaces/archery` (my project name).

I used pwsh to call into `Platform.SelectProductNameForDirectory` to check what is returned, and this is my result:

```pwsh
└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(0)
/home/vscode/.config/powershell
└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(1)

└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(2)
/home/vscode/.local/share/powershell
└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(3)
/home/vscode/.local/share/powershell/Modules
└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(4)
/usr/local/share/powershell/Modules
└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(5)
/home/vscode/.config/powershell
```

As you can see, the enum value `1` for `XDG_Type.Cache` returns an empty string.
I then looked what could be the cause that this returns an empty string and I found the last part in the method: https://github.com/PowerShell/PowerShell/blob/71035543e761c9c749d11ed94d18a1058f88a863/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L341-L346
If there is no permission to create the directory, it returns an empty string.

Turns out, the installation of powershell feature and also my oh-my-posh feature happens as root, and I copy the themes from the `/root/.cache/oh-my-posh` to the `${_REMOTE_USER_HOME}/.cache/oh-my-posh` directory (as root). The `.cache` directory did not exist at installation time and was created as root, and so the vscode user had no permission to write in `~/.cache.`

I fixed that permission problem, and now the `/home/vscode/.cache/powershell` folder can be created and used:

```pwsh
└─Δ [System.Management.Automation.Platform]::SelectProductNameForDirectory(1)
/home/vscode/.cache/powershell
```
