### ISSUE TITLE
Several Cmdlets from Microsoft.PowerShell.Core are missing

### ISSUE THREAD

**Issue by ffeldhaus** [PowerShell/PowerShell#2122]
The following Cmdlets from `Microsoft.PowerShell.Core` are missing:

``` powershell
Cmdlet          Add-PSSnapin                                       3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Disable-PSRemoting                                 3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Enable-PSRemoting                                  3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Export-Console                                     3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Get-PSSnapin                                       3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Remove-PSSnapin                                    3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Suspend-Job                                        3.0.0.0    Microsoft.PowerShell.Core
```

At least the `Export-Console` and `Suspend-Job` Cmdlets should get implemented, a removal notice (ideally including explanation) should be added to release notes for the other Cmdlets if they will be permanantly removed.

**Comment by SteveL-MSFT** [comment]
PSSnapins are deprecated and not supported on this PowerShell.  I thought we doc'd this, but don't see mention of it in this repo

**Comment by vors** [comment]
[Command availability table](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#command-availability) need to be updated.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  snapins and export-console are not supported and not part of PowerShell Core.  PSRemoting needs to be ported for Windows and created for Linux (with optional OMI pkg).  *Job is being done #1972

**Comment by joeyaiello** [comment]
@jeffbi did you ever happen to look into the `Suspend-Job` cmdlet? Looks like we don't have it on Windows either, not sure if we ever ruled out porting to .NET Core. 

Setting up another issue specifically for Enable/Disable-PSRemoting on Linux.

**Comment by jeffbi** [comment]
@joeyaiello No, I didn't. None of my tests do anything with this cmdlet. It's been a while so I don't remember whether we discussed this.

**Comment by joeyaiello** [comment]
To recap:
* PSSnapins aren't coming back
* Enable/Disable-PSRemoting is there now in Beta.7
* Export-Console is also snap-in related
* Suspend-Job should be its own issue, @SteveL-MSFT to investigate.

**Comment by iSazonov** [comment]
@SteveL-MSFT Have we tracking Issue for •Suspend-Job ?

**Comment by SteveL-MSFT** [comment]
@iSazonov `Suspend-Job` and `Resume-Job` only work with Workflow jobs which aren't supported.

**Comment by felixfbecker** [comment]
Could someone explain me how I can test a Cmdlet with PowerShell core? I can't find any mentions in the [new documentation](https://docs.microsoft.com/en-us/powershell/index?view=powershell-6) and googling just brings up [this old MSDN site](https://msdn.microsoft.com/en-us/library/dd878294(v=vs.85).aspx) which instructs to write a SnapIn.

**Comment by iSazonov** [comment]
@ffeldhaus Please see https://github.com/PowerShell/PowerShell/tree/master/docs/cmdlet-example
