### ISSUE TITLE
Reopen/Reconsider Support lowering TrustLevel using Start-Process (Drop HIGH to MEDIUM)

### ISSUE THREAD

**Issue by agowa** [PowerShell/PowerShell#21225]
### Summary of the new feature / enhancement

Hi, the conclusion reached within #15562 does not appear to still be true.
1) Windows now has sudo
2) There is an increased demand with tools like `winget` now being able to just fail when being elevated e.g. `ElevationRequirement: elevationProhibited`.

Therefore I'd like to request that the decision of "WontFix" is re-evaluated and a first party and native way to lower privileges is added to `Start-Process` to make all of the ugly (and probably also unsupported) workaround unnecessary and provide a good and stable way to execute a process as limited user from an elevated context.

### Proposed technical implementation details (optional)

Possible implementations:
1) Nicely poke the Win32 people to add a new Verb for launching processes. So that we can use e.g. `-Verb RunAsLimited` in addition to `RunAsUser` (to have the "Run as different user" prompt popup) and `RunAs` (to elevate using UAC). [And please also ask them about a "RunAsInvoker" which forces an application to run in whatever context currently exists and ignore UAC request of the application, e.g. similar to the CompatibilityShim-reliant and undocumented hack of `cmd /min /C "set __COMPAT_LAYER=RUNASINVOKER && start "" %1"`]
2) Implement a `-AsLimited` and use the C++ APIs within the PowerShell Engine for it, e.g.  `AdjustTokenPrivileges` with `SE_PRIVILEGE_REMOVED` (or was it `DisableAllPrivileges=$true`?) set OR using `CreateRestrictedToken` with `LUA_TOKEN` set followed by `CreateProcessAsUser` on our own access token that we can easily access using `GetCurrentProcessToken`.
3) Use one of the crude workaround people currently use (see countless stackoverflow questions and answers for them)

I'd prefer if we could get option # 1 as it would be where people expect it (and technically also always have looked for before settling with workarounds) but if the win32 people decline to help here we still could just implement dropping permissions ourself within the PowerShell Engine when `-AsLimited` is specified for `Start-Process` using the C++ APIs (# 2).

We should however avoid using the crude hacks. However for completeness we technically could use them internally and thereby allow us to transparently change to something more stable later while avoiding that users will use them themselves directly (and thereby prevent deprecation of it or break/complain when it breaks unintentionally by a patch or update).
For completeness the workarounds I've seen so far (I didn't test all of them, but for those that I did test I'll also add a note about what the issues with them are):
* `explorer.exe powershell.exe  -NoP -EP Bypass -File "$PSCommandPath"` (interestingly this one works, however I'd be surprised if it doesn't trigger lolbin detection in EDR/XDR)
* `runas /trustlevel:0x20000 "powershell.exe  -NoP -EP Bypass -File '$PSCommandPath'"` (does not properly drop integrity level, but disables the administrators group. New process will be integrity level high)
* `gsudo --integrity medium "$PSCommandPath"`
* Creating, starting, waiting, and deleting a scheduled task. (will be async, no access to console or UI and cannot accept any user input, also I think this requires asking for username and password to create the scheduled task, but I'm not quite sure if there is a way around it)
* Asking the user to enter their own credentials with which they're currently logged in to de-elevate using `Start-Process -FilePath pwsh.exe -ArgumentList '-noprofile' -Credential $credential -Wait` (which has the risk of leaking the credentials as well as exposing them in memory to all other currently running applications. It also renders other protections like e.g. lsass isolation kinda useless when the user has to enter their credentials into a process instead of just using SSO through the windows login. Also depending on how this is implemented it may cause credentials to get logged into the PowerShell eventlog and thereby shipped to a centralized SIEM).
* Stealing/Copying StartupInfo from explorer and spawning a process using it. (I don't think this (still?) works, but I've seen it being suggested...)
* `psexec -accepteula -l "$PSCommandPath"` (including the suggestion to base64 encode the psexe binary into the script and unpack it at runtime to use this (which usually also triggers EDR/XDR), however this also causes an integrity level of "low" and therefore less privileges than "just without elevation" and therefore is not what we want [we wanted Medium])
* copy pwsh or cmd and use `icacls C:\Windows\System32\cmd-high.exe /setintegritylevel medium` and then run it (didn't work for me. Still in elevated/high integrity level afterward, ironically this one is from MS learning https://learn.microsoft.com/en-us/previous-versions/dotnet/articles/bb625960(v=msdn.10)?redirectedfrom=MSDN, I tried it with both cmd and pwsh as well as using low as the article uses. Neither worked to drop the integrity level. The new process always also was at integrity level high when launched from an elevated process)
* Use PInvoke to lower own process token integrity and AdjustTokenPrivileges within the powershell script. (Basically what I suggested as # 2, but not done within PowerShell and therefore not a unified and streamlined experience. Also has a high risk of exposing stuff it shouldn't as different places outline different steps to do it and some (at least look) insecure and error prone. Esp. the ones that still keep a handle, threads, whatever using/to the original privileged token and invoke other executables which could open up a path to elevate without going through UAC for non elevated applications in same user session)
* ...

**Comment by rhubarb-geek-nz** [comment]
In the [issue #15562](https://github.com/PowerShell/PowerShell/issues/15562) it said

> It's often rather impractical to run your script as an unprivileged user or under a UAC-protected admin then elevate only the specific parts you require:

However, as I understand it, this is what has been addressed by the addition of `sudo`. This is certainly a common pattern used on UNIX.

**Comment by agowa** [comment]
@rhubarb-geek-nz The windows sudo is also the other way around untrusted to trusted.
> Welcome to the repository for [Sudo for Windows](https://aka.ms/sudo) 🥪. Sudo for Windows allows users to run elevated commands directly from unelevated terminal windows

https://github.com/microsoft/sudo

**Comment by agowa** [comment]
Well that was already possible before. The only thing sudo enables (as it reads, haven't tried it yet, as it is not available on windows servers) to basically have a form of `Start-Process -Verb RunAs -NoNewWindow` now.

However it is also a common thing on windows to go to full trust at the beginning (if needed for the application or script).
The only issue is now that winget is basically the first application that entirely refuses to work when it has more permissions than needed. Normally applications would "just work" as long as you're the correct user.
However when you run `winget install Spotify.Spotify` from within e.g. an "update all my software" script that runs as administrator because of all of the AllUser/Machine installs it will fail just fail. The only way to make it work is to use one of the above workarounds.

Because many developers orient themselves around what Microsoft does, it is probably only a matter of time until also other developers fail their application when it was started as administrator instead of AsLimited.

Almost all scripts that are written in enterprise and that need to do something as Admin at some point will get invoked as administrator (e.g. Because there is no way to have a scheduled task start asLimited and elevate as needed. Even with sudo this still won't work, as it is not available on server).

And even for scripts that are user triggered it has been a common theme to request all of the needed privileges at the start and have it run until completion without any user input afterward. It'd also kinda defeat the purpose of automation if you've to stand by and watch until it asks to approve elevation at random intervals...

**Comment by SeeminglyScience** [comment]
Can you elaborate on what effect the introduction of `sudo` has? It seems unrelated to the original issue.

> Nicely poke the Win32 people to add a new Verb for launching processes.

It's more motivating for other teams to get requests from users rather than other teams. We'd basically be saying "we heard some people want this" which isn't very meaningful. I'd recommend using the Feedback Hub to voice the request

**Comment by agowa** [comment]
@SeeminglyScience I don't know how sudo is related. However it was part of the reason for the initial decission for "Won't fix" in the original ticket. See https://github.com/PowerShell/PowerShell/issues/15562#issuecomment-903269556

**Comment by rhubarb-geek-nz** [comment]
There was this comment in the original.....

> The group concluded that such a feature should surface in a separate OS-specific cmdlet. Such a cmdlet can be developed and maintained outside the core engine and hosted in a gallery module.

If implementing the feature does not require access to the internals of PowerShell itself then I recommend building new components externally and publish in the PowerShell Gallery.

**Comment by agowa** [comment]
But then it's not part of Start-Process. Which is the whole point of this feature request.
Also Start-Process is already platform specific because of all of the `-Verb` stuff.
It really is the place where it should be in my eyes.

@SeeminglyScience is there a way to write a feedback hub item without using a web browser? I don't have a windows insider build running right now and feedback hub is not available on my work computer.

**Comment by rhubarb-geek-nz** [comment]
[ProcessStartInfo.Verb Property](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.verb?view=net-8.0#system-diagnostics-processstartinfo-verb)

> You should use only verbs that appear in the set of verbs returned by the [Verbs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.verbs?view=net-8.0) property.

If you want it as a verb, it needs to come from dotnet. 

If you just want the capability to drop the trust level then that can go in a new cmdlet and not have any additional dependencies.

**Comment by agowa** [comment]
Are you sure this is dotNet? I thought this is some Win32 stuff.
E.g. if I rename `HKEY_CLASSES_ROOT\exefile\shell\runasuser` into `runasuser2` the list `[System.Diagnostics.ProcessStartInfo]::new("test.exe").Verbs` returns also changes and now contains `runasuser2` instead of `runasuser`.

Isn't this Win32 stuff?

**Comment by rhubarb-geek-nz** [comment]
> Isn't this Win32 stuff?

I would expect so, it would even go back to 16-bit OLE I expect.

**Comment by jborean93** [comment]
`-Verb` is a shell (explorer shell not console shell) concept, dotnet exposes it in the `Process` class but it ultimately calls [ShellExecuteEx](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecuteexw) when you specify a Verb. It handles all the logic to decide what that verb means and what to do afterwards, i.e. send the ALPC request to UAC for `Runas`, finds the default extension application with `Open` and start that process, etc.

As for the task at hand this isn't an easy thing to do, there are a lot of hairy details that would need to be considered

+ Starting a new process with `explorer.exe` as a parent only works on a host with the shell experience installed
  + Rules out server core/nano
  + Starting with a custom parent changes how handles are inherited which is a whole other mess
  + Dotnet's Process class doesn't expose a way to set the parent process, while possible to do it with `CreateProcess` it's not simple to do
+ `runas /trustlevel:0x20000`/Safer APIs - same problem mentioned where it's close but still has a high integrity token
  + This API predated Vista/UAC so has no concept of integrity tokens
+ Getting the linked access token of the current user that is limited and starting a process with that
  + Requires the `SeTcbPrivilege` which admins don't have by default
  + You can technically impersonate `System` before doing this but this won't work if you don't have `SeDebugPrivilege`
  + Starting the process with an explicit token can't really use `CreateProcessAsUser` as it requires a privilege admin users don't normally have
  + Using `CreateProcessWithToken` doesn't require as many privileges but has more limitations (1024 command line length, must be new console)
  + The logic for this is complex so is quite a lot of code

I highly doubt the PowerShell team will want to take on this complexity, especially for something that is Windows specific. Your better options is

+ Find a module/write your own and share that can do this for you
  + I have one [ProcessEx](https://github.com/jborean93/ProcessEx) that can start a process with a custom parent or with an explicit access token
+ Petition whatever relevant team in Windows to expose a new Verb and have the shell/explorer handle this for you
+ Ask the team behind [windows sudo](https://github.com/microsoft/sudo) to add a flag that can run with the unelevated linked token
+ Find a 3rd party executable (psexec/gsudo) that can already do this
+ Hope the pwsh team implement this in some way - wait for the WG to triage this issue

An example of `ProcessEx` starting a limited version when you are elevated

```powershell
$explorer = Get-Process -Name explorer | Where-Object SessionId -eq (Get-Process -Id $pid).SessionId
$si = New-StartupInfo -ParentProcess $explorer
Start-ProcessEx pwsh.exe -StartupInfo $si
```

![image](https://github.com/PowerShell/PowerShell/assets/8462645/10fa9dde-1a4f-48be-abe5-32c8a2c711c8)

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience I don't know how sudo is related. However it was part of the reason for the initial decission for "Won't fix" in the original ticket. See [#15562 (comment)](https://github.com/PowerShell/PowerShell/issues/15562#issuecomment-903269556) (At least I think it was part of the decission. It is the last post before it was labeled as won't fix)

Ah thanks for the link, I didn't see that. Still unsure why they mentioned it as I don't think they're really linked in that way, but totally understand why it was brought up now.

> @SeeminglyScience is there a way to write a feedback hub item with only a web browser? I don't have a windows insider build running right now and feedback hub is not available on my work computer (because of privacy settings via GPO)

Sorry I'm not familiar enough. Worst case you could make a VM. Not great, but would work.

**Comment by jdhitsolutions** [comment]
Added for the Cmdlet WG to review again.

**Comment by SteveL-MSFT** [comment]
WG discussed this again.  We still agree that the scenario makes sense, but is an edge case and can be solved by other means (as evident by @jborean93's  examples).  We continue to suggest that if there is a need for this that it can be solved outside of PowerShell.
