### ISSUE TITLE
Failed to clone Powershell repository/installation

### ISSUE THREAD

**Issue by kalebers** [PowerShell/PowerShell#21240]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I'm experiencing issues when downloading/cloning the repository for Powershell on my MacOS catalina.

`kalebers@Kalebes-Air ~ % curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.4.1/powershell-7.4.1-osx-x64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to github.com port 443: Connection refused
kalebers@Kalebes-Air ~ % git clone https://github.com/PowerShell/PowerShell.git
Cloning into 'PowerShell'...
fatal: unable to access 'https://github.com/PowerShell/PowerShell.git/': Failed to connect to github.com port 443: Connection refused`

### Expected behavior

```console
Should get the installation of Powershell after doing the commands.
```

### Actual behavior

```console
Instead, I'm having the connetion refused error after the commands.
```

### Environment data

```powershell
-
```

**Comment by mklement0** [comment]
I suspect this was either a temporary server-side problem or there's a problem with your possibly proxy-mediated internet connection, because both commands work for me (macOS 14.2.1)

**Comment by kalebers** [comment]
Thanks for the tip! Actually a VPN config was blocking the download
