### ISSUE TITLE
Unexpected behavior of `AutomationNull` casting to `[String]`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#21250]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am probably wrong here, but when I cast an `AutomationNull` to a `[String]` I would expect an (empty) string back.
Knowing that a solid `$Null` does work as expected:
```PowerShell
[String]$Null | Should -BeOfType String
```
And casting a `AutomationNull` to another type works also as expected:
```PowerShell
[Int](& { @() }) | Should -BeOfType Int
```

### Expected behavior

```PowerShell
[String](& { @() }) | Should -BeOfType String
```

### Actual behavior

> InvalidResult: Expected the value to have type [string] or any of its subtypes, but got $null with type $null

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
It is consistent in that a null string is null value.

If you look at int, char, bool, decimal, double they are struct values, so when assigned null they become zero or false, but a string is an object reference.

So assigning null to a string gives you a null value. Because it is null, it does not refer to any object so as a value it has no type.

**Comment by iRon7** [comment]
@rhubarb-geek-nz 

Thanks for the answer.
