### ISSUE TITLE
External dependency on the buildinfo URLs

### ISSUE THREAD

**Issue by austoonz** [PowerShell/PowerShell#21254]
### Summary of the new feature / enhancement

As a user I want to take a dependency on the build info endpoints, without the URL or the format of the response breaking me in future. These endpoints seem like the most reliable endpoint for identifying the "latest" PowerShell version for each channel.

The endpoints I'm referring to are:

* https://aka.ms/pwsh-buildinfo-lts
* https://aka.ms/pwsh-buildinfo-stable
* https://aka.ms/pwsh-buildinfo-preview

Are the URLs and the JSON format of the response treated as a contract I can depend on?

**Comment by kilasuit** [comment]
I think you should be able to rely on these as I can't see why these would change at all, but I'm not on the team so can't confirm this for sure.

**Comment by StevenBucher98** [comment]
Yes those links can be depended on!

**Comment by austoonz** [comment]
Thank you for the confirmation!
