### ISSUE TITLE
`Move-Item` gives incorrect error message "The file exists" when destination file is used being used by a process

### ISSUE THREAD

**Issue by nopeless** [PowerShell/PowerShell#21251]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Move-Item -Force <source> <dest>` when dest is locked

I don't have latest version of powershell in my system, but I do have `7.3.7` and I don't see this issue mentioned on the issues tab so I'm pretty certain this issue will still exist in `7.5.0`

### Expected behavior

```console
The message should reflect the file state i.e "The file is being used by another process"
```

### Actual behavior

```console
The file exists
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by rhubarb-geek-nz** [comment]
The exception matches that returned by the .NET API, this is on Windows. Low level POSIX does allow files to be replaced when they already exist.

Error from Move-Item

```
PS D:\tmp> Move-Item .\src.txt .\dest.txt
Move-Item: Cannot create a file when that file already exists.
```

and with force

```
PS D:\tmp> Move-Item -Force .\src.txt .\dest.txt
Move-Item: Cannot create a file when that file already exists.
```

Error attempting to overwrite file using System.IO.Fille

```
PS D:\tmp> $file=[System.IO.File]::OpenWrite("dest.txt")
MethodInvocationException: Exception calling "OpenWrite" with "1" argument(s): "The process cannot access the file 'D:\tmp\dest.txt' because it is being used by another process."
```

Error trying to move to replace the file

```
PS D:\tmp> [System.IO.File]::Move("src.txt","dest.txt")
MethodInvocationException: Exception calling "Move" with "2" argument(s): "Cannot create a file when that file already exists."
```

Trying to delete the file does given the expected exception

```
PS D:\tmp> [System.IO.File]::Delete("dest.txt")
MethodInvocationException: Exception calling "Delete" with "1" argument(s): "The process cannot access the file 'D:\tmp\dest.txt' because it is being used by another process."
```

**Comment by nopeless** [comment]
@rhubarb-geek-nz  That's rather interesting. My idea would be that the process looks something like delete -> rename so `The process cannot access the file 'D:\tmp\dest.txt' because it is being used by another process.` makes sense. I am guessing that this problem is outside the scope of powershell, right?

**Comment by nopeless** [comment]
> I would expect Move-Item to attempt to just move the item and it is the responsibility of the caller to ensure the preconditions are correct.
> 
> For example in POSIX, moving a file is an atomic operation to replace the destination, so having a step to check if it exists and then attempt to delete would defeat the atomic behaviour.

This sounds outside the scope of powershell then. Where would I go to raise this issue?

**Comment by hb-webdev** [comment]
This "File exists" error was definitely confusing when I had the `-Force` flag enabled. Claude.ai didn't know what to make of it either. It's only thanks to this Github thread that i learned that **MAYBE** the issue was that the file was opened...Unsatisfactory outcome from this thread.

**Comment by nopeless** [comment]
@hb-webdev glad I could help
