### ISSUE TITLE
Console geometry in pwsh-7.5.0-preview.2

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#21267]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

80x24 regardless of terminal settings

### Expected behavior

```console
The console geometry must match the terminal settings
```

### Actual behavior

```console
80x24
```

### Error details

```console
No errors
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.2
PSEdition                      Core
GitCommitId                    7.5.0-preview.2
OS                             ArcoLinux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/4637b738-54a2-4d4a-85a4-d9316f5187cc)

**Comment by 237dmitry** [comment]
Returned on preview.1

**Comment by mklement0** [comment]
I see the problem on macOS too, but not on Windows.

What changed between preview.1 and preview.2 is the move from .NET 8 to .NET 9 (specifically, 9.0.100-preview.1.24101.2).

However, the problem does appear to be on the PowerShell side: when I compile a console application with the same SDK, the correct values are reported.

This bug makes the terminal experience on Unix-like platforms very frustrating.

**Comment by microhobby** [comment]
Same for me on Debian

![image](https://github.com/PowerShell/PowerShell/assets/2633321/9ffe9cdf-5e3d-4b69-860c-bc292ca27493)

**Comment by microhobby** [comment]
I suppose that the `s_terminalHandle` is `null` here: 
https://github.com/dotnet/runtime/blob/79dd9bae9bb881eb716b608577c4cedc6c9cba72/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L360-L361

Then it fallback to the `TerminalFormatStringsInstance.Columns`:

![image](https://github.com/PowerShell/PowerShell/assets/2633321/bcecd24b-b41b-4058-8dbe-7c4652e05b9d)
