### ISSUE TITLE
Invoke-WebRequest HandshakeFailure with TLS_ECDHE_ECDSA_WITH_AES

### ISSUE THREAD

**Issue by ChristianKrausse** [PowerShell/PowerShell#21262]
Invoke-WebRequest HandshakeFailure with TLS_ECDHE_ECDSA_WITH_AES

I run PowerShell 7.4.1 on a Windows 2022 Server (21H2 Microsoft Windows [Version 10.0.20348.2322])
My  goal is to check a bunch of URLs  but it seems on some Systems the vendor decided to limit the available CipherSuites.
So it seems to me, Powershell is working with Tls12 and Tls13 I can connect to servers using the Ciphers : 
    TLS_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384

But not: TLS_ECDHE_ECDSA_WITH_AES* which seem to be my problem

    # Try to Connect to my "problem" TLS Endpoint: (redacted)
    PS >Invoke-WebRequest https://my.testserver.invalid
    Invoke-WebRequest: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
----
    # query of relevant CipherSuites on the system where I want to execute the invoke-WebRequest
    PS > Get-TlsCipherSuite | findstr TLS_ECDHE_ECDSA_WITH_AES_
    Name                  : TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    Name                  : TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    Name                  : TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    Name                  : TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    Name                  : TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    Name                  : TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
----
    #Cipher Suites Supported by the requested System:
    Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
    -----------------------------------------------------------------------------------------------------------------
    xc02c   ECDHE-ECDSA-AES256-GCM-SHA384     ECDH 253   AESGCM      256      TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    xc024   ECDHE-ECDSA-AES256-SHA384         ECDH 253   AES         256      TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    xc02b   ECDHE-ECDSA-AES128-GCM-SHA256     ECDH 253   AESGCM      128      TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    xc023   ECDHE-ECDSA-AES128-SHA256         ECDH 253   AES         128      TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256

_Originally posted by @ChristianKrausse in https://github.com/PowerShell/PowerShell/issues/5159#issuecomment-1959485752_

**Comment by jborean93** [comment]
The TLS settings on newer dotnet versions just fallback to the OS settings as this isn't controlled at all by dotnet or PowerShell at this layer. Using [tls-web-server.py](https://gist.github.com/jborean93/28a3e44e3645d0ba56ad876adf33164a) which allows you to create a standalone HTTP TLS service where you can restrict the TLS versions and ciphers as a test:

```bash
$ ./tls_web_server.py --tls-max-protocol TLSv1_2 --tls-ciphers ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES256-GCM-SHA384
Listening on ('0.0.0.0', 39331)
192.168.56.15 - - [23/Feb/2024 06:12:42] "GET /get HTTP/1.1" 200 -
TLS Client {'protocol': 'TLSv1.2', 'cipher': 'ECDHE-ECDSA-AES256-GCM-SHA384', 'client_cert': None}
```

Then in PowerShell I did a `GET` request to that endpoint

```ps
PS > invoke-webrequest -uri https://192.168.56.1:39331/get -SkipCertificateCheck

StatusCode        : 200
StatusDescription : OK
Content           : {"tls": {"protocol": "TLSv1.2", "cipher": "ECDHE-ECDSA-AES256-GCM-SHA384", "client_cert": null}, "request_headers": {"Host": "192.168.56.1:39331",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Microsof…
RawContent        : HTTP/1.0 200 OK
                    Server: BaseHTTP/0.6
                    Server: Python/3.11.5
                    Date: Thu, 22 Feb 2024 20:12:42 GMT
                    Content-Type: application/json; charset=utf-8

                    {"tls": {"protocol": "TLSv1.2", "cipher": "ECDHE-ECD…
Headers           : {[Server, System.String[]], [Date, System.String[]], [Content-Type, System.String[]]}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 288
RelationLink      : {}
```

You can see there is no fundamental reason why it wouldn't work in PowerShell with `Invoke-WebRequest`. One thing you do need to make sure on is that the certificate you used on the web service end is configured with an ECDSA based key. If it's using an RSA key then the TLS handshake will fail with the error message you supplied.

**Comment by jborean93** [comment]
As per the request in https://github.com/PowerShell/PowerShell/issues/5159, this isn't really possible to do cross platform. While you can configure what TLS protocols are used, the underlying .NET library does not offer a cross platform way to restrict the cipher suites that are offered by the client. There is the functionality but it's currently Linux/macOS only as Schannel on Windows doesn't really offer an API to do the same thing.

**Comment by ChristianKrausse** [comment]
Thank  you @jborean93,

your [tls-web-server.py](https://gist.github.com/jborean93/28a3e44e3645d0ba56ad876adf33164a) works like a charm and invoke-webrequest is working as I expect.

But unfortunatly the "blackbox" Java-Based Werdserver I need to monitor, still says 'HandshakeFailure' if I try to connect.
With linux based "testssl"  It could connect with the mentioned "#Cipher Suites Supported by the requested System: "

As I could not change much on the Server and the "Cipher Suites" should work with Powershell, as I tested by myself, is there some other option to check the TLS-Endpoint? 

Maybe invoke-webrequest is not the best way to check the service, since it is in fact an AS4 Service (https://en.wikipedia.org/wiki/AS4), my goal is to check wether the Service is UP (some Status Code?) and maybe something like the "Common Name" (CN) and the "subjectAltName" (SAN)  of the Certificate.

**Comment by jborean93** [comment]
> As I could not change much on the Server and the "Cipher Suites" should work with Powershell, as I tested by myself, is there some other option to check the TLS-Endpoint?

It is interesting because my Python web server didn't work with that particular cipher until I added the ECDSA certificate generation. It could be that your webserver is using a RSA based certificate and `testssl` is able to handle that while Schannel cannot. I don't think that's the issue but at this point you might need to look into the network captures in a tool like Wireshark to compare the exchange.

> Maybe invoke-webrequest is not the best way to check the service, since it is in fact an AS4 Service (https://en.wikipedia.org/wiki/AS4), my goal is to check wether the Service is UP (some Status Code?) and maybe something like the "Common Name" (CN) and the "subjectAltName" (SAN) of the Certificate.

`Invoke-WebRequest` is certainly a few layers above testing just TLS. You could use something like [Test-Tls](https://gist.github.com/jborean93/52a56d28cb658000b64d82d900b5e882) to test just the TLS handshake but the error you shared initially means the handshake itself failed so this should most likely do the same.

**Comment by rhubarb-geek-nz** [comment]
> My goal is to check a bunch of URLs

Depending on what information you want to recover, these are two cross platform tools;

```
$ openssl s_client -showcerts -connect www.github.com:443 </dev/null
```

This can be used to get the SSL certificate of a server without validating it.

Alternatively you can use Java's keytool

```
$ keytool -printcert -sslserver www.github.com:443
```

**Comment by ChristianKrausse** [comment]
The Java Keytool and Openssl worked, so do I need to use third party tools?  I was hoping I could query these things with the native Powershell. thanks anyway

**Comment by jborean93** [comment]
If `openssl` and `keytool` works then it sounds like your Java server is providing data in a format that is incompatible with Schannel when using that cipher suite. Schannel is what PowerShell and most other native TLS tools use on Windows.

**Comment by jborean93** [comment]
It will use OpenSSL as that is what dotnet links to on non-Windows.
