### ISSUE TITLE
CorError.h is not in the Windows 10 SDK and PowerShell is using it

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#2127]
## Steps to reproduce

Build on a machine with only vc++ and windows 10 SDK
## Expected behavior

The build works
## Actual behavior

The build fails with the following error 

```
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /I"D:\git\PowerShell\src\powershell-native
  \nativemsh\pwrshcommon" /Zi /nologo /W3 /WX- /O1 /Ob2 /Oi /Oy- /GL /D WIN32 /D _WINDOWS /D NDEBUG /D CORECLR /D _AMD6
  4_ /D _WIN64 /D AMD64 /D BIT64=1 /D _TARGET_AMD64_=1 /D WIN32 /D _WIN32 /D WINVER=0x0602 /D _WIN32_WINNT=0x0602 /D WI
  N32_LEAN_AND_MEAN=1 /D _CRT_SECURE_NO_WARNINGS /D EnC_SUPPORTED /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Release\""
  /D _UNICODE /D UNICODE /U_MT /GF /Gm- /EHa /MT /Zp8 /GS /Gy /fp:precise /Zc:wchar_t- /Zc:forScope /Zc:inline /GR- /Fo
  "pwrshcommon.dir\Release\\" /Fd"pwrshcommon.dir\Release\pwrshcommon.pdb" /Gd /TP /FC /Zl /errorReport:queue  /d2Zi+ /
  Zm200 /ZH:SHA_256 /guard:cf "D:\git\PowerShell\src\powershell-native\nativemsh\pwrshcommon\pwrshcommon.cpp" "D:\git\P
  owerShell\src\powershell-native\nativemsh\pwrshcommon\WinSystemCallFacade.cpp" "D:\git\PowerShell\src\powershell-nati
  ve\nativemsh\pwrshcommon\ConfigFileReader.cpp"
  pwrshcommon.cpp
d:\git\powershell\src\powershell-native\nativemsh\pwrshcommon\pwrshcommon.cpp(12): fatal error C1083: Cannot open inclu
de file: 'corerror.h': No such file or directory [D:\git\PowerShell\src\powershell-native\nativemsh\pwrshcommon\pwrshco
mmon.vcxproj]
```
## Additional Info

Per this blog `corerror.h` was removed from the windows 10 SDK
https://naughter.wordpress.com/2015/05/24/changes-in-the-windows-10-sdk-compared-to-windows-8-1-part-two/

It is referenced at 
https://github.com/PowerShell/PowerShell/blob/eb3fd7ae6c8ed3e787beb9f4fd4f5c7b99921e65/src/powershell-native/nativemsh/pwrshcommon/pwrshcommon.cpp#L12

**Comment by TravisEz13** [comment]
@vors this is the issue we talked about

**Comment by TravisEz13** [comment]
To resolve this make sure your latest install windows 10 SDK has the following (highlighted in yellow) feature installed:
![image](https://cloud.githubusercontent.com/assets/10873629/18101709/a8f4a0d0-6ea4-11e6-9d1c-60a51d3f8af3.png)

**Comment by brycem** [comment]
I've found you can get this error even if you have the SDK installed - https://github.com/PowerShell/PowerShell/issues/2571

**Comment by iSazonov** [comment]
I found the file [here](https://github.com/dotnet/coreclr/blob/master/src/pal/prebuilt/inc/corerror.h).
Maybe need install Core SDK by dotnet cli?

**Comment by rjmholt** [comment]
I've experienced this a couple of times now -- my machine will build PowerShell, then a week later (it's a machine I don't use often) it will throw this error, and I have to go and repair/modify the Windows 10 SDK installation, possibly because updates have occurred.

**Comment by joeyaiello** [comment]
@TravisEz13 do you know if this has happened to anyone recently? If not, we can probably close it.
