### ISSUE TITLE
Microsoft Store version of PowerShell throws an exeception when running `Get-WindowsEdition -Online`

### ISSUE THREAD

**Issue by farag2** [PowerShell/PowerShell#21295]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

* Download the latest PowerShell 7.4.1 or 7.5 preview 2 from Microsoft Store;
* Run `Get-WindowsEdition -Online`;
* PowerShell hangs for a minute and throws an exception `Get-WindowsEdition: Class not registered`

To avoid the error, we need to import DISM module first, unlike in a Win32 PowerShell 7 version: `Import-Module -Name DISM -UseWindowsPowerShell`.

### Expected behavior

```console
PS C:\Users\Sanctuary\test> Get-WindowsEdition -Online
Edition : Professional
```

### Actual behavior

```console
PS C:\Windows\System32> Get-WindowsEdition -Online
Get-WindowsEdition: Class not registered
```

### Error details

```console
PS C:\Windows\System32> Get-Error

Exception             :
    Type       : System.Runtime.InteropServices.COMException
    ErrorCode  : -2147221164
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : [System.Management.Automation.MshCommandRuntime]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Class not registered

    Source     : System.Management.Automation
    HResult    : -2147221164
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
CategoryInfo          : NotSpecified: (:) [Get-WindowsEdition], COMException
FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsEditionCommand
InvocationInfo        :
    MyCommand        : Get-WindowsEdition
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : Get-WindowsEdition -Online
    Statement        : Get-WindowsEdition -Online
    PositionMessage  : At line:1 char:1
                       + Get-WindowsEdition -Online
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-WindowsEdition
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

PS C:\Windows\System32>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.26052
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![изображение](https://github.com/PowerShell/PowerShell/assets/10544660/7f14313a-3808-45b1-8dd2-b651d8044679)

**Comment by StevenBucher98** [comment]
Hmmm I am getting a different error on my Parallels windows VM, the command just hangs....

**Comment by farag2** [comment]
> Hmmm I am getting a different error on my Parallels windows VM, the command just hangs....

The same behaviour, but it unhangs after about 3 minutes for me.

**Comment by farag2** [comment]
Any workaround?

**Comment by SteveL-MSFT** [comment]
The PowerShell team has discussed limitations of calling the DISM APIs from the PS7 MSIX app and they are fully aware and working through how to solve that from within Windows as this is not something PS7 can solve.
