### ISSUE TITLE
Powershell Remoting via C# Throwing Error when using BasicAuthToOAuthConversion parameter with Exchange Online

### ISSUE THREAD

**Issue by nickjmcclure** [PowerShell/PowerShell#21290]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When attempting to open a remote runspace to Exchange Online, an exception is thrown claiming that the authentication mechanism is not supported. This occurs at `runspace.Open();`

A simple project can be found here to reproduce the issue: https://github.com/nickjmcclure/PSRunspaceTest

```csharp
using Microsoft.Identity.Client;
using System.Management.Automation;
using System.Management.Automation.Runspaces;
using System.Security;
using System.Security.Cryptography.X509Certificates;


string clientId = "";
string tenantId = "";
string tenantDomain = "";
string powerShellEndpoint = "https://outlook.office365.com/powershell-liveid/";

string pathToCert = @"";
string certPassword = "";


//Get the Access Token
X509Certificate2 cert = new(pathToCert, certPassword, X509KeyStorageFlags.Exportable);

IConfidentialClientApplication thisApp = ConfidentialClientApplicationBuilder.Create(clientId)
    .WithCertificate(cert)
    .WithAuthority($"https://login.windows.net/{tenantDomain}/")
    .Build();

AuthenticationResult accessToken = thisApp.AcquireTokenForClient(new[] { $"https://outlook.office365.com/.default" }).ExecuteAsync().Result;


//Create the PSCredential
string auth = $"Bearer {accessToken.AccessToken}";
SecureString password = GetSecureString(auth);

PSCredential psCredential = new($"OAuthUser@{tenantId}", password);


//Create the WSManConnectionInfo
string email = $"SystemMailbox{{bb558c35-97f1-4cb9-8ff7-d53741dc928c}}@{tenantDomain}";
string urlEncodedEmail = Uri.EscapeDataString(email);

Uri psURI = new($"{powerShellEndpoint}?BasicAuthToOAuthConversion=true&email={urlEncodedEmail}");

WSManConnectionInfo connectionInfo = new(psURI, "Microsoft.Exchange", psCredential)
{
    AuthenticationMechanism = AuthenticationMechanism.Basic,
};

//Create the Runspace and open the Runspace
using Runspace runspace = RunspaceFactory.CreateRunspace(connectionInfo);
runspace.Open();

using PowerShell ps = PowerShell.Create();


static SecureString GetSecureString(string input)
{
    SecureString password = new();
    foreach (char c in input)
    {
        password.AppendChar(c);
    }
    return password;
}
```

### Expected behavior

```console
Runspace should open using the oauth token provided and should be able to execute PowerShell commands against the remote runspace.
```

### Actual behavior

```console
Exception is thrown when calling runspace.Open()

Connecting to remote server outlook.office365.com failed with the following error message : The WinRM client cannot process the request.
```

### Error details

```console
System.Management.Automation.Remoting.PSRemotingTransportException
  HResult=0x80131501
  Message=Connecting to remote server outlook.office365.com failed with the following error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is not supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted traffic setting in the service configuration or specify one of the authentication mechanisms supported by the server.  To use Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the destination computer are joined to a domain. To use Basic, specify the computer name as the remote destination, specify Basic authentication and provide user name and password. Possible authentication mechanisms reported by server: For more information, see the about_Remote_Troubleshooting Help topic.
  Source=System.Management.Automation
  StackTrace:
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()
   at System.Management.Automation.Runspaces.RunspacePool.Open()
   at System.Management.Automation.RemoteRunspace.Open()
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jborean93** [comment]
Has Basic auth been enabled on the client WinRM settings?

```powershell
Get-Item WSMan:\Localhost\Client\Auth\Basic
```

**Comment by nickjmcclure** [comment]
@jborean93 would this be on the destination server, or the server running the .net app?

**Comment by jborean93** [comment]
The client host that is running the WinRM code. PowerShell on Windows uses the native WinRM stack. The native stack only allows Basic auth (what the OAuth tokens are smuggled through) if the client allows you to do so and it’s not enabled by default.

**Comment by nickjmcclure** [comment]
@jborean93 well, this is something that was working at one point, and now is not working. The code typically runs from an Azure App Service, so I don't believe there is a way for me to check there to see if this works or not. I can say that other operations that use basic auth to connect to our physical exchange environment work without issue. So I can only assume it is enabled.

**Comment by jborean93** [comment]
The error is from the WSMan stack and PowerShell is just bubbling it back up to you. PowerShell has no control over this policy as it’s a system setting and while it provides you the ability to get and set it through the WSMan provider it cannot just enable it for one connection. The error you are getting is what I would expect if basic auth is disabled on the client settings and you requested it.

**Comment by nickjmcclure** [comment]
@jborean93 so why does it work with some connections, but not the one to Exchange Online? and why does the error message state that the server refused it?

The complete exception includes this: "The authentication mechanism requested by the client is not supported by the server or unencrypted traffic is disabled in the service configuration."

**Comment by jborean93** [comment]
> so why does it work with some connections, but not the one to Exchange Online?

Exchange online uses OAuth tokens but as the WSMan stack on Windows never supported OAuth natively it actually it just OAuth smuggled through basic authentication. So to the WSMan stack it see ok the application is requesting basic auth is my client configuration set to allow this. Exchange on prem uses Kerberos auth and normal Windows hosts can utilise NTLM and Kerberos through the Negotiate protocol which is separate from Basic auth. Basic auth has always been something you need to opt into and the Exchange Online modules [even state you need to enable this](https://learn.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#turn-on-basic-authentication-in-winrm). Granted they are moving away from this frankenstein setup into their own REST APIs but this applies to your `WSManConnectionInfo` setup. This could even be the cause behind the problem but I'm not sure on that point.

> why does the error message state that the server refused it?

It could be that's just the generic error message it gets back from a failed auth, the client doesn't necessarily know what the server offers just that it failed to auth.

**Comment by nickjmcclure** [comment]
@jborean93 My on prem connection is using Basic, here is the code for it:

```csharp
PSCredential cred = new(_username, _securePassword);
WSManConnectionInfo connectionInfo = new(_powerShellURI, "http://schemas.microsoft.com/powershell/Microsoft.Exchange", cred)
{
    AuthenticationMechanism = AuthenticationMechanism.Basic
};

using Runspace runspace = RunspaceFactory.CreateRunspace(connectionInfo);
runspace.Open();

PowerShell ps0 = PowerShell.Create();
```

Also, my understanding is the `System.Management.Automation` and `Microsoft.PowerShell.Native` packages don't rely on any underlying system level configuration, they are self-contained libraries that allow .net apps to be shipped without any additional dependencies. At least this is the way it has been for the last 6 years when I initially built the first version of this application. As for migrating to rest APIs. I'd happily drop the PowerShell requirement and move to the Graph API, however the item I need to query for isn't exposed in the Graph API, and from what I can tell there are no plans to expose it.

I've been doing Basic auth from an Azure App Service using multiple versions of .net from Framework 4.7 to .net8 without having to do any WinRM changes on the server, or my local machine. None of the docs for the `System.Management.Automation` package state any system dependencies or configuration changes that need to be made.

**Comment by jborean93** [comment]
> Also, my understanding is the System.Management.Automation and Microsoft.PowerShell.Native packages don't rely on any underlying system level configuration, they are self-contained libraries that allow .net apps to be shipped without any additional dependencies

For WSMan that is not the case, even for SSH that's also not the case as it relies on the `ssh` binary being present. On Windows it relies on the `WsmSvc.dll` that Windows provides and non-Windows it's the `libmi` library that PowerShell used to ship with and was pretty old and hard to get working.

**Comment by nickjmcclure** [comment]
@daxian-dbw I noticed this was marked as answered, but it hasn't been answered. The information provided by @jborean93 doesn't apply here.
