### ISSUE TITLE
Document TabExpansion and ArgumentCompleter

### ISSUE THREAD

**Issue by MartinSGill** [PowerShell/PowerShell#2130]
TabExpansion could be a really nice feature of PowerShell, but it's very difficult to easily expand it. Usually if you want to you end up writing code like this:

```
if (Test-Path Function:\TabExpansion) {
    Rename-Item Function:\TabExpansion TabExpansionBackup
}
```

This approach is fine for a single module to extend TabExpansion, but you start running into all sorts of issues (like name collisions) when multiple modules start trying to do the same thing.

It would be great if there were a mechanism to register TabExpansion functions. e.g 

Register-TabExpansion -Command cmd.exe -ScriptBlock/File

Internally this function would simply be a map between the command (or an alias) and the function which would be called if the command is matched.

Once there is a consistent mechanism for TabExpansion it should be fairly easy for people to write modules to add expansions for various tools (git, rake, npm, etc), making powershell much more useable.

**Comment by lzybkr** [comment]
We need better documentation, but tab completion is pretty extensible right now.

Extensibility was part of the design introduced with `TabExpansion2` in V3, but registering completers wasn't, so I created [TabExpansionPlusPlus](http://github.com/lzybkr/TabExpansionPlusPlus) to help register those completers.

In V5, we added `Register-ArgumentCompleter` which is nearly identical to the one in `TabExpansionPlusPlus`. We also added the attribute [ArgumentCompleter](https://github.com/PowerShell/PowerShell/blob/c1faf1e6e10fc1ce45e84ef6f49ae7136c67a111/src/System.Management.Automation/engine/CommandCompletion/ExtensibleCompletion.cs#L27) which can be used in both [C#](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/GetCommandCommand.cs#L102) and in PowerShell.

**Comment by MartinSGill** [comment]
@lzybkr  Thanks for pointing out those features, i'd never have realised they were there.

I certainly agree about the documentation part https://technet.microsoft.com/en-us/library/mt631420.aspx looks a bit empty, as indeed does `Get-Help Register-ArgumentCompleter -Full`

I think entries about_TabExpansion (and an alias about_AutoComplete) in the help would be good, and Register-ArgumentCompleter also needs some documentation.

**Comment by vors** [comment]
I renamed the issue, based on the discussion.

**Comment by kilasuit** [comment]
There were a number of additional v5 (& now v5.1) features that could have done with clearer docs including classes.

Hopefully though with lead up to a "releasable" v6 we will be able to get this aligned and add in docs like these as well.

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShell-Docs#747
