### ISSUE TITLE
`Get-Process -IncludeUserName` fails to retrieve the user name for certain processes (`.UserName` property)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#21300]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Unlike for some system processes (e.g. `wininit`), the user name associated with `fontdrvhost` processes _can_ be retrieved, but as of v7.4.1 isn't reported via `Get-Process -IncludeUserName` - unlike in Windows PowerShell:

```powershell
# Run on a W11 machine
#requires -RunAsAdministrator
Get-Process -IncludeUserName fontdrvhost | % UserName
```

### Expected behavior

```console
Font Driver Host\UMFD-0
Font Driver Host\UMFD-1
```

This is what you get in Windows PowerShell.

### Actual behavior

```console
(No output)
```

### Environment data

```powershell
PowerShell 7.4.1 / 7.5.0-preview.2 on Windows 11
```

**Comment by jborean93** [comment]
https://github.com/PowerShell/PowerShell/pull/21302 fixes this issue by just using .NET to translate the SecurityIdentifier.

![image](https://github.com/PowerShell/PowerShell/assets/8462645/852efc75-9cd4-47e9-8fec-a73195e91e67)
