### ISSUE TITLE
`Get-Process`: Add a switch that limits retrieval to the current user's own processes

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#21301]
### Summary of the new feature / enhancement

When retrieving processes - either with or without a `-Name` filter - it would be helpful to allow limiting the set of candidate processes to the current user's _own_ processes, say with a newly introduced `-CurrentUser` (or `-User`) switch

```powershell
# WISHFUL THINKING

# Only retrieve processes started with the current user identity.
Get-Process -CurrentUser

# Only retrieve `cmd` processes started with the current user identity.
Get-Process -CurrentUser -Name cmd
```

It is often only one's own processes that are of interest, especially when running _non-elevated_.

In non-elevated sessions, there's currently no easy way to determine which processes are one's own.
_Update_: One's own means: all processes running with the current user identity, irrespective of how they were started - see discussion in the next two comments.

Even in elevated sessions the solution is cumbersome:
`Get-Process -IncludeUserName  | Where UserName -eq $env:USERDOMAIN\$env:USERNAME`

### Proposed technical implementation details (optional)

Add the new switch only to the `Name` parameter set.

It would be the (possibly `-Name`-filtered) equivalent of the following, which on Windows can currently only be run with elevation:

```powershell
#requires -RunAsAdministrator
Get-Process -IncludeUserName  | 
  Where UserName -eq ($IsWindows ? "$env:USERDOMAIN\$env:USERNAME" : $env:USER)
```

**Comment by jborean93** [comment]
I'm not sure this is going to be too helpful as I don't think there is one definition of your "own" processes. Does your own process include

+ Processes running as your user but in another session (network logon/winrm/scheduled task/other user running as you)
+ You running processes as other users in your current session (`runas.exe`, `Start-Process ... -Credential $cred`)
+ Others running in your current session through various means (interactive scheduled task)

Unfortunately I don't think a single parameter can really convey the user's intent (they probably don't even know themselves) but that's just my opinion.

**Comment by mklement0** [comment]
@jborean93, I was thinking that it should encompass what `Get-Process -IncludeUserName  | 
  Where UserName -eq ($IsWindows ? "$env:USERDOMAIN\$env:USERNAME" : $env:USER)` returns, which, from what I gather, includes the first and the third of your groups, but not the second.

In other words: any processes on the local machine running with your own user identity, irrespective of how they were launched.

This is easy to conceptualize and document, and I suspect it is good enough in most cases.
(If needed, further analysis can be performed on the returned process-information objects; I don't think more fine-grained support by `Get-Process` is warranted.)

While your PR #21302 will allow running the above command even in non-elevated sessions, the proposed switch enables a  much simpler solution that is a direct expression of the intent.

**Comment by rhubarb-geek-nz** [comment]
This sounds like the thing [Console Process Groups](https://learn.microsoft.com/en-us/windows/console/console-process-groups) or UNIX setpgrp() is designed for. Eg in UNIX processes that share the same controlling terminal, or are part of the same process tree.

**Comment by mklement0** [comment]
* As long as the implementation effort isn't prohibitive, _it should not matter whether an underlying .NET API exists_: The only thing that should matter is whether the functionality is a useful addition to `Get-Process` in line with its mandate. After all, PowerShell is much more than just a layer on top of .NET APIs.

* Currently, the proposed `Where-Object` solution isn't possible _except in elevated sessions_, which is an unnecessary limitation.

* While PR #21302, if accepted  (🤞), will lift this limitation, consider the awkwardness of a `Where-Object` solution compared to the simplicity of the proposed solution.

```powershell
Get-Process -IncludeUserName  | 
  Where-Object UserName -eq ($IsWindows ? "$env:USERDOMAIN\$env:USERNAME" : $env:USER)

# vs. (wishful thinking)

Get-Process -CurrentUser
```
