### ISSUE TITLE
Listbox doesn't show in version 7.4.1 

### ISSUE THREAD

**Issue by JupyterPS** [PowerShell/PowerShell#21315]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This snippet activates a listbox in 5.1 and no listbox in 7.4:
#load the appropriate assemblies
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms.DataVisualization")

#create chart
$Chart = New-object System.Windows.Forms.DataVisualization.Charting.Chart
$Chart.Width = 500
$Chart.Height = 400
$Chart.Left = 40
$Chart.Top = 30

#create a chartarea to draw on and add to chart
$ChartArea = New-Object System.Windows.Forms.DataVisualization.Charting.ChartArea
$Chart.ChartAreas.Add($ChartArea)

#listbox form
$form = New-Object System.Windows.Forms.Form
$form.Text = 'FjernvarmeChart 2020'
$form.Size = New-Object System.Drawing.Size(300,280)
$form.StartPosition = 'CenterScreen'

#legend
$legend = New-Object system.Windows.Forms.DataVisualization.Charting.Legend
$legend.name = "Legend1"
$Chart.Legends.Add($Legend)
$Legend.Docking = 'bottom'

$okButton = New-Object System.Windows.Forms.Button
$okButton.Location = New-Object System.Drawing.Point(75,190)
$okButton.Size = New-Object System.Drawing.Size(75,23)
$okButton.Text = 'OK'
$okButton.DialogResult = [System.Windows.Forms.DialogResult]::OK
$form.AcceptButton = $okButton
$form.Controls.Add($okButton)

$cancelButton = New-Object System.Windows.Forms.Button
$cancelButton.Location = New-Object System.Drawing.Point(150,190)
$cancelButton.Size = New-Object System.Drawing.Size(75,23)
$cancelButton.Text = 'Cancel'
$cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $cancelButton
$form.Controls.Add($cancelButton)

$label = New-Object System.Windows.Forms.Label
$label.Location = New-Object System.Drawing.Point(10,20)
$label.Size = New-Object System.Drawing.Size(280,20)
$label.Text = ' '
$form.Controls.Add($label)

#listbox
$listBox = New-Object System.Windows.Forms.ListBox
$listBox.Location = New-Object System.Drawing.Point(10,40)
$listBox.Size = New-Object System.Drawing.Size(260,20)
$listBox.Height = 135

             # listbox
             [void] $listBox.Items.Add('                                  👀')
             $y=2020
             $x=2021
             $z=2022
             $count = 1
             $Xyear = @()
             $antyear = (Get-Date).year - 2019
             While ($count -lt $antyear)
             {
                  $Xyear += @("$y $x $z")
                  $y++
                  $x++
                  $z++
                  $count ++
             }

             [void]$listBox.Items.AddRange($Xyear)
             $form.Controls.Add($listBox)
             $form.Topmost = $true
             $result = $form.ShowDialog()

### Expected behavior

```console
show listbox
```

### Actual behavior

```console
no listbox
```

### Error details

```console
no errors at all
```

### Environment data

```powershell
[32;1mName                          [0m[32;1m Value[0m
[32;1m----                          [0m [32;1m-----[0m
PSVersion                      7.4.1
```

### Visuals

x

**Comment by mklement0** [comment]
Please use fenced code blocks to properly format your code and provide complete environment information.

I get the following when I run your code, both in Windows PowerShell as well as in PowerShell 7.4.1 and PowerShell 7.5.0-preview.2 on my W11 22H2 machine:

<img width="284" alt="image" src="https://github.com/PowerShell/PowerShell/assets/588825/b3eda5fc-fcd4-496b-9477-c42f865ca68d">

In other words: I cannot reproduce the problem.

**Comment by JupyterPS** [comment]
So, what do you want me to do about that? I had expected you to come up with "try this snippet" or suggestions that would reveal the truth!!

**Comment by mklement0** [comment]
Thanks for confirming, @rhubarb-geek-nz (the problem with the first `.Add()` is incidental; it suggests that you didn't use a UTF-8 file _with BOM_, which Windows PowerShell requires).

**Comment by JupyterPS** [comment]
I have changed to 7.4.1 within the last weeks and therefore I am baffled so much noise I get from the new version! I have a pretty big collection of Powershell scripts and whatever so I need somebody's shoulder to cry out on! I have had a good collaboration with AI; but "he" reckons I should "confront" you with "all" the red I see in the command pane; but if you do not/cannot give any advice that gets me rolling again, I shall forget about 7.4.1

**Comment by rhubarb-geek-nz** [comment]
> I have changed to 7.4.1 within the last weeks and therefore I am baffled so much noise I get from the new version! 

90% of your code is not actually PowerShell code, it is dotnet. If you have moved straight from PowerShell 5.1 to PowerShell 7.4.1 then you have also moved from .NET framework 4.x to .NET Core 8.

**Comment by mklement0** [comment]
Let's take a step back, @JupyterPS:

* Both @rhubarb-geek-nz and I are fellow PowerShell users and speak in no official capacity.

* We extended you the courtesy of trying to reproduce the problem, but couldn't.

* You posted an incomplete bug report, and even though you added more code later, the information about your runtime environment - which may or may not matter in the end - is still missing.

* The more information you provide - ideally up front - the better the chances of narrowing down the problem. Ultimately, if no one else can reproduce your problem, no action can be taken here, and your problem won't be solved.

* Even if an actual problem _with PowerShell_ is eventually isolated (as implied by @rhubarb-geek-nz's comment, sometimes it is a _.NET_ problem that simply surfaces via PowerShell), there's no guaranteed time frame for a fix (there are many verified bugs that have been open for a long time). However, knowing the problem usually allows finding a _workaround_.

**Comment by JupyterPS** [comment]
Is this a community of helpers?

**Comment by mklement0** [comment]
By and large, yes. 
But, invariably, only those willing to be helped and willing to participate constructively in that process _can_ be helped.

**Comment by JupyterPS** [comment]
you must be kidding, we have just stated, unless you want to bail out!
