### ISSUE TITLE
System.Windows.Forms.ListBox doesn't show

### ISSUE THREAD

**Issue by JupyterPS** [PowerShell/PowerShell#21314]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

#load the appropriate assemblies
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms.DataVisualization")
#listbox
$listBox = New-Object System.Windows.Forms.ListBox
_______________________________________________________________
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition   
_______________________________________________________________
When running my listbox script in 7.4.1, the listbox doesn't show. In one incident it was hidden behind the powershell page.
Works fine in 5.1

### Expected behavior

```console
Show listbox
```

### Actual behavior

```console
No listbox at all, and the run botton is on
```

### Error details

```console
No "noice" what so ever
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition
```

**Comment by JupyterPS** [comment]
This snippet activates a listbox in 5.1 and no listbox in 7.4:
#load the appropriate assemblies
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms.DataVisualization")

#create chart
$Chart = New-object System.Windows.Forms.DataVisualization.Charting.Chart 
$Chart.Width = 500
$Chart.Height = 400
$Chart.Left = 40
$Chart.Top = 30

#create a chartarea to draw on and add to chart
$ChartArea = New-Object System.Windows.Forms.DataVisualization.Charting.ChartArea
$Chart.ChartAreas.Add($ChartArea)

#listbox form
$form = New-Object System.Windows.Forms.Form
$form.Text = 'FjernvarmeChart 2020'
$form.Size = New-Object System.Drawing.Size(300,280)
$form.StartPosition = 'CenterScreen'

#legend
$legend = New-Object system.Windows.Forms.DataVisualization.Charting.Legend
$legend.name = "Legend1"
$Chart.Legends.Add($Legend)
$Legend.Docking = 'bottom'

$okButton = New-Object System.Windows.Forms.Button
$okButton.Location = New-Object System.Drawing.Point(75,190)
$okButton.Size = New-Object System.Drawing.Size(75,23)
$okButton.Text = 'OK'
$okButton.DialogResult = [System.Windows.Forms.DialogResult]::OK
$form.AcceptButton = $okButton
$form.Controls.Add($okButton)

$cancelButton = New-Object System.Windows.Forms.Button
$cancelButton.Location = New-Object System.Drawing.Point(150,190)
$cancelButton.Size = New-Object System.Drawing.Size(75,23)
$cancelButton.Text = 'Cancel'
$cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $cancelButton
$form.Controls.Add($cancelButton)

$label = New-Object System.Windows.Forms.Label
$label.Location = New-Object System.Drawing.Point(10,20)
$label.Size = New-Object System.Drawing.Size(280,20)
$label.Text = '                          '
$form.Controls.Add($label)

#listbox
$listBox = New-Object System.Windows.Forms.ListBox
$listBox.Location = New-Object System.Drawing.Point(10,40)
$listBox.Size = New-Object System.Drawing.Size(260,20)
$listBox.Height = 135

                 # listbox
                 [void] $listBox.Items.Add('                                  👀')
                 $y=2020
                 $x=2021
                 $z=2022
                 $count = 1
                 $Xyear = @()
                 $antyear = (Get-Date).year - 2019
                 While ($count -lt $antyear)
                 {
                      $Xyear += @("$y $x $z")
                      $y++
                      $x++
                      $z++
                      $count ++
                 }

                 [void]$listBox.Items.AddRange($Xyear)
                 $form.Controls.Add($listBox)
                 $form.Topmost = $true
                 $result = $form.ShowDialog()

**Comment by JupyterPS** [comment]
#load the appropriate assemblies
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void][Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms.DataVisualization")

#create chart
$Chart = New-object System.Windows.Forms.DataVisualization.Charting.Chart
$Chart.Width = 500
$Chart.Height = 400
$Chart.Left = 40
$Chart.Top = 30

#create a chartarea to draw on and add to chart
$ChartArea = New-Object System.Windows.Forms.DataVisualization.Charting.ChartArea
$Chart.ChartAreas.Add($ChartArea)

#listbox form
$form = New-Object System.Windows.Forms.Form
$form.Text = 'FjernvarmeChart 2020'
$form.Size = New-Object System.Drawing.Size(300,280)
$form.StartPosition = 'CenterScreen'

#legend
$legend = New-Object system.Windows.Forms.DataVisualization.Charting.Legend
$legend.name = "Legend1"
$Chart.Legends.Add($Legend)
$Legend.Docking = 'bottom'

$okButton = New-Object System.Windows.Forms.Button
$okButton.Location = New-Object System.Drawing.Point(75,190)
$okButton.Size = New-Object System.Drawing.Size(75,23)
$okButton.Text = 'OK'
$okButton.DialogResult = [System.Windows.Forms.DialogResult]::OK
$form.AcceptButton = $okButton
$form.Controls.Add($okButton)

$cancelButton = New-Object System.Windows.Forms.Button
$cancelButton.Location = New-Object System.Drawing.Point(150,190)
$cancelButton.Size = New-Object System.Drawing.Size(75,23)
$cancelButton.Text = 'Cancel'
$cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $cancelButton
$form.Controls.Add($cancelButton)

$label = New-Object System.Windows.Forms.Label
$label.Location = New-Object System.Drawing.Point(10,20)
$label.Size = New-Object System.Drawing.Size(280,20)
$label.Text = ' '
$form.Controls.Add($label)

#listbox
$listBox = New-Object System.Windows.Forms.ListBox
$listBox.Location = New-Object System.Drawing.Point(10,40)
$listBox.Size = New-Object System.Drawing.Size(260,20)
$listBox.Height = 135

             # listbox
             [void] $listBox.Items.Add('                                  👀')
             $y=2020
             $x=2021
             $z=2022
             $count = 1
             $Xyear = @()
             $antyear = (Get-Date).year - 2019
             While ($count -lt $antyear)
             {
                  $Xyear += @("$y $x $z")
                  $y++
                  $x++
                  $z++
                  $count ++
             }

             [void]$listBox.Items.AddRange($Xyear)
             $form.Controls.Add($listBox)
             $form.Topmost = $true
             $result = $form.ShowDialog()

**Comment by JupyterPS** [comment]
See the snippet code above for your test in 7.4

**Comment by mklement0** [comment]
Since you've created an effective duplicate in #21315, please close this issue.
