### ISSUE TITLE
Odd Issue with Get-CsOnlineLisLocation

### ISSUE THREAD

**Issue by JG-Robo** [PowerShell/PowerShell#21329]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Let's say you have Two Emergency Address: A and B
A has place called "Floor 1" and a place called "Floor 1, Floor 2" (some subnets are only on 1 and some span 1 and 2)
B has a place called "Floor 1"
"Get-CsOnlineLisLocation -Location "floor 1" will return all 3 locations above.. not just the ones for A and B. I would expect it to only return "Floor 1" from A and B .. ?

"Get-CsOnlineLisLocaiton -Location "Floor 1" | ? {$_civicaddressid -eq "someGUID"}" will return both results for Address A. I would expect it to only return "Floor 1" from Location A ?

"Get-CsOnlineLisLocation | ? {$_.location -eq "Floor 1"}" you will get Floor 1 from A and Foor 1 from B - I would think this is expected behavior.

"Get-CsOnlineLisLocation | ? {$_.location -eq "Floor 1"  -and $_Civicaddressid -eq "someguid"}" you will only get Floor 1 from A. I would think this is expected.

It seems using the -Location parameter is doing a like or contains match in some instances. In earlier versions this was even worse but it appears some of the issues have been fixed.

### Expected behavior

```console
get-csOnlineLisLocation -location "Floor 1" | fl location, civicaddressid

Location       : Floor 1
CivicAddressId : e7311871-9d63-4715-a34f-6c0b147b3f56

Location       : Floor 1
CivicAddressId : 436951b6-d75f-437f-b0f0-bfc399a1b1c6
```

### Actual behavior

```console
get-csOnlineLisLocation -location "Floor 1" | fl location, civicaddressid

Location       : Floor 1
CivicAddressId : e7311871-9d63-4715-a34f-6c0b147b3f56

Location       : Floor 1
CivicAddressId : 436951b6-d75f-437f-b0f0-bfc399a1b1c6

Location       : Floor 1, Floor 2
CivicAddressId : 436951b6-d75f-437f-b0f0-bfc399a1b1c6
```

### Error details

```console
No errors just unexpected results
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

nothing here

**Comment by rhubarb-geek-nz** [comment]
This does not look like part of PowerShell Core

```
PS> Get-Command get-csOnlineLisLocation
Get-Command: The term 'get-csOnlineLisLocation' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

This looks like it is part of [MicrosoftTeams](https://www.powershellgallery.com/packages/MicrosoftTeams).

The projects URL points to [office-docs-powershell](https://github.com/MicrosoftDocs/office-docs-powershell/tree/main/teams).

**Comment by mklement0** [comment]
Indeed the originating module, [`SkypeForBusiness`](https://learn.microsoft.com/en-us/powershell/module/skype/?view=skype-ps), isn't being maintained in this repo.

The official advice for reporting issues with modules that ship with Windows (rather than as part of PowerShell) and aren't open-source is, taken from the now _obsolete_ [PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage) repo (emphasis added):  

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

Generally, if you define the following function and pass it the name of a command, the `.BuiltIn` output property (column) will tell you whether the command ships with PowerShell itself or not, and what (possibly external) module it comes from:

```powershell
function Get-CommandOrigin {
  param([Parameter(Mandatory)] $Command)
  $cmd = Get-Command $Command -ErrorAction Stop
  if ($cmd.ResolvedCommand) { $cmd = $cmd.ResolvedCommand }
  [pscustomobject] @{
    Command = $cmd
    BuiltIn = $cmd.ModuleName -and (-not $cmd.Module -or $cmd.Module.Path.StartsWith($PSHOME))
    Module = $cmd.Module ?? $cmd.ModuleName
  }
}
```

**Comment by mklement0** [comment]
@JG-Robo, no worries: the issue templates currently provide little guidance as to how to find out whether a given cmdlet is built in or not.

As noted, you'll have to use [the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) to report your issue.
