### ISSUE TITLE
Set-AuthenticodeSignature Changes Script

### ISSUE THREAD

**Issue by v-mimcbr** [PowerShell/PowerShell#2133]
## Steps to reproduce

run Set-AuthenticodeSignature -Certificate $cert -FilePath $AttachedScript
## Expected behavior

Only the signature should change
## Actual behavior

$Global:LogRoot = "\cyprus\share\ITScriptOutput" 
to
$Global:LogRoot = "\cyprus\share\ITScriptOutput

The last character was removed
[settings.txt](https://github.com/PowerShell/PowerShell/files/445770/settings.txt)
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by GeeLaw** [comment]
This issue is reproducible for:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.82
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.82
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ThomasNieto** [comment]
@v-mimcbr is this still an issue with the latest version of PowerShell?

**Comment by doctordns** [comment]
I can not duplicate this in the latest versions of PowerShell.

Can we close this issue?

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this be closed as the issue can not be duplicated?
