### ISSUE TITLE
Powershell 5.1 to Powershell 7 migration: impicit cast breaking change (double/int)?

### ISSUE THREAD

**Issue by rangercej** [PowerShell/PowerShell#21369]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This may be intentional, but I can't find any documentation to back this up - but it appears that there's some implicit casting differences/breaking changes in behaviour between Powershell 5.1 and Powershell 7. The code below is a minimum reproduction of the issue from a larger script we have that does some string manipulation.

```
$x = [Math]::Floor(13/3)
write-host "x = $x of type [$($x.GetType())]"
$s = "This is a test string for test purposes" -split ' '
[string]::Join("-", $s, $s.Length - $x, $x)
[string]::Join("-", $s, $s.Length - [int]$x, $x)
```

In Powershell 5.1, both of the final lines output: "string-for-test-purposes", however in Powershell 7, the first Join appears to not cast a parameter well, and outputs is as shown below. Explicitly casting the double to an int resolves the issue (as demonstrated in the final line of output).

We can obviously workaround this with explicit casts where this turns out to be a problem.

### Expected behavior

```console
Script above should output (this is what PS5.1 does, but not PS7):

x = 4 of type [double]
string-for-test-purposes
string-for-test-purposes
```

### Actual behavior

```console
Script above actually outputs on PS7:

x = 4 of type [double]
System.String[]-4-4
string-for-test-purposes
```

### Error details

```console
n/a
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

n/a

**Comment by mklement0** [comment]
The problem is an unfortunate side effect of new `String.Join` method overloads having been introduced in .NET (Core), `static string Join(string separator, Params System.Object[] values)`, and `static string Join(char separator, Params System.Object[] values)`

That is, PowerShell's behavior hasn't changed, but it now happens to find one of the new overloads.

Unfortunately, such inadvertent breaking changes cannot be avoided _unless_ the method parameter types are matched exactly.

While your `[int]` cast happens to be sufficient to find the previously selected overload, the fully robust formulation would be:

```powershell
# Note: [string[]] isn't strictly necessary, because that's the type -split returns.
[string]::Join("@", [string[]] $s, [int] ($s.Length - $x), [int] $x)
```

See https://github.com/PowerShell/PowerShell/issues/11720#issuecomment-579866445 for a similar case in the context of `String.Split()`, which manifests more frequently.

**Comment by rangercej** [comment]
Thanks @mklement0  - I didn't think of looking at the overloads, but that makes sense. I'll bear this in mind for any other migration issues we bump in to.  Is it worth updating the [5.1 to 7 Migration page ](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.4) to draw this out more explicitly? It probably should be a given that PS 7 runs against a different version of .Net to PS 5.1, but maybe a line that makes it explicit that there may be additional overrides introduced that could break scripts, and so explicit casts may be needed where they weren't previously.

**Comment by mklement0** [comment]
Adding this to the linked documentation page makes sense to me, and I encourage you to create an issue to suggest it.
 
You can click on the "Open a documentation issue" link at the bottom of the page, which creates a new issue in https://github.com/MicrosoftDocs/PowerShell-Docs specific to that very page.

**Comment by rangercej** [comment]
@mklement0 - thanks for the pointer. Ticket raised and it looks like docs around this have been updated and are now live, so something more formal to point folk to: https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.4

**Comment by mklement0** [comment]
Thank you, @rangercej. 👍
