### ISSUE TITLE
Get-LocalGroupMember Group Administrators will fail if Intune DEM accounts are members

### ISSUE THREAD

**Issue by TassieTrooper** [PowerShell/PowerShell#21362]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Get-LocalGroupMember -Group "Administrators" will fail if Intune DEM accounts are members BUT the account has not resolved to EID, which is apparent when the respective SID is displayed and not resolved to EID UPN SAM account name.

Scenario/Config:
EID Joined PC
AAADC Sync of Users and Groups to EID.
DEM accounts do not exist in Local AD.

Get-LocalGroupMember : Failed to compare two elements in the array.
At line:1 char:1
+ Get-LocalGroupMember -Group "Administrators"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException
    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand

### Expected behavior

```console
ObjectClass Name                       PrincipalSource
----------- ----                       ---------------
User        MyDomain\SAMAccount             AzureAD
User        MyDomain\SAMAccount             AzureAD
User        MyDomain\SAMAccount             AzureAD
User        MyPCName\Administrator Local

Or...
ObjectClass Name                       PrincipalSource
----------- ----                       ---------------
User        Unknown                         AzureAD
User        Unknown                         AzureAD
User        MyDomain\SAMAccount             AzureAD
User        MyPCName\Administrator Local

Or...
ObjectClass Name                       PrincipalSource
----------- ----                       ---------------
User        Device Manager Admin            AzureAD
User        Device Manager Admin2           AzureAD
User        MyDomain\SAMAccount             AzureAD
User        MyPCName\Administrator Local
```

### Actual behavior

```console
Get-LocalGroupMember : Failed to compare two elements in the array.
At line:1 char:1
+ Get-LocalGroupMember -Group "Administrators"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException
    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand
```

### Error details

```console
Get-LocalGroupMember : Failed to compare two elements in the array.
At line:1 char:1
+ Get-LocalGroupMember -Group "Administrators"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException
    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mklement0** [comment]
The official advice for reporting issues with modules that ship with Windows (rather than as part of PowerShell) and aren't open-source is, taken from the now _obsolete_ [PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage) repo (emphasis added):  

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

If you define the following function and pass it the name of a command, the `.BuiltIn` output property (column) will tell you whether the command ships with PowerShell itself or not, and what (possibly external) module it comes from:
```
function Get-CommandOrigin {
  param([Parameter(Mandatory)] $Command)
  $cmd = Get-Command $Command -ErrorAction Stop
  if ($cmd.ResolvedCommand) { $cmd = $cmd.ResolvedCommand }
  [pscustomobject] @{
    Command = $cmd
    BuiltIn = $cmd.ModuleName -and (-not $cmd.Module -or $cmd.Module.Path.StartsWith($PSHOME))
    Module = $cmd.Module ?? $cmd.ModuleName
  }
}
```

**Comment by TassieTrooper** [comment]
OK thanks. Let me check that. (And I was thinking this might be as you said, so my apologies for lack of effort researching before posting.)

**Comment by mklement0** [comment]
No worries, @TassieTrooper - the bug-report issue template really should have an additional check box for ensuring that the command in question is maintained in this repo, with explicit guidance on how to determine that.
