### ISSUE TITLE
Modules like PowerShell Get need the version bumped up when modified

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#2136]
https://github.com/PowerShell/PowerShell/blob/master/src/Modules/Shared/PowerShellGet/PowerShellGet.psd1 - This still shows 1.0.0.1 for the module version (same version as the module that was bundled with Win10 10586) even though there have been a number of changes to this module since July 2015

This follows on from the request in #1979 to decouple any included modules like PowerShell Get so that with these modules we can have a build & release process that we have confidence in and this is becoming more and more important to get right as the number of changes to this Repository grows.

**Comment by zipzit** [comment]
If you are a user, is there any way to determine which version of powershell you are running? 
`powershell help` and `powershell help version` reveal nothing.   `powershell --version` and `powershell -ver` reveal nothing.   There is no menu select for "About" or anything related.  And why isn't such a command available by an observer starting at `powershell help` ? 

Why the big secret?   Is the version level such a big secret, or am I just doing this wrong?

**Comment by kilasuit** [comment]
@zipzit you would have to start powershell and then run
```powershell
$PSVersionTable.PSVersion
```
that is the correct way to find the version of PowerShell that you are running. 

If you are new to using powershell then take a look at the following learning powershell page at https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell

**Comment by bmanikm** [comment]
Fixed in #2372

**Comment by kilasuit** [comment]
@bmanikm It may be fixed for PowerShellGet however this needs to be **enforced on all inbox shipped modules** until #1979 has been completed and each module has decoupled and has a reliable and robust build process that all users can trust in which is especially truthful of all MS released modules

Currently I haven't got that level of trust that any change in any of the modules shipped inside of this repository, regardless of the size of the change, couldn't end up bringing an unforeseen breaking change somewhere else down the line.

Don't get me wrong as now PowerShell has been Open Sourced the direction is going the right way to being able to actually have that level of trust however there is still work to be done to get us there so could you re-open this until #1979 has been completed

**Comment by bmanikm** [comment]
Thanks @kilasuit!, I have updated my above comment.

**Comment by SteveL-MSFT** [comment]
@zipzit getting the powershell version using -version without argument makes sense, can you open as a new issue?

**Comment by joeyaiello** [comment]
We should do this, but I think it's probably more in line with whenever we do the module refactoring.

**Comment by kilasuit** [comment]
Bumping this to get a review - is this something that the internal modules to PSCore that aren't being decoupled in #1979 are getting their versions updated when there are updates to them?

**Comment by kilasuit** [comment]
@SteveL-MSFT are changes to the modules that are bundled as part of PSCore getting version bumped at all? Because technically they should be in line with the version of PSCore unless they can be decoupled further as part of #1979 which would help #5681 out

**Comment by SteveL-MSFT** [comment]
@kilasuit we haven't been keeping the module version updated with the PSCore6 version partly because it's manual and partly because the modules aren't separate.  Once decoupled, it will be easier to have them rev as needed.

**Comment by kilasuit** [comment]
I think this can be closed now as many modules got decoupled and they now have proper versioning
