### ISSUE TITLE
Application to join the Cmdlets and Modules Working Group

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#21360]
### Name of Working Group you are requesting to join?

Cmdlets and Modules

### Can you provide at least 1 hour per week to the Working Group? Note that time commitments will vary per Working Group and decided by its members.

Yes

### Why do you want to join this working group?

To help improve the core cmdlets and modules shipped with PowerShell

### What skills do you bring to this working group?

Background knowledge of many years in the community and using PowerShell

### Public links to articles, code, or other resources that demonstrate your skills.

https://blog.kilasuit.org
https://github.com/kilasuit

**Comment by SteveL-MSFT** [comment]
@kilasuit, the @PowerShell/wg-powershell-cmdlets discussed this and we would welcome more diversity to our WG.  I'll reach out to you on specifics to join our next meeting.
