### ISSUE TITLE
Add the ability to redirect the same stream to multiple files

### ISSUE THREAD

**Issue by amoorcroft-nortech** [PowerShell/PowerShell#21381]
### Summary of the new feature / enhancement

We'd like the ability to redirect the same stream to multiple files, splitting warnings, errors, while still sending all streams * (inc. warning and error stream) to a combined file.

The background behind the question is a PS build script we'd like to capture output for (which writes to several streams). We'd like to turn the captured output into several files, with everything.log containing all possible output to provide context for build errors/warnings, while the separate error.log and warning.log would provide a quick reference for emerging issues.

Some examples of things we've tried:
`.\Script.ps1 2> "warnings.log" 3> "errors.log" *> "everything.log"`
`.\Script.ps1 *>&1 | Tee-Object "everything.log" 2> "error.log" 3> "warning.log" `

I couldn't find any existing questions/documentation on this, hence I'm raising as a feature request.

Thanks in advance!

**Comment by rhubarb-geek-nz** [comment]
No need for new PowerShell feature, the functionality is there if you know how to use it

I have just written a 'Super Tee-Object', [Invoke-PipelineBroadcast](https://github.com/rhubarb-geek-nz/PipelineBroadcast) which will send the contents of a single pipeline to multiple parallel script blocks.

Basically, write a script block for each output you want to capture. the [Invoke-PipelineBroadcast](https://github.com/rhubarb-geek-nz/PipelineBroadcast/blob/main/Modules/rhubarb-geek-nz.PipelineBroadcast/1.0.0/PipelineBroadcast.psm1) will write to each script using a steppable pipeline for each.

Example code

```
Invoke-Command -ScriptBlock {
	Write-Output 'write to the output'
	Write-Error 'write to error' 2>&1
	Write-Information 'write information'
	Write-Verbose 'write verbose information to the pipeline with a unique record type in order to identify it and filter'
	Write-Warning 'this is your final warning'
} *>&1 | Invoke-PipelineBroadcast -ScriptBlock (
	{
		Write-Output > stdout.log
	},{
		Where-Object { $_ -is [System.Management.Automation.ErrorRecord] } *> stderr.log
	},{
		Where-Object { $_ -is [System.Management.Automation.InformationRecord] } *> information.log
	},{
		Where-Object { $_ -is [System.Management.Automation.WarningRecord] } *> warning.log
	},{
		Where-Object { $_ -is [System.Management.Automation.VerboseRecord] } *> verbose.log 
	}
) -ArgumentList ((0),(0),(0),(0),(0))
```

The pipelines will all run until the original pipeline is closed.

**Comment by rhubarb-geek-nz** [comment]
I have a question regarding the error output....

In the above example, if I remove the `2>&1` from the `Write-Error` line then the error output disappears completely.

Where does it go?

The "*>&1" for the `Invoke-Command` does not seem to capture it to send to `Invoke-PipelineBroadcast`, otherwise it would appear in the stdout.log which shows everything.

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this today, while we see merit in the idea we think the additional complexity in the implementation would not be worth the impact it would have. We suggest using workarounds like the one detailed above.
