### ISSUE TITLE
Opening a runspace leaks environment variable to hosting application and other runspaces

### ISSUE THREAD

**Issue by valainisgt** [PowerShell/PowerShell#21382]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When opening a runspace, environment variables will leak out to the hosting application. In addition, environment variables will leak to other runspaces that were previously opened.

1. Create an initial session state using `InitialSessionState.CreateDefault2`
2. Add an environment variable value to the initial session state (in my case `PSModulePath`) using `InitialSessionState.EnvironmentVariables.Add`
3. Create a runspace using said initial session state
4. Repeat steps 1 - 3 to create a second runspace (except this time use a different value for the `PSModulePath` environment variable)
5. Check what `PSModulePath` is currently in the hosting application (should not be what was set for either of the two runspaces)
6. Open the first runspace and run a PowerShell script
7. See that the hosting application has `PSModulePath` now set to what the first runspace set it to
8. Open the second runspace and run a PowerShell script
9. See that the hosting application has `PSModulePath` changed again
10. Run the following script against the first runspace: `return $env:PSModulePath`
11. See that the returned value from the script is whatever the second runspace's `PSModulePath` was supposed to be as set in step 4

I have forked this repository, created a new branch using the tag v7.4.1 as the starting point, and added a new xUnit c# test that demonstrates the behavior:

https://github.com/valainisgt/PowerShell/blob/runspace-leak/test/xUnit/csharp/test_PowerShellBug.cs

### Expected behavior

```console
For runspaces to not effect the hosting application's environment variables or other separate runspace environment variables.
```

### Actual behavior

```console
Opening a runspace will change the hosting application and any other open runspaces' environment variables.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1-1-g7ff9577a3b81077f4a7fe60221d0416cf3f41f86
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
@SeeminglyScience this does bring up a good point in that it might not be possible to adjust the default module lookup PATHs so something scoped to just a Runspace. Maybe that should be exposed in another way to achieve this like a normal var.

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience this does bring up a good point in that it might not be possible to adjust the default module lookup PATHs to something scoped to just a Runspace (unless there is another way I’m not aware off). Maybe that should be exposed in another way to achieve this like a normal var.

Yeah I don't think there is anything like that currently.

---

If anyone has a proposal for how that would should work feel free to open an issue detailing it
