### ISSUE TITLE
Uploading file via Invoke-RestMethod corrupts file

### ISSUE THREAD

**Issue by Binomimus** [PowerShell/PowerShell#21386]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When uploading a file to Citrix Sharefile via API the file somehow gets corrupted. I am uploading a 7-zip archive and the uploaded file is about 50% larger than the original and cannot be opened afterwards (e.g. source file is 180.930 bytes, uploaded file is 271.815 bytes). That issue does not appear when using PowerShell 7.3.5. It first appeared after upgrading to 7.4.1

### Example code

```powershell
$uploadUri = "###removed, see sharefile docs###"
$fileInfo = Get-Item $filepath
$fileBytes = [System.IO.File]::ReadAllBytes($fileInfo.FullName)
$fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetString($fileBytes);
$boundary = [System.Guid]::NewGuid().ToString(); 
$LF = "`r`n";
$bodyLines = (
    "--$boundary",
    "Content-Disposition: form-data; name=`"Filedata`"; filename=`"$($fileInfo.Name)`"",
    "Content-Type: application/octet-stream$LF",
    $fileEnc,
    "--$boundary--$LF" 
) -join $LF

$uploadResult = Invoke-RestMethod -Uri $uploadUri -Method Post -ContentType "multipart/form-data; boundary=$boundary" -Body $bodyLines
```

The URI for uploading is generated like described in the ShareFile API documentation. See "Upload file" here: https://api.sharefile.com/docs/resource?name=Items

### Expected behavior

```console
Uploaded file is same as original
```

### Actual behavior

```console
Uploaded file is larger and corrupted
```

### Error details

```console
There is no error. From PowerShell perspective everything seems to be fine...
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
A couple of questions, why use Invoke-RestMethod rather than Invoke-WebRequest ?

Why are you converting the byte data to string when you are saying in the content-type it is application/octet-stream? That looks like part of the corruption problem.

As an alternative using forms and PowerShell, this is an example of something I use locally

```
        $web = New-Object -Type 'System.Net.WebClient'

        try
        {
                $web.Headers["Authorization"] = "Basic whatevergoeshere"

                $response = $web.UploadFile('http://10.1.2.12:8080',$Path)
        }
        finally
        {
                $web.Dispose()
        }
```

**Comment by Binomimus** [comment]
Thank you very much @jborean93 !
At the time of writing the code I found an example for text files and was just happy that encoding ISO-8859-1 seemed to work for zip/7z files as well ... until now.  Not sure what changed in PowerShell 7.4.1 though.
The second filename seems not to cause any issues, so I am going to use your first solution. Way mor robust than building the body myself.

Thanks & greetings,
Binomimus

**Comment by Binomimus** [comment]
Thanks @rhubarb-geek-nz 
I think I initially tried it this way but that's not working. I just tested again and received:
"ERROR: upload.aspx: ID='b6eb197a-8969-42fd-a62a-8ade371b7708' No files were received!" as response

**Comment by ray-wn** [comment]
Add the charset since Powershell 7.4 encodes to UTF-8, you need -ContentType "multipart/form-data; boundary=$boundary;**charset=iso-8895-1**"

Worked for 1 of my issues.
