### ISSUE TITLE
Add function for changing "Let this app work in background" option for msix apps

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#21399]
### Summary of the new feature / enhancement

It would be a nice to have a function for changing this parameter, since I can't find a way to change this parameter from powershell.

![image](https://github.com/PowerShell/PowerShell/assets/5204968/81b2163a-cb8a-4b24-9b25-392deb399350)
![image](https://github.com/PowerShell/PowerShell/assets/5204968/ce54b3bf-a0e2-43f6-92f3-779a47aef21e)

**Comment by SeeminglyScience** [comment]
I think you mean as an option in the `AppX` module - the code for that is not in this repo (and maintained by a different team). You'd want to pass that along via the feedback hub (see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)).
