### ISSUE TITLE
Rename or rephrase "CreateShortcut" while checking shortcut/weblink properties.

### ISSUE THREAD

**Issue by NekoJonez** [PowerShell/PowerShell#21391]
### Summary of the new feature / enhancement

I'm writing a script for the students who leave the school I work for during the schoolyear. 
One of these things in the script is placing a shortcut to the website of our supplier. 
Now, I wrote in that script a check if nothing changed the URL and the icon. Yet, when you want to check the location of a weblink shortcut... You get this:

The variables of shortcutlocation and shortcuticon are filled earlier in the script. 

```
      $ShellShortcut = New-Object -ComObject WScript.Shell
      $ShortcutTest = $ShellShortcut.CreateShortcut($ShortcutLocation)

      if (($ShortcutTest.IconLocation -eq "") -OR ($ShortcutTest.IconLocation -ne $ShortcutIcon)) {
          $ShortcutTest.IconLocation = $ShortcutIcon
          $ShortcutTest.Save()
      }

```

What is tripping me up every time is "CreateShortcut". I'm not a native English speaker (yet I speak it extremely fluently) ... and I always read it as it creates a new shortcut and skips the checking part. 

What's even stranger is that if you do a "Get-Content $ShortcutLocation", you can see the URL in there just fine. 

I honestly think that this function should get another name OR more information in "Get-Content". Since, it might help with confusion.

**Comment by SeeminglyScience** [comment]
The COM object isn't something we can change, it's built into Windows. You'd need to use the Feedback Hub to request that (but changing the name would be a huge breaking change so it is not likely to be accepted)

`Get-Content` just reads the file as is, it doesn't do any processing of file formats. You would need a dedicated command to managed shortcuts. There might be one on the PowerShell gallery you could install
