### ISSUE TITLE
Invalid paths with final segment with 3 or more dots (...) are incorrectly detected as valid

### ISSUE THREAD

**Issue by DanSM-5** [PowerShell/PowerShell#21404]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Test-Path` and other cmdlets resolve 3 or more dots (`...`) as a base path without the dots. E.g. `C:\Users\...` becomes `C:\Users`. This in turn makes `Test-Path` to return `True` even though no file or directory with a 3 dot (or more dots) name exists.

This happens on Windows only. Linux and Macos powershell will correctly return `False` when a invalid path ending in `...` is tested.

### Expected behavior

```console
# If '...' or more dots are not a file or directory

PS> Test-Path '...'
False
PS> Test-Path '........'
False
PS> Test-Path 'C:\Users\foo\...' # For a valid foo user
False
PS> Test-Path 'C:\........'
False
PS> Test-Path -LiteralPath '  .... .. ... ' # Spaces at any place if only dots
False
PS> Test-Path -LiteralPath 'C:\...     ..  .  ' # Spaces in between and end if absolute path
False
```

### Actual behavior

```console
# If '...' or more dots are not a file or directory

PS> Test-Path '...'
True
PS> Test-Path '........'
True
PS> Test-Path 'C:\Users\foo\...' # For a valid foo user
True
PS> Test-Path 'C:\........'
True
PS> Test-Path -LiteralPath '  .... .. ...' # Spaces in between
True
PS> Test-Path -LiteralPath 'C:\...     ..  .  ' # Spaces in between and end if absolute path
True
```

### Error details

```console
- I have checked the documentation on [path syntax](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_path_syntax?view=powershell-7.4) and there is no indication that 3 or more dots (`...`) should have any meaning.
- Adding `-LiretalPath` doesn't change the output on Test-Path.
- You can add spaces and the path will still be marked as valid.
- Same version of powershell 7.4.1 in Linux and Macos do not show this behavior.
- It happens in powershell 5.1.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

https://github.com/PowerShell/PowerShell/assets/49035812/588898fb-97ed-4112-847d-848e98e5fea5

**Comment by mklement0** [comment]
It looks like PowerShell is only the messenger here, because the underlying .NET APIs behave the same way; e.g.:

```powershell
# -> $true; '...' is interpreted the same as '.'
[System.IO.DirectoryInfo]::new('...').Exists
```

This may be a nod to legacy file-system quirks, though, curiously, `dir ...` in `cmd.exe` more sensibly does _not_ work.

**Comment by DanSM-5** [comment]
I see, I attempted the same thing with `cmd.exe` and because it failed as I would expect, it made me think that this could be a powershell issue.

**Comment by MatejKafka** [comment]
This is standard Windows behavior – trailing dots are ignored by most Win32 APIs. See:
- https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html
- https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats
- https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions (end of `Naming conventions`)

**Comment by DanSM-5** [comment]
Got it, looks like there isn't anything to be done on powershell's side but a windows thing to keep in mind.
Thanks for the reference. I'll close the issue.
