### ISSUE TITLE
{Set,New}-Service: add functionality from `sc failure`

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#21400]
### Summary of the new feature / enhancement

Right now, you can't configure these recovery parameters (from `services.msc`) from {Set,New}-Service powershell functions:
![image](https://github.com/PowerShell/PowerShell/assets/5204968/055b85e6-0426-45e0-bfa4-9f263447d763)

Would be nice if this can be configured with {Set,New}-Service powershell functions.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.4
https://learn.microsoft.com/ru-ru/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc742019(v=ws.11)

**Comment by StevenBucher98** [comment]
A little more context would be helpful, I am not sure what GUI you are sharing is referring to. If you are asking for PowerShell functionality that the `sc` command provides, you can wrap the command using **https://github.com/PowerShell/Crescendo**. Otherwise I also suggest providing feedback here https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332

**Comment by soredake** [comment]
> I am not sure what GUI you are sharing is referring to

It's from `services.msc`.

**Comment by mklement0** [comment]
@StevenBucher98, please note that this feature request explicitly asks for enhancing the existing `Set-Service` and `New-Service` cmdlets, which are part of this repo.

Wrapping the external `sc.exe` utility would be an inferior substitute, and submitting feature requests via the Feedback Hub is only appropriate for code _not_ maintained in this repo, and

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this, although the `*-Service` cmdlets are part of PowerShell 7, there is no expectation that the Windows specific cmdlets are updated to match the Windows GUI capabilities.  It does appear that there are some solutions in powershellgallery.com that could be expanded to address this specific use case.  We would encourage the community to build a full feature rich module for managing Windows services and publish to the gallery.
