### ISSUE TITLE
 Set-AuthenticodeSignature breaks .psd1 file syntax by removing last line (closing brace)

### ISSUE THREAD

**Issue by tonymet** [PowerShell/PowerShell#21403]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce
**NOTE** See "Detailed Repro Case" below
example I/O: https://gist.github.com/tonymet/d5df33b6a5003e1281c458a2d58d2d43

1. Create Module Manfiest .psd1 LF-encoded-newlines with no newline at the end
2. Call Get-AuthenticodeSignature win-fonts.psd1

### Expected behavior

```console
1. StatusMessage = "signature Verified" 
2. Invoke-ScriptAnalyzer .\win-fonts.psd1 should pass. 
e.g.


❯ Get-AuthenticodeSignature Win-fonts.psd1

    Directory: C:\Users\tonymet\scripts\win-fonts

SignerCertificate                         Status                StatusMessage        Path
-----------------                         ------                -------------        ----
xxxxxxxxxxxxxxxxxxzxxxxxxxxxxxxxxxxxxxxx  Valid                 Signature verified.  Win-fonts.psd1   
```

 `Invoke-ScriptAnalyzer .\win-fonts.psd1  `
```


### Actual behavior

```console
Syntax is broken because last line has been removed. e.g. "MissingEndCurlyBrace" 
1. Invoke-ScriptAnalyzer reports MissingEndCurlyBrace

❯ Invoke-ScriptAnalyzer .\win-fonts.psd1

RuleName                            Severity     ScriptName Line  Message
--------                            --------     ---------- ----  -------
MissingEndCurlyBrace                ParseError 

syntax is broken because the last line is remove
```
```


### Error details

_No response_

### Environment data

```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Detailed Repro Case
```
> $cert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert |
∙     Select-Object -First 1
>  New-moduleManifest -File kaka-crlf.psd1
# remove newlines between } and #SIG
> notepad kaka-crlf.psd1
> dos2unix kaka-crlf.psd1 kaka-lf.psd1
> Set-AuthenticodeSignature -File .\kaka-lf.psd1 -Certificate $cert
❯ Invoke-ScriptAnalyzer .\kaka-lf.psd1

RuleName                            Severity     ScriptName Line  Message
--------                            --------     ---------- ----  -------
MissingEndCurlyBrace                ParseError   kaka-lf.psd1 9
```

```
 function dos2unix ($infile, $outfile) {
∙     (Get-Content -raw $infile) -replace "`r`n","`n" |
∙     Set-Content -nonewline $outfile
∙ }
```

**Comment by rhubarb-geek-nz** [comment]
Does "signtool.exe" from the Windows SDK do the same thing?

**Comment by jborean93** [comment]
Can you share what is the exact file before you signed it. The reproducer just states set `ModuleVersion` then `Get-AuthenticodeSignature` but it's a bit unclear on how/when you've signed it and the structure of the `psd1` was before it was signed, i.e. was there an end newline, no newline, etc.

**Comment by tonymet** [comment]
> Can you share what is the exact file before you signed it. 

https://www.powershellgallery.com/packages/win-fonts/0.0.4/Content/win-fonts.psd1

LF new lines encoded

**Comment by tonymet** [comment]
> Can you share what is the exact file before you signed it

here's a complete example with before, after & the script I sign with.

https://gist.github.com/tonymet/d5df33b6a5003e1281c458a2d58d2d43

**Comment by tonymet** [comment]
Here's a 100% repro ... 


## Steps
```
> $cert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert |
∙     Select-Object -First 1
>  New-moduleManifest -File kaka-crlf.psd1
# remove newlines between } and #SIG
> notepad kaka-crlf.psd1
> dos2unix kaka-crlf.psd1 kaka-lf.psd1
> Set-AuthenticodeSignature -File .\kaka-lf.psd1 -Certificate $cert
❯ Invoke-ScriptAnalyzer .\kaka-lf.psd1

RuleName                            Severity     ScriptName Line  Message
--------                            --------     ---------- ----  -------
MissingEndCurlyBrace                ParseError   kaka-lf.psd1 9
```
```
 function dos2unix ($infile, $outfile) {
∙     (Get-Content -raw $infile) -replace "`r`n","`n" |
∙     Set-Content -nonewline $outfile
∙ }
```

**Comment by jborean93** [comment]
I cannot replicate

```powershell
$certParams = @{
    CertStoreLocation = 'Cert:\CurrentUser\My'
    KeyUsage = 'DigitalSignature'
    Subject = 'CN=Test-SelfSigned'
    TextExtension = @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
    Type = 'Custom'
}
$cert = New-SelfSignedCertificate @certParams

# Create test psd1 files without the end newline after the }
[System.IO.File]::WriteAllText("test1.psd1", "{`r`nRootModule = 'foo.psm1'`r`n}")
[System.IO.File]::WriteAllText("test2.psd1", "{`nRootModule = 'foo.psm1'`n}")

Set-AuthenticodeSignature -FilePath test1.psd1 -Certificate $cert
Set-AuthenticodeSignature -FilePath test2.psd1 -Certificate $cert

Format-Hex test1.psd1 -Count 50

   Label: C:\Users\vagrant-domain\test1.psd1

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 7B 0D 0A 52 6F 6F 74 4D 6F 64 75 6C 65 20 3D 20 {��RootModule =
0000000000000010 27 66 6F 6F 2E 70 73 6D 31 27 0D 0A 7D 0D 0A 23 'foo.psm1'��}��#
0000000000000020 20 53 49 47 20 23 20 42 65 67 69 6E 20 73 69 67  SIG # Begin sig
0000000000000030 6E 61                                           na

Format-Hex test2.psd1 -Count 50

   Label: C:\Users\vagrant-domain\test2.psd1

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 7B 0A 52 6F 6F 74 4D 6F 64 75 6C 65 20 3D 20 27 {�RootModule = '
0000000000000010 66 6F 6F 2E 70 73 6D 31 27 0A 7D 0D 0A 23 20 53 foo.psm1'�}��# S
0000000000000020 49 47 20 23 20 42 65 67 69 6E 20 73 69 67 6E 61 IG # Begin signa
0000000000000030 74 75                                           tu
```

It is true that the file will append `\r\n` automatically at the end before the signature regardless of the line endings used but it doesn't strip out the last `}`. In your instructions you are saying remove newlines between } and `#SIG`, how is there a `#SIG` if this is a new manifest? Are you editing an existing file to change a value. What are the reasons why you are using `\n` and not `\r\n`.

Ultimately the code signing and editing of the file is done by code outside of PowerShell. There could very well be a bug in some handling, especially when you are trying to mix in newlines that aren't Windows newlines, but there isn't much that could be fixed here in this repo. From what I can see I cannot replicate the bug when signing a psd1 without an ending newline in either the `\r\n` or `\n` variant.

**Comment by tonymet** [comment]
thanks for all the help & guidance with this. 
> I cannot replicate

 It seems the issue is with signtool.exe so I'll see about filing a ticket with them. 

For now I'll convert to CRLF and add the spaces at the end as a workaround. 

>  What are the reasons why you are using \n and not \r\n

I do most of my work on WSL / linux VMs so i try to keep LF for consistency with version control.    I'll start using CRLF with windows tools now that I know it's causing some bugs. 

thanks for the guidance and help understanding the issue.  `Format-Hex` is a great tool i hadn't used before

**Comment by tonymet** [comment]
> how is there a #SIG if this a new manifest

I run `add-signature.ps1` (above) prior to deploy to add the signature to the scripts/modules.   You're right with CRLF this works ok.

**Comment by tonymet** [comment]
root cause seems to be in `signtool.exe` in windows sdk (see comment above) . Closing and will forward to that repo
