### ISSUE TITLE
Remove the "code was generated by a tool" comments should be removed from *.Generated.cs files under src/Microsoft.PowerShell.GraphicalHost

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#2141]
Some *.Generated.cs files under "src/Microsoft.PowerShell.GraphicalHost" has the comment "code was generated by a tool; do not edit it" in them. According to the SD history, it looks some of those files were hand-edited before, so the comment doesn't make sense anymore and should be removed.

**Comment by akkatracker** [comment]
How can we find out which ones have been hand-edited?

Here's a search through the repo - about 11 pages worth:
https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=code+was+generated

**Comment by daxian-dbw** [comment]
The history information is only available in our internal Source Depot. I believe this comment in all `.Generated.cs` files are outdated, I couldn't even find information about what *tool* was used back then to generate those files.
@daviwil: do you think it's OK to remove this comment from all `.Generated.cs` files under `src/Microsoft.PowerShell.GraphicalHost`?

**Comment by daviwil** [comment]
Yeah, I think it'd be safe to do that for the files in the GraphicalHost assembly.

**Comment by joeyaiello** [comment]
This is code cleanup work that's probably not necessary for 6.0.0.
