### ISSUE TITLE
powershell / azure module

### ISSUE THREAD

**Issue by sachinvgaikwad** [PowerShell/PowerShell#2142]
I have installed powershell on my Ubuntu system i tried to install Azure module it didn't work can you help me out with this

**Comment by vors** [comment]
Did you install **AzureRM.NetCore.Preview, AzureRM.Profile.NetCore.Preview and AzureRM.Resources.NetCore.Preview** as mentioned in 
https://github.com/PowerShell/PowerShell/tree/master/demos/Azure#prerequisites ?
