### ISSUE TITLE
Copy-UserInternationalSettingsToSystem

### ISSUE THREAD

**Issue by sydevinfra** [PowerShell/PowerShell#21435]
### Summary of the new feature / enhancement

Hello,

On Windows 11, the command  Copy-UserInternationalSettingsToSystem allows you to copy language settings (among other parameters). Would it be possible to have this command on Windows Server 2022?

Best regards

**Comment by mklement0** [comment]
At least judging by the [documentation](https://learn.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=windowsserver2022-ps), the command _should_ be available in Windows Server2022:  Note how the version-selector dropdown list at the top of the sidebar states "Windows 11 and Window Server 2022"

Taking a step back:

The [`International`](https://learn.microsoft.com/en-us/powershell/module/international/?view=windowsserver2022-ps`) module that `Copy-UserInternationalSettingsToSystem` is a part of isn't being maintained in this repo, so the standard advice applies (taken from the now _obsolete_ [PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage) repo, emphasis added):

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

**Comment by MartinGC94** [comment]
As an alternative, you can use this function to do the same thing:

```
function Copy-UserLocalizationOptions ([bool]$ToWelcomeScreen=$true, [bool]$ToNewUsers=$true)
{
$XmlToCopy=@"
<gs:GlobalizationServices xmlns:gs="urn:longhornGlobalizationUnattend">
    <gs:UserList>
        <gs:User UserID="Current" CopySettingsToDefaultUserAcct="$(([string]$ToWelcomeScreen).ToLower())" CopySettingsToSystemAcct="$(([string]$ToNewUsers).ToLower())"/> 
    </gs:UserList>
</gs:GlobalizationServices>
"@
    $FilePath="$env:TEMP\$((New-Guid).Guid).xml"
    Set-Content -Value $XmlToCopy -Path $FilePath -Force
    Start-Sleep -Seconds 1
    control.exe "intl.cpl,,/f:""$FilePath"""
    Start-Sleep -Seconds 1
    Remove-Item -Path $FilePath -Force
}
```

It's one of the first functions I wrote when learning PowerShell many years ago.
