### ISSUE TITLE
Prompt Scriptblock Reference Link is broken

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell#21440]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
PS C:\Users\JGrote> command prompt |% scriptblock

"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
# .Link
# https://go.microsoft.com/fwlink/?LinkID=225750
# .ExternalHelp System.Management.Automation.dll-help.xml

```
https://go.microsoft.com/fwlink/?LinkID=225750 is a dead link. Hardcoded here: https://github.com/PowerShell/PowerShell/blob/1a52a93345d00eab3bd16cab31c1f3fafcb803b6/src/System.Management.Automation/engine/InitialSessionState.cs#L4880

### Expected behavior

```console
See Above
```

### Actual behavior

```console
See Above
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22635
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by sdwheeler** [comment]
This link has been deleted. I will investigate whether we can get it recreated or if we have to create a new one. If we have to create a new one, then the link will be broken in all downlevel versions.

**Comment by sdwheeler** [comment]
@JustinGrote this is fixed now. Thanks for the report.
