### ISSUE TITLE
 Powershell crashing System.OutOfMemoryException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

### ISSUE THREAD

**Issue by rahulchaudharyofficial** [PowerShell/PowerShell#21443]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Go to android studio download link (My guess is it can reproducilble for any large data file) and copy download link
2. open powershell, use wget to download i.e. 
     wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.24/android-studio-2023.2.1.24-windows.zip
3. data transfer continue for few mins then finally throws exceptiion

### Expected behavior

```console
wget should download the file in current directory
```

### Actual behavior

```console
crashed with error
```

### Error details

```console
wget : Array dimensions exceeded supported range.
At line:1 char:1
+ wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.4239
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4239
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

<img width="841" alt="Screenshot 2024-04-06 221911" src="https://github.com/PowerShell/PowerShell/assets/1083982/1c82d83a-ac86-4989-974c-a803870d3c12">

**Comment by mklement0** [comment]
Generally, please note that this repository is not for reporting issues with _Windows PowerShell_ (the legacy, ships-with-Windows PowerShell edition with versions up to 5.1); to report Windows PowerShell issues as well as issues with Microsoft-authored modules that aren't maintained in this repository, use the [Feedback Hub application](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

---

However, it looks like the only problem is that you expected `wget` to refer to `wget.exe`, whereas in _Windows PowerShell_ `wget` is (unfortunately) a built-in alias of  PowerShell's `Invoke-WebRequest` cmdlet (this alias has been removed in PowerShell (Core)).

(The latter doesn't automatically save to a file - you need `-OutFile` for that; in its absence, the resulting in-memory operation ran into limits.)

To predictably target `wget.exe`, use its filename extension explicitly:

```powershell
wget.exe https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.24/android-studio-2023.2.1.24-windows.zip
```

If `wget.exe` isn't installed, you can use `curl.exe`, which now ships with Windows:

```powershell
curl.exe -LO https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.24/android-studio-2023.2.1.24-windows.zip
```
