### ISSUE TITLE
.md files generated with PlatyPS incorrectly include -ProgressAction parameter section.

### ISSUE THREAD

**Issue by yotsuda** [PowerShell/PowerShell#21445]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Update help .md files with PlatyPS with following for cmdlets created with c#.

```
$parameters = @{
    Path = "./md"
    RefreshModulePage = $true
    AlphabeticParamsOrder = $true
    UpdateInputOutput = $true
    ExcludeDontShow = $true
    LogPath = "./log"
    Encoding = [System.Text.Encoding]::UTF8
}
Update-MarkdownHelpModule @parameters
```

### Expected behavior

```console
The generated .md files should not include a section for `-ProgressAction` parameter since this is a common parameter.
```

### Actual behavior

```console
The generated .md files include an unnecessary section for the `-ProgressAction` parameter.

### -ProgressAction
{{ Fill ProgressAction Description }}


Type: ActionPreference
Parameter Sets: (All)
Aliases: proga

Required: False
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
The repo for platyPS is https://github.com/PowerShell/platyPS. That said, there's already an issue there. You can track it at PowerShell/platyPS#595.

**Comment by yotsuda** [comment]
@SeeminglyScience Oh! I am very sorry for mistakenly filing this in the wrong place. Thank you for pointing it out and for your guidance. Regards,
Yoshifumi
