### ISSUE TITLE
Why the  command  winget search Microsoft.PowerShell can not get the latest version(7.4.2) of powershell?

### ISSUE THREAD

**Issue by palp1tate** [PowerShell/PowerShell#21465]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

![image](https://github.com/PowerShell/PowerShell/assets/120303802/405ae260-c023-474c-b0fe-e2d39f03ded2)

### Expected behavior

```console
PS C:\Users\19393> winget search Microsoft.PowerShell
名称               ID                           版本    源
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.4.2.0 winget
PowerShell Preview Microsoft.PowerShell.Preview 7.5.0.2 winget
```

### Actual behavior

```console
PS C:\Users\19393> winget search Microsoft.PowerShell
名称               ID                           版本    源
---------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.4.1.0 winget
PowerShell Preview Microsoft.PowerShell.Preview 7.5.0.2 winget
```

### Environment data

```powershell
PS C:\Users\19393> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
As a rule in a week or two after release

**Comment by mlutsoucs** [comment]
> As a rule in a week or two after release

👍 As a rule of 2w annoying message on every terminal tab 😸
