### ISSUE TITLE
I don't understand. The existing logic is to not allow this method to be called multiple times from native code.

### ISSUE THREAD

**Issue by Moazzem-Hossain-pixel** [PowerShell/PowerShell#21464]
I don't understand. The existing logic is to not allow this method to be called multiple times from native code.

_Originally posted by @daxian-dbw in https://github.com/PowerShell/PowerShell/pull/21361#discussion_r1535892580_

**Comment by SeeminglyScience** [comment]
I'm guessing this was done by mistake. If not please open a new issue with the template filled out.
