### ISSUE TITLE
`ConciseView` error view mangles `ParseException` child classes with custom message

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#21469]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The implementation of ConciseView has special handling for rendering parser errors: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1223

However, the code assumes that anything with `CategoryInfo` equal to `ParserError` is a `ParseException` and assumes that the format of the error message exactly matches the `Message` property of a `ParseException`.

In my code, I'm parsing custom PowerShell data files and throwing an exception class inheriting from `ParseException`, with added source position metadata in the error message. This results in confusing error messages when the exception is rendered using ConciseView.

I would prefer if the special rendering was only triggered for `ParseException`, and not for subclasses.

### Expected behavior

```console
Import-Pog: At D:\_\Pog\data\manifests\VS Code\.template\pog.psd1:27 char:137
+ … hePath"\s*:\s*)"([a-z][A-Z]+)"', ("`$1" + (ConvertTo-Json $CachePath)
+                                                                        ~
Missing closing ')' in expression.
```

### Actual behavior

```console
# no context, very hard for callers to understand where does the syntax error come from
Import-Pog: Missing closing ')' in expression.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.2
PSEdition                      Core
GitCommitId                    7.5.0-preview.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
There was previously discussion on abstracting errors for module so it doesn't show internal details.  Seems like you have a valid case to bubble up the error and provide more details.  I think the question for the WG is how to enable this scenario.  For example, do we want to make it opt-in for modules (like adding a special TypeName that can be used by conciseview).

**Comment by sdwheeler** [comment]
The working group discussed this issue. We understand the scenario but there are other ways to resolve your problem.

The class `ParseException` is used for to display parse errors in PowerShell syntax. There are existing scenarios where folks inherit `ParseException` but still generate `ParseErrors` that PowerShell can display. We would recommend not inheriting `ParseException` if this is not the behavior you are looking for.
