### ISSUE TITLE
Can not upgrade via `winget upgrade`

### ISSUE THREAD

**Issue by WeihanLi** [PowerShell/PowerShell#21470]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

upgrade powershell to latest with `winget upgrade Microsoft.PowerShell`, same error whether use `powershell` or `cmd`

### Expected behavior

```console
Upgrade successfully
```

### Actual behavior

```console
failed with exception


An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072efd : unknown error
```

### Environment data

```powershell
PS C:\Users\weihan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/7604648/0ed29a53-339b-45df-9a06-6125a8ac051d)

**Comment by mklement0** [comment]
The error, [`0x80072EFD`](https://www.hresult.info/FACILITY_WIN32/0x80072EFD), suggests that you had no internet connection at the time you ran the comnand.

**Comment by WeihanLi** [comment]
I'm good to download from the url directly. Would it relate to the system proxy?

> The error, [`0x80072EFD`](https://www.hresult.info/FACILITY_WIN32/0x80072EFD), suggests that you had no internet connection at the time you ran the comnand.

**Comment by mklement0** [comment]
Possibly, yes. Another possible cause is that PowerShell as an application may be blacklisted by threat-mitigation software such as ThreatLocker.

**Comment by AbishekPonmudi** [comment]
It is probably a error occurred due the network related issue , or A firewall, proxy, or other network security settings may be blocking access to the URL.
