### ISSUE TITLE
Clearing gateway using powershell WMI does not function as expected

### ISSUE THREAD

**Issue by elksson** [PowerShell/PowerShell#21481]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using a powershell in admin mode, set the network adapter to static mode. 
I used address 192.168.180.30, Mask 255.255.255.0 and gateway 192.168.180.2
however it does not matter what ip address, gateway or mask is used as long as its a valid ip, gateway, and netmask combination. 

You will notice that the enable static function results in setting the ip address the static address as expected. 
The set gateways function also sets the gateway as expected. You can observe this in the printed route table, and ipconfig /all information. 

Per the wmi documentation setting the gateway to the same address used to call EnableStatic should result in the gateway being cleared. However as observed in the route print, and also ipconfig /all this actually results in the gateway being set to 0.0.0.0 which is not the expected behavior, it actually applies a "default route" instead of no route. 

As note this issue is also observed using c++ however I am not sure how to report this to the windows team, or the WMI Team at microsoft. 

$nic = Get-WmiObject Win32_NetworkAdapterConfiguration -filter "Index='3'"
$ip_address = Read-Host("What's the IP address? :")
$subnetMask = Read-Host("what's the subnet mask? :")
$gateway = Read-Host("what's the gateway? :")
$nic.EnableStatic($ip_address,$subnetmask)
$nic.SetGateways($gateway,1)
Start-Sleep -Seconds 5
route print
ipconfig /all
$nic.SetGateways($ip_address,1)
Start-Sleep -Seconds 5
route print
ipconfig /all

### Expected behavior

```console
The route should be cleared when SetGateways is called with the same IP address that was used to EnableStatic
```

### Actual behavior

```console
The route should default gateway is set to 0.0.0.0 when SetGateways is called which results in the incorrect routing table and a network that does not route traffic properly.
```

### Environment data

```powershell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.4170
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4170
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by IsaacTruss-CCCU** [comment]
Based off of the information provided, I can recommend you clear the existing gateway and then configure the gateway. I have provided an example bellow. I hope this helps :+1:

```ps1
# Clear any existing gateway
$nic.SetGateways($null)
Start-Sleep -Seconds 2

# Reconfigure the IP address and gateway as needed
$nic.EnableStatic($ip_address, $subnetMask)
$nic.SetGateways($gateway, 1)
```

**Comment by iSazonov** [comment]
The repo is only for PowerShell development. Please use MSFT support channels to get help.

**Comment by elksson** [comment]
@iSazonov There is not any clear mechanism to report this bug to the Windows API Team. Can you either give details on this process of how to report this bug or since it also effects powershelgl then this issue should be left open until the downstream issue is resolved. Since the behavior is also reproduced in this powershell module. See example above.
