### ISSUE TITLE
travis-ci on a fork fails

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#2148]
The command "(cd tools && ./download.sh)" failed and exited with 127 during 

Is there a write up on how to wire travis-ci to a fork? 

![image](https://cloud.githubusercontent.com/assets/67258/18147059/04e918a6-6fa1-11e6-833d-8122f90c61fa.png)

**Comment by vors** [comment]
Looks like it failed to download the .deb package. Could be for various reasons (i.e. non-authenticated calls to github API is limited). Can you re-trigger the build and see does it happen consistently or not?

**Comment by dfinke** [comment]
Yes, the 3rd re-trigger worked.
