### ISSUE TITLE
Powershell 7.1

### ISSUE THREAD

**Issue by mathias619** [PowerShell/PowerShell#21490]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have never measured below 18cm.

I have measured 18.2cm 

I have seen a firmer fuller pole past that of the 18.2cm, a little 

I haven’t measured while on alcohol for example 

### Expected behavior

```console
PS> 7 + .09
```

### Actual behavior

```console
PS> 7 + .17
```

### Error details

```console
PS> Behavior when all factors constant
```

### Environment data

```powershell
PS> Powershell 7.1
```

**Comment by SteveL-MSFT** [comment]
Inappropriate visual which I've deleted.
