### ISSUE TITLE
How can I disable PSAMSIMethodInvocationLogging

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#21491]
### Summary of the new feature / enhancement

As a user I do not want any logging or tracing of invocations of .NET methods either collected or passed to other components.

### Proposed technical implementation details (optional)

In order to comply with [How the Antimalware Scan Interface (AMSI) helps you defend against malware](https://learn.microsoft.com/en-us/windows/win32/amsi/how-amsi-helps) it should be restricted to those mechanisms that take an entire script or string and either execute it or create a script block.

It should not log every single method, passing private data to 2nd or 3rd party dlls.

It should at most scan the script itself, not the expanded variable values.

It should only deal with fileless threats.

It should not log/scan anything that comes from a script read from the file system - that is considered already trusted

Neither should it need to scan signed scripts, again that should already be trusted

**Comment by rhubarb-geek-nz** [comment]
For example, I have a very simple one line script calling nothing except PowerShell provided commands

```
$env:__PSDumpAMSILogContent='1'

$null = Get-ChildItem "$HOME\Downloads\*.exe" | ConvertTo-JSON -Depth 2
```

Run this script using a new pwsh.exe process so the environment variable is respected.

An example output is

```
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 2

=== Amsi notification report content ===
<System.Diagnostics.FileVersionInfo>.GetVersionInfo(<C:\Users\OnlyMe\Downloads\dotnet-sdk-8.0.100-win-arm64.exe>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.String>.Remove(<28>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.Diagnostics.FileVersionInfo>.GetVersionInfo(<C:\Users\OnlyMe\Downloads\dotnet-sdk-8.0.204-win-x64.exe>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.String>.Remove(<26>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.Diagnostics.FileVersionInfo>.GetVersionInfo(<C:\Users\OnlyMe\Downloads\MediaCreationTool22H2.exe>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.String>.Remove(<21>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.Diagnostics.FileVersionInfo>.GetVersionInfo(<C:\Users\OnlyMe\Downloads\MSTeamsSetup_c_l_.exe>)
=== Amsi notification report success: True ===

=== Amsi notification report content ===
<System.String>.Remove(<17>)
=== Amsi notification report success: True ===
```

Is it really necessary to send all this information to AMSI given I already have Windows Defender installed and it is scanning my system?

**Comment by SteveL-MSFT** [comment]
WG reviewed this and this logging is required on Windows to provide protection via Windows Defender (or possibly other AMSI compliant scanners).

**Comment by SteveL-MSFT** [comment]
In your first case, I believe the actual script block to be executed (meaning variable expansion) is sent to AMSI so you can't hide executable code within a variable.

in your second case, those reports appears to be due to the large script for the Concise ErrorView formatting.  So any script executed during formatting would also be sent to AMSI since 3rd parties can add their own scripts during formatting.

**Comment by rhubarb-geek-nz** [comment]
Scanning a script block should occur when it is created from a string, this is the equivalent of loading a script file.

Yes with this approach you can't hide executable code within a string, but there is nothing wrong with a script in a string if it is not being executed, it is just data. But then neither can you hide database credentials, or SSN or bank account details or any other information you may be legitimately processing.

So lets say you think this is an excellent idea, and you are welcome to think that. There is another audience that considers this a gross violation of the expectation of being able to write programs with privacy. I can only assume now that there is no data privacy within a PowerShell execution environment on Windows, so as a tool or scripting language it should not be used, say, basically for anything other than hello world.

**Comment by rhubarb-geek-nz** [comment]
https://github.com/PowerShell/PowerShell/issues/21536
