### ISSUE TITLE
Set-LocalGroup Description Limitation

### ISSUE THREAD

**Issue by jimmyca15** [PowerShell/PowerShell#2150]
The Set-LocalGroup command imposes a length maximum of 48 characters. If I use `net localgroup <groupname> /comment:"<Here is where I put my description>"` I can go far past 48 characters. This restriction seems unreasonable especially given that you cannot replicate the descriptions of builtin groups such as the local 'Administrators' group which has a description containing 75 characters.

Local Administrators description (75 chars)
Administrators have complete and unrestricted access to the computer/domain

**Comment by vors** [comment]
Indeed. @mirichmo may have some insights about this code and why it's written that way. Mike is on vacation so it could take some time to hear back from him.

Relevant code: https://github.com/PowerShell/PowerShell/blob/c531098f3be5c6f5e671a162e6c49751474609f6/src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/SetLocalGroupCommand.cs#L35

```csharp
        /// <summary>
        /// The following is the definition of the input parameter "Description".
        /// A descriptive comment (48 characters).
        /// </summary>
        [Parameter(Mandatory = true)]
        [ValidateNotNull]
        [ValidateLength(0, 48)]
        public string Description
        {
            get { return this.description;}
            set { this.description = value; }
        }
        private string description;
```

**Comment by mirichmo** [comment]
I verified that Win 7 accepts descriptions greater than 48 characters, so I'll remove the check and let the SAM API validate string length.

The check got added because of [out-of-date documentation](https://technet.microsoft.com/en-us/library/bb490706.aspx) on TechNet.
