### ISSUE TITLE
Add Cmdlets to Get and Remove EngineEvents

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#21513]
### Summary of the new feature / enhancement

As a user I want an easy way to Register, then Get, and the Remove engine events using builtin cmdlets

### Proposed technical implementation details (optional)

Add the following Cmdlets
Get-EngineEvent
Remove-EngineEvent

**Comment by jborean93** [comment]
What benefit do you see this having over `Get-Event`, `Remove-Event`, `Get-EventSubscriber`? While there is a dedicated `Register-EngineEvent` I believe you are meant to use the generic `*-Event` cmdlets to manage events that are subscribed from various providers. You can even publicly extend your own event source like I've done in [PSEtw](https://github.com/jborean93/PSEtw).

**Comment by jdhitsolutions** [comment]
Submitted to the cmdlet Working Group to review.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this, as the behavior already exists, we recommend updating the docs with some example when using `-Force`
