### ISSUE TITLE
Simplified syntax doesn't recognize static members.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#21514]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Note: 

* If this ends up being declared to be by design, [about_Simplified_Syntax](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Simplified_Syntax) should be amended to clarify that.

```powershell
(Add-Type @'
public class Foo
{
  public static string Bar(string s) { return s; }
}
'@ -PassThru)::new() | ForEach-Object Bar '1'
```

### Expected behavior

`1`

That is, the static `.Bar()` method should be called.

### Actual behavior

The following error occurs:

`Input name "Bar" cannot be resolved to a method.`

### Environment data

```powershell
PowerShell 7.5.0-preview.2
```

**Comment by jborean93** [comment]
While I agree the documentation in the about page and for the `-MemberName` parameter in `ForEach-Object` could be expanded to state this won't work for static methods it does look to be by design. You can't call static methods as a normal member and `Get-Member` doesn't even show it unless you explicitly opt into to showing static members of that type with `Get-Member -Static`.

```powershell
Add-Type @'
public class Foo
{
  public static string Bar(string s) { return s; }
}
'@

$f = [Foo]::new()
$f.Bar('a')  # Doesn't work
$f | Get-Member # Doesn't show Bar

$f | Get-Member -Static  # Does show
```

**Comment by mklement0** [comment]
@jborean93:

* It's true that when it comes to _direct_ method calls there's a necessary distinction - driven by _syntax_ requirements - between _instance_ member access (`.`) and _static_ member access (`::`), and it is true that this distinction is also reflected in the logic of [`Get-Member`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-member), which reports only _instance_ members by default, and requires `-Static` to alternatively report _static_ members.

* By contrast, with simplified syntax there is _no_ requirement to _syntactically_ distinguish between accessing instance and 
static members.

Therefore, there are two possible resolutions:

* Preferably (to me): Extend  simplified syntax to also support accessing _static_ members.

* Officially declare the current behavior to be by design, and amend the docs accordingly.

**Comment by jborean93** [comment]
Personally it makes sense for ForEach-Object to run on multiple instances in an array but not for a static method. Why would you be enumerating multiple instances to call a static method that has no correlation to that type.

Ultimately a question for the WG.

**Comment by mklement0** [comment]
You're right: 

I've been trying to come with real-world examples of when static member access may be useful with simplified syntax, and so far the only - not very compelling - examples I've come up with are the following:

```powershell
# Possibly should be the same as:
#   [regex] 'foo' | % { $_.GetType()::CacheSize }
[regex] 'foo' | % CacheSize

# Possibly should be the same as:
#   [regex] 'foo' | % { $_.GetType()::unescape('a\\b') }
[regex] 'foo' | % Unescape 'a\\b'
```

To put it differently: the suggested ability to access static members would only be useful for static _properties_ and for static _methods_ whose parameters are _unrelated to each input instance_.

Therefore - unless someone finds additional angles - I agree that amending the docs is sufficient.

**Comment by rhubarb-geek-nz** [comment]
While not using the simplified syntax it could be done with with reflection.

```
(Add-Type @'
public class Foo
{
  public static string Bar(string s) { return s; }
}
'@ -PassThru)::new() | ForEach-Object { $_.GetType().GetMethod('Bar',[System.Reflection.BindingFlags]'Static, Public').Invoke($null,[string[]](,'1')) }
```

**Comment by mklement0** [comment]
@rhubarb-geek-nz: no need for reflection: [`::`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#static-member-operator-) also works on expressions:

```powershell
(Add-Type @'
public class Foo
{
  public static string Bar(string s) { return s; }
}
'@ -PassThru)::new() | 
  ForEach-Object { $_.GetType()::Bar('1') }
```

**Comment by mklement0** [comment]
I appreciate all the feedback.

I've concluded that adding a note to the docs is sufficient, so I'm closing this.

See:

* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11047
* https://github.com/MicrosoftDocs/PowerShell-Docs/issues/11048
