### ISSUE TITLE
The silent installation option does not take effect

### ISSUE THREAD

**Issue by ichat001** [PowerShell/PowerShell#21524]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I use the following command line to install the latest version, but the option still gets added to the context menu.
ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=**0** ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL=**0**
```
msiexec.exe /package PowerShell-7.4.2-win-x64.msi /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=0 ADD_FILE_CONTEXT_MENU_RUNPOWERSHELL=0 ENABLE_PSREMOTING=0 REGISTER_MANIFEST=1 USE_MU=0 ENABLE_MU=0 ADD_PATH=1
```

### Expected behavior

```console
no
```

### Actual behavior

```console
no
```

### Error details

```console
no
```

### Environment data

```powershell
7.4.2
```

**Comment by krzydoug** [comment]
If I only read the expected and actual behavior sections, it appears it's working as you desire.

**Comment by StevenBucher98** [comment]
@krzydoug can you please add more details expected and actual behavior sections? It is unclear which ones are not getting set and if you are expecting a silent install or if the settings are not getting set via CLI command you provide
