### ISSUE TITLE
`-LiteralPath` still interprets `~`

### ISSUE THREAD

**Issue by Hashbrown777** [PowerShell/PowerShell#21555]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I [personally] think `LiteralPath` should not be interpreting any special characters.
However, if understandably this cannot be helped at this stage, tilde should be mentioned in the documentation.
`'./~'` can be used to rectify this if possible within your script, but it erodes trust in what else PowerShell is doing.
The example uses `cd`, but this affects everything (`Get-Item`, `Remove-Item`, et cetera).

### Expected behavior

```console
PS> $PWD.Path
/home/hashbrown
PS> New-Item -Type Directory -Name '~' >$NULL
PS> cd -LiteralPath '~'
PS> $PWD.Path
/home/hashbrown/~
```

### Actual behavior

```console
PS> $PWD.Path
/home/hashbrown
PS> New-Item -Type Directory -Name '~' >$NULL
PS> cd -LiteralPath '~'
PS> $PWD.Path
/home/hashbrown
```

### Error details

```console
-LiteralPath
Specifies the path to be resolved.
The value of the LiteralPath parameter is used exactly as typed.
No characters are interpreted as wildcard characters.
If the path includes escape characters, enclose it in single quotation marks (').
Single quotation marks tell PowerShell not to interpret any characters as escape sequences.

(from https://learn.microsoft.com/en-us/powershell/module/*/*?view=powershell-7.4#-literalpath)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Fedora Remix for WSL
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
I agree that the docs should be amended to clarify that the literal aspect of the `-LiteralPath` parameter only relates to not treating its arguments as a _wildcard_ pattern, not also to not interpreting an argument-initial `~` (either standalone or if followed by `\` or `//`) as the home location of the provider underlying the current location (which is interpreted as such irrespective of whether you use `-LiteralPath` or `-Path`). 

(I don't think that changing the current behavior to also treat `~` literally would be considered acceptable, as it is likely to break existing scripts.)

Note that, unlike in POSIX-compatible shells:

* Neither interpretation (wildcard patterns, `~`) is a _shell_ expansion, i.e. the interpretation is not performed by PowerShell itself in a command-agnostic fashion; instead, the interpretation is provided by the targeted [provider](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Providers).

* As such, whether  a `-LiteralPath` or `-Path` argument is _quoted_ or not is irrelevant.

**Comment by Hashbrown777** [comment]
@mklement0 that's interesting that it's not powershell doing it.. but the same systems using the other 'native' CLI do not have this issue (id est it is the shell expanding `~`)
![image](https://github.com/PowerShell/PowerShell/assets/6907206/8428711a-f579-4042-988e-f624a005cf7f)
If the [.net] provider cannot be amended, and the cmdlets wont be changed to escape `~` before handing over to it (to bring it in line with other shells..), it absolutely must be in all documentation (as it functions counter to non-pwsh expectations)

**Comment by rhubarb-geek-nz** [comment]
> @mklement0 that's interesting that it's not powershell doing it

I think it is PowerShell doing it because there is nobody else doing it, the operating system does not do it. What I think @mklement0 is saying is it is not the command line variable expansion doing it, it is the PowerShell file system provider almost treating ~ as a logical drive.

**Comment by Hashbrown777** [comment]
I took it to mean it's .NET doing it, as pwsh would be using it to provide filesystem access, and the other CLI not utilising .NET is why 'nobody else is doing it'. But I could be wrong, I'd have to write some C# or something to check.

**Comment by rhubarb-geek-nz** [comment]
> I'd have to write some C# or something to check.

[PSCmdlet.GetUnresolvedProviderPathFromPSPath](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.pscmdlet.getunresolvedproviderpathfrompspath?view=powershellsdk-7.4.0) does this translation, in my test case from "~/.ssh/known_hosts" to "C:\Users\rhubarb\.ssh\known_hosts".

Typically you use GetResolvedProviderPathFromPSPath for -Path and GetUnresolvedProviderPathFromPSPath for -LiteralPath.

**Comment by StevenBucher98** [comment]
I suggest making a doc issue to clarify the use of `-LiteralPath` ,https://github.com/MicrosoftDocs/PowerShell-Docs. (cc @sdwheeler). I will leave it up to working group to decide how to approach this, feels like a pretty niche case but definitely sympathize with the confusing messaging with "literal path"

**Comment by sdwheeler** [comment]
I'm not sure that this is unique to `-LiteralPath`. The workaround for the OP is to qualify the path.

```
/home/sdwheeler> $pwd

Path
----
/home/sdwheeler

/home/sdwheeler> New-Item -Type Directory -name ~

    Directory: /home/sdwheeler

UnixMode         User Group         LastWriteTime         Size Name
--------         ---- -----         -------------         ---- ----
drwxr-xr-x  sdwheeler sdwheeler  05/06/2024 13:37         4096 ~

/home/sdwheeler> cd ~
/home/sdwheeler> cd ./~

Path
----
/home/sdwheeler/~
```

**Comment by mklement0** [comment]
Yes, the interpretation of a stand-alone `~` as a path or a `~/`-prefixed path as `~` referring to the provider's home location  is unrelated to the `-LiteralPath` / `-Path` distinction,
but the point is that it's reasonable to assume that if you use `-LiteralPath` that `~` _too_ will be treated literally, so adding a note to the docs would be helpful.

Incidentally, that `~` in `New-Item -Type Directory -Name ~` is _not_ resolved to the home directory should be considered a bug. By contrast, in `New-Item -Type File ~/foo.txt` it is, as expected.

**Comment by sdwheeler** [comment]
The docs have been updated.

**Comment by SteveL-MSFT** [comment]
Resolving as the current code behavior would be a breaking change and I do think some folks would be surprised if `~` didn't go home even for `-literalpath`.
