### ISSUE TITLE
`$PSScriptRoot` unpopulated when script missing the `.ps1` file extension

### ISSUE THREAD

**Issue by Hashbrown777** [PowerShell/PowerShell#21554]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Create a script utilising `$PSScriptRoot`, running via crunchbang instead of file association.

### Expected behavior

```console
PS> $pwd.Path
/home/hashbrown
PS> gc testScript
#!/bin/pwsh
$PSScriptRoot
PS> ./testScript
/home/hashbrown
PS>
```

### Actual behavior

```console
PS> $pwd.Path
/home/hashbrown
PS> gc testScript
#!/bin/pwsh
$PSScriptRoot
PS> ./testScript

PS>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Fedora Remix for WSL
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/6907206/1f838c74-e0c3-4ee9-92f8-42182ed0f453)

**Comment by Hashbrown777** [comment]
> Is this a duplicate of #21402 ?
![image](https://github.com/PowerShell/PowerShell/assets/6907206/cae94bd7-1d05-412c-8078-c4c29f898bf9)

Looks like it.

![image](https://github.com/PowerShell/PowerShell/assets/6907206/9a92b802-11b0-433c-ad54-5cbcf9618323)
They need to update the title with the real cause of the issue; the calling name (`$args[0]` in other languages, eg `$0` in bash) is missing the `.ps1` is the cause.
Seems it's not so much the name of the actual script itself.
Keeping it "Symbolic links can change..." is impossible to search if you're closer to the real problem à la "...script missing .ps1 extension".

To add; I think what's really responsible is that `$MyInvocation` has `.MyCommand` listed as the whole script as a raw string, instead of the script as a file, when the extension is missing.
If `MyCommand` isn't a file it cannot have a path.
![image](https://github.com/PowerShell/PowerShell/assets/6907206/1445b3eb-b93f-4ddf-ab0e-529be8ae6bb9)

**Comment by Hashbrown777** [comment]
> Dup #4217

Can't dupe a closed-due-to-inactivity issue.

"if this is a bug please try to reproduce on the latest version of PowerShell and reopen a new issue and reference this issue if this is still a blocker for you"

**Comment by rhubarb-geek-nz** [comment]
#21402 did have a work around, creating a shell script without the extension adjacent to the powershell script with ps1

```
#!/bin/sh -e
exec pwsh -File "$0.ps1" "$@"
```

**Comment by rhubarb-geek-nz** [comment]
>  instead of pushing input&output streams through an intermediary

Just so you know, the exec means no fork occurs and pwsh replaces sh with the same process id, environment, file descriptors etc. There is no intermediate.

**Comment by Hashbrown777** [comment]
> #!/bin/sh -e

It's more bourne itself, I don't want to have to look up the intricacies of `$@` et cetera and any caveats involved with explicitly using pwsh's `-File`, even if it turns out there are none for either. It's much simpler to just rename the script for now.
