### ISSUE TITLE
Invoke-Command does not support -Startuptype AutomaticDelayedStart

### ISSUE THREAD

**Issue by Ryssk** [PowerShell/PowerShell#21557]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi, seems like an issue with using StartupType AutomaticDelayedStart on 7.4.1 while running Invoke-Command, checking the enum i only get the following options aswell. Is it due to running it inside a Scriptblock?

[enum]::GetNames([System.ServiceProcess.ServiceStartMode])
Boot
System
Automatic
Manual
Disabled

According to the FAQ it should be working: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-service?view=powershell-7.4#-startuptype

### Expected behavior

```console
$S = Get-Service -Name Telegraf
Invoke-Command -ComputerName remotepc -ScriptBlock { Set-Service -StartupType "AutomaticDelayedStart" -InputObject $S -Status Running }
```

### Actual behavior

```console
$S = Get-Service -Name Telegraf
Invoke-Command -ComputerName remotepc -ScriptBlock { Set-Service -StartupType "AutomaticDelayedStart" -InputObject $S -Status Running }

Set-Service: Cannot bind parameter 'StartupType'. Cannot convert value "AutomaticDelayedStart" to type "System.ServiceProcess.ServiceStartMode". Error: "Unable to match the identifier name AutomaticDelayedStart to a valid enumerator name. Specify one of the following enumerator names and try again:
Boot, System, Automatic, Manual, Disabled"
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
When you use `Invoke-Command` with `-ComputerName` it connects to a registered PSSessionConfiguration under a specific name. The default configuration is `Microsoft.PowerShell` which is the PSSession registered for Windows PowerShell 5.1. You can see this by running `Invoke-Command -ComputerName foo { $PSVersionTable.PSVersion }` and see it will be for 5.1 and not 7.4.1.

While `Set-Service` on Windows PowerShell 5.1 did have a `-StartupType` parameter the `AutomaticDelayedStart` was added in version in PowerShell 7.x. To use this startup type you'll either have to

+ Target the `PowerShell.7` configuration with the `-ConfigurationName` parameter on `Invoke-Command`
+ Use `sc.exe` to set the startup type to automatic delayed start

The `PowerShell.7` configuration will only exist on the remote host if you installed PowerShell 7 and registered the session configuration with `Enable-PSRemoting` on PowerShell 7. You can see what configurations are available by running as admin `Get-PSSessionConfiguration` in PowerShell 7 on the target host.
