### ISSUE TITLE
Update-Help Fails (and previos issue was closed on outdated and wrong fix)

### ISSUE THREAD

**Issue by eabase** [PowerShell/PowerShell#21608]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In the previously reported and detailed issue #17067, your developer prematurely closed the issue on by citing an old and outdated blog, that has nothing to do with the issue. 

Please reopen.

### Expected behavior

```console
That Developers doesn't prematurely close open issues on the wrong basis.
```

### Actual behavior

```console
none
```

### Environment data

```powershell
n/a
```

**Comment by 237dmitry** [comment]
Try `-Scope CurrentUser`

![ss](https://github.com/PowerShell/PowerShell/assets/78153320/1885b068-5401-45ae-bd42-c8c508e60c01)

**Comment by eabase** [comment]
This has nothing to do with the scope. Please read the linked thread.

**Comment by SteveL-MSFT** [comment]
cc @sdwheeler

**Comment by sdwheeler** [comment]
The previous issue was answered and closed with this comment https://github.com/PowerShell/PowerShell/issues/17067#issuecomment-1850901137.

Are you having a problem not answered by that comment?

**Comment by eabase** [comment]
@sdwheeler 

> Are you having a problem not answered by that comment?

Yes. This:

> The Windows modules are not maintained by the PowerShell team. To prevent the error, the module owners on the Windows team must fix the modules. For modules that ship in Windows, open a support case with Windows Support or send feedback via the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

The Feedback Hub is like black hole for issues that MS does not intend to do anything about. I have filed stuff there in the past and never had any response or feedback, ever. At the end of the day, we're just slightly more advanced regular users of your product, so when we file for issues, we kind of expect that MS will take care of it. In this sense, I think it is really you who should file the issue on that Hub and ensure it gets to the correct team for a planned solution. 

Second, I have no idea why someone thinks that it the right procedure to close open issues, when they have not been fixed, completed or otherwise dealt with, regardless the team who's responsible for the actual fix.
