### ISSUE TITLE
Set-Alias: Add ability for parameters of ResolvedCommand

### ISSUE THREAD

**Issue by 237dmitry** [PowerShell/PowerShell#21603]
### Summary of the new feature / enhancement

Not to write scripts, functions or install 3party modules.

For example:
```powershell
Set-Alias -Name ttymc -Value "mc -bS default"
Set-Alias -Name ttymc -Value mc -ArgumentList "-b -S default"
```
instead of:

```powershell
function Start-mcOnTTY
{
    [Alias('ttymc')]
    param ()

    if ($env:TERM -eq 'linux') { bash -c "mc -bS default" }
    else { bash -c mc }
}
```

Like in bash. `alias alias_name="Command --with-parameters"`

**Comment by mklement0** [comment]
```powershell
Set-Item Function:ttymc 'mc -bS default @args'
```

**Comment by kilasuit** [comment]
This I think is a similar enough request to #12962 that can close this as Resolution-Duplicate

**Comment by 237dmitry** [comment]
> this as Resolution-Duplicate

> Not to write scripts, functions or install 3party modules.

This is not resolution. Because function is not an alias. This is feature request and not looking for workaround.

**Comment by mklement0** [comment]
The linked duplicate explicitly asks for an alias-based solution.

**Comment by 237dmitry** [comment]
> The linked duplicate explicitly asks for an alias-based solution.

I couldn't find a solution there. Just a workaround with functions. I want to get rid of the alias functions because there is a list of natural aliases and a few other functions. In my opinion, this is generally not neat, but I like order when everything is in its place.. The only good thing is that aliases of functions are displayed with `Get-Alias` cmdlet.

If it duplicate https://github.com/PowerShell/PowerShell/issues/12962 then I will close this issue tomorrow.

**Comment by mklement0** [comment]
Generally speaking, @237dmitry:

It is _asking for the same thing / reporting the same problem_ that makes a preexisting issue a duplicate, not whether or not the thing that was asked for has since been implemented / a (satisfying) workaround has been posted.

As for a unified discovery mechanism for different command forms: that's what `Get-Command` is for.
