### ISSUE TITLE
Maximum function count limitation when initializing a new session

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2161]
When creating a new session that imports modules and defines new functions, the number of allowed functions is limited to the default maximum count (4096).  This count value is reflected by the $MaximumFunctionCount built-in variable which can be modified.  But this doesn't help much during session initialization unless you have the foresight to include in one module an entry that sets the $MaximumFunctionCount variable.

During runspace binding on session initialization the number of defined functions and variables should not be limited to the default value.  Instead the session maximum count variables should be adjusted to accommodate.

**Comment by HemantMahawar** [comment]
Fixed by #2363
