### ISSUE TITLE
New-LocalUser doesn't work in Power 7.3+ without importing Microsoft.Powershell.LocalAccounts

### ISSUE THREAD

**Issue by NekoJonez** [PowerShell/PowerShell#21645]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

``` 
try {
        $Secure_String_Pwd = ConvertTo-SecureString "GeheimWachtwoord" -AsPlainText -Force
        New-LocalUser -Name "Eigenaar" -Password $Secure_String_Pwd -FullName "Eigenaar" -Description "Lokale admingebruiker" -AccountNeverExpires | Out-Null

        try {
          Add-LocalGroupMember -Group "Administrators" -Member "Eigenaar"
        }
        catch {
          Write-Host "Er was een fout met het toevoegen van de 'Eigenaar' gebruikersaccount als beheerder. Stuur deze fout naar de ICT dienst als deze fout blijft aanhouden: $($_.Exception.Message)"
        }

        Write-Host "De eigenaar account is aangemaakt met wachtwoord: $($Global:Pwd_Shown). De gebruikernaam is .\Eigenaar."
      }
      catch {
        Write-Host "Er was een fout met het aanmaken van de 'Eigenaar' gebruikersaccount. Stuur deze fout naar de ICT dienst als deze fout blijft aanhouden: $($_.Exception.Message)"
      }
```
The above script fails to create the user account in PowerShell 7+, it works fine in PowerShell 5.3...

If I set this underneath the first try statement: 

        if ($PSVersionTable.PSVersion.Major -ge 7) {
          # Deze module zo inladen. Niet via "ModuleIfNeeded", want anders werkt het niet in Powershell 7.
          Import-Module Microsoft.PowerShell.LocalAccounts -UseWindowsPowerShell -SkipEditionCheck | Out-Null
        }

It works perfectly. So, I think something is going wrong.

### Expected behavior

```console
The user account is created.
```

### Actual behavior

```console
The useraccount isn't created.
```

### Error details

```console
Could not load type 'Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI' from assembly 'System.Management.Automation, Version=7.4.2.500, Culture=neutral, PublicKeyToken=*****'.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by theJasonHelmick** [comment]
Thank you @NekoJonez for reporting this issue.  In my testing, the module Microsoft.PowerShell.LocalAccounts did properly autoload by calling the cmdlets directly, however when in the above script, it fails as described.  7.4.2, Win 11.  There may be a missing module dependency Microsoft.PowerShell.Telemetry.Internal.TelemetryAPI. Will forward to the working group for review and investigation if needed.

**Comment by jbne** [comment]
This seems to be related to #18624

**Comment by theJasonHelmick** [comment]
Hi @iSazonov - I'm good with the above labels.  I wanted to check before re-closing the issue.
