### ISSUE TITLE
Remove unused commented-out code

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2171]
As part of #2058 and #2154 we discovered few places where we have a commented-out code.

I.e. https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.WSMan.Management/CredSSP.cs#L59

We should revisit this code and possible remove.

**Comment by vors** [comment]
Also, https://github.com/PowerShell/PowerShell/blob/7a89b33f8b0de97f592f65354ea435df7f163302/src/Microsoft.PowerShell.PackageManagement/Utility/HostApiExtensions.cs#L85 is not apparently used anywhere, including ISE (which is different codebase, but has internal visibility)

**Comment by joeyaiello** [comment]
More code cleanup not needed for 6.0.0.

**Comment by vpondala** [comment]
Can I work on this?

**Comment by vpondala** [comment]
Hi @mi-hol

Yes, I definitely did. The issue is #7935
<https://github.com/PowerShell/PowerShell/pull/7935>.

Thanks
Vijay
