### ISSUE TITLE
Figure out PSDesiredStateConfiguration.psm1

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2172]
This is a follow-up from #1590
## Context

Currently, we are using **PSDesiredStateConfiguration 1.0.0-alpha01 nuget package** to deliver `PSDesiredStateConfiguration.psm1` in the final package, so DSC Configuration -> mof compilation can work on Linux.

https://github.com/PowerShell/PowerShell/blob/48d87842b112bf6c42f1f295d3007e3a2ee39803/src/powershell-unix/project.json#L59

It's sub-optimal.

`PSDesiredStateConfiguration.psm1` is a huge file that contains dynamic keyword `Configuration` definition (that's what we need for compilation) but also DSC runtime code.
## Proposition

We can try to extract the code that is needed for `Configuration` compilation from `PSDesiredStateConfiguration.psm1` and replace nuget package by this separated, compilation-specific code.

cc @nitinbps @nanalakshmanan @johnkord

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and the work item is to decouple DSC from PSCore eventually

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this be closed now that `PSDesiredStateConfiguration` is in its own repo and shipped separately?
