### ISSUE TITLE
Pipes between native processes are too slow

### ISSUE THREAD

**Issue by jhclark** [PowerShell/PowerShell#2176]
Problem: Native (non-object) pipes between native processes are ~1000X faster versus PowerShell object pipes. This is especially problematic for us systems people who like to work on 500MB-5GB files routinely.

Proposed solution: Automatically detect 2 native processes (neither is a function nor commandlet), and use a direct system pipe.

Timings from my box:

1) Powershell object pipe

    PS> time { cat bigfile.txt | measure -line }
    Minutes           : 15
    Seconds           : 14
    TotalSeconds      : 914.4296154

2) Using cygwin utilities

    PS> time { FastPipe { C:\cygwin\bin\cat.exe bigfile.txt | c:\cygwin\bin\wc -l } }
    TotalSeconds      : 1.7950218

*FastPipe is a hack I wrote that stringifies the scriptblock and passes it to cmd.exe for its faster raw pipes. Perhaps this is the best solution for now?

**Comment by GeeLaw** [comment]
No. There is NOT pipes between native commands.

When invoking a native command, PowerShell runs the command, interprets the `stdout` of it and make it a typed output.

If you are sending an object to a native command, PowerShell outputs it into the `stdin` of that command.

With those two combined, if you do `native | native` on PowerShell, PowerShell will "help" you corrupt the `stdout` of the first native and of course, the `stdin` of the second native.

Use `Start-Process` or `System.Diagnostics.Process` to invoke native commands.

**Comment by jhclark** [comment]
I am aware that this is not the current implementation and that is what I would like changed.


The object in the middle model makes sense for functions and commandlets, but not native processes, both in terms of efficiency and possible data corruption.


If you believe this is a feature and not a deficiency, could you provide a concrete user case?


Get Outlook for Android






On Mon, Sep 5, 2016 at 12:07 AM -0700, "Gee Law" <notifications@github.com> wrote:












No. There is NOT pipes between native commands.



When invoking a native command, PowerShell runs the command, interprets the stdout of it and make it a typed output.



If you are sending an object to a native command, PowerShell outputs it into the stdin of that command.



With those two combined, if you do native | native on PowerShell, PowerShell will "help" you corrupt the stdout of the first native and of course, the stdin of the second native.



Use Start-Process or System.Diagnostics.Process to invoke native commands.

**Comment by GeeLaw** [comment]
I don't believe that this is a useful feature. There is already an issue addressing this. See #559. This issue is mostly a duplicate/sunset of that issue.

**Comment by jhclark** [comment]
I could go for better language than "this is not a useful feature" -- I'm quite certain that it is.

However, I do buy that it is a duplicate of #1908, which appears to be discussed in #559 now and actively worked on by @vors on the PowerShell team.

**Comment by GeeLaw** [comment]
I was digging the history today and found this. To set the record straight, re:

> I could go for better language than "this is not a useful feature" -- I'm quite certain that it is.

This seems to be in reply to (and disagreeing with) my:

> I don't believe that this is a useful feature.

It appears @jhclark forgot the context, because my reply was in reply to:

> If you believe this is a feature and not a deficiency, could you provide a concrete user case?

In the quotation above, "this" (in "this is a feature and not a deficiency") refers to the fact that PowerShell "helps" you corrupt data. In the first quotation, it reads to me that "this" ("it" in "that it is") is the hope that PowerShell doesn't corrupt data.

To reiterate: I don't think PowerShell corrupting data is a useful feature.
