### ISSUE TITLE
[feature-request] powershell ISE like GUI environment for the open source cross platform release of powershell

### ISSUE THREAD

**Issue by zaxebo1** [PowerShell/PowerShell#2177]
Even this sysadmin related website lists Ten reasons for using powrshell ISE(Integrated scripting environment) GUI than using powershell console.
https://4sysops.com/archives/10-reasons-for-using-powershell-ise-instead-of-the-powershell-console/

powershell ISE is available only on Windows. It will be godsend for sysadmins , if an opensource  "powershell ISE" is available cross platform

**Comment by rkeithhill** [comment]
This exists but it is not a port of ISE.  I seriously doubt that will happen as ISE is built on WPF and AFAIK there are no plans to port WPF/XAML.  However, there is a cross platform editor/debugger for PowerShell.  It is a combination of the [VSCode](https://github.com/microsoft/vscode) editor/debugger and the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode.

**Comment by zaxebo1** [comment]
i did not requested for port of powershell ISE itself , i requested for powershell ISE **like** GUI environment.
So, thanks for the pointer to Powershell extension of VSCode. I will try it.
Can i use VScode+powershell extension for directory traversal with autocompletitions etc too. I hope that it is as conducive as powershell ISE.

**Comment by rkeithhill** [comment]
There is terminal in VSCode. You have to configure it to default to PowerShell though.  See this [blog post](http://jdhitsolutions.com/blog/powershell/5078/configuring-the-vscode-powershell-terminal/) on how to configure VSCode to use PowerShell in the VSCode terminal window.  But there is not an equivalent of the command add-on yet.

**Comment by andschwa** [comment]
I believe that Visual Studio Code coupled with the PowerShell extension (which is compatible with PowerShell Core) is close enough to the requested "powershell ISE like GUI environment for the open source cross platform release of powershell" that we can close this (and also as @rkeithhill stated, ISE itself will not be ported to my knowledge).

Thanks for the idea @zaxebo1!

**Comment by MaximoTrinidad** [comment]
I was told that upcoming release in October or sometime soon, will have an interactive shell.
check post at:
https://github.com/PowerShell/vscode-powershell/issues/295

:)

**Comment by zaxebo1** [comment]
@MaximoTrinidad 
thanks for the great news! 
i hope they release it in flatpak format, so that i can effortlessly install it, even without admin rights
