### ISSUE TITLE
Listening to Windows RT events

### ISSUE THREAD

**Issue by MarkTiedemann** [PowerShell/PowerShell#2181]
I tried using Powershell to listen to the `Dismissed` event of a `ToastNotification` as follows:

``` powershell
$toast = [Windows.UI.Notifications.ToastNotification]::new( ... )
$notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier( ... )
$notifier.Show($toast)

Register-ObjectEvent -InputObject $toast -EventName Dismissed -Action { ... }
```

Running this code, however, fails with the following exception message: 
`Windows PowerShell cannot subscribe to Windows RT events.`

Therefore, I'd like to ask:
- Does a workaround exist to subscribe to Windows RT events from Powershell?
- Is there another way to query the current state or final result of a `ToastNotification` (i.e. whether it is `Activated`, `Dismissed`, or `Failed`) from Powershell? 

Any help is much appreciated.

**Comment by iSazonov** [comment]
We need to check with latest builds or simply close.

**Comment by citelao** [comment]
Any update on this in 2020? It's weird that I can do a ton of WinRT stuff, but then cannot register event handlers.

**Comment by iSazonov** [comment]
@citelao Do you test with latest PowerShell 7.0 build?

**Comment by iSazonov** [comment]
I found a workaround from @david-risney https://deletethis.net/dave/2016-06/WinRT+Toast+from+PowerShell

**Comment by Windos** [comment]
If you can get that working @iSazonov (or anyone out there) I'll send you a beer or something!

A lot of the APIs/References that uses have changed. I managed to compile and get it working on Windows 8 (maybe 8.1), but haven't been able to replicate on Windows 10 even after updating references etc. I even reached out to Dave at one point to see if he knew how to update it for Windows 10.

As for if it works on the current version, I test this in every Windows update and PowerShell release because I'm *very* invested in seeing this work. The answer today with Windows 10 1909 and PowerShell 7.1 is... no:

![image](https://user-images.githubusercontent.com/6955786/77963197-6e5adc80-7339-11ea-98d2-61d43b08a3b9.png)

**Comment by iSazonov** [comment]
@Windos Please share you test script.

**Comment by Windos** [comment]
@iSazonov sure thing: https://gist.github.com/Windos/78ed980d926c634d0acede61e44a29af

**Comment by iSazonov** [comment]
After reviewing this I see that PowerShell need a wrapper to process WinRT events.
I am not sure that it is stable area (API) to allow us to inject this in PowerShell engine. So best way to address the issue is to create a module in PowerShell Gallery.

Perhaps @rkeithhill could share thoughts.

@rjmholt @TylerLeonhardt  Perhaps it is useful for PowerShell related projects.

**Comment by iSazonov** [comment]
It seems .Net Core has a code for WinRT events. https://github.com/dotnet/runtime/blob/c9edf7e621350ae8171e1ae4461d4a9e2c74c092/src/libraries/System.Runtime.WindowsRuntime/src/System/Runtime/InteropServices/WindowsRuntime/MarshalingHelpers.cs#L199 I don't know whether we use it.

**Comment by Windos** [comment]
I wish I could be of more help actually writing a solution to this, my C# is both rusty and rudimentary ☹️

I can point to where the check for WinRT events in the PowerShell code base is though, in case that helps anyone: https://github.com/PowerShell/PowerShell/blob/b7cb335f03fe2992d0cbd61699de9d9aafa1d7c1/src/System.Management.Automation/engine/EventManager.cs#L675

**Comment by iSazonov** [comment]
It is block condition only for writing user friendly message. Really AddEventHandler() below does not support WinRT events.
If you want to get a progress you could open an issue-question in .Net Runtime repo about how work with WinRT events in .Net Core.

**Comment by JK-MS1** [comment]
issue is still present, no solution to use event with toast notification with Ps7

$XmlString = @"
<toast>
  <visual>
    <binding template="ToastGeneric">
      <text>Default Notification</text>
      <image src="C:\Windows\IdentityCRL\WLive48x48.png" placement="appLogoOverride" />
    </binding>
  </visual>
  <audio src="ms-winsoundevent:Notification.Default" />
</toast>
"@

$AppId = 'Microsoft.AutoGenerated.{A49227EA-5AF0-D494-A3F1-0918A278ED71}'

$null = [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime]
$null = [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime]

$ToastXml = [Windows.Data.Xml.Dom.XmlDocument]::new()

$ToastXml.LoadXml($XmlString)

$Toast = [Windows.UI.Notifications.ToastNotification]::new($ToastXml)

$Toast | Get-Member -MemberType Event

Register-ObjectEvent -InputObject $Toast -EventName Activated -Action {
    Out-File -FilePath C:\Temp\Event.txt -InputObject (Get-Date -Format 'o') -Append -Force
}

[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($AppId).Show($Toast)



PS C:\temp\1110> .\testtoast.ps1


   TypeName: Windows.UI.Notifications.ToastNotification

Name      MemberType Definition
----      ---------- ----------
Activated Event      Windows.Foundation.TypedEventHandler`2[Windows.UI.Notifications.ToastNotification,System.Object...
Dismissed Event      Windows.Foundation.TypedEventHandler`2[Windows.UI.Notifications.ToastNotification,Windows.UI.No...
Failed    Event      Windows.Foundation.TypedEventHandler`2[Windows.UI.Notifications.ToastNotification,Windows.UI.No...
Register-ObjectEvent : Windows PowerShell cannot subscribe to Windows RT events.
At C:\temp\1110\testtoast.ps1:26 char:1
+ Register-ObjectEvent -InputObject $Toast -EventName Activated -Action ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Windows.UI.Noti...astNotification:ToastNotification) [Register-Object
   Event], InvalidOperationException
    + FullyQualifiedErrorId : INVALID_REGISTRATION,Microsoft.PowerShell.Commands.RegisterObjectEventCommand

**Comment by tauseedzaman** [comment]
getting the same issue but seems like there is no proper solution for this yet.?
