### ISSUE TITLE
Tap Expansion not working in Linux Remote xrdp session

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2189]
Steps to reproduce
------------------
Install tightvncserver and xrdp on Linux
Set the according 2D session to use xfce4-session
On Windows OS, open remote session, and connect to the IP address of the Linux machine
On the remote session, open a terminal session.
Run powershell
type psver -> press TAB key
It won't complete to $PSVersionTable

You will need to type the whole word case-sensitive
$PSVersionTable

Expected behavior
-----------------
To autocomplete to $PSVersionTable

Actual behavior
---------------
It will not do anything.

![linux_xrdp_tabexp_2016-09-05_13-16-10](https://cloud.githubusercontent.com/assets/19892435/18254675/13eb3b06-736e-11e6-9851-2e6bb143fc01.jpg)

Environment data
----------------

Ubuntu 16.04.1 Desktop

> $PSVersionTable

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.9                                  
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

**Comment by SteveL-MSFT** [comment]
This is an issue with xfce configuration and not PowerShell.  Solution here:
https://ubuntuforums.org/showthread.php?t=1771058&page=2

**Comment by MaximoTrinidad** [comment]
This is Awesome!  

I'm guessing there will be issues like this that will end up making changes in Linux Desktop configuration. I will make changes and test again. 

Thanks!

**Comment by MaximoTrinidad** [comment]
Yes! Its working now.

I can RDP from Windows into Linux, Open a Terminal session, start PowerShell and now use Tab-Expansion to complete my commands.

Thanks again!

I guessed you can close this issue.
:)
