### ISSUE TITLE
JEA on Linux

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2198]
Need to investigate how to implement JEA (Just Enough Administratio) on Linux

**Comment by ArieHein** [comment]
General question: 
Why would a Linux sysadmin stop using BASH with remote commands and swap to a JEA endpoint ?

I mean on a windows machine, I can stop RDP, create a JEA endpoint, and give my NOC team a script to do a specific job using specific cmdlets that I pre-configured in the JEA endpoint. This way I closed the GUI way, didn't give them local admin to the box so they cant use the other methods to remotely run commands.

What's the equivalent in Linux world ? Wouldn't a SSH with BASH just override the JEAL ( JEA on Linux :)  )

**Comment by SteveL-MSFT** [comment]
Good question.  From my perspective, this backlog item isn't to copy JEA as it exists on Windows today to Linux, but to investigate scenarios that necessitated JEA and see how it applies to Linux and what experience makes sense on Linux (ideally updating the Windows experience if it makes sense to have it consistent).  A possible outcome is that existing Linux tools are fine and this is just a documentation thing.

**Comment by ArieHein** [comment]
Can you elevate a powershell script to act as if one used sudo root or similar ?
If I wanted my NOC to run a remote command on a Linux box and I didn't want to give them admin rights but the command itself necessitated higher permission, would PS be able to do it via JEA ?

**Comment by ArieHein** [comment]
Can you elevate a powershell script to act as if one used sudo root or similar ?
If I wanted my NOC to run a remote command on a Linux box and I didn't want to give them admin rights but the command itself necessitated higher permission, would PS be able to do it via JEA ?

What are the tools used today by Linux sysadminns to carry such a task of delegation ?

**Comment by ArieHein** [comment]
Can you elevate a powershell script to act as if one used sudo root or similar ?
If I wanted my NOC to run a remote command on a Linux box and I didn't want to give them admin rights but the command itself necessitated higher permission, would PS be able to do it via JEA ?

What are the tools used today by Linux sysadmins to carry such a task of delegation ?

**Comment by SteveL-MSFT** [comment]
Currently you can elevate the entire powershell session via sudo.  There is an existing issue to get sudo working within a PowerShell session https://github.com/PowerShell/PowerShell/issues/1527

**Comment by soroshsabz** [comment]
ITNOA

@SteveL-MSFT please reopen this issue

JEA in Linux is very important for all Appliance product that wants to use PowerShell as a main shell and run on Linux

related to https://github.com/PowerShell/PowerShell/discussions/26657
related to https://github.com/PowerShell/PowerShell/issues/20514
related to https://github.com/PowerShell/PowerShell/issues/20583
related to https://github.com/PowerShell/PowerShell/issues/4094


<blockquote><img src="https://opengraph.githubassets.com/0b86659fb23def095b120065b52dc291ed1910875d41d7d8c1afef8480d6285b/PowerShell/PowerShell/discussions/26657" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PowerShell/PowerShell/discussions/26657">JEA for Linux PowerShell · PowerShell PowerShell · Discussion #26657</a></strong></div><div>ITNOA Hi, I want to implement role based access control on pwsh in ubuntu server (I have multiple user and I want every user can Enter-PSSession with specific role, to access very restricted comman...</div></blockquote>
