### ISSUE TITLE
Help content for PowerShell module should be generated on GitHub

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#2215]
## Steps to reproduce

Right now, if a cmdlets is added to PowerShell on GitHub, we do not have a way to followup and write help content for for it. We should fix this by maintaining and publishing the help content for PowerShell built-in cmdlets on GitHub. 
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by vors** [comment]
cc @juanpablojofre @sankethka @jongeller who are working on it

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShell-Docs#754
