### ISSUE TITLE
Allow (some) method names that happen to be keywords

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2217]
This should work:

``` powershell
class MyClass {     
    [object] Filter() {
        return $null
    }
}
```

Copied from TFS task 1358992

Reminder to close this Connect bug if this work gets done: https://connect.microsoft.com/PowerShell/Feedback/Details/1709557

**Comment by msftrncs** [comment]
I wouldn't think PowerShell needs a special character.  I think PowerShell's general concept of context serves better.   Pretty much all the useful keywords have no other use in `class { }`.  Only `hidden` and `static` would truly be reserved.  Even `base` only has a very specific context it can be used in.
