### ISSUE TITLE
Workflow + PS defined types

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2222]
This is copied from TFS 1406196

> There are undoubtedly issues trying to use a class/enum defined in PowerShell from workflow.
> We need to investigate the issues, most likely add errors.

Note: workflows currently exists only in Desktop edition.

**Comment by SteveL-MSFT** [comment]
No investments planned for PSWorkflow.  Investments in PSLanguage to remove historical need for Workflow.
