### ISSUE TITLE
Support interface declaration using classes

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2223]
Copied from TFS task 150409

We should be able to write something along these lines

``` powershell
interface IFoo
{
  [string] foo();
}

class Foo : IFoo
{
  [string] foo() { return 'foo' }
}
```

**Comment by GeeLaw** [comment]
Also, explicit implementation.

**Comment by forensicsguy20012004** [comment]
I agree, this would be a great addition  to powershell

**Comment by SteveL-MSFT** [comment]
@daxian-dbw can help you out, but he's going to be attending PSConf.EU next week

cc @rjmholt

**Comment by rjmholt** [comment]
@IISResetMe I saw your lightning demo and went to your repo afterward. Really amazing work. Your interface DSL actually inspired me, both in how rich it was and since it means interfaces could be made definable in PowerShell without necessarily adding them as a universal language feature. With that said, more complicated things like inheritance might not be so straightforward and would probably need to be part of the parser.

There's a discussion of some of the class-specific stuff in #6418 as well.

But for settling on the syntax and general design, the best place to start might be with an [RFC](https://github.com/PowerShell/powershell-rfc/blob/master/RFC0000-RFC-Process.md), just to drive discussion on how interfaces should look and what features should be supported in PowerShell. Especially so that the PowerShell Committee can consider it.

**Comment by IISResetMe** [comment]
@SteveL-MSFT Cool, I'll be at PSConfEU as well, will try to catch up with @daxian-dbw!

@rjmholt Thank you for the kind words. I'll try to add support for inheritance to Legislator over the next week, but based on the MSIL generated by CSC for multiple inherited interfaces it looks quite trivial to add.

If we go for something like what @vors suggest here, interfaces (including inheritance) would require just a subset of the existing grammar already in place for classes, the only thing missing is basically the `interface` keyword itself 😃 

I'll try to write up an RFC in the coming weeks and submit it to the RFC repo!

**Comment by IISResetMe** [comment]
Thanks to a few pointers from @daxian-dbw last month I got unstuck again 🎉 

If anyone wants to check out a working implementation of parser support for `interface` declarations, I've pushed it here: https://github.com/IISResetMe/PowerShell/tree/feature/interfaces 

I still need to add a type compilation step for interfaces in `TypeOps`, already have a basic routine working just need to merge it into that branch, will try and add it during this week

**Comment by IISResetMe** [comment]
Here we go: https://github.com/IISResetMe/PowerShell/commit/156e010413cbae1c7f5d5aa36e5a8d7116544eed

Parser rules for interface members are still slightly buggy (`;` not recognized as statement terminator atm), but it at least produces correct interface types as can bee seen below 😄 

![image](https://user-images.githubusercontent.com/7413755/48620140-4adefe00-e99f-11e8-8988-2b6133bc650c.png)

Syntax in this implementation also doesn't support get/set control, but it's arguably of limited value unless we decide on whether class properties in PowerShell should behave like fields or actualy properties (at which point we need to generate getters and setters implicitly)

**Comment by vors** [comment]
> class properties in PowerShell should behave like fields or actualy properties (at which point we need to generate getters and setters implicitly)

We are doing it already

https://github.com/PowerShell/PowerShell/blob/dedddb6b59b8b01fadb4312bbddc7992a6cbbe0a/src/System.Management.Automation/engine/parser/PSType.cs#L605

**Comment by IISResetMe** [comment]
@vors I see, must be something else that trips up then, will keep digging

![image](https://user-images.githubusercontent.com/7413755/48659475-0fe9d280-ea52-11e8-842a-a9d5b539addc.png)

**Comment by ThomasNieto** [comment]
@IISResetMe are you still working on this? It would be nice to have interface definitions in PowerShell.

**Comment by IISResetMe** [comment]
@ThomasNieto no, I completely dropped the ball on this, but looks like @rjmholt and @daxian-dbw might pick it up in a near future, please see https://github.com/PowerShell/PowerShell-RFC/pull/152#issuecomment-594167624

**Comment by joeyaiello** [comment]
To be clear, @daxian-dbw and @rjmholt can *review* the implementation, but they don't currently have the time to take it and run it towards a production implementation. Are you still interested in taking it all the way to the finish line if that's the case?

**Comment by vexx32** [comment]
If necessary, I can pick up the remainder of the necessary work once y'all are done reviewing what's currently done.

I will probably need you to brief me on what's still left in the to-do pile, though, @IISResetMe 😁

**Comment by Xpyder** [comment]
I think this is the right place for this but not 100% sure so if it's not please point me in the right place to post

I'm trying to figure out how to implement [Composition Over Inheritance](https://www.makeuseof.com/tag/basic-programming-principles/#composition-over-inheritance) in my powershell scripts.

I think it would go like this:

Diagram for clarity:

![2021-01-20_17-32-32](https://user-images.githubusercontent.com/12039454/105268405-09ca7180-5b47-11eb-813e-4d233a1d5f26.png)


```
# Actions
interface Swims {
    [bool] Swim( [object]$config );
}

interface Lands {
    [bool] Land( $land_spot );
}

interface Flies : Lands {
    [bool] Fly( $destination );
}

# Animals
class Duck : Flies, Swims {
    Duck(){}
    
    [bool] Fly( $destination, $land_spot ){
        $this.Fly($destination);
        $this.Land($land_spot)
        return $true
    }

    [bool] Fly( $destination ){
        write-host "The duck flies to $($destination)"
        return $true
    }

    [bool] Land( $land_spot ){
        write-host "The duck lands at $($land_spot)"
        return $true
    }

    [bool] Swim(){
        write-host "The duck paddles it's flippers"
        return $true
    }
}

class Dove : Flies {
    [bool] Fly( $destination, $land_spot ){
        $this.Fly($destination);
        $this.Land($land_spot)
        return $true
    }

    [bool] Fly( $destination ){
        write-host "The dove flies to $($destination)"
        return $true
    }

    [bool] Land( $land_spot ){
        write-host "The dove lands at $($land_spot)"
        return $true
    }
}

$duck = [Duck]::New()
$dove = [Dove]::New()

function Fly-To([Flies]$flier, $destination){ return $flier.Fly($destination) }
function Swim-To([Swims]$swimmer, $destination){ return $swimmer.Swim($destination) }

## Should Work ##
Fly-To $duck "Minnesota"
Fly-To $dove "New York"
Swim-To $duck "Pier 15"


## Should Fail ##

# should error because $dove doesn't implement [Swims]
# or if Duck Typing then because it doesn't implement $_.Swim()
Swim-To $dove "Pier 21"
```

The net result being that I don't have to create different versions of Fly-To for Duck and Dove, but Swim-To gives a meaningful error when trying to make the Dove swim

I take it these aren't currently implemented (I can't find documentation for this anywhere) so I was going to submit a feature request but I think this ticket is a match for this pattern?  But let me know if it should be a separate issue

**Comment by vexx32** [comment]
Yeah, this more or less would allow for that pattern in full. 

From discussions with @IISResetMe as far as I recall, he had the features more or less ready to go, but there were some design decisions he felt shouldn't be made alone and he was trying to solicit feedback on his implementation as @joeyaiello mentioned above. 

I don't think that's gone anywhere thus far, though, as far as I can recall the implementation hasn't really had a good look that I'm aware of.

**Comment by ericfran** [comment]
No update on the capability to support : interface ?
