### ISSUE TITLE
Comment-based Help for classes

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2225]
This is copied from TFS task 3231226

**Comment by joeyaiello** [comment]
If anyone is interested in implementing this, I can dig out a spec I wrote for this a couple years back. Went through the whole review process and churned on a bunch of feedback, we ran out of time to implement it :)

**Comment by vors** [comment]
I think it would be good to put the spec here or in an RFC.

**Comment by joeyaiello** [comment]
Found it! It's actually for DSC resources as well: [PS Classes Help Model Design Review.pptx](https://github.com/PowerShell/PowerShell/files/567775/PS.Classes.Help.Model.Design.Review.pptx)

Shouldn't be too hard to RFC-ize, I just gotta take the time. Are you interested in implementing it? (i.e. cause then I'll actually do it right now)

**Comment by vors** [comment]
I think the prioritization would not allow me to work on that in the near future.
