### ISSUE TITLE
Get folder delimiter

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#2231]
Is there a better way to determine the folder delimiter than this?

```powershell
$delimiter = "\"
if($IsWindows -eq $false)
{
    $delimiter = '/'
}
```
Looking up the VolumeSeparatedByColon on the FileSystem provider seems clunky as well.

**Comment by vors** [comment]
`[System.IO.Path]::DirectorySeparatorChar`, but PowerShell is actually slash-agnostic and understands both on all systems.

https://github.com/PowerShell/PowerShell/issues/570

**Comment by thezim** [comment]
My use case was this.

```powershell
$folder = Convert-Path -Path .
$files = Get-ChildItem -Recurse -File -Exclude manifest.txt -Path $folder
$files | Get-FileHash |
    Select-Object -Property Algorithm, Hash, @{Name="RelativePath";Expression={$_.Path.Replace($folder, $null).TrimStart('\','/')}} |
    Format-Table -AutoSize | Out-String -Width ([int]::MaxValue) |
    Out-File -FilePath "$folder\manifest.txt"
```

Was trying not to have to trim both \ or / in the above. [System.IO.Path]::DirectorySeparatorChar will work well in this case.

Thanks

**Comment by vors** [comment]
@thezim thank you for sharing the use-case!
