### ISSUE TITLE
convertfrom-string bug on windows

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2236]
notice:
i have  already searched windows powershell bug report use 'ConvertFrom-String'.Did not find the same bug report.
https://windowsserver.uservoice.com/forums/301869-powershell

'PS C:>"Hello World" | ConvertFrom-String' is examples in the manual.
but the following command have bug.
## Steps to reproduce

``` powershell
"hello   0.1234" | ConvertFrom-String
"hello   -0.1234" | ConvertFrom-String
```
## Actual behavior

```
"hello 0.1234" | ConvertFrom-String

P1    P2
--    --
hello  0

"hello -0.1234" | ConvertFrom-String

P1    P2
--    --
hello  0
```
## Environment data

win:

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by guxu2004** [comment]
as this question, its important issue .pls asw asap

**Comment by vors** [comment]
cc @LeeHolmes 
The technology behind `ConvertFrom-String` is PROSE, MS Research project.
ConvertFrom-String is currently not part of this repo, see #726

**Comment by SteveL-MSFT** [comment]
@joeyaiello is following up with MSR

**Comment by iSazonov** [comment]
We could close the issue. We have #726.
