### ISSUE TITLE
Get-DscResource cannot list DSC resources

### ISSUE THREAD

**Issue by gutenxu** [PowerShell/PowerShell#2237]
## Steps to reproduce

Ubuntu 14.04:
Install DSC for linux. 
Invoke InstallModule.py to install nx_1.0.zip
Install PowerShell 6.0.0 alpha.9
Invoke PowerShell and execute Get-DscResources
## Expected behavior

Get the DSC resource list
## Actual behavior

Failure:
You cannot call a method on a null-valued expression. 
...
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by vors** [comment]
cc @nanalakshmanan 

Currently, DSC on Linux and PowerShell on Linux are not integrated.
We definitely need to look into it.

**Comment by gutenxu** [comment]
Can Get-DscResources work? If it can, how to put DSC resources?

**Comment by gaelcolas** [comment]
Given the changes of DSC and pwsh, this issue should be closed.
(pwsh Invoke-DscResource only supports powershell DSC Resources).
