### ISSUE TITLE
Add What's New in PowerShell 6 document

### ISSUE THREAD

**Issue by TimCurwick** [PowerShell/PowerShell#2253]
Please add a What's New in PowerShell 6 document. PowerShell on Linux is cool, but what other enhancements have been implemented?

**Comment by ealexjordan** [comment]
What do you see the benefit of this being over the changelog?

**Comment by RamblingCookieMonster** [comment]
[This repo](https://github.com/PowerShell/PowerShell-Docs/blob/staging/scripting/whats-new/What-s-New-in-Windows-PowerShell-50.md) might be a better fit?

That said, definitely agree, very helpful to have this info if the list has solidified yet.  If not, could include notation for, or simply exclude features that might not make the final cut, if that's something that ever happens.

Cheers!

**Comment by RamblingCookieMonster** [comment]
@ealexjordan - check out the link vs. changelog - if I'm assuming correctly, Tim's looking for _what's different between PowerShell 5(.1) and PowerShell 6, ideally with some highlighting of big points_, where the changelog might include small bug fixes, and version-to-version changes - both are certainly valuable though : )

Cheers!

**Comment by MaximoTrinidad** [comment]
Definitely a Changelog stays under GitHub.  Then, the change log could be included as part of the What's New In PowerShell 6.0 Documentation.  
:)

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShell-Docs#755
