### ISSUE TITLE
Implement Invoke-Item for .NET Core on Windows, Nano Server and IoT

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#2272]
## Steps to reproduce

To fix this issue, a possible solution is to wrap the call in cmd.exe “start...”; however, in order to figure out if the process fail to start, we need WaitForExit, then check the exit code, and extract the standard error.  This is a change on behavior between Full and CoreCLR PowerShell. The problem with this implementation is that PowerShell will be blocked until the process completes. Alternatively, if we decide to just ignore the error, then this behavior will also be incorrect since in PowerShell no error means the operation was successful. 
We should explore doing a PInvoke in Windows CoreCLR. This way, we can get the Marshal.GetLastWin32Error() if we fail to start the process. 

on Windows Core CLR
invoke-item path_to_file_or_exe 
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by adityapatwardhan** [comment]
@Francisco-Gamino. Please add the PSVersionTable information.

**Comment by daxian-dbw** [comment]
This issue covers the `Invoke-Item` part of the original issue #1325

**Comment by SteveL-MSFT** [comment]
This also needs to work on Linux so don't have just a Windows solution

**Comment by daxian-dbw** [comment]
`Invoke-Item` already works on Linux and Mac. On windows, `Invoke-Item` was enabled by adding support to `ShellExecuteEx` in powershell core via #3281
