### ISSUE TITLE
Implement Get-Uptime and present uniform system uptime statistics across platforms

### ISSUE THREAD

**Issue by snobu** [PowerShell/PowerShell#2277]
I feel it's high time to add a native `Get-Uptime` cmdlet and present uniform system uptime statistics across all supported platforms:

Example:
https://www.powershellgallery.com/packages/get-uptime/1.1/Content/get-uptime.ps1

Which returns:
`12:37:27 AM up 0 days, 4 hours, 26 minutes, 8 seconds`

We should also have a `-Seconds` parameter, in case people want to pipe this through and quickly parse a long.

**Comment by iSazonov** [comment]
Need to close the issue @PowerShellTeam
