### ISSUE TITLE
No digital signature for PowerShell_6.0.0.10-alpha.10-win10-x64.msi and one

### ISSUE THREAD

**Issue by KexyBiscuit** [PowerShell/PowerShell#2283]
Steps to reproduce
------------------
Download `PowerShell_6.0.0.10-alpha.10-win10-x64.msi` and `PowerShell_6.0.0.10-alpha.10-win81-x64.msi` from https://github.com/PowerShell/PowerShell/releases .

Expected behavior
-----------------
Each Has a digital signature from Microsoft Corporation.

Actual behavior
---------------
No digital signature available, But the SHA256 checksums match.

Environment data
----------------
N/A
<!-- provide the output of $PSVersionTable

```powershell
> $PSVersionTable

``` -->

**Comment by andschwa** [comment]
@daxian-dbw I guess this didn't get documented in the releasing notes; @raghushantha gets the packages signed by some internal Microsoft service.

**Comment by raghushantha** [comment]
The release page has been refreshed with Signed MSIs

**Comment by KexyBiscuit** [comment]
The alpha.10 MSIs have SHA1 signature only, but the alpha.9 ones have SHA256 only...

**Comment by daxian-dbw** [comment]
According to @raghushanth, he was only able to sign the packages with SHA1. He is on vacation this week, so hopefully he can comment on this Monday next week.
But one thing for sure is that we do have issues in our current releasing process. We will fix the issues and keep improving the process.
