### ISSUE TITLE
Referencing System.Management.Automation in .NET Core / VS Code

### ISSUE THREAD

**Issue by concentrateddon** [PowerShell/PowerShell#2284]
What's the correct way to reference System.Management.Automation? E.g., this snippet from project.json:

```
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
    "Microsoft.AspNetCore.Routing": "1.0.0",
    "System.Security.Cryptography.Algorithms": "4.2.0",
    "System.Management.Automation": "6.1.7601.17514"
  },
```

Works when you run **dotnet restore** in that it finds and claims to install the System.Management.Automation dependency (noting that .17515 isn't compatible with .NET Core). But you can't simply add a **using** in the code, or it says:

```
The type or namespace name 'Management' does not exist in the namespace 'System'
```

The intent here is to programmatically instantiate PowerShell in the code, but .NET Core is a bit restrictive in how it wants references handled...

**Comment by mirichmo** [comment]
This is a known issue for NuGet that we are trying to resolve. There are a number of rogue System.Management.Automation packages that external people have posted. Those packages are all "FullCLR" assemblies and are not compatible with PowerShell Core.

The current way to consume the PowerShell Core version of System.Management.Automation is to copy the technique used by this project. Our [nuget.config](https://github.com/PowerShell/PowerShell/blob/master/nuget.config) file points to the correct version that is posted to MyGet. [powershell-win-core\project.json](https://github.com/PowerShell/PowerShell/blob/master/src/powershell-win-core/project.json) shows how to consume it within your project.json.

**Comment by vors** [comment]
Hi Don.

There are few things about `dotnet` cli that may help you sort it out.

* If you don't specify nuget feeds explicitly with `nuget.config` it will use https://www.nuget.org
  PowerShell Team didn't published SMA there, but somebody did a long time ago (as @mirichmo said) https://www.nuget.org/packages?q=System.Management.Automation
* You current setup consumes this package from nuget. You can make it consume your local SMA copy from GAC, if you build for FullCLR, but you would need to include reference under `frameworks / net451 / frameworkAssemblies`, like here https://github.com/PowerShell/PowerShell/blob/dd2394b1e6088f6c82054f5cae5520e532010fd4/src/System.Management.Automation/project.json#L188
* There are different `dependencies` sections in `project.json`: globabl and framework specific. You should use them appropriately.
* CoreCLR version of SMA will require additional massage on Initialization to register ALC (AssemblyLoadContext). For example, check our c# test runner: https://github.com/PowerShell/PowerShell/blob/master/test/csharp/fixture_AssemblyLoadContext.cs

**Comment by concentrateddon** [comment]
Perfect.
