### ISSUE TITLE
Add-AzureRmAccount : A parameter cannot be found that matches parameter name 'Credential'

### ISSUE THREAD

**Issue by jennyhunter-msft** [PowerShell/PowerShell#2288]
## Steps to reproduce

Run Add-AzureRmAccount with the credential parameter. Also repeatable with Login-AzureRmAccount
e.g. Add-AzureRmAccount -Credential $Credential -Tenant 'xxxx-xxxx-xxxx-xxxx' -ServicePrincipal
## Expected behavior

```
Add-AzureRmAccount -Credential $credential -TenantId $tenant -ServicePrincipal

Environment           : AzureCloud
Account               :  xxxxx-xxxxx-xxxx-xxxx
TenantId              : xxxxx-xxxxx-xxxx-xxxx
SubscriptionId        : xxxxx-xxxxx-xxxx-xxxx
SubscriptionName      : Subscription Name
CurrentStorageAccount : 

```
## Actual behavior

```
Add-AzureRmAccount : A parameter cannot be found that matches parameter name 'Credential'.
At ./Azure-Demo.ps1:22 char:20
+ Add-AzureRmAccount -Credential $credential -TenantId $tenant -Service ...
+                    ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-AzureRmAccount], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand
```
## Environment data

Ubuntu 14.0.4

```

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by dfaropennetwork** [comment]
I 've the same issue, i think that we need the azure module on our linux  powershell

**Comment by vors** [comment]
Did you use AzureRM.NetCore.Preview, AzureRM.Profile.NetCore.Preview and AzureRM.Resources.NetCore.Preview as described in https://github.com/PowerShell/PowerShell/tree/master/demos/Azure ? The regular [azure-powershell](https://github.com/Azure/azure-powershell) is FullCLR only currently.

**Comment by jhunter-msft** [comment]
Yes, I used the most recent AzureRM.NetCorePreview, and everything seemed to import properly. The command works without the credential parameter, but I need to use it in a script without interactions.

**Comment by HemantMahawar** [comment]
This issue was moved to Azure/azure-powershell#3174
