### ISSUE TITLE
Copy / Paste is inconsistant

### ISSUE THREAD

**Issue by t3dodson** [PowerShell/PowerShell#2294]
Steps to reproduce
------------------

In chrome on windows copy and paste is inconsistent it appears to be linked if there is special text inputs. Steps to reproduce are when copying from the url bar but I have found this behavior across many applications and use cases.

This behavior seems to go away if you copy and paste from the source to notepad and then copy from notepad and paste into powershell.

#### Chrome: 
    F6 -> right click -> Copy 
#### PowerShell: 
    Right Click Title Bar -> Edit -> Paste

#### Chrome: 
    F6 -> right click -> Copy 
#### Notepad.exe:
    Right click -> paste -> ctrl + A -> right click -> copy
#### PowerShell: 
    Right Click Title Bar -> Edit -> Paste

Expected behavior
-----------------
### **Scenario 1**
http://someurl.com
### **Scenario 2**
http://someurl.com

Actual behavior
---------------
**Scenario 1**
// nothing
**Scenario 2**
http://someurl.com

Environment data
----------------

```powershell
> $PSVersionTable | fl

```

Name  : PSVersion
Value : 4.0

Name  : WSManStackVersion
Value : 3.0

Name  : SerializationVersion
Value : 1.1.0.1

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : BuildVersion
Value : 6.3.9600.16406

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0}

Name  : PSRemotingProtocolVersion
Value : 2.2

---
Windows 7

**Comment by lzybkr** [comment]
I believe your scenario is related to `conhost` - the process that handles the pasting - and not PowerShell. I would expect you'll see the same thing in `cmd`.

Assuming this is the case, you could report the issue [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo), though I will note that I couldn't repro on Win10.

**Comment by Liturgist** [comment]
I also could not repro on Win10 using PowerShell v6.0.0-alpha.10.

**Comment by lzybkr** [comment]
OK - I'm closing the issue then. I do think it's not a PowerShell issue, so tagging it as external.
