### ISSUE TITLE
Get-Help -Online not working

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2297]
Steps to reproduce
------------------

Enter the command in PowerShell `Get-Help Get-Help -Online`

Expected behavior
-----------------

Web browser opens and help information about Get-Help appears.

Actual behavior
---------------

PS C:\Program Files\PowerShell\6.0.0.10> Get-Help Get-Help -Online
Get-Help : Operation is not supported on this platform.
At line:1 char:1
+ Get-Help Get-Help -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Help], PlatformNotSupportedException
    + FullyQualifiedErrorId : System.PlatformNotSupportedException,Microsoft.PowerShell.Commands.GetHelpCommand

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
CLRVersion
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.10
```

**Comment by andschwa** [comment]
Closing as duplicate of https://github.com/PowerShell/PowerShell/issues/1325. Please search for existing issues before opening new ones, per the [contributing guidelines](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#contributing-to-issues).

**Comment by Liturgist** [comment]
@andschwa - I did search and find #1325, but it did not seem to be limited to .NET core. I cannot use -Online on anything.

**Comment by andschwa** [comment]
The version you posted was PowerShell Core.

**Comment by Liturgist** [comment]
My apologies. I am trying to learn the ropes here.

**Comment by andschwa** [comment]
No worries! There are indeed a lot of versions, but rest assured this is due to the. NET Core port and is already in others to be fixed 😁
