### ISSUE TITLE
There is no about_Redirection

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2298]
## Steps to reproduce

Get-Help about_Redirection
## Expected behavior

Information about redirection in PowerShell appears.
## Actual behavior

PS C:\src\powershell> Get-Help about_Redirection
Get-Help : Get-Help could not find about_Redirection in a help file in this session. To download updated help topics type:
"Update-Help". To get help online, search for the help topic in the TechNet library at
https://go.microsoft.com/fwlink/?LinkID=107116.
At line:1 char:1
- Get-Help about_Redirection
- ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
  - FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand
## Environment data

``` powershell
Name                           Value
----                           -----
PSEdition                      Core
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.10
PSVersion                      6.0.0-alpha
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
CLRVersion
```

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShell-Docs#768
