### ISSUE TITLE
Bug - HOME env not set, error message is not clear on what the issue is

### ISSUE THREAD

**Issue by damon-atkins** [PowerShell/PowerShell#2299]
# HOME environment varable not set results in a error message which is hard to determine the actual fault.

If calling powershell from another tool,  HOME may not be part of the environment space. Powershell should report better error message.

Steps to reproduce
------------------
$ unset HOME
$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

The shell cannot be started. A failure occurred during initialization:
The type initializer for 'System.Management.Automation.ConfigPropertyAccessor' threw an exception.

Expected behavior
-----------------
$ unset HOME
$ powershell
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
Please set the HOME environment variable before using powershell, as powershell stores configuration items in $HOME/.configure/powershell

Actual behavior
---------------
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

The shell cannot be started. A failure occurred during initialization:
The type initializer for 'System.Management.Automation.ConfigPropertyAccessor' threw an exception.

Environment data
----------------
```
powershell '$PSVersionTable'

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.10
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment]
Same problem as #2205.

@mirichmo this is due to the ConfigPropertyAccessor requiring that HOME be both set and writable, but that's something that can be expected.

**Comment by andschwa** [comment]
I'm going to close as duplicate; but thank you for filing. This is indeed a bug.
