### ISSUE TITLE
Enhancement Request...Full Integration with Node.Js

### ISSUE THREAD

**Issue by forensicsguy20012004** [PowerShell/PowerShell#2302]
Is there a potential for full Powershell integration within the Node.JS environment? Now that MS is fully supporting Node.JS in the Azure space and has announced support for Node.JS in Windows Server 2016 Nano, will there be any attempts by the Powershell Community to openly endorse the Node.JS community? Currently for integration of Powershell into Node.JS I am utilizing [https://github.com/dfinke/edge-ps], however, I think a long-term solution would be for the Powershell Community to undertake a fully integrated solution, working both with the Node.JS Community via an NPM module and this community. Thank you.

Matt

**Comment by ArieHein** [comment]
Powershell is based on .net and as such anything supported (there are probably some unsupported stuff) in .net would have an equivalent way in powershell, you'll just have to reference the correct .net api.  I think powershell at its core shouldn't be tight to any framework, to be as agnostic as possible allowing the community to add things like Doug created.

**Comment by megamorf** [comment]
@forensicsguy20012004  What exactly do you understand as *full PowerShell integration within the Node.JS environment*?

**Comment by forensicsguy20012004** [comment]
Both of these are great questions...if nothing more thank you for taking the time to read the request. I agree that Powershell should not be linked to or tied to any system or framework...since Powershell now works on both Mac and Linux systems. My concept or thought of full integration into the Node.JS environment is merely a concept in which Microsoft (MS) takes a lead in integrating these two systems. Someone has done it [at least at the OS level] or else it [Node.JS] would not be a supported platform in Azure or in Windows Server 2016. Since Powershell is now OpenSource and the direction is away from monolith stacks, and scripting environments, I just thought that maybe this is something the Powershell Community would like to undertake. Potentially the Posh Communicy built an NPM module that supports Powershell. I was hoping we could spark a discussion among the Powershell Community and the Node.JS Community at MS. So, if you go to [https://github.com/Microsoft/nodejs-guidelines]; Microsoft Loves Node.JS...maybe this question or request is better asked on that project, but I wanted to give the Powershell Community first "crack" at joining the "love." If you and the community feel that this request should die that is fine. You can go ahead and make your final comments and close the issue if you like. Thank you for your time and energy.

**Comment by ArieHein** [comment]
Your views, ideas and interaction are of same value as ours. Were all 'users' of the technology seeking to improve it and make it easier for us to create and use :)

One of the areas I can see posh community helping, though this might be best done by MS, is actually a PowerShell wrapper class. If you look at all the long list of steps required to create a node.js app, either locally or in the cloud, all of it can be automated and wrapped in Node.ps (not a typo) wrapper with a simple DSL where you just supply the values as an object/array and the wrapper does all for you.

Some of this already exists in one way or another, like:
https://github.com/aaronpowell/ps-nvmw

There are also Node.js projects that interact with PowerShell, like:
https://github.com/bitsofinfo/powershell-command-executor-ui

**Comment by forensicsguy20012004** [comment]
You are correct about the wrapper part...I have found and I am using a DSC resource that does "roll" a Node.JS app...it is so easy that one might think it does not work...but it does. I like your idea of Node.ps that is a really cool idea. You are correct about other projects interacting with Powershell/Node.js. I was just wondering if this was a path that the Community would like to embrace, have an official "module" that is aligned with the Powershell Community Guidelines and Standards but could be an NPM module that hooks directly into Powershell. Like I said I love Doug's project/repo, but I just wanted to gauge the reaction if this is something the Community would like to undertake. If not that is cool and you can make final comment(s) and close. Once again I really appreciate you taking the time to read my request and ponder it.
