### ISSUE TITLE
Import-PowerShellDataFile Function missing documentation

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2303]
## Steps to reproduce

Get-Help Import-PowerShellDataFile -full

or

Get-Help Import-PowerShellDataFile -online
## Expected behavior

Expect documentation about the use of this function.
## Actual behavior

Provide a skeleton structure about this function but make no sense on how to use it.
The online link redirects  to another cmdlet information.

![importposhdatafile](https://cloud.githubusercontent.com/assets/19892435/18618196/822f4468-7daf-11e6-9a1c-8c6dd529fb18.png)
## Environment data

Linux - Ubuntu 16.04.1 64bit

``` powershell
> $PSVersionTable

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.10                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1



```

**Comment by megamorf** [comment]
Could you rename the issue title, it's a bit misleading as this is about *Import-PowerShellDataFile*.

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShell-Docs#769
