### ISSUE TITLE
Get-PSdrive disk information differs from Linux

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2304]
## Steps to reproduce

In PowerShell use cmdlet:  'Get-PSDrive'
and in Linux use 'df -h'.
## Expected behavior

I expect Get-PSDrive 'Used' column amount for the 'FileSystem' provider would be the same as Linux 'Used' column for sda6 drive.  
## Actual behavior

But, is not the same value.
Get-PSdrive - FileSystem shows 'Used' = 113.34GB
df -h - = Shows 'Used' with 66G
(See attached image)

![getpsdriveissue](https://cloud.githubusercontent.com/assets/19892435/18618282/33eb5628-7db1-11e6-859f-1b7e0b8e9157.png)
## Environment data

Linux: Ubuntu 16.04.1 64bit

``` powershell
> $PSVersionTable
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.10                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1  

```

**Comment by andschwa** [comment]
This repros for me on Ubuntu 16.04. The funny thing is that in both our tests, the "Free"/"Avail" amounts are the same.

/cc @JamesWTruher

**Comment by joeyaiello** [comment]
This must've been a bug in .NET Core, as it appears to be fixed now.
