### ISSUE TITLE
Github 'Get PowerShell' need a Build Date column 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2305]
This is just a suggestion.

I think it would helpful in GitHub to include a "Last Build Date" or "Last Version Date" in the "Get PowerShell" section for all different platform.

![getpowershellver_2016-09-19](https://cloud.githubusercontent.com/assets/19892435/18638504/67dcf9e8-7e5e-11e6-9209-51e4eefb9467.jpg)

**Comment by vors** [comment]
The date would always be the same for all the packages, so it probably doesn't worth to create a whole column for it.

**Comment by lzybkr** [comment]
I agree - the date of the release is easily found on the releases tab, along with other important release information.  It doesn't need to be front and center.
