### ISSUE TITLE
fwlink helpURI of Get-Uptime,Get-FileHash and others doesn't work

### ISSUE THREAD

**Issue by Ashc0d** [PowerShell/PowerShell#23069]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The helpURI forward link for `Get-Uptime` does not lead to its powershell documentation.
Last work done on `Get-Uptime` related to helpURI was in #2688.

I believe helpURI in these two following file needs to be updated to fix this issue after getting fwlink.

* PowerShell/test/powershell/engine/Help/assets/HelpURI/V3Cmdlets.csv

Inline:
https://github.com/PowerShell/PowerShell/blob/11a7448d7a03fb4d86618ab5783608127df2056d/test/powershell/engine/Help/assets/HelpURI/V3Cmdlets.csv?plain=1#L44

* PowerShell/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUptime.cs

Inline:
https://github.com/PowerShell/PowerShell/blob/11a7448d7a03fb4d86618ab5783608127df2056d/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUptime.cs#L14

### Expected behavior

```console
PS> Get-Help Get-Uptime -Online

Should open link: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-uptime?view=powershell-7.4
```

### Actual behavior

```console
PS> Get-Help Get-Uptime -Online

Open's link after redirection: https://www.bing.com/?ref=go&linkid=834862
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
cc @sdwheeler

**Comment by Ashc0d** [comment]
Found several another cmdlet that does not have correct fwlink helpURI:

Get-FileHash	https://go.microsoft.com/fwlink/?LinkId=517145

Get-LocalGroupMember	https://go.microsoft.com/fwlink/?LinkId=717988

Get-LocalUser	https://go.microsoft.com/fwlink/?LinkId=717980

Remove-LocalGroup	https://go.microsoft.com/fwlink/?LinkId=717975

Get-LocalGroup	https://go.microsoft.com/fwlink/?LinkId=717974

there can be more cmdlets that have same problems.

**Comment by sdwheeler** [comment]
There were a total of 34 links that got deactivated. These have been restored.

**Comment by Ashc0d** [comment]
Great, I will close this issue now.
