### ISSUE TITLE
Linux Enviroment Variable $env:ComputerName is missing 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2312]
Steps to reproduce
------------------
In Windows OS PowerShell, type: $env:COMPUTERNAME or hostname.
Result = Earth

In Ubuntu Linux 16.04.1, type:
$env:computername   (of course it doesn't exist)
or 
hostname
Result = orion

Expected behavior
-----------------
In Linux to see the $env:computername variable and its value.  
Is it possible to use the 'hostname' value to create the $env:COMPUTERNAME variable?

Actual behavior
---------------
$env:computername   (of course it doesn't exist)
or 
hostname
Result = orion

See attached images
![posh610_misscompname](https://cloud.githubusercontent.com/assets/19892435/18652586/948d3a96-7ea1-11e6-9807-9006791bc9d6.png)

Environment data
----------------
Linux: Ubuntu 16.04.1 64bit

PS /home/maxt> $PSVersionTable                                                  

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.10                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1  

```

**Comment by vors** [comment]
This is a special case of #1262

**Comment by andschwa** [comment]
I'm going to close this as a duplicate.

**Comment by MaximoTrinidad** [comment]
Sounds Good! Thanks

**Comment by TiloGit** [comment]
if anybody find this via google. here what works for hostname and user on linux:  (tested on ps container image)
```powershell
echo "My hostname is $([Environment]::Machinename) and My User $([Environment]::Username)"
```
