### ISSUE TITLE
Why is Select-XML really missing?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#2316]
According to the [Known Issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md) page, `Select-XML` is likely to be removed because XML is not in .Net Core...

However, it appears to me that the entire `System.Xml` namespace is in [CoreFX](https://github.com/dotnet/corefx) and [available on nuget](https://www.nuget.org/packages?q=system.xml+owner%3Adotnetframework) ... is there actually something missing, or is this just a mistake in the doc?

**Comment by rkeithhill** [comment]
XML schema validation support isn't in .NET Core (and my company needs that).  But I thought basic XML support was in there.

**Comment by mirichmo** [comment]
Mistake in the documentation. The cmdlet is part of 6.0.0-alpha.9:

```powershell
PS C:\Program Files\PowerShell\6.0.0.9 > select-xml "/doc" -Path $PSHOME\powershell.xml

Node Path                                               Pattern
---- ----                                               -------
doc  C:\Program Files\PowerShell\6.0.0.9\powershell.xml /doc
```

**Comment by vors** [comment]
@BrucePay this note was added in 585b8338 . Do you remember what didn't work?

**Comment by iSazonov** [comment]
@SteveL-MSFT  The issue seems should be closed.
