### ISSUE TITLE
Limitations on Workflow Parameters

### ISSUE THREAD

**Issue by EpicPhil** [PowerShell/PowerShell#2317]
Currently PowerShell Workflow does not support parameter validation on nested workflows.
It also does not support complex types on parameters. As more automation and orchestration tools are using PSWorkflow, I would like to see these limitations removed.

**Comment by alexandair** [comment]
I don't think this is related to open source PowerShell. Could you post it to UserVoice?

**Comment by EpicPhil** [comment]
Yep. I posted it here as there were already some workflow issues submitted. [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/16276288-parameter)

**Comment by ealexjordan** [comment]
We don't support PSWorkflow in open PowerShell:

Workflow is not supported in PowerShell Core.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : WorkflowNotSupportedInPowerShellCore

I'm not aware of any plans to support it, does anyone else know?

**Comment by ealexjordan** [comment]
Closing as this bug is not applicable to the repository in its current state, and I know of no plans to support workflow for this project yet. There is also a semi-similar issue here (again, only for desktop): https://github.com/PowerShell/PowerShell/issues/2222
