### ISSUE TITLE
Stop-Process and Stop-Service should have -ComputerName support

### ISSUE THREAD

**Issue by 1RedOne** [PowerShell/PowerShell#2318]
Steps to reproduce
------------------

- Teach someone about PowerShell and its built-in remote capabilities
- Show them the magic of Get-Service <someservice> -ComputerName A,B,C
- They ask you if you can pipe the results to Stop- or Start-Service to run on multiple machines
- Experience the joy of telling your children there is no Santa again, when you tell them that Stop-Service and Stop-Process don't have `-ComputerName` support.
- Their eyes glaze over when you explain that you *can* do it in WMI instead.

Expected behavior
-----------------
`Stop-Process ` should have `-ComputerName` support.  It stinks today to have to use an ugly `Get-WMIobject` cmdlet instead to actually enact changes on remote processes or services.

Actual behavior
---------------
If you try to Pipe the results of `Get-Process` or` Get-Service` to its matching Start or Stop cmdlet, PowerShell tries to make changes ON YOUR LOCAL PC instead. 

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.0.10514.6                                                                             
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.33440                                                                         
BuildVersion                   10.0.10514.6                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     



```

**Comment by alexandair** [comment]
Is this related to open source PowerShell?

**Comment by 1RedOne** [comment]
I was wrong! Nevermind! Closing...
