### ISSUE TITLE
build.psm1 Should Refresh the Ruby Gems during Start-PSBuild or Start-PSPackage

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#2322]
Steps to reproduce
------------------
This occurred during a Travis CI pass on OSX. The PR succeeded during initial validation, but failed after merge. It is unrelated to the content of the PR that got merged.

Expected behavior
-----------------
Success

Actual behavior
---------------
. . .
publish: Published to /Users/travis/build/PowerShell/PowerShell/src/powershell-unix/bin/Linux/netcoreapp1.0/osx.10.11-x64/publish
Published 1/1 projects successfully
VERBOSE: PowerShell Ngen assemblies have been generated, deleting ILs...
PowerShell.exe with ngen binaries is available at: /Users/travis/build/PowerShell/PowerShell/src/powershell-unix/bin/Linux/netcoreapp1.0/osx.10.11-x64/publish/powershell
WARNING: Please ensure you have previously run Start-PSBuild -Clean -CrossGen!
WARNING: -Types was not specified, continuing with osxpkg!
WARNING: Suffix not given, building primary PowerShell package!
     roff: /Users/travis/build/PowerShell/PowerShell/assets/powershell.1
/gems/ruby-2.2.1/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `map'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:76:in `contains_requirable_file?'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `block in find_in_unresolved'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `find_all'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `find_in_unresolved'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:74:in `require'
	from /Users/travis/.rvm/gems/ruby-2.2.1/gems/bundler-1.13.1/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.2.1/gems/bundler-1.13.1/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `map'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1370:in `add_self_to_load_path'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1283:in `activate'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /Users/travis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /Users/travis/.rvm/gems/ruby-2.2.1/bin/fpm:22:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Execution of { fpm $Arguments } failed with exit code 1
At /Users/travis/build/PowerShell/PowerShell/build.psm1:1871 char:13
+             throw "Execution of {$sb} failed with exit code $LASTEXIT ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Execution of { ...ith exit co 
   de 1:String) [], RuntimeException
    + FullyQualifiedErrorId : Execution of { fpm $Arguments } failed with exit 
    code 1

Environment data
----------------

Travis CI for OSX

**Comment by vors** [comment]
We should fix it ASAP, the current status of master on Travis is failing, because of it.

**Comment by andschwa** [comment]
This wasn't a problem with the gems, it was as buggy version of bundler. Fixed in #2352.
