### ISSUE TITLE
Incorrect Auto-Completion When Using Tab

### ISSUE THREAD

**Issue by JackW6809** [PowerShell/PowerShell#23244]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Typing ip shows ipconfig as a suggested auto-completion. However, when pressing TAB it auto-completes it to ipal

### Expected behavior

```console
Pressing TAB button when presented with auto-complete should fill in the rest with what we are presented with.
```

### Actual behavior

```console
Pressing TAB button when presented with auto-complete instead fills it to a random cmdlet it thinks is correct, which is what happens on PowerShell 5.1.
```

### Environment data

```powershell
PS C:\Users\jwillis> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/53652452/ac160ad0-8f70-4e0c-8958-f873f0f38362)
https://github.com/PowerShell/PowerShell/assets/53652452/67cc3405-8f92-4016-9b87-4651090b1f8b

**Comment by MartinGC94** [comment]
That's not tab completion, it's prediction. The standard way to accept predictions is the right arrow key, you can bind it to Tab like this: `Set-PSReadLineKeyHandler -Function AcceptSuggestion -Chord Tab` but then you won't have your standard tab completion so I'd advice against it.

**Comment by jhoneill** [comment]
You're seeing IPConfig because that was the most recent command beginning with IP that you used. 
If I type IP I get `IPMO module name`   

As @MartinGC94  says tab cycles through all commands beginning `IP` in alphabetical order, right arrow pulls back the whole of the line by default (so If you had `ipconfig /flushdns` you'd get the switch)
In my profile I've set ctrl right arrow to pull back a word at a time, which IMHO makes the feature significantly more useful.
