### ISSUE TITLE
Can't install packages using Nuget 2.8.5.207

### ISSUE THREAD

**Issue by swernli** [PowerShell/PowerShell#2331]
I filed issue https://github.com/NuGet/NuGetGallery/issues/3249 against Nuget for this, but wanted to file one here for both awareness and in case it is actually a PowerShell issue.

I'm working on the Docker PowerShell project (https://github.com/Microsoft/Docker-PowerShell) and we recently starting having issues with our automatic appveyor builds because of the new Nuget 2.8.5.207. It seems that installing packages via PowerShell's Install-Module command fails if the client machine has the latest version, but succeeds with version 2.8.5.205. This fails for 207 in our local testing as well, and happens regardless of which version produced the package. This means that any new clients will be unable to use our module at all. I tried dotnet packages, and those seem to work fine, so it has something to do with the way the PowerShell module packages get unpacked.

This is a major blocking issue for any PowerShell users who want to distribute modules via nupkgs.

@jterry75 @jstarks FYI.

**Comment by bmanikm** [comment]
Please note that local directory based repository can be used for both modules and scripts, so Publish cmdlets add PSModule tag for modules and PSScript tag for scripts during the publish operation. Publish cmdlets ensure that modules and scripts are valid before creating and pushing the Nupkg. 
We don't recommend users to use the NuGet tools directly to publish the modules and scripts.
