### ISSUE TITLE
start-process doesn't work properly in functions invoked from REPL

### ISSUE THREAD

**Issue by rjstone** [PowerShell/PowerShell#2341]
## Steps to reproduce

Define this function:

``` powershell
function su { Start-Process PowerShell -Verb RunAs }
```

Type `su` at the prompt.
## Expected behavior

It should either:
1. launch a new powershell widow running as Administrator or
2. Suspend the current shell and run an Administrator shell in the same window 
## Actual behavior

It seems like it's trying to run both processes in the same console where possibly both are getting stdin and outputting to stderr. It looks similar to trying to run an interactive process in using with `&` (background).

![animated gif](https://dl.dropboxusercontent.com/u/57161259/ShareX/201609/2016-09-22_15-11-57.gif)

Using `-Verb open` makes no difference.
## Environment data

``` powershell
C:\Program Files\PowerShell\6.0.0.10> $PSVersionTable

Name                           Value
----                           -----
PSEdition                      Core
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.10
CLRVersion
BuildVersion                   3.0.0.0
PSVersion                      6.0.0-alpha

```

**Comment by SteveL-MSFT** [comment]
This works on Windows PowerShell, not clear yet if cmdlet or engine issue

**Comment by rjstone** [comment]
**It doesn't work in Windows PowerShell for me.** It pretty much does the same thing. Here's the info from PowerShell on my Win10 system just upated with the anniversary update:

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.187
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.187
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
@rjstone I cut and pasted your repro into Windows PowerShell.  Calling 'su' brings up UAC to run elevated PowerShell as expected.  I'm running the same version of Windows PowerShell as you.  In alpha.10 on Windows, I see it not working.

**Comment by iSazonov** [comment]
Its work well on:
1.
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14926.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14926.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

2.
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10240.17113
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

**Comment by rjstone** [comment]
Ok, I'll clean out my profile and such to make sure that this isn't being caused by a module import or something similar. I really should have done that in the first place.

**Comment by rjstone** [comment]
Ok, cleaned out my profiles and modules folders. Still have problems with alpha but different:

![screenshot](https://dl.dropboxusercontent.com/u/57161259/ShareX/201609/2016-09-28_03-33-20.gif)

Actually, the same thing happens even if I run it directly rather than in a function.

Works fine in WindowsPowerShell now.

The first PowerShell.exe in my path is WindowsPowerShell. If I try to invoke alpha with start-process using the full path then something else happens. (For this test I didn't use RunAs.) The window appears but wont respond to keyboard input.

**Comment by joeyaiello** [comment]
In the latest PowerShell Core alpha (6.0.0-alpha.12) we explicitly don't allow `Start-Process -Verb`, but the problem does not appear to exist without -Verb (a new console is launched as you'd expect). 

#1691 is there to support `-Verb`
