### ISSUE TITLE
Corrupted PowerShellProperties.json prevents powershell from starting

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2342]
Steps to reproduce
------------------

Corruption of this file can happen for natural reasons (i.e. file was not flushed, but process died).
You can corrupt it artificially.

I.e.

```powershell
'' > src\powershell-win-core\bin\Debug\netcoreapp1.0\win10-x64\PowerShellProperties.json
src\powershell-win-core\bin\Debug\netcoreapp1.0\win10-x64\powershell.exe
```

Expected behavior
-----------------

PowerShell should be able to run

Actual behavior
---------------

```
C:\Users\sevoroby>F:\dev\PowerShell/src/powershell-win-core\bin\Debug\netcoreapp1.0\win10-x64\powershell.exe
PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

The shell cannot be started. A failure occurred during initialization:
Error reading JToken from JsonReader. Path '', line 0, position 0.

C:\Users\sevoroby>
```

PowerShell cannot run.
Removing the file fixes the problem.

I propose to handle this error gracefully: if file is corrupted, we should re-create it, like it was not present at all.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
CLRVersion
GitCommitId                    v6.0.0-alpha.10
PSRemotingProtocolVersion      2.3
PSEdition                      Core
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
```

**Comment by vors** [comment]
cc @mirichmo

**Comment by mirichmo** [comment]
This request is similar to #1614 (add Schema validation to the JSON file)

**Comment by mirichmo** [comment]
The simplest repro is to empty the config file:
``` powershell
Set-Content <path to config file> -Value "{}"
```
and then restart PowerShell. Give it invalid contents to trigger the scenario specified here.
