### ISSUE TITLE
Import-DscResource cannot override built-in DSC resources.

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/PowerShell#2344]
If a module has a DSC resource with the same name as the one from built-in DSC resources (from PSDesiredstateConfiguration) module, Powershell fails to compile DSC configuraiton.

**Comment by daxian-dbw** [comment]
@nitinbps could you please add repro steps?

**Comment by HemantMahawar** [comment]
@nitinbps I believe this issue was resolved in DSC layer. Can you validate and close? /cc: @grayzu

**Comment by nitinbps** [comment]
@HemantMahawar @grayzu  Yes, this issue is resolved in DSC layer. Closing the issue.
