### ISSUE TITLE
FindFirstFileName and FindNextFileName are available in NanoServer and IoT now, so we should enable the usage of them in powershell core

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#2349]
There are 2 issues to address here
- [ ] The usage of `FindFirstFileName` and `FindNextFileName` is disabled in powershell core at https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L7928. Now they are available in NanoServer and IoT in the API set `api-ms-win-core-file-l1-2-2`, so maybe now it's the time to enable them in powershell core. Note that this API set is not available in .net core packages by default, so we basically need to verify if the `kernel32` forwarder on NanoServer and IoT can correctly forward the call to the right API set.
- [x]  (Fixed in #7655) `FileSystemProvider.cs` needs to be refactored. I spot 2 things -- (1) `GetTarget` and `InternalGetTarget` needs to be refactored as `Platform.NonWindowsInternalGetTarget` won't be reached at all. (2) runtime checks should be converted to compilation time checks as much as possible.

**Comment by SteveL-MSFT** [comment]
It appears that this will enable retrieving file attributes if a file is in use.

```powershell
PS C:\> dir -Hidden .\pagefile.sys


    Directory: C:\


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
              11/2/2016   5:46 PM     5637144576 pagefile.sys
```

Expected is Mode column has attribute information

**Comment by iSazonov** [comment]
@daxian-dbw I reviewed point one and debug for windows reparse points (symlink and mount point) - this works well and we get ETS Target property for FileSystemInfo objects. So the code with FindFirstFileName (currently disabled) looks unnecessary. I think we could remove it. Do I skip something?

**Comment by iSazonov** [comment]
@daxian-dbw Could you please look my previous comment? Seems we could remove the dead code.

**Comment by daxian-dbw** [comment]
@iSazonov Will look at the uses of those native APIs again.

**Comment by iSazonov** [comment]
@daxian-dbw @SteveL-MSFT Can we close the issue?
