### ISSUE TITLE
Bundled Modules should be installed in \Name\Version\ folders in PSCore

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#2350]
## Steps to reproduce

Install v6.0.0.10 for Windows10
Open `C:\Program Files\PowerShell\6.0.0.10\Modules` and check the folder for the bundled module like PSReadLine
## Expected behavior

There should be a folder relating to the version of the Module installed and the module files should be in that location i.e. `C:\Program Files\PowerShell\6.0.0.10\Modules\PSReadLine\1.2\`
## Actual behavior

Module files are stored in the module name folder with no version folder i.e. `C:\Program Files\PowerShell\6.0.0.10\Modules\PSReadLine\`
## Environment data

``` powershell
Name                           Value                                                                                   
----                           -----                                                                                   
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSVersion                      6.0.0-alpha                                                                             
SerializationVersion           1.1.0.1                                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
WSManStackVersion              3.0                                                                                     
GitCommitId                    v6.0.0-alpha.10-dirty                                                                   
BuildVersion                   3.0.0.0                                                                                 
CLRVersion                                                                                                             
```

**Comment by SteveL-MSFT** [comment]
This appears to affect all modules

**Comment by kilasuit** [comment]
This seems to still affect the modules below that are built along with PowerShell from what I can tell in the 6.0.0.13 release

CimCmdlets
Microsoft.PowerShell.Archive
Microsoft.PowerShell.Diagnostics
Microsoft.PowerShell.Host
Microsoft.PowerShell.LocalAccounts
Microsoft.PowerShell.Management
Microsoft.PowerShell.Security
Microsoft.PowerShell.Utility
Microsoft.WSMan.Management
Pester
PSDesiredStateConfiguration
PSDiagnostics
PSReadLine

**Comment by joeyaiello** [comment]
Still relevant, but not critical for 6.0.0.

**Comment by kilasuit** [comment]
@joeyaiello - although not critical it is IMO detrimental for being able to ship any of these in packaged versions as separate packages

**Comment by iSazonov** [comment]
I believe it requires an enhancement in Import-Module to load last version, required version or explicit version too, doesn't  it?

**Comment by SteveL-MSFT** [comment]
@iSazonov `import-module` already understands module versioning, this should only require putting the module files under a version folder

**Comment by iSazonov** [comment]
Sorry for the inaccuracy. I mean, can the cmdlet do this for directory structure like "<PowerShell install directory>\PowerShell\<PowerShell version>\Modules\<Module name>\<Module version>\" ?

**Comment by SteveL-MSFT** [comment]
Should be $PSHome/Modules/<ModuleName>/<ModuleVersion/

**Comment by joeyaiello** [comment]
@iSazonov: yes, we look in any folder in PSModulePath for module folders, and in those module folders we look for version folders. In the absence of a version folder, we load the module from there. 

For context, this is in the PSModulePath in 6.0.0-beta.1:

```
$env:psmodulepath
C:\Users\jaiello.REDMOND\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6.0.0-beta.1\Modules
```

@kilasuit could you elaborate? I don't fully understand the scenario you're describing.

**Comment by kilasuit** [comment]
@joeyaiello - It just shows a level of inconsistency & it could easily cause confusion to those not that overly familiar. It also allows in future for the potential for all modules bundled with the engine to be unbundled as per #1979 

Also as versioned modules support was brought in v5 it really doesn't make sense for there to be this inconsistency in a v6 product especially as you are moving to a more decoupled nature the further that the development goes on and on.

**Comment by SteveL-MSFT** [comment]
Until the module is decoupled from PSCore itself, there's no value to have it in a versioned folder since it's not updatable outside of updating PSCore itself.  The ones that have versioned folders are those obtained from PSGallery.

**Comment by iSazonov** [comment]
Currently we removed all external modules from the repo and as @SteveL-MSFT said all standard modules is installed without version folder to support servicing by WU. 
So I close the Issue.

**Comment by o-l-a-v** [comment]
This should not be closed. Making WU able to update modules might be implemented, but it partially broke import.
