### ISSUE TITLE
Fails to build on macOS Seirra

### ISSUE THREAD

**Issue by AmandaCameron** [PowerShell/PowerShell#2353]
Steps to reproduce
------------------
Attempt to build PowerShell on macOS Seirra.

Expected behavior
-----------------
PowerShell builds.

Actual behavior
---------------
Bunch of nasty errors about unsupported runtime `osx.10.12-x64` -- adding that to the sets, and the various `package.json`s results in a cryptic build output: https://gist.github.com/AmandaCameron/5e088a8fbae1f1f8b95f737133fca08c

Environment data
----------------

(Not sure it matters, but: )

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.10
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andschwa** [comment]
@AmandaCameron can you verify that both CoreCLR, CoreFX, and .NET CLI all support OS X 10.12 now?

**Comment by andschwa** [comment]
Confirmed that .NET does not yet support 10.12. I'm going to close this as there is nothing we can do until our language gets supported on this platform (*please do re-open as soon as that's the case*). Thanks!
