### ISSUE TITLE
Can we improve the semantic version implementation for myget?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#2354]
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

http://semver.org/
### Two things I'd propose improving.

First, current releases on MyGet are being labelled badly. For instance, SMA is "1.0.0-alpha10" or "1.0.0-alpha9" ... 
1. I'm pretty sure that should be 6.0.0?
2. I think the pre-release section should be -alpha.9 and -alpha.10 

Second, the `System.Management.Automation.SemanticVersion` built into PowerShell 6 can't sort pre-releases into the right order ... because it treats everything on the end as a _single_ text label and sorts them alphabetically (so, like Visual Studio, it thinks the "1.0.0-alpha9" is newer than "1.0.0-alpha10").

**Comment by SteveL-MSFT** [comment]
I would suggest having the SMA.SemanticVersion be a separate issue

**Comment by vors** [comment]
@daxian-dbw can you, please comment on the "." in pre-release part?
Together with alpha.11, we will remove alpha9 package from myget feed to fix the order.

**Comment by daxian-dbw** [comment]
@Jaykul yes, we spotted this awkward issue in powershell-core myget, and I'm sorry for not thinking through when publishing the alpha9 packages.
As for the '.', nuget treats version tags like "1.0.0-alpha.05" as invalid, and package with that version tag cannot be opened by tools like "Nuget Package Explorer".

```
PS:80> cat .\test.nuspec -TotalCount 6
<?xml version="1.0"?>
<package >
    <metadata>
        <id>test</id>
        <version>1.0.0-alpha.05</version>
        <title>test</title>
PS:81> nuget pack .\test.nuspec
Attempting to build package from 'test.nuspec'.
'1.0.0-alpha.05' is not a valid version string.
Parameter name: value
```

**Comment by Jaykul** [comment]
Ok, I just double-checked, and I see that even though your feed on MyGet has support for Semver 2, _after 2 years_, SemVer2 is still _deliberately blocked_ in `nuget pack` ...

So yeah, uhm ... zero padding, and a little bit of planning about how many "-alpha" releases are reasonable 😲 

The [current state](https://github.com/NuGet/Home/wiki/SemVer-2.0.0-support) --for anyone else.

**Comment by emgarten** [comment]
@daxian-dbw ``1.0.0-alpha.05`` contains a leading zero on a release label which makes it invalid. Try: ``1.0.0-alpha.5`` or if you really want the zero, ``1.0.0-alpha-05``

See http://semver.org/#spec-item-9 for more on the release label rules

**Comment by daxian-dbw** [comment]
@emgarten thanks for pointing it out. I tried `1.0.0-alpha.5` and it doesn't work even with the latest [v3.5.0-rc1 nuget.exe](https://dist.nuget.org/index.html):
```
PS:38> cat .\test.nuspec -TotalCount 6
<?xml version="1.0"?>
<package >
    <metadata>
        <id>test</id>
        <version>1.0.0-alpha.5</version>
        <title>test</title>
PS:39> E:\arena\nupkg\NuGet.exe pack .\test.nuspec
Attempting to build package from 'test.nuspec'.
Versions using SemVer 2.0.0 are not supported: 1.0.0-alpha.5.
PS:40> E:\arena\nupkg\NuGet.exe | select -First 1
NuGet Version: 3.5.0.1737
```

**Comment by emgarten** [comment]
@daxian-dbw use the latest NuGet.exe here: https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829

3.5.0-rc1 had SemVer 2.0.0 blocked, but that was changed after rc1.

**Comment by daxian-dbw** [comment]
Thanks @emgarten, the rtm build works, though with warning about incompatibility with old client:
```
Attempting to build package from 'test.nuspec'.
Successfully created package 'E:\arena\nupkg\temp\test.1.0.0-alpha.5.nupkg'.
WARNING: Issue found with package 'test'.

WARNING: Issue: Package version not supported on legacy clients.
WARNING: Description: The package version '1.0.0-alpha.5' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. This message can be ignored if the package is not intended for older clients.
WARNING: Solution: Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter.
```
dotnet-cli works with `1.0.0-alpha.5` nuget package, but the latest "Nuget Package Explorer" v3.18 doesn't because it's compatible only with nuget 2.8.1 and below.

**Comment by Jaykul** [comment]
That's such a shame ;-)

**Comment by andschwa** [comment]
(Ah wouldn't life have been simpler with 0.11.0? 😉)

**Comment by joeyaiello** [comment]
As discussed, add the `.` so we can close this out. The rest of SemVer is covered in #2983

**Comment by joeyaiello** [comment]
The `.` has been added to `$PSVersionTable` and the filename
