### ISSUE TITLE
ISE Excape Caracters Bug

### ISSUE THREAD

**Issue by agowa338** [PowerShell/PowerShell#2355]
Steps to reproduce
------------------
Open ISE and Run the following code:
```Write-Host "Text1" -NoNewline;Write-Host $("`rText2");```
Now open Powershell (not ISE) and do the same, it has a different behavior 

Expected behavior
-----------------
The following output
> Text2

Actual behavior
---------------
The following output
> Text1Text2

Environment data
----------------
```
Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.0.10586.494                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.10586.494                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1
```

**Comment by MaximoTrinidad** [comment]
Hum! What about PowerShell PSVersion  -  6.0.0-alpha for Windows.  It seem this is a Windows PowerShell ISE issue and should be address thru Windows UserVoice  site at:
https://windowsserver.uservoice.com/forums/301869-powershell/ 

In PowrShell version 6.0.0-alpha.10 for Windows as well as Windows PowerShell version 5.1 is woking fine.

![ise_issue_2016-09-25](https://cloud.githubusercontent.com/assets/19892435/18817887/c4a4f5c4-8339-11e6-8f13-c269ebd874f7.jpg)

**Comment by kiazhi** [comment]
Yes, I think it is an ISE issue too.

![ise excape caracters bug 2355](https://cloud.githubusercontent.com/assets/13409063/18818425/8b1d9378-83d5-11e6-91f2-3973fe6536c7.jpg)

**Comment by joeyaiello** [comment]
As @MaximoTrinidad said, please file this bug on UserVoice under the ISE subforum: https://windowsserver.uservoice.com/forums/301869-powershell/category/148050-ise-and-tooling
