### ISSUE TITLE
PowerShell causes Segmentation Fault with Find-Command on Linux when network is connected through VPN

### ISSUE THREAD

**Issue by hsaito** [PowerShell/PowerShell#2356]
Steps to reproduce
------------------
1. Start Powershell
2. Prompt is displayed
3. Type in Find-Command
4. A segmentation fault occurs

Expected behavior
-----------------
It should not cause a segmentation fault, and should display a list of commands.

strace below:
```
PS /home/hideki>                           Find-Command                                                                                                                                               
) = 0
futex(0x93c188, FUTEX_WAKE_PRIVATE, 1)  = 0
gettid()                                = 28897
clone(child_stack=0x7f74317b8fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f74317b99d0, tls=0x7f74317b9700, child_tidptr=0x7f74317b99d0) = 28917
sched_getparam(28917, [0])              = 0
sched_getscheduler(28917)               = 0 (SCHED_OTHER)
sched_get_priority_max(SCHED_OTHER)     = 0
sched_get_priority_min(SCHED_OTHER)     = 0
sched_setscheduler(28917, SCHED_OTHER, [0]) = 0
write(168, "*", 1)                      = 1
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
futex(0x93c1b4, FUTEX_WAIT_PRIVATE, 9, NULL <unfinished ...>
+++ killed by SIGSEGV +++
zsh: segmentation fault  strace powershell
```

Actual behavior
---------------
Powershell segfaults and does not display a list of commands.

Environment data
----------------
```
Name                           Value                                                                                                                                                                 
----                           -----                                                                                                                                                                 
PSVersion                      6.0.0-alpha                                                                                                                                                           
PSEdition                      Core                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                               
BuildVersion                   3.0.0.0                                                                                                                                                               
GitCommitId                    v6.0.0-alpha.10                                                                                                                                                       
CLRVersion                                                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                   
SerializationVersion           1.1.0.1     
```

**Comment by MaximoTrinidad** [comment]
Hi hsaito!

You missed to provide which version of linux you had this issue.

I did ran Find-Command on my Ubuntu 16.04.1 LTS Desktop and had no problems executing the Find-Command in PowerShell version v6.0.0-alpha.10.

![posh6findcmd](https://cloud.githubusercontent.com/assets/19892435/18818859/bb47e4dc-8352-11e6-8b0f-9cc2e31bf35f.png)
. (see image)

**Comment by hsaito** [comment]
Sorry for the lack of info on that, it's ubuntu 16.04 LTS, 15.6GiB memory, Intel Core i7-2600 CPU @ 340GHz x 8, Gallium 0.4 and AMD TURKS (DRM 2.43.0, LLVM 3.8.0).

I have actually isolated this issue to only happen when I am connected through VPN. If I disconnect from the VPN, it works as designed.

**Comment by hsaito** [comment]
For the security reason, I can't provide too much detail on VPN connection, but it is an OpenVPN connection.

**Comment by andschwa** [comment]
@hsaito can you run the Pester tests and see which fail? That might help to narrow it down.

**Comment by hsaito** [comment]
I am not sure how the Pester test works at this moment, but does the following output suffice?

./Pester.Tests.ps1                                                                                                                                                     
Describing Pester manifest and changelog
 [+] has a valid manifest 40ms
 [+] has a valid name in the manifest 13ms
 [+] has a valid guid in the manifest 13ms
 [+] has a valid version in the manifest 14ms
 [+] has a valid version in the changelog 19ms
 [+] changelog and manifest versions are the same 10ms
Describing Clean treatment of the $error variable
   Context A Context
    [+] Performs a successful test 30ms
 [+] Did not add anything to the $error variable 21ms
Describing SafeCommands table
 [+] The SafeCommands table contains all commands that are called from the module 33ms
Describing Style rules
 [+] Pester source files contain no trailing whitespace 79ms
 [+] Pester Source Files all end with a newline 9ms
Describing ResolveTestScripts
 [+] Resolves non-wildcarded file paths regardless of whether the file ends with Tests.ps1 61ms
 [-] Finds only *.Tests.ps1 files when the path contains wildcards 19ms
   Expected: {True}
   But was:  {False}
   at line: 187 in /home/hideki/pester/Pester/Pester.Tests.ps1
   187:             ($paths -contains "$TestDrive\SomeFile.Tests.ps1") | Should Be $true
 [-] Finds only *.Tests.ps1 files when the path refers to a directory and does not contain wildcards 19ms
   Expected: {True}
   But was:  {False}
   at line: 198 in /home/hideki/pester/Pester/Pester.Tests.ps1
   198:             ($paths -contains "$TestDrive\SomeFile.Tests.ps1") | Should Be $true
 [+] Assigns empty array and hashtable to the Arguments and Parameters properties when none are specified by the caller 21ms
   Context Passing in Dictionaries instead of Strings
    [+] Allows the use of a "P" key instead of "Path" 31ms
    [+] Allows the use of an "Arguments" key in the dictionary 16ms
    [+] Allows the use of an "Args" key in the dictionary 14ms
    [+] Allows the use of an "A" key in the dictionary 16ms
    [+] Allows the use of a "Parameters" key in the dictionary 16ms
    [+] Allows the use of a "Params" key in the dictionary 20ms
    [+] Throws an error if no Path is specified 15ms
    [+] Throws an error if a Parameters key is used, but does not contain an IDictionary object 16ms

**Comment by SteveL-MSFT** [comment]
This issue was moved to PowerShell/PowerShellGet#20

**Comment by mi-hol** [comment]
@hsaito with several new version of PSGet published since the bug was reported I wonder if it still exists.
Would you mind to test and comment on https://github.com/PowerShell/PowerShellGet/issues/20 ?
