### ISSUE TITLE
Module install fails due to missing-localisation on Windows

### ISSUE THREAD

**Issue by ryangrannell** [PowerShell/PowerShell#2357]
I'm currently trying to install Azure on one of our Windows2012 VMs, but the install fails due to a missing localisation variable. If there's anymore information needed to identify the cause of this bug, leave a comment and I'll respond quickly. 

It appears to be related to #1874 

### Steps to reproduce:

Run `Install-Module Azure`, `Install-Module Azure-RM`, `Install-Module pester`, or `Find-Module` on a particular machine. This doesn't occur on any of our companies other PCs / VMs.

## Suspected cause

The cmdlet `Install-Package` from `PowerShellGet` as it makes several calls to methods on the variable `$LocalizedData`. I don't understand why `$LocalizedData` is undefined.

## Expected behaviour

The module should be successfully installed.

## Actual behaviour

The following errors occurs:

```
PS C:\Users\Administrator> install-module pester
WARNING: The variable '$LocalizedData' cannot be retrieved because it has not been set.
PackageManagement\Install-Package : The variable '$LocalizedData' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\PSGet.psm1:1009 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (LocalizedData:String) [Install-Package], Exception
    + FullyQualifiedErrorId : VariableIsUndefined,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\Users\Administrator> install-module pester
```

```
Find-Module

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.1.0      AzureRM.profile                     PSGallery            Microsoft Azure PowerShell - Profile credential ...
2.1.0      Azure.Storage                       PSGallery


PS C:\Users\Administrator>
```

## Windows version

````
WindowsServer 2012
(Get-ItemProperty -Path c:\windows\system32\hal.dll).VersionInfo.FileVersion
6.3.9600.17196 (winblue_gdr.140601-1505)
````

## PowerShell-version

```
PSVersion:                 5.0.10514.6
WSManStackVersion:         3
SerializationVersion:      1.1.0.1
CLRVersion:                4.0.30319.42000
BuildVersion:              10.0.10514.6
PSCompatibleVersions:      {1.0, 2.0, 3.0,4.0...}
PSRemotingProtocolVersion: 2.3
```

**Comment by bmanikm** [comment]
@ryangrannell From the error message, it looks like you have very old version of PowerShellGet. Please try with the latest version of PowerShellGet.  There’s a blog topic with the details [here](https://blogs.msdn.microsoft.com/powershell/2016/09/29/powershellget-and-packagemanagement-in-powershell-gallery-and-github/).
