### ISSUE TITLE
Add Standard Deviation to Measure-Object output

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2358]
Standard Deviation is a measure that is used to quantify the amount of variation or dispersion of a set of data values. A low standard deviation indicates that the data points tend to be close to the mean (also called the expected value) of the set, while a high standard deviation indicates that the data points are spread out over a wider range of values.

This is a commonly used to get an insight about a set of values, and would be easy to implement as an addition to Measure-Object.

**Comment by iSazonov** [comment]
This requires a double iterate: first, to calculate the mean value, the second, to calculate the variance.
Now Measure-Object don't collect values for second iterate. It is too complicate the cmdlet.
Also there's the challenge of the accuracy of the calculations for real data.
I believe this is a task for specialized statistical module.

**Comment by powercode** [comment]
@iSazonov I'd turn the argument around: Give me something easy and useful as a build in tool, and write a specialized statistical module if you want higher accuracy or better performance.

**Comment by vors** [comment]
Fixed in #6238
