### ISSUE TITLE
nuget feature tests are failing in daily builds

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#2360]
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-alpha.10-686#L6984
is an example

Steps to reproduce
------------------

observe daily build (ex: https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-alpha.10-686)

Expected behavior
-----------------
no errors

Actual behavior
---------------
```
 [-] EXPECTED: Finds 'TestPackage' Package using fwlink 1.94s
   Expected: {} to match the expression {TestPackage}
   at line: 332 in C:\projects\powershell\test\powershell\Modules\PackageManagement\Nuget.Tests.ps1
   332:         (find-package -name "TestPackage" -provider $nuget -source $fwlink -forcebootstrap).name | should match "TestPackage"
```
Environment data
----------------
```
AppVeyor
Build started
git clone -q --branch=master https://github.com/PowerShell/PowerShell.git C:\projects\powershell
git checkout -qf f991d5fea48a1700229855fc133c933910c6c3fb
```

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShellGet#40
