### ISSUE TITLE
Set-LocalUser -PasswordNeverExpires seems to be broken on Nano Server

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/PowerShell#2365]
Steps to reproduce:
On Nano server: 
(either create a fake user account or use an existing one)
Set-LocalUser -Name 'userName' -PasswordNeverExpires:$true

Expected behavior:
The PasswordExpires attribute should now be set to $null for this user

When set back to $false, this attribute should be an expiration date

Actual behavior:
Nothing is changed

Environment data:
Nano Server

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14300.1003
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.14300.1003
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

**Comment by mirichmo** [comment]
I fixed that issue in May. Can you retry with a more recent Nano Server build? Nano Server RTM or later should include the fix.

**Comment by mbreakey3** [comment]
Yes, thank you!
