### ISSUE TITLE
Test priority/scope Tag @(CI, Feature, Scenario) should be exclusive

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2366]
At the moment there are test suites (i.e.
https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.LocalAccounts/Pester.Command.Cmdlets.LocalAccounts.LocalGroupMember.Tests.ps1 ) that have entries like

```powershell
Describe "Validate simple Get-LocalGroupMember" -Tags "CI", "Feature" {
...
```
We should have only one priority tag on the test suite.

**Comment by mirichmo** [comment]
I fixed LocalAccounts in PR #2335
