### ISSUE TITLE
FileSystemProvider path normalization for 8dot3 names broken in certain cases

### ISSUE THREAD

**Issue by oising** [PowerShell/PowerShell#2369]
Certain classes of 8dot3 short names cause the FileSystemProvider to erroneously state that the folder does not exist, but only for certain operations. The below example is from my own office, where my `$env:temp` folder uses the short filename reference in the path string (some historical reason for this, no idea.) Calls to `test-path $env:path` return `true`, and `dir $env:path` succeed, but `cd $env:temp` fails stating:

```
cd : An object at the specified path C:\Users\OA148~1.GRE does not exist.
At line:1 char:1
+ cd $env:temp
+ ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.SetLocationCommand
```

Reproduction requires short file name generation to be enabled, so if it's not enabled for you, you'll need to run:

`fsutil behavior set disable8dot3 0` and then reboot.
## Steps to reproduce

```
PS c:\temp> md o.grehan
PS c:\temp> fsutil file setshortname c:\temp\o.grehan OA148~1.GRE
PS c:\temp> test-path -PathType Container C:\temp\oa148~1.gre
True
PS c:\temp> cd C:\temp\oa148~1.gre
cd : An object at the specified path C:\temp\oa148~1.gre does not exist.
...
```

Initial investigation led me to believe that the issue lies in `FileSystemProvider.NormalizeThePath(String, Stack<String>)` method. There appears to be some assumption that is no longer true when the "short" name becomes longer than the original target "long" name. This seems to occur when the target has a long "extension", e.g. "o.grehan." 

It appears this bug has existed since v1.
## Expected behavior

Should be able to set-location to the folder by using the 8dot3 name.
## Actual behavior

Unable to set-location by using the 8dot3 name. 
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by oising** [comment]
`cd` works fine, btw, for most SFNs - specifically ones that are actually shorter than their targets (which is the majority of the time.)

**Comment by oising** [comment]
Trying to fork and write a fix for a PR and my build fails precisely because of this bug. Oh, the irony!

![image](https://cloud.githubusercontent.com/assets/1844001/19580754/fec0beba-96ed-11e6-8b7a-85150eb6fcf9.png)

**Comment by oising** [comment]
I have to run: `$env:temp = "c:\users\o.grehan\appdata\temp"` and it avoids triggering the bug.

**Comment by bormm** [comment]
This is still an issue and also has a "newer" duplicate( #7760). Unfortunately it never got any interest from microsoft in the last 5 years, even you find [530.000 pages](https://www.google.com/search?q=%22An+object+at+the+specified+path%22) with this error message and most seems to be related with this issue. As even Microsoft developers do not know about this, it also causes [this issue in Azure DevOps](https://github.com/microsoft/azure-pipelines-tasks/issues/10571).

**Comment by arsing** [comment]
Copying repro steps from #7760 :

```powershell
New-Item -Type Directory .\a.bcde
New-Item -Type File .\a.bcde\f.txt
Get-ChildItem '.\A5055~1.BCD\f.txt' # succeeds
Get-Content '.\A5055~1.BCD\f.txt' # succeeds
Remove-Item '.\A5055~1.BCD\f.txt' # fails
Set-Location '.\A5055~1.BCD' # fails
```
