### ISSUE TITLE
Enable importing classes from module versions

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2370]
In 5.1, to import the classes defined in a module, you using the 'Using module' keywords. But the Using keyword does not take a ModuleSpecification object, so you can't enter a version. This is a real problem if you have multiple versions of a module. Also, module versioning lets you version the classes in a module, but Using requiring a constant prevents it.

I'd like to suggest the following:
-- Make Import-Module import classes. It already has version params + FullyQualifiedName.
-- Add ClassesToExport key to the module manifest. If that breaks back-compat, put it in PrivateData.
-- Add Class parameter to Export-ModuleMember.
-- Make classes public by default, but users can use Export-ModuleMember or manifest to prevent export of a class.

If this isn't possible, at least add ModuleSpecification value to 'Using module.'

**Comment by vors** [comment]
Hi June,

I see that your closed the issue. It should work as you described already.
Please let us know, if you find any problem!

-Sergei
