### ISSUE TITLE
"Find-Command" & "Install-Module" cmdlets show identify OS compatibility

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2374]
Steps to reproduce
------------------
In Linux, using either Find-Command or Install-Module, will list all available (Windows and Linux).

Expected behavior
-----------------
Install the module that can be executed Linux, as well as Windows.

It maybe a good idea to have these cmdlets check for the OS type before providing the list.

Actual behavior
---------------
A Module won't install because it need dependencies, or was built for Windows OS.  Below, example has been addressed;
https://github.com/janegilring/PSVersion/issues/5 

![psversionissue](https://cloud.githubusercontent.com/assets/19892435/18915047/9d00aaba-855d-11e6-82dd-60ea70da1c59.png)

Environment data
----------------
Linux: Ubuntu 16.04.1 64bit

```
PS /home/maxt> $PSVersionTable                                                  

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.10                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1  
```

**Comment by joeyaiello** [comment]
We've talked about this in the past. My only reservation here is that many module authors won't know that they are actually compatible (or mostly compatible) with macOS or Linux, and I'd rather not *prevent* users from installing those modules. (E.g. posh-git is 99% working on Mac/Linux)

Maybe we should offer a warning at install time if compatibility isn't explicitly listed? 

I also agree we should absolutely give users a way to explicitly filter by OS or Edition.

**Comment by SteveL-MSFT** [comment]
This issue was moved to PowerShell/PowerShellGet#19
