### ISSUE TITLE
`Remove-Item` progress should only be displayed if > 5 items

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#23831]
### Summary of the new feature / enhancement

https://github.com/PowerShell/PowerShell/pull/20778 added progress for `remove-item`, but for small sets of items it can be a bit annoying to see it flash "removing 1" or 2 items.  I think it makes sense to not write progress unless the number of items is at least >5 and/or total time exceeds 2 seconds

**Comment by theJasonHelmick** [comment]
Thank you @SteveL-MSFT for this issue. The Interactive Working group has reviewed this and agrees that displaying the progress bar for items that take less than a couple of seconds doesn't make sense.

**Comment by iSazonov** [comment]
The same for Copy-Item.

**Comment by TheSpyGod** [comment]
Is this still available to take?

**Comment by TheSpyGod** [comment]
I'll take this if its free
