### ISSUE TITLE
PoweShell preview releases vanished from github

### ISSUE THREAD

**Issue by core-code** [PowerShell/PowerShell#23832]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

up until a few days ago all the releases of powershell-preview have been posted to this GitHub repository. 

e.g.: https://github.com/PowerShell/PowerShell/releases/tag/v7.5.0-preview.2/

now they are all gone? why? where will they be posted in the future? thanks!

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```powershell
N/A
```

### OS Data

```powershell
N/A
```

### Windows update log

```markdown
N/A
```

**Comment by jborean93** [comment]
If it helps, they are still up for me.

**Comment by core-code** [comment]
do you see them here?

https://github.com/PowerShell/PowerShell/releases

**Comment by core-code** [comment]
but i see the info has moved here, so lets close this:

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.4#installation-via-direct-download
