### ISSUE TITLE
PowerShell won't load .NET Assemblies cross-platform

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2384]
## Steps to reproduce

I've been trying to figured out to load some of the .NET Assemblies available under PowerShell ver. 6.0.0.0-alpha.10.

In Windows PowerShell 5.1 the following code runs OK:

_$writer = New-Object XML.XmlTextWriter 'c:\tempxml\sample.xml', ([Text.Encoding]::Unicode)
$writer.GetType().FullName_

But, in both Windows and Linux under PowerShell ver. 6.0.0.0-alpha.10 failed to run giving the error message:
New-Object : Cannot find type [XML.XmlTextWriter]: verify that the assembly containing this type is loaded.
## Expected behavior

To run as expected.
## Actual behavior

Script line fails:
New-Object : Cannot find type [XML.XmlTextWriter]: verify that the assembly containing this type is loaded.
At line:1 char:11
- $writer = New-Object XML.XmlTextWriter 'c:\temp\test3.xml', ([Text.En ...
-           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
  - FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

![posh5assemissue_2016-09-29](https://cloud.githubusercontent.com/assets/19892435/18958264/12baaada-8630-11e6-833f-8c0d44797907.jpg)
## Environment data

Windows OS Name:  Microsoft Windows 10 Pro Insider Preview 10.0.14931 N/A Build 14931

Linux: Ubuntu 16.04.1 LTS Desktop

``` powershell
PS C:\Program Files\PowerShell\6.0.0.10> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
CLRVersion
GitCommitId                    v6.0.0-alpha.10
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
SerializationVersion           1.1.0.1
PSEdition                      Core


```

**Comment by joeyaiello** [comment]
I'm not sure that CoreFX has implemented it yet: https://docs.microsoft.com/en-us/dotnet/core/api/system.xml#System_Xml

Leaving this open for someone else to validate though.

**Comment by MaximoTrinidad** [comment]
I just wanted to be documented.  I tried to use other assemblies under both Linux and Windows PowerShell 6.0.0.0-alpha.10 folder. But wasn't able to create a PowerShell object using New-Object.

I know that maybe this will be implemented sometime soon.

:)

**Comment by Jaykul** [comment]
@joeyaiello https://github.com/dotnet/corefx/tree/master/src/System.Xml.XmlDocument ??

**Comment by jgraafstra** [comment]
I'm also seeing similar results on OS X. I installed the MySql package via 'install-package', and then referenced the assembly using Add-Type. The MySql package came from: https://docs.efproject.net/en/latest/providers/mysql/

Add-Type didn't return any errors. However, when trying to reference that assembly it fails with:
`New-Object : Cannot find type [MySql.Data.MySqlClient]: verify that the assembly containing this type is loaded.`


```
$PSVersionTable                                                                                                                                                          
Name                           Value                                                                                                                                                      
----                           -----                                                                                                                                                      
PSVersion                      6.0.0-alpha                                                                                                                                                
PSEdition                      Core                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                    
BuildVersion                   3.0.0.0                                                                                                                                                    
GitCommitId                    v6.0.0-alpha.10                                                                                                                                            
CLRVersion                                                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                        
SerializationVersion           1.1.0.1  
```

**Comment by Jaykul** [comment]
@jgraafstra You should have opened a new ticket. 

THIS ticket isn't really about loading, it's about types that were built-in in _Full .NET_ and are not in PowerShell Core (in this particular case, it should be fixable, since the XML classes are in CoreFX now).

However, *your* problem is simply that you don't know what you're doing 😉 

### `MySql.Data.MySqlClient` is a namespace, not a class.

Most likely, your main problem is that you _need to load [**all** of the **dependencies**](https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore#dependencySets) of that `MySql.Data` library first_. And there are *a lot* of them when you start looking at them recursively.

Try looking at the **actual error** that happens when you try to run `Add-Type` ... run something like this:

```posh
add-type -Path .\MySql.Data.dll -PassThru
$Error[0].Exception.LoaderExceptions
```

To make it work, the simplest thing is to collect **all** the dependencies together in one folder.
You can do that like this:

```posh
Install-Package MySql.Data.EntityFrameworkCore -RequiredVersion 7.0.5-IR21 -Destination .\MySql
Get-ChildItem .\MySql\*\lib\netstandard1.*\*.dll | Move-Item -Destination .\MySql -Force
Get-ChildItem .\MySql\ -Directory | Remove-Item -Recurse
```

Now that you have all the assemblies in the MySql folder, you can actually Add-Type successfully, and make a connection, like this:

```posh
Add-Type -Path .\MySql\MySql.Data.EntityFrameworkCore.dll -PassThru
[MySql.Data.MySqlClient.MySqlConnection]::new("server=localhost; user id=root; password=admin; database=mydatabase");
```

**Comment by joeyaiello** [comment]
Resolving as external given that this is a .NET Core problem. 

Also, @jaykul, I don't actually see any implementation in the folder you posted. They're just empty type forwarders

**Comment by Jaykul** [comment]
Good point @joeyaiello, the implementation is in /future (e.g. https://github.com/dotnet/corefx/blob/future/src/System.Xml.XmlDocument/src/System/Xml/Dom/XmlDocument.cs )
