### ISSUE TITLE
`Remove-Item` throws "Attempted to divide by zero" on PS 7.5.0-preview.3

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#23868]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

`Remove-Item` throws `Attempted to divide by zero` on *PS 7.5.0.preview.3* when removing items from folder where some of files are empty and locked by other processes (like *VSCode*):

1. Start `VSCode` or other process that locks files in user's `LOCALAPPDATA\Temp` folder
2. `Remove-Item -Path "$env:LOCALAPPDATA\Temp\*" -Recurse -Force -ErrorAction Ignore -Verbose`

**This does not throw on PowerShell 7.4.2 or PowerShell 5.1**

### Possible cause

[I guess this might have something to do with new progress bar for Remove-Item?](https://github.com/PowerShell/PowerShell/pull/20778)

### Workaround

The error is gone when I disable the progress bar with `$ProgressPreference = 'SilentlyContinue'`

![image](https://github.com/PowerShell/PowerShell/assets/16168755/f51ecec9-bd43-4784-a50e-561f31766aa5)

### Expected behavior

```console
No error is thrown
```

### Actual behavior

```console
PS C:\> Remove-Item -Path "$env:LOCALAPPDATA\Temp\*" -Recurse -Force -ErrorAction Ignore
Remove-Item: Attempted to divide by zero.
```

### Error details

```console
Exception             :
    Type       : System.DivideByZeroException
    TargetSite :
        Name          : RemoveDirectoryInfoItem
        DeclaringType : [Microsoft.PowerShell.Commands.FileSystemProvider]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message    : Attempted to divide by zero.
    Source     : System.Management.Automation
    HResult    : -2147352558
    StackTrace :
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\namespaces\FileSystemProvider.cs:line 3124
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\namespaces\FileSystemProvider.cs:line 3073
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\namespaces\FileSystemProvider.cs:line 3073
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\namespaces\FileSystemProvider.cs:line 3073
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\namespaces\FileSystemProvider.cs:line 2904
   at System.Management.Automation.SessionStateInternal.RemoveItem(CmdletProvider providerInstance, String path, Boolean recurse, CmdletProviderContext context) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\SessionStateContainer.cs:line 1018
CategoryInfo          : NotSpecified: (:) [Remove-Item], DivideByZeroException
FullyQualifiedErrorId : System.DivideByZeroException,Microsoft.PowerShell.Commands.RemoveItemCommand
InvocationInfo        :
    MyCommand        : Remove-Item
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : Remove-Item -Path "$env:LOCALAPPDATA\Temp\*"  -Recurse -Force -ErrorAction Ignore
    Statement        : Remove-Item -Path "$env:LOCALAPPDATA\Temp\*"  -Recurse -Force -ErrorAction Ignore
    PositionMessage  : At line:1 char:1
                       + Remove-Item -Path "$env:LOCALAPPDATA\Temp\*"  -Recurse -Force -ErrorA …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Remove-Item
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.3
PSEdition                      Core
GitCommitId                    7.5.0-preview.3-20-gcdb7556d041b5db42049b39a9cf0363b5b9806a6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Animation](https://github.com/PowerShell/PowerShell/assets/16168755/dcab09bb-020b-4597-b346-698a5c02bd70)

**Comment by kborowinski** [comment]
@237dmitry  Yes, I've mentioned that PR in the issue description:
![image](https://github.com/PowerShell/PowerShell/assets/16168755/3fd4c4fa-bd87-4572-9076-aa0c189d199c)

**Comment by jborean93** [comment]
A simple reproducer is to delete a directory with a 0 byte file as `_totalBytes` will equal 0. I've got a fix so will submit a PR with the fix and a test for it.

**Comment by iSazonov** [comment]
@jborean93 FYI https://github.com/PowerShell/PowerShell/pull/19038 😄

**Comment by jborean93** [comment]
Yep that's the code I've got to fix it :) The trouble is I think there might be a race condition I need to sort out before writing the tests as the total file calculator is done in a background task so the deletion might happen before it is enumerated.

**Comment by jborean93** [comment]
Yep definite race condition there so this may or may not happen depending on the timing of when a file/folder is deleted and when it was enumerated in the size task. Unfortunately this means I can't write a consistent test for this so left it out.
