### ISSUE TITLE
Bug - PowerShell displays an error when loading in Windows Terminal

### ISSUE THREAD

**Issue by tomtaylor-kbg** [PowerShell/PowerShell#23877]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I launched Windows Terminal, and expected to see PowerShell with no errors
Launched from Windows Terminal 

### Expected behavior

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will
exit .
```

### Actual behavior

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will
exit .
```

### Error details

```console
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will
exit .
```

### Environment data

```powershell
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will
exit.
```

### Visuals

![Capture d'écran 2024-05-30 184745](https://github.com/PowerShell/PowerShell/assets/103009535/0762942e-c562-489c-92ff-091b14aa44a5)

**Comment by MartinGC94** [comment]
It looks to be referring to WinGet which is not a module that is loaded by default. Try launching powershell without a profile: `pwsh -noprofile`. If that works then you need to take a look at the commands you've added to `$profile`.

**Comment by mklement0** [comment]
@tomtaylor-kbg:

On a general note:

* When  you file a bug report, please give it a descriptive title - "Bug" isn't helpful, as it conveys no additional information beyond choosing the "Bug report" template on creation of an issue.

* Please fill in the sections of the issue template as prescribed - repeating the same information over and over isn't helpful.

Following this advice is much more likely to get your feedback to be taken seriously.

**Comment by tomtaylor-kbg** [comment]
Thanks for your help

**Comment by theJasonHelmick** [comment]
Thanks @tomtaylor-kbg for reporting this issue - it seems this is resolved. Please feel free to reopen or start a new issue if this was closed in error.
