### ISSUE TITLE
pwsh Exception not serializable anymore

### ISSUE THREAD

**Issue by frerksaxen** [PowerShell/PowerShell#23889]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

[pwsh 7.4.2]
```console
PS> try { throw "x" } catch { $_.GetType().IsSerializable }
False
```

[pwsh 7.3.1]
```console
PS> try { throw "x" } catch { $_.GetType().IsSerializable }
True
```

[Windows Powershell 5.1]
```console
PS> try { throw "x" } catch { $_.GetType().IsSerializable }
True
```

### Expected behavior

```console
PS> try { throw "x" } catch { $_.GetType().IsSerializable }
True
```

### Actual behavior

```console
PS> try { throw "x" } catch { $_.GetType().IsSerializable }
False
```

### Environment data

[pwsh 7.4.2]
```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

[pwsh 7.3.1]
```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

[Windows Powershell 5.1]
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by frerksaxen** [comment]
I just discovered that the BinaryFormatter I intendet to use to serialize the exception object should not be used. Should the IsSerializble attribute not be used anymore? 
https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide

**Comment by jborean93** [comment]
.NET has removed the BinaryFormatter in .NET 9 after it being obsoleted for a while now. It's not something you should be basing any work on as pwsh 7.5 will ship with .NET 9 and thus won't work with that approach anymore.

**Comment by frerksaxen** [comment]
Thanks @jborean93 for the explanation. I found https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide and tried XmlSerializer and DataContractSerializer to serialize the ErrorRecord object. However, I always get the error that the type 'System.Management.Automation.ErrorRecord' cannot be serialized. Is it just not possible anymore or am I missing something?
