### ISSUE TITLE
PowerShell community Power BI dashboard - Colors of Linux and MacOS are the same in graphs

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PowerShell#23883]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I randomly checked the PowerShell dashboard ( <https://aka.ms/psgithubbi> ) just now, and noticed that the colors used for Linux and MacOS in the graphs on page 1 / 4 are the exact same color of blue, at least according to my eyes.

<img width="638" alt="image" src="https://github.com/PowerShell/PowerShell/assets/6450056/585daa84-95e4-4f36-b9a9-b82181de04ae">

### Expected behavior

```console
Different colors for all OS-es measured
```

### Actual behavior

```console
Same color for multiple OS-es
```

### Environment data

```powershell
Google Chrome v125 in Guest Mode (no extensions)
```

**Comment by o-l-a-v** [comment]
I checked the closing comment of <https://github.com/PowerShell/PowerShell/issues/18897#issuecomment-1522057323> which says a new dashboard was published to <aka.ms/PSPublicDashboard>.

It seems it resolves to the same dasboard which has the exact same problem.

**Comment by SteveL-MSFT** [comment]
cc @StevenBucher98

**Comment by StevenBucher98** [comment]
Fixed
