### ISSUE TITLE
Unable to attach Visual Studio debugger to pwsh.exe process

### ISSUE THREAD

**Issue by ShortRoundDev** [PowerShell/PowerShell#23896]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

**Context**

I am creating a powershell cmdlet in C# with Visual Studio. When I try to connect the Visual Studio debugger to the pwsh.exe process with Debug > Attach to process, I receive the error message

> Unable to attach to the process. A debug component is not installed

This was possible with PowerShell 5.1. I tested with both Powershell `7.4.2` and `7.5.0-preview.3` on Windows 11 with Visual Studio 2022 17.9.6 and dotnet version 8.0.204

Perhaps here is another preferred workflow for debugging C# cmdlets, and if so, is it documented anywhere?

**Steps to reproduce**:

1. Launch Windows Terminal with powershell. Make sure all other powershell windows are closed (windows terminal tabs, vscode, etc.)
2. In Visual Studio, create a .Net 8 C# class library project to test with. No code is necessary
3. In Visual Studio, Go to `Debug > Attach to Process`
4. Search for `pwsh.exe` and select the running pwsh.exe process
5. Observe the error above

### Expected behavior

```console
Visual Studio attaches to the pwsh.exe process
```

### Actual behavior

```console
Visual Studio complains that a debug component is not installed
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.5.0-preview.3
PSEdition                      Core
GitCommitId                    7.5.0-preview.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![devenv_m34SB9obkK](https://github.com/PowerShell/PowerShell/assets/8528613/5f1f551b-3e47-4866-b441-414f60ba2cc3)

_No response_

**Comment by rhubarb-geek-nz** [comment]
> Perhaps here is another preferred workflow for debugging C# cmdlets..

When developing Cmdlets I prefer to use test-driven-development and write Unit tests for the cmdlets. These can be debugged using the "Test Explorer".

Example of a [solution with unit tests](https://github.com/rhubarb-geek-nz/ScriptBlock) that test a couple of cmdlets with PowerShell 5.1, 7.2, 7.3 and 7.4 all from within the test explorer.

**Comment by ShortRoundDev** [comment]
@rhubarb-geek-nz are you able to connect the debugger to the underlying assembly that way? Can you place breakpoints within the cmdlet source code and step into them? I'm looking to place breakpoints and be able to step through the source code line by line

**Comment by rhubarb-geek-nz** [comment]
> @rhubarb-geek-nz are you able to connect the debugger to the underlying assembly that way? Can you place breakpoints within the cmdlet source code and step into them? I'm looking to place breakpoints and be able to step through the source code line by line

Absolutely, I put the breakpoint in the code using the "Solution Explorer" in the IDE, then select the test case within the Test Explorer and select Debug.

This means the test case can already set up the scenario and input data, and validate the output data. So you can repeatedly debug exactly the same scenario.

**Comment by ShortRoundDev** [comment]
@rhubarb-geek-nz Thanks for your help, I'll check out your repo and give it a try!

**Comment by MartinGC94** [comment]
The attach to process method is what I normally use. I don't remember having to do anything special to set it up, it just worked out of the box. Maybe try launching PowerShell in the normal consolehost? I don't use the new Windows Terminal because I don't like how slow it is.

**Comment by ShortRoundDev** [comment]
@rhubarb-geek-nz I was able to get breakpoints working in an xunit project with Visual Studio 2022 using your example, thanks so much for your help!
