### ISSUE TITLE
Document RequireAdminOnWindows in tests

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2389]
This is a follow-up from PR #2280 and Windows counter-part #1486

We should
- [x] implement similar test mechanic and separation for Unix
- [ ] document this design in our test docs

**Comment by vors** [comment]
@andschwa does `sudo: required` in `.travis.yml` means that when you need `sudo` you should specify it explicitly in the commands?

**Comment by andschwa** [comment]
I'm not sure what you mean... `sudo: required` requests an image from Travis CI that allows you to use passwordless sudo. Moreover, it is required to request the Trusty (Ubuntu 14.04) image. See [here](https://docs.travis-ci.com/user/trusty-ci-environment/).

**Comment by vors** [comment]
Ok, then as far as I see, we already run tests in Travis CI unelevated. Correct?

**Comment by andschwa** [comment]
Correct. I do not see any Pester tests that call sudo, and we don't start the PowerShell process with sudo.

**Comment by vors** [comment]
Sweet, then we just need to document windows side of the things.

**Comment by vors** [comment]
Hm, I conveniently already covered it in https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/WritingPesterTests.md#admin-privileges-in-tests
