### ISSUE TITLE
New-AzureRmRoleAssignment : Cannot access a closed Stream.

### ISSUE THREAD

**Issue by jlaherran** [PowerShell/PowerShell#2391]
Steps to reproduce
------------------
Run New-AzureRmRoleAssignment providing the signInName, Owner as built in RoleDefinitionName and the subscription id '/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' in the scope.

Expected behavior
-----------------
Role assignment successful

Actual behavior
---------------
```
New-AzureRmRoleAssignment : Cannot access a closed Stream.
At /root/Azure-Roles-Demo.ps1:20 char:1
+ New-AzureRmRoleAssignment -SignInName $signInName -RoleDefinitionName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleAssignment], ObjectDisposedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

```

Environment data
----------------
CentOS Linux release 7.2.1511 (Core)

Name | Value
----                |               -----
PSVersion       |               6.0.0-alpha
PSEdition       |               Core
PSCompatibleVersions    |       {1.0, 2.0, 3.0, 4.0...}
BuildVersion        |           3.0.0.0
GitCommitId        |            v6.0.0-alpha.10
CLRVersion |
WSManStackVersion        |      3.0
PSRemotingProtocolVersion  |    2.3
SerializationVersion      |     1.1.0.1

**Comment by vors** [comment]
This problem should be reported on https://github.com/Azure/azure-powershell

**Comment by jlaherran** [comment]
This issue https://github.com/PowerShell/PowerShell/issues/2288 is also about a cmdlet, should be also moved?

Thanks.
