### ISSUE TITLE
install-powershell.sh doesn't work on azure-linux

### ISSUE THREAD

**Issue by dpoole73** [PowerShell/PowerShell#23944]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I deployed a virtual machine in azure specifying:

publisher: MicrosoftCBLMariner
offer: azure-linx
sku: azure-linux-gen2

when I ran the install script, it failed saying it was an unsupported os:

`Sorry, your operating system is based on  and is not supported by PowerShell or this installer at this time`

### Expected behavior

```console
pwsh is installed
```

### Actual behavior

```console
pswh installation fails with error:

Sorry, your operating system is based on  and is not supported by PowerShell or this installer at this time
```

### Error details

```console
Sorry, your operating system is based on  and is not supported by PowerShell or this installer at this time
```

### Environment data

```powershell
N/A
```

**Comment by kasini3000** [comment]
https://gitee.com/chuanjiao10/kasini3000_agent_linux#microsoft-azurelinux-20-kernel515

**Comment by bosesubham2011** [comment]
Hey,
Can you please run the code like this in the azure linux console and let me know the output?

OS=$(lowercase "$(uname)")
echo ${OS}

**Comment by bosesubham2011** [comment]
My best guess is the above statement doesn't work in Azure linux. Maybe it misses lowercase command and it is failing at that level. I will put a PR, if you can confirm me the output of ${OS}

**Comment by dpoole73** [comment]
yes it seems the base image is missing `lowercase`:

```bash
adminUsername@vm [ ~ ]$ OS=$(lowercase "$(uname)")
-bash: lowercase: command not found
adminUsername@vm [ ~ ]$ echo ${OS}
```
FYI

`uname` returns `Linux`

`cat /etc/os-release` returns
```bash 
NAME="Microsoft Azure Linux"
VERSION="3.0.20240524"
ID=azurelinux
VERSION_ID="3.0"
PRETTY_NAME="Microsoft Azure Linux 3.0"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/azurelinux"
BUG_REPORT_URL="https://aka.ms/azurelinux"
SUPPORT_URL="https://aka.ms/azurelinux"
```

**Comment by dpoole73** [comment]
i think the script will need to be updated to check for /etc/azurelinux-release

**Comment by bosesubham2011** [comment]
Which is what I thought! So, thanks for confirming.

So, a simple if and else statement should be brought in to the code to check for the presence of lowercase command.

I will push the fix via a PR.

**Comment by bosesubham2011** [comment]
Yes, it is certain that there is no support for Microsoft Azure Linux.

**Comment by bosesubham2011** [comment]
I might be completely off, but this was a quick and easy solution to try and implement.

https://github.com/PowerShell/PowerShell/pull/23955

This is a PR that I have raised to fix the issue, maybe.

**Comment by dpoole73** [comment]
I tested with your changes and it didn't work, here is the error:

```bash
Get-PowerShell MASTER Installer Version 1.2.0
Installs PowerShell and Optional The Development Environment
  Original script is at: https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools\install-powershell.psh
Arguments used:

Operating System Details:
  OS: linux
  DIST:
  DistroBasedOn: mariner
  PSUEDONAME: Azure Linux 3.0
AZURELINUX_BUILD_NUMBER=3.0.20240524
  REV: Azure
AZURELINUX_BUILD_NUMBER=3.0.20240524
  KERNEL: 6.6.29.1-3.azl3
  MACH: x86_64
  OSSTR:
Configuring PowerShell Environment for: mariner  Azure
AZURELINUX_BUILD_NUMBER=3.0.20240524
Could not find "installpsh-mariner.sh" next to this script...
Pulling and executing it from "https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/installpsh-mariner.sh"
found and using curl

*** PowerShell Development Environment Installer 1.2.0 for mariner
***    Original script is at: https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/installpsh-mariner.sh

*** Arguments used:

*** This installer is only for mariner and you are running , please run "https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools\install-powershell.sh" to see if your distro is supported AND to auto-select the appropriate installer if it is.
```

**Comment by daxian-dbw** [comment]
> I deployed a virtual machine in azure specifying:
>
> publisher: MicrosoftCBLMariner
> offer: azure-linx
> sku: azure-linux-gen2

@dpoole73 Can you share the details steps to create an Azure VM with the `azure-linux` image? I cannot find the image when creating a VM in Auzre Portal. The https://github.com/microsoft/azurelinux says the `azurelinux` is _an internal Linux distribution for Microsoft’s cloud infrastructure and services_. If so, the image won't be public, right?

**Comment by dpoole73** [comment]
oh I didn't realize it was an internal image.  I am using an internal microsoft subscription so likely it shows up for me but not for you.  I'm trying to install powershell on it so that I can validate the image for testing. I guess mariner got rebranded to azure-linux so I'm guessing this is just the latest image and will be available going forward?
