### ISSUE TITLE
PowerShell manifest `Description` is not being output by `Get-Module`

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PowerShell#23954]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using this manifest file (excerpt):

```
@{
  RootModule = 'MyPSModule.dll'
  ModuleVersion = '1.0'
  Description = 'This is my personal description.'
  PowerShellVersion = '7.4'
  CompatiblePSEditions = @('Core')
  FunctionsToExport = @('New-Something')
  AliasesToExport = @('nst')
  VariablesToExport = @('')
}
```

… after importing my binary module using `Import-Module .\MyPSModule.dll`, `(Get-Module MyPSModule).Description` yields an empty string.

### Expected behavior

`(Get-Module MyPSModule).Description` should yield: "This is my personal description."

### Actual behavior

`(Get-Module MyPSModule).Description` yields: "".

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
You need to import the module as a whole, typically by folder name (`Import-Module MyPSModule`) or by explicitly importing the module manifest (`*.psd1`), not just the binary root module (`*.dll`), which doesn't know about the manifest metadata.

**Comment by SetTrend** [comment]
Ah, I see … Thanks a lot for enlightening me! 😊👍
