### ISSUE TITLE
System.TypeInitializationException in PowerShell 7.4.3 / arm64

### ISSUE THREAD

**Issue by riverar** [PowerShell/PowerShell#23969]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Install PowerShell 7.4.3 on arm64 machine
2. Observe error at launch

### Expected behavior

```console
No error
```

### Actual behavior

```console
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Configuration.PowerShellConfig' threw an exception.
 ---> System.BadImageFormatException: Could not load file or assembly 'C:\Program Files\PowerShell\7\Newtonsoft.Json.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'C:\Program Files\PowerShell\7\Newtonsoft.Json.dll'
   at System.Management.Automation.Configuration.PowerShellConfig..ctor()
   at System.Management.Automation.Configuration.PowerShellConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Utils.GetPolicySettingFromConfigFile[T](ConfigScope[] preferenceOrder)
   at System.Management.Automation.Utils.GetPolicySetting[T](ConfigScope[] preferenceOrder)
   at Microsoft.PowerShell.CommandLineParameterParser.GetConfigurationNameFromGroupPolicy()
   at Microsoft.PowerShell.ConsoleHost.ParseCommandLine(String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
   at Microsoft.PowerShell.ManagedPSEntry.Main(String[] args)
```
```


### Error details

```console
Not available
```

### Environment data

```powershell
Not available
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/475132/5b935a20-803e-4d0d-a6f3-ae57611da854)

**Comment by riverar** [comment]
Disregard, somehow x64 and arm64 copies of PowerShell got onto the box. Removed both and installed arm64 fresh.

**Comment by zrivkis** [comment]
> Disregard, somehow x64 and arm64 copies of PowerShell got onto the box. Removed both and installed arm64 fresh.

Ran into the same issue today as well, and while I did uninstall the x64 ver, I didn't uninstall arm64 and reinstall it until I read your post. Saved me a lot of frustration, thank you!
