### ISSUE TITLE
v7.4.3 SHA256 hashes don't match for some artifacts

### ISSUE THREAD

**Issue by tlgDJPorv** [PowerShell/PowerShell#23975]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The hashes file for the v7.4.3 release seems to be wrong for some artifacts.

Steps to reproduce:

```bash
curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/powershell-7.4.3-linux-x64.tar.gz -o powershell-7.4.3-linux-x64.tar.gz
curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/PowerShell-7.4.3-win-x64.zip -o PowerShell-7.4.3-win-x64.zip
curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/hashes.sha256 -o hashes.sha256
sha256sum -c --ignore-missing hashes.sha256 
```

### Expected behavior

```console
powershell-7.4.3-linux-x64.tar.gz: OK
PowerShell-7.4.3-win-x64.zip: OK
```

### Actual behavior

```console
powershell-7.4.3-linux-x64.tar.gz: FAILED
PowerShell-7.4.3-win-x64.zip: OK
sha256sum: WARNING: 1 computed checksum did NOT match
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Debian GNU/Linux 12 (bookworm)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by pamelafox** [comment]
I think we are seeing this cause failures to build the Powershell devcontainer feature. Here's what I see in the logs:

2024-06-21 22:13:40.237Z: #18 2.966 POWERSHELL_VERSION=7.4.32024-06-21 22:13:40.239Z: 
2024-06-21 22:13:41.785Z: #18 4.515 SHA256: 3ae8f3a556fd7e14fecefaacf15f5cfb0afab520b6f1aeae796d2eeafc9b64222024-06-21 22:13:41.787Z: 
2024-06-21 22:13:42.064Z: #18 4.792 sha256sum: WARNING: 1 computed checksum did NOT match
2024-06-21 22:13:42.213Z: #18 4.792 powershell-7.4.3-linux-x64.tar.gz: FAILED

**Comment by tlgDJPorv** [comment]
It was also while building one of our devcontainers that led me to create this issue.  
The workaround was to pin to 7.4.2, there the SHA for the linux x64 release matches.

```jsonc
// .devcontainer/devcontainer.json
{
// snip
    "features": {
        "ghcr.io/devcontainers/features/powershell:1": {
            "version": "7.4.2" // Specific version until SHA's are fixed
        }
// snip
    }
}
```

**Comment by sliekens** [comment]
Hi,

This issue impacts everyone using the PowerShell dev container feature, as it uses the SHA256 sums from the release notes to verify the download. 

This sum is incorrect:

```
powershell-7.4.3-linux-x64.tar.gz
3ae8f3a556fd7e14fecefaacf15f5cfb0afab520b6f1aeae796d2eeafc9b6422
```

It should be:

```
5cfcc228afd3ffce536ec4541abafe97c629afcd6dc85c9a20712894bbf65adb
```

Please adjust the release notes @daxian-dbw

**Comment by scott-brady** [comment]
FYI @sliekens @daxian-dbw 

Noting that it might be more than just the `powershell-7.4.3-linux-x64.tar.gz` file with the wrong sum. 

I'm getting the PS dev container issue on an M1 MacBook for the `powershell-7.4.3-linux-arm64.tar.gz` file i.e.:

```
3.643 POWERSHELL_VERSION=7.4.3
7.530 SHA256: 6ba8ae0dedabbbfd4bf4a8f48d8819ec504ef092d4c3df120ff6565e542e39b1
7.771 powershell-7.4.3-linux-arm64.tar.gz: FAILED
7.771 sha256sum: WARNING: 1 computed checksum did NOT match
7.771 ERROR: Feature "PowerShell" (ghcr.io/devcontainers/features/powershell) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/powershell for help troubleshooting this error.
```

**Comment by adityapatwardhan** [comment]
Updated the hashes file with the correct hashes.

**Comment by iSazonov** [comment]
Why not add tests in release process to check the hashes before publish?

**Comment by pdrew-tessitura** [comment]
The `hashes.sha256` file is missing from the v7.4.3 release downloads, could you please let me know if this is expected? It's absence is breaking one of our automations:

`WebDownload: [ ERROR ] Operation could not be completed due to error - Source https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/hashes.sha256, Destination C:\Windows\TEMP\pwsh-hashes256.txt, Error failed to download source https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/hashes.sha256 after 5 retries - Error received HTTP status code 404 for source https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/hashes.sha256 with HEAD request. Cannot download resource`

**Comment by FlorianAlbert** [comment]
Now the `hashes.sha256` is there again, but it seems like it is malformed. I get the following error:
`File name 'PowerShell-7.4.3-win-x64.msi' not found in checksum file.`

When looking at the raw file contents it looks like the file endings are missing.

**Comment by ardole** [comment]
+1 `hashes.sha256` is malformed, file endings are missing

```
...
57342b7b9aca6c53b27ee40a307e8fc5dc28b97218bfd016c7941ce25621f79b *PowerShell-7.4.3-win-x64
64b4a0636a2af4854b90593ac78645bb59f86b4d094f75b41a5a617afd2478d3 *PowerShell-7.4.3-win-x64
...
```

**Comment by adityapatwardhan** [comment]
Updated again. Please verify.

**Comment by FlorianAlbert** [comment]
@adityapatwardhan Works now! 👍

**Comment by tlgDJPorv** [comment]
Confirmed. Works now.  
Devcontainers can again use powershell feature with version set to latest (which is default).
