### ISSUE TITLE
Invoke-Command Command not able to connect to Azure VM

### ISSUE THREAD

**Issue by dsm4u** [PowerShell/PowerShell#23994]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

We are trying to execute the poweshell Invoke-Command command to connect to the Azure VM using the script below but getting the error message:
WinRM ports for the VM are added to NSG inbound rules (5985, 5986). No firewall rules are set in the VM.

Invoke-Command `
		-ComputerName $IpName `
		-Credential $cred `
		-UseSSL `
		-SessionOption $SessionOptions `
		-ScriptBlock { `
			param($ServiceDisplayName) 
			Stop-Service -displayname $ServiceDisplayName
			} `
		-ArgumentList "Xerox DCE Shell" 

The error message received is as below:
Connecting to remote server ******** failed with the following error message : WinRM cannot complete 
the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that 
a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall 
exception for public profiles limits access to remote computers within the same local subnet. For more information, see the 
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (*********:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : WinRMOperationTimeout,PSSessionStateBroken

### Expected behavior

```console
The error message received is as below:
Connecting to remote server ******** failed with the following error message : WinRM cannot complete 
the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that 
a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall 
exception for public profiles limits access to remote computers within the same local subnet. For more information, see the 
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (*********:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : WinRMOperationTimeout,PSSessionStateBroken
```

### Actual behavior

```console
Should get connected to VM.
```

### Error details

```console
The error message received is as below:
Connecting to remote server ******** failed with the following error message : WinRM cannot complete 
the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that 
a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall 
exception for public profiles limits access to remote computers within the same local subnet. For more information, see the 
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (*********:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : WinRMOperationTimeout,PSSessionStateBroken
```

### Environment data

```powershell
Azure
```

**Comment by kasini3000** [comment]
### enable powershell script on win controlled machine,see:
https://gitee.com/chuanjiao10/kasini3000/blob/master/node_script/k%E5%BC%80%E5%90%AF%E6%9C%AC%E6%9C%BApowershell%E8%84%9A%E6%9C%AC%E6%89%A7%E8%A1%8C%E6%9D%83%E9%99%90.bat


### enable winrm see：
https://gitee.com/chuanjiao10/kasini3000/blob/master/bkj_install_k%E8%AE%B0%E9%A5%AD%E5%BA%97_win%E8%A2%AB%E6%8E%A7%E6%9C%BA.ps1

### how to connetc to winrm from client see：
https://gitee.com/chuanjiao10/kasini3000/blob/master/run_win2win5985_pwd.ps1

**Comment by dsm4u** [comment]
We have enabled winrm and powershell script is also enables.. winrm service is up and running in the vm.

**Comment by kasini3000** [comment]
Run the script 1 ，2 above. You can use a new Win10, or Win11 virtual machine for testing,
after setup winrm，use：
k_run_ip.port_w2w_user_pwd. ps1       
--- This is a standalone script, which means you need to enter a username and password. 
It has been proven to be error free.

**Comment by dsm4u** [comment]
We are using windows 2016 datacenter vm.. can you please advise what these scripts do?

**Comment by kasini3000** [comment]
as far as I am concerned:
Win2016 has enabled the ps-remote feature by default and does not require any settings.
```powershell
c:\ProgramData\kasini3000\tcp--ping-v5.ps1 win2016_ipv4_oripv6 5985

c: \ProgramData\kasini3000\k_run_ip.port_w2w_user_pwd.ps1  -ip '192.168.168.232' -user 'youname' -pwd 'xxx ' -scriptblock { dir d: \ | out string }
```

**Comment by dsm4u** [comment]
Thanks! Can you please advise what these script thus. And any other suggestions to fix this issue?

**Comment by kasini3000** [comment]
https://gitee.com/chuanjiao10/kasini3000/blob/master/k_run_ip_port_w2w_user_pwd.ps1

https://gitee.com/chuanjiao10/kasini3000/blob/master/tcp--ping-v5.ps1    # I will release v6 in a few days

win：
```
Remove-Item -Force -LiteralPath 'c:\ProgramData\kasini3000' #备份后，删除旧版
cd C:\ProgramData
git clone https://gitee.com/chuanjiao10/kasini3000.git
```



linux：
```
Remove-Item -Force -LiteralPath '/etc/kasini3000' #备份后，删除旧版
cd /etc
git clone https://gitee.com/chuanjiao10/kasini3000.git
```

**Comment by SteveL-MSFT** [comment]
The default firewall rules only permit incoming traffic to WinRM for private networks.  Note that this issue is not related to this repo and any additional support should go through Azure support.
