### ISSUE TITLE
import module in linux

### ISSUE THREAD

**Issue by usmarine2141** [PowerShell/PowerShell#2399]
I downloaded a ps1 module and i am not able to import the module into. Can you provide steps to import. below is what i am attempting to import for testing.

https://github.com/dafthack/MailSniper

Steps to reproduce
------------------

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by Jaykul** [comment]
That's a script (.ps1) not a module (.psm1). 
 
Either dot-source it, to import the functions to your current scope:

```posh
. .\MailSniper.ps1
```

Or rename it to .psm1 and then `import-module .\MailSniper.psm1`

**Comment by usmarine2141** [comment]
Ahhh okay thank you!

**Comment by usmarine2141** [comment]
I tried both ways to no avail.

**Comment by vors** [comment]
What is the error when you dot-sourcing?

**Comment by usmarine2141** [comment]
PS /root> . .\MailSniper.ps1                                                    
. : The term '.\MailSniper.ps1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ . .\MailSniper.ps1
+   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\MailSniper.ps1:String) [], Co 
   mmandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS /root> . .\MailSniper.psm1                                                   
. : The term '.\MailSniper.psm1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ . .\MailSniper.psm1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\MailSniper.psm1:String) [], C 
   ommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS /root> .\MailSniper.psm1                                                     
.\MailSniper.psm1 : The term '.\MailSniper.psm1' is not recognized as the name 
of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ .\MailSniper.psm1
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\MailSniper.psm1:String) [], C 
   ommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by usmarine2141** [comment]
if i am in the directory and do the following i get this

PS /root/MailSniper> ./MailSniper.psm1                                          
PS /root/MailSniper> 


PS /root/MailSniper> Import-Module ./MailSniper.psm1                            
PS /root/MailSniper>

**Comment by usmarine2141** [comment]
Disregard. I got it to work now. Sorry for the trouble!

**Comment by EkremSel** [comment]
@usmarine2141 Im having the same trouble. I got it to work when i cd into the directory. But other than than it does not recognize it.

**Comment by kilasuit** [comment]
@EkremSel - you need to be in the directory where this is downloaded for you to be able to import scripts into your session which is a standard behaviour (since PowerShell v1)
 
The exception to this is if you have a PowerShell Module in one of the paths that is in the PSModulePath environmental variable then you can call `Import-Module <Module Name>`

**Comment by EkremSel** [comment]
Thanks 

Sezai Ekrem SELAH 
Selah Shipbuilding and Repair Co. 
Member of Board 
www.selahshipyard.com
