### ISSUE TITLE
ARM64 Powershell Microsoft Office COM invocation fails when running elevated

### ISSUE THREAD

**Issue by IRQL-NOT-LESS-OR-EQUAL** [PowerShell/PowerShell#24005]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The following command will fail when executed under an elevated (admin) PowerShell ARM64 session:

**$excel = New-Object -Com Excel.Application**

To reproduce:

1. Install the ARM64 version of Office (18.2405.1221.0) on an ARM64 release of Windows (26100)
2. Install the ARM64 flavor of PowerShell 7 (7.4.3) using the zip extraction installation process
3. Launch pwsh.exe as admin
4. Exec the command **$excel = New-Object -Com Excel.Application**

On an ARM64 Windows Device: 

ARM64 pwsh.exe run as admin --> Repro
ARM64 pwsh.exe run non-elevated --> No-repro
X64 pwsh.exe run as admin --> No-repro
X64 pwsh.exe run non-elevated --> No-repro 

### Expected behavior

```console
The command successfully creates an Excel application session through COM
```

### Actual behavior

```console
The Excel application fails to initialize and a COM error is returned.
```

### Error details

```console
When this error occurs, a dialog with the following message is displayed:

Error: The operating system is not presently configured to run this application.

After dismissing this dialog, the follow error is returned through the PowerShell session (after ~30 seconds):

New-Object: Retrieving the COM class factory for component with CLSID {00024500-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
```

### Environment data

```powershell
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
Tested on the same version of ARM64 Office, on Window Dev Kit 2023 but with PowerShell 7.2.21 and had no issues with either normal user or admin mode, PowerShell 5.1 or PowerShell 7.2.21. No problems on x64 machine either.

```
trap
{
	throw $PSItem
}

$ErrorActionPreference = 'Stop'

$excel = New-Object -Com Excel.Application
try
{
	$excel.Version
}
catch
{
	$excel.Quit()
}
```

In all cases the result was 

```
16.0
```

Suggest confirm if problem is within COM server activation rather than PowerShell. Suggest confirm behaviour with simple ARM64 C++ application using CoInitializeEx(), CLSIDFromProgId() and CoCreateInstance().

**Comment by rhubarb-geek-nz** [comment]
Quick test using C# and reflection

Works both as admin and normal user on ARM64

```
using System;
using System.Reflection;
using System.Runtime.InteropServices;

Type type = Type.GetTypeFromProgID("Excel.Application");

Object obj = Activator.CreateInstance(type);

try
{
    var result = type.InvokeMember("Version", BindingFlags.Public | BindingFlags.Instance | BindingFlags.GetProperty, null, obj, new object[0]);

    Console.WriteLine($"{result}");
}
finally
{
    type.InvokeMember("Quit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.InvokeMethod, null, obj, new object[0]);
}
```

**Comment by IRQL-NOT-LESS-OR-EQUAL** [comment]
Hi rhubarb-geek-nz,

Thank-you for attempting to repro. Further testing indicates that this might be Windows 24H2 (26100.1) specific, as I was unable to reproduce on a 23H3 (22631.2428) install.

I’ll give the simple ARM64 c++ app suggestion a try.

**Comment by rhubarb-geek-nz** [comment]
> I’ll give the simple ARM64 c++ app suggestion a try.

A C++ version would be

```
#include <objbase.h>
#include <stdio.h>

static HRESULT invoke(IDispatch* dispatch, LPCOLESTR str, WORD flags)
{
	LCID lcid = GetUserDefaultLCID();
	BSTR names[] = { SysAllocString(str) };
	DISPID dispid[sizeof(names) / sizeof(names[0])];
	UINT ui = sizeof(names) / sizeof(names[0]);
	HRESULT hr = dispatch->GetIDsOfNames(IID_NULL, names, ui, lcid, dispid);

	if (SUCCEEDED(hr))
	{
		UINT argErr = 0;
		VARIANT result;
		DISPPARAMS params;
		EXCEPINFO exinfo;
		ZeroMemory(&params, sizeof(params));
		ZeroMemory(&exinfo, sizeof(exinfo));
		VariantInit(&result);

		hr = dispatch->Invoke(dispid[0], IID_NULL, lcid, flags, &params, &result, &exinfo, &argErr);

		if (SUCCEEDED(hr))
		{
			if (result.vt == VT_BSTR)
			{
				printf("%S\n", result.bstrVal);
			}
		}

		VariantClear(&result);
	}

	while (ui--)
	{
		SysFreeString(names[ui]);
	}

	return hr;
}

int main(int argc,char **argv)
{
	HRESULT hr = OleInitialize(NULL);

	if (SUCCEEDED(hr))
	{
		CLSID clsid;
		BSTR bstr = SysAllocString(L"Excel.Application");
		hr = CLSIDFromProgID(bstr, &clsid);
		SysFreeString(bstr);

		if (SUCCEEDED(hr))
		{
			IDispatch* dispatch = NULL;

			hr = CoCreateInstance(clsid, NULL, CLSCTX_LOCAL_SERVER, IID_IDispatch, (void**)&dispatch);

			if (SUCCEEDED(hr))
			{
				hr = invoke(dispatch, L"Version", DISPATCH_PROPERTYGET);

				hr = invoke(dispatch, L"Quit", DISPATCH_METHOD);

				dispatch->Release();
			}
		}

		OleUninitialize();
	}

	return SUCCEEDED(hr) ? 0 : 1;
}
```

**Comment by IRQL-NOT-LESS-OR-EQUAL** [comment]
Thanks – that was incredibly helpful!

The test app did not reproduce the problem.

It looks like there were a lot of changes in combase.dll between 23H2 and 24H2. I’m reaching out to the owners of that module to see if they can help figure out what might be going on here.

**Comment by IRQL-NOT-LESS-OR-EQUAL** [comment]
This appears to be an app compat shimming issue that is tripping up Excel (and other Office Apps).

If the Excel process is created with the environment variable __COMPAT_LAYER set to “Installer”, then the problematic app compat shims will be added during CreateProcess. The Excel process is inheriting the environment variables from pwsh via the COM instantiation.

Pwsh.exe appears to only have this variable set when launched from Explorer as elevated, and only on the ARM64 version of pwsh (isn’t present on the x64 version of pwsh.exe). It is also not present when pwsh is launched from an elevated ARM64 cmd.exe.

Removing __COMPAT_LAYER from the pwsh.exe process before invoking the Office applications via COM works around the problem. I’ll reach out to the Windows AppCompat team to see how this should be fixed.

From: Timothy Davis
Sent: Wednesday, July 3, 2024 10:25 AM
To: 'PowerShell/PowerShell' ***@***.***>; PowerShell/PowerShell ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [PowerShell/PowerShell] ARM64 Powershell Microsoft Office COM invocation fails when running elevated (Issue #24005)

Thanks – that was incredibly helpful!

The test app did not reproduce the problem.

It looks like there were a lot of changes in combase.dll between 23H2 and 24H2. I’m reaching out to the owners of that module to see if they can help figure out what might be going on here.

**Comment by IRQL-NOT-LESS-OR-EQUAL** [comment]
Closing issue as this appears to be a Microsoft appcompat shimming issue and not an issue with PowerShell. 

Windows OS bug 52322413 is tracking the appcompat work to address this issue.
