### ISSUE TITLE
Integer literals in function arguments in non-decimal base are treated as strings by `-f`

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PowerShell#24018]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
function bin($n) {
	if ($n -is [int]) {
		"{0:b}" -f $n # $n is [int], so it should be formatted in binary
	}

	if ($n -is [int]) {
		"{0:b}" -f [int]$n # the same, but we explicitly cast it
	}
}

bin 0x10
```

### Expected behavior

```console
10000
10000
```

### Actual behavior

```console
0x10
10000
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.3
PSEdition                      Core
GitCommitId                    7.5.0-preview.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
This problem has been reported before, but was - unfortunately - declared to be by design:

* #17199

Related issue with _arrays_:

* #14355

The issue at hand is but one of many problems related to incidental `[psobject]` wrappers, summarized in:

* #5579

**Comment by MatejKafka** [comment]
You're right, thanks for the references.
