### ISSUE TITLE
Environment variable `%PROGRAMFILES%` for `cmd` expanded incorrectly to `C:\Program Files (x86)`

### ISSUE THREAD

**Issue by Diogo-Rossi** [PowerShell/PowerShell#24021]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

---

### Steps to reproduce

In **v7.4.3:**
When running a `.bat` file inside PowerShell the environment variable `%PROGRAMFILES%` is not expanded to `C:\Program Files\` but incorrectly to `C:\Program Files (x86)\`

In **previous version (7.4.2), it works ok**, i.e., expands to `C:\Program Files\` 

In `cmd`, it works ok, i.e., expands to `C:\Program Files\` .

### Expected behavior

```console
PS> cmd /c "echo %PROGRAMFILES%"
C:\Program Files
```

### Actual behavior

```console
PS> cmd /c "echo %PROGRAMFILES%"
C:\Program Files (x86)
```

### Environment data

```powershell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
Not on 7.4.3 here
![image](https://github.com/PowerShell/PowerShell/assets/16209593/5e7e8528-676f-4b53-bdc9-fb01c1751196)

Have you somehow managed to install the 32 bit instead of 64bit PowerShell ?

**Comment by Diogo-Rossi** [comment]
> Have you somehow managed to install the 32 bit instead of 64bit PowerShell ?

Yesss, that was the problem. Sorry, my bad 😢.
