### ISSUE TITLE
Select-String line number overflows

### ISSUE THREAD

**Issue by Snowman-25** [PowerShell/PowerShell#24027]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using 'Select-String' on extremly big files can return negative line numbers. I've tested this with rockyou2024.txt, which has roughly 10 billion lines.

### Expected behavior

```console
The beginning looks fine (line numbers have been partly anonymized):

PS H:\FFDownloads> Select-String -Path .\rockyou2024.txt -SimpleMatch:$true -Pattern "[redacted]"

rockyou2024.txt:35x7454:[redacted]
rockyou2024.txt:373x742:[redacted]
rockyou2024.txt:22835x658:[redacted]
rockyou2024.txt:94x240763:[redacted]
```

### Actual behavior

```console
Excerpt from the middle, where multiple overflows happen:

rockyou2024.txt:-16155x8268:[redacted]
rockyou2024.txt:-16155x8252:[redacted]
rockyou2024.txt:-1615x88255:[redacted]
rockyou2024.txt:-8271632x7:[redacted]
rockyou2024.txt:-82716xx70:[redacted]
rockyou2024.txt:13197x054:[redacted]
rockyou2024.txt:1319871x7:[redacted]
rockyou2024.txt:1113x02014:[redacted]
rockyou2024.txt:11133x5056:[redacted]
rockyou2024.txt:111348x182:[redacted]
rockyou2024.txt:1594956x68:[redacted]
rockyou2024.txt:176566x256:[redacted]
rockyou2024.txt:18529x8022:[redacted]
rockyou2024.txt:1936742839:[redacted]
rockyou2024.txt:-2079296217:[redacted]
rockyou2024.txt:-2079092911:[redacted]
rockyou2024.txt:-2079088x42:[redacted]
```

### Environment data

```powershell
PS H:\FFDownloads> $PSVersionTable | clip

Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by u20221022** [comment]
2³¹ = 2147483648 (or 2 147 483 648)
Does have an overflow the «Get-Content»?

**Comment by IISResetMe** [comment]
Makes sense, `Select-String` uses a signed 32-bit integer to track the line number:

https://github.com/PowerShell/PowerShell/blob/dcf67544451425c98580d79a8381e9a07775c86d/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L83

**Comment by Snowman-25** [comment]
> Makes sense, `Select-String` uses a signed 32-bit integer

I don't see a reason why it shouldn't be a 64Bit unsigned Int.
There can't exist negative linenumbers

**Comment by Snowman-25** [comment]
FYI: I'm working on a fix
