### ISSUE TITLE
Resolve-Path whilst in a PSDrive doesnt return the full (non-relative to PSDrive) path 

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#2403]
When in a script or interactive use and you have defined a PSDrive as a shortlink to another location on the same disk Resolve-Path returns the PSDrive relative file path whereas I think that it should be able to return the actual full file path instead similarly to how Get-Item returns the non-relative PSDrive path and shows this correctly under the PSPath & Fullname properties 
## Steps to reproduce

Create new PSDrive to C:\temp folder - `New-PSDrive -Name CT -Root C:\temp -Provider FileSystem`
Create file test.txt in C:\temp folder - `New-Item C:\temp\test.txt`
cd to the PSDrive -`Set-location CT:\`
Run `Resolve-Path test.txt`
## Expected behavior

Resolve-Path returns the full path to the file so output should be `C:\temp\test.txt`
## Actual behavior

Resolve-Path returns the PSDrive relative path so it returns `CT:\test.txt`
## Environment data

``` powershell

Name                           Value                                                                                                                                                                      
----                           -----                                                                                                                                                                      
PSVersion                      5.1.14393.187                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                    
BuildVersion                   10.0.14393.187                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                                                    
```

**Comment by joeyaiello** [comment]
Unless we add a new, opt-in parameter, this is a breaking change that would require a (brief) Committee vote.

**Comment by mklement0** [comment]
I don't think a change is warranted:

Remember that `Resolve-Path` :

* makes no promises of returning a _provider-native_ path  - that's what `Convert-Path` is for.

* returns `[System.Management.Automation.PathInfo]` instances that _also_ contain the provider-native path.

Thus, to get what you want - a provider-native absolute path _string_ - all you need to do is:

```powershell
> Convert-Path test.txt
C:\temp\test.txt
```

which is effectively the same as:

```powershell
> (Resolve-Path test.txt).ProviderPath
C:\temp\test.txt
```

**Comment by joeyaiello** [comment]
@mklement0 yeah, I'm good with that. `Convert-Path` works just fine on all platforms.

**Comment by kilasuit** [comment]
Didn't think to use Convert-Path at the time - thanks @mklement0 for mentioning this and reminding me :-)
