### ISSUE TITLE
[Feature Request] Active Directory Snap-In for Mac Powershell

### ISSUE THREAD

**Issue by c0dyhi11** [PowerShell/PowerShell#2404]
Powershell team,
Thanks for porting Powershell to *nix!

Not sure where else to submit feature requests...
But I'd like to be able to manage Active Directory without having to RDP into a windows machine.
Specifically I need to be able to manage users and groups (Set-ADUser, Get-ADUser, Set-ADGroup, Get-ADGroup. Etc...)

Thank you,
Cody Hill

**Comment by joeyaiello** [comment]
The GitHub Issues on this project are specific to PowerShell itself. I encourage you to reach out to the Active Directory team via their UserVoice forums: https://windowsserver.uservoice.com/forums/304621-active-directory

Also note, we don't currently plan on supporting snap-ins on Mac, so you'll likely be looking for a PowerShell *module* instead.
