### ISSUE TITLE
Compress-Archive - Require native password encryption option

### ISSUE THREAD

**Issue by sladecurtis** [PowerShell/PowerShell#24055]
### Summary of the new feature / enhancement

Compress-Archive should have a password encryption option. This is a basic required feature for all archives and should have been included natively, since day one.
Specific use case: doing an Azure live response session and trying to grab a potentially malicious file from the system. Looking to zip and encrypt the file with a password (standard malicious file handling procedures). However cannot utilize native PowerShell to accomplish this without installing 7zip or 7zip4powershell. 
Please include parameters for zip password/encryption into Compress-Archive cmdlet for future releases.

**Comment by ThomasNieto** [comment]
That cmdlet is in another repository. 

https://github.com/PowerShell/Microsoft.PowerShell.Archive

**Comment by SteveL-MSFT** [comment]
We've archived the archive repo as we have no immediate plans to address open issues.  However, we do intend to eventually re-write the archive module, but will probably be in a new repo.

As for this issue, the archive module solely depends on the .NET ZipFile class which doesn't appear to support encryption.  I would suggest up-voting this https://github.com/dotnet/runtime/issues/1545 and once that is implemented, it can be exposed via an Archive module.

**Comment by kasini3000** [comment]
# Temporary solution for you

In my project, there is a “node_stcript” directory: 

https://gitee.com/chuanjiao10/kasini3000/tree/master/node_script/7z

Use my project, When you first connect to a controlled machine, this directory will be copied to the controlled machine.

In this directory, I have placed the 7z toolkit.
The 7z directory can be used independently. This means you can use it separately from the Kasini3000 project.
For you, just change the script inside and add the 'password' parameter.


-------

Welcome to the powershell script framework I wrote: kasini3000

main site: https://gitee.com/chuanjiao10/kasini3000
site mirror: https://github.com/kasini3000/kasini3000 --- Welcome give star to project

win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline)
Open source, free, cross-platform

English manual:
https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

tech：
https://www.cnblogs.com/piapia/p/16534765.html
