### ISSUE TITLE
Call operator (`&{}`) with no results doesn't type compare

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#24054]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```PowerShell
&{} -is [int]
&{} -isnot [int]
```

### Expected behavior

I understand that [*when the left-hand value in the expression is a collection, the operator returns the elements of the collection that match the right-hand value of the expression.*](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_comparison_operators#common-features) but specifically in the case there is nothing returned, I would expect a `[Bool]` where both statements are each other's opposite (similar to `@() -is [int]`):

```PowerShell
False
True
```

Knowing that the following comparisons *do* work:

```PowerShell
@() -is [int]
False
@() -isnot [int]
True
@{} -in 1,2,3
False
@{} -notin 1,2,3
True
```

### Actual behavior

Nothing returned, meaning that both statements below evaluate to `False`:

```PowerShell
if (&{} -is [int]) { 'True' } else { 'False' }
if (&{} -isnot [int]) { 'True' } else { 'False' }
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Workaround

Use parenthesis:
```PowerShell
(@{}) -is [int]
False
(@{}) -isnot [int]
True
```

_No response_

**Comment by 237dmitry** [comment]
> Nothing returned, meaning that both statements below evaluate to False

Both returned `False`

**Comment by iRon7** [comment]
> ### Expected behavior
> `[Bool]` as it supposed to unroll in an empty output/collection:

For the same reason, I would actually expect also the following to return `True` rather than `1`:
As I would expect `@{1}` to return a [scalar](https://learn.microsoft.com/en-us/powershell/scripting/learn/glossary#scalar-value) value:

```PowerShell
&{1} -is [int]
1
```

Anyways, I am probably wrong in this...

**Comment by iRon7** [comment]
Regardless my expectation is correct or not, any change in this will likely result in a break change. Therefore a PSScriptAnalyzer rule like "*use parentheses when **type** comparing the result a call operator*" would probably more in place. (Please confirm.)

**Comment by rhubarb-geek-nz** [comment]
```
&{} -is [int]
&{} -isnot [int]
```

Perhaps it is worth understanding what the & operator does

```
& command [argument list ...] [&]
```

So you are basically passing `-is [int]` and `-isnot [int]` as arguments to an empty script block.

Lets see what happens if we handle the parameters

```
PS> &{param($is) $is} -is [int]
[int]
PS> &{param($isnot) $isnot} -isnot [int]
[int]
```

So the -is and -isnot are not behaving as operators but as simple arguments for the scriptblock.

**Comment by mklement0** [comment]
To summarize @rhubarb-geek-nz's comment:

* Use of `&`, the call operator, starts a _command_ and is therefore parsed in _argument mode_; what follows the command name / path is invariably interpreted as _arguments_ to pass to the former.

* As with any command, if you want it to participate in an _expression_, you need to enclose it in `(...)`
