### ISSUE TITLE
PowerShell Command Explorer extension module filter/search

### ISSUE THREAD

**Issue by emgeiger** [PowerShell/PowerShell#24062]
### Summary of the new feature / enhancement

With the PowerShell Command Explorer extension in the sidebar, I would Like to see a way to search/filter, similar to how it is in the PowerShell integrated scripting environment. To filter by the module, instead of all the modules being all combined with each other.

**Comment by mklement0** [comment]
It sounds like you're talking about a Visual Code Extension, perhaps [PowerShell Commander](https://marketplace.visualstudio.com/items?itemName=DocNougat.powershell-commander)?

You'll need to file issues in the relevant repository instead (e.g., https://github.com/DocNougat/PowerShell-Commander) - this repo is only for issues with PowerShell (Core) itself.
