### ISSUE TITLE
powershell session from linux box to windows server gets stuck

### ISSUE THREAD

**Issue by mbhatia-mdsol** [PowerShell/PowerShell#24064]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hi, I am running a powershell script from a linux box where it needs to execute several commands on 4 remote windows servers and finally deploy the application on them. For this I am using pwsh plugin. At several points in the script, I am creating ps session using new-pssession command and removing them as soon as the work is done. Sometimes i even have to use foreach/for loop to execute a function on all 4 remote nodes. This thing works fine sometimes but many a times the code gets stuck while executing the function on those nodes.  

### Expected behavior

```console
The sessions should work properly without getting stuck and code must go to the next step.
```

### Actual behavior

```console
Sometimes it gets executed on the 2nd session and then gets stuck and other time it gets stuck on the first one itself. There is no specific point where it gets stuck. And there is no specific remote node for which this issue is coming up.

Earlier we used to run this script from a windows node and it used to work fine. 

I even created a separate small script to perform one of these functions via sessions, and it worked fine. So it shows that my code is logically correct. Is there any timeout issue with the PSSession or pwsh plugin or something related to this? It's a very big blocker for us right now.
```

### Environment data

```powershell
I login to a windows server where via putty i connect to the linux box. from that linux box i am trying to access and perform some steps on multiple windows remote nodes. I am using PS version 7.
```

**Comment by SteveL-MSFT** [comment]
It sounds like you are using WSMan remoting?  That is no longer supported for Linux as a client or target.  Can you switch to using SSH?

**Comment by mbhatia-mdsol** [comment]
SSH is not allowed by network team due to some security reason. I have now changed the linux box from RHEL to ubuntu, so it's not stucking anymore. But i want to download 9 files from s3 bucket to my 4 remote servers, for this i am downloading those files to my local via reads3object/aws cp command and then sending them to remote via copy-item. But it's not working. Is it because i am sending 9 files ? because we have done the same thing earlier as well but that time we sent 1-2 files only.

**Comment by mbhatia-mdsol** [comment]
any update on this ??

**Comment by daxian-dbw** [comment]
@mbhatia-mdsol As Steve said above, WSMan is no longer supported for Linux. If you have to use WSMan, take a look at https://github.com/jborean93/PSWSMan/blob/main/docs/en-US/PSWSMan.md and see if that module can help you.
