### ISSUE TITLE
MS Store PATH symlink

### ISSUE THREAD

**Issue by pawelel** [PowerShell/PowerShell#24060]
### Summary of the new feature / enhancement

As a user, I want to have a constant PATH to PowerShell (pwsh) installed through MS Store, which remains stable across updates.
MS Store provides updates (while Windows Update fails for PowerShell). The current path to pwsh is variable and changes with each update, for example:
`C:\Program Files\WindowsApps\Microsoft.PowerShell_7.4.3.0_x64__8wekyb3d8bbwe\pwsh.exe`

This changing path requires manual updates in multiple IDEs and configuration files after each PowerShell update. 
### Proposed technical implementation details (optional)

1. Provide a system-wide symlink that always points to the latest version of PowerShell, e.g., `C:\Program Files\PowerShell\pwsh.exe`
2. Automatically update the system PATH to include the current PowerShell directory after each update
3. Create a wrapper or alias in a stable location that calls the current PowerShell executable

These solutions would greatly improve user experience and reduce the need for manual configuration updates after PowerShell upgrades.

An example
# wrapper directory
New-Item -ItemType Directory -Path "C:\ProgramData\PowerShellWrapper" -Force

# wrapper script
@echo off
setlocal enabledelayedexpansion

REM Find PowerShell directory
for /f "tokens=* usebackq" %%F in (`dir /b /a:d "C:\Program Files\WindowsApps\Microsoft.PowerShell_*_x64__*"`) do (
    set "PWSH_DIR=%%F"
)

REM Check if PWSH_DIR is set
if not defined PWSH_DIR (
    echo couldn't find PowerShell in "C:\Program Files\WindowsApps".
    exit /b 1
)

REM create BAT script to run PowerShell
echo @echo off > "C:\ProgramData\PowerShellWrapper\pwsh.cmd"
echo start /b cmd /c ""C:\Program Files\WindowsApps\!PWSH_DIR!\pwsh.exe" %%*" >> "C:\ProgramData\PowerShellWrapper\pwsh.cmd"

**Comment by jborean93** [comment]
I could be wrong but there should be an AppExecAlias created in the user profile where the PowerShell Appx has been installed. You can see these AppExecAlias files in `$env:LOCALAPPDATA\Microsoft\WindowsApps`, they are 0 byte files but are reparse points which contains the target location in the `C:\Program Files\WindowsApps` folder which Windows knows how to execute.

The location this points to is updated when the application is also updated and is designed to be the public executable used for store applications that are run through an exe. The design of `C:\Program Files\WindowsApps` is meant to be opaque from end users and not something you use directly. The unfortunate downside to this is that the application must be installed per user, it probably is possible to preload the app for new profiles but it is a trickier situation than before with a non-store application.

**Comment by pawelel** [comment]
wow, didn't know that, thank you @jborean93!
