### ISSUE TITLE
Unable to find type [EnvironmentVariableTarget]

### ISSUE THREAD

**Issue by ALIENQuake** [PowerShell/PowerShell#2406]
Hi,
missing type [EnvironmentVariableTarget], .NET Core have support for this type: https://docs.microsoft.com/en-us/dotnet/core/api/system.environmentvariabletarget
so I wonder if this is intended behavior of the new Powershell or bug?

Steps to reproduce
------------------
SetEnvironmentVariable($key, $value, [EnvironmentVariableTarget]::Process)

Expected behavior
-----------------
Set Environment Variable for current Powershell process

Actual behavior
---------------
Unable to find type [EnvironmentVariableTarget].
At line:1 char:38
+ ... EnvironmentVariable($key, $value, [EnvironmentVariableTarget]::Proces ...
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (EnvironmentVariableTarget:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Environment data
----------------

```powershell
Name                           Value
----                           -----
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.10
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSEdition                      Core
PSVersion                      6.0.0-alpha
```

**Comment by kilasuit** [comment]
looks like this may be linked to https://github.com/dotnet/corefx/issues/8533

**Comment by ALIENQuake** [comment]
@kilasuit You right, I've used search but I didn't see any results. Thanks.
