### ISSUE TITLE
Getting ArgumentNullException exception on calling System.Management.Automation.PowerShell.Create() when publishing a single file exe

### ISSUE THREAD

**Issue by kawaiifoxx** [PowerShell/PowerShell#24070]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a dotnet console app.
2.  Add nuget package System.Management.Automation, Microsoft.Powershell.SDK
3. Write below code in  Program.cs of the console application

```C#
var shell = PowerShell.Create()
            .AddCommand("Set-ExecutionPolicy")
            .AddParameter("Scope", "Process")
            .AddParameter("ExecutionPolicy", "Unrestricted")
            .AddScript(
                $"Write-Host 'Hello World!'");

        var results = await shell.InvokeAsync();
```
4. Run `dotnet publish -c Release -o .\bin\Publish --self-contained true --runtime win-x64 /p:PublishSingleFile=true`
5. then `cd  .\bin\Publish
6. run the exe file.
7. You'll get below error:
```C#
 System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
         at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
         at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
```

### Expected behavior

```console
should not throw exception.
```

### Actual behavior

```console
Throwing System.ArgumentNullException exception
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
I believe the problem is that PowerShell uses the location of System.Management.Automation.dll to get the location of $PSHOME which is what fails when built into a single exe.  I was working on a change to allow building pwsh as a singleexe (which as other problems), but I can submit a simple change that would (I think) fix your problem.

**Comment by kasini3000** [comment]
#23797 
#13540

Such a big repair, thank you ！ I will tell my father

**Comment by SteveL-MSFT** [comment]
@mySCHOTT there is no intent to support WinPS5.1 with single-exe
