### ISSUE TITLE
Removing email addresses from a DG im AD using powershell

### ISSUE THREAD

**Issue by adamhaas98** [PowerShell/PowerShell#2407]
Hi guys, I've got a list of email addresses in an excel spreadsheet.

I run this script on the DC in AD Powershell, 

Get-Recipient -resultSize unlimited | select name -expand emailAddresses | where {$_.smtpAddress -match "USERS EMAIL ADRESS"} | Format-Table name, smtpaddress

This then returns a Distribution Group. I need that DG to be put into the spreadsheet alongside the email.

I then run this script with the DG in it Set-DistributionGroup Distribution Group -EmailAddresses @{Remove=’USERS EMAIL ADRESS’}

So my question is, is there a way of automating this? I have over 100 email addresses and would quite like it to be done immediately.

Regards,

Adam.

**Comment by joeyaiello** [comment]
The GitHub Issues here are specific to PowerShell itself rather than external modules. I encourage you to reach out to the TechNet forums for help on Active Directory: https://social.technet.microsoft.com/Forums/windowsserver/en-US/home?forum=winserverDS
