### ISSUE TITLE
Text contrast issue in PowerShell on macOS with light theme

### ISSUE THREAD

**Issue by shashinma** [PowerShell/PowerShell#24089]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Switch macOS to a light theme.
2. Open PowerShell on a macOS device.
3. Observe the text colors in the PowerShell terminal.

### Expected behavior

```console
Text colors should adjust for better contrast in the light theme, making the text easily readable.
```

### Actual behavior

```console
Text colors remain bright, as they do in the dark theme, resulting in poor readability.
```

### Environment data

```powershell
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Darwin 22.6.0 Darwin Kernel Version 22.6.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="570" alt="Снимок экрана 2024-07-25 в 21 13 00" src="https://github.com/user-attachments/assets/d767cec1-95ad-479f-bb4b-f5d946e21ae0">

**Comment by rhubarb-geek-nz** [comment]
Many issues regarding this have been discussed in https://github.com/PowerShell/PowerShell/issues/21160 and it opens a can of worms.

If you want PowerShell to dynamically change colours and given it is a cross-platform console application -

- How does it know what theme is active?
- How does it know when it changes?
- What rules does it use to select a new set of colours?
- How should PowerShell executing on a remote host through ssh behave when a the client's theme changes?

This simplest would be to support monochrome through NO_COLOR and let the console do whatever it wants.

**Comment by 237dmitry** [comment]
Colors depends on settings of:

- Terminal
- $PSStyle
- PSReadline module ( `Set-PSReadLineOption -Colors @{.....}` )

**Comment by shashinma** [comment]
@rhubarb-geek-nz Yes, perhaps using monochrome mode would be the most appropriate. 
If I remember correctly, at the moment we can determine the active theme either using WPF or with MAUI, but of course, they are not suitable for us. 
There's also an option to use a small amount of Swift code, but that doesn't seem very practical to me

**Comment by SteveL-MSFT** [comment]
There's a bunch of modules available for applying themes https://www.powershellgallery.com/packages?q=theme

**Comment by SteveL-MSFT** [comment]
@shashinma keep in mind that PS7 is also supported on Linux which has different Windows Managers and also different terminals can also have their own themes.
