### ISSUE TITLE
Cmdlet - ConvertFrom-Base64String

### ISSUE THREAD

**Issue by gw-bcharboneau** [PowerShell/PowerShell#24099]
### Summary of the new feature / enhancement

I have written this Basic Function to Decode a Base64 Encoded String. However I was hoping that it or something similar to it could be considered for an addition to the builtin Powershell CmdLets/Modules. 

Understand, what I have included in the codeblock below in the Proposed technical implementation details is only an example and others may have their own opinions on how to better approach it, I am all for the free exchange of ideas to better this process and hope this simple concept can be included in a future release of powershell.

### Proposed technical implementation details (optional)

A CmdLet or set of CmdLets to be added to Powershell that will allow Encoding/Decoding of Strings to and From Base64 and potentially even other Encoding Types. A basic example of this is included in the codeblock below

```powershell
function ConvertFrom-Base64String {
    [CmdletBinding()]
    param (
        [Parameter(mandatory=$true,ValueFromPipeline=$true)]
        [String]
        $EncodedString
    )
    try {
        $decodedString = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($EncodedString))
        return $decodedString
    }
    catch {
        throw "The provided string is not a valid Base64 encoded string."
    }
}
```

**Comment by rhubarb-geek-nz** [comment]
Hi,

>  I am all for the free exchange of ideas to better this process

Not all new ideas have to be added to PowerShell itself. The [PowerShell Gallery](https://www.powershellgallery.com) is good place for sharing useful modules.

> allow Encoding/Decoding of Strings to and From Base64 and potentially even other Encoding Types

The only type that makes sense to encode with Base64 is a sequence or array of bytes. Base64 is not intended as a way of encoding strings. Places where this is done, for example in HTTP Basic authentication, are the exception not the rule. All you end up with is a string that is 50% bigger. Any further encodings to and from byte sequences can be done with other cmdlets.

So has this been done before? Yes, there is a pair of cmdlets, [ConvertTo-Base64String](https://github.com/rhubarb-geek-nz/Base64String/blob/main/Base64String/ConvertToBase64String.cs) and [ConvertFrom-Base64String](https://github.com/rhubarb-geek-nz/Base64String/blob/main/Base64String/ConvertFromBase64String.cs) available as a [PowerShell Module](https://www.powershellgallery.com/packages/rhubarb-geek-nz.Base64String/1.0.0). These convert individual records between byte arrays and strings.

There is another pair, [ConvertTo-Base64](https://github.com/rhubarb-geek-nz/Base64/blob/main/Base64/ConvertToBase64.cs) and [ConvertFrom-Base64](https://github.com/rhubarb-geek-nz/Base64/blob/main/Base64/ConvertFromBase64.cs) which are intended for use in a streaming pipeline, there the entire content is treated as a single encoding. Also available in [The Gallery](https://www.powershellgallery.com/packages/rhubarb-geek-nz.Base64/1.0.0).

**Comment by ThomasNieto** [comment]
Here is the Microsoft written module with those cmdlets. https://www.powershellgallery.com/packages/Microsoft.PowerShell.TextUtility/0.5.0

**Comment by gw-bcharboneau** [comment]
Since it is often used with Web based requests, that is why im asking.   AWS Also uses it with their AWS CLI for exporting CSV based reports through the CLI which is where I use modules currently, it would just be nice to have it be natively there, so that if i share scripts with others, I don't have to make specific modules required.

**Comment by rhubarb-geek-nz** [comment]
> so that if we share scripts with others, we don't have to make specific modules required. especially for the Base64Decode.

Alas that approach really doesn't scale. Modern languages are all designed to be extendable and use Maven, NuGet, Pip, npm etc to provide additional functionality that can be shared and avoid reinventing the wheel. PowerShell has PSGallery for that.

Say you get Base64Decode added as a cmdlet to PowerShell 7.5, you won't get it until months away and anything that uses won't be backward compatible with existing PowerShell installations. If the cmdlet is in the Gallery then even PowerShell 5.1 can use it along any other version.

I suggest either make a dependency on any suitable implementation you choose from the Gallery or use the native method invocation as you are using.

**Comment by kasini3000** [comment]
My suggestion (best way) for you：

#### Abandon AWS CLI and use AWS PowerShell:
Manual root directory
https://docs.aws.amazon.com/powershell/index.html

All commands are in:
https://docs.aws.amazon.com/powershell/latest/reference/Index.html

#### Use the PowerShell script framework I wrote
If you place the script in the 'node_stcript' directory, it will be automatically copied to each controlled machine when first connected to it.


-------

main site: https://gitee.com/chuanjiao10/kasini3000
site mirror: https://github.com/kasini3000/kasini3000 --- Welcome give star to project

win,linux devops automation batch script framework.(It is similar to Puppet，Ansible，pipeline)
Open source, free, cross-platform

English manual:
https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/kasini3000_manual.xlsx

tech：
https://www.cnblogs.com/piapia/p/16534765.html

Features:
Transfer PowerShell objects (. net objects) over both WINRM and SSH between the main control machine and the controlled machine.This means that you can pass object level variables between hybrid clouds.
