### ISSUE TITLE
DateTime/Get-Date Month 'MMM' String Formatting Is Adding Unexpected Period

### ISSUE THREAD

**Issue by dpo007** [PowerShell/PowerShell#24102]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When attempting to format a DateTime to a string that uses the 3 character abbreviation for the month, PowerShell 7.x is unexpectedly appending the period (to show it's an abbreviation).

This is unexpected based on previous versions of PS, years of formatting date strings similarly in an MS environment, and Microsoft's own custom DateTime string formatting documentation (https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings).

This is problematic (for example) when trying to build a file spec based on a date string. 

e.g. `c:\temp\vendordata_01Jul2024.dat`:

`$fileSpec = ('vendordata_{0}.dat' -f (Get-Date).AddDays(-1).ToString('ddMMMyyyy'))`

### Expected behavior

```console
PS C:\temp> (Get-Date).ToString('MMM')
Jul
PS C:\temp> (Get-Date 05/05/2024).ToString('MMM')
May
PS C:\temp> (Get-Date 01/01/2024).ToString('MMM')
Jan
PS C:\temp> $fileSpec = ('vendordata_{0}.dat' -f (Get-Date).AddDays(-1).ToString('ddMMMyyyy'))
PS C:\temp> $fileSpec
vendordata_30Jul2024.dat
```

### Actual behavior

```console
PS C:\temp> (Get-Date).ToString('MMM')
Jul.
PS C:\temp> (Get-Date 05/05/2024).ToString('MMM')
May
PS C:\temp> (Get-Date 01/01/2024).ToString('MMM')
Jan.
PS C:\temp> $fileSpec = ('vendordata_{0}.dat' -f (Get-Date).AddDays(-1).ToString('ddMMMyyyy'))
PS C:\temp> $filespec
vendordata_30Jul.2024.dat
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
I expect this dotnet behaviour, not PowerShell specific.

```
PS> (Get-Date).GetType().FullName
System.DateTime
```

The type returned is a basic dotnet type, and it is using it's [ToString](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=net-8.0#system-datetime-tostring(system-string)) implementation.

**Comment by dpo007** [comment]
Good point.  Interestingly(?), on the page you point to, they show the MMM example NOT returning a dot.

![image](https://github.com/user-attachments/assets/70c6a641-b935-43f2-a9d5-0493ff080097)

I also just tried `'ddd'` for days, and it also seems to suffer from the same unexpected dot (also not reflected in the documentation):

![image](https://github.com/user-attachments/assets/249a0aa0-a445-403c-a2a1-f83b9948cfe3)
![image](https://github.com/user-attachments/assets/71008f7f-f0d9-4092-b008-74cc1cbe38ce)

**Comment by rhubarb-geek-nz** [comment]
I expect it is locale specific. 

From you examples it looks like May does not have the period because it is not truncated, where as Jan. and Jul. are.

**Comment by 237dmitry** [comment]
I think this depends on culture formats (Australia maybe?):
```powershell
$ & {
         $en = [Globalization.CultureInfo]::GetCultures('All') | ? Name -match 'en-'
         foreach ($i in $en) {
         [Threading.Thread]::CurrentThread.CurrentCulture = $i.Name
         '{0} {1}' -f (Get-Date -Month 7).ToString('MMM'), $i.DisplayName
    }}
Jul English (world)
Jul English (Europe)
Jul English (United Arab Emirates)
Jul English (Antigua & Barbuda)
Jul English (Anguilla)
Jul English (American Samoa)
Jul English (Austria)
July English (Australia)
Jul English (Barbados)
Jul English (Belgium)
Jul English (Burundi)
Jul English (Bermuda)
Jul English (Bahamas)
Jul English (Botswana)
Jul English (Belize)
Jul English (Canada)
Jul English (Cocos [Keeling] Islands)
Jul English (Switzerland)
Jul English (Cook Islands)
Jul English (Cameroon)
Jul English (Christmas Island)
Jul English (Cyprus)
Jul English (Germany)
Jul English (Diego Garcia)
Jul English (Denmark)
Jul English (Dominica)
Jul English (Eritrea)
Jul English (Finland)
Jul English (Fiji)
Jul English (Falkland Islands)
Jul English (Micronesia)
Jul English (United Kingdom)
Jul English (Grenada)
Jul English (Guernsey)
Jul English (Ghana)
Jul English (Gibraltar)
Jul English (Gambia)
Jul English (Guam)
Jul English (Guyana)
Jul English (Hong Kong SAR China)
Jul English (Indonesia)
Jul English (Ireland)
Jul English (Israel)
Jul English (Isle of Man)
Jul English (India)
Jul English (British Indian Ocean Territory)
Jul English (Jersey)
Jul English (Jamaica)
Jul English (Kenya)
Jul English (Kiribati)
Jul English (St. Kitts & Nevis)
Jul English (Cayman Islands)
Jul English (St. Lucia)
Jul English (Liberia)
Jul English (Lesotho)
Jul English (Madagascar)
Jul English (Marshall Islands)
Jul English (Macao SAR China)
Jul English (Northern Mariana Islands)
Jul English (Montserrat)
Jul English (Malta)
Jul English (Mauritius)
Jul English (Maldives)
Jul English (Malawi)
Jul English (Malaysia)
Jul English (Namibia)
Jul English (Norfolk Island)
Jul English (Nigeria)
Jul English (Netherlands)
Jul English (Nauru)
Jul English (Niue)
Jul English (New Zealand)
Jul English (Papua New Guinea)
Jul English (Philippines)
Jul English (Pakistan)
Jul English (Pitcairn Islands)
Jul English (Puerto Rico)
Jul English (Palau)
Jul English (Rwanda)
Jul English (Solomon Islands)
Jul English (Seychelles)
Jul English (Sudan)
Jul English (Sweden)
Jul English (Singapore)
Jul English (St. Helena)
Jul English (Slovenia)
Jul English (Sierra Leone)
Jul English (South Sudan)
Jul English (Sint Maarten)
Jul English (Eswatini)
Jul English (Turks & Caicos Islands)
Jul English (Tokelau)
Jul English (Tonga)
Jul English (Trinidad & Tobago)
Jul English (Tuvalu)
Jul English (Tanzania)
Jul English (Uganda)
Jul English (U.S. Outlying Islands)
Jul English (United States)
Jul English (United States, Computer)
Jul English (St. Vincent & Grenadines)
Jul English (British Virgin Islands)
Jul English (U.S. Virgin Islands)
Jul English (Vanuatu)
Jul English (Samoa)
Jul English (South Africa)
Jul English (Zambia)
Jul English (Zimbabwe) 
```

**Comment by dpo007** [comment]
```powershell
PS C:\temp> get-culture

LCID             Name             DisplayName
----             ----             -----------
4105             en-CA            English (Canada)
```

I ran you example there, and low and behold Canada shows the dot.. but only Canada?

```
Jul English (World)
Jul English (Caribbean)
Jul English (Europe)
Jul English (United Arab Emirates)
Jul English (Antigua & Barbuda)
Jul English (Anguilla)
Jul English (American Samoa)
Jul English (Austria)
Jul English (Australia)
Jul English (Barbados)
Jul English (Belgium)
Jul English (Burundi)
Jul English (Bermuda)
Jul English (Bahamas)
Jul English (Botswana)
Jul English (Belize)
Jul. English (Canada)
Jul English (Cocos [Keeling] Islands)
Jul English (Switzerland)
Jul English (Cook Islands)
Jul English (Cameroon)
Jul English (Christmas Island)
Jul English (Cyprus)
Jul English (Germany)
Jul English (Denmark)
Jul English (Dominica)
Jul English (Eritrea)
Jul English (Finland)
Jul English (Fiji)
Jul English (Falkland Islands)
Jul English (Micronesia)
Jul English (United Kingdom)
Jul English (Grenada)
Jul English (Guernsey)
Jul English (Ghana)
Jul English (Gibraltar)
Jul English (Gambia)
Jul English (Guam)
Jul English (Guyana)
Jul English (Hong Kong SAR China)
Jul English (Indonesia)
Jul English (Ireland)
Jul English (Israel)
Jul English (Isle of Man)
Jul English (India)
Jul English (British Indian Ocean Territory)
Jul English (Jersey)
Jul English (Jamaica)
Jul English (Kenya)
Jul English (Kiribati)
Jul English (St Kitts & Nevis)
Jul English (Cayman Islands)
Jul English (St Lucia)
Jul English (Liberia)
Jul English (Lesotho)
Jul English (Madagascar)
Jul English (Marshall Islands)
Jul English (Macao SAR)
Jul English (Northern Mariana Islands)
Jul English (Montserrat)
Jul English (Malta)
Jul English (Mauritius)
Jul English (Malawi)
Jul English (Malaysia)
Jul English (Namibia)
Jul English (Norfolk Island)
Jul English (Nigeria)
Jul English (Netherlands)
Jul English (Nauru)
Jul English (Niue)
Jul English (New Zealand)
Jul English (Papua New Guinea)
Jul English (Philippines)
Jul English (Pakistan)
Jul English (Pitcairn Islands)
Jul English (Puerto Rico)
Jul English (Palau)
Jul English (Rwanda)
Jul English (Solomon Islands)
Jul English (Seychelles)
Jul English (Sudan)
Jul English (Sweden)
Jul English (Singapore)
Jul English (St Helena)
Jul English (Slovenia)
Jul English (Sierra Leone)
Jul English (South Sudan)
Jul English (Sint Maarten)
Jul English (Eswatini)
Jul English (Turks & Caicos Islands)
Jul English (Tokelau)
Jul English (Tonga)
Jul English (Trinidad & Tobago)
Jul English (Tuvalu)
Jul English (Tanzania)
Jul English (Uganda)
Jul English (US Outlying Islands)
Jul English (United States)
Jul English (United States, Computer)
Jul English (St Vincent & the Grenadines)
Jul English (British Virgin Islands)
Jul English (US Virgin Islands)
Jul English (Vanuatu)
Jul English (Samoa)
Jul English (South Africa)
Jul English (Zambia)
Jul English (Zimbabwe)
```

But yours does not... hmmmmm

Yet I'm seeing this on both my domain-joined, office machines, and my personal machine at home (all running Windows 11).

**Comment by dpo007** [comment]
And to be clear, PowerShell 5.1 on the same machines does NOT add the dot.

**Comment by dpo007** [comment]
> From your examples it looks like May does not have the period because it is not truncated, where as Jan. and Jul. are.

Exactly, so it's doing it on purpose, with some logic.  I just can't find any reference to this being the expected behaviour (now).

**Comment by 237dmitry** [comment]
> But yours does not..

Different versions of Net, imho, I use pwsh 7.5.0-preview.3.

What does show 'en-CA': culture?

```
[System.Globalization.CultureInfo]::CurrentCulture.DateTimeFormat.AbbreviatedMonthNames
```

**Comment by dpo007** [comment]
> What does show 'en-CA': culture?

```powershell
> [System.Globalization.CultureInfo]::CurrentCulture.DateTimeFormat.AbbreviatedMonthNames
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
```

**Comment by dpo007** [comment]
> [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
.NET 8.0.7

**Comment by 237dmitry** [comment]
.NET 9.0.0-preview.3.24172.9 and all English-Canadian month abbreviations are as expected.

**Comment by 237dmitry** [comment]
What will be result if you try different formatting methods:

```
Get-Date -Month 7 -format 'MMM'
Get-Date -Month 7 -uformat '%b'
'{0:MMM}' -f (Get-Date -Month 7)
```

**Comment by dpo007** [comment]
> What happens if you try different formatting methods?:

![image](https://github.com/user-attachments/assets/65199ec4-a9fa-4cfd-80cf-9e4454bc0a2f)

**Comment by rhubarb-geek-nz** [comment]
Can I suggest look at the problem another way?

The locale formats for dates are for presentation to the end user. However what you are wanting is a consistent file name format for the identification of a file, either for archiving or transfer to other systems. 

Now should that file name format be at the whim of the user's locale preference or is it for machine readability? 

You could choose to either use a numeric format for the date fields, or else use the [InvariantCulture](CultureInfo.InvariantCulture) for the date fields for consistent conversion independent of the user's settings.

**Comment by dpo007** [comment]
> You could choose to either use a numeric format for the date fields, or else use the [InvariantCulture](CultureInfo.InvariantCulture) for the date fields for consistent conversion independent of the user's settings.

Using the Invariant Culture seems to be a solid approach for sure...

```powershell
PS C:\temp> $InvariantCulture = [System.Globalization.CultureInfo]::InvariantCulture
PS C:\temp> (Get-Date).ToString('MMM', $InvariantCulture)
Jul
PS C:\temp> (Get-Date).ToString('ddMMMyyyy', $InvariantCulture)
31Jul2024
PS C:\temp> (Get-Date).ToString('ddd MMM yyyy', $InvariantCulture)
Wed Jul 2024
```

**Comment by iSazonov** [comment]
```powershell
$c=get-culture en-CA
(Get-Date).ToString('MMM', $c)
Aug

(Get-Date).ToString('ddMMM', $c)  # or (Get-Date).ToString('dMMM', $c)
01Aug.                                             # 1Aug
```
Looks like .Net issue. So I'd suggest to report the issue in https://github.com/dotnet/runtime

**Comment by dpo007** [comment]
Ok, I dug into their issues and (finally) managed to find others reporting the same thing (dating back to at least 2022).
e.g: https://github.com/dotnet/runtime/issues/68385

Thanks for the direction!

It _is_ working as designed.

Apparently in .Net 6+ they started using `DateTimeFormat.AbbreviatedMonthGenitiveNames` instead of `DateTimeFormat.AbbreviatedMonthNames` for the DateTime ToString method.

```powershell
> [System.Globalization.CultureInfo]::CurrentCulture.DateTimeFormat.AbbreviatedMonthGenitiveNames
Jan.
Feb.
Mar.
Apr.
May
Jun.
Jul.
Aug.
Sep.
Oct.
Nov.
Dec.
```

Thanks everyone! :)

**Comment by dpo007** [comment]
Thanks again everyone, closing.
