### ISSUE TITLE
Execution policy blocks powershell's own components

### ISSUE THREAD

**Issue by ExtremePro11299** [PowerShell/PowerShell#24106]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Set the execution policy to Restricted and then run powershell.

### Expected behavior

```console
The PSReadLine module should turn on in any execution policy, as Restricted is the default execution policy.
```

### Actual behavior

```console
it says that Cannot load PSReadline module.  Console is running without PSReadline.
.: File C:\Users\Adam\Documents\PowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170. When I set the execution policy to AllSigned, and it said that the PSReadLine module has an untrusted publisher which is Microsoft.
```

### Error details

```console
It even tried to block the execution policy setter when i ran Set-ExecutionPolicy while it was AllSigned.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

In execution policy Restricted:  
![image](https://github.com/user-attachments/assets/6b78ead7-7978-473b-b342-e8421f3d7251)
In execution policy AllSigned:
![image](https://github.com/user-attachments/assets/fda44c7e-a6c5-4ecd-81d0-3023a191c815)  
After that the PSReadline module worked, as I chose to run them.

**Comment by SteveL-MSFT** [comment]
`Restricted` disallows all scripts and PSReadLine uses a psm1.  We don't want to special case PSReadLine here.  Using `AllSigned` or `RemoteSigned` is appropriate as the PSReadLine script is signed.

**Comment by theJasonHelmick** [comment]
The Interactive WG agrees with comments from @SteveL-MSFT -  this is by design.
