### ISSUE TITLE
LUID

### ISSUE THREAD

**Issue by arielsil** [PowerShell/PowerShell#24127]
### Summary of the new feature / enhancement

Hi,  Could we have a module/script/command like Get-LUID (computer wide) , Get-ProcessLUID and Get-ServiceLUID (for user subservices)?

### Proposed technical implementation details (optional)

Get-LUID = Get-CimInstance -ClassName Win32_LUID -Property *
Get-ServiceLUID = "Get-Service '*_*' | Select-Object Name | ForEach-Object { $_.Name.Split('_')[-1] } | Group-Object | Sort-Object Count -Descending | Select-Object -First 1 -ExpandProperty Name"
Get-NetLuidIndex = values at HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\* for each adapter

**Comment by rhubarb-geek-nz** [comment]
> Hi, Could we have a module/script/command like ....

Given it does not depend on PowerShell internals, is Windows specific and is a wrapper on existing functionality it sounds like an excellent candidate for a PSGallery module.
