### ISSUE TITLE
Copy-Item ToSession Unusably Slow

### ISSUE THREAD

**Issue by pyrostew** [PowerShell/PowerShell#24137]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to copy a folder containing around 80-100 files ranging in size from 3kb to 400mb with about 1.8gb total from a Windows 11 machine running PowerShell 7.4.3 to a Windows 10 VM (fresh install) running Windows PowerShell 5.1.

The VM is hosted by the Windows 11 machine and connected by an internal virtual switch

I do not have means to use file shares (for various reasons) so I am using Copy-Item -ToSession. This does work but it is 2/3 orders of magnitude slower than I would expect literally taking multiple minutes to move a single 3kb file with long periods of time with apparently no CPU or network activity. While the command is running there are also multiple instances of the "Network Connection interrupted" warning that I believe comes from WinRM?
![image](https://github.com/user-attachments/assets/67d65a4f-c5d1-44b4-a5a6-180b949064f9)

### Expected behavior

Copying the files over an SMB file share should take about 15 seconds on a 1gbps connection, I understand that this copy process has a lot of overhead and I would tolerate it taking an order of magnitude longer, say 2-3 minutes.

### Actual behavior

The copy process is taking upwards of 3 HOURS to move 1.8gb of files.

### Environment data

PSVersion on host machine Windows 11
```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
PSVersion on VM Windows 10
```powershell
Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by mklement0** [comment]
Please see https://github.com/PowerShell/PowerShell/issues/14646#issuecomment-791729923

**Comment by mklement0** [comment]
As for the specifics of the overhead, from https://github.com/PowerShell/PowerShell/issues/14646#issuecomment-764558144:

> Using `-ToSession` ` -FromSession` means all the data is being encapsulated inside a PowerShell object which is then serialized to XML, base64 encoded, chunked to smaller sizes, then finally transferred over the connection you've defined for that transport. You also have the overhead of setting up the Runspace Pool and Pipeline which I believe happens multiple times due to a file transfer limit set for each pipeline.
Compare this to SMB where the raw bytes of your data is not encapsulated in any container and the protocol is specifically designed for that task. I don't think there is much that can be done here, if you have SMB access then I would use that to copy the file, if you don't then you are limited to what is currently available.

**Comment by SteveL-MSFT** [comment]
`Copy-Item -ToSession` should only be used if there is no other means of file transfer (SMB, SCP, SFTP, etc...).  Unfortunately, when PowerShell remoting protocol was created a long time back, they didn't consider file transfers so files get transferred over the same protocol as objects which, because of WS-Man, has the overhead of SOAP and also base64 encoding (multiple times, once for PS remoting protocol and I believe again in WinRM for the WS-Man payload).  There's no plan to address this as the recommendation is to use SMB, SSH, etc...

**Comment by kasini3000** [comment]
are you use hyperv on win11 host?

Also, I guess your router overheats frequently and crashes, or the network cable is loose.

===========================
PowerShell Direct lets you remote connect to a Windows Virtual Machine running on a Hyper-V host, without any network connection inside the VM.
PowerShell Direct uses the Hyper-V VMBus to connect inside the Virtual Machine

connect to a Linux VM using SSH over the Hyper-V VMBus. You are also able to copy file


=====================================

### Execute command from hyperv parent machine to child machine: Linux child machine is not supported
Enter-PSSession -Credential (Get-Credential) -VMName 虚拟机名称 #或-vmid 
Invoke-Command -Credential (Get-Credential) -VMName 虚拟机名称 -ScriptBlock { 需要执行的命令 }

### Copy files from hyperv mother machine to child machine, command test passed: supports Linux child machine
Copy VMFile SourcePath d: \Mother machine path\a.txt -DestinianPath c: \Must already exist_Child machine path - Name 'win2012' - Filehost
#### Or Linux
Copy VMFile SourcePath d: \Mother machine path\a.txt DestinianPath/tmp - Name 'centos7' - FileSource host

**Comment by pyrostew** [comment]
@mklement0 I did have a read of that issue before posting. As I alluded to in my original post, I can understand the overhead of packing the files into various wrappers for cramming them through a powershell and WinRM session, I accept that would increase the transferred size of a file by 2x maybe? but that wouldn't explain why there are no network or cpu resources consumed for many minutes at a time around the transfer of a single tiny file.

As I said it would take about 15 seconds to transfer the 1.8gb of files over SMB on a 1gbps network link, I would tolerate this taking 2-3 minutes (an order of magnitude slower), but 4 hours (3 orders of magnitude slower) is obviously ridiculous. especially considering the process works at an acceptable rate on a Windows 10 VM host.

**Comment by mklement0** [comment]
@pyrostew, if you're aware of a previous issue (#14646 in this case) please link to it to begin with, so that everyone has the full picture.

It sounds like _network problems_ may be causing the excessive execution time.
Unless you suspect that it is _PowerShell_ causing them, that is really a separate issue.

It is clear from the official response both in #14646 and here that there are no plans to invest in optimizing this scenario.

But, as @kasini3000 points out, using [`Copy-VMFile`](https://learn.microsoft.com/en-us/powershell/module/hyper-v/copy-vmfile) may be the better tool to begin with, and may solve your problem.
