### ISSUE TITLE
Add basic navigation support for help pages

### ISSUE THREAD

**Issue by cktgh** [PowerShell/PowerShell#24136]
### Summary of the new feature / enhancement

Please consider adding page navigation support for:
1. [`ShowCommandHelp`](https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/dynamic-help?view=powershell-7.4#getting-cmdlet-help), which currently supports keyboard actions:
  - Up - next line
  - Down - previous line
  - Q - exit
2. `help`, which currently supports keyboard actions:
  - Space - next page
  - Enter - next line
  - Q/Ctrl+C - exit

It surprises me that the page up and page down buttons are not supported. We can't scroll back up on `help`, and also there is no button to jump to next page on `ShowCommandHelp`.

I would suggest:
1. Synchronizing the keys actions for both variants of manual pages.
2. Adding support for "Page Up"/"Page Down"/"Home"/"End" keys.

**Comment by jhoneill** [comment]
Just as an FYI,  help is a function which wraps `Get-Help`   (in most cases `Thing` will run `Get-Thing`  if there is no actual `thing` command  - try `date` and `get-command date`)  and sends help's output through a pager - on windows this defaults to `more.com` but it can be over-ridden with an environment variable `$env:Pager` so you can set it to (e.g.) `less.exe` and get different keys and functionality. 

Because of the issues running an external pager in the middle of processing command line input AIUI [PSReadLine](https://github.com/PowerShell/PSReadLine)  - which has its own repo - implements it's own pager. 

Changing the behaviour of more.com after so long as it is is unlikely (but the Windows team updated `tree.com` for Windows 11 so anything is possible) making PSReadline more like other pagers would be a query for that repo, but is more likely to get traction.

**Comment by cktgh** [comment]
Thanks for the information!

***

I played with your example and now I'm curious as to how `date` works 🤔

Like what you said, `help` it is a wrapping function, such that `(gcm help).Definition` would print its definition; `gal help` would return an error as expected because it is not an alias.

Yet `date` is different: `gal date` shows that it is not an alias; `gcm date` shows that it is not a function, script, nor program. So what is `date`?

**Comment by cktgh** [comment]
(in retrospect, the `gal date` check is redundant, as `gcm` would resolve it too)

**Comment by jhoneill** [comment]
> Thanks for the information!
> 
> I played with your example and now I'm curious as to how `date` works 🤔
> 
> Like what you said, `help` it is a wrapping function, such that `(gcm help).Definition` would print its definition; `gal help` would return an error as expected because it is not an alias.
> 
> Yet `date` is different: `gal date` shows that it is not an alias; `gcm date` shows that it is not a function, script, nor program. So what is `date`?

Powershell just has a a backstop before reporting "not found" which is to try `Get-whatever` 

```
function get-thing {"A Thing"} 
Thing
```
Works 

`Help` is unusual in not being a hidden alias for `get-help`  but being  way to do  `get-help  | more`  with various conditions - which allow people to do `get-help | less ` or any other alternative pager.

**Comment by SteveL-MSFT** [comment]
`date` (on Windows) isn't a command, but PowerShell has a lesser known feature where if you type a command, like `date` and it doesn't exist, PowerShell will try it with `get-` in front.  So `date`, on Windows, will actually execute `get-date`.  You can try the same with `service` which will run `get-service`.

**Comment by SteveL-MSFT** [comment]
There are currently no plans to continue to enhance the builtin pager as there are much better pages out there.

**Comment by mklement0** [comment]
As an aside: that `Get-Command` (`gcm`) and `Get-Help` / `help` aren't aware of the default-verb logic (`date` falling back to `Get-Date`) is a long-standing bug:

* #3987

**Comment by mklement0** [comment]
FWIW, I agree that:

* the pagers used in the two scenarios should exhibit the _same_ behavior.

   * I had previously suggested improvements to the `ShowCommandHelp` pager in https://github.com/PowerShell/PSReadLine/issues/3561 (note that the source code is maintained in the `PSReadLine` repo), without considering the asymmetry with the `help` function.

* that there should be a unified mechanism to allow specifying a _custom_ pager.
  * Only the `help` function supports this, via the `$env:PAGER` environment variable.
