### ISSUE TITLE
PowerShell doesn't finish installing

### ISSUE THREAD

**Issue by FahimFBA** [PowerShell/PowerShell#24167]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Download PowerShell-7.4.4-win-x64.msi
Install
It gets stuck!
![Screenshot 2024-08-15 182946](https://github.com/user-attachments/assets/4e5c4d59-8f15-49fb-98b5-3b310f106d8e)

### Expected behavior

```console
The installation should be finished successfully or end with an error.
```

### Actual behavior

```console
It remains stuck!
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.3958
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3958
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![Screenshot 2024-08-15 182946](https://github.com/user-attachments/assets/b71e0431-c75a-4d56-abb6-28097ffd3b1d)

**Comment by SteveL-MSFT** [comment]
Can you run it via [`msiexec`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec) with logging to see where it's getting stuck?

**Comment by FahimFBA** [comment]
Sorry to update the issue. 

I am going to write here directly. After some manual update downloading, the issue has been resolved. However, it takes longer to finish installing.

As the primary issue of this has been resolved, I am closing the issue.
