### ISSUE TITLE
Different behavior on Linux vs. Windows for passing "*" to az cli

### ISSUE THREAD

**Issue by onionhammer** [PowerShell/PowerShell#24170]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a powershell script which passes variable to the "--pattern" argument to `az storage blob upload-batch`
2. Set pattern variable to "*" or "`*"
3. Run script on Windows: Voila it works
4. Run script on Linux: It finds no files
5. Hard-code the "*" into the "--pattern" argument on Linux, it works

There does not appear to be a way to pass "*" as variable to `az storage blob upload-batch` on linux, only hardcode it as a parameter; this behavior works as-expected on Windows.

### Expected behavior

```console
$Path = "`*"
      az storage blob upload-batch `
        --auth-mode login `
        --pattern $Path `
        -s "." `
        -d $dest

# Should upload all files in a directory and return a list of files; i.e. ['file1.txt']
```

### Actual behavior

```console
$Path = "`*"
      az storage blob upload-batch `
        --auth-mode login `
        --pattern $Path `
        -s "." `
        -d $dest

# Actually returns [] or no output on Linux, but on Windows works consistently

      az storage blob upload-batch `
        --auth-mode login `
        --pattern '*' `
        -s "." `
        -d $dest

# Works fine
```

### Error details

```console
No errors
```

### Environment data

pwsh --version
PowerShell 7.4.4

**Comment by jborean93** [comment]
The behaviour here works like how typical sh shells like shl/bash works on Linux when you pass in `*` as an argument to an executable. When the value `*` is provided literally or as a variable without quotes the shell will expand that to an array of files/folders that match pattern in the current location. The same also applies if you pass in `*` through a variable that is not quoted, for example in both of the following examples I am in a folder with the files `foo.txt` and `bar.txt`

```bash
# bash
W="*"

~/dev/print_argv *
# [1] bar.txt
# [2] foo.txt

~/dev/print_argv $W
# [1] bar.txt
# [2] foo.txt
```

```powershell
# powershell
$w = '*'

~/dev/print_argv *
# [1] bar.txt
# [2] foo.txt

~/dev/print_argv $w
# [1] bar.txt
# [2] foo.txt
```

To avoid this you need to explicitly quote the the argument, both when using it literally or when using it as a variable.

```bash
# bash
W="*"

~/dev/print_argv '*'
# [1] *

~/dev/print_argv "*"
# [1] *

~/dev/print_argv "$W"
# [1] *
```

```powershell
# powershell
$w = '*'  # This can also be double quoted, it doesn't matter

~/dev/print_argv '*'
# [1] *

~/dev/print_argv "*"
# [1] *

~/dev/print_argv "$w"
# [1] *
```

What I cannot get to work is when you provide `*` inside an array variable or through a splat regardless of quoting. This is probably a bug.

```powershell
$w = '*'
$arr1 = @($w)
$arr2 = @("$w")
$arr3 = @('*')

# These all find the files using the glob pattern
~/dev/print_argv $arr1
~/dev/print_argv @arr1
~/dev/print_argv $arr2
~/dev/print_argv @arr2
~/dev/print_argv $arr3
~/dev/print_argv @arr3
# [1] bar.txt
# [2] foo.txt
```

Just as an FYI the `print_argv` is an executable you can compile from https://gist.github.com/jborean93/d45fcf5eca04dfe79dadb2e0c8c584c2#file-linux_print_argv-c. It just prints each argument in the provided array after the `[x]` index.

**Comment by onionhammer** [comment]
So is this the desired behavior? To have scripts work differently on different platforms?
