### ISSUE TITLE
Allow Selection of PowerShell Runtime Version in .NET Core Applications

### ISSUE THREAD

**Issue by jeharris-eci** [PowerShell/PowerShell#24185]
### Summary of the new feature / enhancement

As a developer integrating PowerShell into my .NET Core C# application,
I want the ability to select the PowerShell runtime version,
so that I can choose between PowerShell Core and other versions (e.g., Windows PowerShell 5.1) to ensure compatibility with custom PowerShell libraries and avoid runtime issues.

Issue Explanation:

Currently, when integrating PowerShell into a .NET Core application, the default runtime used is PowerShell 7.x (PowerShell Core). This presents a significant challenge because many existing custom PowerShell libraries and scripts are designed to work with older versions, such as Windows PowerShell 5.1. These libraries may not be compatible with PowerShell Core, leading to errors and functionality gaps in the application.

Allowing developers to explicitly choose the PowerShell runtime version would provide the necessary flexibility to use the appropriate environment for their specific scripts and libraries. This would enhance compatibility, reduce errors, and streamline the integration of PowerShell into .NET Core applications.

### Proposed technical implementation details (optional)

To support this feature, developers should be able to specify the desired PowerShell version programmatically when creating a runspace. Below is a conceptual implementation example:

```csharp
var version = new Version(5, 1); // Specify the PowerShell version, e.g., 5.1 for Windows PowerShell 5.1
var initialSessionState = GetInitialSessionState(ExecutionPolicy.Unrestricted, version); // Get the initial session state for the specified version
using var runspace = RunspaceFactory.CreateRunspace(initialSessionState); // Create a runspace using the specified version
runspace.Open();

using var powerShell = PowerShell.Create(runspace); // Create a PowerShell instance within the specified runspace

var result = powerShell.Invoke(); // Execute the command
```

**Comment by rhubarb-geek-nz** [comment]
Any process can only have one version of the CLR runtime active. So given PowerShell is already using CLR and the runtime runs in the same process choosing a different runtime is not an option.

However there is a better solution, eg use unit tests with a multiple framework project and it will enumerate each framework when running the tests, eg [UnitTests.csproj](https://github.com/rhubarb-geek-nz/AspNetForPowerShell/blob/main/UnitTests/UnitTests.csproj)

**Comment by lich8990** [comment]
Hi @jeharris-eci, I faced the same issue as you. Could you tell me where is this function?
var initialSessionState = **GetInitialSessionState**(ExecutionPolicy.Unrestricted, version); // Get the initial session state for the specified version
