### ISSUE TITLE
When remoting over 5.1, PWSH will instantly exit if we try to run it.

### ISSUE THREAD

**Issue by deathly809** [PowerShell/PowerShell#24189]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Enter-Psession -ComputerName "MyMachine" ...
2. Install PowerShell 7

```powershell
[string]$PowerShell_7_Uri = "https://github.com/PowerShell/PowerShell/releases/download/v7.4.4/PowerShell-7.4.4-win-x64.msi"
[string]$PowerShell_7_DownloadPath = "$( $PWD )\PowerShell-7.4.4-win-x64.msi"
[string]$PowerShell_7_InstallArguments = "/quiet ALLUSERS=1 REGISTER_MANIFEST=1 ADD_PATH=1 ENABLE_PSREMOTING=1"
$client = [System.Net.WebClient]::new();
$client.DownloadFile($PowerShell_7_Uri , $PowerShell_7_DownloadPath );
$client.Dispose();
$process = Start-Process -FilePath $PowerShell_7_DownloadPath  -ArgumentList $PowerShell_7_InstallArguments  -Wait -PassThru
```

3. Restart ```Restart-Computer -Force```
4. Enter-Psession -ComputerName "MyMachine" ...
5. Run PWSH
    a. This just displays version + initial "PS Path >" then exits with exit code 0

I have also tried 
* Multiple different flags to pwsh.exe (-ExecutionPolicy Unregisted, -NoExit, -Intteractive, -NoProfile) 
* Capturing the trace logs (F90714A8-5509-434A-BF6D-B1624C8A19A2) using logman but perfview just shows garbage when I open the ETLs. 
* Capturing the named providers.

### Expected behavior

```console
pwsh.exe does not exit.
```

### Actual behavior

```console
C:\tmp> pwsh.exe
PowerShell 7.4.4
PS C:\tmp>
<pwsh exits and returns to previous Windows PowerShell session"
C:\tmp>
```

### Environment data

```powershell
Will try to get $PSVersionTable, just redeployed the system and will take a few hours.

Internal testing environment for a Microsoft Product (i.e. we are moving to PowerShell Core for our product). Please reach out to jerobins if you want more information, or an environment.
```

**Comment by mklement0** [comment]
Unfortunately, remote sessions fundamentally do not support _interactive_ console applications, so the problem isn't specific to launching `pwsh.exe` - you'd see the same problem with `cmd.exe`, for instance.

If you want the remoting endpoint to use `pwsh.exe`, i.e. PowerShell 7:

* Enable remoting there with `Enable-PSRemoting`

* Then pass a `-ConfigurationName` argument to `Enter-PSSession` that targets this configuration. e.g. `Enter-PSSession -ConfigurationName PowerShell.7.4.5 -ComputerName $foo`

**Comment by kasini3000** [comment]
Unable to reproduce the issue, perhaps you should provide more details or test with a newly installed VM.

------

My testing environment:
The client, powershell v5.1 ，powershell 7.5
The server, powershell v5.1，powershell 7.2.19，powershell 7.4.5

Testing process:
From the client, use both PowerShell v5.1 and PowerShell 7.5 connect to the server's powershell v5, 
then enter pwsh.

**Comment by kasini3000** [comment]
Unable to reproduce the issue, perhaps you should provide more details or test with a newly installed VM.

------

My testing environment:
The client, powershell v5.1 ，powershell 7.5
The server, powershell v5.1，powershell 7.2.19，powershell 7.4.5

Testing process:
From the client, use both PowerShell v5.1 and PowerShell 7.5 connect to the server's powershell v5, 
then enter pwsh.

**Comment by deathly809** [comment]
> Unfortunately, remote sessions fundamentally do not support _interactive_ console applications, so the problem isn't specific to launching `pwsh.exe` - you'd see the same problem with `cmd.exe`, for instance.
> 
> If you want the remoting endpoint to use `pwsh.exe`, i.e. PowerShell 7:
> 
> * Enable remoting there with `Enable-PSRemoting` - though you may not be able to do so from a remote session targeting Windows PowerShell (`pwsh.exe -c Enable-PSRemoting` fails for me). However, it looks like remoting for the PowerShell 7 version was enabled as part of the installation, in your case.
> * Then pass a `-ConfigurationName` argument to `Enter-PSSession` that targets this configuration. e.g. `Enter-PSSession -ConfigurationName PowerShell.7.4.5 -ComputerName $foo`

Thanks for the info. I will keep trying to get it to work. I think I messed up with the Start-Process ArgumentList and should have made it an array of strings and not a single string. I think that is what was breaking normal remoting for me.

**Comment by mklement0** [comment]
@deathly809, no, it's fine to pass a _single string encoding all arguments_ to `Start-Process -ArgumentList` - in fact, it is preferable due to a long-standing bug: #5576

What I described is a _fundamental limitation of PowerShell remoting sessions_, which prevents them from running interactive terminal applications, notably including interactive shell sessions using a different shell from an `Enter-PSSession`-initiated session.

In the case at hand, the solution is to target PowerShell 7 directly as the remoting endpoint.
