### ISSUE TITLE
Release Process for v7.4.5 not found in winget

### ISSUE THREAD

**Issue by patricsjoo** [PowerShell/PowerShell#24187]
### Checklist

Why is winget not updated with latest but Microsoft Store is?
![image](https://github.com/user-attachments/assets/97b92caf-4d93-4e85-a138-b86cc4df1964)

**Comment by kennethSpence** [comment]
All download links only providing 7.4.4.0 including the MSI package links so it's not just winget.

**Comment by kilasuit** [comment]
There is always a small delay between releases here and them showing up in places like Winget
It is now available so closing this as resolved
