### ISSUE TITLE
Scriptblock logging not working on macOS

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PowerShell#24202]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create a `powershell.config.json` file in $PSHOME on macOS with the following settings.
   ```json
   {
       "ModuleLogging": {
           "EnableModuleLogging": false,
           "ModuleNames": [
               "PSReadLine",
               "PowerShellGet"
           ]
       },
       "ScriptBlockLogging": {
           "EnableScriptBlockInvocationLogging": true,
           "EnableScriptBlockLogging": true
       },
       "LogLevel": "verbose"
   }
   ```
2. Clear the logs in the macOS Console.app
3. Start a new PowerShell session and note the logging.

See the documentation https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging_non-windows?view=powershell-7.4#configuring-logging-on-linux-or-macos

We have reproduced the problem on Macs with @theJasonHelmick and @mikefrobbins.

### Expected behavior

```console
Expect to see scriptblock log entries.
```

### Actual behavior

```console
Jason got none in our test. Mike got it intermittently.
```

### Environment data

```powershell
PowerShell 7.4.3 and 7.4.4 on macOS 14.6.1 Sonoma
```

**Comment by sdwheeler** [comment]
This issue was reported to us by a customer (wustl.edu) that is trying to set this up.

**Comment by theJasonHelmick** [comment]
Thanks @sdwheeler -- will bring up next week and investigate.

**Comment by theJasonHelmick** [comment]
@sdwheeler - I investigate this with engineering and the script block logging is working as expected. The documentation steps are correct. We discovered that changes to the Apple logging system has made the Console.app on macOS no longer effective.  Instead, use the `log show` commands.

Example to retrieve pwsh events:
```
log show --predicate "subsystem == 'com.microsoft.powershell'" --style json
```
