### ISSUE TITLE
set-content expand variable option

### ISSUE THREAD

**Issue by marct22** [PowerShell/PowerShell#24211]
### Summary of the new feature / enhancement

If I set-content with value "$myvariablevaluesetpreviously", I run it, and it literally saves the output with that.  Which breaks my script as it has no idea what that value is. I want it to expand to the value of that variable.  How hard is this to do?

### Proposed technical implementation details (optional)

do something like set-content -path pathtofile -value '$myvariablevaluesetpreviously -somearg $somevalue' -expandvariable true

So if 
```
$myvariablevaluesetpreviously = "c:\users\myusername\I\installed\here
``` 
and 
```
$somevalue = "doit"
```
when set-value is executed,
 it sets the content of pathtofile to 
 ```
"c:\users\myusername\I\installed\here -somearg doit"
```
People have been requesting this for a while, hacks exist that are dumb hacks.  add this capability.

and unix bourne shell easily does that.
```
#!/bin/sh

myyvalue="hey you get out of my cloud"

myfile='./hey.txt'

echo $myyvalue > $myfile
```
cat hey.txt, it has 'hey you get out of my cloud' right there.  change the value of myyvalue, to 'blahblahblah', hey.txt changes to it.

really, how hard is that to provide such simple capability???

**Comment by jhoneill** [comment]
String interpolation with double quotes ? 

"$myvariablevaluesetpreviously -somearg $somevalue"

**Comment by SteveL-MSFT** [comment]
Single quotes means that argument is literal and isn't expanded.  As @jhoneill noted, double quotes has PowerShell expand variables (among other things) and that result is passed as an argument.  This is not specific to `Set-Content` and works the same for all cmdlets and commands.
