### ISSUE TITLE
404 on direct download marketplace url

### ISSUE THREAD

**Issue by TheRealBenForce** [PowerShell/PowerShell#2423]
I found this link for assistance in determining the link to resolve to an extension for direct downloads from the marketplace. 
https://code.visualstudio.com/docs/editor/extension-gallery

The link I came up with for Powershell 0.7.2 is this, however it does not resolve. I tried a few variations.
https://Microsoft.gallery.vsassets.io/_apis/public/gallery/publisher/Microsoft/extension/PowerShell/0.7.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

I tested the example link, and this does resolve.
https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/0.10.18/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

Steps to reproduce
------------------
Follow instructions at this link to compose direct download marketplace link. Place created link in browser:
https://code.visualstudio.com/docs/editor/extension-gallery

Expected behavior
-----------------
Link resolves to powershell marketplace vsix download.

Actual behavior
---------------
HTTP 404 Not Found

Environment data
----------------
n/a

**Comment by lzybkr** [comment]
vscode-powershell issues should be reported in https://github.com/PowerShell/vscode-powershell.
