### ISSUE TITLE
Add property "ConfigurationSource" to Get-DnsClientServerAddress

### ISSUE THREAD

**Issue by DerekBelanger** [PowerShell/PowerShell#24234]
### Summary of the new feature / enhancement

There currently isn't a commandlet which exposes the configuration source of DNSClientServerAddresses. This makes it cumbersome to test or swap configuration sources.

### Proposed technical implementation details (optional)

Please consider adding a property "ConfigurationSource" to Get-DnsClientServerAddress. This property should clearly indicate the ConfigurationSource of the DnsClientServerAddress ie. Static, DHCP, Auto, whatever.

**Comment by rhubarb-geek-nz** [comment]
I don't think this is part of this project. The DnsClient module looks like part of original the PowerShell Desktop

```
C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DnsClient>dir
 Volume in drive C is Local Disk
 Volume Serial Number is ACF6-E72D

 Directory of C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DnsClient

07/05/2022  09:00    <DIR>          .
08/11/2023  16:02    <DIR>          ..
07/05/2022  08:56             1,964 DnsClient.psd1
07/05/2022  08:56            17,850 DnsClientPSProvider.Format.ps1xml
07/05/2022  08:56             4,788 DnsClientPSProvider.Types.ps1xml
07/05/2022  08:56            61,640 DnsCmdlets.Format.ps1xml
07/05/2022  08:56            22,151 DnsCmdlets.Types.ps1xml
07/05/2022  08:56            23,188 DnsConfig.Format.ps1xml
07/05/2022  08:56             1,100 DnsConfig.Types.ps1xml
07/05/2022  08:56            38,912 dnslookup.dll
07/05/2022  08:56             4,504 MSFT_DnsClient.cdxml
07/05/2022  08:56             4,130 MSFT_DnsClientCache.cdxml
07/05/2022  08:56             3,854 MSFT_DnsClientDohServerAddress.cdxml
07/05/2022  08:56             1,306 MSFT_DnsClientGlobalSetting.cdxml
07/05/2022  08:56             3,613 MSFT_DnsClientServerAddress.cdxml
07/05/2022  08:56             5,188 PS_DnsClientNRPTGlobal_v1.0.0.cdxml
07/05/2022  08:56             1,704 PS_DnsClientNrptPolicy_v1.0.0.cdxml
07/05/2022  08:56            18,650 PS_DnsClientNRPTRule_v1.0.0.cdxml
              16 File(s)        214,542 bytes
```

**Comment by DerekBelanger** [comment]
Sorry, that's a bit over my head. I do know that Get-DnsClientServerAddress is an operable commandlet in my terminal running PS 7.4.5

**Comment by DerekBelanger** [comment]
Sorry, that's a bit over my head. I do know that Get-DnsClientServerAddress is an operable commandlet in my terminal running PS 7.4.5

**Comment by rhubarb-geek-nz** [comment]
Yes, if you look at the module path when running 7.4.5

```
$env:PSModulePath
```

You should see that the directory `C:\Windows\System32\WindowsPowerShell\v1.0\Modules` is included. So PowerShell 7 will run the commands provided by PowerShell Desktop.

**Comment by jhoneill** [comment]
`Get-DnsClientServerAddress | gm ` show that the command returns CIM objects, which don't includedthe source (as far as I can see) , if I missed something and one of the properties does indicate the source it's easy to change the formatting to show it.

I thought there might be a route via Get-NetIPConfiguration  but that seems to just return the objects via CIM.  

As @rhubarb-geek-nz  notes, these tools are provided by Windows not as part of the PowerShell 7 language, so a request to change the functions (or what CIM/WMI return for these classes) needs to go there.

**Comment by kilasuit** [comment]
As this is part of the modules shipped in Windows this would need to be raised in the Feedback Hub in Windows so am closing this as Resolution-External as unfortunately we can't resolve this like you are asking.

**Comment by kilasuit** [comment]
FYI Co-pliot thinks that you should be able to check for DHCP via 

```powershell
$dnsServers = Get-DnsClientServerAddress -InterfaceAlias "YourNetworkInterface"
$dnsServers | ForEach-Object {
    if ($_.AddressOrigin -eq "Dhcp") {
        Write-Output "The DNS server is obtained via DHCP."
    } else {
        Write-Output "The DNS server is statically assigned."
    }
}
```

**Comment by kilasuit** [comment]
You should be able to get DHCP/Static using this or similar code 
```powershell
Get-NetIPInterface -AddressFamily IPv4  | ForEach-Object {
    Write-Output $_.InterfaceAlias
if ($_.Dhcp -eq "Enabled") {
        Write-Output "The DNS server is obtained via DHCP."
    } else {
        Write-Output "The DNS server is statically assigned."
    }
}
```

**Comment by DerekBelanger** [comment]
Thanks @kilasuit. An IP interface can have DNS configured statically while IP/NM/GW are DHCP. The method you propose does not account for this split configuration. Split configuration is the very reason the feature I suggested is needed.
