### ISSUE TITLE
Executionpolicy set in GPO is ignored in Powershell 7.4.5

### ISSUE THREAD

**Issue by bdhirsch-code** [PowerShell/PowerShell#24238]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with PowerShell 7.4.5.  I set the execution policy for MachinePolicy using GPO to Allow All Scripts, but PowerShell 7.4.5 shows the policy as Restricted.  PowerShell 5.1.22621.3958 shows the policy as Unrestricted.  I can't run the InstallPSCorePolicyDefinitions.ps1 script that comes with V7.4.5 because the execution policy is Restricted and I can't change that.  If I try to run the script using the native Windows 11 executable (5.1.22621.3958) the script fails with an error.  I tried unblocking the script but that didn't change the situation.

### Expected behavior

```console
MachinePolicy = Unrestricted
```

### Actual behavior

```console
MachinePolicy = Restricted
```

### Error details

```console
When trying to run the PowerShell 7 script using the native Windows PowerShell executable:

PS C:\Program Files\PowerShell\7> InstallPSCorePolicyDefinitions.ps1
Test-Elevated : Cannot invoke method. Method invocation is supported only on core types in this language mode.
At C:\Program Files\PowerShell\7\InstallPSCorePolicyDefinitions.ps1:40 char:11
+ if (-not (Test-Elevated))
+           ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-Elevated], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,Test-Elevated
```

### Environment data

```powershell
PS C:\Program Files\PowerShell\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![PowerShellGPO](https://github.com/user-attachments/assets/15a06fab-46ab-4566-b1c2-159c19a539ca)
![PowerShellNewList](https://github.com/user-attachments/assets/2bf801a8-1bbb-4ebe-a358-6e76010246a5)
![PowerShellOldList](https://github.com/user-attachments/assets/f862d3c1-e2d1-4765-aeb7-3d4b090f429a)

**Comment by rhubarb-geek-nz** [comment]
Are you able to run it with 

```
C:\Program Files\PowerShell\7>pwsh -ExecutionPolicy ByPass InstallPSCorePolicyDefinitions.ps1
```

**Comment by mklement0** [comment]
Note: I don't know how _domain_-controlled GPOs fit into this picture.

* An `-ExecutionPolicy` CLI argument cannot override a GPO; however, something like `pwsh -nop { iex (Get-Content -Raw $PSHOME/InstallPSCorePolicyDefinitions.ps1) }` from an elevated session may work.

* Alternatively, you can modify PowerShell Core's machine-level GPO settings directly via the registry, at `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PowerShellCore` (requires elevation).

**Comment by bdhirsch-code** [comment]
> pwsh -ExecutionPolicy ByPass InstallPSCorePolicyDefinitions.ps1

No, it will not execute with ByPass.

![PowerShellBypass](https://github.com/user-attachments/assets/c9254ac9-4901-4207-a456-ec2641ac91af)

**Comment by bdhirsch-code** [comment]
> * An `-ExecutionPolicy` CLI argument cannot override a GPO; however, something like `pwsh -nop { iex (Get-Content -Raw $PSHOME/InstallPSCorePolicyDefinitions.ps1) }` from an elevated session may work.

![PowerShellPath](https://github.com/user-attachments/assets/37db4f3c-7196-4e96-bfa2-8611c04357f9)

**Comment by bdhirsch-code** [comment]
> * Alternatively, you can modify PowerShell Core's machine-level GPO settings directly via the registry, at `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PowerShellCore` (requires elevation).

This WORKED!  Hopefully this answer will help some other poor soul

**Comment by bdhirsch-code** [comment]
Modifying the registry directly solved the problem.

**Comment by mklement0** [comment]
Glad to hear it, @bdhirsch-code.

As for the error you saw with the `pwsh -noprofile { iex ... }` call: This looks like an old `Invoke-Expression` (`iex`) bug, #8778; I've updated my previous comment with a workaround.
