### ISSUE TITLE
Cannot install EWS via NuGet, Ubuntu 16.04 and 14.04

### ISSUE THREAD

**Issue by jwcrawley** [PowerShell/PowerShell#2424]
Steps to reproduce
------------------
install Powershell for Linux (stock Ubuntu 14.04 or 16.04 - tested with both)
execute powershell in terminal
PS :> Install-Package Microsoft.Exchange.WebServices   (as listed https://www.nuget.org/packages/Microsoft.Exchange.WebServices/ )
 

Actual behavior
---------------
Install-Package : No match was found for the specified search criteria and 
package name 'Microsoft.Exchange.WebServices'. Try Get-PackageSource to see 
all available registered package sources.
At line:1 char:1
+ Install-Package Microsoft.Exchange.WebServices
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPacka 
  ge:InstallPackage) [Install-Package], Exception
   + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.Pac 
  kageManagement.Cmdlets.InstallPackage

Expected behavior
-----------------
Should successfully install required module, so EWS can be utilized in Linux Powershell scripts. Tested on Windows machines, and completes/installs successfully.

Environment data
----------------

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.10                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

**Comment by andschwa** [comment]
Looks to me like package sources aren't setup. How did you add NuGet.org as a package source?

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShellGet#39
