### ISSUE TITLE
Status Line

### ISSUE THREAD

**Issue by xborke** [PowerShell/PowerShell#24242]
### Summary of the new feature / enhancement

Hey mates, I wish that there should be a plugin to allow embedding a status line into bottom of Windows  Terminal  Powershell like Tmux's status bar working in Linux

**Comment by jhoneill** [comment]
It's trivial to put info on the **top** of window (my profile puts an "Admin" indicator and the PowerShell version there.)
Is there any support in Windows Terminal for a status bar at the bottom? The Write-Progress cmdlet can update display a progress donut on the by calling something in WT, so if the a similar API can be called to set text instead of % complete, PowerShell can do it, otherwise... it's a much tougher ask.

**Comment by rhubarb-geek-nz** [comment]
You are describing a feature of [Tmux](https://github.com/tmux/tmux) which is effectively a terminal manager not a shell. The equivalent here would be [Windows Terminal](https://github.com/microsoft/terminal) implementing the feature, not PowerShell.

**Comment by xborke** [comment]
> You are describing a feature of [Tmux](https://github.com/tmux/tmux) which is effectively a terminal manager not a shell. The equivalent here would be [Windows Terminal](https://github.com/microsoft/terminal) implementing the feature, not PowerShell.
> 
> For instance on Linux you could run PowerShell in a Tmux session and get the behaviour you describe.

Thank you for your response, yes I also meant the "Windows Terminal" but in Powershell section
so can it be done by writing a Powershell script?

**Comment by xborke** [comment]
> It's trivial to put info on the **top** of window (my profile puts an "Admin" indicator and the PowerShell version there.) Is there any support in Windows Terminal for a status bar at the bottom? The Write-Progress cmdlet can update display a progress donut on the by calling something in WT, so if the a similar API can be called to set text instead of % complete, PowerShell can do it, otherwise... it's a much tougher ask.

Thanks for response, so can this API be done by typing a powershell script?

**Comment by rhubarb-geek-nz** [comment]
> Thanks for response, so can this API be done by typing a powershell script?

As far as I can tell Windows Terminal has no [suitable extension or plugin mechanism](https://github.com/microsoft/terminal/issues/15833).

**Comment by kasini3000** [comment]
#### my powershell  automation framework kasini3000 

```powershell
./cdos 'debian11' #choose all debian11 node on nodelist.csv
./k_run_os {   scriptblock on debian}
```

####  execute scriptblock on each controlled machine in order of k_run_os and display progress percentage on the title

https://gitee.com/chuanjiao10/kasini3000/blob/master/k_run_os.ps1

**Comment by xborke** [comment]
> Yes, Windows terminals only have tilebar and no status bar， Even if you get kasini3000 use “prompt” to store the “current node name” ， “current group name”

thanks one more time, could you please share screen shot? i really would like to see what it is looking like....

**Comment by kasini3000** [comment]
![QQ拼音截图20240910004243](https://github.com/user-attachments/assets/59ffd45c-e153-44ef-9f17-fb06e37e8961)
![QQ拼音截图20240910004307](https://github.com/user-attachments/assets/3b62954a-5604-492e-a094-879235e9da90)

**Comment by psmux** [comment]
[psmux](https://github.com/marlocarlo/psmux) provides exactly this — a customizable status line for your PowerShell terminal on Windows, working identically to tmux's status bar.

psmux maintainer here. psmux is a native Windows terminal multiplexer (ConPTY-based, no WSL/Cygwin) and the status bar is a first-class feature:

### Enable and customize

```bash
# Enable status bar
set-option -g status on

# Customize what it shows
set-option -g status-left "[#S] "
set-option -g status-right "%H:%M %d-%b-%y"
set-option -g status-style "bg=colour235,fg=colour136"
```

### What you can display

psmux supports [126+ format variables](https://github.com/marlocarlo/psmux/blob/main/docs/format-variables.md) — session name, window index, pane title, host, date/time, etc. The format strings are tmux-compatible, so you can use existing tmux status line configurations.

**Examples:**
- `#S` — session name
- `#W` — window name  
- `#H` — hostname
- `#(command)` — output of shell command (update intervals configurable)
- Conditional formatting with `#{?condition,true,false}`

### Reads `.tmux.conf`

If you already have a tmux config with status line settings, psmux reads it on Windows. Plugins like [tmux-cpu](https://github.com/marlocarlo/psmux-plugins/tree/main/psmux-cpu), [tmux-battery](https://github.com/marlocarlo/psmux-plugins/tree/main/psmux-battery), and [tmux-net-speed](https://github.com/marlocarlo/psmux-plugins/tree/main/psmux-net-speed) are available for richer status bar content.

### Install

```powershell
winget install psmux
```

Also via `cargo install psmux`, `scoop install psmux`, `choco install psmux`.

Current release: [v0.4.10](https://github.com/marlocarlo/psmux/releases/tag/v0.4.10) — MIT licensed.

This is a terminal multiplexer feature as the commenters noted — psmux brings that tmux-level terminal functionality natively to Windows PowerShell.
