### ISSUE TITLE
get-PrintConfiguration outputs a different value than was expected

### ISSUE THREAD

**Issue by BramVandendaele** [PowerShell/PowerShell#24249]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to get to know if a printer has colour enabled or not. 

- On the printserver I run the following command to retrieve the printerInfo
   - Get-PrintConfiguration  -PrinterName $printer

![afbeelding](https://github.com/user-attachments/assets/efd7dc0d-2f6d-4cfd-81a7-541bdb058e65)

As you can see from the powershell output. The Color is set to True. While on the print management page on the printserver it says NO

### Expected behavior

```console
Expected behaviour is that the powershell output and the output in print management are the same.
```

### Actual behavior

```console
The output is not the same.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rhubarb-geek-nz** [comment]
This is provided by the Windows Desktop version of PowerShell, not PowerShell 7.

```
PS D:\> (Get-Command Get-PrintConfiguration).Module.Path
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PrintManagement\PrintManagement.psd1
```

**Comment by mklement0** [comment]
To add some canned advice and links to @rhubarb-geek-nz's comment:

The [`PrintManagement`](https://learn.microsoft.com/en-us/powershell/module/printmanagement) module that `Get-PrintConfiguration` is a part of isn't being maintained in this repo, so the standard advice applies (taken from the now _obsolete_ [PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage) repo, emphasis added):

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

For more information, including custom function `Get-CommandOrigin` that can identify whether a given command's source code is maintained in this repository, see #23981

**Comment by jhoneill** [comment]
Further to the above, the commands return the CIM/WMI object for the printers and their configuration. If WMI gets the wrong information it's unlikely a PowerShell command will be able to fix it. This may be a widespread problem, or it may only affect a small number of printer drivers - on my machine everything reports as expected so I can't gauge that.
