### ISSUE TITLE
The $IsLinux variable is set to true on non-Linux platforms

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#24257]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am running PowerShell as a [native FreeBSD build](https://github.com/rhubarb-geek-nz/powershell-freebsd) using RID "freebsd-x64" and "freebsd-arm64".

### Expected behavior

```console
I would expect when on FreeBSD for $IsLinux to be false

I would expect $IsLinux to have the same value as [System.OperatingSystem]::IsLinux()
```

### Actual behavior

```console
PS> @{ IsWindows=$IsWindows;IsLinux=$IsLinux;IsMacOS=$IsMacOS }

Name                           Value
----                           -----
IsLinux                        True
IsMacOS                        False
IsWindows                      False

PS> [System.OperatingSystem]::IsLinux()
False
PS> [System.OperatingSystem]::IsFreeBSD()
True
```

### Error details

```console
no actual error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             FreeBSD 13.3-RELEASE FreeBSD 13.3-RELEASE releng/13.3-n257428-80d2b634ddf0 GENERIC
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0â€}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
good，It is time to new an automatic variable for freebsd:  $IsFreeBsd
for next：
After conducting a period of testing, find a way to let the compile into freebsd ports

**Comment by iSazonov** [comment]
> ```
> I would expect $IsLinux to have the same value as [System.OperatingSystem]::IsLinux()
> ```

It is exactly so in pwsh code.

> It is time to new an automatic variable for freebsd: $IsFreeBsd

Will be in https://github.com/PowerShell/PowerShell/pull/20041

**Comment by rhubarb-geek-nz** [comment]
That is excellent news!
