### ISSUE TITLE
why was Get-Help -Online removed?

### ISSUE THREAD

**Issue by whitequill** [PowerShell/PowerShell#24266]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

get-help New-Partition -Online

### Expected behavior

```console
it will redirect to https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-help?view=powershell-7.4&viewFallbackFrom=powershell-7.3
```

### Actual behavior

```console
It opens bing:
https://www.bing.com/?ref=go&linkid=816434
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![Screenshot 2024-09-09 220905](https://github.com/user-attachments/assets/9a2c06a6-4b24-4016-b70b-546356a287f5)

**Comment by 237dmitry** [comment]
> Expected behavior

This

**Comment by mklement0** [comment]
I cannot reproduce your symptom with respect to `New-Partition`, on my 
PowerShell Core v7.4.5 (.NET 8.0.8) on Microsoft Windows 11 Pro (ARM 64-bit Processor; Version 22H2, OS Build: 22621.4037) system.

However, there _is_ a bug with respect to using `Get-Help -Online` _in isolation_:
In the absence of a command to target it should either _fail_ or, preferably, default to targeting `Get-Help` itself.

That is, `Get-Help -Online` could  more helpfully act like `Get-Help -Online Get-Help`.

**Comment by jhoneill** [comment]
It's a slightly odd link that yours has gone to when I look I see there are two online help links 
`https://docs.microsoft.com/powershell/module/storage/new-partition?view=windowsserver2022-ps&wt.mc_id=ps-gethelp`
and 
`https://go.microsoft.com/fwlink/p/?LinkId=113387`

These may vary with the exact version of Windows there are windows 11 desktop. It's likely that for link-not-found one of those redirects to Bing.

If there is a broken link in a module supplied with Windows, not with PowerShell 7 that needs to go to the Windows team, not PowerShell 7 language.

**Comment by whitequill** [comment]
if I run `get-help new-partition -online in Powershell 5.1:
```
Name                           Value
----                           -----
PSVersion                      5.1.22621.4111
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4111
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
it returns:
```
get-help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help
topic is not specified in the command code or in the help file for the command.
At line:1 char:1
+ get-help new-partition -online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-Help], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.GetHelpCommand
    ```

**Comment by whitequill** [comment]
actually I have Windows 11 23H2.

**Comment by SteveL-MSFT** [comment]
You can observe the same issue in 5.1.

If you look at the `Storage` module manifest, the help URL points to `https://aka.ms/winsvr-2022-pshelp` which returns that the blob doesn't exist.  This needs to be reported via the Windows Feedback Hub (as noted above) so that the team that owns this can fix it on their end.

**Comment by mklement0** [comment]
@SteveL-MSFT:

While indeed reporting the issue via the Feedback Hub is likely the best avenue, note that your diagnosis 
doesn't explain the symptom, because even on my system - where `Get-Help -Online New-Partition` works fine - `(Get-Module -ListAvailable Storage).HelpInfoUri` too reports `https://aka.ms/winsvr-2022-pshelp`.

In fact, it's not even clear to me when said URI is actually ever used, given that `Get-Help` has no `-Category` value for _modules as a whole_.

Can you tell us when and where this URI is used?
