### ISSUE TITLE
https://aka.ms/pwsh-buildinfo-preview still return 7.5.0-preview.3

### ISSUE THREAD

**Issue by mdaneri** [PowerShell/PowerShell#24262]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The URL `https://aka.ms/pwsh-buildinfo-preview` return a `preview.json` file with old information

### Expected behavior

```console
{
  "ReleaseDate": "2024-08-28T18:13:56Z",
  "ReleaseTag": "v7.5.0-preview.4",
  "BlobName": "v7-5-0-preview-4"
}
```

### Actual behavior

```console
{
  "ReleaseDate": "2024-05-28T18:13:56Z",
  "ReleaseTag": "v7.5.0-preview.3",
  "BlobName": "v7-5-0-preview-3"
}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Being worked on

**Comment by mdaneri** [comment]
I can see that has been fixed 
Thanks
