### ISSUE TITLE
Question:  Why is https not permitted in HelpInfoUri?

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2427]
Just wondering why https is not permitted. When we doc'd in 3.0, any HelpInfoUri value with http or https was valid. The docs (https://msdn.microsoft.com/en-us/library/hh852735(v=vs.85).aspx) have not been updated.

**Comment by JKeithB** [comment]
Sorry, but am confused. The doc you points to says (under Step 2: Add a HelpInfoURI...) : For security, the address must begin with "http" or "https". The URI should specify an Internet location, but must not include the HelpInfo XML file name.
Is the problem that it's not working somewhere?

**Comment by SteveL-MSFT** [comment]
@juneb both should work, I think it only fails if you put in a https uri that redirects to an http uri

**Comment by SteveL-MSFT** [comment]
Latest helpinfouris are all using https
