### ISSUE TITLE
MenuComplete cannot handle ctrl+h as same as backspace

### ISSUE THREAD

**Issue by Xdminsy** [PowerShell/PowerShell#24277]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Run `pwsh -noprofile` for pure powershell start
2. Run `Set-PSReadLineOption -BellStyle None -EditMode Emacs` to bind emacs hotkeys, and `ctrl+h` can delete a character backward now.
4. Input `ls -` then press `ctrl+space` for MenuComplete, The `Path` is first completion so get highlighted
6. Press `L` and the `LiteralPath` is the possible completion, while the `iteralPath` is highlighted
7. Press `ctrl+h`

### Expected behavior

```console
Should be same as pressing backspace.
The actual command should be `ls -` and following a highlit `Path`
```

### Actual behavior

```console
The actual command becomes `ls -iteralPath`.
While the cursor is at character `i`.
It accepts the completion then delete a character backward.
```

### Environment data

```powershell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![menucomplete](https://github.com/user-attachments/assets/65fc6d2f-b7df-4825-a5a2-c6aa413e84a3)

**Comment by 237dmitry** [comment]
> then press ctrl+space for MenuComplete

I could not open menu. But it works with PSReadline's `Windows` mode. Imho, this is an issue of the PSReadline module, [ask them](https://github.com/PowerShell/PSReadLine/releases).

**Comment by Xdminsy** [comment]
Thanks, I've filed an issue there. https://github.com/PowerShell/PSReadLine/issues/4170
