### ISSUE TITLE
`Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0` command freezes in pwsh from microsoft store

### ISSUE THREAD

**Issue by soredake** [PowerShell/PowerShell#24283]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1) Install powershell from microsoft store
2) Do `Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0`
3) Comamnd will freeze and install nothing.

### Expected behavior

```console
`OpenSSH.Server` component should be installed.
```

### Actual behavior

```console
`Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0` command is freezing and installs nothing.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![изображение](https://github.com/user-attachments/assets/18694e33-6482-4ecd-a821-769ea39490b8)

**Comment by soredake** [comment]
![изображение](https://github.com/user-attachments/assets/49abebb0-2c9a-4ba2-ad48-f4a2d4e9cd41)

Same with `Disable-WindowsOptionalFeature` command

**Comment by mklement0** [comment]
The `Dism` module that the `Add-WindowsCapability`, ...,  cmdlets are a part of isn't being maintained in this repo, so the standard advice applies (taken from the now _obsolete_ [PowerShellModuleCoverage](https://github.com/PowerShell/PowerShellModuleCoverage) repo, emphasis added):

> NOTE To **report problems with _modules that ship in Windows_, use the _Windows Feedback Hub_**. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

For more information, including custom function `Get-CommandOrigin` that can identify whether a given command's source code is maintained in this repository, see #23981

---

So, unless you suspect that something _in PowerShell 7 itself_ is causing the hang, and that the module itself is not to blame (and works fine in _Windows PowerShell_), I suggest using the Feedback Hub.

**Comment by SteveL-MSFT** [comment]
There's a known issue with cmd dism cmdlets working with the PS7 MSIX.  This is being addressed on the cmdlet side and not something PS7 can fix.

**Comment by MartinGC94** [comment]
@SteveL-MSFT If the MSIX deployment option have limitations that module authors need to be aware of (like unavailable APIs) then I think that should be documented so other people don't make the same mistake that the DISM team apparently did.
