### ISSUE TITLE
Memory leak when transcription logging is enabled

### ISSUE THREAD

**Issue by KevinPeng24** [PowerShell/PowerShell#24282]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When the transcription logging is enabled, the runspace created for transcription logging is not correctly disposed, it leads a memory leak.

In this function , the method dispose() of PowerShell instance is not called, then the method dispose() of runspace created in the PowerShell instance won't be called.
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs#L1071
`        internal void TranscribeError(ExecutionContext context, InvocationInfo invocation, PSObject errorWrap)
        {
            context.InternalHost.UI.TranscribeCommandComplete(invocation);
            InitialSessionState minimalState = InitialSessionState.CreateDefault2();
            Collection<PSObject> results = **PowerShell.Create**(minimalState).AddCommand("Out-String").Invoke(
                new List<PSObject>() { errorWrap });
            TranscribeResult(results[0].ToString());
        }
`

Because of this runspace is not disposed, its record in the global variable s_runspaceDictionary will never be removed. The memory leak happen.
https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/hostifaces/Connection.cs#L1568
`
        protected virtual void Dispose(bool disposing)
        {
            lock (s_syncObject)
            {
                s_runspaceDictionary.Remove(Id);
            }
        }
`

### Expected behavior

```console
When transcription logging is enabled, the runspace is correctly disposed, no memory leak.
```

### Actual behavior

```console
Memory leak is observed.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17763.6292
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.6292
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by powercode** [comment]
The WG-Engine agrees that the Runspace should be properly disposed. 
Please provide a pull-request.
