### ISSUE TITLE
ConvertFrom-Markdown doesn't format multiline code blocks

### ISSUE THREAD

**Issue by rybal06** [PowerShell/PowerShell#24327]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Multiline markdown code blocks don't produce expected html.

1. Create markdown file with this content:
```md
# This is my code block
Some text explaining the code block:
```powershell
foreach ($item in $markdownRepro) {
  Write-Output "Processing $item..."
}
\```
```
(note, slash was added to to prevent GitHub issue editor from interpreting as markdown)

2. Read that file, and convert to html:
```powershell
(Get-Content ./template.md | ConvertFrom-Markdown).Html | out-file test.html
```
3. Observe html file

### Expected behavior

```console
<h1 id="this-is-my-code-block">This is my code block</h1>

<p>Some text explaining the code block:</p>

<pre><code class="language-powershell">
foreach ($item in $markdownRepro) {
  Write-Output "Processing $item..."
}
</code></pre>

<p>Some other text</p>
```

### Actual behavior

```console
<h1 id="this-is-my-code-block">This is my code block</h1>

<p>Some text explaining the code block:</p>

<pre><code class="language-powershell"></code></pre>

<p>foreach ($item in $markdownRepro) {</p>

<p>Write-Output &quot;Processing $item...&quot;</p>

<p>}</p>

<pre><code></code></pre>

<p>Some other text</p>
```

### Environment data

```powershell
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Darwin 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
In pwsh-7.5.0-preview.4 it works as expected:

```html
<h1 id="this-is-my-code-block">This is my code block</h1>
<p>Some text explaining the code block:</p>
<pre><code class="language-powershell">foreach ($item in $markdownRepro) {
  Write-Output &quot;Processing $item...&quot;
}
</code></pre>
```

**Comment by rybal06** [comment]
Good catch; I didn't realize that ConvertFrom-Markdown would accept a file directly. On the powershell version listed in the issue; when using Get-Content and passing to ConvertFrom-Markdown, the formatting is lost. When using ConvertFrom-Markdown directly to read the file, there is no issue.
