### ISSUE TITLE
`Sort-Object -Parallel`

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PowerShell#24338]
### Summary of the new feature / enhancement

Since PowerShell 7, PowerShell's engine has parallel processing capabilities which is used mainly by the `ForEach-Object` cmdlet.
But a `Sort-Object` cmdlet might also leverage from the parallel processing.
For a superficial PowerShell user, sorting an object list is often done with a single `Sort-Object` command where he doesn't care about the sorting algorithms but just the performance when he is sorting a million or more objects. For those users a `Sort-Object -Parallel` might show a PowerShell powershell improvement.

### Proposed technical implementation details (optional)

IMO, it should be possible to do a kind of parallel [merge sort](https://en.wikipedia.org/wiki/Sorting_algorithm) by first dividing the major groups over the existing processors. Let all processors sort their object list as usual and than merge the results to a single list.
Unfortunately, I don't have enough C# knowledge to build a C# prototype, but even with PowerShell, I am ably create a performance improvement of `20%` using a (3 threads) parallel merge sort, as shown here: [Custom Powershell sort function](https://stackoverflow.com/a/76146840/1701026)

**Comment by 237dmitry** [comment]
Not sure if it will give any performance gain. Let's see Foreach-Object:

```powershell
$ 0..999 | Foreach-Object -parallel { $_ }
$ 0..999 | Foreach-Object { $_ }
$ Get-History -Count 2                                             

  Id     Duration CommandLine
  --     -------- -----------
  52        1.317 0..999 | ForEach-Object -parallel { $_ }
  53        0.028 0..999 | ForEach-Object { $_ }
```

**Comment by iRon7** [comment]
@237dmitry,

What you simulating here is definitely not the same thing that I am proposing here. I recommend you to read about the [(merge) sort algorithms](https://en.wikipedia.org/wiki/Sorting_algorithm) or check my [PowerShell prototype](https://stackoverflow.com/a/76146840/1701026) (as in the original propose).
For your background, to correctly simulated this, you will need to divide the `1000` (`0..999`) over the amount of processors you have available (e.g. `4`). Each processor gets an even amount of objects to sort (`250` in this example). When they done with the you collect the result. The advantage is that lays in the fact that you know that the `250` objects are already sorted, meaning that you will need 4 indices to point to each of the 4 list which will move only forward until you collected all the `1000` objects.
(note that due to the overhead, `1000` is probably also not a good example, I expect performance improvement to noticeable with objects list larger than `100.000` or so.)

FYI: Java has a [`parallelsort` method](https://www.geeksforgeeks.org/java-8-arrays-parallelsort-method-with-examples/) too.
