### ISSUE TITLE
Code coverage data should be available for PowerShell core

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#2434]
# testability

see https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/TestRoadmap.md

**Comment by SteveL-MSFT** [comment]
#2585

**Comment by joeyaiello** [comment]
@JamesWTruher same question as in #2435

**Comment by adityapatwardhan** [comment]
#3914

**Comment by adityapatwardhan** [comment]
Fixed by #3914
