### ISSUE TITLE
Invoke-WebRequest return behaves unexpectedly when setting to a variable

### ISSUE THREAD

**Issue by miketheitguy** [PowerShell/PowerShell#24349]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Steps to reproduce:

Valid test of URL which results in a 200 status code.
`$res = Invoke-WebRequest -Uri "https://www.google.com" ; $res.statuscode`

Re-run the same request with an unknown hostname, and the status code still returns 200.
`$res = Invoke-WebRequest -Uri "https://www.googleslkdjflsjdljf.com" ; $res.statuscode`

### Expected behavior

```console
The expected behavior here would be that since $res in the 2nd scenario has errored out due to no such host, that $res would be populated with some flavor of error data. Whether $res.StatusCode would be $null or some other value.
```

### Actual behavior

```console
$res returns the previously returned status code but writes an error output that no such host is known via invoke-webrequest.
```

### Environment data

```powershell
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      5      0      preview.4
```

**Comment by 237dmitry** [comment]
The `$res` variable is still alive at the second attempt:

![ss](https://github.com/user-attachments/assets/33bfbad5-74ac-40ae-a748-384f4a40ec33)

Most likely because the variable is not overwritten when the exception on the right side of the expression cannot be caught.

**Comment by mklement0** [comment]
Indeed, `Invoke-WebRequest -Uri "https://www.googleslkdjflsjdljf.com"` creates a _statement-terminating_ error (uncaught exception), which means that _no assignment takes place_ so it is a _preexisting_ `$res` variable, if any, that remains in effect.

The solution is to use something like `$res = try { Invoke-WebRequest -Uri "https://www.google.com" } catch { }`

The behavior may be surprising, especially compared to other shells, but it has always worked this way, and changing it now would likely be considered an unacceptable breaking change, given that existing code may rely on the target variable to stay untouched in the event of a statement-terminating error.
