### ISSUE TITLE
PowerShell Core test result data should be available via public dashboard

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#2435]
# testability

this should include results from daily run as well as CI
see https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/TestRoadmap.md

**Comment by joeyaiello** [comment]
@JamesWTruher isn't this technically done? Or are we leaving it open until we have good coverage numbers again?

**Comment by SteveL-MSFT** [comment]
We should do this, but this doesn't block 6.0.0 release

**Comment by JamesWTruher** [comment]
this is done
