### ISSUE TITLE
unable to replace a string by `$`

### ISSUE THREAD

**Issue by Taoduhui** [PowerShell/PowerShell#24356]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have such a string `{item}.title -match $("4.2.24" -replace '-r0*', '.')`, I want to replace the `{item}` to `$_` (not variable, I mean text `$_`).

### Expected behavior

```console
PS> $expr = "{item}.title -match `$(`"4.2.24`" -replace '-r0*', '.')"
PS> $expr -replace '{item}',"`$_" 
"$_.title -match `$(`"4.2.24`" -replace '-r0*', '.')"
PS> $expr -replace '{item}','$_' 
"$_.title -match `$(`"4.2.24`" -replace '-r0*', '.')"
```

### Actual behavior

```console
PS> $expr = "{item}.title -match `$(`"4.2.24`" -replace '-r0*', '.')"
PS> $expr -replace '{item}',"`$_" 
{item}.title -match $("4.2.24" -replace '-r0*', '.').title -match $("4.2.24" -replace '-r0*', '.')
PS> $expr -replace '{item}','$_'
{item}.title -match $("4.2.24" -replace '-r0*', '.').title -match $("4.2.24" -replace '-r0*', '.')
```

### Error details

```console
Not an Error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
```
$expr = "{item}.title -match `$(`"4.2.24`" -replace '-r0*', '.')"
$expr -replace '{item}', '$$_'  
```

```
$_.title -match $("4.2.24" -replace '-r0*', '.')
```

**Comment by mklement0** [comment]
Indeed, `$` has special meaning _to the .NET regex engine_ in the substitution operand of the `-replace` operator, so it must be _escaped_ in order to be used verbatim.
As @237dmitry's solution shows, escaping requires _doubling_ the character, i.e. `$$`

See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Comparison_Operators#regular-expressions-substitutions and  https://learn.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions
