### ISSUE TITLE
Set-executionpolicy cannot set executionpolicy

### ISSUE THREAD

**Issue by max9836** [PowerShell/PowerShell#24358]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I was trying to set execution policy as bypass in pwsh v.7.4.5 admin mode, but I could not put it to bypass. The only way I could overcome this problem is to edit directly in Registry.

### Expected behavior

```console
PS C:\Users\Max> get-executionpolicy
Restricted
PS C:\Users\Max> set-executionpolicy bypass
PS C:\Users\Max>  Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell

Path            : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ExecutionPolicy : Bypass
PSPath          : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Micro
                  soft.PowerShell
PSParentPath    : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds
PSChildName     : Microsoft.PowerShell
PSDrive         : HKLM
PSProvider      : Microsoft.PowerShell.Core\Registry
PS C:\Users\Max> get-executionpolicy
Bypass
```

### Actual behavior

```console
PS C:\Users\Max> get-executionpolicy
Restricted
PS C:\Users\Max> set-executionpolicy bypass
PS C:\Users\Max>  Get-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell

Path            : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
ExecutionPolicy : Restricted
PSPath          : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Micro
                  soft.PowerShell
PSParentPath    : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds
PSChildName     : Microsoft.PowerShell
PSDrive         : HKLM
PSProvider      : Microsoft.PowerShell.Core\Registry
PS C:\Users\Max> get-executionpolicy
Bypass
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iRon7** [comment]
> I was trying to set execution policy as bypass in pwsh v.7.4.5 admin mode, but I could not put it to bypass. The only way I could overcome this problem is to edit directly in Registry.

What let's you believe that `HKLM:\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell` holds the Execution Policy for PowerShell 7?

It looks like your expectation is that the *Windows* PowerShell and PowerShell (*core*) share the same Execution Policy, which is not the case:

```
pwsh -Command Get-ExecutionPolicy # PowerShell (7)
RemoteSigned
PowerShell -Command Get-ExecutionPolicy # Windows PowerShell (5.1)
Unrestricted
```

Which also presumably answers your issue: if you want to set the *Windows* PowerShell Execution Policy from PowerShell 7, you might use the command:

```PowerShell
PowerShell -Command Set-ExecutionPolicy Bypass
```

**Comment by mklement0** [comment]
Good points, @iRon7, but the registry location you state relates to execution policies controlled _via GPOs_, which is unrelated to `Set-ExecutionPolicy` calls.

Execution policies set with `Set-ExecutionPolicy [-Scope LocalMachine` aren't stored in the registry but rather in a file, `$PSHOME\powershell.config.json`, in the `"Microsoft.PowerShell:ExecutionPolicy"` property.

For `-Scope CurrentUser` it is `"$([Environment]::GetFolderPath('MyDocuments'))/powershell/powershell.config.json"`

**Comment by max9836** [comment]
@iRon7 As I mentioned in my issue content, the only way I solved this is to set that registry to Bypass. 
If you ask me where did I find this registry path. Here is where:

```
PS C:\Users\Max> set-executionpolicy

cmdlet Set-ExecutionPolicy at command pipeline position 1
Supply values for the following parameters:
ExecutionPolicy: unrestricted
set-executionpolicy : Access to the registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft
.PowerShell' is denied. To change the execution policy for the default (LocalMachine) scope, start Windows PowerShell w
ith the "Run as administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -S
cope CurrentUser".
At line:1 char:1
+ set-executionpolicy
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetExecutionPolicyComma
   nd
PS C:\Users\Max>```

I ran this command in PowerShell 7. After realizing PowerShell 5 and PowerShell 7 have different execution policies, it solved my problem. Thank you.
