### ISSUE TITLE
Use the AppData Folder for Configuration Files

### ISSUE THREAD

**Issue by AdreKiseque** [PowerShell/PowerShell#24363]
### Summary of the new feature / enhancement

PowerShell currently, for whatever reason, drops its configuration files in the Documents folder. I do have to say this is a bit irritating, since Documents is where I store various documents that I access on a more frequent basis, and is one of the folders I keep synced to OneDrive so I can access its files from anywhere. It's certainly not a place I want to be having configuration files that I would rarely want to be directly accessing, and ones that are only relevant to the installation of a particular program on one specific device. Instead, I propose the default location for these files be changed to the AppData folder, which exists specifically for programs to store their configuration files.

**Comment by kilasuit** [comment]
This is a dup of #15552 so closing in favour of that
