### ISSUE TITLE
Cross-plat remoting tests need to be available for PowerShell Core

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#2436]
# testability

we need to test between all the available platforms (Core and Full) as well as SSH/OMI
see: https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/TestRoadmap.md

**Comment by SteveL-MSFT** [comment]
We also need to include perf comparison between PSRP over SSH and WSMan.  Also scale for fan-out.
