### ISSUE TITLE
Get-ChildItem returns nothing if -Path contains []

### ISSUE THREAD

**Issue by timthedevguy** [PowerShell/PowerShell#24361]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

To recreate please create the following directory structure.

```
C:\Test\
C:\Test\[core]\
C:\Test\[core]\test.txt
```

Running ```Get-ChildItem -Path "C:\Test\[core]" -Recurse``` runs fine but returns nothing.  Running ```Get-ChildItem -Path "C:\Test" -Recurse``` works as intended however.

### Expected behavior

```console
PS> Get-ChildItem -Path "C:\Test\[core]" -Recurse

    Directory: C:\Test\[core]


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2024-09-30     08:00              0 test.txt
```

### Actual behavior

```console
PS> Get-ChildItem -Path "C:\Test\[core]" -Recurse
PS>
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/user-attachments/assets/755a1102-b6bf-41ec-8a1b-9da35d4813b0)

**Comment by iRon7** [comment]
This is know issue, see e.g. StackOverfflow:

* [Is Get-ChildItem -Recurse broken when there are square brackets in the input path?](https://stackoverflow.com/questions/33721892/is-get-childitem-recurse-broken-when-there-are-square-brackets-in-the-input-pat)
* [Dealing with a variable containing a path with brackets](https://stackoverflow.com/questions/57604315/dealing-with-a-variable-containing-a-path-with-brackets)
* [powershell get-childitem not finding files that contains [ ] [duplicate]](https://stackoverflow.com/questions/73128510/powershell-get-childitem-not-finding-files-that-contains)

The solution is to use the [`-LiteralPath` parameter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem#-literalpath)

**Comment by timthedevguy** [comment]
Escaping with a backtick produces the same results, sorry, I left that out
![image](https://github.com/user-attachments/assets/6d2d9532-da15-44fd-9af5-2a5b993a20dc)

**Comment by timthedevguy** [comment]
@iRon7 I googled and googled and never hit someone that had the same issue, thank you for the LiteralPath, that did it, never even noticed that

**Comment by MartinGC94** [comment]
FYI the reason why your escaped backtick didn't work was because of your use of double quotes. In double quoted (or unquoted) strings you need 2 backticks, one to escape the backtick in the string interpretation and another to escape the actual char in the path provider.

**Comment by timthedevguy** [comment]
Martin, you just blew my mind, I've never ran into a situation that calls for a double backtick, super interesting info, thanks so much for that!
