### ISSUE TITLE
nav bar 

### ISSUE THREAD

**Issue by ParvamShah1** [PowerShell/PowerShell#24373]
### Summary of the new feature / enhancement

The navbar can be more well designed and moves up with the website when i scroll down to the website the navbar is not accessible which makes it difficult for the user to use it.user has to scroll it the top again to access the navbar 
IN THIS IMAGE THE NAV BAR IS NOT ACCESSIBLE T THE USER . 
https://github.com/user-attachments/assets/d39a14d7-eda4-47bb-8a6f-5d6b12415bfe

**Comment by mklement0** [comment]
Your feedback appears to a be about a _documentation web page_ associated with PowerShell, so this repository isn't the right place to report this issue, presumably https://github.com/MicrosoftDocs/PowerShell-Docs/issues is.
