### ISSUE TITLE
Start-Process - Allow redirecting output while using a verb

### ISSUE THREAD

**Issue by ChristopherJTrent** [PowerShell/PowerShell#24388]
### Summary of the new feature / enhancement

As it is, there's no way I can find to actually get output from start-process if I'm starting a process as admin.
I'd really like it if there were some functionality that would allow me to see what the program I'm starting is printing to standard out, as that includes important debug information that I cannot get otherwise. 

Some proposals:
* allow the use of RedirectStandardOutput and RedirectStandardError when using Verb RunAs
* Allow the use of NoNewWindow when using Verb RunAs
* Add the ability for the spawned powershell window to be prevented from closing so standard output can be read

**Comment by jborean93** [comment]
This is unfortunately not possible as the underlying verb execution goes through [ShellExecuteEx](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecuteexw) which does not expose a way way to redirect the output.

**Comment by ChristopherJTrent** [comment]
That is unfortunate.
Such is life, I understand that it'd be a massive, compatibility breaking undertaking to implement this functionality.

Thanks for the answer

________________________________
