### ISSUE TITLE
Failures from Enable-WindowsOptionalFeature should refer to C:\windows\logs\dism\dism.log 

### ISSUE THREAD

**Issue by labo-pdc** [PowerShell/PowerShell#24385]
### Summary of the new feature / enhancement

When Enable-WindowsOptionalFeature fails, it is usually due to some error from DISM.
The error output from Enable-WindowsOptionalFeature is usually very misleading, and it would be better to refer to $env:windir\logs\dism\dism.log
Manually invoking DISM to install Windows features refers to $env:windir\logs\dism\dism.log, so I would argue that Enable-WindowsOptionalFeature should refer to the log file as well.

For additional motivation, see the following bug reports against PowerShell, which are probably caused by issues elsewhere:
- https://github.com/PowerShell/PowerShell/issues/18476
- https://github.com/PowerShell/PowerShell/issues/13866

My motivation, is that I recently debugged an issue where Enable-WindowsOptionalFeature failed with errorcode -2147221164 / "class not registered", like in the linked github issues.
It turned out that the cause of the issue was that I DISM attempted to move the following file C:\inetpub\custerr\en-US\401-1.htm, but the file (and its folder) did not exist on my computer, see the following stackoverflow post: 
https://stackoverflow.com/questions/76080157/dism-exe-works-but-get-windowsoptionalfeature-powershell-fails
Once I created the file Enable-WindowsOptionalFeature was able to install the Windows features, which among other things created the missing file.

I found out that C:\inetpub\custerr\en-US\401-1.htm was missing, by installing the the Windows feature via DISM, which referred to C:\windows\logs\dism\dism.log, which referred to C:\windows\logs\cbs\cbs.log, which said that it failed to move C:\inetpub\custerr\en-US\401-1.htm to a temporary folder.

The true cause of my particular issue is probably a bug in the code that installed the Windows feature, but I would have been easier to debug if Enable-WindowsOptionalFeature had referred to $env:windir\logs\dism\dism.log
PowerShell has a bunch of DISM wrappers, which could probably all use an error message referring to $env:windir\logs\dism\dism.log, og maybe you can get the actual error message from DISM.
The error message that I got from Enable-WindowsOptionalFeature (errorcode -2147221164 / "class not registered") is was not helpful to me, and I think that the PowerShell issues that I linked to previously show that the error message is not helpful to others.

### Proposed technical implementation details (optional)

Failures from Enable-WindowsOptionalFeature should refer to $env:windir\logs\dism\dism.log if the failure comes from a DISM invokation.
Alternatively, try to forward the error message from DISM in exception raised by Enable-WindowsOptionalFeature.

The same change would be welcome in other PowerShell cmdlets calling DISM.

**Comment by rhubarb-geek-nz** [comment]
`Enable-WindowsOptionalFeature` is not provided by PowerShell 7

```
PS> (Get-Command Enable-WindowsOptionalFeature).Module.ModuleBase
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Dism
```

See [Can Windows/Non-Core Powershell 5 bugs be reported here?](https://github.com/PowerShell/PowerShell/discussions/24299)

**Comment by labo-pdc** [comment]
Ok. I'm closing this issue and I created the issue in to the Microsoft Feedback Hub instead: https://aka.ms/AAslo5k
