### ISSUE TITLE
New-Object Hashtable makes properties case sensitive

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShell#2440]
Raising here as per reported at https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/60
and https://github.com/PowerShell/PowerShellGet/issues/7

**Comment by lzybkr** [comment]
This is by design. You are calling the default constructor of a class in .Net. To do anything else would be incorrect.

**Comment by GeeLaw** [comment]
If you want case-insensitive `HashTable`, pass an appropriate `IHashCodeProvider` and an appropriate `IEqualityComparer`. There is an overload available among the constructors.

I guess when you `@{}`, you get case-insensitive hash code provider and equality comparer.
