### ISSUE TITLE
PowerShell Fails to Recognize and Process Files in Folders with Complex Naming Structures

### ISSUE THREAD

**Issue by ajax1337** [PowerShell/PowerShell#24424]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

PowerShell, including versions 5.1 and 7.4.5, fails to recognize files within folders that have complex naming structures, especially when the folder name ends in a file extension (e.g., .mkv) and contains special characters. Despite renaming or simplifying access paths, PowerShell does not consistently detect or move files in such directories, impacting automation and file management.

Steps to Reproduce:

1.Create a folder with a complex name that includes special characters, spaces, and a file-like suffix (such as .mkv or .txt).

Example Folder Name Pattern:

D:\Test\ComplexFolderName - Example (2024) [Info - More Info - 600MB].mkv

2.Place a file inside this folder with the same complex name, also ending in .mkv:

Example File Name Pattern:
scss

ComplexFolderName - Example (2024) [Info - More Info - 600MB].mkv

3.Attempt to list and move the file using PowerShell:

powershell
Copy code
# Define paths
$folderPath = "D:\Test\ComplexFolderName - Example (2024) [Info - More Info - 600MB].mkv"
$filePath = "$folderPath\ComplexFolderName - Example (2024) [Info - More Info - 600MB].mkv"

# Attempt to list and move the file
if (Test-Path -Path $filePath) {
    Move-Item -Path $filePath -Destination "J:\TargetFolder" -Force
}

### Expected behavior

```console
PowerShell should detect the file within the specified folder and allow standard operations, such as listing or moving the file to another directory.
```

### Actual behavior

```console
PowerShell does not recognize the file inside the folder. Commands like Get-ChildItem and Test-Path either fail silently or indicate that the file does not exist, even though it is accessible in File Explorer. Attempts to simplify access by renaming the folder or removing the .mkv suffix yield inconsistent results.
```

### Environment data

```powershell
PowerShell Versions Tested: 5.1.22621.4249 (Windows PowerShell) and 7.4.5 (PowerShell Core)

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
The problem here is the `[` and `]` characters which is used for wildcard pattern matching https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.4. By default most provider cmdlets do wildcard matching by default (one main exception is `New-Item`). When you encounter a path with these wildcard pattern characters you either have to use the `-LiteralPath` parameter or escape the character with a backtick. For example

```powershell 
Set-Content -LiteralPath 'foo-[test].txt' -Value value
Get-ChildItem -Name
# foo-[test].txt

# Using -LiteralPath and not -Path
Move-Item -LiteralPath 'foo-[test].txt' -Destination 'bar-[test].txt'
Get-ChildItem -Name
# bar-[test].txt

# Using backtick escape (single quoted string)
# Because it's in a single quoted string you don't need to escape the `
Move-Item -Path 'bar-`[test`].txt' -Destination 'foo-[test].txt'
Get-ChildItem -Name
# foo-[test].txt

# Using backtick escape (double quoted string)
# Because it's in a double quoted string you do need to escape the `
Move-Item -Path 'foo-``[test``].txt' -Destination 'bar-[test].txt'
Get-ChildItem -Name
# bar-[test].txt
```

You can also pipe in a file object and it'll bind to the `-LiteralPath/-PSPath` parameter for you

```powershell
$file = Get-Item -LiteralPath 'bar-[test].txt'
$file | Move-Item -Destination 'foo-[test].txt'
Get-ChildItem -Name
# foo-[test].txt
```
