### ISSUE TITLE
PowerShell should have a remote session inactive timeout clean up option

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2444]
This has been requested by multiple users.  Currently a PowerShell remote session lifetime is governed solely by the client.  A remote session will remain on a target machine as long as the client maintains a connection to it and the client decides when the session is terminated.

The only exception is if the session becomes disconnected whether from network issues or through a manual disconnect operation.  In this case the "IdleTimeout" parameter determines how long the orphaned session remains on the server and will terminate the session after the timeout time has elapsed.

But many users would like to have the option of terminating a remote session if it has been inactive (no commands or scripts run in it) for a specified period of time.

This would be a new feature and so an RFC document should be generated.

**Comment by SteveL-MSFT** [comment]
This seems unnecessary in a PSRP/SSH world

**Comment by PaulHigin** [comment]
It is still a problem with SSH since it is a feature of PSRP (PowerShell Remoting Protocol).  Some users would like to better monitor/manage activate remote endpoints on their systems.  They would like to be able to terminate sessions on the target system for some users.  I believe the scenarios are related to PSWS (PowerShell Web Services) where active sessions become abandoned and use system resources.  But I haven't really thought through the issues (privacy?, how such a feature might be abused?) or how PSRP could be modified to support this.  This should be discussed in an RFC.

**Comment by SteveL-MSFT** [comment]
We should do some more research on this on how SSH admins do this today.  My preference is to leverage SSH conventions/tooling where possible.
