### ISSUE TITLE
Get-NetIPAddress show if IPv6 address is temporary

### ISSUE THREAD

**Issue by Worldwidebrine** [PowerShell/PowerShell#24466]
### Summary of the new feature / enhancement

`netsh` prints "Temporary" as AddrType.
I can't find any alternative member in `Get-NetIPAddress`.

### Proposed technical implementation details (optional)

Add IPAddressInformation.IsTransient?

**Comment by rhubarb-geek-nz** [comment]
As far as I can tell, `Get-NetIPAddress` is not part of PowerShell 7

```
PS> (Get-Command Get-NetIPAddress).Module.ModuleBase
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetTCPIP
```

I suggest see [Can Windows/Non-Core Powershell 5 bugs be reported here?](https://github.com/PowerShell/PowerShell/discussions/24299)
