### ISSUE TITLE
How can I define a convenient Join-String function?

### ISSUE THREAD

**Issue by Zim-Inn** [PowerShell/PowerShell#24462]
### Summary of the new feature / enhancement

I often use powershell to deal data. For example, I use `rg` in powershell to find strings.
The command is like
```powershell
$aList = someCommand's output;
$myRegex = "(wordA)|(wordB)|(sentenceA) ..."
$aList | rg -e $myRegex
```
I might build $myRegex from a file such as `cat list | ForEach-Object -Process {"(" + $_ + ")"} | Join-String -Separator "|"`

`list` is a text file which contains serveal lines.

And finally I want to save `ForEach-Object -Process {"(" + $_ + ")"} | Join-String -Separator "|"` as a function.

When I define the function like this 
```powershell
function Join2OrLogicRegex {$args | ForEach-Object -Process {"(" + $_ + ")"} | Join-String -Separator "|"}
```
It works for
![image](https://github.com/user-attachments/assets/16733de8-896a-4d1a-9125-01b8bb5b1842)
But when I try `cat list | Join2OrLogicRegex ` , it shows that Join2OrLogicRegex 's $args.Count = 0

When I try to add pipeline support,
```powershell
param(
        [Parameter(ValueFromPipeline)]
        [object[]]$args
    )
```
It can works as I expect in the condition `Join2OrLogicRegex (cat list)`
But in `Join2OrLogicRegex (cat list)` , I always get the last line in the file `list`.

**Comment by santisq** [comment]
`$args` represents the positional arguments, it's not populated on pipeline input but you can use [`$input`][1]. So the function could look something like:

```powershell
function Join2OrLogicRegex {
    if ($MyInvocation.ExpectingInput) {
        $result = $input | ForEach-Object -Process { '(' + $_ + ')' }
    }
    else {
        $result = $args | ForEach-Object -Process {"(" + $_ + ")"}
    }

    $result | Join-String -Separator '|'
}
```


[1]: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.4#input

**Comment by Zim-Inn** [comment]
Cool! It's very cool. Thanks for help .
And I add one extra conditon :
```powershell
function Join2OrLogicRegex {
    if ($MyInvocation.ExpectingInput) {
        $result = $input | ForEach-Object -Process { '(' + $_ + ')' }
    }
    else {
        [string[]] $strs = $args
        if ($strs.Count -eq 1)
        {
            $strs = $strs.Split()
        }
        $result = $strs | ForEach-Object -Process {"(" + $_ + ")"}
    }

    $result | Join-String -Separator '|'
}
```
so that it can handle `Join2OrLogicRegex (cat list)` as my expect.

**Comment by santisq** [comment]
> Cool! It's very cool. Thanks for help . And I add one extra conditon :
> 
> ```powershell
> function Join2OrLogicRegex {
>     if ($MyInvocation.ExpectingInput) {
>         $result = $input | ForEach-Object -Process { '(' + $_ + ')' }
>     }
>     else {
>         [string[]] $strs = $args
>         if ($strs.Count -eq 1)
>         {
>             $strs = $strs.Split()
>         }
>         $result = $strs | ForEach-Object -Process {"(" + $_ + ")"}
>     }
> 
>     $result | Join-String -Separator '|'
> }
> ```
> 
> so that it can handle `Join2OrLogicRegex (cat list)` as my expect.

In the case of a single string you might want to consider using `-split` on the left side instead of the `Split()` because it will get rid of extra white-spaces, for example:

```powershell
PS ..\> '1  2  3'.Split() | ForEach-Object { "[$_]" }
[1]
[]
[2]
[]
[3]

PS ..\> -split '1  2  3' | ForEach-Object { "[$_]" }
[1]
[2]
[3]
```

**Comment by IISResetMe** [comment]
`Join-String` already affords you the option to format each item:

```pwsh
Join-String -FormatString '({0})' -Separator '|' -InputObject a,b,c
# or 
-split 'a b c' |Join-String -FormatString '({0})' -Separator '|'
```

The only real upside of rolling your own is that you can add a regex escape hatch (pun definitely intended):

```pwsh

function Join2OrLogicRegex {
    param([switch]$EscapeTerms)

    $termProcessor = { "($($EscapeTerms ? [regex]::Escape($_) : $_))" }

    if ($MyInvocation.ExpectingInput) {
        $result = $input |ForEach-Object -Process $termProcessor
    }
    else {
        [string[]] $strs = $args.Length -lt 2 ? (-split $args) : $args
        $result = $strs |ForEach-Object -Process $termProcessor
    }

    $result |Join-String -Separator '|'
}
```

```pwsh
PS ~> -split 'a *' |Join2OrLogicRegex
(a)|(*)
PS ~> -split 'a *' |Join2OrLogicRegex -EscapeTerms
(a)|(\*)
```
