### ISSUE TITLE
`test-path $null` throws error

### ISSUE THREAD

**Issue by rkitover** [PowerShell/PowerShell#24468]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
test-path $null
```

### Expected behavior

```console
$false
```

### Actual behavior

```console
Test-Path: Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')
```

### Error details

```console
Exception             :
    Type      : System.ArgumentNullException
    Message   : Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')
    ParamName : The provided Path argument was null or an empty collection.
    HResult   : -2147467261
CategoryInfo          : InvalidArgument: (:) [Test-Path], ArgumentNullException
FullyQualifiedErrorId : NullPathNotPermitted,Microsoft.PowerShell.Commands.TestPathCommand
InvocationInfo        :
    MyCommand        : Test-Path
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 1
    Line             : test-path $null
    Statement        : test-path $null
    PositionMessage  : At line:1 char:1
                       + test-path $null
                       + ~~~~~~~~~~~~~~~
    InvocationName   : test-path
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
      0
      1
```

### Environment data

```powershell
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.27729
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasini3000** [comment]
use:
if not $null or not '',
or try { test-path ... } catch {}

**Comment by mklement0** [comment]
I agree that not failing and outputting `$false` is the more sensible behavior, given that the very purpose of the cmdlet is to test the validity of the given path _itself_.

As usual, however, the question is whether changing this behavior now will break existing code.

Hypothetically, there's code out there that relies on the error, such as aborting execution via 
`$ErrorActionPreference = 'Stop'`

In order to establish that the suggested change would amount to an acceptable [bucket 3](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area) change, analysis of existing code would be required.

**Comment by rkitover** [comment]
Let me give you a real world example of why this can be extremely annoying.

I had this code in the profile for my guide:

```powershell
if (test-path $env:VCPKG_ROOT) {
    $global:vcpkg_toolchain = $env:VCPKG_ROOT + '/scripts/buildsystems/vcpkg.cmake'

    if ($iswindows) {

        $env:LIB     = $env:LIB     + ';' + $env:VCPKG_ROOT + '/installed/' + $env:VCPKG_DEFAULT_TRIPLET + '/lib'
        $env:INCLUDE = $env:INCLUDE + ';' + $env:VCPKG_ROOT + '/installed/' + $env:VCPKG_DEFAULT_TRIPLET + '/include'
    }
}
```
, and this was broken for months for anyone who didn't use vcpkg, because unlike scripts in general without `$erroractionpreference = 'stop'`, profiles will abort on error.

In a normal script, this will cause an ugly error in the output but the logic will still work.

I found it when I did yet another Windows reinstall on a laptop.

**Comment by mklement0** [comment]
I do empathize in general - though I observe no difference in error handling between a profile and a regular script.
As noted, I suspect this proposal won't go anywhere unless some analysis of existing code (e.g. by examining PowerShell code across all repos on GitHub) is undertaken that indicates that existing code predominantly doesn't rely on the current behavior.

In the meantime, the most concise workaround is `Test-Path $env:VCPKG_ROOT 2>$null`

**Comment by jborean93** [comment]
You can also do

```powershell
if ($env:VCPKG_ROOT -and (Test-Path -LiteralPath $env:VCPKG_ROOT)) {
    ...
}
```

**Comment by mklement0** [comment]
Or, more concisely, using `??`, the [null-coalescing operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Operators#null-coalescing-operator-): `Test-Path ($env:VCPK_ROOT ?? '')` (use `-LiteralPath` if needed).

**Comment by rkitover** [comment]
I like the `2>$null` solution, I forgot about this for some reason.

I also very often use `-ea ignore` for these purposes.

I did what @jborean93 suggested in this case when I fixed it, but any of these methods would be fine.

I was thinking, you probably have literally hundreds of issues like this holding up the evolution of the language.

What if you could make an AI system that checks the "code space" for simple constructs or whatever is needed. These things can "read" code to some degree. Would require some manual handling and verification of corse, and would not be 100% accurate, but probably good enough for these purposes.

**Comment by kilasuit** [comment]
FYI this was the committee's response to the PR #8080 that would have implemented `$false` to be output for this and requested the current behaviour instead.

https://github.com/PowerShell/PowerShell/pull/8080#issuecomment-432849050

**Comment by rkitover** [comment]
If this has already been decided then I will close this. Please consider my idea about using AI for issues such as this however. Thank you for your response.

**Comment by mklement0** [comment]
@rkitover 

> I also very often use -ea ignore for these purposes.

Good point; unlike `2>$null` - which is the equivalent of `-ErrorAction SilentlyContinue` - it has the advantage of not recording the error in `$Error`.

An AI-assisted solution for evaluating potential bucket-3 changes sounds promising.

@kilasuit, thanks for linking to the previous issue.

FWIW, I think the linked committee decision is unfortunate, and that someone willing to do the analysis that was suggested, in the case at hand, could still present a bucket-3 case, depending on the outcome of that analysis.
