### ISSUE TITLE
ANSI escape codes for colored text output support.

### ISSUE THREAD

**Issue by Anyspeed** [PowerShell/PowerShell#24477]
### Summary of the new feature / enhancement

I would like to suggest enhancing the support for ANSI escape codes in PowerShell, particularly for color output. Currently, while some terminals handle ANSI codes well, PowerShell does not consistently interpret them, leading to raw escape codes being displayed instead of colored text.

**Background**:
Many users are integrating PowerShell with other tools and scripts that utilize ANSI escape codes for color formatting. Increasing compatibility would improve the user experience significantly, especially for those transitioning from other terminal environments where ANSI codes are fully supported.

**Proposed Solution**:
- Enhance the existing handling of ANSI escape codes in PowerShell to ensure they are interpreted correctly across all supported terminal environments.
- Consider adding configuration options to enable or disable ANSI support, allowing users to customize their experience based on their needs.

**Benefits**:
- Improved aesthetics and readability for command-line output.
- Greater compatibility with scripts and tools that rely on ANSI codes for color output.

Thank you for considering this enhancement!

**Comment by 237dmitry** [comment]
> I would like to suggest enhancing the support for ANSI escape codes in PowerShell, particularly for color output.

PowerShell works with color esc-codes, for example:

```powershell
"`e[1;33mBright Yellow`e[0m"                  # 16 palette
"`e[38;5;220mBright Yellow`e[0m"              # 256 palette
"`e[38;2;255;200;100mBright Yellow`e[0m"      # rgb
```

**Comment by rhubarb-geek-nz** [comment]
> * Enhance the existing handling of ANSI escape codes in PowerShell to ensure they are interpreted correctly across all supported terminal environments.

The only thing a POSIX app has is environment variable TERM and termcaps/terminfo. Windows does not traditionally respect the TERM environment variable and assumes a fixed set. It is extremely challenging when SSHing from one machine to another or a remote session being shown in an X session it knows nothing about. It is also challenging on a mac where the terminal changes it's colours based on the time of day.

It is very hard to treat ANSI escape sequences in the middle of a pipeline, for example a string containing just an ANSI escape sequence is also holding a completely valid UNIX filename. Practically you can only manage colour at the end of a pipeline at the presentation stage.

> * Consider adding configuration options to enable or disable ANSI support, allowing users to customize their experience based on their needs.

That is what NO_COLOR is for. see also https://github.com/PowerShell/PowerShell/issues/21198 and https://github.com/PowerShell/PowerShell/issues/21168

**Comment by mklement0** [comment]
@Anyspeed:

>  leading to raw escape codes being displayed instead of colored text.
> PowerShell does not consistently interpret them

There are several open bugs that I know of:
 

* #20898



* #19961
* #20170
* #20171 
* #21168

Are you aware of additional problems _not_ covered by the above issues?

**Comment by SeeminglyScience** [comment]
@Anyspeed The terminal application (Windows Terminal, conhost, xterm, etc) handles rendering of VT sequences. PowerShell only passes them through as is. If you can find an instance where PowerShell specifically mangles a VT sequence before it gets to the terminal, please open another issue with repro steps.
