### ISSUE TITLE
Can't update to 7.4.6 using winget

### ISSUE THREAD

**Issue by archraziel** [PowerShell/PowerShell#24485]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am not able to update from  7.4.5 to 7.46 using winget
![image](https://github.com/user-attachments/assets/b97a0460-f155-4a1e-be0b-4a8dfd0228f7)

### Expected behavior

```console
It should update to the newversion and show the new version in winget
```

### Actual behavior

```console
It is still showing the 7.4.5 version
```

### Error details

```console
None
```

### Environment data

```powershell
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kilasuit** [comment]
This is a reoccuring issue due to the releases to winget having a delay. It should be resolved in the next few days & I will check this daily and update this issue when it is available

**Comment by kkamegawa** [comment]
It appears that the yaml registered in the winget manifest repository does not include the Arm64 on Windows version. Could you please add this as well?

```
- Architecture: arm64
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.4.6/PowerShell-7.4.6-arm-arm64.msi
```
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/PowerShell/7.4.6.0/Microsoft.PowerShell.installer.yaml

**Comment by mklement0** [comment]
Good point, @kkamegawa, but note that the URL should be:
`https://github.com/PowerShell/PowerShell/releases/download/v7.4.6/PowerShell-7.4.6-win-arm64.msi`

It looks like anyone can submit a PR; would you mind doing it?

**Comment by mklement0** [comment]
@kkamegawa: Just found this: https://github.com/microsoft/winget-pkgs/issues/164830#issuecomment-2257244469

>  It seems the PowerShell team won't be adding msi arm installers to winget until 7.5 becomes stable (sometime in Q4, usually November)

> For now PowerShell 7.5 preview's winget includes the .msi for arm.

**Comment by kilasuit** [comment]
7.4.6 is available, just not if you are looking for an arm64 installer

As mentioned above this is by current team plans & as such I am marking this as Resolution-Answered

**Comment by kkamegawa** [comment]
7.4.6 for Arm64 is merged
https://github.com/microsoft/winget-pkgs/pull/186064
