### ISSUE TITLE
Could not load type 'System.Runtime.InteropServices.IDispatchImplAttribute' from assembly mscorlib with pwsh 7.4.X

### ISSUE THREAD

**Issue by dearjimmyball** [PowerShell/PowerShell#24497]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The code below works without error on Powershell 7.3.12 and lower.   However, with Powershell 7.4.X, it throws an error on the Read call to a .NET component from WebSuperGoo named abcpdf, regardless of their version.   WebsuperGoo reports no issue with their component.

**Error**
OperationStopped: C:\temp\go.ps1:3
Line |
   3 |  $doc.Read("c:\temp\test.pdf")
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Runtime.InteropServices.IDispatchImplAttribute' from assembly 'mscorlib,
     | Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Code to Reproduce**
Add-Type -Path "c:\utils\abcpdf13\abcpdf.dll"
$doc = New-Object Websupergoo.Abcpdf13.doc
$doc.Read("c:\temp\test.pdf")
$doc.PageCount

### Expected behavior

```console
c:\temp> pwsh go.ps1
70
```

### Actual behavior

```console
pwsh go.ps1
OperationStopped: C:\temp\go.ps1:4
Line |
   4 |  $doc.Read("c:\temp\test.pdf")
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Runtime.InteropServices.IDispatchImplAttribute' from assembly'mscorlib,
     | Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
0
```

### Error details

```console
OperationStopped: C:\temp\go.ps1:4
Line |
   4 |  $doc.Read("c:\temp\test.pdf")
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Runtime.InteropServices.IDispatchImplAttribute' from assembly 'mscorlib,
     | Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
0
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jborean93** [comment]
I believe this is the underlying cause, .NET 8 removed this attribute and PowerShell 7.4 uses .NET 8 https://learn.microsoft.com/en-us/dotnet/core/compatibility/interop/8.0/idispatchimplattribute-removed. Unfortunately I don't know if you can do anything here except hope the module authors of `ABCpdf` stop using a deprecated and now removed .NET type in their code.
