### ISSUE TITLE
`Write-Host` renders an `[xml]` or `[XmlElement]` instance as an empty line.

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#24508]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```powershell
Write-Host ([xml] '<OhElement>Where art thou?</OhElement>').DocumentElement
```

Note: The problem _may_ come down to the base class, `System.Xml.XmlNode`, implementing `IEnumerable`, and `Write-Host` not only enumerating the given instance itself, but doing so recursively, down to the leaf elements that by definition have nothing to enumerate. As argued below, no enumeration should take place at all.

### Expected behavior

```console
OhElement
```

i.e., the name of the element, as if you had applied `.ToString()` to the instance.

Note that even though such instances technically implement `IEnumerable`, for consistency with pipeline enumeration behavior I expect them _not_ to be enumerated.

I suspect that the bug is related to the fact that they _are_ enumerated.

### Actual behavior

```console
(An empty line prints.)
```

### Environment data

```powershell
PowerShell 7.5.0-preview.5 (problem dates back to Windows PowerShell)
```

**Comment by SteveL-MSFT** [comment]
```powershell
([xml] '<OhElement>Where art thou?</OhElement>').DocumentElement | write-host
```

does the right thing, so it's definitely an issue during enumeration

**Comment by daxian-dbw** [comment]
When piping to `Write-Host`, the `XmlElement` object is wrapped into a `PSObject`, and falls to the `PSObject.ToString`.

**Comment by daxian-dbw** [comment]
`Write-Host` renders `IDictionary` inconsistently depending on how the value is passed in. This is tracked by #24671.
