### ISSUE TITLE
Cannot run PS 7.4.6 or 7.5.0P5 if the network has failed

### ISSUE THREAD

**Issue by RG255** [PowerShell/PowerShell#24526]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am not sure if I can reproduce the exact network failure, but I can say I started both version of PS several times with the same result 

### Expected behavior

```console
I should be able to run PS when my network fails
```

### Actual behavior

```console
Both versions of PS when a terminal session was started opened the window and then failed as per the errors below. PS 5.1 does NOT display the same behaviour it runs as expected.
```

### Error details

```console
No errors for here as the window closes see attached text files
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-preview.5
PSEdition                      Core
GitCommitId                    7.5.0-preview.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

[PS750P5Failure.txt](https://github.com/user-attachments/files/17590347/PS750P5Failure.txt)
[PS746Failure.txt](https://github.com/user-attachments/files/17590348/PS746Failure.txt)

**Comment by SeeminglyScience** [comment]
That error is caused by the `Microsoft.WinGet.CommandNotFound` module (https://github.com/microsoft/winget-command-not-found/issues/12). A fix was released, you'll need to update the module to receive it.
