### ISSUE TITLE
`pwsh` gets in a weird state when doing `Import-Module -UseWindowsPowerShell Appx` from a working directory with `[`/`]`

### ISSUE THREAD

**Issue by philcerf** [PowerShell/PowerShell#24538]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Hey.

![1](https://github.com/user-attachments/assets/b0ecd002-4ce5-4688-927b-b2a623bb2b1c)

In the above transcript, you see where I try several things in `pwsh` that was started from `cmd` in a working directory that contains the characters `[` and `]` (not sure whether both of them are needed or which is the offender).

In the first two tries, I merely `cd ..` and then `cd` back to the “special” directory - with and without `$ErrorActionPreference = 'Stop'` which does seem to work properly.

I then repeat that with calling `Import-Module -UseWindowsPowerShell Appx` in between.

When doing that **without** `$ErrorActionPreference = 'Stop'` it again works flawlessly (or at least there's no visible error), but when doing it with, I get an error like this:
```
Set-Location: Cannot find path 'C:\tmp\foo [bar]' because it does not exist.
```
Now one could argue that something of `Import-Module -UseWindowsPowerShell Appx` simply doesn’t work with “special” characters in the current working directory (though I wonder why `Import-Module` needs the CWD at all), but as you can see, the whole system is in weird state afterwards:<br>
If I `cd ..` and `cd` back to the “special” directory it gives the same error again, despite the prompt being changed to it, and a `dir` showing the file `baz` which actually is in `C:\tmp\foo [bar]`.

It does work in the example below, where there’s no `[`/`]` in the directory name:
![2](https://github.com/user-attachments/assets/8f631089-dc03-4bfe-91ba-6579e1908af1)

btw: I assume that `pwsh` **is** expected to work from working directories that use any names/characters that are valid in Windows (though I actually haven’t managed to find a list, which these are - I mean like in POSIX where it’s simply anything except `0x0`.), or are there any exceptions?

Thanks,
Philippe

### Expected behavior

```console
Well it should just work?!
```

### Actual behavior

```console
*Was there ever any bug report written actually any better by forcing people to enter text in some fields which may or may not at all make sense when describing an issue?*
```

### Environment data

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
I think the bug isn't related to `AppX`, specifically, but to the [Windows PowerShell Compatibility feature](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Windows_PowerShell_Compatibility) as a whole.

It seems that `Set-Location -LiteralPath` inexplicably breaks with directory paths containing `[` / `]` once the first time in a session a module is imported via said feature.

**Comment by philcerf** [comment]
Can that Compatibility feature be fixed?

**Comment by mklement0** [comment]
@philcerf: I've created a new bug report with a minimal repro in the following issue:

* #24541

If you agree that its general description also matches your specific scenario, I suggest closing your issue in favor of the latter.

**Comment by philcerf** [comment]
> If you agree that its general description also matches your specific scenario, I suggest closing your issue in favor of the latter.

Sure... btw: I haven’t checked whether it’s only `[` and/or `]`.

**Comment by mklement0** [comment]
Thanks, @philcerf.

Since we're by definition talking about Windows, it is just `[` and `]` that are the problem, because they are the only other wildcard metacharacters (in addition to `*` and `?`, which aren't legal in literal file names).

The problem comes down to mistakenly using `Set-Location -Path` (path is interpreted as a wildcard expression) behind the scenes rather than `Set-Location -LiteralPath`.

I've since found the exact location of the bug in the source code, and it turns out there's another bug lurking - see the updated linked post.

**Comment by philcerf** [comment]
Thanks :-) Hope a version with a fix gets released soon.
