### ISSUE TITLE
Start-Process doesn't put process in same job group on Windows

### ISSUE THREAD

**Issue by leidegre** [PowerShell/PowerShell#24558]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Maybe this isn't a bug but I cannot find any way to actually do this and it feels wrong.

```ps1
$job = Start-Job -ScriptBlock { start notepad.exe -Wait }
$job

Wait-Job $job -Timeout 10

Stop-Job $job
```

What I expect to happen here is that notepad will close when the job is stopped but this doesn't happen because somehow the Start-Process has been called in a way that makes it break away from the win32 process job group.

![image](https://github.com/user-attachments/assets/27d5557a-95ab-4428-9475-b05b90ec75d5)

Also, there's this little tidbit. Why does it default to shell execute, that could be the issue...

https://github.com/PowerShell/PowerShell/blob/31b70ecd9fa2a245768f267eae2fb96a0a5ab92d/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L1892-L1894

Futher down there's this

https://github.com/PowerShell/PowerShell/blob/31b70ecd9fa2a245768f267eae2fb96a0a5ab92d/src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs#L1949-L1952

But when I look at the processes in process explorer they haven't been created in the same job group which is what I think should happen unless create process is used with creation flags, like breakaway or new process group which I believe is not the case.

This is creating headaches for me because I need to cleanup the process tree when the job i stopped, the job is stopped because it's taking to long and this is creating more problems. I need the process tree to die when I stop jobs forcefully.

### Expected behavior

```console
I would have expected all processes to end up in the same Win32 job and that notepad was killed when I stopped the job.
```

### Actual behavior

```console
Notepad keeps running even after job is stopped.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
This works the same way as with cmd.exe - if we start Notepad.exe from cmd.exe and then stop the cmd.exe this will not stop the Notepad process.

**Comment by leidegre** [comment]
That is true but cmd.exe is not running inside a Job, if we use Process Explorer to investigate the job tab, we see no job is associated with cmd.exe but if you go back to my earlier screenshot from powershell, we can see that powershell is running in a job group and that it has a job group. Maybe this job group is created by Windows Terminal but I don't understand how it manages to break away from the job group. This is not the default behavior... but I cannot find the root cause of it.

![image](https://github.com/user-attachments/assets/867f7ce5-6989-46d7-9dd1-65f79e62c048)

**Comment by iSazonov** [comment]
pwsh works as cmd.exe - it never terminates GUI applications, only console applications.

**Comment by leidegre** [comment]
This is specifically about jobs, and how jobs should operate, they should not allow processes to escape job. The whole point of a job group is to keep the processes together. Otherwise you end up having to write a lot of cleanup code which isn't really helpful when you already have process jobs for this.

**Comment by rhubarb-geek-nz** [comment]
Lets look at what a [Console Process Grouip](https://learn.microsoft.com/en-us/windows/console/console-process-groups) is.

> The signal is only received by those processes in the group that are attached to the same console as the process that called GenerateConsoleCtrlEvent.

I suggest trying with a SUBSYSTEM=CONSOLE rather than SUBSYSTEM=WINDOWS program.

Windows programs don't inherit the parent's console and don't use console events to manage lifecycle. They use typically use GetMessage and WM_QUIT.

**Comment by mklement0** [comment]
With _GUI_-subsystem applications,  you're fundamentally out of luck, for the reasons explained in @rhubarb-geek-nz's comment.

With _console_-subsystem applications, be sure to invoke them _directly_ rather than via `Start-Process`, then you'll get the desired behavior.

**Comment by mklement0** [comment]
A background job in PowerShell is just a hidden PowerShell process and, like regular PowerShell sessions, does _not_  use [Windows Jobs](https://docs.microsoft.com/en-us/windows/win32/procthread/job-objects)  to keep track of processes it launches - however, a synchronously launched, still-running console application _is_ terminated if you use `Stop-Job` or `Remove-Job -Force` (but _not_ if you _kill_ the hidden process running the job).

However, in the context of _remoting_, Windows Jobs _are_ used, which means that even `Start-Process`-launched processes are terminated along with the remote session; see:
* #16001

**Comment by leidegre** [comment]
Okay, notepad was a bad choice. I think I can get this to work now. Thanks for clearing things up.
