### ISSUE TITLE
A way to see if two variables hold references to the same array

### ISSUE THREAD

**Issue by Hashbrown777** [PowerShell/PowerShell#24561]
### Summary of the new feature / enhancement

`-eq` has weird behaviour when either operand is a list, [working more as a filter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-5.1) and not returning a boolean. I'm not going to speak to that design choice..but now how do we achieve object equivalence for lists?

Other `Collection`s such as `Hashtable` are able to be checked à la `$bob = @{}; $steve = $bob; $steve -eq $bob` but nomatter what I try I'm unable to find such a thing for `$()`.
Even using `ArrayList` over a basic array the value was still successfully evaluated as a list to filter, but I did find luck in instead using the [`SyncRoot`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.arraylist.syncroot?view=net-8.0) thereof.
Id est `$bob = [System.Collections.ArrayList]::new(); $steve = $bob; $steve.SyncRoot -eq $bob.SyncRoot` did yield `$True` (and a fresh `[]::new()` for `$steve` made the expression return `$False`).

However, this was on v5... on PowerShell 7 this workaround doesn't function because for *public virtual **object** SyncRoot { get; }* it instead returns itself; ***ArrayList***
:( I'm at a loss what to try.

**Comment by mklement0** [comment]
Use [`System.Object.ReferenceEquals`](https://learn.microsoft.com/en-US/dotnet/api/System.Object.ReferenceEquals):

```powershell
$bob = [System.Collections.ArrayList]::new(); $steve = $bob
[object]::ReferenceEquals($steve, $bob) # -> $true
```

**Comment by Hashbrown777** [comment]
Thankyou!
I did so much googling and all the results were trying to help compare arrays by their values and suggesting `Compare-Object`
