### ISSUE TITLE
Convert-Path to to a standard registry path fail if a forward backslash is present

### ISSUE THREAD

**Issue by GaetanRabier** [PowerShell/PowerShell#24586]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Easily reproducible : 
Convert-Path -Path "HKLM:SYSTEM\CurrentControlSet\Control\Session Manager\I/O System"

### Expected behavior

```console
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\I/O System
```

### Actual behavior

```console
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\I\O System
```

### Error details

```console
The forward back slash at the end (between I and O) is converted to a regular backslash.
This is due to the call to MakePath that is converting all the slashs from the child path.

https://github.com/cobbr/InsecurePowerShell/blob/fed7a542da3346c0f686157990e0c8a954b108c8/src/System.Management.Automation/namespaces/NavigationProviderBase.cs#L386

We should instead divide the path into multiple variables and then reassemble them.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Good point; this was first reported 7 years ago, in:

* #5536

Despite it having been acknowledged as a bug, and a decision having been made to fix it, allowing a community PR by labeling it `Up-for-Grabs`, the bot auto-closed the issue due to lack of activity - which arguably should never happen for issues labeled this way.

**Comment by SteveL-MSFT** [comment]
I've reopened the original issue

**Comment by mklement0** [comment]
Thanks, @SteveL-MSFT.

However, as acknowledged in https://github.com/PowerShell/PowerShell/issues/20524#issuecomment-2501183069, adding the `Keep-Open` label doesn't in and of itself reopen already-closed issues; I hope this will be fixed automatically, retroactively.

**Comment by iSazonov** [comment]
I reopened that issue.
