### ISSUE TITLE
Remove -UseBasicParsing from web cmdlets

### ISSUE THREAD

**Issue by rmbolger** [PowerShell/PowerShell#24598]
### Summary of the new feature / enhancement

The `-UseBasicParsing` switch in `Invoke-WebRequest` and `Invoke-RestMethod` has been labeled as "deprecated" in the PowerShell documentation since the PowerShell 6.0 release in 2018. Using it has no effect and it was included only for backwards compatibility with PowerShell 5 so existing scripts wouldn't break between versions.

Historically, deprecated software features tend to get removed in the next major release of the software where breaking changes are expected. So I assumed the 7.0 release would have removed it, but that didn't happen. Are there any plans to remove it with an 8.x release? Or is it destined to remain deprecated until PowerShell 5 is no longer included/supported in current Windows OSes?

**Comment by MartinGC94** [comment]
Why should it be removed? It seems pretty nice that I can write a script that is compatible with both 5.1 and the newer versions without having to worry about the parameters.

**Comment by rmbolger** [comment]
Because it's legacy baggage that isn't needed. Additionally, the web cmdlets have already changed in many other breaking ways since PowerShell 5.1.

- They use different .NET HTTP clients under the hood leading to different Exception type handing for the same errors
- Accessing content bodies from an error response is different.
- They use different methods to deal with certificates and ignoring certificate validation
- They use different methods to deal with TLS versions
- Invoke-RestMethod parses JSON dates differently

I'm sure there are things I'm forgetting. Realistically if you're trying to write non-trivial code that works with both versions, you're already having to jump through hoops to make different calls for the different versions anyway.

**Comment by jborean93** [comment]
To me it’s more a question of what do we gain by removing it which to me is very little. If powershell 7 was in box to Windows leading to a solid way to actually stop working on 5.1 then maybe it’s worth the pain but I don’t think adding yet another breaking difference is going to worth the pain it introduces.

**Comment by rmbolger** [comment]
Less code to maintain and test in the PowerShell repo. Less documentation to maintain. Less confusion for new users. Fewer parameters to tab complete through. More reasons for users to drop 5.1 support willingly.

Even when 5.1 is long dead and buried, there will still be people who include it in their scripts such that removing it will cause pain. There's no avoiding it unless you literally leave it in forever. I say rip off the band-aid with the next major release and update the docs now to say it's going to happen so folks can plan for that eventuality.

The great thing about modern PowerShell is the relatively short support lifecycle and fast paced release schedule. We don't have to wait nearly as long as we used to in order to start relying on all the great new stuff. But that same mentality should apply to deprecated stuff. Let it go when it's no longer useful.

**Comment by 237dmitry** [comment]
I can't understand one thing, why Windows PowerShell has stopped developing. It would seem that PowerShell 7 has new capabilities, just go ahead and implement them. But no. When PowerShell appeared, it was a real revolution, with each release new capabilities appeared, I was waiting for these changes, and now the shell has become a burden, not only does it not develop, but it also hangs its baggage on PowerShell 7.

**Comment by rhubarb-geek-nz** [comment]
> I can't understand one thing, why Windows PowerShell has stopped developing.

I suggest this points to a more fundamental problem with PowerShell and the expectation that it can meaningfully be compared to POSIX shells such as bash, ksh, zsh etc.

There is not reason at all why any of the web cmdlets should have be tied to a version of PowerShell. When changes are made to curl, it has no involvement with bash or any of the POSIX shells. Curl is completely independent.

**Comment by MartinGC94** [comment]
It's not a fundamental problem. There have been talks about splitting modules out into different repositories: https://github.com/PowerShell/PowerShell/issues/9960 it's just a lot of work that hasn't been prioritized.

I don't know if there have been talks about splitting up the modules themselves but that could make it easier to slowly work towards that goal. For example a new module called `Microsoft.PowerShell.WebCommands` could be created and the web cmdlets could be moved there.

**Comment by rhubarb-geek-nz** [comment]
> There have been talks about splitting modules out into different repositories

That is good to hear!

**Comment by jhoneill** [comment]
I'm contracting somewhere that is very reluctant to put downloaded PowerShell on their servers, so I need to write code which works in 7.x  (so I can use 7 on my workstation and be prepared for when we DO run 7 on the servers, but they are still writing stuff in VB script so not expecting that any time soon) AND works in 5.x.   This switch is needed in  5.x scripts we use (not hundreds, but perhaps 60-80 scripts.)  

There is already a solution to this which is to have a `DontShow` attribute on the parameter which is done (IIRC) for the `NoTypeInformation` switch in `Export-Csv`  this gives a does-nothing, never suggested switch to prevent legacy code breaking.  You can even display a warning that the switch is ignored if you want.  

But every time someone says "Lets put something something in v-next which means some scripts from v-old do not run anymore" customers say "You can't install new version because they break everything".  But as a matter of principle, Version n _should_ run all scripts that worked on a version < n , and with exceptions only where the benefit is unarguably great, and recognising that those exceptions will mean that some users stop upgrading.

**Comment by iSazonov** [comment]
UseBasicParsing is already documented as `deprecated` and is already hided by `DontShow` attribute.

**Comment by mklement0** [comment]
True, @iSazonov, but note that it still shows up in the _syntax diagrams_, which has - surprisingly - been considered to be by design:

* #18503

**Comment by iSazonov** [comment]
@mklement0 I think we would lost/break nothing if we removed such `DontShow`-ed parameters from syntax diagram.

**Comment by rmbolger** [comment]
> UseBasicParsing is already documented as deprecated and is already hided by DontShow attribute.

Respectfully, I wasn't asking for it to be deprecated. I was asking when it would actually get removed (if ever).

**Comment by iSazonov** [comment]
As noted, there is no intention to force the removal of this parameter.
