### ISSUE TITLE
X509Certificate2 DNSNameList is not language independent, don't work on non-english clients

### ISSUE THREAD

**Issue by MaurizioFocareta** [PowerShell/PowerShell#24594]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In any version of powershell create a X509Certificate2 object by using:

`$certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($path, $pwd)`

Then query for the $certificate.DNSNameList property. 

If you do the action on an english client you obtain the list of the SubjectAlternativeNames, if you do from another language (in my case, Italian client) the property is empty.

If you look at source file:

> src/Microsoft.PowerShell.Security/security/CertificateProvider.cs

You can see that the property has a FIXED dns name prefix in english language

```
    public sealed class DnsNameProperty
    {
        private readonly List<DnsNameRepresentation> _dnsList = new();
        private readonly System.Globalization.IdnMapping idnMapping = new();

        private const string dnsNamePrefix = "DNS Name=";
```

and this prefix is used in the DNSNameList property to discard all that is not a DNS name

```
            foreach (X509Extension extension in cert.Extensions)
            {
                // Filter to the OID for Subject Alternative Name
                if (extension.Oid.Value == "2.5.29.17")
                {
                    string[] names = extension.Format(true).Split(Environment.NewLine);
                    foreach (string nameLine in names)
                    {
                        // Get the part after 'DNS Name='
                        if (nameLine.StartsWith(dnsNamePrefix, System.StringComparison.InvariantCultureIgnoreCase))
                        {
```

But in Italian language the prefix code you obtais is not 'DNS Name=" but "Nome DNS=" and so they are all discarded, resulting in an empty DNSNameList property.

### Expected behavior

```console
The expected behaviour is that the DNSNameList is populated the same way if the client is english or not english language.
```

### Actual behavior

```console
The actual behaviour is that the DNSNameList property is empty on non-english clients (for example, Italian client)
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ericlaw1979** [comment]
Using `EnumerateDnsNames` does sound like the right fix.

Today, PowerShell is relying on parsing the extension as a string. On Windows by default, that string comes from the CngAsnFormatter, which itself the text from Windows' Crypt32 format function, and in Windows, IDS_DNS_NAME is a localized string which has a different value on a non-English system. And it's hypothesized above that this might even fail on an English system if OpenSslAsnFormatter.cs does not format the text in the same way as Crypt32 does.

**Comment by vcsjones** [comment]
Right. Parsing the output of the extension as a string is prone to failure. It depends on the OS locale, and other operating systems (Linux / OpenSSL, macOS) are going to output different things.

The `EnumerateDnsNames` was added exactly so that folks would not try to parse the output from stringifying the extension since it is brittle.

https://github.com/dotnet/runtime/issues/22699

> Currently applications make programmatic decisions for it via ToString() which has a couple of problems:

> It's localized on Windows
> It's not the same on Windows and !Windows.

**Comment by ArmaanMcleod** [comment]
I guess usage would simply turn into:

```csharp
var subjectAlternativeNameExtension = new X509SubjectAlternativeNameExtension(cert.RawData);

foreach (string dnsNameEntry in subjectAlternativeNameExtension.EnumerateDnsNames())
{
    // Add entries to DnsNameList property
}
```

Which looks pretty simple instead of going through all the extensions and doing DNS name prefix + OID SAN checking.

**Comment by iSazonov** [comment]
@ArmaanMcleod Yes, it is right way.

**Comment by ArmaanMcleod** [comment]
I guess workaround for now could be to just do:

```pwsh
($cert.Extensions | Where-Object { 
    $_ -is [System.Security.Cryptography.X509Certificates.X509SubjectAlternativeNameExtension] 
}).EnumerateDnsNames()
```

I'll see if I can create a PR soon to get the `DnsNameList` property populated.
