### ISSUE TITLE
Microsoft.PowerShell.Commands.Utility v7.4.6 accidently depends on dotnet v9 preview packages?

### ISSUE THREAD

**Issue by jeroenjanssen-cpp** [PowerShell/PowerShell#24602]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

The dependencies for 7.4.6 depends on v9 preview packages (7.4.5 depends on the official v8 ones)
https://www.nuget.org/packages/Microsoft.PowerShell.Commands.Utility/7.4.6#dependencies-body-tab

![image](https://github.com/user-attachments/assets/56d5d713-675b-4a93-a503-538868b21baa)

From https://github.com/PowerShell/PowerShell/pull/24429/files, it seems the package versions accidently got bumped  for the Microsoft.PowerShell.Commands.Utility.csproj

### Expected behavior

```console
official 7.4.6 to not depend on v9 preview packages
```

### Actual behavior

```console
official 7.4.6 depends on v9 preview packages
```

### Error details

```console
n/a
```

### Environment data

```powershell
n/a
```

**Comment by fMichaleczek** [comment]
Also a question in discussions
https://github.com/PowerShell/PowerShell/discussions/24562

**Comment by SydneyhSmith** [comment]
This is a known issue and will be fixed -- thanks
