### ISSUE TITLE
Inconsistent Display Behavior/Blank Items When Using Invoke-Command with Get-Childitem

### ISSUE THREAD

**Issue by Starfaesh** [PowerShell/PowerShell#24606]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Using Invoke-Command with Get-ChildItem results in some properties not displaying, depending on which formatting options are used. I tested several combinations; no combinations that I tried resulted in all selected properties being displayed in the console/terminal.

When investigating, I found this issue was previously noted in [](url)https://github.com/PowerShell/PowerShell/issues/10759 & [](url)https://github.com/PowerShell/PowerShell/issues/11400 .

Also Tested on:
PSVersion                      7.5.0-rc.1
PSEdition                      Core

### Expected behavior

```console
All selected properties (explicit or implicit) are displayed in console/terminal window.
```

### Actual behavior

```console
Only some properties are displayed in console/terminal window, varying based on formatting (ex: Format-Table, Format-List) or Select-Object properties.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

` invoke-command -computer $Name -scriptblock{get-childitem -path $Path}`
**Result: Of the selected items, only PSComputerName is returned.**
![PS7_01](https://github.com/user-attachments/assets/ef60bd91-64a8-40ee-8ae0-fad4989d4f81)

`invoke-command -computer $Name -scriptblock{get-childitem -path $Path | select Name,PSComputerName,LastWriteTime}`
**Result: Of the selected items, all properties are returned.**
![PS7_02](https://github.com/user-attachments/assets/c0e4730b-6ec1-4e06-8719-b337de81901b)

`invoke-command -computer $Name -scriptblock{get-childitem -path $Path | select Name,PSComputerName,LastWriteTime | format-table}`
**Result: Of the selected items, all properties are returned EXCEPT PSComputerName.**
![PS7_03](https://github.com/user-attachments/assets/c5240daf-2f5a-4a82-a45a-0d6498e44391)

`invoke-command -computer $Name -scriptblock{get-childitem -path $Path | select Name,PSComputerName,LastWriteTime | format-List}`
**Result: Of the selected items, all properties are returned EXCEPT PSComputerName.**
![PS7_04](https://github.com/user-attachments/assets/00a67aff-9f5b-4cd2-afbb-32bca8f1ca46)

**Comment by mklement0** [comment]
Hard to believe, but this bug was first reported almost 5 years ago:

* #11400

It affects remoting from PowerShell Core to _Windows PowerShell_ (which is still targeted by default, unless specified otherwise via `-ConfigurationName`.

Note that your `PSComputerName`-related examples work as expected, however: `PSComputerName` is added as an ETS property on the _client_ side, so it's there inside the remote session.

**Comment by Starfaesh** [comment]
> Note that your PSComputerName-related examples work as expected, however: PSComputerName is added as an ETS property on the client side, so it's there inside the remote session.

My mistake on that aspect- I didn't realize that was intended behavior. My original script didn't use that field but when I started testing I chose a selection of properties I felt I'd be likely to use and noticed that it was coming up blank.

**Comment by kasini3000** [comment]
ps v5 ---> winrm ---> psv5 use:
New-PSSession  -ConfigurationName 'microsoft.powershell'

install and set psv7 it  default remote shell
ps v7.x ---> winrm ---> ps v7.x use:
New-PSSession  -ConfigurationName 'powershell.7'

**Comment by SteveL-MSFT** [comment]
I've reopened the original issue as it has the investigation details.
