### ISSUE TITLE
Is version 7.4.6 a bad release?

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [PowerShell/PowerShell#24613]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have seen a number of problems with 7.4.6, is it just a bad release and should be avoided? I expanded the [PowerShell-7.4.6-win-x64.zip](https://github.com/PowerShell/PowerShell/releases/download/v7.4.6/PowerShell-7.4.6-win-x64.zip)

7.4.6 should still be using dotnet 8 sdk

https://github.com/PowerShell/PowerShell/issues/24602
https://github.com/PowerShell/PowerShell/issues/24548

### Expected behavior

```console
PS>(get-item System.Drawing.Common.dll).VersionInfo

8.0.10+81cabf28… 8.0.1024.46610   PowerShell-7.4.6-win-x64\System.Xml.dll
```

### Actual behavior

```console
PS> (get-item System.Drawing.Common.dll).VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
9.0.0-preview.6… 9.0.24.32706     PowerShell-7.4.6-win-x64\System.Drawing.Common.dll

PS> (get-item System.Xml.dll).VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
8.0.10+81cabf28… 8.0.1024.46610   PowerShell-7.4.6-win-x64\System.Xml.dll
```

### Error details

```console
none
```

### Environment data

```powershell
Not important, I am not running that version
```

**Comment by SteveL-MSFT** [comment]
This is a known issue and will be addressed with next 7.4 release
