### ISSUE TITLE
Cannot install PS module from .net application using Microsoft.PowerShell.SDK

### ISSUE THREAD

**Issue by begemott** [PowerShell/PowerShell#24618]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I need to install a PowerShell module from my .NET application. I have added Microsoft.PowerShell.SDK nuget package to the project and use PowerShell class to execute Install-Module cmdlet but it fails because of CommandNotFoundException.

Code:
  ```
 PowerShell ps = PowerShell.Create();
 ps.AddCommand("Install-Module").AddParameter("Name", "ExchangeOnlineManagement").AddParameter("Force");
 ps.Invoke();
```

### Expected behavior

```console
The PS module should be installed.
```

### Actual behavior

```console
CommandNotFoundException is thrown.
```

### Environment data

```powershell
.NET version: 8.0
Microsoft.PowerShell.SDK version: 7.4.5
OS: Windows 10
```

**Comment by rhubarb-geek-nz** [comment]
[Install-Module](https://learn.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershellget-3.x) is not part of the SDK, it is installed as part of the PowerShell application.

It is installed as a [module](https://www.powershellgallery.com/packages/PowerShellGet/2.2.5)

```
PS> (get-command Install-Module)

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     2.2.5      PowerShellGet

PS> (Get-Command Install-Module).Module.ModuleBase
C:\program files\powershell\7\Modules\PowerShellGet
```

But [Import-Module](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.4) is part of Microsoft.PowerShell.Core

```
PS> (Get-Command Import-Module)

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Import-Module                                      7.2.23.500 Microsoft.PowerShell.Core
```

**Comment by begemott** [comment]
> [Install-Module](https://learn.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershellget-3.x) is not part of the SDK, it is installed as part of the PowerShell application.
> 
> It is installed as a [module](https://www.powershellgallery.com/packages/PowerShellGet/2.2.5)
> 
> ```
> PS> (get-command Install-Module)
> 
> CommandType     Name                                               Version    Source
> -----------     ----                                               -------    ------
> Function        Install-Module                                     2.2.5      PowerShellGet
> 
> PS> (Get-Command Install-Module).Module.ModuleBase
> C:\program files\powershell\7\Modules\PowerShellGet
> ```
> 
> But [Import-Module](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7.4) is part of Microsoft.PowerShell.Core
> 
> ```
> PS> (Get-Command Import-Module)
> 
> CommandType     Name                                               Version    Source
> -----------     ----                                               -------    ------
> Cmdlet          Import-Module                                      7.2.23.500 Microsoft.PowerShell.Core
> ```

Does it mean that there is no way to install a PowerShell module from a .NET application without installing the PowerShell application?

**Comment by begemott** [comment]
> Should your application be updating or affecting the machine's normal PowerShell installation?
No, my application should work without PowerShell being installed. I need to install only ExchangeOnlineManagement module and then use cmdlets from it.

> You could have a modules directory tree within your application package that contains all the modules you need that are not part of the SDK.

Thanks

**Comment by mklement0** [comment]
[This StackOverflow answer](https://stackoverflow.com/a/78788436/45375) is a summary of the problem, with links to other answers with concrete solution. 
Notably, [here](https://stackoverflow.com/a/77829044/45375) is a solution that uses build tooling to bundle a given module with your project.

**Comment by begemott** [comment]
Thanks
