### ISSUE TITLE
Passing `$null` to `[Environment]::SetEnvironmentVariable` sets environment variable to empty string `''` (7.5 RC1)

### ISSUE THREAD

**Issue by pjking07** [PowerShell/PowerShell#24637]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

In .NET 9, a [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/empty-env-variable) introduced empty string support to environment variables. As of that change, the only way to remove an environment variable is to set it to `null` via `Environment.SetEnvironmentVariable()`. I've confirmed this behavior in .NET 9 with C#.

PR #24133 introduced .NET 9, and the above breaking change, into PowerShell v7.5.0-preview.4.

However, setting an environment variable to `$null` in `[Environment]::SetEnvironmentVariable()` now sets the environment variable to an empty string, instead of the expected behavior of unsetting the environment variable. Notably, setting the variable to null via the ENV provider works as expected.

The below tests explain the expected behavior, but `Environment Variable.System.Environment.Should unset environment variables with null` fails because `[Environment]::GetEnvironmentVariable()` yields an empty string `''` instead of `$null`.

```pwsh
Describe 'Environment Variable' {

    Context 'System.Environment' {
        It 'Should unset environment variables with null' {
            [System.Environment]::SetEnvironmentVariable('TEST_DOTNETAPI_NULL', $null)
            [System.Environment]::GetEnvironmentVariable('TEST_DOTNETAPI_NULL') | Should -Be $null
        }

        # See breaking change in .NET 9:
        # https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/empty-env-variable
        It 'Should set environment variables with empty string' -Skip:([Environment]::Version.Major -lt 9) {
            [System.Environment]::SetEnvironmentVariable('TEST_DOTNETAPI_EMPTY', '')
            [System.Environment]::GetEnvironmentVariable('TEST_DOTNETAPI_EMPTY') | Should -Be ''
        }
    }

    Context 'ENV Drive' {
        It 'Should unset environment variables with null' {
            $ENV:TEST_ENV_NULL = $null
            $ENV:TEST_ENV_NULL | Should -Be $null
        }

        # See breaking change in .NET 9:
        # https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/empty-env-variable
        It 'Should set environment variables with empty string' -Skip:([Environment]::Version.Major -lt 9) {
            $ENV:TEST_ENV_EMPTY = ''
            $ENV:TEST_ENV_EMPTY | Should -Be ''
        }
    }
}
```

### Expected behavior

```console
All four tests pass
```

### Actual behavior

```console
> Invoke-Pester .\EnvironmentVariable.Tests.ps1

Starting discovery in 1 files.
Discovery found 4 tests in 7ms.
Running tests.
[-] Environment Variable.System.Environment.Should unset environment variables with null 4ms (3ms|0ms)
 Expected $null, but got <empty>.
 at [System.Environment]::GetEnvironmentVariable('TEST_DOTNETAPI_NULL') | Should -Be $null, C:\EnvironmentVariableTest\EnvironmentVariable.Tests.ps1:6
 at <ScriptBlock>, C:\EnvironmentVariableTest\EnvironmentVariable.Tests.ps1:6
Tests completed in 60ms
Tests Passed: 3, Failed: 1, Skipped: 0, Inconclusive: 0, NotRun: 0
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-rc.1
PSEdition                      Core
GitCommitId                    7.5.0-rc.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by pjking07** [comment]
I believe this is related to parameter parsing for dotnet methods, in which `null` string values seem to coalesce to an empty string `""`.

As an example, let's use .NET string compare between null and an empty string in both PowerShell and C#. We'll find that PowerShell finds them equal while C# finds them different.

```pwsh
[string]::Compare($null, '') # 0
```

```cs
string.Compare(null, "") // -1
```

**Comment by rhubarb-geek-nz** [comment]
See https://github.com/PowerShell/PowerShell/discussions/24605

**Comment by kilasuit** [comment]
I think that this is similar to the discussion that was had in [Issue 21186](https://github.com/PowerShell/PowerShell/issues/21186) & the output from the Working Group [in this comment](https://github.com/PowerShell/PowerShell/issues/21186#issuecomment-2270067750)

**Comment by mklement0** [comment]
Thanks, @kilasuit.

Indeed, this was an intentional breaking change in .NET 9, which the working group in effect decided to surface in PowerShell too:

To recap, based on https://github.com/PowerShell/PowerShell/issues/21186#issuecomment-2187252118:

 * [As before] `$env:FOO = $null` will _remove_ the variable.

* [Breaking change] `$env:FOO = ''` will now create it as / set it to _the empty string_.

* [Newly introduced bug]  `Set-Content Env:FOO -Value $null` converts `$null` to the empty string (due the parameter binding turning the `$null` into an empty array, which is then stringified to the empty string), so it _will no longer remove the variable_.

  * By contrast, `Set-Item Env:FOO ...` behaves the same as namespace variable notation (`$env:FOO = ...`)
