### ISSUE TITLE
start-job doesn't recognize the $variable 

### ISSUE THREAD

**Issue by CN-CODEGOD** [PowerShell/PowerShell#24636]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When i try to use start-job to download with aria2, i pass a variable to the powershell
but When i receive-Job the variable doesn't pass in the job causing path error 

```
PS F:\> $path='g:\'
PS F:\> start-job {aria2c.exe "https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe"  -d "$path\program Files\"} -name "lghub"|Out-Null
receive-Job -id 73
[#2b62dc 38MiB/55MiB(69%) CN:1 DL:6.1MiB ETA:2s]

[#2b62dc 43MiB/55MiB(78%) CN:1 DL:5.9MiB ETA:2s]

[#2b62dc 48MiB/55MiB(87%) CN:1 DL:5.8MiB ETA:1s]

[#2b62dc 53MiB/55MiB(97%) CN:1 DL:5.8MiB]
12/04 00:17:42 [NOTICE] Download complete: /program Files//lghub_installer.exe
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
2b62dc|OK  |   5.7MiB/s|/program Files//lghub_installer.exe

Status Legend:
(OK):download completed.
```

### Expected behavior

```console
The output path should be g:\program Files
```

### Actual behavior

```console
The output path was :\program Files



```
```


### Error details

```console
none
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-rc.1
PSEdition                      Core
GitCommitId                    7.5.0-rc.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0鈥
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 237dmitry** [comment]
Try `$using:path` in Start-Job's script-block

**Comment by kilasuit** [comment]
As seen by this sample you can pass it using either the ArguementList or directly using the $using:path method
```powershell
$path = 'C:\tmp'
Start-Job -ScriptBlock { "Path = $path"}
Start-Job -ScriptBlock { "Path = $($args[0])"} -ArgumentList $path
Start-Job -ScriptBlock {"Path =  $using:path"}
Get-Job | Wait-Job | Receive-Job
```

**Comment by CN-CODEGOD** [comment]
yes i have try $using:path,and work well thanks

> As seen by this sample you can pass it using either the ArguementList or directly using the $using:path method
> 
> ```powershell
> $path = 'C:\tmp'
> Start-Job -ScriptBlock { "Path = $path"}
> Start-Job -ScriptBlock { "Path = $($args[0])"} -ArgumentList $path
> Start-Job -ScriptBlock {"Path =  $using:path"}
> Get-Job | Wait-Job | Receive-Job
> ```
