### ISSUE TITLE
Time check against known NTP Time server

### ISSUE THREAD

**Issue by EndyCZ** [PowerShell/PowerShell#24633]
### Summary of the new feature / enhancement

As an support engineer I would like to provide a cross platform PowerShell diagnostics script to my customers that can verify that the time on the system is correct so that my customers can easily find out what is the root cause that their system cannot connect to a secure HTTP server (reason is time is not correct which leads to certificate not being valid). This leads to a lot of time saving on both customer and support engineer time.

### Proposed technical implementation details (optional)

Add a command `Test-Time` to reference commands similar like `Test-Connection` [Docs](https://learn.microsoft.com/es-es/powershell/module/microsoft.powershell.management/test-connection?view=powershell-7.4) where you provide as input NTP servers like [pool.ntp.org](https://www.ntppool.org/en/use.html).

The command output is similar to w32tm

```
w32tm /stripchart /computer:$ntp_destination /dataonly /samples:2
```

And the output is similar to

```powershell
Tracking pool.ntp.org [85.214.133.14:123].
Collecting 2 samples.
The current time is 21/03/2023 9:51:40 AM.
09:51:40, +00.0811169s
09:51:42, +00.0801740s
```

**Comment by iSazonov** [comment]
pwsh is portable and cmdlet should work on all supported OSes including Linux-s and MacOS.

I see it is possible to have portable NTP client https://github.com/vbocan/sntp-client

The feature could be added to Get-Date cmdlet.

**Comment by rhubarb-geek-nz** [comment]
I suggest to use a PSGallery module, for example [NtpTime](https://www.powershellgallery.com/packages/NtpTime/1.1) already exists and uses `pool.ntp.org` by default.

```
PS> Get-NtpTime

NtpServer                 NtpTime               OffsetSeconds Stratum ReferenceIdentifier
---------                 -------               ------------- ------- -------------------
pool.ntp.org              12/03/2024 12:10:25          -0.001       2 68.166.61.255
```

**Comment by kasini3000** [comment]
another : 
https://gitee.com/chuanjiao10/kasini3000/blob/master/node_script/Get-NtpTime_v1.04.ps1
Welcome to the powershell script framework I wrote: kasini3000
kasini3000 can help you automatically push the scripts in the node_stcript directory to each Windows and Linux controlled machine.

**Comment by jdhitsolutions** [comment]
Submitted for the Cmdlet WG to review.

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets discussed this.  We agreed that community solutions already available are sufficient and recommended.
