### ISSUE TITLE
Expose an event corresponding to the runspace stopping

### ISSUE THREAD

**Issue by alx9r** [PowerShell/PowerShell#24646]
### Summary of the new feature / enhancement

As a user of long-running .Net calls that accept [`System.Threading.CancellationToken`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-9.0) I would like to be able to configure those calls to be canceled when I stop the PowerShell job where they are running.  To accomplish that I would need some way to obtain or fashion a `CancellationToken` whose cancellation corresponds to the job's runspace entering the "Stopping" state.  

Consider the desired use-case

```PowerShell
$job =
    Start-Job {
        $token =
            Get-RunspaceCancellationToken `
                -State Stopping
        # this is a stand-in for a cancellable long-running .Net task
        [System.Threading.Tasks.Task]::Delay(
            3000  , # millisecondsDelay
            $token
        ).Wait()
    }
# ...
$job | Stop-Job # this should cancel $token
$job | Wait-Job # this should complete without waiting for the whole millisecondsDelay
```

which would complete quickly after calling `Stop-Job`.  Contrast that with what is currently possible with public APIs

```PowerShell
$job =
    Start-Job {
        # this is a stand-in for a cancellable long-running .Net task
        [System.Threading.Tasks.Task]::Delay(
            3000  # millisecondsDelay
        ).Wait()
    }
# ...
$job | Stop-Job # this hangs waiting for Delay() to complete its full millisecondsDelay
```

which waits the full `millisecondsDelay` before completing.

### Proposed technical implementation details
The above seems to be possible using reflection to subscribe to a non-public `Stopping` state transition event.  A demonstration of that is shown in the code below.  That demo outputs 

```
TotalSeconds
------------
        0.64
begin
clean
```

which indicates the following:

- the job is successfully stopped long before the full `millisecondsDelay`
- the last line of `end{}` is never reached
- `clean{}` is invoked indicating graceful stopping of the runspace succeeded

#### Demo

```PowerShell
$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
$jobRunning = [System.Threading.EventWaitHandle]::new($false,'ManualReset','event_1f242755')
$job = Start-Job {
    begin { 'begin' | Set-Content .\log.txt }
    end {
        function Get-RunspaceCancellationToken {
            [OutputType([System.Threading.CancellationToken])]
            param(
                [runspace]
                $Runspace = ([runspace]::DefaultRunspace),
            
                [Parameter()]
                [System.Management.Automation.Runspaces.PipelineState]
                $State = [System.Management.Automation.Runspaces.PipelineState]::Stopping
            )            
            Add-Type @'
using System.Threading;
using System;
using System.Management.Automation.Runspaces;

namespace n {
    public static class RunspaceExtensions {
        public static EventHandler<PipelineStateEventArgs>
            GetPipelineStateChangeAction(
                CancellationTokenSource cts,
                PipelineState           state) {
            return (s,e)=> {
                if (e.PipelineStateInfo.State != state) {
                    return;
                }
                cts.Cancel();
            };
        }
    }
}        
'@
            $cts = [System.Threading.CancellationTokenSource]::new()
            $method = [runspace].GetMethod(
                'GetCurrentlyRunningPipeline',
                [System.Reflection.BindingFlags] 'NonPublic, Instance')
            $pipeline = $method.Invoke($Runspace, $null)
            $action = [n.RunspaceExtensions]::GetPipelineStateChangeAction($cts,$State)
            $pipeline.add_StateChanged($action)
            $cts.Token
        }
        $token =   
            Get-RunspaceCancellationToken `
                -State    Stopping
        $jobRunning = [System.Threading.EventWaitHandle]::new($false,'ManualReset','event_1f242755')
        $jobRunning.Set()            
        [System.Threading.Tasks.Task]::Delay(
            3000  , # int millisecondsDelay
            $token # System.Threading.CancellationToken cancellationToken
        ).Wait()
        'end' | Add-Content .\log.txt
    }
    clean { 'clean' | Add-Content .\log.txt }
}
$jobRunning.WaitOne() | Out-Null
$job | Stop-Job | Wait-Job | Receive-Job
$stopwatch.Elapsed | Select-Object TotalSeconds    
Get-Content .\log.txt
```

**Comment by santisq** [comment]
This might be something @jborean93's PR: https://github.com/PowerShell/PowerShell/pull/24620 might be able to solve (?)

**Comment by alx9r** [comment]
Thanks @santisq.  Somehow I missed that.  It looks like there are a handful of related proposals as follows:

- #19685 is sort of the inverse of this proposal.  This proposal suggests exposing a cancellation token that is canceled with the runspace, whereas #19685 suggests (I _think_) adding a cancellation token parameter to the common parameters.
- I think this proposal is a duplicate of #24620.  In particular,  [the PR Summary](https://github.com/PowerShell/PowerShell/pull/24620#issue-2695957668) states "This now makes it possible to do...`[MyType]::SomeMethodWithCancellation($PSCmdlet.PipelineStopToken)`" which would mean I could replace `$token` in my OP demo with `$PSCmdlet.PipelineStopToken`.  That sounds pretty great to me.  PowerShell/PowerShell-RFC#382 seems to confirm the same.

I'm closing this as a duplicate of #24620 and PowerShell/PowerShell-RFC#382.  I hope that makes it into PowerShell.

**Comment by alx9r** [comment]
>Right now the only public API is overriding the StopProcessing method in a compiled cmdlet which is called when the engine is requested to stop. 

@jborean93 If I'm understanding this correctly, there might be a way to emit a token from a compiled command (e.g. `CancellationContext` below) at the top of a PowerShell call stack that would be available to any descendants.  So it might look like the following:

```
Start-Job {
    CancellationContext {
        param($CancellationToken)
        # do all user work here
    }
 }
```

Your proposal is way nicer ergonomics, but this might be an adequate stop-gap.  At least the API used is public.

**Comment by alx9r** [comment]
>...there might be a way to emit a token from a compiled command...at the top of a PowerShell call stack that would be available to any descendants...

Yup.  This works.  There is a demo [here](https://stackoverflow.com/a/79256460/1404637).  I'd prefer the solution from the RFC, but this works even in Windows PowerShell.

**Comment by kasini3000** [comment]
Is there a script block for Linux?

$jobRunning = [System.Threading.EventWaitHandle]::new($false,'ManualReset','event_1f242755')
Exception calling ".ctor" with "3" argument(s): "The named version of this synchronization primitive is not supported on this platform."

**Comment by alx9r** [comment]
@kasini3000 I’m surprised by that error message.  [The API catalog entry for that overload](https://apisof.net/catalog/9d3cae23a98e413048bf9b5611126934) says “This API is supported on all platforms.”  For the use in my OP you can use another synchronization method like checking for files or probably even sleeps.

**Comment by kasini3000** [comment]
1 On Windows, the script block works as expected.
2 The above error is reported on Rocky Linux 9.2 x64 + PowerShell 7.5 preview 5.
3 use $jobRunning = [System.Threading.EventWaitHandle]::new($false,'ManualReset')  on this linux ,   hang!

**Comment by jborean93** [comment]
The docs are somewhat unclear but I don’t believe named EventWaitHandle is supported outside of Windows. It seems like the only cross platform synchronisation primitive that is supported is a Mutex https://learn.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives#waithandle-class-and-lightweight-synchronization-types

**Comment by alx9r** [comment]
@jborean93 Short of attempting to call each API on each platform, do you see a better way than apisof.net to check whether an API is supported?

**Comment by alx9r** [comment]
@kasini3000 I've update both the OP demo and [this demo](https://stackoverflow.com/a/79256460/1404637) to use a primitive that I expect is more linux-friendly.  But those demos now rely on thread jobs, which, I think, are still shipped as a separate module.

**Comment by jborean93** [comment]
> Short of attempting to call each API on each platform, do you see a better way than apisof.net to check whether an API is supported?

The documentation on the types and methods themselves. Granted the one for `EventWaitHandle` is vague enough in that it looks like a named event handle would work but maybe that's only for process scoped ones or some sort of documentation inheritance thing.

**Comment by kasini3000** [comment]
@alx9r good,thanks!
After my testing, the demo works as expected on Windows and Linux.

for next :
How to add parameters such as “-timeout 5(seconds)” to demo function

**Comment by santisq** [comment]
> @alx9r good,thanks! After my testing, the demo works as expected on Windows and Linux.
> 
> for next : How to add parameters such as “-timeout 5(seconds)” to demo function

I did my take including a timeout, last example from: https://github.com/santisq/PSUsing?tab=readme-ov-file#usage

**Comment by kasini3000** [comment]
@santisq  Thank you for sharing.
Would you be willing to PR "your C# code" to
https://github.com/PowerShell/ThreadJob/issues/26
when you have free time?

Or 
who is willing to do this?
Adding timeouts to the runspace-thread is important , But there is no hope in the long run.

**Comment by santisq** [comment]
Hi @kasini3000, I'll not be doing any PR but in case you want to have a `ThreadJob` that includes a `CancellationToken` and supports timeout, you can clone this fork: https://github.com/santisq/ThreadJob. It can basically allow you to do this:

![vpzcX5jNXB](https://github.com/user-attachments/assets/a950ba2d-6965-4459-ae6c-93b40184397c)

Hope it helps!

**Comment by kasini3000** [comment]
@santisq I'll give it a try
