### ISSUE TITLE
*-ScheduledTask errors when Scheduled Task has either MonthlyTrigger and MonthlyDOW triggers

### ISSUE THREAD

**Issue by Borgquite** [PowerShell/PowerShell#24651]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Re-opening #7292 which seems to have been auto-closed.

When trying to get, or set, triggers which use the MSFT_TaskMonthlyTrigger or MSFT_TaskMonthlyDOWTrigger trigger via Get-ScheduledTask, and Register-ScheduledTask, classes return incorrect types, and some values are unavailable. This prevents reading and writing scheduled tasks with these triggers when using native PowerShell. See bug above for more details.

There are two broad issues:

1. Classes do not have correct types on the properties. The values cannot be set because they become out of range due to incorrect typing on the CIM class. Only one is included here though there are also others that also appear incorrect.

```
$tempCimClass = Get-CimClass -ClassName MSFT_TaskMonthlyTrigger `
-Namespace Root/Microsoft/Windows/TaskScheduler:MSFT_TaskMonthlyTrigger
$tempCreatedTrigger = New-CimInstance -CimClass $tempCimClass -ClientOnly
$tempCimClass.CimClassProperties | Select *
```

**Expected behaviour**

```
Name : DaysOfMonth
Value :
CimType : UInt32 (really, if going by the API this should be a non-nullable long)
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :
```

**Actual behaviour**

```
Name : DaysOfMonth
Value :
CimType : UInt16
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :
```

2. Some classes are not typed correctly. When MSFT_TaskMonthlyTrigger or MSFT_TaskMonthlyDOWTrigger triggers are retrieved, they are typed as the base class (MSFT_TaskTrigger), and thus do not have the all the properties available on it for retrieval. You can get the actual classes here:

```
$tempCimClass = Get-CimClass -ClassName MSFT_TaskMonthlyTrigger `
-Namespace Root/Microsoft/Windows/TaskScheduler:MSFT_TaskMonthlyTrigger
$tempCimClass | Select *
```

```
$tempCimClass = Get-CimClass -ClassName MSFT_TaskMonthlyDOWTrigger `
-Namespace Root/Microsoft/Windows/TaskScheduler:MSFT_TaskMonthlyDOWTrigger
$tempCimClass | Select *
```

**Steps to reproduce**
Create monthly and monthly DOW trigger
![image](https://github.com/user-attachments/assets/5898439e-62ae-4eb8-9c05-54758c425998)

In PS:

```
$temp = (get-ciminstance -ClassName 'MSFT_ScheduledTask' -Namespace 'Root/Microsoft/Windows/TaskScheduler'
-Shallow:$false
) | Where-Object {
$_.TaskName -like 'test2' `
}
$temp.Triggers | Select *
```

**Expected behaviour**

```
Enabled : False
EndBoundary : 2019-07-13T21:50:17-05:00
ExecutionTimeLimit :
Id :
Repetition : MSFT_TaskRepetitionPattern
StartBoundary : 2018-07-13T21:50:15-05:00
PSComputerName :
CimClass : Root/Microsoft/Windows/TaskScheduler:**MSFT_TaskMonthlyTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties : Microsoft.Management.Infrastructure.CimSystemProperties

...CimInstanceProperties
Name : Enabled
Value :
CimType : Boolean
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : EndBoundary
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : ExecutionTimeLimit
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : Id
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : Repetition
Value :
CimType : Instance
Flags : Property, NullValue
Qualifiers : {EmbeddedInstance}
ReferenceClassName : MSFT_TaskRepetitionPattern

Name : StartBoundary
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : DaysOfMonth
Value :
CimType : UInt16
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : MonthOfYear
Value :
CimType : UInt16
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : RandomDelay
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : RunOnLastDayOfMonth
Value :
CimType : Boolean
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Enabled : False
EndBoundary :
ExecutionTimeLimit :
Id :
Repetition : MSFT_TaskRepetitionPattern
StartBoundary : 2018-07-15T13:47:26
PSComputerName :
CimClass : Root/Microsoft/Windows/TaskScheduler:MSFT_**TaskMonthlyDOWTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties : Microsoft.Management.Infrastructure.CimSystemProperties

...CimInstanceProperties

Name : Enabled
Value :
CimType : Boolean
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : EndBoundary
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : ExecutionTimeLimit
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : Id
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : Repetition
Value :
CimType : Instance
Flags : Property, NullValue
Qualifiers : {EmbeddedInstance}
ReferenceClassName : MSFT_TaskRepetitionPattern

Name : StartBoundary
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : DaysOfWeek
Value :
CimType : UInt16
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : MonthOfYear
Value :
CimType : UInt16
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : RandomDelay
Value :
CimType : String
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : RunOnLastWeekOfMonth
Value :
CimType : Boolean
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :

Name : WeeksOfMonth
Value :
CimType : UInt16
Flags : Property, NullValue
Qualifiers : {}
ReferenceClassName :
……….
```

**Actual behavior**

```
Enabled : False
EndBoundary : 2019-07-13T21:50:17-05:00
ExecutionTimeLimit :
Id :
Repetition : MSFT_TaskRepetitionPattern
StartBoundary : 2018-07-13T21:50:15-05:00
PSComputerName :
CimClass : Root/Microsoft/Windows/TaskScheduler:**MSFT_TaskTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties : Microsoft.Management.Infrastructure.CimSystemProperties

….CimInstanceProperties

Name : Enabled
Value : False
CimType : Boolean
Flags : Property, NotModified
IsValueModified : False

Name : EndBoundary
Value : 2019-07-13T21:50:17-05:00
CimType : String
Flags : Property, NotModified
IsValueModified : False

Name : ExecutionTimeLimit
Value :
CimType : String
Flags : Property, NotModified, NullValue
IsValueModified : False

Name : Id
Value :
CimType : String
Flags : Property, NotModified, NullValue
IsValueModified : False

Name : Repetition
Value : MSFT_TaskRepetitionPattern
CimType : Instance
Flags : Property, NotModified
IsValueModified : False

Name : StartBoundary
Value : 2018-07-13T21:50:15-05:00
CimType : String
Flags : Property, NotModified
IsValueModified : False

Enabled : False
EndBoundary :
ExecutionTimeLimit :
Id :
Repetition : MSFT_TaskRepetitionPattern
StartBoundary : 2018-07-15T13:47:26
PSComputerName :
CimClass : Root/Microsoft/Windows/TaskScheduler:**MSFT_TaskTrigger**
CimInstanceProperties : {Enabled, EndBoundary, ExecutionTimeLimit, Id...}
CimSystemProperties : Microsoft.Management.Infrastructure.CimSystemProperties

…CimInstanceProperties

Name : Enabled
Value : False
CimType : Boolean
Flags : Property, NotModified
IsValueModified : False

Name : EndBoundary
Value : 2019-07-13T21:50:17-05:00
CimType : String
Flags : Property, NotModified
IsValueModified : False

Name : ExecutionTimeLimit
Value :
CimType : String
Flags : Property, NotModified, NullValue
IsValueModified : False

Name : Id
Value :
CimType : String
Flags : Property, NotModified, NullValue
IsValueModified : False

Name : Repetition
Value : MSFT_TaskRepetitionPattern
CimType : Instance
Flags : Property, NotModified
IsValueModified : False

Name : StartBoundary
Value : 2018-07-13T21:50:15-05:00
CimType : String
Flags : Property, NotModified
IsValueModified : False

……...
```

Please can this behaviour be investigated. It would also be helpful for the New-ScheduledTaskTrigger cmdlet to natively support creating Monthly and MonthlyDOW triggers; however just being able to use the Get-CimInstance bypass for now, would help.

### Expected behavior

```console
See above
```

### Actual behavior

```console
See above
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SeeminglyScience** [comment]
Both the module and the cim class are not a part of this repo, you would need to submit feedback via the [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332)

**Comment by Borgquite** [comment]
Ah, the Feedback Hub, 'where bugs go to die'. Shame that it'll never get fixed.

**Comment by jborean93** [comment]
I had a look at the decompiled code for the `SchedProv` CIM implementation to see what is up with the Monthly and MonthlyDOW trigger and unfortunately it seems like it goes beyond just a simple typo in the MOF definition of these hinted at https://github.com/PowerShell/PowerShell/issues/7292#issuecomment-2508222706. The code that converts the CIM instance to the COM object used internally implements all the trigger types (0-11) except `TASK_TRIGGER_MONTHLY (4)` and `TASK_TRIGGER_MONTHLYDOW (5)`. This means there is no way of creating a scheduled task with one of those triggers using the CIM cmdlets in PowerShell.

The code that converts the COM object to the CIM instance that is returned with `Get-ScheduledTask` also has not implemented any logic for these trigger types so it always returns the base class `MSFT_TaskTrigger` so you'll never be able to retrieve the specific trigger values for these two types.

The three things you can do here to define a task with these trigger types

+ Use `schtasks.exe` as it does expose these options on the cmdline
+ Define the task manually, export the XML and use that when registering the task instead of building the object through the CIM classes (I haven't tested this but it should work)
+ Use the COM API that the CIM cmdlets are driving in the background
  + Example of the `MonthlyDOW` can be found at https://gist.github.com/jborean93/bc4b29f4a98b785b28d4a7fee75c1480
  + The first revision of that gist also shows the `Monthly` trigger example

Would be great if MS would actually implement this but I doubt that would happen and this repo would have no sway over that decision.

<blockquote><img src="https://github.githubassets.com/assets/gist-og-image-54fd7dc0713e.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/jborean93/bc4b29f4a98b785b28d4a7fee75c1480">How to create a scheduled task with a monthly day of week trigger in PowerShell</a></strong></div><div>How to create a scheduled task with a monthly day of week trigger in PowerShell - MonthlyDOWTask-COM.ps1</div></blockquote>
