### ISSUE TITLE
The test `HelpSystem.OnlineHelp.Tests.ps1` needs to be updated after fixing #951

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#2465]
Two issues about `test/powershell/engine/HelpSystem.OnlineHelp.Tests.ps1`:
- [ ] Some tests don't need to be skipped on Linux and OSX after fixing #951
- [ ] Test data files `V2Cmdlets.csv` and `V3Cmdlets.csv` should be put in "assets" folder, not `testdata` folder. Run `dir assets -Recurse` under `PowerShell\test\powershell` for examples. So basically, the folder `engine\testdata` needs to be renamed to `engine\assets`.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
