### ISSUE TITLE
Unable to find WPF types even after `Add-Type`

### ISSUE THREAD

**Issue by HO-COOH** [PowerShell/PowerShell#24655]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am trying to write a simple WPF GUI in powershell. It seems that powershell is unable to find wpf types even when I put `Add-Type -AssemblyName PresentationFramework, PresentationCore` on the first line of the script. It only works if I first type that line inside the terminal.

What's more, it seems like the line is not even executed, because I ran it inside the vscode with powershell extension, and the break point on the `Add-Type` line is not hit.

Create a `test.ps1`,
```powershell
Add-Type -AssemblyName PresentationFramework, PresentationCore

class Window 
{
    [System.Windows.Window]$window
    [System.Windows.Controls.Button]$button
    [int]$count = 0

    Window()
    {
        [xml]$xaml = @"
        <Window
            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            x:Name="Window"
            Title="C#Shell!">
            <Grid x:Name="Grid">
                <Grid.RowDefinitions>
                    <RowDefinition Height="*"/>
                    <RowDefinition Height="100"/>
                </Grid.RowDefinitions>
                
                <ListView x:Name="List" />
                <Button x:Name="AddButton" Content="Add" Grid.Row="1"/>
            </Grid>
        </Window>
"@
        $reader = [System.Xml.XmlNodeReader]::new($xaml)
        $this.window = [System.Windows.Markup.XamlReader]::Load($reader)
        $this.button = $this.window.FindName("AddButton")
        $this.button.Add_Click({
            param($sender, $arg)
            [Window]$parentWindow = Get-Variable this -Scope 1 -ValueOnly -EA 0
            $parentWindow.window.FindName("List").Items.Add("Item" + ($parentWindow.count++).ToString())
        })
        $this.window.ShowDialog()
    }
}

$window = [Window]::new()
```
Run it inside terminal

### Expected behavior

```console
Run successfully
```

### Actual behavior

```console
PS C:\Users\Test\Desktop\powershellTest> .\test.ps1
ParserError: C:\Users\Test\Desktop\powershellTest\test.ps1:5
Line |
   5 |      [System.Windows.Window]$window
     |       ~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [System.Windows.Window].
```
```


### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
```


### Visuals

_No response_

**Comment by rhubarb-geek-nz** [comment]
I suggest it is because the parsing of the class happens _before_ the script is actually executed.

If you remove the `Add-Type`, but run it in the powershell sesssion before running your script then it works.

So, literally, the reason Add-Type is not executed is because the parsing of the script file fails before it gets to executing any statements.

A PowerShell script is not executed line by line, the entire script is loaded and parsed prior to execution.

So you could try splitting your program into two scripts, one which loads the dependant modules and the second which contains your gui app.

Alternatively remove replace the types System.Windows.Window and System.Windows.Controls.Button with Object, and use reflection to invoke the System.Windows.Markup.XamlReader.Load method.

**Comment by mklement0** [comment]
This problem has come up several times before; for a summary of the state of affairs, see:

* https://github.com/PowerShell/PowerShell/issues/21140#issuecomment-1910416737
* Also: #18482
