### ISSUE TITLE
Add EventGridSystemTopicEventSubscription with deadletter not working

### ISSUE THREAD

**Issue by nulllogicone** [PowerShell/PowerShell#24664]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I want to create an event subscription for a FunctionApp on a SystemTopic but can not find how to define the DeadletterEndpoint. My pipeline has Az module v12.5.0 installed.

The following code is working but how can I define the storage account container for deadletter?

```
$funcid = "/subscriptions/$funcSubID/resourceGroups/$func_rg/providers/Microsoft.Web/sites/$funcapp/functions/$func_name" $func_evdo = New-AzEventGridAzureFunctionEventSubscriptionDestinationObject -ResourceId $funcid

New-AzEventGridSystemTopicEventSubscription -ResourceGroupName $resourceGroupName `       
   -eventSubscriptionName $eventSubscriptionName `         
   -systemTopicName $systemTopicName `         
   -destination $func_evdo
```

I searched this documentation but couldn't find something about DeadletterEndpoint or destination: https://learn.microsoft.com/en-us/powershell/module/az.eventgrid/new-azeventgridsystemtopiceventsubscription?view=azps-12.5.0

### Expected behavior

```console
A parameter that allows me to define a deadletter container
```

### Actual behavior

```console
Missing parameter
```

### Error details

```console
The term 'DeadletterEndpoint' can not be found
```

### Environment data

```powershell
Az module v 12.5.0
```

**Comment by mklement0** [comment]
The command in question isn't being maintained in this repository, please post your issue in the [`azure-powershell` repo](https://github.com/Azure/azure-powershell) instead.

For future reference: There is general guidance on determining the appropriate place to report a given issue in  [Can Windows/Non-Core PowerShell 5 bugs be reported here?](https://github.com/PowerShell/PowerShell/discussions/24299).

**Comment by nulllogicone** [comment]
Thank you @mklement0 for pointing me to the right repo, I reported it there.
