### ISSUE TITLE
Can't redirect Process output with `add_OutputDataReceived` / `add_ErrorDataReceived`

### ISSUE THREAD

**Issue by akbyrd** [PowerShell/PowerShell#24687]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Run this script
```
$process = New-Object System.Diagnostics.Process
$process.StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$process.StartInfo.FileName = "cmd"
$process.StartInfo.RedirectStandardOutput = $true
$process.StartInfo.UseShellExecute = $false
$process.StartInfo.CreateNoWindow = $true

$process.add_OutputDataReceived({})

$process.Start()
$process.BeginOutputReadLine()
```

Observe error
```
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.Management.Automation.PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:
   at System.Management.Automation.ScriptBlock.GetContextFromTLS()
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at lambda_method150(Closure, Object, DataReceivedEventArgs)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

It seems like this was supposed to be fixed according to https://github.com/PowerShell/PowerShell/issues/11658, however I'm still encountering it on 7.4.6.

### Expected behavior

```console
It is possible to add a script block to `add_OutputDataReceived` and `add_ErrorDataReceived`.

Without this capability, working with a Process can become onerous. For example, if handling stdout and stderr can't be done on a separate thread it's not possible to use synchronous operations on stdin. Writing to stdin may deadlock because stderr is full and needs to be read
```

### Actual behavior

```console
Adding a script block to `add_OutputDataReceived` or `add_ErrorDataReceived` terminates pwsh abnormally.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Visuals

_No response_

**Comment by SeeminglyScience** [comment]
In the linked issue they are using a synchronizing object (specifically a winform control). ScriptBlocks cannot run in a thread without a runspace and we can't generically any API handle that.

In most cases where you have an event that will trigger on a different thread, you need to use the [`Register-ObjectEvent`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/register-objectevent?view=powershell-7.4) cmdlet.

**Comment by akbyrd** [comment]
When I tested `Register-ObjectEvent` it didn't appear to be suitable for this use case. I think what happens is that the callback is queued in a task pool. So you can still hit a deadlock if the process writes to stdout and the script does a blocking write to the process' stdin. It _should_ be possible to do async reads from stdout and sync writes to stdin but the object event workaround prevents it.

**Comment by SeeminglyScience** [comment]
> When I tested `Register-ObjectEvent` it didn't appear to be suitable for this use case. I think what happens is that the callback is queued in a task pool. So you can still hit a deadlock if the process writes to stdout and the script does a blocking write to the process' stdin. It _should_ be possible to do async reads from stdout and sync writes to stdin but the object event workaround prevents it.

It's definitely challenging no doubt, but definitely doable. You need to make sure you aren't blocking the pipeline, easiest way is with a while loop (e.g. `while (-not $process.WaitForExit(200)) { }`). That allows the "pulse" (event processing) pipeline to take over the thread briefly to process the event.

I've also heard it's easier to use `Wait-Event` instead of the while loop trick, but don't have any experience with it myself. If you need more assistance figuring it out I'd highly recommend asking on the [PowerShell Community Discord](https://aka.ms/psdiscord).

**Comment by akbyrd** [comment]
I'll pop onto the discord, but I'm not sure either of those prevent the deadlock.

The case in question is:
* Long running process with back-and-forth communication
* Script handles stderr event
* Process fills stderr again and blocks
* Script does a blocking write to stdin
* Deadlock

The documentation for Process says it is legal to mix non-blocking ops on one stream and blocking ops on another. Which makes sense because my writes can block as long as I can service stdout and stderr asynchronously while the write is blocked to allow the process to get to my 

But this limitation in pwsh means it's not possible to implement truly async reads.

I apologize if I'm misunderstanding. I'm not trying to turn this into a technical support thread. But if I'm correct it seems like significant issue if it's not possible to use Process safely from PowerShell.

**Comment by SeeminglyScience** [comment]
> * Process fills stderr again and blocks

The handler that `Register-ObjectEvent` registers won't block, it adds the event args to queue and then returns. PowerShell's event system reads from that queue in between loop iterations.

> I apologize if I'm misunderstanding. I'm not trying to turn this into a technical support thread. But if I'm correct it seems like significant issue if it's not possible to use Process safely from PowerShell.

While I do think you can accomplish what you want to do here, you also aren't wrong. Threading is a weak point in PowerShell due to its design and architecture. Some things will definitely be far easier in C#. It doesn't come up as often as you'd think though
