### ISSUE TITLE
Powershell Encoding change after setting into $variable ,lead to chinese characters error

### ISSUE THREAD

**Issue by CN-CODEGOD** [PowerShell/PowerShell#24683]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

run an node JavaScript from powershell and setting the chinese output into $variable

### Expected behavior

```console
PS C:\Users\Adminnistrator\my-modules\dre>  node $Pwd\GETtitle.js "https://osu.ppy.sh/users/36821905"
(node:13164) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
网页标题: _flyhigh · player info | osu!
```

### Actual behavior

```console
PS C:\Users\Adminnistrator\my-modules\dre>  $title = node $Pwd\GETtitle.js "https://osu.ppy.sh/users/36821905"
>>  $title
(node:14860) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
缃戦〉鏍囬: _flyhigh 路 player info | osu!
```

### Error details

```console
null
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.5.0-rc.1
PSEdition                      Core
GitCommitId                    7.5.0-rc.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0鈥
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by CN-CODEGOD** [comment]
> When you run an executable without capturing the var or redirecting it, the application will write directly to the console stream. This API operates on strings and thus doesn't really need to deal with encoding. If you were to capture the output, or redirect it in PowerShell the application is now started with a redirected stdout pipe. Instead of the application writing to the console buffers directly it now writes the output to the redirected output pipe.
> 
> This pipe must have the output encoded as bytes and thus will be encoded through an encoding scheme. The standard is for applications to use the console output encoding setting but some applications ignore this and either use some other settings, or in this case it's probably hardcoded to use UTF-8. When PowerShell reads these bytes from the application it will use the value of `[Console]::OutputEncoding` to decode those raw bytes back into a string and if this encoding value does not match the encoding the application uses then you'll get the incorrect output back.
> 
> Assuming the Javascript application is always using UTF-8 you can do the following to capture the output and decode the bytes using UTF-8 with
> 
> ```powershell
> $origEncoding = [Console]::OutputEncoding
> try {
>     [Console]::OutputEncoding = [Text.UTF8Encoding]::new()
>     $output = node $Pwd\GETtitle.js ...
> }
> finally {
>     [Console]::OutputEncoding = $origEncoding
> }
> 
> $output
> ```

i used iconv- to change encoding into utf-8, which will result utf-8 output 
```
const decodedOutput = iconv.decode(Buffer.from(stdout, binaryEncoding), encoding);
    try {
        const dom = new JSDOM(decodedOutput);
        console.log(`${dom.window.document.title}`);
    } catch (err) {
        console.error( iconv.decode(Buffer.from(err.message, binaryEncoding), encoding));
    }
```

**Comment by CN-CODEGOD** [comment]
> When you run an executable without capturing the var or redirecting it, the application will write directly to the console stream. This API operates on strings and thus doesn't really need to deal with encoding. If you were to capture the output, or redirect it in PowerShell the application is now started with a redirected stdout pipe. Instead of the application writing to the console buffers directly it now writes the output to the redirected output pipe.
> 
> This pipe must have the output encoded as bytes and thus will be encoded through an encoding scheme. The standard is for applications to use the console output encoding setting but some applications ignore this and either use some other settings, or in this case it's probably hardcoded to use UTF-8. When PowerShell reads these bytes from the application it will use the value of `[Console]::OutputEncoding` to decode those raw bytes back into a string and if this encoding value does not match the encoding the application uses then you'll get the incorrect output back.
> 
> Assuming the Javascript application is always using UTF-8 you can do the following to capture the output and decode the bytes using UTF-8 with
> 
> ```powershell
> $origEncoding = [Console]::OutputEncoding
> try {
>     [Console]::OutputEncoding = [Text.UTF8Encoding]::new()
>     $output = node $Pwd\GETtitle.js ...
> }
> finally {
>     [Console]::OutputEncoding = $origEncoding
> }
> 
> $output
> ```

i have tried to change the console encoding ,but the output was error too
```
$origEncoding = [Console]::OutputEncoding
try {
    [Console]::OutputEncoding = [Text.UTF8Encoding]::new()
    $output = node "C:\Users\Adminnistrator\my-modules\dre\GETtitle.js" "https://www.bilibili.com/"
}
finally {
    [Console]::OutputEncoding = $origEncoding
}

$output


网页标题: 鍝斿摡鍝斿摡 (銈�-銈�)銇ゃ儹 骞叉澂~-bilibili
```

**Comment by CN-CODEGOD** [comment]
> > When you run an executable without capturing the var or redirecting it, the application will write directly to the console stream. This API operates on strings and thus doesn't really need to deal with encoding. If you were to capture the output, or redirect it in PowerShell the application is now started with a redirected stdout pipe. Instead of the application writing to the console buffers directly it now writes the output to the redirected output pipe.
> > This pipe must have the output encoded as bytes and thus will be encoded through an encoding scheme. The standard is for applications to use the console output encoding setting but some applications ignore this and either use some other settings, or in this case it's probably hardcoded to use UTF-8. When PowerShell reads these bytes from the application it will use the value of `[Console]::OutputEncoding` to decode those raw bytes back into a string and if this encoding value does not match the encoding the application uses then you'll get the incorrect output back.
> > Assuming the Javascript application is always using UTF-8 you can do the following to capture the output and decode the bytes using UTF-8 with
> > ```powershell
> > $origEncoding = [Console]::OutputEncoding
> > try {
> >     [Console]::OutputEncoding = [Text.UTF8Encoding]::new()
> >     $output = node $Pwd\GETtitle.js ...
> > }
> > finally {
> >     [Console]::OutputEncoding = $origEncoding
> > }
> > 
> > $output
> > ```
> 
> i have tried to change the console encoding ,but the output was error too
> 
> ```
> $origEncoding = [Console]::OutputEncoding
> try {
>     [Console]::OutputEncoding = [Text.UTF8Encoding]::new()
>     $output = node "C:\Users\Adminnistrator\my-modules\dre\GETtitle.js" "https://www.bilibili.com/"
> }
> finally {
>     [Console]::OutputEncoding = $origEncoding
> }
> 
> $output
> 
> 
> 网页标题: 鍝斿摡鍝斿摡 (銈�-銈�)銇ゃ儹 骞叉澂~-bilibili
> ```

it turns out to be the problem solve easily by turn the system encoding into beta utf-8
![image](https://github.com/user-attachments/assets/2e389f2e-2c80-407e-906d-778e76b08783)

**Comment by kasini3000** [comment]
$a = Invoke-WebRequest https://www.bilibili.com/video/BV1YwkPYjEQV/
$a.Content.split('<title')[1].split('/title')[0]

data-vue-meta="true">《岩羊攀岩》青海海南藏族自治州-----失足蹄子摔死动力老师昆仑舔盐纪录片每一只岩羊都是绝对的攀岩高手徒手攀岩者入门世界杯比赛指力训练少女钟离鞋子视频_哔哩哔哩_bilibili<

**Comment by jhoneill** [comment]
I wrote a long post about it here. https://jhoneill.github.io/2023/03/14/utf.html But basically it's the value of $outputEncoding, [console]::outputEncoding and [console]::InputEncoding not matching the default code page.

**Comment by jborean93** [comment]
@jhoneill nice post, I do recommend updating `$OutputEncoding = [console]::OutputEncoding = [console]::InputEncoding = [System.Text.Encoding]::UTF8` to be `$OutputEncoding = [console]::OutputEncoding = [console]::InputEncoding = [System.Text.UTF8Encoding]::new()` though. The `UTF8` static property is set to UTF8 with BOM so it means doing `"foo" | some.exe` will include the BOM bytes in the data sent to `some.exe`.

```powershell
PS > $OutputEncoding = [System.Text.Encoding]::UTF8
PS > 'café' | hexdump -C                           
00000000  ef bb bf 63 61 66 c3 a9  0a                       |...caf...|
00000009
PS > $OutputEncoding = [System.Text.UTF8Encoding]::new()
PS > 'café' | hexdump -C                                
00000000  63 61 66 c3 a9 0a                                 |caf...|
00000006
```

**Comment by jhoneill** [comment]
> @jhoneill nice post, I do recommend updating `$OutputEncoding = [console]::OutputEncoding = [console]::InputEncoding = [System.Text.Encoding]::UTF8` to be `$OutputEncoding = [console]::OutputEncoding = [console]::InputEncoding = [System.Text.UTF8Encoding]::new()` though. 


Yeah, I should probably change that.

**Comment by CN-CODEGOD** [comment]
> @jhoneill nice post, I do recommend updating `$OutputEncoding = [console]::OutputEncoding = [console]::InputEncoding = [System.Text.Encoding]::UTF8` to be `$OutputEncoding = [console]::OutputEncoding = [console]::InputEncoding = [System.Text.UTF8Encoding]::new()` though. The `UTF8` static property is set to UTF8 with BOM so it means doing `"foo" | some.exe` will include the BOM bytes in the data sent to `some.exe`.
> 
> ```powershell
> PS > $OutputEncoding = [System.Text.Encoding]::UTF8
> PS > 'café' | hexdump -C                           
> 00000000  ef bb bf 63 61 66 c3 a9  0a                       |...caf...|
> 00000009
> PS > $OutputEncoding = [System.Text.UTF8Encoding]::new()
> PS > 'café' | hexdump -C                                
> 00000000  63 61 66 c3 a9 0a                                 |caf...|
> 00000006
> ```
 in my case there was an error by setting the bytes into variable 
```
  $title = node $Pwd\GETtitle.js "https://osu.ppy.sh/users/36821905"
>>  $title

缃戦〉鏍囬: _flyhigh 路 player info | osu!
```

and i was changing the encode at javascript ,so this cause the error occur
by changing the system encoding to beta uft-8 , i don't need to change the encoding in javascript and it work fine after output to powershell
