### ISSUE TITLE
command “ cd - ”

### ISSUE THREAD

**Issue by raoyi** [PowerShell/PowerShell#24691]
### Summary of the new feature / enhancement

As a user, I want PowerShell support the command " cd - " like Linux shell.

**Comment by 237dmitry** [comment]
Did you try it?

**Comment by raoyi** [comment]
I have tried it in windows powershell, but it is not available. version:5.1.26100.2161
![5](https://github.com/user-attachments/assets/c3c1004b-ce3f-4b3e-8cf7-655ab747f0ec)

**Comment by 237dmitry** [comment]
> I have tried it in windows powershell, but it is not available. version:5.1.26100.2161
>> version:5.1.26100.2161

This repo is only for PowerShell 7.

From Set-Location help topic

```
DESCRIPTION
    The Set-Location cmdlet sets the working location to a specified location. That location could be a directory,
    a subdirectory, a registry location, or any provider path.
    
    PowerShell 6.2 added support for - and + as a values for the Path parameter. PowerShell maintains a history
    of the last 20 locations that can be accessed with - and +. This list is independent from the location stack
    that is accessed using the StackName parameter.
```

**Comment by jhoneill** [comment]
https://gist.github.com/jhoneill/47f5151b22a1dabb4ddc79c083162f77 

I put this into my profile years and years ago for Windows PowerShell. Still works with PowerShell 7 as well as `cd -` I have `cd ....`  for up 3 levels  `cd = [tab]` to cycle through past directories on the stack, `cd ~~pic[tab]` for my pictures.   `cd ^` for the profile directory.  Plus missing the space out of `cd ~`  `cd \` and `cd ..` all work
