### ISSUE TITLE
Copy-Item folder recursively to WinRm session is broken in Powershell 5.1.*.*

### ISSUE THREAD

**Issue by stishkin** [PowerShell/PowerShell#2469]
## Steps to reproduce

Copy a folder recursively to a remote session (WinRM)

Copy-Item $PSScriptRoot\TemplateUtils -Destination C:\ -Force -Recurse -ToSession $session 
## Expected behavior

Copy succeeds and this worked for Powershell 5.0._._

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  494
```
## Actual behavior

```
copy : Unable to index into an object of type System.IO.DirectoryInfo.

+     copy $PSScriptRoot\TemplateUtils -Destination C:\ -Force -Recurse ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (0:Int32) [Copy-Item], RuntimeException
    + FullyQualifiedErrorId : CannotIndex
```
## Environment data

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14942  1000
```

``` powershell
> $PSVersionTable

```

**Comment by stishkin** [comment]
The copy fails to a WinRm session over https. In particular we the following function to create the session:


function SecureRemotePSToAnAzureVM_ARM(
      [Parameter(Mandatory=$true)]$ResourceGroup
    , [Parameter(Mandatory=$true)]$VMName
    # Name of the KeyVault containing the WinRM certificate
    , [Parameter(Mandatory=$true)]$VaultName
    # Name of the certificate
    , $WinRMSecretName
    , $Credential
)
{
    Write-Host "Downloading certificate from azure vault"
    Import-PfxCertificateFromKeyVaultToLocalStore -VaultName $VaultName -secretName $WinRMSecretName

    # Get Public IP address from resource group
    $c = GetBackendIpAndPort -resourceGroup $resourceGroup -ruleName 'WinRM_HTTPS' -defaultPort 5986

    # Construct the RemotePS/WinRM Uri to connect to
    # Enter a remote PS session on the VM
    $uri = "https://$($c.hostname):$($c.port)"
    $ipUri = "https://$($c.ipaddress):$($c.port)"
    Write-Host "WinRM secured:" $uri "(IP: $ipUri)"
    $options = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
    New-PSSession -ConnectionUri $uri -Credential $Credential -SessionOption $options
}


The copy to this session does fail with the described error

**Comment by stishkin** [comment]
Another bit of information: the target VM OS is Windows Server 2008 R2

**Comment by PaulHigin** [comment]
This is a good find.  This bug was introduced in V5.x with the addition of copy-item -tosession functionality.  Fortunately this only affects copying to a V2 remote session.  The reason for this bug is that the one helper function copied to the remote session uses a script feature that is not available in PowerShell V2 (the ability to use '[0]' to select the first element on an non-array type).  This is in the PSValidatePathDefinition function:
```powershell
        # Get the root path using Get-Item
        $item = Microsoft.PowerShell.Management\Get-Item $pathToValidate -ea SilentlyContinue
        if (($item -ne $null) -and ($item[0].PSProvider.Name -eq 'FileSystem'))
        {
...
```
$item[0] results in the "Unable to index into an object of type System.IO.DirectoryInfo." error.  The file copy still works because fortunately there is enough information returned to continue with the copy operation.

**Comment by stishkin** [comment]
@PaulHigin  you are right, copy works fine. The problem becomes bigger when I try to do copy -fromSession

See the last error at the end of the list below

Copy : Unable to index into an object of type System.IO.FileInfo.

+ ...             Copy -FromSession $session $remoteSymbolsListPath -Destin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (0:Int32) [Copy-Item], RuntimeException
    + FullyQualifiedErrorId : CannotIndex
 
Copy : Parameter attributes need to be a constant or a script block.
+ ...             Copy -FromSession $session $remoteSymbolsListPath -Destin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Management.Automation.PowerShell:PowerShell) [Copy-Item], RemoteException
    + FullyQualifiedErrorId : CopyFileRemoteExecutionError,Microsoft.PowerShell.Commands.CopyItemCommand
 
Copy : The term 'PSCopyFromSessionHelper' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.

**Comment by PaulHigin** [comment]
@stishkin Thanks, I didn't notice that before.  This is a similar issue except that in this case the helper function (PSCopyFromSessionHelper) won't parse because it is using a parameter validation attribute not supported in V2.
```powershell
[ValidateRange(0, [long]::MaxValue)]
```
V2 won't evaluate [long]::MaxValue.
This case is worse because the helper function is not available and so the copy operation will not run.

**Comment by SteveL-MSFT** [comment]
@Francisco-Gamino /cc

**Comment by hayleybai** [comment]
Do this issue has any flexible solution?
@Francisco-Gamino 
@palladia

**Comment by pmartindev** [comment]
Is there any workaround for this issue?

**Comment by SteveL-MSFT** [comment]
Since this only affects remoting to v2, this is no longer a priority as v2 is formally deprecated

**Comment by pmartindev** [comment]
@SteveL-MSFT Sounds good. I've posted this question on SE as well. If anyone finds a resolution for it, and would care to post it there as well for others, it would be greatly appreciated!
https://serverfault.com/questions/891643/copy-item-tosession-from-powershell-v-5-0-to-v-2-0

**Comment by SteveL-MSFT** [comment]
@pmartindev my recommendation is to use https://github.com/PowerShell/Win32-OpenSSH/releases with `scp` to copy files

**Comment by TylerLeonhardt** [comment]
I think we can probably close this issue now, right? 2yo, only repros with v2...

**Comment by jmbeach** [comment]
I found a workaround that I like a good bit.

```
function Copy-ItemRemote {
  param (
      [Parameter(Mandatory)][string] $filePath,
      [Parameter(Mandatory)][string] $destination,
      [Parameter(Mandatory)][System.Management.Automation.Runspaces.PSSession] $session
  )
  Invoke-Command -Session $session -ScriptBlock {
    param($txt, $destination)
    [System.Io.File]::WriteAllText($destination, $txt);
  } -ArgumentList ([System.IO.File]::ReadAllText($filePath)), $destination;
}
```

based on the solution [here](https://social.technet.microsoft.com/Forums/en-US/64a3d37c-9828-4feb-817a-d28e7a147f25/copy-file-from-local-to-remote?forum=winserverpowershell)

[here it is](https://github.com/jmbeach/custom-powershell-scripts/blob/99bc2af706c3eac8d29430cecc7c187db5077508/file-utilities.ps1#L104) in my personal scripts repo with better documentation. Wouldn't be hard to make this recursive; although it might take some thought to make it efficient.
