### ISSUE TITLE
CTRL+backspace behavior is unexpected when `&&` is involved

### ISSUE THREAD

**Issue by MartyIX** [PowerShell/PowerShell#24718]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Behavior of CTRL+BACKSPACE seems counterintuitive. 

I'm not an expert on this topic so perhaps I'm just simply wrong but it would save some of my time as a PowerShell user if the behavior were as described below.

### Expected behavior

1. Type `dotnet restore --force-evaluate &&` (note the `&&`)
2. Press CTRL+BACKSPACE (to delete the last word)
3. `dotnet restore --force-evaluate` 

### Actual behavior

I would expect this to behave like this:

1. Type `dotnet restore --force-evaluate &&`
2. Press CTRL+BACKSPACE (to delete the last word)
3. `dotnet restore --force-`

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by surfingoldelephant** [comment]
That behavior is controlled by [`PSReadLine`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline), specifically, its [`BackwardKillWord`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline_functions#backwardkillword) function which is bound by default to `Ctrl+Backspace`.

If you start a new session without `PSReadLine` (or remove it from the current), you'll see different behavior, depending on your terminal. E.g., with `conhost.exe`, only the `&&` token is removed:

```powershell
pwsh -NoProfile -NonInteractive # Launch without PSReadLine
restore --force-evaluate &&<Ctrl+Backspace>

# restore --force-evaluate 
```

This issue in the [`PSReadLine` repo](https://github.com/PowerShell/PSReadLine) reports the same behavior: 
* https://github.com/PowerShell/PSReadLine/issues/4275 

What you're looking for is token-based deletion, which [`ShellBackwardKillWord`](https://learn.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline_functions#shellbackwardkillword) and other `Shell*` functions provide.

```powershell
Set-PSReadLineKeyHandler -Chord Ctrl+Backspace -Function ShellBackwardKillWord
restore --force-evaluate &&<Ctrl+Backspace>

# restore --force-evaluate 
```

Add the `Set-PSReadLineKeyHandler` change to your `$PROFILE` to persist it across sessions. If you want to adjust the behavior further (e.g., remove the trailing space as well), you will need to write your own [custom keyhandler](https://learn.microsoft.com/en-us/powershell/module/psreadline/set-psreadlinekeyhandler#example-2-bind-a-key-to-a-script-block).
