### ISSUE TITLE
copy-item does not respect -ErrorAction SilentlyContinue if file is in use

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2474]
TFS:7761026

``` powershell
PS C:\Users\ststair> copy c:\windows\system32\cmd.exe
PS C:\Users\ststair> start .\cmd
PS C:\Users\ststair> copy c:\windows\system32\cmd.exe -erroraction SilentlyContinue
copy : The process cannot access the file 'C:\Users\ststair\cmd.exe' because it is being used by another process.
At line:1 char:1
+ copy c:\windows\system32\cmd.exe -erroraction SilentlyContinue
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Copy-Item], IOException
+ FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.CopyItemCommand
```

**Comment by JVimes** [comment]
This bug is a time waster.

**Comment by SteveL-MSFT** [comment]
@JVimes just to be clear, it's a `time waster` in that because the bug exists it wastes your time or that it's a waste of time to fix?

**Comment by JVimes** [comment]
Oh, yes, it wasted my time as a user (I should have been clearer). I spent time trying everything out I could think of, assuming I was doing something wrong. I think most users are in the same boat.

**Comment by SteveL-MSFT** [comment]
@JVimes thanks for the clarification.  This should be a simple change, I'll take a quick look.

**Comment by JVimes** [comment]
Thank you so much Steve. Inconsistent or unpredictable behavior is frustrating, and does bad things for the product reputation. I appreciate the effort.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree this should be a non-terminating error.  We also ask that other `*-Item` cmdlets be reviewed to see if they have similar issue and all should be consistent.

**Comment by mi-hol** [comment]
@SteveL-MSFT it seems this issue is falling through the cracks. Any chance this annoying defect could be addressed in version 7, when everybody expects a breaking change?
