### ISSUE TITLE
Default permissions is 744 when i use New-Item to create a file

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2481]
How to create a new text file? such as 'a.txt'?
linux shell user can 'touch a.txt' in common use.
powershell user can 'new-item -path a.txt -ItemType File' in common use.  
I found permissions was not 644, but 744. why?
permissions 644 is POSIX standard,right?
## Steps to reproduce

``` powershell
new-item -path a.txt -ItemType File
```
## Expected behavior

permissions 644 is POSIX standard,right?
## Actual behavior

permissions is 744
## Environment data

```
Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-alpha                                                                                                       
PSEdition                      Core                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   3.0.0.0                                                                                                           
GitCommitId                    v6.0.0-alpha.10                                                                                                   
CLRVersion                                                                                                                                       
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1 
```

on centos 7
## reporter

By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by andschwa** [comment]
Oh boy, that's funky. It shouldn't be executable, you're right.

**Comment by thezim** [comment]
This should take umask into account as well.

**Comment by nzubair** [comment]
It doesn't look like a PowerShell issue, rather .Net Core issue.  Seems like a deliberate choice was made to leave user's execution bit in place.  Not sure about umask interaction though. 

https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/UnixFileStream.cs#L116-L124  [canonical](https://github.com/dotnet/corefx/blob/c9b1b944763aa8aa83c3bad29c12c4845ef38f21/src/System.IO.FileSystem/src/System/IO/UnixFileStream.cs#L116-L124)

Seeing the same behavior when compiling a simple C# program which does a File.Create(). 

```
nasir:~/projects$ umask
0022
nasir:~/projects$ touch test1.txt
nasir:~/projects$ ls -al
total 8
drwxr-xr-x 2 nasir nasir 0 Oct 18 14:18 .
drwxr-xr-x 2 nasir nasir 0 Oct 18 14:04 ..
drwxr-xr-x 2 nasir nasir 0 Oct 18 14:13 hello
-rw-r--r-- 1 nasir nasir 0 Oct 18 14:18 test1.txt
nasir:~/projects$ powershell -Command "New-Item -Path test2.txt -ItemType File"


    Directory: /home/nasir/projects


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
------         10/18/16   2:19 PM              0 test2.txt


nasir:~/projects$ ls -al
total 8
drwxr-xr-x 2 nasir nasir 0 Oct 18 14:19 .
drwxr-xr-x 2 nasir nasir 0 Oct 18 14:04 ..
drwxr-xr-x 2 nasir nasir 0 Oct 18 14:13 hello
-rw-r--r-- 1 nasir nasir 0 Oct 18 14:18 test1.txt
-rwxr--r-- 1 nasir nasir 0 Oct 18 14:19 test2.txt
nasir:~/projects$
```

**Comment by bjtucker** [comment]
It does seem to respect changes to umask.

but the umask command won't change the umask within the powershell session. It appears powershell spawns a separate shell which is then discarded. 

    PS> umask
    0022
    PS> touch t
    PS> ls -la t
    -rw-r--r--  1 test  staff  0 Oct 21 22:00 t
    PS> new-item -Path n -Type File


        Directory: /Users/test


    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    ------         10/21/16  10:01 PM              0 n


    PS> ls -la n
    -rwxr--r--  1 test  staff  0 Oct 21 22:01 n
    PS> umask 0000
    PS> umask
    0022
    PS> exit
    $ umask 0000
    $ umask
    0000
    $ powershell
    PowerShell
    Copyright (C) 2016 Microsoft Corporation. All rights reserved.

    PS> umask
    0000
    PS> touch t2
    PS> ls -la t2
    -rw-rw-rw-  1 test  staff  0 Oct 21 22:02 t2
    PS> new-item n2


        Directory: /Users/test


    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    ------         10/21/16  10:02 PM              0 n2


    PS> ls -la n2
    -rwxrw-rw-  1 test  staff  0 Oct 21 22:02 n2
    PS> umask 0022
    PS> umask
    0000
    PS> exit
    $ umask
    0000
    $ umask 0022
    $ umask
    0022

**Comment by jeffbi** [comment]
This appears to be fixed by .NET Core 2.0. The current set of permission bits seems to be 666 (checked with umask set to 000).

**Comment by SteveL-MSFT** [comment]
Thanks @jeffbi
