### ISSUE TITLE
Word Wrap in ISE

### ISSUE THREAD

**Issue by bspach** [PowerShell/PowerShell#2483]
IMO, a glaring omission from ISE has always been basic line/word wrap functionality.  Notepad has it, can we get this in ISE, as well?

**Comment by joeyaiello** [comment]
Unfortunately, the ISE is not a part of this GitHub project. Feel free to file a suggestion on the UserVoice forum for the ISE: https://windowsserver.uservoice.com/forums/301869-powershell/category/148050-ise-and-tooling

**Comment by pcgeek86** [comment]
@bspach I rarely write code that goes off the right edge. One thing you can do to improve your code style, is to use PowerShell Splatting.

https://www.youtube.com/watch?v=CkbSFXjTLOA

**Comment by bspach** [comment]
I use splatting all the time; that does not mean other people do!  Here's a screenshot from a Microsoft Ignite 2016 session I'm watching right now... even Microsoft PPM's don't use it! :)

![2016-10-16_09-29-07](https://cloud.githubusercontent.com/assets/4923618/19418967/b0ba6e40-9383-11e6-8a24-c8bee3eadf1e.png)

**Comment by pcgeek86** [comment]
@bspach Hahaha, doesn't surprise me.
