### ISSUE TITLE
Should have a [CHAR]$ProgressPreference to allow users to specify the character to use in the progress bar!

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2488]
## Environment data

``` powershell
> $PSVersionTable

```

**Comment by oising** [comment]
Should have customizable progress bars ;)

**Comment by lzybkr** [comment]
How about a parameter to `Write-Progress` instead?

You could always use `$PSDefaultParameterValues` as an alternative to a preference variable.

**Comment by ThomasNieto** [comment]
Is this something that should be added to `PSStyle` or is it something that doesn't need to happen with the new `Minimal` progress view?
