### ISSUE TITLE
Register-ArgumentCompleter

### ISSUE THREAD

**Issue by thinkbeforecoding** [PowerShell/PowerShell#2491]
Out of curiosity,
was the Register-ArgumentCompleter inspired by PSCompletion (created in 2013 to provide dynamic completion on PS3.0 and early 4.0)  ?

https://github.com/thinkbeforecoding/pscompletion

The name cmdlet name, is astonishingly close from Register-ParameterCompleter, and the parameter -ParameterName has the same name as in PSCompletion, whereas the cmdlet name would suggest to use -ArgumentName...

The implementation is quite different since it uses C# cmdlets. Still, I'd appreciate to know if it was an inspirational source for this part of PowerShell.

**Comment by lzybkr** [comment]
I don't recall ever seeing PSCompletion, so I don't think so.

Register-ArgumentCompleter comes from `TabExpansionPlusPlus`, it looks like I came up with that cmdlet in [Nov 2012](https://github.com/lzybkr/TabExpansionPlusPlus/commit/c245db8d5f9c9aa20f3c4dc38092e857de4ae4ff)
