### ISSUE TITLE
Powershell with WSL basic console issues

### ISSUE THREAD

**Issue by lypanov** [PowerShell/PowerShell#2496]
Steps to reproduce
------------------

Start up WSL (1607).
Fire up Powershell inside WSL (running self built master as of October 17th / or powershell_6.0.0-alpha.10-1ubuntu1.14.04.1_amd64.deb).
Press enter key 9 times.

Expected behavior
-----------------

Shouldn't wrap to top of window.

Actual behavior
---------------

Wraps back to top of window rather than using all available space.

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.10
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1```

**Comment by MaximoTrinidad** [comment]
@lypanov. This is a known issue that has been around for time in GitHub in both PowerShell and Bash:
"PowerShell in Windows BASH display issues when typing cmdlets #980"

Also, check for workaround solution to make it work:  [http://www.maxtblog.com/2016/10/running-powershell-in-windows-10-bash-workaround/] 

👍
Max

**Comment by iSazonov** [comment]
@MaximoTrinidad  Please fix link on issue 980 (on 1829 ?). And thanks for workaround!

**Comment by andschwa** [comment]
Closing duplicate issue.
