### ISSUE TITLE
Get Uptime

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2497]
The feature request is on UserVoice [Add a Get-Uptime cmdlet](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11105001-add-a-get-uptime-cmdlet)

Incredibly that we don't have an easy way on Windows to get Uptime!

I would like to discuss this.

1.
There's a workaround is suggested:

``` powershell
function Get-Uptime { 
 [timespan]::FromSeconds([double][System.Diagnostics.Stopwatch]::GetTimestamp() / [double][System.Diagnostics.Stopwatch]::Frequency) 
} 
```

It's not working remotely.
It's working on non-Windows.

2.
Current Powershell versions have Get-ComputerInfo cmdlet that also returns OsUptime.
Problem is that Get-ComputerInfo  is slow and return a lot of unnecessary information.

It's not working remotely.
It seems it is not ported.

3.
And the last way is to use System.Environment.
It would be cool to have **[Environment]::Uptime**

Is there a way to add [Environment]::Uptime in Powershell  without requesting .Net developers?
It does not work remotely, but looks wonderful.

(We can not use [Environment]::TickCount to calculate Uptime because it is reset every 29 days.
Amazingly there is no [Environment]::TickCount64. 😕)

**Comment by oising** [comment]
```
function get-uptime {
    (get-date) - [Management.ManagementDateTimeConverter]::ToDateTime((gwmi `
        win32_operatingsystem).LastBootUpTime)
}
```

**Comment by jdhitsolutions** [comment]
For Windows systems this is pretty easy as @oising  suggests. Even easier when using Get-Ciminstance because the timestamps are automatically converted. The challenge I think is that non-Windows systems don't any may not have the same WMI classes.

**Comment by jdhitsolutions** [comment]
I don't have a Linux instance running now to check but another technique I used to use was to get the date of the swapfile and use that to calculate when the computer last booted. Wonder if we could do something similar with Linux and MacOS.

**Comment by rkeithhill** [comment]
On Linux you can get the uptime info from `cat /proc/uptime`.   "The first number is the total number of seconds the system has been up."  https://en.wikipedia.org/wiki/Uptime

**Comment by oising** [comment]
Yep, or even just use the gnu command `uptime`, `w` and it's also visible with `top`.

**Comment by iSazonov** [comment]
Thanks for comments guys!

One of the main goals of the Open Powershell project is portable code. This eliminates the use of WMI. Above I just provide portable examples.

I really like the simplicity of Linux to get Uptime by means of `/proc/uptime` or `uptime`. 
Now Powershell and bash are often compared. So It would be a good suggestion to make **`uptime`** as an alias in Powershell.

**Comment by iSazonov** [comment]
Related #2277
