### ISSUE TITLE
Windows MSI link still downloading version powershell-6.0.0-alpha.10 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2500]
![downloadprevversion_2016-10-18_14-59-32](https://cloud.githubusercontent.com/assets/19892435/19492189/b1ef45c6-9543-11e6-8055-cd0a79fd81af.jpg)

Steps to reproduce
------------------
Click on either of the "Get PowerShell" - Download "MSI" Platform links: "Windows 10.." or "Windows 8.1..".

Expected behavior
-----------------
To download PowerShell-6.0.0-alpha.11-*.msi

Actual behavior
---------------
It will download previous version: PowerShell-6.0.0-alpha.11-*.msi

Workaround: Go to the PowerShell Release page:
[https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.11]

Environment data
----------------
Windows 10 Pro Insider Preview Build 14946

**Comment by mirichmo** [comment]
Fixed by #2498
You caught the brief window of time where they were out of sync.
