### ISSUE TITLE
Instructions to build Powershell 6 for RHEL 6.0

### ISSUE THREAD

**Issue by alpeshvaghela123** [PowerShell/PowerShell#2508]
I will like to know steps/instructions on how to build Powershell 6 for RHEL 6.0 from source.

Regards,
Alpesh

**Comment by andschwa** [comment]
[Here you go](https://github.com/PowerShell/PowerShell/blob/master/docs/building/linux.md#build-manually). Note that the distribution you're asking for is not supported by us, nor by .NET Core (our language), so you'll have to fudge a lot.
