### ISSUE TITLE
Docker container image for Alpha 11 not available on Docker Hub

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2509]
A couple of days ago, the newest version of the PowerShell Core (Alpha 11) was released on GitHub. Unfortunately, the Docker container image, hosted on the Docker Hub, under the `microsoft/powershell` repository, has not been updated. In the screenshot below, you'll notice that the newest PowerShell Docker container image is Alpha 10, not Alpha 11.

![image](https://cloud.githubusercontent.com/assets/466713/19537733/4a96b640-960e-11e6-80c4-08bc407af703.png)

Furthermore, the Docker Hub shows that the latest `microsoft/powershell` container image was built 8 days ago, which is six days prior to the GitHub release of PowerShell Core Alpha 11.

![image](https://cloud.githubusercontent.com/assets/466713/19537758/62b19f42-960e-11e6-9492-08e0d476b23c.png)

Please make sure that the newest Docker container image is available for each public release of PowerShell Core going forward. @andschwa 

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by andschwa** [comment]
[Building now](https://hub.docker.com/r/microsoft/powershell/builds/). Just needed to be triggered with a push to the `docker` branch (@daxian-dbw my bad, this isn't in the release docs).

**Comment by pcgeek86** [comment]
Great, thanks Andy
