### ISSUE TITLE
Test script 'PowerShellGet.Tests.ps1' fails in OS X CI

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#2510]
The following failure happens in OS X CIs for several time in different RPs.

```
Describing XmlCommand DRT basic functionality Tests
 [!] Import with CliXml directive should work 56ms
 [!] Import with Rehydration should work 6ms
 [-] Error occurred in test script '/Users/travis/build/PowerShell/PowerShell/test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1' 2.76s
  The specified Uri 'https://dtlgalleryint.cloudapp.net/' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
  at ThrowError, /Users/travis/build/PowerShell/PowerShell/src/powershell-unix/bin/Linux/netcoreapp1.0/osx.10.11-x64/Modules/PowerShellGet/PSModule.psm1: line 14627
```

**Comment by vors** [comment]
It boils down to this error

```
PS /Users/vors/dev/PowerShell> $handler = New-Object System.Net.Http.HttpClientHandler                                                       New-Object : Exception calling ".ctor" with "0" argument(s): "The type initializer for 'System.Net.Http.CurlHandler' threw an exception."    
At line:1 char:12
+ $handler = New-Object System.Net.Http.HttpClientHandler
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```

Which is internally

```
PS /Users/vors/dev/PowerShell> $error[0].Exception.InnerException.InnerException.InnerException.InnerException.InnerException.StackTrace        at Interop.CryptoInitializer.EnsureOpenSslInitialized()                                                                                   
   at Interop.CryptoInitializer..cctor()
PS /Users/vors/dev/PowerShell> $error[0].Exception.InnerException.InnerException.InnerException.InnerException.InnerException                
Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)

```

I don't see it on alpha.11 release, but I see it on the build from master.

@andschwa any ideas?

**Comment by vors** [comment]
I opened a corefx issue https://github.com/dotnet/corefx/issues/12983

**Comment by andschwa** [comment]
Sure looks like the crypto library isn't getting patched. .NET may have updated the rpath finally but the 1.0.0 expected (incorrectly) for OpenSSL to be symlinked into the system, which our build module is supposed to fix.

**Comment by vors** [comment]
I did more experiments, looks like our patching aproach stop working after upgrade to "4.3.0-preview1-24530-04" for "System.Net.Http"

**Comment by andschwa** [comment]
I definitely believe that!

**Comment by andschwa** [comment]
I would love to know when .NET will stop shipping libraries with a disallowed setup requirement.

**Comment by vors** [comment]
Looks like they updated instructions http://stackoverflow.com/questions/38670295/brew-refusing-to-link-openssl

Now it's 

```
brew update
brew install openssl
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

That doesn't look more promising

**Comment by andschwa** [comment]
Yeah that's asking users to manually create a security hole that the home brew team purposefully closed.

**Comment by andschwa** [comment]
Our solution is to fix .NET's libraries because they are legitimately broken.

**Comment by vors** [comment]
But it stopped to work now. So should we consider roll back to 4.1.0?

**Comment by andschwa** [comment]
We should investigate why the patch is failing.

**Comment by vors** [comment]
Umh. I don't know how patching work. Want to take this other?

**Comment by vors** [comment]
Verified that it works with un-secure symlink.

**Comment by andschwa** [comment]
The patch is the application of the install_name_tool. It's just updating the rpath of the libraries to search for OpenSSL in the correct location.

**Comment by daxian-dbw** [comment]
Would this be a blocker for our alpha.12 release?
The discussion in [#12983](https://github.com/dotnet/corefx/issues/12983) suggests using symlink, so shall we update our documentation?

**Comment by vors** [comment]
The name of dylib changed from `System.Security.Cryptography.Native.dylib` to `System.Security.Cryptography.Native.OpenSsl.dylib`. There is also `System.Security.Cryptography.Native.Apple.dylib`.
Working on the fix.
