### ISSUE TITLE
Request Make #Requires script metalanguage conditional

### ISSUE THREAD

**Issue by Sarafian** [PowerShell/PowerShell#2516]
This is regarding the [about_Requires](https://technet.microsoft.com/en-us/library/hh847765.aspx).
Currently if any of them appear anywhere in the script, then the condition is applied. 

For example both following scripts will raised the error 

```powershell
#Requires -RunAsAdministrator
if($false)
{
   Write-Host "Only this would require admin rights"
}
```

and

```powershell
if($false)
{
   #Requires -RunAsAdministrator
   Write-Host "Only this would require admin rights"
}
```

I understand that the above example is a bit dummy in terms of usefulness but this is what I really have in mind.
I'm building scripts that have the potential to execute a certain logic locally or remotely. When the execution is local I want to block non-administrators like the `#Requires -RunAsAdministrator` does. But when its a remote execution, I would like my script to execute and the remote execution to raise an error same as with the `#Requires -RunAsAdministrator`. And I would like the same reasoning to be applied for the rest of the `#Requires` statements in [about_Requires](https://technet.microsoft.com/en-us/library/hh847765.aspx).

Here is a small example

```powershell
$block={
    #Requires -RunAsAdministrator
   Write-Host "You are an administrator"
}

# Prevent local execution
Invoke-Command -ScriptBlock $block

# Prevent remote execution in the remote session.
Invoke-Command -ComputerName MECULAB12201 -ScriptBlock $block
```

Because of the issue described above this is not possible and the entire script's execution is rejected.

I know about validating with .net language but it would be nice if PowerShell offered native support for this. Example code

```powershell 
([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
```

My current alternative for local execution is to isolate the `#Requires -RunAsAdministrator` in a script e.g. `Test-Administrator.ps1` and conditionally execute it from the main script. It's a bit like using a cmdlet with C# style implementation but I prefer to use the native concepts when possible.

**Comment by iSazonov** [comment]
@Sarafian Thanks for feature request.

I think may be better define new _global_ const as:
```powershell
$isRunAsAdministrator = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
```
(Today we already have similar variables: $isWindows, $PID, $HOME...)

**Comment by Sarafian** [comment]
@iSazonov  those global consts are nice and yes the `$isRunAsAdministrator` would be a very useful one. But I still think you need to consistency in the experience that Powershell offers with the `#Requires` meta language. I find them great but I do not like how they are identified in the script's body. 

I would prefer them to get executed like any other command. That means even as part of a script block anywhere the script block executes.

**Comment by lzybkr** [comment]
This proposal is incompatible with the current design of `#requires` - processing of `#requires` happens at parse time before any of the script executes.

If we changed this behavior, I can imagine scripts doing weird things trying to execute in ways they weren't designed for.

**Comment by Sarafian** [comment]
@lzybkr I was expecting something like that. But still I have a question.

If I execute a script block, shouldn't the parser do the same thing at the beginning? I would expect that a script block and a script file are loaded somehow similarly into the memory. Scripts are verified for signing but once that is ok, parsing starts. Shouldn't that be applies for the script block, especially when executed remotely? If that was possible, a `#requires` in the script or script block beginning should do the trick. 
Currently the parser is not even checking for only the biggining. Anywhere in the body of the script, the `#requires` gets captured

**Comment by lzybkr** [comment]
Most script blocks come from files and `#requires` is enforced at the file level. Checking at the script block level would be expensive (e.g. it would slow down `foreach-object` or `where-object` unnecessarily.

That said, it could be useful remotely, but I would not encourage the use of `#requires` in that way if we supported it for remoting, instead I would encourage the use of `Invoke-Command -FilePath`.

**Comment by Sarafian** [comment]
Didn't know `Invoke-Command -FilePath was possible. Hadn't noticed. Thanks for the tip.
I understand the reasoning. Is there anyway to force PowerShell to verify and throw the same error message without code duplication?

**Comment by lzybkr** [comment]
I wouldn't be surprised if `Invoke-Command -FilePath` did not report any errors from `#requires` today (I didn't test it), but in my opinion, that's the scenario that should enable what you're asking for.

The api to validate script requirements is internal and expects a file, so duplicating that experience would require (pun not intended) a new api.

**Comment by Sarafian** [comment]
Ok. From my perspectieve the subject is exhausted. I have not other arguments to support my idea :). Thank you all.
