### ISSUE TITLE
PSDesiredStateConfiguration.psm1 has call to `sort` which is a native linux command and not an alias

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2520]
In PSDSC.psm1 (from nuget package 1.0.0-alpha01), on line 1873, there is a call to `sort` which should be `sort-object`. `sort` is not an alias on unix, it's a coreutil command.

``` powershell
$moduleInfos = Get-Module -ListAvailable -FullyQualifiedName $moduleToImport | sort -Property Version -Descending
```

Not sure how it manages to work as is.
@johnkord @nitinbps

**Comment by joeyaiello** [comment]
@vors: I'm refiling that bug where the code is actually housed.

**Comment by vors** [comment]
Since we are currently consuming nuget package with psm1 file and owning it, I think it would be better to leave it open until it's fixed.

**Comment by ThomasNieto** [comment]
@StevenBucher98 this issue can be closed as the issue reported has been resolved.

https://github.com/PowerShell/PSDesiredStateConfiguration/blob/b711f75b4639d892f96291b7dbad790f392fbe56/src/PSDesiredStateConfiguration/PSDesiredStateConfiguration.psm1#L1822
