### ISSUE TITLE
Download link for Windows 10 .msi incorrect

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2522]
Download link appears to be incorrect.

https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.11/PowerShell_6.0.0.10-alpha.11-win10-x64.msi

Should it be...?

https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.11/PowerShell_6.0.0.11-alpha.11-win10-x64.msi

**Comment by MaximoTrinidad** [comment]
Duplicate issue that was supposed to be corrected:
https://github.com/PowerShell/PowerShell/issues/2500

Now this is confirmed: the link is missing!!
What happened?
:)

![missinglink_2016-10-21_23-21-42](https://cloud.githubusercontent.com/assets/19892435/19616590/429c1d8a-97e5-11e6-84d5-a6f8127a3732.jpg)

**Comment by vors** [comment]
Thank you for catching this!

**Comment by mirichmo** [comment]
Fixed via #2523
