### ISSUE TITLE
Enhancement Request: Get-Verb -Group parameter

### ISSUE THREAD

**Issue by bcdady** [PowerShell/PowerShell#2527]
The Get-Verb cmdlet should include a -Group Parameter, or another means of filtering the list of approved verbs.
## Steps to reproduce

Per [Windows PowerShell 5.0 documentation](https://technet.microsoft.com/en-us/library/hh852690.aspx), `Get-Verb` Syntax is:
`Get-Verb [[-Verb] <string[]>] [<CommonParameters>]`
## Expected behavior

`Get-Verb -Group <Common|Communications|Data|Diagnostic|Lifecycle|Other|Security>`
Specifying a -Group Parameter would filter to show only the approved verbs in that Group.
Alternatively, Get-Verb could support a `-Filter`, or `-Include` and `-Exclude` parameter(s)
## Actual behavior

`Get-Verb` enumerates the full list of approved verbs and their corresponding verb group, but does not provide a convenient way to filter and more easily view approved verbs
## Environment data

Symptom appears consistent from PSVersions 3.0 - 5.0

**Comment by iSazonov** [comment]
@bcdady Thanks for the enhancement request.
Today `(get-verb).count` return 98. Do you really think that this _short_ list should be filtered? Could you give practical examples?
I believe that this list is very short and stable. And that I would really expect from this cmdlet, this is a description of the verbs and groups.

**Comment by jpsnover** [comment]
I like it!

**Comment by iSazonov** [comment]
@jpsnover What? '-Group' parameter?

**Comment by kilasuit** [comment]
Not sure there is much need for this as its simple enough to just pipe to Where-Object in my opinion.

**Comment by bcdady** [comment]
@kilasuit Yes, except that with `| where {}`, the admin / IT Pro needs to first know that Verbs are grouped, the names of the Groups they want to view verbs from. Strictly speaking, they could first invoke `get-verb | select Group -Unique`, and then try each of those Group names through `| where {$_.Group -eq $group } | Out-Host -Paging`. But why not make all that easier (especially newbies learning the ropes, not yet familiar with approved verbs. If the same results were possible via a parameter of the cmdlet, then an IT Pro can more simply tab through the available Groups, select the best option for their use case, and enumerate the list approved Verbs in that Group.

**Comment by iSazonov** [comment]
I do think that there isn't a cmdlet that is used less frequently:
[Get-Verb](https://www.google.ru/#newwindow=1&q=filetype:ps1+%22get-verb%22)

**Comment by bcdady** [comment]
@iSazonov Perhaps after we make it more useful, it will be used more frequently.

**Comment by iSazonov** [comment]
Give up! 😊 

What do you say to add a brief description?
```powershell
PS > Get-Verb

Verb        Group      Description
----        -----      -----------
Add         Common     <Add description>
Clear       Common     <Clear description>
```

**Comment by lzybkr** [comment]
There is little point in speculating on the usage.

I don't really see any downside to this proposal, it is a simple change to add and I can't see the any potential UX problems in the future, e.g. the cmdlet ending up with too many parameters.
