### ISSUE TITLE
Support PowerShell package on Server 2008 R2

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/PowerShell#2529]
Package doesn't work on Server 2008 R2. I was able to run powershell.exe after adding the following files to the package:
API-MS-Win-Eventing-Provider-L1-1-0.dll 
api-ms-win-core-version-l1-1-0.dll
api-ms-win-core-registry-l1-1-0.dll
api-ms-win-core-console-l2-1-0.dll
api-ms-win-core-shlwapi-legacy-l1-1-0.dll

**Comment by mirichmo** [comment]
Are you installing the Windows 8.1 package on Windows 7? If so, that is not a supported scenario.

I've run the Windows 7 MSI on a fully patched Win 7 SP1 system without issue. You can build it using `Start-PSBuild` and `Start-PSPackage` by specifying the `Win7-x64` `Runtime`.

**Comment by joeyaiello** [comment]
So we *did* support this (and we plan to continue to support it), but it's blocked on #3747. Given that that's basically the same issue, closing this one as a duplicate.
