### ISSUE TITLE
Ability to create the package based on features.

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/PowerShell#2530]
Size of PowerShell package is ~92 MB. It would be nice to be able to create the package based on the features in PowerShell to reduce the size of the package. This is extremely helpful in scenarios where large number of packages need to be distributed on low bandwidth environment where only limited set of PowerShell functionality is being used.

**Comment by iSazonov** [comment]
Today package size is not more 40MB ([Releases](https://github.com/PowerShell/PowerShell/releases))

And the package contains only the Powershell core. I cannot imagine that can be removed from it.

**Comment by daxian-dbw** [comment]
Unsign myself for now as we are asked to focus on `beta1` issues.

**Comment by iSazonov** [comment]
With framework based model we can reduce PowerShell Core package size.

**Comment by iSazonov** [comment]
We could reduce size by .Net IL Lynker #5881 - now it is in .Net Core 3.0.
