### ISSUE TITLE
SSH based remoting broken with recent Win32-OpenSSH change

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2531]
SSH based remoting no longer works when connecting to a Windows machine with Win32-OpenSSH installed.  The reason is that PowerShell expects a console to be available when hosted in a process and Win32-OpenSSH now creates subsystem processes without a console.

This should be Ok for remoting because PowerShell in server mode has no need for a console.  So the fix should be in PowerShell where it can fail gracefully when a console is not available.

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/2531

Looks like a dupe
