### ISSUE TITLE
Test-Connection Missing

### ISSUE THREAD

**Issue by tibmeister** [PowerShell/PowerShell#2537]
Seems that the Test-Connection camdlet is missing. Is this going to be implemented in the future?  If not I do have a wrapper I made to handle this.

**Comment by mirichmo** [comment]
Test-Connection is present in the Windows build of the 6.0.0-alpha.11 release. Please file an issue if you encounter a bug when using it.

If you are asking about Test-Connection for non-Windows platforms, it has not yet been ported and is an open task for someone to pick up.

**Comment by tibmeister** [comment]
Definitely thinking other platforms.  I will see if I can work on something for this.
