### ISSUE TITLE
Get-Service Name parameter allows Null value

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PowerShell#2540]
Reported via uservoice @ https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13741089-get-service-name-parameter-allows-null-value
## Steps to reproduce

Get-Service -Name $VariableThatResultsInNullorEmptyValue
or
$VariableThatResultsInNullorEmptyValue | Get-Service
## Expected behavior

ParameterBinding exception saying the value is null or empty
## Actual behavior

Returns all service
## Environment data

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
I copy here from UserVoice:
>Roman Kuzmin  commented  ·  May 17, 2016 07:16  ·  Flag as inappropriate    

In theory, here is a possible **unwanted scenario**:

$service = Get-ServiceToStop ... 
Get-Service $service | Stop-Service

If Get-ServiceToStop is expected to get something but returns nothing then all services are going to be stopped.

**Comment by HemantMahawar** [comment]
#2542 fixed it
