### ISSUE TITLE
Package Manager Package Naming Guidance?

### ISSUE THREAD

**Issue by ferventcoder** [PowerShell/PowerShell#2548]
Howdy @andschwa @vors!

We are looking for guidance on what to name the Chocolatey package for the core version of PowerShell?

We typically try to match the id with other package managers to allow for things like configuration management tools to simply be able to do something like:

``` puppet
package {'powershell-core':
  ensure => latest,
}
```

And it works on all platforms. However we currently use `powershell` as the package id for the CLR version of PowerShell.

Are you looking at using something like `powershell-core` for the .NET Core version or are you set on `powershell` as the name of the package?

**Comment by vors** [comment]
I think we settled on `powershell` and different [**editions**](https://msdn.microsoft.com/en-us/powershell/gallery/psget/script/scriptwithpseditionsupport) to distinguish functionality. I think it would make sense to use `powershell-core`, then `-core` part would represent edition.  @joeyaiello @HemantMahawar @SteveL-MSFT  please correct me, if I'm misrepresenting anything.

**Comment by ferventcoder** [comment]
Right now it appears just `powershell` is the id - https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md

**Comment by ferventcoder** [comment]
No worries if `powershell-core` is not an option for other platforms. It makes the most sense on Windows. I think @darwinjs is going to maintain that one. He maintains the Microsoft OpenSSH package now.

**Comment by ferventcoder** [comment]
However, it may not be a bad idea to set up the Chocolatey package as another item in the github releases, even if you don't push the package up to the community repository (https://chocolatey.org/packages).

**Comment by DarwinJS** [comment]
It's curious that "Desktop Edition" is for servers?

Had you guys considered something more specifically differentiating from "core" - maybe something like "Full Edition" or "Framework Edition" (to sync up with the .NET edition names) ?

**Comment by SteveL-MSFT** [comment]
@DarwinJS We had wanted to call it something other than "Desktop", but by the time we caught it, we had already shipped the PSEdition so changing it was a breaking change.  We could potentially fix this for 6.0 as it's a major version. cc @joeyaiello

**Comment by SteveL-MSFT** [comment]
powershell-core makes sense
