### ISSUE TITLE
Powershell 4/5 and remote workflow Restart-Computer over an SSL connection

### ISSUE THREAD

**Issue by bozho** [PowerShell/PowerShell#2551]
## Steps to reproduce

This bug occurs on both PS 4 and 5.0 on Windows 2012R2 remote workflow target machine (non-domain). I'm aware these are not the latest release versions of PS, but we can't really afford to run 6.0 alpha in production :-)

Please use the attached scripts to reproduce the bug. You will need a Win10 client machine to generate appropriate self-signed SSL certificates.
1. Execute step.01.ps1 on the "client" Win10 machine. It will create two self-signed SSL certificates: one server and one client. It will create server.pfx, server.cer and client.cer in your HOME directory.
2. Copy server.pfx and client.cer to the Win2012R2 server and import them. Import server.pfx to CERT:\LocalMachine\My. Import client.cer to CERT:\LocalMachine\Root (Trusted Root CA).
3. Copy step.02.ps1 to the target server machine and execute it. The script will configure an HTTPS WinRM listenner and remove the HTTP listener. It will also register the client certificate against a specified local server account.
4. Dot-source step.03.ps1 on the client machine in a PS session and prepare these two variables:

$cert = gi CERT:\CurrentUser\My<your certificate hash>
$cred = Get-Credential -Message "Please enter server credentials"

step.03.ps1 defines two workflows that will be run on the remote server: TestDir and TestRestart. TestDir simply performs "Get-ChildItems C:\" on the target machine, while TestRestart attempts a restart and waits for the target machine to reboot.

Run them using the -PSParameterCollection parameter:

TestDir -PSParameterCollection $p
or
TestRestart -PSParameterCollection $p

There are 3 scenarios to test:

TestRestart fails with "access denied" error and an audit failure in the Windows Security event log on the target machine:
**$p = @(@{PSComputerName = <your server hostname>}, @{PSComputerName = "*"; Verbose = $true; PSUseSSL = $true; PSCertificateThumbprint = $cert.Thumbprint } )**

TestRestart restarts the machine, but waits indefinitely until you run 'winrm qc' on the target machine after the reboot to re-enable the HTTP listener
**$p = @(@{PSComputerName = <your server hostname>; PSCredential = $cred}, @{PSComputerName = "*"; Verbose = $true; PSUseSSL = $true } )**

TestRestart works if there is an HTTP listener on the target server and associated firewall rules are enabled
**$p = @(@{PSComputerName = <your server hostname>; PSCredential = $cred}, @{PSComputerName = "*"; Verbose = $true } )**

TestDir works fine in all three cases.
## Expected behavior

TestRestart should restart the target machine, wait for it to reboot and exit.
## Actual behavior

When using a registered client SSL certificate thumbprint for authentication, TestRestart fails with 'access denied' error and there is a security audit failure event logged in the Windows Security event log.

When using PSCredential over SSL, TestRestart restarts the target machine, but waits indefinitely for the reboot confimration until 'winrm qc' is run on the target machine after it has rebooted.
## Environment data

``` powershell
> $PSVersionTable

```

Name                           Value

---

PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

Name                           Value

---

PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

[steps.zip](https://github.com/PowerShell/PowerShell/files/557000/steps.zip)

**Comment by SteveL-MSFT** [comment]
Please open this on Uservoice.  Workflow is not supported on PowerShell Core

**Comment by bozho** [comment]
Can I link to this issue, since it doesn't seem like I can upload files to Uservoice?

**Comment by SteveL-MSFT** [comment]
@bozho I don't see any problem with linking to this issue
