### ISSUE TITLE
Docker Instructions show not found

### ISSUE THREAD

**Issue by MasashiTeruya** [PowerShell/PowerShell#2552]
This is not a bug but document feedback.
Docker "Instructions" link in README is broken and shows not found (HTTP 404).
URL is [https://hub.docker.com/r/microsoft/powershell/docker](https://hub.docker.com/r/microsoft/powershell/docker)

**Comment by vors** [comment]
It's the same for all relative links everywhere. Docker-hub just copies `README.md` and doesn't copy the rest of documentation. The link works fine on GitHub.
