### ISSUE TITLE
PowerShell doesn't kill native child processes when StopProcessing is called on pipeline

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2561]
The native command processor doesn't correctly kill child processes (only the parent) when Stop()/BeginStop() is called:

build createchildprocess from test\tools\CreateChildProcess

``` powershell
$cmd = "pathto\createchildprocess.exe"
$ps = [powershell]::create().Addcommand($cmd)
$ps.AddParameter(2) # this creates two children
$ps.BeginInvoke()
# verify that 3 instances of createchildprocess has started
$ps.Stop()
```

Expected:
parent and child process to be killed

Actual:
parent is killed and children are orphaned (they will eventually timeout and exit)

Repros on PS5.1, PSCore 6.0 Windows/Linux

``` powershell
Name                           Value
----                           -----
PSVersion                      5.1.14931.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14931.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
@joeyaiello see if this impacts our partners

**Comment by iSazonov** [comment]
Related [test ](https://github.com/SteveL-MSFT/PowerShell/blob/52e3916fab229378e118ce8fb32d8d01364309d6/test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1#L42) "Should kill native process tree" should be enabled after the fix.
Also we could replace "while (((Get-Date) - $startTime).TotalSeconds -lt 5)" with Wait-Process in the test.
