### ISSUE TITLE
Get-Help about_Pester

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2565]
## Steps to reproduce

Use the command `Get-Help about_Pester`
## Expected behavior

Information about using Pester should appear.
## Actual behavior

Output appear to list two (2) "about_Pester" topics, but no other information appears.

PS /home/pwatson/Downloads> get-help about_Pester                                              

Name                              Category  Module                    Synopsis                

---

about_Pester                      HelpFile                            Pester is a BDD based...
about_Pester                      HelpFile                            Pester is a BDD based...
## Environment data

Ubuntu 16.04

PS /home/pwatson/Downloads> uname -a  
Linux pwatson-VirtualBox 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

PS /home/pwatson/Downloads> $PSVersionTable                                                    

Name                           Value

---

PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.11
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lzybkr** [comment]
@adityapatwardhan - I thought we fixed this.

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShell-Docs#770

**Comment by Hicsy** [comment]
Don't know if this helps:
This duping also occurs on Windows in current PS
```Name                           Value
----                           -----
PSVersion                      5.1.15048.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15048.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1```

current dupes:
```
about_BeforeEach_AfterEach        HelpFile                            performed at the beginning and end of every It block. This can eliminate duplication of code
about_Mocking                     HelpFile                            Pester provides a set of Mocking functions making it easy to fake dependencies
about_Pester                      HelpFile                            Pester is a BDD based test runner for PowerShell.
about_should                      HelpFile                            Provides assertion convenience methods for comparing objects and throwing
about_TestDrive                   HelpFile                            A PSDrive for file activity limited to the scope of a singe Describe or
about_Scheduled_Jobs              HelpFile                            Describes scheduled jobs and explains how to use and manage
about_Scheduled_Jobs_Advanced     HelpFile                            Explains advanced scheduled job topics, including the file structure
about_Scheduled_Jobs_Basics       HelpFile                            Explains how to create and manage scheduled jobs.
about_Scheduled_Jobs_Troublesh... HelpFile                            Explains how to resolve problems with scheduled jobs
about_ActivityCommonParameters    HelpFile                            Describes the parameters that Windows PowerShell
about_Checkpoint-Workflow         HelpFile                            Describes the Checkpoint-Workflow activity, which
about_ForEach-Parallel            HelpFile                            Describes the ForEach -Parallel language construct in
about_InlineScript                HelpFile                            Describes the InlineScript activity, which runs Windows
about_Parallel                    HelpFile                            Describes the Parallel keyword, which runs the
about_Sequence                    HelpFile                            Describes the Sequence keyword, which runs selected
about_Suspend-Workflow            HelpFile                            Describes the Suspend-Workflow activity, which suspends
about_WorkflowCommonParameters    HelpFile                            This topic describes the parameters that are valid on all Windows
about_Workflows                   HelpFile                            Provides a brief introduction to the Windows
```

**Comment by joeyaiello** [comment]
#2653 says that about_* topics are missing.

This issue here is that we're showing duplicates when there's only one copy in $PSHome.

@HemantMahawar is adding a lower-priority issue now to enable disambiguation when duplicates exist (and to expose the help location name and module version to ease disambiguation).
