### ISSUE TITLE
Use the type of a variable for tab expansion

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2567]
It would be useful if 
```powershell
[Diagnostics.Process[]] $p = Get-Process
$p | % Prio<tab>
```
would tab complete in the same way as
```powershell
Get-Process | % Prio<tab>
```
Even nicer would be if 
```powershell
$p = Get-Process
$p | % Prio<tab>
```
worked too. (Maybe getting the ArgumentTypeConverterAttribute from the OutputType?)

**Comment by lzybkr** [comment]
Indeed, it is useful. It works too, at least some of the time, e.g. in your example.

It's a bit hacky/simple minded in how it works, so I'm certain there are scenarios where it doesn't work. Start with this [method](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/ast.cs#L284) and find it's implementations and references.

**Comment by powercode** [comment]
@lzybkr It works when writing a script in the ISE, but not on the command line.

At the end of VariableExpressionAst::GetInferredType, the closest assignment is looked up.
But on the command line, we don't have that context.

Is it to expensive to actually look at the Value of the variable and determine the type from it, or from the first element if it's a collection type?

**Comment by powercode** [comment]
https://github.com/PowerShell/PowerShell/pull/2589

**Comment by HemantMahawar** [comment]
@powercode Thanks for your onging PR.

**Comment by powercode** [comment]
@lzybkr https://github.com/powercode/PowerShell/commits/typeinference-visitor
Is this roughly what you had in mind?

**Comment by lzybkr** [comment]
I only took a very quick look, but it's definitely the direction I had in mind.

**Comment by powercode** [comment]
I have pushed a version where I have maintained logical functionality, i.e. no functional changes.

Do you want that as a separate PR, or should I merge the work to use variable values into this?

**Comment by masaeedu** [comment]
Does tab expansion call some function that may have side effects, or does it simply reflect over the structure of the data?

**Comment by powercode** [comment]
@masaeedu It is a fairly complex process, that is highly context sensitive. The *-object commands has special treatment for example, and so has hashtables in certain circumstances. You can register you own completers with Register-ArgumentCompleter, and these may very well have side effects, even if that is discouraged.
