### ISSUE TITLE
Regression caused by PR #2392, Resolve-Path -LiteralPath returns wrong output.

### ISSUE THREAD

**Issue by charub** [PowerShell/PowerShell#2570]
Steps to reproduce
------------------
Resolve-Path c:\

Expected behavior
-----------------
![image](https://cloud.githubusercontent.com/assets/18017330/19874121/1dfa9824-9f80-11e6-8a20-93d4da1a67a9.png)

Actual behavior
---------------
![image](https://cloud.githubusercontent.com/assets/18017330/19873863/ab4639c4-9f7e-11e6-8302-f1893a61816d.png)

Environment data
----------------

![image](https://cloud.githubusercontent.com/assets/18017330/19873888/c93ab39c-9f7e-11e6-957b-c3338e405cb1.png)

```

**Comment by daxian-dbw** [comment]
This issue is a Regression caused by PR #2392

**Comment by charub** [comment]
Resolved by PR #2572
