### ISSUE TITLE
Should I find Get-VpnConnection in PowerShell 6?

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#2577]
I am running v6.0.0-alpha.11. Is Get-VpnConnection part of Core? Where might it be found?

```
PS C:\Program Files\PowerShell\6.0.0.11> (Get-CimInstance Win32_OperatingSystem).Name
Microsoft Windows 10 Pro|C:\WINDOWS|\Device\Harddisk0\Partition2

PS C:\Program Files\PowerShell\6.0.0.11> Get-VpnConnection
Get-VpnConnection : The term 'Get-VpnConnection' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-VpnConnection
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-VpnConnection:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by SteveL-MSFT** [comment]
Get-VpnConnection comes from the VpnClient module which is part of Windows and not part of PowerShell Core.  VpnClient module isn't compatible with PowerShell Core currently

**Comment by Liturgist** [comment]
I would very much appreciate some reference to documentation specifying what is and is not PowerShell Core. Ok, a what is list is a must, but a what is not list would be helpful.

Should I just take the output of `Get-Command` and `Get-Help *` as the definition of PowerShell Core?

**Comment by SteveL-MSFT** [comment]
@Liturgist for now, those commands will tell you what is shipped with PowerShell Core, but there are other modules that work on Windows PowerShell and PowerShell Core that aren't part of PowerShell itself.  The VpnClient module above is part of Windows, but not part of Windows PowerShell (for example, it's not shipped as part of Windows Management Framework).
