### ISSUE TITLE
Scripts signed with an external CA aren't automatically trusted

### ISSUE THREAD

**Issue by ZakReynolds** [PowerShell/PowerShell#2582]
This could be the expected behavior, but if it is, it doesn't really make sense to me, so if someone could clarify, I'd really appreciate it. 

Basically, I'm trying to make sure that scripts signed with my company's code signing certificate are trusted on remote systems that have their execution policy set to AllSigned. From what I've seen in my tests and looking at the code, PowerShell ultimately requires that the certificate be included in the Trusted Publishers store. Below is the code that seems to confirm it:

        // Checks that a publisher is trusted by the system or is one of
        // the signed product binaries
        private bool IsTrustedPublisher(Signature signature, string file)
        {
            // Get the thumbprint of the current signature
            X509Certificate2 signerCertificate = signature.SignerCertificate;
            string thumbprint = signerCertificate.Thumbprint;

            // See if it matches any in the list of trusted publishers
            X509Store trustedPublishers = new X509Store(StoreName.TrustedPublisher, StoreLocation.CurrentUser);
            trustedPublishers.Open(OpenFlags.ReadOnly);

            foreach (X509Certificate2 trustedCertificate in trustedPublishers.Certificates)
            {
                if (String.Equals(trustedCertificate.Thumbprint, thumbprint, StringComparison.OrdinalIgnoreCase))
                    if (!IsUntrustedPublisher(signature, file)) return true;
            }

            return false;
        }

Is this the expected behavior? If so, then why shouldn't it check other certificates in the chain? What would be the purpose of purchasing a certificate if I would have to import the certificate on the target machines anyway?

**Comment by iSazonov** [comment]
Is this the expected behavior? _Yes_
why shouldn't it check other certificates in the chain? _CAPI do. (You can enable CAPI event log and see there)_
What would be the purpose of purchasing a certificate if I would have to import the certificate on the target machines anyway? _By design 😊 Do you want to make a request to the Internet each time you start the script?_
