### ISSUE TITLE
Please clarify "shortly after the Alpha release"

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#2584]
There are several things, such as remoting and JEA in the [KnownIssues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md#remoting-support) which say something like:

>  This will be enabled shortly after the Alpha release by installing an additional package.

Since we're on Alpha 11, it seems appropriate to ask what is meant by "after the Alpha release"?  Can you please clarify (in the documentation) which release we're waiting for, and how these "additional package"s will be delivered.

**Comment by SteveL-MSFT** [comment]
I'll update that doc "shortly" :)

The short version is that JEA/Linux is not in scope for 6.0.0.  We need to do a lot more thinking on this as JEA today is tightly coupled with WinRM.  This will go the RFC route.

The client side WSMan remoting on Linux/Mac is being done in this repo: https://github.com/PowerShell/psl-omi-provider.
