### ISSUE TITLE
Analysis of 'PowerShell' source code by PVS-Studio static code analyzer

### ISSUE THREAD

**Issue by VasilievSerg** [PowerShell/PowerShell#2587]
Developers of PVS-Studio C/C++/C# static analyzer present their check report of the source code of 'PowerShell' in the article, containing the review of the most suspicious code fragments they discovered.

You can read article at the official site:
http://www.viva64.com/en/b/0447/

I have provided links to GitHub for each code fragment to make viewing more comfortable. Nevertheless, a lot of fragments, detected by the analyzer weren't given in the article. That's why I would suggest trying out the analyzer and viewing other warnings besides fixing the given code fragments.

**Comment by iSazonov** [comment]
@VasilievSerg  Could you publish here the entire report?

**Comment by VasilievSerg** [comment]
@iSazonov Do you mean the report of the analyzer with all the warnings? 
I did the check about a month ago with quite an old  version (not even 6.09, the current one is 6.10)
So, I would advise generating the report once again.
