### ISSUE TITLE
Need way to interop between PSCore and PSFull on Windows

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2592]
investigate: implicit remoting sufficient or alternatively having a way for PSCore to spawn PSFull

**Comment by SteveL-MSFT** [comment]
If .Net Std 2.0 proves we can use FullCLR modules in PSCore6, we won't need this anymore.  Assigned to @adityapatwardhan to validate.  Current know limitation is that assemblies in the GAC won't be found so we may need to add some logic to search the GAC paths.

**Comment by SteveL-MSFT** [comment]
Related https://github.com/PowerShell/PowerShell/issues/3135

**Comment by joeyaiello** [comment]
I will say that even if you *could* change the port, the scenario that it supports would not be able to consume the new port...

**Comment by iSazonov** [comment]
@SteveL-MSFT Is the Issue fixed (label)?
