### ISSUE TITLE
Improve formatting of timespan

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2595]
According to conclusion of @PowerShell/powershell-committee #2517 we need to improve formatting of timespan.

Steps to reproduce
------------------

`$a=[timespan]"1:12:23:56"`
`$a`

Expected behavior
-----------------
1:12:23:56.5550000
or
1.12:23:56.5550000

Actual behavior
---------------
```
Days              : 1
Hours             : 12
Minutes           : 23
Seconds           : 56
Milliseconds      : 555
Ticks             : 1310365550000
TotalDays         : 1.51662679398148
TotalHours        : 36.3990430555556
TotalMinutes      : 2183.94258333333
TotalSeconds      : 131036.555
TotalMilliseconds : 131036555
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10240.17113
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3


Name                           Value
----                           -----
PSEdition                      Core
CLRVersion
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.12-3-g9721983ad49bcf1ba3e178131bfa1dc8f7108b79
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
```

**Comment by iSazonov** [comment]
The question is should we use the culture-sensitive output (my preference):
```powershell
$a=[timespan]"1:12:23:56" 
$a.ToString("G")
```
or culture-**in**sensitive output:
````powershell
$a.ToString("c")
```
[Related MSDN](https://msdn.microsoft.com/en-us/library/ee372286%28v=vs.110%29.aspx)

**Comment by lzybkr** [comment]
Personally, I'd like a more human friendly display:
```
1 day, 12 hours, 23 minutes, 56.000s
```

In my personal profile, I use this script in my format.ps1xml:

```powershell
$d = $_.Days; $h = $_.Hours; $m = $_.Minutes; $as = "","s"
$(if ($d) { "{0} day{1}," -f $d, $as[$d -gt 1] }
  if ($h) { "{0} hour{1}," -f $h, $as[$h -gt 1] }
  if ($m) { "{0} minute{1}," -f $m, $as[$m -gt 1] }
  "{0}.{1}s" -f $_.Seconds, $_.Milliseconds.ToString('D3')) -join " "
```

Obviously this needs some changes for localization, but I find it useful.

**Comment by RichardSiddaway** [comment]
I prefer
1 day, 12 hours, 23 minutes, 56.000s
to something like
1:12:23:56.5550000

If we're producing formatted output then make it easily readable

**Comment by iSazonov** [comment]
I like human friendly display too. 
But it seems like the localization is not easy. I haven't found anything about localization of `TimeSpan` in CoreCLR (only delimiters). For `Datetime` CoreCLR retrieves a format information from OS (`CallGetCalendarInfoEx`). For `TimeSpan` there is nothing like this.

Whether the right to make here a special procedure and localized resources? Probably every language will require not only their local resources but also a separate procedure.

The .Net creators have come to the compromise on TimeSpan format to avoid the difficulties.
Maybe we should do the same and use standart `ToString`?

**Comment by thezim** [comment]
@iSazonov is there an RFC for a time span in general? I only know of date time ones. Is the standard 1:12:23:56.5550000?

**Comment by iSazonov** [comment]
No. It is from the same [datetime RFCs](https://en.wikipedia.org/wiki/ISO_8601).
