### ISSUE TITLE
running enable-wsmancredssp causes PowerShell to exit with error

### ISSUE THREAD

**Issue by JamesWTruher** [PowerShell/PowerShell#2599]
Steps to reproduce
------------------
enable-wsmancredssp -DelegateComputer ServerA.foo.xyz.com -Role Client -Force

Expected behavior
-----------------
not to crash

Actual behavior
---------------
Unhandled Exception: System.InvalidCastException: Unable to cast COM object of type 'Microsoft.WSMan.Management.GPClass'
 to interface type 'Microsoft.WSMan.Management.IGroupPolicyObject'. This operation failed because the QueryInterface cal
l on the COM component for the interface with IID '{EA502723-A23D-11D1-A7D3-0000F87571E3}' failed due to the following e
rror: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.WSMan.Management.EnableWSManCredSSPCommand.UpdateCurrentUserRegistrySettings() in C:\Users\jimtru\src\github\Forks\JamesWTruher\PowerShell-1\src\Microsoft.WSMan.Management\CredSSP.cs:line 733
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      6.0.0-alpha
PSRemotingProtocolVersion      2.3
CLRVersion
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.11-64-g1851e1a5dcc648dec6170d037109775b3dce0038
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
PSEdition                      Core
```

**Comment by jeffbi** [comment]
The underlying cause of this is the lack of support for STA in CoreCLR. See issue #3353.

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/3353
