### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by shaolinint** [PowerShell/PowerShell#2615]
Expected behavior
-----------------
Successfully register repository?

Actual behavior
---------------
Segmentation fault sudo powershell
```
PS /home/shaolinint/powershell> Register-PSRepository -Name "PSGallery" –SourceLocation "https://www.powershellgallery.com/api/v2/" -InstallationPolicy Trusted
[1]    4365 segmentation fault  sudo powershell
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.12
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by bmanikm** [comment]
@shaolinint is this still reproducible on latest PowerShell Core release? 
- If not, can we close this?
- If yes, could you please provide more details to repro this error along with -Debug output of a PowerShellGet command?

**Comment by iSazonov** [comment]
I close the old Issue. If problem still exists it should be tracked in PowerShellGet repo.
