### ISSUE TITLE
Get-Help -Online opens help for 5.0, not 5.1/6.0.

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2616]
The first related link in the help files links to online help for 5.0.
e.g. Get-Content Online Version: http://go.microsoft.com/fwlink/?LinkId=821583

The HelpUri hasn't been updated to 5.1 either: 
e.g. Get-Content: https://go.microsoft.com/fwlink/?LinkID=113310

**Comment by joeyaiello** [comment]
Now this is directing to 5.1, so we need to point to 6.0 by release time.

**Comment by iSazonov** [comment]
@joeyaiello We get duplicate Issue for this - it seems time to fix the Issue.

Currently we use short links for Help Uri - it would be great if we could use its with parameter like `https://go.microsoft.com/fwlink/?LinkID=113280&view=powershell-6`

**Comment by iSazonov** [comment]
After Update-Help we get help files in user profile and then we can get wrong help in PowerShell session.

**Comment by SteveL-MSFT** [comment]
Still repros in 6.1.  cc @sdwheeler

**Comment by sdwheeler** [comment]
@SteveL-MSFT Adding the view to the query string will not fix the problem. The problem is that the FWLINK is wrong. There needs to be a new FWLINK created for v6. There may already be one, in which case, we just need to update the header in the markdown file with the proper FWLINK.

**Comment by SteveL-MSFT** [comment]
@sdwheeler can you create the fwlink and I'll update it in the code?

**Comment by sdwheeler** [comment]
@SteveL-MSFT  I have never done it. These FWLINKs should be owned by the dev team. @adityapatwardhan may know how to do it. We should inventory all of the FWLINKs and validate that the accuracy across all of the cmdlets/versions.

**Comment by SteveL-MSFT** [comment]
Thanks, I'll follow-up offline.

**Comment by FireInWinter** [comment]
This is still an issue in 6.2.0-preview.3.  Or at least it is with a few cmdlets I tested: Get-Content, ConvertFrom-Json, and ConvertTo-Json.  And they pointed to 5.0 documentation.

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan we should probably bulk update the fwlinks

**Comment by sdwheeler** [comment]
@SteveL-MSFT @adityapatwardhan We need to create a bunch of new FWLinks to point to the new version content. Or, if we reuse the existing FWLinks then we need new ones to point to the old content.
