### ISSUE TITLE
Update git docs on how to work from a fork

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2618]
https://github.com/PowerShell/PowerShell/blob/master/docs/git/README.md

Currently it covers how to work from a branch, but not how to work from a fork, setup remotes correctly and keep fork in sync with upstream

**Comment by lzybkr** [comment]
That document was meant to document our specific workflow, not general git setup. Github already has good documentation on working from a fork: https://help.github.com/articles/fork-a-repo/

**Comment by SteveL-MSFT** [comment]
@lzybkr I was following the GitHub documentation, but @vors was recommending something different

**Comment by SteveL-MSFT** [comment]
I'm closing this and recommend using the GitHub documentation
