### ISSUE TITLE
If Urlmon.dll is not present, follow an alternative code path to get security zone of a given file

### ISSUE THREAD

**Issue by charub** [PowerShell/PowerShell#2619]
Refer to MSFT:9583626

PS Core is dependent on Urlmon.dll to get the security zone of a given file.  Urlmon.dll is not available on NanoServer. Make changes to follow an alternative code path if Urlmon.dll is not present.

## **Following Scenarios should work :**
**Scenario 1 :**
1. Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
2. Set-Content -path .\TestRemoteFile.ps1 -Value Get-Date
3. $alternateStreamContent = @"
[ZoneTransfer]
ZoneId=3
"@
4. Add-Content -path E:\Scripts\TestRemoteFile.ps1 -Value $alternateStreamContent -Stream Zone.Identifier
5.  .\TestRemoteFile.ps1

**Expected behavior :**

.\TestRemoteFile.ps1 : File E:\Scripts\TestRemoteFile.ps1 cannot be loaded. The file E:\Scripts\TestRemoteFile.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\TestRemoteFile.ps1
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Scenario 2 :**
1. Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
2. Set-Content -path .\TestUntrustedFile.ps1 -Value Get-Date
3. $alternateStreamContent = @"
[ZoneTransfer]
ZoneId=4
"@
4. Add-Content -path .\TestUntrustedFile.ps1 -Value $alternateStreamContent -Stream Zone.Identifier
5.  .\TestUntrustedFile.ps1

**Expected behavior :**
.\TestUntrustedFile.ps1 : File E:\Scripts\TestUntrustedFile.ps1 cannot be loaded. The file E:\Scripts\TestUntrustedFile.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\TestUntrustedFile.ps1
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Scenario 3 :**
1. Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
2. Set-Content -path .\TestLocalFile.ps1 -Value Get-Date
3. $alternateStreamContent = @"
[ZoneTransfer]
ZoneId=0
"@
4. Add-Content -path E:\Scripts\TestLocalFile.ps1 -Value $alternateStreamContent -Stream Zone.Identifier
5.  .\TestRemoteFile.ps1

**Expected behavior :**
Friday, November 4, 2016 11:02:46 AM

**Scenario 4 :**
1. Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
2. Set-Content -path .\TestIntranetFile.ps1 -Value Get-Date
3. $alternateStreamContent = @"
[ZoneTransfer]
ZoneId=3
"@
4. Add-Content -path E:\Scripts\TestIntranetFile.ps1 -Value $alternateStreamContent -Stream Zone.Identifier
5.  .\TestIntranetFile.ps1

**Expected behavior :**
Friday, November 4, 2016 11:02:46 AM

**Scenario 5 :**
1. Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
2. Set-Content -path .\TestTrustedFile.ps1 -Value Get-Date
3. $alternateStreamContent = @"
[ZoneTransfer]
ZoneId=2
"@
4. Add-Content -path E:\Scripts\TestTrustedFile.ps1 -Value $alternateStreamContent -Stream Zone.Identifier
5.  .\TestTrustedFile.ps1

**Expected behavior :**
Friday, November 4, 2016 11:02:46 AM

**Environment data
----------------**
PS C:\> $PSVersionTable

Name                                        Value
----                                             -----
CLRVersion
PSEdition                                   Core
PSVersion                                  6.0.0-alpha
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
WSManStackVersion                  3.0
BuildVersion                               3.0.0.0
SerializationVersion                    1.1.0.1
GitCommitId                               v6.0.0-alpha.12

**Comment by daxian-dbw** [comment]
Resolved via #2625
