### ISSUE TITLE
Add ValidatePositive and ValidateNonNegative attributes

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2634]
From @lzybkr #2492 
> it seems like we should have `ValidatePositive` and `ValidateNonNegative` attributes.

as replacement of `[ValidateRange((int)1, Int32.MaxValue)] ` and `[ValidateRange((int)0, Int32.MaxValue)] `

**Comment by dchristian3188** [comment]
Picking this one up in PR: 
https://github.com/PowerShell/PowerShell/pull/4084

**Comment by lzybkr** [comment]
Closed via #4084
