### ISSUE TITLE
Is this ConvertFrom-StringData bug?

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2638]
Is this ConvertFrom-StringData bug?

The return value of linux, a little more **blank line**, than Windows  

Steps to reproduce
------------------
$aaa =
@'
OrganizationNO = "00269904"
OrganizationNameShort = "综合办公室厂处级"
OrganizationName = "机械分公司综合办公室厂处级"
SuperiorNo = "00269881"
OrganizationLevel = "二级单位直属机构内设机构"
OrganizationLevelCode = "3C"
RegionCode = "070"
Region = "1省"
City = "1市"
IsEmptyOrg = None
OrgStartDate = "20161001"
OrgEndDate = "99991231"
CreateTime = "2005/10/22 12:47:09"
LastUpdateTime = "2016/10/12 0:16:59"
'@ 
    
ConvertFrom-StringData $aaa

Expected behavior
-----------------
no that black line.

Actual behavior
---------------
![006](https://cloud.githubusercontent.com/assets/8968667/20035989/924f27cc-a434-11e6-91ae-3beaa15c0877.png)

Environment data
----------------
linux:
Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-alpha                                                                                                       
PSEdition                      Core                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   3.0.0.0                                                                                                           
GitCommitId                    v6.0.0-alpha.11                                                                                                   
CLRVersion                                                                                                                                       
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1 

windows:
windows 10 1607 ,tested,no this issue.

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by chuanjiao10** [comment]
report: The problem is still in powershell beta1(.net core 2.0)

**Comment by chuanjiao10** [comment]
6.0.2 + psreadline 2.0.0: 
has this bug

v6.1.0-preview.1 + psreadline 2.0.0: 
fixed 

good job !                  THANKS !!!

**Comment by iSazonov** [comment]
@chuanjiao10 6.0.2 is only security update - all new PR is only in 6.1.0 - use the version for tests.

**Comment by iSazonov** [comment]
Seems it is side effect from @SteveL-MSFT fix (I can not find the PR).

**Comment by SteveL-MSFT** [comment]
@iSazonov I suspect this is a side effect of the change to not have whitespace at the end.  With the double-wide characters, the calculation of the length of the string would have been wrong so the amount of whitespace added was too large thus creating a newline
