### ISSUE TITLE
Kali linux not supported

### ISSUE THREAD

**Issue by deepgray** [PowerShell/PowerShell#2641]
Steps to reproduce
------------------
trying to build on the Kali Linux 2 2016 rolling build which is based on debian 8 and download.sh complains about not supported. since both kali AND ubuntu 16 are based on debian, wouldn't it be more prudent to support debian rather then a layer on top of that? (like Red hat versus CentOS)...

how do i compile the code for a native solution?

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
The Powershell is open project. If Debian community want Powershell - Welcome!

**Comment by TheFlyingCorpse** [comment]
Install libicu from regular Debian 8 (version 1.52 I think it was) and you can get it running under Kali 2016.2. libicu under kali is 1.57 which is not what its linked against. Alternatively, if you are brave, try to find a matching Ubuntu version and use its .deb file, I think its yakkety (16.10) comes with 1.57.

**Comment by sdcampbell** [comment]
I documented an easy way to install PowerShell on Kali here: https://www.stevencampbell.info/2017/04/install-powershell-on-kali-linux/

**Comment by iSazonov** [comment]
@sdcampbell Thanks! If you placed it in the official repo we could refer to this in our docs.

**Comment by sdcampbell** [comment]
@iSazonov I submitted a PR to include the Kali installation process.
