### ISSUE TITLE
Get-PSRepository throws an error

### ISSUE THREAD

**Issue by adbertram** [PowerShell/PowerShell#2645]
Steps to reproduce
------------------
Run Get-PSRepository

Expected behavior
-----------------
The PowerShellGallery PS repository to be displayed.

Actual behavior
---------------
```
PackageManagement\Get-PackageSource : Unable to find module providers (PowerShellGet).
At /Users/AdamBertram/Dropbox/GHI/Modules/PowerShellGet/1.0.0.1/PSModule.psm1:3544 char:31
+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSource], Exception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource
```

Environment data
----------------
MacOS Sierra

Name                           Value                                                                                                                                      
----                           -----                                                                                                                                      
PSVersion                      6.0.0-alpha                                                                                                                                
PSEdition                      Core                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                    
BuildVersion                   3.0.0.0                                                                                                                                    
GitCommitId                    v6.0.0-alpha.12                                                                                                                            
CLRVersion                                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                        
SerializationVersion           1.1.0.1

**Comment by bmanikm** [comment]
This is happening due to broken PackageManagement on Alpha12 release #2664
