### ISSUE TITLE
Consider renaming 0-backlog and 2-Ready labels

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2648]
Although 0-backlog is documented to mean 'up for grabs', feedback is that it's not obvious and backlog may be interpreted as backlog (planned items) by the PowerShell team. 

2-Ready is intended to mean ready to start work, but may be interpreted as ready to merge.

**Comment by SteveL-MSFT** [comment]
Integrate with http://up-for-grabs.net/

**Comment by HemantMahawar** [comment]
@PowerShell/powershell-committee discussed and agreed to:
* rename '0-backlog' to 'up-for-grabs'
* remove '1..4-<name>' labels

**Comment by SteveL-MSFT** [comment]
Added project to up-for-grabs.net https://github.com/up-for-grabs/up-for-grabs.net/pull/498

**Comment by iSazonov** [comment]
It would be good for the community to have a description of all labels.
Need fix  `0 - Backlog` in [CONTRIBUTING.md ](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#contributing-to-issues)

**Comment by SteveL-MSFT** [comment]
#2681 to fix CONTRIBUTING.md, thanks for the catch

@PowerShell/powershell-committee I like your suggestion on 'Resolution - Committee' although it's more of a direction/decision than a resolution (unless it's a question)

**Comment by iSazonov** [comment]
@SteveL-MSFT  `Resolution` is only sample from me.
I agree that options may be direction/decision/conclusion/...

**Comment by SteveL-MSFT** [comment]
@iSazonov thanks for the feedback, @PowerShell/powershell-committee has added `Committee - Reviewed` label and used it

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks! It's very useful.
