### ISSUE TITLE
Get-Help is not reading from release-specific 6.0.0.n help directory

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2649]
Beginning in PowerShell 6.0.0.12, the version-specific (release-specific) $pshome\en-us ($env:ProgramFiles\PowerShell\6.0.0.12\en-US) has its own help files. But, Get-Help in 6.0.0.12 is reading its help files from $pshome in 5.1 (C:\Windows\System32\WindowsPowerShell\v1.0\en-us).

If we take the time to create release-specific help files, Get-Help should read them. 

Repro:
The about topics have characteristic off-by-one errors, so you can tell which one Get-Help is reading. 

In the image below, note that the 5.1 en-US About topics have this name error:

about_Aliases <--- extra line
TOPIC
    about_aliases

The 6.0.0.12 en-US About topics have a different name error:

TOPIC
    about_aliases

    about_aliases    #<-- extra name line

SHORT DESCRIPTION

So, when you run Get-Help, you can tell that it's pulling the older file.
![screenshot 2016-11-09 09 54 33](https://cloud.githubusercontent.com/assets/2954883/20148945/d77e6cfa-a663-11e6-8d75-ccaa8c20caf2.png)

Here's the effect:
![screenshot 2016-11-09 09 45 12](https://cloud.githubusercontent.com/assets/2954883/20148954/e15049e2-a663-11e6-9813-e5cd10f22d0b.png)

**Comment by joeyaiello** [comment]
I'm willing to bet that #2653 doesn't repro on Windows because it's finding Windows PowerShell help files.

**Comment by iSazonov** [comment]
@chunqingchen Do we ready to close the Issue?

**Comment by juneb** [comment]
Yes, thanks.
