### ISSUE TITLE
About topics have extra name line; off-by-one error

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2651]
About topics don't match About topic template. This creates off-by-one errors that make Get-Help About* display fail. (We need to serialize About topics! Markdown, XML, json, whatever)

In PS 5.1, About topics in $pshome\en-US have an extra filename line that creates an off-by-one error.

about_Aliases    #<---- extraneous
TOPIC
    about_aliases

SHORT DESCRIPTION

In $env:ProgramFiles\PowerShell\6.0.0.12\en-US, About topics have a different extra name line.

TOPIC
    about_aliases
                              #<---- Extra line
    about_aliases      #<---  Extra name line

SHORT DESCRIPTION
    Describes how to use alternate names for cmdlets and commands in  Windows
    PowerShell®.

These are not just annoying, but they create an off-by-one error because Get-Help About* is looking for line 5. See attached image.
![screenshot 2016-11-09 09 45 12](https://cloud.githubusercontent.com/assets/2954883/20151460/12dff36c-a66f-11e6-9575-89755f7e8eac.png)

**Comment by vors** [comment]
cc @Francisco-Gamino

**Comment by zjalexander** [comment]
Looking into this, it's present in 5.0/5.1 as well. Investigating this as part of all the other issues with updateable help downlevel.

**Comment by TaraMeyer** [comment]
@vors  Is this an issue with the schema in PlatyPS, or no?

**Comment by vors** [comment]
Schema is fine, it's the content in PowerShell-Docs.
I moved this issue to https://github.com/PowerShell/PowerShell-Docs/issues/804

Thank you, @juneb !

**Comment by vors** [comment]
I sent PR with a fix
https://github.com/PowerShell/PowerShell-Docs/pull/807
