### ISSUE TITLE
Update-Help not updating topics.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2652]
Steps to reproduce
------------------
Update-Help -force

Expected behavior
-----------------
To proceed and update topics.

Actual behavior
---------------
PS /home/maxt> update-help -Force                                               
     update-help : Failed to update Help for the module(s)                      'Microsoft.PowerShell.Core, Microsoft.PowerShell.Host, e                        Microsoft.PowerShell.Management, Microsoft.PowerShell.Security,                 Microsoft.PowerShell.Utility' with UI culture(s) {en-US} : The type oooooooooo] initializer for                                                                 'System.Management.Automation.Internal.CabinetExtractorFactory' threw an 
exception.
At line:1 char:1
+ update-help -Force
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.Upd 
   ateHelpCommand
![updatehelperror](https://cloud.githubusercontent.com/assets/19892435/20153737/2966bac6-a692-11e6-89ad-7b81f6bae021.png)

Environment data
----------------
OS = Ubuntu 16.04.1 LTS Desktop

```powershell
PS /home/maxt> $PSVersionTable                                                  

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.12                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment]
This got fixed by #2493 and will ship in the next alpha. 👍
