### ISSUE TITLE
Invoke-WebRequest performance with -OutFile

### ISSUE THREAD

**Issue by MathiasMagnus** [PowerShell/PowerShell#2656]
Steps to reproduce
------------------
Invoke-WebRequest -Uri <direct link to any large file> -OutFile test.bin

Expected behavior
-----------------
Achieve performance similar to that of a browser

Actual behavior
---------------
1% of available speed achieved (Fetching file from local cluster, Edge downloads with 150-250 Mbit, PS does with stable 4 Mbit)

(Most likely the issue is that the Write-Progress uses the main thread to report progress.)

Environment data
----------------

```powershell
PS C:\Users\Matty\Desktop> $PSVersionTable

Name                           Value
----                           -----
SerializationVersion           1.1.0.1
PSEdition                      Core
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
CLRVersion
GitCommitId                    v6.0.0-alpha.11
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
```

**Comment by iSazonov** [comment]
@MathiasMagnus Please test with latest build. We fixed a progress bar performance yesterday #2138

**Comment by MathiasMagnus** [comment]
Seems OK to me. Thanks.

**Comment by iSazonov** [comment]
@MathiasMagnus Thanks for the bug report. Welcome back with new bug reports and suggestions.
