### ISSUE TITLE
Get-ChildItem triggers Antimalware Service Executable

### ISSUE THREAD

**Issue by MathiasMagnus** [PowerShell/PowerShell#2657]
Steps to reproduce
------------------
Choose a directory with a fair amount of beefy executables and issue Get-ChildItem on the directory.

Expected behavior
-----------------
Obtain a directory listing in a reasonable amount of time.

Actual behavior
---------------
In reality it takes far longer than it should, mostly because displaying the directory listing triggers the Antimalware Service Executable which burns a CPU core but more importantly, takes a significant amount of time to finish scaling with the size of the directory.

```powershell
PS C:\Users\Matty\Downloads> ls | measure -Property Length -Sum


Count    : 83
Average  :
Sum      : 7041940346
Maximum  :
Minimum  :
Property : Length
```

83 files and 7 Gigs of Downloads with a fair amount of .exe, .iso and what not.

```powershell
PS C:\Users\Matty\Downloads> Measure-Command {$list = Get-ChildItem; foreach ($elem in $list) {Write-Host $elem}}
...
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 631
Ticks             : 26310762
TotalDays         : 3,04522708333333E-05
TotalHours        : 0,0007308545
TotalMinutes      : 0,04385127
TotalSeconds      : 2,6310762
TotalMilliseconds : 2631,0762
```

So just ordinarily printing the name of the files takes 2 seconds and 631 milliseconds (already not quite what I'd expect, but ok). Now, executing the following script block (forgive me, I couldn't devise a better solution to demo the artifact)

```powershell
$start = Get-Date;
ls ~\Downloads
$end = Get-Date;
$span = $end - $start;
Write-Host $span;
```

Prints out the following:

```PowerShell
"Exactly what I'd see if invoking Get-ChildItem plain from the console"
00:00:07.8705418
```
This is fishy.

Environment data
----------------

Latest nightly.

```powershell
PS C:\Users\Matty\Downloads> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.12-21-g2077e42b52cd431a9097cf6673f9b4d5f4e4f391
PSEdition                      Core
BuildVersion                   3.0.0.0
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
```

**Comment by MathiasMagnus** [comment]
I understand that this is not a "valuable" feature request, but its such core functionality that I was hoping to see this addressed sooner. Simply navigating the filesystem is immensely subpar to a native Linux experience.

It is not just the the pathological large `~\Downloads` folder that suffers from this, but most Windows `bin` folders (Cygwin, Git, Visual Studio, Qt, etc.) so any install that has a fair amount of `.exe` and `.dll` in it. It is fairly common for a sysadmin to list folders for files. On Linux, it's roughly as fast as the console can spew out characters.

And I haven't even talked about `locate somehing` vs. `gci C:\ -R -Fil something -Err SilentlyContinue`. Prior takes 1 second at most, while the latter is a multi-minute command. Powershell could really improve on its interactive part.

**Comment by MathiasMagnus** [comment]
I did some more research, AMSE triggers and as such slows down dir listings of files that were downloaded and have not yet been targets of `Unblock-File`. (If I download a ZIP file and expand it, the result is the same. Unzipped content also need to be Unblocked, if the ZIP has not been prior to unzipping.)

**Comment by lzybkr** [comment]
Can you add a stack where AMSE triggers? That could save someone a bit of work and possibly get a fix in faster.

**Comment by MathiasMagnus** [comment]
What do you mean "add a stack where AMSE triggers"? For me, _stack_ means _call stack_, but I have no idea how to obtain something like that. You mean write a short script?

**Comment by lzybkr** [comment]
Yes, I meant call stack. I guessed incorrectly that you were looking at call stacks to see that AMSE was triggered.

**Comment by MathiasMagnus** [comment]
No, `Get-ChildItem` on my `~\Downloads` dir takes 7 seconds (now actually 14 seconds, was 7 when I reported). That is totally enough to see AMSE dominate the CPU usage in Task Manager.

**Comment by MathiasMagnus** [comment]
For future reference, how can I get a call stack that has demonstrative power as to what's happening? AMSE I thought is a constantly running service, and as such it should not be directly associated with any of my processes.

**Comment by lzybkr** [comment]
[Perfview](https://github.com/Microsoft/perfview) is great for collecting etw traces, though the UI is hard to use.

Windows Performance Toolkit has `wpa` which is good for analyzing traces. This [blog post](https://randomascii.wordpress.com/2015/09/24/etw-central/) has lots of good references on getting started.

I will say these tools are not exactly beginner friendly - but they are super powerful.

**Comment by powercode** [comment]
@lzybkr And Bruce is also unicycling :)

**Comment by lzybkr** [comment]
@powercode - Bruce Dawson is somewhat well known for unicycling a popular bike ride from Seattle to Portland - 200 miles. 10,000 riders do it every year, most take 2 days. I saw him training for that ride commuting to work - so he was actually part of how I got started unicycling.

As long as you brought it up - @LeeHolmes and @vors can also ride a unicycle - so it's highly recommended if you want to be one of the cool PowerShell peeps :)

**Comment by powercode** [comment]
A quick look gives at hand that the `Mode` CodeProperty is very expensive. (33% on my machine) and the lions share of that is `Microsoft.PowerShell.Commands.InternalSymbolicLinkLinkCodeMethods::WinIsHardLink`

**Comment by powercode** [comment]
Seems like we could improve on the Console output. For each line we write, we make PInvoke calls to GetConsoleScreenBufferInfo, GetConsoleMode and WriteConsole. Do we really have to to the first two calls for each line?

**Comment by vors** [comment]
Lol, what a thread. I probably would not be able to unicycle after that long.
