### ISSUE TITLE
PackageManagement is broken in the latest alpha-12 on Linux

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShell#2664]
A user reported in https://github.com/OneGet/oneget/issues/239 that OneGet is broken in the Alpha12 on Linux.

Debugging into the issue, the following line seems causing the problem.  Microsoft.Win32.Registry throws an exception now which is peace and safe before. Per Dongbo, it is caused by the latest CoreCLR change.
 
System.TypeInitializationException
"Operation is not supported on this platform."
"Microsoft.Win32.Registry"
"   at Microsoft.Win32.RegistryKey.OpenBaseKeyCore(RegistryHive hKey, RegistryView view)\n   at Microsoft.Win32.Registry..cctor()"
 
 
 
Source: https://github.com/OneGet/oneget/blob/master/src/Microsoft.PackageManagement/Implementation/PackageManagementService.cs
 
 ``` C#
       internal void LoadProviders(IHostApi request) {
        …
 
            var providerAssemblies = (_initialized ? Enumerable.Empty<string>() : _defaultProviders)
                .Concat(GetProvidersFromRegistry(Registry.LocalMachine, "SOFTWARE\\MICROSOFT\\PACKAGEMANAGEMENT"))
                .Concat(GetProvidersFromRegistry(Registry.CurrentUser, "SOFTWARE\\MICROSOFT\\PACKAGEMANAGEMENT"));

```
Steps to reproduce
------------------
Install the alpha12 on Linux
Get-PackageProvider

Expected behavior
-----------------
PowerShellGet and NuGet providers should be listed from Get-PackageProvider

Actual behavior
---------------
Nothing returned. No assemblies are successfully initialized.

Environment data
----------------

```powershell
PS /opt/microsoft> $PSVersionTable                                              

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.12                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         


```

**Comment by jianyunt** [comment]
I am going to make PR soon

**Comment by jmuelbert** [comment]
In Powershell for macOS is the same error

**Comment by mirichmo** [comment]
@jianyunt Is this issue resolved? if so, please close it, mark it fixed, and place it in the alpha.12 milestone. If you don't have permissions for that, let me know.

**Comment by jianyunt** [comment]
@mirichmo yes, checked-in. Can you place it to alpha12 milestone. After that i can close it.

**Comment by mirichmo** [comment]
I'm closing it since I am already modifying it.
