### ISSUE TITLE
CC with lpthreads instead of lpthread for pthread_create found only in pthred (without s)

### ISSUE THREAD

**Issue by VGib** [PowerShell/PowerShell#2668]
Hello,

powershell don't compile any more on archlinux, after analyse I found something which should be a bug in makefile.

I explain (I'm not a C++ expert).

In my computer powershell compile with found_threads, but the theads are in pthread:
 
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.5.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done

When compiling with CC there is the option -tpthread
/usr/bin/cc  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -DCHECK_FUNCTION_EXISTS=pthread_create   -Wl,-O1,--sort-common,--as-needed,-z,relro  CMakeFiles/cmTC_2f539.dir/CheckFunctionExists.c.o  -o cmTC_2f539 -rdynamic -lpthread 

But one time it's seems to use -lpthreads, and we have this error:
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c8e41.dir/link.txt --verbose=1
/usr/bin/cc  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -DCHECK_FUNCTION_EXISTS=pthread_create   -Wl,-O1,--sort-common,--as-needed,-z,relro  CMakeFiles/cmTC_c8e41.dir/CheckFunctionExists.c.o  -o cmTC_c8e41 -rdynamic -lpthreads 
/usr/bin/ld : ne peut trouver -lpthreads
collect2: erreur : ld a retourné 1 code d'état d'exécution
make[1]: *** [CMakeFiles/cmTC_c8e41.dir/build.make:98: cmTC_c8e41] Error 1
make[1] : on quitte le répertoire « /supp/tmp/yaourt-tmp-vincent/aur-powershell-git/src/powershell/src/libpsl-native/CMakeFiles/CMakeTmp »
make: *** [Makefile:126: cmTC_c8e41/fast] Error 2

I think this may be a Makefile error, daesn't it? 
As I'm not a C++ developer, it's difficult for me to propose a patch .....

Regards,

VGib

**Comment by VGib** [comment]
Solved

**Comment by iSazonov** [comment]
@VGib Please add more comments about solution.

**Comment by VGib** [comment]
I don't know. I tryed month after, I didn't have the error and I've compiled without a problem. I think the variable's problem may have been solved.
Do you want to  open it again?

**Comment by iSazonov** [comment]
Thanks for clarify!
If the problem appears again feel free to re-open the Issue.
