### ISSUE TITLE
System.Management.Automation.pdb (and others) are missing from 6.0.0-alpha.12 package

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/PowerShell#2669]
powershell-6.0.0-alpha.12-win81-x64.zip doesn't contain symbols for System.Management.Automation.dll

**Comment by joeyaiello** [comment]
To be honest, it's kindaaaaa weird that we ship symbols at all in our release packages.

**Comment by vors** [comment]
Symbols are traditionally live in [separate](http://docs.nuget.org/ndocs/create-packages/symbol-packages) nupkg files. Production code that we ship should not have symbols.
