### ISSUE TITLE
Add ability to turn experimental features on/off

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#2670]
Rough thinking here: for stuff like [globbing](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0009-Glob-for-Native-Tools.md) the @PowerShell/powershell-committee discussed the ability to introduce experimental features that people can opt into in alpha/beta builds. Something like `Get-/Enable-/Disable-PSExperimentalFeature`. 

I actually might try to implement this myself if I get some free time. :)

**Comment by SteveL-MSFT** [comment]
This probably should be a RFC

**Comment by iSazonov** [comment]
Are you talking about the run-time or compile-time?

**Comment by lzybkr** [comment]
Runtime.

**Comment by iSazonov** [comment]
@lzybkr  Thanks! 
Means these new experimental features should conflict with existing ones. Expose breaking changes?  It seems it is somewhere near `Set-StrictMode`.

**Comment by iSazonov** [comment]
Implemented in #7242
