### ISSUE TITLE
Add validation on get-* cmdlets where passing $null returns all objects instead of error

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2672]
@PowerShell/powershell-committee discussed #2544 and decided that we should fix all the cmdlets except for the Provider ones as it's a risky breaking change as we can't be certain if $null is a valid value for the path.  

- [x] Get-Credential -UserName
- [x] Get-Event -SourceIdentifier
- [x] Get-EventSubscriber -SourceIdentifier
- [x] Get-Help -Name
- [x] Get-PSBreakpoint -Script
- [x] Get-PSProvider -PSProvider
- [x] Get-PSSessionConfiguration -Name
- [x] Get-PSSnapin -Name
- [x] Get-Runspace -Name
- [x] Get-RunspaceDebug -RunspaceName
- [x] Get-Service -Name
- [x] Get-TraceSource -Name
- [x] Get-Variable -Name
- [x] Get-WmiObject -Class
- [x] Get-WmiObject -Property

**Comment by iSazonov** [comment]
Can we fix this in one PR or in separate PRs?

**Comment by SteveL-MSFT** [comment]
@iSazonov I think a single PR would be fine

**Comment by HemantMahawar** [comment]
@iSazonov  Are you going to work on this?

**Comment by dlwyatt** [comment]
Attributes added in #2685 , along with a question about testing this.
