### ISSUE TITLE
Get-AuthenticodeSignature should support an explicit catalog path.

### ISSUE THREAD

**Issue by mattifestation** [PowerShell/PowerShell#2676]
I would like the ability to specify an explicit catalog path when using Get-AuthenticodeSignature. -CatalogFilePath would probably be the ideal parameter name. I see some software that includes a signed cab file as part of their build artifacts and I would like to be able to validate the signature against the catalog file without having to install it in catroot. Additionally, with the addition of the New-FileCatalog and Test-FileCatalog, I would expect more PowerShell authors to include cab files with their build artifacts.

**Comment by doctordns** [comment]
Is this still an issue?  I have not seen any need expressed in public forums for this feature.

**Comment by iSazonov** [comment]
Maybe @jborean93 has thoughts.
