### ISSUE TITLE
Remove dotnet pinning

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2684]
Housekeeping issue, so we don't lost this information.

1) I pinned version of `dotnet` cli that we install in #2573

https://github.com/PowerShell/PowerShell/blob/25005a0ba04a3509e33f18b8184ba90fbc22dd44/build.psm1#L916

2) I pinned sha1 commit that we use for downloading dotnet install/uninstall scripts in #2682

https://github.com/PowerShell/PowerShell/blob/25005a0ba04a3509e33f18b8184ba90fbc22dd44/build.psm1#L864

We should un-pin versions, if we can.
It's probably ok to wait until `dotnet` has the full support for MSBuild and allign this work with transition to `.csproj` files instead of `project.json` files.

**Comment by randomvariable** [comment]
Repinned in #2737 to the .NET 1.1 release.

**Comment by vors** [comment]
This issue got resolved in some way, closing because the originally captured info is currently irrelevant.
