### ISSUE TITLE
Invoke-Command should support -StrictMode

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2692]
This would effectly add the command "Set-StrictMode -version 5" at the beginning of the scriptblock.
The reason why should should be a parameter vs just having the user add that line to every script is that it allows someone to set this via $PSDefaultParameterValues and have it affect an entire corpus of scripts (without having to change the scripts itself).

Here is the workaround that I wrote to implement this:
https://www.powershellgallery.com/packages/Invoke-Command

**Comment by faraazahmad** [comment]
I would like to work on this

**Comment by PaulHigin** [comment]
Unfortunately, this would not be a trivial change.  The specified strictmode version would have to be communicated to the target, where it can be applied to the runspace being created in the remote session there.  But this means updating the remoting protocol, which means gaining approval, updating the protocol version, documentation, and handling down level (non-supported) cases.

**Comment by iSazonov** [comment]
This is not the first time that we talk about the fact that PSRP needs to be extended.
If we think about implementing new remoting subsystem why not think about PSRP enhancing, new transport like gRPC, and fallback to WinRM and old PSRP version?

**Comment by PaulHigin** [comment]
Updating the protocol is an arduous undertaking, and we need to maintain compatibility with WindowsPowerShell, so I feel we need to have very strong reasons for doing it.  Maybe we can keep a collection of improvements that require protocol update and at some point we update the protocol when the benefits justify the effort.

**Comment by iSazonov** [comment]
The new remoting subsystem should definitely allow not only different transport but protocol versions too. :-)

**Comment by iSazonov** [comment]
Uh! 5 years to implement :-)
