### ISSUE TITLE
Debug: Should be able to Step-Into "Invoke-Command -Computername" 

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2697]
This should provide a simple way to debug the scriptblock on the remotemachine.

**Comment by joeyaiello** [comment]
Also need to eventually support this even if `-AsJob` is specified.

**Comment by daviwil** [comment]
Paul has submitted a PR for this: https://github.com/PowerShell/PowerShell/pull/3015

**Comment by daxian-dbw** [comment]
I'm resolving this issue as a duplicate of #2827
