### ISSUE TITLE
Debug: Should be able to SET NEXT LINE to execute

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2698]
Scenario:  
1) Stop before a line
2) Run a variation of that line interactively on the command line (you can't edit scripts while debugging).
3) Set Next line to the be the line after this effectively skipping over the line I entered at the CLI.

Don't implement this as SKIP LINE because  SET NEXT LINE has a lot of other scenarios as well.

**Comment by lzybkr** [comment]
Much of what's needed to implement this feature is already implemented in the compiler to support the trap statement.

The generated code for a script turns into a big switch statement so we can jump to a specific statement after processing a trap.

I believe the debugger can simply compute which statement a particular line corresponds to, and set a field in the function context, then this functionality should more or less work. I'm sure I'm missing some tricky aspects, but I think the hardest part was already implemented.
