### ISSUE TITLE
Allow a mechanism to ERROR out if there are uninitialized variables in a script

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2699]
Set-StrictMode will generate an error for uninitialized variables AT RUNTIME (when the variable is accessed)
I want a mechanism to have it check the AST and throw the error BEFORE running anything.

NOTE - this should also flow into analyzing scriptblocks that have $USING:variable

**Comment by lzybkr** [comment]
I believe we need new syntax to support this feature. I suggest `using strict` or something like that, but perhaps we need an RFC.
