### ISSUE TITLE
Split-Path should support -Extension and -LeafBase

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#2700]
$f = "c:\temp\foo.txt"

Split-Path $f -Leaf -> "foo.txt"
Split-Path $f -Extension -> ".txt"  (with the "." to be compatible with dir)
Split-Path $f -LeafBase -> "foo"

**Comment by thezim** [comment]
If the file exist Get-Item will work.

(Get-File c:\temp\foo.txt).Extension -> .txt
(Get-File c:\temp\foo.txt).Name -> foo.txt
(Get-File c:\temp\foo.txt).BaseName -> foo

**Comment by iSazonov** [comment]
How it will work for other providers?

**Comment by jpsnover** [comment]
Split-Path doesn't require the object to exist.  
(Get-Item c:\temp\foo.txt).Name does

**Comment by powercode** [comment]
@powershell/powershell I can take a stab at it.

**Comment by powercode** [comment]
All providers that can produce a child can also give us base and extension, so that shouldn't be a problem.
```
Parent\Child    -> Leaf, LeafBase,Ext
Fubaar\Foo.bar  -> Foo.bar, Foo, bar
Fubaar\Foo      -> Foo, Foo, ''

```

**Comment by kvprasoon** [comment]
An issue #5766 is reported in relation with this.
