### ISSUE TITLE
Need Additional Launch condition in Windows 10 / Server 2016 MSI Package

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#2707]
The Windows **8** MSI has a proper launch condition in it to block installs on anything older than Windows 8.

It appears that same launch condition was copied to the Windows 10 package.

This means that nothing is blocking the Windows 10 package from installing on Windows 8.x.

I suggest leaving *ADDING* a new launch condition after the "less than Windows 8" one that blocks for installing on Windows 8.  Retaining the "less than windows 8" launch condition will then give proper guidance when that package is attempted on OSes older than Windows 8.

Untested:
Condition: **Installed OR (WindowsNT > 601 AND WindowsNT < 10)**
Message: **This package is for Windows 10 / Server 2016 or later, please install the Windows 8 package instead.**

**Comment by mirichmo** [comment]
We are evaluating moving to two windows installers, one for x86 and one for x64 per #2608. In that scenario, the launch condition must be inclusive of all supported OS versions (Win 7+).

**Comment by iSazonov** [comment]
Currently we have one package for all versions.
