### ISSUE TITLE
Chocolate Package Now Available

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#2708]
A Chocolatey package is now available for installing PowerShell Core on WIndows 8 and 10.

To request improvements to the package, please file an issue here (please mention the package name as the repo covers multiple packages): https://github.com/DarwinJS/ChocoPackages/issues

Some notable considerations:
- chocolatey does not run on Nano - so the package has not been setup to handle it.
- the package is "pre-release" (by semantic versioning standards) and therefore WILL NOT show up in chocolatey searches.  You can view it directly at http://chocolatey.org/packages/powershell-core
- because it is pre-release you will need to use the "-pre" chocolatey switch to get it to install - including if you are installing a specific version, like this: ''''choco install powershell-core -pre -confirm```
- If you only want one version installed when upgrading, you will have to issue choco uninstall for the version you currently have installed.
- If you give the package a -force to have it install, previous versions are not removed
- if the the version you are trying to install with chocolatey is already present, the package exits with success without installed - use "-force" if you want to actually re-write the binaries.

**Comment by kilasuit** [comment]
@SteveL-MSFT - Are there any plans for this package to become owned by the PowerShell Team and therefore have it managed and released to chocolatey just like the other package managers for linux systems.

If not currently then in my opinion it should be transferred to be be owned by your release process for consistency

**Comment by SteveL-MSFT** [comment]
@kilasuit there was some discussion about PowerShell Gallery team standing up their own instance of a Chocolatey repo so that we can support it with official releases.  cc @edyoung who would own this.

**Comment by kilasuit** [comment]
@SteveL-MSFT - why can't this be posted to the community Chocolatey repo? I think all that would need to happen is that @DarwinJS would need to transfer/add the PowerShell team as a Publisher which would then allow this to be owned & maintained by the PSTeam

**Comment by DarwinJS** [comment]
@kilasuit  - this package is in the community chocolatey repo.  Community OSS packaging works just like other OSS - if a community member can shoulder the load, then they generally do.

**Comment by kilasuit** [comment]
@DarwinJS I know that it is as I use it however from what @SteveL-MSFT was saying it sounded like they were looking not to use this one and to make use of their own PowerShell Chocolately repository instead. Or at least that's how it read to me.

Perhaps would be best to see what @edyoung says on this if it would be owned by him/his team.

**Comment by kilasuit** [comment]
@DarwinJS - my ask was to transfer the community package to being maintained by the PowerShell team as an extension to their existing release mechanisms for other package managers 

However I think that @SteveL-MSFT was hinting that there would be a Microsoft choco instance that would likely house all possible microsoft trusted downloads which would be a better scenario longer term for all Microsoft products not just PowerShell Core which I think would be a great thing to happen if it did

**Comment by DarwinJS** [comment]
@kilasuit - yes I understand and am aware of these things as I am on the monthly MS open source calls.  

This particular package does much more than function simply as a Chocolatey package - it can also run outside of Chocolatey in environments that don't support Chocolatey (like Nano and machine or OS builds where the user does not want the chocolatey client installed): https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md

I'm not sure if Microsoft wants to port all of that capability as it requires learning the code, maintenance and testing.

If Microsoft does not want it and folks in the community still want the non-chocolatey functionality - it's possible this package would continue to be maintained on Chocolatey.org - with the official packaging on the Microsoft feed should the team so choose.
