### ISSUE TITLE
Powershell.sln does not build in Visual Studio

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2714]
Steps to reproduce
------------------
Open PowerShell.sln in visual studio 2015
Build Solution

Expected behavior
-----------------
Project builds and enables F5 debugging, at least for FullClr

Actual behavior
---------------
Lots of reference errors

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by lzybkr** [comment]
Duplicate of #1895.
