### ISSUE TITLE
Many definitions of cmdlets use 'string' instead Verbs<> class strings

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2716]
Would we have to fix it?

Full list attached. [cmdletverbs.txt](https://github.com/PowerShell/PowerShell/files/599195/cmdletverbs.txt)

Samples:

Now | Must Be
-|-
`[Cmdlet("Export", "Counter",`  |  `[Cmdlet(VerbsData.Export, "Counter",`
`[Cmdlet("Invoke", "Item",`       | `[Cmdlet(VerbsLifecycle.Invoke, "Item",`

**Comment by lzybkr** [comment]
This is a reasonable change to make, but it's definitely not necessary. I would expect the resulting binary to be exactly the same, so the only benefit is to make browsing for references easier.

**Comment by iSazonov** [comment]
> to make browsing for references easier

That's exactly why I want to clean it.
If PG approve, I'll do it.

**Comment by lzybkr** [comment]
I implicitly approved it when I said it's a reasonable change to make.
