### ISSUE TITLE
Unexpected behavior (usability) in Register-PSRepository

### ISSUE THREAD

**Issue by WernerMairl** [PowerShell/PowerShell#2717]
Hi
Working with Register-PSRepository i have found some behavior that was really unexpected.
Probably we are not talking about bugs but about usability....

1. Repository uniqueness
All the functions around PSRepository (Get, Register, Unregister) are using the Name Property/Argument to identify a Repo.
 
Seeing this API-Surface i'm assuming that the property Name is the one that implements the "unique" Key for Repos => expected behavior at the first look....

after playing a few hours with the api, i find out that internally NOT the Name must be unique but the property "SourceLocation" enforces uinqueness.

- That means i'm not be able to register the same package Source with different Names
- Means in different Powershell-Codebases that should run on the same server i must synchronize Repository NAMES....

To solve problems like that must select/filter my Repos by SourceLocation BUT the Get-PSRepo function doesn't implement filter for SourceLocation.... usability Issue, a property that is used as primary key should have some easy access....(yes i can do that with pure Powershell, but we are talking about API-Usability)

2. ErrorActionPreference is ignored!
If i call "Register-PSRepository" with a unique/random Name but a SourceLocation that is used in another Repo then the Function writes Error output.

_**PackageManagement\Register-PackageSource : The repository could not be registered because there exists a registered repository with Name 'XXXXX' and SourceLocation 'http://xxxxxxx.y.z.a:8080/api/odata'. To register 
another repository with Name 'XXXXX', please unregister the existing repository using the Unregister-PSRepository cmdlet**_

I found the following unexpected behavior here:

$ErrorctionPreference value is "Stop" in the calling script => assuming that a exception can be catched with try catch
Register-PSRepository writes the error record but it does not FOLLOWS the STOP behavior.. it IGNORES!

To enforce the "expected" behavior i must expplicitely use
Register-PSRepository ......-ErrorAction Stop

I'm not a expert in all the coding and behavior rules for PS but 
in 99% of my PS-Code i'm able to catch exceptions by using $ErrorActionPrefence on the global level
so i think that can be behavior issue inside Register-PSRepository

regards
Werner

**Comment by HemantMahawar** [comment]
This issue was moved to PowerShell/PowerShellGet#61
