### ISSUE TITLE
Rewrite Microsoft.PowerShell.Utility.psm1 on C#

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2718]
Would we rewrite the cmdlets on C# from the module [Microsoft.PowerShell.Utility.psm1](https://github.com/PowerShell/PowerShell/blob/master/src/Modules/Shared/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psm1) ?

- [x] Get-FileHash #2731 
- [x] New-TemporaryFile #2732 
- [x] New-Guid #2733 
- [x] Format-Hex #2730 
- [x] Import-PowerShellDataFile #2734 
- [x] ConvertFrom-SddlString #3212

**Comment by rkeithhill** [comment]
I would like to rewrite Format-Hex as a C# cmdlet.  I have written this cmdlet in C# for PSCX. I would also like to add support for `-Count` and `-Offset` parameters as well.  That said, I've really got to get Plaster 1.0 out the door first.  :-)

**Comment by iSazonov** [comment]
@rkeithhill Thanks! If PG approve this issue we open on a issue for every cmdlet and you can grab the cmdlet. :-) and discuss the new parameters.

I remember what @lzybkr  said about `Get-Uptime` that C# is better  because Powershell start will be faster.

**Comment by lzybkr** [comment]
I approve.

**Comment by joeyaiello** [comment]
@iSazonov I hope you don't mind I updated your comment with the issue numbers for each so they get auto-checked as those get closed :)

**Comment by iSazonov** [comment]
auto-checked? Good! :-)
