### ISSUE TITLE
Toolbox for scripters for common patterns

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2729]
I would like to see classes shipping with PowerShell geared towards scripters implementing advanced functions.

With common patterns I mean path processing, with or w/o globbing,  Include/Exclude filtering,
Progress management (percent complete/seconds remaining), creation of error records etc.

All these things that we write over and over again.

**Comment by rkeithhill** [comment]
You're right - it's a lot of boiler plate crap that is a PITA to have to write.  I've added snippets for some of this (primarily path processing) to the PowerShell extension for VSCode.  It seems like path processing is so common that there would be a specific `PathParameterAttribute` that would move all the grungy boiler plate code into PowerShell and provide your script's [string] or [string[]] parameter with all the properly resolved (tested for existence if the path must exist) and error appropriately (like when a "must exist" path doesn't exist).  Ah, I can dream.  :-)

**Comment by powercode** [comment]
Wow, this issue really attracted a lot of attention :) 

Is it better to open multiple issues with more specific suggestions?

**Comment by lzybkr** [comment]
Yeah, I'd say more specific issues would help drive something forwards.

**Comment by powercode** [comment]
What would be a good namespace for such tools?
SMA.Util?
SMA.Common?
SMA.SDK?

**Comment by ThomasNieto** [comment]
Similar issue #6745

**Comment by powercode** [comment]
Ping to keep alive
