### ISSUE TITLE
Rewrite Format-Hex on C#

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2730]
As approved in #2718 `Format-Hex` should be rewritten on C#.

**Comment by rkeithhill** [comment]
Where should this cmdlet go? I was thinking it would go in `PowerShell\src\Microsoft.PowerShell.Commands.Utility\commands\utility\FormatAndOutput\format-hex\format-hex.cs`?  Is that the right place?

**Comment by iSazonov** [comment]
Yes. Looks good.
