### ISSUE TITLE
Rewrite New-Guid on C#

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2733]
As approved in #2718  New-Guid  should be rewritten on C#.

**Comment by iSazonov** [comment]
Now it's just a wrapper for `[system.guid]::NewGuid`.
It would be good to add new parameters:
`-Empty` to get `[system.guid]::Empty`
`-Guid` as [string] (with `ValueFromPipeline`)
`-NewGuid` as default

**Comment by powercode** [comment]
Starting work.
@powershell/powershell assignment?

**Comment by lzybkr** [comment]
I disagree about adding `-Empty` and `-Guid`.  Neither seem to fit with the `New` verb, and converting a string to a `Guid` happens where necessary automatically, at least I think it does.

**Comment by powercode** [comment]
I agree about -Guid. As Guids are values without identity, you create then with new-guid. Why not provide a way to create the sentinel guid?

**Comment by iSazonov** [comment]
Some applications use GUID as a unique identifier. In this case, the identifier is a string. So really, we can get a stream of strings (ex. from logs), that we want to convert to `[guid]`. And yes this is more for `ConvertTo-Guid` but I looked through `New-*` cmdlets and many of them do a similar operation (string -> object). Most likely the new `ConvertTo-Guid` cmdlet is redundant and perhaps it would be better to make the `GUID` parameter.

Actually I'm surprised that `New-Guid` has appeared. But if it is, then it is logical to realize a full set of features including `Empty`. It is also used by some applications (ex. SCCM).

If we do not do `Guid` and `Empty` and do not use `pipeline` there is an option to make a breaking change and remove `New-Guid` because there is `[guid]`.

**Comment by iSazonov** [comment]
@PowerShellTeam Please close the Issue.
