### ISSUE TITLE
Microsoft.PowerShell.Archive Cmdlets should work on typical linux compression formats

### ISSUE THREAD

**Issue by stephlocke** [PowerShell/PowerShell#2740]
PowerShell 5 now supports native (de)compression of zip files. It would be great if this could be extended to include:
- .tar
- .gz
- .lzma / .7z
- .bz2

Ideally, this would function recursively so formats like .tar.gz get decompressed or created.  

This would make PowerShell better at handling archives from multiple systems.

**Comment by ctrlbold** [comment]
+1

**Comment by vors** [comment]
Great suggestion!
Per #1979 we are working on consuming the Archive module from it's own repo https://github.com/PowerShell/Microsoft.PowerShell.Archive

Can you, please, open an issue there?

**Comment by vors** [comment]
Opened #2743 to decouple it

**Comment by stephlocke** [comment]
Thx @vors!
