### ISSUE TITLE
Passing "-ExecutionPolicy Bypass" throws "Aborted"

### ISSUE THREAD

**Issue by Daniel15** [PowerShell/PowerShell#2742]
I;m trying to update the [Jenkins PowerShell plugin](https://wiki.jenkins-ci.org/display/JENKINS/PowerShell+Plugin) to handle Linux as well as Windows. At the moment, it passes `-ExecutionPolicy Bypass` as a command line parameter. While testing, I noticed that this causes PowerShell 6.0 on Linux to throw an "Aborted" error and exit with error code 134:

```
daniel@debian-test:/tmp$ echo "Write-Output 'Hello World'" > test.ps1
daniel@debian-test:/tmp$ powershell ./test.ps1
Hello World
daniel@debian-test:/tmp$ powershell -ExecutionPolicy Bypass ./test.ps1
Aborted
daniel@debian-test:/tmp$ echo $?
134
```

I know that script signing currently isn't implemented for non-Windows platforms, but perhaps it could just ignore the option?

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.12
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by glennsarti** [comment]
Noted - Still an issue in v6.0.0-alpha.17

**Comment by glennsarti** [comment]
@TravisEz13 Is this actually resolved?  I can still replicate the issue as per the repro case above easily in alpha-17

**Comment by TravisEz13** [comment]
It's fixed in the code.  It should be available in alpha 18.  The release should be very soon.  But I'm also happy to build it for you if you tell me the package you are using.

**Comment by glennsarti** [comment]
No. That's fine.  Happy to wait for alpha-18.  Was just surprised to see the issue closed.

**Comment by TravisEz13** [comment]
We build the ubuntu 14.04 package after it's merged to master it's available here:
https://s3.amazonaws.com/powershell-artifacts/PowerShell/PowerShell/2746/2746.1/powershell_6.0.0-alpha.17-71-g8de8b195-1ubuntu1.14.04.1_amd64.deb

You can find the URL at the bottom of the Travis-CI logs here:  https://s3.amazonaws.com/archive.travis-ci.org/jobs/218682617/log.txt

**Comment by Daniel15** [comment]
Why is it on S3 rather than Azure? 😄

**Comment by TravisEz13** [comment]
Travis-CI didn't support azure when we setup the system.
