### ISSUE TITLE
Commit "Merge remote-tracking branch 'upstream\master'"

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2746]
Today after sync with Powershell/master I get local a commit  285f2bfbe216ee6ada27fbd161fe40fe26ab4f91 Merge remote-tracking branch 'upstream\master'
Is it ok? The name is strange and no link to PR.

![commit](https://cloud.githubusercontent.com/assets/22290914/20475847/3fc66b28-afe7-11e6-9eb5-fc5776a0e61f.png)

**Comment by joeyaiello** [comment]
Looks just like @steve forgot to rebase instead of merge :) 

Unless a smarter git-wiz than me sees something wrong here, this should be okay to close.

**Comment by SteveL-MSFT** [comment]
Uh, my bad.
