### ISSUE TITLE
Flaky hang on Travis during class tests run

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2748]
I have seen this situation at least 4 times recently

![image](https://cloud.githubusercontent.com/assets/816680/20494642/b8b218a8-afd2-11e6-8e6c-176213db8733.png)

The worst part that it's not consistent and happens sporadically with about 20% chance.
It affects CI and master branch builds. 

The particular tests is different, but it's always during class language tests.

**Comment by daxian-dbw** [comment]
I saw this too in a recent PR.

**Comment by TravisEz13** [comment]
Per @lzybkr 

> I don't know, but a search of 'create linux core dump' suggests that gcore or kill may be capable of creating the core dump.

**Comment by iSazonov** [comment]
It is dup #3670
