### ISSUE TITLE
Extend System.Diagnostics.Process with a ParentProcess property

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2763]
It is unreasonably obscure to get the parent of a process via PowerShell today.
`Get-Command -Noun Process` will not give you anything, and you have to know that
there is a  `ParentProcessId` on `Get-CimInstance win32_process`. Even when you know that, you have to understand recycling of process ids and that you have to check the start time of the processes to actually know if it is your parent.

On top of that `Get-CimInstance win32_process` is dog slow due to some repetitive loading of mui dlls for some time zone related localization.

I suggest an extended property `Diagnostics.Process ParentProcess {get;}` that does the heavy lifting for the user in a fast and correct manner.

I don't know if it is valuable to also expose the ParentPid. (You were started by a process that had this id at the time when our your process started). Thoughts?

**Comment by powercode** [comment]
I can't find what `src\System.Management.Automation\engine\Types_Ps1Xml.generated.cs ` is generated from.
Any hints?

**Comment by powercode** [comment]
Or was it generated once upon a time, but isn't any longer?

**Comment by powercode** [comment]
Initial (working on WinFull) at https://github.com/powercode/PowerShell/tree/process-parentpid

What's the deal here regarding platform differences?
I'm not really well versed enough to say how to implement this on Linux/maxos.
Pointers?

**Comment by iSazonov** [comment]
> I can't find what  src\System.Management.Automation\engine\Types_Ps1Xml.generated.cs  is generated from.
 Any hints?

The file's history say that you can modify it.

**Comment by iSazonov** [comment]
>What's the deal here regarding platform differences?
 I'm not really well versed enough to say how to implement this on Linux/maxos.
 Pointers?

Start from [libpsl-native getcurrentprocessorid](https://github.com/PowerShell/PowerShell/blob/8e3861a64bfc5a64bbd84c9a7d351381b658ec6b/src/libpsl-native/src/getcurrentprocessorid.cpp)

I think you can easy add and use [getppid](https://linux.die.net/man/2/getpid)

**Comment by powercode** [comment]
getppid is just the parent of the current process.
I think I have to read /proc/pid/stat to get the ppid of a specific pid.

**Comment by iSazonov** [comment]
Yes, read /proc right direction.

**Comment by powercode** [comment]
I'm getting a test error when Import/Export-CliXml with process after adding the Parent property to Process.
Is there any way to opt out a property from clixml serialization?

**Comment by lzybkr** [comment]
I don't know why the tests are failing in CI. I tried your changes it it works for me locally.

You can try debugging in CI. On AppVeyor, you can follow these instructions:

https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
