### ISSUE TITLE
Unable to use Invoke-WebRequest or Invoke-RestMethod on a service with a self-signed cert

### ISSUE THREAD

**Issue by 0byt3** [PowerShell/PowerShell#2774]
I can't find a way in PowerShell Core to ignore certificate errors when using Invoke-WebRequest or Invoke-RestMethod. 
I can only find a way to do it on PowerShell 3-5 .

Here is a link to the same reported issue:
https://github.com/PowerShell/PowerShell/issues/1945

However, despite it being closed there is no fix/workaround. User ffeldhaus says something about a new variable $SkipCertificateCheckPreference and putting in $PSDefaultParameterValues.Add("Invoke-RestMethod:SkipCertificateCheck",$true) , but this does nothing for me.

*** Powershell Version
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.12
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      6.0.0-alpha
CLRVersion
PSEdition                      Core
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3

*** .NET Core Version
1.0.0-preview2-003133

Please help.

**Comment by rkeithhill** [comment]
Try alpha.13 that was released yesterday.  These two cmdlets now have a `-SkipCertificateCheck` switch parameter.

**Comment by 0byt3** [comment]
Fantastic.

Thanks.
