### ISSUE TITLE
single quote in here-string causes TerminatorExpectedAtEndOfString in V5.0

### ISSUE THREAD

**Issue by m8ram** [PowerShell/PowerShell#2780]
Steps to reproduce
------------------
```
$herestr=@"
'"'
"@
Write-Host $herestr
```

Expected behavior
-----------------
A string containing a single-quote, a double quote and another single quote should be printed to stdout.
According to Powershell "[about quoting rules](https://technet.microsoft.com/en-us/library/hh847740.aspx)":
A here-string is a single-quoted or double-quoted string in which quotation marks are interpreted literally.

Actual behavior
---------------
A TerminatorExpectedAtEndOfString  is thrown in version 5.0 (with version 2.0 the actual behaviour is as expected).
If I escape the last single quote with a backtick the behaviour is also as expected in V5.0

Environment data
----------------

Powershell version 5.0 (build 10586, revision 117) throws the exception.
In a Powershell version 2.0 it works as expected

Additional information
-------------------------
According to [feedback I received on superuser.com](http://superuser.com/questions/1148577/why-do-i-need-to-escape-the-last-single-quote-in-this-powershell-here-string) escaping the single quote is not the only way to work around this. Other options are:

> You can workaround this by putting extra space: $herestr =@"... or $herestr= @"...; or by enclosing in parenthesis: ($herestr=@"..."@)
The option of enclosing in parenthesis causes the here document to be echoed but I can confirm that these options work in V5.0 (build 10586, revision 117)

**Comment by iSazonov** [comment]
I don't see TerminatorExpectedAtEndOfString in latest builds of Windows and Powershell 6 but the problem persists as incomplete input.

**Comment by PetSerAl** [comment]
@iSazonov Try it like that:
```
iex "`$herestr=@`"`n'`"'`n`"@"
```
so it do not expect addition input.

**Comment by iSazonov** [comment]
@PetSerAl Thanks! You are right.

From[ about quoting rules](https://technet.microsoft.com/en-us/library/hh847740.aspx?f=255&MSPPError=-2147217396):
> A here-string contains all the text between the two hidden characters.
    In the here-string, all quotation marks are interpreted literally.
    For example:
>
>        @"
>        For help, type "get-help"
>        "@
>
>   The output of this command is:
>
>        For help, type "get-help"

Really a incomplete input is here.

In fact, this is a bug.
