### ISSUE TITLE
Add -NoWrap flag

### ISSUE THREAD

**Issue by idleberg** [PowerShell/PowerShell#2781]
By default, all output produced by PowerShell is wrapped at 80 characters.  Would it be possible to add a flag that disables this behaviour? There are cases when this makes parsing the output by third-party software much easier.

**Comment by iSazonov** [comment]
Could you clarify your question? Samples?

Powershell auto detect a console width. So you need configure a console.
Also you can do `Out-File -Width`

**Comment by idleberg** [comment]
Consider this simple example:

```
Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\NSIS' -Name InstallLocation).InstallLocation
```

Since there is no `HKLM:\` on Linux or macOS, PowerShell will report an error like this the following

```
Get-ItemProperty : Cannot find drive. A drive with the name 'HKLM' does not exi
st.

At /Users/me/here-is-a-very-long-path-that-will-ultimately-get-wrapped-after-80-
-characters/myScript.ps1:34 char:19
```

> Also you can do Out-File -Width

I don't want to wrap/unwrap the output generated by my scripts, but the default PowerShell output, such as error messages.

> Powershell auto detect a console width

I'm using iTerm2 with `bash` as my main shell. `bash` respects my window-width for its line-breaks, it's only `powershell` that doesn't (see screenshot below!) I also tested this using `fish` and `zsh`. 

![screen shot 2016-11-24 at 15 53 59](https://cloud.githubusercontent.com/assets/1504938/20602543/173f04ac-b25e-11e6-9d0d-9fda4395485c.png)

So maybe we should refer to this as a bug instead 😉

**Comment by idleberg** [comment]
I think we can close this issue. It turned out that `bash` works fine and `fish` didn't.

**Comment by idleberg** [comment]
I did some more testing at home. Everything works fine in `bash`. I forgot to restart iTerm2, so in my previous post, I was still running `fish` as my shell. In another, previously unmentioned case, I was spawning `powershell` in Node, where it also wrapped at 80 characters. By default, the Node console wraps at 80 characters, so this kinda makes sense. However, when spawning other executables, the output did not wrap at 80 characters.

**Comment by iSazonov** [comment]
@idleberg Thanks for tests! 
I believe that you should close this issue and open a new one if you think that Powershell is not working as it should. Please only specify the exact Powershell version, your system's name and version, environment (shell and so on), and your test actions. The more precisely you describe the situation, the easier it will be to implement the fix.
