### ISSUE TITLE
Cannot Import-Module AzureRM on PowerShell Core

### ISSUE THREAD

**Issue by kim0** [PowerShell/PowerShell#2784]
Steps to reproduce
------------------
* Install powershell on macOS, then `install-module azurerm`
* Attempt to `import-module azurrm.Dns` or any other module

Expected behavior
-----------------
* Module is successfully imported

Actual behavior
---------------
* Exception as below
```
PS /Users/kim0> Import-Module AzureRM.Dns
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module AzureRM.Dns
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.13
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ljt91** [comment]
@kim0 - Check this out https://blogs.technet.microsoft.com/jessicadeen/azure/getting-started-with-powershell-core-and-azurerm-modules-on-ubuntu-and-os-x/

Looks like there's only a few of the modules are currently supported on macOS.

AzureRM.NetCore.Preview
AzureRM.Profile.NetCore.Preview
AzureRM.Resources.NetCore.Preview

**Comment by kim0** [comment]
Hi Folks, did anyone have a chance to improve this situation? I would really love to start playing with azurerm form PS on OSX .. Thanks!

**Comment by joeyaiello** [comment]
We're working with the Azure PowerShell team to work through this. I don't want to offer a timeline right now, but it's definitely a high priority for us.

**Comment by CyTheGuy** [comment]
I get this same issue with Import-Module AzureRM.Storage on his same versions.

```
PS /Users/cdickey.ctr> Import-Module AzureRM.Storage
VERBOSE: Loading module from path
'/usr/local/microsoft/powershell/6.0.0-alpha.18/Modules/AzureRM.Storage/2.8.0/AzureRM.Storage.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path
'/usr/local/microsoft/powershell/6.0.0-alpha.18/Modules/AzureRM.Storage/2.8.0/Microsoft.Azure.Commands.Management.Storag
e.format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module AzureRM.Storage.
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module AzureRM.Storage
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by Flodu31** [comment]
Hello,
I've the same problem:

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Any idea of the date when the new AzureRM module will be released?
Thanks.
Florent

**Comment by iSazonov** [comment]
@Flodu31 A few days ago PowerShell Core was moved to .Net Core 2.0 - this paved the way for support of many old and new modules. Now many teams can surprise us support PowerShell Core in any time. I believe AzureRM will be one of the first.

**Comment by SteveL-MSFT** [comment]
AzureRM port to CoreCLR has a different name: [AzureRM.NetCore.Preview](https://www.powershellgallery.com/packages/AzureRM.NetCore.Preview/0.3.4).  Try this one.  It's a work in progress, but this is the one the Azure team will support on PSCore6.

**Comment by bilalaslamseattle** [comment]
Sigh. Tried this October 2017 and no luck.

```
> Import-Module AzureRM.KeyVault
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module AzureRM.KeyVault
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by SteveL-MSFT** [comment]
@bilalaslamseattle unfortunately, it looks like KeyVault isn't part of https://www.powershellgallery.com/packages/AzureRM.Netcore yet

**Comment by iSazonov** [comment]
@SteveL-MSFT Maybe add review and status of most popular modules in our docs? Wiki?

**Comment by SteveL-MSFT** [comment]
@joeyaiello we should have something about that in our final release notes
