### ISSUE TITLE
Enable Catch by FullyQualifiedErrorID

### ISSUE THREAD

**Issue by kittholland** [PowerShell/PowerShell#2791]
The FullyQualifiedErrorID as described in https://msdn.microsoft.com/en-us/library/ms714465(v=vs.85).aspx is used: "for scripts that handle specific error conditions with specific error handlers."

Currently this can be accomplished with conditional logic such as a Switch ($PSItem.FullyQualifiedErrorID) inside a general Catch block, but it would be nice if the FullyQualifiedErrorID were treated as a first class property for catching errors.

This property is generally more specific than the exception type and always includes the Cmdlet/Function name that generated it. It is easy to create your own using Write-Error with the string ErrorID parameter.

**Comment by rkeithhill** [comment]
Perhaps this is an area where PowerShell could borrow from C# and have exception handling filters e.g.
```
catch [Exception] if ($PSItem.FullyQualifiedErrorID -eq ...) {
```
Although that is starting to feel a bit advanced for a shell scripting language.  :-)

**Comment by kittholland** [comment]
to me, a possible simple syntax would be:

catch 'NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand'
{ }

**Comment by lzybkr** [comment]
I like this idea and the proposed syntax.

Some thoughts/questions:

* Multiple strings should be allowed, like `catch "aaa","bbb"`
* Should we support wildcards, e.g. `catch "*GetServiceCommand"`

**Comment by briandrennan** [comment]
My personal sentiment is that multiple strings should be allowed, and the input type should probably be `System.String[]`. Wildcards would also provide a very nice shortcut syntax, per the example you put for `catch "*GetServiceCommand"`.

**Comment by iSazonov** [comment]
` catch "aaa","bbb" ` say nothing about `FullyQualifiedErrorID` 😕 Why not filter by any other properties of exception? Like @rkeithhill 's idea:
`try {} catch filter() do {} `

**Comment by lzybkr** [comment]
Things may have changed, but LINQ expression trees did not support `filter` when I last looked. They have support in the api, but no code generation support, I believe due to issues in the JIT.

That doesn't mean we couldn't implement exception filtering anyway, but it might not work like it does in C# (e.g., unwinding behavior might differ).

I think using an exception filter will be less obvious to many folks - it's more verbose. Of course it's more powerful, but I doubt that power is needed in PowerShell much.

**Comment by iSazonov** [comment]
Another option. The `catch` expects types and we cannot break it. Therefore we need a prefix to say that  next is not a type, but something else. It was also good for UX to use a tab completion.

```powershell
try {}
catch : FullyQualifiedErrorID  "aaa", "bbb" {}
catch ( FullyQualifiedErrorID )   "aaa", "bbb" {}

```

**Comment by JustinGrote** [comment]
@iSazonov I know this is an ancient issue but it annoyed me enough that there wasn't a short way to do this I looked it up. Was there any movement on this or is it still up for grabs?

**Comment by iSazonov** [comment]
> Was there any movement on this or is it still up for grabs?

It is still up for grabs. You can continue the discussion.

**Comment by JustinGrote** [comment]
In that case do we really need a special syntax? Why not just take the fully qualified as a string and determine logic based on whether it is a type definition or a string?

catch `[exception]` {

}

vs 

catch 'FullyQualifiedErrorId' {

}

**Comment by iSazonov** [comment]
I think PowerShell parser would allow this. 
https://github.com/PowerShell/PowerShell/blob/c406f9fe68b7bee1bc4695f70d9dba86b3061ad4/src/System.Management.Automation/engine/parser/Parser.cs#L5450
