### ISSUE TITLE
Add Windows container image for PowerShell Core

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2793]
On the Docker Hub, there are automated builds for Linux container images, however there's no container image to run PowerShell Core on the Windows platform. We should provide a new container image tag for `microsoft/powershell:nano`, or similar.

![image](https://cloud.githubusercontent.com/assets/466713/20677890/eadc47ac-b551-11e6-84b3-d2d9f29b2711.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by SteveL-MSFT** [comment]
I thought https://github.com/PowerShell/PowerShell/pull/2495 addressed this?  @brycem

**Comment by brycem** [comment]
Correct - We have Dockerfiles to install the current Powershell release here:  https://github.com/PowerShell/PowerShell/tree/master/docker/release.  No nightly\daily build support yet.

**Comment by SteveL-MSFT** [comment]
@brycem are you working on getting nightly/daily build support?

**Comment by brycem** [comment]
Before I I left on vacation, @raghushantha and I were blocked on a Win10Sdk bug.  Looks like they may have a private fix to take a look at.  Have you done this already Raghu?

**Comment by TravisEz13** [comment]
Images are up:
![image](https://cloud.githubusercontent.com/assets/10873629/24572052/666f3080-162a-11e7-9c4b-ec998ec1a79a.png)

**Comment by brycem** [comment]
@TravisEz13, @raghushantha  - The Jenkins deployment would be an easy place to automate the build process for these images going forward:  https://azopenci.westcentralus.cloudapp.azure.com/

**Comment by TravisEz13** [comment]
@brycem The build is already automated.  Let's please discuss this offline.
