### ISSUE TITLE
We don't upload all PR artifacts in AppVeyor CI

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2794]
Steps to reproduce
------------------

Take any PR build, i.e.
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-alpha.12-1515

Expected behavior
-----------------

We build all artifacts

Actual behavior
---------------

We fail to build them and don't fail the build
![image](https://cloud.githubusercontent.com/assets/816680/20679110/6396e728-b54e-11e6-8c02-9be3d0596382.png)

**Comment by iSazonov** [comment]
@TravisEz13 Seems we could close the old Issue.

**Comment by TravisEz13** [comment]
Agreed
