### ISSUE TITLE
Updating progress pane using timer causes race condition that would randomly crash powershell

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#2800]
With PR #2640, a timer is used to trigger updating progress pane every 100 ms to improve progress record rendering performance (commit: https://github.com/PowerShell/PowerShell/commit/760a9c2997148f32a0b763165a32647abe49b985). Before the change, `_progPane.Show` and `_pendingProgress.Update` used to be called on the same thread, and now they will be called on different threads. This causes race conditions -- **for all type members that are used by both methods, they might be changed at the same time and the states may be corrupted.**

The screenshot below is from a recent CI build on master branch. The exception was raised from [RenderHelper](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs#L763), and that was because it was actually enumerating over `PendingProgress._topLevelNodes` and at the same time new node was being added to/removed from `_topLevelNodes` by [Update](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs#L60).

![image](https://cloud.githubusercontent.com/assets/127450/20699550/bd1d52e6-b5bc-11e6-862d-cf3a302d8fe7.png)

/cc @iSazonov @lzybkr

**Comment by iSazonov** [comment]
@daxian-dbw  Is the #2771 addressed this?

**Comment by iSazonov** [comment]
Strange... I specially made restart the timer after completing `_progPane.Show` to exclude collisions.

**Comment by lzybkr** [comment]
Does https://github.com/PowerShell/PowerShell/pull/2771 fix this?

**Comment by daxian-dbw** [comment]
Ah, I didn't know we already had an issue for this: #2756.
However, `_topLevelNodes` is not the only type member that is shared between the main pipeline thread and `_progPane.Show` running on the timer thread, `_rawui` and `_progressRegion` are another 2 examples. I think we need to analyze all those members in case any of them have similar race conditions.
