### ISSUE TITLE
Powershell hangs for a while on close (when X button pressed)

### ISSUE THREAD

**Issue by badgh** [PowerShell/PowerShell#2804]
Steps to reproduce
------------------
Launch Powershell, then close with standard X button

Expected behavior
-----------------
Quick exit

Actual behavior
---------------
Powershell hangs for at least 5 sec before exit (It should be noted that when I type "exit" in PS console itself, it exits instantly, which is what I want)

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

I tried ngen script from here http://superuser.com/a/777658
But it didn't help.
Maybe the issue began after installing Windows 10 Anniversary Update, although I'm not sure.

**Comment by SteveL-MSFT** [comment]
@badgh I'm not able to repro this on my Win10 machine.  I start powershell, then click 'x' to close and it exits immediately.  Does this repro with cmd on your machine?

**Comment by iSazonov** [comment]
May the cause due to third-party module?

**Comment by mak42** [comment]
Same Problem here after installing Windows 10 Anniversary Update, if I close powershell via exit command it quits instant. No third-party modules installed. Cmd does not have this problem, only powershell.

**Comment by badgh** [comment]
I agree with @mak42, the issue began after install of Windows 10 Anniversary Update, no third-party installed (it began exactly when I made clean install and further anniversary update of the system), cmd has no similar problem.

I tried to google this problem. In fact, the issue very much resembles https://github.com/lzybkr/PSReadLine/issues/17, and they suggest install ConsoleZ, I do not want install 3rd party consoles. Their issue was closed with the words 

> Closing - there is unlikely anything I can do about this. I guess you need to type exit if you want to exit faster.

which is today unacceptable, since as far as I understand PSReadline now is part of standard Powershell 5.0 and should work properly by default.

**Comment by mak42** [comment]
I also experience some weird artifacts if I use auto-complete tab. Apparently it disappears to fast to make a screenshot and if I record a video this artifacts aren't visible.

**Comment by SteveL-MSFT** [comment]
@badgh agree that this is unacceptable, we'll need to investigate

**Comment by mak42** [comment]
If we can support you in any way, please let us know.

**Comment by iSazonov** [comment]
Please make simple test: remove PSReadline and check whether the problem persists.

**Comment by mak42** [comment]
I did remove the PSReadline Folder in Program Files restarted Power Shell, apparently that didn't seem to help.

**Comment by iSazonov** [comment]
Let's check that the module isn't loaded. You can check loaded modules by means of `Get-Module` and unload the module by `Remove-Module PSReadline`.

**Comment by lzybkr** [comment]
lzybkr/PSReadline#17 was fixed a long time ago, so unless you're somehow using a really old version of PSReadline, I would assume something else is going on.

If you can repro in a debugger, maybe you can capture a stack trace for us - just break into the debugger before the process dies, hopefully we can get a useful stack from that.

Alternatively, maybe we can figure out what's going on with an ETW trace that you collect using [WPR](https://blogs.technet.microsoft.com/yongrhee/2015/08/04/windows-performance-recorder-wpr-exe-now-inbox-in-windows-10/) or [PerfView](https://github.com/Microsoft/perfview/releases).

@mak42 - if you are seeing artifacts during tab completion and can provide sufficient information to investigate or repro (e.g. capture a video), please open a new issue on [PSReadline](https://github.com/lzybkr/PSReadline/issues).

**Comment by pmaillot** [comment]
I have the same issue; Exit with typing an "exit" command quits immediately while exit with clicking on the "X" sign at top right of the Powershell window takes about 5 to 10 seconds, with a message saying (not responding) in the window banner; No suspicious event reported in the event logs. I have no idea where this comes from, but it did start (several months ago) after installing one of WIndows (insider?) updates.

**Comment by lzybkr** [comment]
Like @SteveL-MSFT - I can't reproduce this issue.  With three people reporting they can repro, hopefully someone can do some investigation to give us a clue what could be happening.

It would be helpful to know If you can repro with Win+R then `powershell -noprofile -command "sleep 300"`, then click on the X.  If that repros, I think we can eliminate the any modules (including PSReadline, which would not be loaded in this scenario) or something in your profile causing problems.

**Comment by pmaillot** [comment]
Just tried the command your proposed. Same behavior, using “x” the powershell windows takes 5 to 10 seconds to quit.

 

-Patrick

**Comment by SteveL-MSFT** [comment]
@pmaillot this doesn't repro with a cmd window, correct?

**Comment by pmaillot** [comment]
I confirm this does not happen using a cmd window.

-Patrick

**Comment by iSazonov** [comment]
All good on Windows 10 5.1.14971.1000 

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14971.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14971.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```powershell
PS C:\Program Files\PowerShell\6.0.0.13> $PSVersionTable

Name                           Value
----                           -----
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.13
PSEdition                      Core
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
SerializationVersion           1.1.0.1
CLRVersion
BuildVersion                   3.0.0.0

```

**Comment by badgh** [comment]
Is there a way to totally reinstall powershell (clean and then install this new version 5.1.14971.1000)?

**Comment by mak42** [comment]
I'll tried upgrading to a different windows build but apparently that didn't work still shows "Build 14393.rs1_release_inmarket.161102-0100". Also I tried using PS Version 6 Alpha with no success. I think I will do a full reinstall of windows cause it's the only machine where I have this problem, maybe that will help.

**Comment by iSazonov** [comment]
May be install new Windows 10 Preview build.

**Comment by badgh** [comment]
I totally reinstalled Windows, now it's ok for me. But I suppose the problem is maybe due to some Antivirus activity burden. For example, I installed and uninstalled AVG Free Antivirus, and noted that it causes some delay to Powershell closing (although not as bad as it was initially when I asked the question).

**Comment by SteveL-MSFT** [comment]
@badgh good to hear, I'll resolve this as external for now unless we have something we can investigate.  thanks.

**Comment by pmaillot** [comment]
Nice catch!

 

Reading your post and not changing anything to my PC configuration, 

I disabled AVG:

Exit from powershell (using the x button) is instantaneous.

Re-enabling all but the “Computer Protection” (the leftmost option of AVG GUI window)

Exit from powershell (using the x button) is instantaneous.

Re-enabling the “Computer Protection” (the leftmost option of AVG GUI window)

Exit from powershell (using the x button) hangs again for 5 to 10 seconds before being effective.

 

So it looks more like an AVG issue than a Windows powershell problem.

 

Thanks for pointing to this.

 

-Patrick

**Comment by badgh** [comment]
@pmaillot you are welcome! For me it was specifically "AVG protection" (or something called like that), which I uninstalled from Control Panel (while keeping AVG itself), and the problem disappeared, although I'm not sure cause details may vary on each Windows and AVG install...

**Comment by pmaillot** [comment]
Issue reported onto the AVG support forum.

 

-Patrick

 

From: Patrick-Gilles Maillot [mailto:patrick.maillot@gmail.com] 
Sent: Tuesday, December 20, 2016 7:24 PM
To: 'PowerShell/PowerShell'; 'PowerShell/PowerShell'
Cc: 'Mention'
Subject: RE: [PowerShell/PowerShell] Powershell hangs for a while on close (when X button pressed) (#2804)

 

Nice catch!

 

Reading your post and not changing anything to my PC configuration, 

I disabled AVG:

Exit from powershell (using the x button) is instantaneous.

Re-enabling all but the “Computer Protection” (the leftmost option of AVG GUI window)

Exit from powershell (using the x button) is instantaneous.

Re-enabling the “Computer Protection” (the leftmost option of AVG GUI window)

Exit from powershell (using the x button) hangs again for 5 to 10 seconds before being effective.

 

So it looks more like an AVG issue than a Windows powershell problem.

 

Thanks for pointing to this.

 

-Patrick

**Comment by mak42** [comment]
Can confirm, I added powershell.exe to AVG Exceptions now the problem is gone. Thanks for the Tip 👍
