### ISSUE TITLE
Get-Help Needs a -Module parameter to list all the help topics for the specified module

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#2810]
The primary way I discover what commands a module provides is to run `gcm -m pester`.  I really want a way to find all the help topics available for a module.  Command help isn't so hard to find but the about topics a module exposes are harder to discover.  Plus there is a nice symmetry and transfer of learning if I could execute `man -m pester`.  

BTW you can use the -Name parameter but it doesn't seem to list everything.  For example `Get-Help -Name Pester` fails to list the `about_should`, `about_Mocking`, `about_TestDrive`, `about_BeforeEach_AfterEach` help topics.

**Comment by iSazonov** [comment]
Do you want to get something like `gcm -m pester | get-help` ?

**Comment by rkeithhill** [comment]
No, not really.  `about_*` may be listed directly in ModuleInfo but the information can be found easily enough:
```powershell
25> Get-Module pester | Foreach { Get-ChildItem $_.ModuleBase -recurse about_*.txt} | 
                        Foreach {$_.BaseName -replace '\.help',''} | Select-Object -Unique | Sort-Object
about_BeforeEach_AfterEach
about_Mocking
about_Pester
about_should
about_TestDrive
```

**Comment by joeyaiello** [comment]
I was just actually *just* thinking about this other day, and I think it would be really useful. 

That being said, I think we should respect ModuleInfo and not try and do any crazy heuristics like you've proposed. So really, I think this parameter should be just shorthand on `Get-Module pester | Get-Help`, which currently returns the following:

```
Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Invoke-Pester                     Function  pester                    Invokes Pester to run all tests (files contain...
about_Pester                      HelpFile                            Pester is a BDD based test runner for PowerShell.
```

**Comment by rkeithhill** [comment]
Then is there a way we can get `Get-Module pester | Get-Help` to return the other HelpFile (`about_*) topics?  It is a real shame not to make those other Pester help files more discoverable.

**Comment by iSazonov** [comment]
List all help files in module manifest.

**Comment by rkeithhill** [comment]
In which field?  I'm looking at a PSD1 I just created with New-ModuleManifest.  There is no obvious field for help files.

**Comment by iSazonov** [comment]
@rkeithhill Sorry I put it vaguely. I had in mind that we need a _new field_ in psd1 file where we can specify all help files of module. If this information will be cached in ModuleInfo Get-Help will work fast.

**Comment by kilasuit** [comment]
I would be more inclined to push people to actually make use of the File list field in the manifest than to add another field to the manifest and risk any further version specific breaking changes (like CompatiblePSEditions) 

Once the file list in the manifest has all the files listed within there then I don't think that it would then be much additional logic within Get-Help to equate for either adding in a module parameter or when a PSModuleInfo object is passed down the pipeline, to then parse the File List property for any about_* files that are included with the module. 

We could also add an additional property to PSModuleInfo that would only show any found about_* files within a module.
