### ISSUE TITLE
Invoke-WebRequest hangs in some cases, unless -UseBasicParsing is used

### ISSUE THREAD

**Issue by ilgrank** [PowerShell/PowerShell#2812]
**Invoke-WebRequest hangs, 100% of the times, when processing webpages containing specific elements.**

Several bug reports on this same topic have been opened on Microsoft Connect in 2014 and 2015 and Microsoft UserVoice later on, but since they have been filed on different platforms and with different topics, Microsoft failed to notice they were all referring to the same issue, so I am consolidating those reports and filing a bug report here on Github:

Steps to reproduce
------------------
```
$URL='http://windows.microsoft.com/en-US/windows-8/system-requirements'
(Invoke-WebRequest -Uri $URL).parsedhtml
```

other URLs to try:
```
https://github.com/hluk/CopyQ/releases
http://www.heise.de
http://www.bloomberg.com/professional/downloads/
```

Expected behavior
-----------------
Invoke-Webrequest should parse the page and populate several properties, like 
```
ParsedHtml
Links
```
and others.

Actual behavior
---------------
Invoke-WebRequest hangs, sometimes spitting out the message:

**`Vector smash protection is enabled`**

Environment data
----------------

Verified on PowerShell4 on Windows 8.1:
```
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.16394
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

and PowerShell5 on Windows 10 
```
PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

For sake of completeness, the abovementioned bug reports from UserVoice are reported here:

[https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13890669--url-http-www-bloomberg-com-professional-down ](url)
[https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11515881-invoke-webrequest-hangs-freeze-at-many-websites](url)
[https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/15692703-invoke-webrequest-returned-object-hangs-when-acces ](url)

[](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088744-invoke-webrequest-hangs-in-some-cases-unless-use)

**Comment by MaximoTrinidad** [comment]
This incident needs to be submitted to the Windows UserVoice as this is for PowerShell Open Source.  

But interesting enough, in PowerShell v6.0.0-alpha.13, in the (Invoke-WebRequest -Uri $URL) the property ".parsedhtml" doesn't exist.

OS = Windows 10 Insider Preview 14971
PS C:\Program Files\PowerShell\6.0.0.13> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.3
PSEdition                      Core
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.13
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

See attached images

![w_webreq_01_2016-11-30_11-21-30](https://cloud.githubusercontent.com/assets/19892435/20760934/57eb97d2-b6ef-11e6-970c-e8d20352dd60.png)

![w_webreq_02_2016-11-30_11-21-30](https://cloud.githubusercontent.com/assets/19892435/20760938/5d06fd88-b6ef-11e6-9a69-fa10a5554e86.png)

**Comment by ilgrank** [comment]
Thanks for the quick reply
I had hope that what MS POSH could not do, PSOS could have accomplished :)
Alas, Microsoft does not listen very actively to bug reports :(

**Comment by MaximoTrinidad** [comment]
Hey @ilgrank , I understand.  The good thing about this is the contribution you provide. There are lots of MVP's looking at this all the time and we can (sort of) redirect the effort to where is needed.  You did Great in providing references to UserVoice posts.  

Don't give us on us!  We'll do whatever we can to continue helping in improving PowerShell.
:)
Maximo Trinidad

**Comment by ilgrank** [comment]
Thanks @MaximoTrinidad , I really appreciate the effor of all the people here 👍 
and of course I hope, as you say, that this will gather the interest of enough people for Microsoft to notice.
I also cross-referenced this issue on Uservoice, so that either side will know :)

**Comment by MaximoTrinidad** [comment]
Greatly Appreciated!
Max

**Comment by SteveL-MSFT** [comment]
This doesn't repro with PSCore as CoreCLR has a different web client class that doesn't exhibit the same behavior.

**Comment by ilgrank** [comment]
Hi @SteveL-MSFT : As @MaximoTrinidad  suggested some day ago, it seems that PSCore is lacking (among other things) the .AllElements and .ParsedHtml properties.
One of the greatest (IMHO of course) features of (MS) Invoke-WebRequest is the ability to parse web pages in order to return addressable object.
It is a very useful feature, and it is a shame PSCore is missing it :(

**Comment by SteveL-MSFT** [comment]
@ilgrank please open a separate issue for .allelements and .parsedhtml properties

**Comment by ilgrank** [comment]
Thanks @SteveL-MSFT 
I opened a new issue here: [](https://github.com/PowerShell/PowerShell/issues/2867)

**Comment by TerrorFactor** [comment]
Are there any updates on this? Possible workaround?

**Comment by SteveL-MSFT** [comment]
-UseBasicParsing to avoid hang, the other issue above is to implement parsedhtml

**Comment by whiggs** [comment]
Well, unfortunately, using the "-usebasicparsing" parameter removes the "forms" property from the returned object, thus making the workaround just that: a temporary non-solution.  This problem needs to be fixed.  It is shameful that Microsoft has not fixed this in over 2 years.  Shameful, microsoft.

**Comment by TerrorFactor** [comment]
Maybe useful for some people, but I found a way to work around the issue and have a useable html element:
```
Function ConvertTo-NormalHTML {
    param([Parameter(Mandatory = $true, ValueFromPipeline = $true)]$HTML)

    $NormalHTML = New-Object -Com "HTMLFile"
    $NormalHTML.IHTMLDocument2_write($HTML.RawContent)
    return $NormalHTML
}
```

It's a bit silly, but at least you can do something with the html.

**Comment by efd7887** [comment]
> Well, unfortunately, using the "-usebasicparsing" parameter removes the "forms" property from the returned object, thus making the workaround just that: a temporary non-solution. This problem needs to be fixed. It is shameful that Microsoft has not fixed this in over 2 years. Shameful, microsoft.

Yeah its pretty terrible.  I have a task on a server that runs an XML import file for Cisco Unified Messaging and it only runs once a month.  Looking at the history it has failed 88% over the past 8 months because of this very issue.
