### ISSUE TITLE
Import-Module tab completion not working when inside $env:PSModulePath

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#2813]
_From @Aculeo on November 30, 2016 12:44_

When trying to import a module tab completion isn't working if my current working directory happens to be the same as the module path defined in `$env:PSModulePath`. When I hit tab twice I can see that all modules are listed twice.

**PowerShell Version:**
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
PSReadLine is version 1.2.

_Copied from original issue: lzybkr/PSReadLine#477_

**Comment by ThomasNieto** [comment]
This doesn't look to be an issue anymore. Tested on 7.1 preview 5 with PSReadline 2.1 beta 2.

**Comment by ThomasNieto** [comment]
@iSazonov can you please check this one out and see if it can be closed? I am not able to reproduce on 7.1 RC1.

**Comment by iSazonov** [comment]
I can not reproduce.

**Comment by ThomasNieto** [comment]
@iSazonov @vexx32  since it cannot be reproduced can this issue be closed?

**Comment by iSazonov** [comment]
It seems it was fixed in a PR related to PSModulePath.
