### ISSUE TITLE
.msi uninstall leaves an empty version folder and start menu entry (for alpha.10)

### ISSUE THREAD

**Issue by khansen00** [PowerShell/PowerShell#2815]
Steps to reproduce
------------------
uninstall a alpha.10 release 

Expected behavior
-----------------
expected path is completely removed

Actual behavior
---------------
empty folder remains

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
Could you test with the latest version 13?
