### ISSUE TITLE
.msi alpha.13 does not provide a start menu access point

### ISSUE THREAD

**Issue by khansen00** [PowerShell/PowerShell#2816]
Steps to reproduce
------------------
install alpha.13 using .msi - when already have alpha.10 on the box.

Expected behavior
-----------------
a start menu icon for alpha.13

Actual behavior
---------------
no start menu option

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by lzybkr** [comment]
I see an item:

![image](https://cloud.githubusercontent.com/assets/2148248/20774889/4594ab82-b70d-11e6-8f2c-a46cf04628c8.png)

**Comment by MaximoTrinidad** [comment]
I'm confuse! Which OS is this? A server or client? I'm on Windows 10 Insider Preview 14971.

Do you mean right-click on PowerShell_6.0.0.13 and "pin to start"? I can find it and do a "Pin to Start".
:)

![p6start_2016-11-30_19-54-29](https://cloud.githubusercontent.com/assets/19892435/20777778/4597fec0-b737-11e6-9a3e-085fa31b6dce.png)
