### ISSUE TITLE
PowerShell not able to run a script file from bash prompt

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2818]
Steps to reproduce
------------------
I created a script file test.ps1 with just 'dir' in it.

See attached image for result.

Expected behavior
-----------------
List the directory list

Actual behavior
---------------
Either "Aborted (core dumped)" or "test.ps1 not recognized"

Environment data
----------------
OS = Ubuntu 16.04.1 LTS

```powershell
PS /home/maxt> $PSVersionTable                                                  

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.13                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1        

```
![powershellbashscripterr](https://cloud.githubusercontent.com/assets/19892435/20777625/2dc55d2a-b736-11e6-9f5d-1ae53f6ac637.png)

**Comment by n3rdopolis** [comment]
Try
```
powershell -c test.ps1
```

**Comment by MaximoTrinidad** [comment]
Thanks @n3rdopolis,

I did try that one. But, you got me closer. 

I realized I didn't try:
powershell -c ./test.ps1
or 
powershell ./test.ps1

They both work.  The issue started when I was looking at the powershell -help which doesn't show an example to run a script file. This example need to be added to the help.

![powershellbashscript](https://cloud.githubusercontent.com/assets/19892435/20822891/a7520ea4-b81c-11e6-932e-d54fd95ee5a0.png)

![powershellbashscript1](https://cloud.githubusercontent.com/assets/19892435/20822893/ae3fb5c2-b81c-11e6-82cf-8e1f7dff2e6d.png)

**Comment by n3rdopolis** [comment]
'-c' is short for '-Command'

**Comment by MaximoTrinidad** [comment]
Yes! I knew that.  But then again, that sample should be included in the "powershell -help" for beginners.
Just a suggestion.

:)

**Comment by vors** [comment]
`-Command` can do the job, but there is a whole different dedicated flag `-File` for that.
It will work without the `./` for the relative path.

```
powershell -File foo.ps1
```

**Comment by vors** [comment]
On Unix, you can see all the flag with `man powershell`.

**Comment by MaximoTrinidad** [comment]
Thanks! I got to use the Linux way.  I'm trying to get use to it.
:)

**Comment by vors** [comment]
Seems like the question is answered.
