### ISSUE TITLE
Why these two lines code results different?

### ISSUE THREAD

**Issue by jianglibo** [PowerShell/PowerShell#2821]
Steps to reproduce
------------------
```
($myenv.boxGroup.boxes | % {$_.roles} | ? {($_ -match $MYSQL_MASTER) -and ($_ -notmatch $MYSQL_REPLICA)}).Count | Should Be 1

($myenv.boxGroup.boxes | ? {($_.roles -match $MYSQL_MASTER) -and ($_.roles -notmatch $MYSQL_REPLICA)}).Count | Should Be 1
```
Expected behavior
-----------------
The second line should be 1 too.

Actual behavior
---------------
The Second line results in 0

Environment data
----------------
Name                           Value
----                           -----
_                              /usr/bin/powershell
HISTCONTROL                    ignoredups
HISTSIZE                       1000
HOME                           /root
HOSTNAME                       localhost.localdomain
JAVA_HOME                      /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b15.el7_2.x86_64/jre
LANG                           en_US.UTF-8
LESSOPEN                       ||/usr/bin/lesspipe.sh %s
LOGNAME                        root
LS_COLORS                      rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01...
MAIL                           /var/spool/mail/root
PATH                           /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
PSMODULEPATH                   /root/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/6.0.0-alpha.13/Modules
PWD                            /root
SELINUX_LEVEL_REQUESTED
SELINUX_ROLE_REQUESTED
SELINUX_USE_CURRENT_RANGE
SHELL                          /bin/bash
SHLVL                          1
SSH_CLIENT                     192.168.33.1 59321 22
SSH_CONNECTION                 192.168.33.1 59321 192.168.33.110 22
SSH_TTY                        /dev/pts/0
TERM                           xterm
USER                           root
XDG_RUNTIME_DIR                /run/user/0
XDG_SESSION_ID                 64

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.13
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by lzybkr** [comment]
You can debug this yourself to understand what is happening if you remove the `.Count` and instead look at the actual objects you are counting.

For this line:
```powershell
($myenv.boxGroup.boxes | % {$_.roles} | ? {($_ -match $MYSQL_MASTER) -and ($_ -notmatch $MYSQL_REPLICA)}).Count | Should Be 1
```
You count the number of roles that match your filter because you enumerate the roles before your filter.

For this line:
```powershell
($myenv.boxGroup.boxes | ? {($_.roles -match $MYSQL_MASTER) -and ($_.roles -notmatch $MYSQL_REPLICA)}).Count | Should Be 1
```
You count the number of boxes that match your filter because you filter on the boxes.

**Comment by jianglibo** [comment]
Yes, what you said was definitely right. What I thought wrong is prejudging the pipe result to be a collection.
Follow your way, I got the output.
```
line1 result: NAMENODE,MYSQL_MASTER,RESOURCEMANAGER
line2 result: @{id=1736704; ip=192.168.33.110; name=box1; hostname=a0.host.name; roles=NAMENODE,MYSQL_MASTER,RESOURCEMANAGER; dnsServer=192.168.2.60; ips=; ports=; boxRoleConfig=}
```
psobject has no Count property, so it just return null.
I should rather use TrueFalse detection instead of count.
