### ISSUE TITLE
Input variable tracking and validation

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2826]
There are a number of potential script vulnerabilities associated with unvalidated input variables such as code injection.

One way to mitigate this is for PowerShell to do input variable tracking.  Any function or script input variable is considered "tainted" or "untrustworthy" if it has not been validated.  Validation can occur with an input parameter validation attribute or via custom code that removes the "untrustworthy" mark on the variable.  The validation should include any quote escaping needed to prevent code injection.

If an "untrustworthy" variable is used then this should result in a terminating exception.  It is not clear to me if this should be default behavior or opt-in via strict mode or something.

The "untrustworthy" mark must follow the variable through manipulations and assignments so that any derived variable is also marked "untrustworthy".

**Comment by PaulHigin** [comment]
Dongbo, I have assigned this to you since you have started work on this.

**Comment by daxian-dbw** [comment]
The first part of the work has been checked in our internal source depot. It covers tracking values assigned to global/module scope variables.

**Comment by daxian-dbw** [comment]
Unsign myself for now as we are asked to focus on the `beta1` milestone issues.

**Comment by iSazonov** [comment]
> One way to mitigate this is for PowerShell to do input variable tracking. 

How could we detect `input variable`? It would be very expensive to check every variable copied to current scope.
