### ISSUE TITLE
Update ISE to include windows for local variables and callstack during debugging

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#2829]
The ISE would be a much better debugging environment if it provided Variable and Callstack windows.  It would also be good to have a separate Output window for capturing output.  Currently everything is routed to the ISE console window and the information gets confused in the different spews.

**Comment by SteveL-MSFT** [comment]
@PaulHigin probably better to open this issue here https://github.com/PowerShell/PowerShellEditorServices/issues

**Comment by rkeithhill** [comment]
PSES is UI agnostic.  It is meant to be used as a "backend" service for various editors (eventually).  Unfortunately, I think the only place for ISE feedback ATM is UserVoice.  https://windowsserver.uservoice.com/forums/301869-powershell/category/148050-ise-and-tooling

**Comment by SteveL-MSFT** [comment]
At this point, there are no plans to add features to ISE (ISE can't be Open Source nor cross platform).  Our strategy is to improve Editor Services and integration (primarily VSCode at the moment) to address experience gaps.

**Comment by PaulHigin** [comment]
Ok.  I'll close this issue for ISE.
