### ISSUE TITLE
Leverage new API for creating symlink without administrator privileges on Windows

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#2845]
Just saw this get posted today: https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/

We should opt-in to this API so that we're uniform across all platforms in allowing non-admins to create links. 

Steps to reproduce
------------------
Try to create a symlink as a non-admin. You'll get a permission denied. 

Expected behavior
-----------------
(as non-admin)
```powershell
PS C:\temp> New-Item -type SymbolicLink -Path link -Value source

    Directory: C:\temp
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l        12/5/2016   6:39 PM              0 link
```

Actual behavior
---------------
```powershell
PS C:\temp> New-Item -type SymbolicLink -Path link -Value source
New-Item : Administrator privilege required for this operation.
At line:1 char:1
+ New-Item -type SymbolicLink -Path link -Value source
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\temp\source:String) [New-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : NewItemSymbolicLinkElevationRequired,Microsoft.PowerShell.Commands.NewItemCommand
```

Environment data
----------------

All versions of Windows PowerShell 5.x and PowerShell Core 6.0.

**Comment by iSazonov** [comment]
Will the API be ported on Windows 7/8?

**Comment by andschwa** [comment]
@iSazonov no, and what's more, adding the flag to builds < 14972 will cause an invalid parameter error (according to [this thread](https://cygwin.com/ml/cygwin/2017-04/msg00305.html)). That said, the flag can be conditionally added after checking the current build.

**Comment by dilijev** [comment]
This issue still repros in RS4 build 17134

**Comment by yhvicey** [comment]
It's already two years after the [feature](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/) is released. Is there any update on this feature?

**Comment by nu8** [comment]
https://github.com/PowerShell/PowerShell/issues/2845
https://github.com/PowerShell/PowerShell/issues/5000
https://github.com/PowerShell/PowerShell/pull/8534
