### ISSUE TITLE
VSCode corrupts 'registered sign' character

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2851]
The Issue was opened in VSCode repo Microsoft/vscode#15303 and closed with resolution:
> VS Code, on the other hand, doesn't silently fix the incorrect encoding for you, so you actually find out about the encoding mistake in your files and can fix it.

Ex. [CoreAdapter.cs](https://github.com/PowerShell/PowerShell/blob/e568fda5c3dfd85ea18c0406217533849bb6e966/src/System.Management.Automation/engine/CoreAdapter.cs#L3124)

[Microsoft.PowerShell.Utility.psd1](https://github.com/PowerShell/PowerShell/blob/master/src/Modules/Windows-Full/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1)

Root of the problem is that VS Code default encoding is UTF8 and at the same time, most of the files in the Powershell repo is ASCII. (This problem does not exist in Visual Studio and Notepad++)

VS Code is recommended for the Powershell repo. So we would fix the problem here.

**Comment by iSazonov** [comment]
Related #722 #1559

**Comment by lzybkr** [comment]
Hopefully fixing these issues will avoid other random tools from corrupting our files - I know of at least one other tool that has caused problems.

**Comment by iSazonov** [comment]
Is it permissible to convert all files to UTF8 w/o BOM? Or is there another solution?

**Comment by lzybkr** [comment]
Convert to ASCII in some cases - e.g. use "\unnnn" instead of Unicode.

Windows tools necessarily assume UTF8, they use heuristics that are unnecessary if there is a BOM. As much as I don't like the BOM, I don't see a strong argument for doing a wholesale conversion of every file in the repo.

**Comment by iSazonov** [comment]
@lzybkr Clear. Thanks!

**Comment by iSazonov** [comment]
All cs files was cleaned up.
