### ISSUE TITLE
New-Item -ItemType SymbolicLink cannot understand directory path ending with slash on Linux

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell#2865]
Steps to reproduce
------------------

`New-Item -ItemType SymbolicLink -Path /foo/ -Value /bar/`

Expected behavior
-----------------

Symbolic link is created from `/foo/` to `/bar/`.

Actual behavior
---------------

`New-Item : No such file or directory`

Removing the slash at the end of the Path argument makes the call behave as expected. This is counterintuitive, as a slash at the end of a path generally works fine in PowerShell scripts to designate directories (and directory links).

Environment data
----------------

Running PowerShell on Ubuntu 16.04.

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.12
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by chunqingchen** [comment]
this issue has been resolved 
https://github.com/PowerShell/PowerShell/pull/2974
