### ISSUE TITLE
Invoke-Webrequest is missing some properties, like .ParsedHtml and .AllElements

### ISSUE THREAD

**Issue by ilgrank** [PowerShell/PowerShell#2867]
Hello Everyone
PsCore 6.x's Invoke-Webrequest is missing on the most 'loved' Ps 'classic' features, ie the ability to parse web pages and turn them into explorable objects.

Steps to reproduce
------------------
$test=invoke-webrequest -url http://www.github.com

Expected behavior
-----------------
$test.ParsedHtml 
$test.AllElements
(amont others) are missing:

Microsoft Powershell :
![psclassic](https://cloud.githubusercontent.com/assets/4583412/21061793/200fed48-be4e-11e6-88ac-98a06d79be34.png)

Core Poweshell:
![pscore](https://cloud.githubusercontent.com/assets/4583412/21061794/20177a72-be4e-11e6-991b-63e36dd15583.png)

Actual behavior
---------------
these properties are missing

Environment data
----------------

```
CLRVersion
SerializationVersion 1.1.0.1
PSRemotingProtocolVersion 2.3
PSEdition Core
WSManStackVersion 3.0
BuildVersion 3.0.0.0
GitCommitId v6.0.0-alpha.13
PSVersion 6.0.0-alpha
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}

```

I have hope to have web parsing capabilities in PSCore!
Thanks everyone!

**Comment by BrucePay** [comment]
@joeyaiello  FYI: Full PowerShell essentially uses Internet Explorer to do the HTML parsing. This is likely to be problematic to replicate on .NET core.

**Comment by joeyaiello** [comment]
@BrucePay I'd still like to investigate after we look at whatever ends up shipping .NET Standard 2.0

**Comment by jakerobinson** [comment]
What's the best alternative if this is low priority? Any low effort workarounds for parsing HTML in core?

**Comment by SteveL-MSFT** [comment]
.Net Std 2.0 doesn't solve this.  There is another issue where we discussed the need to leverage an OSS html parser rather than rely on a web browser being available (https://github.com/PowerShell/PowerShell/issues/2867), doing that work should also resolve this one.

**Comment by SRGOM** [comment]
May I propose using https://github.com/servo/html5ever?  Loosely speaking, Servo is the next generation of Firefox written in Rust. You can writing your bindings against https://github.com/utkarshkukreti/select.rs which is written on top of html5ever. 

Unlike some of the other parts of OSS community which in the past haven't colloborated with their own specific list of companies, Rust community is incredibly open and collaborative. VSCode uses a rust-coded library- https://github.com/BurntSushi/ripgrep/ whose author made changes specifically to accomodate them- @BurntSushi . 

There's also https://github.com/google/gumbo-parser which doesn't seem maintained right now and Chromium but I don't know how easy it is to pull in external code. 

PS: I am an honorary member of the Rust action strike force, which pressures people into rewriting already existing codebases into Rust. No I'm not, lol, there's no such thing. I'm just a Linux user who wishes to be able to parse html with `iwr`.

**Comment by SteveL-MSFT** [comment]
@SRGOM I don't have any affinity to any particular html parser, but certainly one that is maintained is more desirable.  I know that @iSazonov had proposed looking at some other OSS ones as well.

**Comment by SRGOM** [comment]
@SteveL-MSFT I'd like to say maintained + in use (so constantly tested). 

Webkit ranks higher than servo's html5ever there

**Comment by iSazonov** [comment]
It was in #3267 - AngleSharp. I now believe that AngleSharp is a lightweight and sufficient solution to this Issue. The use of more powerful engines should be discussed further (For example, if we want to migrate completely to a similar engine).

**Comment by SteveL-MSFT** [comment]
Rather than having this as part of the webcmdlets, these should be separate as html cmdlets which can be used against local files.

**Comment by MSAdministrator** [comment]
I am guessing this is still considered for the future?

**Comment by markekraus** [comment]
@MSAdministrator Yes, it is still considered for the future.

**Comment by iSazonov** [comment]
@MSAdministrator `Up-for-Grabs` delegate this to community :-). Feel free to write RFC to start the dev process.

**Comment by MSAdministrator** [comment]
Submitted RFC for `ConvertFrom-Html` here: https://github.com/PowerShell/PowerShell-RFC/pull/137

**Comment by wyzerd** [comment]
Why has this been changed to default of -UseBasicParsing?
This is the cause of the issue. I was using the scripts property for gathering information from the marketplace.visualstudio.com and now that property is missing causing my automation script to fail. This really shouldn't be a RFC but a request to restore original functionality. All that needs to be done to fix this is remove that hidden flag.

**Comment by SteveL-MSFT** [comment]
@wyzerd Windows PowerShell relied on Internet Explorer to parse the html.  Since Internet Explorer wasn't available in most platforms we support with PowerShell Core 6 (nanoserver, Linux, macOS), it made sense to default to `-UseBasicParsing`.  @MSAdministrator's proposal for `ConvertFrom-Html` is a better solution rather than marrying the parsing capability to the web cmdlets (like parsing a local html file).

**Comment by SRGOM** [comment]
MS is trusted for a backwards compatibility. It's okay to miss features but please don't add or remove things silently. It breaks trust.

**Comment by vexx32** [comment]
It wasn't removed silently. There were several announcement blog posts, including at least two or three from the main man behind the change, and it was documented in the patch notes and I believe is also in the updated help documentation.

**Comment by SRGOM** [comment]
@vexx32- You know what I'm trying to say but yes silently wasn't the right word to use. Please don't change default behavior that already works.

**Comment by vexx32** [comment]
There wasn't really much of a choice given they wanted to support multiple platforms, really. It's unfortunate, but as Steve mentions it's probably best to look at alternate solutions than to keep it tied down to a past solution that would inevitably break.

MS as a whole is moving away from IE to Edge, so I'm sure that having IE as a dependency isn't desirable, regardless of how much it might be convenient for some.

**Comment by wyzerd** [comment]
@SteveL-MSFT,
Thanks for the explanation. It never occurred to me that IE would have been the used as part of the library. In consideration of the evolution of Powershell, I suppose it made sense in 3.0 when it was generated specifically for Windows. I still think ConvertFrom-Html is sort of a hack (no offense intended). For maximum compatibility, it would be better to have rewrite the library to parse the HTML in a similar manner that the IE Library did it and return a compatible object type.


While -UseBasicParsing removes the one class defined by IE (mshtml library), it also removes other objects unnecessarily, Scripts, AllElements, Forms to name a few that are readily available. It seems it should be easier to override the ParsedHtml than to write a crutch app to append to the call.

**Comment by markekraus** [comment]
@wyzerd 

> it should be easier to override the ParsedHtml than to write a crutch app to append to the call.

This is an Open Source project. So if you feel this is a low level of effort, you are free to create a pull request to do so. 😃

**Comment by wyzerd** [comment]
@markekraus 
To be fair, I didn't say low level. However, writing ConvertFrom-HTML is likely to be more complex than an override of the single element of the HtmlWebResponseObject. Saddest part about it is I don't even care about that single mshtml element. What I want is the scripts element that is completely compatible, but removed because of the implementation. 

It is a good suggestion though and I really could use the time to sharpen my tools.

**Comment by thenecroscope** [comment]
Hi,

Can I check if there is any progress on this out of interest? Will this be resolved/added into Powershell 7 and / or .Net Core 3? Perhaps I should raise the request with the .net Core team. This was a really handy feature.

Many thanks!
Steve

**Comment by iSazonov** [comment]
Since  new Microsoft Edge is based on Chromium we could discover Chromium engine on system and utilize the API.

**Comment by jdelforno** [comment]
Ran into this today as well.

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core 
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`

**Comment by fMichaleczek** [comment]
I think @kamome283 module is a better way with AngleSharp than try to communicate with an external process. 
https://github.com/kamome283/AngleParse

**Comment by SteveL-MSFT** [comment]
Seems that the community has helped fill in this gap with modules on PowerShellGallery to specifically handle parsing html.

**Comment by francisco-lafe** [comment]
So, simply put, this Invoke-WebRequest cmdlet is not compatible for PS7 if I developed a script on PS5? 
Given that all the online information is mixed and you never know when they're talking about PS5 or PS7.

**Comment by wisemoth** [comment]
> Given that all the online information is mixed and you never know when they're talking about PS5 or PS7.

To be fair the documentation hosted at Microsoft makes it very easy to choose between (Windows) Powershell 5.1 and (say) Powershell 7.1; for example:

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1

There you can (for example) see different text for `-UseBasicParsing`

**Comment by serialhex** [comment]
@wisemoth did you intentionally make 2 links to the same thing for invoke-webrequest?  because both of those links point to the same URL and give the same information (for PowerShell 7,2).  If you're trying to say that the information is not mixed then doing this disproves your point...

**Comment by francisco-lafe** [comment]
> @wisemoth did you intentionally make 2 links to the same thing for invoke-webrequest? because both of those links point to the same URL and give the same information (for PowerShell 7,2). If you're trying to say that the information is not mixed then doing this disproves your point...

You're using the link previews created by github....
