### ISSUE TITLE
get-help not displaying for Aliases, Parameter Set Value and dynamic attributes of Parameters

### ISSUE THREAD

**Issue by hp-powershell** [PowerShell/PowerShell#2869]
Steps to reproduce
------------------
This issue is regarding powershell help issue for external providers i mean MAML xml file.
1) Create a help for a exported function Test-Cmd in the PowerShell module file M1.
2) Test-Cmd function takes 3 parameters as arguments and below is the signature of it,
    Test-Cmd
    (
    [int]a1, 
    [alias("A2")] 
    [string]a2,
    ValidateSet("set1","set2")] 
    [string]a3
    )
3) Save the created powershell help of Test-Cmd in a xml file called M1-help.xml in en-US folder of the installed M1 module file.
4) Launch PowerShell ISE and try get-help for the Test-Cmd with -Full option.
5) You can see that get-help does not display Aliases, Parameter Set Value and dynamic attributes for the above function.
6) Go to MAML file and delete the file under en-US location of M1 module location.
7) Try step-4 you could see that help displays all parameter attributes mentioned above (Reason is PowerShell help is dynamically generated this time not invoked from MAML help file).

Expected behavior
-----------------
Step-7 is expected behavior.
Get-help should display Aliases, Parameter Set Value and dynamic attributes of the cmdlet Test-Cmd function. 

Actual behavior
---------------
Step-5 is actual behavior.
Get-help is not displaying Aliases, Parameter Set Value and dynamic attributes of the cmdlet Test-Cmd function. 

Environment data
----------------
Name                           Value                                                                                                            
----                           -----                                                                                                            
PSVersion                      5.0.10240.16384                                                                                                  
WSManStackVersion              3.0                                                                                                              
SerializationVersion           1.1.0.1                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                  
BuildVersion                   10.0.10240.16384                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                          
PSRemotingProtocolVersion      2.3     

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
@hp-powershell Could you please test this with latest builds (PS 5.1 and 6.0)?
And it would be great if you attached the test files.

**Comment by Bishwas-py** [comment]
You can do this with [powershell alias function with parameters](https://webmatrices.com/d/530-powershell-alias-function-with-parameters), this given help is helpful.

**Comment by LethiferousMoose** [comment]
I'm not sure how that is related, that seems to be a PowerShell function wrapping a python execution, it doesn't seem related at all to the generated help documentation for the aliases of function parameters.
