### ISSUE TITLE
Download.sh for alpha 13 references alpha 11

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell#2870]
The file at `https://github.com/PowerShell/PowerShell/blob/v6.0.0-alpha.13/tools/download.sh` actually references the string `v6.0.0-alpha.11` in the code. This feels like an error - should it not say 13?

**Comment by mklement0** [comment]
This has happened again in alpha.16:

The Unix [download page](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md) references the download script at https://github.com/PowerShell/PowerShell/blob/v6.0.0-alpha.16/tools/download.sh, which seems right, but the actual file at that location still points to alpha._15_.

It sounds like updating the script should be _automated_.

**Comment by iSazonov** [comment]
Download scripts was refactored.
