### ISSUE TITLE
Windows 10 builtin SSH, arrows keys do not work in PowerShell in Azure Ubuntu Server 16.04

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell#2871]
Steps to reproduce
------------------

1. Deploy Ubuntu Server 16.04 on Azure (the default image in Marketplace).
1. On a Windows 10 machine, Install Linux Subsystem for Windows.
1. Open *Bash on Ubuntu on Windows*.
1. SSH into the Azure server from Windows.
1. Enter some arbitrary commands and press arrow keys. Observe that arrow keys behave as expected.
1. Install PowerShell according to https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md
1. Execute PowerShell by entering the `powershell` command.
1. Enter some arbitrary commands and press arrow keys.

Expected behavior
-----------------

Arrow keys navigate history (up/down) and move the cursor (left/right).

Actual behavior
---------------

Arrow keys produce letters A, B, C and D.

Such a basic feature should really work out of the box, considering how this is using a Microsoft OS on a Microsoft cloud default image, with default configuration for everything.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.13
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Duplicate #1586
