### ISSUE TITLE
Add newline customization parameter to Set-Content 

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell#2872]
While I see that PowerShell respects platform line endings quite well, it is sometimes necessary to generate files for one OS when operating on another OS. As far as I can tell, Set-Content always uses the platform line endings. Therefore, at the moment, newline characters have to be manually post-processed when this is done.

Having a `-NewlineString` or equivalent parameter on Set-Content would simplify this, at least for many basic cases.

**Comment by iSazonov** [comment]
👍 Looks good!
👎 Powershell i/o is based on CoreCLR where `Environment.Newline` is platform _**readonly**_ property. I believe that if we want it, then we need to make a feature request in .Net Core to manage i/o more flexibility that is very desirable for multi platform support.
👍 Now Powershell already handle `NoNewline`. So we can easy enhance this to handle `newline`
For `Add-Content` and `Set-Content` [here](https://github.com/PowerShell/PowerShell/blob/309bf603f9aff9009dce7e725d42b2d4f99f58c9/src/System.Management.Automation/namespaces/FileSystemContentStream.cs#L1111) and [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L7627) 
For `Out-File` [here](https://github.com/PowerShell/PowerShell/blob/309bf603f9aff9009dce7e725d42b2d4f99f58c9/src/System.Management.Automation/commands/utility/FormatAndOutput/common/ILineOutput.cs#L395)
For `Write-Host` it is unnecessary I think. 

Proposed parameter:
```powershell
Set-Content -Newline ( Default | Windows | Unix )
```
`Default` is platform default (current behavior)

**Comment by kittholland** [comment]
Would it make sense or be possible to support a variable we could define as our line ending kind of how $OFS works?

**Comment by iSazonov** [comment]
+1 Good point!

**Comment by rkeithhill** [comment]
$EOL??

**Comment by iSazonov** [comment]
I think a full name will be more user friendly.
$EndOfLine
$FileOutputNewLine
???

**Comment by rkeithhill** [comment]
@iSazonov kind of like the user friendly `$OFS` (output field separator)?  ;-)

**Comment by iSazonov** [comment]
I would like to have this name was closer to the cmdlets on which it has effect `$FIleContentNewLine`

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and believes this is useful, however, can be complicated enough to warrant an RFC to discuss the design proposal before implementation.  Some considerations is environment variable vs parameters vs new cmdlet (maybe also handle encoding conversion?).

**Comment by SteveL-MSFT** [comment]
If there's interest in an environment variable to control this, please open a new issue.  Let's keep this some simply for `Set-Content -LineEnding` parameter
