### ISSUE TITLE
Dotnet-resgen now support <lang>

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2882]
Based on dotnet/cli#819 we could make improvements here with strongly-typed auto-generated C# bindings for resources.

@andschwa @vors  If the community can help with this, could you publish a road map?

Related #745 #746

**Comment by lzybkr** [comment]
Most of our resources have been localized by the Windows localization team, so I don't think it makes much sense to ask for community help until we figure out the best way to pull in those translations.

**Comment by vors** [comment]
@lzybkr I don't see how that's related. The `<lang>` in the title refers to C# language, not the localizations.

@iSazonov yes, it would be awesome to remove our own res-gen. Theoretically it should be a drop-in replacement. We are currently pinning version of dotnet, so I think it make sense to combine this effort with switch to csproj.

**Comment by iSazonov** [comment]
I tried to build with target "ResGen" and get error in diagnostic log "Generating strongly typed resource files not currently supported on .NET Core MSBuild". It seems we are still blocked by .Net Core 2.0 Preview.

**Comment by iSazonov** [comment]
Tracking Issue in MSBuild repo https://github.com/Microsoft/msbuild/issues/2272

**Comment by iSazonov** [comment]
It seems we get this in .Net Core 3 and 5.
See https://github.com/microsoft/msbuild/issues/2272#issuecomment-532268770

**Comment by andschwa** [comment]
@iSazonov oh, that's awesome!

**Comment by iSazonov** [comment]
I pulled PR to use dotnet ResGen.
