### ISSUE TITLE
Please compile PowerShell icon into powershell.exe for Windows binary

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#2883]
This is likely related to #2881 - perhaps the reason that it was necessary to create a separate component for the icon?

Would be nice to have it compiled right in so that normal windows icon behaviors are observed (shortcut creation, visual identification in file system, etc).

**Comment by iSazonov** [comment]
It seems this is still not supported dotnet/cli#3267

**Comment by SteveL-MSFT** [comment]
See discussion in #5013 for some of the findings
