### ISSUE TITLE
Consider including PR# for each change in CHANGELOG.md

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/PowerShell#2891]
Hi all!

Linking a particular bullet back to the context - a pull request, issue, etc. - could be quite valuable.  It might take a bit more effort, but you might consider including this information.

For example, check the [kubernetes changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#other-notable-changes-2) - this makes it easy for me to go right to discussion / implementation details for a change I'm curious about (Thanks for the example Trevor!)

Cheers!

**Comment by lzybkr** [comment]
I imagine we'll do that more when we get closer to a supported release.

**Comment by RamblingCookieMonster** [comment]
Even if you don't do it consistently, I suppose it might be handy for big-ish things, despite the early state of things.  For example, was curious about PSRP in the recent release, had to dig through a few issues before finding #942, which had exactly what I was looking for via @paulcallen

Personally I would love to see each bullet linked to a PR or group of PRs, and each PR would always link to related issues, but, I know it might not be a priority.

Cheers!

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we close the Issue?

**Comment by SteveL-MSFT** [comment]
We're doing this now, but don't plan to retroactively fix the old ones unless someone else wants to contribute that as a PR :)

**Comment by iSazonov** [comment]
Months ago I sent @daxian-dbw  a script to create a table with closed PRs - this allow automate creating changelog if we'd accurate with PR header (description).
