### ISSUE TITLE
PowerShell installation new version not removing previous existing product folders

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2894]
Steps to reproduce
------------------
Install powershell latest version "powershell_6.0.0-alpha.14-1ubuntu1.16.04.1_amd64.deb"

Expected behavior
-----------------
To complete installation without any errors.

Actual behavior
---------------
Errors are showing that can't delete folder because they are not empty.

dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/PSReadLine': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/Microsoft.PowerShell.Archive/en-US': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/Microsoft.PowerShell.Archive': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/PackageManagement/1.1.1.0': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/PackageManagement': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/PowerShellGet/1.1.1.0/en-US': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/PowerShellGet/1.1.1.0': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules/PowerShellGet': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/Modules': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13/en-US': Directory not empty
dpkg: warning: unable to delete old directory '/opt/microsoft/powershell/6.0.0-alpha.13': Directory not empty

Environment data
----------------

OS: Ubuntu 16.04.1

```powershell
PS /home/maxt/Downloads> $PSVersionTable                                                                                

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-alpha                                                                             
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   3.0.0.0                                                                                 
GitCommitId                    v6.0.0-alpha.14                                                                         
CLRVersion                                                                                                             
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1 

```
(See attached image)

![notremovingfolders](https://cloud.githubusercontent.com/assets/19892435/21247986/b51e820c-c301-11e6-88d5-3c8a74634df1.png)

**Comment by anmenaga** [comment]
@joeyaiello this probably is Not a 'HighPriority' issue:

- those are soft warnings, not errors; installation of the new version completes successfully;
- each PS version is installed into a separate folder (e.g. "/opt/microsoft/powershell/6.0.0-beta.3" side-by-side with "/opt/microsoft/powershell/6.0.0-alpha.18");  link "/usr/bin/powershell" points to the last installed one.
- looks like such dpkg warnings are a common issue when updating/removing some packages:

> dpkg will not remove non-empty directories. If:
> a directory was owned by some package, and 
> you added a file manually, or some package added a generated file, to that directory and then,
> removed the first package,
> dpkg will warn you that it is not removing that non-empty directory.

**Comment by SteveL-MSFT** [comment]
I agree with @anmenaga , also I think the leftover content is from PSGet metadata

**Comment by SteveL-MSFT** [comment]
With the change to have stable versions install to `6` folder and preview versions in `6-preview`, this should no longer be an issue.  If there's concern about PSGet metadata being left over from an uninstall, I suggest opening an issue in https://github.com/powershell/powershellget
