### ISSUE TITLE
Make PowerShell Really Monadic (in Category Theory)

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#2903]
With an analogue between PS concepts and the category theory:

- Cmdlets ←→ Kleisli Category
- Streams ←→ Monadic types
- `|` ←→ Kleisli Composition (`>=>`)
- `cat` ←→ `return`

Could we extend PS’s type system to support other monad types? For example, list comprehension.

**Comment by ArieHein** [comment]
Something you can not achieve via Add-Type ?

**Comment by SteveL-MSFT** [comment]
@be5invis if you're serious, I would suggest writing a RFC.
