### ISSUE TITLE
Enable coloring of Select-String output

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#2905]
@lzybkr bkr added a [gist](https://gist.github.com/lzybkr/dcb973dccd54900b67783c48083c28f7) adding coloring formatdata for MatchInfo. 

I played a bit with it and added coloring of [regex groups](https://gist.github.com/powercode/4833804efd23045387bd5d5249d76f7b) and after having used it for a few months, I have to say that it is very useful. Instead of a wall of text, it is really easy to distinguish the things you're looking for.

![matchinfo](https://cloud.githubusercontent.com/assets/3505151/21308912/54c8894c-c5dc-11e6-9a21-df68f0cbfa2c.PNG)

How about making some version of this ship with the platform?

**Comment by iSazonov** [comment]
Looks superb!
We must help our eyes.
It would be nice to paint all output.
Maybe make the individual format color views for other types?

**Comment by lzybkr** [comment]
Most won't notice, but there is a small issue that we should consider in the formatting engine before using color in any default formatting.

If you change your foreground/background colors, the "reset color" ANSI escape sequence (CSI 0 m) doesn't work as expected.  For example, I have the following in my profile (using my unpublished module [ConsoleUtilities](https://github.com/lzybkr/ConsoleUtilities))

```powershell
Import-Module -Name ConsoleUtilities

Set-ConsoleColorTable -ColorTable @{
    Black       = '#141414'
    Blue        = '#004bff'
    Cyan        = '#00ffff'
    DarkBlue    = '#374b80'
    DarkCyan    = '#008080'
    DarkGray    = '#808080'
    DarkGreen   = '#008000'
    DarkMagenta = '#800080'
    DarkRed     = '#C81010'
    DarkYellow  = '#808000'
    Gray        = '#c0c0c0'
    Green       = '#00ff00'
    Magenta     = '#ff00ff'
    Red         = '#ff0000'
    White       = '#ffffff'
    Yellow      = '#ffff00'
} -TextForegroundColor Gray -TextBackgroundColor Black
```

If I start PowerShell from the regular shortcut that has the royal blue background, my suggested implementation for highlighting matches causes weird things to happen.

I'm not sure if this issue should be considered a PowerShell bug or conhost bug, but I do think PowerShell needs to provide a good experience for folks that customize their consoles like I do.

**Comment by powercode** [comment]
And how should we think about the new console with full RGB support? 
Seems wrong to limit ourselves to the small set of named console colors.

**Comment by lzybkr** [comment]
Discussion about color support is in https://github.com/PowerShell/PowerShell/issues/2381

**Comment by HumanEquivalentUnit** [comment]
I saw this recently https://twitter.com/LincolnAtkinson/status/907708171728257024 ([Code here](https://gist.github.com/latkin/cead06658b45539f16ba1b276095cc5e)) and it's related.

It couldn't be just formatting because it changes the output and has multiple lines, but it does go usefully further in explaining how the group names match up against the input test. 

e.g. `Select-String` could get an `-ExplainMatch` switch which makes it take the first match and output something like this.

**Comment by derek-xia** [comment]
I'm at HackIllinois right now and I'd like to take a look at this issue.

**Comment by ThomasNieto** [comment]
@iSazonov the emphasis logic was merged, can this issue be closed?
