### ISSUE TITLE
The output of help command is one letter per line

### ISSUE THREAD

**Issue by yanxyz** [PowerShell/PowerShell#2909]
Run help command:

```powershell
> help cd
```

![20161220_194627](https://cloud.githubusercontent.com/assets/737120/21349818/f9360bb8-c6ee-11e6-9f2c-25c58b863e9b.png)

The one on the right is the latest PowerShell:

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.3
WSManStackVersion              3.0
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.14
PSEdition                      Core
```

The one on the left is system embeded PowerShell:

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

My OS is Windows 10 x64 Chinese language. 

The `Get-Help`  cmdlet has no problem.

**Comment by randomvariable** [comment]
Just looking at #2809. Is this because on Windows, the help file gets piped into more, and this doesn't support unicode properly, and is it an issue for the command prompt team?

**Comment by chunqingchen** [comment]
This only repros on cmd running powershell.exe, it won't repro on powershell console running Core powershell.exe

**Comment by chunqingchen** [comment]
@yanxyz can we close the issue?

**Comment by SteveL-MSFT** [comment]
@chunqingchen I don't think that's a viable workaround.  if `more` has an issue, then we should have `help` have a dependency on `more`.

**Comment by yanxyz** [comment]
@chunqingchen thanks. I have no idea the inner detail. As a normal user I'm just curious about why it doesn't work after update. I have tried the second method you mentioned, it works. 

You could close this issue when you think it is OK.

**Comment by iSazonov** [comment]
@chunqingchen Can we close the Issue as resolved?
