### ISSUE TITLE
Get-Process should display PM and WS in MB instead of KB

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#2910]
Steps to reproduce
------------------
```powershell
PS C:\Program Files\PowerShell\6.0.0.14> get-process | Select-Object -First 1

 NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
 ------    -----      -----     ------     --  -- -----------
     14     4208      21604       3.70   7008   1 ApplicationFrameHost
```
On Servers, processes are more likely to take up multiple megs so displaying K is less useful

Expected behavior
-----------------
PM(M), WS(M)

Actual behavior
---------------
PM(K), WS(K)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSEdition                      Core
CLRVersion
GitCommitId                    v6.0.0-alpha.14
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
```

TFS:9750040

**Comment by faheel** [comment]
I'm working on this issue currently.
I've found the code that needs to be fixed ([link to code section](https://github.com/PowerShell/PowerShell/blob/ae7b857c235203d1fd3708fe05c076e5a376859a/src/System.Management.Automation/commands/utility/FormatAndOutput/common/DefaultFormatters/DotNetTypes_format_ps1xml.cs#L534-L552)):
```
              yield return new FormatViewDefinition("process",
                TableControl.Create()
                    .AddHeader(Alignment.Right, label: "NPM(K)", width: 7)
                    .AddHeader(Alignment.Right, label: "PM(K)", width: 8)
                    .AddHeader(Alignment.Right, label: "WS(K)", width: 10)
                    .AddHeader(Alignment.Right, label: "CPU(s)", width: 10)
                    .AddHeader(Alignment.Right, width: 6)
                    .AddHeader(Alignment.Right, width: 3)
                    .AddHeader()
                    .StartRowDefinition()
                        .AddScriptBlockColumn("[long]($_.NPM / 1024)")
                        .AddScriptBlockColumn("[long]($_.PM / 1024)")
                        .AddScriptBlockColumn("[long]($_.WS / 1024)")
                        .AddScriptBlockColumn(@"if ($_.CPU -ne $()) { $_.CPU.ToString(""N"") }")
                        .AddPropertyColumn("Id")
                        .AddPropertyColumn("SI")
                        .AddPropertyColumn("ProcessName")
                    .EndRowDefinition()
                .EndTable());
```
The way it looks to me, I would need to change `NPM(K)` to `NPM(M)` in the `AddHeader()` call, and change `$_.NPM / 1024` to `$_.NPM / (1024 * 1024)` in the `AddScriptBlockColumn()` call. Similarly for PM.

Could I be assigned on this issue, or can I submit a PR without being assigned?

**Comment by lzybkr** [comment]
Consider yourself assigned.
You can always submit a PR without being assigned
We can't assign in the GitHub UI without making someone a collaborator (a GitHub restriction), but we need to see some history as a contributor before making that person a collaborator.
