### ISSUE TITLE
PowerShell module fails to install: "version of the module being installed is not catalog signed"

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2917]
Steps to reproduce
------------------

1. Create a vanilla Windows Server 2016 Data Center virtual machine
2. Login to the instance using RDP or PowerShell Remoting over WinRM
3. Open PowerShell Console Host or Integrated Scripting Editor (ISE)
4. Call `Install-Module -Name AWSPowerShell -Scope CurrentUser -Force`

Expected behavior
-----------------

When installing a PowerShell module, using the standard, built-in `Install-Module` command, the PowerShell module should install successfully, without throwing errors.

Actual behavior
---------------

Rather than installing successfully, the `Install-Module` PowerShell command throws a nasty error message about code signing. Within the text of the error message, I didn't observe a link to documentation about what code signing is, how to code sign a PowerShell module, or under what circumstances code signing a module is necessary, or who is responsible for doing this.

The exception message does indicate adding a parameter called `-SkipPublisherCheck`, but doesn't explain why this is necessary, or if this is even safe to do, from a security standpoint. Security conscious users will not want to arbitrarily disable security policies that were put into place to ensure the integrity of the software that they are installing and executing.

```
PS C:\Users\Administrator> Install-Module -Scope CurrentUser -Name AWSPowerShell -Force;
PackageManagement\Install-Package : The version '3.3.32.0' of the module 'AWSPowerShell' being installed is not catalog signed. Ensure that the version '3.3.32.0' of 
the module 'AWSPowerShell' has the catalog file 'AWSPowerShell.cat' and signed with the same publisher 'CN=VeriSign Class 3 Public Primary Certification Authority - 
G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US' as the previously-installed module '3.3.32.0' with 
version '3.3.23.0' under the directory 'C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell'. If you still want to install or update, use -SkipPublisherCheck 
parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1661 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

<img width="1606" alt="screen shot 2016-12-21 at 10 08 44 am" src="https://cloud.githubusercontent.com/assets/466713/21398949/b7d5e83c-c766-11e6-813b-d1b9d89e382d.png">

Environment data
----------------

- Windows Server 2016 Data Center Edition
- Instance provisioned on Amazon Web Services (AWS) EC2
- Instance exists in dedicated Virtual Private Cloud (VPC)
- VPC has Internet Gateway attached
- VPC Subnet has full outbound routing to the Internet

```powershell
PS C:\Users\Administrator> $PSVersionTable

Name                           Value                                                                                                                           
----                           -----                                                                                                                           
PSVersion                      5.1.14393.206                                                                                                                   
PSEdition                      Desktop                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                         
BuildVersion                   10.0.14393.206                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                 
WSManStackVersion              3.0                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                             
SerializationVersion           1.1.0.1                                                                                                                         
```

**Comment by bmanikm** [comment]
@pcgeek86 This was a known issue and got resolved with the latest Cumulative Update. Please try again after installing the latest Cumulative Update.

**Comment by pcgeek86** [comment]
@bmanikm Thanks, let me take a look to see if there's a Cumulative Update available for this instance.

**Comment by getSurreal** [comment]
Do you have a more specific patch number?  I'm having the same issue on the latest patched Windows 2012 R2 instance in AWS.

**Comment by Cloudmersive** [comment]
Was this ever actually fixed?
