### ISSUE TITLE
XmlDocument missing Load(string) method

### ISSUE THREAD

**Issue by LethiferousMoose** [PowerShell/PowerShell#2922]
Steps to reproduce
------------------
On PowerShell 5.0 I was able to access the XmlDocument.Load(string) method. I downloaded the latest PowerShell version off GitHub and that method overload now appears to be missing. This method is still listed on MSDN (https://msdn.microsoft.com/en-us/library/875kz807(v=vs.110).aspx) so it does not appear to have been deprecated.

5.0:
OverloadDefinitions
-------------------
void Load(string filename)
void Load(System.IO.Stream inStream)
void Load(System.IO.TextReader txtReader)
void Load(System.Xml.XmlReader reader)

v6.0.0-alpha.14:
OverloadDefinitions
-------------------
void Load(System.IO.Stream inStream)
void Load(System.IO.TextReader txtReader)
void Load(System.Xml.XmlReader reader)

Expected behavior
-----------------
I am able to call the Load(string) method on XmlDocument.

Actual behavior
---------------
The XmlDocument.Load(string) method is not detected as a possible overload and throws an exception.

Environment data
----------------
5.0:
Name                           Value
----                           -----
PSVersion                      5.0.10240.17146
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

v6.0.0-alpha.14:
Name                           Value
----                           -----
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.14
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
PSEdition                      Core
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by vors** [comment]
It's dotnet core, not PowerShell issue.
Dotnet core 1.0 and 1.1 (currently used by PS) have a lot of missed APIs.
They are [bringing missing APIs back in 1.2](https://github.com/dotnet/corefx/issues/5925#issuecomment-261730549).
Once they release it, we will switch to the new version and such APIs should be back.

**Comment by LethiferousMoose** [comment]
Thanks for the response. That's what I wanted to know.
