### ISSUE TITLE
can not use "~" with mkdir

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#2928]
can not use "~" with mkdir

1 In powershell, the following functions are normal: (command with "~")
test-path ~/xxx
cd ~/xxx

2 i foud powershell's mkdir is linked to /usr/bin/mkdir:
mkdir --help     #    return gnu 

3 can use 【mkdir ~/xxx】in bash,but can't use that command in powershell,i think it is a bug.

Steps to reproduce
------------------
mkdir ~/xxx

Expected behavior
-----------------
support ~

Actual behavior
---------------

Environment data
----------------
linux: 
centos 7.3 1611

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-alpha                                                                                                       
PSEdition                      Core                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   3.0.0.0                                                                                                           
GitCommitId                    v6.0.0-alpha.14                                                                                                   
CLRVersion                                                                                                                                       
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1  

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by chuanjiao10** [comment]
hi @SteveL-MSFT    This problem has been fixed,close it please.

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-beta                                                                                                        
PSEdition                      Core                                                                                                              
BuildVersion                   3.0.0.0                                                                                                           
CLRVersion                                                                                                                                       
GitCommitId                    v6.0.0-beta.1                                                                                                     
OS                             Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017                                              
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0

**Comment by SteveL-MSFT** [comment]
I'm not repro'ing this with Ubuntu16.04 and beta.1.  `mkdir ~/test2` created a folder called `test2` in my home directory.

I'll try with CentOS.
