### ISSUE TITLE
Start-PSBuild fails with Could not find Visual Studio vcvarsall.bat at .

### ISSUE THREAD

**Issue by goyalmohit** [PowerShell/PowerShell#2929]
Please pardon if this is not the right way to build or file a bug.

I'm trying to build PowerShell core on windows 2012 R2 machine. When I'm running command Start-PSBuild after importing module build.psm1, it fails with error:

PS C:\Program Files (x86)\jenkins\workspace\powershellcore> Start-PSBuild
Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files (x86)\jenkins\workspace\powershellcore\build.psm1:163 char:49
+         $vcVarsPath = (Get-Item(Join-Path -Path "$env:VS140COMNTOOLS" -ChildPath ...
+                                                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
   PathCommand

Could not find Visual Studio vcvarsall.bat at . Please ensure the optional feature 'Common Tools for Visual C++' is
installed.
At C:\Program Files (x86)\jenkins\workspace\powershellcore\build.psm1:165 char:13
+             throw "Could not find Visual Studio vcvarsall.bat at $vcVarsPath. Pl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...' is installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio vcvarsall.bat at . Please ensure the optional feature 'Comm
   on Tools for Visual C++' is installed.

Naturally, I don't have visual studio installed on the machine. If I run the Start-PSBootStrap, it's output is as below:
PS C:\Program Files (x86)\jenkins\workspace\powershellcore> Start-PSBootstrap
Installing PowerShell build dependencies
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-1-003177/dotn
et-dev-win-x64.1.0.0-preview2-1-003177.zip
dotnet-install: Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-1-003
177/dotnet-dev-win-x64.1.0.0-preview2-1-003177.zip
dotnet-install: Adding to current process PATH: "C:\Users\Administrator\AppData\Local\Microsoft\dotnet\". Note: This cha
nge will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

Steps to reproduce
------------------
Try to build in the following fashion:
PS C:\Program Files (x86)\jenkins\workspace\powershellcore> import-module .\build.psm1
PS C:\Program Files (x86)\jenkins\workspace\powershellcore> Start-PSBootStrap
PS C:\Program Files (x86)\jenkins\workspace\powershellcore> Start-PSBuild

Expected behavior
-----------------
This should be covered as part of Start-PSBootStrap module or documentation/FAQ.md should be updated for workaround.

Environment data
----------------
PS C:\Program Files (x86)\jenkins\workspace\powershellcore> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by goyalmohit** [comment]
This is PowerShell code throwing error inside Start-PSBuild function: 

$vcVarsPath = (Get-Item(Join-Path -Path "$env:VS140COMNTOOLS" -ChildPath '../../vc')).FullName
        if ((Test-Path -Path $vcVarsPath\vcvarsall.bat) -eq $false) {
            throw "Could not find Visual Studio vcvarsall.bat at $vcVarsPath. Please ensure the optional feature 'Common Tools for Visual C++' is installed."
        }

**Comment by mirichmo** [comment]
Start-PSBootStrap will not install Visual Studio for you. Additionally, you need to install the "Common Tools for Visual C++" component as described in the error message. Once both are installed, I would expect the build process to work as expected for you. We provide links [here](https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-core.md#visual-studio).

**Comment by goyalmohit** [comment]
Yes, it works after installing component as mentioned. The bug is raised for either updating build instructions or covering this using bootstrap script as per existing instructions.

**Comment by goyalmohit** [comment]
Documentation stands updated. So closing this bug now.
