### ISSUE TITLE
Different directory structures when using Copy-Item when destination does or does not exist.

### ISSUE THREAD

**Issue by rickwebiii** [PowerShell/PowerShell#2934]
Suppose I have the following directories in the current working path:
src\foo\bar

and the dest directory does not exist.

Running "Copy-Item -Recurse src dest" yields dest\foo\bar

However, if dest does exist then I get dest\**src**\foo\bar

I at least expect to get the same behavior regardless of whether dest already exists or not.

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by dennismi** [comment]
I can confirm this. It is really annoying. And if you need to add more items to the destination, the copy item throws an error, unless you force it.

**Comment by Aculeo** [comment]
While this would be a pretty big breaking change, the current behavior is very confusing and can lead to nasty bugs that are hard to track down. I stumbled into this problem on more than one occasion. My preference would also to get this changed.

As it stands I've gotten into the habit of writing this when copying a folder to another location:

```powershell
if (!(Test-Path $TargetPath)) {
    New-Item -ItemType Directory $TargetPath
}
Copy-Item -Path "$SourcePath\*" -Destination $TargetPath -Recurse -Force
```

Somewhat annoying to have this much boilerplate code just for a simple, complete and consistent copy.

**Comment by mklement0** [comment]
@Aculeo, you can ease the pain a bit by replacing the `if` statement with `$null = New-Item -Force -ItemType Directory $TargetPath`, which, thanks to `-Force`, is a quiet no-op if the dir. already exists (the `New-Item` call returns a `[System.IO.DirectoryInfo]` instance either way - representing either the newly created or the preexisting dir.  - which `$null = ` discards).

You can therefore even roll it into a single command:

```powershell
Copy-Item -Path "$SourcePath\*" -Destination (New-Item -Force -ItemType Directory $TargetPath) -Recurse -Force
```
