### ISSUE TITLE
OutputType attribute doesn't work with String type + other problems discovered

### ISSUE THREAD

**Issue by tahir-hassan** [PowerShell/PowerShell#2935]
This is an issue with the "intellisense" for the `[OutputType]` attribute, when the output type is `String`.  No intellisense is given for the `String` type, So I cannot find the `Substring` method etc.  This only affects the `String` type.

A PowerShell MVP, BartekB, also reproduced this issue: http://stackoverflow.com/a/41351336/288393

Steps to reproduce
------------------

* Install PowerShell_6.0.0.14-alpha.14-win10-x64.msi
* Paste the following code in into a PowerShell 6 window

```powershell
function Send-Greeting
{
  [OutputType([String])]
  Param ($Name)

  "Hello, $Name"
}
```

And press enter.

* Type in:

`Send-Greeting "John" | % { $_.<TAB> }`

* Press the tab character where `<TAB>` is.  

* Alternatively, use PowerShell ISE and after pressing dot, you get the same list of methods (so it is not PSReadline related).

Expected behavior
-----------------

I should get the string type's methods and properties.

Actual behavior
---------------

I get a bunch of methods I don't want and are not from the string class:

```
CompareTo    GetType      ToByte       ToDecimal    ToInt32      ToSingle     ToUInt16
Equals       GetTypeCode  ToChar       ToDouble     ToInt64      ToString     ToUInt32
GetHashCode  ToBoolean    ToDateTime   ToInt16      ToSByte      ToType       ToUInt64
```

Environment data
----------------

```
Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-alpha.14
PSEdition                      Core
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Perhaps related #2567

**Comment by tahir-hassan** [comment]
Hi, not related to #2567.  

This problem only affects the `string` type.  I imagine because `string` is `IEnumerable<char>` and `$_` is being treated as a `char` instead of a `string`

**Comment by tahir-hassan** [comment]
I've did some interesting investigations on this. I added an `IString` interface which is the same as `String` class:

```powershell
& {
    $props = [string].GetProperties([System.Reflection.BindingFlags]::Instance -bor [System.Reflection.BindingFlags]::Public);
    $methods = [string].GetMethods([System.Reflection.BindingFlags]::Instance -bor [System.Reflection.BindingFlags]::Public) | ? { -not ($_.IsSpecialName) };

    $propertyDecls = $props | % { "$($_.PropertyType.FullName) $($_.Name) { $(if ($_.CanRead) { "get;" }) $(if ($_.CanWrite) { "set;" }) }" }
    $methodDecls = $methods | % { $parameters = [string]::Join(",", @($_.GetParameters() | % { "$($_.ParameterType.FullName) $($_.Name)" })); "$(if ($_.ReturnType -eq [void]) { "void" } else { $_.ReturnType.FullName }) $($_.Name) ( $parameters );" }

    $classDefinition = "public interface IString {" + $propertyDecls + $methodDecls + "}"
    
    Add-Type $classDefinition
}
```

Then I changed the `Send-Greeting` function above to reference `IString`:
```powershell
function Send-Greeting
{
  [OutputType("IString")]
  Param ($Name)

  "Hello, $Name"
}
```

Then, lo and behold, the following behavior worked:

```powershell
Send-Greeting "John" | % { $_.<TAB> }
```

However, then I tried to define another test function `Get-FirstChar` which accepts pipeline input:

Function Get-FirstChar
{
    [OutputType("IString")]
    [CmdletBinding()]

    param(
      [Parameter(Mandatory=$true, ValueFromPipeline=$true)][string[]]$Strings
    )

    process {
        foreach ($str in $Strings) {
            $str.SubString(0, 1);
        }   
    }
}

What I noticed is that with pipeline input, it doesn't work:

```powershell
# does not work :(
"John","Smith","Fred" | Get-FirstChar | % { $_.<TAB> }
```

However, if I get rid of the input and put `Get-FirstChar` at the front, then the tab-completion works:

```powershell
# works :)
Get-FirstChar | % { $_.<TAB> }
```

**Comment by MartinGC94** [comment]
This works now in `7.3.0-preview.7` possibly earlier. I'm guessing it got fixed in one of the recent type inference updates.

**Comment by iSazonov** [comment]
@MartinGC94 Have we tests for the case?

**Comment by MartinGC94** [comment]
@iSazonov I don't know if there are tests that specifically test strings but I usually add tests for my fixes (they are mandatory after all 😁) so if it was one of my recent changes that fixed it then it should be covered by a test. I updated the type inference for `$_` so it uses the same one used for `foreach ($x in $y)` and IIRC it includes code that specifically handles strings (to prevent enumeration) so whoever added that must have added a test for strings.
