### ISSUE TITLE
mac $env:path is empty in powershell

### ISSUE THREAD

**Issue by minoseah629** [PowerShell/PowerShell#2937]
Steps to reproduce
------------------
1. open terminal
2. input "powershell" in terminal
3. input "$env:path"
4. exited powershell
5. input echo $PATH

Expected behavior
-----------------
The behavior I expected to see was a string of environmental folders. 

From echo $path
/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Application Support/GoodSync:/usr/local/lib/dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update1/bin:/Users/{username}/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/share/dotnet:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

Actual behavior
---------------
The actual behavior provide no information. 
PS /Users/> $env:path                                                
PS /Users/> 

Environment data
----------------
                                 
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.14                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

**Comment by minoseah629** [comment]
I just tried using $env:PATH and that provided the correct result.  

I do not think the case should matter in this situation considering that other scripts will potentially use $env:path

**Comment by vors** [comment]
On Mac and Linux env variables are case-sensetive.
PowerShell should not try to wrap them in case-insensitive manner for the same reasons it should not try to wrap the filesystem.
