### ISSUE TITLE
Parser: Multiple methods, one line

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2939]
While working on #2219 , I am blocked by the [wrong test 
](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Language/Classes/Scripting.Classes.BasicParsing.Tests.ps1#L69)

Steps to reproduce
------------------
```powershell
        # Multiple fields, one line, last w/o semicolon
        class C4 { $x; $y }

        # Multiple methods, one line
        class C4 { f() {} f1() {} }
```
Expected behavior
-----------------
Parser throw on the second test.
_I believe that the definitions of methods must be separated by a delimiter ( ';' or new line) similar to first properties test._
```powershell
 class C4 { f() {} ; f1() {} }
```

Actual behavior
---------------

Parser pass both test.

**Comment by lzybkr** [comment]
Duplicate, see https://github.com/PowerShell/PowerShell/issues/2779
