### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by yanxyz** [PowerShell/PowerShell#2941]
Under the latest Powershell, when running a script encoded in different encodings,

test1:

```powershell
# encoding ANSI(codepage 936, gbk)
Write-Host "hello 你好"
# hello ÄãºÃ
```

It seams like that the script file is decoded in Latin1。

test2:

```powershell
# encoding UTF8 without BOM
Write-Host "hello 你好"
# hello ä½ å¥½
```

test3:

```powershell
# encoding UTF8 with BOM
Write-Host "hello 你好"
# hello 你好
```

PowerShell included in Windows(my OS is Win10 x64 ) works well besides the test2 which outputs "hello 浣犲ソ". 

Now try to write a file by Out-File

test4:

```powershell
# encoding UTF8 with BOM
 "hello 你好" | Out-File 't.txt' -Encoding default
# t.txt content: hello ??
```

 `-Encoding default` means system encoding which is GBK here，but the Chinese characters is messed. 

test5:

```powershell
# encoding ANSI(codepage 936, gbk)
 "hello 你好" | Out-File 't.txt' -Encoding default
# t.txt content: hello 你好
```

test6:

```powershell
# encoding ANSI(codepage 936, gbk)
 "hello 你好" | Out-File 't.txt' -Encoding utf8
# t.txt content: hello ÄãºÃ
```

I got quite lost. I expect that whether the encoding my file encoding is, the console output and Out-File -Encoding default(or unicode) is fine, it seams that I can't get these targets at the same time. PowerShell includes in Windows works well expected besides UTF8 without BOM.

```powershell
> $PSVersionTable

Name                           Value
----                           -----
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSEdition                      Core
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.14
CLRVersion
PSVersion                      6.0.0-alpha
WSManStackVersion              3.0
```

**Comment by chuanjiao10** [comment]
hi beginer:
  I found that you have a problem with powershell coding problems. But this is your problem, not the powershell problem. You need to learn as a rookie, and here is a master submit bug, you should not make trouble here.

I am a powershell fans. I'm a teacher of powershell.
Welcome to my group. Powershell study group. QQ group No. is 183173532
============ chinese ================
hi 菜鸟：
我发现你对powershell编码问题产生了困扰。但这是你的问题，不是powershell的问题。你作为菜鸟需要学习，而这里是高手提交bug的地方，你不应该在此捣乱。

我是一个powershell fans。我是教powershell的老师。
欢迎加入我的群。powershell学习研究群。 QQ group No. is 183173532

**Comment by yanxyz** [comment]
@chuanjiao10 你认为我在捣乱的话，那你先在打广告之前先把我的问题给解答一下呀，我也好知道你是否有资格教训别人。

**Comment by chuanjiao10** [comment]
Here is the place to submit the bug. you submit the title ambiguous, content confusion, so this issue should be closed. Please go to learn the wisdom of questions.(请你先去学习提问的智慧。)
