### ISSUE TITLE
Add debugging information to determine if running in container

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2943]
Something that might be useful for people using software containers, such as Docker / OCI or rkt, would be to include some debugging information to `$PSVersionTable`, to determine whether or not the PowerShell instance is running inside a software container. This may aid in debugging by providing additional, contextual information about the PowerShell process.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by phwelo** [comment]
Could also use an $env variable to give us something to work with, which is more of a Docker-y way of presenting that

**Comment by joeyaiello** [comment]
@phwelo Possibly a PS variable, but `$env` variables are explicitly [environment variables](https://en.wikipedia.org/wiki/Environment_variable). Unless there's already an environment variable for knowing if you're in a container, I don't think that's applicable here.

**Comment by phwelo** [comment]
My point was more that a container is describing the environment more than it is the Powershell thread. Overall it doesn't matter to me as long as I can differentiate though!

**Comment by joeyaiello** [comment]
@phwelo oh, gotcha, that make sense. 

I'm hoping that .NET Core 2.0 exposes something in System.Environment to help with this. But otherwise, it might be Docker's responsibility, as you say.

**Comment by iSazonov** [comment]
There is many ways to detect docker container
https://stackoverflow.com/questions/43002803/detect-if-process-executes-inside-a-windows-container
https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker

I close the issue until we decide to do the detection inside PowerShell Core.
