### ISSUE TITLE
Mac OS X :: iTerm 2 :: Go forward / back a word

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#2948]
How would one configure iTerm2 in order to go forward / back a word in PowerShell Core? Right now, if I try to use `ALT + B` and `ALT + F` keyboard shortcuts, the result is simply that a `b` or `f` character is printed. I even tried manually adding keyboard mappings to the PowerShell iTerm2 profile, but this didn't seem to have any effect positive or negative.

Both Bash and ZSH use the `ALT + B` and `ALT + F` keyboard shortcuts to go forward and back a word.

<img width="1128" alt="screen shot 2017-01-03 at 8 28 30 am" src="https://cloud.githubusercontent.com/assets/466713/21612524/d12c4e52-d18e-11e6-9c40-b9f21c2c060c.png">

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
@daviwil @TravisEz13 any thoughts on this one? It would make editing command lines much easier. Am I just missing something simple?

**Comment by TravisEz13** [comment]
adding @PowerShell/area-console

**Comment by iSazonov** [comment]
@pcgeek86 Could you please update a status of the issue with latest builds?

**Comment by TravisEz13** [comment]
`alt+back arrow` and `alt+ forward arrow` works for me in iTerm 2, in both the preview and the `6.0.4`

**Comment by pcgeek86** [comment]
@TravisEz13 I must have had PSReadline set to `Windows` edit mode, instead of the default.
