### ISSUE TITLE
Docker page contains broken links to documentation

### ISSUE THREAD

**Issue by jawn** [PowerShell/PowerShell#2949]
Steps to reproduce
------------------
Go to https://hub.docker.com/r/microsoft/powershell/
Click one of the links to documentation, eg 'getting started' or 'Instructions'

Expected behavior
-----------------
Navigates to corresponding documentation page.

Actual behavior
---------------
404 error message

Eg https://hub.docker.com/r/microsoft/powershell/docs/learning-powershell/

**Comment by vors** [comment]
The links are relative for github.
Docker exports only README.md

We can replace all relative links by absolute links in README.md
This came up second time already, probably worth to replace them.

**Comment by lzybkr** [comment]
Would an update to README.md automatically update hub.docker.com?

I see I can manually edit the "Full Description" manually in hub.docker.com, so I doubt they are connected, more likely somebody just pasted the contents.

**Comment by jawn** [comment]
Closing - issue seems to be fixed.
