### ISSUE TITLE
Support PowerShell Policies on Non-Windows Editions - especially Global Transcription Policies

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#2950]
The Transcription policies are not only useful for audit, but also for debugging PowerShell code that is run in complex call stacks (like we experience in automation tool stacks).

Transcription policies affect powershell engine execution in contexts where the powershell developer does not have the ability to specify command line parameters - so it seems these should be stored as settings.

The transcription policies are discussed here: https://blogs.msdn.microsoft.com/powershell/2015/06/09/powershell-the-blue-team/

Seems like it would make sense that whatever approach is taken, that it allows for any other relevant PowerShell policies.  It would also be in the spirit of PowerShell to keep the settings names the same as the current registry value names so that it is easy to translate articles written about these settings under Windows.

Perhaps it is time for /etc/powershell.conf ?

**Comment by fmichaleczek** [comment]
it is time for /etc/powershell/transcript.conf (or a Unix registry ^^)

**Comment by DarwinJS** [comment]
I have a personal theory that the whole concept of the registry has caused the IT industry billions.

This "in memory only accessible" configuration data store that is split between user and machine is a continual source of work around upon work around in automation code.

Unix / Linux never had this problem because all config is on disk - so if you're an admin, you can just see it all and manipulate it all.  No "loading user registry hives" to complete setup tasks.

Technically we have IBM to thank for it as it was inherited from OS/2 into the first versions of Windows NT.

**Comment by mirichmo** [comment]
I laid the foundation for this a few months ago when I added support to store [ExecutionPolicy values in configuration files](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/PropertyAccessor.cs). We have outstanding issues to cover moving additional values to configuration files (out of the registry), but not much time available to do it. I initially left all the GroupPolicy registry checks in place because we do not currently have support for those actions in PowerShell Core on non-Windows platforms.

In this specific instance of transcription, a bunch of new code would be needed to hook into logging mechanisms on the various non-Windows OSs that we support, so it is a much larger task than just storying the GroupPolicy value in a config file.

**Comment by ArieHein** [comment]
Are you at least "forcing" a dual config policy for new code / options that rely on configuration from this point forward ? 

Would this be something in the "best practices" or "how to" manual for contributors ?

**Comment by DarwinJS** [comment]
Seems like it might be valuable to write something that redirects registry calls to a file based storage method on non-windows.  Then the approach could be used throughout powershell and maybe .NET apps.  I **don't** mean that the store would be some type of blob that needs special utilities to read - could just be a directory structure that emulates registry levels and files named with the "value name" that contain the data.  Only handle simple registry data types at first.

**Comment by DarwinJS** [comment]
Anyone know if registry redirection to the file system has been discussed on the .NET core project?

**Comment by DarwinJS** [comment]
I started a discussion which revealed there is some activity around registry API emulation / redirection on non-windows: https://github.com/dotnet/standard/issues/148

**Comment by mirichmo** [comment]
@DarwinJS The current iteration of the code has two implementations of the interface: one for redirecting the request to the registry (on Windows PowerShell) and another for redirecting the request to JSON files (for PowerShell Core).
Your idea of generalizing it within Microsoft.Win32.Registry is interesting, but would have to be produced by the .Net team for us to consume it.
@ArieHein At the moment, enforcement is done by me via code review. Internally, we all have a mindset that whenever we add or modify PSCore, we need to do it in a cross-platform way.
