### ISSUE TITLE
Update-ModuleManifest should process regardless of current host

### ISSUE THREAD

**Issue by bcdady** [PowerShell/PowerShell#2951]
Steps to reproduce
------------------
From a PowerShell Console, Invoke Update-ModuleManifest cmdlet, specifying a `-Path` to a .psd1 manifest which includes `PowerShellHostName = 'Windows PowerShell ISE Host'`.

Specific example (this module is available from [PowerShellGallery](http://www.powershellgallery.com/packages/ISESteroids/):
```Update-ModuleManifest -Path $(Get-Module -ListAvailable -Name ISESteroids).Path```

Expected behavior
-----------------
Update-ModuleManifest would work as described: [Update-ModuleManifest](https://msdn.microsoft.com/powershell/reference/5.1/PowerShellGet/Update-ModuleManifest)

Actual behavior
---------------
PowerShell Console returns the following error message (in red text):
```
Update-ModuleManifest : Cannot update the manifest properly. 'The name of the current Windows PowerShell host is:
'ConsoleHost'. The module 'ISESteroids.psd1' requires the following Windows PowerShell host: 'Windows PowerShell ISE Host'.'
At line:1 char:1
+ Update-ModuleManifest -Path $(Get-Module -ListAvailable -Name ISESteroids).Path
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidArgument: (C:\Users\bdady\...SESteroids.psd1:String) [Update-ModuleManifest], ArgumentException
+ FullyQualifiedErrorId : InvalidModuleManifestFile,Update-ModuleManifest
```

Environment data
----------------
```powershell
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

**Comment by lzybkr** [comment]
`Update-ModuleManifest` is in PowerShellGet - open an issue [here](https://github.com/powershell/PowerShellGet/issues).
