### ISSUE TITLE
Add short alias for Select-Object

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#2956]
I would be nice to have a short alias for Select-Object as there is for Where-Object (?) and ForEach-Object (%). Seems natural that Select-Object would have one as frequently as it is used. All three of these are my bread an butter most days. I'd be open to any non conflicting single symbol character.

**Comment by RichardSiddaway** [comment]
I've always thought that the use of ? and % were 2 of the worst decisions made in the early days of PowerShell. Adding another one compounds the confusion.  if you want a single character alias its easy to add one but why stop with select-object. Shouldn't the same be done for sort-object?

**Comment by fmichaleczek** [comment]
@RichardSiddaway Production guys need sometimes to do things quickly in the consolehost. I don't see any character available to be aliased.

**Comment by thezim** [comment]
Maybe caret?

**Comment by RichardSiddaway** [comment]
Two things

sel then tab will give you select   - - that's pretty quick

the use of ? and % are confusing to many newcomers which is why I've never liked them. Getting people to stop using them in scripts can be painful.

I know people in production need to do things quick - I spent 25 years working in IT production environments. I think its just as important to avoid bad habits that can actually hurt

**Comment by thezim** [comment]
@RichardSiddaway I don't like them in scripts either but at console it makes sense to me.

**Comment by vors** [comment]
> All three of these are my bread an butter most days.

@thezim I'm curious about your usage of it. I hardly use `Select-Object` 10% of the time that I use `%` and `?`. What's the scenarios that it solves for you?

**Comment by thezim** [comment]
@vors usually it is something like this where I would prefer the line to not wrap, especially with expressions. I'm not saying  a select alias would eliminate a wrap but it would help.

``` powershell
gci -recurse -file -filter *.cs -path c:\source | sls "sometext" | select Path,LineNumber,Pattern,IgnoreCase,@{Name="Line";Expression=@{$_.Line.Trim()}} | export-csv c:\temp\found.csv
```

**Comment by vors** [comment]
Ah, with export-*. Makes sense.

**Comment by iSazonov** [comment]
@SteveL-MSFT Should we have a conclusion from powershell-committee? Won't fix?

**Comment by SteveL-MSFT** [comment]
I don't think this needs a discussion from the Committee.  Seems like a nice to have and individuals can create aliases for themselves.  In the future, if we can get telemetry on cmdlet usage (interactive vs script), perhaps we can add additional aliases at that time if warranted.

**Comment by DavidSeaton** [comment]
Not sure if these examples will help.


```
PS> Get-SmbServerConfiguration | findstr EnableMulti
EnableMultiChannel              : True
```


```
PS> Get-SmbServerConfiguration | ft EnableMulti*

EnableMultiChannel
------------------
              True
```

```
PS> Get-SmbServerConfiguration | fl EnableMulti*

EnableMultiChannel : True
```

Think the findstr is the prettiest solution, unfortunately it is Windows only.

**Comment by PeteMWilson** [comment]
I decided to use `/` as `Select-Object` and `//` as `Select-Object -Expand-Property` as shortcuts when typing in commands (as opposed to running scripts).

What I would like to know how to (easily) do is alias `Select-Object -First 1` and/or create filters/aliases that preset parameters to existing filters.
