### ISSUE TITLE
Encoding error in PSModuleInfo property value

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell#2959]
Very low pri. Just wanted to get this on the record.

The FullName and ScopeName (string) property values of the System.Reflection.Emit.AssemblyBuilder value in the ImplementingAssembly property of PSModuleInfo have the wrong encoding. It looks like UTF-8 output in unicode.

![screenshot 2017-01-05 11 46 27](https://cloud.githubusercontent.com/assets/2954883/21700171/4634a504-d35c-11e6-8fc0-e20af539dd53.png)

**Comment by iSazonov** [comment]
@juneb Could you please update a status of the isssue with latest builds?

**Comment by ThomasNieto** [comment]
Tested this on 7.1 preview 5. This doesn't look to be an issue anymore.

```powershell
PS C:\> (Get-Module class).ImplementingAssembly.FullName
PowerShell Class Assembly, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null
PS C:\> (Get-Module class).ImplementingAssembly.ManifestModule.ScopeName
RefEmit_InMemoryManifestModule
```

**Comment by iSazonov** [comment]
Close until we get new confirmation.
