### ISSUE TITLE
The same number of tests should run on any platform

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2965]
As stated in #2887 each test must be performed on all supported platforms.

- [ ] We need a tool (script) to check this on every day basis
- [ ] We need to analyze test results (pester-tests.xml), identify the problems and correct tests

**Comment by iSazonov** [comment]
How to get pester-tests.xml from Travis job?

**Comment by lzybkr** [comment]
`pester-tests.xml` should now be published as an artifact - see #3003.

**Comment by iSazonov** [comment]
@lzybkr Thanks! I saw the PR. I found code sample for Appveyor but don't undestand how download the Travis artifact. Could you help me?

**Comment by lzybkr** [comment]
It looks like Travis is not like AppVeyor, the artifacts are private and we'd need to do something to share them.  I'm guessing @JamesWTruher knows much more than I, hopefully he can help.

**Comment by iSazonov** [comment]
>How to get pester-tests.xml from Travis job?

Is any updates?

**Comment by SteveL-MSFT** [comment]
@iSazonov I'll look into this today

**Comment by SteveL-MSFT** [comment]
The immediate issue I see is that Travis-CI only supports uploading artifacts to S3 and not Azure.  We can add a step at the end to upload pester-tests.xml to a public Azure blob.

cc @JamesWTruher

**Comment by JamesWTruher** [comment]
it should be possible to download the artifacts from S3. When we finish a test run it reports the upload path of the pester log. For example: run 2427.1 is uploaded to: https://s3.amazonaws.com/powershell-artifacts/PowerShell/PowerShell/2427/2427.1/pester-tests.xml
