### ISSUE TITLE
Code coverage skip some files

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#2966]
As we can see on https://coveralls.io/github/PowerShell/PowerShell some files reported with 0% coverage although the corresponding tests exist and should run successfully. Samples:

[NewTimeSpanCommand.cs](https://coveralls.io/builds/9534326/source?filename=C%2Fprojects%2Fpowershell-f975h%2Fsrc%2FMicrosoft.PowerShell.Commands.Utility%2Fcommands%2Futility%2FNewTimeSpanCommand.cs)
[NewGuidCommand.cs](https://coveralls.io/builds/9534326/source?filename=C%2Fprojects%2Fpowershell-f975h%2Fsrc%2FMicrosoft.PowerShell.Commands.Utility%2Fcommands%2Futility%2FNewGuidCommand.cs)
[NewWinEventCommand.cs](https://coveralls.io/builds/9534326/source?filename=C%2Fprojects%2Fpowershell-f975h%2Fsrc%2FMicrosoft.PowerShell.Commands.Diagnostics%2FNewWinEventCommand.cs)

**Comment by mirichmo** [comment]
@adityapatwardhan Please comment on this

**Comment by adityapatwardhan** [comment]
I am working on a change which will generate logs for the tests that are executed. This will let us know if some tests are not executed or erroring out.

**Comment by iSazonov** [comment]
Clear. Thanks!

**Comment by iSazonov** [comment]
@adityapatwardhan @lzybkr 
I see the opposite that PSReadline files get into the coverage stats though should be removed because PSReadline live in a separate repo and we haven't PSReadline's tests in Powershell repo.

**Comment by iSazonov** [comment]
@adityapatwardhan
Please see link https://coveralls.io/builds/9893487/source?filename=C%2Fprojects%2Fpowershell-f975h%2Fsrc%2FMicrosoft.PowerShell.Commands.Utility%2Fgen%2FSelectObjectStrings.cs
I got the error:
>Source Not Available
The file "C/projects/powershell-f975h/src/Microsoft.PowerShell.Commands.Utility/gen/SelectObjectStrings.cs" isn't available on github. Either it's been removed, or the repo root directory needs to be updated. 

The same result is for all files with `/gen/` in path.
Perhaps it makes sense to exclude them from statistics.

**Comment by lzybkr** [comment]
There are better tools to find unused strings.
PSReadline will naturally disappear when I finish integrating the work from this repo into it's own repo and produce a universal module that works with PowerShell Core and Windows PowerShell.

**Comment by SteveL-MSFT** [comment]
I see coverage data for the files listed originally
