### ISSUE TITLE
Get-ScheduledTaskInfo -taskname parameter does not work as expected

### ISSUE THREAD

**Issue by m8ram** [PowerShell/PowerShell#2967]
Steps to reproduce
------------------
```
> Get-ScheduledTaskInfo -taskname <taskname>
```

Expected behavior
-----------------
Get the same output as 
```
> Get-ScheduledTask -taskname SynchronizeTime|Get-ScheduledTaskInfo


LastRunTime        : 1/6/2017 5:57:57 AM
LastTaskResult     : 1056
NextRunTime        :
NumberOfMissedRuns : 0
TaskName           : SynchronizeTime
TaskPath           : \Microsoft\Windows\Time Synchronization\
PSComputerName     :
```

Actual behavior
---------------
```
> Get-ScheduledTaskInfo -taskname SynchronizeTime
Get-ScheduledTaskInfo : The system cannot find the file specified.
At line:1 char:1
+ Get-ScheduledTaskInfo -taskname SynchronizeTime
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Get-ScheduledTaskI
   nfo], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070002,Get-ScheduledTaskInfo
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

Same issue on PSVersion 5.0.10586.117

**Comment by m8ram** [comment]
Start-ScheduledTask has the same issue.
According to get-help both get-scheduledtaskInfo and start-scheduledtask accept the "-TaskName" parameter, both have it defined as a string just like get-scheduledTask but both get-scheduledtaskInfo and start-scheduledtask throw an error when passed this parameter with a string of an existing taskname

**Comment by m8ram** [comment]
I just found [this documentation for the Get-ScheduledTaskInfo Cmdlet](https://technet.microsoft.com/en-us/library/jj649823.aspx) and they show an example where the option to `-TaskName` contains the full path to the task.
The [documentation for Get-ScheduledTask](https://technet.microsoft.com/en-us/library/jj649808(v=wps.630).aspx) shows that the `-TaskName` parameter of that Cmdlet accepts only a name without a path.

However [the documentation for the Start-ScheduledTask Cmdlet](https://technet.microsoft.com/en-us/library/jj649818(v=wps.630).aspx) also shows an example where the `-TaskName` parameter accepts the name of a task without a path.

**Comment by iSazonov** [comment]
The cmdlets is not still in the Powershell Core project. Maybe better report this issue on UserVoice site.
