### ISSUE TITLE
DSC Pullserver huge amount of "SendReport" requests. Normal?

### ISSUE THREAD

**Issue by J0F3** [PowerShell/PowerShell#2978]
Hi,

I have observed a strange behavior of the DSC Pullserver Reporting feature in WMF 5.1. The clients are making excessive amount of request to send status reports. They make 10-15 request per seconds! Is this normal? 

Example out of an IIS log file which show the request of only one client for 5sec. I think it shows way too much request for this small time frame:
![image](https://cloud.githubusercontent.com/assets/12759579/21761075/e2ca7168-d650-11e6-94b3-3e5ab2cd1a4c.png)

Thanks
Jonas

**Comment by grayzu** [comment]
This may be normal. The way that DSC status reporting works is that it will send a report when there is a connection to the pull server. If there is no connection to the pull server, the agent will cache the status locally for every run. When a connection is reestablished, DSC will send all of the status messages that were cached locally. Once all status messages are successfully sent to the pull server, DSC will only send status after finishing a run.

Does this sound like your  scenario? 

MarkG

**Comment by J0F3** [comment]
Hi Mark,

Yes, this sound like whats happens here. But then I have some questions about the scalability of the Pullserver or the possibilities to configure a DSC Pullserver for high availability.

We have about 180 VMs registerd to our Pullserver. When they have reporting enabled  I can see that the AppPool for the DSC Pullserver has very high CPU and RAM utilization. I additional there are a lot of error in  the event log from ESENT: "The version store for this instance as reached its maximum size of 15MB..."

As consequence the DSC Pull Server becomes almost unresponsive.

So is there a possibilty to load balance or scale out the DSC Pullserver so that the load can be distributed to multiply servers?
And how can a DSC Pullserver made highly aviable (with WMF 5.1 and EDB database)?

Thanks
Jonas

**Comment by grayzu** [comment]
Jonas,

The issue with the ESENT db not using circular logging has been resolved in WMF 5.1. This resolves, your issue, correct? 

MarkG

**Comment by J0F3** [comment]
No, this issue here still exists. It has actually nothing to do with the circular logging. Have also a look at: https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/296. This one is also still open. Even after circular logging is enabled.

In additional the question about the scalability and high availability is still unanswered. I had also questioned the same at the PowerShell-Docs repo. But also, there, still no answer. -> https://github.com/PowerShell/PowerShell-Docs/issues/908 
For production use its very important that we can make the DSC Pullserver HA. But with the current ESENT DB it seems impossible. Or at least, no one know how to do it.

So, some clarifications would be much appreciated!

Thx
Jonas

**Comment by iSazonov** [comment]
@TravisEz13 Should we move the issue in DSC repo and close?

**Comment by TravisEz13** [comment]
DSC is Windows PowerShell and should be reported via User Voice per the issue template.

**Comment by iSazonov** [comment]
@J0F3 Please report via User Voice site.
