### ISSUE TITLE
Prioritize alias when doing command completion

### ISSUE THREAD

**Issue by mattiasunger** [PowerShell/PowerShell#2979]
When doing command completion at least I tend to use aliases more often than not. Perhaps even more often my own specified aliases over others. I therefore feel like it would be a nice improvement to have aliases prioritized, or have the option have it so, over other commands since those are the ones I'm more often looking for.

Another option would be to prioritize latest/most used commands but in general I think aliases are more used than not in these cases.

**Comment by iSazonov** [comment]
@mattiasunger Thanks for your opinion! Now there are several open issues about aliases and completion. You can find them easily. Perhaps you'd better move your motivation in one of those discussions and close this issue as duplicate.

**Comment by mattiasunger** [comment]
@iSazonov Hi! I could definitely do that and I did search for something similar to what I suggested. However I couldn't find one that fitted, perhaps I don't know the correct lingo yet. If you know one feel free to link it so I can close this one.

**Comment by iSazonov** [comment]
@mattiasunger If you do not find a suitable issue, I moreover will not be able to do that :-)

Please specify how your aliases conflict with existing commands? Can you give examples?
Can you use your personal short prefix to exclude conflicts? (`zSelect-Object`)

**Comment by mattiasunger** [comment]
@iSazonov I can of course give my own aliases a prefix to make it easier. An example that happens every now and then are some aliases for opening and building solutions. I.e.

**opensln**
`"ope" -> [tab] -> Open-NetGPO -> [tab] -> openfiles.exe -> [tab] -> opensln`

**buildsln**
`"build" -> [tab] -> .\Build\ -> [tab] -> "BuildAbout.exe" -> [tab] -> BuildConsole.exe -> [tab] x10 -> buildsln
`

I'm not saying I will never use the files or folders but at least as the first word it's probably an alias i'm after.

**Comment by iSazonov** [comment]
Currently we do simple string sorting. To implement the request we have to create more complex custom comparer. It seems not worth the effort.
