### ISSUE TITLE
"Compress-Archive" have no output even if docs state it is: "System.IO.FileInfo"

### ISSUE THREAD

**Issue by as-it** [PowerShell/PowerShell#2989]
Steps to reproduce
------------------
md c:\data1 -Force
$zip = dir c:\windows -File | select -first 1 | Compress-Archive -DestinationPath c:\data1\zip.zip
$zip.GetType()

Expected behavior
-----------------
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     FileInfo                                 System.IO.FileSystemInfo

Actual behavior
---------------
You cannot call a method on a null-valued expression.
At line:1 char:1
+ $zip.GetType()
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      5.1.14393.576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by MaximoTrinidad** [comment]
Just a reminder that Windows PowerShell need to go thru Windows UserVoice at: https://windowsserver.uservoice.com/forums/301869-powershell 

:)

**Comment by iSazonov** [comment]
@as-it Thanks for report the Issue.
 
[Docs](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.archive/compress-archive) say:
> OUTPUTS
System.IO.FileInfo

I fast looked at the module and have not found anything similar to `return FileInfo`.
I suppose it makes sense to initiate a rewrite of the [Microsoft.PowerShell.Archive.psm1](https://github.com/PowerShell/PowerShell/tree/309bf603f9aff9009dce7e725d42b2d4f99f58c9/src/Modules/Shared/Microsoft.PowerShell.Archive) module on C# and fix the issue in the time.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you comment?

**Comment by SteveL-MSFT** [comment]
Please open Archive module issues here: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues

This particular issue has already been addressed in the latest version of the module in the gallery via this PR: https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/18

**Comment by iSazonov** [comment]
@SteveL-MSFT Please still comment my "it makes sense to initiate a rewrite of the Microsoft.PowerShell.Archive.psm1 module on C#"

**Comment by SteveL-MSFT** [comment]
@iSazonov Since Archive isn't one of the modules auto-loaded by PowerShell, I don't think we must convert it to C# like new-guid which affected startup time by bringing in the parser.  However, I think when we start adding features to the Archive module (like https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19), we should evaluate if it would be more productive to move to C#.

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks!
