### ISSUE TITLE
PowerShell Open Source - Compress-Archive not working.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#2990]
Steps to reproduce
------------------
 Compress-Archive -Path c:\Temp -DestinationPath c:\TempLog\Tempzip.zip

or 

 Compress-Archive -Path c:\Temp -DestinationPath c:\Temp\Tempzip.zip

Expected behavior
-----------------
To create Tempzip.zip file on folder c:\TempLog

Actual behavior
---------------
Error message comes up:

Exception calling "Write" with "3" argument(s): "Stream was too long."
At C:\program files\powershell\6.0.0.14\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:819
char:29
+ ...                     $destStream.Write($buffer, 0, $numberOfBytesRead)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

Environment data
----------------
Windows 10 Pro Insider Preview Build 14986

```powershell
PS C:\Program Files\PowerShell\6.0.0.14> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.14
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSEdition                      Core

```
![compressarchiveissue_2017-01-10_12-16-51](https://cloud.githubusercontent.com/assets/19892435/21816631/c0bc4d2e-d72e-11e6-9da5-cedcd570e384.jpg)

**Comment by MaximoTrinidad** [comment]
By the way, it does work in Linux Ubuntu 16.04.1
![compressarchivegood](https://cloud.githubusercontent.com/assets/19892435/21816993/40a98da2-d730-11e6-8fd1-c59705e7e64a.png)

**Comment by iSazonov** [comment]
@MaximoTrinidad  Please specify what is a size of the source data?
According to the [documentation](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.archive/compress-archive),  limit is 2 Gb.

**Comment by MaximoTrinidad** [comment]
Ah!!  Thanks @iSazonov 
Sorry! I should have checked for the size limitation.
Closed the incident.

Greatly Appreciated,
Maximo Trinidad

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad the 2GB limit is an unfortunately limitation of the .Net api being used.  There is an open issue for Zip64 support: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/19
