### ISSUE TITLE
Possible bug embedding `using module` inside a method call

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#2992]
_From @rjmholt on January 11, 2017 2:12_

Was deleting a `using module Foo` statement inside a `[powershell]::AddStatement(...)` method call. Screenshot attached:
![psbug](https://cloud.githubusercontent.com/assets/7009879/21832463/2d0ba32c-d760-11e6-9eb9-ff4d38a9684f.PNG)

_Copied from original issue: lzybkr/PSReadLine#489_

**Comment by iSazonov** [comment]
I can't reproduce (for both WindowsPowershell and Powershell Core):
```powershell
PS C:\temp> $a=[powershell]::Create()
PS C:\temp> $a.AddStatement(using module f)
>>
At line:1 char:17
+ $a.AddStatement(using module f)
+                 ~
Missing ')' in method call.
At line:1 char:17
+ $a.AddStatement(using module f)
+                 ~~~~~
Unexpected token 'using' in expression or statement.
At line:1 char:31
+ $a.AddStatement(using module f)
+                               ~
Missing a newline or semicolon.
At line:1 char:17
+ $a.AddStatement(using module f)
+                 ~~~~~~~~~~~~~~
A 'using' statement must appear before any other statements in a script.
At line:1 char:31
+ $a.AddStatement(using module f)
+                               ~
Unexpected token ')' in expression or statement.
At line:1 char:17
+ $a.AddStatement(using module f)
+                 ~~~~~~~~~~~~~~
Could not find the module 'f'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

PS C:\temp>
```

**Comment by lzybkr** [comment]
I repro'd the problem at the console in Windows PowerShell - there might be something about how `PSReadline` is invoking the parser, but I moved the bug from `PSReadline` because the call stack makes it clear it's an engine problem, not a `PSReadline` problem.

**Comment by iSazonov** [comment]
@lzybkr Could you post the exact code to reproduce the problem? (Then I'll try to debug and fix).
Please clarify - Is there the problem in Powershell Core too or only in Windows Powershell?

**Comment by lzybkr** [comment]
Interactive repo - just typing in from the screen shot. I think it was both, will need to double check.

**Comment by lzybkr** [comment]
Confirmed, repros in full and core, just type `$foo.bar(using module)`, you'll get the exception after typing the closing paren.

**Comment by iSazonov** [comment]
Oh, yes.  I'll try to debug on next week.

**Comment by rjmholt** [comment]
Apologies — I saw the reference to my PR appear here and thought that was enough; I know for next time.

It looks like your fix is considerably more useful.

**Comment by iSazonov** [comment]
@rjmholt The cross-references don't cause notifications to be sent by mail, only posts.
