### ISSUE TITLE
Add WindowsUBR property to Get-ComputerInfo

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#2994]
Here's the info for UBR:

New Property Name in Get-ComputerInfo: WindowsUBR
Registry Key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
Registry Value: UBR

It's stored in the registry as a DWORD, but should be converted to an int for the WindowsUBR property.

TFS:10041234

**Comment by SteveL-MSFT** [comment]
UBR = Update Build Revision
