### ISSUE TITLE
[Idea] - Addition of Video Series of Powershell with Mac OSX  (Beginner Series)

### ISSUE THREAD

**Issue by azurechamp** [PowerShell/PowerShell#2999]
I got a chance to prepare some videos on PowerShell using Mac with Visual Studio Code. I am presenting an idea if we can include that in README.md as material to get started with PowerShell on OSX.

Here is my playlist on Youtube for review.
[YouTube Series on PowerShell on Mac OSX](https://www.youtube.com/playlist?list=PL4URqfIIQcfBOtaSXl5tu4tYvpApw91Ew)

Thanks

**Comment by SteveL-MSFT** [comment]
@muhammad92 very cool!  I think we can add a link to your videos in https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/README.md, but I'm tagging this for @PowerShell/powershell-committee to review first

**Comment by muhammad92** [comment]
@SteveL-MSFT  Great!

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and the recommendation is to add link to your videos to https://github.com/janikvonrotz/awesome-powershell#videos.  Thanks!
