### ISSUE TITLE
PowerShell Web Access based on kestrel

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/PowerShell#3004]
As I couldn't find documentation, have you thought about removing the dependency of PSWA on IIS and .NET and instead base it on Kestrel and .NET Core  (or Node.js) ?

**Comment by SteveL-MSFT** [comment]
Good suggestion, however PowWa is outside the scope of PowerShell Core (not owned by this team).

**Comment by iSazonov** [comment]
Any plans to put PSWA on GitHub?

**Comment by SteveL-MSFT** [comment]
There are currently no plans to OSS PowerShell Web Access.

**Comment by iSazonov** [comment]
So we can close the Issue.
