### ISSUE TITLE
We need to host our endpoint of http://httpbin.org/ for the web cmdlets tests

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#3012]
Steps to reproduce
------------------
http://httpbin.org is not very reliable, so we need to host our own endpoint to validate the web cmdlets. To do this, please take a look at https://github.com/Runscope/httpbin, and see Deploy to Heroku. Perhaps there is a way that we can host our own web service on an Azure VM.

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
@markekraus Do we ready to close the Issue?

**Comment by markekraus** [comment]
Yes. this work is being tracked int #2504. This issue can be closed.
