### ISSUE TITLE
Move Windows Native Components to a Sub-project or Separate Project

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#3014]
The WinRM plugin for PowerShell introduces the Visual Studio and Windows 10 SDK dependencies. These are heavyweight components that slow down the build time. Moving the native Windows components to a separate project or sub-project would decouple this dependency and improve build times, CI passes, etc.

**Comment by iSazonov** [comment]
What is Sub-project or Separate Project? New GitHub Repo? If so only maintainers can do this.

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
Current plan is to just pull the native binaries from the last official release at build time.  Since the native code hasn't changed much at all, no need for a separate repo for now.

**Comment by SteveL-MSFT** [comment]
Feedback from @daxian-dbw that makes sense to me:

- I think we should by default continue to build native component for OSX and Linux. Unlike pwrshplugin.dll, libpsl is much more crucial to PSCore (it has important native implementations that PS engine needs to call in via P/inovke), and it changes far more frequently than the WinRM plugin dll -- for example, @jeffbi made changes to it to fix the cyclic symbolic link detection issue in file system provider; @PaulHigin made changes to it to create the SSH process for remoting.
- For pwrshplugin.dll, pwrshplugin.pdb and Install-PowerShellRemoting.ps1, they should be made into a NuGet package and published to powershell-core feed. So we can depend on dotnet-cli to handle them and it's also more robust and cleaner. When we need to make changes to pwrshplugin.dll, we just publish a new version of the NuGet package.

**Comment by iSazonov** [comment]
Native components don't seem so slow to build, I don't have a problem with that. Also we have some opened Issues for remoting and console and  a Issue for refactoring native components.

**Comment by daxian-dbw** [comment]
@iSazonov yes, the building itself doesn't take much time, the problem here is `Start-PSBootstrap` for Windows -- building `pwrshplugin.dll` requires to install win10 SDK and Visual Studio, and that's too heavy. If we can move WinRM remoting components to NuGet package, then a regular user don't need to install them on bootstrap anymore.

**Comment by iSazonov** [comment]
Locally we don't install SDK every time. For CI we could use a build cache.
