### ISSUE TITLE
Get-ComputerInfo : Unable to find an entry point named 'GetFirmwareType' in DLL 'kernel32.dll'."

### ISSUE THREAD

**Issue by n3l5** [PowerShell/PowerShell#3023]
Error Message:
"Get-ComputerInfo : Unable to find an entry point named 'GetFirmwareType' in DLL 'kernel32.dll'."

Environment:
------------------
Windows Management Framework 5.1
Operating System: Windows 7 x64

Examples
------------------
```
PS C:\Users\user> Get-ComputerInfo -Property OsInstallDate
Get-ComputerInfo : Unable to find an entry point named 'GetFirmwareType' in DLL 'kernel32.dll'.
At line:1 char:1
+ Get-ComputerInfo -Property OsInstallDate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ComputerInfo], EntryPointNotFoundException
    + FullyQualifiedErrorId : System.EntryPointNotFoundException,Microsoft.PowerShell.Commands.GetComputerInfoCommand

PS C:\Users\user> Get-ComputerInfo -Property TimeZone
Get-ComputerInfo : Unable to find an entry point named 'GetFirmwareType' in DLL 'kernel32.dll'.
At line:1 char:1
+ Get-ComputerInfo -Property TimeZone
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ComputerInfo], EntryPointNotFoundException
    + FullyQualifiedErrorId : System.EntryPointNotFoundException,Microsoft.PowerShell.Commands.GetComputerInfoCommand
```

```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@n3l5 Thanks for bug report!

`GetFirmwareType`[ is introduced in Windows 8 and Windows Server 2012 ](https://msdn.microsoft.com/en-us/library/windows/desktop/hh848321%28v=vs.85%29.aspx)

**Comment by joeyaiello** [comment]
Given the behavior isn't there on Win7, I'm not sure what we can do other than do a better of job of erroring out. We also wouldn't ship a change for that unless we had a hypothetical WMF 5.2, though I'm not speaking here to whether that's happening or not.

**Comment by n3l5** [comment]
Unless there is an option to feature request a kernel fix for Win 7 to support this, can be closed out since this appears to be a kernel feature and Win 7 is on the way out.

**Comment by joeyaiello** [comment]
Thanks @n3l5!

**Comment by zii-dmg** [comment]
Isn't solution is just one `if` check for windows version in [GetComputerInfoCommand.cs](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs#L561)?

**Comment by SteveL-MSFT** [comment]
We should wrap the api calls so this fails silently.

**Comment by jeffbi** [comment]
Just as a point of interest, at the time this cmdlet was written the target OS was Win10.

Fortunately there aren't too many native API calls, so wrapping them shouldn't be too onerous.

@SteveL-MSFT  I can take this one if you like.

**Comment by iSazonov** [comment]
Perhaps it is time to start porting this cmdlet instead of doing partial fixes. It would be good to do it in Beta time.

**Comment by SteveL-MSFT** [comment]
Making it cross-platform is a pretty big task and probably something we'd do for 6.1.0.  @jeffbi it should be pretty straightforward to wraps so they `silentlycontinue` for current release.

**Comment by zii-dmg** [comment]
Alpha 18 no longer crash on `GetFirmwareType` in Windows 7, but other strange crash - #3541.
