### ISSUE TITLE
Document and setup up Fedora releases

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#3026]
#2982 added the ability to build Fedora, but we don't have updated documentation or a release plan for it.

**Comment by andschwa** [comment]
@SteveL-MSFT Should we close this?

**Comment by SteveL-MSFT** [comment]
cc @joeyaiello do we still need this?  Don't recall any customers asking for this

**Comment by iSazonov** [comment]
We already have Fedora distributive and instructions.
