### ISSUE TITLE
Set-AdUser does not do input validation on -HomeDrive

### ISSUE THREAD

**Issue by pv2b** [PowerShell/PowerShell#3030]
Steps to reproduce
------------------

```Set-Aduser johndoe -HomeDrive H -HomeDirectory \\file01\home$\johndoe```

Log in interactively as Johndoe, look in explorer and see what drive letter the home directory is mapped to.

Expected behavior
-----------------

When John Doe logs in, the H: drive is mapped to his home directory ```\\file01\home$\johndoe```

Alternatively, an error message should be thrown by Set-Aduser because of the incorrect setting of ```-HomeDrive H``` rather than ```-HomeDrive H:```

Actual behavior
---------------

When John Doe logs in, the Z: drive is mapped to his home directory ```\\file01\home$\johndoe```

The problem is actually in the invocation of Set-AdUser. The correct invocation would be:

```Set-AdUser johndoe -HomeDrive H: -HomeDirectory \\file01\home$\johndoe```

However, since Set-AdUser does not do any input validation, the caller is not alerted to this problem. Different windows components will show differnet info, ADUC will show it like it's correct while windows itself will just fall back to Z: for whatever reason.

One possible approach would be to simply put a ValidateRegex like "^[A-Z]:$" or something, another would be to tack on a : if it's missing, but that would cause scripts to fail on older versions of powershell if written against newer versions.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      5.0.10586.117                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                   10.0.10586.117                                                                                                                 
CLRVersion                     4.0.30319.36373                                                                                                                
WSManStackVersion              3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                        

```

**Comment by joeyaiello** [comment]
Unfortunately, this GitHub project is only for issues relating to PowerShell 6.0+, and the PowerShell modules that ship with it. 

Feel free to refile your feedback on the [Active Directory UserVoice](https://windowsserver.uservoice.com/forums/304621-active-directory) where someone from the AD team can take a look at it. Thanks!
