### ISSUE TITLE
Get-WinEvent does not read all TraceLogging event details

### ISSUE THREAD

**Issue by letmaik** [PowerShell/PowerShell#3035]
Steps to reproduce
------------------
1. Use [TraceLogging](https://msdn.microsoft.com/en-us/library/windows/desktop/dn904637(v=vs.85).aspx) and record some events.
2. Run:
```ps
$Events = Get-WinEvent -Path trace.etl -Oldest -MaxEvents 500
$Events[401] | Format-List *
```

Expected behavior
-----------------
The information should correspond to what can be seen when opening the file in Windows Performance Analyzer.

Actual behavior
---------------
Fields like task name, or custom fields are not included and can't be accessed:

```
> $Events[401] | Format-List *

Message              :
Id                   : 1362
Version              : 0
Qualifiers           :
Level                : 5
Task                 : 0
Opcode               : 1
Keywords             : 0
RecordId             : 401
ProviderName         :
ProviderId           : 3970f9cf-2c0c-4f11-b1cc-e3a1e9958833
LogName              :
ProcessId            : 9880
ThreadId             : 5260
MachineName          : ***
UserId               :
TimeCreated          : 23/01/2017 21:49:31
ActivityId           : 486882ca-72a5-0000-56e0-7848a572d201
RelatedActivityId    :
ContainerLog         : c:\...\trace.etl
MatchedQueryIds      : {}
Bookmark             : System.Diagnostics.Eventing.Reader.EventBookmark
LevelDisplayName     : Verbose
OpcodeDisplayName    : Start
TaskDisplayName      :
KeywordsDisplayNames : {}
Properties           : {}
```

Are the TraceLogging-generated traces introduced in Windows 10 supported by this cmdlet?

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@letmaik 
1. Please try `$Events[401] | Format-List * -Force`
2. The cmdlet use Windows standard API call to read events. So if it is not working then most likely this is a limitation of the API.

**Comment by letmaik** [comment]
I had tried `-Force` but got the same results.
What underlying API is this using? Then I could check that.

**Comment by iSazonov** [comment]
You can start with [Get-WinEvent](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs)
Target is WEVTAPI https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs#L542

**Comment by letmaik** [comment]
It seems that the [trace data helper APIs](https://msdn.microsoft.com/en-us/library/windows/desktop/ee441329(v=vs.85).aspx) can be used to decode the event data, according to the [About TraceLogging](https://msdn.microsoft.com/en-us/library/windows/desktop/dn904632(v=vs.85).aspx) page:
> [TraceLogging] Events are self-describing which means that a binary containing the instrumentation manifest does not need to be registered on the system in order to use the Trace Data Helper (TDH) APIs to decode and show events.

Do you think that this is in any way integrateable to Get-WinEvent with the current Win APIs used?

**Comment by iSazonov** [comment]
My understanding is that current `Get-WinEvent` code stack based on ["static" property set](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/NativeWrapper.cs#L829)
If we want to decode the self-described events and expose them, we will need to migrate to a dynamic property set. It looks like a lot of work.

I am not an expert in the WEVTAPI so maybe Powershell PG comment this.
I can say that this addition would be useful for users.
I also see a lot of questions that are likely to be disclosed in a Powershell RFC prior to implementation.

**Comment by letmaik** [comment]
Just wanted to say that I have been successfully using the [TraceEvent library](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent) within C# to read TraceLogging events.

**Comment by letmaik** [comment]
And here's a snippet using that within a powershell script:

```powershell
#Require -Version 5.0
using namespace Microsoft.Diagnostics.Tracing
using namespace Microsoft.Diagnostics.Tracing.Etlx

param (
    [Parameter(Mandatory=$true)][string]$etlPath
)

$ErrorActionPreference = "Stop"

(new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/ligershark/nuget-powershell/master/get-nugetps.ps1") | iex

$libpath = (Get-NuGetPackage Microsoft.Diagnostics.Tracing.TraceEvent -binpath)
Add-Type -Path (Join-Path $libpath 'Microsoft.Diagnostics.Tracing.TraceEvent.dll')

$traceLog = [TraceLog]::OpenOrConvert($etlPath)

$events = $traceLog.Events.Filter({ $args[0].ProviderName -eq "MyProvider" })
echo $events
```

This has full access to all data, very comprehensive in general with lots of helper functionality.

**Comment by iSazonov** [comment]
I see the Microsoft TraceEvent Library is very popular - over 240000 downloads and actively developed.
It would be useful to integrate these capabilities in Powershell Core.
@powershell-committee @SteveL-MSFT Could you consider this?

**Comment by SteveL-MSFT** [comment]
@iSazonov this seems like a great enhancement

**Comment by iSazonov** [comment]
@SteveL-MSFT Can MSFT move the TraceEvent Library sources in the Powershell repo?

**Comment by SteveL-MSFT** [comment]
@iSazonov why do we need the sources?  shouldn't referencing it from nuget be sufficient?

**Comment by iSazonov** [comment]
We would try to merge it with Get-WinEvent.

**Comment by MaximoTrinidad** [comment]
Sorry to ask!

But, is this incident considered a PowerShell Core or Windows PowerShell issue?  I've notice a lot of Windows PowerShell issue been submitted under PowerShell Core.

So, how about providing a different tag(label) so it can be identified? Or, does it really matter?

I just want to be clear and help others on how-to submit the feedbacks.

Thanks,
:)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad Get-WinEvent ships with PSCore for Windows.  We wouldn't take these changes for Windows PowerShell.

@iSazonov seems better to use it as a library

**Comment by MaximoTrinidad** [comment]
Thanks @SteveL-MSFT .. I appreciate your quick response. 
:)

**Comment by iSazonov** [comment]
@SteveL-MSFT Have we examples of such integration in the Powershell repo?

**Comment by SteveL-MSFT** [comment]
@iSazonov we do it today with Newtonsoft.Json

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks! Good example!

I shortly have look at the TraceEvent Library.
We could not only expand Get-WinEvent to support this trace format.
Also it would be interesting to create trace events, to manipulate trace files...
On the other hand why we don't use low-level trace internally in Powershell Core?

**Comment by iSazonov** [comment]
@vancem Could you please comment the discussion and help enhance the PowerShell capabilities for working with trace events?

**Comment by vancem** [comment]
> @vancem Could you please comment the discussion and help enhance the PowerShell capabilities for working with trace events?

You have a bunch of possible options here.   As @ISazonov indicates you can do a bunch more.   But frankly I think just getting Get-WinEvent to work well both (ideally for both files and 'real time' monitoring), would be a very reasonable design point (at least to start).    Ideally it could decode

1) TraceLogging style events.
2) EventSource events that happen to not use TraceLogging.  

Both of these may require a bit of extra effort.   One solution is to simply use the TraceEvent library to do this decoding (note that you do NOT have to call 'OpenOrConvert' as was done above to use the library (since that complicates things for the end user).   The TraceEvent library can open ETL files directly (as well as real time session) and parse them fully.   

it is also possible to call native windows APIs (the Tdh* APIs that were mentioned).   This is effectively how the TraceEvent library works.   The value of doing this is that you avoid the dependency on the TraceEventLibrary.  It is more work, but you grab much of what you need from the TraceEvent source code (it is available on the https://github.com/Microsoft/PerfView GitHub repo).    

I can help with details of doing this (or of using the TraceEvent library if you want to just use that).   Adding this is probably reasonably easy (< 1man week).
