### ISSUE TITLE
PSReadLine does not support Ctrl-Left and Ctrl-Right on Ubuntu

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#3038]
Ctrl-Left and Ctrl-Right do not move the cursor to the previous or next word.

Steps to reproduce
------------------
1: Type a cmdlet name and a single parameter to ensure white space appears, such as Get-Content -ReadCount
2: Use Ctrl-Left to tab to the start of the word ReadCount
3: Use Ctrl-Left to move to the start of the word Content

Expected behavior
-----------------
The cursor is moved the R in ReadCount followed by C in Content

Actual behavior
---------------
The cursor does not move.

Environment data
----------------
Ubuntu Desktop 16.04

PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by lzybkr** [comment]
I believe this is by design - on Linux we default to using `Emacs` key bindings.

If I switch to `Windows` bindings, it works as expected:

```PowerShell
Set-PSReadlineOption -EditMode Windows
```

**Comment by iSazonov** [comment]
I can confirm that it works as expected with `Set-PSReadlineOption -EditMode Windows`.

**Comment by javidcf** [comment]
For anyone stumbling upon this, if you do not want to use `Windows` mode but still want ctrl+left and ctrl+right to move through words, you can use:

```pwsh
Set-PSReadLineKeyHandler -Chord Ctrl+LeftArrow BackwardWord
Set-PSReadLineKeyHandler -Chord Ctrl+RightArrow ForwardWord
```
