### ISSUE TITLE
VSCode removes Explorer "Run wit PowerShell" menu entry.

### ISSUE THREAD

**Issue by olivier-spinelli** [PowerShell/PowerShell#3044]
Steps to reproduce
------------------
Open a .ps1 with VSCode after having installed PowerShell support.

Expected behavior
-----------------
In Explorer I still benefit of "Run wit PowerShell" in Explorer menu entry.

Actual behavior
---------------
Explorer's menu item is no more available.
Closing VSCode does not restore the expected behavior. Rebooting does.

Environment data
----------------
$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by daviwil** [comment]
Hi Oliver, this is likely an issue with VS Code itself, we don't do anything specific to change the Explorer context menu for .ps1 files.  I'd recommend filing this issue over on their GitHub repository:

https://github.com/Microsoft/vscode/issues

**Comment by olivier-spinelli** [comment]
Thanks, I will investigate a bit more and report this.
