### ISSUE TITLE
New-localuser cmdlet fails length check on Name parameter

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#3045]
Update: This is a documentation bug. Example 3 is not correct and should be removed.

The cmdlet should accept longer names such as MSAs as specified in the [MSDN help](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.localaccounts/new-localuser).

```powershell
PS F:\> nlu -name abcdefghijklmnopqrstuvwxyz
New-LocalUser : Cannot validate argument on parameter 'Name'. The character length of the 26 argument is too long. Shorten the character length of the argument so it is fewer than or equal to "20" characters, and then try the command again.
At line:1 char:11
+ nlu -name abcdefghijklmnopqrstuvwxyz
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-LocalUser], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.NewLocalUserCommand
```
Version:
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

TFS:10558531

**Comment by iSazonov** [comment]
@mirichmo Can you post the MSDN help link?

**Comment by mirichmo** [comment]
Updated

**Comment by iSazonov** [comment]
The help say:
> A user name can contain up to 20 uppercase characters or lowercase characters.
I believe that this happens from [here](https://msdn.microsoft.com/en-us/library/ms679635(v=vs.85).aspx)

**Comment by jeffbi** [comment]
The page the original decision came from was [here](https://technet.microsoft.com/en-us/library/cc770642.aspx).

**Comment by mirichmo** [comment]
The original SAM API (pre-Win 7?) had that restriction, so it is documented in those locations, in net.exe, and lusrmgr.msc. However, I suspect that the new SAM API allows longer names (up to 255+?), so we may be able to relax the restriction or get rid of it.

**Comment by iSazonov** [comment]
Seems the documentation is still not updated. I could find nothing about this change. Is there a public description?

**Comment by jeffbi** [comment]
I just stepped through the new-localuser cmdlet on my Windows 10 box with the name-length validation removed. The SAM API call fails with INVALID_USER on user names greater than 20 characters.

**Comment by mirichmo** [comment]
Confirmed. I looked through the SAM source code and double-checked account name validation. The limit is 20 characters for users and 256 for groups. 

I am going to re-classify this as a documentation bug.

**Comment by joeyaiello** [comment]
@mirichmo make sure to file doc bugs for already shipped code in [http://github.com/PowerShell/PowerShell-Docs](PowerShell-Docs). That way @jpjofre can track it easily

**Comment by joeyaiello** [comment]
This issue was moved to PowerShell/PowerShell-Docs#997
