### ISSUE TITLE
Smartcard support for Get-Credential and PSRP

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3048]
Originally filed at https://github.com/PowerShell/PowerShell-Docs/issues/990

Quote from @aarju:

> I would like to be able to use a smartcard + pin to authenticate a new PSSession on a remote host. The smartcard can be selected via the Get-Credential popup window, but the credential object created will not successfully authenticate to the domain or other hosts.
> 
> The enterprise network I work on has separation of account privileges along with enforcing 2FA for all accounts. This means that I have multiple smartcard readers on my system, and when I need to run as administrator I have to use the smartcard + pin to start a new powershell prompt with my admin account. When I try New-PSSession with a remote computer I receive a winRM client error because default authentication fails without HTTPS transport. My current work around for executing remote PSSessions is an exception to policy allowing login to an admin account without 2FA, not an ideal situation.

**Comment by jcotton42** [comment]
Is there any progress on this issue?

**Comment by SteveL-MSFT** [comment]
This is not part of 6.0.0 release plan.  We should probably expose Authn interfaces making it pluggable.

**Comment by jdix531** [comment]
Looking forward to this enhancement (we all are here).

**Comment by milesgratz** [comment]
Need this functionality as well. Also hoping to see this fixed too: [Get-Credential does not work for smart cards with multiple certificates] (https://github.com/PowerShell/PowerShell/issues/4670)

**Comment by charleswj** [comment]
Over a year out, has there been any progress?

**Comment by SteveL-MSFT** [comment]
No update on this as no one on my team is actively working on this.  Since we support PSRP over SSH, you can use two-factor auth over SSH (just normal OpenSSH two factor support).  Changed to WinRM would be required to support this over WSMan and there are no plans to add capabilities to WinRM.

**Comment by kilasuit** [comment]
@SteveL-MSFT any updates on this as there are MANY orgs that will be adopting MFA (mine have) and this wukk be a limitation that become a barrier of entry

I know that you suggest that there are no plans to add WinRM capabilities but surely there likely to be enterprises that will require this functionality?

**Comment by SteveL-MSFT** [comment]
@kilasuit tried to setup TFA for OpenSSH which works, but fails with PSRP.  Opened https://github.com/PowerShell/PowerShell/issues/6439

**Comment by SteveL-MSFT** [comment]
@kilasuit I've verified that MFA works with PSRP over SSH (at least macOS to Linux) using google-authenticator and pub key auth.  Any auth methods used with SSH should just work with PowerShell remoting as PowerShell Core doesn't do any of the authentication and hands it off completely to SSH.

**Comment by joeyaiello** [comment]
Just to clarify, there's an existing workflow on Windows PowerShell that is *kind of* 2FA where a user:

* runs Get-Credential to get the username/password UI
* selects a smartcard (physical or virtual) from a dropdown
* inputs a PIN

I don't believe we can support this workflow easily on non-Windows platforms, but we should strongly consider it for 6.2 on Windows. One possible implementation would be to provide a parameter to Get-Creedential that can tab-complete into available smartcards.

**Comment by manivasagam1130107** [comment]
@joeyaiello

The existing workflow doesn't seem to work, it gives me winrm issues like mentioned above...can you please advise what version should I use to get the existing workflow working?

**Comment by Nahuatl-Mexica** [comment]
Still any update on this? I work in a large environment where we use smart cards for daily logins,  and would like to see if this is an option to use with Posh. This would be great for an enterprise environment like the DOD, or DOS who rely on CAC authentication for everything.
