### ISSUE TITLE
Feature: powershell.exe mouse clickable file paths

### ISSUE THREAD

**Issue by Ciantic** [PowerShell/PowerShell#3054]
Suppose I have devised some magical command line, e.g.
gci -recurse *.php | select name, Directory, LastWriteTime | sort lastwritetime

And now I have list of files and paths in front of me, it would be useful to be able to click or ctrl+click on the powershell window to open the path in file explorer. 

Open question is how it should behave if I ctrl click a file path (vs. directory path) should it give options to open the file or browse to the path?

I think command Ctrl+Click is somewhat defacto e.g. for URLs in other programs like nutty etc.

Thanks for considering.

**Comment by joeyaiello** [comment]
I'm not *positive* on this,, but I believe this would require changes to the console host before PowerShell could do anything.  

In fact, it looks like there's already a UserVoice suggestion for the Windows conhost: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/6511299-make-links-clickable

Feel free to upvote that one!

**Comment by iSazonov** [comment]
I would even say that it is not a powershell and conhost function, it is rather VT and operating system function similar to launch default applications in cmd.exe.

**Comment by Ciantic** [comment]
I'm closing this since the uservoice voting addresses this already.

**Comment by lzybkr** [comment]
Console applications like PowerShell can implement features like this (process mouse input) but very few do these days.

That said, this feature makes sense for conhost to support as that helps all console applications.
