### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by Lantizia** [PowerShell/PowerShell#3056]
Not a bug...

Just a suggestion/feature request that this page...

https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md

Should probably also mention that official Microsoft repositories seem to exist for RHEL, SLES and Ubuntu over at packages.microsoft.com.

You can see them in use on this page...

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools

The *same* repository details on that page also work for powershell (you can see in the repository that todays alpha 15 release is already in there - so someone is maintaining it)...

http://packages.microsoft.com/ubuntu/16.04/prod/pool/main/p/powershell/

At least if people use a repository rather than individual packages... they'll get updates with the rest of their system.  Now if only they can throw Skype in there too... hmmm...

**Comment by mirichmo** [comment]
@raghushantha FYI

**Comment by joeyaiello** [comment]
Yeah, we're just still playing with it. @Lantizia keep your eyes peeled on [our blog](https://blogs.msdn.microsoft.com/powershell) for more details. We should be pushing a PR to install instructions around the same time.

**Comment by SteveL-MSFT** [comment]
https://blogs.msdn.microsoft.com/powershell/2017/02/01/installing-latest-powershell-core-6-0-release-on-linux-just-got-easier/
