### ISSUE TITLE
Add operating system name to Mac OS X package

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3058]
For PowerShell Core distribution packages, every other package has the operating system name in the file name, except for the Apple Mac OS X one, with a `.pkg` file extension. 

I'd suggesting adding the operating system into the package's file name, to make it clear which OS it's intended for.

![screen shot 2017-01-27 at 9 06 35 am](https://cloud.githubusercontent.com/assets/466713/22377683/18b335e4-e470-11e6-82a8-60347720648d.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by kwiknick** [comment]
This has to be done by someone with access to the builds correct?  I see that the appveyor builds publish most of the installation artifacts.  I looked over the code, and nothing in there packages it up as far as I can see.
