### ISSUE TITLE
When using Invoke-SqlCmd in a loop, print buffer doesn't get flushed before a Read-Host is executed

### ISSUE THREAD

**Issue by Gemstar007** [PowerShell/PowerShell#3060]
Steps to reproduce
------------------
function Bug {
  while($true) {
    “Before Output”
    Invoke-SqlCmd -Query "SELECT TOP 10 *  FROM YourTable” -Server "YourServer" -Database "YourDB"    
    "After Output"
    Read-Host -Prompt “press a key…”
  }
}
Bug

Expected behavior
-----------------
“Before Output” -> SqlCmd results -> “After Output” -> “press a key…” ->(returned Read-Host value) -> LOOP.

Actual behavior
---------------
“Before Output” -> “press a key…” -> SqlCmd results ->  “After Output” -> (returned Read-Host value) -> LOOP.

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      5.1.15023.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15023.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
Invoke-Sqlcmd cmdlet is not part of the Powershell Core.
Please report the issue on [UserVoice site](https://windowsserver.uservoice.com/forums/301869-powershell).

**Comment by Gemstar007** [comment]
This was filed after speaking with folks from Powershell and from SQL.  SQL folks say this is an issue with the default powershell output, not their code.

**Comment by iSazonov** [comment]
The following code works as expected:
```powershell
function Bug {
 while($true) {
    "Before Output"
    Get-Command Get-Alias
    "After Output"
    Read-Host -Prompt "press a key…"
 }
}
```
@Gemstar007 We need more details.

**Comment by joeyaiello** [comment]
@Gemstar007 could you tell me with whom you spoke on the SQL team? I can follow up with them offline.

**Comment by SteveL-MSFT** [comment]
TFS:10131325

**Comment by matteot31415** [comment]
As I told @joeyaiello in e/mail, this does not look like an issue with the SQL PowerShell cmdlet. It seems more related to dubious handling of arrays or collections of 'DataRow' objects.

Here's an independent repro:
`# Create a dummy table
$table = New-Object "System.Data.DataTable" "Foo"

# Create a couple of columns
# and add them to the table
$dc = New-Object "System.Data.DataColumn"
$dc.DataType = [System.Type]::GetType("System.String")
$dc.ColumnName = "name";
$table.Columns.Add($dc)
$dc2 = New-Object "System.Data.DataColumn"
$dc2.DataType = [System.Type]::GetType("System.Int32")
$dc2.ColumnName = "object_id"
$table.Columns.Add($dc2)

# Populate two rows..
$row = $table.NewRow()
$row["name"] = "AAA"
$row["object_id"] = -103

$row2 = $table.NewRow()
$row2["name"] = "BBB"
$row2["object_id"] = -104

function Bug {
  while($true) {
    Write-Host "Before Output"
    @($row, $row2)
    Write-Host "After Output"
    Read-Host -Prompt "press a key..."
  }
}
`
Keep pinging me on e/mail, if you have questions. @Gemstar007: I'm also curious to know who you spoke on the SQL Team (I own SQL PowerShell and I don't recall talking to you... Lol)

-Matteo

**Comment by MaximoTrinidad** [comment]
Hi @Gemstar007 

Yes! Invoke-SQLCmd or any SQL PowerShell cmdlets are not supported in PowerShell Open Source (only on Windows Systems).  If the problem in Windows PowerShell 5,1 then it needs to be addressed thru UserVoice in the Windows section: 
https://windowsserver.uservoice.com/forums/295047-general-feedback 

Also, you can use the following link for specific SQL PowerShell cmdlets issues: https://trello.com/b/NEerYXUU/powershell-sql-client-tools-sqlps-ssms 

Hope this helps,
:)

**Comment by SteveL-MSFT** [comment]
This seems to be an issue with System.Data.DataTable than SQL cmdlet.  We should investigate why the output is out-of-order as this may not be unique to that type.

**Comment by iSazonov** [comment]
I can not reproduce in PS 6.0 alfa.16:
```powershell
PS C:\Program Files\PowerShell\6.0.0.16> $table = New-Object "System.Data.DataTable" "Foo"
New-Object : A constructor was not found. Cannot find an appropriate constructor for type System.Data.DataTable.
At line:1 char:10
+ $table = New-Object "System.Data.DataTable" "Foo"
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand

PS C:\Program Files\PowerShell\6.0.0.16> [System.Data.DataTable].Assembly

GAC    Version        Location
---    -------        --------
       v4.0.30319     C:\Program Files\PowerShell\6.0.0.16\System.Data.Common.dll
```

CoreFX already has the constructor.

**Comment by MaximoTrinidad** [comment]
Hum! I don't think there's a problem with Invoke-SQLCmd as the proper way is to use this command is to save the results to a variable and then displaying the object properties.  Although I don't understand the use of the forever-loop as I would have to condition the loop properly.  This issue on relates only to Windows 5.1 and not Alpha 6.0.  

![invokesql_2017-03-07_16-01-56](https://cloud.githubusercontent.com/assets/19892435/23677851/cb29e490-034f-11e7-93f2-5e350f1a59a6.jpg)

**Comment by MaximoTrinidad** [comment]
Hey @iSazonov,

Why not creating a separate issue for loading assembly "System.Data.SqlClient.dll"?  I can't use to connect to a SQL instance in either PowerShell Alpha 6.0.0.16 version in Linux not Windows.  And, it works on Windows PowerShell fine.

Of course, unless I'm doing something wrong in how to load the assemblies. Feel free to correct my mistake.  See code below and attached image.

I tried the code in both Windows 10 Build 15048 and Linux Ubuntu 16.04.1.

`
## - Loading Assemblies:
Add-Type -Path "C:\Program Files\PowerShell\6.0.0.16\System.Data.Common.dll"
Add-Type -Path "C:\Program Files\PowerShell\6.0.0.16\System.Data.SqlClient.dll"

## - NON-SMO script code Set PowerShell variables:
$ConnectionString = 'server=servername;database=Master;Integrated Security=false;User ID=sa;Password=yrpassword';
$TSQLQuery = "Select @@Version as SQLVersion; ";

## - Connect and Execute Stored-Procedure:
$sda = New-Object System.Data.SqlClient.SqlDataAdapter ($TSQLQuery, $ConnectionString);
$sdt = New-Object System.Data.DataTable;
$sda.fill($sdt) | Out-Null;
$sdt.Rows;
`
![sqlclient_01_2017-03-07_16-51-20](https://cloud.githubusercontent.com/assets/19892435/23679814/1296a780-0357-11e7-94b6-aa227569cf4c.jpg)

**Comment by SteveL-MSFT** [comment]
@MaximoTrinidad SqlDataAdapter not in corefx and not planned for .Net Std 2.0 https://github.com/dotnet/corefx/issues/10706

SqlClient should show up once we moved to latest corefx

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

Cool!!  Thanks.  I'll be waiting for it.

Greatly Appreciated,
:)
