### ISSUE TITLE
psl-native-test fails [Manjaro Linux]

### ISSUE THREAD

**Issue by mwallner** [PowerShell/PowerShell#3063]
git revision: d7cf81b64dc244ef4451c3be725205058c068a90
gist log: https://gist.github.com/mwallner/457bde412489830319be10212bfb91e7

Steps to reproduce
------------------
run ./src/libpsl-native/test/psl-native-test after building

Expected behavior
-----------------
all tests should pass

Actual behavior
---------------
'LocaleTest' fails - test-locale.cpp:20

Environment data
----------------
Linux mwmaster 4.1.37-1-MANJARO #1 SMP PREEMPT Wed Dec 28 00:40:11 UTC 2016 x86_64 GNU/Linux

**Comment by mwallner** [comment]
Connected to https://github.com/PowerShell/PowerShell/blob/309bf603f9aff9009dce7e725d42b2d4f99f58c9/src/libpsl-native/test/test-locale.cpp#L16 ?

**Comment by iSazonov** [comment]
@ealexjordan Please comment the issue.

**Comment by mwallner** [comment]
1 out of 32 tests fail.

```
[----------] 1 test from LocaleTest
[ RUN      ] LocaleTest.Success
/trunk/git/PowerShell/src/libpsl-native/test/test-locale.cpp:20: Failure
Value of: "UTF-8"
Expected: nl_langinfo(CODESET)
Which is: "ANSI_X3.4-1968"
[  FAILED  ] LocaleTest.Success (1 ms)
[----------] 1 test from LocaleTest (1 ms total)
```

looking into the sourcecode: the tests expects the current locale to be UTF-8, nl_langinfo returns ANSI_X3.4-1968 .
Is the test-case valid to 'assume utf-8' ?

**Comment by thezim** [comment]
@mwallner I had a similar issue #2997. Perhaps your terminal application of choice has a similar setting.

**Comment by mwallner** [comment]
@thezim - that indeed looks like it's the very same thing.. still questioning the validity of this test case!
- closing this issue because of the duplicate.

**Comment by darkn3rd** [comment]
I set my local to `en_US.UTF-8`, but this causes is not good enough. :)

**Comment by iSazonov** [comment]
@darkn3rd Can you provide more information?
