### ISSUE TITLE
Change from #2958 cause test regressions (no output)

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#3069]
Comments from #2958

>lzybkr commented 2 days ago
> If I'm reading the logs correctly, the async changes didn't help at all, and most likely are a net negative right now. See these logs:
> 
> https://travis-ci.org/PowerShell/PowerShell/jobs/195355364
> 
> Notice 10 minutes with no output - so we failed to kill the async test and did not get further results.
> Also, I  notice the error tests take ~250ms when they should really take about ~1ms or less.

  @iSazonov
>      Collaborator
> iSazonov commented 13 hours ago
> The same https://travis-ci.org/PowerShell/PowerShell/jobs/195856711

**Comment by JamesWTruher** [comment]
I'll pull them, I was never happy about it in the first place

**Comment by JamesWTruher** [comment]
merged
