### ISSUE TITLE
Create package for Windows Server 2012

### ISSUE THREAD

**Issue by narrieta** [PowerShell/PowerShell#3077]
Currently 2012 is not in the list of supported platforms.

For context: we would like to use the package as part of the Azure DSC Extension.

**Comment by joeyaiello** [comment]
Just to clarify, 2012 or 2012 R2? If the former, I don't see any reason why the Win7/2008R2 package shouldn't work. If the latter, we have the package.

**Comment by SteveL-MSFT** [comment]
Installed the Win7/WS2012R2 pkg on WS2012 and it worked after installing the [VC++ redistributable](https://download.microsoft.com/download/7/2/5/72572684-052f-4aa9-9170-9d40813a87be/vc_redist.x64.exe).  We should at least update the install instructions.

**Comment by mirichmo** [comment]
The real fix is #2608 - produce two packages:
1. universal Windows x64 MSI
2. universal Windows x86 MSI

We are close to getting it. We just need to rename the existing win 7 packages and stop building the other ones.

**Comment by mirichmo** [comment]
I'm closing this because it is a duplicate of #2608
