### ISSUE TITLE
cmdlet example readme needs to be update to describe how to create a .net core cmdlet with Visual Studio

### ISSUE THREAD

**Issue by v-tbert** [PowerShell/PowerShell#3081]
The help at PowerShell/docs/cmdlet-example/README.md describes a command line process. That process does not appear to be reproducible through the Visual Studio UI. It would be helpful to include such guidance.

**Comment by SteveL-MSFT** [comment]
I don't see the original cmdlet example.  @andschwa I believe you created it originally, do you know what happened to it?

**Comment by daxian-dbw** [comment]
@SteveL-MSFT the original cmdlet example was out-dated and removed in #3409, which added a new documentation about hosting powershell core in .NET Core applications.

To create a .NET Core cmdlet, you just need to reference the NuGet package `System.Management.Automation` from the [`powershell-core`](https://powershell.myget.org/gallery/powershell-core) feed. It's the same as how you use any other NuGet packages.

So it seems to me that nothing needs to be done. Can we close this issue?

**Comment by SteveL-MSFT** [comment]
@daxian-dbw I think we should have specific documentation for module authors even if there's redundancy with hosting PowerShell Core documentation.  A simple 'hello world' cmdlet is sufficient.
