### ISSUE TITLE
Implement type alias support

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#3082]
The parser has support for type aliases (like a type accelerator), but it's not fully implemented.

The following should work, but reports `Unable to find type [MyMap]`:

```PowerShell
using type MyMap = System.Collections.Generic.Dictionary[string,int]
[MyMap]::new()
```

The following should also work, but reports `This syntax of the 'using' statement is not supported`:

```PowerShell
using type foo = System.Collections.Arraylist
```

**Comment by g8tguy** [comment]
Yep! I Noticed this bug a log ago. Also If you import assembly with `using assembly` it is inaccessible from  the `PowerShell` classes ! 
And `[Ordered]` to initialize an ordered hash table  doesn't work inside posh classes too!

**Comment by MartinGC94** [comment]
It probably also makes sense to add support for `using namespace Alias = RealName`  
Special parsing rules were also made for `using command Alias = RealName` and `using module Alias = RealName` what was the idea behind those? In the case of using command, was it just an alternative to New-Alias?

**Comment by iSazonov** [comment]
> what was the idea behind those?

"using" is evaluated at _parse_ time.

**Comment by MartinGC94** [comment]
>"using" is evaluated at parse time.

I know, but what functionality would those 2 using directives have had? Namespace and Type is obvious, Command and Module are harder to guess.

**Comment by iSazonov** [comment]
`using module` is already implemented and call `Get-Module -FullQualifiedName`.

**Comment by iSazonov** [comment]
`using module` imports class definitions that allows using the classes below in the script I guess.

**Comment by MartinGC94** [comment]
Maybe I wasn't clear, but I meant that the `using module Alias = RealName` syntax was unimplemented and that I couldn't figure out what the original intent may have been.  
Maybe it would have imported class definitions from the specified module in the specified namespace?

**Comment by iSazonov** [comment]
While type alias could be so useful as type accelerator I don't see benefits for module or command aliases. Although module alias could resolve module name conflict it is unlikely situation.

**Comment by SeeminglyScience** [comment]
> Maybe I wasn't clear, but I meant that the `using module Alias = RealName` syntax was unimplemented and that I couldn't figure out what the original intent may have been. Maybe it would have imported class definitions from the specified module in the specified namespace?

Fairly certain it was only added to make way for the unfinished `using type/command alias = newname` syntax. Doubt there were any plans to make it work with `using module` though I could very well be wrong.
