### ISSUE TITLE
when System.Timers.Timer work?

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#3090]
Yes,i want use 【Register-ObjectEvent】+【Timer】.
【Register-ObjectEvent】work normal in linux,【Timer】work normal in windows,【Timer】do not work in linux.
Do I need to import a namespace? How?Or is this new feature supported in the future? 
When will it work?

Steps to reproduce
------------------
$timerA = New-Object Timers.Timer   

#return
#Cannot find type [Timers.Timer]: verify that the assembly containing this type is loaded.

Environment data
----------------
linux: 
centos 7.3 1611

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-alpha                                                                                                       
PSEdition                      Core                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   3.0.0.0                                                                                                           
GitCommitId                    v6.0.0-alpha.15                                                                                                   
CLRVersion                                                                                                                                       
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
Timers.Timer is still not in CoreCLR.

**Comment by joeyaiello** [comment]
Agreeing with @iSazonov, I don't think we can do anything about this in PowerShell.

**Comment by chuanjiao10** [comment]
Timers.Timer back from .net core 2.0，
so problem solved from powershell 6.0 beta1.
