### ISSUE TITLE
Set-PSRepository Fails with Error Gallery Not Available on OS X

### ISSUE THREAD

**Issue by johnmccrae** [PowerShell/PowerShell#3092]
Steps to reproduce
------------------
Clean system
Load Alpha 15 on it.
Start Powershell
Set-PSRepository -Name PSGallery -InstallattionType Trusted

Expected behavior
-----------------
[completed]

Actual behavior
---------------

Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At /usr/local/microsoft/powershell/6.0.0-alpha.15/Modules/PowerShellGet/1.1.2.0/PSModule.psm1:4302 char:9
+         Get-PSGalleryApiAvailability -Repository $Name
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability

Set-PSrepository : No repository with the name 'PSGallery' was found.
At line:1 char:1
+ Set-PSrepository -Name PSGallery -InstallationPolicy Trusted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PSGallery:String) [Set-PSRepository], InvalidOperationException
    + FullyQualifiedErrorId : RepositoryNotFound,Set-PSRepository

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.15
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by bmanikm** [comment]
@johnmccrae is this still reproducible on latest PowerShell Core release? 
- If not, can we close this?
- If yes, could you please provide more details to repro this error along with -Debug output of a PowerShellGet command?

**Comment by johnmccrae** [comment]
Working now. You can kill this. Thanks!
