### ISSUE TITLE
Find why "Write-Information outputs an information object" fails on macOS in CI

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3094]
In #3071 I disabled the test on OS X.
We should figure out why it fails.

**Comment by ThomasNieto** [comment]
Is this still an issue?

**Comment by vexx32** [comment]
Looks like the test is still marked pending. We can remove the Pending flag and find out 😉 
       It "Write-Information outputs an information object" -Pending:($IsMacOS) {
            # redirect the streams is sufficient
            $result = Write-Information "Test Message" *>&1
            $result.NativeThreadId | Should Not Be 0
            $result.ProcessId | Should Be $pid
            $result | Should BeOfType System.Management.Automation.InformationRecord


            # Use Match instead of Be so we can avoid dealing with a potential domain name
            $result.Computer | Should Match "^($([environment]::MachineName)){1}(\.[a-zA-Z0-9]+)*$"
            if ($IsWindows)
            {
                $result.User | Should Match ".*${env:USERNAME}"
            }
            else
            {
                $result.User | Should Be $(whoami)
            }


            "$result" | Should be "Test Message"
       }
