### ISSUE TITLE
Test fails in nightly build (master, Linux)

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3098]
https://travis-ci.org/PowerShell/PowerShell/jobs/198247453

```
Describing Get-Help -Online opens the default web browser and navigates to the cmdlet help content
 [-] Error occurred in Describe block 40ms
   The type initializer for 'Microsoft.Win32.Registry' threw an exception.
   At /home/travis/build/PowerShell/PowerShell/src/powershell-unix/bin/Linux/netcoreapp1.1/ubuntu.14.04-x64/publish/Modules/Pester/Functions/Describe.ps1:100 char:13
```

**Comment by vors** [comment]
Same on OSX build
https://travis-ci.org/PowerShell/PowerShell/jobs/198247454

**Comment by vors** [comment]
I investigated it a little and found a minimal repro

```powershell
Describe '[Microsoft.Win32.Registry]::ClassesRoot failure' {
    
    if ($IsWindows) {
        [Microsoft.Win32.Registry]::ClassesRoot # this code is not executed, but throws in type initializer
    }

    It 'works on windows' -Skip:(!$IsWindows) {
        [Microsoft.Win32.Registry]::ClassesRoot # inside 'it' ClassesRoot doesn't cause problems
    }
}
```

Or even simpler

```
PS /Users/vors/dev/PowerShell> [Microsoft.Win32.Registry]::ClassesRoot                                                
An error occurred while creating the pipeline.
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException
```

The main problem is that it throws exception (probably in TypeResolver?) without executing the code.

**Comment by vors** [comment]
I don't see it happens again, which is weird.

**Comment by iSazonov** [comment]
Get-Help test failed in "Describe" and before "It".
I guess it is line 
```powershell
    $skipTest = -not ([System.Management.Automation.Platform]::IsIoT -or [System.Management.Automation.Platform]::IsNanoServer)
```
But it is working well in WSL.
May the [System.Management.Automation.Platform] call cause the loading of some dll?

I unpack .deb package and see multiple files with links to Win32 Registry. Why? For remoting?

**Comment by daxian-dbw** [comment]
Accessing any static properties of `Microsoft.Win32.Registry` will raise `PlatformNotSupportedException` exception. For script like `if ($false) { [Microsoft.Win32.Registry]::ClassesRoot }`, even though it won't be hit at run time, powershell needs to access the property via reflection at compilation time, and thus will trigger this exception. This means users cannot have the uses of this type in script even if it won't run on unix, sucks 😦 

@adityapatwardhan can you please fix the test? An option is to put the real logic in a string, and call `[ScriptBlock]::Create` to create the script block and run it.

**Comment by iSazonov** [comment]
Can we somehow log this exception and get a call stack?

**Comment by daxian-dbw** [comment]
Yes we can, by using `$Error`
```
PS /home/pi> [Microsoft.Win32.Registry]::ClassesRoot
An error occurred while creating the pipeline.
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException

PS /home/pi> $Error[0].InnerException.InnerException.InnerException
Operation is not supported on this platform.
PS /home/pi> $Error[0].InnerException.InnerException.InnerException.StackTrace
   at Microsoft.Win32.RegistryKey.OpenBaseKeyCore(RegistryHive hKey, RegistryView view)
   at Microsoft.Win32.Registry..cctor()
```

**Comment by iSazonov** [comment]
@daxian-dbw Sorry for the inaccuracy, my question was - can we somehow do it in _CI_?

**Comment by vors** [comment]
Why in CI? I can repro it locally. Can you?

**Comment by iSazonov** [comment]
@vors The test "Describing Get-Help -Online opens the default web browser and " work well locally for me.
As I understand the problem occurs randomly in CI only.

**Comment by vors** [comment]
> the problem occurs randomly in CI
Yes, that's correct!

> only

Nope, both me and Dongbo can repro it locally.
I'm using macOS.
It's interesting that it doesn't repro in WSL.

Another very interesting question is "why it sometimes succeed in CI?"

**Comment by vors** [comment]
Ah, ok the second mystery is not a mystery: it's a nightly build (that includes Feature) vs CI.
For example: 

- CI build https://travis-ci.org/PowerShell/PowerShell/jobs/201617482
- subsequent nightly: https://travis-ci.org/PowerShell/PowerShell/builds/201743741

**Comment by iSazonov** [comment]
😕 I only tested on Windows and WSL.
It's not my train. See you later  :smiley:

**Comment by daxian-dbw** [comment]
> Describing Get-Help -Online opens the default web browser and navigates to the cmdlet help content

@vors It looks like we don't run this test in nightly test pass ☹️ Just search it in the log of a [successful nightly run](https://travis-ci.org/PowerShell/PowerShell/jobs/201617482), and cannot find it.

**Comment by SteveL-MSFT** [comment]
I haven't seen the `Get-Help -Online` tests failing recently, do we still need this issue open?  We had failures due to an issue with a remoting test, but that's not related to this topic.

**Comment by vors** [comment]
@SteveL-MSFT it's there, take a look at this yesterday build
https://travis-ci.org/PowerShell/PowerShell/jobs/212862882#L1395

It's pretty confusing to hunt down the nightly builds in all the builds, but you can filter by branch (master) and distinguish them by the much longer execution time. And red status :P.

**Comment by daxian-dbw** [comment]
@SteveL-MSFT @vors For Travis builds, you can search for `Executing travis.ps1 $isPR='False' $isFullBuild='True'` to tell if it's a nightly build. The combinations are:
`Executing travis.ps1 $isPR='True' $isFullBuild='False'`  -- PR build
`Executing travis.ps1 $isPR='False' $isFullBuild='False'` -- push build
`Executing travis.ps1 $isPR='False' $isFullBuild='True'`  -- nightly build

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/pull/3377
