### ISSUE TITLE
Suggestion: Powershell should be able to Import-Module from an exe

### ISSUE THREAD

**Issue by andrewducker** [PowerShell/PowerShell#3102]
I have a bunch of EXEs written in C# which carry out useful utility functions.

I would love to make the functionality in them available to PowerShell.

Ideally PowerShell should be able to detect that the exe I'm about to run contains PowerShell commands and autofill my parameters (and accept objects from the response).  But failing that, having the ability to build a single artefact and have it work both as an exe and a PS Module would make life a lot easier.

**Comment by mirichmo** [comment]
An alternative approach would be to refactor your EXEs by moving the useful utility functions into a separate assembly. At that point you could package that assembly as a PowerShell module and compile your refactored EXEs against it.

**Comment by andrewducker** [comment]
That would be possible.  But doesn't work with the traditional workflow of "All of the tools that the team use are sitting in a shared tools folder that's on the path" - at the moment all of the command line tools are individual exes, because that's how command line exes have tended to work.

I'm trying to work out how to migrate forward from that without breaking the existing workflow, and it's proving...tricky.

**Comment by andrewducker** [comment]
As an example of why this is useful - the Nuget.exe used for carrying out nuget CLI tasks is pretty good.  But if it could be used both as normal from within DOS and also from within Powershell with autocompletion (and returning objects rather than text) that would be fantastic.

**Comment by iSazonov** [comment]
Have you ideas how implement this on C#?

**Comment by MaximoTrinidad** [comment]
Are these C# executable portable .NET Core? And, keeping in mind, that only Windows will work with *.exe programs. So, what about the other environments? This should work cross-platform.

:)

**Comment by andrewducker** [comment]
My understanding is that both .Net DLL and EXE files are basically assemblies with a bit of metadata.

In which case the dead simple case of "Load the Powershell functionality from this assembly" should work perfectly well.

Obviously, trying to load an EXE which isn't a .Net assembly wouldn't work.  But is there any reason why loading it from an EXE wouldn't work in general?

That way I could either run the exe as normal, or Import-Module on the exe and use the functionality in a PowerShell manner.

**Comment by lzybkr** [comment]
@andrewducker - have you tried it? Maybe add a cmdlet to your exe, copy it or create a symbolic link to the exe with a dll extension?

I do like the idea in principle, I've never been a fan of multi-file modules and the module directory structure, but I do think command auto-discovery would be problematic if this was supported - you don't want PowerShell looking at every `exe` in the `PATH` checking if it has any cmdlets, at least not with the current implementation.

**Comment by andrewducker** [comment]
Sadly, blocked.

LoadModuleNamedInManifest in ModuleCmdletBase checks against ModuleIntrinsics.IsPowerShellModuleExtension which checks against PSModuleProcessableExtensions which checks against a bunch of approved extensions.

Of which "exe" isn't one.

**Comment by iSazonov** [comment]
We could load EXEs with `Add-Type -AssemblyName` not Import-Module.

**Comment by lzybkr** [comment]
I'm aware of the extension check, that's why I suggested copying an exe to a dll or using a symbolic link - to see if you could get past the extension check, then you'd know if it could work.

**Comment by andrewducker** [comment]
Aaah, gotcha.  Yup, it works!

So, any chance of getting the check to allow exes in the future?

**Comment by SteveL-MSFT** [comment]
@andrewducker this doesn't seem to be a common use case, so I don't think my team would look at addressing this, I'd rather spend time supporting `import-module module.nupkg` instead so that modules can stay in archived form rather than expanded to a folder

**Comment by iSazonov** [comment]
@SteveL-MSFT It seems we already implement this in #7281 and can close the issue.
