### ISSUE TITLE
Debugger.ProcessCommand always adds commands to history

### ISSUE THREAD

**Issue by daviwil** [PowerShell/PowerShell#3109]
When running PSCommands which contain AddScript calls through Debugger.ProcessCommand, the scripts in those commands are always added to the user's command history.  Any host that relies on Get-History to retrieve the command history will end up with items which the user didn't personally execute in the debugger.  It'd be nice if there was a ProcessCommand overload (or some other way) to indicate that the executed command shouldn't be added to the command history.

/cc @PaulHigin @lzybkr

**Comment by lzybkr** [comment]
There is definitely a way - a host calls `prompt` but that never shows up in the history.

**Comment by daviwil** [comment]
I think this only happens when using `PSCommand.AddScript`.  I use `PSCommand.AddCommand` to invoke `prompt`, that hasn't shown up in the history.

**Comment by BrucePay** [comment]
You can use the 
    `CreatePipeline(string command, bool addToHistory)`
API on the Runspace object to execute scripts without adding them to the history.

**Comment by TheOnlyWei** [comment]
It's been 3 years, any updates on this? Just wasted a few hours debugging a Start-Transcript call in my code only to realize that the strange logs came from VS Code PowerShell extension.

**Comment by SeeminglyScience** [comment]
@TheOnlyWei The VSCode extension is solving this a slightly different way in that we're routing less things through `ProcessCommand`. It's currently in the latest preview if you want to give it a go. Note that as it is a preview and this change is experimental it may need to be reverted.

> There is definitely a way - a host calls `prompt` but that never shows up in the history.

Unfortunately that's due to a hard coded list of ~5 commands that the API specifically checks for and excludes from history.

**Comment by TheOnlyWei** [comment]
@SeeminglyScience I tried 7.3-preview, but didn't work. Using this thread for the discussion:
https://github.com/PowerShell/vscode-powershell/issues/873#issuecomment-1089170579
