### ISSUE TITLE
Allow non standard HTTP verbs.

### ISSUE THREAD

**Issue by thezim** [PowerShell/PowerShell#3113]
Web cmdlets do not allow non standard verbs. Any verb should be allowed.

**Comment by Mwiedmeyerd** [comment]
What is your reasoning, please?

Having non-standard verbs goes against the tenet of PowerShell discoberability

**Comment by thezim** [comment]
@Mwiedmeyerd in my case WebDAV.

**Comment by SteveL-MSFT** [comment]
Perhaps a new parameter set for `-custommethod`?

**Comment by joeyaiello** [comment]
Just to clarify, you're talking about the `-Method` parameter on `Invoke-WebRequest` and `Invoke-RestMethod`?

```
PS C:\dev\joeyaiello> Invoke-WebRequest -Method Default
Default  Delete   Get      Head     Merge    Options  Patch    Post     Put      Trace
```

**Comment by Lee303** [comment]
I've just added a pull request for this. Would appreciate feedback as this is my first code pull for PS

**Comment by thezim** [comment]
@joeyaiello Yes.
