### ISSUE TITLE
Does this project allow mirror?

### ISSUE THREAD

**Issue by KexyBiscuit** [PowerShell/PowerShell#3114]
It's well known that Internet access in China is not as fast as the US. As a result, Linux community usually use local mirror for software repositories.

I'd like to know if it's allowed to mirror packages.microsoft.com, and how.

This is not a PowerShell specific issue, but I have no idea where it belongs to.

**Comment by iSazonov** [comment]
You can ask the local software repository maintainers to download [Powershell Core packages](https://github.com/PowerShell/PowerShell/#get-powershell) and share it local.
