### ISSUE TITLE
SSH Remoting Documentation: Minor mistake in command

### ISSUE THREAD

**Issue by ChristophB125** [PowerShell/PowerShell#3116]
Hi, I just wanted to point out a small mistake in a command in the [SSH remoting documentation](https://github.com/PowerShell/PowerShell/tree/master/demos/SSHRemoting) :
The command should be 'sudo service sshd restart' and not 'sudo service ssh restart'
It should be obvious by looking at the text above but it can be confusing if a command does not work out of the box.

**Comment by MaximoTrinidad** [comment]
Good catch! I got to verify my blog post too. 
Thx!
