### ISSUE TITLE
Add support for templates when creating new modules

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#3117]
dotnet cli has added support for templates to create new projects, see https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/

There should be a template for creating PowerShell modules to help people get started.

**Comment by rkeithhill** [comment]
See https://github.com/PowerShell/Plaster/tree/master/src/Templates/NewPowerShellScriptModule

**Comment by lzybkr** [comment]
That's for a script module, right?  I'm suggesting we should plug into dotnet cli better for binary modules.

**Comment by rkeithhill** [comment]
Yup. Thanks for the clarification.

**Comment by tintoy** [comment]
I built one of these a while back, and after reading this, figured I may as well contribute what I've got:

https://github.com/tintoy/ps-binary-module-template

Feel free to reuse it if that's helpful :)

**Comment by iSazonov** [comment]
Implemented https://dotnetnew.azurewebsites.net/template/Microsoft.PowerShell.Standard.Module.Template/Microsoft.PowerShell.Standard.Module.Template
