### ISSUE TITLE
Feature Request: Create a preference variable to turn Off/On path normalization

### ISSUE THREAD

**Issue by arebee** [PowerShell/PowerShell#3118]
I want to tell PowerShell to leave my "/" path delims alone when I am on Windows and "\\" alone when I am on *nix. Perverse I know!

**Comment by thezim** [comment]
I had an similar issue today where I used ```Split-Path``` on a URL stem on Windows and it autocorrected the path delimiter. Would be nice if there was a switch for this particular cmdlet to ignore translation.

```powershell
PS C:\> Split-Path -Parent -Path /one/two
\one
```

**Comment by iSazonov** [comment]
We should have both:
1. Global preference variable with default value a platform depended.
2. Switch `-Normalize` or parameter -Style [Windows | Unix]
What cmdlets  is affected by the issue?

**Comment by thezim** [comment]
@iSazonov ```-Style [Windows | Unix]``` make more sense from a discovery point of view. Also ```-Normalize``` could get confusing if you have preferenced something else already, better to avoid the ambiguity.

**Comment by iSazonov** [comment]
We should have switches (in different parameter sets):
-StyleWindows - default true on Windows
-StyleUnix - default on Linux and IOS.

And we should consider remoting and remote sessions  Windows -> Unix, Unix -> Windows. Is it possible and reasonable to make implicit conversions?

**Comment by arebee** [comment]
-PathDelimiter [Windows|Unix]

$PSPathDelimier = [Windows|Unix] defaults to platform.

This should be a cosmetic styling.

Sent from my Windows 10 phone
