### ISSUE TITLE
Code Coverage Status Badge is cached

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3122]
Our main ReadMe.md contains Code Coverage Status. The badge looks wrongly due to caching (the badge display old information).

Fix from https://github.com/github/markup/issues/224
> We're pretty confident that the image caching works. If you're having issues with something like a CI badge, make sure the image has the  Cache-Control: no-cache  header, and either  Expires ,  Last-Modified  or  Etag . 

Or workaround from https://github.com/codecov/support/issues/218
```
[![Coverage](
https://img.shields.io/codecov/c/github/chesslave/chesslave.svg?maxAge=600)]
(https://codecov.io/gh/chesslave/chesslave)

URL param  maxAge  does the trick. The value is expressed in seconds.
```

**Comment by adityapatwardhan** [comment]
The badge seems to showing the latest build. Are you seeing it otherwise?

**Comment by iSazonov** [comment]
**Today** I see 33% and on the coveralls.io I see the same.
In recent days I have seen sometimes old up to 4-day badge.

**Comment by iSazonov** [comment]
Check from another computer - 46% vs 46%. No problem.

**Comment by adityapatwardhan** [comment]
@iSazonov  So are you OK closing the issue?

**Comment by iSazonov** [comment]
Yes. We can always come back if the problem appears.

**Comment by iSazonov** [comment]
@adityapatwardhan The Issue is up. I see 21% - really 49%.
