### ISSUE TITLE
Please fix this link 

### ISSUE THREAD

**Issue by yuriw** [PowerShell/PowerShell#3124]
Please fix this link 
https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.15/PowerShell_6.0.0-alpha.15-win10-x64.msi

**Comment by joeyaiello** [comment]
In what document do you see that link? The correct link is https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.15/PowerShell_6.0.0-alpha.15-win10-win2k16-x64.msi

**Comment by NathansNexus** [comment]
It's the main MSI link for Windows 10/Server 2k16 in the readme.

**Comment by yuriw** [comment]
Main page
https://github.com/PowerShell/PowerShell
=>
Windows 10 / Server 2016 (x64)
=> .msi URL

**Comment by NathansNexus** [comment]
If you click the link it takes you to a 404, but if you right click Save link as, it works. I guess the issue should be closed, or links fixed to open directly to the .msi URL.

**Comment by mirichmo** [comment]
@daxian-dbw We should fix this when we roll the alpha.16 release

**Comment by joeyaiello** [comment]
This has been fixed
