### ISSUE TITLE
Inaccurate results for Get-ACL due to lack of exception

### ISSUE THREAD

**Issue by JoesCrepes** [PowerShell/PowerShell#3128]
Steps to reproduce
------------------
Modify the ACL of a test object so that it contains two entries:
1. Allow full control to System
2. Deny full control to your user object
Then run:
Get-ACL -path "\\path\to\object"

Expected behavior
-----------------
I'd expect either the unauthorized access exception received in PS4.0 or a message stating that I don't have rights to read this object.

Actual behavior
---------------
This returns an ACL containing one entry - a denial to myself. This is inaccurate, but since it returns a technically valid ACL object, if I were to parse this to try to determine what permissions System has, I would get an inaccurate response. 

Environment data
----------------
```
Name                           Value                                           
----                           -----                                           
PSVersion                      5.0.10586.117                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.10586.117                                  
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1     
```

**Comment by iSazonov** [comment]
[File.GetAccessControl Method](https://msdn.microsoft.com/en-us/library/8e1fc3b8(v=vs.110).aspx) has UnauthorizedAccessException 

We must understand why PS 5 changed the behavior because reverting it back is a breaking change.

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you ping anybody to get understanding is the regression or not?

**Comment by SteveL-MSFT** [comment]
@iSazonov looking at the cmdlet code, it just enables SeSecurityPrivilege and creates new instance of FileSecurity instance with the file path.  I don't see any changes in this in the PowerShell code but .NET could have changed something.

@JoesCrepes can you repro the same thing using [this](http://www.leeholmes.com/blog/2010/09/24/adjusting-token-privileges-in-powershell/) to enable SeSecurityPrivilege then create FileSecurity instance like:

```powershell
[System.Security.AccessControl.FileSecurity]::new($filePath, [System.Security.Access
Control.AccessControlSections]::All)
```
