### ISSUE TITLE
Invoke-WebRequest / Invoke-RestMethod ContentType problem

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3131]
Steps to reproduce
------------------

Try to use dropbox API https://www.dropbox.com/developers/documentation/http/teams#team-get_info

**I'm passing explicit `-ContentType 'application/json'` and getting error `Bad HTTP "Content-Type" header: "application/x-www-form-urlencoded"`**

```
Invoke-RestMethod -Uri https://api.dropboxapi.com/2/team/get_info -ContentType 'application/json' -Headers @{"Authorization" = "Bearer $AUTH_TOKEN" } -Method POST
```

Expected behavior
-----------------

Success, like when I call

```
curl -X POST https://api.dropboxapi.com/2/team/get_info --header "Authorization: Bearer $AUTH_TOKEN"
```

Actual behavior
---------------

Current behavior just returns generic error, see #2193

Here is the output [deobfuscated with my hotfix](https://github.com/PowerShell/PowerShell/issues/2193#issuecomment-279125767)

```
Error in call to API function "team/get_info": Bad HTTP "Content-Type" header: "application/x-www-form-urlencoded".  Expecting one of "application/json", "application/json; charset=utf-8", "text/plain; charset=dropbox-cors-hack".
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                              
----                           -----                                                                                                                              
PSVersion                      6.0.0-alpha                                                                                                                        
PSEdition                      Core                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                            
BuildVersion                   3.0.0.0                                                                                                                            
GitCommitId                    v6.0.0-alpha.14-78-gaa764dd54edd5b214eb1fcb67aba5370014e7663-dirty                                                                 
CLRVersion                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                
SerializationVersion           1.1.0.1 
```

**Comment by vors** [comment]
I read the code a little bit and it could be dotnet problem O_o
So, if endpoint require some payload, I can run `
Invoke-RestMethod -Uri https://api.dropboxapi.com/2/team/groups/list -ContentType 'application/json' -Headers @{"Authorization" = "Bearer $AUTH_TOKEN" } -Method POST -Verbose -Body (@{'limit' = 100} | ConvertTo-Json)
`
And I get a good response

But if it doesn't require, the `Content-Type` header is [not getting set](https://github.com/PowerShell/PowerShell/blob/aa764dd54edd5b214eb1fcb67aba5370014e7663/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebRequestPSCmdlet.CoreClr.cs#L294).

If I add dummy `-Body ''`, I getting `Error in call to API function "team/get_info": request body: could not decode input as JSON`

**Comment by SteveL-MSFT** [comment]
@vors I looked at this and it does appear to be a limitation with dotnet.  They don't allow Body to be null and having Content-Type header.  Best we can do here might be to output a warning that `ContentType` isn't being used if the Body is not specified.  Based on my reading of [RFC2626](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7) you should be allowed to specify `Content-Type` without a Body.

**Comment by vors** [comment]
@SteveL-MSFT thanks for confirming. That was my understanding as well.

It seems dotnet-core specific, because in the Full framework, there is a [separate field](https://github.com/PowerShell/PowerShell/blob/d59627f9ae51c90f405efc3def38e134d4164d88/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FullClr/WebRequestPSCmdlet.FullClr.cs#L257) for the ContentType.

That pretty much prohibits using most of the Dropbox API v2 endpoints from PowerShell core and from dotnet core as well. For example https://github.com/dropbox/dropbox-sdk-dotnet could not be ported to dotnet core.

**Comment by SteveL-MSFT** [comment]
@vors did you open an issue against corefx?  We should ref it here

**Comment by vors** [comment]
BTW, on the full version of PS v5.1 I'm getting another error

```
Invoke-WebRequest : Error in call to API function "team/get_info": request body: could not decode
input as JSON
At line:1 char:1
+ Invoke-WebRequest -Uri https://api.dropboxapi.com/2/team/get_info -Co ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke
   -WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWe
   bRequestCommand
```

**Comment by vors** [comment]
After conversation in corefx issue, it seems that `-Body "null"` workaround is the right way to do it in the dropbox case.
Meanwhile, I think that powershell side of things could be improved.
Particualrly, I don't like the fact that powershell silently ignores `-ContentType 'application/json'`.

**Comment by SteveL-MSFT** [comment]
@vors so the workaround is to have the word `null` in the body?

**Comment by vors** [comment]
@SteveL-MSFT in the dropbox v2 API case yes.
There could be different API endpoints that may be unavailable because of a similar issue, I don't have data about it.

**Comment by iSazonov** [comment]
@markekraus Could you please look the Issue?
@vors Currently we was moved to .Net Core 2.1 with new WebClient - could you update status of the Issue?

**Comment by vors** [comment]
Hey it works on 6.1.0 :) 👍

**Comment by yar05** [comment]
Can this be re-opened ? This is still an issue in 6.2.1
```
Invoke-WebRequest -Method Post -ContentType 'application/json' $url
```
This does not send content type header at all !
When I run it in 5.1.18922.1000 it works. I''ve also tested this on windows 8. Same behaviour
```
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18922
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@yar05 Please open new issue with repo steps and reference the issue.

**Comment by SteveL-MSFT** [comment]
@yar05 this appears to be an optimization by .NET.  `Content-Type` is only necessary if there is a body to indicate the media type of the body content.  Since you are not providing a body, that header doesn't get included.  If you try:

```powershell
Invoke-WebRequest -Uri "http://httpbin.org/headers" -ContentType "application/json" -Body "test"
```

You'll see

```output
StatusCode        : 200                                                                                                                                                                                                                                                         StatusDescription : OK                                                                                                                                                                                                                                                          Content           : {
                      "headers": {
                        "Content-Length": "4",
                        "Content-Type": "application/json",
                        "Host": "httpbin.org",
                        "User-Agent": "Mozilla/5.0 (Macintosh; Darwin 18.6.0 Darwin Kernel Version 18.6.0:…
RawContent        : HTTP/1.1 200 OK
                    Access-Control-Allow-Credentials: true
                    Access-Control-Allow-Origin: *
                    Date: Fri, 05 Jul 2019 20:45:47 GMT
                    Referrer-Policy: no-referrer-when-downgrade
                    Server: nginx
                    X-Content-Type-Optio…
Headers           : {[Access-Control-Allow-Credentials, System.String[]], [Access-Control-Allow-Origin, System.String[]], [Date, System.String[]], [Referrer-Policy, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 300
RelationLink      : {}
```
