### ISSUE TITLE
[Meta] Tag issues for new contributors to work on

### ISSUE THREAD

**Issue by tylerl0706** [PowerShell/PowerShell#3136]
Meta issue here. Feel free to close. 

I've noticed a lot of big projects that have a solid following tag certain issues with a tag such as "first-time contributors" or "good first bug". 

The idea is that new people (like myself) who want to contribute but don't really know how or where to get started have a place to start.

It'd be really sweet if the Powershell repo had this!

**Comment by joeyaiello** [comment]
While there's not a particular label "easy" issues, we use [`up-for-grabs`](https://github.com/PowerShell/PowerShell/issues?q=is%3Aopen+is%3Aissue+label%3AUp-for-Grabs) for the sorts of issues that anyone can feel free to pick up.
