### ISSUE TITLE
Update copyright notices

### ISSUE THREAD

**Issue by andschwa** [PowerShell/PowerShell#3148]
The copyright notices are still `Copyright (C) 2016 Microsoft Corporation` when they should be `Copyright (C) 2017 Microsoft Corporation` or better `Copyright (C) <YYYY> Microsoft Corporation` where it's dynamically updated to the current year.

**Comment by kwiknick** [comment]
There is a discussion going on about my pull request that takes care of this issue.  Some are saying we don't need the year.  And others are saying it shouldn't be dynamic.  When I find out more, I'll make a change if need be and do another push.

**Comment by kwiknick** [comment]
@andschwa The PR was approved, and should be ready to merge.  So this issue is almost closed.  This was a ton of fun and I look forward to contributing more in the future.

**Comment by andschwa** [comment]
Thanks for your contribution @kwiknick! It's much appreciated.
