### ISSUE TITLE
Unix nightly badge is inaccurate

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3150]
Right now the nightly badge is inaccurate.
Last nightly run finished 3 hours ago and and it's red
https://travis-ci.org/PowerShell/PowerShell/jobs/201743742

The image is getting from here:
`[tv-nightly-image]: https://jimtru1979.blob.core.windows.net/badges/DailyBuildStatus.svg`

![image](https://cloud.githubusercontent.com/assets/816680/22963079/b341ec88-f305-11e6-9130-c5d2a0448fd0.png)

I'm not sure is it a lag in automation or a persistent problem.
cc @JamesWTruher 

Also the last CI run doesn't filter out nightly, but it's a known problem.

**Comment by daxian-dbw** [comment]
The test `Describing Get-Help -Online opens the default web browser and navigates to the cmdlet help content` is not running in nightly build, which fails in travis CI.

**Comment by vors** [comment]
@daxian-dbw nope. It does run. And it does fail.
This issue is about the badge only.
Travis CI doesn't have a way to run two different projects from the same repo.
Unlike in appveyor, where we just have two projects for CI and for nightly.
That's why we mix all builds at the same travis project.

My understanding is that Jim wrote automation to find last nightly build form the project and upload corresponding badge to `https://jimtru1979.blob.core.windows.net/badges/DailyBuildStatus.svg`.

This issue is about this automation.

**Comment by daxian-dbw** [comment]
@vors you are right. I was confused about the Travis jobs.

**Comment by daxian-dbw** [comment]
@JamesWTruher Could you please take a look at this issue? It is the nightly build that has failures, but the Travis CI tags in our README.md indicates otherwise.

**Comment by SteveL-MSFT** [comment]
I talked to @JamesWTruher and it appears that GitHub may be caching the image.  If you go directly to the badge URL, you'll see the correct failed image

**Comment by vors** [comment]
Oh, that could be.
I seen it with the CI badges, but they are usually refreshed after Ctrl+R in chrome.
I not sure who is caching the image, chrome or github, I suspect github.

If I see it again, I will try to do a refresh couple times. If it doesn't help, I will re-open the issue.

**Comment by vors** [comment]
Nope, refresh doesn't help.
I may have an idea...

**Comment by iSazonov** [comment]
Maybe related #3122

**Comment by daxian-dbw** [comment]
I reopen this issue because our Travis CI full build passed last night but the badge shows `Failed`.

**Comment by daxian-dbw** [comment]
Reopen this issue. The Travis badge seems still not fixed. Full build failed today while CI builds passed, however, our Travis badge shows CI failed and full build passed.
Here is the failed full build: https://travis-ci.org/PowerShell/PowerShell/jobs/216614572

**Comment by daxian-dbw** [comment]
And as @iSazonov pointed out, CodeCover badge is also cached.

**Comment by SteveL-MSFT** [comment]
According to the link Dongbo provided, this should have worked as we are setting `Cache-Control` header and `ETag` is there as well:

```powershell
PS C:\Users\slee\repos\PowerShell> $a = iwr https://jimtru1979.blob.core.windows.net/badges/DailyBuildStatus.svg
PS C:\Users\slee\repos\PowerShell> $a.Headers

Key               Value
---               -----
Cache-Control     {no-cache}
Date              {Thu, 30 Mar 2017 16:13:25 GMT}
ETag              {0x8D4762F734F4A9A}
Server            {Windows-Azure-Blob/1.0, Microsoft-HTTPAPI/2.0}
x-ms-request-id   {2a5cbca2-0001-0046-1270-a95f29000000}
x-ms-version      {2009-09-19}
x-ms-lease-status {unlocked}
x-ms-blob-type    {BlockBlob}
```

I'll follow-up with GitHub support

**Comment by SteveL-MSFT** [comment]
I contacted GitHub support and they said they `cleared the cache on our side so that badge shouldn't be cached anymore`.  I'm resolving this as closed unless someone sees it's still an issue.
