### ISSUE TITLE
Requesting Nano Server install instructions

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShell#3151]
On the repo homepage, there are a set of MSI links but as far as I know, Nano Server does not support MSI.  Furthermore, the instructions page mentions "Full SKU" which gives me the impression it does not document installation on Nano Server.

Therefore, I request that instructions be added on how to install the latest version of PowerShell 6 onto Nano Server.

**Comment by mirichmo** [comment]
The quick answer is to copy the win10 zip (PowerShell_6.0.0-alpha.15-win10-win2k16-x64.zip) to your Nano Server instance and unzip it.

I will update the install instructions with more detailed steps as well since Nano Server interaction is a little different from other SKUs.
