### ISSUE TITLE
Update releasing.md

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#3156]
We (maintainers) need to update [releasing.md](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md) to reflect the current state of the release process using our internal automation.

**Comment by iSazonov** [comment]
Can we close the Issue?

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
I think it's been updated sufficiently since when this was opened.  There's still improvements we can make to how we release, but let's have those as separate specific issues.
