### ISSUE TITLE
Move-CSUser command works in winform application but not window service

### ISSUE THREAD

**Issue by ccm1st** [PowerShell/PowerShell#3162]
I am trying to write a window service where I can pass in the powershell script and it will execute script accordingly. The service works fine with most of of script, but when I try to run the following command, it will always failed with error indicating that it requires MSOIDCLIL.DLL.  
Note, the command is used to move a lync user from on-prem to office 365.

`Move-CsUser -Identity username@contoso.com -Target sipfed.online.lync.com -Credential $creds -HostedMigrationOverrideUrl <URL>.`

What I have tried:

1. Same piece of code if I ran it inside an application( instead of service), it works fine.
2. Powershell runs fine if I ran it inside Powershell ISE

Here is what I know: 

1. MSOIDCLIL.DLL is used to connect office 365 
2. MSOIDCLIL.DLL comes with skype server 2015, which my server already have
3. When running the powershell script inside the window service, it will look for the dll inside of the service folder
4. When I run the powershell script locally inside powershell ISE, it will look for the DLL in skype server folder. 

C# code I used to execute powers
`Runspace` runspace = RunspaceFactory.CreateRunspace();

    // open it

    runspace.Open();

    // create a pipeline and feed it the script text

    Pipeline pipeline = runspace.CreatePipeline();
    pipeline.Commands.AddScript(scriptText);

    // add an extra command to transform the script
    // output objects into nicely formatted strings

    // remove this line to get the actual objects
    // that the script returns. For example, the script

    // "Get-Process" returns a collection
    // of System.Diagnostics.Process instances.

    pipeline.Commands.Add("Out-String");

    // execute the script

    Collection<psobject /> results = pipeline.Invoke();

    // close the runspace

    runspace.Close();
`

I suspect the difference in execution context for window service and application caused this, but I am not sure how to solve it. 

Question: What do I need to do so that my service can ran the Move-CSUser command above?

Anywhere I can find the source code for move-csuser command?

**Comment by vors** [comment]
As a workaround, you can probably find the file on the system, i.e. with `Get-ChildItem` and call `[Reflection.Assembly]::LoadFrom($LocalDllPath)` directly to pre-load the dll into the process.
