### ISSUE TITLE
Unexpected behavior of array-valued calculated properties added to a custom object with Select-Object

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3163]
[Superseded by #5579]

Steps to reproduce
------------------

```powershell
'' | Select-Object @{ n='prop'; e={ 1, 2 } } | ConvertTo-Json
```

Expected behavior
-----------------

```
{
    "prop":  [
                 1,
                 2
             ]
}
```

Actual behavior
---------------

_Update_: This symptom no longer happens in PowerShell _Core_ due to [this fix](https://github.com/PowerShell/PowerShell/pull/3231), but it can still be observed in _Windows PowerShell_; the symptom illustrates that the `Select-Object` way of creating the array-valued property differs from the seemingly equivalent `[pscustomobject] @{ .... }`  way, which is both unexpected and could cause problems in other contexts.

```
{
    "prop":  {
                 "value":  [
                               1,
                               2
                           ],
                 "Count":  2
             }
}
```

Note that what _should_ be an equivalent command:

    [pscustomobject] @{ prop = 1, 2 } | ConvertTo-Json    

 _does_ produce the expected output.

An unexpected difference in the resulting array-valued property can also be observed via `Get-Member`:

    (Get-Member prop -InputObject (New-Object pscustomobject |Select-Object @{ n='prop'; e={  1, 2  } })).Definition

yields

    System.Object[] prop=1 2    

whereas 

    (Get-Member prop -InputObject ([pscustomobject] @{ prop = 1, 2 })).Definition

yields

    Object[] prop=System.Object[]

For more information and a workaround, see http://stackoverflow.com/a/38212718/45375

Environment data
----------------

```powershell
PowerShell v6.0.0-alpha (v6.0.0-alpha.15) on Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
PowerShell v5.1.14393.693 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by iSazonov** [comment]
@daxian-dbw Taking into account the experience of last time we corrected `Select-Object` cmdlet I guess it most likely a breaking change.

**Comment by iSazonov** [comment]
@mklement0 Could you please add comment why you close the Issue.

**Comment by mklement0** [comment]
@iSazonov: Thanks for the reminder, but I'd already put "[Superseded by #5579]" at the top of the original post. #5579 describes the issue in more general terms.
