### ISSUE TITLE
Send-MailMessage Excluded from Non-Windows systems

### ISSUE THREAD

**Issue by tibmeister** [PowerShell/PowerShell#3164]
Not sure of the background on this one but if it's something that just needs re-written and tweaked for non-Win systems then I could probably take that on.  I can't even count the number of scripts I have that rely on this.

**Comment by joeyaiello** [comment]
Looks like it [depends primarily on `System.Net.Mail`](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs#L8). 

Fortunately, it also [looks like we'll get some semblance of `Mail` with .NET Standard 2.0](https://github.com/dotnet/corefx/pull/12416)

**Comment by ThreeFive-O** [comment]
@joeyaiello I think this issue can be closed as the Send-MailMessage cmdlet was ported in PR #3869
