### ISSUE TITLE
Set-Clipboard -AsHtml puts invalid CF_HTML on clipboard with non-ASCII text

### ISSUE THREAD

**Issue by bcdev-com** [PowerShell/PowerShell#3177]
Steps to reproduce
------------------
1) Set-Clipboard -AsHtml "abc" 
2) Paste into Word 
3) Text appears correctly as: abc 
4) Set-Clipboard -AsHtml "àbc" 
5) Paste into Word 
6) Text appears incorrectly as: ࢣ
Appears CP 1251 text is being put in the CF_HTML, not UTF8. 

Expected behavior
-----------------
Text containing non-ASCII characters should be corrected converted to CF_HTML

Actual behavior
---------------
Any characters outside the ASCII range corrupt the HTML placed on the clipboard.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SteveL-MSFT** [comment]
At this time the Clipboard cmdlets are not compatible with PSCore6 as it depends on a System.Windows.Forms class which isn't part of corefx and would not be cross platform compatible.

I do think the clipboard cmdlets are useful, but should be a separate module that is cross platform compatible which may require different code paths per OS.

**Comment by pcgeek86** [comment]
@SteveL-MSFT Can you open up this ticket, unless there's already a stub somewhere for a future **Clipboard** PowerShell module?

**Comment by SteveL-MSFT** [comment]
@pcgeek86 I think you should open a new issue if you want a clipboard module as this one was for a specific issue
