### ISSUE TITLE
Windows PowerShell Get-ChildItem -Force / -Hidden / -Attributes Hidden fails to find C:\pagefile.sys and C:\swapfile.sys

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3196]
Steps to reproduce
------------------

```powershell
Get-ChildItem -Force C:\pagefile.sys | % { $_.Name + ": " + $_.Mode }
Get-ChildItem -Hidden C:\pagefile.sys  | % { $_.Name + ": " + $_.Mode }
Get-ChildItem -Attributes Hidden C:\pagefile.sys  | % { $_.Name + ": " + $_.Mode }
```

Expected behavior
-----------------

```
pagefile.sys: -a-hs-
pagefile.sys: -a-hs-
pagefile.sys: -a-hs-
```

Actual behavior
---------------

All 3 commands fail and report:

    Get-ChildItem : Cannot find path 'C:\pagefile.sys' because it does not exist.

Note that the Core edition (v6.0-alpha16) _does_ find the file, but the `.Mode` property is empty.

Also, in both editions, `Get-ChildItem -Hidden \` _does_ list `pagefile.sys` and `swapfile.sys`, but without a  `.Mode ` value.

Environment data
----------------

```
Windows PowerShell v5.1.14393.693 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by daxian-dbw** [comment]
@mklement0 this seems to be a duplicate issue of #2144, which has been fixed in powershell core. However, the `Mode` property doesn't return the correct value for hidden system files in powershell core.
Given that, I'm closing this issue and track the `Mode` property problem with #3200
