### ISSUE TITLE
Get-Item and Get-ChildItem ignore extraneous trailing periods in a literal file path and report the trailing periods in the .Name property (Windows)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3197]
Steps to reproduce
------------------

```powershell
Get-ChildItem -LiteralPath c:\windows\system32\cmd.exe... | Format-List Name, Extension
Get-Item -LiteralPath c:\windows\system32\cmd.exe... | Format-List Name, Extension
```

Expected behavior
-----------------

Both commands should fail, because no such file exists (due to the extraneous trailing `.` chars.)

Actual behavior
---------------

Both commands output:

```
Name      : cmd.exe...
Extension : .exe
```

Note how (a) `cmd.exe` was still matched, despite the extraneous trailing `.` chars., and (b) the `.Name` property reflects those` `. chars., whereas `.Extension` and `.FullName` do not.

(As a consequence of the above, `.BaseName` reports an incorrect value.)

On a related note, _directory_ paths with `Get-Item` behave slightly differently: (a) directly appended periods are also ignored, but the `.Name` property is reported correctly; (b) you get the same behavior with an intervening `\` followed by _3_ (`\...`) or more trailing periods (with `\.` and `\..` exhibiting the expected behavior).

As an aside: The `.Extension` property only reflect's a directory name's extension if the path doesn't end in `\`: `$null = mkdir foo.bar; (Get-Item foo.bar).Extension; (Get-Item foo.bar\).Extension`

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.16) on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
Windows PowerShell v5.1.14393.693 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by mklement0** [comment]
PowerShell seems to infer the existence of the specified path _as is_  from whether the [GetFileAttributes()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364944%28v=vs.85%29.aspx) native Windows API function finds the file (by successfully returning its attributes). 

It is `GetFileAttributes()` that inexplicably accepts the trailing `...` appended to an existing file's path and still returns the file's attributes, _except_ when support for long paths is turned on by prepending `\\?\`, as the following C# snippet demonstrates:

```c#
public static class GetFileAttributesTest
{

	[DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
	static extern uint GetFileAttributes(string lpFileName);

	const uint INVALID_FILE_ATTRIBUTES = 0xffffffff;

	public static void Main()
	{
		string path = @"c:\windows\system32\cmd.exe...";
                // !! SUCCEEDS, despite trailing '...'
		var attrShortPath = GetFileAttributes(path);
                // FAILS, as expected.
		var attrLongPath = GetFileAttributes($@"\\?\{path}");
		var foundShortPath = attrShortPath != INVALID_FILE_ATTRIBUTES;
		var foundLongPath= attrLongPath != INVALID_FILE_ATTRIBUTES;
	}

}
```

**Comment by HumanEquivalentUnit** [comment]
This originally surfaced from looking at `Get-ChildItem -Filter`, and how the Filter wildcards are handled by the filesystem provider. There, it is expected that a dot `.` wildcard will match at the end of a filename, e.g.
   - in a command prompt `dir c:\windows\system32\cmd.exe.......`  will find the file, but it will have the correct name.
   - This replicates in PowerShell using the -Filter parameter, e.g.
   - `gci -LiteralPath c:\windows\system32\ -Filter 'cmd.exe.'` will find it, with the correct name (no dot)

So the buggy bit (to me) is that the PowerShell wildcarding, without using Filter, does match the file but pulls it back with the wrong name.

 - This behavior happens back to PS 2.0 on Server 2003 SP2 (so I imagine it's known about / documented somewhere previously).
 - The `Name` property gets the extra dots added to the end, but the `BaseName` property varies depending on how many dots there are; they cause it to merge in part of the extension until there are more dots than characters in the extension, then extra dots get added to the end:
   - `gi -LiteralPath c:\windows\system32\cmd.exe. | fl BaseName` -> 1 dot  = `cmd.`
   - `gi -LiteralPath c:\windows\system32\cmd.exe.. | fl BaseName` -> 2 dots = `cmd.e`
   - `gi -LiteralPath c:\windows\system32\cmd.exe... | fl BaseName` -> 3 dots = `cmd.ex`
   - `gi -LiteralPath c:\windows\system32\cmd.exe.... | fl BaseName` -> 4 dots = `cmd.exe`
   - `gi -LiteralPath c:\windows\system32\cmd.exe..... | fl BaseName` -> 5 dots = `cmd.exe.`
- As well as `Get-Item`, this affects `Get-ChildItem`:
   - `Get-ChildItem -LiteralPath c:\windows\system32\cmd.exe.` returns a file with an incorrect name.

**Comment by mklement0** [comment]
@HumanEquivalentUnit: Thanks for the additional information.

* Given that the problem surfaces with `-LiteralPath` (too), it is not about _wildcarding_; I think that passing the path as a _literal_ to `GetFileAttributes`, and inferring from its ability to successfully return  attributes for it that the path is valid _as-is_ is the problem.

* `.BaseName` being incorrect is just a follow-on effect of `.Name` being incorrect: `.BaseName` is a script property that chops off the extension from the `.Name` property by string length, and since `.Extension` has the correct value (`.exe`, in this case), whereas `.Name` has the extraneous trailing `.` chars.,  a part of the extension unexpectedly surfaces in `.BaseName`.

**Comment by lzybkr** [comment]
I believe this is how Win32 (not PowerShell, not .Net, but Win32) path processing works - removing trailing dots is, well, expected.

Here is a rather definitive reference, based on reverse engineering:

https://googleprojectzero.blogspot.cz/2016/02/the-definitive-guide-on-win32-to-nt.html

**Comment by mklement0** [comment]
@lzybkr: Thanks for that link - interesting (and frightening) read. The relevant passage (emphasis added) tells us that trailing _spaces_ are ignored as well:

> 	**Remove any trailing spaces or dots for the last path element**, assuming that it isn’t a single or double dot name.
> 	 
> That last rule seems odd, but as we’ll see it really does do this for normal paths.
