### ISSUE TITLE
convertto-securestring will fail on Ubuntu 16x64 for v6.0.0-alpha.16 Release

### ISSUE THREAD

**Issue by JumpingYang001** [PowerShell/PowerShell#3198]
Steps to reproduce
------------------
PS /> $password='abcdef'
PS /> $PWord = convertto-securestring $password -asplaintext -force

Expected behavior
-----------------
No error

Actual behavior
---------------
Unable to find the specified file.
At line:1 char:1
+ $PWord = convertto-securestring $password -asplaintext -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException

Environment data
----------------

```powershell
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.16
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by SteveL-MSFT** [comment]
SecureString type doesn't exist in CoreCLR yet

**Comment by JumpingYang001** [comment]
So we can not use securestring any more from now on?
I used below command, and what should I replace these command for latest build? thanks
```
$PWord = convertto-securestring $password -asplaintext -force
$cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User,$PWord
```

**Comment by JumpingYang001** [comment]
@SteveL-MSFT but it still exist in https://github.com/dotnet/coreclr/blob/master/src/mscorlib/corefx/System/Security/SecureString.cs

**Comment by SteveL-MSFT** [comment]
Looks like CoreFx already did the work https://github.com/dotnet/corefx/issues/13062 and we just need to consume it

**Comment by SteveL-MSFT** [comment]
Not getting the exception on alpha.17

```powershell
PS /home/steve> $password='abcdef'                                                        
PS /home/steve> $PWord = convertto-securestring $password -asplaintext -force             
PS /home/steve> $pword                                                                    
System.Security.SecureString
```

We have a separate issue to actually use the .Net SecureString implementation: https://github.com/PowerShell/PowerShell/issues/3228
