### ISSUE TITLE
Show Script panel left in ISE

### ISSUE THREAD

**Issue by skest3qc** [PowerShell/PowerShell#3199]
Hi,

it would be nice to have a option to show ISE script panel on the left side.

**Comment by RichardSiddaway** [comment]
I've been asking for that since ISE first appeared in PowerShell 2.0. As far as I can tell there's no reason it can be done. just never had a high enough priority. need to have a more people chip in and second this

**Comment by MaximoTrinidad** [comment]
Just an FYI

Please, make sure to reposted this issue on windowsserver.uservoice.com as this is section is for PowerShell Open Source and not Windows PowerShell or ISE.  

I know this issue will not be moved to the UserVoice, unless it has any relation any of the PowerShell Core modules shared with Windows PowerShell.

:)
