### ISSUE TITLE
"dir -force -hidden c:\pagefile.sys | % Mode" returns null while it should be '-a-hs-'

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3200]
Steps to reproduce
------------------
```
$s = Get-ChildItem -Force C:\pagefile.sys
$s.Mode
```

Expected behavior
-----------------
'-a-hs-'

Actual behavior
---------------
returns `null`

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSEdition                      Core
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.16-20-g56dddcd42944024bafa04f57d108c6760c5d09ae-dirty
```

The `Mode` property is a `CodeProperty` added by powershell and the method `[Microsoft.PowerShell.Commands.FileSystemProvider]::Mode(PSObject)` will be called when accessing `Mode`. In this case, an exception will be thrown from `InternalSymbolicLinkLinkCodeMethods.IsReparsePoint(fileInfo)` within that method.

**Comment by iSazonov** [comment]
It was fixed in CoreFX for Windows but still doesn't work on Unix-s.

**Comment by iSazonov** [comment]
On WSL 7.0 Preview1 still returns "Access to the file '/mnt/c/pagefile.sys' is denied.

**Comment by CityguyUSA** [comment]
If you don't fix problems they don't fix themselves   This stupid theory that if no one complains they must be working just makes you look foolish.

**Comment by CityguyUSA** [comment]
Get-ChildItem <Drive\Folder\File> -recurse -force | where {(Get-ItemProperty $_.fullname).attributes -BAND [io.fileattributes]::archive}

Same problem.

Get-ChildItem : Could not find item C:\swapfile.sys.
At line:1 char:1
+ Get-ChildItem c:\*.* -recurse -force | where {(Get-ItemProperty $_.fu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\swapfile.sys:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by meluvalli** [comment]
It's always nice to see an 8 year old issue still exist isn't it?  DUMB!

**Comment by CityguyUSA** [comment]
I ended up talking to a MS tech person regarding an error I was having with Window 10 the other month.  Her reply was they new it was a problem so they removed the feature in Window's 11.
