### ISSUE TITLE
WMF 5.1 : How to repair or uninstall?

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#3210]
Good eveing

WMF 5.1 is really annoying, because the installaiton behaves different than the usual, great working way: it is impossible to uninstall or to repair it on the 'great, stable, ...' Windows 10 Platform. Are you sure that WMF is rock solid??

If we use Powershell Enum, we get an exception. This is the content of the test-script test.ps1:

Enum ComputerType
{
  E1
  E2
}

If we call it:
 
PS C:\temp> c:\temp\test.ps1
The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ c:\temp\test.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException

We have the latest WMF 5.1 Version for Windows 10:

PS C:\temp> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  693

Please bring back a standard Installer, so that WMF can be installed individually on each Windows. It shouldn't belong to the OS itself. 

btw: We've got this problem after upgrading to the Windows 10 anniversary upgrade.
It looks like we have to reinstall the OS just to fix the scripting environment... we really hope you agree it's annoying to fix a software package this way...

Kind regards,
Thomas

**Comment by JKeithB** [comment]
WMF 5.1 **does not apply to, and cannot be installed on Win10**. Each WMF package targets specific older versions of Windows. WMF takes the latest version of the management stack and updates older versions of the operating system's PowerShell, WMI, & WinRM components. 
Win10/Server 2016 are maintained via Windows Update. If you want to update earlier version of Win10 to the latest PowerShell/WMI/WinRm features, use WU to get the latest update of Win10. If you modify the in-box version of PowerShell/WMI/WinRM, you should be able to do a system repair to get back to the original components.
I believe this is nearly duplicated in the [WMF blog topic]
(https://blogs.msdn.microsoft.com/powershell/2016/12/06/wmf-5-1-releasing-january-2017/).
