### ISSUE TITLE
Rewrite ConvertFrom-SddlString in C#

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#3212]
See #2718.

**Comment by faraazahmad** [comment]
I would like to take this up

**Comment by vexx32** [comment]
@lzybkr the code here mentions that certain libraries/methods/classes used by the code are not available in CoreCLR. Would we need to reimplement that, or is this pending support from .NET Core itself?

**Comment by SteveL-MSFT** [comment]
@vexx32 I looked at the script, there are some specific rights not supported in .Net Core.  I think we would just skip those and add a comment in the code in case they do show up in .Net Core in the future.

**Comment by SteveL-MSFT** [comment]
This was done as part of https://github.com/PowerShell/PowerShell/pull/8341
