### ISSUE TITLE
Get-Item -LiteralPath with full paths prefixed with "\\?\" doesn't fail with nonexistent paths (Windows)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3216]
Steps to reproduce
------------------

```powershell
Get-ChildItem -LiteralPath "\\?\$pwd\NoSuchItemHere"
Get-Item -LiteralPath "\\?\$pwd\NoSuchItemHere"
```

Expected behavior
-----------------

_Both_ commands should report an error such as follows:

```none
Get-ChildItem : Cannot find path '\\?\C:\Users\jdoe\NoSuchItemHere' because it does not exist.
```

Actual behavior
---------------

Only the `Get-ChildItem` call reports the error.

The `Get-Item` call is a quiet no-op: no output is produced and `$?` is `$True`.

Note that using the `\\?\` prefix (for opting into long path support ad-hoc) does work in principle.

Also note that the behavior doesn't change if you enable long path support by default, as described in [this blog post](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/). (Although, obviously, you then no longer need the `\\?\` prefix).

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.16) on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by iSazonov** [comment]
@mklement0 Seems it was fixed. I do not know when it happened.

**Comment by Binomimus** [comment]
Still an issue in 7.2.4
