### ISSUE TITLE
Remove type data for `System.Array` type

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#3222]
Type data for `System.Array` type contains single alias property `Count` -> `Length`. It was good for consistency, as `ICollection.Count` is implemented explicitly by arrays and was not visible while other collections types do not have `Length` property. But since PowerShell v3 it is possible to reference explicitly implemented interface members. So, this alias property no longer necessary. It also cause some headaches with `ConvertTo-Json` cmdlet:
```powershell
PS> ConvertTo-Json (,1)
[
  1
]
PS> ConvertTo-Json ([PSObject](,1))
{
  "value": [
    1
  ],
  "Count": 1
}
PS> Remove-TypeData System.Array
PS> ConvertTo-Json (,1)
[
  1
]
PS> ConvertTo-Json ([PSObject](,1))
[
  1
]
```

**Comment by daxian-dbw** [comment]
It feels reasonable to remove the AliasProperty `Count` from `System.Array`, given that powershell now exposes the `Count` property implementation from `ICollection` interface. Feel free to submit a PR, the AliasProperty is defined [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Types_Ps1Xml.generated.cs#L34).

As for `ConvertTo-Json`, the issue you listed seems to have been fixed in powershell core:
```
PS:76> ConvertTo-Json ([psobject](,1))
[
    1
]
```

**Comment by iSazonov** [comment]
@daxian-dbw What build you use? I see the issue in alfa.16 (Windows 10 14936):
```powershell
PS C:\Program Files\PowerShell\6.0.0.16> ConvertTo-Json ([psobject](,1))
{
    "value":  [
                  1
              ],
    "Count":  1
}
```

**Comment by PetSerAl** [comment]
@daxian-dbw Is it OK to edit `Types_Ps1Xml.generated.cs` directly? I mean it have `generated` in name and this header:
```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```
It looks like it was automatically generated from `Types.ps1xml` file, but I can not find this file in repository.

**Comment by iSazonov** [comment]
@PetSerAl Now `Types.ps1xml` is in code for faster Powershell start. You can modify `Types_Ps1Xml.generated.cs` (see the file history on gitHub).

**Comment by lzybkr** [comment]
The file was generated to keep the ps1xml in sync, but we no longer maintain the ps1xml, so we should remove the comment and rename the file.

**Comment by daxian-dbw** [comment]
@iSazonov My bad, I must have tried that after `Remove-TypeData`. Removing the alias property `Count` will fix that.

**Comment by iSazonov** [comment]
@daxian-dbw Clear.

@lzybkr I searched `*generated.*` - there are multiple files. Are there files that we also should fix?

**Comment by lzybkr** [comment]
For now, I would just change:

```
GetEvent_Types_Ps1Xml.generated.cs
TypesV3_Ps1Xml.generated.cs
Types_Ps1Xml.generated.cs
```

The files in GraphicalHost can be ignored, and the ones in the interpreter come from another project, so it would be better to not rename those.

**Comment by iSazonov** [comment]
I opened Issue #3230
