### ISSUE TITLE
Parameter Binding String Array

### ISSUE THREAD

**Issue by WernerMairl** [PowerShell/PowerShell#3225]
Steps to reproduce
------------------
execute the following script (as ps1 file)

```powershell

function Get-Sample
{
    [cmdletbinding()]
    param
    (
       [parameter(Mandatory = $true)][string[]]$Data 
    )
    Write-Verbose "$($Data.Length)";
}

$ErrorActionPreference = "Stop";
Get-Sample -Data @("","xx");

```

Expected behavior
-----------------
script execution without exception
the (mandatory) argument exists and is not empty, ther is no "ValidateNotNullOrEmpty" Validation so i expect that the argument is accepted as valid.

Workaround: if you set Mandatory to "false" the sample is working and the argument-array contains 2 items!

Actual behavior
---------------
Exception:
Get-Sample : Cannot bind argument to parameter 'Data' because it is an empty string.

Environment data
----------------

```powershell
Name                           Value                                                                                                                                                                                               
----                           -----                                                                                                                                                                                               
PSVersion                      5.1.14393.693                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                             
BuildVersion                   10.0.14393.693                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                                                             


```

**Comment by iSazonov** [comment]
Usually  we use unary operator `,` with arrays:
```powershell
Get-Sample -Data (,@("","xx"))
```
I believe that this is "by design". Samples https://rkeithhill.wordpress.com/2007/09/24/effective-powershell-item-8-output-cardinality-scalars-collections-and-empty-sets-oh-my/

**Comment by WernerMairl** [comment]
Ilya, thank you!
technically that sounds logically.
For me that means that i change the arguments of my function so that it works/looks better.

feedback usability: it was a unexpected behavior and i takes some time to find the reason for the exception... so any improvement here can be helpful for a lot of people.

**Comment by lzybkr** [comment]
This is by design.

Cmdlets typically accept parameters of type `string[]` so that they can process objects via the pipeline in the same way that they would if not passed in the pipeline.

To be concrete, consider: 

```PowerShell
$jobNames = "Job1","Job2"
<#1#> $jobNames | Get-Job | Receive-Job
<#2#> Get-Job -Name $jobNames | Receive-Job
```

Job objects should stream to `Receive-Job` either way - so a cmdlet accepts a `string[]` and prcoesses each element in it's `Process` block/method even though in the pipeline scenario - that array will have a single element.

Because of this - and the desire to validate parameters - we must validate the elements of the array.
