### ISSUE TITLE
Rename "generated" files

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3230]
We should rename some *.generated.cs files and correct comments (See https://github.com/PowerShell/PowerShell/issues/3222#issuecomment-283120200):

>GetEvent_Types_Ps1Xml.generated.cs
TypesV3_Ps1Xml.generated.cs
~~Types_Ps1Xml.generated.cs~~

**Comment by daxian-dbw** [comment]
PR #3231 renamed `Types_Ps1Xml.generated.cs` to `Types_Ps1Xml.cs`. Two to go 😄
