### ISSUE TITLE
Format-Table should have parameter to display all properties of all Objects

### ISSUE THREAD

**Issue by fbehrens** [PowerShell/PowerShell#3233]
In the current implementation it show the properties of the first object.

    $a = [PsCustomObject] @{a=1}
    $b = [PsCustomObject] @{a=2;b=3}
    $a,$b | ft -au
    # a  
    # -  
    # 1  
    # 2  

    $b,$a | ft -au
    # a b
    # - -
    # 2 3
    # 1

I would like to have an option which shows all properties, like

    $a,$b | ft -au
    # a b
    # - -
    # 1
    # 2 3

Sometimes I work with such sparse data, where not all objects have the same properties,
and i missed this feature.

**Comment by joeyaiello** [comment]
Yeah, that seems busted to me. 

Maybe @JamesWTruher can weigh in on whether there might be some reason why this is by design?

**Comment by fbehrens** [comment]
This would block, when part of a pipeline, same as `-AutoSize` does.
But most of the time, you use `Format-Table` as the last command for display.
This may make it reasonable to change the default behavior of the command.

**Comment by joeyaiello** [comment]
Ah, that's a good point...in that case, I don't think we should change the default (speed is king), but rather offer a parameter to override the default.

**Comment by BrucePay** [comment]
Formatting and output uses metadata and a set of heuristics to _automagically_ guess how to render an item. Format-Table in particular assumes that it's rendering a more or less homogeneous collection objects (i.e. a table). In the absence of metadata describing the specific set of properties to render, it applies heuristics to the first object picking a set of properties to display by default. You can override this set on the command line, giving a specific set of properties to render in a specific order. This addresses your example:
`$a,$b | ft -au a,b`
If you have a heterogeneous set of objects where you know the aggregate set of properties you're interested in, then simply specify those properties on the command line. If you don't know (or don't want to figure out) the aggregate set of properties, then I suggest using Format-List which works much better with heterogeneous collections of object. (Also note that Format-Table, in the absence of metadata, will only display 10 columns.)

Ultimately, the formatter is heuristic - it makes a best guess at how to render an object. In some cases that works fine but most cases require additional metadata to render objects the way you want.

**Comment by BrucePay** [comment]
Since the formatter is working as designed, I've changed the tag from ISSUE-BUG to ISSUE-ENHANCEMENT.

**Comment by thezim** [comment]
#2228 for reference.

**Comment by doctordns** [comment]
is this still a burning issue?  In the nearly 5 years since the issue was raised and I've seen no great community enthusiasm to implement a change.

**Comment by fbehrens** [comment]
Thanks for asking 😄 

It's not that burning right now, but I still think it is a useful feature.
