### ISSUE TITLE
Add tests for NanoServer and IoT for the debugging support to step in "Invoke-Command -ComputerName"

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3236]
This is a follow-up issue for PR #3015. There are 2 open comments left in the PR, both are about the test file added in the PR (test/powershell/engine/Remoting/InvokeCommandRemoteDebug.Tests.ps1):
1. Comments about [validating this feature on NanoServer and IoT and add (or skip if needed) the tests when running on NanoServer/IoT](https://github.com/PowerShell/PowerShell/pull/3015#discussion_r96794322).
2. Comments about the [`DummyHost` implementation](https://github.com/PowerShell/PowerShell/pull/3015#discussion_r96982488) in the test.

The PR has been merged, and this follow-up issue can be addressed separately.

**Comment by iSazonov** [comment]
If MSFT team migrate tests to VS Team Services the issue must be taken into account.
/cc @TravisEz13

**Comment by TravisEz13** [comment]
@iSazonov  Why is the Migration to VSTS relevant here?

**Comment by iSazonov** [comment]
@TravisEz13 I hope we'll can able to get VMs with full set platforms and versions (including IoT, Core, Server ...) and to implement remoting tests.

**Comment by TravisEz13** [comment]
Ahh, with VSTS we should be able to test with nanoserver and windowsservercore containers.  Getting VMs would cost money for the times we keep them running.

**Comment by TravisEz13** [comment]
Technically we can do this with AppVeyor, but... it's more complicated.
