### ISSUE TITLE
Discussion about 'Move test "No Exception!" pattern to "ShouldBeErrorId" '

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3238]
The Issue is opened on @TravisEz13 request in #3161 

In short:
1. Move our test helper modules in the appropriate place where are all tools `test\Tools\Modules` ([See](https://github.com/PowerShell/PowerShell/pull/3161/#discussion_r102573978) )
1.1 Load the modules with Build.psm1 (It seem we have an opened bug "submodules don't reloaded")
1.2 Load the modules in `Start-PSPester`
1.3 Use autoload by set  $env:PSModulePath in Build.psm1 or in `Start-PSPester`

2. 'Move test "No Exception!" pattern to 'ShouldBeErrorId' 

/cc @TravisEz13 @lzybkr @SteveL-MSFT @JamesWTruher @daxian-dbw

**Comment by iSazonov** [comment]
1.
Currently we have up to 9 modules in different subfolders `test\powershell`. We should place the tools in one place. Preferably near to C# tools.
Multiple test files try load the modules _multiple_ times and do that by _relative_ paths. It makes sense to load these modules once per session and release test files from unnecessary code. Yes, we will have to load Build.psm1 and perhaps call Start-PSPester once per session as minimum. I prefer Start-PSPester because it perform many essential and non-obvious action (compile C# tests...) and we must focus on community users who are unaware of these subtleties.

2.
Currently we use old Pester version without advanced support to test exceptions. Latest Pester versions already has the function but we blocked because the versions isn't still ported.
We have to use our "No Exception!" pattern to test exceptions. The problem is that we have many deviations from this pattern in test files and even bugs. In `Test.Helpers.psm1` we have `ShouldBeErrorId` function to test exceptions which can use until migrating to a new Pester version. The new template is much shorter, simpler and easier to understand and use. It also would make it easier to migrate to native Pester function in future.

**Comment by iSazonov** [comment]
@TravisEz13 @lzybkr @SteveL-MSFT @JamesWTruher @daxian-dbw
Please make a conclusion. :pray:

I see contributors become actively use `ShouldBeErrorId` in recent times.

I could split the PR  #3161 to finish the job easier (to move to `ShouldBeErrorId` and remove relative paths to test modules).

**Comment by TravisEz13** [comment]
I already suggested splitting the PR.  I think there is general agreement on moving to `No Exception!` in the helper.  I would suggest starting there and a sample test or two.  Once you know you have the pattern correct, move on to updating broader things like `Start-PSPester` and the rest of the tests.

**Comment by iSazonov** [comment]
We already actively use the pattern. So I start PR #3342 for auto-loading our test modules. This will allow us to remove the explicit loading of test modules from files and avoid their double edit.
