### ISSUE TITLE
Namespace variable notation referencing the FileSystem provider is broken on Unix platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3245]
Steps to reproduce
------------------

```powershell
Set-Location $HOME
${/:foo.txt} = 'hi, mom'
Get-Content foo.txt
````

Expected behavior
-----------------

```powershell
hi, mom
```

Actual behavior
---------------

The 2nd line causes the following error:

```
Access to the path '/:foo.txt' is denied.
....
```

Please see [this explanation](https://github.com/PowerShell/PowerShell/issues/2268#issuecomment-283755725) for why `${/:foo.txt} = 'hi, mom'` - whose _Windows_ equivalent is `${c:foo.txt} = 'hi, mom'` - should work.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.16) on Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
```

**Comment by BrucePay** [comment]
Namespace notation does work but not when using "/:" as the drive. If you create a new drive named 'root'
`    New-PSDrive -PSProvider filesystem -root / -scope global -name root:`
Then cd into that drive
`    cd "root:$home"`
doing
`    ${root:foo.txt} = 'hi, mom'`
`    Get-Content foo.txt`
works fine. 

In fact you can't use '/:' as a drive anywhere. For example, `resolve-path /:` fails with path not found whereas `resolve-path root:` works fine. This appears to be the real issue - that you can't use '/' as a drive name in paths.

**Comment by SteveL-MSFT** [comment]
The FileSystem provider explicitly disallows it:

```powershell
PS /home/steve> New-PSDrive -Root / -PSProvider FileSystem -Name /:                
New-PSDrive : Cannot process the drive name because the drive name contains one 
or more of the following characters that are not valid: ; ~ / \ . :
At line:1 char:1
+ New-PSDrive -Root / -PSProvider FileSystem -Name /:
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-PSDrive], PSArgumentExcep 
   tion
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.NewPSDriveCo 
   mmand
```

Should we support this?  Perhaps the solution is to simply have root: defined as / on Linux systems.

**Comment by iSazonov** [comment]
@mklement0 We had related PRs - could you please re-check the Issue?

**Comment by mklement0** [comment]
@iSazonov: Sorry, I just realized that I never responded:

It is still broken as of v6.1.0

**Comment by msftrncs** [comment]
Still doesn't work as of 6.2.   Is the '/' drive merely a requirement internal to powershell so that it lists the filesystem provider in the drives list?  While I understand that this would be a weird concept to Linux people to use something like `dir /:.`, the fact it is listed (by `get-psdrive`) would make me think it should at least work, even though its not needed in that example.

**Comment by danielzgtg** [comment]
Same on 7.3.4. This seems to be related to the differences with `cd /` on Windows and non-Windows platforms. `cd alias: cd /` leaves one at `alias:` on Windows, but the rootfs on non-Windows.

Following this pattern on non-Windows, I propose a simpler syntax. How about we make `${/a/b/c}` on non-Windows like `${c:\a\b\c}` on Windows, and on Windows keep the old behavior of resolving to `${variable:/a/b/c}`. This will only change strange scripts that name variables with leading slashes and make PowerShell more consistent across platforms.
