### ISSUE TITLE
Using Visual Studio Code for PowerShell Development - ext install instructions needs edits

### ISSUE THREAD

**Issue by rkyttle** [PowerShell/PowerShell#3257]
Using Visual Studio Code for PowerShell Development
https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/using-vscode.md

This page lists the following:
•Press F1 (or Ctrl+Shift+P) which opens up the "Command Palette" inside the Visual Studio Code app.
• In the command palette, type ext install and hit Enter. It will show all Visual Studio Code extensions available on your system.

These instructions need some editing.  Simply typing ext install and hitting Enter selects the first option in the command palette list, which is to Disable All Installed Extensions

Mentioning @daviwil and @rkeithhill for their visibility

**Comment by daviwil** [comment]
I believe those instructions were written back before the new extension UI existed.  Thanks for catching that!

**Comment by daviwil** [comment]
Actually, no, there's a screenshot of the new UI in this documentation...  At any rate, we'll fix it :)
