### ISSUE TITLE
Suggestion: Allow placing the stop-parsing symbol (--%) before the executable name too

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3261]
Note: I don't know whether what I'm proposing is _technically_ feasible.

It would improve the usability of `--%`, the stop-parsing symbol, if it could be placed _before_ the executable name. Currently, you have to translate executable paths based on `%...%` into PowerShell first.

A real-world use case from this [SO question](http://stackoverflow.com/q/42601270/45375):

    "%winscp%" ...

To use such a `cmd.exe` command line (mostly) as-is with `--%`, this currently has to be translated into:

    & $env:winscp --% ...

Such a translation may be too steep a hurdle for beginners, who are the primary demographic for the `--%` feature.

It would be nice if one could instead do:

     & --% "%winscp%" ...

or perhaps even let `--%` take the syntactic place of `&`:

    --% "%winscp%" ...

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and is concerned about the discoverability and complexity of this capability.  We can revisit if there are compelling use cases.  We should review if there is sufficient documentation covering calling to other shells.
