### ISSUE TITLE
tab complete align error and input block size error when output/line contains asian characters

### ISSUE THREAD

**Issue by LinkeyLeo** [PowerShell/PowerShell#3265]
<img width="714" alt="screen shot 2017-03-06 at 14 51 27" src="https://cloud.githubusercontent.com/assets/10334184/23599492/6f6d5f34-027c-11e7-9623-db85993061d8.png">
here is the screenshot
the input block always act all words in line are half-width chars, and actually it is already the end of the line in the screenshot 

Env:
macOS 10.12.3 Release / macOS 10.12.4 beta build 16E175b
PowerShell v6.0.0-alpha.16 (Downloaded from GitHub release page)

**Comment by iSazonov** [comment]
@LinkeyLeo Thanks for report the issue!
Please try install nuget package [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/) and test again.

**Comment by iSazonov** [comment]
PSReadline and engine was updated a lot of times. Fill free reopen if the Issue persists.
