### ISSUE TITLE
[adsi] type accelerator is unavailable / throws an exception

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3266]
Steps to reproduce
------------------

```powershell
[adsi]
```

Expected behavior
-----------------

The code should return a `System.RuntimeType` representing the `System.DirectoryServices.DirectoryEntry` class, similar to the full version of PowerShell.

```powershell
PS D:\Users\tsulli\sshscan> [adsi].GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    True     RuntimeType                              System.Reflection.TypeInfo
```

Actual behavior
---------------

Throws an exception.

```
PS /Users/tsulli> [adsi]
Unable to find type [adsi].
At line:1 char:1
+ [adsi]
+ ~~~~~~
    + CategoryInfo          : InvalidOperation: (adsi:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.15
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by iSazonov** [comment]
[Following types not in CoreCLR](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/System.Management.Automation/engine/parser/TypeResolver.cs#L728):
- adsi
- adsisearcher
- wni
- wmiclass
- wmisearcher
- mailaddress

**Comment by BrucePay** [comment]
@SteveL-MSFT Do we have any idea when the active directory types are going to be added to CoreClr? You can't add the accelerators until the underlying types are there so marking this "up for grabs" is kind of pointless.

**Comment by SteveL-MSFT** [comment]
@BrucePay no idea, not a focus for PS Core 6.0.0

**Comment by iSazonov** [comment]
They've just added to CoreFX without tests. The work has high priority for .NET Standard 2.0
https://github.com/dotnet/corefx/issues/2089#issuecomment-261681168

**Comment by iSazonov** [comment]
CoreFX change milestone to 2.1.0. System.DirectoryServices is still unstable.

**Comment by iSazonov** [comment]
@SteveL-MSFT @daxian-dbw I believe it is important features for Enterprises and we should enable its.
Currently there is no progress in CoreFX with `System.DirectoryServices`. So  I think we should enable it for Windows only.

It seems we cannot [directly reference in GAC ](https://github.com/dotnet/sdk/issues/987#issuecomment-318174931)`System.DirectoryServices` .
Is there a way to solve this problem?

**Comment by SteveL-MSFT** [comment]
I think we should defer this to 6.1.0 given we should depend on corefx.  Perhaps we should suppress the type accelerator for now.

**Comment by iSazonov** [comment]
In CoreFX repo comments say that it depends very much on COM, also, there is no port LDAP library yet. I believe that this will not be done much longer. That's why I'm requesting to enable it on Windows based on GAC dlls.

**Comment by SteveL-MSFT** [comment]
I'm not sure if we want to set a precedent on creating a dependency on the GAC from PSCore.  cc @daxian-dbw

**Comment by daxian-dbw** [comment]
It seems DirectoryServices code is available in corefx: https://github.com/dotnet/corefx/tree/master/src/System.DirectoryServices/src/System/DirectoryServices
and the preview version nuget package for `System.DirectoryServices` is also available on dotnet-core feed (https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.DirectoryServices).
Can't we wait for that to mature and depend on that instead?

**Comment by SteveL-MSFT** [comment]
I suggest we wait until 6.1.0 timeframe to tackle this

**Comment by iSazonov** [comment]
I agree that native support would be best. But...
1. My scripts is 80% Active Directory related - so I cannot use 6.0 in Enterprise at all. All the more ActiveDirectory module is not supported. ETA? No one can use PowerShell Core 6.0 version in Enterprises.
2. DirectoryServices nuget package is not updated for about a last month. Works frozen.
3. Little progress is in last year.
4. It is not stable and haven't tests.
5. It is not ported. No plans (possibilities) is to port all APIs (depends on COM and LDAP native Windows dlls).
6. No full time MSFT employers works on the DirectoryServices.

**Comment by SteveL-MSFT** [comment]
@iSazonov would you be ok with a workaround (in your scripts or profile) until we can do this properly in 6.1.0?

```powershell
Add-Type -AssemblyName $env:windir\microsoft.net\framework64\v4.0.30319\system.direc
toryservices.dll
[psobject].Assembly.GetType("System.Management.Automation.TypeAccelerators")::add("a
dsi","System.DirectoryServices.DirectoryEntry")
[adsi]"WinNT://${env:computername}/${env:username}"
```

**Comment by iSazonov** [comment]
I thought about this and about our compatibility module.
My concerns:
1.  I don't believe that the module will be ready in RTM time.
2. I see we have codes for DirectoryEntry (ExtendedAdapter and etc.) - it could be the main breaking change.

Suggestion is - create temporary nuget package to expose the GAC dll until CoreFX issue a ported version.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agreed we should not take explicitly dependency on assemblies in the GAC.  However, to resolve this class of issues, we agreed that we should have a module like "WindowsPSModulePath" to create aliases that have been excluded from PSCore6.  Steve to work on that module.  Leaving this issue until DirectoryEntry shows up in corefx.

**Comment by SteveL-MSFT** [comment]
Unfortunately, it appears my workaround isn't complete so I can't actually enable this in my module.  Currently, we explicitly `#ifdef` out the [type convertors for ADSI](https://github.com/PowerShell/PowerShell/blob/4bc52d2358222084738157a08907fac32d13bd3a/src/System.Management.Automation/engine/LanguagePrimitives.cs#L2343) (and WMI) as the type doesn't exist in corefx.  Without the type convertors, it's only a partial solution to manually add the type accelerator.

**Comment by lzybkr** [comment]
It would be useful to have a "delay resolved" type accelerator - that would help startup performance a bit by not eagerly loading all the assemblies referenced by accelerators, and as a bonus, you could add the `adsi` accelerator in the core.

That said, I never implemented this idea because I was pretty sure some other code running during startup would just load the assemblies I was trying to defer.

**Comment by dronkoff** [comment]
So, gentleman, can I search in AD from PS Core 6.0 or need to wait for future releases?

**Comment by iSazonov** [comment]
Try the module https://github.com/markekraus/PSCoreWindowsCompat

**Comment by markekraus** [comment]
@dronkoff the PSCoreWindowsCompat will add most of the .NET `System.DirectoryServices` name space back (Only works on windows, no support for macOS or Linux). The ADSI type accelerators and the special things PS does with them are not available.

**Comment by dronkoff** [comment]
Guys, that works for me. Thanks @markekraus !
Is it an official way (workaround) from PS team?

**Comment by iSazonov** [comment]
We consider Windows Compatibility Pack as an opportunity to return back the excluded features in PowerShell Core on Windows until .Net Core implement the APIs.
Currently Windows Compatibility Pack is still _preview_.
