### ISSUE TITLE
Webcmdlets should parse the <html><head><meta charset="foo"> attribute for the correct encoding if not in http header

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3267]
Some websites do not populate the `charset` property of the `content-type` header so characters aren't rendered correctly.  Suggestion is to expose a `-charset` parameter, however the user still needs to know the expected charset.  Advanced users today can do the encoding translation in script.  `utf-8` probably works in most cases, so not entirely sure how useful this will be to expect the user to know ahead of time the correct charset.

See discussion from https://github.com/PowerShell/PowerShell/issues/3126 for details on how this came about

**Comment by iSazonov** [comment]
Point for the fix is [here](https://github.com/PowerShell/PowerShell/blob/c74b2a7670c79b02bb526c0998720b93ac385d03/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebRequestPSCmdlet.CoreClr.cs#L512)

**Comment by iSazonov** [comment]
I believe we should discuss here a default encoding for Web cmdlets.
Currently [we use RFC 2616 "ISO-8859-1" ](https://github.com/PowerShell/PowerShell/blob/77c622eeea474e21af0ea954836d49c53f71f5b1/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs#L20)
In fact, browsers for a long time use Windows-1252.
And HTML5 default is UTF-8.

Perhaps we should also use Windows 1252.

**Comment by chuanjiao10** [comment]
There are all like powershell fans,do not be perfunctory.
I disagree "-CharSet", do not push this question to the users.
 Think:
 If the browser does not recognize 【meta charset="gb2312"】,every time you need to manually select   ...

1 Receive raw html string
2 Find out after 'charset=' strings.
3 use 【some charset】 encoding raw html，and out to console  
2 and 3 are so hard that powershell can not do it?

**Comment by iSazonov** [comment]
I looked Web cmdlets and found that we use `ContentType` parameter to encode a request (Content-Type header can contains `charset` value). If we don't specify a charset in `ContenType` we use default charset ISO-8859-1.
For decoding a response we use a charset from `ContentType` of the response. If a server return no `ContentType` we use the same default charset ISO-8859-1.

So we should treat `-CharSet` as `-ResponseCharSet`.

After some thought, I believe that using Windows 1252 as default is obsolete and we should aim at HTML5 and UTF-8 as defaults.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree this is an issue for customers.  proposal is to parse the HTTP header first, if charset is in content-type, we use that.  otherwise if content-type is html, we parse `<meta charset="X">`  for the charset attribute and use that

**Comment by iSazonov** [comment]
In Windows Powershell we use Internet Explorer to parse HTML. What portable parser we can use in PowerShell Core?
And if HTML don't contain <meta charset="foo"> ? What defaults we should use?

**Comment by SteveL-MSFT** [comment]
@iSazonov the proposal is that we don't rely on any browser for the html parsing (if complete parsing is needed, I still think it would make more sense in a `convertfrom-html` cmdlet).  I think "best effort" for this is sufficient (perhaps even just a regular expression) to cover the majority of cases and we wouldn't worry about malformed html.

**Comment by iSazonov** [comment]
@SteveL-MSFT Original Windows web cmdlet returns `ParsedHtml        : mshtml.HTMLDocumentClass` - we want lost the functionality?

**Comment by SteveL-MSFT** [comment]
@iSazonov `.ParshedHtml` relied on Internet Explorer.  I don't think we can have a dependency on any particular web browser in the webcmdlets.

To answer your other question I missed, if `<meta charset>` doesn't exist and `charset` isn't specified in the `content-type` HTTP header, then we do what we do today which is assume ISO-8859-1

**Comment by iSazonov** [comment]
@SteveL-MSFT 
>  .ParshedHtml  relied on Internet Explorer

If we use any ported library for HTML parsing we will solve this Issue, get `ParshedHtml` ported, as well as get a base for `ConvertFrom-HTML`.

I wonder about `ISO-8859-1`. Why we do not want to accept the new standard HTML5?

**Comment by SteveL-MSFT** [comment]
@iSazonov my understanding is that HTTP1.1 still defaults to `iso-8859-1`, if the content-type is `text/html`, we should just follow the [HTML 5 rules for determining content type](https://dev.w3.org/html5/cts/html5-type-sniffing.html) ideally just using one of the OSS HTML parsing libraries you already found

**Comment by iSazonov** [comment]
@SteveL-MSFT It seems the doc is very old. New is http://www.w3.org/TR/html5/syntax.html#the-input-byte-stream It don't mention `iso-8859-1` at all.

**Comment by iSazonov** [comment]
Currently CoreFX already use [UTF8 as default](https://github.com/dotnet/corefx/blob/b1865ea0847a7a86baefe8378b772ecf0b785681/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L223).

**Comment by SteveL-MSFT** [comment]
@iSazonov that's html5, HTTP 1.1 defaults to ISO-8859-1 if charset is not specified.  See 3.4.1 in https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html

**Comment by iSazonov** [comment]
These standards are too muddled 😕 From https://tools.ietf.org/html/rfc7231:
>The default charset of ISO-8859-1 for text media types has been
   removed; the default is now whatever the media type definition says.
   Likewise, special treatment of ISO-8859-1 has been removed from the
   Accept-Charset header field.

In any case we trust CoreFX. Yes?

**Comment by SteveL-MSFT** [comment]
Ideally, we should just leave this to corefx.

**Comment by iSazonov** [comment]
This already is in CoreFX so we can. 
Only is this in CoreFX version we use currently or we blocked until NetStandard 2.0?

**Comment by SteveL-MSFT** [comment]
Marking as waiting on NetStandard20.  Once we move to latest CoreClr, we can verify if this is still an issue.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can you initiate internal conclusion about using HtmlAgilityPack or
AngleSharp? What one we can more trust?
Then I would try to replace IE on one of these parsers for PowerShell Core (and leave IE for FullCLR).

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee believes AngleSharp is a better choice as it seems to be more actively updated and this should be a separate `convertfrom-html` cmdlet.  The `charset` attribute on the `meta` html tag parsing should still be in the webcmdlets and a simplified best effort than using a complete html parser.

**Comment by chuanjiao10** [comment]
Please help look, there seems to be a problem. could reopen?


Steps to reproduce
------------------
Invoke-RestMethod -Uri 'http://www.gov.cn' |more #html 4.01 utf8 
Invoke-RestMethod -Uri 'http://news.sina.com.cn' |more # utf8
Invoke-RestMethod -Uri 'http://ip138.com' |more #gb2312
Invoke-RestMethod -uri "http://tv.sohu.com" |more #gbk 

Environment data
----------------
win10 15063	+	PowerShell v6.0.0-beta.6
cenos 7.3 + PowerShell v6.0.0-beta.6

**Comment by SteveL-MSFT** [comment]
@dantraMSFT can you look into this?

**Comment by dantraMSFT** [comment]
Looking now. The challenge will be verifying.

**Comment by dantraMSFT** [comment]
The problem occured because Invoke-RestMethod was calling ContentHelper.GetEncoding.  This returns a fallback encoding which was defeating checks for meta tags in the response.  Explicit tests were added to cover the same variations as are tested for Invoke-WebRequest.

**Comment by chuanjiao10** [comment]
From beta7 i tested again,return:


already fixed
------------------
Invoke-RestMethod -Uri 'http://www.gov.cn' |more #html 4.01 utf8 
Invoke-RestMethod -Uri 'http://news.sina.com.cn' |more # utf8


No fixed,Garbled still
------------------
Invoke-RestMethod -Uri 'http://weibo.com' | more #gb2312
Invoke-RestMethod -Uri 'http://ip138.com' | more #gb2312

Invoke-RestMethod -Uri 'http://tv.sohu.com' | more #gbk 
Invoke-WebRequest -Uri 'http://tv.sohu.com' #gbk


Environment data
----------------
cenos 7.3 + PowerShell v6.0.0-beta.7

**Comment by dantraMSFT** [comment]
I'm not seeing the problem with 'http://weibo.com'.  Invoke-RestMethod is detecting the encoding correctly.  Can you be more specific?

For tv.sohu.com and ip138.com, I found a bug in Invoke-RestMethod. It is calling WriteVerbose with the encoding indicating the encoding name or header name but Encoding.EncodingName is throwing.  I'll need to change this and update the tests.

**Comment by chuanjiao10** [comment]
Oh, looks like this is .Net core 2.0 problem. Please help confirm the following:

Same as #3126,this code can return right strings of "http://weibo.com".
```
$gbk = [System.Text.Encoding]::GetEncoding(936) 
$utf8 = [System.Text.Encoding]::GetEncoding(65001) 
$iso88591 = [System.Text.Encoding]::GetEncoding(28591) #ISO 8859-1 ,Latin-1

$wrong_string = Invoke-RestMethod -Uri 'http://weibo.com'
$wrong_bytes = $utf8.GetBytes($wrong_string)

$right_bytes = [System.Text.Encoding]::Convert($utf8,$iso88591,$wrong_bytes)
$right_string = $gbk.GetString($right_bytes)
write-host $right_string
```
Environment data:
windows 10 build 14393 + PowerShell 5.1


=================================================
but this codes can not run in linux + powershell beta7, Problem code:

```
$utf8 = [System.Text.Encoding]::GetEncoding(65001) #normal 
$gbk = [System.Text.Encoding]::GetEncoding(936) #System.NotSupportedException
```
return:
Exception calling "GetEncoding" with "1" argument(s): "No data is available for encoding 936. For information on defining a custom encoding, see 
the documentation for the Encoding.RegisterProvider method."

Environment data:
cenos 7.3 + PowerShell v6.0.0-beta.7

**IS THIS .NET CORE 2.0 PROBLEM?** Please help us to see.

**Comment by chuanjiao10** [comment]
somebody tell me, .net core need:

1 import dll from nuget.   "System.Text.Encoding.CodePages"
2 use System.Text.Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)

But I do not know .net core 2.0 need to be so.

**Comment by iSazonov** [comment]
We already do this in [private static void EncodingRegisterProvider()](https://github.com/PowerShell/PowerShell/blob/deb8c4485d0b9755bdfa1f17c9d8bdd2855e2620/src/System.Management.Automation/utils/ClrFacade.cs#L131)

**Comment by SteveL-MSFT** [comment]
Any further work on this I'm deferring to 6.1.0

**Comment by chuanjiao10** [comment]
ao

**Comment by MSAdministrator** [comment]
Submitted RFC for the creation of `ConvertFrom-Html` here: https://github.com/PowerShell/PowerShell-RFC/pull/137

**Comment by iSazonov** [comment]
We get new HttpClient with .Net 3+ so I remove the label.
