### ISSUE TITLE
Invoke-WebRequest

### ISSUE THREAD

**Issue by ZSSchulze** [PowerShell/PowerShell#3278]
Steps to reproduce
------------------
Invoke-WebRequest 

Expected behavior
-----------------
ParsedHtml should contain the ParsedHtml

Actual behavior
---------------
ParsedHtml is empty

Environment data
----------------

Name                           Value                                                                                                      
----                           -----                                                                                                      
PSVersion                      6.0.0-alpha                                                                                                
PSEdition                      Core                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                    
BuildVersion                   3.0.0.0                                                                                                    
GitCommitId                    v6.0.0-alpha.16                                                                                            
CLRVersion                                                                                                                                
WSManStackVersion              3.0                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                        
SerializationVersion           1.1.0.1

**Comment by ZSSchulze** [comment]
Opened at another ticket

**Comment by iSazonov** [comment]
Duplicate #2867
