### ISSUE TITLE
Microsoft.PowerShell.LocalAccounts Add support for ComputerName parameter. 

### ISSUE THREAD

**Issue by thesmall** [PowerShell/PowerShell#3282]
There have been several implementations of what is now officially called Microsoft.PowerShell.LocalAccounts over the last 10 years. 

Most of those implementations feature a parameter -ComputerName, that allows you to interact with remote computers. I obviously cannot speak for everyone here, but the benefit of having such a parameter allows you to execute against a host that does not have this module, and seeing as how Microsoft.PowerShell.LocalAccounts is only available in PowerShell 5.1 (from the searching ive done), its not always feasible to simply patch a server to have PowerShell 5.1.

Therefore, it would be a great feature to expose a -ComputerName parameter in the official implementation, such that users of PowerShell can execute the functions in this module against hosts that do not have their own Microsoft.PowerShell.LocalAccounts.

I did do a search for this "issue" and did not find any open issues matching it, but if there is, apologies for the duplication. Feel free to merge or close as needed.

**Comment by ThomasNieto** [comment]
Are you able to use `Invoke-Command` in this scenario?

**Comment by jdhitsolutions** [comment]
Under review by the Cmdlet Working Group
