### ISSUE TITLE
PS 6  and ISE with Windows PE

### ISSUE THREAD

**Issue by LoggSar** [PowerShell/PowerShell#3283]
Hi there

I have two questions regarding WindowsPE (at the moment still 10240 based):

1.) Is there a possibility to test the actual 6.0-Release under PE?
     I found none, but this can be my mistake.
2.) Are there some plans that the ISE can run under PE?

THX

**Comment by joeyaiello** [comment]
1. We haven't explored it yet, and it's not currently in our priority queue.
2. No, and given the dependency on certain UI frameworks, it's extremely unlikely.

**Comment by LoggSar** [comment]
OK, thank your.
