### ISSUE TITLE
Get-ComputerInfo.Tests.ps1 should cache the WMI instances

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3292]
The code currently makes separate WMI calls each time it needs a property.  Each call is relatively expensive.  Since the data doesn't appear to be transient, the test should cache the instance and reuse it.

**Comment by jeffbi** [comment]
It does cache it. The Get-CimClassPropVal function calls the Get-CimClass function, which caches each instance into $cimClassList.

**Comment by SteveL-MSFT** [comment]
@jeffbi I should have looked at more of the code, you're right
