### ISSUE TITLE
Powershell should make it easier to use decimal values

### ISSUE THREAD

**Issue by fanoI** [PowerShell/PowerShell#3293]
Steps to reproduce
------------------
Write 42.42 - 42 in the PowerShell prompt

Expected behavior
-----------------
0.42 is returned

Actual behavior
---------------
0,420000000000002 is returned

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
A possible mitigation could be as could be as it is done in C# Interactive to do "42.42m - 42m" to force the evalutation as Decimal.

**Comment by SteveL-MSFT** [comment]
Can you try with alpha.16?  Here's what I get:

```powershell
PS /home/steve/repos/PowerShell> 42.42 - 42                                                    
0.420000000000002
PS /home/steve/repos/PowerShell> (42.42).gettype()                                             

IsPublic IsSerial Name                                     BaseType                           
-------- -------- ----                                     --------                           
True     True     Double                                   System.ValueType  
```

**Comment by SteveL-MSFT** [comment]
Sorry, misread your request.

**Comment by SteveL-MSFT** [comment]
Workaround:

```powershell
PS /home/steve/repos/PowerShell> [decimal]42.42 -42                                            
0.42
```

The concern I have is this would be a breaking change

**Comment by fanoI** [comment]
On the other hand think when you use it to do calculation on the shell? The user would expect the behavior of the calculator application  and it gets an wrong result...

**Comment by SteveL-MSFT** [comment]
@fanoI I agree that for interactive shell, I would prefer it to be a decimal for quick calculations.  However, we try to keep the shell and scripting experience the same so there aren't any surprises switching from one to the other.  Maybe for interactive we could do something with formatting so it looks like a decimal even though it's still a double.

**Comment by lzybkr** [comment]
I wouldn't change the default formatting because it is difficult to infer the expected precision people want to see, but it's relatively easy for folks to change that themselves.

We could add an `m` suffix though, I think that's a good idea.

**Comment by rkeithhill** [comment]
Isn't `d` already defined for decimal literals?

**Comment by SteveL-MSFT** [comment]
@rkeithhill you're right

```powershell
PS /home/steve> 42.42d - 42                                                                    
0.42
```

**Comment by lzybkr** [comment]
I implemented it and I still can't remember that, `d` will forever mean double to me.

We could still add `m` to align with C# - I'm not sure if that's a good idea or not though.

**Comment by rkeithhill** [comment]
LOL.  I remembered that this feature was added but my first guess was `m` as well.  When that didn't work, I figured it might be `d` (for decimal).

**Comment by BrucePay** [comment]
Some comments: 
- PowerShell uses d for decimal because m was for 'mega'. m eventually turned into mb at a partners' request but that was later on. 
- FWIW the 'd' suffix e.g. 123d is what Visual Basic uses. Don't assume all PowerShell users are C# programmers.
- 'd' for decimal is certainly more mnemonic.
- Floating point operations in PowerShell are double by default so there's no suffix needed. You have to use the suffix f to force single precision floats. Don't assume all PowerShell users are C/C++ programmers.

**Comment by fanoI** [comment]
It is possible to add a sort of configuration so that Decimal is used by default when calculations are done in the shell?
