### ISSUE TITLE
OrderedDictionary: PSReference: Exception: … does not contain a method named 'Contains'

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#3312]
Good morning

I have to handle a big OrderedDictionary. Therefore, I passed it by reference to a function.
Unfortunately, this referenced object does not know the OrderedDictionary methods like Contains().

In https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Ref
there is no note about any restrictions. If this kind of .Net (!) object is not supported, it would be great to get a more descriptive error.

Steps to reproduce
------------------
```
# Just test if [ref]$dict has a method named 'Contains'
function TestRef([ref]$adict) {
	# This should probably will create an exception:
	Write-Host $adict.Contains('a')
	# Exception:
	# Method invocation failed because 
	# [System.Management.Automation.PSReference`1[[System.Collections.Specialized.OrderedDictionary, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]] 
	# does not contain a method named 'Contains'.
	# +     Write-Host $adict.Contains('a')
	# +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	#     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
	# + FullyQualifiedErrorId : MethodNotFound
}

# Create an OrderedDictionary
$ODict = New-Object Collections.Specialized.OrderedDictionary([StringComparer]::OrdinalIgnoreCase)
$ODict['a'] = '1'

# Assure that there is a method named 'Contains'
Write-Host $ODict.Contains('a')

# Pass ODict by reference and call Contains in it
TestRef ([ref]$ODict)

```

Expected behavior
-----------------
[ref] should work as the developer expect. 
Or it should create a parser exception (which is probably almost impossible).
Or it should create a clear exception says that this kind of object is not supported.

Actual behavior
---------------
It looks like there is a wrapper for [ref] Objects which does not completely support common .Net Objects.

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by lzybkr** [comment]
This is by design.  Objects other than value types are passed by reference, so you shouldn't normally use `[ref]`.

`[ref]` exists mostly for COM support. It is usable outside of COM though, it creates a wrapper object which you need to unwrap.

**Comment by schittli** [comment]
Hi Jason, thank you very much!, I'm sorry for the trouble. 
I've added a 'not helpful' vote to the help page [about_Ref]( https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Ref) because it does not explain which kind of objects needs a [ref] for methods.
