### ISSUE TITLE
AppImage download filename should include version number

### ISSUE THREAD

**Issue by zaxebo1** [PowerShell/PowerShell#3314]
appimage format of powershell was developed in the issue https://github.com/PowerShell/PowerShell/issues/2024

Now, the AppImage download for " PowerShell v6.0.0-alpha.17 Release" provided at url https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.17 currently has the name "PowerShell-x86_64.AppImage"

I think  currently the filename **"PowerShell-x86_64.AppImage"** file should be **renamed** as 
**"powershell-x86_64-6.0.0-alpha.17.AppImage"** . Just like filename of other download formats, Appimage filename should also include version

**Comment by andschwa** [comment]
Looking at it, our names are inconsistent in general. The Windows ones use the casing `PowerShell`, yet the Linux and macOS ones use `powersehell`, with AppImage using `PowerShell`. Weird.

**Comment by SteveL-MSFT** [comment]
@andschwa although the mixed casing are inconsistent with each other, they are consistent with the target platforms.  The Linux releases are consistent with Fedora guidelines (for example) which say that they SHOULD be lowercase, while AppImage appears to have adopted Pascal casing (along with Windows).  I'll add the `version` to the AppImage filename, but not make any changes to the casing.
