### ISSUE TITLE
To install an application using powershell, clicking, keystrokes and detection of new pop up dialog box

### ISSUE THREAD

**Issue by krishna1291soni** [PowerShell/PowerShell#3317]
hello everyone!
I m new to Power Shell, I had written a piece of code for the execution of a .exe file that installs itself. The part of code where I am failing is that i had given time slots in seconds so that installation  will finish within that duration and then take keystroke "enter" to finish the installation. But it is not reliable at all because the installation speed depends upon the  processor speed of machine and I have to use this code in different machines, so if the installation is taking 20 sec and i had given 15 seconds then it will take "enter" keystroke before the completion of installation, which will click on "cancel" in dialog box, and the installation is terminated without completion. Is there any way that power shell can detect new pop up dialog box or it will check whether the process is finished or not and then execute rest of the program. 
please help me in solving this problem.... !

$InstallFile = "D:\File for installation\folder\file.exe"
Start-Process $InstallFile
$wshell = New-Object -ComObject wscript.shell;
$wshell.AppActivate($InstallFile)
Sleep 1
$wshell.SendKeys('~')
Sleep 1
$wshell.SendKeys('~')
$wshell.SendKeys(" ")
$wshell.SendKeys("{TAB}")
$wshell.SendKeys("{TAB}")
$wshell.SendKeys('~')
Sleep -s 10
$wshell.SendKeys('~')
Sleep -s 5

**Comment by iSazonov** [comment]
Almost all standard installers have silent mode.
