### ISSUE TITLE
Unexpected module loading through NuGet

### ISSUE THREAD

**Issue by chunqingchen** [PowerShell/PowerShell#3325]
Steps to reproduce
------------------
Get VS 2017 RTW. 
Install an “experimental” VSIX of NuGet like the one here by double clicking on it:
\\nuget\nuget\Share\Drops\CI\NuGet.Client\dev\2381\artifacts\VS15\NuGet.Tools.vsix
Open PackageManagerConsole…

Expected behavior
-----------------
correct version of  'NuGet.PackageManagement.PowerShellCmdlets.dll' is loaded

Actual behavior
---------------
the wrong NuGet.PackageManagement.PowershellCmdlets.dll is pulled in

Environment data
----------------
PSVersion                      5.1.14393.693                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                              
BuildVersion                   10.0.14393.693                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                  
SerializationVersion           1.1.0.1            

```

**Comment by SteveL-MSFT** [comment]
Seems like this is an issue with VS2017 which hosts PowerShell and has their own PackageManagement module?

**Comment by alpaix** [comment]
NuGet Package Manager Console (PMC) hosts PowerShell for running NuGet cmdlets and executing install/uninstall/init package scripts. It imports `<extension root>\Modules\NuGet\NuGet.psd1` module which in its turn depends on a nested module `NuGet.PackageManagement.PowerShellCmdlets.dll`. 

The last one is loaded from wrong location when working with "experimental" VS instance.

**Comment by nkolev92** [comment]
Any updates here?
ETA?

**Comment by daxian-dbw** [comment]
Close via #5161
