### ISSUE TITLE
Question: How to create an ahead-of-time compiled native powershell ("crossgen")

### ISSUE THREAD

**Issue by SRGOM** [PowerShell/PowerShell#3335]
On #3249 @iSazonov helpfully pointed out that one can use "crossgen" to get binaries that run start up pretty fast. 
I explored and it looks like one cannot get such binaries from a powershell instance alone. Is my observation correct? (I'm not sure because technically if I have the CLR assembly and .NET core on my computer already so it looks like it may be possible).

To continue on that, I want to ask here how does one go about getting such binaries? 

Could somebody give steps for that, please?

 I'd like to know the following:

1) Does it require installation of tools outside of powershell? I am currently using AppImage on arch. Quite a few power users use Arch so I would hope you guys would treat it on an equal footing as the sysadmin-favoured RH/Suse. Could you list the tools required? 

2) The generation procedure

I am hoping that the answer of this question could later be documented into something useful for more people looking to do this.

**Comment by SteveL-MSFT** [comment]
The official releases are already crossgen'd.  You can build it yourself using `start-psbuild -crossgen` if you clone our repo and import the `build.psm1` module

**Comment by SRGOM** [comment]
@SteveL-MSFT I'm using the official build, the AppImage meant for Linux distros. I saw a speed difference of ~1.9s to ~1.5s in the latest build for powershell -c 'exit'. 

While that is great, would it be unreasonable to say it's still pretty slow? I've never used any other aot compiled binary before but I was hoping it would start much faster.

**Comment by SteveL-MSFT** [comment]
Our targets have been 250ms for startup.  There is an open issue to improve startup perf for Beta1 https://github.com/PowerShell/PowerShell/issues/1954

**Comment by SRGOM** [comment]
@SteveL-MSFT Got it. Hope to see this soon. 

Closing this issue since distributed AppImage is already crossgen'd.
