### ISSUE TITLE
PS non-interactive and confirmation messages

### ISSUE THREAD

**Issue by f0rt** [PowerShell/PowerShell#3337]
Team,

We're using PS for automation on internal build system. When running PS on non-interactive mode we get error messages like this for cmdlets that are trying to prompt:

> Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.

This makes it very difficult to diagnose the problem on the internal build system. I guess printing the actual prompt message will resolve the issue for us.

Thanks,
f0rt

**Comment by SteveL-MSFT** [comment]
The fix appears pretty simple to suppress this.  There's actually a bunch of code to explicitly support this.  Not clear if we should just remove the current ThrowOnReadAndPrompt code?  Doesn't seem like it provides value to have this exception.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee needs more information on the specific repro to understand the scope of this issue and the best way to resolve.  Is the script explicitly trying to confirm?  Do you want the command to auto-confirm or just want a better error message?  Please include `expected` error message.  Thanks.

**Comment by f0rt** [comment]
We get these messages when analyzing failed build logs. Here is a [recent example of the issue](https://github.com/PowerShell/PowerShellGet/issues/101). 

- The script is not trying to confirm explicitly since this is unexpected behavior. 
- We need **better error messages** to see what caused the prompt and how we should avoid it (pass -Confirm:$false/-Force in some cases or another workarounds as suggested in the example above)
- Error message should contain: the cmdlet causing the prompt, location(script file, line), error message, suggested way to bypass it (especially when it's not obvious) . For example:

> An exception occurred when running script "test.ps1"  on line 34. The cmdlet "Register-PSRepository" prompted "< message >". Prompts are not supported in non-interactive mode. You can avoid the prompt by < suggested fix >.

Thanks

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee it appears that powershell host is doing the right thing outputting an error message of something it can't support in `-noninteractive` mode along with the cmdlet trying to make the ShouldProcess call.  In this case, we should have a PSScriptAnalyzer rule to catch cmdlets that make explicit prompts without supporting `-force` and `-confirm`

**Comment by atruskie** [comment]
Any chance of reconsidering this?



- I ran into this issue while testing a script on my CI
![image](https://user-images.githubusercontent.com/1452968/106241173-4be36980-6251-11eb-9997-1591cc32943f.png)
- The error message ` Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."` provides no useful information
- There are dozens of results that show up in an internet search which are all very misleading
- Even after working out he issue, AFAIK there's no way to detect a non-interactive mode, If I could detect ineractivity so I can work around it or present a better experience to the script consumer (i.e. bailing early, suggesting they use `-Force` when non-interaactive)
