### ISSUE TITLE
Runspace pools are they sharing states or objects between processes ?

### ISSUE THREAD

**Issue by elpj** [PowerShell/PowerShell#3344]
Hi, I have a simple application written in c# for .NET Framewrok 4.6  that hosts a RunspacePool that is initialized with maximum runspaces to 5 and minimum to 2.  Everything works fine, commands get executed at decent speed. However, when I start 20 instances of that application on the same machine, it gets very slow for even only one application ( one runspacepool)  to run commands. 

When I start my application alone (not all the 20) and I start PowerShell ISE or PowerShell at the same time, I see a significant increase in the startup time, even thought they are not loading any module. 

Then comes my question,

Are Runspacepool sharing some kind of state or objects between processes ?

**Comment by lzybkr** [comment]
The only shared state is a file based cache of the commands exported by modules - it is not specific to any host or runspace pools, so your host should benefit from this cache.

I suggest you use [perfview](https://github.com/Microsoft/perfview) or [Windows Performance Toolkit](https://msdn.microsoft.com/en-us/windows/hardware/commercialize/test/wpt/index) to analyze the performance and compare what's happening in your host versions regular powershell.

One thing to look for is how much time is spent in the JIT.
