### ISSUE TITLE
Scrub for 'Windows PowerShell' in strings

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3345]
There are still some error messages and warnings being emitted by PowerShell Core that refer to "Windows PowerShell". We should scrub through [all strings in the repository](https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=%22windows+powershell%22) and change these to "PowerShell" where applicable (i.e. for everything that isn't FullCLR-specific).

**Comment by zackschuster** [comment]
If a file contains a reference to things like `<windows.h>`, `System.Windows.Forms` or .NET Framework 4.5, does that invalidate it for conversion? Going through the code, it seems like all instances of "Windows PowerShell" are either directly or indirectly connected to those resources, which makes me wary of submitting a PR with any conversions.

**Comment by SteveL-MSFT** [comment]
@zackschuster That's a good point.  Currently, the Windows PowerShell (fullclr) code is intermixed with the PSCore code.  Let's defer this for now.

**Comment by iSazonov** [comment]
We have dup #1372

**Comment by iSazonov** [comment]
Currently we only have 'Windows PowerShell' in some Resx files related to workflows and remoting.
Also we have 'Windows PowerShell' strings in comments in *.cs files.

Should we keep the Issue open?

**Comment by SteveL-MSFT** [comment]
I think the intent of this was more for user facing strings, so I think we can resolve this as fixed.
