### ISSUE TITLE
CentOS/Red Hat (RHEL) 7.2/7.3 Support

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3349]
It looks like we've already published our CentOS packages (which hopefully shouldn't need to be different than RHEL packages) to our [RHEL 7](http://packages.microsoft.com/rhel/7/) and [RHEL 7.3](http://packages.microsoft.com/rhel/7.3/) repositories. Going forward, we should:

- [ ] Test these packages on RHEL 7.2 and 7.3 on same cadence to ensure that are working properly 
- [ ] Remove "centos" from the package name to indicate that the RPM is universal across CentOS and RHEL ([as .NET Core has done](http://destek.serbestinternet.com/rhel-repo/rhel-7-server-dotnet-rpms/Packages/))

**Comment by SteveL-MSFT** [comment]
@joeyaiello currently, we name it `powershell-6.0.0_alpha.17-1.el7.centos.x86_64.rpm`, should we change it to `powershell-6.0.0_alpha.18-redhat.x86_64.rpm`?

**Comment by SteveL-MSFT** [comment]
@joeyaiello also, RHEL appears to be paid only (presumably for support), not sure how we should test RHEL regularly

**Comment by joeyaiello** [comment]
@SteveL-MSFT no the recommendation here would be to remove the `centos`/`redhat` qualifier ([`el7` should already be sufficient here](https://unixy.net/secure/knowledgebase/104/What-does-el5-el6-and-el7-mean.html)). 

Also, I did some more research and, while the source has to be available (it's GPL), Red Hat does some stuff with trademarks that prevent redistribution of RHEL binaries. However, the difference between RHEL and CentOS is even less than I previously understood, so I'm now proposing that we just test again CentOS 7.2 and/or 7.3 in addition to 7.1. 

Let's talk offline on which we should do and how we prioritize them.

**Comment by JamesWTruher** [comment]
Travis-CI doesn't support running build/test on CentOS directly. There are some forum threads on running tests on CentOS via docker, but that seems to be quite old (2015).

**Comment by SteveL-MSFT** [comment]
I suspect we'll need VMs for getting regular coverage of distros

**Comment by kfiresmith** [comment]
+1 for as much testing as possible on Centos 7 as we are a prod RHEL 7 shop that will probably end up using Powershell for AzureRM functions on RHEL.

**Comment by joeyaiello** [comment]
According to @JamesWTruher, we at least now have a release-time VM for testing CentOS 7.3 before we go out with a release.

**Comment by joeyaiello** [comment]
Can anyone confirm that this means we're confident we support 7.2/7.3? If it's supported, let's add it to the matrix and close this out. 

/cc @JamesWTruher @SteveL-MSFT @PowerShell/powershell-maintainers

**Comment by chuanjiao10** [comment]
hello anyone:
I use centos 7.3, or the latest version. I am willing to help test, test requirements as simple as possible, try to use a unified format. Thank you. Cc me or mail me ` 1328486072@QQ.com ` . I try to give test results within 48 hours.

**Comment by SteveL-MSFT** [comment]
I believe @JamesWTruher has already verified that the package works on CentOS.  He'll run the tests manually for the beta1 package and we'll get automation running nightly later.

**Comment by JamesWTruher** [comment]
this seems to be working fine at this point
