### ISSUE TITLE
Format-Hex should support all primitive types (including enums) and arrays of these types  - instead of this random assortment.

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#3358]
Steps to reproduce
------------------
Format-Hex should support all primitive types (including enums) and arrays of these types  - instead of this random assortment.

Take a look at the prototype https://gist.github.com/lzybkr/9940b63c8301c31316bdb3ec6305536f written by @lzybkr.

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
@SteveL-MSFT The enhancement was made. Can we close or there is anything that we should add?

**Comment by SteveL-MSFT** [comment]
@iSazonov it doesn't appear that the enhancements to `format-hex` addresses this issue.  Based on the gist sample, I think the expectation is that this will work:

```powershell
[System.Net.HttpStatusCode]::OK | format-hex
```

Which still fails.

**Comment by iSazonov** [comment]
I wonder why Maria did not use Jason code? Was there some discussion internally?

**Comment by SteveL-MSFT** [comment]
@iSazonov good question, @MiaRomero reports to a different manager, so I don't know what discussions took place or didn't

**Comment by MiaRomero** [comment]
@SteveL-MSFT and @iSazonov this was part of my internship project and unfortunately I didn't have time to implement what Jason had recommended.  I wasn't aware of his code until the PR ( #3320) was almost complete and then my internship was over :(

**Comment by SteveL-MSFT** [comment]
@MiaRomero no worries, we just didn't have the context!

**Comment by iSazonov** [comment]
Thanks for clarify. Will continue to look how to adopt the Jason's code.

**Comment by vexx32** [comment]
For anyone looking at this issue, I would also like to point out that the behaviour and handling of piped input is _weird_.

For example, if you pipe a series of bytes into it, I would expect a display like this:
```
           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   EF BB BF 74 65 73 74 0D 0A                       ï»¿test..
```

Instead, we get this:

```
           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   EF                                               ï


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   BB                                               »


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   BF                                               ¿


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   74                                               t


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   65                                               e


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   73                                               s


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   74                                               t


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   0D                                               .


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   0A                                               .
```
Which is a bit tricky to read! 😄

**Comment by vexx32** [comment]
If you read as string, then you miss the BOM, which may well be what you care about. 

Most cmdlets' handle a piped array and a directly input array the name. This cmdlets' currently does not. If you pass an array directly it works; the handling for piped input is simply at odds with the behaviour for most other cmdlets'.

**Comment by vexx32** [comment]
I think I address basically everything in #8596

Many thanks @lzybkr for that concept code that is _far_ cleverer than I could figure out myself without at least a week's work, and thanks @Francisco-Gamino for the link!

@SteveL-MSFT just because you brought that one up 😉 
![image](https://user-images.githubusercontent.com/32407840/50731769-cc027800-113a-11e9-8728-50aab0c7abe9.png)

If there are any improvements I can make further, let me know in the PR, I'll be happy to tackle it. 😄

**Comment by iSazonov** [comment]
@vexx32 There is #8191

**Comment by msftrncs** [comment]
@iSazonov, is the issue with piping arrays supposed to be fixed?  I just noticed it in 6.2, then found this old thread.

**Comment by msftrncs** [comment]
Samples:
```PowerShell
[byte[]](1,2,3,4,5,6,7,8,9,0) | format-hex
format-hex -inputobject ([byte[]](1,2,3,4,5,6,7,8,9,0))
```

**Comment by rkeithhill** [comment]
Also, it would be nice to have a switch param like `-Bare` or `-SuppressHeaders` so such `Format-Hex -Inp 65535 -SuppressHeaders` would output simply `0000FFFF`.  And for @msftrncs case:
```
[byte[]](1,2,3,4,5,6,7,8,9,10) | format-hex
```
the output would be vastly simplified to just:
```
00
01
...
09
0A
```

**Comment by vexx32** [comment]
@msftrncs I actually had the same gripe and submitted a PR to attempt to solve that issue more elegantly. See #8674  😄

**Comment by iSazonov** [comment]
@rkeithhill @vexx32 Please open new Issue for the suggestion.

**Comment by vexx32** [comment]
@iSazonov see #9403
