### ISSUE TITLE
 Set-Content/Append-Content does not create intermediate subdirectories, despite the help text.

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#3363]
Steps to reproduce
------------------
_Suppose the D:\tmp\foobarbeen path does not exist, but D:\ does._

Add-Content 'Foobar' -Path D:\tmp\foobarbeen\f.txt

Expected behavior
-----------------
D:\tmp\foobarbeen is created and populated with Foobar.

Actual behavior
---------------

Add-Content : Could not find a part of the path 'D:\tmp\foobarbeen\f.txt'.
At line:1 char:1
+ Add-Content 'Foobar' -Path D:\tmp\foobarbeen\f.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\tmp\foobarbeen\f.txt:String) [Add-Content], DirectoryNotFoundException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand
 

Environment data
----------------
                                                                                                                                                                 
PSVersion                      5.1.15155.1000                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.15155.1000                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
`Set-Content` has the same behavior:
```powershell
>Set-Content 'Foobar' -Path c:\temp\foobarbeen\f.txt

Set-Content : Could not find a part of the path 'C:\temp\foobarbeen\f.txt'.
At line:1 char:1
+ Set-Content 'Foobar' -Path c:\temp\foobarbeen\f.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\temp\foobarbeen\f.txt:String) [Set-Content], DirectoryNotFoundExcept
   ion
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand
```

**Comment by arkein** [comment]
The commands fail even with `-Force` parameter.

**Comment by orangerkater** [comment]
so, no fix for this …
