### ISSUE TITLE
$ForEach automatic variable does not work properly with value types enumerators

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#3368]
Steps to reproduce
------------------
```powershell
PS> $a = 1..10
PS> $b = [System.Collections.ArrayList]::new($a)
PS> $c = [System.Collections.Generic.List[Object]]::new($a)
PS> $a, $b, $c | ForEach-Object {
>>>     $_.GetType().FullName
>>>     foreach($i in $_) {
>>>         "$i, $($ForEach.MoveNext()), $($ForEach.Current), $($ForEach.MoveNext()), $($ForEach.Current)"
>>>     }
>>> }
System.Object[]
1, True, 2, True, 3
4, True, 5, True, 6
7, True, 8, True, 9
10, False, , False,
System.Collections.ArrayList
1, True, 2, True, 3
4, True, 5, True, 6
7, True, 8, True, 9
10, False, , False,
System.Collections.Generic.List`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
1, True, 1, True, 2
2, True, 3, True, 4
3, True, 5, True, 6
4, True, 7, True, 8
5, True, 9, True, 10
6, False, , False,
7, False, , False,
8, False, , False,
9, False, , False,
10, False, , False,
```

Expected behavior
-----------------
Interacting with `$ForEach` automatic variable should affect `foreach` loop.

Actual behavior
---------------
When enumerator implemented as value type, it seems that PowerShell copy enumerator by value, when assigning it to `$ForEach` automatic variable, and that disjoin it from enumerator, which PowerShell using internally for `foreach` loop.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSEdition                      Core
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.17-18-gedecf7e04d65f7183cd1d278daa5ebed2970813f
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0}
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
```

**Comment by powercode** [comment]
Does the same thing happen in the with the `$switch` variable in the switch statement?

**Comment by lzybkr** [comment]
`$switch` should have the same problem - they share the key part of the implementation [here](https://github.com/PowerShell/PowerShell/blob/30eb61e3b9b36130da051fb315201f208d9ee0a2/src/System.Management.Automation/engine/parser/Compiler.cs#L4107).

Mutable valuetypes are difficult to get right in PowerShell because everything tends to get boxed, and that is exactly what happens here. We can't know ahead of time what the type of the enumerator is, so code is generated using `IEnumerable`, which requires boxing.

**Comment by powercode** [comment]
@PetSerAl Nice catch by the way

**Comment by PetSerAl** [comment]
@powercode It is not actually my catch. I see the [problem](https://windowsserver.uservoice.com/forums/301869/suggestions/11113494) some time ago. And as it not fixed yet and I do not find same issue here, I decide to repost it here.

**Comment by PetSerAl** [comment]
@lzybkr IMHO, boxing is not a problem, but part of solution. If you pass boxed instance around as object or as interface, then all references would point to the same boxed instance. The problem is that PowerShell try to preserve copy by value semantic for value types in some cases (for example, assigning value to variable), but does not provide any option to opt-out from this behavior.
```powershell
PS> Add-Type -TypeDefinition 'public interface I { } public struct S : I { }'
PS> $S = [S]::new()
PS> $A = [Object[]]::new(1)
PS> $A[0] = $S
PS> [Object]::ReferenceEquals($A[0], $S)
True
PS> $B = [I[]]::new(1)
PS> $B[0] = $S
PS> [Object]::ReferenceEquals($B[0], $S)
True
PS> $C = $S
PS> [Object]::ReferenceEquals($C, $S)
False
```

**Comment by lzybkr** [comment]
If the value was boxed, we would unbox when calling a method. At runtime, we don't really pay attention to the fact that an object implements an interface, we just look for the appropriately named method in the class/struct, and correct code gen that way would require an unbox.

**Comment by PetSerAl** [comment]
@lzybkr I am confused now. How does enumerator advance then? I mean I call `$ForEach.MoveNext()` where `$ForEach` is boxed value type. Is it unbox `$ForEach` and call method on unboxed copy? But that should left `$ForEach` boxed copy unaffected.

**Comment by lzybkr** [comment]
I haven't looked closely to see exactly what's going on, but if we copied once to a strongly typed field/variable, but did not box, I think that would explain the behavior I see in the repro.

But I could easily be wrong here, my point was mostly to point out how boxing causes problems with mutable structs, it has been a problem in the past.

**Comment by powercode** [comment]
Something that came as a surprise to me it the difference in behavior between these two examples:
Should the parenthesis around the command have to be there?
Seems like a bug.
```
# unexpected repeated output
switch -Regex (cmd /c dir){
     '.*' {
        $_
        while ($switch.MoveNext()){  
            
            '--' + $switch.Current            
        }
     }
}

# second - expected result
switch -Regex ((cmd /c dir)){
     '.*' {
        $_
        while ($switch.MoveNext()){  
            
            '--' + $switch.Current            
        }
     }
}

```

**Comment by powercode** [comment]
Looking at this again, I think I understand what is going on.
In the first case, we get an value type enumerator, producing extra output, and in the latter case we get a ref type enumerator.
So the wrapping in `()` yields a collection while the first example iterates on the command output directly (on a value type enumerator)
