### ISSUE TITLE
clean-up existing tab completion tests, add more coverage

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3369]
Current tests are for specific bug fixes in `test/powershell/Host/TabCompletion/BugFix.Tests.ps1`

We should have proper `TabCompletion.Tests.ps1` that replaces this file with proper test titles.

**Comment by iSazonov** [comment]
I believe we should transform the file in _full completion test set_ - currently we don't cover the code by tests.

**Comment by SteveL-MSFT** [comment]
@daxian-dbw added a bunch of tests, consider this resolved.
