### ISSUE TITLE
Tab completion don't work for $error

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3373]
Steps to reproduce
------------------
```powershell
5/0
$error[0].<tab>
```
Expected behavior
-----------------
Tab completion substitutes property names (CategoryInfo, Exception ...)

Actual behavior
---------------
Tab completion don't work.

Environment data
----------------

All (Windows and Windows Core) PowerShell versions.

**Comment by SteveL-MSFT** [comment]
Workaround is:

```powershell
$global:error[0].<tab>
```

Did some debugging, command completion finds another variable named `Error` in a lower scope which is empty so nothing to tab complete.  Still investigating.

**Comment by SteveL-MSFT** [comment]
On master branch, tab completion appears to work.  @iSazonov I agree we should add some tests.

**Comment by vexx32** [comment]
Does this also resolve #7828, @SteveL-MSFT ?

**Comment by SteveL-MSFT** [comment]
@vexx32 no, that one isn't resolved
