### ISSUE TITLE
Revisit macOS crypto patching logic and install instructions

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#3374]
According to https://github.com/dotnet/corefx/pull/17011 dotnet core 2.0 doesn't have a dependency on openssl for macOS.
When we switch to 2.0, we should revisit
- [ ] crypto deps patching logic
- [ ] install instructions

**Comment by iSazonov** [comment]
Can we close the old Issue?

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
I don't think this is relevant anymore.  @iSazonov thanks for reviewing our old issues!  Much appreciated!
