### ISSUE TITLE
Uninstall-Module: add ability to uninstall dependent modules

### ISSUE THREAD

**Issue by dmilov** [PowerShell/PowerShell#3379]
The use-case is to upgrade multiple modules to their new version. When there is a module with number of dependent modules Install-Module allows installing all dependent modules at once. If I need to upgrade the modules to new version with no willing to have multiple versions of certain module I'd expect to be able to uninstall module with all dependent modules at ones using Uninstall-Module.

Here is an example

Module A with version 1.0
Module B with version 1.0, which is required module in the A module's manifest

This call:
Install-Module -Name A -RequiredVersion 1.0

installs both A and B

When new versions of the above modules are published

Module A with version 2.0
Module B with version 2.0

I'd like to be able to 

Uninstall-Module -Name A
Install-Module -Name A -RequiredVersion 2.0

and as a result to have installed only

A version 2.0
B version 2.0

**Comment by iSazonov** [comment]
We have related Issue #2505 "Reloading module does not reload submodules"
If we fix this we fix "upgrade multiple modules to their new version" too.

**Comment by joeyaiello** [comment]
This issue was moved to PowerShell/PowerShellGet#114

**Comment by joeyaiello** [comment]
FYI moved this to PowerShellGet as it'd have to implemented in that module rather than PowerShell itself.
