### ISSUE TITLE
Question: Digitally signing updatable help

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3381]
The ["step-by-step" documentation for updatable help](https://blogs.msdn.microsoft.com/powershell/2017/02/01/installing-latest-powershell-core-6-0-release-on-linux-just-got-easier/) indicates that it's a best practice to digitally sign your HelpInfo XML files. However, there aren't any specific directions, that I can find, that would indicate exactly how this is accomplished.

Are there any directions on how to digitally sign updatable help? Is this something that can be done cross-platform, or is it only possible on Windows?

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by iSazonov** [comment]
@SteveL-MSFT @sdwheeler My understanding is that it is about CAB files. Should we move the issue to PowerShell-Docs repo?

**Comment by SteveL-MSFT** [comment]
cc @adityapatwardhan

**Comment by ThomasNieto** [comment]
@SteveL-MSFT does MS sign any of their HelpInfo xml files or is it just the CAB files?

**Comment by ThomasNieto** [comment]
@sdwheeler do you know what the recommendation is for signing help files? Is it just the cab files or also including the helpinfo xml files?

**Comment by sdwheeler** [comment]
@ThomasNieto I don't know. I had the same question. We don't sign our help files. I expect that the individual files installed by `Update-Help` would need to be catalog-signed. That includes:
- the HelpInfo.xml file
- Module MAML file(s)
- any about_*help.txt files

I think if you added an authenticode signature to those files, it would break the help system.

**Comment by iSazonov** [comment]
The only reason we can think of and why it would be necessary to sign these files is to run examples from these files.

**Comment by ThomasNieto** [comment]
@sdwheeler I just tried using `Set-AuthenticodeSignature` on the maml help and helpinfo.xml and it failed. You can sign the help cab file. It doesn't look like you can catalog sign the files in the help cab either.

Can we get the docs updated to remove that recommendation to sign the help files?

```powershell
Status                 : UnknownError
StatusMessage          : The form specified for the subject is not one supported or known by the specified trust
                         provider.
```

**Comment by ThomasNieto** [comment]
@sdwheeler can this issue be closed since the documentation was updated?

**Comment by sdwheeler** [comment]
@ThomasNieto Yes, this can be closed.
