### ISSUE TITLE
Use -TestCases parameter in FormatHex.Tests.ps1

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#3382]
The test FormatHex.Tests.ps1 has helper functions and use foreach where the `-TestsCases` parameter to `It` could be used.

Fixing this would make it a little easier to read the test and be more consistent with other tests.

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/commit/ea77b5796682faac68d4ff6422a1e1ece012e29b#diff-3a1cbed60da65fb56198b42f1cece013
