### ISSUE TITLE
Format-Hex should have Count and Offset parameters

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell#3383]
Is there any chance we could add `Count` and `Offset` parameters? I could probably live without `Offset` but on the PSCX Format-Hex command, I use `-Count` almost all the time. That's because I use it to see if a text file has a BOM, in which case I only want to see the first 3 characters.

**Comment by adamdriscoll** [comment]
I have a working prototype of this and will put in a PR for it but will do so during my PoshSummit session as this is one of my examples\demos for our lab. So please don't fix until then. ;) 

![image](https://cloud.githubusercontent.com/assets/1256531/24482811/a73b44ae-14b9-11e7-86ea-3f1445467a44.png)

**Comment by lzybkr** [comment]
OK - no longer up for grabs.

**Comment by iSazonov** [comment]
Resumed this work.
