### ISSUE TITLE
demo script for remoting scenarios

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3385]
Need demo.ps1 script and corresponding markdown authored for beta1 scenarios, both SSH and WSMan remoting

**Comment by joeyaiello** [comment]
We need demos for:
- [ ] PSRP over SSH with the new parameter sets
- [ ] PSRP over WSMan from Linux w/ NTLM auth

**Comment by alexandair** [comment]
@SteveL-MSFT @joeyaiello Where can we find these demos?

**Comment by SteveL-MSFT** [comment]
@alexandair the SSH one is here: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ssh-remoting-in-powershell-core?view=powershell-6

I thought we had docs for enabling NTLM on Linux, but can't seem to find it.  @joeyaiello ?
