### ISSUE TITLE
Make isTranscribing internal bool accessible to the end user

### ISSUE THREAD

**Issue by vector-sec** [PowerShell/PowerShell#3388]
It would nice if https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostTranscript.cs#L27 were visible to the end user such that you could determine by checking the value of isTranscribing to see if the powershell session you are currently in is being transcribed.

**Comment by SteveL-MSFT** [comment]
@vector-sec can you give a use case where you would use this information?

@LeeHolmes is there any concern about exposing the state of transcription?

**Comment by iSazonov** [comment]
We can to reopen if we get a real business scenario.
