### ISSUE TITLE
Interactive remote session should support file transfer

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#3397]
Currently you can copy files over a PowerShell remote session via Copy-Item -ToSession/-FromSession, where you run Copy-Item on the client machine with an existing session variable:
```powershell
PS C:\> $session = New-PSSession -Cn <targetMachine>
PS C:\> Copy-Item -ToSession $session -Path C:\SetUp\* -Dest C:\SetUp
```
But it would be much nicer to be able to copy files from within an remote interactive session, similar to what you can do in Remote Desktop:
```powershell
PS C:\> Enter-PSSession -Cn <targetMachine> -ShareDrives @{ ClientCDrive = "C:\" }
[targetMachine]: PS C:\> cd C:\SetUp
[targetMachine]: PS C:\SetUp> Copy-Item -Path ClientCDrive:\SetUp\* -Dest .
[targetMachine]: PS C:\SetUp> dir
    SetUpHelper.psm1
    RunSetUp.ps1
    ...
[targetMachine]: PS C:\SetUp> .\RunSetUp.ps1
```
This would be a new feature and require an RFC to provide a detailed design.

**Comment by JaminShanti** [comment]
to lower your expectations, ssh doesn't have this either.  If you want to copy a file to/from you have to scp or sftp.

**Comment by mkarpuk** [comment]
It would be enough to just make PS Session available when connected to a remote interactive session.
```
PS C:\> Enter-PSSession targetmachine
[targetmachine]: PS C:\> $S = Get-PSSession
[targetMachine]: PS C:\> Copy-Item c:\test.txt c:\destfolder -ToSession $S
```
Unfortunately, Get-PSSession returns nothing (I tried -ComputerName parameter as well).

**Comment by JaminShanti** [comment]
I actually think pssession died when they added ssh to windows.  It will stay around but I doubt you will see new features.  Still waiting for a command line windows text editor which would help either way.

**Comment by PaulHigin** [comment]
We do still intend to continue PowerShell remoting over SSH (and legacy WinRM), even though SSH is now shipped with Windows, and so PSSession will remain for the foreseeable future.  But I still would like to see a file copy while within a PowerShell remoting session.  Maybe we can get some traction on this in the next sprint.

**Comment by JaminShanti** [comment]
Rather see you spend your time adding a command line text editor. I can add vim as it’s in git-SCM but if it’s a production box many times I can only use binaries included in the operating system to edit text.  So the need is there.

**Comment by mkarpuk** [comment]
@PaulHigin, thanks for the update.
@JaminShanti, I agree, that text editor is important, but it's a different story. Copy functionality is also important basic feature that is widely used during remote sessions. I think that my suggestion (expose PS session used by Enter-PSSession) could be implemented quite easy.
As for the text editor... There is a psedit option that works with PowerShell ISE and VSCode and provides experience similar to editing remote files. I know that it's not the same, but at least something that already works.

**Comment by JaminShanti** [comment]
Powershell ISE is a development application. It should not be on a production system.

**Comment by mkarpuk** [comment]
As far as I know, you don't need it on the server. When you type psedit <file>, PowerShell ISE downloads file locally and allows editing it. When changes are saved, it uploads file back to the server. This requires typing psedit from the PowerShell ISE (which is inconvenient), but workable. https://4sysops.com/archives/psedit-edit-files-remotely-with-powershell/

**Comment by JaminShanti** [comment]
Happy Thanksgiving!
