### ISSUE TITLE
Duplicate help items in PowerShell -- how does one disambiguate?

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3399]
Steps to reproduce
------------------

Run `Get-Help -Name about_Should`.

Expected behavior
-----------------

The help for `about_Should` appears.

Actual behavior
---------------

Two help items are returned, but not the actual contents of the help documents.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.17
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

![screen shot 2017-03-22 at 2 46 52 pm](https://cloud.githubusercontent.com/assets/466713/24222263/bfd96622-0f0e-11e7-8276-af4941223568.png)

Cheers,
Trevor Sullivan

**Comment by PetSerAl** [comment]
Content actually returned, just not displayed. You can use this:
```powershell
Get-Help -Name about_Should | % Clone
```
to display content.
