### ISSUE TITLE
Confusing `Get-Command -ArgumentList` behavior

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3402]
Not sure this is a bug, but the behavior is confusing.

Currently, the following two commands are equivalent:

```powershell
Get-Command -foo -bar -baz
```

```powershell
Get-Command -ArgumentList '-foo', '-bar', '-baz'
```

Apparently, any remaining unbound parameters are collected in `-ArgumentList`, and parameter set `CmdletSet` is selected.
No error is reported and lengthy output is produced - albeit fewer items than without any parameters.

* This behavior makes it easy to miss mistyped parameter names.

* Additionally, it's not clear what effect the `-ArgumentList` values are actually having.

Given that the purpose of `-ArgumentList`  is to pass arguments _through_ to the _target_ command(s) (in order to trigger inclusion of dynamic parameters in combination with `-Syntax`), shouldn't invalid arguments  cause _errors_?

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.17) on Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
```

**Comment by bielawb** [comment]
The purpose of ArgumentList is to pass positional arguments to a given command:
E.g. to see `-Concatenate` on `Set-Item` you would do this:
`Get-Command Set-Item -ArgumentList WSMan:\localhost\Client\TrustedHosts -Syntax`

Another example: to see all extra parameters for New-PSDrive in ActiveDirectory provider (PSProvider is a second positional parameter in this case) you would run:
`Get-Command -Syntax -Name New-PSDrive -ArgumentList foo, ActiveDirectory`

Help for that parameter is a bit confusing, mixing parameters and arguments... but the name is correct: you won't be able to pass parameters to it. In my opinion it's a documentation bug.

**Comment by mklement0** [comment]
@bielawb: 

Thanks for that important clarification. 

Generally, the term "arguments" in the help topics is _not_ limited to just _positional_ arguments; for instance, the description of `-ArgumentList` for [`Start-Process`](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.management/start-process) states (emphasis added):

> Specifies _parameters_ or _parameter values_ to use when this cmdlet starts the process.

I wonder what the reason for this restriction to _positional_ arguments is; arguably, to use your example, `Get-Command -Syntax -Name New-PSDrive -ArgumentList '-PSProvider', ActiveDirectory` is clearer, and, aside from the need to quote `-PSProvider`, simpler;  
given the current parsing, even `Get-Command -Syntax -Name New-PSDrive -PSProvider ActiveDirectory` would then work, although this syntax is problematic with respect to typos, as I've mentioned.

Also, _some_ cmdlets cause an error if you pass _too many_ positional arguments, whereas others don't; e.g.:

```powershell

# Breaks - too many positional arguments.
Get-Command -Syntax Get-Item -ArgumentList 1,2,3

# !! Doesn't break - even though there are too many pos. args.
Get-Command -Syntax Get-Date -ArgumentList 1,2,3

```

It doesn't even break if you define a function that explicitly forbids positional arguments:

```powershell
function foo { [cmdletbinding(positionalbinding=$false)]param($bar) }

# !! Doesn't break, even though no pos. args. are allowed.
Get-Command -Syntax foo -ArgumentList 1,2,3
```

**Comment by bielawb** [comment]
Generally, I would argue that `-Arguments` that would take a hash table would be much cleaner:
```powershell
Get-Command -Arguments @{ PSProvider = 'ActiveDirectory' } -Name New-PSDrive -Syntax
```
I believe errors are only possible if a command that has dynamic parameters (true for Get-Item, false for Get-Date and your foo).

Easy to reproduce with updated foo (empty `DynamicParam` block)

```powershell 
function foo { [cmdletbinding(positionalbinding=$false)]param($bar) DynamicParam {} }
# breaks....
Get-Command foo -Syntax -ArgumentList a
```

I guess it's only validated when there is a good reason to "give it a try" - nothing changes in syntax of "normal" command no matter how many positional parameters you pass, so value for that parameter seems to be ignored.

**Comment by mklement0** [comment]
Thanks again.

> I would argue that -Arguments that would take a hash table would be much cleaner:

Great idea.

**Comment by ThomasNieto** [comment]
The behavior seems to have changed since the original posting. The example command now produces an error.

```powershell
PS C:\> Get-Command -foo -bar -baz
Get-Command: The command could not be retrieved because the ArgumentList parameter can be specified only when retrieving a single cmdlet or script.
PS C:\> Get-Command -ArgumentList '-foo', '-bar', '-baz'
Get-Command: The command could not be retrieved because the ArgumentList parameter can be specified only when retrieving a single cmdlet or script.
```

I was trying to find a way to get `-Syntax` to return dynamic parameters however, the current design of `ArgumentList` only passes positional arguments and there is not a way to pass named parameters with values to the command.

I bet this behavior stems from PowerShell only using dynamic parameters for the provider cmdlets and those commands use `-Path` which is position 0 to call the specific provider `GetDynamicParameters()` method.

**Comment by ThomasNieto** [comment]
I don't know what changed since the original posting but there seems to be new behavior and it can now bind to named parameters.

```powershell
PS C:\> Get-Command -foo -bar -baz
Get-Command: The command could not be retrieved because the ArgumentList parameter can be specified only when retrieving a single cmdlet or script.
PS C:\> Get-Command -ArgumentList '-foo', '-bar', '-baz'
Get-Command: The command could not be retrieved because the ArgumentList parameter can be specified only when retrieving a single cmdlet or script.
```

You can now pass named parameters and have it work as expected, still the syntax is not intuitive.

```powershell
PS C:\> Get-Command -Syntax Set-Item -Path HKLM:\

Set-Item [-Path] <string[]> [[-Value] <Object>] [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-Type <RegistryValueKind>] [<CommonParameters>]

Set-Item [[-Value] <Object>] -LiteralPath <string[]> [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-Type <RegistryValueKind>] [<CommonParameters>]

PS C:\> Get-Command -Syntax Set-Item

Set-Item [-Path] <string[]> [[-Value] <Object>] [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [<CommonParameters>]

Set-Item [[-Value] <Object>] -LiteralPath <string[]> [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

You can also use a splat.

```powershell
PS C:\> $splat = @{ Path = 'HKLM:\' }
PS C:\> Get-Command -Syntax Set-Item @splat

Set-Item [-Path] <string[]> [[-Value] <Object>] [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-Type <RegistryValueKind>] [<CommonParameters>]

Set-Item [[-Value] <Object>] -LiteralPath <string[]> [-Force] [-PassThru] [-Filter <string>] [-Include <string[]>] [-Exclude <string[]>] [-Credential <pscredential>] [-WhatIf] [-Confirm] [-Type <RegistryValueKind>] [<CommonParameters>]
```
