### ISSUE TITLE
$myInvocation.OffSetInLine wrong?

### ISSUE THREAD

**Issue by rtestardi** [PowerShell/PowerShell#3413]
From: Richard Testardi 
Sent: Thursday, March 23, 2017 11:17 AM
To: PowerShell Discussions
Subject: $myInvocation.OffSetInLine wrong?

Hi,

I found an old blog post from Jeffrey Snover which seems to not work anymore:

- https://blogs.msdn.microsoft.com/powershell/2007/05/31/getting-all-your-parameters/

In his post, $myInvocation.OffSetInLine is the string offset of the start of the parameters.

But now it seems to be 1 more than the start of the command.

Jeffrey showed:

- PS>function test {$myinvocation.line.substring($myInvocation.OffSetInLine)}
- PS>write-host “PowerShell”;test -A Value -b Value2 -c Value3 this is a test
- PowerShell
- -A Value -b Value2 -c Value3 this is a test

But now I see (I added $myInvocation.OffSetInLine to the output for clarity):

- PS C:\temp> function test {$myInvocation.OffSetInLine; $myinvocation.line.substring($myInvocation.OffSetInLine)}
- PS C:\temp> write-host "PowerShell";test -A Value -b Value2 -c Value3 this is a test
- PowerShell
- 25
- est -A Value -b Value2 -c Value3 this is a test
- PS C:\temp> test -abc
- 1
- est -abc

Is this a bug, or can I count on it not changing?

(Actually, even if it is a bug, can I count on it not changing? :-)

Thanks.

-- Rich

  

Rich Testardi | Principal Software Development Engineer | Microsoft
1020 Enterprise Way, Sunnyvale, CA 94089 | 7th Floor
Direct: 303.546.1449 | Home (Boulder, CO): 303.443.4254

**Comment by iSazonov** [comment]
From [docs](https://msdn.microsoft.com/en-us/library/system.management.automation.invocationinfo.offsetinline(v=vs.85).aspx) OffsetInLine:
>Gets the offset (in characters) of the command location in the line.

So it is "By design".

**Comment by rtestardi** [comment]
It's off by one for the command.

Did you see that?

**Comment by iSazonov** [comment]
Yes, I see. 
I think the trick is that the documentation says "in characters" - so it is not C/C++ offset.
I agree that this is surprising.
I agree that we could recognize this as bug, but it will breaking change.

**Comment by rtestardi** [comment]
OK, so then (I would agree that) it should not change.

My fear was that it would get "fixed" at some random time and our scripts would break.

(I did manage to figure out a different way to do this, so as to not depend on that variable, I will admit.)

Thanks.

**Comment by rtestardi** [comment]
Perhaps someone could just tweak the documentation?


From: Rich Testardi
Sent: Friday, March 24, 2017 12:59 PM
To: 'PowerShell/PowerShell' <reply@reply.github.com>; PowerShell/PowerShell <PowerShell@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [PowerShell/PowerShell] $myInvocation.OffSetInLine wrong? (#3413)

OK, so then (I would agree that) it should not change.

My fear was that it would get "fixed" at some random time and our scripts would break.

(I did manage to figure out a different way to do this, so as to not depend on that variable, I will admit.)

Thanks.

**Comment by iSazonov** [comment]
@SteveL-MSFT Maybe @powershell-committee makes a conclusion: should we fix this?

**Comment by mopadden** [comment]
This is confusing! Shouldn't the offset for a command that starts at the beginning of the line be zero?

**Comment by joeyaiello** [comment]
@PowerShell/powershell-committee discussed this and agreed on a few points:

* This has been broken since 3.0, and changing it could potentially break a lot of people. While starting the offset at 0 might make more intuitive sense for most developers, there's no PowerShell design principle that absolutely dictates that it needs to, and the relative risk of the breaking change (again) is too great to justify. 
* In the long run, `$MyInvocation` either needs to be massively improved or replaced by something better
* We know that @rtestardi has already worked around the problem by not using `$MyInvocation` (yet another proof point for replacing it altogether)
* We should update Jeffrey's blog to mark it as "deprecated".

**Comment by rtestardi** [comment]
Thanks, all, it is nice to see this being taken care of and the committee process working well.

> We should update Jeffrey's blog to mark it as "deprecated".

This would be great, if it is possible.

This is how I pass bound parameters from a local invocation to a remote invocation now, which seems quite a bit cleaner anyway:

        Invoke-Command -Session $s -ScriptBlock { & $using:PSCOMMANDPATH @using:psboundparameters }

Which I think was the goal of that blog post anyway (I realize I didn't get unbound parameters here).

-- Rich (richardt@microsoft.com)

**Comment by joeyaiello** [comment]
Blog post has been updated
