### ISSUE TITLE
Equivalent of bash `set -e`

### ISSUE THREAD

**Issue by pauldambra** [PowerShell/PowerShell#3415]
I [asked this question on twitter](https://twitter.com/pauldambra/status/845274435707977728) and it was suggested I post here.

[Many](http://stackoverflow.com/a/13478622/222163) [people](https://github.com/azet/community_bash_style_guide#style-conventions) consider it good practice to start a bash script.

```
#! /bin/bash
set -eu
```

`set -e` tells the script to stop on first error
`set -u` tells the script to not allow undeclared variables

Although [not everyone agrees](http://mywiki.wooledge.org/BashFAQ/105)

I think `set -u` and `Set-StrictMode -Version 1.0` are equivalent.

I just wrote a set of Powershell scripts for managing an elasticsearch server. Then a few top-level scripts to tie them together. 

It would have been really useful to be able to write something equivalent to...

```
set -e

$someValue = .\server-task-1.ps1
.\server-task-2.ps1 -using $someValue
.\task-that-requires-everything-else-suceeded.ps1
```

... but I couldn't find how to and ended up with something more like...

```

$someValue = .\server-task-1.ps1
if ($LastExitCode -ne 0) {
    exit $LastExitCode 
}

.\server-task-2.ps1  -using $someValue
if ($LastExitCode -ne 0) {
    exit $LastExitCode 
}

.\task-that-requires-everything-else-suceeded.ps1
if ($LastExitCode -ne 0) {
    exit $LastExitCode 
}

```

Apologies if this is already possible and I've missed it...

**Comment by SteveL-MSFT** [comment]
`$erroractionpreference = "stop"` is similar to `set -e`, except it only works against cmdlets and not native commands

**Comment by pauldambra** [comment]
As someone fresh to Powershell that's a confusing distinction. 

So would $erroractionpreference = "stop" work for my example above..?

i.e.

```
$erroractionpreference = "stop"

$someValue = .\server-task-1.ps1

# does not run the next two commands if server-task-1.ps1 exits with code != 0
.\server-task-2.ps1 -using $someValue
.\task-that-requires-everything-else-suceeded.ps1
```

but

```
$erroractionpreference = "stop"

$someValue = .\server-task-1.exe

# does run the next two commands _even though_ server-task-1.exe exits with code != 0
.\server-task-2.ps1 -using $someValue
.\task-that-requires-everything-else-suceeded.ps1
```

**Comment by SteveL-MSFT** [comment]
`$erroractionpreference = "stop"` only works if `Write-Error` is called (such as an exception is raised).  It doesn't do any checks against $lastexitcode.  We can certainly look into adding another preference variable to throw an exception if $lastexitcode != 0.

**Comment by mopadden** [comment]
Would probably want to throw the exception only in a context where Powershell also sets $? to false as a result.
Throwing an exception in other situations where lastexitcode != 0 would not give a result equivalent to "set -e" in bash.

https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html

**Comment by mopadden** [comment]
Hi, i've done some work on this, can I ask for an assignment?

**Comment by SteveL-MSFT** [comment]
@mopadden consider it assigned, GitHub doesn't allow assigning to people without write access

**Comment by SteveL-MSFT** [comment]
Assigning to @daxian-dbw who's assigned to the PR so no one else duplicates this work

**Comment by SteveL-MSFT** [comment]
Anyone who's interested in this should review the RFC: https://github.com/PowerShell/PowerShell-RFC/pull/88/files

**Comment by choovick** [comment]
+1, very inconvenient to check $LastExitCode, especially when using PS for build scripts with multiple steps...

**Comment by b-rad15** [comment]
Since this is the first google result, linking the most recent thread on this RFC that I can find for anyone interested in implementing it https://github.com/PowerShell/PowerShell-RFC/pull/277

**Comment by daxian-dbw** [comment]
The PR that implements the RFC was already merged as an experimental feature: #15897
So, closing this issue.

**Comment by nhooyr** [comment]
Is the equivalent of `set -eu` then:

```
Set-StrictMode -Version Latest
\$ErrorActionPreference = "Stop"
Enable-ExperimentalFeature PSNativeCommandErrorActionPreference
\$PSNativeCommandUseErrorActionPreference = \$true
```

**Comment by LinAGKar** [comment]
It seems like `$ErrorActionPreference = "Stop"` makes it exit with 0 (success) on error, so it's not equivalent to `set -e` in that regard either.
