### ISSUE TITLE
Get-Help (linux, ubuntu)

### ISSUE THREAD

**Issue by ljgww** [PowerShell/PowerShell#3419]
Get-Help on Ubuntu 14.04
$ powershell --version
powershell v6.0.0-alpha.17

Steps to reproduce
------------------
PS /home/lj> Get-Help Find                                                          Searching Help for Find ...                                                     [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]                                                                                       Get-Help                                                                           Searching Help for Find ...                                                     [oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]      

Expected behaviour
-----------------
Full help text

Actual behaviour
---------------
Seems that text rendering has no LF just CR so text gets overwritten with the new text in the stream.
In essence Get-Help is not usable at the moment as help text do not render properly.

Environment data
----------------

PS /home/lj> $PSVersionTable                                                    

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-alpha                                     
PSEdition                      Core                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   3.0.0.0                                         
GitCommitId                    v6.0.0-alpha.17                                 
CLRVersion                                                                     
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
I think this is a side effect of a broken progressbar (which was fixed https://github.com/PowerShell/PowerShell/pull/3362).  if you set `$progresspreference='silentlycontinue'` it renders correctly.

**Comment by SteveL-MSFT** [comment]
This was not fixed with #3362 and something specific to formatting.  Investigating.

**Comment by averyfreeman** [comment]
I can confirm that setting $progresspreference='silentlycontinue' appears to fix this problem in Debian Stretch

**Comment by ljgww** [comment]
Thank you!

I got that this was honest mistake on my part, as later I figured out that as usual 'it is not what you are thinking you are saying but what you are actually saying'.

        Get-Help Find 

is actually searching for non existent Find (cmdlet or other object) which I would expect to be something existent, or hoped to find 'finding' commands in search engine way. All other Get-Help actually (existing cmdlets help) renders well on Linux.
I did not expect to hit something deeper than that but as I see from the latter discussion it actually uncovered something deeper and as well something for me to learn about PS.

behaviour is the same for all unknown strings

tried: $progresspreference='silentlycontinue'

it works like charm even for Find.

        > Get-Help Find                                            

        Name                              Category  Module                    Synopsis 
        ----                              --------  ------                    -------- 
        Find-Command                      Function  PowerShellGet             ...      
        Find-DscResource                  Function  PowerShellGet             ...      
        Find-Script                       Function  PowerShellGet             ...      
        Find-Module                       Function  PowerShellGet             ...      
        Find-RoleCapability               Function  PowerShellGet             ...      
        Find-PackageProvider              Cmdlet    PackageManagement         Find-P...
        Find-Package                      Cmdlet    PackageManagement         Find-P...

**Comment by ljgww** [comment]
> Get-Help mela                                            
        Get-Help : Get-Help could not find mela in a help file in this session. To 
        download updated help topics type: "Update-Help". To get help online, search 
        for the help topic in the TechNet library at 
        https://go.microsoft.com/fwlink/?LinkID=107116.
        At line:1 char:1
        + Get-Help mela
        + ~~~~~~~~~~~~~
            + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoun 
           dException
            + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHe 
           lpCommand

'mela' is not matching anything. Error makes sense.

**Comment by SteveL-MSFT** [comment]
@ljgww Get-Help tries to be smart.  It searches for exact match, and if not found, tries to match the title, and if not found, tries matching content before giving up.  If one match is found, it displays it, otherwise shows a list of potential topics.
