### ISSUE TITLE
Question: Where to find the schema file for ETS ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#3422]
On this web [page](https://msdn.microsoft.com/en-us/library/ms714674(v=vs.85).aspx) (_Extended Type System (ETS)_) the quoted links are broken :

> For more information about ETS and how Windows PowerShell uses objects, see Windows PowerShell Object Concepts [ps] and Windows PowerShell Extended Type System (ETS) [ps]. 

And this web [page](https://msdn.microsoft.com/en-us/library/dd878306(v=vs.85).aspx) is incomplete.

No details on the _IsHidden_ attribut  : 
```xml 
   <ScriptProperty IsHidden='true'>
```
No example on :
```xml
   <TypeConverter>
```
Or about the specific name '_PropertySerializationSet_' into a propertySet :
```xml
          <PropertySet>
            <Name>PropertySerializationSet</Name>
            <ReferencedProperties>
             ...
```

**Comment by joeyaiello** [comment]
This issue was moved to PowerShell/PowerShell-Docs#1208
