### ISSUE TITLE
PathIntrinsics.ParseParent throw AssertException in debug build when root is null

### ISSUE THREAD

**Issue by PetSerAl** [PowerShell/PowerShell#3423]
Steps to reproduce
------------------
```powershell
$ExecutionContext.SessionState.Path.ParseParent('a\b', [NullString]::Value)
```

Expected behavior
-----------------
Return `a`

Actual behavior
---------------
`AssertException`: ASSERT: Caller should validate root before calling this method

Environment data
----------------
```powershell
> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0}
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.17-42-g51e66b2244aa0394e77ed7b81ea3cd51f450bfad
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
```

Info
----------------
I see no place in call chain from [`ParseParent`](https://github.com/PowerShell/PowerShell/blob/master@%7B2017-03-25%7D/src/System.Management.Automation/engine/PathInterfaces.cs#L1125) to the [assertion](https://github.com/PowerShell/PowerShell/blob/master@%7B2017-03-25%7D/src/System.Management.Automation/engine/SessionStateNavigation.cs#L378-L380) where `root` argument actually validated. Help for methods does not say that `null` is invalid value for `root`. And it actually work in release build. So, it is looks like not valid assertion.

**Comment by iSazonov** [comment]
I cannot repo on Windows.

**Comment by PetSerAl** [comment]
Looks like this [commit](https://github.com/PowerShell/PowerShell/commit/54fa658e317244b04f87d1501c26b91a40b0b342) is the first where assertions are included in debug build and cause the issue.

**Comment by iSazonov** [comment]
Sorry, I tested in release.
