### ISSUE TITLE
Add support for SLES 12

### ISSUE THREAD

**Issue by TheFlyingCorpse** [PowerShell/PowerShell#3427]
Please add support for SLES 12, the Microsoft friendly Linux distribution.

I have added a ticket with [dotnet-cli](https://github.com/dotnet/cli/issues/6152) to get support for SLES 12, this ticket is for PowerShell once that is underway.

/cc @TravisEz13

**Comment by TravisEz13** [comment]
Thanks, @TheFlyingCorpse. Some people have suggested that the package for OpenSUSE 42.2 should work for SLES 12.  This solution is not quite the same thing as support, but I'll try to update this issue if we get unblocked on 42.2

**Comment by iSazonov** [comment]
I see 
- SLES 12 SP3 EOL - 31 Oct 2027
- SLES 15 EOL - 31 Jul 2031

**Comment by iSazonov** [comment]
@TravisEz13 What is the old issue status? Should we do anything before 7.0 release?

**Comment by TravisEz13** [comment]
Our policy on SLES is that we test on the equivalent of CentOS.  We don’t test on SLES due to licensing issues.
