### ISSUE TITLE
Write RFC for SemanticVersion work

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3438]
@SteveL-MSFT, @HemantMahawar, and I agree that the semantic versioning work (#2983) will very likely not get done in `6.0.0-beta1`, but we should do our best to have an RFC out by `beta1` timeframe, so that we can have a strong implementation in `beta2`.

**Comment by SteveL-MSFT** [comment]
@HemantMahawar can you author this?
