### ISSUE TITLE
Suspicious StringBuilder using

### ISSUE THREAD

**Issue by AppChecker** [PowerShell/PowerShell#3457]
Hi.
Please look this code fragment:
1) https://github.com/PowerShell/PowerShell/blob/4d0e21f6d2fa8280fb69e858b2f4b61bc52841f8/src/System.Management.Automation/engine/InitialSessionState.cs#L3940
```
 var allErrors = new StringBuilder('\n');

```

StringBuilder constructor with a char argument constructs a string with no characters in it ( this argument  specified  initial capacity) .

You may see example - http://ideone.com/1pPHlZ
I hope this may help you

These possible defects found with [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by iSazonov** [comment]
@AppChecker Thanks for your report!

I cannot repo the bug:
```powershell
using namespace System.Text
$sb = New-Object StringBuilder('[')
$sb.Append('a')
$sb.Append(' ')
$sb.Append('b')
$sb.Append(']')
$sb.ToString()

[a b]
```

**Comment by iSazonov** [comment]
@SteveL-MSFT The init post contains link on site (https: //cnpo.ru) with invalid certificate. Should we remove the link?

**Comment by AppChecker** [comment]
@iSazonov  Hi! Creating StringBuilder with char argument is work for powershell script, but not work for C#-code: http://ideone.com/1pPHlZ
P.S. I've updated link with valid certificate

**Comment by SteveL-MSFT** [comment]
@AppChecker thanks for the bug report, I was able to repro:

```powershell
PS C:\Users\slee\repos\PowerShell> Add-Type @"
>> using System.Text;
>> public class Test
>> {
>>   public static string Foo()
>>   {
>>     StringBuilder sb = new StringBuilder('[');
>>     sb.Append('a');
>>     sb.Append(' ');
>>     sb.Append('b');
>>     sb.Append(']');
>>     return sb.ToString();
>>   }
>> }
>> "@
PS C:\Users\slee\repos\PowerShell> [Test]::Foo()
a b]
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Sorry, I lost my post about that  I was able to repro too and pushed fix.
