### ISSUE TITLE
Suggestion: Provide a type accelerator for [System.Management.Automation.SemanticVersion]

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3460]
Now that [semantic version numbers](http://semver.org/) (semver) are becoming ubiquitous, it would be nice to be able to do something like

```powershell
$ [semver] '1.2.3-preview-02+build42'

Major Minor Patch Label         
----- ----- ----- -----         
    1     2     3 preview-02+build42

```

instead of what you currently need to do:

```powershell
$ [System.Management.Automation.SemanticVersion] '1.2.3-preview-02+build42'
```

**Comment by oising** [comment]
Ok, this looks mindlessly simple. Can I take this?

**Comment by mklement0** [comment]
@oising: I can't speak for the team, but I think it's fine to just go ahead, now that you've announced your intent. Thanks for taking it on.

**Comment by SteveL-MSFT** [comment]
@oising consider it yours!  I can only assign to formal team members so don't worry about that

**Comment by oising** [comment]
Just a quick update - I got busy, and then got lost trying to get everything to build in VS2017 - but I'm back on track.

**Comment by oising** [comment]
I don't see anything wrong with allowing [semver] in constrained language mode, so I'm permitting it there. If there's anything outlandish about this, bring it up in the PR review I guess.

**Comment by iSazonov** [comment]
@oising Can we close the Issue as fxed?

**Comment by oising** [comment]
Yes :) My first (and hopefully not last) PR.

**Comment by iSazonov** [comment]
@oising Good start!
