### ISSUE TITLE
Update docker files and replace `MAINTAINER` tag with `LABEL maintainer`

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#3465]
There is additional issue, is what email should we use on this tag
This was brought up in #3462

**Comment by SteveL-MSFT** [comment]
`powershellteam@hotmail.com` is a valid email address, although I'm not sure if anyone really monitors it (I certainly don't).  Having an individual's email who isn't actively maintaining the image seems incorrect.
