### ISSUE TITLE
Configuring the WinRM client requires the WinRM server service.

### ISSUE THREAD

**Issue by skyguy94** [PowerShell/PowerShell#3468]
The barrier to entry for configuring WinRM is very high for unfamiliar users and I don't think it needs to be that way. Its unclear to me why the WinRM service needs to be started on the client computer in order to configure client settings like trusted hosts. I'm convincing more of our developers to use pssessions/write remote scripts for managing remote instances instead of RDPing into them just to open a powershell window.

For someone new to ps-remoting and possible powershell, I have to get them to update their execution policy, with something like:
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine` 

Like most devs, they'll google it while we are talking about it just to familiarize themselves. That goes pretty well usually as execution policies make sense.

Then I want them to enable PS remoting, so we:
```
Enable-PSRemoting -Force
Set-Item WSMAN:\localhost\Client\TrustedHosts -value *
```
Since its a dev machine, '*' is a reasonable default. The problem is that `Enable-PSRemoting -Force` werids them out a bit, especially if you forget the `-Force` flag. You'll get a prompt like:

```
Start WinRM Service
WinRM service is not started currently. Running this command will start the WinRM service.

Do you want to continue?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
```

Which is a bit disconcerting as they wonder why they are starting a service. A quick bing search yeilds the msdn docs, which state:

![image](https://cloud.githubusercontent.com/assets/181450/24557586/d1b27e42-15fd-11e7-9aa2-46efa185f23d.png)

And at that point there's some pushback. I don't want people remoting into my box! What about security? etc.... 

So, why do I need the winrm service to set a client setting. Why can't I just configure my client without it?

It gets even more difficult if we run into public/private adapter issues. Again, that can be explained away, but its not clear to me why I need to deal with this to set a client setting.

**Comment by SteveL-MSFT** [comment]
WinRM configuration (including client) is actually a WSMan invocation to a configuration plugin, so it has to go through the WinRM service.  If you really want this addressed, you'll have to open an issue on [UserVoice](https://windowsserver.uservoice.com/forums/295047-general-feedback) as it's not something we can change in PowerShell.

Alternatively, my recommendation is to use PowerShell remoting over SSH which doesn't have this problem, although it does require you to install [OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/releases) onto Windows machines

**Comment by skyguy94** [comment]
Thanks for the response. We're definately interested in OpenSSH on our boxes, but that'll take some time to get migrated over to. I'll open a uservoice issue and see what comes of that.

**Comment by skyguy94** [comment]
https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/18814972-configure-the-winrm-client-without-starting-the-wi
