### ISSUE TITLE
Invoke-Command doesn't always return result

### ISSUE THREAD

**Issue by crazywalterke** [PowerShell/PowerShell#3472]
Steps to reproduce
------------------
New-Pssession -hostname linuxmachine -username user
new-pssession -hostname windowsmachine -username user
$sessions=get-pssession
invoke-command -session $sessions -scriptblock {
get-module -all
}

Expected behavior
-----------------
get list of all modules on both machines

Actual behavior
---------------
no return at all

Environment data
----------------
[win10]: PS C:\Users\user\Documents> $PSVersionTable

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
CLRVersion
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.17
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

[ubuntu 16.04.2]: PS /home/user> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.17
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```powershell
> $PSVersionTable

```

**Comment by PetSerAl** [comment]
@crazywalterke `get-module -all` will return only already loaded modules (wild guess: you mix `-All` with `-ListAvailable`). You just create new PowerShell remote sessions (with default configuration, remote sessions do not load any PowerShell profile) and asking which modules already loaded in them. IMHO, empty result is vary reasonable expected response.

**Comment by crazywalterke** [comment]
I suppose I made a mistake, but what is the diffrence then if I:

- invoke get-module -all to both sessions
- invoke get-module after (with the same sessions stil opened) enter-pssession and running get-module -all

**Comment by PetSerAl** [comment]
@crazywalterke Looks like `Enter-PSSession` run some commands in remote PowerShell session before enter into it. And that cause some module to be automatically loaded into remote session:
```powershell
$s = New-PSSession ...
Invoke-Command $s { $PSModuleAutoLoadingPreference = 'None' }
Enter-PSSession $s
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Please review milestone.

**Comment by SteveL-MSFT** [comment]
@iSazonov if the issue is closed, I haven't been removing/changing the milestone
