### ISSUE TITLE
Document prerequisites for install on Windows 7

### ISSUE THREAD

**Issue by stknohg** [PowerShell/PowerShell#3473]
Steps to reproduce
------------------
Install PowerShell 6.0(Alpha17) on Windows 7(not SP1) and start powershell.exe.

Expected behavior
-----------------
Powershell is started?

Actual behavior
---------------
Failed to start.

----
I failed to install PowerShell 6.0(Alpha17) on Windows 7(not SP1) and find 2 prerequisites.

## 1. SP1 and Visual C++ Redistributable for VS2015

PowerShell 6.0 on Windows 7 requires`Visual C++ Redistributable for VS2015` same as Windows 8.1 / Windows 2012R2, and `Visual C++ Redistributable for VS2015` reuires Windows 7 SP1.

Without `Visual C++ Redistributable for VS2015`, I failed to start powershell.exe with following message(Japanese).

> コンピューターに api-ms-win-crt-runtime-l1-1-0.dll がないため プログラムを開始できません。 この問題を解決するには、プログラムを再インストールしてみてください。

![lack of Visual C++ Redistributable for VS2015](https://cloud.githubusercontent.com/assets/720127/24578839/62f294a6-1724-11e7-973e-c5ae60f4f845.png)

## 2. KB2533623

[KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remote-code-execution) is [.NET Core prerequisites](https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites) for Windows 7.

Even after installing SP1 and Visual C++ Redistributable for VS2015,  without `KB2533623`, I failed to start powershell.exe with following message.

> Failed to load the dll from [C:\Program Files\PowerShell\6.0.0.17\hostfxr.dll],  
> HRESULT: 0x80070057 The library hostfxr.dll was found, but loading it from C:\Program Files\PowerShell\6.0.0.17\hostfxr.dll failed

![lack of KB2533623](https://cloud.githubusercontent.com/assets/720127/24578844/802481ce-1724-11e7-8bb6-9cb8527b5d59.png)

I think we should update documents.

**Comment by iSazonov** [comment]
From https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet
> Support for Windows 7 RTM without service packs ended on April 9, 2013

@SteveL-MSFT Author ask to update docs. Maybe `Area-Documents` is more suitable?

**Comment by mirichmo** [comment]
Did you install the [Universal C Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=50410)?

It ships downlevel to Win 7 and can be installed via Windows Update.

**Comment by stknohg** [comment]
@mirichmo No. I installed [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-US/download/details.aspx?id=48145).  
Which is appropriate?

**Comment by stknohg** [comment]
I installed the [Universal C Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=50410), and got same result.  
PowerShell 6.0 on Windows 7 requires
* SP1
* KB3118401 (Universal C Runtime)
* KB2533623  

Of course, it is best to apply the latest patch with Windows update.

**Comment by daxian-dbw** [comment]
Closed via #3495
