### ISSUE TITLE
Special characters are not displayed correct in interactive console

### ISSUE THREAD

**Issue by Platzer** [PowerShell/PowerShell#3486]
Steps to reproduce
------------------
Run `ping` on german windows 7 machine in powershell interactive console.

Expected behavior
-----------------
![grafik](https://cloud.githubusercontent.com/assets/3358663/24692178/fce471d2-19d7-11e7-8df2-685244fcd84d.png)
Run in VS Code with powershell in terminal.

Actual behavior
---------------
![grafik](https://cloud.githubusercontent.com/assets/3358663/24692200/1c70fe62-19d8-11e7-8e2f-7cfcdd490d7d.png)
Run in VS Code with powershell interactive console.

Environment data
----------------

## VS Code:
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:02:52.799Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

## Env:
Windows 7

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10514.6
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10514.6
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by iSazonov** [comment]
@Platzer Thanks for your report!

Could you please test in PowerShell console running without VS Code? Also please test with latest release PowerShell Core 6 **alfa 17**.

**Comment by Platzer** [comment]
@iSazonov I'm sorry i posted the issue to the wrong project!
New issue: https://github.com/PowerShell/vscode-powershell/issues/684
