### ISSUE TITLE
Need a full set of encoding tests

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3488]
Now we don't have a full set of encoding tests (only for [redirections](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Language/Parser/RedirectionOperator.Tests.ps1)). We need to create them during future [Encoding RFC](https://github.com/PowerShell/PowerShell-RFC/issues/71) implementation (?).

In #3467 (discussion Issue #3248) we fix Default/OEM encoding behavior PowerShell Core on Windows (as in Windows PowerShell) but don't add tests (waiting the RFC). The simplest test (from @mklement0) is:
```PowerShell
# Setup:
# Create a no-BOM UTF-8 file with the following literal content:
#   'ö' 
# which, when executed as a PS script, should echo 'ö' back, IF the script
# was correctly decoded from UTF-8 by PS.
# UTF-8 bytes: 0x27 (single quote), 0xc3 0xb6 (encoding of 'ö', U+00F6), 0x27 (single quote)
[byte[]] (0x27, 0xc3, 0xb6, 0x27) | Set-Content -Encoding Byte /tmp/$PID.ps1

# Test: See if the 'ö' is echoed back correctly.
#       Should return $True
'ö' -eq (& /tmp/$PID.ps1)
```

We need test for:
- [ ] File provider cmdlets
- [ ] Utility (and other) cmdlets
- [ ] Redirections
- [ ] Console Host
- [ ] Web cmdlets (Discussion Issue #3267)
- [ ] PowerShell engine source file reading

**Comment by mklement0** [comment]
@iSazonov: 

The test snippet tests how _PowerShell itself_ reads source code that has no BOM, so can you please add that as a separate action item (check box) to the list of tests?
(Perhaps that behavior is implied by the other tests, but I think it should still be a separate one.)

(And, on a more quibbly note: Can you add the word "character" before "encoding" to the title, so that it's clear what kind of encoding is being referred to?)

And here are the `Set-Content` / `Get-Content` test snippets with BOM-less UTF-8 encoding in effect:

```PowerShell
# Setup: *create* a  BOM-less UTF-8 file.
'ö' | set-content -nonewline /tmp/$pid.txt

# Tests: Both should output $True

# Compare the raw bytes of the new file to the UTF-8 encoding of 'ö' (0xc3 0xb6)
# With the current alpha17, this would return $False, because Set-Content creates an
# ISO-8859-1 file.
$null -eq (Compare-Object (Get-Content -Encoding Byte -Raw /tmp/$pid.txt) (0xc3, 0xb6))

# See if the BOM-less UTF-8 file is *read* correctly.
'ö' -eq (Get-Content -Raw /tmp/$pid.txt)
```

**Comment by iSazonov** [comment]
We have never used "character" before so it can confuse us even more. (?)

**Comment by mklement0** [comment]
@iSazonov: 

Not that it will matter much in this instance, but just for the record and for future instances where the distinction may matter:

We are discussing [character encodings](https://en.wikipedia.org/wiki/Character_encoding) here.

[Encoding](https://en.wikipedia.org/wiki/Code) is a far more generic term, of which _character_ encoding is just one instance.

Given that the issues in this repo span all sorts of topics, giving sufficient context is preferable.

**Comment by iSazonov** [comment]
@mklement0 In the code we use "encoding". So let us defer the question to the discretion of the mantainers.

**Comment by mklement0** [comment]
@iSazonov: 

Sounds good.

It's perfectly understandable to shorten "character encoding" to "encoding" in a given, narrow context, where there's no risk of ambiguity.

My only point is that in a larger context the added specificity can be helpful - both for searching topics by keywords and for quick comprehension.
