### ISSUE TITLE
Export-Clixml loses NoteProperties in nested hashtables

### ISSUE THREAD

**Issue by wisemoth** [PowerShell/PowerShell#3489]
Steps to reproduce
------------------
```
$d=@{'a'="A";'b'="B"}
$d | add-member -MemberType NoteProperty -name np -value NP
$d.hash=@{}
$d.hash.e='E'
$d.hash | add-member -MemberType NoteProperty -name np2 -value NP2
$d

> $d

Name                           Value
----                           -----
a                              A
hash                           {e}
b                              B

> $d|gm -membertype NoteProperty
   TypeName: System.Collections.Hashtable

Name MemberType   Definition
---- ----------   ----------
np   NoteProperty string np=NP

$d.hash|gm
> $d.hash|gm -membertype NoteProperty
   TypeName: System.Collections.Hashtable

Name MemberType   Definition
---- ----------   ----------
np2  NoteProperty string np2=NP2
```
Now export at the top level hashtable:
```
$d | Export-Clixml C:\tmp\exported
```
And import back into a new object, which should be the same as `$d`
```
$dd = Import-Clixml C:\tmp\exported
$dd
> $dd|gm -MemberType NoteProperty
   TypeName: Deserialized.System.Collections.Hashtable

Name MemberType   Definition
---- ----------   ----------
np   NoteProperty string np=NP

> $dd.hash

Name                           Value
----                           -----
e                              E
```
The top-level noteproperty survived the roundtrip; the noteproperty in the nested table did not:
```
> ($dd.hash|gm -MemberType NoteProperty) -eq $null
True
```
Expected behavior
-----------------
It would be strange semantics for a NoteProperty to sometimes survive round-tripping.  I'm aware that some membertypes (eg `ScriptProperty`) are not serialised at all (though that would be nice to have too); but having the top-level `NoteProperty` be correctly serialized and the second-level not is probably a bug.
```
PS C:\dev\PowerShell\src\Microsoft.PowerShell.Commands.Utility> $d.np -eq $dd.np
True
PS C:\dev\PowerShell\src\Microsoft.PowerShell.Commands.Utility> $d.hash.np2 -eq $dd.hash.np2
True #but currently it's false
```
Actual behavior
---------------
The nested `NoteProperty` to also be in `$dd`:
```
PS C:\dev\PowerShell\src\Microsoft.PowerShell.Commands.Utility> $d.np -eq $dd.np
True
PS C:\dev\PowerShell\src\Microsoft.PowerShell.Commands.Utility> $d.hash.np2 -eq $dd.hash.np2
False
```

Environment data
----------------

```
> $psversiontable

Name                           Value
----                           -----
CLRVersion
PSEdition                      Core
WSManStackVersion              3.0
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.17-69-g3be547c78e9878865445ca8e9108e914f029b80d
BuildVersion                   3.0.0.0
SerializationVersion           1.1.0.1
```

**Comment by PetSerAl** [comment]
`Export-Clixml` does not include extended properties, when object is not wrapped into `PSObject`.
```powershell
PS> $hash = @{ a=1 }
PS> Add-Member -InputObject $hash -NotePropertyName b -NotePropertyValue 2
PS> $array = $hash, [PSObject]$hash
PS> [System.Management.Automation.PSSerializer]::Serialize($array)
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <Obj RefId="0">
    <TN RefId="0">
      <T>System.Object[]</T>
      <T>System.Array</T>
      <T>System.Object</T>
    </TN>
    <LST>
      <Obj RefId="1">
        <TN RefId="1">
          <T>System.Collections.Hashtable</T>
          <T>System.Object</T>
        </TN>
        <DCT>
          <En>
            <S N="Key">a</S>
            <I32 N="Value">1</I32>
          </En>
        </DCT>
      </Obj>
      <Obj RefId="2">
        <TNRef RefId="1" />
        <DCT>
          <En>
            <S N="Key">a</S>
            <I32 N="Value">1</I32>
          </En>
        </DCT>
        <MS>
          <I32 N="b">2</I32>
        </MS>
      </Obj>
    </LST>
  </Obj>
</Objs>
```

**Comment by wisemoth** [comment]
Thanks @PetSerAl .

However I'm not sure this can be an intended: the `noteproperty` of the top-level hashtable is stored.  The `noteproperty` of the nested hashtable is not stored.  That doesn't seem right.  As a client I've just go two hashtables with noteproperties.  No casting to `[psobject]` for either; but the behavior is different.  The behavior is not described in the `-detail`ed help either., nor is there any `verbose` or `warning` stream output telling me that information-loss has occurred.

I really think that exporting noteproperties is surely what callers would expect.  If I get a complex-ly nested hashtable object out of a third-party module which I want to store, I'd export `export-clixml` / `import-clixml` to allow me to store that object with very high fidelity.

**Comment by PetSerAl** [comment]
>No casting to [psobject] for either; but the behavior is different.

`InputObject` parameter of `Export-Clixml` cmdlet is types as `PSObject`:
```powershell
(Get-Command Export-Clixml).Parameters.InputObject.ParameterType
```
So there is implicit cast for top level object to `PSObject`.

**Comment by wisemoth** [comment]
But the *intent* surely of the implementer at the time was not to have such awkward lossy semantics? I think you are highlighting how the code is - rather than how it was intended or should be.

**Comment by doctordns** [comment]
Is this still an issue worth looking at? 

I have seen no real need for this in the community - but I may have missed something! :-)

**Comment by wisemoth** [comment]
> I have seen no real need for this in the community 

There is a need which is why I raised the issue.

The documentation for `export-clixml` does not suggest the lossiness implied by this issue.  As soon as you embed an object with `NoteProperty` members into some other object, the former will be serialized with lossiness.  This would cause rather difficult to find issues.

Unless we want everyone to encode their own non-lossy encoders, `export-clixml` itself should perform non-lossy serialization (which is likely what people believe it *does* do at present).

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this.  Based on @SeeminglyScience's observation, this appears to be a bug that has existed for sometime.  We would be ok with an `ExperimentalFeature` that fixes this bug, however, we would want to verify what happens if you export from PS7 (with the change) and then try to import on WinPS (or older PS7).

**Comment by SeeminglyScience** [comment]
For a fix I'd probably look at changing this code:

https://github.com/PowerShell/PowerShell/blob/5b6407741cd2b85409538c1b99e858846a1259e7/src/System.Management.Automation/engine/serialization.cs#L1263-L1266

to use `PSObject.HasInstanceMembers(object, out PSMemberInfoInternalCollection<PSMemberInfo>)`, or just always wrap with `PSObject.AsPSObject(object)`

As a work around, you can explicitly wrap objects you want to retain ETS members for. In the repro steps if you add this before the export, it'll retain them:

```powershell
$d.hash = [psobject]$d.hash
```
