### ISSUE TITLE
Add suspicious obfuscated scripts to PowerShell automatic ScriptBlock logging

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#3490]
PowerShell currently automatically logs ScriptBlocks that are suspicious.  @LeeHolmes has done statistical analysis on known obfuscated malicious scripts and has created an algorithm that does a good job detecting these.  We should incorporate this algorithm in PowerShell so that these suspicious ScriptBlocks are also automatically logged.

**Comment by mafrahim** [comment]
Hi @PaulHigin, where do i find the current automated Scriptblocks logging in the repo here? I have read Lee Holmes article about frequency analysis and would like to maybe implement it here.

Thanks.

**Comment by iSazonov** [comment]
@SteveL-MSFT @PaulHigin Is any plans to implement this in 7.0 release?

**Comment by SteveL-MSFT** [comment]
This is not currently in plan for 7
