### ISSUE TITLE
Powershell issue in VS 2015

### ISSUE THREAD

**Issue by ssuhas76** [PowerShell/PowerShell#3493]
I am using VS 2015 and trying to install few packages via Nuget. I keep getting the below error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to initialize the PowerShell host. If your PowerShell execution policy setting is set to AllSigned, open the Package Manager Console to initialize the host first.			0	

It's not only coming up during package installation but i am getting the error when i try to ald a project.

Please help

**Comment by MaximoTrinidad** [comment]
Hi @ssuhas76, 

Please provide some more information:
1. What's the OS?  What build?
2. Desktop or Server?
3. Which version of PowerShell? Use $PSVersionTable

By the way, this site handles only PowerShell v6.0.0-alpha.xx. And/or anything that's PowerShell Core module related.

For Windows PowerShell (Version: 3, 4, and 5.x) all other non-Core module related issues, you better use the following UserVoice link:
https://windowsserver.uservoice.com/forums/301869-powershell 

This way the issues will be routed to the proper group.

:)

**Comment by ssuhas76** [comment]
@MaximoTrinidad . I managed to resolve the issue. There was a mismatch with x86 and 64 bit
