### ISSUE TITLE
Resolve-Path -Relative mistakenly bases the relative path on the provider-native path

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3501]
Steps to reproduce (Unix)
------------------

```powershell
New-PSDrive -PSProvider FileSystem u /usr
Set-Location u:/bin
Resolve-Path u:/ -Relative
```

Expected behavior
-----------------

```
..
```

To get from `u:/bin` to `u:/`, you need `..`

Actual behavior
---------------

```
../../usr
```

This path is not relative to the current _PS_-drive-based location, `u:/bin`, it is relative to the underlying _provider-native_ location, `/usr/bin` (in a roundabout way).

Trying to use this relative path from the current PS location actually fails:

```powershell
PS u:/bin> Get-ChildItem (Resolve-Path u:/ -Relative)  # !! Fails.
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.17) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

**Comment by iSazonov** [comment]
The desired behavior reminds `change root`.

**Comment by an-dr-eas-k** [comment]
I have the following behavior:
```
$ pwd
c:\tmp
$ Resolve-Path -Relative .
..\tmp
```
I expect `Resolve-Path -Relative .` to be `.`

**Comment by mklement0** [comment]
That's also problematic, @an-dr-eas-k, but it's a separate issue. Can you please create a new issue? Note that `Resolve-Path $PWD -Relative` exhibits the same problem.

**Comment by an-dr-eas-k** [comment]
> That's also problematic, @an-dr-eas-k, but it's a separate issue. Can you please create a new issue? Note that `Resolve-Path $PWD -Relative` exhibits the same problem.

true, and sorry, the relation is missing. Take a look: https://github.com/PowerShell/PowerShell/issues/10792#issuecomment-542129577
