### ISSUE TITLE
Get-Help About_Automatic_Variables does not dislay the full help content

### ISSUE THREAD

**Issue by GlennFaustino** [PowerShell/PowerShell#3503]
Steps to reproduce
------------------
In PowerShell version 6.0.0-Alpha.17 typing "Get-Help About_Automatic_Variables" in the console does not display the full help content, I've tried other about_* topics but same issue.

Expected behavior
-----------------
Typing "Get-Help About_Automatic_Variables" must display the full help content.

Actual behavior
---------------
PS C:\Program Files\PowerShell\6.0.0.17> Get-Help about_Automatic_Variables

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
about_Automatic_Variables         HelpFile                            Describes variables that store state informati...
about_Automatic_Variables         HelpFile                            SHORT DESCRIPTION

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
WSManStackVersion              3.0
CLRVersion
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.17
PSEdition                      Core
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
```

**Comment by MaximoTrinidad** [comment]
This is more anything you try to do a 'Get-Help About_--any topic--'  will not display the information.

PS C:\Program Files\PowerShell\6.0.0-alpha.18> $PSVersionTable

Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
CLRVersion
PSVersion                      6.0.0-alpha
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.18
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

You can't even use the '-Detailed' to show the information.

![gethelp_about_2017-05-07_10-50-54](https://cloud.githubusercontent.com/assets/19892435/25782192/c315daea-3313-11e7-9ed2-d848e117c73a.jpg)

**Comment by iSazonov** [comment]
It is duplicate #2653

**Comment by joeyaiello** [comment]
This is not actually a duplicate. #2653 says that about_* topics are missing. 

This issue here is that we're showing duplicates when there's only one copy in $PSHome. 

@HemantMahawar is adding a lower-priority issue now to enable disambiguation when duplicates exist (and to expose the help location name and module version to ease disambiguation).

**Comment by joeyaiello** [comment]
I lied! The original is #2565. Pasting my above context there to keep things clean.
