### ISSUE TITLE
Download Error 404 - Windows 10 PowerShell.0.0-alpha18 MSI not found

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3505]
Steps to reproduce
------------------
Click on the Windows 10 PowerShell MSI link on the main GitHub PowerShell page

Expected behavior
-----------------
Download Windows 10 MSI

Actual behavior
---------------
MSI not found

Environment data
----------------

Windows 10 client

![downloaderr_2017-04-07_9-35-09](https://cloud.githubusercontent.com/assets/19892435/24802488/3755c6d2-1b76-11e7-8084-6d515760b75c.jpg)

**Comment by chuanjiao10** [comment]
try later,i can download it.
server in New York , Amazon, slow some time.

**Comment by MaximoTrinidad** [comment]
Hi @chuanjiao10,

Nope! No luck. I'm still getting the 404 link error.  Of course I'm able to go to the "release" page but anyone could have issues with the link.

:)

**Comment by iSazonov** [comment]
All other links also defaced.
But I can load from release page https://github.com/PowerShell/PowerShell/releases
I believe it is GitHub cache problem.

**Comment by mirichmo** [comment]
I'm closing this issue since the links are functioning now
