### ISSUE TITLE
PowerShell.6.0.0-alpha18 - Update-Help cmdlet failes giving "Access Denied" error 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3506]
Steps to reproduce
------------------
update-help -force

Expected behavior
-----------------
No errors

Actual behavior
---------------
update-help : Failed to update Help for the module(s) 'Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core,         Microsoft.PowerShell.Host, Microsoft.PowerShell.Management, Microsoft.PowerShell.Security,                              Microsoft.PowerShell.Utility, PackageManagement, PowerShellGet, PSReadLine' with UI culture(s) {en-US} : Access to the  path '/opt/microsoft/powershell/6.0.0-alpha.18/en-US/Microsoft.PowerShell.Commands.Management.dll-Help.xml' is denied.

![updatehelp_err_ 2017-04-07 10-12-41](https://cloud.githubusercontent.com/assets/19892435/24804098/55343e90-1b7b-11e7-817b-714dd1b0541e.png)

Environment data
----------------
PS /home/maxt> cat /etc/issue                                                                                           
Ubuntu 16.04.2 LTS \n \l

```powershell
> $PSVersionTable

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-alpha                                                                             
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   3.0.0.0                                                                                 
GitCommitId                    v6.0.0-alpha.18                                                                         
CLRVersion                                                                                                             
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
@MaximoTrinidad Can you run with elevated rights?

**Comment by MaximoTrinidad** [comment]
Hi @iSazonov ,

Let me try that!  OK..

It works!

sudo powershell
update-help -force 

Thanks,
Max

**Comment by iSazonov** [comment]
It would be good to make a more user-friendly message.

**Comment by SteveL-MSFT** [comment]
Fixing [this](https://github.com/PowerShell/PowerShell/issues/2190) should resolve the real issue
