### ISSUE TITLE
Read-Host -AsSecureString   failing on pasting value into it

### ISSUE THREAD

**Issue by kae** [PowerShell/PowerShell#3511]
Get it on windows 10 with  `PowerShell-6.0.0-alpha.18-win10-win2016-x64` and version `5.1.15063.0` (coming with creators update)

Steps to reproduce
------------------
 1. Copy anything into clipboard
 2. execute command `read-host -AsSecureString`
 3. paste clipboard content into console (right mouse button click)

Expected behavior
-----------------
 There is a star in console for each pasted character. On `enter` everything is going to be returned as secure string

Actual behavior
---------------

 There is shown one star and clipboard content is shown in promt (without first two characters)

Value of $StackTrace variable just after execution is 
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
and 
```
SerializationVersion           1.1.0.1
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
GitCommitId                    v6.0.0-alpha.18
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
I can confirm that Issue is only on Windows 10 Creator with both Alfa.17 and Alfa.18.

**Comment by joeyaiello** [comment]
@iSazonov: you're not seeing this on Anniversary Update or earlier? If so, my hunch is that something changed in `conhost` with Creators Update.

**Comment by iSazonov** [comment]
In 10586 no problem.

**Comment by nehcsivart** [comment]
It seems this is not a problem with pasting, but a problem with the speed at which characters are entered into the stream.
For example, if you run `Read-Host -AsSecureString`, and press "j" and "k" at the same time, the same problem happens.

**Comment by iSazonov** [comment]
@lzybkr Could you please comment the Issue?

**Comment by lzybkr** [comment]
I have reproduced the issue in Windows PowerShell and PowerShell Core on Creators Update, but have not investigated further.

I pinged the `conhost` folks and they are not aware of any issues like this. We'll open an issue with them and figure it out - it could still come back to PowerShell if our console api usage is somehow really wrong.

**Comment by SteveL-MSFT** [comment]
Saw the thread with the `conhost` folks and they understand the issue on their side

**Comment by skrysmanski** [comment]
@SteveL-MSFT I've been bitten by this as well. Unfortunately, we have important scripts that depend a lot on this functionality. Is there an issue I can watch/monitor for the progress on the underlying problem? 

Or is there a rough time estimate (i.e. days, weeks, months) on when this will be fixed? I'm asking because I'm trying to figure out whether I should implement a workaround for this problem.

**Comment by skrysmanski** [comment]
**Workaround:** You can use the **PowerShell terminal in Visual Studio Code** as workaround. This terminal isn't affected by the problem.

**Comment by SteveL-MSFT** [comment]
@skrysmanski  This doesn't repro for me on latest Win10 fast lane flight (specifically build 16197)

**Comment by foddrick** [comment]
The workaround mentioned by @skrysmanski did not work for me. I ended up using a hotkey tool (Autohotkey) to "type" the contents of the clipboard instead of pasting it.

**Comment by crossan007** [comment]
I'm seeing a similar issue on Windows 10 1703 where typing too quickly into a ```Read-Host -AsSecureString``` prompt will forcefully terminate the running script without throwing an exception or any other indication that there was a problem.

For example: typing "asdf;lkjasdf;lkjasdf;lkjasd" very rapidly succession will cause the script to terminate.

Is there a linked issue somewhere that the progress of this can be viewed?

**Comment by SteveL-MSFT** [comment]
@crossan007 I'm not seeing a repro on Win10 1703 (10.0.16278).  Unfortunately, I believe the conhost issues are tracked only internally.  Maybe open an issue [here](https://github.com/microsoft/console)

**Comment by crossan007** [comment]
See below for reproduction: 

![image](https://user-images.githubusercontent.com/11679900/29820393-4eab61ce-8c92-11e7-9388-54d1ff689e65.png)

I'll open an issue at the link you provided.

**Comment by nehcsivart** [comment]
It seems this issue is fixed on Windows 10 Version 1709 (Build 16299.64).
The PowerShell version is 5.1 Build 16299 Revision 64.

**Comment by ecspresso** [comment]
Windows 10 Version (OS Build 16299.214). 

Run `Read-Host -AsSecureString` and ctrl+v pastes one star but right click pastes all stars.

**Comment by MaximoTrinidad** [comment]
Microsoft Windows [Version 10.0.17083.1000]
WSL = DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04

All good!

**Comment by martinzwirner** [comment]
At least in PowerShell 7.2.1 on Windows 10 Version 10.0.18363 this is not solved IMO.

Running ``Read-Host -AsSecureString`` and using Ctrl+V pastes one star and doesn't return the correct value.

Issue does not appear when using right click, and it does not appear when using PowerShell 7.2.1 inside Windows Terminal or Jetbrains Rider.

Let me know if I should open a new issue for this.
