### ISSUE TITLE
Is the suse release at going to be available at https://packages.microsoft.com/ ?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#3512]
I see suse linux in the releases.

Any chance on getting the instructions here: https://blogs.msdn.microsoft.com/powershell/2017/02/01/installing-latest-powershell-core-6-0-release-on-linux-just-got-easier/ merged into this repo and kept up to date?

Thanks!

**Comment by SteveL-MSFT** [comment]
@DarwinJS we merged a PR to update the instructions for registering the repository https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604 already.  Will look into suse support.

**Comment by DarwinJS** [comment]
I just did a PR to make download.sh autodetect the version.

What about also making download.sh automatically use repos for any variants that have repo support?

**Comment by TravisEz13** [comment]
@DarwinJS I suggested you change to use repo support before a read this.  Could you update your PR?
I'm working on getting an OpenSUSE 42.1 repo setup.

**Comment by DarwinJS** [comment]
@TravisEz13 - is the repo updated? I will also need to be briefed on the OpenSUSE commands to register the repo and pull the package. Thanx!

**Comment by TravisEz13** [comment]
42.1 is about to be unsupported.  Does it make sense to publish this?

**Comment by DarwinJS** [comment]
I wasn't aware that the previous restriction was based on known issues - I have no problem putting it back in.

**Comment by TravisEz13** [comment]
@DarwinJS  don't do anything yet.

**Comment by TravisEz13** [comment]
This is dependant on #3961

**Comment by daxian-dbw** [comment]
We now have only one RPM package for all supported red hat family of distros and it's published to the Microsoft YUM repository. However, an interactive manual step is required to install on OpenSUSE, see the [docs here](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#opensuse-422). Starting from the next release, we will publish `.tar.gz` packages for Linux/macOS, so the installation on OpenSUSE can be done using the tarball package.

.NET Core 2.0 RPM package has the same manual step requirement: https://www.microsoft.com/net/core#linuxopensuse

**Comment by DarwinJS** [comment]
This manual step is not very workable.  I spent several hours trying to work around it.  Could it be avoided by having a separate package for Open SUSE?

Is the manual step required for every update as well?

I was able to work around it by downloading the RPM and then using rpm -ivh <package> --nodeps.

But is looks like a possible side effect of that is that NONE of the dependencies are installed (rather than just skipping problematic ones) (http://blog.endpoint.com/2008/08/rpm-nodeps-really-disables-all.html)

**Comment by daxian-dbw** [comment]
Starting from the next release, we will publish `.tar.gz` packages for Linux/macOS, so the installation on OpenSUSE can be done using that tarball package. Here is an example of doing it: https://github.com/PowerShell/PowerShell/blob/master/docker/release/opensuse42.2/Dockerfile

You can play with it using the tarball package I uploaded at https://github.com/daxian-dbw/PowerShell/releases/download/v6.0.0-beta.8/powershell-6.0.0-beta.8-linux-x64.tar.gz

**Comment by DarwinJS** [comment]
@daxian-dbw - Ok I will adapt these lines in the open suse installer: https://github.com/PowerShell/PowerShell/blob/master/tools/installpsh-suse.sh#L142-L158

Is Suse the only one affected by the inability to use a package manager to create a fully automated install?

**Comment by daxian-dbw** [comment]
As far as I know, the Amazon Linux is also affected. You can find the updated dockerfile for Amazon Linux here: https://github.com/PowerShell/PowerShell/blob/master/docker/community/amazonlinux/Dockerfile

It's moved to the community folder as the Amazon Linux image is not officially supported.

**Comment by daxian-dbw** [comment]
`installpsh-suse.sh` has been updated to the `tar.gz` binary archive via the PR #5309. I will close this issue.
