### ISSUE TITLE
32bit Powershell from CMD window error

### ISSUE THREAD

**Issue by PhilNewell** [PowerShell/PowerShell#3513]
When running the following form a cmd window in Powershell 4, I get no issues.
With Powershell 5.1 I have the following issue.
When launching powershell from a commandline I get the following error.
"C:\Windows\WinSxS\wow64_microsoft-windows-powershell-exe_31bf3856ad364e35_6.3.9600.17415_none_6475a3ed0a50d87b\powershell.exe"

Output is :
`
C:\Users\pnewell> -showinitialprompt : The term '-showinitialprompt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a p
ath was included,
verify that the path is correct and try again.
At line:1 char:1
 showinitialprompt
     CategoryInfo          : ObjectNotFound: (-showinitialprompt:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException
`
Powershell Version:
PS C:\Users\pnewell> $PSVersionTable.PSVersion
`
Major  Minor  Build  Revision
5      1      14409  1005`

I use the 32bit version to launch apps in Remote Desktop Services.

Steps to reproduce
------------------
open cmd prompt in either administrator or standard mode:
"C:\Windows\WinSxS\wow64_microsoft-windows-powershell-exe_31bf3856ad364e35_6.3.9600.17415_none_6475a3ed0a50d87b\powershell.exe"

Expected behavior
-----------------
Powershell Prompt

Actual behavior
---------------
C:\Users\pnewell> -showinitialprompt : The term '-showinitialprompt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a p
ath was included,
verify that the path is correct and try again.
At line:1 char:1
 showinitialprompt
     CategoryInfo          : ObjectNotFound: (-showinitialprompt:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException

Environment data
----------------
Windows server 2012 R2

```powershell
> $PSVersionTable
Major  Minor  Build  Revision
5      1      14409  1005`

```

**Comment by lzybkr** [comment]
You are launching the v4 version of powershell.exe - which you can sort of tell from the partial path `6.3.9600.17415`. I'm not sure why your system still has the old binary, but you shouldn't use it.

That parameter was an internal flag used in V3-V5 to accept input from the unmanaged code while the engine was still starting up, making PowerShell feel more responsive unless your profile defined a `prompt` function, in which case this flag was passed to the managed code.

To run the 32 bit powershell.exe, you would run `%SystemRoot%\syswow64\WindowsPowerShell\v1.0\powershell.exe`.

**Comment by PhilNewell** [comment]
Yep, that solved my issue.  I cannot use %SystemRoot% in RDS, but substituting for the full path did work.  Thanks for the resolution.
