### ISSUE TITLE
FileVersion info is missing from System.Diagnostics.Process

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#3515]
This has to do with the underlying .net implementation but we should get them to change it and track that here.

Expected behavior
-----------------
jps> gps power* |ft name,desc*,comp*
Name       Description        Company
----       -----------        -------
powershell dotnet             Microsoft Corporation
powershell Windows PowerShell Microsoft Corporation
powershell Windows PowerShell Microsoft Corporation

Actual behavior
---------------
jps> gps power* |ft name,desc*,comp*

Name       Description Company
----       ----------- -------
powershell
powershell
powershell

Environment data
----------------

jps> $PSVersionTable

Name                           Value
----                           -----
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
GitCommitId                    v6.0.0-alpha.18
PSVersion                      6.0.0-alpha
CLRVersion
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSEdition                      Core

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this issue be closed? I can't reproduce the issue on 7.4.

```powerhell
gps pwsh |ft name,desc*,comp*

Name Description Company
---- ----------- -------
pwsh pwsh        Microsoft Corporation
```
