### ISSUE TITLE
Linux alpha.18 install script is deploying alpha.17

### ISSUE THREAD

**Issue by latkin** [PowerShell/PowerShell#3521]
https://raw.githubusercontent.com/PowerShell/PowerShell/v6.0.0-alpha.18/tools/download.sh

![image](https://cloud.githubusercontent.com/assets/5943573/24875142/f5aa2d96-1ddb-11e7-8cbd-3bbc700e4afd.png)

**Comment by latkin** [comment]
Looks like doc/script updates for .18 were merged after the release was cut: https://github.com/PowerShell/PowerShell/compare/v6.0.0-alpha.18...master

**Comment by joeyaiello** [comment]
Hmm, I don't know how tricky it is fix the tag, paging @PowerShell/powershell-maintainers

**Comment by latkin** [comment]
Maybe best to just create a .19 tag/release and delete the .18 release

**Comment by vors** [comment]
This is expected, because we creating the tag, before building the packages.
See the [release instruction doc](https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md#release-checklist).

We can try to revisit this process, but we usually want to make a tag and grab the build from CI, so we need working `download.sh` to get it out. That creates a chicken and egg problem and we just using the previous pre-built for the `download.sh`.

I propose to remove the tag version pinning from the [install instruction](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md) to avoid confussion. It safe to get the version from main and it would allow maintainers update one less place, when making the release.

**Comment by lzybkr** [comment]
I don't think it's expected - we're not pushing a tag until the release is ready to publish.

All of the changes are made in a branch, the build server builds the branch, we publish those binaries - no CI is needed.  @raghushantha can confirm.

**Comment by TravisEz13** [comment]
@lzybkr Alpha.17 has the same issue.  We haven't updated the download script until the binaries have been published.  I talked to @daxian-dbw  during the release and pointed out this issue i.r.t. the docker files.  I think we should fix the process for the next release.   Once download.sh is changed, Linux won't build until we publish the next build.  We need to put some thought into how to make the work properly.  I suggest using the repositories where available in download.sh.

**Comment by raghushantha** [comment]
@lzybkr Correct. The Release system does not use download.sh. It clones/builds based off the tag and packages the binaries.

**Comment by DonPwrShellHunt** [comment]
The link 
https://raw.githubusercontent.com/PowerShell/PowerShell/v6.0.0-beta.1/tools/download.sh
points to v6.0.0-alpha.18. No surprise really (based on the description of this issue), but it delayed my install of beta.1 on macOS since the first documented beta install instructions I saw used download.sh.

**Comment by joeyaiello** [comment]
@DonPwrShellHunt but that's because you're grabbing the download.sh in the beta tag. If you use the download.sh from master, you'll always get the latest *release* build: https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/download.sh

**Comment by latkin** [comment]
@joeyaiello If the official team guidance is "use download.sh from master to get the latest release package" then I recommend you update your published installation documentation to say so. At the moment, your docs in the master branch are telling people to run the wrong script: https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md

**Comment by andschwa** [comment]
Why don't we just update `download.sh` to add the relevant package repository, and install the package from there? No more fussing with downloading a particular file from GitHub.

**Comment by joeyaiello** [comment]
Now *that* is...totally valid. We should do that. 😄 

@TravisEz13 that sound reasonable to you?

**Comment by joeyaiello** [comment]
@andschwa I'm good w/ that too, but it sounds like more work. Doc update might be the way to go in the meantime.

**Comment by andschwa** [comment]
@joeyaiello it really wouldn't be. We already have all the code to do it in the form of instructions on the installation documentation page.

**Comment by joeyaiello** [comment]
So you got this then? ;) 

Also, would that mean that we would install Homebrew and Homebrew-Cask on macOS users?

**Comment by andschwa** [comment]
> Also, would that mean that we would install Homebrew and Homebrew-Cask on macOS users?
I wouldn't install home brew, but if it's there, we could use it to install the cask version.

I'm also a fan of just deleting this script entirely (I tried pre-launch), it's a maintenance nightmare.

**Comment by joeyaiello** [comment]
There is a long tail of scenarios that are using it in the wild. I can't enumerate them all off-hand, but I've dealt with enough users that need it that I think it's worthwhile to continue maintaining.

**Comment by andschwa** [comment]
I know 😢

**Comment by TravisEz13** [comment]
Yeah, there is a PR to move to using the repo's but it got stalled.  
https://github.com/PowerShell/PowerShell/pull/3608/files

**Comment by joeyaiello** [comment]
Just came back once to post that once I remembered it was there. Thanks, @TravisEz13

**Comment by iSazonov** [comment]
Seems we could close the old issue.

**Comment by TravisEz13** [comment]
I agree.  We have updated the build process and the docs are mainly separate from the repo now.
