### ISSUE TITLE
Add Where-Object -Not support

### ISSUE THREAD

**Issue by ChrisMagnuson** [PowerShell/PowerShell#3529]
I often have the need to filter for objects that do not have a property specified or who have a falsey value for a property by doing something like the following:

```
$Computers = [PSCustomObject]@{
    ComputerName = "SPC-1234"
    IPAddress = "192.168.0.1"
},
[PSCustomObject]@{
    ComputerName = "BGP-5678"
    IPAddress = ""
},
[PSCustomObject]@{
    ComputerName = "MGC-9101"
}

$Computers | 
Where {-not $_.IPAddress }
```
```
ComputerName IPAddress
------------ ---------
BGP-5678              
MGC-9101 
```

If I am doing the opposite test I can avoid using a script block with Where-Object:

```
$Computers |
Where IPAddress
```

```
ComputerName IPAddress  
------------ ---------  
SPC-1234     192.168.0.1
```

I would like to be able to also avoid using a script block when using -Not which would enable the following:
```
$Computers | 
where -not IPAddress
```

**Comment by BrucePay** [comment]
This is an issue with the Where-Object cmdlet not the language itself.

**Comment by iSazonov** [comment]
@BrucePay Thanks! Clear.
 We have related Issue #2658 Do we want to really do this?

/cc @lzybkr

**Comment by SimonWahlin** [comment]
I think I could add a -Not parameterset to Where-Object.

I can't find any tests for Where-Object, where are those?

**Comment by powercode** [comment]
I think it is a good idea.

**Comment by iSazonov** [comment]
@SimonWahlin I dont found `Where-Object` test.
I think we should place it in `test\powershell\Modules\Microsoft.PowerShell.Core` folder.

**Comment by SimonWahlin** [comment]
Thanks, I'll try to come up with a set of tests and place them there.

**Comment by iSazonov** [comment]
@SimonWahlin Please use new Pester 4 syntax in tests.

**Comment by SimonWahlin** [comment]
Absolutely!
