### ISSUE TITLE
Get-Childitem Parameter -ExpiringInDays in Cert: PSDrive in Windows 7 and Powershell 5.0

### ISSUE THREAD

**Issue by NoNeedToYell** [PowerShell/PowerShell#3531]
Steps to reproduce
------------------
Run Get-Childitem Cert:\LocalMachine\My -ExpiringInDays xx

Expected behavior
-----------------
Cmdlet should return certificates that expire in xx days or less. This works perfectly on Windows 10 with PS 5.1

Actual behavior
---------------
Errormessage: A Parameter cannot be found that matches parameter name 'ExpiringInDays'

Environment data
----------------
Windows 7 with WMF updated to 5.0

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

**Comment by iSazonov** [comment]
Dup #3847
