### ISSUE TITLE
PowerShell 6 Alpha18 - Cursor jumping to next line screen issues in Windows 10 Bash.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3532]
Steps to reproduce
------------------
Open Windows 10 Bash then execute the following commands:
ps -e
dir
service --status-all
powershell
Scroll-up
Scroll-down
dir
**>screen jump
Type Service
**>screen jump while typing service

Expected behavior
-----------------
Typing command should not jump cursor to next line.

Actual behavior
---------------
While typing the jump cursor to next line. Also, sometimes the content is lost when scrolling up.
(See images)

![posh6alpha18screenjump_2017-04-11_13-59-37](https://cloud.githubusercontent.com/assets/19892435/24924912/7aae78c4-1ec4-11e7-9630-613a324b039a.jpg)

![posh6alpha18screenjump_2_2017-04-11_13-59-37](https://cloud.githubusercontent.com/assets/19892435/24924922/8461c6be-1ec4-11e7-8eb8-da230c86b132.jpg)

Environment data
----------------

Windows 10 Pro Build 16170.rs_prerelease.170331-1532

```powershell
PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by SteveL-MSFT** [comment]
Isn't this the same as https://github.com/PowerShell/PowerShell/issues/1829 which is due to https://github.com/dotnet/corefx/issues/12452?

**Comment by MaximoTrinidad** [comment]
Just realized, that when resizing (expanding) the Bash Console with PowerShell loaded seems to cause the scroll-up sometimes misbehave and the screen doesn't refresh completely.

Windows 10 Pro Insider latest build 16184

![bash_02_2017-05-04_10-23-52](https://cloud.githubusercontent.com/assets/19892435/25708883/cd32a0ea-30b5-11e7-8052-1468f2f52f7d.jpg)


By the way, How can I see what version of Bash I'm running?  Or, Do I need to rebuild my Bash environment every time I update my Windows 10 Insider build?

Thank!
