### ISSUE TITLE
Out-String concatenation behavior 

### ISSUE THREAD

**Issue by jaredpar** [PowerShell/PowerShell#3534]
I'm trying to understand how `Out-String` chooses to combine the input strings.  In particular, how it chooses what separators to insert between the strings.  The [documentation](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/out-string) only states the following:

>  By default, Out-String accumulates the strings and returns them as a single string, but you can use the stream parameter to direct Out-String to return one string at a time. 

This says nothing about inserting anything between the string objects being combined but in practice `Out-String` seems to do exactly this.  

``` powershell
> $lines = @('hello', 'world')  
> $lines | Out-String
hello
world

>
```

The `Out-String` command let appears to be inserting new line characters here.  Is this what is actually occurring and it's simply undocumented or there a more subtle behavior at work here that i'm missing?  Additionally what new line is inserted: `Environment.NewLine` or is it hard coded to a particular combination?

**Comment by lzybkr** [comment]
I believe it is a `Environment.Newline` based on this [code](https://github.com/PowerShell/PowerShell/blob/8d4db01a5d4b5dcd981ef216d3d7f24b484c7c60/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/out-string.cs#L127) - assuming `StringBuilder.AppendLine` uses `Environment.Newline` on all targets.

As the documentation suggests - you can use the `-Stream` parameter if need different behavior.

**Comment by mklement0** [comment]
@jaredpar: 

You can think of `Out-String` as producing the same output as in the console (implied `Out-Host`):

Since the default formatter is involved,

  *  _multiple_ objects of the same type may be formatted _together_, so it's not a simple case of concatenating individual, self-contained representations.

    * With an array of  _strings_ as the (only) input, however - given that strings are output as-is - the input strings are concatenated with - and invariably also _terminated_ with (see #3684) - a platform-appropriate newline each (`[environment]::NewLine`), as @lzybkr notes.

    * The formatting of multiple _non-string objects_ results in a _combined_ representation (whose internal line breaks also use the platform-appropriate newline).

      * If all input objects are of the _same_ type, you get predictable output; e.g.: `(Get-Item /), (Get-Item /) | Out-String`

      * If the type are disparate, the output is hard to predict, because the _first_ object's type determines the formatting; compare `(Get-Date), (Get-Item /) | Out-String` to `(Get-Item /), (Get-Date) | Out-String`

      * Given the above, which applies to all `Out-` cmdlets (because they all use the default formatter), it's better to limit use of `Out-` cmdlets to creating output for _human eyeballs_ rather than machine-parsable output.
         * In the case of  a string array, perhaps the better  approach is to use `('hello', 'world') - join [environment]::newline` (which does _not_ add a trailing newline).

**Comment by powercode** [comment]
@jaredpar We are also in the process of adding `Join-String`, a cmdlet specifically designed to create new strings from pipelined input. See #7660.
