### ISSUE TITLE
Could you please keep the numeric-only version number unique => use 6.0.2-beta1 - NOT 6.0.0-beta1 ?

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#3536]
The reason is that I would like to remove the alpha characters from the version so that this starts showing up on chocolatey public searches.  Nuget hides anything with alpha in the version number as being a pre-release.

So if you rev the second position every release will have a completely unique NUMERIC ONLY version number.

Would also just be nice in general to have the numeric-only version be completely unique for easy reference.

**Comment by SteveL-MSFT** [comment]
Until 6.0.0 final, the current releases are all pre-releases.  After 6.0.0, the plan is to use 6.1.0 as the version and 6.0.1 if we need to service 6.0.0.  For Beta1, it'll likely be 6.0.0-beta.1.

**Comment by vors** [comment]
We use [semver](https://github.com/PowerShell/PowerShell/blob/68bcd4b5284bb169c52a570afbfdd1bb70d0de10/docs/maintainers/releasing.md#preparing). That's how semver works. :)

**Comment by DarwinJS** [comment]
Yep - familiar with strict semver - thanks.
