### ISSUE TITLE
Get-ComputerInfo : Unable to find an entry point named 'GetCurrentThread'

### ISSUE THREAD

**Issue by zii-dmg** [PowerShell/PowerShell#3541]
Steps to reproduce
------------------
```powershell
> Get-ComputerInfo

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'GetCur
rentThread' in DLL 'api-ms-win-core-processthreads-l1-1-2.dll'.
   at GetCurrentThread()
   at Microsoft.Management.Infrastructure.Native.OperationHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Finalize()
Get-ComputerInfo : Unable to find an entry point named 'GetCurrentThread' in DLL 'api-ms-win-core-p
rocessthreads-l1-1-2.dll'.
At line:1 char:1
+ Get-ComputerInfo
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ComputerInfo], EntryPointNotFoundException
    + FullyQualifiedErrorId : System.EntryPointNotFoundException,Microsoft.PowerShell.Commands.Get
   ComputerInfoCommand
```

Environment data
----------------
Windows 7 SP1 x64 Pro
PowerShell 6.0.0 alpha 18 from PowerShell-6.0.0-alpha.18-win7-win2008r2-x64.zip

```powershell
> $PSVersionTable
Name                           Value
----                           -----
GitCommitId                    v6.0.0-alpha.18
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
CLRVersion
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
PSEdition                      Core
```

**Comment by jeffbi** [comment]
I don't think this is a `Get-ComputerInfo` issue _per se_. `Get-ComputerInfo` does not use `GetCurrentThread` or any of the threading functions.

The stack trace suggests that the issue is based in releasing a `SafeHandle`. `Get-ComputerInfo` doesn't (directly) use `SafeHandle`s either.

**Comment by iSazonov** [comment]
I never considered this cmdlet as a useful but it really useful! - it helped find already some bugs 😄

**Comment by iSazonov** [comment]
@mirichmo Could you please comment the Issue?

And why 'api-ms-win-core-processthreads-l1-1-2.dll'? I check "dumpbin.exe" /exports api-ms-win-core-processthreads-l1-1-0.dll - the `GetCurrentThread` is there.

Is the Issue in Area-Build?

**Comment by jeffbi** [comment]
@iSazonov Glad you like it :blush:

**Comment by mirichmo** [comment]
I duplicated it using Alpha.17. api-ms-win-core-processthreads-I1-1-2.dll is not used by PowerShell Core. The callstack indicates that the call originates in MI .Net (Microsoft.Management.Infrastructure.Native.*), so the bug isn't in PowerShell Core.

The fix would be to address it in MI .Net and update the version of MI .Net that PowerShell Core uses (or just update it if the fix it already published).

**Comment by iSazonov** [comment]
@mirichmo Thanks for clarify! 

Now we moved to .Net Core 2.0 and we should re-check the bug again.

**Comment by zii-dmg** [comment]
Beta 5 still crashes on Windows 7 x64 (PowerShell-6.0.0-beta.5-win7-win2008r2-x64.zip, PowerShell-6.0.0-beta.5-win7-x86.zip).

**Comment by SteveL-MSFT** [comment]
cc @adityapatwardhan looks like we may missing some other package for MMI to work on Win7

**Comment by zii-dmg** [comment]
Beta 7 still crashes on Windows 7 x64 (PowerShell-6.0.0-beta.7-win-x64.zip, PowerShell-6.0.0-beta.7-win-x86.zip).

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/3541
