### ISSUE TITLE
running dpkg -i on Ubuntu 16.04 gives many leaked file descriptor errors

### ISSUE THREAD

**Issue by FawcettJohnW** [PowerShell/PowerShell#3543]
Steps to reproduce
------------------
Install PowerShell on Ubundu 16.04 system
Download kernel package
Install kernel package with "dpkg -i <package>"

Expected behavior
-----------------
Package installs silently, as with bash

Actual behavior
---------------
Package appears to install correctly, but there are hundreds of errors like this on the screen:
        File descriptor 173 (/dev/zero) leaked on vgs invocation. Parent PID 8742: /usr/sbin/grub-probe

Environment data
----------------

PS /tmp/latest_kernel> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.17
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by SteveL-MSFT** [comment]
@FawcettJohnW can you provide URL to kernel package you used?

**Comment by SteveL-MSFT** [comment]
Finally got around to investigating this.  Installed latest .deb on Ubuntu 16.04 using PowerShell beta.2.  No extraneous output using `dpkg -i`.  Closing this.
