### ISSUE TITLE
Question: what is the default value of SerializationDepth ?

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShell#3549]
In the [documentation](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/update-typedata) of Update-TypeData we read this for the parameter _SerializationDepth_
```
Specifies how many levels of type objects are serialized as strings. 
The default value, 1, serializes the object and its properties. 
A value of 0 serializes the object, but not its properties. 
A value of 2 serializes the object, its properties, and any objects in property values.
```
But the default value is 'none' for Powershell  v6.0.0-alpha (v6.0.0-alpha.18):
```Powershell  
help Update-TypeData -Parameter SerializationDepth
    -SerializationDepth [<Int32>]
        #same description
    
        Required?                    false
        Position?                    named
        Default value                none
        Accept pipeline input?       false
        Accept wildcard characters?  false
```       
And the default value is '1' for Powershell v5.1.14409.1005 :  
```Powershell
help Update-TypeData -Parameter SerializationDepth
   -SerializationDepth [<Int32>]
        #same description
        
        Required?                    false
        Position?                    named
        Default value                1
        Accept pipeline input?       false
        Accept wildcard characters?  false
```       
With this code the default value is zero for the both versions :
```Powershell         
Add-Type @'
using System;
namespace Test
{
    public class SD
    {
        public string Name{ get; set; } 

        public SD()
        {
            Name = "Test";
        }
    }
}
'@
Update-TypeData -TypeName Test.SD -DefaultDisplayPropertySet Name
Get-TypeData -TypeName Test.SD|Select SerializationDepth
SerializationDepth
------------------
                 0
```
The default value of SerializationDepth is zero or one ?

**Comment by iSazonov** [comment]
I believe the default is 1
See [MshDefaultSerializationDepth](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs#L73)

**Comment by LaurentDardenne** [comment]
Thanks.

[PSSerializer.Serialize](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/System.Management.Automation/engine/serialization.cs#L101) use 1 and [Update-TypeData](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs#L234) use _int.MinValue_.

In this case, but may be is it an another question/context, why must I declare a .ps1xml file with a PSConverterType for the rehydration ?
```xml
    <Type>
        <Name>Test.SD</Name>
        <TypeConverter>
            <TypeName>Test.SDConverter</TypeName>
        </TypeConverter>
        <Members>
            <MemberSet>
                <Name>PSStandardMembers</Name>
                <Members>
                    <NoteProperty>
                        <Name>SerializationDepth</Name>
                        <Value>1</Value>
                    </NoteProperty>
                </Members>
            </MemberSet>
        </Members>
    </Type>
```

**Comment by iSazonov** [comment]
`int.MinValue` is not used as real value, only as "null".

I know nothing about your second question.

**Comment by LaurentDardenne** [comment]
Thanks.

Same remark about the **Export-Clixml** cmdlet, parameter _Depth_. 
The default value is 'none' for Powershell v6.0.0-alpha (v6.0.0-alpha.18):
```Powershell
help Export-Clixml -parameter Depth
   -Depth [<Int32>]
    Specifies how many levels of contained objects are included in the XML representation. 
    The default value is 2.

    The default value can be overridden for the object type in the Types.ps1xml files. 
   For more information, see about_Types.ps1xml.
  
      Required?                    false
      Position?                    named
      Default value                none
      Accept pipeline input?       false
      Accept wildcard characters?  false
```
And the default value is '2' for Powershell v5.1.14409.1005 :
```Powershell
  -Depth <Int32>
    #same description
    Required?                    false
    Position?                    named
    Default value                2
    Accept pipeline input?       false
    Accept wildcard characters?  false
```
Is it a breaking change or a documentation error ?

**Comment by SteveL-MSFT** [comment]
@LaurentDardenne according to the [code](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs#L37), `Export-CliXml -Depth` default is 0 for PSCore v6.  I looked in the Windows PowerShell 5.1 code and it's also `-Depth 0` default.  Looks like a problem in the documentation.

**Comment by lzybkr** [comment]
The default of 0 in the code is just a sentinel value to signal no `-Depth` parameter used, and instead use the real default, which I believe is 2.

**Comment by iSazonov** [comment]
The [default](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/serialization.cs#L52) is 2.

**Comment by LaurentDardenne** [comment]
Thanks :-)
