### ISSUE TITLE
`Get-Help !!` returns help for Get-FileHash

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3552]
Should investigate to understand why help resolved to `Get-FileHash` cmdlet as there may be a bigger issue.

TFS:11375235

Repro:

```powershell
PS> update-help
PS> get-help !!
```

Expected:

Probably help not found

Actual:

```powershell

NAME
    Get-FileHash

SYNOPSIS
    Computes the hash value for a file by using a specified hash algorithm.
...
```

```powershell
Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.18
```

**Comment by adityapatwardhan** [comment]
The '!!' matches one of examples in the Get-FileHash 
```
Write-Error "Get-FileHash results are inconsistent!!"
```

So I believe this is a "Won't Fix". Marking and closing it accordingly. Please re-open if you do not agree.

**Comment by iSazonov** [comment]
May be change the example? `Write-Error "Get-FileHash results are inconsistent!"
`

**Comment by SteveL-MSFT** [comment]
Seems like an edge case, but '!!' seems grammatically incorrect.  Changing it to a single exclamation marks seems right to me.

**Comment by SteveL-MSFT** [comment]
I believe the fix needs to be made in powershell-docs repo
