### ISSUE TITLE
Enter-PSSession Windows -> Linux throws "Cannot find drive"

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PowerShell#3553]
Steps to reproduce
------------------
Create new PSSession and enter or just run Enter-PSSession immediately.
Doesn't matter if transport is WSMAN or SSH.

Expected behavior
-----------------
Doesn't throw error and enters the session

Actual behavior
---------------
Does throw error and enters the session.
![2017-04-13_20-48-53](https://cloud.githubusercontent.com/assets/10071039/25019458/f4cd8ae2-208a-11e7-94d8-9d15d1db21aa.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
CLRVersion
WSManStackVersion              3.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.18
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSEdition                      Core
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
```

**Comment by daviwil** [comment]
Hey Ben, does this happen outside of VS Code too?

**Comment by bgelens** [comment]
Hi @daviwil, Yes, this is happening outside of code too

**Comment by attesch** [comment]
This issue also occurs when passing a string that contains an asterisk as an argument to a command. 
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' $authURI --user 'user:test*pass
'
Cannot find drive. A drive with the name 'user' does not exist.
At line:1 char:1
+ curl -X POST --header 'Content-Type: application/json' --header 'Acce ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (user:String) [], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound
```

**Comment by SteveL-MSFT** [comment]
@attesch your issue is https://github.com/PowerShell/PowerShell/issues/3931

@bgelens This doesn't repro for my using beta.2 on both the client (Windows) and server (Ubuntu16.04).  Does this still repro for you?

**Comment by bgelens** [comment]
@SteveL-MSFT I need to prep an environment to check this out. Will check this out asap

**Comment by bgelens** [comment]
Doesn't repro for me with beta.2 either. Client (Server 2016) Server (CentOS 7.3)

**Comment by DanielSSilva** [comment]
This is happening to me (also from Windows to Linux), but only on the PowerShell Integrated Terminal, when trying to access to my raspberry (I'll assume it also happens to any other Linux OS). If I do the same through pwsh, it connects successfully.
![image](https://user-images.githubusercontent.com/6862119/46587357-44499680-ca83-11e8-83ed-47d01cb5946e.png)

**Comment by SteveL-MSFT** [comment]
@tylerl0706 is this something you can try to repro?

**Comment by DanielSSilva** [comment]
@SteveL-MSFT it got solved really fast. @tylerl0706 asked me to try with this CI build https://ci.appveyor.com/project/PowerShell/vscode-powershell/build/artifacts
And it worked!
