### ISSUE TITLE
Exit-PSSession results in terminating exception resulting in process crash

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PowerShell#3554]
Steps to reproduce
------------------
Create / Enter PSSession over SSH or WSMAN Windows -> Linux.
Exit-PSSession

Expected behavior
-----------------
No issue

Actual behavior
---------------
Throws error and crashes PowerShell
![2017-04-13_20-52-32](https://cloud.githubusercontent.com/assets/10071039/25019742/f949eace-208b-11e7-8b6e-861bf19c9d50.png)
![2017-04-13_20-56-25](https://cloud.githubusercontent.com/assets/10071039/25019751/063ca33e-208c-11e7-9b70-71271b172db9.png)

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
GitCommitId                    v6.0.0-alpha.18
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
PSEdition                      Core
PSRemotingProtocolVersion      2.3
CLRVersion
```

**Comment by SteveL-MSFT** [comment]
No longer seeing this issue
