### ISSUE TITLE
PowerShell Core in a NanoServer container hangs after running Get-ComputerInfo

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3557]
Steps to reproduce
------------------
Create a NanoServer container with PowerShell Core build alpha 18 using the image from microsoft/powershell. Run powershell.exe from "c:\Program Files\PowerShell\latest". Run Get-ComputerInfo.

Expected behavior
-----------------
Get-ComputerInfo command successfully runs and outputs data. 

Actual behavior
---------------
Get-ComputerInfo command hangs after outputting some data.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
CLRVersion
PSEdition                      Core
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
PSVersion                      6.0.0-alpha
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
GitCommitId                    v6.0.0-alpha.18
```

**Comment by TravisEz13** [comment]
Verified `get-computerinfo` does not hang but fails as expected no 6.0.2 and nanoserver 1709
