### ISSUE TITLE
Install-Script from PowerShellGet kills variables in Path variable.

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/PowerShell#3559]
Steps to reproduce
------------------

Run Install-script on Windows 10 to install a script from the PowerShell Gallery. On a fresh system the cmdlet will ask you to add to the path `PATH Environment Variable Change`, if you agree your path variable is screwed up. 

Expected behavior
-----------------
Path environment variable should be:
 `%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%BinDir%;%BinDir%\scripts;C:\Program Files\WindowsPowerShell\Scripts`

Actual behavior
---------------
Path environment variable is:
`C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\bin;C:\bin\scripts;C:\Program Files\WindowsPowerShell\Scripts`

Environment data
----------------
I have seen this problem before and wrote a [blog post ](https://peter.hahndorf.eu/blog/AddingToPathVariable.html )about it:

It also links to code to do it correctly.

**Comment by iSazonov** [comment]
@hahndorf Please move the Issue in PowerShellGet repo https://github.com/PowerShell/PowerShellGet

**Comment by hahndorf** [comment]
Wrong repo, open issue in PowerShellGet repo and close it here.

**Comment by iSazonov** [comment]
For reference https://github.com/PowerShell/PowerShellGet/issues/116
