### ISSUE TITLE
AppImage fails under Centos 6.8

### ISSUE THREAD

**Issue by paul-bell** [PowerShell/PowerShell#3563]
Hello,

I first tried the Centos 7 RPM but executing the resulting powershell binary complained about GLIBCXX versions. Everything I've read suggests that trying to maintain multiple versions of glibc is a bad idea.

So I then tried the Linux AppImage which claimed to be self-contained and independent of the Linux distribution. This failed because of a missing dependency, libfuse.so.2. So...I did a local rpm install of the fuse libraries, retried PS, and got a different error, one that led me back to the need for a different glibc (please see "Actual Behavior" below).

I sure would like to be able to run PS under Centos 6.8!

Thanks for your help.

Steps to reproduce
------------------
./PowerShell-6.0.0-alpha.18-x86_64.AppImage

Expected behavior
-----------------
Either a PowerShell prompt or some evidence that the binary works, e.g., a message.

Actual behavior
---------------
**error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory**

Then installed the fuse libs via:

**rpm -ivh fuse-libs-2.8.3-5.el6.x86_64.rpm**

Then got this result:

**/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.mount_rwW5m7/usr/lib/libtinfo.so.5)**

Environment data
----------------
Kernel: 2.6.32-642.11.1.el6.x86_64
Centos: centos-release-6-8.el6.centos.12.3.x86_64

**Comment by joeyaiello** [comment]
Unfortunately, .NET Core does not support versions of CentOS before 7. Without support on their end, we also can't support anything prior to 7. 

I'd look at or participate in this issue: dotnet/coreclr#6792

There's some people there discussing that you might just need a new version of glibc (which would align with the error you see here).

**Comment by paul-bell** [comment]
Got it, Joey; thanks very much.

**Comment by probonopd** [comment]
If you __really__ need this to work you might explore https://github.com/probonopd/AppImages/issues/84
