### ISSUE TITLE
Review all if/def and Unix specific code after moving to .NET Core 2.0

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3565]
PowerShell Core is moving to .NET Core 2.0 with PR #3556. Once that PR is merged, we need to review all if/def and Unix specific code to:
- Clean up the code
- Make sure the code make sense and is not a temporary hack

#### An Example (Please remove when fixed)
`Platform.InternalGetFolderPath` in `src/System.Management.Automation/CoreCLR/CorePsPlatform.cs` has the following code:
```
                case System.Environment.SpecialFolder.ProgramFiles:
                    folderPath = "/bin";
                    if (!System.IO.Directory.Exists(folderPath)) { folderPath = null; }
                    break;
                case System.Environment.SpecialFolder.ProgramFilesX86:
                    folderPath = "/usr/bin";
                    if (!System.IO.Directory.Exists(folderPath)) { folderPath = null; }
                    break;
                case System.Environment.SpecialFolder.System:
                case System.Environment.SpecialFolder.SystemX86:
                    folderPath = "/sbin";
                    if (!System.IO.Directory.Exists(folderPath)) { folderPath = null; }
                    break;
```
It use `/bin` for `ProgramFiles`, `/usr/bin` for `ProgramFilesX86` and `/sbin` for `System` and `SystemX86`. It's not clear if this is appropriate, so code like this should be reviewed.

**Comment by iSazonov** [comment]
@daxian-dbw If this does not require a lot of time please create a sln file - without it IntelliSense does not work in VS Code (after json files was removed) properly.

**Comment by daxian-dbw** [comment]
@iSazonov IntelliSense doesn't work for you? It works for me in VS Code after moving to `.csproj` file. Just run `Start-PSBuild -publish`, then open the `.csproj` file in VS Code, and if you see a prompt on top of VS Code asking to restore, just click `Close`, and things like reference resolution and IntelliSense should just work.
I thought creating a `sln` file would be just as simple as opening `powershell-win-core.csproj` in VS2017 and then saving a solution file, but it turned out the `.csproj` doesn't work properly within VS2017. I haven't got the chance to figure out why and fix it.

**Comment by jeffbi** [comment]
@daxian-dbw, @iSazonov IntelliSense doesn't work for me either. I tried following the steps above, but no joy.

**Comment by iSazonov** [comment]
As mentioned in #3356 there is a limitation https://github.com/OmniSharp/omnisharp-vscode/issues/1156 
So we need sln file in repo root folder.
I suggest to continue the discussion in #3356.

**Comment by iSazonov** [comment]
Code for review https://github.com/PowerShell/PowerShell/pull/3224/files#r103523572

**Comment by andschwa** [comment]
These hacks are finally being cleaned up? Huzzah!

**Comment by iSazonov** [comment]
I created 3 PRs to address `#if CORECLR`.
There are still 75 places left but they are too complicated for me. Leave them to MSFT team.

/cc @SteveL-MSFT
