### ISSUE TITLE
missing path to system modules in $env:PSModulePath in microsoft/powershell Docker base image

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3569]
This is not a PowerShell Core issue, but it's connected to Docker base image created to support easy test of PowerShell Core. I don't know if this is the right place to submit this issue.

When I run a container built on microsoft/powershell Docker base image (the one with the latest PowerShell Core), $env:PSModulePath has a different value when I run PowerShell in the container directly and when I connect to it using Invoke-Command -ContainerID.

Steps to reproduce
------------------
Run a container based on microsoft/powershell:nanoserver image.
```
docker run -it --rm microsoft/powershell:nanoserver powershell
```
Execute this inside of a container:
```
PS C:\> $env:PSModulePath -split ';'
C:\Users\ContainerAdministrator\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\latest\Modules
```
Connect to the same container using Invoke-Command:
```
PS C:\> Enter-PSSession -ContainerId 3b7424b9239b... -RunAsAdministrator

[3b7424b9239b...]: PS C:\> $env:psmodulepath -split ';'
C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
c:\windows\system32\windowspowershell\v1.0\Modules
```
Expected behavior
-----------------
Content of $env:PSModulePath should be the same in both cases. 

Actual behavior
---------------
`c:\windows\system32\windowspowershell\v1.0\Modules` is missing when you run PowerShell in a container directly.

**Comment by mirichmo** [comment]
@alexandair Check $PSHOME in both cases. In the first instance, it looks like you are using PowerShell Core. In the second instance, you are using Windows PowerShell (inbox system32 version). If that is the case then the difference in module path sets is expected.

**Comment by alexandair** [comment]
@mirichmo As I said, this is not connected to PowerShell Core. In both cases I'm "connected" to Windows PowerShell.

```
# directly running commands in a container
PS C:\> $pshome
C:\Windows\System32\WindowsPowerShell\v1.0
PS C:\> $env:PSModulePath -split ';'
C:\Users\ContainerAdministrator\Documents\PowerShell\Modules
C:\Program Files\PowerShell\Modules
c:\program files\powershell\latest\Modules
```

```
# Interactive session using the -ContainerID
[354ec2ca2095...]: PS C:\> $pshome
C:\Windows\System32\WindowsPowerShell\v1.0
[354ec2ca2095...]: PS C:\> $env:psmodulepath -split ';'
C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
c:\windows\system32\windowspowershell\v1.0\Modules
```

The content of $env:PSModulePath is not the same.
The main problem is that c:\windows\system32\windowspowershell\v1.0\Modules is missing in the first case.

$PSVersionTable is the same in both cases:
```
PS C:\> $psversiontable

Name                           Value
----                           -----
BuildVersion                   10.0.14393.1000
SerializationVersion           1.1.0.1
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      5.1.14393.1000
PSEdition                      Core
PSRemotingProtocolVersion      2.3
WSManStackVersion              3.0
```

`Get-Module -List` doesn't give the same output.

**Comment by SteveL-MSFT** [comment]
The Windows Docker Images we currently create and publish are targeting use of PSCore v6 on them even though they also contain the inbox Windows PowerShell [Core] v5.  They are really designed to be used as:

```
docker run -it microsoft/powershell:nanoserver
```

where the default entry point is PS Core v6 and the env vars point to that.  When you use Invoke-Command/Enter-PSSession -ContainerId, this is connecting to the inbox Windows PowerShell v5.  Perhaps we should update the remoting endpoint configuration to point to PSCore v6.

cc @TravisEz13

**Comment by TravisEz13** [comment]
Unless PowerShell Direct can be told to use a different configuration per VM, I agree we should update PowerShell 6 to be the default for the Docker containers.

**Comment by SteveL-MSFT** [comment]
`Enter-PSSession` takes a `-ConfigurationName` parameter so it should be possible to point it to the PSCore6 endpoint.  However, you have to run `$PSHOME\Install-PowerShellRemoting.ps1` first to create the endpoint.  Looking at our dockerfiles, we only install PSCore6 and don't register the endpoint so we should do that and also consider pointing the default endpoint to PSCore6 as that is the purpose of those images.

**Comment by mirichmo** [comment]
`Enable-PSRemoting` is also supported. That can be used instead of the script.

**Comment by TravisEz13** [comment]
`1709` version of `nanoserver` this functionality does not work any longer.  I've been assured that this functionality will be restored in the next major release for servers (working with PowerShell Core).

Also, for `nanoserver` the team has said that [the use of BuiltinAdministrator should be discontinued](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/system-requirements#nano-server-vs-windows-server-core).

>Starting with Windows Server version 1709 applications run under a user context, so commands that require administrator privileges will fail. You can specify the container administrator account via the --user flag (i.e. docker run --user ContainerAdministrator) however **in the future we intend to fully remove administrator accounts from NanoServer.**

I'm going to resolve this as external.
