### ISSUE TITLE
$env:PATH casing on Linux is not consistent with $env:Path on Windows

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3571]
Steps to reproduce
------------------

Expected behavior
-----------------
You've changed casing for $env:PSModulePath on Linux to be consistent with Windows. I would expect the same for $env:Path. (or any other environmental variable that would exist on both platforms)

Actual behavior
---------------
$env:PATH on Linux and $env:Path on Windows

Environment data
----------------

```powershell
PS /home/aleksandar> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by jeffbi** [comment]
Case-sensitivity issues rise again!
`$PATH` and `$Path` are two different environment variables on Unix platforms. On Windows they are not.

**Comment by iSazonov** [comment]
It seems as bad UX. On Unix too: why use Path,PAth,PaTh,PatH for in the same time?! 
Related Issue #3573 about module names: MoDuLeNaMe?!
/cc @rkeithhill 

We should save PowerShell Engine on both platforms as case-insensitive but FileSystemProvider on Linux case-sensitive.

**Comment by mklement0** [comment]
To add to @jeffbi's comment: `$env:PSModulePath` is under PowerShell's control, `$env:Path` (Windows) / `$env:PATH` (Unix) is not.

It's unfortunate that these system-fundamental environment variables are defined differently across platforms (and that the case-sensitivity of accessing them varies), but I fear it's something we'll have to live with.

The workaround is to use `$env:PATH` consistently on all platforms, which will work on Windows too (due to its case-insensitive variable access).

**Comment by iSazonov** [comment]
The workaround is a working.

Only with each passing day I become more and more fear that consumers will curse us, if even two environment variables follow different rules!
For better UX we should follow simple and common rule, ex:
- PowerShell internally case-insensitive on both platforms.
- PowerShell externally case-sensitive on Unix
- PowerShell externally case-insensitive on both platforms but FileSystemProvider is case-sensitive on Unix
- ...

**Comment by joeyaiello** [comment]
Total agreement with @mklement0 on this one.

@iSazonov what do you mean by "externally" vs "internally"

**Comment by iSazonov** [comment]
Sorry, "internally" - I means PowerShell language, "externally" - file systems, environment variables, native commands and so on.

**Comment by jeffbi** [comment]
File system case-sensitivity should be filesystem-specific, not OS-specific. Windows _can_ be case-sensitive on NTFS volumes with the right Registry tweak, and if it can read/write Linux ext file systems, those are case-sensitive.

Even on Linux, FAT volumes are case-insensitive.

The HFS+ file system on OS X is _not_ case-sensitive

**Comment by mklement0** [comment]
Good points, @jeffbi; just to elaborate a little (do tell me if I'm wrong):

* NTFS:
  
   * _NTFS_ is intrinsically case-_sensitive_, whereas the _Windows API_ is not (by default).

   * Therefore, any software that _bypasses_ the Windows API can gain case-sensitive access, irrespective of the system configuration (such as the registry setting mentioned below) - this is what WSL, the Windows Subsystem for Linux that `bash` on Window is based on, does.

   * The registry tweak you mention - `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel`, value `obCaseInsensitive` - is the _prerequisite_ for enabling case-sensitivity _opt-in_ by the _Windows API methods_ via the `FILE_FLAG_POSIX_SEMANTICS
` flag.

* HFS+

  * While rarely seen in the wild, you _can_ create case-_sensitive_ volumes, but that decision is locked in _at volume creation time_ (e.g., with `newfs_hfs -s ...`).

**Comment by jeffbi** [comment]
@mklement0 I believe your points are correct. A couple of additional notes:
- Both Linux and OS X recognize NTFS volumes as case-sensitive and will allow creating files with names differing only in case but with different content. I've done this by plugging an NTFS external hard drive into both types of systems.
- Window can "see" all such files, but will only open one. For example, Windows Explorer shows both `Fred` and `fred`, but when opening either Windows will always actually open only one of them---it seems to favor ones with upper-case letters in the name.
![image](https://cloud.githubusercontent.com/assets/6708868/25109414/224a19e6-2391-11e7-812b-8a6d4507f011.png)
- I don't know what Windows will do with an ext volume, which is case-sensitive. I assume it will treat it as case-*in*sensitive, but I don't have an external ext volume handy to try it with, so I'm just guessing.

**Comment by SteveL-MSFT** [comment]
Going back to the original topic, we were able to change PSModulePath as that's an env var we create, but Path and PATH already exists in their respective operating systems.  We could have tab-complete always make Path uppercase as Windows will happily treat $env:PATH as $env:Path so at least script authors have a consistent variable for cross platform scripts, but it's not clear to me how many cross platform scripts will make use of PATH as absolute file paths are inherently different on different operating systems.

**Comment by iSazonov** [comment]
Can we use in scripts case-insensitive `$env:PAth` and do something like:
```
if (Unix)
   return env:PATH 
else
   return env:Path

**Comment by SteveL-MSFT** [comment]
@iSazonov since env vars are case sensitive on Unix, it possible (although improbable) that $env:PAth (or any variant) is a real env var used for some other purpose.  Perhaps we just define a set of $interop:PATH, $interop:TEMP, $interop:HOME, $interop:DOCUMENTS type variables that point to the correction values.

**Comment by iSazonov** [comment]
I agree. My thoughts were somewhere near.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, there is an RFC coming regarding env var management that should encapsulate this

**Comment by TSlivede** [comment]
Just an additional thought on `$interop:PATH`:

Could that variable have type ```System.Collections.Generic.List`1[System.IO.DirectoryInfo]``` ?

This way it would be easy to add things to the path, and one doesn't need to worry about using `:` of `;` as a separator.

Instead one could just do:
`$interop:PATH.Add('/some/path/')`

(The format of the path string gets even validated!)

**Comment by joeyaiello** [comment]
Just to add the trackback, we're looking at PowerShell/PowerShell-RFC#92 (and I need to add some details there that explain our current thoughts on this issue).

**Comment by SteveL-MSFT** [comment]
I'm going to defer this work to 6.1.0 since PATH and Path are different and aren't really cross platform compatible
