### ISSUE TITLE
Tab-completion for environmental variable on Linux returns non-existent env. variable

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3572]
Pressing TAB after `$env:P` returns `env:PATHEXT` that doesn't exist on PowerShell Core on Linux on my machine.

Steps to reproduce
------------------
PS /home/aleksandar> $env:P<tab>

Expected behavior
-----------------
```
PS /home/aleksandar> $env:P<tab>
PATH          PSModulePath  PWD
```

Actual behavior
---------------
```
PS /home/aleksandar> $env:P<tab>
PATH          PSModulePath  PWD           env:PATHEXT
```

Environment data
----------------

```powershell
PS /home/aleksandar> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by chuanjiao10** [comment]
$env:pathext or env:pathext return
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
no this environmental on linux.

yes! Deleting the variable PATHEXT on linux is better than clearing it,then just press the tab once

**Comment by iSazonov** [comment]
I believe we use `$env:pathext` to find native commands.
Perhaps we would enhance that on Unix.

/cc @mirichmo @andschwa Could you please comment?

**Comment by lzybkr** [comment]
PATHEXT is used to find native commands, but shouldn't be necessary on non-Windows systems.

I believe it's added to a cache of all special variables [here](https://github.com/PowerShell/PowerShell/blob/06020f34e556171b5ebd88155c3ff14e2cc1f5d8/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4853).

So I think the right fix is probably to add `#if !UNIX` around the "special" variables that are not used on Unix.

**Comment by iSazonov** [comment]
It was removed in #7697 but we continue discussing in #7755
