### ISSUE TITLE
on Linux, "gin" alias points to Get-ComputerInfo that's still unsupported

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell#3577]
Get-ComputerInfo isn't supported on Linux currently, however, `gin` alias points to it. `gin` alias should be removed (for now).

Steps to reproduce
------------------
```
PS /> gin
gin : The term 'Get-ComputerInfo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Expected behavior
-----------------
```
PS /> get-alias gin
get-alias : This command cannot find a matching alias because an alias with the name 'gin' does not exist.
```

Actual behavior
---------------
```
PS /> get-alias gin

CommandType     Name
-----------     ----
Alias           gin -> Get-ComputerInfo
```

Environment data
----------------

```powershell
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by iSazonov** [comment]
@joeyaiello @SteveL-MSFT Have we plans to port `Get-ComputerInfo` before RTM?

**Comment by joeyaiello** [comment]
I don't believe so. And really, if we're not planning to get it working, we shouldn't just remove the alias, we should remove the cmdlet.

**Comment by iSazonov** [comment]
@joeyaiello Please clarify - remove from Windows too?

**Comment by MaximoTrinidad** [comment]
Hum! How about to mimic the Linux command the series of commands to list the Linux distro system configurations?  

I don't think it need to be removed.  As long as it can point to these Linux commands:
lscpu
cat /proc/cpuinfo
cat /proc/meminfo
cat /proc/version
cat /etc/issue

That's my take!

**Comment by joeyaiello** [comment]
@iSazonov no, just on Linux. We've got plenty of cmdlets exported there that aren't exported on Linux, we should just add it to that list.

**Comment by joeyaiello** [comment]
@MaximoTrinidad I want to do that at some point, but it's really tricky considering how differently so much of that information is handled across distros/versions of Linux (especially in today's post-systemd world).

**Comment by iSazonov** [comment]
/proc is exposed by kernel so it would be "standard".

**Comment by joeyaiello** [comment]
Good to know. Unfortunately, my knowledge of Linux systems management is pretty ad-hoc, and I've personally never leveraged `/proc` (I just use the GNU utils that probably read from it). 

In any case, I think it's `up-for-grabs` and/or post-6.0.

**Comment by MaximoTrinidad** [comment]
Well, I think the Linux System Admin will definitely appreciate that there's a cmdlet that will provide system information on any Linux distros in a generic way. It really doesn't need to match Windows format. 
:)

**Comment by jeffbi** [comment]
`/proc` is standard on Linux, but not on OS X, which is BSD-based. There would need to be a completely different implementation to support OS X.

**Comment by alexandair** [comment]
@joeyaiello Get-ComputerInfo is already removed from Linux. I've opened this issue to remove the "gin" alias as well.

**Comment by joeyaiello** [comment]
@alexandair ah, gotcha. That makes a lot more sense. Yeah, let's just do that. Easy to fix.
