### ISSUE TITLE
Document what is supported is macOS

### ISSUE THREAD

**Issue by garysweaver** [PowerShell/PowerShell#3579]
Attempted to run a few PowerShell scripts I found online today with the macOS version of PowerShell, however, each failed. At this point, I'd go look in documentation for what is supported in the macOS version, but to get at that info I'd be digging through code.

Could you create a document that has a matrix of what features are supported and not supported for each target OS like macOS?

**Comment by joeyaiello** [comment]
It needs to be updated (I've got a WIP reivision in a fork right now, trying to hammer it out this week), but we have a known issues document here: https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md
