### ISSUE TITLE
PowerShell core on Linux - Get-Service should mimic linux "service" command.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3582]
Steps to reproduce
------------------
Type the cmdlet: Get-Service ssh
Or, Stop-Service ssh
Or, Start-Service ssh

Expected behavior
-----------------
  PowerShell    =>    Linux
Get-Service ssh => service --status-all
Start-Service ssh => service ssh start
Stop-Service ssh => service ssh stop

Actual behavior
---------------
Any of the three cmdlets will give the following errors:
xxx-service : The term 'xxx-service' is not recognized as the name of a cmdlet, function, script file, or operable
program.
![xx-service_2017-04-17_13-59-44](https://cloud.githubusercontent.com/assets/19892435/25098353/3867b74e-2376-11e7-83bb-d6a1f5aa2cf2.jpg)

Environment data
----------------
Linux Ubuntu Desktop 16.04.2

```powershell
PS /home/maxt> $PSVersionTable                                                                                          
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by joeyaiello** [comment]
Except that `service` is only available on systemd machines. That's why this is tricky. We basically need to implement this behavior two (or three or four) times.

**Comment by pat0s** [comment]
Hi, any new progress with implementing Start-Service for Linux? I would really appreciate it.

**Comment by brolifen** [comment]
6 years later and no change on this?

**Comment by ThomasNieto** [comment]
There is the [nxtools](https://www.powershellgallery.com/packages/nxtools/1.1.0) module that has wrappers for common Linux utilities.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/3582#issuecomment-294551258

@joeyaiello, almost all distributions nowadays use `systemd` for that same reason. Trying to automate initialization scripts across distributions was hellish until it standardized the API through its marketshare. Consequently, I would wholeheartedly accept an implementation which solely supported `systemd`. (Proponents of SysVInit etcetera could request or implement their own if it had any kind of extension system built in.)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/3582#issue-222187394

@MaximoTrinidad, why do you propose `service` rather than calling `systemctl`?

**Comment by priestapostate1208** [comment]
Okay - I thought there was something wrong with my PowerShell install onto Debian 12 - so it is a bit reassuring to see that I'm not the only person struggling with the "Get-Service" command.

If I'm understanding this correctly, there is no workaround for this?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/PowerShell/PowerShell/issues/3582#issuecomment-2270024182

@microsoft-github-policy-service, this should be reopened.
