### ISSUE TITLE
Set-PSReadlineKeyHandler fails with certain key chords on Unix

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3584]
Steps to reproduce
------------------

Define <kbd>Control</kbd> and <kbd>Alt</kbd>-key-based chords for doubling characters `'`, `"`, and `(` when typed with <kbd>Control</kbd> or <kbd>Alt</kbd> held down:

```powershell
Set-PSReadlineKeyHandler -Chord "Ctrl+'" { [Microsoft.PowerShell.PSConsoleReadLine]::Insert("''") }
Set-PSReadlineKeyHandler -Chord 'Ctrl+"' { [Microsoft.PowerShell.PSConsoleReadLine]::Insert('""') }
Set-PSReadlineKeyHandler -Chord 'Ctrl+(' { [Microsoft.PowerShell.PSConsoleReadLine]::Insert('()') }
Set-PSReadlineKeyHandler -Chord "Alt+'" { [Microsoft.PowerShell.PSConsoleReadLine]::Insert("''") }
Set-PSReadlineKeyHandler -Chord 'Alt+"' { [Microsoft.PowerShell.PSConsoleReadLine]::Insert('""') }
Set-PSReadlineKeyHandler -Chord 'Alt+(' { [Microsoft.PowerShell.PSConsoleReadLine]::Insert('()') }
```

Expected behavior
-----------------

The definitions should be accepted on all platforms and function as defined.
E.g. <kbd>Ctrl+'</kbd> should result in `''`.

Actual behavior
---------------

On Windows, the actual behavior matches the expected behavior.

On Unix platforms (verified on macOS 10.12.4 and Ubuntu 16.04 with the respective default terminal applications), the definitions fail with (repetitions of) the following error messages (note that omitting modifier keys `ctrl` and `alt` from the definitions would work fine):

```
Set-PSReadlineKeyHandler : Unrecognized key 'ctrl'. Please use a character literal or a well-known key name from the System.ConsoleKey enumeration.
Set-PSReadlineKeyHandler : Unrecognized key 'alt'. Please use a character literal or a well-known key name from the System.ConsoleKey enumeration.
```

The error messages suggest that `ctrl` / `alt` are not recognized as _modifier keys_ in this case.

Note that something like `Ctrl+A` _does_ work, however; the problem appears to be the specific characters (`'`, `"`, `(`) that the modifiers are paired with.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

**Comment by joeyaiello** [comment]
This issue was moved to lzybkr/PSReadLine#529

**Comment by joeyaiello** [comment]
Tracking this in the PSReadline project.

**Comment by axbender** [comment]
Using PowerShell 6.0 and PSReadline 2.0, the following binding fails for me in Windows 7:

Set-PSReadlineKeyHandler -Chord "Ctrl+." ...

This might be a problem with PowerShell 6.0 as the AltGr key mappings for the German keyboard don't work, e.g. AltGr+8 wouldn't result in "["...

Being new to PS6, is this expected/worked on?

**Comment by axbender** [comment]
Using PowerShell 6.0 and PSReadline 2.0, the following binding fails for me in Windows 7:

Set-PSReadlineKeyHandler -Chord "Ctrl+." ...

This might be a problem with PowerShell 6.0 as the AltGr key mappings for the German keyboard don't work, e.g. AltGr+8 wouldn't result in "["...

Being new to PS6, is this expected/worked on?

Btw., is there a way to specifiy e.g. [ConsoleKey]::OemPeriod in the chord?, and, what is the -Key parameter which is not described but "exampled" in the help page?
