### ISSUE TITLE
Pre-Pull Request Testing Needed for New Bash Installer

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#3586]
I am an intermediate-noob at bash so I would love to have some testing of the new installer before doing a pull request.

The goals and overall idea is described in #3547 

## Features (and fixes of download.sh):
* Bare minimum requirements to get going (wget & sed) (attempts to install curl if not present)
* defaults to only install PowerShell core (using repos where they are available)
* For non-repo based installs - detects latest version from git tags
* Optional -includeide switch installs VS Code and PowerShell Extension (using repos where they are available)
* Fix/Cleanup: Installs on OpenSUSE using download from regular github releases page (until repo is established)
* Removed restriction to OpenSUSE 42.1, should install 42.1 and later.
* Removed restriction to CentOS only - should install on Redhat as well.

## I have it working and tested under:
* Ubuntu Desktop 16.04
* CentOS 7.2 with GNOME Desktop
* OpenSUSE 42.2 with KDE Desktop

## Known Issues (and Help Needed):
* The -appimage switch just calls the pre-existing appimage.sh which did not work on any of the above test cases
* The OSX install was pieced together from various sources and is untested.

Here is the readme: https://github.com/DarwinJS/PowerShell/blob/feature/install-powershell.sh/tools/install-powershell.readme.md

### Only Install PowerShell Core:
```bash
bash <(wget -O - https://raw.githubusercontent.com/DarwinJS/PowerShell/feature/install-powershell.sh/tools/install-powershell.sh)
```
###  Install PowerShell Core with IDE:
```bash
bash <(wget -O - https://raw.githubusercontent.com/DarwinJS/PowerShell/feature/install-powershell.sh/tools/install-powershell.sh) -includeide
```
###  Install PowerShell Core with IDE and do tests that require a human to interact with the install process:
```bash
bash <(wget -O - https://raw.githubusercontent.com/DarwinJS/PowerShell/feature/install-powershell.sh/tools/install-powershell.sh) -includeide -interactivetesting
```

**Comment by MaximoTrinidad** [comment]
Hey @DarwinJS,

Please help understand. What does it means "PowerShell Core with IDE"? 
I'm also a noob in Linux. 
:)

**Comment by DarwinJS** [comment]
@MaximoTrinidad - IDE = Integrated Development Environment.  In this case it means adding Visual Studio Code and the PowerShell Language Plug-in for vs code.

I'm a bash noob, but I've been doing hands on Linux LAMP administration for my own servers for over 15 years - just have not done a lot of bash for automation ;)

**Comment by MaximoTrinidad** [comment]
Ah! That's what I was trying to understand IDE with VS Code. So, you'll be using a VS Code Extension to perform the PowerShell upgrade. I think that a good thought!

:)

**Comment by DarwinJS** [comment]
@MaximoTrinidad - the IDE is optional and does not have anything to do with the initial install of PowerShell.  If and only if you give the -includeide switch, the script installs vs code and powershell vs code extension so you can edit and debug powershell on the linux machine similar to how you do in PowerShell ISE on a Windows machine.

**Comment by DarwinJS** [comment]
This is done and integrated.
