### ISSUE TITLE
Could not load file or assembly 'Microsoft.CSharp

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3587]
After moving to .Net Core 2.0 I build PowerShell by `Start-PSBuild -Clean`, I can build successfully but PowerShell dont start:
```
PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

The shell cannot be started. A failure occurred during initialization:
Could not load file or assembly 'Microsoft.CSharp, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

```

I see in AddType.cs "Microsoft.CSharp, Version=4.0.0.0" but in autogenerated CorePSTypeCatalog.cs "Microsoft.CSharp, Version=4.0.3.0"

Also in ActivityGenerator.cs and WebServiceProxy.cs we would mask `using Microsoft.CSharp;` by `#if !CORECLR`.

/cc @daxian-dbw

**Comment by anmenaga** [comment]
+1
I observe the same initialization error on Windows 10 Enterprise.

**Comment by SteveL-MSFT** [comment]
@daxian-dbw tells me this is a bug in dotnet, current workaround is to always use `-publish`

**Comment by daxian-dbw** [comment]
When not specifying `-publish` with `Start-PSBuild` (using 'dotnet build'), the TPA list used by the host powershell.exe (dotnet.exe actually) contains a path to the incorrect `Microsoft.CSharp.dll`, which is of version `4.0.2.0`.
I'm about to update the build script to always use `dotnet publish`. I will also open an issue in dotnet/corefx or dotnet/cli.

**Comment by daxian-dbw** [comment]
The dotnet/cli issue is https://github.com/dotnet/cli/issues/6352

**Comment by adityapatwardhan** [comment]
When using -publish I can successfully build and launch powershell. But launching using Start-DevPowershell does not work. It does not point to the publish directory.
