### ISSUE TITLE
Compress-Archive is stripping UNIX file permissions

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3590]
Steps to reproduce
------------------

```powershell
Set-Content -Path mytestfile.txt -Value testing
Compress-Archive -Path mytestfile.txt -Destination mytestzip.zip
zipinfo mytestzip.zip
```

<details>
 <summary>Result of zipinfo command</summary>

```
Archive:  mytestzip.zip
Zip file size: 136 bytes, number of entries: 1
?---------  2.0 unx        8 b- defN 17-Apr-18 12:23 mytestfile.txt
1 file, 8 bytes uncompressed, 10 bytes compressed:  -25.0%
```
</details>

Expected behavior
-----------------

Permissions of files are retained upon compression into ZIP format.

Actual behavior
---------------

Permissions are not preserved when files are compressed.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
PS /> uname -a
Darwin 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
@SteveL-MSFT Please prioritize this appropriately. This is requiring me to resort to calling the native `zip` command, which is less preferable to using `Compress-Archive`. I'm not sure if this is an issue with .NET Core or PowerShell Core, but it's manifesting itself in PowerShell Core, so this is the logical place to start. 

@BrucePay @daviwil

**Comment by MaximoTrinidad** [comment]
Hum! What about when moving the compress file cross-platform? Or, when been attached to an email?
Is it going to keep permission from a Linux to a Windows filesystem, or the way around?

What's the catch? 
:)

**Comment by SteveL-MSFT** [comment]
@pcgeek86 please open this issue in the [Archive Module repo](https://github.com/PowerShell/Microsoft.PowerShell.Archive).  If the native zip cmd retains the permissions (presumably if uncompressed on Windows it throws it away?), then we can do something as long as the underlying .Net api we're using supports it

**Comment by pcgeek86** [comment]
@SteveL-MSFT Yep, took care of it. See new ticket.

**Comment by MartyIX** [comment]
I hit the same issue as well. I know there is https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/36 but that repo is not [actively maintained](https://github.com/PowerShell/Microsoft.PowerShell.Archive?tab=readme-ov-file). 

Should this issue be reopened then?
