### ISSUE TITLE
Decrypting DSC Credentials not working

### ISSUE THREAD

**Issue by aboersch** [PowerShell/PowerShell#3591]
Steps to reproduce
------------------
Create a MOF using a DSC Resource that uses a PSCredential on one Windows Server 2016 Machine using a certificate File then apply it on a Windows Server 2016 computer that has the private key for the certificate file under the local machine my store.

Expected behavior
-----------------
Decrypt the credentials and use them to access a file share

Actual behavior
---------------
I have created a Pull Server Configuration. I have created the DSC Signing Certificate using a custom template on a Enterprise Root CA which has worked for 2012R2 nodes and also tested using xDSCUtils New-xSelfSignedDscEncryptionCertificate.
I kept getting errors when passing in credentials. I therefore wrote a tiny custom DSC Resource that Displays the Password as clear txt when I run Start-DSCConfiguration -Wait -Verbose
You can find it [here](https://gist.github.com/aboersch/65e846a4966fe2c4708ed21d655a54a7)
The Client does not correctly decrypt the Credentials. As a Password I am receiving
```powershell
-----BEGIN CMS-----
<Long Multi-Line Base64 String>
-----END CMS-----
```

If I pass this to Unprotect-CmsMessage I receive the correct Password.
The Certificate passes $.PrivateKey.KeyExchangeAlgorithm and $.Verify
I have tried changing the Certificate Provider to '"Microsoft Enhanced Cryptographic Provider v1.0"', '"Legacy Cryptographic Service Provider"', and '"Microsoft RSA SChannel Cryptographic Provider"'.
I have already tried these: 
[DSC problems with Credentials and build 10586](http://stackoverflow.com/questions/34006865/dsc-problems-with-credentials-and-build-10586)
https://wespoint.wordpress.com/2017/01/19/powershell-dsc-encryption-issue/

Environment data
----------------
Both Systems are Windows Server 2016 from Azure with identical PSVersionTables

```powershell
> $PSVersionTable
Name                           Value                                                                                                                  
----                                -----                                                                                                                  
PSVersion                      5.1.14393.1066                                                                                                         
PSEdition                      Desktop                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                
BuildVersion                   10.0.14393.1066                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                        
WSManStackVersion              3.0                                                                                                                    
PSRemotingProtocolVersion    2.3                                                                                                                    
SerializationVersion           1.1.0.1  
```

Please find attached the certificate that I used. Pfx Password is "Password"

[test.zip](https://github.com/PowerShell/PowerShell/files/930971/test.zip)

**Comment by SteveL-MSFT** [comment]
@aboersch thanks for the report, but DSC is not part of this repository.  Please open your issue on [UserVoice](https://windowsserver.uservoice.com/) so that it gets the right attention
