### ISSUE TITLE
Sort-Object doesn't respect `-` as a symbol when sorting strings

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3593]
[Filed on UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/18580849-bug-sort-is-incorrect-for-strings-containing-the#comments), repros on both 5.1 and the latest 6.0-alpha.18. 

Steps to reproduce
------------------
```powershell
"somefile1","somefile2","s-abc","s-little","s-foo","s-poo","s-wtf" | Sort-Object
```

Expected behavior
-----------------
```
s-abc 
s-foo 
s-little 
s-poo 
s-wtf 
somefile1 
somefile2
```

> Note: this is actually the behavior already when using other symbols like `_`:

```
"somefile1","somefile2","s_abc","s_little","s_foo","s_poo","s_wtf" | Sort-Object
s_abc 
s_foo 
s_little 
s_poo 
s_wtf 
somefile1 
somefile2
```

Actual behavior
---------------
```
s-abc 
s-foo 
s-little 
somefile1 
somefile2 
s-poo 
s-wtf
```

Environment data
----------------

```
Name                           Value
----                           -----
SerializationVersion           1.1.0.1
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSEdition                      Core
WSManStackVersion              3.0
CLRVersion
GitCommitId                    v6.0.0-alpha.18

```

**Comment by iSazonov** [comment]
@joeyaiello This s dup #3425 and it is External bug 😕

**Comment by joeyaiello** [comment]
Wow, you're good. Leave a comment next time in the UV item and I'll make sure not to re-file? 😉

**Comment by iSazonov** [comment]
Clear. It is good workflow.
