### ISSUE TITLE
Get-Random unexpectedly outputs [double] values with various integer types

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3598]
Steps to reproduce
------------------

The following uses variations of `Get-Random 1` to produce a number in the interval `[0,1)`, which for any integer type should invariably yield `0`:

```powershell
[sbyte], [byte], [int16], [uint16], [int], [uint32], [int64], [uint64] | % {
  [pscustomobject] @{
    TypeIn = $_.Name
    Result = Get-Random ($_::Parse(1))
    TypeOut = (Get-Random ($_::Parse(1))).GetType().Name
  }
}
```

Expected behavior
-----------------

```
TypeIn            Result TypeOut
------            ------ -------
SByte                  0 SByte 
Byte                   0 Byte 
Int16                  0 Int16 
UInt16                 0 UInt16
Int32                  0 Int32  
UInt32                 0 UInt32 
Int64                  0 Int64  
UInt64                 0 UInt64 
```

Actual behavior
---------------

Something like:

```
TypeIn            Result TypeOut
------            ------ -------
SByte  0.412813293008512 Double 
Byte   0.117663220557227 Double 
Int16  0.326887441485602 Double 
UInt16 0.502738704207697 Double 
Int32                  0 Int32  
UInt32 0.995645226908683 Double 
Int64                  0 Int64  
UInt64  0.39285415708686 Double 
```

Note how only `[int32]` and `[int64]` correctly output a (type-preserved) integer.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

**Comment by iSazonov** [comment]
With code side it is "by design" not "unexpectedly". So should we change the design?

**Comment by mklement0** [comment]
@iSazonov:

The existing [documentation](https://msdn.microsoft.com/en-us/powershell/reference/5.0/microsoft.powershell.utility/get-random) _partially contradicts_  current behavior:

> Enter a 32-bit integer or a double-precision floating-point number, or an object that can be converted to an integer or double

If we assume that "to an integer" means to an `[int32]`, then certainly the _smaller_ integer types would qualify for that conversion - but that's not what's happening currently.

Under the same assumption, you could argue that the _larger_ integer types only fit into `[double]` and that the docs therefore do match current behavior for these types - I still find that behavior counter-intuitive, however.

I think that a change is warranted from a common-sense standpoint, and that the change falls into [bucket 3 - unlikely grey area]( https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).

**Comment by iSazonov** [comment]
@mklement0 I mean only that the code make this _explicity_ and it is not bug. 
Is "Expected behavior" that you want to get _precisely_ or you want to get int32 for small "integers"?

**Comment by mklement0** [comment]
@iSazonov:  That's fine, as long as there's agreement that the behavior is counter-intuitive (which is what I meant by "unexpected").

I think getting the precise type back makes sense, but I'm not sure I'm aware of all the ramifications.

(As an aside: It's open to debate whether the [source code](https://github.com/PowerShell/PowerShell/blob/02b5f357a20e6dee9f8e60e3adb9025be3c94490/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs#L385) reflects deliberate intent to treat the less common integer types not explicitly mentioned as `[double]`, or whether that was a mere oversight.)
