### ISSUE TITLE
Publish runtime 6.0 assemblies to Nuget

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3599]
Talked about this in today's team meeting. In addition to the reference/scaffolding assemblies we're building in #3095, we should publish the runtime 6.0 assemblies to Nuget (in addition to MyGet).

**Comment by Mattacks** [comment]
@joeyaiello Hi.
Any ETA on things being properly published in NuGet? We (especially our legal departments) don't like referencing alternative NuGet repositories.
Matt

**Comment by joeyaiello** [comment]
@Mattacks looks like you found #6475, so I'm going to close this one as a dupe.

No ETA unfortunately, but it is still high in our queue pending some more urgent work.
