### ISSUE TITLE
Complex Data Format Linters?  Test-Json, Test-yaml, Test-xml, Test-CSV

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#3613]
Sure would be nice to be able to do basic validation of the syntax fussy data formats in code - and even in the console not having to use an editor or website.

I do *not* mean to imply that powershell do broadbased syntax checking of other things - just these very common data formats that are syntax heavy and that we have to work with a lot.

**Comment by iSazonov** [comment]
I believe Test-CSV is impossible - what is formal rules?
Test-Json and Test-xml can be implemented - we have all for that.
Test-yaml only once we receive support for YAML in PowerShell.

**Comment by BrucePay** [comment]
@DarwinJS what form do you see this talking? The various import and convert commands already validate that documents are well-formed. Are you talking about schema validation? Better errors?

**Comment by DarwinJS** [comment]
@iSazonov - I know that csv does not have a published standard, but tools like CSVEdit (http://csved.sjfrancke.nl/) have been successful at collecting all the "common formats in the wild".  However, I'm not really hung on that one - it's these others that I have to deal with much more often.

@BrucePay - I am thinking "dedicated test- CMDLets"  (if "test-" is the right verb to use for well-formed validations) to expose this functionality so that:
- I can easily discover this functionality.
- I can be sure to only receive errors of the format validation (execution of the general CMDLets could be emitting errors for many conditions and I don't know how many different validation errors it might be capable of emitting).  Especially important when I as the script author am not the author of the formatted input data.
- I can be given the exact position in the data where the error occurs - like I am used to in online linters - this may already be part of the built-in check, but if it is not for any given command, that test-whatever would be diligent in surfacing that information.

Although I think a CMDLet is more discoverable, if providing a CMDLet is difficult, perhaps "Convert-ToYaml -validateonly"

I haven't wrapped my head around this enough to know if validation errors are all that the "Convert-" CMDLets output?  But even if so, I would still say that having dedicated cmdlets would help people understand that better and through broader use feedback might improve the quality of the validation code.

In general it seems like there could be a lot more "Test-" CMDLets across all of powershell.

**Comment by iSazonov** [comment]
Test-Json was added.

**Comment by jasonchester** [comment]
+1 to better handling of CSV files.

While not an official standard there are best practices published and commonly accepted 
* https://www.ietf.org/rfc/rfc4180.txt 
* https://www.w3.org/TR/tabular-data-primer/ & https://github.com/w3c/csvw

Test-CSV is certainly possible as there are a number of tools in that space already 
* http://csvlint.io/ & https://github.com/theodi/csvlint.rb
* https://csvkit.readthedocs.io/en/1.0.3/scripts/csvclean.html#
* https://github.com/slashbit/csv-lint
* https://github.com/Clever/csvlint
