### ISSUE TITLE
Question / Potential Bug: Redirection for native command StdErr output

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3617]
Overview
------------------

I'm not sure if this is a bug or expected behavior, but I'm fairly certain I'm doing this right. Basically I'm trying to suppress any output from appearing in the PowerShell host. To do this, I'm attempting to redirect the StdErr stream to the PowerShell Output stream, and then assigning the consolidated result to `$null`.

I can't seem to figure out how to prevent a native UNIX command from printing StdErr to the host.

Steps to reproduce
------------------

```
$TempPath = '{0}/pythontemptrevor' -f $HOME
mkdir $TempPath
$null = pip install --target $TempPath pip
$null = pip install --target $TempPath pip 2>1
```

Expected behavior
-----------------

No output is printed to stderr.

Actual behavior
---------------

* Output is printed to stderr (I think).
* A file named `1` is created.

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Cheers,
Trevor Sullivan

**Comment by iSazonov** [comment]
Right format is "2>&1".
Great article from June Blender https://blogs.technet.microsoft.com/heyscriptingguy/2014/03/30/understanding-streams-redirection-and-write-host-in-powershell/

Also you can create a runspace without host and use it streams.

**Comment by SteveL-MSFT** [comment]
`2>1` means redirect stderr to a file called `1`.  `2>&1` means redirect stderr to stdout.

**Comment by pcgeek86** [comment]
I knew I was doing something wrong. :) Thanks!
