### ISSUE TITLE
Get/Set-Clipboard command missing from PowerShell Core Edition on Mac

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3618]
PowerShell Core Edition doesn't have a `Set-Clipboard` command. I've tried using `pbcopy` on Mac OS X, but it doesn't seem to work well with certain UTF-8 characters, like emojis. For example, using my Emojis PowerShell module, on the PowerShell Gallery, the `pbcopy` command pastes an emoji into my web browser as a question mark.

Having a high-quality `Set-Clipboard` command would be convenient from a first-class PowerShell perspective, and resolving bugs similar to those with `pbcopy`.

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
Related ticket: https://github.com/PowerShell/PowerShell/issues/3177

**Comment by iSazonov** [comment]
From @SteveL-MSFT:
>At this time the Clipboard cmdlets are not compatible with PSCore6 as it depends on a System.Windows.Forms class which isn't part of corefx and would not be cross platform compatible.

>I do think the clipboard cmdlets are useful, but should be a separate module that is cross platform compatible which may require different code paths per OS.

**Comment by iSazonov** [comment]
@pcgeek86 Could you make the Issue more common and change the title to "Get/Set-Clipboard commands missing from PowerShell Core"?

**Comment by BrucePay** [comment]
pbcopy/pbpaste should work. @pcgeek86 Have you investigated to see if this is an encoding problem? It would be nice if Out-Clipboard could just be an alias to pbcopy.

**Comment by mklement0** [comment]
It is indeed an encoding issue: because `$OutputEncoding` defaults to ASCII, any non-ASCII chars. are converted to _literal_ `?` chars:

     > 'ö' | pbcopy; pbpaste | od -tx1
     0000000    3f  0a                                                        
     0000002

`3f` is literal `?` (and `0a` is `\n`).

If you set `$OutputEncoding` to BOM-less UTF-8, it works:

     > & { $OutputEncoding = [System.Text.Utf8Encoding]::New(); 'ö' | pbcopy; pbpaste | od -tx1 }
     0000000    c3  b6  0a                                                    
     0000003

`c3 b6` is the UTF-8 encoding of `ö`, proving that the value was copied correctly.

**Comment by SteveL-MSFT** [comment]
Please use https://www.powershellgallery.com/packages/ClipboardText
