### ISSUE TITLE
The Universal Openssh Installer

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#3621]
Major documentation upgrade and reorganization to try to surface the fact that the Universal Installer also supports Chocolatey ;) 

https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md

**Comment by SteveL-MSFT** [comment]
Perhaps an implementation of the [Enable-SSHRemoting RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0012-Enable-SSH-Remoting.md) can leverage this

**Comment by DarwinJS** [comment]
Sounds interesting.  I would be keen to understand what happens if openssh is installed for one of the purposes (regular or SSHRemoting) and then someone runs the installer to configure the other scenario.  Definitely, if both scenarios were managed in the same installer there would be a better chance that something sensible would happen :)

**Comment by SteveL-MSFT** [comment]
I would think your installer only serves to install OpenSSH (perhaps check if it's already installed).  Enable-SSHRemoting would handle additional configuration for PowerShell remoting over SSH.

**Comment by SteveL-MSFT** [comment]
cc @PaulHigin

**Comment by DarwinJS** [comment]
I have blogged the universal installer with some more details here: https://cloudywindows.com/post/unveiling-the-openssh-universal-automated-installer/
