### ISSUE TITLE
Enabling process start with other priority than normal

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#3627]
It would be great to be able to specify the priority a started process should run with.

This is hard from PowerShell today without coding .NET.

compare to cmd's `start /belownormal`

**Comment by iSazonov** [comment]
.Net Core supports [Process.PriorityClass](https://apisof.net/catalog/System.Diagnostics.Process.PriorityClass).

**Comment by powercode** [comment]
This should also be easy to add, since we already has all the code to start the process suspended for hooking it up to a job.
