### ISSUE TITLE
Write-Error in a function doesn't set automatic success variable $? to $False (doesn't set the execution status to indicate a non-terminating error) in the caller's scope

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3629]
`Write-Error` is used to signal a non-terminating error, yet `$?` (the execution-status automatic variable) isn't set to `$False` in the _caller's_ scope when it is called from an (advanced) function.

By contrast, if you use `$PSCmdlet.WriteError` from an advanced function, it is.

Steps to reproduce
------------------

```powershell
function foo { Write-Error 'oh no' }; foo; $?
function foo2 { [cmdletbinding()] param() $PSCmdlet.WriteError((New-Object System.Management.Automation.ErrorRecord "oh no", $null, 'NotSpecified', $null)) }; foo2; $?
```

Expected behavior
-----------------

```powershell
# (error details omitted)
$False
# (error details omitted)
$False
```

Actual behavior
---------------

```powershell
# (error details omitted)
$True
# (error details omitted)
$False
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

**Comment by iSazonov** [comment]
Related #3359

**Comment by mklement0** [comment]
@iSazonov: Re typo (assuming you meant the prompt placeholders, `> `): done.

**Comment by mklement0** [comment]
@iSazonov: 

Re as-designed: 

This issues is about the ability for an (advanced) function, _as a functional unit_, to signal _to the caller_ that a non-terminating error has occurred.

While you _can_ do that with `$PSCmdlet.WriteError()`, it is quite cumbersome.

What I'm suggesting is that `Write-Error` set `$?` to `$False` in the _caller's_ scope _on returning from the function_. I've updated the title and first post to clarify that.

**Comment by iSazonov** [comment]
Typo:
`function foo { Write-Error 'oh no' }; $?` vs `function foo { Write-Error 'oh no' }; foo; $?`

**Comment by mklement0** [comment]
@iSazonov Ah, got it, thanks - updated.

**Comment by BrucePay** [comment]
Perhaps $? should be all scope.

**Comment by mklement0** [comment]
@BrucePay: 

Making the variable `-Option AllScope` is problematic, because it would restrict use of `Write-Error` to the very last statement of the function / script (and `Write-Error` itself would then have to not reflect _its_ success in `$?`), so that subsequent statements don't overwrite it.

`$PSCmdlet.WriteError()` already works as expected:

* it sets `$?` in the _caller's_ scope, wherever it is used in the script / function's body

* while leaving the _local_ copy untouched, so that the remainder of the script / function can continue to make use of it to determine the success of calling other commands.

I haven't looked at the code yet, but it sounds like it shouldn't be too hard to make `Write-Error` behave the same way.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We agree there is a need for a script or pipeline to have a way to set `$?` but should not change the current behavior of `Write-Error` which would be a breaking change.  Proposals were discussed in https://github.com/PowerShell/PowerShell/issues/10917
