### ISSUE TITLE
Need OSX install bash commands for installing PowerShell and VSCode using Homebrew

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#3632]
@joeyaiello - in the community call someone was talking about homebrew and it sounded like they might know the steps to get PowerShell Core and VS Code installed using homebrew.

Could anyone who knows how to do this please post the script code bits to this issue so I can add them to install-powershell.sh ?

**Comment by DarwinJS** [comment]
Anyone from the recent community call have the code to do this?

**Comment by vors** [comment]
```
brew cask install powershell
brew cask install visual-studio-code
```

**Comment by DarwinJS** [comment]
@vors - thanks!  
I was hoping for a script similar to the existing download.sh that accounds for a clean machine that's never had brew on it, etc.

However, I also don't find those package names at http://braumeister.org/ - am I misunderstanding braumeister.org ?
