### ISSUE TITLE
Powershell scripted package is not working while deployed using HPSA tool 

### ISSUE THREAD

**Issue by CKGanesh** [PowerShell/PowerShell#3642]
We are trying to deploy elastic search 2.3.2 package using HPSA tool in windows server 2012. The installation script is written using powershell. When I am trying to manually install the package using the scripts, it is working flawlessly. But when I am trying to deploy the package using HPSA tool, the logs are showing that the deployment is executed.But the installation bat file in the package is not getting executed and it is failing to install elastic search in machine. I tired changing different execution policy in machine, but it is not resolving the issue. Please help me out , since many days of testing is getting delayed due to this

**Comment by SteveL-MSFT** [comment]
Will need more info to understand what the problem is.  HPSA is the HP Support Assistant tool?  What error are you getting?  Did you try HP support?

**Comment by CKGanesh** [comment]
Hi Steve, HPSA is HP server automation. We didnt reach out HP yet for checking the issue. 

The code snippet will be somewhat like this

"Invoke -cmd   'Packagepath/bin/service.bat' Install   "
"Invoke -cmd   'Packagepath/bin/service.bat' Start"

The above snippet should start elastic search as windows service.When I am doing it manually, it is getting created. But When I am deploying the package via HPSA, the software is not getting installed and there is no specific error in logs also

**Comment by chuanjiao10** [comment]
@CKGanesh ：
bat is script for cmd.exe . show us  **powershell command** in this *.bat first.

use this format:

```
Steps to reproduce
------------------

Expected behavior
-----------------

Actual behavior
---------------


```
