### ISSUE TITLE
Defining the $ErrorView preference variable in the current scope does not take effect (only in parent scope)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3645]
Preference variables generally take effect in the scope in which they're defined, which appears not be  the case for `$ErrorView`, which only honors it in an ancestral scope:

Steps to reproduce
------------------

```powershell
& { Set-Variable -Scope 0 VerbosePreference Continue; Write-Verbose 'I will display.' }
& { Set-Variable -Scope 0 ErrorView CategoryView; Get-Item /NoSuchItem }
& { Set-Variable -Scope 1 ErrorView CategoryView; Get-Item /NoSuchItem }
```

Note: To re-run the test, start a new session, because the last command sets `$ErrorView` in the global scope.

Expected behavior
-----------------

```powershell
I will display.
ObjectNotFound: (/NoSuchItem:String) [Get-Item], ItemNotFoundException
ObjectNotFound: (/NoSuchItem:String) [Get-Item], ItemNotFoundException
```

Actual behavior
---------------

```powershell
I will display.
Get-Item : Cannot find path '/NoSuchItem' because it does not exist.
At line:1 char:54
+ ... t-Variable -Scope 0 ErrorView CategorizedView; Get-Item /NoSuchItem }
+                                                    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/NoSuchItem:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
ObjectNotFound: (/NoSuchItem:String) [Get-Item], ItemNotFoundException
```

Setting `$ErrorView` in the same scope as the failing `Get-Item` command didn't take effect - contrast this with the `$VerbosePreference` variable.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

**Comment by atkinsroy** [comment]
Same here with V7.1.3. Further testing:
`& { $ErrorView ; Set-Variable ErrorView 'ConsiseView' -Option AllScope  ; 1/0 ; $ErrorView }`
This doesn't work either. It changes the variable in the current scope only but also ignores it in preference for the parent scope setting.

The following does work, but you are changing the parent scope variable. In my case this is what I wanted to do:
`& { $ErrorView; $global:ErrorView = 'ConciseView; 1/0 ; $ErrorView }
NormalView
ConciseView
RuntimeException: Attempted to divide by zero.
ConciseView`

So I guess the answer is, grab the current setting of ErrorView, change it in your script using $global to do what you want it to do, then change ErrorView back at the end.

**Comment by rkeithhill** [comment]
I was just testing the addition of a new error view `DetailedView` on a PR branch and noticed the same thing.

**Comment by 5HT2** [comment]
Was this ever resolved?
