### ISSUE TITLE
PowerShell class instance methods cannot run concurrently

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#3651]
This behavior changed between PowerShell versions 5.0 and 5.1.  The change was to make PowerShell class method script blocks bound to the runspace in which they were created.  If a class instance method is run from within a different runspace then it gets "marshaled" back to the original runspace (via engine events).  The result is that if a single class instance is shared among multiple runspaces (e.g., a runspace pool) with the intention to execute instance methods concurrently, the methods run serially instead.

I don't know why this changed between 5.0 and 5.1 but it looks to be by design.  @vors  can you please comment?

Repro steps:
```powershell
PS > (measure-command { .\RunspaceInstanceTest.ps1 }).TotalSeconds

RunspaceInstanceTest.ps1 file script:
class Writer
{
    static WriteLineS([string] $Msg)
    {
        for ($i=0; $i -lt 10; $i++)
        {
            [Console]::WriteLine("Static: Loop $i - $Msg")
            Start-Sleep -MilliSeconds 100
        }
    }

    WriteLineI([string] $msg)
    {
        for ($i=0; $i -lt 10; $i++)
        {
            [Console]::WriteLine("Instance: Loop $i - $Msg")
            Start-Sleep -MilliSeconds 100
        }
    }
}

$script = @'
    param ([object] $writerInstance, [string] $Title)

    class Writer
    {
        static WriteLineS([string] $Msg)
        {
            for ($i=0; $i -lt 10; $i++)
            {
                [Console]::WriteLine("Static: Loop $i - $Msg")
                Start-Sleep -MilliSeconds 100
            }
        }

        WriteLineI([string] $msg)
        {
            for ($i=0; $i -lt 10; $i++)
            {
                [Console]::WriteLine("Instance: Loop $i - $Msg")
                Start-Sleep -MilliSeconds 100
            }
        }
    }

    # Create new instance
    #$writerInstance = [Writer]::new()

    # Instance write
    $writerInstance.WriteLineI("$Title")

    # Static write
    #[Writer]::WriteLineS("$Title")
'@

$writer = [Writer]::new()

$rsp = [runspacefactory]::CreateRunspacePool(1, 10, $host)
$rsp.Open()

class Task
{
    [powershell] $powershell
    [System.IAsyncResult] $Async
}

$tasks = @()

1..5 | foreach {

    $task = [Task]::new()
    $tasks += $task

    $task.powershell = [powershell]::Create()
    $task.powershell.RunspacePool = $rsp
    $task.Async = $task.powershell.AddScript($script).AddArgument($writer).AddArgument("Task $_").BeginInvoke()
}

foreach ($task in $tasks)
{
    $task.powershell.EndInvoke($task.Async)
    $task.powershell.Dispose()
}

$rsp.Dispose()

```
Expected:
5 concurrently running 1 second loops (with sleep) should take about 1 second to run.

Actual Result:
It takes about 5 seconds to run indicating that the concurrent scripts are running serially.

**Comment by SteveL-MSFT** [comment]
Per @vors, the primary reason for the change is to have consistent and predictable behavior.  Runspaces have state and when defining a class, it uses that state so it makes sense to bound it to a specific runspace.  Otherwise you will have unexpected behavior like static fields shared across runspaces without synchronization or getting more than one type when expecting one.

We should revisit this as part of the effort to target developers in 6.1.0 timeframe

**Comment by joeyaiello** [comment]
Changing to enhancement given the scope of this work (and the investigation required; I don't believe we know how to solve this today).

**Comment by daxian-dbw** [comment]
There is a workaround to allow users to intentionally create a PowerShell class instance that is not bound to any Runspaces. PR #3871 add tests to cover this scenario.

A generic version of `New-UnboundClassInstance`:
```
# Module CreateClassInstanceHelper.psm1
$Script:powershell = $null
$Script:body = @'
    function New-UnboundClassInstance ([Type] $type, [object[]] $arguments) {
        [activator]::CreateInstance($type, $arguments)
    }
'@
 
function Initialize {
    ## A runspace is created and NO powershell class is defined in it
    $Script:powershell = [powershell]::Create()
    ## Define a function in that runspace to create an instance using the given type and arguments
    $Script:powershell.AddScript($Script:body).Invoke()
    $Script:powershell.Commands.Clear()
}
 
function New-UnboundClassInstance ([Type] $type, [object[]] $arguments = $null)
{
    if ($Script:powershell -eq $null) { Initialize }
 
    try {
        ## Pass in the powershell class type and ctor arguments and run the helper function in the other runspace
        if ($arguments -eq $null) { $arguments = @() }
        $result = $Script:powershell.AddCommand("New-UnboundClassInstance").
                                     AddParameter("type", $type).
                                     AddParameter("arguments", $arguments).
                                     Invoke()
        return $result[0]
    } finally {
        $Script:powershell.Commands.Clear()
    }
}
```
When you need to create a powershell class instance without pre-bound to a runspace, just do the following:
```
Import-Module .\CreateClassInstanceHelper.psm1
New-UnboundClassInstance([Foo], $argsForCtor)
```

**Comment by vors** [comment]
oh man, this!
Both runspace-bound instances and runspace-unbound instances create problems.
I feel it would be good to rethink this part of the language and maybe provide an easier way to create both.

**Comment by mponton** [comment]
@daxian-dbw This just saved my butt. Long story short, I'm dealing with PoSh classes and "need" to use UniversalDashboard.io to create a REST API. One of the class instances is a shared logger instance (NLog wrapper with specific methods). I could not get this to work in a 2nd runspace until I read this issue and tried to make the instance an unbound class instance. Man, the time I have spent debugging this... I would never have been able to do this without your fix/helper class. I will admit I feel a bit like a script kiddy that downloaded a piece of code from the Net without fully understanding it, but considering my deadlines, I think this will do for now until I have more time. Just wanted to thank you so very much for this!
