### ISSUE TITLE
PowerShell should not depend on environment variables 

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3662]
From #3580 @daxian-dbw 
> I feel the right approach probably should be avoiding using environment variables in powershell as much as possible. After we move to  netcoreapp2.0 , we can use  [System.Environment]::GetFolderPath  to get most special folder paths on windows. For example,  ClrFacade.GetFileSecurityZone  uses  Environment.GetEnvironmentVariable("SystemRoot")  which can be replaced now. It seems  PSReadline  also depends on environment variables and thus I got the error  The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine .

>However, it's impossible to avoid environment variables in powershell on Unix, as  [System.Environment]::GetFolderPath  doesn't work in most cases. So I believe powershell started by  Start-Process powershell -UseNewEnvironment  on Unix platforms won't work well by design.

> I prefer to fix the issue for win-core powershell by directly removing the dependencies on environment variables -- I believe they are workarounds for  Environment.GetFolderPath  which were missing in .NET Core 1.1 and prior.

Realted #3545.

**Comment by DarwinJS** [comment]
I tried to do a similar thing back on VBScript and then again in PowerShell - specifically for folder locations.
(http://csi-windows.com/toolkit/csigetspecialfolder)

I was working on a universal retriever (not published) that could take any of the known constants from any of the folder retrieval APIs and give you the right thing back.

I found that there were certain user contexts in which the folder APIs would not return anything, but the regular old environment variable would return something.

I could try to exhume the code to see if I documented the problems directly in it - but I would say you would want to test your folder retrieve APIs in all run contexts before trusting them to return the right results.

Also sometimes the discrepancies between environment variables and folder APIs are fall in favor of local folders.

I'm not sure there is anyway around the path variable as it is so specially constructed.

However, even if you disregard all of the above, I personally believe environment variables are a unifying mechanism across OSes that can be used to "patch up" many differences for truly "run anywhere" scripts.

I have put this forward in this RFC: https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0019-PowerShell-Core-Interop-Module.md

**Comment by iSazonov** [comment]
@DarwinJS I think it entirely depends on the using context. Can you assess how PowerShell uses environment variables? As a result, we could open a few sub-Issues to fix the specific problems.

But it seems first we need to conclude - Environment variables vs CoreFX special folder API.
/cc @SteveL-MSFT

**Comment by DarwinJS** [comment]
@iSazonov - beyond the PSModulePath, regular Path I do not know the internals of the PowerShell engine's reliance on them.

If your original post was to address PowerShell engine internals only it makes sense.  My comments are guarded toward this idea moving into the mainstream of scripts that we write.

Also, at the Vista/Windows 7 timeframe special folders receive a new API upgrade to "SHGetKnownFolderPath" which is more abstract and OEM extensible legacy "SHGetFolderPath" in that it uses GUIDs for the folder IDs which uses more human friendly constants.  If SHGetKnownFolderPath was picked it may hamper support on pre-Vista kernels.  But maybe .NET Core does it differently than either of these APIs?

I'm not personally losing any sleep over lacking support for OSes before Windows 7 - but only Microsoft knows the global customer implications of such choices.

**Comment by iSazonov** [comment]
@DarwinJS PowerShell Core is only supported on Windows 7 SP1 and above.
[CoreFX](https://github.com/dotnet/corefx/blob/1fa2fe8a9307b7b0d3901f989a2f69f5027d949c/src/System.Runtime.Extensions/src/System/Environment.Win32.cs#L217) uses `SHGetKnownFolderPath`

**Comment by DarwinJS** [comment]
Is this issue really more to "reduce powershell dependence on environment variables pointing to file system locations" ?

I found a similar concept to what I am trying to express in the 12factor app design principles:  https://12factor.net/config - look for statements about "environment variables"

**Comment by iSazonov** [comment]
@DarwinJS Feel free share any ideas! Later we can always open a new discussion for a more specific case.

From the link:
>The twelve-factor app stores config in environment variables (often shortened to env vars or env). Env vars are easy to change between deploys without changing any code; unlike config files, there is little chance of them being checked into the code repo accidentally; and unlike custom config files, or other config mechanisms such as Java System Properties, they are a language- and OS-agnostic standard.
