### ISSUE TITLE
On Unix, PowerShell will not find files with backslashes in their names

### ISSUE THREAD

**Issue by jeffbi** [PowerShell/PowerShell#3666]
This is similar to #3414, but involves only the backslash portion.

The basis of the problem is premature normalization of paths. Path normalization happens quite early (and *very* frequently and in a great number of places in the PowerShell code) while processing a command. Usually this happens before the path reaches its provider, and often that normalization is a brute-force change one slash to another mechanism. Thus a path such as `1\2` on Unix is "normalized" to `1/2`, ensuring that the path will never be found.

Using `-LiteralPath` does not prevent the path normalization, so that is not a workaround.

Steps to reproduce
------------------
From bash:
```bash
$ touch 'a\b'
```
then from PowerShell:
```PowerShell
PS> Remove-Item a\b
```
or
```PowerShell
PS> Move-Item a\b a-b
```

Expected behavior
-----------------
The file `a\b` is deleted

Actual behavior
---------------
```
Remove-Item : Cannot find path 'a/b' because it does not exist.
At line:1 char:1
+ Remove-Item a\b
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (a/b:String) 
    [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                     
----                           -----                                                     
BuildVersion                   3.0.0.0                                                   
CLRVersion                                                                               
GitCommitId                    v6.0.0-alpha.18-38-g08e855556cff42274a5903799b826e78d0c...
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                   
PSEdition                      Core                                                      
PSRemotingProtocolVersion      2.3                                                       
PSVersion                      6.0.0-alpha                                               
SerializationVersion           1.1.0.1                                                   
WSManStackVersion              3.0                                                       
```

**Comment by iSazonov** [comment]
On Windows the same:
```powershell
PS C:\temp> New-Item "1/2"
New-Item : Could not find a part of the path 'C:\temp\1\2'.
At line:1 char:1
+ New-Item "1/2"
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\temp\1\2:String) [New-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : NewItemIOError,Microsoft.PowerShell.Commands.NewItemCommand
```

**Comment by jeffbi** [comment]
@iSazonov I think this is a separate issue. It may turn out to be related to path normalization, but I still think it should have it's own issue.

This one is about attempting to rename, remove or move an *existing* file. The error message in this case is `Cannot find path '1\2' because it does not exist.` rather than `Could not find a part of the path 'C:\temp\1\2'`.

I think you'd be unlikely to run into this in Windows, at least on its native file systems, since both forward and backslashes are disallowed. In Unix forward slashes are allowed, and it's simple create, from bash or other programs, a file with forward slashed in the name.

**Comment by iSazonov** [comment]
It seems this should apply to the type of the file system and not to a platform.

**Comment by iSazonov** [comment]
Interesting, Is `[System.IO.Path]::GetInvalidPathChars()` and `[System.IO.Path]::GetInvalidFileNameChars()` based on a platform or a file system type?

**Comment by jeffbi** [comment]
@iSazonov I would love to see this based on file system type rather than platform, along with a number of other areas. One problem is that I haven't found a way to definitively identify an NTFS file system under Linux.

Regarding `[System.IO.Path]::GetInvalidPathChars()` and `[System.IO.Path]::GetInvalidFileNameChars()`, there appear to be separate implementations for each *platform* in coreclr.

It seems that the notion of illegal characters is largely platform-based rather than file system based. As an experiment, I create a file named `a>b<c:?|` on an NTFS volume on my Linux box with the `touch` command. There are five characters in there that Windows considers to be illegal, but the NTFS file system accepts them and Windows displays the file properly in Windows Explorer. I can't *do* anything with it on Windows, such open or delete it, but it is recognized.

**Comment by iSazonov** [comment]
This is specificity of higher-level API (Win2k).
If so we must always follow the same rule and be platform based.We will not be able to be more flexible 😕

**Comment by joeyaiello** [comment]
We might just have to force users to escape the backslash. I'm open to it, at least....

**Comment by iSazonov** [comment]
This should be the last resort.

**Comment by joeyaiello** [comment]
I mean, is it? If I want path normalization for platform-agnostic scripts (e.g. `$PSScriptRoot\foo`), I don't see how we can avoid escaping backslashes.

**Comment by iSazonov** [comment]
Maybe we should take into account [System.IO.Path]::GetInvalidPathChars()  and  [System.IO.Path]::GetInvalidFileNameChars() in normalization.

**Comment by HumanEquivalentUnit** [comment]
Escaping backslashes isn't a complete solution, you can't even shell-glob wildcard match them; `gci *` throws an exception in a directory containing `a\b` as a filename:

```
gci : Could not find a part of the path '/test/a/b'.
At line:1 char:1
+ gci *
+ ~~~~~
    + CategoryInfo          : ReadError: (/test/a/b:String) [Get-ChildIt
   em], DirectoryNotFoundException
    + FullyQualifiedErrorId : GetItemIOError,Microsoft.PowerShell.Commands.Get
   ChildItemCommand
```

**Comment by SteveL-MSFT** [comment]
`-literalpath` should not normalize

In the `get-childitem` case, we'll need to be smarter in the filesystem provider because it tries to normalize all the time.  When it finds the file `a\b` it needs to know that this is literal.

**Comment by vors** [comment]
Hit it again today, because of https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/11
The above issue makes the `\` very common char in the unzipped names on macOS.

I think both escaping and literal path are not good solutions, because they break all the normal ways that we work with files in powershell

```
PS /Users/vors/junk/baskslash> ls                                                                                    
untitled\folder
PS /Users/vors/junk/baskslash> Get-ChildItem . | Remove-Item                                                         
Remove-Item : Cannot find path '/Users/vors/junk/baskslash/untitled\folder' because it does not exist.
At line:1 char:19
+ Get-ChildItem . | Remove-Item
+                   ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (/Users/vors/jun...untitled\folder:String) [Remove-Item], ItemNotFoun 
   dException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

Like, that stuff should just work, no matter what.
As one mitigation for interactive only usage, a good tab-completion (that adds escaping) can help. It's the same as tab-completion that adds quotes to handle whitespaces in the names.

**Comment by vors** [comment]
Also literal path doesn't work

```
Get-ChildItem . | % { Remove-Item -LiteralPath $_.Name }
```

But I would argue that it's not the right way to fix it.
We can error out if the command is ambiguous, but when it's not we should just silently execute that.

**Comment by joeyaiello** [comment]
This discussion came up again on #8587, and I want to note for later that we should really look at the pipelining scenario described by @vors above. 

Unfortunately, I think that the logic we applied to solving that issue (valid globbing characters in Linux filenames) is worse when we're talking about a "valid" (at least to Windows) path separator in a Linux filename. 

To me, the scenario we need to solve here is the one where folks used to paths on Windows will be contributing to or sharing scripts with folks used to paths on Linux. Furthermore, one of our primary goals right now is enabling more backwards compatibility with existing scripts and modules. 

With both of those in my mind, **I think it's fair to rule out ever requiring Windows users to conform to Linux and use forward slashes**. 

On a more positive note, I think that enabling escaping of backslashes (which we may have already done to some degree) is certainly a step in the right direction, even if it doesn't solve the pipelining issue. **Is there any reason someone sees *not* to do this?**

**Comment by SteveL-MSFT** [comment]
The FileSystemProvider is overly aggressive in normalizing the path, so even:

```powershell
set-content -literalpath "a\b.txt" -value "hello"
```

Creates a `b.txt` within a folder `a` (assuming this exists) rather than a file called `a\b.txt`.

I think if we have a literalpath with a backslash and not on Windows, it should be escaped and preserved.  The path normalization would take this into account and not blindly replace slashes.

**Comment by iSazonov** [comment]
I'd start with design. We want magic features but every time fallback to platform specific implementation details.
What is the main goal? I believe it is having portable scripts.
At the same time, we need to give users the ability to perform low-level operations (such as described in description of the issue).
Currently, path portability is achieved by means of aggressive normalization. It has several side effects and they _cannot be eliminated_ completely without adding complexity to the language or/and rules.
I'd split file provider to two levels - high (portable) and low (platform specific). Then introduce [portable] path (PSSA will understand this!). Perhaps non-portable could be default in console or we could have a switch for the mode. Perhaps we could do agressive normalization while user types a path and force typing backstick to escape and stop the normalization. Perhaps we could have syntax sugar for [portablepath]/[non-portablepath] to enhance current Path/LiteralPath experience.

**Comment by SteveL-MSFT** [comment]
I think the default behavior with `-Path` is fine for portability reasons.  I can see how `a\b.txt` would be problematic used with `-LiteralPath` as it would do different things on Windows vs Unix.  However, ``a`\b.txt`` where the backslash is escaped should be honored.

**Comment by austincrft** [comment]
I ran into this issue while trying to download files from Azure Blob Storage. On Windows, it was creating directories properly for blobs with slashes, but on unix systems it was creating files with backslashes in their names instead. Here is the function I wrote to build a directory structure out of the files in the directory.

For example, given a file with the name `foo\bar\baz.txt`, the directories `./foo/bar/` will be created with a `baz.txt` file in it.

Hopefully this helps someone out.

```powershell
function Repair-DirectoriesForUnixSystems($directory) {
    if ($IsWindows) {
        return;
    }

    $filesWithBackslashes = @(Get-ChildItem $directory | Where Name -like '*\*')

    foreach ($file in $filesWithBackslashes) {
        $split = $file.FullName.Split("\")

        $directoryNames = $split[0..($split.Length - 2)]

        $path = $directoryNames -join "/"

        if (-not (Test-Path $path)) {
            New-Item -Path $path -Type Directory > $null
        }

        $fileName = $split[$split.Length - 1]

        # NOTE: the native unix copy and remove must be used because of this issue
        # https://github.com/PowerShell/PowerShell/issues/3666
        & cp $file.FullName "$path/$fileName"
        & rm $file.FullName
    }
}
```

**Comment by Serentty** [comment]
I ran into this today when I accidentally created two directories with ``mkdir`` (the Linux version) instead of one with a space in its name, since I was trying to use the backslash to escape the space as I'm used to (I'm aware that PowerShell uses a different escape character). Afterwards, I was unable to delete the one whose name ended in a backslash.

**Comment by NicolaiMogensen** [comment]
When trying to run files with `bash` in powershell, the tab-completion resorts to doing `bash .\script.sh` which then won't find the file. Running `bash script.sh` or `bash ./script.sh` works fine, but the tab-completion uses `.\` which does not work.

**Comment by Kuinox** [comment]
Hey @SteveL-MSFT, your bot auto-closed this issue, the bug still exists.

**Comment by somescout** [comment]
The issue still exists and is still annoying
