### ISSUE TITLE
Make it an internal policy to publich the powershell equivalent of every point-click action

### ISSUE THREAD

**Issue by SRGOM** [PowerShell/PowerShell#3667]
I know this is "above" you guys but could you guys try and make it so? I don't want to go finding around a setting and do twenty clicks when I can do a `Win+X , A, Ctrl-V, Enter` to do something. 

I shouldn't have to. That's the entire reason Powershell is there, right?

**Comment by lzybkr** [comment]
I think there has been a rather obvious move towards enable scriptable automation (e.g. Nano Server has no UI), but these things take time and at some point there are diminishing returns.

I suggest you provide feedback [here](https://windowsserver.uservoice.com/forums/295047-general-feedback) for any **specific** areas that you can't currently automate with PowerShell but would like to - this can help the appropriate teams prioritize.
