### ISSUE TITLE
Allow advanced functions to only return objects to the pipeline explicitly

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3669]
One concern I've heard from several people is that they are surprised that anything emitted (generally accidentally because they didn't set or pipe to $null) within the function shows up in the pipeline.  Although is can be a powerful construct, it can also cause confusion to developers familiar with other language semantics for `return`.  PowerShell classes does support `return` to explicit return objects, but we should consider perhaps adding a property to the `CmdletBinding` attribute so that objects not `returned` are swallowed and only emitted if explicitly `returned`.

**Comment by powercode** [comment]
I think that will prevent a lot of bugs

**Comment by lzybkr** [comment]
One proposal I had was to add something like:
```
using strict return
```
At the top of the script. We could also enable lexical scoping in a similar manner.

**Comment by bergmeister** [comment]
Makes sense but only if a function with this new attribute does not prevent Windows PowerShell from being able to parse/use such a function.
Being able to enforce the return type and prevent PowerShell from casting the type of returned object would be great as well

**Comment by markekraus** [comment]
I like the idea of adding an option to make this possible. But, I also fear this will result in some really bad code for PowerShell. It will encourage users to ball things up and return them all at once instead of releasing them to the pipeline as created. That is the issue I see more commonly coupled with users who mistakenly think that `return` is the only place objects are emitted.

One design consideration would be to include the ability to return multiple objects explicitly to without the flow control aspect of `return`. for the sake of demonstration I will use `emit` as a keyword for this:

```powershell
function Get-Stuff {
    [CmdletBinding(ExplicitReturn)]
    param ()
    process {
        # Not emitted
        Get-ChildItem c:\
        # emitted without flow control
        emit 1
        emit 2
        # emitted and flow control sent
        return 3
        # Not executed
        Get-Date
    }
}
Get-Stuff
```

Result:

```none
1
2
3
```

**Comment by iSazonov** [comment]
Breaking change.

**Comment by markekraus** [comment]
@iSazonov How would this be a breaking change? So far everything discussed here is additive. instead of `emit` we could change `return` to accept a switch `return -Continue $value` or something.

**Comment by iSazonov** [comment]
Dot-sourcing can be break.

**Comment by markekraus** [comment]
@iSazonov I'm not sure I follow how that would break dot sourcing. Can you elaborate?

**Comment by iSazonov** [comment]
```powershell
using strict return

. .\function.ps1
```
Seems `function.ps1` may not work as expected.

**Comment by markekraus** [comment]
Maybe. The original proposal from @SteveL-MSFT  was to add a property to `CmdletBinding`.

**Comment by jez9999** [comment]
Can I ask a dumb question?  It seems like the design goal of PowerShell was "output stuff to the pipeline and then stop processing".  So why does `return $someValue` even exist as valid syntax?  It makes it look an AWFUL lot like you are just returning `$someValue`.  Wouldn't it make more sense to say, if you want to just output anything emitted to the pipeline, say `return`.  If you want to swallow that and just output a certain value, say `return $someValue`?  Right now it seems like some weird hybrid where it outputs everything that was emitted previously AND `$someValue`.  I'd be interested to know the thinking that went into that decision.

**Comment by jez9999** [comment]
Quite.  It's a convenience that saves no bytes at all, and looks misleading.

**Comment by jantari** [comment]
> I like the idea of adding an option to make this possible. But, I also fear this will result in some really bad code for PowerShell. It will encourage users to ball things up and return them all at once instead of releasing them to the pipeline as created. That is the issue I see more commonly coupled with users who mistakenly think that `return` is the only place objects are emitted.
> 
> One design consideration would be to include the ability to return multiple objects explicitly to without the flow control aspect of `return`. for the sake of demonstration I will use `emit` as a keyword for this:

I feel like PowerShell could just reuse the C# syntax `yield return` for explicitly passing an object to the pipeline without exiting the function like a bare `return` would.

I would still love to see this feature: `[CmdletBinding(ExplicitReturn)]` on functions and then only pass objects on to the pipeline with `yield return` or `return` keywords. As @SteveL-MSFT said it's been a long standing source of frustration for new and old PowerShell users, could this be looked at again and evaluated for the roadmap for this year or so?

**Comment by jantari** [comment]
This is still something I'd very much like to see and I also stand by the idea of borrowing `yield return` as a new statement.
