### ISSUE TITLE
Remove-Item -Recurse on symlink should recurse when path ends with path separator

### ISSUE THREAD

**Issue by jeffbi** [PowerShell/PowerShell#3674]
Part of the resolution of issue #621 was to have the `-Recurse` option be ignored when removing a symlink to a directory with a command such as `Remove-Item -Recurse -Path linktodir`, to be more in line with the unix Unix `rm` command.

However, on Unix the `rm` command, when given as `rm -r linktodir/', with the trailing slash on the pathname, *will* recurse into the target directory and delete its contents, then remove the link, leaving the target directory behind. Without the trailing slash `rm -r linktodir` simply removes the link.

Steps to reproduce
------------------
```PowerShell
New-Item -ItemType Directory subdir
New-Item subdir/file.txt
New-Item -ItemType SymbolicLink link-to-sub -value subdir
Remove-Item -Recurse link-to-sub/
```

Expected behavior
-----------------
Symbolic link `link-to-sub` should be deleted, directory `subdir` should still exist but be empty.

Actual behavior
---------------
On Linux, the directory `subdir` is emptied and remains, but an error is emitted and the symbolic link is not deleted. Error is `Not a directory`.

On Windows, the symbolic link is deleted but the directory `subdir` and its contents remain.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-alpha.18-33-ged4e77d65809ed8ee2589fd50...
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by mklement0** [comment]
Using the Unix utilities, I actually get slightly different behavior, and also differing behavior between platforms:

```sh
# Set up a temp dir. with subfolder 'subd' and symlink 'subdl' that points to it.
mkdir -p /tmp/$$ && cd /tmp/$$ && rm -rf subd && rm -f subdl && mkdir -p subd && touch subd/file{1..2}.txt && ln -s subd subdl && ls -l

# Try to remove the symlink with -r and trailing /
rm -r subdl/
```

### macOS 10.12.4:  

* The command succeeds (no error message, exit code `0`).
* The _target_ folder is completely removed, and a `subdl` is left behind as a _broken symlink_.

In other words: `rm -r subdl/` behaves as if the symlink's _target_ had been passed to `rm -r` (`rm -r subd`).

### Ubuntu 16.04: 

* The command fails (error message `rm: cannot remove 'subdl/': Not a directory`, exit code `1`).
* `subd`'s _content_ was removed, but the folder itself was retained, as was the symlink.

---

From what I can tell, both behaviors are in violation of [`rm`'s POSIX spec](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/rm.html):

> The rm utility removes symbolic links themselves, not the files they refer to, as a consequence of the dependence on the unlink() functionality, per the DESCRIPTION. When removing hierarchies with -r or -R, the prohibition on following symbolic links has to be made explicit.

I read this to mean: When given a symlink to a directory _on the command line_ with `-r` at least _warn_ that the symlink won't be followed.

**There's nothing in the spec about how the presence/absence of a trailing `/`, but given that you can usually refer to a directory _interchangeably with or without a trailing `/` (e.g., `ls subd` is the same as `ls subd/`)_, I think the existing Unix behaviors are questionable and not worth adopting in PowerShell.**

**Comment by xeijin** [comment]
Was there any progress on this issue? It prevents me from clearing out a directory...
