### ISSUE TITLE
Invoke-WebRequest claims it is "writing request stream (number of bytes written X)" when downloading

### ISSUE THREAD

**Issue by AArnott** [PowerShell/PowerShell#3677]
Steps to reproduce
------------------

```ps1
Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -outfile $env:temp\nuget.exe
```

Expected behavior
-----------------

The PowerShell progress dialog suggests we are **reading** bytes from the **response** stream.

Actual behavior
---------------

The PowerShell progress dialog claims it is "**Writing request** stream (number of bytes **written** X)"

Environment data
----------------

```ps1
 $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.15063.168
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.168
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@AArnott Thanks for your report!

I believe the message should depend on the Get/Post method.

**Comment by AArnott** [comment]
`GET` verbs have no request stream so response stream messages would always be appropriate.
But `POST` verbs have both a request and a response stream. So ideally the message shown would be appropriate for the stream that is currently being written or read from.

**Comment by iSazonov** [comment]
@SteveL-MSFT 
![invoke-webrequest](https://user-images.githubusercontent.com/22290914/31009120-7630b8fa-a517-11e7-9b31-d30f1a8efa23.png)

Can we fix this by changing Resx strings to
```
Web request status
    Number of bytes processed: 99999
```

**Comment by markekraus** [comment]
@iSazonov Are you working on this one? if not, this one was next on my list.

**Comment by iSazonov** [comment]
@markekraus Please grab it - thanks!

**Comment by markekraus** [comment]
@iSazonov or @SteveL-MSFT I see that is is possible to test the progress output through a job. If I'm just changing the .resx strings, is there any need to write pester tests for it?

**Comment by SteveL-MSFT** [comment]
@markekraus assigned it to me for now.  If you are only changing the resx strings, no tests are typically needed as those strings are expected to be localized at some time.  We have some meta tests for resx files.

**Comment by markekraus** [comment]
PR #5078
