### ISSUE TITLE
Out-String cmdlet should support -NoNewline too

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3684]
PSv5 brought the `-NoNewline` switch to the `Set-Content` (`Add-Content`) and `Out-File` cmdlets to allow direct concatenation of the input objects without newlines (strings among the input objects retain their _embedded_ newlines however).

_By default_, these cmdlets _blindly append an additional newline_, whereas `Out-String` currently _invariably_ does that, because it lacks `-NoNewline`.

For symmetry, `Out-String` should support `-NoNewline` too.

Current behavior
------------------

```powershell
> (Out-String -InputObject 'a') -match '^a\r?\n$'
$True  # A trailing newline was added.
```

Desired behavior
-----------------

```powershell
> (Out-String -NoNewline -InputObject 'a') -match '^a$'
$True  # No trailing newline was added.
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

**Comment by raghav710** [comment]
@mklement0 how complex is this for a beginner? If its fairly straightforward I'd like to give it a try!

**Comment by mklement0** [comment]
@raghav710: 

Shouldn't be too hard:

* Add the new parameter [here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/out-string.cs#L20).
* Act on it accordingly [here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/out-string.cs#L122).
* Add tests [here](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Utility/Out-String.Tests.ps1).

I'm not sure how the documentation part is usually handled; perhaps create an issue in the [docs repo](https://github.com/PowerShell/PowerShell-Docs/issues); @iSazonov, can you advise?

Thanks for taking it on.

**Comment by SteveL-MSFT** [comment]
For the docs, the best thing is to create a corresponding doc PR in the [docs repo](https://github.com/PowerShell/PowerShell-Docs) and link it to the PR in this repo.

**Comment by iSazonov** [comment]
@raghav710  Typically, beginners receive most style comments. Please read out [Coding Guidelines](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md). Mainly you should  follow the style of the surrounding code.

**Comment by raghav710** [comment]
@iSazonov @SteveL-MSFT @mklement0  thanks for all the guidance :) That was quite kind of you all :)
Should the issue be assigned before i start working?

**Comment by iSazonov** [comment]
We cannot formally assign you today because your GitHub status is still not `Contributor`.

**Comment by SteveL-MSFT** [comment]
@raghav710 consider it implicitly assigned to you :)

I'll assign it to myself so no one else ends up duplicating your work.  Thanks!

**Comment by raghav710** [comment]
@mklement0 I notice that when the -Stream switch is used, no newline is appended. Should I make the behaviour consistent and add in a newline when -NoNewLine is not set?

**Comment by iSazonov** [comment]
`-Stream` turn out internal formatting in Out-String. I think `-Stream` and `-NoNewLine` should be in different parameter sets.

**Comment by mklement0** [comment]
Yes, `-Stream` and `-NoNewline` should be mutually exclusive and should therefore be in different parameter sets.

All `Out-String` output goes through the formatting system to generate multi-line string output; by default, the result is output as a _single_, multi-line string; `-Stream`, by contrast, outputs the lines as a string _array_, and the individual array elements - the lines - should _never_ have a trailing newline.

**Comment by raghav710** [comment]
I've added the code and a couple of tests. I tried the Current behaviour and desired behaviour commands and both work as expected. The behaviour of -Stream is not impacted. 
Thanks!

**Comment by mklement0** [comment]
@SteveL-MSFT:  The more I think about this, perhaps it's also time to rethink the behavior of `Out-File` with respect to types that have PS formatting data:

Currently, whatever lines the (default) formatter produces (for types with formatting data) are newline-stripped too, resulting in virtually useless representations:

```powershell
Get-Item / | Out-File -NoNewline t.txt
```

It's not obvious in the console due to word wrapping, but if you inspect `t.txt` in an editor with word wrapping turned off, you'll see that a _single_ output line was produced - it's basically the equivalent of `(Get-Item / | Out-String) -replace '\r?\n'`:

```none
    Directory: Mode                LastWriteTime         Length Name                                                                                                                              ----                -------------         ------ ----                                                                                                                              d-r---          10/8/17   2:56 PM                /                                                                                                                                 
```

With this PR, `Out-String -NoNewline` will work the same, but the larger question is whether this behavior should be changed for _both_ `Out-File` and `Out-String`.

**Comment by iSazonov** [comment]
We have some issues about problems with our formatting (adding LF/CR). So I think it is good to have `-NoNewline`- users are able to control output more flexibly.

**Comment by mklement0** [comment]
Yes, `-NoNewline` is desirable, but the aspect of stripping out _embedded_  newlines from formatter-generated output is the problematic one.

To put it differently: This obscure behavioral distinction between `.ToString()`-stringified types (such as `[string]` itself) and those with PS formatting data is problematic and there is no good reason for the embedded newline stripping to begin with.

As a separate issue, given the name and the state of the current documentation, it may not be obvious to users that `-NoNewline` effectively means `-NoSeparatorBetweenOutputObjects`, not `-SuppressOnlyTheTrailingNewline`.  
Given that a  change would be a serious breaking change, the solution is to document `-NoNewline` properly - see https://github.com/PowerShell/PowerShell-Docs/issues/1739

**Comment by mklement0** [comment]
Consider the following example, which illustrates the difference in behavior between `.ToString()`-stringified and formatter-generated output with respect to stripping of embedded newlines:

```powershell
> "one`ntwo", [pscustomobject] @{ three = 3 } | Out-file -NoNewline t.txt; Get-Content -Raw t.txt
one
twothree-----    3
```
Note how all newlines were stripped from the formatter-generated output for `@{ three = 3 }`, which included removal of empty lines; to spell it out:

```

three
-----
    3
```

turned into `twothree-----    3`


In summary: we first need to decide whether `Out-File -NoNewline` requires fixing for formatter-generated output, and then implement `Out-String -NoNewline` accordingly.

**Comment by SteveL-MSFT** [comment]
cc @joeyaiello @HemantMahawar 

I don't know the history of `out-file -nonewline`, but as an end user, it seems that `-nonewline` should always mean the last newline, not every newline.  If someone wanted to strip newlines, they can easily do it themselves, but the cmdlets (without the `-nonewline`) would typically add a trailing newline which they can't suppress without the switch.

**Comment by raghav710** [comment]
If I may add to the discussion. I noticed that when you do a 
`"a","b" | out-string` you get an output that is of length **6** in windows. This was a bit surprising for me and then I noticed that the extra 4 characters were because of two _\r\n_s. I believe this value may be different in Linux.
Some points to ponder:
* Should `-NoNewLine` be the solution to this issue or should we only strip the last newline and let the user handle the problem?
* If the user is capable of stripping embedded new lines, why should s/he use `-NoNewLine` ?

**Comment by mklement0** [comment]
@raghav710: Yes, PowerShell Core uses platform-appropriate newlines (CRLF on Windows, LF-only on Unix), so getting 6 chars. on Windows vs. 4 on Unix is to be expected.

This behavior is unrelated to `-NoNewline` (_newline_ is used as an abstract term for line break, irrespective of what specific character [sequence] is used to represent it).

As @SteveL-MSFT mentions, the natural assumption about what `-NoNewline` does is to suppress a _trailing_ newline only, but - unfortunately - that is never how it has worked: all implementations of `-NoNewline` - in `Write-Host` (v2+), `Set-Content`/`Add-Content` (v5+), `Out-File` (v5+) _directly concatenate_ the (representations of) _all_ input objects without newlines:

```powershell
> 1, 2 | Write-Host -NoNewline; Write-Host more
12more
```
(You won't notice with `Write-Host 1, 2` or the equivalent `Write-Host 1 2`, because the array is processed as a whole and stringified to `1 2`.)

The usefulness of this behavior is questionable, but changing it would certainly be a breaking change.

Currently, `-NoNewline` only work as one would expect with a _single_ input object.

The only conceivable benefit of the current  `-NoNewline` behavior with _multiple_ input objects is a way to suppress all newlines _at the source_, as opposed to having to remove them after the fact.

As such, it is as special case of a generic `-Delimiter` parameter, that was suggested in #3855: 
 `-Delimiter ''`.

`-Delimiter` would work as a _terminator_ - i.e., placed after _every_ object, including the last; arguably, it would also be helpful to place the string only _between_ elements, not also after the last, i.e, act as a _separator_ (with an empty delimiter that distinction doesn't matter).

If `-NoNewline` gets fixed to work the way users probably expect - suppress the _last_ newline only - `-NoTerminator` could be introduced as an _alias_ of `-NoNewline` to generically suppress a trailing delimiter - be it a newline by default or one specified via `-Delimiter`, which effectively applies the delimiter string as a _separator_.

**Comment by iSazonov** [comment]
@mklement0 if  `-NoNewline` works as No Newline Between Objects we would add new parameter -NoLastNewLine which will suppress only last new line.
The parameter name `-NoNewline` does not explicitly imply that new lines is suppressed all or only the last. So user expectiotions is based on docs and/or actual behavior. Considering it's a long-standing parameter I beleive that `-NoLastNewLine` is right way if we really want fix something here.

**Comment by mklement0** [comment]
User expectations _may_ be based on examining actual behavior (personally, I only very recently discovered the true behavior), and it's certainly _not_ based on the docs, [as I've tried to point out](https://github.com/PowerShell/PowerShell-Docs/issues/1739).

That said, introducing `-NoLastNewline`  (and possibly alias `-NoLastDelimiter`) sounds like a good compromise for the sake of backward compatibility.

**Comment by raghav710** [comment]
Should the docs be updated with the details of the current implementation of `-NoNewLine` ?

**Comment by SteveL-MSFT** [comment]
@raghav710 yes!  is this something you can contribute?

**Comment by iSazonov** [comment]
@mklement0 Could you please open new Issue for ` -NoLast*`?

**Comment by mklement0** [comment]
@iSazonov: Please see #5108 and #5107.

**Comment by raghav710** [comment]
@SteveL-MSFT I'd be happy to :) I should first create an issue and then work on it right?

**Comment by SteveL-MSFT** [comment]
@raghav710 for the doc update, you don't need to create an issue, you can just submit PR to https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Out-String.md

**Comment by raghav710** [comment]
@mklement0 @SteveL-MSFT @iSazonov I've added the docs and raised a PR [here](https://github.com/PowerShell/PowerShell-Docs/pull/1764). Please let me know if I need to add more clarity anywhere
