### ISSUE TITLE
Multiline prompt behaves incorrectly on macOS

### ISSUE THREAD

**Issue by tLXvGt** [PowerShell/PowerShell#3687]
Steps to reproduce
------------------
Run:
``function prompt { "Hello, World`r`nHi> " }``

Expected behavior
-----------------
On Windows PowerShell correctly prompts me with 2 lines:
```
Hello, World
Hi> [cursor]
```
I can write anything and prompt will stay the same.

Actual behavior
---------------
On macOS PowerShell correctly prompts me with 2 lines:
```
Hello, World
Hi> [cursor]
```
However, when I press any key prompt copies first line into second one and prompt looks like this:
```
Hello, World
Hell[cursor]
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lzybkr** [comment]
This is another symptom https://github.com/lzybkr/PSReadLine/issues/468. When that issue is fixed, this one will be as well.

**Comment by daxian-dbw** [comment]
I believe this is addressed by https://github.com/PowerShell/PowerShell/pull/3867
