### ISSUE TITLE
Corruption of non-ASCII characters when piping to a non-built-in

### ISSUE THREAD

**Issue by elirnm** [PowerShell/PowerShell#3689]
Steps to reproduce
------------------
1. Execute `"øæå" | <any non-powershell command>` 

2. See that the string has been converted to `???`

3. Execute `"øæå" | <any cmdlet>`

4. See that the string is maintained correctly as `øæå`

This behavior has occurred with every native program and every cmdlet I've tested it with.

I've also experienced the same behavior when reading a file with `gc` and then piping that along.

![capture](https://cloud.githubusercontent.com/assets/19817004/25645722/f921535a-2f65-11e7-909d-559981874d70.PNG)

As seen in the last example in the picture, the string is actually being converted to `???` rather than this being a display error.

Expected behavior
-----------------
String should remain `øæå` when being piped anywhere.

Actual behavior
---------------
String is corrupted when being piped to a non-powershell-builtin

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
CLRVersion
PSRemotingProtocolVersion      2.3
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
SerializationVersion           1.1.0.1
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
```

This is on Windows 7.

**Comment by iSazonov** [comment]
It seems duplicate https://github.com/PowerShell/PowerShell/issues/707

**Comment by lzybkr** [comment]
Actually, the duplicate is https://github.com/PowerShell/PowerShell/issues/1908
