### ISSUE TITLE
Import-Csv does not handle newlines containing just \r (Carriage Return)

### ISSUE THREAD

**Issue by Szeraax** [PowerShell/PowerShell#3692]
Steps to reproduce
------------------
"one,two,three`rthree,three,three" | out-file test.csv 
import-csv test.csv

Expected behavior
-----------------
Expected result:
```
one   two   three
---   ---   -----
three three three
```

Actual behavior
---------------
import-csv : The member "three" is already present.

Environment data
----------------
Tested on windows 8.1 and windows X (10). 
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Steps to fix
----------------
It seems that the ImportCsvHelper method located in my C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Utility\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.Commands.Utility.dll is the culprit. 

It looks like the code here:
```
		private bool IsNewLine(char ch)
		{
			bool result = false;
			if (ch == '\n')
			{
				result = true;
			}
			else if (ch == '\r' && this.PeekNextChar('\n'))
			{
				result = true;
			}
			return result;
		}
```

should include 
```
			else if (ch == '\r')
			{
				result = true;
			}
```

and then all will be happy. Thanks!

**Comment by Szeraax** [comment]
By the way, Get-Content does handle this case correctly. My solution for these files is to use Get-Content foo.csv | ConvertFrom-Csv.

**Comment by MaximoTrinidad** [comment]
Hum!  I normally use both "r`n`" then I can get the expected result.  I don't think something is wrong here.

"one,two,three`r`nthree,three,three"| out-file test.csv
import-csv test.csv

Results:
one   two   three
---   ---   -----
three three three

![csvgood_2017-05-03_16-18-16](https://cloud.githubusercontent.com/assets/19892435/25679833/c14326b8-301c-11e7-9d25-75024b719eab.jpg)

By the way, just a reminder, for Windows 5.x issues need to routed to UserVoice forum: https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by Szeraax** [comment]
Good to know about UserVoice!

And yes, using \r\n and \n both work fine. Its only just the plain `r that causes this issue. If I could, I would beat whoever creates files with `r as a line ending, but that's illegal and stuff.

The fact that Get-Content can read a file that uses just carriage returns means that there is inconsistency between using Get-Content foo.csv | ConvertFrom-Csv and Import-Csv. I would think those two usages should perform the same.

**Comment by iSazonov** [comment]
"`r" (LF) is Unix style EOL. I see the Issue on WSL too. So it is a bug.

**Comment by MaximoTrinidad** [comment]
Now I see what you're referring with the 'r`'.  I notice the inconsistency between import-csv and get-content.  Yeap! This might be a Bug!!

At the same time PowerShell is not working in WSL Bash Console as some of it previous behavior, like Scroll-Up and screen refresh issues, are back again making it hard to work with it.

![bashimportcsv_2017-05-04_10-23-52](https://cloud.githubusercontent.com/assets/19892435/25708509/af7e6fa8-30b4-11e7-8f72-7e4fd2eac0cd.jpg)
![bashimportcsv_02_2017-05-04_10-23-52](https://cloud.githubusercontent.com/assets/19892435/25708512/b3ee4ff4-30b4-11e7-855f-a1514d0f5e5c.jpg)

**Comment by jeffbi** [comment]
Isn't "`r" carriage-return (CR, 0x0D) rather that line-feed (LF, 0x0A)? Unix-style line endings are LF. Old, pre-OS X mac line-endings were CR.

**Comment by ditta95aR** [comment]
#

**Comment by Szeraax** [comment]
Yes

**Comment by thezim** [comment]
-LineDelimiter would be nice addition.

**Comment by Szeraax** [comment]
If we add line delimiter, do we add it to get-content too?

**Comment by MaximoTrinidad** [comment]
I think it should also be added in the "Get-Content" in order to keep some kind on consistent behavior.

+1 on to add the parameter '-LineDelimiter'.

:)

**Comment by iSazonov** [comment]
There is the informational [RFC 4180](https://tools.ietf.org/html/rfc4180) for CSV:
>    1.  Each record is located on a separate line, delimited by a line
       break (CRLF).  For example:

>       aaa,bbb,ccc CRLF
>       zzz,yyy,xxx CRLF

This obviously does not take into account Unix style EOL (LF) that we should support.
I agree that we should support old MAC style (CR, '\r') too.

Modern W3C standard - [Model for Tabular Data and Metadata on the Web](http://www.w3.org/TR/2015/REC-tabular-data-model-20151217/)
[line terminators](http://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#dialect-lineTerminators)
>An atomic property that sets the line terminators flag to either an array containing the single provided string value, or the provided array. The default is ["\r\n", "\n"].

It should also be noted that the SQL bcp utility has support of custom (EOL) _terminators_.

**Comment by Szeraax** [comment]
Personally, I'm not sure that it is worth making a -LineDelimiter parameter, given that I can Get-Content a csv file, split it using any delimiter I want, and then ConvertFrom-Csv to already accomplish the same thing. As just a regular powershell user, I don't expect import-csv or get-content to have custom EOL characters/terminators/delimiters. 

I'll let others decide that one though.

**Comment by mklement0** [comment]
@MaximoTrinidad You beat me to it: I meant to point you to the fact that `Get-Content` already has a `-Delimiter` parameter, though its current behavior is surprising: #3706

**Comment by MaximoTrinidad** [comment]
LOL @mklement0!! 
:)

**Comment by iSazonov** [comment]
Although files with '\r' EOL is a rare case, we should fix the Issue.

**Comment by Szeraax** [comment]
I agree that should be fixed to work the same as get content. I don't think
that we should add anything else though (at least, not based on this ticket)

Devin Rich
801-896-7937

**Comment by thezim** [comment]
@Szeraax yes, fix it first.

**Comment by mi-hol** [comment]
@SteveL-MSFT maybe this issue could be fixed using the code proposed by @Szeraax any time soon?

**Comment by iSazonov** [comment]
I can pull PR on next week if the fix will be approved.

**Comment by SteveL-MSFT** [comment]
Seems like treating a single CR the same as a single LF is reasonable.

**Comment by lzybkr** [comment]
There are 3 line ending variants supported by the PowerShell parser - CRLF (Windows), LF (Unix), and CR (old Apple), so it's very reasonable for CSV to do the same.

See [here](https://en.wikipedia.org/wiki/Newline) for more excessive details.

**Comment by bcrotty** [comment]
@iSazonov I'm still having an issue with this. My PS version is 5.1.18362.145. When I import a CSV where a line ends in `\r` instead of `\r\n`, the final value gets set to `\r` instead of an empty string, which is what I'd expect. Here's sample code:

```
"Name,Date`r`nBob,`r" | Set-Content ".\Test.csv" -NoNewline
$test = Import-Csv .\Test.csv
$test[0].Date -eq "`r"
```

**Comment by mi-hol** [comment]
@bcrotty did you notice that this repository is for PowerShell Core with version 7 preview release?
Actually I am surprised that an issue for the very different product Windows PowerShell 5.1 not covered here, wasn't closed right away.

**Comment by bcrotty** [comment]
@mi-hol Got it.

**Comment by iSazonov** [comment]
@bcrotty You can use Windows 10 Feedback tool or UserVoice site to report but before check latest Windows 10 builds.
