### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by ditta95aR** [PowerShell/PowerShell#3701]
Steps to reproduce
------------------

Expected behavior
-----------------

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by SteveL-MSFT** [comment]
@ditta95aR need more info

**Comment by iSazonov** [comment]
@SteveL-MSFT It is dummy account - see you previous posts.

**Comment by SteveL-MSFT** [comment]
Yeah, I'm noticing that based on other comments
