### ISSUE TITLE
Get-Content -Delimiter unexpectedly keeps the delimiter in the lines returned

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3706]
Note: It may be too late to change this behavior, or perhaps it falls into [Bucket 3: Unlikely Grey Area](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-3-unlikely-grey-area).
If the former, perhaps a `-TrimDelimiter` option could be added.

By default, `Get-Content` strips the newline character [sequence] from the lines it returns.

The generalization of this concept is to use the `-Delimiter` parameter, which allows specifying a custom line (record) delimiter (terminator / separator).

However, unlike with the default delimiter - a newline - whatever `-Delimiter` argument you specify is _kept_ in the lines returned, which is:

* an inconsistency

* an inconvenience, because the delimiter - which by its nature is not part of the data itself - must be stripped explicitly before further processing.

Steps to reproduce
------------------

I'd expect the following 2 commands to be equivalent:

```powershell
1,2 > t.txt; get-content                                     t.txt | % { "[$_]" }
1,2 > t.txt; get-content -delimiter ([environment]::newline) t.txt | % { "[$_]" }
```

Expected behavior
-----------------

```PowerShell
[1]
[2]
[1]
[2]
```

Actual behavior
---------------

```PowerShell
[1]
[2]
[1
]
[2
]
```

Note how the trailing newlines were retained in the output from the 2nd command.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on macOS 10.12.4
```

**Comment by MaximoTrinidad** [comment]
Hey @iSazonov,

Just wondering if this could be tied up with this other issue experiencing with Import-Csv:
"Import-Csv does not handle newlines containing just \r (Carriage Return) #3692"

Can someone confirmed this?

:)

**Comment by mklement0** [comment]
@MaximoTrinidad: The other issue is somewhat related, though in the case of `Import-Csv` the proper fix is to have it detect `\r`-only line breaks too (in line with `Get-Content`), so I see less of a need for an explicit `-Delimiter` parameter there.

**Comment by MaximoTrinidad** [comment]
Thanks @mklement0!

**Comment by iSazonov** [comment]
I agree that both should work uniformly `Get-Content` and `Get-Content -Delimiter`. Although the parameter name `LineTerminator` is more suitable.

And it is an other issue -  `Import-Csv` don't use FileProvider code. Although worth discussing that all file cmdlets (Out-File, Import-Csv, Export-Csv ...)  have been based on FileProvider code to work uniformly.

/cc @jeffbi

**Comment by mklement0** [comment]
@iSazonov: 

Historically, there's been a lot of confusion around the terms _separator_, _delimiter_, and _terminator_.

I agree that `-Delimiter` is not a great name, and that _terminator_ is more appropriate here - though, arguably, we're then not dealing with _lines_ anymore, but with the abstraction of _records_ (the terminology adopted by `awk` for instance, which has otherwise settled on _separator_, unfortunately).

Therefore, bypassing the secondary issue of _line_ vs. _record_, perhaps defining `-Terminator` as an alias for `-Delimiter` is appropriate (`-Delimiter` currently has no alias).

**Comment by iSazonov** [comment]
@mklement0 We could rely on the W3C standard - [Model for Tabular Data and Metadata on the Web
line terminators](http://www.w3.org/TR/2015/REC-tabular-data-model-20151217/)

**Comment by mklement0** [comment]
@iSazonov:  

In the context of _CSV_ files, specifically, which are _line-oriented_, _line_ terminator is the right term.

By contrast, by allowing _arbitrary_ terminator strings with `-Delimiter`, what a terminator terminates is no longer necessarily a _line_: with a terminator other than a newline (in any of its variations), any number of lines may then occur between instances of the terminator.  

In other words: the units of data may themselves be _multi-line_, so calling such a unit a _line_ is inappropriate.

That's why `awk` chose _record_, for instance, but my point is that it isn't necessary for the parameter name to reflect a term for the data unit, given that only _one_ kind of terminator is supported (for the implied lines / data units).

On a meta note: even though the label of your link suggests that it is to a specific comment on the issue page, the link is just to the issue page itself.
A recent post by @lzybkr exhibited the same problem.
How are you generating these links? Is this a GitHub bug?

**Comment by iSazonov** [comment]
@mklement0 You can copy such links from post header datetime string "mklement0  commented _**9 minutes ago**_". 
It is GitHub bug.

**Comment by shreyjain362** [comment]
The issue is still not resolved. Why has it been marked "Resolution Fixed"?

**Comment by shreyjain362** [comment]
The issue is still not resolved. Why has it been marked "Resolution Fixed"? @mklement0 @iSazonov

**Comment by mklement0** [comment]
@shreyjain362, it has been fixed in PowerShell 7 (which this repo is solely devoted to) - at least judging by running the original reproduction steps.

Note that _Windows PowerShell_ won't receive this fix, because it is no longer actively developed and only receives security-critical fixes.
