### ISSUE TITLE
New-SelfSignedCertificate not recognized on macOS

### ISSUE THREAD

**Issue by bgever** [PowerShell/PowerShell#3715]
My ASP.NET Core 1.1 project is intended to be used cross-platform. To help getting started with development of the website I'd like to include a PS script to setup the appropriate SSL certificate for development purpose.

For this scenario it would be perfect if I can use `New-SelfSignedCertificate` on both macOS and Windows, so that I don't need to deal with OpenSSL.

`New-SelfSignedCertificate` shipped first with Win2012 & Win8 releases of PowerShell. [(MSDN link)](https://technet.microsoft.com/en-us/library/hh848633(v=wps.620))

Steps to reproduce
------------------

Execute `New-SelfSignedCertificate` on macOS.

Expected behavior
-----------------

Command to execute.

Actual behavior
---------------

```powershell
> New-SelfSignedCertificate                             
New-SelfSignedCertificate : The term 'New-SelfSignedCertificate' is not recognized as the name of a cmdlet, function, s
cript file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
rect and try again.
At line:1 char:1
+ New-SelfSignedCertificate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-SelfSignedCertificate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-alpha                                                                             
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   3.0.0.0                                                                                 
GitCommitId                    v6.0.0-alpha.18                                                                         
CLRVersion                                                                                                             
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

**Comment by iSazonov** [comment]
The cmdlet is located in PKI module that is not part of the repo.

**Comment by SteveL-MSFT** [comment]
PKI module is owned by another team in Windows.  Would be great to have a cross platform module for this cmdlet on the Gallery.

**Comment by bgever** [comment]
Thanks for the prompt responses! Is that other team aware of this, and is it possible to pass this feature request to them?

**Comment by SteveL-MSFT** [comment]
@bgever best thing to do is post a request on the [Windows Server Uservoice](https://windowsserver.uservoice.com/forums/295047-general-feedback)

**Comment by bgever** [comment]
Thanks, requested here: https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/19187815-make-powershell-pki-module-cross-platform-with-ps

**Comment by iSazonov** [comment]
I think many MSFT teams and third party teams start once they get stable version of PoweShell Core. So welcome test and contribute in PowerShell Core.

**Comment by johncrim** [comment]
I haven't tested it yet, but this project looks promising and well-written:

https://github.com/rjmholt/SelfSignedCertificate

It is not a drop-in replacement for `New-SelfSignedCertificate`, but provides similar cert generation functionality using .NET Core native functionality. It doesn't store the generated certs in Windows cert storage.

**Comment by SteveL-MSFT** [comment]
@johncrim, that module was written by @rjmholt who is a member of the PowerShell Team.  It is only intended for use by our tests that require a self-signed cert and not intended to be used in production.  (Production systems generally should be using real-signed certs...)

**Comment by Archehandoro** [comment]
@SteveL-MSFT but if it was to be used for LDAP, like shown in the tutorial here https://docs.microsoft.com/en-gb/azure/active-directory-domain-services/tutorial-configure-ldaps#create-a-certificate-for-secure-ldap, would then the module work as intended?

**Comment by jrnkng** [comment]
Anyone has any updates on this/

**Comment by bgever** [comment]
@jrnkng if you're looking for a simple way to generate cross platform self-signed certificates for development purpose, then this `mkcert` utility is a possible alternative: https://github.com/FiloSottile/mkcert It's what I started to use instead of PowerShell.
