### ISSUE TITLE
Can't update to alpha18 in .NET project

### ISSUE THREAD

**Issue by erwinwildenburg** [PowerShell/PowerShell#3717]
Steps to reproduce
------------------
Start a new project with the following packages:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="6.0.0-alpha18" />
  </ItemGroup>
</Project>
```

Expected behavior
-----------------
The packages restore normally.

Actual behavior
---------------
Errors which block using powershell alpha18 with .NET:
```
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.PowerShell.ConsoleHost (>= 6.0.0)' for '.NETCoreApp,Version=v1.1'. [C:\Users\x\Source\Repos\x\src\BuildEntry\BuildEntry.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.PowerShell.Security (>= 6.0.0)' for '.NETCoreApp,Version=v1.1'. [C:\Users\x\Source\Repos\x\src\BuildEntry\BuildEntry.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.PowerShell.Commands.Utility (>= 6.0.0)' for '.NETCoreApp,Version=v1.1'. [C:\Users\x\Source\Repos\x\src\BuildEntry\BuildEntry.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.PowerShell.Commands.Management (>= 6.0.0)' for '.NETCoreApp,Version=v1.1'. [C:\Users\x\Source\Repos\x\src\BuildEntry\BuildEntry.csproj]
```

Environment data
----------------

```
Name                           Value
----                           -----
PSEdition                      Core
WSManStackVersion              3.0
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
SerializationVersion           1.1.0.1
GitCommitId                    v6.0.0-alpha.18
PSVersion                      6.0.0-alpha
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
```

**Comment by iSazonov** [comment]
We are moving to .Net Core 2.0. So you can build based on this repo sources or wait Alfa.19 or Beta1. Docs isn't still updated too.

**Comment by gorankor** [comment]
I have the same issue, but I am trying to do this on Linux. I am following this document:

https://github.com/PowerShell/PowerShell/tree/master/docs/host-powershell

The errors I get are very similar:

/disk/dotnet/sdk/2.0.0-preview1-005952/NuGet.targets(97,5): error : Unable to resolve 'Microsoft.PowerShell.Commands.Management (>= 6.0.0)' for '.NETCoreApp,Version=v2.0'. [/disk/PowerShell/test/Logic/Logic.csproj]
...
/disk/dotnet/sdk/2.0.0-preview1-005952/NuGet.targets(97,5): error : Unable to resolve 'Microsoft.WSMan.Runtime (>= 6.0.0)' for '.NETCoreApp,Version=v2.0'. [/disk/PowerShell/test/Logic/Logic.csproj]

I tried editing the _Logic.csproj_ file and using various target framework specifications ("netcoreapp2.0" and "netstandard1.6"), but to no avail. I also tried specifying the required versions as "6.*", but that also does not help. Previously this worked OK.

How can one do this now without having to wait for the mentioned releases?

**Comment by iSazonov** [comment]
Beta.1 is already out! Please download and test.

**Comment by gorankor** [comment]
If you mean Beta.1 of PowerShell, then I can add this: I have cloned the repository today (May 10th at about 09:20), built it myself and version shows as:

PS /disk/PowerShell>      $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Linux 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

And I still have the issue.

**Comment by iSazonov** [comment]
@gorankor Thanks for clarify!
I don't still see that new packages is published.

/cc @daxian-dbw

**Comment by daxian-dbw** [comment]
This is a known issue and should be fixed by #3678 
Basically, `dotnet pack` stopped applying version suffix to referenced projects since it moved to MSBuild. We didn't know this issue until finding out alpha.18 nuget packages were broken.
Relevant dotnet issues: https://github.com/NuGet/Home/issues/4337 and https://github.com/NuGet/Home/issues/3953

**Comment by daxian-dbw** [comment]
BTW, we will publish nuget packages for beta.1 release soon, but it requires dotnet-cli 2.0 preview to use those packages because they target `netcoreapp2.0`. If you want to target `netcoreapp1.1`, please use `alpha.17` package for now.

**Comment by daxian-dbw** [comment]
@erwinwildenburg the `6.0.0-beta.1` NuGet packages are now published to powershell-core feed.

**Comment by daxian-dbw** [comment]
Given the provided information, I'm closing this issue. Feel free to comment if you have any concerns/questions.

**Comment by daxian-dbw** [comment]
> I have the same issue, but I am trying to do this on Linux.

@gorankor Sorry that I missed your comments. It's an unfortunate known issue that the published NuGet packages don't work on Unix plats. The NuGet packages on powershell-core feed so far only contain windows runtime assemblies. We are actively working on resolving this, and it's tracked by #3417. Feel free to leave comments/discuss in that issue.

**Comment by gorankor** [comment]
Thank you - I will post anything else in #3417 if needed.
