### ISSUE TITLE
-rf flag for remove-item cmdlet

### ISSUE THREAD

**Issue by xoviat** [PowerShell/PowerShell#3718]
Can we please have this?

**Comment by iSazonov** [comment]
@xoviat Could you clarify do you want "flag" or "function"?

**Comment by xoviat** [comment]
Current behaviour:

```
rm -r -Force dir
```

Requested:
```
rm -rf dir
```

To answer your question, I want a flag. the function and options are already there, they just need to be combined.

**Comment by xoviat** [comment]
And I'm not suggesting changing any existing functionality, only adding the option.

**Comment by iSazonov** [comment]
It is duplicate  #2199
