### ISSUE TITLE
Side-by-side insallation of v5 and v6 on Windows

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#3720]
So we can **confidently** break the behavior and leave the old Enterprise users can still use the old one.

Also...

 * .ps1 --> V5
 * .ps6 --> V6
 * .ps7 --> V7

**Comment by MaximoTrinidad** [comment]
In my opinion! I would leave the *.ps1 extension and rather use the '#requires -Version X' statement so I can at least provide some useful cross-platform scripting.  But, it only works in script file.  I would love this statement with the '-Version' to work in modules.

At the same time, we can always figured out other ways to make it work.

:)

**Comment by iSazonov** [comment]
It is duplicate https://github.com/PowerShell/PowerShell/issues/2013

**Comment by be5invis** [comment]
@iSazonov It is not a duplicate.
The main issue is about installing Two versions side-by-side, so that we can finally confidently introduce breaking changes. For scripts, `#REQUIRING` or changing extension would be both fine to distinct "Old" and "New" scripts.

**Comment by be5invis** [comment]
@iSazonov And, you know, the story of Edge and IE.

**Comment by iSazonov** [comment]
@be5invis You can install PowerShell Core and use it without removing Windows PowerShell.

**Comment by be5invis** [comment]
@iSazonov What would happen if PSv6 has shipped to Windows, like in RS3 or RS4?

**Comment by lzybkr** [comment]
Could but maybe not should. We can use Python 2 and 3 as an example, I'm still not sure that community has any consensus on their choice.
