### ISSUE TITLE
PowerShell Core availability on Ubuntu 17.04 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3721]
Just want to know the plan for supporting PowerShellCore in the upcoming Ubuntu Version 17.04.

I tried to installed it but I getting some library errors:
"Package libicu55 is not installed."

Steps to reproduce
------------------
1. Download PowerShell v6.0.0.0-alpha.18-1ubuntu1.16.04.1_amd64.deb
2. sudo dpkg -i powershell v6.0.0.0-alpha.18-1ubuntu1.16.04.1_amd64.deb

Expected behavior
-----------------
Installation to complete without errors

Actual behavior
---------------
"Package libicu55 is not installed."

Environment data
----------------
Ubuntu 17.04

```powershell
> $PSVersionTable

```

**Comment by iSazonov** [comment]
A simple rule is - first CoreFX/CoreCLR should add support a planform.

**Comment by pcgeek86** [comment]
@iSazonov perhaps add the `Resolution - External` label?

**Comment by iSazonov** [comment]
@pcgeek86 The Issue is "Waiting external" 😄

**Comment by MaximBar** [comment]
Hi, 
I've chatted with the corefs guys and they said that the latest portable dotnet core 2.0 works fine on Ubuntu 17.04:
[](https://github.com/dotnet/corefx/issues/20562#issuecomment-305555951)
and the PS run (not install) file  AppImage PowerShell-6.0.0-beta.1-x86_64.AppImage also works with Ubuntu 17.04

but not the other install .deb files.
So it's now should be possible to port PS to Ubuntu 17,04.

**Comment by iSazonov** [comment]
@joeyaiello @TravisEz13 CoreFX team support Ubuntu 17,04. What is a PowerShell team plan?

**Comment by iSazonov** [comment]
@joeyaiello @TravisEz13 @SteveL-MSFT  CoreFX team support Ubuntu 17,04. What is a PowerShell team plan?

Update: I see CoreFX team change their support policy. For .Net Core 1.0.1 they support _specific_ versions. [For .Net Core 2.0](https://github.com/dotnet/core/blob/master/roadmap.md#net-core-20---supported-os-versions) they indicate the _minimum_ OS version.

**Comment by joeyaiello** [comment]
Not sure what the problem is here, but we should get this working.

Also, I should read the entirety of an issue before I start adding labels. ;)

**Comment by MaximoTrinidad** [comment]
So, what's the steps to install PowerShell in Ubuntu 17.04?  

As of now, with PowerShell Beta.2, I'm getting the following message with .Net Core 2.0 Preview installed:

The following packages have unmet dependencies:
 powershell : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.

:)

**Comment by iSazonov** [comment]
@joeyaiello I expect that we should have new clear policy in our docs to support different OS versions. Because now dotnet support is based on minimal OS version our current policy "we follow CoreFX" is too vague - unlike a CoreFX, we have OS version dependencies.

**Comment by joeyaiello** [comment]
Adding context from the duped issue. Apparently, running PowerShell dumps this:

`powershell: pal_io.cpp:758: int64_t SystemNative_SysConf(SysConfName): Assertion `false && "Unknown SysConfName"' failed.`

**Comment by TravisEz13** [comment]
Talked to @janvorli and by portable, he means targeting runtime id `linux-x64` and standalone (specify the runtime id when publishing, which will inclued all the assemblies and native shared libraries)

**Comment by borgdylan** [comment]
When running a generic app on .NET Core 1.1 and 2.0 I get no issues on my 17.04 machine, the same machine of the "duped" issue. The interface for certain system calls gets updated after a few kernel releases. I'd recommend depending on common shell builtins for getting system information or at least using the latest .NET Core at all times which does get tested on newer kernels AFAIK. I do realise that it is hard tracking a kernel that is not maintained in house

**Comment by iSazonov** [comment]
@TravisEz13 Good catch! Should we create a tracking Issue for  `linux-x64`  ?

**Comment by borgdylan** [comment]
One of more problematic libraries is ICU which gets updated each year. There are ways to have an older version installed side by side.

**Comment by chuanjiao10** [comment]
remind:
debian9 formal edition will release on july , please pay attention to compatible

**Comment by janvorli** [comment]
@chuanjiao10 we are already compatible with debian 9.

**Comment by janvorli** [comment]
@borgdylan CoreCLR is now resilient to ICU version, it should work with any future version up to version number 70, provided there is no breaking change in the interface. But the ICU doc says that stable APIs should stay in the future versions and we are using stable APIs only.

**Comment by TravisEz13** [comment]
@iSazonov We will try to come up with a plan and get back to you on how to track the work.  I changed this issue to an enhancement for now.

**Comment by TravisEz13** [comment]
@iSazonov I have filed an issue.  Thanks.

**Comment by iSazonov** [comment]
@MaximoTrinidad  See https://github.com/PowerShell/PowerShell/issues/3961 with PowerShell team plan.

**Comment by borgdylan** [comment]
The bug is because an incorrect string is being passed in: https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_io.cpp#L844 . The allowed strings are only three based on specific constants.

**Comment by SteveL-MSFT** [comment]
@borgdylan is there an issue opened for corefx?

**Comment by borgdylan** [comment]
I have opened an issue against corefx.

**Comment by iSazonov** [comment]
@borgdylan Please add cross link here to the Issue.

**Comment by TravisEz13** [comment]
https://github.com/dotnet/corefx/issues/21386
