### ISSUE TITLE
Bug: Get-Help -Category HelpFile returns nothing

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3722]
# Overview

In PowerShell Core Alpha 18 on Mac OS Sierra, I'm receiving no output from the `Get-Help -Category HelpFile` command. Possibly related to #3503. 

# Expected Behavior

The `Get-Help -Category HelpFile` command should return a list of conceptual help documents.

# Actual Behavior

No output is emitted from the command.

```powershell
~ sudo powershell
Password: ...
PS /Users/tsulli> Update-Help -Force
update-help : Failed to update Help for the module(s) 'Microsoft.PowerShell.Archive, Microsoft.PowerShell.Core, Microsoft.PowerShell.Host,                             Microsoft.PowerShell.Management, Microsoft.PowerShell.Security, Microsoft.PowerShell.Utility, PackageManagement, PowerShellGet, PSReadLine' with UI culture(s)         {en-US} : Access to the path '/usr/local/microsoft/powershell/6.0.0-alpha.18/en-US/Microsoft.PowerShell.Commands.Management.dll-Help.xml' is denied.                   At line:1 char:1                                                                                                                                                       + update-help -force
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
    + FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
PS /Users/tsulli> get-help -Category HelpFile
PS /Users/tsulli>
```

Cheers,
Trevor Sullivan

**Comment by MaximoTrinidad** [comment]
FYI 

In Windows build is working fine:
![helpfile_01_2017-05-07_14-18-40](https://cloud.githubusercontent.com/assets/19892435/25783850/087bf7d2-3331-11e7-91a9-f448562b77d7.jpg)

But, Not In Linux Ubuntu, as after completing 'Update-Help -force':
![nohelpcat_ 2017-05-07 14-20-52](https://cloud.githubusercontent.com/assets/19892435/25783854/21761ba0-3331-11e7-8e13-e0467bd842ff.png)

:)

**Comment by adityapatwardhan** [comment]
@pcgeek86 I believe this is fixed. Can you confirm using the latest release?

**Comment by SteveL-MSFT** [comment]
Works for me on Ubuntu16.04 and beta.4
