### ISSUE TITLE
Get-Help about_Classes does not return help

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#3728]
Steps to reproduce
------------------
Get-Help about_Classes

Expected behavior
-----------------
Information about classes is presented.

Actual behavior
---------------
PS C:\Program Files\PowerShell\6.0.0-alpha.18> get-help about_Classes

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
about_Classes                     HelpFile                            Describes how you can use classes to develop in Windows PowerShell
about_Classes                     HelpFile                            SHORT DESCRIPTION

Environment data
----------------

```
PSRemotingProtocolVersion      2.3
GitCommitId                    v6.0.0-alpha.18
PSVersion                      6.0.0-alpha
SerializationVersion           1.1.0.1
BuildVersion                   3.0.0.0
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
WSManStackVersion              3.0
PSEdition                      Core

**Comment by mklement0** [comment]
I see the same symptom on Windows, but neither on Linux nor on macOS.

**Comment by MaximoTrinidad** [comment]
Duplicate !!  

Get-Help About_Automatic_Variables does not dislay the full help content #3503

**Comment by joeyaiello** [comment]
Closing as a duplicate.
