### ISSUE TITLE
Documentation on number, locations, purpose, and names of profile scripts.

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#3729]
I have created all six (6) profile scripts for PowerShell 5 on Windows 10.
When I run PowerShell 6 on the same machine, it appears that none are used.
What are the profile scripts for PowerShell Core 6?
I have read that there was not full agreement on this issue between Window and Linux locations. Has this been resolved? If so, where can I find the result?

**Comment by mklement0** [comment]
As for the locations:

The `$PROFILE` variable, even though it is a `[string]`, contains all profile paths as note properties:

Use the following, platform-neutral command to list all profile paths:

```powershell
>  $PROFILE | Get-Member -Type NoteProperty | % Name | % { "$_ = $($PROFILE.$_)" }
```

On a Windows 10 machine, for instance, this yields:

```none
AllUsersAllHosts = C:\Program Files\PowerShell\6.0.0-alpha.18\profile.ps1
AllUsersCurrentHost = C:\Program Files\PowerShell\6.0.0-alpha.18\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts = C:\Users\jdoe\Documents\PowerShell\profile.ps1
CurrentUserCurrentHost = C:\Users\jdoe\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
```

On a macOS machine, you'll get something like:

```none
AllUsersAllHosts = /usr/local/microsoft/powershell/6.0.0-alpha.18/profile.ps1
AllUsersCurrentHost = /usr/local/microsoft/powershell/6.0.0-alpha.18/Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts = /Users/jdoe/.config/powershell/profile.ps1
CurrentUserCurrentHost = /Users/jdoe/.config/powershell/Microsoft.PowerShell_profile.ps1
```

On a Linux machine, you'll get something like:

```none
AllUsersAllHosts = /opt/microsoft/powershell/6.0.0-alpha.18/profile.ps1
AllUsersCurrentHost = /opt/microsoft/powershell/6.0.0-alpha.18/Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts = /home/jdoe/.config/powershell/profile.ps1
CurrentUserCurrentHost = /home/jdoe/.config/powershell/Microsoft.PowerShell_profile.ps1
```

---

Contrast this with a Windows 10 Windows PowerShell v5.1 installation:

```none
AllUsersAllHosts = C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
AllUsersCurrentHost = C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell_profile.ps1
CurrentUserAllHosts = C:\Users\jdoe\Documents\WindowsPowerShell\profile.ps1
CurrentUserCurrentHost = C:\Users\jdoe\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

**Comment by Liturgist** [comment]
Many thanks, mklement0.

**Comment by theking2** [comment]
PS1 files stored in the CurrentUserCurrentHost cannot be executed as they are not found. 
For instance a PS1 script Restart-Process.PS1 stored in C:\Users\%username%\Documents\WindowsPowerShell cannot be located:

Restart-Process : The term 'Restart-Process' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Restart-Process
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Restart-Process:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
