### ISSUE TITLE
Get-ChildItem -Recurse shouldn't quietly ignore -Include and -Exclude when -LiteralPath is used instead of -Path

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3730]
Even without using wildcards, `Get-ChildItem -Recurse` allows matching items on every level of the target hierarchy, possibly filtered with `-Include` and `-Exclude`.

However, if you use `-LiteralPath` rather than the (implied) `-Path` parameter, `-Include` and `-Exclude` are _quietly ignored_:

_If_ there's a good reason for this behavior (none that I'm aware of), then at the very least a _warning_ about `-Include` / `-Exclude`  getting ignored should be issued, or a separate parameter set should prevent combining `-LiteralPath` with `-Include` / `-Exclude`.

Steps to reproduce
------------------

```powershell
Get-ChildItem              $PSHOME -Recurse -Exclude *   # implies -Path $PSHOME
Get-ChildItem -LiteralPath $PSHOME -Recurse -Exclude *
```

Expected behavior
-----------------

Both calls should yield _no_ output, because all items should be excluded by virtue of `-Exclude *`.

Actual behavior
---------------

The 2nd command, due to `-Exclude *` getting _ignored_, outputs the entire subtree of `$PSHOME`.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on macOS 10.12.4
PowerShell Core v6.0.0-alpha (v6.0.0-alpha.18) on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by SteveL-MSFT** [comment]
This appears to be a regression from v5 (repros with v5.1)

**Comment by nightroman** [comment]
> This appears to be a regression from v5 (repros with v5.1)

From my observations, it worked as expected in PS v5 Preview. So something changed exactly in v5 Preview -> v5 RTM.
