### ISSUE TITLE
Cmdlets that takes bytes as input

### ISSUE THREAD

**Issue by be5invis** [PowerShell/PowerShell#3731]
This is an follow-up to #1908 and #2145.

For `Native | PS` piping, we should able to write cmdlets that takes **raw bytes** and returns whatever they like.

**Comment by BrucePay** [comment]
I'm not sure I understand the intent here. Can you provide some examples illustrating what you mean? Thanks.

**Comment by powercode** [comment]
One example that I have run into is `p4.exe` where `-G` makes it produce python dictionaries as it's record instead of text. And to produce .net objects from that, it would be really nice to have simple access to the raw stream of bytes.

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this be closed now with the `PSNativeCommandPreserveBytePipe` experimental feature?

**Comment by StevenBucher98** [comment]
Yes fixed with https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3#psnativecommandpreservebytepipe
