### ISSUE TITLE
ScriptsToProcess not honored when Import-Module is passed -Version param

### ISSUE THREAD

**Issue by Matteo-T** [PowerShell/PowerShell#3738]
Steps to reproduce
------------------
- Install SqlServer module from PSGallery (I doubt the issue is specific to my module, though)
- Open PowerShell (full .Net, I'm on Win10 using the PowerShell that comes with the OS)
   PowerShell -executionpolicy bypass
- Import-Module SqlServer -Verbose
  (observe that SqlServer.ps1, listed in the SqlServer.psd1 manifest file, is loaded during import)
- Close PowerShell
- Restart PowerShell (same as above)
- Import-Module SqlServer -Verbose -Version 21.0.17099

Expected behavior
-----------------
The SqlServer.ps1 script is loaded

Actual behavior
---------------
The SqlServer.ps1 script is NOT loaded

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16192.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16192.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
@Matteo-T Thanks for your report! Could you check on latest PowerShell Core?

**Comment by Matteo-T** [comment]
My module does not work on PowerShell Core, so I'm not sure how that would help... I'm not sure I'll have time to create a dummy repro (i.e. a dummy module) that works on PowerShell Core any time soon, but if I have to...

**Comment by megamorf** [comment]
This repo is for PowerShell Core only. Please report regular PowerShell issues on the uservoice website:

https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by iSazonov** [comment]
@Matteo-T Please test after PowerShell Core Beta1 release (in the coming days).
And yes, we can report on UserVoice.

**Comment by Matteo-T** [comment]
Sorry, I did not know this was for "Core" only. I was told to come here, but I guess I was told incorrectly. I'll try the UserVoice thing...

**Comment by joeyaiello** [comment]
@megamorf @Matteo-T for bugs that are almost certainly applicable to both editions of PowerShell, it's perfectly fine to file them here. I suspect that this one repros on Core 6 just fine, and given the importance of `Import-Module` we should probably get it fixed (assuming it *does* repro). 

I'll build a basic repro on my box right now.

**Comment by joeyaiello** [comment]
Yup, totally repros on `6.0.0-alpha.18` and `6.0.0-beta.1`:

```
C:\> mkdir C:\temp\VersionParam
C:\> cd temp\VersionParam
C:\temp\VersionParam> 1 | Out-File Output1.ps1
C:\temp\VersionParam> New-ModuleManifest VersionParam.psd1 -ScriptsToProcess .\Output1.ps1
C:\temp\VersionParam> Import-Module .\VersionParam.psd1
1
C:\temp\VersionParam> Remove-Module VersionParam
C:\temp\VersionParam> Import-Module .\VersionParam.psd1 -Version 1.0
C:\temp\VersionParam> Get-Module VersionParam

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0        VersionParam
```
