### ISSUE TITLE
PSVersion in `$PSVersionTable` is hard-coded in PSVersionInfo.cs

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3739]
> private static SemanticVersion s_psV6Version = new SemanticVersion(6, 0, 0, "alpha");

It should not be a hard-coded, but instead should be generated based on the `GitCommitId`.

**Comment by iSazonov** [comment]
@daxian-dbw I can fix this in #3690

**Comment by iSazonov** [comment]
We agreed to break #3690 down into a few small parts.
