### ISSUE TITLE
ValidateSet should support a dynamically generated set

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#3744]
People often use dynamic parameters so they can dynamically generate a `ValidateSet` attribute.

We should provide a simpler way to do this. One option is to accept a scriptblock:

```powershell
param(
    [ValidateSet( { Get-ChildItem -ah | ForEach-Object Name } )]
    $HiddenFileName
)
```

**Comment by lfshr** [comment]
This is a much better solution. Well played @Izybkr. I like it!

**Comment by lzybkr** [comment]
We should also consider binary cmdlets. One option is to accept a type that implements an interface, something like:

```c#
public interface IValidateSetGenerator
{
    IEnumerable<string> Get();
}
public class MyValidateSetGenerator : IValidateSetGenerator
{
    public IEnumerable<string> Get()
    {
        yield return "Something";
    }
}
...
    [Parameter()]
    [ValidateSet(typeof(MyValidateSetGenerator)]
    public string Something { get; set; }
```

This could probably work in PowerShell too (the interface would be defined in System.Management.Automation.dll.

I think we'd need a way of passing `$PSBoundParameters` to truly cover most of the scenarios where people are resorting to dynamic parameters today.

**Comment by iSazonov** [comment]
Recently I played with this and it seems like it might be too expensive  due to IntelliSense.

**Comment by powercode** [comment]
@iSazonov What is to expensive?

**Comment by iSazonov** [comment]
@powercode IntelliSense can call attributes very often. ValidateSet with script block becomes similar to ValidateScript (can run unpredictably long).


Perhaps we should do only IValidateSetGenerator (not script block) because we want support interfaces in PowerShell classes.

Also we could add IValidateSetGenerator not only in ValidateSet attribute: ValidateScript, ValidatePattern, ???.

**Comment by lfshr** [comment]
@iSazonov I don't think that would be much of a problem. Most people know not to have long-running commands in intellisense code. People are already working around this issue using the less-friendly dynamicparam block and passing a ValidateSetAttribute to the attribute collection.

**Comment by lfshr** [comment]
So two new overloads for ValidateSetAttribute:
```c#
ValidateSetAttribute(ScriptBlock sb)
```
and
```c#
ValidateSetAttribute(IValidateSetGenerator g)
```

**Comment by iSazonov** [comment]
IValidateSetGenerator vs IValidateSetEnumerator ?

**Comment by lfshr** [comment]
@iSazonov maybe even **IDynamicValidateSet**?

**Comment by iSazonov** [comment]
It looks like it is from DynamicParams but it is not related directly. Also we have RFC for Dynamic Keywords so we should avoid "Dynamic" term to eliminate confusion.

**Comment by lfshr** [comment]
@iSazonov IDynamicValidateSet?

**Comment by lzybkr** [comment]
@lfshr - C# requires `typeof(MyValidateSetGenerator)` because `MyValidateSetGenerator` is not an expression.

The interface name should probably not end in `Enumerator` because the interface does not define an enumerator.

**Comment by iSazonov** [comment]
Maybe IValidateSetValuesGetter

**Comment by lfshr** [comment]
@lzybkr Sorry. Idiot moment.

**Comment by lfshr** [comment]
I agree with @lzybkr, something like `IValidateSetGenerator` is a good shout.

**Comment by oising** [comment]
Is this still up for grabs? I'm looking for something small to start with.

**Comment by iSazonov** [comment]
Welcome to code review!

**Comment by rafaelc81** [comment]
maybe you can help me out with my challange. I like to set ValidateSet to run my "example.ps1 -region eu-cental-1" and get the AWS regions

Eg:

Param(
    [parameter(Mandatory=$true)]
    [ValidateSet((Get-AWSRegion).region)]
    [String[]]
    $region
)

process {
# do whatever
}

**Comment by vexx32** [comment]
I don't see any link to the relevant PR, but it appears to need a script block, so you would write:
```
[ValidateSet({ (Get-AwsRegion).Region })]
```

**Comment by vexx32** [comment]
@lzybkr a PR is mentioned in this thread, but I don't see any links to it. Did this end up getting implemented?

**Comment by iSazonov** [comment]
You need to implement `IValidateSetValuesGenerator`. See:
https://github.com/iSazonov/PowerShell/blob/65349de2b25022092213d86cfc1f5dfe0c92cbc6/test/powershell/Language/Classes/Scripting.Classes.Attributes.Tests.ps1#L273

**Comment by vexx32** [comment]
@rafaelc81 see here for the example that was merged into documentation after the PR was merged. 

https://github.com/PowerShell/PowerShell-Docs/pull/3133/files?short_path=8b392e6#diff-8b392e69e97629458a3c80ee54386057

**Comment by OlsonDev** [comment]
The example in the docs looks nothing like the example the OP of this issue wanted. The OP asks for a script block, and the solution provided is a full on syntax-verbose class.

I can't get an example like the script block to work. Was that implemented or only the syntax-verbose class version?

If not, are there any plans to support the significantly more terse syntax? Should another issue be opened?

Thanks!

**Comment by iSazonov** [comment]
@OlsonDev The issue description is misleading. We only implemented a variant based on `IValidateSetValuesGenerator` interface until we receive more feedback. Feel free open new issue with the description of the necessary feature.

**Comment by vexx32** [comment]
Indeed. It should be possible to borrow portions of the code from `[ArgumentCompleter()]` for this purpose; it also takes a script block and apparently applies it to the method defined in `IArgumentCompleter`

**Comment by iSazonov** [comment]
@vexx32 There is samples in attributes.cs file how to use execution context. I assume that the tests will be most of this work and not the code itself. :-)

**Comment by OlsonDev** [comment]
@iSazonov @vexx32 Thanks, I created [the aforementioned issue here](https://github.com/PowerShell/PowerShell/issues/8651).
