### ISSUE TITLE
6.0 beta no longer compatible with OSX 10.11?

### ISSUE THREAD

**Issue by latkin** [PowerShell/PowerShell#3749]
Steps to reproduce
------------------
Running on OSX 10.11.6
Download and install [`powershell-6.0.0-beta.1-osx.10.12-x64.pkg`](https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-beta.1/powershell-6.0.0-beta.1-osx.10.12-x64.pkg)
Open Terminal, run `powershell`

Expected behavior
-----------------
Powershell 6.0 beta 1 runs.

Documentation still indicates 10.11 support: https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#macos-1011

Actual behavior
---------------
Fails to start:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/microsoft/powershell/6.0.0-beta.1/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/microsoft/powershell/6.0.0-beta.1/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

From installer file name I am wondering if 10.11 support has been dropped, and only 10.12 is now supported?

Environment data
----------------
OSX 10.11.6
Note that I have successfully installed and run many of the alpha releases.

**Comment by vors** [comment]
I think it's related to the switching to dotnet core 2.0
Previously dotnet version were compatible between 10.11 and 10.12 and we basically used it interchangeable. We should be able to create a build for 10.11.

Thank you for bringing it to our attention!

**Comment by daxian-dbw** [comment]
The supported OS versions for Mac OS X is 10.12+ for .NET Core 2.0, see [Supported OS Versions](https://github.com/dotnet/core/blob/master/roadmap.md#net-core-20---supported-os-versions).
PowerShell Core beta.1 moved to .NET Core 2.0, and thus can only support OSX 10.12+.

**Comment by latkin** [comment]
@daxian-dbw thats fine, I recommend you update your documentation accordingly, and make it clear to users. Nowhere in any of yesterday's announcements was it mentioned that alpha users might not be able to upgrade to beta.

**Comment by daxian-dbw** [comment]
@latkin Yeah, you are right, we should have mentioned those "deal breakers". /cc @SteveL-MSFT @joeyaiello maybe we should add this to [Kown Issues](https://github.com/PowerShell/PowerShell/blob/master/docs/KNOWNISSUES.md).

The doc update PR #3748 was sent out yesterday but it didn't get approved until this morning. Now it has been merged.

**Comment by cobaltjacket** [comment]
Why is this issue closed? This is a drastic requirement change, isn't it?

**Comment by SteveL-MSFT** [comment]
@cobaltjacket this is closed as there isn't anything we can do in this repo to support it.  you'll need to open an issue in the [corefx](https://github.com/dotnet/corefx) repo and get them to support 10.11
