### ISSUE TITLE
debian stretch, beta.1 seg fault after 30 seconds

### ISSUE THREAD

**Issue by allywilson** [PowerShell/PowerShell#3750]
Steps to reproduce
------------------
launch powershell, wait 30 seconds

Expected behavior
-----------------
Stay open

Actual behavior
---------------
Exits after 30 seconds, seg fault.

Environment data
----------------
Debian Stretch, powershell 6 beta.1

```powershell
> $PSVersionTable
PSVersion                      6.0.0-beta                                      
PSEdition                      Core                                            
BuildVersion                   3.0.0.0                                         
CLRVersion                                                                     
GitCommitId                    v6.0.0-beta.1                                   
OS                             Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0 
```
[posh-strace.txt](https://github.com/PowerShell/PowerShell/files/988716/posh-strace.txt)

**Comment by allywilson** [comment]
Reading some of the other issues (which are for Win7 and MacOS) I tried installing dotnet 2.0 (specifically: 2.0.0-preview2-005905), but same thing unfortunately.

**Comment by daxian-dbw** [comment]
I don't think Debian stretch (Debian 9) is a supported OS of .NET Core, but we need to confirm with folks from .NET team.
@JamesWTruher any comments?

**Comment by iSazonov** [comment]
Related https://github.com/dotnet/corefx/issues/13221 
Possible workaround https://github.com/dotnet/corefx/issues/8951

**Comment by allywilson** [comment]
Workaround worked like a charm!

Uninstalled curl and libcurl3 via apt (this also removes powershell beta.1 [and spotify, but that's not relevant]).

Downloaded and installed curl and libcurl3 from here: https://packages.debian.org/stable/allpackages

Installed powershell beta.1 via apt again, and it's stayed open :+1: 

Thanks again!
