### ISSUE TITLE
PowerShell Beta Linux Direct install didn't remove Alpha18

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3758]
During Alpha18 I use the Direct Download for Ubuntu 16.04.

Steps to reproduce
------------------
sudo apt update
sudo apt upgrade  --> which found PowerShell Beta and proceed to replace Alpha18

Expected behavior
-----------------
It should have removed the previous version of PowerShell (Alpha18 in my case)

Actual behavior
---------------
It couldn't remove some folders.

![powershell6 install errors 2017-05-10 07-24-58](https://cloud.githubusercontent.com/assets/19892435/25924301/0bf820e4-35b0-11e7-9cbe-b9735d7fc70e.png)

![powershell6 install errors 2_2017-05-10 07-24-58](https://cloud.githubusercontent.com/assets/19892435/25924315/1604920c-35b0-11e7-8a40-1abad203ce14.png)

Environment data
----------------
Ubuntu 16.04.2 LTS

```powershell
PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-beta                                                                              
PSEdition                      Core                                                                                    
BuildVersion                   3.0.0.0                                                                                 
CLRVersion                                                                                                             
GitCommitId                    v6.0.0-beta.1                                                                           
OS                             Linux 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017                      
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0



```

**Comment by SteveL-MSFT** [comment]
I didn't get a repro.  Did you do the `apt-get upgrade` within alpha.18 (while powershell was still running)?

**Comment by MaximoTrinidad** [comment]
I've been doing the manual dpkg and then the apt install on Alpha17.  Then I use the direct download instructions for Alpha18 with no errors during the upgrade.

Now, doing the sudo apt upgrade, is showing errors that can't remove some folder. But PowerShell Beta is installed and seems working.

I'm not sure what happened!

I did the Direct Download on my Windows 10 Bash and works fine.

:)

**Comment by chuanjiao10** [comment]
powershell 6.0 alpha version have this little trouble in centos also.
I use rpm -Uvh new-powershell-release.rpm
Old file deleted, but old directory still, did not remove clean.

**Comment by SteveL-MSFT** [comment]
I'm seeing the same thing on Ubuntu14.04.  The folders being left behind appear to be created by PowerShellGet.

cc @bmanikm

**Comment by bmanikm** [comment]
PowerShellGet uses New-Item and Copy-Item cmdlets to install/save the modules.

https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/PSModule.psm1#L13948
https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/PSModule.psm1#L13968

Perhaps, an additional step is required in the build step to apply the required permissions on all directories and files under $PSHome directory.

**Comment by MaximoTrinidad** [comment]
FYI 

I had to manually (with privilege) uninstall the beta, and remove the leftover folders so I can do the 'sudo apt update' followed by the 'sudo apt upgrade'.

I have to say that I love having PowerShell added to the Ubuntu repository.  I just run the two commands above and PowerShell gets installed.

Thanks to that!!
:)

**Comment by joeyaiello** [comment]
This is definitely fixed/irrelevant now.
