### ISSUE TITLE
Package names for SuSe and CentOS still use "_" - "6.0.0_beta.1"

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3760]
From https://github.com/PowerShell/PowerShell/pull/3748#discussion_r115657073

powershell-6.0.0_beta.1-1.el7.centos.x86_64.rpm   ->  powershell-6.0.0-beta.1-1.el7.centos.x86_64.rpm 
powershell-6.0.0_beta.1-1.suse.42.1.x86_64.rpm  -> powershell-6.0.0-beta.1-1.suse.42.1.x86_64.rpm

/cc @TravisEz13

**Comment by SteveL-MSFT** [comment]
cc @joeyaiello seems like we should standardize on using dashes unless there's a specific convention for centos/suse to use underscores

**Comment by iSazonov** [comment]
[Guidelines for Naming Fedora Packages](https://fedoraproject.org/wiki/Packaging:Naming?rd=Packaging:NamingGuidelines)
> When naming packages for Fedora, the maintainer must use the dash '-' as the delimiter for name parts. The maintainer must NOT use an underscore '_', a plus '+', or a period '.' as a delimiter. Version numbers used in compat libraries do not need to omit the dot '.' or change it into a dash '-' (see  Multiple packages with the same base name for more info on this case). 

>There are a few exceptions to the no underscore '_' rule. 
- httpd, pam, and SDL addon packages are excluded, refer to " Addon Packages (httpd, pam and SDL) ". 
- packages that are locale specific, and use the locale in the name are excluded, refer to " Addon Packages (locale) ". 
- Compat packages where the base package name ends in a digit. refer to " Multiple packages with the same base name" 
- packages where the upstream name naturally contains an underscore are excluded from this. Examples of these packages include:

**Comment by TravisEz13** [comment]
I believe this has been fixed by this commit.

**Comment by iSazonov** [comment]
@TravisEz13 Could you please link the PR/commit?

**Comment by TravisEz13** [comment]
updated my comment

**Comment by iSazonov** [comment]
deb packages still have "_" in name powershell_6.0.1-1.ubuntu.17.04_amd64.deb

**Comment by TravisEz13** [comment]
If there is not an issue open for that can your file one.  This issue was for RedHat packages.

**Comment by iSazonov** [comment]
Done #6137
