### ISSUE TITLE
newly increased a switch parameter to Get-ChildItem, pass through (or not) a directory symbolic link

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#3761]
Q:How to find any ps1 file?
A:(Get-ChildItem / -Recurse -File ).Extension -match 'ps1' 

but this command is circling in centos.
in my test,powershell exhausted memory,killed by kernel.

ls -la /proc/1
#return:
lrwxrwxrwx.   1 root root 0 5月  11 20:52 cwd -> /

#1958 

 
@daxian-dbw 
@iSazonov  
@SteveL-MSFT  
@jeffbi 
@jaraco 

Steps to reproduce
------------------
Get-ChildItem /proc -Recurse
#Dead loop

Get-ChildItem / -Recurse
#3697 create a trap for users, who use this command

Environment data
----------------
centos 7.3 1611

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-beta                                                                                                        
PSEdition                      Core                                                                                                              
BuildVersion                   3.0.0.0                                                                                                           
CLRVersion                                                                                                                                       
GitCommitId                    v6.0.0-beta.1                                                                                                     
OS                             Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017                                              
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0   

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by iSazonov** [comment]
"Get-ChildItem /" read and convert to psobjects in memory all file names from file system!

**Comment by chuanjiao10** [comment]
I would like to exclude the `proc` directory, but powershell can not do it.
see #3762

**Comment by jeffbi** [comment]
@iSazonov And then some. Since `Get-ChildItem` follows symlinks any directory that has a symlink pointing to it will have its contents enumerated at least twice: once for the actual directory and again for each symlink that points to it.

The `/proc` directory is particularly problematic in that each of the process subdirectories has a symlink to the root directory, which will eventually get back to `/proc` guaranteeing an endless loop.

I think in the fix for #1958 I should have added additional code that prevented following symlinks for anything but the path specified with the cmdlet's `-Path` parameter.

**Comment by iSazonov** [comment]
@jeffbi It seems we already have old Issue for symlink loops.

**Comment by chuanjiao10** [comment]
@iSazonov : 
about symlink loops,i check again,not found.
i found jeffbi talk remove-item symlink loops in #3674. 

@jeffbi :  
in my test memory full,the additional code work? 
endless loop test command：
(Get-ChildItem / -Recurse -File -ErrorAction SilentlyContinue ).Extension -match 'ps1'

**Comment by daxian-dbw** [comment]
Closed via #3780
