### ISSUE TITLE
Get-ChildItem don't work and return error,when parameter -Exclude with -path /

### ISSUE THREAD

**Issue by chuanjiao10** [PowerShell/PowerShell#3762]
Steps to reproduce
------------------
Get-ChildItem -path "/" -Exclude "tmp"

Get-ChildItem -path "/" -Exclude "proc"

note:
The problem is only in the root directory,there is no problem with the subdirectory. 

Expected behavior
-----------------
mkdir /root/tmp
Get-ChildItem -path "/root" -Exclude "tmp" #return is normal

Get-ChildItem -path "/" #return is normal

Get-ChildItem -path "/" -Exclude "tmp" # I expect it to work properly

Actual behavior
---------------
Get-ChildItem : Cannot process argument because the value of argument "path" is not valid.

Environment data
----------------
centos 7.3 1611

Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0-beta                                                                                                        
PSEdition                      Core                                                                                                              
BuildVersion                   3.0.0.0                                                                                                           
CLRVersion                                                                                                                                       
GitCommitId                    v6.0.0-beta.1                                                                                                     
OS                             Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017                                              
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0   

reporter
----------------
By the chinese powershell study & research group. QQ group No. is 183173532

in 'vscode' or other open source project,in version release notes,bug reporter should be thank.
So I left a group name.

**Comment by iSazonov** [comment]
Related #3730

**Comment by chuanjiao10** [comment]
i tested,it fixed from version  v6.1.0-preview.1.   3Q !!!
by pr 5462 ?

**Comment by iSazonov** [comment]
Most likely in 5462.
