### ISSUE TITLE
PowerShell logging needs to go to syslog on non-Windows

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3766]
PowerShell currently has ETW logging on Windows, but no logging on non-Windows

**Comment by iSazonov** [comment]
Is there no plans to port ETW on Unix?

**Comment by SteveL-MSFT** [comment]
Perhaps consider using [OpenTracing ](https://github.com/opentracing/opentracing-csharp)

**Comment by lzybkr** [comment]
I believe .Net settled on [LTTng](http://lttng.org/) for logging, so it's worth a look too.

**Comment by daxian-dbw** [comment]
Closed via #5144 
Tests of the syslog work need to be added, which is tracked by #5312
