### ISSUE TITLE
Get-Help about_* bugs (conceptual help topics)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3782]
Note: This is an attempt to consolidate the related existing issues:
* #2653 
* #3503
* #3728
* #3781

The **behavior as of beta1**, verified on Windows 10, macOS 10.12, Ubuntu 16.04:

* `Get-Help about_*` (using wildcards)
  * Windows: OK
  * Unix: Broken
      * No success output, only error `get-help : Unable to find type [wmiclass].`
      * Problem starts with as few chars.  as `Get-Help ab*`, but, curiously, _doesn't_ break with `Get-Help a*`, in which case only matching _non-conceptual_ topics are output.

* `Get-Help about_Variable` (any individual topic, specified _in full, without wildcards_)  
  * Windows: Broken
     * Shows a _list_ of 2 _duplicates_ rather than the text of the help topic itself.
  * Unix: OK

* Tab completion with `about_*` topics:
   * Windows: OK
   * Unix: Broken
        * Nothing happens when you press <kbd>tab</kbd> after typing `Get-Help about_`, for instance.

**Comment by joeyaiello** [comment]
Thanks for doing this, @mklement0. Those issues are all over the place. 

I'm also seeing duplicates on Windows 6.0.0-beta.1 (e.g. about_Jobs). I think we're probably looking in Windows PowerShell $PSHome.
