### ISSUE TITLE
Platform Independent HOME

### ISSUE THREAD

**Issue by SRGOM** [PowerShell/PowerShell#3788]
It's a very low priority thing but i'm mentioning anyway.
PSVer: `powershell-6.0.0-alpha.17-x86_64.AppImage`

Platform: Arch/Win

On Windows I use $Env:USERPROFILE 
On Linux, there's $HOME which nobody has to define. Maybe define either of the variable on the other platform?

**Comment by SteveL-MSFT** [comment]
Dupe of https://github.com/PowerShell/PowerShell/issues/1262
