### ISSUE TITLE
New-ModuleManifest creates files in UTF-16

### ISSUE THREAD

**Issue by andrewducker** [PowerShell/PowerShell#3789]
Steps to reproduce
------------------
1) Run New-ModuleManifest
2) Discover that it's created in UTF-16
3) And that this means that Git will treat it as a binary, and not diff it.

Expected behavior
-----------------
New-ModuleManifest creates files in UTF8

Actual behavior
---------------
![image](https://cloud.githubusercontent.com/assets/91378/26094938/ad30b090-3a13-11e7-93f9-7c6b38f8556e.png)

**Comment by iSazonov** [comment]
@andrewducker Thanks for the report!

Related #1559

**Comment by BrucePay** [comment]
Perhaps this should be included/mentioned in the encoding RFC.

**Comment by anmenaga** [comment]
Submitted doc PR that mentions New-ModuleManifest in encoding RFC.

**Comment by joeyaiello** [comment]
Blocked on changes from @JamesWTruher

**Comment by anmenaga** [comment]
@joeyaiello this was fixed and merged previously. Jim's changes ( #4119 ) are separate and overwrite this.
