### ISSUE TITLE
Fix PSScriptAnalyzer warnings and errors

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3791]
We should be PSScriptAnalyzer clean and any new PRs should pass PSScriptAnalyzer

```powershell
PS> $e = Get-ChildItem -Recurse -Include *.ps1,*.psm1 | ? { $_.fullname -notmatch "\\bin\\" } | % { Invoke-ScriptAnalyzer -Path $_ }
PS> $e | Group-Object severity

Count Name                      Group
----- ----                      -----
 1528 Warning                   {Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Win...
   20 Error                     {Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Win...
  129 Information               {Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Win...
```

**Comment by mi-hol** [comment]
Affected files identified below are the ones to be fixed, correct?
Count Name
----- ----	
    4 Microsoft.PowerShell.Archive.psm1
    1 Microsoft.PowerShell.Utility.psm1
    4 MSFT_PackageManagement.psm1
    3 MSFT_PackageManagementSource.psm1
    1 PackageManagementDscUtilities.psm1
    9 PackageProviderFunctions.psm1
  115 PSModule.psm1
   74 PSDesiredStateConfiguration.psm1
   14 PSDiagnostics.psm1
    4 Install-PowerShellRemoting.ps1
    3 RegisterManifest.ps1

**Comment by SteveL-MSFT** [comment]
Running off latest master, I got 303 files:

$e | select scriptname -unique

**Comment by SteveL-MSFT** [comment]
@mi-hol if you want to help out, I would suggest not fixing them all at once (which would make the PR review more difficult), but perhaps each folder can be a separate PR.  Thanks!

**Comment by mi-hol** [comment]
@SteveL-MSFT  sure thats the right approach and reason why I've tried to locate the source file for 'Microsoft.PowerShell.Utility.psm1' in this repository but didn't succeed. 
What file would you suggest that I'd try first?

**Comment by SteveL-MSFT** [comment]
Perhaps start with all the psm1 files

**Comment by rjmholt** [comment]
I'll take on the warnings in Import-Module.Tests.ps1
