### ISSUE TITLE
On keyboard input, every new character adds a new line

### ISSUE THREAD

**Issue by w3rs** [PowerShell/PowerShell#3797]
Steps to reproduce
------------------

Launch `./PowerShell-6.0.0-beta.1-x86_64.AppImage`. Type anything, e.g. `exit`

Expected behavior
-----------------

```PS /home/alex> exit```

Actual behavior
---------------

```
PS /home/alex> PS /home/alex> e
               PS /home/alex> ex
               PS /home/alex> exi
               PS /home/alex> exit
```
Stdout redirection (`./PowerShell-6.0.0-beta.1-x86_64.AppImage > out`), produces file like this:
```
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_cqcHJD/usr/bin/powershell.wrapper.
PowerShell 
Copyright (C) Microsoft Corporation. All rights reserved.

PS /home/alex> eexexiexit
```

Similarly, I get this **eexexiexit** if I disable PSReadLine with `Remove-Module -Name PSReadline`.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                  
----                           -----                                                                                  
PSVersion                      6.0.0-beta                                                                             
PSEdition                      Core                                                                                   
BuildVersion                   3.0.0.0                                                                                
CLRVersion                                                                                                            
GitCommitId                    v6.0.0-beta.1                                                                          
OS                             Linux 4.9.20 #1-NixOS SMP Fri Mar 31 08:32:02 UTC 2017                                 
Platform                       Unix                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                
PSRemotingProtocolVersion      2.3                                                                                    
SerializationVersion           1.1.0.1                                                                                
WSManStackVersion              3.0                                                                                    
```
I launch AppImage file with
```
LD_LIBRARY_PATH=~/.nix-profile/lib:/run/current-system/sw/lib/:/nix/store/2ha6ykgqyqdd2dvaxj76ijnsv42zv68c-util-linux-2.29.2/lib/ ./PowerShell-6.0.0-beta.1-x86_64.AppImage
```

**Comment by probonopd** [comment]
Can you reproduce this on any other system but NixOS?

**Comment by w3rs** [comment]
@probonopd I tried AppImage on two Debian systems and also a docker version on my NixOS. All of them work fine. Only AppImage on NixOS has this problem.

**Comment by w3rs** [comment]
Also I just noticed that `Up/Down` keys don't work for browsing history. But `Ctrl-p/Ctrl-n` work.

**Comment by chuanjiao10** [comment]
I have the same problem with the results, but the environment is different, can I discuss it under this issue?

I think:
1 font and psreadline related.
2 The environment in which the problem occurred is:
2.1 in the win + powershell.exe environment, rarely appear.
2.2 in Chinese, Japenese, Korean (CJK) environment, prone to.
2.3 in the vscode + powershell terminal environment, prone to.
2.4 in the win + terminal software + ssh to linux release, prone to.


So cc @lzybkr:
Will psreadline want compatible with chinese simhei family (黑体)?

problem is:
Command line cursor position is incorrect in the terminal console.
press letters key, BackSpace key ,past to terminal console, multiple lines.



Steps to reproduce
------------------
```
$mycreds = New-Object System.Management.Automation.PSCredential ($用户名,$用户密码密文)
$mycreds = New-Object System.Management.Automation.PSCredential ($用户名,$用户密码密文)
$mycreds = New-Object System.Management.Automation.PSCredential ($用户名,$用户密码密文)
```
#"simhei" font + terminal software + paste this code = multiple lines

**Comment by au-phiware** [comment]
I also observe this behaviour in a docker container based on microsoft/powershell:centos7. It appears to be related to the width of my terminal (new lines appears after a certain length dependent on the width of the window). Also the flashing cursor doesn't align with the text.
