### ISSUE TITLE
This project supports Office 365 PS management?

### ISSUE THREAD

**Issue by danilocanel** [PowerShell/PowerShell#3802]
Steps to reproduce
------------------
>> powershell
>>Connect-MsolService

Expected behavior
-----------------

Actual behavior
---------------
PS /Users/ccanel> Connect-MsolService                                                                                          
Connect-MsolService : The term 'Connect-MsolService' is not recognized as the name of a cmdlet, function, script file, or oper
able program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-MsolService
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-MsolService:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Environment data
----------------

```powershell
> $PSVersionTable

```
Name                           Value                                                                                          
----                           -----                                                                                          
PSVersion                      6.0.0-alpha                                                                                    
PSEdition                      Core                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                        
BuildVersion                   3.0.0.0                                                                                        
GitCommitId                    v6.0.0-alpha.11                                                                                
CLRVersion                                                                                                                    
WSManStackVersion              3.0                                                                                            
PSRemotingProtocolVersion      2.3                                                                                            
SerializationVersion           1.1.0.1

**Comment by mirichmo** [comment]
@joeyaiello - Do you know the status of their cmdlets? I suspect the answer is that they have not been ported to .Net Core.

**Comment by MaximoTrinidad** [comment]
I would thing this will be possible way down the road as it was build to run on Window PowerShell and not PowerShell Core.

I would expect people will ask about SQLServer module and SharePoint.  But, not at time soon.

Just wondering, if this need to be included in the PowerShell Core RFC? 
:)

**Comment by mirichmo** [comment]
You might try finding the O365 UserVoice and leaving some feedback regarding your desire for their cmdlets on PowerShell Core. Porting their cmdlets isn't something that we can control and external feedback can help influence their decision.
