### ISSUE TITLE
Remove UTC and SQM telemetry code

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3807]
The code base inherited from Windows UTC and SQM telemetry data points that are no longer relevant for cross platform now that we've adopted AppInsights.  This code needs to be removed as it's counting against our code coverage

**Comment by SteveL-MSFT** [comment]
@JamesWTruher we should remove this when we close on new telemetry plan to see what logic in the legacy telemetry we can reuse

**Comment by JamesWTruher** [comment]
thank you
