### ISSUE TITLE
Remoting: WS-Man "Authentication failure" with Basic authentication from Mac --> Windows

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3812]
Overview
------------------

Basic Authentication to WinRM on Windows Server 2016 fails from Mac OS X PowerShell client.

Steps to reproduce
------------------

1. Spin up a Windows Server 2016 instance
2. Join Windows Server 2016 instance to Active Directory domain
3. Enable Basic Authentication for Windows Remote Management (WinRM): `Set-Item -Path wsman:\localhost\Service\Auth\Basic -Value true; Restart-Service -Name WinRM`
4. From Mac OS X, run the following command against a Windows Server 2016 system.

```powershell
Set-Item -Path wsman:\Service\Auth\Basic -Value true
```

Expected behavior
-----------------

Remoting connection is successful.

Actual behavior
---------------

Exception occurs:

```
Enter-PSSession : Connecting to remote server <redacted> failed with the following error message : Authentication Failure For more information, see the about_Remote_Troubleshooting Help topic.
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Cheers,
Trevor Sullivan

**Comment by SteveL-MSFT** [comment]
Did you also set wsman:\localhost\service\allowunencrypted to $true or are you explicitly using HTTPS?

**Comment by pcgeek86** [comment]
There's a GPO in place that requires `AllowUnencrypted` on the WinRM service. Is that a requirement for this to work? Is there an equivalent doc / guide for WinRM remoting, similar to this one, linked in the community call this morning?

https://github.com/PowerShell/PowerShell/tree/master/demos/SSHRemoting

**Comment by SteveL-MSFT** [comment]
@joeyaiello is working on the equivalent for WS-Man

**Comment by bgelens** [comment]
This will help you I think https://github.com/powershell/psl-omi-provider/#connecting-from-linux-to-windows

**Comment by pcgeek86** [comment]
This is interesting:

> Basic authentication with WinRM can only access local machine accounts so you will need to create a local account on your Windows machine that is part of the administrator group.a SPNEGO connections can use domain credentials.

How do you create a SPNEGO connection?

**Comment by SteveL-MSFT** [comment]
SPNEGO == Negotiate authn.  From Linux, it will negotiate to NTLM.  Since NTLM isn't supported on Mac, you can't use Negotiate.

https://github.com/PowerShell/psl-omi-provider#connecting-from-linux-to-windows

**Comment by pcgeek86** [comment]
@SteveL-MSFT Got it. While you're working on the updated docs for this, it might be worth adding these fields to the "master table":

* Client
* Client PS Edition
* Server / Target
* Server / Target PS Edition
* Authentication Mechanism (Basic, NTLM, etc.)
* Protocol (SSH or WS-Man)

Anything I'm missing? @joeyaiello

**Comment by pcgeek86** [comment]
Based on the current state, the original issue is pending the following two items:

* NTLM / SPNEGO support from Mac OS X client running PowerShell Core Edition
* Support for encrypted connections, to avoid enabling unencrypted connections.

**Comment by SteveL-MSFT** [comment]
@pcgeek86 as long as you use Negotiate, you should get encryption over HTTP.  In the case of Mac, it doesn't look like NTLM/SPNEGO is coming so you would have to use HTTPS with Basic

**Comment by pcgeek86** [comment]
@SteveL-MSFT Is the "encrypted connections" setting in WinRM the same thing as using HTTPS? My current understanding is that this is a distinct setting from setting up an HTTPS listener. If this is correct, is there any description of how this works?
