### ISSUE TITLE
Class-definition syntax should support calling the same class's other constructors

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3820]
Both C# and PowerShell allow calling a _base_ class constructor from a given constructor.

However, it seems that only C# currently supports calling another constructor in the _same_ class.

The ability to do so enables constructors of a given class to call each other to avoid duplication of initialization code.

Desired behavior
-----------------

```powershell
class Foo {
  [string] $bar
  [int] $n
  # Argument-less constructor for shared (dynamic) initialization code.
  Foo() { $this.bar = 'none' }
  # Already works: call the (argument-less) *base*-class constructor
  Foo([int]    $n) : base() { $this.n = $n }   
  # Wishful thinking: call the (argument-less) constructor in the *same* class.
  Foo([double] $n) : this() { $this.n = $n }
}
```
That is, given the above class, calling the `Foo([double] $n)` constructor would call the parameter-less `Foo()` constructor _in the same class_ by virtue of `: this()` following the method signature:

```powershell
# .bar is initialized to 'None' in the argument-less same-class constructor
> [Foo]::new(2.0)

bar  n
---- -
none 2
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta (v6.0.0-beta.1)
```

**Comment by iSazonov** [comment]
@mklement0 Please clarify that you means:
https://msdn.microsoft.com/en-us/powershell/wmf/5.0/class_baseconstructor
https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_classes

**Comment by mklement0** [comment]
@iSazonov: See if my update clarifies it.

**Comment by lzybkr** [comment]
PowerShell is not C# and it was not a goal to replicate all of C#'s capabilities.

For this specific area - we added the `: base()` syntax because some syntax is required to call a base class constructor.

We did not add `: this()` syntax because there is a reasonable alternative that is also somewhat more intuitive syntax wise - introduce a shared initialization method and just call it, e.g.:

```powershell
class Foo {
  [string] $bar
  [int] $n
  Foo() { $this.Init() }
  Foo([double] $n) { $this.Init(); $this.n = $n }
  hidden Init() { $this.bar = 'none' }
}
```

**Comment by mklement0** [comment]
@lzybkr: 

Good to know, thanks for the rationale; I'm closing this.

Two parting thoughts:

* Given that `: base()` is already supported, to me it is `: this()` that is more intuitive, irrespective of C# (and more concise).

* It would be great to collect such design rationales publicly somewhere - perhaps in the upcoming language spec.

**Comment by mklement0** [comment]
@lzybkr:

P.S.: I've added your rationale to [this SO answer](http://stackoverflow.com/a/44035451/45375) (which I've also updated based on your recommended solution - initially, I had more clumsily used a _static_ helper method).
