### ISSUE TITLE
Windows PowerShell will not launch from Core PowerShell when remoting into Windows over SSH

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell#3827]
Steps to reproduce
------------------
(Windows box has OpenSSH configured)
(remote to Windows box from Mac/Linux)
Enter-PSSession -Hostname windowsbox -Username foo -SSHTransport
$PSVersionTable (returns 6 beta)
cd 'C:\Windows\System32\WindowsPowerShell\v1.0'
.\powershell.exe
(PowerShell copyright banner is displayed but the session closes)
$PSVersionTable (returns 6 beta)

Expected behavior
-----------------
(Windows box has OpenSSH configured)
(local experience)
(start PowerShell Core)
$PSVersionTable (returns 6 beta)
cd 'C:\Windows\System32\WindowsPowerShell\v1.0'
.\powershell.exe
(PowerShell copyright banner is displayed)
$PSVersionTable (returns 5.1.xxxxx.xxxx)
(can run full .NET modules here)
Exit
$PSVersionTable (returns 6 beta)
(this should be the same experience remotely over SSH)

Actual behavior
---------------
See repro

Environment data
----------------
Windows Server 2016 with PS Core Beta 1
MacOS Sierra with PS Core Beta 1

**Comment by iSazonov** [comment]
Perhaps  a remote SSH doesn't load environment variables. #3545

**Comment by mirichmo** [comment]
I am leaning toward calling this a feature request rather than a bug since Windows PowerShell does not support the same behavior. You cannot start another instance of PowerShell within a remote session. @PaulHigin - Please confirm

``` powershell
PS C:\WINDOWS\system32> $pid
9588
PS C:\WINDOWS\system32> etsn .
[localhost]: PS C:\Users\mirichmo\Documents> $pid
1692
[localhost]: PS C:\Users\mirichmo\Documents> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\mirichmo\Documents>
[localhost]: PS C:\Users\mirichmo\Documents> $pid
1692
[localhost]: PS C:\Users\mirichmo\Documents>
```

**Comment by PaulHigin** [comment]
Correct.  PowerShell remoting does not support nested interactive sessions.  I am not sure what the use case would be for this.

**Comment by MaximoTrinidad** [comment]
I think the fact has always been OpenSSH only works with PowerShell Core only in order to support cross-platform interaction.  Keeping in mind, that all existing Windows PowerShell modules only work in Windows System.

**Comment by GoateePFE** [comment]
The use case is trying to use full PowerShell modules remotely from a Linux box. I want to remote over SSH from Linux to Windows and use, for example, the ActiveDirectory module which is not supported in PowerShell Core.

**Comment by AmazingWizard** [comment]
I know you are trying to use SSH to accomplish this, but if you are accessing a windows box, couldn't you use `Enter-PSSession` and then load ActiveDirectory? I think PowerShell Core supports Enter-PSSession. 

I could be mistaken though. I haven't tried this my self.

**Comment by GoateePFE** [comment]
I have not yet tried the WinRM from Linux to Windows. I'm guessing that would work. SSH remoting requires PowerShell Core which does not support full modules.

**Comment by mirichmo** [comment]
@GoateePFE Yes, that scenario is not currently supported with PSRP over OpenSSH. An alternative, hinted at by @AmazingWizard is to use PRSP over WSMan to establish a remote connection directly to the instance of Windows PowerShell that you would like to use. That is a scenario that we currently support.

**Comment by PaulHigin** [comment]
No, this is not currently allowed (nested Enter-PSSession).  But I do think this is a potentially good solution.  Something like:
```powershell
PS > Enter-PSSession -HostName targetComputer -User UserName
[paulhig-3]: PS > Enter-PSSession -Cn localhost -EnableNetworkAccess
[localhost]: [paulhig-3]: PS> $psversionTable
Name                           Value
----                           -----
PSVersion                      5.1.16204.1000
...
```
I'll look into whether this change is feasible.

**Comment by MaximoTrinidad** [comment]
Hum! You guys are correct. In the scenario of Linux remote connect to Windows then be able to load and use Windows modules to keep managing Windows environment. I would use it.
Yet, I haven't try using Winrm.

**Comment by mirichmo** [comment]
@joeyaiello and @paulcallen - I think we blogged about and demonstrated Linux support for WinRM, but I'm not finding any links. Can you guys please dig one up and include it here?

**Comment by MaximoTrinidad** [comment]
I just did a simple test connecting (via winrm) PowerShell Core (beta1) to a Windows Server PowerShell then execute Invoke-SqlCmd without any problem.  At least it works using:

enter-pssession -ComputerName WindowsServer1 -Credential domain\username;

It would be nice to see the same behavior connecting Linux to Windows without the need to executing 'Windows PowerShell.exe' at the prompt.

![poshcore2winposh_2017-05-23_13-21-07](https://cloud.githubusercontent.com/assets/19892435/26366899/be8870c4-3fba-11e7-9815-e830da62129c.jpg)

**Comment by PaulHigin** [comment]
The scenario I outlined above is feasible.  The problem is that PowerShell 5.1 currently does not allow it.  So built-in PowerShell would have to be patched to allow this on the target Windows machine, which is undesirable.

**Comment by mirichmo** [comment]
Here is the [link to setup instructions](https://github.com/PowerShell/psl-omi-provider#connecting-from-linux-to-windows) I wanted (from @paulcallen).

**Comment by SteveL-MSFT** [comment]
@GoateePFE https://github.com/PowerShell/PowerShell/pull/3900 may resolve the issue of using FullCLR Modules in PSCore6 thus removing the need to call out to Windows PowerShell

**Comment by SteveL-MSFT** [comment]
Removing off `High Priority` list as this is an enhancement.  Other mitigation:

1. with improvements to .Net Std 2.0 and GAC loading, you may not need to use Windows PowerShell
2. use ssh remoting to start Windows PowerShell instead of PSRP over SSH
3. use WSMan remoting directly to Windows PowerShell

**Comment by SteveL-MSFT** [comment]
This is also a problem starting PSCore6 from within Windows PowerShell remote session.  The use case is Windows IoT where you only get a remote Windows PowerShell session.
