### ISSUE TITLE
Add `Get-Content -Wait` capabilities to PowerShell web cmdlets

### ISSUE THREAD

**Issue by dfinke** [PowerShell/PowerShell#3829]
I've looked at some C# apps that print the logstream endpoint for a serverless Azure function.
 
I used `Invoke-WebRequest` to point at the same endpoint. It "connects", I see the progress bar and it just sits there. I can hit the Azure function endpoint and watch the byte count increase in the progress bar.

Having these cmdlets emit the results before reading the entire response stream would be useful.

**Comment by markekraus** [comment]
I think this functionality would better fit being an entirely separate cmdlet. The way irm and iwr are now they are basically after-the-fact stream processor/modifiers. They pretty much rely on a completed stream to do anything meaningful. They could probably be modified to work this way, but I feel that functionality breaks with what is expected of these cmdlets.

Is see this working well with a separate web cmdlets that can grow with more continuous streaming based features (maximum line count, maximum bytes, retrungin a stream object, etc). This kind of functionality would have its own set of parameters that would clutter the other cmdlets for functionality that doesn't really make sense in their normal context.

**Comment by doctordns** [comment]
What is the status of this request? I've not seen any community posts regarding this - I wonder if it can be closed?

**Comment by iSazonov** [comment]
I can't imagine that existing cmdlets can implement this simply. At the same time, there is a policy to first implement a new cmdlets as a community project. Sp we can close this.

**Comment by doctordns** [comment]
@dfinke  ???
