### ISSUE TITLE
Support a foreach statement with implicit iteration variable $_ for consistency with the ForEach-Object cmdlet

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3830]
<sup>Inspired by #3695.</sup>

The builtin `foreach` _alias_ for the `ForEach-Object` _cmdlet_ keeps causing confusion with the `foreach` _statement_.

Given that the cmdlet and the statement are conceptually analogous, perhaps one way to mitigate the confusion is to allow the `foreach` _statement_ to have an _implied_ iteration variable, namely `$_`, just as when using `ForEach-Object`.

Desired behavior
-----------------

```powershell
# This works currently: an *explicit* iteration variable is needed.
> foreach ($suffix in 1, 2, 3) { "A" + $suffix }
A1
A2
A3

# Wishful thinking: allow *omitting* an iteration variable to use $_ by default,
# as in a pipeline, which would be the equivalent of:
#   1, 2, 3 | ForEach-Object { "A" + $_ }
> foreach (1, 2, 3) { "A" + $_ }
A1
A2
A3
```

Currently, one is forced to choose between:

* more concise, but decidedly _slower_ pipeline syntax: `1, 2, 3 | ForEach-Object { "A" + $_ }`

* faster, but more verbose `foreach` syntax: `foreach($suffix in 1, 2, 3) { "A" + $suffix }`

The suggested `foreach` syntax evens the playing field and allows a solution that is both concise _and_ performant.

```powershell
PowerShell Core v6.0.0-beta (v6.0.0-beta.1) 
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Is the language enhancement approved or we need PowerShell-Committee conclusion?

**Comment by mklement0** [comment]
As an aside - and arguably this an argument both for and against this enhancement - note that even the current documentation doesn't know the difference between the `foreach` statement and the `ForEach-Object` cmdlet - see https://github.com/PowerShell/PowerShell-Docs/issues/1514

I still think the enhancement makes a lot of sense, but the documentation needs to be fixed.

**Comment by SteveL-MSFT** [comment]
@iSazonov my opinion is that this isn't big enough or controversial to warrant a RFC, but I'll have the committee review this

**Comment by lzybkr** [comment]
The @PowerShell/powershell-committee has reviewed this and decided against this proposal.

We have two primary concerns:

* There are important distinctions between `ForEach-Object` and the `foreach` statement and making them more similar makes it more difficult to teach these distinctions.
* The bigger concern is that `$_` will commonly refer to different objects in what looks like potentially the same scope:

```powershell
foreach (Get-Process)
{
    # The first $_ refers to a System.Diagnostics.Process
    # The second $_ refers to a System.Diagnostics.ProcessModule
    $_.Modules | % { $_.ModuleName }
}
```

**Comment by mklement0** [comment]
A post-mortem, just to indulge reveries of a better world:

> There are important distinctions between ForEach-Object and the foreach statement and making them more similar makes it more difficult to teach these distinctions.

Yes, there are, and the way to highlight these _distinctions_ is to:

* fix the documentation, as suggested.

* (I get that it's too late for that) remove the unfortunate `foreach` _alias_

By contrast, implicit use of `$_` is a _commonality_ worth implemeting.

---

> The bigger concern is that $_ will commonly refer to different objects in what looks like potentially the same scope:

The very same concern applies to `ForEach-Object` already:

```powershell
Get-Process | ForEach-Object {
    # The first $_ refers to a System.Diagnostics.Process
    # The second $_ refers to a System.Diagnostics.ProcessModule
    $_.Modules | % { $_.ModuleName }
}
```

**Comment by lzybkr** [comment]
Our hypothesis is that nested ForEach-Object is significantly less common than `ForEach-Object` inside a for statement.

We have plenty of longstanding feedback, often conflicting, but the feedback on `$_` is skewed negatively, so that plays into this decision as well.
