### ISSUE TITLE
Extend Get-Culture with a -Name parameter to allow retrieving a specific culture

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3832]
`Get-Culture` currently supports returning information about the _current_ culture.

It would be helpful if it supported a `-Name` switch to allow retrieving information about a _specified_ culture.

(This would be analogous to existing `Get-Date` behavior, which by default returns the current date and optionally supports operating on a _specified_ date via `-Date`.)

Also, as @iSazonov  suggests, _listing_ available cultures should be supported: `-ListAvailable`, supplemented by an optional `-Type` parameter that defaults to `SpecificCultures` - (see https://msdn.microsoft.com/en-us/library/system.globalization.culturetypes(v=vs.110).aspx for permissible values, though not all of them may make sense).

Desired behavior
-----------------

```powershell
# Should be the equivalent of: [cultureinfo]::GetCultureInfo('fr-FR')
> Get-Culture fr-FR      # assumes that -Name is the 1st positional param

LCID             Name             DisplayName                                                                                                                                      
----             ----             -----------                                                                                                                                      
1036             fr-FR            French (France)                                                                                                                                  

# Should be the equivalent of [cultureinfo]::GetCultures('SpecificCultures')
> Get-Culture -ListAvailable

LCID             Name             DisplayName                                                                                                                                      
----             ----             -----------                                                                                                                                      
4096             af-NA            Afrikaans (Namibië)                                                                                                                              
1078             af-ZA            Afrikaans (South Africa)                                                                                                                         
# ....
```

Environment data
----------------
```powershell
PowerShell Core v6.0.0-beta (v6.0.0-beta.1)
```

**Comment by iSazonov** [comment]
What is the benefit we get from getting the CultureInfo ?

**Comment by mklement0** [comment]
If there's value in getting the _current_ culture's `[System.Globalization.CultureInfo]` instance - which is currently the sole purpose of `Get-Culture` - then there's obviously value in getting a _different_ culture's information.

For instance, if you wanted to get a given culture's list-separator character, you could then do

```powershell
(Get-Culture it-IT).TextInfo.ListSeparator  # assuming -Name is the 1st positional param
```

instead of

```powershell
[cultureinfo]::GetCultureInfo('it-IT').TextInfo.ListSeparator
```

**Comment by iSazonov** [comment]
Then needed `-ListAvailable`

**Comment by mklement0** [comment]
@iSazonov: Good idea - initial post updated.
