### ISSUE TITLE
Sluggish cursor on linux over SSH

### ISSUE THREAD

**Issue by AndrewSav** [PowerShell/PowerShell#3835]
Steps to reproduce
------------------

Connect to Ubuntu box from Windows with PuTTY/KiTTY
Start powershell (v6.0.0-beta.1) from command line on Ubuntu (16.04) `powershell` and start typing stuff.

Expected behavior
-----------------

Cursor moves one character forward when you type a character.

Actual behavior
---------------

Cursor is all over the place (demo):

![2017-05-21_15-05-49](https://cloud.githubusercontent.com/assets/658865/26280838/105f3138-3e37-11e7-9ea7-01dc8e5cedf5.gif)

I'm wondering what's up with that. I have not found any reports about this (except for bash on windows specific) and I'm wondering why I'm seeing this and everyone else does not. What am I doing wrong? This is a clean install of both ubuntu and powershell. I've also seen the same behavior on Fedora with Centos RPM.

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Linux 4.9.15-x86_64-linode81 #1 SMP Fri Mar 17 09:47:36 EDT 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
It seems your environment is very slow if you can see rewriting the line.

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/1877
