### ISSUE TITLE
Java/Linux: The file does not have a '.PS1' extension

### ISSUE THREAD

**Issue by DarkLite1** [PowerShell/PowerShell#3837]
Steps to reproduce
------------------
See [StackOverflow](http://stackoverflow.com/questions/44087451/running-a-powershell-file-from-java-says-the-file-does-not-have-a-ps1-extensi) question.

Expected behavior
-----------------
Simply to run the file 'MyScript.ps1'.

Actual behavior
---------------
An error is thrown:
Processing -File '"/home/b/Downloads/MyScript.ps1"' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.

Environment data
----------------
```powershell
> $PSVersionTable
Name                           Value                                                                                                                  
----                           -----                                                                                                                  
PSVersion                      6.0.0-beta                                                                                                             
PSEdition                      Core                                                                                                                   
BuildVersion                   3.0.0.0                                                                                                                
CLRVersion                                                                                                                                            
GitCommitId                    v6.0.0-beta.1                                                                                                          
OS                             Linux 4.10.15-200.fc25.x86_64 #1 SMP Mon May 8 18:46:06 UTC 2017                                                       
Platform                       Unix                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                
WSManStackVersion              3.0     
```

**Comment by MaximoTrinidad** [comment]
@DarkLite1 

Hum!  Try if adding '.' in front of the forward slash to see if this fix the issue. Also, avoid using single-quotes within the double-quote as it will take it as full string and not as a file path.
(See image)

Hope this helps!
![dotsourceposh](https://cloud.githubusercontent.com/assets/19892435/26303886/40b4c8cc-3eb7-11e7-8ad5-703e9ec00ce9.png)

**Comment by DarkLite1** [comment]
Thank you Maximo. I tried your suggestion in Java like this:
`command = "powershell -ExecutionPolicy RemoteSigned -NoProfile -NonInteractive -File \"./home/b/Downloads/MyScript.ps1\"";`

However, still getting the same error:

> Standard Error:
> Processing -File '"./home/b/Downloads/MyScript.ps1"' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.
> Done

**Comment by MaximoTrinidad** [comment]
Sorry @DarkLite1!

I'm trying to setup my Java environment to get familiar to what you're doing.  It's been a long time since I did some little Java coding and it was very simple stuff.  

I'm still think is something with the string.  By any chance, have you try just to run the only the powershell calling the script at the bash console by itself (just like in my print screen image).  Just to make sure script runs.

:)

**Comment by MaximoTrinidad** [comment]
OK! This most be a bug!! 

This what's going on.

PowerShell is not working with folder. It lonely work if the script is stored in the local folder where you're executing PowerShell with the script.

Even at the console I can't even do a "powershell ./mnt/c/Scripts/TestDir.ps1" as it doesn't recognize the ".ps1" extension or more likely the path to it.  The error could happened in PowerShell console.

![javaposh3_2017-05-22_14-45-00](https://cloud.githubusercontent.com/assets/19892435/26326242/6b426c88-3f08-11e7-8ce0-d4781cfceceb.jpg)

I was able to execute the script from bash console with and without the extension:
powershell ./TestDir  or powershell ./TestDir.ps1 (as long I'm on the current folder)

![javaposh4_2017-05-22_14-45-00](https://cloud.githubusercontent.com/assets/19892435/26326259/799039a0-3f08-11e7-8443-efaf20e8a64a.jpg)

![javaposh4b_2017-05-22_14-45-00](https://cloud.githubusercontent.com/assets/19892435/26327623/197a96ea-3f0e-11e7-9137-5f0f72e2a5d5.jpg)

So, you can't run the script stored on another location.  You need to run it at the current location.

![javaposh4a_2017-05-22_14-45-00](https://cloud.githubusercontent.com/assets/19892435/26326621/f8d0c576-3f09-11e7-9b56-47e16f95c03b.jpg)

I can provide the Java Code if necessary!

:)

**Comment by ebrucucen** [comment]
@MaximoTrinidad, I think you got it right with the screenshot putting \\ [ @DarkLite1 thus // for Linux works:]
This is from my Mac [10.12.4], Java SDK 8 [1.8.0_131], PowerShell [v6.0.0-beta.1]   

` command = "powershell -ExecutionPolicy RemoteSigned -NoProfile -NonInteractive -File //Users//demokritos//work//commands.ps1";`


```
Ebrus-MacBook-Pro:java demokritos$ javac PowerShellCommand.java
Ebrus-MacBook-Pro:java demokritos$ java PowerShellCommand
Standard Output:   
Hello-Mars
Standard Error:
Done
```

**Comment by MaximoTrinidad** [comment]
Nice!  I missed one variation.  Good!
It's confirmed and is working now.  It was a little confusing.
:)

![javaposh5_2017-05-22_14-45-00](https://cloud.githubusercontent.com/assets/19892435/26335378/55f38840-3f39-11e7-93b1-7615267e1854.jpg)

**Comment by DarkLite1** [comment]
Hi guys and girls, thans for the help on this. Really appreciate it!

So, I've done some more tests based on someones's post on [StackOverflow](https://stackoverflow.com/questions/44087451/running-a-powershell-file-from-java-says-the-file-does-not-have-a-ps1-extensi/44124246#44124246). 

In Linux, at least on Fedora 25, the following is not working (but is working fine on a Mac as stated in the post above and on StackOverflow):

```
String command = "powershell -ExecutionPolicy RemoteSigned -NoProfile   
-NonInteractive -File //home//b//Downloads//MyScript.ps1";
```

This made me try the following, which works perfectly fine on Linux:

`String command = "powershell -ExecutionPolicy RemoteSigned -NoProfile -NonInteractive -File /home/b/Downloads/MyScript.ps1";`

The only problem left now is how to call a script from within Java on Linux that has spaces in it's path? This part still doesn't work. The following doesn't work for example:

String command = "powershell -ExecutionPolicy RemoteSigned -NoProfile -NonInteractive -File /home/b/Downloads/My script has spaces.ps1";

**Comment by MaximoTrinidad** [comment]
Hi everyone,

My testing includes Ubuntu 16.04.2, and Windows 10 Bash (WSL), This is a bit confusing.

I think providing the path should work similar to keeping the format "c:\folder1\Scripts\..." or "/home/username/Scripts/...".  Unless, it's mandatory to use double-slashes.

So, doing the double/slash seems the workaround but is it the proper way?

Thanks,
Max

**Comment by mklement0** [comment]
I think we can close this as as-designed now, based on the following resolution:

The problem was that the command line was passed as a _single string with embedded quoting_, which the Java library didn't recognize - it simply splits a command line by whitespace, retaining embedded quotes and ignoring argument boundaries indicated by embedded quoting.

The solution is to pass an _array_ of strings to form the command to begin with.

For details, see the [accepted answer to the linked SO question](https://stackoverflow.com/a/51227527/45375).

**Comment by DarkLite1** [comment]
Agree, issue closed now. Thx for the help guys :)
