### ISSUE TITLE
Document the WMF 4.0+ Dependency for Remoting on Server 2008r2

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#3841]
On a fully patched Server 2008r2 system, the remoting install script (Install-PowerShellRemoting.ps1) installs the plugin, but WinRM rejects it as a corrupted plugin. This prevents PoweShell Core from accepting incoming PowerShell connections.

The fix is to install WMF 4.0 or higher prior to installing the plugin. This should be documented in the installation instructions for Windows.

If you encounter this issue, follow the instructions in the Winrm error message to delete the plugin using `winrm delete ...`

**Comment by SteveL-MSFT** [comment]
Documented https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6#prerequisites
