### ISSUE TITLE
WebCmdlets: WebResponseObject.CoreClr.cs every get on Headers creates a new Dictionary

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3842]
The Headers property creates a new Dictionary which then gets populated.  Users typically do something like

```powershell
if (obj.Headers.ContainsKey("Something"))
{
    obj.Headers["Something"] ...
}
```

which now instantiates a new Dictionary twice, we should optimize this code.  consider using a `ReadOnlyDictionary`

**Comment by markekraus** [comment]
@SteveL-MSFT If #4845 is an OK idea, this could be incorporated at the same time as it has somewhat mutual goals.

**Comment by SteveL-MSFT** [comment]
@markekraus go for it!
