### ISSUE TITLE
Could it be made possible to cast from delegates to script blocks and psmethod?

### ISSUE THREAD

**Issue by poizan42** [PowerShell/PowerShell#3846]
If I do the following:

```PowerShell
    $delegate = [System.Environment].GetMethod("GetEnvironmentVariable", $([string])).CreateDelegate([System.Func[string,string]])
    [System.Management.Automation.ScriptBlock]$delegate
```

Then I get the error:
```
Cannot convert the "System.Func`2[System.String,System.String]" value of type "System.Func`2[[System.String,
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String,
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" to type
"System.Management.Automation.ScriptBlock".
At line:1 char:1
+ [System.Management.Automation.ScriptBlock]$delegate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException
```

The same happens if I attempt to cast to System.Management.Automation.PSMethod.

Of course it can be wrapped in a script block with { $delegate.InvokeDynamic($args) }, and $delegate.Invoke is a PSMethod, but it feels like unnecessary boilerplate code.

**Comment by powercode** [comment]
What are you trying to accomplish?

**Comment by poizan42** [comment]
@powercode GetEnvironmentVariable was just to show an example. Assume that I have a delegate from some other source. e.g. because a function in my script is called from some C# code.

**Comment by poizan42** [comment]
@iSazonov It wasn't meant as a question as much as a discussion about whether these casts should be added to PowerShell

**Comment by iSazonov** [comment]
@poizan42 Please correct the title and description of the Issue.

**Comment by powercode** [comment]
I think it is more the question of what the gain is. 
Seems like ```{$delegate.invoke()}``` would accomplish the same thing.
@poizan42 Do you mean we should add this as a convenience?

**Comment by poizan42** [comment]
@powercode, yes, and there is already a convenience conversion from ScriptBlock, e.g.

```PowerShell
$block = { echo "Hello, World!" }
([Func[String]]$block).Invoke()
```

outputs "Hello, World!" as expected. And I can see that you are working on adding conversions from PSMethod to delegates (#2864), so it would only be natural if they could all be casted to each other.

**Comment by powercode** [comment]
@lzybkr Thoughts?

**Comment by lzybkr** [comment]
Interesting idea. If this was possible, I wonder if I would have used a `scriptblock` instead of a delegate in some places, e.g.:

```
Set-PSReadlineOption ... [-AddToHistoryHandler <Func[string,bool]>] [-CommandValidationHandler <Action[CommandAst]>] ...
```

When I added these features, I considered `scriptblock`, but used a delegate partly because it was convenient in C#, but also knowing that:
1. Converting a script block to a delegate worked
2. The arguments and expected return type are clearly documented in the syntax

I could see adding the proposed conversion from delegate to script block, but I could also see adding support for explicit delegates in some cmdlets, e.g. `Where-Object` could be much faster if you used a delegate instead of converting the delegate to a script block.

**Comment by SeeminglyScience** [comment]
The Engine WG discussed this, we do not think this meets the bar for impact and we're marking this issue as declined.
