### ISSUE TITLE
Add-Type: add CSharpVersion7

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#3853]
Should we add new CSharpVersion7 option in [Language](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs#L43) enum in Add-Type cmdlet?

And why we use "#if CORECLR" in the enum?

**Comment by lzybkr** [comment]
If it works, then yeah.

Windows PowerShell relies on CodeDom instead of Roslyn for Add-Type, so there are differences, mostly CodeDom isn't updated.

**Comment by iSazonov** [comment]
It seems we already have microsoft.codeanalysis.csharp-2.0.0 and microsoft.codeanalysis.csharp-2.0.0 (last version of the packages is 2.2.0 /cc @daxian-dbw -Should we update? ) and the next works well:
```powershell
$Source = @"
using System;
public class BasicTest
{
public static void PrintStars(string s) 
{ 
    if (int.TryParse(s, out var i)) { Console.WriteLine(new string('*', i)); } 
    else { Console.WriteLine("Cloudy - no stars tonight!"); } 
} 
}
"@
Add-Type -TypeDefinition $Source

[BasicTest]::PrintStars("3")
```

**Comment by daxian-dbw** [comment]
The example above already works in beta.1, so I guess we should add `CSharpVersion7` to the enum.
As for `microsoft.codeanalysis.csharp`, it will be updated to 2.2.0 with the next refreshment, see PR https://github.com/PowerShell/PowerShell/pull/3887

**Comment by iSazonov** [comment]
Thanks! Clear!
