### ISSUE TITLE
NTFS: Remove-Item cannot delete Directories with long names which New-Item can create

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShell#3859]
Good evening

of course, anno 2017 it's annoying to still have to fight with 260 character limits and that powershell is not using the unicode File API. (Win10 LongPathsEnabled is set to 1). Anyway.

Remove-Item cannot delete a directory which was created by Net-Item, it reports that the path is "too long".

Steps to reproduce
------------------
```powershell
PS C:\temp> # Create a Directory
PS C:\temp> $dirname = 'c:\Temp\123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345'

PS C:\temp> New-Item -ItemType Directory -Force -Path $dirname
    Directory: C:\Temp
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25.05.2017     00:52                123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345

PS C:\temp> # Delete Directory
PS C:\temp> Remove-Item -Force -Recurse -Path $dirname
Remove-Item : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
At line:1 char:1
+ Remove-Item -Force -Recurse -Path $dirname
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Temp\1234567...123456789012345:String) [Remove-Item], PathTooLongException
    + FullyQualifiedErrorId : RemoveItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

Expected behavior
-----------------
We expect, that PowerShell suports some 1000s characters.
But at least, that Remove-Item can delete Items which were created by New-Item.

Actual behavior
---------------
Remove-Item can not delete Items with long path names which were created by New-Item.

Environment data
----------------

```powershell
> $PSVersionTable
PS C:\temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by schittli** [comment]
To the LongPathsEnabled note: It's strange, I have re-tested it and PowerShell is handling it the right way; if LongPathsEnabled is set to 1, then PowerShell supports long paths.

But if LongPathsEnabled is not enabled, then tehre is a bug that Remove-Item cannot remove File-System items which were created by New-Item, if the max Path lengt is used. (See original post 'steps to reproduce'

**Comment by jeffbi** [comment]
On `6.0.0-beta` I was seeing a different error:
```PowerShell
PS> Remove-Item -Force -Recurse -Path $dirname
Remove-Item : Cannot find path 'C:\Temp\123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678
9012345678901234567890123456789012345678901234567890123456789012345678901234567
8901234567890123456789012345678901234567890123456789012345' because it does
not exist.
At line:1 char:1
+ Remove-Item -Force -Recurse -Path $dirname
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Temp\1234567...1234567890123
   45:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.Remov
   eItemCommand
```

I believe this is now fixed by #3960. Neither error is emitted and the `Remove-Item` succeeds.

**Comment by Hillery21** [comment]
Hi I encountered the same problem . But I try using long path tool and it worked. Try using it too. :)  let me know your experience about it. Some people says it don't work but it works for me. :)

**Comment by RogerFarrow1** [comment]
Use Long Path Tool, Long Path Tool can simplify and probably end your problems in unlocking, managing and renaming files that appear to have a long filename.

**Comment by JohnClayton2** [comment]
I suggest you try Long path tool is the very good program for easily delete, copy & rename long path files, error, unlock solution.
Try it and solve your problem.
I used long path tool and I solve my error, unlock problem solution.

**Comment by schittli** [comment]
Thank you very much, @RogerFarrow1 and @JohnClayton2 for your workarounds!

It's not a problem to find 3rd party tools which can handle long path / file names,
but after many, many years it's very annoying that Microsoft's standard scripting platform:
1. is still not able to do this kind of very basic job
2. has still not fixed  the issue while the OS API offers the solution and just could be used

**Comment by vexx32** [comment]
@schittli I note that your test case is from Windows PowerShell; issues for that are not handled by this repo itself, and as @iSazonov notes, it seems this isn't an issue in the current version of PowerShell Core.

Please check with the most recent version of PS Core. :)

**Comment by SteveL-MSFT** [comment]
PSCore6 doesn't have an issue because .NET Core defaults to supporting LFN.  .NET Framework is opt-in because it's a breaking change.  See https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/ on how to enable for Windows PowerShell

**Comment by KevinNelson0700** [comment]
You should try LongPathTool

**Comment by CalebRivers97** [comment]
LongPathTool provides a way to fix long path problems like this.
