### ISSUE TITLE
Get-FileHash does not support SHA512/256

### ISSUE THREAD

**Issue by dilijev** [PowerShell/PowerShell#3860]
Steps to reproduce
------------------
Get-FileHash -Algorithm sha512 -Path file.txt # Supported
Get-FileHash -Algorithm sha256 -Path file.txt # Supported
Get-FileHash -Algorithm sha512256 -Path file.txt # (SHA512/256 aka truncated SHA512) Not Supported

Expected behavior
-----------------
SHA512/256 should be supported.
(Reference Unix `shasum -a 512256`)

Actual behavior
---------------
SHA512/256 is not supported.

Environment data
----------------

```
Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
We are following CoreFX - CoreFX don't support  sha512256. You can open Issue in CoreFX Repo.
