### ISSUE TITLE
Enable/Disable-PSRemoting for Linux

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3864]
This cmdlet would enable WSMan-based remoting on Linux/macOS. Probably something like:

1. Download/install OMI
2. Download/install the [OMI provider for WSMan](https://github.com/PowerShell/Psl-omi-provider)

That miiight actually be all it needs to do...

**Comment by mirichmo** [comment]
All the *sessionconfiguration cmdlets are needed for endpoint management as well.

**Comment by mirichmo** [comment]
These should be removed from #2122 when implemented

**Comment by digz6666** [comment]
@mirichmo According to this comment https://github.com/PowerShell/PowerShell/issues/2122#issuecomment-330692259, this is implemted right?

**Comment by mirichmo** [comment]
[Enable/Disable-PSRemoting](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs#L4796) were enabled for Windows. This issue is still open.

**Comment by digz6666** [comment]
@joeyaiello Would you mind sharing some example how to use OMI and OMI provider?
I've installed them but couldn't figure out that to use on LD_LIBRARY_PATH before starting powershell.
