### ISSUE TITLE
Export-Csv -InputObject and ConvertTo-Csv -InputObject export/convert the collection object itself rather than its elements

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3865]
Note that providing input via the _pipeline_ is not affected.

Affects all platforms and Windows PowerShell v5.1

Steps to reproduce
------------------

```powershell
$coll = [pscustomobject] @{ foo = 1; bar = 2 }, [pscustomobject] @{ foo = 3; bar = 4 }
ConvertTo-Csv -InputObject $coll
'---'
Export-Csv -InputObject $coll t.csv; Get-Content t.csv
```
Expected behavior
-----------------

```powershell
#TYPE System.Management.Automation.PSCustomObject
"foo","bar"
"1","2"
"3","4"
---
#TYPE System.Management.Automation.PSCustomObject
"foo","bar"
"1","2"
"3","4"
```

Actual behavior
---------------

```powershell
#TYPE System.Object[]
"Length","LongLength","Rank","SyncRoot","IsReadOnly","IsFixedSize","IsSynchronized","Count"
"2","2","1","System.Object[]","False","True","False","2"
---
#TYPE System.Object[]
"Length","LongLength","Rank","SyncRoot","IsReadOnly","IsFixedSize","IsSynchronized","Count"
"2","2","1","System.Object[]","False","True","False","2"
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta (v6.0.0-beta.1) on macOS 10.12.5
PowerShell Core v6.0.0-beta (v6.0.0-beta.1) on Ubuntu 16.04.1 LTS
PowerShell Core v6.0.0-beta (v6.0.0-beta.1) on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
Windows PowerShell v5.1.14393.1198 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
```

**Comment by BrucePay** [comment]
This is how ValueFromPipeline works by design. InputObject is a single object to be processed. When used in a pipeline, InputObject is bound to each element in the pipeline and processed one at a time. If InputObject was processed as a collection, then each item from the pipeline would also be processed as a collection.

**Comment by mklement0** [comment]
Thanks for the clarification, @BrucePay.

My misconception was that only _select_ cmdlets such as `Get-Member` made this distinction, because of their specific purpose.

I know understand that _all_ cmdlets are affected, which means we have a bigger usability and/or documentation problem at our hands - I'll address that in a new issue.
