### ISSUE TITLE
Invoke-Command error message on localhost loopback

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#3874]
Steps to reproduce
------------------
Invoke-Command -ComputerName localhost -ScriptBlock { dir }

Expected behavior
-----------------
Directory contents are presented.

Actual behavior
---------------
```
PS C:\Program Files\PowerShell\6.0.0-beta.1> Invoke-Command -ComputerName localhost -ScriptBlock { dir }
[localhost] Connecting to remote server localhost failed with the following error message : Access is denied. For more
information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionStateBroken
```

If using the loopback adapter to localhost is prohibited unless elevated, the error message should include that information. It clearly knows the problem. Not sure of the implications on Linux.

Environment data
----------------

```powershell
> $PSVersionTable
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Liturgist** [comment]
This appears to be a security restriction by design on Windows.

**Comment by a-kanaan** [comment]
I am getting same error
but if remove ComputerName then, it will work, but I think it's not a loopback work

**Comment by iSazonov** [comment]
`ComputerName ` is implemented as remoting that requires elevated rights.

**Comment by Liturgist** [comment]
Does not work using "Run as Administrator." What elevated rights are required?

**Comment by iSazonov** [comment]
Did you set remoting up?

**Comment by FcoJavier0099** [comment]
Well, you need to enlist the localhost (with its hostname) to use remoting.
There are the steps that I follow:
(1) Start a new powershell window with administrator privilegies (Run as Administrator)
(2) Retrive your localhost name with the command: hostname, in my example its name is "PROCDB01"
(3) Enlist this hostname in the list of trusted servers with a comman like this:
# procdb01 is the localhost
Set-Item WSMan:\localhost\Client\TrustedHosts -Value "procdb01,procdb02,procdb03,procdb04,procdb05" 
(4) Activate Remoting with these commands:
Winrm qc
Enable-PSRemoting
(5) Test it
Invoke-Command -ComputerName procdb01 -ScriptBlock {hostname}
Invoke-Command -ComputerName localhost -ScriptBlock {hostname}

Note: I'am using this version:
```PowerShell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
