### ISSUE TITLE
Encoding should be utf-8 by default on Unix

### ISSUE THREAD

**Issue by SRGOM** [PowerShell/PowerShell#3875]
Or else you'll find people stumped. Most don't understand encoding but assume utf-8 is being used.

**Comment by iSazonov** [comment]
Welcome to main discussion https://github.com/PowerShell/PowerShell-RFC/issues/71!

Also you can find multiple related Issues and PRs in the PowerShell Core Repo.

**Comment by SRGOM** [comment]
For what it's worth, I googled powershell out-file default encoding before creating this...

**Comment by iSazonov** [comment]
It is better to use internal GitHub search.
