### ISSUE TITLE
powershell deb for ubuntu require libicu52 but is replaced by 55

### ISSUE THREAD

**Issue by robertlabrie** [PowerShell/PowerShell#3876]
Followed the instructions to install on ubuntu (using the Linux subsystem for Windows), the deb has a depend on libicu52 but ubuntu has replaced it with libicu55.

Details below.

```
rob@BADGER:~$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

rob@BADGER:~$ uname -a
Linux BADGER 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
rob@BADGER:~$

rob@BADGER:~$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libicu52 but it is not installable
E: Unable to correct problems, you have held broken packages.
rob@BADGER:~$ cat /etc/issue

rob@BADGER:~$ sudo apt-cache search libicu
icu-devtools - Development utilities for International Components for Unicode
libicu-dev - Development files for International Components for Unicode
libicu55 - International Components for Unicode
libicu55-dbg - International Components for Unicode
libicu4j-4.4-java - Library for Unicode support and internationalization
libicu4j-49-java - Library for Unicode support and internationalization
libicu4j-java - Library for Unicode support and internationalization

rob@BADGER:~$ cat /etc/apt/sources.list.d/microsoft.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
rob@BADGER:~$

**Comment by joeyaiello** [comment]
`/etc/apt/sources.list.d/microsoft.list` should be `deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod trusty main` because you're on Ubuntu 16.04. 

If that fixes you, please close this issue. :)

**Comment by robertlabrie** [comment]
Yep, 100% my fault. This worked:
`deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main`

PS: As a Windows and Linux admin, running Powershell for Linux in Ubuntu userland as legit Windows 10 processes is a little surreal.

Cheers!
Rob

**Comment by asears** [comment]
The installation instructions may need to be verified, also encountered this issue on 16.04.

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6

**Comment by SathishRanjan** [comment]
Incase some is struggling for ubuntu 18.04
add this line
`deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main` in `/etc/apt/sources.list.d/microsoft.list` create the same if not exists

**Comment by Superset1986** [comment]
> Incase some is struggling for ubuntu 18.04
> add this line
> `deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main` in `/etc/apt/sources.list.d/microsoft.list` create the same if not exists

Thank you for sharing this.

**Comment by ukreddy-erwin** [comment]
Any powershell release for 14.04 of ubuntu release?
