### ISSUE TITLE
Tests should explicitly pass -NoProfile when launching powershell.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#3881]
Steps to reproduce
------------------
Update the profile script to implicitly or explicitly write to the output stream.
Run the test\powershell\Modules\Microsoft.PowerShell.Core\Out-Default.Tests.ps1 tests.

Expected behavior
-----------------
All tests pass 

Actual behavior
---------------
All tests fail.

The pattern in the tests assumes running powershell -c 'somescript' will only produce output from the script.  The output from the profile is unexpected and causes the tests to fail.

For these types of tests; -Profile should also be specified.

```
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1-21-g73dd94197b5f4fb7a4d2ece325199bfd5caa64b1-dirty
OS                             Microsoft Windows 10.0.16209
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TravisEz13** [comment]
fixed in https://github.com/PowerShell/PowerShell/pull/4132
