### ISSUE TITLE
Set-Content test failing due to filesystem not able to access local share

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3883]
It seems with some recent updates to Windows, the following no longer works:

```powershell
net share testshare=c:\test /grant:everyone,FULL
net view \\${env:computername}
dir \\${env:computername|\testshare
```

Expected:
dir to succeed

Actual:
dir returns `The network path was not found`

We need to find another way to get this test to work.

**Comment by kyanha** [comment]
This seems to be working for me locally. Was there a configuration change to the CI servers at that time?
