### ISSUE TITLE
PSReadline should not bind to keys that are not usable

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3890]
https://github.com/PowerShell/PowerShell/pull/3815#discussion_r119167392

On Nano, two apis are not available which prevents usage, for example, of ctrl+] as a valid key chord to bind to a PSReadline handler.  PSReadline, by default, binds this key combination to go to matching brace.  When connected directly to a Nano container (not via PSRP), it will show:

```
Ctrl+Oem6             GotoBrace               Go to matching brace
```

which is not useful to the end user.  It seems the right thing to do may be to not bind this (as well as two other chords dependent on `]`) by default if those APIs are not avaialble.

**Comment by lzybkr** [comment]
Are you sure the binding doesn't work?

From my understanding, this is a simple UI problem in the output of `Get-PSReadlineBoundParameters` - the key binding should still work.

**Comment by SteveL-MSFT** [comment]
When I hit Ctrl+] on Nano, it just shows ^] on the screen

**Comment by lzybkr** [comment]
Interesting - that seems like a distinct problem from the proposed change in #3815, though it's possible that .Net is using that api as well, and has a different code path when it's not present.

I'm curious what you get from the following when you type Ctrl+]:
```
#762 PS> $x = [Console]::ReadKey($true)
#763 PS> $x

KeyChar  Key Modifiers
-------  --- ---------
       Oem6   Control


#764 PS> [int]$x.KeyChar
29

```

**Comment by SteveL-MSFT** [comment]
Current plan is for future NanoServer to support the missing APIs, so no work to be done here.

TFS:12445647
