### ISSUE TITLE
New-Partition cmdlet 4th partition cannot be specified as primary

### ISSUE THREAD

**Issue by imakiro** [PowerShell/PowerShell#3892]
Request
-----------------

The Powershell New-Partition cmdlet is creating an extended type partition when called when there are already 3 primary partitions on an MBR disk.

There is no option to create this 4th partition as Primary, with no parameter capable of specifying this information. 

An old [Stackoverflow post](https://stackoverflow.com/questions/26282835/powershell-new-partition-need-4th-partition-to-be-primary-not-extended) references such a need as well as this request

Environment data
----------------

PS C:\> $PSVersionTable

Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.14393.953                                   
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.14393.953                                  
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
@imakiro The cmdlet is not in the Repo. Please report the Issue to https://windowsserver.uservoice.com/forums/301869-powershell
