### ISSUE TITLE
Export-CliXml shouldn't require writing to a file

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#3898]
The `Export-CliXml` command should offer a parameter set that emits a string, instead of writing the result to a file. Right now, it only supports outputting CLIXML to a file via the `-Path` or `-LiteralPath` parameters.

Cheers,
[Trevor Sullivan](https://trevorsullivan.net)

**Comment by mklement0** [comment]
Given how this distinction is handled in existing cmdlets (e.g., `Export-Csv` / `ConvertTo-Csv`), that would probably call for a new cmdlet named `ConvertTo-CliXml`, plus a matching `ConvertFrom-CliXml`.

**Comment by RichardSiddaway** [comment]
Struggling to see the use case for Clixml representation of a an object just in memory. The CliXml cmdlets, as I understand them, are about persisting objects

**Comment by pcgeek86** [comment]
There are many different places you might want to persist objects. The filesystem is just one place.

**Comment by pldmgg** [comment]
Just came across a decent use case for this...

Environment variables currently on take strings, so storing a complex object as an environment variable is not really possible. But if Export-Clixml could export a string to an environment variable, then we could relatively easily use Import-Clixml to re-hydrate the object.

**Comment by markekraus** [comment]
If this followed the convention of CSV, it would actually be better to have a `ConvertTo-Clixml` cmdlet as well as a `ConvertFrom-Clixml` One reason I could think of this as useful is to pass the persisting object to things other than files, such as network streams or as body data in HTTP without needing to write to a file first.

**Comment by pcgeek86** [comment]
Building on top of what @markekraus mentioned, another use case would be sending the CLIXML off to a message queue for processing by a different consumer application. I should not have to write the CLIXML to disk, and then read it again, to accomplish this.

**Comment by charlieschmidt** [comment]
Progress on this: https://github.com/charlieschmidt/PowerShell/commit/8f79094dff0959850c1dd58fe5d9c518b581dca5
I'll get the tests & docs added this weekend and do a proper PR

**Comment by Nillth** [comment]
As a simple workaround how about this...

`$SerializedString = [System.Management.Automation.PSSerializer]::Serialize($Object)
$BackToObject = [System.Management.Automation.PSSerializer]::Deserialize($SerializedString)`

**Comment by mklement0** [comment]
It's a _viable_ workaround, but I wouldn't call it _simple_, because these behind-the-scenes types are neither widely known nor easy to remember.

As an aside: `Serialize()` defaults to depth `1`, whereas `Export-CliXml` defaults to depth `2`.

**Comment by Shriram0908** [comment]
I like to work on this issue. I hope that the cmdlets are still needed.

**Comment by vexx32** [comment]
I see there was an old PR that never got merged and is now closed... but yeah we can still use this. Go for it! 🙂

**Comment by foxx** [comment]
First of all, thanks to everyone for getting this fixed.

Are there any indications on which release this might land in?

It's a drop in the ocean of the 3.2k open issues, but would be nice to get this issue closed out :)

**Comment by doctordns** [comment]
So far as I can tell, this PR has _not_ been merged. I can't see any trace of it in either  7.4 preview  3 or a recent daily build. 

Are there folks that want to take this on and complete the PR? If not, we should close this.

**Comment by ArmaanMcleod** [comment]
> So far as I can tell, this PR has _not_ been merged. I can't see any trace of it in either 7.4 preview 3 or a recent daily build.
> 
> Are there folks that want to take this on and complete the PR? If not, we should close this.

@doctordns I've created a new PR which should address this. Will wait for feedback and hopefully get this one merged since I needed this recently and would be great to have these cmdlets in 7.4.
