### ISSUE TITLE
Invoke-RestMethod -MaxRelLink should be -MaximumRelLink

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell#3899]
This is a new cmdlet shipping with `6.0.0-beta.2`. The current parameter name is `-MaxRelLink`, but it should be spelled out as `-MaximumRelLink`.

There is other precedent for using `Maximum` instead of `Max`:

```powershell
gcm -ParameterName max* -syntax | sls 'max'
```

`rel` should stay "abbreviated" because the term is actually a "rel link" (per [this IETF spec](https://tools.ietf.org/html/rfc5988#section-5)). 

/cc @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
@joeyaiello it's currently `-MaximumFollowRelLink` https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs#L57

**Comment by joeyaiello** [comment]
Was just going off of the changelog line item. Thanks!
