### ISSUE TITLE
Not able to pass arguments in invoke-expression

### ISSUE THREAD

**Issue by ip28** [PowerShell/PowerShell#3905]
We are using remote PowerShell deployment via VSTS and calling the deployment script.

When I am running this script from a VSTS agent (agent is running on Windows 2008 R2) and deploying on a machine (target) with Windows 2012, the script is able to pass the parameters. But when I am trying to deploy it on a target machine with Windows 2008 none of the arguments are passed.

Edit, for better reference, pasting the complete code of the function:

function ExecuteDSCScript([string]$file, [string]$machine, [object]$params) {
    # Sample value for $file is MyDeploymentFolder\MyDeploymentScript.ps1
    $arguments = ""

    foreach ($param in $params) {
        $arguments = $arguments + " -" + $param.name + " '" + $param.value + "'" #Param is a key value pair
    }

    Write-Verbose $arguments.ToString() -Verbose

    $command = $file + $arguments + " -Ensure " + $Ensure + " -DeployServerName " + $machine #Forming PS command for remote execution

    # writing command in log with our password
    $paramslogging = $params

    foreach ($param in $paramslogging) {
        if ($param.Name.ToLower() -eq "password") {
            #masking the password so that it doesnt appear on console logs
            $param.Value= "************"
        }
    }
    $argumentslogging = ""

    foreach ($param in $paramslogging) {
        $argumentslogging = $argumentslogging + " -" + $param.Name + " '" + $param.Value + "'"
    }

    $commandlogging = $file + $argumentslogging + " -Ensure " + $Ensure + " -DeployServerName " + $machine

    Write-Verbose $commandlogging -Verbose  # I am able to get the complete list of parameters here (i.e. value of $argumentslogging)

    $result = Invoke-Expression -Command $command
}

Update:-
One more difference below are the .Net versions of the machines:-
Agent - .Net 4.6
Target1 - .Net 4.6 (Where the script works)
Target2 - .Net 4.5.2 (Where the script doesn't work)

**Comment by TravisEz13** [comment]
marked as a question as the issue template is not complete.  This seems to be targetting Windows PowerShell and the guidance is those issues should be reported to user voice.

**Comment by MaximoTrinidad** [comment]
@ip28 

This issue need to be properly addressed in the **Windows PowerShell**  _Windows Server UserVoice Forum_ (https://windowsserver.uservoice.com/forums/301869-powershell) as stated in PowerShell Open Source landing page: https://github.com/PowerShell/PowerShell#windows-powershell-vs-powershell-core

**Windows PowerShell** issues are not been taken here in Github!

Please provide this information in UserVoice.
Thanks
