### ISSUE TITLE
DSC deployment got reverted even when LCM configuration is set to ApplyandMonitor

### ISSUE THREAD

**Issue by ip28** [PowerShell/PowerShell#3906]
Hi All, 
Few days ago, we have done a deployment using DSC, the server was 2008 R2 version and the LCM configuration was "ApplyAndMonitor", we had a typo in web.config and corrected it after our tests, which was rolled back by LCM after 15mins. Can you please help me to find out how we can prevent this in future?

**Comment by ArieHein** [comment]
Can you share via gist your configuration script (minus real life servers/paths/passwords etc) and the LCM script as well ?

**Comment by ip28** [comment]
@ArieHein , Below is the complete script which got executed. It was a remote script execution by Invoke-Expression command, the machine from which it was running had Powershell 5.0 Windows Server 2008 R2, the target machine also had Windows Server 2008 R2.


`param
(
$DeployServerName,
$Ensure,
$AppPoolName,
$WebsiteName,
$WebApplicationName,
$WebAppPhysicalPath,
$BackupFolder,
$WebsitePhysicalPath,
$ManagedPipelineMode,
$ManagedRuntimeVersion,
$AppPoolIdentitytype,
$UserName,
$Password,
$Protocol,
$Port,
$IP,
$HostName,
$ServiceEndpoint,
$ClientEndpoint,
$AuthRoleAllowedUsers,
$ConnectionString1,
$ConnectionString2,
$ConnectionString3,
$AppsettingsKey
)
$myFQDN=(Get-WmiObject win32_computersystem).DNSHostName+"."+(Get-WmiObject win32_computersystem).Domain
$SourcePath="\\$myFQDN\BuildShare\MyComponent\MyDrop"


$ErrorActionPreference = "Stop"
configuration MyComponentWebsite
{
    
    # Import the module that defines custom resources 
    Import-DscResource -ModuleName @{ModuleName='xWebAdministration';ModuleVersion='1.3.2'}
    Import-DscResource -ModuleName @{ModuleName='WebDirProperties';ModuleVersion='1.3.2'}
    Import-DscResource -ModuleName @{ModuleName='xWinEventLog';ModuleVersion='0.0.0.1'} 
    Import-DscResource -ModuleName @{ModuleName='Custom_cXmlEdit';ModuleVersion='1.0'}
    Import-DscResource -ModuleName @{ModuleName='cEsitCustomDscResources';ModuleVersion='0.0'}
    Import-DscResource -ModuleName @{ModuleName='WebsiteBindings';ModuleVersion='1.3.2'} 


    Node $DeployServerName
    {                  
                   
            if($Ensure -ieq "present")
            {
                Registry RegKey_MyComponent
                {
                    Ensure = "$Ensure"  
                    Key = "HKLM:SYSTEM\CurrentControlSet\Services\Eventlog\DS\MyComponent"
                    ValueName = "EventMessageFile"
                    ValueData = "%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll"
                    ValueType = "ExpandString"
                 }
                Script CreateBackup_RemoveWebAppPhyPath
                {
                    GetScript = {
                                   $result=@{
                                            WebAppPhysicalPath=$WebAppPhysicalPath
                                            BackupFolder="$BackupFolder"
                                       }
                                   return $result
                                }
                    TestScript = {  
                                    $result=$true
                                    if(Test-Path -Path "$using:WebAppPhysicalPath")
                                    {
                                        $result=$false
                                    }
                                    return $result
                                 }
                    SetScript = {
                                    Write-Verbose "Copying existing web app files to Backup folder - START" -verbose
                                    Robocopy "$using:WebAppPhysicalPath" "$using:BackupFolder" /E
                                    Write-Verbose "Copying existing web app files to Backup folder - END" -verbose                                    
                                }
                 }

                File Present_Copy_SourceToWebAppPhysicalPath
                {
                    Type = "Directory" 
                    Ensure = "$Ensure"
                    Recurse = $true
                    SourcePath = "$SourcePath"
                    DestinationPath = "$WebAppPhysicalPath"
                    Force = $true
                    MatchSource = $true
                    Checksum = "CreatedDate"
                }

                Custom_cXmlEdit Present_ConnectionString1
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='/configuration/connectionStrings/add[@name="ConnectionString1"]/@connectionString'
                    Value="$ConnectionString1"
                    Ensure="$Ensure"
                }

                Custom_cXmlEdit Present_ServiceEndpoint
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='/configuration/system.serviceModel/services/service/endpoint[@contract="MyComponent.Interfaces.IService"]/@address'
                    Value="$ServiceEndpoint"
                    Ensure="$Ensure"
                }

                Custom_cXmlEdit Present_ClientEndpoint
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='/configuration/system.serviceModel/client/endpoint[@contract="Client.IClient"]/@address'
                    Value="$ClientEndpoint"
                    Ensure="$Ensure"
                }

                Custom_cXmlEdit Present_AuthRoleAllowedUsers
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='configuration/system.web/authorization/allow/@roles'
                    Value="$AuthRoleAllowedUsers"
                    Ensure="$Ensure"
                }

                Custom_cXmlEdit Present_ConnectionString2
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='/configuration/connectionStrings/add[@name="ConnectionString2"]/@connectionString'
                    Value="$ConnectionString2"
                    Ensure="$Ensure"
                }

                Custom_cXmlEdit Present_ConnectionString3
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='/configuration/connectionStrings/add[@name="ConnectionString3"]/@connectionString'
                    Value="$ConnectionString3"
                    Ensure="$Ensure"
                }
                
                Custom_cXmlEdit Present_AppsettingsKey
                {
                    FilePath = "$WebAppPhysicalPath\web.config"
                    XPathExpression='/configuration/appSettings/add[@key="AppsettingsKey"]/@value'
                    Value="$AppsettingsKey"
                    Ensure="$Ensure"
                }                
                
            }
            elseif($Ensure -ieq "Absent")
            {
                Script Absent_Remove_WebAppPhysicalPath_UnInstall
                {
                GetScript = {
                        $result = @{
                                WebAppPhysicalPath = "$WebAppPhysicalPath"
                                BackupFolder="$BackupFolder"
                                WebsiteName="$WebsiteName"
                                WebApplicationName="$WebApplicationName"
                                }
                                return $result
                            }
                TestScript = {
                                return $false
                             }
                SetScript = {
                                if(Test-Path -Path "$using:BackupFolder")
                                {
                                    Remove-Item -Path $using:WebAppPhysicalPath -Recurse -Force
                                    Robocopy "$using:BackupFolder" "$using:WebAppPhysicalPath" /E
                                }
                                else
                                {
                                    Remove-WebApplication -Site $using:WebsiteName -Name $using:WebApplicationName -Verbose
                                    Remove-Item -Path $using:WebAppPhysicalPath -Recurse -Force
                                }
                            }
                }
            }           
            if ($Ensure -ieq "Present")
            {                          
                xWebAppPool NewWebAppPool 
                { 
                    Name   = $AppPoolName
                    Ensure = "$Ensure"
                    State  = "Started"
                }
                Script CheckWebsitePath
                {
                    GetScript = {
                                    $result=@{WebsitePhysicalPath=$WebsitePhysicalPath}
                                    return $result
                                }
                    TestScript = {
                                    $result=$true
                                    if(!(Test-Path -Path "$using:WebsitePhysicalPath"))
                                    {
                                        $result=$false
                                    }
                                    return $result
                                }
                    SetScript = {
                                    New-Item -Path $using:WebsitePhysicalPath -ItemType Directory -Force 
                                }
                    DependsOn = @("[xWebAppPool]NewWebAppPool")
                }
                xWebsite MyComponentWebsite 
                { 
                    Ensure          = "$Ensure"
                    Name            = $WebsiteName 
                    State           = "Started" 
                    PhysicalPath    = "$WebsitePhysicalPath"
                    ApplicationPool = $AppPoolName
                    BindingInfo     = MSFT_xWebBindingInformation 
                                        { 
                                            Protocol              = $Protocol
                                            Port                  = $Port
                                            IPAddress             = $IP
                                            HostName              = $HostName
                                        } 
                    DependsOn       = @("[Script]CheckWebsitePath") 
                }

                if($AppPoolIdentitytype -ieq "Custom")
                {
                    WebsiteBindings MyComponentBindings_Custom
                    {
                        WebsiteName = "$WebsiteName"
                        APPPOOl = "$AppPoolName"
                        ManagedPipelineMode = "$ManagedPipelineMode"
                        ManagedRuntimeVersion = "$ManagedRuntimeVersion"
                        UserName = "$UserName"
                        Password = "$Password"
                        DependsOn = @("[xWebsite]MyComponentWebsite")
                    }
                }
                else
                {                    
                    Script ApplicationPoolIdentity_Builtin
                    {
                        GetScript = {
                                        $result = @{AppPoolName = $AppPoolName
                                               AppPoolIdentitytype = $AppPoolIdentitytype
                                               ManagedPipelineMode = $ManagedPipelineMode
                                               ManagedRuntimeVersion = $ManagedRuntimeVersion
                                              }
                                        return $result
                                    }
                        TestScript = {
                                        return $false
                                     }
                        SetScript = {
                                        Import-Module WebAdministration
                                        Set-ItemProperty IIS:\AppPools\$using:AppPoolName -name processModel.identityType -Value "$using:AppPoolIdentitytype"
                                        Set-ItemProperty IIS:\AppPools\$using:AppPoolName -Name managedPipelineMode -Value "$using:ManagedPipelineMode"
                                        Set-ItemProperty IIS:\AppPools\$using:AppPoolName -Name managedRuntimeVersion -Value "$using:ManagedRuntimeVersion"
                                    }
                    }
                }

                xWebApplication MyComponentWebApplication_Install 
                { 
                    Name = $WebApplicationName 
                    Website = $WebsiteName 
                    WebAppPool = $AppPoolName 
                    PhysicalPath = "$WebAppPhysicalPath" 
                    Ensure = $Ensure
                    DependsOn = @("[xWebSite]MyComponentWebsite") 
                }

                Script Present_MyComponentWebApplicationProperties_Install
                {
                    GetScript = {
                                    $result = @{WebsiteName = $WebsiteName
                                           WebApplicationName = $WebApplicationName}
                                    return $result
                                }
                    TestScript = {
                                    return $false
                                 }
                    SetScript = {
                                    Import-Module Webadministration
                                    Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/windowsAuthentication" -Name Enabled -Value True -PSPath "IIS:\Sites\$WebsiteName" -Force -ErrorAction SilentlyContinue
                                    Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/AnonymousAuthentication" -Name Enabled -Value True -PSPath "IIS:\Sites\$WebsiteName" -Force -ErrorAction SilentlyContinue
                                    Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/windowsAuthentication" -Name Enabled -Value True -PSPath "IIS:\Sites\$WebsiteName\$WebApplicationName" -Force -ErrorAction SilentlyContinue
                                    Set-WebConfigurationProperty -Filter "/system.webServer/security/authentication/AnonymousAuthentication" -Name Enabled -Value True -PSPath "IIS:\Sites\$WebsiteName\$WebApplicationName" -Force -ErrorAction SilentlyContinue
                                }
                    DependsOn = @("[xWebApplication]MyComponentWebApplication_Install")
                }
            }             
        }
}

Write-Verbose "Executing MyComponentWebsite Deployment - Start" -Verbose

MyComponentWebsite
Start-DscConfiguration -Path MyComponentWebsite -Verbose -Wait -ComputerName $DeployServerName -force
Write-Verbose "Executing MyComponentWebsite - End" -Verbose`

**Comment by ArieHein** [comment]
Hi and thanks for the configuration script,

Nothing i can see directly from the configuration script, except the two
        if ($Ensure -ieq "Present")
sections in the script, but that in itself shouldn't be a reason for such behavior.

LCM ConfigurationMode will always try to apply a new configuration and will continue to until successful, no matter what the value is. The difference will be whether it checks for a drift and what it does if it finds one. So as long as there's a new configuration in the process of being applied, the value of ConfigurationMode isn't looked upon.

I can think of one place in the code that might contribute, but its a slim chance.
This is in the File resource your using, it might have brought the file back from the original
$SourcePath as you have MatchSource set to True, Force set to True, and Checksum set to CreatedDate.
          
When fixing the web.config, was it done manually on the node itself, or did you do the fix in the DSC configuration script and then pushed it again ? 

You didnt  link your LCMscript but ill assume it is ok or you wouldn't be able to do other activities.

**Comment by ip28** [comment]
Hi Arie,
Thanks for your reply and explanation of the script.
 We don't have a specific LCM script as such. This deployment script is called remotely by another script. 
The web.config was corrected manually on the target machine.

Regards,
Indranil

**Comment by ArieHein** [comment]
Hi,

As a rule of thumb, when you venture into the world of configuration management and deveops in generally, try to make sure you stop doing ANY manual changes to anything as you introducing "chaos" to a system that's trying to remain balanced.

The main idea with DSC is that I can run it on a node 1000 times and I will always get the same result = the same state, no matter what changes someone did manually. So I know for 100% at what state a system is especially when I cant control them multiple changes that may happen to a node.

I've been emphasizing to my peers to stop any manual changes, any RDP session, convert all manual configurations into scripts and then when a change is needed, it is done to the code/script that's is stored in our local source control.

You want to make a change to web.config you best do it at the source and run the configuration script again. AS most of the settings in the configuration are the same the script will be very fast, compared to the first time you run the script.

**Comment by ip28** [comment]
Hi Arie,
 Thanks a lot for giving insights on the way DSC works, I too agree with you on avoiding manual changes. I am new to DSC, this is what we are doing for our components:-
1. Deployment scripts are through DSC
2. Web.Config changes etc are with normal (non-DSC) PowerShell [I believe DSC will consider this also as manual change, please correct me if I am wrong]

The applications which we are deploying are kinda legacy (monolith WCFs, windows services etc.) and are very heavily dependent on configuration, also in case of Disaster Recovery or tenant (caller) on-boarding, these configs might change, also we can't afford downtime of the service (we have multiple servers and take one/few server out of load balancer before deployment). 

The whole purpose of configuration (web.config etc.) , as I understood, is to give flexibility to change values/behaviour of the application without having to change the code and redeploy the application again. But if I try to run the deployment script again, just for a configuration change, which essentially redeploys the whole service, is as good as keeping all config values in the code itself.
Also, I feel I might have misunderstood the DSC documentation, I thought "ApplyandMonitor" LCM configuration will detect the change in state and just log it into event viewer, without changing the actual code bits.

It might be possible we are using DSC in a wrong way, but it will be really helpful if you can guide me here.

Thanks a ton for your elaborate reply again, really appreciate it.

Thanks,
 Indranil
