### ISSUE TITLE
We need to have daily release build to make sure the release build pipeline works

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3910]
Currently, we only run Jenkins build when we are working on a release, so if there are any issues that cause the Jenkins build to fail, we won't know until at release time. We need to set up daily Jenkins build so that issues can be caught early enough.

@TravisEz13 is working on enabling the release build pipeline in VSTS

**Comment by TravisEz13** [comment]
Added the schedule.  Will verify tomorrow.

**Comment by TravisEz13** [comment]
We have had two scheduled runs with only antivirus signature update failures.
