### ISSUE TITLE
Need to add logging to understand failures Import-Counter.Tests.ps1

### ISSUE THREAD

**Issue by Francisco-Gamino** [PowerShell/PowerShell#3913]
Steps to reproduce
------------------
``` powershell
# Build PowerShell

# Start PowerShell Core at this location:
E:\GitHub\PowerShell\test\powershell\Modules\Microsoft.PowerShell.Diagnostics>

# Run Import-Counter tests
.\Import-Counter.Tests.ps1

```
The file to update is the following:
https://github.com/PowerShell/PowerShell/blob/c97ca777dfb2536dc79051dfa1ae7dce852df125/test/powershell/Modules/Microsoft.PowerShell.Diagnostics/CounterTestHelperFunctions.ps1#L262

Expected behavior
-----------------
All test pass

Actual behavior
---------------

```powershell
# We had one failure in appveyor 

Test failure
Description: Can import samples ending at a given end time (BLG format)
Name:        Feature tests for Import-Counter cmdlet.Can import samples ending at a given end time (BLG format)
message:
Expected: {11}
But was:  {20}
stack-trace:
at line: 262 in C:\projects\powershell-f975h\test\powershell\Modules\Microsoft.PowerShell.Diagnostics\CounterTestHelperFunctions.ps1
$setA.Length | Should Be $setB.Length
```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by Francisco-Gamino** [comment]
@TravisEz13 : Could you please send @MiaRomero the logging example you were talking about? Thanks.

**Comment by TravisEz13** [comment]
@MiaRomero  https://github.com/PowerShell/PowerShell/blob/master/test/tools/Modules/HelpersCommon/HelpersCommon.psm1#L48
