### ISSUE TITLE
Disable-ScheduledTask -TaskName will fail with tasks including spaces in name.

### ISSUE THREAD

**Issue by r-pufky** [PowerShell/PowerShell#3915]
Steps to reproduce
------------------
Disable-ScheduledTask -TaskName "Data Integrity Scan for Crash Recovery"
Disable-ScheduledTask : The system cannot find the file specified.
At line:1 char:1
+ Disable-ScheduledTask "Data Integrity Scan for Crash Recovery"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [ 
   Disable-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070002,Disable-ScheduledTask

Expected behavior
-----------------
This should disable the scheduled task and not crash.

You can workaround this by searching for the task object and disabling that way:

$Name = "Data Integrity Scan for Crash Recovery"
Get-ScheduledTask | where-object {($_.TaskName -eq $Name)} | Disable-ScheduledTask

Actual behavior
---------------
Crashes with the following exception:
Disable-ScheduledTask : The system cannot find the file specified.
At line:1 char:1
+ Disable-ScheduledTask "Data Integrity Scan for Crash Recovery"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [ 
   Disable-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070002,Disable-ScheduledTask

Environment data
----------------
Name                           Value                                                                 
----                           -----                                                                 
PSVersion                      5.1.15063.296                                                         
PSEdition                      Desktop                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                               
BuildVersion                   10.0.15063.296                                                        
CLRVersion                     4.0.30319.42000                                                       
WSManStackVersion              3.0                                                                   
PSRemotingProtocolVersion      2.3                                                                   
SerializationVersion           1.1.0.1

**Comment by iSazonov** [comment]
@r-pufky Thanks for you report!

The cmdlet is not in the Repo - please report to [UserVoice]( https://windowsserver.uservoice.com/forums/301869-powershell).

**Comment by joeyaiello** [comment]
@iSazonov for those modules not actually owned by the PowerShell Team, that's not actually the right place either. 

@r-pufky please file that one using the Windows 10 Feedback Hub as Scheduled Tasks (and its associated PowerShell module) is a component of Windows 10. 

Sorry about the confusion!

**Comment by r-pufky** [comment]
Thanks,

I've already submitted it to: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/19474735-disable-scheduledtask-taskname-will-fail-with-tas

I'll submit another issue via the feedback hub per @joeyaiello later tonight.

**Comment by r-pufky** [comment]
This has been posted to the feedback hub: https://aka.ms/Xirmlx

**Comment by joeyaiello** [comment]
@r-pufky thanks for that! I'm not super familiar with the Feedback Hub tool, but I know that's the right place for it. If there's some way for you to edit the category to Server -> Management, that would be awesome as well. (Again, it's the Scheduled Task team that needs to fix this...)

**Comment by r-pufky** [comment]
There were no server categories for the feedback submission selections, so I grabbed the closest one related to powershell. It seems that the feedback hub is geared much more towards consumer submissions :\

I cannot change the category post submission, but I've left a comment on the submission indicating where it *should* go.

Here's a list of all feedback submission categories:
![selections-1](https://user-images.githubusercontent.com/4778046/26864083-f831c3ba-4b0a-11e7-856c-f27d379f6415.png)
![selections-2](https://user-images.githubusercontent.com/4778046/26864085-fd492aa0-4b0a-11e7-9244-654fcddb208c.PNG)
