### ISSUE TITLE
Unregister-ScheduledJob -Name 'Name' -WhatIf does not honor whatif

### ISSUE THREAD

**Issue by wasserja** [PowerShell/PowerShell#3920]
From [UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/19501987-unregister-scheduledjob-name-name-whatif-does).

Steps to reproduce
------------------
Import-Module PSScheduledJob
Register-ScheduledJob -Name 'test' -ScriptBlock {echo 'hello world'}
Unregister-ScheduledJob -Name test -WhatIf
Get-ScheduledJob

Expected behavior
-----------------
I expect the job to still be there.

It *does* work with Unregister-ScheduledJob -Id 11 -WhatIf.

Actual behavior
---------------
The scheduled job is corrupted. 

Get-ScheduledJob : Cannot get the test scheduled job because it is corrupted or in an irresolvable state. Because
it cannot run, Windows PowerShell has deleted test and its results from the computer. To recreate the scheduled
job, use the Register-ScheduledJob cmdlet. For more information about corrupted scheduled jobs, see
about_Scheduled_Jobs_Troubleshooting.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
The cmdlet isn't still ported. So please duplicate the report to [UserVoice]( https://windowsserver.uservoice.com/forums/301869-powershell) too.

**Comment by wasserja** [comment]
I have duplicated the report in UserVoice.

Jason Wasser

**Comment by iSazonov** [comment]
@wasserja Please add cross-links to/from UserVoice.

**Comment by wasserja** [comment]
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/19501987-unregister-scheduledjob-name-name-whatif-does
