### ISSUE TITLE
Start-PSBuild -SMAOnly not working

### ISSUE THREAD

**Issue by anmenaga** [PowerShell/PowerShell#3924]
-SMAOnly flag does Not work when building using Start-PSBuild.

Steps to reproduce
------------------
`Start-PSBuild -SMAOnly`

Expected behavior
-----------------
Build successful.

Actual behavior
---------------
Error:

> Assets file 'System.Management.Automation\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0/win10-x64'

**Comment by iSazonov** [comment]
I started to publish PRs to move the logic from Build.psm1 to csproj files and take advantages of MSBuild. This way, we get an optimized and fast re-build process.

**Comment by vors** [comment]
This should be fixed already, not sure why it didn't auto close this issue before.
