### ISSUE TITLE
PSRP over SSH into Mac does not work

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell#3935]
I’ve been struggling to get PSRP over SSH working INTO the Mac. I can make all other directions and OSes work, including FROM the Mac.
 
From either Ubuntu or Windows I can SSH into the Mac with no issue. However, if I try Enter-PSSession -SSHTransport into the Mac my session will hang for a while, and then it will start scrolling blank lines very fast. CTRL+C will not work. I have to end the session to get out of it.
 
All three OSes have OpenSSH installed and configured with the Subsystem in sshd_config. The Mac has remote login enabled and working over normal SSH.

Steps to reproduce
------------------
From a Windows or Linux host into a Mac host:
Enter-PSSession -Hostname machost -Username y -SSHTransport

Expected behavior
-----------------
Normal PowerShell remoting prompt

Actual behavior
---------------
After entering the password at the prompt the local console hangs for a number of minutes, then it begins to scroll blank lines very quickly. CTRL+C will not interrupt it. Must end the session by closing the terminal.

Environment data
----------------

```powershell
Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta                                      
PSEdition                      Core                                            
BuildVersion                   3.0.0.0                                         
CLRVersion                                                                     
GitCommitId                    v6.0.0-beta.1                                   
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: F...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0  
```

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MaximoTrinidad** [comment]
Hum!  Just in case, what's the OpenSSh version installed in Windows?
It should be version v0.0.15.0: https://github.com/PowerShell/Win32-OpenSSH/releases

Also, have you try using the "enter-possession..." without the -sshtransport parameter. I don't use that parameter between my Linux and Windows systems so I'm curious to see if it makes any difference.

:)

**Comment by GoateePFE** [comment]
I see the exact same result from Linux to Mac with PSRP over SSH.

**Comment by MaximoTrinidad** [comment]
Ah! To bad I don't have a Mac to properly test this issue. 
:)

Sounds like a bug!

**Comment by qiUnity** [comment]
I'm on 6.0.0-beta2 and hitting the same.

**Comment by SteveL-MSFT** [comment]
Working for me with beta.7, updating demo docs to include Mac specific configuration steps (see referenced PR to try out)
