### ISSUE TITLE
Need to automate as many steps as possible in our release process

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3942]
Some of our release steps can be automated:

- [x] Microsoft Source Code Compliance Tasks (Microsoft Employee Only)
- [x] Step 2.3 - Once the candidate packages are generated, we need to install them and verify the packages. This validation could be automated, at least for Linux packages.
- [x] Step 3.3 - Update documents and scripts to use the new package names and links. This could be automated. _[update] we will ask every PR to add one line to CHANGELOG.md for the PR_
- [x] Step 4 - We need to verify release Dockerfiles that are used for building the container images before creating/pushing the release tag. This validation could be automated.
- [x] Step 5 - Publish Linux packages to Microsoft YUM/APT repositories.
- [x] Step 6 - Create NuGet packages and publish to powershell-core. This could be automated.
- [x] Step 9 - Create release draft in Github. This could be automated. Refer to section 3 in 'StepsToReleasePSCore.md'.
- [x] Step 11 - Once the Docker builds are done, we need to verify the generated docker images. This validation could be automated.
- [ ] Microsoft Binary and Package Compliance Tasks 
  - [ ] [Code Metrics](https://msdn.microsoft.com/en-us/library/bb385914.aspx?f=255&MSPPError=-2147217396)
  - [ ] [FXCop](https://github.com/dotnet/roslyn-analyzers)
  - [x] Other (Microsoft Employee Only)

**Comment by iSazonov** [comment]
Script or MSBuild? Before we talked that we would have separate csproj for packaging.

**Comment by daxian-dbw** [comment]
@iSazonov Those should be scripts to help reduce manual validations in a release. We want to improve the release process before `beta.3`.
As for csproj, I'm not sure how far we want to go with .csproj to replace our build scripts. Need some discussion on it.

**Comment by iSazonov** [comment]
@daxian-dbw What is current state? Should we enhance of using .csproj ? I think our scripts (Build.psm1) scripts become too complex to support. We could move some _stable_ parts to .csproj files. I mean ResRen and TypeGen in the first place.

**Comment by daxian-dbw** [comment]
@iSazonov For the release procedure, we have made more tasks run in parallel.
For moving to `.csproj`, we haven't yet had a discussion internally on how much we want to move to `.csproj`. I have 2 unbaked thoughts:
1. We have more and more build steps gradually, such as embedding icon resources, fixing symbolic links, download additional modules and etc. If we move all to `csproj`, it will become another huge complex `build.psm1`. So I think we need to understand what the goal is, and only move those steps to `csproj` to support the goal.
2. If we move some steps to `.csproj`, then we need to make sure those steps run only once when building all powershell assemblies. If I remember correctly, the target `GetPSCoreVersionFromGit` runs for building every powershell assembly. It's OK to do some duplicate 'git describe' and regex matching, but for a build task like `resgen`, it would be too expensive.

/cc @PowerShell/powershell-maintainers

**Comment by iSazonov** [comment]
@daxian-dbw Thanks! I agree with p.1.

It is not a problem to run our `ResGen.exe` for every assembly. It is already enhanced to re-generate only changed resx files. Currently if you change one resx file all resx files should be regenerated manually and _all_ cs files will be re-compiled. With csproj we check if any resx file changed and only the _single_ changed file will be re-compliled.
For TypeGen the same - we could re-generate "powershell.inc" only if json files changed by `dotnet restore` or the file is missing. 
I have no idea how we can build on VS 2015 without these things.
