### ISSUE TITLE
Represent output from external executables as raw byte streams

### ISSUE THREAD

**Issue by masaeedu** [PowerShell/PowerShell#3943]
The raw text story in Powershell is kind of annoying right now. There's lots of gotchas with newlines and encodings, so a simple command like `type foo.txt > bar.txt` ends up turning into `type foo.txt | out-file -encoding ascii -nonewline bar.txt` (and I might still be missing some edge cases).

If an object isn't already a string array, I usually don't want it to be implicitly coerced into one, since:

 - This can be a lossy transformation, and can [introduce subtle data corruption](https://github.com/PowerShell/PowerShell/issues/2145)
 - I'm usually piping stuff from one file descriptor to another (exe to exe, stdout to exe, exe to stdin, etc.), so all the string encoding/decoding roundtrip does is slow things down

It would be useful if decoding I/O streams could be turned into an opt-in feature of certain operators and cmdlets, instead of being implicitly applied to every external data source. Specifically, the result of ``(echo.exe "foo`nbar").gettype()`` should be some kind of `Stream` type instead of a string array. 

Without any other changes, this would massively break existing Powershell code that pipes to/from executables and files. However, it is possible to greatly mitigate this issue if the task of guessing a byte stream's encoding and splitting by newline is instead shifted to the pipe operator and cmdlets. In other words, while ``echo.exe "foo`nbar"`` is a stream, ``echo.exe "foo`nbar" | % { $_ }`` is still an array of lines, as in previous versions, and each `$_` is a string.

Piping without decoding the stream can then be provided as an additional binary operator (perhaps `|>`). If the RHS of the expression is an invocation of an external process, the stream returned from the LHS should simply be fed into the stdin of the new process invocation. If the RHS is a cmdlet/function, the stream should be passed to it as some well-specified variable, similarly to how `$input` works now.

**Comment by iSazonov** [comment]
I believe it is duplicate https://github.com/PowerShell/PowerShell/issues/1908

**Comment by masaeedu** [comment]
@iSazonov Yup, dupe
