### ISSUE TITLE
Refactor the Get-Content tests to use -TestCases

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#3945]
This came up during the code review for PR #3808 regarding this test:

It "should throw 'PSNotSupportedException' when you set-content to an unsupported provider" -Skip:($IsLinux -Or $IsOSX) { 

It should be refactored to use the -TestCases feature of Pester.

Environment data
----------------

6.0.0-beta.2

**Comment by TravisEz13** [comment]
The comment triggering this is here:  https://github.com/PowerShell/PowerShell/pull/3808#discussion_r118306040

**Comment by TravisEz13** [comment]
Code is currently at https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1#L73

**Comment by adityapatwardhan** [comment]
Please refactor this test using TestCases from Pester https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1#L113

**Comment by kalgiz** [comment]
Fixed in PR #6082
