### ISSUE TITLE
Enable upgrade (not SxS) install from MSI

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3946]
Just for clarification. So, it's required to first remove the previous version before installing the latest.
Right!

I'm not sure if this could lead to some of the issues I'm experiencing with remoting (maybe).

So, are there any plan to automatically do the upgrade?

![poshinstall](https://cloud.githubusercontent.com/assets/19892435/26809999/d5b54660-4a36-11e7-8369-ef3b9aee0c5a.png)

**Comment by SteveL-MSFT** [comment]
Currently each version has been a side-by-side install on Windows.  We've been discussing internally how to improve the install experience on Windows and hopefully we'll have an RFC posted in the near future.

cc @joeyaiello

**Comment by SteveL-MSFT** [comment]
The leftover files on Linux are due to an older issue you opened https://github.com/PowerShell/PowerShell/issues/3758

**Comment by joeyaiello** [comment]
Renaming this issue to only address the Windows aspect of the problem (given that the Linux part of it is duped).
