### ISSUE TITLE
Meta issue: add code blocks to the relevant sections of the new-issue template to facilitate formatting

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3952]
Not sure where to post this, so I'm doing it here.

Below is a modified version of the new-issue template (use the markdown source) that adds fenced code blocks / output blocks  to the `Steps to reproduce`, `Expected behavior` and `Actual behavior` sections, to facilitate proper formatting.

---

Steps to reproduce
------------------

```powershell

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by lzybkr** [comment]
You can submit a PR on the issue template - it's [here](https://github.com/PowerShell/PowerShell/edit/master/.github/ISSUE_TEMPLATE.md)

**Comment by mklement0** [comment]
Thanks, @lzybkr - find the PR at #3953
