### ISSUE TITLE
HelpSystem should be a separate module outside of the engine

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3955]
HelpSystem code is currently in SMA.dll, it should really be a separate module so that non-interactive use, for example, doesn't need to pull it in.

**Comment by iSazonov** [comment]
Should we move the HelpSystem in new namespace "Microsoft.PowerShell.HelpSystem" and new folder with the same name?

**Comment by SteveL-MSFT** [comment]
We should think through the impact to reduce compatibility issues.  cc @PowerShell/area-helpsystem
