### ISSUE TITLE
Add a new parameter to Get-Counter to quickly capture instantaneous raw data

### ISSUE THREAD

**Issue by jtippet** [PowerShell/PowerShell#3974]
The builtin Get-Counter cmdlet queries the system performance counters.  Many counters are presented as rates, i.e., thing-per-second.  In order to measure the rate, the Get-Counter cmdlet takes one measurement, sleeps for a second, takes a second measurement, then does the arithmetic.  Get-Counter returns an object that contains both the raw counter value and the computed rate of change.

For example, a network interface has a "Bytes Total/sec" counter:

````
PS C:\> (Get-Counter '\Network Interface(*)\Bytes Total/sec').CounterSamples[0] | fl *

Path             : \\computer\network interface(intel[r] 82579v gigabit network connection)\bytes total/sec
InstanceName     : intel[r] 82579v gigabit network connection
CookedValue      : 64.1894983120117
RawValue         : 2522840331
SecondValue      : 2927905331869
MultipleCount    : 1
CounterType      : RateOfCountsPerSecond64
Timestamp        : 6/8/2017 23:50:36
Timestamp100NSec : 131414394363810000
Status           : 0
DefaultScale     : 4294967292
TimeBase         : 3020490
````

Here the `CookedValue` is the rate, measured in bytes per second, and is what the user usually wants to see.  The formatter for a `PerformanceCounterSample` highlights this value, and that's great.  In contrast, the `RawValue` is the absolute total number of bytes sent (since the system rebooted).  Usually the user doesn't need this.  But there *are* a few good uses for the RawValue.

One use for RawValue: Suppose you want to get a rolling average over the last 60 seconds.   The cmdlet itself doesn't support rolling averages, so you have to build it yourself.  You could either run Get-Counter 60 times in parallel, which gets a bit silly.  Or you could run Get-Counter once every second, capturing the RawValues (and discarding the rest of the data).  But now there's a new problem -- because Get-Counter internally sleeps for 1 second, you can't quite run it 60 times consecutively in 60 second.  You either have to fudge the arithmetic with some errors, or run multiple Get-Counter calls in parallel.

There are a few other reasons you'd *only* want the RawValue -- you might want to get statistics measured over a large interval like an hour, but you don't want the cmdlet to sit there sleeping for an hour.  You might want to build a weighted average.  The end user might just only be interested in the total number of packets sent, not the rate.  If you're doing any sort of statistical analysis, the RawValue is almost always a better starting point than the CookedValue.  Sleeping for a second to get the CookedValue just gets in the way, then.

Anyway, I propose we add a new parameter to Get-Counter.  The new parameter tells the cmdlet to just capture the first raw sample, do not sleep, and do not bother trying to calculate any CookedValue.  The new parameter is not compatible with the preexisting -SampleInterval or -MaxSamples parameters, so it should probably go into a new ParameterSet.

Naming is always hard.  I can think of a few names for the new thing, and I'm totally open to suggestions & analogies to preexisting features in other cmdlets:
  *  -RawOnly (hinting that the user is only interested in the RawValue from the output)
  *  -CookedValue:$false  (which tells the user what will be missing from the output)
  *  -Instantaneous  (which suggests why you'd want this option: the cmdlet runs much faster with it)

I'm willing to implement, test, and document it myself.  I have a working prototype that -- amazingly enough -- demonstrates how eliminating a 1-second sleep from something makes it almost 1000 milliseconds faster:

````
# Before
PS C:\Source\Repos\PowerShell> Measure-Command { Get-Counter '\Network Interface(*)\Bytes Total/sec' }
TotalMilliseconds : 1002.9342

# After, with the new thing
PS C:\Source\Repos\PowerShell> Measure-Command { Get-Counter -RawOnly '\Network Interface(*)\Bytes Total/sec' }
TotalMilliseconds : 4.6826
````

Thanks for reading.  Is the motivation motivating?  Any thoughts on the design or naming?

**Comment by iSazonov** [comment]
My understanding you want to get one instantaneous value without delay and fix should just let you remove the delay.

**Comment by jtippet** [comment]
Yeah that's the one-sentence summary :)

**Comment by iSazonov** [comment]
We can get the same single raw couter values by [WMI](https://blogs.technet.microsoft.com/georgewallace/2013/10/29/pulling-performance-counters-from-wmi-with-powershell/). So I see no reasons why this is not possible by `Get-Counter`.

**Comment by jtippet** [comment]
Well the blog you linked to demonstrates how to get cooked counters out of WMI.  But I did a bit of looking, and found that you can get raw counters from WMI:

**Comment by iSazonov** [comment]
I think it might be useful.
If PDH doesn't scare you, you can easily push the PR - welcome!
