### ISSUE TITLE
PowerShellAssemblyLoadContext is not initialized in .NetCore 2.0 Preview

### ISSUE THREAD

**Issue by sonphnt** [PowerShell/PowerShell#3975]
Hi 

I have installed .NetCore 2.0 Preview and play around a bit in console app with Powershell core (SMA.dll 6.0.0 beta 2)

```
Runspace runspace = RunspaceFactory.CreateRunspace();
            runspace.Open();
            using (System.Management.Automation.PowerShell ps = System.Management.Automation.PowerShell.Create())
            {
                ps.Runspace = runspace;
                ps.AddScript("Get-Process");
                var results = ps.Invoke();
            }
            runspace.Close();
```

I got exception with "PowerShellAssemblyLoadContext is not initialized". These code lines works fine with former .NetFramework 4,5

Do you know what make this code raise exception?

Thanks

**Comment by SteveL-MSFT** [comment]
I believe https://github.com/PowerShell/PowerShell/issues/3649 will resolve your issue

**Comment by SteveL-MSFT** [comment]
Actually, did you follow this? https://github.com/PowerShell/PowerShell/blob/2d06c17093f8ce7805e24e83f86925275aa038f0/docs/host-powershell/README.md

**Comment by sonphnt** [comment]
Hi @SteveL-MSFT  

Is #3649 still being fixed, isnt it? I can see there are some tasks incomplete in his list.

And the second link you mentioned looks like we have to load dll from a class that requires some unfriendly coding with assembly name and dll.

**Comment by SteveL-MSFT** [comment]
I think what we need here is a clear example in our repo for hosting PowerShell

**Comment by sonphnt** [comment]
Yes. I agree. We should have an clear example how to execute a simple PS script. And also that would be perfect if we could have ONLY 1 nuget package for Powershell instead of 5-6 packages involving to PS need to be installed at the same time such as

System,Management.Automation 6.0.0 beta 2
Microsoft.WSMan.Management 6.0.0 beta2
Microsoft.Powershell.SDK 6.0.0 beta2
Microsoft.Powershell.Commands.Diagnostics. 6.0.0 beta2
...

Thanks

**Comment by daxian-dbw** [comment]
When using any powershell NuGet packages prior to beta.3, you need to read the instructions in https://github.com/PowerShell/PowerShell/blob/2d06c17093f8ce7805e24e83f86925275aa038f0/docs/host-powershell/README.md, and if you read it, you will know there are samples already 😄 see here:
- [sample-dotnet1.1](https://github.com/PowerShell/PowerShell/tree/2d06c17093f8ce7805e24e83f86925275aa038f0/docs/host-powershell/sample-dotnet1.1)
- [sample-dotnet2.0-powershell.beta1](https://github.com/PowerShell/PowerShell/tree/2d06c17093f8ce7805e24e83f86925275aa038f0/docs/host-powershell/sample-dotnet2.0-powershell.beta.1)

The beta.3 packages will make hosting story the same as on Full CLR.

As for NuGet packages, you can just reference to Microsoft.Powershell.SDK and Microsoft.Powershell.Commands.Diagnostics, the former package will pull in the rest packages.

**Comment by MaximoTrinidad** [comment]
@sonphnt, 

Curious! Which OS are you using to run this code?

Thanks,
:)

**Comment by daxian-dbw** [comment]
#3998 is filed to track adding another sample when beta.3 is out.
