### ISSUE TITLE
Windows installation doc: broken link to Visual C++ Redistributable

### ISSUE THREAD

**Issue by JeffJacobson** [PowerShell/PowerShell#3977]
In the documentation for Windows installation in the [prerequisites](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/windows.md#prerequisites) section, the link to *[Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145) for VS2015* is broken. (I tried searching microsoft.com to find the current location, but their search also just returns the same outdated URL.)

**Comment by SteveL-MSFT** [comment]
Try https://my.visualstudio.com/Downloads?pid=2082
