### ISSUE TITLE
Dynamic Parameter Doesn't Autocomplete

### ISSUE THREAD

**Issue by mattmcnabb** [PowerShell/PowerShell#3984]
Consider this function:

```powershell
function Test-DynamicParameter
{
    [CmdletBinding()]
    PARAM
    (
        [string[]]
        $Param1,
        # this parameter seems to cause the problem - if I specify [string] then tab-completion works for -DynamicParameter
        [PSCredential]
        $Param2
    )
    DYNAMICPARAM 
    {
        $Name = "DynamicParameter"
        $ParamAttr = [System.Management.Automation.ParameterAttribute]::new()
        $ParamAttr.Mandatory = $true
        $Attributes = [Collections.ObjectModel.Collection[System.Attribute]]::new()
        $Attributes.Add($ParamAttr)
        $Parameter = [System.Management.Automation.RuntimeDefinedParameter]::new($Name, [string], $Attributes)
        $Dictionary = [System.Management.Automation.RuntimeDefinedParameterDictionary]::new()
        $Dictionary.Add($Name, $Parameter)
        $Dictionary
    }
    PROCESS
    {

        $DynamicParameter
    }
}
```

It seems that auto-completion of the dynamic parameter name is broken by the inclusion of the [PSCredential]-typed parameter. 

This works as expected - hitting tab expands the parameter "-DynamicParameter"
`Test-DynamicParameter -Param1 'a' -<tab>`

This fails - hitting tab does nothing. however, the parameter still works if I type it out
`Test-DynamicParameter -Param1 'a' -Param2 $Credential -<tab>`

If I change the type attribute of Param2 to [string] then tab-completion works for the dynamic parameter

I have observed this happening with other parameter types as well -for instance, the same condition exists if you use [DateTime] for Param2. Also, when using Plaster at the command line to scaffold a new PowerShell project, the parameters defined in the Plaster manifest won't autocomplete. This may also be the same bug.

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.296
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.296
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by paule96** [comment]
also not working, if you type in a parameter that requieres a hashTable

**Comment by thedavecarroll** [comment]
I'm having a similar issue when specifying a `[ValidateScript()]` in the param section. With it commented out, intellisense properly displays the dynamic parameter. 

This does not prevent manually supplying the dynamic parameter and value.

Reproduced on PS versions 5.1, 7.01, and 7.1.0-preview.3 on Windows 10.0.18363 and 7.0.0 on  WSL Ubuntu 18.04 (Linux 4.4.0-18362-Microsoft).

Thank you for all you that do to bring the best PowerShell to the community.

**Comment by FireQuencher** [comment]
This also happens if you are working with arrays. Evaluating a [string] makes intellisense/tab completion work, but if you look at a [string[]] it will stop working, but the function will run as intended
