### ISSUE TITLE
Enhance suggestion code to recommend typos for commands and parameters

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3988]
PowerShell's current [suggestion code](https://github.com/PowerShell/PowerShell/blob/7a55bf98b2370ab4817ab2533cb67673053ee446/src/System.Management.Automation/engine/hostifaces/HostUtilities.cs#L335) is limited.  We should enhance it to give a better experience like the `git` command on typos for arguments or `apt-get` finding apps to install that fit your missing command (leveraging PowerShellGet).

**Comment by iSazonov** [comment]
We already have a Issue #3955 to put HelpSystem in a separate module. This will allow _different_ Help systems. We can deal with these issues together. I believe HeplSystem should have not only a description of the commands but also a description of the errors. This is very related.

Option to turn on/off suggestions.

Get a help for an error:
 Get-Help -Error    - for last error
 Get-Help -Error nnn    - for `$error[nnn]` error
 Get-Help -Error $error[kkk] - for `$error[kkk]` error
 Get-Help -FullyQualifiedErrorId <name>

We could add an option for error detail:
 - only short generic error message
 - short error message optionally with short help message (like current behavior)
 - long error message with long help message

We could review all Resx error strings to move it to a common format template.

**Comment by SteveL-MSFT** [comment]
@iSazonov that's an interesting idea we should certainly explore

**Comment by lzybkr** [comment]
Dupe of #1982?

**Comment by SteveL-MSFT** [comment]
@lzybkr agree
