### ISSUE TITLE
Remove usage of HasFlags

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#3989]
The `HasFlags()` method has [performance impact](https://www.codeproject.com/tips/441086/nets-enum-hasflag-and-performance-costs) and the recommendation is to use a simple bitwise comparison instead.

There's a number is cases in our [source](https://github.com/PowerShell/PowerShell/search?utf8=%E2%9C%93&q=hasflag&type=) that uses this and some in core loops.

**Comment by iSazonov** [comment]
Is the true for CoreFX? I don't see using reflection. https://github.com/dotnet/coreclr/blob/5b9680fcc9b6fe9429f4a649bf5215de273fcbec/src/mscorlib/src/System/Enum.cs#L964

**Comment by SteveL-MSFT** [comment]
That code still has the type safety check and if you look at [InternalHasFlags](https://github.com/dotnet/coreclr/blob/13e7c4368da664a8b50228b1a5ef01a660fbb2dd/src/vm/reflectioninvocation.cpp#L3064) it still boxes and unboxes along with additional checks.

**Comment by SteveL-MSFT** [comment]
@louistio given the optimizations in JIT in .NET Core 2.1, this no longer seems relevant.  Thanks for bringing this up!

**Comment by xtqqczze** [comment]
> @louistio given the optimizations in JIT in .NET Core 2.1, this no longer seems relevant. Thanks for bringing this up!

Issue opened to replace the existing bitwise flag comparisons: #18385.
