### ISSUE TITLE
Suggestion: Alias Start-Sleep's -Milliseconds parameter to -ms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#3991]
"ms" is a standard abbreviation for "milliseconds", so it make sense to allow `-ms` as an alias for `-MilliSeconds`.

```powershell
Start-Sleep -ms 100  # should be short for Start-Sleep -Milliseconds 100
```

```powershell
PowerShell Core v6.0.0-beta.2
```

**Comment by SteveL-MSFT** [comment]
Just add a `[Alias("ms")]` here https://github.com/PowerShell/PowerShell/blob/7a55bf98b2370ab4817ab2533cb67673053ee446/src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs#L55 as well as new test case.
