### ISSUE TITLE
PowerShell Core Beta 2 - Windows Bash Console screen refresh not working on copy /paste

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#3993]
In Windows 10 Insider 16215, Bash Console is finally working.  But, when you copy/paste a block of code, the screen is not refresh correctly leaving characters scatter on top of the prompt.

Also, sometime it will leave spaces between prompt.
Steps to reproduce
------------------
1. Open Windows 10 Bash Console
2. Start PowerShell
3. Copy/Paste the following code:
```powershell
[System.Console]::OutputEncoding = [System.Text.Encoding]::ASCII
Write-Host "PowerShell version: $($PSVersionTable.psversion) loaded"
```

Expected behavior
-----------------
The console should display back the following result:
```none
PS /home/maxt> Write-Host "PowerShell version: $($PSVersionTable.psversion) loaded"
PowerShell version: 6.0.0-beta loaded
```

Actual behavior
---------------
Screen refresh is leaving unwanted screen results.
```none
PS /home/maxt> System.Console]::OutputEncoding = [System.Text.Encoding]::ASCII
"PPoweSrSh el/l vheorsimon:e /$(m$aPSxVetrsion>Tab le.ps[vers ion )  loa ded "                                                                                     PS /home/maxt> [System.Console]::OutputEncoding = [System.Text.Encoding]::ASCII
PS /home/maxt> Write-Host "PowerShell version: $($PSVersionTable.psversion) loaded"
PowerShell version: 6.0.0-beta loaded
PS /home/maxt>
```

Environment data
----------------

Windows 10 Insider 16215 -> Bash Console - Ubuntu 16.04.2 LTS

.NET Core 2.0 Preview 1 

```powershell
PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.2
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
![bashcorescreenissue_2017-06-12_14-40-24](https://user-images.githubusercontent.com/19892435/27049517-9ab8f9ca-4f7d-11e7-93bf-3d686953419d.jpg)

**Comment by joeyaiello** [comment]
Yeah, this kinda stinks...been messing around this weekend, and it's definitely a legit bug. The line or two above wherever you paste gets corrupted by any paste

**Comment by joeyaiello** [comment]
Also, still repros on Beta.7`

**Comment by SteveL-MSFT** [comment]
Works for me on Win 10.0.16299.2

**Comment by fmichaleczek** [comment]
Works for me on Win 10.0.16298.1 and PowerShell v6.0.0-beta.4

**Comment by fmichaleczek** [comment]
Works for me (after upgrading package) on Win 10.0.16298.1 and PowerShell v6.0.0-beta.7

**Comment by joeyaiello** [comment]
Right-click to paste or Ctrl+V?
