### ISSUE TITLE
Clone() implemented improperly for MatchString.cs?

### ISSUE THREAD

**Issue by Narvey** [PowerShell/PowerShell#3994]
It looks like the Clone functions in MatchString.cs often reference the clone when they meant to reference "this" (explicitly or implicitly). For example, https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L65 checks the newly-created object to see if it has a PreContext, when it probably should check the current object.

It looks like this mistake occurs in both Clone() functions.

Also, where is the definition of the Match class?

**Comment by lzybkr** [comment]
This seems like an obvious bug. I would consider removing the methods - `Clone` isn't well specified, and nobody could be using these methods successfully, so removing has a low chance of breaking anything.

**Comment by iSazonov** [comment]
The Clone is used in filter mode: `Select-String -Context ... | Select-String` - the second make a clone [here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs#L1684) and then clear a context to remove it from an output - can we skip the cloning and clear the context in original object (matchInfo)?

**Comment by dee-see** [comment]
I'll work on that one!

**Comment by SteveL-MSFT** [comment]
@dee-see awesome!  consider it yours!

**Comment by iSazonov** [comment]
What is right fix? Removing the public method should be approved by @powershell-committee.

**Comment by dee-see** [comment]
I don't know how the committee works, but I can start by fixing the `Clone` method and then the committee can see if we remove it?

**Comment by SteveL-MSFT** [comment]
@dee-see fixing Clone() doesn't require committee approval.  Removing Clone() would, but as @iSazonov pointed out, it appears to be in use so we should fix it rather than remove

**Comment by dee-see** [comment]
Ok will do
