### ISSUE TITLE
Update 'host-powershell' README.md when beta.3 release is done

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#3998]
The PR #3903 makes powershell core depend on the default loader of CoreCLR, so that we can make it much easier to host powershell in applications -- it will be just like hosting powershell in FullCLR applications. When beta.3 published, I need to update the README.md in https://github.com/PowerShell/PowerShell/tree/2d06c17093f8ce7805e24e83f86925275aa038f0/docs/host-powershell and add one more sample using beta.3 packages.

**Comment by iSazonov** [comment]
@daxian-dbw Should we close the Issue?

**Comment by daxian-dbw** [comment]
@iSazonov Yep 😄
