### ISSUE TITLE
PowerShell class static method has inconsistent behavior when the .ps1 file is dot sourced into multiple Runspace's

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#4001]
Root cause
------------
Here is the background information:
1. When running the same unchanged script file multiple times, the script file will not be re-parsed. Instead, the AST will be used.
1. When re-using the AST, we will reuse the same .NET type generated for a powershell class.
1. At compilation time, [`ScriptBlockMemberMethodWrapper.InitAtRuntime`](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/runtime/Operations/ClassOps.cs#L115) will be called to bound the static method of a powershell class to the [Runspace, SessionState] where the compilation is happening.

This causes a problem -- a static method of powershell class will always execute in the [Runspace, SessionState] where the script file that defines it lastly run.

Steps to reproduce
------------------
> class.ps1 -- defines a powershell class `Foo`

```powershell

class Foo
{
    static [string] GetName()
    {
        return (Get-Name)
    }
}
```
> test.ps1
Dot source `class.ps1`, create function `Get-Name` and run `[Foo]::GetName()`.
Then create a new runspace, define another `Get-Name` and dot source `class.ps1` in that runspace.
Then run `[Foo]::GetName()` again.

```powershell

. $PSScriptRoot\class.ps1

function Get-Name
{
    "Console Runspace"
}

[Foo]::GetName()

$ps = [powershell]::Create()
$ps.AddScript("function Get-Name { 'powershell instance Runspace' }").Invoke()
$ps.Commands.Clear()
$ps.AddScript(". $PSScriptRoot\class.ps1").Invoke()

[Foo]::GetName()
```
> Then just run `test.ps1` in powershell

```powershell
.\test.ps1
```

Expected behavior
-----------------
> Since I'm running both `[Foo]::GetName()` in the default console runspace, I expect the same result.

```none
Console Runspace
Console Runspace
```

Actual behavior
---------------

```none
Console Runspace
powershell instance Runspace
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
CLRVersion
GitCommitId                    v6.0.0-beta.2-22-g7a51b446e5cc428efd634e8a8a38271156cc182b
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
I had a conversation with @BrucePay about this issue. 

Currently both instance methods and static methods of a PowerShell class are bound to a [Runspace, SessionState] by default, and the execution of the methods will happen in that environment.

This makes PowerShell class not friendly to concurrent execution in PowerShell (via RunspacePool or multiple Runspaces), because if when calls to the methods are not in the bound [Runspace, SessionState], they will be sent there to run instead of running in the current Runspace.

Maybe a better semantics is:
When calling instance/static methods, if the current thread that makes the call has a default Runspace associated with it, then the methods runs in that Runspace; if the current thread doesn't have a default Runspace associated with it, then the bound [Runspace, SessionState] will be used to run the methods.

**Comment by lzybkr** [comment]
I think it's worth revisiting how we bind script blocks to session state.

In my mind, the current implementation is meant to simulate early binding primarily for script blocks in module scope. I'm not sure the current implementation is useful elsewhere.

I'd also like to avoid semantics that apply to class methods because the problem is broader than that. For example, invoking a script block in a background runspace doesn't always work like people expect.

**Comment by PaulHigin** [comment]
While experimenting with this I found a related bug where the engine event mechanism used to marshal a script block back to the original runspace/session state doesn't work.  The result is running the script block on a different runspace/thread and corrupted state errors ("index out of range", "global scope cannot be removed", etc.).
https://github.com/PowerShell/PowerShell/issues/4003
