### ISSUE TITLE
Update README.md of the powershell repo to let people know they need to install  v1.11.0-beta4 of C# extension to work with the latest .NET Core 2.0-preview2 packages

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#4004]
Update README.md of the powershell repo to let people know they need to install  v1.11.0-beta4 of C# extension to work with the latest .NET Core 2.0-preview2 packages

**Comment by iSazonov** [comment]
OmniSharp was fixed https://github.com/OmniSharp/omnisharp-vscode/issues/1495 - Beta4 contains the fix.

**Comment by daxian-dbw** [comment]
Yes, but they will not make a public release of v1.11.0 for a while, see https://github.com/OmniSharp/omnisharp-vscode/issues/1495#issuecomment-307863132
So we need to let people know they need to manually install v1.11.0-beta4 release of C# extension on OSX and Linux.
