### ISSUE TITLE
/usr/bin/sort: invalid option -- 'P' Try '/usr/bin/sort --help' for more information.

### ISSUE THREAD

**Issue by dalmat89** [PowerShell/PowerShell#4005]
Powershell 6 beta 2 Ubuntu 16.04 LTS,  the script exit with the following error :

/usr/bin/sort: invalid option -- 'P' Try '/usr/bin/sort --help' for more information.

Powershell code :

$shares = $shares.GetEnumerator() | where {( $_.value -ne $null ) -and ($_.value -ne "0") } | sort -Property value -Descending | select -first 5

**Comment by iSazonov** [comment]
@dalmat89 Thanks for you report!

Currently "sort" alias for Sort-Object cmdlet is only enabled in Windows PowerShell and in PowerShell Core on Windows - we removed the alias in Unix because of conflict with native command `/usr/bin/sort`.

**Comment by dalmat89** [comment]
Great ! thanks so much for your quick reply

**Comment by iSazonov** [comment]
You can find the supportability matrix here https://github.com/PowerShell/PowerShell/blob/master/test/powershell/engine/DefaultCommands.Tests.ps1#L12
