### ISSUE TITLE
Stress tests needed

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4008]
- [ ] Publish RFC for stress plan
- [ ] Code coverage targets for stress tests
- [ ] Reuse existing Pester tests
- [ ] May need targeted tests for concurrency (runspaces)

**Comment by anmenaga** [comment]
Ran old stress tests that were used for WindowsPS; results on PSCore were much better than what they used to be on WindowsPS.
Moving this to 6.1
