### ISSUE TITLE
Add dotnet version check to build.psm1 module

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#4018]
Currently it is not obvious when PowerShell takes a dependency on a new version of dotnet, which can cause the build to fail.  It would be great if Start-PSBuild would check dotnet existing and required versions and provide a notification when the existing version is out of date.  The notification can tell the user how to update:
a) Remove the old dotnet version
b) Run Install-Dotnet or Start-PSBootstrap

**Comment by iSazonov** [comment]
Ah, I fought it for a few hours yesterday, and today we rolled over to the previous CoreFX version. 😄 
+1
