### ISSUE TITLE
Powershell doesn't support F11

### ISSUE THREAD

**Issue by sochka** [PowerShell/PowerShell#4028]
Powershell doesn't support F11 for full-screen, supports only Alt+Enter. Cmd.exe supports both F11 and Alt+Enter. 

Steps to reproduce
------------------

```powershell
Press f11
```

Expected behavior
-----------------

```none
Console goes fullscreen
```

Actual behavior
---------------
```none
Nothing happens
```

**Comment by SteveL-MSFT** [comment]
It appears that PSReadline is intercepting F11.  If you `rmo psreadline`, F11 will switch between full screen mode.

**Comment by lzybkr** [comment]
Duplicate of https://github.com/lzybkr/PSReadLine/issues/280

**Comment by mklement0** [comment]
For a workaround, see https://github.com/lzybkr/PSReadLine/issues/280#issuecomment-441338880.
