### ISSUE TITLE
Enable-PSRemoting doesn't enable LocalAccountTokenFilterPolicy if WinRM Firewall rule is enabled

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4033]
https://github.com/PowerShell/PowerShell/blob/7a55bf98b2370ab4817ab2533cb67673053ee446/src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs#L4045

Checks if WinRMQuickConfig (winrm qc) is needed to be run to enable PowerShell remoting.  It checks if WinRM service is running, startup mode is automatic, listener created, and if the WinRM firewall rule is enabled, but doesn't check if LocalAccountTokenFilterPolicy is enabled.  This causes an issue on WS2016 where WinRM is enabled by default so Enable-PSRemoting doesn't set the LocalAccountTokenFilterPolicy registry setting compared to WS2012R2.

Reported by customer

**Comment by iSazonov** [comment]
Related article https://support.microsoft.com/en-us/help/951016/description-of-user-account-control-and-remote-restrictions-in-windows

@SteveL-MSFT Should we fix this before 7.0 release? It looks simple.

**Comment by SteveL-MSFT** [comment]
@iSazonov should be simple fix

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PowerShell/pull/10245#discussion_r314572920
