### ISSUE TITLE
New syntax: Enable splatting for class instantiations and method calls

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShell#4038]
This feedback was well-received a couple years ago, with 23 upvotes on Microsoft Connect, but hasn't been implemented yet. Basically, it would be really cool to be able to call a class constructor and "splat" the input parameters, and invoke static & instance methods the same way.

https://connect.microsoft.com/PowerShell/feedback/details/1376904/splatting-for-class-method-input-parameters

```powershell
class Person {
    [string] $FirstName;
    [string] $LastName;

    Person ([string] $First, [string] $Last) {
        $this.FirstName = $First;
        $this.LastName = $Last;
    }
}

$NewPerson = @{
    FirstName = 'Trevor';
    LastName = 'Sullivan';
    };
[Person]::new(@NewPerson);
```

Cheers,
Trevor Sullivan
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by lzybkr** [comment]
This is discussed in the generalized splatting RFC, see [here](https://github.com/PowerShell/PowerShell-RFC/blob/master/1-Draft/RFC0002-Generalized-Splatting.md#splatting-in-method-invocations).

**Comment by pcgeek86** [comment]
[RFC comments reference](https://github.com/PowerShell/PowerShell-RFC/issues/6)
