### ISSUE TITLE
Segmentation fault on Debian 9

### ISSUE THREAD

**Issue by dasbaumwolltier** [PowerShell/PowerShell#4055]
Steps to reproduce
------------------

```none
Start powershell and wait for a while.
```

Expected behavior
-----------------

```none
Powershell should not terminate
```

Actual behavior
---------------

```none
Powershell terminates with a "segmentation fault"
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.2
OS                             Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This is actually only true for the Debian package version and the Ubuntu Repo version. AppImage version works just fine. I don't know if this is a compatibility issue, because I use Debian 9 to try it. I just thought someone might be interested.

**Comment by SteveL-MSFT** [comment]
unfortunately coreFx doesn't support Debian9 yet

**Comment by chuanjiao10** [comment]
@janvorli  say:we are already compatible with debian 9.

**Comment by janvorli** [comment]
CoreFX in .NET 2.0.0 Preview 2 does support Debian 9. It was enabled on April 28:
https://github.com/dotnet/corefx/pull/19070
You can check if you have a version that supports that by locating the System.Security.Cryptography.Native.OpenSsl.so and running:
`strings System.Security.Cryptography.Native.OpenSsl.so | grep "libssl.so"`
It should dump
```
libssl.so.1.0.0
libssl.so.10
libssl.so.1.0.2
```
If it dumps just the first two lines, it is an older version that doesn't have the support yet.

**Comment by SteveL-MSFT** [comment]
@janvorli good to know, I was only looking at the front page of the corefx repo and it only lists Debian 8

**Comment by dasbaumwolltier** [comment]
Thanks for the answer
