### ISSUE TITLE
Work towards supporting POSIX character classes?

### ISSUE THREAD

**Issue by Liturgist** [PowerShell/PowerShell#4057]
Is there any work going to support POSIX character classes in PowerShell regex processing?

**Comment by SteveL-MSFT** [comment]
PowerShell regex processing simply depends on dotnet regex processing.  If you have any specific requests, you should probably open it on their repo https://github.com/dotnet/corefx and we would get it "for free"

**Comment by Liturgist** [comment]
Thanks, Steve. Will do.
