### ISSUE TITLE
Make it easier to do integer arithmetic with overflow

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#4063]
This is something that I've come across at quite a few occasions now. Most recently, it was when writing a `GetHashCode` implementation. But also when writing tools for developers/myself I have wanted to do integer arithmetic with overflow/wrapping.
The only reasonable way I've found was to write it in C# and use `add-type` to access it, but that cannot be our recommendation in the long term.

I can see this being done in two ways.

1. By far the simplest: provide class in System.Management.Automation that provides us with this functionality, as part of the Module Writers Toolbox™.

2. Second, and with much higher effort/expertise involved, is to provide language support for it. I don't have any concrete suggestion for syntax yet.

This has come up often enough that I thought it was worth an issue.

**Comment by SteveL-MSFT** [comment]
cc @PowerShell/area-language
