### ISSUE TITLE
PowerShell Beta - the ESC key doesn't clear in Linux 

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4067]
In Linux, the ESC kay is not clearing the current line. This works in Windows!

## Steps to reproduce
------------------
1. Type any cmdlet in PowerShell console prompt but don't press TAB nor Enter Key:
```powershell
PS /home/maxt> $PSVers
```
2.  Press the ESC key to cleared the line.

## Expected behavior
-----------------
To clear the line you are currently On.
```none
PS /home/maxt> $PSVers   ## - Press ESC key.
PS /home/maxt>  ## Current line is blank.
```

## Actual behavior
---------------
Doesn't  do anything!

## Environment data
----------------
Ubuntu:  16.04.01

```powershell
PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.2
OS                             Linux 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by lzybkr** [comment]
This is by design - on LInux, PSReadline defaults to Emacs mode.
If you want Windows mode, you can put this in your profile:
```powershell
Set-PSReadlineOption -EditMode Windows
```

**Comment by MaximoTrinidad** [comment]
Awesome!! Thanks @lzybkr.
:)

**Comment by chuanjiao10** [comment]
Make it the default value better
