### ISSUE TITLE
Suggestion: allow specifying switch parameter values numerically too (0 or 1) 

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4069]
Typically, the logic of `[switch]` parameter is _implicit_: merely _using_ the switch parameter (e.g., `-Foo`) implies a value `$True`, whereas _omitting it_ implies `$False`.

However, `[switch]` parameters also allow passing an _explicit value_, such as `-Foo:$True` and  
`-Foo:$False`.

_Conceptually_, switches are _Boolean_ values, so it's a reasonable expectation that `-Foo:1` and `-Foo:0` would work too, but that currently isn't true:

```powershell
> function Foo { param( [Parameter(Mandatory)] [switch] $Bar) $Bar }; Foo -Bar:0
Foo : Cannot process argument transformation on parameter 'Bar'.
Cannot convert the "0" value of type "System.Int32" to type "System.Management.Automation.SwitchParameter".
```

By contrast, a `[bool]` parameter _does_ support numerical values:
```powershell
> function Foo { param( [Parameter(Mandatory)] [bool] $Bar) $Bar }; Foo -Bar 0
False  # OK - 0 was coerced to $False
```
It would be handy to support numerical values too, especially in the context of _external_ invocations on Unix platforms, where avoiding `$`-prefixed tokens such as `$False` is desirable, so as to prevent accidental up-front expansion of such tokens by POSIX-like shells.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.2
```

**Comment by iSazonov** [comment]
It looks like implicit converting 0 and 1 to bool but it seems lead to big confusion in PowerShell language.

**Comment by mklement0** [comment]
@iSazonov: Can you say more? What difference do you see between allowing `0` and `1` to be converted to `[bool]` vs. to `[switch]`?

**Comment by iSazonov** [comment]
I have a question too :-)  Do you want to fix?
```powershell
PS >[System.Management.Automation.SwitchParameter]0
Cannot convert the "0" value of type "System.Int32" to type "System.Management.Automation.SwitchParameter".
At line:1 char:1
+ [System.Management.Automation.SwitchParameter]0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException
```

**Comment by mklement0** [comment]
That something like `[switch] 0` doesn't work was the starting point, so I'm unsure what you're trying to say. 

That you _personally_ don't want to take the time to implement it? 

Earlier it sounded like you thought that it shouldn't be implemented ("big confusion"), and I still don't know why.

**Comment by iSazonov** [comment]
My first glance was too general: int -> bool.

And if the Issue is only to fix ">[System.Management.Automation.SwitchParameter]0" - I agree.

**Comment by BrucePay** [comment]
The current behavior is very much by design. The only intended scenario for providing literal values to switch parameters is commands calling commands. Only allowing boolean values is intended to discourage other uses. Switch parameters and boolean parameters should not be conflated.

**Comment by mklement0** [comment]
I get that it's the right decision to be restrictive when it comes to binding Booleans that should be specified as such (as opposed to, say, `[bool] 'foo'`).

However, the difference between a `[bool]` parameter and `[switch]` parameters is _in syntax only_.
What is a `[switch]` other than a Boolean value with implicit syntax?

In fact, [_the code already treats them the same in the context of parameter binding_](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/ArgumentTypeConverterAttribute.cs#L114), and it is _only the lack of methods for converting from _numbers_  _on  the `[switch]` class itself_ that results in different behavior_.

That this is more of an _accident_ is also reflected in the fact that, unlike with `[bool]`-typed parameters, there is no specific error message for `[switch]` when you use _numeric_ arguments:

```powershell
# With [bool]: specific, helpful error message:
> & { param([bool] $b) $b } 'foo'
Cannot process argument transformation on parameter 'b'. Cannot convert value "System.String" to type "System.Boolean". Boolean parameters accept only 
Boolean values and numbers, such as $True, $False, 1 or 0.

# With [switch] and a *NON-numeric* value: same helpful message
> & { param([switch] $sw) $sw } -sw:foo
Cannot process argument transformation on parameter 'sw'. Cannot convert value "System.String" to type "System.Management.Automation.SwitchParameter". 
Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.

# With [switch] and a *numeric* value:
# *Generic error message* that results from the initial inability to coerce a number
> & { param([switch] $sw) $sw } -sw:1
Cannot process argument transformation on parameter 'sw'. Cannot convert the "1" value of type "System.Int32" to type

```

From that vantage point I see no reason why the permissible values should differ, especially given that `[bool]`-typed parameters seems to strike the right balance between restrictiveness that signals intent on the one hand, and allowing sensible variations on the other: `$true`, `$false`, `0`, `1`.

As an aside: Arguably, the fact that `[bool]`-typed parameters more generally accept _any number_ of _any numeric type_ is too lax, however.

As stated, aside from _consistency_, the _upside_ of also allowing `-switch:0` and `-switch:1`  is to facilitate calls from POSIX-like shells.

**Comment by SteveL-MSFT** [comment]
cc @PowerShell/area-language

**Comment by iSazonov** [comment]
> As an aside: Arguably, the fact that  [bool] -typed parameters more generally accept any number of any numeric type is too lax, however.

It seems we can accept this (accept any number) because it works such in other places.

**Comment by mklement0** [comment]
@iSazonov: 

In case you're referring to `[bool]` _casts_  (e.g., `[bool] 'anything goes'`) / _coercion_ (e.g., `if (Get-Date) ... `): these cases are intentionally treated very differently: by design, _anything_ can be converted to a Boolean there.
