### ISSUE TITLE
VSCode PS Extension 1.4.0 OS X issue

### ISSUE THREAD

**Issue by steviecoaster** [PowerShell/PowerShell#4073]
I get this error when opening any type of ps1 file or when changing the editor to Powershell on a new untitled file:

An error occurred while starting PowerShell Editor Services:

The specified module 'PowerShellEditorServices' with version '1.4.0' was not loaded because no valid module file was found
in any module directory.

This just started happening after my powershell module updated when I launched VSCode on my Mac. I've only found the following log information:

[20:14:0] Language server starting...
powershell.exe started --
    pid: 60901
    exe: /usr/local/bin/powershell
    args: /Users/redacted/.vscode/extensions/ms-vscode.powershell-1.4.0/scripts/Start-EditorServices.ps1 -EditorServicesVersion '1.4.0' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.4.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/Users/redacted/.vscode/extensions/ms-vscode.powershell-1.4.0/modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath '/Users/redacted/.vscode/extensions/ms-vscode.powershell-1.4.0/logs/1498090440-a86f0207-d364-42b8-981d-3e9813a2056f1498090327621/EditorServices.log' -SessionDetailsPath '/Users/redacted/.vscode/extensions/ms-vscode.powershell-1.4.0/sessions/PSES-VSCode-60620-290843' -FeatureFlags @()

[20:15:0] Language server startup failed.
The language service could not be started: 
Timed out waiting for session file to appear.
_powershell.exe terminated or terminal UI was closed
The terminal process terminated with exit code: 1_

Also, I was in VSCode literally all day on my Windows machine, and didn't have any issues at all. Noticing it only on my MacBook Pro while doing some work from home this evening.

**Comment by vors** [comment]
https://github.com/PowerShell/vscode-powershell is a better place for this issue
