### ISSUE TITLE
FileSystem Provider incorrectly assumes if a directory has a reparse point it has a mount point

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4077]
User impact is that they can't delete a directory using PowerShell on a virtualized filesystem (like [GVFS](https://github.com/Microsoft/gvfs)).  Issue is in [RemoveDirectoryInfoItem](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L2906)

TFS:12023495

**Comment by NickVH-MS** [comment]
It would be great to see this fixed. In 2021 people shouldn't be needing to switch over to CMD because powershell doesn't "do it properly".

**Comment by iSazonov** [comment]
I can able to remove `src` (detected as link) in cloned directory by `Remove-Item src -Recurse -Force` on latest 7.2 daily build.
