### ISSUE TITLE
'Web cmdlets tests using the cmdlet's aliases' tests are unreliable.

### ISSUE THREAD

**Issue by dantraMSFT** [PowerShell/PowerShell#4081]
There are two tests that fail randomly:

1: Execute Invoke-WebRequest --> 'iwr -URI www.bing.com?q=how+many+feet+in+a+mile'
2: Execute Invoke-RestMethod --> 'irm -URI www.bing.com?q=how+many+feet+in+a+mile'

Since these tests are only verifying the existing of the aliases, the HTTPListener should be used instead.
Alternatively, rewrite the tests to verify the alias's values.

Note that this is similar to https://github.com/PowerShell/PowerShell/issues/2504 where tests dependent on httpbin.org fail randomly.

Steps to reproduce
------------------
run the CI tests on a slower system.

Expected behavior
-----------------
All tests pass.

Actual behavior
---------------
The two tests in this suite  randomly fail.

Environment data
----------------

PSVersion                      6.0.0-beta
PSEdition                      Core
CLRVersion
GitCommitId                    v6.0.0-beta.2-56-g25260caaca1a2028c582b9bfd7c9e9c27c1a050e-dirty
OS                             Microsoft Windows 10.0.16225
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by SteveL-MSFT** [comment]
I generalized #2504 as whomever fixes that should look at all external site dependencies
