### ISSUE TITLE
Have a light weight PowerShell client that can be used to manage remote endpoints

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4096]
We should be able to have a lightweight client library/host that is solely for managing remote PowerShell endpoints.  This means that the parser, etc... is not on the client.

**Comment by iSazonov** [comment]
We could start with two separated clients - 1. PSRS 2. SSH

If I understand right we need simple console app to setup remote session and run remote PowerShell process.

**Comment by SteveL-MSFT** [comment]
The client should understand both WSMan and SSH PSRP.  Pure SSH should be existing solutions.  For a library, I wonder if it's better to just enable a basic REST endpoint to execute PowerShell and get back JSON which means many existing languages can easily work with PowerShell remotely or if there is a real need for apps to talk PSRP.

**Comment by iSazonov** [comment]
@markekraus Have you thoughts about PowerShell REST endpoint?

**Comment by markekraus** [comment]
Kind of...  

* The API should be swagger defined
* Some or all "core" cmdlets should be exposed as endpoints that accept parameters as queries
  `/api/v1.0/Cmdlets/Get-Process?Name=pwsh` == `Get-Process -Name pwsh`
* The same endpoint without a cmdlet should list available cmdlets
  `/api/v1.0/Cmdlets/` lists available cmdlets and parameters
* the cmdlet endpoints should accept a json object body that contains a object with a `Parameters` property that is an array of objects containing paramters to execute..
   `/api/v1.0/Cmdlets/Get-Process` accepts the body `{"Parameters":[{"Name":"pwsh"},{"Id":1234}]}` and executes `Get-Process -Name pwsh; Get-Process -d 12345`
* There should be and endpoint that takes general cmds
  `/api/v1.0/Command` takes a body with something like `{"Commands":["$ProcessName = \"pwsh\"","Get-Process -Name $ProcessName"]}` which executes `$ProcessName = "pwsh"; Get-Process -Name $ProcessName`
* Results should some what mimic jobs where the output streams are sepertaed. 
* There should be a modules endpoint which lists the available modules and any exposed endpoints
* modules endpoint should possibly be allowed to install and uninstall modules 
* Piping objects should be done though a JSON body.. not really sure on this one.. might only work on `ValueFromPipelineByPropertyName`?? *shrugs
* and `$SessionId` query should be available on all endpoints to identify a PowerShell session the cmds are run in and response header should include session expiry date. Variables and such should persist in that session until expiry, expiry clock resets after every execution, session expiry time is configurable, session should be tied current auth, a single auth can have multiple session, thus requiring a session edpoint to reqeust manage sessions.... API calls with out `$SessionID` could either run in a one off session or against a default session...


Its fair to say I have given this some thought before....

**Comment by iSazonov** [comment]
@markekraus 😄 I only ask your opinion not full specifications. Thanks for great comment. I think it is better to move this in new Issue.
@SteveL-MSFT Perhaps it makes sense to ask MSFT product teams to give feedback about PowerShell REST endpoint. I know Exchange Server team is actively using PowerShell over HTTPS (EMS).

**Comment by SteveL-MSFT** [comment]
@markekraus perhaps you can author an RFC :)

**Comment by Jaykul** [comment]
### I, for one, **definitely** don't want a REST endpoint. 

I already have PowerShell remoting and constrained endpoints, etc. I don't need a replacement **server** product -- I need client libraries to call the PowerShell remoting endpoints I already have.

For what it's worth, we have web apps that currently make PowerShell remoting calls, and as we're moving things to ASP.NET Core, we still need to be able to do PowerShell remoting (including from containers). I just don't want (to need) to ship a whole copy of all of PowerShell's dependencies for that...

**Comment by SteveL-MSFT** [comment]
The REST discussion deviated from the original topic (yes, I did that!).  Let's focus discussion of this issue on a client library to remotely manage existing PowerShell endpoints.

**Comment by it-praktyk** [comment]
@nitzmahone, @jborean93, is it something that can be used by Ansible to manage Windows?

**Comment by jborean93** [comment]
@it-praktyk from the original topic probably not. We use our own Python client(s) and talk to the server. Having a REST endpoint is interesting but we currently don't have any plans on officially supporting PSCore in the short term which is what will be affected by this.

**Comment by Jaykul** [comment]
@jborean93 well, the client library would be .NET Core, but it would be able to talk to either Windows PowerShell or PowerShell Core endpoints. It would basically be a .NET version of the Python client ;)

**Comment by jborean93** [comment]
@Jaykul agreed, technically on the Windows side you have `winrs` which allows you to run commands over WinRM outside of PSRP but that's Windows specific.

**Comment by kilasuit** [comment]
this is also linked to #5681
