### ISSUE TITLE
Add parameter to `Sort-Object` to implement `SORT_STRINGSORT ` flag or `ASCII` sorting.

### ISSUE THREAD

**Issue by JohnLBevan** [PowerShell/PowerShell#4098]
The current implementation of `Sort-Object` appears to use a [word sort](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318144(v=vs.85).aspx) when sorting strings.  For many scenarios, this is confusing / inappropriate behaviour.   

Suggested improvement: Add a parameter to define the sorting method.

```
    [Parameter()]
    [ValidateSet('WordSort','StringSort','CharCodeSort')]
    [string]$ComparisonPreference = 'WordSort'
```

* WordSort - the current behaviour
* StringSort - enables the `SORT_STRINGSORT` flag; i.e. hyphens and apostrophes are treated  the same as all other punctuation.
* CharCodeSort - sorts strings by its characters' byte code - e.g. in a case-sensitive sort, `^` would appear between `Z` and `a`.  In a case insensitive sort characters would be treated as lower case (users can always put strings to upper case before calling sort if the reverse is required).

Alternatively, allow users to provide a `StringComparer` (or better yet, an `IComparer`) for each property being sorted.  This could be implemented by allowing a `Comparer` key on the `Property` parameter's [hash table.](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/sort-object?f=255&MSPPError=-2147217396#-property); thus giving the full array of options.

Originated from a question on StackOverflow: https://stackoverflow.com/questions/44731470/powershell-sorting-string-objects-with-a-special-character/44732124#44732124

**Comment by iSazonov** [comment]
@JohnLBevan Thanks for your report!

It is duplicate #3425. Please continue discussion there.

**Comment by JohnLBevan** [comment]
Apologies; didn't spot that.  Thank-you for reviewing / closing.
