### ISSUE TITLE
Out-GridView (and ISE?) should ... handle ... ANSI escape sequences.

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell#4101]
For the sake of argument, I don't really care if it handles it by _stripping escape sequences_ or by processing color ... but it needs to not show the text of the escape sequence.

Use case: we can now put ANSI sequences in format files to, for instance, color files by extension -- but the result is that Out-GridView shows things like this:

```
Mode  	LastWriteTime     	Length	Name
-a----	8/20/2016 1:12:42 AM	5654	[37m.poshhistory[39m	
-a----	4/12/2017 7:04:21 PM	6	[36mdata.csv[39m	
-a----	1/22/2017 4:09:13 PM	1760	[36mDefaultParameterValues.clixml[39m	
-a----	4/12/2017 7:03:51 PM	6	[93mMyModule.psm1[39m	
```

**Comment by SteveL-MSFT** [comment]
There are no plans to update out-gridview as it only ships with Windows PowerShell and the dependency on WPF means it's not cross platform.  The issue is unfortunate but isn't critical enough to fix in 5.x

**Comment by MaximoTrinidad** [comment]
Hi @Jaykul,

You'll need to open this issues in Windows PowerShell Uservoice:
https://windowsserver.uservoice.com/forums/301869-powershell/

:)

**Comment by Jaykul** [comment]
No @MaximoTrinidad you misunderstand: **_Windows_ PowerShell is finished**.

If they won't take it as a feature request here, they won't take it anywhere.

Basically, if you read between the lines of that @SteveL-MSFT wrote: don't bother filing bugs or suggestions that only affect Windows PowerShell, unless they are show stoppers (which is going to be a very hard mark to meet at this point, considering). 

Features need to _also_ apply to PowerShell Core to get worked on.

**Comment by MaximoTrinidad** [comment]
Hi Jakul!   Thanks for clarifying!
:)
