### ISSUE TITLE
Support for parameter set selection by parameter value.

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#4102]
A common pattern with native binaries is to have a first parameter indicating some general command, and the rest of the commandline is options to that first command.
Like 
```
p4 opened ...
git commit -a --amend 

#pattern
exe command flag1 option2=1
```

Today, this is something that I find cumbersome to express in PowerShell, since the allowed verbs are often a mismatch with the `command`, and we have no nice way to match parameter sets with the value of a parameter. (It can be done with dynamic parameters, but that quickly becomes unwieldy and seems like an abuse of the feature).

I'd like to start a discussion to see if we can come up with a better way.

An initial suggestion is to allow an `enum`  or `string` parameter at the first position with a Parameter flag (here: ParameterSetSelector)be the selector of the parameter set.

```
enum SubCommandTypes {
    SomeSubCommand
   AnotherSubCommand
}

function Start-MainCommand {
    param(
        [Parameter(ParameterSetSelector=$true, Mandatory=$true)]
        [SubCommandTypes ] $Command
        ,
        [Parmameter(ParametersetName="SomeSubCommand")]
        [int] $Count
        ,
        [Parmameter(ParametersetName="AnotherSubCommand")]
        [int] $Size
    )
}
# or 
function Start-MainCommand {
    param(
        [Parameter(ParameterSetSelector=$true, Mandatory=$true)]
        [ValidateSet("SomeSubCommand", "AnotherSubCommand")]
        [string] $Command
        ,
        [Parmameter(ParametersetName="SomeSubCommand")]
        [int] $Count
        ,
        [Parmameter(ParametersetName="AnotherSubCommand")]
        [int] $Size
    )
}

```

Thoughts?

**Comment by iSazonov** [comment]
@powercode Thanks for opening the discussion! I've waited a long time for this.

I think we should start with trying to formalize the description (notation, terms).

```
statement := command [parameterset]

parameterset := parametersetParameterList

parametersetParameterList := parametersetParameter parametersetParameterList

parametersetParameter  := Parameter [SubParameterlist]

SubParameterlist := parametersetParameterList 

Parameter := valueParameter | Switch

```

**Comment by SteveL-MSFT** [comment]
cc @PowerShell/area-language

**Comment by ohadschn** [comment]
I would take this a step further and suggest that the value of the property could be inspected as well. Something like:
```ps
[Parameter(ParameterSetSelector="MyParamSetName", ConditionalValue=$true)]
        [Switch] $Command
```

This way you would support `Start-MainCommand -Command:$myFlag`, otherwise you would resolve the wrong set for `Start-MainCommand -Command:$false`.

**Comment by powercode** [comment]
What would the effect be of having a callback to user code to determine parameter set?

We have a few different scenarios that PowerShell doesn't handle well, and this could potentially open up for handling the more difficult cases.

I'm thinking in the way of an attribute on Cmdlet, `[ParameterSetResolver(typeof(MyResolver))]`.
