### ISSUE TITLE
JEA role capabilities cannot be discovered if placed in a versioned module folder

### ISSUE THREAD

**Issue by rpsqrd** [PowerShell/PowerShell#4105]
>Note: Ported from bug 11787772

If a PowerShell Session Configuration file references one or more role capability files in the RoleDefinitions field and those role capability files are stored in versioned module folders (e.g. `C:\Program Files\WindowsPowerShell\Modules\MyModuleName\1.0.0\RoleCapabilities\MyRole.psrc`), PowerShell will be unable to find those role capability files and may fail to establish the PSSession.

The current workaround is to move the "RoleCapabilities" folder up one level so that it is under the main module folder, not a versioned subfolder, however this is not ideal for customers downloading modules that are already set up this way from the PowerShell Gallery or other repository. Customers on Windows 10 1703 or higher can also use the "RoleCapabilityFiles" parameter in the "RoleDefinitions" hashtable to explicitly select the role capability file to load, regardless of whether it is nested in a versioned folder or not.

This issue is filed to request that JEA search versioned subfolders in modules for role capability files to maintain compatibility with the PowerShell Gallery best practices.

**Comment by briantist** [comment]
This is a very poor experience. The JEA documentation doesn't mention this at all and acts as though you just need to have a module in the path. The worst part is that there's no great workaround that's consistent. 

I'm dealing with this now, trying to come up with a solution that accounts for an updated module with new or updated role configurations and it just sucks all around; makes it practically unusable for anyone who manages their modules with an actual repository!

**Comment by doctordns** [comment]
Using a 'random' module for this is really not a great design decision (with the benefit of hindsight) 

In PowerShell 7, you just avoid using the module totally. Here is a sample that demonstrates this:

```powershell

# 1. Create Capabilities Folder
$JEACF = "C:\JEACapabilities"
New-Item -Path $JEACF -ItemType Directory | Out-Null

# 2. Create Role Capabilities file in the folder
$RCF = Join-Path -Path $JEACF -ChildPath "RKDnsAsmins.psrc"
$RCHT = @{
  Path            = $RCF
  Author          = 'Reskit Administration'
  CompanyName     = 'Reskit.Org' 
  Description     = 'Defines RKDnsAdmins role capabilities'
  AliasDefinition = @{name='gh';value='Get-Help'}
  ModulesToImport = 'Microsoft.PowerShell.Core','DnsServer'
  VisibleCmdlets  = ("Restart-Service",
                     @{ Name       = "Restart-Computer"; 
                        Parameters = @{Name = "ComputerName"}
                        ValidateSet = 'DC1, DC2'},
                      'DNSSERVER\*')
  VisibleExternalCommands = ('C:\Windows\System32\whoami.exe')
  VisibleFunctions = 'Get-HW'
  FunctionDefinitions = @{
    Name = 'Get-HW'
    Scriptblock = {'Hello JEA World'}}
}
New-PSRoleCapabilityFile @RCHT -verbose

# 3. Create a JEA Session Configuration file
$SCF = "C:\JEASessionConfiguration"  # root location
$P   = Join-Path -Path $SCF -ChildPath 'RKDnsAdmins.pssc' # get filename
$RDHT = @{
  'Reskit\RKDnsAdmins' = @{'RoleCapabilityFiles' = 'C:\JEACapabilities\RKDnsAsmins.psrc'
}
$PSCHT= @{
  Author              = 'DoctorDNS@Gmail.Com'
  Description         = 'Session Definition for RKDnsAdmins'
  SessionType         = 'RestrictedRemoteServer'   # ie JEA!
  Path                = $P       # Role Capabilties file
  RunAsVirtualAccount = $true
  TranscriptDirectory = 'C:\Foo\JeaTranscripts'
  RoleDefinitions     = $RDHT     # RKDnsAdmins role mapping
}
New-PSSessionConfigurationFile @PSCHT

# 4. Test the session configuration file
Test-PSSessionConfigurationFile -Path $P 

# 5. Enable Remoting and Register the JEA Session Definition
Enable-PSRemoting -Force 
  Out-Null
$SCHT = @{
  Path  = $P
  Name  = 'RKDnsAdmins' 
  Force =  $true 
}
Register-PSSessionConfiguration @SCHT

# 6. Check What the User Can Do
Get-PSSessionCapability -ConfigurationName RkDnsAdmins -Username 'Reskit\Jerryg' |
  Sort-Object Module

# 7. Create Credentials for user JerryG
$U    = 'JerryG@Reskit.Org'
$P    = ConvertTo-SecureString 'Pa$$w0rd' -AsPlainText -Force 
$Cred = New-Object System.Management.Automation.PSCredential $U,$P

# 8. Define Three Script Blocks and an Invocation Splatting Hast Table
$SB1   = {Get-Command}
$SB2   = {Get-HW}
$SB3   = {Get-Command -Name  '*-DNSSERVER*'}
$ICMHT = @{
  ComputerName      = 'DC1.Reskit.Org'
  Credential        = $Cred 
  ConfigurationName = 'RKDnsAdmins' 
} 

# 12. How many Commands are available within the JEA session
Invoke-Command -ScriptBlock $SB1 @ICMHT |
  Sort-Object -Property Module |
    Select-Object -First 15

# 13. Invoke a JEA Defined Function in a JEA Ssession As JerryG
Invoke-Command -ScriptBlock $SB2 @ICMHT

# 14. Get DNSServer commands available to JerryG
$C = Invoke-command -ScriptBlock $SB3 @ICMHT 
"$($C.Count) DNS commands available"

# 15 Examine the contents of the Transcripts folder:
Get-ChildItem -Path $PSCHT.TranscriptDirectory

# 16. Examine a transcript
Get-ChildItem -Path $PSCHT.TranscriptDirectory | 
  Select-Object -First 1  |
     Get-Content 
```

**Comment by briantist** [comment]
@doctordns I'm not using a "random" module. I see the value in having the option to define role capabilities outside of a module, particularly for roles that only restrict built-in cmdlets.

But I like the idea of packaging roles with modules when the roles are specific to the module's purpose and its commands. 

Putting them alongside makes sense, especially from the POV of coordination and packaging. If I add new commands to a module, up its version, and publish it, and I want a new role available to make use of them, I'd like that to come along _with_ the module.

Conversely, if I have to define it separately then 
1. there's no versioned/packaged format for the standalone directory full of unrelated roles
2. if I put the new role definition in place before the module that supports it, it won't work
3. having to change the session configuration is yet another change and applying it means restarting winrm which is disruptive.

Trying to implement JEA, which is supported on 5.1, only to find that the entire module-searching that underpins its ability to find roles, doesn't actually support the same module paths that the entire rest of Windows PowerShell uses, is a very bad experience. It's set our project back by a lot. Even if we wanted to dump all the role configurations into a random directory, it would be an entirely different project to get PowerShell 7 out to all our environments and tested with existing workflows.

I don't think that the role searching idea was problematic, it was just implemented in a way that somehow doesn't work with PowerShell's own package management, which is bonkers. I'm in awe that this has been known for years, and hasn't been fixed and backported.

**Comment by briantist** [comment]
For anyone interested, I made a script that applies the workaround @rpsqrd mentioned, but continuously, by monitoring the module directories and symlinking a `RoleCapabilities` folder in the module folder, pointing to latest version of the module:

https://github.com/briantist/jea-role-cap-hack
