### ISSUE TITLE
Start-PSPester should default to running CI and Feature tests

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4107]
We've seen a few cases where an engineer runs `start-pspester` and it passes but it breaks our nightly runs as the `Feature` tests weren't run.  We should change the default of `start-pspester` to run both CI and Feature tests and update our CI scripts to explicitly pass `-Tag CI`.

**Comment by TravisEz13** [comment]
fixed by #4273
