### ISSUE TITLE
Linux Build Script Errors out on Docker Container - No Sudo (Container Centos:Latest)

### ISSUE THREAD

**Issue by henryza** [PowerShell/PowerShell#4116]
<!--

Getting error "sudo: command not found" when running download script (/tools/download.sh) on latest Centos build on Docker due to no Sudo Escalation.

Steps to reproduce
------------------
git clone https://github.com/PowerShell/PowerShell.git
cd PowerShell
sh /tools/download.sh

ERROR : "sudo: command not found"
![image](https://user-images.githubusercontent.com/20166417/27582580-a89cd894-5b31-11e7-8a57-25dceca26d8e.png)
```

Expected behavior
-----------------

Expected : Congratulations! PowerShell is installed at /opt/microsoft/powershell/6.0.0-beta.3

```

Actual behavior
---------------

ERROR : "sudo: command not found"

```

Environment data
----------------
Docker on Windows
Docker version 17.03.1-ce, build c6d412e

PowerShell Information
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Linux 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

Resolution
------------
Removed all sudo escalations in (/tools/download.sh) and re-ran 

Suggested Solution
------------
Detect if in a docker container with something like the below?

if  [ls -a / | grep dockerenv]; then
 "Container"
else
 "Non-Container"
fi

**Comment by TravisEz13** [comment]
Please provide details.  We run our official builds in a `centos:7` container.  I'm closing the issue.  Please and fill out the issue template.
