### ISSUE TITLE
Powershell window comes to the strange position when starts from Win + X menu while Taskbar is on the top of the screen.

### ISSUE THREAD

**Issue by thelastfantasy** [PowerShell/PowerShell#4124]
<https://social.technet.microsoft.com/Forums/azure/zh-CN/acd4b8c6-4d21-4e15-8af9-522a008c1013/bugwin10-1703-powershell?forum=win10itprogeneralCN>
I find this problem is also reported in this thread 3 months ago but is still not solved.

    System: Windows 10

**Comment by MaximoTrinidad** [comment]
If this is a Windows PowerShell issue (meaning not a PowerShell Core) then it needs to be reported in Windows PowerShell UserVoice so it can be addressed correctly:
https://windowsserver.uservoice.com/forums/301869-powershell/category/148044-powershell-engine
