### ISSUE TITLE
Get-ChildItem -Include/-Exclude should support wildcards in the parent path

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#4126]
Sample to remove all `x64` subdirectories:
```powershell
    Get-ChildItem -Path ./  -Directory -Include "*x64*" -Recurse | Remove-Item -Force
```

From @mklement0:
   We want that it to work against the full path. For the leaf component it is already work.

**Comment by mklement0** [comment]
Can you be more specific? Your `Get-ChildItem` command works for me on both Windows and Unix.

(As an aside:  you misspelled `-Recurse`)

**Comment by iSazonov** [comment]
I only split discussion to discuss one branch.

**Comment by mklement0** [comment]
@iSazonov: Thanks for fixing the typo. 
I still don't understand what needs enhancing / isn't working (except that _without `-Recurse`_, the behavior is surprising - see #3304).

**Comment by mklement0** [comment]
@iSazonov: Thanks for fixing the typo.

It is only after looking at the linked issue that I understood what this is about:

You want the wildcard to be matched _against the full path_ vs. _just the leaf component_ (which is how it currently works), correct? If so, could you please make that clear in the initial post?

**Comment by raghav710** [comment]
@iSazonov is this already being implemented or can I give it a try?

**Comment by iSazonov** [comment]
@raghav710 Feel free to grab!

**Comment by raghav710** [comment]
@iSazonov could you help me get started? I was searching the GetChildrenCommand.cs and FileSystemProvider.cs but couldnt find the exact location to make the changes. Thanks!

**Comment by iSazonov** [comment]
@raghav710 I'd start with https://github.com/Windos/PowerShell/blob/a464c578a2d96da7e23df7597670fe8780c89c84/src/System.Management.Automation/engine/SessionStateContainer.cs

**Comment by raghav710** [comment]
@iSazonov I havent spent time on this. If there is any deadline for this feature, let me know so I can fastrack it if required (or someone who has time can take this up). Thanks! :)
