### ISSUE TITLE
Suggestion: extend the -? parameter syntax to ask for more detailed help on demand, as a Get-Help shortcut

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4137]
Using `<cmdletOrFunction> -?` is the equivalent of `Get-Help <cmdletOrFunction>`.

In order to get the `-Detailed` or `-Full` levels, you need to switch from `-?` to an entirely different command line based on `Get-Help`, which is inconvenient.

The following would ease the pain of that transition:

* `-??` could be the equivalent of `Get-Help -Detailed`

* `-???` could be the equivalent of `Get-Help -Full`

Written as of: PowerShell Core v6.0.0-beta.3

**Comment by SteveL-MSFT** [comment]
This is one of those things that has bothered me, but I guess I learned to live with it.  Alternatively we could use the syntax:

-? Detailed
-? Full
-? Examples
