### ISSUE TITLE
$?=$null crashes powershell

### ISSUE THREAD

**Issue by Stugr** [PowerShell/PowerShell#4140]
Steps to reproduce
------------------

```powershell
$?=$null
```
Expected behavior
---------------
Do nothing

Actual behavior
---------------
Powershell crashes with "powershell has stopped working"

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.0
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by mklement0** [comment]
That is indeed problematic, but it only affects _Windows PowerShell_, so you should report it at [uservoice.com](https://windowsserver.uservoice.com/forums/301869-powershell).

_PowerShell Core_, by contrast - on all platforms - handles this more gracefully

```powershell
> $?=$null
Cannot overwrite variable ? because it is read-only or constant.
...
```

**Comment by lw-schick** [comment]
I can't reproduce the error on Windows 7 64x

![image](https://user-images.githubusercontent.com/19262181/27674315-6cefe4ec-5ca5-11e7-98c3-e03fba8fb4bc.png)

**Comment by MaximoTrinidad** [comment]
Nice finding!!  It crashed on my Windows 10 latest build 16226 on Windows PowerShell and not on PowerShell Core Beta 3.  

Although, I don't know the practical use of such statement but can definitely crash Windows PowerShell.

**Comment by mklement0** [comment]
@lw-schick: Your version is too old - the bug was apparently introduced later (it is present as of at least `5.1.14394.1000`), but, as noted, PowerShell _Core_ is not affected (as of beta 3).

**Comment by chuanjiao10** [comment]
$?=1
powershell windows close  , like   exit  command .
5.1.14393.1358

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/2243
