### ISSUE TITLE
PowerShell scrolling buffer in PSReadline incorrectly over SSH

### ISSUE THREAD

**Issue by marekr** [PowerShell/PowerShell#4141]
@iSazonov @lzybkr

As a followup to #4075

The next issue while remote use of Powershell seems to be calculating the wrong locations to move cursors on wrap around:

I recorded a video showing split console with one showing the visual usage of powershell and the other one of a log file dumped 

https://www.youtube.com/watch?v=_2LBAzFDsCk

You can see: when I execute a command that would exceed the current screen, it fails to scroll and "wraps". Once its wrapped, it begins to start jumping the cursor around. In fact, hitting Enter on empty line stops creating blank prompts altogether.

The log file was a quick hack in `WriteBufferLines`
```
            System.IO.File.AppendAllText(@"/home/mroszko/pstest/PowerShell/test.log", String.Format("top:{0},blc:{1},$
            if ((top + bufferLineCount) > Console.BufferHeight)
            {
                var scrollCount = (top + bufferLineCount) - Console.BufferHeight;
                ScrollBuffer(scrollCount);
                top -= scrollCount;

                System.IO.File.AppendAllText(@"/home/mroszko/pstest/PowerShell/test.log", String.Format("scrolling:{0$
            }
```

I started the video by executing "clear" before 

You can see the strange wrap around it does in the video with top as I type in the log output and visually. 

I don't think the  ScrollBuffer() is quite implemented correct.

**Comment by SteveL-MSFT** [comment]
@marekr can you try latest PSReadLine 2.0.0-beta2?  Just tried ssh on macBook and it renders fine.  Include more specific repro steps if this is still an issue.  Thanks.

**Comment by MaximoTrinidad** [comment]
Repo steps should always be included:

1. Open MacOs terminal session
2. Create a remote connection using Enter-PSSession
3. Then, set terminal session to full-screen.
4. Use "dir"command to populate the screen with list of files.

At this point the issue shows when the cursor jumps to the middle of the screen.
This is with PSReadline version 1.2

![pwsh_cursorjump_2018-06-05_7-47-58](https://user-images.githubusercontent.com/19892435/40975214-3183ca86-6898-11e8-82b1-e38c156d1eb2.jpg)

Installed PSReadline-Beta2 and the symptoms seems to be corrected:

![pwsh_psreadbeta2_2018-06-05_7-47-58](https://user-images.githubusercontent.com/19892435/40975268-5dde01b4-6898-11e8-9d8d-4a8b74d8995c.jpg)

**Comment by MaximoTrinidad** [comment]
Hi @SteveL-MSFT,

Quick question: Is PSReadline Beta2 going to be release with the next version of PScore?
:)

**Comment by iSazonov** [comment]
@MaximoTrinidad Yes, we already have the opened PR.

**Comment by MaximoTrinidad** [comment]
@iSazonov, That's Great! 

Thanks

**Comment by SteveL-MSFT** [comment]
@marekr seems like PSReadLine 2.0.0-beta2 (to be included with next PSCore6.1-Preview3 release) fixes your issue.
