### ISSUE TITLE
Add test for *-Service cmdlets

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4147]
Add tests for *-service cmdlets.

Related code coverage report: https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
Doing this in parts to keep the code reviews simpler:

- [ ] Get tests
- [ ] Set-New tests
- [ ] Start-Stop-Suspend-Resume-Restart tests
