### ISSUE TITLE
Remove Microsoft.PowerShell.CoreCLR.AssemblyLoadContext.dll from PowerShell core

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShell#4149]
This is a follow-up issue of #3649 
After refactoring PowerShell assembly load context, we actually don't need `Microsoft.PowerShell.CoreCLR.AssemblyLoadContext.dll` anymore -- the remaining logic/functionality of this dll should be moved to `System.Management.Automation.dll` (`S.M.A.dll` depends on `AssemblyLoadContext.dll` today).
This might affect DSC because the DSC host is still depending on `AssemblyLoadContext.dll`, so we should communicate with DSC team on this to make sure nothing breaks.

Tasks
------

- [x] Remove `Microsoft.PowerShell.CoreCLR.AssemblyExtensions.LoadFrom(string assemblyPath)` once the PackageManagement module is migrated to .NET Core 2.0.
- [x] Removing `Microsoft.PowerShell.CoreCLR.AssemblyLoadContext.dll` completely.

**Comment by whatevergeek** [comment]
hi! any updates on this?
I'm trying to build powershell for linux.
It's failing for:
error CS0534: 'PowerShellAssemblyLoadContext' does not implement inherited abstract member 'AssemblyLoadContext.Load(AssemblyName)' 

Any workaround for now?

**Comment by iSazonov** [comment]
@whatevergeek Please open new Issue with repo steps.

**Comment by whatevergeek** [comment]
@iSazonov
someone suggested if i can get a fresh repo
as they said travics CI is passing.
I'll try that.
If issue still persist, i'll open a new issue
