### ISSUE TITLE
Add tests for Get-Content -Tail

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4150]
Add tests for ```Get-Content -Tail ``` parameter:

Related code coverage report: 
https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by sarithsutha** [comment]
@adityapatwardhan I'm interested in taking this up.  This would be my first time contributing to open source and this one seemed like a good place to start.

**Comment by sarithsutha** [comment]
@SteveL-MSFT @adityapatwardhan Is there a way to run the code coverage report before submitting a PR?

**Comment by adityapatwardhan** [comment]
You may want to have a have a look at https://blogs.msdn.microsoft.com/powershell/2017/01/11/code-coverage-now-available-for-powershell-core/

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sarithsutha** [comment]
Thanks for the information @adityapatwardhan , it came in handy.  I have raised a PR with my changes.
