### ISSUE TITLE
Add tests for New-Object -ArgumentList and -ComObject

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4154]
Add tests for New-Object 
- [x] -ArgumentList and 
- [x] -ComObject
    - [ ] - STA vs MTA

Related code coverage report: 
https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.PowerShell.Commands.Utility/commands/utility/new-object.cs

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by chunqingchen** [comment]
@adityapatwardhan I think this issue can be closed as all the scenarios are covered.
