### ISSUE TITLE
Add tests for WSMan provider, cmdlets and CredSSP

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4158]
Add tests for WSMan provider, cmdlets and CredSSP
Related code coverage report:

https://codecov.io/gh/PowerShell/PowerShell/tree/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/Microsoft.WSMan.Management

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
This is a big area, so I'm doing this is stages:

- [ ] ConfigProvider
- [X] CredSSP
- [ ] CurrentConfigurations
- [ ] InvokeWSManAction
- [ ] New-WSManSession
- [ ] PingWSMan
- [ ] Set-QuickConfig
- [ ] WSManConnections
- [ ] WSManInstance

**Comment by SteveL-MSFT** [comment]
The remaining files may be covered already by https://github.com/PowerShell/PowerShell/pull/4756, will wait on results before doing more here.
