### ISSUE TITLE
Add tests for TabCompletion for various input types

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4160]
Add tests for TabCompletion for various input types

Related code coverage report:

https://codecov.io/gh/PowerShell/PowerShell/tree/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/System.Management.Automation/engine/CommandCompletion

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment]
Summary of missing areas

CommandCompletion.cs
- [x] negatives cases/error handling (if some of these can't be hit, consider converting to asserts)
- [ ] in debugger
- [x] nested runspace/remote runspace
- [x] getting next result including wrap around
- [x] user overridden tabexpansion
- [ ] legacy tabexpansion
- [x] ~~remove PSv2 code~~ `PSv2CompletionCompleter` is for tab completion in a remote session that is from win8+ to win7, so it needs to be kept.
- [x] adding/handling quotes

CompletionAnalysis.cs
- [ ] cursor position (you have some of these covered, not sure if all)
- [ ] constrained language mode
- [ ] filename after redirection
- [ ] line continuation
- [ ] DSC resource

CompletionCompleters.cs
- [ ] fully qualified cmdlet
- [ ] remove workflow code
- [ ] complete module name
- [ ] import-dscresource
- [ ] positional parameter

CompletionResult.cs
- [ ] s_nullInstance
- [ ] Exceptions

ExtensibleCompletion.cs
- [ ] Exceptions
- [ ] `Register-ArgumentCompleter` with `CommandName = [string]::empty`

PseudoParameterBinder.cs
- [ ] remove workflow related code
- [ ] examine the code to see to find out specific missing areas

**Comment by SteveL-MSFT** [comment]
@daxian-dbw is the `PSv2CompletionCompleter` targeting PSv2?

**Comment by daxian-dbw** [comment]
Yes, it's for tab completion in a remote session from PSv3+ to PSv2.

**Comment by SteveL-MSFT** [comment]
Since we've formally deprecated v2, I'm wondering if we should keep this.  cc @joeyaiello

**Comment by SteveL-MSFT** [comment]
I think the remaining items can be pushed to MQ
