### ISSUE TITLE
Add tests for -is, -isnot, -contains, -notcontains and -like operators

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4162]
Add tests for -is, -isnot, -contains, -notcontains and -like operators

Related code coverage report:

https://codecov.io/gh/PowerShell/PowerShell/src/9e41c647a9407e05d86f4971a6bd25719a7130d0/src/System.Management.Automation/engine/lang/parserutils.cs

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16204
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan is this for the parser or where-object params?  I see tests for -like, -contains, and -notcontains and -is is used by other tests

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT  Added link to the report showing the missing coverage. Not sure why this is not covered.
