### ISSUE TITLE
Request: Allow runspaces to access "shared" pre-loaded modules.

### ISSUE THREAD

**Issue by axpae** [PowerShell/PowerShell#4170]
I understand that it is possible to Share variables and Objects between PowerShell runspaces.

I also understand that it is possible to pre-load modules with InitialSessionState, however this still results with having to wait for modules to load as each runspaces is created.

Runspaces are great, but when working with larger modules that take a few seconds to load into memory this starts to create significant resource costs, negating a lot of their potential benefit. For example, if I want to create 100s of runspace instances over a few minutes to undertake multi-threaded procedures due to certain triggers... having to import modules for every instance reduces the potential value of using runspaces.

To get around this, would it be possible to pre-load "shared" module(s) which are accessible to all runspaces, so there is no need to load required modules every time we kick off a new runspaces instance.

**Comment by iSazonov** [comment]
Modules is loaded in their own context so I believe it is possible to share them. Interesting whether they thread-safed?

**Comment by BrucePay** [comment]
It is not possible to share variables between runspaces as they are not thread-safe.

InitialSessionState doesn't pre-load modules. It takes a list of modules to load when the runspace is opened.

Ultimately, modules can only be loaded into a runspace and everything in a module is tied to that runspace. In other words, the minimum context for a module is the runspace.
