### ISSUE TITLE
Add Runtime (Timespan) property to Microsoft.PowerShell.Commands.HistoryInfo

### ISSUE THREAD

**Issue by powercode** [PowerShell/PowerShell#4181]
As is, we have StartExecutionTime and EndExecutionTime. 

We should add a property, `RunTime` defined as `EndExecutionTime - StartExecutionTime`, since at least in my experience, I am more concerned with how long a command took to execute than when it ran.

**Comment by SteveL-MSFT** [comment]
Seems like we can just use ETS to add a `RunTime` property and perhaps consider updating `get-history` formatting to include runtime by default as a column

**Comment by lzybkr** [comment]
@KirkMunro adds the property `Duration` in [HistoryPx](https://github.com/KirkMunro/HistoryPx). I believe he was considering integrating his ideas in HistoryPx into PowerShell Core.

**Comment by powercode** [comment]
@SteveL-MSFT Would that be easier than to add the property in code?

**Comment by SteveL-MSFT** [comment]
@powercode personally, I'm fine either way
