### ISSUE TITLE
PowerShell Snapin Overrides JEA VisibleCmdlets

### ISSUE THREAD

**Issue by tseward** [PowerShell/PowerShell#4187]
When loading a snapin via `Add-PSSnapin`, the cmdlets provided by the snapin override those allowed specified via VisibleCmdlets. Is this intended behavior? Ideally, only cmdlets assigned via VisibleCmdlets would be allowed after loading a snapin.

**Comment by alexandair** [comment]
First, you are not talking about PowerShell Core 6, right?
Second, I don't get how your JEA endpoint looks like. Is Add-PSSnapin one of the cmdlets defined in VisibleCmdlets setting?

**Comment by tseward** [comment]
That's correct, just PowerShell as shipped in Windows Server 2016. As far as VisibleCmdlets, no the snapin is added via a script specified via ScriptsToProcess; Add-PSSnapin is not specified in VisibleCmdlets.

**Comment by SteveL-MSFT** [comment]
PSSnapins aren't supported by PSCore, so this only affects Windows PowerShell.  cc @PaulHigin @rpsqrd

**Comment by tseward** [comment]
A workaround appears to be creating a 'fake' module in the Modules directory. E.g. `MyModule\MyModule.psm1` in which it runs `Add-PSSnapin Mysnapin`. Add 'MyModule' to `ModulesToImport`. From there, only the cmdlets exposed via `VisibleCmdlets` appear.

**Comment by alexandair** [comment]
It's hard to tell what you are trying to accomplish without looking at your session configuration and role capability files. In general, Add-PSSnapin and Import-Module should not be exposed in the constrained, JEA endpoint. Also, I think the VisibleCmdlets setting doesn't work as you expected it to work.

**Comment by tseward** [comment]
As I said, `Add-PSSnapin` isn't exposed via the endpoint, validated through `Get-Command` on the JEA session. Take SharePoint, as an example. Let's say you had a `VisibleCmdlets = 'Get-SPFarm'`. If you have a .ps1 that runs `Add-PSSnapin Microsoft.SharePoint.Powershell` and specify that script in `ScriptsToProcess`, the snapin will load successfully, but all cmdlets loaded by the snapin will be available (e.g. `Get-SPWebApplication`, `Disconnect-SPContentDatabase`, and so forth). That's clearly not desired.

If we create a module named `Microsoft.SharePoint.PowerShell` with the same `Add-PSSnapin Microsoft.SharePoint.Powershell` command within the .psm1, then add that module to `ModulesToImport`, only the cmdlets specified in `VisibleCmdlets` are available.

Hopefully that clarifies the difference.

**Comment by alexandair** [comment]
What happens if you just set VisibleCmdlets = 'Get-SPFarm' without any Add-PSSnapin and Import-Module?

**Comment by tseward** [comment]
Nothing, as the snapin must be loaded. Typically we'd accomplish this (locally) through the SharePoint Management Shell. But if we use a standard Windows PowerShell window or `Enter-PSSession`, we must call `Add-PSSnapin Microsoft.SharePoint.PowerShell [-EA 0]` to make the SharePoint cmdlets available for use.

**Comment by alexandair** [comment]
Could you try:
ModulesToImport='Microsoft.SharePoint.PowerShell'
VisibleCmdlets='Get-SPFarm'
Remove Add-PSSnapin line for a script (to load).

Does that expose only Get-SPFarm from SharePoint snapin?

**Comment by alexandair** [comment]
One more idea:
```
VisibleCmdlets='Microsoft.SharePoint.PowerShell\Get-SPFarm'
```

**Comment by tseward** [comment]
No, neither of those will work. SharePoint doesn't have a PowerShell Module, unfortunately. Only the  snapin. It will not load unless you explicitly call `Add-PSSnapin Microsoft.SharePoint.PowerShell`. None the less, I did try your suggestion of `ModulesToImport` and specifying the full path for `VisibleCmdlets`. In that case, because the snapin isn't loaded, the cmdlet isn't visible via `Get-Command` and my function that calls on a SharePoint cmdlet does not work

**Comment by doctordns** [comment]
You could build a module from the snapin. If the snapin just a container for an assembly containing cmdlets, then creating a module that loads the assembly should work. I've not tested it!

**Comment by kilasuit** [comment]
This isn't a PowerShell Core issue so should be raised in a forum like PowerShell.org for further discussion IMO

**Comment by SteveL-MSFT** [comment]
Yes, you can wrap the snapin as a module and it'll work just fine as a module.  However, if the snapin registration code is still there it won't work in PSCore6.  Porting a snapin to a module is simply deleting the snapin code and authoring a module manifest.

**Comment by TravisEz13** [comment]
Security Working group:
Windows PowerShell issues should be report at: https://windowsserver.uservoice.com/forums/301869-powershell

If this is a security vuln, please follow the [security policy](https://github.com/PowerShell/PowerShell/security/policy)
