### ISSUE TITLE
Calling powershell.exe in PSCore6 on Windows starts Windows PowerShell

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4194]
On Windows, `$env:Path` has Windows PowerShell in the path before `$PSHOME` which means that if you're in PowerShell Core 6 and type `powershell`, it starts Windows PowerShell 5.1 instead of a nested instance of PowerShell Core 6.  This may be unexpected for end users as it seems that one would expect `powershell` to refer to the currently running version of PowerShell.

The immediate impact is that partner teams running existing PowerShell script tests in PowerShell Core 6 that spawn `powershell` will get incorrect results as that process is running Windows PowerShell.

cc @joeyaiello @HemantMahawar 

Steps to reproduce
------------------

```powershell
# within PowerShell Core 6
powershell
$psversiontable
```

Expected behavior
-----------------

```none
PowerShell Core 6
```

Actual behavior
---------------

```none
Windows PowerShell 5.1
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.3
OS                             Microsoft Windows 10.0.16225
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@SteveL-MSFT Maybe Area-SideBySide?

**Comment by iSazonov** [comment]
If we have some PowerShell versions on system we should think about "default PowerShell" and a way to run specific PowerShell version by `-Version` parameter.

**Comment by SteveL-MSFT** [comment]
Based on some internal discussions, I think we agree that on Windows, we should put $PSHOME first in $env:PATH rather than at the end.

**Comment by iSazonov** [comment]
What about to enhance `-Version`?
```powershell
powershell -Version 5.1
powershell -Version 6.0.0
powershell -Version 6.0.0-Beta.4
powershell -Version UserDefault
powershell -Version SystemDefault
```

**Comment by SteveL-MSFT** [comment]
@iSazonov I think you should open a separate issue to discuss that

**Comment by iSazonov** [comment]
Done #4199

**Comment by chuanjiao10** [comment]
In my opinion, this is the default value question.
In the shortcut, start the directory settings.

**Comment by joeyaiello** [comment]
@SteveL-MSFT: other implications of this worry me. E.g. it might mean that anyone who can write to $PSHome can now squat over system binaries from within PowerShell. Let's talk offline.

**Comment by MaximoTrinidad** [comment]
In my own opinion, we should kept then separately.  As soon the PowerShell Core installation overrides any of the existing Windows variables over the Windows PowerShell it could open issues across the board. 

:)

**Comment by SteveL-MSFT** [comment]
@joeyaiello PSCore6 implicitly trusts binaries in $PSHome so that folder needs to be secure regardless.  The only change being proposed here is to move $PSHome to front of $env:Path (at the process level, not system or user setting) instead of the end so that it takes precedence over Windows PowerShell path.

**Comment by SteveL-MSFT** [comment]
If we decide to do https://github.com/PowerShell/PowerShell/issues/4214, we don't need to address this one
