### ISSUE TITLE
Question: In upcoming releases, is .NET Core 2.0 going to be required?

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4197]
Just to make sure I got all required component for up coming releases of PowerShell Core.
I case is needed to be added to the README.md file.

Thanks,
:)

**Comment by SteveL-MSFT** [comment]
Not sure what you mean.  PSCore6 releases include the appropriate version of .Net Core so you should never have to install it yourself.  You do need dotnet sdk to build PSCore6, however.
