### ISSUE TITLE
can not import Azure module

### ISSUE THREAD

**Issue by LaurentPrat** [PowerShell/PowerShell#4202]
Steps to reproduce
------------------
Can not import Azure module

PS /Users/laurentprat> Import-Module Azure 
---- Output generate with completion (tab)
                                                                      
Azure                            AzureRM.DataLakeStore            AzureRM.RecoveryServices.Backup                Azure.AnalysisServices           AzureRM.DevTestLabs              AzureRM.RedisCache                             Azure.Storage                    AzureRM.Dns                      AzureRM.Relay                                  AzureRM                          AzureRM.EventHub                 AzureRM.Resources                              AzureRM.AnalysisServices         AzureRM.HDInsight                AzureRM.Scheduler                              AzureRM.ApiManagement            AzureRM.Insights                 AzureRM.ServerManagement                       AzureRM.Automation               AzureRM.IotHub                   AzureRM.ServiceBus                             AzureRM.Backup                   AzureRM.KeyVault                 AzureRM.ServiceFabric                          AzureRM.Batch                    AzureRM.LogicApp                 AzureRM.SiteRecovery                           AzureRM.Billing                  AzureRM.MachineLearning          AzureRM.Sql                                    AzureRM.Cdn                      AzureRM.Media                    AzureRM.Storage                                AzureRM.CognitiveServices        AzureRM.Network                  AzureRM.StreamAnalytics                        AzureRM.Compute                  AzureRM.NotificationHubs         AzureRM.Tags                                   AzureRM.Consumption              AzureRM.OperationalInsights      AzureRM.TrafficManager                         AzureRM.ContainerRegistry        AzureRM.PowerBIEmbedded          AzureRM.UsageAggregates                        AzureRM.DataFactories            AzureRM.profile                  AzureRM.Websites                               AzureRM.DataLakeAnalytics        AzureRM.RecoveryServices       

----> Confirm the command + Enter                                                 
PS /Users/laurentprat> Import-Module Azure                                                                       
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module Azure
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
PS /Users/laurentprat> 

Expected behavior
-----------------
Should install Azure, like it did for AzureRM

Actual behavior
---------------
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ Import-Module Azure
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

Environment data
----------------
MacOS PowerShell, Beta Release 3
powershell-6.0.0-beta.3-osx.10.12-x64.pkg

```powershell
> $PSVersionTable

Name                           Value                                                                            
----                           -----                                                                            
PSVersion                      6.0.0-beta                                                                       
PSEdition                      Core                                                                             
GitCommitId                    v6.0.0-beta.3                                                                    
OS                             Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root...
Platform                       Unix                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                          
PSRemotingProtocolVersion      2.3                                                                              
SerializationVersion           1.1.0.1                                                                          
WSManStackVersion              3.0

**Comment by SteveL-MSFT** [comment]
You need to wait for latest Azure.NetCore update.  Existing Azure module isn't supported on coreclr.

Related https://github.com/PowerShell/PowerShell/issues/4090

**Comment by MaximoTrinidad** [comment]
Just a suggestion!!

This should be added to ReadMe.md document stating the difference between Windows PowerShell and PowerShell Core.  I think it should help clear some confusion.

:)
