### ISSUE TITLE
Disable deafening beep when pressing backspace by default 

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShell#4207]
Following the instructions [here](https://superuser.com/a/1180319), I managed to disable the deafening beep when pressing backspace.
I think it should be disabled by default because no matter what volume your computer is, it will play the beep at maximum volume and if you're using earphones, as I often am, it is a quite deafening sound.

**Comment by SteveL-MSFT** [comment]
cc @joeyaiello this falls into the bucket of PSReadline defaults

**Comment by WurstCommander** [comment]
Same here, it's not just the immediate press of backspace or if I reached the end of the line. Powershell random beeps after I typed some commands, it's very annoying. On my desktop PC, everything is fine, my Lenovo Laptop is having this problem.

**Comment by kilasuit** [comment]
This could potentially have been fixed as part of this issue https://github.com/PowerShell/PSReadLine/issues/422

**Comment by MartinGC94** [comment]
It has definitely been fixed so this issue should be closed.
