### ISSUE TITLE
Get-FormatData quietly ignores non-existing type-name arguments

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4235]
Steps to reproduce
------------------

```powershell
Get-FormatData NoSuch.Type.Exists.Or.IsLoaded
```

Expected behavior
-----------------

An error that indicates that the type does not exist (in the current session).

Actual behavior
---------------

A quiet no-op. No output, `$?` reports `$True`.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.3 on macOS 10.12.5
PowerShell Core v6.0.0-beta.3 on Ubuntu 16.04.1 LTS
PowerShell Core v6.0.0-beta.3 on Microsoft Windows 10 Pro (64-bit; v10.0.14393)
Windows PowerShell v5.1.15063.413 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by faraazahmad** [comment]
I would like to work on this

**Comment by faraazahmad** [comment]
What should the `ErrorCategory` be?

**Comment by faraazahmad** [comment]
@mklement0 @SteveL-MSFT  What should the `ErrorCategory` be?

**Comment by mklement0** [comment]
@faraazahmad:

Thanks for your willingness to take this on.

I'm not the best person to ask, but looking at the enumeration values at https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.errorcategory?view=powershellsdk-1.1.0, perhaps `ResourceUnavailable`?

**Comment by SteveL-MSFT** [comment]
@faraazahmad consider it yours!  Thanks!

**Comment by faraazahmad** [comment]
So my code now outputs this: 
```
PS /home/faraaz> Get-FormatData yolo
Get-FormatData : No such type
At line:1 char:1
+ Get-FormatData yolo
+ ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (System.String[]:String[]) [Get-FormatData], ArgumentException
+ FullyQualifiedErrorId : SPECIFIED_TYPE_NOT_FOUND,Microsoft.PowerShell.Commands.GetFormatDataCommand
```
Is this all right?

**Comment by Jaykul** [comment]
HANG ON ... This is a **breaking** change to the function!!! 

Does `-ErrorAction SilentlyContinue` work, or are you now forcing everyone to wrap this in a try/catch block?
