### ISSUE TITLE
Consider adding -NoRemoting switch to Start-PSBuild to obviate VC++ deps.

### ISSUE THREAD

**Issue by oising** [PowerShell/PowerShell#4236]
The requirement to have the VC++ build tools in order to build powershell-win-core seems like a needless barrier for contributing to this project. Even installing 14.0 build support with VS 2017 doesn't allow a full build due to parameter changes in various support files (vcvars.cmd, mc.exe etc.) Adding this switch would remove the requirement for VS 2015 -- in fact it should remove the requirement for VS entirely.  I am willing to take on this PR.

**Comment by SteveL-MSFT** [comment]
This will be resolved by https://github.com/PowerShell/PowerShell/issues/3014
