### ISSUE TITLE
Limitations .Net Core to migrate Test-Connection cmdlet

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell#4240]
It is only a tracking issue.

We plan to migrate `Test-Connection` cmdlet from WMI to .Net but underlying .Net Core have still Issue [System.Net.Ping ignores PingOptions on unix](https://github.com/dotnet/corefx/issues/9350). 
[Related code](https://github.com/dotnet/corefx/blob/7ce4889d1de78d251d7e536ee174ff8640fa8583/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs#L71). There are no plans yet to fix it in 2.0.0 timeframe.

**Comment by its02003** [comment]
Any update on this?

**Comment by iSazonov** [comment]
We have #5328 for Test-Connection.
I don't know .Net Core plans about removing implementation restrictions.

**Comment by its02003** [comment]
So until .Net core moves, this won't hit RC?

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please comment - what's our road map?

**Comment by SteveL-MSFT** [comment]
This depends on corefx and I'm not sure what their roadmap is as I've been focused on 6.0.0 right now.  We should revisit for 6.1.0

**Comment by artisticcheese** [comment]
This is a huge bummer for adoption of powershell core when `windows powershell` is still available. This one of very first things any respectable admin will do when troubleshooting any sort of communication between hosts. So for now, definitely not recommending within our company to adopt.

**Comment by iSazonov** [comment]
@artisticcheese You can load the build from #5328, test the new ported cmdlet and leave a feedback in the #5328.

**Comment by SteveL-MSFT** [comment]
Fixed by https://github.com/PowerShell/PowerShell/pull/5328

**Comment by iSazonov** [comment]
@SteveL-MSFT No. It is a tracking issue - we are waiting a fix in .Net Core repo.

**Comment by vexx32** [comment]
Per https://github.com/dotnet/corefx/issues/28934 .NET Core team are deferring likely until .NET 5 according to current milestone assignments.

Related PR: 

- [ ] #10697 Improvements to behaviour & output

Related issues:

- [ ] #10979 Mostly-useless traceroutes on Unix
- [ ] #7590 Wrong error codes
