### ISSUE TITLE
PowerShell Core Beta 4 - Instruction page send back to landing page.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4249]
When clicking in the PowerShell Core OS "Instructions" link, then is talking back to the main page.  I can go straight to the "release" link to download PowerShell Core Beta 4 with no issues.

:)
![powernext_2017-07-13_19-59-12](https://user-images.githubusercontent.com/19892435/28192782-610d4068-6806-11e7-9595-170e1685f089.jpg)

**Comment by SteveL-MSFT** [comment]
Not seeing your repro.  Clicking on those two links takes me to the instruction pages.

**Comment by MaximoTrinidad** [comment]
Never mind!  It's something with mi Edge Browser cache not getting to the page.  I can access the link with another browser Chrome.

I'm closing the issue!

Thanks
