### ISSUE TITLE
Invoke-Item -Path does not work 

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#4252]
PS C:\PowerShell\6.0.0-beta.4> ii -Path c:\
ii : Access is denied
At line:1 char:1
+ ii -Path c:\
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.InvokeItemCommand

PS C:\PowerShell\6.0.0-beta.4> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.16226
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by mklement0** [comment]
Just to spell it out: any _directory_ path triggers the bug (as opposed to a _file_ path).

* On Windows, the terminating error cited above occurs.

* On Unix (macOS, Linux), the command is a  quiet no-op (no action, no output, `$?` is `$True`).

**Comment by MaximoTrinidad** [comment]
Hum!  I'm not getting the error and I'm on Windows 10 Insider Build 16237. I can use the Tab key and it auto-completes the line.  I'm getting valid errors.

```
PS C:\Program Files\PowerShell\6.0.0-beta.4> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.16237
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Ah!  This is if you don't auto-complete what you're typing.  Press Enter after typing c: then the error happens.  I normally use the tab to auto filled the line.

Definitely the error is not the correct one!

![ps5ii_2017-07-14_10-04-53](https://user-images.githubusercontent.com/19892435/28215508-4c8d6cf0-687c-11e7-8b39-ca6c3125a816.jpg)

**Comment by mklement0** [comment]
@MaximoTrinidad: The bug is unrelated to tab completion. The only thing that matters is whether the path you end up submitting is a path to a _directory_ (bug) or to a _file_ (OK).

**Comment by MaximoTrinidad** [comment]
@mklement0, 

Thanks!

Sorry for the confusion! I didn't meant the tab-completion was an issue.  On the contrary,  I won't have never spotted the bug because I either:  I type the whole path, or type the path partially to then use Tab to complete the line. 

I see the bug!

:)

**Comment by SteveL-MSFT** [comment]
This is a regression in corefx.
