### ISSUE TITLE
Alias for "which" would be useful on Windows

### ISSUE THREAD

**Issue by marekr** [PowerShell/PowerShell#4263]
cmd.exe has "where" which is equivalent to the linux "which" which reports back where a executable is from PATH.

PowerShell aliases "where" to "Where-Object" so unforunately the cmd.exe compat is out the window.

But "which" is available and could be a nice alias to match linux here by aliasing it to Get-Command.

**Comment by mklement0** [comment]
This has been proposed before - see #2885

I think the consensus is that PowerShell aliases should not shadow standard Unix utilities, which is the reason why aliases such as `ls` and `cat` - present in _Windows PowerShell_ - were removed from PowerShell _Core_ - see #929 (related: #3610)

**Comment by marekr** [comment]
The other problem then is powershell aliases windows cmd.exe commands like
"dir" but not "where"

**Comment by marekr** [comment]
*
