### ISSUE TITLE
default shortcut on Windows remaps ANSI colors 35,36

### ISSUE THREAD

**Issue by refack** [PowerShell/PowerShell#4266]
This should probably go to the Windows group, but Github is a better platform.
Ref: https://github.com/nodejs/node/issues/14243

Steps to reproduce
------------------

```powershell
node
> process.stdout.write(`\u001b[35mXXX\u001b[39m`)
```

Expected behavior
-----------------
megenta output
![image](https://user-images.githubusercontent.com/96947/28250472-83dd43da-6a37-11e7-91c8-682c6989a63f.png)

Actual behavior
---------------
dark blue output (same as background)
![image](https://user-images.githubusercontent.com/96947/28250572-c85d6772-6a39-11e7-920b-eb3540a71dd3.png)

Environment data
----------------
The default [powershell `.lnk`](https://stackoverflow.com/questions/13690223/how-can-i-launch-powershell-exe-with-the-default-colours-from-the-powershell-s) remaps colors 35, and 36 

![image](https://user-images.githubusercontent.com/96947/28250592-67b454e8-6a3a-11e7-8d37-dab2436ff8ed.png)

**Comment by iSazonov** [comment]
@refack Thanks for your report! Could you please test with latest PowerShell Core version - Beta.4?

**Comment by refack** [comment]
Direct execution:
![image](https://user-images.githubusercontent.com/96947/28265701-15e8ada0-6abf-11e7-85de-74826640f87f.png)

With the shortcut:
![image](https://user-images.githubusercontent.com/96947/28265733-4203d2de-6abf-11e7-8044-088fb8b7ba25.png)

The `.lnk` file
[powershel.lnkl.zip](https://github.com/PowerShell/PowerShell/files/1152332/powershel.lnkl.zip)

**Comment by iSazonov** [comment]
@refack Thanks for the test!

**Comment by chuanjiao10** [comment]
what do you want?
you want change text color?
why you change background color.

**Comment by BrucePay** [comment]
FWIW - some background:  This behavior is actually intentional. Prior to the V1 release of PowerShell, the UI designers picked colors for the PowerShell console. Since the background color they chose wasn't part of the standard palette, one of the less used standard colors was remapped to produce what the designers wanted. It's been shipping that way ever since.

**Comment by refack** [comment]
> FWIW - some background: This behavior is actually intentional. Prior to the V1 release of PowerShell, the UI designers picked colors for the PowerShell console. Since the background color they chose wasn't part of the standard palette, one of the less used standard colors was remapped to produce what the designers wanted. It's been shipping that way ever since.

Designers 🤷‍♂️ .
IMHO should have remapped the black and white, but...
If anyone has any idea how force `conhost` to respect ANSI, we could implement on our end.

**Comment by rkeithhill** [comment]
conhost in Window 10 1607 and higher IIRC has some ANSI support.  Try:

```posh
$E = [char]0x1b; "$E[35;1;40m"
```
If you're using PowerShell Core then you can use:
```posh
"`e[35;1;40m"
```
It's not 100% though.  As I type commands I can see the original blue as the background.

**Comment by refack** [comment]
@rkeithhill interesting results
![image](https://user-images.githubusercontent.com/96947/28344856-5f1d4f36-6bf4-11e7-9fa4-eff3fd2de6d0.png)
Still seems like `conhost` is using it's own palette, and not ANSI colors...

**Comment by rkeithhill** [comment]
That ANSI directive is still using one of the 16 palette colors.  So if the color palette index has been overridden, you'll get the overridden color.  That is why used the bright magenta e.g.:
![image](https://user-images.githubusercontent.com/5177512/28345234-33433d20-6be6-11e7-9779-b467985740a4.png)
If you are on 1703, then you can use 24-bit color:
```posh
"`e[38;2;128;0;128;48;2;0;0;0m"
```
But it only colors output as opposed to changing the bg color.

**Comment by chuanjiao10** [comment]
"`e[38;2;128;0;128;48;2;0;0;0m"
But it only colors output as opposed to changing the bg color.
--------Wow,6.0 beta 1 test success,tell me more. How can a tutorial?

**Comment by rkeithhill** [comment]
I don't know about a tutorial but I use as a reference: https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx

**Comment by gibfahn** [comment]
>This behavior is actually intentional. Prior to the V1 release of PowerShell, the UI designers picked colors for the PowerShell console. Since the background color they chose wasn't part of the standard palette, one of the less used standard colors was remapped to produce what the designers wanted.

Does that mean there's no chance of it changing? Not being able to see one of the standard colours seems like a pretty major defect for a console (which I guess is why it's remapped in the powershell shortcut, see https://github.com/nodejs/node/issues/14243#issuecomment-315631040).

>IMHO should have remapped the black and white, but...

This seems like a reasonable solution, any chance of it happening?

**Comment by chuanjiao10** [comment]
rkeithhill  3q

**Comment by silverwind** [comment]
> Since the background color they chose wasn't part of the standard palette, one of the less used standard colors was remapped to produce what the designers wanted.

I think the default fg/bg colors should be decoupled from the 16 ANSI colors, and instead be separately be defined. That's how pretty much all Unix terminals do it.

**Comment by SteveL-MSFT** [comment]
As best as I can tell, neither the cmd.exe shortcut nor the PSCore6 shortcut modifies the magenta color so it's only an issue with Windows PowerShell, correct?  As @BrucePay mentioned, for Windows PowerShell, this is by-design and changing it now is a breaking change.
