### ISSUE TITLE
 Cant't import MsOnline module on Linux based OS.

### ISSUE THREAD

**Issue by Arjun4545** [PowerShell/PowerShell#4269]
Hello,
When trying to import Msol module, I am getting the following error on linux (Ubuntu 14.04) OS:

**import-module : The specified module 'msonline' was not not loaded because no valid module file was found in any directory.**

Though required DLLs are present in the installed module directory.

**Comment by pcgeek86** [comment]
Chances are that this module is not compatible with .NET Core and it has been specifically targeting the "Full" .NET Framework on the Microsoft Windows platform. Given the nature of this module, the best team to handle porting the module would likely be the Azure Active Directory or Office 365 teams.

**Comment by MaximoTrinidad** [comment]
My suggestion, as this has been previously discussed, that it should be mention in the PowerShell GitHub landing page (readme.md).  We now there's a Azure Core module coming out soon, but nothing on Office 365 nor Azure Active Directory.  This way we could avoid this issue appearing every time.

:)

**Comment by iSazonov** [comment]
We collect such  non-compatibility in #4062

**Comment by MaximoTrinidad** [comment]
@iSazonov 

Thanks for the heads up!!
:)

**Comment by iSazonov** [comment]
See comments in dup #3776
