### ISSUE TITLE
On Windows, Login-AzureRmAccount fails

### ISSUE THREAD

**Issue by funrockstefan** [PowerShell/PowerShell#4281]
In 6.0.0-beta.4 on Windows, Login-AzureRmAccount throws the following exception:

Login-AzureRmAccount : Could not load type 'System.Drawing.Drawing2D.InterpolationMode' from assembly 'System.Drawing,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

**Comment by SteveL-MSFT** [comment]
The existing Azure module is not expected to work with PSCore6.  Azure PowerShell team is porting their module to coreclr.
