### ISSUE TITLE
Add validation that Invoke-Item opens directory in Finder on Mac

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4282]
For PR https://github.com/PowerShell/PowerShell/pull/4262 validation was added to Windows and Linux. 
On Linux, we change the default application to a shell command to verify the output.  On Mac, you would
use `lsregister` to do something similar, however, MacOS doesn't have a straightforward way to register
and unregister at runtime (no api).  Registration is done as part of app creation and startup.

**Comment by mklement0** [comment]
You can use AppleScript as follows (via its `osascript` CLI):

```powershell
$appleScriptWindowCount = 'tell application "Finder" to count of windows'

$before = [int] ($appleScriptWindowCount | osascript)

# Invoke-Item $PSHome
open $PSHOME

$startTime = Get-Date
while (((Get-Date) - $startTime).TotalSeconds -lt 5 -and ([int] ($appleScriptWindowCount | osascript) -eq $before))
{
  Start-Sleep -Milliseconds 100
}

$after = [int] ($appleScriptWindowCount | osascript)

$before + 1  | Should Be $after

('tell application "Finder" to POSIX path of ((target of front window) as text)' | osascript) | Should Be "$PSHOME/"
```

Note the need to _pipe_ the AppleScript source code to `osascript`, because **argument passing on Unix is still horribly broken** (I've lost track of the debate):

```powershell
osascript -e 'tell application "Finder" to count of windows'
```

SHOULD work, but currently doesn't, because the embedded `"` are discarded.

**Comment by SteveL-MSFT** [comment]
@mklement0 got around to finishing this.  your pointer to AppleScript really helped!

**Comment by mklement0** [comment]
@SteveL-MSFT: I am glad to hear it.

[Ceterum censeo](https://en.wikipedia.org/wiki/Carthago_delenda_est) argumentum transitum esse reficiendam.<sup>[1]</sup>

<sup>[1] That's fake Latin for: Fix the argument passing on Unix platforms.</sup>

**Comment by SteveL-MSFT** [comment]
If there isn't an issue already, please open one for that

**Comment by mklement0** [comment]
@SteveL-MSFT: Please have a look at https://github.com/PowerShell/PowerShell/issues/1995#issuecomment-325231274.
