### ISSUE TITLE
Remoting tests that target PowerShell 5.1 should be disabled consistently

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PowerShell#4289]
WinRM (Windows only) based remoting tests require either a default or custom PowerShell endpoint, and currently endpoints are based on built-in PowerShell 5.1.  Consequently many remoting tests do not work correctly and must be disabled.  We should disable them in a consistent way, I think by using the -Pending switch.

**Comment by SteveL-MSFT** [comment]
Instead of marking them `Pending`, we may be able to fix them after https://github.com/PowerShell/PowerShell/pull/2671 gets merged

**Comment by PaulHigin** [comment]
I somehow missed that PR, but yes part of that work should be to update all remoting tests so that they run on the new endpoints.  I'll take a look at the PR this week.

**Comment by PaulHigin** [comment]
Actually, that work is incomplete.  We need to make all remoting cmdlets work, not just Enable-PSRemoting.  I'll comment on the PR.

**Comment by TravisEz13** [comment]
@PaulHigin  Can this be closed?
