### ISSUE TITLE
Suggestion: Add parameters to Compare-Object that directly support retrieval of left-side-only or right-side-only objects

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4293]
When comparing two sets of objects, it is currently somewhat cumbersome to retrieve only those objects exclusive to _one_ side of the comparison:

```powershell
$left = 1, 2, 3, 4
$right = 1, 3, 4, 5

# Left-side only: -> 2
(Compare-Object $left $right | Where-Object SideIndicator -eq '<=').InputObject

# Right-side only: -> 5
(Compare-Object $left $right | Where-Object SideIndicator -eq '=>').InputObject
```

Wishful thinking:

```powershell
$left = 1, 2, 3, 4
$right = 1, 3, 4, 5

# Left-side only: -> 2
Compare-Object $left $right -LeftOnly -PassThru

# Right-side only: -> 5
Compare-Object $left $right -RightOnly -PassThru
```

* `-LeftOnly` and `-RightOnly` would be mutually exclusive and incompatible with `-ExcludeDifferent`

* The existing `-PassThru` switch omits the custom-object wrapper with the side indicator that is created by default (despite the documentation claiming "Returns an object representing the item with which you are working. By default, this cmdlet does not generate any output." - see https://github.com/PowerShell/PowerShell-Docs/issues/1461).

* To achieve left-"join" and right-"join" logic, simply add the existing `-IncludeEqual` switch.

<sup>Note: I'm using "join" in double quotes, because no joining (merging of data) in the usual sense happens - only different or identical objects are returned.</sup>

Note that the _left_  / _right_ terminology is not currently part of `Compare-Object`, but I feel it is descriptive and intuitive (cf. SQL join terminology).

Thus, additionally, the following parameter aliases could be introduced:

* `-LeftObject` as an alias for `-ReferenceObject`
* `-RightObject` as an alias for `-DifferenceObject`

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.4
```

**Comment by iSazonov** [comment]
More native:
`Join-Object  -Left -Right -Union -Intersection`

**Comment by mklement0** [comment]
@iSazonov: `Join-Object` is not appropriate, because `Compare-Object` performs no joining (merging) of data - it only returns different or identical objects (I've updated the original post to clarify that).

While a bona fide SQL-style `Join-Object` cmdlet would be great, it would be a much bigger undertaking.

By contrast, what I'm proposing here is a relatively simple addition to the existing `Compare-Object` functionality.

**Comment by iSazonov** [comment]
The question is what is the comparison for? I think getting the end list is more useful - Compare-Object returns comparison results then we should filter the results and get the end list for processing.
Internally ` Join-Object ` will be based on `Compare-Object`.

**Comment by mklement0** [comment]
@iSazonov: Building a future `Join-Object` on `Compare-Object` sounds promising.

I don't understand the rest of your statement, but let me try to clarify what this issue is about:

`Compare-Object` currently makes it easy to find:

* only unique objects (property sets)
* only identical objects (property sets)
* or both

However, the unique objects currently invariably are the unique objects from _both_ sides, whereas it is not uncommon - see [this SO question](https://stackoverflow.com/q/45193418/45375), for instance - to only want _one_ side's unique objects - this is what `-Left[Difference]Only` and `-Right[Difference]Only` would provide.

**Comment by iSazonov** [comment]
I would prefer classic terms:
- Union (A ∪ B)
- Intersection (A ∩ B)
- Symmetric difference (A ∆ B)
- Relative complement (A ∖ B)

**Comment by mklement0** [comment]
First things first: I definitely like the idea.

Let's see how these concepts map onto how `Compare-Item` currently works:

* Union (A ∪ B)

`Compare-Object $A $B -IncludeEqual -PassThru`

* Intersection (A ∩ B)

`Compare-Object $A $B -IncludeEqual -ExcludeDifferent -PassThru`

* Symmetric difference (A ∆ B)

`Compare-Object $A $B  -PassThru`

* Relative complement (A ∖ B)

`Compare-Object $A $B  | ? SideIndicator -eq '=>' | % InputObject`

Thus, new parameters `-Union`, `-Intersection`, `-SymmetricDifference`, and `-Complement` could be introduced that are effectively aliases / shortcuts to the commands above.

Note that since _2_ sets are by definition involved, I think the shorter `-Complement` will do instead of `-RelativeComplement`.

One thing to note is the _order_ in which objects are output - this is not currently documented (from a _set_ perspective, order doesn't matter, but for subsequent processing it may), and I haven't dug into the source to verify, but from what I can tell, it is:

* `==` (identical) objects first
* `>=` right-side-only objects next
* `<=` left-side-only objects last

Note that all of them effectively suppress the custom-object wrapper with the `.SideIndicator` property and return the selected input objects directly.

On a related note, I wonder if something like a new `-Group` switch would make sense in order to return a _hashtable_ of original objects grouped by what is currently the `.SideIndicator` value; e.g.:

```powershell
$A = 1, 2, 3, 4
$B = 1, 3, 4, 5

# Wishful thinking
Compare-Object -Group -Union $A $B
```

which would yield the equivalent of:

```powershell
@{
  '==' = 1, 3, 4
  '<=' = , 2
  '=>' = , 5
}
```

Unless you think this needs refining / you want to discuss further, I'll update the initial post and the issue's title.

**Comment by iSazonov** [comment]
>Thus, new parameters  -Union ,  -Intersection ,  -SymmetricDifference , and  -Complement  could be introduced that are effectively aliases / shortcuts to the commands above.

I see it as parameter sets.

>Note that since 2 sets are by definition involved, I think the shorter  -Complement  will do instead of  -RelativeComplement .

Agree.

> something like a new  -Group  switch would make sense in order to return a hashtable of original objects 

Maybe `-AsHashTable`?

**Comment by mklement0** [comment]
> I see it as parameter sets.

Yes, absolutely - they would complement the old parameter sets (which could then be considered deprecated).

> Maybe `-AsHashTable`?

While that nicely parallels `Group-Object`, the difference is that there you _always_ get a group, and `-AsHashTable` simply changes the _format_ used to represent that group.

Here, we're actually changing the _structure_ of the output fundamentally.

That said, perhaps the `Group-Object` analogy is more helpful, so I'm open to the idea, though it's certainly something that can be decided later.

I'll write up a summary of our conversation, presumably as a new issue (I'll close this one).
Thanks for all your input.

**Comment by mklement0** [comment]
Thanks, for tagging, @SteveL-MSFT, but I'm closing this in favor of the rewritten, more focused #4316
