### ISSUE TITLE
bug: Could not load type 'System.Diagnostics.PerformanceCounter'

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShell#4295]
Steps to reproduce
------------------
the script error.ps1 is attached.

1. download WinSCP .Net assembly from [https://winscp.net/download/WinSCP-5.9.6-Automation.zip](url)
2. unzip in a directory named  `C:\PS_B4`)
**Note:**
in case a different directory name is choosen, script code below needs to be adapted before running it!
$WinSCPnet_dll = ("C:\PS_B4\WinSCPnet.dll")
3. copy attached script: error.ps1 inthe the same directory
4. run powershell.exe
.\error.ps1 

Expected behavior
-----------------

no error

and text:
script: ended successfully

Actual behavior
---------------

error gets 

thrown:

Exception calling ".ctor" with "0" argument(s): "Could not load type 'System.Diagnostics.PerformanceCounter' from assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by iSazonov** [comment]
@mi-hol Thanks for your report! Please add a _sample_ script to repo the error.

**Comment by mi-hol** [comment]
[error.ps1.txt](https://github.com/PowerShell/PowerShell/files/1160140/error.ps1.txt)

**Comment by iSazonov** [comment]
@mi-hol Thanks! 
I tried WinSCP module https://github.com/dotps1/WinSCP - it use the same dll and works well.

**Comment by iSazonov** [comment]
I mannually load the dll from the module - works well.

**Comment by iSazonov** [comment]
I download WinSCP-5.9.6-Automation.zip and mannually load the dll from the package - works well.

**Comment by mi-hol** [comment]
@iSazonov do the comments mean that you can't reproduce the error using my error.ps1 script?

**Comment by iSazonov** [comment]
@mi-hol I edited my message.

It seems CoreFX don't implement `System.Diagnostics.PerformanceCounter` 
See https://github.com/dotnet/corefx/issues/3906
and https://github.com/dotnet/corefx/pull/17898 - "Only refs adjusted!"

/cc @daxian-dbw Is it problem for PowerShell Core RTM?

**Comment by mi-hol** [comment]
From my view PerformanceCounter is frequently used and all metrics are defined in
PowerShell/src/Microsoft.PowerShell.Commands.Diagnostics/CoreCLR/Stubs.cs
i.e. to calculate

'        /// A difference timer that shows the total time between when the component
        /// or process started and the time when this value is calculated.
        /// </summary>
        ElapsedTime = 807666944,'

**Comment by daxian-dbw** [comment]
https://github.com/dotnet/corefx/issues/3906 is labelled with `Future` milestone, so it won't be available in .NET Core 2.0. @mi-hol please feel free to leave comments in that corefx issue, so as to let them know the user demands.

**Comment by iSazonov** [comment]
I wonder what is plans for our counter cmdlets? Should we make a workaround in the repo until we have CoreFX implementations? Have we a tracking Issue?

/cc @TravisEz13

**Comment by TravisEz13** [comment]
#4306 is tracking the lack of counter CmdLets.
I'm not aware of a workaround.

**Comment by mi-hol** [comment]
@daxian-dbw in light of Joey Aiello's public community request to 'tell us what does and doesn’t work for you on github'  I'm a bit puzzled by the unexpected close of a confirmed incompatibility.
#4306 doesn't mention the error message user will receive due to this incompatibly, hence I wonder how user feedback for this specific issue will be properly gathered?

**Comment by daxian-dbw** [comment]
@mi-hol We do welcome feedbacks and I appreciate you brought up this issue.
This issue was closed because the problem is understood and the resolution is out of the scope of powershell. The API/assembly it depends on is not available in `.NET Core 2.0` and `netstandard2.0`, and thus nothing can be done on the powershell side unless dotnet/corefx#3906 is fixed.

**Comment by daxian-dbw** [comment]
@mi-hol I edited your comment related to this issue in #4062 to add the root cause of this issue. That will help get all information we need in one place.

**Comment by mi-hol** [comment]
@daxian-dbw Thanks! Hopefully the effort I put into opening & reproducing this bug is not wasted.

**Comment by daxian-dbw** [comment]
@mi-hol Your effort is truly appreciated. When reviewing comments reported in #4062, people can easily get here via the link to learn more information about the issue.

Thanks for bringing up your concern about this issue being closed. I should have better explained the "why" when closing it. Lesson learned :)
