### ISSUE TITLE
Missing Bash colors

### ISSUE THREAD

**Issue by loxal** [PowerShell/PowerShell#4298]
As you can observe in PS6beta4 the Bash colors are not displayed when starting bash form withing PowerShell or login via SSH into a remote Linux bash:

![image](https://user-images.githubusercontent.com/87507/28389769-cb9e0964-6cd7-11e7-81e1-96e5f506f8d1.png)

**Comment by SteveL-MSFT** [comment]
I see the same behavior starting bash from cmd.exe?

**Comment by MaximoTrinidad** [comment]
Windows 10 Pro Insider Preview Build 16241 
Cmd to Bash Colors fine!

![cmdbash_2017-07-20_20-44-50](https://user-images.githubusercontent.com/19892435/28444619-863a9008-6d8c-11e7-94c8-3618a5260f2b.jpg)

**Comment by loxal** [comment]
I am not talking about Windows' "Bash". I am talking about Linux' bash into which I logged in via SSH. My screenshot shows a remote Linux machine's bash prompt not the local Ubuntu Bash prompt (which works as yours incl. colors).

**Comment by loxal** [comment]
@SteveL-MSFT yes, SSHing into a Bash from `cmd.exe` results in same behavior. Only SSHing from Windows' Bash into a Linux Bash gives me the proper colors.

**Comment by SteveL-MSFT** [comment]
@loxal if you're using Win32-OpenSSH, I believe you're hitting https://github.com/PowerShell/Win32-OpenSSH/issues/252, if you explicit `export TERM=xterm` I expect you'll get your colors back

**Comment by loxal** [comment]
It changed something but still no colors... 

When I login with PowerShell, Ubuntu's bash (real Linux, over SSH) automatically sets `TERM=cygwin`. However, if I login with Windows' Bash then, the Linux bash sets `TERM=xterm-256color` which is fine for Windows' Bash and I see the colors. Setting `TERM=xterm` or `TERM=xterm-256color` in `~/.profile` has still no effect on the prompt but when I open Vim, I see a mess.

**Comment by SteveL-MSFT** [comment]
@loxal can you provide step-by-step repro instructions?

**Comment by loxal** [comment]
Actually there are no steps, just SSH into a Linux machine, e.g. Ubuntu.

**Comment by MaximoTrinidad** [comment]
Hum!! Interesting... In my case.

Windows 10 Pro Insider Build 16241
Win32 OpenSSH (Universal Installer) 0.0.18.0
Ubuntu 16.04.2

Yes! @loxal is correct. To replicate run command
```
ssh username@ubunsystem
```
Sample images shows Bash console colors are gone.

![winubunssh_01_2017-07-26_8-38-15](https://user-images.githubusercontent.com/19892435/28621410-db653992-71de-11e7-8684-50e0facebb4f.jpg)

![winubunssh_02_2017-07-26_8-38-15](https://user-images.githubusercontent.com/19892435/28621417-e0aea744-71de-11e7-8dfa-98d09665338c.jpg)

![winubunssh_04_2017-07-26_8-38-15](https://user-images.githubusercontent.com/19892435/28621498-2a36f286-71df-11e7-97fc-d63d5812b176.jpg)

![winubunssh_03_2017-07-26_8-38-15](https://user-images.githubusercontent.com/19892435/28621432-e89232e6-71de-11e7-9284-e65fb6f314e3.jpg)

**Comment by SteveL-MSFT** [comment]
This is https://github.com/PowerShell/Win32-OpenSSH/issues/828 which I just opened and has workaround
