### ISSUE TITLE
Implement LocalAccounts module using supported APIs

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4305]
The code for the previous implementation is here:
https://github.com/PowerShell/PowerShell/tree/master/src/Microsoft.PowerShell.LocalAccounts 
removed due to #4272

**Comment by SteveL-MSFT** [comment]
Looks like https://docs.microsoft.com/en-us/windows/win32/api/lmaccess/ APIs are now public.  So we could port this to Core, just need to map the old API calls to public ones.

**Comment by fullenw1** [comment]
Any news on this module?
In PowerShell 7 it's still not working...

```powershell
PS> Get-LocalGroup
Get-LocalGroup: The 'Get-LocalGroup' command was found in the module 'Microsoft.PowerShell.LocalAccounts', but the module could not be loaded.
For more information, run 'Import-Module Microsoft.PowerShell.LocalAccounts'.

PS> Import-Module -Name Microsoft.PowerShell.LocalAccounts
Import-Module: The parameter is incorrect.

PS> Import-Module -Name Microsoft.PowerShell.LocalAccounts -UseWindowsPowerShell
Import-Module: The parameter is incorrect.

PS>
```

**Comment by TravisEz13** [comment]
This is done
![image](https://user-images.githubusercontent.com/10873629/82503812-d4005500-9aae-11ea-9e2e-a5a159508090.png)

**Comment by TravisEz13** [comment]
@SteveL-MSFT Do we still need this if it works.  Looks like it loads directly in PowerShell 7.

**Comment by fullenw1** [comment]
Hi @TravisEz13 

Interesting! I upgraded PowerShell 7.0.0 to PowerShell 7.0.1 but still have the same error message.
There is certainly a difference between our systems...

**Comment by joeyaiello** [comment]
If `Import-Module -Name Microsoft.PowerShell.LocalAccounts` isn't working, please file a different issue with repro steps. 

This is working fine on my machine (and has for a while). I agree with @TravisEz13 (and @SteveL-MSFT offline), that this isn't something we need to do for Windows specifically given that it already ships in the box and is fully compatible.
