### ISSUE TITLE
Implement Counter CmdLets using Supported APIs

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4306]
Implement Counter CmdLets using Supported APIs
The previous implementation is here:
https://github.com/PowerShell/PowerShell/tree/master/src/Microsoft.PowerShell.Commands.Diagnostics
Which was removed due to #4272

**Comment by iSazonov** [comment]
Could you please clarify what is "unsupported API" in previous implementation?

**Comment by TravisEz13** [comment]
I'll restate @iSazonov question which I removed.

> How do I know what APIs are supported?

You can assume that APIs documented in MSDN are supported as long as you follow the requirements in MSDN.

**Comment by SteveL-MSFT** [comment]
System.Diagnostics.PerformanceCounter is part of WindowsCompatibilityPack for dotnetcore so this work is being done as part of WindowsPowerShellCompatibilityPack

**Comment by iSazonov** [comment]
@SteveL-MSFT The problem is that there is no public API - MSFT can distribute the cmdlets only in  _binary package._

**Comment by SteveL-MSFT** [comment]
@iSazonov need to figure out how to handle non-public APIs as I think only components shipped with Windows can use those APIs so even a binary package on PSGallery wouldn't be acceptable

**Comment by iSazonov** [comment]
It seems the API is already ported to .Net Core and present in WCP https://github.com/dotnet/corefx/issues/3906

**Comment by TravisEz13** [comment]
Specifically https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter

**Comment by iSazonov** [comment]
I fast review the CoreFX code - it seems it implement only a counter reader but not file (blg) reader/writer. This is enough for `Get-Counter` but not for `Import/Export-Counter`.
We should make a request in CoreFX if we want `System.Diagnostics.Eventing.Reader` and etc.

**Comment by bill-long** [comment]
Is this being considered for Powershell 7? I noticed Get-Counter still doesn't work in the preview.

**Comment by TravisEz13** [comment]
@bill-long I think our current thought is to get the Windows Inbox module to work.  It currently works but has a naming conflict with with a PowerShell 7 module (also meaning both modules cannot be loaded at the same time).  We considering a solution that resolves the naming conflict.
