### ISSUE TITLE
PowerShell fails to install on Debian-9

### ISSUE THREAD

**Issue by KirkMunro** [PowerShell/PowerShell#4320]
Steps to reproduce
------------------
Try installing PowerShell on Debian-9 using the instructions for Debian-8.

Expected behavior
-----------------
Not sure. :) I just wanted to draw attention to the fact that it doesn't install, in case you hadn't gotten around to testing it yet.

Actual behavior
---------------
```none
The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.0 but it is not installable
              Depends: libicu52 bit it is not installable
```
For libssl, Debian stretch has libssl1.0.2 installed. I'm not sure about the other library though.

Environment data
----------------
```none
root@myserver:/# cat /etc/debian_version
9.0
```

**Comment by andschwa** [comment]
Looks like it's `libicu57` for Debian 9.

**Comment by cobbr** [comment]
This seems to also be the case for Kali. The install instructions [here](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#kali) don't work. Missing `libicu55`, only `libicu57` is in the repos.

Installing the Ubuntu `libicu55` package works to make it install, but the PowerShell process segfaults after running for a few seconds. Also confirmed on Debian 9. The trick of installing Ubuntu `libicu55` package worked prior to beta.

**Comment by KonstMisch** [comment]
Try to pull the network cable. Not even kidding. Powershell tries to communicate with 40.114.241.141. When it finds it, it fails getting a certificate from 40.114.241.141 and libcrypt or something like that crashes.

**Comment by cobbr** [comment]
@KonstMisch Wow! That is kind of funny, but yeah I can confirm that unplugging the network cable fixes the issue for me.

**Comment by KaliszAd** [comment]
Debian 9 has libcurl3 libssl1.0.2 libunwind8 libicu57 and PowerShell needs libssl1.0.0 and libicu55 in case of the Ubuntu 16.04 LTS deb Package.

You can install this package by changing the dependencies in the deb archive like this:
https://serverfault.com/questions/250224/how-do-i-get-apt-get-to-ignore-some-dependencies#answer-383958

Just change to the version in Debian (e.g. libssl1.0.2 libicu57) and install using dpkg -i package

It is a shame, there isn't a package for Debian 9 Stretch which is now current stable branch.

**Comment by TravisEz13** [comment]
I assume you are referring to #3961

**Comment by SteveL-MSFT** [comment]
That IP address is AppInsights which is used to send startup telemetry.  You can just follow the instructions to [disable telemetry](https://github.com/powershell/powershell#telemetry) rather than pulling the network cable.

**Comment by lgomezgonz** [comment]
Just edit your apt sources:

cat /etc/apt/sources.list.d/microsoft.list
deb [arch=amd64] https://packages.microsoft.com/debian/stretch/prod stretch main

**Comment by MarcosCC** [comment]
And libicu60 in Debian testing...

**Comment by melezhik** [comment]
> Just edit your apt sources:
> cat /etc/apt/sources.list.d/microsoft.list
> deb [arch=amd64] https://packages.microsoft.com/debian/stretch/prod stretch main

that does not help, the same issue on debian9

**Comment by iSazonov** [comment]
@melezhik Please open new issue with repo steps.

**Comment by stadub** [comment]
Have been facing the same problem.
And even tried to install manually disabling the dependencies(this approach makes PowerShell works 
 but makes apt-get not usable😊)
After some research found out that  the  Debian 9 repos don't include  libicu57 

so the next solution worked for me:
```
sudo add-apt-repository "deb http://ftp.de.debian.org/debian stretch main"
sudo apt-get update

sudo apt install powershell
```

**Comment by arcotek-ltd** [comment]
I'm unable to get PS 7.0.2 to 'install' in my container's Dockerfile, based on Debian 9. I've tried @stadub 's suggestion, and one from: https://github.com/WhitewaterFoundry/Pengwin/issues/502

```
The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.2 but it is not installable
              Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

## Dockerfile snippet
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# Add repository for missing dependencies
#&& add-apt-repository "deb http://ftp.de.debian.org/debian stretch main" \
&& add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main" \
&& apt-get update \
```

Any other ideas, please?

T. I. A.

**Comment by iSazonov** [comment]
@arcotek-ltd Do you follow https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md#debian-9?

**Comment by michaelsync** [comment]
@iSazonov  Yes. It doesn't work. 

```root@8179a:/# sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libssl1.0.0 but it is not installable
              Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

My OS is debian:buster-slim.

**Comment by iSazonov** [comment]
@michaelsync Do you follow the note?
> [!NOTE] The dpkg -i command fails with unmet dependencies. The next command, apt-get install -f resolves these issues then finishes configuring the PowerShell package.

**Comment by michaelsync** [comment]
@iSazonov Sorry. I missed that out. The issue was that I don't have those libraries pre-installed. Not sure if apt-get-install -f will install those dependenceis. 

I have used the following steps that don't require me to ```apt-get install -y powershell``` and it works for me. 

````sudo apt-get update
# install the requirements
sudo apt-get install -y \
        less \
        locales \
        ca-certificates \
        libicu63 \
        libssl1.1 \
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        liblttng-ust0 \
        libstdc++6 \
        zlib1g \
        curl

# Download the powershell '.tar.gz' archive
curl -L  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/powershell-7.1.0-linux-x64.tar.gz -o /tmp/powershell.tar.gz

# Create the target folder where powershell will be placed
sudo mkdir -p /opt/microsoft/powershell/7

# Expand powershell to the target folder
sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7

# Set execute permissions
sudo chmod +x /opt/microsoft/powershell/7/pwsh

# Create the symbolic link that points to pwsh
sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# Start PowerShell
pwsh
