### ISSUE TITLE
Import-Module error on Mac OS-10.12

### ISSUE THREAD

**Issue by sonus21** [PowerShell/PowerShell#4327]
Steps to reproduce
------------------
Install PowerShell from https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-beta.4/powershell-6.0.0-beta.4-osx.10.12-x64.pkg
>sudo powershell

```powershell
Install-Module AzureRM
Login-AzureRmAccount
```

Expected behavior
-----------------
Prompt for Login
```none

```

Actual behavior
---------------
VERBOSE: Loading module from path '/usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM/4.2.1/AzureRM.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module AzureRM.
VERBOSE: Loading module from path '/usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM/4.2.1/AzureRM.psm1'.
Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM/4.2.1/AzureRM.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/Azure.Storage/3.2.1/Azure.Storage.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.AnalysisServices/0.4.2/AzureRM.AnalysisServices.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.ApiManagement/4.2.1/AzureRM.ApiManagement.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Automation/3.2.1/AzureRM.Automation.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Backup/3.2.1/AzureRM.Backup.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Batch/3.2.1/AzureRM.Batch.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Billing/0.13.2/AzureRM.Billing.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Cdn/3.2.1/AzureRM.Cdn.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.CognitiveServices/0.8.2/AzureRM.CognitiveServices.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Compute/3.2.1/AzureRM.Compute.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Consumption/0.2.2/AzureRM.Consumption.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.ContainerRegistry/0.2.2/AzureRM.ContainerRegistry.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.DataFactories/3.2.1/AzureRM.DataFactories.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.DataLakeAnalytics/3.2.1/AzureRM.DataLakeAnalytics.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.DataLakeStore/4.2.1/AzureRM.DataLakeStore.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.DevTestLabs/3.2.1/AzureRM.DevTestLabs.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Dns/3.2.1/AzureRM.Dns.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.EventHub/0.4.2/AzureRM.EventHub.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.HDInsight/3.2.1/AzureRM.HDInsight.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Insights/3.2.1/AzureRM.Insights.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.IoTHub/2.2.1/AzureRM.IotHub.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.KeyVault/3.2.1/AzureRM.KeyVault.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.LogicApp/3.2.1/AzureRM.LogicApp.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.MachineLearning/0.15.2/AzureRM.MachineLearning.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Media/0.7.2/AzureRM.Media.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Network/4.2.1/AzureRM.Network.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.NotificationHubs/3.2.1/AzureRM.NotificationHubs.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.OperationalInsights/3.2.1/AzureRM.OperationalInsights.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.PowerBIEmbedded/3.2.1/AzureRM.PowerBIEmbedded.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.RecoveryServices/3.2.1/AzureRM.RecoveryServices.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.RecoveryServices.Backup/3.2.1/AzureRM.RecoveryServices.Backup.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.RedisCache/3.2.1/AzureRM.RedisCache.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Relay/0.2.2/AzureRM.Relay.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Resources/4.2.1/AzureRM.Resources.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Scheduler/0.15.2/AzureRM.Scheduler.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.ServerManagement/3.2.1/AzureRM.ServerManagement.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.ServiceBus/0.4.2/AzureRM.ServiceBus.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.ServiceFabric/0.2.2/AzureRM.ServiceFabric.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.SiteRecovery/4.2.1/AzureRM.SiteRecovery.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Sql/3.2.1/AzureRM.Sql.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Storage/3.2.1/AzureRM.Storage.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.StreamAnalytics/3.2.1/AzureRM.StreamAnalytics.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Tags/3.2.1/AzureRM.Tags.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.TrafficManager/3.2.1/AzureRM.TrafficManager.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.UsageAggregates/3.2.1/AzureRM.UsageAggregates.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
At /usr/local/microsoft/powershell/6.0.0-beta.4/Modules/AzureRM.Websites/3.2.1/AzureRM.Websites.psm1:15 char:3
+   Import-Module AzureRM.Profile -RequiredVersion 3.2.1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.ImportModuleCommand

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Darwin 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
@sonus21 Thanks for your report! We already have the same Issue #4090.
