### ISSUE TITLE
Remove-Item: potential v6 regression on path like Function:\Global:*

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PowerShell#4330]
Steps to reproduce
------------------

```powershell
    # works
    $null = New-Item Function:\Global:Test-Me -Value '"Test-Me1"'
    Test-Me

    # works
    Set-Item Function:\Global:Test-Me -Value '"Test-Me2"'
    Test-Me

    # works in v2-v5, fails in v6
    Remove-Item Function:\Global:Test-Me
```

Expected behavior
-----------------

`Remove-Item Function:\Global:Test-Me` removes the specified global function in v6,
like it does in v2-v5.

Actual behavior
---------------

`Remove-Item Function:\Global:Test-Me` fails in v6:

```none
    Remove-Item : The given path's format is not supported.
```

Environment data
----------------

```
    Name                           Value
    ----                           -----
    PSVersion                      6.0.0-beta
    PSEdition                      Core
    GitCommitId                    v6.0.0-beta.4
    OS                             Microsoft Windows 10.0.10586
    Platform                       Win32NT
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
    WSManStackVersion              3.0
```

**Comment by joeyaiello** [comment]
This is a real bug, but removing the `Global:` works in some cases, and it seems like a bit of an edge case.

@nightroman do you have a scenario that this is blocking? Seems a bit academic.

**Comment by nightroman** [comment]
My mocking tool creates temporary global functions.

**Comment by SteveL-MSFT** [comment]
My PR for https://github.com/PowerShell/PowerShell/pull/4866 will also address this.  However, I noticed on both Windows PowerShell 5.1 and with my private build, you would need to do:

```powershell
remove-item function:\test-me
```

To actually remove the function
