### ISSUE TITLE
$ENV:PSMODULEPATH is not set correctly for remoting

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PowerShell#4339]
JPS> diff ($env:PSModulePath -split ";") ((icm -cn . -config powershell.6.0.0-beta.4 {$env:PSM
odulePath})-split ";")

InputObject                                          SideIndicator
-----------                                          -------------
C:\Users\jsnover\Documents\WindowsPowerShell\Modules <=
C:\Program Files\WindowsPowerShell\Modules           <=
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\  <=

And that is why I can't access the bulk of the WIndows cmdlets (e.g. Get-Disk) from remoting.

**Comment by SteveL-MSFT** [comment]
Will be resolved as part of #4056 when we have final implementation
