### ISSUE TITLE
Modify Environment Variables (for example $env:PSModulePath) on Linux

### ISSUE THREAD

**Issue by rudolfvesely** [PowerShell/PowerShell#4341]
Hi all,

I think it would be great if you can change Environment Variables (accessed for example by $env:Name or Get-ChildItem env:) on Linux.

For example to set there values a new configuration file in **/etc** ?

On Windows I can change for example PSModulePath and add a custom path. The only option on Linux is to create a profile ps1 file for all users.

Thank you.

**Comment by mklement0** [comment]
Can I suggest that you change the title of your issue to reflect the fact that you're looking for PowerShell to introduce a _profile-independent_ way to _persistently_ define environment variables?

A few thoughts:

* Environment variables are by definition _shell/application-agnostic_ and are seen by _all_ descendant processes, irrespective of what shell/application create them.

* PowerShell "listens to" only _2_ environment variables, `$env:PSModulePath` being one of them.

* From what I understand, Linux environments (not all of them?) already have file `/etc/environment` as a system-wide, shell-independent mechanism for defining environment variables.

* That said, if the environment variables are truly only used by _PowerShell_, then the system-wide _PowerShell_ profile - `$profile.AllUsersAllHosts` - arguably _is_ the right place to define them.

   * This solution would also work for macOS, which doesn't have a system-wide mechanism for defining environment variables (anymore).

**Comment by danwize** [comment]
I tried setting an environment variable like this on an Ubuntu machine:
[System.Environment]::SetEnvironmentVariable('ASPNETCORE_ENVIRONMENT', 'HypervDev', [System.EnvironmentVariableTarget]::Machine)  

I was hoping this would edit the /etc/environment file to set the environment variable system wide.

**Comment by vexx32** [comment]
Unfortunately .NET Core have yet to implement a method to set environment variables in Unix systems. The documentation for those methods states that applying values to anything other than the current process is only supported on windows. :frowning_face:

**Comment by sumit84mca** [comment]
> I tried setting an environment variable like this on an Ubuntu machine: [System.Environment]::SetEnvironmentVariable('ASPNETCORE_ENVIRONMENT', 'HypervDev', [System.EnvironmentVariableTarget]::Machine)
> 
> I was hoping this would edit the /etc/environment file to set the environment variable system wide.

Is there any update on this or any work around

**Comment by vexx32** [comment]
No, you'd need to file an issue in the https://github.com/dotnet/runtime repository to request the functionality be expanded for non-Windows operating systems.

A workaround for now would be to modify the /etc/environment file manually instead.

**Comment by rbleattler** [comment]
I've written a function which can be used to accomplish this when running elevated (as `su`) as part of my xEnvironmentVariables Module. I don't know how helpful it is to anyone, but thought I'd share [Set-NixEnvironmentVariable.ps1](https://github.com/rbleattler/xEnvironmentVariables/blob/master/Private/Set-NixEnvironmentVariable.ps1). Hope this is helpful to anyone landing here looking for a solution.

**Comment by mieliespoor** [comment]
Can we re-open this as this still seem to be an issue?
