### ISSUE TITLE
Support -Breakpoint parameter to Start-Job to enable easier debugging of jobs without modifying the job script

### ISSUE THREAD

**Issue by f0rt** [PowerShell/PowerShell#4345]
Team,

It's really hard to debug background jobs since they're started in a separate process and the debugger doesn't hit the breakpoints.
Please consider the following features:
- Implement new parameter "InSameProcess" for the Start-Job cmdlet that forces it to be run in the same process
- Attach debugger to the child background job processes

Thanks,
Nedko

P.S. Note that the lack of this features makes some people avoid completely background jobs since they are hard to maintain.

**Comment by iSazonov** [comment]
@f0rt Thanks for your suggestion!

Possibly related #3000

**Comment by lzybkr** [comment]
Debugging background processes is definitely possible starting in V5 -
I see a couple of relevant blog posts in the first page of results from this [search](https://www.bing.com/search?q=powershell+debug+background+job)

**Comment by rkeithhill** [comment]
The following Scripting Guys blog post shows how to use VSCode and the PowerShell extension to attach to a process in order to debug it.  https://blogs.technet.microsoft.com/heyscriptingguy/2017/02/13/debugging-powershell-script-in-visual-studio-code-part-2/

**Comment by SteveL-MSFT** [comment]
Although the title of this [blog post](https://blogs.msdn.microsoft.com/powershell/2016/03/14/debugging-powershell-dsc-class-resources/) is about DSCResources, it applies to debugging PowerShell in any runspace

**Comment by f0rt** [comment]
Thanks for the replies. Is there a clean way to break into a Job? Set-PSBreakpoint is not working. Modifying the job script to add Wait-Debugger doesn't seem to be a developer friendly way.

**Comment by iSazonov** [comment]
@f0rt Use Debug-Job https://blogs.msdn.microsoft.com/powershell/2014/12/11/powershell-job-debugging/

**Comment by f0rt** [comment]
I'm using Debug-Job but it fails if I don't add Wait-Debugger to the job script. This means that I need to modify the script that I'm trying to debug which is not desired in some cases.

**Comment by iSazonov** [comment]
Do you say that the sample from the blog post mentioned above doesn't work?

**Comment by f0rt** [comment]
The example is working. I'm saying that debugging should not involve modifying the script under investigations(because sometimes this is not possible).

**Comment by iSazonov** [comment]
Can you show a sample script where Debug-Job failed?

**Comment by dmilov** [comment]
Hi,

I'd like to join the discussion adding an use-case for the point of f0rt. Here it is

I as a consumer of a PowerShell module, which has a function that spawns a job,
find out that the job produces wrong result for my input.
I'd like to be able to debug this  job without modifying the code of the module I use. 

Here is an example, I have

2ndPartyModule.psm1 with content

function Do-Work {
param([int]$n)
   start-job {
      for ($i =0; $i -lt 10; $i++) {
         Write-Output ($i*$n)
      }
   } | Wait-Job | Receive-Job
}

If I want to break on the "Write-Output ($i*$n)" line to debug, 

my option is to modify the code of 2ndPartyModule.psm1 adding "Set-PSBreakPoint" or "Wait-Debugger" and also adding "Debug-Job" somewhere. 

It would be great if I am able to set break point from my host process, the PS console for instance, where I have imported the module and call it. To illustrate this imagine I start the console and do the following

Import-Module .\2ndPartyModule.psm1
Set-PSBreakPoint  .\2ndPartyModule.psm1 4
Do-Work -n 7

And this automatically breaks the job at my breakpoint.

**Comment by iSazonov** [comment]
@lzybkr Could you please comment the scenario? It seems guys want that `Set-PSBreakPoint` implicitly set `Wait-Debugger` in a job.

**Comment by PaulHigin** [comment]
Jobs run in a separate process and PowerShell session.  Set-PSBreakpoint works in the current process/session.  Debug-Job attaches the remote debugger to the process/session where the job is running.  If the job is running script during the attach then the job script is stopped at the attach point.  If the job is already stopped and waiting for a debugger attach (due to a breakpoint being set or Wait-Debugger) then attaching the debugger shows the current execution point.

As you mention PowerShell script can be stopped in the debugger in one of two ways:
```powershell
Set-PSBreakpoint   # cmdlet when called in the job process/session
Wait-Debugger      # cmdlet when inserted into the job script
```
You can set script breakpoints in a job before you run any script files in the job to get the job to stop and wait for a debugger attach:
```powershell
PS > $job = Start-Job { Set-PSBreakpoint e:\temp\Modules\Test1.psm1 -Line 10; ipmo e:\temp\Modules\Test1.psd1; PublicFn }

PS > $job

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
11     Job11           BackgroundJob   AtBreakpoint  True            localhost             Set-PSBreakpoint e:\t...

PS > Debug-Job $job
Hit Line breakpoint on 'E:\temp\Modules\Test1\Test1.psm1:10'

At E:\temp\Modules\Test1\Test1.psm1:10 char:5
+     "Get-Processes"
+     ~~~~~~~~~~~~~~~~~
```
Or alternatively:
```powershell
PS > $job = Start-Job { ipmo E:\temp\Modules\Test1\Test1.psd1; PublicFn } -InitializationScript { $
host.Runspace.Debugger.SetDebugMode([System.Management.Automation.DebugModes]::RemoteScript); Set-PSBreakpoint E:\temp\M
odules\Test1\Test1.psm1 -line 10 }
```
We could make this easier by adding to the existing Start-Job parameter sets that allow you provide breakpoint information for the running job.  Maybe something like:
```powershell
Start-Job { c:\Scripts\MyScript.ps1 } -Breakpoints @{ ScriptFile='c:\Scripts\MyScriptModule.psm1'; Lines=10,32 }
```
```

**Comment by dmilov** [comment]
@PaulHigin Thanks for the detailed explanation!

Changing DebugMode and setting breakpoints in the initialization script is a good option I haven't thought of. 

If there is a switch parameter of the Start-Job cmdlet like "-PropagateBreakpoints" to get the breakpoints from the process that starts the job and sets them into the job's process it would be a bit more convenient.

**Comment by iSazonov** [comment]
If we'll propagate breakpoints from the parent process to a job process we get breakpoint clones in two processes.

**Comment by SteveL-MSFT** [comment]
I like the `-Breakpoints` parameter suggestion from @PaulHigin.  I'll reopen this issue and change it to a enhancement.

**Comment by lzybkr** [comment]
Does it make sense to support `Set-PSBreakpoint -Job $job ...`?

**Comment by PaulHigin** [comment]
I am not sure how useful it would be since it is impossible to know where a job is running a script and so difficult to know where to set breakpoints.  In a way this is already supported because Debug-Job stops the running script at the next execution point and attaches the debugger.  You can then see where the script is executing and set breakpoints more intelligently.

**Comment by t-tsvetkov** [comment]
It will be really valuable to add support for debugging scripts running in separate PowerShell jobs without having to modify the source script.

I did some testing with the suggested approach and it seems to work only when the breakpoint is set in a separate file, i.e. I am unable to set a breakpoint on a particular line of the job's script itself. 

Here is the sample script file:

```
function Do-Work {   
    $script = {
        # PowerShell is unable to debug the job unless an explicit Wait-Debugger command is specified inside the job.
        # Changing the debug mode and setting session breakpoints in the job initialization script has no effect.
        # Also, the $MyInvocation.ScriptName, and $MyInvocation.PSCommandPath properties are empty 
        # inside the executed job, which is probably causing the observed behavior.
        
        # Wait-Debugger

        $MyInvocation | fl

        Write-Host "Running job..."   
        for ($i =1; $i -le 5; $i++) {
            Write-Host ($i)
        }
    }

    $initDebugModeScript = {        
        $host.Runspace.Debugger.SetDebugMode([System.Management.Automation.DebugModes]::RemoteScript);
        Set-PSBreakpoint -Script <This file> -Line 14    
    }         
                       
    $job = Start-Job -ScriptBlock $script -InitializationScript $initDebugModeScript
    
    Wait-Debugger
    Debug-Job -Job $job
    Receive-Job -Job $job       
}

Do-Work
```

Most of our standalone jobs run longer scripts and it is typical that you need to set a breakpoint somewhere in the middle of the script, e.g. before a particular command. Extracting the job's script to a separate file (either statically or implicitly at run time)  is not always an option.

It seems that PowerShell is currently unable to transfer location information for the scriptblock object that is passed to the new job. However, setting breakpoints inside script blocks in the same session works perfectly fine.

[Debug_Inline_Job.ps1.txt](https://github.com/PowerShell/PowerShell/files/1234146/Debug_Inline_Job.ps1.txt)

**Comment by PaulHigin** [comment]
PowerShell doesn't support line breakpoints in script blocks.  This is a known weakness (#3000) and shouldn't be that difficult to fix.  A workaround is to use command or variable breakpoints for the script block.

**Comment by mklement0** [comment]
I like the flexibility of `-Breakpoints` (though it should probably be singular (`-Breakpoint`)), but I'd love to also see a `-WaitDebugger` switch that simplifies the following common use case:

* Launch the job.
* Have it wait for a debugger to attach right away, before doing any work.

In other words: it would be like an implicit `Wait-Debugger` call as the 1st line of the background script.
