### ISSUE TITLE
SSH between Windows system is very slow using PowerShell or cmd console

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4346]
Connecting from Windows and/or Windows Bash Console. I'm getting a very slow response when connecting to another Windows machine using SSH.  There's a delay when the cursor is processing the command.

Steps to reproduce
------------------

```powershell
ssh username@ubunsystem
```

Expected behavior
-----------------
No screen delays
```none

```

Actual behavior
---------------
Screen delays, slow performance
```none

```

Environment data
----------------
Windows 10 Pro Insider Build 16241
Win32 OpenSSH (Universal Installer) 0.0.18.0
Ubuntu 16.04.2
PowerShell 6 Beta 4
.Net Core 2.0 Preview2

In Linux
```powershell
PS /home/maxt> $PSVersionTable                                                                                                                                     
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Linux 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
In Windows:
```
PS C:\Program Files\PowerShell\6.0.0-beta.4> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.16241
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

![winssh2ubun_01_2017-07-26_8-23-45](https://user-images.githubusercontent.com/19892435/28621816-344bac8e-71e0-11e7-9535-dc4498cdb61f.jpg)

![winssh2ubun_02_2017-07-26_8-23-45](https://user-images.githubusercontent.com/19892435/28621821-3a43d846-71e0-11e7-9998-f847ad52ec09.jpg)

**Comment by SteveL-MSFT** [comment]
Is it still an issue if you `rmo psreadline`?

**Comment by MaximoTrinidad** [comment]
@SteveL-MSFT 

Apparently, when connecting Windows-Windows using SSH seems very sluggish.  The session starts in DOS command shell, and the typing PowerShell, Version 5.1 opens.  Even when changing directories to PowerShell Core Beta 4 and running ``` rmo psreadline ``` doesn't fix the problem.

I can still see the moving side-to-side when executing the any command.

**Comment by joeyaiello** [comment]
@MaximoTrinidad: would you mind trying this cmd <-> cmd? I'm not sure that this has anything to do with PowerShell...

**Comment by marcosnils** [comment]
@joeyaiello what's the command?. I'm experiencing something similar here

**Comment by MathiasMagnus** [comment]
I have a very similar experience.

I use Powershell

- On my Win10 box natively
- Inside WSL, still from the Windows console
- Through SSH on remote Ubuntu Server boxes
- SSH-ing to the same Ubuntu servers using [Token2Shell/MD](https://www.microsoft.com/en-us/store/p/token2shell-md/9nblggh2ncx9)

When using it on WSL and through SSH, it's terribly choppy. The cursor is visibly jumping back and forth on its line when coloring changes (first word of the command is colored yellow), or even if I type fast enough, garbage characters appear mid-line and the cursor jumps one line down... it's as if the entire line would be redrawn but VERY slowly. No human being can type faster than one char per few tens of milliseconds, and it really should not take that long to put a character on the screen.

Currently this is one the last standing reasons why it's not my default shell on any linux box.

**Comment by SteveL-MSFT** [comment]
@MathiasMagnus try `remove-module psreadline` to see if that improves the experience from a performance perspective.  A new version of PSReadline is coming that should address some of this.

**Comment by MathiasMagnus** [comment]
@SteveL-MSFT I did as you suggested and it did help performance wise. With psreadline removed in WSL it worked like a charm. (Minus the fact that there was no tab completion, and generally nothing that psreadline does.) When I tried to do the same through SSH (again into WSL to avoid connection issues), powershell with psreadline is totally unusable.

```
PS C:\Users\Matty> ssh -p 2222 mnagy@localhost
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-43-Microsoft x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Oct 18 09:57:42 DST 2017

  System load:    0.52      Memory usage: 45%   Processes:       9
  Usage of /home: unknown   Swap usage:   0%    Users logged in: 0

  => There were exceptions while processing one or more plugins. See
     /var/log/landscape/sysinfo.log for more information.

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 csomag frissíthető.
0 frissítés biztonsági frissítés.


Last login: Wed Oct 18 09:54:00 2017 from ::1
mnagy@MATTY-Z50-75:~$ powershell
PowerShell v6.0.0-beta.8
Copyright (C) Microsoft Corporation. All rights reserved.


PS /home/mnagy>                                                                                                         
PS /home/mnagy> r                                                                                                       
PS /home/mnagy> re                                                                                                      
PS /home/mnagy> rem                                                                                                     
PS /home/mnagy> remo                                                                                                    
PS /home/mnagy> remov                                                                                                   
PS /home/mnagy> remove                                                                                                  
PS /home/mnagy> remove-                                                                                                 
PS /home/mnagy> remove-m                                                                                                
PS /home/mnagy> remove-mo                                                                                               
PS /home/mnagy> remove-mod                                                                                              
PS /home/mnagy> remove-modu                                                                                             
PS /home/mnagy> remove-modul                                                                                            
PS /home/mnagy> remove-module                                                                                           
PS /home/mnagy> remove-module                                                                                           
PS /home/mnagy> remove-module p                                                                                         
PS /home/mnagy> remove-module ps                                                                                        
PS /home/mnagy> remove-module psr                                                                                       
PS /home/mnagy> remove-module psre                                                                                      
PS /home/mnagy> remove-module psrea                                                                                     
PS /home/mnagy> remove-module psread                                                                                    
PS /home/mnagy> remove-module psreadl                                                                                   
PS /home/mnagy> remove-module psreadli                                                                                  
PS /home/mnagy> remove-module psreadlin                                                                                 
PS /home/mnagy> remove-module psreadline
```

After this, things get messed up in a different way. Typing on the console garbles the actual line in strange ways. It does resemble things that I typed, but not quite.

That having said, I wanted to investigate more. I was using ssh.exe that ships with the Git installation of Visual Studio (why install another one, if that works? It's under `VSROOT\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\usr\bin\ssh.exe`) I wanted to try the OpenSSH-Win32 executable (v0.0.19), because I know that acts weird in other ways. With that the cursor still jumps like crazy with psreadline enabled, but works more or less. (Hard to type fast enough to ruin the actual line, coloring works...) Disabling psreadline removes coloring and cursor jumping. This SSH client however does not relay cursor buttons properly (among others), so I cannot walk the history or move the cursor in VIM. (SSH that ships with 'Git for Windows' does not work either)

Does anyone have an SSH client that relays AltGr+whatever, cursor buttons, Ctrl+c correctly AND works with powershell over SSH? It's not hard to test, just install a Hungarian layout for instance, turn on the onscreen keyboard and try sending AltGr+stuff, to see if you can type #&@<>[]{}\$; etc. just about everything you use for scripting and programming.

Either I don't have special chars, or powershell doesn't work. The choice is mine. :)

**Comment by MathiasMagnus** [comment]
@Steve-Lee Corrections: For future reference, Win32-OpenSSH v0.0.22 with PowerShell v6.0.0-beta.8 works with all features. AltGr+stuff, Ctrl+c, arrow buttons, and psreadline performs fast enough for practical use. (Cursor still visibly jumps around, but output is correct.)

When will the new psreadline hit? (Just to know when might the cursor hiccups be fixed.)
