### ISSUE TITLE
CLI: -STA and -MTA are mistaken for a -File parameter value

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4350]
Note: `-STA` and `-MTA` are not supported in Core, but for consistency with Windows PowerShell, they should still be _recognized_, and either an error or a warning should be reported.

[Here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs#L715) you can see that checking for `-STA` and `-MTA` is simply _bypassed_ in Core.

Steps to reproduce
------------------

```powershell
powershell -sta
```

Expected behavior
-----------------

An error or a warning about how `-STA` and `-MTA` are not supported in PowerShell Core.

Actual behavior
---------------

`-sta` is misinterpreted as an (implied) `-File` parameter value; an error message is reported, and the session is exited.

```none
The argument '-sta' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.4 on macOS 10.12.5
PowerShell Core v6.0.0-beta.4 on Ubuntu 16.04.2 LTS
PowerShell Core v6.0.0-beta.4 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by SteveL-MSFT** [comment]
Agree that we should error out so that existing Windows PowerShell scripts fail more gracefully
