### ISSUE TITLE
CLI: Ambiguous parameter names such as -no are misinterpreted as positional parameter values

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4351]
Steps to reproduce
------------------

```powershell
# -no is ambiguous: could be -NoProfile, -NoLogo, ...
powershell -no -command get-date
```

Expected behavior
-----------------

An error complaining about the ambiguity of the parameter name and refusal to continue.

Actual behavior
---------------

PS Core and Windows PS behave differently, due to the recent Core change to default to `-File` instead of `-Command`:

* PowerShell Core:

```none
The argument '-no' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
PowerShell v6.0.0-beta.4
Copyright (C) Microsoft Corporation. All rights reserved.
```

* Windows PowerShell:

```none
-no : The term '-no' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ -no -command get-date
+ ~~~
    + CategoryInfo          : ObjectNotFound: (-no:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.4 on macOS 10.12.5
PowerShell Core v6.0.0-beta.4 on Ubuntu 16.04.2 LTS
PowerShell Core v6.0.0-beta.4 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.413 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by SteveL-MSFT** [comment]
`-no` might be a valid script file, so I don't think we want check against ambiguous intended parameters (`-Command` didn't do this either).  However, we can improve the error message.  How about:

```
-no : The term `-no` is not recognized as a valid script file.  Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
```

**Comment by mklement0** [comment]
@SteveL-MSFT:

For consistency and predictability, you should never assume that `-`-prefixed tokens are parameter _values_, _unless_ they follow a recognized, unambiguous parameter name (such as `-NoProfile`):

* If a _positional_ token _looks like_ a parameter name - i.e., if it starts with `-` followed by a _letter_ -  it should be interpreted as such.
* If that parameter name is not recognized / cannot be resolved unambiguously, an error should occur, just as would happen _inside_ PowerShell with something like `get-item -f *.txt` (`Get-Item : Parameter cannot be processed because the parameter name 'f' is ambiguous. Possible matches include: -Filter -Force.`).

If it a positional parameter value happens to start with `-` (e.g., a script file named `-no`), the explicit parameter name must be used to disambiguate: `-File -no`.

**Comment by mklement0** [comment]
@SteveL-MSFT: I just realized that even PowerShell's _internal_ parameter parsing has inconsistencies - see #4576

**Comment by SteveL-MSFT** [comment]
I have a change that I think addresses your valid concern:

```powershell
PS> .\powershell.exe -no -file foo
Invalid argument '-no', did you mean:

        -nologo
        -noexit
        -noprofile
        -noninteractive
```

Need to add tests
