### ISSUE TITLE
Remove annoying corporate copyright header

### ISSUE THREAD

**Issue by loxal** [PowerShell/PowerShell#4352]
![capture](https://user-images.githubusercontent.com/87507/28644902-b15f5448-725b-11e7-98b4-928d4a2c0ec7.PNG)

...seeing this, every time a terminal starts, is really annoying, isn't it? I mean I do not see Richard Stallman's GNU copyright header every time the Linux Bash starts. Microsoft is trying to become more open and it worked in many areas already quite well, so get rid of your old habits in more areas ;) 

I know that `/nologo` helps to get rid of this corporate blob but this cannot be the only solution.

**Comment by SteveL-MSFT** [comment]
cc @joeyaiello you want to follow-up on this?

**Comment by iSazonov** [comment]
Related PRs #1738 and #1704

**Comment by neuhaus** [comment]
As mentioned in the PR: 

Tell your lawyers that Notepad.exe doesn't show me a copyright notice on every launch either.

Add a `--copyright` option that will give me all the legalese i would ever want (and more!) but get it out of the view in normal use, where it is in the way. Screen estate is previous.

**Comment by ThomasNieto** [comment]
@StevenBucher98 can this be closed since copyright notice was removed?
