### ISSUE TITLE
Determine *-PSSession and *-PSSessionConfiguration Cmdlet Support Via OMI

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#4355]
These cmdlets are included in non-Windows platforms, but are they supported?

``` powershell
Connect-PSSession
Disable-PSSessionConfiguration
Disconnect-PSSession
Enable-PSSessionConfiguration
Get-PSSessionCapability
Get-PSSessionConfiguration
New-PSSessionConfigurationFile
New-PSSessionOption
Receive-PSSession
Register-PSSessionConfiguration
Set-PSSessionConfiguration
Test-PSSessionConfigurationFile
Unregister-PSSessionConfiguration
```

If they are not supported, they should be removed from [here](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/InitialSessionState.cs#L5952)

Environment data
----------------
v6.0.0-beta.3

**Comment by SteveL-MSFT** [comment]
I don't believe OMI supports the same configuration xml required for these cmdlets to work.  We should remove them from non-Windows until have a PSSessionConfiguration+SSH story

**Comment by iSazonov** [comment]
If we want _temporary_ block the cmdlets on Unix until we port them I believe it is better don't remove them but add NotImplementedException. It is more easy to track and better inform users that the cmdlets will be ported later.
