### ISSUE TITLE
Get-Verb should list alias prefixes too (extend System.Management.Automation.VerbInfo)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4372]
<sup>Related documentation issue: https://github.com/PowerShell/PowerShell-Docs/issues/1480</sup>

`Get-Help` helpfully lists the verb names and the group they fall into.

However, it doesn't list the - also standardized - **alias prefix** associated with each verb, such as `g` for `Get` and `ip` for `Import`, as defined in [Approved Verbs for Windows PowerShell Commands](https://technet.microsoft.com/en-us/library/ms714428(v=vs.85).aspx).

Having these aliases readily available for reference would help establish a common, consistent language for _aliases_ too, which in the long run would hopefully make people move away from the hotly debated _legacy_ aliases.

It looks like all that is needed is to an `.AliasPrefix` property to type `[System.Management.Automation.VerbInfo]`.

Current behavior
------------------

```powershell
> Get-Verb | Select-Object -First 3

Verb  Group 
----  ----- 
Add   Common
Clear Common
Close Common
```

Desired behavior
-----------------

```powershell
> Get-Verb | Select-Object -First 3

Verb  Group Alias Prefix
----  ----- ---------
Add   Common a
Clear Common cl
Close Common cs
```

For easy reference, here's the current mapping (without group) information:

```none
Add (a)
Approve (ap)
Assert (as)
Backup (ba)
Block (bl)
Checkpoint (ch)
Clear (cl)
Close (cs)
Compare (cr)
Complete (cp)
Compress (cm)
Confirm (cn)
Connect (cc)
Convert (cv)
ConvertFrom (cf)
ConvertTo (ct)
Copy (cp)
Debug (db)
Deny (dn)
Disable (d)
Disconnect (dc)
Dismount (dm)
Edit (ed)
Enable (e)
Enter (et)
Exit (ex)
Expand (en)
Export (ep)
Find (fd)
Format (f)
Get (g)
Grant (gr)
Group (gp)
Hide (h)
Import (ip)
Initialize (in)
Install (is)
Invoke (i)
Join (j)
Limit (l)
Lock (lk)
Measure (ms)
Merge (mg)
Mount (mt)
Move (m)
New (n)
Open (op)
Out (o)
Ping (pi)
Protect (pt)
Publish (pb)
Push (pu)
Read (rd)
Receive (rc)
Redo (re)
Register (rg)
Remove (r)
Rename (rn)
Repair (rp)
Request (rq)
Reset (rs)
Resolve (rv)
Restart (rt)
Restore (rr)
Resume (ru)
Revoke (rk)
Save (sv)
Search (sr)
Select (sc)
Send (sd)
Set (s)
Show (sh)
Skip (sk)
Split (sl)
Start (sa)
Step (st)
Stop (sp)
Submit (sb)
Suspend (ss)
Switch (sw)
Sync (sy)
Test (t)
Trace (tr)
Unblock (ul)
Undo (un)
Uninstall (us)
Unlock (uk)
Unprotect (up)
Unpublish (ub)
Unregister (ur)
Update (ud)
Use (u)
Wait (w)
Watch (wc)
Write (wr)
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.4
```

**Comment by iSazonov** [comment]
Documentation is silent too.

**Comment by mklement0** [comment]
@iSazonov: Good point, thanks. I've create a documentation issue and have update the initial post with a link to it.
