### ISSUE TITLE
Improper usage of $input as a function parameter is silently ignored

### ISSUE THREAD

**Issue by petrSchreiber** [PowerShell/PowerShell#4391]
As I learned the hard way today, **$input** is PowerShell [automatic variable](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_automatic_variables).

PowerShell seems to ignore obviously improper usage of the $input, leaving the programmer confused about the parameter not being propagated further.

Steps to reproduce
------------------
There are two identical (non-optimal, I admit) implementations of Ensure-Array.
They both differ only in parameter name, nothing more.
```powershell
function Ensure-ArrayA($input)
{
    $result = @()
    if ($input -is [system.array])
    {
        $result = $input
    }
    else
    {
        $result = @($input)
    }
    return [Array]$result
}

function Ensure-ArrayB($Unknown)
{
    $result = @()
    if ($Unknown -is [system.array])
    {
        $result = $Unknown
    }
    else
    {
        $result = @($Unknown)
    }
    return [Array]$result
}

$x = Ensure-ArrayA 1
$y = Ensure-ArrayB 1

$x.Count
$y.Count
```

Expected behavior
-----------------
I would presume PowerShell would fire an exception regarding improper usage of the $input as function parameter in Ensure-ArrayA.

Actual behavior
---------------
Instead, PowerShell silently ignores this incorrect code, pretending everything is all right. Of course, using $input will result in incorrect output as consequence.

The script above will output simply:
```
0
1
```

Environment data
----------------
```powershell
> $PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.14393.1198                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14393.1198                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1 
```

**Comment by iSazonov** [comment]
@petrSchreiber Thanks for your report!

Related #3695.

/cc @jpsnover

**Comment by mklement0** [comment]
Also: #3061, which tackles the issue comprehensively.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this and agree that the parser will enforce not allowing writing to $input

**Comment by mklement0** [comment]
I'm glad to hear it, @SteveL-MSFT.

I hope that you'll consider the same for  [all other automatic variables that should be read-only too](https://github.com/PowerShell/PowerShell/issues/3061#issuecomment-300058958) - the lists needs careful vetting though, given that not all automatic variables are conceptually read-only.

**Comment by iSazonov** [comment]
`Set-Variable` can write to the variable.

**Comment by SteveL-MSFT** [comment]
@iSazonov I think the intent here is to address common usage where the user isn't aware that the variable they are using could be clobbered by PowerShell.  `Set-Variable` doesn't seem like it would fall under this, but I'm not opposed to special casing it in that cmdlet.

**Comment by mklement0** [comment]
See [this documentation issue](https://github.com/PowerShell/PowerShell-Docs/issues/1510) for the necessary attendant change to the documentation.

**Comment by SteveL-MSFT** [comment]
Although a breaking change, I think we can address this in 6.1.0

**Comment by petrSchreiber** [comment]
Dear Microsoft,

it seems the issue persists even in the latest version, could you have a look?
![image](https://github.com/PowerShell/PowerShell/assets/8292220/990b8a6d-071b-4312-91b1-759a65d2e496)
