### ISSUE TITLE
Data propagation problem for msol objects and Exchange objects

### ISSUE THREAD

**Issue by buzznut** [PowerShell/PowerShell#4434]
PowerShell control of O365 User/Contact/Group object's data is not propagated. For example using set-msoluser to set the user's title works to set the msol object. If I fetch the same user (using the ExternalDirectoryObjectId) with get-user, the title never shows up. This same behavior happens if I initially set a property value with the Office portal UI, I see the change on the msol object but never on the get-user object. Also, if I set a user's data with set-mailuser, I never see the change in the portal UI or in the msol object. What can I do to get the data sync'd? This happens with user, contact, and group properties. The O365 test tenant is stand-alone and is not dir-sync'd. If the property is set when the object is created then it propagates correctly.

**Comment by iSazonov** [comment]
@StewartNutter1 Thanks for your report!

Please reformat the report to contain description, repo step, PowerShell and modules versions.

**Comment by StewartNutter1** [comment]
Current environment: PS version 4, Stand alone O365 tenant (ENTERPRISEPACK), MSOL is version 1.0

Remote session to exchange: ($credcorp is created with "new-credential")
1) $session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $credcorp -Authentication Basic -AllowRedirection
2) Import-PSSession $session
3) Connect-MsolService -Credential $credcorp

Repo steps:
1) Create a new user (filling in the domain name as appropriate) with 'new-msoluser -DisplayName "testuser" -UserPrincipalName "testuser@domain" '
2) Get the objectId of the new user with '$id = (get-msoluser -searchstring "testuser").ObjectId'
3) Get the user object from '$u = get-user -Identity $id.ToString()'. Repeat step 3 until the user object appears. This may take 1 to 5 minutes.
4) Set the title property on the user with 'set-msoluser -objectId $id -title "My Title"'
5) Get the title from '(get-user -Identity $id.ToString()).Title'. Wait for it to be set to "My Title". 

This is the problem, step 5 never happens.  You can reverse this test by setting a property with 'set-user' and then wait for the value to appear with 'get-msoluser'. This change also never propagates.

**Comment by StewartNutter1** [comment]
Sorry - hit the wrong button
