### ISSUE TITLE
AppImage build script failing

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4462]
FYI, @probonopd 

Travis CI Linux build has been failing for 5 days (since https://travis-ci.org/PowerShell/PowerShell/builds/258768719)
It's because building AppImage is failing:

Steps to reproduce
------------------
Run `start-pspackage -AppImage`
on Ubuntu 14.04

Expected behavior
-----------------

appimage.sh should work

Actual behavior
---------------

```none
tar: ./usr/bin: Cannot open: File exists
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2
+rm usr/bin/powershell
```
line 427 in appimage.sh is failing:  
 find ../*.deb -exec dpkg -x {} . \; || true

Environment data
----------------

```powershell
> $PSVersionTable

```

**Comment by probonopd** [comment]
Strange, this script has not been touched since months...https://github.com/PowerShell/PowerShell/commits/master/tools/appimage.sh

**Comment by probonopd** [comment]
Maybe adding `--force-overwrite` to the `dpkg -x` call might help?

**Comment by daxian-dbw** [comment]
The error happens when running `dpkg -x ../powershell_6.0.0-beta.8-1ubuntu1.14.04.1_amd64.deb .`
```
root@7bc6cce4fb08:/PowerShell/powershell/powershell.AppDir# dpkg -X ../powershell_6.0.0-beta.8-1ubuntu1.14.04.1_amd64.deb .
./
./usr/
./usr/bin
tar: ./usr/bin: Cannot open: File exists
./usr/share/
./usr/share/doc/
```
I will try adding `--force-overwrite`

**Comment by daxian-dbw** [comment]
Adding `--force-overwrite` doesn't solve the problem:
```
root@5680e22d76ad:/PowerShell/powershell/powershell.AppDir# dpkg -x --force-overwrite ../powershell_6.0.0-beta.8-1ubuntu1.14.04.1_amd64.deb .
tar: ./usr/bin: Cannot open: File exists
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2

root@5680e22d76ad:/PowerShell/powershell/powershell.AppDir# dpkg -x --force-overwrite-dir ../powershell_6.0.0-beta.8-1ubuntu1.14.04.1_amd64.deb .
tar: ./usr/bin: Cannot open: File exists
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2

root@5680e22d76ad:/PowerShell/powershell/powershell.AppDir# dpkg -x --force-overwrite-diverted ../powershell_6.0.0-beta.8-1ubuntu1.14.04.1_amd64.deb .
tar: ./usr/bin: Cannot open: File exists
tar: Exiting with failure status due to previous errors
dpkg-deb: error: subprocess tar returned error exit status 2
```

**Comment by probonopd** [comment]
Has the format or content of `powershell_*-1ubuntu1.14.04.1_amd64.deb` changed recently?

**Comment by daxian-dbw** [comment]
We just found the Ubuntu packages are broken -- symbolic file '/usr/bin/powershell' is missing after install. The AppImage failure might be caused by it. We are investigating.

**Comment by TravisEz13** [comment]
I filed https://github.com/PowerShell/PowerShell/issues/4480 to track what I believe is the root cause.
