### ISSUE TITLE
Add LengthOnDisk property to FileInfo for sparse files

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4485]
Sparse files are being used more often on Windows (OneDrive, GVFS) where the file is physically someone else and only filled in locally on access.  This means that the size of the file shown represents the total file size in the cloud and not the actual space taken on disk.  Add a new `SizeOnDisk` or `LengthOnDisk` property (`LengthOnDisk` is consistent with existing `Length` property, although Size sounds better...)

**Comment by PinkSerenity** [comment]
I guess it is safe to assume that a property like this does not exist yet? If so, I'd advocate for an implementation of such a feature.
