### ISSUE TITLE
Official mac build should not contain alias in the path

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#4492]
Attached to powershell `v6.0.0-beta.4` from VSCode and got this error
![image](https://user-images.githubusercontent.com/816680/28955577-92603782-789c-11e7-97dc-3a63680f43c8.png)

Notices the file path contains PII.

> When creating the packages, please ensure that the file path does not contain user names. That is, clone to /PowerShell on Unix, and C:\PowerShell for Windows. The debug symbols include the absolute path to the sources when built, so it should appear /PowerShell/src/powershell/System.Management.Automation, not /home/username/src/PowerShell/....

https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md#building-packages

The package build script should check such problems and prevent from doing an official release from home directory.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                   
----                           -----                                                                                                   
PSVersion                      6.0.0-beta                                                                                              
PSEdition                      Core                                                                                                    
GitCommitId                    v6.0.0-beta.4                                                                                           
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEA...
Platform                       Unix                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                     
SerializationVersion           1.1.0.1                                                                                                 
WSManStackVersion              3.0   
```

**Comment by daxian-dbw** [comment]
cc @TravisEz13 

This got fixed in beta.5. OSX package was produced with path `/PowerShell` for beta.5.

**Comment by SteveL-MSFT** [comment]
@vors can you verify and close this?

**Comment by TravisEz13** [comment]
I have a PR to help prevent this from happening.

**Comment by TravisEz13** [comment]
@SteveL-MSFT This should not be possible unless someone packages with `-SkipReleaseChecks` 
So, this should be closed and should not occur again.
