### ISSUE TITLE
Can't import DSC resources in dotnet core

### ISSUE THREAD

**Issue by erwinwildenburg** [PowerShell/PowerShell#4493]
When trying to build a configuration in a dotnet core application, I can't get it to import the required modules.

Running the following script in a PSCore console works but when running it in a dotnet application it can't find the module:
```
Configuration Test {
	Import-DscResource -ModuleName PolicyFileEditor
}
```

Running the following command in the dotnet core application works perfectly, so the problem seems to be limited the the dsc resources:
`Import-Module PolicyFileEditor`

Steps to reproduce
------------------

```
using (PowerShell ps = PowerShell.Create())
{
	string configScript = "Configuration Test { Import-DscResource -ModuleName PolicyFileEditor }";
	ps.AddScript(configScript);
	ps.Invoke();
}
```

Expected behavior
-----------------

The DSC module is imported

Actual behavior
---------------

```
At line:2 char:1
+ Import-DscResource -ModuleName PolicyFileEditor
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module 'PolicyFileEditor'.
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by erwinwildenburg** [comment]
The same happens with:
```
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by erwinwildenburg** [comment]
Some more additional info:

1. I need to manually set the execution policy when importing PSDesiredStateConfiguration or I get the "cannot be loaded because the execution of scripts is disabled on this system." message.

2. When running the following block I get the same error as in https://github.com/PowerShell/PowerShell/issues/2902. 
```
using (PowerShell ps = PowerShell.Create())
{
	try
	{
		ps.AddScript("Set-ExecutionPolicy Unrestricted -Scope Process -Force");
		ps.AddScript("Import-Module PSDesiredStateConfiguration");
		ps.AddScript("Get-DscResource");
		var test = ps.Invoke();

		string test2 = "lol";
	}
	catch (Exception e)
	{
		Console.WriteLine(e.Message);
	}
}
```
`Cannot find type [Microsoft.PowerShell.DesiredStateConfiguration.DscResourceInfo]: verify that the assembly containing this type is loaded.`

**Comment by SteveL-MSFT** [comment]
cc @PowerShell/area-dsc

**Comment by TravisEz13** [comment]
Can you run `get-module policyfileeditor -ListAvailable | fl *` ?

I cannot repro the issues in Beta.4 or beta.5

Although, I hit another issue when trying to run the configuration.  The module is obviously meant to only work on non-windows environments.

**Comment by TravisEz13** [comment]
filed #4570

**Comment by nitinbps** [comment]
I am able to repro this issue on Server 2012 R2 without WMF 5/5.1 installed on the machine.

**Comment by TravisEz13** [comment]
I believe this was fixed by https://github.com/PowerShell/PowerShell/pull/6225 and #4570
