### ISSUE TITLE
ssh-keygen export to PEM fails.

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#4510]
Windows 10.
OpenSSH 0.0.18.0

![image](https://user-images.githubusercontent.com/11597190/29002837-88ea1856-7a79-11e7-9d82-2a886678d78b.png)

**Comment by iSazonov** [comment]
@DarwinJS Could you please add full text description?

**Comment by iSazonov** [comment]
I believe right repo https://github.com/PowerShell/Win32-OpenSSH.
