### ISSUE TITLE
PowerShell Core Beta 5 - Linux Enter-PSSession can't connect to Windows

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PowerShell#4513]
Enter-PSSession stop working connecting Linux to Windows. Also, this error is impacting the Ubuntu Bash console badly to the point that I'm force to close the terminal session. (I will create another incident for it).

Steps to reproduce
------------------
Enter command:
```powershell
PS /home/maxt> Enter-PSSession -HostName earth2 -UserName max_t                                                         
The authenticity of host 'earth2 (10.0.0.15)' can't be established.
ECDSA key fingerprint is SHA256:R3auoG/SZpsj8oCMmlchP2JRrtf+tj9+Tr4NJgKp+hY.
Are you sure you want to continue connecting (yes/no)? yes
max_t@earth2's password: 
```

Expected behavior
-----------------
To connect to Windows 10 PowerShell Core session.

Actual behavior
---------------
Immediate error after typing password.
```none
Enter-PSSession : The background process reported an error with the following message: The SSH client session has 
ended with error message: Failed to add the host to the list of known hosts (/home/maxt/.ssh/known_hosts)..
At line:1 char:1
+ Enter-PSSession -HostName earth2 -UserName max_t
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.PowerSh 
   ell.Commands.EnterPSSessionCommand
```

Environment data
----------------
Ubuntu 16.04.3 
PowerShell Core Beta 5
OpenSSH

```powershell
PS /home/maxt> $PSVersionTable                                                                                          

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-beta                                                                              
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.0-beta.5                                                                           
OS                             Linux 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017                     
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0

```
![enterpssession_err_01](https://user-images.githubusercontent.com/19892435/29008890-eef417ec-7aeb-11e7-8960-3e633b4ac950.png)

**Comment by iSazonov** [comment]
Maybe we already have [such Issue](https://github.com/PowerShell/PowerShell/search?p=3&q=+%22Enter-PSSession%22&state=open&type=Issues&utf8=%E2%9C%93) for Enter-PSSession?

**Comment by MaximoTrinidad** [comment]
By the way.  I can connect Windows to Linux using both SSH and PowerShell Enter-PSSession command. Previously, I was able to connect Powershell Core Linux to Windows on previous Beta. 

:)

**Comment by PaulHigin** [comment]
This error is coming from SSH
```
Failed to add the host to the list of known hosts 
```
It looks like SSH is unable to write to the known_hosts file.  Check the write permissions on that file and ensure no other application has it opened.  You can also try just deleting the file and SSH will ask you again to verify the host machines to connect to.

**Comment by MaximoTrinidad** [comment]
Hi @PaulHigin,

I've already try deleting the known_hosts file with no results.  The error stills happening in Ubuntu.  But, no issues using SSH.exe (ssh max_t@earth2). 

:)

**Comment by PaulHigin** [comment]
@MaximoTrinidad  Hmm, then I am not able to repro this.  With beta 5 I am able to use PowerShell SSH remoting to connect from by Ubuntu16 machine to Windows 10 and vice versa.

It is strange that ssh.exe works correctly.  It makes me think that PowerShell is starting ssh.exe process without needed permissions.  Are you running PowerShell in any unusual way, like under a different account that doesn't have permissions to access the known_hosts file?

**Comment by MaximoTrinidad** [comment]
@PaulHigin 

Strange indeed! I'm the only user. This is a Ubuntu Desktop I've build since last July 2016.
Every time, I upgrade PowerShell Core in Ubuntu, I go for the exercise of redoing openssh-win32 on my Windows 10. This is all workgroup environment I've setup for Demo purpose. 

There has been few changes in Windows 10 such a the SSH Proxy/Broker Services which I have them turned off in order to allow ssh/ssh-agent not to compete with it. 

I mean this was working in Beta4.  I will try a few more things as it may be on the Windows 10 OpenSSh side.

:)

**Comment by iSazonov** [comment]
@PaulHigin Thanks for your comments!

Might consider using OpenSSH as library to get better manageability?

**Comment by iSazonov** [comment]
@MaximoTrinidad Could you please continue the exploration? We really need the exact steps to reproduce.

**Comment by MaximoTrinidad** [comment]
I've been using OpenSSH in Linux since the beginning of PowerShell Core Alpha.  Also, I'm constantly updating/upgrading my OS's both Linux and Windows.  

I will continue pursuing it but I'm fine tuning my presentation for SQL Saturday JAX this weekend. 
I'm not dropping this one.

Keep you posted!

:)
