### ISSUE TITLE
Start-Process -ArgumentList should accept an empty array / the null collection and interpret that as "no arguments to pass"

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4520]
`-ArgumentList` (`-Args`) currently requires that a _non-empty_ array be passed, which is inconvenient in scenarios where you want to pass arguments through, whether any were specified or not, such as via `$Args`.

An empty array or a null collection (`[System.Management.Automation.Internal.AutomationNull]::Value`) should be accepted and should be interpreted as "no arguments to pass".

Currently, passing `$Args` through in a function is cumbersome; imagine a function `wpsh` whose purpose is to invoke a Windows PowerShell window from PowerShell Core, with any arguments passed through:

```powershell
function wpsh {
  # Pass all arguments through. 
  # To do this in a single Start-Process call, you need a cumbersome workaround
  # via an aux. hashtable and splatting.
  # Ideally,  
  #    Start-Process (Get-Command powershell.exe).Path -Args $Args 
  # should work directly.
  $htArgs  = if ($Args.Count) { @{ Args = $Args } } else { @{} }
  Start-Process (Get-Command powershell.exe).Path @htArgs
}
```

Steps to reproduce
------------------

```powershell
# Or: [System.Management.Automation.Internal.AutomationNull]::Value, such as produced by `& {}`
$arguments = @()  
Start-Process code -Args $arguments
```

Expected behavior
-----------------

`code` (the Visual Studio CLI, if installed) should open / activate, with no arguments being passed.

Actual behavior
---------------

Invocation fails with the following error message:

```none
Start-Process : Cannot validate argument on parameter 'ArgumentList'.
The argument is null, empty, or an element of the argument collection contains a null value.
Supply a  collection that does not contain any null values and then try the command again.
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by iSazonov** [comment]
Is the main motivation a dynamic construction of the parameter list? Any samples?

**Comment by mklement0** [comment]
@iSazonov: It is primarily about passing `$Args` through, though allowing empty arrays can also help with dynamically constructed parameter lists; I've added an example to the initial post, based on [this real-world code](https://github.com/PowerShell/PowerShell/issues/4214#issuecomment-320761856).

**Comment by ZSkycat** [comment]
I also encountered this problem.
my code
```powershell
function RunAsAdministrator {
    $principal = [System.Security.Principal.WindowsPrincipal][System.Security.Principal.WindowsIdentity]::GetCurrent()
    $isAdministrator = $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
    if (!$isAdministrator) {
        $cmd = [System.Environment]::GetCommandLineArgs()
        Start-Process -Verb 'runas' ($cmd[0] -replace '.dll$', '.exe') $cmd[1..$cmd.Length]
        exit
    }
}
RunAsAdministrator
```
can work in `Windows Powershell`
can not work in `Powershell Core`

@iSazonov

**Comment by iSazonov** [comment]
@ZSkycat It seem is another issue. Please open Issue-Question.

**Comment by iSazonov** [comment]
@SteveL-MSFT Can you approve @mklement0 request change?

**Comment by mklement0** [comment]
@iSazonov: 

Thanks.

Re @ZSkycat's issue: it _is_ the same issue (and Windows PowerShell and PowerShell Core are therefore equally affected): if `$cmd[1..$cmd.Length]` evaluates to `$null` - i.e., if the PowerShell instance was originally invoked without any arguments - binding to `-ArgumentList` breaks.

**Comment by ZSkycat** [comment]
@iSazonov 
This is the same issue. As @mklement0  said

`Windows PowerShell` support `-ArgumentList` equal `$null`

`PowerShell Core` will throw an error
```
Start-Process : Cannot validate argument on parameter 'ArgumentList'. The argument is null, empty, or an element of the
 argument collection contains a null value. Supply a collection that does not contain any null values and then try the
command again.
```

**Comment by mklement0** [comment]
@ZSkycat: 

Yes, it is the same issue, but Windows PowerShell also doesn't support an empty array / `$null` `-ArgumentList` value: try `Start-Process notepad -ArgumentList $null`

As an aside: Unfortunately, the way `Start-Process` currently works may require additional, embedded quoting to pass arguments through.
For instance, your function would fail if the session had been invoked with something like `powershell -noexit -file "C:\Users\jdoe\t 1.ps1"`, due to the space in the filename - see #5576

**Comment by ZSkycat** [comment]
@mklement0 
I try it, you are right.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree that the change in behavior makes sense and has low risk

**Comment by BrucePay** [comment]
Hmm - looking at the code in 
    Microsoft.PowerShell.Commands.Management\commands\management\process.cs
for the parameter definition, it appears we are deliberately blocking null/empty values```
        [Parameter(Position = 1)]
        [Alias("Args")]
        [ValidateNotNullOrEmpty]
        [SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays")]
        public string[] ArgumentList { get; set; }
```
Removing the [ValidateNotNullOrEmpty] attribute should fix the problem.  This is not a breaking change per the breaking change contract description of acceptable changes:
"Any existing behavior that results in an error message generally may be changed to provide new functionality"

**Comment by SteveL-MSFT** [comment]
@BrucePay do you want to submit a PR for this?
