### ISSUE TITLE
Clarify the purpose / behavior of the Start-Process cmdlet on Unix platforms

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4521]
On Windows, the default behavior of `Start-Process` is to run a program _in a new window_, _asynchronously_.
_Console_ applications can optionally be forced to run in the _current_ console (terminal) with `-NoNewWindow`, but that is [of limited usefulness](https://github.com/PowerShell/PowerShell/issues/1543#issuecomment-320771943).

On Unix (Linux and macOS), as of PowerShell Core v6.0.0-beta.5, **`-NoNewWindow` is the _implied and unchangeable default_**: terminal (console) programs _invariably_ execute in the _current_ terminal, which is **rarely useful**:
A program asking for interactive input interferes with the current shell and/or one producing (non-redirected) output prints it _asynchronously_ to the current terminal, which can be disruptive - see #1543.

For non-interactive terminal programs, launching a _job_, e.g., by simply appending ` &` - is the superior alternative, given that it allows you to determine success and inspect the output later.

**For _synchronous_ invocations, using `-Wait` is also pointless on Unix**:

* To run a terminal-based application synchronously, just invoke it _directly_ - no need for `Start-Process`

* `-Wait` is _not_ effective with a GUI-launching CLI such as `code` for Visual Studio Code, which launches the GUI _asynchronously_, but in a manner that `Start-Process` doesn't detect.

This leaves **just the following narrow use cases for `Start-Process` on Unix**: 
 * Launching a terminal-based application asynchronously, _assuming that that application doesn't request interactive user input_ (something that _is_ supported in Bash - see below) and ideally doesn't produce (non-redirected) stdout/stderr output, as that would print asynchronously in the current terminal.
 * Launching a _GUI_ application whose CLI is _blocking_ - e.g., `gedit` - in a _non-blocking_ manner:
`Start-Process gedit`, as a light-weight, launch-it-and-forget-it alternative to `gedit &` (which invariably creates a job).

---

Is the current `Start-Process` behavior what is intended for the v6 release on Unix?

If so:

  * The documentation should clearly state its limitations.
  * Perhaps runtime warnings for pointless invocations can be implemented.

As an aside: On Windows, `Start-Process` can also open _documents_, whereas on Unix only `Invoke-Item` can do that.

**Comment by iSazonov** [comment]
I think we should improve that on Unix. We should consider to start new process in new process group too not only background process in the same process group.

**Comment by mklement0** [comment]
@iSazonov: 

I fear that that is not enough, because we would then need Bash-like _job-control_ features, such as bringing a background job back to the foreground in case it needs _interactive_ input (and 
"stopping" (suspending) it first if that happens in the _background_, and being able to send it back to the background.

Using PS jobs behind the scenes is not an option, because, as far as I know, there's no support for jobs requesting _interactive_ (non-redirected stdin) input.

Also PS jobs don't _output_ directly to the invoking terminal the way Bash jobs do by default.

P.S.: I've updated the initial post to point out that `Start-Process -Wait` too is pointless on Unix.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee discussed this, we agree that most of the time, users don't need to use `Start-Process`, however, on Unix, it does have at least one applicable use case:

`Start-Process` can start a new process without inheriting the current environment

```powershell
PS /home/steve> $env:foo = "bar"
PS /home/steve> start-process "powershell" -args '-c $env:foo'                                                                                 
PS /home/steve> bar

PS /home/steve> start-process "powershell" -args '-c $env:foo' -UseNewEnvironment
```

So we plan to leave it.

**Comment by mklement0** [comment]
@SteveL-MSFT:

Good point about `-UseNewEnvironment`, but note that its current implementation is virtually useless - see #4671

Also,  your example only makes sense with `-Wait` (the only reason that you didn't see a problem is that your command happened to produce no output).

To summarize the use cases for `Start-Process` on Unix:

* Launch a blocking GUI-launching CLI such as `gedit` asynchronously, launch-and-forget-it style.

* Run a _non-interactive_ CLI with a pristine environment with `-UseNewEnvironment -Wait` 

   * As stated, an _interactive_ CLI launched this way - such as new interactive `powershell` instance - competes with the calling instance for control of keyboard input.

   * Because use of `Start-Process` makes the process run outside of PowerShell's streams (by default, the process' output would print straight to the terminal), the only way to provide input / collection output is via the `-Redirect*` parameters, which requires _auxiliary files_.

**Comment by mklement0** [comment]
I've created a doc issue: https://github.com/PowerShell/PowerShell-Docs/issues/2690
