### ISSUE TITLE
Consider introducing an automatic variable such as $LASTJOB that reflects the last background job started with & (Start-Job)

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4527]
Now that postpositional `&` can be used as a Bash-like alternative to using `Start-Job` - e.g.,  
`ls &` for `Start-Job { set-location $using:PWD; ls }`  -  
perhaps an automatic variable that reflects the most recently launched job - analogous to `%%` / `$!` in `bash` - would be helpful.

`$%%` and `$!` are not valid variable names in PS, so perhaps something like `$LASTJOB` would work, analogous to `$LASTEXITCODE`.

Capturing the output explicitly with something like  `$jb = ls &` is always an option, but it is an unfamiliar practice to Unix users and generally amounts to more typing and increasing the cognitive load somewhat, given that you have to pick an appropriate variable name.

Desired behavior
------------------

```powershell
# Launch a background job (without capturing the 
# [System.Management.Automation.PSRemotingJob] instance being output).
ls &

# Obtain the output from the most recently launched job, via the
# [System.Management.Automation.PSRemotingJob] instance stored in automatic variable $LASTJOB.
Receive-Job $LASTJOB -Wait -AutoRemove
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5
```

**Comment by iSazonov** [comment]
We can be more flexible:
```powershell
$job = ls &
```

**Comment by mklement0** [comment]
@iSazonov: Please re-read the paragraph starting with "Capturing the output explicitly".

**Comment by iSazonov** [comment]
Sorry, I got distracted. 😄 

I like `$job = ls &` (possibly as Windows user) more than creating a new entity.

If we want `$LASTJOB` it should be `$PSLASTJOB`

**Comment by mklement0** [comment]
:)

`$job = ls &` is definitely all that is _needed_, but my thought was that mimicking the Unix experience more comprehensively - given that the `... &` syntax is a nod to POSIX-like shells - perhaps makes sense.

Good point about the name.

**Comment by iSazonov** [comment]
We have to look at it on the other side. Perhaps Unix-like style is not the best in terms of clarity of understanding. If we based on c# and .Net Core, maybe it's better to follow that style.

**Comment by mklement0** [comment]
I hear you, but now that I think about it, let me reframe the issue: 

Think of it as a convenience for _interactive_ use, for quickly firing off a background command.

In a _script_, `$job = ls &` is absolutely the way to go.

**Comment by iSazonov** [comment]
it is reasonable. It seems we said the same thing about `$?`.

**Comment by lzybkr** [comment]
See https://github.com/PowerShell/PowerShell-RFC/issues/27 - I think the proposal is more generally useful and address this issue as well.

**Comment by mklement0** [comment]
@lzybkr: Yes and no:

Yes, if you remember which among the recent commands happened to be the one that launched the job.

No, if you're expecting a _distinct_ variable referring to the most recently launched the most recent background job, irrespective of how many intervening commands were executed.

It's comparable to the distinction between `$?` (most recent statement - albeit _only_ the most recent) and `$LASTEXITCODE` (exit code of the most recently executed external utility, no matter how many commands ago).

The general RFC and a specific variable needn't be mutually exclusive, however:

I definitely RFC idea in principle (a few quick asides: in addition to limiting the _number_ of outputs stored, perhaps a _per-item_ size limit is needed too, to guard against something `Get-Content`-ing a 10-GB file to the console; also not sure if outputs explicitly captured in a variable are worth duplicating; I wouldn't allow customizing the names of these automatic variables - see below).

While proliferation of variables in the _user_-variable namespace is problematic - see https://github.com/PowerShell/PowerShell/issues/4394#issuecomment-321955860 - if we had a `$ps:` namespace, both the RFC variables (e.g., `$ps:LastResult`) and a `$ps:LastJob` variable could be accommodated.

A tangent on why a separate namespace is worth considering, taking a step back to look at traditional shells:

* To `cmd.exe`, not only do automatic variables live in the same namespace as user variables, _all_ variables are environment variables seen by child processes. Given that variable access is case-insensitive, not even a case-based convention allows distinguishing standard environment / automatic variables from user-defined variables.

* In the world of POSIX-like shells such as `bash`, where variable access is case-_sensitive_, the _convention_ is to reserve the "sub-namespace" of all-uppercase variables to standard environment variables and the shell's own automatic variables (such as `$BASH`). Shell variables do not become environment variables unless explicitly requested.

While POSIX-like shells at least have a convention in place, the limited features of both `cmd.exe` and POSIX-like shell cannot reliably prevent name collisions.

PowerShell, by contrast, as a shell with much more sophisticated features at its disposal, allows solving these potential name conflicts once and for all, via a reserved-for-PowerShell namespace such as `$ps:` (as mentioned, existing automatic / preference variables would have to remain the user-variable namespace for backward compatibility).
