### ISSUE TITLE
Consistent way to enable PSRemoting

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#4528]
We have internally been referring to this as the "Nano Server Scenario" aka headless, remote-only remoting activation. The idea is that we need a way to register a non-running instance of PowerShell Core with WinRM. In Nano Server, you can create a remote session (`New-PSSession`)to the instance of Windows PowerShell running on the system. Once in that session (`Enter-PSSession`), you can unzip PowerShell Core on Nano Server to make it available for use. The only way to register the new instance of PowerShell Core as a WinRM endpoint is to run `Install-PowerShellRemoting.ps1` from within the current Windows PowerShell remote session.

Enable-PSRemoting works to register the running instance of PowerShell Core with WinRM, but the script `Install-PowerShellRemoting.ps1` is the only solution to this problem. We should consider building that functionality into a new cmdlet or an existing cmdlet to make it more permanent.

Environment data
----------------
Windows
Beta.5

**Comment by mirichmo** [comment]
The script and cmdlet should produce the same configuration name, so divergence is a bug. I prefer it without the "v" as well.

**Comment by SteveL-MSFT** [comment]
For this issue, it seems we have a couple of minor things:

1. Add support for `-PowerShellHome` to `Enable-PSRemoting`, however, this makes it a bit more complicated to run on Windows IoT where you initially only have Windows PowerShell Core which won't have the updated `Enable-PSRemoting`.
2. Fix `Enable-PSRemoting` endpoint name to not contain `v`

**Comment by SteveL-MSFT** [comment]
I think what we have is sufficient, so closing this item.
