### ISSUE TITLE
Test failures in *PSSessionConfiguration tests

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PowerShell#4535]
Feature tests failing, which is causing the nightly build to fail.
Related to #2671 
Test Failures: https://ci.appveyor.com/project/PowerShell/powershell-f975h/build/tests

Steps to reproduce
------------------
Run tests with [Feature] as git commit message.

Expected behavior
-----------------
All tests pass

Actual behavior
---------------
*PSSessionConfiguration tests fail.

**Comment by mirichmo** [comment]
Fixed via #4928
