### ISSUE TITLE
Literals passed as unconstrained parameters to script blocks can result in culture-invariant default output

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4545]
Note: Unlike _string interpolation_, _default output_ is meant to be _culture-sensitive_, as the following example demonstrates:

```powershell
> [cultureinfo]::CurrentCulture = 'de-DE'; "$(1.2)"; 1.2
1.2  # culture-invariant string interpolation
1,2 # culture-sensitive default output formatting
```

Steps to reproduce
------------------

```powershell
# Switch to a culture with "," as the decimal mark, then output a [double] in 3 scenarios:
# a literal, a literal inside a script block, a *literal* passed to a script block as an *untyped* 
# parameter (plus a literal inside for comparison).
# In all 3 scenarios, the output should be culture-sensitive: 1.2 -> "1,2"
[cultureinfo]::CurrentCulture = 'de-DE'; 1.2; & { 1.2 }; & { 1.2; $Args[0] } 1.2
'---'
# Same as above, only wrapped in a script block invoked with &.
# This *nesting* of script blocks causes the problem here, but, more generally,
# wrapping the commands in a function also triggers the problem.
[cultureinfo]::CurrentCulture = 'de-DE'; & { 1.2; & { 1.2 }; & { 1.2; $Args[0] } 1.2 }
```

Expected behavior
-----------------

```none
1,2
1,2
1,2
1,2
---
1,2
1,2
1,2
1,2
```

Actual behavior
---------------

```none
1,2
1,2
1,2
---
1,2
1,2
1,2
1.2   # !! Default output of parameter-passed [double] literal not localized
```

Note that if you _explicitly_ type the parameter, the problem goes away:

```powershell
# OK, but if you were to remove [double], the problem would surface.
> [cultureinfo]::CurrentCulture = 'de-DE'; & { & { param([double]$a) 1.2; $a } 1.2 }
1,2
1,2
```

Conversely, even an untyped (unconstrained) parameter works fine if the parameter value comes from a _variable_:

```powershell
# OK, because the [double] instance is passed via a *variable*:
> [cultureinfo]::CurrentCulture = 'de-DE'; & { $val = 1.2; & { param($a) 1.2; $a } $val }
1,2
1,2
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by iSazonov** [comment]
`1.2` is a string - no convertion to number - and we get it back "as is".

**Comment by mklement0** [comment]
@iSazonov:

```powershell
> (1.2).GetType().FullName; & { $Args[0].GetType().FullName } 1.2
System.Double
System.Double
```

Source-code literals are always parsed with the invariant culture:

```powershell
> [cultureinfo]::CurrentCulture = 'de-DE'; (1.2).GetType().FullName
System.Double
```

**Comment by iSazonov** [comment]
@mklement0 It seems we see "side effect". Please use trace for analyzing:
```powershell
Set-TraceSource -Name TypeConversion -Option All -PSHost
```

**Comment by mklement0** [comment]
@iSazonov: I can't make sense of what `Set-TraceSource` is trying to tell me, but the following`Trace-Command` command again suggests that `1.2` is parsed as a `[double]`.

```powershell
> Trace-Command -pshost -Name * { Write-Output 1.2 }
...
Trying to convert argument value from System.Double to System.Management.Automation.PSObject
...
```

More generally, https://github.com/PowerShell/PowerShell/issues/2751#issuecomment-307175363 aims to describe how number literals are parsed in argument mode.


Aside from that, I see no good reason for the discrepancy in behavior between the two commands in the original post.

**Comment by lzybkr** [comment]
This is by design. When PowerShell parses a literal as a command argument, it does not know the intended use of the literal.

When the use is a string, it is important that we have the **exact** string used as the argument and that we do not go through the literal's `ToString` implementation.

Examples:
```
PS> echo 0.00001 001 0x1
0.00001
001
0x1
```

If PowerShell did not do this, you would see:
```
PS> echo 0.00001 001 0x1
1E-05
1
1
```

**Comment by mklement0** [comment]
I get that, but that wasn't the point of this issue.
Please explain the following discrepancy (a more narrowly focused reformulation of the original commands):

```powershell
> [cultureinfo]::CurrentCulture = 'de-DE'; & { $Args[0].GetType().Name; $Args[0] } 1.2
Double
1,2    # Culture-SENSITIVE representation
```

vs. 

```powershell
> [cultureinfo]::CurrentCulture = 'de-DE'; & { & { $Args[0].GetType().Name; $Args[0] } 1.2 }
Double 
1.2    # !! Culture-INVARIANT representation.
```

Note that the only difference is an _extra enclosing script block_.

**Comment by mklement0** [comment]
P.S.: Even `echo` (`Write-Output`)  doesn't _always_ behave the way you describe:

```powershell
> [cultureinfo]::CurrentCulture = 'de-DE'; Write-Output 0.0001 1.2 1e2
0,0001   # !! Culture-SENSITIVE output
1,2  # !! ditto
1e2  # passed through as-is
```

The exact rules aren't clear to me. For instance, if you added just one extra - `00.0001` or `0.0001` - you would again get an culture-invariant representation.

**Comment by lzybkr** [comment]
It looks like there is a small bug [here](https://github.com/PowerShell/PowerShell/blob/1a8563336a1a7f297c05fe06d732994f8efa8691/src/System.Management.Automation/engine/parser/Compiler.cs#L3456)

The bug is assuming the culture won't change between compilation and execution. This is a mostly reasonable assumption, fixing this might hurt performance and not fix any real customer issue.

As for the difference between adding a script block invocation - I forget exact details, but the current culture is reset for reasons I never understood. I thought it was done in the host after each command line, but it looks like it's done more often than that.

**Comment by mklement0** [comment]
@lzybkr:

Thanks. I realize I didn't really fully understand the issue until now (hopefully), so let me try to confirm my understanding:

When a literal is bound to an unconstrained parameter:

* On the one hand, it _is_ converted to a numeric type if it can be interpreted as such (`1.2` becomes a `[double]`).
* On the other hand, the intent is for its default output representation to be the literal _exactly as originally specified_.  
It is this aspect that does _not_ apply when a number literal is used in an _expression_.

Therefore, `[cultureinfo]::CurrentCulture = 'de-DE'; & { $Args[0] } 1.2` currently yielding `1,2` - a culture-_sensitive_  representation - is actually a manifestation of the bug you mention.

---

> The bug is assuming the culture won't change between compilation and execution. This is a mostly reasonable assumption, fixing this might hurt performance and not fix any real customer issue.

Understood. If it isn't fixed, I suggest documenting the behavior.

>  I forget exact details, but the current culture is reset for reasons I never understood

This sounds more worrisome and perhaps warrants further investigation. 

While the example commands are contrived, I actually ran into this in a real-world scenario:
I'm using a function called `Use-Culture` (inspired by [this oldie-but-goodie blog post](https://rkeithhill.wordpress.com/2009/10/21/windows-powershell-2-0-string-localization/) by @rkeithhill) that accepts a script block to be executed in the context of a specified culture that is temporarily switched to.

```powershell
> Use-Culture de-DE { & { $Args[0]; 1.2; [cultureinfo]::currentculture.Name } 1.2 } 
1.2   # !! Due to "culture reset" in nested script block, the original bug is *masked*
1,2   # literal: still culture-sensitive
de-DE # German culture still in effect
```

The above shows that culture isn't _categorically_ reset: the default output of a literal is still localized, and `[cultureinfo]::currentculture` still reports the specified culture.

So the questions is: In what way is the culture reset and what are the implications?

**Comment by mklement0** [comment]
For clarity I've opened two new, focused issues: #4557 and #4558
