### ISSUE TITLE
Please sign the mac installer

### ISSUE THREAD

**Issue by jackfruh** [PowerShell/PowerShell#4547]
Hi Folks, can we get signed installers for mac?

I can help with the $99 apple developer account if that's an issue.

- Jack

**Comment by iSazonov** [comment]
@jackfruh Thanks! Please describe the problems you are experiencing (scenarios).

**Comment by jackfruh** [comment]
Sure,  on OSX, applications need to be signed in order to install with default settings on OSX.

In the security settings for MacOS 10.12, on the general tab, there are options to
 "allow apps downloaded from: [] App Store, [] App Store and identified developers"
(Signing is what makes the difference between identified and unidentified)

Without Signing, OSX will refuse to install the item:
![2017-08-10_23-01-29](https://user-images.githubusercontent.com/334880/29201009-e73eaa76-7e1f-11e7-80dc-12556193f7a2.jpg)

There is a workaround, but it's often disabled on corporate and government managed devices.

Generally speaking, all mac apps are signed which ties the app back to a developer or company.
This signing process helps the user know that the software they are downloading hasn't been tampered with, and adds peace of mind knowing that if malware is ever associated with any signed software, the certificate will be revoked. 

You could say signing is like a more advanced version of providing SHA256 hashes, with the added benefit of being built into the operating system, not needing user interaction to verify the signature, and offering the ability to revoke the certificate if foul play is discovered.

**Comment by iSazonov** [comment]
@jackfruh Thanks for clarify!

@TravisEz13 Could you please comment the request?

**Comment by TravisEz13** [comment]
I'll investigate.

**Comment by jackfruh** [comment]
Any update on this?

**Comment by TravisEz13** [comment]
@jackfruh the next release **should** be signed.
I close this when we know our process works.
