### ISSUE TITLE
Parameter completion should work even when #requires fails

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PowerShell#4549]
Steps to reproduce
------------------
In a non-elevated PowerShell, try to tab complete parameters to a script that looks like:

```powershell
#requires -RunAsAdministrator
param($ABC)
```

Expected behavior
-----------------
Completion works. Note that the current behavior is slightly useful as an indicator that the script won't run even after finishing the command line, but it is poor behavior in an editor that probably isn't running elevated.

Actual behavior
---------------
Completion fails silently

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.16262
Platform                       Win32NT
```

**Comment by rjmholt** [comment]
I've opened [an RFC](https://github.com/PowerShell/PowerShell-RFC/pull/122) on updating the behaviour of `#requires`. Please feel free to comment in the PR.
