### ISSUE TITLE
CustomMethod parameter does not show up in help for Invoke-RestMethod or Invoke-WebRequest

### ISSUE THREAD

**Issue by gpduck** [PowerShell/PowerShell#4559]
Steps to reproduce
------------------

```powershell
Get-Help Invoke-RestMethod

Get-Help Invoke-RestMethod -Parameter CustomMethod
```

Expected behavior
-----------------
Displays help for both StandardMethod and CustomMethod parameter sets.

Also displays parameter help for the CustomMethod parameter.

Actual behavior
---------------
Only the StandardMethod parameter set.  Throws an error when -Parameter CustomMethod is used.
```none
Get-Help : No parameter matches criteria CustomMethod.
At line:55 char:5
+     Get-Help @PSBoundParameters | more
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (System.Manageme...CommandHelpInfo:ProviderCommandHelpInfo) [Get-Help],
    PSArgumentException
    + FullyQualifiedErrorId : NoParmsFound,Microsoft.PowerShell.Commands.GetHelpCommand
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment]
Looks like it's because `-CustomMethod` isn't in the [updateable help documentation](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md)

**Comment by markekraus** [comment]
`-SkipCertificateCheck` is also missing from both.

`-FollowRelLink` is missing from `Invoke-RestMethod`

**Comment by thezim** [comment]
PR submitted - https://github.com/PowerShell/PowerShell-Docs/pull/1663

**Comment by thezim** [comment]
PR merged, this can be closed.
