### ISSUE TITLE
Docker build: Include server module ActiveDirectory, MSOnline, Azure...

### ISSUE THREAD

**Issue by juju4** [PowerShell/PowerShell#4564]
Currently docker container lacks module to interact with Microsoft world.
Any way to have them or in the plan?

Thanks

Steps to reproduce
------------------
Use Microsoft Powershell in Docker from
https://hub.docker.com/r/microsoft/powershell/

and trying above Module

```powershell
$ docker run -it microsoft/powershell powershell
PS /> Import-Module ActiveDirectory
PS /> Import-Module MSOnline
# V2
PS /> Install-Module AzureAD

```

Expected behavior
-----------------
load without error

Actual behavior
---------------
not loaded because no valid module file was found

Environment data
----------------

```powershell
> $PSVersionTable
PSVersion: 6.0.0-beta
PSEdition:: Core
GitCommitId: V6.0.0-beta.5

```

**Comment by SteveL-MSFT** [comment]
ActiveDirectory is not supported on PSCore6 since it's implemented as a PSSnapIn which is not supported on PSCore6.  In general, for any modules not owned by the PowerShell Team, you should ask those teams (generally they have a UserVoice page) to publish PSCore6 compatible modules on PSGallery then you can install them from within the docker image.  There aren't plans to add more images for specific modules.

**Comment by monokal** [comment]
Is this still the case? PowerShell is only so useful (over Python, etc) without what I would expect to be core modules like ActiveDirectory.

**Comment by SteveL-MSFT** [comment]
@monokal We worked with the AD team to fix their module so that it works with PSCore6.1+, however it requires the latest version of their module that ships in Windows.  I don't think we want to maintain a large set of images that have different combinations of modules.  Would be better to give the feedback to the AD team to produce such an image.

**Comment by monokal** [comment]
@SteveL-MSFT How would you suggest installing the module, if it is a module? It's not available from powershellgallery.com so I don't see a way of installing it inside a container.

**Comment by SteveL-MSFT** [comment]
@monokal Unfortunately, AD module currently only ships with Windows and I don't believe that team has any plans to ship it on PSGallery even though we told them there is customer demand for it.  It's much stronger for them to hear it directly from customers than from the PowerShell team.

**Comment by spanarek** [comment]
Try using ActiveDirectoryTools, it is worked for me....
`
PS /> Install-Module ActiveDirectoryTools                                                                                                                                                        PS /> import-Module ActiveDirectoryTools                                                                                                                                                         PS /> Get-A                                                                                                                                                                                      Get-ADComputerSite                  Get-ADGroupMembershipAddInfo        Get-ADObjectPropertyChangeInfo      Get-ADPrincipalGroupMembership      Get-Alias                           
Get-ADGroupMembers                  Get-ADGroupMembershipChangeSummary  Get-ADPrincipalDetails              Get-ADUserAccountControl  
 `

**Comment by arulrajnet** [comment]
Needed this running powershell inside container.

**Comment by gfrid** [comment]
we can install windows node and use windows docker image, it requires .net framework
but not sure what docker image to use, .net framework or core server image

**Comment by RealCoder1980** [comment]
is it resolved ? Can we use Active directory module inside container image on powershell?
