### ISSUE TITLE
DSC Configurations should work on windows

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4570]
## Repro

```powershell
configuration foo {
    service foo {
        name ='foo'
     } 
}
foo
```

Expected behavior
-----------------

should run configuration

Actual behavior
---------------

```none
WARNING: The names of some imported commands from the module 'PSDesiredStateConfiguration' include unapproved verbs
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
out-file : Could not find a part of the path 'C:\dev\null'.
At C:\program files\powershell\6.0.0-beta.5\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:1957
char:17
+ ...             New-Item -ErrorVariable mkdirError -ItemType Directory -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Additional data

PSDesiredStateConfiguration.psm1:1597 is hard coded to output to `/dev/null` which doesn't work on windows

**Comment by SteveL-MSFT** [comment]
@vors, do you know where the source is for this published module?

**Comment by SteveL-MSFT** [comment]
Cc @Indhukrishna

**Comment by vors** [comment]
don't remember too good, but there were some changes to make it work on linux from the MSOSS team.
@andschwa do you remember?

**Comment by andschwa** [comment]
It's not [this](https://github.com/PowerShell/xPSDesiredStateConfiguration) is it? Maybe @paulcallen knows?

**Comment by SteveL-MSFT** [comment]
@andschwa I see a bunch of resoureces, but not psdesiredstateconfiguration.psm1 module itself.  Despite the name, it seems that repo is something else.

**Comment by Indhukrishna** [comment]
The repo pointed to by @andschwa is the resource that is part of DSC Resource Kit and it has not much do with the PSDesiredStateConfiguration module that we are looking for
@SteveL-MSFT Should we take the PSDesiredStateConfigurarion module from the Nuget package and maintain that as the source going forward?

**Comment by SteveL-MSFT** [comment]
@Indhukrishna seems like the right thing to do, I'll work with you offline on this
