### ISSUE TITLE
Using a 2> error-stream redirection with cmdlets still records error records in $Error

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4572]
<sup>Closely related to #4002, which discusses the problem with respect to invoking _external utilities_, where it has additional side effects.</sup>

Any attempt to _redirect_ the error-output stream with `2>` causes the errors unexpectedly be recorded in the `$Error` collection _as well_.

While this could be considered [as designed](https://github.com/PowerShell/PowerShell/issues/3768#issuecomment-301909398), it may contravene user expectations, especially with `2>$null`.

Steps to reproduce
------------------

```powershell
$Error.Clear(); Get-Item /NoSuch 2>$null; $Error
```

Expected behavior
-----------------

No output.

Actual behavior
---------------

```none
Get-Item : Cannot find path '/NoSuch' because it does not exist.
...
```

That is, despite the explicit intent to _discard_ error output, it was recorded in `$Error` behind the scenes.

Similarly, redirecting to  a _file_ exhibits the same behavior.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by SteveL-MSFT** [comment]
The redirection is independent of the "running $error log".  As you know, there's several issues covering terminating/non-terminating, stderr, etc... I'm open to proposals on how to simplify our error handling story while not introducing breaking changes where possible.

**Comment by mklement0** [comment]
@SteveL-MSFT:

Please have a look at [Our Error Handling, Ourselves - time to fully understand and properly document PowerShell's error handling](https://github.com/PowerShell/PowerShell-Docs/issues/1583).
