### ISSUE TITLE
Parameter values disambiguated with their explicit parameter names should not require quoting

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4576]
In order to pass a parameter _value_ that _looks like_ a parameter _name_ you currently have to use _quoting_ - _sometimes_.

However, if you explicitly precede the value with its parameter _name_ as opposed to passing it _positionally_, no quoting should be necessary.

Especially with respect to PowerShell's CLI and all its quoting headaches, this extra quoting requirement should be reconsidered - see #4351

Steps to reproduce
------------------

```powershell
'hi'>'-t.txt'; Get-Content '-t.txt'; Get-Content -LiteralPath -t.txt
```

Expected behavior
-----------------

```none
hi
hi
```

The two `Get-Content` commands should be equivalent: 

* In the 1st case, the quoting implies that `-t.txt` is a parameter _value_ rather than a _name_. 
* In the 2nd case, the explicit use of  parameter `-LiteralPath`, which _requires_ a value, should unambiguously identify the _next_ token as the parameter _value_ - even if it starts with `-` - _whether quoted or not_.

Actual behavior
---------------

```none
hi
Get-Content : Parameter cannot be processed because the parameter name 't' is ambiguous. Possible matches include: -TotalCount -Tail.
...
```

That is, despite being preceded by `-LiteralPath`, which _requires_ a parameter value, 
 _unquoted_ `-t.txt` was _not_ interpreted as that parameter's _value_, but as another parameter _name_.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by markekraus** [comment]
I'll weight in that this is not a good idea, IMO.

For example:
```powershell
Get-Command -Module -Name Get-Help
```

With your proposal in place, looking at that command should it be interpreted as

```powershell
Get-Command -Module '-Name' -Name 'Get-Help'
````

or

```powershell
Get-Command  -Name 'Get-Help' -Module # Missing an argument for parameter 'Module'...
```

This could cause unexpected/unpredictable behavior and lead to a bad UX. This also opens a Pandora's box of exceptions like passing string parameters with subexpression operators. Strings that contain special tokens should be quoted while strings without special token can be passed without quoting as a kind of convenient syntactic sugar. Unquoted string parameters should be the exception, not the rule, IMO.

**Comment by mklement0** [comment]
@markekraus:

I get your concern, but do note:

* that there's no syntactical ambiguity: in PowerShell, a parameter either _requires_ a value or is a _switch_; so, for any given parameter name specified explicitly, it is unambiguously implied whether the next token is a parameter _value_ or a _different parameter_. 

* that even single-character `-` suffixes - where there's no obvious resemblance to a parameter name - can trigger the problem; e.g., `-n`.

* that the current behavior is _inconsistent_:

```powershell
> Write-Output -InputObject -z
-z

> Write-Output -InputObject -n
Write-Output : Missing an argument for parameter 'InputObject'. Specify a parameter of type 'System.Management.Automation.PSObject[]' and try again.
```

As you can see, `-z`, because it happens not to be the _start of_ a parameter name, is accepted as the _parameter value_.

By contrast, because `-n`  happens to be the start of `-NoEnumerate`, it is interpreted as that, and then `-InputObject` has no value, and the command _breaks_.

---

I suppose that one way to resolve the problem would be to disallow unquoted values that start with `-`, but my concern would then be PowerShell's _CLI_, where introducing such an additional quoting requirement (e.g., the need to pass a script filename `-t.ps1` _explicitly quoted_) would further aggravate the quoting headaches, e.g., when calling from `bash`:

```powershell
# Currently works.
powershell -noprofile -file -t.ps1

# Here's what the need to quote explicitly would entail:
# *2* layers of quoting: an outer layer interpreted by Bash that gets removed before
# PS is passed the value, and the inner layer for PowerShell's benefit.
powershell -noprofile -file "'-t.ps1'"
```

I guess the CLI could operate differently, but such an inconsistency is ill-advised.

**Comment by markekraus** [comment]
> that there's no syntactical ambiguity: in PowerShell, a parameter either requires a value or is a switch;

Yes and I'm suggesting this would introduce that ambiguity. In my example you could consider `Get-Help` the positional parameter for `-Name` and `-Name` as the string parameter for `-Module`. That's not what I as a user would expect. I would expect to be told I forgot to provide a value for `-Module`. Instead, I would just get nothing in return assuming I don't have a `Get-Help` command in a `-Name` module.

> I suppose that one way to resolve the problem would be to disallow unquoted values that start with `-`

If any change is made, I would say that this one is the way to go. I didn't even know `-` could begin any unquoted string value. 

As for the rest, I'm not sure that's the case unless i misunderstand you. It appears you are seeking consistency between parent shells and PowerShell syntax. Trying to make the PowerShell CLI consistent with other Shells is a bit futile.

When PowerShell is the parent shell, you already have to quote `-t.ps1`

```
PS C:\> powershell -noprofile -file -t.ps1
Processing -File '-t' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.

PS C:\> powershell -noprofile -file '-t.ps1'
# Executes the contents of -t.ps1
```

I wouldn't expect PowerShell's argument parsing to be consistent with Bash, CMD, ksh, python REPL, or other interactive CLI.

**Comment by mklement0** [comment]
> Yes and I'm suggesting this would introduce that ambiguity.

There's no ambiguity, because what I'm proposing is state-dependent, _based on the specific syntax of the command in question_:

* With a clean slate, `-Name` is unambiguously the parameter _name_.
* Once that has been recognized, given that the `-Name` parameter _requires a value_, the _next_ token is unambiguously the parameter _value_ - even if it looks like a _parameter_.

It's not that common a pattern in POSIX-like shells, but the equivalent is an _option_ with a _mandatory_ option-argument; for instance, if you want to pass a script filename to `sed` via its `-f` option, the next token is _invariably_ treated as the filename, even if it starts with `-`:

```sh
sed -f -my_script ...  # -my-script is invariably treated as the option *argument*
```

Again, in the case of `Get-Command -Module -Name Get-Help` it is obvious what the _intent_ is, but let's not forget that it is a _syntax error_ - based on a misunderstanding of how the `-Module` parameter works.

In other cases, such as in my `-n` example, the intent may be quite different, and since `-InputObject -n` is a syntactically unambiguous way to pass `-n` as a _value_ - because `-InputObject` _requires_ one - it should be treated as such.

---

```powershell
PS C:\> powershell -noprofile -file -t.ps1
```

This looks like a bug.

---

> I wouldn't expect PowerShell's argument parsing to be consistent with Bash, CMD, ksh, python REPL, or other interactive CLI.

I didn't mean other shells, I meant the consistency between PowerShell's CLI and parameter passing to cmdlets and functions:

If:

* `powershell -noprofile -file -t.ps1` works (which it should and currently does from `cmd.exe` and `bash` and, as stated, that it doesn't from _inside_ PowerShell should be considered a _bug_), 

* something like `Get-Content -LiteralPath -t.ps1` should work too.

**Comment by markekraus** [comment]
> that it doesn't from inside PowerShell should be considered a bug

I don't think so. It should be considered a difference of syntax between shells. How a shell parses arguments to pass to binary is up to that shell and there are only similarities between shells. PowerShell *as a shell* will have a different method for parsing and passing arguments to binaries then Bash, CMD, etc. that would be expected. What one shell deems an important token another may deem irrelevant. 

Internally, PowerShell is consistent:

```powershell
#Doesn't work
powershell -noprofile -file -t.ps1
Get-Content -LiteralPath -t.ps1

# Works
powershell -noprofile -file '-t.ps1'
Get-Content -LiteralPath '-t.ps1'
```

**Comment by mklement0** [comment]
The _way_ in which it fails tells us that something is amiss - the two commands fail for different reasons:

* `Get-Content -LiteralPath -t.ps1` fails, because `-t.ps1` is interpreted as a parameter _name_ (the starting point of our discussion - purely _syntactically_, given that `-`-prefixed barewords are allowed, this _should_ work).

* `powershell -noprofile -file -t.ps1` fails due to an _unrelated bug_, because, even though `-t.ps1` is interpreted as a parameter _value_ in principle, it unexpectedly considers the `.ps1` suffix a _separate argument_, and `-file` only sees filename `-t`, not `-t.ps1`

The latter, as I've just discovered, is a generic parsing bug:

(At least I see no reason why, if `-`-prefixed tokens can be barewords in principle, a `.`-prefixed suffix should cause the bareword to be split into 2 arguments.)

```powershell
# OK
> Write-Output -InputObject -t
-t

# BROKEN
> Write-Output -InputObject -t.ps1
Write-Output : A positional parameter cannot be found that accepts argument '.ps1'.
```

Essentially, PS parses `Write-Output -InputObject -t.ps1` as if `.ps1` had been passed as a _separate argument_ - `Write-Output -InputObject -t .ps1` - even though I see no good reason for that - `Write-Object -InputObject t.ps1` (value doesn't start with `-`) works just fine, for instance.

**Comment by markekraus** [comment]
Huh.. to add to the weirdness... this is totally possible...

```powershell
$Variable = 'temp'
Write-Output -t*+_*^%$variable#@!<>/?\=+-
Write-Output -InputObject -t*+_*^%$variable#@!<>/?\=+-
#output: for both:
-t*+_*^%$variable#@!<>/?\=+-
```

`(`,`)`,`'`,`"`, and `.` all break it, but any of the others, including what would normally be a variable, is treated as a literal string.

I really think the solution is to treat `-` as a reserved prefix for named parameters. I would expect 

```powershell
Write-Output -NonexistentParameter
```
to throw a `NamedParameterNotFound` exception, and I would expect

```powershell
Write-Output -InputObject -NonexistentParameter
```

To throw a `MissingArgument` exception. I definitely would not expect either to output `-NonexistentParameter` as a string.

**Comment by mklement0** [comment]
Good find re lack of expansion.

I've created #4578 to focus on the aspect of `-`-prefixed bareword parsing (and to generally ask the question whether it should be supported).

I'm with you with respect to `Write-Output -NonexistentParameter`: without a preceding, valid parameter name that requires a value, `-NonexistentParameter` should be parsed as a parameter _name_ (and in order to force interpretation as a _positional value_ the user would have to quoting; e.g.,  
`'-NonexistentParam'` or `` `-NonexistentParam ``)

I disagree with respect to `Write-Output -InputObject -NonexistentParameter` (as stated, the use of `-InputObject` unambiguously makes the following token its _value_, so `-NonexistentParam` should print, as happens now, but _inconsistently_), but #4578 will hopefully bring clarity.

**Comment by lzybkr** [comment]
Feel free to continue discussing, but I'm closing the issue because I can't see adding more complexity to the parameter binder to change this behavior.

The "workaround" is in my opinion the preferred style - use quotes.

There is no confusion to human readers.
There is no potential ambiguity for the parameter binder to deal with.
The script is future proof, adding a new parameter that might match some argument won't cause a problem.

**Comment by markekraus** [comment]
@mklement0 

> as stated, the use of `-InputObject` unambiguously makes the following token its value, so `-NonexistentParam` should print, as happens now, but inconsistently

This may be unambiguous from a code standpoint. But from a user standpoint, that would be really confusing. 

```powershell
Remove-Item -force -Path -wwhatif
Remove-Item -force -Path -whatiff
Remove-Item -force -Path -watif
````

Now my very important `-wwhatif` file is deleted. :( Maybe I was just trying to test out the command but flubbed the `-whatif` parameter. My expectation as a user would be that I should be told `-Path` is missing its value or that `-wwhatif` is not a valid paramter, not that `-wwhatif` is either deleted or not found.

**Comment by mklement0** [comment]
@markekraus: 

That's a good example, and I can see how requiring quoting ultimately makes for a user-friendlier solutions.

@lzybkr seems to agree with you, so this means that the unquoted-`-`-prefixed-bareword-as-value loophole should be closed:  #4591

For the sake of a sane _CLI_, I hope that something like `powershell -noprofile -file -t.ps1` will continue to work _from outside of PowerShell_.

**Comment by PetSerAl** [comment]
Another workaround would be to use parameter with explicit argument syntax:
```powershell
Write-Host -Object: -NoNewline
```

**Comment by mklement0** [comment]
@markekraus:

Actually, on further reflection, I do not think that something like

```powershell
Remove-Item -force -Path -wwhatif
```

is a good reason to abstain from using the definition of `-Path` determine the syntactic role of `-wwhatif`. An actual filename matching a misspelled `-WhatIf` is too obscure a scenario to drive the decision on how to properly parse such commands.

Based on the subsequent discussion in #4591, I'm now more than ever convinced that the only predictable way to handle `-`-prefixed barewords is as I've originally proposed, given the desire to retain the ability to use such barewords, in the context of `ValueFromRemainingArguments`.

Please see #4624
