### ISSUE TITLE
"-"-prefixed barewords in argument mode should always be interpreted as parameter names

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4591]
#4578 shows that you can _sometimes_ use `-`-prefixed bareword as parameter _values_ - namely only if the bareword happens not to (prefix)-match a parameter name of the target command - and when such barewords _are_ recognized as _values_, they don't behave the same way as non-`-`-prefixed barewords with respect to interpolation and being recognized as a single argument.

This inconsistency is problematic.

Given, @lzybkr's comment at https://github.com/PowerShell/PowerShell/issues/4576#issuecomment-322572999

> The "workaround" is in my opinion the preferred style - use quotes.

it seems that the desired solution is to _disallow_ `-`-prefixed barewords as _values_ and to _always_ assume that such an _unquoted_ `-`-prefixed token is a parameter _name_.

```powershell
# Currently interpreted as *value*, because no Write-Output parameter name starts with -z.
# This should no longer be supported.
> Write-Output -InputObject -z
-z

# Interpreted as *parameter name*, because -n prefix-matches parameter -NoEnumeration
> Write-Output -InputObject -n
Write-Output : Missing an argument for parameter 'InputObject'. Specify a parameter of type 'System.Management.Automation.PSObject[]' and try again.
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5
```

**Comment by lzybkr** [comment]
I believe this is very much by design.

These parameters as arguments are often parameters themselves, but they are unknown to the cmdlet accepting them.

Here is a good example:

```
PS> Get-Command -Syntax Get-ChildItem -Path cert:

Get-ChildItem [[-Path] <string[]>] [[-Filter] <string>] [-Include <string[]>] [-Exclude <string[]>] [-Recurse] [-Depth <uint32>] [-Force] [-Name] [-UseTransaction] [-CodeSigningCert] [-DocumentEncryptionCert] [-SSLServerAuthentication] [-DnsName <DnsNameRepresentation>] [-Eku <string[]>] [-ExpiringInDays <int>] [<CommonParameters>]

Get-ChildItem [[-Filter] <string>] -LiteralPath <string[]> [-Include <string[]>] [-Exclude <string[]>] [-Recurse] [-Depth <uint32>] [-Force] [-Name] [-UseTransaction] [-CodeSigningCert] [-DocumentEncryptionCert] [-SSLServerAuthentication] [-DnsName <DnsNameRepresentation>] [-Eku <string[]>] [-ExpiringInDays <int>] [<CommonParameters>]
```

`Get-Command` accepts it's parameter `ArgumentList` with `ValueFromRemainingArguments`, and in this scenario, values that look like parameters are expected. The use case here is to help determine dynamic parameters (which is why I used `cert:` to show the syntax includes the correct dynamic parameters.)

I suppose there could be a refinement to `ValueFromRemainingArguments` to specify that parameters are not arguments - that might be useful and avoid confusion in a few cases, but I'm not sure `Write-Object` is such a case as parameters are rarely named with that cmdlet.

**Comment by mklement0** [comment]
Leaving `ValueFromRemainingArguments` aside for now, which is not that common:

While `Write-Output` was not the best example, there are definitely cmdlets where this inconsistency is more likely to arise:

`Get-Item -LiteralPath -z` vs. `Get-Item -LiteralPath -p`, for instance.

That the _specific content_ of a token (beyond its lexical structure) would decide its _syntactical role_ situtationally sounds iffy to me.

**Comment by lzybkr** [comment]
For non-cmdlet binding functions or for `ValueFromRemainingArguments`, the current behavior is definitely by design. In other cases, it might be of questionable value, but the behavior is consistent and I guess easy to explain.

The parser doesn't interpret the script any differently - you can verify this by looking at the AST, so this is just a parameter binding issue.

**Comment by mklement0** [comment]
> I suppose there could be a refinement to ValueFromRemainingArguments to specify that parameters are not arguments - that might be useful and avoid confusion in a few cases

Don't get that, but let me point out how `ValueFromRemainingArguments` is confusing the way it works currently, using a less mind-bending example than `Get-Command`, namely `Join-Path` (as an aside: nothing in `Join-Path -?` tells us that `ValueFromRemainingArguments` is supported):

```powershell
# OK: non-"-"-prefixed tokens
> Join-Path a b c
a/b/c

# OK: quoted "-"-prefixed tokens.
> Join-Path '-z' '-z' '-z'
-z/-z/-z

# BROKEN: not clear what's happening here.
> Join-Path -z -z -z

cmdlet Join-Path at command pipeline position 1
Supply values for the following parameters:
Path[0]: 

```

**Comment by lzybkr** [comment]
Yeah, `ValueFromRemainingArguments` has issues, see https://github.com/PowerShell/PowerShell/pull/2038

**Comment by mklement0** [comment]
Pragmatically speaking:

* I know we're talking about edge cases.

* I know that I can avoid ambiguity by quoting.

That said, not having to quote constantly due to uncertainty over how barewords will be interpreted would be nice - after all, use of barewords is a perk of argument mode / shell-like syntax.

>  the behavior is consistent and I guess easy to explain.

I'm not trying to be flippant when I say: Please do.

I'm honestly confused at this point, so if you can give a concise, comprehensive explanation of how `-`-prefixed barewords are _meant_ to be handled in _all_ scenarios - current bugs notwithstanding -  based on rules people can actually keep in their heads, without needing to know how the parameter sausage is made, I'd _personally_ appreciate it, but, as usual, documenting it for the world at large is the right thing to do.

Also worth noting that PowerShell already has an unrelated bareword-rules complexity problem - see #3217

**Comment by mklement0** [comment]
P.S.: Let's not forget that when a `-<letter>`-prefixed bareword does make it through as a _value_, it is not expanded the same way as  non `-`-prefixed bareword, as originally discussed in #4578:

```powershell
> Join-Path a b z$HOME
a/b/zhome/jdoe

> Join-Path a b -z$HOME
a/b/-z$HOME  # no expansion
```

**Comment by mklement0** [comment]
I've taken a step back; please see #4624
