### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by joeparkerz** [PowerShell/PowerShell#4593]
Hi!

How would one update PowerShell through command line? Can it be done through cURL?

Thanks.

**Comment by SteveL-MSFT** [comment]
Depends on the OS, follow the instructions per OS in [README.md](https://github.com/PowerShell/PowerShell#get-powershell).  If Windows, there is a [installer proposal](https://github.com/PowerShell/PowerShell-RFC/pull/97) in the works and open for feedback
