### ISSUE TITLE
Add Documentation Covering the Process of Handling Comments that Will Not Be Addressed in a PR

### ISSUE THREAD

**Issue by mirichmo** [PowerShell/PowerShell#4595]
We have a policy, but it is not documented anywhere. We need to write it down for everyone to see and refer back to. 

The idea is that comments may be added to a PR that are considered non-blocking and should not hold up a pull request. We want to preserve the feedback and document it so that it may be addressed at a later time. The way to handle it is to file a new issue covering the topic and note it in the PR.

**Comment by daxian-dbw** [comment]
The recent changes in [CONTRIBUTING.md](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md) documented how to handle non-critical comments after a PR is approved:
> Non-critical late feedback (after PR has been approved) can be submitted as a new issue or new pull request from the reviewer.

Do you think we can close this issue now?
