### ISSUE TITLE
Move certificateCommon.psm1 to a Common Area and Replace Self-Signed Cert Valid for All tests

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4598]
[certificateCommon.psm1](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Security/certificateCommon.psm1) contains a self signed certificate used for tests in the `Microsoft.PowerShell.Security`. Other modules will require certificates so this test module should be moved to a common area accessible to all tests.

Additionally, the certificate  in `New-GoodCertificate` is issued for only the `Key Encipherment`, `Data Encipherment`, and `Document Encryption` key usages. This key cannot be used for tests such as certificate authentication with `Invoke-WebRequest`/`Invoke-RestMethod`. A new self-signed certificate should be issued that includes key usage for all tests that may require it to prevent the need for separate certificates and functions for each key requirement.

For more details see #4546

**Comment by iSazonov** [comment]
@adityapatwardhan Could you please comment the suggestion?

**Comment by iSazonov** [comment]
If we want one (two) reusable certificate(s) we should document their properties (usages) by means of comments in the module.

**Comment by markekraus** [comment]
The comments should probably include the following (at minimum):

* Subject
* Thumbprint
* NotBefore
* NotAfter 
* Key Usages (including Extended Key Usages)

**Comment by markekraus** [comment]
Closed by #7875
