### ISSUE TITLE
Install-Module Default Modules Path is Under Versioned PowerShell Folder

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/PowerShell#4599]
I have been running PowerShell Core under Jenkins on Linux.

While troubleshooting another problem I did a yum update and the system was pleasantly updated to beta **5** installed side-by-side to /opt/microsoft/powershell/6.0.0-beta.**5**/ . 

However, when I went to use an optional module I had installed before the update it was not found because the previous version was under /opt/microsoft/powershell/6.0.0-beta.**4**/Modules.

Install-Module appears to default to this location - but this causes automatic loss of access to installed modules when doing a simple 'yum update -y'

Specifying "-Scope AllUsers" causes an install to the same folder - so it seems PowerShell Core considers this the "allusers" location.

I think the default "install-module" behavior should be to install to /usr/local/share/powershell/Modules or a new location like /opt/microsoft/powershell/Modules.
Especially since:
* modules shouldn't go missing because PowerShell was updated.
* This seems to be an artifact of support for multiple concurrent PowerShell versions and should not interfere with defacto expected behavior for machine level installed extensions.
* The experience is unnecessarily different from the defacto expectations created by Windows PowerShell (it has no equivalent to a version specific modules folder).

If this is not an artifact, but purposely designed for version specific modules, then I would propose adding a new configuration value for -scope.

In addition, it would be helpful if "Install-Module" could take something like -InstallationFolder so that when necessary, I can have complete control and use custom locations when desired.

**Comment by michaeltlombardi** [comment]
Would it make sense for this to be handled as a scope for `Install-Module` - ie, what we're seeing now is `Install-Module -Scope Version` and what we _want_ as the default is `Install-Module -Scope Global` or `Install-Module -Scope CurrentUser`

**Comment by iSazonov** [comment]
@DarwinJS Is the issue still actual?

**Comment by iSazonov** [comment]
Close as stale issue. Feel free to continue discussion.
