### ISSUE TITLE
PSCopyToSessionHelper and PSCopyFromRemoteSession scripts should not support streams on UNIX

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell#4601]
In FileSystemProvider.cs we have scripts than handle the file copy and has parameters to support alternate streams which is only supported on NTFS on Windows (due to PInvoke usage).  This code after https://github.com/PowerShell/PowerShell/pull/4567 is merged will not be hit, but shouldn't be there to make it more clean.

**Comment by mklement0** [comment]
@SteveL-MSFT: Small typo in the title: "steams" -> "streams".

**Comment by SteveL-MSFT** [comment]
@mklement0 fixed!
