### ISSUE TITLE
Create Native Test Solution for Certificate Authentication

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4609]
## Problem

There is currently no native cross-platform, CI independent mechanism to test Certificate Authentication in `Invoke-WebRequest` and `Invoke-RestMethod`.

## Proposal

Create a docker container to house a minimal aspnetcore app to validate Client Certificate presence in calls made by `Invoke-WebRequest` and `Invoke-RestMethod`. The docker container will need a self-signed certificate, SSL/TLS configuration, and be Linux based (debian jessie?). The aspnetcore app will need to, at minimum, echo whether a Client Certificate was presented or not and possibly include details about the Client Certificate. The entire solution will need to work in both AppVeyor and Travis CI and be as CI agnostic as possible.

see #4546

**Comment by markekraus** [comment]
@TravisEz13 We can work on the solution through this issue.

**Comment by markekraus** [comment]
@TravisEz13 I think I'm on to something. the built-in Kestrel server for ASP.NET core supports client certificates. I'm working on an small app that returns the client certificate details. The idea is that the test calls `dotnet run` on the project in a `Start-Job`, does the tests, then tears it down the job. I actually have a prototype of this working in a web browser, but `Invoke-WebRequest` and `Invoke-RestMethod` can't find a common algorithm with Kestrel. It looks like I need to enable TLS in Kestrel, but the examples I have found for doing so no longer work in 2.0.

**Comment by iSazonov** [comment]
I believe we should use natively supported web server - Apache on CI Travis and IIS on CI AppVeyor. It requires more effort, but it makes our tests more predictable. I do not see the pressing need to make sure to use a port server.

**Comment by markekraus** [comment]
As an update on this, it was discovered in #4620 that Docker is not supported on macOS in Travis CI. The current approach in #4622 is to have the listener app published by `Publish-PSTestTools` like `TextExe` and then run the listener on demand using the baked in Kestrel server. This has the advantage of being much quicker.

Also, the possibility of moving all tests form HttpListener to this app is open for discussion.

**Comment by TravisEz13** [comment]
@markekraus It seems worth investigating.  I would start with feature tests and if there are any issues with the approach the impact would not be blocking.  Then if it proves a good solution, we can try broadening the approach to other tests.

**Comment by markekraus** [comment]
@TravisEz13 How should I approach PR's for this? There are a bunch of feature `it`'s for both cmdlets, how should I break them up, if at all?

**Comment by TravisEz13** [comment]
@markekraus Let's finish the current PR, then think about this if you don't mind?

**Comment by markekraus** [comment]
@TravisEz13 sure thing!

**Comment by markekraus** [comment]
in #4622 it was discovered that Client Certificate Authentication is still unavailable in macOS due to a compatibility issue between CoreFX and and macOS's implementation of curl. 

dotnet/corefx#19718

**Comment by SteveL-MSFT** [comment]
cc @JamesWTruher
