### ISSUE TITLE
Windows version crashes under Wine

### ISSUE THREAD

**Issue by staalmannen** [PowerShell/PowerShell#4619]
Tested on Arch Linux 64-bit, both 32-bit and 64-bit WINEPREFIX.

WINE version : 2.14 (staging)
PowerShell version : 6.0.0-beta5

Steps to reproduce
------------------

Install powershell in a fresh WINEPREFIX (using msiexec -i).

Expected behavior
-----------------
PowerShell should execute and run

Actual behavior
---------------
PowerShell crashes

**Comment by Mixaill** [comment]
Wine currently does not implement Kernel32!FindNLSStringEx function

https://bugs.winehq.org/show_bug.cgi?id=41911

**Comment by iSazonov** [comment]
Please clarify why you use the emulator but not native PowerShell Core for Linux?

**Comment by staalmannen** [comment]
My main reason would be to run the chocolatey package manager in wine.

**Comment by iSazonov** [comment]
Thanks for clarify! Are you agree with @Mixaill conclusion?

**Comment by staalmannen** [comment]
Yes that was a very good explanation. This should probably be seen as a Wine bug.

Thanks!

**Comment by iSazonov** [comment]
Ok, I close the Issue as external. Feel free reopen if you find anything new.

**Comment by Mixaill** [comment]
`kernel32.FindNLSStringEx` was added to wine https://source.winehq.org/git/wine.git/commit/2d74a4ff43284c35447ed2a915b0b5b3e40748f1

worth to test Wine 3.4+

**Comment by staalmannen** [comment]
Powershell works under Wine 3.4 :) Chocolatey install did not work :(
