### ISSUE TITLE
Inconsistent, unpredictable behavior of "-"-prefixed barewords in argument mode

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4624]
<sup>Follow-up to #4576 and #4591</sup>

### Context:

Note: By _bareword_ I mean a run of non-whitespace characters not single- or double-quoted as a whole (e.g., `foo`), used in argument mode, and normally interpreted as an expandable string (e.g., `$HOME/boy`).

While `-`-prefixed barewords _look_ like _parameter names_ (e.g.,`-foo`), they _sometimes_ act as _arguments_ (_values_ to bind to parameters), and the ability to use them as such is important in two contexts:

* In the context of the external CLI, when passing the name of a script file that happens to start with `-`; e.g., `powershell -File -foo.ps1`

* When passing arguments _through_ that themselves happen to be command line or command-line fragments, which is enabled by cmdlets/advanced functions that declare a `ValueFromRemainingArguments` parameter; e.g., 
`Get-Command -Syntax Get-ChildItem -Path cert:` passes `-Path cert:` through (the `-Path` bareword is _not_ interpreted as `Get-Command`'s parameter) in order to discover the certificate provider's dynamic parameters.

Note that, except when using the external CLI, you can always use _quoting_ to explicitly mark a bareword as an _argument_.

Generally, though, if there's no ambiguity, not having to quote tokens that don't strictly need it is a matter of convenience.

### The problem:

There are two major problems with how `-`-prefixed barewords are currently parsed and interpreted:

* Pragmatically speaking, **their syntactic role (parameter name vs. argument) is virtually unpredictable by the end user**. 

   * E.g., the `-a` in `Get-Item -LiteralPath -a` is an _argument_, whereas the `-c` in `Get-Item -LiteralPath -c` is _parameter name_`-Credential`.

* They are **not parsed and expanded in the same way as barewords that do _not_ start with `-`**.

   * E.g., bareword `a$HOME` expands `$HOME`, while `-a$HOME` does not.

More examples below.

### Solution options:

* Leave things as they are and _document_ the current behavior, recommending that _quoting_ be used for predictability.

* Change the parameter binding as proposed in #4576: Once a parameter has been (unambiguously) identified, its specific definition  - switch vs. parameter-with-argument- _alone_ determines whether the next token is its argument or a different parameter:

  * E.g., in `Get-Item -LiteralPath -p`, `-p` would _unambiguously_ be an _argument_, because `-LiteralPath` _syntactically requires_ an argument.

    * An argument can be made that in cases where the _user intent_ was likely different - e.g., `Get-Item -LiteralPath -Path` - that _unconditional_ interpretation of `-`-prefixed barewords as _parameter names_ is preferable in terms of the user experience (`Missing an argument for parameter 'LiteralPath'` as opposed to `Cannot find path '-Path' because it does not exist`); a point that [@markekraus has made](https://github.com/PowerShell/PowerShell/issues/4576#issuecomment-322574632).

     * That said, I think the conceptual simplicity and clarity of the let-the-identified-parameter-determine-the-next-token's-syntactic-role approach is more beneficial in the grand scheme of things.

  * Note: [@lzybkr has already discounted this option](https://github.com/PowerShell/PowerShell/issues/4576#issuecomment-322572999) based on implementation cost, but I'm resubmitting it for consideration now that we have a fuller picture of all the issues involved: 
>  I can't see adding more complexity to the parameter binder to change this behavior.

* Disallow `-`-prefixed barewords altogether, as proposed in #4591: In order for a `-`-prefixed tokens to be recognized as an _argument_, it would have to be _single- or double-quoted_ .

   * E.g., `Get-Item -LiteralPath -a` would then _break_, because `Get-Item` has no `-a*` parameter, and `Get-Item -LiteralPath '-a'` would have to used consistently. (But, in contrast, PowerShell's _outside_ CLI would still need to accept something like `-File -a`.)

   * The convenience of being able to specify `-`-prefixed tokens _as arguments_ is lost, but at least the behavior is _predictable_.

     * That said, the waters would still be muddy with respect to commands that have a `ValueFromRemainingArguments` parameter, where, based on the current behavior, a `-`-prefixed barewords _if it happens not to match a regular parameter_ would still be interpreted as an _argument_.

### Examples:

```powershell
### Virtually unpredictable syntactic role

# BREAKS
# -c, because it happens to match parameter name -Credential, is interpreted as a *parameter name*.
# Note that, purely based on -LiteralPath being a parameter that *requires an argument*, there is
# no good reason to parse -c as a parameter name. The syntax of Get-Item unambigously implies that
# the token following -LiteralPath must be an *argument*.
Get-Item -LiteralPath -c

# SUCCEEDS
# -a, because it happens not to match any of Get-Item's parameters, is interpreted as an *argument*
Get-Item -LiteralPath -a


# Even though a "-"-prefixed token as the 1st argument is normally *invariably* interpreted as 
# a *parameter name*, that is not the case for cmdlets with a ValueFromRemainingArguments parameter,
# such as Write-Output:

# BREAKS
# -n happens to match parameter (switch) -NoEnumeration, and the call is therefore missing
# arguments to output (-InputObject)
Write-Output -n
# Solution: Use -- to signal the start of all positional arguments.
Write-Output -- -n

# SUCCEEDS, because -z happens not to match a parameter name and is therefore bound to -InputObject.
Write-Output -z

### Parsing / expansion inconsistencies

# As part of an array, a "-"-prefixed bareword doesn't work as the 1st element.
Write-Output -a, b	# BREAKS
Write-Output a, -b  # SUCCEEDS


# "-"-prefixed barewords are non-expanding
Write-Output a$HOME   # expands $HOME
Write-Output -a$HOME  # doesn't expand $HOME


# A "-"-prefixed bareword containing a "."-prefixed suffix is parsed as *2* arguments
Get-Item -LiteralPath a.ps1  # SUCCEEDS
Get-Item -LiteralPath -a.ps1 # BREAKS: Get-Item receives *2* arguments: '-a' and '.ps1'
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by markekraus** [comment]
@mklement0

> But, in contrast, PowerShell's outside CLI would still need to accept something like `-File -a`.

As a point of clarity, this is not something under PowerShell's control as that is the calling shell (bash, another PowerShell, CMD, ksh, etc) has final say in the matter. What you are specifically requesting here is to maintain the current argument parsing for arguments passed from the calling shell to the PowerShell binary upon initialization. Correct?

**Comment by mklement0** [comment]
@markekraus:

> What you are specifically requesting here is to maintain the current argument parsing for arguments passed from the calling shell to the PowerShell binary upon initialization. Correct?

Correct: `powershell -File -foo.ps1` currently works already, and should continue to work.'  
(And as _one_ aspect of conceptual simplicity and consistency, that should work _predictably_ PowerShell-_internally_ as well (calling functions/cmdlets)).

Calling from a POSIX-like shell (Unix; e.g., `bash`),  `powershell -File -foo.ps1` is indistinguishable from variants `powershell -File '-foo.ps1'` and `powershell -File "-foo.ps1"`, because the POSIX-like shell performs _quote removal_ before passing the array of arguments as literals to the target command: `powershell` sees just literals `-File` and `-foo.ps1` in all cases.

Conceivably, PowerShell _could_ - but shouldn't, in my view - then place _additional_ requirements on the arguments passed, based on _its_ syntax requirement, such as for the received `-foo.ps1` argument to still be represented as `'-foo.ps1'`, for instance, _if_ 
the decision were made (I hope not) that `-`-prefixed tokens are only recognized as _arguments_ when _quoted_.

If such a requirement existed, you'd have to call `powershell -File "'-foo.ps1'"` (or `powershell -File '"-foo.ps1"'`) - and such two-unrelated-quoting-layers awkwardness is best avoided.

Unfortunately, we already have that awkwardness with respect to how `-Command` parsing works: because it assembles all arguments into a single string that it then interprets based on PowerShell rules, you do need two-layer quoting; e.g.:

```powershell
# Oops! "The string is missing the terminator: '."
# PowerShell ended up interpreting `Write-Output don't` as the script.
powershell -noprofile -command Write-Output "don't"

# OK, but clearly cumbersome:
# With *shell-variable based* arguments, it gets even tricker
powershell -noprofile -command 'Write-Output' "\"don't\""
```

See https://github.com/PowerShell/PowerShell/issues/4024#issuecomment-312267611 for more.
