### ISSUE TITLE
New-TemporaryFile should throw terminating error

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#4634]
As part of PR 4612, it was discussed [here](https://github.com/PowerShell/PowerShell/pull/4612#discussion_r134333394) that New-TemporaryFile should throw a terminating error (instead of a non-terminating one). Everyone was clear on the expected behaviour but the issue is that this change would be a breaking change in behaviour.

**Comment by raghav710** [comment]
Is there any clarity/decision taken on this now?

**Comment by bergmeister** [comment]
It was originally pending on PR 4612 that is still open but not active any more (due to the team being more busy before the release I did not want to push back on this minor item and PR before the release).
Can you please describe why this is important to you so that we can understand the situation?

**Comment by iSazonov** [comment]
I opened https://github.com/dotnet/corefx/issues/24001 to get the API in CoreFX.
