### ISSUE TITLE
Pester testing guideline for tests against thrown errors

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PowerShell#4635]
As part of PR 4612, it was found that the current guideline [here](https://github.com/PowerShell/PowerShell/blob/68bcd4b5284bb169c52a570afbfdd1bb70d0de10/docs/testing-guidelines/WritingPesterTests.md) recommends this approach
```
It "Get-Item on a nonexisting file should have error PathNotFound" {
    try
    {
        get-item "ThisFileCannotPossiblyExist" -ErrorAction Stop
        throw "No Exception!"
    }
    catch
    {
        $_.FullyQualifiedErrorId | should be "PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand"
    }
}
```

However, @iSazonov suggests [here](https://github.com/PowerShell/PowerShell/pull/4612#discussion_r134120245) that the guideline should be updated to this pattern:
```
{ get-item  "ThisFileCannotPossiblyExist" -ErrorAction Stop } | ShouldBeErrorId "PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand"
```

**Comment by SteveL-MSFT** [comment]
Current recommendation is to use `ShouldBeErrorId`, I'll submit a PR to update the guidance
