### ISSUE TITLE
Push-Location should generate a terminating error, not a non-terminating one, when passed an invalid/non-existent location

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4636]
<sup>Related: #4634</sup>

Based on the official cmdlet error-reporting guidelines, (statement)-_terminating_ errors should be reported in the following situations: "Cmdlets that can accept only 0-1 input objects and generate only 0-1 output objects should treat errors as terminating errors and generate terminating exceptions." - https://msdn.microsoft.com/en-us/library/ms714412%28v=vs.85%29.aspx  

Therefore, `Push-Location`, which, only accepts 1 input and produces no output, should generate a (statement-)_terminating_ error in case of inability to change to the specified location.

More generally, it's worth examining _all_ core cmdlets with respect to whether they're playing by the official error-reporting rules. In _Windows PowerShell_, there's at least one cmdlet that, based on its documented behavior, claims to report a (statement)-terminating error in a specific scenario: `Resume-Job`,  which applies to _workflows_ only, supposedly generates a terminating error when passed a non-workflow job object, but currently doesn't.

Steps to reproduce
------------------

```powershell
try { Push-Location /NoSuch } catch { 'no such dir.' }
```

Expected behavior
-----------------

The Try / Catch handler should catch the terminating error.

```none
no such dir
```

Actual behavior
---------------

The Try / Catch handler is ignored, and a non-terminating error is issued.

```none
Push-Location : Cannot find path '/NoSuch' because it does not exist
...
```

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by markekraus** [comment]
I disagree. `-Path` can be accepted via the pipeline and this creates the ability to accept multiple Paths instead of just 1.  In a scenario where you where you needed to so something like this

```powershell
'c:\temp', 'c:\' | Push-Location -PassThru | Invoke-SomeCommand 
```

One would not want a terminating error from push location to break the pipeline. 

In this case, I think perhaps changing `-Path` and `-LiteralPath`  to accept an arrays might be a better approach to make the parameters consistent between named parameter and pipeline modes.

**Comment by mklement0** [comment]
@markekraus:

Thanks - you are correct; I hadn't considered this use of `Push-Location`. I'm closing this.

> In this case, I think perhaps changing -Path and -LiteralPath to accept an arrays might be a better approach to make the parameters consistent between named parameter and pipeline modes.

Actually, this one of those rare case where a _scalar_ pipeline-binding parameter does make sense, given that something like `Push-Location -LiteralPath 'c:\temp', 'c:\'` wouldn't make sense.

Generally, though, we unfortunately have many cmdlets where the pipeline-binding `-InputObject` parameter indeed should be an array, but currently isn't (e.g., `Export-Csv`) - see #4242.

**Comment by mklement0** [comment]
P.S.:  A pitfall regarding your sample command that I wasn't initially aware of:

Since the current location is a session-global setting, whatever path `Push-Location `ends up changing to last in the pipeline remains as the session's current location after the pipeline has run.

**Comment by markekraus** [comment]
Correct. In cases like that you may be building a stack against candidate paths, performing an action and then reversing the stack. might also use a named stack `-StackName`

```powershell
'c:\temp', 'c:\', 'c:\noloexisto\' | Push-Location -PassThru -StackName 'Test' | Invoke-SomeCommand

$Processedpaths = Get-Location -StackName 'Test'
```

**Comment by mklement0** [comment]
Thanks, though note that `$ProcessedPaths` will not contain _all the paths sent through the pipeline_, but instead the previous working location plus all paths sent through the pipeline _except the last_.

Also note that outputs a `[System.Management.Automation.PathInfoStack]` _scalar_, not an array - which I personally think is unfortunate - see #4642.

Allow me this little tangent (I wrote it up for my own notes; do tell me if I got something wrong):

If you could guarantee that the `Test` stack doesn't exist / is empty before the pipeline runs, you could use `Set-Location (Get-Location -StackName Test).ToArray()[-1]` to return to the previous location after.
Ensuring an empty / non-existent `Test` stack beforehand is quite cumbersome, however, because there's no direct test for whether a stack  with a given name exists, and if it does exist, calling `.Clear()` on the  `[System.Management.Automation.PathInfoStack]` instance returned has no effect (except on the object returned) - see #4643.

Thus, to avoid the pitfall I mentioned, it's probably easiest to save and restore the current location:

```powershell
Push-Location -StackName temp # Save current location using temp. stack.

'/', '/tmp' | Push-Location -PassThru | % { "running in $PWD" }

Pop-Location -StackName temp # Restore previous location from temp. stack.
```

Of course, if the locations changed to in the pipeline don't need to be remembered, using `Set-Location` instead enables a simpler solution (assuming that _no_ command in the pipeline calls `Push-Location` or `Pop-Location`):

```powershell
Push-Location # Save current location using the unnamed (default) stack.

'/', '/tmp' | Set-Location -PassThru | % { "running in $PWD" }

Pop-Location # Restore previous location.
```

Lastly, using a custom variable to save and restore the location is, of course, also an option:

```powershell
$prevLoc = $PWD

'/', '/tmp' | Set-Location -PassThru | % { "running in $PWD" }

Set-Location $prevLoc
```
