### ISSUE TITLE
Add support for multiple response headers with the same name from HttpListener

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4639]
Multiple response header support was added in #4494 but the HttpListener concatenates multiple headers with the same name in Linux/macOS instead of returning multiple lines with the same header name.

In Windows:
```
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain
Server: Microsoft-HTTPAPI/2.0
X-Fake-Header: testvalue01
X-Fake-Header: testvalue02
Date: Tue, 22 Aug 2017 09:49:37 GMT
```

In Linux/macOS:
```
HTTP/1.1 200 OK
X-Fake-Header: testvalue01, testvalue02
Server: Microsoft-NetCore/2.0
Date: Tue, 22 Aug 2017 09:18:18 GMT
Content-Type: text/plain
Content-Length: 2
```

This results in a false failure of the `Verifies Invoke-WebRequest Supports Multiple response headers with same name` test on Linux/macOS.

We should find a cross-platform method of returning a multiple header response. (Possibly with the new listener inf #4622)

**Comment by markekraus** [comment]
@iSazonov this issue is still outstanding. We still do not have a test in place for Linux or macOS to ensure the multiple headers feature is working. The merged PR referenced is to address the nightly build errors the tests were causing.

**Comment by iSazonov** [comment]
Ah, sorry - I reopen the Issue.

**Comment by markekraus** [comment]
I think that WebListener supports this properly on all platforms. since we are moving all the tests to WebListener and off of HttpListener, I will come back to this when that transition is complete.
