### ISSUE TITLE
Pull Request Tests with [feature] tag in commits should report failed in CI when "Feature" tests fail

### ISSUE THREAD

**Issue by markekraus** [PowerShell/PowerShell#4641]
I have had 2 pull requests merged where I missed the failing tests due to Travis CI reporting the build passing when tests actually failed. It is partially my fault for not being completely attentive to the test results, but in my defense there are a very large number of feature tests run and it is easy to lose track in the sea of results.

IMO, the CI should report the build failed when when the [feature] tag is present in the commit and any "Feature" test fails. This will make it easier to spot when something goes wrong.

Example PR #4494 Travis CI Passing with failed test https://travis-ci.org/PowerShell/PowerShell/jobs/266123025

**Comment by TravisEz13** [comment]
This shouldn't be specific to the feature tag.  It indicates there is some bug in `Test-PSPesterResults` in build.psm1.  I tried a simple repro locally, and couldn't repro the issue.

**Comment by markekraus** [comment]
I had a really fun one #4622. https://travis-ci.org/PowerShell/PowerShell/jobs/266586350#L8280 That one was an unhandled exception in a Job, that killed the calling process, and the pester process, and the test "passed". That's when I started looking very closely at the test results.

**Comment by TravisEz13** [comment]
[This](https://travis-ci.org/PowerShell/PowerShell/jobs/266586350#L8280) is interesting... pester must write the result as it is going because `Test-PSPesterResults` will fail if the results file is missing.  

I think we will have to switch to running `Invoke-Pester` with `-PassThru`  and use those results to determine if the tests passed or failed.

**Comment by TravisEz13** [comment]
I found one issue... `Start-PSPester` is not checking the exit code from powershell.
