### ISSUE TITLE
Managing location stacks via the *-Location cmdlets lacks ability to clear stacks

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4643]
Location history for use with `Push-Location` and `Pop-Location` can be kept in separate history _stacks_, if desired.

These stacks cannot be managed directly; they are indirectly managed via the `*-Location` cmdlets.

* You indirectly _create_ a stack with `Push-Location -StackName <name>`.
* Once created, further locations can be pushed and popped.
* `Set-Location -StackName <name>` can be used to make a given stack the current stack.
* `Get-Location -Stack [-StackName <name>]` returns the locations currently stored in the active / given stack.

However, there is currently no way to _clear_ a stack (other than by popping off all items through repeated `Pop-Location` calls).

Clearing a stack is desirable if you want to make sure that it is _empty_ before you use it - either to reuse a previously used stack or in cases where previously executed code may have created a stack by the same name.

Secondarily,

* there's also no way to _delete_ a stack, although, arguably, the ability to _clear_ stacks is enough.

* there's no _test_ whether a stack with a given name _exists_, other than letting `Get-Location -StackName <name>` _fail_; arguably, rather than worrying about explicit existence / deletion of stacks, letting `Get-Location -Stack -StackName <name>` return _nothing_ (the null collection) for a nonexistent stack is preferable, given that `Get-Location -Stack` with the _unnamed_ stack already works that way.

As an aside: While calling the `.Clear()` _method_ on the stack object that `Get-Location -Stack` returns may seem like a workaround for the current inability to clear a stack using cmdlets, it doesn't actually work (only clears the object returned, not the actual stack); more importantly, `Get-Location -Stack` should arguably return an array of location paths rather than a scalar stack 
object - see  ##4642.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5
```

**Comment by IAmIlliest** [comment]
I see this has been closed, but is there actually some way to clear a given stack?
