### ISSUE TITLE
ValueFromRemainingArguments parameters in compiled cmdlets such as Write-Host break a hashtable argument into key-value pairs

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell#4647]
Closely related to #2035.

It seems to me that, again, advanced functions behave correctly, while compiled cmdlets do not.

Hashtables are generally treated as _scalars_ in PowerShell.

Therefore, when passing a hashtable as an argument, it should bind _as a whole_.

Using the example of _cmdlet_ `Write-Host`, which applies `.ToString()` to each of its arguments, and a seemingly analogous `Write-Host2` _advanced function_:

Steps to reproduce
------------------

```powershell
# Call Write-Host with a hashtable.
Write-Host @{ one=1; two = 2 }
# Define an analogous advanced function and call it the same way.
Function Write-Host2 { param([parameter(ValueFromRemainingArguments)] $Object) $Object[0].ToString() }
Write-Host2  @{ one=1; two = 2 }
```

Expected behavior
-----------------

```none
System.Collections.Hashtable
System.Collections.Hashtable
```

Actual behavior
---------------

```none
System.Collections.DictionaryEntry System.Collections.DictionaryEntry
System.Collections.Hashtable
```

Cmdlet `Write-Host` bound the hashtable _entries_ (key-value pairs) _individually_ to the ValueFromRemainingArguments parameter.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.5 on macOS 10.12.6
PowerShell Core v6.0.0-beta.5 on Ubuntu 16.04.3 LTS
PowerShell Core v6.0.0-beta.5 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
Windows PowerShell v5.1.15063.483 on Microsoft Windows 10 Pro (64-bit; v10.0.15063)
```

**Comment by PetSerAl** [comment]
It is not binding problem. `Write-Host` itself [enumerate every IEnumerable](https://github.com/PowerShell/PowerShell/blob/master@%7B2017-09-26%7D/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteConsoleCmdlet.cs#L87-L106), when it generate string for printing.

**Comment by mklement0** [comment]
Good find, @PetSerAl, thanks - closing this.
