### ISSUE TITLE
Missing Dependencies Being Reported for PS 6 Beta5 but not on PS 6 Alpha

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/PowerShell#4649]
I'm running into an issue on 2008 R2 running our Catch Unit tests on PS 6 Beta 5. When I ran a dependency check on our unit test EXE file through PS Beta 5, it seems that the system cannot find the MI.dll nor some of its dependencies. The test file runs fine on the Alpha version of PS 6 and when I ran a dependency check on the unit test EXE from PS Alpha, it did not show the same missing dependencies. When I searched for the reported missing files I was able to find them in both the Alpha folder and the Beta folder. Below is the output from Dependency Walker. The left image is from Alpha, the right image is from Beta:

![image](https://user-images.githubusercontent.com/18012846/29593082-1254b8a4-875d-11e7-9f26-ce095398f1a3.png)

**Comment by SteveL-MSFT** [comment]
This appears to be fixed with the unified pkg and beta.7
