### ISSUE TITLE
Test-Connection doesn't function

### ISSUE THREAD

**Issue by BrendanHere** [PowerShell/PowerShell#4651]
Hi. I've never submitted a bug so here goes, if this is in the wrong place, or has already been reported, please advise. I have searched everywhere for it.

Test-connection doesn't work on Windows 10, nor Windows 7
Each OS returns a different error message.

Steps to reproduce
------------------

Test-Connection -Count 3 -ComputerName "Server1", "Server2", Server3" | select-object Address, IPV4Address, ResponseTime | ft -AutoSize

```
Expected behavior
-----------------

`Address                     IPV4Address                  ResponseTime
Server1                      192.168.1.1                    0
Server2                      192.168.1.2                    85
Server3                      192.168.1.3                    0

```

Actual behavior
---------------

Windows 7:  
test-connection : Unable to find an entry point named 'GetCurrentThread' in
DLL 'api-ms-win-core-processthreads-l1-1-2.dll'.
At line:1 char:1
+ test-connection -count 1 -ComputerName "pbtpmgt04"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Test-Connection], EntryPointN
   otFoundException
    + FullyQualifiedErrorId : System.EntryPointNotFoundException,Microsoft.Pow
   erShell.Commands.TestConnectionCommand

PS C:\Program Files\PowerShell\6.0.0-beta.5>
```
Windows 10:

Test-Connection : The client cannot connect to the destination specified in the request. Verify that the service on
the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service
running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following
command on the destination to analyze and configure the WinRM service: "winrm quickconfig".
At line:1 char:1
+ Test-Connection -Count 3 -ComputerName "Server1", "Server2. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Test-Connection], CimException
    + FullyQualifiedErrorId : TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand

Environment data
----------------

<!-- provide the output of $PSVersionTable -->
Windows 7: 
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> $PSVersionTable

```
Windows 10: 
PS C:\Program Files\PowerShell\6.0.0-beta.5>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.5
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Thanks.

**Comment by SteveL-MSFT** [comment]
Win7 issue is https://github.com/PowerShell/PowerShell/issues/4649

**Comment by SteveL-MSFT** [comment]
Not able to repro your win10 issue.  Moving out of HighPriority list as Win7 issue should be resolved with the other issue.

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShell/issues/2777
