### ISSUE TITLE
Release beta.6

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell#4652]
From:  https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/releasing.md

- [x] Create a branch named `release` in `PowerShell/PowerShell` repository.
   All release related changes should happen in this branch.
- [x] Prepare packages
   - [x]  [Build release packages](#building-packages).
   - [x]  Sign the MSI packages and DEB/RPM packages.
   - [x]  Install and verify the packages.
- [x]  Update documentation, scripts and Dockerfiles
   - [x]  Summarize the change log for the release. It should be reviewed by PM(s) to make it more user-friendly.
   - [x]  Update [CHANGELOG.md](../../CHANGELOG.md) with the finalized change log draft.
   - [x]  Update other documents and scripts to use the new package names and links.
- [ ]  Verify the release Dockerfiles.
- [x]  [Create NuGet packages](#nuget-packages) and publish them to [powershell-core feed][ps-core-feed].
- [x]  [Create the release tag](#release-tag) and push the tag to `PowerShell/PowerShell` repository.
- [x]  Create the draft and publish the release in Github.
- [x]  Merge the `release` branch to `master` and delete the `release` branch.
- [x]  Publish Linux packages to Microsoft YUM/APT repositories.
- [ ]  Trigger the release docker builds for Linux and Windows container images.
   - [ ]  Linux: push a branch named `docker` to `powershell/powershell` repository to trigger the build at [powershell docker hub](https://hub.docker.com/r/microsoft/powershell/builds/).
     Delete the `docker` branch once the builds succeed.
   - [ ]  Windows: queue a new build in `PowerShell Windows Docker Build` on VSTS.
- [ ]  Verify the generated docker container images.
- [x]  [Update the homebrew formula](#homebrew) for the OSX package.
   This task usually will be taken care of by the community,
   so we can wait for one day or two and see if the homebrew formula has already been updated,
   and only do the update if it hasn't.
- [x] Open the next release milestone.

**Comment by daxian-dbw** [comment]
@mirichmo and @TravisEz13, please check the above tasks that have been finished. Feel free to close this once all tasks are checked.

**Comment by daxian-dbw** [comment]
I have verified the beta.5 ubuntu packages and centos package are available in Microsoft YUM/APT repository.

**Comment by daxian-dbw** [comment]
@TravisEz13 I assign this bug to you, so once you finish the docker builds, you can close it.
